### ISSUE TITLE
Podman commands not working on WSL2 based Ubuntu distribution

### ISSUE THREAD

**Issue by slohana** [containers/podman#10027]
/kind bug

**Description**
I have installed Podman on Ubuntu distribution that has been configured using WSL2 on Windows 10 laptop. Trying to execute podman commands using admin as well as root user but it fails. Podman options and flagged commands are working fine, however, couldn't find any way to run normal podman commands. What could be the reason for this behavior? Please suggest a solution. 

Pls refer to the below example:

**slohana@slohana-laptop:~$ #Below commands DON'T work**
**slohana@slohana-laptop:~$ podman login**
cannot clone: Invalid argument
Error: cannot re-exec process
**slohana@slohana-laptop:~$ podman version**
cannot clone: Invalid argument
Error: cannot re-exec process
**slohana@slohana-laptop:~$ #Below commands work**
**slohana@slohana-laptop:~$ podman -v**
podman version 3.0.1
**slohana@slohana-laptop:~$ podman --version**
podman version 3.0.1
**slohana@slohana-laptop:~$ podman help**
Manage pods, containers and images

Usage:
  podman [options] [command]

Available Commands:
  attach      Attach to a running container
  auto-update Auto update containers according to their auto-update policy
  build       Build an image using instructions from Containerfiles
.
.
.
_Trimmed command output_

**Steps to reproduce the issue:**

1. Installation of podman has been done using commands mention in this link. No configurations for rootless execution have been done other than the execution of the given commands.
https://www.redhat.com/sysadmin/podman-windows-wsl2

**Output of `podman version`:**
```
cannot clone: Invalid argument
Error: cannot re-exec process
```

**Output of `podman info --debug`:**
```
cannot clone: Invalid argument
Error: cannot re-exec process
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**
```
slohana@slohana-laptop:~$ rpm -q podman
Command 'rpm' not found, but can be installed with:
sudo apt install rpm

slohana@slohana-laptop:~$ apt list podman
Listing... Done
podman/unknown,now 100:3.0.1-2 amd64 [installed]
podman/unknown 100:3.0.1-2 arm64
podman/unknown 100:3.0.1-2 armhf
podman/unknown 100:3.0.1-2 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**
Believe Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
WSL2 based Ubuntu

**Using sudo as well as directly the root user doesn't work.**
```
slohana@slohana-laptop:~$ sudo podman version
Error: failed to mount overlay for metacopy check with "nodev,metacopy=on" options: invalid argument
```

**Comment by rhatdan** [comment]
@slohana Any chance you could check against main by building podman yourself.  We are about to release podman 3.1.1 which has fixes for overlay mounts on certain systems.

**Comment by slohana** [comment]
@rhatdan Thanks for the reply. Sorry, I am new to Podman as well as Linux. Please help with more details about how to check against main by building the podman myself. Thanks.

**Comment by slohana** [comment]
@community - The problem remains the same, pls suggest a way out. Thanks.

**Comment by vrothberg** [comment]
> Error: failed to mount overlay for metacopy check with "nodev,metacopy=on" options: invalid argument

A number of fixes went into c/storage to fix these symptoms, so I am optimistic that it works with Podman v3.2.x.

**Comment by ruckc** [comment]
@vrothberg - wsl2 / ubuntu 20.04.3 / podman 3.3.1, still get this.

```sh
ruckc@DESKTOP:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
ruckc@DESKTOP:~$ podman info -D
WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers
cannot clone: Invalid argument
Error: cannot re-exec process
```

**Comment by mheon** [comment]
Your error message seems unrelated to the original bug reported, please file a new issue.
