### ISSUE TITLE
Therer is no Centos 7 rpm for 3.1.0

### ISSUE THREAD

**Issue by bulanovk** [containers/podman#10023]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Therer is no RPM build for centos 7.

**Comment by afbjorklund** [comment]
See https://podman.io/blogs/2021/03/02/podman-support-for-older-distros.html

> Podman 3.0 will be the last major build on CentOS 7, Debian 10 and Ubuntu 18.04. After this release, we recommend users who need the latest versions of Podman to move to newer versions of their Linux distribution.

**Comment by vrothberg** [comment]
Thanks, @afbjorklund.

If you need more recent versions of Podman, please update to a more recent version of Cent OS.

**Comment by afbjorklund** [comment]
I suppose the other obvious solution would be to stay on podman 3.0.x, when you can't upgrade OS
