### ISSUE TITLE
podman-remote build: can fail but exit 0 (success)

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#10029]
[ Forked from #9751 ]

podman-remote build sometimes fails but returns exit status 0. Trivial reproducer (assumes podman system service running elsewhere):
```console
$ cat Containerfile
FROM quay.io/libpod/nosuchimage:nosuchtag
RUN echo hi
$ while :;do ../bin/podman-remote build -t build_test --pull-never . && break;done
...runs for a minute or two, then

STEP 1: FROM quay.io/libpod/nosuchimage:nosuchtag
Error: error creating build container: pull policy is "never" but "quay.io/libpod/nosuchimage:nosuchtag" could not be found locally

STEP 1: FROM quay.io/libpod/nosuchimage:nosuchtag
$ <--- back to prompt, with exit status 0. This should never happen.
```
master @ 14ec3a64d, also in podman-3.1.0-3.fc33

**Comment by edsantiago** [comment]
Flake. The above reproducer works fine for the first 50-100 iterations, it just fails randomly. (Same in CI).

**Comment by mheon** [comment]
Alright, it's a race then. Damn, I was hoping this one was going to be simple.

**Comment by rhatdan** [comment]
I might have a fix.

**Comment by edsantiago** [comment]
@rhatdan I'm sorry... no-go. It takes a lot longer than before (30 seconds instead of about 10), but the race is still there.
