### ISSUE TITLE
Changed host network configuration is not reflected to containers created with `--network host`

### ISSUE THREAD

**Issue by StayPirate** [containers/podman#10026]
/kind bug

**Description**

If I create a container with `--network host` the host's file `/etc/resolv.conf` is copied within the container. When I later connect the host to a VPN which reconfigure the resolvers, by passing new DNS servers via DHCP, these changes are not reflected inside the container.

**Steps to reproduce the issue:**

1. create a container with `--network host`

2. change your host `/etc/resolv.conf`

3. From the container, try to resolve a domain name which is only resolvable with the new configured DNS servers.

**Describe the results you received:**

This prevent me to access new available network resources from the container.

**Describe the results you expected:**

I'd like to continue to use the container as I would do from the host system after I connected the host to the VPN.

**Output of `podman version`:**

```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.16
Git Commit:   c640670e85c4aaaff92741691d6a854a90229d8d
Built:        Sun Feb 21 16:29:46 2021
OS/Arch:      linux/amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Comment by Luap99** [comment]
I think the problem is that we copy the content in /etc/resolv.conf before we bind mount it in the container. I think when --network host is used we can directly bind mount /etc/resolv.conf and /etc/hosts.

@mheon @baude WDYT?

**Comment by rhatdan** [comment]
I believe we copied the behaviour of Docker for this.  One issue with not copying the contents, is the contents become non writable from within the container. Since you don't want the container to modify the hosts resolv.conf.

**Comment by Luap99** [comment]
@rhatdan You are right I just tested this with docker.

**Comment by mheon** [comment]
Concur, this is a Docker compat measure.

For folks who don't want this, we added the `--dns=none` flag to disable Podman's management of /etc/resolv.conf, then you can bind-mount in the original from the host.

**Comment by alitvak69** [comment]
Will application in the container react to a changed resolve.conf file? Some apps at least from my experience read resolver info only   once on start.

**Comment by rhatdan** [comment]
If you do a -v /etc/resolv.conf:/etc/resolv.conf it should work as long as the resolver file is not renamed and replaced.

There is no guarantee that any application will reread the /etc/resolv.conf ever.

**Comment by alitvak69** [comment]
OK to close.

**Comment by StayPirate** [comment]
Unfortunately I had not spare time to follow this up until today. I appreciated all your suggestions and tried them out, but without any luck.

Even if I use `--dns=none` and `-v /etc/resolv.conf:/etc/resolv.conf`, `/etc/resolv.conf` inside the container does not reflect the changes I make to the host's one. Here what I did:

```bash
host > cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 192.168.1.1
```
```bash
host > podman container run --rm -ti --dns=none -v /etc/resolv.conf:/etc/resolv.conf alpine:latest sh
guest > cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 192.168.1.1
```
Then I change the `/etc/resolv.conf` in the host.
```bash
host > cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 10.160.0.1
nameserver 10.160.2.88
nameserver 2620:113:80c0:8080:10:160:2:88
# NOTE: the libc resolver may not support more than 3 nameservers.
# The nameservers listed below may not be recognized.
nameserver 2620:113:80c0:8080:10:160:0:1
nameserver 192.168.1.1
```
I then check again the file from the container, expecting to see the above changes reflected:
```bash
guest > cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 192.168.1.1
```
But that's not the case. Am I doing something wrong here or have I hit a bug?
