### ISSUE TITLE
Typo in doc

### ISSUE THREAD

**Issue by adrian5** [containers/podman#10042]
In the [introduction](https://github.com/containers/podman/blob/master/docs/source/Introduction.rst) I think there's a missing word.

> This single file often contains all the instructions needed to build **the new** and can easily be shared with others publicly using tools like GitHub.

**Comment by zhangguanzhang** [comment]
Could you open a pr for this？the pr's title should startwith `[CI:DOCS]`

**Comment by adrian5** [comment]
Afaik I have to sign podman PRs with my real name and email, which I don't want to do.

**Comment by TomSweeneyRedHat** [comment]
Just spun up 10070 to address it.  @adrian5 thanks for the eagle eye and the issue!

**Comment by adrian5** [comment]
Just thinking out loud, but would it be possible to file a PR (think simple doc-fixes like this) but waiver my rights or something like that? I.e. an open/anonymous contribution that belongs to RedHat from there on? Or is that simply not viable within the licensing structure?

**Comment by rhatdan** [comment]
The PR's/Code does not belong to Red Hat. it basically belongs to the open source world.  By signing you are allowing you code to follow the code's license.
