### ISSUE TITLE
[I18N]DO you need translation for Chinese ,i can help you.

### ISSUE THREAD

**Issue by 2926295173** [containers/podman#10048]

**Comment by vrothberg** [comment]
Thanks for offering help, @2926295173!

@baude @rhatdan @fatherlinux PTAL

**Comment by pendulm** [comment]
I think it hard to maintain translation for a opensource project.  It alway outdated and inaccurate  over time, especially the code team can't  deal with it.

**Comment by 2926295173** [comment]
> I think it hard to maintain translation for a opensource project.  It alway outdated and inaccurate  over time, especially the code team can't  deal with it.

我挺喜欢这个项目的，所以想翻译个`readme.md`这个文档，与时俱进应该不难，而不是去翻译整个程序，另外，官网是我的下一个目标，程序的话应该我不去动的，有一点帮助是一点帮助吧。

**Comment by 2926295173** [comment]
I will try.

**Comment by rhatdan** [comment]
Fedora project and other distros support translations, So it would be better to work there.

**Comment by rhatdan** [comment]
https://fedoraproject.org/wiki/L10N
