### ISSUE TITLE
rootless podman 3.1.0-3 load fails for image built with docker which contains httpd

### ISSUE THREAD

**Issue by adelton** [containers/podman#10049]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

With rootless podman 3.1.0-3, loading image built with docker now fails if the image contains Fedora httpd package.

**Steps to reproduce the issue:**

1. Have Dockerfile.fedora-33:
```
FROM registry.fedoraproject.org/fedora:33
RUN dnf install -y --setopt=install_weak_deps=False httpd
```
2. Build image with docker:
```
docker build -t local/image -f Dockerfile.fedora-33 .
```
3. Save the image to a file:
```
docker save local/image > image.tar
```
4. Load the image with rootless image:
```
podman load < image.tar
```

**Describe the results you received:**

```
Getting image source signatures
Copying blob sha256:c8723788d73992805685b6e3e5beead1e5c59d71d34b18719c1c5e230e73a88b
Copying blob sha256:d9e1d1e08de26f234a83c6c737827884dd15c68c80714a5a973d245ed456f7a1
Copying config sha256:ddeba5347998b8e561407893a2b10c47cc6cd9455fde95e74ea8655471db3de7
Writing manifest to image destination
Storing signatures
  Error processing tar file(exit status 1): operation not permitted
Getting image source signatures
Copying blob sha256:c8723788d73992805685b6e3e5beead1e5c59d71d34b18719c1c5e230e73a88b
Copying blob sha256:d9e1d1e08de26f234a83c6c737827884dd15c68c80714a5a973d245ed456f7a1
Copying config sha256:ddeba5347998b8e561407893a2b10c47cc6cd9455fde95e74ea8655471db3de7
Writing manifest to image destination
Storing signatures
  Error processing tar file(exit status 1): operation not permitted
  open /var/tmp/podman857410420/manifest.json: not a directory
  open /var/tmp/podman857410420/index.json: not a directory
Error: error pulling image: payload does not match any of the supported image formats (oci-archive, oci-dir, docker-archive, docker-dir)
```

**Describe the results you expected:**

```
Getting image source signatures
Copying blob sha256:d9e1d1e08de26f234a83c6c737827884dd15c68c80714a5a973d245ed456f7a1
Copying blob sha256:f0397af76ccccc7bea350d65d589ec3f2c615761bd1fb509a9e3015f8e8910bc
Copying config sha256:5a947964a4fedc3375645941d73d45867bca4e4a73f9c8a8c9178b78809885ca
Writing manifest to image destination
Storing signatures
Loaded image(s): localhost/local/image:latest
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I've experienced the problem on Travis CI and GitHub Actions Ubuntus, here's a reproducer on GitHub Actions:
* https://github.com/adelton/freeipa-container/runs/2360157891

It is a regression against podman 3.0.1-2 where the same steps pass:
* https://github.com/adelton/freeipa-container/runs/2360162565

**Output of `podman version`:**

Sorry, I did not run that one on those GitHub Actions jobs, but the version is 3.1.0-3.

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.20.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 2
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: fv-az177-148
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 121
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.4.0-1043-azure
  linkmode: dynamic
  memFree: 4154982400
  memTotal: 7292149760
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.18.1-45fb5-dirty
      commit: 7931a1eab0590eff4041c1f74e2844b297c31cea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /tmp/podman-run-1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 2m 48.25s
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/runner/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/runner/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /tmp/podman-run-1001/containers
  volumePath: /home/runner/.local/share/containers/storage/volumes
version:
  APIVersion: 3.1.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 3.1.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
Listing...
podman/unknown,now 100:3.1.0-3 amd64 [installed]
podman/unknown 100:3.1.0-3 arm64
podman/unknown 100:3.1.0-3 armhf
podman/unknown 100:3.1.0-3 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes to the latest podman package available in the repositories; No to checking the troubleshooting guide.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I see this suddenly in GitHub Actions, the problem is limited to rootless containers. Two days ago everything passed (https://github.com/freeipa/freeipa-container/actions/runs/747032538), today with 3.1.0 rootless fails (https://github.com/freeipa/freeipa-container/actions/runs/754364292).

I was not able to reproduce on Fedora 33 with podman-3.1.0-3.fc33.x86_64.

Installing other package (I tried it with zsh) does not show the problem.

**Comment by adelton** [comment]
I thought that perhaps the problem is with file capabilities on /usr/sbin/suexec that httpd brings but even if I do
```
RUN dnf install -y --setopt=install_weak_deps=False httpd && rm -f /usr/sbin/suexec
```
in the Dockerfile, `podman load` still fails.

**Comment by rhatdan** [comment]
If you build with Podman does it work?
@nalind @giuseppe Ideas?

**Comment by adelton** [comment]
@rhatdan, good question.

Attempting to run rootless `podman build` in GitHub Actions Ubuntu environment fails with
```
STEP 1: FROM registry.fedoraproject.org/fedora:33
Getting image source signatures
Copying blob sha256:157ab801145489f145f258148bd135102a3294e420f1859a39e824e7cda56b2f
Copying config sha256:9f2a56037643a68ea81711a8eeb4501428eefd40b000c866ad9745a581c0464d
Writing manifest to image destination
Storing signatures
time="2021-04-16T11:53:03Z" level=error msg="error unmounting /home/runner/.local/share/containers/storage/overlay/781ca68fff15020c090b2b37d59bfb63e7018eeeaad718dab8e9309afece937b/merged: invalid argument"
Error: error mounting new container: error mounting build container "41bcce718d96add49663a05adae8a50558f4d4c517ee0692132e307ce8709673": error creating overlay mount to /home/runner/.local/share/containers/storage/overlay/781ca68fff15020c090b2b37d59bfb63e7018eeeaad718dab8e9309afece937b/merged, mount_data=",lowerdir=/home/runner/.local/share/containers/storage/overlay/l/YVYAFOL4CLGWMP6SYMAWEMWOMC,upperdir=/home/runner/.local/share/containers/storage/overlay/781ca68fff15020c090b2b37d59bfb63e7018eeeaad718dab8e9309afece937b/diff,workdir=/home/runner/.local/share/containers/storage/overlay/781ca68fff15020c090b2b37d59bfb63e7018eeeaad718dab8e9309afece937b/work,userxattr": invalid argument
```
at https://github.com/adelton/freeipa-container/runs/2361954818 with 3.1.0-3.

It works with 3.0.1-2: https://github.com/adelton/freeipa-container/runs/2361973062.

Does it look likely related, or a separate issue?

**Comment by rhatdan** [comment]
That is a separate issue.

Try it with podman build --format docker ...

**Comment by adelton** [comment]
I've filed https://github.com/containers/podman/issues/10059 for the build issue.

Running with `--format docker` did not help:
* https://github.com/adelton/freeipa-container/runs/2364153959

**Comment by nalind** [comment]
That environment summary lists kernel 5.4, so the `userxattr` option wouldn't have been recognized (it was added in 5.11), which should explain the "error mounting...: invalid argument" errors when they pop up.

**Comment by adelton** [comment]
Based on https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md and https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md, both GitHub Actions Ubuntu 18.04 and Ubuntu 20.04 environments use kernel version 5.4.0-1043-azure.

So if podman 3.1.0 assumes / relies on something newer, it would be disqualified from GitHub Action workers.

**Comment by nalind** [comment]
3.1.0 uses storage 1.28.1, which had this problem.  The problem should have been fixed in 1.29.0, which is used on the development branch.

**Comment by mheon** [comment]
I bumped 3.1.1 to v1.29.0, so the next release should resolve that.

**Comment by adelton** [comment]
@mheon, great, thanks.

I see https://github.com/containers/podman/releases/tag/v3.1.1 was released -- what is the timeline to get it built to https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/.

**Comment by adelton** [comment]
For the record, podman 3.1.2-1 in https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ seems to have fixed the problem for me.
