### ISSUE TITLE
API /containers/stats does not support query parameter "one-shot"

### ISSUE THREAD

**Issue by jwhonce** [containers/podman#10058]
For API endpoint /containers/stats, to be compatible the query parameter  "one-shot" and associated logic should be added.

https://docs.docker.com/engine/api/v1.41/#operation/ContainerStats

See https://github.com/containers/podman/pull/9126

**Comment by cdoern** [comment]
@rhatdan I might be able to figure this one out. I found the proper files to edit, just might take me a bit to orient myself as to what is going on.

**Comment by cdoern** [comment]
see #10517 for PR regarding this issue.
