### ISSUE TITLE
In a ROOTLESS podman setup, how to communicate between containers in different pods

### ISSUE THREAD

**Issue by nmvega** [containers/podman#10054]
Hello Friends:

I read all I could find, but documentation on this scenario is scant or unclear for `podman`. I have the following (contrived) `ROOTLESS` `podman` setup:

 - pod-1 name: `pod1`
   
     Container names in `pod1`:

     - `p1c1`  -- This is also it's assigned `hostname` within `pod1`
     - `p1c2`  -- This is also it's assigned `hostname` within `pod1`
     - `p1c3`  -- This is also it's assigned `hostname` within `pod1`

 - pod-2 name: `pod2`
   
     Container names in `pod2`:

     - `p2c1`  -- This is also it's assigned `hostname` within `pod2`
     - `p2c2`  -- This is also it's assigned `hostname` within `pod2`
     - `p2c3`  -- This is also it's assigned `hostname` within `pod2`

I keep certain containers in different `pods` specifically to avoid `port conflict`, and to manage containers as groups.

**QUESTION**:

Give the above topology, how do I communicate between, say, `p1c1` and `p2c1`? In other words, step-by-step, what `podman(1)` commands do I issue to collect the necessary `addressing information` for `pod1:p1c1` and `pod2:p2c1`, and then use that information to configure applications in them so they can communicate with one another?

Thank you in advance!

**Comment by eriksjolund** [comment]
The same question can also be found here:
https://stackoverflow.com/questions/67126730/in-a-rootless-podman-setup-how-to-communicate-between-containers-in-different-p

**Comment by nmvega** [comment]
@eriksjolund Yes that was my post. :grinning:
