### ISSUE TITLE
print api request and response information to the console when log-level=debug

### ISSUE THREAD

**Issue by brianwcook** [containers/podman#10053]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

In order to make troubleshooting easier it would be nice if podman would print api request and response information to the console when log-level=debug.  This should include include all headers including tokens, request methods, request uri, payloads, etc.  There should be enough to reconstruct the api calls using curl.  the 'oc' command from OpenShift does this very nicely when you add lots of -vvvvvvv's.

Since some of the payloads can be large, more granular options for verbosity could be implemented.  It's not so useful to get a tar file printed to my console, but I definitely want to be able to see the json of a manifest write operation.

**Steps to reproduce the issue:**

1. do something with podman that would initiate communication with a registry endpoint

2. add log-level=debug to cli

3. observe output and wish that it included api request and response information

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

podman version 3.0.1

**Additional environment details (AWS, VirtualBox, physical, etc.):**

fedora 33

**Comment by baude** [comment]
@jwhonce can you give the history here? I cannot quite remember it.

**Comment by jwhonce** [comment]
@baude We do this already on the service side for inbound API calls when started with `--log-level=debug`. @brianwcook mentions registry endpoint so I assume he wants c/images to do the same when making outbound calls to pull images etc. Buildah would also be a candidate if it making outbound calls not utilizing c/images.

/cc @vrothberg

**Comment by mheon** [comment]
This definitely seems worthwhile. We just added support for trace logging, and this is a good candidate.

**Comment by rhatdan** [comment]
Is there risk here of divulging secrets in logs?  Do we need to be careful?

**Comment by mheon** [comment]
Hm. If we use TRACE level, and add a warning to the manpage that Trace will print *everything*, even potentially privileged data - would that be OK?

**Comment by rhatdan** [comment]
Yes, I am fine with it printing in tracelevel.

**Comment by rhatdan** [comment]
@jwhonce any chance you can work on this?

**Comment by jwhonce** [comment]
@rhatdan Researching into how to implement this and still stream in and out of handler. Holding whole payload in memory seems wasteful.

**Comment by rhatdan** [comment]
@jwhonce any progress?
