### ISSUE TITLE
API /networks/{id} missing query parameters

### ISSUE THREAD

**Issue by jwhonce** [containers/podman#10061]
For compatibility, the following query parameters should be implemented:
- verbose
- scope 

Any value for scope other than `local` should return a 400 error.

See https://github.com/containers/podman/pull/9126

**Comment by rhatdan** [comment]
This would seem to be a good first issue, we would need volunteers for this.  Or we can have interns look into it.

**Comment by jamesdube** [comment]
> This would seem to be a good first issue, we would need volunteers for this. Or we can have interns look into it.

This looks like something I can do. I've tried to look into the background of the issue, is this adding query parameters to filter networks?

**Comment by jwhonce** [comment]
@jamesdube The query parameters do filter the networks returned. Research is needed on:

* how verbose changes the returned payload
* which scopes podman most approximates, errors should be returned on non-supported values

See https://docs.docker.com/engine/api/v1.41/#operation/NetworkInspect for details. I look forward to your PR.

**Comment by jamesdube** [comment]
I get it now thanks, let me have a look
