### ISSUE TITLE
Single consistent naming scheme for API json fields.

### ISSUE THREAD

**Issue by arctic-alpaca** [containers/podman#10076]
/kind feature

**Description**

Hi,
I'm not sure whether there are any technical reasons for the naming of the API fields. A single naming scheme would simplify de-/serializing fields.

As an example, the [system -> get info method](https://docs.podman.io/en/latest/_static/api.html#operation/SystemInfoLibpod) returns json with three different naming schemes:
* `host` with camelCase
* `host` contains `idMappings` which contains `gidmap` which uses snake_case
* `version` contains PascalCase

Is it possible to unify the field names?

**Comment by rhatdan** [comment]
Probably yes and no.  It is possible, but would it break existing API.  Would it break conformance with Docker.

**Comment by arctic-alpaca** [comment]
> Would it break conformance with Docker.

Sorry, I was only refering to the non-compat podman API.

**Comment by rhatdan** [comment]
If you want to open a PR to make that change, I am sure we would review it.
@mheon @vrothberg What do you think?  Would this require a major version Bump if we were to clean this up?

**Comment by mheon** [comment]
Yep. This is Podman 4.0 at earliest.

**Comment by arctic-alpaca** [comment]
Are there any guidelines for the correct naming conventions?

Are there central folders for input and output types? I found [podman/libpod/define/](/containers/podman/tree/master/libpod/define) but I'm not sure whether there are other relevant places in the code and if so, how to find them.

The [apiv2 tests](/containers/podman/tree/master/test/apiv2) probably need to be kept in line with the naming changes, is there anything else to keep in mind?

> We should also use some rendering implementation that does not require duplicating the handlers that are currently shared between compat and libpod.

I don't think I can help with that.

**Comment by mheon** [comment]
I believe all API structs live in `pkg/domain/entities`

**Comment by vrothberg** [comment]
Whatever we do, older clients should not break. We can have consistency _and_ allow the server to accept the old keys such that new users aren't confused by inconsistent naming and older clients continue running.

**Comment by rhatdan** [comment]
@jwhonce do we still have this issue?

**Comment by arctic-alpaca** [comment]
There is currently no consistent naming in the API, neither in parameters, nor in responses.
The [system->get info endpoint](https://docs.podman.io/en/latest/_static/api.html#operation/SystemInfoLibpod) example from the first post in this issue is still using multiple naming schemes.

**Comment by umohnani8** [comment]
Unless we find a way to remain backwards compatible, we are not going to fix it. The existing deployments would break.
