### ISSUE TITLE
After Kernel upgrade to 5.10 Podman bind volume mount stopped to work: Error: invalid container path...

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/podman#10073]
/kind bug
**Description**
Looks like regression due to Linux Kernel upgrade or bug in the new WSL Kernel
After upgrade the Microsoft WSL kernel to the latest 5.10 bind volume mount stopped to work. The error is  
podman run -v type=bind,ro,src=/mnt/d/Pavel,dst=/mnt/ docker.io/library/ubuntu
Error: invalid container path "type=bind,ro,src=/mnt/d/Pavel,dst=/mnt/", must be an absolute path
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

**Steps to reproduce the issue:**

1. It comes with regular Windows release update :(
2. Pull Ubuntu image from Docker.io
3. podman run -v type=bind,ro,src=/mnt/d/Pavel,dst=/mnt/ docker.io/library/ubuntu

**Describe the results you received:**
Error: invalid container path "type=bind,src=/mnt/d/Pavel,dst=/mnt/dPavel", must be an absolute path

**Describe the results you expected:**
Container is running and host directory is mounted as at /mnt/dPavel like 1 week ago.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman --version
podman version 3.1.0
crun version 0.19
commit: e67a75672412975916dac6b87f8346f870e4b99a
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
```

**Output of `podman info --debug`:**
host:
  arch: amd64
  buildahVersion: 1.20.0
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.27-2.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 2
  distribution:
    distribution: fedoraremixforwsl
    version: "33"
  eventLogger: journald
  hostname: MSI-wsl
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.16.3-microsoft-standard-WSL2
  linkmode: dynamic
  memFree: 7612522496
  memTotal: 8344264704
  ociRuntime:
    name: crun
    package: crun-0.19-1.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.19
      commit: e67a75672412975916dac6b87f8346f870e4b99a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 17179869184
  swapTotal: 17179869184
  uptime: 1h 31m 6.27s (Approximately 0.04 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 0
    stopped: 5
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.1.0
  Built: 1618238356
  BuiltTime: Mon Apr 12 17:39:16 2021
  GitCommit: ""
  GoVersion: go1.15.8
  OsArch: linux/amd64
  Version: 3.1.0

```
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
WSL Kernel
Linux MSI-wsl 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
+systemd-genie
User: root
Image: docker.io/library/ubuntu         latest  26b77e58432b  2 weeks ago. But tested with any image.
The container starts without mount. /mnt exists inside container owned by root.
The Fedoradistro works OK and 
systemctl status
● MSI-wsl
    State: running
     Jobs: 0 queued
   Failed: 0 units
Backing filesystem is extfs but no such FS in the distro: 
df: /proc/sys/fs/binfmt_misc: Too many levels of symbolic links.
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/sdb       263174212  2202076 247533980   1% /
tools          139271164 82506908  56764256  60% /init
none             4072264        0   4072264   0% /dev
tmpfs               4096        0      4096   0% /sys/fs/cgroup
none             4074348      116   4074232   1% /run
none             4074348        0   4074348   0% /run/lock
none             4074348      176   4074172   1% /run/shm
none             4074348        0   4074348   0% /run/user
drivers        139271164 82506908  56764256  60% /usr/lib/wsl/drivers
lib            139271164 82506908  56764256  60% /usr/lib/wsl/lib
none             4074348        4   4074344   1% /mnt/wsl
drvfsa         139271164 82506908  56764256  60% /mnt/c
drvfsa          87256060 61319104  25936956  71% /mnt/d
tmpfs            4074348        0   4074348   0% /tmp
tmpfs             814868        4    814864   1% /run/user/1000
tmpfs             814868        0    814868   0% /run/user/0 This error is known from the Docker-for-win. Their, reset solves the problem but podman system reset doesn't.
The ability to create symlinks in the rootfs by the new kernel is not broken. Are there other pre-requisites for bind mount to test?

**Comment by Luap99** [comment]
Your podman command is incorrect, you have to use the --mount flag not --volume when you want to use this syntax, `podman run --mount type=bind,ro,src=/mnt/d/Pavel,dst=/mnt/ docker.io/library/ubuntu`

**Comment by PavelSosin-320** [comment]
OK, SOLVED! I tried many things until found that in the WSL Kernel boot log that the new WSL Kernel supports FUSE. So in the storage.conf the line 
mount_program = "/usr/bin/fuse-overlayfs" must be uncommented. The long hot discussion with WSL gave its fruits.
I suppose, for >= Kernel 5.10 and Fedora34 it should be the default.
