### ISSUE TITLE
network connect rootless

### ISSUE THREAD

**Issue by tmds** [containers/podman#10071]
When I try to use the `network connect` command I get an error message:

```
Error: network disconnect is not enabled for rootless containers
```

The message should probably say: network **connect** is not enabled for rootless containers.

I'm using v3.1.0.
Is this command supported rootless in a later version of podman?

I think v3.1.0 allows me to specify a network id, and network alias when I execute `podman run` I'm going to give that a try.

cc @AkihiroSuda @Luap99

**Comment by Luap99** [comment]
Rootless network connect is currently only supported in the master branch. You can expect it to be in the 3.2 release. With 3.1 both `--network` and `--network-alias` for `podman run` should work.
