### ISSUE TITLE
Feature request: podman network rm: add -a, --all option

### ISSUE THREAD

**Issue by tmds** [containers/podman#10086]
to remove all networks.

Similar to the flags on `podman rm` and `podman rmi` to remove all containers and images.

**Comment by rhatdan** [comment]
Interested in opening a PR?  I think this might be a little more difficult, and potentially dangerous.
@mheon @Luap99 PTAL

**Comment by Luap99** [comment]
It should be fine but we have to ensure that we do not delete the default podman network. We already support network prune.

**Comment by tmds** [comment]
I didn't know about `network prune`. That also works for me. You can close this ticket if you want.

**Comment by rhatdan** [comment]
Perhaps we could add information to podman network rm  about this capability?  Would that have helped you?

**Comment by tmds** [comment]
It's worth mentioning. Also, `prune` could have been a flag on `podman network rm`.

**Comment by rhatdan** [comment]
Sure, but we are trying to match the Docker CLI, so they have a docker network prune command and so do we.
