### ISSUE TITLE
Question: To what extent are concurrent builds with Podman supported?

### ISSUE THREAD

**Issue by lexemmens** [containers/podman#10082]
To what extent are concurrent builds, i.e. on the same machine, with Podman supported (specifically when file copy actions are part of the `Containerfile`)?

The reason behind this question is that I am running into issues that seem rather vague and I did not read anything about it in the documentation. Issues of which it is unclear whether they are:
* caused by a potential issue in Podman;
* showing up because I am doing something which is simply not supported, or is a limitation of Podman;
* caused by us doing something wrong.

**Background:**
I am working on multiple Java applications, which are built with Maven. A Jenkins CI server builds the projects and executes a `podman build` using a custom made plugin (Podman Maven Plugin). During the `podman build` command a multistage `Containerfile` is used and 2 of the 3 stages copy an executable (jar file) to the image. This works rather well.

However, all Jenkins nodes have multiple executors, meaning that multiple jobs can run in parallel on the same machine. This is sometimes problematic if two or more of these jobs happen to execute Podman. In that case EOF-errors like the (simplified and anonymised) one below are witnessed around 40% of the time.

```
(... other output omitted for readability purposes ...)
STEP 1: FROM my-internal-nexus-server:12345/adoptopenjdk/openjdk11:11.0.3 AS base
Getting image source signatures
Copying blob sha256:ad26192fb1166465550d702a8418c67ecda7b089149870f48673d8f0fb5ab8c1
Copying blob sha256:95c2c089cb32f9959093f091b223b04c3a8e0e0aa8b703c0052ebfe9be5f0b3c
Copying blob sha256:c29f4698c17768b4bf36dde25d584231424db9f4b9c9e67cce8980cfc50efbc1
Copying blob sha256:df15d82c4ffe976522b836c1f0c300e289f797cb2e302df1b7d0b917af7d3795
Copying blob sha256:67300986eedeec2c7442a3b30e65142200b72dc72dc6da2e945a0f06d5e9183b
Copying blob sha256:b08df05e829707fdd711d6669671a0dd0431a20ca7ae89d7cd415e0025ba3a84
Copying config sha256:c83be72afce332f5c3c3ae4992f3340479fee3115d7f449afebf39d0b6eb16b6
Writing manifest to image destination
Storing signatures
STEP 2: LABEL Build-User=username Git-Repository-Url=null 
--> efb962baf92
STEP 3: WORKDIR /myapplication
--> fb45d282d4f
STEP 4: ENV RUN_CMD="exec java -jar my-jar-file.jar"
--> 69aad2f542e
STEP 5: FROM 69aad2f542e75ba283a270c57fcf4b59bdf480d376d7ceabe22c520d242858bb AS somestage
STEP 6: LABEL Build-User=username Git-Repository-Url=some-git-repo 
--> 041c3208b08
STEP 7: ENV BLA="bla"
--> 2e4a8e94c2c
STEP 8: COPY target/my-other-jar-file.jar ./
Error: error building at STEP "COPY target/my-other-jar-file.jar ./": error decoding response: EOF
```

All Podman images are built by invoking the `podman` via the command line using a custom `root` location, i.e. `podman --root=<directory> build ...`

I am using Podman 2.1.1 on RHEL7, but I also managed to reproduce this with Podman 2.2.1. 

Any insights on this behavior is greatly appreciated. Please let me know if you require any additional information is required.

**Comment by mheon** [comment]
I see no reason why parallel builds would not be supported. v2.2.1 is still very old, so my first recommendation would be to try with a more recent version (ideally v3.1.1) which should feature a rewritten copy implementation.

**Comment by lexemmens** [comment]
That's interesting. That would support my assumption that something broke after our upgrade from v1.x last year.

I realise that v2.2.1 is very old. Since the build nodes are running RHEL7, the best I can do for those nodes is to upgrade towards Podman 3.0.0 (which according to [this page](https://podman.io/getting-started/installation) seems to be the latest supported version). 

I will give 3.1.1 a try anyway on both RHEL7 and RHEL8 and get back to you.

**Comment by rhatdan** [comment]
You could always update to RHEL8 :^)

**Comment by lexemmens** [comment]
> You could always update to RHEL8 :^)

I have, on my private notebook :-) 

But for the Jenkins slaves, I will need some help from the IT department and I think it will take some time before they have migrated the nodes to RHEL8

Anyway, I did some initial tests with Podman 3.0.0, and so far it looks promising. I still need to do some more extensive testing though. Will keep you posted.

**Comment by rhatdan** [comment]
I think the question has been answered.  Closing.
