### ISSUE TITLE
Selection of repository from the list using arrow doesn't work if "Scrolling forward" is enabled in Win console setting

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/podman#10095]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The selection of repository from proposed repository list in the podman pull, buildah pull, .... doesn'twork if 
![Win Terminal setting](https://user-images.githubusercontent.com/54495912/115498023-6c7df700-a275-11eb-9163-58a04740df27.png)

**Steps to reproduce the issue:**

1. Install Podman 3.1 on the one of WSL distro

2. Start Distro with systemd-genie

3. Run Podman pull of one of images presented in many repositories
4. Try to move selection using Up/Down arrow

**Describe the results you received:**
Selection doesn't move. Scrolling happens instead.

**Describe the results you expected:**

The selection moves up and  down
**Additional information you deem important (e.g. issue happens only occasionally):**
Using Podman and buildah on Windows WSL. There is In Windows Terminal setting 
**Output of `podman version`:**

```
[root@MSI-wsl ~]# podman version
Version:      3.1.0
API Version:  3.1.0
Go Version:   go1.15.8
Built:        Mon Apr 12 17:39:16 2021
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The new Windows insider preview build. It happens when the scroll buffer is enlarged over the physical screen size and Scroll-Forward is enabled.
I suppose that it is Windows glitch but it makes Podman unusable.
Please, document ASAP in the Podman troubleshooting guide!😒.

**Comment by PavelSosin-320** [comment]
Proposal: maybe, Repository list must be enumerated in priority order like in other name resolution use-cases? It will save the developer's time.

**Comment by vrothberg** [comment]
Thanks for reaching out!  I agree that this looks like an issues in the Windows terminal; others tools should be impacted as well.

> Please, document ASAP in the Podman troubleshooting guide!

Would you open a PR?

**Comment by PavelSosin-320** [comment]
@vrothberg Maybe, even better and less efforts-consuming solution that will make repository selection faster:
add --registry-filter or --filter registry=*docker* option to podman pull command that applies regex filter on repositories list. In the case when only one entry left it can be accepted automatically. It will eliminate dependency on terminal behaviour and is applicable in non-interactive mode.

**Comment by vrothberg** [comment]
@PavelSosin-320, you can configure `/etc/containers/registries.conf` if you want to resolve to only one registry.

**Comment by PavelSosin-320** [comment]
OK, This is not a major issue but maybe, navigation through repositories list can be re-think and made less terminal implementation-dependent, like VI allows navigation using J & K keys instead of arrows - it works always, although less user-friendly.
