### ISSUE TITLE
Support environment variable secrets

### ISSUE THREAD

**Issue by ashley-cui** [containers/podman#10106]
/kind feature

**Description**

We want to support environment variable secrets, where an environment variable would exist inside the container but not get committed inside an image.

**Comment by mheon** [comment]
Is there a risk the current secrets are committed? I thought we had a guarantee they were not.

**Comment by ashley-cui** [comment]
No, they're not committed, we just want to be able to do the same for some env variables

**Comment by rhatdan** [comment]
Current secrets just support sticking a file into a container.  In this case we insert the secrets as environment variables, which do not get committed to the container. they are only given to the OCI Runtime.

Imagine running a container with a database in it that requires $PASSWORD to be set.
