### ISSUE TITLE
RFE: podman image scp

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#10108]
Podman has so much ssh stuff in it these days, why not scp?
```console
$ podman image scp myimage:latest otherhost::
$ podman image scp user@otherhost::registry/image:tag .
```
Would basically run `podman image save | ssh host podman image load`. This is something I find myself running pretty often between my home desktop and laptop.

Double colon is a suggestion to deal with the ambiguity between *host:image* and *image:tag*. There may be better ideas.

**Comment by baude** [comment]
neat idea @edsantiago .. could also use the system connection to do this.

**Comment by vrothberg** [comment]
Both great ideas!

A `podman --remote save $image` would work already.

**Comment by vrothberg** [comment]
> Both great ideas!
> 
> A `podman --remote save $image` would work already.

Brain fart on my end... `podman --remote load $path` would work.

**Comment by rhatdan** [comment]
Would it be best to do this through a remote socket?  IE Have podman use the local cache to save and then use the remote socket to load.
Might be something for an intern.

**Comment by rhatdan** [comment]
@ashley-cui @Luap99 @cdoern Any one have time and want to look at this?

**Comment by rhatdan** [comment]
Or any contributor out there?

**Comment by cdoern** [comment]
> @ashley-cui @Luap99 @cdoern Any one have time and want to look at this?

I can look into this! I need to get some background knowledge on how `image save` works but I think I could figure it out @rhatdan

**Comment by vrothberg** [comment]
> > @ashley-cui @Luap99 @cdoern Any one have time and want to look at this?
> 
> I can look into this! I need to get some background knowledge on how `image save` works but I think I could figure it out @rhatdan

Feel free to ping me if you have questions, @cdoern. I am free 10-11AM eastern.

**Comment by edsantiago** [comment]
Not true, github-actions, not true at all. You have no idea!
