### ISSUE TITLE
Is support of katocontainer runtime expected?

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/podman#10129]
/kind feature

**Description**
Starting from Windows build 20190 the Intel's Nested virtualization is supported by WSL, FUSE is supported by WSL Kernel starting from 5.10, and RedHat virtio comes with Fedoraremixforwsl distro i.e. at glance, all Kato hardware and software requirements are fulfilled. 
Is Katocontainers runtime based on Intel virtualization technology and better suitable for lightweight VM's like WSL is expected? 

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by PavelSosin-320** [comment]
I already have kata-runtime on the board of my Fedora34 WSL VM:
kata-runtime --version
kata-runtime  : 1.12.1
   commit   : <<unknown>>
   OCI specs: 1.0.1-dev

**Comment by rhatdan** [comment]
We expect KATA to work, whether it works on WSL, I have no idea.
