### ISSUE TITLE
It is not possible to mount /dev even with root

### ISSUE THREAD

**Issue by talesam** [containers/podman#10133]
I will explain what I am trying to do ..
I want to automate the creation of the Manjaro iso inside a container. In Docker it is not possible even with privileges to the host, so I got to the podman because I need the systemD running.

I created an image of manjaro with some extra packages and settings for me to try to create the iso inside it, I tried to mount the `/dev` that is necessary and it was not possible. tried with rootless and straight with root.

**ERROR:**
```
[bruno@bruno-virtualbox podman]$ sudo podman run -it -v /dev:/dev bigmanjaroido:0.3
[sudo] senha para bruno: 
Error: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: open /dev/console: operation not permitted: OCI permission denied
```

**Dockerfile:**
```
FROM manjarolinux/base:latest
LABEL version="0.4" description="BigLinux ISO generator" maintainer="Tales A. Mendonça<talesam@gmail.com>"

# Muda para os espelhos do Brasil
RUN pacman-mirrors -c Brazil

# Attualiza o sistema
RUN pacman -Syy --noconfirm

RUN pacman -S --noconfirm \
        btrfs-progs \
        manjaro-tools-iso \
        git

# Limpa os arquivos dos pacotes baixados
RUN pacman -Scc --noconfirm

WORKDIR /root
RUN echo "root:root" | chpasswd

ENTRYPOINT [ "/sbin/init" ]
```

**Comment by mheon** [comment]
You need to add a `/dev/pts` mount with `--mount type=devpts,target=/dev/pts` to retain a usable console.

**Comment by talesam** [comment]
> --mount type=devpts,target=/dev/pts

`[bruno@bruno-virtualbox podman]$ sudo podman run -it --mount type=devpts,target=/dev/pts -v /dev:/dev bigmanjaroido:0.3
Error: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: open /dev/console: operation not permitted: OCI permission denied`

**Comment by rhatdan** [comment]
SELinux might be blocking this?

**Comment by talesam** [comment]
> SELinux pode estar bloqueando isso?

I can't say :-/
I need to build the dev but so far no one has managed to get a working solution.

**Comment by rhatdan** [comment]
Could you try --privileged and then work our way back.

**Comment by talesam** [comment]
The problem with using "--privileged" is that the host is too exposed. But I managed to run with it activated without any error in loading, now when creating the iso ended up giving an error that I haven't discovered yet.

I would have to be able to run without the "--privileged" to not compromise the system

**Comment by rhatdan** [comment]
The idea was to attempt to figure out what is causing the breakage.  I usually start with --privileged, and if this works, start turning off individual security tools.   If it does not work then it might be namespaces, or some other feature of containers that is breaking the application.

**Comment by talesam** [comment]
with all the privileges the system loads normal, but this is not ideal, and I really don't know everything you need to load the system.

**Comment by rhatdan** [comment]
Ok so next step is  drop --privileged and go through each one of the security mechanisms to see which one when disabled the container works.

Disable SELinux --security-opt label=disable
Disable SECCOMP --security-opt seccomp=unconfined
Disable dropped caps --cap-add all

Try each one of these separately.  If one works, then we know what security mechanism is breaking you container.  Once we know this we can continue to work to futher confine the container, especially if it is --cap-add.

**Comment by talesam** [comment]
> Disable dropped caps --cap-add all

So it works, everything is loaded well.
`caps --cap-add all`

But when will the iso generate an error, which I couldn't solve ...

I can go through the steps, can you test test there for me?

**Comment by rhatdan** [comment]
This looks like it could be a overlay on overlay issue.

If you tried with --storage-driver=vfs, it might work. Looking at this section.  I am guessing that something in the pacman install is attempting to mount an overlayfs file system.
```
==> Prepare [Desktop installation] (desktopfs)
 --> overlayfs mount: [/var/lib/manjaro-tools/buildiso/xfce/x86_64/desktopfs]
mount: /var/lib/manjaro-tools/buildiso/xfce/x86_64/desktopfs: wrong fs type, bad option, bad superblock on overlay, missing codepage or helper program, or other error.
```

**Comment by talesam** [comment]
I changed the driver to btfrs and another error, now permission, appeared. 

```
==> Prepare [/iso/boot/grub]
  -> Building core.img ...
  -> Building bootx64.efi ...
  -> Set menu_show_once=1 in '/var/lib/manjaro-tools/buildiso/xfce/iso/boot/grub/grubenv'
  -> Creating fat image of 4M ...
 --> mount: [/var/lib/manjaro-tools/buildiso/xfce/mnt/efiboot]
mount: /var/lib/manjaro-tools/buildiso/xfce/mnt/efiboot: mount failed: Operation not permitted.
==> ERROR: A failure occurred in make_grub().
    Aborting...
```
I will try with the vfs now, but I think it should give the same permission error.

**Comment by rhatdan** [comment]
You are not allowed to mount unless you do a --cap-add sys_admin

**Comment by vrothberg** [comment]
Are the remaining questions or shall we close the issue?
