### ISSUE TITLE
podman(1) start | run failing: ERRO[0008] "container_linux.go:367: starting container process caused: process_linux.go:340: applying cgroup configuration for process caused: no cgroup mount found in mountinfo: OCI runtime error" 

### ISSUE THREAD

**Issue by nmvega** [containers/podman#10141]
Hello Friends:

Today I rebuilt a `docker` image from scratch (via a `Dockerfile(5)`, which I've been iteratively doing (for weeks) to get the image perfect. That `docker` image is built to support `ROOTLESS podman(1)` within it, and that has worked perfectly until after today's rebuild.

Just a reminder from [this GitHub issue](https://github.com/containers/podman/issues/10001) that my setup is like this (which works). I only mention it because I did a `dnf -y update` in layers **(1)** and **(2)** this 
weekend, and of course also in layer **(3)** when rebuilding the `docker` image today:

- (1) Bare-metal host: FC-33 x86_64
   - (2) Linux / LXC container: FC-33 x86_64
     - (3)  Docker-CE container: FC-33 x86_64
       - (4) Podman

Please see below. Any ideas? Was a new version of `podman(1)` released?

Here is the script, taking note of my in-line comment where failure is triggered:
```
#! /usr/bin/bash

podman pod create \
    --name cassandra \
    --network acme \
    --share net \
    --publish 9042:9042

podman create \
    --pod cassandra \
    --name cassandra_container \
    --hostname cassandra \
    --restart always \
    --add-host cassandra:127.0.0.1 \
    docker.io/library/cassandra:latest

podman start cassandra_container  # <-- Failure is triggered by this.
```

Here's the `error` thrown by the `start` command:
```
jdoe@fedora33$ podman start cassandra_container
ERRO[0008] error starting some container dependencies   
ERRO[0008] "container_linux.go:367: starting container process caused: process_linux.go:340: applying cgroup configuration for process caused: no cgroup mount found in mountinfo: OCI runtime error" 
Error: unable to start container "2bfb0320ffe6e2ad4a95c236e14a105a83d102c19b2d2ebf6c359dc537f706e7": error starting some containers: internal libpod error
```

Diagnostic information:

**podman(1) veraion**:
```
jdoe@fedora33$ podman version
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.15.8
Built:        Thu Apr 22 13:21:33 2021
OS/Arch:      linux/amd64
```
**./containers.conf**:
```
jdoe@fedora33$ cat ~/.config/containers/containers.conf 
[engine]
events_logger = "file"
cgroup_manager = "cgroupfs"
```

**./storage.conf**:
```
jdoe@fedora33$ cat ~/.config/containers/storage.conf
[storage]
driver = "overlay"
graphroot             = "$HOME/.local/share/containers/storage"
rootless_storage_path = "$HOME/.local/share/containers/storage"

[storage.options]
additionalimagestores = []
mount_program = "/usr/bin/fuse-overlayfs"

[storage.options.overlay]
mountopt = "nodev"
mount_program = "/usr/bin/fuse-overlayfs"

[storage.options.thinpool]
```

**Comment by nmvega** [comment]
Additional information (a running comment):

```
jdoe@fedora33$ podman unshare cat /proc/self/uid_map
         0       1000          1
         1     100000      65536
```

**Comment by nmvega** [comment]
**UPDATE**:

In reviewing [this issue](https://github.com/containers/podman/issues/7004), I solved the above issue by installing `crun(1)`, which my `Dockerfile(5)` doesn't install (but will now).

- So what happened that it now requires `crun(1)`? A new podman(1) version?
- Is `crun(1)` better? That's good if so. =:)
- What was it using before? `runc(1)`?

Thank you!

**Comment by mheon** [comment]
```
ERRO[0008] "container_linux.go:367: starting container process caused: process_linux.go:340: applying cgroup configuration for process caused: no cgroup mount found in mountinfo: OCI runtime error" 
```

Alright, never seen this one before. Potentially a runc bug? Swapping to crun may be avoiding said bug. We made crun default in 3.0 but still support runc if crun is unavailable.

**Comment by mheon** [comment]
Cgroups v1 vs v2 is an OS-level configuration option. We definitely prefer v2. You need to add `systemd.unified_cgroup_hierarchy=1` to your Kernel command line (You probably have this already there, but set to 0, given Fedora now defaults to v2).

**Comment by nmvega** [comment]
> Cgroups v1 vs v2 is an OS-level configuration option. We definitely prefer v2. You need to add `systemd.unified_cgroup_hierarchy=1` to your Kernel command line (You probably have this already there, but set to 0, given Fedora now defaults to v2).

@mheon Thank you. Do I need to do this at every layer in my nesting?

**Comment by nmvega** [comment]
> Cgroups v1 vs v2 is an OS-level configuration option. We definitely prefer v2. You need to add `systemd.unified_cgroup_hierarchy=1` to your Kernel command line (You probably have this already there, but set to 0, given Fedora now defaults to v2).

@mheon  Though solved below, a quick follow-up to this comment. You may be correct that I sidestepped this issue by installing `crun(1)`, so your hypothesis here still lingers. `=:)`

**Comment by mheon** [comment]
@nmvega It does need to be done on the host, I think that everything underneath probably picks it up from there, though if there's a completely separate systemd in play anywhere (Maybe the LXC container? Maybe?) that might also need to be set to use v2.

**Comment by nmvega** [comment]
@mheon Yea, that makes sense (`bare-meta` + possibly the nested `LXC` containers, too). I'll try `cgroups v2` somewhat soon. I have four levels of nesting for my little project so I'm cautious, buy I'll try it once I have the project stabilized. `=:)` Thanks for your help.

**Comment by rhatdan** [comment]
I am lost, is this still an issue?  Is this a problem with runc?

**Comment by nmvega** [comment]
@rhatdan Well yes and no. My installation of `crun` sidestepped (masked) the original issue which arises while using `runc`, and `may` still be an issue for you. That's why I didn't close this issue, in case you wanted to follow-up with respect to `runc`. But I'm all good here as long as I use `crun`. So check out the `OP` the opening comment). That may still be a problem because of `runc` or something else that happens when using `runc`. You can close this if you like. Thanks for the assistance!

**Comment by rhatdan** [comment]
Ok I am going to close this issue.
