### ISSUE TITLE
Document the single ID rootless mode

### ISSUE THREAD

**Issue by andrewshadura** [containers/podman#10145]
The single ID rootless mode is not documented properly. It is possible to use rootless, but limited to just one user, together with `ignore_chown_errors`:
> `podman --storage-opt ignore_chown_errors ...` when a single ID is available and all the files will be owned by just one user.
> 
> It is not done automatically (and I think it shouldn't) because potentially it can lead to security problems when the files ownership inside the container matters.

_Originally posted by @giuseppe in https://github.com/containers/podman/issues/9788#issuecomment-806684711_

**Comment by rhatdan** [comment]
Interested in opening a PR?

Should this be documented in the podman run man page, or in some other location?
