### ISSUE TITLE
podman build: stream dropped, unexpected failure

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#10154]
Looks like an unintended consequence of #10034 . I'm seeing a lot of these failures in my buildah-bud-tests-under-podman-remote testing (#9887):
```
# podman-remote build ....
STEP 1: FROM <some image>
STEP 2: something-somethng
Error: stream dropped, unexpected failure
[rc=125]
```
Logs, all from fedora34-beta:
* [first attempt](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6745318667583488/html/bud-remote-fedora-34beta-root-host.log.html#t--00118)
* [second attempt](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5257019318861824/html/bud-remote-fedora-34beta-root-host.log.html#t--00118)
* [third attempt](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5265760818823168/html/bud-remote-fedora-34beta-root-host.log.html#t--00090) (this one has three separate failures)

Four of the five failures are in tests that expect rc=125; but one of them is in a test that expects rc=0.

This is based on master @ 476c76f58 as of yesterday afternoon (Apr 26)

**Comment by edsantiago** [comment]
Two more failures in [my next rerun](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5742129533157376/html/bud-remote-fedora-34beta-root-host.log.html) (plus one more flake which I'm just going to stick my head in the sand about)

**Comment by edsantiago** [comment]
[Still happening](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6011994407960576/html/bud-remote-fedora-34-root-host.log.html)

**Comment by edsantiago** [comment]
Update: although it _mostly_ happens in the `bud with copy-from with bad from flag in Dockerfile with --layers` test, not always: the "third attempt" and "my next rerun" links, above, include failures in different tests.

This bug makes it impossible to merge #9887

**Comment by edsantiago** [comment]
[Another one](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6509655984701440/html/bud-remote-fedora-34-root-host.log.html), in bud-http-Dockerfile test

**Comment by edsantiago** [comment]
Here's a reproducer (assumes `podman system service --timeout=0` running):
```console
$ cat Containerfile
FROM php:7.2
COPY --from foo:bar a b
$ while :;do x=$(../bin/podman-remote build --force-rm=false -t foo . 2>&1); if [[ $x =~ stream ]]; then echo $x; break;fi;done
STEP 1: FROM php:7.2
STEP 2: COPY --from foo:bar a b
Error: stream dropped, unexpected failure
```
Might take 3 minutes, might take 15. The `--force-rm=false` seems to be necessary: without it, I couldn't get a failure in over an hour of trying.

**Comment by edsantiago** [comment]
Update: #10295 did not, alas, fix the problem. Here is a [failed CI run](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6378585393987584/html/bud-remote-fedora-34-root-host.log.html) from my buildah-bud-under-podman-remote PR. I was also able to reproduce the problem locally on my laptop, using the reproducer above. (I added `buildah rm -a &>/dev/null` to the loop, because otherwise I end up with gajillions of stale containers).

Curiously... I ran the server with `--log-level=info`, expecting to see `Client disconnect reported`, but no luck. Actually, it's worse than that: the message appears, but in a run that succeeded (over a minute before the failed run). I have no idea what that could mean.

Hint: if you run with a verbose log-level, redirect server output to a logfile in shm. With output going to my rxvt, I wasn't able to reproduce the failure.

**Comment by edsantiago** [comment]
@jwhonce, @rhatdan, I know nothing at all about Go streams ... but is EOF really considered an error? Is it possible for EOF to trigger in conjunction with a successful read? And, more to the point, WDYT of:
```diff
--- a/pkg/bindings/images/build.go
+++ b/pkg/bindings/images/build.go
@@ -353,7 +353,7 @@ func Build(ctx context.Context, containerFiles []string, options entities.BuildO
                }
                if err := dec.Decode(&s); err != nil {
                        if errors.Is(err, io.EOF) {
-                               if mErr == nil && id == "" {
+                               if mErr == nil && s.Error == "" && id == "" {
                                        mErr = errors.New("stream dropped, unexpected failure")
                                }
                                break
```
With that, I've been unable to trigger the error on my laptop, and it even [passed in CI](https://cirrus-ci.com/task/6138511351873536), which has not happened in weeks. I don't know what unintended consequences that might have, though.

**Comment by edsantiago** [comment]
Okay... never mind. I tried the following:
```diff
diff --git a/pkg/bindings/images/build.go b/pkg/bindings/images/build.go
index f5e7c0c98..44434810d 100644
--- a/pkg/bindings/images/build.go
+++ b/pkg/bindings/images/build.go
@@ -354,6 +354,7 @@ func Build(ctx context.Context, containerFiles []string, options entities.BuildO
                if err := dec.Decode(&s); err != nil {
                        if errors.Is(err, io.EOF) {
                                if mErr == nil && id == "" {
+                                       logrus.Errorf("got here: s.Error=%q", s.Error)
                                        mErr = errors.New("stream dropped, unexpected failure")
                                }
                                break
```
...and ran my reproducer, which quickly failed with:
```console
$ while :;do x=$(../bin/podman-remote build --force-rm=false -t foo . 2>&1); if [[ $x =~ stream ]]; then echo $x; beep;break;fi;buildah rm -a >/dev/null;done
STEP 1: FROM php:7.2
STEP 2: COPY --from foo:bar a b
time="2021-05-11T10:06:35-06:00" level=error msg="got here: s.Error=\"\""
Error: stream dropped, unexpected failure
```
Therefore: adding `&& s.Error == ""`, as I suggested in my previous comment, is a NOP. The fact that it worked then is pure coincidence. Never mind.

**Comment by edsantiago** [comment]
New record: [seven failures in one CI run](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5468767036637184/html/bud-remote-fedora-34-root-host.log.html).

* bud with --rm flag
* bud-from-scratch
* bud-from-scratch-iid
* bud-http-Dockerfile
* bud-http-context-with-Dockerfile
* bud pull never
* bud-builder-identity

**Comment by edsantiago** [comment]
Sigh. I had hoped that #10549 would fix this, but [nope](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5540293895258112/html/bud-remote-fedora-34-root-host.log.html#t--00018).

**Comment by edsantiago** [comment]
PR #9887 (buildah-bud tests under podman-remote) has been catching a large number of bugs in both podman and buildah. It would be really great if we could merge that and run it in CI, instead of manually by me, but we can't, because of this flake. Is there any chance someone could take a fresh look?

**Comment by edsantiago** [comment]
[Still happening](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4597575966785536/html/bud-remote-fedora-34-root-host.log.html)

**Comment by edsantiago** [comment]
Oh well. I was slightly hopeful that #10916 would fix this, but nope.

**Comment by edsantiago** [comment]
Oh, this is really bad. We're now seeing this flake in regular CI ([sys remote ubuntu-2104 root host](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4665540334583808/html/sys-remote-ubuntu-2104-root-host.log.html)).

**Comment by edsantiago** [comment]
...and, looking back through flake logs, [another one](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5323542813212672/html/sys-remote-ubuntu-2104-root-host.log.html) also in ubuntu-2104 root.

**Comment by edsantiago** [comment]
And [another one in our regular CI](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6477853039525888/html/sys-remote-ubuntu-2010-root-host.log.html), this time ubuntu-2010.

@containers/podman-maintainers this is becoming a serious problem. I don't care if we can't merge #9887, but the flake is now affecting us in real-world CI.

**Comment by vrothberg** [comment]
I am still dizzy from my 2nd shot but bookmarked it.  Will take a look at it with a fresh brain on Monday.

Thank you for the ping, @edsantiago!

**Comment by vrothberg** [comment]
Hit the flake also in https://github.com/containers/podman/pull/11049
