### ISSUE TITLE
Container resolv.conf list IPv6 servers in absence of IPv6 connectivity, breaking DNS

### ISSUE THREAD

**Issue by FallenWarrior2k** [containers/podman#10158]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

On one of my machines, Podman containers get a resolv.conf that contains all DNS servers configured on the host verbatim, including IPv6 ones. However, since the container does not have v6 connectivity by default, this causes all DNS operations to fail.

**Steps to reproduce the issue:**

1. Set IPv6 nameservers in systemd-resolved/systemd-networkd. In my case, I have configured them in a `.network` file for my external traffic interface. (I'm sure this can be repro'd with other network managers, but this is the one I'm using.)

2. Start a container in a v4-only network, such as the default `podman` network, and inspect `/etc/resolv.conf`, e.g. `podman run --rm alpine cat /etc/resolv.conf`.

**Describe the results you received:**

The container's `resolv.conf` contains the host's configured name servers copied verbatim.
```
# podman run --rm alpine cat /etc/resolv.conf
nameserver 2606:4700:4700::1111
nameserver 2606:4700:4700::1001
nameserver 1.1.1.1
nameserver 1.0.0.1
```

**Describe the results you expected:**

The container's `resolv.conf` should only contain servers the container can actually access.

**Additional information you deem important (e.g. issue happens only occasionally):**

First off, I am using rootful containers. 

The issue only occurs on one of my machines. The machine in question uses systemd-resolved with `/etc/resolv.conf` symlinked to `/run/systemd/resolve/stub-resolv.conf`. This means `/etc/resolv.conf` looks like this:
```
nameserver 127.0.0.53
options edns0 trust-ad
search .
```
The actual systemd-resolved generated `resolv.conf` at `/run/systemd/resolve/resolv.conf` looks like this:
```
nameserver 2606:4700:4700::1111
nameserver 2606:4700:4700::1001
nameserver 1.1.1.1
# Too many DNS servers configured, the following entries may be ignored.
nameserver 1.0.0.1
search .
```

On my other machine, I am using NetworkManager with local dnsmasq, so my `/etc/resolv.conf` there looks like this instead:
```
nameserver ::1
nameserver 127.0.0.1
options edns0 trust-ad
```
On this machine, podman ignores the system resolver and generates a resolv.conf containing Google's DNS servers, _also_ containing v6 servers, but with v4 servers listed first, so the issue doesn't manifest:
```
# podman run --rm alpine cat /etc/resolv.conf
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 2001:4860:4860::8888
nameserver 2001:4860:4860::8844
options edns0 trust-ad
```

Additionally, just as a side note because I don't know if it might be relevant, the network configuration on the affected machine is a bit unusual: I am also using this machine to run VMs with MACVTAP network interfaces, and to allow those to communicate with the host, I am not using my ethernet interface directly but am rather using a MACVLAN interface on top of the raw ethernet interface as the "main" interface for my network traffic.

**Output of `podman version`:**

```
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.16.3
Git Commit:   51b8ddbc22cf5b10dd76dd9243924aa66ad7db39
Built:        Wed Apr 21 21:34:03 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.20.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.0.27-1
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: 65fad4bfcb250df0435ea668017e643e7f462155'
  cpus: 4
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: boreas
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.32-1-lts
  linkmode: dynamic
  memFree: 7305834496
  memTotal: 7773085696
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 0.19.1-1
    path: /usr/bin/crun
    version: |-
      crun version 0.19.1
      commit: 1535fedf0b83fb898d449f9680000f729ba719f5
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 11m 53.89s
registries:
  search:
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: zfs
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Compression: zstd
    Parent Dataset: zroot/var/lib/containers/storage
    Parent Quota: "no"
    Space Available: "226493284352"
    Space Used By Parent: "7020544"
    Zpool: zroot
    Zpool Health: ONLINE
  imageStore:
    number: 2
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.1.2
  Built: 1619040843
  BuiltTime: Wed Apr 21 21:34:03 2021
  GitCommit: 51b8ddbc22cf5b10dd76dd9243924aa66ad7db39
  GoVersion: go1.16.3
  OsArch: linux/amd64
  Version: 3.1.2
```

**Package info (output of `pacman -Q podman`):**

```
podman 3.1.2-1
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

phsyical

**Comment by FallenWarrior2k** [comment]
I want to note that, for now, I have alleviated this issue by modifying the default network to include IPv6 addresses, but it's still an issue for containers where v6 support is unavailable or undesired for whatever reason.

**Comment by rhatdan** [comment]
Interested in opening a PR to filter out the IP6 or IP4 addresses when the container does not support those versions?

**Comment by FallenWarrior2k** [comment]
I wouldn't be opposed to doing this myself, but I'd have to familiarize myself with the codebase first.

**Comment by rhatdan** [comment]
SGTM

**Comment by rhatdan** [comment]
@Luap99 Mind taking a look at this?

**Comment by Luap99** [comment]
I will take a look.
