### ISSUE TITLE
Rootless podman fails to run Fedora 34 systemd aarch64 container in Travis CI

### ISSUE THREAD

**Issue by adelton** [containers/podman#10161]
/kind bug

**Description**

Rootless `podman run` fails when attempting to run `/usr/sbin/init` in Fedora 34-based ARM container in Travis CI.

**Steps to reproduce the issue:**

1.  Have Dockerfile.fedora-34 which says
```
FROM registry.fedoraproject.org/fedora:34
RUN dnf install -y --setopt=install_weak_deps=False /usr/sbin/init
```
2. In .travis.yml with
```
arch: arm64-graviton2
```
install podman 3.1.2-1 with
```
. /etc/os-release && echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list && curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add - && sudo apt-get update -y && sudo apt-get install -y podman containernetworking-plugins fuse-overlayfs uidmap slirp4netns
```
build image with
```
- podman build -t systemd -f Dockerfile.fedora-34 .
```
and attempt to run the container with
```
- podman run --name systemd -ti --rm systemd /usr/sbin/init
```

**Describe the results you received:**

https://travis-ci.com/github/adelton/freeipa-container/jobs/501607368
```
systemd v248-2.fc34 running in system mode. (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization podman.
Detected architecture arm64.
Welcome to Fedora 34 (Container Image)!
Failed to create /user.slice/user-2000.slice/user@2000.service/user.slice/podman-6674.scope/init.scope control group: Operation not permitted
Failed to allocate manager object: Operation not permitted
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
```

**Describe the results you expected:**

No error, container running fine.

**Additional information you deem important (e.g. issue happens only occasionally):**

On AMD64, the same steps lead to working container in Travis CI:
https://travis-ci.com/github/adelton/freeipa-container/jobs/501611054

**Output of `podman version`:**

I did not run it but it's podman 3.1.2-1 installed from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04.

**Output of `podman info --debug`:**

I did not run it but it's podman 3.1.2-1 installed from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04.

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

I did not run it but it's podman 3.1.2-1 installed from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04.

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is Travis CI Ubuntu 20.04 ARM64 VM.

**Comment by adelton** [comment]
This worked fine with Fedora 33-based container in the same Travis CI setup.

**Comment by mheon** [comment]
Any chance you can get a `--log-level debug` added to the very end of that `podman run` command (after `/usr/sbin/init` - we want it to be an argument to systemd)? Systemd is very unhelpful about what actually went wrong at default log level.

**Comment by adelton** [comment]
https://travis-ci.com/github/adelton/freeipa-container/jobs/501711567
```
systemd v248-2.fc34 running in system mode. (+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified)
Detected virtualization podman.
Detected architecture arm64.
Detected initialized system, this is not the first boot.
Welcome to Fedora 34 (Container Image)!
Hostname was already set to <91ead6682e99>.
Failed to add address 127.0.0.1 to loopback interface: Operation not permitted
Failed to add address ::1 to loopback interface: Operation not permitted
Failed to bring loopback interface up: Operation not permitted
Failed to read AF_UNIX datagram queue length, ignoring: No such file or directory
Setting 'fs/file-max' to '9223372036854775807'.
Failed to bump fs.file-max, ignoring: Permission denied
Setting 'fs/nr_open' to '2147483640'.
Failed to bump fs.nr_open, ignoring: Permission denied
Failed to read memory.limit_in_bytes cgroup attribute, ignoring cgroup memory limit: No such file or directory
Found cgroup on /sys/fs/cgroup/systemd, legacy hierarchy
Using cgroup controller name=systemd. File system hierarchy is at /sys/fs/cgroup/systemd/user.slice/user-2000.slice/user@2000.service/user.slice/podman-6737.scope.
Failed to create /user.slice/user-2000.slice/user@2000.service/user.slice/podman-6737.scope/init.scope control group: Operation not permitted
Failed to allocate manager object: Operation not permitted
[!!!!!!] Failed to allocate manager object.
Exiting PID 1...
```

**Comment by mheon** [comment]
Alright, it's an EPERM trying to create a cgroup, specifically in Travis ARM64 (AMD64 works). Is this a travis VM, or container?

**Comment by mheon** [comment]
I do wonder about the underlying OS being different - possibly a different kernel or systemd config?

**Comment by adelton** [comment]
> Is this a travis VM, or container

It is a VM, defined with
```
virt: vm
arch: arm64-graviton2
group: edge
```

**Comment by rhatdan** [comment]
@giuseppe PTAL.

**Comment by rhatdan** [comment]
@giuseppe any ideas on this one?

**Comment by giuseppe** [comment]
looks like the user doesn't own the cgroup and then systemd refuses to run without cgroups.

Could you wrap the call to podman with `systemd-run --scope --user` and see if it makes any difference?

I also suggest to add `--log-level debug` to podman, so we can check if it is failing to create a new cgroup

**Comment by adelton** [comment]
Here's the run with
```
systemd-run --scope --user podman run --log-level debug --name systemd -ti --rm systemd /usr/sbin/init --log-level debug
```
https://travis-ci.com/github/adelton/freeipa-container/jobs/518998380

**Comment by giuseppe** [comment]
is the job triggered if I open a PR against your github repo?

Maybe it will be easier for me to debug what is going on

**Comment by adelton** [comment]
No. I'm pretty lot on the Travis CI credits at this point so I only run things manually when necessary.

**Comment by giuseppe** [comment]
I can't spot anything strange in the debug log.

Would be helpful to also print `find /sys/fs/cgroup/ -type d -exec stat \{\} \; && cat /proc/self/cgroup && ps auxww`

**Comment by adelton** [comment]
Here you go: https://travis-ci.com/github/adelton/freeipa-container/builds/230846266

**Comment by giuseppe** [comment]
the cgroup seems to be configured correctly, so I don't think it is an ownership problem.

I'd give it a try with seccomp and AppArmor disabled: `--security-opt seccomp=unconfined --security-opt apparmor=unconfined`

**Comment by adelton** [comment]
That worked: https://travis-ci.com/github/adelton/freeipa-container/builds/230860587

Now to figure out which of those did the trick.

**Comment by adelton** [comment]
So it turns out, both are actually needed to make systemd in rootless podman container work.

**Comment by rhatdan** [comment]
Could you look into /var/log/audit/audit.log to see what seccomp failures were being denied

ausearch -m seccomp

**Comment by adelton** [comment]
> So it turns out, both are actually needed to make systemd in rootless podman container work.

I take that back -- `--security-opt seccomp=unconfined` helped.

**Comment by rhatdan** [comment]
The seccomp failure should be fixed, we need to know which syscalls are being blocked.

**Comment by adelton** [comment]
When I try `ausearch`, I get
```
/home/travis/.travis/functions: line 109: ausearch: command not found
```
and I have no idea how to get it on that Travis CI Ubuntu. And when I try to grep it directly with `sudo grep -i seccomp /var/log/audit/audit.log`, I get
```
grep: /var/log/audit/audit.log: No such file or directory
```

I think I'll leave it with you guys, for the FreeIPA container `--security-opt seccomp=unconfined` is enough as a workaround.

**Comment by rhatdan** [comment]
Do you get journal logs?

**Comment by adelton** [comment]
I tried that with `sudo journalctl -l | grep -i seccomp` but did not see anything related to seccomp in the output: https://travis-ci.com/github/adelton/freeipa-container/builds/230870090

**Comment by rhatdan** [comment]
Well unless you can get us the seccomp failure, we have no way to fix.  Closing, reopen if you descover what syscall is being blocked.
