### ISSUE TITLE
Update from containers-common 100:1-14 to 100:1-15 breaks SSH login to container

### ISSUE THREAD

**Issue by veita** [containers/podman#10164]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Clone https://github.com/veita/podman-issue

2. Follow the instruction in the README to build and run the test image.

**Describe the results you received:**

With `containers-common 100:1-14` SSH login to the running container is possible. After update to `containers-common 100:1-15` SSH login is no longer possible.

`journalctl` in the running container shows
```
Apr 27 22:31:25 f420cd7310bc systemd[1]: Started D-Bus System Message Bus.
Apr 27 22:31:29 f420cd7310bc sshd[223]: Accepted password for root from 10.1.1.10 port 52042 ssh2
Apr 27 22:31:29 f420cd7310bc sshd[223]: pam_unix(sshd:session): session opened for user root by (uid=0)
Apr 27 22:31:29 f420cd7310bc sshd[230]: fatal: linux_audit_write_entry failed: Operation not permitted
Apr 27 22:31:29 f420cd7310bc sshd[223]: Received disconnect from 10.1.1.10 port 52042:11: disconnected by user
Apr 27 22:31:29 f420cd7310bc sshd[223]: Disconnected from user root 10.1.1.10 port 52042
Apr 27 22:31:29 f420cd7310bc sshd[223]: pam_unix(sshd:session): session closed for user root
```
**Describe the results you expected:**

SSH login to the running container should be possible.

**Additional information you deem important (e.g. issue happens only occasionally):**
The container is run by root.

```bash
root ~ # lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

root ~ # uname -a
Linux vmdebianplay 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

root ~ # podman version
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.14
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64

root ~ # buildah version
Version:         1.19.6
Go Version:      go1.15.2
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.10.2
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64

root ~ # cat /etc/apt/sources.list.d/podman.list 
deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/ /
```
**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Comment by rhatdan** [comment]
We have dropped audit_write capability from containers.conf to make all containers more secure.  You will either need to edit the containers.conf file in /etc/containers/containers.conf to add the capability in general or modify your container by adding the capability.

podman run --cap-add audit_write ...

@giuseppe Don't we have a workaround for this in seccomp rules?

**Comment by veita** [comment]
With `--cap-add audit_write` the error `linux_audit_write_entry failed: Operation not permitted` disappeared.

However, login via SSH does not succeed due to the following error:

```
Apr 28 12:47:52 a13cf1157f93 sshd[226]: Accepted password for root from 10.1.1.10 port 51756 ssh2
Apr 28 12:47:52 a13cf1157f93 sshd[226]: pam_loginuid(sshd:session): Error writing /proc/self/loginuid: Operation not permitted
Apr 28 12:47:52 a13cf1157f93 sshd[226]: pam_loginuid(sshd:session): set_loginuid failed
Apr 28 12:47:52 a13cf1157f93 sshd[226]: pam_unix(sshd:session): session opened for user root by (uid=0)
Apr 28 12:47:52 a13cf1157f93 sshd[226]: error: PAM: pam_open_session(): Cannot make/remove an entry for the specified session
Apr 28 12:47:52 a13cf1157f93 sshd[226]: Received disconnect from 10.1.1.10 port 51756:11: disconnected by user
Apr 28 12:47:52 a13cf1157f93 sshd[226]: Disconnected from user root 10.1.1.10 port 51756
```

**Comment by mheon** [comment]
I believe you also need `CAP_AUDIT_CONTROL` - `--cap-add audit_write,audit_control`

**Comment by rhatdan** [comment]
I would hope you do not need audit_control.  (Audit_control allows you do adjust the auditing subsystem, this could be very dangerous, for instance telling the system to stop watching for modifications on a file.).  audit_write just allows you to write messages that end up being recorded in /var/log/audit/audit.log.  I consider this dangerous because a container could cause the audit subsystem to write a record that a monitoring tool could take action on.  But this is a much lower risk to being able to manage audit.

**Comment by veita** [comment]
`--cap-add audit_write,audit_control` works.

You can test it with the container linked above (https://github.com/veita/podman-issue).

**Comment by rhatdan** [comment]
Does it work without audit_control?

**Comment by veita** [comment]
Yes, `--cap-add audit_write,audit_control` works. `audit_control` alone doesn't work.

**Comment by rhatdan** [comment]
I want you to do `--cap-add audit_write` and see if this works.  I don't want you adding audit_control.

**Comment by veita** [comment]
This is the same as above: https://github.com/containers/podman/issues/10164#issuecomment-828430763

`--cap-add audit_write` alone does not work.

**Comment by rhatdan** [comment]
Yuck.  Why do you want to run a login program within a container anyways as opposed to logging into the system and then being stuck into a container?

**Comment by veita** [comment]
Simplicity. The containers provide test environments where applications and services can be installed and tested. They run on remote servers and provide SSH login with "publicly" known passwords or pre-installed keys on different ports. Security is not a concern.

For me Systemd support is one of Podman's biggest selling points. Since it allows installing applications composed of different services in a single container we could replace virtual machines with containers. No need for tedious container orchestration. This speeds things up. It's great. :)

**Comment by rhatdan** [comment]
Ok in that case you pretty much are running the equivalent to a VM within a container, so allowing this access is not as big a deal.

**Comment by veita** [comment]
That's true. However, since the fix is rather non-obvious, and I am certainly not the only person with this idea, it should probably be documented somewhere. ;-)

**Comment by rhatdan** [comment]
It is really difficult to `document` all of the multitude of security issues that can arise from running millions of different applications within containers, without advising people to just do --privileged.
The biggest issue is with the linux kernel, telling you why you get permission denied, and then figuring out which kernel subset is causing the error, SELinux, Seccomp, User Namespace, Dropped Capabilities, ...

So I am not hopefully how to document all of these.
