### ISSUE TITLE
Podman >= 2.2.0 is statically linked with LGPLv3 code

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/podman#10163]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug (perhaps?)

**Description**

Podman >= 2.2.0 is statically linked with https://github.com/juju/ansiterm , which is licensed under the terms of LGPLv3.
https://github.com/containers/podman/blob/v2.2.0/vendor/github.com/juju/ansiterm/LICENSE

Podman (Apache License 2.0) is probably not expected to be statically linked with LGPLv3 packages. (IANAL)

**Steps to reproduce the issue:**

```console
$ go mod why github.com/juju/ansiterm
# github.com/juju/ansiterm
github.com/containers/podman/v3/libpod/image
github.com/containers/image/v5/pkg/shortnames
github.com/manifoldco/promptui
github.com/juju/ansiterm
```

**Comment by AkihiroSuda** [comment]
https://github.com/containers/podman/blob/db1d2ff111ee9b012779ff3a5279a982520ccda4/vendor/github.com/juju/ansiterm/LICENSE#L1-L28

The license file has "exception" rule, so this might not be a problem.

**Comment by rhatdan** [comment]
I have no idea if this is a problem or not, I would tend to think, no.
@vrothberg PTAL

I guess we could ask the developers of github.com/juju/ansiterm for their opinion.

**Comment by AkihiroSuda** [comment]
Related: https://github.com/kubernetes/steering/issues/21

Kubernetes seems to have deleted a LGPLv3 library with the same exception clauses, but they didn't seem to have made any conclusion whether it is compatible with Apache License 2.0 or not.

**Comment by vrothberg** [comment]
I _interpret_ the exception as giving us permission to use it.  But I am not qualified to make a call.  I will reach out to a Red Hat peer.

**Comment by rhatdan** [comment]
As I recall the peer said this is fine for us to ship.
