### ISSUE TITLE
Podman emits a died event instead of die event when container stops

### ISSUE THREAD

**Issue by davemulford** [containers/podman#10168]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When a container is stopped, podman emits a `died` event. This is incompatible with Docker that emits a `die` event.

**Steps to reproduce the issue:**

1. Run a container and make sure that it exits.

```
# podman run --rm -ti registry.redhat.io/rhel8/support-tools id
uid=0(root) gid=0(root) groups=0(root)
```

2. Verify the `died` event is generated.

```
# podman events --since 5m | grep die
2021-04-28 11:23:27.633897365 -0400 EDT container died 69d9b51cb1f6a4916404880f474c34943be795f9ce5e8973f788a326658f1077 (image=registry.redhat.io/rhel8/support-tools, name=festive_allen)
```

**Describe the results you received:**

Podman generated a `died` event.

**Describe the results you expected:**

I'd expect to see a `die` event.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Version:      3.2.0-dev
API Version:  3.2.0-dev
Go Version:   go1.15.11
Git Commit:   ec42db68e0b4b703d3e4ab173630ab386aaf052e
Built:        Sat Aug  4 00:00:00 2018
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.20.1-dev
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.27-2.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 24
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: woodhouse
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.11-200.fc33.x86_64
  linkmode: dynamic
  memFree: 51972804608
  memTotal: 135073447936
  ociRuntime:
    name: crun
    package: crun-0.19.1-2.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.19.1
      commit: 1535fedf0b83fb898d449f9680000f729ba719f5
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.9-1.fc33.x86_64
    version: |-
      slirp4netns version 1.1.9
      commit: 4e37ea557562e0d7a64dc636eff156f64927335e
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 4208148480
  swapTotal: 4294963200
  uptime: 2009h 11m 51.68s (Approximately 83.71 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/dmulford/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.5.0-1.fc33.x86_64
      Version: |-
        fusermount3 version: 3.9.3
        fuse-overlayfs: version 1.5
        FUSE library version 3.9.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/dmulford/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 4
  runRoot: /run/user/1000/containers
  volumePath: /home/dmulford/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.0-dev
  Built: 1533340800
  BuiltTime: Sat Aug  4 00:00:00 2018
  GitCommit: ec42db68e0b4b703d3e4ab173630ab386aaf052e
  GoVersion: go1.15.11
  OsArch: linux/amd64
  Version: 3.2.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

podman built from source at commit ba9c1f3f17a4f0086d9ac25fe0f211b3c75e514a.

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine running Fedora 33 and podman built from source at commit ba9c1f3f17a4f0086d9ac25fe0f211b3c75e514a.

For reference, Docker generates a `die` event as seen here: https://gist.github.com/davemulford/b9fdf09d377601bb460df138cd89dda1

**Comment by rhatdan** [comment]
Is this something to just fix in the API or fix all over, this could be a breaking change for existing users of podman?
@jwhonce @baude @mheon WDYT?

**Comment by mheon** [comment]
We haven't really made solid promises about Events matching exactly, and we already have a number of apps (Cockpit notably) using the existing Died event, so I don't think we can change at this point. Maybe a Podman 4.0 thing next year?

Changing it in the Compat API does seem reasonable as a solution for the moment.

**Comment by mheon** [comment]
Reopening given we didn't fix this fully - just the API bit.

**Comment by rhatdan** [comment]
@davemulford What do you think?  Is changing the API good enough.  I think the died reads better in Podman the container die.

**Comment by rhatdan** [comment]
Since we did not get a response, I take it as it is good enough.  Closing.
