### ISSUE TITLE
Question: podman REST API exec streaming

### ISSUE THREAD

**Issue by scabala** [containers/podman#10169]
Hi,
I have not found this information anywhere and I'm not that proficient with Go to read it from source so here's my question:
is it possible to stream output data from command using Podman REST API exec start endpoint (`/libpod/exec/{id}/start`)?
My goal is to update client with live data when executing long command inside container. I wanted to know if it's possible at all before hacking around.

**Comment by rhatdan** [comment]
Yes this is what we are doing with podman-remote now.
