### ISSUE TITLE
Fedora 34 podman rootless container accessing host

### ISSUE THREAD

**Issue by akostadinov** [containers/podman#10180]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am trying to access host machine from podman container with default container network settings as in Fedora 34. I can't.
I see that default gateway in container is 10.0.2.2 but then trying to access it I see:

```
$ podman run --name porxy --rm --add-host=host.docker.internal:10.0.2.2 -p 3008:3008 -ti --entrypoint /bin/bash quay.io/openshift/origin-cli:4.6
[root@fa8d95cd7b12 /]# ip route list
default via 10.0.2.2 dev tap0 
10.0.2.0/24 dev tap0 proto kernel scope link src 10.0.2.100 
[root@fa8d95cd7b12 /]# curl 10.0.2.2:3000
curl: (7) Failed to connect to 10.0.2.2 port 3000: Network is unreachable
```

That also begs another question. I [docs](https://podman.io/getting-started/network.html#container---container-communication) I see `Host_IP_Address`. Can it be documented what is `Host_IP_Address`?

**Steps to reproduce the issue:**

1. `$ podman run --name porxy --rm --add-host=host.docker.internal:10.0.2.2 -p 3008:3008 -ti --entrypoint /bin/bash quay.io/openshift/origin-cli:4.6`

2. `# curl 10.0.2.2:3000`

**Describe the results you received:**
```
curl: (7) Failed to connect to 10.0.2.2 port 3000: Network is unreachable
```

**Describe the results you expected:**

I would expect either a successful response or at least some more reasonable error than `Network is unreachable`. Maybe connection refused or whatever,  just at least reach the host.

**Output of `podman version`:**

```
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.16
Built:        Thu Apr 22 16:11:28 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.20.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.27-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: koTak
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 10000
      size: 2000
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 10000
      size: 2000
  kernel: 5.11.15-300.fc34.x86_64
  linkmode: dynamic
  memFree: 10563592192
  memTotal: 33403404288
  ociRuntime:
    name: crun
    package: crun-0.19.1-2.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.19.1
      commit: 1535fedf0b83fb898d449f9680000f729ba719f5
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.9-1.fc34.x86_64
    version: |-
      slirp4netns version 1.1.8+dev
      commit: 6dc0186e020232ae1a6fcc1f7afbc3ea02fd3876
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 16982728704
  swapTotal: 16982728704
  uptime: 39h 36m 42.39s (Approximately 1.62 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/avalon/.config/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 5
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.5.0-1.fc34.x86_64
      Version: |-
        fusermount3 version: 3.10.2
        fuse-overlayfs: version 1.5
        FUSE library version 3.10.2
        using FUSE kernel interface version 7.31
  graphRoot: /var/lib/libvirt/images/containers/avalon
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 8
  runRoot: /run/user/1001/containers
  volumePath: /var/lib/libvirt/images/containers/avalon/volumes
version:
  APIVersion: 3.1.2
  Built: 1619097088
  BuiltTime: Thu Apr 22 16:11:28 2021
  GitCommit: ""
  GoVersion: go1.16
  OsArch: linux/amd64
  Version: 3.1.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.1.2-1.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by AkihiroSuda** [comment]
You need --net slirp4netns:allow_host_loopback=true .
This is set to false by default for security reason.

https://github.com/containers/podman/blob/v3.1.2/docs/source/markdown/podman-pod-create.1.md

**Comment by akostadinov** [comment]
@AkihiroSuda , this makes sense, thank you. How about updating the getting started guide with this information? Possible to reopen and assign to somebody with a good idea how to do?

https://podman.io/getting-started/network.html#container---container-communication

**Comment by afro-coder** [comment]
Can I help with the documentation if possible? any pointers would help!

**Comment by rhatdan** [comment]
@afro-coder Look at the podman.io git repo and add docs to suggested lines above.

**Comment by afro-coder** [comment]
Thanks @rhatdan working on this.
