### ISSUE TITLE
Can't use podman alongside docker

### ISSUE THREAD

**Issue by codefist** [containers/podman#10186]
The screenshot says it all.
![Screenshot from 2021-05-01 08-19-49](https://user-images.githubusercontent.com/16125676/116782314-46670c80-aa56-11eb-9b83-653eed3e8e90.png)

I need to have my UID in this file for docker to be able to operate in the same manner as podman's "rootless" which I need to facilitate my development environment workflow.

Podman should not give a F about my UID being in this file.

**Comment by rhatdan** [comment]
Podman will automatically add your User to the user namespace as either UID=0 (default) or as UID=UID if you specify --userns=keep-id.  The issue here is in /etc/subuild, you are attempting to set your UID to some other value, and that is why it is complaining.

**Comment by giuseppe** [comment]
yes, that is an invalid configuration for `/etc/sub?id`.  It should not include your own ID
