### ISSUE TITLE
(Rootless) Container with pod that is connected to network cannot run after machine reboot

### ISSUE THREAD

**Issue by phongngthanh** [containers/podman#10196]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Run the following command
```bash
# Create network
podman network create test_network
# Create a pod and connect to the network
podman pod create --name test_pod --network test_network --publish 8000:80
# Run a container that with the pod
podman run --name test-container --pod test_pod --restart=unless-stopped --detach=True containous/whoami:latest
```
The container runs normally. (tested via curl localhost:8000)
2. Reboot the machine and recreate the container
```bash
# Remove the previous container
podman rm -f test-container
# Recreate the container
podman run --name test-container --pod test_pod --restart=unless-stopped --detach=True containous/whoami:latest
```

**Describe the results you received:**
Container failed to be recreated. Errors message:
```bash
ERRO[0000] error starting some container dependencies   
ERRO[0000] "command rootless-cni-infra [alloc c34fd7c5eab6b9c8ec795c8521602efe49f022f6528724450bce4b6cd01eee2d test_network test_pod   ] in container f018fec5bcc075949a2b403462f5d095f5f2184cddc4ae89d6822e32d534e7a5 failed with status 1, stdout=\"\", stderr=\"failed to open netns \\\"/proc/293234/ns/net\\\": failed to Statfs \\\"/proc/293234/ns/net\\\": no such file or directory\\n\"" 
Error: error starting some containers: internal libpod error
```
**Describe the results you expected:**
Container recreation runs normally

**Additional information you deem important (e.g. issue happens only occasionally):**
- Containers can be created normally if the pod is recreated
```bash
podman pod rm test_pod
podman pod create --name test_pod --network test_network --publish 8000:80
podman run --name test-container --pod test_pod --restart=unless-stopped --detach=True containous/whoami:latest
```
**Output of `podman version`:**

```
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.16
Built:        Thu Apr 22 20:11:28 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.1.2-1.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Luap99** [comment]
see https://github.com/containers/podman/discussions/10036#discussioncomment-629380

**Comment by Luap99** [comment]
I close this since this is already fixed in the master branch.
