### ISSUE TITLE
Podman Auto-Update Does Not Update Some Containers Due to Expired Certificate

### ISSUE THREAD

**Issue by Saroufim** [containers/podman#10198]
/kind bug

**Description**

Podman auto-update complains some certificates are expired for docker.io even though it can pull updates from other containers that are hosted on docker.io just fine. 

**Steps to reproduce the issue:**

1. Install containers with the correct update label

2. Update them with podman auto-update

3. notice the error

**Describe the results you received:**
error auto-updating container "ccd..": image check for "redis" failed: error pinging docker registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": x509: certificate has expired or is not yet valid: current time 2021-03-25T02:15:51Z is before 2021-04-25T00:00:00Z

**Describe the results you expected:**
All containers to updated normally

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.8
Built:        Fri Feb 19 16:57:15 2021
OS/Arch:      linux/arm64

**Output of `podman info --debug`:**

host:
  arch: arm64
  buildahVersion: 1.19.4
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.26-1.fc33.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 1edc5a142b9c009741e959ea66fd0436462acab9'
  cpus: 4
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: pi
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.11.11-200.fc33.aarch64
  linkmode: dynamic
  memFree: 99315712
  memTotal: 4004024320
  ociRuntime:
    name: crun
    package: crun-0.18-5.fc33.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 0.18
      commit: 808420efe3dc2b44d6db9f1a3fac8361dde42a95
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.9-1.fc33.aarch64
    version: |-
      slirp4netns version 1.1.9
      commit: 4e37ea557562e0d7a64dc636eff156f64927335e
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 1996484608
  swapTotal: 2001727488
  uptime: 26h 27m 57.96s (Approximately 1.08 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /var/home/pi/.config/containers/storage.conf
  containerStore:
    number: 20
    paused: 0
    running: 18
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.4.0-1.fc33.aarch64
      Version: |-
        fusermount3 version: 3.9.3
        fuse-overlayfs: version 1.4
        FUSE library version 3.9.3
        using FUSE kernel interface version 7.31
  graphRoot: /var/home/pi/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 98
  runRoot: /run/user/1000/containers
  volumePath: /var/home/pi/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1613753835
  BuiltTime: Fri Feb 19 16:57:15 2021
  GitCommit: ""
  GoVersion: go1.15.8
  OsArch: linux/arm64
  Version: 3.0.1

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

podman-3.0.1-1.fc33.aarch64

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Checked troubleshooting guide but did not compile podman from source

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical raspberry pi 4 with Fedora IoT 34 Aarch64 (I started having this error after updating to version 34 of Fedora).

**Comment by vrothberg** [comment]
Thanks for reaching out!

>  Physical raspberry pi 4 with Fedora IoT 34 Aarch64 (I started having this error after updating to version 34 of Fedora).

The `podman info` output states that you're on Fedora 33, can you clarify?  The certificates on the host are outside of Podman's control. Is your machine on the latest updates?

**Comment by Saroufim** [comment]
Hello. Thanks for pointing that out. Sometimes the answer is right in plain sight. The issue was that I triggered the upgrade but on that specific system, rpm-ostree did not actually apply the offline updates. I've tried several times afterwards to no avail. Seems like the problem isn't related to podman but to rpm-ostree. Thanks a lot.
