### ISSUE TITLE
How to start a podman container on the host within a podman container? 

### ISSUE THREAD

**Issue by LuvsicYue** [containers/podman#10203]
Using docker, I can add "-v /var/run/docker.sock:/var/run/docker.sock" to mount the host docker.sock so that I am able to call **docker run** inside the container to start a sibling container on the host. But this behavior depends on that docker CLI is connecting with docker daemon. How can I achieve the same thing for podman? How can I start a container on the host from inside a podman container?

**Comment by mheon** [comment]
With Podman 2.0 and higher, we provide a REST API accessible via Unix socket (default location for root being /run/podman.sock) and the ability to connect to an API server by adding the `--remote` flag to a Podman command. The API can be enabled via `systemctl enable podman.sock` if your distribution ships the default systemd unit files.

**Comment by mheon** [comment]
So, generally speaking, as of now you can use the same approach by mounting in the Podman socket and using the `--remote` flag or the podman-remote client, which only connects to a server.

**Comment by LuvsicYue** [comment]
@mheon In order to connect to the server on the host from the container, I believe I also need to install podman inside the container? Does it matter if the podman version inside the container is different from the host podman version?

**Comment by mheon** [comment]
For versions 3.0 and lower, yes - the version on host and in the container will need to match. 3.1 and up should not require a strict match.
