### ISSUE TITLE
Upgrading to latest released podman

### ISSUE THREAD

**Issue by charbel14** [containers/podman#10218]
This is not a defect of feature request, but a general question.

If there a way to force upgrade my Redhat 8 podman to the latest release version? Currently my repo is only pulling podman 2.2.1, I tried reposync but that changed nothing.
I am assuming the only option I have is to talk to my local repo admin? Or are the other options?
Thanks

**Comment by rhatdan** [comment]
Have you followed the instructions on 

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/building_running_and_managing_containers/index

I think podman 3.0 only shows up in RHEL8.4 which should be shipping this week.

**Comment by rhatdan** [comment]
https://podman.io/getting-started/installation has information on getting RHEL8 tools as well.
