### ISSUE TITLE
rootless CNI infra image not present

### ISSUE THREAD

**Issue by lejeczek** [containers/podman#10217]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

-> $ echo; podman run -dt --log-level=debug --restart=always --security-opt label=disable --pod=${_POD} --name someName docker.io/library/wordpress
...
...
DEBU[0000] Container 212c4910e502c32688ce3d6de3791a7d3d1b6c542c96a5d467da26f303d15d58 storage is already unmounted, skipping... 
ERRO[0000] error starting some container dependencies   
ERRO[0000] "rootless CNI infra image not present - please build image from https://github.com/containers/podman/blob/v3.0.1-rhel/contrib/rootless-cni-infra/ and tag as \"rootless-cni-infra\"" 
DEBU[0000] ExitCode msg: "error starting some containers: internal libpod error" 
Error: error starting some containers: internal libpod error

I've reset podman system, removed bits manually, rpm-reinstalled I believe all involved bits. I've also tried what that error message says on 'github' - which fails to build.
I'm on CentOS Stream with:
container-selinux-2.158.0-1.module_el8.5.0+736+58cc1a5a.noarch
runc-1.0.0-70.rc92.module_el8.5.0+736+58cc1a5a.x86_64
containers-common-1.2.2-6.module_el8.5.0+736+58cc1a5a.x86_64
libcap-2.26-4.el8.x86_64
containernetworking-plugins-0.9.1-1.module_el8.5.0+736+58cc1a5a.x86_64
podman-3.0.1-6.module_el8.5.0+736+58cc1a5a.x86_64
podman-catatonit-3.0.1-6.module_el8.5.0+736+58cc1a5a.x86_64

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Luap99** [comment]
As the error message states you have to build the image yourself.

**Comment by lejeczek** [comment]
As I said in original report - I've also tried what that error message says on 'github' - which fails to build

**Comment by Luap99** [comment]
Please provide the steps you used. This should work:
```
git clone https://github.com/containers/podman.git
cd podman
git checkout v3.0.1-rhel
cd contrib/rootless-cni-infra/
podman build -t rootless-cni-infra .
```

**Comment by Luap99** [comment]
@lejeczek Were you able to build the image successfully?

**Comment by lejeczek** [comment]
Hi. Yes I can confirm following above instruction works.
But if I might ask - this is user manual intervention: how 'rootless-cni-infra' gets into the system initially, originally?
many thanks, L.

**Comment by Luap99** [comment]
The upstream version does pull the image automatically from quay.io, however this does not work for environments without internet access. RedHat decided that the users should manually build/distribute the image to circumvent such limitation.

With podman v3.2 this image is no longer needed and rootless cni will work in all environments without extra setup.
