### ISSUE TITLE
Pull from `docker-daemon` is not working.

### ISSUE THREAD

**Issue by matejvasek** [containers/podman#10228]
Pulling from local docker daemon to podman is not working.
```
~> podman pull "docker-daemon:index.docker.io/library/lifecycle:matejs"
Error: unsupported transport "docker-daemon" for pulling
```

This has been introduced in `migrate Podman to containers/common/libimage` a278195af3423f882c1f5bb218792f7c2ce10a3c.

**Comment by rhatdan** [comment]
Fixed by https://github.com/containers/common/pull/526
@matejvasek Please verify this fixes the issue.

**Comment by rhatdan** [comment]
Reopen if I am mistaken.

**Comment by matejvasek** [comment]
@rhatdan looks like it fixes the issue, but this should be closed once we put newer version of `containers/common` into `podman`s `go.mod` right?

**Comment by rhatdan** [comment]
Well I know that is about to happen, and I am likely to forget to close, so I jumped the chance.
