### ISSUE TITLE
podman-remote build --iidfile : spurious "Copying config" appears in iidfile

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#10233]
Please bear with me, I realize this is weird.  Every so often, `podman-remote build`, with just the right set of flags, writes an unwanted "Copying config" into the iidfile:

In window 1:
```console
$ podman system service --timeout=0
```
In window 2:
```console
$ cat Containerfile
FROM scratch
$ while :;do ../bin/podman-remote build --layers=false --force-rm=false --iidfile /tmp/foo.iid -t scratch-image .;grep Copying /tmp/foo.iid && break;../bin/podman rmi scratch-image;done
STEP 1: FROM scratch
STEP 2: COMMIT scratch-image
Getting image source signatures
Copying blob sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef
Copying config sha256:5eb5601aaca27b05615d6fb9a7ff44692ee79d4ab4ea5e2ce9726ed95853a577
Writing manifest to image destination
Storing signatures
--> 5eb5601aaca
Successfully tagged localhost/scratch-image:latest
sha256:Copying config sha256:5eb5601aaca27b05615d6fb9a7ff44692ee79d4ab4ea5e2ce9726ed95853a577
```
(Expected: just `sha256:5eb....`, without `Copying config`)

It does not happen with non-remote `podman`. It does not happen without `--layers=false --force-rm=false`. Even with all these flags and settings, it sometimes takes 2-3 repeats to fail.

**Comment by edsantiago** [comment]
[Sample failure](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5553399140712448/html/bud-remote-fedora-34-root-host.log.html), seen in my buildah-bud + podman-remote PR

**Comment by rhatdan** [comment]
You love to find the weird ones. :^)

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/podman/pull/10242
