### ISSUE TITLE
Data not copying up to volumes for containers created but not started

### ISSUE THREAD

**Issue by vikas-goel** [containers/podman#10262]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When volume and container with this volume are created by docker, that volume gets populated (copied up from the image) and can then be consumed by another container using `--volumes-from`. It does not seem to work with podman. With podman, the workaround is to run `podman container init` after creating the container as described in https://github.com/containers/podman/issues/8041.

Running `podman container init` gives error same as mentioned in https://github.com/containers/podman/issues/8041#issuecomment-710080732. The command, however, does the job.

I am using Docker Compose to create data volume container and then adding the same as a dependency for the service/application in the same Docker Compose configuration YAML file.

With Podman 3.0.2 and later version, I am using podman-docker package to manage my podman containers using Docker Compose. As the said podman command (podman container init) for the workaround is very specific to podman, Docker Compose does not have option to do the same.

Can we have a podman (global) configuration option, say `setup-volume-mount`, that can stay turned off by default. When the option is turned on, the ```podman create --name <name> <container-image>``` behaves same as corresponding `docker` command. That is, the podman should internally prepare the mount, i.e. copy the data without requiring additional commands (podman container init). The error described in https://github.com/containers/podman/issues/8041#issuecomment-710080732 should be ignored.

**Steps to reproduce the issue:**
Same as described in https://github.com/containers/podman/issues/8041

**Describe the results you received:**
Same as described in https://github.com/containers/podman/issues/8041

**Describe the results you expected:**
Same as described in https://github.com/containers/podman/issues/8041

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.0.2-dev
API Version:  3.0.0
Go Version:   go1.15.7
Built:        Tue Mar  2 07:10:06 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.26-1.module+el8.4.0+10198+36d1d0e3.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 0a5175681bdd52b99f1f0f442cbba8f8c126a1c9'
  cpus: 8
  distribution:
    distribution: '"rhel"'
    version: "8.4"
  eventLogger: file
  hostname: flex-vm-02.dc2.ros2100.veritas.com
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-293.el8.x86_64
  linkmode: dynamic
  memFree: 14160437248
  memTotal: 33511845888
  ociRuntime:
    name: runc
    package: runc-1.0.0-70.rc92.module+el8.4.0+10198+36d1d0e3.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 16921104384
  swapTotal: 16924012544
  uptime: 61h 34m 49.72s (Approximately 2.54 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 2
    stopped: 3
  graphDriverName: overlay
  graphOptions:
    overlay2.size: 10G
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 3
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1614697806
  BuiltTime: Tue Mar  2 07:10:06 2021
  GitCommit: ""
  GoVersion: go1.15.7
  OsArch: linux/amd64
  Version: 3.0.2-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.0.1-3.module+el8.4.0+10198+36d1d0e3.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Red Hat Enterprise Linux 8.4 Beta
VMware virtual machine

**Comment by vikas-goel** [comment]
Hi @mheon , @rhatdan,
Is it possible to get this fixed in podman-3.2?

**Comment by mheon** [comment]
I doubt it. This would involve a significant refactor of the way volume mount and copy-up happens to move it to container creation from first-time initialization. We're planning 3.2.0 final later this week, and this is too much work and too large of a change to land before then. Maybe in 3.3.x.

**Comment by vikas-goel** [comment]
I see. Is there a timeline for 3.3?

**Comment by mheon** [comment]
If we maintain our current pace, mid to late July seems reasonable?

**Comment by vikas-goel** [comment]
That will work. Thank you.

**Comment by vikas-goel** [comment]
Hi @mheon , just checking on this one.

**Comment by vikas-goel** [comment]
@mheon , is this planned for the July release?

**Comment by mheon** [comment]
No one has begun work on it yet.

**Comment by vikas-goel** [comment]
@mheon ,
I looked at the code for fixing the issue. Would the following two patches be good?

1. containers/common
```
diff --git a/pkg/config/config.go b/pkg/config/config.go
index 68076b1..b30b4ff 100644
--- a/pkg/config/config.go
+++ b/pkg/config/config.go
@@ -125,6 +125,9 @@ type ContainersConfig struct {
        // container that forwards signals and reaps processes.
        Init bool `toml:"init,omitempty"`

+       // Initialize container during creation
+       InitOnCreate bool `toml:"init_on_create,omitempty"`
+
        // InitPath is the path for init to run if the Init bool is enabled
        InitPath string `toml:"init_path,omitempty"`

```

2. container/podman
```
diff --git a/libpod/runtime_ctr.go b/libpod/runtime_ctr.go
index 6c69d1b..1d17ab4 100644
--- a/libpod/runtime_ctr.go
+++ b/libpod/runtime_ctr.go
@@ -446,6 +446,14 @@ func (r *Runtime) setupContainer(ctx context.Context, ctr *Container) (_ *Contai
                toLock.lock.Lock()
                defer toLock.lock.Unlock()
        }
+
+       // Auto initialize the container during creation if user opted to.
+       if r.config.Containers.InitOnCreate {
+               if err := ctr.init(ctx, false); err != nil {
+                       return nil, err
+               }
+       }
+
        // Add the container to the state
        // TODO: May be worth looking into recovering from name/ID collisions here
        if ctr.config.Pod != "" {
```

I'm unable create branches for these repos. How can I contribute to this issue?

**Comment by rhatdan** [comment]
Why can't you create branches for these repos?

**Comment by mheon** [comment]
The patch also won't work - it's happening too soon. Initialization *must* happen after the container is added to the state.

**Comment by vikas-goel** [comment]
> Why can't you create branches for these repos?

GitHub does not show me option to create branch when I type a unique name in the branch text field.

![image](https://user-images.githubusercontent.com/12242590/125206672-54e35880-e23d-11eb-919f-d64598e1756b.png)

**Comment by vikas-goel** [comment]
Thanks @mheon for the review and comment.

> The patch also won't work - it's happening too soon. Initialization _must_ happen after the container is added to the state.

Not sure what "happening to soon" mean. I changed the logic to just prepare container instead of initializing so that there is no init event sent. It would also avoid the "executable file not found in" error as observed in the issue. With this change, I guess we should be okay calling prepare before adding container to state. Let me know if that's not the case.

The new patches look like

1. containers/common
```
diff --git a/pkg/config/config.go b/pkg/config/config.go
index 68076b1..a327b1f 100644
--- a/pkg/config/config.go
+++ b/pkg/config/config.go
@@ -151,6 +151,9 @@ type ContainersConfig struct {
        // NoHosts tells container engine whether to create its own /etc/hosts
        NoHosts bool `toml:"no_hosts,omitempty"`

+       // Prepare container to mount storage during creation
+       PrepareOnCreate bool `toml:"prepare_on_create,omitempty"`
+
        // PidsLimit is the number of processes each container is restricted to
        // by the cgroup process number controller.
        PidsLimit int64 `toml:"pids_limit,omitempty"`
```

2. containers/podman
```
diff --git a/libpod/runtime_ctr.go b/libpod/runtime_ctr.go
index 6c69d1b..f5515ab 100644
--- a/libpod/runtime_ctr.go
+++ b/libpod/runtime_ctr.go
@@ -446,6 +446,14 @@ func (r *Runtime) setupContainer(ctx context.Context, ctr *Container) (_ *Contai
                toLock.lock.Lock()
                defer toLock.lock.Unlock()
        }
+
+       // Prepare container to mount storage during creation if user opted to.
+       if r.config.Containers.PrepareOnCreate {
+               if err := ctr.prepare(); err != nil {
+                       return nil, err
+               }
+       }
+
        // Add the container to the state
        // TODO: May be worth looking into recovering from name/ID collisions here
        if ctr.config.Pod != "" {
```

**Comment by mheon** [comment]
This does not fix the core problem of the earlier patch  - the prepare is happening *before* the container is added to the state, so configuration information is not being saved to the DB. The old init() code was fine but it must be more further down in the function.

**Comment by vikas-goel** [comment]
I see. Thanks for the quick one. I am moving the call after adding the container to the state. I am still keeping it to _prepare()_ so as to avoid the "executable file not found" error.
```
diff --git a/libpod/runtime_ctr.go b/libpod/runtime_ctr.go
index 6c69d1b..200c1a6 100644
--- a/libpod/runtime_ctr.go
+++ b/libpod/runtime_ctr.go
@@ -460,6 +460,14 @@ func (r *Runtime) setupContainer(ctx context.Context, ctr *Container) (_ *Contai
        } else if err := r.state.AddContainer(ctr); err != nil {
                return nil, err
        }
+
+       // Prepare container to mount storage during creation if user opted to.
+       if r.config.Containers.PrepareOnCreate {
+               if err := ctr.prepare(); err != nil {
+                       return nil, err
+               }
+       }
+
        ctr.newContainerEvent(events.Create)
        return ctr, nil
 }
```

Is this okay?

**Comment by vikas-goel** [comment]
Could someone set the “In Progress” label and assign this to me?

**Comment by rhatdan** [comment]
@vikas-goel I am suggesting you fork the project create a branch and open a PR for MAIN.  Not that you create a branch on the main repo.

**Comment by vikas-goel** [comment]
Thank you @rhatdan for the suggestion and assignment.
