### ISSUE TITLE
Docker compatibility: Timestamps are a different format than docker

### ISSUE THREAD

**Issue by candrews** [containers/podman#10267]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**
1. Start a container, pull an image, or do anything else that results in the docker API returning a timestamp

**Describe the results you received:**
All timestamps (such as `StartedAt` and `CreatedAt`) are longer in podman than docker.
"StartedAt":"2021-05-07T13:28:21.783776413-04:00" <- podman
"StartedAt":"2021-05-07T17:27:52.347500403Z" <- docker

Clients, such as `docker-java`, cannot parse the longer timestamps resulting in exceptions, like this:
```
Caused by: java.time.format.DateTimeParseException: Text '2021-05-07T14:37:12.414551043-04:00' could not be parsed at index 29
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
	at org.testcontainers.utility.DockerStatus.isDockerTimestampNonEmpty(DockerStatus.java:78)
	at org.testcontainers.utility.DockerStatus.isContainerStopped(DockerStatus.java:67)
```

Here's an example from docker:
```javascript
{"Id":"sha256:f80194ae2e0ccf0f098baa6b981396dfbffb16e6476164af72158577a7de2dd9","RepoTags":["alpine:3.5"],"RepoDigests":["alpine@sha256:66952b313e51c3bd1987d7c4ddf5dba9bc0fb6e524eed2448fa660246b3e76ec"],"Parent":"","Comment":"","Created":"2019-01-30T22:20:40.179652676Z","Container":"3dcfc9c1f7f8d3ef3a808cc9c492e13d966771908d1e75dca22bdaec5e750bc0","ContainerConfig":{"Hostname":"3dcfc9c1f7f8","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["/bin/sh","-c","#(nop) ","CMD [\\"/bin/sh\\"]"],"ArgsEscaped":true,"Image":"sha256:be4705c10dd809a3a3b0dfd96016943fa43b8731e17321be9e8fe32a7426da62","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":{}},"DockerVersion":"18.06.1-ce","Author":"","Config":{"Hostname":"","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["/bin/sh"],"ArgsEscaped":true,"Image":"sha256:be4705c10dd809a3a3b0dfd96016943fa43b8731e17321be9e8fe32a7426da62","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":null},"Architecture":"amd64","Os":"linux","Size":3995534,"VirtualSize":3995534,"GraphDriver":{"Data":{"MergedDir":"/var/lib/docker/overlay2/569b37dff748becb02407bc50dd54f17265f067b44cbabfe795d93b2ab164a7b/merged","UpperDir":"/var/lib/docker/overlay2/569b37dff748becb02407bc50dd54f17265f067b44cbabfe795d93b2ab164a7b/diff","WorkDir":"/var/lib/docker/overlay2/569b37dff748becb02407bc50dd54f17265f067b44cbabfe795d93b2ab164a7b/work"},"Name":"overlay2"},"RootFS":{"Type":"layers","Layers":["sha256:f566c57e6f2da2364c14195c832b922fd8f4813fd139b8fe45e3454c16e33975"]},"Metadata":{"LastTagTime":"0001-01-01T00:00:00Z"}}
```

And from podman:
```javascript
{"Id":"sha256:f80194ae2e0ccf0f098baa6b981396dfbffb16e6476164af72158577a7de2dd9","RepoTags":["docker.io/library/alpine:3.5"],"RepoDigests":["docker.io/library/alpine@sha256:66952b313e51c3bd1987d7c4ddf5dba9bc0fb6e524eed2448fa660246b3e76ec","docker.io/library/alpine@sha256:f7d2b5725685826823bc6b154c0de02832e5e6daf7dc25a00ab00f1158fabfc8"],"Parent":"","Comment":"","Created":"2019-01-30T22:20:40.179652676Z","Container":"","ContainerConfig":null,"DockerVersion":"18.06.1-ce","Author":"","Config":{"Hostname":"","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["/bin/sh"],"Image":"","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":null},"Architecture":"amd64","Os":"linux","OsVersion":"18.06.1-ce","Size":4238777,"VirtualSize":4238777,"GraphDriver":{"Data":{"UpperDir":"/home/candrews/.local/share/containers/storage/overlay/f566c57e6f2da2364c14195c832b922fd8f4813fd139b8fe45e3454c16e33975/diff","WorkDir":"/home/candrews/.local/share/containers/storage/overlay/f566c57e6f2da2364c14195c832b922fd8f4813fd139b8fe45e3454c16e33975/work"},"Name":"overlay"},"RootFS":{"Type":"layers","Layers":["sha256:f566c57e6f2da2364c14195c832b922fd8f4813fd139b8fe45e3454c16e33975"]},"Metadata":{"LastTagTime":"0001-01-01T00:00:00Z"}}
```

**Describe the results you expected:**
Podman should use the same timestamp format to be compatible with docker.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 3.2.0-rc1
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.20.2-dev
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.27-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: craigatwork
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.11.18-300.fc34.x86_64
  linkmode: dynamic
  memFree: 584716288
  memTotal: 16647507968
  ociRuntime:
    name: crun
    package: crun-0.19.1-2.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.19.1
      commit: 1535fedf0b83fb898d449f9680000f729ba719f5
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.9-1.fc34.x86_64
    version: |-
      slirp4netns version 1.1.8+dev
      commit: 6dc0186e020232ae1a6fcc1f7afbc3ea02fd3876
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 13761241088
  swapTotal: 17024671744
  uptime: 21h 14m 26.11s (Approximately 0.88 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/candrews/.config/containers/storage.conf
  containerStore:
    number: 14
    paused: 0
    running: 14
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.5.0-1.fc34.x86_64
      Version: |-
        fusermount3 version: 3.10.3
        fuse-overlayfs: version 1.5
        FUSE library version 3.10.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/candrews/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 6
  runRoot: /run/user/1000
  volumePath: /home/candrews/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.0-rc1
  Built: 1620248626
  BuiltTime: Wed May  5 17:03:46 2021
  GitCommit: ""
  GoVersion: go1.16.3
  OsArch: linux/amd64
  Version: 3.2.0-rc1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.2.0-0.1.rc1.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 34

**Comment by nanonyme** [comment]
So in other words, timestamps in manifest must be UTC time, not local times?

**Comment by candrews** [comment]
> So in other words, timestamps in manifest must be UTC time, not local times?

To match docker, yes.

**Comment by rcowsill** [comment]
> Here's an example from docker:
> 
> ```js
> {"Id":"sha256:f80194ae2e0ccf0f098baa6b981396dfbffb16e6476164af72158577a7de2dd9","RepoTags":["alpine:3.5"],"RepoDigests":["alpine@sha256:66952b313e51c3bd1987d7c4ddf5dba9bc0fb6e524eed2448fa660246b3e76ec"],"Parent":"","Comment":"","Created":"2019-01-30T22:20:40.179652676Z","Container":"3dcfc9c1f7f8d3ef3a808cc9c492e13d966771908d1e75dca22bdaec5e750bc0","ContainerConfig":{"Hostname":"3dcfc9c1f7f8","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["/bin/sh","-c","#(nop) ","CMD [\\"/bin/sh\\"]"],"ArgsEscaped":true,"Image":"sha256:be4705c10dd809a3a3b0dfd96016943fa43b8731e17321be9e8fe32a7426da62","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":{}},"DockerVersion":"18.06.1-ce","Author":"","Config":{"Hostname":"","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["/bin/sh"],"ArgsEscaped":true,"Image":"sha256:be4705c10dd809a3a3b0dfd96016943fa43b8731e17321be9e8fe32a7426da62","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":null},"Architecture":"amd64","Os":"linux","Size":3995534,"VirtualSize":3995534,"GraphDriver":{"Data":{"MergedDir":"/var/lib/docker/overlay2/569b37dff748becb02407bc50dd54f17265f067b44cbabfe795d93b2ab164a7b/merged","UpperDir":"/var/lib/docker/overlay2/569b37dff748becb02407bc50dd54f17265f067b44cbabfe795d93b2ab164a7b/diff","WorkDir":"/var/lib/docker/overlay2/569b37dff748becb02407bc50dd54f17265f067b44cbabfe795d93b2ab164a7b/work"},"Name":"overlay2"},"RootFS":{"Type":"layers","Layers":["sha256:f566c57e6f2da2364c14195c832b922fd8f4813fd139b8fe45e3454c16e33975"]},"Metadata":{"LastTagTime":"0001-01-01T00:00:00Z"}}
> ```
> 
> And from podman:
> 
> ```js
> {"Id":"sha256:f80194ae2e0ccf0f098baa6b981396dfbffb16e6476164af72158577a7de2dd9","RepoTags":["docker.io/library/alpine:3.5"],"RepoDigests":["docker.io/library/alpine@sha256:66952b313e51c3bd1987d7c4ddf5dba9bc0fb6e524eed2448fa660246b3e76ec","docker.io/library/alpine@sha256:f7d2b5725685826823bc6b154c0de02832e5e6daf7dc25a00ab00f1158fabfc8"],"Parent":"","Comment":"","Created":"2019-01-30T22:20:40.179652676Z","Container":"","ContainerConfig":null,"DockerVersion":"18.06.1-ce","Author":"","Config":{"Hostname":"","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["/bin/sh"],"Image":"","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":null},"Architecture":"amd64","Os":"linux","OsVersion":"18.06.1-ce","Size":4238777,"VirtualSize":4238777,"GraphDriver":{"Data":{"UpperDir":"/home/candrews/.local/share/containers/storage/overlay/f566c57e6f2da2364c14195c832b922fd8f4813fd139b8fe45e3454c16e33975/diff","WorkDir":"/home/candrews/.local/share/containers/storage/overlay/f566c57e6f2da2364c14195c832b922fd8f4813fd139b8fe45e3454c16e33975/work"},"Name":"overlay"},"RootFS":{"Type":"layers","Layers":["sha256:f566c57e6f2da2364c14195c832b922fd8f4813fd139b8fe45e3454c16e33975"]},"Metadata":{"LastTagTime":"0001-01-01T00:00:00Z"}}
> ```

Am I missing something here? The timestamps in both examples (Created and Metadata.LastTagTime) are identical. 

I tried to repro it and got the same result. While container timestamps are given in local time, images built or pulled with podman use UTC timestamps just like docker.

**Comment by matejvasek** [comment]
I submitted a PR for this. Still I think that Java client should also accept TS with timezone. It uses `DateTimeFormatter.ISO_INSTANT` but IMHO it should use `DateTimeFormatter.ISO_OFFSET_DATE_TIME`.

**Comment by rcowsill** [comment]
> I submitted a PR for this. Still I think that Java client should also accept TS with timezone. It uses `DateTimeFormatter.ISO_INSTANT` but IMHO it should use `DateTimeFormatter.ISO_OFFSET_DATE_TIME`.

I think so too. Docker *prefers* to use UTC time when making images/containers, but it's happy to parse non-UTC times too. It will then pass those on in its output. For example:
```
C:\Users\***>docker images
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
mcr.microsoft.com/windows/nanoserver   10.0.14393.1066     a943c29f0046        4 years ago         1.01GB

C:\Users\***>docker image inspect a943c29f0046
[
    {
        "Id": "sha256:a943c29f0046aa2764d32bf9dfeca1d816865729e3fa26be0259915bf78ac05e",
        "RepoTags": [
            "mcr.microsoft.com/windows/nanoserver:10.0.14393.1066"
        ],
        "RepoDigests": [
            "mcr.microsoft.com/windows/nanoserver@sha256:ded482e81f381c94458a1d12d995506ac331d6d3180ed6da24ba809b0849a46c"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2017-04-11T02:12:36.3606843-07:00",
        [...]
```

**Comment by candrews** [comment]
I submitted a PR to testcontainers: https://github.com/testcontainers/testcontainers-java/pull/4073

Thank you for all of this information and for making the change to podman.
