### ISSUE TITLE
Add option to "podman generate systemd" to create and use a wrapper script in ExecStart

### ISSUE THREAD

**Issue by eriksjolund** [containers/podman#10276]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

With `podman generate systemd --name foobar --new` it is possible to generate a Systemd unit file.
For instance
```
$ podman run --name foobar --publish 8080:80 -d docker.io/library/nginx:latest
605047b101cc8267e2d9604f2e82752b78fa66913a8be446878b06a5aa3e4d6c
$ podman generate systemd --new -n foobar > foobar.service
```

When you start a Systemd service

```
$ systemctl --user start foobar.service
```

there are some specifiers (e.g. `%H`, `%s` ) that could be used in the Systemd unit file to pass some
information to the `podman run` command. 
See _Table 4. Specifiers available in unit files_ in [`man systemd.unit`](https://www.freedesktop.org/software/systemd/man/systemd.unit.html)

If there is a need to modify the generated line starting with `ExecStart=/usr/bin/podman run ` and
somehow insert the information from the specifiers it is quite easy to do that  if you can use the values
directly in the form they are provided.

But what could you do if you need to compute some value from the specifier information
before adding it to the line?

One solution seems to be to replace  the line

```
ExecStart=/usr/bin/podman run --conmon-pidfile %t/container-foobar.pid --cidfile %t/container-foobar.ctr-id --cgroups=no-conmon --replace --name foobar --publish 8080:80 -d docker.io/library/nginx:latest
```
with

```
ExecStart=/path/to/wrapper.py --arg-b %b --arg-C %C --arg-E %E \
      --arg-f %f --arg-h %h --arg-H %H --arg-i %i --arg-I %I --arg-j %j --arg-J %J \
      --arg-L %L --arg-m %m --arg-n %n --arg-N %N --arg-p %p --arg-P %P \
       --arg-s %s --arg-S %S --arg-t %t --arg-T %T --arg-u %u --arg-U %U \
       --arg-v %v --arg-V %V
```

and use a wrapper script 
```
#!/usr/bin/python3

import argparse
import os

parser = argparse.ArgumentParser()

options = [ "b" ,"C" ,"E" ,"f" ,"h" ,"H" ,"i" ,"I" ,"j" ,"J" , "L" ,"m" ,"n" ,"N" ,
                  "p" ,"P" ,"s" ,"S" ,"t" ,"T" ,"u" ,"U" ,"v" ,"V"]

for i in options:
  parser.add_argument(f"--arg-{i}", help=f"systemd specifier %{i}", required=True)

args = parser.parse_args()

# Here it would be possible to compute something from the Systemd
# specifier information. The result could then be used in the arguments 
# provided to Podman

os.execv("/usr/bin/podman",
    [ "/usr/bin/podman", 
     "run",
     "--conmon-pidfile", f"{args.arg_t}/container-foobar.pid",
     "--cidfile", f"{args.arg_t}/container-foobar.ctr-id",
     "--cgroups=no-conmon", 
     "--publish", "8080:80",
     "-d", "--replace",
     "--name", "foobar",
     "docker.io/library/nginx:latest"])
```

###

Maybe it would be possible to introduce two new command-line options to `podman generate systemd`?

#### _--list-wrapper-languages_

That would list the available wrapper script programming languages. (I wrote the Python wrapper script example but I haven't tried it out in any other languages yet)
```
$ podman generate systemd --list-wrapper-languages
golang
python
rust
bash
```

#### _--wrapper_ 

```
$ podman generate systemd --name foobar --new --files --wrapper python
```

This would generate both a Systemd unit file and a wrapper script.

#### Combining this feature with Systemd template units

This feature request would be more useful in combination with
the feature described in https://github.com/containers/podman/issues/10275

It would then for instance be possible to look up a TCP port number from one of the configuration files `production.json`
and `development.json` by starting the service with either 

```
$ systemctl --user start foobar@production
```
or

```
$ systemctl --user start foobar@development
```

Such a port number could then be used in the `--publish` option for `podman run`

**Comment by vrothberg** [comment]
Thanks for opening the issue!

The added complexity on the code and on maintenance (including testing) is scaring me.   Generating the unit files is already quite complex but adding such wrappers seems to explode the matrix and cross support boundaries.

I usually try to draw the line between infrastructure (Podman) and business/application logic (not Podman), and I think we're very much on the application logic side.  Besides the aforementioned impacts on code and maintenance, I don't how we could support customized wrappers.  Until now, if users don't adhere to generated unit files we do "best effort" support.

@rhatdan PTAL

**Comment by eriksjolund** [comment]
@vrothberg I understand your point of view. It makes sense. (I was not even 100% convinced myself when I created this feature request).

**Comment by rhatdan** [comment]
I agree with @vrothberg this is out of scope for the project.

**Comment by vrothberg** [comment]
Thanks for your understanding, @eriksjolund.  I do enjoy such conversations as they help shape the direction of the project, so I appreciate your request a lot.
