### ISSUE TITLE
userns doesn't seem to work anymore (rootless) - big UID

### ISSUE THREAD

**Issue by bitstrings** [containers/podman#10272]
/kind bug

When the `uid` is big, i.e.: > `65536` and using `userns`, I get some weird errors.

The `uid` is seems to be correct inside the container but I get permissions issues
when trying to create file/dir for examples.

For example:

```
[x@localhost-live ~]$ podman run -it --rm --userns=keep-id ubuntu bash

x@5f3774553d8f:/$ id
uid=177777777(x) gid=1001(x) groups=1001(x)

x@5f3774553d8f:/$ touch /tmp/a
touch: setting times of '/tmp/a': No such file or directory
```

This used to work, not long ago, before my update to `3.1.2`.

Obviously tried `system migrate` and `system reset`.

Same error on `a+rwX` folders.

---

Fail with Ubuntu 20.04 & 21.04, Fedora 34.

Podman 3.0.1 & 3.1.2.

![image](https://user-images.githubusercontent.com/911165/117507546-328b4100-af55-11eb-9598-070cc21f1bf5.png)

**Comment by bitstrings** [comment]
Funny thing if the subuid count is `1000000` then magically, it works!

Example:

```
someuser:99999999:1000000
```

**Comment by rhatdan** [comment]
Could you show 
podman run --rm --userns=keep-id ubuntu cat /proc/self/uid_map?

@giuseppe WDYT?

**Comment by bitstrings** [comment]
![image](https://user-images.githubusercontent.com/911165/117881475-47c6df00-b277-11eb-8fe8-208d3f5dbc5c.png)

**Comment by giuseppe** [comment]
I think this depends on how fuse-overlayfs does the inverse mappings for IDs.

Requests from the user 177777777 will be written to the storage with uid=177777777, but that ID is not available in the user namespace so it fails.

I think the solution is to disable the fuse-overlayfs shifting when the mapping is not contiguous

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/storage/pull/897
