### ISSUE TITLE
Running privileged podman containers inside a docker container gives "Error: container_linux.go:367: starting container process caused: apply caps: operation not permitted: OCI runtime permission denied error"

### ISSUE THREAD

**Issue by infiniteregrets** [containers/podman#10282]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
- Running Podman inside a Docker Container with the --privileged tag gives the following error: 
Error: container_linux.go:367: starting container process caused: apply caps: operation not permitted: OCI runtime permission denied error

**Steps to reproduce the issue:**

1. Dockerfile
```
FROM ubuntu:20.10 
RUN apt-get update -y \
    && apt-get install -y\
    ca-certificates \
    libprotobuf-dev \
    libnl-route-3-dev \    
    podman \
    runc \ 
    criu \
    vim 
ARG DEBIAN_FRONTEND='noninteractive'
RUN apt-get install -y iptables-persistent     
```
Build this image: 
```
docker build .  OR docker build < Dockerfile   
```
2. Run a docker container with --privileged tag 
- `docker image ls `
-  select the image ID and run `docker run --privileged -i -t --rm {IMAGE ID} /bin/bash`

3. Build the Alpine image 
- `podman pull alpine`
- `podman images`
- select the image ID and run `podman run --privileged --cgroup-manager="cgroupfs" --rm -it {IMAGE ID} /bin/sh`

**Describe the results you received:**
`Error: container_linux.go:367: starting container process caused: apply caps: operation not permitted: OCI runtime permission denied error`

**Describe the results you expected:**
`/ # `

**Additional information you deem important (e.g. issue happens only occasionally):**
`podman run --cap-drop=all --cgroup-manager="cgroupfs" --rm -it {IMAGE ID} /bin/sh` results in the same error

**Output of `podman version`:**

```
Version:      2.0.6
API Version:  1
Go Version:   go1.14.7
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.2
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: unknown'
  cpus: 2
  distribution:
    distribution: ubuntu
    version: "20.10"
  eventLogger: file
  hostname: 6fc6a3d77e11
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.25-linuxkit
  linkmode: dynamic
  memFree: 829906944
  memTotal: 2084691968
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version spec: 1.0.2-dev
      go: go1.14.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 991195136
  swapTotal: 1073737728
  uptime: 6h 47m 47.2s (Approximately 0.25 days)
registries:
  search:
  - quay.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus: {}
  imageStore:
    number: 1
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.0.6
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
root@6fc6a3d77e11:/test_dir# apt list podman -a
Listing... Done
podman/groovy-updates,now 2.0.6+dfsg1-1ubuntu1.2 amd64 [installed]
podman/groovy 2.0.6+dfsg1-1ubuntu1 amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes
Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
macOS Catalina 10.15.7

**Comment by rhatdan** [comment]
I would figure this is a mismatch in the capabilities that Docker knows about versus those known by a newer Podman.  If you run a confined podman, does everything work?

**Comment by rhatdan** [comment]
How about if you run `--cap-add=all` Does it fail?
If yes try:
`--cap-add=all --cap-drop=CAP_PERFMON` ...

**Comment by infiniteregrets** [comment]
Okay so I have tried everything (including what you just mentioned), but none of it works. I tried manually adding capabilities from https://man7.org/linux/man-pages/man7/capabilities.7.html and it fails as soon as you reach CAP_BPF. In my case I am trying to launch the container with nsjail (https://nsjail.dev/) and here's what I ran:  (I hope this gives some more context)
```
podman run --cap-add=CAP_AUDIT_CONTROL,CAP_AUDIT_READ,CAP_AUDIT_WRITE,CAP_BLOCK_SUSPEND --cgroup-manager="cgroupfs" -i -t --rm 9907cd788c9f nsjail --user 99999 --group 99999 --disable_proc --chroot / --time_limit 30 /bin/bash
```
Error: 
```
[I][2021-05-10T18:39:15+0000] Mode: STANDALONE_ONCE
[I][2021-05-10T18:39:15+0000] Jail parameters: hostname:'NSJAIL', chroot:'/', process:'/bin/bash', bind:[::]:0, max_conns:0, max_conns_per_ip:0, time_limit:30, personality:0, daemonize:false, clone_newnet:true, clone_newuser:true, clone_newns:true, clone_newpid:true, clone_newipc:true, clone_newuts:true, clone_newcgroup:true, keep_caps:false, disable_no_new_privs:false, max_cpus:0
[I][2021-05-10T18:39:15+0000] Mount: '/' -> '/' flags:MS_RDONLY|MS_BIND|MS_REC|MS_PRIVATE type:'' options:'' dir:true
[I][2021-05-10T18:39:15+0000] Uid map: inside_uid:99999 outside_uid:0 count:1 newuidmap:false
[W][2021-05-10T18:39:15+0000][1] void cmdline::logParams(nsjconf_t*)():253 Process will be UID/EUID=0 in the global user namespace, and will have user root-level access to files
[I][2021-05-10T18:39:15+0000] Gid map: inside_gid:99999 outside_gid:0 count:1 newgidmap:false
[W][2021-05-10T18:39:15+0000][1] void cmdline::logParams(nsjconf_t*)():263 Process will be GID/EGID=0 in the global user namespace, and will have group root-level access to files
[E][2021-05-10T18:39:15+0000][1] bool uts::initNs(nsjconf_t*)():38 sethostname('NSJAIL'): Operation not permitted
[W][2021-05-10T18:39:15+0000][1] pid_t subproc::runChild(nsjconf_t*, int, int, int, int)():488 Received error message from the child process before it has been executed
[E][2021-05-10T18:39:15+0000][1] int nsjail::standaloneMode(nsjconf_t*)():272 Couldn't launch the child process```

**Comment by rhatdan** [comment]
Does podman work inside of the container if you don't specify --priviged.

podman run fedora echo hello.

**Comment by infiniteregrets** [comment]
Yes it does work

**Comment by rhatdan** [comment]
Does if fail if you run 

podman run --cap-add all fedora echo hello.

**Comment by rhatdan** [comment]
If yes, does it fail if you run

podman run --security-opt seccomp=unconfined --cap-add all fedora echo hello.

**Comment by infiniteregrets** [comment]
yes it does lol, on either of --privileged or --cap-add=all

**Comment by infiniteregrets** [comment]
I had not tried before with the --security-opt flag. But unfortunately, it fails again 
```
Error: container_linux.go:367: starting container process caused: apply caps: operation not permitted: OCI runtime permission denied error
```

**Comment by rhatdan** [comment]
```
            "CapAdd": [
                "CAP_DAC_READ_SEARCH",
                "CAP_LINUX_IMMUTABLE",
                "CAP_NET_BROADCAST",
                "CAP_NET_ADMIN",
                "CAP_IPC_LOCK",
                "CAP_IPC_OWNER",
                "CAP_SYS_MODULE",
                "CAP_SYS_RAWIO",
                "CAP_SYS_PTRACE",
                "CAP_SYS_PACCT",
                "CAP_SYS_ADMIN",
                "CAP_SYS_BOOT",
                "CAP_SYS_NICE",
                "CAP_SYS_RESOURCE",
                "CAP_SYS_TIME",
                "CAP_SYS_TTY_CONFIG",
                "CAP_LEASE",
                "CAP_AUDIT_CONTROL",
                "CAP_MAC_OVERRIDE",
                "CAP_MAC_ADMIN",
                "CAP_SYSLOG",
                "CAP_WAKE_ALARM",
                "CAP_BLOCK_SUSPEND",
                "CAP_AUDIT_READ",
                "CAP_PERFMON",
                "CAP_BPF",
                "CAP_CHECKPOINT_RESTORE"
            ],
```
These are the capabilities --all attempts to set.  

Docker currently supports these:

docker run --rm --cap-add all fedora capsh --print | grep "Current IAB"
Current IAB: cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read,!cap_perfmon,!cap_bpf,!cap_checkpoint_restore

Notice it does not support   "CAP_PERFMON","CAP_BPF", "CAP_CHECKPOINT_RESTORE"

Sadly there is no way to remove them currently.

**Comment by infiniteregrets** [comment]
Hey, thanks for letting me know! I have been experimenting with nested containers, so will it be okay if I submit a PR with some more info to https://github.com/containers/podman/blob/master/troubleshooting.md#13-running-podman-inside-a-container-causes-container-crashes-and-inconsistent-states

**Comment by rhatdan** [comment]
Yes all PRs are welcome.

**Comment by rhatdan** [comment]
We had an internal discussion about improving this situation with Podman, Basically changing --privileged to only set the capabilities available to the podman process, not in the realm of what Podman considers privileged.  Once this is fixed, we will warn the users about the missing Capabilities, when run in --privileged or --cap-add=all

**Comment by infiniteregrets** [comment]
> Yes all PRs are welcome.
Thanks! will do 

> We had an internal discussion about improving this situation with Podman, Basically changing --privileged to only set the capabilities available to the podman process, not in the realm of what Podman considers privileged. Once this is fixed, we will warn the users about the missing Capabilities, when run in --privileged or --cap-add=all

Awesome! That would be so nice

**Comment by infiniteregrets** [comment]
> We had an internal discussion about improving this situation with Podman, Basically changing --privileged to only set the capabilities available to the podman process, not in the realm of what Podman considers privileged. Once this is fixed, we will warn the users about the missing Capabilities, when run in --privileged or --cap-add=all

@rhatdan was this functionality added or is under work?

**Comment by rhatdan** [comment]
Nope this was lost in the flow.  Interested in opening a PR?

**Comment by infiniteregrets** [comment]
Sure, I'll try

**Comment by rhatdan** [comment]
@infiniteregrets is this still an issue?

**Comment by infiniteregrets** [comment]
@rhatdan Yes it is and sorry for the late response, I couldnt get to this one. I havent studied much about how capabilities work, once I read the man page I'll try to work on this or if I can't figure it ill let you know

**Comment by infiniteregrets** [comment]
@rhatdan  This does not look like an issue anymore. Previously when I tested this I was on an ubuntu 20.04 Image inside a 20.10 image which installs a very old podman version. Picking up the Dockerfile listed here https://www.redhat.com/sysadmin/podman-inside-container I took the following steps:
I created a another Dockerfile inside this fedora container running in interactive mode. The file looks like this:
```
  FROM fedora
  RUN dnf install -y \
          autoconf \
          bison \
          ca-certificates \
          flex \
          g++ \
          gcc \
          git \
          protobuf-devel \
          libnl3-devel \
          libtool \
          make \
          pkg-config \
          protobuf-compiler

  RUN git clone --recursive https://github.com/google/nsjail.git /nsjail \
      && cd /nsjail \
      && git checkout a9790e14bf88e3fa7c1a543ca5a07f5d8e8c7a5c \
      && make && mv /nsjail/nsjail /usr/bin/
```
Then `podman build -t test .` && `podman run -it --privileged test /bin/bash`
Inside this nested container `capsh --print` gives the same capability IAB list as the one you sent before but the current state  includes "CAP_PERFMON","CAP_BPF", "CAP_CHECKPOINT_RESTORE" if I understand correctly
```
[root@d7bcd4ac2b72 test]# podman run -it --privileged test /bin/bash -c "capsh --print"
Current: =eip cap_perfmon,cap_bpf,cap_checkpoint_restore-eip
Bounding set =cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read
Ambient set =
Current IAB: cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read,!cap_perfmon,!cap_bpf,!cap_checkpoint_restore
Securebits: 00/0x0/1'b0 (no-new-privs=0)
```
But in the previous version on the parent ubuntu container run by docker I had to specify `cgroup_manager="cgroupfs"` which I don't have to do anymore? 

I dont think we need to warn the users for the capabilities being set or not set for the podman process since for the most used cases including `--privileged` this works fine and if a capability unavailable is set then the user will get the OCI runtime error which seems reasonable.

**Comment by rhatdan** [comment]
Ok I am going to close.
