### ISSUE TITLE
error creating container: error creating read-write layer with ID "8f4675210bf6a73534c3c64aefcfe80e63eabfc4f21707036a7c7ef2ca55036d": no such file or directory

### ISSUE THREAD

**Issue by runseason** [containers/podman#10284]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1.# podman images
REPOSITORY                                                              TAG             IMAGE ID       CREATED         SIZE
registry.jqpqa.c.saic-gm.net/baseimages/python-36-nginx-114-rhel7   latest          1d21340f1af3   9 months ago    682 MB

2.# env=$(buildah from registry.jqpqa.c.saic-gm.net/baseimages/python-36-nginx-114-rhel7:latest)
error creating container: error creating read-write layer with ID "ab9b7b0613be96240480fe144ccc6df33b5148b17bd89f465531342da2e4cc9e": no such file or directory

3.

**Describe the results you received:**
error creating container: error creating read-write layer with ID "ab9b7b0613be96240480fe144ccc6df33b5148b17bd89f465531342da2e4cc9e": no such file or directory

**Describe the results you expected:**
generate a container with base image python-36-nginx-114-rhel7:latest

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Version:            1.4.2-stable2
RemoteAPI Version:  1
Go Version:         go1.12.8
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
# podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.8
  podman version: 1.4.2-stable2
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.2-5.module+el8.1.0+4240+893c1ab8.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.1-dev, commit: unknown'
  Distribution:
    distribution: '"rhel"'
    version: "8.1"
  MemFree: 2393362432
  MemTotal: 3963858944
  OCIRuntime:
    package: runc-1.0.0-60.rc8.module+el8.1.0+4081+b29780af.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 8589930496
  SwapTotal: 8589930496
  arch: amd64
  cpus: 2
  hostname: ruyiqa02
  kernel: 4.18.0-147.el8.x86_64
  os: linux
  rootless: false
  uptime: 43m 47.42s
registries:
  blocked: null
  insecure:
  - registry.redhat.io
  - registry.jqpqa.c.saic-gm.net
  search:
  - registry.redhat.io
  - registry.access.redhat.com
  - quay.io
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# podman version
Version:            1.4.2-stable2
RemoteAPI Version:  1
Go Version:         go1.12.8
OS/Arch:            linux/amd64
# rpm -q podman
podman-1.4.2-5.module+el8.1.0+4240+893c1ab8.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by zhangguanzhang** [comment]
your podman's version is very old, you could update it and try agian

**Comment by mheon** [comment]
That Podman is very out of support, so I concur - it is *strongly*
recommended to upgrade.

**Comment by zhangguanzhang** [comment]
close if happend on the latest version
/close
