### ISSUE TITLE
podman info - field to check whether it's a remote client

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#10289]
`podman info` should have a field indicating whether it's a remote client or not (see https://github.com/kubernetes-sigs/kind/pull/2235#pullrequestreview-654663239).

**Comment by Luap99** [comment]
The remoteSocket field is only added by the local client:
```
$ podman info | grep remoteSocket
  remoteSocket:
$ podman-remote info | grep remoteSocket
```

**Comment by vrothberg** [comment]
@Luap99, that's not a reliable source:
```
~ $ podman-remote info |grep emote
  remoteSocket:
~ $ podman info |grep emote
  remoteSocket:
```

**Comment by Luap99** [comment]
It looks like this behaviour changed after v3.1.2.

**Comment by afbjorklund** [comment]
It would be even more strange if podman-remote didn't have a socket ?

So far we have mostly been using `podman version` to tell them apart.

```console
$ podman version
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
$ podman-remote version
Client:
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64

Server:
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64

```


But it could be good with an explicit field.

Like the current "rootless", or something ?

```console
$ podman info | grep rootless
    rootless: true
$ sudo podman info | grep rootless
    rootless: false
```

**Comment by afbjorklund** [comment]
So if you run podman-remote, it does *not* have a socket ?

`podman-remote info`

But if you log in to the machine and run podman local, it does ?

`podman machine ssh podman info`

```diff
@@ -42,6 +42,9 @@
       spec: 1.0.0
       +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
   os: linux
+  remoteSocket:
+    exists: true
+    path: /run/user/1000/podman/podman.sock
   security:
     apparmorEnabled: false
     capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
```

That is quite counter-intuitive.

**Comment by jwhonce** [comment]
@afbjorklund FYI A HEAD on `/_ping` returns the header `Libpod-Api-Version` which clients could use to determine which method to use.

**Comment by afbjorklund** [comment]
@jwhonce : assuming that `podman` is the regular daemonless version, where would one send the `/_ping` ?

Otherwise, we could just look at the binary. If it is `podman-remote`, it is remote. (not using `podman --remote`)

So I think the proposed info field for remoteness is fine.

----

If i understand correctly, they had some different original requirements anyway:

```
		// Unlike `docker info`, `podman info` does not print available cgroup controllers.
		// So we parse "cgroup.subtree_control" file by ourselves.
```

So maybe they were more interested in `cgroupVersion`, and some new fields ?

**Comment by aojea** [comment]
> `I don't think looking at $CONTAINER_HOST would work anymore, since it could be using a "connection"

in the meantime, can we use the env CONTAINER_HOST variable to discriminate?

**Comment by afbjorklund** [comment]
> in the meantime, can we use the env CONTAINER_HOST variable to discriminate?

That was my point, that variable doesn't have to be in use. It _could_ just be config files...

When using the new `podman machine` for instance, instead of `podman-machine env`

```
$ env | grep CONTAINER
$ podman system connection list
Name                         Identity                                    URI
podman-machine-default*      /home/anders/.ssh/podman-machine-default  ssh://core@localhost:34265/run/user/1000/podman/podman.sock
podman-machine-default-root  /home/anders/.ssh/podman-machine-default  ssh://root@localhost:34265/run/podman/podman.sock
```

**Comment by jwhonce** [comment]
> @jwhonce : assuming that `podman` is the regular daemonless version, where would one send the `/_ping` ?
> 
@afbjorklund I have RESTful API on the brain. Sorry for the noise.

**Comment by aojea** [comment]
did you mean to close it @jwhonce ? :thinking:

**Comment by jwhonce** [comment]
https://github.com/containers/podman/pull/10300 will auto-close.
