### ISSUE TITLE
Podman errors when stopping the container

### ISSUE THREAD

**Issue by psaini79** [containers/podman#10280]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Podman intermittently throws errors when I m stopping the container.

**Steps to reproduce the issue:**

1. Create the container
```
[root@podman-test-server opc]#  podman create -t -i \
>  --cgroupns=private \
>  --hostname test1 \
>  --privileged=false  \
>  --memory 16G \
>  --memory-swap 32G \
>  --restart=always \
>  --systemd=true \
>  --name test1  \
>  oraclelinux:8
```

2. Assign bridge network create locally on podman host to the container
```
[root@podman-test-server opc]#  podman start test1
[root@podman-test-server opc]#  podman network connect test_nw2  test1
[root@podman-test-server opc]#  podman network connect test_nw3 test1
[root@podman-test-server opc]#  podman network disconnect podman test1
```
3. stop the container
```
podman stop test1
```
**Describe the results you received:**
root@podman-test-server opc]# podman stop test1
ERRO[0000] Error deleting network: running [/sbin/iptables -t nat -X CNI-1e45509069c6d8321d067692 --wait]: exit status 4: iptables v1.8.4 (nf_tables):  CHAIN_USER_DEL failed (Device or resource busy): chain CNI-1e45509069c6d8321d067692 
ERRO[0000] Error while removing pod from CNI network "test_nw2": running [/sbin/iptables -t nat -X CNI-1e45509069c6d8321d067692 --wait]: exit status 4: iptables v1.8.4 (nf_tables):  CHAIN_USER_DEL failed (Device or resource busy): chain CNI-1e45509069c6d8321d067692 
ERRO[0000] unable to cleanup network for container 3e40029b483024dfef90ad339aa48394d2ad19f9b61193d5f14bbe47a779d377: "error tearing down CNI namespace configuration for container 3e40029b483024dfef90ad339aa48394d2ad19f9b61193d5f14bbe47a779d377: running [/sbin/iptables -t nat -X CNI-1e45509069c6d8321d067692 --wait]: exit status 4: iptables v1.8.4 (nf_tables):  CHAIN_USER_DEL failed (Device or resource busy): chain CNI-1e45509069c6d8321d067692\n" 
3e40029b483024dfef90ad339aa48394d2ad19f9b61193d5f14bbe47a779d377

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2
Go Version:   go1.14.12
Built:        Fri Feb 19 11:46:00 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.22-3.module+el8.3.1+9659+c1901784.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.22, commit: 3ef8df793032fc21d5db1f32c0b3e5a73998381c'
  cpus: 4
  distribution:
    distribution: '"ol"'
    version: "8.3"
  eventLogger: file
  hostname: podman-test-server
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.17-2036.102.0.2.el8uek.x86_64
  linkmode: dynamic
  memFree: 2622922752
  memTotal: 24651005952
  ociRuntime:
    name: runc
    package: runc-1.0.0-70.rc92.module+el8.3.1+9659+c1901784.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 16h 2m 42.54s (Approximately 0.67 days)
registries:
  search:
  - container-registry.oracle.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 11
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: "2"
  Built: 1613735160
  BuiltTime: Fri Feb 19 11:46:00 2021
  GitCommit: ""
  GoVersion: go1.14.12
  OsArch: linux/amd64
  Version: 2.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.2.1-7.0.1.module+el8.3.1+9659+c1901784.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

NO

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by baude** [comment]
I'm closing this as @jwhonce was unable to replicate with main branch ... please re-open if it is not.
