### ISSUE TITLE
podman info - print available cgroup controllers

### ISSUE THREAD

**Issue by aojea** [containers/podman#10306]
Opening a new issue with from:

_Originally posted by @afbjorklund in https://github.com/containers/podman/issues/10289#issuecomment-837840788_

> If i understand correctly, they had some different original requirements anyway:
> 
> ```
> 		// Unlike `docker info`, `podman info` does not print available cgroup controllers.
> 		// So we parse "cgroup.subtree_control" file by ourselves.
> ```
> 
> So maybe they were more interested in `cgroupVersion`, and some new fields ?
> 
> ```
> 	MemoryLimit     bool     `json:"MemoryLimit"`
> 	PidsLimit       bool     `json:"PidsLimit"`
> 	CPUShares       bool     `json:"CPUShares"`
> ```
> 
> https://github.com/kubernetes-sigs/kind/issues/2233
>

**Comment by afbjorklund** [comment]
The complete list is available at github.com/docker/docker/pkg/sysinfo

        v.MemoryLimit = sysInfo.MemoryLimit
        v.SwapLimit = sysInfo.SwapLimit
        v.KernelMemory = sysInfo.KernelMemory
        v.KernelMemoryTCP = sysInfo.KernelMemoryTCP
        v.OomKillDisable = sysInfo.OomKillDisable
        v.CPUCfsPeriod = sysInfo.CPUCfsPeriod
        v.CPUCfsQuota = sysInfo.CPUCfsQuota
        v.CPUShares = sysInfo.CPUShares
        v.CPUSet = sysInfo.Cpuset
        v.PidsLimit = sysInfo.PidsLimit

**Comment by rhatdan** [comment]
Care to open a PR to fix?

**Comment by rhatdan** [comment]
Do you want podman info to report all of this information?

**Comment by afbjorklund** [comment]
> Do you want podman info to report all of this information?

The request from `kind` was for three new fields.  Maybe add swap too ?

```go
// dockerInfo corresponds to `docker info --format '{{json .}}'`
type dockerInfo struct {
        CgroupDriver    string   `json:"CgroupDriver"`  // "systemd", "cgroupfs", "none"
        CgroupVersion   string   `json:"CgroupVersion"` // e.g. "2"
        MemoryLimit     bool     `json:"MemoryLimit"`
        PidsLimit       bool     `json:"PidsLimit"`
        CPUShares       bool     `json:"CPUShares"`
        SecurityOptions []string `json:"SecurityOptions"`
}
```

It is mostly used for producing warnings, when running rootless / cgroups v2:

```go
        if info.Rootless {
                if !info.Cgroup2 {
                        return errors.New("running kind with rootless provider requires cgroup v2, see https://kind.sigs.k8s.io/docs/user/rootless/")
                }
                if !info.SupportsMemoryLimit || !info.SupportsPidsLimit || !info.SupportsCPUShares {
                        return errors.New("running kind with rootless provider requires setting systemd property \"Delegate=yes\", see https://kind.sigs.k8s.io/docs/user/rootless/")
                }
        }
```

----

The current code was trying to parse `/sys` itself, which is why it failed when running with podman-remote.

https://github.com/kubernetes-sigs/kind/blob/main/pkg/cluster/internal/providers/docker/provider.go#L308

https://github.com/kubernetes-sigs/kind/blob/main/pkg/cluster/internal/providers/podman/provider.go#L367

If the three fields were available in the `info` JSON, it would not have to resort to such desperate measures.
