### ISSUE TITLE
Using podman rootful, but mapping the container to a user and keeping groups 

### ISSUE THREAD

**Issue by KCSesh** [containers/podman#10314]
**Description**
I am trying to understand starting podman as a rootful user (to get overlay2 access) but still trying to start containers as a specific unprivileged host user, which inside the container is root. 

Additionally, this `user` belongs to a common group that I also want in the container so if the common group has read/write permissions on a host file, it can read/write to it from the container. 

How can this be done? 

**Steps to reproduce the issue:**

First My user1 setup:  

```
user1 uid = 1002
user1 gid = 1004
userCommon gid = 1002
```

1. 
```
sudo podman --runtime /usr/local/bin/crun run --uidmap 0:1002:1 --uidmap 1:100000:65536 --gidmap 0:1004:1 --gidmap 1:100000:1001 --gidmap 1002:1002:1 --gidmap 1003:101003:65536  -v /tmp:/tmp --rm -it <image>
```

This should be mapping user1:user1 as `root` into the container. 
User namespace filling for 1:100000:65536 for UID. 
User namespace filling for 1:100000:1001 for GID. 
Map the common group `userCommon` directly into the container at 1002. 
Then user namespace filling for 1003:101003:65536. 

2. 
```
# cat /tmp/groupCommonRead.txt
cat: /tmp/groupCommonRead.txt: Permission denied
```

**Describe the results you received:**
Permission denied when attempting to read a file that is control by a common group permission. 

**Describe the results you expected:**
I should be able to read from the file as my user that is running container belongs in the common group, and I have mapped the common group directly into the container. 

Now I imagine this is related because the group inside the container has no information about the users in the commonGroup? Is that right? 
Is there any way I can properly map this group into the container such that the common group can be read from inside the container, and remain read by other users on the host? 

**A version I did get to work**, was using: `--group-add keep-groups` 

```
sudo podman --runtime /usr/local/bin/crun run --uidmap 0:1002:1 --uidmap 1:100000:65536 --gidmap 0:1004:1 --gidmap 1:100000:65536 --group-add keep-groups  -v /tmp:/tmp --rm -it <image>
```

But this required me to add my host `root` to the `userCommon ` group because that is the user that is running podman. 

Is this the only approach that would work?

**Comment by giuseppe** [comment]
since you run as root, my suggestion is to add the `userCommon` group to the user namespace:

`sudo podman --runtime /usr/local/bin/crun run --uidmap 0:1002:1 --uidmap 1:100000:65536 --gidmap 0:1004:1 --gidmap 1:100000:65536 --gidmap 100000:$userCommonGID:1  -v /tmp:/tmp --rm -it` and if you run with `CAP_DAC_OVERRIDE` as your command does, you won't even need to set the group or additional groups

**Comment by KCSesh** [comment]
@giuseppe Unfortunately your suggestion seems not to have worked either: 

```
newuser@tegra-ubuntu:~$sudo podman --runtime /usr/local/bin/crun run --uidmap 0:1002:1 --uidmap 1:100000:65536 --gidmap 0:1004:1 --gidmap 1:100000:65536 --gidmap 100000:1002:1 -v /tmp:/tmp --rm -it nvcr.io/nvidia/l4t-base:r32.4.4
root@f3ea5d275add:/# cat /tmp/group.txt
cat: /tmp/group.txt: Permission denied
root@f3ea5d275add:/# ls -la /tmp/group.txt
-rw-r----- 1 nobody  100000 5 May 11 22:27 /tmp/group.txt
root@f3ea5d275add:/# exit
```

```
newuser@tegra-ubuntu:~$ id
uid=1002(newuser) gid=1004(newuser) groups=1004(newuser),27(sudo),44(video),1002(userCommon)
newuser@tegra-ubuntu:~$ cat /tmp/group.txt
test
```

**Comment by giuseppe** [comment]
```
# ls -la /tmp/group.txt
-rw-r----- 1 nobody  100000 5 May 11 22:27 /tmp/group.txt
```

this should not happen, it should be owned by a group that is mapped into the user namespace.

Can you show me the output for this command on the host (not in a container):

```
# ls -ln /tmp/group.txt
```

and make sure that group is mapped inside the user namespace

**Comment by KCSesh** [comment]
```
newuser@tegra-ubuntu:~$ ls -ln /tmp/group.txt
-rw-r----- 1 1001 1002 5 May 11 22:27 /tmp/group.txt
```

**Comment by giuseppe** [comment]
ok so `DAC_OVERRIDE` still fails when the uid is not mapped in the user namespace.

In this case I think you can fix it by adding `--group-add 1002` to the `podman run` options

**Comment by KCSesh** [comment]
Could you provide more details? 

If I keep your suggestion the same and do this:

```
newuser@tegra-ubuntu:~$ sudo podman --runtime /usr/local/bin/crun run --uidmap 0:1002:1 --uidmap 1:100000:65536 --gidmap 0:1004:1 --gidmap 1:100000:65536 --gidmap 100000:1002:1 --group-add 1002 -v /tmp:/tmp --rm -it nvcr.io/nvidia/l4t-base:r32.4.4
groups: cannot find name for group ID 1002
root@4f71e387835f:/# cat /tmp/group.txt
cat: /tmp/group.txt: Permission denied
```
I get the warning: `groups: cannot find name for group ID 1002`
And Permission denied.


If I drop the --gidmap and do this:

```
sudo podman --runtime /usr/local/bin/crun run --uidmap 0:1002:1 --uidmap 1:100000:65536 --gidmap 0:1004:1 --gidmap 1:100000:65536 --group-add 1002 -v /tmp:/tmp --rm -it <image>
groups: cannot find name for group ID 1002
root@ed2458c54850:/# cat /tmp/group.txt
cat: /tmp/group.txt: Permission denied
```
I get the warning: `groups: cannot find name for group ID 1002`
And Permission denied.


And lastly, if I try what I did in my ticket opening:

```
sudo podman --runtime /usr/local/bin/crun run --uidmap 0:1002:1 --uidmap 1:100000:65536 --gidmap 0:1004:1 --gidmap 1:100000:1001 --group-add 1002 --gidmap 1003:101003:65536  -v /tmp:/tmp --rm -it  nvcr.io/nvidia/l4t-base:r32.4.4
Error: OCI runtime error: setgroups: Invalid argument
```
`
Error: OCI runtime error: setgroups: Invalid argument
`

**Comment by KCSesh** [comment]
I was able to get it to work if I also mapped in the `user` like you suggested. 

```
newuser@tegra-ubuntu:~$ sudo podman --runtime /usr/local/bin/crun run --uidmap 0:1002:1 --uidmap 1:100000:65536 --uidmap 100000:1001:1 --gidmap 0:1004:1 --gidmap 1:100000:65536 --gidmap 100000:1002:1 -v /tmp:/tmp --rm -it <image>
root@5768bc089b0d:/# cat /tmp/group.txt
test
```

However, I was hoping not to have to do this.

**Comment by giuseppe** [comment]
sorry, try:

`sudo podman --runtime /usr/local/bin/crun run --uidmap 0:1002:1 --uidmap 1:100000:65536 --gidmap 0:1004:1 --gidmap 1:100000:65536 --gidmap 100000:1002:1 --group-add 100000 -v /tmp:/tmp --rm -it <image>`

**Comment by KCSesh** [comment]
Thanks @giuseppe. 

Looks like it work!  But I am confused! 

```
sudo podman --runtime /usr/local/bin/crun run --uidmap 0:1002:1 --uidmap 1:100000:65536 --gidmap 0:1004:1 --gidmap 1:100000:65536 --gidmap 100000:1002:1 --group-add 100000 -v /tmp:/tmp --rm -it <image>
groups: cannot find name for group ID 100000
root@7983c0f2103f:/# cat /tmp/group.txt
test
```

I still get what seems to be a warning of: `groups: cannot find name for group ID 100000` 

But If I remove the

```
sudo podman --runtime /usr/local/bin/crun run --uidmap 0:1002:1 --uidmap 1:100000:65536 --gidmap 0:1004:1 --gidmap 1:100000:65536 --gidmap 100000:1002:1 -v /tmp:/tmp --rm -it <image>
root@ce6be019a8a0:/# cat /tmp/group.txt
cat: /tmp/group.txt: Permission denied
```
But no warning, haha.

**Comment by KCSesh** [comment]
Also @giuseppe 

Just for my understanding, this is essentially equivalent to the docker re map user mode, right? https://docs.docker.com/engine/security/userns-remap/ 

Do you know of any other way to do this in podman then what I am doing? 
I just want to verify my approach is correct, since there are many uid/gid flags in podman.

**Comment by giuseppe** [comment]
> I still get what seems to be a warning of: `groups: cannot find name for group ID 100000`

If you run groups, then it cannot find the ID 100000 in `/etc/group`.  This is an expected error.



> Just for my understanding, this is essentially equivalent to the docker re map user mode, right? https://docs.docker.com/engine/security/userns-remap/

right.

> Do you know of any other way to do this in podman then what I am doing?
> I just want to verify my approach is correct, since there are many uid/gid flags in podman.

I think the way you are doing it in the last command is the correct one.  With root you can map any ID so it makes sense to map exactly the group you need into the container

**Comment by giuseppe** [comment]
since it seems to be solved, I am closing the issue.  Please feel free to keep commenting

**Comment by KCSesh** [comment]
@giuseppe I have noticed that starting containers like this, seems to take the container extra long to start for an image of size ~600mb. 

**With** the `uid/gid mappings` it takes about: **2 minutes and 44 seconds**


**Without** the `uid/gid mappings` it takes about: **Less than 5 seconds.** 

Could you elaborate why this might be happening? 

I see that with I do it **with** the `uid/gid mappings` I see 2 new Filesystems created in my output of 


```
df -h
/dev/mapper/enc_mmcblk0p1   7.9G  6.8G  635M  92% /
/dev/mapper/enc_mmcblk0p21  7.6G  6.1G  1.1G  86% /data
none                         16G     0   16G   0% /dev
tmpfs                        16G  312K   16G   1% /dev/shm
shm                          63M     0   63M   0% /data/podman/users/newuser/podman-root/overlay-containers/bd83b4183449ef29f1902865e327521df7dae35d9189f90a526823fd72ba7b03/userdata/shm
overlay                     7.6G  6.1G  1.1G  86% /data/podman/users/newuser/podman-root/overlay/31b7e78da8ca10c2c274386913bb99321cf619a7b7e314ee681e0919f31f89aa/merged
````

The `shm` and `overlay` are new and go away when I close the container.

**Comment by giuseppe** [comment]
> @giuseppe I have noticed that starting containers like this, seems to take the container extra long to start for an image of size ~600mb.
> 
> **With** the `uid/gid mappings` it takes about: **2 minutes and 44 seconds**
> 
> **Without** the `uid/gid mappings` it takes about: **Less than 5 seconds.**
> 
> Could you elaborate why this might be happening?

when a mapping is specified, containers/storage needs to create a clone of the image with the IDs shifted to what must be used in the user namespace.  Once idmapped mounts will support overlay we won't need this anymore

**Comment by rhatdan** [comment]
Using the image again with the same mapping, should be instantaneous.
Did you use metacopy?
```
grep metacopy /etc/containers/storage.conf
mountopt = "nodev,metacopy=on"
```

**Comment by KCSesh** [comment]
Hey @gabibeyer Thanks for the continued help, I really appreciate it! 

Lets see a few questions. 

I added the CLI: 
```
--storage-opt=mountopt=nodev,metacopy=on
```

But when I do a podman info, I still see the status showing false:


```
  graphOptions:
    overlay.imagestore: /data/cloud/assets/yguysdfiudyf8yww3ebjhwei93hlowie
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /data/podman/users/newuser/podman-root
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
```

1. Not sure if I am missing a step? 
Realistically my kernel is could be too old for that feature (maybe I am wrong).
I am on **4.9** and that won't be changing. 


I do have another follow up question @giuseppe. 

2. If my plan is to only run the image, onetime as a single user. Can I pull the image down as the user that I am planning to run so that no "clone of the image with the IDs shifted to what must be used in the user namespace" happens? 
Maybe if I pulled the image without root, could that speed this up?

**Comment by giuseppe** [comment]
> ```
> 
> ```

yes that could be the reason, that kernel is quite old.



>     1. If my plan is to only run the image one time, as a single user.
> 
> 
> Can I pull the image down as the user that I am planning to run so that no "clone of the image with the IDs shifted to what must be used in the user namespace" happens?
> Maybe if I pulled the image without root, could that speed this up?
> The challenge is I need to still the pull the image with `root` because I need to use `overlay2`.
> I would be fine to manually change the permission of the files if that would work.

does it work if you let the run command pull the image instead of pulling it beforehand?  Please make sure to pass the mapping you want to use.

>     1. Is there anywhere I can read more about: mountopt = "nodev,metacopy=on" ?

you can find more info here: https://www.kernel.org/doc/html/latest/filesystems/overlayfs.html?highlight=overlayfs

**Comment by KCSesh** [comment]
>does it work if you let the run command pull the image instead of pulling it beforehand? Please make sure to pass the mapping you want to use.

Yes, unfortunately. However, for my use case though this wouldn't be a working option, I need the image to exist on device before I run `run`. 

Do you think if I change the permissions manually of the images/layers there is a path forward?

**Comment by KCSesh** [comment]
I just tested it! 

If I manually change all the permissions of the image files/directories to my user, it works quite quickly! This is great! :D

**Comment by KCSesh** [comment]
@giuseppe does it make sense that if I chown the image files permissions to the user it happens instantaneous? 
I am surprised it still doesn't need to do the cloning? 

Also,

> Once idmapped mounts will support overlay we won't need this anymore

Is there a tracking issue for this?

**Comment by giuseppe** [comment]
> > Once idmapped mounts will support overlay we won't need this anymore
> 
> Is there a tracking issue for this?

no that must happen in the kernel first

> If I manually change all the permissions of the image files/directories to my user, it works quite quickly! This is great! :D
> 
> ```
> sudo chown -R 1002:1004 <path-to-image>
> ```

what is `/path/to/image`?

**Comment by KCSesh** [comment]
@giuseppe
> when a mapping is specified, containers/storage needs to create a clone of the image with the IDs shifted to what must be used in the user namespace. 

Is there a way I can view the cloned image files that exist in the username space?

**Comment by KCSesh** [comment]
> /data/podman-read-only
where is this path stored? Network file system?

It is saved on my host, just a different ext4 disk. 

>but it is available only in the local storage DB

This is the bolt_state.db ?

**Comment by KCSesh** [comment]
@giuseppe @rhatdan 
If I start a 2nd container with the same mappings, is that safe to do so? 

Container 1:
```
sudo podman --root /data/podman/some-path --storage-opt=additionalimagestore=/data/podman-read-only run --uidmap 0:1002:1 --uidmap 1:100000:65536 --gidmap 0:1004:1 --gidmap 1:100000:65536 --gidmap 100000:1002:1 -v /tmp:/tmp --rm -it ubuntu
```

Container 2:
```
sudo podman --root /data/podman/some-path --storage-opt=additionalimagestore=/data/podman-read-only run --uidmap 0:2003:1 --uidmap 1:100000:65536 --gidmap 0:2004:1 --gidmap 1:100000:65536 --gidmap 100000:1002:1 -v /tmp:/tmp --rm -it ubuntu
```

(All that changed between 1 and 2 is the "root" user in the container). 

Or do I need to make sure container 2 changes the mapping for me as well? 

```
sudo podman --root /data/podman/some-path --storage-opt=additionalimagestore=/data/podman-read-only run --uidmap 0:2003:1 --uidmap 1:165536:65536 --gidmap 0:2004:1 --gidmap 1:165536:65536 --gidmap 165536:1002:1 -v /tmp:/tmp --rm -it ubuntu
```

Like this where I use: `--uidmap 1:165536:65536 ` and ` --gidmap 1:165536:65536 --gidmap 165536:1002:1 `

If the answer is "yes, you need to update the mappings for each container otherwise you will have user conflicts", 
I just want to know to verify if my approach of starting containers as non-root users with running podman as root seems correct.

**Comment by giuseppe** [comment]
Ir works but you have less security because if a malicious process manages to escape a container then it has control on the files owned by the other container.  It is safer if the mappings are distinct and that is what the --userns=auto functionality is for

**Comment by KCSesh** [comment]
Thanks @giuseppe 

But how would I map additional groups if I was user --userns=auto?

Above you had me map group 1002 as: 

```
--gidmap 100000:1002:1
```
Because host is 100000 would be unused. 

What about for userns=auto? 
How do I pick an unused host is when I don't know which ID's auto is setting?

**Comment by giuseppe** [comment]
please look at the documentation for `userns=auto`.  There is a way to force mappings to be present with "gidmapping": `auto:gidmapping=...`

**Comment by KCSesh** [comment]
@giuseppe  do you mind providing me with more context on what this is doing? 

> sorry, try:
> 
> `sudo podman --runtime /usr/local/bin/crun run --uidmap 0:1002:1 --uidmap 1:100000:65536 --gidmap 0:1004:1 --gidmap 1:100000:65536 --gidmap 100000:1002:1 --group-add 100000 -v /tmp:/tmp --rm -it <image>`

Specifically: 
>--gidmap 100000:1002:1 --group-add 100000

1. This maps group 1002 into the container at ID 100000, then `--group-add 100000` attaches this group to the user running the main container process. Is this accurate?  

2. How does this work with `read-only`? 
I have tested it, and tt works, but I don't understand where this `--group-add 100000` is stored? 
It does not appear under: `/etc/groups` in the container. 
I guess that is what this complaint is: `groups: cannot find name for group ID 100000`
So is this stored in memory? 

This is more for my understanding. 

Thanks!
