### ISSUE TITLE
additionalimagestores as a CLI option for podman and pull option for readonly image store

### ISSUE THREAD

**Issue by KCSesh** [containers/podman#10311]
/kind feature

**Description**

1. Can additionalimagestores be a CLI option for podman. 

```
podman --additional-image-stores <some-path(s)>
```

This can be useful if I want to set the path without it being in the `storage.conf`. 
Having the ability to decide which read-only paths can be viewed via CLI instead of updating the storage.conf.  

2. Also can we get the ability to `pull/load` images as read-only? 

Currently the approach to setup `additionalimagestores` is to pull images normally, and then add the path to the storage.conf. This creates the `libpod/bolt_state.db` that seems to go unused along with other directories if the purpose of the image pull is for read-only. 

I have a use case where I would like to setup a read-only image store location, but then have the freedom to move it to different locations or even between systems of the same arch. All I would like to be contained in the read-only image store is the required image files + layers which from testing appears to be the directories (when using overlay): 
`overlay-images/      overlay-layers/      overlay/`

Suggestion Examples: 
```
podman load -i <some.tar> --read-only-image-store <path> 
OR
podman pull <image> --read-only-image-store <path> 

Alternatively:

podman --root <path> load -i i<some.tar> --read-only-image-store
OR 
podman --root <path> pull <image> --read-only-image-store

```

This way all that would exist in the directory would be: 

```
$ sudo ls root/
overlay-images  overlay-layers  overlay
```
Instead of the usual: 

```
$ sudo ls root/
cache	mounts	 overlay-containers  overlay-layers  tmp
libpod	overlay  overlay-images      storage.lock    userns.lock
```

**Comment by rhatdan** [comment]
podman --storage-opt=additionalimagestore=/var/lib/shared info

**Comment by KCSesh** [comment]
@rhatdan Your comment addresses my #1 point. 

But for #2, I am wondering if there is a specific way to pull images specifically for use in images as read-only doesn't currently exist. 

I essentially want a way to pull images so that it looks like this: 


```
$ sudo ls root/
overlay-images  overlay-layers  overlay
```

Instead of the default: 
```
$ sudo ls root/
cache	mounts	 overlay-containers  overlay-layers  tmp
libpod	overlay  overlay-images      storage.lock    userns.lock
```

**Comment by rhatdan** [comment]
This command would allow you to pull to the addiitonal store.
```
podman --root /var/lib/shared pull fedora
Resolved "fedora" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull registry.fedoraproject.org/fedora:latest...
Getting image source signatures
Copying blob 3d89e185f185 done  
Copying config 5f05951e20 done  
Writing manifest to image destination
Storing signatures
5f05951e20652d401698316fb70d9e7e80e548a03647c033584c871ebc6ccf25
```

**Comment by KCSesh** [comment]
Right, that is the normal pull approach. 

I am suggesting a pull approach that only brings in the image + layers and does not write the `libpod/bolt_state.db` directory or file, along with other unnecessary directories.

**Comment by rhatdan** [comment]
And why would those directories matter?  Size?  Or you just don't like the clutter?

**Comment by KCSesh** [comment]
Right. 

Size + Clutter is definitely part of the reasoning. 

Other points would be: 

- More clear that the directory is meant for read-only 
- I am planning to essentially pull an image on 1 machine, and transfer this read-only directory to another machine. Having the metadata from `libpod` and the other directories seem to be useless and odd. 
  - I could delete the directories myself, but I want to make it `future-proof` and if directories in the future are added I would like to not worry about updating my `delete` unused directories`.
