### ISSUE TITLE
Please rename the master branch to the main branch.

### ISSUE THREAD

**Issue by rhatdan** [containers/podman#10329]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

/kind feature

**Description**

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cevich** [comment]
***Supporting/Required changes:***

* Update `$DEST_BRANCH` in `.cirrus.yml` ***and*** default value in `./contrib/cirrus/lib.sh` and `contrib/cirrus/pr-should-include-tests`
* Update conditional for `"$CIRRUS_BRANCH" == "master"` in `./contrib/cirrus/runner.sh`

(I'll update this comment as/if I find more)

**Comment by TomSweeneyRedHat** [comment]
Almost every *.md file that we have scattered across the site will need attention, plus several other scripts and such.

`grep -R master . | grep -v tests | grep -v vendor | grep -v pkg | grep master`

**Comment by cevich** [comment]
Local podman updates for CI are in https://github.com/containers/podman/pull/10827

Changes for udica are in https://github.com/containers/udica/pull/93

**Comment by rhatdan** [comment]
Done
