### ISSUE TITLE
race condition in `logs -f` with journald driver

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#10323]
Reproducer from https://github.com/containers/podman/pull/10222#issuecomment-839833465:
```
$ while :;do ./bin/podman run --log-driver=journald -d --name foo quay.io/libpod/testimage:20210427 sh -c 'echo hi;sleep 2;echo bye';./bin/podman logs -f foo;./bin/podman rm foo;done
caf4dce7ce3ac5d08da339a8c0ecd4ec97df498cd472fbff61182352e71cf831
hi     <---- there is no subsequent bye!
caf4dce7ce3ac5d08da339a8c0ecd4ec97df498cd472fbff61182352e71cf831
08f58203f738027300d651fed861f1673eb8a1a953b869c788d905664b709938
hi
bye
```

I know where the error is and will drop a `// FIXME` in libpod/container_logs_linux.go (and a link to the code once https://github.com/containers/podman/pull/10222 is merged).

**Comment by vrothberg** [comment]
@rhatdan FYI

**Comment by vrothberg** [comment]
As pointed out in https://github.com/containers/podman/pull/10222/files#diff-20cc30e1cdf302ef7404e5923eada3912c68c8b8943c0a7a0a834b29236eba69R92, using the `Follow` API is racy.  In order to get it done correctly, _we_ have to implement our custom follow function that forward everything from stdout and stderr UNTIL we read on the journal that the container died (i.e., get the died event).

I looked at the journal and the died event is always printed _after_ the logs are written.  The problem at the moment is that we have to many things running concurrently. Having one goroutine reading the log and filtering out what's necessary until we read the died event seems one way to avoid that race.

**Comment by mheon** [comment]
We should refactor the Wait code to use the logic where we wait for the
Died event - it’s already implemented for the Compat API, and should not be
that bad to pry into Libpod. We should then be able to use  that in the
Follow function, as well as turning off polling for every consumer of the
existing Wait code.

**Comment by vrothberg** [comment]
That is not enough to resolve the race unfortunately (tried that). The race
is in reading the journal. Follow() may sleep when streaming which can
cause the died event to be read before the last logs.
