### ISSUE TITLE
Broken language in docs.  The Open Source is not about consumption.

### ISSUE THREAD

**Issue by 5KS** [containers/podman#10325]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
https://github.com/containers/podman/blob/master/docs/source/Introduction.rst
> Containers_ simplify the ***consumption*** of applications with all of their dependencies and default configuration files. ***Users*** ...

**Steps to reproduce the issue:**

1. Read the docs.

2. Being harrased.

**Describe the results you received:**
Frustration.

**Describe the results you expected:**
Consistency.

**Additional information you deem important (e.g. issue happens only occasionally):**
Is this really English in docs?

**Output of `podman version`:**
```
See latest NixOS.
```

**Output of `podman info --debug`:**
```
See latest NixOS.
```

**Package info**

```
See latest NixOS.
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The word crime happened in the Web Browser, your honor.

**Comment by mheon** [comment]
Retagging as documentation.

I'm quite certain this is valid English - to consume can be used in contexts other than food, utilizing something as a customer being one of them. If there are suggestions for better terms, though, I'm not opposed to replacing it.

**Comment by rhatdan** [comment]
Do you have a suggestion that would be better?

**Comment by 5KS** [comment]
Well,
"Containers_ simplify the usage of applications ...".

**Comment by rhatdan** [comment]
How about 
Containers_ simplify the production, distribution, discoverability and usage of applications ...

**Comment by TomSweeneyRedHat** [comment]
@rhatdan I'm chasing a podman.io issue, will take this one as part of that investigation.
