### ISSUE TITLE
Add ability to publish other ports in container restore

### ISSUE THREAD

**Issue by new-sashok724** [containers/podman#10338]
/kind feature

Hello! We use podman checkpoint/restore to speed up the launch of our TCP application in multiple instances.
We run container with application, then when it launched checkpoint it to tar, and then restore it from tar with different names.

**Steps to reproduce the issue:**
1. `podman run -d -p 10000:$port $image`
2. Wait until it started
3. `podman container checkpoint -R -e $container.tar.gz $container`
4. `podman container restore --import $container.tar.gz -n $container2`

**Describe the results you received:**
Container restore fails because published port is already used by original container.
I have to manually modify .tar.gz archive to change the port, which even if automated will be longer than just starting new instance without checkpoint.

Also it would be good to have ability to checkpoint just to uncompressed tar archive, or to directory, and maybe just to publish port after container is created.

**Describe the results you expected:**
There's argument in restore command to publish other ports (-p)

**Output of `podman version`:**
podman version 3.1.2

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**
Yes

**Comment by rhatdan** [comment]
@adrianreber @mheon would this even be possible?

**Comment by new-sashok724** [comment]
It's already possible by modifying config.dump in tar archive. It's just too inconvenient

**Comment by eriksjolund** [comment]
Just an idea, I don't know how realistic it is:

Some imaginary command-line options

* --export-to-stdout  write tar stream to stdout (uncompressed)
* --import-from-stdin read tar stream from stdout (uncompressed)

```
podman container checkpoint -R --export-to-stdout $container | custom_script_to_adjust_port_number | podman container restore --import-from-stdin -n $container2
```
(Note the command-line options `--export-to-stdout` and `--import-from-stdin` do not exist as of now).


I would guess the performance would be less of a problem, because the adjustment of the port number could be done without  the extra decompress and compress steps.

**Comment by new-sashok724** [comment]
I think option to import/export to/from directory would be even more convenient

**Comment by adrianreber** [comment]
> It's already possible by modifying config.dump in tar archive. It's just too inconvenient

If it is just a change in `config.dump` then it would work more or less like the `--name` option. To be honest I never tested port forwarding when implementing checkpoint/restore. I just tested it now and I see that it works. Cool. I think it should be possible to add the `-p` as during container creation also to restore. I will try to implement something and open a pull request next week.

**Comment by adrianreber** [comment]
Please see #10381 for a pull request implementing `--publish` for `restore`.
