### ISSUE TITLE
podman.io seems to be broken

### ISSUE THREAD

**Issue by steve-todorov** [containers/podman#10330]
Hey,

It looks like the https://podman.io/ website is broken. 
Maybe the last deployment didn't go through?

![image](https://user-images.githubusercontent.com/2303663/118153908-1721a980-b41f-11eb-90cc-5409254037d2.png)

**Comment by mheon** [comment]
@TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
Looking,

Thanks for the heads up, I'm not sure what's gone south there...

t

**Comment by Luap99** [comment]
@TomSweeneyRedHat  Can you add an empty commit to podman.io to force a rebuild of the page. Hopefully this fixes it.

**Comment by TomSweeneyRedHat** [comment]
@Luap99 That did indeed fix it, but we used @rhatdan 's PR which touched up a few links.

But the page is back up, thanks for the report.
