### ISSUE TITLE
podman-3.2.0_rc1: `podman image prune` and `podman system prune` now remove all images

### ISSUE THREAD

**Issue by srcshelton** [containers/podman#10350]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

With `podman-3.1.2` and below, `podman image prune` or `podman system prune` would only remove untagged images.

With `podman-3.2.0_rc1`, the same commands remove **all** images not linked to a running container.

This is unhelpful as it clears libraries of cached (and correctly tagged) images.  If this was an intentional change rather than a bug, then it would appear preferable to introduce it as a new option for the `prune` sub-commands, as the current situation is bound to lead to unintended data-loss.

I also note in passing that this may be related to a lack of clarity in the command help text: the `podman image prune` help text reads:

```
$ podman image prune --help
Remove unused images

Description:
  Removes all unnamed images from local storage.

  If an image is not being used by a container, it will be removed from the system.
```

… which appears unclear - which is the intended behaviour: to remove unnamed images, or to remove _all_ images 
not being used by an active container?

The `podman system prune` help text is even less clear:

```
$ podman system prune --help
Remove unused data

Description:
  
        podman system prune

        Remove unused data
```

… which doesn't specify what is classified as 'unused', or what items will be considered.

**Steps to reproduce the issue:**

1. Pull some images

2. `podman image prune -f`

3. `podman image ls`

**Describe the results you received:**

All images removed.

**Describe the results you expected:**

Untagged images removed, but previously pulled images retained (as per pre-`3.2.0_rc1` behaviour).

**Output of `podman version`:**

```
Version:      3.2.0-rc1
API Version:  3.2.0-rc1
Go Version:   go1.16.2
Git Commit:   cb30558bdf8c8f0481c4f05774105fffe0db597a
Built:        Thu May  6 10:55:51 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.20.2-dev
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: app-emulation/conmon-2.0.27
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: 65fad4bfcb250df0435ea668017e643e7f462155'
  cpus: 8
  distribution:
    distribution: gentoo
    version: unknown
  eventLogger: file
  hostname: dellr330
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.12.0-gentoo
  linkmode: dynamic
  memFree: 488505344
  memTotal: 67158777856
  ociRuntime:
    name: crun
    package: app-emulation/crun-0.19.1
    path: /usr/bin/crun
    version: |-
      crun version 0.19.1
      commit: 1535fedf0b83fb898d449f9680000f729ba719f5
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 25428819968
  swapTotal: 25769787392
  uptime: 378h 41m 18.33s (Approximately 15.75 days)
registries:
  localhost:5000:
    Blocked: false
    Insecure: true
    Location: localhost:5000
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: localhost:5000
  search:
  - docker.io
  - docker.pkg.github.com
  - quay.io
  - public.ecr.aws
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 24
    paused: 0
    running: 23
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /space/podman/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 23
  runRoot: /var/run/podman
  volumePath: /space/podman/volumes
version:
  APIVersion: 3.2.0-rc1
  Built: 1620294951
  BuiltTime: Thu May  6 10:55:51 2021
  GitCommit: cb30558bdf8c8f0481c4f05774105fffe0db597a
  GoVersion: go1.16.2
  OsArch: linux/amd64
  Version: 3.2.0-rc1

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Also occurs on ARM64.

**Comment by vrothberg** [comment]
Thanks for the report.  I am looking into it now.

**Comment by vrothberg** [comment]
Opened https://github.com/containers/podman/pull/10363 to fix the issue.
