### ISSUE TITLE
podman-remote: building image cannot find Dockerfile

### ISSUE THREAD

**Issue by Poweranimal** [containers/podman#10351]
/kind bug

**Description**

Building an image based on a `Dockerfile` with rootless remote podman `podman --remote build` fails with the following error:
`Error: stat /var/tmp/libpod_builder635041555/build/Dockerfile: no such file or directory` 

**Steps to reproduce the issue:**

1. Create a `Dockerfile` in current dir.

2. Run `podman --remote build -t debug/building .` in current dir.

**Describe the results you received:**
The follwoing error is returned after executing the build command:
`Error: stat /var/tmp/libpod_builder220925742/build/Dockerfile: no such file or directory`

**Describe the results you expected:**
Expecting a successfull build of the image.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.16.3
Built:        Wed May 12 21:27:59 2021
OS/Arch:      linux/amd64
```

**Output of `podman --remote version`:**

```
Client:
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.16.3
Built:        Wed May 12 21:27:59 2021
OS/Arch:      linux/amd64

Server:
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.16.3
Built:        Wed May 12 21:27:59 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.20.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.27-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 48
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: fedora
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.11.20-300.fc34.x86_64
  linkmode: dynamic
  memFree: 54240124928
  memTotal: 67338047488
  ociRuntime:
    name: crun
    package: crun-0.19.1-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.19.1
      commit: 1535fedf0b83fb898d449f9680000f729ba719f5
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.9-1.fc34.x86_64
    version: |-
      slirp4netns version 1.1.8+dev
      commit: 6dc0186e020232ae1a6fcc1f7afbc3ea02fd3876
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 16m 19.08s
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /var/home/poweranimal/.config/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 1
    stopped: 5
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.5.0-1.fc34.x86_64
      Version: |-
        fusermount3 version: 3.10.2
        fuse-overlayfs: version 1.5
        FUSE library version 3.10.2
        using FUSE kernel interface version 7.31
  graphRoot: /var/home/poweranimal/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 311
  runRoot: /run/user/1000/containers
  volumePath: /var/home/poweranimal/.local/share/containers/storage/volumes
version:
  APIVersion: 3.1.2
  Built: 1620847679
  BuiltTime: Wed May 12 21:27:59 2021
  GitCommit: ""
  GoVersion: go1.16.3
  OsArch: linux/amd64
  Version: 3.1.2

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.1.2-3.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Comment by mheon** [comment]
Possibly related to #9871

**Comment by edsantiago** [comment]
Can you please confirm the exact command that you're using? I cannot reproduce using your instructions, and I know for a fact that `podman-remote build PATH` has been working well. It's the `-f` flag that causes problems.

**Comment by Poweranimal** [comment]
@edsantiago Thank you for your patience.
I'll setup up a my OS from scratch the next days and can report you back in that regard.

However, I haven't mentioned a detail that might contribute to the root cause.
I'm not using plain `fedora 34`, I'm using `fedora 34 silverblue`. Maybe the OS's configurations cause trouble...

**Comment by Poweranimal** [comment]
I did a new `fed 34 silverblue` installation and run the following commands to start `podman remote`:
`systemctl --user enable --now podman.socket`
`sudo loginctl enable-linger $USER`
Afterwards I rebooted the system.

Then I executed `podman --remote build -t debug/podman .`
Now I get another error, telling me I'm not having a TTY session:
```
Error: 1 error occurred:
	* error getting default registries to try: short-name resolution enforced but cannot prompt without a TTY
```
`podman build` works fine in the same session and it also allows me to select the image registry via TTY.

Output of **`podman --remote version`**:
Client:
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.16.3
Built:        Wed May 12 21:27:59 2021
OS/Arch:      linux/amd64

Server:
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.16.3
Built:        Wed May 12 21:27:59 2021
OS/Arch:      linux/amd64

**Comment by edsantiago** [comment]
Can you try specifying precise fully-qualified image names in your Dockerfile? i.e. `FROM reg.istry/namespace/image:tag`

**Comment by Poweranimal** [comment]
Yes, a qualified image name helped.

And I have good news, the `podman --remote build` works fins and doesn't cause any errors.

Apparently something was broken in my old `fed34 silverblue` installation.

Thank you very much for your help and effort.
