### ISSUE TITLE
Is there a way to use podman load, for images saved by docker? 

### ISSUE THREAD

**Issue by KCSesh** [containers/podman#10368]
/kind bug

**Description**

It is unclear to me based on the documentation if podman can load docker images that are saved by the docker cli. 
I have searched and checked: https://github.com/containers/podman/blob/master/troubleshooting.md

I have locally run a test and it seems the answer is no? 

**Steps to reproduce the issue:**

1. `sudo docker save --output ubuntu.tar ubuntu`
2. 

```
sudo podman load < ubuntu.tar

Error: payload does not match any of the supported image formats (oci, oci-archive, dir, docker-archive)
```

If this is expected, what does the documentation mean when it says:

> podman load loads an image from either an oci-archive **or a docker-archive stored on the local machine into container storage** 

Also, would a `podman pull` be the **only way** to get a docker image loaded into podman? 

**Describe the results you received:**
Podman does not load the tar archive generated from docker. 

**Describe the results you expected:**
I would expect podman to load the tar archive generated from docker. 

**Output of `podman version`:**

```
sudo podman --version
podman version 3.2.0-dev
```
**Output of `docker version`:**

```
 docker --version
Docker version 20.10.3, build 48d30b5
```

**Output of `podman info --debug`:**
```
sudo podman info --debug
host:
  arch: amd64
  buildahVersion: 1.20.2-dev
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.28-1.el7.2.1.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.28, commit: '
  cpus: 48
  distribution:
    distribution: '"amzn"'
    version: "2"
  eventLogger: file
  hostname: host
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.102-52.177.amzn2int.x86_64
  linkmode: dynamic
  memFree: 146805985280
  memTotal: 198272716800
  ociRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc94+dev
      commit: 4e50d1c16334d42506f1aa8bfadbdabf785e8acf
      spec: 1.0.2-dev
      go: go1.15.8
      libseccomp: 2.4.1
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 744h 27m 22.97s (Approximately 31.00 days)
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.2.0-dev
  Built: 1621277955
  BuiltTime: Mon May 17 18:59:15 2021
  GitCommit: 0a3444613e5eed3322d2b44cdc94a5ab9678768b
  GoVersion: go1.15.8
  OsArch: linux/amd64
  Version: 3.2.0-dev
 ```
 
 **Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Build from source
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Comment by KCSesh** [comment]
Closing this issue because this appeared to be happening because my:

```
/etc/containers/policy.json
/etc/containers/registries.conf
```

were not correctly configured. 

After fixing those files, loading docker images from podman worked.

**Comment by KCSesh** [comment]
Might be worth making a more meaningful error if possible though? 

> Error: payload does not match any of the supported image formats (oci, oci-archive, dir, docker-archive)

Was not clear that I had an issue in:

```
/etc/containers/policy.json
/etc/containers/registries.conf
```

**Comment by jbarriewalker** [comment]
@KCSesh, please could you give an indication as to what wasn't correct in those files. I'm having the same issue.
