### ISSUE TITLE
podman run --ip6 support

### ISSUE THREAD

**Issue by vikas-goel** [containers/podman#10373]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Is there a timeline for supporting `podman run --ip6` option? The podman manual says the option is not implemented. We are using IPv6 with Docker in RHEL7.9 and planning to move to RHEL 8+ with podman.

**Comment by aojea** [comment]
podman supports ipv6 and dual-stack since https://github.com/containers/podman/pull/8143 that is 2.2.0 IIRC

**Comment by vikas-goel** [comment]
Hello @aojea, @rhatdan,
Is it possible to update podman-run manual to state this? It still says IPv6 not implemented.

**Comment by mheon** [comment]
I don't believe the `--ipv6` flag for static v6 addresses is implemented yet.

**Comment by rugk** [comment]
Duplicate of https://github.com/containers/podman/issues/7511 (?)

**Comment by rhatdan** [comment]
This is being worked on and can be followed in github.com/containers/netavark.

**Comment by Luap99** [comment]
Lets close this as dup of #7511.
