### ISSUE TITLE
unable to install podman-docker on ubuntu to use with docker-compose

### ISSUE THREAD

**Issue by Bharath92** [containers/podman#10378]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am trying to use docker-compose along with podman. I am following this article to do so: https://www.redhat.com/sysadmin/podman-docker-compose. This article mentions that podman-docker is required package for the docker-compose to work. But, I am not able to find that package for Ubuntu. Should this be compiled locally? Any help is appreciated.

**Comment by rhatdan** [comment]
It is not required for this to work. You just need to set DOCKER_HOST to point at /var/run/podman/podman.sock or setup a symbolic link between /run/docker.sock->/run/podman/podman.sock.
