### ISSUE TITLE
`podman info --format {{json .}}` should show available cgroup controllers

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/podman#10376]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

`podman info --format {{json .}}` should show available cgroup controllers, as in `docker info --format {{json .}}`
https://github.com/moby/moby/blob/v20.10.6/api/types/types.go#L148

Related: https://github.com/kubernetes-sigs/kind/pull/2256

**Comment by aojea** [comment]
@AkihiroSuda this is a duplicate of https://github.com/containers/podman/issues/10306

**Comment by AkihiroSuda** [comment]
didn't notice, sorry
