### ISSUE TITLE
Shared volumes, like in Kubernetes Pod

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/podman#10379]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature
or only Idea
**Description**
Enable to create shared volumes at the Pod level like in the Kubernetes Pod

Currently, Podman volumes can be shared via podman run --mounts-from, i.e only at the container level. On other hand, Kubernetes allows share volumes uniformly mounted by all Pod's containers. I would prefer to mount Podman volumes at the Pod level using
either podman volume create --pod mount-point.
or podman volume create & podman pod create --volume volume:mount-point --volume,..
what is easy for implementation.
**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
Seems reasonable, interested in opening a PR?
@haircommander @umohnani8 WDYT?

**Comment by rhatdan** [comment]
@cdoern At some point might want to look at this.

**Comment by cdoern** [comment]
@rhatdan yeah this looks cool! also want to give that buildah issue a try since I haven't worked on anything there yet,

**Comment by cdoern** [comment]
working on this, contingent on #10933 which is the infra container rework

**Comment by rhatdan** [comment]
@cdoern any update on this issue?

**Comment by cdoern** [comment]
yep @rhatdan this is what #11409 deals with. Should be merged soon
