### ISSUE TITLE
rawhide: metacopy flag was not set on file in upper layer

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#10389]
Seeing this in [rawhide gating tests](http://artifacts.dev.testing-farm.io/c8d3bfbd-fd19-4c32-8631-6966576be3c0/work-tests.ymlVlBQbU/tests-HAAq_k/test.podman-rootless-cgroupsv2.bats.log):
```console
$ mkdir -p /tmp/pm/root
$ podman --root /tmp/pm/root pull quay.io/libpod/alpine:latest
Error: metacopy flag was not set on file in upper layer: lgetxattr /tmp/pm/root/overlay/metacopy-check849016741/l2/f: operation not supported
```
Kernel 5.13.0-0.rc1.20210513gitc06a2ba62fc4.15.fc35

container-selinux-2.162.1-2.dev.git233e620.fc35 and also 2.162.1-3.dev.git233e620.fc35

I tried `chcon -R -v -t container_ro_file_t /tmp/pm/root/overlay`, no luck.

[UPDATE: `setenforce 0` has no effect, so this may not be SELinux-related]

**Comment by rhatdan** [comment]
I am using one less then the current kernel in Rawhide and this worked for me.

Ok this is happening to me also, with the current podman.

@giuseppe PTAL

./bin/podman --root /tmp/podman_bats_login.uTSrPQ/root1 --runroot /tmp/podman_bats_login.uTSrPQ/runroot1 pull quay.io/libpod/registry:2.7
Error: metacopy flag was not set on file in upper layer: lgetxattr /tmp/podman_bats_login.uTSrPQ/root1/overlay/metacopy-check906030688/l2/f: operation not supported

**Comment by rhatdan** [comment]
24041 lgetxattr("/tmp/podman_bats_login.uTSrPQ/root1/overlay/metacopy-check916359409/l2/f", "user.overlay.metacopy", 0xc000050600, 128) = -1 EOPNOTSUPP (Operation not supported)

**Comment by rhatdan** [comment]
@mheon This might be a showstopper for the release?

**Comment by mheon** [comment]
If it's just gating tests... Probably not for an RC?

**Comment by mheon** [comment]
Given this is just an RC I am fine with not having everything completely 100%

**Comment by rhatdan** [comment]
Sure, I just would like to have @giuseppe input.  I am not sure why this is blowing up for me.

**Comment by giuseppe** [comment]
> 24041 lgetxattr("/tmp/podman_bats_login.uTSrPQ/root1/overlay/metacopy-check916359409/l2/f", "user.overlay.metacopy", 0xc000050600, 128) = -1 EOPNOTSUPP (Operation not supported)

it seems like xattrs failing on tmpfs?  Do you get the same error if you try on another file system?

**Comment by giuseppe** [comment]
I see.  You are running as rootless, so on 5.13 we use native overlay by default.

metacopy is not supported (for security reasons) when running as unprivileged

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/storage/pull/913

**Comment by rhatdan** [comment]
@mheon FYI ^^.  We will have this issue in RC2, but can safely wait until final release for this fix.

**Comment by rhatdan** [comment]
I just released https://github.com/containers/storage/releases/tag/v1.31.2, which should get dependaboted into here tomorow, which should fix this issue, so I am going to close.
