### ISSUE TITLE
flake: ubuntu 2010: systemd: Failed to create ... control group, EPERM

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#10386]
Starting to see this flake often on ubuntu:
```console
$ podman run ... -t -i -d registry.access.redhat.com/ubi8-init /sbin/init
systemd 239 (239-41.el8_3.2) running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=legacy)
Detected virtualization container-other.
Detected architecture x86-64.

Welcome to Red Hat Enterprise Linux 8.3 (Ootpa)

Set hostname to <7ee143227d95>.
Initializing machine ID from random generator.
Failed to read AF_UNIX datagram queue length, ignoring: No such file or directory
Failed to install release agent, ignoring: Permission denied
Failed to create /user.slice/user-27341.slice/session-3.scope/init.scope control group: Permission denied
Failed to allocate manager object: Permission denied
!!!!!!
Failed to allocate manager object, freezing.
Freezing execution.
```

## Podman systemd [It] podman run container with systemd PID1
* ubuntu-2010 : int podman ubuntu-2010 rootless host
  * PR #10369
    * [05-17 17:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5325276205809664/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [05-17 17:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5325276205809664/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [05-17 17:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5325276205809664/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #10328
    * [05-17 10:40](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6401947835039744/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [05-17 10:40](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6401947835039744/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [05-17 10:40](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6401947835039744/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #10300
    * [05-10 18:01](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4841312982663168/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [05-10 18:01](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4841312982663168/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [05-10 18:01](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4841312982663168/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #10291
    * [05-10 10:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6043197034987520/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [05-10 10:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6043197034987520/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [05-10 10:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6043197034987520/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #10239
    * [05-11 22:06](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4566239319162880/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [05-11 22:06](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4566239319162880/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [05-11 22:06](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4566239319162880/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)

**Comment by rhatdan** [comment]
Well it is not SELinux, is there anyway we could check the audit.log to see if there is any seccomp failures?

**Comment by edsantiago** [comment]
OMG yes there is! Thanks to the foresight of @cevich, audit.log is preserved! For any of the above logs, go to the top, click the **Task** link, scroll to the bottom, and expand the **audit** accordion. [Example](https://cirrus-ci.com/task/5325276205809664?logs=audit_log#L0). (I have no idea what to look for, though)

**Comment by rhatdan** [comment]
No seccomp failures, that I see.

**Comment by rhatdan** [comment]
This looks like ubuntu occasionally has a cgroup file system that is not allowed to be written from within the container.
@giuseppe Any thoughts?

**Comment by giuseppe** [comment]
cgroup v1 for systemd doesn't need to be writeable, just `/sys/fs/cgroup/systemd`.

Are the rootless tests running from a `systemd-run --scope --user` environment?

**Comment by edsantiago** [comment]
I don't know what that means. They are running as a user with the magic `loginctl` enabled, via ansible `become_user`.

**Comment by edsantiago** [comment]
Oops - correction, these are failing in CI, not gating tests. I don't know what the setup is for rootless (wrt loginctl) but AFAICT those are run via `ssh user@localhost`. The interesting thing is that this is e2e tests, not system tests. e2e tests do automatic triple-retries, and in all the cases above, all three fail. That is: once a host gets into a mode where this test fails, it will always fail. A CI retry (which spins up a new VM) then succeeds.

**Comment by cevich** [comment]
Weird. 

> AFAICT those are run via ssh user@localhost

Correct.

> e2e tests do automatic triple-retries

Additionally: The tests run in a randomized order.  The "seed" for the order is displayed at the beginning.  It's possible to run the tests with a specified seed, to guarantee the order.  It might be useful to nail-down whether or not this failure is influenced by another test munging the system, or is the failure ever  reproducible when running just this one test in isolation (on a fresh VM)

**Comment by edsantiago** [comment]
## Podman systemd [It] podman run container with systemd PID1
* ubuntu-2010 : int podman ubuntu-2010 rootless host
  * PR #10506
    * [05-31 06:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6178769590288384/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [05-31 06:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6178769590288384/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [05-31 06:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6178769590288384/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #10485
    * [05-27 11:01](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6605149046046720/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [05-27 11:01](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6605149046046720/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [05-27 11:01](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6605149046046720/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #10369
    * [05-17 17:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5325276205809664/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [05-17 17:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5325276205809664/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [05-17 17:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5325276205809664/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #10328
    * [05-17 10:40](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6401947835039744/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [05-17 10:40](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6401947835039744/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [05-17 10:40](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6401947835039744/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)

**Comment by edsantiago** [comment]
## Podman systemd [It] podman run container with systemd PID1
* ubuntu-2010 : int podman ubuntu-2010 rootless host
  * PR #10532
    * [06-02 09:05](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5178664745697280/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [06-02 09:05](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5178664745697280/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [06-02 09:05](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5178664745697280/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #10509
    * [05-31 09:46](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5194196689616896/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [05-31 09:46](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5194196689616896/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [05-31 09:46](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5194196689616896/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)

**Comment by rhatdan** [comment]
Could this be AppArmor causing this?  Has anyone looked at the audit.log to see if apparmor is complaining about something?

**Comment by edsantiago** [comment]
For any log link above: click the link, Press `Home` key to go to the top of the log, click the `Task` link at top. That takes you to the Cirrus page for the failed run. I don't see an AppArmor log anywhere, but there's a `Run journal` tab that includes things like "PID", "scope", "control group", and EPERM.

**Comment by cevich** [comment]
IIRC, there is no `audit.log` on Ubuntu, AppArmor messages are logged into `kern.log` which is captured under the 'audit' tab.  The `journal` tab also may have clues as Ed explained.

**Comment by edsantiago** [comment]
## Podman systemd [It] podman run container with systemd PID1
* ubuntu-2010 : int podman ubuntu-2010 rootless host
  * PR #10635
    * [06-10 07:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5881830315393024/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [06-10 07:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5881830315393024/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [06-10 07:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5881830315393024/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #10628
    * [06-10 03:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5233077971582976/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [06-10 03:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5233077971582976/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [06-10 03:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5233077971582976/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #10605
    * [06-08 15:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6349956568055808/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [06-08 15:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6349956568055808/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [06-08 15:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6349956568055808/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)

**Comment by cevich** [comment]
In case it matters: New VM images for Ubuntu were ***just*** merged in for use by PR https://github.com/containers/podman/pull/10451 . This includes (among other things) and updated runc v1.0-rc95.

**Comment by edsantiago** [comment]
## Podman systemd [It] podman run container with systemd PID1
* ubuntu-2010 : int podman ubuntu-2010 rootless host
  * PR #10811
    * [06-29 09:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6338015317458944/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [06-29 09:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6338015317458944/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [06-29 09:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6338015317458944/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #10803
    * [06-28 16:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4612754737725440/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [06-28 16:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4612754737725440/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [06-28 16:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4612754737725440/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #10696
    * [06-23 10:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5388217055707136/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [06-23 10:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5388217055707136/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [06-23 10:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5388217055707136/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #10583
    * [06-23 13:39](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4931765715337216/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [06-23 13:39](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4931765715337216/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [06-23 13:39](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4931765715337216/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
* ubuntu-2104 : int podman ubuntu-2104 rootless host
  * PR #10759
    * [06-23 08:00](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5991574128558080/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [06-23 08:00](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5991574128558080/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [06-23 08:00](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5991574128558080/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)

**Comment by edsantiago** [comment]
[Another one](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5807505197498368/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)

**Comment by cevich** [comment]
FWIW, I'm working my way through numerous issues blocking adoption of  refreshed VM images in #10829.  Not sure if they will have any impact on this issue or not, but I'll keep my eyes out.

**Comment by edsantiago** [comment]
Some more:

* ubuntu-2010 : int podman ubuntu-2010 rootless host
  * PR #10999
    * [07-20 17:25](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4753710577352704/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [07-20 17:25](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4753710577352704/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [07-20 17:25](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4753710577352704/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #10932
    * [07-15 07:51](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5807505197498368/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [07-15 07:51](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5807505197498368/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [07-15 07:51](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5807505197498368/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #10896
    * [07-09 18:56](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6667268898684928/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [07-09 18:56](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6667268898684928/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [07-09 18:56](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6667268898684928/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #10836
    * [07-02 11:58](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6640422232522752/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [07-02 11:58](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6640422232522752/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [07-02 11:58](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6640422232522752/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)

**Comment by edsantiago** [comment]
The past month:

### Podman systemd [It] podman run container with systemd PID1
* ubuntu-2010 : int podman ubuntu-2010 rootless host
  * PR #11333
    * [08-27 07:03](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5372310774349824/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [08-27 07:03](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5372310774349824/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [08-27 07:03](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5372310774349824/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #11153
    * [08-09 10:06](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6107772820389888/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [08-09 10:06](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6107772820389888/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [08-09 10:06](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6107772820389888/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #11120
    * [08-03 15:31](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6496152620105728/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [08-03 15:31](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6496152620105728/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [08-03 15:31](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6496152620105728/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #11101
    * [08-02 17:57](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5519583357435904/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [08-02 17:57](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5519583357435904/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [08-02 17:57](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5519583357435904/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #11097
    * [08-02 15:52](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4524904365162496/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [08-02 15:52](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4524904365162496/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [08-02 15:52](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4524904365162496/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #11082
    * [08-01 08:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5393852082159616/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [08-01 08:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5393852082159616/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [08-01 08:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5393852082159616/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #11073
    * [07-29 05:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5775927943626752/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [07-29 05:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5775927943626752/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [07-29 05:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5775927943626752/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #10861
    * [07-26 17:27](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6727261337419776/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [07-26 17:27](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6727261337419776/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [07-26 17:27](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6727261337419776/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)

**Comment by rhatdan** [comment]
Did the conmon attach fix this Issue?

**Comment by edsantiago** [comment]
Last seen September 10. Last change to `IMAGE_SUFFIX` in `.cirrus.yml` was committed on September 14. I don't know if it includes the new conmon or not... but I'm comfortable closing this with fingers crossed.

## Podman systemd [It] podman run container with systemd PID1
* ubuntu-2010 : int podman ubuntu-2010 rootless host
  * PR #11523
    * [09-10 08:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6490688910000128/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [09-10 08:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6490688910000128/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [09-10 08:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6490688910000128/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #11503
    * [09-09 12:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5089997867974656/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [09-09 12:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5089997867974656/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [09-09 12:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5089997867974656/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
  * PR #11451
    * [09-05 13:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5305984961740800/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--1)
    * [09-05 13:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5305984961740800/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--2)
    * [09-05 13:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5305984961740800/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-run-container-with-systemd-PID1--3)
