### ISSUE TITLE
podman play kube does not apply labels

### ISSUE THREAD

**Issue by alucryd** [containers/podman#10401]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm trying to use the auto-update feature of podman and added the `io.containers.autoupdate: registry` label to my pod definition, however `podman play kube` does not apply it, the label does not appear in `podman ps`.

My Kube YAML: https://paste.xinu.at/7u47JTC9DpO4zcON/

**Steps to reproduce the issue:**

1. Add the `io.containers.autoupdate: registry` label to a pod

2. Play the kube file with `podman play kube`

3. Notice the label does not appear in `podman ps -a --format "{{.Names}} {{.Labels}}"`

**Describe the results you received:**

No label so auto-update is unusable.

**Describe the results you expected:**

Label should be added and auto-update be usable.

**Additional information you deem important (e.g. issue happens only occasionally):**

I followed this guide, replacing `image` with `registry` as it seems `image` is deprecated: https://www.jwillikers.com/automatically-update-podman-containers

**Output of `podman version`:**

```
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.16.3
Git Commit:   51b8ddbc22cf5b10dd76dd9243924aa66ad7db39
Built:        Wed Apr 21 23:34:03 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.20.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.0.28-1
    path: /usr/bin/conmon
    version: 'conmon version 2.0.28, commit: 6b18f7e0f2e4cd7f7b016b88141e82210d370008'
  cpus: 8
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: server
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.11.21-hardened1-2-hardened
  linkmode: dynamic
  memFree: 24617160704
  memTotal: 33565261824
  ociRuntime:
    name: runc
    package: /usr/bin/runc is owned by runc 1.0.0rc94-1
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc94
      commit: 2c7861bc5e1b3e756392236553ec14a78a09f8bf
      spec: 1.0.2-dev
      go: go1.16.4
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 41m 7.82s
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 15
    paused: 0
    running: 8
    stopped: 7
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Build Version: 'Btrfs v5.11.1 '
    Library Version: "102"
  imageStore:
    number: 9
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.1.2
  Built: 1619040843
  BuiltTime: Wed Apr 21 23:34:03 2021
  GitCommit: 51b8ddbc22cf5b10dd76dd9243924aa66ad7db39
  GoVersion: go1.16.3
  OsArch: linux/amd64
  Version: 3.1.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman 3.1.2-1
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical Arch Linux server

**Comment by mheon** [comment]
Will be fixed in 3.2.0, thanks to @EduardoVega
