### ISSUE TITLE
Permission denied when --mount'ing a directory not owned by container root (with --uidmap)

### ISSUE THREAD

**Issue by PhrozenByte** [containers/podman#10403]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

This might not really be a bug in Podman, but a kernel limitation.

**Description**

I'm trying to `podman run` a rootful container with a user namespace (`--uidmap`) and getting a "Permission denied: OCI permission denied" error when trying to `--mount` a directory that isn't either owned by the container root or world readable/writeable, even though the container root has full access to said directory via a mutual group. It looks like group permissions are being ignored.

It seems like Podman (tbh, I rather assume it's actually the kernel, not Podman) isn't taking group permissions into account when `stat`'ing the bind mount's source directory. If I either change ownership of `/srv/storage/test` to the container root (user `testuser_croot`, uid 100000), or change permissions of `/srv/storage/test` to 777 (i.e. making it world readable/writeable), everything works fine.

**Steps to reproduce the issue:**

Run all commands as `root`.

1. Create users `testuser` (uid 2001) and `testother` (uid 2002) as well as the directory `/srv/storage/test` to `--mount` (owned by user `testother` and with `770` permissions):
    ```sh
    useradd -u 2001 -g 2001 -d / testuser
    useradd -u 2002 -g 2002 -d / testother

    mkdir /srv/storage{,/test}
    chown testother:testother /srv/storage{,/test}
    chmod 770 /srv/storage{,/test}
    ```

2. User `testuser` is going to use the subuid/subgid range 100000-165535. Create user `testuser_croot` (uid 100000) representing the container root on the host, use group `testuser` (gid 2001) as primary group, but also add it to group `testother` (gid 2002):
    ```sh
    useradd -u 100000 -g 2001 -d / testuser_croot
    useradd -aG testother testuser_croot
    ```

    User `testuser_croot` (uid 100000) now has full permissions on `/srv/storage/test` due to the common group `testother` (gid 2002):

    ```sh
    sudo -u testuser_croot -- sh -c "echo foo > /srv/storage/test/bar"
    ```

3. Create a simple test image:
    ```sh
    CONTAINER="$(buildah from 'docker.io/busybox')"
    buildah config --cmd "sleep 3600" "$CONTAINER"
    buildah commit "$CONTAINER" "sleeper"
    ```

4. Try `--mount`ing `/srv/storage` with a `--uidmap`:
    ```sh
    podman run -dt --name "sleeper-test" --uidmap 0:100000:65536 --gidmap 0:100000:65536 --mount "type=bind,source=/srv/storage/test,destination=/mnt" "sleeper"
    ```

**Describe the results you received:**

```
Error: error stat'ing file `/srv/storage`: Permission denied: OCI permission denied
```

**Describe the results you expected:**

Container is up and bind mounts `/srv/storage/test` to `/mnt` in the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

See description above.

<details>
<summary><strong>Output of <code>podman version</code>:</strong></summary>

```
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.16.3
Git Commit:   51b8ddbc22cf5b10dd76dd9243924aa66ad7db39
Built:        Wed Apr 21 23:34:03 2021
OS/Arch:      linux/amd64
```
</details>

<details>
<summary><strong>Output of <code>podman info --debug</code>:</strong></summary>

```
host:
  arch: amd64
  buildahVersion: 1.20.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.0.28-1
    path: /usr/bin/conmon
    version: 'conmon version 2.0.28, commit: 6b18f7e0f2e4cd7f7b016b88141e82210d370008'
  cpus: 3
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: SGS-CPX21-Nuernberg-1
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.37-1-lts
  linkmode: dynamic
  memFree: 3686375424
  memTotal: 4019585024
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 0.19.1-1
    path: /usr/bin/crun
    version: |-
      crun version 0.19.1
      commit: 1535fedf0b83fb898d449f9680000f729ba719f5
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 14h 46m 3.63s (Approximately 0.58 days)
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 13
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.1.2
  Built: 1619040843
  BuiltTime: Wed Apr 21 23:34:03 2021
  GitCommit: 51b8ddbc22cf5b10dd76dd9243924aa66ad7db39
  GoVersion: go1.16.3
  OsArch: linux/amd64
  Version: 3.1.2
```
</details>

<details>
<summary><strong>Package info (e.g. output of <code>rpm -q podman</code> or <code>apt list podman</code>):</strong></summary>

Running `pacman -Qs podman`:

```
local/podman 3.1.2-1
    Tool and library for running OCI-based containers in pods
```
</details>

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Hetzner Cloud server. SELinux is disabled for now.

**Comment by mheon** [comment]
@giuseppe @rhatdan Ideas?

**Comment by giuseppe** [comment]
so is `/srv/storage` owned by 2002:2002 and the mappings you are using for the user namespace are ` 0:100000:65536` and ` 0:100000:65536`?

That won't work, you need to make sure 2002 (either the uid, or gid, or both) are mapped inside the user namespace

**Comment by PhrozenByte** [comment]
Okay, this is embarrassing :disappointed: I didn't even think about adding user `testother` to the mapping, because I expected it to end up as user `nobody`. After knowing the solution and thinking about it it totally makes sense. Adding `--uidmap 65536:2002:1 --gidmap 65536:2002:1` works.

Sorry for the noise. Keep up the amazing work. Thank you! :heart:

**Comment by giuseppe** [comment]
> Okay, this is embarrassing disappointed

no worries, user namespaces are confusing sometimes.
