### ISSUE TITLE
podman in HPC with mpich

### ISSUE THREAD

**Issue by adrianreber** [containers/podman#10409]
For a long time it is possible to run Open MPI based containers using Podman. The option `--env-host` was introduced to forward all information from the main `mpirun` process to individual ranks (processes) each running in a separate container.

Trying this with MPICH does not work. It seems (not yet confirmed) that MPICH uses another mechanism to communicate between the main MPI process and the ranks. My current guess is that MPICH passes down FDs to each child processes which are then used to exchange information.

Looking at open FDs from a process running under the control of mpirun shows a couple of open FDs:
```
$ mpirun sleep infinity
$ lsof -p `pidof sleep`
sleep   26038  mpi    0r  FIFO               0,13      0t0    95206 pipe
sleep   26038  mpi    1w  FIFO               0,13      0t0    95207 pipe
sleep   26038  mpi    2w  FIFO               0,13      0t0    95208 pipe
sleep   26038  mpi    3r  FIFO               0,13      0t0    92467 pipe
sleep   26038  mpi    4w  FIFO               0,13      0t0    92467 pipe
sleep   26038  mpi    5u  IPv4              92468      0t0      TCP *:38299 (LISTEN)
sleep   26038  mpi    6u  unix 0xffff9315adf9b180      0t0    95205 type=STREAM
sleep   26038  mpi    7u  unix 0xffff9315adc5ba80      0t0    92470 type=STREAM
sleep   26038  mpi    8r  FIFO               0,13      0t0    95206 pipe
sleep   26038  mpi    9w  FIFO               0,13      0t0    92471 pipe
sleep   26038  mpi   11w  FIFO               0,13      0t0    92472 pipe
sleep   26038  mpi   13w  FIFO               0,13      0t0    95207 pipe
sleep   26038  mpi   15w  FIFO               0,13      0t0    95208 pipe
```

Doing the same with Podman (as it would work with Open MPI):
```
$ mpirun podman run --env-host --userns=keep-id --net=host --pid=host --ipc=host ubi8 sleep infinity
$ lsof -p `pidof sleep`
sleep   26142  mpi    0u      CHR    1,3      0t0     9096 /dev/null
sleep   26142  mpi    1w     FIFO   0,13      0t0    96879 pipe
sleep   26142  mpi    2w     FIFO   0,13      0t0    96880 pipe
$ lsof -p `pidof podman`
podman  26081  mpi    0r     FIFO               0,13      0t0    96618 pipe
podman  26081  mpi    1w     FIFO               0,13      0t0    96619 pipe
podman  26081  mpi    2w     FIFO               0,13      0t0    96620 pipe
podman  26081  mpi    3r     FIFO               0,13      0t0    92605 pipe
podman  26081  mpi    4w     FIFO               0,13      0t0    92605 pipe
podman  26081  mpi    5u     IPv4              92606      0t0      TCP *:40155 (LISTEN)
podman  26081  mpi    6u     unix 0xffff9315adf9b180      0t0    96617 type=STREAM
podman  26081  mpi    7u     unix 0xffff9315adc5ba80      0t0    92608 type=STREAM
podman  26081  mpi    8r     FIFO               0,13      0t0    96618 pipe
podman  26081  mpi    9w     FIFO               0,13      0t0    92609 pipe
podman  26081  mpi   10u     unix 0xffff9315a392cc80      0t0    89720 @00031 type=DGRAM
podman  26081  mpi   11w     FIFO               0,13      0t0    92610 pipe
podman  26081  mpi   12u  a_inode               0,14        0     9090 [eventpoll]
podman  26081  mpi   13w     FIFO               0,13      0t0    96619 pipe
podman  26081  mpi   14r     FIFO               0,13      0t0    89715 pipe
podman  26081  mpi   15w     FIFO               0,13      0t0    96620 pipe
podman  26081  mpi   16w     FIFO               0,13      0t0    89715 pipe
podman  26081  mpi   17r      REG                8,3  9253600  8572544 /var/lib/sss/mc/passwd
podman  26081  mpi   18u     unix 0xffff9315a3929b00      0t0    89723 type=STREAM
podman  26081  mpi   19u     unix 0xffff9315add4ad00      0t0    91508 type=SEQPACKET
```

Unfortunately right now I am still only guessing but I want to open a corresponding issue with MPICH to get some input from their side.

So it seems using MPICH based containers with Podman in a way it is possible with Open MPI does not work currently.

I am using Podman 3.1.0 on a  RHEL 8.4 system with MPICH from OpenHPC mpich-ucx-gnu9-ohpc-3.3.2-13.1.ohpc.2.0.x86_64

For now this is just a bug to track this not 100% understood problem.

**Comment by adrianreber** [comment]
I asked upstream mpich if they could comment on this issue how the communication between the main process and the ranks is working: https://github.com/pmodels/mpich/issues/5292

**Comment by marcodelapierre** [comment]
I have just open another issue, detailing the error in attempting to use Podman with MPICH:

https://github.com/containers/podman/issues/10410

**Comment by giuseppe** [comment]
could `run --preserve-fds` be helpful in this case?

**Comment by adrianreber** [comment]
> could `run --preserve-fds` be helpful in this case?

Very interesting option. I was not aware of it. It gets me a small step closer. Running a single rank `mpirun -np 1`  seems to work, but it does not work with two ranks or more `mpirun -np 2`.

The problem seems to be that `--preserve-fds`  does not like if some FDs in the range are closed. FD 10 12 16 18 are not open and the necessary number of FDs is also not always the same. I could try a hack to see if it works if Podman just ignores FDs which are not open in the range given in  `--preserve-fds`. Thanks for the pointer.

**Comment by adrianreber** [comment]
Removing the check from `--preserve-fds` gets me a bit further. I can run an MPICH based test case with two processes/ranks:
```
mpirun -np 2 podman run --env-host --userns=keep-id --net=host --pid=host --ipc=host -v /root:/home -v /usr/:/usr/ -v /lib64:/lib64 --preserve-fds 6 fedora:34 /home/ring
```
It does not work with `-np 3` or more ranks. So it seems to be doable to pass the FDs from the outside to the container process. Good. Now it would be good to know which FDs are necessary. I hope someone from the MPICH side can help us out.

**Comment by adrianreber** [comment]
mpich has a mode to run without FDs: `mpirun -pmi-port`. That works also for me. Closing.
