### ISSUE TITLE
BUG REPORT: podman build may run into storage problems when a step cause lot of changes

### ISSUE THREAD

**Issue by groovyman** [containers/podman#10413]
/kind bug

**Description**
The problem occurred on a test-platform, that helps to check, if a systemupgrade can 
be performed on the same productive environment. The productive is a Fedora F33-server 
server host and a F33-container os. The container is used to run a root-less accounting
web-application. 
This application runs on the top of a Fedora-Linux, using apache, perl and latex for printing,
and is connected to a postgres-DB running on the server itself. The container and its
services is driven by a systemd, that is running in the container too. You can call him
a fatty container.

While building `podmain build` the container performs a an update on the recent fedora (it must be now  F34)  and then performs lot of updates. After this he trys to load additional packages to run the accounting app.

`
FROM fedora

\# perform updates 
RUN dnf -y update
\# perform install (disabled php-fpm)
RUN dnf -y install  `[[ ${POSTGR_HOST} != '127.0.0.1' &&  ${POSTGR_HOST} != 'localhost' ]] || echo postgresql-server`\
  httpd mod_fcgid  postgresql-contrib\
  perl-Algorithm-CheckDigits perl-Archive-Zip perl-Archive-Extract-zip-Archive-Zip perl-CPAN perl-Class-XSAccessor \
  perl-Clone perl-Config-Std perl-DBD-Pg perl-DBI perl-Daemon-Generic \
  perl-DateTime perl-DateTime-Set perl-Email-Address perl-Email-MIME perl-FCGI \
  perl-File-Copy-Recursive perl-File-Flock perl-File-MimeInfo perl-File-Slurp \
  perl-GD perl-HTML-Restrict perl-JSON perl-List-MoreUtils perl-List-UtilsBy \
  perl-Net-SMTP-SSL perl-Net-SSLGlue perl-PBKDF2-Tiny perl-PDF-API2 \
  perl-Params-Validate perl-Regexp-IPv6 perl-Rose-DB perl-Rose-DB-Object \
  perl-Rose-Object perl-Sort-Naturally perl-String-ShellQuote \
  perl-Template-Toolkit perl-Text-CSV_XS perl-Text-Iconv perl-URI perl-XML-Writer \
  perl-YAML perl-libwww-perl cpanminus \
  aqbanking poppler-utils  \
  php-pecl-apcu php-cli php-pear php-pdo php-mysqlnd php-pgsql php-gd  php-xml php-zipstream \ 
  texlive-scheme-medium texlive-collection-latex texlive-collection-latexextra \
  texlive-collection-latexrecommended texlive-collection-langgerman \
  texlive-collection-langenglish\
  langpacks-de git procps-ng
`
The most recent intall will kill him, when podman tries to commit that step:
`
Complete!
Error: error committing container for step {Env:[A_POSTGR_PORT=5435 A_POSTGR_USR=tu_lxoffic DISTTAG=f34container FGC=f34 container=oci EXT_LOGDIR=/var/log ADMIN_PWD=1geheim APACHE_LOGDIR=/var/log/httpd POSTGR_USR=tu_lxoffic POSTGR_PWD=1geheim POSTGR_DB=postgres POSTGR_HOST=kividb POSTGR_PORT=5435 POSTGR_DATADIR=/var/lib/pgsql/data POSTGR_LOGDIR=/var/lib/pgsql/data/log POSTGR_KIVI_AUTH_USR=postgres POSTGR_KIVI_AUTH_PWD=1geheim POSTGR_KIVI_AUTH_DB=kivitendo_auth POSTGR_KIVITST_USR=grtst POSTGR_KIVITST_PWD=1geheim TERM=vt100 locale=de_DE postgrespassword=1geheim KIVITENDO_VER=release-3.5.6.1 KIVITENDO_DATA=/var/www/kivitendoData PG_HOSTNAME= PG_DATA= APACHE_LOG_DIR=/var/log/httpd PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:run Args:[dnf -y install  `[[ ${POSTGR_HOST} != '127.0.0.1' &&  ${POSTGR_HOST} != 'localhost' ]] || echo postgresql-server`  httpd mod_fcgid  postgresql-contrib ...
texlive-scheme-medium texlive-collection-latex texlive-collection-latexextra   texlive-collection-latexrecommended texlive-collection-langgerman   texlive-collection-langenglish  langpacks-de git procps-ng}: error copying layers and metadata for container "047b8afeb1ded13044a1211e102ab6cee6c085c7fe874ace54074d5bb65e1361": Error initializing source containers-storage:834466bb4d44576dcac73d6a250772941daa44f62b3578ebb5c2b2a48cb86435-working-container: error extracting layer "b52227b3d4f0761ee82e8d8b1ee6322f521c627d1addd5c92f43d949d4808851": lgetxattr /mnt/raider/home2/techlxoffice/.local/share/containers/storage/overlay/b52227b3d4f0761ee82e8d8b1ee6322f521c627d1addd5c92f43d949d4808851/merged/var/cache/dnf/fedora-cisco-openh264-ffa960505abcfb54/repodata/3d50825fb25440abc9579f078205d6ba3590b1d146187af8179eb43214c8b40e-comps-Temporary.x86_64.xml.gz: software caused connection abort
`
Yes of course i checked via `ls -dZ` the KIVITENDO_DATA directory, that is located in the (tech-) users home directory.
Do you have any idea, why i received that message:
`error copying layers and metadata for container "537c264841188e82407cbe898f34d98071c0d718e895fc66bcb0057bfee2503d": Error initializing source containers-storage:511be9d72b4effbec63b6d8e0409d2d8817d35097df40d667181b2ef454e991a-working-container: error extracting layer "6fa0a74d49b34e6ff2163fe02e83aed0d48adb93cd173fb80b03093e0e4ea0c2": lgetxattr /mnt/raider/home2/techlxoffice/.local/share/containers/storage/overlay/6fa0a74d49b34e6ff2163fe02e83aed0d48adb93cd173fb80b03093e0e4ea0c2/merged/var/cache/dnf/fedora-cisco-openh264-ffa960505abcfb54/repodata/3d50825fb25440abc9579f078205d6ba3590b1d146187af8179eb43214c8b40e-comps-Temporary.x86_64.xml.gz: software caused connection abort
^C[1]+  Exit 125`

A connection abort sounds like a ressouce problem, am i right?

**Steps to reproduce the issue:**

1. simply call  `podman build --tag kivirel:V0_6_0 --tmpdir=${DATA_STORE}/podmanTMP -v ${DATA_STORE}/data:/var/lib/pgsql/data:z  -v ${DATA_STORE}/logs:/var/log:z -v ${DATA_STORE}/rteFiles:/www/kivitendoData:z --build-arg  A_POSTGR_USR=tu_lxoffic --build-arg POSTGR_PWD=lx1geheim --build-arg   A_POSTGR_PORT=5435  --cgroup-manager=cgroupfs .`

2. 

3.

**Describe the results you received:**

It smells like a exhausted ressource somewhere in the code. 

**Describe the results you expected:**

I would exprect a docker image, that is generated on the F33 node.

**Additional information you deem important (e.g. issue happens only occasionally):**
Just a note, this tech-user account has been recreated.

**Output of `podman version`:**

```
$ podman --version 
podman version 3.1.2
```

**Output of `podman info --debug`:**

```
[techlxoffice@chasmash docker_kivitendo]$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.20.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.27-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 4
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: chasmash
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1003
      size: 1
    - container_id: 1
      host_id: 296608
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
  kernel: 5.11.20-300.fc34.x86_64
  linkmode: dynamic
  memFree: 13250543616
  memTotal: 16422182912
  ociRuntime:
    name: crun
    package: crun-0.19.1-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.19.1
      commit: 1535fedf0b83fb898d449f9680000f729ba719f5
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1002/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.9-1.fc34.x86_64
    version: |-
      slirp4netns version 1.1.8+dev
      commit: 6dc0186e020232ae1a6fcc1f7afbc3ea02fd3876
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 8588619776
  swapTotal: 8589930496
  uptime: 16h 25m 29.66s (Approximately 0.67 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /mnt/raider/home2/techlxoffice/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.5.0-1.fc34.x86_64
      Version: |-
        fusermount3 version: 3.10.2
        fuse-overlayfs: version 1.5
        FUSE library version 3.10.2
        using FUSE kernel interface version 7.31
  graphRoot: /mnt/raider/home2/techlxoffice/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 42
  runRoot: /run/user/1002/containers
  volumePath: /mnt/raider/home2/techlxoffice/.local/share/containers/storage/volumes
version:
  APIVersion: 3.1.2
  Built: 1620847679
  BuiltTime: Wed May 12 21:27:59 2021
  GitCommit: ""
  GoVersion: go1.16.3
  OsArch: linux/amd64
  Version: 3.1.2

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```

$ rpm -q -a | grep podman 
podman-plugins-3.1.2-3.fc34.x86_64
podman-3.1.2-3.fc34.x86_64
podman-compose-0.1.7-4.git20210129.fc34.noarch
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
This could be we ran out of space on /var/tmp?

**Comment by groovyman** [comment]
Salut 

for this reason i set `--tmpdir=${DATA_STORE}/podmanTMP`

**Comment by groovyman** [comment]
In order to cope suspected lack of disk space if moved the directory `/var/tmp` directory physically to a mounted raid device using a symbolic link. The new target directory shares the same selinux-attributes and has been _accepted_ by the os.

`
$ ls -lZ /mnt/raider/sys/vartmp
insgesamt 0
drwxr-xr-x. 2 abrt abrt system_u:object_r:abrt_var_cache_t:s0  6 17. Mai 14:18 abrt
drwx------. 3 root root system_u:object_r:mnt_t:s0            25 24. Mai 11:19 systemd-private-b718ab0a384c432ea3d383a3a7ef93aa-chronyd.service-p1tJk5
drwx------. 3 root root system_u:object_r:mnt_t:s0            25 24. Mai 11:26 systemd-private-b718ab0a384c432ea3d383a3a7ef93aa-cockpit.service-6ouI2H
drwx------. 3 root root system_u:object_r:mnt_t:s0            25 24. Mai 11:19 systemd-private-b718ab0a384c432ea3d383a3a7ef93aa-dbus-broker.service-Ow7Rs0
drwx------. 3 root root system_u:object_r:mnt_t:s0            25 24. Mai 11:19 systemd-private-b718ab0a384c432ea3d383a3a7ef93aa-ModemManager.service-ReD1FT
drwx------. 3 root root system_u:object_r:mnt_t:s0            25 24. Mai 11:19 systemd-private-b718ab0a384c432ea3d383a3a7ef93aa-systemd-logind.service-5vaYhT
drwx------. 3 root root system_u:object_r:mnt_t:s0            17 24. Mai 11:19 systemd-private-b718ab0a384c432ea3d383a3a7ef93aa-systemd-oomd.service-zvnvbO
drwx------. 3 root root system_u:object_r:mnt_t:s0            17 24. Mai 11:19 systemd-private-b718ab0a384c432ea3d383a3a7ef93aa-systemd-resolved.service-clPxyR
drwx------. 3 root root system_u:object_r:mnt_t:s0            17 24. Mai 11:26 systemd-private-b718ab0a384c432ea3d383a3a7ef93aa-systemd-timedated.service-DoHj2q
`
So i ran the podman build again an was running into the same problem again, it is not the `/var/run ` directory, that caused the problem!
`
Complete!
Error: error committing container for step {Env:[A_POSTGR_USR=tu_lxoffic A_POSTGR_PORT=5435 DISTTAG=f34container FGC=f34 container=oci EXT_LOGDIR=/var/log ADMIN_PWD=1geheim APACHE_LOGDIR=/var/log/httpd ....
error copying layers and metadata for container "e0b67293053a84200efa3f576b0938615e5a5bf324e393e322d4ea0b477899cc": Error initializing source containers-storage:aa366b9d629f0d6e76287c9df89929c0b1c0c7c867d55c3ad5fdf9d56fe1d637-working-container: error extracting layer "a99b1b6251d33cf91ebf0968a79398885b0cbff161908f7bf7ff053f7fd7d907": lgetxattr /mnt/raider/home2/techlxoffice/.local/share/containers/storage/overlay/a99b1b6251d33cf91ebf0968a79398885b0cbff161908f7bf7ff053f7fd7d907/merged/var/cache/dnf/fedora-cisco-openh264-ffa960505abcfb54/repodata/3d50825fb25440abc9579f078205d6ba3590b1d146187af8179eb43214c8b40e-comps-Temporary.x86_64.xml.gz: software caused connection abort
`

**Comment by rhatdan** [comment]
@groovyman Do you still have this issue.  The TMPDIR setting should be used to redirect where podman stores temporary images pulled from the internet --tmpdir is just for storing container runtime content, not image content.

**Comment by groovyman** [comment]
Salut Dan, (@rhatdan )

well as a workaround i exchanged the dockerfile from 
> FROM fedora
to
FROM fedora:33

and i got my image. Well, after a couple of updates, let's give him a change. ...

**Comment by groovyman** [comment]
Salut @rhatdan 

still got the blues with:
`LANG=C podman build --tag kivirel:V0_6_1t00_34 --tmpdir=${DATA_STORE}/podmanTMP -v ${DATA_STORE}/data:/var/lib/pgsql/data:z  -v ${DATA_STORE}/logs:/var/log:z -v ${DATA_STORE}/rteFiles:/www/kivitendoData:z --build-arg  A_POSTGR_USR=tu_lxoffic --build-arg POSTGR_PWD=lx1geheim --build-arg   A_POSTGR_PORT=5435  --cgroup-manager=cgroupfs .


Error: error committing container for step {Env:[A_POSTGR_USR=tu_lxoffic A_POSTGR_PORT=5435 DISTTAG=f34container FGC=f34 container=oci EXT_LOGDIR=/var/log ADMIN_PWD=1geheim APACHE_LOGDIR=/var/log/httpd POSTGR_USR=tu_lxoffic POSTGR_PWD=1geheim POSTGR_DB=postgres POSTGR_HOST=kividb POSTGR_PORT=5435 POSTGR_DATADIR=/var/lib/pgsql/data POSTGR_LOGDIR=/var/lib/pgsql/data/log POSTGR_KIVI_AUTH_USR=postgres POSTGR_KIVI_AUTH_PWD=1geheim POSTGR_KIVI_AUTH_DB=kivitendo_auth POSTGR_KIVITST_USR=grtst POSTGR_KIVITST_PWD=1geheim TERM=vt100 locale=de_DE postgrespassword=1geheim KIVITENDO_VER=release-3.5.6.1 KIVITENDO_DATA=/var/www/kivitendoData PG_HOSTNAME= PG_DATA= APACHE_LOG_DIR=/var/log/httpd PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:run Args:[dnf -y install  `[[ ${POSTGR_HOST} != '127.0.0.1' &&  ${POSTGR_HOST} != 'localhost' ]] || echo postgresql-server`  httpd mod_fcgid  postgresql-contrib  perl-Algorithm-CheckDigits perl-Archive-Zip perl-Archive-Extract-zip-Archive-Zip perl-CPAN perl-Class-XSAccessor   perl-Clone perl-Config-Std perl-DBD-Pg perl-DBI perl-Daemon-Generic   perl-DateTime perl-DateTime-Set perl-Email-Address perl-Email-MIME perl-FCGI   perl-File-Copy-Recursive perl-File-Flock perl-File-MimeInfo perl-File-Slurp   perl-GD perl-HTML-Restrict perl-JSON perl-List-MoreUtils perl-List-UtilsBy   perl-Net-SMTP-SSL perl-Net-SSLGlue perl-PBKDF2-Tiny perl-PDF-API2   perl-Params-Validate perl-Regexp-IPv6 perl-Rose-DB perl-Rose-DB-Object   perl-Rose-Object perl-Sort-Naturally perl-String-ShellQuote   perl-Template-Toolkit perl-Text-CSV_XS perl-Text-Iconv perl-URI perl-XML-Writer   perl-YAML perl-libwww-perl cpanminus   aqbanking poppler-utils    php-pecl-apcu php-cli php-pear php-pdo php-mysqlnd php-pgsql php-gd  php-xml php-zipstream   texlive-scheme-medium texlive-collection-latex texlive-collection-latexextra   texlive-collection-latexrecommended texlive-collection-langgerman   texlive-collection-langenglish  langpacks-de git procps-ng] Flags:[] Attrs:map[] Message:RUN dnf -y install  `[[ ${POSTGR_HOST} != '127.0.0.1' &&  ${POSTGR_HOST} != 'localhost' ]] || echo postgresql-server`  httpd mod_fcgid  postgresql-contrib  perl-Algorithm-CheckDigits perl-Archive-Zip perl-Archive-Extract-zip-Archive-Zip perl-CPAN perl-Class-XSAccessor   perl-Clone perl-Config-Std perl-DBD-Pg perl-DBI perl-Daemon-Generic   perl-DateTime perl-DateTime-Set perl-Email-Address perl-Email-MIME perl-FCGI   perl-File-Copy-Recursive perl-File-Flock perl-File-MimeInfo perl-File-Slurp   perl-GD perl-HTML-Restrict perl-JSON perl-List-MoreUtils perl-List-UtilsBy   perl-Net-SMTP-SSL perl-Net-SSLGlue perl-PBKDF2-Tiny perl-PDF-API2   perl-Params-Validate perl-Regexp-IPv6 perl-Rose-DB perl-Rose-DB-Object   perl-Rose-Object perl-Sort-Naturally perl-String-ShellQuote   perl-Template-Toolkit perl-Text-CSV_XS perl-Text-Iconv perl-URI perl-XML-Writer   perl-YAML perl-libwww-perl cpanminus   aqbanking poppler-utils    php-pecl-apcu php-cli php-pear php-pdo php-mysqlnd php-pgsql php-gd  php-xml php-zipstream   texlive-scheme-medium texlive-collection-latex texlive-collection-latexextra   texlive-collection-latexrecommended texlive-collection-langgerman   texlive-collection-langenglish  langpacks-de git procps-ng Original:RUN dnf -y install  `[[ ${POSTGR_HOST} != '127.0.0.1' &&  ${POSTGR_HOST} != 'localhost' ]] || echo postgresql-server`  httpd mod_fcgid  postgresql-contrib  perl-Algorithm-CheckDigits perl-Archive-Zip perl-Archive-Extract-zip-Archive-Zip perl-CPAN perl-Class-XSAccessor   perl-Clone perl-Config-Std perl-DBD-Pg perl-DBI perl-Daemon-Generic   perl-DateTime perl-DateTime-Set perl-Email-Address perl-Email-MIME perl-FCGI   perl-File-Copy-Recursive perl-File-Flock perl-File-MimeInfo perl-File-Slurp   perl-GD perl-HTML-Restrict perl-JSON perl-List-MoreUtils perl-List-UtilsBy   perl-Net-SMTP-SSL perl-Net-SSLGlue perl-PBKDF2-Tiny perl-PDF-API2   perl-Params-Validate perl-Regexp-IPv6 perl-Rose-DB perl-Rose-DB-Object   perl-Rose-Object perl-Sort-Naturally perl-String-ShellQuote   perl-Template-Toolkit perl-Text-CSV_XS perl-Text-Iconv perl-URI perl-XML-Writer   perl-YAML perl-libwww-perl cpanminus   aqbanking poppler-utils    php-pecl-apcu php-cli php-pear php-pdo php-mysqlnd php-pgsql php-gd  php-xml php-zipstream   texlive-scheme-medium texlive-collection-latex texlive-collection-latexextra   texlive-collection-latexrecommended texlive-collection-langgerman   texlive-collection-langenglish  langpacks-de git procps-ng}: error copying layers and metadata for container "e506295c6105c44bd8d88ca8cc884b95b50bf889aa177f430b453db039947d42": Error initializing source containers-storage:4ab65a50e8cd80e75ac6fa92111495e8803bb30b89170a70d480f9a94e9b009a-working-container-1: error extracting layer "e5b7dbd120dfcad611a37d8ff900f65029242ab5c6909a5ba92588fdac36abb1": lgetxattr /mnt/raider/home2/techlxoffice/.local/share/containers/storage/overlay/e5b7dbd120dfcad611a37d8ff900f65029242ab5c6909a5ba92588fdac36abb1/merged/var/cache/dnf/fedora-cisco-openh264-ffa960505abcfb54/repodata/3d50825fb25440abc9579f078205d6ba3590b1d146187af8179eb43214c8b40e-comps-Temporary.x86_64.xml.gz: software caused connection abort

`

**Comment by rhatdan** [comment]
`TMPDIR=${DATA_STORE}/podmanTMP/tmp` LANG=C podman build --tag kivirel:V0_6_1t00_34 --tmpdir=${DATA_STORE}/podmanTMP -v ${DATA_STORE}/data:/var/lib/pgsql/data:z -v ${DATA_STORE}/logs:/var/log:z -v ${DATA_STORE}/rteFiles:/www/kivitendoData:z --build-arg A_POSTGR_USR=tu_lxoffic --build-arg POSTGR_PWD=lx1geheim --build-arg A_POSTGR_PORT=5435 --cgroup-manager=cgroupfs .

**Comment by rhatdan** [comment]
I was suggesting something like this^^

**Comment by groovyman** [comment]
Salut Daniel,
i already tried  this, but with no success. Besides i also executed a export directive.
`
# first run
$ TMPDIR=${DATA_STORE}/podmanTMP/tmp LANG=C podman build --tag kivirel:V0_6_1t00_34 --tmpdir=${DATA_STORE}/podmanTMP -v ${DATA_STORE}/data:/var/lib/pgsql/data:z -v ${DATA_STORE}/logs:/var/log:z -v ${DATA_STORE}/rteFiles:/www/kivitendoData:z --build-arg A_POSTGR_USR=tu_lxoffic --build-arg POSTGR_PWD=lx1geheim --build-arg A_POSTGR_PORT=5435 --cgroup-manager=cgroupfs .

# next try
$ export TMPDIR=${DATA_STORE}/podmanTMP/tmp
$ export LANG=C
$  podman build --tag kivirel:V0_6_1t00_34 --tmpdir=${DATA_STORE}/podmanTMP -v ${DATA_STORE}/data:/var/lib/pgsql/data:z -v ${DATA_STORE}/logs:/var/log:z -v ${DATA_STORE}/rteFiles:/www/kivitendoData:z --build-arg A_POSTGR_USR=tu_lxoffic --build-arg POSTGR_PWD=lx1geheim --build-arg A_POSTGR_PORT=5435 --cgroup-manager=cgroupfs .
`
Both calls return a
`

ve-collection-langenglish  langpacks-de git procps-ng}: error copying layers and metadata for container "7afe323ffac880b8446a4206b895a2ef21f7baaa6da32052ee5e3531f5b5e856": Error initializing source containers-storage:4ab65a50e8cd80e75ac6fa92111495e8803bb30b89170a70d480f9a94e9b009a-working-container-1: error extracting layer "5eb3fb94ede9cecf1d3e624046e43ad6de63396e943b482108d758f100790fde": lgetxattr /mnt/raider/home2/techlxoffice/.local/share/containers/storage/overlay/5eb3fb94ede9cecf1d3e624046e43ad6de63396e943b482108d758f100790fde/merged/var/cache/dnf/fedora-cisco-openh264-ffa960505abcfb54/repodata/3d50825fb25440abc9579f078205d6ba3590b1d146187af8179eb43214c8b40e-comps-Temporary.x86_64.xml.gz: software caused connection abort
`
so i assume  that there must be a stubborn piece of code, that ignores  any indicatoion of an altered tmpdir argument. You may also have recognized, that my call used the --tmpdir argument.

Anyway, the session must have understood our tmpdir change, cause:
`
$ mktemp -u -d 
/mnt/raider/home2/techlxoffice/rteDataSpace/podmanTMP/tmp/tmp.f24QWT0NHZ
`

**Comment by rhatdan** [comment]
I did recently do some fixes for podman to handle TMPDIR 

I did a fix for handling of TMPDIR in podman here. 7864108ff191e2d78666fb5bdf098d295b7bae59
But I am not sure if that is the problem you are seeing.  Any chance you can check a newer podman 3.2.1 or later?

**Comment by groovyman** [comment]
Salut Daniel,
i am running a `podman-3.2.1-1.fc34.x86_64` on my testserver. Sad to say, that the problem is
still there. The given tmpdir is not beeing used and i did not recognized any problem on the
file endpoint. 
I think, that the new tmpfile-System is running out of space.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
can you please try with fuse-overlayfs 1.6?

**Comment by groovyman** [comment]
Where can i get it? I am using Fedora F34!

**Comment by giuseppe** [comment]
you can grab it here: https://bodhi.fedoraproject.org/updates/FEDORA-2021-2285144517

Since the issue is not related to Podman but to fuse-overlayfs, lets close it
