### ISSUE TITLE
Docs: Manifest add subcommand suggest only two usable transports

### ISSUE THREAD

**Issue by cevich** [containers/podman#10417]
/kind bug

**Description**

For the `manifest add` subcommand, the docs describe the `imageName` argument as

```
Transport
       Multiple transports are supported:

       docker:
       ...
       containers-storage:
```

My understanding is this is incorrect, all transports can be used.  

**Steps to reproduce the issue:**

1. man podman-manifest-add

**Describe the results you received:**

A list of two transports

**Describe the results you expected:**

A complete list of all transports, or pointer to a complete listing elsewhere.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is broken even worse in buildah, where the man page doesn't have any section specifying transports.

**Output of `podman version`:**

```
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.15.8
Built:        Thu Apr 22 09:21:33 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

***N/A***

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.1.2-1.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Web-version of this page is also broken: http://docs.podman.io/en/latest/markdown/podman-manifest-add.1.html#transport

**Comment by rhatdan** [comment]
@ashley-cui PTAL
