### ISSUE TITLE
Rootless Podman requires /etc/subuid to be sorted with multiple --uidmap

### ISSUE THREAD

**Issue by PhrozenByte** [containers/podman#10422]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm trying to run a rootless container with some rather complex UID/GID maps. I want to map …
* host uid 100000-165535 to container uid 0-65535,
* the executing user (user `test`, uid 1000) to container uid 65536, and
* host uid 975 to container uid 65537.

I looks like rootless Podman (or the kernel?) requires `/etc/subuid` and `/etc/subgid` resp. `/proc/self/uid_map` and `/proc/self/gid_map` to be sorted for complex UID/GID maps like the above. See "Additional information" below: By either running as root, or by simply changing order, `podman run` succeeds.

**Steps to reproduce the issue:**

1. Update `/etc/subuid` and `/etc/subgid` to include the necessary UID ranges:
    ```
    test:100000:65536
    test:975:1
    ```

2. Execute `podman run` with appropriate `--uidmap` and `--gidmap` options:
    ```
    $ podman run -dt --name "test" \
        --uidmap 0:1:65536 --uidmap 65536:0:1 --uidmap 65537:65537:1 \
        --gidmap 0:1:65536 --gidmap 65536:0:1 --gidmap 65537:65537:1 \
        docker.io/busybox
    ```

**Describe the results you received:**

`podman run` fails with the following error:

```
Error: writing file `/proc/3810/gid_map`: Operation not permitted: OCI permission denied
```

**Describe the results you expected:**

`podman run` succeeds.

**Additional information you deem important (e.g. issue happens only occasionally):**

There are two things to note:

1. If we run `podman run` as root (i.e. a rootful container), `podman run` succeeds. The UID/GID maps are applied just fine.

2. If we swap lines in `/etc/subuid` and `/etc/subgid`, and update the `--uidmap` and `--gidmap` options accordingly, `podman run` (rootless) suceeds:

    1. Update `/etc/subuid` and `/etc/subgid` to include the necessary UID ranges, just the other way round:
        ```
        test:975:1
        test:100000:65536
        ```

    2. Execute `podman run` with updated `--uidmap` and `--gidmap` options:
        ```
        $ podman run -dt --name "test" \
            --uidmap 0:2:65536 --uidmap 65536:0:1 --uidmap 65537:1:1 \
            --gidmap 0:2:65536 --gidmap 65536:0:1 --gidmap 65537:1:1 \
            docker.io/busybox
        ```

<details>
<summary><strong>Output of <code>podman version</code>:</strong></summary>

```
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.16.3
Git Commit:   51b8ddbc22cf5b10dd76dd9243924aa66ad7db39
Built:        Wed Apr 21 23:34:03 2021
OS/Arch:      linux/amd64
```
</details>

<details>
<summary><strong>Output of <code>podman info --debug</code>:</strong></summary>

```
host:
  arch: amd64
  buildahVersion: 1.20.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.0.28-1
    path: /usr/bin/conmon
    version: 'conmon version 2.0.28, commit: 6b18f7e0f2e4cd7f7b016b88141e82210d370008'
  cpus: 3
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: SGS-CPX21-Nuernberg-1
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.37-1-lts
  linkmode: dynamic
  memFree: 3686375424
  memTotal: 4019585024
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 0.19.1-1
    path: /usr/bin/crun
    version: |-
      crun version 0.19.1
      commit: 1535fedf0b83fb898d449f9680000f729ba719f5
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 14h 46m 3.63s (Approximately 0.58 days)
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 13
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.1.2
  Built: 1619040843
  BuiltTime: Wed Apr 21 23:34:03 2021
  GitCommit: 51b8ddbc22cf5b10dd76dd9243924aa66ad7db39
  GoVersion: go1.16.3
  OsArch: linux/amd64
  Version: 3.1.2
```
</details>

<details>
<summary><strong>Package info (e.g. output of <code>rpm -q podman</code> or <code>apt list podman</code>):</strong></summary>

Running `pacman -Qs podman`:

```
local/podman 3.1.2-1
    Tool and library for running OCI-based containers in pods
```
</details>

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Hetzner Cloud server. SELinux is disabled for now.

**Comment by rhatdan** [comment]
I am not sure what the issue is here?

**Comment by PhrozenByte** [comment]
```
$ podman run -dt --name "test" \
    --uidmap 0:1:65536 --uidmap 65536:0:1 --uidmap 65537:65537:1 \
    --gidmap 0:1:65536 --gidmap 65536:0:1 --gidmap 65537:65537:1 \
    docker.io/busybox
```

fails with

```
Error: writing file `/proc/3810/gid_map`: Operation not permitted: OCI permission denied
```

with `/etc/subuid`

```
test:100000:65536
test:975:1
```

even though it shouldn't.

I assume there's an error in Podman calculating the `uid_map` from `/etc/subuid` and `--uidmap` with these parameters. Since there are no requirements documented that `/etc/subuid` and `--uidmap` must be sorted, this is a bug.

**Comment by srbala** [comment]
@PhrozenByte having multiple rows for same user id in `subuid` or `subgid` is correct, you can have one line for one user.
> with `/etc/subuid`
```sh
test:100000:65536
test:975:1
```

Are you trying have three different user id entry in `subuid` or `subgid`? so you are passing multiple params `uidmap` and `gidmap`?

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by PhrozenByte** [comment]
> Are you trying have three different user id entry in `subuid` or `subgid`? so you are passing multiple params `uidmap` and `gidmap`?

Yes and no. As explained, I'm having two entries in `/etc/subuid` and `/etc/subgid`, but three `--uidmap` resp. `--gidmap` command-line options due to the implicit mapping of the executing user. `podman run` fails unless I sort my mappings in `/etc/subuid` and `/etc/subgid`. Since neither `subuid(5)` nor `podman-run(1)` note that `/etc/subuid` and `/etc/subgid` must be sorted, I assume this to be a bug.

**Comment by PhrozenByte** [comment]
ic, thank you! :heart:
