### ISSUE TITLE
GetRootlessRuntimeDir does not check for readonly FS

### ISSUE THREAD

**Issue by kurt-google** [containers/podman#10433]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

As noted in https://github.com/bazelbuild/rules_docker/issues/1663, when podman tries to figure out where to store its runtime files it ends up choosing /run/user/ID. But when running under bazel this directory may be readonly.

**Steps to reproduce the issue:**

1. Configure your system such that `which docker` resolves to podman. 

2. Attempt to build bazel rules that execute docker. One example BUILD file might be:

```
load("@io_bazel_rules_docker//docker/package_managers:apt_key.bzl", "add_apt_key")
add_apt_key(
    name = "some_apt_key",
    image = "@debian_buster_slim//image",
    keys = ["DEADBEEF.asc"],
)
```
via a command like `bazel build --sandbox_debug //some_apt_key`

3. Observe a failure by podman attempting to set the sticky bit in a readonly filesystem.

**Describe the results you received:**

Podman fails trying to use a readonly filesystem.

**Describe the results you expected:**

Podman succeeds by choosing a more appropriate filesystem. I suspect this can be resolved by modifying https://github.com/containers/podman/blob/54dce001cce131bbbdcf16512a4722e080561fc7/pkg/util/utils_supported.go#L28 to be more robust to readonly file systems and containerization. Perhaps attempting to create a folder as is done for os.Tempfile() (which should succeed in this case of running under `bazel`).

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 3.0.1
```

**Output of `podman info --debug`:**

```
Not sure how to extract this from the sandbox, if desired I will work on finding it.
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
3.0.1+dfsg1-2
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
Why would XDG_RUNTIME_DIR point to a Read/Only file system.  Isn't it your responsibility to launch the container with XDG_RUNTIME_DIR pointing at a writable directory.  If XDG_RUNTIME_DIR is not set, then Podman will attempt to write to files in /tmp, I believe.

**Comment by kurt-google** [comment]
XDG_RUNTIME_DIR is unset, sorry the link may be misleading. I mean the fallback code that checks /run/user/ID where it only checks permissions which in this case are succeeding even though the filesystem is read only.

**Comment by kurt-google** [comment]
Checking bazel it appears to just be a simple RO bind mount, you can see the effect (writable permissions, but ro filesystem) by running `mount --bind -o ro /some/writable/path /tmp/ro_vers`

**Comment by mheon** [comment]
While we can look into rewriting the code for choosing a temporary directory to be more robust, this strikes me as more of a problem with Bazel. Why is it remounting important system directories as read-only? We greatly prefer `/run/user` because it's actually guaranteed to be a tmpfs, unlike `/tmp`.

**Comment by kurt-google** [comment]
It looks like bazel will take all existing mounts and expose them in the sandbox as read only, /run/user/UID is only added because it was identified as an existing host mount. I could work around this by explicitly adding this directory as writable in the sandbox.

`bazel build --sandbox_writable_path=/run/user/${UID} ...` (I also had to add the container storage to sandbox writable as well)

There does seem to be some code to ensure `/tmp` prefixed paths are writable, so it may be correct to adjust bazel to also ensure `/var/user/${UID}` mounts are also writable, ill bring it up over there.

**Comment by rhatdan** [comment]
This looks like it is no longer an issue with Podman, So closing. Reopen if I am mistaken.
