### ISSUE TITLE
Gap: Rootless user's service can't start using generated unit due to dependency from the service socket

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/podman#10441]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The scenario:

- Portainer image is started by the rootless user
- systemd unit is generated to be used to start Pontainer every time when user logins
- Systemd-user attempts to start Pontainer upon login using generated unit but fails due to missed Podman end-point socket. After logout / login everything works but after reboot doesn't - podman system service for the Rootless user has not existed. There is no Root or rootless user systemd unit that starts Podman service by default or using --systemd option.

**Steps to reproduce the issue:**

1. Start Podman service as rootless user using Podman system service ...
2. Run image that shares Podman service socket, like Portainer
2. Generate systemd unit as rootless user
3. Copy the generated unit to $HOME/.config/systemd/user
4. Logout
5. Login - The Portainer is started by systemd-user
6. Reboot
7. Login as the same user that started Portainer and generated systemd unit
8. Check status using systemctl --user: status is degraded
9. Check Podman ps - no running containers
10. Check log using journalctl --user

2.

3.

**Describe the results you received:**
Container failed to start because service is not started and socket doesn't exist

**Describe the results you expected:**
Podman service is started by its own unit and Portainer starts due to fulfilled dependency from the Podman service. Podman system service must generate its own systemd unit by default.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
```
The systemd user instance is killed after the last session for the user is closed. The systemd user instance can be kept running ever after the user logs out by enabling lingering using

$ loginctl enable-linger <username>
```
https://github.com/containers/podman/blob/master/troubleshooting.md#17-rootless-containers-exit-once-the-user-session-exits

**Comment by rhatdan** [comment]
I believe this is your issue, reopen if I am mistaken.

**Comment by PavelSosin-320** [comment]
Second thought: can command podman system service exist in the systemd-based system? Why not simple systemctl enable podman.service It will work in any scenario, root and rootless. It also allows expressing dependency of Slave services providing GUI, proxy (nginx) , and monitoring from the Podman service. Nginx is important because without Websocket or grpc any good GUI is impossible. Nginx is needed to keep WS on the air.

**Comment by PavelSosin-320** [comment]
So, unit. Something like podman.service:
[Unit]
Description=Podman endpoint
[Service]
ExecStart=podman system service -t 0
[Install]
WantedBy=default.target

ToDo: how to stop Podman service if I don't want to leave open sockets and ports unattended?
