### ISSUE TITLE
No result for apt install/search podman on RaspPi 4B running 4 DietPi 64bit

### ISSUE THREAD

**Issue by buleherb** [containers/podman#10455]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Running DietPi 7.1.2 64bit on a Raspberry Pi 4B 4GB (arm64). Using 'apt search podman' or 'apt install podman' (after an 'apt search'), I can't find the package. I have flushed my firewall and have had no problem finding other packages before. 

My apt sources look like this:
deb https://deb.debian.org/debian/ buster main contrib non-free
deb https://deb.debian.org/debian/ buster-updates main contrib non-free
deb https://deb.debian.org/debian-security/ buster/updates main contrib non-free
deb https://deb.debian.org/debian/ buster-backports main contrib non-free
deb https://archive.raspberrypi.org/debian/ buster main

**Steps to reproduce the issue:**

1. Install & [DietPi 64bit Raspberry Pi image](https://dietpi.com/downloads/images/DietPi_RPi-ARMv8-Buster.7z) onto Raspberry Pi 4B

2. apt update && apt upgrade

3. apt search podman/apt install podman

**Describe the results you received:**
apt search podman: 
Sorting... Done
Full Text Search... Done

apt install podman: 
E: Unable to locate package podman

**Describe the results you expected:**
I expected apt to be able to find the podman package, to which I could then install onto my system.

**Additional information you deem important (e.g. issue happens only occasionally):**
I was going to try and install podman manually using [this guide](https://computingforgeeks.com/how-to-install-podman-on-debian/), although I wanted to first troubleshoot why I couldn't find the package in the first place.

**Output of `podman version`:**

```
N/A
```

**Output of `podman info --debug`:**

```
N/A
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
[DietPi 7.1.2 64bit](https://dietpi.com/downloads/images/DietPi_RPi-ARMv8-Buster.7z), Raspberry Pi 4B 4GB (arm64)

uname -a:
Linux hostname 5.10.17-v8+ #1414 SMP PREEMPT Fri Apr 30 13:23:25 BST 2021 aarch64 GNU/Linux

cat /etc/debian-version:
10.9

**Comment by giuseppe** [comment]
@lsm5 PTAL

**Comment by rechandler12** [comment]
As far as I know podman is available for Bullseye

**Comment by buleherb** [comment]
I'm not sure why podman isn't available on my system. I've included below the output of 'uname -a' and my Debian version, and have edited the post with this new info.

uname -a:
Linux hostname 5.10.17-v8+ #1414 SMP PREEMPT Fri Apr 30 13:23:25 BST 2021 aarch64 GNU/Linux

cat /etc/debian-version:
10.9

**Comment by rechandler12** [comment]
Look here:
https://packages.debian.org/bullseye/podman

You've got Buster:
deb https://deb.debian.org/debian/ buster main contrib non-free

and you need at least Bullseye

**Comment by buleherb** [comment]
I'm a bit lost here sorry, do I need to reinstall my OS to Bullseye in order to use podman?

**Comment by rechandler12** [comment]
You can upgrade your system to Bullseye or do what you want from beginning, install by this guide: https://computingforgeeks.com/how-to-install-podman-on-debian/

>  I was going to try and install podman manually using this guide, although I wanted to first troubleshoot why I couldn't find the package in the first place.

You have to install podman manually because there is no package

**Comment by buleherb** [comment]
That's grand thanks for that. Out of curiosity why is podman not available for Buster? Bullseye isn't yet stable?

**Comment by rhatdan** [comment]
No one from the community has packaged it.

**Comment by buleherb** [comment]
Ok. I'll build it with the article anyway, thanks very much. I was unsure as to whether it was compatible with my system or not based on the fact that it didn't seem available.
