### ISSUE TITLE
Please, add option to terminate Podman service and release sockets/ports using command

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/podman#10467]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

The Podman system service used by a rootless user creates Unix/TCP socket that can be left unattended while not used anymore until timeout expiration 
If the user uses generated units to start/stop his/her containers then the container that shares or uses Podman's socket (like Ponteiner) can be stopped but the Service left running and the socket unattended. There is no way to stop the service and release or delete socket or, maybe, undocumented. 
1. Run Ponteiner image
2. Generate unit file
3. Add unit file to the systemd/user folder
4. Logout, login,etc.  User Close Ponteiner, ...

**Describe the results you received:**
The Podman socket still exists and served although unattended

**Describe the results you expected:**
I would like to stop service and release the socket as a housekeeping measure and for security reasons. upon the "client" container's service has stopped.
**Additional information you deem important (e.g. issue happens only occasionally):**
This is scenario opposite to a long-running server, but useful also in the testing. In the test automation cleanup must not leave something running and sockets unattended.
**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Does `systemctl stop podman.service` not suffice here?

I don't think we can make a Podman command to do this. The socket isn't even managed by us in the typical, socket-activated case - it's being managed by systemd. More generally, we don't know what init system there is on the system, so we can't tell exactly how to shut down the service. We could just instruct any open `system service` instances to shut down, but then the init system would just restart them.

I'm going to close this one - this is a job for the init system, not Podman.
