### ISSUE TITLE
Outbound address is broken under rootless containers

### ISSUE THREAD

**Issue by Diniboy1123** [containers/podman#10463]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When creating a rootless container, if I set outbound_addr as described in the podman run docs, doesn't matter if I set an IP or an interface it doesn't seem to work and instead every direct IP curl request hangs forever within the container.

**Steps to reproduce the issue:**

1. Create a network interface with internet connectivity and an outbound IP. I have created a wireguard interface called `wg0`.

2. Start up a test container with the following flags: `--dns 1.1.1.1 --network slirp4netns:port_handler=slirp4netns,outbound_addr=wg0,enable_ipv6=false`. Such as `podman run -it --name test_container --dns 1.1.1.1 --network slirp4netns:port_handler=slirp4netns,outbound_addr=wg0,enable_ipv6=false alpine /bin/ash`

3. Try to install curl and send a request to a direct IP address, such as: `curl http://1.1.1.1`

**Describe the results you received:**

The terminal hangs until I manually interrupt. There doesn't seem to be networking within the container at all.

**Describe the results you expected:**

The internet works within the container and the above mentioned curl command doesn't hang.

**Additional information you deem important (e.g. issue happens only occasionally):**

Before submitting this issue I have confirmed that the interface works and outside of the container I can use it just fine:
```
[test@machine ~]$ curl --silent -q --interface wg0 http://1.1.1.1 -I | head -n1
HTTP/1.1 301 Moved Permanently
```

**Output of `podman version`:**

```
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.16.3
Built:        Wed May 12 22:27:59 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.20.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.27-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 32
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: machine
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.12.6-300.fc34.x86_64
  linkmode: dynamic
  memFree: 84504137728
  memTotal: 135050776576
  ociRuntime:
    name: crun
    package: crun-0.19.1-3.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.19.1
      commit: 1535fedf0b83fb898d449f9680000f729ba719f5
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.9-1.fc34.x86_64
    version: |-
      slirp4netns version 1.1.8+dev
      commit: 6dc0186e020232ae1a6fcc1f7afbc3ea02fd3876
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 1h 18m 22s (Approximately 0.04 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/test/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.5.0-1.fc34.x86_64
      Version: |-
        fusermount3 version: 3.10.3
        fuse-overlayfs: version 1.5
        FUSE library version 3.10.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/test/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 8
  runRoot: /run/user/1000/containers
  volumePath: /home/test/.local/share/containers/storage/volumes
version:
  APIVersion: 3.1.2
  Built: 1620847679
  BuiltTime: Wed May 12 22:27:59 2021
  GitCommit: ""
  GoVersion: go1.16.3
  OsArch: linux/amd64
  Version: 3.1.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.1.2-3.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

dedicated server

**Comment by giuseppe** [comment]
>     1. Create a network interface with internet connectivity and an outbound IP. I have created a wireguard interface called `wg0`.

is the wg0 created on the host?  The rootless container  cannot access devices from the host network namespace

**Comment by Diniboy1123** [comment]
It is, indeed. Why can it not access that? If I run curl for example from the same user on the host, it can just use the specific outbound IP/inteface.

But if that would be the case a warning would be helpful instead of silently failing.

**Comment by giuseppe** [comment]
sorry my last comment, I misunderstood the original post.

**Comment by giuseppe** [comment]
can you check what connection is performed?  What does `netstat -aenp | grep slirp4netns` show?

**Comment by Diniboy1123** [comment]
This is all I am seeing: ```
[test@machine ~]$ netstat -aenp | grep slirp4netns
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
udp        0      0 10.65.203.10:39189      0.0.0.0:*                           1000       82515613   711710/slirp4netns
udp        0      0 10.65.203.10:53886      0.0.0.0:*                           1000       82515603   711710/slirp4netns
unix  2      [ ACC ]     STREAM     LISTENING     82511542 711710/slirp4netns   /run/user/1000/libpod/tmp/199b4a78e6ec49163e5f2e8c83db15f665695e770d5439748c256d9c98179450.net
unix  2      [ ]         STREAM     CONNECTED     82511541 711710/slirp4netns
```

There is only one container running at the moment under this user

**Comment by Diniboy1123** [comment]
I did some further debugging and if I do `tcpdump -i wg0` there is absolutely nothing I can see. It looks like the packets are never even leaving the container.

**Comment by rhatdan** [comment]
@Luap99 @mheon PTAL

**Comment by Diniboy1123** [comment]
I will just close this and see if slirp4netns will ever fix the issue in the other ticket opened at them.
