### ISSUE TITLE
podman doesn't create volume host dir when it doesn't exist.

### ISSUE THREAD

**Issue by tmds** [containers/podman#10471]
With `docker`:

```
$ docker run -v /tmp/doesntexist:/root busybox
```

This runs. `/tmp/doesntexist` is created.

With `podman`:

```
$ podman run -v /tmp/doesntexist:/root busybox
Error: statfs /tmp/doesntexist: no such file or directory
```

**Comment by rhatdan** [comment]
Yes, and we consider this a Bug in Docker.  Since a simple typo can lead to a random directory being created on the host OS.  We have rejected this before and believe it is the wrong behaviour.

Closed won't fix.  BTW I was forced kicking and screaming to allow this for the Remote Compatible API.

**Comment by tmds** [comment]
@rhatdan is there a doc that describes these known differences?
