### ISSUE TITLE
Containers keep exiting randomly mid work

### ISSUE THREAD

**Issue by miladfarca** [containers/podman#10475]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Containers stop and exit randomly on their own even mid work and return to the host environment. 
```
root@cc94dee0e30c:/home# exit

[me@hostmachine ~]$ 
```

**Steps to reproduce the issue:**

1. Create a new container: `docker run -it ubuntu bash`

2. Container exits on its intermittently even mid work.

**Describe the results you received:**
Exit.

**Describe the results you expected:**
Container should not exit.

**Additional information you deem important (e.g. issue happens only occasionally):**
I have noticed this issue on x64 and PowerPC even when starting containers as root.

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2
Go Version:   go1.14.7
Built:        Mon Feb  8 16:19:06 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.20-2.module+el8.3.0+8221+97165c3f.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.20, commit: 77ce9fd1e61ea89bd6cdc621b07446dd9e80e5b6'
  cpus: 120
  distribution:
    distribution: '"rhel"'
    version: "8.3"
  eventLogger: journald
  hostname: host-machine
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 4.18.0-240.10.1.el8_3.x86_64
  linkmode: dynamic
  memFree: 815285096448
  memTotal: 1081677234176
  ociRuntime:
    name: runc
    package: runc-1.0.0-70.rc92.module+el8.3.1+9857+68fb1526.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-2.module+el8.3.0+8221+97165c3f.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 137438949376
  swapTotal: 137438949376
  uptime: 2064h 18m 37.43s (Approximately 86.00 days)
registries:
  search:
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 1
    stopped: 3
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-3.module+el8.3.0+8221+97165c3f.x86_64
      Version: |-
        fuse-overlayfs: version 1.3
        FUSE library version 3.4.1
        using FUSE kernel interface version 7.27
  graphRoot: /home/user/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 3
  runRoot: /run/user/1001/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: "2"
  Built: 1612819146
  BuiltTime: Mon Feb  8 16:19:06 2021
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.2.1-7.module+el8.3.1+9857+68fb1526.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Is there anything on the system that may be sending a signal to these containers? My guess would be a process on the host is shooting either the container process or Conmon with SIGINT or SIGTERM and they are exiting because of this.

**Comment by rhatdan** [comment]
`docker run -it ubuntu bash`?
I take it you have podman-docker installed?

**Comment by miladfarca** [comment]
@rhatdan Yes it is using podman behind the scenes.

@mheon possibly, but I'm not aware of such process. Has this never happened in the past? it's strange as i'm experiencing it on 2 separate machines.

**Comment by rhatdan** [comment]
Yes we have never heard of it.  After podman executes the containers are just processes on the system.  Podman/Conmon are just monitoring them.  If they die, either they are dying naturally or something like systemd or the kernel is shooting them in the head.

**Comment by vrothberg** [comment]
I am going to close the issue.  If the issue persists, please use the official Red Hat customer channels which will give your issue priority.
