### ISSUE TITLE
IPVLAN networks

### ISSUE THREAD

**Issue by ananthb** [containers/podman#10478]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

Support ipvlan CNI plugin? I'd like to contribute. Can I get pointers to the macvlan code?

**Comment by Luap99** [comment]
Contributions are always welcome @ananthb.
The network create code lives under the `libpod/network` package. This is the function used to create macvlan networks: https://github.com/containers/podman/blob/master/libpod/network/create.go#L251

**Comment by mheon** [comment]
If the question is whether we support using `ipvlan` networks, I think the answer is definitely yes - if you provide your own config, Podman will quite happily launch containers with it.

If the question is whether we can make the configs ourselves with `podman network create`, the answer to that is a no, but I don't see a specific reason why we couldn't start.

**Comment by ananthb** [comment]
@mheon yeah I noticed that cni has ipvlan support, so it should just work. I couldn't understand why `podman network create -d ipvlan ...` was failing with an "unsupported driver" error, but I get it now. I'd be happy to contribute the necessary code to make `podman network create` work with ipvlan.

**Comment by ananthb** [comment]
@mheon also can confirm IPVLAN works by simply editing the conflist file. Thanks for clearing that up.

**Comment by ananthb** [comment]
I've just started working on this. Besides IPVLAN are there other network drivers I can add support for as well @mheon @Luap99?

**Comment by ananthb** [comment]
This is being fixed here: https://github.com/containers/podman/pull/11232 so closing the issue

**Comment by Luap99** [comment]
This is not fixed in #11232 yet, I want to do a follow up PR once this is merged.

**Comment by ananthb** [comment]
Sure thing @Luap99
