### ISSUE TITLE
Losing Quay Session; Looks like an Error -> UX improvement suggestion

### ISSUE THREAD

**Issue by erikbgithub** [containers/podman#10482]
/kind feature

**Description**

During my DO180 training, I ran into the following error message.

![Error Screenshot](https://i.imgur.com/qcbEVcu.png)

**Steps to reproduce the issue:**

1. Start a DO180 Training VM (probably needs help from RH curriculum dev team)

2. Run the commands as described in above screenshot.

3. See the error message and how quickly it can go away.

**Describe the results you received:**

It reports the action is not permitted. But actually just the underlying session has timed out.

**Describe the results you expected:**

As I saw in the follow-up steps, that the login could proceed with a local session token and didn't need my manual user/pw input again, I think podman could under the hood capture this error and try a re-auth itself.

```
IF registry API response returns:
  - 401 unauthorized
  - 403 forbidden
  - 405 method not allowed
THEN:
 1. Do I (=podman) think that a a re-auth is possible without user input?
 2. IF possible:
   a. run re-auth
   b. repeat command
   c. IF failed again, with same error code: Report error
   d. IF failed again, with different error code: Report to user the original error, the attempted re-auth, and the new error
```

This way, I think the whole process would be less confusing for the user. And it could be even optimized. E.g. maybe a set of first-error + second-error would be convincing enough that we really need to re-auth WITH user input. Then we can just tell exactly that to the user.

**Additional information you deem important (e.g. issue happens only occasionally):**

Since podman works as intended, but the User Experience is a little lacking I propose this as a feature request and not a bug report.

**Output of `podman version`:**

```
Can't really paste from the web-ui for the training VM. Ergo, just hand-written:
version 1.6.4
```

**Output of `podman info --debug`:**

```
too much to copy by hand, let me know more specific questions.
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.4-10-module+el8.2.0+6063+e761893a.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No - Because:

 * I believe it works as currently intended, therefore this behavior is likely not different in another version.
 * I don't decide which version runs in a training Lab environment.
 * Happy to create a support ticket with training to provide a contact point, if desired.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

RedHat Training Lab environment.

**Comment by mheon** [comment]
That is a very old Podman in that training VM... RHEL 8.2.0 is similarly out of date.

I would strongly encourage you to try again with a more recent Podman (the newly-released 8.4.0 shipped with 3.0.1, and upstream is preparing for a 3.2.0 release). We have made a lot of fixes since then, and this could very well be one of them.

Regardless of the current state of the fix, it won't be making it back into 1.6.4 - that release is still supported, but only for critical bugfixes and security issues, and this doesn't qualify for either. So unfortunately, it won't be picked up by these training VMs until they update to something more recent.

**Comment by erikbgithub** [comment]
@mheon Thanks for checking the situation. If I understand you correctly, you can't do much about this issue due to the version difference between the training Labs and current version?

It's a shame tho, isn't it? This training is so well designed. Really makes people want to use more Podman. Quite a favor the training team is doing for this project. If there would be anything that could be done, that would be great, wouldn't it?

**Comment by rhatdan** [comment]
Sure, the question is how do we get the version of Podman in the training updated?

**Comment by rhatdan** [comment]
I sent an Email internal to Red Hat to see who I should contact to see about getting the version updated.  I am  going to assume that podman 3.* fixes this issue and close it.
