### ISSUE TITLE
Config priority and short-name-mode

### ISSUE THREAD

**Issue by matejvasek** [containers/podman#10492]
In Fedora 34 short-name-mode are in enforcing mode by default.
From the config `/etc/containers/registries.conf`:
```
# Enforcing mode for short names is default for Fedora 34 and newer
short-name-mode="enforcing"
```

This is really not good when using `podman` as a service as there is no interactive input.

So I tried to change it in `~/.cache/containers/short-name-aliases.conf`.

I am positive that the `podman` at least reads into `~/.cache/containers/short-name-aliases.conf`.
a) according `strace` the file was open
b) if I write invalid syntax into the file it will cause `podman` to fail dues to syntax error

Still it seems that option from `/etc/` takes precedence.

I find this unexpected.

How it should behave? Shouldn't user config take precedence?

Does it make sense use enforce for service mode?

**Comment by Luap99** [comment]
I think you need to set this in `~/.config/containers/registries.conf`. The `~/.cache/containers/short-name-aliases.conf` file is only used  to save the selections from the cli dropdown.

**Comment by matejvasek** [comment]
@Luap99  The `~/.config/containers/registries.conf` file seems to be not opened at all (according `strace -f`).

**Comment by matejvasek** [comment]
@Luap99 it works with `~/.config/containers/registries.conf`!

**Comment by matejvasek** [comment]
Another question: do we wan't to honour the setting even for Docker APIv2 endpoints? Because docker does allow short names.

**Comment by rhatdan** [comment]
That will be controlled, by how the server is setup.  If you want the server to ignore short names, then it should be configured that way.  Either to allow them or to block, since obviously the Client side can not be made to prompt.

Bottom line, I believe shortnames are a risk that should be handled if the administrator wants to block the risk.

**Comment by vrothberg** [comment]
Thanks for opening the issue, @matejvasek!

The `containers-registries.conf(5)` man page _should_ answer all of the questions.  In case information is missing, please let me know and I will open a PR to address it.

> Does it make sense use enforce for service mode?

I think that depends on the individual use case.  Short-name resolution can be an attack vector [1] that aliases close.  If users wish to preserve the old behavior, they can change the `registries.conf`.

I fully understand that this can come at a surprise when installing a fresh Fedora 34 but the consensus was to make "enforcing" the default mode.  Pretty much to follow the rule that security should not be opt-in but default.

Upgrading from previous versions to F34 will use the "permissive" mode.

[1] https://www.redhat.com/sysadmin/container-image-short-names

**Comment by matejvasek** [comment]
@vrothberg I see. Then at least we should improve the Docker APIv2 endpoint. Now it happily returns 200. It should return `Bad Request` or `Internal Server Error` instead.

**Comment by vrothberg** [comment]
> @vrothberg I see. Then at least we should improve the Docker APIv2 endpoint. Now it happily returns 200. It should return `Bad Request` or `Internal Server Error` instead.

Can you give a reproducer?  It should only return 200 if there's an alias.

**Comment by matejvasek** [comment]
The endpoint returns 200 in advance before it does anything (similarly to wait endpoint). Error is reported latter in body as status message. So the error is detectable by caller, still I would prefer fail via http status code.

**Comment by matejvasek** [comment]
```
curl -XPOST "http://localhost:1234/v1.38/images/create?fromImage=paketobuildpacks%2Frun&tag=full-cnb"
{"progressDetail":{},"error":"short-name resolution enforced but cannot prompt without a TTY\n"}
```

I encounter this while using `pack` (buildpacks CLI) which uses docker apiv2, so I even didn't see the error message. I just saw that subsequent call to the `/images/{name}/json` endpoint failed.

**Comment by matejvasek** [comment]
I could look into it.

**Comment by matejvasek** [comment]
Also the error message should link to the documentation better explaining what is happening.

**Comment by vrothberg** [comment]
Can you open a dedicated issue for that?  Feel free to tackle it :)
