### ISSUE TITLE
containers-mounts.conf.5.md in two repositories

### ISSUE THREAD

**Issue by Procyhon** [containers/podman#10512]
/kind bug

I noticed that the file containers-mounts.conf.5.md is located in two different repositories.

first repository: https://github.com/containers/common/blob/master/docs/containers-mounts.conf.5.md
second repository: https://github.com/containers/podman/blob/master/docs/source/markdown/containers-mounts.conf.5.md

Both files are identical. 

Is this desired or a mistake?

**Comment by vrothberg** [comment]
Thanks for reaching out.  The source of truth should be the one in containers/common since the corresponding code lives there.  I'll open a PR to delete the file from the Podman repo.

**Comment by vrothberg** [comment]
https://github.com/containers/podman/pull/10516
