### ISSUE TITLE
No access to /dev/ptmx

### ISSUE THREAD

**Issue by jpalus** [containers/podman#10530]
It's not so much of a bug report but more like support request. I can't really tell if anything's wrong and if it is then where (podman/crun/systemd/something else).

What I'm trying to achieve is to run rootless container with full systemd boot inside and normal, non-root user running ie tmux when logged in over ssh. The last part, tmux that is, does not work due to lack of access to `/dev/ptmx` it seems:
```
$ ls -l /dev/ptmx
lrwxrwxrwx 1 root root 8 06-02 09:47 /dev/ptmx -> pts/ptmx

$ ls -l /dev/pts/ptmx 
c--------- 1 root root 5, 2 06-02 09:50 /dev/pts/ptmx

$ mount | grep /dev/pts
devpts on /dev/pts type devpts (rw,relatime,gid=100004,mode=620,ptmxmode=000)
```
root can run tmux without issues, so does normal user if I force `666` mode on `/dev/pts/ptmx`. Any hints of how this could be fixed?

**Comment by rhatdan** [comment]
@giuseppe Any ideas?

**Comment by giuseppe** [comment]
how was the container created?

I see different results when running as rootless:

```
$ podman run --rm -ti fedora bash
# ls -l /dev/ptmx
lrwxrwxrwx. 1 root root 8 Jun  2 19:16 /dev/ptmx -> pts/ptmx
# ls -l /dev/pts/ptmx 
crw-rw-rw-. 1 root root 5, 2 Jun  2 19:16 /dev/pts/ptmx
# mount | grep /dev/pts
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,context="system_u:object_r:container_file_t:s0:c274,c868",gid=100004,mode=620,ptmxmode=666)
```

**Comment by jpalus** [comment]
@giuseppe Indeed it's the `--cap-add SYS_ADMIN` that breaks it. More or less container is created with:
```
podman create --volume /data:/data --publish 2222:22 --device /dev/fuse --cap-add SYS_ADMIN <image> /sbin/init
```
Where `/sbin/init` points to systemd. I suppose without `SYS_ADMIN` cap it works because systemd fails to remount `/dev/pts`:
```
systemd-remount-fs[24]: mount: /dev/pts: permission denied.
```
I would very much be glad to drop `SYS_ADMIN` if there is a nicer way for non-root user inside container to read/write files from/to volume with same permissions as host user other than `bindfs`.

Otherwise I suppose I should adjust `fstab` with additional permissions?

**Comment by giuseppe** [comment]
Is CAP_DAC_OVERRIDE enough for that?

**Comment by jpalus** [comment]
@giuseppe thanks, that's an interesting suggestion and I've tried to fit into my use case. Unfortunately some processes in hierarchy could have CAP_DAC_OVERRIDE while some must not. Even if it would be possible to control somehow, it would become too complex to manage. Also new files with CAP_DAC_OVERRIDE appear to be created with uid/gid of user inside container while it needs to be uid/gid of host user.

**Comment by giuseppe** [comment]
> Also new files with CAP_DAC_OVERRIDE appear to be created with uid/gid of user inside container while it needs to be uid/gid of host user.

that would happen also with CAP_SYS_ADMIN, no?

**Comment by jpalus** [comment]
CAP_SYS_ADMIN is used so that `bindfs` can perform mount, `bindfs` maps inside container uid/gid 0 <-> uid/gid of normal user, which in turn results in host uid/gid outside of container.

**Comment by giuseppe** [comment]
one trick you could use is to add CAP_SYS_ADMIN, perform the bindfs mount then drop CAP_SYS_ADMIN and start systemd.

Another hint, have you had a look at `--userns keep-id`?  Would that work for you?

**Comment by jpalus** [comment]
> have you had a look at --userns keep-id? Would that work for you?

Yes I'm aware of `keep-id`, but I really like the idea of isolating normal users in container (other than volume access of course :) ) so I prefer not to use it. If performance was more important than it is in my case -- bindfs seems to affect it considerably -- I'd probably go with this option. It would be super awesome if there was some magic solution that would be performant, maintained isolation, didn't require additional caps and was easy to set up.

> one trick you could use is to add CAP_SYS_ADMIN, perform the bindfs mount then drop CAP_SYS_ADMIN and start systemd.

Actually I was meaning to do that irrespective of this issue but was postponed to "later time" after container is up and running (part of it being working tmux). Now after reprioritization I'm happy to report that container is working exactly as intended! Thanks a lot for excellent support!
