### ISSUE TITLE
rootless podman 

### ISSUE THREAD

**Issue by Timoses** [containers/podman#10547]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Run any podman command as a specific user (rootless podman)

**Describe the results you received:**
Error: could not get runtime: error creating tmpdir /run/user/1586400222/libpod/tmp: mkdir /run/user/1586400222: permission denied

**Describe the results you expected:**
Proper podman output

**Additional information you deem important (e.g. issue happens only occasionally):**
The error occurs more often than not. Sometimes the error does not appear and podman correctly displays requested information (like `podman images` lists the available images). However, shortly after the error appears again.
When watching the directory `/run/user` (`watch ls -la /run/user`) it is observable that when podman works correctly, the directory mentioned in the error other times exists. When the error returns, the directory no longer exists.

**Output of `podman version`:**

```
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

Executing this as the broken user gives:
```
Error: could not get runtime: error creating tmpdir /run/user/1586400222/libpod/tmp: mkdir /run/user/1586400222: permission denied
```

Executing it as other user (also rootless):
```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.6.4
host:
  BuildahVersion: 1.11.5
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.8-1.el7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.8, commit: f85c8b1ce77b73bcd48b2d802396321217008762'
  Distribution:
    distribution: '"centos"'
    version: "7"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1586410091
      size: 1
    - container_id: 1
      host_id: 300000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1586410091
      size: 1
    - container_id: 1
      host_id: 300000
      size: 65536
  MemFree: 5816508416
  MemTotal: 8196476928
  OCIRuntime:
    name: runc
    package: runc-1.0.0-67.rc10.el7_8.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 2147479552
  SwapTotal: 2147479552
  arch: amd64
  cpus: 2
  eventlogger: file
  hostname: myhost.int
  kernel: 3.10.0-1160.11.1.el7.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.3-4.el7_8.x86_64
    Version: |-
      slirp4netns version 0.4.3
      commit: 2244b9b6461afeccad1678fac3d6e478c28b4ad6
  uptime: 1h 9m 25.51s (Approximately 0.04 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  ConfigFile: /home/ansible/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-6.el7_8.x86_64
      Version: |-
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.6.1
        using FUSE kernel interface version 7.29
  GraphRoot: /home/ansible/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /tmp/run-1586410091/containers
  VolumePath: /home/ansible/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.4-22.el7_9.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**
Yes. 
CentOS7 Extras Channel contains no newer podman version (e.g. on mirror http://centos.bio.lmu.de/7.9.2009/extras/x86_64/Packages/)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS7, Virtual Machine, 
rootless user exists via IPA/SSSD

**Comment by Timoses** [comment]
I've tried 
```
rm -rf .config/containers
rm -rf .local/share/containers
```

Shortly thereafter it worked, but then shortly after that again no longer with the same error again.

**Comment by rhatdan** [comment]
First it would be nice if you could use a more recent version of Podman then is available on RHEL7.  Any chance of upgrading to RHEL8.

This looks like you are having issues with how you login to this account.  And in certain situations the /run/user/UID is not accessible to you.

This directory is supposed to be created by systemd when you login, and often is not if you login as root and then `su` to user.  Could you try with `su -l` or to login via ssh or local console directly as the user, so that pam_systemd sets up the account properly.

**Comment by mheon** [comment]
Alternatively, you can `loginctl enable-linger` the user in question.

**Comment by srbala** [comment]
@Timoses Using `CentOS 8` will give you  `podman 3.1.x` with better support and enhncements. https://podman.io/getting-started/installation https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/

Please try this `podman system migrate` command. Not sure this one suported in older versioin of podman. this was expected when making changes to configs.

**Comment by srbala** [comment]
@Timoses if OS upgrade is not an option for you, still upgrade to podman 3.0.x using [OpenSuse dev repo](https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/devel:kubic:libcontainers:stable.repo) 

https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/x86_64/

**Comment by Timoses** [comment]
Thanks for the answers.

`loginctl enable-linger` does work (directory `/run/user/<user>` is kept).

I also found out why it worked sporadically. It seems periodically some cron jobs run for the user. This triggers existence of `/run/user/<user>` directory.


However I wonder: Why is this user affected by this limitation of requiring a directory under `/run/user` to work while another user isn't?
Another user is set up just the same which I can `sudo -u` into and run `podman images` and it just works. No directory for this user under `/run/user` exists.

Where's the catch?

**Comment by mheon** [comment]
Podman will always prefer `/run/user/$UID` if available. It's managed by the system, not us, and is considered the correct place to put per-user temporary files.

However, if it is not available, we will fall back to making our own directory in `/tmp`. This is less reliable for a variety of reasons (not the least of which `/tmp` is not guaranteed to be a tmpfs, which we require), but we can't guarantee every system is appropriately configured to make `/run/user`.

What you're see here is an unfortunate interaction of `sudo` / `su` and the `/run/user/$UID` directory (well, the entire login session, which includes said directory). `sudo` and `su` are not considered a valid login session for the user in question so they will not result in `/run/user/$UID` being mounted. If the first Podman command run as a user is done using `sudo` or `su` we will assume the system does not have support for `/run/user` and fall back to paths in `/tmp`. Generally speaking, we do not recommend running Podman as a non-root user via `sudo -u` and recommend using `su --login` to ensure a login session is created - it's not just the `/run/user/$UID` directory that's missing, but also a dbus session and various other things we expect to have.

**Comment by vrothberg** [comment]
I think we can close the issue after @mheon's excellent explanation.
