### ISSUE TITLE
Support specifying references with both a tag and a digest, as docker does

### ISSUE THREAD

**Issue by micah** [containers/podman#10551]
/kind feature

**Description**

Docker allows you to specify references with both a tag and a digest, but podman currently does not support this. It would be good to have that harmonization with docker.

**Steps to reproduce the issue:**

1. `podman pull debian:buster@sha256:acf7795dc91df17e10effee064bd229580a9c34213b4dba578d64768af5d8c51`

2. compare with docker pull of the same

**Describe the results you received:**

With podman:

```
"debian:buster@sha256:acf7795dc91df17e10effee064bd229580a9c34213b4dba578d64768af5d8c51": Docker references with both a tag and digest are currently not supported
```

**Describe the results you expected:**

This is what you get from docker-ce:

```
sha256:acf7795dc91df17e10effee064bd229580a9c34213b4dba578d64768af5d8c51: Pulling from library/debian
d960726af2be: Pull complete 
```

**Comment by mheon** [comment]
@vrothberg Didn't you just implement this?

**Comment by micah** [comment]
FWIW, I'm on 3.0.1-2 at the moment.

**Comment by mheon** [comment]
Don't expect this until 3.3.0 - we're in the process of releasing 3.2.0 right now. So probably late July-ish for this to land in upstream.

**Comment by rhatdan** [comment]
Well this is in the main branch now, so closing.

**Comment by vrothberg** [comment]
Yes, it's now supported in the main branch (didn't land in v3.2). Commit fb4a0c572ed1264ebb12218e8905c4845cb159c5 added support for it.
