### ISSUE TITLE
Podman v3.2.0 does not load internal seccomp profile any more

### ISSUE THREAD

**Issue by saschagrunert** [containers/podman#10556]
/kind bug

**Description**

Podman v3.1.2 did load the internal seccomp profile (struct) if the `seccomp.json` was not present on disk. This behavior has changed in v3.2.0.

**Steps to reproduce the issue:**

On a system where `/usr/share/containers/seccomp.json` is not available:
```
> podman run -it alpine:latest echo
Error: opening seccomp profile failed: open /usr/share/containers/seccomp.json: no such file or directory
```

**Describe the results you expected:**

With Podman v3.1.2:
```
> podman run --log-level=debug -it alpine:latest echo 2>&1 | rg "default seccomp"
time="2021-06-04T09:43:26+02:00" level=debug msg="Loading default seccomp profile"
```

**Additional information you deem important (e.g. issue happens only occasionally):**

`/etc/containers/containers.conf` has no seccomp profile specified.

**Output of `podman version`:**

```
Version:      3.2.0
API Version:  3.2.0
Go Version:   go1.16.4
Git Commit:   0281ef262dd0ffae28b5fa5e4bdf545f93c08dc7
Built:        Tue Jan  1 01:00:00 1980
OS/Arch:      linux/amd64
```

**Comment by Luap99** [comment]
bad commit 18cb17ffeb33195879730b2bc83e1a2c82310e6a
I think we have to leave the default seccomp path empty in c/common. https://github.com/containers/common/blob/86254d6d63e08f14a8c4d66a6ca40089bec8a01e/pkg/config/default.go#L201

**Comment by Luap99** [comment]
https://github.com/containers/common/pull/604 to fix

**Comment by mheon** [comment]
Any way we can test this in CI? I imagine the VMs probably have a `seccomp.json` because we're using the standard packaged configs on them - maybe we can remove it for one of the tests?

Regardless, this sounds like a good reason to spin up a quick 3.2.1 early next week.

**Comment by vrothberg** [comment]
Reopened as it's not yet in Podman.  Also need to create backports here and in c/common.

**Comment by srbala** [comment]
Using following temp work around until this issue being resolved.

```sh 
mkdir -p /usr/share/containers; \	
wget -O /usr/share/containers/seccomp.json https://src.fedoraproject.org/rpms/containers-common/raw/rawhide/f/seccomp.json ;
```
