### ISSUE TITLE
Podman does not support importing image from source with a platform specified

### ISSUE THREAD

**Issue by cdoern** [containers/podman#10566]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

While implementing the API endpoint for [/images/create](https://github.com/containers/podman/pull/10548) I noticed that CreateImageFromSrc within pkg/api/handlers/compat/images.go has some issues with supporting platform due to imageEngine.Import/the ImageImportOptions struct not supporting a platform parameter. Suggesting that we modify the ImageImportOptions struct as well as the abi image.go code to support handling the platform as [docker does ](https://github.com/docker/engine/blob/7c6a9484ee37b28fa314f716581bdb268cd78ce2/api/server/router/image/image_routes.go#L26). I can then go back and open up another PR with this fix as well as the API endpoint for supporting platform parsing.

I will most likely need to open up an Issue/PR on containers/common as well due to the fact that the import functions in podman/pkg/domain/infra/abi use libimage migration and end up calling the import function in that directory.

**Output of `podman version`:**

```
podman version 3.1.2
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Comment by cdoern** [comment]
I can take this issue myself if someone would like to assign.

**Comment by rhatdan** [comment]
@cdoern once you join the project you should be able to self assign.
