### ISSUE TITLE
Compat API: creating containers with `"NetworkMode": "default"` started failing with #10447 

### ISSUE THREAD

**Issue by riyad** [containers/podman#10569]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Trying to find regressions by exercising the Compat API trough [docker-py](https://github.com/docker/docker-py)'s test suite (see #5386) I came across a regression that reduced the number of passing tests by ~40 and affects another ~20 tests.

Creating containers with `"NetworkMode": "default"` started failing with #10447 (which is suspiciously network-related :raised_eyebrow: ).

**Steps to reproduce the issue:**

1.
```shell
curl -sS --unix-socket /var/run/user/1000/podman/podman.sock -XPOST 'http://localhost/v1.40/containers/create'  -H "Content-Type: application/tar" -d '{"Tty": false, "OpenStdin": false, "StdinOnce": false, "AttachStdin": false, "AttachStdout": false, "AttachStderr": false, "Cmd": ["sleep", "300"], "Image": "alpine", "NetworkDisabled": false, "HostConfig": {"NetworkMode": "default"}}' 
```

**Describe the results you received:**

Running the command above returns:
```json
500 Internal Server Error
{"cause":"network not found","message":"container create: unable to find network configuration for default: network not found","response":500}
```

**Describe the results you expected:**

Creating containers with `"NetworkMode": "default"` should work again. 

**Additional information you deem important (e.g. issue happens only occasionally):**

FWIW changing `"NetworkMode"` to `"podman"` (the only network listed with `podman network ls`) results in:
```
201 Created
{"Id":"240bd40f9f68344ad9f680f2a1ba5b3e29cc7fafb33a95453ca0b0cdf78ec23e","Warnings":[]}
```

**Comment by mheon** [comment]
Damn. I broke it, I'll take this one.

**Comment by mheon** [comment]
#10591 to fix
