### ISSUE TITLE
podman exec --tty resizes only after the process is started

### ISSUE THREAD

**Issue by Luap99** [containers/podman#10560]
/kind bug

**Description**

`podman exec -it` only resizes the terminal after the exec process is started. This issues exists in both local and remote podman.

**Steps to reproduce the issue:**

1. `podman run -dit --name test alpine top`

2. `podman exec -it test stty size`

**Describe the results you received:**
`stty: standard input`

**Describe the results you expected:**
two numbers, the real terminal size
`19 194`

**Comment by rhatdan** [comment]
@Luap99 do you plan on opening a PR for this?

**Comment by Luap99** [comment]
@rhatdan Yes
