### ISSUE TITLE
Cannot get to run on R-Pi4 with latest Raspberry Pi OS Lite image

### ISSUE THREAD

**Issue by dwhiteddsoft** [containers/podman#10576]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Running on Raspberry Pi OS Lite. Release date: May 7th 2021. Kernel version: 5.10.
After I build podman manually (there is no package I can find even in back ports), I cannot get a container to start

**Steps to reproduce the issue:**

1. Follow [this](https://www.osradar.com/how-to-install-podman-on-debian-on-10-9/) to build podman. One note, I do not install the Golang package where it say but build it manually as a higher version is needed now
2. Install slip4nets
3. podman pull hello-world

**Describe the results you received:**
Error: /usr/bin/slirp4netns failed: "/usr/bin/slirp4netns: unrecognized option '--netns-type=path'\nUsage: /usr/bin/slirp4netns [OPTION]... PID TAPNAME\nUser-mode networking for unprivileged network namespaces.\n\n-c, --configure      bring up the interface\n-e, --exit-fd=FD     specify the FD for terminating slirp4netns\n-r, --ready-fd=FD    specify the FD to write to when the network is configured\n-m, --mtu=MTU        specify MTU (default=1500, max=65521)\n-6, --enable-ipv6    enable IPv6 (experimental)\n-h, --help           show this help and exit\n-v, --version        show version and exit\n"

**Describe the results you expected:**
I would have expected the container to run

**Additional information you deem important (e.g. issue happens only occasionally):**
All the conf files needed are not created/installed in a manual build. I copied them over from a running Ubuntu 20.14 image

**Output of `podman version`:**

```
Version:      3.2.0-dev
API Version:  3.2.0-dev
Go Version:   go1.16.5
Git Commit:   1e006a58ccf62d9def0778af550c35f5acf504ae
Built:        Sun Jun  6 03:02:11 2021
OS/Arch:      linux/arm
```

**Output of `podman info --debug`:**

```
host:
  arch: arm
  buildahVersion: 1.21.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/local/libexec/podman/conmon
    version: 'conmon version 2.0.30-dev, commit: 24c73c2abb3f220ebd97acf498b57c560ca26c04'
  cpus: 4
  distribution:
    distribution: raspbian
    version: "10"
  eventLogger: journald
  hostname: raspberrypi
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.17-v7l+
  linkmode: dynamic
  memFree: 1891442688
  memTotal: 4013191168
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0~rc6+dfsg1
      commit: 1.0.0~rc6+dfsg1-3
      spec: 1.0.1
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 0.2.3
      commit: be6d34ba4c7ac62b9f31b0ea931ec91a5f16dc3b
  swapFree: 104853504
  swapTotal: 104853504
  uptime: 10h 32m 29.4s (Approximately 0.42 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  configFile: /home/pi/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 0
    stopped: 3
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/pi/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /home/pi/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.0-dev
  Built: 1622944931
  BuiltTime: Sun Jun  6 03:02:11 2021
  GitCommit: 1e006a58ccf62d9def0778af550c35f5acf504ae
  GoVersion: go1.16.5
  OsArch: linux/arm
  Version: 3.2.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on R-Pi 4 hardware

**Comment by mheon** [comment]
How did you install slirp4netns - from the system package? Have you tried building a more recent version from source?

**Comment by Luap99** [comment]
Yes this is definitely a to old slirp4netns version.
@dwhiteddsoft Podman will be included in debian bullseye, see https://packages.debian.org/source/testing/libpod
