### ISSUE TITLE
The command Podman system service creates 2 processes that are hard to die.

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/podman#10575]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Every execution of the command podman system service by a rootless user with default parameters results in the creation of 2 processes owned by the user but only one Linux Domain socket. The 1st process is zombi.
**Steps to reproduce the issue:**

1. Login as a rootless user
2. Execute podman system service -t 0 --> no output???? No pid file??????
2.  Execute ps and get 2 "podman" processes
3. Check Socket existence ls $XDG_RUNTIME_DIR/podman/ podman.sock ---> exists!
3. Kill the 1st process - nothing happens
4. Try another way:
 podman system service -t 0 &
[1] 16712
[pavel@MSI-wsl user]$ ps
    PID TTY          TIME CMD
  14055 pts/6    00:00:00 bash
  16712 pts/6    00:00:00 podman
  16722 pts/6    00:00:00 podman

5. kill 16722; The output is [1]+  Exit 1                  podman system service -t 0

**Describe the results you received:**
2 processes are created, one of them is zombi.

**Describe the results you expected:**
Only one "Leading" process is created and its PID is placed into XDG_RUNTIME_DIR/podman/podman.pid
To be used later for kill $(<%XDG_RUNTIE_DIR/podman/podman.pid
**Additional information you deem important (e.g. issue happens only occasionally):**
Pevent management podman service using systend,
**Output of `podman version`:**
podman version
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.15.11
Built:        Tue May 11 16:53:47 2021
OS/Arch:      linux/amd64

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
![image](https://user-images.githubusercontent.com/54495912/120926290-f2021d00-c6e4-11eb-9fcd-ed9e528048ec.png)

**Comment by mheon** [comment]
Replicates on Linux. It's not the pause process - I see that too, but there are also two `podman system service` processes and a zombie from the `podman system service` invocation.

**Comment by PavelSosin-320** [comment]
Starting Podman service using the following Unit
_[Unit]
Description=Podman API Service
#Requires=podman.service
#After=podman.socket
Documentation=man:podman-system-service(1)
StartLimitIntervalSec=0

[Service]
Type=simple
KillMode=process
Environment=LOGGING="--log-level=info"
ExecStart=/usr/bin/podman system service -t 0
ExecReload=/bin/kill -- $MAINPID
PIDFile=$XDG_RUNTIME_DIRECTORY/podman/podman.pid_

instead of direct Podman command execution makes Podman service behavior much more predictable and looks like solves the issue. The unit file has to be copied to all users' .config/systemd/user folders. Unfortunately, the PID file is not created yet.

**Comment by mheon** [comment]
@jwhonce @baude PTAL - we should try and fix the zombie bit, at least.

**Comment by jwhonce** [comment]
I assume the extra processes are coming from the restart for rootless setup/support.

**Comment by PavelSosin-320** [comment]
This is simply crazy! After full reboot of the system, I have the following situation:
(From the root session)
//
pstree pavel
systemd─┬─(sd-pam)
        ├─podman─┬─podman─┬─podman
        │        │        └─9*[{podman}]
        │        └─9*[{podman}]
        └─podman pause
// But no session exists
[root@MSI-wsl ~]# loginctl
SESSION UID USER SEAT TTY
     c1   0 root      pts/1

1 sessions listed.
[root@MSI-wsl ~]#
// Podman process is alive with 8? threads and in the "Waiting for interruption" status.
ps -aux | grep Ssl
root         101  0.0  0.2 258256 17452 ?        Ssl  07:28   0:00 /usr/sbin/NetworkManager --no-daemon
**pavel        236  0.0  0.7 1420700 60812 ?       Ssl  07:28   0:00 /usr/bin/podman system service -t 0**
How it can happen in the systemd driven system?

**Comment by PavelSosin-320** [comment]
Completed! Socket activation is even running! Except extra proc:
systemctl --user status podman
● podman.service - Podman API Service
     Loaded: loaded (/home/pavel/.config/systemd/user/podman.service; static)
     Active: active (running) since Wed 2021-06-09 09:49:09 IDT; 3h 5min ago
       Docs: man:podman-system-service(1)
   Main PID: 614 (podman)
     CGroup: /user.slice/user-1000.slice/user@1000.service/podman.service
             ├─614 /usr/bin/podman system service -t 0
             ├─624 /usr/bin/podman system service -t 0
             └─628 /usr/bin/podman

pstree -p -T pavel
bash(431)───pstree(782)

systemd(124)─┬─(sd-pam)(131)
             ├─dbus-broker-lau(280)───dbus-broker(281)
             ├─podman(614)───podman(624)───podman(627)
             └─podman pause(628)

**Comment by rhatdan** [comment]
Podman always kicks off another podman on first execution to hold open the user namespace.
This Podman continues to run until the user logs out, or you execute `podman system migrate`

http://docs.podman.io/en/latest/markdown/podman-system-migrate.1.html

**Comment by rhatdan** [comment]
@mheon didn't you write a blog on this somewhere?

**Comment by PavelSosin-320** [comment]
@mheon So, this process must disappear after logout, poweroff together with the user's session. But it doesn't happen - see above. This is the same problem: no PID file means no clean-up is possible.

**Comment by PavelSosin-320** [comment]
P.S. Maybe the correct way to create and manage Podman service CGroups and slice is the Podman-user.slice >
Only 4 lines of Podman-user slice unit
cat podman-user.slice
[Unit]
Description=Podman ServerResource Limits
Slice]
Created me 
$ systemctl --user start podman-user.slice
[pavel@MSI-wsl-wsl user]$ systemctl --user status podman-user.slice
● podman-user.slice - Podman ServerResource Limits
     Loaded: loaded (/home/pavel/.config/systemd/user/podman-user.slice; static)
     Active: active since Thu 2021-06-10 14:42:16 IDT; 9s ago
     CGroup: /user.slice/user-1000.slice/user@1000.service/podman.slice/podman-user.slice

Jun 10 14:42:16 MSI-wsl-wsl systemd[175]: Created slice Podman ServerResource Limits.

Without spawning a zombie processes.

**Comment by PavelSosin-320** [comment]
If Podman service is a Linux service which kind of service it is, simple or forking or oneshot? What is the head process of Podman service?
On one hand, Podman requires systemd t run but on another hand is incompatible with systemd.

**Comment by mheon** [comment]
I believe we're `Type=notify` in the upstream unit files. Definitely not `Type=forking`.

**Comment by PavelSosin-320** [comment]
@mheon I tried but it doesn't work due to the original problem - zombie process:
Jun 24 11:50:47 MSI-wsl systemd[127]: Starting PodmanAPI Service for dogs...
Jun 24 11:50:47 MSI-wsl systemd[127]: podman.service: Got notification message from PID 18421, but reception only permitted for main PID 18411
[pavel@MSI-wsl user]$ pidof podman
18421 18411

Maybe, if the only duty of the 2nd process is the creation of Cgroup under User's slice the Service Unit of the type "slice" is more reliable? See above. It creates:
 server. slice - Podman ServerResource Limits
     Loaded: loaded (/home/pavel/.config/systemd/user/server.slice; static)
     Active: active since Thu 2021-06-24 12:14:10 IDT; 4s ago
     **CGroup: /user.slice/user-1000.slice/user@1000.service/server.slice** for the User's Podman service

**Comment by PavelSosin-320** [comment]
@mheon I tried systemd-run podman system service -t 0 and it gives me some improvement: it creates CG under rootless user service CG : run-r795fc18f8c5a494ba5f86417fb3a7a16.service and yet 2 podman server processes under this CG. But, at least, when I stopped this unit using systemctl --user stop run-r795fc18f8c5a494ba5f86417fb3a7a16.service both processes disappeared without  leaving zombie. Does it satisfy podman server?

**Comment by mheon** [comment]
That seems like the desired behavior, yes. Would still like to know why we're leaving a zombie in the non-systemd case, but for the typical systemd-managed case things work as expected.

**Comment by PavelSosin-320** [comment]
@mheon I think the answer to your question is  [here](https://stackoverflow.com/questions/40898077/systemd-systemctl-stop-aggressively-kills-subprocesses). The systemd kills service's processes aggressively as expected from smart resource manager to fast pressure relief and port release. On another hand, grace time can be given to kill all containers and wait for the exit. It also ensures that the Unix or TCP socket is not served after the stop.

**Comment by PavelSosin-320** [comment]
@vrothberg I checked the CG structure created by systemd-run and didn't see something unexpected - see picture.
![PodmanServiceAsSystemdTransientService](https://user-images.githubusercontent.com/54495912/126956221-2c1f5da7-9c60-46e0-a47b-b4fd06f6f394.png) The only special thing is that systemd-cgls sees only one process, i.e. the second service process is born as zombie. Both Linux and TCP socket listening localhost or all interfaces ( WSL case) are served. The Transient  unit's CG is not something artificial : ls sees it. I have no practical knowledge in systemd in the user mode but I don't see something abnormal in /user/slice/ ... - It looks like systemd is very reliable in the CG v2 management.
When I stopped the unit using systemctl --user stop all processes undernit unit's GC disappeared as promised. 
I did only manual testing so, I can't ensure that this solution is comprehensive. Can systemd.io assist in the case of issue detection?

**Comment by PavelSosin-320** [comment]
The 1st easily picked benefit of using systemd-run is easy customization of configuration: systemd-run --user **--setenv CONTAINERS_CONF=$HOME/.config/containers/containers.conf**  allows to play with configuration every server run without "Administrator can change..."

**Comment by PavelSosin-320** [comment]
@giuseppe To avoid zombie process creation when running Podman service by the rootless user I run Podman service using systemd-run --user. Systemd-run creates the CG for the transient unit and assigns all created Podman processes to this CG. Then systemctl --user stop or kill accurately kills all processes and removes CGs. The issue is that systemd-run puts everything into a unified hierarchy because it is the systemd default.   Could it cause any problems from your point of view? I suppose that when containers are started using generated units it's expected to have the same issue - the unit's CG will be created in the unified hierarchy. Related to #https://github.com/containers/podman/issues/9259.

**Comment by giuseppe** [comment]
opened a PR: https://github.com/containers/podman/pull/11073
