### ISSUE TITLE
default log driver: switch to journald

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#10587]
A reminder to switch the default log driver from k8s-file to journald. It passed CI a couple of weeks ago but we were to close to the v3.2 release and wanted to play it safe.  With RHEL 9 being in a not so distant future anymore, we should give the journald logger some time cooking in CI, Rawhide, and Fedora.

Cc: @rhatdan

**Comment by rhatdan** [comment]
Yes I think we should make it default for rootful and test it for rootless, have it default unless rootless can's work with it.

**Comment by tobwen** [comment]
Just small info: On _Debian_ _Buster_ and _Stretch_, I can write to _journald_ as a user. In my eyes, that's a kind of security risk, since a user easily could make the bad designed binary log explode... but that's offtopic.

**Comment by vrothberg** [comment]
@tobwen, can you elaborate on that?  How can the journal logs explode?  Doesn't it rotate?

Note that the k8s-file log driver does not implement any rotation.

**Comment by tobwen** [comment]
@vrothberg 
> can you elaborate on that? How can the journal logs explode? Doesn't it rotate?

I mean, a malicious user just could run `< /dev/random logger` and some minutes later, a server could be locked up (if the logs are on the same partition as root).

Also please think about this: https://github.com/containers/podman/issues/10624 - sure, it's not a _podman_ problem, but might be an issue... once the data is logged in _journald_ you can't get it out without removing the whole log. Or some acrobatic import/export hacks.

**Comment by tobwen** [comment]
I just tried it and after 25 minutes:

``` shell
Filesystem      Size  Used Avail Use% Mounted on
udev            3.9G     0  3.9G   0% /dev
tmpfs           796M   81M  716M  11% /run
/dev/sda1        31G   31G     0 100% /
tmpfs           3.9G  100K  3.9G   1% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           796M  116K  796M   1% /run/user/1000
tmpfs           796M     0  796M   0% /run/user/0
```

**Comment by vrothberg** [comment]
> I mean, a malicious user just could run < /dev/random logger and some minutes later, a server could be locked up (if the logs are on the same partition as root).

Couldn't a malicious user do that pretty much everywhere on the system?  I am not saying it's not a problem but I question whether it's tied to journald.  To the best of my knowledge, journald does a decent job at log rotation to prevent the disk from running full.

**Comment by Luap99** [comment]
> To the best of my knowledge, journald does a decent job at log rotation to prevent the disk from running full.

Yes and in fact journald is much better than the current default k8s-file which has by default no limit set.

**Comment by tobwen** [comment]
I'm not completely against _journald_, but it really has some design problems or non-implemented features, like the missing handling of broken journals (and not even complain about it...). But after all: sure, it's all up to the user and his configuration. 

Sorry for the noise :-)

**Comment by vrothberg** [comment]
> Sorry for the noise :-)

No worries, we appreciate the feedback a lot!

I think that the journald logger is a major improvement over the k8s-file logger.  As @Luap99 mentioned, the file logger does not implement any rotation which can cause issues.  Our goal is to use as much existing infrastructure as possible, and offloading such things to systemd/journald make our life much easier and Podman more robust.

**Comment by rhatdan** [comment]
PR still has not merged, because of one error failure.  And I have no idea why.

**Comment by vrothberg** [comment]
Closed by https://github.com/containers/podman/pull/11263
