### ISSUE TITLE
podman 3.2 fails to build from source (FTBFS) on all architectures that are not amd64, arm64

### ISSUE THREAD

**Issue by siretart** [containers/podman#10625]
/kind bug

Please consider the buildlogs at https://buildd.debian.org/status/package.php?p=libpod&suite=experimental

Right now, amd64 and arm64 are the only architectures that podman can build on. On all other architectures, the build fails with:

```
# github.com/containers/podman/pkg/machine
src/github.com/containers/podman/pkg/machine/fcos.go:26:15: undefined: getFCOSDownload
```

The reason is that the function getFCOSDownload is implemented only for these two archs at:
- https://github.com/containers/podman/blob/master/pkg/machine/fcos_amd64.go
- https://github.com/containers/podman/blob/master/pkg/machine/fcos_arm64.go

Please provide either a buildflag to disable this library/functionality or a generic implementation that allows compilation on other architectures.

**Comment by mheon** [comment]
We'll need a fix for this landed before we release 3.2.1 tomorrow. @baude is on PTO, so I guess I'll take a look (unless @ashley-cui has time?)

**Comment by Luap99** [comment]
This compiles just fine. The package `pkg/machine` is never called on non supported architectures so it should not be pulled in.

I can see in the linked build logs that go install is called for every single package in the repository and thus `go install pkg/machine` is failing. I do not know why this is done but I guess we should add the same buildtags from cmd/podman to this package.

**Comment by siretart** [comment]
thank you for the very quick turnaround!

@Luap99 -- I didn't invent the golang debhelper that drives the compilation of golang applications in Debian package builds. I guess this, let's call it "interesting" design decision, was made to allow to "unvendor" sources easily. The debian package build would first identify all sources, copy them to a temporary directory, create symlink farms to `/usr/share/gocode/src/...` and then start with `go build`, `go install`, etc.. As a package maintainer, I do have influence over the targets that it builds, in fact, I had to exclude a number of targets that don't need to be built (cf. https://salsa.debian.org/debian/libpod/-/blob/d99bceebd6aca473dca9b5537b9c1018894aa4c2/debian/rules#L16). I could add `pkg/machine` to that list on `!arm64`, `!amd64`, but your suggestion with the build tags seems much much cleaner to me. So thanks again!
