### ISSUE TITLE
[journald] possible GDPR issues

### ISSUE THREAD

**Issue by tobwen** [containers/podman#10624]
I've read about your plans to make _journald_ the default logging target of _podman_. Since some containers dump to _stdout_ and _stderr_, even data protected by laws of data protection and privacy might get logged. So there might be some issues according to the _EU-General Data Protection Regulation_ (_EU-GDPR_), some administrators might not be aware of.

1. _journald_ - right now, `systemd 247 (247.3-5)` - doesn't provide a way to granularly remove logs based on _journald_ variable, e.g. `CONTAINER_NAME=nginx`. You only can remove *all* your logs:
```
journalctl CONTAINER_NAME=nginx --vacuum-time 2weeks 
Extraneous arguments starting with 'CONTAINER_NAME=nginx'
```
2. When the binary file of _journald_ gets corrupted, there's currently no tool or function to access logs or single entries. The privacy data will still be stored in the corrupted log file and it can't be removed, without removing the whole logs.
3. [to be continued]

Some rulings even treat IPs as personal data. These must be removed after a certain period of time. In many cases, the user even has a right to have his data deleted. _journald_ allows these records to be fished out of the logs, but not to be removed granularly.

**Comment by vrothberg** [comment]
Thanks for opening the issue, @tobwen.

It's an interesting topic.  I wonder whether there's a difference to other data a user may leave on the machine, for instance, data written to volumes.  It sounds like a general problem to me which is not limited to journald.

> journald allows these records to be fished out of the logs, but not to be removed granularly.

Yes, that would be a better user experience with `journalctl`.

How about adding a section to the man pages that explains how logs can be removed from the journal?

**Comment by tobwen** [comment]
> How about adding a section to the man pages that explains how logs can be removed from the journal?

I don't think _journald_ was designed to edit existing journals. I think the seal doesn't allow this kind of modification. A trick is to export, modify and rewrite the log, which also needs external scripting.

Since the new default is going to "silently" log to _journald_, it should be aware to the user, that privacy data my be stored in there and can not be removed easily.

**Comment by vrothberg** [comment]
journalctl allows for deleting all logs based on time (e.g., --vacuum-time=1h).  I think that may be helpful information in the man pages.

**Comment by tobwen** [comment]
Yes, but I don't want to delete all my logs. Just specific logs, e.g. for container "nginx" or for IP "x.x.x.x.".

On my system, _journald_ just acts as a buffer and _rsyslog_ with post-processing does the real job.

**Comment by tobwen** [comment]
No podman issue. Closing.
