### ISSUE TITLE
Identifier is not an image error when trying to remove image

### ISSUE THREAD

**Issue by crcox** [containers/podman#10647]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

My system root resides on a fairly small hard drive, and container images were occupying an uncomfortable amount of that space. Furthermore, my goal was to install images in a shared location that multiple non-root users (without sudo rights) could use.

After resetting podman and clearing everything out, I created a directory on my data filesystem and bound it to `/var/lib/containers`. That seemed to address the storage issues when I manipulated images as root that I did not intend to share.

```
# mount --bind /data/containers /var/lib/containers
```

I then added a shared location to `additionalimagestores` in `/etc/containers/storage.conf`, and started to install images I wanted to share:

```
# podman --root /data/shared/.local/containers/ pull some/image
```

This was all done with podman 2. I don't remember the minor release numbers. I just upgraded to podman 3, and am trying to uninstall those shared images.

Podman sees them:

```
# podman images
REPOSITORY                  TAG     IMAGE ID      CREATED       SIZE     R/O
docker.io/bids/validator    latest  5801eacbb38f  3 months ago  347 MB   true
docker.io/nipy/heudiconv    latest  afdef7270c0e  5 months ago  1.25 GB  true
docker.io/nipreps/fmriprep  20.2.1  d7235efbbd3c  7 months ago  13.6 GB  true
```

But if I try to remove them:

```
# podman --root /data/shared/.local/containers/ rmi --all
Error: lock "/data/shared/.local/containers/overlay-images/images.lock" is not a read-only lock
```

```
# podman system reset

WARNING! This will remove:
        - all containers
        - all pods
        - all images
        - all build cache
Are you sure you want to continue? [y/N] y
ERRO[0002] Error removing image d7235efbbd3c1af98e45b0c61e3b91c741feeaceeb0dd096b10c42c3a1726203: identifier is not an image
ERRO[0002] Error removing image afdef7270c0ebb3146a4eaa483d7d04ca313233b33d1502fb5bd9b2e600f87ed: identifier is not an image
ERRO[0002] Error removing image 5801eacbb38f54dfcf4b2e9bfda207801f3f5f01d32b65f06c11a4ec8477d453: identifier is not an image
A storage.conf file exists at /etc/containers/storage.conf
You should remove this file if you did not modified the configuration.
```

My guess is that I accidentally screwed something up, and this isn't inherently a problem with my upgrade to Podman 3. But I am not sure how to get things back on track. I am totally comfortable with a complete uninstall and reinstall of Podman, including complete removal of all images and containers, if I have guidance on a safe/thorough way to do that.

My desired outcome is to remove the images.

**Output of `podman version`:**

```
Version:      3.0.2-dev
API Version:  3.0.0
Go Version:   go1.15.13
Built:        Tue Jun  8 02:52:06 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.8
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.26-3.module+el8.4.0+11311+9da8acfb.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: a35bb9ea67d5a83c7da53202f2fcd505c036d29c'
  cpus: 32
  distribution:
    distribution: '"rhel"'
    version: "8.4"
  eventLogger: file
  hostname: relearn0.lsu.edu
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-80.el8.x86_64
  linkmode: dynamic
  memFree: 109238800384
  memTotal: 134525079552
  ociRuntime:
    name: runc
    package: runc-1.0.0-73.rc93.module+el8.4.0+11311+9da8acfb.x86_64
    path: /usr/bin/runc
    version: |-
      runc version spec: 1.0.2-dev
      go: go1.15.13
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 3198676992
  swapTotal: 4294963200
  uptime: 17184h 57m 26.39s (Approximately 716.00 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /data/shared/.local/containers
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 3
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1623138726
  BuiltTime: Tue Jun  8 02:52:06 2021
  GitCommit: ""
  GoVersion: go1.15.13
  OsArch: linux/amd64
  Version: 3.0.2-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman.x86_64    3.0.1-7.module+el8.4.0+11311+9da8acfb    @rhel-8-for-x86_64-appstream-rpms
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is running on a physical server that I own.

**Comment by rhatdan** [comment]
I believe this is something we fixed in later Podman.  Could you try off of the main branch and verify,  reopen if I am mistaken.

**Comment by crcox** [comment]
Would this involve building Podman from source? I am running RHEL8 and would prefer to keep my Podman version in sync with the official repositories. Is there a work around?
