### ISSUE TITLE
Incorrect documentation examples for podman-image-diff

### ISSUE THREAD

**Issue by infiniteregrets** [containers/podman#10649]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
In the documentation at http://docs.podman.io/en/latest/markdown/podman-image-diff.1.html
this example: `podman diff --format json redis:old redis:alpine` is used. But this does not work with the current version of podman. 

```
:/$ podman image diff alpine:latest alpine:3
:/$ Error: accepts 1 arg(s), received 2 
```
```
:/$ podman diff alpine:latest alpine:3
:/$ Error: `podman diff` accepts at most one argument 
```
I think when a single image is mentioned the diff should be done between the image and its parent layer and when two are mentioned the diff should be between them. 

The JSON output when `--format=json` flag is used is not indented and `JSON` is not accepted as a valid option, which in my opinion should be. This would just be a minor fix in the regular expression here: https://github.com/containers/podman/blob/0c38ac44efcaa83f98c727408fbba78456f9edd8/vendor/github.com/containers/common/pkg/report/validate.go#L5

**Output of `podman version`:**

```
podman version 3.1.2
```

Please provide correct documentation examples, and if there are any potential bug fixes then let me know! I would love to try working on them

**Comment by rhatdan** [comment]
Please open a PR to fix the documentation, and if you want to add the feature to compare two images, then go for it.

**Comment by infiniteregrets** [comment]
I have already opened #10536 and it's in progress. In the meantime, i'll try working on this
