### ISSUE TITLE
[Docs Enhancement]: unclear what the package `podman-docker` is

### ISSUE THREAD

**Issue by josh-hemphill** [containers/podman#10645]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Current directions for compatibility with docker-compose lists needing to install `podman-docker`, but there doesn't seem to be any mention of it itself in documentation and the listings in the package repose (e.g. arch repo search), just link back to this repo.

If it's all in flux right now, perhaps just mentioning it here someplace searchable would still be helpful.

Is there any plan to create a debian package for it? Or create directions for setting up on debian without it?

**Comment by raveinid** [comment]
A Debian package would be beneficial. Documentation and download links would be useful. I've been searching for podman-docker after watching The Level Up Hour (E35): Podman v3 and docker-compose.

**Comment by siretart** [comment]
I believe this request is tracked as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=984770 -- let me know if I'm missing something here.

Sorry for the delay, but I was planning to work on this after podman v3.2.1 makes it to experimental.

Note that this unfortunately won't make it into debian/bullseye :-(

**Comment by rhatdan** [comment]
Since this is not a upstream issue, I am going to close it, follow up in the bugs.debian.org.
Thanks.

**Comment by siretart** [comment]
FYI, the `podman-docker` is now available in debian/experimental and ubuntu/impish.

**Comment by rhatdan** [comment]
Great thanks @siretart
