### ISSUE TITLE
podman-remote-static in release v3.2.0 is not static 

### ISSUE THREAD

**Issue by polettix** [containers/podman#10656]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The podman-remote-static build for Linux available in release v3.2.0 is not static.

**Steps to reproduce the issue:**

```
$ curl -LO https://github.com/containers/podman/releases/download/v3.2.0/podman-remote-static.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   635  100   635    0     0   1765      0 --:--:-- --:--:-- --:--:--  1768
100 14.7M  100 14.7M    0     0  1735k      0  0:00:08  0:00:08 --:--:-- 1912k

$ tar xvf podman-remote-static.tar.gz 
podman-remote-static

$ ls -l
total 48096
-rwxr-xr-x 1 poletti poletti 33786912 Jun  3 22:09 podman-remote-static
-rw-r--r-- 1 poletti poletti 15459539 Jun 11 16:13 podman-remote-static.tar.gz

$ ldd podman-remote-static
./podman-remote-static: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./podman-remote-static)
	linux-vdso.so.1 (0x00007ffd215f4000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fa7613be000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fa7611ba000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa760e1b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa7615db000)
```

**Describe the results you received:**

The `ldd` command provides a list of linked shared object files.

**Describe the results you expected:**

This is the same command run on version v3.1.2, showing the expected result:

```
$ ldd ~/v3.1.2/podman-remote-static 
	not a dynamic executable
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Only tested on the latest version and the previous one.

**Output of `podman version`:**

As the static version is not static, `podman` v.3.2.0 is not capable of running in my setup.

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

Downloaded file from GitHub, no package manager involved.

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes, the test was done on the latest version as of June 11th, 2021.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Run in a VirtualBox VM, Debian Linux 9:

```
$ uname -a
Linux polebian 4.9.0-15-amd64 #1 SMP Debian 4.9.258-1 (2021-03-08) x86_64 GNU/Linux
```

This is actually not relevant as I was expecting a static build.

**Comment by mheon** [comment]
We definitely did some makefile maintenance between 3.1.2 and 3.2.0, so we probably broke this somewhere in the midst of that.

**Comment by cevich** [comment]
Oh!  Yep, Matt's likely correct.  I'll take a peek, thanks for letting us know.

**Comment by cevich** [comment]
I think I see the problem: The definition for `$LDFLAGS_PODMAN_STATIC` seems to have been lost.  Working on a PR to fix it.
