### ISSUE TITLE
Rootless container created with network will not start on podman-3.0.1-6

### ISSUE THREAD

**Issue by Aight25** [containers/podman#10659]
**Steps to reproduce the issue:**

1. Set cgroups v2
grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=1"; shutdown -r 0

2. Enable linger
loginctl enable-linger ctest01

3. Build rootless-cni-infra via the ctest01 user
Download Containerfile & rootless-cni-infra
chmod 755 rootless-cni-infra
podman build -t rootless-cni-infra .

4. Create network
podman network create --subnet 192.168.3.0/28 --gateway 192.168.3.1 test01

5. Run container with network, test01
podman run -d --name test01 --hostname test01.example.lan --net test01 --ip 192.168.3.10 ubi8-init
Error: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:76: mounting "/home/ctest01/.config/cni/net.d" to rootfs at "/etc/cni/net.d" caused: operation not permitted: OCI permission denied

6. Run container with network, test01 with debug flag
podman run -d --log-level debug --name test01 --hostname test01.example.lan --net test01 --ip 192.168.3.10 ubi8-init
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called run.PersistentPreRunE(podman run -d --log-level debug --name test01 --hostname test01.example.lan --net test01 --ip 192.168.3.10 ubi8-init) 
DEBU[0000] Reading configuration file "/usr/share/containers/containers.conf" 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf": &{Containers:{Devices:[] Volumes:[] ApparmorProfile:containers-default-0.33.4 Annotations:[] CgroupNS:private Cgroups:enabled DefaultCapabilities:[NET_RAW CHOWN DAC_OVERRIDE FOWNER FSETID KILL NET_BIND_SERVICE SETFCAP SETGID SETPCAP SETUID SYS_CHROOT] DefaultSysctls:[net.ipv4.ping_group_range=0 0] DefaultUlimits:[] DefaultMountsFile: DNSServers:[] DNSOptions:[] DNSSearches:[] EnableKeyring:true EnableLabeling:true Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin TERM=xterm] EnvHost:false HTTPProxy:true Init:false InitPath: IPCNS:private LogDriver:k8s-file LogSizeMax:-1 NetNS:slirp4netns NoHosts:false PidsLimit:2048 PidNS:private SeccompProfile:/usr/share/containers/seccomp.json ShmSize:65536k TZ: Umask:0022 UTSNS:private UserNS:host UserNSSize:65536} Engine:{ImageBuildFormat:oci CgroupCheck:false CgroupManager:systemd ConmonEnvVars:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] ConmonPath:[/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon] DetachKeys:ctrl-p,ctrl-q EnablePortReservation:true Env:[] EventsLogFilePath:/run/user/1006/libpod/tmp/events/events.log EventsLogger:file HooksDir:[/usr/share/containers/oci/hooks.d] ImageDefaultTransport:docker:// InfraCommand: InfraImage:registry.access.redhat.com/ubi8/pause InitPath:/usr/libexec/podman/catatonit LockType:shm MultiImageArchive:false Namespace: NetworkCmdPath: NetworkCmdOptions:[] NoPivotRoot:false NumLocks:2048 OCIRuntime:runc OCIRuntimes:map[crun:[/usr/bin/crun /usr/sbin/crun /usr/local/bin/crun /usr/local/sbin/crun /sbin/crun /bin/crun /run/current-system/sw/bin/crun] kata:[/usr/bin/kata-runtime /usr/sbin/kata-runtime /usr/local/bin/kata-runtime /usr/local/sbin/kata-runtime /sbin/kata-runtime /bin/kata-runtime /usr/bin/kata-qemu /usr/bin/kata-fc] runc:[/usr/bin/runc /usr/sbin/runc /usr/local/bin/runc /usr/local/sbin/runc /sbin/runc /bin/runc /usr/lib/cri-o-runc/sbin/runc /run/current-system/sw/bin/runc]] PullPolicy:missing Remote:false RemoteURI: RemoteIdentity: ActiveService: ServiceDestinations:map[] RuntimePath:[] RuntimeSupportsJSON:[crun runc] RuntimeSupportsNoCgroups:[crun] RuntimeSupportsKVM:[kata kata-runtime kata-qemu kata-fc] SetOptions:{StorageConfigRunRootSet:false StorageConfigGraphRootSet:false StorageConfigGraphDriverNameSet:false StaticDirSet:false VolumePathSet:false TmpDirSet:false} SignaturePolicyPath:/etc/containers/policy.json SDNotify:false StateType:3 StaticDir:/home/ctest01/.local/share/containers/storage/libpod StopTimeout:10 TmpDir:/run/user/1006/libpod/tmp VolumePath:/home/ctest01/.local/share/containers/storage/volumes VolumePlugins:map[]} Network:{CNIPluginDirs:[/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin] DefaultNetwork:podman NetworkConfigDir:/home/ctest01/.config/cni/net.d}} 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /home/ctest01/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/ctest01/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1006/containers     
DEBU[0000] Using static dir /home/ctest01/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1006/libpod/tmp      
DEBU[0000] Using volume path /home/ctest01/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] Not configuring container store              
DEBU[0000] Initializing event backend file              
DEBU[0000] using runtime "/usr/bin/crun"                
DEBU[0000] using runtime "/usr/bin/runc"                
INFO[0000] Error initializing configured OCI runtime kata: no valid executable found for OCI runtime kata: invalid argument 
INFO[0000] Setting parallel job count to 13             
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called run.PersistentPreRunE(podman run -d --log-level debug --name test01 --hostname test01.example.lan --net test01 --ip 192.168.3.10 ubi8-init) 
DEBU[0000] Reading configuration file "/usr/share/containers/containers.conf" 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf": &{Containers:{Devices:[] Volumes:[] ApparmorProfile:containers-default-0.33.4 Annotations:[] CgroupNS:private Cgroups:enabled DefaultCapabilities:[NET_RAW CHOWN DAC_OVERRIDE FOWNER FSETID KILL NET_BIND_SERVICE SETFCAP SETGID SETPCAP SETUID SYS_CHROOT] DefaultSysctls:[net.ipv4.ping_group_range=0 0] DefaultUlimits:[] DefaultMountsFile: DNSServers:[] DNSOptions:[] DNSSearches:[] EnableKeyring:true EnableLabeling:true Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin TERM=xterm] EnvHost:false HTTPProxy:true Init:false InitPath: IPCNS:private LogDriver:k8s-file LogSizeMax:-1 NetNS:slirp4netns NoHosts:false PidsLimit:2048 PidNS:private SeccompProfile:/usr/share/containers/seccomp.json ShmSize:65536k TZ: Umask:0022 UTSNS:private UserNS:host UserNSSize:65536} Engine:{ImageBuildFormat:oci CgroupCheck:false CgroupManager:systemd ConmonEnvVars:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] ConmonPath:[/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon] DetachKeys:ctrl-p,ctrl-q EnablePortReservation:true Env:[] EventsLogFilePath:/run/user/1006/libpod/tmp/events/events.log EventsLogger:file HooksDir:[/usr/share/containers/oci/hooks.d] ImageDefaultTransport:docker:// InfraCommand: InfraImage:registry.access.redhat.com/ubi8/pause InitPath:/usr/libexec/podman/catatonit LockType:shm MultiImageArchive:false Namespace: NetworkCmdPath: NetworkCmdOptions:[] NoPivotRoot:false NumLocks:2048 OCIRuntime:runc OCIRuntimes:map[crun:[/usr/bin/crun /usr/sbin/crun /usr/local/bin/crun /usr/local/sbin/crun /sbin/crun /bin/crun /run/current-system/sw/bin/crun] kata:[/usr/bin/kata-runtime /usr/sbin/kata-runtime /usr/local/bin/kata-runtime /usr/local/sbin/kata-runtime /sbin/kata-runtime /bin/kata-runtime /usr/bin/kata-qemu /usr/bin/kata-fc] runc:[/usr/bin/runc /usr/sbin/runc /usr/local/bin/runc /usr/local/sbin/runc /sbin/runc /bin/runc /usr/lib/cri-o-runc/sbin/runc /run/current-system/sw/bin/runc]] PullPolicy:missing Remote:false RemoteURI: RemoteIdentity: ActiveService: ServiceDestinations:map[] RuntimePath:[] RuntimeSupportsJSON:[crun runc] RuntimeSupportsNoCgroups:[crun] RuntimeSupportsKVM:[kata kata-runtime kata-qemu kata-fc] SetOptions:{StorageConfigRunRootSet:false StorageConfigGraphRootSet:false StorageConfigGraphDriverNameSet:false StaticDirSet:false VolumePathSet:false TmpDirSet:false} SignaturePolicyPath:/etc/containers/policy.json SDNotify:false StateType:3 StaticDir:/home/ctest01/.local/share/containers/storage/libpod StopTimeout:10 TmpDir:/run/user/1006/libpod/tmp VolumePath:/home/ctest01/.local/share/containers/storage/volumes VolumePlugins:map[]} Network:{CNIPluginDirs:[/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin] DefaultNetwork:podman NetworkConfigDir:/home/ctest01/.config/cni/net.d}} 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /home/ctest01/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/ctest01/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1006/containers     
DEBU[0000] Using static dir /home/ctest01/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1006/libpod/tmp      
DEBU[0000] Using volume path /home/ctest01/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] overlay: mount_program=/usr/bin/fuse-overlayfs 
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=false 
DEBU[0000] Initializing event backend file              
INFO[0000] Error initializing configured OCI runtime kata: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] using runtime "/usr/bin/crun"                
DEBU[0000] using runtime "/usr/bin/runc"                
INFO[0000] Setting parallel job count to 13             
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf" 
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/000-shortnames.conf" 
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/001-rhel-shortnames.conf" 
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/002-rhel-shortnames-overrides.conf" 
DEBU[0000] parsed reference into "[overlay@/home/ctest01/.local/share/containers/storage+/run/user/1006/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]@9bbdcc2d3f32a0f64fdd226f4e1efdb15cede47140f5dc1739cd3c48b3f07b63" 
DEBU[0000] exporting opaque data as blob "sha256:9bbdcc2d3f32a0f64fdd226f4e1efdb15cede47140f5dc1739cd3c48b3f07b63" 
DEBU[0000] parsed reference into "[overlay@/home/ctest01/.local/share/containers/storage+/run/user/1006/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]@9bbdcc2d3f32a0f64fdd226f4e1efdb15cede47140f5dc1739cd3c48b3f07b63" 
DEBU[0000] exporting opaque data as blob "sha256:9bbdcc2d3f32a0f64fdd226f4e1efdb15cede47140f5dc1739cd3c48b3f07b63" 
DEBU[0000] using systemd mode: true                     
DEBU[0000] setting container name test01                
DEBU[0000] Loading seccomp profile from "/usr/share/containers/seccomp.json" 
DEBU[0000] Allocated lock 0 for container 38c2ba4e304eec5b24d688ae6ea7abc3a19f239abdfe87933dc2be545c2bb89c 
DEBU[0000] parsed reference into "[overlay@/home/ctest01/.local/share/containers/storage+/run/user/1006/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]@9bbdcc2d3f32a0f64fdd226f4e1efdb15cede47140f5dc1739cd3c48b3f07b63" 
DEBU[0000] exporting opaque data as blob "sha256:9bbdcc2d3f32a0f64fdd226f4e1efdb15cede47140f5dc1739cd3c48b3f07b63" 
DEBU[0000] created container "38c2ba4e304eec5b24d688ae6ea7abc3a19f239abdfe87933dc2be545c2bb89c" 
DEBU[0000] container "38c2ba4e304eec5b24d688ae6ea7abc3a19f239abdfe87933dc2be545c2bb89c" has work directory "/home/ctest01/.local/share/containers/storage/overlay-containers/38c2ba4e304eec5b24d688ae6ea7abc3a19f239abdfe87933dc2be545c2bb89c/userdata" 
DEBU[0000] container "38c2ba4e304eec5b24d688ae6ea7abc3a19f239abdfe87933dc2be545c2bb89c" has run directory "/run/user/1006/containers/overlay-containers/38c2ba4e304eec5b24d688ae6ea7abc3a19f239abdfe87933dc2be545c2bb89c/userdata" 
DEBU[0000] overlay: mount_data=,lowerdir=/home/ctest01/.local/share/containers/storage/overlay/l/KS2UGBZM3VYXBAFGYVCQJEZT7A:/home/ctest01/.local/share/containers/storage/overlay/l/SYH4FOOO4SGUF7JNSPPPR43ZTE:/home/ctest01/.local/share/containers/storage/overlay/l/HO5WCC4RL4JGHHRO5L3BNSOHVG,upperdir=/home/ctest01/.local/share/containers/storage/overlay/e789f49b8c9b738dbcee497959b35cf54616143d3908a7b57b9a594cf55d7e69/diff,workdir=/home/ctest01/.local/share/containers/storage/overlay/e789f49b8c9b738dbcee497959b35cf54616143d3908a7b57b9a594cf55d7e69/work,context="system_u:object_r:container_file_t:s0:c77,c395" 
DEBU[0000] mounted container "38c2ba4e304eec5b24d688ae6ea7abc3a19f239abdfe87933dc2be545c2bb89c" at "/home/ctest01/.local/share/containers/storage/overlay/e789f49b8c9b738dbcee497959b35cf54616143d3908a7b57b9a594cf55d7e69/merged" 
DEBU[0000] rootless CNI: infra container "a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07" is "configured", being started 
DEBU[0000] Created root filesystem for container 38c2ba4e304eec5b24d688ae6ea7abc3a19f239abdfe87933dc2be545c2bb89c at /home/ctest01/.local/share/containers/storage/overlay/e789f49b8c9b738dbcee497959b35cf54616143d3908a7b57b9a594cf55d7e69/merged 
DEBU[0000] overlay: mount_data=,lowerdir=/home/ctest01/.local/share/containers/storage/overlay/l/O3Z6U4XDUP6QJXF2YJY2CLZ2RM:/home/ctest01/.local/share/containers/storage/overlay/l/3IIO6BWF5HZTAN6K6HPBTOQO3F:/home/ctest01/.local/share/containers/storage/overlay/l/ETMG52XSYBWTQ75EWLKJDHG3J2:/home/ctest01/.local/share/containers/storage/overlay/l/F3CVEP25H4NZCMSOWJEDAIQDH3:/home/ctest01/.local/share/containers/storage/overlay/l/UWTMKQAZXAZ3YXL4HADCYH5325:/home/ctest01/.local/share/containers/storage/overlay/l/ZEDFAVYOGJS7GK6KQRGXKOTNW7,upperdir=/home/ctest01/.local/share/containers/storage/overlay/bbc7e21a8ead7451361267c8b72093ecc4ba8dc353d87dabaaa0cf95d4b3a80a/diff,workdir=/home/ctest01/.local/share/containers/storage/overlay/bbc7e21a8ead7451361267c8b72093ecc4ba8dc353d87dabaaa0cf95d4b3a80a/work,context="system_u:object_r:container_file_t:s0:c225,c527" 
DEBU[0000] Made network namespace at /run/user/1006/netns/cni-ccacd29e-54cc-2c2f-bdf9-89f59288cae0 for container a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07 
DEBU[0000] mounted container "a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07" at "/home/ctest01/.local/share/containers/storage/overlay/bbc7e21a8ead7451361267c8b72093ecc4ba8dc353d87dabaaa0cf95d4b3a80a/merged" 
DEBU[0000] slirp4netns command: /usr/bin/slirp4netns --disable-host-loopback --mtu=65520 --enable-sandbox --enable-seccomp -c -e 3 -r 4 --netns-type=path /run/user/1006/netns/cni-ccacd29e-54cc-2c2f-bdf9-89f59288cae0 tap0 
DEBU[0000] Created root filesystem for container a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07 at /home/ctest01/.local/share/containers/storage/overlay/bbc7e21a8ead7451361267c8b72093ecc4ba8dc353d87dabaaa0cf95d4b3a80a/merged 
DEBU[0000] Workdir "/" resolved to host path "/home/ctest01/.local/share/containers/storage/overlay/bbc7e21a8ead7451361267c8b72093ecc4ba8dc353d87dabaaa0cf95d4b3a80a/merged" 
DEBU[0000] /etc/system-fips does not exist on host, not mounting FIPS mode subscription 
INFO[0000] User mount overriding libpod mount at "/dev/shm" 
DEBU[0000] Setting CGroups for container a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07 to user.slice:libpod:a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07 
DEBU[0000] reading hooks from /usr/share/containers/oci/hooks.d 
DEBU[0000] Created OCI spec for container a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07 at /home/ctest01/.local/share/containers/storage/overlay-containers/a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07/userdata/config.json 
DEBU[0000] /usr/bin/conmon messages will be logged to syslog 
DEBU[0000] running conmon: /usr/bin/conmon               args="[--api-version 1 -c a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07 -u a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07 -r /usr/bin/runc -b /home/ctest01/.local/share/containers/storage/overlay-containers/a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07/userdata -p /run/user/1006/containers/overlay-containers/a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07/userdata/pidfile -n rootless-cni-infra --exit-dir /run/user/1006/libpod/tmp/exits --socket-dir-path /run/user/1006/libpod/tmp/socket -s -l k8s-file:/home/ctest01/.local/share/containers/storage/overlay-containers/a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07/userdata/ctr.log --log-level debug --syslog --conmon-pidfile /run/user/1006/containers/overlay-containers/a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07/userdata/conmon.pid]"
INFO[0000] Running conmon under slice user.slice and unitName libpod-conmon-a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07.scope 
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

DEBU[0000] Received: -1                                 
DEBU[0000] Cleaning up container a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07 
DEBU[0000] Tearing down network namespace at /run/user/1006/netns/cni-ccacd29e-54cc-2c2f-bdf9-89f59288cae0 for container a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07 
DEBU[0000] unmounted container "a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07" 
DEBU[0000] unmounted container "38c2ba4e304eec5b24d688ae6ea7abc3a19f239abdfe87933dc2be545c2bb89c" 
DEBU[0000] Network is already cleaned up, skipping...   
DEBU[0000] Cleaning up container 38c2ba4e304eec5b24d688ae6ea7abc3a19f239abdfe87933dc2be545c2bb89c 
DEBU[0000] Network is already cleaned up, skipping...   
DEBU[0000] Container 38c2ba4e304eec5b24d688ae6ea7abc3a19f239abdfe87933dc2be545c2bb89c storage is already unmounted, skipping... 
DEBU[0000] ExitCode msg: "time=\"2021-06-11t17:58:35+02:00\" level=warning msg=\"freezer not supported: open /sys/fs/cgroup/user.slice/user-1006.slice/user@1006.service/user.slice/libpod-a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07.scope/cgroup.freeze: no such file or directory\"\ntime=\"2021-06-11t17:58:35+02:00\" level=warning msg=\"lstat /sys/fs/cgroup/user.slice/user-1006.slice/user@1006.service/user.slice/libpod-a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07.scope: no such file or directory\"\ntime=\"2021-06-11t17:58:35+02:00\" level=error msg=\"container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:76: mounting \\\"/home/ctest01/.config/cni/net.d\\\" to rootfs at \\\"/etc/cni/net.d\\\" caused: operation not permitted\": oci permission denied" 
Error: time="2021-06-11T17:58:35+02:00" level=warning msg="freezer not supported: open /sys/fs/cgroup/user.slice/user-1006.slice/user@1006.service/user.slice/libpod-a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07.scope/cgroup.freeze: no such file or directory"
time="2021-06-11T17:58:35+02:00" level=warning msg="lstat /sys/fs/cgroup/user.slice/user-1006.slice/user@1006.service/user.slice/libpod-a7a9b7431fffd54699d8eaa156e79ab7850acb3f592918e9357345413d72bb07.scope: no such file or directory"
time="2021-06-11T17:58:35+02:00" level=error msg="container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:76: mounting \"/home/ctest01/.config/cni/net.d\" to rootfs at \"/etc/cni/net.d\" caused: operation not permitted": OCI permission denied

**Describe the results you received:**
Error: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: rootfs_linux.go:76: mounting "/home/ctest01/.config/cni/net.d" to rootfs at "/etc/cni/net.d" caused: operation not permitted: OCI permission denied

And the container gets created but doesn't start

**Describe the results you expected:**
podman run -d --name test01 --hostname test01.example.lan --net test01 --ip 192.168.3.10 ubi8-init
160ff79ffab3538a85e0732e423f43b943d09fc82c11ac95964032744940c47a

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
```
Version:      3.0.2-dev
API Version:  3.0.0
Go Version:   go1.15.13
Built:        Tue Jun  8 09:52:06 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.8
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.26-3.module+el8.4.0+11311+9da8acfb.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: a35bb9ea67d5a83c7da53202f2fcd505c036d29c'
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "8.4"
  eventLogger: file
  hostname: X.example.lan
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1006
      size: 1
    - container_id: 1
      host_id: 493216
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1006
      size: 1
    - container_id: 1
      host_id: 493216
      size: 65536
  kernel: 4.18.0-305.3.1.el8_4.x86_64
  linkmode: dynamic
  memFree: 14270205952
  memTotal: 16601272320
  ociRuntime:
    name: runc
    package: runc-1.0.0-73.rc93.module+el8.4.0+11311+9da8acfb.x86_64
    path: /usr/bin/runc
    version: |-
      runc version spec: 1.0.2-dev
      go: go1.15.13
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/user/1006/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.4.0+11311+9da8acfb.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 19m 39.1s
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/ctest01/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.4.0-3.module+el8.4.0+11311+9da8acfb.x86_64
      Version: |-
        fusermount3 version: 3.2.1
        fuse-overlayfs: version 1.4
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/ctest01/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 24
  runRoot: /run/user/1006/containers
  volumePath: /home/ctest01/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1623138726
  BuiltTime: Tue Jun  8 09:52:06 2021
  GitCommit: ""
  GoVersion: go1.15.13
  OsArch: linux/amd64
  Version: 3.0.2-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.0.1-7.module+el8.4.0+11311+9da8acfb.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No
Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
The rootless network stack was completely reworked in Podman 3.2.0, so this type of error can no longer occur.
