### ISSUE TITLE
Verification for #podman:matrix.org ownership

### ISSUE THREAD

**Issue by lsm5** [containers/podman#10657]
I'm in talks with matrix.org support team to reclaim ownership of `#podman:matrix.org` room. Currently it seems to be a private room and nobody knows who the current owner is.

I have sent a bunch of links about my association with podman but I'm hoping this issue serves as a public team signoff on the request.

Could people +1 this issue so I can forward this as verification to the matrix folks that this is an official podman request? 

@edsantiago @mheon @vrothberg @rhatdan @umohnani8 @jwhonce @TomSweeneyRedHat

**Comment by cevich** [comment]
+1

**Comment by umohnani8** [comment]
+1

**Comment by mheon** [comment]
+1

**Comment by rhatdan** [comment]
+1

**Comment by TomSweeneyRedHat** [comment]
+1

**Comment by lsm5** [comment]
Sent this over to the matrix support ticket. I'll update any progress here.

**Comment by edsantiago** [comment]
+1

**Comment by towe75** [comment]
+1

**Comment by vrothberg** [comment]
+1

**Comment by rhatdan** [comment]
I think the issue has served its purpose.
