### ISSUE TITLE
Compat API: building a container with a custom Dockerfile started failing with #10550

### ISSUE THREAD

**Issue by riyad** [containers/podman#10663]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Trying to find regressions by exercising the APIv2 through [docker-py](https://github.com/docker/docker-py)'s test suite (see #5386) I came across a regression.

Building a container with a custom Dockerfile started failing with #10550.

**Steps to reproduce the issue:**

1.
```shell
cat > custom.dockerfile <<EOF
FROM busybox
EOF
```

2. `tar cf test.tar custom.dockerfile`

3. `curl -sS --unix-socket /run/user/1000/podman/podman.sock -XPOST 'http://localhost/v1.40/build?dockerfile=custom.dockerfile'  -H "Content-Type: application/tar" --data-binary '@test.tar'`

**Describe the results you received:**

Run against commit 2970e3518cc95910444903f572418f5887316e47 the result is:
```
400 Bad Request
{"cause":"invalid character 'c' looking for beginning of value","message":"failed to parse query parameter 'dockerfile': \"custom.dockerfile\": invalid character 'c' looking for beginning of value","response":400}
```

**Describe the results you expected:**

Before #10550 (e.g. c75d62c9877f56f6cc6253087b75ab05b8e4eac5) was merged the result was:
```
200 OK
{"stream":"STEP 1: FROM busybox\n"}
{"stream":"STEP 2: COMMIT\n"}
{"stream":"--\u003e d3cd072556c\n"}
{"stream":"d3cd072556c21c1f1940bd536675b97d7d419a2287d6bb3bd5044ea7466db788\n"}
{"stream":"Successfully built d3cd072556c2\n"}
```

**Comment by mheon** [comment]
Dupe of https://github.com/containers/podman/issues/10660?

**Comment by riyad** [comment]
Oh, indeed. :sweat_smile:
