### ISSUE TITLE
podman logs -f: misses final container output

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#10675]
This one smells a little like #10003 but it's podman-local, not -remote.
```
$ podman run -d quay.io/libpod/testimage:20210427 sh -c 'for i in 1 2 3 4 5 6 8 10 12 13 14 15 16 20 21 22 23 24 25 26 64; do trap "echo got: $i" $i; done;echo READY;while ! test -e /stop; do sleep 0.05; done;echo DONE'
$ podman kill -s X $cid
[lots more podman-kills]
$ podman exec $cid touch /stop
...container fails to echo DONE...
```
(The above is not a real reproducer, just an overview of the problem)

## sys: podman kill - test signal handling in containers
* fedora-33 : sys podman fedora-33 rootless host
  * PR #10635
    * [06-11 11:14](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4808706966683648/html/sys-podman-fedora-33-rootless-host.log.html)
  * PR #10628
    * [06-10 11:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6007134157537280/html/sys-podman-fedora-33-rootless-host.log.html)
  * PR #10611
    * [06-09 12:59](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5129405514121216/html/sys-podman-fedora-33-rootless-host.log.html)
* fedora-34 : sys podman fedora-34 rootless host
  * PR #10654
    * [06-11 16:25](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6147039093325824/html/sys-podman-fedora-34-rootless-host.log.html)
    * [06-11 13:17](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6185071246835712/html/sys-podman-fedora-34-rootless-host.log.html)
  * PR #10634
    * [06-10 05:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6718132841611264/html/sys-podman-fedora-34-rootless-host.log.html)
  * PR #10611
    * [06-09 14:53](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5645402952171520/html/sys-podman-fedora-34-rootless-host.log.html)
    * [06-09 12:59](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4546459199602688/html/sys-podman-fedora-34-rootless-host.log.html)
  * PR #10550
    * [06-08 17:11](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5927947845500928/html/sys-podman-fedora-34-rootless-host.log.html)
* ubuntu-2010 : sys podman ubuntu-2010 rootless host
  * PR #10618
    * [06-09 13:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5904247494541312/html/sys-podman-ubuntu-2010-rootless-host.log.html)
  * PR #10405
    * [06-11 11:49](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6692056417435648/html/sys-podman-ubuntu-2010-rootless-host.log.html)
* ubuntu-2104 : sys podman ubuntu-2104 rootless host
  * PR #10646
    * [06-10 16:51](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6249054431608832/html/sys-podman-ubuntu-2104-rootless-host.log.html)
  * PR #10618
    * [06-09 14:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5278299212480512/html/sys-podman-ubuntu-2104-rootless-host.log.html)
    * [06-09 13:34](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4778347587698688/html/sys-podman-ubuntu-2104-rootless-host.log.html)
  * PR #10550
    * [06-08 17:10](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6490897798922240/html/sys-podman-ubuntu-2104-rootless-host.log.html)

**Comment by edsantiago** [comment]
Here's a reproducer (copy-paste into `foo.sh`):
```bash
#!/bin/bash

while :;do
    cid=$(./bin/podman run -d quay.io/libpod/testimage:20210610 sh -c 'for i in 1 2 3 4 5 6 8 10 12 13 14 15 16 20 21 22 23 24 25 26 64; do trap "echo got: $i" $i; done;echo READY;while ! test -e /stop; do sleep 0.05; done;echo DONE')

    ./bin/podman logs -f $cid >| /tmp/foo.log &
    logger=$!

    for s in 6 64 10 14 25 13 20 3 1 21 8 2 4 16 26 5 24 12 23 15 22 1 INT FPE USR1 USR2; do ./bin/podman kill -s $s $cid >/dev/null;done
    ./bin/podman exec $cid touch /stop
    sleep 2
    grep DONE /tmp/foo.log || exit 1

    ./bin/podman rm -a
done
```
What it looks like to me is a resurrection of an old bug: `podman logs -f` sees that the container has died, and it exits without emitting the final output from the container.

Note that when this script fails, `podman logs -l` (correctly) shows DONE as the last line, but `/tmp/foo.log` does not include DONE.

Connected to @vrothberg's recent work on events and logging?

**Comment by edsantiago** [comment]
UPDATE: I edited the reproducer, simplifying it because signals and `exec` have nothing to do with the failure. It's just logs. But I'm also now seeing weird `ERROR[0000] <nil>` messages spit out at random:
```console
$ sh -x ./foo.sh                                                                                                                                  - (2)
+ :
++ ./bin/podman run -d quay.io/libpod/testimage:20210610 sh -c 'while ! test -e /stop; do sleep 0.05; done;echo DONE'
+ cid=082f99f2206144e2169cca936b8ff632e684eb4bfd0c623b0016f4fdecca3fdb
+ ./bin/podman exec 082f99f2206144e2169cca936b8ff632e684eb4bfd0c623b0016f4fdecca3fdb touch /stop
+ ./bin/podman logs -f 082f99f2206144e2169cca936b8ff632e684eb4bfd0c623b0016f4fdecca3fdb
+ ./bin/podman wait 082f99f2206144e2169cca936b8ff632e684eb4bfd0c623b0016f4fdecca3fdb
ERRO[0000] <nil>
0
+ grep DONE /tmp/foo.log
DONE
+ ./bin/podman rm -a
082f99f2206144e2169cca936b8ff632e684eb4bfd0c623b0016f4fdecca3fdb
+ :
++ ./bin/podman run -d quay.io/libpod/testimage:20210610 sh -c 'while ! test -e /stop; do sleep 0.05; done;echo DONE'
+ cid=9dbddfcfa4de3b39b155db659e7b9e132525bc92b9502838966895270c70a8d4
+ ./bin/podman exec 9dbddfcfa4de3b39b155db659e7b9e132525bc92b9502838966895270c70a8d4 touch /stop
+ ./bin/podman logs -f 9dbddfcfa4de3b39b155db659e7b9e132525bc92b9502838966895270c70a8d4
ERRO[0000] <nil>
+ ./bin/podman wait 9dbddfcfa4de3b39b155db659e7b9e132525bc92b9502838966895270c70a8d4
0
+ grep DONE /tmp/foo.log
DONE
+ ./bin/podman rm -a
9dbddfcfa4de3b39b155db659e7b9e132525bc92b9502838966895270c70a8d4
+ :
++ ./bin/podman run -d quay.io/libpod/testimage:20210610 sh -c 'while ! test -e /stop; do sleep 0.05; done;echo DONE'
+ cid=52b6e82bc2aa97254faf525b8eab789d4a051970ec33417da4d77ab4b1da9a37
+ ./bin/podman exec 52b6e82bc2aa97254faf525b8eab789d4a051970ec33417da4d77ab4b1da9a37 touch /stop
+ ./bin/podman logs -f 52b6e82bc2aa97254faf525b8eab789d4a051970ec33417da4d77ab4b1da9a37
^C+ ./bin/podman wait 52b6e82bc2aa97254faf525b8eab789d4a051970ec33417da4d77ab4b1da9a37
0
+ grep DONE /tmp/foo.log
+ exit 1
```

**Comment by edsantiago** [comment]
Yeah, there is something broken in `podman logs`. That's where the red `ERRO[0000] <nil>` is coming from. Changing the above reproducer as follows:
```diff
-     ./bin/podman logs -f $cid >| /tmp/foo.log &
+     ./bin/podman logs -f $cid >| /tmp/foo.log 2>&1 &
```
...makes the ERRO message go away. Instead, it shows up in foo.log as:
```
time="2021-06-15T05:59:25-06:00" level=error msg="<nil>"
```
And, bizarrely, it takes many more iterations for the failure to happen (about 10-20, instead of 2-5).

**Comment by Luap99** [comment]
@edsantiago Just to confirm you are using the file log driver?

**Comment by edsantiago** [comment]
I'm just using whatever is default, I haven't touched anything. I assume the CI systems (which are failing, which is the motivation for filing this issue) also use default.

On my system:
```console
$ podman info --format json | gron | grep -i log
json.host.eventLogger = "journald";
```
Is `eventLogger` the same as `log driver`?

**Comment by Luap99** [comment]
Yeah the default is `k8s-file`, `eventLogger` is not the same as `log driver`.
You can check the container with `podman container inspect --format "{{.HostConfig.LogConfig.Type}}" ...`.

**Comment by edsantiago** [comment]
I cannot reproduce this if I switch the `podman run` as follows:
```diff
-cid=$(./bin/podman run -d ... sh -c 'while ! test -e /stop; do sleep 0.05; done;echo DONE')
+cid=$(./bin/podman run -d ... sh -c 'sleep 5;echo DONE')
```
(even if I keep the `podman exec`)

**Comment by edsantiago** [comment]
I cannot reproduce if I change `sleep 0.05` to `sleep 2`. I *can* reproduce with `sleep 1`.

**Comment by edsantiago** [comment]
Followup from this morning's conversation: every so often, the reproducer will hang. I just got one of those; it was 30 seconds, and my CPU was pegged during that period:
```console
$ ./foo.sh | ts
Jun 15 12:49:23 0
Jun 15 12:49:23 DONE
Jun 15 12:49:23 e51322e2b563e2154b77a90d2d6300b15a07e7978dc22a9193d6efd96b74132a
Jun 15 12:49:23 4b0c79103a429bb544df1a70a7a9c32fe674438555504ac0425a3a56d542098d
Jun 15 12:49:24 0
Jun 15 12:49:24 DONE
Jun 15 12:49:24 6424c6c49f9f61af84695d557978ab69af4a5f7c7eb3314ca0cebcb36056c2aa
ERRO[0000] <nil>
       [ this is where it hung ]
Jun 15 12:49:52 0
Jun 15 12:49:52 DONE
```
I don't have the granularity to know exactly where it hung: it could've been `podman run`, or `podman logs`, or `podman exec`, or `podman wait`.

**Comment by edsantiago** [comment]
The hang is in `exec`. `strace -p` is useless, showing `futex(0x28709f0, FUTEX_WAIT_PRIVATE, 0, NULL`, a pause, then `) = ?`.

**Comment by edsantiago** [comment]
Filed #10701 for the `exec` hang.

**Comment by vrothberg** [comment]
I'll take a look.  I recently touch the code and may have caused this regression.

**Comment by vrothberg** [comment]
Opened https://github.com/containers/podman/pull/10742 to clean up the ugly error log and fix the race condition.
