### ISSUE TITLE
podman search: Cannot move process 482667 to cgroup \"/sys/fs/cgroup/user.slice/user-31763.slice/user@31763.service/user.slice/podman-pause.scope\""

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#10674]
This is the new top flake, the "https" one. Over a hundred of these in the last week:
```
Running: podman [options] search localhost:5005/my-alpine
INDEX           NAME                      DESCRIPTION  STARS   OFFICIAL  AUTOMATED
localhost:5005  localhost:5005/my-alpine               0                 
time="2021-06-11T09:43:13-05:00" level=warning msg="Cannot move process 482667 to cgroup \"/sys/fs/cgroup/user.slice/user-31763.slice/user@31763.service/user.slice/podman-pause.scope\""
```
## Podman search [It] podman search attempts HTTP if registry is in registries.insecure and force secure is false
* fedora-33 : int podman fedora-33 rootless host
  * PR #10654
    * [06-11 10:46](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5762858781769728/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--1)
    * [06-11 10:46](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5762858781769728/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--2)
    * [06-11 10:46](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5762858781769728/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--3)
  * PR #10639
    * [06-10 15:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5265625367969792/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--1)
    * [06-10 15:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5265625367969792/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--2)
    * [06-10 15:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5265625367969792/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--3)
    * [06-10 10:57](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4711119655796736/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--1)
    * [06-10 10:57](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4711119655796736/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--2)
    * [06-10 10:57](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4711119655796736/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--3)
    * [06-10 10:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5577145385746432/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--1)
    * [06-10 10:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5577145385746432/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--2)
    * [06-10 10:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5577145385746432/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--3)
  * PR #10635
    * [06-10 07:03](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6585517757169664/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--1)
    * [06-10 07:03](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6585517757169664/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--2)
    * [06-10 07:03](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6585517757169664/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--3)
  * PR #10611
    * [06-09 15:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5005969429102592/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--1)
    * [06-09 15:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5005969429102592/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--2)
    * [06-09 15:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5005969429102592/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--3)
    * [06-09 11:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6398560297025536/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--1)
    * [06-09 11:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6398560297025536/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--2)
    * [06-09 11:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6398560297025536/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--3)
    * [06-09 10:19](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4686412789317632/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--1)
    * [06-09 10:19](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4686412789317632/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--2)
    * [06-09 10:19](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4686412789317632/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--3)
  * PR #10609
    * [06-10 15:28](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4584841443278848/html/int-podman-fedora-33-rootless-host.log.html#t--podman-search-attempts-HTTP-if-registry-is-in-registries-insecure-and-force-secure-is-false--1)
 
...and on and on and on. Also f34 and ubuntu 2104.

**Comment by edsantiago** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
```

           Expected
               <string>: time="2021-06-09T10:05:50-05:00" level=warning msg="Cannot move process 533368 to cgroup \"/sys/fs/cgroup/user.slice/user-12955.slice/user@12955.service/user.slice/podman-pause.scope\""
           to be empty
 ```

I think we should ignore the warning, or downgrade it to a debugging message

**Comment by giuseppe** [comment]
The failure seems to happen reliably with updated images, so added a patch here: https://github.com/containers/podman/pull/10451
