### ISSUE TITLE
rootless container suddenly stops and cannot be restarted

### ISSUE THREAD

**Issue by dan-m8t** [containers/podman#10673]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am running Podman rootless. Adguard Home is my DNS server, the container suddenly just stops for no reason and cannot be restarted. A reboot of the whole system is needed to get it to work again 

The container itself is restarting a lot of times, this is the container log:

```
2021/06/14 10:24:08.541261 [info] Received signal "terminated"
2021/06/14 10:24:08.541442 [info] Stopping AdGuard Home
2021/06/14 10:24:08.541447 [info] stopping http server...
2021/06/14 10:24:09.041611 [info] stopped http server
2021/06/14 10:24:09.041662 [info] Stopping the DNS proxy server
2021/06/14 10:24:09.041716 [info] udpListen.ReadFrom() returned because we're reading from a closed connection, exiting loop
```

**Steps to reproduce the issue:**

1. run container

2. container stops suddenly for no reason apparently

**Describe the results you received:**

podman debug log gives me this when I try to run the container again:

```
INFO[0000] Failed to add conmon to cgroupfs sandbox cgroup: error creating cgroup for memory: mkdir /sys/fs/cgroup/memory/libpod_parent: permission denied 
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied
```

**Describe the results you expected:**

a running container ;)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.0.2-dev
API Version:  3.0.0
Go Version:   go1.15.13
Built:        Tue Jun  8 09:52:06 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.8
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.26-3.module+el8.4.0+11311+9da8acfb.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: a35bb9ea67d5a83c7da53202f2fcd505c036d29c'
  cpus: 8
  distribution:
    distribution: '"rhel"'
    version: "8.4"
  eventLogger: file
  hostname: kvmhost.danscrib.de
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-305.3.1.el8_4.x86_64
  linkmode: dynamic
  memFree: 9509126144
  memTotal: 16550236160
  ociRuntime:
    name: runc
    package: runc-1.0.0-73.rc93.module+el8.4.0+11311+9da8acfb.x86_64
    path: /usr/bin/runc
    version: |-
      runc version spec: 1.0.2-dev
      go: go1.15.13
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.4.0+11311+9da8acfb.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 8443129856
  swapTotal: 8443129856
  uptime: 4m 27.59s
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/podmanusr/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 4
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.4.0-3.module+el8.4.0+11311+9da8acfb.x86_64
      Version: |-
        fusermount3 version: 3.2.1
        fuse-overlayfs: version 1.4
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/podmanusr/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 4
  runRoot: /tmp/podman-run-1000/containers
  volumePath: /home/podmanusr/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1623138726
  BuiltTime: Tue Jun  8 09:52:06 2021
  GitCommit: ""
  GoVersion: go1.15.13
  OsArch: linux/amd64
  Version: 3.0.2-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.0.1-7.module+el8.4.0+11311+9da8acfb.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Podman runs on a physical RHEL 8.4 host

**Comment by giuseppe** [comment]
`runRoot: /tmp/podman-run-1000/containers`

tmp is cleaned up by systemd-tmpfiles (with the default configuration weekly).

If you are using containers that run longer than that, please make sure a different path is used, or instruct tmpfiles to not touch files under /tmp/podman-run-1000`

**Comment by dan-m8t** [comment]
How do I make sure that podman is using a different path?
I got some other containers running way longer than this one, those do not run into any issues.

**Comment by mheon** [comment]
We now ship a tmpfiles config that will tell systemd to ignore these directories. Please upgrade to a more recent Podman.

**Comment by dan-m8t** [comment]
This is the most recent podman version I get from RHEL repos ... 

`dnf list installed | grep podman
podman.x86_64                                     3.0.1-7.module+el8.4.0+11311+9da8acfb          @rhel-8-for-x86_64-appstream-rpms
`

there's another container-tools stream which gives me this:

`dnf module info container-tools:3.0 | grep podman
  podman-0:3.0.1-6.module+el8.4.0+10614+dd38312c.x86_64`

Should I consider to switch to the kubic repo?

**Comment by dan-m8t** [comment]
Problem seems to be fixed after I set `rootless_storage_path` - no more restarts, closing this, thanks for your input!
