### ISSUE TITLE
[systemd] launching podman in systemd from root in another instance makes trouble

### ISSUE THREAD

**Issue by tobwen** [containers/podman#10677]
## category
That's neither a bug nor a feature. Maybe something for https://github.com/containers/podman/blob/master/troubleshooting.md

## summary
When trying to launch a _podman_/_conmon_  from _systemd_ service in another User/Group **from root**, neither `Type=forking` nor `Type=notify` works because of _systemd_'s safety precautions.

## `Type=notify`
``` ini
[Service]
User=podman
Group=podman
Restart=on-failure
TimeoutStopSec=70
ExecStart=/usr/bin/podmanrun --sdnotify=conmon --cgroups=no-conmon --rm --replace --name foo foo
Type=notify
NotifyAccess=all
```
Fails with the error message like:
```
Got notification message from PID 6946, but reception only permitted for main PID 496
```

## `Type=forking`
``` ini
[Service]
User=podman
Group=podman
Restart=on-failure
ExecStartPre=/usr/bin/rm -f /tmp/foo-pid /tmp/foo-cid
ExecStart=/usr/bin/podman run --conmon-pidfile /tmp/foo-pid --cidfile /tmp/foo-cid -d busybox:latest top
ExecStop=/usr/bin/sh -c "/usr/bin/podman rm -f `cat /tmp/foo-cid`"
KillMode=none
Type=forking
PIDFile=/tmp/foo-pid
```
Fails with the error message like:
```
New main PID 7756 does not belong to service, and PID file is not owned by root. Refusing.
```

## `Type=simple`
Works so far... but the communication with _conmon_ is lost, of course. Maybe other disadvantages.

## analysis
The observations of `Type=forking` nor `Type=notify` are based on CVEs. Non-privileged users shouldn't be able to manipulate processes or PID-files started by root. Since _podman_ gets started under non-root and since _conmon_ writes the PID-file as another user, this doesn't work. Also, since we've got a _systemd_-instance for user-lingering (_cgroupsv2_ seems to need this), this might interfere with the notification stuff.

## conclusion
- start _podman_ with under `--user` of_ systemd_ (harder to control from root, since `systemctl --user -M` will be available from https://github.com/systemd/systemd/releases/tag/v248)
- use `Type=simple` with possible disadvantages.

**Comment by mheon** [comment]
I know we talked to the systemd team, specifically about the `Type=forking` bit here - it seems like it would make sense that, since `User=podman` is specified, the PID file being owned by `podman` would be ok, but they did not agree. Their recommendation was to use `systemd --user` for the user in question instead.

Can't speak to the Notify bit, but it may well be similar reasoning.

**Comment by tobwen** [comment]
The problem I'm having with that is: it's ugly to control from root:
```
sudo -u podman XDG_RUNTIME_DIR=/run/user/$(id -u podman)/ systemctl --user stop foo
```

_systemd v248_ will be nicer, at least _Debian Bullseye_ comes with _v247_ only:
```
systemctl --user -M podman@.host stop foo
```

Aliasing might help here, of course.

**Comment by rhatdan** [comment]
Interested in opening a PR for troubleshooting.md
@vrothberg WDYT?

**Comment by vrothberg** [comment]
SGTM

**Comment by jmpolom** [comment]
I have a similar experience as @tobwen when attempting to run a podman container as a systemd service and setting `Type=notify` and using the `--sdnotify=conmon` option on the run command. However, the complaint from systemd when attempting to start the service unit is a little different. Also tried `--cgroups=split` just in case there was some issue there but the results were identical.

podman-dwspectrum.service:
```
[Unit]
Description=Podman for Digital Watchdog Spectrum
Wants=network.target
After=network-online.target

[Service]
WorkingDirectory=/tank/enc/dwspectrum
User=dwspectrum
Group=dwspectrum
ExecStartPre=/usr/bin/rm -f %T/%N.cid
ExecStartPre=/usr/bin/podman rm --ignore -f dwspectrum
ExecStart=/usr/bin/podman run --cidfile %T/%N.cid  --cgroups=no-conmon \
  --sdnotify=conmon \
  --detach \
  --pull=always \
  --log-driver=journald \
  --log-opt tag=dwspectrum \
  --name=dwspectrum \
  --env TZ=Americas/Detroit \
  --hostname=watchdog \
  --dns-search=subly.me \
  --publish 7001:7001 \
  --volume /tank/enc/dwspectrum/config:/config \
  --volume /tank/enc/dwspectrum/media:/media \
  --volume /tank/enc/dwspectrum/archive:/archive \
  docker.io/ptr727/dwspectrum-lsio:4.2.0.32660
ExecStop=/usr/bin/podman stop --ignore dwspectrum -t 10
ExecStopPost=/usr/bin/podman rm --ignore -f dwspectrum
ExecStopPost=/usr/bin/rm -f %T/%N.cid
TimeoutStopSec=3m
Type=notify
NotifyAccess=all

[Install]
WantedBy=multi-user.target default.target
```

systemd output when starting unit fails:
```
jon@arc:/etc/systemd/system$ sudo systemctl start podman-dwspectrum
Job for podman-dwspectrum.service failed because the service did not take the steps required by its unit configuration.
See "systemctl status podman-dwspectrum.service" and "journalctl -xe" for details.
```

journal excerpt from systemd status:
```
Aug 07 23:01:59 arc systemd[1]: Starting Podman for Digital Watchdog Spectrum...
Aug 07 23:02:04 arc systemd[1]: podman-dwspectrum.service: Failed with result 'protocol'.
Aug 07 23:02:04 arc systemd[1]: Failed to start Podman for Digital Watchdog Spectrum.
```

I am unclear if I'm either misusing the `--sdnotify=conmon` option or if it simply isn't doing what the documentation suggests it should (conmon sending systemd a "ready" notification). This is on podman 3.0.1 on Debian testing.

**Comment by vrothberg** [comment]
@jmpolom, this should with Podman v3.2+.  `type=notify` is now the default.

**Comment by jmpolom** [comment]
I experienced inconsistencies trying to get notify units working with podman 3.2.3 and conmon 2.0.29 on Fedora 34. The container image `docker.io/ptr727/dwspectrum-lsio` did not seem to work. The unit remained in the "activating" phase until a timeout was reached. However, the following unit worked:

```
[Unit]
Description=Podman test.service
Wants=network.target
After=network-online.target

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%N
Environment=XDG_RUNTIME_DIR=/run/user/1500
User=testuser
Group=testuser
Restart=never
ExecStartPre=-/usr/bin/podman rm --ignore -f test
ExecStart=/usr/bin/podman run --log-level=debug --sdnotify=conmon \
      --name test \
      docker.io/ubuntu:18.04 \
      sh -c "while true; do $(echo date); sleep 1; done"
ExecStop=/usr/bin/podman stop -t 10 test
ExecStopPost=-/usr/bin/podman rm --ignore -f test

Type=notify
KillMode=none
NotifyAccess=all

[Install]
WantedBy=multi-user.target
```

Any ideas why this admittedly trivial test unit works and the other does not? Are there some limitations to `--sdnotify=conmon` that aren't documented? Does function have some dependency on how the container is built or runs internally?

**Comment by vrothberg** [comment]
@jmpolom, my apologies.  Podman 3.3.x (not 3.2.x) changed to use `type=notify`.

**Comment by tobwen** [comment]
I'm lost now... need to try it for myself. I'm feeling so sad for all the _podman_ users, who are on v3.0.1 now with the release of Debian 11 :(

**Comment by jmpolom** [comment]
Looks like podman 3.3.x is still in rc status. Any package repos for Fedora that provide rc builds? Don't really feel like building myself to test this.

**Comment by rhatdan** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2021-94cbb4fa81

**Comment by vrothberg** [comment]
> I'm lost now... need to try it for myself. I'm feeling so sad for all the _podman_ users, who are on v3.0.1 now with the release of Debian 11 :(

@tobwen, I am extremely happy about Podman being part of a stable Debian release.  It has been over two years of work.  If some users desire more recent versions (of any software) they use Debian testing or experimental; or Fedora :^)

> @vrothberg were there other changes from 3.2.x to 3.3.x that would affect the discrepancies I noted above with the two different service units? I still don't understand why one works and the other times out. I definitely will test again with 3.3.x if I decide to try the rc or wait for a stable release however some context for what I experienced would be helpful.

Not to my knowledge.  The most notable change was to move the units over to `type=notify` and enforce `--sdnotify=conmon` by default.

**Comment by tobwen** [comment]
> I am extremely happy about Podman being part of a stable Debian release. It has been over two years of work. If some users desire more recent versions (of any software) they can use Debian testing or experimental; or Fedora :^)

https://github.com/vrothberg Meh, of course... I just mean all the awesome new features and bug fixes will only make it into the LTS version to a limited extent. Some users may not even know how fast and well _podman_ is constantly evolving.

**Comment by rhatdan** [comment]
I don't believe this is still an issue, closing.  Reopen if I am mistaken.
