### ISSUE TITLE
[conmon] pass custom `--log-opt`

### ISSUE THREAD

**Issue by tobwen** [containers/podman#10694]
/kind feature

**Description**
It would be nice to pass custom `--log-opt` to _conmon_. That way, I could finish https://github.com/containers/conmon/pull/273

**Example**
```
--log-opt="message-prefix={{.Name}}[{{.Tag}}]"
or
--log-opt="message-prefix=podman-nginx[test-build-20210706]"
```
to get
```
Jun 7 00:00:00 debian conmon[666]: podman-nginx[test-build-20210706] message
```

**Comment by haircommander** [comment]
would you be interested in submitting a patch :)

**Comment by tobwen** [comment]
> would you be interested in submitting a patch :)

Trust me, you really don't want me to mess around in _GO_. But I can give it a try.

**Comment by tobwen** [comment]
Easier than expected. Let me work on it:

https://github.com/containers/podman/blob/9b9bd9e0e7b72c91d8e60103e8da7999cefbc63d/pkg/bindings/containers/types.go#L13:6

**Comment by tobwen** [comment]
Sorry, I'm stuck here. Maybe I'll make it an environment variable for conmon or just apply the changes to my own builds.

**Comment by rhatdan** [comment]
Isn't this what tag does?

```
man podman run
...
   --log-opt=name=value
       Logging driver specific options.

       Set custom logging configuration. The following *name*s are supported:

       path: specify a path to the log file
           (e.g. --log-opt path=/var/log/container/mycontainer.json);

       max-size: specify a max size of the log file
           (e.g. --log-opt max-size=10mb);

       tag: specify a custom log tag for the container
          (e.g. --log-opt tag="{{.ImageName}}".
```

**Comment by tobwen** [comment]
> Isn't this what tag does?

No, see my report on conmon. The tag ends up in a journald variable, which is pretty costly to extract (see rsyslog docs on their journald module for example).

My approach just prefixes the important stuff to the syslog message, which is processed by default and at high performance.

But I am making use of the tag, of course. All that is missing is a switch to change the behavior to not break default logging (see the PR in conmon).

**Comment by mheon** [comment]
Passing new log options is pretty cheap on the Podman side, so long as Conmon is capable of interpreting them correctly (that would be a @haircommander question)

**Comment by tobwen** [comment]
> Passing new log options is pretty cheap on the Podman side, so long as Conmon is capable of interpreting them correctly (that would be a @haircommander question)

Pretty cheap for someone who's into it :-) I'd extent _Conmon_ of course. But I wanted to check if it's possible to get a _podmon_ switch at all. Without it, I would only patch it for my own use (because nobody else would be able to access it).

**Comment by tobwen** [comment]
@mheon
Could you guide me, how to integrate new log options (as you can see, I already tried) Then I could finish it and present it to you.

**Comment by tobwen** [comment]
Implementation is too complicated and the audience is too little. Closing.
