### ISSUE TITLE
protect pods from getting stopped by `podman stop --all`

### ISSUE THREAD

**Issue by tobwen** [containers/podman#10695]
/kind feature

**Description**
It would be nice to "protect" containers running in pods from `podman stop --all`.  The man page just says `Stop all running containers` on the `--all`, so I was a bit surprised that also the pods were stopped (which, of course, consist of containers).

**Example**
``podman pod start --protect foo``

**Comment by mheon** [comment]
Would a filter be sufficient here? Something like `podman stop --all --filter pod=none`?

**Comment by rhatdan** [comment]
I dont't think we can change the meaning of podman stop --all, but adding a filter would make some sense.

**Comment by tobwen** [comment]
Surely a filter would be useful. I just didn't assume that `podman stop` also stops containers in pods. I thought this was the task of `podman pod stop`.

For me, you don`t need to include the function. So you can close the request if it's up to me.

**Comment by mheon** [comment]
I think the intent of the `stop --all` command is to stop every container that is possible to stop. This includes every container in every pod, so as a side effect it does take pods down as well. Could be worth documented in the manpages? Maybe even a blog about how Podman treats pods - they're groups of containers, so all common container operations continue to work on containers in a pod, up to and including ones with `--all` attached.
