### ISSUE TITLE
stable podman 3.2 packages for CentOS 8

### ISSUE THREAD

**Issue by sappersd** [containers/podman#10702]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Hi! I see you released podman v3.2.1, but for CentOS 8 still doesn't exist stable v3.2.0 rpm (kubic repo). May be you know why? And when appropriate packages will appear?

**Comment by afbjorklund** [comment]
I don't think there are any packages for Ubuntu 20.04 LTS either, latest is v3.1.2.

**Comment by mheon** [comment]
@lsm5 PTAL

**Comment by lsm5** [comment]
there were some selinux issues on f33. Let me check how things go on centos 8 and update there.

ubuntu packages are in kubic testing. I'll run some quick tests there and release to the main kubic repo.

**Comment by qm78** [comment]
@rhatdan: could you explain, why this issue has been closed? Is Podman 3.2 on its way to Centos 8 stream? Thanks in advance!

**Comment by sappersd** [comment]
@lsm5 Are there any predictions for rpms publication?

**Comment by TomSweeneyRedHat** [comment]
No promises @sappersd , but fingers crossed, early July
