### ISSUE TITLE
Q: Which connection is the default; rootless or root? 

### ISSUE THREAD

**Issue by gbraad** [containers/podman#10707]
https://github.com/containers/podman/blob/a634b2cd5977c60f1907733efe07b61ba36271fb/pkg/machine/qemu/machine.go#L172-L180

**Comment by vrothberg** [comment]
@ashley-cui @baude PTAL

**Comment by ashley-cui** [comment]
@gbraad  rootless is the default, unless you have already set another connection to be the default via `podman system connection add`
