### ISSUE TITLE
podman-3.2.0-5.fc34 : "Error: cannot setup namespace using newuidmap: exit status 1" for unprivileged users

### ISSUE THREAD

**Issue by ianw** [containers/podman#10717]
/kind bug

**Description**

Running any un-privileged command on our Fedora 34 nodes, with and unmodified podman-3.2.0-5.fc34 results in 

```
[zuul@fedora-34-rax-ord-0025166927 ~]$ podman info
WARN[0000] The cgroupv2 manager is set to systemd but there is no systemd user session available 
WARN[0000] For using systemd, you may need to login using an user session 
WARN[0000] Alternatively, you can enable lingering with: `loginctl enable-linger 1000` (possibly as root) 
WARN[0000] Falling back to --cgroup-manager=cgroupfs    
Error: cannot setup namespace using newuidmap: exit status 1
```

The hosts have subuid

```
$ cat /etc/subuid
zuul:100000:65536
```

When I strace podman to see what newuidmap is doing I see

```
2294  openat(3, "uid_map", O_WRONLY)    = 5
2294  write(5, "0 1000 1\n1 100000 65536\n", 24) = -1 EPERM (Operation not permitted)
2294  write(2, "newuidmap: write to uid_map fail"..., 60) = 60
```

So I guess that shows ```newuidmap``` is there and working, the ```subuid``` seems to be read correctly, it's opening ```/proc/<pid>/uid_map``` -- but then can not write to it?

This is a slightly customised Fedora 34 image we use for CI testing.  But podman is simply installed from repos normally.  We are running a bit behind on updates to this image; the CI environment was previously working with Fedora 32 and nothing in the podman deployment bits have changed.  Very willing to believe it's something we've misconfigured, but I'm not sure what!

**Comment by rhatdan** [comment]
I would think there is something wrong with your install of newuidmap and newgidmap.

Could you try

dnf reinstall -y shadow-utils

And see if this fixes the problem.  I believe for some reason the newuidmap and newgidmap executables on your system no longer have the setfcap turned on.

**Comment by ianw** [comment]
@rhatdan thanks, a prescient insight!  reinstalling shadow-utils did seem to help, so it appears we have some capabilities issues to sort out
