### ISSUE TITLE
1GiB layer limit?

### ISSUE THREAD

**Issue by marcpawl** [containers/podman#10712]
/kind bug

**Description**

Images pull down using docker but fail with podman  Layers are very large and fail consistently at 1Gib.

**Steps to reproduce the issue:**

1.
'/usr/bin/podman'  'pull'  'XXX/YYY/ZZZ:cc1d905']
Trying to pull XXX/YYY/ZZZ:cc1d905...
Getting image source signatures
Copying blob 55521dc71959 skipped: already exists
Copying blob 0b0cbaa13104 skipped: already exists
Copying blob e8ddce32b711 skipped: already exists
Copying blob 2d473b07cdd5 skipped: already exists
Copying blob 99fd0fec0f5a skipped: already exists
Copying blob 057f1a5f99f8 skipped: already exists
Copying blob f0e51667e647 [========================>-------------] 1015.4MiB / 1.5GiB
Copying blob 85b2badac0ac done
Copying blob d16368f59c32 done
  unexpected EOF
Error: Error writing blob: error storing blob to file "/var/tmp/storage016327387/1": error happened during read: unexpected EOF

**Describe the results you received:**

Many times it fails at exactly 1.0GiB

**Describe the results you expected:**

Layer's are pulled like using docker.

**Additional information you deem important (e.g. issue happens only occasionally):**

Consistently fails.  Use artifactory as repository.

**Output of `podman version`:**
$ podman version
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.14.10
Built:        Tue Dec  8 09:37:43 2020
OS/Arch:      linux/amd64

```
(paste your output here)
```

**Output of `podman info --debug`:**
$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.27-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: 253f230b3f653ff8ed47efbfffa52f0ae3f1820d'
  cpus: 4
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: journald
  hostname: WWW
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.11.22-100.fc32.x86_64
  linkmode: dynamic
  memFree: 414691328
  memTotal: 16766525440
  ociRuntime:
    name: crun
    package: crun-0.17-1.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 8434483200
  swapTotal: 8455712768
  uptime: 49h 7m 51.11s (Approximately 2.04 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/VVV/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.4.0-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.4
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/VVV/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 34
  runRoot: /run/user/1000/containers
  volumePath: /home/VVV/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1607438263
  BuiltTime: Tue Dec  8 09:37:43 2020
  GitCommit: ""
  GoVersion: go1.14.10
  OsArch: linux/amd64
  Version: 2.2.1

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**
$ rpm -q podman
podman-2.2.1-1.fc32.x86_64
```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Latest version: yes
trouble shooting: yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
Thanks for reaching out, @marcpawl!

@mtrmac, have you seen that happening before?  I _suspect_ a transient network error.

**Comment by rhatdan** [comment]
Could you be running out of disk space?  I think we cause 2*Sizeofimage to be used?  Image space is being used in /var/tmp by default.

**Comment by mtrmac** [comment]
“error happened during read” means this is the registry client reporting, so not local storage.

For now I see no reason to doubt that “unexpected EOF” is exactly what happens, i.e. the registry (probably cleanly, not 100% sure about this part) closes a connection before sending all of the data. That could be a timeout, some kind of proxy (we’ve had reports of environments that let through connections with Docker’s User-Agent: but no other), or perhaps a server-side setting.

**Comment by vrothberg** [comment]
@marcpawl, can you elaborate a bit on the registry that you attempt to pull from?  What's your networking environment?  Is there a proxy in between?

**Comment by eMGabriel** [comment]
@marcpawl could you please share the /tmp and /var/tmp entries of your /etc/fstab file? Because you mentioned that error comes at the 1GB limit, I think that /var/tmp is mounted to /tmp which maybe a 1GB size tmpfs filesystem which gets full.

**Comment by rhatdan** [comment]
Since we have had no feedback in the past month, I am going to close,  If more feedback happens we will reopen.

**Comment by a85302543** [comment]
Im facing the same problem here. when using docker pull it work find but podman will failed.

**Comment by mheon** [comment]
Can you provide additional details - what image, where are you pulling from, output of a `podman pull --log-level=debug` on the image?
