### ISSUE TITLE
stat /home/USER1/.config/containers/storage.conf: permission denied"

### ISSUE THREAD

**Issue by statiksof** [containers/podman#10725]
Any idea of what causing this?

`stat /home/USER1/.config/containers/storage.conf: permission denied"`

Actually I started the container as USER 2 and have no config for that user, so why podman is trying to `stat`
 into other USER directory.

**Comment by mheon** [comment]
Did you copy any configurations from the first user? Or, potentially, do a `sudo` or `su` from the other user (these will retain environment variables from the first user in some cases, so we get a bad XDG_RUNTIME_DIR, for example)?

**Comment by rhatdan** [comment]
Usually this is $HOME or $XDG_* directories pointing at the previous users information, when you su or sudo to a different user.

**Comment by statiksof** [comment]
@rhatdan @mheon thank you for your quick replies. Is there a way to set those variables in real time? I mean something like:

`podman exec --env XDG_=... `

I am already using --root, it solved me other issues but still having this one.

**Comment by mheon** [comment]
You’ll need to set them in your shell before calling ‘podman exec’.

**Comment by vrothberg** [comment]
@statiksof, make sure to use the `--login` flag when using sudo or su.  That will setup the required login session.
