### ISSUE TITLE
Exposing ports on an internal network

### ISSUE THREAD

**Issue by Roxolasu** [containers/podman#10729]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm trying to deny internet / network access while exposing some ports.

**Steps to reproduce the issue:**

1. `sudo podman network create --internal internal-net`
2. `sudo podman run --network=internal-net -dt -p 8080:80 docker.io/library/httpd`
3. `sudo podman run -dt -p 9080:80 docker.io/library/httpd`
4. `curl localhost:8080`
5. `curl localhost:9080`

**Describe the results you received:**

localhost:9080 is accessible, localhost:8080 fails: 
`curl: (7) Failed to connect to localhost port 8080: Connection refused`

**Describe the results you expected:**
localhost:8080 should also be accessible

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 3.0.1
```

**Output of `podman info --debug`:**
(ran as rooot)
```
host:
  arch: amd64
  buildahVersion: 1.19.6
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 4
  distribution:
    distribution: debian
    version: "11"
  eventLogger: journald
  hostname: xyz
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.0-7-amd64
  linkmode: dynamic
  memFree: 223330304
  memTotal: 1541668864
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 309h 56m 28.47s (Approximately 12.88 days)
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 2
    stopped: 2
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.9
  OsArch: linux/amd64
  Version: 3.0.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/testing,now 3.0.1+dfsg1-2+b2 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
KVM VM

**Comment by rhatdan** [comment]
@Luap99 @mheon PTAL

**Comment by mheon** [comment]
First question is, does this work with Docker? To me, internal means
internal and an internal network should not have any access to the outside.

From a technical perspective, this also sounds completely out of what CNI
offers now. We’d either need a rewritten version of the Portmap plugin, or
to use slurp.

**Comment by Roxolasu** [comment]
Docker fails with the same error.

I guess this depends on the definition of "internal". Comparing the documentation of --internal, the intent of docker seems clearer to me.

- Docker: Restrict external access **to** the network
- Podman: Restrict external access **of** this network

I was hoping it might be supported by CNI, as there is this snipped in the internal-net:
`            {
                "capabilities": {
                    "portMappings": true
                },
                "type": "portmap"
            },
`


Do you have any other ideas how to expose ports without allowing internet access? It might be possible to use macvlan to attach the network to an isolated bridge, but macvlan is deprecated.

**Comment by basilgello** [comment]
@Roxolasu I do achieve the same by running iptables in createContainer OCI hook. This works most of the time in rootless mode with Slirp4netns. However I decided to add new "netwprksetup" extension hook exactly for that purpose (see #10704). If you run containers in non-root mode, jailed process won't be able to alter iptables rules within the network namespace.

If you need an example of how I do it, let me know.﻿

**Comment by Roxolasu** [comment]
@basilgello An example would be much appreciated!

**Comment by basilgello** [comment]
@Roxolasu here you go:

First, you define the following the script in `/etc/containers/restrict-outbound-access` and `chmod 0755` it:

```shell
#!/bin/sh

IPTABLES=$(command -v iptables)
IP6TABLES=$(command -v ip6tables)

if [ -z "$IPTABLES" ] || [ -z "$IP6TABLES" ]; then
	[ -x "/sbin/iptables" ] && IPTABLES="/sbin/iptables"
	[ -x "/usr/sbin/iptables" ] && IPTABLES="/usr/sbin/iptables"

	[ -x "/sbin/ip6tables" ] && IP6TABLES="/sbin/ip6tables"
	[ -x "/usr/sbin/ip6tables" ] && IP6TABLES="/usr/sbin/ip6tables"
fi

while read _1
do
	"$IPTABLES" -A OUTPUT -d "$_1" -j ACCEPT
done <<.p
$(LC_ALL=C ip addr | awk '
$1 == "inet" && !($2 ~ /^127./) {
	sub(/\/.+/, "", $2)
	ips[$2]=1
}

END {
	for (ip in ips) {
		print ip
	}
}
')
.p

"$IPTABLES" -A OUTPUT -j DROP
```

It allows outgoing traffic only to Slirp4netns gateway to be able to forward traffic between your mapped ports and jailed app but nothing more.

Then, define an OCI hook in `/etc/containers/oci/hooks.d/restrict-internal-networks.json`:

```json
{
  "version": "1.0.0",
  "hook": {
    "path": "/etc/containers/restrict-internal-networks"
  },
  "when": {
    "annotations": {
      "restrict-internal-networks": "true"
    }
  },
  "stages": ["createContainer"]
}

```

Finally, as root start the Busybox official container, for example:

```shell
podman run \
	--rm -it \
	--annotation "restrict-internal-networks=true" \
	--subuidname roxolasu --subgidname roxolasu --user 1000 \
	-p 8081:8080 \
	docker.io/library/busybox \
	/bin/sh
```

and inside the container, check that nothing is accessible:

```shell
busybox wget http://104.18.7.156
```

but you can start busybox httpd on port 8080:

```shell
cd /tmp
echo w00f > /tmp/index.html
busybox httpd -v -f -p 8080
```

then detach from container pressing Ctrl+P followed by Ctrl+Q and check the server replies with "w00f" on host port 8081:

```shell
curl -v http://ip:8081
...
w00f
```
﻿

**Comment by Roxolasu** [comment]
Wow, thank you!

**Comment by baude** [comment]
can we close this?

**Comment by rhatdan** [comment]
Reopen if you believe this still needs to be fixed.

**Comment by Roxolasu** [comment]
It would certainly be nice to have a simple and default way to prevent outbound access from a container. This might be better suited for a new feature request. What would you prefer, if any?

**Comment by rhatdan** [comment]
You want to prevent a container from using the network?

--net=none

Or do you want something else?

**Comment by Roxolasu** [comment]
I want to prevent a container from using the network *while having exposed ports*.

The host should be able to access the exposed ports, the container should be prevent from accessing any outside its pod.

**Comment by basilgello** [comment]
If the pod must be accessed, too, then create a private network and attach to it. My solution is for containers that need to have Internet-only connectivity without letting them reach infrastructure :)

**Comment by Roxolasu** [comment]
@basilgello: What do you mean by "private network"? 

- If it is `--internal `: it doesn't work, see my first post ;) 
- if it is -o parent=privateBridge: I assumed macvlan was deprecated completely, upon rereading the manpage it seems only the **option** --macvlan is deprecated. If macvlan stays, its exactly what I am looking for.

**Comment by basilgello** [comment]
Either macvlan or `--network=private` or `--network=container:id`

**Comment by lukasmrtvy** [comment]
> @Roxolasu here you go:
> 
> First, you define the following the script in `/etc/containers/restrict-outbound-access` and `chmod 0755` it:
> ...


Thanks. 
This can work only for privileged users that are able to manipulate with iptables, right? ( Has `roxolasu` user these permissions ? )
I am trying to use `--userns=auto`, but getting `Error: OCI runtime error: error executing hook `/etc/containers/restrict-outbound-access` (exit code: 4)`

**Comment by rhatdan** [comment]
yes a unpriv user is not allowed to modify iptables.

**Comment by lukasmrtvy** [comment]
@rhatdan is there any workaround? (the bridge is a no-go for me as these should be completely isolated in terms of network connectivity ) 

Seems that OCI hook can not be triggered as another user ( root )

**Comment by rhatdan** [comment]
Did you run as root with --userns=auto and it failed?

**Comment by lukasmrtvy** [comment]
Yes, I believe because of this `Fatal: can't open lock file /run/xtables.lock: Permission denied`.

EDIT:
Its working with `iptables-nft`, as it does not require /run/xtables.lock locking file.

**Comment by rhatdan** [comment]
So it is not allowed to create /run/xtables.lock, because it is running in a user namespace?
