### ISSUE TITLE
push and pull from tarball file

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#10730]
The documentation of [buildah push](https://github.com/containers/buildah/blob/master/docs/buildah-push.md) offers as export
```
oci:path:tag An image tag in a directory compliant with "Open Container Image Layout Specification" at path.

oci-archive:path:tag An image tag in a tar archive compliant with "Open Container Image Layout Specification" at path.
```
The documentation of [podman push](https://github.com/containers/podman/blob/master/docs/source/markdown/podman-push.1.md) contains:
```
oci-archive:path:tag An image tag in a directory compliant with "Open Container Image Layout Specification" at path.

$ podman push myimage oci-archive:/tmp/myimage
```
It does not offer just **oci:**.

The documentation of [buildah pull](https://github.com/containers/buildah/blob/master/docs/buildah-pull.md) offers as import
```
oci:path:tag** An image tag in a directory compliant with "Open Container Image Layout Specification" at path.

oci-archive:path:tag An image tag in a directory compliant with "Open Container Image Layout Specification" at path.
```
Finally the documentation of [podman pull](https://github.com/containers/podman/blob/master/docs/source/markdown/podman-pull.1.md) offers:
```
oci-archive:path:tag An image tag in a directory compliant with "Open Container Image Layout Specification" at path.

$ podman pull oci-archive:/tmp/myimage
```
Corollary:

buildah push can export as directory and as tar file.  The former is perfomed with **oci:**, the latter with **oci-archive**.  podman push has the option with the same name **oci-archive**, but different semantic: it exports as directory.  podman push cannot export in tar file.

Neither buildah nor podman can import (pull) from tarball file.

**Comment by vrothberg** [comment]
Thanks for pointing that out, @dilyanpalauzov!

Podman and Buildah support the exact same transports for push and pull.  It seems like a doc-only issue.  My proposal would be to point to the `containers-transports` man page instead of listing them in buildah/podman push/pull.

@mtrmac @nalind @TomSweeneyRedHat WDYT?

**Comment by mtrmac** [comment]
Yup, the transport:… format should have consistent semantics everywhere, if at all possible.

Linking to the primary transports man page would make it easier to maintain the reference as transports change (though it might well make sense to directly include some frequently-used examples, specifically chosen for a specific subcommand).

**Comment by rhatdan** [comment]
SGTM
