### ISSUE TITLE
Podman not able to start pod from jenkins 

### ISSUE THREAD

**Issue by pyronaid** [containers/podman#10738]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Hi all, let me describe better what happened. Currently I have a rootless user for podman called myuserpod. In addition to that I have on the same machine also a jenkins user that have some sudo privileges to launch podman command as myuserpod. 
jenkins ALL=(myuserpod) NOPASSWD: /usr/bin/podman
What happened now is that, launching a pod using the command:
#podman play kube pod_mypod.yaml --> directly from myuserpod shell work fine 
#sudo -u myuserpod /usr/bin/podman play kube pod_mypod.yaml --> from jenkins pipeline start the pod but it ends in error with the following sentences:
- /bin/sh: 1: chmod: Transport endpoint is not connected
- /bin/sh: 1: ./startmyscript.sh: Transport endpoint is not connected

here below the contents of pod_mypod.yaml
######################################################
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-pod
  name: my-pod
spec:
  restartPolicy: Never

  containers:
    - name: my_container
      image: localhost/myimage:1.0.2.6
      tty: true
      volumeMounts:
        - name: bigstorage
          mountPath: /Big-Storage
      ports:
        - containerPort: 1521
          hostPort: 1597
        - containerPort: 10443
          hostPort: 10999
        - containerPort: 12443
          hostPort: 12998
      command: [ "/bin/sh", "-c" ]
      args:
        - echo starting;
          ulimit -a;
          ls -latr ./startmyscript.sh;
          chmod +x ./startmyscript.sh;
          ./startmyscript.sh;

  volumes:
    - name: bigstorage
      persistentVolumeClaim:
        claimName: bigstorage

######################################################

**Steps to reproduce the issue:**

1. Launch the command sudo -u myuserpod /usr/bin/podman play kube pod_mypod.yaml from jenkins pipeline 

2.

3.

**Describe the results you received:**
- /bin/sh: 1: chmod: Transport endpoint is not connected
- /bin/sh: 1: ./startmyscript.sh: Transport endpoint is not connected

**Describe the results you expected:**
Everything works fine. Pod and container should run without errors

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 3.0.2-dev
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.8
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.26-3.module+el8.4.0+11311+9da8acfb.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: a35bb9ea67d5a83c7da53202f2fcd505c036d29c'
  cpus: 2
  distribution:
    distribution: '"rhel"'
    version: "8.4"
  eventLogger: file
  hostname: xxxxxxxxxx
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 502
      size: 1
    - container_id: 1
      host_id: 493216
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1006
      size: 1
    - container_id: 1
      host_id: 493216
      size: 65536
  kernel: 4.18.0-305.3.1.el8_4.x86_64
  linkmode: dynamic
  memFree: 6461902848
  memTotal: 12360126464
  ociRuntime:
    name: runc
    package: runc-1.0.0-73.rc93.module+el8.4.0+11311+9da8acfb.x86_64
    path: /usr/bin/runc
    version: |-
      runc version spec: 1.0.2-dev
      go: go1.15.13
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /tmp/podman-run-1006/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.4.0+11311+9da8acfb.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 2147479552
  swapTotal: 2147479552
  uptime: 1h 55m 56.85s (Approximately 0.04 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/myuserpod/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 3
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.4.0-3.module+el8.4.0+11311+9da8acfb.x86_64
      Version: |-
        fusermount3 version: 3.2.1
        fuse-overlayfs: version 1.4
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /var/lib/containers/myuserpod/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 19
  runRoot: /tmp/containers-user-1006/containers
  volumePath: /var/lib/containers/myuserpod/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1623138726
  BuiltTime: Tue Jun  8 09:52:06 2021
  GitCommit: ""
  GoVersion: go1.15.13
  OsArch: linux/amd64
  Version: 3.0.2-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.0.1-7.module+el8.4.0+11311+9da8acfb.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

YES

**Additional environment details (AWS, VirtualBox, physical, etc.):**

ulimit -a myuserpod
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 46997
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 262144
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 46997
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

ulimit -a jenkins
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 46997
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 262144
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 46997
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by pyronaid** [comment]
I discovered something new. If I add a sleep 3m at the end of jenkins pipeline, the pod work fine during all the 3minutes. 
This means that some processes died together with the jenkins bash launching the podman commands invalidating the pod status. Is there any possible solution to this behaviour?

**Comment by mheon** [comment]
The first bit that is suspicious to me is the `sudo -u`. Podman requires a login session be available for the user we are run as, and sudo usually does not do this. You can try doing a `loginctl enable-linger` for the user you are running Podman as.

**Comment by pyronaid** [comment]
Hi mheon, many thanks for your feedback.
I've tried to launch the command: "loginctl enable-linger jenkins"
In addition to that I've removed the sudo on the second user and configured the user jenkins as podman user as well in order to try to understand the core issue.
Unfortunately the issue remain. Until the jenkins pipeline is running the pod started and works well. As soon as it ends the pod lose all the references related to filesystem (it is not able to find any path or directory and show the error Transport endpoint is not connected). 
If later, using always the jenkins user, I stop and restart the pod, everything works fine again.
I do not know why but the end of the jenkins bash pipeline where the pod is started put something in bad status on the respect of the filesystem.

I tried also to see if some process ends after the end of the jenkins pipeline bash, but none do.

**Comment by pyronaid** [comment]
Does the command "loginctl enable-linger jenkins" need a reboot to work?

**Comment by mheon** [comment]
No.

Is the Jenkins pipeline doing anything with the filesystem - NFS mounts, maybe?

**Comment by pyronaid** [comment]
I do not think so but let me put my jenkinsfile here below just to make the context clearer






pipeline {
    agent any
    tools { 
        //maven 'Maven_3.6.3'
        //jdk 'jdk_1.8.0_292'
        maven 'localMAVEN'
        jdk 'localJDK'
       }
	environment {
		//Use Pipeline Utility Steps plugin to read information from pom.xml into env variables
		IMAGE = readMavenPom().getArtifactId()
		VERSION = readMavenPom().getVersion()
		WORKSPACE = "${WORKSPACE}"
		JAVA_HOME_TARGET= "/etc/alternatives/java_sdk_1.8.0"
    }

    stages {
        stage('clean') {
            steps {
                sh 'mvn clean'
            }
        }

        stage('build') {
            steps {
                withMaven(
                    // Maven installation declared in the Jenkins "Global Tool Configuration"
                    maven: 'localMAVEN', // (1)
                    // Use `$WORKSPACE/.repository` for local repository folder to avoid shared repositories
                    // mavenLocalRepo: '.repository', // (2)
                    // Maven settings.xml file defined with the Jenkins Config File Provider Plugin
                    // We recommend to define Maven settings.xml globally at the folder level using
                    // navigating to the folder configuration in the section "Pipeline Maven Configuration / Override global Maven configuration"
                    // or globally to the entire master navigating to  "Manage Jenkins / Global Tools Configuration"
                    mavenSettingsConfig: 'b6139bf3-60c3-4d61-8d31-3f88e72fc548' // (3)
                ){
                    sh 'mvn compile'
                    sh 'mvn package'
                }
            }
        }

        stage('podman') {
            steps {

                sh '''#!/bin/bash -x
                   targetname=igfs3dsserver

                   #see if the pod already exist
                   ###############################
                   ###############################
                   ###############################
                   ###############################
                   counterPods=$(podman pod list | grep -c ${targetname})
                   if [[ $counterPods > 1 ]];then
                   	echo "Impossible to discriminate which pod to refresh. Use a more detailed name"
                   	exit 1
                   fi
                   if [[ $counterPods == 1 ]];then
                   	echo "Before to create the fresh Pod we will going to delete the old one"
                   	podman pod stop ${targetname}-pod
                   	podman pod rm ${targetname}-pod
                   fi

                   #see if the container already exist
                   ###############################
                   ###############################
                   ###############################
                   ###############################
                   counterContainers=$(podman container list -a | grep -c ${targetname})
                   if [[ $counterContainers > 1 ]];then
                   	echo "Impossible to discriminate which container to refresh. Use a more detailed name"
                   	exit 1
                   fi
                   if [[ $counterContainers == 1 ]];then
                   	echo "In this phase no container should be found. Investigate pls"
                   	exit 1
                   fi

                   #see if the image already exist
                   ###############################
                   ###############################
                   ###############################
                   ###############################
                   counterImages=$(podman image list --filter reference=*${targetname}*${VERSION}* --format "table {{.ID}}" --noheading | wc -l)
                   if [[ $counterImages -ge 1 ]];then
                    for idImage in $(podman image list --filter reference=*${targetname}*${VERSION}* --format "table {{.ID}}" --noheading); do
                        echo "Before to create the fresh Image we will going to delete the old one"
                        podman image rm $idImage
                    done
                   fi

                   ###############################
                   ###############################
                   ###############################
                   ###############################
                   sed -i "s/#VERSION/$VERSION/g" pod_${targetname}.yaml
                   sed -i "s/#IMAGE/$IMAGE/g" pod_${targetname}.yaml
                   podman build . --format docker --tag ${targetname}:${VERSION} --build-arg IMAGE=${IMAGE} --build-arg VERSION=${VERSION} --build-arg TARGETNAME=${targetname}
                   podman play kube pod_${targetname}.yaml
                   touch /var/lib/jenkins/basePodTmpl/fileSemaphores/semaphore_${targetname}_${VERSION}.sem

                '''
            }
        }
    }
}

**Comment by pyronaid** [comment]
The yaml instead start from a local image that make some activities like:


RUN mkdir -p /Local-Storage/${IMAGE}/${VERSION}
COPY ./package/${IMAGE}-${VERSION}.tar.gz /Local-Storage/${IMAGE}/${VERSION}/
COPY ./cfg/online/igfs.properties /Local-Storage/${IMAGE}/${VERSION}/
WORKDIR /Local-Storage/${IMAGE}/${VERSION}
RUN tar -xvzf ${IMAGE}-${VERSION}.tar.gz
RUN cp igfs.properties cfg/online/igfs.properties

**Comment by giuseppe** [comment]
since the user myuserpod is used to launch containers, don't you need something like `loginctl enable-linger myuserpod` instead of using the `jenkins` user?

**Comment by pyronaid** [comment]
hi giuseppe, after the suggest of mheon i removed the intermediate layer of myuserpod, using only jenkins user to execute podman commands too.

**Comment by giuseppe** [comment]
can you verify if there is the user systemd session running at any time? Even after the jenkins user logs out?

**Comment by rhatdan** [comment]
Since no feedback in a month, I figure @pyronaid has fixed his issue. CLosing.

**Comment by rvalenca** [comment]
Just to add a "happy end" here:

I had the same issue, and the problem is that when a Jenkins job finishes, it makes sure that any process started during that job also gets killed. This is the default behavior.

If you want to circumvent that, you can set an env var (BUILD_ID) just before starting the desired process.
Ex.:
`BUILD_ID=dontKillMe podman run -d ...`

This is also described here:
https://stackoverflow.com/questions/39169457/how-to-tell-jenkins-not-to-kill-processes-after-successful-execution-of-job-in-m
