### ISSUE TITLE
Add website to GitHub description

### ISSUE THREAD

**Issue by rugk** [containers/podman#10746]
IMHO the best would be to just click on the wheel in the “About” section of your repository and add the following website link:
https://podman.io/

![image](https://user-images.githubusercontent.com/11966684/122830034-0f8bd500-d2e8-11eb-8b28-c1b595e3a4cf.png)

Edit: As far as I see,. it’s also not linked in the Readme anywhere.

**Comment by vrothberg** [comment]
Thanks for reaching out!

It's linked in the README but rather in the middle of the document: https://github.com/containers/podman/blob/master/README.md#podman-information-for-developers

Maybe we should drop a link at the top of the README?

Putting the website in the description sounds good to me.

@mheon @TomSweeneyRedHat PTAL

**Comment by mheon** [comment]
SGTM

**Comment by TomSweeneyRedHat** [comment]
I've added the website to the description of the site (Buildah's too).  I don't think I want to move the site up any in the README.md as it stands. With the link front and center at the top of the page, I don't think that part is necessary.  Thanks for the idea!
