### ISSUE TITLE
set signed-by via environment variable

### ISSUE THREAD

**Issue by volker-raschek** [containers/podman#10750]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Hello, 
I have set up a sigstore after the following post.

https://github.com/containers/podman/blob/master/docs/tutorials/image_signing.md

What bothers me as a developer is that I have to specify the gpg key every time I want to sign images. In the documentation I did not find an environment variable that sets the flag `--sign-by` with the value automatically if available. So now I always have to set the flag for build or push operations. By the way, the same is true for skopeo. 

http://docs.podman.io/en/latest/markdown/podman-build.1.html#sign-by-fingerprint
http://docs.podman.io/en/latest/markdown/podman-push.1.html#sign-by-key

Could you add such an option?

**Comment by vrothberg** [comment]
Thanks for reaching out, @volker-raschek!

@mtrmac @rhatdan PTAL

Maybe something for registries.conf or containers.conf?

**Comment by mtrmac** [comment]
Not `registries.conf`, this is a very per-user configuration.

`containers.conf` might make sense — but do you _really_ want to sign every single image ever pushed from that user account? Is it reasonable to sign every accidental testing one-off throw-away images, possibly with known vulnerabilities, during some experimentation? (Is that user account a bot that ensures this never happens?) Would this apply to every single `skopeo copy`? (It feels risky to have `skopeo copy` automatically sign if the destination supports that, and _silently_ not sign if the destination doesn’t, so with this option many `skopeo copy` commands would just break.)

Or is the proposal something like `--sign-by default` just to avoid writing a key ID, but still explicitly opting in to signing? 

(At _some_ point all these kind of RFEs are universally solved by shell aliases without adding extra configuration options to every single command out there. Alternatively, turn more of the build process into a script — a single `make release` will beat anything we can come up with around `podman build $args && podman push $args` every time, after a one-time investment.)

**Comment by rhatdan** [comment]
@mtrmac has some great points, @volker-raschek are you fine with this?

**Comment by volker-raschek** [comment]
Hi @mtrmac and @rhatdan, 

> but do you really want to sign every single image ever pushed from that user account?

yes I would like to sign every image pushed by a user account. Maybe a little more on the background. The problem with signing does not only affect the developer, who has to set the flag manually, but also the user of a jumping station. 

The jumping station is documented and rolled out as part of the infrastructure using Ansible. Images that are deployed via the jumping station should receive a signature. Whether the signing key is set as an environment variable or as a configuration parameter is less important. We simply pursue the goal of not having to set the option on every call. 

> Is it reasonable to sign every accidental testing one-off throw-away images, possibly with known vulnerabilities, during some experimentation?

We are aware that signing test images is not absolutely necessary, especially if it contains vulnerbilities. I definitely agree with you there. Our goal is much more to be able to track who signed the image and what processes it went through.  

> Alternatively, turn more of the build process into a script — a single make release will beat anything we can come up with around podman build $args && podman push $args every time, after a one-time investment.)

I definitely agree with you there. But that only applies to projects or much more companies that have already opened up to the extent that teams can deliver their releases directly. This is not always the case. Often applications are part of an ecosystem, which has to be tested separately as a whole. Only after testing the ecosystem, a job is triggered to publish container images in specific versions and make them available to users. This is where the Jumping Station with user comes into play, which signs the images again. Users usually trust the GPG key from the Jumping Station. The Jumping Station only trust signed images from the developers or ci nodes.

**Comment by mtrmac** [comment]
> Only after testing the ecosystem, a job is triggered to publish container images in specific versions and make them available to users.

Wouldn’t that job, or its part that runs on the Jumping Station, be a natural place to add the `--sign-by` parameter, then? I’m guessing whatever happens on that station is mostly intended to be a consistent deterministic process. If the inputs are (image determined to be trusted, destination), a `transfer-image $source $destination` script can do that in one step without users _manually_ typing `skopeo copy docker://… docker://…`, `podman build … && podman push …` , or whatever it is.

Especially if you need to turn a sigstore-staging directory into a published sigstore on a server, automating the sign+publish step seems much more efficient and less error-prone than doing that manually by typing commands.

**Comment by volker-raschek** [comment]
> Wouldn’t that job, or its part that runs on the Jumping Station, be a natural place to add the `--sign-by` parameter, then?

Yes definitively, when you should add the flag and define the used gpg key inside the `transfer-image $source $destination` script, but we don't want to define the gpg key inside the script. 

The jumping station example was simply another example where we could have used the ability for the GPG key to be configurable. 

The GPG key is not defined in a script or specified by flag. It is much more part of ansible and available as a vault. Ansible has the advantage that it documents itself using the YAML notation. There you could include the GPG key for creating signatures. The jumping station would be reproducible using the playbook. 

> Especially if you need to turn a sigstore-staging directory into a published sigstore on a server, automating the sign+publish step seems much more efficient and less error-prone than doing that manually by typing commands.

Yes, that is more of a fundamentally still open point. Which I have at least not yet fully understood. The signatures are in the staging directory, if someone has signed an image. Is there a nicer way to copy signatures from a staging to a public sigstore? 

At the moment our workflow would be to copy the signatures via `scp` or `rsync` to a directory that is simply accessible through an nginx webserver via https. 

Is there a way, service or API, which automatically sends the signature to the defined sigstore via https on a podman or skopeo push? 

This would at least round up the workflow in some points.

**Comment by mtrmac** [comment]
> Is there a way, service or API, which automatically sends the signature to the defined sigstore via https on a podman or skopeo push?

Using what protocol??! So, no.

**Comment by rhatdan** [comment]
I believe that this can be done with scripting and not necessary to build it into the tools.  Reopen if you disagree.
