### ISSUE TITLE
Set docker_host environmental variable to rootless podman socket via podman-docker packet

### ISSUE THREAD

**Issue by MartinX3** [containers/podman#10757]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Please set the docker_host env variable and let it point to the rootless podman socket, now since podman officially supports rootless docker-compose.
Maybe via config file to choose between root and rootless socket.

**Steps to reproduce the issue:**

1. Try to boot a docker-compose service without setting docker_host by yourself

**Describe the results you received:**

Cryptic permission denied errors.

**Describe the results you expected:**

My working services.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.2.1
API Version:  3.2.1
Go Version:   go1.16.5
Git Commit:   152952fe6b18581615c3efd1fafef2d8142738e8
Built:        Thu Jun 17 12:55:05 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.21.0
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon ist in conmon 1:2.0.29-1 enthalten
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 7e6de6678f6ed8a18661e1d5721b81ccee293b9b'
  cpus: 8
  distribution:
    distribution: endeavouros
    version: unknown
  eventLogger: journald
  hostname: deus-ex-machina
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.12.12-zen1-1-zen
  linkmode: dynamic
  memFree: 529506304
  memTotal: 33381634048
  ociRuntime:
    name: crun
    package: /usr/bin/crun ist in crun 0.20.1-1 enthalten
    path: /usr/bin/crun
    version: |-
      crun version 0.20.1
      commit: 38271d1c8d9641a2cdc70acfa3dcb6996d124b3d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns ist in slirp4netns 1.1.11-1 enthalten
    version: |-
      slirp4netns version 1.1.11
      commit: 368e69ccc074628d17a9bb9a35b8f4b9f74db4c6
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 28622974976
  swapTotal: 36722176000
  uptime: 3h 1m 20.6s (Approximately 0.12 days)
registries: {}
store:
  configFile: /home/martin/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /home/martin/.local/share/containers/storage
  graphStatus:
    Build Version: 'Btrfs v5.12.1 '
    Library Version: "102"
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  volumePath: /home/martin/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.1
  Built: 1623927305
  BuiltTime: Thu Jun 17 12:55:05 2021
  GitCommit: 152952fe6b18581615c3efd1fafef2d8142738e8
  GoVersion: go1.16.5
  OsArch: linux/amd64
  Version: 3.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ pacman -Q --info podman
Name                     : podman
Version                  : 3.2.1-1
Beschreibung             : Tool and library for running OCI-based containers in pods
Architektur              : x86_64
URL                      : https://github.com/containers/libpod
Lizenzen                 : Apache
Gruppen                  : Nichts
Stellt bereit            : Nichts
Hängt ab von             : cni-plugins  conmon  containers-common  device-mapper  iptables
                           libseccomp  runc  slirp4netns  libsystemd  fuse-overlayfs
                           libgpgme.so=11-64
Optionale Abhängigkeiten : podman-docker: for Docker-compatible CLI [Installiert]
                           btrfs-progs: support btrfs backend devices [Installiert]
                           catatonit: --init flag support [Installiert]
                           crun: support for unified cgroupsv2 [Installiert]
Benötigt von             : podman-compose-git  podman-docker
Optional für             : Nichts
In Konflikt mit          : Nichts
Ersetzt                  : Nichts
Installationsgröße       : 72,35 MiB
Packer                   : David Runge <dvzrv@archlinux.org>
Erstellt am              : Do 17 Jun 2021 12:55:05 CEST
Installiert am           : Di 22 Jun 2021 18:24:10 CEST
Installationsgrund       : Ausdrücklich installiert
Installations-Skript     : Nein
Verifiziert durch        : Signatur
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
N/A

**Comment by vrothberg** [comment]
Thanks for reaching out!

Please reach out to your distribution if you want this solved in the podman-docker package.

**Comment by rhatdan** [comment]
The current podman-docker package should be setting up a symbolic link at boot time betweek /run/docker.sock->/run/podman/podman.sock

**Comment by MartinX3** [comment]
That's true
But what's the best way for the rootless way?
Filling the docker_host env in profile.d or giving an option in a settings file to redirect it to the rootless socket?

**Comment by rhatdan** [comment]
Yes profile.d is probably best.  Since mimicking the docker.sock in rootless mode, was never thought of.

Which socket does compose attempt to write to in rootless mode? Does it still try /var/run/docker.sock, or does it try a user specific socket?

**Comment by MartinX3** [comment]
Good to know

First it looks for docker_host, then it wants to use the root docker socket.
But maybe my informations are wrong.

Since docker also has a (for me not good working if I use networks) rootless mode, I wonder how docker-compose handles it.

But I think the socket can get changed here
https://wiki.archlinux.org/title/docker#Daemon_socket

And here it is further described I see now
https://wiki.archlinux.org/title/docker#Docker_rootless

maybe the podman docs need an update, since docker-compose rootless is now officially supported.
I never thinked before about looking in the docker rootless docs for the podman rootless usage.

**Comment by mheon** [comment]
When I look up rootless docker-compose guides, they don't do anything special to instruct compose to point to a different socket. This makes me think that compose is smart enough to know it's not running as root and use the rootless Docker socket, but this needs to be confirmed manually.

If this is true, perhaps it's enough to have a symlink from the Docker socket at `$XDG_RUNTIME_DIR/docker.sock` to Podman's non-root socket. I don't think we can do this in the `podman-docker` package automatically, but a single `ln -s` command is not a difficult addition to our rootless tutorial?
