### ISSUE TITLE
podman rootless support

### ISSUE THREAD

**Issue by Mingli-Yu** [containers/podman#10769]
It works with root, but throw below error with non-root user.
$ podman version
ERRO[0000] cannot find UID/GID for user test: open /etc/subuid: no such file or directory - check rootless mode in man pages. 
WARN[0000] using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding sub*ids 
Error: kernel does not support overlay fs: 'overlay' is not supported over <unknown> at "/home/test/.local/share/containers/storage/overlay": backing file system is unsupported for this graph driver

**Comment by trusch** [comment]
Please have a look at https://github.com/containers/podman/blob/master/docs/tutorials/rootless_tutorial.md

It explains how to setup your system so that rootless podman can work. In the end it will boil down to create /etc/subuid and /etc/subgid with correct values, so its an easy thing to do.

**Comment by rhatdan** [comment]
Continue to ask questions here if you have problems, but I am closing this issue.

**Comment by Mingli-Yu** [comment]
$ cat /etc/subuid
test:10000:65536
$ cat /etc/subgid
test:10000:65536

$ podman --version
podman version 3.2.1
$ podman ps -a
Error: kernel does not support overlay fs: 'overlay' is not supported over <unknown> at "/home/test/.local/share/containers/storage/overlay": backing file system is unsupported for this graph driver

**Comment by Mingli-Yu** [comment]
It works now after install fuse-overlayfs.

**Comment by rhatdan** [comment]
Kernels 5.13 will support rootless overlay, without requiring fuse-overlay.

**Comment by Mingli-Yu** [comment]
@rhatdan
Thanks your info!
But there comes a new issue:
1,
$ cat Dockerfile 
FROM centos:latest

RUN yum -y install systemd mariadb-server nginx

RUN systemctl enable mariadb.service && \
    systemctl enable nginx.service

EXPOSE 80

# Use systemd as command
CMD [ "/usr/sbin/init" ]

2, build the image
$ podman build --rm -t myserver .
[snip]
psmisc-23.1-5.el8.x86_64                                                      
  xkeyboard-config-2.28-1.el8.noarch                                            

Complete!
ERRO[0671] error unmounting /home/test/.local/share/containers/storage/overlay/2653d992f4ef2bfd27f94db643815aa567240c37732cae1405ad1c1309ee9859/merged: invalid argument 
Error: error committing container for step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:run Args:[yum -y install systemd mariadb-server nginx] Flags:[] Attrs:map[] Message:RUN yum -y install systemd mariadb-server nginx Original:RUN yum -y install systemd mariadb-server nginx}: error copying layers and metadata for container "41275dbc16b824fce0123af38984b53a917778ffc1ce2916d25b90d8eab85a68": Error initializing source containers-storage:centos-working-container: error extracting layer "801d835103fc38397690b85b68f50c4dfc08a3bafcc91c29b9b3be3827fe2c17": error creating overlay mount to /home/test/.local/share/containers/storage/overlay/2653d992f4ef2bfd27f94db643815aa567240c37732cae1405ad1c1309ee9859/merged, mount_data="ro,lowerdir=/home/test/.local/share/containers/storage/overlay/2653d992f4ef2bfd27f94db643815aa567240c37732cae1405ad1c1309ee9859/diff:/home/test/.local/share/containers/storage/overlay/2653d992f4ef2bfd27f94db643815aa567240c37732cae1405ad1c1309ee9859/empty": using mount program /usr/bin/fuse-overlayfs: fuse-overlayfs: upperdir not specified
: exit status 1

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
Looks like a very old version of fuse-overlayfs that doesn't support running without a upperdir.  Please use a newer version for fuse-overlayfs

**Comment by Mingli-Yu** [comment]
@giuseppe 
Thanks you! Have upgraded fuse-overlayfs to 1.6, I can succeed to build the image with rootless now.
But a new issue occurs.
1,
$ cat Dockerfile
FROM centos:latest

RUN yum -y install systemd mariadb-server nginx

RUN systemctl enable mariadb.service &&
systemctl enable nginx.service

EXPOSE 80

# Use systemd as command
CMD [ "/usr/sbin/init" ]

2, build the image
$ podman build --rm -t myserver .
[snip]
STEP 6: COMMIT myserver
--> 5417ae0fdd6
Successfully tagged localhost/myserver:latest
5417ae0fdd6b43011127ed8604b4477a89ba447ee07e426d2def158baad2393a

3, start the container
$ podman run -d --name=myserver_run -p 8080:80  myserver
0cd64cfe817d0d58bdb22febf177be3b564ff6aef74ebca711e6c12ecd665033

4, check the service
$ curl localhost:8080
curl: (7) Failed to connect to localhost port 8080: Connection refused
