### ISSUE TITLE
CONTAINERS_STORAGE_CONF variable is not working properly

### ISSUE THREAD

**Issue by olivergs** [containers/podman#10762]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

CONTAINERS_STORAGE_CONF variable is not working properly.  If set, podman info --debug shows that store configFile is the one specified by the environment variable, but the contents of the file are ignored and graphRoot and runRood are not changed at all and the default is shown.

**Steps to reproduce the issue:**

1. Copy the default storage file for rootless podman to another place

2. Change the graphRoot and runRoot in that file to another different path

3. Run: CONTAINERS_STORAGE_CONF=path_to_your_storage_file podman info —debug

**Describe the results you received:**

The store configFile is changed, but graphRoot and runRoot are not read from the configFile

**Describe the results you expected:**

The store configFile is changed and graphRoot and runRoot are read and set to the values in the configFile

**Output of `podman version`:**

```
podman version 3.2.1
```

**Output of `podman info --debug`:**

```
 host:
  arch: amd64
  buildahVersion: 1.21.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.27-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: t480s.fc.ad
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.12.9-300.fc34.x86_64
  linkmode: dynamic
  memFree: 1296146432
  memTotal: 16647704576
  ociRuntime:
    name: crun
    package: crun-0.20.1-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.20.1
      commit: 0d42f1109fd73548f44b01b3e84d04a279e99d2e
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.9-1.fc34.x86_64
    version: |-
      slirp4netns version 1.1.8+dev
      commit: 6dc0186e020232ae1a6fcc1f7afbc3ea02fd3876
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 14671007744
  swapTotal: 17000554496
  uptime: 214h 3m 57.2s (Approximately 8.92 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: ""
  containerStore:
    number: 6
    paused: 0
    running: 0
    stopped: 6
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.5.0-1.fc34.x86_64
      Version: |-
        fusermount3 version: 3.10.3
        fuse-overlayfs: version 1.5
        FUSE library version 3.10.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/oliver/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 4
  runRoot: /run/user/1000/containers
  volumePath: /home/oliver/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.1
  Built: 1623697949
  BuiltTime: Mon Jun 14 20:12:29 2021
  GitCommit: ""
  GoVersion: go1.16.3
  OsArch: linux/amd64
  Version: 3.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.2.1-1.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical laptop with Fedora 34

**Comment by olivergs** [comment]
Well, after reading the code I found the option rootless_storage_path

Seems that if I'm running podman rootless, the runRoot and graphRoot are ignored when read from the configuration file, but, if I set the rootless_storage_path, then the graphRoot and volumePath changes automatically to the one specified in rootless_storage_path.

Is this the intended behavior?

**Comment by mheon** [comment]
This definitely sounds like a bug, we should not be ignoring that environment variable.

**Comment by olivergs** [comment]
Well, the variable is not ignored. The configFile value is set if I set the variable. The problem is that the values I set into that alternate file for runRoot and graphRoot are not being taken into account when running the rootless podman. There is another extra variable as I told before, called rootless_storage_path that seems to do what I need, but I asked if this is the intended behavior or there is something weird here.

**Comment by rhatdan** [comment]
Yes I believe by default we ignore the graphRoot and runRoot settings in rootless mode.  Basically those fields are for rootfull and we automatically force the settings in rootless mode to the users homedir unless rootless_storage_path is set.

@giuseppe Any other comment on this?

**Comment by rhatdan** [comment]
I think I answered this, so closing.  Reopen if more info is required.

**Comment by olivergs** [comment]
Thanks Daniel.  All is clear.
