### ISSUE TITLE
systemd service files contain hardcoded paths

### ISSUE THREAD

**Issue by tobwen** [containers/podman#10787]
/kind bug

**Description**
On installation via `make install`, the _systemd_ service files contain hardcoded paths even when `DESTDIR` or `PREFIX` are set.

**Describe the results you received:**
https://github.com/containers/podman/tree/master/contrib/systemd

**Describe the results you expected:**
These files should be created with the settings that the user has specified. Alternatively, it is questionable whether the data is necessary at all, as it can usually be generated from _podman_ (at least the _systemd_ files). 

Another alternative would be to include these configuration files only as example files. In that case, however, the installation in the currently selected folders would be wrong. `PREFIX/share/doc/podman/examples/` might be expected.

**Comment by rhatdan** [comment]
I would prefer to keep the fixes and have the make install modify the path based on the PREFIX value.

**Comment by rhatdan** [comment]
Interested in opening a PR?

**Comment by tobwen** [comment]
> I would prefer to keep the fixes and have the make install modify the path based on the PREFIX value.

But why include these only then? I mean, we've got way more configs, which are needed in _podman_, but don't get installed by `make install`:

```
https://raw.githubusercontent.com/containers/common/main/pkg/config/containers.conf
https://raw.githubusercontent.com/containers/image/main/registries.conf
https://raw.githubusercontent.com/containers/common/main/pkg/seccomp/seccomp.json
https://raw.githubusercontent.com/containers/shortnames/main/shortnames.conf
https://raw.githubusercontent.com/containers/storage/main/storage.conf
```

**Comment by rhatdan** [comment]
So you want to make it more complex. In a perfect world, we should specify man installs for each of these config files in their subpackages.

**Comment by tobwen** [comment]
My main problem was that `make install` by default installs configs with paths, which didn't match with my configuration. So there are two ways at least:

1. fix those configurations to match to `prefix`
2. don't make them default `make install`, like all the other configs.

"1" doesn't seem that hard to make. I'd just insert a placeholder in the contrib config and replace them using `sed`. I can give it a try.
"2" seems also doable. It might even use the stuff from "1". But we need to talk about https://github.com/containers/podman/issues/10792 first.

We could end in `make install.configs` or such.

**Comment by rhatdan** [comment]
Yes both seem reasonable.  We probably should not install the configs with make install.  I would be willing to take that as long as we add a make install.configs.  Handling the PREFIX change would be nice also.  Interested in opening a PR?

**Comment by tobwen** [comment]
> Interested in opening a PR?

Yes, but I can't start until the week after next at the earliest. And my knowledge of "go" is limited, so I can do it on Makefile and shell level only ;)

**Comment by rhatdan** [comment]
SGTM

**Comment by rhatdan** [comment]
@tobwen Did you ever get a chance to look at this?

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Comment by rhatdan** [comment]
@tobwen are you still interested in this?  Interested in opening a PR?

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Comment by vrothberg** [comment]
We discussed various ways to address the issue in #11788 but I am not convinced at all. IMHO, it's common to ship hard-coded (and absolute) paths in .service files and I think we're getting more problems than we'd fix by changing the current state.

**Comment by tobwen** [comment]
> Interested in opening a PR?

I tried, but I really can't get along with Go. Sorry :(
