### ISSUE TITLE
RFE: pod infra container name customization

### ISSUE THREAD

**Issue by mskarbek** [containers/podman#10794]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I would like to be able to set name for infra container created inside pod, Additional option in `podman pod create` in form of `--infra-name=name` should be ok. Reasoning: we are using strict naming convention for pods/containers and only infra containers require additional code path to handle its naming divergence.

**Comment by rhatdan** [comment]
Interested in opening a PR to fix this?

**Comment by rhatdan** [comment]
@cdoern Interested in taking a look at this?

**Comment by jvanz** [comment]
Can I work on this? Thanks!

**Comment by rhatdan** [comment]
Sure we love free labor...
