### ISSUE TITLE
unify config locations

### ISSUE THREAD

**Issue by tobwen** [containers/podman#10792]
/kind feature

**Description**
Right now, _podman_ reads configs from various locations.

**containers.conf**
1. `/usr/share/containers/`
2. `/etc/containers/`
3. `$HOME/.config/containers/`

**storage.conf**
1. `/etc/containers/`
2. `$HOME/.config/containers/`

**registry.conf**
1. `/etc/containers/`
2. `/etc/containers/registries.d/`
3. `$HOME/.config/containers/`

**policy.json**
1. `/etc/containers/`
2. `$HOME/.config/containers/`

**seccomp.json**
1. `/usr/share/containers/`
2. `/etc/containers/`

**cni/*.conflist**
1. `/etc/cni/net.d/`
2. `$HOME/.config/cni/net.d/`

**Describe the results you expected:**
Would be fine to have this unified
1. `/usr/share/containers/`
2. `/etc/containers/`
3. `$HOME/.config/containers/`

Plus some dot-d-directories of course.

**Comment by Luap99** [comment]
Seccomp should already use `/etc/containers/seccomp.json` if present.

I do not think we should change the CNI directories `/etc/cni/net.d/` and `$HOME/.config/cni/net.d/`

**Comment by Luap99** [comment]
@rhatdan Did you patched `containers.conf` to read from `containers.conf.d` directories?

**Comment by tobwen** [comment]
Thanks, I've updated my initial post. Here another design:

|                 | /usr/share/containers/ | /etc/containers/ | $HOME/.config/containers/ | /etc/cni/net.d/ | $HOME/.config/cni/net.d/ |
|-----------------|------------------------|------------------|---------------------------|-----------------|--------------------------|
| containers.conf | 1                      | 1                | 1                         | 0               | 0                        |
| storage.conf    | 0                      | 1                | 1                         | 0               | 0                        |
| registry.conf   | 0                      | 1                | 1                         | 0               | 0                        |
| policy.json     | 0                      | 1                | 1                         | 0               | 0                        |
| seccomp.json    | 1                      | 1                | 0                         | 0               | 0                        |
| cni/*.conflist  | 0                      | 0                | 0                         | 1               | 1                        |

**Comment by rhatdan** [comment]
Yes containers.conf now supports .d files.

**Comment by vrothberg** [comment]
registries.conf can also read from $HOME/.confing/containers/registries.conf.d. Note 100 percent sure about containers.conf.

While it would be nice to have consistency for all configs, some of them grew historically with requirements from other tools.  I'd be terrified of changing the loading behavior and breaking consumers.

**Comment by rhatdan** [comment]
I think we satisfied the things we could in this issue, but we will not unify all of the config files. Reopen if you think there is more work to be done.
