### ISSUE TITLE
some entries might be missing in `tmpfile.d`

### ISSUE THREAD

**Issue by tobwen** [containers/podman#10791]
/kind bug

**Description**
`/run/libpod` and `/run/user/*/libpod` might be missing in `tmpfile.d`.
I also don't think, `/var/lib/cni/networks` would touched from `systemd-tmpfiles` at all?

**Describe the results you received:**
https://github.com/containers/podman/blob/0a0ade3cc00c3779bbf68ddd103d3efd10b5c25b/contrib/tmpfile/podman.conf#L3-L7

**Describe the results you expected:**
```
x /tmp/podman-run-*
x /tmp/containers-user-*
x /tmp/run-*/libpod
D! /run/lipod 0600 root root
D! /run/podman 0600 root root
D! /run/user/*/libpod
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Actually, I'm not aware, when `systemd-tmpfiles` is executed on all those distributions. On some distributions, like _Debian_ `/tmp/` is NOT _tmpfs_. So the temporary files will survive a reboot (theoretically). I guess on all OS, `/run/` is _tmpfs_, so it won't survive a reboot at all.

My 50 Cent: `systemd-tmpfiles` is highly destructive and *DOES NOT* have a `--dry-run` flag. My god, why???

**Comment by tobwen** [comment]
@mheon 
In commit message https://github.com/containers/podman/commit/9a02b50551d73c1427d158cca85d020fc71e27a7 you also wanted to add `/run/user-$UID/libpod`, but you didn't. Was this just a typo (`s/run/tmp`)?

**Comment by mheon** [comment]
Ah, it was a typo, but the commit message, not the entry in tmpfiles.d - it
should be in /tmp, not /run. Oops. At least the patch was right, even if
the commit message was off?

As for whether entries in /run should be there - I believe, but am not
sure, that systemd-tmpfiles only targets /tmp (at least, I don't think
we've ever had reports of it wiping our state in /run).

**Comment by tobwen** [comment]
> I believe, but am not sure, that systemd-tmpfiles only targets /tmp

I've just seen:
```
 D! /run/podman 0700 root root 
 D! /var/lib/cni/networks 
```

And thought: okay, there might be a reason, why they've done this. But then, it's incomplete :-)

I don't even think, `/var/lib/` will be touched. On Debian, `/var/lib/postgresql/` contains the _PostgreSQL_ clusters. I hope, _sytemd-tmpfiles_ will never ever go there.

**Comment by rhatdan** [comment]
These lines tell systemd-tmpfiles to delete this content if it exists at boot time.  The /run command is probably unnecessary, since systemd will not boot (As I understand it) if /run is not a tmpfs.
The /var/lib/cni/networks is definitely necessary.

**Comment by tobwen** [comment]
So:

```
x /tmp/podman-run-*
x /tmp/containers-user-*
x /tmp/run-*/libpod
D! /var/lib/cni/networks 
```

**Comment by rhatdan** [comment]
I believe we are all set, reopen if I am mistaken.
