### ISSUE TITLE
How to route requests between the HOST and PODs attached to a podman network

### ISSUE THREAD

**Issue by nmvega** [containers/podman#10815]
Hello again Friends:

I asked this [question on `StackOverflow`](https://stackoverflow.com/questions/68183481/podman1-how-to-route-requests-between-the-host-and-pods-attached-to-a-podman), but figured I'd ask here, too. `Note`: I use `Spark` here to aid this `podman(1)` question, but the question itself isn't about `Spark`.

Using `rootless podman(1)`, I start a tiny `Spark` cluster within it's own `Pod` using the following script, which works well:

```
#! /usr/bin/bash

podman network create --subnet 192.168.10.0/24 --gateway 192.168.10.1 mynet

podman pod create \
    --name=spark \
    --network=mynet \
    --share net \
    --publish 7077:7077 \
    --publish 8080:8080

podman run \
    --detach \
    --pod=spark \
    --name=master01 \
    --hostname spark \
    --restart always \
    --env SPARK_MODE=master \
    --env SPARK_RPC_AUTHENTICATION_ENABLED=no \
    --env SPARK_RPC_ENCRYPTION_ENABLED=no \
    --env SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no \
    --env SPARK_SSL_ENABLED=no \
    --add-host spark:127.0.0.1 \
    --add-host worker01:127.0.0.1 \
    docker.io/bitnami/spark:latest

podman run \
    --detach \
    --pod=spark \
    --name=worker01 \
    --hostname worker01 \
    --restart always \
    --env SPARK_MODE=worker \
    --env SPARK_MASTER_URL=spark://spark:7077 \
    --env SPARK_WORKER_MEMORY=4G \
    --env SPARK_WORKER_CORES=8 \
    --env SPARK_RPC_AUTHENTICATION_ENABLED=no \
    --env SPARK_RPC_ENCRYPTION_ENABLED=no \
    --env SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no \
    --env SPARK_SSL_ENABLED=no \
    --add-host spark:127.0.0.1 \
    --add-host worker01:127.0.0.1 \
    docker.io/bitnami/spark:latest
```

Following is an image of the `SparkUI`.

[![enter image description here][1]][1]

See lower-left corner of the browser image. Hovering the mouse over the only available `Spark worker` link (beneath `Worker id`), notice that the URL resolves to `192.168.10.2`, which is a valid `Pod IP-Address` falling within the `podman network` created above. 

However, clicking that URL will, of course, hang because that `Pod IP-Address` is not reachable from the `HOST`. With `docker(1)` (not `podman(1)`) there's a gateway mechanism to routes requests between `guest containers` and the `Host`. 

How is this accomplished with `podman(1)`?

A few other points to help:

 - This is an example `Spark Pod`. There are additional `Pod`s that attach that same `pod network`: `mynet`
 - I don't want to publish extra ports, because that will break anyway once you go deeper into the `UI`. More importantly, doing that defeats the purpose of `Pod`s, which isolate conflicting ports from one another. Rather, I need to understand how to "gateway" these requests.
 - Finally, I'm humbled because I thought I knew `podman(1)` quite well. `LoL`

Thank you in advance.

  [1]: https://i.stack.imgur.com/3uBcf.png

**Comment by mheon** [comment]
Are you running as root, or without?

As root, the internal IP addresses of the pods should be accessible from the host, same as Docker. Without root, we do not have privileges to configure bridge networking that would allow that. Rootless containers can only be accessed via forwarded ports as their network configuration is confined to a network namespace.

**Comment by nmvega** [comment]
Hi again @mheon  Sorry, I forgot to mention that, indeed, I'm running `rootless`.

Okay, I understand your comment.

But even if I were to forward ports, the `SparkUI` `URLs` will always point to a non-accessible, internal `IP-Address`. That's what makes this example interesting and why I chose it.

And ideas on how to handle that?

**Comment by mheon** [comment]
There isn't really a way of dealing with this, aside from setting host networking on the pod to disable network separation or running the application with root Podman. Without root, we don't have the privileges to make those IPs available to the wider system.

**Comment by nmvega** [comment]
@mheon Understood.

And with `host networking`, are `Pod`s still relevant for network separation? For example, if `Pod-A` and `Pod-B` have services that use the same `port`, I assume there will be `host-side` port conflicts, correct?

In other words, for `host networking`, what advantages do `Pod`s offer, if not network isolation?

Thank you.

**Comment by mheon** [comment]
They continue to provide a grouping of containers which are managed together, but you are correct that host networking removes the advantage of shared networking for all containers in the pod (instead, you get shared networking for all containers on the system with host networking, and the host itself).

**Comment by nmvega** [comment]
@mheon Excellent and well-written replies. I'll close this issue. Thanks as always for the help Matt!
