### ISSUE TITLE
API "PortMapping" fields are named differently depending on the endpoint.

### ISSUE THREAD

**Issue by arctic-alpaca** [containers/podman#10838]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Hello,
the struct `PortMapping` is used in three endpoints, [List containers ](https://docs.podman.io/en/latest/_static/api.html#operation/ContainerListLibpod), [Create a container](https://docs.podman.io/en/latest/_static/api.html#operation/ContainerCreateLibpod) and [Create a pod](https://docs.podman.io/en/latest/_static/api.html#operation/PodCreateLibpod). 
The naming of fields differs between the `List Containers` and the `Create a Container` endpoints. I'm currently not able to check the `Create a pod` endpoint.

**Steps to reproduce the issue:**

1. ``podman system service unix:///home/`whoami`/testing.sock --log-level=debug --time=500``

2. ```
    curl -X POST -d '{"image":"testcontainer:latest","portmappings":[{"containerPort":1234,"hostPort":1234}]}' --header "Content-Type: application/json" --unix-socket /home/`whoami`/testing.sock http://d/v3.0.0/libpod/containers/create
    {"cause":"container port number must be non-0","message":"container port number must be non-0","response":500}``` 

3. ```
    curl -X POST -d '{"image":"testcontainer:latest","portmappings":[{"container_port":1234,"host_port":1234}]}' --header "Content-Type: application/json" --unix-socket /home/`whoami`/testing.sock http://d/v3.0.0/libpod/containers/create
    {"Id":"5e9b87e2e6d5345bc7e8212c4591517347f3f921a9f32580ddd8d5c225ad6a9e","Warnings":[]}``` 

4. ```
    curl --unix-socket /home/`whoami`/testing.sock http://d/v3.0.0/libpod/containers/json?all=true
    [{"AutoRemove":false,
    "Command":["/run.sh"],
    "Created":"2021-07-01T16:53:11.1415177+02:00",
    "CreatedAt":"",
    "Exited":false,
    "ExitedAt":-62135596800,
    "ExitCode":0,
    "Id":"5e9b87e2e6d5345bc7e8212c4591517347f3f921a9f32580ddd8d5c225ad6a9e",
    "Image":"localhost/testcontainer:latest",
    "ImageID":"9a08c242d461c0f99dafc1d947837aff08bbf6a8cd2b1d43d92a6fd1fd02cdd0",
    "IsInfra":false,
    "Labels":{"io.buildah.version":"1.19.4"},
    "Mounts":[],
    "Names":["admiring_galileo"],
    "Namespaces":{},
    "Networks":null,
    "Pid":0,
    "Pod":"",
    "PodName":"",
    "Ports":[
        {"hostPort":1234,
        "containerPort":1234,
        "protocol":"tcp",
        "hostIP":""}],
    "Size":null,
    "StartedAt":-62135596800,
    "State":"configured",
    "Status":""}]``` 

**Describe the results you received:**
Different field naming for `PortMapping`.

**Describe the results you expected:**
No different field naming for `PortMapping`.

**Output of `podman version`:**

```
./podman version
Version:      3.3.0-dev
API Version:  3.3.0-dev
Go Version:   go1.16.4
Git Commit:   fd1715568b7c14451dcf2581c385c8d3e307d30e-dirty
Built:        Tue Jan  1 01:00:00 1980
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
./podman info --debug
host:
  arch: amd64
  buildahVersion: 1.22.0-dev
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 12
  distribution:
    distribution: debian
    version: "10"
  eventLogger: file
  hostname: DESKTOP
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.4.72-microsoft-standard-WSL2
  linkmode: static
  memFree: 12355756032
  memTotal: 13346447360
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.18.1-7931a-dirty
      commit: 7931a1eab0590eff4041c1f74e2844b297c31cea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /tmp/podman-run-1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.4
  swapFree: 4294967296
  swapTotal: 4294967296
  uptime: 9h 1m 38.38s (Approximately 0.38 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/alpaca/.config/containers/storage.conf
  containerStore:
    number: 18
    paused: 0
    running: 0
    stopped: 18
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.4.1
        fuse-overlayfs: version 1.4
        FUSE library version 3.4.1
        using FUSE kernel interface version 7.27
  graphRoot: /home/alpaca/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 22
  runRoot: /tmp/podman-run-1000/containers
  volumePath: /home/alpaca/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.0-dev
  Built: 315532800
  BuiltTime: Tue Jan  1 01:00:00 1980
  GitCommit: fd1715568b7c14451dcf2581c385c8d3e307d30e-dirty
  GoVersion: go1.16.4
  OsArch: linux/amd64
  Version: 3.3.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

Static version from: https://github.com/containers/podman/runs/2956588976

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows 10, 64bit, WLS2, Debian 10

**Comment by rhatdan** [comment]
@jwhonce PTAL

**Comment by jwhonce** [comment]
@mheon @baude The issue @arctic-alpaca raises stems from container list using ocicni.PortMapping structure while container create is using specgen.PortMapping. Given our forward direction for networking code, I'm leaning towards having container list report using specgen vs ocicni fields. Either way this falls, this is a Podman API v4 change.

**Comment by mheon** [comment]
@jwhonce As part of the 4.0 networking changes, I want to change the way we're storing ports in the DB from the OCICNI struct to the Specgen one, which will allow us to unify on that in the container list code. I don't think we can do it before that because converting between these structs is very expensive in CPU and memory terms.

**Comment by baude** [comment]
sgtm, can we make a jira card for this so it is not forgotten?

**Comment by Luap99** [comment]
This should be fixed in the main branch. The container list endpoint should use the specgen format.
