### ISSUE TITLE
Symlink devices not working

### ISSUE THREAD

**Issue by dayjaby** [containers/podman#10887]
/kind bug

**Description**

Devices, that are symlinks on the host, are not correctly resolved. 

**Steps to reproduce the issue:**

1. Run this udev rule: `SUBSYSTEMS=="usb", KERNEL=="ttyACM[0-9]*", ATTRS{idVendor}=="1546", ATTRS{idProduct}=="01a8", MODE="0666", GROUP="dialout", SYMLINK+="ublox_rtk"`
2. Run this command in repo (https://github.com/at-wat/ublox-rtcm3): `podman run -it --rm --device /dev/ublox_rtk:/dev/ublox_rtk:rwm localhost/rtklib-ubx`

I made sure that the udev rule got triggered:
```
$ ls -al /dev/ublox_rtk
lrwxrwxrwx 1 root root 7 Jul  9 11:40 /dev/ublox_rtk -> ttyACM1
```

**Describe the results you received:**

```
`podman exec -it ublox-rtcm3_ublox-rtcm3_1 ls /dev/ublox_rtk
ls: /dev/ublox_rtk: No such file or directory`
```

**Describe the results you expected:**

That I can access the /dev/ttyACM device within the container, but with its symlink names.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version
Version:      3.1.2
API Version:  3.1.2
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

https://pastebin.com/jzgV1ey4

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
apt list podman
Listing... Done
podman/unknown 100:3.2.2-1 amd64 [upgradable from: 100:3.1.2-1]
podman/unknown 100:3.2.2-1 arm64
podman/unknown 100:3.2.2-1 armhf
podman/unknown 100:3.2.2-1 s390x```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**


No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 20.04

**Comment by dayjaby** [comment]
One more thing: I ran everything as `sudo`. As a normal user it seems to work.

**Comment by rhatdan** [comment]
As a normal user we are only volume (bind) mounting the device from the host in.

In rootfull mode we actually attempt to create the device.

I just tried the following.
```
# ln -s /dev/null /dev/dan
# podman run --device /dev/dan:/dev/dan fedora ls -l /dev/dan
crw-rw-rw-. 1 root root 1, 3 Jul  9 14:37 /dev/dan
```
And it seemed to work.

Does this test work for you?

**Comment by dayjaby** [comment]
Yes, this works. And appearently in my case above now as well. No idea, what I did wrong in the beginning..thanks for your help :)
