### ISSUE TITLE
Strage behavior of `python3 -c 'import socket ; print(socket.getfqdn())'` within containers with --net=host

### ISSUE THREAD

**Issue by sebastian-philipp** [containers/podman#10888]
Hi, 

I'm getting some super random hostname, when calling `pyhton -c `import socket ; print(socket.getfqdn())` from contaieners:

My example command looks like so:

```
sudo podman run -it --rm  --name foo.bar  quay.ceph.io/ceph-ci/ceph:master python3 -c 'import socket ; print(socket.getfqdn())'
foo.bar
```

And the results look like so:

|            | --name foo-bar    | --name foo.bar | --name foo        |
|-----------------------|-------------------|----------------|-------------------|
| (omit --hostname)                | sebastians-laptop | foo.bar        | sebastians-laptop |
| **--hostname baz.baaaaz** | baz.baaaaz        | baz.baaaaz     | baz.baaaaz        |
| **--hostname baz**        | sebastians-laptop | foo.bar        | sebastians-laptop |

My goal is to reliably make `socket.getfqdn()` to return the FQDN of the container host, but right now, I don't see how I can get this result. 

Do you have any guidance?

**Comment by vrothberg** [comment]
Thanks for reaching out, @sebastian-philipp!

@Luap99 do you know what's going on?

**Comment by Luap99** [comment]
@sebastian-philipp Could you clarify if you have the issue with `--net host`, I do not see it in your example command.

**Comment by rhatdan** [comment]
I am able to reproduce.  I am guessing this has something to do with DNS.  Are we adding information to DNS about the container, so that other containers can ping.  When the name looks like a host(Has a "." in it) then python discovers the name?

**Comment by rhatdan** [comment]
```
$ sudo podman run -it --rm  --name foo.bar  quay.ceph.io/ceph-ci/ceph:master ping foo.bar
PING 1272466af54d (10.88.0.15) 56(84) bytes of data.
64 bytes from 1272466af54d (10.88.0.15): icmp_seq=1 ttl=64 time=0.019 ms
64 bytes from 1272466af54d (10.88.0.15): icmp_seq=2 ttl=64 time=0.070 ms
^C
--- 1272466af54d ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1049ms
rtt min/avg/max/mdev = 0.019/0.044/0.070/0.026 ms
buildah (excludes) $ sudo podman run -it --rm  --name foo  quay.ceph.io/ceph-ci/ceph:master ping foo
PING 1aff16e09d68 (10.88.0.16) 56(84) bytes of data.
64 bytes from 1aff16e09d68 (10.88.0.16): icmp_seq=1 ttl=64 time=0.038 ms
64 bytes from 1aff16e09d68 (10.88.0.16): icmp_seq=2 ttl=64 time=0.059 ms
^C
--- 1aff16e09d68 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1037ms
rtt min/avg/max/mdev = 0.038/0.048/0.059/0.012 ms
```

**Comment by sebastian-philipp** [comment]
Right, an example of the commands I run was:

```
sudo podman run -it --rm --net=host --hostname baz --name foo.bar  quay.ceph.io/ceph-ci/ceph:master python3 -c 'import socket ; print(socket.getfqdn())'
foo.bar
```



> ```
> $ sudo podman run -it --rm  --name foo.bar  quay.ceph.io/ceph-ci/ceph:master ping foo.bar
> PING 1272466af54d (10.88.0.15) 56(84) bytes of data.
> 64 bytes from 1272466af54d (10.88.0.15): icmp_seq=1 ttl=64 time=0.019 ms
> 64 bytes from 1272466af54d (10.88.0.15): icmp_seq=2 ttl=64 time=0.070 ms
> ^C
> ```
Right, But that only works from within the container. We need an fqdn that is also resolvable form outside. 


> I am able to reproduce. I am guessing this has something to do with DNS. Are we adding information to DNS about the container, so that other containers can ping. When the name looks like a host(Has a "." in it) then python discovers the name?

That's my hypothesis right now. It seems as if `socket.getfqdn()` uses the hostname with dots in it and if the container name contains dots, it's uses as the FQDN of the host. https://github.com/ceph/ceph/pull/42242 is an attempt to find out, if using dashes would solve this issue. But maybe I'm missing something?

**Comment by Luap99** [comment]
AFAIK this information is usually gathered from /etc/hostname. Podman will write the container hostname to it. If --hostname is omitted it uses the container ID or with `--net host` it will use the hostname from the host. 
`socket.getfqdn()` does not seem to be happy when the hostname when there is not dot in the name. I think it will fall back to reading entries from /etc/hosts and it will take the first entry which has a dot in it. Podman will write both the container name and hostname to /etc/hosts if the container name has a dot in it `socket.getfqdn()` will use this instead of the actual hostname from /etc/hostname. I do not think Podman is doing anything wrong here.

**Comment by Luap99** [comment]
see https://docs.python.org/3/library/socket.html#socket.getfqdn

**Comment by sebastian-philipp** [comment]
Sigh. thanks for the help.

**Comment by rhatdan** [comment]
Nice diagnosis @Luap99
