### ISSUE TITLE
Document that source IP for rootless containers is always 10.0.2.100 and slirp4netns workaround with it's (dis)advantages

### ISSUE THREAD

**Issue by rugk** [containers/podman#10884]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind documentation
(?)

## Problem

I had a [curious "problem" with the webserver caddy](https://caddy.community/t/use-real-ip-in-docker-podman-container/12978?u=rugk), where each source IP was always `10.0.2.100`. I could trace it back to podman being the obvious fault, because it's the "inside of container" vs "outside of container" view… :upside_down_face: 
In the end, I solved this by switching to `host` networking…

Later I noticed this comment by @AkihiroSuda:
> Also it should be documented that apps will always see 10.0.2.100 (or CNI IP) as the source address.

https://github.com/containers/podman/pull/9052#issuecomment-764700524

## Documentation

[Searching the docs](http://docs.podman.io/en/latest/search.html?q=10.0.2.100) it seems that this comment was forgotten and nothing was actually documented.

As such, here is an issue to document the fact that this happens and explain the workaround/solution in this case (which AFAIK are either using rootfull containers or host networking as I did).
**Edit:** or… `--network slirp4netns:port_handler=slirp4netns`, apparently, [as I was made ware](https://caddy.community/t/use-real-ip-in-docker-podman-container/12978/5?u=rugk), ref https://github.com/containers/podman/pull/9052 (anyway, that also needs documentation)

## Relevance

IMHO this is important to document, because the use case of having a proper ingoing IP address is quite popular for all webservers, I guess.
Also, it's a difference to Docker/limitation of rootless containers, so IMHO, it [should also be documented here](https://github.com/containers/podman/blob/main/rootless.md).

**Comment by rugk** [comment]
@openshift-ci-robot retry

**Comment by mheon** [comment]
Worth noting that this behavior can be worked around by specifying `--net slirp4netns:port_handler=slirp4netns` when creating the container. This forces the old slirp4netns port forwarding, as opposed to rootlesskit - it's slower, but does preserve source address (at the cost of some other quirks)

**Comment by rugk** [comment]
> it's slower, but does preserve source address (at the cost of some other quirks)

_Very_ worth noting to also document these two things and whatever quirks are used. Especially for a webserver (as I use it), the performance thing actually _matters_ (especially if you use "multiple" reverse-proxies or so…).
So I would be very interested in hearing that…

--

Unrelated: Could someone add the `kind/documentation` tag, please? (I messed up with the bot I know :sweat_smile: )

**Comment by rugk** [comment]
> This forces the old slirp4netns port forwarding, as opposed to rootlesskit

Do I understand this correctly that the new method is `rootlesskit` fopr rootless containers, and the old one was `slirp4netns`?
If yes, then [the doc is outdated here too](https://github.com/containers/podman/blob/main/docs/source/markdown/podman-create.1.md#--networkmode---net), as it says:
> **slirp4netns[:OPTIONS,...]:** use slirp4netns(1) […]. This is the default for rootless containers.

It's then not the default anymore, as far as I get that.

**Comment by rhatdan** [comment]
@mheon @Luap99 is this still an issue?

**Comment by mheon** [comment]
I don't recall seeing a docs PR, so this still requires attention.

**Comment by Luap99** [comment]
I opened #11177
