### ISSUE TITLE
Why is IPv6 disabled for rootless/slirp4netns containers?

### ISSUE THREAD

**Issue by rugk** [containers/podman#10889]
[The man page](https://github.com/containers/podman/blob/main/docs/source/markdown/podman-create.1.md#--networkmode---net) says:
> **enable_ipv6=true|false:** Enable IPv6. Default is false. (Required for `outbound_addr6`).

I interpret that as such, that IPv6 is disabled by default and thus containers/ports bound can only be reached via IPv4. Is that true?

If so, why is that so? Given [various](https://ipv6.watch/) [initiatives](https://ipv4flagday.net/) to [finally get to the](https://www.google.de/ipv6/statistics.html) [day](https://ipv4flagday.net/) we use IPv6 only, I wonder why you do not enable this by default…?

**Comment by AkihiroSuda** [comment]
Probably safe to enable v6 by default, but not massively tested as v4 and there might be some vulns

**Comment by rhatdan** [comment]
This should probably be done in containers.conf then.  That way users could have  a way to customize.

**Comment by Luap99** [comment]
You can already set this in containers.conf with `network_cmd_options = ["enable_ipv6=true"]`

@AkihiroSuda How does slirp4netns behave when ipv6 is disabled in the kernel, will it fail or ignore the ipv6 setup?

**Comment by AkihiroSuda** [comment]
> @AkihiroSuda How does slirp4netns behave when ipv6 is disabled in the kernel, will it fail or ignore the ipv6 setup?

Haven't tried

**Comment by rhatdan** [comment]
@rugk interested in opening a PR containers/common to change the default?

**Comment by rugk** [comment]
Hmm, tried with https://github.com/containers/common/pull/741, though I have no idea whether that is the correct thing to change… :smile:

**Comment by rhatdan** [comment]
You need to change default.go, we will carry on the conversation in the PR.
