### ISSUE TITLE
Open questions on limiting resources of a running container. Total memory and total disk usage. 

### ISSUE THREAD

**Issue by KCSesh** [containers/podman#10897]
**Description**

This is more of some open question on functionality that I haven't been able to find good answers for. 

By default podman creates `tmpfs` mounts like:

```
/run
/tmp
/var/tmp
/dev/mqueue
/dev/pts 
```

1. Does setting the `--memory` runtime option limit what can be written to these mount points as well?
2. Is a `tmpfs Volume` additional memory the container can use? Or will it also abide by the  `--memory` limit? 
  i.e. if my `--memory 50mb` but my `tmfps volume allows for 100mb` can I write 100mb to my volume and still have `50mb` of memory? 

3. For Disk limits is there a clear way in podman how to give a container a volume that can persist reboots but have a max-size associated to it? 
From my understanding, the `-o=size=100m` limit only works for `tmpfs` volumes.  I am looking to give a container write access to disk, but want to have a max size allocated so the container can only write 100mb to disk. Can I achieve this in podman with volumes? 
If I can't achieve this with volumes, do you suggest any linux approaches?

**Comment by rhatdan** [comment]
tmpfs mounts follow the rules of the lesser of MAX Size, and 50% of available memory.

If you set --memory 50mb, then the tmpfs with 100mb set, will still only be allowed to use 25mb. This is a feature of the kernel and cgroups.  BTW, this 25mb is for all tmpfs within the cgroup, not for each.

If you setup project quota on xfs and vfs, you should be able to control quota on the volume mounts.

**Comment by rhatdan** [comment]
BTW Podman by default does NOT create tmpfs on /run, /var/tmp and /tmp. This only happens when running in systemd mode.  It does mount on...

```
# podman run fedora mount | grep tmpfs
tmpfs on /dev type tmpfs (rw,nosuid,context="system_u:object_r:container_file_t:s0:c134,c237",size=65536k,mode=755,inode64)
tmpfs on /etc/resolv.conf type tmpfs (rw,seclabel,size=3205668k,nr_inodes=819200,mode=755,inode64)
tmpfs on /etc/hosts type tmpfs (rw,seclabel,size=3205668k,nr_inodes=819200,mode=755,inode64)
shm on /dev/shm type tmpfs (rw,relatime,context="system_u:object_r:container_file_t:s0:c134,c237",size=64000k,inode64)
tmpfs on /etc/hostname type tmpfs (rw,seclabel,size=3205668k,nr_inodes=819200,mode=755,inode64)
tmpfs on /run/.containerenv type tmpfs (rw,seclabel,size=3205668k,nr_inodes=819200,mode=755,inode64)
tmpfs on /run/secrets type tmpfs (rw,seclabel,size=3205668k,nr_inodes=819200,mode=755,inode64)
tmpfs on /proc/acpi type tmpfs (ro,relatime,context="system_u:object_r:container_file_t:s0:c134,c237",size=0k,inode64)
devtmpfs on /proc/kcore type devtmpfs (rw,seclabel,size=7993096k,nr_inodes=1998274,mode=755,inode64)
devtmpfs on /proc/keys type devtmpfs (rw,seclabel,size=7993096k,nr_inodes=1998274,mode=755,inode64)
devtmpfs on /proc/latency_stats type devtmpfs (rw,seclabel,size=7993096k,nr_inodes=1998274,mode=755,inode64)
devtmpfs on /proc/timer_list type devtmpfs (rw,seclabel,size=7993096k,nr_inodes=1998274,mode=755,inode64)
devtmpfs on /proc/sched_debug type devtmpfs (rw,seclabel,size=7993096k,nr_inodes=1998274,mode=755,inode64)
tmpfs on /proc/scsi type tmpfs (ro,relatime,context="system_u:object_r:container_file_t:s0:c134,c237",size=0k,inode64)
tmpfs on /sys/firmware type tmpfs (ro,relatime,context="system_u:object_r:container_file_t:s0:c134,c237",size=0k,inode64)
tmpfs on /sys/fs/selinux type tmpfs (ro,relatime,context="system_u:object_r:container_file_t:s0:c134,c237",size=0k,inode64)
tmpfs on /sys/dev/block type tmpfs (ro,relatime,context="system_u:object_r:container_file_t:s0:c134,c237",size=0k,inode64)
```

**Comment by KCSesh** [comment]
Thanks @rhatdan.

> tmpfs mounts follow the rules of the lesser of MAX Size

Is this documented anywhere? 


Also I will look into project quota, I am not too familiar with it. 
I am on an ext4 file system, but it seems there may be options. 

> BTW Podman by default does NOT create tmpfs on /run, /var/tmp and /tmp.

Thanks I was not familiar with turning off `systemd` mode until now, thanks for the info!

**Comment by rhatdan** [comment]
```
man tmpfs
...
       size=bytes
              Specify an upper limit on the size of the filesystem.  The  size
              is given in bytes, and rounded up to entire pages.

              The  size  may  have  a k, m, or g suffix for Ki, Mi, Gi (binary
              kilo (kibi), binary mega (mebi) and binary giga (gibi)).

              The size may also have a % suffix to limit this  instance  to  a
              percentage of physical RAM.

              The  default,  when  neither size nor nr_blocks is specified, is
              size=50%.
```
