### ISSUE TITLE
Release v3.2.2 is still missing the binaries

### ISSUE THREAD

**Issue by jensklose** [containers/podman#10904]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The github release page only shows 2 assets with packed sources.

**Steps to reproduce the issue:**

1. Open browser

2. Navigate to https://github.com/containers/podman/releases/tag/v3.2.2

**Describe the results you expected:**

There should be more assets with binary builds for different operating systems.

**Comment by mheon** [comment]
Done.
