### ISSUE TITLE
Error: readlink: Permission denied: OCI permission denied

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#10912]
This is one of those flakes that appear at random, in random tests, making it almost impossible for my flake-logger to isolate. Symptom is:
```
Running: podman [options] run [...]  quay.io/libpod/alpine:latest [command]
Error: readlink: Permission denied: OCI permission denied
```
One interesting thing: I see this (sometimes, not always) with `run -d`, implying that the error happens before detach.

## Podman UserNS support [It] podman --userns=container:CTR
* fedora-34 : int podman fedora-34 rootless host
  * PR #10405
    * [06-11 09:42](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6077820007874560/html/int-podman-fedora-34-rootless-host.log.html#t--podman---userns-container-CTR--1)

## Podman pod create [It] podman pod container can override pod not sharing pid
* fedora-33 : int podman fedora-33 rootless host
  * PR #10611
    * [06-09 10:19](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4686412789317632/html/int-podman-fedora-33-rootless-host.log.html#t--podman-pod-container-can-override-pod-not-sharing-pid--1)
* fedora-34 : int podman fedora-34 rootless host
  * PR #10405
    * [06-10 15:02](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6621687673257984/html/int-podman-fedora-34-rootless-host.log.html#t--podman-pod-container-can-override-pod-not-sharing-pid--1)
* ubuntu-2104 : int podman ubuntu-2104 rootless host
  * PR #10684
    * [06-15 11:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5406628473208832/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-pod-container-can-override-pod-not-sharing-pid--1)

## Podman run [It] podman shared PID NS container share SELinux labels
* fedora-33 : int podman fedora-33 rootless host
  * PR #10609
    * [06-10 10:43](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6633304150507520/html/int-podman-fedora-33-rootless-host.log.html#t--podman-shared-PID-NS-container-share-SELinux-labels--1)
* fedora-34 : int podman fedora-34 rootless host
  * PR #10639
    * [06-10 11:01](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5618642084691968/html/int-podman-fedora-34-rootless-host.log.html#t--podman-shared-PID-NS-container-share-SELinux-labels--1)

## Podman pod create [It] podman pod correctly sets up PIDNS
* fedora-34 : int podman fedora-34 rootless host
  * PR #10905
    * [07-12 09:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5861766438584320/html/int-podman-fedora-34-rootless-host.log.html#t--podman-pod-correctly-sets-up-PIDNS--1)
  * PR #10654
    * [06-11 10:46](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4636958874927104/html/int-podman-fedora-34-rootless-host.log.html#t--podman-pod-correctly-sets-up-PIDNS--1)
* ubuntu-2104 : int podman ubuntu-2104 rootless host
  * PR #10651
    * [06-11 07:14](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4541544750383104/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-pod-correctly-sets-up-PIDNS--1)

## Podman top [It] podman pod top on pod with containers in same pid namespace
* fedora-33 : int podman fedora-33 rootless host
  * PR #10684
    * [06-15 08:28](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5136634548060160/html/int-podman-fedora-33-rootless-host.log.html#t--podman-pod-top-on-pod-with-containers-in-same-pid-namespace--1)
* ubuntu-2104 : int podman ubuntu-2104 rootless host
  * PR #10684
    * [06-15 11:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5406628473208832/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-pod-top-on-pod-with-containers-in-same-pid-namespace--1)

## sys: podman selinux: shared context in (some) namespaces
* fedora-34 : sys podman fedora-34 rootless host
  * PR #10803
    * [06-29 07:10](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5316442179502080/html/sys-podman-fedora-34-rootless-host.log.html)

**Comment by edsantiago** [comment]
### Podman top [It] podman pod top on pod with containers in same pid namespace
* fedora-33 : int podman fedora-33 rootless host
  * PR #11176
    * [08-10 06:00](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4803999527337984/html/int-podman-fedora-33-rootless-host.log.html#t--podman-pod-top-on-pod-with-containers-in-same-pid-namespace--1)

### Podman pod create [It] podman pod container can override pod not sharing pid
* fedora-34 : int podman fedora-34 rootless host
  * PR #10913
    * [07-14 08:58](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4657233700061184/html/int-podman-fedora-34-rootless-host.log.html#t--podman-pod-container-can-override-pod-not-sharing-pid--1)

### Podman pod create [It] podman pod correctly sets up PIDNS
* fedora-34 : int podman fedora-34 rootless host
  * PR #10905
    * [07-12 09:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5861766438584320/html/int-podman-fedora-34-rootless-host.log.html#t--podman-pod-correctly-sets-up-PIDNS--1)

**Comment by edsantiago** [comment]
I've been keeping flake logs for a few months, and on August 17 I wrote a tool to grep those logs. The last occurrence of "readlink" on the same line as "Permission denied" was August 10 (already logged in comment above). It's possible that the error message changed, also possible that the issue magically fixed itself. I don't think there's anything I can do aside from close the issue.

**Comment by edsantiago** [comment]
Reopening: this is still happening.

### Podman pod create [It] podman pod create with --userns=keep-id can add users
* fedora-34 : int podman fedora-34 rootless host
  * PR #12235
    * [11-09 04:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6272633235832832/html/int-podman-fedora-34-rootless-host.log.html#t--podman-pod-create-with---userns-keep-id-can-add-users--1)
* fedora-35 : int podman fedora-35 rootless host
  * PR #12482
    * [12-02 10:46](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6132977408147456/html/int-podman-fedora-35-rootless-host.log.html#t--podman-pod-create-with---userns-keep-id-can-add-users--1)

### Podman pod create [It] podman pod create with --userns=auto
* fedora-35 : int podman fedora-35 rootless host
  * PR #12469
    * [12-01 14:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6655382601859072/html/int-podman-fedora-35-rootless-host.log.html#t--podman-pod-create-with---userns-auto--1)
    * [12-01 14:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6655382601859072/html/int-podman-fedora-35-rootless-host.log.html#t--podman-pod-create-with---userns-auto--2)
    * [12-01 14:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6655382601859072/html/int-podman-fedora-35-rootless-host.log.html#t--podman-pod-create-with---userns-auto--3)

### Podman pod create [It] podman pod create with --userns=keep-id
* ubuntu-2110 : int podman ubuntu-2110 rootless host
  * PR #12256
    * [11-11 14:59](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5997224665546752/html/int-podman-ubuntu-2110-rootless-host.log.html#t--podman-pod-create-with---userns-keep-id--1)

### Podman pod create [It] podman pod create --userns=auto:size=%d
* fedora-34 : int podman fedora-34 rootless host
  * PR #12221
    * [11-08 09:51](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6725032610103296/html/int-podman-fedora-34-rootless-host.log.html#t--podman-pod-create---userns-auto-size--d--1)


Two observations:
* There's an awful lot of `userns` in the list above. Much more than I think can be explained by coincidence.
* In logs where this happens, it seems to happen often, in other tests.

**Comment by vrothberg** [comment]
```
          podman pod create --userns=auto:size=%d
           /var/tmp/go/src/github.com/containers/podman/test/e2e/pod_create_test.go:739
         
         [BeforeEach] Podman pod create
           /var/tmp/go/src/github.com/containers/podman/test/e2e/pod_create_test.go:28
         [It] podman pod create --userns=auto:size=%d
           /var/tmp/go/src/github.com/containers/podman/test/e2e/pod_create_test.go:739
         Running: podman [options] pod create --userns=auto:size=500 --name testPod
         6092a09b3c751d0a768f5f7193034c2d793fbd3680fe7c42e344b8dcaf202fd4
         Running: podman [options] run --pod testPod quay.io/libpod/alpine:latest cat /proc/self/uid_map
                  0          1        500
         Running: podman [options] pod create --userns=auto:size=3000 --name testPod-1
         40ec609fac65ff52559ee8033d475074eb009f924d909ed11a42ab3b458a6bb9
         Running: podman [options] run --pod testPod-1 quay.io/libpod/alpine:latest cat /proc/self/uid_map
         Error: readlink: Permission denied: OCI permission denied
```

@giuseppe, could this be a crun issue?

**Comment by rhatdan** [comment]
No you are running a container within a Pod and already have set the userns size to 500, now you are attempting to set a container in the same user namesapce to use 3000 uids, which is not allowed.

What should happen here is --pod and userns option should conflict if container is sharing userns with the pod.

**Comment by rhatdan** [comment]
BTW We should do that for all of the namespace options.  If you share a namespace with the pod, then you should use the options set within the pod.

**Comment by rhatdan** [comment]
593d0907c5c11e933be7dbdce98022f76183ea3c just did this for conflicting --hostname when in a Pod.

**Comment by rhatdan** [comment]
```
# ./bin/podman pod create --userns=auto:500  --name dan
Error: invalid option specified: "500"
# ./bin/podman pod create --userns=auto:size=500  --name dan
9af8b13ebbb413e871ba1cfabfeda3d09342988b2500dabec5394b7a095acdf0
# ./bin/podman create --userns=auto:size=3000 --pod dan fedora echo hi
Error: --userns and --pod cannot be set together
```
Looks like current code at least conflicts setting USERNS within a Pod that is using user namespace.

Not sure if this is enough to close down this issue.

**Comment by edsantiago** [comment]
Most recent instance was Jan 12:

### [sys] 236 podman selinux: shared context in (some) namespaces
* fedora-34 : sys podman fedora-34 rootless host
  * PR #12832
    * [01-12 14:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4737079623024640/html/sys-podman-fedora-34-rootless-host.log.html#t--00236)

That instance does not seem to have anything to do with userns or pods:
```
[+0933s] [not ok 236 podman selinux: shared context in (some) namespaces]()
         # (from function `die' in file test/system/helpers.bash, line 448,
         #  from function `run_podman' in file test/system/helpers.bash, line 221,
         #  in test file test/system/410-selinux.bats, line 125)
         #   `run_podman run --rm --pid container:myctr $IMAGE cat -v /proc/self/attr/current' failed with status 126
         # $ podman rm --all --force
         # $ podman ps --all --external --format {{.ID}} {{.Names}}
         # $ podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
         # quay.io/libpod/testimage:20210610 9f9ec7f2fdef
         # $ podman run -d --name myctr quay.io/libpod/testimage:20210610 top
         # ac8e1d127b201330e12858aa66306362b24359e4bbf31b3f8f42283e97536b2f
         # $ podman exec myctr cat -v /proc/self/attr/current
         # system_u:system_r:container_t:s0:c68,c413^@
         # $ podman run --name myctr2 --ipc container:myctr quay.io/libpod/testimage:20210610 cat -v /proc/self/attr/current
         # system_u:system_r:container_t:s0:c68,c413^@
         # $ podman run --rm --pid container:myctr quay.io/libpod/testimage:20210610 cat -v /proc/self/attr/current
         # Error: readlink: Permission denied: OCI permission denied
         # [ rc=126 (** EXPECTED 0 **) ]
```

**Comment by edsantiago** [comment]
Nothing in my logs since Jan 12; make of that what you will.

**Comment by rhatdan** [comment]
@edsantiago Close?

**Comment by edsantiago** [comment]
No new instances since Jan 12. Okay, closing.

**Comment by edsantiago** [comment]
Seen today in [f37 rootless](https://api.cirrus-ci.com/v1/artifact/task/5465137050550272/html/int-podman-fedora-37-rootless-host-sqlite.log.html#t--podman-pod-top-on-pod-with-containers-in-same-pid-namespace--1). Reopening.
```
  podman pod top on pod with containers in same pid namespace
...
$ podman [options] pod create --infra=false --share 
d8b01eac6d1ea48c3f663d4b63b3fc54ceef58e1922331c5aeda1c963141dcd4
$ podman [options] run -d --pod d8b01eac6d1ea48c3f663d4b63b3fc54ceef58e1922331c5aeda1c963141dcd4 quay.io/libpod/alpine:latest top -d 2
6e812b0d7d847c624707baafadfd1d128ac5bcedc18b0704683e8829422e7d23
$ podman [options] run -d --pod d8b01eac6d1ea48c3f663d4b63b3fc54ceef58e1922331c5aeda1c963141dcd4 --pid container:6e812b0d7d847c624707baafadfd1d128ac5bcedc18b0704683e8829422e7d23 quay.io/libpod/alpine:latest top -d 2
d4fe59cf384803bd5340d32240722a8601b588ca99d9da6fbae5756b74f53b53
$ podman [options] pod top d8b01eac6d1ea48c3f663d4b63b3fc54ceef58e1922331c5aeda1c963141dcd4
Error: error extracting PID namespace: readlink /proc/59714/ns/pid: permission denied
```

**Comment by vrothberg** [comment]
@giuseppe could this be a race in `psgo`?

**Comment by rhatdan** [comment]
@edsantiago waiting for response from you

**Comment by edsantiago** [comment]
No instances since the one on May 1
