### ISSUE TITLE
permission denied: OCI error unless sudo

### ISSUE THREAD

**Issue by jonz-secops** [containers/podman#10918]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. centos stream 8 EC2 us-west-2

2. install podman from standard repo using @continaer-tools

3. try and run any -it image without sudo

I rebuilt this machine just to try and isolate this issue and address it, I can't find a way to address these OCI errors without running the image as sudo/root. The "--security-opt label=disable" doesn't help.

**Describe the results you received:**

<pre><font color="#005FD7">podman</font> <font color="#00AFFF">run</font> <font color="#00AFFF">-it</font> <font color="#00AFFF">alpine:latest</font> <font color="#00AFFF">ash</font>                                                                                        <font color="#585858">144ms  Mon 12 Jul 2021 11:52:17 PM UTC</font>
Error: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: process_linux.go:422: setting cgroup config for procHooks process caused: failed to write &quot;2048&quot; to &quot;/sys/fs/cgroup/user.slice/user-1001.slice/user@1001.service/user.slice/libpod-9d309fe1d527053d598bfc12d77c19b208d5619b81484601622b4c17323e3c4e.scope/pids.max&quot;: open /sys/fs/cgroup/user.slice/user-1001.slice/user@1001.service/user.slice/libpod-9d309fe1d527053d598bfc12d77c19b208d5619b81484601622b4c17323e3c4e.scope/pids.max: permission denied: OCI permission denied
</pre>

**Describe the results you expected:**

Like it seems to work for most, running a container without needing to sudo is my goal.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.1.0-dev
API Version:  3.1.0-dev
Go Version:   go1.16.1
Built:        Fri Mar 26 18:32:03 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.8
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.27-1.module_el8.5.0+733+9bb5dffa.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: dc08a6edf03cc2dadfe803eac14b896b44cc4721'
  cpus: 4
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: ip-172-199-2-149.us-west-2.compute.internal
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 4.18.0-315.el8.x86_64
  linkmode: dynamic
  memFree: 11424665600
  memTotal: 16290885632
  ociRuntime:
    name: runc
    package: runc-1.0.0-70.rc92.module_el8.5.0+733+9bb5dffa.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module_el8.5.0+733+9bb5dffa.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 0
  swapTotal: 0
  uptime: 2h 29m 32.83s (Approximately 0.08 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/secops-jzamani/.config/containers/storage.conf
  containerStore:
    number: 8
    paused: 0
    running: 0
    stopped: 8
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/secops-jzamani/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/user/1001/containers
  volumePath: /home/secops-jzamani/.local/share/containers/storage/volumes
version:
  APIVersion: 3.1.0-dev
  Built: 1616783523
  BuiltTime: Fri Mar 26 18:32:03 2021
  GitCommit: ""
  GoVersion: go1.16.1
  OsArch: linux/amd64
  Version: 3.1.0-dev

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.1.0-0.13.module_el8.5.0+733+9bb5dffa.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
`podman info` says this is a v2 system, but I didn't know that Cent Stream shipped that by default. Have you made any cgroups changes to convert the system to v2?

**Comment by jonz-secops** [comment]
@mheon I checked the system and it was v2 enabled, so I modified the grub configuration according to <https://www.redhat.com/en/blog/world-domination-cgroups-rhel-8-welcome-cgroups-v2> in order to move to cgroupv2.

**Comment by mheon** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
it is an issue with systemd on RHEL: https://bugzilla.redhat.com/show_bug.cgi?id=1897579

A workaround is to not set any pids limit: https://github.com/containers/podman/issues/9410#issuecomment-785840320

I am closing the bug as it is already tracked in bugzilla for the downstream.
