### ISSUE TITLE
podman generate systemd fails with "no create command found"

### ISSUE THREAD

**Issue by nebulon42** [containers/podman#10925]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

Rather a question. I wanted to post on the mailing list but moderator did not approve subscription so far. So I'm trying here.

**Description**

I'm using podman 3.2.2. on Ubuntu 20.04 and have a Kubernetes pod manifest on which I ran `podman play kube` (all of the follwing is in root mode). I then wanted to generate systemd files from it and ran `podman generate systemd --files --name --new PODNAME` which failed with the error message `Error: cannot use --new on pod "POD_HASH": no create command found`.

This [article](https://www.jwillikers.com/a-podman-pod-as-a-systemd-service) seems to suggest that it would be possible to use `generate systemd --new` after creating a pod with `play kube`. Not sure if this is true. How would one supply a create command or does this functionality not work with pods created from a Kubernetes manifest?

**Steps to reproduce the issue:**

1. Take the following manifest file:
```
apiVersion: v1
kind: Pod
metadata:
  name: docker-registry-proxy
spec:
  containers:
  - name: registry-proxy
    image: ghcr.io/rpardini/docker-registry-proxy:0.6.2
    env:
    - name: ENABLE_MANIFEST_CACHE
      value: "true"
    - name: CACHE_MAX_SIZE
      value: "10g"
    volumeMounts:
    - mountPath: /docker_mirror_cache
      name: mirror-cache
    - mountPath: /ca
      name: ca
    ports:
    - containerPort: 3128
      hostPort: 3128
  volumes:
  - name: mirror-cache
    hostPath:
      path: /opt/docker-registry-proxy/cache
  - name: ca
    persistentVolumeClaim:
      claimName: docker-registry-proxy-ca
```

2. Run `podman play kube`

3. Run `podman generate systemd --files --name --new PODNAME`

**Describe the results you received:**
`Error: cannot use --new on pod "POD_HASH": no create command found`

**Describe the results you expected:**
Command would generate systemd service files which create containers anew upon start.

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Output of `podman version`:**

```
Version:      3.2.2
API Version:  3.2.2
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.21.0
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 2
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: [redacted]
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.0-77-generic
  linkmode: dynamic
  memFree: 3590025216
  memTotal: 4026621952
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.20.1.5-925d-dirty
      commit: 0d42f1109fd73548f44b01b3e84d04a279e99d2e
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: [redacted]
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 2
  runRoot: /run/containers/storage
  volumePath: /mnt/storage/containers/volumes/root
version:
  APIVersion: 3.2.2
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 3.2.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 100:3.2.2-1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VCS

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Comment by vrothberg** [comment]
Thanks for reaching out, @nebulon42!

I think the article is wrong.  `podman generate systemd` requires the "create command" to be set for container/pod. The create command is, in fact, just the exact command (e.g., "podman run -d fedora top").  

>  How would one supply a create command or does this functionality not work with pods created from a Kubernetes manifest?

Since the create command is not set during "play kube", I fear this has never worked.  `podman generate systemd` only works on containers/pods created on the CLI:
```
$ podman pod create --name=testpod
$ podman create --pod=testpod --name=testcontainer fedora top
$ podman generate systemd --new testpod
```

I am going to close the issue, since `play kube` is something we cannot support.

**Comment by nebulon42** [comment]
Thank you for clarifying.
