### ISSUE TITLE
podman start --attach, a container created with --rm, does not rm the container

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#10935]
...at least, not immediately. There's a race condition, and the following test is actually broken:
https://github.com/containers/podman/blob/4c38202bd1f79e0c6dc4d5533e3412a3761192c4/test/e2e/start_test.go#L67-L78

Trivial reproducer:
```console
$ while :;do cid=$(./bin/podman create --rm quay.io/libpod/testimage:20210610 foo);./bin/podman start --attach $cid;./bin/podman container exists $cid && break;done
```
Will spit out a few iterations of errors, then break (because `podman container exists` succeeded).

Seems to be root & rootless

**Comment by vrothberg** [comment]
I am taking a look. Thanks for the reproducer, @edsantiago !

**Comment by vrothberg** [comment]
Small fix: `s/foo/ls/` in the reproducer.  `foo` will bark immediately as it doesn't exist on the image.

**Comment by edsantiago** [comment]
That's the point -- I was going with a reproducer of the exact same e2e test

**Comment by vrothberg** [comment]
For `ls` I think the race is natural; only `run` will wait for the container to be cleaned up.

My gut feeling is that this should be true for `foo` as well; should podman wait if the command succeeded (if so, for how long)?  But I'll have a look at the git history and see what Docker does.

**Comment by vrothberg** [comment]
Opened https://github.com/containers/podman/pull/10942.
