### ISSUE TITLE
failed to create rootless cni resolv.conf: open .../resolv.conf: no such file or directory

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#10930]
I think this is now our number-one flake:
```
Running: podman [options] run --name con1 --network IntTesta6a1514e70245da0670fc583887a7057165a3da069ad872452ca38bbcf957c44 quay.io/libpod/alpine:latest nslookup con1
Error: failed to create rootless cni resolv.conf: open /run/user/13502/rootless-cni/resolv.conf: no such file or directory
```
Once this happens, the system is forevermore broken, but further attempts give a different error:
```
Error: failed to mount netns directory for rootless cni: no such file or directory
```
It's a hard one to track down because once it fails, many other tests fail. I will try to follow up here after our f2f.

## Podman network [It] podman network prune
* fedora-34 : int podman fedora-34 rootless host
  * PR #10905
    * [07-12 09:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5861766438584320/html/int-podman-fedora-34-rootless-host.log.html#t--podman-network-prune--1)
    * [07-12 09:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5861766438584320/html/int-podman-fedora-34-rootless-host.log.html#t--podman-network-prune--2)
    * [07-12 09:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5861766438584320/html/int-podman-fedora-34-rootless-host.log.html#t--podman-network-prune--3)
  * PR #10879
    * [07-08 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5704491279319040/html/int-podman-fedora-34-rootless-host.log.html#t--podman-network-prune--1)
    * [07-08 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5704491279319040/html/int-podman-fedora-34-rootless-host.log.html#t--podman-network-prune--2)
    * [07-08 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5704491279319040/html/int-podman-fedora-34-rootless-host.log.html#t--podman-network-prune--3)

## Podman run networking [It] podman run check dnsname plugin
* fedora-33 : int podman fedora-33 rootless host
  * PR #10921
    * [07-13 09:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4899261046325248/html/int-podman-fedora-33-rootless-host.log.html#t--podman-run-check-dnsname-plugin--1)
    * [07-13 09:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4899261046325248/html/int-podman-fedora-33-rootless-host.log.html#t--podman-run-check-dnsname-plugin--2)
    * [07-13 09:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4899261046325248/html/int-podman-fedora-33-rootless-host.log.html#t--podman-run-check-dnsname-plugin--3)
  * PR #10896
    * [07-09 18:56](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6104318945263616/html/int-podman-fedora-33-rootless-host.log.html#t--podman-run-check-dnsname-plugin--1)
    * [07-09 18:56](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6104318945263616/html/int-podman-fedora-33-rootless-host.log.html#t--podman-run-check-dnsname-plugin--2)
    * [07-09 18:56](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6104318945263616/html/int-podman-fedora-33-rootless-host.log.html#t--podman-run-check-dnsname-plugin--3)

**Comment by Luap99** [comment]
I know what is going on. It is a race between the cleanup and setup for the rootless cni namespace. I think I know how to fix this.
