### ISSUE TITLE
Failed to decode the keys ["secret" "secret.opts"] from "/usr/share/containers/containers.conf"

### ISSUE THREAD

**Issue by cevich** [containers/podman#10934]
/kind bug

**Description**

[After building brand-new-fresh VM images for our CI system w/ updates pacakges](https://github.com/containers/automation_images/pull/82), numerous errors/failures are appearing.  In particular on F34 and Ubuntu (log lo, there are many integration test failures and the logs are splattered with this error message.

**Steps to reproduce the issue:**

1. Edit `.cirrus.yml` to use `IMAGE_SUFFIX: "c6248193773010944"`
2. [Let CI run the integration tests](https://github.com/containers/podman/pull/10829#issuecomment-880199612) (PR comment w/ log links)

**Describe the results you received:**

Logs riddled with this warning message ([Ubuntu example](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6244339543179264/html/int-remote-ubuntu-2010-root-host.log.html#t--podman-run---uidmap--etc-hosts-contains---hostname--1))

**Describe the results you expected:**

All CI tests should pass w/o this warning.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

[Compiled from source.](https://github.com/containers/podman/commit/1611e0e5a335a024d1e58b7fc36fb0f931e13799)

**Output of `podman info --debug`:**

[From Fedora 34 CI run](https://cirrus-ci.com/task/5012886520070144?logs=podman_system_info#L0)

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

[From Fedora 34 CI run](https://cirrus-ci.com/task/5012886520070144?logs=package_versions#L1)

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Podman testing in Cirrus-CI

**Comment by vrothberg** [comment]
We saw that coming. @rhatdan, PTAL.

What we need to do is to update the containers.conf in the packages.  We had the same problem in Buildah CI and temporarily removed /usr/share/containers/containers.conf until the issue is resolved.

Background: containers/common is now checking for config errors in containers.conf and warns about them.  The annoying issue now is that we actually had such a config error in the containers.conf we ship in Fedora, Ubuntu, etc.

**Comment by vrothberg** [comment]
@lsm5, can you double check that we ship the latest containers.conf (from https://github.com/containers/common/blob/main/pkg/config/containers.conf) in our packages?

From what I could see, RHEL is _not_ impacted.

**Comment by cevich** [comment]
> The annoying issue now is that we actually had such a config error in the containers.conf we ship in Fedora, Ubuntu, etc.

Ugh, well, at least out testing is keeping us honest :smirk: 

> in our packages?

@lsm5 to be very specific here (as it relates to CI):

    * F34 Updates-testing repo.
    * F33 Updates repo.
    * Ubuntu 20.10 & 21.04 Kubik testing repo.

**Comment by rhatdan** [comment]
@cevich This should fix the rootless podman on F33 selinux issue.
https://bodhi.fedoraproject.org/updates/FEDORA-2021-862d1936a6
This should fix containers-common on f34
https://bodhi.fedoraproject.org/updates/FEDORA-2021-01325d81c4

**Comment by cevich** [comment]
Fantastic, thanks!

**Comment by vrothberg** [comment]
I am going to close as it is a packaging issue in Fedora.
