### ISSUE TITLE
iscsi and volume

### ISSUE THREAD

**Issue by snail59** [containers/podman#10946]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I have an LVM logical volume on top of an iscsi LUN, mounted on a directory ( let's call it /foo/bar ) :
iscsi -> LVM -> logical volume -> /foo/bar

I ran something like podman run -v /foo/bar:/my_container_directory my_image .
Only /foo was mounted on /my_container_directory  in the container, not /foo/bar.

**Steps to reproduce the issue:**

1. add an iscsi target to your machine

2. create an lvm volume or a filesystem on this volume

3. try to bind it to a container

**Describe the results you received:**
The mount command run in the container shows that /foo is mounted on /my_container_directory in the container

**Describe the results you expected:**
I expected /foo/bar to be mounted on /my_container_directory in the container, instead of /foo.

**Additional information you deem important (e.g. issue happens only occasionally):**
I tried this with docker and it worked fine.
**Output of `podman version`:**

```
Version:      3.2.1
API Version:  3.2.1
Go Version:   go1.16.5
OS/Arch:      linux/amd64

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
*  app-emulation/podman
      Latest version available: 3.2.1
      Latest version installed: 3.2.1
      Size of files: 10 503 KiB
      Homepage:      https://github.com/containers/podman/
      Description:   Library and podman tool for running OCI-based containers in Pods
      License:       Apache-2.0 BSD BSD-2 CC-BY-SA-4.0 ISC MIT MPL-2.0
This is on gentoo
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No/Maybe I don't know

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical

**Comment by Luap99** [comment]
Can you try with `-v /foo/bar:/my_container_directory:rbind`.

> If you want to recursively mount a volume and all of its submounts into a container, then you can use the rbind option. By default the bind option is used, and submounts of the source directory will not be mounted into the container.

From https://github.com/containers/podman/blob/main/docs/source/markdown/podman-create.1.md#--volume--vsource-volumehost-dircontainer-diroptions

**Comment by snail59** [comment]
I tried, it does not work either.
Interesting facts are that: 
- / is mounted from an LVM logical volume ( so /foo is already a mountpoint on a mountpoint) 
- it works if /foo/bar is a zfs dataset
- it works perfectly well with docker
So I do not think this is a bind problem

**Comment by Luap99** [comment]
@mheon @rhatdan PTAL

**Comment by mheon** [comment]
Can you provide a `podman inspect` of the container showing this behavior?

**Comment by rhatdan** [comment]
@rhvgoyal WDYT?

**Comment by snail59** [comment]
> Can you provide a `podman inspect` of the container showing this behavior?

Here it is :
[podman_inspect.json.txt](https://github.com/containers/podman/files/6825932/podman_inspect.json.txt)

**Comment by mheon** [comment]
I see 3 bind mounts in there (`Binds` under `HostConfig` in the output). Can you verify they look correct relative to what you typed in? If so, this seems like a potential OCI runtime, or even kernel, issue - if we parsed the mounts correctly and they appear correct in Inspect, we've done everything Podman needs to, and are handing off correct information to the OCI runtime, which subsequently makes the mounts as kernel bind-mounts.

**Comment by snail59** [comment]
> I see 3 bind mounts in there (`Binds` under `HostConfig` in the output). Can you verify they look correct relative to what you typed in? If so, this seems like a potential OCI runtime, or even kernel, issue - if we parsed the mounts correctly and they appear correct in Inspect, we've done everything Podman needs to, and are handing off correct information to the OCI runtime, which subsequently makes the mounts as kernel bind-mounts.

I am not sure.
I ran a simple test with alpine and compared docker to podman in different scenarios.

1) a lun with ext4 filesystem
```
docker run -it --rm -v /media/lineageos/lo-18.1:/demo docker.io/library/alpine mount -t ext4
/dev/mapper/lo181-part1 on /demo type ext4 (rw,noatime,stripe=256)
```
The mount is OK with docker ( /dev/mapper/lo181-part1 was expected )
```
podman run -it --rm -v /media/lineageos/lo-18.0:/demo docker.io/library/alpine mount -t ext4
/dev/mapper/vgpulse-lvlineageos on /demo type ext4 (rw,noatime)
```
The mount is not ok with podman

2) no lun, zfs filesystem

```
docker run -it --rm -v /media/lineageos/lo-17.1:/demo docker.io/library/alpine mount -t zfs
[...]
zdonnees/lineageos/lo-17.1 on /demo type zfs (rw,noatime,xattr,noacl)
```
The mount is OK with docker

```
podman run -it --rm -v /media/lineageos/lo-17.1:/demo docker.io/library/alpine mount -t zfs
zdonnees/lineageos/lo-17.1 on /demo type zfs (rw,noatime,xattr,noacl)
```
The mount is also OK with podman

3) a lun with zfs

```
docker run -it --rm -v /media/lineageos/lo-19.0:/demo docker.io/library/alpine mount -t zfs
lo190 on /demo type zfs (rw,xattr,noacl)
```
The mount is OK with docker (it shows **lo190** on the left because I am using the root dataset of a zpool named lo190)

`podman run -it --rm -v /media/lineageos/lo-19.0:/demo docker.io/library/alpine mount -t zfs`

The mount is NOT OK with podman

4) a deeper mountpoint 

Here, I tried to mount the zfs lun inside the ext4 one:

```
docker run -it --rm -v /media/lineageos/lo-18.0/lo-19.0/:/demo docker.io/library/alpine mount -t zfs
[...]
lo190 on /demo type zfs (rw,xattr,noacl)
```
The mountpoint is OK with docker

```
podman run -it --rm -v /media/lineageos/lo-18.0/lo-19.0/:/demo docker.io/library/alpine mount -t zfs
Error: statfs /media/lineageos/lo-18.0/lo-19.0: no such file or directory
```
Podman is not happy with this.

I may have done something wrong, but I am more inclined to think there is a problem with podman because it runs fine with docker.

In both cases, the runtimes are the same one (same machine) :

```
podman info | grep ociRuntime -A 7
  ociRuntime:
    name: runc
    package: app-emulation/runc-1.0.0_rc95
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc95
      commit: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
      spec: 1.0.2-dev
```

```
docker info |grep -E 'Default Runtime|runc version'
 Default Runtime: runc
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
```

**Comment by mheon** [comment]
Any chance you can try with the `crun` OCI runtime instead? Bit of a longshot, but I'd like to see if it behaves differently.

**Comment by snail59** [comment]
> Any chance you can try with the `crun` OCI runtime instead? Bit of a longshot, but I'd like to see if it behaves differently.

I tried, the result is the same :-)

**Comment by mheon** [comment]
Can you do a `podman init` on a container with a bad bind-mount, do a `podman inspect` on it, and provide the file pointed to by the `OCIConfigPath` field? That's the OCI runtime config, what Podman is actually instructing the runtime to do. Ideally I'd want the Docker one as well to diff against, but I'm not 100% familiar with where they store them - have to look into that.

**Comment by snail59** [comment]
I am going to need guidance here, I shamly do not know how to use podman init

**Comment by mheon** [comment]
Make the container exactly as you were previously but with `podman create` instead of `podman run`, then run `podman init` on the newly-created but not running container. This will create the container configuration and prepare it to be started, but will not actually start the container.

**Comment by snail59** [comment]
Here is the file for podman.[config.json.txt](https://github.com/containers/podman/files/6832899/config.json.txt)
I could not find the equivalent one for docker, unfortunately.

**Comment by snail59** [comment]
I tried as root and it worked.
I do not know if that means that I did something wrong or if this is a bug/feature of podman.
If I did something wrong, could you please direct me to the information I missed in the documentation ? And I would (really) kindly suggest to maybe document this case (using mountpoint  from iscsi lun) or add a message in podman, that might be of help for other users.
Tell me if you need more informations.

**Comment by rhatdan** [comment]
So this is a rootless versus rootfull issue.  The recursive bind mount is working in rootfull mode, but not in rootless.  Could be the OCI Runtime doing something different.

**Comment by snail59** [comment]
Again, the oci runtime is the same one in both cases ( podman and docker).
That is weird, isn't it ?

**Comment by mheon** [comment]
Is Docker running as root? If your user is added to the Docker group and you're accessing the root Docker daemon, that could very well be our difference.

**Comment by snail59** [comment]
Yes, my user is in the docker group, so I agree with you that this could be the difference.
My point is, s I said before,my wish is, as a user, to understand what I "did wrong". 
From a developer point of view this might be obvious, but to be honest I do not think so as this did not come to your minds instantly.
Be assured that my point is not to criticize, english is not my language so it is not easy to bring nuances I would like to. I just want to point that, as a ( even not beginner) user, things do not seem obvious and that the gap between docker and podman is not that thin. i could not find any reason why this did not work in documentation so maybe, maybe, it should be kind of improved to allow beginners to switch easily.
 I still do not know what to do for this to work with podman while I neither had issue with docker nor had to think about how to do this, it went smoothly. I would love to know what I should have done in this case.
I hope you ,developers, understand my point here; again, english is not my mother tong.

**Comment by rhatdan** [comment]
I have a feeling this is a use namespace issue.  I wish we had a reproducer for this.  I tried to duplicate using bind mounts and it worked fine.

**Comment by rhatdan** [comment]
@giuseppe any ideas?

**Comment by giuseppe** [comment]
Does the mount exist from the `podman unshare` environment?

It could be that the mountwas created after the unprivileged user+mount namespace and its parent has the propagation set to private.

It could be helpful to show the output of `podman unshare findmnt -o PROPAGATION,TARGET /`

**Comment by snail59** [comment]
```
podman unshare findmnt -o PROPAGATION,TARGET /
PROPAGATION TARGET
private     /
```


```
podman unshare findmnt -o PROPAGATION,TARGET /media/lineageos/lo-18.1
Error: exit status 1
```

**Comment by giuseppe** [comment]
sorry my mistake, I forgot the `-R` argument to findmnt.

So it seems the `/media/lineageos/lo-18.1` mount is not available in the unprivileged mount namespace.

Can you try running `podman system migrate` to recreate the user+mount namespace (it stops all running containers), and repeat again the findmnt command?  Does the mount exist now?

**Comment by snail59** [comment]
I appeared thanks to the migrate command.
And then, my container ran successfully !
Thank you.

Could you please explain what this command did exactly ?
You wrote that it would **re**create the namespace which implies that it should have been created in first instance. But I did not do anything to create it from the beginning and would like to know/understand what I missed or failed.

**Comment by rhatdan** [comment]
The first time you run rootless Podman after boot, it creates a user/mount namespace and keeps the Podman executable running in the background.  This reserves the namespace and future executions of Podman just join the existing namespace.  The reason we do this is to prevent race conditions, where one podman is remove the user namespace at the same time as one is creating it.
Since the user namespace was created before the mount, we do not see the new mounts.

If you rebooted the machine or logged out and logged back in, the Podman user namespace would be recreated.

`podman system migrate` is just a quick way to migrate from the old usernamespace to a new one.

**Comment by rhatdan** [comment]
This seems like a useful blog.

**Comment by snail59** [comment]
Ok, thank you for the clear information.
Have a nice day, podman people ;-)

**Comment by giuseppe** [comment]
One thing to investigate is why the new mount was not propagated. Why is it mounted as MS_PRIVATE?

There wouldn't be such issue if the mount was using MS_SHARED or MS_SLAVE

**Comment by rhatdan** [comment]
@giuseppe interested in writing a blog on this when you get back from PTO?

**Comment by giuseppe** [comment]
sure, we can blog about this issue but it should not really happen unless the mount point is configured to `MS_PRIVATE`.  With the default configuration, on Fedora at least, this is not the case.

@snail59 could you provide more information on how the mount is performed?

**Comment by rhatdan** [comment]
I was thinking of a blog on the user namespace podman process.  Changes to the config like /etc/subuid and /etc/subgid require this processes be restarted via a podman system migrate.  Now we have a second example of needing to restart the namespace.  In the long run, I would love to get rid of this process if there are no containers running on the system, which would for the most part remove this problem, as long as you stop all containers.

**Comment by snail59** [comment]
@giuseppe : when my computer boots, the mountpoint is not automatically mounted and I mount it manually whenever I want.
As @rhatdan explained, if I launch podman for whatever reason ( `podman images` for example) before mounting the mountpoint, then podman won't be aware of it and, in my case, will fail at running my container.

So, by the way, this is absolutely not an iscsi problem but a ordering problem between launching podman and mounting a mountpoint.

As a non-expert-at-all, my thought would be to launch `podman system migrate` on every podman call. Would that be stupid or problematic for already running containers ?

**Comment by giuseppe** [comment]
> As a non-expert-at-all, my thought would be to launch `podman system migrate` on every podman call. Would that be stupid or problematic for already running containers ?

that will restart all the containers.  So you shouldn't do that unless there is a change in the host that must be propagated to the rootless user namespace.

How do you manually mount it?  Using the `mount` command?

How does `findmnt -R -o PROPAGATION,TARGET /` look like on the host before you mount it?

**Comment by snail59** [comment]
`that will restart all the containers`
Ok, that is a bad idea of mine ;-)

`How do you manually mount it? Using the mount command?`
Exactly, as root

> How does findmnt -R -o PROPAGATION,TARGET / look like on the host before you mount it?

The propagation is private for all mountpoints.
Of course, my iscsi mountpoint is not listed. I won't show data mountpoints as there are many, but here are the system ones, if it is of any help:

```
PROPAGATION TARGET
private     ├─/proc
private     │ └─/proc/sys/fs/binfmt_misc
private     ├─/sys
private     │ ├─/sys/kernel/security
private     │ ├─/sys/kernel/debug
private     │ ├─/sys/fs/fuse/connections
private     │ ├─/sys/fs/pstore
private     │ └─/sys/fs/cgroup
private     │   ├─/sys/fs/cgroup/openrc
private     │   ├─/sys/fs/cgroup/unified
private     │   ├─/sys/fs/cgroup/cpuset
private     │   ├─/sys/fs/cgroup/cpu
private     │   ├─/sys/fs/cgroup/cpuacct
private     │   ├─/sys/fs/cgroup/blkio
private     │   ├─/sys/fs/cgroup/memory
private     │   ├─/sys/fs/cgroup/devices
private     │   ├─/sys/fs/cgroup/freezer
private     │   ├─/sys/fs/cgroup/net_cls
private     │   ├─/sys/fs/cgroup/perf_event
private     │   ├─/sys/fs/cgroup/net_prio
private     │   ├─/sys/fs/cgroup/hugetlb
private     │   ├─/sys/fs/cgroup/pids
private     │   ├─/sys/fs/cgroup/rdma
private     │   ├─/sys/fs/cgroup/debug
private     │   └─/sys/fs/cgroup/systemd
private     ├─/dev
private     │ ├─/dev/pts
private     │ ├─/dev/shm
private     │ └─/dev/mqueue
```

Tell me if you need more informations.

**Comment by giuseppe** [comment]
thanks for confirming it.  The mounts on the host are configured to `private`, so any new mount won't be propagated inside the rootless mount namespace.

What distro are you using?  Have you changed anything in the default configuration?  Perhaps it is worth to report an issue.

I'd suggest using `slave` or even better `shared` instead of `private`.  Fedora is using the latter by default.

**Comment by rhatdan** [comment]
Systemd sets up shared,  Kernel defaults to private.

**Comment by giuseppe** [comment]
opened a PR to print a warning when `/` is not mounted as shared: https://github.com/containers/podman/pull/11056
