### ISSUE TITLE
"podman info" fails on MacOS

### ISSUE THREAD

**Issue by bentito** [containers/podman#10944]
/kind bug

**Description**

Fresh upgrade of podman on MacOS via Homebrew fails to execute

**Steps to reproduce the issue:**

1. `brew install podman` (or `brew upgrade podman` if already installed via brew)

2. type `podman info`

**Describe the results you received:**

```bash
$ podman info
Error: cannot connect to the Podman socket, please verify that Podman REST API service is running: Get "http://d/v3.2.2/libpod/_ping": dial unix ///var/folders/s2/5qv42zmn6678nhr8sgd2njj00000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```

**Describe the results you expected:**
Output of info about podman system. Also, this is same result for other basic operations of podman.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
```bash
$ podman version
Error: cannot connect to the Podman socket, please verify that Podman REST API service is running: Get "http://d/v3.2.2/libpod/_ping": dial unix ///var/folders/s2/5qv42zmn6678nhr8sgd2njj00000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```

**Output of `podman info --debug`:**

```
(fails also)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```bash
$ brew upgrade podman
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core and homebrew/cask).
==> Updated Formulae
Updated 10 formulae.
==> Updated Casks
Updated 1 cask.

Warning: podman 3.2.2 already installed
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```bash
$ sw_vers
ProductName:	macOS
ProductVersion:	11.3.1
BuildVersion:	20E241
```

**Comment by mheon** [comment]
@baude Good candidate for machine?

**Comment by ashley-cui** [comment]
@bentito do you have a vm running? (podman machine or otherwise?) 

i think this should just be a error message fix, on macs display an error message that says "do you have a vm running? podman machine -h" or something like that?

**Comment by rhatdan** [comment]
Yes, I think this would be a nice fix for MAC/Windows.

**Comment by bentito** [comment]
But, also:
```bash
$ podman machine init
Error: exec: "qemu-system-x86_64": executable file not found in $PATH
```

**Comment by ashley-cui** [comment]
@bentito ah yeah we need to fix our dependencies for homebrew installations. i think i can get that in soon, but for now, do a `brew install qemu` , then you can get a machine up.

**Comment by bentito** [comment]
okay, so `brew install podman && brew install qemu && podman machine init && podman machine start` then `podman info` and, I suspect, all things podman, work on MacOS now for me. ty!

**Comment by rhatdan** [comment]
@ashley-cui Does brew install have the equivalent of a "recommends" versus a "requires",  Meaning you could install `podman` without installing `qemu`?

**Comment by ashley-cui** [comment]
@rhatdan yes! there's a `recommended` which installs by default and an `optional` that only installs if specified. there's also a only install dependency on intel vs m1.

I was thinking of making qemu a recommended dependency on intel only (because qemu still needs patches for m1), and on m1 printing a warning about qemu patches.  do you think recommended works better or optional for now?

**Comment by rhatdan** [comment]
SGTM

**Comment by bentito** [comment]
`reccomended` when Intel present sounds like a better user experience to me.

**Comment by ashley-cui** [comment]
update: brew doesn't allow recommended in its core repo. looks like its going to have to go in either as a dependency or not :(

@rhatdan @bentito

**Comment by rhatdan** [comment]
Make it a dependency.  How large is it?

**Comment by bentito** [comment]
so after `brew upgrade podman` just now, same system info as above, I am getting:
``` $ podman info
Error: failed to create sshClient: Connection to bastion host (ssh://core@localhost:51687/run/user/1000/podman/podman.sock) failed.: dial tcp [::1]:51687: connect: connection refused```

**Comment by bentito** [comment]
I deleted the old services, so then I just get: ```$ podman system connection list
$ podman info
Error: cannot connect to the Podman socket, please verify that Podman REST API service is running: Get "http://d/v3.2.3/libpod/_ping": dial unix ///var/folders/s2/5qv42zmn6678nhr8sgd2njj00000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory```

Info for starting service again seems outdated here:
https://www.redhat.com/sysadmin/podmans-new-rest-api

**Comment by ashley-cui** [comment]
I don't think the PR for the fix yet has merged: https://github.com/containers/podman/pull/11192. We'll see if we can get this in today/soon

**Comment by NeckBeardPrince** [comment]
> podman machine init && podman machine start

These would be helpful https://podman.io/getting-started/installation and https://github.com/containers/podman/blob/main/docs/tutorials/mac_win_client.md.

Neither of these docs tell you that you have to `machine init` and then `machine start`.

**Comment by baude** [comment]
> > podman machine init && podman machine start
> 
> These would be helpful https://podman.io/getting-started/installation and https://github.com/containers/podman/blob/main/docs/tutorials/mac_win_client.md.
> 
> Neither of these docs tell you that you have to `machine init` and then `machine start`.

Mind doing a PR?

**Comment by NeckBeardPrince** [comment]
> > > podman machine init && podman machine start
> > 
> > 
> > These would be helpful https://podman.io/getting-started/installation and https://github.com/containers/podman/blob/main/docs/tutorials/mac_win_client.md.
> > Neither of these docs tell you that you have to `machine init` and then `machine start`.
> 
> Mind doing a PR?

Looks like someone [did](https://github.com/containers/podman/pull/10565) but looks like nothing links to it https://github.com/containers/podman/blob/main/docs/tutorials/mac_experimental.md.

**Comment by daniellaera** [comment]
`❯ podman machine start`
`Error: due to missing upstream patches, Apple Silicon is not capable of running Podman machine yet`
is someone having this

**Comment by NeckBeardPrince** [comment]
> `❯ podman machine start`
> `Error: due to missing upstream patches, Apple Silicon is not capable of running Podman machine yet`
> is someone having this

I would assume everyone who is running Apple Silicon.

**Comment by rhatdan** [comment]
Should be fixed soon...
