### ISSUE TITLE
Switching to overlay2 storage driver causes new problems with podman 3.2.2

### ISSUE THREAD

**Issue by alitvak69** [containers/podman#10955]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

overlay2 stopped working

After update to the latest 3.2.2 and buildah 1.21.1  certain features stopped working if overlay2 specified as storage driver.
Command _podman info_ no longer works unless prefixed with sudo.  I cannot build a container either. 

**Steps to reproduce the issue:**

1. Change storage.conf driver from overlay to overlay2. Execute podman system reset to cleanup and remove local .cache and .configs related to containers

2.  Run _podman info_ as non-root user

3. Also  try building image with 
podman build --format=docker  -t myrepo.io/xyz:latest . 

**Describe the results you received:**
```
$ podman ps
Error: kernel does not support overlay fs: kernel too old to provide multiple lowers feature for overlay: driver not supported
```
This only happens when run as non root but works fine when I add sudo

Also 
```
sudo podman build --log-level=debug --format=docker -t docker.xcastlabs.net/mysql/mysql8-server:1.1 -t docker.xcastlabs.net/mysql/mysql8-server:latest .
```
ERRO[0007] error deleting build container "e9440197c0f1d13958efbc54c14c4c801191e37fea47c6ce6111daf9a0547ec0": identifier is not a container 
DEBU[0007] Failed to cleanup intermediate containers: identifier is not a container 
Error: identifier is not a container: error preparing container for next step: error creating build container: error creating container: error creating read-write layer with ID "879b09f3be658711c7df107e0cd3c3dd75f7316257d3d9ae1d3aaf387ac5c301": Stat /var/lib/containers/storage/overlay/d3608bc9c34af538e0e57cba7c5dc217132635533ead3cfacbc0aa83f06592d8: no such file or directory

However: 
/var/lib/containers/storage/overlay/d3608bc9c34af538e0e57cba7c5dc217132635533ead3cfacbc0aa83f06592d8 
is located in
/var/lib/containers/storage/overlay2/d3608bc9c34af538e0e57cba7c5dc217132635533ead3cfacbc0aa83f06592d8
as it should, but podman or buildah looking for it in /var/lib/containers/storage/overlay/

**Describe the results you expected:**
A successful execution of podman info and successful build of the image.  As I said, going back to overlay makes things to work again.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.2.2
API Version:  3.2.2
Go Version:   go1.15.2
Built:        Wed Dec 31 16:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.21.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 4
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: alex3.xcastlabs.net
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 296608
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 296608
      size: 65536
  kernel: 5.4.0-45-generic
  linkmode: dynamic
  memFree: 2109612032
  memTotal: 4126879744
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.20.1.5-925d-dirty
      commit: 0d42f1109fd73548f44b01b3e84d04a279e99d2e
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1002/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 0
  swapTotal: 0
  uptime: 7646h 11m 29.96s (Approximately 318.58 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/alexl/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.9.0
        fuse-overlayfs: version 1.5
        FUSE library version 3.9.0
        using FUSE kernel interface version 7.31
  graphRoot: /home/alexl/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1002/containers
  volumePath: /home/alexl/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.2
  Built: 0
  BuiltTime: Wed Dec 31 16:00:00 1969
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 3.2.2

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 100:3.2.2-1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
$ uname -r
5.4.0-45-generic
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by vrothberg** [comment]
@rhatdan PTAL

**Comment by rhatdan** [comment]
If you change it back to overlay does it work correctly?  overlay == overlay2, there is no difference in Podman.  We only use the overlay2 name for compatibility with Docker.

**Comment by alitvak69** [comment]
@rhatdan That is correct but it was working with previous versions.  Even 3.2.1, I believe.

**Comment by rhatdan** [comment]
I have no idea why this would not be working with overlay2.  I tried this on my Fedora machine and everything works fine.
Only thing I can think of is, some override check is failing when driver is overlay2

**Comment by rhatdan** [comment]
https://github.com/containers/storage/pull/966 might fix this, since we really do not want to deal with overlay2 at all.  Docker made a mistake when they renamed the driver.  No one uses the original overlay driver, so when we started making our container tools we just aliased the driver names together.

**Comment by alitvak69** [comment]
@rhatdan I tried it both on Ubuntu  20.04 and centos 7.9 with our nix static podman and buildah.  However, I will wait for #966  to clear the merge and test it then.  My problem with just going back to overlay  is I have to run podman system reset on multiple nodes.  It requires restarting bunch of containers and re-downloading bunch of images.

**Comment by rhatdan** [comment]
You could just set up a sympolic link between the two directories.

**Comment by alitvak69** [comment]
I could do that, but to do that I have to stop all the containers anyway.  Otherwise real directory /var/lib/containers/overlay is still in use and cannot be deleted before I could symlink it overlay2

**Comment by alitvak69** [comment]
@rhatdan I guess containers/storage#966 have not been merged.  Is it going to be or you guys had other thoughts about the issue?

**Comment by rhatdan** [comment]
We have to hold off until we are ready to ship podman 4. since this is a breaking change.  It will cause the same issue you are having.

**Comment by onedr0p** [comment]
This is still an issue.

**Comment by giuseppe** [comment]
> I could do that, but to do that I have to stop all the containers anyway. Otherwise real directory /var/lib/containers/overlay is still in use and cannot be deleted before I could symlink it overlay2

you'd still need to do a `system reset` since the driver has changed, and Podman will complain with:

```
ERRO[0000] User-selected graph driver "overlay" overwritten by graph driver "overlay2" from database - delete libpod local files to resolve
```

so I am not sure the fix for containers/storage will be helpful for your use case.

**Comment by awfulcooking** [comment]
Fwiw, I found that this caused a DoS for other accounts on the system. None of them could start or create containers and I ended up restoring the system from backup to fix it. I wasn't 110% sure I hadn't done something else to cause the problem, but I think it's worth investigating

**Comment by rhatdan** [comment]
Were you using overlay2?

**Comment by awfulcooking** [comment]
```
$ podman system reset
ERRO[0000] User-selected graph driver "overlay" overwritten by graph driver "vfs" from database - delete libpod local files to resolve 
ERRO[0000] User-selected graph driver "overlay" overwritten by graph driver "vfs" from database - delete libpod local files to resolve 
Error: vfs driver does not support overlay.mount_program options
```

Sorry if this is a separate issue. I think I was linked here from IRC when I described it. I'll try to reproduce it in a VM.

**Comment by rhatdan** [comment]
I believe this is now fixed in the main branch.  You should get a loud warning if you are attempting to use overlay2.
