### ISSUE TITLE
podman auto-update always restarts containers

### ISSUE THREAD

**Issue by Fodoj** [containers/podman#10959]
podman auto-update always restarts containers, even if image didn't change. To reproduce (note I am using user systemd):

```
podman pod create --name podA
podman run --label io.containers.autoupdate=image --pod dockerless -d quay.io/kshirinkin/dockerless-curl:v1 sleep infinite
podman generate systemd dockerless --name -f --new
mv *.service /home/MYUSER/.config/systemd/user/
systemctl start pod-podA --user
podman auto-update
```

Even though I never change the image, `podman auto-update` always pulls, kills container, creates new one. Expectation was that if image didnt change, nothing will happen.

```
podman version 3.1.2
```

```
Fedora release 33 (Thirty Three)
5.12.8-200.fc33.x86_64

```

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Comment by vrothberg** [comment]
Thanks for reaching out, @Fodoj!  

That's likely a bug in the Podman 3.1.2.  I couldn't reproduce with Podman 3.2.2, so I am going to close.

Note that `auto-update` received some rework to provide more useful output to the user. Starting with Podman v3.3.0, the output will look as follows:
```
$ podman auto-update
UNIT                              CONTAINER                      IMAGE                                  POLICY      UPDATED
container-priceless_cerf.service  a6c4625ceb7f (friendly_yalow)  quay.io/kshirinkin/dockerless-curl:v1  registry    false
```
