### ISSUE TITLE
3.2.3: No chain of trust for release

### ISSUE THREAD

**Issue by dvzrv** [containers/podman#10972]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Hi, @Foxboron and I are packaging podman for Arch Linux. We use the signatures of release tags to verify the authenticity of this upstream. With the release of 3.2.3 we have run into the issue, that the current release is signed by a PGP key for which we can not establish a trust path.

Most releases (except a few release candidate releases done by @rhatdan ) have been made by @mheon, signed with `B7DBDCA456F7335E91F1C25CD3624C551D0515C4`.
The 3.2.3 release is made by @ashley-cui using `7CE1E6F8C90CB53E7E4D8F2D502E08DB0BBF8EEE`.

However, I am unable to find any signatures of @mheon towards @ashley-cui's key and we are not able to upgrade to 3.2.3 to prevent a potential supply chain attack in progress (no offense).

**Steps to reproduce the issue:**

1. `git clone https://github.com/containers/podman`

2. Attempt to ` gpg --auto-key-locate wkd --search-keys acui@redhat.com` (fails), `gpg --auto-key-locate wkd --search-keys mheon@redhat.com` (fails), `gpg --keyserver keyserver.ubuntu.com --search-keys acui@redhat.com` (fails) and `gpg --keyserver keyserver.ubuntu.com --search-keys mheon@redhat.com` (succeeds).

3. Eventually import keys from github: `git --import <(curl -O https://github.com/mheon.gpg)` and `git --import <(curl -O https://github.com/ashley-cui.gpg)`
4. Check signatures on new key: `gpg --list-sigs 7CE1E6F8C90CB53E7E4D8F2D502E08DB0BBF8EEE`
5. Check signatures for releases: `git verify-tag v3.2.2` and `git verify-tag v3.2.3` 

**Describe the results you received:**

I am unable to get the new key from anywhere but github. The new key does not have signatures from the key used previously.

**Describe the results you expected:**

The new key is available on keyservers and provides valid signatures by the previous key.

Ideally and/or alternatively the people (and their respective keys) allowed to create releases are declared in a central document in this repository, that is created in a signed commit by the keyholder of the initial trust (in this case @mheon). Further additions and removals are then only taking place by trusted entities.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
n/a

**Output of `podman info --debug`:**
n/a

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

n/a

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No (n/a)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
n/a

**Comment by mheon** [comment]
Ah, I can handle this once I get in on Monday.

For context, @ashley-cui is our backup engineer for releases, and handled yesterday's release to become familiar with the process before I leave for a vacation.

**Comment by dvzrv** [comment]
@mheon excellent! Thanks for looking into this before your holidays! <3

**Comment by dvzrv** [comment]
Hi! Is there any news on this? We are currently blocked from updating.

**Comment by ashley-cui** [comment]
@dvzrv I've added my keys to https://keys.openpgp.org. I'm not sure what else has been done/needs to be done, but @mheon is on vacation this week

**Comment by vrothberg** [comment]
Did we resolve the issue?

**Comment by mheon** [comment]
I have signed Ashley's key, but I am having trouble actually getting any keyserver to accept the signature. I've exported the signature and tried to attach it here, but Github appears to object to .asc files. I have renamed to .txt in an attempt to avoid this.
[acui.txt](https://github.com/containers/podman/files/6946276/acui.txt)

**Comment by Foxboron** [comment]
@mheon Because of recent keyserver issues this has become complicated. It's easier to send the signature to Ashley and have her upload it to a keyserver and/or github.
