### ISSUE TITLE
Podman logs doesn't exit for stopped container and after restarting container the log doesn't change and displays the same thing

### ISSUE THREAD

**Issue by lzmihoubi** [containers/podman#10971]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman `logs `doesn't exit for a stopped container and after restarting the container the log doesn't change and displays the same thing. 

**Steps to reproduce the issue:**

1. `podman run -d --name looper busybox /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'`

2. `podman logs -l`

3. `podman container checkpoint -l`

4. `podman logs -l`

5. `podman container restore -l`

6. `podman logs -l`

**Describe the results you received:**
Before the container is checkpointed (and thus stopped) the command `podman logs -l` works correctly (the log changes with every execution of the command and shows that the looper is progressing in its counting as it is supposed to). But once the container is stopped, whether it is restarted or stopped, the output to the command `podman logs -l` is always the next: 
`0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
`
The container was checkpointed once it reached 26 in its loop.

**Describe the results you expected:**

1. When running the command `podman logs -l` after stopping/checkpointing the container, I expect podman to exit correctly and display the message that the container is no running.
2. When running the command `podman logs -l` after restoring/restarting the container, I expect the log to change as the looper continues looping from where it was checkpointed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.2.2
API Version:  3.2.2
Go Version:   go1.15.2
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.21.0
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 8
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: relay
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.0-74-generic
  linkmode: dynamic
  memFree: 3342057472
  memTotal: 8347516928
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.20.1.5-925d-dirty
      commit: 0d42f1109fd73548f44b01b3e84d04a279e99d2e
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_                                                                                        NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 663h 58m 13.52s (Approximately 27.62 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.2.2
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 3.2.2

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 100:3.2.2-1 amd64 [installed]
podman/unknown 100:3.2.2-1 arm64
podman/unknown 100:3.2.2-1 armhf
podman/unknown 100:3.2.2-1 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm using a KVM virtual machine running a Ubuntu 20.04.2

**Comment by mheon** [comment]
Can you confirm that this is only when the container is stopped by checkpoint/restore, and normal `podman stop` / `podman start` cause logging to behave as expected?

**Comment by lzmihoubi** [comment]
I confirmed and it doesn't work even with a regular  podman stop / podman
start.

**Comment by mheon** [comment]
Interesting. @vrothberg The stop/start bit ought to work, right?

Can you provide a `podman inspect` of a container exhibiting symptoms, so we can determine the log driver in use? Doesn't look like the defaults for that are in `podman info`.

**Comment by vrothberg** [comment]
> When running the command podman logs -l after stopping/checkpointing the container, I expect podman to exit correctly and display the message that the container is no running.

`podman logs` never displayed that a container is not running.  Can you elaborate on "exit correctly"?  The exit code is 0 in the reproducer.

> When running the command podman logs -l after restoring/restarting the container, I expect the log to change as the looper continues looping from where it was checkpointed.

What I see locally _after_ stop/start is:
```
$ podman logs -l
0 1 2 ... 20 0 1 2 3 ...
```
That is what I would expect: Podman is displaying all logs of the container but does not clear the logs during restart.

> Interesting. @vrothberg The stop/start bit ought to work, right?

I do think it still works but we need to agree on what the correct behavior is.

```
~ $ podman run --name test --replace alpine date
38b4b19ec27da6d0f99c3d16c3dc3dd3ea69c05c2edaa2f8bfe6d3976bd70bbf
Tue Jul 20 14:22:46 UTC 2021
~ $ podman logs -l
Tue Jul 20 14:22:46 UTC 2021
~ $ podman start test
test
~ $ podman logs -l
Tue Jul 20 14:22:46 UTC 2021
Tue Jul 20 14:22:57 UTC 2021
```

**Comment by rhatdan** [comment]
That seems correct to me.

**Comment by vrothberg** [comment]
Closing as I think Podman behaves correctly. Feel free to reopen or comment if something pops up.
