### ISSUE TITLE
Image name different between podman versions after pulling from docker-daemon:// location

### ISSUE THREAD

**Issue by tetchel** [containers/podman#10998]
Podman version: 3.2.2

Previously, when pulling an image from the Docker image storage, the image in Podman would then be prefixed with `docker.io/library`.

eg.
`podman pull docker-daemon:myimage`
-> 
`podman images` has `docker.io/library/myimage`

But now, the image is prefixed with `localhost`.

eg.
`podman pull docker-daemon:myimage`
-> 
`podman images` has `locahost/myimage`

This is a good change, this behaviour makes a lot more sense. But I do not see it in the release notes.

I know this was changed sometime between versions 3.1.2 and 3.2.2 so I am assuming it was changed in the minor release 3.2.0.

But, since we now have to read the podman version to determine how the image will be tagged after pulling, we have to know the exact version that introduced the new behaviour. 

Does anyone know in which version of Podman this change was introduced?

re: https://github.com/redhat-actions/push-to-registry/issues/42#issuecomment-882056449

**Comment by tetchel** [comment]
possibly https://github.com/containers/common/commit/f109e1a662ade4b46618bbc68fc3dca85a436358 which went into common/0.38.5 which would mean podman/3.2.0

**Comment by rhatdan** [comment]
@vrothberg PTAL.

I believe the behavior should end up with an image named.

docker.io/library/myimage
 
Since this is what it is named in docker.io.

localhost/myimage indicates the image was created locally and does not have a default registry.  podman build images have this name.

**Comment by vrothberg** [comment]
Thanks for reaching out!  I'll take a look.

**Comment by vrothberg** [comment]
I opened https://github.com/containers/common/pull/685 to fix it.
