### ISSUE TITLE
podman build + workdir(?): Error adding network: failed to setup hairpin mode for veth3e067d53: operation not supported

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#11010]
This *seems* to be correlated with `podman run` of an image built with `workdir`. (It is not for me to understand why):
```
# podman build ...
...
STEP 5/25: WORKDIR /emkbn7Pa2r
...
# podman run thatimage ...
time="2021-07-15T13:33:54-05:00" level=error msg="error loading cached network config: network \"podman\" not found in CNI cache"
time="2021-07-15T13:33:54-05:00" level=warning msg="falling back to loading from existing plugins on disk"
Error: error configuring network namespace for container d7934ec1abb74c0fc57d5540482798f665bb41874ed916bc7603645ad7df622f: error adding pod boring_dhawan_boring_dhawan to CNI network "podman": failed to setup hairpin mode for vethb0252915: operation not supported
[ rc=126 (** EXPECTED 0 **) ]
```
Note the "error adding pod" message, despite no pods anywhere. Note also that "veth" appears in another buildah flake, https://github.com/containers/buildah/issues/2628, although there it's "failed to make veth pair".

### Podman network connect and disconnect [It] podman network connect when not running
* fedora-34 : int podman fedora-34 root host
  * PR #10688
    * [06-16 20:43](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6375706138509312/html/int-podman-fedora-34-root-host.log.html#t--podman-network-connect-when-not-running--1)

### sys: podman build - workdir, cmd, env, label
* fedora-34 : sys podman fedora-34 root host
  * PR #10947
    * [07-15 14:46](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6403209813032960/html/sys-podman-fedora-34-root-host.log.html)
* fedora-34 : sys remote fedora-34 root host [remote]
  * PR #10868
    * [07-09 14:12](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6255466528374784/html/sys-remote-fedora-34-root-host.log.html)
  * PR #10821
    * [06-29 20:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5069525583396864/html/sys-remote-fedora-34-root-host.log.html)

### Podman containers  [It] podman kill latest container with SIGTERM
* fedora-34 : Test Bindings
  * PR #10879
    * [07-08 08:37](https://api.cirrus-ci.com/v1/task/6043140860674048/logs/main.log)

Also in a [int-podman-fedora-34-root-container](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6243936386678784/html/int-podman-fedora-34-root-container.log.html) run that my flake referencer didn't seem to find

Also right now in my own PR, in [sys-podman-fedora-34-root-host](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5748593362468864/html/sys-podman-fedora-34-root-host.log.html) (not yet indexed by my flake catcher)

**Comment by rhatdan** [comment]
Coincidence, I just read the following:
https://github.com/containers/podman/issues/10052#issuecomment-884355182

@Luap99 Could this be related.

**Comment by edsantiago** [comment]
The #10052 issue is rootless, whereas this issue (so far) I've only seen in root.

**Comment by Luap99** [comment]
I don't think this is a podman issue. The bridge cni plugin tries to set the hairpin mode on the veth interface and this fails. It only failed on f34, this could be a kernel problem.

**Comment by rhatdan** [comment]
@edsantiago @Luap99 where do we stand on this one?

**Comment by edsantiago** [comment]
Seen twice last week:

### sys: podman logs - journald log driver requires journald events backend
* fedora-34 : sys podman fedora-34 root host
  * PR #11314
    * [08-24 14:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6644621242531840/html/sys-podman-fedora-34-root-host.log.html)

### Podman commit [It] podman commit with volume mounts and --include-volumes
* fedora-34 : int podman fedora-34 root host
  * PR #11202
    * [08-19 15:34](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5929720823939072/html/int-podman-fedora-34-root-host.log.html#t--podman-commit-with-volume-mounts-and---include-volumes--1)

**Comment by vrothberg** [comment]
@edsantiago are we still seeing this flake?

@Luap99 does @tlammi's comment on networkd interfering help?

**Comment by edsantiago** [comment]
The last instance I see in my flake logs is from September 14, and the log has been GC'ed, so I'll close.
