### ISSUE TITLE
Podman continuosly restarts every 5 sec

### ISSUE THREAD

**Issue by blindshare** [containers/podman#11020]
/kind bug

**Description**
Podman continuosly restarts every 5 sec

When I went through my /var/log/syslog I noticed that podman restarts every (aprox) 5 seconds without any apparent reason.
It look like this:

Jul 22 14:12:15 v2202106122433155620 systemd[807]: podman.service: Succeeded.
Jul 22 14:12:15 v2202106122433155620 systemd[807]: Finished Podman API Service.
Jul 22 14:12:15 v2202106122433155620 systemd[807]: Starting Podman API Service...
Jul 22 14:12:20 v2202106122433155620 systemd[807]: podman.service: Succeeded.
Jul 22 14:12:20 v2202106122433155620 systemd[807]: Finished Podman API Service.
Jul 22 14:12:20 v2202106122433155620 systemd[807]: Starting Podman API Service...
Jul 22 14:12:26 v2202106122433155620 systemd[807]: podman.service: Succeeded.
Jul 22 14:12:26 v2202106122433155620 systemd[807]: Finished Podman API Service.
Jul 22 14:12:26 v2202106122433155620 systemd[807]: Starting Podman API Service...
Jul 22 14:12:32 v2202106122433155620 systemd[807]: podman.service: Succeeded.
Jul 22 14:12:32 v2202106122433155620 systemd[807]: Finished Podman API Service.
Jul 22 14:12:32 v2202106122433155620 systemd[807]: Starting Podman API Service...

My System is:
  cat /etc/os-release 
  NAME="Ubuntu"
  VERSION="20.04.2 LTS (Focal Fossa)"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu 20.04.2 LTS"
  VERSION_ID="20.04"

  podman --version
  podman version 3.1.2

Podman gets launched via systemd with the "--user" option. This is the current configuration:
  cat /lib/systemd/system/podman.service

  [Unit]
  Description=Podman API Service
  Requires=podman.socket
  After=podman.socket
  Documentation=man:podman-system-service(1)
  StartLimitIntervalSec=0

  [Service]
  Type=exec
  Environment=LOGGING="--log-level=info"
  ExecStart=/usr/bin/podman $LOGGING system service

  cat /lib/systemd/system/podman.socket

  [Unit]
  Description=Podman API Socket
  Documentation=man:podman-system-service(1)

  [Socket]
  ListenStream=%t/podman/podman.sock
  SocketMode=0660

  [Install]
  WantedBy=sockets.target

The socket at /run/user/1000/podman/podman.socket get's constantly re-created
However, when I start the podman service manually I don't see this behavior 

  $ podman system service -t 0 &

**Comment by rhatdan** [comment]
Podman without the -t 0 will shut down in 5 seconds if noone is connected to it, it then is supposed to sit idle until someone hits the socket, and the podman service gets socket activated.

**Comment by mheon** [comment]
Yes - this is expected behavior. We shut down the service at idle to lower our resource consumption.

**Comment by blindshare** [comment]
So the sollution would be to alter this line:
`ExecStart=/usr/bin/podman $LOGGING system service`
to
`ExecStart=/usr/bin/podman -t 0 $LOGGING system service`
in: /lib/systemd/system/podman.service ?

**Comment by mheon** [comment]
If you do not want the service to idle, yes, that will prevent it from doing so.

**Comment by rhatdan** [comment]
I prefer
```
ExecStart=/usr/bin/podman $LOGGING system service -t 0
```

But why not use socket activation?  So the service would not always be running?
