### ISSUE TITLE
Error: OCI runtime error: container_linux.go:380: starting container process caused: error adding seccomp filter rule for syscall bdflush: requested action matches default action of filter

### ISSUE THREAD

**Issue by liaobaikai** [containers/podman#11029]
[root@localhost home]# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
[root@localhost home]# podman -v
podman version 3.0.1
[root@localhost home]# docker run -dit --name zk_01 --network  master-network --ip 172.20.0.11 zookeeper
Error: OCI runtime error: container_linux.go:380: starting container process caused: error adding seccomp filter rule for syscall bdflush: requested action matches default action of filter

**Comment by liaobaikai** [comment]
[root@liaobaikai ~]# cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)
[root@liaobaikai ~]# podman -v
podman version 3.0.1
[root@liaobaikai ~]# docker run -dit --name zk_03 --network  master-network --ip 172.20.0.13 zookeeper
bd622a72e3650c3434cdad235b1f308df4de37da5729674b8bc82379923b227d

**Comment by cdoern** [comment]
You are using docker not podman as the `container_linux` error you are getting is a common docker error. Try restarting docker daemon or even better, use podman :-)

**Comment by mheon** [comment]
That could easily have been Podman with the Docker alias added - that error
is out of runc, not Docker itself, so it can easily happen with Podman.
Usually points to a too old runc or libseccomp.

**Comment by cdoern** [comment]
@mheon I thought -dit was docker only, I will reopen sorry.

**Comment by cdoern** [comment]
still, container_linux also doesnt have a line 80, so I think this is docker

**Comment by mheon** [comment]
It’s pointing to a line in the runc codebase, which  AFAIK changed heavily
recently for the 1.0 release - a refactor to split the code into
subpackages. That sounds like a reasonable line number given that.

Speaking of runc versions, I suspect upgrading to the most recent will
resolve this.

**Comment by kolyshkin** [comment]
> Speaking of runc versions, I suspect upgrading to the most recent will resolve this.

It won't. The fix is in https://github.com/opencontainers/runc/pull/3109, but originally that comes from the fact that podman started to generate redundant seccomp rules recently. I have explained why that happens and what is the fix in https://github.com/containers/podman/issues/11005

**Comment by kolyshkin** [comment]
I think we can fix it in podman, too. 

First, we need https://github.com/containers/common/pull/689 (and cut a v0.38.17 release).
One a release is made, we need to bump containers/common to v0.38.17 in podman v3.2 branch.

https://github.com/containers/podman/issues/11005#issuecomment-885277879

**Comment by mheon** [comment]
OK, this sounds like it needs to be a priority backport. Thanks!

**Comment by liaobaikai** [comment]
[root@localhost ~]# /usr/bin/docker -v
podman version 3.0.1
[root@localhost ~]# rpm -qa | grep podman
podman-3.0.1-2.el7.3.1.x86_64
podman-plugins-3.0.1-2.el7.3.1.x86_64
podman-docker-3.0.1-2.el7.3.1.noarch
[root@localhost ~]# rpm -e podman-docker-3.0.1-2.el7.3.1.noarch
[root@localhost ~]# podman run -dit --name zk_01 --network  master-network --ip 172.20.0.11 zookeeper
Error: OCI runtime error: container_linux.go:380: starting container process caused: error adding seccomp filter rule for syscall bdflush: requested action matches default action of filter
[root@localhost ~]# runc -v
runc version 1.0.1
commit: ae184aa
spec: 1.0.2-dev
go: go1.15.5
libseccomp: 2.3.1
[root@localhost ~]# podman -v
podman version 3.0.1
[root@localhost ~]# 
[root@localhost ~]# podman -v
podman version 3.0.1
[root@localhost ~]# podman info
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.el7.3.1.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: '
  cpus: 6
  distribution:
    distribution: '"centos"'
    version: "7"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 3.10.0-957.el7.x86_64
  linkmode: dynamic
  memFree: 370847744
  memTotal: 16656515072
  ociRuntime:
    name: runc
    package: runc-1.0.1-0.el7.1.1.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.1
      commit: ae184aa
      spec: 1.0.2-dev
      go: go1.15.5
      libseccomp: 2.3.1
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4153360384
  swapTotal: 4160745472
  uptime: 18h 10m 35.79s (Approximately 0.75 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 6
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 23
  runRoot: /home/var/run/containers/storage
  volumePath: /home/var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1614609040
  BuiltTime: Mon Mar  1 22:30:40 2021
  GitCommit: ""
  GoVersion: go1.15.5
  OsArch: linux/amd64
  Version: 3.0.1


So... This version is relatively new.

Upgrade:
sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/devel:kubic:libcontainers:stable.repo
sudo yum -y install podman

**Comment by kolyshkin** [comment]
Opened https://github.com/containers/podman/issues/11031 to summarize my understanding of the issue.

**Comment by kolyshkin** [comment]
@liaobaikai can you report the version of `containers-common` rpm, as well as the output of `grep defaultErrno /usr/share/containers/seccomp.json`?

**Comment by liaobaikai** [comment]
@kolyshkin containers-common rpm info:
[root@localhost ~]# grep defaultErrno /usr/share/containers/seccomp.json
        "defaultErrnoRet": 38,
[root@localhost ~]#

**Comment by kolyshkin** [comment]
@liaobaikai what's the version of containers-common rpm? `rpm -qf /usr/share/containers/seccomp.json`

**Comment by kolyshkin** [comment]
@liaobaikai it seems that you can work around the bug by removing the whole line containing `defaultErrnoRet` from `/usr/share/containers/seccomp.json`

**Comment by liaobaikai** [comment]
> @liaobaikai what's the version of containers-common rpm? `rpm -qf /usr/share/containers/seccomp.json`

[root@localhost ~]# rpm -qf /usr/share/containers/seccomp.json
containers-common-1-18.el7.20.1.noarch

**Comment by liaobaikai** [comment]
> @liaobaikai it seems that you can work around the bug by removing the whole line containing `defaultErrnoRet` from `/usr/share/containers/seccomp.json`

As well as  _sed -i '/defaultErrnoRet/d' /usr/share/containers/seccomp.json_  ?

**Comment by liaobaikai** [comment]
@kolyshkin When I removed the whole line containing defaultErrnoRet from /usr/share/containers/seccomp.json, got the same error.

[root@localhost ~]# podman run -dit --name zk_01 --network  master-network --ip 172.20.0.11 zookeeper
Error: OCI runtime error: container_linux.go:380: starting container process caused: error adding seccomp filter rule for syscall bdflush: requested action matches default action of filter
[root@localhost ~]# 
[root@localhost ~]# 
[root@localhost ~]# 
[root@localhost ~]# grep defaultErrno /usr/share/containers/seccomp.json
[root@localhost ~]#

**Comment by liaobaikai** [comment]
Is working when i copy /usr/share/containers/seccomp.json from other operation system.

[root@localhost ~]# podman run -dit --name zk_03 --network  master-network --ip 172.20.0.13 zookeeper
6019ce868d8c925a570eb6e46321e3f17ccefd24ea8b2d7cab852f876b04b14f
[root@localhost ~]#

**Comment by kolyshkin** [comment]
> Is working when i copy /usr/share/containers/seccomp.json from other operation system.

Please share the output of `diff -u old-seccomp.json new-seccomp.json`

**Comment by liaobaikai** [comment]
@kolyshkin 

[root@localhost containers]# diff -u seccomp.json.bak seccomp.json
--- seccomp.json.bak    2021-07-24 08:22:45.607000000 +0800
+++ seccomp.json        2021-07-24 08:31:02.048000000 +0800
@@ -1,6 +1,5 @@
 {
        "defaultAction": "SCMP_ACT_ERRNO",
-       "defaultErrnoRet": 38,
        "archMap": [
                {
                        "architecture": "SCMP_ARCH_X86_64",
@@ -53,44 +52,6 @@
        "syscalls": [
                {
                        "names": [
-                               "bdflush",
-                               "io_pgetevents",
-                               "kexec_file_load",
-                               "kexec_load",
-                               "migrate_pages",
-                               "move_pages",
-                               "nfsservctl",
-                               "nice",
-                               "oldfstat",
-                               "oldlstat",
-                               "oldolduname",
-                               "oldstat",
-                               "olduname",
-                               "pciconfig_iobase",
-                               "pciconfig_read",
-                               "pciconfig_write",
-                               "sgetmask",
-                               "ssetmask",
-                               "swapcontext",
-                               "swapoff",
-                               "swapon",
-                               "sysfs",
-                               "uselib",
-                               "userfaultfd",
-                               "ustat",
-                               "vm86",
-                               "vm86old",
-                               "vmsplice"
-                       ],
-                       "action": "SCMP_ACT_ERRNO",
-                       "args": [],
-                       "comment": "",
-                       "includes": {},
-                       "excludes": {},
-                       "errnoRet": 1
-               },
-               {
-                       "names": [
                                "_llseek",
                                "_newselect",
                                "accept",
@@ -115,7 +76,6 @@
                                "clock_nanosleep",
                                "clock_nanosleep_time64",
                                "clone",
-                               "clone3",
                                "close",
                                "close_range",
                                "connect",
@@ -172,7 +132,6 @@
                                "ftruncate",
                                "ftruncate64",
                                "futex",
-                               "futex_time64",
                                "futimesat",
                                "get_robust_list",
                                "get_thread_area",
@@ -189,7 +148,6 @@
                                "getgroups",
                                "getgroups32",
                                "getitimer",
-                               "get_mempolicy",
                                "getpeername",
                                "getpgid",
                                "getpgrp",
@@ -240,7 +198,6 @@
                                "lstat",
                                "lstat64",
                                "madvise",
-                               "mbind",
                                "memfd_create",
                                "mincore",
                                "mkdir",
@@ -259,9 +216,7 @@
                                "mq_notify",
                                "mq_open",
                                "mq_timedreceive",
-                               "mq_timedreceive_time64",
                                "mq_timedsend",
-                               "mq_timedsend_time64",
                                "mq_unlink",
                                "mremap",
                                "msgctl",
@@ -286,9 +241,6 @@
                                "pipe",
                                "pipe2",
                                "pivot_root",
-                               "pkey_alloc",
-                               "pkey_free",
-                               "pkey_mprotect",
                                "poll",
                                "ppoll",
                                "ppoll_time64",
@@ -304,7 +256,6 @@
                                "pwritev2",
                                "read",
                                "readahead",
-                               "readdir",
                                "readlink",
                                "readlinkat",
                                "readv",
@@ -312,7 +263,6 @@
                                "recv",
                                "recvfrom",
                                "recvmmsg",
-                               "recvmmsg_time64",
                                "recvmsg",
                                "remap_file_pages",
                                "removexattr",
@@ -321,7 +271,6 @@
                                "renameat2",
                                "restart_syscall",
                                "rmdir",
-                               "rseq",
                                "rt_sigaction",
                                "rt_sigpending",
                                "rt_sigprocmask",
@@ -329,7 +278,6 @@
                                "rt_sigreturn",
                                "rt_sigsuspend",
                                "rt_sigtimedwait",
-                               "rt_sigtimedwait_time64",
                                "rt_tgsigqueueinfo",
                                "sched_get_priority_max",
                                "sched_get_priority_min",
@@ -338,7 +286,6 @@
                                "sched_getparam",
                                "sched_getscheduler",
                                "sched_rr_get_interval",
-                               "sched_rr_get_interval_time64",
                                "sched_setaffinity",
                                "sched_setattr",
                                "sched_setparam",
@@ -350,15 +297,12 @@
                                "semget",
                                "semop",
                                "semtimedop",
-                               "semtimedop_time64",
                                "send",
                                "sendfile",
                                "sendfile64",
                                "sendmmsg",
                                "sendmsg",
                                "sendto",
-                               "setns",
-                               "set_mempolicy",
                                "set_robust_list",
                                "set_thread_area",
                                "set_tid_address",
@@ -421,7 +365,6 @@
                                "timer_gettime",
                                "timer_gettime64",
                                "timer_settime",
-                               "timer_settime64",
                                "timerfd_create",
                                "timerfd_gettime",
                                "timerfd_gettime64",
@@ -639,21 +582,6 @@
                },
                {
                        "names": [
-                               "open_by_handle_at"
-                       ],
-                       "action": "SCMP_ACT_ERRNO",
-                       "args": [],
-                       "comment": "",
-                       "includes": {},
-                       "excludes": {
-                               "caps": [
-                                       "CAP_DAC_READ_SEARCH"
-                               ]
-                       },
-                       "errnoRet": 1
-               },
-               {
-                       "names": [
                                "bpf",
                                "fanotify_init",
                                "lookup_dcookie",
@@ -675,28 +603,6 @@
                },
                {
                        "names": [
-                               "bpf",
-                               "fanotify_init",
-                               "lookup_dcookie",
-                               "perf_event_open",
-                               "quotactl",
-                               "setdomainname",
-                               "sethostname",
-                               "setns"
-                       ],
-                       "action": "SCMP_ACT_ERRNO",
-                       "args": [],
-                       "comment": "",
-                       "includes": {},
-                       "excludes": {
-                               "caps": [
-                                       "CAP_SYS_ADMIN"
-                               ]
-                       },
-                       "errnoRet": 1
-               },
-               {
-                       "names": [
                                "chroot"
                        ],
                        "action": "SCMP_ACT_ALLOW",
@@ -711,21 +617,6 @@
                },
                {
                        "names": [
-                               "chroot"
-                       ],
-                       "action": "SCMP_ACT_ERRNO",
-                       "args": [],
-                       "comment": "",
-                       "includes": {},
-                       "excludes": {
-                               "caps": [
-                                       "CAP_SYS_CHROOT"
-                               ]
-                       },
-                       "errnoRet": 1
-               },
-               {
-                       "names": [
                                "delete_module",
                                "init_module",
                                "finit_module",
@@ -743,32 +634,16 @@
                },
                {
                        "names": [
-                               "delete_module",
-                               "init_module",
-                               "finit_module",
-                               "query_module"
-                       ],
-                       "action": "SCMP_ACT_ERRNO",
-                       "args": [],
-                       "comment": "",
-                       "includes": {},
-                       "excludes": {
-                               "caps": [
-                                       "CAP_SYS_MODULE"
-                               ]
-                       },
-                       "errnoRet": 1
-               },
-               {
-                       "names": [
-                               "acct"
+                               "get_mempolicy",
+                               "mbind",
+                               "set_mempolicy"
                        ],
                        "action": "SCMP_ACT_ALLOW",
                        "args": [],
                        "comment": "",
                        "includes": {
                                "caps": [
-                                       "CAP_SYS_PACCT"
+                                       "CAP_SYS_NICE"
                                ]
                        },
                        "excludes": {}
@@ -777,16 +652,15 @@
                        "names": [
                                "acct"
                        ],
-                       "action": "SCMP_ACT_ERRNO",
+                       "action": "SCMP_ACT_ALLOW",
                        "args": [],
                        "comment": "",
-                       "includes": {},
-                       "excludes": {
+                       "includes": {
                                "caps": [
                                        "CAP_SYS_PACCT"
                                ]
                        },
-                       "errnoRet": 1
+                       "excludes": {}
                },
                {
                        "names": [
@@ -808,25 +682,6 @@
                },
                {
                        "names": [
-                               "kcmp",
-                               "process_madvise",
-                               "process_vm_readv",
-                               "process_vm_writev",
-                               "ptrace"
-                       ],
-                       "action": "SCMP_ACT_ERRNO",
-                       "args": [],
-                       "comment": "",
-                       "includes": {},
-                       "excludes": {
-                               "caps": [
-                                       "CAP_SYS_PTRACE"
-                               ]
-                       },
-                       "errnoRet": 1
-               },
-               {
-                       "names": [
                                "iopl",
                                "ioperm"
                        ],
@@ -842,22 +697,6 @@
                },
                {
                        "names": [
-                               "iopl",
-                               "ioperm"
-                       ],
-                       "action": "SCMP_ACT_ERRNO",
-                       "args": [],
-                       "comment": "",
-                       "includes": {},
-                       "excludes": {
-                               "caps": [
-                                       "CAP_SYS_RAWIO"
-                               ]
-                       },
-                       "errnoRet": 1
-               },
-               {
-                       "names": [
                                "settimeofday",
                                "stime",
                                "clock_settime",
@@ -875,24 +714,6 @@
                },
                {
                        "names": [
-                               "settimeofday",
-                               "stime",
-                               "clock_settime",
-                               "clock_settime64"
-                       ],
-                       "action": "SCMP_ACT_ERRNO",
-                       "args": [],
-                       "comment": "",
-                       "includes": {},
-                       "excludes": {
-                               "caps": [
-                                       "CAP_SYS_TIME"
-                               ]
-                       },
-                       "errnoRet": 1
-               },
-               {
-                       "names": [
                                "vhangup"
                        ],
                        "action": "SCMP_ACT_ALLOW",
@@ -907,21 +728,6 @@
                },
                {
                        "names": [
-                               "vhangup"
-                       ],
-                       "action": "SCMP_ACT_ERRNO",
-                       "args": [],
-                       "comment": "",
-                       "includes": {},
-                       "excludes": {
-                               "caps": [
-                                       "CAP_SYS_TTY_CONFIG"
-                               ]
-                       },
-                       "errnoRet": 1
-               },
-               {
-                       "names": [
                                "socket"
                        ],
                        "action": "SCMP_ACT_ERRNO",
[root@localhost containers]#

**Comment by liaobaikai** [comment]
[root@localhost containers]# diff  seccomp.json.bak seccomp.json
3d2
<       "defaultErrnoRet": 38,
56,93d54
<                               "bdflush",
<                               "io_pgetevents",
<                               "kexec_file_load",
<                               "kexec_load",
<                               "migrate_pages",
<                               "move_pages",
<                               "nfsservctl",
<                               "nice",
<                               "oldfstat",
<                               "oldlstat",
<                               "oldolduname",
<                               "oldstat",
<                               "olduname",
<                               "pciconfig_iobase",
<                               "pciconfig_read",
<                               "pciconfig_write",
<                               "sgetmask",
<                               "ssetmask",
<                               "swapcontext",
<                               "swapoff",
<                               "swapon",
<                               "sysfs",
<                               "uselib",
<                               "userfaultfd",
<                               "ustat",
<                               "vm86",
<                               "vm86old",
<                               "vmsplice"
<                       ],
<                       "action": "SCMP_ACT_ERRNO",
<                       "args": [],
<                       "comment": "",
<                       "includes": {},
<                       "excludes": {},
<                       "errnoRet": 1
<               },
<               {
<                       "names": [
118d78
<                               "clone3",
175d134
<                               "futex_time64",
192d150
<                               "get_mempolicy",
243d200
<                               "mbind",
262d218
<                               "mq_timedreceive_time64",
264d219
<                               "mq_timedsend_time64",
289,291d243
<                               "pkey_alloc",
<                               "pkey_free",
<                               "pkey_mprotect",
307d258
<                               "readdir",
315d265
<                               "recvmmsg_time64",
324d273
<                               "rseq",
332d280
<                               "rt_sigtimedwait_time64",
341d288
<                               "sched_rr_get_interval_time64",
353d299
<                               "semtimedop_time64",
360,361d305
<                               "setns",
<                               "set_mempolicy",
424d367
<                               "timer_settime64",
642,656d584
<                               "open_by_handle_at"
<                       ],
<                       "action": "SCMP_ACT_ERRNO",
<                       "args": [],
<                       "comment": "",
<                       "includes": {},
<                       "excludes": {
<                               "caps": [
<                                       "CAP_DAC_READ_SEARCH"
<                               ]
<                       },
<                       "errnoRet": 1
<               },
<               {
<                       "names": [
678,699d605
<                               "bpf",
<                               "fanotify_init",
<                               "lookup_dcookie",
<                               "perf_event_open",
<                               "quotactl",
<                               "setdomainname",
<                               "sethostname",
<                               "setns"
<                       ],
<                       "action": "SCMP_ACT_ERRNO",
<                       "args": [],
<                       "comment": "",
<                       "includes": {},
<                       "excludes": {
<                               "caps": [
<                                       "CAP_SYS_ADMIN"
<                               ]
<                       },
<                       "errnoRet": 1
<               },
<               {
<                       "names": [
714,728d619
<                               "chroot"
<                       ],
<                       "action": "SCMP_ACT_ERRNO",
<                       "args": [],
<                       "comment": "",
<                       "includes": {},
<                       "excludes": {
<                               "caps": [
<                                       "CAP_SYS_CHROOT"
<                               ]
<                       },
<                       "errnoRet": 1
<               },
<               {
<                       "names": [
746,764c637,639
<                               "delete_module",
<                               "init_module",
<                               "finit_module",
<                               "query_module"
<                       ],
<                       "action": "SCMP_ACT_ERRNO",
<                       "args": [],
<                       "comment": "",
<                       "includes": {},
<                       "excludes": {
<                               "caps": [
<                                       "CAP_SYS_MODULE"
<                               ]
<                       },
<                       "errnoRet": 1
<               },
<               {
<                       "names": [
<                               "acct"
---
>                               "get_mempolicy",
>                               "mbind",
>                               "set_mempolicy"
771c646
<                                       "CAP_SYS_PACCT"
---
>                                       "CAP_SYS_NICE"
780c655
<                       "action": "SCMP_ACT_ERRNO",
---
>                       "action": "SCMP_ACT_ALLOW",
783,784c658
<                       "includes": {},
<                       "excludes": {
---
>                       "includes": {
789c663
<                       "errnoRet": 1
---
>                       "excludes": {}
811,829d684
<                               "kcmp",
<                               "process_madvise",
<                               "process_vm_readv",
<                               "process_vm_writev",
<                               "ptrace"
<                       ],
<                       "action": "SCMP_ACT_ERRNO",
<                       "args": [],
<                       "comment": "",
<                       "includes": {},
<                       "excludes": {
<                               "caps": [
<                                       "CAP_SYS_PTRACE"
<                               ]
<                       },
<                       "errnoRet": 1
<               },
<               {
<                       "names": [
845,860d699
<                               "iopl",
<                               "ioperm"
<                       ],
<                       "action": "SCMP_ACT_ERRNO",
<                       "args": [],
<                       "comment": "",
<                       "includes": {},
<                       "excludes": {
<                               "caps": [
<                                       "CAP_SYS_RAWIO"
<                               ]
<                       },
<                       "errnoRet": 1
<               },
<               {
<                       "names": [
878,895d716
<                               "settimeofday",
<                               "stime",
<                               "clock_settime",
<                               "clock_settime64"
<                       ],
<                       "action": "SCMP_ACT_ERRNO",
<                       "args": [],
<                       "comment": "",
<                       "includes": {},
<                       "excludes": {
<                               "caps": [
<                                       "CAP_SYS_TIME"
<                               ]
<                       },
<                       "errnoRet": 1
<               },
<               {
<                       "names": [
907,921d727
<               },
<               {
<                       "names": [
<                               "vhangup"
<                       ],
<                       "action": "SCMP_ACT_ERRNO",
<                       "args": [],
<                       "comment": "",
<                       "includes": {},
<                       "excludes": {
<                               "caps": [
<                                       "CAP_SYS_TTY_CONFIG"
<                               ]
<                       },
<                       "errnoRet": 1

**Comment by liaobaikai** [comment]
The format is terrible.

**Comment by liaobaikai** [comment]
@kolyshkin 

[root@localhost containers]# diff -u seccomp.json.bak seccomp.json
--- seccomp.json.bak    2021-07-24 08:22:45.607000000 +0800
+++ seccomp.json        2021-07-24 08:31:02.048000000 +0800
@@ -1,6 +1,5 @@
 {
        "defaultAction": "SCMP_ACT_ERRNO",
-       "defaultErrnoRet": 38,
        "archMap": [
                {
                        "architecture": "SCMP_ARCH_X86_64",
@@ -53,44 +52,6 @@
        "syscalls": [
                {
                        "names": [
-                               "bdflush",
-                               "io_pgetevents",
-                               "kexec_file_load",
-                               "kexec_load",
-                               "migrate_pages",
-                               "move_pages",
-                               "nfsservctl",
-                               "nice",
-                               "oldfstat",
-                               "oldlstat",
-                               "oldolduname",
-                               "oldstat",
-                               "olduname",
-                               "pciconfig_iobase",
-                               "pciconfig_read",
-                               "pciconfig_write",
-                               "sgetmask",
-                               "ssetmask",
-                               "swapcontext",
-                               "swapoff",
-                               "swapon",
-                               "sysfs",
-                               "uselib",
-                               "userfaultfd",
-                               "ustat",
-                               "vm86",
-                               "vm86old",
-                               "vmsplice"
-                       ],
-                       "action": "SCMP_ACT_ERRNO",
-                       "args": [],
-                       "comment": "",
-                       "includes": {},
-                       "excludes": {},
-                       "errnoRet": 1
-               },
-               {
-                       "names": [
                                "_llseek",
                                "_newselect",
                                "accept",
@@ -115,7 +76,6 @@
                                "clock_nanosleep",
                                "clock_nanosleep_time64",
                                "clone",
-                               "clone3",
                                "close",
                                "close_range",
                                "connect",
@@ -172,7 +132,6 @@
                                "ftruncate",
                                "ftruncate64",
                                "futex",
-                               "futex_time64",
                                "futimesat",
                                "get_robust_list",
                                "get_thread_area",
@@ -189,7 +148,6 @@
                                "getgroups",
                                "getgroups32",
                                "getitimer",
-                               "get_mempolicy",
                                "getpeername",
                                "getpgid",
                                "getpgrp",
@@ -240,7 +198,6 @@
                                "lstat",
                                "lstat64",
                                "madvise",
-                               "mbind",
                                "memfd_create",
                                "mincore",
                                "mkdir",
@@ -259,9 +216,7 @@
                                "mq_notify",
                                "mq_open",
                                "mq_timedreceive",
-                               "mq_timedreceive_time64",
                                "mq_timedsend",
-                               "mq_timedsend_time64",
                                "mq_unlink",
                                "mremap",
                                "msgctl",
@@ -286,9 +241,6 @@
                                "pipe",
                                "pipe2",
                                "pivot_root",
-                               "pkey_alloc",
-                               "pkey_free",
-                               "pkey_mprotect",
                                "poll",
                                "ppoll",
                                "ppoll_time64",
@@ -304,7 +256,6 @@
                                "pwritev2",
                                "read",
                                "readahead",
-                               "readdir",
                                "readlink",
                                "readlinkat",
                                "readv",
@@ -312,7 +263,6 @@
                                "recv",
                                "recvfrom",
                                "recvmmsg",
-                               "recvmmsg_time64",
                                "recvmsg",
                                "remap_file_pages",
                                "removexattr",
@@ -321,7 +271,6 @@
                                "renameat2",
                                "restart_syscall",
                                "rmdir",
-                               "rseq",
                                "rt_sigaction",
                                "rt_sigpending",
                                "rt_sigprocmask",
@@ -329,7 +278,6 @@
                                "rt_sigreturn",
                                "rt_sigsuspend",
                                "rt_sigtimedwait",
-                               "rt_sigtimedwait_time64",
                                "rt_tgsigqueueinfo",
                                "sched_get_priority_max",
                                "sched_get_priority_min",
@@ -338,7 +286,6 @@
                                "sched_getparam",
                                "sched_getscheduler",
                                "sched_rr_get_interval",
-                               "sched_rr_get_interval_time64",
                                "sched_setaffinity",
                                "sched_setattr",
                                "sched_setparam",
@@ -350,15 +297,12 @@
                                "semget",
                                "semop",
                                "semtimedop",
-                               "semtimedop_time64",
                                "send",
                                "sendfile",
                                "sendfile64",
                                "sendmmsg",
                                "sendmsg",
                                "sendto",
-                               "setns",
-                               "set_mempolicy",
                                "set_robust_list",
                                "set_thread_area",
                                "set_tid_address",
@@ -421,7 +365,6 @@
                                "timer_gettime",
                                "timer_gettime64",
                                "timer_settime",
-                               "timer_settime64",
                                "timerfd_create",
                                "timerfd_gettime",
                                "timerfd_gettime64",
@@ -639,21 +582,6 @@
                },
                {
                        "names": [
-                               "open_by_handle_at"
-                       ],
-                       "action": "SCMP_ACT_ERRNO",
-                       "args": [],
-                       "comment": "",
-                       "includes": {},
-                       "excludes": {
-                               "caps": [
-                                       "CAP_DAC_READ_SEARCH"
-                               ]
-                       },
-                       "errnoRet": 1
-               },
-               {
-                       "names": [
                                "bpf",
                                "fanotify_init",
                                "lookup_dcookie",
@@ -675,28 +603,6 @@
                },
                {
                        "names": [
-                               "bpf",
-                               "fanotify_init",
-                               "lookup_dcookie",
-                               "perf_event_open",
-                               "quotactl",
-                               "setdomainname",
-                               "sethostname",
-                               "setns"
-                       ],
-                       "action": "SCMP_ACT_ERRNO",
-                       "args": [],
-                       "comment": "",
-                       "includes": {},
-                       "excludes": {
-                               "caps": [
-                                       "CAP_SYS_ADMIN"
-                               ]
-                       },
-                       "errnoRet": 1
-               },
-               {
-                       "names": [
                                "chroot"
                        ],
                        "action": "SCMP_ACT_ALLOW",
@@ -711,21 +617,6 @@
                },
                {
                        "names": [
-                               "chroot"
-                       ],
-                       "action": "SCMP_ACT_ERRNO",
-                       "args": [],
-                       "comment": "",
-                       "includes": {},
-                       "excludes": {
-                               "caps": [
-                                       "CAP_SYS_CHROOT"
-                               ]
-                       },
-                       "errnoRet": 1
-               },
-               {
-                       "names": [
                                "delete_module",
                                "init_module",
                                "finit_module",
@@ -743,32 +634,16 @@
                },
                {
                        "names": [
-                               "delete_module",
-                               "init_module",
-                               "finit_module",
-                               "query_module"
-                       ],
-                       "action": "SCMP_ACT_ERRNO",
-                       "args": [],
-                       "comment": "",
-                       "includes": {},
-                       "excludes": {
-                               "caps": [
-                                       "CAP_SYS_MODULE"
-                               ]
-                       },
-                       "errnoRet": 1
-               },
-               {
-                       "names": [
-                               "acct"
+                               "get_mempolicy",
+                               "mbind",
+                               "set_mempolicy"
                        ],
                        "action": "SCMP_ACT_ALLOW",
                        "args": [],
                        "comment": "",
                        "includes": {
                                "caps": [
-                                       "CAP_SYS_PACCT"
+                                       "CAP_SYS_NICE"
                                ]
                        },
                        "excludes": {}
@@ -777,16 +652,15 @@
                        "names": [
                                "acct"
                        ],
-                       "action": "SCMP_ACT_ERRNO",
+                       "action": "SCMP_ACT_ALLOW",
                        "args": [],
                        "comment": "",
-                       "includes": {},
-                       "excludes": {
+                       "includes": {
                                "caps": [
                                        "CAP_SYS_PACCT"
                                ]
                        },
-                       "errnoRet": 1
+                       "excludes": {}
                },
                {
                        "names": [
@@ -808,25 +682,6 @@
                },
                {
                        "names": [
-                               "kcmp",
-                               "process_madvise",
-                               "process_vm_readv",
-                               "process_vm_writev",
-                               "ptrace"
-                       ],
-                       "action": "SCMP_ACT_ERRNO",
-                       "args": [],
-                       "comment": "",
-                       "includes": {},
-                       "excludes": {
-                               "caps": [
-                                       "CAP_SYS_PTRACE"
-                               ]
-                       },
-                       "errnoRet": 1
-               },
-               {
-                       "names": [
                                "iopl",
                                "ioperm"
                        ],
@@ -842,22 +697,6 @@
                },
                {
                        "names": [
-                               "iopl",
-                               "ioperm"
-                       ],
-                       "action": "SCMP_ACT_ERRNO",
-                       "args": [],
-                       "comment": "",
-                       "includes": {},
-                       "excludes": {
-                               "caps": [
-                                       "CAP_SYS_RAWIO"
-                               ]
-                       },
-                       "errnoRet": 1
-               },
-               {
-                       "names": [
                                "settimeofday",
                                "stime",
                                "clock_settime",
@@ -875,24 +714,6 @@
                },
                {
                        "names": [
-                               "settimeofday",
-                               "stime",
-                               "clock_settime",
-                               "clock_settime64"
-                       ],
-                       "action": "SCMP_ACT_ERRNO",
-                       "args": [],
-                       "comment": "",
-                       "includes": {},
-                       "excludes": {
-                               "caps": [
-                                       "CAP_SYS_TIME"
-                               ]
-                       },
-                       "errnoRet": 1
-               },
-               {
-                       "names": [
                                "vhangup"
                        ],
                        "action": "SCMP_ACT_ALLOW",
@@ -907,21 +728,6 @@
                },
                {
                        "names": [
-                               "vhangup"
-                       ],
-                       "action": "SCMP_ACT_ERRNO",
-                       "args": [],
-                       "comment": "",
-                       "includes": {},
-                       "excludes": {
-                               "caps": [
-                                       "CAP_SYS_TTY_CONFIG"
-                               ]
-                       },
-                       "errnoRet": 1
-               },
-               {
-                       "names": [
                                "socket"
                        ],
                        "action": "SCMP_ACT_ERRNO",

**Comment by kolyshkin** [comment]
@liaobaikai can you please edit your comment above, wrapping the whole diff output into

<pre>
```diff
(here goes the diff output)
.....
```
</pre>

You can use the preview tab to check how it looks like. The result should look like

```diff
--- seccomp.json.bak 2021-07-24 08:22:45.607000000 +0800
+++ seccomp.json 2021-07-24 08:31:02.048000000 +0800
@@ -1,6 +1,5 @@
{
"defaultAction": "SCMP_ACT_ERRNO",

-  "defaultErrnoRet": 38,
...
```

**Comment by mheon** [comment]
It looks like they're packaging a too-old containers.conf, recommend you ask them to update.

**Comment by glaszig** [comment]
actually, with `seccomp-18.el7.21.1.json` i get the error. copying over `seccomp-8.el7.13.1.json` on to the newer package version, it works.
