### ISSUE TITLE
Support to start container with image layer

### ISSUE THREAD

**Issue by chenk008** [containers/podman#11038]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Currenlty Podman can start container with rootfs by specify `--rootfs`. The rootfs must be writable. 

Now I have a image layer mount as read-only at somewhere like `/var/lib/containers/test` , I want to start a container which rootfs is overlay on this image layer. Podman can manage container overlay upper/work/merged directory.

How about add some flag like `--root-layer`?

**Comment by rhatdan** [comment]
This works for me.  I think you need to add more information.

```
# podman image mount fedora
/var/lib/containers/storage/overlay/9e6713d530bf59dd0ce8155e1a48372e2ad1773be06a8087deafeb5ad0fed586/merged
# mount --bind -o ro /var/lib/containers/storage/overlay/9e6713d530bf59dd0ce8155e1a48372e2ad1773be06a8087deafeb5ad0fed586/merged /var/lib/containers/storage/overlay/9e6713d530bf59dd0ce8155e1a48372e2ad1773be06a8087deafeb5ad0fed586/merged
# touch /var/lib/containers/storage/overlay/9e6713d530bf59dd0ce8155e1a48372e2ad1773be06a8087deafeb5ad0fed586/merged/etc/resolv.conf 
touch: cannot touch '/var/lib/containers/storage/overlay/9e6713d530bf59dd0ce8155e1a48372e2ad1773be06a8087deafeb5ad0fed586/merged/etc/resolv.conf': Read-only file system
# podman run --read-only --rootfs /var/lib/containers/storage/overlay/9e6713d530bf59dd0ce8155e1a48372e2ad1773be06a8087deafeb5ad0fed586/merged echo hi
hi
```

**Comment by chenk008** [comment]
I want to start a writable container with overlayfs. 
The overlayfs lower layer is image layer and has been mounted on somewhere as read-only. And Podman can create writable layer and mount a overley rootfs.

**Comment by rhatdan** [comment]
So you want to specify a the upper directory where the overlay can write?

**Comment by rhatdan** [comment]
Could you describe the use cases that this would be valuable for, as opposed to you just creating your own overlay and not building it into Podman.

**Comment by chenk008** [comment]
In the docker-container, there is a daemon agent which can mount  a container image to some directory as readonly. I want to reuse this mounted directory to start a nested-container. 

I hope Podman can start the nested-container based on the image mounted directory.

![image](https://user-images.githubusercontent.com/2086945/127796611-49e4b5cd-6c40-4d1c-842a-2039ee302fad.png)

**Comment by rhatdan** [comment]
@giuseppe @nalind @rhvgoyal WDYT?

**Comment by giuseppe** [comment]
`--rootfs` is backend agnostic as it doesn't have to deal with overlay itself, the user provides the final root for the container.

With the model above, we probably want to implement it in containers/storage to use the overlay driver before it can be exposed in Podman.

I think it is an useful feature.

**Comment by rhatdan** [comment]
I would figure something like

podman run --rootfs /:O --tmpfs /var 

Would be kind of cool, allowing you to launch containers on existing file systems that are writable, but, there would be  no way to do a commit on these containers, and lots of stuff would be different then traditional Podman containers.

One issue would be overlay does not like the underlying file system changing from underneath it.

**Comment by flouthoc** [comment]
@rhatdan @giuseppe I tried this patch (https://github.com/flouthoc/podman/commit/d66104e6f1e9ece0da23dec36f0fbab0801f57f6) which implements scenarios such as below.
```bash
podman run --rootfs /some/readonly/path:O echo hello
```

I didn't open a PR as i was not really sure if this approach is expected and its crude but i can open a PR if this looks okish.

**Comment by giuseppe** [comment]
I think it is fine, as long as the overlay upper layer lives as long as the container (it cannot be on a tmpdir), and that it is reused when the container is restarted

**Comment by rhatdan** [comment]
Yes the upper directory should be in containers/storage rootfs just like all other containers uppers.

**Comment by flouthoc** [comment]
@rhatdan @giuseppe Thanks I will make the required changes.

**Comment by rhatdan** [comment]
@flouthoc any update?
