### ISSUE TITLE
Add line numbers to output of contrib/cirrus/pr-should-include-tests

### ISSUE THREAD

**Issue by baude** [containers/podman#11034]
Ran into @edsantiago new Makefile hack that checks for a pattern around exit codes -> contrib/cirrus/pr-should-include-tests

Please include line numbers in the output.

**Comment by edsantiago** [comment]
I'm a little lost. This is a CI check that triggers upon _not_ finding something. How do I print a line number of something that doesn't exist?

I must be misunderstanding something big. Can you give me an example of what you'd like to see, or how you expect this could work?

**Comment by baude** [comment]
@edsantiago im going to close this ... but the problem here was that i had a bunch of new e2e tests in a pr, so when you added this, my pr broke down but the stuff being flagged didnt tell me where in the code the problem was...
