### ISSUE TITLE
Mount host resolv.conf does not work as expected.

### ISSUE THREAD

**Issue by StayPirate** [containers/podman#11042]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

This is a follow up of #10026, unfortunately I had no chance to have tried out suggested tips until today and in the meantime the issue has been closed for inactivity. Opening this one as a continuation.

Even if I use `--dns=none` and `-v /etc/resolv.conf:/etc/resolv.conf`, `/etc/resolv.conf` inside the container does not reflect the changes I make to the host's one. Here what I did:

**Steps to reproduce the issue:**

```bash
host > cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 192.168.1.1
```
```bash
host > podman container run --rm -ti --dns=none -v /etc/resolv.conf:/etc/resolv.conf alpine:latest sh
guest > cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 192.168.1.1
```
Then I change the `/etc/resolv.conf` in the host.
```bash
host > cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 10.160.0.1
nameserver 10.160.2.88
nameserver 2620:113:80c0:8080:10:160:2:88
# NOTE: the libc resolver may not support more than 3 nameservers.
# The nameservers listed below may not be recognized.
nameserver 2620:113:80c0:8080:10:160:0:1
nameserver 192.168.1.1
```
I then check again the file from the container, expecting to see the above changes reflected:
```bash
guest > cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 192.168.1.1
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.2.2
API Version:  3.2.2
Go Version:   go1.16.5
Git Commit:   d577c44e359f9f8284b38cf984f939b3020badc3
Built:        Fri Jul  9 14:54:04 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.21.0
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.0.29-1
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 7e6de6678f6ed8a18661e1d5721b81ccee293b9b'
  cpus: 8
  distribution:
    distribution: manjaro
    version: unknown
  eventLogger: journald
  hostname: wintermute
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65536
  kernel: 5.13.4-1-MANJARO
  linkmode: dynamic
  memFree: 19271749632
  memTotal: 33384263680
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 0.20.1-2
    path: /usr/bin/crun
    version: |-
      crun version 0.20.1
      commit: 38271d1c8d9641a2cdc70acfa3dcb6996d124b3d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.1.11-1
    version: |-
      slirp4netns version 1.1.11
      commit: 368e69ccc074628d17a9bb9a35b8f4b9f74db4c6
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 9446825984
  swapTotal: 9446825984
  uptime: 46h 50m 38.69s (Approximately 1.92 days)
registries:
  search:
  - docker.io
store:
  configFile: /home/crazybyte/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: /usr/bin/fuse-overlayfs is owned by fuse-overlayfs 1.6-1
      Version: |-
        fusermount3 version: 3.10.4
        fuse-overlayfs: version 1.6
        FUSE library version 3.10.4
        using FUSE kernel interface version 7.31
  graphRoot: /home/crazybyte/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 55
  runRoot: /run/user/1000/containers
  volumePath: /home/crazybyte/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.2
  Built: 1625835244
  BuiltTime: Fri Jul  9 14:54:04 2021
  GitCommit: d577c44e359f9f8284b38cf984f939b3020badc3
  GoVersion: go1.16.5
  OsArch: linux/amd64
  Version: 3.2.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Name            : podman
Version         : 3.2.2-2
Description     : Tool and library for running OCI-based containers in pods
Architecture    : x86_64
URL             : https://github.com/containers/libpod
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : cni-plugins  conmon  containers-common  device-mapper  iptables  libseccomp  crun  slirp4netns  libsystemd  fuse-overlayfs  libgpgme.so=11-64
Optional Deps   : podman-docker: for Docker-compatible CLI
                  btrfs-progs: support btrfs backend devices [installed]
                  catatonit: --init flag support
                  crun: support for unified cgroupsv2 [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 72.37 MiB
Packager        : Morten Linderud <foxboron@archlinux.org>
Build Date      : Fri 09 Jul 2021 02:54:04 PM CEST
Install Date    : Sun 18 Jul 2021 01:04:01 PM CEST
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
Backup Files    :
UNREADABLE	/etc/cni/net.d/87-podman-bridge.conflist
```

**Comment by Luap99** [comment]
Do you edit the file? I assume not. I think NetworkManager will create a new `resolv.conf` file for each change and overwrites  `/etc/resolv.conf`. This breaks the bind mount because the source was "deleted". The container keeps using the old file while the host has the new file. This is how bind mounts work in the kernel. One solution would be to mount the parent directory, but this is probably not desired for `/etc`

**Comment by StayPirate** [comment]
You are correct, I do not directly edit the file, I connect the host to a VPN via NetworkManager and in turn it changes `/etc/resolv.conf`. I have not thought it might delete the file and replace it with the new one, this actually explains the behavior I experienced. As you anticipated, mounting the whole `/etc` it's out of scope. I'm wondering what happens if I create a symlink to `/etc/resolv.conf` and mount that one instead. It should not be deleted, and after a few milliseconds of being a broken link (while NetworkManager is replacing `resolv.conf`) it will keep pointing to the same destination which is now the updated `resolv.conf`. I'm gonna try this way out soon and I will post here the result.

**Comment by Luap99** [comment]
This will not work. Symlinks are always resolved before doing the bind mount.

**Comment by StayPirate** [comment]
Are you aware of any other solution? Maybe I could avoid to bind mount `/etc/resolv.conf`?

**Comment by Luap99** [comment]
Maybe there is a way to prevent NetworkManager from creating a new file and instead edit this in place. Or you setup a local resolver with a fixed ip so you do not have to change /etc/resolv.conf every time.

I close the issue since I do not think this can be fixed in podman.

**Comment by mheon** [comment]
The solution that Toolbox ended up using was to mount `/etc/` from the host into the container at `/host/etc/` and then symlink `/etc/resolv.conf` in the container to `/host/etc/resolv.conf` - because the entire `/etc/` directory is bind-mounted in, changes are captured.

**Comment by StayPirate** [comment]
In [secbox](https://github.com/StayPirate/secbox) I took a different approach, it maintains (syncs) it's own copy of the host's `/etc/resolv.conf` as explained in [this commit](https://github.com/StayPirate/secbox/commit/ce2a46332222a07796624cc9c3466229a1592848). TBH I don't know how toolbox works, but if you use it by spawning a shell and keep working from there, then secbox's solution won't work. Secbox is transparent for the user, commands are ran from the host's terminal and their output is printed there.
