### ISSUE TITLE
[Feature request] Running host applications in container / Image-free partial isolation for HPC

### ISSUE THREAD

**Issue by Hoeze** [containers/podman#11041]
Hi, I'd have a number of applications where I would like to isolate only certain aspects of the host OS, e.g.:
- Have different mount points for an application
- Isolate insecure web servers from other users

For example, our HPC cluster users could spawn a Rstudio session, Spark dashboard, etc. which can be accessed by every user on the same host. In this case, it would be desirable to have a virtual network for every user, s.t. insecure applications cannot be attacked by foreign users.

Running the full-blown container stack is not desirable in this case, because the users want to access other OS resources (GPUs, Kerberos-secured NFS mounts, ...) as usual.
Therefore, one would only want to `unshare` network and mount points of their application while keeping to run in the host OS.

**Concrete example:**
Is it possible to directly run a host application without changing user id or software environment with podman?
```bash
# Directly run jupyter lab from host OS within isolated network;
# map container port 80 to host port 10080
podman run -p 10080:80 -t jupyter lab
```

**Comment by vrothberg** [comment]
Thanks for reaching out, @Hoeze!

Having a mount (and user) namespace is mandatory but most other namespaces can be used of the host environment.

`$ podman run --pid=host --ipc=host --uts=host --userns=keep-id --cgroupns=host alpine`

Note that `--userns=keep-id` creates a user namespace with the current UID/GID of the calling process.  This way, the UID remains the same inside the container as outside the container.

If you want to run a host application, you _could_ mount it into the container (e.g., `$ podman run ... -v /usr/bin/myapp:/myapp $image /myapp`).  Note that the application must be a static binary in order to run properly.

May I ask what drives the desire to run applications from the host rather than using the ones one the image? If you really just want a mount namespace and a private network, I am not sure a container engine is the right tool.

Cc: @rhatdan @giuseppe @fatherlinux

**Comment by Hoeze** [comment]
Thanks for your detailed answer @vrothberg!
My intention is to isolate only certain aspects of applications. Any user should be able to run his application in a private network namespace with eventually different network overlays.

> If you really just want a mount namespace and a private network, I am not sure a container engine is the right tool.

Yes, I'm also not sure about this.
However, after playing with `unshare`, `overlayfs-fuse` and network namespaces I came to the conclusion that podman is already doing all of the necessary heavy lifting. It would only need to use the host mounts instead of the container image.

**Comment by mheon** [comment]
I believe @Luap99 looked into something very similar to what you are asking for (containers created directly from host content, without the use of an image), but eventually abandoned the idea because of permissions and SELinux issues.

A potential alternative is `--rootfs` which uses a directory from the host, instead of an image, as the root filesystem of a container.

**Comment by Luap99** [comment]
I also used `--rootfs`, the idea was the following:
```
$ podman unshare mount --rbind / ./rootfs
$ podman unshare mount -t tmpfs none ./rootfs/run
$ podman run -d --net=slirp4netns  --rootfs ./rootfs
```
This allowed me to keep the host mounts while mounting a new tmpfs to `/run` to make it writeable for the rootless user in the container.

**Comment by Hoeze** [comment]
Thanks for your description @Luap99.
I tried this on our servers, but it's not really working:
```bash
/scratch/tmp/<user>> mkdir rootfs
/scratch/tmp/<user>> podman unshare mount --rbind / ./rootfs
/scratch/tmp/<user>> ll rootfs 
insgesamt 0
# why empty?
/scratch/tmp/<user>> podman unshare mount -t tmpfs none ./rootfs/run
/scratch/tmp/<user>> podman run -d --net=slirp4netns  --rootfs ./rootfs bash
Error: OCI runtime error: rootfs (/scratch/tmp/<user>/containers/storage/overlay-containers/24bfeaa7aa20e7ee4f7fb3d5427e6d905098b9977b07efe08d5ebb0a1523a8d7/userdata/rootfs) does not exist
```

**Comment by Luap99** [comment]
Can you try with a absolute path to the rootfs. The roofs dir will be empty in host namespace you have to use `podman unshare ls` to see the content.

**Comment by rhatdan** [comment]
Once the 
podman unshare ... 
Line exits, you will no longer see the mount, because you are now in a different mount namespace.

Try
``` 
$ podman unshare 
#  mount --rbind / ./rootfs
# podman run -d --net=slirp4netns  --rootfs ./rootfs bas
```

**Comment by Hoeze** [comment]
Thanks @rhatdan, this works:
```bash
podman unshare
# mount --rbind / $(realpath rootfs/) 
# mount -t tmpfs none $(realpath rootfs/) 
# podman run -d -i --name test --net=slirp4netns  --rootfs $(realpath rootfs/) /usr/bin/bash
# podman attach test
```
However, inside the container I am appearing to be the root user, although I can access all my files in my home, etc.
Is it possible to keep my user id and groups?

**Comment by rhatdan** [comment]
@giuseppe Is this possible?

The way you do this from outside of the user namespace is:

$ podman run --add-group=keep-groups --userns=keep-id ...

Not sure if this works from within the user namespace.

**Comment by giuseppe** [comment]
I think `--add-group=keep-groups --userns=keep-id` should be enough

**Comment by Hoeze** [comment]
Unfortunately, this does not work:
```bash
# podman run --group-add=keep-groups --userns=keep-id -d -i --name test --net=slirp4netns  --rootfs $(realpath rootfs/) /usr/bin/bash
ERRO[0000] cannot find UID/GID for user <user>: No subuid ranges found for user "<user>" in /etc/subuid - check rootless mode in man pages. 
Error: error creating temporary passwd file for container 812a0091bbde8e3fba14f57e42179a62ad69c57afcbaa8f75a622e38292f06c0: container 812a0091bbde8e3fba14f57e42179a62ad69c57afcbaa8f75a622e38292f06c0: open /data/nfshome/<user>/rootfs/etc/passwd: permission denied
```
Please note that users are managed by FreeIPA/SSSD and homes are stored on NFS.

**Comment by vrothberg** [comment]
Friendly ping.  Did you progress @Hoeze ?

**Comment by Hoeze** [comment]
Hi @vrothberg, thanks for the ping.

Unfortunately I am still hanging at the `permission denied` error: 
> ```shell
> # podman run --group-add=keep-groups --userns=keep-id -d -i --name test --net=slirp4netns  --rootfs $(realpath rootfs/) /usr/bin/bash
> ERRO[0000] cannot find UID/GID for user <user>: No subuid ranges found for user "<user>" in /etc/subuid - check rootless mode in man pages. 
> Error: error creating temporary passwd file for container 812a0091bbde8e3fba14f57e42179a62ad69c57afcbaa8f75a622e38292f06c0: container 812a0091bbde8e3fba14f57e42179a62ad69c57afcbaa8f75a622e38292f06c0: open /data/nfshome/<user>/rootfs/etc/passwd: permission denied
> ```

Do you have any idea how to solve this?

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
what is the ownership for `data/nfshome/<user>/rootfs/etc/` and `data/nfshome/<user>/rootfs/etc/passwd`?  They must be owned by the current user or be world readable/accessible

**Comment by giuseppe** [comment]
and is the rootfs on NFS?

**Comment by Hoeze** [comment]
@giuseppe Yes, the rootfs was on a NFS3 share. Probably an issue with missing secondary group support then.

I tried a different one using cephfs, which supports secondary groups + ACLs:
```bash
# mkdir /data/ceph_ssd/scratch/tmp/<user>/rootfs
# podman run --group-add=keep-groups --userns=keep-id -d -i --name test --net=slirp4netns  --rootfs $(realpath /data/ceph_ssd/scratch/tmp/<user>/rootfs/) /usr/bin/bash
ERRO[0000] cannot find UID/GID for user <user>: No subuid ranges found for user "<user>" in /etc/subuid - check rootless mode in man pages. 
ERRO[0000] cannot find UID/GID for user <user>: No subuid ranges found for user "<user>" in /etc/subuid - check rootless mode in man pages. 
Error: OCI runtime error: User namespaces enabled, but no user mapping found.
```

**Comment by giuseppe** [comment]
so there are two things to check:

1) make sure all the files under `/data/ceph_ssd/scratch/tmp/<user>/rootfs/` are accessible to your user.
2) both `--group-add=keep-groups` and `--userns=keep-id` with a single user mapped in the user namespace are crun-only features.  So please make sure you are using `crun` instead of `runc`

**Comment by rhatdan** [comment]
Did you do the system migrate?

**Comment by Hoeze** [comment]
@rhatdan Yes I ran `podman system migrate` (now with podman v3.3.1), but I still get the same error:
```
ERRO[0000] cannot find UID/GID for user hoelzlwi: No subuid ranges found for user "<user>" in /etc/subuid - check rootless mode in man pages. 
ERRO[0000] cannot find UID/GID for user hoelzlwi: No subuid ranges found for user "<user>" in /etc/subuid - check rootless mode in man pages. 
Error: OCI runtime error: writing file `/proc/4024492/gid_map`: Invalid argument
```

As I said, we do not want to setup subuid-ranges for every user (shared filesystem, many hosts, ...).
Instead we need to keep the current uid's.

**Comment by rhatdan** [comment]
You run with a single UID, but not with more then one, unless you use /etc/subuid and /etc/subgid.
We should have support for these files being available over the network.

**Comment by Hoeze** [comment]
> You run with a single UID, but not with more then one, unless you use /etc/subuid and /etc/subgid. 

Yes, but why does Podman then try to setup `/proc/4024492/gid_map`?
There is no need to move into subuid/subgid ranges.

E.g. normally I have 
```bash
id -u -> 5534
id -G -> 501918 500000 979000000 979000007 979000011 [...]
```
I want to keep exactly those IDs.

**Comment by rhatdan** [comment]
Does podman unshare fail?

**Comment by Hoeze** [comment]
Podman unshare works fine :)

**Comment by rhatdan** [comment]
How about if you don't use --userns=keep-id?  I think with this you would be required to have two UIDs root and your UID.

**Comment by Hoeze** [comment]
Now I get a new error:
```bash
# podman run --group-add=keep-groups -d -i --name test --net=slirp4netns --rootfs $(realpath $TMP/rootfs/) $(which bash)
Error: executable file `/usr/bin/bash` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found
```

**Comment by rhatdan** [comment]
The which bash will run locally, do you have a $TMP/rootfs/usr/bin/bash?

**Comment by Hoeze** [comment]
No, there are only the following folders:
```bash
# ls -1 $TMP/rootfs/            
dev
etc
proc
run
sys
```

**Comment by rhatdan** [comment]
Then it will never work, there is nothing to run there.  You need to add a /bin directory or /usr/bin.

**Comment by Hoeze** [comment]
I see, getting closer now:
```bash
# podman run -v /usr/:/usr -v /bin:/bin -v /data/:/data -v /home/:/home -v /opt:/opt --group-add=keep-groups -d -i --name test --net=slirp4netns --rootfs $(realpath $TMP/rootfs/) $(which bash) && echo "OK"
b0235ec92c688d1fa8ac5c31041c555a4d0f53ac84061d610fb231126f602bc4
OK
```
Why does the bash shell close immediately?
Running `podman run [...] $(which bash) -c "echo 'test'"` does not return anything as well.

**Comment by rhatdan** [comment]
Add a --tty
Also you probably need to disable SELinux --security-opt label=disable

**Comment by rhatdan** [comment]
We can continue the conversation here, but this is not an issue with Podman.
