### ISSUE TITLE
Podman secret as environment variable not available to exec command 

### ISSUE THREAD

**Issue by millerthegorilla** [containers/podman#11051]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I am using podman run with a secret environment variable for the root password of a maria database container.
Because I am generating systemd units with the --new switch, I don't want the run command to create a database, so instead I run the run command, and then use a podman exec to create the database.  This means that I have to pass in the root password as an environment variable, in order to allow the command to succeed, and this means the root password is readable from the command line, ps -aux, fds etc. so not really secure enough.
So, I would like to be able to reuse my podman run command secret in the following exec command.
ie
```
podman exec -it  --secret=MARIADB_ROOT_PASSWORD,type=env CONTAINER_NAME bash -c "..."
```

**Steps to reproduce the issue:**

1. n/a

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.2.2
API Version:  3.2.2
Go Version:   go1.16.4
Built:        Sat Jun 26 00:49:19 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
n/a
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
n/a
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

n/a

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@ashley-cui PTAL

Did you use the secret command when doing the podman create or podman run?  If yes, then the secret should be available when you exec into the container. If it is not then this is a bug.

If in addition you would like to be able to inject a secret even when podman run/create did not add a secret, then this is a new feature.

**Comment by ashley-cui** [comment]
Secrets are mounted into the container at the time of container creation. Injecting a secret when podman create/run did not add a secret, and doing so via exec seems interesting, I think I can take a look sometime later this week or next week, soon

**Comment by millerthegorilla** [comment]
Ok, thanks, I wasn't aware that the environment variable would still be available.  Is that certainly the case, if so I have read the docs poorly.  I know that if one runs/creates the container using type=mount, then the secret will persist, but I didn't imagine that  an environment variable would persist  from the exec of the run command to a new exec session.
I can't test it at the moment, as I have shut down the machine till tomorrow, but I'll have a look then.
There are other ways to deal with the issue, such as creating a envsubst template in the dockerfile, and running envsubst when the container is created, and then running the script to create the database, which would contain the root password, and then delete itself once it had run.
But it would be hellish easier if I could pass in a secret as an environment variable, assuming it doesn't persist.

**Comment by ashley-cui** [comment]
Looks like a bug then, 
```
$ ./bin/podman run -tid  --secret mysecr,type=env --name a alpine 
d75ec241fe78b6470461c39cdc6defd61ab68fe25594e8899818c9e61ed940e5

$ ./bin/podman exec a printenv
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
TERM=xterm
container=podman
HOME=/root

```

**Comment by millerthegorilla** [comment]
Ok, many thanks for your input.

**Comment by millerthegorilla** [comment]
I finally found some time, and no the secret environment variable is not available in following exec sessions.   I like the fact that this is the case, as this means the variable doesn't persist, but is available for a script that runs as the dockerfile CMD.
I run the podman run command with -d to detach, and then run the exec command.   Currently (lazily) I am passing the maria root password as an environment variable but this is visible to the world, should they have access, so I intend to find a more secure method, and being able to pass in a secret to the exec would be useful.
