### ISSUE TITLE
Not able to install Podman on openshift 4.6

### ISSUE THREAD

**Issue by dattatrayvaze** [containers/podman#11053]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. run below command to install podman

2. sudo yum install podman

3.

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   359  100   359    0     0    391      0 --:--:-- --:--:-- --:--:--   391
Loaded plugins: product-id, search-disabled-repos
devel_kubic_libcontainers_stable                                                                                                                 | 1.3 kB  00:00:00
Resolving Dependencies
--> Running transaction check
---> Package podman.x86_64 0:3.0.1-2.el7.3.1 will be installed
--> Processing Dependency: podman-plugins = 3.0.1-2.el7.3.1 for package: podman-3.0.1-2.el7.3.1.x86_64
--> Processing Dependency: containers-common >= 4:1-4 for package: podman-3.0.1-2.el7.3.1.x86_64
--> Running transaction check
---> Package containers-common.noarch 4:1-18.el7.20.1 will be installed
--> Processing Dependency: oci-runtime for package: 4:containers-common-1-18.el7.20.1.noarch
Package 2:runc-1.0.1-0.el7.1.1.x86_64 is obsoleted by containerd.io-1.4.8-3.1.el7.x86_64 which is already installed
---> Package podman-plugins.x86_64 0:3.0.1-2.el7.3.1 will be installed
--> Finished Dependency Resolution
Error: Package: 4:containers-common-1-18.el7.20.1.noarch (devel_kubic_libcontainers_stable)
           Requires: oci-runtime
           Available: 2:runc-1.0.1-0.el7.1.1.x86_64 (devel_kubic_libcontainers_stable)
               oci-runtime
           Available: runc-0.0.8-1.git4155b68.el7.x86_64 (Local-Extras)
               Not found
           Available: runc-0.1.0-3.el7.x86_64 (Local-Extras)
               Not found
           Available: runc-0.1.1-4.el7.x86_64 (Local-Extras)
               Not found
           Available: runc-0.1.1-5.el7.x86_64 (Local-Extras)
               Not found
           Available: runc-1.0.0-1.rc2.el7.x86_64 (Local-Extras)
               Not found
           Available: runc-1.0.0-3.rc2.el7.x86_64 (Local-Extras)
               Not found
           Available: runc-1.0.0-6.gite800860.el7.x86_64 (Local-Extras)
               Not found
           Available: runc-1.0.0-12.1.gitf8ce01d.el7.x86_64 (Local-Extras)
               Not found
           Available: runc-1.0.0-14.rc4dev.git84a082b.el7.x86_64 (Local-Extras)
               Not found
           Available: runc-1.0.0-21.rc4.dev.gitaea4f21.el7.x86_64 (Local-Extras)
               Not found
           Available: runc-1.0.0-23.rc4.dev.git1d3ab6d.el7.x86_64 (Local-Extras)
               Not found
           Available: runc-1.0.0-26.rc4.dev.git9f9c962.el7.x86_64 (Local-Extras)
               Not found
           Available: runc-1.0.0-27.rc5.dev.git4bb1fe4.el7.x86_64 (Local-Extras)
               Not found
           Available: runc-1.0.0-37.rc5.dev.gitad0f525.el7.x86_64 (Local-Extras)
               Not found
           Available: runc-1.0.0-52.dev.git70ca035.el7_5.x86_64 (Local-Extras)
               Not found
           Available: runc-1.0.0-54.dev.git2abd837.el7.x86_64 (Local-Extras)
               Not found
           Available: runc-1.0.0-57.dev.git2abd837.el7.x86_64 (Local-Extras)
               Not found
           Available: runc-1.0.0-59.dev.git2abd837.el7.x86_64 (Local-Extras)
               Not found
           Available: runc-1.0.0-64.rc8.el7.x86_64 (Local-Extras)
               Not found
           Available: runc-1.0.0-65.rc8.el7.x86_64 (Local-Extras)
               Not found
           Available: runc-1.0.0-66.rc8.el7_7.x86_64 (Local-Extras)
               Not found
           Available: runc-1.0.0-67.rc10.el7_8.x86_64 (Local-Extras)
               Not found
           Available: runc-1.0.0-69.rc10.el7_9.x86_64 (Local-Extras)
               Not found
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Describe the results you expected:**

podman should have been installed successfully.

**Comment by mheon** [comment]
What do you mean by "on Openshift 4.6' - on the base CoreOS operating system, or inside a container run on Openshift? If so, what kind of container - do you know what the base image was?

**Comment by dattatrayvaze** [comment]
the base core OS operating system is Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Comment by rhatdan** [comment]
We don't support Podman 3.* on any RHEL7 box.  This is not supported and not something for upstream.
