### ISSUE TITLE
need to bump buildah to v1.21.3+ in main branch

### ISSUE THREAD

**Issue by lsm5** [containers/podman#11069]
https://github.com/containers/podman/blob/f9395ddc5ad8b32e4e9b24542f0869722f7c9743/go.mod#L14

buildah on main branch needs to be bumped to v1.21.3 or newer.

I tried 2 combos:
- buildah `v1.21.3` + c/common `v0.38.12` 
- buildah `v1.21.4` + c/common `v0.38.16`

both of which gave me compiler errors. The c/common versions are the ones used in the respective buildah versions.

@vrothberg any ideas? Remind me what's the status of dependabot updates on main branch?

**Comment by lsm5** [comment]
also, no luck with c/common v0.40.1 either.

**Comment by TomSweeneyRedHat** [comment]
Looking at Buildah quickly, I think we may need to do a vendor dance across skopeo, podman and buildah for all the c/* projects in preparation for Podman 3.3.  This might be part of your problem @lsm5 

@vrothberg thoughts on appropriate versions for c/storage, c/common, and c/image at least?

**Comment by vrothberg** [comment]
> https://github.com/containers/podman/blob/f9395ddc5ad8b32e4e9b24542f0869722f7c9743/go.mod#L14
> 
> buildah on main branch needs to be bumped to v1.21.3 or newer.
> 
> I tried 2 combos:
> 
>     * buildah `v1.21.3` + c/common `v0.38.12`
> 
>     * buildah `v1.21.4` + c/common `v0.38.16`

Both would _downgrade_ the current dependencies in the main branch. c/common is already over 0.41 and
`github.com/containers/buildah v1.21.1-0.20210721171232-54cafea4c933` is actually newer than 1.23.3.  `go mod` is just not able to find a the right tag and chooses v1.21.1 for whatever reason. You can try it with `$ go get github.com/containers/buildah@main` ... it will again use `v1.21.1-jaddajadda-$HEAD`.

That being said, the security alert is wrong as it is only looking that version but not at the actual commit.

**Comment by vrothberg** [comment]
> Looking at Buildah quickly, I think we may need to do a vendor dance across skopeo, podman and buildah for all the c/* projects in preparation for Podman 3.3. This might be part of your problem @lsm5

Yes, a vendor dance (and hence a new Buildah cut from c/buildah@main) would solve the false alarm.

> @vrothberg thoughts on appropriate versions for c/storage, c/common, and c/image at least?

c/image would be v5.14.x. Not sure for the rest as I am not sure if there's ongoing work or fixes we may need to wait for. Probably something for a Monday PS? I think we can cut a release candidate before the vendor dance.

**Comment by lsm5** [comment]
remind me, when's the right time for vendor dance? and how can i help?

**Comment by lsm5** [comment]
ah I notice we don't really need vendor dance, my bad.

> `github.com/containers/buildah v1.21.1-0.20210721171232-54cafea4c933` is actually newer than 1.23.3. `go mod` is just not able to find a the right tag and chooses v1.21.1 for whatever reason. You can try it with `$ go get github.com/containers/buildah@main` ... it will again use `v1.21.1-jaddajadda-$HEAD`.

@vrothberg so I guess such an issue could occur in future as well? It would be really nice if `@main` could just pick up version from `define/types.go`.

**Comment by vrothberg** [comment]
> remind me, when's the right time for vendor dance? and how can i help?

Any moment in the coming days :) 

> @vrothberg so I guess such an issue could occur in future as well? It would be really nice if @main could just pick up version from define/types.go.

That won't work since `go` looks at Git tree and tries to match the commit against a tag. Depending on the branches, it sometimes picks the wrong one.

**Comment by TomSweeneyRedHat** [comment]
@vrothberg @mheon we need to cut Podman v3.3.0 rc by end of day Monday.  I've started the vendor dance already.

c/common - v0.41.0  - branch v0.41
c/image - v5.14.0 - branch release-5.14
c/storage - v1.33.0 - branch release-v1.33

If anything is wrong with the above let me know.  Currently having issues with Skopeo's make, Buildah PR up, and Podman's in progress.

**Comment by vrothberg** [comment]
@TomSweeneyRedHat, v0.41.0 is wrong. We need a new v0.42. See email.

**Comment by vrothberg** [comment]
I think we can safely close the issue here given it's a false alarm.
