### ISSUE TITLE
podman secret command not found

### ISSUE THREAD

**Issue by SoniKanthP** [containers/podman#11071]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)** BUG REPORT

/kind bug

/kind feature

**Description**

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**
$podman secret
Error: unrecognized command `podman secret`
Try 'podman --help' for more information.

**Describe the results you expected:**
create secrets 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
Version:      3.0.2-dev
API Version:  3.0.0
Go Version:   go1.15.13
Built:        Tue Jun  8 07:52:06 2021
OS/Arch:      linux/amd64

**Output of `podman info --debug`:**
host:
  arch: amd64
  buildahVersion: 1.19.8
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.26-3.module+el8.4.0+11311+9da8acfb.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: a35bb9ea67d5a83c7da53202f2fcd505c036d29c'
  cpus: 2
  distribution:
    distribution: '"rhel"'
    version: "8.4"
  eventLogger: file
  hostname: ip-172-31-0-184.us-west-2.compute.internal
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-147.el8.x86_64
  linkmode: dynamic
  memFree: 119947264
  memTotal: 3962089472
  ociRuntime:
    name: runc
    package: runc-1.0.0-73.rc93.module+el8.4.0+11311+9da8acfb.x86_64
    path: /usr/bin/runc
    version: |-
      runc version spec: 1.0.2-dev
      go: go1.15.13
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.4.0+11311+9da8acfb.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 0
  swapTotal: 0
  uptime: 147h 16m 50.44s (Approximately 6.12 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 11
    paused: 0
    running: 11
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.4.0-3.module+el8.4.0+11311+9da8acfb.x86_64
      Version: |-
        fusermount3 version: 3.2.1
        fuse-overlayfs: version 1.4
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/user/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 29
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1623138726
  BuiltTime: Tue Jun  8 07:52:06 2021
  GitCommit: ""
  GoVersion: go1.15.13
  OsArch: linux/amd64
  Version: 3.0.2-dev

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**
$rpm -q podman
podman-3.0.1-7.module+el8.4.0+11311+9da8acfb.x86_64

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Comment by infiniteregrets** [comment]
> create secrets

I am confused, what are you exactly referring to? Did you see http://docs.podman.io/en/latest/markdown/podman-secret-create.1.html

**Comment by Kiritow** [comment]
Podman secrets seem to be available after Podman 3.1.0 but you are using 3.0. Try upgrade it to latest version.

**Comment by SoniKanthP** [comment]
@Kiritow  - By default I am able to install only 3.0 version. Kindly help how to install/upgrade 3.1 version

# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"


# podman version
Version:      3.0.2-dev
API Version:  3.0.0
Go Version:   go1.15.13
Built:        Tue Jun  8 07:44:00 2021
OS/Arch:      linux/amd64


]# yum module install container-tools
Installing group/module packages:
cockpit-podman      noarch       29-2.module+el8.4.0+11311+9da8acfb         rhel-8-appstream-rhui-rpms      1.1 M
podman  x86_64 3.0.1-7.module+el8.4.0+11311+9da8acfb        rhel-8-appstream-rhui-rpms                          12 M
toolbox   noarch    0.0.8-1.module+el8.4.0+11311+9da8acfb     rhel-8-appstream-rhui-rpms                          16 k
Installing dependencies:
 podman-catatonit                                    x86_64                         3.0.1-7.module+el8.4.0+11311+9da8acfb                                 rhel-8-appstream-rhui-rpms                         323 k
Installing module profiles:
 container-tools/common

**Comment by Kiritow** [comment]
Sorry but I don't have RHEL8 installed. I have removed and install the new version of Podman following `CentOS 8` steps in [Podman Installation](https://podman.io/getting-started/installation) on Rocky Linux 8.4, and it seems to work fine.

**Comment by SoniKanthP** [comment]
Thank you @Kiritow . I followed the installation steps for Centos8 and I can install now Podman latest version (3.2.3)

**Comment by mheon** [comment]
Looks like this is answered, so closing.
