### ISSUE TITLE
support connect remote server over a proxy

### ISSUE THREAD

**Issue by shuaiyy** [containers/podman#11078]
/kind feature

**Description**

i have a remote podman server in production environment，with a network ACL limit, i have to use a proxy(socks5 or ssh jump server) to visit my service.
but i didn't find a way to set proxy, please give a help, thx!

**Comment by mheon** [comment]
@jwhonce PTAL

**Comment by jwhonce** [comment]
@shuaiyy Currently we do not provide a transparent way to do what you ask. 

As a work around that might work, run ssh port forward (-L) between local host and bastion host which runs another ssh command on the bastion to forward (-L) the same port to the production environment anchored to port/socket. Then configure your podman client to connect to the local socket.

**Comment by shuaiyy** [comment]
@jwhonce thanks for reply.
the solution may work, but not general, it's difficult to ask every my user to do that.
i try to import this project in my golang project and build a proxied `bindings.Connection`, but the `clientKey` is unexported， i can't add my proxied Connection object into a ctx with ``

**Comment by jwhonce** [comment]
@shuaiyy How about adding `bindings.ConnectionWithClient(ctx context.Context, client *http.Client) (context.Context, error)`? It would not break encapsulation or any current users.

```go
// Build custom http.client...
client := MyHttpClient()
conn, _ := bindings.NewConnection(...)
conn, _ := conn.ConnectionWithClient(conn, client)
```

**Comment by shuaiyy** [comment]
@jwhonce great idea! 

about the example  detail,  `bindings.NewConnection(...)` always return a nil `conn`,  cause `pingNewConnection`  will fail without a custom `http.client`. 

how about  this one `bindings.NewConnectionWithClient(ctx context.Context, uri string, client *http.Client)(context.Context, error)`

**Comment by baude** [comment]
@shuaiyy happy enough to close?

**Comment by rhatdan** [comment]
Reopen if this is not fixed.
