### ISSUE TITLE
Build a Dockerfile as rootless not possible via Gitlab 

### ISSUE THREAD

**Issue by ImanGharib** [containers/podman#11083]
I try to build an Image from Docker file via Gitlab like this:
`deploy:
  stage: deploy
  script:
    - echo "the project directory is - $CI_PROJECT_DIR"
    - cat $CI_PROJECT_DIR/README.md ; echo
    - echo "and where am I? - $PWD"
    - echo "CONTAINER_OWNER=$(whoami)"
    - echo "Start building image for client"
    - cd client
    - podman build -t lm-client-dev .
    - echo "Start creating container"
    - podman run lm-client-dev -d --restart=always --pod=lm-dev`
  but I get error as follow: 
`$ podman build -t lm-client-dev .
time="2021-07-30T14:25:56+02:00" level=error msg="cannot find mappings for user vagrant: No subuid ranges found for user \"vagrant\" in /etc/subuid"
STEP 1: FROM node:16.5-alpine3.14
Getting image source signatures
Copying blob sha256:e9d0d9a61f19bb1a72fa8e0ba3b59c540b5fb3efdcfd18ef791c89df65124ac5
Copying blob sha256:5843afab387455b37944e709ee8c78d7520df80f8d01cf7f861aae63beeddb6b
Copying blob sha256:a323d77b1d49df4d6e599429af7f9d22261517634f01b40c9e5d667605a6bbde
Copying blob sha256:375bc03a48532f283299c8274457241e4ba17c54e961237743485a2de23d8be3
Copying config sha256:f88956284d230b0e2a76638c1be616e272b5b9e7db19c41bacd356a857154bb2
Writing manifest to image destination
Storing signatures
Error: error creating build container: The following failures happened while trying to pull image specified by "node:16.5-alpine3.14" based on search registries in /etc/containers/registries.conf:
* "localhost/node:16.5-alpine3.14": Error initializing source docker://localhost/node:16.5-alpine3.14: error pinging docker registry localhost: Get https://localhost/v2/: dial tcp [::1]:443: connect: connection refused
* "registry.access.redhat.com/node:16.5-alpine3.14": Error initializing source docker://registry.access.redhat.com/node:16.5-alpine3.14: Error reading manifest 16.5-alpine3.14 in registry.access.redhat.com/node: name unknown: Repo not found
* "registry.redhat.io/node:16.5-alpine3.14": Error initializing source docker://registry.redhat.io/node:16.5-alpine3.14: unable to retrieve auth token: invalid username/password: unauthorized: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication
* "docker.io/library/node:16.5-alpine3.14": Error committing the finished image: error adding layer with blob "sha256:5843afab387455b37944e709ee8c78d7520df80f8d01cf7f861aae63beeddb6b": Error processing tar file(exit status 1): there might not be enough IDs available in the namespace (requested 0:42 for /etc/shadow): lchown /etc/shadow: invalid argument`

On my host (redhat 8) I have registered my auth token and have added a user named vagrant:
grep vagrant /etc/subuid /etc/subgid
/etc/subuid:vagrant:1083040:65536
/etc/subuid:vagrant:200000:1001

but still getting the same error. 

podman info:
`host:
  arch: amd64
  buildahVersion: 1.21.3
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.el8.3.7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: '
  cpus: 20
  distribution:
    distribution: '"rhel"'
    version: "8.4"
  eventLogger: journald
  hostname: mail.semdatex.de
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-305.7.1.el8_4.x86_64
  linkmode: dynamic
  memFree: 8123510784
  memTotal: 99643265024
  ociRuntime:
    name: crun
    package: crun-0.18-2.module+el8.4.0+11311+9da8acfb.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.18
      commit: 808420efe3dc2b44d6db9f1a3fac8361dde42a95
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4263383040
  swapTotal: 4294963200
  uptime: 678h 35m 36.52s (Approximately 28.25 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 0
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.2.3
  Built: 1626840471
  BuiltTime: Wed Jul 21 06:07:51 2021
  GitCommit: ""
  GoVersion: go1.15.13
  OsArch: linux/amd64
  Version: 3.2.3`

**Comment by mheon** [comment]
Can you provide the Dockerfile that Podman is being instructed to build? Really need to see the `FROM` line.

**Comment by ImanGharib** [comment]
sure:
`FROM node:16.5-alpine3.14

WORKDIR /usr/src/app

COPY package*.json /usr/src/app/package.json
RUN npm install

COPY . /usr/src/app

EXPOSE 3000

# start app
CMD ["npm", "run", "start"]`

**Comment by mheon** [comment]
```
idMappings:
gidmap: null
uidmap: null
```

From your `podman info` - looks like UID and GID mappings are not set up.

Please try running `podman system migrate`

**Comment by ImanGharib** [comment]
Thanks a lot for your answer. The problem was that the runner for GitLab is running in a VM which I was not aware of. So the changes I made on the server had no effect on that. I added the uid in VM and it works.
