### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by qhaas** [containers/podman#11088]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Podman users can achieve [rootless GPU acceleration with nvidia GPUs using the nvidia-container-runtime](https://www.redhat.com/en/blog/how-use-gpus-containers-bare-metal-rhel-8).  This has limitations.  [It requires setting subuids for each user needing GPU acceleration](https://github.com/NVIDIA/nvidia-container-runtime/issues/145) and it only works with nvidia GPUs.  AMD is making inroads with GPU compute, such as with the upcoming [Frontier supercomputer](https://www.olcf.ornl.gov/frontier/).

[Singularity has achieved GPU acceleration without root/subuid and supports both nvidia and AMD GPUs](https://sylabs.io/guides/3.8/user-guide/gpu.html).  It [does not need nvidia-container-runtome](https://sylabs.io/guides/3.8/user-guide/gpu.html#library-search-options) to be installed since it can [mount the needed libraries / devices from the host inside the container](https://sylabs.io/guides/3.8/admin-guide/configfiles.html#gpu-library-configuration).

Since GPU acceleration is becoming a 'must-have' for many users, is it possible with podman's architecture to use Singularity's approach to GPU acceleration and forgo the reliance upon nvidia-container-runtime for GPU acceleration?

**Comment by vrothberg** [comment]
Thanks for reaching out, @qhaas.

I am convinced that we can get it to run with Podman as well.  In most cases, we need to bind mount a number of libraries into the container along with the specific devices. User can do that manually at the moment.  Singularity seems to have some special flags that do much of the heavy lifting for the user (e.g., `--rocm`).

We always welcome contributions, so feel free to open a pull request and we can help.

Cc: @rhatdan @fatherlinux

**Comment by mheon** [comment]
My concern about adding a flag for this is that I don't know if we can reasonably create a configuration that will work on all hosts - I don't know if there are guarantees that these libraries always exist at the same locations, and with permissions such that we can consistently access them.

**Comment by proutrc** [comment]
Is an option of a configuration file possible? Similar to *liblist.conf files in Singularity (looks like per vendor config files - Nvidia and AMD)? This allows the admins of the system to configure the access for their users. In this case, Podman shouldn't have to assume anything about location or permissions.

**Comment by vrothberg** [comment]
@proutrc, you can use containers.conf (see `man containers.conf`) which supports all kinds of settings.  As mentioned in the man pages, we can point Podman to a custom file via the `CONTAINERS_CONF` environment variable.  So if you have a custom containers.conf for running with NVIDIA GPUs, you do a `$ CONTAINERS_CONF=/path/to/nvidia.containers.conf podman run ...`.

**Comment by qhaas** [comment]
> I don't know if we can reasonably create a configuration that will work on all hosts

It would be a pain, but that is how Singularity does it with [nvidia](https://github.com/sylabs/singularity/blob/master/etc/nvliblist.conf) and [AMD](https://github.com/sylabs/singularity/blob/master/etc/rocmliblist.conf).   If the software licenses permits, could just use those.  I'd also recommend the ability to override said lists with another list at the regular user level (e.g. a setting in a user's `~/.config`) in case podman is not kept in lock-step with driver stack.

Given the target audience for this feature would likely be multi-user, HPC systems, I could see the GPU OEMs being convinced to help maintain such a list for major, long-term support software releases.  Most end-users on their workstations will likely continue to set subuid, run with sudo, etc. with the nvidia-container-runtime since the marketshare of AMD compute oriented GPUs is likely low (for now) and IT policy is typically different between single-user workstations and multi-user HPC systems.

**Comment by eriksjolund** [comment]
The [SingularityCE roadmap](https://github.com/sylabs/singularityce-community/blob/main/roadmap.md) (the Sylabs fork) discusses how to improve NVIDIA GPU / CUDA support. 

A quote (regarding the current approach):
 _this works well, but does not support features such as GPU masking, MIG awareness_

**Comment by zvonkok** [comment]
We are working on an interface for any runtime: https://github.com/container-orchestrated-devices/container-device-interface

The needed files are in different locations in Debian, RHEL, SUSE. Also, the number of files to mount can and has changed. Additionally, the prestart hook also creates symlinks to some libraries and handles some start/stop of needed processes. 

And to clarify we do not need the runtime only the hook in RHEL and RHEL based OS. The runtime is needed for runtimes that do not support OCI hooks.  'containerd' has hardcoded the call of the prestart hook but you still need to install the hook package. 

For MIG support the hook and the dependent libraries were updated, we will release a blog post soon on how to use MIG on OpenShift and Podman. 

The business logic of how to enable GPUs is encoded in the nvidia-container-cli which the hook just calls to enable the GPU.

**Comment by elezar** [comment]
@zvonkok I know that CDI support was recently merged in #10081. Would there be benefit in driving this further? From the NVIDIA side, we could provide tooling to generate a CDI spec for the available devices. This could then be consumed by podman and other container runtimes as these start to offer CDI support.

cc @bart0sh

**Comment by zvonkok** [comment]
@bthurber @mrunalp PTAL

**Comment by rhatdan** [comment]
@zvonkok what are they supposed to look at?

**Comment by vrothberg** [comment]
friendly ping

**Comment by zvonkok** [comment]
@rhatdan Several folks from different companies are working on this: [https://github.com/container-orchestrated-devices/container-device-interface](https://github.com/container-orchestrated-devices/container-device-interface ), recently podman merged #10081 so it could consume a CDI configuration. 

@elezar I think this would be a good start with podman and GPUs and see how the CDI pipeline would work. I spoke to several vendors to take a look at CDI before implementing their own prestart hook again. 

@mrunalp @bthurber let's take NV (again) as the example for how to enable hardware accelerators in a container "correctly" and get away from using prestart hooks. 

@elezar Can you provide an CDI spec that we could use for testing?

**Comment by elezar** [comment]
@zvonkok the CDI spec would depend on the devices that are available on the host. I still have to implement tooling to extract this, but may be able to get to this next week. I will update here as soon as I have something that is useful.

**Comment by zvonkok** [comment]
@elezar We could do a V100 or T4 enablement in podman. 

/cc @dagrayvid  @kpouget

**Comment by rhatdan** [comment]
@zvonkok @elezar what is up with this issue?

**Comment by elezar** [comment]
The tooling to generate a CDI spec for installed NVIDIA devices is available in an MR. We have not been able to move forward on testing the podman CDI integration though. Is there someone that we could work with directly to start moving forward on this?

**Comment by rhatdan** [comment]
You want someone from the Podman team?

**Comment by elezar** [comment]
I will look into this again once I'm back from PTO.

**Comment by rhatdan** [comment]
@elezar any progress?

**Comment by elezar** [comment]
@rhatdan I wasn't able to get to this at the end of last year, but I will spend the next couple of days getting started on this. There was also some work done on the CDI tooling in container-orchestrated-devices/container-device-interface#39 that I will look at integrating if required. I will open PRs as neccessary.

**Comment by rhatdan** [comment]
Awesome thanks.

**Comment by elezar** [comment]
@qhaas with #12825 merged, we could look at creating a CDI spec for devices, libraries, environment variables, and hooks for the use cases that you describe in your initial comment. At present the NVIDIA CDI spec I used for testing still relies on the `nvidia-container-toolkit` to be installed, but this is not generally true and many steps performed by the prestart hook could be captured in the spec instead.

**Comment by rhatdan** [comment]
Since #12825 has been merged, I am going to close this issue.  Reopen if I am mistaken.

**Comment by elezar** [comment]
I don't know whether this ticket can be closed. I think the work in #12825 would enable what is requested in this ticket, but there would still be more work to do -- in terms of documenting how this could be done and constructing the relevant CDI specs. If @qhaas feel that this could be done elsewhere then let's close this and track this there. 

@qhaas one option would be to continue the discussion in the CDI repo. Please let me know if you need assistance from my side.

**Comment by rhatdan** [comment]
I am closing the issue.
