### ISSUE TITLE
Error: invalid config provided: rootless containers and pods cannot be assigned static MAC addresses

### ISSUE THREAD

**Issue by alexisfrjp** [containers/podman#11112]
How to use `--mac-address` with a rootless container?

* `podman run --rm -it --mac-address=02:23:45:67:89:ab centos:latest`

I get this error: `Error: invalid config provided: rootless containers and pods cannot be assigned static MAC addresses`

**Comment by Luap99** [comment]
You have to use this together with `--network ...`

**Comment by alexisfrjp** [comment]
By default it should be `--network=slirp4netns`, 
I also tried with `--network=host` and `--network=private` but I get the same error.

**Comment by Luap99** [comment]
Sorry, I forgot to mention that you need to use a cni network, create one with `podman network create ...` and add `--network <netname>`

**Comment by alexisfrjp** [comment]
I was doing it but I need to build the `rootless-cni-infra` before testing. It should work.
Thank you for your help.

**Comment by Luap99** [comment]
With podman v3.2 and newer you no longer need the rootless-cni-infra image. I recommend updating if possible.

**Comment by alexisfrjp** [comment]
Thank you for that info!
I just tried and it works, perfect!
