### ISSUE TITLE
timing flake: podman stop/pause takes long time

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#11146]
Two timing flakes being reported by the multiarch testing group:
* https://gitlab.com/cki-project/kernel-tests/-/issues/641
* https://gitlab.com/cki-project/kernel-tests/-/issues/642

In one case, `podman stop` is taking 3 seconds; in the other, a `podman pause`, `podman unpause` sequence is taking 7. These are tests that do not flake in CI nor gating tests, but they're flaking on other-arch systems (metal, not emulated).

Relevant code:
https://github.com/containers/podman/blob/b243185e4fbf002c381b4d6cf9be1fe25450f4b9/test/system/050-stop.bats#L86-L94

https://github.com/containers/podman/blob/b243185e4fbf002c381b4d6cf9be1fe25450f4b9/test/system/080-pause.bats#L24-L31

Solution would be easy: bump up the allowed time. I'm uncomfortable doing that, because these commands really should not be taking that long.

We don't have reproducer systems or really any useful details. I'm filing this issue in the desperate hope that someone will recognize a possible flaw in podman's non-x86_64 operation.

**Comment by vrothberg** [comment]
It really seems like there are some signal-handling issues on non x86 machines.

**Comment by vrothberg** [comment]
I'll try to revive a Raspberry Pi in my drawer to have a closer look.

**Comment by pclass-sensonix** [comment]
On my SAMA5D27 Microchip ARM platform - stopping a podman container running a simple python flask webserver is a very slow and costly operation. It can be longer than 10-15 seconds. Starting the application seems to be much less expensive in time.

**Comment by edsantiago** [comment]
@pclass-sensonix have you tried `podman stop --timeout 0` or `podman kill --signal SOMETHING-OTHER-THAN-TERM`? Some processes ignore `SIGTERM`; podman then waits ten seconds before sending `SIGKILL`

**Comment by rhatdan** [comment]
@edsantiago @vrothberg Still not fixed?

**Comment by vrothberg** [comment]
@edsantiago, do we still see these flakes?  I increased the signal buffers a short while ago and think this _may_ have fixed it.

**Comment by edsantiago** [comment]
I am spending a ridiculous amount of time looking at test failures in the multiarch setup, and one common factor that appears over and over is that podman is ultra-incredibly-slow on non-x86_64. Nobody knows if it's podman, or kernel, or POM. I've asked for a reproducer system, but the failures are not 100% reliable. If/when I can get a system that exhibits this behavior, I will reach out for developer help.

**Comment by rhatdan** [comment]
@edsantiago giving up yet?  :^)

**Comment by edsantiago** [comment]
Absent a way to reproduce this, I see no alternative.
