### ISSUE TITLE
Podman is very spammy around health-checks

### ISSUE THREAD

**Issue by Spindel** [containers/podman#11157]
/kind bug

**Description**

Podman healthchecks are quite spammy as they are always printing output, rather than obeying log-levels on running containers.  This in practice causes podman to have an almost absurd log volume on machines that run a few containers with health-checks enabled.

When running podman containers as a systemd service, this becomes even worse as there will be a neat little prefix and suffix from systemd about activating adn deactivating the generated service.

The "healthy"  message is a print-out on stdout, while I would have expected it to be a log-message on a level less than "Warning", as "normal  healthcheck" should be expected to happen every 5 seconds anyhow.

Then there is the "container exec" line:

`Aug 07 12:47:36 spring.skuggor.se podman[8022]: 2021-08-07 12:47:36.630307078 +0000 UTC m=+0.343193648 container exec 62ed6777043d7f648d92fd79d34bd7a4157dba4e2ad7375f0c5e1c5b68534d12 (image=docker.io/dperson/samba:latest, name=samba, PODMAN_SYSTEMD_UNIT=samba.service, io.containers.autoupdate=image)`

Which is the bigger nasty in here, and another message I would not expect to see every few seconds simply for health-checks.

**Steps to reproduce the issue:**

1. Launch a container,  use "podman generate systemd".
2. Trigger a healthcheck every 5 seconds, perhaps just running /bin/true to make sure
4. Spawn a few more such containers
5. Watch as podman's logging consumes a fairly absurd amount of log traffic

**Describe the results you received:**
Healthcheck services as generated by podman cause a systemd-service to trigger every N seconds, causing an continious IO-load on the system and ignoring log-settings.

**Describe the results you expected:** 

Health checks would be fairly quiet in logs unless something failed.
Health-checks would output log-data via the same log driver as the configured job it is tied to.
Health-checks would not cause service enable-disable every N seconds. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.13.15
Built:        Sat Jul 17 00:00:00 2021
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.21.3
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.29-1.1.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: unknown'
  cpus: 4
  distribution:
    distribution: '"opensuse-microos"'
    version: "20210805"
  eventLogger: journald
  hostname: spring.skuggor.se
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.13.6-1-default
  linkmode: dynamic
  memFree: 157605888
  memTotal: 14546845696
  ociRuntime:
    name: runc
    package: runc-1.0.1-1.1.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.1
      spec: 1.0.2-dev
      go: go1.13.15
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 1069543424
  swapTotal: 1073737728
  uptime: 1h 20m 0.56s (Approximately 0.04 days)
registries:
  search:
  - registry.opensuse.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 9
    paused: 0
    running: 5
    stopped: 4
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Build Version: 'Btrfs v5.13 '
    Library Version: "102"
  imageStore:
    number: 12
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.2.3
  Built: 1626480000
  BuiltTime: Sat Jul 17 00:00:00 2021
  GitCommit: ""
  GoVersion: go1.13.15
  OsArch: linux/amd64
  Version: 3.2.3

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.2.3-1.1.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Not applicable

**Comment by pclass-sensonix** [comment]
I agree - the successful container healtchecks I have setup are very noisy in the journald logs on my system.

**Comment by baude** [comment]
@rhatdan you assigned to me but I don't really understand what you want ... they have noisy healthchecks.  do you want a change in policy for healthchecks?

**Comment by rhatdan** [comment]
My understanding of their complaint, is that when healthy we are logging messages at a level of Warning or above rather then in Debug mode.

**Comment by Spindel** [comment]
Partially.

podman actually prints healthy to standard out, rather than logging it.

The other thing is that podman uses a systemd service that it continuously
starts over and over again, causing more log lines, rather than a simple
persistent health-check.

ie, health checks running every 5s will cause a service started+exec into
container + result + service stopped, causing approximately 1kb of log-spam
for each health check invocation.

Further than that, it also isn't using the same log-settings as the main
invocation.

**Comment by mheon** [comment]
It sounds like you're asking for a some rather fundamental changes to how we do healthchecks. For context, we're using systemd deliberately (we don't have a persistent daemon, so systemd timer units are a logical way of triggering periodic execution. I would characterize this as a fundamental design decision of how we implemented healthchecks, and not one we'd revisit lightly.

The actual healthchecks are performed via an exec under the hood, producing the event you're seeing (our events log to journald by default - this is the `container exec` log). The type of that event is actually incorrect (to match Docker it should be a `health_status` event), so we can't get rid of that - it's carrying information on whether the HC was successful or not. We could theoretically get rid of this one, but I don't think we can do so without impacting Docker compat.

**Comment by mheon** [comment]
Could you expound on healthchecks not using the same log settings as the main Podman invocation, though? That sounds like a bug.

**Comment by Spindel** [comment]
It's printing results to stdout, and the podman log isn't passed via the systemd log output when the main container uses that.

So where systemd is responsible for 2 of the lines (service enable/disable), podman's health check is responsible for the rest, and those are still spammy.

**Comment by mheon** [comment]
Can you provide the full output you're seeing and identify the parts you see as spammy?

**Comment by Spindel** [comment]
A typical single task shows like this ( stripped from where they interleave)

Aug 07 11:57:47 spring.skuggor.se systemd[1]: Started /usr/bin/podman
healthcheck run
62ed6777043d7f648d92fd79d34bd7a4157dba4e2ad7375f0c5e1c5b68534d12.
Aug 07 11:57:47 spring.skuggor.se podman[2495]: 2021-08-07
11:57:47.582356972 +0000 UTC m=+0.326028928 container exec
62ed6777043d7f648d92fd79d34bd7a4157dba4e2ad7375f0c5e1c5b68534d12 (image=
docker.io/dperson/samba:latest, name=samba, io.containers.autoupdate=image,
PODMAN_SYSTEMD_UNIT=samba.service)
Aug 07 11:57:48 spring.skuggor.se podman[2495]: healthy
Aug 07 11:57:48 spring.skuggor.se systemd[1]:
62ed6777043d7f648d92fd79d34bd7a4157dba4e2ad7375f0c5e1c5b68534d12.service:
Deactivated successfully.


At a log level of warning, I would not expect  neither "Healthy" or "exec"
in my normal output.

**Comment by mheon** [comment]
The `exec` line is an event, and it will always appear, regardless of log level; we're logging the status of the exec into the container. The `healthy` line could be trimmed, though.

**Comment by rhatdan** [comment]
"healthy" should be eliminated, and I agree that the healthcheck unit should match up with the unit file it is checking.

**Comment by rhatdan** [comment]
Since healthy has been eliminated, I am going to close this issue.  If you would like additional changes please open a new issue.
