### ISSUE TITLE
Container port mapping issue

### ISSUE THREAD

**Issue by wzpoo** [containers/podman#11159]
/kind bug

**Description**

I want to use podman restful api to start image and implement port mapping.After I create a container, I use the command "podman ps -a" to see info of the container.It shows '0.0.0.0:4000->3000/tcp'.But I can't access this port in the brower.How should I do?
If I use the command 'podman run -p 0.0.0.0:4000:3000 rtw:latest' , it work well. My docker image is  rtw:latest and it has no problem.

**Steps to reproduce the issue:**

1.create a container, the api is http://127.0.0.1:8888/v3.0.0/libpod/containers/create the payload are:
```
{
"image":"docker.io/wzpoo/rtw:latest",
"portmappings:[
{"container_port":3000,
"host_ip":"0.0.0.0",
"host_port":4000,
"protocol":"tcp",
"range":1}
],
"user":"user",
"remove":true,
"command":["top"]
}
```
2.the response code is 201 and I decode the container id, then I use http://127.0.0.1:8888/v3.0.0/libpod/containers/{name}/start to start this container

**Describe the results you received:**
In the brower, I input 'http://127.0.0.1:4000', it show error. It means that port mapping failed.

**Describe the results you expected:**
I can access the mapping port in the brower

**Output of `podman version`:**

```
 version: v3.0.0
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 8
  distribution:
    distribution: ubuntu
    version: "18.04"
  eventLogger: journald
  hostname: ubuntu
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.4.0-80-generic
  linkmode: dynamic
  memFree: 888664064
  memTotal: 8319324160
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.18.1-7931a-dirty
      commit: 7931a1eab0590eff4041c1f74e2844b297c31cea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.3.1
  swapFree: 1984163840
  swapTotal: 2147479552
  uptime: 82h 19m 4.54s (Approximately 3.42 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/workstation/.config/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 0
    stopped: 6
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/workstation/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 2
  runRoot: /run
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by Luap99** [comment]
It looks like you are overwriting the container command in your json payload. Remove the `"command":["top"]` part and it should work.

**Comment by wzpoo** [comment]
> It looks like you are overwriting the container command in your json payload. Remove the `"command":["top"]` part and it should work.

remove the "command": ["top"], the issue also exist.

**Comment by Luap99** [comment]
Can you provide the output of podman inspect on the container.

**Comment by wzpoo** [comment]
> Can you provide the output of podman inspect on the container.

[
    {
        "Id": "d806cb392902d692d30b11372c5aa6a92acbbdffbeaf96923b7b9948efe7dce6",
        "Created": "2021-08-09T19:26:48.282103785+08:00",
        "Path": "setup.sh",
        "Args": [
            "setup.sh"
        ],
        "State": {
            "OciVersion": "1.0.2-dev",
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 81389,
            "ConmonPid": 81372,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-08-09T19:26:48.596850581+08:00",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Healthcheck": {
                "Status": "",
                "FailingStreak": 0,
                "Log": null
            }
        },
        "Image": "b6d836aa6baae9333666b88479722ac443543dc9e713a8a891d0d50f23ae1cf1",
        "ImageName": "docker.io/wzpoo/rtw:latest",
        "Rootfs": "",
        "Pod": "",
        "ResolvConfPath": "/run/containers/storage/overlay-containers/d806cb392902d692d30b11372c5aa6a92acbbdffbeaf96923b7b9948efe7dce6/userdata/resolv.conf",
        "HostnamePath": "/run/containers/storage/overlay-containers/d806cb392902d692d30b11372c5aa6a92acbbdffbeaf96923b7b9948efe7dce6/userdata/hostname",
        "HostsPath": "/run/containers/storage/overlay-containers/d806cb392902d692d30b11372c5aa6a92acbbdffbeaf96923b7b9948efe7dce6/userdata/hosts",
        "StaticDir": "/var/lib/containers/storage/overlay-containers/d806cb392902d692d30b11372c5aa6a92acbbdffbeaf96923b7b9948efe7dce6/userdata",
        "OCIConfigPath": "/var/lib/containers/storage/overlay-containers/d806cb392902d692d30b11372c5aa6a92acbbdffbeaf96923b7b9948efe7dce6/userdata/config.json",
        "OCIRuntime": "crun",
        "ConmonPidFile": "/run/containers/storage/overlay-containers/d806cb392902d692d30b11372c5aa6a92acbbdffbeaf96923b7b9948efe7dce6/userdata/conmon.pid",
        "Name": "gracious_northcutt",
        "RestartCount": 0,
        "Driver": "overlay",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "containers-default-0.33.4",
        "EffectiveCaps": null,
        "BoundingCaps": [
            "CAP_CHOWN",
            "CAP_DAC_OVERRIDE",
            "CAP_FOWNER",
            "CAP_FSETID",
            "CAP_KILL",
            "CAP_NET_BIND_SERVICE",
            "CAP_SETFCAP",
            "CAP_SETGID",
            "CAP_SETPCAP",
            "CAP_SETUID",
            "CAP_SYS_CHROOT"
        ],
        "ExecIDs": [],
        "GraphDriver": {
            "Name": "overlay",
            "Data": {
                "LowerDir": "/var/lib/containers/storage/overlay/6b06b05f7ef7e36bb6e5316c4cfba0b43520791a8f08b11cd2d71e6c40fd3c3b/diff:/var/lib/containers/storage/overlay/c0e1e77ccf807a9924e4484d9f84852642d5ed0ddd24d911b1e09812c00ddc56/diff:/var/lib/containers/storage/overlay/c217720c120b2ddedaeb8b3254ff90efb29bdae782f7bf5d619141f673173e9c/diff:/var/lib/containers/storage/overlay/76dafc60935a360b85ef81d3dcb051bacd3471e47a9193129af622e931612f7f/diff:/var/lib/containers/storage/overlay/45d828cf33d1ffd60840eac3aecb7c856a09be9ba95495eb9cd4c7b1c9e39018/diff:/var/lib/containers/storage/overlay/b92fd14d9bb17e06cbbc51789461a9605b851cfb000603560f443104cd8303ee/diff:/var/lib/containers/storage/overlay/79d1a4afb9b8c8851efc59006d98163ca0ce970fb517d9d0ae1e1d5e75aef152/diff:/var/lib/containers/storage/overlay/bc2a36abf7ba39633865fefe26c1d11f45b1d04f1226b289c89b691076bf2b41/diff:/var/lib/containers/storage/overlay/620766bf52104a331926cf1a28b9b4c86149c7bff867cebf2f29a46adcf816ce/diff:/var/lib/containers/storage/overlay/cf8fa6a873b7a9cd53ab5441be6f0759bd4b032d5d50c6ad6d8f1fb2595fab1e/diff:/var/lib/containers/storage/overlay/7ed52e4533531de14c7a6036649318a79d01498729e3cb8ca57a4e5838aae8af/diff:/var/lib/containers/storage/overlay/29d9e4d12f4dc1190b34b462a0b795ae78f3e7af67a907258e7498de23e40990/diff:/var/lib/containers/storage/overlay/64b95bb6ca8ddf6e7f6fbb716ee963d6f1d4ac9e95940accf913b1fd1e73d118/diff:/var/lib/containers/storage/overlay/e586c206a321512643d37a4fd2cbec17609dca849976bb215b74a453427962c3/diff:/var/lib/containers/storage/overlay/63786b64e5aff3aae4d091951650270c986978aae9110b0e7d0a945d58939abb/diff:/var/lib/containers/storage/overlay/f5f2f2e7be4f67ea4a64b745cb2e8e4d1684154215f2865e824fc88859910e2d/diff:/var/lib/containers/storage/overlay/d15b096f0c6a2b675823b9407c9750065e1e544fb889b70b67f9cfb587da39a9/diff:/var/lib/containers/storage/overlay/1fa1d9b3757fc1522a8328a268158911eb568bb8e955b62c41e42f06cdba034f/diff:/var/lib/containers/storage/overlay/8141009263b2d55a328e53c88b7d8f11a5a5d2098a40e67a618dd17fc9019dbc/diff:/var/lib/containers/storage/overlay/3d25cdec587e0afc3ae3b490a323d43395a4abf11a5d216ab203d81c50344c35/diff:/var/lib/containers/storage/overlay/4a3e4083cda74872b30ea99537f2775ae8820a96da9b957dc630ab522a447822/diff:/var/lib/containers/storage/overlay/f087376e9abe3c8ff5a10472dcf6775b60aec09b59247ff1c921cbf782b738e9/diff:/var/lib/containers/storage/overlay/fd61d8e87859f06dc4a226248a5ad6e56f6c41e7b2678c721cff2ccaf9f7594c/diff:/var/lib/containers/storage/overlay/e371be661428dffdb5a136f898afa65e1e66ad988bac09180ef3150f221c8b13/diff:/var/lib/containers/storage/overlay/fe6fd6d0669cffaf5cd919a12e0540f25cf68cdfefb5a32fed753caee358667b/diff:/var/lib/containers/storage/overlay/eb92db6bc713fa199f3bfdfb9a1fcbe397759c6c12a9fbac5ef1c5b3ec2047ed/diff:/var/lib/containers/storage/overlay/d09b97801bda777e72c25ae7a8a3133d5beba1329ce371f3d7a9e6655f9b15e0/diff:/var/lib/containers/storage/overlay/fc9cbc783b7c841911721398951fc7d5862364b1a6a70688a438225350075047/diff:/var/lib/containers/storage/overlay/fbc280fbd829fdc528a153b5f5dc45902fe0ff9503ccba53ef14627222c85c3a/diff:/var/lib/containers/storage/overlay/b2e0a1e3f08d39a6b47dc58ddf4a6dc7c364f68ec3b41a35603405ef15ab2681/diff:/var/lib/containers/storage/overlay/861ffa79ab42fd2c5e1ee1c2dd2210c2f9d5b1f72bbf81045e1e84ae2f4cb8c2/diff:/var/lib/containers/storage/overlay/fd78a0fe3a572e60c47b65a21a7886963537e27de42a306646df7b5028905d6a/diff:/var/lib/containers/storage/overlay/808ecddccf3fbfaca393e677ee22ee77d1e21523157363ac7fe89716edee290f/diff:/var/lib/containers/storage/overlay/c2341c9c867ee2a78ccd70d1d9b6f34a1f594458ad1df4def5e915d78146b963/diff:/var/lib/containers/storage/overlay/118636467a4e2b526056ee3f695a8aec73ad9902376a7fb10cb803f82120f0f8/diff:/var/lib/containers/storage/overlay/ae3a7ac278055a88e5dcf18ccd81b4959494f6846d723220b4d12aa883f60a90/diff:/var/lib/containers/storage/overlay/878dab86cf0f5ad62033738e93d064580c63a6a2140badccddc8e7bddd45fd94/diff",
                "MergedDir": "/var/lib/containers/storage/overlay/582c012ad16200c1f71c6145c2ae4e5d2cbae24a6cad3794d47b67fa2c10995e/merged",
                "UpperDir": "/var/lib/containers/storage/overlay/582c012ad16200c1f71c6145c2ae4e5d2cbae24a6cad3794d47b67fa2c10995e/diff",
                "WorkDir": "/var/lib/containers/storage/overlay/582c012ad16200c1f71c6145c2ae4e5d2cbae24a6cad3794d47b67fa2c10995e/work"
            }
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/home/workstation/Documents/test/math/section1/3",
                "Destination": "/home",
                "Driver": "",
                "Mode": "",
                "Options": [
                    "rbind"
                ],
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Dependencies": [],
        "NetworkSettings": {
            "EndpointID": "",
            "Gateway": "10.88.0.1",
            "IPAddress": "10.88.0.32",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "MacAddress": "42:9c:9a:df:27:79",
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "3000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "10000"
                    }
                ]
            },
            "SandboxKey": "/run/netns/cni-8d936d90-7971-602f-f592-a85c685c263a",
            "Networks": {
                "podman": {
                    "EndpointID": "",
                    "Gateway": "10.88.0.1",
                    "IPAddress": "10.88.0.32",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "42:9c:9a:df:27:79",
                    "NetworkID": "podman",
                    "DriverOpts": null,
                    "IPAMConfig": null,
                    "Links": null
                }
            }
        },
        "ExitCommand": [
            "/usr/bin/podman",
            "--root",
            "/var/lib/containers/storage",
            "--runroot",
            "/run/containers/storage",
            "--log-level",
            "warning",
            "--cgroup-manager",
            "systemd",
            "--tmpdir",
            "/run/libpod",
            "--runtime",
            "crun",
            "--storage-driver",
            "overlay",
            "--storage-opt",
            "overlay.mountopt=nodev,metacopy=on",
            "--events-backend",
            "journald",
            "container",
            "cleanup",
            "--rm",
            "d806cb392902d692d30b11372c5aa6a92acbbdffbeaf96923b7b9948efe7dce6"
        ],
        "Namespace": "",
        "IsInfra": false,
        "Config": {
            "Hostname": "d806cb392902",
            "Domainname": "",
            "User": "user",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/webots:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "TERM=xterm",
                "container=podman",
                "SHELL=/bin/bash",
                "ROS_DISTRO=melodic",
                "LD_LIBRARY_PATH=/usr/local/webots/lib/controller",
                "LANG=C.UTF-8",
                "WEBOTS_WORLD_FILE_PATH=/usr/local/webots/projects/samples/tutorials/worlds/my_first_simulation.wbt",
                "strip=false",
                "YARN_VERSION=1.22.5",
                "THEIA_DEFAULT_PLUGINS=local-dir:/opt/theia/plugins",
                "QTWEBENGINE_DISABLE_SANDBOX=1",
                "DEBIAN_FRONTEND=noninteractive",
                "hhh=888",
                "NODE_VERSION=12.18.3",
                "THEIA_WORK_DIR=/home/user/catkin_ws",
                "WEBOTS_HOME=/usr/local/webots",
                "LC_ALL=C.UTF-8",
                "HOME=/home/user",
                "HOSTNAME=d806cb392902"
            ],
            "Cmd": null,
            "Image": "docker.io/wzpoo/rtw:latest",
            "Volumes": null,
            "WorkingDir": "/home/user/catkin_ws",
            "Entrypoint": "setup.sh",
            "OnBuild": null,
            "Labels": null,
            "Annotations": {
                "io.container.manager": "libpod",
                "io.kubernetes.cri-o.Created": "2021-08-09T19:26:48.282103785+08:00",
                "io.podman.annotations.autoremove": "TRUE",
                "io.podman.annotations.init": "FALSE",
                "io.podman.annotations.privileged": "FALSE",
                "io.podman.annotations.publish-all": "FALSE",
                "org.opencontainers.image.stopSignal": "15"
            },
            "StopSignal": 15,
            "Umask": "0000"
        },
        "HostConfig": {
            "Binds": [
                "/home/workstation/Documents/test/math/section1/3:/home:rw,rprivate,rbind"
            ],
            "CgroupManager": "systemd",
            "CgroupMode": "host",
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "k8s-file",
                "Config": null,
                "Path": "/var/lib/containers/storage/overlay-containers/d806cb392902d692d30b11372c5aa6a92acbbdffbeaf96923b7b9948efe7dce6/userdata/ctr.log",
                "Tag": "",
                "Size": "0B"
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "3000/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "10000"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "on-failure",
                "MaximumRetryCount": 10
            },
            "AutoRemove": true,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [],
            "CapDrop": [
                "CAP_MKNOD",
                "CAP_NET_RAW",
                "CAP_AUDIT_WRITE"
            ],
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": [],
            "GroupAdd": [],
            "IpcMode": "private",
            "Cgroup": "",
            "Cgroups": "default",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "private",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [],
            "Tmpfs": {},
            "UTSMode": "private",
            "UsernsMode": "",
            "ShmSize": 65536000,
            "Runtime": "oci",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": 0,
            "OomKillDisable": false,
            "PidsLimit": 2048,
            "Ulimits": [
                {
                    "Name": "RLIMIT_NOFILE",
                    "Soft": 1048576,
                    "Hard": 1048576
                },
                {
                    "Name": "RLIMIT_NPROC",
                    "Soft": 131072,
                    "Hard": 131072
                }
            ],
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "CgroupConf": null
        }
    }
]

**Comment by wzpoo** [comment]
@Luap99  .In the podman reference, it said that if I want to edit 'portmapping' parameter ,I also should to edit parameter 'netns'.'netns' has two parameter: 'nsmode' and 'value',but I don't know how to write it. So I don't input this parameter. Is the question here? If there is problem, can you tell me how to write parameter 'netns'? I want to use mode 'bridge'.

**Comment by Luap99** [comment]
```
"Ports": {
"3000/tcp": [
{
"HostIp": "0.0.0.0",
"HostPort": "10000"
}
]
```
Somehow port 10000 got forwarded into the container. I cannot reproduce this problem. Could you try a more recent version, e.g. pomdan 3.2.3.

**Comment by Luap99** [comment]
I do not think you have to set the nsmode. The default one is bridge and it shows bridge in your inspect output.

**Comment by wzpoo** [comment]
My system is ubuntu18.04, so I use this podman version. If I use the command 'podman run -p 0.0.0.0:3000:10000 docker.io/wzpoo/rtw:latest, it work well. I want to use the podman api achieve the same result.

**Comment by wzpoo** [comment]
![image](https://user-images.githubusercontent.com/87136343/128702204-99954594-ff67-4142-a3d6-5ac8b89606be.png)
This is my brower response.

**Comment by Luap99** [comment]
Compare the podman inspect output from a container created via api and cli and check if you see any difference. Also start the podman service with --log-level debug and look for errors.

**Comment by Luap99** [comment]
@wzpoo  Were you able to make it work?

**Comment by wzpoo** [comment]
> @wzpoo Were you able to make it work?

Yes, I take your suggestion and try a new version '3.2.3'. It works.
