### ISSUE TITLE
Multi-arch image build is pushing too many tags

### ISSUE THREAD

**Issue by bcrochet** [containers/podman#11162]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The multi-arch image build is updating the most current versioned tag, as well as the "latest" tag. According to the README, once a versioned tag is cut, it should not be updated. Currently though, the v3.2.3 tag is being updated every time the latest tag is built.

**Steps to reproduce the issue:**

1. No manual steps. The automation is doing the push. Just have to look at quay.io/podman/stable, and see that latest and v3.2.3 are the same.

**Describe the results you received:**

v3.2.3 keeps getting updated.

**Describe the results you expected:**

v3.2.3 should not be updated.

**Additional information you deem important (e.g. issue happens only occasionally):**

From the README.md in contrib/podmanimage:

quay.io/containers/podman:<version> and quay.io/podman/stable:<version> - These images are built when a new Podman version becomes available in Fedora. These images are intended to be unchanging and stable, they will never be updated by automation once they've been pushed. For build details, please see the configuration file.

**Comment by mheon** [comment]
@TomSweeneyRedHat PTAL

**Comment by rhatdan** [comment]
Maybe the documentation needs to be updated.  But these images are not static, they will get updated with the latest software in Fedora in order to maintain their security.  What won't be updated is the version of Podman within the container.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @cevich Any progress on this?

**Comment by cevich** [comment]
I think this can be closed - "Fixed" in https://github.com/containers/podman/pull/11190  Users wanting stable images (for now) can reference them by tag + sha.

For the long-term, I'm re-architecting the automation that builds these (for many reasons).  Once that's in place and working, there will be an open window to more easily add "intelligence" into the process.  For example, to avoid pushing entirely new images unless a security-related update is included.  Or similar things like this.
