### ISSUE TITLE
--uidmap does not apply to mounted volumes

### ISSUE THREAD

**Issue by developedsoftware** [containers/podman#11182]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I have a RHEL UBI 8 init container (CMD /sbin/init) that is starting a SSH deamon. I understand that when I run rootless the ROOT user is mapped to my rootless user on the host. And writing files inside a volume as root inside the container get written to host as my rootless user (great!). 

However, I am now trying to log in over SSH to the container using a user other than root (user 1000 in the container)

I can SSH in perfectly fine, and browse around the system. However I am unable to write to any mounted volumes as these are owned by "root". I have tried to do uidmapping - which works inside the container. Files inside the container are no longer owned by root and I can edit them. 

However this behaviour does not cascade to mounted volumes. They continue to be owned by root even with a uidmapping. Is there anything than can be done? The mapping commands I have so far are as below. 

```
--uidmap 0:1000:1000 \
--gidmap 0:1000:1000 \
--uidmap 1000:1000:1 \
--gidmap 1000:1000:1 \
```

**Steps to reproduce the issue:**

1. Run a rootless container that starts /sbin/init ( registry.access.redhat.com/ubi8/ubi-init:latest )

2. Mount a volume from the host inside the container

3. Add the above UID mapping

4. Notice that the volumes remain owned by root inside the container and not the user that is being mapped

**Describe the results you received:**

Permission denied writing to a mapped volume

**Describe the results you expected:**

To be able to write to these volumes as a user other than root

**Additional information you deem important (e.g. issue happens only occasionally):**

You may suggest just running the container as root (as its running with the same permissions as the rootless user on the host). However, I require the container to be run as root (inside the container) so that systemd will start (fails if I try to run the /sbin/init with --user=1000). But I want to actually SSH in via the SSH deamon using a "not root user" inside the container whilst still having the systemd bus available to me (so I can run podman inside podman). WOAH - confused yet!?

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
podman version 3.0.2-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.0.1-7.module+el8.4.0+11311+9da8acfb.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

RHEL8.4 running on the host. SELINUX disabled.

**Comment by mheon** [comment]
Podman offers a `:U` option to recursively chown the volume mounted in to the appropriate permissions for the user and group in the container, which should take UID and GID maps into account. Would this suffice?

**Comment by developedsoftware** [comment]
`Error: invalid option type "U"`

What version is that option available?

**Comment by rhatdan** [comment]
I think Podman 3.1

**Comment by rhatdan** [comment]
Since the :U is available, I am going to close this issue.
