### ISSUE TITLE
Ignore files/directories while using podman container cp?

### ISSUE THREAD

**Issue by infiniteregrets** [containers/podman#11194]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
/kind feature

**Description**
While using podman container cp to copy files between a container and the host, I realized that there is no way to ignore a file or a directory. Having a cli argument just like `--cidfile=...` would be really nice in this case and might look like `--ignore=ignore.txt`

**Output of `podman version`:**

```
./podman --version
podman version 3.3.0-dev
```

**Comment by rhatdan** [comment]
It would probably be best to use .containerignore syntax for this (.dockerignore)

**Comment by infiniteregrets** [comment]
I asked this on irc, and afaik since there are no logs no one would have seen this. 

I am a bit confused regarding how a .containerignore/.dockerignore file is applied while building an image in buildah. I can see that when we create a new executor https://github.com/containers/buildah/blob/ea7127cf6983345bc0337855fc9fd8ed7b8403d8/imagebuildah/executor.go#L137 we do parse the ignore file and add it to the options with the excludes list which is later used with exec.Build(), but I don't get where is it being used to ignore the files.
https://github.com/containers/buildah/blob/ea7127cf6983345bc0337855fc9fd8ed7b8403d8/imagebuildah/executor.go#L494

My use case would be ignore files/directories while doing a podman container cp and the only way I can think of doing is to parse the source directory into a tree and then traverse to see if any of the elements are to be ignored or not while checking if they are a directory or a file or if the source is a file we just do a simple loop to check the same.

I am not sure if I am thinking this right, can someone tell me how could we approach this? Maybe @vrothberg can help me when they are back

**Comment by vrothberg** [comment]
This is something we had to implement in buildah/copier first but I am not yet convinced about the use case.  `cp(1)` doesn't support it and I am not sure it's worth the extra complexity.

Files could easily be filtered via `find` if needed which doesn't work during build.

**Comment by infiniteregrets** [comment]
@vrothberg When I was using podman cp, I had a directory with some python files and a config.py file. I just didn't want to copy that file from the directory and I couldn't figure how to do that with podman. 

If you think this might not be as useful, then let me know i'll close this issue
