### ISSUE TITLE
podman run --cgroups=disabled: missing "supervisor"

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#11191]
One of the integration tests is flaking when reading `/proc/NNN/cgroup`:
```console
$ podman run --name testctr -d --cgroups=disabled quay.io/libpod/alpine:latest top
$ podman inspect testctr
...
$ (read /proc/X/cgroup)
       Expected
               <string>: 0::/system.slice/google-startup-scripts.service
           to equal
               <string>: 0::/system.slice/google-startup-scripts.service/supervisor
```
### Podman run [It] podman run with cgroups=disabled runs without cgroups
* fedora-33 : int podman fedora-33 root host
  * PR #11176
    * [08-10 05:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5314172922626048/html/int-podman-fedora-33-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--1)
  * PR #11134
    * [08-09 13:54](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6432032650690560/html/int-podman-fedora-33-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--1)
  * PR #10970
    * [07-20 12:27](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5111577587220480/html/int-podman-fedora-33-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--1)
  * PR #10583
    * [06-23 13:43](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4509553250271232/html/int-podman-fedora-33-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--1)
* fedora-34 : int podman fedora-34 root host
  * PR #11176
    * [08-10 05:58](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5877122876047360/html/int-podman-fedora-34-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--1)
  * PR #11101
    * [08-02 18:00](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5660320845791232/html/int-podman-fedora-34-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--1)
  * PR #10860
    * [07-05 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5611599042969600/html/int-podman-fedora-34-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--1)
  * PR #10688
    * [06-16 20:43](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6375706138509312/html/int-podman-fedora-34-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--1)
  * PR #10679
    * [06-14 15:48](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6229905521246208/html/int-podman-fedora-34-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--1)
* ubuntu-2104 : int podman ubuntu-2104 root host
  * PR #10992
    * [07-20 09:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5339356614361088/html/int-podman-ubuntu-2104-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--1)
  * PR #10383
    * [05-26 17:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6675874742272000/html/int-podman-ubuntu-2104-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--1)

**Comment by rhatdan** [comment]
Can we change the test to be less specific?  I /supervisor critical to the test?

**Comment by edsantiago** [comment]
The test itself doesn't have any `supervisor` in it; it's just comparing `/proc/self/cgroup` to `/proc/CONTAINERPID/cgroup`. (I think). git blames @mheon in #3581. Matt, how's your memory?

**Comment by mheon** [comment]
This test verifies that the container is running as the same cgroup that launched it if we run with `--cgroups=disabled`. An exact match is important as such. The test itself is sound. I can think of no obvious reason why it would not be failing.

**Comment by rhatdan** [comment]
@giuseppe thoughts?

**Comment by giuseppe** [comment]
we create the `/supervisor` sub-cgroup only when the cgroups mode is set to `--cgroups=split`:

```
	if ctr.config.CgroupsMode == cgroupSplit {
		if err := utils.MoveUnderCgroupSubtree("supervisor"); err != nil {
			return err
		}
	}
```

I don't see any other way of ending up under `/supervisor`.

One thing we could try to make the test more robust is to avoid going through its PID to read the cgroup with `--cgroupns=host` as:

```
podman run --name testctr --rm  --cgroupns=host --cgroups=disabled quay.io/libpod/alpine:latest cat /proc/self/cgroup
```

**Comment by rhatdan** [comment]
@giuseppe @edsantiago @mheon any movement on this issue?

**Comment by giuseppe** [comment]
opened a PR to simplify the test: https://github.com/containers/podman/pull/11561

**Comment by edsantiago** [comment]
#11561 has merged. Closing, with fingers crossed.

**Comment by edsantiago** [comment]
This is happening again, sort of, except now it's the opposite:
```
Expected
      <string>: 0::/system.slice/google-startup-scripts.service/supervisor
  to equal
      <string>: 0::/system.slice/google-startup-scripts.service
```
(it used to be the other way around).

### Podman run [It] podman run with cgroups=disabled runs without cgroups
* fedora-34 : int podman fedora-34 root host
  * PR #11834
    * [10-01 16:37](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6739354816086016/html/int-podman-fedora-34-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--1)
    * [10-01 16:37](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6739354816086016/html/int-podman-fedora-34-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--2)
    * [10-01 16:37](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6739354816086016/html/int-podman-fedora-34-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--3)
  * PR #11609
    * [09-24 13:53](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5317318256361472/html/int-podman-fedora-34-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--1)
    * [09-24 12:53](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6111071514656768/html/int-podman-fedora-34-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--1)
    * [09-24 12:53](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6111071514656768/html/int-podman-fedora-34-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--2)
    * [09-24 11:48](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6557297460641792/html/int-podman-fedora-34-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--1)
    * [09-24 11:48](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6557297460641792/html/int-podman-fedora-34-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--2)
* ubuntu-2104 : int podman ubuntu-2104 root host
  * PR #11655
    * [09-20 09:14](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4541307474411520/html/int-podman-ubuntu-2104-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--1)

**Comment by edsantiago** [comment]
No, not since the 10-01 instances reported above. Okay, I'll close again - thank you!

**Comment by cevich** [comment]
@giuseppe [It reproduced again with your new name (log)](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6513868798164992/html/int-podman-ubuntu-2104-root-host.log.html#t--podman-run-with-cgroups-disabled-runs-without-cgroups--1)

```
         • Failure [1.763 seconds]
         Podman run
         /var/tmp/go/src/github.com/containers/podman/test/e2e/run_test.go:25
           podman run with cgroups=disabled runs without cgroups [It]
           /var/tmp/go/src/github.com/containers/podman/test/e2e/run_test.go:1396
         
           Expected
               <string>: 0::/system.slice/google-startup-scripts.service/runtime
           to equal
               <string>: 0::/system.slice/google-startup-scripts.service
```

So that means it cannot be systemd, it must be a podman or crun bug, eh?

**Comment by giuseppe** [comment]
yeah, it seems it is all our fault :/

**Comment by giuseppe** [comment]
another attempt:https://github.com/containers/podman/pull/12162

**Comment by cevich** [comment]
> yeah, it seems it is all our fault :/

Proof positive that no matter how hard we try, we're still human.  But a positive way of looking at it is: At least we don't need to patch systemd + wait for a new version to be released + incorporate that into our VMs :grin:
