### ISSUE TITLE
Install particular version 

### ISSUE THREAD

**Issue by Srirammkm** [containers/podman#11237]
I want to install podman v1.5.0
How can i install a particular podman version?

**Comment by vrothberg** [comment]
Thanks for reaching out!  You can compile it from source.  To get the source you can clone the Git repository or download them directly from the release page (https://github.com/containers/podman/releases/tag/v1.5.0).

Note that v1.5.0 is two years old and not supported upstream anymore.  I recommend running the latest version of Podman.

**Comment by rhatdan** [comment]
Also Podman requires lots of other applications like runc, crun, containers-common, fuse-overlay. slirp4netns...  If these are not matching, bad things can also happen.

**Comment by TomSweeneyRedHat** [comment]
Or you could potentially use the container image that we have on quay.io   quay.io/podman/stable:v1.5.0

However, that's old enough that it might be a bit wonky....
