### ISSUE TITLE
rootfull Podman building is significantly slower than Docker

### ISSUE THREAD

**Issue by kurt-google** [containers/podman#11236]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Image creation in docker is significantly slower. In my minimal tests it appears to be related to either excessive layer compression or just slower compression speeds in podman. But that may be me mistaking how podman works. This issue has been discussed somewhat it seems on the tracker but usually in rootless podman to docker, in this case both are rootfull and running on overlayfs so I would expect similar performance.

It may be important to state that I am on a nvme drive with 1GB/s or so rw bandwidth. So I know that using uncompressed images is going to be many many times faster than waiting for gzip to complete and I want podman to fully utilize this system.

It takes about 15s to `sha256sum` the 4GB iso, and everything else in the dockerfile runs at about 1GB/s so it seems this simple image would optimally take maybe a minute or two based how much data needs to get hashed in the layers (maybe someone can provide a better basis for estimating work done). So docker which has to pull the data across the socket first seems to do close enough to optimally assuming it needs to hash the whole iso/tar a couple times but podman is twice as slow for unknown reasons.

Im happy to provide more information but I think the reproduction steps should be sufficient. In my real docker file with a few more layers `podman --compress=false`, `podman --compress=true`, and `docker --compress=true` all take about the same time but `docker --compress=false` (the default) takes less than half the time of `podman` similar to the reproduction case.

**Steps to reproduce the issue:**

Get the debian 11 install dvd for testing.
`wget https://cdimage.debian.org/debian-cd/current/amd64/iso-dvd/debian-11.0.0-amd64-DVD-1.iso`

Make a trivial dockerfile

```
cat <<EOF > Dockerfile
from docker.io/debian:bullseye-slim

copy debian.iso /debian.iso
run tar cvf debian.iso.tar /debian.iso
EOF
```

**Describe the results you received:**

```
time sudo podman --compress=true --no-cache
real    6m28.711s

(We saved some time in this example. In a more complicated build that prompted this bug report no time was gained from compress=false).
time sudo podman --compress=false --no-cache
real    4m46.139s

time docker --compress=false --no-cache
real    2m0.426s

(Docker spends almost all the time compressing the input, in fact it spends nearly 6m doing so, so it the build part is still about 2m. In a more complicated build the speed of the rest of the docker pipeline makes it the same as podman --compress=true).
time docker --compress=true --no-cache
real    8m7.935s
```

**Describe the results you expected:**
I would expect podman to run at the same speed as docker. Its unclear to me if docker is compressing intermediate layers and/or final images or not, but I would expect podman --compress=false to be at least as docker when both are running as root with overlayfs.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
podman version 3.0.1
podman version 3.2.3
No significant differences between the two versions tested.

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.6
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 12
  distribution:
    distribution: debian
    version: rodete
  eventLogger: journald
  hostname: testinghouse
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.40-1rodete2-amd64
  linkmode: dynamic
  memFree: 10360897536
  memTotal: 67014131712
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 68026101760
  swapTotal: 68354568192
  uptime: 329h 32m 52.75s (Approximately 13.71 days)
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 48
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 0
  BuiltTime: Wed Dec 31 16:00:00 1969
  GitCommit: ""
  GoVersion: go1.15.9
  OsArch: linux/amd64
  Version: 3.0.1
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine

**Comment by rhatdan** [comment]
@nalind @mtrmac WDYT?

**Comment by kurt-google** [comment]
I threw the reproduction case into pprof and it seems I was probably mistaken, about 3 of the 4 minutes are actually attributed to sha256sum. So its probably a case of excessive hashing and not compression occuring where it shouldnt.

Example patch for profiling

```diff
diff --git a/cmd/podman/images/build.go b/cmd/podman/images/build.go
index 04fdeab0a..d7cae004b 100644
--- a/cmd/podman/images/build.go
+++ b/cmd/podman/images/build.go
@@ -3,8 +3,10 @@ package images
 import (
 	"io"
 	"io/ioutil"
+	"log"
 	"os"
 	"path/filepath"
+	"runtime/pprof"
 	"strings"
 	"time"
 
@@ -25,6 +27,8 @@ import (
 	"github.com/spf13/cobra"
 )
 
+var cpuprofile string
+
 // buildFlagsWrapper are local to cmd/ as the build code is using Buildah-internal
 // types.  Hence, after parsing, we are converting buildFlagsWrapper to the entities'
 // options which essentially embed the Buildah types.
@@ -101,6 +105,7 @@ func buildFlags(cmd *cobra.Command) {
 
 	// Podman flags
 	flags.BoolVarP(&buildOpts.SquashAll, "squash-all", "", false, "Squash all layers into a single layer")
+	flags.StringVarP(&cpuprofile, "cpuprofile", "", "", "write cpu profile to file")
 
 	// Bud flags
 	budFlags := buildahCLI.GetBudFlags(&buildOpts.BudResults)
@@ -182,6 +187,15 @@ func build(cmd *cobra.Command, args []string) error {
 		return errors.New("cannot specify --squash, --squash-all and --layers options together")
 	}
 
+	if cpuprofile != "" {
+		f, err := os.Create(cpuprofile)
+		if err != nil {
+			log.Fatal(err)
+		}
+		pprof.StartCPUProfile(f)
+		defer pprof.StopCPUProfile()
+	}
+
 	// Extract container files from the CLI (i.e., --file/-f) first.
 	var containerFiles []string
 	for _, f := range buildOpts.File {
```

Run the same reproduction command but with `--cpuprofile=profile.pprof` and then view with `go tool pprof -web profile.pprof`

**Comment by kurt-google** [comment]
It there are multiple places where source hashes are computed even if the data is not being transformed (compressed).

* `containers/buildah/image.go:NewSourceImage` computes pre and post compression hashes. Even when data is not being compressed.
* `containers/storage/layers.go:ApplyDiff` does the same.
* `containers/image/v5/copy/copy.go:copyBlobFromStream` has a paranoid hash validation.

Making these noop during uncompressed image creation reduces the podman time to 3m. There is still one more minute to save potentially to reach Docker's speed but it is beyond my knowledge of the podman codebase at this point. I hope some of this can help find potential savings.

**Comment by mtrmac** [comment]
Thanks. A part of that sounds similar to https://github.com/containers/image/issues/1160 ; if there are more such situations in c/image, having them documented there would be helpful.

(Of course recording the redundancy and _fixing_ the redundancy are not the same; any help with the latter would also be welcome. Still, knowing what needs fixing is, by itself, valuable.)

**Comment by mtrmac** [comment]
https://github.com/containers/image/issues/1160 was now fixed, so the outstanding parts are probably Buildah (or redundancy in Buildah image creation vs. c/image copy, where I’m not yet quite sure we want to eliminate it).

**Comment by kurt-google** [comment]
One final thing which brings performance in-line with docker at least for the reproduction case (2m10s for podman vs 2m for docker).

Buildah.go:Builder.ContentDigester is used to hash all content from Containerfile ADD/COPY.
However these digests are only used when caching is enabled (buildah/imagebuildah/stage_executor.go:Execute checkForLayers=True) but are computed unconditionally in the ADD/COPY implementation (buildah/add.go:520)

However its worth noting that docker is not using this optimization its always hashing all the context (or appears to be) so there may be additional savings possible in podman still. It just happens that our build cannot rely on caching so we had --no-cache enabled.

**Comment by kurt-google** [comment]
With the commit changes, the current PR, and the above proposed change podman vs docker times for my real image is pretty competitive with docker at 12m6s and podman at 14m22s (down from 25m).

**Comment by rhatdan** [comment]
Now that this is merged, I will close this issue, reopen if I am mistaken.

**Comment by kurt-google** [comment]
Thats fine, but i would say that without improvements to `Buildah.go:Builder.ContentDigester` mentioned in my last comment things are still significantly slower.

**Comment by rhatdan** [comment]
Can you open an issue over there to fix that.
