### ISSUE TITLE
rhel9 + log-driver=journald : logs -f does not work

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#11255]
Without a magic flag, it errors out immediately:
```console
# podman run -d --log-driver=journald  --name c1 quay.io/libpod/testimage:20210610 sh -c 'echo a;sleep 10;echo b'
069c5b77b15de114d7315fa574a0da5a9f92b14d931c9c0000e6055ab5262df3
# podman logs -f c1
Error: using --follow with the journald --log-driver but without the journald --events-backend (file) is not supported
```
With the magic flag (which IMHO podman itself should figure out, not force the user to deal with it):
```console
# podman logs --events-backend=journald -f c1
b    <--- hangs here forever
```
Expected: `podman logs -f` to exit once the container stops. The hang happens with and without `--rm` (in `run`).

(Note also the missing 'a'; that is filed as #11253)

podman-3.3.0-0.18.module+el9beta+12201+6a03aeff.x86_64

**Comment by nalind** [comment]
My test system had `events_logger = "file"` set in `/usr/share/containers/containers.conf`, which is what I think is triggering the error you're seeing when attempting to use the `-f` flag.  I think we're going to want to go back to not explicitly setting it.

**Comment by mheon** [comment]
The container remembers what its log driver is. This sounds like a bug in `podman logs` which should not use the default driver, but instead whatever driver the container is using.

**Comment by rhatdan** [comment]
I can not get Ed's iniitial error to happen?

**Comment by nalind** [comment]
@rhatdan does your system have `event_logger = "file"` hardwired in through `/usr/share/containers/containers.conf`, as it seems to me it must have been on the system @edsantiago ws on?

**Comment by rhatdan** [comment]
Hardwired now, I was just changing the values in /etc/containers/containers.conf to try to get it to happen.

**Comment by rhatdan** [comment]
@edsantiago Could you check if this is still an issue.  I can not remember if we fixed it or not.

**Comment by edsantiago** [comment]
I don't really follow RHEL, but a very quick look at the most recent module build (12714, on 09-22) shows that the problem persists. All logs are in intranet, so I prefer not to post links.
