### ISSUE TITLE
kubic repo changed default dependencies for podman from crun to run runc

### ISSUE THREAD

**Issue by sappersd** [containers/podman#11257]
Kubic repo changed default dependencies for podman from crun to runc.
2 weeks ago installation of podman requared dependend - crun, after 11 aug it requered - runc.
I can install crun separatly, but without runc podman doesn't install now.
At the same time runc is default runtime for podman yet.

Is it relate with some plans to change default runtime for podman from crun to runc? Or may be something else?
Just now I get error with runc "Error: container_linux.go:380: starting container process caused: error adding seccomp filter rule for syscall bdflush: permission denied: OCI permission denied".
With crun - all work well.

**Comment by Luap99** [comment]
@lsm5 PTAL

**Comment by sappersd** [comment]
additional info:
Centos8
repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/x86_64/
```
dnf -y module disable container-tools
dnf -y install 'dnf-command(copr)'
dnf -y install podman-3.2.* fuse-overlayfs skopeo
``

**Comment by lsm5** [comment]
Hi @sappersd . I recommend you switch to the default distro packages from CentOS or CentOS Stream.

The Ceph team reported a bunch of issues in their CI with the kubic packages after which we removed all kubic repo mentions for CentOS from the podman.io docs and we aren't really updating those packages anymore.

Sorry about that.

**Comment by sappersd** [comment]
@lsm5, thanks for the info! But where I can get podman-3.3 for CentOS8? Version 3.3.0 was released month ago.
