### ISSUE TITLE
--security-opt seccomp=unconfined --privileged | bash: /dev/null: Permission denied

### ISSUE THREAD

**Issue by cucosion** [containers/podman#11270]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Porting a old app to docker images, tested on docker for windows and it works fine on podman I have the below issue.

sudo podman create --name=somename --network container:othername --security-opt seccomp=unconfined --privileged mysuperimage:1.0
sudo podman start somename
sudo podman exec -it somename /bin/bash 
[root@a0c3e1fd8d5a app]# su - cli
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied
bash: /dev/null: Permission denied

**Steps to reproduce the issue:**

1. Create image instance with --priviledged

2. Try to switch to cli user that will trigger a certain script in background and i receive the bash: /dev/null: Permission denied

**Describe the results you received:**
Permission denied on podman on centos 8

**Describe the results you expected:**
To work as it works in docker on docker for windows.

**Additional information you deem important (e.g. issue happens only occasionally):**
I remember that before the podman update it was working with an image build on docker for windows. I presume that its the build on windows or the newer version of podman.

**Output of `podman version`:**

```
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.15.13
Built:        Sat Aug  7 20:21:48 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
[icucos@localhost podman-run-commands]$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.21.3
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.el8.16.3.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: '
  cpus: 28
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-305.10.2.el8_4.x86_64
  linkmode: dynamic
  memFree: 57874034688
  memTotal: 126452551680
  ociRuntime:
    name: crun
    package: crun-0.20.1-1.el8.3.6.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.20.1
      commit: 0d42f1109fd73548f44b01b3e84d04a279e99d2e
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-1.el8.33.2.x86_64
    version: |-
      slirp4netns version 1.1.9
      commit: 4e37ea557562e0d7a64dc636eff156f64927335e
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 0
  swapTotal: 0
  uptime: 290h 33m 42.83s (Approximately 12.08 days)
registries:
  dub1-eud-git01.aeroflex.corp:5000:
    Blocked: false
    Insecure: true
    Location: dub1-eud-git01.aeroflex.corp:5000
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: dub1-eud-git01.aeroflex.corp:5000
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/icucos/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.7-1.el8.2.3.x86_64
      Version: |-
        fusermount3 version: 3.2.1
        fuse-overlayfs: version 1.5
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/icucos/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 51
  runRoot: /run/user/1000/containers
  volumePath: /home/icucos/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.3
  Built: 1628356908
  BuiltTime: Sat Aug  7 20:21:48 2021
  GitCommit: ""
  GoVersion: go1.15.13
  OsArch: linux/amd64
  Version: 3.2.3
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.2.3-1.el8.9.1.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

eSXI VM

**Comment by mheon** [comment]
FYI, `--privileged` implies `--security-opt seccomp=unconfined`; there's no need to use both.

Can you provide a reproducer? It's very difficult to identify what's going on unless we have can replicate the error.

**Comment by cucosion** [comment]
Found the issue, during the build i didnt noticed that i was receiving the 

mknod: `/opt/cli/jail/dev/null': Operation not permitted
mknod: `/opt/cli/jail/dev/pts/ptmx': Operation not permitted
mknod: `/opt/cli/jail/dev/random': Operation not permitted
mknod: `/opt/cli/jail/dev/tty': Operation not permitted
mknod: `/opt/cli/jail/dev/urandom': Operation not permitted
mknod: `/opt/cli/jail/dev/zero': Operation not permitted

by building the image with CAP_MKNOD  it worked

```
podman build --cap-add=CAP_MKNOD -t 
```

**Comment by rhatdan** [comment]
Yes we default to a tighter security then Docker, we don't allow CAP_MKNOD by default.
