### ISSUE TITLE
Failed to add podman to systemd sandbox cgroup

### ISSUE THREAD

**Issue by smijolovic** [containers/podman#11284]
Ubuntu 20.04.2 with podman 3.2.3
when running the command "podman --log-level debug info"

There is a debug error that always causes the system to pause.
DEBU[0240] Failed to add podman to systemd sandbox cgroup: Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=120000ms).

chaasmadmin@maestro-puppyfood:~$ echo $XDG_RUNTIME_DIR
/run/user/5000

Anytime I try to run a container, similar issues are present with the sandbox cgroup failure. For example when building k0s...
docker build --rm -t k0sbuild.docker-image.k0s -f build/Dockerfile .
STEP 1: FROM golang:1.16-alpine
STEP 2: RUN apk add --no-cache gcc musl-dev
error running container: error from /usr/bin/crun creating container for [/bin/sh -c apk add --no-cache gcc musl-dev]: sd-bus call: Connection timed out
: exit status 1
Error: error building at STEP "RUN apk add --no-cache gcc musl-dev": error while running runtime: exit status 1
WARN[0480] Failed to add pause process to systemd sandbox cgroup: `<nil>`

Below is the full output of the podman info:

INFO[0000] podman filtering at log level debug          
DEBU[0000] Called info.PersistentPreRunE(podman --log-level debug info) 
DEBU[0000] overlay storage already configured with a mount-program 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf" 
DEBU[0000] overlay storage already configured with a mount-program 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /home/chaasmadmin/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/chaasmadmin/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/5000/containers     
DEBU[0000] Using static dir /home/chaasmadmin/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/5000/libpod/tmp      
DEBU[0000] Using volume path /home/chaasmadmin/.local/share/containers/storage/volumes 
DEBU[0000] overlay storage already configured with a mount-program 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] overlay: mount_program=/usr/bin/fuse-overlayfs 
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
DEBU[0000] configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] Using OCI runtime "/usr/bin/crun"            
DEBU[0000] Default CNI network name podman is unchangeable 
INFO[0000] Setting parallel job count to 13             
DEBU[0240] Failed to add podman to systemd sandbox cgroup: Failed to activate service 'org.freedesktop.systemd1': timed out (service_start_timeout=120000ms) 
DEBU[0240] Loading registries configuration "/etc/containers/registries.conf" 
DEBU[0240] Loading registries configuration "/etc/containers/registries.conf.d/shortnames.conf" 
host:
  arch: amd64
  buildahVersion: 1.21.3
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon-chaasm: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: 65fad4bfcb250df0435ea668017e643e7f462155'
  cpus: 4
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: maestro-puppyfood
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 5000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 5000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.4.0-81-generic
  linkmode: dynamic
  memFree: 363577344
  memTotal: 12550541312
  ociRuntime:
    name: crun
    package: 'crun-chaasm: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.21
      commit: c4c3cdf2ce408ed44a9e027c618473e6485c635b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/5000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 0.4.3
      commit: 2244b9b6461afeccad1678fac3d6e478c28b4ad6
  swapFree: 8553594880
  swapTotal: 8589930496
  uptime: 88h 12m 25.94s (Approximately 3.67 days)
registries:
  search:
  - docker.io
store:
  configFile: /home/chaasmadmin/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.9.0
        fuse-overlayfs: version 0.7.6
        FUSE library version 3.9.0
        using FUSE kernel interface version 7.31
  graphRoot: /home/chaasmadmin/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/user/5000/containers
  volumePath: /home/chaasmadmin/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.3
  Built: 1609357106
  BuiltTime: Wed Dec 30 19:38:26 2020
  GitCommit: 1e6fd46e91b21342f9454cf8105a92b90e398c52-dirty
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.2.3

**Comment by mheon** [comment]
@giuseppe PTAL

**Comment by flouthoc** [comment]
@smijolovic it seems like systemd session is not valid , does `systemd-loginctl list-sessions` lists a session for your user `5000`. Could you try `systemctl restart systemd-logind` and run podman info again.

**Comment by smijolovic** [comment]
chaasmadmin@maestro-puppyfood:~$ loginctl list-sessions
SESSION  UID USER        SEAT TTY  
      1 5000 chaasmadmin      pts/0
      3 5000 chaasmadmin      pts/1

2 sessions listed.

Same issue persists

**Comment by flouthoc** [comment]
@smijolovic could you paste output of `busctl` please.

**Comment by smijolovic** [comment]
org.freedesktop.systemd1          1 systemd         root            :1.0          init.scope                  -       -

**Comment by flouthoc** [comment]
@smijolovic I am not sure why is it not active so `org.freedesktop.systemd1` needs to be activatable.

What does `systemctl status org.freedesktop.systemd1` says ?

Some common knows issues are

* Low memory or swap. Check if you are running low on memory. Clean up process if its low and then try `sudo systemctl daemon-reexec`
* Try restarting dbus `systemctl start dbus.service`
* This i am not sure about but found somewhere on web. `sudo kill 1`.
* Last resort if you could `reboot`.

**Comment by smijolovic** [comment]
What's really strange is that my other system is working...and shows the same systemd1 result as this one, so I'm pretty sure that is not the issue. One has selinux permissive and the other is enforcing.  When I run setenforce 0 to the second system, it still doesn't work....so I'm stumped on why they are behaving differently.

**Comment by smijolovic** [comment]
I will close this issue for now - because it is an selinux related issue - once set to permissive at boot - podman and k0s build.

More work to be done on the policies to address this.  Thank you for all of your help!

**Comment by smijolovic** [comment]
I see the following with ausearch, but audit2allow does not supply a policy to address the issue:

time->Fri Aug 20 19:19:09 2021
node=maestro-puppyfood type=PROCTITLE msg=audit(1629487149.823:1023368): proctitle=2F6C69622F73797374656D642F73797374656D64002D2D75736572
node=maestro-puppyfood type=PATH msg=audit(1629487149.823:1023368): item=0 name="/proc/1800/cgroup" nametype=UNKNOWN cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
node=maestro-puppyfood type=SYSCALL msg=audit(1629487149.823:1023368): arch=c000003e syscall=257 success=no exit=-13 a0=ffffff9c a1=7ffcc8c99110 a2=80000 a3=0 items=1 ppid=1 pid=1719 auid=5000 uid=5000 gid=5000 euid=5000 suid=5000 fsuid=5000 egid=5000 sgid=5000 fsgid=5000 tty=(none) ses=2 comm="systemd" exe="/usr/lib/systemd/systemd" subj=sysadm_u:sysadm_r:sysadm_systemd_t:s0-s0:c0.c1023 key="perm_access"
node=maestro-puppyfood type=AVC msg=audit(1629487149.823:1023368): avc:  denied  { search } for  pid=1719 comm="systemd" name="1800" dev="proc" ino=1460330 scontext=sysadm_u:sysadm_r:sysadm_systemd_t:s0-s0:c0.c1023 tcontext=sysadm_u:sysadm_r:sysadm_dbusd_t:s0-s0:c0.c1023 tclass=dir permissive=0

**Comment by rhatdan** [comment]
sysadmin_systemd_t is not defined in default policy on Fedora,  so this looks like it is custom policy and outside of Podmans control.

**Comment by flouthoc** [comment]
Host policy cannot be changed by podman. Closing this as `WONTFIX` please reopen if you feel issue is with podman.
