### ISSUE TITLE
Cannot resolve own hostname IP address for rootless container

### ISSUE THREAD

**Issue by gvenzl** [containers/podman#11302]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I have a strange issue where my rootless containers are not able to resolve their own container hostnames to IP addresses. That, in turn, causes programs that try to look up the container IP address via hostname to fail.

**Steps to reproduce the issue:**

1. Start a new container:  `podman run --name test -ti centos:8 bash`

2. Install `nslookup` inside the container: `dnf install bind-utils`

3. Run `nslookup $(hostname)` to resolve the container hostname to IP address:
```
[root@bb7ea5c6fe3e /]# nslookup $(hostname)
Server:		10.0.2.3
Address:	10.0.2.3#53

** server can't find bb7ea5c6fe3e: NXDOMAIN
```

**Describe the results you received:**
The results of `nslookup` show that it cannot resolve, in this case of the currently running container, hostname `bb7ea5c6fe3e` to its IP address.

**Describe the results you expected:**
I would expect `nslookup` to resolve the hostname to the container IP address, in the current running container `10.0.2.100`:
```
[root@bb7ea5c6fe3e /]# ifconfig -a
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 4  bytes 156 (156.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 4  bytes 156 (156.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tap0: flags=67<UP,BROADCAST,RUNNING>  mtu 65520
        inet 10.0.2.100  netmask 255.255.255.0  broadcast 10.0.2.255
        inet6 fe80::c47f:21ff:fe45:9d44  prefixlen 64  scopeid 0x20<link>
        ether c6:7f:21:45:9d:44  txqueuelen 1000  (Ethernet)
        RX packets 3060  bytes 39102707 (37.2 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2085  bytes 121726 (118.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Additional information you deem important (e.g. issue happens only occasionally):**
`/etc/resolv.conf` does have the `slirp4netns` nameserver correctly configured (as is also apparent by the `nslookup` output):
```
[root@bb7ea5c6fe3e /]# cat /etc/resolv.conf
nameserver 10.0.2.3
nameserver 192.168.11.1
nameserver 1.1.1.1
```
**Output of `podman version`:**

```
$ podman version
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.15.14
Built:        Tue Aug 10 13:55:16 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.21.3
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.module_el8.4.0+886+c9a8d9ad.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 97bba1e91aaab5be2e93bacd34ec4e66655a02ae'
  cpus: 2
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-305.12.1.el8_4.x86_64
  linkmode: dynamic
  memFree: 529469440
  memTotal: 4120113152
  ociRuntime:
    name: runc
    package: runc-1.0.0-74.rc95.module_el8.4.0+886+c9a8d9ad.x86_64
    path: /usr/bin/runc
    version: |-
      runc version spec: 1.0.2-dev
      go: go1.15.14
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module_el8.4.0+641+6116a774.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 0
  swapTotal: 0
  uptime: 1h 15m 15.12s (Approximately 0.04 days)
registries:
  search:
  - docker.io
store:
  configFile: /home/gvenzl/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.6-1.module_el8.4.0+886+c9a8d9ad.x86_64
      Version: |-
        fusermount3 version: 3.2.1
        fuse-overlayfs: version 1.6
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/gvenzl/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 8
  runRoot: /run/user/1000/containers
  volumePath: /home/gvenzl/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.3
  Built: 1628628916
  BuiltTime: Tue Aug 10 13:55:16 2021
  GitCommit: ""
  GoVersion: go1.15.14
  OsArch: linux/amd64
  Version: 3.2.3
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ rpm -q podman
podman-3.2.3-0.10.module_el8.4.0+886+c9a8d9ad.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm running Podman on CentOS Linux release 8.4.2105 inside a VirtualBox VM, Version 6.1.22 r144080 (Qt5.6.3)

**Comment by Luap99** [comment]
The hostname is written to /etc/hosts so no dns lookup is used. `nslookup` directly query's the dns server without checking /etc/hosts first so you do not get a valid result. If you use something like `ping hostname` it should work.

**Comment by gvenzl** [comment]
Hi @Luap99,

First of all, thank you so much for taking the time to look into this issue!

I believe there was a misunderstanding.
My issue is not so much how I myself can determine the IP address via the hostname but what to do when a program tries to determine the IP address via a DNS lookup on the container's hostname.

In my case, I'm containerizing Oracle Database XE that itself tries to determine the IP address of the host and fails.
Unfortunately, there is little I can do to change that behavior.
What puzzles me is that this used to work and I successfully [built images of it and ran containers](https://hub.docker.com/r/gvenzl/oracle-xe) in the past.
Yesterday evening, however, I updated my CentOS 8 VM and now I'm running into this issue, although I have nothing changed the [built scripts](https://github.com/gvenzl/oci-oracle-xe) or anything else.

What I cannot say is whether a DNS lookup used to work or never worked, but somehow in the past the hostname could be resolved to some IP address, it seems.
While researching yesterday, I found that `slirp4netns` includes an `--disable-host-loopback` option, but not knowing this technology at all, I can just guess that maybe in the past this flag was not set and the hostname resolved to 127.0.0.1:
```
[gvenzl@localhost ~]$ ps -ef | grep slirp
gvenzl      1817    1800  0 11:51 pts/0    00:00:00 /usr/bin/slirp4netns --disable-host-loopback --mtu=65520 --enable-sandbox --enable-seccomp -c -e 3 -r 4 --netns-type=path /run/user/1000/netns/cni-4bf2bc7f-93af-87aa-e055-55d8dc02dfe0 tap0
```

You are correct, that `/etc/hosts` is amended (by or for `slirp4netns`?)  to contain the hostname:
```
[root@75e1d4f09734 /]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
# used by slirp4netns
10.0.2.100	75e1d4f09734 test
10.0.2.2 host.containers.internal
```

But, of course, as you said, that doesn't help with a DNS lookup which is ignoring this file.
However, likewise the `/etc/resolv.conf` is amended to also include the nameserver IP address also of `slirp4netns`, I believe:
```
[root@75e1d4f09734 /]# cat /etc/resolv.conf
nameserver 10.0.2.3
nameserver 192.168.11.1
nameserver 1.1.1.1
```
I was wondering whether 10.0.2.3 shouldn't be able to resolve the hostname of the container to 10.0.2.100, but again, I'm not an expert in this technology.

So I'm left to wonder, how would any program that wants to resolve its own IP address via the hostname work inside a Podman container?
Obviously, IP addresses are somewhat useless inside a container, I get that.
But I cannot change the fact that the software fails due to the inability to resolve the IP address.

For me, it would be even fine if it could get resolved to 127.0.0.1, as said, the IP address carries little meaning in this scenario.
But after spending my Friday night on this and 5 hours off googling and trial and error, I'm still not able to get around this.
Which is the reason why I left this issue here, any help that you or the team could offer is highly appreciated!
Should `10.0.2.3` be able to resolve the container hostname to its IP address and did this work in the past and there is a regression?
Or is there some configuration change that happened, perhaps that `--disable-host-loopback` was added for `slirp4netns` and if so, why, and what's the workaround for it?
Or did I miss some configuration steps or anything else?

As said, any help would be highly, highly appreciated!

**Comment by mheon** [comment]
Wait - is Oracle actively ignoring `/etc/hosts`? That seems... unusual? I've genuinely never heard of an application that deliberately ignores `/etc/hosts` (aside from dedicated DNS utilities like `dig`). Is there no way to opt out of this? Because this genuinely does not seem like sane behavior on the part of the database.

The `dnsname` plugin ought to take care of this if the container is joined to a CNI network, but `dnsname` defaults its entries to container name, not hostname (you could add an alias manually, or ensure the two match, to correct this?).

**Comment by Luap99** [comment]
AFAIK you can configure this via `/etc/nsswitch.conf`. It should contain a line like this `hosts:      files myhostname mdns4_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns`. It must contain `files` otherwise `/etc/hosts` is not used.

**Comment by Luap99** [comment]
The `10.0.2.3` nameserver is just a proxy to your real host nameserver and `--disable-host-loopback` shouldn't matter in this case.

**Comment by gvenzl** [comment]
Hi @mheon, thanks for your help on this as well!

In this particular case, it's actually not so much the database software itself but a Java-based configuration tool that tries to determine the public-facing IP for the database. From what I can tell, it uses some internal Java routine to determine the IP address. Now whether that's supposed to use `/etc/hosts` or not, I cannot tell, only that it apparently isn't using `/etc/hosts` :)

Not using the configuration tools is not easy either as it is part of the installation process for the database (so it fails to install the DB while building the image).
What I can say is that this used to work before, which makes me now think more and more that perhaps some configuration got lost on my environment.

@Luap99, I just checked `/etc/nsswitch.conf` and have this inside my container:
```
...
# Installation instructions:
#
# To use 'db', install the appropriate package(s) (provide 'makedb' and
# libnss_db.so.*), and place the 'db' in front of 'files' for entries
# you want to be looked up first in the databases, like this:
#
# passwd:    db files
# shadow:    db files
# group:     db files

# In order of likelihood of use to accelerate lookup.
passwd:      sss files systemd
shadow:     files sss
group:       sss files systemd
hosts:      files dns myhostname
services:   files sss
netgroup:   sss
automount:  files sss

aliases:    files
ethers:     files
gshadow:    files
# Allow initgroups to default to the setting for group.
# initgroups: files
networks:   files dns
protocols:  files
publickey:  files
rpc:        files

[root@eeef9f605b2e /]# nslookup `hostname`
Server:		10.0.2.3
Address:	10.0.2.3#53

** server can't find eeef9f605b2e: NXDOMAIN
```

So this does look correct, however, could it be that `myhostname` should be before `dns`?
I did edit the file on the host to reflect this, but the file inside a new container did unfortunately not inherit that update.

**Comment by Luap99** [comment]
You cannot test with `nslookup`. This is a **dns** only tool and does not read /etc/hosts. Use `ping` or `curl` to make sure the glib resolver is used.

**Comment by gvenzl** [comment]
Hi @Luap99,

Yes, I can confirm that `ping` works just fine and I think it always has:

```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
# used by slirp4netns
10.0.2.100	8f03d93b6012 test
10.0.2.2 host.containers.internal
[root@8f03d93b6012 /]# ping `hostname`
PING 8f03d93b6012 (10.0.2.100) 56(84) bytes of data.
64 bytes from 8f03d93b6012 (10.0.2.100): icmp_seq=1 ttl=64 time=0.028 ms
64 bytes from 8f03d93b6012 (10.0.2.100): icmp_seq=2 ttl=64 time=0.030 ms
64 bytes from 8f03d93b6012 (10.0.2.100): icmp_seq=3 ttl=64 time=0.030 ms
```

In the meantime, I could also find out some more about the Java tool and what it is using to resolve the address.
It's issuing a call to [`InetAddress.getAllByName()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/InetAddress.html#getAllByName(java.lang.String)) to get all the addresses from the host.
I did a quick test run with the following little snippet:

```java
package com.gvenzl;

import java.net.InetAddress;

public class Main {

    public static void main(String[] args)throws Exception {
        InetAddress localhost = InetAddress.getLocalHost();
        String hostname = localhost.getHostName();
        System.out.println("Hostname: " + hostname);
        InetAddress address = InetAddress.getByName(hostname);
        System.out.println("Local address: " + address.getHostAddress());
        InetAddress[] addresses = InetAddress.getAllByName(hostname);
        for (InetAddress addr : addresses) {
            System.out.println("Address: " + addr.getHostAddress());
            System.out.println("Hostname: " + addr.getHostName());
            System.out.println("Is loopback addr: " + addr.isLoopbackAddress());
        }
    }
}
```

but that also seems to return the correct results and, more importantly, resolves the hostname from `/etc/hosts`:

```
[root@8f03d93b6012 /]# java Main
Hostname: 8f03d93b6012
Local address: 10.0.2.100
Address: 10.0.2.100
Hostname: 8f03d93b6012
Is loopback addr: false
```

I will keep looking but for now, thank you both very much for your help on this!
If I get to the bottom of this, I will update this issue so that perhaps the analysis is of help for future readers of this issue.
