### ISSUE TITLE
How to completely remove podman from mac?

### ISSUE THREAD

**Issue by DarthPestilane** [containers/podman#11319]
I installed podman using homebrew on mac. How do I completely remove it? Simply `brew uninstall podman` ?

**Comment by Luap99** [comment]
@ashley-cui @baude PTAL

**Comment by ashley-cui** [comment]
Yep. `brew uninstall podman`

**Comment by josh-m-sharpe** [comment]
Seems like `brew uninstall podman` doesn't do all the things:

?130 (4:39:00 PM) ~/work/ctm-nginx (master) 😜 ps aux|grep podman
jsharpe          12105   0.1 11.5 412424192 3846768 s004  S     4:12PM   1:04.24 /opt/homebrew/bin/qemu-system-aarch64 -m 2048 -smp 1 -fw_cfg name=opt/com.coreos/config,file=/Users/jsharpe/.config/containers/podman/machine/qemu/podman-machine-default.ign -qmp unix://var/folders/62/_hwr4js55n792krd00ch10yc0000gp/T/podman/qmp_podman-machine-default.sock,server=on,wait=off -netdev socket,id=vlan,fd=3 -device virtio-net-pci,netdev=vlan,mac=5a:94:ef:e4:0c:ee -device virtio-serial -chardev socket,path=/var/folders/62/_hwr4js55n792krd00ch10yc0000gp/T/podman/podman-machine-default_ready.sock,server=on,wait=off,id=podman-machine-default_ready -device virtserialport,chardev=podman-machine-default_ready,name=org.fedoraproject.port.0 -accel hvf -accel tcg -cpu cortex-a57 -M virt,highmem=off -drive file=/opt/homebrew/share/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on -drive file=/Users/jsharpe/.local/share/containers/podman/machine/qemu/podman-machine-default_ovmf_vars.fd,if=pflash,format=raw -drive if=virtio,file=/Users/jsharpe/.local/share/containers/podman/machine/qemu/podman-machine-default_fedora-coreos-36.20220421.dev.0-qemu.aarch64.qcow2 -display none
jsharpe          13240   0.0  0.0 408628368   1632 s003  S+    4:39PM   0:00.00 grep podman
jsharpe          12104   0.0  0.1 409251008  38096 s004  S     4:12PM   0:05.83 /opt/homebrew/opt/podman/libexec/gvproxy -listen-qemu unix:///var/folders/62/_hwr4js55n792krd00ch10yc0000gp/T/podman/qemu_podman-machine-default.sock -pid-file /var/folders/62/_hwr4js55n792krd00ch10yc0000gp/T/podman/podman-machine-default.pid -ssh-port 49933 -forward-sock /Users/jsharpe/.local/share/containers/podman/machine/podman-machine-default/podman.sock -forward-dest /run/user/502/podman/podman.sock -forward-user core -forward-identity /Users/jsharpe/.ssh/podman-machine-default
√ (4:39:04 PM) ~/work/ctm-nginx (master) 😜 brew uninstall podman
Uninstalling /opt/homebrew/Cellar/podman/4.0.3... (172 files, 46.2MB)
√ (4:39:09 PM) ~/work/ctm-nginx (master) 😜 ps aux|grep podman
jsharpe          13387   0.6  0.0 408628368   1632 s003  S+    4:39PM   0:00.00 grep podman
jsharpe          12105   0.1 11.5 412429232 3846912 s004  S     4:12PM   1:04.27 /opt/homebrew/bin/qemu-system-aarch64 -m 2048 -smp 1 -fw_cfg name=opt/com.coreos/config,file=/Users/jsharpe/.config/containers/podman/machine/qemu/podman-machine-default.ign -qmp unix://var/folders/62/_hwr4js55n792krd00ch10yc0000gp/T/podman/qmp_podman-machine-default.sock,server=on,wait=off -netdev socket,id=vlan,fd=3 -device virtio-net-pci,netdev=vlan,mac=5a:94:ef:e4:0c:ee -device virtio-serial -chardev socket,path=/var/folders/62/_hwr4js55n792krd00ch10yc0000gp/T/podman/podman-machine-default_ready.sock,server=on,wait=off,id=podman-machine-default_ready -device virtserialport,chardev=podman-machine-default_ready,name=org.fedoraproject.port.0 -accel hvf -accel tcg -cpu cortex-a57 -M virt,highmem=off -drive file=/opt/homebrew/share/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on -drive file=/Users/jsharpe/.local/share/containers/podman/machine/qemu/podman-machine-default_ovmf_vars.fd,if=pflash,format=raw -drive if=virtio,file=/Users/jsharpe/.local/share/containers/podman/machine/qemu/podman-machine-default_fedora-coreos-36.20220421.dev.0-qemu.aarch64.qcow2 -display none
jsharpe          12104   0.0  0.1 409251008  38096 s004  S     4:12PM   0:05.83 /opt/homebrew/opt/podman/libexec/gvproxy -listen-qemu unix:///var/folders/62/_hwr4js55n792krd00ch10yc0000gp/T/podman/qemu_podman-machine-default.sock -pid-file /var/folders/62/_hwr4js55n792krd00ch10yc0000gp/T/podman/podman-machine-default.pid -ssh-port 49933 -forward-sock /Users/jsharpe/.local/share/containers/podman/machine/podman-machine-default/podman.sock -forward-dest /run/user/502/podman/podman.sock -forward-user core -forward-identity /Users/jsharpe/.ssh/podman-machine-default

**Comment by josh-m-sharpe** [comment]
Seems like these were better steps:

```
podman list
podman machine list
podman machine stop podman-machine-default

podman machine rm podman-machine-default

The following files will be deleted:

/Users/jsharpe/.ssh/podman-machine-default
/Users/jsharpe/.ssh/podman-machine-default.pub
/Users/jsharpe/.config/containers/podman/machine/qemu/podman-machine-default.ign
/Users/jsharpe/.local/share/containers/podman/machine/qemu/podman-machine-default_fedora-coreos-36.20220421.dev.0-qemu.aarch64.qcow2
/Users/jsharpe/.local/share/containers/podman/machine/podman-machine-default/podman.sock
/Users/jsharpe/.local/share/containers/podman/machine/qemu/podman-machine-default_ovmf_vars.fd
/Users/jsharpe/.config/containers/podman/machine/qemu/podman-machine-default.json


ps aux|grep podman
jsharpe          13798   0.0  0.0 408628368   1632 s003  S+    4:41PM   0:00.00 grep podman



 brew uninstall podman
```

**Comment by rhatdan** [comment]
brew unsinstall podman should default to those commands in its setup script.

**Comment by mongoliaredmountain** [comment]
<img width="437" alt="image" src="https://user-images.githubusercontent.com/22609864/202607143-c6dc20ac-1707-42fd-866e-a74a3f641937.png">
How to uninstall podman?

**Comment by Kovah** [comment]
What if one has installed Podman through Podman Desktop and not through brew?

**Comment by captainepoch** [comment]
> What if one has installed Podman through Podman Desktop and not through brew?

Was anybody uninstall it when installed this way?

**Comment by cdbca** [comment]
> > What if one has installed Podman through Podman Desktop and not through brew?
> 
> Was anybody uninstall it when installed this way?

```bash
which podman 
sudo rm -rf /opt/podman
```

**Comment by heyvito** [comment]
> > What if one has installed Podman through Podman Desktop and not through brew?
> 
> Was anybody uninstall it when installed this way?

I had to remove it after Podman Desktop installed it, and I did this:

1. Remove the default podman machine (if any)

```bash
podman machine rm
```

Then, basically run the PKG's `postinstall` steps in reverse:

```bash
sudo /opt/podman/bin/podman-mac-helper uninstall
sudo rm /etc/paths.d/podman-pkg
sudo rm -rfv /opt/podman
```

**Comment by masterkain** [comment]
that is not enough, podman broke my access to docker desktop, I had to remove  /var/run/docker.sock symlink, otherwise no amount of reboots/removals would work:

```
% docker run -d -p 80:80 docker/getting-started
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by thoke** [comment]
> > > What if one has installed Podman through Podman Desktop and not through brew?
> > 
> > 
> > Was anybody uninstall it when installed this way?
> 
> I had to remove it after Podman Desktop installed it, and I did this:
> 
> 1. Remove the default podman machine (if any)
> 
> ```shell
> podman machine rm
> ```
> 
> Then, basically run the PKG's `postinstall` steps in reverse:
> 
> ```shell
> sudo /opt/podman/bin/podman-mac-helper uninstall
> sudo rm /etc/paths.d/podman-pkg
> sudo rm -rfv /opt/podman
> ```

This is what helped me the most!

I was in the same boat where I used Podman Desktop, but have since moved on from it.

Here's what I did:

```shell
podman machine stop
podman machine rm
sudo podman-mac-helper uninstall
sudo rm /etc/paths.d/podman-pkg
sudo rm -frv /opt/podman
```

Then, I  removed Podman Desktop with my AppCleaner app.

**Comment by asmoura** [comment]
Additional step in macOS: 
 rm -fr ~/.local/share/containers/

**Comment by antun** [comment]
I think there's a step missing for `podman-mac-helper`. I'm trying to undo the changes that `podman-mac-helper` did. Before I installed it, the `docker.sock` looked like this:

    /var/run/docker.sock -> /Users/antun/.docker/run/docker.sock

I just ran: `sudo /usr/local/Cellar/podman/4.7.0/bin/podman-mac-helper `uninstall`, but the `docker.sock` is still pointing to the podman one:

    /var/run/docker.sock -> /Users/antun/.local/share/containers/podman/machine/podman.sock

Not sure how to correct this.

**Comment by sdavids** [comment]
I had to do the following:

```
$ sudo sfltool dumpbtm | grep pod
    #1: com.github.containers.podman.helper-dev
                 Name: podman-mac-helper
           Identifier: com.github.containers.podman.helper-dev
                  URL: file:///Library/LaunchDaemons/com.github.containers.podman.helper-dev.plist
      Executable Path: /usr/local/podman/helper/dev/podman-mac-helper
$ sudo /usr/local/podman/helper/dev/podman-mac-helper uninstall
$ sudo rm /usr/local/podman/helper/dev/podman-mac-helper
$ sudo rm /Library/LaunchDaemons/com.github.containers.podman.helper-dev.plist
$ sudo rm /var/run/podman-helper-dev.socket
$ sudo sfltool resetbtm
$ sudo reboot
```
