### ISSUE TITLE
docs.podman.io Logo missing.

### ISSUE THREAD

**Issue by adrian5** [containers/podman#11332]
When visiting [docs.podman.io](https://docs.podman.io), I don't see the podman logo but `https://github.com/containers/podman/blob/main/logo/podman-logo.png&raw=true`.

Consider switching that URL to `https://raw.githubusercontent.com/containers/podman/main/logo/podman-logo.png` which should persist as well.

**Comment by TomSweeneyRedHat** [comment]
@Luap99 where did you fix it?  Cycling through the versions, I'm seeing a number of others with the same issue.  For instance, v3.2.3 is also broken.  I don't mind fixing them, but I'm not sure what's getting tweaked?

**Comment by Luap99** [comment]
The latest version was still trying to build the master branch. @baude changed it to the main branch.
Unfortunately it is not possible to fix the link for the old releases.

**Comment by TomSweeneyRedHat** [comment]
@Luap99 thanks, I was looking all over and couldn't find anything to tweak.
