### ISSUE TITLE
Allow mounting volumes/host paths to a running container.

### ISSUE THREAD

**Issue by tomprince** [containers/podman#11336]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I'd like to be able to add and remove mounts on a running container. I have long-running container that I use for builds and tests of several related projects. I'd like to be able to mount and unmount the project source directories as I work on different parts of the system.

I think for my use case, being able to mount them during `podman exec` would be sufficient,

**Comment by rhatdan** [comment]
podman exec enters the userns and mountns, you could do `podman exec--user root --privileged` but not sure you would have access to content on the host mount namespace at that time.

rootless containers can only do the following kinds of mounts

fuse, bind, procfs, overlay, sysfs, tmpfs (I believe).
