### ISSUE TITLE
Podman /dev mount can't be manually set with --tmpfs

### ISSUE THREAD

**Issue by KCSesh** [containers/podman#11343]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Host /dev is mounted as:

```
none on /dev type devtmpfs (rw,nosuid,noexec,relatime,size=15932176k,nr_inodes=3983044,mode=755)
```

Container by default gets `/dev` mounted as, according to the config.json: 

```
    {
      "destination": "/dev",
      "type": "tmpfs",
      "source": "tmpfs",
      "options": [
        "nosuid",
        "strictatime",
        "mode=755",
        "size=65536k"
      ]
    },
```

I am trying to mount my container `/dev` manually so I can add additional mount options.
**However**, when I try and mount it manually with the **default mount options** it fails to launch the container in interactive psudeo terminal mode. 

**2 Questions:**

1. Why is this not working? 
2. Why is `/dev` not matching my hosts `noexec` 

**Steps to reproduce the issue:**

1.
```
sudo podman --storage-driver=vfs create --read-only -it --tmpfs=/dev:nosuid,strictatime,mode=755,size=65536k --name test --rootfs /data/rootfs /bin/bash
```
2.
```
sudo podman --storage-driver=vfs start -ia test
```
3.
`
Error: unable to start container 6d9bd39dac12be88ef26e192b3e0eb2e37699b9f9334212edf1b563977c14930: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"open /dev/ptmx: no such file or directory\"": OCI runtime attempted to invoke a command that was not found
`

IF I remove `--tmpfs=/dev:nosuid,strictatime,mode=755,size=65536k` it works and the mount options show:

`
        "nosuid",
        "strictatime",
        "mode=755",
        "size=65536k"
`

**Describe the results you received:**
Container fails to start in interactive mode. 
It will work if I remove the `-it` flags, but this is odd behavior. 

**Describe the results you expected:**
I would expect the container to start normally, even if I create the `--tmpfs /dev` myself. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 3.3.0-dev

```

**Output of `podman info --debug`:**

```
podman info --debug
host:
  arch: arm64
  buildahVersion: 1.21.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - debug
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/local/bin/conmon'
    path: /usr/local/bin/conmon
    version: 'conmon version 2.0.29-dev, commit: '
  cpus: 8
  distribution:
    distribution: ubuntu
    version: "18.04"
  eventLogger: file
  hostname: pan-appliance
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.9.140
  linkmode: dynamic
  memFree: 24989339648
  memTotal: 33424560128
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 16712269824
  swapTotal: 16712269824
  uptime: 49h 50m 32.94s (Approximately 2.04 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.3.0-dev
  Built: 1623343160
  BuiltTime: Thu Jun 10 16:39:20 2021
  GitCommit: dffbf16b24ba971a96db753100b7f43f5d6df3f8
  GoVersion: go1.16
  OsArch: linux/arm64
  Version: 3.3.0-dev

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Built podman myself for Ubuntu 18.04

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Comment by giuseppe** [comment]
I think it should be fine to add `noexec` to `/dev`.

We already have a `--security-opt proc-opts=...` to pass additional arguments for the `/proc` mount, I think we could have a similar option for `/dev` in case users want to opt out from the default.

**Comment by KCSesh** [comment]
@giuseppe that would be great! 


1. Do you know why setting the `--tmpfs` manually is not working? 

2. And do you know where the  `/dev` defaults are?  
Is this hardcoded somewhere?

**Comment by giuseppe** [comment]
>     1. Do you know why setting the `--tmpfs` manually is not working?

because you override the `/dev/tty` mount.

>     2. And do you know where the  `/dev` defaults are?
>        Is this hardcoded somewhere?

yes, they are hardcoded in `vendor/github.com/opencontainers/runtime-tools/generate/generate.go`

**Comment by KCSesh** [comment]
Thanks @giuseppe so I can simply use `--tmpfs /dev` AND `--mount=type=devtps,destination=/dev/pts/` and then I can override the `/dev` mount with my options.
This works for now! 

But I am interested in the --security-opt dev-opts= as well like you suggested.

**Comment by rhatdan** [comment]
Should we change the default, if this just works, and it would be more secure to mount /dev with noexec, we should just do it.  Although this is buries in runtime-tools.

**Comment by KCSesh** [comment]
Doesn't seem like '--mount' lets me specify 'noexec' for `/dev/pts`, from what I can tell. 
Unless I'm missing something @giuseppe and @rhatdan?

**Comment by KCSesh** [comment]
Hmm, when I do: 

`
--tmpfs=/dev:noexec,nosuid,strictatime,mode=755,size=65536k --mount=type=devpts,destination=/dev/pts
`

The `config.json` looks like this:

```
...
    {
      "destination": "/dev",
      "type": "tmpfs",
      "source": "tmpfs",
      "options": [
        "noexec",
        "nosuid",
        "strictatime",
        "mode=755",
        "size=65536k"
      ]
    },
    {
      "destination": "/dev/pts",
      "type": "devpts",
      "source": "devpts"
    },
...
```

And in the actual container, when I type: `mount`,
I see:

```
tmpfs on /dev type tmpfs (rw,nosuid,noexec,size=65536k,mode=755,uid=1004,gid=1006)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=100004,mode=620,ptmxmode=666)
```

So this works for me! 

I am curious if those must be the default mount options for type: `devpts`

**Comment by KCSesh** [comment]
Seems I am hitting the default logic here:

https://github.com/containers/podman/blob/266a3892f25d8cee508f421e718ba6f135ff7123/pkg/specgen/generate/oci.go#L231-L254
