### ISSUE TITLE
Support multiple source files in `podman container cp`.

### ISSUE THREAD

**Issue by tomprince** [containers/podman#11346]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I recently wanted to copy multiple files from a container to the local filesystem. I'd have liked to do something like:
```shell
podman container cp nix:/src/flake.{nix,lock} .
```
but instead needed to use multiple commands (there were a bunch of other files in the container directory that I *didn't* want to copy as well).

**Comment by rhatdan** [comment]
@vrothberg PTAL
Can podman cp support "globbing"?

**Comment by vrothberg** [comment]
> @vrothberg PTAL
> Can podman cp support "globbing"?

No, that's not supported and would be quite some work.  Note that Docker doesn't support it either.  Currently, the underlying assumption is that it's either _one_ file or _one_ directory. Globbing would lift that to _multiple_ files or directories and require changing the REST endpoint, and then, step-by-step, introducing the notion of a list of paths being copied.

**Comment by vrothberg** [comment]
Note that an alternative to `container cp` would be using `podman container mount` and operate on the returned mount point.

**Comment by mheon** [comment]
Concur that `podman container mount` is probably a better option. We've tried globbing on `cp` before, and it resulted in more than one CVE before we dropped the idea.

**Comment by vrothberg** [comment]
Thanks, @mheon. That's reassuring. I'll open a PR to elaborate on that in the man pages.
