### ISSUE TITLE
Provide a version of `podman container cp container:/file -` that doesn't create a tarball. 

### ISSUE THREAD

**Issue by tomprince** [containers/podman#11345]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I'd like a way to get the contents of a file from a container in a way that I can pipe into another program. I'm looking to do something like
```shell
podman container cp nix:/nix/.../docker-archive.tar.gz - | podman load
```

I *could* do this by adding `tar xO` in the middle of the pipeline, but it seems like a reasonable thing to want to do, without needing an extra program.

**Comment by rhatdan** [comment]
Why not do `podman exec CONTAINER cat foobar`

**Comment by vrothberg** [comment]
Thanks for reaching out, @tomprince!

I can only echo what @rhatdan suggests.  `podman exec` is better suited for your use case.  Another option could be using `podman mount $CONTAINER` and operate on the returned mount point.
