### ISSUE TITLE
--userns documentation markdown layout issue

### ISSUE THREAD

**Issue by eriksjolund** [containers/podman#11364]
The itemized list in the `--userns` section changed between

in v3.2.3
https://docs.podman.io/en/v3.2.3/markdown/podman-run.1.html#userns-mode

and

in v3.3.0
https://docs.podman.io/en/v3.3.0/markdown/podman-run.1.html#userns-mode

The items __container__ and __host__ are not listed in the same way as the other items in the v3.3.0 version.

The hyphens before __container__ and __host__ were removed in this git commit
https://github.com/containers/podman/commit/100c23dc5b01b8f9730e3c39fd538f81e269484c

I would assume that  __container__ and __host__ should be listed in the itemized list just like the other items.

**Comment by giuseppe** [comment]
thanks, opened a PR: https://github.com/containers/podman/pull/11368
