### ISSUE TITLE
container does not show exposed ports from the pod when created via --pod-id-file

### ISSUE THREAD

**Issue by laolux** [containers/podman#11369]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
`podman generate systemd` does not pass on opened ports from the pod to the containers inside the pod -> containers are not reachable from outside. This does not happen when creating the pod by hand.

**Steps to reproduce the issue:**

1. create a pod: `podman pod create --name testpod -p 2000:2000/tcp`

2. add a container to the pod `podman run --pod testpod --rm -d docker.io/library/alpine:latest /bin/sleep 1000`

3. run `podman ps`: you will see that port 2000:2000/tcp is available to both the pod and the container

4. create systemd units with `podman generate systemd --new -f -n testpod `

5. restart the pod using the freshly created systemd units using `systemctl --user start pod-testpod.service`

6. run `podman ps` again: you will see that only the pod has port 2000:2000/tcp, and the container has no exposed port 

**Describe the results you received:**
When initially creating the pod, both the pod and the container have port 2000:2000/tcp exposed.
When generating a systemd unit and running the pod as systemd user service, then only the pod has port 2000:2000/tcp exposed.

**Describe the results you expected:**
The container has port 2000:2000/tcp exposed as well when run via systemd user service

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.3.0
API Version:  3.3.0
Go Version:   go1.16.6
Built:        Sat Aug 21 04:36:14 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.22.3
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.29-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: Notebook
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.13.12-200.fc34.x86_64
  linkmode: dynamic
  memFree: 331317248
  memTotal: 16660295680
  ociRuntime:
    name: crun
    package: crun-0.21-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.21
      commit: c4c3cdf2ce408ed44a9e027c618473e6485c635b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 1h 6m 39.5s (Approximately 0.04 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 1
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.7.1-1.fc34.x86_64
      Version: |-
        fusermount3 version: 3.10.4
        fuse-overlayfs: version 1.7.1
        FUSE library version 3.10.4
        using FUSE kernel interface version 7.31
  graphRoot: /home/user/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 18
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.0
  Built: 1629488174
  BuiltTime: Sat Aug 21 04:36:14 2021
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.3.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.3.0-1.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes  (I ran `dnf update --refresh --enablerepo=updates-testing podman`, so according to the install instructions I now have the very latest podman. Will try again when there is something new available in updates-testing, koji is too slow to download from at the moment)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
Thanks for reaching out!

It does not seem to be related to `generate systemd` but to using `--pod-id-file` rather than using `--pod`.

@cdoern, do you have cycles to look into this issue?

**Comment by mheon** [comment]
Can you try with 3.3.1, just released? I recall backporting a fix from @Luap99 related to `--pod-id-file`

**Comment by vrothberg** [comment]
Reproducer:
```
$ rm -f /tmp/pod.id
$ podman pod create --pod-id-file /tmp/pod.id --name testpod -p 2000:2000/tcp
$ podman run --pod-id-file /tmp/pod.id --rm -d docker.io/library/alpine:latest /bin/sleep 1000
$ podman ps ...
```

**Comment by vrothberg** [comment]
> Can you try with 3.3.1, just released? I recall backporting a fix from @Luap99 related to `--pod-id-file`

Good catch, it is fixed in the main branch, closing :)

**Comment by laolux** [comment]
Works great for me, thanks.
Sorry, I did not understand that it's related to `--pod-id-file` and just looked for systemd stuff in the 3.3.1 release notes.
