### ISSUE TITLE
podman's docker-compose support sets incorrect CreateCommand which breaks systemd generation

### ISSUE THREAD

**Issue by andrew-kennedy** [containers/podman#11370]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman sets the incorrect CreateCommand info on containers created through docker-compose, which breaks systemd unit file generation.

**Steps to reproduce the issue:**

1. Create a container with docker-compose. E.g.:
```
version: "3"
services:
  terraria:
    restart: always
    image: docker.io/ryshe/terraria:latest
    command: --log-opt max-size=200k
    container_name: terraria
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 4G
    ports:
      - 7777-7778:7777-7778
    environment:
      WORLD_FILENAME: "Terrarius.wld"
    volumes:
      - ./world:/root/.local/share/Terraria/Worlds
    networks:
      - terraria

networks:
  terraria:
    name: terraria_default
```

2.  run container with `sudo docker-compose up -d`

3. Inspect container with: `sudo podman inspect --format '{{.Config.CreateCommand}}' terraria`

**Describe the results you received:**

The CreateCommand is `[/usr/bin/podman --log-level=info system service]`, and `sudo podman generate systemd --new --name terraria` fails with an error that the create command is too short or invalid.

**Output of `podman version`:**

```
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.16.6
Built:        Mon Aug  2 12:39:21 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.21.3
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.29-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: '
  cpus: 24
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: <redacted>
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.13.12-200.fc34.x86_64
  linkmode: dynamic
  memFree: 15541796864
  memTotal: 67361185792
  ociRuntime:
    name: crun
    package: crun-0.21-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.21
      commit: c4c3cdf2ce408ed44a9e027c618473e6485c635b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.9-1.fc34.x86_64
    version: |-
      slirp4netns version 1.1.8+dev
      commit: 6dc0186e020232ae1a6fcc1f7afbc3ea02fd3876
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 8584949760
  swapTotal: 8589930496
  uptime: 25h 50m 55.72s (Approximately 1.04 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
  - nvcr.io
store:
  configFile: /home/guest/.config/containers/storage.conf
  containerStore:
    number: 17
    paused: 0
    running: 17
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.7.1-1.fc34.x86_64
      Version: |-
        fusermount3 version: 3.10.4
        fuse-overlayfs: version 1.7.1
        FUSE library version 3.10.4
        using FUSE kernel interface version 7.31
  graphRoot: /home/guest/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 155
  runRoot: /run/user/1000/containers
  volumePath: /home/guest/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.3
  Built: 1627933161
  BuiltTime: Mon Aug  2 12:39:21 2021
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.2.3

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.2.3-2.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine.

**Comment by vrothberg** [comment]
Thanks for reaching out, @andrew-kennedy!

That's known but, to be fair, not-well documented limitation.  `podman generate systemd **--new**` requires the container to be created via Podman.  Container created via the remote/REST API, which is the case when using `docker-compose`, do not work.

Background: `generate systemd --new` is a looking at the "create command" of the container which is simply the `os.Args` at container creation.

Unfortunately, I don't see a way to support that since there's no way we can reverse-map an existing container to command-line flags and options.

I will open a PR though to make this more obvious in the man pages.

**Comment by vrothberg** [comment]
Opened https://github.com/containers/podman/pull/11371

**Comment by andrew-kennedy** [comment]
@vrothberg thank you for the info and the documentation updates! This does lead me to a question though: is there no official way to do declarative podman image configuration and then systemd unit generation? With docker I could create a set of compose files that I could update and add to as needed for all the services on a system. With podman, I figured I could leverage docker-compose API support to match this using the systemd unit file generation, but it seems this might not be the case?
