### ISSUE TITLE
Remote clients for macOS and Windows tutorial: unclear about what package to download for Windows

### ISSUE THREAD

**Issue by Chealer** [containers/podman#11382]
/kind feature

**Description**

[The _Podman Remote clients for macOS and Windows_ tutorial's _Windows_ section](https://github.com/containers/podman/blob/main/docs/tutorials/mac_win_client.md#windows) refers to "the Podman windows installer", which can be found on [the latest release's description page](https://github.com/containers/podman/releases/tag/v3.3.1). My best guess is that this refers to podman-v3.3.1.msi, yet that name doesn't sound like a client for Podman.

It would help to indicate the installer's file name or provide a download page which clearly presents the various downloads.

By the way, "Windows" is a proper noun and should be capitalized.

**Steps to reproduce the issue:**
This does not report a behavioral bug.

**Describe the results you received:**
This does not report a behavioral bug.

**Describe the results you expected:**
This does not report a behavioral bug.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
This does not report a behavioral bug.

**Output of `podman info --debug`:**
This does not report a behavioral bug.

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**
This does not report a behavioral bug.

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? 
No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This does not report a behavioral bug.

**Comment by mheon** [comment]
@baude @TomSweeneyRedHat PTAL

**Comment by baude** [comment]
@Chealer would you consider a PR to make the updates?

**Comment by Chealer** [comment]
@baude: would I consider a _what_?

**Comment by rhatdan** [comment]
He is asking you whether you want to open a PR to fix the documentation to look the way you want.

**Comment by Chealer** [comment]
I am sorry @rhatdan but I am more than a Podman newbie. In fact, I still haven't installed it. I don't know any of the abbreviations and can't find a glossary.

**Comment by rhatdan** [comment]
@ashley-cui @TomSweeneyRedHat @baude PTAL

**Comment by vrothberg** [comment]
ping
