### ISSUE TITLE
upstream podman image should have dnsname plugin installed and enabled

### ISSUE THREAD

**Issue by mattymo** [containers/podman#11380]
/kind feature

**Description**

A popular feature is to use a dns server to facilitate name lookups between containers in a custom network. This is possible with some manual setup, but not in the quay.io/podman/stable:v3.3.0 image.

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@TomSweeneyRedHat PTAL - it sounds like we might not be installing recommended packages? `podman-plugins` might not be in the image?

**Comment by TomSweeneyRedHat** [comment]
@mattymo @mheon we keep the image pretty darn lean, perhaps too lean?

https://github.com/containers/podman/blob/main/contrib/podmanimage/stable/Dockerfile#L14
```
RUN dnf -y update; rpm --restore shadow-utils 2>/dev/null; \
yum -y install podman fuse-overlayfs --exclude container-selinux; \
rm -rf /var/cache /var/log/dnf* /var/log/yum.*
```

I'd be find with adding podman-plugins if that makes sense and doesn't bloat the image too much.  @rhatdan thoughts?

**Comment by mattymo** [comment]
I'm mistaken. I used contrib/podmanimage/upstream/Dockerfile and it doesn't include plugins. The stable image does include dnsname plugin binary. I will reopen if I find issues with it

**Comment by rhatdan** [comment]
Makes sense that we should ship it in the image.
