### ISSUE TITLE
podman machine init - allow for overriding ignition file

### ISSUE THREAD

**Issue by anthr76** [containers/podman#11383]
Given the newest "container on the desktop" news it would be great to have podman in a good usable state on other platforms besides Linux. Currently on my work machine we're MITM with CA certificates. On a `podman machine create` I can use my own ignition and do the configuration podman does by default such as setting up a user and ssh-keys and provide my corps CA certificates. This can be somewhat cumbersome providing this to my co-worker developers. 

It would be great if we can provide an ignition file with the CA certificates etc and `podman machine create` would merge in it's existing configuration. Without these CA certs on my work machine I cannot access the outside net or do pulls.

/kind-feature

**Comment by rhatdan** [comment]
@baude @ashley-cui PTAL

**Comment by rhatdan** [comment]
@baude @ashley-cui Did you get a chance to work on this?

**Comment by ashley-cui** [comment]
Not yet

**Comment by baude** [comment]
@anthr76 how would you feel about expanding the command line with something like `--ign-file` but instead of a merge, it would be the complete ignition file.  I ask because I'm a little worried that merging may be more difficult, esp when merging different sections here and there.  What do you think?

**Comment by rhatdan** [comment]
@ashley-cui @baude I think overriding the ignition file is the best path forward.

**Comment by rhatdan** [comment]
@baude @ashley-cui Did you get a chance to look at this?

**Comment by baude** [comment]
this is fixed by git commit f21744939cbb69110488c427f0778643d5217170
