### ISSUE TITLE
podman play compose -f docker-compose.yml

### ISSUE THREAD

**Issue by abitrolly** [containers/podman#11394]
/kind feature

Use `docker-compose.yml`/`container-compose.yml` directly. Because setting up `podman` is to work with `docker-compose` is not user friendly.

**Describe the results you expected:**

```
podman play compose -f docker-compose.yml
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The most straightforward approach is to use https://kompose.io/ as a lib to do conversion into Kubernetes YAML on the fly and then invoke `podman play kube` internally.

**Comment by Jarvvski** [comment]
I would prefer that the first approach is to use docker-compose CLI, and be expected to export the right `DOCKER_HOST` env for it to work

There are many items that rely on `docker-compose` being just that, the CLI, instead of being called from podman. For example, many test suites that support docker-compose integration are built around executing commands via that CLI

Conforming podman to run `special sauce` around `podman play compose` would result in pain when dealing with this. I'd end up having to write aliases in test env's for;
```
alias docker-compose="podman play compose"
```

Which may not even work for some of the more advanced APIs out there

**Comment by abitrolly** [comment]
`docker-compose` is a development tool - for `production` you still need something like Kubernetes to split containers over multiple hosts, so my use story is not only about making it easier to run `docker-compose.yml` files, but also to make it easier to compare the environments.

As for test suites that rely on `docker-compose` CLI I really haven't seen any, and is interested to see some examples. For testing I would use the infra config that is as close to production as possible.

**Comment by shyim** [comment]
I have downloaded the docker-compose binary and run the system socket using `podman system service -t 0 unix:///var/run/docker.sock` and it works for me very okay better than expected.

**Comment by abitrolly** [comment]
@shyim that's a rootful `podman`.

**Comment by rhatdan** [comment]
@baude @Luap99 PTAL

**Comment by shyim** [comment]
@abitrolly works also for rootless https://wiki.archlinux.org/title/Podman#Docker_Compose

**Comment by Luap99** [comment]
@abitrolly  You can use the podman service as rootless. `systemctl --user start podman.socket` will create the socket at `$XDG_RUNTIME_DIR/podman/podman.sock`

**Comment by abitrolly** [comment]
@Luap99 confirming it works this way.
```
$ systemctl --user start podman.socket
$ docker-compose ps                   
Name   Command   State   Ports
------------------------------
```
Still not user friendly, unless `docker-compose` in Fedora is packaged to start the socket itself.

**Comment by rhatdan** [comment]
We don't want to have services automatically running, since this potentially could cause breakage.  Running rootful docker-compose against docker.service, would fail the same way if the docker.service was not enabled.

**Comment by abitrolly** [comment]
@rhatdan what is difference between breakage caused by user executing `systemctl --user start podman.socket` to start `docker-compose` and the breakage caused by `docker-compose` calling `systemctl --user start podman.socket` to do what the user wants?

**Comment by rhatdan** [comment]
We have no control over docker-compose, you are welcome to open a PR on docker-compose to support that, but I don't think it is likely.

**Comment by abitrolly** [comment]
I actually though that distributions can patch `docker-compose` to provide seamless user experience with `podman`. But it needs to be clarified what could be broken by running `systemctl --user start podman.socket`.

**Comment by rhatdan** [comment]
Sure we might be able to do this for Fedora, but we don't ship docker-compose for RHEL and I am not sure if other distros would go along with the change.

**Comment by abitrolly** [comment]
So. no [`docker compose`](https://docs.docker.com/engine/reference/commandline/compose/) support in `podman`?

**Comment by rhatdan** [comment]
Why do you say that?  We obviously support most Docker-compose work loads.  If you want to troll and say that the latest version does not work well, then fine. If you want to see this happen faster, then roll up your sleeves and start contributing.

**Comment by abitrolly** [comment]
> Why do you say that?
```
✗ podman compose 
Error: unrecognized command `podman compose`
```

**Comment by abitrolly** [comment]
And then you're saying that "Administrators/users still need to enable the service.", but neither `docker compose` nor `podman play` require any services to be enabled, and you've closed the issue, so from my side it looks like you are not going to implement the same UX.

**Comment by rhatdan** [comment]
Podman compose does not exist in the podman command (podman-compose does, but this is a different tool).

Docker compose requires the docker daemon or podman service to be running.  So Docker and Podman have the same requirements.

Podman play kube works without a daemon.  Docker-compose does not.

**Comment by abitrolly** [comment]
https://docs.docker.com/engine/reference/commandline/compose/ docs doesn't mention that `docker compose` requires any daemons to be manually managed by users or admins.

**Comment by rhatdan** [comment]
Try running it on a system with docker daemon shut down.

**Comment by abitrolly** [comment]
But the docker daemon is enabled and started be default when installed. So why `podman` couldn't improve on that by bringing the API on demand?

**Comment by rhatdan** [comment]
The docker daemon is not installed and started by default on any distribution I know of?  Or are you talking about on a MAC?

Fedora, RHEL, Centos, Ubuntu, Debian ... Do not start any services that get installed by default.  The administrator has to enable to service after installation.

**Comment by abitrolly** [comment]
Okay. I may be wrong. Haven't used Docker in a while.

**Comment by rhatdan** [comment]
No problem.
