### ISSUE TITLE
[MacOS BigSur] podman 3.3.1 - Error: failed to parse "X-Registry-Auth"

### ISSUE THREAD

**Issue by JorgeHernandezRamirez** [containers/podman#11407]
Hi,

I just installed podman in my macos bigsur doing

```
brew install podman
podman machine init
podman machine start
```

Until here everything works. Next i do

```
podman search mysql
```

And the following error ocurrs

```
Error: failed to parse "X-Registry-Auth" header for /v3.3.1/libpod/images/search?authfile=&filters=%7B%7D&limit=0&listtags=false&notrunc=false&term=mysql: error storing credentials in temporary auth file (server: "https://index.docker.io/v1/", user: ""): key https://index.docker.io/v1/ contains http[s]:// prefix
```

What is happening?. I just reproduce this error in two different macs. I hope your anwser

Best regards

**Comment by JorgeHernandezRamirez** [comment]
Thanks for responding to quickly

I just found a soluction removing *http://* and *https://* in *auth* section in ```~/config/docker.json```

**Comment by uniquejava** [comment]
> Thanks for responding so quickly
> 
> I just found a solution removing _http://_ and _https://_ in _auth_ section in `~/config/docker.json`

Thanks. worked like charm.
