### ISSUE TITLE
Bind mount a directory located on Mac

### ISSUE THREAD

**Issue by utam0k** [containers/podman#11401]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
Maybe this is perhaps not a conversation to be had in this repository. 
I think podman is a very big alternative to Docker Desktop. One feature I'm currently missing is the ability to share files with the Mac side. I know that this is difficult because we use `qemu`, but I would be very happy if you would consider making this a reality. Is this worthy of consideration?

**Reference**
- [Docker solution](https://docker-docs.netlify.app/docker-for-mac/osxfs/)
- [lima is already experimenting what file sharing](https://github.com/lima-vm/lima#sharing-files-across-macos-and-linux)

**Comment by utam0k** [comment]
So this is being considered. That's excellent news for me. Is it being considered somewhere where everyone can see it? I'd like to see the discussion and progress if possible.

**Comment by anthr76** [comment]
sshfs may be a option here?

**Comment by mheon** [comment]
@TomSweeneyRedHat When's the next community cabal? Seems like a good topic for discussion.

**Comment by georgettica** [comment]
hey! I just had a discussion with the team and I tried to use podman to replace docker-desktop..

I was able to pull and run stateless containers / mount files while in `--privileged` and that the file is in `/etc`

if `/Users/<username>` mapping will be discuss as an option it would be very beneficial

**Comment by afbjorklund** [comment]
Also #8016

**Comment by afbjorklund** [comment]
> I know that this is difficult because we use `qemu`

QEMU has built-in file sharing (using `9p` protocol), sample implementation in  #11454

Like reverse sshfs, it is probably too slow for real-life use cases. But it is _something_ ?

Normal sshfs is fast, since most files are on the VM and you only open the ones you edit.

There is an implementation of the `mount` command for it (sshfs) available in #11423

**Comment by mheon** [comment]
Update: The next community cabal is next Thursday, September 16th at 10:00 a.m. EDT (UTC-4). We'll be discussing, among other topics, the architecture and next steps for volume mounts for `podman machine`

**Comment by utam0k** [comment]
@mheon Thanks for the information. I'm looking forward to it. Should I close this issue? Or should I keep it for tracking purposes?

**Comment by mheon** [comment]
I'll close in favor of the existing #8016 - we can continue to track there.

**Comment by afbjorklund** [comment]
The other story is slightly more generic, since it talks about providing a solution for _any_ remote connection (which would most likely based on sshfs) but this use case (Mac) only needs something to work locally (which means that it can use something like virtfs)

No reason why both features could not be covered by the other issue, though.

**Comment by heyvito** [comment]
I know that's a big stretch, but has anyone researched whether we can run ELFs "natively" using `Hypervisor.framework` on macOS? To be simple, reductive, and absurd, it would be a matter of providing basic runtime requirements like ld, a glibc and so, intercepting syscalls we don't have on macOS, and somewhat translating it to have the same result as we would have on linux. 🤔 
We wouldn't even need to load a kernel there, I believe that just mapping the ELF to the VM's memory and setting registers as needed would suffice, but I'm really rusty on those topics TBH.

**Comment by afbjorklund** [comment]
That sounds more like WSL1 for Windows (which was abandoned), but if you are interested in that you can check out [noah](https://github.com/linux-noah/noah)

**Comment by heyvito** [comment]
> > I know that's a big stretch, but has anyone researched whether we can run ELFs "natively" using Hypervisor.framework
> 
> That sounds more like WSL1 for Windows (which was [abandoned](https://docs.microsoft.com/en-us/windows/wsl/compare-versions)), but if you are interested in that you can check out [noah](https://github.com/linux-noah/noah)

Whoa! Noah is indeed what I was looking for. Wonder why they abandoned it. 🤔 
Will take a look and fiddle around to see what we can get from it. 🙌🏻 

Thank you, @afbjorklund!

**Comment by afbjorklund** [comment]
> Wonder why they abandoned it. :thinking:

It's harder to do syscall translation and process isolation, than to emulate the old system - with all the warts and all.

But it _can_ be done, as seen in the FreeBSD linuxulator and the SmartOS lx-branded zones. If one _really_ wants to...

It's totally off-topic in **this** issue, though. 😊
