### ISSUE TITLE
should not rely on TMPDIR env variable

### ISSUE THREAD

**Issue by maxandersen** [containers/podman#11418]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. `podman machine stop` (or start or other commands) shows error: 
   `Error: unable to resolve TMPDIR`

2. re-run with `TMPDIR=blah podman machine stop` and it works

**Describe the results you received:**

unless TMPDIR is set most podman machine commands fail.

**Describe the results you expected:**

that podman machine will just work.

TMPDIR should be assumed set.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version
Error: failed to create sshClient: Connection to bastion host (ssh://core@localhost:61556/run/user/1000/podman/podman.sock) failed.: dial tcp [::1]:61556: connect: connection refused
```

but it is `3.3.0` :)

**Output of `podman info --debug`:**

```
same error :)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
i'm on OS X
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Are you sure that it fails when `TMPDIR` is completely unset?

**Comment by Luap99** [comment]
@mheon Yes. https://github.com/containers/podman/blob/858d3e47c26788e64083842cc6617b666f4279a1/pkg/machine/qemu/options_darwin.go#L9-L15

@baude @ashley-cui PTAL Should this fall back to something like `/tmp` on macOS?

**Comment by mheon** [comment]
OK. OS X only, makes sense. Concur we need to rewrite to not depend on that.

**Comment by ashley-cui** [comment]
> Should this fall back to something like `/tmp` on macOS?
/tmp sgtm
