### ISSUE TITLE
There is no localhost on /etc/hosts

### ISSUE THREAD

**Issue by 1995parham** [containers/podman#11411]
/kind bug

I have setup rootless podman and after running a container everything works find but in the `/etc/hosts/` I have the following content:

```
# Static table lookup for hostnames.
# See hosts(5) for details.
# used by slirp4netns
10.0.2.100      b932ec01d49e compassionate_visvesvaraya
10.0.2.2 host.containers.internal
```

but I think it should be:

```
# Static table lookup for hostnames.
# See hosts(5) for details.
127.0.0.1 localhost
# used by slirp4netns
10.0.2.100      b932ec01d49e compassionate_visvesvaraya
10.0.2.2 host.containers.internal
```

and because of that there is no resolution from localhost to 127.0.0.1.

**Comment by 1995parham** [comment]
sure, I used the following command:

```
podman run -ti --rm bash 
```

Also I can share my configuration if it helps.

**Comment by Luap99** [comment]
What is in `/etc/hosts` on the host?

**Comment by 1995parham** [comment]
it is empty on my host but images by default has this, when I use `no_hosts` option I have localhost.

**Comment by Luap99** [comment]
Podman will use the the file from the host and then append the new entries, in your case for slirp4netns.
@mheon Should we add localhost if it does not exists in the host file, WDYT?

**Comment by mheon** [comment]
For `slirp4netns` and similar network modes, I would say yes.

For `host` networking, no, we should ensure that we exactly mirror the host system.

**Comment by 1995parham** [comment]
so if you agree I can a PR for this.

**Comment by mheon** [comment]
Sure
