### ISSUE TITLE
Release Assets 

### ISSUE THREAD

**Issue by tonykay** [containers/podman#11417]
/kind feature

**Description**

The release page assets include a `Darwin` release zip and DMG which is in fact really Darwin x86_64

1) Should specify Darwin and x86_64
2) Please add Darwin + aarch? Whatever designator best represents current and future ARM/M series builds

(I do realize not all releases e.g. `3.3.0` have a Darwin arm build but `3.2.0` did.)

**Comment by mheon** [comment]
Seems reasonable. @cevich Would you want to take this one?

**Comment by cevich** [comment]
Sure, happy to.
