### ISSUE TITLE
podman run could be really help and tell try `podman machine start`

### ISSUE THREAD

**Issue by maxandersen** [containers/podman#11419]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

on OSX when running `podman run` the error is: 

```
podman run alpine
Error: failed to create sshClient: Connection to bastion host (ssh://core@localhost:61556/run/user/1000/podman/podman.sock) failed.: dial tcp [::1]:61556: connect: connection refused
```

Which is rather technical info and a user using podman to just run containers have very little context why that does not work.

**Describe the results you received:**

Cryptic technical message received with no aid to user.

**Describe the results you expected:**

```
podman run alpine
Error: could not run `alpine` as connection to podman could not be established. Have you ensure podman is running ? Try using `podman machine start`

Root cause:
Error: failed to create sshClient: Connection to bastion host (ssh://core@localhost:61556/run/user/1000/podman/podman.sock) failed.: dial tcp [::1]:61556: connect: connection refused
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
 podman version
Error: failed to create sshClient: Connection to bastion host (ssh://core@localhost:61556/run/user/1000/podman/podman.sock) failed.: dial tcp [::1]:61556: connect: connection refused
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@rhatdan and @baude have both been talking about this one. Definitely something we want to do.

**Comment by rhatdan** [comment]
Agreed.
@ashley-cui PTAL
