### ISSUE TITLE
warning when check "podman --version"

### ISSUE THREAD

**Issue by Mingli-Yu** [containers/podman#11425]
\# podman --version
WARN[0000] Failed to decode the keys ["storage.options.override_kernel_check" "storage.options.thinpool.ostree_repo" "storage.options.thinpool.skip_mount_home"] from "/etc/containers/storage.conf". 
podman version 3.3.1

How to remove the warning? Thanks!

**Comment by Luap99** [comment]
Your config file contains invalid keys. Did you modify this file?
Remove the listed entries from the file to remove the warning.

**Comment by Mingli-Yu** [comment]
Thanks Luap99! Actually I also removed the keys in warning as a workaround locally, but consider if there any means to make the keys work.

**Comment by rhatdan** [comment]
Are you attempting to use devicemapper backend?  

Why are you trying to override the kernel_check?

**Comment by lineber** [comment]
Thanks @rhatdan , this error message showed up for me as well around the end of August.  I didn't associate the error with my adding a udev file until I just read your reply.

I have a custom keyboard (Planck) and I need to add the udev command for the device to be seen in Linux:
`KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0666", TAG+="uaccess", TAG+="udev-acl"`

I don't really see how modifying a device file could affect my podman instance, but I cannot deny that the issue happened immediately after that update.

Either way, the instance still runs despite the error; and I need the keyboard file as I'm using it to learn Colemak (alternate keyboard format). I at least now know where to begin researching the issue.

**Comment by rhatdan** [comment]
What OS are you on?  Have you modified /etc/containers/storage.conf?

**Comment by lineber** [comment]
I'm running Fedora Silverblue 34. I did not modify the /etc/container/storage.conf file. But the override kernel_check is marked as true.

**Comment by rhatdan** [comment]
grep override /etc/containers/storage.conf
grep override ~/.config/containers/storage.conf

**Comment by lineber** [comment]
Thanks for the reply. But before I saw this message, I just deleted the file and that got rid of the error message. The server works perfectly now. I know that's not probably the best answer. But it worked for me. Thanks again.

**Comment by plagov** [comment]
I'm getting the same warning when running any `podman` command.
```
~> podman --version
WARN[0000] Failed to decode the keys ["storage.options.ostree_repo"] from "$HOME/.config/containers/storage.conf". 
podman version 4.1.1
```

Here's my `storage.conf` file:
```
[storage]
  driver = "overlay"
  runroot = "/run/user/1000"
  graphroot = "$HOME/.local/share/containers/storage"
  [storage.options]
    size = ""
    remap-uids = ""
    remap-gids = ""
    ignore_chown_errors = ""
    remap-user = ""
    remap-group = ""
    ostree_repo = ""
    skip_mount_home = ""
    mount_program = "/usr/bin/fuse-overlayfs"
    mountopt = ""
    [storage.options.thinpool]
      autoextend_percent = ""
      autoextend_threshold = ""
      basesize = ""
      blocksize = ""
      directlvm_device = ""
      directlvm_device_force = ""
      fs = ""
      log_level = ""
      min_free_space = ""
      mkfsarg = ""
      mountopt = ""
      use_deferred_deletion = ""
      use_deferred_removal = ""
      xfs_nospace_max_retries = ""
```
I can delete this file as was suggested above, but is it a correct and proper solution?

**Comment by rhatdan** [comment]
Basically podman is telling you that it does not know what the ostree line is in your storage.conf file.

Remove that line, or if you don;t need storage.conf customized, remove the file altogether.

**Comment by plagov** [comment]
@rhatdan, yes, I understand the workaround. I mean, I left my comment mostly not for asking for a help/solution but rather to communicate a potentially not ideal behaviour.
I'm not a frequent user of Podman and haven't made any custom configurations to either Podman or ostree. Thus, was a bit surprised to see a warning about stuff I'm not aware of.
