### ISSUE TITLE
have podman env or similar command to output setup that makes other docker clients work

### ISSUE THREAD

**Issue by maxandersen** [containers/podman#11422]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I'm coming to podman to have a way to run containers but still use it with the larger ecosystem
that know how to connect to docker demon (i.e. test containers etc.) 

They don't "just work" thus I assume there is some environment I need to setup - should/could podman provide a command like `podman env` that would print out out the necessary config ?

**Describe the results you received:**

```
podman env 
DOCKER_HOST=abc
DOCKER_...
## use this in your shell `source <(podman env)`
```

or similar.

Just some hint/setup to enable docker ce migrations.

**Comment by afbjorklund** [comment]
It's possible to view the current sockets, using `podman system connection ls`

Ultimately this needs to be paired with the _other_ feature, to create a ssh tunnel.

But one could add a generic feature. to print both DOCKER_HOST and CONTAINER_HOST ?

Currently there is no way to provide the ssh key or even the socket path to Docker, though...

**Comment by n1hility** [comment]
FYI I have a WIP proposal that introduces this and ssh tunneling here:
https://github.com/containers/podman/pull/11643

**Comment by afbjorklund** [comment]
@n1hility : does your PR add another "connection" for the temporary unix socket, or only the env vars ?

**Comment by rhatdan** [comment]
@n1hility @afbjorklund What is going on with this?

**Comment by maxandersen** [comment]
Still relevant

**Comment by baude** [comment]
I'm a little turned around on this one @maxandersen ... what exactly are you asking for?  are you wanting to use a podman frontend and a docker backend?

**Comment by n1hility** [comment]
ill do a follow-up PR for that for a later release

**Comment by afbjorklund** [comment]
Both docker and podman seem to be switching to magic config files, instead of using environment variables.

**Comment by afbjorklund** [comment]
The help text seems to have a typo/syntax error in it, missing the `//` in the scheme.

`      --url string                URL to access Podman service (CONTAINER_HOST) (default "unix:/run/user/1000/podman/podman.sock")`

But it's a valid configuration (for Podman), so it's just not an URL. Probably not important.

**Comment by maxandersen** [comment]
But magic context files is more for global config, right ?

It doesn't let you isolate / reset configuration for just one shell ?

**Comment by rhatdan** [comment]
We have talked about adding a podman context command to match the Docker one for certain types of scripts. Perhaps hidden from users.

podman machine env would probably be acceptable  Perhaps with a --docker option or maybe just print out the DOCKER_HOST=/PATH
