### ISSUE TITLE
podman machine start reports error but seem to run ?

### ISSUE THREAD

**Issue by maxandersen** [containers/podman#11421]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

```
podman machine start
INFO[0000] waiting for clients...
INFO[0000] listening tcp://0.0.0.0:7777
INFO[0000] new connection from  to /Users/max/tmp2/podman/qemu_podman-machine-default.sock
Waiting for VM ...
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
```

**Describe the results you received:**

Some indication that there was a success and a hint on what to do next as user.

**Describe the results you expected:**

```
podman machine start
INFO[0000] waiting for clients...
INFO[0000] listening tcp://0.0.0.0:7777
INFO[0000] new connection from  to /Users/max/tmp2/podman/qemu_podman-machine-default.sock
Waiting for VM ...
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
SUCCESS podman machine is now running! You should now be able to use commands such as `podman run`
```

or ultimately:
```
podman machine start
Starting podman machine...
SUCCESS podman machine is now running! You should now be able to use commands such as `podman run`
```

**Comment by mheon** [comment]
Can you provide more environment details - where are you running `podman machine` on (OS X? If so, what CPU, Intel or M1?).

**Comment by maxandersen** [comment]
OSX - Intel

**Comment by scottschreckengaust** [comment]
I am receiving the same "warning" message with `podman machine start` on an Intel based MacOS installed with brew:

```
❯ sw_vers
ProductName:	macOS
ProductVersion:	11.5.2
BuildVersion:	20G95

❯ system_profiler | grep "Processor Name: "
      Processor Name: Quad-Core Intel Core i5

❯ brew --version
Homebrew 3.2.10

❯ podman --version
podman version 3.3.0

❯ qemu-system-x86_64 --version
QEMU emulator version 6.1.0
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers
```

Consider adding the `-cpu host` to the `addArchOptions` function like the linux version:
https://github.com/containers/podman/blob/056f492f59c333d521ebbbe186abde0278e815db/pkg/machine/qemu/options_linux_amd64.go#L7-L13

at:
https://github.com/containers/podman/blob/056f492f59c333d521ebbbe186abde0278e815db/pkg/machine/qemu/options_darwin_amd64.go#L7-L10

_See https://github.com/GNS3/gns3-server/issues/1639 for the inspiration_

**Comment by baude** [comment]
the error is benign

**Comment by maxandersen** [comment]
> the error is benign

This issue is not about the specific warning - but that there is no indication to the user to know that the start succeeded - I'm suggesting that since such warnings/errors show up to actually print that there was a success; then users actually have a chance to know the warnings/errors are benign.

**Comment by rhatdan** [comment]
@maxandersen We have a fix to eliminate the warning. But you want a last line that says something like
XYZ VM Started
Correct?

**Comment by maxandersen** [comment]
Yes. Something to reliably indicate success or failure.
