### ISSUE TITLE
brew install podman not working for all + podman machne not clean setup/remove

### ISSUE THREAD

**Issue by maxandersen** [containers/podman#11424]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I and @n1hility both tried `brew install podman` and got two different results.

First few steps were similar:

`brew install podman`
(lots of python updates?)

`podman run`
(fail with no good info, see #11419)

```
podman machine init
Extracting compressed file
```
(could be a bit more useful informational)

```
podman machine start
...
```
(works but shows warning error, see #11421)

after this `podman machine ssh` works and for @n1hility he could do run but I got errors about 
permission errors (I unfortunately lost that error - and now I get a new one):

```
podman machine start
ERRO[0000] "/Users/max/tmp2/podman/qemu_podman-machine-default.sock" already exists
panic: interface conversion: net.Conn is nil, not *net.UnixConn

goroutine 1 [running]:
github.com/containers/podman/v3/pkg/machine/qemu.(*MachineVM).Start(0xc000345e40, 0x1d70aaa, 0x16, 0xc000345e40, 0x0)
        pkg/machine/qemu/machine.go:277 +0xb46
github.com/containers/podman/v3/cmd/podman/machine.start(0x2571680, 0x25bfb80, 0x0, 0x0, 0x0, 0x0)
        cmd/podman/machine/start.go:62 +0x2f5
github.com/spf13/cobra.(*Command).execute(0x2571680, 0xc0001181a0, 0x0, 0x0, 0x2571680, 0xc0001181a0)
        vendor/github.com/spf13/cobra/command.go:856 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0x257c300, 0xc00012e008, 0x1bfa5a0, 0x25bfb80)
        vendor/github.com/spf13/cobra/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        vendor/github.com/spf13/cobra/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        vendor/github.com/spf13/cobra/command.go:895
main.Execute()
        cmd/podman/root.go:90 +0xe7
main.main()
        cmd/podman/main.go:39 +0x92
```

...doing podman machine stop/rm does not fix it.

**Comment by maxandersen** [comment]
note, I'm on a different wifi/network now than I was yesterday when creating the machine...in case that matters.

**Comment by maxandersen** [comment]
managed to clean up podman machines (had to manually remove tmpdir content) and the error I get is:

```
podman run alpine
Error: failed to parse "X-Registry-Auth" header for /v3.3.0/libpod/images/pull?alltags=false&arch=&authfile=&os=&password=&policy=missing&quiet=false&reference=alpine&username=&variant=: error storing credentials in temporary auth file (server: "https://index.docker.io/v1/", user: ""): key https://index.docker.io/v1/ contains http[s]:// prefix
```

**Comment by maxandersen** [comment]
turned out I had a `~/.docker/config.json` with following content:

```
{
  "stackOrchestrator" : "swarm",
  "auths" : {
    "registry.redhat.io" : {

    },
    "https://index.docker.io/v1/" : {

    }
  },
  "HttpHeaders" : {
    "User-Agent" : "Docker-Client/19.03.12 (darwin)"
  },
  "credsStore" : "desktop",
  "experimental" : "disabled"
}
```

I assume something docker desktop setup ...no recollection :) 

if I remove that file things work.

podman shouldn't fail on this or at least hint to user why it fails.

**Comment by mheon** [comment]
@jwhonce @ashley-cui PTAL

**Comment by guillaumerose** [comment]
The panic is due to a missing error check. #11428 will help to see the proper error. Still, it doesn't fix the root cause.

**Comment by matejvasek** [comment]
> managed to clean up podman machines (had to manually remove tmpdir content) and the error I get is:
> 
> ```
> podman run alpine
> Error: failed to parse "X-Registry-Auth" header for /v3.3.0/libpod/images/pull?alltags=false&arch=&authfile=&os=&password=&policy=missing&quiet=false&reference=alpine&username=&variant=: error storing credentials in temporary auth file (server: "https://index.docker.io/v1/", user: ""): key https://index.docker.io/v1/ contains http[s]:// prefix
> ```

@maxandersen https://github.com/containers/podman/issues/11235

**Comment by baude** [comment]
is this something we can close now? fixed?

**Comment by rhatdan** [comment]
I think this is all fixed.  If new issues happen, please open up new issues.
