### ISSUE TITLE
Error: credentials key has http[s]://prefix

### ISSUE THREAD

**Issue by ritesh** [containers/podman#11435]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Install podman on macOS with `brew install podman`. Create a new `podman` machine with `podman init`

2. Use podman as a docker drop-in replacement (I have a symlink in `~/.local/bin` to point to `/usr/local/bin/podman`

3.  Try to log in to AWS Elastic Container Registry (ECR). `podman login --username AWS --password-stdin https://my-aws-account-number.dkr.ecr.us-east-1.amazonaws.com`
4. This fails with `Error: credentials key has https[s]:// prefix`
5. Try the same command with the docker binary `docker login --username AWS --password-stdin https://my-aws-account-number.dkr.ecr.us-east-1.amazonaws.com`. This works as expected.

**Describe the results you received:**
I ran `podman login --username AWS --password-stdin https://my-aws-account-number.dkr.ecr.us-east-1.amazonaws.com`

and got 

`Error: credentials key has https[s]:// prefix`

**Describe the results you expected:**

I expected to be prompted for a password from `stdin`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
Client:
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.17
Built:        Mon Aug 30 20:15:26 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.3.0
API Version:  3.3.0
Go Version:   go1.16.6
Built:        Fri Aug 20 20:36:14 2021
OS/Arch:      linux/amd64

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
N/A as this is on macOS
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I believe the macOS version uses QEMU but I'm not sure

**Comment by vrothberg** [comment]
Thanks for reaching out!  There's already an issue for that https://github.com/containers/podman/issues/11235 and is currently being worked on in https://github.com/containers/podman/pull/11430.

**Comment by ritesh** [comment]
Whoa - that was way too quick! Thanks @vrothberg!
