### ISSUE TITLE
Windows remote breaks with stdout redirection.

### ISSUE THREAD

**Issue by mook** [containers/podman#11444]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

On Windows, redirecting output from `podman run` results in an error.

**Steps to reproduce the issue:**

1. `podman.exe help version | more`

**Describe the results you received:**

Error string:
> time="2021-09-03T19:28:38-07:00" level=error msg="The handle is invalid."

**Describe the results you expected:**

Help about the command:
> Display the Podman Version Information …

**Additional information you deem important (e.g. issue happens only occasionally):**

- Running without redirection works.
- Reproducible on demand.
- This would be useful for `podman run`; the bug is also reproducible in that situation.

**Output of `podman version`:**

```
Client:
Version:      3.3.0
API Version:  3.3.0
Go Version:   go1.15.14
Git Commit:   98f252a3a1a8f1ee00f9f96c6ba00500954b5093
Built:        Fri Aug 20 11:29:20 2021
OS/Arch:      windows/amd64

Server:
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.13.15
Built:        Fri Jul 16 17:00:00 2021
OS/Arch:      linux/amd64
```
(I don't believe the server version matters here; `podman help version` shouldn't need a server.)

**Output of `podman info --debug`:**

<details><summary>(This is probably irrelevant)</summary>

```
host:
  arch: amd64
  buildahVersion: 1.21.3
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.1.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: unknown'
  cpus: 16
  distribution:
    distribution: '"opensuse-tumbleweed"'
    version: "20210801"
  eventLogger: file
  hostname: wsl
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.19.128-microsoft-standard
  linkmode: dynamic
  memFree: 12594503680
  memTotal: 12872359936
  ociRuntime:
    name: runc
    package: runc-1.0.1-1.1.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.1
      spec: 1.0.2-dev
      go: go1.13.15
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: tcp:127.0.0.1:1234
  security:
    apparmorEnabled: false
_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4294967296
  swapTotal: 4294967296
  uptime: 14m 6.89s
registries:
  search:
  - registry.opensuse.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.2.3
  Built: 1626480000
  BuiltTime: Fri Jul 16 17:00:00 2021
  GitCommit: ""
  GoVersion: go1.13.15
  OsArch: linux/amd64
  Version: 3.2.3
```
</details>

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

On the server side, which isn't needed to reproduce:
```
# rpm -q podman
podman-3.2.3-1.1.x86_64
```
The client is freshly downloaded from https://github.com/containers/podman/releases/download/v3.3.0/podman-remote-release-windows.zip

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes (just the client)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows 10 / WSL2 (using PowerShell and cmd.exe)

**Comment by atykhyy** [comment]
This same issue is reproduced in releases as far back as 2.0.2. podman-remote-windows from 2.0.1 and 2.0.0 handle redirection correctly. 1.x.x releases fail to start on Windows (known fixed issue #6558).

**Comment by atykhyy** [comment]
This bug also prevents podman from working in alternative Windows consoles such as ConEmu or MSYS2/MingW console:
```
Anton@DESKTOP MINGW64 ~
$ /c/users/anton/programs/podman.exe
time="2021-09-13T19:04:21+03:00" level=error msg="The handle is invalid."
```

**Comment by ultymatom** [comment]
Hello,

I have the same error (that was preventing the creation of volume to work in podman-compose)

I see that there were a merge pull request, but I'm not sure I understand when will this be ready, do we need to wait for next release ? or is there already a version that we can install with the fix ? 

(And thank you for the fix !)

**Comment by rhatdan** [comment]
podman 3.4 rc1 is just being cut.

https://github.com/containers/podman/pull/11616

**Comment by rhatdan** [comment]
@lsm5 this seem to be only available in Rawhide.  Can we get builds for f34?
