### ISSUE TITLE
Build with git repository with branch displays error

### ISSUE THREAD

**Issue by leighmcculloch** [containers/podman#11450]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Support building images from git repositories at a specific branch.

Podman appears to support building images from git repositories already. This works for me, and is discussed in the [docs](https://docs.podman.io/en/latest/markdown/podman-build.1.html#building-an-image-using-a-git-repository).

However, `docker build` supports building a specific branch of a git repository by appending `#branchname` to the end of the URL. For example, this will build the `cap21and40` branch instead of the default branch:

```
docker build -t stellar/quickstart:cap21and40 https://github.com/leighmcculloch/stellar--docker-stellar-core-horizon.git#cap21and40
```

When I attempt to do the same thing with podman I get an error:

```
podman build -t stellar/quickstart:cap21and40 -f Dockerfile https://github.com/leighmcculloch/stellar--docker-stellar-core-horizon.git#cap21and40
Error: no FROM statement found
```

**Steps to reproduce the issue:**

1. Run the podman command above.

2. Watch it fail.

**Describe the results you received:**

```
Error: no FROM statement found
```

**Describe the results you expected:**

I expected it to start building the git repository at the given branch.

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Output of `podman version`:**

```
Client:
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.17
Built:        Mon Aug 30 12:15:26 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.3.0
API Version:  3.3.0
Go Version:   go1.16.6
Built:        Fri Aug 20 12:36:14 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.22.3
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.29-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: '
  cpus: 1
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: localhost
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.13.12-200.fc34.x86_64
  linkmode: dynamic
  memFree: 1273651200
  memTotal: 2061852672
  ociRuntime:
    name: crun
    package: crun-0.21-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.21
      commit: c4c3cdf2ce408ed44a9e027c618473e6485c635b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.9-1.fc34.x86_64
    version: |-
      slirp4netns version 1.1.8+dev
      commit: 6dc0186e020232ae1a6fcc1f7afbc3ea02fd3876
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 0
  swapTotal: 0
  uptime: 35m 0.51s
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 13
  runRoot: /run/user/1000/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.0
  Built: 1629488174
  BuiltTime: Fri Aug 20 19:36:14 2021
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.3.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

Installed via `brew install podman`.

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes, this is the latest version available on brew.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

macOS 11.5.2. `podman machine init` was used to setup the vm.

**Comment by mheon** [comment]
@nalind @TomSweeneyRedHat Needs to be moved to Buildah, I think

**Comment by leighmcculloch** [comment]
It looks like buildah supports it, so maybe this is a bug: https://github.com/containers/buildah/blob/aff9f6beb2a3238938120b5cab8d2e65408b149a/define/types.go#L162

**Comment by leighmcculloch** [comment]
Ok I think this could be a bug in buildah.

At the following line buildah only considers a URL and Git repo if it starts with git:// or ends in .git, but a URL containing a branch will have the branch after the .git. buildah should parse the URL and check that .git is the end of the path excluding the anchor/hash and anything that trails. 

https://github.com/containers/buildah/blob/aff9f6beb2a3238938120b5cab8d2e65408b149a/define/types.go#L114

I'd be happy to open a PR with an attempted fix.
