### ISSUE TITLE
Inter container communication is not working with docker-compose and podman as a backend

### ISSUE THREAD

**Issue by mikegit21** [containers/podman#11457]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am trying to host a container architecture using ```docker-compose``` with the podman backend. The docker-compose.yml looks somewhat like this: 

```
services:
  db:
    image: db
    container_name: db
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - com
  backend:
    image: backend
    container_name: backend
    ports:
      - 8080:8080
    environment:
      # Lookup host of db on docker-compose network
      - DB_HOST=db:7687
    depends_on:
      - db
    networks:
      - com
networks:
  com: {}
```
You can see that I am creating a database and a backend that is trying to access said database over the docker-compose network. This is working when run with the docker backend, but db does not resolve when using the podman backend. 

I also tried accessing the database over localhost by setting DB_HOST to localhost:7678 as I assumed that podman would create all the containers in one pod and the would share the localhost, but this did not work either.  Running ```podman pod ls``` shows me no pods at all. Maybe this is the reason for this. 

Bottom line is that the inter container communication is not working. 

**Steps to reproduce the issue:**

1. Run a similar docker-compose architecture

2. Try to access the first container from the second container using the docker-compose service name or localhost.

**Describe the results you received:**

Service name cannot be resolved, using localhost does result in timeouts as the container cannot be found.

**Describe the results you expected:**

One container can actually reach the other container by using the service name or localhost.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version: 3.0.2-dev
API Version: 3.0.0
Go Version: go1.15.13
Built: Tue Jun 8 09:52:06 2021
OS/Arch: linux/amd64
```

**Output of `podman info --debug`:**

```
host:

  arch: amd64

  buildahVersion: 1.19.8

  cgroupManager: cgroupfs

  cgroupVersion: v1

  conmon:

    package: conmon-2.0.26-3.module+el8.4.0+11311+9da8acfb.x86_64

    path: /usr/bin/conmon

    version: 'conmon version 2.0.26, commit: a35bb9ea67d5a83c7da53202f2fcd505c036d29c'

  cpus: 8

  distribution:

    distribution: '"rhel"'

    version: "8.4"

  eventLogger: file

  hostname: ***

  idMappings:

    gidmap:

    - container_id: 0

      host_id: 714200513

      size: 1

    uidmap:

    - container_id: 0

      host_id: 1123618122

      size: 1

  kernel: 4.18.0-305.10.2.el8_4.x86_64

  linkmode: dynamic

  memFree: 5973929984

  memTotal: 33484582912

  ociRuntime:

    name: runc

 

package: runc-1.0.0-73.rc93.module+el8.4.0+11311+9da8acfb.x86_64

    path: /usr/bin/runc

    version: |-

      runc version spec: 1.0.2-dev

      go: go1.15.13

      libseccomp: 2.5.1

  os: linux

  remoteSocket:

    path: /run/user/1123618122/podman/podman.sock

  security:

    apparmorEnabled: false

    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT

    rootless: true

    seccompEnabled: true

    selinuxEnabled: true

  slirp4netns:

    executable: /usr/bin/slirp4netns

    package: slirp4netns-1.1.8-1.module+el8.4.0+11311+9da8acfb.x86_64

    version: |-

      slirp4netns version 1.1.8

      commit: d361001f495417b880f20329121e3aa431a8f90f

      libslirp: 4.3.1

      SLIRP_CONFIG_VERSION_MAX: 3

      libseccomp: 2.5.1

  swapFree: 4294963200

  swapTotal: 4294963200

  uptime: 954h 41m 51.78s (Approximately 39.75 days)

registries:

  search:

  - registry.access.redhat.com

  - registry.redhat.io

  - docker.io

store:

  configFile: /home/***/.config/containers/storage.conf

  containerStore:

    number: 0

    paused: 0

    running: 0

    stopped: 0

  graphDriverName: overlay

  graphOptions:

    overlay.mount_program:

      Executable: /usr/bin/fuse-overlayfs

      Package: fuse-overlayfs-1.4.0-3.module+el8.4.0+11311+9da8acfb.x86_64

      Version: |-

        fusermount3 version: 3.2.1

        fuse-overlayfs: version 1.4

        FUSE library version 3.2.1

        using FUSE kernel interface version 7.26

  graphRoot: /home/***/.local/share/containers/storage

  graphStatus:

    Backing Filesystem: xfs

    Native Overlay Diff: "false"

    Supports d_type: "true"

    Using metacopy: "false"

  imageStore:

    number: 0

  runRoot: /run/user/1123618122/containers

  volumePath: /home/***/.local/share/containers/storage/volumes

version:

  APIVersion: 3.0.0

  Built: 1623138726

  BuiltTime: Tue Jun  8 09:52:06 2021

  GitCommit: ""

  GoVersion: go1.15.13

  OsArch: linux/amd64

  Version: 3.0.2-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.0.1-7.module+e18.4.0+11311+9da8acfb.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes I checked the troubleshooting guide, but didn't find the issue. I know that we are using an older version of podman, but we have no possibility to upgrade podman on this VM. 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Luap99** [comment]
Do you have the dnsname plugin installed (`rpm -q podman-plugins`)?
docker-compose will never create pods, it should work exactly like docker.

**Comment by mikegit21** [comment]
Yeah, I saw this issue https://github.com/containers/podman/issues/9292 and installed it: ```podman-plugins03-0.1-7.module+e18.4.0+11311+9da8acfb.x86_64```.

**Comment by mheon** [comment]
Can you try with a more recent Podman release? 3.0.x was the first release that supported Compose and we've merged a lot of fixes since then.

**Comment by mikegit21** [comment]
Upgrading to podman version 3.2.3 did indeed fix the problem

**Comment by Edunzz** [comment]
I have the same problem, but am using podman version 3.3.1:
version: '3.7'
services:
  zabbix_proxy:
    build:
      context: .
    ports:
      - 10055:10051
    env_file:
      - env-file.env
    container_name: crl_ZabbixProxy_5.4_10055
    volumes:
      - /opt/zabbix/zabbix-files/proxy-zabbix-crl-10055/enc:/var/lib/zabbix/enc:z
      - /opt/zabbix/zabbix-files/proxy-zabbix-crl-10055/externalscripts:/usr/lib/zabbix/externalscripts:z
      - /opt/zabbix/zabbix-files/proxy-zabbix-crl-10055/mibs:/var/lib/zabbix/mibs:z
      - /opt/zabbix/zabbix-files/proxy-zabbix-crl-10055/modules:/var/lib/zabbix/modules:z
      - /opt/zabbix/zabbix-files/proxy-zabbix-crl-10055/snmptraps:/var/lib/zabbix/snmptraps:z
      - /opt/zabbix/zabbix-files/proxy-zabbix-crl-10055/ssh_keys:/var/lib/zabbix/ssh_keys:z
      - /opt/zabbix/zabbix-files/proxy-zabbix-crl-10055/ssl_ca:/var/lib/zabbix/ssl/ssl_ca:z
      - /opt/zabbix/zabbix-files/proxy-zabbix-crl-10055/ssl_certs:/var/lib/zabbix/ssl/certs:z
      - /opt/zabbix/zabbix-files/proxy-zabbix-crl-10055/ssl_keys:/var/lib/zabbix/ssl/keys:z
    networks:
      - crl_ZabbixProxy_5.4_10055_network
  mysql_db_crl:
    container_name: mysql_crl_ZabbixProxy_5.4_10055
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - /opt/zabbix/zabbix-files/mysql-proxy-zabbix-crl-10055/mysql:/var/lib/mysql:z
    environment:
      - MYSQL_ROOT_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
    networks:
      - crl_ZabbixProxy_5.4_10055_network

networks:
  crl_ZabbixProxy_5.4_10055_network:
    driver: bridge

On docker it works fine
