### ISSUE TITLE
The contributor tests don't work on Ubuntu (or Debian)

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman#11460]
/kind bug

**Description**

Contributor tests are broken with /bin/sh

Looks like they require /bin/sh -> /bin/bash

**Steps to reproduce the issue:**

1. `make lint`

2.

3.

**Describe the results you received:**

`./hack/install_golangci.sh: 7: Syntax error: "(" unexpected`

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 20.04

**Comment by afbjorklund** [comment]
Removing the "function" made it work

**Comment by Luap99** [comment]
Can you open a PR to fix it, not all shells support the function keyword.

**Comment by vrothberg** [comment]
Friendly ping

**Comment by afbjorklund** [comment]
Actually it did have `bash` as the interpreter, but then make tried to run it using `sh`
