### ISSUE TITLE
Failed to remove image, image is in use by container 

### ISSUE THREAD

**Issue by mwoehlke-kitware** [containers/podman#11472]
/kind bug

### Description
An interrupted `podman build` leaves artifacts that are very difficult to clean up. Variations on `prune` don't work, and `image rm` complains about images "in use by a container". These can only be cleaned up by `--force`, and by listing every single individual image (there can be quite a few!).

### Steps to reproduce the issue:
1. podman build .
2. ctrl-C
3. podman image prune

(Just about any `Dockerfile` will suffice. I reproduced using several `RUN sleep 1` statements and `FROM ubuntu:bionic`, but any base image with `sleep` will likely work.)

### Describe the results you received:
Nothing is pruned, and many artifacts are left "dangling".

### Describe the results you expected:
All artifacts from the aborted `build` are removed.

### Additional information:
This was previously reported as #7889 (back in 2.0!) but does not appear to be resolved in any way, and I was asked to open a new Issue. While buildah is obviously involved, it's unclear that the fault lies entirely with buildah, or if this needs changes on the Podman end to also know about leftover buildah containers / images. (If this should rather be a buildah bug, I am happy to migrate it.)

I have not tested the latest version, but Fedora is only a single point release behind. I did not immediately find anything of relevance in the [Troubleshooting Guide](https://github.com/containers/podman/blob/master).

### Output of `podman version` and `rpm -q podmon`:
```
podman version 3.3.0
podman-3.3.0-1.fc33.x86_64)
```

**Comment by flouthoc** [comment]
@mwoehlke-kitware Thanks for creating the issue i think we can have `--external`  with **prune** or  **rm** that should clean up all the external containers.

**Comment by mwoehlke-kitware** [comment]
Yeah, I could live with needing to remember `--external`. (Any chance an environment variable or config file could make that default behavior?) What's important is not having to enumerate individual images.

**Comment by rhatdan** [comment]
What command would you want to have --external on by default?  All of them?

**Comment by vrothberg** [comment]
I think that --external should be turned off by default (to preserve behavior) but, as @mwoehlke-kitware suggested, make the default configurable (e.g., in containers.conf).

@rhatdan @mwoehlke-kitware if you folks are cool with it, I can start doing the necessary plumbing.

**Comment by rhatdan** [comment]
SGTM

**Comment by vrothberg** [comment]
Here are two PRs to address the issue:
* c/common: https://github.com/containers/common/pull/785
* c/podman: https://github.com/containers/podman/pull/11737
