### ISSUE TITLE
MacOS: When a connection has an SSH identity file, podman-remote always ignores ssh-agent

### ISSUE THREAD

**Issue by tashian** [containers/podman#11470]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When a `podman-remote` connection has an identity file associated with it, it will always ask for the private key password for that identity, even if the key is loaded in the SSH agent.

**Steps to reproduce the issue:**

1. On macOS, add a connection with an SSH identity file that has a password.

2. Add that SSH identity to the SSH agent using `ssh-add`.

3. Run `podman info` and see that it asks for the private key password.

**Describe the results you received:**

`podman` always asks for the SSH key's password.

**Describe the results you expected:**

I expected it to behave like `ssh`: When running `ssh -i`, the SSH agent is queried first, and if the desired key is present there then it is used.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.17
Built:        Mon Aug 30 12:15:26 2021
OS/Arch:      darwin/arm64

Server:
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.16.6
Built:        Mon Aug  2 12:39:21 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.21.3
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.29-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: '
  cpus: 64
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: localhost
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.13.7-200.fc34.x86_64
  linkmode: dynamic
  memFree: 7681679360
  memTotal: 8301727744
  ociRuntime:
    name: crun
    package: crun-0.20.1-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.20.1
      commit: 0d42f1109fd73548f44b01b3e84d04a279e99d2e
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.9-1.fc34.x86_64
    version: |-
      slirp4netns version 1.1.8+dev
      commit: 6dc0186e020232ae1a6fcc1f7afbc3ea02fd3876
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 0
  swapTotal: 0
  uptime: 2m 47.85s
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.3
  Built: 1627933161
  BuiltTime: Mon Aug  2 19:39:21 2021
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.2.3

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.2.3-2.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Comment by mheon** [comment]
@ashley-cui PTAL

**Comment by jwhonce** [comment]
The existing code is working as expected. We prompt for the password to decode the identity file using the golang ssh library. If you have the same key in your ssh-agent, we default to that copy. We would need to research the golang ssh library bindings to see if we can get the sha256 fingerprint from an identity file without the passphrase.

**Comment by rhatdan** [comment]
@ashley-cui @jwhonce Any progress on this?

**Comment by rhatdan** [comment]
@jwhonce is this a ssh verssus go-ssh problem?

**Comment by tashian** [comment]
If I'm reading the code properly, I think [this `sshClient` function](https://github.com/containers/podman/blob/2df9bdc00948e24855f3da42e31a6d273861e380/pkg/bindings/connection.go#L187) first makes an ordered list of client identities to present to the SSH server, starting with the passed-in identity and then adding SSH agent identities.

Then it attempts to dedup the list based on sha256 fingerprint.
There's a comment seems to indicate that agent keys will be preferred over an identity file at this step ("`Dedup signers based on fingerprint, ssh-agent keys override CONTAINER_SSHKEY`").

My hunch is, either there's a bug in that deduping code, or the private key password prompt is presented before `sshClient` is even run.

**Comment by jwhonce** [comment]
@umohnani8 @cdoern was going to look into this, but I think his suggested change would ignore the agent completely if the identity file was given.
