### ISSUE TITLE
Machines created by `podman machine` must alter registries.conf

### ISSUE THREAD

**Issue by mheon** [containers/podman#11489]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

At present, `podman-remote` does not properly support short name prompting. The VMs created by `podman machine` presently use FCOS based on F34, which includes a `registries.conf` that enforces shortname prompting. The combination of these two renders shortnames unusable with machines created by `podman machine` at present.

After some discussion, the team decided on a temporary workaround of changing `registries.conf` to only have a single search registry for VMs created by `podman machine`: `docker.io`. This will remove the need for prompting as there will be no ambiguity. In the future we will investigate a more permanent solution that allows `podman-remote` to prompt (while not requiring the Docker-compatible API to do so).

**Comment by afbjorklund** [comment]
I got "lucky" while testing, since the image was covered by the hard-coded list

**Comment by afbjorklund** [comment]
Was there another issue already, on how to handle the prompting over remote ?

**Comment by rhatdan** [comment]
Nope we need one for that as well.  We are talking about multiple different steps to fix this long term.

**Comment by vrothberg** [comment]
I suggest dropping a config into `/etc/containers/registries.conf.d/` with the following content:
```TOML
unqualified-search-registries = ["docker.io"]
```

Cc: @mtrmac

**Comment by vrothberg** [comment]
I gave it a shot in https://github.com/containers/podman/pull/11498

**Comment by vrothberg** [comment]
For the record: the same issue applies when using Podman/Buildah without having access to a TTY (e.g., in a build pipeline) when the short-name mode is set to enforcing. That was the trade-off for increasing security. It is hence not entirely limited to remote.

Getting prompting to work over the libpod endpoints will increase the interactive experience when using podman-remote but the core issue still persists when using the remote API in a non-interactive fashion (without podman-remote) or using the compat API.

**Comment by rhatdan** [comment]
That is understood, we are trying to help out Humans though and not robots.  Robots can more easily be fixed the humans.
