### ISSUE TITLE
suggest a --replace flag for play kube

### ISSUE THREAD

**Issue by chenzhiwei** [containers/podman#11481]
/kind feature

**Description**

* podman kube create -f k8s-manifests.yaml
* podman kube apply -f k8s-manifests.yaml
* podman kube delete -f k8s-manifests.yaml

**Comment by rhatdan** [comment]
Please further explain or open PRs to examine.
@haircommander @mrunalp WDYT?

**Comment by haircommander** [comment]
the `create` and `apply` commands are done with `podman play kube`, and `delete` was added with `podman play kube --down`

are you just looking for an alias between the two sets of commands?

**Comment by chenzhiwei** [comment]
@haircommander something similar.

* create just creates the manifests, return error if already exist
* apply pulls the images in the manifests, if new images or containers detected, apply the new images to the manifests
* delete means deleting the manifests

**Comment by haircommander** [comment]
Ah so you'd like podman behaving like api server/etcd, rather than kubelet/runtime which is closer to how it's behaving now. What use case are you looking to fill? I can't think of a use of  keeping track of the underlying manifest if the pod/containers is what podman typically thinks about

**Comment by chenzhiwei** [comment]
one of the container use `latest` tag image, can podman now support update the image to the real `latest` one?

**Comment by flouthoc** [comment]
@chenzhiwei I dont think that even `k8s` supports that you can have a `image pull policy`  as `always` on deployment and `k8s` will only update image if pod is restarted. You can have similar pull policy on `podman pods` but afaik they need to be restarted.

**Comment by chenzhiwei** [comment]
@flouthoc Thank you.

What about introducing a new flag `--replace` to play kube?

I think my core requirement is apply the new changes from both my manifest file and the images inside it.

If the pod already exists, delete and re-create it, this can trigger the image refresh if the pull policy is always or image tag is `latest`. If no pod found, create one.

**Comment by rhatdan** [comment]
That makes some sense to me.  @baude @mheon WDYT?

**Comment by mheon** [comment]
A `--replace` flag SGTM
