### ISSUE TITLE
run --mount has no equivalent to -v :U

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#11491]
In docker, the only difference between --mount and -v is [that the latter creates a directory, if it was not born](https://docs.docker.com/storage/bind-mounts/#differences-between--v-and---mount-behavior).

As far as I can see, `podman run` introduces another difference: -v has the option `:U` :
> The :U suffix tells Podman to use the correct host UID and GID based on the UID and GID within the container, to change recursively the owner and group of the source volume.

While `podman run --mount type=bind` does not have this option.

**Comment by rhatdan** [comment]
@EduardoVega PTAL

**Comment by rhatdan** [comment]
@dilyanpalauzov Interested in opening a PR?

**Comment by dilyanpalauzov** [comment]
I cannot fix this.

**Comment by rhatdan** [comment]
No problem.  I will see if Eduardo has time to work on it. or any other contributor. If that does not work, we can get someone from the core team to look at it.  Probably not a big deal.
What error do you see when you add a :U to podman run --mount

**Comment by EduardoVega** [comment]
@rhatdan I can take this one. If I'm not wrong support for :U was not added for --mount flag

**Comment by rhatdan** [comment]
You got it.
