### ISSUE TITLE
podman 3.2.3 search seems to ignore REGISTRY_AUTH_FILE on RHEL 8.4

### ISSUE THREAD

**Issue by zubcevic** [containers/podman#11501]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

If you are using an environment variable REGISTRY_AUTH_FILE to store auth.json in a custom directory, podman search ignores it and throws:
```
ERRO[0000] error getting search results from v2 endpoint "xxxx": unable to retrieve auth token: invalid username/password: unauthorized: access to the requested resource is not authorized
```

**Steps to reproduce the issue:**

1.
REGISTRY_AUTH_FILE=./auth.json

2.
podman login xxxx

3.
podman search xxxx/yyy

**Describe the results you received:**
ERRO[0000] error getting search results from v2 endpoint "xxxx": unable to retrieve auth token: invalid username/password: unauthorized: access to the requested resource is not authorized

**Describe the results you expected:**
Expected a list of the containers in namespace yyy

**Additional information you deem important (e.g. issue happens only occasionally):**
The REGISTRY_AUTH_FILE is picked up properly for login, pull and push. Just not for search. Of course it is only noticed for private registries that require login for search etc.

**Output of `podman version`:**

```
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.15.7
Built:        Tue Jul 27 09:29:39 2021
OS/Arch:      linux/amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes, checked the guide and the release notes of later releases. Can't test on higher version right now.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Workaround**

The environment variable XDG_RUNTIME_DIR is picked up, but then I would need additional variables just for the search. 
XDG_RUNTIME_DIR=/home/test/podman
REGISTRY_AUTH_FILE=$XDG_RUNTIME_DIR/containers/auth.json
podman login xxxx
podman search xxxx/yyy

If you set the REGISTRY_AUTH_FILE to ./auth.json it would still be ignored and break the search while still working login/pull/push

**Comment by rhatdan** [comment]
It looks to me like it is all wired up correctly in the main branch.
Could you test against main?

If not could you see what `podman search --help | grep auth` shows

**Comment by zubcevic** [comment]
The output is:
```
--authfile string   Path of the authentication file. Use REGISTRY_AUTH_FILE environment variable to override
```
Also using this --authfile itself is ignored for podman search

**Comment by zubcevic** [comment]
Here is a test that shows the problem on a RHEL8.4 podman 3.2.3 environment (tested with a local private container registry that requires logon):
```
podman pull docker.io/webgoat/goatandwolf
podman tag docker.io/webgoat/goatandwolf:latest localhost:5000/webgoat:latest
podman logout localhost:5000 #just make sure that there is no auth.json file in the default location

export REGISTRY_AUTH_FILE=./auth.json
podman login localhost:5000 --tls-verify=false
podman push localhost:5000/webgoat:latest --tls-verify=false
podman pull localhost:5000/webgoat --tls-verify=false
podman search localhost:5000/webgoat --tls-verify=false #returns the error
```
So all commands go fine, except for the search

**Comment by zubcevic** [comment]
The same test on a Fedora 34 linux VM with podman 3.1.0 or 3.3.1 shows no Errors. 
So strangely related to RHEL 8.4

**Comment by zubcevic** [comment]
I'll close the issue for now as it looks to be related to the package as delivered by RHEL

Installed Packages
podman.x86_64                                 3.2.3-0.10.module+el8.4.0+11989+6676f7ad                                  @rhel-8-for-x86_64-appstream-rpms
