### ISSUE TITLE
[Feature Request] Addition of "--quiet" flag Where Applicable

### ISSUE THREAD

**Issue by p0da** [containers/podman#11515]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Would it be possible to add a --quiet flag to various commands that would prevent any output to stdout? For example both `podman stop` and `podman rm` would be good candidates. Of course one can always `&> /dev/null` but there are instances where that is not available i.e running podman without using a shell.

**Comment by rhatdan** [comment]
The --quiet option usually stops progress output.  But for those tools that do not currently have --quiet, I have no problem with that change.

I am not sure it is customary to block stderr on --quiet though.

**Comment by Rayqan** [comment]
Personally I have seen behavior vary between tools. Perhaps --quiet by default could only block stdout while something like --quiet=stderr or --quiet=both would also block stderr.

**Comment by rhatdan** [comment]
That is a difficult change, since --quiet is a boolean,  Getting CLI Processor to handle something like that would be difficult.

**Comment by p0da** [comment]
Of course if it prohibitively difficult just stopping output to stdout will suffice. However having both would be nice to have.
