### ISSUE TITLE
healthcheck status should be suffix to podman ps status field

### ISSUE THREAD

**Issue by jwhonce** [containers/podman#11527]
For compatibility, the podman ps should include the healthcheck status in the Status field when the container has been configured with a healthcheck.

Expected output:
```
$ podman ps
CONTAINER ID  IMAGE  STATUS                  NAMES
d53529ca4c93  fedora Up 4 minutes (healthy)  sweet_potato
```
Actual output:
```
$ podman ps
CONTAINER ID  IMAGE  STATUS        NAMES
d53529ca4c93  fedora Up 4 minutes  sweet_potato
```

This is as of podman 3.1.2.
I assume this will require database changes to store the last healthcheck run.

**Comment by mheon** [comment]
We already store recent HCs (`podman inspect` will show details) so this shouldn't be difficult.

**Comment by sankalp-r** [comment]
@jwhonce @mheon 
I would like to work on this issue.
Can you please guide me to the right direction?
