### ISSUE TITLE
XDG_RUNTIME_DIR is pointing to a path which is not writable. Most likely podman will fail

### ISSUE THREAD

**Issue by Luap99** [containers/podman#11521]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

All integration test logs now have this warning for each podman command
`time="2021-09-10T08:35:26Z" level=warning msg="XDG_RUNTIME_DIR is pointing to a path which is not writable. Most likely podman will fail."`

**Steps to reproduce the issue:**
Look at any recent integration test logs (rootless).

**Describe the results you expected:**
This warning should not be there. It makes it impossible to exactly match output.

**Comment by Luap99** [comment]
@flouthoc PTAL
cc @edsantiago

**Comment by flouthoc** [comment]
@Luap99 hmm this is a weird blocker , should we have a quit flag for tests ? as this warning was specifically meant for users. I'll check this. Thanks for creating this issue.

We can de-escalate this to debug log but then the whole purpose of warning would go away.

Btw this is only triggered 
* Session is rootless && cgroupv2 && systemdsession is invalid && XDG_RUNTIME_DIR is not writable

**Comment by flouthoc** [comment]
Also curious about how did CI pass for this I guess any of the old tests are not doing exact match in this specific case. Except for changes in this PR right https://github.com/containers/podman/pull/11513 @Luap99 ?

**Comment by Luap99** [comment]
This is cluttering the logs with useless warnings. This is big problem for me. I am sure @edsantiago agrees. 
The test are running successfully, that means that we are given a warning if there is no error! Yes the STDERR output is almost never checked in tests so this passed in your PR without problems. However some test might require to check for no output on STDERR like my PR.

Why is this warning shown in CI tests, the runroot is obviously writeable. I think the problem is that the directory does not exist when the check is made but podman will automatically create it at a later point.

**Comment by flouthoc** [comment]
@Luap99 This makes sense we can create the dir if it does not exists or move the check just after the directory is created. That should suppress warning for most of the cases.

**Comment by Luap99** [comment]
Why do we check the systemd session or cgroupv2? I think we should just check if the dir is writable. As long as the dir is not writable people will always run into problems.

**Comment by flouthoc** [comment]
@Luap99 Podman fall backs to temp and things work out fine in most of the cases when its `cgroup v1`

**Comment by flouthoc** [comment]
since everything falls back to cgroup fs

**Comment by flouthoc** [comment]
Some of the key points are discussed here as well https://github.com/containers/podman/pull/11327

**Comment by giuseppe** [comment]
@flouthoc this is not a serious issue.  You don't have to look at it during your day off.

I'll take a look at it

**Comment by flouthoc** [comment]
thanks @giuseppe @Luap99 :)
