### ISSUE TITLE
Race conditions with gvproxy when starting podman machine

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman#11532]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

It looks like qemu and gvproxy are racing towards the tunneled ssh port, which causes `Start` to fail.

**Steps to reproduce the issue:**

1. `podman machine start`

2. `podman machine ssh`

3.

**Describe the results you received:**

`tcpproxy: for incoming conn [::1]:49996, error dialing "192.168.127.2:22": connect tcp 192.168.127.2:22: connection was refused`

`Error: exit status 255`

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 4.0.0-dev
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

macOS

**Comment by afbjorklund** [comment]
Problem encountered when trying to run ssh commands right after start.

**Comment by mheon** [comment]
@baude PTAL

**Comment by guillaumerose** [comment]
`podman machine start` doesn't wait for SSH to be up and running but checks if a serial console is working. Hence the described behavior.

Perhaps we could poll the status with `podman ps`. With this, we will be sure, podman is up and running when start command ends.

**Comment by Luap99** [comment]
Yes, I think it would be the best to check that the podman socket is up and working.

**Comment by afbjorklund** [comment]
I wanted to use the ssh connections for mounts, so I don't really care about the status of the podman service (or socket).

Issuing the commands (mkdir + mount) over the serial console would also be fine, in case ssh won't "work". Looked at QMP

**Comment by rhatdan** [comment]
@baude What is going on with this one?

**Comment by Luap99** [comment]
I think we can add `After=sshd.service` to the ready unit: https://github.com/containers/podman/blob/8430ffc72e74f1271174984674a1c2ee6118779e/pkg/machine/ignition.go#L82

**Comment by rhatdan** [comment]
Please open a PR?

**Comment by Luap99** [comment]
PR #12314
