### ISSUE TITLE
The path to gvproxy is hardcoded to /usr/libexec/podman

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman#11531]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The path is hardcoded, which becomes a problem on systems that don't have it.

Such as Debian (/usr/lib/podman) or macOS (/usr/local/bin). It should be config ?

**Steps to reproduce the issue:**

1. `podman machine start`

2.

3.

**Describe the results you received:**

`Error: unable to start host networking: "start /usr/libexec/podman/gvproxy: no such file or directory"`

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

Looked like a known problem:

```go
       // TODO we may wish to configure the directory in containers common
        binary := filepath.Join("/usr/libexec/podman/", machine.ForwarderBinaryName)
```

**Output of `podman version`:**

```
podman version 4.0.0-dev
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

macOS

**Comment by mheon** [comment]
This is exclusively a problem on main. The v3.3 branch uses different logic, which I believe @baude is going to forward-port to the main branch.

**Comment by afbjorklund** [comment]
Oh, I didn't know you dis development on the branch

**Comment by afbjorklund** [comment]
Duplicate of Issue #11226

**Comment by afbjorklund** [comment]
Apparently the debian packages still install in `/usr/libexec`, even if it is against the FHS policy.

* https://packages.debian.org/sid/amd64/catatonit/filelist
