### ISSUE TITLE
Deadlink in documantation of podman-pull

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#11535]
The bottom of https://docs.podman.io/en/latest/markdown/podman-pull.1.html contains a link:

containers-transports(5) → https://github.com/containers/image/blob/main/docs/containers-transports.5

The destination does not exist.

**Comment by mheon** [comment]
That actually exists in c/image - https://github.com/containers/image/blob/main/docs/containers-transports.5.md

Mind opening a PR to change the link to point there?

**Comment by dilyanpalauzov** [comment]
No, I am not willing to open PR.

**Comment by Luap99** [comment]
The link is actually correct in the man page. Something in the sphinx conversion process removed the .md suffix.

**Comment by giuseppe** [comment]
it seems to work now:

```
$ wget --spider -r -nd -nv -H -l 1 -o- https://docs.podman.io/en/latest/markdown/podman-pull.1.html | grep -i broken
Found no broken links.
```
