### ISSUE TITLE
Ability to map CNI networks to user-configurable interface names inside containers

### ISSUE THREAD

**Issue by ettoredn** [containers/podman#11534]
/kind feature

Could you consider the ability to map networks to specific interface names inside the container? From what I can see right now every interface is simply named `eth<id>`.

A simple use case for this is running a DHCP client on an macvlan interface from inside the container. By mapping a network to a predictable interface name, there would be more assurance on which interface/network it is run. Moreover, this would also become handy when there is the need to bind certain services to specific networks only.

**Comment by mheon** [comment]
Can you give an example of what you would like the interfaces to be named?

**Comment by Luap99** [comment]
That should be possible with CNI but how should the UI look like? I would prefer to not have an extra cli flag.

**Comment by ettoredn** [comment]
Had a quick look at [CRI-O](https://github.com/cri-o/ocicni/blob/95ad096688fd4609233f8ed30b798cfbe29c3c95/pkg/ocicni/types.go#L107) and there already is support for it (also look around for `CNI_IFNAME` env). 

IMO the best design would be as simple as adding a "ifname" key to the network `.conflist`.

@mheon does it matter what name I'd like to set it to? In the current configuration i'm dealing with the name is `tcloud`.

**Comment by mheon** [comment]
Ah, so the ask is for the interface name to be user-configurable.

**Comment by Luap99** [comment]
The problem is we support n networks for a container, so `CNI_IFNAME` env does not work. Adding it to the conflist file is out of our control and I doubt that the CNI maintainers would like this.
I know that this is easy to set in the networking code. The problem is the frontend IMO. I just don't see a good UI at the moment.

**Comment by mheon** [comment]
We could do something similar to what we used to do for static IP and IPv6, where they're only supported with the CNI backend if you only join a single network - the user experience for that is bad, but not unusable.
