### ISSUE TITLE
podman run silently succeeds when container command exits with code 125

### ISSUE THREAD

**Issue by martinpitt** [containers/podman#11540]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`podman run` succeeds with exit code 0 if command inside fails with code 125. This error code is [used by meson](https://github.com/mesonbuild/meson/commit/185238fdb479e2f7007ccda47e59b65557b7ee4b) in case of failures. In CI these two behaviours mean that [failing builds like this](https://github.com/martinpitt/umockdev/runs/3578829033?check_suite_focus=true) are silently shown as green, as the exit code is not propagated properly.

**Steps to reproduce the issue:**

1. `podman run registry.fedoraproject.org/fedora sh -c 'exit 125'; echo $?`

**Describe the results you received:**

Exits with code 0

**Describe the results you expected:**

Exits with non-zero, preferably 125. `man podman-run` describes 125 as "The error is with Podman itself", so it may seem legit to change error 125 of the wrapped command into something else, but *anything except zero*.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is not specific to the container image. It happens with e.g. `docker.io/alpine` as well. Exit codes 1, 124, 126 etc. behave correctly.

**Output of `podman version`:**

```
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.6
Built:        Mon Aug 30 22:46:36 2021
OS/Arch:      linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.3.1-1.fc34.x86_64
```

**Comment by mheon** [comment]
@rhatdan PTAL
