### ISSUE TITLE
Feature Request: Explicitly specifying which podman config file to use.

### ISSUE THREAD

**Issue by gravypod** [containers/podman#11543]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I'm a maintainer on [rules_docker](https://github.com/bazelbuild/rules_docker) and I've recently been looking into using `podman` to run rootless containers in sandboxed tests. To run containers in a Bazel test I'd need to make sure that my container runtime:

1. Does not store data in file paths I don't tell it about.
2. Avoids all network traffic (uses only the local file system).
3. Can be provided a deadline.

I think 2 & 3 in this list are possible. `podman system service` takes `--time` and if all of the containers exist in Podman's storage no network traffic should be done. Something that I'm concerned about is 1. It doesn't seem possible to really control which config file is used by `podman`. Are there any ways I can tell podman "Only read/write into `./data/podman`?"

Also, rather than executing podman through the command line, is there a way to link podman into a golang program and start the API programatically?

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

1. Bazel [Rule Docs](https://docs.bazel.build/versions/main/skylark/rules.html)
2. Bazel [action environment](https://docs.bazel.build/versions/main/skylark/rules.html#actions)

**Comment by mheon** [comment]
I can't comment on the config file bits (I'll leave @vrothberg and @rhatdan to that), but I believe you are misunderstanding the timeout flag for `podman system service`. It is not a maximum time that the service is alive, but length of time since the last active connection after which `podman system service` will exit. Podman does offer a timeout flag for individual containers, but there is presently no mechanism to timebox all Podman operations.

**Comment by rhatdan** [comment]
You can set a CONTAINERS_CONF environment variable to point at a particular container.confm but I am not sure if that totally makes sense.  You can also run containers with the --read-only flag, which prevents containers from writing  to anything except tmpfs or volumes mounted in.

**Comment by gravypod** [comment]
@rhatdan thanks, `CONTAINERS_CONF` is exactly what I was looking for. I'm making this issue as closed.

**Comment by rhatdan** [comment]
Great.
