### ISSUE TITLE
podman system df shows much less disk usage than du /var/lib/containers/storage

### ISSUE THREAD

**Issue by nivekuil** [containers/podman#11544]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. use podman, run `podman system prune`

2. run `podman system df` and check the size of /var/lib/containers/storage, notice a big difference

**Describe the results you received:**
on one machine
```
podman system df
TYPE           TOTAL       ACTIVE      SIZE        RECLAIMABLE
Images         17          16          2.571GB     350.7MB (0%)
Containers     38          37          342.5MB     0B (0%)
Local Volumes  31          16          2.462GB     524.3kB (0%)
```

```
du -hs /var/lib/containers/storage/        
13G	/var/lib/containers/storage/
```
```
du -hs --apparent-size /var/lib/containers/storage/ 
11G	/var/lib/containers/storage/
```
on another
```
~# podman system df
TYPE           TOTAL       ACTIVE      SIZE        RECLAIMABLE
Images         9           9           1.485GB     0B (0%)
Containers     23          19          2.476MB     8.001kB (0%)
Local Volumes  9           7           387.8MB     0B (0%)
~# du -hs /var/lib/containers/storage
6.3G	/var/lib/containers/storage
```

**Describe the results you expected:**
should be about the same size?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.15.13
Built:        Tue Aug 10 22:05:24 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
      go: go1.15.13
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCA
P,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 555892736
  swapTotal: 2147475456
  uptime: 278h 13m 18.22s (Approximately 11.58 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 38
    paused: 0
    running: 37
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 17
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.2.3
  Built: 1628633124
  BuiltTime: Tue Aug 10 22:05:24 2021
  GitCommit: ""
  GoVersion: go1.15.13
  OsArch: linux/amd64
  Version: 3.2.3
```

**Comment by rhatdan** [comment]
@nalind PTAL

**Comment by giuseppe** [comment]
could you run `find /var/lib/containers/storage/` and share the output?

**Comment by nivekuil** [comment]
It seems like there may be stuff in the `find` output that is better off not public but I am happy to share it privately. 

I wonder if this issue is already known, as suggested by https://access.redhat.com/solutions/5822921 (to which I do not have access)

**Comment by giuseppe** [comment]
are there containers running when you run `du`?

Do you get the same result if you add `--one-file-system` to `du`?

**Comment by nivekuil** [comment]
> are there containers running when you run du?
yes

> Do you get the same result if you add --one-file-system to du?
It's closer, but still not quite matching:

~# podman system df
TYPE           TOTAL       ACTIVE      SIZE        RECLAIMABLE
Images         25          18          3.629GB     1.05GB (0%)
Containers     39          38          409.5MB     0B (0%)
Local Volumes  34          18          3.734GB     655.4kB (0%)

~# du -hs /var/lib/containers/storage/
19G	/var/lib/containers/storage/

~# du -hs --apparent-size /var/lib/containers/storage/
16G	/var/lib/containers/storage/

~# du -hs --one-file-system --apparent-size /var/lib/containers/storage/
9.7G	/var/lib/containers/storage/

**Comment by rhatdan** [comment]
SInce no response, I am going to assume it is fixed, reopen if I am mistaken.
