### ISSUE TITLE
/libpod/images/prune endpoint does not support the dangling filter

### ISSUE THREAD

**Issue by jelly** [containers/podman#11576]
/kind bug

**Description**

The `/libpod/images/prune` endpoint does not remove unused images.

**Steps to reproduce the issue:**

1. Have some unused images

2.  ```curl -X POST -g --no-buffer --unix-socket /run/user/1000/podman/podman.sock 'http://localhost/v1.12/libpod/images/prune?filters={"dangling":["true"]}'```

**Describe the results you received:**

```
null
```

**Describe the results you expected:**

Unused images are removed.

**Additional information you deem important (e.g. issue happens only occasionally):**

Dangling support is not implemented yet in the code, the filters are removed https://github.com/containers/podman/blob/main/pkg/api/handlers/libpod/images.go#L177

**Output of `podman version`:**

```
podman version 3.3.1
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.22.3
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.0.29-1
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 7e6de6678f6ed8a18661e1d5721b81ccee293b9b'
  cpus: 8
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: natrium
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.2-arch1-2
  linkmode: dynamic
  memFree: 1482002432
  memTotal: 31471919104
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.0-1
    path: /usr/bin/crun
    version: |-
      crun version 1.0
      commit: 139dc6971e2f1d931af520188763e984d6cdfbf8
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.1.12-1
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 6066733056
  swapTotal: 7867977728
  uptime: 82h 40m 46.13s (Approximately 3.42 days)
registries: {}
store:
  configFile: /home/jelle/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /home/jelle/.local/share/containers/storage
  graphStatus:
    Build Version: 'Btrfs v5.13.1 '
    Library Version: "102"
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /home/jelle/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.1
  Built: 1630517266
  BuiltTime: Wed Sep  1 19:27:46 2021
  GitCommit: 4c5283fabff2de5145838f1847a5a7b2b1fbc0a5-dirty
  GoVersion: go1.17
  OsArch: linux/amd64
  Version: 3.3.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
pacman -Q podman
podman 3.3.1-1
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Comment by baude** [comment]
@jwhonce @cdoern do the right thing here. I am too far removed from it.  We can also discuss in water cooler tomorrow if there is any open questions ...

**Comment by cdoern** [comment]
@vrothberg not sure, I really think this is an example of just some necessary code removal, `--dangling` does not seem to do anything cc/ @jwhonce @baude

**Comment by rhatdan** [comment]
We have been carrying this for a year, is "danglng" documented somewhere when it comes to prune?
```
$ podman image prune --help
Remove unused images
Description:

  Removes dangling or unused images from local storage.
```
Passing dangling filter makes no sense.

**Comment by jelly** [comment]
Cockpit-podman has an prune implementation for a while and it does not require the dangling filter option to work so this issue can be closed in my opinion.

**Comment by vrothberg** [comment]
Sounds good, thanks!
