### ISSUE TITLE
Deadlink in https://docs.podman.io/en/latest/markdown/podman-machine.1.html

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#11583]
https://docs.podman.io/en/latest/markdown/podman-machine.1.html shows a link (in the middle):

podman-machine-init(1) → https://docs.podman.io/en/latest/markdown/podman-machine-init.1.md

The destination does not exist

**Comment by Luap99** [comment]
Links inside tables do not work, see https://github.com/ryanfox/sphinx-markdown-tables/issues/18

Feel free to try and find a way to make it work.

**Comment by rhatdan** [comment]
It looks like all the code needs to do is substitute the *.md with *.html, and it would work?

**Comment by rhatdan** [comment]
Do we have tools that generate this or does it happen elsewhere?
@TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
This is interesting.  I ran into this about 10 days ago, but then couldn't find this page with the bad links again.

If you go to https://docs.podman.io, and then click on the "Commands" link on the left side of the page, you'll get to:  https://docs.podman.io/en/latest/Commands.html.  If you then scroll down on that commands page and click on the "machine" link, it takes you to:  https://docs.podman.io/en/latest/machine.html.  The links on this page work fine and there is no table displayed.  (https://docs.podman.io/en/latest/markdown/podman-machine-init.1.html)

The difference is the "markdown" directory is part of the link that you provided for the machine page.  (https://docs.podman.io/en/latest/markdown/podman-machine.1.html )

@dilyanpalauzov , do you recall how you got to that particular podman-machine page?  I'm thinking we have a bad link somewhere that I'd like to track down.  All of this is auto-generated for us, but we may be able to tweak things.

Thanks for sending this along, I thought I just had a bad cache on my browser last weekend as I couldn't replicate, now I'm thinking we might have something to fix.

**Comment by dilyanpalauzov** [comment]
I asked Google for “podman machine”.

**Comment by rhatdan** [comment]
Yup #2 link on google "podman machine" is
https://docs.podman.io/en/latest/markdown/podman-machine.1.html
Which has the bad links.

**Comment by Luap99** [comment]
Again, every table on docs.podman.io contains broken links , the `sphinx-markdown-tables` extension is used to convert the markdown tables to html. https://github.com/containers/podman/blob/9119a578e782b92bd344f093f5491c318bc20d69/docs/source/conf.py#L32
The extension does not convert links. I looked at this before but did not find a easy solution in a timely manner.

**Comment by rhatdan** [comment]
Well I think this should be raised in priority, since the first page anyone goes to from google has broken links.

Could we do something like
https://github.com/ryanfox/sphinx-markdown-tables/issues/18#issuecomment-496789373

And just post process the html and sed all html://.*md -> html://.*html

**Comment by rhatdan** [comment]
Man pages are all straightened out now. Check them out.

**Comment by TomSweeneyRedHat** [comment]
@dilyanpalauzov thanks again for the issue report and the follow-up.  It made it a lot easier for us to track it down.

**Comment by lanctot** [comment]
> And just post process the html and sed all html://.*md -> html://.*html

Hi @rhatdan, is this the solution you chose? (I'm having the same problem in our project.) If so, do you have a working configuration of a sphinx build on Read the Docs? I'm having issues trying this solution, but only on Read the Docs, details here: https://stackoverflow.com/questions/73455350/how-to-modify-documentation-built-with-sphinx-via-a-script-in-readthedocs-build

**Comment by Luap99** [comment]
@lanctot we use sphinx + readthedocs: https://github.com/containers/podman/blob/main/docs/source/conf.py

**Comment by lanctot** [comment]
> @lanctot we use sphinx + readthedocs: https://github.com/containers/podman/blob/main/docs/source/conf.py

Thanks! I found a bypass solution to my problem described here: https://stackoverflow.com/questions/73455350/how-to-modify-documentation-built-with-sphinx-via-a-script-in-readthedocs-build
