### ISSUE TITLE
Cannot set sysctl net.unix.max_dgram_qlen

### ISSUE THREAD

**Issue by konfiot** [containers/podman#11588]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. run a conteainer with parameters `--sysctl net.unix.max_dgram_qlen=1024`

**Describe the results you received:**

```
Error: open /proc/sys/net/unix/max_dgram_qlen: No such file or directory: OCI not found
```

**Describe the results you expected:**

Container starting with correct parameters

**Additional information you deem important (e.g. issue happens only occasionally):**

This works with docker but not with podman

**Output of `podman version`:**

```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.9
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.6
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 16
  distribution:
    distribution: debian
    version: "11"
  eventLogger: journald
  hostname: node2
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.0-8-amd64
  linkmode: dynamic
  memFree: 6980669440
  memTotal: 33681297408
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.4.0
  swapFree: 1022357504
  swapTotal: 1023406080
  uptime: 340h 55m 49.42s (Approximately 14.17 days)
registries:
  registry.local.wandercraft.eu:5000:
    Blocked: false
    Insecure: true
    Location: registry.local.wandercraft.eu:5000
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: registry.local.wandercraft.eu:5000
store:
  configFile: /home/arthur.toussaint/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 1
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.10.3
        fuse-overlayfs: version 1.4
        FUSE library version 3.10.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/arthur.toussaint/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 3
  runRoot: /run/user/1000/containers
  volumePath: /home/arthur.toussaint/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.9
  OsArch: linux/amd64
  Version: 3.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/stable,now 3.0.1+dfsg1-3+b2 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Comment by konfiot** [comment]
Also, I tried to put the correct parameters on the host, but they don't get honored in the container

**Comment by mheon** [comment]
`    rootless: true`

That's probably the cause. I imagine you were running Docker as root, and are not running Podman rootless? I'm not the most familiar with what sysctls are allowed and disallowed without root, but it seems logical to assume that this is a root-only sysctl. Have you tried running Podman as root?

**Comment by konfiot** [comment]
Nope, will do, it would make sense...
Although what surprised me is that the hosts parameters were not honored in the container
If I run my container with `--network=host` it works though, but I would prefer not using that option

**Comment by giuseppe** [comment]
that setting is exposed from the kernel only when the network namespace is owned by the initial user namespace (i.e. not running in a user namespace).

I'd expect it to fail with root Podman or Docker also when they are creating a user namespace.

**Comment by konfiot** [comment]
I understand that, but again, what surprises me is that If I set it correctly system-wide in the kernel (outside of podman), then this setting is not honored inside podman containers =/

**Comment by rhatdan** [comment]
That is because you are in a different user namespace.  But this could be a kernel bug.  If this is not applied to the new network namespace.
