### ISSUE TITLE
podman --remote pull oci-archive:….tar gives up

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#11593]
I have podman 3.3.1 and minikube version 1.23.0.  I call
```
$ minikube start --container-runtime=cri-o
$ eval $(minikube podman-env)
$ podman pull oci-archive:ldap-2021-09-15.tar
Getting image source signatures
Copying blob 7e2ef1512247 done  
Copying config 80cf270784 done  
Writing manifest to image destination
Storing signatures
80cf270784576d867d9bb447ccf3e135aadb97d5803d566115d7179012241d3f
$ podman --remote pull oci-archive:ldap-2021-09-15.tar
Error: unsupport transport oci-archive in "oci-archive:ldap-2021-09-15.tar": only docker transport is supported
```

https://minikube.sigs.k8s.io/docs/handbook/pushing/ says this should work.

As discussed elsewhere, `podman pull oci-archive:...tar` is simpler to cope with, than skopeo-copy, as the former honours the reference/repository/tag annotation.  I want to use podman --remote to push images into minikube.

• `podman --remove pull oci-archive:….tar` shall not fail with “only docker transport is supported”.

**Comment by dilyanpalauzov** [comment]
See also https://github.com/kubernetes/minikube/issues/12479 .

**Comment by rhatdan** [comment]
Does podman load/import (I always forget which one, work?)

**Comment by rhatdan** [comment]
@vrothberg @mtrmac WDYT?

**Comment by dilyanpalauzov** [comment]
```
$ podman --remote load < ./ldap-2021-09-12.tar
Loaded image(s): localhost/2021-09-12:latest
$ minikube image ls
localhost/2021-09-12:latest

$ podman --remote import ./ldap-2021-09-12.tar
sha256:279d69857479cd22a30747162c0d55bd91b86c4fd3097cfbc93151953ba08028

$ minikube image ls
<none>:<none>
```

**Comment by vrothberg** [comment]
Remote pull supports only the docker transport (as the error message indicates). Using `load` is the right thing to do for the remote client.
