### ISSUE TITLE
Install Podman 3.3 on Centos 7

### ISSUE THREAD

**Issue by DaniBet** [containers/podman#11626]
Hello,

Is there any way to install Podman 3.3 on Centos 7? If you install podman in the easiest way on Centos 7 with yum install Podman, you receive version 1.6. Is there 0 interest for Centos?

**Comment by rhatdan** [comment]
Sorry we don't support updates on RHEL7 or Centos 7.  Best you could do is self build.  But you need lots of packages built for that old of an OS. (crun or runc), slirp4netns, fuse-overlayfs, podman, conmon containers-common.

**Comment by DaniBet** [comment]
Is that specified in your documentation?

**Comment by rhatdan** [comment]
You mean the fact that we are not updating RHEL7/Centos7 or how to build all of the components?  
The upstream project does not get into how to get newer packages on any distribution.
https://podman.io/getting-started/installation
has
 RHEL7

Subscribe, then enable Extras channel and install Podman.

sudo subscription-manager repos --enable=rhel-7-server-extras-rpms
sudo yum -y install podman
