### ISSUE TITLE
`podman` fails to relabel volume after mounting it inside container

### ISSUE THREAD

**Issue by mskarbek** [containers/podman#11625]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I would like to declare a set of volumes using `podman volume` based on ZFS datasets. Unfortunately, if I try to use them in container, I can't because `podman` after mounting volume inside container does not relabel it - mount path have `system_u:object_r:unlabeled_t:s0` label (`vol1` example). I can enforce labeling on the mount point in ZFS (`vol2` example) but that will get me only base label, not full container context. This will let me use it, but won't get me full isolation, and I can't declare full label because I don't know full context upfront.
There is no issue if I create and mount a dataset on the host and then use it directly with `-v` without declaring it as a volume in podman (`vol3` example).

**Steps to reproduce the issue:**
```
#!/usr/bin/env bash

zfs create -o mountpoint=legacy a258b6f1-e580-42ea-a79d-c6df33239837/datafs/var/lib/volumes/vol1
zfs create -o mountpoint=legacy -o rootcontext="system_u:object_r:container_file_t:s0" a258b6f1-e580-42ea-a79d-c6df33239837/datafs/var/lib/volumes/vol2
zfs create a258b6f1-e580-42ea-a79d-c6df33239837/datafs/var/lib/volumes/vol3

podman volume create --opt type=zfs --opt device=a258b6f1-e580-42ea-a79d-c6df33239837/datafs/var/lib/volumes/vol1 vol1
podman volume create --opt type=zfs --opt device=a258b6f1-e580-42ea-a79d-c6df33239837/datafs/var/lib/volumes/vol2 vol2

podman run -it\
 -v vol1:/srv/vol1:Z\
 -v vol2:/srv/vol2:Z\
 -v /var/lib/volumes/vol3:/srv/vol3:Z\
 registry.access.redhat.com/ubi8/ubi:8.4 bash
```
**Describe the results you received:**
```
[root@4efc0adb3aa0 /]# cd /srv/
[root@4efc0adb3aa0 srv]# ls -laZ
total 13
drwxr-xr-x.  5 root root system_u:object_r:container_file_t:s0:c13,c783  5 Sep 16 15:23 .
dr-xr-xr-x. 18 root root system_u:object_r:container_file_t:s0:c13,c783 22 Sep 16 12:29 ..
drwxr-xr-x.  2 root root system_u:object_r:unlabeled_t:s0                2 Sep 16 15:23 vol1
drwxr-xr-x.  2 root root system_u:object_r:container_file_t:s0           2 Sep 16 15:23 vol2
drwxr-xr-x.  2 root root system_u:object_r:container_file_t:s0:c13,c783  2 Sep 16 15:23 vol3
[root@4efc0adb3aa0 srv]# 
```

**Describe the results you expected:**
`vol1` should be relabeled 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.15.14
Built:        Tue Aug 10 20:55:16 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.21.3
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.29-1.module_el8.4.0+886+c9a8d9ad.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 97bba1e91aaab5be2e93bacd34ec4e66655a02ae'
  cpus: 2
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: li1356-20.members.linode.com
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-305.19.1.el8_4.x86_64
  linkmode: dynamic
  memFree: 2316226560
  memTotal: 3918147584
  ociRuntime:
    name: runc
    package: runc-1.0.0-74.rc95.module_el8.4.0+886+c9a8d9ad.x86_64
    path: /usr/bin/runc
    version: |-
      runc version spec: 1.0.2-dev
      go: go1.15.14
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 536866816
  swapTotal: 536866816
  uptime: 3h 12m 17.77s (Approximately 0.12 days)
registries:
  registry.lab.skarbek.name:
    Blocked: false
    Insecure: true
    Location: registry.lab.skarbek.name
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: registry.lab.skarbek.name
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 1
    stopped: 2
  graphDriverName: zfs
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Compression: lz4
    Parent Dataset: a258b6f1-e580-42ea-a79d-c6df33239837/datafs/var/lib/containers
    Parent Quota: "no"
    Space Available: "57809133568"
    Space Used By Parent: "302411776"
    Zpool: a258b6f1-e580-42ea-a79d-c6df33239837
    Zpool Health: ONLINE
  imageStore:
    number: 3
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.2.3
  Built: 1628628916
  BuiltTime: Tue Aug 10 20:55:16 2021
  GitCommit: ""
  GoVersion: go1.15.14
  OsArch: linux/amd64
  Version: 3.2.3
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.2.3-0.10.module_el8.4.0+886+c9a8d9ad.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
# rpm -q zfs
zfs-2.1.0-1.el8.x86_64
```

**Comment by Luap99** [comment]
@rhatdan PTAL

**Comment by rhatdan** [comment]
If you execute chcon -t container_file_t on one of these zfs files or directories from outside of the container, does it succeed?  Or is this more about zfs not working well with SELinux?

**Comment by mskarbek** [comment]
ZFS itself works perfectly well with SELinux for years now. The label for `vol3` from the host perspective is correct (`system_u:object_r:container_file_t:s0:c13,c783`), you won't see `vol1` and `vol2` from host because those are mounted directly into container mount namespaces. You can think of `vol1` and `vol2` datasets as block devices in that case (not accurate, but close enough). Those are "devices" that are mounted inside a container.
In `vol3` case, the dataset is mounted on the host and automatically inherits the correct label. Podman then relabels the already labeled dataset during bind mount into container mount namespace.
In `vol1` case, dataset is mounted directly into container mount namespace where SELinux context is unknown - we don't have SELinux namespace, so it is unlabeled, there is nothing to inherit.
In `vol2` case, label is manually enforced on "device" as its property and ZFS overrides whatever is inherited with that property - in my case there is nothing so unlabeled becomes my property which allows me to use that mount point, but I'm left without full protection of SELinux since I have only base label without full container context.

Now the main question would be how and whose responsibility is to relabel dataset mounted directly into mount namespace.

**Comment by mskarbek** [comment]
I made additional test - `vol4` is an actual block device with one GTP-base partition formatted with XFS added to `podman` volumes as `podman volume create --opt type=xfs --opt device=/dev/zd0p1 vol4`.
Container run with ` podman run -it -v vol4:/srv/vol4:Z registry.access.redhat.com/ubi8/ubi:8.4 bash` will give:
```
drwxr-xr-x.  2 root root system_u:object_r:unlabeled_t:s0               6 Sep 17 11:59 vol4
```
So, I would not blame ZFS for that behavior.

**Comment by rhatdan** [comment]
Weird, so vol2 works but vol1 does not?
Can you  get this to happen repeatedly. 
If you destroy vol1 and recreate does it work properly?  If you setup --log-level debug, does it report anything?

**Comment by mskarbek** [comment]
Let's assume a simpler scenario: I have one block device:
```
# dd if=/dev/zero of=/srv/vol.img bs=1M count=1024
# losetup -fP /srv/vol.img
# sgdisk -Z /dev/loop0
# sgdisk -n 0:0:0 -t 0:8300 /dev/loop0
# mkfs.xfs /dev/loop0
# mkdir /srv/vol
# ls -lZ /srv
(...)
drwxr-xr-x. 2 root root unconfined_u:object_r:var_t:s0         4096 Sep 17 12:53 vol
# mount /dev/loop0p1 /srv/vol
# ls -lZ /srv
(...)
drwxr-xr-x. 2 root root system_u:object_r:unlabeled_t:s0          6 Sep 17 12:52 vol
# restorecon -v /srv/vol
Relabeled /srv/vol from system_u:object_r:unlabeled_t:s0 to system_u:object_r:var_t:s0
```
All above steps were made on host, no containers involved, and should make perfect sense. Freshly formatted XFS file system does not have any labeling so when mounted presents itself as unlabeled regardless of the fact that the directory that become its mount point already had proper label and requires restoring proper context.

Now XFS file system on `/dev/loop0p1` has proper label, let's create `podman` volume with
```
podman volume create --opt type=xfs --opt device=/dev/loop0p1 vol
```
and start container:
```
podman --log-level=debug run -it -v vol:/srv/vol:Z registry.access.redhat.com/ubi8/ubi:8.4 bash
(...)
DEBU[0000] [graphdriver] trying provided driver "zfs"
DEBU[0000] ID:81b5061e-0924-41e6-bd9d-3600281014a6 START zfs list -rHp -t filesystem -o name,origin,used,available,mountpoint,compression,type,volsize,quota,referenced,writte
n,logicalused,usedbydataset a258b6f1-e580-42ea-a79d-c6df33239837/datafs/var/lib/containers  storage-driver=zfs
DEBU[0000] Made network namespace at /run/netns/cni-73fadd0a-d2d4-4c92-1715-fd54564c55b2 for container 677ef8b524fc0c3c73ce11315841457445ea02858d81bf6af64d0d3e48471b3b
INFO[0000] Got pod network &{Name:mystifying_booth Namespace:mystifying_booth ID:677ef8b524fc0c3c73ce11315841457445ea02858d81bf6af64d0d3e48471b3b NetNS:/run/netns/cni-73fadd0
a-d2d4-4c92-1715-fd54564c55b2 Networks:[{Name:podman Ifname:eth0}] RuntimeConfig:map[podman:{IP: MAC: PortMappings:[] Bandwidth:<nil> IpRanges:[]}] Aliases:map[]}
INFO[0000] Adding pod mystifying_booth_mystifying_booth to CNI network "podman" (type=bridge)
DEBU[0000] ID:81b5061e-0924-41e6-bd9d-3600281014a6 FINISH  storage-driver=zfs
DEBU[0000] mount("a258b6f1-e580-42ea-a79d-c6df33239837/datafs/var/lib/containers/b7beee566551c8a070b0d76d72da2e40e23341685844b2514edbafd58eac23e1", "/var/lib/containers/stora
ge/zfs/graph/b7beee566551c8a070b0d76d72da2e40e23341685844b2514edbafd58eac23e1", "context="system_u:object_r:container_file_t:s0:c78,c251"")  storage-driver=zfs
DEBU[0000] mounted container "677ef8b524fc0c3c73ce11315841457445ea02858d81bf6af64d0d3e48471b3b" at "/var/lib/containers/storage/zfs/graph/b7beee566551c8a070b0d76d72da2e40e233
41685844b2514edbafd58eac23e1"
DEBU[0000] Going to mount named volume vol
DEBU[0000] Running mount command: /usr/bin/mount -t xfs /dev/loop1p1 /var/lib/containers/storage/volumes/vol/_data
DEBU[0000] Mounted volume vol
DEBU[0000] Volume vol mount count now at 1
DEBU[0000] Copying up contents from container 677ef8b524fc0c3c73ce11315841457445ea02858d81bf6af64d0d3e48471b3b to volume vol
DEBU[0000] Created root filesystem for container 677ef8b524fc0c3c73ce11315841457445ea02858d81bf6af64d0d3e48471b3b at /var/lib/containers/storage/zfs/graph/b7beee566551c8a070b
0d76d72da2e40e23341685844b2514edbafd58eac23e1
(...)

# ls -lZ /srv/
total 0
drwxr-xr-x. 2 root root system_u:object_r:var_t:s0 6 Sep 17 12:52 vol
```
From the above, we can see that `podman` correctly sets context for the container root using ZFS driver but completely omits relabeling during mount of the named volume.
At this point, I am convinced that this has nothing to do with ZFS but purely with named volumes functionality in `podman`. It looks like nobody tested that functionality. File system is "just mounted" on `/var/lib/containers/storage/volumes/<volume_name>/_data` and left as is. As you can see after restoring context on the host file system in containers has restored context.

**Comment by rhatdan** [comment]
Any chance you can try this out with podman 3.3 or later?

**Comment by mskarbek** [comment]
And yes, this is not a fluke, this just behaves that way every time.

**Comment by mskarbek** [comment]
```
# cat /etc/os-release 
NAME=Fedora
VERSION="34 (Workstation Edition)"
(...)
# uname -r
5.13.13-200.fc34.x86_64
# rpm -q podman
podman-3.3.1-1.fc34.x86_64
```

It works correctly for both XFS on loop device and ZFS dataset.
I have also installed https://koji.mbox.centos.org/koji/buildinfo?buildID=19068 on that CentOS8 host - also works as expected.
Seems like I'll have to wait for 3.3.x in RHEL8 repo or install that koji build.

**Comment by rhatdan** [comment]
Should be there in RHEL8.5.
