### ISSUE TITLE
changed uid is not recorded.

### ISSUE THREAD

**Issue by hboetes** [containers/podman#11646]
OS: fedora 35 amd64
podman version: 3.3.1

I just changed my uid from 1000 to 1026, so it matches with my other systems and rebooted 3 times for good measure.

I got an error saying tmp file /run/user/1000 could not be created. To find out what was being written to that folder I created it, with my permissions and ran the same command `podman image build -f Containerfile -t localhost/mg-static` again and got:
```
% find /run/user/1000/
/run/user/1000/
/run/user/1000/containers
/run/user/1000/containers/overlay-layers
/run/user/1000/containers/overlay-layers/mountpoints.json
/run/user/1000/containers/overlay-layers/mountpoints.lock
/run/user/1000/containers/overlay-locks
/run/user/1000/containers/overlay-containers
/run/user/1000/containers/overlay
/run/user/1000/containers/overlay/volatile-true
/run/user/1000/containers/overlay/native-diff()-true
/run/user/1000/containers/overlay/metacopy()-false
/run/user/1000/containers/overlay/overlay-true
/run/user/1000/libpod
/run/user/1000/libpod/tmp
/run/user/1000/libpod/tmp/alive
/run/user/1000/libpod/tmp/pause.pid
/run/user/1000/libpod/tmp/alive.lck
/run/user/1000/libpod/tmp/exits
/run/user/1000/libpod/tmp/events
```
Now `/run/user/1026/containers/overlay/overlay-true` does exist, so not everything is writing to the old  uid.

I checked all config files and none of them contain 1000 as my uid. I ran the same command with `strace` and that also didn't show the user id. `journalctl --user -xe` also gave no results. It's also not in my `env`.

Something is wrong here, but I don't know what. I hope someone can try to reproduce the problem, which should be fairly straightforward.

**Comment by Luap99** [comment]
I don't think changing the uid is supported by podman, please see this issue https://github.com/containers/podman/issues/11377

**Comment by hboetes** [comment]
The solution is mentioned here: https://github.com/containers/podman/issues/11377#issuecomment-910094162

```
% sudo rm -rf ~/.local/share/containers
```
