### ISSUE TITLE
`podman machine start` cannot find gvproxy

### ISSUE THREAD

**Issue by jakub-murin** [containers/podman#11665]
/kind bug

**Error: unable to start host networking: "stat /usr/libexec/podman/gvproxy: no such file or directory"**

I'm trying to install podman on Ubuntu 20.04 following [these instructions](https://podman.io/getting-started/installation)

**Steps to reproduce the issue:**

1. Install podman:

```sh
  . /etc/os-release
  echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
  curl -L "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key" | sudo apt-key add -
  sudo apt-get update
  sudo apt-get -y upgrade
  sudo apt-get -y install podman
```

2. run `podman machine init`:

    > Error: exec: "qemu-system-x86_64": executable file not found in $PATH

3. install qemu:

    `sudo apt-get -qq -y install qemu-system-x86`

4. try again `podman machine init`:

    > Downloading VM image: fedora-coreos-34.20210904.1.0-qemu.x86_64.qcow2.xz: done

5. run `podman machine start`:

    **Error: unable to start host networking: "stat /usr/libexec/podman/gvproxy: no such file or directory"**

**Describe the results you received:**

Error: unable to start host networking: "stat /usr/libexec/podman/gvproxy: no such file or directory"

**Describe the results you expected:**

No error

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.6
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.22.3
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 6
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: REDACTED
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.11.0-34-generic
  linkmode: dynamic
  memFree: 2305429504
  memTotal: 16447160320
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.20.1.5-925d-dirty
      commit: 0d42f1109fd73548f44b01b3e84d04a279e99d2e
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 7998533632
  swapTotal: 7998533632
  uptime: 2h 36m 13.22s (Approximately 0.08 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/jakub/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/jakub/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /home/jakub/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.1
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.3.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 100:3.3.1-1 amd64 [installed]
podman/unknown 100:3.3.1-1 arm64
podman/unknown 100:3.3.1-1 armhf
podman/unknown 100:3.3.1-1 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by afbjorklund** [comment]
If you want to run `podman machine` also on Linux, you can install `gvproxy` from https://github.com/containers/gvisor-tap-vsock)

**Comment by jakub-murin** [comment]
I've followed the instructions for Ubuntu (under *Installing development versions of Podman*), I've pasted the bash commands I had used in *Steps to reproduce the issue, step 1*

I'll try to install `gvisor-tap-vsock` to get `gvproxy`, thank you.

**Comment by mheon** [comment]
@baude @lsm5 Do we need to start shipping gvproxy in OBS?

**Comment by baude** [comment]
imho if ubuntu wants to support machine, gvproxy will have to be added as a dep as well as qemu.

**Comment by baude** [comment]
I'm going to close this bug as I dont think there is anything here for the upstream team.  Reopen if you feel otherwise.
