### ISSUE TITLE
Incorrect /sys/fs/cgroup with --network=ns and --uidmap ?

### ISSUE THREAD

**Issue by LucaFulchir** [containers/podman#11663]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Using `uidmap`/`gidmap` with `--network=ns:...` might not correctly setup `/sys/fs/cgroup` in the container

I am experimenting with containers and manually setting up network namespaces, and if I use `uidmap`/`gidmap` and  `--network=ns=/run/netns/my_custom_ns` I can not startup a systemd container anymore.

checking the contents of the containers' `/sys/fs/cgroup` with and without `--network=ns:...` will give much different results

**Steps to reproduce the issue:**

1. make sure you have enough free subuid/gid, I am testing this from root

2. setup a custom network namespace (we'll create an unconnected veth pair):
```
ip link add veth-ctr0 type veth peer name veth-ctr1
ip netns add netns-custom
ip link set veth-ctr1 netns netns-custom
# optional: rename, configure the interface
ip netns exec netns-custom   ip link set veth-ctr1 name eth0
ip netns exec netns-custom   ip a add 172.18.0.2/24 dev eth0
ip netns exec netns-custom   ip l set dev eth0 up
ip netns exec netns-custom   ip r add default via 172.18.0.1 dev eth0
```

2. check contents of `/sys/fs/cgroup` with `--network=private`, looks fine:
```
# podman run \
  --rm -it \
  --name='custom' \
  '--systemd=always' \
  '--network=private' \
  '--uidmap=0:200000:65536' \
  '--gidmap=0:200000:65536' \
  docker.io/library/alpine:latest ls /sys/fs/cgroup
cgroup.controllers         cpu.max                    hugetlb.1GB.current        hugetlb.2MB.rsvd.current   hugetlb.64KB.events.local  memory.events              memory.swap.current
cgroup.events              cpu.pressure               hugetlb.1GB.events         hugetlb.2MB.rsvd.max       hugetlb.64KB.max           memory.events.local        memory.swap.events
cgroup.freeze              cpu.stat                   hugetlb.1GB.events.local   hugetlb.32MB.current       hugetlb.64KB.rsvd.current  memory.high                memory.swap.high
cgroup.max.depth           cpu.weight                 hugetlb.1GB.max            hugetlb.32MB.events        hugetlb.64KB.rsvd.max      memory.low                 memory.swap.max
cgroup.max.descendants     cpu.weight.nice            hugetlb.1GB.rsvd.current   hugetlb.32MB.events.local  io.latency                 memory.max                 pids.current
cgroup.procs               cpuset.cpus                hugetlb.1GB.rsvd.max       hugetlb.32MB.max           io.max                     memory.min                 pids.events
cgroup.stat                cpuset.cpus.effective      hugetlb.2MB.current        hugetlb.32MB.rsvd.current  io.pressure                memory.numa_stat           pids.max
cgroup.subtree_control     cpuset.cpus.partition      hugetlb.2MB.events         hugetlb.32MB.rsvd.max      io.stat                    memory.oom.group
cgroup.threads             cpuset.mems                hugetlb.2MB.events.local   hugetlb.64KB.current       io.weight                  memory.pressure
cgroup.type                cpuset.mems.effective      hugetlb.2MB.max            hugetlb.64KB.events        memory.current             memory.stat
```

3. check contents of `/sys/fs/cgroup` with `--network=ns:/run/netns/netns-custom`, completely different and now your systemd container will not start:
```
# podman run \
  --rm -it \
  --name='custom' \
  '--systemd=always' \
  '--network=ns:/run/netns/netns-custom' \
  '--uidmap=0:200000:65536' \
  '--gidmap=0:200000:65536' \
  docker.io/library/alpine:latest ls /sys/fs/cgroup
-.mount                        cgroup.stat                    cpuset.cpus.effective          io.cost.model                  memory.numa_stat               sys-kernel-config.mount
cgroup.controllers             cgroup.subtree_control         cpuset.mems.effective          io.cost.qos                    memory.pressure                sys-kernel-debug.mount
cgroup.max.depth               cgroup.threads                 dev-hugepages.mount            io.pressure                    memory.stat                    system.slice
cgroup.max.descendants         cpu.pressure                   dev-mqueue.mount               io.stat                        nix-store.mount                user.slice
cgroup.procs                   cpu.stat                       init.scope                     machine.slice                  sys-fs-fuse-connections.mount
```

**Describe the results you received:**

any systemd containers will not start in this configuration (`uidmap`+`gidmap`+`network=ns:...`) since it can not write to the `/sys/fs/cgroup`, which looks a lot like what the root user sees on the host

using only `--network=ns:...` without `--uidmap`/`--gidmap` will give a correct  `/sys/fs/cgroup` like in point `2` above

**Describe the results you expected:**

`/sys/fs/cgroup` in the two runs above should look identical

systemd containers starts correctly with uid remap and a custom netns, like it does with `--network=private`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.8
Built:        Tue Jan  1 00:00:00 1980
OS/Arch:      linux/arm64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
host:
  arch: arm64
  buildahVersion: 1.22.3
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /nix/store/fg8hyap5icfpg9x9v8r3ksxksfjrdfl8-conmon-2.0.29/bin/conmon
    version: 'conmon version 2.0.29, commit: '
  cpus: 4
  distribution:
    distribution: nixos
    version: "21.11"
  eventLogger: journald
  hostname: multivac
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.52
  linkmode: dynamic
  memFree: 519131136
  memTotal: 3976019968
  ociRuntime:
    name: crun
    package: Unknown
    path: /nix/store/9v1m816lqahjp9i5flvqdqghmpbd9axn-crun-1.0/bin/crun
    version: |-
      crun version 1.0
      commit: 1.0
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /nix/store/z819i5jd1dabzfwql9qv5q8cn6jgg3ic-slirp4netns-1.1.12/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 8588869632
  swapTotal: 8589926400
  uptime: 6h 5m 1.05s (Approximately 0.25 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 1
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 149
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.3.1
  Built: 315532800
  BuiltTime: Tue Jan  1 00:00:00 1980
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/arm64
  Version: 3.3.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

nixos unstable, podman 3.3.1, crun 1.0

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Comment by giuseppe** [comment]
it is not possible to mount a sysfs file system when running in a user namespace (that is the case when you specify a user mapping) and the user namespace doesn't own the network namespace.  This is a limit from the kernel to prevent user namespaces to mess up with network namespaces they don't own by mounting `sysfs` and writing to it.

My suggestion would be to create the network namespace as part of the container creation, so `--network private` and then configure it from the outside.

You could try using a prestart hook so that the network namespace can be configured after the user+network namespaces are created but before the container process starts.

**Comment by giuseppe** [comment]
I'll close this issue since there is not much we can do in Podman, but feel free to add more comments

**Comment by LucaFulchir** [comment]
uhm... I'm trying to play with oci hooks, I can run a test script just fine, but the documentation is scarce...

`prestart` hooks should be run just before the user command is run, but if my script has just:

```
#!/bin/bash
/usr/bin/env >> /tmp/oci-hook-test
/usr/bin/ip link >> /tmp/oci-hook-test
/usr/bin/ip netns  >> /tmp/oci-hook-test
```
I see that the script is run from the `/var/lib/container.../userdata` of that container  
I can see the host network just fine, but I can't see the container network namespace  (or even the new bridged interface)
if I run the same `ip netns` from the host after the container has started, I correctly see the new private netns setup by podman for the new container

...soo... any pointer on how to configure the network?  
Thank you

**Comment by mheon** [comment]
This sounds like a separate issue, given it relates to OCI hooks. Please open a new issue.

**Comment by giuseppe** [comment]
you need to manually join the container net namespace from the hook (`unshare --net=/proc/CONTAINER_PID/ns/net...`)
