### ISSUE TITLE
podman machine start cannot be run as a Automator application

### ISSUE THREAD

**Issue by raghavendra-talur** [containers/podman#11667]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I was trying to create an application for Podman machine on my mac. This is mainly to achieve two goals
1. I want to auto start podman machine
2. I want to start podman using the spotlight/alfred application.

**Steps to reproduce the issue:**

1. Create a new application in Automator using "Run Shell Script" option. Where the shell script content is `/usr/local/bin/podman machine start`

2. Run the application

**Describe the results you received:**
It failed with the error: "The action “Run Shell Script” encountered an error: “Error: unable to start host networking: "stat /usr/libexec/podman/gvproxy: no such file or directory"”

**Describe the results you expected:**
podman machine should start

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
% podman --version
podman version 3.3.1
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Comment by rhatdan** [comment]
@ashley-cui PTAL

This looks like an installer problem.  Did  you install podman via brew?  Could you check if there is an update?

**Comment by ashley-cui** [comment]
Looks like you don't have the gxproxy binary, can you confirm how you installed podman?

**Comment by raghavendra-talur** [comment]
Yes, I installed podman using brew. Here is the command

`brew install podman`

I checked and it is updated.
```
Warning: podman 3.3.1 is already installed and up-to-date.
To reinstall 3.3.1, run:
  brew reinstall podman
```

I was able to start the podman machine when invoked in a terminal directly. It was only in the Automator application that this error occurred. Thanks for the hint that it might be due to installation settings; updating the script to this made it work.

```
export PATH=/usr/local/bin:$PATH
/usr/local/bin/podman machine start
```

You may close this issue.
