### ISSUE TITLE
Podman commands not working on WSL2

### ISSUE THREAD

**Issue by ruckc** [containers/podman#11666]
/kind bug

**Description**
When following the Podman on [WSL2 guide](https://www.redhat.com/sysadmin/podman-windows-wsl2), it errors with similar error to #10027.

**Steps to reproduce the issue:**
1. On Windows 10, wsl version 2, kernel following the [WSL2 guide](https://www.redhat.com/sysadmin/podman-windows-wsl2) to setup and install podman. 

2. `podman info`

**Describe the results you received:**
```sh
ruckc@DESKTOP:~$ podman info
WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers
cannot clone: Invalid argument
Error: cannot re-exec process
```

**Describe the results you expected:**
expected podman info output

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
```sh
ruckc@DESKTOP:~$ podman version
WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers
cannot clone: Invalid argument
Error: cannot re-exec process
```

**Output of `podman info --debug`:**

```
ruckc@DESKTOP:~$ podman info --debug
WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers
cannot clone: Invalid argument
Error: cannot re-exec process
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
ruckc@DESKTOP:~$ apt list podman
Listing... Done
podman/unknown,now 100:3.3.1-1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical (and virtual) Windows 10 with WSL2 and Ubuntu 20.04.3 inside

**Comment by mheon** [comment]
This is most likely related to a lack of CLONE_NEWUSER support in the kernel in use. Can you provide additional information on the kernel in question? Any chance there are upgrades available, given we have seen this before and it's since been fixed?

**Comment by ruckc** [comment]
So `buildah info` shows that error: `Error during unshare(CLONE_NEWUSER): Invalid argument`.  The kernel is provided by Microsoft, uname -a output:
```
ruckc@DESKTOP:~$ uname -a
Linux DESKTOP 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ruckc** [comment]
Argh, looks like even though its a newly created WSL environment, and the default version is 2, it still created it in WSL1.  Once i converted it to wsl2 it works.

**Comment by djohn156** [comment]
Just in case someone stumbles upon the same issue: Had the same problem on an Ubuntu WSL 2. The issue disappeared after installing `buildah`.

**Comment by mig8447** [comment]
> Argh, looks like even though its a newly created WSL environment, and the default version is 2, it still created it in WSL1. Once i converted it to wsl2 it works.

@ruckc How did you convert the vm to WSL2?

**Comment by ruckc** [comment]
@mig8447 

Using the wsl command line utility in PowerShell/command prompt.  

`wsl --set-version <distro name> 2`

**Comment by mig8447** [comment]
In case anyone wonders, you can list the WSL version of your distros using:
```powershell
PS C:\Users\...> wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu-20.04           Running         1
```
And then to upgrade, you can run
```powershell
wsl --set-version Ubuntu-20.04 2
```

**Comment by mig8447** [comment]
> @mig8447
> 
> Using the wsl command line utility in PowerShell/command prompt.
> 
> `wsl --set-version <distro name> 2`

Thanks @ruckc, I had just figured it out

**Comment by wswind** [comment]
> 

Works on fedora wsl too, thanks.  Can't understand why buildah has anything to do with this warning.

**Comment by kbaran1998** [comment]
> @mig8447
> 
> Using the wsl command line utility in PowerShell/command prompt.
> 
> `wsl --set-version <distro name> 2`

This worked for me but to get that working. I had to first fix ```WSL2: Virtual hard disk files must be uncompressed and unencrypted and must not be sparse```. This [thread](https://github.com/microsoft/WSL/issues/4103) helped me solve it if anyone is wondering.
