### ISSUE TITLE
Add some documentation on how podman machine is updated

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman#11680]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

It would be nice with documentation on **how** `podman machine` keeps the OS updated.

Some summary lines and then links over to [Fedora CoreOS](https://docs.fedoraproject.org/en-US/fedora-coreos/auto-updates/) for details would be just fine...

**Steps to reproduce the issue:**

1. `podman machine init`

2. `podman machine start`

3. Wonder how the OS is updated ?

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

The upgrades happened just fine, as per documentation:

1) A new OS upgrade comes out every 14 days, and is detected automatically.

2) The [Zincati](https://github.com/coreos/zincati) service detects the new version, and stages it with `rpm-ostree`.

Then the podman machine is rebooted, with the new OS.

The count-down starts at 10 minutes:
```
Connecting to vm podman-machine-default. To close connection, use `~.` or `exit`
Could not create directory '/root/.ssh'.
Warning: Permanently added '[localhost]:38901' (ECDSA) to the list of known hosts.
Fedora CoreOS 34.20210808.1.0
Tracker: https://github.com/coreos/fedora-coreos-tracker
Discuss: https://discussion.fedoraproject.org/c/server/coreos/

[core@localhost ~]$ 
New update 34.20210904.1.0 is available and has been deployed.
If permitted by the update strategy, Zincati will reboot into this update when all
interactive users have logged out, or in 10 minutes, whichever comes earlier.
Please log out of all active sessions in order to let the auto-update process continue.
```

And then it proceeds automatically:
```
New update 34.20210904.1.0 is available and has been deployed.
If permitted by the update strategy, Zincati will reboot into this update when all
interactive users have logged out, or in 1 minute, whichever comes earlier.
Please log out of all active sessions in order to let the auto-update process continue.

[core@localhost ~]$ Connection to localhost closed by remote host.
Connection to localhost closed.
Error: exit status 255
```

**Output of `podman version`:**

```
podman version 4.0.0-dev
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu

**Comment by baude** [comment]
@afbjorklund at this point you know more than me ... would you consider writing something up and i'll review it?

**Comment by afbjorklund** [comment]
Will do, maybe we could get some assistance from Fedora CoreOS when it comes to suitable "starting point" (for linking)

**Comment by afbjorklund** [comment]
It seems like the perfect storm, the image is automatically upgraded to the latest and greatest (and also rather untested)

It's not obvious how to downgrade a broken upgrade, such as `podman-plugins-3.3.1-1.fc34.x86_64` with custom network
