### ISSUE TITLE
Named-volume's SElinux labels are not being created properly - RHEL's branch

### ISSUE THREAD

**Issue by Craconia** [containers/podman#11683]
Hi,

On RHEL 8 podman is not honoring the "Z" flag (that creates the SELinux private unshared label) when creating named-volumes.  It does for bind-mounts but not for named-volumes.

Here's an example of the same command on both RHEL & Fedora:

**# RHEL 8 with podman version 3.2.3**

```
podman run -v myvol:/tmp/foobar:Z ubi8
ls -Zd /local/testuser/.local/share/containers/storage/volumes/myvol/_data
system_u:object_r:container_file_t:s0 /local/testuser/.local/share/containers/storage/volumes/myvol/_data
```

**# Fedora 33 with podman version 3.3.0**
```
podman run -v myvol:/tmp/foobar:Z ubi8
ls -Zd /home/testuser/.local/share/containers/storage/volumes/myvol/_data
system_u:object_r:container_file_t:s0:c926,c1002 /home/testuser/.local/share/containers/storage/volumes/myvol/_data
```

Podman in RHEL is not honoring the user's request of creating a private unshared named-volume.  It should behave as it does on Fedora these days.

**Comment by flouthoc** [comment]
@Craconia thanks for opening up the issues. Is this happening with latest release as well ?

**Comment by mheon** [comment]
I recommend opening a Bugzilla if this cannot be reproduced in latest code.

**Comment by Craconia** [comment]
Hi.  Yes, it happens with the latest RHEL 8.4 (fully patched) using the default rolling stream of "container-tools".

**Comment by Craconia** [comment]
Opened a Bugzilla as suggested.
