### ISSUE TITLE
`podman stats` stopped giving an error on systems with cgroupv1

### ISSUE THREAD

**Issue by KKoukiou** [containers/podman#11697]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`podman stats` command changed behavior in cgroupv1 systems.

**Describe the results you received:**

Now (podman-3.3.1-8.module+el8.5.0+12582+56d94c81.x86_64) there is this behavior:
$ podman stats
ID          NAME        CPU %       MEM USAGE / LIMIT  MEM %       NET IO      BLOCK IO    PIDS        CPU TIME    AVG CPU %

**Describe the results you expected:**

Previously (podman-3.0.1-6.module+el8.4.0+10607+f4da7515.x86_64) there was this behavior:
$ podman stats 
Error: stats is not supported in rootless mode without cgroups v2

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
]# podman version 
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.7
Built:        Mon Sep 13 11:11:29 2021
OS/Arch:      linux/amd64

```

**Comment by Luap99** [comment]
Do you run the command rootless?

**Comment by KKoukiou** [comment]
Yes, this is a duplicate of. https://bugzilla.redhat.com/show_bug.cgi?id=1988252 

Closing it and leaving it to the downstream tracker.
