### ISSUE TITLE
mounting host images into container as a rootless user

### ISSUE THREAD

**Issue by DustinKLo** [containers/podman#11708]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I'm trying to run a podman container with access to it's host images, i can do it with a root user by mounting `-v /var/lib/containers:/var/lib/containers` and inside the container i have access to it's host images:
```
root@ubuntu-20-04:~# podman run --privileged \
    -v /var/lib/containers:/var/lib/containers \
    -v /run/netns:/run/netns \
    --rm -it  quay.io/podman/stable:v3.3.1 bash
[root@bcedb6a1962e /]# podman images
REPOSITORY                TAG         IMAGE ID      CREATED       SIZE
quay.io/podman/stable     v3.3.1      803fcf0206f7  14 hours ago  437 MB
docker.io/library/python  3.9.7-slim  66f4843b721f  13 days ago   128 MB
```
however running it as a rootless user i'm unable to get the same results and no images are displayed when inside the container (i'm mounting `-v $HOME/.local/share/containers/storage/:/var/lib/containers/`)
```
$ podman run --privileged -v $HOME/.local/share/containers/storage/:/var/lib/containers podman:v3.3.1 podman images
REPOSITORY                TAG         IMAGE ID      CREATED       SIZE
```

**Steps to reproduce the issue:**

1. `podman pull podman:v3.3.1`
2. `podman run --privileged -v $HOME/.local/share/containers/storage/:/var/lib/containers podman:v3.3.1 podman images`

**Describe the results you expected:**
I should be seeing the images from the host container

**Output of `podman version`:**
3.3.1

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**
yes but it only says how to [run podman inside a container as root](https://github.com/containers/podman/blob/main/troubleshooting.md#solution-11)

**Comment by vrothberg** [comment]
@giuseppe @rhatdan PTAL

**Comment by giuseppe** [comment]
Why the extra `/storage` when running rootless?

**Comment by giuseppe** [comment]
you'd need to bind mount the storage directory twice (since the path is hardcoded into the database):

```
$ podman run --privileged -v /run/user/$UID/netns:/run/user/$UID/netns \
   -v $HOME/.local/share/containers:$HOME/.local/share/containers \
   -v $HOME/.local/share/containers:/var/lib/containers quay.io/podman/stable:v3.3.1 podman images
```

**Comment by DustinKLo** [comment]
@giuseppe apologies for the late reply and thank you for responding

was able to get it to work, but i had to change one of the mounts to `-v /run/user/$UID:/run/user/$UID`
```bash
$ podman run --privileged \
> -v /run/user/$UID:/run/user/$UID \
> -v $HOME/.local/share/containers:$HOME/.local/share/containers \
> -v $HOME/.local/share/containers:/var/lib/containers quay.io/podman/stable:v3.3.0 \
> podman images
REPOSITORY                TAG         IMAGE ID      CREATED      SIZE
docker.io/library/python  3.9.7-slim  66f4843b721f  2 weeks ago  128 MB
quay.io/podman/stable     v3.3.0      b648fbc5870f  3 weeks ago  387 MB

```

**Comment by DustinKLo** [comment]
i was also able to get the host images by mounting `-v $HOME/.local/share/containers/storage:/var/lib/shared`
besides it being read-only, what are some advantages to mounting the storage directory twice?

```bash
$ podman run --rm --privileged \
    -v $HOME/.local/share/containers/storage:/var/lib/shared \
    quay.io/podman/stable:v3.3.0 \
    podman images
REPOSITORY                TAG         IMAGE ID      CREATED      SIZE        R/O
docker.io/library/python  3.9.7-slim  66f4843b721f  2 weeks ago  128 MB      true
quay.io/podman/stable     v3.3.0      b648fbc5870f  3 weeks ago  387 MB      true
```

**Comment by rhatdan** [comment]
Allows you to run rootless and rootfull containers.
