### ISSUE TITLE
podman machine ssh failed in fedora for rootless

### ISSUE THREAD

**Issue by pendulm** [containers/podman#11731]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman machine works on Fedora 34, But failed when ssh login in the machine.

```sh
$  podman machine ssh podman-machine-default
Connecting to vm podman-machine-default. To close connection, use `~.` or `exit`
Bad owner or permissions on /etc/ssh/ssh_config.d/50-redhat.conf
Error: exit status 255
```

**Steps to reproduce the issue:**
In Fedora Linux 34

1. podman machine init

2. podman machine start podman-machine-default

3. podman machine ssh podman-machine-default
failed

**Describe the results you received:**
Bad owner or permissions on /etc/ssh/ssh_config.d/50-redhat.conf
Error: exit status 255

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.6
Built:        Tue Aug 31 04:46:36 2021
OS/Arch:      linux/amd64
```

**Comment by pendulm** [comment]
In rootless mode, podman enter userns which ssh  complain abount permission.
```
$ podman unshare

# ls -lh /etc/ssh/ssh_config.d/50-redhat.conf
-rw-r--r--. 1 nobody nobody 831 May 24 20:15 /etc/ssh/ssh_config.d/50-redhat.conf

# ssh  -i /home/mike/.ssh/podman-machine-default  -p 40317 core@localhost "-o UserKnownHostsFile /dev/null" "-o StrictHostKeyChecking no"
Bad owner or permissions on /etc/ssh/ssh_config.d/50-redhat.conf

**Comment by vrothberg** [comment]
Thanks for reaching out, @pendulm.  I guess that `podman machine` shouldn't enter the user ns. @giuseppe WDYT?

**Comment by Luap99** [comment]
Yes it should not need to join the usersns. All machine commands already disabled the normal podman setup.

I guess this should work:
```diff
$ git diff
diff --git a/pkg/rootless/rootless_linux.c b/pkg/rootless/rootless_linux.c
index 4d8443fcb..6ce4b1e29 100644
--- a/pkg/rootless/rootless_linux.c
+++ b/pkg/rootless/rootless_linux.c
@@ -212,6 +212,7 @@ can_use_shortcut ()
         continue;
 
       if (strcmp (argv[argc], "mount") == 0
+          || strcmp (argv[argc], "machine") == 0
           || strcmp (argv[argc], "search") == 0
           || (strcmp (argv[argc], "system") == 0 && argv[argc+1] && strcmp (argv[argc+1], "service") != 0))
         {
```

**Comment by rhatdan** [comment]
Yes Please open a PR.

**Comment by giuseppe** [comment]
the patch LGTM.  @Luap99 please open a PR

**Comment by Luap99** [comment]
PR #11752
