### ISSUE TITLE
podman machine init prompt to set default config or custom set resources (cpu, ram, disk)

### ISSUE THREAD

**Issue by pumano** [containers/podman#11743]
/kind feature

**Description**
Would be good to have default asking user in command line when `podman machine init` executed, for selecting default config or provide input for cpu / ram / disk with example in command line.

For example:

![vue-create](https://user-images.githubusercontent.com/17675259/134749880-5ff8447f-209b-4a32-97cc-c77c8a506605.png)

**Describe the results you received:**
currenly in default init i got only 10gb of disk storage and somehow I can't install nodejs app out of the box, but reiniting machine with some advanced settings `podman machine init --cpus 2 --memory 4096 --disk-size 50` - solve my problem.

**Describe the results you expected:**

Would love if cli ask for default and provide possibility to set cpu / ram / disk with custom values without using explicit `podman machine init --cpus 2 --memory 4096 --disk-size 50` command

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

3.3.1

**Comment by rhatdan** [comment]
I hesitate to make command line tools prompt.  We are bumping the defaults in the newer versions of machine to --disk-size 20.  Not sure about memory.  These fields are going to be in containers.conf, so they can be set for all future inits.  I would like to have a sane default, which is larger then what we have now.

**Comment by pumano** [comment]
@rhatdan ok, thank you

**Comment by afbjorklund** [comment]
I added it to the "[podman-systray](https://github.com/afbjorklund/podman-systray)" GUI, where such prompts are more common

![podman-systray-init-dialog](https://user-images.githubusercontent.com/10364051/134770942-5063cb62-7c06-45c0-9ad2-4510578e8b95.png)

**Comment by rhatdan** [comment]
Yes it probably makes more sense there rather then prompting.

**Comment by pumano** [comment]
Ok thank you guys! So I close issue
