### ISSUE TITLE
Mapped directory ownership issue (reopen of #11412)

### ISSUE THREAD

**Issue by fishy** [containers/podman#11770]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

This is basically the reopen of https://github.com/containers/podman/issues/11412, but with updated podman and kernel version.

When using `podman run -v --user`, the owner of the files in the mapped directory is root instead of the current user.

**Steps to reproduce the issue:**

```
$ ls -l
total 20
-rw-r--r-- 1 fishy fishy 8232 Sep 28 10:17 baseplate.thrift
drwxr-xr-x 3 fishy fishy 4096 Sep  2 09:55 gen-go
drwxr-xr-x 2 fishy fishy 4096 Sep  9 12:04 limitopen

$ docker run --rm -v ${PWD}:/data/ --user "$(id -u):$(id -g)" -it --entrypoint=/bin/bash ghcr.io/reddit/thrift-compiler:0.14.2
groups: cannot find name for group ID 1000
I have no name!@e42b97a09859:/data$ whoami
whoami: cannot find name for user ID 1000
I have no name!@e42b97a09859:/data$ touch foo
I have no name!@e42b97a09859:/data$ ls -l
total 20
-rw-r--r-- 1 1000 1000 8232 Sep 28 17:17 baseplate.thrift
-rw-r--r-- 1 1000 1000    0 Sep 28 17:18 foo
drwxr-xr-x 3 1000 1000 4096 Sep  2 16:55 gen-go
drwxr-xr-x 2 1000 1000 4096 Sep  9 19:04 limitopen

$ podman run --rm -v ${PWD}:/data/ --user "$(id -u):$(id -g)" -it --entrypoint=/bin/bash ghcr.io/reddit/thrift-compiler:0.14.2
1000@e9e0d3ae4951:~$ whoami
1000
1000@e9e0d3ae4951:~$ touch foo
touch: cannot touch 'foo': Permission denied
1000@e9e0d3ae4951:~$ ls -l
total 20
-rw-r--r-- 1 root root 8232 Sep 28 17:17 baseplate.thrift
drwxr-xr-x 3 root root 4096 Sep  2 16:55 gen-go
drwxr-xr-x 2 root root 4096 Sep  9 19:04 limitopen
```

I also tried the alternatives described on https://github.com/containers/podman/blob/main/troubleshooting.md#2-cant-use-volume-mount-get-permission-denied:

```
$ podman run --rm -v ${PWD}:/data/ --security-opt label=disable --user "$(id -u):$(id -g)" -it --entrypoint=/bin/bash ghcr.io/reddit/thrift-compiler:0.14.2
1000@918b73991fe5:~$ touch foo
touch: cannot touch 'foo': Permission denied

$ podman run --rm -v ${PWD}:/data/:z --user "$(id -u):$(id -g)" -it --entrypoint=/bin/bash ghcr.io/reddit/thrift-compiler:0.14.2
1000@14cce0de7b8c:~$ touch foo
touch: cannot touch 'foo': Permission denied

$ podman run --rm -v ${PWD}:/data/:Z --user "$(id -u):$(id -g)" -it --entrypoint=/bin/bash ghcr.io/reddit/thrift-compiler:0.14.2
1000@f8201b86e09b:~$ touch foo
touch: cannot touch 'foo': Permission denied
```

**Describe the results you received:**

The files under the mapped /data/ are owned by root:root

**Describe the results you expected:**

The files under the mapped /data/ should be owned by 1000:1000

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.7
Built:        Wed Dec 31 16:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.22.3
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 12
  distribution:
    distribution: debian
    version: unknown
  eventLogger: journald
  hostname: perch
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.0-1-amd64
  linkmode: dynamic
  memFree: 9001725952
  memTotal: 16378265600
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 16773017600
  swapTotal: 16773017600
  uptime: 43m 29.39s
registries: {}
store:
  configFile: /home/fishy/.config/containers/storage.conf
  containerStore:
    number: 10
    paused: 0
    running: 0
    stopped: 10
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.10.5
        fuse-overlayfs: version 1.7.1
        FUSE library version 3.10.5
        using FUSE kernel interface version 7.31
  graphRoot: /home/fishy/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  volumePath: /home/fishy/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.1
  Built: 0
  BuiltTime: Wed Dec 31 16:00:00 1969
  GitCommit: ""
  GoVersion: go1.16.7
  OsArch: linux/amd64
  Version: 3.3.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ apt list podman
Listing... Done
podman/testing,now 3.3.1+ds2-1 amd64 [installed]
podman/testing 3.3.1+ds2-1 i386
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical, with kernel:

```
$ uname -a
Linux perch 5.14.0-1-amd64 #1 SMP Debian 5.14.6-2 (2021-09-19) x86_64 GNU/Linux
```

**Comment by mheon** [comment]
I think we may need to do a review of what Docker does, versus what we do, here, and determine what the actual rules are for both, and whether we want to deviate from Docker's behavior; we've been doing this piecemeal for the last year, and it's basically just playing whack-a-mole with bugs at this point.

**Comment by rhatdan** [comment]
I actually believe what we do is correct.  But I am willing to look at alternatives.

**Comment by Luap99** [comment]
We should not chown external volumes by default IMO. If a user want to chown they can use the `:U` option.

**Comment by giuseppe** [comment]
I agree we should not chown already existing directories.  It will be confusing because something like `-v /tmp:/tmp` won't work anymore for rootless users

**Comment by fishy** [comment]
I'm sorry what's the solution to the problem? is it not supposed to work when mapping an existing directory?

**Comment by rhatdan** [comment]
We believe that if you volume mount over a directory within the image, then the volume should match the owner and permissions of the directory you are mounting over.
-v foobar:/tmp should be owned by root with 777 permissions.
If the directory does not exists, then the directory will get created owned by the user of the container.
So if you run the container as dwalsh, the directory will be owned by dwalsh.  If  you run the container as root, it will be owned by root.  BTW, this will only happen the first time you run a newly created volume.

**Comment by fishy** [comment]
@rhatdan thanks for the explanation.

I think the problem here is that at least when building a docker image from docker, you cannot set WORKDIR to a directory that does not exist. In https://github.com/reddit/thrift-compiler/blob/59a07ce63416a7873b2925840360424e30769127/Dockerfile (the source of the docker image I used in the example) we never explicitly create the `/data` directory, and I would assume it's created because we set it as WORKDIR on line line 35, and that created it.

The whole point here is that we need to run this tool from this container on the files in the current directory on the host machine (thrift compiler in this case), because maintaining and distributing this tool is much bigger a hassle than maintaining and distribution a container.

Another example this does not work is https://github.com/buchgr/bazel-remote. That container needs the user to map their local directory into the container as the cache, and when using it with podman the cache directory is not writable by the tool in the container and breaks everything.

**Comment by rhatdan** [comment]
Ok perhaps we have a couple of issues.  In Docker build WORKDIR /data, does not create the data directory? But we create it with the ownership of the USER at the time the WORKDIR gets created?

Could you show me the actual Podman command that you are seeing the bazel-remote error?
Actually the same for the original error.

**Comment by fishy** [comment]
>In Docker build WORKDIR /data, does not create the data directory? But we create it with the ownership of the USER at the time the WORKDIR gets created?

No docker build created `/data` inside the container, which caused podman to refuse to `chown` to current user, and caused permission issues when trying to use it.

>Could you show me the actual Podman command that you are seeing the bazel-remote error?

`podman run --restart=always --pull=always --name=bazel_remote_cache --user "1000:1000" -d -v /home/bazel-cache:/data -p 127.0.0.1:9090:8080 -p 9092:9092 buchgr/bazel-remote-cache --max_size=5`

>Actually the same for the original error.

I already provided them in this bug report?

**Comment by giuseppe** [comment]
Is Docker running as root?  In this case the ` --user "$(id -u):$(id -g)"` means the real user 1000:1000 on the host.

With rootless podman instead, the current user (your 1000:1000) is mapped to root in the container user namespace.

The equivalent command line for podman would be:

`$ podman run --rm -v ${PWD}:/data/ -it --entrypoint=/bin/bash ghcr.io/reddit/thrift-compiler:0.14.2`

so no `--user` option.

Alternatively, you could add `--userns keep-id` that creates an inner namespace where the current user is mapped to the same value, so you could have:  `$ podman run --userns keep-id --rm --user "$(id -u):$(id -g) -v ${PWD}:/data/ -it --entrypoint=/bin/bash ghcr.io/reddit/thrift-compiler:0.14.2`

**Comment by fishy** [comment]
@giuseppe Thanks. Either `--userns keep-id` or remove `--user` works, so that resolves my problem with bazel-remote.

The problem with thrift is that we provide a `thrift-docker.sh` file for people to be used as a drop-in replacement for thrift compiler binary on their computer (as that's hard to distribute), and we can't ask all our devs to replace docker with podman, so we want to provide a script that works for both.

This is what the script looks like today:

```sh
DOCKER_CMD=${DOCKER:-docker}
DEFAULT_DOCKER_TAG="0.14.2"
DOCKER_TAG=${THRIFT_VERSION:-${DEFAULT_DOCKER_TAG}}
DOCKER_REPO=ghcr.io/reddit/thrift-compiler

exec ${DOCKER_CMD} run -v ${PWD}:/data/ --user "$(id -u):$(id -g)" ${DOCKER_REPO}:${DOCKER_TAG} "$@"
```

which works for docker, but not for podman, as the reasons stated above.

Adding `--userns keep-id` to the `exec` line doesn't work for docker, as docker doesn't support `--userns keep-id`.
Removing `--user "$(id -u):$(id -g)"` from the `exec` line doesn't work for docker either. Although the script works, the files generated by the script will be owned by `root:root` instead of the current user on the host machine (podman does not have this problem).

`podman --userns keep-id run ...` doesn't work either as `--userns` is a flag for `run` subcommand, not the global command (so I cannot just set `DOCKER="podman --userns keep-id"` env).

I guess the best workaround right now is to change the script to replace the whole `docker run` (vs. only replace `docker`) via environment variable, so that for podman our devs can set it to `DOCKER_RUN="podman run --userns keep-id"`. It would be great if this use case can be supported better in future versions of podman, but my immediate problem is resolved. Thanks!

**Comment by rhatdan** [comment]
Docker runs as root without the user namespace. Podman would probably work fine for rootfull mode.  If you want to run rootless, I would check to see if the script is running as rootless and running Podman then adjust the --user or --userns flag.

**Comment by fishy** [comment]
@rhatdan how do I check whether podman is running in rootless or rootful mode?

I think overall devs are not supposed to run thrift compiler as root so they are very unlikely to run the script as root either, but checking for it is a good idea anyways.

**Comment by rhatdan** [comment]
$ if [ $(id -u) -ne 0 ];then echo non root; fi
non root
