### ISSUE TITLE
Existence of user storage.conf (rootless) causes driver errors

### ISSUE THREAD

**Issue by rauar** [containers/podman#11778]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Overriding the system-wide storage.conf is causing errors.

Without user-specific storage.conf podman works fine. As soon as I create $HOME/.config/containers/storage.conf with this content (which is identical with the system-wide settings):

```
[storage]
driver = "overlay"
graphroot="$HOME/.local/share/containers/storage"
```

any podman commands fail with this error:

```
$ podman info
ERRO[0000] User-selected graph driver "overlayfs" overwritten by graph driver "overlay" from database - delete libpod local files to resolve 
Error: kernel does not support overlay fs: 'overlay' is not supported over <unknown> at "/home/xxx/.local/share/containers/storage/overlay": backing file system is unsupported for this graph driver
```

I wiped $HOME/.local completely and still the error persists.

My goal is to use an additional disk for storing containers for a particular user - I'd like to change graphRoot therefore on a user-basis.

For the storage driver I tried ```driver = "fuse-overlayfs"```as well which did not help.

**Steps to reproduce the issue:**

1. Create file $HOME/.config/containers/storage.conf and add this content:
```
[storage]
driver = "overlay"
graphroot="$HOME/.local/share/containers/storage"
```

2. Run "podman info"

**Describe the results you received:**

$ podman info
```
ERRO[0000] User-selected graph driver "overlayfs" overwritten by graph driver "overlay" from database - delete libpod local files to resolve 
Error: kernel does not support overlay fs: 'overlay' is not supported over <unknown> at "/home/xxx/.local/share/containers/storage/overlay": backing file system is unsupported for this graph driver
```
**Describe the results you expected:**

Usual output of podman info with all settings.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman --version
podman version 3.2.3
```

**Output of `podman info --debug`:**

same error as with "podman --version" above

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.2.3-0.11.module+el8.4.0+12050+ef972f71.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"
````

```
$ uname -a
Linux xxx 4.18.0-305.19.1.el8_4.x86_64 #1 SMP Tue Sep 7 07:07:31 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ rpm -q fuse-overlayfs
fuse-overlayfs-1.6-1.module+el8.4.0+11822+6cc1e7d7.x86_64
```

```
$ head -n 15 /etc/containers/storage.conf 
# This file is is the configuration file for all tools
# that use the containers/storage library.
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver, Must be set for proper operation.
driver = "overlay"

# Temporary storage location
runroot = "/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"
```

Filesystem is ext4.

**Comment by rauar** [comment]
If I switch the driver to "overlay" instead of "overlayfs" in the user's storage.conf I still receive an error:

```
$ podman info
Error: kernel does not support overlay fs: 'overlay' is not supported over <unknown> at "/home/xxx/.local/share/containers/storage/overlay": backing file system is unsupported for this graph driver
```

**Comment by Luap99** [comment]
Can you try adding:
```
[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
```
Your kernel does not support rootless overlayfs.

**Comment by rauar** [comment]
> Can you try adding:
> 
> ```
> [storage.options.overlay]
> mount_program = "/usr/bin/fuse-overlayfs"
> ```
> 
> Your kernel does not support rootless overlayfs.

Wow. This helped. Thanks a lot. The error is gone and podman info outputs all settings nicely.

However I'm still puzzled because ```mount_program = "/usr/bin/fuse-overlayfs"``` is already defined in /etc/containers/storage.conf. And as I did not define mount_program in the user's storage.conf at all I would assume it should still be valid/applied.

**Comment by rhatdan** [comment]
Users storage.conf does not currently inherit from the system one, it overrides it.

**Comment by mheon** [comment]
We need to make this more clear - maybe a comment at the top of the system-level `storage.conf` that this is not inherited by rootless users?

**Comment by rhatdan** [comment]
Sure you have to be clear on the wording.  Open a PR in containers/storage.

**Comment by PavelSosin-320** [comment]
It will be awesome to inimize using Path environment variables in the storage.conf and use only configuration files merge because manipulation with environment in the systemd units is the hell: generators + Environment= + EnvironmentFile=  + PassEnvironment= + PostExec=systemctl --user --export-environment, DBUS .....

**Comment by PavelSosin-320** [comment]
@rauar Why you didn't create symbolic link ?
