### ISSUE TITLE
RFE: podman machine with hyperkit (on MacOS)

### ISSUE THREAD

**Issue by typekpb** [containers/podman#11797]
/kind feature

**Description**

I'd love to see podman machine supporting hyperkit as an alternative to qemu on MacOS.

**Steps to reproduce the issue:**

1. `podman machine init && podman machine start`

**Describe the results you received:**
 uses on MacOS in the background quemu

**Describe the results you expected:**
I'd love to have an option to use hyperkit (as rumors say, that it should be more performant)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm running MacOS

**Comment by baude** [comment]
@typekpb can you substantiate the claim?  our machine code is heavily interfaced so it could be a possibility to be able to do it.  Hyperkit would also need the ability to shove the ignition file into the vm as well.

**Comment by afbjorklund** [comment]
I think Docker are deprecating HyperKit for an internal implementation, talking to the Apple frameworks

These are the same Hypervisor.framework and Virtualization.framework that QEMU uses

**Comment by rhatdan** [comment]
Since we have had no response and I do not see us doing this in the short time, I am closing.
