### ISSUE TITLE
RFE: Native windows containers support on windows

### ISSUE THREAD

**Issue by isanych** [containers/podman#11809]
/kind feature

**Description**

Currently podman running only linux containers. Windows containers are younger than linux ones and less widespread, but they do exists and growing in popularity. As Docker Desktop is not free for companies anymore and there is no official way to install Docker CE on windows there is increasing need in a free container tools for windows.
Microsoft will stop support of Docker EE in September 2022, so not only Windows client but Windows server will loose free container tools too.

To be clear, I'm talking about windows containers like `mcr.microsoft.com/windows/server:ltsc2022` running on windows without any virtualization involved (like `docker run --isolation=process` does).
This is not a duplicate of #8136 which wants to run windows containers on linux
This is not a duplicate of #11494 which wants to run linux containers on windows

I understand that it is a huge undertaking, but I think it is a good time to have docker alternative on windows.

**Comment by rhatdan** [comment]
This  would be all about contributors.  The core team are all Linux. So need windows experts to make this happen.

**Comment by gbraad** [comment]
So far, Microsoft themselves have been focusing on utilizing Docker Desktop to enable Windows containers. Although, some work has been done by the community to use containerd https://www.jamessturtevant.com/posts/Windows-Containers-on-Windows-10-without-Docker-using-Containerd/ More about the internals to enable this can be found in this blog article: https://poweruser.blog/hands-on-windows-container-internals-c9782d0115ff

**Comment by gbraad** [comment]
One of the first actions would be to allow eg. skopeo to run on windows and download the container images, and use `wclayer` to create the needed `sandbox.vhdx` to run with `runhcs`. This would have to be broken down in several steps among the tools in question.

**Comment by slonopotamus** [comment]
> not only Windows client but Windows server will loose free container tools too

You might want to take a look at [Stevedore](https://github.com/slonopotamus/stevedore) project as a way to install modern Docker engine for Windows containers on both Windows Server/Client.

**Comment by gbraad** [comment]
@slonopotamus It seems stevedore is a recompile/repackaging of the Docker tools on Windows. What would it take to enable Windows containers to be used with `podman` natively?

**Comment by rhatdan** [comment]
Windows Engineers.

**Comment by vrothberg** [comment]
@containers/podman-maintainers, I vote for closing this issue.  I don't think we can realistically ship a feature that no maintainer has experience in.  We're Linux engineers.
