### ISSUE TITLE
podman build is throwing an error at gradlew

### ISSUE THREAD

**Issue by babubalagani** [containers/podman#11814]
We have a plan to migrate from Docker to Podman, as part of the process when we try to build the same docker file with podman we are facing issues at gradlew command.

Podman version = 1.6.4
Gradle version = 4.8

issue: Error: error building at STEP "RUN ./gradlew build test jacocoTestReport sonarqube": error while running runtime: exit status 1
Build step 'Execute shell' marked build as failure

Logs:
=====
FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
Error: error building at STEP "RUN ./gradlew build test jacocoTestReport sonarqube": error while running runtime: exit status 1
Build step 'Execute shell' marked build as failure
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Error: error building at STEP "RUN ./gradlew build test jacocoTestReport sonarqube": error while running runtime: exit status 1
Build step 'Execute shell' marked build as failure

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
BUG REPORT
/kind bug

**Description**

Error: error building at STEP "RUN ./gradlew build test jacocoTestReport sonarqube": error while running runtime: exit status 1
Build step 'Execute shell' marked build as failure

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No

**Comment by rhatdan** [comment]
Please fill out this issue, there is no info here that we can work with.

**Comment by edsantiago** [comment]
The info is actually there, but the reporter accidentally seems to have embedded it inside of the HTML comments of the template.. (This is one reason why I find templates troublesome). I seem to have Edit privs on comments, so I've taken the liberty of fixing the broken submission and am reopening. (The bug report itself is meaningless to me, and I suspect that this is something podman can't do anything about, but please take a fresh look-see at the issue and close on the merits if needed, vs closing on technicality)

**Comment by mheon** [comment]
Podman 1.6.4 is frankly ancient at this point. Please upgrade to a more recent Podman release and retest.
