### ISSUE TITLE
Ubuntu 20.04 apt download certificate expired

### ISSUE THREAD

**Issue by delight** [containers/podman#11838]
/kind bug

**Description**

Can't install or upgrade podman on xUbuntu 20.04 via apt as described in https://podman.io/getting-started/installation because of a untrusted certificate.

**Steps to reproduce the issue:**

. /etc/os-release
echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
curl -L "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key" | sudo apt-key add -
sudo apt-get update

**Describe the results you received:**

Err:15 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  Release                                                   
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 195.135.221.134 443]
.
.
.
E: The repository 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Describe the results you expected:**

Available installation or potential upgrade

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```

```

**Output of `podman info --debug`:**

```
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No need >> Installation failure !

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Comment by delight** [comment]
Same behavior on the testing release

**Comment by afro-coder** [comment]
This seems to be related to the Letsencrypt issue, that broke the internet
https://letsencrypt.status.io/pages/history/55957a99e800baa4470002da
https://www.whynopadlock.com/results/559336d5-8068-4336-9910-7151e47db561

**Comment by delight** [comment]
yes I just looked into apt-key list and it says the published key (testing) [expires: 2022-12-06]

**Comment by delight** [comment]
@afro-coder In that case even trusted=yes won't be working because the problem is with the https-cert on the opensuse-server, right? 

I guess there should be an ubuntu cert update that fixes the certififcation chain. Haven't upgraded my box yet since I just  returned from vacation. I'll look into it and leave a comment to close the issue if so.

**Comment by afro-coder** [comment]
Yeah, I was wondering what you meant by published key, from that error, it's due to the Opensuse Cert, I had to do the same on my box, even though it was updated, I still had to force renew the SSL cert.

**Comment by delight** [comment]
As I thought, the problem was in the cert chain + the ubuntu system-upgrade fixed the problem. Closing the ticket + sorry for opening it. Issue stopped me from upgrading in the first place \o/

Closing the issue!
