### ISSUE TITLE
Podman build with remote client on windows don't interpret well paths

### ISSUE THREAD

**Issue by ultymatom** [containers/podman#11845]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

Hello,

I'm using podman remote client on windows with a VM created with minikube and Hyper-V.

When I try to execute podman build, I have a problem with the paths.

I'm gonna explain with an example:
I have this app:
![image](https://user-images.githubusercontent.com/90399827/135847879-c8d4f2df-5e82-4fe6-bcc0-2e5af9f7d5b1.png)

with this file inside the views directory:
![image](https://user-images.githubusercontent.com/90399827/135847967-ded7a87b-8292-410e-afb6-d8b783380496.png)

this is my Dockerfile
![image](https://user-images.githubusercontent.com/90399827/135848064-dd06e145-b739-48ad-8344-6d3a325242c9.png)

when I execute `podman build` (on my podman remote client installed on my windows), no erros appears, the build is succesfull.

But when i tried to run my application, I add an error with a file missing, so i opened a shell prompt inside my container and saw this:
![image](https://user-images.githubusercontent.com/90399827/135849293-ee15420a-797e-4b63-beae-8ac9c33089f9.png)

All paths from windows are not understood correctly by podman. 

The only solution I have at the moment is sharing a volume between my VM and windows so that i can connect to SSH to my VM and execute the build command, but is there any another way ?

**Steps to reproduce the issue:**

1. Build any app with subfolder from windows's podman remote client

2. run this image in a container

3. open a shell prompte inside the container to check the name of files contained in subfolders

**Describe the results you received:**

Windows path are interpreted as name of the file

**Describe the results you expected:**

windows paths should be interpreted as paths

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
version 2.2.1
```

**Output of `podman info --debug`:**

```
PS C:\Users\tipaty\Downloads\gsd-master (1)\gsd-master\first-container> podman info --debug
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.17, commit: 41877362fc4685d55e0473d2e4a1cbe5e1debee0'
  cpus: 4
  distribution:
    distribution: buildroot
    version: 2020.02.12
  eventLogger: journald
  hostname: minikube
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.19.182
  linkmode: dynamic
  memFree: 130707456
  memTotal: 2081931264
  ociRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc93
      commit: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
      spec: 1.0.2-dev
      go: go1.13.15
      libseccomp: 2.4.1
  os: linux
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 19m 15.95s
registries:
  search:
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 19
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1625187279
  BuiltTime: Fri Jul  2 00:54:39 2021
  GitCommit: a0d478edea7f775b7ce32f8eb1a01e75374486cb
  GoVersion: go1.13.15
  OsArch: linux/amd64
  Version: 2.2.1
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No because I'm using minikube that still don't have podman3 included

Thank you for your time

**Comment by Luap99** [comment]
I am pretty sure that this is already fixed, please try with the latest version.
