### ISSUE TITLE
Unable to connect to Podman

### ISSUE THREAD

**Issue by fnordfish** [containers/podman#11847]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Running macOS with a lot of ssh keys and a fresh installation of podman 3.4.0, I cannot execute podman commands like `podman search busybox` or `podman machine ssh`; they all fail with a SSH error "Too many authentication failures"
 

**Steps to reproduce the issue:**

1. Have a bunch of ssh keys (I have around 10)
2. (not sure if that step is necessary, at least it's what I did) Add passphrases to those keys to the macOS keychain using `ssh-add -K .ssh/some_key`
3. Add all identities to the agent using `ssh-add -A`
4. `podman machine init`
5. `podman machine start`
6. `podman machine ssh` / `podman search busybox`

**Describe the results you received:**

```console
$ podman search busybox
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: Connection to bastion host (ssh://core@localhost:59949/run/user/1000/podman/podman.sock) failed.: ssh: handshake failed: ssh: disconnect, reason 2: Too many authentication failures
```

```console
$ podman machine ssh
Connecting to vm podman-machine-default. To close connection, use `~.` or `exit`
Warning: Permanently added '[localhost]:59949' (ECDSA) to the list of known hosts.
Received disconnect from ::1 port 59949:2: Too many authentication failures
Disconnected from ::1 port 59949
Error: exit status 255
```

**Describe the results you expected:**

SSH connection should ignore ssh agent identities and only use the known good one.

**Additional information you deem important (e.g. issue happens only occasionally):**

After trying to ssh into the machine manually (`ssh -v -i ~/.ssh/podman-machine-default core@localhost -p 59949`), I found that it will try all my other agent ssh keys, causing the machine to error with "Too many authentication failures".
Disabling agent identities using `ssh -o IdentityAgent=none [...]` worked and I could connect to the machine.
I tried to disable SSH IdentityAgent for localhost via `~/.ssh/config` and it actually worked for `podman machine ssh`, but `podman search` is still failing.

```
#  ~/.ssh/config
# this could break other user ssh connections to localhost
Host localhost
  IdentityAgent none
```

**Output of `podman version`:**

```
Client:
Version:      3.4.0
API Version:  3.4.0
Go Version:   go1.15.15
Git Commit:   6e8de00bb224f9931d7402648f0177e7357ed079
Built:        Thu Sep 30 21:11:48 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.6
Built:        Mon Aug 30 22:46:36 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.22.3
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.29-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: '
  cpus: 1
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: localhost
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.13.16-200.fc34.x86_64
  linkmode: dynamic
  logDriver: ""
  memFree: 1664008192
  memTotal: 2061852672
  ociRuntime:
    name: crun
    package: crun-1.0-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.0
      commit: 139dc6971e2f1d931af520188763e984d6cdfbf8
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 0
  swapTotal: 0
  uptime: 17m 38.75s
plugins:
  log: null
  network: null
  volume: null
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.1
  Built: 1630356396
  BuiltTime: Mon Aug 30 20:46:36 2021
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.3.1


```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

Using the binary distribution as described in https://github.com/containers/podman/blob/main/docs/tutorials/mac_experimental.md

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Could not find a relevant entry in there :(

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@baude @ashley-cui PTAL

**Comment by baude** [comment]
@jwhonce have you seen any change in the upstream library on this one? did we report it?
