### ISSUE TITLE
Container sigkill after stop timeout not logged as error

### ISSUE THREAD

**Issue by pboguslawski** [containers/podman#11854]
/kind bug

**Description**

If `podman stop` kills container after timeout, no info about timeout is logged in journal/stderr; killing container after timeout should be treated as dangerous because of data loss possibility so message

https://github.com/containers/podman/blob/800e91dafd47c284489be586bd18c3cdf7dc5737/libpod/oci_conmon_linux.go#L438

priority should be higher than info (at least warn) and systemd unit files generated with podman generate should produce such warnings to journal/syslog in case of killing container by podman with sigkill.

Using `podman stop --log-level=info` is not an option because it produces too much noise.

**Steps to reproduce the issue:**

1. Run any container that need >1s to stop.

2. Stop it using `podman stop --time=1`

**Describe the results you received:**

No traces in journal/syslog about container killing.

**Describe the results you expected:**

Journal/syslog should contain message about stop timeout and container killing with level warn (or maybe even error).

**Comment by rhatdan** [comment]
Interested in opening a PR to fix?

**Comment by edsantiago** [comment]
I agree that falling back to SIGKILL is noteworthy, but I'm not convinced that `podman stop` is the right place for this. The careful developer makes sure to check container exit status:
```console
$ podman run --name foo -d alpine sleep 100
7e6c79489feac65fa34353146047214e05014c30bf4efa048b09192c29c5513c
$ podman stop --time=1 foo
foo
$ podman inspect --format '{{.State.ExitCode}}' foo
137
```
In an automated environment, a warning would be of limited use: nobody would see it. In an automated environment, it really is kind of important for the developer to check container exit status.

When playing on the command line, I can see a "timed out" warning being mildly helpful -- but in this environment the user will (presumably) also notice the timeout delay itself. 

@pboguslawski in what scenario do you think this kind of warning would actually help someone?

**Comment by rhatdan** [comment]
You could change the --log-level info command on the podman stop command to see this output.

**Comment by mheon** [comment]
I don't know if this is worthy of printing by default - `podman stop` on a container running a binary that ignores signals (sleep is a good example) will always trigger it, so my feeling is that we'll be printing this warning a lot, there's not much the user can do to resolve it (maybe some binaries are like systemd and require a specific stop signal but that seems to be the minority), and it will increase logspam making it more difficult to locate serious problems.

**Comment by pboguslawski** [comment]
> You could change the --log-level info command on the podman stop command to see this output.

Adding `--log-level info` to systemd service unit file fills journal with too much noise; this particular message level should be warn or error (if warn then podman should generate unit files with `podman stop --log-level warn` to feed journal with it in case of timeout).

> I don't know if this is worthy of printing by default 

IHMO: its definitely more important message than podmans messages like container died/cleaned up/etc.

**Comment by edsantiago** [comment]
@pboguslawski thanks, that's a good point (your use case in systemd). I think your proposal is promising: the timeout really should IMHO be more important than `info` (although absolutely not `error`-level); and by automatically setting `log-level` in the unit file, the warning will be visible to log scrapers but not simple schmoes playing with `sleep` containers on the command line.

**Comment by rhatdan** [comment]
Podman defaults to log-level Warn, the question would be do we raise it to Warn, so it is in everyones face when it happens. I am ok with it, but if users start to complain, then we might want to revisit it.
@pboguslawski Please open a PR.

**Comment by mheon** [comment]
If we actually do this, be prepared for the integration tests to break in a lot of places - which might not be the worst thing, considering we usually shouldn't be waiting for that timeout anyways.

**Comment by edsantiago** [comment]
>Podman defaults to log-level Warn

Man page says "error", which is why I was OK with raising the severity of this message.
* If the man page is wrong, can someone please fix it? (I would offer, but I'm OOTO tomorrow with no net access)
  * Also if the man page is wrong, then I withdraw my comments above. I don't think this would be a useful warning for regular users. And `int` tests will be unaffected, because they don't really check any output anywhere, but `sys` tests may need a bit of massaging.

**Comment by mheon** [comment]
Manpages are wrong, then - we swapped to Warn around 9 months ago, AFAIK.
