### ISSUE TITLE
make install and systemd.service files: inconsistent handling of /usr/**local/**bin/podman

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#11858]
On the v3.4 branch `make && make install` calls

```
install  -m 755 bin/podman /usr/local/bin/podman                                                                                        
install  -m 644 contrib/systemd/system/podman.service /usr/local/lib/systemd/system/podman.service
install  -m 644 contrib/systemd/system/podman-restart.service /usr/local/lib/systemd/system/podman-restart.service
```

podman(-restart).service contain:
```
podman-restart.service:ExecStart=/usr/bin/podman $LOGGING start --all --filter restart-policy=always
podman.service:ExecStart=/usr/bin/podman $LOGGING system service
```
so the podman executable is installed in /usr/local/bin/podman , but the installed .service files execute /usr/bin/podman : the difference is `/local`.

**Comment by edsantiago** [comment]
Dup of #11788, which was closed WONTFIX.

**Comment by vrothberg** [comment]
Thanks for reaching out.  As mentioned above, https://github.com/containers/podman/pull/11788 was closed as won't fix since there are conflicting interests.  It has a low priority to me and I did not want spend more time trying to find consensus.

But feel free to open a PR to drive the discussion to an agreement.

**Comment by dilyanpalauzov** [comment]
Most source-code distributions follow a common schema : `./configure && make && make install` does provide reasonable defaults.  Deviating from this common pattern causes headaches, while sticking to it causes no headaches.  An example of deviation causing headache is the default socket utilized by dbus on `./configure && make install` and the default dbus socket looked by systemd by just calling `meson && ninja install` (the problem is the same: the `local/` part in the socket name).

While this change can be looked at frmo many different perspectives, as a rule of thumb, the source code shall be provided in such a way, that it works out of the box on a Linux from Scratch system.  Distributions can do customizations during packaging, as they want.

Podman has no configure phase, just `make && make install`.  It does install the service files.  The trivial fix is:
```diff
$ git diff -U0
diff --git a/contrib/systemd/auto-update/podman-auto-update.service b/contrib/systemd/auto-update/podman-auto-update.service
index dc5fac8cf..9822ecd3b 100644
--- a/contrib/systemd/auto-update/podman-auto-update.service
+++ b/contrib/systemd/auto-update/podman-auto-update.service
@@ -9,2 +9,2 @@ Type=oneshot
-ExecStart=/usr/bin/podman auto-update
-ExecStartPost=/usr/bin/podman image prune -f
+ExecStart=/usr/local/bin/podman auto-update
+ExecStartPost=/usr/local/bin/podman image prune -f
diff --git a/contrib/systemd/system/podman-restart.service b/contrib/systemd/system/podman-restart.service
index baf12b3ae..2af8bff48 100644
--- a/contrib/systemd/system/podman-restart.service
+++ b/contrib/systemd/system/podman-restart.service
@@ -9 +9 @@ Environment=LOGGING="--log-level=info"
-ExecStart=/usr/bin/podman $LOGGING start --all --filter restart-policy=always
+ExecStart=/usr/local/bin/podman $LOGGING start --all --filter restart-policy=always
diff --git a/contrib/systemd/system/podman.service b/contrib/systemd/system/podman.service
index cefb13ae3..ee066da3f 100644
--- a/contrib/systemd/system/podman.service
+++ b/contrib/systemd/system/podman.service
@@ -12 +12 @@ Environment=LOGGING="--log-level=info"
-ExecStart=/usr/bin/podman $LOGGING system service
+ExecStart=/usr/local/bin/podman $LOGGING system service
```

**Comment by rhatdan** [comment]
Open a PR. the problem with your change is if I specify --prefix=/usr then your systemd files are broken.

**Comment by vrothberg** [comment]
Yes, the proposed patch is just changing one problem for another.  Please read through #11788 before opening a PR.

**Comment by dilyanpalauzov** [comment]
See https://github.com/containers/podman/pull/11870#issuecomment-936238661.
