### ISSUE TITLE
podman create: Unable to close conn: \"close unixpacket @->/proc/self/fd/11/attach: use of closed network connection

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#11856]
New flake exposed by #11776:
```
# # podman create docker-archive:/tmp/podman_bats.lhLlzc/archive.tar
...
# dea245e90d8c9b4a645a71d9c20b8e80a3b913e3c41b5327016fe6d9a421533d
# # podman start --attach dea245e90d8c9b4a645a71d9c20b8e80a3b913e3c41b5327016fe6d9a421533d
# h6XQEUDR3lEH7VjgGUcd
# time="2021-10-01T07:26:23-05:00" level=error msg="Unable to close conn: \"close unixpacket @->/proc/self/fd/11/attach: use of closed network connection\""
# #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# #|     FAIL: 'podman run' of 'podman-create docker-archive'
# #| expected: 'h6XQEUDR3lEH7VjgGUcd'
# #|   actual: 'h6XQEUDR3lEH7VjgGUcd'
# #|         > 'time="2021-10-01T07:26:23-05:00" level=error msg="Unable to close conn: \"close unixpacket @->/proc/self/fd/11/attach: use of closed network connection\""'
# #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
### sys: podman run docker-archive
* fedora-33 : sys podman fedora-33 rootless host
  * PR #11816
    * [10-01 16:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5764230893797376/html/sys-podman-fedora-33-rootless-host.log.html)
* fedora-34 : sys podman fedora-34 root host
  * PR #11808
    * [10-01 08:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5370273005305856/html/sys-podman-fedora-34-root-host.log.html)

Looking through `cirrus-flake-grep`, I see this happening as far back as June (when I started collecting logs). This is an old bug, not a new one.

**Comment by edsantiago** [comment]
[another one](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6449789597384704/html/sys-podman-fedora-33-root-host.log.html)

**Comment by Luap99** [comment]
The code will call close twice. 
https://github.com/containers/podman/blob/c963a500909055db3890c42b10d7bb55f379031d/libpod/oci_attach_linux.go#L220-L224
https://github.com/containers/podman/blob/c963a500909055db3890c42b10d7bb55f379031d/libpod/oci_attach_linux.go#L163-L167
If `CloseWrite` is called before `Close`, everything is fine but if `Close` was called first, `CloseWrite` will fail.
I think we can just remove the `CloseWrite` call.
