### ISSUE TITLE
Network create test: nslookup: timed out, no servers could be reached

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#11871]
Twice in the same Zuul run ([podman](https://fedora.softwarefactory-project.io/logs/51/51/555a5a504dd538d5be581f76a5a1fe72aec1e059/check/rpm-test/704d387/artifacts/test.podman-rootless-cgroupsv2.bats.log) and [podman-remote](https://fedora.softwarefactory-project.io/logs/51/51/555a5a504dd538d5be581f76a5a1fe72aec1e059/check/rpm-test/704d387/artifacts/test.podman-remote-rootless.bats.log), both rootless):
```console
not ok 249 podman network create
$ podman run -d --network testnet-MCsl9jiJ42 -p 127.0.0.1:54322:54322 quay.io/libpod/testimage:20210610 nc -l -n -v -p 54322
14bd66a379be97bb057d2fb5c509ccab621c6ca6d64557b104ec3b8235a63237
$ podman exec 14bd66a379be97bb057d2fb5c509ccab621c6ca6d64557b104ec3b8235a63237 nslookup google.com
;; connection timed out; no servers could be reached
[ rc=1 (** EXPECTED 0 **) ]
```
I have a vague memory that this happened on one of last week's builds, but went away when I pressed Rerun.

I can't reproduce on a 1minutetip VM. The string "`no servers could be reached`" does not appear in my flake logs. It only seems to happen in Zuul (it also happened [last week](https://fedora.softwarefactory-project.io/logs/50/50/ec6ea5bdc9b449e8d5c0029d72406a5adf253822/check/rpm-test/0031722/artifacts/)). I have no idea what the Zuul environment looks like, but it _has_ to have working network: podman couldn't pull images otherwise.

This isn't super-critical: we don't use Zuul except for fedpkg PRs. But if Zuul is seeing it, real users might be seeing it too. Reasons for filing:
* Can anyone see an obvious reason why this would fail under Zuul?
* If not, can we add debug info to the test to help diagnose?
* If not, can the test be rewritten so it uses something other than `nslookup`?

**Comment by edsantiago** [comment]
Hmmmmmm..... I was right in the middle of responding when I had an idea: is it possible that `nslookup` uses `/etc/resolv.conf`, but the host itself uses the new systemd-type name resolution? I remember having nightmareish problems when my Fedora "upgraded" to use that, and me having to disable it, but don't remember what those problems were. If that's the problem, then `ping` might actually work because `google.com` would be resolved by the system, not `nslookup`. But then again I really have no clue.

**Comment by Luap99** [comment]
Yeah I would prefer to keep nslookup because this only uses the dns protocol.

Assuming the system has a working internet connection and a correctly configured `/etc/resolv.conf` on the host then one following problems could happen:
1. The container has the wrong nameserver ip in `/etc/resolv.conf`
2. The dnsmasq process for this network is miss configured or died.
3. The rootless CNI slirp4netns process died.
4. The `/etc/resolv.conf` in the rootless CNI namespace was setup incorrectly.

**Comment by rhatdan** [comment]
Should the test cat out the /etc/resolv.conf when it fails. Or always so we can at least see it.

**Comment by edsantiago** [comment]
Yesterday's [3.4.4-1.fc36 build](https://bodhi.fedoraproject.org/updates/FEDORA-2021-dd9a3bc3d2) passed its gating tests; the [previou build](https://bodhi.fedoraproject.org/updates/FEDORA-2021-675fab67a0) failed, but not with this error. Closing until it happens again.
