### ISSUE TITLE
WSL2 support is wrong

### ISSUE THREAD

**Issue by jfmatth** [containers/podman#11872]
/kind bug

**The instructions for WSL2 to the RedHat link do not work anymore**

**Steps to reproduce the issue:**

1. Follow the instructions from the installation page to install for WSL2  https://www.redhat.com/sysadmin/podman-windows-wsl2

2. The repository it has you add http://download.opensuse.org/repositories/devel is no longer available.

3.

**Describe the results you received:**
When updating APT, you get a repository not found error

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
is the way to install for WSL2 just to use the static version?

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
Thanks for reaching out.  Which Linux distribution are you running on?  If it's Ubuntu, podman may already be in the repositories.

**Comment by jfmatth** [comment]
WSL2 Ubuntu 20.04.3 LTS
```
 jfmatth@Dad-dell5580  ~  more /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
```

it is installable on regular (non-WSL) ubuntu, but I don't see that here
```
 jfmatth@Dad-dell5580  ~  sudo apt-get update
Hit:1 https://packages.microsoft.com/repos/azure-cli focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done
 jfmatth@Dad-dell5580  ~  sudo apt-get install podman
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package podman is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'podman' has no installation candidate
 ✘ jfmatth@Dad-dell5580  ~ 
```

I used the original instructions  before the repository was removed, can someone put that back?

I am willing to build from source, but not sure if those instructions will apply here?

I tried using the static version, but seems like there are is a socket / service missing :(

**Comment by jfmatth** [comment]
Odd, in digging into the instructions more, it seems the copy/paste of the Release Key command borked something.  Once I correct that, it works :)

I think it might be my ZSH messing with the copy/paste, if i use BASH then it works great - Weird

copy/paste with ZSH yields the following (notice the extra backslashes)
```
 jfmatth@Dad-dell5580  ~  wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x$\{NAME\}_$\{VERSION_ID\}/Release.key -O Release.key

https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x$%7bNAME%7d_$%7bVERSION_ID%7d/Release.key:
2021-10-06 04:15:25 ERROR 404: Not Found.
```

but switching to BASH works fine, odd.
```
 ✘ jfmatth@Dad-dell5580  ~  bash
jfmatth@Dad-dell5580:~$ . /etc/os-release
jfmatth@Dad-dell5580:~$ wget -nv https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x${NAME}_${VERSION_ID}/Release.key -O Release.key
2021-10-06 04:16:22 URL:https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key [1093/1093] -> "Release.key" [1]
jfmatth@Dad-dell5580:~$
```

Well, it seems to work as published now, sorry for the headaches

**Comment by vrothberg** [comment]
Thanks, @jfmatth!  I am glad it's working.
