### ISSUE TITLE
Using `--pid=host` in rootless mode doesn't clean up backgrounded child processes (including conmon)

### ISSUE THREAD

**Issue by kanaka** [containers/podman#11888]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Using `--pid=host` in rootless mode means any background processes and the conmon process itself will continue running even after the podman container is stopped/deleted.

**Steps to reproduce the issue:**

1. Start a rootless container like this `podman run -it --pid=host ubuntu bash`

2. Start a background process: `sleep 86400 &`

3. Exit the container

4. Look at your process tree and see that conmon and the background process are still running.

**Describe the results you received:**

podman/conmon are not cleaning up backgrounded processes.

**Describe the results you expected:**

podman/conmon should clean up backgrounded process started within the container regardless of whether `--pid=host` is used or not.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.6
Built:        Wed Dec 31 18:00:00 1969
OS/Arch:      linux/amd64
```

I have also tried a source built podman with the same results:

```
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.13.8
Git Commit:   1de96f2c4c390bae29c303e2390da9e87a993d3f
Built:        Fri Oct  1 17:18:12 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.22.3
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 8
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: kanaka
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.11.0-37-generic
  linkmode: dynamic
  memFree: 184606720
  memTotal: 12550447104
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 1.1.5-7b4a-dirty
      commit: 7b4a7042370eea7fb00d3a4da34332b26f080acd
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 6013296640
  swapTotal: 11999899648
  uptime: 190h 22m 53.45s (Approximately 7.92 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/joelm/.config/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 0
    stopped: 5
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/joelm/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 66
  runRoot: /run/user/1000/containers
  volumePath: /home/joelm/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.1
  Built: 0
  BuiltTime: Wed Dec 31 18:00:00 1969
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.3.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 100:3.3.1-1 amd64 [installed]
podman/unknown 100:3.3.1-1 arm64
podman/unknown 100:3.3.1-1 armhf
podman/unknown 100:3.3.1-1 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Comment by mheon** [comment]
The core problem is that Conmon is attached only to PID 1 of the container. In a container with a PID namespace, that's perfectly acceptable as PID 1 in a PID namespace dying, causes the kernel to kill every other process in the namespace; since there is no longer a PID namespace, we no longer have that guarantee.

I suppose we could change Podman's state transition code for stopped -> exited (unmount the container, tear down the network) to also do a `crun kill --all` on the container to ensure all processes are gone. Alternatively, we could add a check of sorts to Conmon to check if there are remaining processes in the cgroup, and possibly kill them, when PID 1 exits?

@giuseppe @haircommander @rhatdan Thoughts?
