### ISSUE TITLE
Non-deterministic /sys mount behavior (rootless) means `ip netns exec` sometimes fails

### ISSUE THREAD

**Issue by kanaka** [containers/podman#11887]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I have a network test environment that creates containers with network namespaces/interfaces within containers. I was experimenting with using rootless podman instead of docker. With the full setup I was seeing occasional permissions failures when trying to run `ip netns exec NS CMD` within the container. I was able to simplify the process until I was able to determine that the failure is caused by non-deterministic mounting behavior of the `/sys` file-system.

A couple of small scripts (and some example output) that I use to quickly test this are at https://gist.github.com/kanaka/950e307e1c8c9ccbea70de04d0267894

**Steps to reproduce the issue:**

1. Build a container image with iproute2 installed

2. Launch the container using a specific set of volume mounts that includes `$HOME/.local/share/containers/storage/overlay` plus some other volume mounts. Removing the `.local` mount means it always fails for me. Adding additional mounts changes the frequency of the behavior (ranging from 100% in either direction to about 50% failures).

3. Create a iproute2 style netns and then try to run a command using that netns (e.g. `ip netns exec NS CMD`).

**Describe the results you received:**

Some runs of the container results in `ip netns exec NS CMD` working, and other runs of the container (identical command line) will cause it to fail with a `mount of /sys failed: Operation not permitted`.

**Describe the results you expected:**

The `ip netns exec NS CMD` should always work.

**Additional information you deem important (e.g. issue happens only occasionally):**

When the command works, the following sysfs related mounts appear in the container:

```
...
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
...
sysfs on /overlay/5089005f7b65568a0b0137a619a4fce517bacf7066e0c93cf499e87d05f9c6d2/merged/sys type sysfs (rw,nosuid,nodev,noexec,relatime)
```

When it doesn't work, the second mount is missing and the first read-only one usually appears later in the mount list.

**Output of `podman version`:**

```
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.6
Built:        Wed Dec 31 18:00:00 1969
OS/Arch:      linux/amd64
```

I have also tried building podman from source and using that with the same behavior:

```
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.13.8
Git Commit:   1de96f2c4c390bae29c303e2390da9e87a993d3f
Built:        Fri Oct  1 17:18:12 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.22.3
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 8
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: kanaka
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.11.0-37-generic
  linkmode: dynamic
  memFree: 225910784
  memTotal: 12550447104
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 1.1.5-7b4a-dirty
      commit: 7b4a7042370eea7fb00d3a4da34332b26f080acd
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 6009597952
  swapTotal: 11999899648
  uptime: 190h 6m 30.44s (Approximately 7.92 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/joelm/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/joelm/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 66
  runRoot: /run/user/1000/containers
  volumePath: /home/joelm/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.1
  Built: 0
  BuiltTime: Wed Dec 31 18:00:00 1969
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.3.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 100:3.3.1-1 amd64 [installed]
podman/unknown 100:3.3.1-1 arm64
podman/unknown 100:3.3.1-1 armhf
podman/unknown 100:3.3.1-1 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Can you provide the output of `mount` from inside the container in a container that works, and one that does not?

**Comment by kanaka** [comment]
BTW, the context here is that I am attempting to get conlink working with rootless podman. conlink (https://github.com/LonoCloud/conlink) enables containers to be networked together with an arbitrary mininet defined network (with routers, switches, smart OVS bridges, tc policy, etc). With a few non-invasive tweaks to conlink I've gotten it to work with rootless podman. The remaining problems are: I periodically see this sysfs problem (unable to `ip netns exec`), and also that it leaves some droppings in the process tree (due to https://github.com/containers/podman/issues/11888)

**Comment by giuseppe** [comment]
the kernel doesn't allow to mount a sysfs file system in a user namespace unless there is already a writeable sysfs mount.

When it works for you, it is because sysfs is already mounted as rw at `/overlay/$CID/merged/sys`

I'd need to investigate further to be 100% sure, but I bet the fact that sometimes sysfs appears as rw could be a race condition in how the mounts are propagated in the two different mount namespaces.

Since `ip` always mount sysfs, it somehow expects to be running in the init user namespace, or to have a rw sysfs mount available (and not covered).

I'd suggest that you just use `--privileged` that forces sysfs to be mounted `rw`.

**Comment by kanaka** [comment]
`--privileged` doesn't actually fix the problem for me. It **does** result in the `/sys` mount always being `rw`. However, the `ip netns exec NS CMD` still fails. The determining factor on whether it works on not is whether the second sysfs mount appears or not.

If it looks like this then the problem will still happen:

```
root@4551f56be1da:/# mount | grep sysfs
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
```

If it looks like this, then the `ip netns exec NS CMD` works:

```
root@fadd2fa44752:/# mount | grep sysfs
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
sysfs on /overlay/882c39449583767875556d147ca643874f93f5f5a30e1c678ed08bb60c847048/merged/sys type sysfs (rw,nosuid,nodev,noexec,relatime)
```

So whether I use `--privileged` or `--cap-add SYS_ADMIN`, the problem still happens and the key is whether the second `sysfs` mount is setup or not. And that appears to be some sort of mount ordering issue because when there are two sysfs mounts then the plain one appears much earlier in the list. Note that with `--privileged` and `crun` it seems to break a lot less frequently that with `--privileged` and `runc`.

**Comment by giuseppe** [comment]
I see.

When ip works, it is because there is already a mounted sysfs visible (the one mounted at `/overlay/$CID/merged/sys`) so the kernel doesn't complain.

If there is only one `sysfs` mounted, then ip does "unmount("/sys"); mount("/sys")" and the mount fails since there is no `/sys` available anymore.

Not sure how this case can be addressed in the container runtime.

Would it work if you also add something like "mount -t sysfs --make-private /random/path` before calling `ip netns`?

**Comment by kanaka** [comment]
I can confirm that doing the `mount -t sysfs --make-private /sys2` allows the `ip netns exec` command to work (even in the case where it's initially broken due to only a single read-only sysfs mount).

Interestingly that trick only needs `SYS_ADMIN` to work with `crun` whereas with `runc` it requires `--privileged`.

**Comment by giuseppe** [comment]
Thanks for confirming it.  I think the difference between runc and crun is likely some race condition when the mounts are propagated, and I don't think we can control it (either from runc/crun or from Podman).

IMO, the cleanest fix would be that `ip netns` doesn't attempt to umount the sysfs. In this way, it would work in a namespace without such sort of hacks on your side.

I will close the issue because I don't think there is anything we can do in Podman or in the OCI runtimes, but feel free to comment further, or reopen it if you disagree with the decision.
