### ISSUE TITLE
FEATURE REQUEST: podman manifest rm == podman rmi

### ISSUE THREAD

**Issue by cevich** [containers/podman#11899]
/kind feature

**Description**

Podman should uniformly handle manifest lists and images so as to cause less user-asonishment.

**Steps to reproduce the issue:**

1. `podman rmi <manifest list>` != `podman manifest rm <manifest list>`

2. `podman push <manifest list>` != `podman manifest push --all <manifest list>`

**Describe the results you received:**

`podman rmi <manifest list>` does not always remove the manifest list itself.

`podman push <manifest list>` does not always push the manifest list itself.

**Describe the results you expected:**

`podman rmi <manifest list>` should act exactly the same as `podman manifest rm <manifest list>`
`podman push <manifest list>` should act exactly the same as `podman manifest push --all <manifest list>`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

v3.4

**Output of `podman info --debug`:**

N/A

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

N/A

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

[Original discussion was relating to a docs update.](https://github.com/containers/podman/pull/11889#pullrequestreview-774230190)

**Comment by rhatdan** [comment]
I think I can close this issue. I believe we settled on the status quo was fine.  Reopen if I am mistaken.
