### ISSUE TITLE
“See also” section at  https://docs.podman.io/en/latest/markdown/podman-build.1.html does not contain hyperlinks

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#11902]
In https://docs.podman.io/en/latest/markdown/podman-pull.1.html#see-also the SEE ALSO man pages are hyperlinked.

At https://docs.podman.io/en/latest/markdown/podman-build.1.html#see-also the SEE ALSO man pages are NOT hyperlinked.

However, other HTML renderers of the same man page manage to include hyperlinks in the SEE ALSO section: https://manpages.debian.org/unstable/podman/podman-build.1.en.html.

**Comment by flouthoc** [comment]
This is fixed for `docs.podman.io`. Closing this issue.
