### ISSUE TITLE
MacOS - podman container stats is failing with missing `cgroups v2`

### ISSUE THREAD

**Issue by iongion** [containers/podman#11909]
Context

```
➜ podman machine list
NAME                     VM TYPE     CREATED      LAST UP
podman-machine-default*  qemu        4 weeks ago  Currently running
➜ podman --version
podman version 3.3.1
```

`podman container stats ID` ends with `Error: stats is not supported in rootless mode without cgroups v2`

But

`podman machine ssh podman container stats`

Works without an issue, command is missing a remote check.

**Comment by mheon** [comment]
@jwhonce PTAL

**Comment by flouthoc** [comment]
I think the check for unified and rootless needs to be moved away from client to backend.
