### ISSUE TITLE
Podman not starting oracle enterprise container

### ISSUE THREAD

**Issue by kbul** [containers/podman#11903]
**Is this a BUG REPORT? (leave only one on its own line)**

/kind bug

When executoing the following command:

$ podman-compose up
using podman version: podman version 3.4.0
podman pod create --name=oracle --share net -p 5503:5500 -p 1521:1521
45ad43454fa8238272bb5f64e6fe5795c6de23650ec37491d2e77982ac652c4f

One cannot connect to the DB by means of for example DBEAVER client.

It stucks (providing no error) at some point of container instantiation. Attempting to connect to the database gives the following error.
Listener refused the connection with the following error:
ORA-12514, TNS:listener does not currently know of service requested in connect descriptor

Downgrading to version 3.1.0, and executing the following:

$ podman-compose up 
using podman version: podman version 3.1.0
podman pod create --name=oracle --share net -p 5503:5500 -p 1521:1521
298a4e3c427a00c7a83fd84746dba73c1a9893d6dc68a2e37be252c7f54364a9

Works fine.

Url to oracle docker image: https://hub.docker.com/_/oracle-database-enterprise-edition

**Steps to reproduce the issue:**

1. Pull the oracle docker image.
2. Run with the defaults.
3. Wait, and wait...

**Describe the results you received:**
Not able to connect to the database.

**Describe the results you expected:**
Database connection.

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue permanent.

**Output of `podman version`:**

```
3.4.0
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    variant: workstation
    version: "34"
  eventLogger: journald
  hostname: fedora-pc
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.9-200.fc34.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 12105699328
  memTotal: 33521885184
  ociRuntime:
    name: crun
    package: crun-1.1-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.1
      commit: 5b341a145c4f515f96f55e3e7760d1c79ec3cf1f
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 7h 29m 47.27s (Approximately 0.29 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/xxx/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/xxx/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  volumePath: /home/xxx/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.0
  Built: 1633030821
  BuiltTime: Thu Sep 30 21:40:21 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.0


```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.0-1.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Host running Fedora.

**Comment by mheon** [comment]
Can you provide a reproducer that doesn't use podman-compose?

**Comment by Luap99** [comment]
It looks like podman successfully starts the container. This looks like an configuration error. Can you inspect the container and provide the output please.

**Comment by kbul** [comment]
Another observation that i think is worth to mention. 
1) Started successfully oracle container with older version of the podman (podman-compose).
2) Stopped the container without removing it, i.e. podman ps does not show the running container, while podman ps -a shows that the oracle container exists.
3) Upgraded the podman to version 3.4.0 and tried to start the stopped container with the podman start <container_id> command. 

Result. I am able to connect to the DB.

**Comment by rhatdan** [comment]
@kbul is this still broken?

**Comment by kbul** [comment]
Good day @rhatdan,
Unfortunately the problem remains unchanged even though there was two updates in fedora repository since then.
Regards.

**Comment by rhatdan** [comment]
@Luap99 any more thoughts?

**Comment by kbul** [comment]
Recently we were discussing an option in which /etc/hosts entries changed. Would it work if i add those entries manually and restart the container?

**Comment by rhatdan** [comment]
Try it out, that should help.

**Comment by kbul** [comment]
Hello. Recent update to version 3.4.4 still does not solve the problem. Regards.

**Comment by kbul** [comment]
Hello. It started work again. Not sure how it happened. I did not configure anything specific. Anyway, thank you for handling the issue.
