### ISSUE TITLE
I son't see my containers (podman ps --all)

### ISSUE THREAD

**Issue by FelixLahaie** [containers/podman#11906]
I am using RHEL 8.4

I installed Podman 3.2.3 with dnf install podman

I can ** run podman hello-world ** but other containers are not showing with ** podman ps --all **

** podman build -t mycontainer. ** I do not see any errors for the construction

** podman run mycontainer --name test -p 5900: 5900 ** I see the key
48f965gb7d08b3289813d1f517621203ea5d59e534b18b3981c5e50b04b73c70

as if the container was working

** podman ps --all **: have no containers

I have the same problem with fullroot and I don't see my containers on htop or systemctl

The podman project interests me a lot, but I can't get my containers to work. What is difficult is that I do not see any errors during execution. I don't know if I did something wrong. Is there a place I need to set it up?

Thank you!

**Comment by mheon** [comment]
Please provide more details - a full `podman info` from the user you are running Podman as would help greatly. The complete output of `podman run --log-level=debug -t -i --rm fedora ls` and `podman ps --log-level=debug --all` would also be appreciated.

**Comment by FelixLahaie** [comment]
@Luap99 you right! my container with VNC service has a problem.

I see that `podman ps -a` is not the probem

Thank you!
