### ISSUE TITLE
generate kube: Do not print `spec.containers.command`, if it is the default entrypoint of the image

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#11915]
At https://github.com/containers/podman/issues/11672 I asked to alter `podman generate kube` not to print variables, which were not part of the container and not to print `spec.containers.command`. podman 3.4.0 still prints on `podman generate kube` the command, even if it is the default commant/entrypoint contained in the image.

As test case I use the instructions from https://mail.aegee.org/cgit/aegee-ldap/tree/readme.md#n13.

**Comment by Luap99** [comment]
This was already fixed in https://github.com/containers/podman/pull/11704
