### ISSUE TITLE
Podman sysvinit support for windows wsl

### ISSUE THREAD

**Issue by SerhiiTopor** [containers/podman#11910]
/kind feature

Due Docker Subscription Service Agreement update, especially in context of Docker Desktop for Windows, many devs have a need to switch to Podman, some projects use extensively docker-compose.yml. Unfortunatly **podman.socket**, as well as docker daemon, can not be used in WSL system because of discrepancy with **systemd**. But SysVinit works and it would be great if podman service socket could be run with it. It would make much easier to switch for a while and then migrate docker-compose.yml to pods and kubernetes yaml files.

WIndows 10 WSL v.2 Ubuntu- 20.04
Podman 3.3.1

systemd
```
serhii@wd:/usr/lib/systemd/user$ sudo systemctl start podman.socket
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

sysvinit
```
serhii@wd:/usr/lib/systemd/user$ sudo service podman.socket start
podman.socket: unrecognized service
```

**Comment by mheon** [comment]
You can manually run the service (`podman system service -t 0`) if you want to. Wrapping that invocation with a sysvinit service should be relatively simple? If someone wants to do it and PR it against the repo we'd be happy to merge it.

**Comment by giuseppe** [comment]
@SerhiiTopor is there anything more left to do in Podman or can we close the issue?

**Comment by SerhiiTopor** [comment]
@giuseppe yep you can close it, thank you)
