### ISSUE TITLE
Failed to start a readonly rootfs which contains colon

### ISSUE THREAD

**Issue by chenk008** [containers/podman#11913]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. podman run --rootfs /some/a:b/readonly/path:O echo hello

**Describe the results you received:**

Error: error running container create option: stat /some/a:b/readonly/path:O: no such file or directory

**Describe the results you expected:**

A new container can run and echo `hello`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.15.2
Git Commit:   ea868933e8c014ac52192f397f5dc1c3e8ee375a
Built:        Mon Oct 11 09:28:05 2021
OS/Arch:      linux/amd64```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - net_cgroup
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.27-1.el7.1.1.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 32
  distribution:
    distribution: '"alios"'
    version: "7.2"
  eventLogger: file
  hostname: arconkube-40-100088092045
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.9.151-015.ali3000.alios7.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 27575443456
  memTotal: 34359738368
  ociRuntime:
    name: runc
    package: containerd.io-internal-1.2.13-4.1.202006231713.alios7.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
      spec: 1.0.1-dev
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-4.el7.7.1.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.3.1
  swapFree: 2147479552
  swapTotal: 2147479552
  uptime: 1835h 50m 7.8s (Approximately 76.46 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 0
    stopped: 7
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.0-dev
  Built: 1633915685
  BuiltTime: Mon Oct 11 09:28:05 2021
  GitCommit: ea868933e8c014ac52192f397f5dc1c3e8ee375a
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 4.0.0-dev```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
None
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by flouthoc** [comment]
@chenk008 I am not sure but is colon `:` expected as a standard in a UNIX path ? Afaik it is a separator right ?
