### ISSUE TITLE
KO looks for credentials in ~/.docker/config.json,  podman on Mac OS does not create the file

### ISSUE THREAD

**Issue by cgruver** [containers/podman#11923]
I am building the OpenShift Pipelines Operator, ( https://github.com/tektoncd/operator), from my MacBook.

I removed Docker Desktop after they changed the licensing.  My job and my hobby blur the lines between personal and professional use, so I did not want to take any legal risk with Docker.

As an alternative, I am using Podman:

```bash
podman machine init
podman machine start
```

podman version 3.3.1

When building the Tekton Operator:

```bash
export KO_DOCKER_REPO=${LOCAL_REGISTRY}/tekton
make TARGET=openshift CR=config/default apply 
```

I get the following error:

```bash
2021/10/11 13:39:28 Publishing nexus.clg.lab:5001/tekton/operator-1d69a75f22dd094880847eac907fb2c1:latest
2021/10/11 13:39:28 Publishing nexus.clg.lab:5001/tekton/webhook-340ad78e88ca5477447aa144fedfe1a1:latest
error: no objects passed to apply
Error: error processing import paths in "-": error resolving image references: POST https://nexus.clg.lab:5001/v2/tekton/operator-1d69a75f22dd094880847eac907fb2c1/blobs/uploads/: UNAUTHORIZED: access to the requested resource is not authorized
2021/10/11 13:39:28 error during command execution: error processing import paths in "-": error resolving image references: POST https://nexus.clg.lab:5001/v2/tekton/operator-1d69a75f22dd094880847eac907fb2c1/blobs/uploads/: UNAUTHORIZED: access to the requested resource is not authorized
```

After copying `~/.config/containers/auth.json` to `~/.docker/config.json` everything works.

If this is isolated to `KO`, then maybe the issue is there, but other apps may also default to looking for credentials in `~/.docker/config.json`

Any advice?

Thanks

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by cgruver** [comment]
@imjasonh Thanks!

I'll add that to the tutorial in my blog post.

**Comment by rhatdan** [comment]
I don't see this as something we can fix.
