### ISSUE TITLE
podman restoring error

### ISSUE THREAD

**Issue by Avijit009** [containers/podman#11936]
After checkpointing at the source node I have copied those checkpointed files to the destination node and tried to restore them.
When I use the restore command the error pop up is:
`Error: did not receive systemd slice as cgroup parent when using systemd to manage cgroups: invalid argument
`
How to solve this problem? 

system using:
Ubuntu: 20.04
podman: 4.0.0-dev

Thank you.

**Comment by mheon** [comment]
Please provide more information - a full reproducer and the complete output of `podman info` on both nodes. Where did you get your Podman build - are you building from source?

**Comment by Avijit009** [comment]
Yes, that was the problem. 
Thank you.

Would you mind please, have a look at the errors
```
(00.032990) cg: Restore special props
(00.033007) cg: Restoring cgroup property value [0-3] to [cpuset/machine.slice/libpod-f7ff7ce4bd07c9d203412628370134e201ae6f24a0f8971d27306113c436cecb.scope/cpuset.cpus]
(00.033060) Error (criu/cgroup.c:1350): cg: Failed writing 0-3 to cpuset/machine.slice/libpod-f7ff7ce4bd07c9d203412628370134e201ae6f24a0f8971d27306113c436cecb.scope/cpuset.cpus: Permission denied
(00.033079) Error (criu/cgroup.c:1617): cg: Restoring cpuset.cpus special property failed
(00.033081) Error (criu/cgroup.c:1677): cg: Restoring special cpuset props failed!
```

How to solve this one? 
Thank you.

**Comment by Avijit009** [comment]
Does podman support diskless migration? 

If support then how to do that?

**Comment by rhatdan** [comment]
@adrianreber PTAL

**Comment by carlhoerberg** [comment]
The original issue is solved so this ticket should be closed. The rest is very much general questions and off topic and should go to a mailing list or forum IMHO

**Comment by adrianreber** [comment]
@Avijit009 I already described to you what is necessary to print the CRIU statistics in another ticket. It is really not helpful if you ask the same questions in different tickets.

> Does podman support diskless migration?

Yes, use `--ignore-rootfs` when exporting the checkpoint.

**Comment by Avijit009** [comment]
> @Avijit009 I already described to you what is necessary to print the CRIU statistics in another ticket. It is really not helpful if you ask the same questions in different tickets.
>  Yeah You already did. I have tried and I got my desired result. But I am asking a different thing. Maybe I have to look into it.  I was actually asking Like a checkpointing is started and besides that, I will run a command that will measure the timing from the start of the checkpointing and stop while it stops at will give me results like t1= 1ns, t2=2ns .... and I can calculate average timing from this.  

> Yes, use `--ignore-rootfs` when exporting the checkpoint.
>Thank you.

**Comment by Avijit009** [comment]
> >@Avijit009 I already described to you what is necessary to print the CRIU statistics in another ticket. It is really not helpful if you ask the same questions in different tickets.
> Yeah, You already did. I have tried and I got my desired result. But I am asking a different thing. Maybe I have to look into it.  I was actually asking Like a checkpointing is started and besides that, I will run a command that will measure the timing from the start of the checkpointing and stop while it stops at will give me results like t1= 1ns, t2=2ns .... and I can calculate average timing from this.  

>> Yes, use `--ignore-rootfs` when exporting the checkpoint.
> Thank you.

**Comment by Avijit009** [comment]
> Yes, use `--ignore-rootfs` when exporting the checkpoint.

Thank you.
Is it the same as https://criu.org/Disk-less_migration this one?

**Comment by adrianreber** [comment]
> > Yes, use `--ignore-rootfs` when exporting the checkpoint.
> 
> Thank you. Is it the same as https://criu.org/Disk-less_migration this one?

No. That is something completely different and not implemented, as far as I know, by any container runtime or container engine. Patches are always welcome.
