### ISSUE TITLE
Run subcommand doesn't care about Insecure: true

### ISSUE THREAD

**Issue by Gwerlas** [containers/podman#11933]
/kind bug

**Description**

Since the upgrade to `v3.4.0`, `podman run` trigger `http: server gave HTTP response to HTTPS client` when `podman pull` works.

**Steps to reproduce the issue:**

1. `podman run my-insecure-registry:5000/my-image:latest` trigger this error :

   ```
   Trying to pull my-insecure-registry:5000/my-image:latest...
   Error: initializing source docker://my-insecure-registry:5000/my-image:latest: pinging container registry my-insecure-registry:5000: Get "https://my-insecure-registry:5000/v2/": http: server gave HTTP response to HTTPS client
   ```

2. `podman system info` show well `Insecure: true`

3. `podman pull my-insecure-registry:5000/my-image:latest` download the image successfully

**Comment by mheon** [comment]
@vrothberg PTAL
