### ISSUE TITLE
podman system prune: error removing pod conmon cgroup: EBUSY

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#11946]
This is not a new flake, it dates back to June or earlier. Possibly I didn't file it because we have a ton of other EBUSY flakes and I thought this was the same one. Symptom seems to be:
```
time="2021-10-12T16:12:29Z" level=error msg="Deleting pod XXX 
    cgroup /libpod_parent/XXX: 
    remove /sys/fs/cgroup/misc/libpod_parent/XXX: 
    remove /sys/fs/cgroup/misc/libpod_parent/XXX/conmon:
    remove /sys/fs/cgroup/misc/libpod_parent/XXX/conmon: device or resource busy"
```
(newlines added for legibility).

### Podman prune [It] podman system prune - pod,container stopped
* fedora-33 : int podman fedora-33 root container
  * PR #11833
    * [10-01 14:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4588980671873024/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--1)
    * [10-01 14:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4588980671873024/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--2)
    * [10-01 14:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4588980671873024/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--3)
  * PR #11813
    * [09-30 18:20](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5574507558600704/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--1)
    * [09-30 18:20](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5574507558600704/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--2)
    * [09-30 18:20](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5574507558600704/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--3)
  * PR #11808
    * [10-01 09:24](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4924581564645376/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--1)
    * [10-01 09:24](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4924581564645376/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--2)
    * [10-01 09:24](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4924581564645376/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--3)
    * [10-01 08:17](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5088798028595200/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--1)
    * [10-01 08:17](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5088798028595200/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--2)
    * [10-01 08:17](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5088798028595200/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--3)
  * PR #11801
    * [09-30 07:32](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6581712890101760/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--1)
    * [09-30 07:32](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6581712890101760/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--2)
  * PR #11761
    * [09-28 12:02](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5405086852579328/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--1)
    * [09-28 12:02](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5405086852579328/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--2)
    * [09-28 12:02](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5405086852579328/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--3)
  * PR #11716
    * [09-23 11:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5054595526295552/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--1)
    * [09-23 11:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5054595526295552/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--2)
    * [09-23 11:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5054595526295552/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--3)
  * PR #11631
    * [09-21 13:15](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5077071157264384/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--1)
    * [09-21 13:15](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5077071157264384/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--2)
    * [09-21 13:15](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5077071157264384/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--3)
  * PR #11604
    * [09-22 16:22](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6420484045668352/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--1)
    * [09-22 16:22](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6420484045668352/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--2)
    * [09-22 16:22](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6420484045668352/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--3)

The fact that it only seems to happen on f33 suggests a cgroups v1 problem.

**Comment by edsantiago** [comment]
Another one, [f33 root](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5242437380603904/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--1) again

**Comment by edsantiago** [comment]
And [another](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4826143716016128/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--1)

**Comment by edsantiago** [comment]
In the past month:

### Podman prune [It] podman system prune - pod,container stopped
* fedora-33 : int podman fedora-33 root container
  * PR #12260
    * [11-11 09:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6103194125205504/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--1)
    * [11-11 09:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6103194125205504/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--2)
    * [11-11 09:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6103194125205504/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--3)
  * PR #12137
    * [11-08 08:22](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5561095936016384/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--1)
    * [11-08 08:22](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5561095936016384/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--2)
    * [11-08 08:22](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5561095936016384/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--3)
  * PR #12117
    * [10-27 10:30](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5524881811963904/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--1)
    * [10-27 10:30](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5524881811963904/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--2)
    * [10-27 10:30](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5524881811963904/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--3)
  * PR #12098
    * [10-26 13:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5640711879000064/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--1)
    * [10-26 13:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5640711879000064/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--2)
    * [10-26 13:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5640711879000064/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--3)
  * PR #12090
    * [10-26 17:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5417337877692416/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--1)
    * [10-26 17:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5417337877692416/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--2)
    * [10-26 17:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5417337877692416/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--3)
    * [10-26 16:48](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5229462619947008/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--1)
    * [10-26 16:48](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5229462619947008/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--2)
    * [10-26 16:48](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5229462619947008/html/int-podman-fedora-33-root-container.log.html#t--podman-system-prune---pod-container-stopped--3)

**Comment by edsantiago** [comment]
Still happening

### Podman prune [It] podman system prune - pod,container stopped
* fedora-34 : int podman fedora-34 root container
  * PR #12541
    * [12-08 10:42](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6553677776289792/html/int-podman-fedora-34-root-container.log.html#t--podman-system-prune---pod-container-stopped--1)
    * [12-08 10:42](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6553677776289792/html/int-podman-fedora-34-root-container.log.html#t--podman-system-prune---pod-container-stopped--2)
    * [12-08 10:42](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6553677776289792/html/int-podman-fedora-34-root-container.log.html#t--podman-system-prune---pod-container-stopped--3)

**Comment by vrothberg** [comment]
> It's all Cgroupsv1 podman-in-container.
> 
> We have a protection against this (setting parent cgroup max processes to 0, to prevent cloning, to prevent the cleanup process from launching; this is usually caused by the cleanup process still being active in the cgroup after the last container exits). Possible this doesn't work in a container?

@giuseppe could you take a look this one?

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/common/pull/858
