### ISSUE TITLE
Restoring exported runc container requires `--runtime runc`

### ISSUE THREAD

**Issue by carlhoerberg** [containers/podman#11945]
/kind bug

**Description**

Importing a checkpoint from a container using `--runtime runc`  cause `Error: OCI runtime error: CRIU restoring failed -52.`

`restore.log` ends with: 

```
(00.006773) mnt:                Will mount 638 from /
(00.006776) mnt:                Will mount 638 @ /tmp/.criu.mntns.1PjNRd/13-0000000000/proc/scsi
(00.006778) mnt:        Read 638 mp @ /tmp/.criu.mntns.1PjNRd/13-0000000000/proc/scsi
(00.006789) Error (criu/mount.c:2830): mnt: No mapping for /proc/sched_debug mountpoint
```

Restoring from a non exported checkpoint works. Then the `restore.log` looks like this:

```
(00.000885) mnt:                Will mount 638 from /
(00.000887) mnt:                Will mount 638 @ /tmp/.criu.mntns.8DLWUa/13-0000000000/proc/scsi
(00.000889) mnt:        Read 638 mp @ /tmp/.criu.mntns.8DLWUa/13-0000000000/proc/scsi
(00.000894) mnt:                Will mount 637 from /dev/null (E)
(00.000896) mnt:                Will mount 637 @ /tmp/.criu.mntns.8DLWUa/13-0000000000/proc/sched_debug
(00.000898) mnt:        Read 637 mp @ /tmp/.criu.mntns.8DLWUa/13-0000000000/proc/sched_debug
```

**Steps to reproduce the issue:**

1. `podman run --name loop -d --runtime runc alpine sh -c "while true; do date; sleep 1; done"`
2. `podman container checkpoint --export /tmp/loop.tar.zst loop`
3. `podman rm loop`
3. `podman container restore --import /tmp/loop.tar.zst`

**Describe the results you received:**

`Error: OCI runtime error: CRIU restoring failed -52.`

**Describe the results you expected:**

To be restored and continue running. 

**Additional information you deem important (e.g. issue happens only occasionally):**

Everytime

**Output of `podman version`:**

```
Version:      3.4.0
API Version:  3.4.0
Go Version:   go1.16.8
Built:        Thu Sep 30 19:40:21 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - hugetlb
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 2
  distribution:
    distribution: fedora
    variant: cloud
    version: "34"
  eventLogger: journald
  hostname: ip-172-31-6-203.ec2.internal
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.11.12-300.fc34.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 1033129984
  memTotal: 2032918528
  ociRuntime:
    name: crun
    package: crun-1.2-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.2
      commit: 4f6c8e0583c679bfee6a899c05ac6b916022561b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 0
  swapTotal: 0
  uptime: 34h 48m 36.69s (Approximately 1.42 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 6
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.0
  Built: 1633030821
  BuiltTime: Thu Sep 30 19:40:21 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.0-1.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
$ runc --version
runc version 1.0.2
commit: e15f155-dirty
spec: 1.0.2-dev
go: go1.16.6
libseccomp: 2.5.0

$ criu --version
Version: 3.16
```

**Comment by adrianreber** [comment]
Please try: `podman --runtime runc container restore --import /tmp/loop.tar.zst`

This is a bug. If you use runc to checkpoint the container Podman should automatically select the same runtime during restore.

**Comment by adrianreber** [comment]
> I am not sure how we can address it. `--import` and `--export` do not store what runtime was used

I had a look at it and the used runtime is actually part of the checkpoint (config.dump: `"runtime": "crun",`). I tried to create a patch, but the problem is that the runtime is selected very early in the code path and once we unpack the checkpoint archive the runtime is already selected.

I was not sure if I can just change the name and path of an existing runtime. It felt not like the right thing to do.

My main problem was that unpacking the checkpoint (only one file (config.dump) would be needed, however) seems like a heavy operation and doing it twice felt like a lot of overhead.

If we could change the runtime properties (mainly name and path) once it has been instantiated it would be easy to solve.

**Comment by carlhoerberg** [comment]
I'm glad closing this as there's a working solution for the issue, maybe just add a note to the documentation and call it a day?

**Comment by mheon** [comment]
@adrianreber I think we need to check if the runtime requested by the checkpoint exists in our available runtimes - if it does not, we can give a sane error back to the user ("checkpoint was created using "runc" but Podman does not recognize this runtime" or similar.
