### ISSUE TITLE
Container name resolves after DNS

### ISSUE THREAD

**Issue by k1rb** [containers/podman#11962]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Containers resolve DNS records before container names, when on a podman network that uses `dnsname` plugin. Even if you do not use a hostname, rather than a FQDN, the hostname + the podman host's search domain, will resolve before a container by the same name.

**Steps to reproduce the issue:**

Assumptions:
- Your podman host's FQDN is `podman.domain.tld`
- Your podman host's search domain is `domain.tld`
- You have a podman network named `mynet` with `dnsname` plugin enabled.

1. In DNS zone `domain.tld` create record `www 1800 IN CNAME podman.domain.tld.`

2. Create container `www` with apache, no port binds, on network `mynet`.

3. Create container `haproxy` with haproxy, using host port bind 80/tcp (unblock ports if req'd), on network `mynet`. Configure haproxy with frontend `*:80`, and backend to `www:80`.

**Describe the results you received:**

HAproxy starts and looks for backend `www` (DNS resolution `www` + host search domain `domain.tld`) and resolves CNAME created in step 1, back to the `podman.domain.tld` that HAProxy port 80 is bound to. This creates a loop where HAProxy's backend is it's frontend.

**Describe the results you expected:**

In docker, container names seem to resolve before host DNS for containers, and this is desirable. HAProxy will resolve backend `www` to the container and not do DNS lookup `www` + host search domain `domain.tld`, which would resolve back to the podman host.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.0.2-dev
API Version:  3.0.0
Go Version:   go1.15.7
Built:        Thu Jun 10 19:48:26 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.8
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.26-3.module+el8.4.0+556+40122d08.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 68a7820227c848cf32bb5555384811697913d451'
  cpus: 4
  distribution:
    distribution: '"rocky"'
    version: "8.4"
  eventLogger: file
  hostname: podman.domain.tld
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-305.3.1.el8_4.x86_64
  linkmode: dynamic
  memFree: 671309824
  memTotal: 16601370624
  ociRuntime:
    name: runc
    package: runc-1.0.0-73.rc93.module+el8.4.0+556+40122d08.x86_64
    path: /usr/bin/runc
    version: |-
      runc version spec: 1.0.2-dev
      go: go1.15.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 8451780608
  swapTotal: 8472489984
  uptime: 487h 38m 8.13s (Approximately 20.29 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 22
    paused: 0
    running: 19
    stopped: 3
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 27
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1623379706
  BuiltTime: Thu Jun 10 19:48:26 2021
  GitCommit: ""
  GoVersion: go1.15.7
  OsArch: linux/amd64
  Version: 3.0.2-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.0.1-7.module+el8.4.0+556+40122d08.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VMware, Rocky Linux 8.4, SELinux Enforcing.

**Comment by Luap99** [comment]
Can you show the resolv.conf from the container.

**Comment by k1rb** [comment]
From the `haproxy` container on the **podman** host:

```text
haproxy@haproxy:/$ cat /etc/resolv.conf 
search domain.tld
nameserver 10.89.0.1
```

From the `haproxy` container on the **docker** host:

```text
root@56df36398ee4:/# cat /etc/resolv.conf
search domain.tld
nameserver 127.0.0.11
options ndots:0
```
