### ISSUE TITLE
podman 3.4.0 breaks support for MacPorts' gvproxy location

### ISSUE THREAD

**Issue by jre21** [containers/podman#11960]
**Is this a BUG REPORT or FEATURE REQUEST?**

/kind bug

**Description**

When I updated my MacPorts-installed podman from 3.3.1 to 3.4.0, podman commands started failing with a message about being unable to find `gvproxy`.

This is a regression, as the podman 3.3.1 client had been interacting with `podman machine` as expected.  For reference, 

**Steps to reproduce the issue:**

1.  Ensure `/opt/local/bin` is on `$PATH` 
2.  Move the `gvproxy` binary to `/opt/local/bin`
3.  Run `podman machine start`

**Describe the results you received:**

Podman errors out with
```
Error: unable to start host networking: "could not find \"gvproxy\" in one of [/usr/local/opt/podman/libexec /opt/homebrew/bin /opt/homebrew/opt/podman/libexec /usr/local/bin /usr/local/libexec/podman /usr/local/lib/podman /usr/libexec/podman /usr/lib/podman]"
```

**Describe the results you expected:**

I expect podman to function normally in this situation.  I can think of a few possible ways to accomplish this, in rough order of preference:

1.  Have podman honor `$PATH` when searching for the `gvproxy` executable.  This is the most flexible approach and gets podman out of the business of needing to guess how users have organized their directory structure.
2. Check for `gvproxy` in the parent directory of the `podman` executable.  This would solve many of the most common installation patterns with a potentially smaller blast radius than the above.
3. Allow the user to configure the location of the `gvproxy` binary, and explain how to set this configuration in the error message.  This would add some friction for new users, but would at least be a one-time set-and-forget deal.
4. Add `/opt/local/bin/` to the list of search locations.  This unblocks MacPorts users, but presents the risk of podman developers being expected to individually support the long tail of bespoke package managers.

**Additional information you deem important (e.g. issue happens only occasionally):**

`/opt/local/bin` is where MacPorts installs all system executables (including podman and gvproxy).

**Output of `podman version`:**

This issue breaks basic functionality of the podman client and results in `podman version` not returning useful output.

**Output of `podman info --debug`:**

Same as above.

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ port installed podman
The following ports are currently installed:
  podman @3.3.1_1
  podman @3.4.0_0 (active)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

macOS 11.6 on bare metal (using podman machine's VM, prior to this bug appearing)

**Comment by MikeNicholls** [comment]
> Is this us packaging this or someone else?

Looks like @judaew is the maintainer.
https://ports.macports.org/port/podman/details/

**Comment by judaew** [comment]
Hi, I'm a maintainer `podman` port in MacPorts.

Thanks @chadcatlett, I've already moved `gvisor` to `${prefix}/libexec` directory in a [recent revision](https://github.com/macports/macports-ports/commit/a6c96c283f7a936a63b8af80ce0803ffffab8f7b).

I have [added a patch](https://github.com/macports/macports-ports/blob/f34c23137ff37bd006dd2aba16be237f1c496b53/sysutils/podman/files/patch-defaultHelperBinariesDir-for-MacPorts.diff) for `containers/common/pkg/config/config_darwin.go` where the paths for MacPorts are defined at the top. Since in MacPorts `/opt/local` path is the default value for `${prefix}`, but can be changed by the user, I will not suggest this patch as a PR for `podman`.
