### ISSUE TITLE
Podman does not tolerate special characters in proxy credentials

### ISSUE THREAD

**Issue by borazem** [containers/podman#11968]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When running podman behind the proxy with authentication, the podman does not tolerate special characters in  proxy password.
Not sure if this is a but or the behavior is by design, but I did not find any warning that proxy password should not contain any special characters. It seems however, that numbers can be used. 

**Steps to reproduce the issue:**

1. Establish a proxy with authentication with username and password where password would include special characters

2. Set the HTTP_PROXY variable `HTTP_PROXY=http://cda:ICPassw0rd#@192.168.10.10:3128`

3. run the podman login  command 

**Describe the results you received:**
in case of the following HTTP_PROXY setting (mind the # in the password):

`HTTP_PROXY=http://cda:ICPassw0rd#@192.168.10.10:3128`

the podman login would return the following message:
```
root@cdautil:proxytests $ podman login docker.io -u bodemo
Password:
Error: error authenticating creds for "docker.io": error pinging docker registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: dial tcp: lookup http on 192.168.10.2:53: no such host
```

if proxy password without special characters is used the podman works well
`HTTP_PROXY=http://cda:ICPassw0rd@192.168.10.10:3128`
```
root@cdautil:proxytests $ podman login docker.io -u bodemo
Password: 
Login Succeeded!
```
In contrast curl command with proxy password with special characters in the env. variable or in command like works ok

`HTTP_PROXY=http://cda:ICPassw0rd#@192.168.10.10:3128`
```
root@cdautil:proxytests $ curl --proxy http://cda:ICPassw0rd#@192.168.10.10:3128 https://google.com
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="https://www.google.com/">here</A>.
</BODY></HTML>
```
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
root@cdautil:upi-bmce $ podman version
Version:      3.0.2-dev
API Version:  3.0.0
Go Version:   go1.15.7
Built:        Wed Apr  7 10:36:54 2021
```

**Output of `podman info --debug`:**

```
root@cdautil:upi-bmce $ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.19.8
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.26-1.module+el8.4.0+10607+f4da7515.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: b883692702312720058141f16b6002ab26ead2e7'
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "8.4"
  eventLogger: file
  hostname: cdautil.cda.internal
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-305.el8.x86_64
  linkmode: dynamic
  memFree: 147111936
  memTotal: 8145596416
  ociRuntime:
    name: runc
    package: runc-1.0.0-70.rc92.module+el8.4.0+10607+f4da7515.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 3101184000
  swapTotal: 3439325184
  uptime: 74h 40m 8.29s (Approximately 3.08 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 1
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1617784614
  BuiltTime: Wed Apr  7 10:36:54 2021
  GitCommit: ""
  GoVersion: go1.15.7
  OsArch: linux/amd64
  Version: 3.0.2-dev

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
root@cdautil:upi-bmce $ rpm -q podman
podman-3.0.1-6.module+el8.4.0+10607+f4da7515.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes, I checked Podman Troubleshooting Guide.
Not sure I checked the latest version of Podman.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
the podbam is running on RHEL 8 in vmware env.

**Comment by Luap99** [comment]
Does it work when you urlencode the password?

**Comment by borazem** [comment]
good one, let me try

**Comment by Luap99** [comment]
You should only urlencode the password

**Comment by borazem** [comment]
yes, I just tried and in this case it works
'HTTPS_PROXY=http://cda:ICPassw0rd%23@192.168.10.10:3128'

```
root@cdautil:proxytests $ podman login docker.io -u bodemo
Password: 
Login Succeeded!
```

**Comment by borazem** [comment]
Thank you very much.

**Comment by rhatdan** [comment]
Since Podman can not fix this, I am going to close. You could open an issue with golang.  Glad you have a fix.
