### ISSUE TITLE
podman pull shall accept https-input as oci-archive

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#11970]
`podman import` can download images over HTTPS, but later the `podman images` shows no repository and no tag:
```
$ podman import https://mail.aegee.org/oci-images/ldap-2021-09-11.tar
Downloading from "https://mail.aegee.org/oci-images/ldap-2021-09-11.tar"
Getting image source signatures
Copying blob 16446d688987 done  
Copying config a4b7d92986 done  
Writing manifest to image destination
Storing signatures
sha256:a4b7d92986aed414c56b3a7d05934bc1e5c9d80d4fe5e7a9abd68766f73f5106
d@d:~$ podman images
REPOSITORY  TAG         IMAGE ID      CREATED        SIZE
<none>      <none>      a4b7d92986ae  4 seconds ago  2.5 MB
```

I can fill the REPOSITORY and TAG column, if I first download the file and then use skope copy:
```
wget https://mail.aegee.org/oci-images/ldap-2021-09-11.tar
$ skopeo copy oci-archive:ldap-2021-09-11.tar:2021-09-11 containers-storage:localhost/openldap:2021-09-11
Getting image source signatures
Copying blob bc523d70bbe7 done  
Copying config f0937f9440 done  
Writing manifest to image destination
Storing signatures
$ podman images
REPOSITORY          TAG         IMAGE ID      CREATED        SIZE
<none>              <none>      a4b7d92986ae  2 minutes ago  2.5 MB
localhost/openldap  2021-09-11  f0937f9440d3  9 hours ago    6.34 MB
```

but the latter is more cumbersome.  Please either extend `skopeo copy` to be able to download from HTTPS in the `oci-archive:` transport, extend `podman import` to be able to import the repository and tag, or both.

`podman import` has as extra, that it can import .tar.zstd files, (which can be compressed by zsd level 19, which is better than `skopeo copy --dest-compress-format=zstd --dest-compress-level=20`.

**Comment by dilyanpalauzov** [comment]
I adjusted the title.  I am asking to be able to pass `podman pull oci-archive:http://....`.  Ideally `podmanpull https://` shall imply `oci-archive:`.

**Comment by vrothberg** [comment]
I'll tackle it.  Not a bug but easy to get done.
