### ISSUE TITLE
Some Containers Are Not Accessible by the Outside Network

### ISSUE THREAD

**Issue by Saroufim** [containers/podman#11975]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Some containers cannot be accessed from outside the network. Others can.  The ones that can't be accessed are fully accessible from inside the network.  

**Steps to reproduce the issue:**

1. Create container

2. Open Firewall and create virtual machine config in modem

3. Try to access it from another network

**Describe the results you received:**

Containers function fully inside the network but not outside

**Describe the results you expected:**

Containers to function seamlessly between inside and outside networks

**Additional information you deem important (e.g. issue happens only occasionally):**
linuxserver/heimdall (port 4040) works from outside the network
miniflux/miniflux (port 7878) bitwardenrs/server (port 8989) and linuxserver/swag (port 443) cannot be accessed from the outside

My arm64 machine doesn't have this issue
**Output of `podman version`:**

podman version 3.3.1
**Output of `podman info --debug`:**

host:
  arch: arm
  buildahVersion: 1.22.3
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.29-2.fc34.armv7hl
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: '
  cpus: 4
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: cloud
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.9-200.fc34.armv7hl
  linkmode: dynamic
  memFree: 186912768
  memTotal: 1002385408
  ociRuntime:
    name: crun
    package: crun-1.0-1.fc34.armv7hl
    path: /usr/bin/crun
    version: |-
      crun version 1.0
      commit: 139dc6971e2f1d931af520188763e984d6cdfbf8
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.armv7hl
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 1000599552
  swapTotal: 1001385984
  uptime: 6h 30m 16.79s (Approximately 0.25 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /var/home/animus/.config/containers/storage.conf
  containerStore:
    number: 11
    paused: 0
    running: 10
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/animus/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 12
  runRoot: /run/user/1000/containers
  volumePath: /home/animus/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.1
  Built: 1630356641
  BuiltTime: Mon Aug 30 20:50:41 2021
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/arm
  Version: 3.3.1

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

podman-3.3.1-1.fc34.armv7hl

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora IoT 34 arm32. Fresh new system. Same configs worked before on the same OS before reinstalling. 
Firewalld is well configured and all the relevant ports are open.

**Comment by Saroufim** [comment]
MacOS you mean? No, it's on Fedora IoT

**Comment by Luap99** [comment]
Can you share the podman commands you use? Do you run the containers rootless or rootful?

**Comment by Saroufim** [comment]
Container that doesn't work:

`podman run -d  --security-opt label=disable --label "io.containers.autoupdate=image" --name=swag --cap-add=NET_ADMIN -e PUID=1000 -e PGID=1000 -e TZ=Asia/Beirut -e URL=myfancywebsite.net -e SUBDOMAINS=  -v ~/.swag:/config  -e EMAIL=antoine.saroufim@someprovider.com  -p 443:443  linuxserver/swag:latest`


Container that works:

`podman run -d --security-opt label=disable  --label "io.containers.autoupdate=image" --name=heimdall  -e PUID=1000  -e PGID=1000  -e TZ=Asia/Beirut  -p 4040:443  -v ~/.heimdall:/config    ghcr.io/linuxserver/heimdall:latest`

**Comment by Saroufim** [comment]
It's also noteworthy that Bitwarden's container doesn't use any capabilities and uses port 8989 yet it would still not connect from the outside

**Comment by mheon** [comment]
Can you access the services via localhost on the system running podman?

**Comment by mheon** [comment]
It looks like it is accessible locally, which is interesting...

Can you stop the containers, turn off firewalld, restart them, and see if it works?
