### ISSUE TITLE
DNS issue, /etc/resolv.conf is not updated with "search dns.podman" on Podman 3.2.3-0.11

### ISSUE THREAD

**Issue by cucosion** [containers/podman#11989]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

/etc/resolv.conf is not updated with "search dns.podman" on a setup that has podman and podman plugins and because of this all aliases are not resolved

**Steps to reproduce the issue:**

1. Install podman and podman plugins
[icucos@localhost temp]$ rpm -qa | grep podman
podman-remote-3.2.3-0.11.module_el8.4.0+942+d25aada8.x86_64
podman-3.2.3-0.11.module_el8.4.0+942+d25aada8.x86_64
podman-catatonit-3.2.3-0.11.module_el8.4.0+942+d25aada8.x86_64
podman-plugins-3.2.3-0.11.module_el8.4.0+942+d25aada8.x86_64

2. create few instances that are using aliases and try to call them from the instances

`#!/bin/bash

podman network create backend2

podman create --privileged --name=instance1 --network backend2 --entrypoint=sh --network-alias service1 --network-alias service2 centos:5.11 -c 'tail -f /dev/null'
podman create --privileged --name=instance2  --entrypoint=sh --network container:instance1 centos:5.11 -c 'tail -f /dev/null'

podman create --privileged --name=instance3 --entrypoint=sh --network backend2 --network-alias service3 --network-alias service4 centos:5.11 -c 'tail -f /dev/null'
podman create --privileged --name=instance4 --entrypoint=sh --network container:instance3 centos:5.11 -c 'tail -f /dev/null'

podman start instance1
podman start instance2
podman start instance3
podman start instance4
`
3. From instance1 if i ping a service4 or service1 it fail to resolve it

**Describe the results you received:**
failed to resolve the host

**Describe the results you expected:**
to be able to ping by hostname

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
[icucos@localhost temp]$ podman version
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.15.13
Built:        Sat Aug  7 13:21:48 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
[icucos@localhost temp]$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.21.3
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.module_el8.4.0+886+c9a8d9ad.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 97bba1e91aaab5be2e93bacd34ec4e66655a02ae'
  cpus: 36
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-305.19.1.el8_4.x86_64
  linkmode: dynamic
  memFree: 164561305600
  memTotal: 168404615168
  ociRuntime:
    name: runc
    package: runc-1.0.0-74.rc95.module_el8.4.0+886+c9a8d9ad.x86_64
    path: /usr/bin/runc
    version: |-
      runc version spec: 1.0.2-dev
      go: go1.15.14
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module_el8.4.0+641+6116a774.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 0
  swapTotal: 0
  uptime: 4h 25m 21.78s (Approximately 0.17 days)
registries:
  dub1-eud-git01.aeroflex.corp:5000:
    Blocked: false
    Insecure: true
    Location: dub1-eud-git01.aeroflex.corp:5000
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: dub1-eud-git01.aeroflex.corp:5000
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/icucos/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.6-1.module_el8.4.0+886+c9a8d9ad.x86_64
      Version: |-
        fusermount3 version: 3.2.1
        fuse-overlayfs: version 1.6
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/icucos/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /home/icucos/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.3
  Built: 1628356908
  BuiltTime: Sat Aug  7 13:21:48 2021
  GitCommit: ""
  GoVersion: go1.15.13
  OsArch: linux/amd64
  Version: 3.2.3
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.2.3-0.11.module_el8.4.0+942+d25aada8.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes, i'm on latest version available in centos repo

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

Do you have any dev repository that I can use to install the latest (3.4) podman on a centos 8.4? previously I tried with kubic but its not working anymore

**Comment by Luap99** [comment]
This is a packaging problem. podman-plugins has to install dnsname version 1.2 or newer
