### ISSUE TITLE
Unnamed sockets doesn't work after checkpointing

### ISSUE THREAD

**Issue by carlhoerberg** [containers/podman#11983]
/kind bug

**Description**

Writing to an [unnamed socket pair](https://www.man7.org/linux/man-pages/man2/socketpair.2.html) after checkpoint/restore fails with `EACCES`. It works if using `criu dump`/`criu restore` manually. `--runtime runc` makes no difference. 

**Steps to reproduce the issue:**

1. `podman run -d ruby:3-slim ruby -r socket -e "a, b = UNIXSocket.pair; loop { a.send('a', 0); p b.recv(1); sleep 1 }"`
2. `podman container checkpoint --latest`
4. `podman container restore --latest`

**Describe the results you received:**

```
-e:1:in `send': Permission denied - send(2) (Errno::EACCES)
```

**Describe the results you expected:**

The application to continue running. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.4.0
API Version:  3.4.0
Go Version:   go1.16.8
Built:        Thu Sep 30 21:40:21 2021
OS/Arch:      linux/amd64
```

**Output of `criu --version`:**

```
Version: 3.16
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Comment by carlhoerberg** [comment]
This means that any Erlang application, that shells out/exec won't be possible to checkpoint (because how erlang solves that without forking the main VM but instead passing arguments to another process that will fork/exec)

```
podman run -d erlang:24-alpine erl -noshell -eval 'L = fun(F) -> io:fwrite(os:cmd("date")), timer:sleep(1000), F(F) end, L(L).'
podman container checkpoint --latest
podman container restore --latest
podman logs -f --latest
```

/kind bug

**Comment by adrianreber** [comment]
Could you also give an example how you try it with CRIU only?
