### ISSUE TITLE
create a container network without ipv4 networking

### ISSUE THREAD

**Issue by kajtzu** [containers/podman#11985]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I'll file this as a feature request since there doesn't seem to be a way to disable ipv4 networking with a command line parameter to podman. It would be useful, however, to have this since it would be nice to have ipv6 only containers because of business reasons (the container hosts are ipv6 only, not dual-stack).

Currently, at least, with podman version 3.2.3 (the one in RHEL8) ipv4 addressing is always provisioned even if one only specifies ipv6 networking.

Perhaps it is just me not able to figure out how to disable it, in that case my apologies ;)

**Steps to reproduce the issue:**

1. podman network create --subnet 2001:db8:dead:babe::/64 --ipv6 my-first-ipv6-network

2. podman network inspect my-first-ipv6-network
```
[
    {
        "cniVersion": "0.4.0",
        "name": "my-first-ipv6-network",
        "plugins": [
            {
                "bridge": "cni-podman1",
                "hairpinMode": true,
                "ipMasq": true,
                "ipam": {
                    "ranges": [
                        [
                            {
                                "gateway": "2001:db8:dead:babe::1",
                                "subnet": "2001:db8:dead:babe::/64"
                            }
                        ],
                        [
                            {
                                "gateway": "10.89.0.1",
                                "subnet": "10.89.0.0/24"
                            }
                        ]
                    ],
                    "routes": [
                        {
                            "dst": "::/0"
                        },
                        {
                            "dst": "0.0.0.0/0"
                        }
                    ],
                    "type": "host-local"
                },
                "isGateway": true,
                "type": "bridge"
            },
            {
                "capabilities": {
                    "portMappings": true
                },
                "type": "portmap"
            },
            {
                "backend": "",
                "type": "firewall"
            },
            {
                "type": "tuning"
            }
        ]
    }
]
```

3. Note the IPv4 subnets and gateways

**Describe the results you received:**

IPv4 and IPv6 config seen

**Describe the results you expected:**

I would expect only to have IPv6 config

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman --version
podman version 3.2.3

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
rpm -q podman
podman-3.2.3-0.11.module_el8.4.0+2535+b6fd1bdf.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I am on bare metal.

**Comment by Luap99** [comment]
Just don't set --ipv6, then it will only use your subnet. The --ipv6 options means dual stack networking. I know it is confusing but this is what docker does
