### ISSUE TITLE
generate kube -s: do not emit ports.targetPort equal to ports.port

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#11994]
I use podman at commit 171f7b8975194ff9f47a.
```
$ podman generate kube -s <ID>
# Created with podman-4.0.0-dev
apiVersion: v1
kind: Service
spec:        
  ports:           
  - name: "3890"     
    nodePort: 31622      
    port: 3890
    targetPort: 3890
```
According to the reference of Service.spec.ports - https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/#ServiceSpec- missing ports.targetPort implies the same value as ports.port.  So there is no point to render targetPort in this case.

**Comment by umohnani8** [comment]
So even though the `TargetPort` option in the Service struct is set to omitempty, it still automatically sets it to 0 when we leave it as empty - no idea why that is happening
```
	TargetPort intstr.IntOrString `json:"targetPort,omitempty" protobuf:"bytes,4,opt,name=targetPort"`

```

That is why I decided it was best to just make its value the same as ports.port so it doesn't end up with a 0 value. Here is the patch that fixed that https://github.com/containers/podman/pull/11982/files.

**Comment by umohnani8** [comment]
Yeah, if it is not set it should be empty and the field shouldn't show up in the yaml. However, when it is empty or not set it is equating that to 0 and it is showing up in the generated yaml.

**Comment by umohnani8** [comment]
Closing this as targetPort gets the value of 0 when it is left empty and is coming from where the struct is defined in k8s.
