### ISSUE TITLE
Podman behind forward proxy problem. Any requirements like which http headers must not be altered/removed? 

### ISSUE THREAD

**Issue by borazem** [containers/podman#11993]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When I tried to to pull images from quay.io or docker.io with podman behind the proxy I am experience errors and I suspect that the forward proxy may be changing http headers.

**is the any list of requirements which header fields must not be altered for podman to work?**

the podman can login successfully to docker.io and quay.io.

**Steps to reproduce the issue:**

steps can not be reproduced as the proxy vendor and settings info are unknown. however the steps done are:
1. login to quay.io or docker.io

2. run the commands: `# podman pull quay.io/openshift-release-dev/ocp-release@sha256:5f57680f3fc9632b0e6db4a9a8804d347108e96c38bc769b03e4158576035895`  or  `# podman pull docker.io/borazem/boa-nodejsexpress`

**Describe the results you received:**
example 1 (quay.io):

`# podman pull quay.io/openshift-release-dev/ocp-release@sha256:5f57680f3fc9632b0e6db4a9a8804d347108e96c38bc769b03e4158576035895`
```
Trying to pull quay.io/openshift-release-dev/ocp-release@sha256:5f57680f3fc9632b0e6db4a9a8804d347108e96c38bc769b03e4158576035895...
 Manifest does not match provided manifest digest sha256:5f57680f3fc9632b0e6db4a9a8804d347108e96c38bc769b03e4158576035895
Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:5f57680f3fc9632b0e6db4a9a8804d347108e96c38bc769b03e4158576035895": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:5f57680f3fc9632b0e6db4a9a8804d347108e96c38bc769b03e4158576035895: unable to pull image: Error determining manifest MIME type for docker://quay.io/openshift-release-dev/ocp-release@sha256:5f57680f3fc9632b0e6db4a9a8804d347108e96c38bc769b03e4158576035895: Manifest does not match provided manifest digest sha256:5f57680f3fc9632b0e6db4a9a8804d347108e96c38bc769b03e4158576035895
```

example2 (docker.io)
`# podman pull docker.io/borazem/boa-nodejsexpress`
```
Trying to pull docker.io/borazem/boa-nodejsexpress...
 invalid character '<' looking for beginning of value
Error: error pulling image "docker.io/borazem/boa-nodejsexpress": unable to pull docker.io/borazem/boa-nodejsexpress: unable to pull image: Error initializing image from source docker://borazem/boa-nodejsexpress:latest: invalid character '<' looking for beginning of value
```

**Describe the results you expected:**

I would expect the images would download.

**Additional information you deem important (e.g. issue happens only occasionally):**
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/32193129/137536013-cd5a01d2-db42-4f56-a7ec-5309461b6fa3.png">

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/32193129/137536057-6542b2eb-b28c-46e0-98c8-e3077d63c363.png">

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/32193129/137536069-06c2befe-c338-456c-b143-848e7bc66587.png">

**Output of `podman version`:**

```
[core@bmceocpb0 ~]$ podman version
Version:      3.0.2-dev
API Version:  3.0.0
Go Version:   go1.15.13
Built:        Tue Jun  8 07:52:06 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.0.1-7.module+el8.4.0+11311+9da8acfb.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes, I checked Podman Troubleshooting Guide 
No, I am not sure if the used podman is of the latest version

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Environment VMWare vSphere.

**Comment by mtrmac** [comment]
> **is the any list of requirements which header fields must not be altered for podman to work?**

The protocol is documented at https://github.com/distribution/distribution/blob/main/docs/spec/api.md .

> **Describe the results you received:** example 1 (quay.io):
> 
> `# podman pull quay.io/openshift-release-dev/ocp-release@sha256:5f57680f3fc9632b0e6db4a9a8804d347108e96c38bc769b03e4158576035895`
> 
> ```
> Trying to pull quay.io/openshift-release-dev/ocp-release@sha256:5f57680f3fc9632b0e6db4a9a8804d347108e96c38bc769b03e4158576035895...
>  Manifest does not match provided manifest digest sha256:5f57680f3fc9632b0e6db4a9a8804d347108e96c38bc769b03e4158576035895
> Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:5f57680f3fc9632b0e6db4a9a8804d347108e96c38bc769b03e4158576035895": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:5f57680f3fc9632b0e6db4a9a8804d347108e96c38bc769b03e4158576035895: unable to pull image: Error determining manifest MIME type for docker://quay.io/openshift-release-dev/ocp-release@sha256:5f57680f3fc9632b0e6db4a9a8804d347108e96c38bc769b03e4158576035895: Manifest does not match provided manifest digest sha256:5f57680f3fc9632b0e6db4a9a8804d347108e96c38bc769b03e4158576035895
> ```

To _directly_ go after the error message, it would be necessary to capture the HTTP response (including the body), maybe using Wireshark, and then try re-computing the digest (or just read the response if it is clearly not an image manifest).

(I can, at least, confirm that pulling that image directly from Quay does work.)

This could happen for quite a few reasons; the proxy modifying the contents for whatever reason, or maybe corrupt storage on a transparent cache, or something like that.

> example2 (docker.io) `# podman pull docker.io/borazem/boa-nodejsexpress`
> 
> ```
> Trying to pull docker.io/borazem/boa-nodejsexpress...
>  invalid character '<' looking for beginning of value
> Error: error pulling image "docker.io/borazem/boa-nodejsexpress": unable to pull docker.io/borazem/boa-nodejsexpress: unable to pull image: Error initializing image from source docker://borazem/boa-nodejsexpress:latest: invalid character '<' looking for beginning of value
> ```

This is more suggestive — I’d pretty much bet on that proxy injecting a HTML… something (either an error page or a login form) instead of just forwarding the request/response as we’d assume.

The debug log does list the HTTP verbs and URLs being involved; for starters, try accessing the last one (that ends with …`/manifests/latest` with something like `curl` and see what the response says.

That is not certain to work (notably just blindly using `curl` does not contain the right authentication headers), so it might be necessary to fall back to the Wireshark approach, but as a first cheap triage option it might well reveal something useful.
