### ISSUE TITLE
Regression 3.4: missing entries in /etc/hosts

### ISSUE THREAD

**Issue by douglas-legulas** [containers/podman#12003]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Example: a pod starts 3 containers named `example-mariadb`, `example-php` and `example-httpd`. Because their `/etc/hosts` file is missing the required entries, they cannot locate one another through hostname resolution. In this example, PHP fails to locate the MariaDB container by hostname `example-mariadb`. As a symptom PHP logs the error:
```
php_network_getaddresses: getaddrinfo failed: Name or service not known
```

`/etc/hosts` available inside containers **before v3.4**:
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

10.88.0.4 example 081aafb26c65-infra
127.0.1.1 example example-mariadb
127.0.1.1 example example-httpd
127.0.1.1 example example-php
```

`/etc/hosts` available inside containers **in v3.4**:
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

10.88.0.5 example 081aafb26c65-infra
10.88.0.1 host.containers.internal
```

Changes in v3.4 that may have caused the regression: #11411, #11596

**Steps to reproduce the issue:**

1. Build and start the pod at https://1drv.ms/u/s!ApqEOOKoIKfoeo7T9Yp5pk5cM9U?e=c0Q086

2. Exec into the shell of one of the containers and check its `/etc/hosts`.

**Output of `podman version`:**

```
Version:      3.4.0
API Version:  3.4.0
Go Version:   go1.16.8
Built:        Thu Sep 30 16:40:21 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    variant: workstation
    version: "34"
  eventLogger: journald
  hostname: alq22
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.11-200.fc34.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 9558335488
  memTotal: 16698474496
  ociRuntime:
    name: crun
    package: crun-1.2-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.2
      commit: 4f6c8e0583c679bfee6a899c05ac6b916022561b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 59m 50.09s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 4
    stopped: 3
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 11
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.0
  Built: 1633030821
  BuiltTime: Thu Sep 30 16:40:21 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.0

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.0-1.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora Workstation 34 (amd64).

**Comment by o-alquimista** [comment]
Sure.

[LegulasPod.zip](https://github.com/containers/podman/files/7388549/LegulasPod.zip)

**Comment by rhatdan** [comment]
Could you show the podman command used to create the /etc/hosts file?

**Comment by douglas-legulas** [comment]
> Could you show the podman command used to create the /etc/hosts file?

Sorry, what do you mean? The pod building scripts are here: https://github.com/containers/podman/files/7388549/LegulasPod.zip

**Comment by rhatdan** [comment]
Could you make a simple repeater that we could examine.

**Comment by douglas-legulas** [comment]
I've added a virtual host and an example webpage.
[LegulasPod.zip](https://github.com/containers/podman/files/7488553/LegulasPod.zip)

To reproduce:
1. Build the pod (as root)
```
$ cd LegulasPod
# sh ./scripts/build.sh
```

2. Check `/etc/hosts`:
```
# podman exec legulas-php cat /etc/hosts
```

### Expected results:
```
legulas c7d7ce974eb3-infra
10.88.0.1 host.containers.internal
127.0.0.1 legulas legulas-httpd
127.0.0.1 legulas legulas-php
127.0.0.1 legulas legulas-mariadb
```

### Actual results:
```
legulas c7d7ce974eb3-infra
10.88.0.1 host.containers.internal
```

**Comment by douglas-legulas** [comment]
Were you able to reproduce the issue?

**Comment by rhatdan** [comment]
@Luap99 did you ever get a chance to look at this?

**Comment by Luap99** [comment]
No I have no spare time at the moment to look at this unfortunately.I am very busy with netavark work

**Comment by rhatdan** [comment]
@douglas-legulas any chance you get this to happen without docker-compose?  IE Can you get it to happen with a simpler podman run or podman -remote run?

**Comment by douglas-legulas** [comment]
I'm using `podman pod`, not docker compose. It's just `buildah` and `podman`, nothing else.

But I'll try to produce something more simple, starting from scratch. I'll do it this weekend.

**Comment by douglas-legulas** [comment]
Here's a greatly simplified pod setup:
[testpod.zip](https://github.com/containers/podman/files/7697462/testpod.zip)

It builds, without any modification, two local images named `localhost/testpod-httpd` and `localhost/testpod-php`, which are based on [httpd](https://hub.docker.com/_/httpd) and [php](https://hub.docker.com/_/php), respectively. They run on a pod named `testpod`, and the containers are named `testpod-httpd` and `testpod-php`. When you open http://localhost:8080 on your browser you see the Apache "It works!" page.

### To reproduce
1. `cd ./testpod/scripts`
2. This will build and run the pod: `sudo sh build.sh`
3. `sudo podman exec -it testpod-httpd bash` or `sudo podman exec -it testpod-php bash`
4. `cat /etc/hosts`

### Expected `/etc/hosts`:
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

10.88.0.3 testpod 8c69480aec9f-infra
10.88.0.1 host.containers.internal
127.0.0.1 testpod testpod-httpd
127.0.0.1 testpod testpod-php
```

### Actual `/etc/hosts`
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

10.88.0.3 testpod 8c69480aec9f-infra
10.88.0.1 host.containers.internal
```

### Consequence
The containers cannot resolve hostnames `testpod-httpd` and `testpod-php`.

### Additional info
Podman 3.4.2 on Fedora Workstation 35 (amd64).

**Comment by nupplaphil** [comment]
I can reproduce it as well.

**Setup**
```console
$ sudo podman pod create --name friendica --hostname friendica -p 8012:80
$ sudo podman run -d --name friendica-mariadb --pod friendica -e PUID=1001 -e PGID=1001 --mount type=bind,src=/tmp/friendica/db,dst=/var/lib/mysql --restart=unless-stopped --env MYSQL_HOST=localhost --env MYSQL_PORT=3306 --env MYSQL_DATABASE=friendica --env MYSQL_USER=friendica --env MYSQL_PASSWORD=friendica  --env MYSQL_RANDOM_ROOT_PASSWORD=yes mariadb:latest
$ sudo podman run -d --name friendica-fpm --pod friendica --env TZ=Europe/Berlin -e PUID=1001 -e PGID=1001 --mount type=bind,src=/tmp/friendica/html,dst=/var/www/html --restart=unless-stopped --env MYSQL_USER=friendica --env MYSQL_PASSWORD=friendica --env MYSQL_DATABASE=friendica --env MYSQL_HOST=friendica-mariadb --env FRIENDICA_ADMIN_MAIL=admin@at.home --env FRIENDICA_SITENAME=friendica.at.home --env FRIENDICA_TZ='Europe/Zurich' --env FRIENDICA_URL='https://friendica.at.home' friendica:fpm
```

**Output `/etc/hosts`**
```console
$ sudo podman exec friendica-fpm cat /etc/hosts
[...] (copied lines from my host)

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
10.88.0.2       friendica 672deab3f9e2-infra
10.88.0.1 host.containers.internal
```

**Additional info**
- Podman 3.4.2
- Ubuntu bullseye/sid

**Comment by Luap99** [comment]
@douglas-legulas Thanks
I think it was caused by https://github.com/containers/podman/pull/11605 which fixed https://github.com/containers/podman/issues/11596. I think to make sure that the other issue stays fixed the expected result should look like this:
```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

10.88.0.3 testpod 8c69480aec9f-infra
10.88.0.1 host.containers.internal
10.88.0.3 testpod testpod-httpd
10.88.0.3 testpod testpod-php
```

**Comment by m3freak** [comment]
The hosts file format proposed by @Luap99 doesn't work for me universally because services running in my containers are configured to listen for connections on 127.0.0.1. I'm not sure how to work around this without assigning fixed IPs. That's not going to be fun to fix.

**Comment by rhatdan** [comment]
In this case should the /etc/hosts within the containers be read-only, or if a container modifies the /etc/hosts does every container see it.

**Comment by rhatdan** [comment]
@cdoern do you have time to look at this one?

I think this should be creating an /etc/hosts file at the POD level and then as each container gets added and removed the hosts file should be modified.  The hosts files within the containers should be read/only.  They should be volume mounted in from the PODs host file just like we do with shm.

**Comment by rhatdan** [comment]
@mheon do you agree with this design?

**Comment by rhatdan** [comment]
@Luap99 Thoughts?

**Comment by Luap99** [comment]
I do not think we can make the hosts file read only, some people want it writeable.
I also want to add that we need to take a very careful look here, every time we changed the hosts file it almost always broke another persons workflow.

**Comment by rhatdan** [comment]
Yes there is going to be some difficulty with adding and removing containers.  If the host file is shared, then it can not be editable by the containers.  I would want it totally managed by the Pod, else adding and removing containers would not be controllable.

**Comment by Luap99** [comment]
I agree with that point but I am not sure if we can do it without breaking many people, I think you can use `--add-host` on a container and not pod at the moment.

**Comment by rhatdan** [comment]
Yup and that should work, but it would modify the pods hosts file. The thing you can not do is have the processes within the contaienr modify the hosts file.

**Comment by mheon** [comment]
Isn't the hosts file *already* shared on a per-network-namespace basis? Since pods share a network NS, I believe they already mount the /etc/hosts file of the first container in the network namespace - IE, the infra container.

**Comment by rhatdan** [comment]
Yes it looks like you are right, and each container can modify the hosts file, which I think is wrong, since one container could attack the others.

**Comment by mheon** [comment]
AFAIK, the original request to add this was to match Docker, so I think they do this as well.

**Comment by rhatdan** [comment]
Hows this look?
```
$ podman pod create  --name test 
d89e962197f7e639be879fa7390af2e2787db0bdf7df2ff2612b59c2310e9a2d
$ ./bin/podman run --name c1 --pod test fedora cat /etc/hosts 
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
104.104.88.51 www.redhat.com
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
# used by slirp4netns
10.0.2.100	test d89e962197f7-infra
192.168.1.141	host.containers.internal
10.0.2.100	231da8c7ac6a c1
$ ./bin/podman run --name c2 --pod test fedora cat /etc/hosts 
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
104.104.88.51 www.redhat.com
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
# used by slirp4netns
10.0.2.100	test d89e962197f7-infra
192.168.1.141	host.containers.internal
10.0.2.100	231da8c7ac6a c1
10.0.2.100	08866c279061 c2
$ ./bin/podman stop c1
c1
$ ./bin/podman start --attach c1
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
104.104.88.51 www.redhat.com
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
# used by slirp4netns
10.0.2.100	test d89e962197f7-infra
192.168.1.141	host.containers.internal
10.0.2.100	231da8c7ac6a c1
10.0.2.100	08866c279061 c2
```

**Comment by mheon** [comment]
Looks fine, though I'm still iffy about having it read-only, if that's the plan.

**Comment by rhatdan** [comment]
I will leave them read/write, although I am not sure if we should consider this an attack vector,  resolv.conf and hostname might fall in the same category.

I just need to get time to work on tests.

**Comment by vkvm** [comment]
Just wanted to highlight that there are users like me running `podman play kube`, for which this is a showstopper. I've been watching this issue, as I assume it's the same as below.

Here's a simple reproducer (tested under Fedora 35)

`example-pod.yml`:

```yaml
apiVersion: apps/v1
kind: Pod
metadata:
  name: helloworld
spec:
  containers:
    - name: webserver
      image: docker.io/library/nginx:stable
    - name: webclient
      image: docker.io/library/alpine:3.15
      command: ["/bin/sh", "-xc"]
      args:
        # sleep at start due to occasional short delay before /etc/hosts is fully populated
        # sleep at the end to allow time to manually inspect before container exit/restart
        - "sleep 2; cat /etc/hosts; echo; nc -vz helloworld-webserver 80; sleep 60"
```

`podman play kube ./example-pod.yml && sleep 5 && podman logs --tail=10 helloworld-webclient`

### podman 3.3.1

```
# used by slirp4netns
10.0.2.100      helloworld 036d5ebec052-infra
10.0.2.2 host.containers.internal
127.0.0.1 helloworld helloworld-webserver
127.0.0.1 helloworld helloworld-webclient
+ echo

+ nc -vz helloworld-webserver 80
helloworld-webserver (127.0.0.1:80) open
+ sleep 60
```

### podman 3.4.4

```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
# used by slirp4netns
10.0.2.100      helloworld fe7c74935cf4-infra
10.0.2.2 host.containers.internal

+ echo
+ nc -vz helloworld-webserver 80
nc: bad address 'helloworld-webserver'
+ sleep 60
```

Anyway, sounds like you have a plan to resolve this. Looking forward to a fix.

**Comment by Luap99** [comment]
There is no PR linked so when was this fixed?  I do not remember PRs for this.

**Comment by rhatdan** [comment]
Perhaps not, I know I looked into this, but not sure if I ever fixed it.

**Comment by mcejp** [comment]
FWIW, I found this issue when googling for problems with DNS resolution among my containers. Turns out I was just missing the `podman-plugins` package -- perhaps this helps somebody.
