### ISSUE TITLE
Support additional linux distro when a podman machine is created

### ISSUE THREAD

**Issue by cmoulliard** [containers/podman#12011]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Suggestion: Support additional linux distro when a podman machine is created.

I downloaded a qcow2 image of Centos8 to create a podman VM but the VM do not boot.

Questions:
- Is it possible to create a podman VM using  different Linux OS/Distro (Cento7, Centos8) ? 
- If we can use a different distro, could it be possible document what we should acheive to let `podman machine` to boot it
as currently that fails

```
podman machine init --image-path ~/Images/CentOS-8-GenericCloud-8.4.2105.x86_64.qcow2 centos8

podman machine list
NAME                     VM TYPE     CREATED         LAST UP         CPUS        MEMORY      DISK SIZE
centos8                  qemu        26 seconds ago  26 seconds ago  1           2.147GB     10.74GB
podman-machine-default*  qemu        5 weeks ago     30 minutes ago  1           2.147GB     0B

podman machine start centos8
0000] podman filtering at log level debug
DEBU[0000] [/usr/local/bin/qemu-system-x86_64 -m 2048 -smp 1 -fw_cfg name=opt/com.coreos/config,file=/Users/cmoullia/.config/containers/podman/machine/qemu/centos8.ign -qmp unix://var/folders/t2/jwchtqkn5y76hrfrws7dqtqm0000gn/T/podman/qmp_centos8.sock,server=on,wait=off -netdev socket,id=vlan,fd=3 -device virtio-net-pci,netdev=vlan,mac=5a:94:ef:e4:0c:ee -device virtio-serial -chardev socket,path=/var/folders/t2/jwchtqkn5y76hrfrws7dqtqm0000gn/T/podman/centos8_ready.sock,server=on,wait=off,id=centos8_ready -device virtserialport,chardev=centos8_ready,name=org.fedoraproject.port.0 -machine q35,accel=hvf:tcg -cpu host -drive if=virtio,file=/Users/cmoullia/.local/share/containers/podman/machine/qemu/centos8_CentOS-8-GenericCloud-8.4.2105.x86_64.qcow2]
[/usr/local/opt/podman/libexec/gvproxy -listen tcp://0.0.0.0:7777 -listen-qemu unix:///var/folders/t2/jwchtqkn5y76hrfrws7dqtqm0000gn/T/podman/qemu_centos8.sock -pid-file /var/folders/t2/jwchtqkn5y76hrfrws7dqtqm0000gn/T/podman/centos8.pid -ssh-port 59432 --debug]
DEBU[0000] Using search domains: [redhat.com win.redhat.com]
INFO[0000] waiting for clients...
INFO[0000] listening tcp://0.0.0.0:7777
DEBU[0000] [/usr/local/bin/qemu-system-x86_64 -m 2048 -smp 1 -fw_cfg name=opt/com.coreos/config,file=/Users/cmoullia/.config/containers/podman/machine/qemu/centos8.ign -qmp unix://var/folders/t2/jwchtqkn5y76hrfrws7dqtqm0000gn/T/podman/qmp_centos8.sock,server=on,wait=off -netdev socket,id=vlan,fd=3 -device virtio-net-pci,netdev=vlan,mac=5a:94:ef:e4:0c:ee -device virtio-serial -chardev socket,path=/var/folders/t2/jwchtqkn5y76hrfrws7dqtqm0000gn/T/podman/centos8_ready.sock,server=on,wait=off,id=centos8_ready -device virtserialport,chardev=centos8_ready,name=org.fedoraproject.port.0 -machine q35,accel=hvf:tcg -cpu host -drive if=virtio,file=/Users/cmoullia/.local/share/containers/podman/machine/qemu/centos8_CentOS-8-GenericCloud-8.4.2105.x86_64.qcow2]
INFO[0000] new connection from  to /var/folders/t2/jwchtqkn5y76hrfrws7dqtqm0000gn/T/podman/qemu_centos8.sock
Waiting for VM ...
0 B sent to the VM, 0 B received from the VM
...
- Layer 1 (14 bytes) = Ethernet	{Contents=[..14..] Payload=[..28..] SrcMAC=5a:94:ef:e4:0c:dd DstMAC=5a:94:ef:e4:0c:ee EthernetType=ARP Length=0}
- Layer 2 (28 bytes) = ARP	{Contents=[..28..] Payload=[] AddrType=Ethernet Protocol=IPv4 HwAddressSize=6 ProtAddressSize=4 Operation=2 SourceHwAddress=[..6..] SourceProtAddress=[192, 168, 127, 1] DstHwAddress=[..6..] DstProtAddress=[192, 168, 127, 2]}
DEBU[0103] Stopping udp proxy (read udp 129.250.35.250:123: i/o timeout)
DEBU[0104] Stopping udp proxy (read udp 83.98.201.134:123: i/o timeout)
DEBU[0104] Stopping udp proxy (read udp 87.233.197.123:123: i/o timeout)
DEBU[0104] Stopping udp proxy (read udp 45.159.204.28:123: i/o timeout)
2.8 kB sent to the VM, 3.4 kB received from the VM
```

**Steps to reproduce the issue:**

1. Download a qcow2 file : https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.4.2105-20210603.0.x86_64.qcow2

2. `podman machine init --image-path ~/Images/CentOS-8-GenericCloud-8.4.2105.x86_64.qcow2 centos8`

3. `podman machine start centos8`

**Describe the results you received:**

VM do not boot

**Output of `podman version`:**

```
podman -v
podman version 3.4.0
```

**OS`:**

```
MacOS:  BigSur - 11.6
```

**Comment by cmoulliard** [comment]
> use ignition during boot and have a recent podman inside it

Is it documented how we could achieve that ?

**Comment by afbjorklund** [comment]
You can use lima instead of podman, if you want to use `cloud-init` instead of `ignition`.

**Comment by afbjorklund** [comment]
Updated the lima examples to Fedora 35 and CentOS 8-Stream, since CentOS Linux is soon EOL...

limactl start https://raw.githubusercontent.com/afbjorklund/fedora-lima/main/fedora-podman.yaml

limactl start https://raw.githubusercontent.com/afbjorklund/fedora-lima/main/centos-podman.yaml

They use the "Cloud" versions (with cloud-init), rather than the "CoreOS" versions (with ignition).

----

```console
$ export LIMA_INSTANCE=centos-podman
$ lima podman version
Version:      3.4.1-dev
API Version:  3.4.1-dev
Go Version:   go1.16.7
Built:        Tue Oct 19 16:11:42 2021
OS/Arch:      linux/amd64
```
```console
$ $ rpm -q $(rpm -q --whatprovides system-release)
centos-stream-release-8.5-3.el8.noarch
$ lima rpm -q podman
podman-3.4.1-3.module_el8.6.0+954+963caf36.x86_64
```

**Comment by cmoulliard** [comment]
I did a test successfully on my mac using `limactl start https://raw.githubusercontent.com/afbjorklund/fedora-lima/main/centos-podman.yaml`

**Comment by afbjorklund** [comment]
The new lima version has automatic mounting of the podman.sock, haven't ported that from ubuntu over to fedora yet.

**Comment by afbjorklund** [comment]
> Suggestion: Support additional linux distro when a podman machine is created.

I'm not sure it is worth the effort, to support `cloud-init` in addition to `ignition` ?

Before that has been done, Podman will only be able to support CoreOS for the VM.

It is easier to just use Vagrant or Lima, if all you want to do is run Podman in a VM ?

Something like: https://boot2podman.github.io/2020/07/22/machine-replacement.html

**Comment by cmoulliard** [comment]
> It is easier to just use Vagrant* or Lima, if all you want to do is run Podman in a VM ?

if using lima will allow on macos to do what we could do using docker desktop, then I'm fine

**Comment by afbjorklund** [comment]
> if using lima will allow on macos to do what we could do using docker desktop, then I'm fine

If you are happy with Docker Desktop, then by all means do continue to use Docker Desktop...
But if there is something missing in Podman or in Lima, then do open issues about it explicitely.

As far as I know, Docker Desktop allows you to run the LinuxKit distribution - and nothing else ?
So I don't see how Podman Machine would be different in this regard, you get Fedora CoreOS.

**Comment by cmoulliard** [comment]
> If you are happy with Docker Desktop, then by all means do continue to use Docker Desktop...

Not really as it only allows to boot a VM running k8s or docker and not buildah and/or podman ;-) and the VM cannot realy be used as a VM to ssh, install software, .... as we can do with vagrant or lima

**Comment by cmoulliard** [comment]
> As far as I know, Docker Desktop allows you to run the LinuxKit distribution - and nothing else ?

Yes but we cannot really use locally the VM to ssh, install software and compile code by example

**Comment by afbjorklund** [comment]
I think you were supposed to do that in containers, not on the VM.. But anyway, seems off topic.

**Comment by afbjorklund** [comment]
On the off chance that someone would like to make a custom ISO for Fedora, I added some [documentation](https://github.com/afbjorklund/fedora-lima#packages).
Otherwise it will use the regular [Fedora Cloud](https://cloud.fedoraproject.org/) (for OpenStack) image, when running podman with Lima...

But that brings in a lot of overhead, so it is _possible_ to do a more customized "spin" running as a "Live CD".
There is a similar project from Rancher, running containerd with Alpine. But that is enough off-topic for now.

**Comment by afbjorklund** [comment]
@cmoulliard : time to close ?

**Comment by afbjorklund** [comment]
I leave the old Fedora Linux docs up there in case anyone wants to re-open that thread in the future.

Otherwise it should be plenty with Fedora CoreOS (podman) and Fedora Cloud (lima), meanwhile.
Since podman _requires_ ignition and lima _requires_ cloud-init, those are more or less necessary anyway.

The alternative would be to use Alpine Linux, which already has a `podman` [package](https://pkgs.alpinelinux.org/packages?name=podman&branch=v3.14) in the aports...

* See https://wiki.alpinelinux.org/wiki/Podman

```console
lima-alpine:/home/anders/lima$ more /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.14.3
PRETTY_NAME="Alpine Linux v3.14"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
BUILD_ID="v0.2.2"
VARIANT_ID="std"
lima-alpine:/home/anders/lima$ podman version
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.16.8
Git Commit:   b7fc5b608b641cd9b9aec2647f9236e31f8f3b27
Built:        Sat Sep 11 14:33:25 2021
OS/Arch:      linux/amd64
```

**Comment by cmoulliard** [comment]
The content discussed here could become part of a FAQ detailing the alternatives which exist to play with `podman` using distro A,B, C and tools. WDYT ? @afbjorklund

**Comment by afbjorklund** [comment]
There **are** no alternatives, afaik. Could add more documentation to Lima, but it doesn't have a proper website or manual yet.

It also defaults to running ubuntu and nerdctl, so changing the tool over to fedora and podman will always be a bit awkward.

----

Theoretically you could change Podman to use RHCOS, but for now it is: FCOS.

> Any customer can have a car painted any color that he wants so long as it is black.

You can change the image stream: https://getfedora.org/en/coreos/download

* Stable
* Testing
* Next

There are plenty of other VM tools (like Vagrant), if you need more than "just Podman".

**Comment by cmoulliard** [comment]
Alternative was not perhaps the appropriate word. Sorry. 
What I'm proposing is to list under podman web site the option which exists to launch on a local machine a VM with different flavors (lima, vagrant) and to mention that podman supports only `ignition` vs lima `cloud-init` ... That will help the developers to figure what they will be able to do or not such as add package, ssh to the VM, ...
