### ISSUE TITLE
podman system service: what should .Host.RemoteSocket.Path be?

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#12023]
Start service with a nonstandard socket:
```console
$ bin/podman system service --timeout=0 tcp:localhost:12345
```
Run `info` against it:
```console
$ bin/podman-remote --url="tcp://localhost:12345" info --format '{{.Host.RemoteSocket.Path}}'
/run/user/14904/podman/podman.sock
```
This surprised me. I expected `tcp://<something>:12345`.

There is no obvious way to find the socket info: `podman-remote info | grep 12345` returns no output.

**Comment by vrothberg** [comment]
@jwhonce could you tackle it?  I had a quick look and it seems that the notion of it being a `path` (in contrast to a URI) is very embedded.

**Comment by rhatdan** [comment]
@jwhonce did you ever get a chance to look at this?

**Comment by edsantiago** [comment]
It's being worked on, @github-actions! Like, in the last two hours! #ReadingComprehensionFail #ThankGoodness #WeHaveSomeTimeBeforeTheRobotApocalypse
