### ISSUE TITLE
Unix sockets can't be checkpoint exported

### ISSUE THREAD

**Issue by carlhoerberg** [containers/podman#12020]
/kind bug

**Description**

UNIX domain sockets (special type of file) can't be tar:ed when exporting a checkpoint. I think it's a limitation in go's tar package, so maybe no quick fix here.. 

**Steps to reproduce the issue:**

1. `podman run -d docker.io/alpine sh -c "apk add netcat-openbsd && exec nc -lU /tmp/sock"`
2. `sleep 10 # wait some time for the pkg to be installed`
3. `podman container checkpoint --latest --export dump.tarz `

**Describe the results you received:**

```
ERRO[0000] Can't add file /var/lib/containers/storage/overlay/1b0bb322728fe44edc410f71bdbb2e51030a64270c54d1bb48a4d3bb9fe81029/merged//tmp/sock to tar: archive/tar: sockets not supported
```

**Describe the results you expected:**

The checkpoint to succeed without errors.

**Output of `podman version`:**

```
Version:      3.4.0
API Version:  3.4.0
Go Version:   go1.16.8
Built:        Thu Sep 30 21:40:21 2021
OS/Arch:      linux/amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Comment by mheon** [comment]
@adrianreber PTAL. I don't think there's much we can do about this except ignore sockets?
