### ISSUE TITLE
podman play kube --replace : timeout

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#12039]
Only one logged flake, but I've seen this one multiple times in the last two days on other PRs:
```
         Running: podman-remote [options] pod ps --format '{{.ID}}'
         @ - - [17/Oct/2021:21:33:52 -0500] "GET /v4.0.0/libpod/_ping HTTP/1.1" 200 2 "" "Go-http-client/1.1"
         @ - - [17/Oct/2021:21:33:52 -0500] "GET /v4.0.0/libpod/pods/json HTTP/1.1" 200 581 "" "Go-http-client/1.1"
         'f2d0ede34702'
         output: 'f2d0ede34702'
         Running: podman-remote [options] pod inspect testPod --format '{{len .Containers}}'
         Running: podman-remote [options] play kube --replace /tmp/podman_test035144678/kube.yaml
         @ - - [17/Oct/2021:21:33:52 -0500] "GET /v4.0.0/libpod/_ping HTTP/1.1" 200 2 "" "Go-http-client/1.1"
         @ - - [17/Oct/2021:21:33:52 -0500] "GET /v4.0.0/libpod/_ping HTTP/1.1" 200 2 "" "Go-http-client/1.1"
         [AfterEach] Podman play kube
           /var/tmp/go/src/github.com/containers/podman/test/e2e/play_kube_test.go:1089
         Running: podman-remote [options] stop -a --time 0
         @ - - [17/Oct/2021:21:35:22 -0500] "GET /v4.0.0/libpod/_ping HTTP/1.1" 200 2 "" "Go-http-client/1.1"
         
         

         ? Failure [183.193 seconds]
         Podman play kube
         /var/tmp/go/src/github.com/containers/podman/test/e2e/play_kube_test.go:1069
           podman play kube replace [It]
           /var/tmp/go/src/github.com/containers/podman/test/e2e/play_kube_test.go:2803
         
           Timed out after 90.000s.
           Expected process to exit.  It did not.
         
           /var/tmp/go/src/github.com/containers/podman/test/utils/utils.go:327
```
### Podman play kube [It] podman play kube replace
* fedora-34 : int remote fedora-34 root host [remote]
  * PR #11957
    * [10-17 22:43](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6402912982138880/html/int-remote-fedora-34-root-host.log.html#t--podman-play-kube-replace--1)
    * [10-17 22:43](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6402912982138880/html/int-remote-fedora-34-root-host.log.html#t--podman-play-kube-replace--2)
    * [10-17 22:43](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6402912982138880/html/int-remote-fedora-34-root-host.log.html#t--podman-play-kube-replace--3)

**Comment by vrothberg** [comment]
Is that remote only?

**Comment by edsantiago** [comment]
It seems to be. Here are the logged failures since my initial report:

### Podman play kube [It] podman play kube replace
* fedora-33 : int remote fedora-33 root host [remote]
  * PR #11956
    * [10-26 08:43](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5848798850187264/html/int-remote-fedora-33-root-host.log.html#t--podman-play-kube-replace--1)
    * [10-26 08:43](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5848798850187264/html/int-remote-fedora-33-root-host.log.html#t--podman-play-kube-replace--2)
    * [10-26 08:43](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5848798850187264/html/int-remote-fedora-33-root-host.log.html#t--podman-play-kube-replace--3)
* fedora-34 : int remote fedora-34 root host [remote]
  * PR #12021
    * [10-19 09:22](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5681603155329024/html/int-remote-fedora-34-root-host.log.html#t--podman-play-kube-replace--1)
  * PR #12281
    * [11-16 09:43](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6381403551039488/html/int-remote-ubuntu-2110-root-host.log.html#t--podman-play-kube-replace--1)

From that list I removed [this one](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6372436632403968/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-play-kube-replace--1) because it looks like a timeout fetching from k8s.io. That suggested that this bug might just be that timeout, misreported in the remote client, but the failure yesterday (in a PR that, presumably, includes #12280) implies otherwise.

**Comment by vrothberg** [comment]
Did it happen again?

**Comment by edsantiago** [comment]
Only two instances since my last post:

### Podman play kube [It] podman play kube replace
* fedora-34 : int remote fedora-34 root host [remote]
  * PR #12380
    * [11-23 04:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6750548943699968/html/int-remote-fedora-34-root-host.log.html#t--podman-play-kube-replace--1)
  * PR #12354
    * [11-18 15:20](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6088848565338112/html/int-remote-fedora-34-root-host.log.html#t--podman-play-kube-replace--1)

**Comment by rhatdan** [comment]
@edsantiago Still an issue?

**Comment by umohnani8** [comment]
@edsantiago have you seen this happen again recently?

**Comment by edsantiago** [comment]
Last one in my logs is 05-23.

**Comment by vrothberg** [comment]
That is good enough for me to close it.  We fixed some deadlocks in the recent past, so it _may_ be related.

Let's reopen if it pops up again.
