### ISSUE TITLE
Feature Request: Limit CPU Usage as a Percentage.

### ISSUE THREAD

**Issue by stellarpower** [containers/podman#12043]
/kind feature

### Overview:
There is a nice range of options [documented](https://docs.podman.io/en/v3.3.1/markdown/podman-run.1.html?highlight=cpu#cpu-period-limit) that allows me to set limits around CPU usage by a container. However, these appear to be based either on a policy to share resources between containers, or on hard limits around execution time. I don't know if it would be possible, but it would be useful and really user-friendly if I could limit a container's CPU usage by percentage, such that it will be throttled back if it goes above this percentage. To give a motivating case - googling how to limit CPU use led me to [this RedHat tutorial](http://redhatgov.io/workshops/security_containers/exercise1.4/#_step_3_view_the_processor_shares). We can see the container processor usage expressed as a percentage, and this is how we're acustomed to viewing it in top or any similar process monitor. I believe that being able to set an upper cap expressed as a percentage in this format would be simpler, and more useful for certain environments, than the (overall more flexible) concept of dividing 1024 virtual shares.

### Proposal in brief
- If this is technically possible to implement, add a flag, `--max-cpu` (I'll name it this for now, but I don't think it's a helpful name), accepting a real number [0.0,1.0], or percentage, that provides an upper limit to the proportion of cycles that the container's proceses may use. Settin --max-cpu=0.3 for example, should limit the container to 30% of available CPU processing shares at any given time, leaving at least 70% for other processes to be scheduled into, be that other containers or host processes.

### Background: 
A "known issue"[1] in the linux kernel means that without setting up a rigorous set of nice settings in advance, as a lone user of my personal machine, basically all processes normally start with the same priority. Something such as a rogue piece of javascript in a web browser can lock up my machine completely, and of course, this website is just as important as trying to open getty and kill the culprit. I have had rubbishy shell scripts mean that a TTY login fails because it took more than 60 seconds to check the password I just typed and thus was aborted for security reasons.

I develop in containers often now, and just had to killswitch because VS Code and make swallowed up all resources and froze me out. It would therefore be nice to set a rough ceiling on CPU resource usage, for a given container, ideally expressed as a percentage. The options already available are nice in that they are configurable, but anyone using htop on a system winding itself into oblivion will probably agree that a percentage speaks volumes. If I could run:

`podman run --rm -it --max-cpu=0.5 primesieve 1e100`

this would be a simple and succinct way of ensuring that no process inside a container (well, I guess in the cgroup under the hood) could exhaust my machine. It's less fine control than would be desireable for many environments, but I think there must be others like me whose usecase has limiting resource usage by any one container as primary concern, and setting specific limits as secondary. I'm running a multi-use server with my team now, and it's a powerful machine, and yet we still regularly eat into the 32G RAM and the swap and it dies. It's very much a development environment for computationally heavy work, so very unlike the carefully controlled production web-based servers a lot of containerisation was designed for. If others are using containers in less formal environments as I am with my team, then I would imagine this format of quota would be simpler than picking individual processsors or sharing the load between containers in a cluster/pod/kube.

### Points to consider:
- I like this idea as it's simple, and in particular, I reckon it reflects how we can limit memory use of a container. In the same manner, if I want a development process to fail over using up all my hardware RAM and swap space, I can set a memory limit of say 2G. This is easier than trying to think of a policy when it's not a controlled production environment. And whilst a percentage for memory would possibly also be easier, I think it's a slightly simpler calculation for RAM than it is for CPU scheduling.
- I am presuming that if the other CPU limit options exist, then the cointainer's processes must be able to be treated as one groupo, and limited altogether, so in this case, it would mean that the cumulative sum of CPU usage for any process inside the container would be limited. But there may be use cases for wanting to limit the usage of any one individual process, that happens to be inside the container
- Does 100% usage count for one core, or all cores combined? I think more often than not we take 100% to be a single core, but then this needs to be communicated clearly.

### Available workarounds:
- I'm about to google if there's any command I can use on the host, other than nice, that can implement this feature, in a hope to reduce the number of ocurrences per week I have to pull the kettle lead out the back and lose my work ;) - maybe these work well inside a container with the right capabilities added.
- I'm not entirely sure on --cpu-quota and --cpu-period - that is, if --cpu-period=100000 and --cpu-quota=50000 would be equivalent, to --max-cpu=0.5. If so then this should be trivial and a matter of interface choice.

(1): [Yes, we're still using operating systems based on 70s design principles](https://cdn.arstechnica.net/wp-content/uploads/2019/08/86-300837.jpg.870x660_q60_crop_upscale-800x607.jpg) - If anyone is interested, I would suggest checking out [Haiku](https://www.haiku-os.org/), a hybrid-architecture OS with a thin kernel and servers providng most features, that, given the vastly reduced number of developer hours it's had over linux, is wonderfully responsive when a userland process dies. As with fish shell, truly state-of-the-art 90s tech that is still working its way into the 2020s.

**Comment by mheon** [comment]
Question: is this expected to be 70% of 1 CPU, or 70% of all CPUs?

If it's the former, I think `podman run --cpus` already does what you want? `podman run --cpus 0.7` would be 70% of one CPU core. Multiply that by number of cores and you have 70% of the total system CPU.

**Comment by stellarpower** [comment]
> Didn't expect to see BeOS here 😀

🤣🍁

**Comment by flouthoc** [comment]
> > Question: is this expected to be 70% of 1 CPU, or 70% of all CPUs?
> > If it's the former, I think `podman run --cpus` already does what you want? `podman run --cpus 0.7` would be 70% of one CPU core. Multiply that by number of cores and you have 70% of the total system CPU.
> 
> Ahhh, okay, I missed that. I thought it was limiting the (integer) number of cores, ie if we want to prevent it using more than two parallel threads at a time, or divide up a very parallel server's hardware. Didn't realise I could give it a real number. Would it be okay to update the documentation a little bit please? And perhaps on the quota and period too, to give a bit more context or some examples; I think the details of the switches themselves are fine, but I was having to work out how it all pieces together.
> 
> Cheers - shall I close this, and also, open a separate issue for minor documentation edits?

@stellarpower Quoting above comment closing this issue.
