### ISSUE TITLE
Podman container image /run & /tmp assumptions

### ISSUE THREAD

**Issue by cevich** [containers/podman#12050]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Certain aspects of podman, in the context of the `upstream` flavors of the podman container image may assume `/run` and `/tmp` are a tmpfs.  This isn't possible to require from within the image itself, for every context (root vs rootless), so a `README.md` update is probably the most reasonable fix.

**Steps to reproduce the issue:**

1. Follow `README.md` for running the upstream podman container image

2. Do something in podman (in the container) which assumes a `tmpfs`

**Describe the results you received:**

It breaks.

**Describe the results you expected:**

It works.

**Additional information you deem important (e.g. issue happens only occasionally):**

I was requested to open this issue, I have no detailed knowledge/study of what's actually broken.

**Output of `podman version`:**

N/A

**Output of `podman info --debug`:**

N/A

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

N/A

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):**

N/A

**Comment by flouthoc** [comment]
@cevich Please correct me if i am wrong If i recall correctly this goes in parity with issues which @vrothberg faced while working with `pause` image. But underlying issues was `overlay` inside `overlay`. So wondering if this still an issue with any actual operation.

Could you also add the `Readme.md` link where this needs to be updated.

**Comment by giuseppe** [comment]
`/tmp` and `/run` are not needed to be on tmpfs, if the entire storage is transient.  e.g., when running in a nested container since the storage is destroyed once the parent container is removed

**Comment by mheon** [comment]
The problem is visible with pet containers, though. If the system restarts and the outer container is subsequently restarted we will run into issues.

**Comment by mheon** [comment]
(I think toolbox either mounts host `/tmp` or their own tmpfs to avoid this)

**Comment by giuseppe** [comment]
I think toolbox is mounting the host `/tmp` but also delegating podman to run on the host, not in the nested container, so it is the host responsibility to ensure `/tmp` and `/run` are on tmpfs

**Comment by cevich** [comment]
> Could you also add the Readme.md link where this needs to be updated.

IIRC, I was thinking of `./contrib/podmanimage/README.md` should maybe mention it so it doesn't catch users off-guard.

**Comment by rhatdan** [comment]
Where would you like it added?

**Comment by cevich** [comment]
"Sample Usage" maybe?  Though it's tricky enough of an issue, maybe it needs a dedicated section also.

**Comment by rhatdan** [comment]
You mean in the README.md file or TROUBLESHOOTING.md or podman.1.md?

**Comment by cevich** [comment]
Oh that's a thought, maybe all three?  I was thinking of the podman container images primarily because it seemed a likely place for someone to run into this.  But those other docs seem reasonable as well, especially `TROUBLESHOOTING.md`.

**Comment by rhatdan** [comment]
Care to open a PR against troubleshooting.md

**Comment by cevich** [comment]
TBH, I understand the basic technical issue here, but not the full practical effects or implications.  I don't feel I have enough experience to offer much on the troubleshooting topic.  I just thought we maybe needed to add a few `--tmpfs` args in the example...as a very blunt instrument to cover some abstract class of issues for people who use this container.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Care to take a stab at this?

**Comment by rhatdan** [comment]
I reread this and really am not sure what assumption about /run and /tmp being on a tmpfs?

Could you give me a concrete example of when this causes issue?  Are you talking about starting and stopping a container?

**Comment by mheon** [comment]
The issue is the same one we'd see on a host with Podman where our temporary files directory is not on a tmpfs, and an unclean shutdown occurs: the outer container is restarted, the temporary files directory is not on a tmpfs, the alive file is not removed as such; therefore, the state of all formerly-running containers that ran in the outer container is now incorrect.

**Comment by cevich** [comment]
Reminder: This issue was filed specifically against podman-in-a-container situations - where we most definitely cannot guarantee the type of `/tmp`.

**Comment by rhatdan** [comment]
I guess it would be nice if Containerfile had the concept of 

TMPFS /run

**Comment by cevich** [comment]
A Containerfile command isn't a guarantee, though that would perhaps solve the problem within `quay.io/containers/podman:latest` (stable) image.  In fact, can't we do that today with something like:

```dockerfile
RUN --mount=type=tmpfs,destination=/run
```

Or does that only affect the singular RUN command (layer)?  In that case, a new command (like TMPFS) which persisted mounts across all layers (including at runtime) would be a nice feature.  Though it would possibly break backwards compatibility with `Dockerfiles`, but maybe nobody cares.

**Comment by rhatdan** [comment]
Yes it would not work on Docker or Kubernetes.  I don't know if this was ever suggested in the past.

**Comment by rhatdan** [comment]
@nalind @vrothberg Thoughts.

**Comment by cevich** [comment]
Idea: Extending the `RUN --mount ...` with a new option, like `sticky=true` such that it persists for all subsequent layers and at runtime, maybe by adding a "magic" annotation?

**Comment by umohnani8** [comment]
@rhatdan @cevich @mheon this needs to be revisited to figure out what to do here.

**Comment by nalind** [comment]
Unilaterally extending Dockerfile syntax is a not on the table.  Is this a good use case for runlabels?

**Comment by mheon** [comment]
Runlabel seems like a reasonable solution to me.

**Comment by rhatdan** [comment]
Since we have a suggested fix, I am closing. Feel free to carry on discussion.
