### ISSUE TITLE
podman system service API does not honor cgroup settings in containers.conf

### ISSUE THREAD

**Issue by kanaka** [containers/podman#12059]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm building a containerized network simulation and development environment and I'm running podman within podman (as documented here: https://www.redhat.com/sysadmin/podman-inside-container). I am able to launch containers directly using the podman cli. However, if I try to launch the same configuration via the `podman system service` API I get conmon/cgroup sandboxing errors. It appears that the API process is not honoring some (or maybe all) `containers.conf` settings.

**Steps to reproduce the issue:**

1. Launch podman within podman like this: `podman run --rm --name podman-test --privileged quay.io/podman/stable podman system service --time=0 unix:///root/podman.sock`. Exec into the `podman-test` container in a different terminal.

2. In the `podman-test` container, pull down the alpine image: `podman pull alpine`. Then create a container via the API like this: `curl --unix-socket /root/podman.sock -H "Content-Type: application/json" -d '{"Image": "alpine", "Cmd": ["echo", "hello"]}' -X POST http://localhost/containers/create`

3. Attempt to start the container using the CID from above: `curl --unix-socket /root/podman.sock -X POST http://localhost/containers/${CID}/start`. 

**Describe the results you received:**

The creation of the container finishes and returns a container ID. However, the start command causes an error. The error from the service API is this:

```
time="2021-10-21T17:39:55Z" level=warning msg="Failed to add conmon to cgroupfs sandbox cgroup: error creating cgroup path /libpod_parent/conmon: write /sys/fs/cgroup/cgroup.subtree_control: device or resource busy"
@ - - [21/Oct/2021:17:39:54 +0000] "POST /containers/256eb18c6270489820b6c3fd1599db46a4f4629b6dca426a35697a8ec9980841/start HTTP/1.1" 500 230 "" "curl/7.76.1"
```

And the error returned to the curl command attempting to start the containers is this:

```
{"cause":"OCI runtime error","message":"writing file `/sys/fs/cgroup/libpod_parent/libpod-256eb18c6270489820b6c3fd1599db46a4f4629b6dca426a35697a8ec9980841/cgroup.procs`: Operation not supported: OCI runtime error","response":500}
```

**Describe the results you expected:**

The container should start successfully like it does with direct cli usage.

**Additional information you deem important (e.g. issue happens only occasionally):**

It doesn't matter whether the parent podman container is rootfull or rootless.

Using the podman cli directly works fine:

```
podman create alpine echo hello
CID=...
podman start -a ${CID}
```

In addition, if I use `podman create` but then try and start it via the API (curl to `.../start`) then that works fine. So it's the creation/definition of the container via the API that is problematic.

I have also tried copying the `/etc/containers/containers.conf` file to `/usr/share/containers/containers.conf` before staging the API service in case it is ignoring the `/etc/` location but the error still happens.

I have tried all the above with an custom built Ubuntu equivalent of the `quay.io/podman/stable` and get the same results.

**Output of `podman version`:**

```
Version:      3.4.0
API Version:  3.4.0
Go Version:   go1.16.8
Built:        Thu Sep 30 19:40:21 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    variant: container
    version: "34"
  eventLogger: file
  hostname: 7a1b599a7958
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.11.0-38-generic
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 1018458112
  memTotal: 12550447104
  ociRuntime:
    name: crun
    package: crun-1.2-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.2
      commit: 4f6c8e0583c679bfee6a899c05ac6b916022561b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 11999899648
  swapTotal: 11999899648
  uptime: 1h 54m 44.45s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /var/lib/shared
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.7.1-2.fc34.x86_64
      Version: |-
        fusermount3 version: 3.10.4
        fuse-overlayfs: version 1.7.1
        FUSE library version 3.10.4
        using FUSE kernel interface version 7.31
    overlay.mountopt: nodev,fsync=0
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.0
  Built: 1633030821
  BuiltTime: Thu Sep 30 19:40:21 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.0-1.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The host system is Ubuntu 20.04, kernel 5.11.0-38-generic, systemd 245.4-4ubuntu3.13), with cgroup v2 enabled via `systemd.unified_cgroup_hierarchy=1` kernel parameter (validated that `/sys/fs/cgroup/cgroup.controllers` exists).

**Comment by rhatdan** [comment]
I think this has been answered, reopen if I am mistaken.
