### ISSUE TITLE
Podman login does not support special characters in password

### ISSUE THREAD

**Issue by rajan123456** [containers/podman#12055]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

On debian bullseye (inside a docker container), trying to use podman to login to private registry. Registry has special character (@) in password.

**Steps to reproduce the issue:**

1. perform podman login to registry with special character in password (such as @)

**Describe the results you received:**
```
podman login my-secret-registry:8080 -u "myspecialuser" -p "myspecial@pass"
Error: error authenticating creds for "my-secret-registry:8080": error creating new docker client: readdirent: not a directory
```
**Describe the results you expected:**
The login should work correctly, as it works in docker login too.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.9
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
# podman info --debug
host:
  arch: amd64
  buildahVersion: 1.19.6
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 2
  distribution:
    distribution: debian
    version: "11"
  eventLogger: journald
  hostname: 113120c72a78
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.19.121-linuxkit
  linkmode: dynamic
  memFree: 204730368
  memTotal: 2062274560
  ociRuntime:
    name: runc
    package: 'runc: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0~rc93+ds1
      commit: 1.0.0~rc93+ds1-5+b2
      spec: 1.0.2-dev
      go: go1.15.9
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 889188352
  swapTotal: 1073737728
  uptime: 29h 34m 35.25s (Approximately 1.21 days)
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus: {}
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.9
  OsArch: linux/amd64
  Version: 3.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# apt list podman
Listing... Done
podman/stable,now 3.0.1+dfsg1-3+b2 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running inside docker container (python:3.7-bullseye)

**Comment by vrothberg** [comment]
Thanks for reaching out!  Special characters are supported but the error indicates something else:

> error creating new docker client: readdirent: not a directory

Could you rerun with `--log-level=debug`.  I suspect the error happens while setting up the TLS certificates.

Cc: @mtrmac
