### ISSUE TITLE
podman build error stat

### ISSUE THREAD

**Issue by haf-tech** [containers/podman#12075]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
podman build does not work on macOS with the info, that the Dockerfile can not be found.

**Steps to reproduce the issue:**

```
$ ls  
Dockerfile

$ podman build -f Dockerfile . -t alpine-custom
Error: stat /var/tmp/libpod_builder228622360/build/Users/xxx/repos/.../tmp/Dockerfile: no such file or directory

```

**Describe the results you received:**
It seems, that podman use a temp. directory to mount the local directory, but not successful

**Describe the results you expected:**
Successful podman build

**Additional information you deem important (e.g. issue happens only occasionally):**

- podman machine deleted, re-initialized
- podman system prune 

**Output of `podman version`:**

```
Client:
Version:      3.4.1
API Version:  3.4.1
Go Version:   go1.17.2
Built:        Tue Oct 19 23:14:42 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.4.0
API Version:  3.4.0
Go Version:   go1.16.8
Built:        Thu Sep 30 21:40:21 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "34"
  eventLogger: journald
  hostname: localhost
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.11-200.fc34.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 1301884928
  memTotal: 2061860864
  ociRuntime:
    name: crun
    package: crun-1.2-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.2
      commit: 4f6c8e0583c679bfee6a899c05ac6b916022561b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 0
  swapTotal: 0
  uptime: 27m 15.83s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.0
  Built: 1633030821
  BuiltTime: Thu Sep 30 19:40:21 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman: stable 3.4.1 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/usr/local/Cellar/podman/3.4.1 (170 files, 39.5MB) *
  Poured from bottle on 2021-10-24 at 18:25:22
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
macOS 11.6

**Comment by haf-tech** [comment]
@Luap99 very big, I have symlinks to remote storages/filesystems
with this info, repeating the scenario in an empty directory and the parent dir is not a symlink works totally fine

will be this fixed with the upcoming version?

**Comment by Luap99** [comment]
The default podman machine is only 10 GB AFAIK.
Please remove the machine with `podman machine rm` and create a new one with `podman machine init --disk-size 100` for 100 GB storage, you can use a bigger number if needed.

**Comment by haf-tech** [comment]
@Luap99 could you explain a little bit the background? will podman also replicate/copy the entire content into the machine instance too? Thanks

**Comment by rhatdan** [comment]
When using podman -remote, like we do on a MAC, podman build, copies the entire context directory on to the remote server. On a MAC this is the VM, in order that the Podman service actually doing the build has access to the contents. This works the exact same way as docker build.

So bottom line, you have to have enough space in the VM to store any content that you want to build from.

**Comment by haf-tech** [comment]
@rhatdan but I have never seen such problems with docker ;-) my environment (macOS, workspaces, storage, configuration etc) is still the same, I replaced only docker thru podman. So probably in the docker world the allocated space is much higher, instead of the default value 10GB?

**Comment by rhatdan** [comment]
Yes I would guess they have a much larger machine by default.

**Comment by haf-tech** [comment]
could we add in the install instruction page the hint with the size and `--disk-size` flag?
https://podman.io/getting-started/installation

**Comment by rhatdan** [comment]
Please open a PR on how you want to change it.

**Comment by Luap99** [comment]
The symlink error should be fixed and the default disk size was increased to 100GB
