### ISSUE TITLE
Port tunneling for the Cockpit web service

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman#12073]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

The port for the cockpit web interface (9090) is not tunneled in machine, only ssh (22)

There needs to be a similar port opened, either the real one or some random local port.

**Steps to reproduce the issue:**

1. [Install Cockpit](https://cockpit-project.org/running#coreos) and reboot the VM

```
podman machine ssh sudo rpm-ostree install cockpit-system cockpit-ostree cockpit-podman cockpit-pcp
podman machine ssh sudo systemctl reboot
```

2. Start the `cockpit` web service

```
podman machine ssh sudo podman container runlabel --name cockpit-ws RUN docker.io/cockpit/ws
podman machine ssh sudo podman container runlabel INSTALL docker.io/cockpit/ws
podman machine ssh sudo systemctl enable --now cockpit.service
```

3. https://localhost:9090

**Describe the results you received:**

"Unable to connect"

**Describe the results you expected:**

"Fedora CoreOS: Log in"

**Additional information you deem important (e.g. issue happens only occasionally):**

Using ssh is a workaround, similar to how to set up the compatibility unix socket for docker.

`-L 9090:localhost:9090`

But maybe there should be an option to set up tunneling for Cockpit, and output the URL ?

![cockpit-fedora-coreos-login](https://user-images.githubusercontent.com/10364051/138591057-48365019-17b0-4516-adb4-3d965e515717.png)

Note: I did have to set up a password for the "core" user, according to the instructions.

```console
$ podman machine ssh
...
[core@linux ~]$ echo 'PasswordAuthentication yes' | sudo tee /etc/ssh/sshd_config.d/02-enable-passwords.conf
PasswordAuthentication yes
[core@linux ~]$ sudo systemctl try-restart sshd
[core@linux ~]$ sudo passwd core
Changing password for user core.
New password: 
Retype new password: 
passwd: all authentication tokens updated successfully.
```

And I did have to accept the self-signed certificate in the web browser (for the https)...

**Output of `podman version`:**

```
3.3.1
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 20.04

**Comment by afbjorklund** [comment]
Note that gvproxy no longer exposes 7777, so you have to do it some other way.

**Comment by afbjorklund** [comment]
This will be done internally in podman and gvproxy instead, with authentication.

* https://github.com/containers/podman/issues/11494

**Comment by Luap99** [comment]
> Note that gvproxy no longer exposes 7777, so you have to do it some other way.
> 
>     * PR [podman machine improve port forwarding #12283](https://github.com/containers/podman/pull/12283)

You can use `podman machine ssh curl http://gateway.containers.internal/services/forwarder/expose  -X POST -d '{"local":":9090","remote":":9090"}'`

**Comment by afbjorklund** [comment]
But it seemed like the preferred approach for cockpit was to use ssh, anyway ?
