### ISSUE TITLE
Inconsistent API behavior when using unix socket vs the cli tool

### ISSUE THREAD

**Issue by iongion** [containers/podman#12076]
With the latest version `3.4.1` on Ubuntu 20.04 here are my scenarios

## Scenario 1

1. `podman system service --time=0 unix:///tmp/podman.socket --log-level=debug`
2. `podman system reset --force --log-level=debug`

Then I try to get a list of all the containers

Request 1 - `curl -iv --unix-socket /tmp/podman.socket http://d/v3.0.0/libpod/containers/json`

Server responds with `500`

```
< HTTP/1.1 500 Internal Server Error
< Api-Version: 1.40
< Libpod-Api-Version: 3.4.1

{"cause":"open /home/istoica/.local/share/containers/storage/libpod/bolt_state.db: no such file or directory","message":"error opening database /home/istoica/.local/share/containers/storage/libpod/bolt_state.db: open /home/istoica/.local/share/containers/storage/libpod/bolt_state.db: no such file or directory","response":500}
```

Immediately after I issue the command again

Request 1 - `curl -iv --unix-socket /tmp/podman.socket http://d/v3.0.0/libpod/containers/json`

It just hangs

## Scenario 2

1. `podman system service --time=0 unix:///tmp/podman.socket --log-level=debug`
2. `podman system reset --force --log-level=debug`

The I try to get a list of all the containers using podman cli

3. `podman container list --format=json` => returns correctly `[]`

I try again to get a list using the http over unix socket
4. `curl -iv --unix-socket /tmp/podman.socket http://d/v3.0.0/libpod/containers/json`

Responds ok
```
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Api-Version: 1.40
< Content-Type: text/plain; charset=us-ascii
< Libpod-Api-Version: 3.4.1

< 
[]
```

Although `Content-Type` should be `application/json` or `text/json`

Am I doing/understanding something wrong ?

**Comment by rhatdan** [comment]
Would it just make sense to have podman system reset do a 
systemctl try-restart podman.service
or systemctl --user try-restart podman.service

**Comment by rhatdan** [comment]
@cdoern would you like to take a look.

**Comment by cdoern** [comment]
@rhatdan sure, I am in this region anyway with my `podman system setup` work

**Comment by Luap99** [comment]
I still do not see why this is needed, `podman system prune` should work just fine.
Restarting the service via systemd will not work when the user manually runs the service as it is the case in the original report.

**Comment by rhatdan** [comment]
If I have a long running service waiting for a connection, ( I think we run for 5 minutes) then someone does podman system reset, connections to the service will fail until the service stops.  Stopping the service ourselves fixes that problem.
I agree if a user runs a service themselves, then it is there problem.

**Comment by cdoern** [comment]
@Luap99 @rhatdan how about this at the bottom of `libpod/reset.go`

```
cmd := exec.Command("systemctl")
if rootless.IsRootless() {
	cmd.Args = append(cmd.Args, []string{"--user", "try-restart", "podman.service"}...)
} else {
	cmd.Args = append(cmd.Args, []string{"try-restart", "podman.service"}...)
}
cmd.Stdin = os.Stdin
cmd.Stderr = os.Stderr
cmd.Env = os.Environ()
if err := cmd.Run(); err != nil {
	return err
}
```

**Comment by rhatdan** [comment]
SGTM
@vrothberg WDYT?

**Comment by rhatdan** [comment]
@vrothberg still need feedback.

**Comment by vrothberg** [comment]
That got lost over Christmas, apologies :)

SGTM, we just need to consider systems without systemd as well. The error should probably only be logged on info level.

**Comment by vrothberg** [comment]
@cdoern, do you have cycles to tackle the issue?

**Comment by rhatdan** [comment]
@iongion @cdoern is this one fixed?

**Comment by cdoern** [comment]
we decided that the behavior we were going to implement is not podman's prerogative to handle, but the users (aka just run a systemctl stop and restart)
