### ISSUE TITLE
How to configure CRun to use BTRFS storage driver backed by BTRFS filesystem?

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/podman#12103]
Is Crun aware about storage driver and backing Filesystem type? Fedora 33/34/35 are shipped with BTRFS / and  /home and filesystems. All artifacts are stored as BTRFS subvolumes by the BTRFS storage driver. What is missed if Podman succeeds to create containers for rootless users in the CLI mode but fails when Podman create is invoked by Systemd unit, i.e. passing to the service process limited set of Session's environment variables. Does CRun read storage.conf?

**Comment by PavelSosin-320** [comment]
No,No,No, this is Open source feature request related to using Podman on Linux workstation only. There is no Enterprise customer hard requirement behind it. Cloud based solution is more suitable for enterprise customers. But Fedora's cloud distro uses btrfs too. What to do with it?

**Comment by giuseppe** [comment]
> But Fedora's cloud distro uses btrfs too. What to do with it?

I suggest using overlay there, it works better also on BTRFS as backend.

If you still want to use BTRFS, PRs are welcome.

**Comment by PavelSosin-320** [comment]
@giuseppe I already tried overlay driver and fuse mount: the same issue. This is not btrfs itself. This is some combination of btrfs, mounting /home by systemd-homed timing and SELinux' customizable label in Fedora. I would like to build Storage CLI by myself and play around using systemd-run and mount dependency but my make failed😒maybe, because btrfs lib version 15.5 .

**Comment by rhatdan** [comment]
Is systemd-homed modifying the default binding set for caps?

grep Cap /proc/self/status

**Comment by PavelSosin-320** [comment]
@rhatdan 
From the "Terminal application"
grep Cap /proc/self/status
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	000001ffffffffff
CapAmb:	0000000000000000

**Comment by vrothberg** [comment]
There's an issue for systemd-homed already -> https://github.com/containers/podman/issues/12590
