### ISSUE TITLE
Unable to run Podman on gitpod

### ISSUE THREAD

**Issue by gbraad** [containers/podman#12136]
Have been looking into getting Podman to run on gitpod, but for some reason this fails. I use the following repo to get this started: https://github.com/gbraad/gitpod-template-podman/. You can easily open and verify this with https://gitpod.io/#https://github.com/gbraad/gitpod-template-podman

The error I get is that both Rootless and rooted does not work. Below are the errors:
```
gitpod /workspace/gitpod-template-podman (master) $ podman run alpine
WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
Error: cannot setup namespace using newuidmap: exit status 1
gitpod /workspace/gitpod-template-podman (master) $ sudo !!
sudo podman run alpine
Resolved "alpine" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/alpine:latest...
Getting image source signatures
Copying blob a0d0a0d46f8b done  
Copying config 14119a10ab done  
Writing manifest to image destination
Storing signatures
WARN[0002] Failed to add conmon to cgroupfs sandbox cgroup: error creating cgroup for cpu: mkdir /sys/fs/cgroup/cpu/libpod_parent: read-only file system 
Error: creating cgroup directory `/sys/fs/cgroup/memory/libpod_parent/libpod-960cc7a4b619e79904b10a34b88605764dba42224423b5dc06c7609816386f6a`: No such file or directory: OCI runtime attempted to invoke a command that was not found
```

From the debug info it shows conmon is failing as it does not having permissions. Anything that can be done?

If you fork the repo, you can modify the link: `https://gitpod.io/#https://github.com/[yourusername]/gitpod-template-podman` to retry.

**Comment by metafaniel** [comment]
> the first thing I'd check is why `/` is not mounted as shared.
> 
> Could you try `mount --make-rshared /` as root first?

I was having the same WARN and this command solves the issue under _Fedora Remix for WSL v34_.
Thanks!

**Comment by flouthoc** [comment]
@gbraad I think the error is coming from `crun` (https://github.com/containers/crun/blob/main/src/libcrun/cgroup.c#L587) . I wonder something is up with way the cgroup is mounted, permission issue or something entirely different with `gitpod` . 

Could you please paste content of  `mount`, `cat /proc/self/cgroup`,  `cat /proc/cgroups`  and `ls /sys/fs/cgroup`

**Comment by gbraad** [comment]
If you click the link above you can actually run it yourself and inspect.
Else you have to wait till tomorrow

**Comment by rhatdan** [comment]
@gbraad @flouthoc any progress on this?

**Comment by gbraad** [comment]
Gitpod can now run Fedora images since the introduction of Imge Builder mk3.

Will update the repo and try again.

**Comment by rhatdan** [comment]
Ok reopen this issue if there is work required by podman.

**Comment by gbraad** [comment]
This is still an issue, but this is on Gitpod to resolve. GitHub Codespaces does not have this issue. This can easily be tested with the https://github.com/gitpod-io/template-fedora image and installing `dnf install -y podman`

/cc: @csweichel
