### ISSUE TITLE
Cannot run containers with --pid host in RHEL 8u4

### ISSUE THREAD

**Issue by adamish** [containers/podman#12135]
/kind bug

**Description**

Following an upgrade from RHEL 8u2 to 8u4 rootless containers started with --pid host fail.

This is an example using a stock image, obviously you wouldn't need --pid host for the registry

1. As a non-privileged user, open a terminal
2. podman run --pid host docker.io/library/registry:2.7

**Describe the results you received:**
Error: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: readonly path /proc/asound: operation not permitted: OCI permission denied

**Describe the results you expected:**
The container to run

**Additional information you deem important (e.g. issue happens only occasionally):**

Observations
* Not specific to /proc/asound, on VM without soundcard it failed on /proc/bus
```
$ ls -ld /proc/asound /proc/bus
dr-xr-xr-x. 5 root root 0 Oct 29 06:47 /proc/asound
dr-xr-xr-x. 4 root root 0 Oct 29 06:47 /proc/bus
```
* Container runs if you add --privileged, however I would like to avoid this
* Can also be worked around by unmasking all the read-only default paths
```
--security-opt=unmask=/proc/asound:/proc/bus:/proc/fs:/proc/irq:/proc/sys:/proc/sysrq-trigger
```

**Output of `podman version`:**

```
Version:      3.0.2-dev
API Version:  3.0.0
Go Version:   go1.15.7
Built:        Wed Apr  7 08:36:54 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
  ociRuntime:
    name: runc
    package: runc-1.0.0-70.rc92.module+el8.4.0+10607+f4da7515.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.0.1-6.module+el8.4.0+10607+f4da7515.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes. Same issue with podman 3.4.1

**Additional environment details (AWS, VirtualBox, physical, etc.):**

 * Red Hat Enterprise Linux release 8.4 (Ootpa)
 * Virtual machine

**Comment by mheon** [comment]
I recall a bug of this nature from a few months back - it's possible we regressed from 8.3 to 8.4. Fix was in runc if I recall correctly?

**Comment by rhatdan** [comment]
This has a feeling of SELinux or Seccomp.

Could you check if one of those are involved.

sudo ausearch -m avc -ts recent
sudo ausearch -m seccomp -ts recent

**Comment by adamish** [comment]
SELinux is permissive, I'm aware of seccomp, but never had any dealings with it.

```
$ sudo ausearch -m avc -ts recent
<no matches>
$ sudo ausearch -m seccomp -ts recent
<no matches>
$ getenforce
Permissive
```

**Comment by rhatdan** [comment]
Well if crun works and runc does not, it could be an older runc or a bug in runc.

**Comment by mheon** [comment]
This is [RHBZ 1947432](https://bugzilla.redhat.com/show_bug.cgi?id=1947432) - we must have regressed. Missing patch from runc most likely.

**Comment by mheon** [comment]
There was apparently also a Podman patch. I don't see it in the v3.0.1-rhel branch.

**Comment by adamish** [comment]
Further info... Seems that /usr/bin/crun isn't actually present on my system. Note that system in question is a highly stripped down installation.

**Comment by rhatdan** [comment]
Since this can not be fixed in upstream podman, closing.  This should be a bugzilla.
