### ISSUE TITLE
Reporting outdated/vulnerable dependencies

### ISSUE THREAD

**Issue by masonzaizhe2** [containers/podman#12140]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
This is actually a security concern (not a bug report) of the dependencies you are using. Due to the scanning result of OWASP dependency check tool we find several vulnerabilities causing by outdated dependencies. Could you please confirm if you are using the dependency versions in the attached list and patch the old dependencies as soon as possible?

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**
[podman_dependency-check_2021-10-13.zip](https://github.com/containers/podman/files/7444043/podman_dependency-check_2021-10-13.zip)

**Describe the results you expected:**
All the dependencies should have been up-to-date

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
v3.4.1
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by lsm5** [comment]
@masonzaizhe2 thank you for the report. We recommend you follow the procedure outlined in https://github.com/containers/common/blob/main/SECURITY.md .

Thanks again.
