### ISSUE TITLE
bug: podman does not pass important args to runsc

### ISSUE THREAD

**Issue by unknowndevQwQ** [containers/podman#12142]
/kind bug

**Description**

Using runsc without adding `--runtime-flag root=/var/lib/containers` in podman causes runsc to complain that it cannot find the container

Because of the cgroup issue in runsc release-20211019.0, rrelease-20211011.0 is used here

**Steps to reproduce the issue:**

1. `sudo podman --cgroup-manager cgroupfs --runtime /bin/runsc --runtime-flag debug --runtime-flag debug-log=/tmp/runsc run --rm hello-world`

**Describe the results you received:**

/tmp/runsc: https://fars.ee/u__p
podman output:
```
WARN[0000] Failed to add conmon to cgroupfs sandbox cgroup: error creating cgroup path for net_cls: mkdir /sys/fs/cgroup/net_cls/libpod_parent: read-only file system 
loading container: file does not exist
Error: `/bin/runsc --debug --debug-log=/tmp/runsc start d8a7a9929c126fa4b23b63716aedaa37937a50485270b91a4efd31c3c9540a19` failed: exit status 128
```
**Describe the results you expected:**

Normal operation of the container

**Additional information you deem important (e.g. issue happens only occasionally):**

https://github.com/google/gvisor/issues/5887

**Output of `podman version`:**

```
Version:      3.4.1
API Version:  3.4.1
Go Version:   go1.17.1
Git Commit:   a6493ae6904a5b7dde2395a374cb77fc45c8a3bc
Built:        Thu Oct 21 01:27:47 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```  
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.0.30-1
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: 2792c16f4436f1887a7070d9ad99d9c29742f38a'
  cpus: 3
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: arch
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.14-zen1-1-zen
  linkmode: dynamic
  logDriver: journald
  memFree: 140382208
  memTotal: 6072868864
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.2-1
    path: /usr/bin/crun
    version: |-
      crun version 1.2
      commit: 4f6c8e0583c679bfee6a899c05ac6b916022561b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.1.12-1
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 4846288896
  swapTotal: 6442442752
  uptime: 26h 9m 8.14s (Approximately 1.08 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 9
    paused: 0
    running: 5
    stopped: 4
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 12
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.1
  Built: 1634750867
  BuiltTime: Thu Oct 21 01:27:47 2021
  GitCommit: a6493ae6904a5b7dde2395a374cb77fc45c8a3bc
  GoVersion: go1.17.1
  OsArch: linux/amd64
  Version: 3.4.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Name            : podman
Version         : 3.4.1-1
Description     : Tool and library for running OCI-based containers in pods
Architecture    : x86_64
URL             : https://github.com/containers/podman
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : cni-plugins  conmon  containers-common  crun  fuse-overlayfs  iptables  libdevmapper.so=1.02-64  libgpgme.so=11-64  libseccomp.so=2-64
                  slirp4netns
Optional Deps   : apparmor: for AppArmor support
                  btrfs-progs: support btrfs backend devices [installed]
                  catatonit: --init flag support [installed]
                  podman-docker: for Docker-compatible CLI
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 72.63 MiB
Packager        : Morten Linderud <foxboron@archlinux.org>
Build Date      : Thu Oct 21 01:27:47 2021
Install Date    : Mon Oct 25 13:08:04 2021
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Comment by rhatdan** [comment]
How is this a Podman bug and how do you suggest we fix it?

**Comment by unknowndevQwQ** [comment]
> How is this a Podman bug and how do you suggest we fix it?

How do other OCI runtimes handle this issue?

**Comment by rhatdan** [comment]
OCI Runtimes do not need to deal with container storage, they deal with already mounted images on rootfs. Podman and container engines manage the storage.

**Comment by unknowndevQwQ** [comment]
> OCI Runtimes do not need to deal with container storage, they deal with already mounted images on rootfs. Podman and container engines manage the storage.

offtopic: Can you create a telegram group for general questions and discussion?

**Comment by unknowndevQwQ** [comment]
> OCI Runtimes do not need to deal with container storage, they deal with already mounted images on rootfs. Podman and container engines manage the storage.

Is the --root flag that runsc wants the location of the rootfs?

**Comment by zhangguanzhang** [comment]
try:
```
sudo -E -i  podman --cgroup-manager cgroupfs --runtime /bin/runsc --runtime-flag debug --runtime-flag debug-log=/tmp/runsc run --rm hello-world
```

**Comment by unknowndevQwQ** [comment]
> try:
> 
> ```
> sudo -E -i  podman --cgroup-manager cgroupfs --runtime /bin/runsc --runtime-flag debug --runtime-flag debug-log=/tmp/runsc run --rm hello-world
> ```

`sudo: you may not specify both the -i and -E options`

**Comment by PavelSosin-320** [comment]
I think the same for the crun case, but in the special case: 1. Fedora 34, i.e BTRFS storage driver. 2. Podman invoked from the Systemd unit, i.e. storage root and Cgroup structure are not pre-defined by User's session. The result is "invalid reference" when binding volume. I tried to pass everything from the systemd environment but something is still missing. It can't be configured using crun configuration, only passed like in the FUSE case.

**Comment by PavelSosin-320** [comment]
For curiosity only: try
sudo systemctl --user xxxx
Failed to connect to bus: $DBUS_SESSION_BUS_ADDRESS and $XDG_RUNTIME_DIR not defined (consider using --machine=<user>@.host --user to connect to bus of other user)
to see what is needed, at least, to make systemd as cgroup manager working.

**Comment by mheon** [comment]
The crun issue is almost certainly unrelated.

For this issue, I think the actual solution is a new field in `containers.conf` to specify per-runtime arguments that should be added by default - see https://github.com/containers/common/issues/715.

**Comment by PavelSosin-320** [comment]
@mheon Related. ICrun needs many things that exported to the session environment by the services managed by the systemd --user. From the systemd point-of-view it is easy: PassEnvironment ...
On the Desktops Terminal is a plain Gnome GUI application reusing Session environment generated by systemd, exported to the session.service, like XDG_RUNTIME_DIR, Logger socket path, DBUS socket path. Journald socket exprted by the corresponding socket unit, tty init, ...
The same is true for CG tree.
To see the actual environment and  CG env is unusable. The real, up-to-moment picture is visible thrue systemd-cgls and systemctl --user show-environment.
Even to pass something from the /proc/self/environ to the container process inside container scope created by Crun Podman has to know what to pass and how to pass. Config is nice for sdanalone processes by it has to be boxed inside rootless GUI session, $XDG_CONFIG_HOME for example.
CRun CLI itself sufers from the same issue - it doesn't work correctly in the Linux Desktop terminal: the "static" Cgroup presence and API is not reliable because the real pre-requisits are 1. User session has started, i.e, $HOME, $XDG etc are exported to the environment and D-Bus broker has started, ready to accept "Create scope" message to the correct socket. 
If Podman can't work on Linux Desktops and WSL with systemd and GUI and always needs Terminal server, so what is its benefit?

**Comment by unknowndevQwQ** [comment]
https://fars.ee/KhKd

This is the output of /tmp/runsc when docker uses runsc

**Comment by unknowndevQwQ** [comment]
@rhatdan I want to know what environment variables podman passes to oci runtime

Related questions: https://github.com/google/gvisor/issues/6849#issuecomment-966525492

**Comment by rhatdan** [comment]
Looks like it passes down:
```
	env := []string{fmt.Sprintf("XDG_RUNTIME_DIR=%s", runtimeDir)}
	if path, ok := os.LookupEnv("PATH"); ok {
		env = append(env, fmt.Sprintf("PATH=%s", path))
	}
```

**Comment by unknowndevQwQ** [comment]
> Looks like it passes down:
> 
> ```
> 	env := []string{fmt.Sprintf("XDG_RUNTIME_DIR=%s", runtimeDir)}
> 	if path, ok := os.LookupEnv("PATH"); ok {
> 		env = append(env, fmt.Sprintf("PATH=%s", path))
> 	}
> ```

Variables with no value in rootfull mode

**Comment by vrothberg** [comment]
It has since been fixed in runsc to not use an empty XDG_ variable, so I am closing the issue.

**Comment by unknowndevQwQ** [comment]
If I had time, I would try to fix it

**Comment by unknowndevQwQ** [comment]
> 

@PavelSosin-320 The problem remains the same now?
