### ISSUE TITLE
pprof test is flaking again

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#12167]
Currently our number one flake. @jwhonce PTAL.

### podman system service verify pprof endpoints [It] are available
* fedora-33 : int podman fedora-33 rootless host
  * PR #12157
    * [11-02 18:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5904958668144640/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--1)
    * [11-02 18:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5904958668144640/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--2)
    * [11-02 18:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5904958668144640/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--3)
  * PR #12111
    * [10-27 07:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4832167642529792/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--1)
    * [10-27 07:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4832167642529792/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--2)
    * [10-27 07:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4832167642529792/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--3)
    * [10-27 06:32](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5567297298366464/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--1)
    * [10-27 06:32](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5567297298366464/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--2)
    * [10-27 06:32](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5567297298366464/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--3)
  * PR #12098
    * [10-26 13:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6203661832421376/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--1)
    * [10-26 13:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6203661832421376/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--2)
    * [10-26 13:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6203661832421376/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--3)
  * PR #12067
    * [10-26 13:06](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6266182060736512/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--1)
    * [10-26 13:06](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6266182060736512/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--2)
    * [10-26 13:06](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6266182060736512/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--3)
  * PR #12047
    * [10-20 15:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5454887401029632/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--1)
    * [10-20 15:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5454887401029632/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--2)
    * [10-20 15:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5454887401029632/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--3)
  * PR #11976
    * [10-14 17:17](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4838977950711808/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--1)
    * [10-14 17:17](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4838977950711808/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--2)
    * [10-14 17:17](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4838977950711808/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--3)
  * PR #11966
    * [10-14 07:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4973595848867840/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--1)
    * [10-14 07:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4973595848867840/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--2)
    * [10-14 07:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4973595848867840/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--3)
  * PR #11932
    * [10-12 06:49](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6507901175988224/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--1)
    * [10-12 06:49](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6507901175988224/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--2)
    * [10-12 06:49](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6507901175988224/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--3)
* fedora-34 : int podman fedora-34 rootless host
  * PR #11959
    * [10-15 15:20](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6537454577516544/html/int-podman-fedora-34-rootless-host.log.html#t--are-available--1)
    * [10-15 15:20](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6537454577516544/html/int-podman-fedora-34-rootless-host.log.html#t--are-available--2)
    * [10-15 15:20](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6537454577516544/html/int-podman-fedora-34-rootless-host.log.html#t--are-available--3)
  * PR #11919
    * [10-11 11:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4721141563523072/html/int-podman-fedora-34-rootless-host.log.html#t--are-available--1)
    * [10-11 11:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4721141563523072/html/int-podman-fedora-34-rootless-host.log.html#t--are-available--2)
    * [10-11 11:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4721141563523072/html/int-podman-fedora-34-rootless-host.log.html#t--are-available--3)
* ubuntu-2104 : int podman ubuntu-2104 rootless host
  * PR #12158
    * [11-01 15:51](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5440459565694976/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-available--1)
    * [11-01 15:51](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5440459565694976/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-available--2)
    * [11-01 15:51](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5440459565694976/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-available--3)
  * PR #12124
    * [10-28 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6550073325649920/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-available--1)
    * [10-28 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6550073325649920/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-available--2)
    * [10-28 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6550073325649920/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-available--3)
  * PR #12120
    * [10-28 04:06](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6009336943083520/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-available--1)
  * PR #11982
    * [10-14 17:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5527844802527232/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-available--1)
    * [10-14 17:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5527844802527232/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-available--2)
    * [10-14 17:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5527844802527232/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-available--3)
  * PR #11935
    * [10-12 07:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5819068348366848/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-available--1)
    * [10-12 07:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5819068348366848/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-available--2)
    * [10-12 07:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5819068348366848/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-available--3)

### podman system service verify pprof endpoints [It] are not available
* fedora-33 : int podman fedora-33 rootless host
  * PR #12118
    * [10-27 11:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6216959588040704/html/int-podman-fedora-33-rootless-host.log.html#t--are-not-available--1)
    * [10-27 11:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6216959588040704/html/int-podman-fedora-33-rootless-host.log.html#t--are-not-available--2)
    * [10-27 11:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6216959588040704/html/int-podman-fedora-33-rootless-host.log.html#t--are-not-available--3)
  * PR #12111
    * [10-27 06:32](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5567297298366464/html/int-podman-fedora-33-rootless-host.log.html#t--are-not-available--1)
  * PR #12098
    * [10-26 13:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6203661832421376/html/int-podman-fedora-33-rootless-host.log.html#t--are-not-available--1)
  * PR #12047
    * [10-20 15:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5454887401029632/html/int-podman-fedora-33-rootless-host.log.html#t--are-not-available--1)
  * PR #11971
    * [10-14 11:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5052447153455104/html/int-podman-fedora-33-rootless-host.log.html#t--are-not-available--1)
    * [10-14 11:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5052447153455104/html/int-podman-fedora-33-rootless-host.log.html#t--are-not-available--2)
    * [10-14 11:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5052447153455104/html/int-podman-fedora-33-rootless-host.log.html#t--are-not-available--3)
  * PR #11966
    * [10-14 07:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4973595848867840/html/int-podman-fedora-33-rootless-host.log.html#t--are-not-available--1)
    * [10-14 07:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4973595848867840/html/int-podman-fedora-33-rootless-host.log.html#t--are-not-available--2)
    * [10-14 07:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4973595848867840/html/int-podman-fedora-33-rootless-host.log.html#t--are-not-available--3)
* fedora-34 : int podman fedora-34 rootless host
  * PR #11919
    * [10-11 11:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4721141563523072/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--1)
    * [10-11 11:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4721141563523072/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--2)
* ubuntu-2104 : int podman ubuntu-2104 rootless host
  * PR #12092
    * [10-25 17:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4865469107666944/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-not-available--1)
    * [10-25 17:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4865469107666944/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-not-available--2)
    * [10-25 17:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4865469107666944/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-not-available--3)
  * PR #12066
    * [10-22 22:11](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6372436632403968/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-not-available--1)
  * PR #11925
    * [10-11 15:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5529224694988800/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-not-available--1)
    * [10-11 15:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5529224694988800/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-not-available--2)
    * [10-11 15:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5529224694988800/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-not-available--3)

Common factor seems to be rootless.

**Comment by edsantiago** [comment]
@jwhonce could you make time to look at this please? 

### podman system service verify pprof endpoints [It] are not available
* fedora-34 : int podman fedora-34 rootless host
  * PR #12235
    * [11-09 04:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6272633235832832/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--1)
    * [11-09 04:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6272633235832832/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--2)
    * [11-09 04:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6272633235832832/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--3)
* ubuntu-2104 : int podman ubuntu-2104 rootless host
  * PR #12250
    * [11-10 07:50](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6075431590821888/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-not-available--1)
    * [11-10 07:50](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6075431590821888/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-not-available--2)
    * [11-10 07:50](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6075431590821888/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-not-available--3)
  * PR #12162
    * [11-04 09:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6296467519307776/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-not-available--1)
    * [11-04 09:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6296467519307776/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-not-available--2)
    * [11-04 09:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6296467519307776/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-not-available--3)

### podman system service verify pprof endpoints [It] are available
* fedora-33 : int podman fedora-33 rootless host
  * PR #12157
    * [11-02 18:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5904958668144640/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--1)
    * [11-02 18:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5904958668144640/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--2)
    * [11-02 18:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5904958668144640/html/int-podman-fedora-33-rootless-host.log.html#t--are-available--3)
* fedora-34 : int podman fedora-34 rootless host
  * PR #12235
    * [11-09 04:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6272633235832832/html/int-podman-fedora-34-rootless-host.log.html#t--are-available--1)
    * [11-09 04:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6272633235832832/html/int-podman-fedora-34-rootless-host.log.html#t--are-available--2)
    * [11-09 04:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6272633235832832/html/int-podman-fedora-34-rootless-host.log.html#t--are-available--3)
  * PR #12221
    * [11-08 09:51](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6725032610103296/html/int-podman-fedora-34-rootless-host.log.html#t--are-available--1)
    * [11-08 09:51](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6725032610103296/html/int-podman-fedora-34-rootless-host.log.html#t--are-available--2)
    * [11-08 09:51](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6725032610103296/html/int-podman-fedora-34-rootless-host.log.html#t--are-available--3)
* ubuntu-2104 : int podman ubuntu-2104 rootless host
  * PR #12158
    * [11-01 15:51](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5440459565694976/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-available--1)
    * [11-01 15:51](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5440459565694976/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-available--2)
    * [11-01 15:51](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5440459565694976/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-available--3)

**Comment by edsantiago** [comment]
### podman system service verify pprof endpoints [It] are not available
* fedora-34 : int podman fedora-34 rootless host
  * PR #12235
    * [11-09 04:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6272633235832832/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--1)
    * [11-09 04:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6272633235832832/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--2)
    * [11-09 04:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6272633235832832/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--3)
* fedora-35 : int podman fedora-35 rootless host
  * PR #12414
    * [11-30 06:05](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5511109798002688/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--1)
    * [11-30 06:05](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5511109798002688/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--2)
    * [11-30 06:05](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5511109798002688/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--3)
  * PR #12372
    * [11-19 13:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5831848392654848/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--1)
    * [11-19 13:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5831848392654848/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--2)
    * [11-19 13:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5831848392654848/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--3)
* ubuntu-2104 : int podman ubuntu-2104 rootless host
  * PR #12250
    * [11-10 07:50](https://storage.googleapis.com/cirrus-ci-6707778565701632-fc
ae48/artifacts/containers/podman/6075431590821888/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-not-available--1)
    * [11-10 07:50](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6075431590821888/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-not-available--2)
    * [11-10 07:50](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6075431590821888/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-not-available--3)
  * PR #12214
    * [11-10 04:15](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4842270814896128/html/int-podman-ubuntu-2104-rootless-host.log.html#t--are-not-available--1)
* ubuntu-2110 : int podman ubuntu-2110 rootless host
  * PR #12326
    * [11-17 07:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6109713315135488/html/int-podman-ubuntu-2110-rootless-host.log.html#t--are-not-available--1)
    * [11-17 07:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fc
ae48/artifacts/containers/podman/6109713315135488/html/int-podman-ubuntu-2110-ro
otless-host.log.html#t--are-not-available--2)
    * [11-17 07:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6109713315135488/html/int-podman-ubuntu-2110-rootless-host.log.html#t--are-not-available--3)
  * PR #12257
    * [11-15 07:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6739054604582912/html/int-podman-ubuntu-2110-rootless-host.log.html#t--are-not-available--1)
  * PR #12174
    * [11-18 11:54](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5741028893261824/html/int-podman-ubuntu-2110-rootless-host.log.html#t--are-not-available--1)
    * [11-18 11:54](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5741028893261824/html/int-podman-ubuntu-2110-rootless-host.log.html#t--are-not-available--2)
  * PR #11957
    * [11-16 08:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6579341078298624/html/int-podman-ubuntu-2110-rootless-host.log.html#t--are-not-available--1)
    * [11-16 08:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6579341078298624/html/int-podman-ubuntu-2110-rootless-host.log.html#t--are-not-available--2)
    * [11-16 08:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6579341078298624/html/int-podman-ubuntu-2110-rootless-host.log.html#t--are-not-available--3)

@jwhonce ping

**Comment by edsantiago** [comment]
Can someone else, anyone, please take a look at this flake? It's hitting us hard.

### podman system service verify pprof endpoints [It] are not available
* fedora-35 : int podman fedora-35 rootless host
  * PR #12482
    * [12-02 10:46](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6132977408147456/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--1)
    * [12-02 10:46](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6132977408147456/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--2)
    * [12-02 10:46](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6132977408147456/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--3)
  * PR #12440
    * [12-02 15:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5683171254599680/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--1)
    * [12-02 15:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5683171254599680/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--2)
    * [12-02 15:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5683171254599680/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--3)

**Comment by edsantiago** [comment]
Oh noooooo... now it's [flaking in the Interrupt, not the Eventually](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6547120636297216/html/int-podman-fedora-35-rootless-host.log.html)

**Comment by vrothberg** [comment]
Come on! :laughing:

**Comment by Luap99** [comment]
Still flaking (I confirmed  that my branch has the latest "fix"): https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5457134111424512/html/int-podman-ubuntu-2110-rootless-host.log.html

**Comment by vrothberg** [comment]
:sob: ... OK, let's bump it to 10 seconds?

**Comment by vrothberg** [comment]
Bumped to 20 in https://github.com/containers/podman/pull/12588
