### ISSUE TITLE
podman-remote with journald+file mishmash: crashes client

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#12175]
With this `containers.conf`:
```
[containers]
log_driver = "journald"

[engine]
events_logger = "file"
```
...and this server command:
```console
$ bin/podman --log-level=info system service --timeout=0
```
...the following sequence yields an unexpected client failure:
```console
$ `bin/podman-remote run -d --name foo quay.io/libpod/testimage:20210610 sleep 30
39e6c6ac379b066642304f6b8d1b7ca12e36fa4023e7bf2061f8e3758ed2fc96
$ bin/podman-remote logs -f foo
Error: channel "123" found, 0-3 supported: lost synchronization with multiplexed stream
```
Expected: the new "file + journald not supported" error. (Which is shown on the server, but only as `info` level):
```
INFO[0016] Request Failed(Internal Server Error): failed to obtain logs for Container 'foo': using --follow with the journald --log-driver but without the journald --events-backend (file) is not supported
```

**Comment by edsantiago** [comment]
Oops, forgot to reference #11795

**Comment by rhatdan** [comment]
https://github.com/containers/podman/pull/12130 was an attempt to fix this, but I think we should just fail outright if you setup this environment. IE If you set journald for logging, we should require event-logger to use it and vice versa.

**Comment by cevich** [comment]
Any chance this is related to issue 12029 as well?  (I'm grasping at straws here)

**Comment by edsantiago** [comment]
Problem still present in main @ 18e31935ab068567178d50e0317ab2f3ea54926e

**Comment by rhatdan** [comment]
@edsantiago we still got this one?

**Comment by edsantiago** [comment]
Still present in main @ 46d9a2570ad3eb4f1d7fe0928927e644ebe8a2a3

**Comment by wnm3** [comment]
I'm getting these errors:
Error: host directory cannot be empty
Error: channel "123" found, 0-3 supported: lost synchronization with multiplexed stream
attempting to run a container mounting volumes

Any solution? I have tried using the command:
podman system connection default podman-machine-default-root

but this does not address the problem for podman v4.0.2

**Comment by robbiemu** [comment]
@cevich it looks possible to me as well. "--events-backend=file" would have specified where to write the logs by default, fi the logs command did not get updated as well, this could be the issue

**Comment by edsantiago** [comment]
Yikes - seen just now in a [random PR in the wild, possibly a flake](https://api.cirrus-ci.com/v1/artifact/build/6518740710850560/sys%20remote%20fedora-36%20root%20host/html/sys-remote-fedora-36-root-host.log.html#t--00074)
```
[+0120s] not ok 74 podman logs - basic test
         # # podman-remote [...] create quay.io/libpod/testimage:20220615 echo GSwcgzUZbhgjKIOCdvNIXEVvc7NqybRHOBGb9D2L
         # 0a167f24f01f348ab9f68e24f9e7f714dd90a70dc3155be488e9c929ce4911f0
         # # podman-remote [....] logs 0a167f24f01f348ab9f68e24f9e7f714dd90a70dc3155be488e9c929ce4911f0
         # Error: channel "123" found, 0-3 supported: lost synchronization with multiplexed stream
         # [ rc=125 (** EXPECTED 0 **) ]
```

**Comment by edsantiago** [comment]
Still present in main @ 07c0dd1f24b112c0161f61cafdfc1ab0866ebb9e (which includes #15717, the multiple-events-problems PR). We're approaching a year of this, and it seems like a non-issue. The June 27 flake bothers me though.

**Comment by vrothberg** [comment]
Tested with Podman v4.5 and both, local and remote, work.

**Comment by Luap99** [comment]
I would say I fixed it in https://github.com/containers/podman/pull/18282 but this is not in v4.5? Did you tested main instead?

**Comment by vrothberg** [comment]
I am fairly confident of having tested v4.5.  Does it not work on your end with 4.5?

**Comment by Luap99** [comment]
No it fails with v4.5, did you forget to add `-f` to logs? This is important to trigger the error condition.
You can also try 
```
$ podman-remote logs notexists
Error: channel "123" found, 0-3 supported: lost synchronization with multiplexed stream
```
Anyway doesn't matter it is 100% fixed on main :)

**Comment by vrothberg** [comment]
I did use `-f` so I must have used `main`.  Thanks for clarifying!
