### ISSUE TITLE
Error: chtimes /var/lib/containers/storage/volumes/my-volume-name/_data: permission denied

### ISSUE THREAD

**Issue by stiller-leser** [containers/podman#12185]
**Description**

I have a Kubernetes deployment where I run the podman api (privileged) and an ubuntu container that uses podman (via podman-remote as user 1000) automatically via a Jenkins automations. Before starting my container, Jenkins creates a podman volume that mounts a cifs volume.

In the ubuntu container my-deployment as user 1000 via Jenkins:
```
podman-remote volume create --driver local --opt type=cifs --opt device=//some.ip.goes.here/A_FOLDER --opt o=username=guest,password='' my-volume-name
```

After the volume is created, Jenkins tries to start a new container that should have access to this volume, again in the ubuntu container my-deployment as user 1000

```
podman-remote run -dt --mount type=bind,source=/my_base_path/scripts/,destination=/scripts --mount type=volume,source=my-volume-name,destination=/mnt--net=private --uts=private my-image:latest
```

When trying to start the container, Jenkins gets the following error message:

```
 Error: chtimes /var/lib/containers/storage/volumes/my-volume-name/_data: permission denied
```

Rerunning the `run` command in Jenkins does not help.

If I `kubectl exec` manually into my ubuntu container an re-run the run command, the container starts (even though the user (verified via whoami and id) is the same in both cases.

**Steps to reproduce the issue:**

1. Create a container that can run podman-remote
2. Deploy to Kubernetes (see below)
3. Create a podman volume (either NFS or CIFS)
4. Run a new container, e.g. busybox from within the container created in 1. and try to mount the volume.

**Describe the results you received:**

```
 Error: chtimes /var/lib/containers/storage/volumes/my-volume-name/_data: permission denied
```

**Describe the results you expected:**

The volume should be mounted or at least the behaviour between the execution via Jenkins pipeline and kubectl exec should be consistent.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 3.3.1
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.30-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 16
  distribution:
    distribution: fedora
    version: "35"
  eventLogger: file
  hostname: build-podman-21-mnrfj-0vwqx-18tn2
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.0-6-cloud-amd64
  linkmode: dynamic
  memFree: 258884120576
  memTotal: 270272696320
  ociRuntime:
    name: crun
    package: crun-1.2-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.2
      commit: 4f6c8e0583c679bfee6a899c05ac6b916022561b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: tcp:localhost:9999
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 0
  swapTotal: 0
  uptime: 78h 42m 5.73s (Approximately 3.25 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /var/lib/shared
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.7.1-2.fc35.x86_64
      Version: |-
        fusermount3 version: 3.10.5
        fuse-overlayfs: version 1.7.1
        FUSE library version 3.10.5
        using FUSE kernel interface version 7.31
    overlay.mountopt: nodev,fsync=0
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 22
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.1
  Built: 1634740316
  BuiltTime: Wed Oct 20 14:31:56 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/now 100:3.3.1-1 amd64 [installed,local]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Kubernetes with such deployment

```
---
apiVersion: v1
kind: Pod
metadata:
  name: my-deployment
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: podman
      image: quay.io/podman/stable
      imagePullPolicy: Always
      command:
      - /bin/sh
      - -c
      - podman system service --time=0 tcp:localhost:9999
      securityContext:
        privileged: true
    - name: my-deployment
      image: my-ubuntu-image-with-podman
      command:
        - /bin/sh
        - -c
        - tail -f /dev/null
      imagePullPolicy: Always
      securityContext:
        runAsUser: 1000
      env:
        - name: CONTAINER_HOST
          value: "tcp://localhost:9999"
```

**EDIT**
Removed `ro` from mount as this was a copy and paste mistake.

**Comment by rhatdan** [comment]
Permission denied is almost always SELinux or User Permissions. Looks like SELinux is disabled.

**Comment by stiller-leser** [comment]
Hey,

Thank you for the quick response. The strange thing is that it does not work when executed via Jenkins. But if I leave the pod running and then kubectl exec into (I.e. The same pod Jenkins started), it then works. So if SElinux would be to blame, I would expect it to never work...

Best regards,
stiller-leser
________________________________

**Comment by mheon** [comment]
What do you mean when you say that if you `kubectl exec` in, it works - are you running a container with the volume attached to it manually, and that works?

**Comment by mheon** [comment]
Also - the volume is mounted as read-only, but it seems Jenkins is trying to modify it (at the very least, to change the modification time?) - this seems expected? Read-only means read-only.

**Comment by stiller-leser** [comment]
> Also - the volume is mounted as read-only, but it seems Jenkins is trying to modify it (at the very least, to change the modification time?) - this seems expected? Read-only means read-only.

Hey, yes this was in fact a copy and paste mistake. Sorry about this

>What do you mean when you say that if you kubectl exec in, it works - are you running a container with the volume attached to it manually, and that works?

I mean, if Jenkins starts the pod (it does not work), but when it leaves the pod running and I then `kubectl exec` from my local machine into the same pod it does work.

**Comment by rhatdan** [comment]
The ID you ran above was that in on the node or in the container.  id -Z inside of a container will lie to you about SELinux being enabled.

I believe the issue is either your kubectl exec is running the success  full process with a different user or SELinux label, and this is why it succeeds.

**Comment by mheon** [comment]
Again, what do you do *after* you `kubectl exec`? Are you running a container that contains the volume?

**Comment by rhatdan** [comment]
cat /proc/self/attr/current 

if set, then you are on an SELinux system.

**Comment by flouthoc** [comment]
@stiller-leser Along with what @rhatdan mentioned could you also please paste output of `id` executed from `container` arg and the one you get after `kubectl exec`

**Comment by stiller-leser** [comment]
Hi everybody, 

I tried creating a picture to hopefully explain this a little better:

![grafik](https://user-images.githubusercontent.com/2844279/140938217-bafb9235-e8f8-4256-8114-7f993145b9e5.png)

Here's what I tried to do in the meantime:

- Ran `cat /proc/self/attr/current`, which returned `docker-default (enforce)` in both cases
- Ran `id`, returned `uid=1000(my-user) gid=9999(my-group) groups=9999(my-group)` in both cases
- Add both users in both containers to a common group with the name `my-group` and gid `9999` and created the volume with `-o guid=9999`
  - Did not help
- Mount the volume with `rw`
  - Did not help
- Verify that I am using the same kubeconfig for Jenkins and my local machine
- Compared both containers started by podman-remote run. The only difference I could find was the the working one had a `mergeddir` entry more under the overlayfs.

**Comment by rhatdan** [comment]
I might be missing something here.  But it seems you have podman running in rootless mode as UID 1000 within the container. Then you report the error as
 Error: chtimes /var/lib/containers/storage/volumes/my-volume-name/_data: permission denied
WHich should only happen if podman thought it was running in rootful mode, and is getting permission denied, because podman running as UID 1000 is attempting to modify a file owned by root.  Are my assumptions correct?

**Comment by rhatdan** [comment]
Closing for lack of feedback.
