### ISSUE TITLE
[RFE] `podman volume label [--list||--add||--remove] <volume>`

### ISSUE THREAD

**Issue by mskarbek** [containers/podman#12196]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I would like to be able to manipulate volume labels after volume creation and attachment to the container.
Use case:
- volume snapshot indication
- containers attachment history

`podman volume label [--list] <volume>` - list all labels, print formal like `volume inspect`, if no options specified for `label` `--list` used by default
`podman volume label --add key=value <volume>` - add new label to the volume
`podman volume label --remove key <volume>` - remove label from the volume

**Comment by mheon** [comment]
I don't think this is possible in the Podman model. Our objects (containers/volumes/pods) are, for the most part, immutable after creation.

**Comment by rhatdan** [comment]
Please give us more information on the use case?

**Comment by rhatdan** [comment]
Since we have had no additional feedback, I am closing, reopen if  you have new feedback.

**Comment by mskarbek** [comment]
I'm fine with this, I have rethought and moved this portion of metadata to the external KV store.
