### ISSUE TITLE
[RFE] Support for wildcard in `volume ls --filter label=key`

### ISSUE THREAD

**Issue by mskarbek** [containers/podman#12199]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Labels, following k8s standard, have prefix and name parts separated with `/`. Podman does not enforce strict k8s rules for volume labels, so I'm able to add another part after either `/` or `:` depending on which convention I would like to use.
I would like to be able to list all volumes marked with label `some.prefix.com/key/*` or `some.prefix.com/key:*`.
This functionality doesn't have to implement full RegEx just simple catch all in place of wildcard.

**Comment by flouthoc** [comment]
@mskarbek The use case you have specified could be easily matched with `HasPrefix` but nothing is stopping users from making a query like `*/secondlabel/anotherlabel/` so i am afraid we will end up implementing `regex` for this. 

I am not also sure if there were any intentions so support multiple labels using `delimiters` but I'd agree it would be cool thing to add. I'd wait for podman-maintainers perspective on this one. 

Thanks for creating the issue.

**Comment by flouthoc** [comment]
@mskarbek also just to clarify are you expecting `wildcards` in label keys ?

**Comment by mskarbek** [comment]
@flouthoc yes, I had keys in mind.

**Comment by mskarbek** [comment]
It's a convenience request for API and Ansible use cases. Ofc it can be worked around.

**Comment by rhatdan** [comment]
@jwhonce WDYT?

**Comment by flouthoc** [comment]
@mskarbek Could you please try above patch. Above patch adds supports to perform pattern based matching on keys. While keeps original behavior intact.
