### ISSUE TITLE
Unwanted logging output in API Bindings package

### ISSUE THREAD

**Issue by b177y** [containers/podman#12204]
In **pkg/bindings/containers/containers.go** there is an instance of `logrus.Infof` 
https://github.com/containers/podman/blob/abbd6c167e8163a711680db80137a0731e06e564/pkg/bindings/containers/containers.go#L203
which I assume was put there during development and was accidentally left in, as none of the other bindings seem to produce any output.

**Comment by flouthoc** [comment]
Hi @b177y I think you are correct but this on a `Info` level added in https://github.com/containers/podman/pull/7451 and I don't think it is doing any harm in fact it seems to be okay for `Info` purpose ? If it is causing any troubles from usage perspective I'd request moving it to `Debug`. 

But honestly I don't think its causing any harm. So i am closing this one but please feel free to move it to `debug` if you think its a better option :smile:
