### ISSUE TITLE
Connection refused is returned as Connection reset by peer

### ISSUE THREAD

**Issue by bogdanmuresan** [containers/podman#12237]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

 We have an haproxy running as podman rootless, when all frontends are disabled, it is expected we respond with 'Connection refused', but the response is actually  'Connection reset by peer'

  This can also be replicated running a container, and mapping to a closed port. The behaviour is different if the container is ran as root, or as rootless.

**Description**

**Steps to reproduce the issue:**

```
[root@testserver ~]# podman run -d --rm -p 9797:9797 nginx:latest
be6147859ae0ba6fa27ea3ef4e40cf5be47a807e2a67664f6c54197779a72ec6
[root@testserver ~]# curl localhost:9797
curl: (7) Failed to connect to localhost port 9797: Connection refused


[user@testserver ~]$ podman run -d --rm -p 9797:9797 nginx:latest
f284b82329ba625c7805dbfaf15826df2d6aad051df063053da56672fae5e5e7
[user@testserver ~]$  curl localhost:9797
curl: (56) Recv failure: Connection reset by peer
```

**Describe the results you received:**

Running as root: Connection refused
Running as non-root: Connection reset by peer

**Describe the results you expected:**

Running as root: Connection refused
Running as non-root: Connection refused

**Additional information you deem important (e.g. issue happens only occasionally):**

Is this expected behaviour?

Is there anyway we can respond with a 'Connection refused', with minor changes and still running as rootless? 
Apologies if this is not the right place for the question. Would https://github.com/rootless-containers/slirp4netns  be better suited?

**Output of `podman version`:**

```
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.15.7
Built:        Thu Jul 29 15:02:43 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.21.3
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.module+el8.4.0+11822+6cc1e7d7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: ae467a0c8001179d4d0adf4ada381108a893d7ec'
  cpus: 1
  distribution:
    distribution: '"rhel"'
    version: "8.4"
  eventLogger: file
  hostname: ip-172-31-6-171.eu-central-1.compute.internal
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-305.el8.x86_64
  linkmode: dynamic
  memFree: 494743552
  memTotal: 1902530560
  ociRuntime:
    name: runc
    package: runc-1.0.0-74.rc95.module+el8.4.0+11822+6cc1e7d7.x86_64
    path: /usr/bin/runc
    version: |-
      runc version spec: 1.0.2-dev
      go: go1.15.13
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 5m 22.18s
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.2.3
  Built: 1627570963
  BuiltTime: Thu Jul 29 15:02:43 2021
  GitCommit: ""
  GoVersion: go1.15.7
  OsArch: linux/amd64
  Version: 3.2.3
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.2.3-0.11.module+el8.4.0+12050+ef972f71.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical server running Red Hat Enterprise Linux release 8.3 (Ootpa) running an older version
but also tested in an AWS EC2 with version 3.2.3

**Comment by Luap99** [comment]
Yes this is a slirp4netns problem.
@AkihiroSuda Can this be fixed in slirp4netns?

**Comment by AkihiroSuda** [comment]
> Yes this is a slirp4netns problem. @AkihiroSuda Can this be fixed in slirp4netns?

The default port driver is RootlessKit, not slirp4netns.

And this behavior is expected with both RootlessKit and slirp4netns, because they always listen on the parent namespace regardless to whether the actual port is listened in the child namespace.

I'm not sure whether we can solve this issue.

**Comment by bogdanmuresan** [comment]
We are starting the podman container via systemd, so moving the systemd definition from the user namespace to system fixed this problem. The once concern is if this is an "official" feature, or just an implementation detail that could change in any version.

Thank you.

**Comment by Luap99** [comment]
I think it is a implementation detail. If this can be fixed it has to happen in slirp4netns and rootlesskit so I am going to close the issue since there is nothing podman can do.
