### ISSUE TITLE
failed to make veth pair: operation not supported

### ISSUE THREAD

**Issue by Mingli-Yu** [containers/podman#12246]
```
# podman --version
podman version 3.3.1

# podman run -it --name mybusybox  docker.io/library/busybox
Trying to pull docker.io/library/busybox:latest...
Getting image source signatures
Copying blob 01c2cdc13739 done  
Copying config cabb9f684f done  
Writing manifest to image destination
Storing signatures
ERRO[0000] error loading cached network config: network "podman" not found in CNI cache 
WARN[0000] falling back to loading from existing plugins on disk 
Error: error configuring network namespace for container 670d4af03e7c805a9fd12b14cde25e473b89302710e316e7501ac150de4c4726: error adding pod mybusybox_mybusybox to CNI network "podman": failed to make veth pair: operation not supported


```

**Comment by giuseppe** [comment]
it looks like your kernel doesn't support veth pairs.

What kernel are you using?

**Comment by Mingli-Yu** [comment]
The kernel version is 5.10.75, how to configure the kernel to support veth pairs, any hints? Thanks,

**Comment by giuseppe** [comment]
My suggestion is to start from a known working configuration, like the Fedora kernel configuration: https://src.fedoraproject.org/rpms/kernel/blob/rawhide/f/kernel-x86_64-fedora.config

**Comment by Mingli-Yu** [comment]
Thanks, install xt_conntrack.ko address the above error.

**Comment by Hergeirs** [comment]
I know this is closed, but I'm running a custom kernel. Does anyone by chance know which kernel modules would have to be added ? If not, just ignore this.

**Comment by giuseppe** [comment]
for xt_conntrack.ko you'd probably need `CONFIG_NETFILTER_XT_MATCH_CONNTRACK`

**Comment by Hergeirs** [comment]
It seems I needed quite a few modules.
The ones I didn't have already are listed below for anyone curious:

- bridge
- libcrc32c
- llc
- nf_conntrack
- nf_defrag_ipv4
- nf_defrag_ipv6
- nf_nat
- nfnetlink
- nf_tables
- nft_chain_nat
- nft_compat
- nft_counter
- stp
- veth
- xt_addrtype
- xt_comment
- xt_conntrack
- xt_mark
- xt_MASQUERADE
- xt_multiport
- xt_nat
- xt_tcpudp

I you deem this irrelevant or "noise" feel free to remove my message.

**Comment by giuseppe** [comment]
> I you deem this irrelevant or "noise" feel free to remove my message.

I think it is useful for other users that end up with the same issue.  Thanks for sharing it

**Comment by ctron** [comment]
On a Raspberry Pi with Ubuntu, the fix for this is:

```
sudo apt install linux-modules-extra-raspi
```

And a reboot.
