### ISSUE TITLE
play kube: brings in unwanted k8s pause

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#12254]
IIUC the world has changed, and pods no longer need k8s/pause. `podman play kube` fetches it anyway:
```console
$ bin/podman images
REPOSITORY  TAG         IMAGE ID    CREATED     SIZE
$ printf "apiVersion: v1\nkind: Pod\nmetadata:\n  name: foo\n" | env CONTAINER_HELPER_PAUSE_PAUSE=bin/pause bin/podman play kube -
Pod:
738622313f1f37b32814664a8dc86d2df36dd5036e661e1d15623686e26c2616
$ bin/podman images
REPOSITORY              TAG                   IMAGE ID      CREATED        SIZE
localhost/podman-pause  4.0.0-dev-1636547894  99f3b83b4245  5 seconds ago  1.65 MB
k8s.gcr.io/pause        3.5                   ed210e3e4a5b  7 months ago   690 kB
```
I expected to see `localhost/podman-pause`; did not expect to see the `k8s` one.

main @ 5437568fcda04c2999b5fa9aad4dd07f2d3cfd67

**Comment by rhatdan** [comment]
@vrothberg PTAL

podman/pkg/domain/infra/abi/play.go is pulling the image.

**Comment by vrothberg** [comment]
Thanks for the report and the ping.

Here's a PR to fix the issue: https://github.com/containers/podman/pull/12280

**Comment by setharnold** [comment]
Hello, was a CVE assigned for this issue? Thanks

**Comment by rhatdan** [comment]
No
