### ISSUE TITLE
flake: check dnsname plugin test

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#12273]
Seeing this one a lot lately:
```
Running: podman [options] run --name con1 --network IntTestcfd597779839e0e4a2e0a821b1a825a17109390c73abd966d39a2f397b4f0cb7 quay.io/libpod/alpine:latest nslookup con1
         nslookup: can't resolve '(null)': Name does not resolve
```
### Podman run networking [It] podman run check dnsname plugin
* fedora-33 : int podman fedora-33 root container
  * PR #12098
    * [10-26 13:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5640711879000064/html/int-podman-fedora-33-root-container.log.html#t--podman-run-check-dnsname-plugin--1)
* fedora-33 : int podman fedora-33 rootless host
  * PR #12227
    * [11-09 10:46](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6097254554533888/html/int-podman-fedora-33-rootless-host.log.html#t--podman-run-check-dnsname-plugin--1)
    * [11-09 10:46](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6097254554533888/html/int-podman-fedora-33-rootless-host.log.html#t--podman-run-check-dnsname-plugin--2)
    * [11-09 10:46](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6097254554533888/html/int-podman-fedora-33-rootless-host.log.html#t--podman-run-check-dnsname-plugin--3)
* fedora-34 : int podman fedora-34 rootless host
  * PR #12235
    * [11-09 04:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6272633235832832/html/int-podman-fedora-34-rootless-host.log.html#t--podman-run-check-dnsname-plugin--1)
  * PR #12221
    * [11-08 09:51](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6725032610103296/html/int-podman-fedora-34-rootless-host.log.html#t--podman-run-check-dnsname-plugin--1)
* ubuntu-2104 : int podman ubuntu-2104 rootless host
  * PR #12250
    * [11-10 07:50](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6075431590821888/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-run-check-dnsname-plugin--1)
  * PR #12214
    * [11-10 21:01](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5310151935655936/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-run-check-dnsname-plugin--1)
    * [11-10 21:01](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5310151935655936/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-run-check-dnsname-plugin--2)
    * [11-10 21:01](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5310151935655936/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-run-check-dnsname-plugin--3)
    * [11-10 04:15](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4842270814896128/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-run-check-dnsname-plugin--1)
    * [11-10 04:15](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4842270814896128/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-run-check-dnsname-plugin--2)
    * [11-10 04:15](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4842270814896128/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-run-check-dnsname-plugin--3)
  * PR #12066
    * [10-22 22:11](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6372436632403968/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-run-check-dnsname-plugin--1)
    * [10-22 22:11](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6372436632403968/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-run-check-dnsname-plugin--2)
    * [10-22 22:11](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6372436632403968/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-run-check-dnsname-plugin--3)

**Comment by edsantiago** [comment]
Another one in [f34 rootless](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6048788029636608/html/int-podman-fedora-34-rootless-host.log.html#t--podman-run-check-dnsname-plugin--1)

**Comment by edsantiago** [comment]
Not as frequent, but still happening as of 11-29

### Podman run networking [It] podman run check dnsname plugin
* fedora-35 : int podman fedora-35 rootless host
  * PR #12372
    * [11-19 13:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5831848392654848/html/int-podman-fedora-35-rootless-host.log.html#t--podman-run-check-dnsname-plugin--1)
* ubuntu-2110 : int podman ubuntu-2110 rootless host
  * PR #12401
    * [11-29 11:10](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4708385208664064/html/int-podman-ubuntu-2110-rootless-host.log.html#t--podman-run-check-dnsname-plugin--1)
    * [11-29 11:10](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4708385208664064/html/int-podman-ubuntu-2110-rootless-host.log.html#t--podman-run-check-dnsname-plugin--2)
    * [11-29 11:10](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4708385208664064/html/int-podman-ubuntu-2110-rootless-host.log.html#t--podman-run-check-dnsname-plugin--3)
  * PR #12174
    * [11-18 11:54](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5741028893261824/html/int-podman-ubuntu-2110-rootless-host.log.html#t--podman-run-check-dnsname-plugin--1)

**Comment by rhatdan** [comment]
It will be interesting to see if this flake disappears when we move to netavark/ardvark.

**Comment by baude** [comment]
@edsantiago is this still a thing?

**Comment by edsantiago** [comment]
Okay, this is weird and a little disconcerting: yes, it's still happening, multiple times every day up to and including [yesterday](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6730236153823232/html/int-podman-fedora-34-rootless-host.log.html#t--podman-run-check-dnsname-plugin--1). But it's not causing test failures:
```
podman run check dnsname plugin
           /var/tmp/go/src/github.com[/containers/podman/test/e2e/run_networking_test.go:817](https://github.com/containers/podman/blob/44fb431a3ced04c6b9e5d05dd7601dc5d2c9159b/test/e2e/run_networking_test.go#L817)
         
         [BeforeEach] Podman run networking
           /var/tmp/go/src/github.com[/containers/podman/test/e2e/run_networking_test.go:24](https://github.com/containers/podman/blob/44fb431a3ced04c6b9e5d05dd7601dc5d2c9159b/test/e2e/run_networking_test.go#L24)
         [It] podman run check dnsname plugin
           /var/tmp/go/src/github.com[/containers/podman/test/e2e/run_networking_test.go:817](https://github.com/containers/podman/blob/44fb431a3ced04c6b9e5d05dd7601dc5d2c9159b/test/e2e/run_networking_test.go#L817)
         $ podman [options] --network-backend cni --storage-driver vfs pod create --name testpod
         663e1ad89f5283fab52b1633b53216dca33154bb2320144ef8dc13d1dbc72a82
         $ podman [options] --network-backend cni --storage-driver vfs network create IntTestce2407e99e14fad72057828a6a81b93a2076b1c6a2324ba3c9b22de4a7643389
         IntTestce2407e99e14fad72057828a6a81b93a2076b1c6a2324ba3c9b22de4a7643389
         $ podman [options] --network-backend cni --storage-driver vfs pod create --network IntTestce2407e99e14fad72057828a6a81b93a2076b1c6a2324ba3c9b22de4a7643389 --name testpod2
         e3b1f24562ee26216266249f5b229953468264aa91abdf1cf5c44bbf79c0ad31
         $ podman [options] --network-backend cni --storage-driver vfs run --name con1 --network IntTestce2407e99e14fad72057828a6a81b93a2076b1c6a2324ba3c9b22de4a7643389 quay.io/libpod/alpine:latest nslookup con1
         
         Name:      con1
         Address 1: 10.89.1.2 0f197ad787e9
         nslookup: can't resolve '(null)': Name does not resolve
         output: Name: con1 Address 1: 10.89.1.2 0f197ad787e9
         $ podman [options] --network-backend cni --storage-driver vfs run --name con2 --pod testpod --network IntTestce2407e99e14fad72057828a6a81b93a2076b1c6a2324ba3c9b22de4a7643389 quay.io/libpod/alpine:latest nslookup con2
         nslookup: can't resolve '(null)': Name does not resolve
         
         Name:      con2
         Address 1: 10.89.1.2 8c110b32980d
         output: Name: con2 Address 1: 10.89.1.2 8c110b32980d
         $ podman [options] --network-backend cni --storage-driver vfs run --name con3 --pod testpod2 quay.io/libpod/alpine:latest nslookup con1
         
         nslookup: can't resolve '(null)': Name does not resolve
         nslookup: can't resolve 'con1': Name does not resolve
         $ podman [options] --network-backend cni --storage-driver vfs run --name con4 --network IntTestce2407e99e14fad72057828a6a81b93a2076b1c6a2324ba3c9b22de4a7643389 quay.io/libpod/alpine:latest nslookup testpod2.dns.podman
         nslookup: can't resolve '(null)': Name does not resolve
         
         Name:      testpod2.dns.podman
         Address 1: 10.89.1.2 testpod2.dns.podman
         output: Name: testpod2.dns.podman Address 1: 10.89.1.2 testpod2.dns.podman
```
I'm trying to wrap up for the day so I'm not going to investigate any further. Maybe one of y'all can see this and recognize it as "oh no big deal".

**Comment by edsantiago** [comment]
### Podman run networking [It] podman run check dnsname plugin with Netavark 
* fedora-35 : Netavark int podman root
  * PR #13662
    * [03-25 11:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4594481012932608/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--1)
    * [03-25 11:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4594481012932608/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--2)
    * [03-25 11:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4594481012932608/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--3)
  * PR #13575
    * [03-21 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4749337602293760/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--1)
  * PR #13460
    * [03-08 14:19](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5807891213975552/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--1)
    * [03-08 14:19](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5807891213975552/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--2)
    * [03-08 14:19](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5807891213975552/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--3)

**Comment by edsantiago** [comment]
This is a different test, but the symptom (dig, no results) looks similar. Oh, and all of these are causing CI failures.

### Podman run networking [It] Aardvark Test 5: Two containers on their own subnets, one container on both 
* fedora-35 : Netavark int podman root
  * PR #13662
    * [03-25 11:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4594481012932608/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--1)
    * [03-25 11:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4594481012932608/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--2)
    * [03-25 11:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4594481012932608/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--3)
  * PR #13575
    * [03-21 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4749337602293760/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--1)
    * [03-21 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4749337602293760/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--2)
    * [03-21 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4749337602293760/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--3)

**Comment by edsantiago** [comment]
Another failure-to-resolve one, possibly related, possibly not

### Podman network [It] podman Netavark network with multiple aliases 
* fedora-35 : Netavark int podman root
  * PR #13662
    * [03-25 11:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4594481012932608/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-Netavark-network-with-multiple-aliases--1)
    * [03-25 11:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4594481012932608/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-Netavark-network-with-multiple-aliases--2)
    * [03-25 11:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4594481012932608/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-Netavark-network-with-multiple-aliases--3)

**Comment by edsantiago** [comment]
Still happening

### Podman run networking [It] podman run check dnsname plugin with Netavark 
* fedora-35 : Netavark int podman root
  * PR #14038
    * [04-27 17:34](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4755624041906176/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--1)
    * [04-27 17:34](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4755624041906176/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--2)
    * [04-27 17:34](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4755624041906176/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--3)
  * PR #13975
    * [04-22 09:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5344791163568128/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--1)
    * [04-22 09:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5344791163568128/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--2)
    * [04-22 09:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5344791163568128/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--3)

**Comment by edsantiago** [comment]
### Podman run networking [It] podman run check dnsname plugin with Netavark
*  fedora-36 : int podman fedora-36 root host
   * PR #14163
     * [05-09 13:02](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6619009629028352/html/int-podman-fedora-36-root-host.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--1)
     * [05-09 13:02](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6619009629028352/html/int-podman-fedora-36-root-host.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--2)
     * [05-09 13:02](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6619009629028352/html/int-podman-fedora-36-root-host.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--3)
   * PR #14040
     * [04-28 08:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5047243462934528/html/int-podman-fedora-36-root-host.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--1)
     * [04-28 08:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5047243462934528/html/int-podman-fedora-36-root-host.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--2)
     * [04-28 08:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5047243462934528/html/int-podman-fedora-36-root-host.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--3)

**Comment by rhatdan** [comment]
@flouthoc PTAL

**Comment by edsantiago** [comment]
Haven't seen this one since, oh, Monday:

### Podman run networking [It] podman run check dnsname plugin with Netavark 
* fedora-35 : Netavark int podman root
  * PR #15147
    * [08-02 04:31](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4600321107296256/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--1)
    * [08-02 04:31](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4600321107296256/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--2)
    * [08-02 04:31](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4600321107296256/html/int-podman-fedora-35-root-host-netavark.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--3)
* fedora-36 : int remote fedora-36 root host [remote]
  * PR #15479
    * [08-29 04:14](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4734581415870464/html/int-remote-fedora-36-root-host.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--1)
    * [08-29 04:14](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4734581415870464/html/int-remote-fedora-36-root-host.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--2)
    * [08-29 04:14](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4734581415870464/html/int-remote-fedora-36-root-host.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--3)
  * PR #15474
    * [08-25 00:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6024322815885312/html/int-remote-fedora-36-root-host.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--1)
    * [08-25 00:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6024322815885312/html/int-remote-fedora-36-root-host.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--2)
    * [08-25 00:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6024322815885312/html/int-remote-fedora-36-root-host.log.html#t--podman-run-check-dnsname-plugin-with-Netavark--3)

**Comment by vrothberg** [comment]
still happening?

**Comment by edsantiago** [comment]
Last seen 09-20, so logs have been lost. I don't know if this is related to our current set of DNS lookup flakes, but I guess there's no point in keeping this open.
