### ISSUE TITLE
checkpoint/restore fails with PostgreSQL

### ISSUE THREAD

**Issue by rst0git** [containers/podman#12277]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Container checkpoint fails for PostgreSQL without the CRIU fix in https://github.com/checkpoint-restore/criu/pull/1622.
However, with this fix container restore still fails due to missing files in `/dev/shm` 

**Steps to reproduce the issue:**

1. `sudo podman  run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres`

2. `sudo podman container checkpoint some-postgres`

3. `sudo podman container restore some-postgres`

**Describe the results you received:**
Podman error message:

> Error: OCI runtime error: CRIU restoring failed -52.  Please check CRIU logfile /var/lib/containers/storage/overlay-containers/eed25ae4295e9b5f5af50adfca4c910e89baa0fab751f5b23be1e4ce520d2763/userdata/restore.log

CRIU error message:
```
    56: Opening 0x007f5b8d13b000-0x007f5b8d142000 0000000000000000 (81) vma
    56: Error (criu/files-reg.c:2143): Can't open file dev/shm/PostgreSQL.2016670368 on restore: No such file or directory
     1: Opening 0x007f5b8d13b000-0x007f5b8d142000 0000000000000000 (81) vma
    56: Error (criu/files-reg.c:2086): Can't open file dev/shm/PostgreSQL.2016670368: No such file or directory
    56: Error (criu/mem.c:1349): `- Can't open vma
     1: Error (criu/files-reg.c:2143): Can't open file dev/shm/PostgreSQL.2016670368 on restore: No such file or directory
     1: Error (criu/files-reg.c:2086): Can't open file dev/shm/PostgreSQL.2016670368: No such file or directory
     1: Error (criu/mem.c:1349): `- Can't open vma
    57: Opening 0x007f5b8d13b000-0x007f5b8d142000 0000000000000000 (81) vma
    58: Opening 0x007f5b8d13b000-0x007f5b8d142000 0000000000000000 (81) vma
    58: Error (criu/files-reg.c:2143): Can't open file dev/shm/PostgreSQL.2016670368 on restore: No such file or directory
    58: Error (criu/files-reg.c:2086): Can't open file dev/shm/PostgreSQL.2016670368: No such file or directory
    58: Error (criu/mem.c:1349): `- Can't open vma
    57: Error (criu/files-reg.c:2143): Can't open file dev/shm/PostgreSQL.2016670368 on restore: No such file or directory
    59: Opening 0x007f5b8d13b000-0x007f5b8d142000 0000000000000000 (81) vma
    57: Error (criu/files-reg.c:2086): Can't open file dev/shm/PostgreSQL.2016670368: No such file or directory
    57: Error (criu/mem.c:1349): `- Can't open vma
    61: Opening 0x007f5b8d127000-0x007f5b8d12a000 0000000000000000 (20000041) vma
    59: Error (criu/files-reg.c:2143): Can't open file dev/shm/PostgreSQL.2016670368 on restore: No such file or directory
    59: Error (criu/files-reg.c:2086): Can't open file dev/shm/PostgreSQL.2016670368: No such file or directory
    61: Opening 0x007f5b8d13b000-0x007f5b8d142000 0000000000000000 (81) vma
    59: Error (criu/mem.c:1349): `- Can't open vma
    61: Error (criu/files-reg.c:2143): Can't open file dev/shm/PostgreSQL.2016670368 on restore: No such file or directory
    61: Error (criu/files-reg.c:2086): Can't open file dev/shm/PostgreSQL.2016670368: No such file or directory
    61: Error (criu/mem.c:1349): `- Can't open vma
mnt: Switching to new ns to clean ghosts
Error (criu/cr-restore.c:2470): Restoring FAILED. 
```
[restore.log](https://github.com/containers/podman/files/7526782/restore.log.txt)

**Describe the results you expected:**
Successful container restore

**Output of `podman version`:**

```
sudo podman version 
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.17.3
Git Commit:   92da8682b3977a6ef57a6f73dde2f2aef6186d19
Built:        Fri Nov 12 09:47:37 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /usr/local/libexec/podman/conmon
    version: 'conmon version 2.0.28-dev, commit: 551605f2f3dfe8e1c812568cd667a6190addc18d'
  cpus: 8
  distribution:
    distribution: fedora
    variant: workstation
    version: "34"
  eventLogger: journald
  hostname: NTIzYjQ2
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.16-201.fc34.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 4761432064
  memTotal: 16154042368
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun-1.2-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.2
      commit: 4f6c8e0583c679bfee6a899c05ac6b916022561b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 40506228736
  swapTotal: 40802181120
  uptime: 13h 16m 21.58s (Approximately 0.54 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 0
    stopped: 3
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 5
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.0-dev
  Built: 1636710457
  BuiltTime: Fri Nov 12 09:47:37 2021
  GitCommit: 92da8682b3977a6ef57a6f73dde2f2aef6186d19
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 4.0.0-dev
```

**Comment by mheon** [comment]
Can you provide the logfile it mentioned?

**Comment by mheon** [comment]
Ah, nevermind, I see it now.

@adrianreber PTAL

**Comment by mheon** [comment]
For reference, `/dev/shm` is a tmpfs in a the container, so I imagine that's related.

**Comment by adrianreber** [comment]
I already discussed it with @rst0git

> For reference, `/dev/shm` is a tmpfs in a the container, so I imagine that's related.

From what I have seen that is not entirely true. `/dev/shm` is a tmpfs on the outside of the container and bind mounted into the container. A tmpfs in the container would be easy, but a tmpfs outside of the container is not handled by CRIU.

The solution we came up with for exporting checkpoints is basically:
 * During checkpointing, before unmounting the tmpfs we store everything in the tmpfs in the export archive
 * During restore we copy the saved content from the checkpoint archive to the tmpfs before restoring the container

For checkpoints which are not exported we have a similar problem. After checkpointing we unmount the tmpfs and everything from `/dev/shm` is gone. So we also have to copy the content of the tmpfs somewhere before unmounting. We already have a location for the actual checkpoint data, so maybe we just put it next to it.

For both cases the solution is not really difficult and I think @rst0git agreed to implement it, right?

**Comment by mheon** [comment]
I wonder if there's a good reason for us to have this special handling for `/dev/shm` - I'll bring this up at our scrum, but I don't see a specific reason why it needs to be a tmpfs that is subsequently mounted in.

**Comment by adrianreber** [comment]
> I wonder if there's a good reason for us to have this special handling for `/dev/shm` - I'll bring this up at our scrum, but I don't see a specific reason why it needs to be a tmpfs that is subsequently mounted in.

We were also wondering why this is the case. For a pod with a shared IPC namespace it makes sense, but for a standalone container it was not obvious to us.

**Comment by rst0git** [comment]
> For both cases the solution is not really difficult and I think @rst0git agreed to implement it, right?

Yes, I hope to open a PR with a fix soon.

**Comment by rhatdan** [comment]
The /dev/shm is for sharing IPC namespace with another container.  The issue is you never know whether an existing container will be shared.  So we had to mount it to container storage and then bind mount it into the container.

**Comment by rst0git** [comment]
@adrianreber I have a patch for this issue but it requires the changes in https://github.com/checkpoint-restore/criu/pull/1622
