### ISSUE TITLE
Container checkpoint fails with --ipc=host

### ISSUE THREAD

**Issue by rst0git** [containers/podman#12276]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Container checkpoint fails when then the container is running with `--ipc=host`

**Steps to reproduce the issue:**

1. `sudo podman run --ipc=host --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres`

2. `sudo podman container checkpoint some-postgres`

**Describe the results you received:**
Podman error message:
> CRIU checkpointing failed -52.  Please check CRIU logfile /var/lib/containers/storage/overlay-containers/4a405bbbc2e82f05e96f7a958bb552f125dde64544e5e85d7a7a8569a03de502/userdata/dump.log

CRIU error message:
> Error (criu/cr-dump.c:433): Task 39540 with SysVIPC shmem map @7f385035d000 doesn't live in IPC ns
Error (criu/cr-dump.c:1431): Dump mappings (pid: 39540) failed with -1

[dump.log](https://github.com/containers/podman/files/7526701/dump.log.txt)

**Describe the results you expected:**

Successful container checkpoint.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
sudo podman version
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.17.3
Git Commit:   92da8682b3977a6ef57a6f73dde2f2aef6186d19
Built:        Fri Nov 12 09:47:37 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /usr/local/libexec/podman/conmon
    version: 'conmon version 2.0.28-dev, commit: 551605f2f3dfe8e1c812568cd667a6190addc18d'
  cpus: 8
  distribution:
    distribution: fedora
    variant: workstation
    version: "34"
  eventLogger: journald
  hostname: NTIzYjQ2
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.16-201.fc34.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 5043109888
  memTotal: 16154042368
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun-1.2-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.2
      commit: 4f6c8e0583c679bfee6a899c05ac6b916022561b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 40507539456
  swapTotal: 40802181120
  uptime: 13h 4m 11.18s (Approximately 0.54 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 1
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 5
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.0-dev
  Built: 1636710457
  BuiltTime: Fri Nov 12 09:47:37 2021
  GitCommit: 92da8682b3977a6ef57a6f73dde2f2aef6186d19
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 4.0.0-dev
```

**Comment by mheon** [comment]
`Version:      4.0.0-dev`

Where did you get this Podman build? We shouldn't be shipping a 4.0.0-dev anywhere.

Regardless, I recall us fixing this upstream recently - please try v3.4.2

**Comment by rst0git** [comment]
@mheon I build Podman from source.

> Regardless, I recall us fixing this upstream recently - please try v3.4.2

Yes, there is a related PR (https://github.com/containers/podman/pull/12088), but this is a different problem.

It fails because CRIU doesn't currently support this use case:
https://github.com/checkpoint-restore/criu/blob/688149930abd96fd9e1db4ee3b67c727bab4f3d8/criu/cr-dump.c#L433

We discussed this with @adrianreber last week.

**Comment by rhatdan** [comment]
@adrianreber Any movement on this?

**Comment by rst0git** [comment]
@adrianreber This is a different issue. CRIU doesn't support checkpoint/restore of sysvipc mapping in external IPC namespace (https://github.com/checkpoint-restore/criu/commit/75d8b81fd17c43370ce2fb5eacb6cf608b2a7b98).

I will close this issue as it is a problem with CRIU not Podman.
