### ISSUE TITLE
[RFE] new `podman` secret mount format

### ISSUE THREAD

**Issue by mskarbek** [containers/podman#12284]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I would like to be able to choose an additional secret type - `mount-env` (I don't have a good name for it yet ;)).
Current `mount` type dumps secret content into file, `mount-env` should prefix that content with new option  `env` content.
`podman run -d --secret some_secret,type=mount-env,env=PASSWORD ubi8/ubi-init:latest` should in that case produce file `/run/secrets/some_secret` with content:
```
PASSWORD=<some_password>
```

Use case:
I can use that file directly in `systemd` unit file without extra magic or bash: 
```
[Unit]
ConditionFileNotEmpty=/run/secrets/some_secret

[Service]
EnvironmentFile=/run/secrets/some_secret
```

Edit:
Yes, I'm aware that I could simply prefix that content myself directly in `secret create` but that way in some cases I would have to produce a set of secrets - one with and one without prefix for different containers/use cases and complicate deployment. I would like to have that handled programmatically on container creation level.

**Comment by rhatdan** [comment]
@ashley-cui PTAL

**Comment by ashley-cui** [comment]
Hmm, I don't think this is a good idea? Secrets is designed to be used with secrets created from the `podman secret create` command, and not handle data passed in via the --secret flag on runs. This feature seems to break that pattern.

**Comment by rhatdan** [comment]
@vrothberg WDYT?

**Comment by vrothberg** [comment]
Lets assume `run --secret some_secret,type=mount-env,env=PASSWORD` would work and it's being used in a systemd unit.

How it behave on `systemctl restart`?  Would it recreate the secret?  Would it override it?  Would it fail due to the conflict?

I don't have good answers to that and sympathize with what @ashley-cui mentioned.

**Comment by rhatdan** [comment]
Since this idea has somewhat been rejected and we have not heard counter argument, I am going to close.  Will reopen if more ideas arise.
