### ISSUE TITLE
Named podman machines do not start correctly on Mac 

### ISSUE THREAD

**Issue by kittylyst** [containers/podman#12299]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The ability to have multiple named machines on Mac seems broken.

**Steps to reproduce the issue:**

1. podman machine init --cpus 1 cpus1

2. podman machine stop

3. podman machine start cpus1

```
INFO[0000] waiting for clients...                       
INFO[0000] listening tcp://0.0.0.0:7777                 
INFO[0000] new connection from  to /var/folders/gl/ztxgcfnj2b39wdt9dt8lcy4c0000gn/T/podman/qemu_cpus1.sock 
Waiting for VM ...
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
Machine "cpus1" started successfully
```

4. podman ps -a
 
```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: Connection to bastion host (ssh://core@localhost:50837/run/user/1000/podman/podman.sock) failed.: dial tcp [::1]:50837: connect: connection refused
```

**Describe the results you received:**

As above, the machine seems to start, but all podman commands fail.

**Describe the results you expected:**

The named podman machine starts.

**Output of `podman version`:**

```
podman version 3.4.2
```

**Output of `podman info --debug`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: Connection to bastion host (ssh://core@localhost:50837/run/user/1000/podman/podman.sock) failed.: dial tcp [::1]:50837: connect: connection refused
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ brew info podman
podman: stable 3.4.2 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/usr/local/Cellar/podman/3.4.2 (170 files, 40MB) *
  Poured from bottle on 2021-11-15 at 15:41:31
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0
==> Dependencies
Build: go ✘, go-md2man ✘
Required: qemu ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Analytics
install: 12,299 (30 days), 35,800 (90 days), 63,671 (365 days)
install-on-request: 12,307 (30 days), 35,802 (90 days), 63,609 (365 days)
build-error: 0 (30 days)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Intel MacBook Pro, late 2018 model, MacOS 11.6

**Comment by Luap99** [comment]
Podman only has one default connection. If you have more than one VM you have to manage the connection yourself. You can use the `podman system connection` commands for this, `podman system connection ls` lists all connections. To use a connection you just run `podman --connection NAME ...`
