### ISSUE TITLE
Remote client should handle auth and credential helpers

### ISSUE THREAD

**Issue by mbrancato** [containers/podman#12291]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

When using podman on Mac with podman machine (or any other VM), the podman remote client should handle the docker auth process. Currently, podman relies on auth from inside the VM. 

What would be best, both to keep the VM clean and support as many configurations as possible, the podman remote should handle the auth process and pass the auth to the VM. This should also include invoking any credential helpers. Currently, the credential helpers are expected to be on the VM.

While mounting the auth file in the VM is a possibility, with external credential tools, it is not very helpful.

**Steps to reproduce the issue:**

1. podman machine start

2. podman pull gcr.io/my-project/my-app

Any authenticated repository should do.

**Describe the results you received:**

Auth failure to container repo

**Describe the results you expected:**

Would be prompted to authenticate, container would be pulled

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
% podman version
Client:
Version:      3.4.1
API Version:  3.4.1
Go Version:   go1.17.2
Built:        Tue Oct 19 17:14:42 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.2.1
API Version:  3.2.1
Go Version:   go1.16.7
Built:        Wed Dec 31 19:00:00 1969
OS/Arch:      linux/amd64
```

**Comment by rhatdan** [comment]
You are saying that podman login, does not create the auth.json file on the MAC but inside of the VM?

**Comment by mbrancato** [comment]
No, I use an external credential helper. Specifically, I use GCR and their credential helper pattern: https://cloud.google.com/container-registry/docs/advanced-authentication#gcloud-helper

As I understand, the `~/.docker/config.json` is used for auth with podman or can be. Specifying this as the auth file, also fails because podman is looking in the VM. Additionally, this won't work because the helper isn't installed in the VM. 

What I'm getting at is a general auth experience where the remote client handles auth. This allows external apps to configure the repo auth file, or be used as credential helpers.

My `~/.docker/config.json` looks like this:

```json
{
  "credsStore" : "desktop",
  "stackOrchestrator" : "swarm",
  "auths" : {

  },
  "credHelpers" : {
    "us.gcr.io" : "gcloud",
    "asia.gcr.io" : "gcloud",
    "marketplace.gcr.io" : "gcloud",
    "eu.gcr.io" : "gcloud",
    "staging-k8s.gcr.io" : "gcloud",
    "gcr.io" : "gcloud"
  },
  "experimental" : "disabled"
}
```

**Comment by rhatdan** [comment]
@vrothberg @mtrmac PTAL

**Comment by mtrmac** [comment]
AFAIK the client _does_ handle authentication; at least #11636 shows that happening (and failing).

(OTOH note that `credsStore` is not supported; you can use `credential-helpers` in `registries.conf` instead.)

**Comment by mbrancato** [comment]
well, I tried again today and it just worked. I think the issue is I may have been I started out specifying the auth file path.
```
% podman pull gcr.io/foo/bar --authfile=~/.docker/config.json
Error: stat ~/.docker/config.json: no such file or directory
```

I'll close this.
