### ISSUE TITLE
CNI: failed to set bridge addr: "cni-podman1" already has an IP address different from 10.25.31.1/24

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#12306]
New flake in the `podman play kube --ip and --mac-address` test:
```
Running: podman [options] play kube --network playkubeb5eb2d5e61c925934d210328653aff1f81fba00bb3540d75d93b37ad213c6976 --ip 10.25.31.5 --ip 10.25.31.10 --ip 10.25.31.15 --mac-address e8:d8:82:c9:80:40 --mac-address e8:d8:82:c9:80:50 --mac-address e8:d8:82:c9:80:60 /tmp/podman_test367571681/kube.yaml
         Trying to pull quay.io/libpod/alpine:latest...
         Getting image source signatures
         Copying blob sha256:9d16cba9fb961d1aafec9542f2bf7cb64acfc55245f9e4eb5abecd4cdc38d749
         Copying config sha256:961769676411f082461f9ef46626dd7a2d1e2b2a38e6a44364bcbecf51e66dd4
         Writing manifest to image destination
         Storing signatures
         time="2021-11-15T15:28:35-06:00" level=warning msg="Failed to load cached network config: network playkubeb5eb2d5e61c925934d210328653aff1f81fba00bb3540d75d93b37ad213c6976 not found in CNI cache, falling back to loading network playkubeb5eb2d5e61c925934d210328653aff1f81fba00bb3540d75d93b37ad213c6976 from disk"
         time="2021-11-15T15:28:35-06:00" level=warning msg="1 error occurred:\n\t* plugin type=\"bridge\" failed (delete): cni plugin bridge failed: running [/usr/sbin/iptables -t nat -D POSTROUTING -s 10.25.31.5 -j CNI-e133ad17a19547ca967e6423 -m comment --comment name: \"playkubeb5eb2d5e61c925934d210328653aff1f81fba00bb3540d75d93b37ad213c6976\" id: \"3bb89d3c521fb4768b9782a238e866950666860321ac9dfc6c92279540b17df1\" --wait]: exit status 2: iptables v1.8.7 (legacy): Couldn't load target `CNI-e133ad17a19547ca967e6423':No such file or directory\n\nTry `iptables -h' or 'iptables --help' for more information.\n\n\n"
         [error starting container 5b9ac17a02c53738bce60cfee1af6075fb5b24370d69640dccc0394633a70338: a dependency of container 5b9ac17a02c53738bce60cfee1af6075fb5b24370d69640dccc0394633a70338 failed to start: container state improper]
         [error starting container 5b9ac17a02c53738bce60cfee1af6075fb5b24370d69640dccc0394633a70338: a dependency of container 5b9ac17a02c53738bce60cfee1af6075fb5b24370d69640dccc0394633a70338 failed to start: container state improper error starting container 3bb89d3c521fb4768b9782a238e866950666860321ac9dfc6c92279540b17df1: plugin type="bridge" failed (add): cni plugin bridge failed: failed to set bridge addr: "cni-podman1" already has an IP address different from 10.25.31.1/24]
         time="2021-11-15T15:28:36-06:00" level=warning msg="Failed to load cached network config: network playkubeb5eb2d5e61c925934d210328653aff1f81fba00bb3540d75d93b37ad213c6976 not found in CNI cache, falling back to loading network playkubeb5eb2d5e61c925934d210328653aff1f81fba00bb3540d75d93b37ad213c6976 from disk"
         time="2021-11-15T15:28:36-06:00" level=warning msg="1 error occurred:\n\t* plugin type=\"bridge\" failed (delete): cni plugin bridge failed: running [/usr/sbin/iptables -t nat -D POSTROUTING -s 10.25.31.10 -j CNI-d1123490cd181b6efc7c6874 -m comment --comment name: \"playkubeb5eb2d5e61c925934d210328653aff1f81fba00bb3540d75d93b37ad213c6976\" id: \"21e8282cb85495d1183d7495a264d1d8fc6aba26879921888ad81cfee67f0f67\" --wait]: exit status 2: iptables v1.8.7 (legacy): Couldn't load target `CNI-d1123490cd181b6efc7c6874':No such file or directory\n\nTry `iptables -h' or 'iptables --help' for more information.\n\n\n"
         [error starting container 21e8282cb85495d1183d7495a264d1d8fc6aba26879921888ad81cfee67f0f67: plugin type="bridge" failed (add): cni plugin bridge failed: failed to set bridge addr: "cni-podman1" already has an IP address different from 10.25.31.1/24]
         [error starting container 21e8282cb85495d1183d7495a264d1d8fc6aba26879921888ad81cfee67f0f67: plugin type="bridge" failed (add): cni plugin bridge failed: failed to set bridge addr: "cni-podman1" already has an IP address different from 10.25.31.1/24 error starting container 79a8ac450aef5ec3ac7d2211a317ef6e3addd030ad4267754d624e89f2170a49: a dependency of container 79a8ac450aef5ec3ac7d2211a317ef6e3addd030ad4267754d624e89f2170a49 failed to start: container state improper]
         time="2021-11-15T15:28:37-06:00" level=warning msg="Failed to load cached network config: network playkubeb5eb2d5e61c925934d210328653aff1f81fba00bb3540d75d93b37ad213c6976 not found in CNI cache, falling back to loading network playkubeb5eb2d5e61c925934d210328653aff1f81fba00bb3540d75d93b37ad213c6976 from disk"
         time="2021-11-15T15:28:37-06:00" level=warning msg="1 error occurred:\n\t* plugin type=\"bridge\" failed (delete): cni plugin bridge failed: running [/usr/sbin/iptables -t nat -D POSTROUTING -s 10.25.31.15 -j CNI-ca8be397b550d04a57dbeaed -m comment --comment name: \"playkubeb5eb2d5e61c925934d210328653aff1f81fba00bb3540d75d93b37ad213c6976\" id: \"58241d142fc04c3afd97f8821c0069b36fdabfda679c1833d9286682c2dce005\" --wait]: exit status 2: iptables v1.8.7 (legacy): Couldn't load target `CNI-ca8be397b550d04a57dbeaed':No such file or directory\n\nTry `iptables -h' or 'iptables --help' for more information.\n\n\n"
         error starting container 5b9ac17a02c53738bce60cfee1af6075fb5b24370d69640dccc0394633a70338: a dependency of container 5b9ac17a02c53738bce60cfee1af6075fb5b24370d69640dccc0394633a70338 failed to start: container state improper
         error starting container 3bb89d3c521fb4768b9782a238e866950666860321ac9dfc6c92279540b17df1: plugin type="bridge" failed (add): cni plugin bridge failed: failed to set bridge addr: "cni-podman1" already has an IP address different from 10.25.31.1/24
         error starting container 21e8282cb85495d1183d7495a264d1d8fc6aba26879921888ad81cfee67f0f67: plugin type="bridge" failed (add): cni plugin bridge failed: failed to set bridge addr: "cni-podman1" already has an IP address different from 10.25.31.1/24
         error starting container 79a8ac450aef5ec3ac7d2211a317ef6e3addd030ad4267754d624e89f2170a49: a dependency of container 79a8ac450aef5ec3ac7d2211a317ef6e3addd030ad4267754d624e89f2170a49 failed to start: container state improper
         error starting container 58241d142fc04c3afd97f8821c0069b36fdabfda679c1833d9286682c2dce005: plugin type="bridge" failed (add): cni plugin bridge failed: failed to set bridge addr: "cni-podman1" already has an IP address different from 10.25.31.1/24
         error starting container 4d6d4db71f989a31583843f33c999aa66a5c6f365e8a44366810e38005d0b870: a dependency of container 4d6d4db71f989a31583843f33c999aa66a5c6f365e8a44366810e38005d0b870 failed to start: container state improper
         Error: failed to start 6 containers
```
### Podman play kube [It] podman play kube --ip and --mac-address
* fedora-34 : int podman fedora-34 rootless host
  * PR #12272
    * [11-12 14:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5446866918703104/html/int-podman-fedora-34-rootless-host.log.html#t--podman-play-kube---ip-and---mac-address--1)
    * [11-12 14:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5446866918703104/html/int-podman-fedora-34-rootless-host.log.html#t--podman-play-kube---ip-and---mac-address--2)
    * [11-12 14:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5446866918703104/html/int-podman-fedora-34-rootless-host.log.html#t--podman-play-kube---ip-and---mac-address--3)
* ubuntu-2104 : int podman ubuntu-2104 rootless host
  * PR #12066
    * [10-22 22:11](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6372436632403968/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-play-kube---ip-and---mac-address--1)
    * [10-22 22:11](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6372436632403968/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-play-kube---ip-and---mac-address--2)
    * [10-22 22:11](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6372436632403968/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-play-kube---ip-and---mac-address--3)

Also seen just now in a live PR, in [f34 rootless](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4910111501058048/html/int-podman-fedora-34-rootless-host.log.html#t--podman-play-kube---ip-and---mac-address--1)

**Comment by Luap99** [comment]
I renamed the issue to display the correct issue `cni plugin bridge failed: failed to set bridge addr: "cni-podman1" already has an IP address different from 10.25.31.1/24]`. The other errors are expected because we try to teardown the cni network so that we do not leak any iptables rules.

**Comment by Luap99** [comment]
OK I took a look at the logs. I think the actual issue is `Unable to cleanup network for container 4c3c259fac1ae12b5ff6c89982d38114b0ad5b2b14065bc1f02513fd4348c01d: \"error getting rootless network namespace: failed to Statfs \\\"/run/user/13236/netns/rootless-netns\\\": no such file or directory\""`

@edsantiago  Can you grep for `error getting rootless network namespace`?

**Comment by edsantiago** [comment]
Here are some. They seem to begin on 11-09.

### Podman network connect and disconnect [It] podman network disconnect and run with network ID
* fedora-33 : int podman fedora-33 rootless host
  * PR #12227
    * [11-09 10:46](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6097254554533888/html/int-podman-fedora-33-rootless-host.log.html#t--podman-network-disconnect-and-run-with-network-ID--1)
* fedora-34 : int podman fedora-34 rootless host
  * PR #12235
    * [11-09 04:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6272633235832832/html/int-podman-fedora-34-rootless-host.log.html#t--podman-network-disconnect-and-run-with-network-ID--1)
  * PR #12100
    * [11-15 16:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4910111501058048/html/int-podman-fedora-34-rootless-host.log.html#t--podman-network-disconnect-and-run-with-network-ID--1)
* ubuntu-2104 : int podman ubuntu-2104 rootless host
  * PR #12250
    * [11-10 07:50](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6075431590821888/html/int-podman-ubuntu-2104-rootless-host.log.html#t--podman-network-disconnect-and-run-with-network-ID--1)

* ubuntu-2110 : int podman ubuntu-2110 rootless host
  * PR #11957
    * [11-16 08:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6579341078298624/html/int-podman-ubuntu-2110-rootless-host.log.html#t--podman-network-disconnect-and-run-with-network-ID--1)

**Comment by Luap99** [comment]
https://github.com/containers/podman/pull/12183 caused this, I know how to fix it. I will open a PR later this week.
