### ISSUE TITLE
podman machine do not use a `tab` but instead `spaces` to list the VM machines

### ISSUE THREAD

**Issue by cmoulliard** [containers/podman#12313]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

The format used to stdout the list of the podman machine do not use a `tab` but instead `spaces`.
The list of the machines displayed should respect the format defined and documented and add a tab between the columns result
```
podman machine list --format "{{.Name}}\t{{.VMType}}\t{{.Created}}\t{{.LastUp}}\t{{.CPUs}}\t{{.Memory}}\t{{.DiskSize}}" | awk -F '\t' '{ print $2 }'

podman machine list --format "{{.Name}}\t{{.VMType}}\t{{.Created}}\t{{.LastUp}}\t{{.CPUs}}\t{{.Memory}}\t{{.DiskSize}}" | awk -F '\t' '{ print $1 }'
macvm*      qemu        2 hours ago  About an hour ago  1           2.147GB     10.74GB

OR

podman machine list | head -n 2 | awk -F '\t' '{ print $2 }'


podman machine list | head -n 2 | awk -F '\t' '{ print $1 }'
NAME        VM TYPE     CREATED      LAST UP            CPUS        MEMORY      DISK SIZE
macvm*      qemu        2 hours ago  About an hour ago  1           2.147GB     10.74GB
```

**Additional information**

podman version: 3.4.2
OS: MacOS

**Comment by rhatdan** [comment]
Interested in opening a PR to fix?
@jwhonce have you been looking into similar fixes?

**Comment by cmoulliard** [comment]
As a Report Template test case validates that the template populated include `\t`, then I suspect that the issue occurs when the result is stdout on macos 

Test case tested
```
package test

import (
	"bytes"
	report "github.com/containers/common/pkg/report"
	"github.com/stretchr/testify/assert"
	"testing"
)

type machineReporter struct {
	Name     string
	Default  bool
	Created  string
	Running  bool
	LastUp   string
	VMType   string
	CPUs     uint64
	Memory   string
	DiskSize string
}

func TestTemplate_Parse(t *testing.T) {
	headers := report.Headers(machineReporter{}, map[string]string{
		"LastUp":   "LAST UP",
		"VmType":   "VM TYPE",
		"CPUs":     "CPUS",
		"Memory":   "MEMORY",
		"DiskSize": "DISK SIZE",
	})

	listFormat := "{{.Name}}\t{{.VMType}}\t{{.Created}}\t{{.LastUp}}\t{{.CPUs}}\t{{.Memory}}\t{{.DiskSize}}\n"
	row := report.NormalizeFormat(listFormat)
	format := report.EnforceRange(row)

	var buf bytes.Buffer
	tmpl, e := report.NewTemplate("TestTemplate").Parse(format)
	assert.NoError(t, e)

	// Check the headers content
	err := tmpl.Execute(&buf, headers)
	assert.NoError(t, err)
	assert.Equal(t, "NAME\tVM TYPE\tCREATED\tLAST UP\tCPUS\tMEMORY\tDISK SIZE\n", buf.String())
	buf.Reset()

	// Check the machineReport
	machineReporter:= genMachineReporter()
	err = tmpl.Execute(&buf, machineReporter)
	assert.NoError(t, err)
	assert.Equal(t, "macvm*\tqemu\t6 hours ago\t5 hours ago\t1\t2.147GB\t10.74GB\n", buf.String())
}

func genMachineReporter() ([]*machineReporter) {
	vms := make([]*machineReporter,0)
	vm := new(machineReporter)
	vm.Default = false
	vm.Running = false
	vm.Name = "macvm*"
	vm.LastUp = "5 hours ago"
	vm.Created = "6 hours ago"
	vm.VMType = "qemu"
	vm.CPUs = 1
	vm.Memory = "2.147GB"
	vm.DiskSize = "10.74GB"
	vms = append(vms, vm)
	return vms
}
```

**Comment by cmoulliard** [comment]
The error occurs when we use the `Report Tab Writer` --> see:
```
	// Use now a Tabwriter
	w := tabwriter.NewWriter(&buf, 12, 2, 2, ' ', 0)
	err = tmpl.Execute(w, machineReporter)
	assert.NoError(t, err)
	w.Flush()
	res := buf.String()
	assert.Equal(t, "macvm*\tqemu\t6 hours ago\t5 hours ago\t1\t2.147GB\t10.74GB\n", res)

--->
Error:      	Not equal: 
        	expected: "macvm*\tqemu\t6 hours ago\t5 hours ago\t1\t2.147GB\t10.74GB\n"
        	 actual  : "macvm*      qemu        6 hours ago  5 hours ago  1           2.147GB     10.74GB\n"
```

**Comment by rhatdan** [comment]
@jwhonce Any progress?

**Comment by ashley-cui** [comment]
Not fixed, but also not sure if this is a bug. The suggested fix breaks the formatting completely:
> from
> 
> ```
> NewWriter(output, 12, 2, 2, ' ', 0) 
> ```
> 
> to
> 
> ```
> NewWriter(output, 0, 5, 0, '\t', 0)
> ```
> 
![Screenshot from 2022-07-21 16-33-40](https://user-images.githubusercontent.com/32910034/180310455-dd76c8f2-1b4a-4a89-ad20-902df217e875.png)

I'm not sure if we should honor the `\t`, as Docker also renders it as spaces. 

@rhatdan @jwhonce WDYT?

**Comment by rhatdan** [comment]
I think the request was for if the user specifies \t in their formatter, then we should use a <tab> rather then <spaces>

**Comment by rhatdan** [comment]
@ashley-cui any progress?

**Comment by ashley-cui** [comment]
Not at the moment

**Comment by SamirPS** [comment]
Hello, can I try this one? And can you guide me to find the code in the source code?

**Comment by rhatdan** [comment]
@SamirPS Sure.

The code is right here.
https://github.com/containers/podman/blob/main/cmd/podman/machine/list.go

**Comment by SamirPS** [comment]
> @SamirPS Sure.
> 
> The code is right here. https://github.com/containers/podman/blob/main/cmd/podman/machine/list.go

Do you know what function?

**Comment by Regis-Caelum** [comment]
Hey I would like to work on this one
How do I test the changes

**Comment by rhatdan** [comment]
You got it. Not sure the best way to test this.

**Comment by Luap99** [comment]
I don't think we should change the formatting, this is not specific to the machine ls commands, all commands that output formatted data work that way. 

On current main your first example seems to work fine when the format is specified by the user:
```
$ bin/podman machine list --format "{{.Name}}\t{{.VMType}}\t{{.Created}}\t{{.LastUp}}\t{{.CPUs}}\t{{.Memory}}\t{{.DiskSize}}" | awk -F '\t' '{ print $1,$5 }'
podman-machine-default* 1
```

**Comment by vrothberg** [comment]
OK, let's close it.  I prefer consistency and Paul mentioned a workaround above.
