### ISSUE TITLE
Error: cannot re-exec process

### ISSUE THREAD

**Issue by statiksof** [containers/podman#12312]
I can't execute any podman command (as a user) after an upgrade of the virtual machine.

I see in logs that these packages have been updated:

* container-selinux.noarch
* containernetworking-plugins.x86_64
* containers-common.noarch

among others.

Any idea?

**Comment by rhatdan** [comment]
As root, do setenforce 0, and see if it works, if yes then it is SELinux, and most likely you have a labeling issue.  You also could try to reinstall container-selinux package, I have heard about some failures on install.

**Comment by statiksof** [comment]
@rhatdan @Luap99 I am not sure if is related to SELinux but I found out that after the upgrade the user has multiple (additional) entries for `/etc/subuid` and `/etc/subgid`. I removed them and now it works aagain. I don't know if podman set up them automatically after the update.

**Comment by flouthoc** [comment]
Could you share additional entries which you removed  to make it work.

I am closing this since issue is resolved for user but we still need to investigate about what did you remove to make it work and if it could re-appear.

**Comment by statiksof** [comment]
Before the update:

```
cat /etc/subuid
user1:100000:65536
user2:200000:1001
```
 after the update:
 
```
cat /etc/subuid
user1:100000:65536
user2:200000:1001
user1:200000:1001
``` 
I removed the 3 line to make work again.

**Comment by rhatdan** [comment]
Was the user user1?

**Comment by statiksof** [comment]
yes

**Comment by rhatdan** [comment]
So removing user1:200000:1001 made it work.

**Comment by rhatdan** [comment]
I add that to my account and I don't see any issue.  Might be a red herring.
