### ISSUE TITLE
Moby client behavior rely on Moby API, and is not compatible with podman short name handling

### ISSUE THREAD

**Issue by mscherer** [containers/podman#12320]
According to https://github.com/moby/moby/blob/master/client/image_pull.go#L22-L29 , "docker.io" suffix is stripped when a program call client.ImagePull (since that's the "familiar name")

For example, trying to client.ImagePull(_, "docker.io/a6543/test_git_plugin", _ ) will result in a API call of 
```
POST /v1.33/images/create?fromImage=a6543%2Ftest_git_plugin&tag=latest
```

This is not compatible with the short-name feature of podman (https://www.redhat.com/sysadmin/container-image-short-names), since this result in podman returning this error in the API (tested with the HEAD version, see #12315 for the whole story):
```
Error response from daemon: failed to resolve image name: short-name resolution enforced but cannot prompt without a TTY
```

Should the compat API  mirror moby client expectation, eg, defaulting to docker.io ?

**Comment by petersenna** [comment]
@vrothberg I am not sure I ran into a corner case, so I do not really know if the behavior I describe is a bug or not. For *reasons* I pull container images from a private registry at VM image creation time, and then after VMs are deployed I create containers over the Podman's Docker-compatible REST API.

The issue I am having is that starting with podman 4 trying to start a container that was previously pulled fails because the container does not exist at Docker Hub. More precisely I get a 404 for `docker.io/library/NAME:TAG`

Here is an example. Please note that I replaced real strings with words in capital letters, like NAME, and TAG.

```
# podman --version
podman version 4.0.2

# podman --log-level=debug system service -t 0 tcp:0.0.0.0:2376
...
DEBU[0017] Looking up image "NAME:TAG" in local containers storage
DEBU[0017] Normalized platform linux/amd64 to {amd64 linux  [] }
DEBU[0017] Trying "NAME:TAG" ...
DEBU[0017] Looking up image "NAME:TAG" in local containers storage
DEBU[0017] Normalized platform linux/amd64 to {amd64 linux  [] }
DEBU[0017] Trying "NAME:TAG" ...
DEBU[0017] Loading registries configuration "/etc/containers/registries.conf"
DEBU[0017] Loading registries configuration "/etc/containers/registries.conf.d/000-shortnames.conf"
DEBU[0017] Loading registries configuration "/etc/containers/registries.conf.d/001-rhel-shortnames.conf"
DEBU[0017] Loading registries configuration "/etc/containers/registries.conf.d/002-rhel-shortnames-overrides.conf"
DEBU[0017] Trying "localhost/NAME:TAG" ...
DEBU[0017] Trying "registry.fedoraproject.org/NAME:TAG" ...
DEBU[0017] Trying "registry.access.redhat.com/NAME:TAG" ...
DEBU[0017] Trying "registry.centos.org/NAME:TAG" ...
DEBU[0017] Trying "docker.io/library/NAME:TAG" ...
DEBU[0017] Trying "localhost/NAME:TAG" ...
DEBU[0017] Trying "docker.io/library/NAME:TAG" ...
DEBU[0017] Trying "registry.fedoraproject.org/NAME:TAG" ...
DEBU[0017] Trying "registry.access.redhat.com/NAME:TAG" ...
DEBU[0017] Trying "registry.centos.org/NAME:TAG" ...
DEBU[0017] Trying "docker.io/library/NAME:TAG" ...
DEBU[0017] Trying "docker.io/library/NAME:TAG" ...
DEBU[0017] Trying "REGISTRY/PATH/NAME:TAG" ...
DEBU[0017] Trying "REGISTRY/PATH/NAME:TAG" ...
DEBU[0017] parsed reference into "[overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev,metacopy=on]@5fb70826285b943f31f0c4b0dc0247d29177941c6e01a99b188bdda633244892"
DEBU[0017] Found image "NAME:TAG" as "REGISTRY/PATH/NAME:TAG" in local containers storage
DEBU[0017] parsed reference into "[overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev,metacopy=on]@5fb70826285b943f31f0c4b0dc0247d29177941c6e01a99b188bdda633244892"
DEBU[0017] Found image "NAME:TAG" as "REGISTRY/PATH/NAME:TAG" in local containers storage
DEBU[0017] Found image "NAME:TAG" as "REGISTRY/PATH/NAME:TAG" in local containers storage ([overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev,metacopy=on]@5fb70826285b943f31f0c4b0dc0247d29177941c6e01a99b188bdda633244892)
DEBU[0017] Looking up image "docker.io/library/NAME:TAG" in local containers storage
DEBU[0017] Normalized platform linux/amd64 to {amd64 linux  [] }
DEBU[0017] Trying "docker.io/library/NAME:TAG" ...
DEBU[0017] Trying "docker.io/library/NAME:TAG" ...
DEBU[0017] Found image "NAME:TAG" as "REGISTRY/PATH/NAME:TAG" in local containers storage ([overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev,metacopy=on]@5fb70826285b943f31f0c4b0dc0247d29177941c6e01a99b188bdda633244892)
DEBU[0017] Looking up image "docker.io/library/NAME:TAG" in local containers storage
DEBU[0017] Normalized platform linux/amd64 to {amd64 linux  [] }
DEBU[0017] Trying "docker.io/library/NAME:TAG" ...
DEBU[0017] Trying "docker.io/library/NAME:TAG" ...
DEBU[0017] Trying "docker.io/library/NAME:TAG" ...
INFO[0017] Request Failed(Not Found): No such image: docker.io/library/NAME:TAG: image not known
DEBU[0017] Trying "docker.io/library/NAME:TAG" ...
INFO[0017] Request Failed(Not Found): No such image: docker.io/library/NAME:TAG: image not known
```

Then if I set `compat_api_enforce_docker_hub` to `false`, podman works as I would expect and will be happy with containers found in local containers storage.

Is this a bug?

**Comment by vrothberg** [comment]
Thanks for the ping, @petersenna. It definitely sounds suspicious when Docker works but Podman does not on the compat API and by definition qualifies as a bug.

Judging from the logs, Podman is able to resolve the image locally when looking for "NAME:TAG":

> DEBU[0017] Looking up image "NAME:TAG" in local containers storage
[...]
> DEBU[0017] Found image "NAME:TAG" as "REGISTRY/PATH/NAME:TAG [...]

For some reasons, Podman is then looking up the normalized version which fails:
> DEBU[0017] Looking up image "docker.io/library/NAME:TAG" in local containers storage
[...]
> INFO[0017] Request Failed(Not Found): No such image: docker.io/library/NAME:TAG: image not known

Would you mind opening a new issue for it?  It would be extremely useful to see the exact API request to isolate the bug.

**Comment by petersenna** [comment]
Created a new issue: https://github.com/containers/podman/issues/14291
