### ISSUE TITLE
cannot start containers after reboot (defaultCNINetExists check -> error configuring network namespace for container)

### ISSUE THREAD

**Issue by martinetd** [containers/podman#12336]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Containers do not start anymore after rebooting (as root, on alpine, if that matters -- I assume something this big works on "normal" setups so I must be missing something obvious?)

**Steps to reproduce the issue:**

1. start containers

2. reboot without shutting it down (doesn't seem cleaned up on stop anyway)

3. try to start containers again

**Describe the results you received:**

immediately after rebooting:
```
armadillo:~# podman run -ti alpine
ERRO[0000] error loading cached network config: network "podman" not found in CNI cache 
WARN[0000] falling back to loading from existing plugins on disk                        
ERRO[0000] Error tearing down partially created network namespace for container 1bc242bba6ec8eeb1593f1f4d370dd474e5144e7f65dd7ab068c6e2e67be4a59: CNI network "podman" not found 
Error: error configuring network namespace for container 1bc242bba6ec8eeb1593f1f4d370dd474e5144e7f65dd7ab068c6e2e67be4a59: CNI network "podman" not found
armadillo:~# rm /var/lib/containers/storage/libpod/defaultCNINetExists 
armadillo:~# podman run -ti alpine
/ # 
```

**Describe the results you expected:**

default CNI should be recreated properly on failures even if the file exists.
Alternatively, moving the file to /run/libpod instead of storage's libpod dir would make more sense and clean things up automatically nicely.

**Output of `podman version`:**

```
armadillo:~# podman version
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.17.3
Git Commit:   d800e4f57e9388a4cd4e5d9321b4594f552bc5d7
Built:        Sun Nov 14 04:26:13 2021
OS/Arch:      linux/arm64
```

**Output of `podman info --debug`:**

(note this was with my config, but I also tried removing /etc/containers/storage.conf and /etc/containers/containers.conf to no avail in case these got updated)

```
armadillo:~# podman info --debug
host:
  arch: arm64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: 4ab06de98f48513b22602d23d59d63b29e75824b'
  cpus: 4
  distribution:
    distribution: alpine
    version: 3.15.0_rc3
  eventLogger: file
  hostname: armadillo
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.52-00112-gec168b956610-dirty
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 1268080640
  memTotal: 1741979648
  ociRuntime:
    name: crun
    package: Unknown
    path: /usr/bin/crun
    version: |-
      crun version 1.3
      commit: 4f6c8e0583c679bfee6a899c05ac6b916022561b
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 0
  swapTotal: 0
  uptime: 1m 43.97s
plugins:
  log:
  - k8s-file
  - none
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 0
    stopped: 4
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /var/lib/containers/storage_readonly
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 3
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 1636831573
  BuiltTime: Sun Nov 14 04:26:13 2021
  GitCommit: d800e4f57e9388a4cd4e5d9321b4594f552bc5d7
  GoVersion: go1.17.3
  OsArch: linux/arm64
  Version: 3.4.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

``` 
armadillo:~# apk info podman
podman-3.4.2-r0 description:
Simple management tool for pods, containers and images

podman-3.4.2-r0 webpage:
https://podman.io/

podman-3.4.2-r0 installed size:
43 MiB
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Not tested latest version, nothing about this in troubleshooting guide

**Additional environment details (AWS, VirtualBox, physical, etc.):**

run on embedded system as root, but I believe environment has little to do here. alpine might if that is expected to be cleaned up otherwise?

**Comment by Luap99** [comment]
Is your `/etc/cni/net.d/` directory on a tmpfs?
Once the default network is created it should stay there, why would you need it to be recreated every single time?

Note that podman4.0 will store the default network in memory so this should be fixed then.

**Comment by martinetd** [comment]
Ah, I didn't know there was extra configuration generated there, that explains it.

Yes, it is indeed a tmpfs. It's normally not a problem as the podman /var/lib/storage/container is normally also a tmpfs, but I was testing a persistent mode for it when I ran into this...

It looks like a one-time thing so I can just run podman once and keep this content at install time. If it's kept in memory in podman4.0 I'll be able to drop this clutch then, so it's even better.
Thanks!

I'll keep this ticket open if you want to backport a workaround (it probably shouldn't fail this blatantly), but happy if you close it instead you provided me the info I was missing.

**Comment by Luap99** [comment]
We cannot backport this, this feature is part of a very big network rewrite.

**Comment by martinetd** [comment]
@Luap99 Forgive me for continuing on this, I have a few extra questions about how that `/etc/cni/net.d/87-podman.conflist` file is generated (it looks like I can't reopen the issue, hopefully you'll see this anyway)

(to reply first, I shouldn't have used 'backport' -- I didn't mean to use the change as it is, just another fix that would avoid the issue, but I agree my setup is rare enough and probably shouldn't be a problem for most users)

Running podman on a laptop where IP is subject to change depending on dhcp however should be a supported case, and I don't see why some weird hotel wifi wouldn't be using 10.88.0.0/16 _somewhere_, so I wanted to check what happens if I use these IPs for something other than podman (our users are expected to run containers in environments we don't control)

With the current "generate once and store to disk" behaviour, I guess there's no much hope it wouldn't change the IP, but even if I clean everything, if 10.88.0.1 is e.g. used as my gateway before starting podman, podman setting up cni with this address will mess everything up.
I've tried making sure I cleaned up everything before my attempt but maybe I missed something?
Looking at libpod/runtime.go I see the network created as `defaultnet.Create(... runtime.config.Network.DefaultSubnet...)` so it looks pretty static, does one need to explicitely modify that file or use `podman network create --subnet xx` commands in this case?
(this also doesn't seem to have changed with the main branch of podman)

I guess "fix by documentation" is not out of question for users whose internet connection relies on this range of IP, but I wanted to make sure I'm not missing something first -- If there's a way for podman to detect the subnet is used on first run it'd be awesome.

```
(cleanup, but I also tried rebooting effectively wiping all of /var and /etc back to their install state)
armadillo:~# ip link del cni-podman0
armadillo:~# rm -rf /etc/cni/net.d/87-podman.conflist /var/lib/cni/networks/podman/ /var/lib/containers/storage/libpod/defaultCNINetExists /var/lib/containers/storage/libpod/bolt_state.db


(base config)
armadillo:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:11:0c:00:0a:f7 brd ff:ff:ff:ff:ff:ff
    inet 10.88.0.2/16 scope global eth0
       valid_lft forever preferred_lft forever
3: eth1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN qlen 1000
    link/ether 00:11:0c:00:0a:f8 brd ff:ff:ff:ff:ff:ff
4: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN qlen 1000
    link/ether 44:c3:06:20:58:44 brd ff:ff:ff:ff:ff:ff
armadillo:~# ip r
default via 10.88.0.1 dev eth0
10.88.0.0/16 dev eth0 scope link  src 10.88.0.2
armadillo:~# ping -c 1 google.com
PING google.com (142.250.196.142): 56 data bytes
64 bytes from 142.250.196.142: seq=0 ttl=110 time=17.759 ms

--- google.com ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 17.759/17.759/17.759 ms


(running container: it picks 10.88.0.0 again unfortunately)
armadillo:~# podman run --rm alpine sh -c 'ip a; ping -c 1 google.com'
[ 1111.381684] IPv6: ADDRCONF(NETDEV_CHANGE): veth5516740f: link becomes ready
[ 1111.388777] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[ 1111.395338] cni-podman0: port 1(veth5516740f) entered blocking state
[ 1111.401707] cni-podman0: port 1(veth5516740f) entered disabled state
[ 1111.408239] device veth5516740f entered promiscuous mode
[ 1111.413651] cni-podman0: port 1(veth5516740f) entered blocking state
[ 1111.420011] cni-podman0: port 1(veth5516740f) entered forwarding state
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0@if29: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether aa:ef:57:d3:e3:3a brd ff:ff:ff:ff:ff:ff
    inet 10.88.0.2/16 brd 10.88.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::a8ef:57ff:fed3:e33a/64 scope link tentative
       valid_lft forever preferred_lft forever
ping: bad address 'google.com'
[ 1116.827162] cni-podman0: port 1(veth5516740f) entered disabled state
[ 1116.834110] device veth5516740f left promiscuous mode
[ 1116.839221] cni-podman0: port 1(veth5516740f) entered disabled state


(outside of container also broken as long as podman interface exists and hijacks the router ip)
armadillo:~# ping -c 1 google.com
ping: bad address 'google.com'
armadillo:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:11:0c:00:0a:f7 brd ff:ff:ff:ff:ff:ff
    inet 10.88.0.2/16 scope global eth0
       valid_lft forever preferred_lft forever
3: eth1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN qlen 1000
    link/ether 00:11:0c:00:0a:f8 brd ff:ff:ff:ff:ff:ff
4: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN qlen 1000
    link/ether 44:c3:06:20:58:44 brd ff:ff:ff:ff:ff:ff
28: cni-podman0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN qlen 1000
    link/ether a6:4c:8e:97:49:51 brd ff:ff:ff:ff:ff:ff
    inet 10.88.0.1/16 brd 10.88.255.255 scope global cni-podman0
       valid_lft forever preferred_lft forever
    inet6 fe80::a44c:8eff:fe97:4951/64 scope link
       valid_lft forever preferred_lft forever


(conf file)
armadillo:~# cat /etc/cni/net.d/87-podman.conflist
{
  "cniVersion": "0.4.0",
  "name": "podman",
  "plugins": [
    {
      "type": "bridge",
      "bridge": "cni-podman0",
      "isGateway": true,
      "ipMasq": true,
      "hairpinMode": true,
      "ipam": {
        "type": "host-local",
        "routes": [{ "dst": "0.0.0.0/0" }],
        "ranges": [
          [
            {
              "subnet": "10.88.0.0/16",
              "gateway": "10.88.0.1"
            }
          ]
        ]
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      }
    },
    {
      "type": "firewall"
    },
    {
      "type": "tuning"
    }
  ]
}
```

**Comment by Luap99** [comment]
There is no check if the subnet is already used. You can change the default subnet in containers.conf. That however only works before the file is generated. Once the file is generated it is not changed by podman in any way.

If you need to make some adjustments to config you can copy this one into the dirctory https://github.com/containers/podman/blob/main/cni/87-podman-bridge.conflist and change it to your needs. Podman will only generated the file if the default network file does not exists (It uses the name from the config not the file name!).

There is also no way to fix this in 3.X. It is simply not possible with the current codebase.

**Comment by martinetd** [comment]
Thanks for the details! I'll just document a workaround for our users in case someone stumbles upon this.
