### ISSUE TITLE
podman-remote checkpoint/restore tests: failing

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#12334]
Tests [failing](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5825307493007360/html/int-remote-fedora-34-root-host.log.html). Almost certainly related to #12281. Failure seems to be here https://github.com/containers/podman/blob/f5e509ce098074cbb4c468b9d443f46e6c7770ed/test/e2e/checkpoint_test.go#L917

**Comment by edsantiago** [comment]
@containers/podman-maintainers looks like I missed @vrothberg, and he's OOTO tomorrow. Can anyone look into this please? It is blocking #11795.

**Comment by vrothberg** [comment]
I will have a look but I guess that something else must have merged after https://github.com/containers/podman/pull/12281 and broken it. https://github.com/containers/podman/pull/12281 was clearly green (and passed locally).

**Comment by vrothberg** [comment]
Correction: I suspect that the tests are now executed with runc, and those break.  I can reproduce locally.  I still have 40 minutes until the course and will hurry to pull something together.

**Comment by vrothberg** [comment]
Here's a PR: https://github.com/containers/podman/pull/12342
