### ISSUE TITLE
RFE: way to detect/kill in-flight pulls

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#12355]
The scenario: in window 1:
```console
$ podman run registry.fedoraproject.org/fedora-minimal:latest true       <---- image must not be local
Trying to pull registry.fedoraproject.org/fedora-minimal:latest...
...
```
Window 2:
```console
$ podman rm -f -a       <--- does nothing, because image is still pulling
```
This of course makes perfect sense: there are no containers. However, this matters because of `e2e` tests, and in particular `Cleanup`: https://github.com/containers/podman/blob/0376e6092c850435b4740876045fdccb467cafd8/test/e2e/common_test.go#L480-L490

What happens is, one test runs `podman run --name foo ...`, but that times out while still pulling, and `Cleanup()` doesn't see the container. On the next ginkgo retry, the image has pulled, the container has started, and `podman run --name foo` fails with the expected "name already in use" error.

I have no suggestions on how to detect this. Am filing just to get it on the map.

**Comment by vrothberg** [comment]
There is no reliable way to detect in-flight pulls (and map that to a process).

Probably the tests should use random names or use the `--replace` flag.  It's an interesting issue.  I also wonder why ginkgo doesn't kill the process when the timeout kicks in.  Is that the case?

**Comment by edsantiago** [comment]
There's no timeout that I know of. Basically, the container gets started in the background, but nothing knows about it. Using random names is a good practice in general but, ironically, if that had been in use I might not have found the actual bug.

If there's no way to detect active pulls, and no interest in doing so, feel free to close.

**Comment by vrothberg** [comment]
I think a `ps | grep | sed  | kill` may be easier.

**Comment by Luap99** [comment]
Why does a test reuse the existing storage, I thought each test will use a separate storage so a new run should not cause naming conflicts.
