### ISSUE TITLE
Podman stoped working properly after update on centos 8

### ISSUE THREAD

**Issue by ImanGharib** [containers/podman#12358]
Running podman as rootles leas to shell time out after waiting for almost 10 minutes. It happens by some commands like 
`podman ps` . But `sudo podman ps` works.

**Comment by rhatdan** [comment]
Have you checked if you are having SELinux issues? 
If not what does
$ podman unshare cat /proc/self/uid_map

Show?

**Comment by ImanGharib** [comment]
It shows:
         0       1000          1
         1     100000      65536

**Comment by ImanGharib** [comment]
And this is `sestatus`
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33

**Comment by ImanGharib** [comment]
And all of the sudden I get `podman ps
ERRO[0000] XDG_RUNTIME_DIR directory "/run/user/1000" is not owned by the current user `
today!!

**Comment by rhatdan** [comment]
Which looks like you have a configuration issue.
