### ISSUE TITLE
Add end-to-end support for config map-based env variables in play kube

### ISSUE THREAD

**Issue by jakub-dzon** [containers/podman#12363]
**Is this a BUG REPORT or FEATURE REQUEST?**

/kind feature

**Description**
This is a follow-up for #12243: `configmaps` query parameter for /v4.0.0/libpod/play/kube is not forwared to the `ContainerEngine.PlayKube` with `PlayKubeOptions` and as a result config maps are not supported in remote `play kube` execution.

As discussed during [the last Podman Community Cabal](https://podman.io/community/meeting/notes/2021-11-18/#forwarding-play-kube-http-api---2445-in-video) the end-to-end solution for the problem described above would be sending `ConfigMap`  YAML as part of the payload of the `/play/kube` request, along other currently supported k8s kinds.

The implementation would entail proper handling of the `ConfigMap` kind in [the document handling loop](https://github.com/containers/podman/blob/63196c26a96652a824ff2d3fe68ac467060a0001/pkg/domain/infra/abi/play.go#L62) and using generated `ConfigMap` objects in the spec generation [here](https://github.com/containers/podman/blob/63196c26a96652a824ff2d3fe68ac467060a0001/pkg/domain/infra/abi/play.go#L324) and [here](https://github.com/containers/podman/blob/63196c26a96652a824ff2d3fe68ac467060a0001/pkg/domain/infra/abi/play.go#L372).

The behavior above _will not_ require a new `podman play kube` parameter (in contrast to the proposal discussed during the Community Cabal), because all the information required to assign `ConfigMap` to `Container` would already be in the set of YAML files sent in the payload. 

Adding support for `ConfigMap` payload will open possibility for adding end-to-end support for using ConfigMaps in other ways that are currently supported in k8s (like mounting them as files).

The existing functionality of specifying paths to files with ConfigMap resources must not be changed by this feature.

**Comment by jakub-dzon** [comment]
I'm going to work on that issue. 
Can one of the members of the organization assign this issue to me and add "In progress" label?

**Comment by rhatdan** [comment]
@umohnani8 FYI
