### ISSUE TITLE
`podman machine init` fails on M1 Macbook Air with exit status 1

### ISSUE THREAD

**Issue by kopiczko** [containers/podman#12379]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Run `brew install podman && podman machine init` on M1 Macbook Air

**Describe the results you received:**

```
$ podman machine init
Extracting compressed file
Error: exit status 1
```

I don't see any flags increasing verbosity for the `machine init` command.

Subsequent call results in:

```
$ podman machine init
Error: podman-machine-default: VM already exists
```

Trying to start the machine:

```
$ podman machine start
INFO[0000] waiting for clients...
INFO[0000] listening tcp://0.0.0.0:7777
INFO[0000] new connection from  to /var/folders/f8/n4kgy1dd4qn0lwrfjp66g0p80000gn/T/podman/qemu_podman-machine-default.sock
Waiting for VM ...
qemu-system-aarch64: -drive file=/Users/kopiczko/.local/share/containers/podman/machine/qemu/podman-machine-default_ovmf_vars.fd,if=pflash,format=raw: Could not open '/Users/kopiczko/.local/share/containers/podman/machine/qemu/podman-machine-default_ovmf_vars.fd': No such file or directory
Error: dial unix /var/folders/f8/n4kgy1dd4qn0lwrfjp66g0p80000gn/T/podman/podman-machine-default_ready.sock: connect: connection refused
ERRO[0003] cannot receive packets from , disconnecting: cannot read size from socket: EOF

ERRO[0003] cannot read size from socket: EOF
```

Trying to SSH:

```
$ podman machine ssh
Error: "podman-machine-default" service destination not found
```

When deleting:

```
$ podman machine rm

The following files will be deleted:

/Users/kopiczko/.ssh/podman-machine-default
/Users/kopiczko/.ssh/podman-machine-default.pub
/Users/kopiczko/.config/containers/podman/machine/qemu/podman-machine-default.ign
/Users/kopiczko/.local/share/containers/podman/machine/qemu/podman-machine-default_fedora-coreos-35.20211029.2.0-qemu.aarch64.qcow2
/Users/kopiczko/.local/share/containers/podman/machine/qemu/podman-machine-default_ovmf_vars.fd
/Users/kopiczko/.config/containers/podman/machine/qemu/podman-machine-default.json


Are you sure you want to continue? [y/N] y
ERRO[0001] remove /Users/kopiczko/.config/containers/podman/machine/qemu/podman-machine-default.ign: no such file or directory
ERRO[0001] remove /Users/kopiczko/.local/share/containers/podman/machine/qemu/podman-machine-default_ovmf_vars.fd: no such file or directory
```

**Describe the results you expected:**

Having running usable podman VM on Apple Silicon.

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Output of `podman version`:**

```
$ podman -v
podman version 3.4.2
```

`podman version` errors because it can't connect to the vm:

```
$ podman version
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v3.4.2/libpod/_ping": dial unix ///var/folders/f8/n4kgy1dd4qn0lwrfjp66g0p80000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```

**Output of `podman info --debug`:**

```
$ podman info --debug
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v3.4.2/libpod/_ping": dial unix ///var/folders/f8/n4kgy1dd4qn0lwrfjp66g0p80000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ brew info podman
podman: stable 3.4.2 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/opt/homebrew/Cellar/podman/3.4.2 (170 files, 40.9MB) *
  Poured from bottle on 2021-11-20 at 23:09:16
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0
==> Dependencies
Build: go ✔, go-md2man ✘
Required: qemu ✔
==> Options
--HEAD
        Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Analytics
install: 13,187 (30 days), 39,480 (90 days), 67,327 (365 days)
install-on-request: 13,191 (30 days), 39,484 (90 days), 67,268 (365 days)
build-error: 0 (30 days)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
$ uname -a
Darwin pawel-air 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101 arm64 arm64 MacBookAir10,1 Darwin
```

<img width="698" alt="Screenshot 2021-11-21 at 09 55 45" src="https://user-images.githubusercontent.com/4608994/142757484-68254de2-4a5d-42f0-ae03-fed13db46df2.png">

**Comment by DesantBucie** [comment]
Same error. Podman 3.4.2, nixpkgs, macos 12.0.1.

<img width="702" alt="image" src="https://user-images.githubusercontent.com/46130107/142766519-a03bbe2c-e432-4066-9df6-c17cbb81cf83.png">

**Comment by rhatdan** [comment]
@ashley-cui @baude PTAL

**Comment by ashley-cui** [comment]
```
acui@Ashleys-Mac-mini podman % podman machine start
INFO[0000] waiting for clients...                       
INFO[0000] listening tcp://0.0.0.0:7777                 
INFO[0000] new connection from  to /var/folders/zn/tds5mhcn3t14vhxc8jyvm4p40000gn/T/podman/qemu_podman-machine-default.sock 
Waiting for VM ...
Machine "podman-machine-default" started successfully
acui@Ashleys-Mac-mini podman % brew info podman
podman: stable 3.4.2 (bottled), HEAD
```
 It's working for me, but I'm on Darwin Kernel Version 20.6.0. Let me update the the mac and see if it still works

**Comment by Luap99** [comment]
The failure is with `podman machine init` not `podman machine start`. If init failed start cannot work. Is this the same issue as https://github.com/containers/podman/issues/12329?

**Comment by ashley-cui** [comment]
Ah sorry forgot to copy all the lines from my terminal, but init works as well for me. Let me try installing coreutils and seeing if that breaks anything...

acui@Ashleys-Mac-mini podman % podman machine init
Extracting compressed file

**Comment by zmc** [comment]
I am seeing this on a fresh install of podman on a new 14" MBP:
```
$ uname -a
Darwin squirrel 21.0.1 Darwin Kernel Version 21.0.1: Tue Sep 14 20:56:24 PDT 2021; root:xnu-8019.30.61~4/RELEASE_ARM64_T6000 x86_64
$ podman --version
podman version 3.4.2
$ podman --log-level=debug machine init
INFO[0000] podman filtering at log level debug
Extracting compressed file
$ podman --log-level=debug machine start
INFO[0000] podman filtering at log level debug
DEBU[0000] [/usr/local/bin/qemu-system-x86_64 -m 2048 -smp 1 -fw_cfg name=opt/com.coreos/config,file=/Users/zack/.config/containers/podman/machine/qemu/podman-machine-default.ign -qmp unix://var/folders/gk/bbndsg2x5xnf63xr1kbgcswc0000gn/T/podman/qmp_podman-machine-default.sock,server=on,wait=off -netdev socket,id=vlan,fd=3 -device virtio-net-pci,netdev=vlan,mac=5a:94:ef:e4:0c:ee -device virtio-serial -chardev socket,path=/var/folders/gk/bbndsg2x5xnf63xr1kbgcswc0000gn/T/podman/podman-machine-default_ready.sock,server=on,wait=off,id=podman-machine-default_ready -device virtserialport,chardev=podman-machine-default_ready,name=org.fedoraproject.port.0 -machine q35,accel=hvf:tcg -cpu host -drive if=virtio,file=/Users/zack/.local/share/containers/podman/machine/qemu/podman-machine-default_fedora-coreos-35.20211119.2.0-qemu.x86_64.qcow2]
[/usr/local/opt/podman/libexec/gvproxy -listen tcp://0.0.0.0:7777 -listen-qemu unix:///var/folders/gk/bbndsg2x5xnf63xr1kbgcswc0000gn/T/podman/qemu_podman-machine-default.sock -pid-file /var/folders/gk/bbndsg2x5xnf63xr1kbgcswc0000gn/T/podman/podman-machine-default.pid -ssh-port 52971 --debug]
DEBU[0000] Using search domains: [redhat.com front.sepia.ceph.com]
INFO[0000] waiting for clients...
INFO[0000] listening tcp://0.0.0.0:7777
DEBU[0000] [/usr/local/bin/qemu-system-x86_64 -m 2048 -smp 1 -fw_cfg name=opt/com.coreos/config,file=/Users/zack/.config/containers/podman/machine/qemu/podman-machine-default.ign -qmp unix://var/folders/gk/bbndsg2x5xnf63xr1kbgcswc0000gn/T/podman/qmp_podman-machine-default.sock,server=on,wait=off -netdev socket,id=vlan,fd=3 -device virtio-net-pci,netdev=vlan,mac=5a:94:ef:e4:0c:ee -device virtio-serial -chardev socket,path=/var/folders/gk/bbndsg2x5xnf63xr1kbgcswc0000gn/T/podman/podman-machine-default_ready.sock,server=on,wait=off,id=podman-machine-default_ready -device virtserialport,chardev=podman-machine-default_ready,name=org.fedoraproject.port.0 -machine q35,accel=hvf:tcg -cpu host -drive if=virtio,file=/Users/zack/.local/share/containers/podman/machine/qemu/podman-machine-default_fedora-coreos-35.20211119.2.0-qemu.x86_64.qcow2]
INFO[0000] new connection from  to /var/folders/gk/bbndsg2x5xnf63xr1kbgcswc0000gn/T/podman/qemu_podman-machine-default.sock
Waiting for VM ...
qemu-system-x86_64: Unknown Error
ERRO[0001] cannot receive packets from , disconnecting: cannot read size from socket: EOF
ERRO[0001] cannot read size from socket: EOF
Error: dial unix /var/folders/gk/bbndsg2x5xnf63xr1kbgcswc0000gn/T/podman/podman-machine-default_ready.sock: connect: connection refused
```
Should it be using an x86_64 image?

**Comment by baude** [comment]
> 



> $ uname -a
> Darwin squirrel 21.0.1 Darwin Kernel Version 21.0.1: Tue Sep 14 20:56:24 PDT 2021; root:xnu-8019.30.61~4/RELEASE_ARM64_T6000 x86_64
> $ podman --version
> podman version 3.4.2

I think your problem might be related to having rosetta installed? I believe I saw this once before where brew got confused or something confused brew about what architecture it was on.

**Comment by baude** [comment]
@kopiczko can you verify that the path that is being reported in the error actually exists?

**Comment by DesantBucie** [comment]
@baude I run it, if it helps. I'm using nix, not brew though, but i reproduced every step and i have 1:1 problem.
```
$ podman --log-level=debug machine init
INFO[0000] podman filtering at log level debug          
DEBU[0000] [/Users/dsnt/.nix-profile/bin/qemu-system-aarch64 -m 2048 -smp 1 -fw_cfg name=opt/com.coreos/config,file=/Users/dsnt/.config/containers/podman/machine/qemu/podman-machine-default.ign -qmp unix://var/folders/f1/lcg51mqj797bj4nvq9y4lbd80000gn/T/podman/qmp_podman-machine-default.sock,server=on,wait=off -netdev socket,id=vlan,fd=3 -device virtio-net-pci,netdev=vlan,mac=5a:94:ef:e4:0c:ee -device virtio-serial -chardev socket,path=/var/folders/f1/lcg51mqj797bj4nvq9y4lbd80000gn/T/podman/podman-machine-default_ready.sock,server=on,wait=off,id=podman-machine-default_ready -device virtserialport,chardev=podman-machine-default_ready,name=org.fedoraproject.port.0 -accel hvf -accel tcg -cpu cortex-a57 -M virt,highmem=off -drive file=edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on -drive file=/Users/dsnt/.local/share/containers/podman/machine/qemu/podman-machine-default_ovmf_vars.fd,if=pflash,format=raw -drive if=virtio,file=/Users/dsnt/.local/share/containers/podman/machine/qemu/podman-machine-default_fedora-coreos-35.20211029.2.0-qemu.aarch64.qcow2] 
Error: podman-machine-default: VM already exists

$ podman machine init
Downloading VM image: fedora-coreos-35.20211119.2.0-qemu.aarch64.qcow2.xz: done  
Extracting compressed file
```

```
$ podman machine start
Error: error checking VM active: stat /Users/dsnt/.local/share/containers/podman/machine/qemu/podman-machine-default_fedora-coreos-35.20211029.2.0-qemu.aarch64.qcow2: no such file or directory
$ podman machine init 
Error: podman-machine-default: VM already exists
$ podman machine start
Error: error checking VM active: stat /Users/dsnt/.local/share/containers/podman/machine/qemu/podman-machine-default_fedora-coreos-35.20211029.2.0-qemu.aarch64.qcow2: no such file or directory
$ cd .local/share/containers/podman/machine/qemu/                                                                                                                                                                              
1) default_fedora-coreos-35.20211119.2.0-qemu.aarch64.qcow2
2) default_ovmf_vars.fd
3) fedora-coreos-35.20211119.2.0-qemu.aarch64.qcow2.xz
```

**Comment by zmc** [comment]
@baude apologies, I deleted my comment and _later_ noticed your reply; you're basically correct. My issue was that I had very recently migrated from an Intel Mac and hadn't set up the separate aarch64 Homebrew install - so I ended up with x86_64 copies of qemu and podman. Everything worked once I corrected that, so my issue wasn't the one described here.

**Comment by kopiczko** [comment]
Thanks @Luap99 I think it's https://github.com/containers/podman/issues/12329 as I have `coreutils` installed and `PATH` changed on my machine. From my POV the fix looks good but I'm not sure if it will work with the nix setup mentioned by @DesantBucie. Waiting for the new release. I could try installing the latest main if there are instructions how to do so on MacOS.

Answering other questions just in case:

@ashley-cui `--log-level=debug` doesn't show much more information:

```
$ podman --log-level=debug machine init
INFO[0000] podman filtering at log level debug
Downloading VM image: fedora-coreos-35.20211119.2.0-qemu.aarch64.qcow2.xz: done
Extracting compressed file
Error: exit status 1
```

@baude just in case:

```
$ ls /Users/kopiczko/.local/share/containers/podman/machine/qemu/podman-machine-default_ovmf_vars.fd
ls: cannot access '/Users/kopiczko/.local/share/containers/podman/machine/qemu/podman-machine-default_ovmf_vars.fd': No such file or directory
```

**Comment by tigris** [comment]
Not sure if I'm seeing the same or similar problem. I also had `coreutils` installed and setup in a way that every GNU tool from homebrew would be found first in my path, including but not limited to `dd`. I switched back to a more stock path to test.

```
#-❯ export "PATH=/opt/homebrew/sbin:/usr/local/sbin:/usr/sbin:/sbin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"

#-❯ podman --log-level=debug machine init
INFO[0000] podman filtering at log level debug
Extracting compressed file
Error: cannot overwrite connection

#-❯ ls -lh ~/.local/share/containers/podman/machine/qemu/
total 4263152
-rw-rw-r--  1 danial.pearce  staff   581M  1 Dec 12:33 fedora-coreos-35.20211119.2.0-qemu.aarch64.qcow2.xz
-rw-------  1 danial.pearce  staff   1.4G  1 Dec 12:40 podman-machine-default_fedora-coreos-35.20211119.2.0-qemu.aarch64.qcow2

#-❯ file ~/.local/share/containers/podman/machine/qemu/*
/Users/danial.pearce/.local/share/containers/podman/machine/qemu/fedora-coreos-35.20211119.2.0-qemu.aarch64.qcow2.xz:                     XZ compressed data
/Users/danial.pearce/.local/share/containers/podman/machine/qemu/podman-machine-default_fedora-coreos-35.20211119.2.0-qemu.aarch64.qcow2: QEMU QCOW2 Image (v3), 10737418240 bytes
```

```
#-❯ brew list
==> Formulae
aom				freeimage			jbig2dec			libtiff				openjpeg			shush
autoconf			freetype			jpeg				libtool				openldap			six
automake			gawk				jpeg-xl				libunistring			openssl@1.1			snappy
awscli				gdbm				jq				libusb				p11-kit				sqlite
bash				gettext				krb5				libuv				pcre				tcl-tk
bdw-gc				gh				less				libvmaf				pcre2				telnet
berkeley-db			ghostscript			libassuan			libyaml				perl				the_silver_searcher
binutils			giflib				libde265			little-cms2			pinentry			unbound
bison				git				libevent			lua				pixman				unzip
bk				glib				libffi				lz4				pkg-config			vde
brotli				gmp				libgcrypt			lzo				podman				vim
buildkite-agent			gnu-getopt			libgpg-error			m4				popt				webp
c-ares				gnu-indent			libheif				make				postgresql			wget
ca-certificates			gnu-sed				libidn				mpdecimal			postgresql@13			x265
chruby				gnu-tar				libidn2				mpfr				pv				xmlto
coreutils			gnu-which			libksba				ncurses				python@3.9			xxhash
curl				gnupg				liblqr				nettle				qemu				xz
diffutils			gnutls				libnghttp2			ninja				rea-as				zip
docbook				grep				libomp				node				readline			zlib
docbook-xsl			guile				libpng				npth				rsync				zstd
docker-credential-helper-ecr	gzip				libslirp			ntfs-3g-mac			rtmpdump
expect				icu4c				libssh				nvm				ruby
findutils			imagemagick			libssh2				oniguruma			ruby-install
fontconfig			imath				libtasn1			openexr				shared-mime-info

==> Casks
graphiql		macfuse			visual-studio-code
```

**Comment by DesantBucie** [comment]
> From my POV the fix looks good but I'm not sure if it will work with the nix setup mentioned by @DesantBucie. 

No it probably won't as I think nix installs coreutils as a dependency.

**Comment by josh-coderpad** [comment]
Removing `/opt/homebrew/opt/coreutils/libexec/gnubin` from my `$PATH` (then a `podman machine rm` first) fixes the issue with `podman machine init` for me.

**Comment by kopiczko** [comment]
Confirmed. Everything works with `PATH=/bin:$PATH podman`.

**Comment by josh-coderpad** [comment]
It'd be nice if podman supported GNU Coreutils on mac, or at least documented that it didn't/gave a better error. That said, I imagine this doesn't need to be run often, so the workaround is effective for now.

**Comment by momrak** [comment]
@DesantBucie did you manage to get a working Nix setup for this? I get the same error as you had above only I am running the  ´podman machine start´ command

**Comment by DesantBucie** [comment]
@momrak Not at all. I also tried to download from release, but it's the same error.
```
└─> podman machine start
INFO[0000] waiting for clients...                       
INFO[0000] listening tcp://127.0.0.1:7777               
INFO[0000] new connection from  to /var/folders/f1/lcg51mqj797bj4nvq9y4lbd80000gn/T/podman/qemu_podman-machine-default.sock 
Waiting for VM ...
qemu-system-aarch64: -drive file=edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on: Could not open 'edk2-aarch64-code.fd': No such file or directory
Error: dial unix /var/folders/f1/lcg51mqj797bj4nvq9y4lbd80000gn/T/podman/podman-machine-default_ready.sock: connect: connection refused
ERRO[0003] cannot receive packets from , disconnecting: cannot read size from socket: EOF 
ERRO[0003] cannot read size from socket: EOF    
```

**Comment by DesantBucie** [comment]
@momrak
It actually looks like issue with nix version of qemu rather than podman. 
Although i don't know how exactly but i did it.
<img width="886" alt="image" src="https://user-images.githubusercontent.com/46130107/147983531-bde411e1-0785-42d1-9062-3ac56903fd5e.png">

Steps to reproduce
1. `cd /nix/store/*qemu-6.1.0/share/qemu`
2. `sudo mkdir -p /usr/local/share/qemu/`
3. `sudo mkdir -p /opt/homebrew/share/qemu/`
4. `cp edk2-aarch64-code.fd  /usr/local/share/qemu`
5.  `cp edk2-aarch64-code.fd  /opt/homebrew/share/qemu`
6.  `cd ~/.local/share/`
7.  `rm -rf containers`

Not really beautiful but it works :v. Also you probably need to install `gvproxy` if you hadn't already.

**Comment by baude** [comment]
m1's require a patched version of qemu in brew for a little while. if you have a different version of qemu installed, it is likely the issue

**Comment by momrak** [comment]
Thank you both @baude and @DesantBucie 

@DesantBucie nice! So you only used the default qemu from nix, not a patched one from brew or similar?

Do you know if the patch is only present in the brew version of this @baude  ? In that case it could have been interesting to try and make the same patch available for m1 macs using nix

**Comment by DesantBucie** [comment]
> @DesantBucie nice! So you only used the default qemu from nix, not a patched one from brew or similar?

I used qemu 6.1.0, gvproxy 0.3 and podman 3.4.4 all from unstable channel.

**Comment by momrak** [comment]
I got it working now as well, but with a slightly different approach
I added this dir as a helper binary. Don't quite remember if that was for gvproxy or something else to be picked up correctly.
`~/.config/containers/containers.conf`
```
...
 [engine]
    helper_binaries_dir = ["/Users/momrak/.nix-profile/bin"]
...
```

Also changed the actual machines qemu config so that the file it looks for uses a abs path
`~/.config/containers/podman/machine/qemu/podman-machine-default.json`
```
...
"file=/nix/store/sbjkaks28979lannj9a2mi5s8v7fchi1-qemu-6.1.0/share/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on"
...

So this is also not a very good solution, hehe.

@baude do you know if there is a way to set some location for qemu to look for the edk2-file in similar to the helper_binaries_dir? Then maybe one could do something in the nix derivation in order to fix it. Not sure if this is possible or a good idea though

**Comment by baude** [comment]
There is not a way to do this currently in podman.

**Comment by DesantBucie** [comment]
@michaelkrasa This is probably due to running qemu x86-64 instead of aarch64.

**Comment by ct9915** [comment]
# patch qemu save me!
```
brew install simnalamburt/x/podman-apple-silicon

```
## remember brew unlink qemu and brew unlink podman if you already installed qemu and podman 
![截圖 2022-02-06 上午9 31 25](https://user-images.githubusercontent.com/3616371/152664712-d6168868-22ba-41d6-8b9a-9992ae5aef64.png)

**Comment by yifeikong** [comment]
I was having the same problem. My guess is that my podman machine is migrated from old Intel MacBook, so the image is Intel based, on which the Qemu bin is located in /usr/local/bin. My solution was simply remove the old machine and creates a new one.

```
podman machine rm
podman machine init
```

Everything works like a charm.

**Comment by jwildeboer** [comment]
It just never works, no matter what I try :(

jwildeboer@JHWMBA ~ % brew remove podman-desktop 
==> Uninstalling Cask podman-desktop
==> Backing App 'Podman Desktop.app' up to '/opt/homebrew/Caskroom/podman-deskto
==> Removing App '/Applications/Podman Desktop.app'
==> Purging files for version 0.9.1 of Cask podman-desktop
jwildeboer@JHWMBA ~ % brew remove podman         
Uninstalling /opt/homebrew/Cellar/podman/4.3.0... (185 files, 47.6MB)
jwildeboer@JHWMBA ~ % brew install podman
==> Downloading https://ghcr.io/v2/homebrew/core/podman/manifests/4.3.0
Already downloaded: /Users/jwildeboer/Library/Caches/Homebrew/downloads/7360bf1699dcbb76150aea89eec8489fa47159edb55acd441ef406cb3a9eca99--podman-4.3.0.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/podman/blobs/sha256:1d00923c766
Already downloaded: /Users/jwildeboer/Library/Caches/Homebrew/downloads/0d6c8046b07544b0baf47ec94a54f757a02a634bbd4529bbd9b6c10aadc2c608--podman--4.3.0.arm64_ventura.bottle.tar.gz
==> Pouring podman--4.3.0.arm64_ventura.bottle.tar.gz
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions

To restart podman after an upgrade:
  brew services restart podman
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/podman/bin/podman system service --time=0
==> Summary
🍺  /opt/homebrew/Cellar/podman/4.3.0: 185 files, 47.6MB
==> Running `brew cleanup podman`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
jwildeboer@JHWMBA ~ % brew services restart podman
==> Tapping homebrew/services
Cloning into '/opt/homebrew/Library/Taps/homebrew/homebrew-services'...
remote: Enumerating objects: 2233, done.
remote: Counting objects: 100% (167/167), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 2233 (delta 120), reused 112 (delta 105), pack-reused 2066
Receiving objects: 100% (2233/2233), 614.54 KiB | 6.61 MiB/s, done.
Resolving deltas: 100% (1000/1000), done.
Tapped 1 command (45 files, 773.1KB).
==> Successfully started `podman` (label: homebrew.mxcl.podman)
jwildeboer@JHWMBA ~ % podman machine init         
Extracting compressed file
Error: cannot overwrite connection
jwildeboer@JHWMBA ~ %
