### ISSUE TITLE
clarification request regarding the necessity and persistence of enable-linger in rootless mode

### ISSUE THREAD

**Issue by godmar** [containers/podman#12376]
The [troubleshooting guide](https://github.com/containers/podman/blob/main/troubleshooting.md) has 2 entries:

[17. rootless containers exit once the user sessions exits](https://github.com/containers/podman/blob/main/troubleshooting.md#symptom-14) and [21. A rootless container running in detached mode is closed at logout](https://github.com/containers/podman/blob/main/troubleshooting.md#21-a-rootless-container-running-in-detached-mode-is-closed-at-logout).

- do these issues address an identical problem?  If so, could they be consolidated into one?
- would it be possible to add more details, such as:
   - when does `loginctl enable-linger` require root privileges (or, in general, what capability does it require)
   - how does a user tell if this applies to them?
   - where is the information whether a user lingers stored, and how long does it persist?  Is it per session, or is it stored in a configuration file?  If so, is it in the user's home directory or elsewhere? (On my system, which has user's home directories on NFS, it appears that I need to repeat this setting every time I start a detached container - is this expected?). Is there a way to make this setting persistent for an unprivileged user?

I note that at the time of this writing, there are [85 closed issues that mention enable-linger](https://github.com/containers/podman/issues?q=is%3Aissue+enable-linger) so this may be a frequent problem.

Thank you.

**Comment by rhatdan** [comment]
Are you interested in opening a PR fo this?
It looks like enable-linger requires the user to be in the `wheel` group or to provide the root password, I don't think there is a capability involved, since this is a communication with systemd.
You can see what users are enabled to linger by listing /var/lib/systemd/linger directory
$ ls /var/lib/systemd/linger
dwalsh

Pretty much without setting the linger, systemd will kill all processes created by users when the log out. Whether those processes are created normally or as a container.
Enable-linger usually comes up more when users are attempting to create user system services to run containers at boot time, in which case they need to enable it.

1. Where is the information whether a user lingers stored?
            /var/lib/systemd/linger
2. How long does it persist? 
            Until the file is removed by the user or an administrator.
3. Is it per session, or is it stored in a configuration file? 
            I believe it is for all user sessions.
4. If so, is it in the user's home directory or elsewhere? 
            See #1
5. (On my system, which has user's home directories on NFS, it appears that I need to repeat this setting every time I start a detached container - is this expected?). 
             No
6. Is there a way to make this setting persistent for an unprivileged user?
             I would think just creating the file.  I don't believe anything other the a user or admin remove the setting.

**Comment by mheon** [comment]
I would concur with Dan that what you're experiencing (needing to frequently reenable lingering) sounds like a bug (almost certainly with Systemd, not Podman, we don't touch that directly).

**Comment by godmar** [comment]
> Are you interested in opening a PR fo this?

Thank you for the reply, at this point I feel like I don't know enough about podman to do this. Perhaps for now continuing this discussion here may help other readers.

> It looks like enable-linger requires the user to be in the wheel group or to provide the root password, I don't think there is a capability involved, since this is a communication with systemd.

On my machine (CentOS 8 Stream with podman-3.4.1-dev), I found out that I can change my own linger setting without requiring any additional privileges such as being in `wheel`, only trying to change another user's linger setting appears to prompt for a root password. That's good.

> You can see what users are enabled to linger by listing /var/lib/systemd/linger directory
> $ ls /var/lib/systemd/linger
> dwalsh

Indeed. I also was mistaken that the setting isn't remembered. It is, it's just that it's in a local file system and not shared across machines as it would be if it were remembered in the user's network-mounted home directory.

> 
> Pretty much without setting the linger, systemd will kill all processes created by users when the log out. Whether those processes are created normally or as a container.

Is this really true?  On our machines, `loginctl show-user` shows `KillUserProcesses=no` which according to [logind.conf](https://www.freedesktop.org/software/systemd/man/logind.conf.html) means that 'the scope is "abandoned", see systemd.scope(5), and processes are not killed'

> Enable-linger usually comes up more when users are attempting to create user system services to run containers at boot time, in which case they need to enable it.

This is confusing. Based on my recollection, user system services used to not work on at least earlier versions of CentOS (before stream) - I recall trying to use them some years ago and having to abandon that.

It appears that the linger setting is necessary for any detached container to survive a logout. Continuing to quote from the manpage:

_In addition to session processes, user process may run under the user manager unit user@.service. Depending on the linger settings, this may allow users to run processes independent of their login sessions. See the description of enable-linger in loginctl(1)._

It appears that `enable-linger` and `KillUserProcesses` are separate settings.  `KillUserProcesses` may be set to no, so users are ordinarily accustomed to their processes not being killed on logout, but yet podman still requires `enable-linger`, presumably because its containers are run under `user@.service`.

The failure mode here, btw, feels uncomfortable - before I discovered this FAQ after browsing the github issues, podman had become unusable, notably, upon `podman ps` the infamous `unknown FS magic` popped up and I could recover only via `podman rm --force <containerid>` as described in other issues.

**Comment by rhatdan** [comment]
I am by no means an expert on this.  I think one of the reasons Podman wants linger is that it uses XDG_RUNTIME_DIR and wants this to be set when running in a systemd user service at boot.

I am not as concerned with when a user logs out, as for the system services.

**Comment by mheon** [comment]
In addition to requiring a valid `XDG_RUNTIME_DIR` for rootless users (systemd will tear down `/run/user/$UID` on logout by default), as Dan mentioned, we also require an active DBus socket for the user on CGroupsv2 systems, which requires an active user session.

**Comment by godmar** [comment]
As a related aside, on one of the machines where I am testing, the use of podman to run a rootless detached container has somehow led to the killing of the 'User Manager' systemd unit for my account. This means that `XDG_RUNTIME_DIR` is no longer set when I log in. It's a machine where I don't have root so I can't examine the logs; I'm working with the system administrator to try to find out what could have caused the failure of this systemd user unit. But it basically means that users could get into a situation that requires recovery actions to be taken by a sysadmin, just for using podman.

**Comment by godmar** [comment]
To follow up on the conversation with my sysadmin. They claimed that some "cleanup" script (whose content they weren't willing to disclose) led to the stopping of my user unit and that they were able to restart it. They then proceeded to disable that "cleanup" script.

After that, I've used podman on the same cluster for a group of over 200 students successfully. Each student built a container and started it in detached mode (all rootless). That is, enabling lingering allowed detached containers to persist even after the users logged off.  The associated user units stayed active.

So the lesson here is that podman probably works as advertised, but that there may be subtle interactions with assumptions system administrators make, or things they believe they need to do to maintain their machines but which inadvertently interact with podman in some way.  Sorry I wasn't able to find out more.

**Comment by rhatdan** [comment]
Thanks @godmar Great information, and I am happy Podman worked correctly.
