### ISSUE TITLE
Rootless podman stopped working after upgrade on ubuntu

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman#12374]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

After upgrading podman on ubuntu, it can no longer read the images.

Apparently you have to delete everything, in order to keeep using it ?

**Steps to reproduce the issue:**

1. `apt update`

2. `apt upgrade`

3. `podman version`

**Describe the results you received:**

`ERRO[0000] User-selected graph driver "overlay" overwritten by graph driver "vfs" from database - delete libpod local files to resolve`

**Describe the results you expected:**

```
Version:      3.4.2
```

**Additional information you deem important (e.g. issue happens only occasionally):**

It was working, with podman 3.3.1.

After upgrade, it started failing:

```
DEBU[0000] cached value indicated that overlay is not supported 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf" 
DEBU[0000] Merged system config "/home/anders/.config/containers/containers.conf" 
DEBU[0000] cached value indicated that overlay is not supported 
```

After wiping the local storage, it says:

```
DEBU[0000] overlay storage already configured with a mount-program 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf" 
DEBU[0000] Merged system config "/home/anders/.config/containers/containers.conf" 
DEBU[0000] overlay storage already configured with a mount-program 
```

But without the images.

**Output of `podman version`:**

```
(paste your output here)
```

```console
$ podman --version
podman version 3.4.2
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 100:3.4.2-1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 20.04 LTS

5.4.0-90-generic

**Comment by rhatdan** [comment]
Were you using a VFS backend before?

**Comment by rhatdan** [comment]
Most likely the kernel changed, which cause fuse-overlay to  no longer be needed, but use native overlay.  Don't know where the vfs error comes from.

**Comment by mheon** [comment]
Did Ubuntu start shipping a default `containers.conf` for all non-root users, potentially? Are these the official packages, or from our OBS repos?

**Comment by mheon** [comment]
That error should only occur if there's a `storage.conf` file in the user's own home directory, hardcoding a graph driver of `overlay`, but the user has previously run Podman without said file using a graph driver of `vfs`

**Comment by rhatdan** [comment]
Yes I agree with this assessment.

**Comment by rhatdan** [comment]
If you were on a system without fuse-overlay and native overlay support, the podman rootless commands would default to vfs.

**Comment by afbjorklund** [comment]
Was using fuse-overlayfs

**Comment by afbjorklund** [comment]
Suggested workaround (deleting files) will have to do
