### ISSUE TITLE
podman play kube and secrets

### ISSUE THREAD

**Issue by Smeds** [containers/podman#12396]
I need some guidance. I can start pods successfully using "podman play kube" with podman secrets, provided to the container with fromEnv and secretRef. My problem with this solution is that then my secrets are viewable using inspect. Is it possible to have them mounted as files like with "podman run --secret"? Or is that just not possible right now with "podman play kube"?

**Comment by vrothberg** [comment]
Thanks for reaching out, @Smeds!

@ashley-cui PTAL

**Comment by rhatdan** [comment]
@ashley-cui Please respond to this issue.

**Comment by ashley-cui** [comment]
I think this is an issue with how play kube treats secrets, it doesn't go in as an env secret, but rather just an regular env var (https://github.com/containers/podman/blob/aaf90c5596fb2232d915fcd75d4d707d180c1b17/pkg/specgen/generate/kube/kube.go#L597) 
@rhatdan We talked about this a while ago with @vrothberg, and a while back we came to the conclusion that play kube secrets were kinda broken and incompatible with native podman secrets. This seems serious enough that we should fix it, but as kube secrets and podman secrets go, they're implemented differently enough that we need to discuss again on how to fix it or what we should go going forwards.

**Comment by rhatdan** [comment]
@vrothberg I think it is time to revisit this.

**Comment by vrothberg** [comment]
I am OK bumping this up the priority list. What we need is:
* Somebody must (re)catch up on what the problem was. I recall that K8s secrets are hierarchical while Podman secrets are flat but I have a squirrel brain.
* A design meeting to discuss how to best solve the problem.
* Somebody to work on it :^)

@acui, do you have time?

**Comment by rhatdan** [comment]
Adding @umohnani8 Also.  I just want to kick off a meeting on completing missing features in podman play/generate kube.  Prioritize and work on the issues that match up with this.  Secrets being one of the big ones.
