### ISSUE TITLE
Docker image with podman.socket service

### ISSUE THREAD

**Issue by gnd** [containers/podman#12391]
/kind feature

Hi, we are experimenting with replacing Docker with Podman in production, and with simple builds this is fairly easy. We are using gitlab runners (docker) within a Kubernetes cluster. The usual way to replace Docker for builds would be: 

```# Using podman for building
image: quay.io/podman/stable
  
stages:
  - build

build:
  stage: build
  before_script:
    - podman login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - podman build -t $SOME_TAG --no-cache --pull .
    - podman push $CI_REGISTRY_IMAGE:$SOME_TAG
```

However more complex pipelines utilize a lot of docker-compose for testing. According to [this article](https://www.redhat.com/sysadmin/podman-docker-compose) it's not a problem with Podman since version 3. However one needs to install _podman-docker_ and _docker-compose_ packages and run the _podman.socket_ service. Inside _quay.io/podman/stable_ the first two requirements are fairly simple: 

`
yum -y install podman-docker docker-compose
`

However it is the _podman.socket_ service that is giving us a headache. The podman stable image doesn't provide a way how to start it. Is there perhaps a different image that has already all prerequisities installed and the service running ? Is it possible that it too is rootless / doesnt require --privileged (which is the top reason we are interested in using podman at all). 

Thanks a lot for any pointers !

**Comment by rhatdan** [comment]
Do you want a systemd version of the service, or why not just start it yourself, with `podman system service -t 0`

**Comment by gnd** [comment]
> Do you want a systemd version of the service, or why not just start it yourself, with `podman system service -t 0`

well i tried that too, and this was the result:

```WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
cannot clone: Operation not permitted
Error: cannot re-exec process
```

**Comment by rhatdan** [comment]
The issue is the docker daemon that github is running is not allow the syscall clone, which will prevent you from running containers inside of containers.
Podman and friends defaults to allowing clone within seccomp.json, but Docker does not.
```
$ grep clone /usr/share/containers/seccomp.json 
				"clone",
				"clone3",
```
If you run Docker with podman seccomp.json file, then this should work.

**Comment by rhatdan** [comment]
Since I answered this issue I am going to close, if you want to continue the conversation, you can do it in this issue.
