### ISSUE TITLE
Cannot set RT priority in container

### ISSUE THREAD

**Issue by mario19911** [containers/podman#12418]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I tried to run a short program in a podman container. When I tried to set the priority to realtime, I always get EPERM as errno. I already tried to run podman with the flag --cpu-rt-runtime=950000. 

The program:
```
#include <stdio.h>
#include <unistd.h>
#include <sched.h>
#include <pthread.h>
#include <errno.h>

int main(int argc, char *argv[])
{
  printf("Setting rt prio\n");

  struct sched_param param;
  param.sched_priority=20;
  int retval = sched_setscheduler(0, SCHED_RR, &param);
  printf("Retval: %d, Errno: %d\n", retval, errno);

  return 0;
 }
```

**Steps to reproduce the issue:**

1. Compile the following program with gcc -o realtime realtime.c -lpthread

2. podman run -it  --entrypoint=/bin/sh realtime

3. ./realtime

**Describe the results you received:**
/ # ./realtime
Setting rt prio
Retval: 1, Errno: 1

**Describe the results you expected:**
I would expect that this call should be ok.
/ # ./realtime
Setting rt prio
Retval: 0, Errno: 0

**Additional information you deem important (e.g. issue happens only occasionally):**
I am running on WSL2 under windows. When I tried to add the flag --cpu-rt-runtime=950000 I got the following error:

Tried the same with runc itself, there it worked.

DEBU[0000] ExitCode msg: "writing file `cpu.rt_runtime_us`: invalid argument: oci runtime error"
Error: OCI runtime error: writing file `cpu.rt_runtime_us`: Invalid argument

**Output of `podman version`:**

```
podman version 3.4.2
```

**Output of `podman info --debug`:**

```
root@md3bex3c:/home# podman info --debug
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 12
  distribution:
    codename: focal
    distribution: ubuntu
    version: "20.04"
  eventLogger: file
  hostname: md3bex3c
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.72-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 10649264128
  memTotal: 13199646720
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: ea1fe3938eefa14eb707f1d22adff4db670645d6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 4294967296
  swapTotal: 4294967296
  uptime: 55m 59.5s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 0
    stopped: 7
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.4.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
root@md3bex3c:/home# apt list podman
Listing... Done
podman/unknown,now 100:3.4.2-1 amd64 [installed]
podman/unknown 100:3.4.2-1 arm64
podman/unknown 100:3.4.2-1 armhf
podman/unknown 100:3.4.2-1 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I am using WSL2, tried with Ubuntu 20.04 and Debian distro.

**Comment by flouthoc** [comment]
@mario19911 I think you would need more privileges or alteast `CAP_SYS_NICE` , could you try with `podman run --security-opt seccomp=unconfined --cap-add all -it --entrypoint=/bin/sh realtime`

>I am running on WSL2 under windows. When I tried to add the flag --cpu-rt-runtime=950000 I got the following error:
>Tried the same with runc itself, there it worked.
>DEBU[0000] ExitCode msg: "writing file cpu.rt_runtime_us: invalid argument: oci runtime error"
>Error: OCI runtime error: writing file cpu.rt_runtime_us: Invalid argument

Could you elaborate more here ? Do you mean `--cpu-rt-runtime=950000` is not processed by `crun` properly while it works with `runc` ?

**Comment by flouthoc** [comment]
@mario19911 For the `invalid argument` it looks more like that there is less CPU bandwidth available than requested. I'd suggest testing with a smaller value with `podman/crun` `--cpu-rt-runtime=95000`.

**Comment by mario19911** [comment]
@flouthoc : Thanks for the fast answer.
I just ran it with ``podman run -it --mount type=bind,source=realtime,target=/realtime --cap-add all --security-opt seccomp=unconfined --entrypoint=/bin/sh rtus/rtum85/04.mj``. This also failed for me.

Additionally I tried to add the ``--cpu-rt-runtime=950000`` and again got the error ``Error: OCI runtime error: writing file `cpu.rt_runtime_us`: Invalid argument``. Also with the smaller value of 95000 I got the same error. It only works when I set it to 0.

Regarding runc: I tried the same with podman + runc --> same result. When I set up a config.json and started the same with runc only, it worked.

**Comment by giuseppe** [comment]
> Regarding runc: I tried the same with podman + runc --> same result. When I set up a config.json and started the same with runc only, it worked.

does the same config.json file work with crun?

Could you share the config.json file you've used?

**Comment by mario19911** [comment]
Sure, this it is:
``{
	"ociVersion": "1.0.2-dev",
	"process": {
		"terminal": true,
		"user": {
			"uid": 0,
			"gid": 0
		},
		"args": [
			"sh"
		],
		"env": [
			"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
			"TERM=xterm"
		],
		"cwd": "/",
		"capabilities": {
			"bounding": [
				"CAP_CHOWN",
				"CAP_DAC_OVERRIDE",
				"CAP_DAC_READ_SEARCH",
				"CAP_FOWNER",
				"CAP_FSETID",
				"CAP_KILL",
				"CAP_SETGID",
				"CAP_SETUID",
				"CAP_SETPCAP",
				"CAP_LINUX_IMMUTABLE",
				"CAP_NET_BIND_SERVICE",
				"CAP_NET_BROADCAST",
				"CAP_NET_ADMIN",
				"CAP_NET_RAW",
				"CAP_IPC_LOCK",
				"CAP_IPC_OWNER",
				"CAP_SYS_MODULE",
				"CAP_SYS_RAWIO",
				"CAP_SYS_CHROOT",
				"CAP_SYS_PTRACE",
				"CAP_SYS_PACCT",
				"CAP_SYS_ADMIN",
				"CAP_SYS_BOOT",
				"CAP_SYS_NICE",
				"CAP_SYS_RESOURCE",
				"CAP_SYS_TIME",
				"CAP_SYS_TTY_CONFIG",
				"CAP_MKNOD",
				"CAP_LEASE",
				"CAP_AUDIT_WRITE",
				"CAP_AUDIT_CONTROL",
				"CAP_SETFCAP",
				"CAP_MAC_OVERRIDE",
				"CAP_MAC_ADMIN",
				"CAP_SYSLOG",
				"CAP_WAKE_ALARM",
				"CAP_BLOCK_SUSPEND",
				"CAP_AUDIT_READ"
			],
			"effective": [
				"CAP_CHOWN",
				"CAP_DAC_OVERRIDE",
				"CAP_DAC_READ_SEARCH",
				"CAP_FOWNER",
				"CAP_FSETID",
				"CAP_KILL",
				"CAP_SETGID",
				"CAP_SETUID",
				"CAP_SETPCAP",
				"CAP_LINUX_IMMUTABLE",
				"CAP_NET_BIND_SERVICE",
				"CAP_NET_BROADCAST",
				"CAP_NET_ADMIN",
				"CAP_NET_RAW",
				"CAP_IPC_LOCK",
				"CAP_IPC_OWNER",
				"CAP_SYS_MODULE",
				"CAP_SYS_RAWIO",
				"CAP_SYS_CHROOT",
				"CAP_SYS_PTRACE",
				"CAP_SYS_PACCT",
				"CAP_SYS_ADMIN",
				"CAP_SYS_BOOT",
				"CAP_SYS_NICE",
				"CAP_SYS_RESOURCE",
				"CAP_SYS_TIME",
				"CAP_SYS_TTY_CONFIG",
				"CAP_MKNOD",
				"CAP_LEASE",
				"CAP_AUDIT_WRITE",
				"CAP_AUDIT_CONTROL",
				"CAP_SETFCAP",
				"CAP_MAC_OVERRIDE",
				"CAP_MAC_ADMIN",
				"CAP_SYSLOG",
				"CAP_WAKE_ALARM",
				"CAP_BLOCK_SUSPEND",
				"CAP_AUDIT_READ"
			],
			"inheritable": [
				"CAP_CHOWN",
				"CAP_DAC_OVERRIDE",
				"CAP_DAC_READ_SEARCH",
				"CAP_FOWNER",
				"CAP_FSETID",
				"CAP_KILL",
				"CAP_SETGID",
				"CAP_SETUID",
				"CAP_SETPCAP",
				"CAP_LINUX_IMMUTABLE",
				"CAP_NET_BIND_SERVICE",
				"CAP_NET_BROADCAST",
				"CAP_NET_ADMIN",
				"CAP_NET_RAW",
				"CAP_IPC_LOCK",
				"CAP_IPC_OWNER",
				"CAP_SYS_MODULE",
				"CAP_SYS_RAWIO",
				"CAP_SYS_CHROOT",
				"CAP_SYS_PTRACE",
				"CAP_SYS_PACCT",
				"CAP_SYS_ADMIN",
				"CAP_SYS_BOOT",
				"CAP_SYS_NICE",
				"CAP_SYS_RESOURCE",
				"CAP_SYS_TIME",
				"CAP_SYS_TTY_CONFIG",
				"CAP_MKNOD",
				"CAP_LEASE",
				"CAP_AUDIT_WRITE",
				"CAP_AUDIT_CONTROL",
				"CAP_SETFCAP",
				"CAP_MAC_OVERRIDE",
				"CAP_MAC_ADMIN",
				"CAP_SYSLOG",
				"CAP_WAKE_ALARM",
				"CAP_BLOCK_SUSPEND",
				"CAP_AUDIT_READ"
			],
			"permitted": [
				"CAP_CHOWN",
				"CAP_DAC_OVERRIDE",
				"CAP_DAC_READ_SEARCH",
				"CAP_FOWNER",
				"CAP_FSETID",
				"CAP_KILL",
				"CAP_SETGID",
				"CAP_SETUID",
				"CAP_SETPCAP",
				"CAP_LINUX_IMMUTABLE",
				"CAP_NET_BIND_SERVICE",
				"CAP_NET_BROADCAST",
				"CAP_NET_ADMIN",
				"CAP_NET_RAW",
				"CAP_IPC_LOCK",
				"CAP_IPC_OWNER",
				"CAP_SYS_MODULE",
				"CAP_SYS_RAWIO",
				"CAP_SYS_CHROOT",
				"CAP_SYS_PTRACE",
				"CAP_SYS_PACCT",
				"CAP_SYS_ADMIN",
				"CAP_SYS_BOOT",
				"CAP_SYS_NICE",
				"CAP_SYS_RESOURCE",
				"CAP_SYS_TIME",
				"CAP_SYS_TTY_CONFIG",
				"CAP_MKNOD",
				"CAP_LEASE",
				"CAP_AUDIT_WRITE",
				"CAP_AUDIT_CONTROL",
				"CAP_SETFCAP",
				"CAP_MAC_OVERRIDE",
				"CAP_MAC_ADMIN",
				"CAP_SYSLOG",
				"CAP_WAKE_ALARM",
				"CAP_BLOCK_SUSPEND",
				"CAP_AUDIT_READ"
			],
			"ambient": [
				"CAP_CHOWN",
				"CAP_DAC_OVERRIDE",
				"CAP_DAC_READ_SEARCH",
				"CAP_FOWNER",
				"CAP_FSETID",
				"CAP_KILL",
				"CAP_SETGID",
				"CAP_SETUID",
				"CAP_SETPCAP",
				"CAP_LINUX_IMMUTABLE",
				"CAP_NET_BIND_SERVICE",
				"CAP_NET_BROADCAST",
				"CAP_NET_ADMIN",
				"CAP_NET_RAW",
				"CAP_IPC_LOCK",
				"CAP_IPC_OWNER",
				"CAP_SYS_MODULE",
				"CAP_SYS_RAWIO",
				"CAP_SYS_CHROOT",
				"CAP_SYS_PTRACE",
				"CAP_SYS_PACCT",
				"CAP_SYS_ADMIN",
				"CAP_SYS_BOOT",
				"CAP_SYS_NICE",
				"CAP_SYS_RESOURCE",
				"CAP_SYS_TIME",
				"CAP_SYS_TTY_CONFIG",
				"CAP_MKNOD",
				"CAP_LEASE",
				"CAP_AUDIT_WRITE",
				"CAP_AUDIT_CONTROL",
				"CAP_SETFCAP",
				"CAP_MAC_OVERRIDE",
				"CAP_MAC_ADMIN",
				"CAP_SYSLOG",
				"CAP_WAKE_ALARM",
				"CAP_BLOCK_SUSPEND",
				"CAP_AUDIT_READ"
			]
		},
		"rlimits": [
			{
				"type": "RLIMIT_MSGQUEUE",
				"hard": 16777216,
				"soft": 16777216
			}
		],
		"noNewPrivileges": true
	},
	"root": {
		"path": "rootfs",
		"readonly": false
	},
	"mounts": [
		{
			"destination": "/proc",
			"type": "proc",
			"source": "proc"
		},
		{
			"destination": "/dev",
			"type": "tmpfs",
			"source": "tmpfs",
			"options": [
				"nosuid",
				"strictatime",
				"mode=755",
				"size=65536k"
			]
		},
		{
			"destination": "/dev/pts",
			"type": "devpts",
			"source": "devpts",
			"options": [
				"nosuid",
				"noexec",
				"newinstance",
				"ptmxmode=0666",
				"mode=0620",
				"gid=5"
			]
		},
		{
			"destination": "/dev/shm",
			"type": "tmpfs",
			"source": "shm",
			"options": [
				"nosuid",
				"noexec",
				"nodev",
				"mode=1777",
				"size=65536k"
			]
		},
		{
			"destination": "/dev/mqueue",
			"type": "mqueue",
			"source": "mqueue",
			"options": [
				"nosuid",
				"noexec",
				"nodev"
			]
		},
		{
			"destination": "/sys",
			"type": "sysfs",
			"source": "sysfs",
			"options": [
				"nosuid",
				"noexec",
				"nodev"
			]
		},
		{
			"destination": "/sys/fs/cgroup",
			"type": "cgroup",
			"source": "cgroup",
			"options": [
				"nosuid",
				"noexec",
				"nodev"
			]
		}
	],
"linux": {
	"devices": [
			{
				"path": "/dev/rtc0",
				"type" : "c",
				"major" : 251,
				"minor" : 0
			}
		],
		"resources": {
			"cpu": {
				"realtimeRuntime": 950000,
				"realtimePeriod": 1000000
			},
			"devices": [
				{
					"allow": true,
					"access": "rwm"
				},
				{
					"allow": true,
					"type" : "c",
					"major" : 251,
					"minor" : 0,
					"access" : "rwm"
				}
			]
		},
		"namespaces": [
			{
				"type": "pid"
			},
			{
				"type": "ipc"
			},
			{
				"type": "uts"
			},
			{
				"type": "mount"
			}
		]
	}
}``

As you suggested I also tested it with crun and the same config.json --> this worked perfectly fine!

``
root@md3bex3c:/home# crun run s8000
/ # ./realtime
Setting rt prio
Retval: 0, Errno: 0
``

What might be of interest:

**The following I executed on my system:**
``root@md3bex3c:/home# cat /sys/fs/cgroup/cpu/cpu.rt_runtime_us`` --> 950000

**In the crun container:**
``root@md3bex3c:/home# cat /sys/fs/cgroup/cpu/cpu.rt_runtime_us`` --> 950000

**In the podman container:**
``root@md3bex3c:/home# cat /sys/fs/cgroup/cpu/cpu.rt_runtime_us`` --> 0

**Comment by flouthoc** [comment]
@mario19911 One difference is your custom config with `crun/runc` also sets `realtimePeriod` while with podman you aren't doing that could you try with `--cpu-rt-runtime=950000` with `--cpu-rt-period=1000000` .

**Comment by mario19911** [comment]
I tried the following two calls:
**First: just setting the period:**
``podman run -it --mount type=bind,source=realtime,target=/realtime --cap-add all --security-opt seccomp=unconfined --cpu-rt-period=1000000 --entrypoint=/bin/sh rtus/rtum85/04.mj`` --> here I got the same issue when executing the realtime program.

**Second: setting period and runtime:**
``podman run -it --mount type=bind,source=realtime,target=/realtime --cap-add all --security-opt seccomp=unconfined --cpu-rt-period=1000000 --cpu-rt-runtime=950000 --entrypoint=/bin/sh rtus/rtum85/04.mj``

Here I get the error ``Error: OCI runtime error: writing file `cpu.rt_runtime_us`: Invalid argument``

**Comment by giuseppe** [comment]
one difference when you run the container manually is that it is not setting a new group.

Since you are using the cgroupfs, please make sure the parent cgroup has the correct settings, you may need to manually do something like:

```
# echo 950000 > /sys/fs/cgroup/cpu/libpod_parent/cpu.rt_runtime_us
# echo 1000000 > /sys/fs/cgroup/cpu/libpod_parent/cpu.rt_period_us
```

or specify a different `--parent-cgroup`

**Comment by mario19911** [comment]
Thank you very much, with this settings it worked :) 

Just for my understanding - when I use systemd as cgroup manager do I have to do the same?

**Comment by giuseppe** [comment]
> Just for my understanding - when I use systemd as cgroup manager do I have to do the same?

yes, systemd doesn't manage the realtime CPU controller.
