### ISSUE TITLE
Permission error on named volume with docker-compose

### ISSUE THREAD

**Issue by ypconstante** [containers/podman#12421]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When running `docker-compose up` with podman, a named volume has a permission error.
Using podman-compose with podman, or docker-compose with docker, works as expected.
Changing to short syntax with `z` label also works.

**Steps to reproduce the issue:**

1. Clone [https://github.com/ypconstante/docker-elk/](https://github.com/ypconstante/docker-elk/) and checkout commit c96ad60fd8e12befa95b9ad82b1d3708969e5727

2. [Setup docker-compose to use rootless podman](https://fedoramagazine.org/use-docker-compose-with-podman-to-orchestrate-containers-on-fedora/)

3. Run `docker-compose up`

**Describe the results you received:**

```
elasticsearch_1  | ElasticsearchException[failed to bind service]; nested: FileSystemException[/usr/share/elasticsearch/data/nodes: Read-only file system];
elasticsearch_1  | Likely root cause: java.nio.file.FileSystemException: /usr/share/elasticsearch/data/nodes: Read-only file system
```

**Describe the results you expected:**

Service up and running

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.8
Built:        Sat Nov 13 21:16:48 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 12
  distribution:
    distribution: fedora
    variant: cinnamon
    version: "34"
  eventLogger: journald
  hostname: fedora
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.18-200.fc34.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 26295451648
  memTotal: 33481519104
  ociRuntime:
    name: crun
    package: crun-1.3-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.3
      commit: 8e5757a4e68590326dafe8a8b1b4a584b10a1370
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 40m 44.62s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/ypconstante/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 2
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/ypconstante/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 4
  runRoot: /run/user/1000/containers
  volumePath: /home/ypconstante/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 1636849008
  BuiltTime: Sat Nov 13 21:16:48 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.2


```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.2-1.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Can you include a `podman inspect` of a container using the volume? If it's mounted by path, I would expect that SELinux could be a problem.

**Comment by ypconstante** [comment]
I generated this two log files with some commands to compare the two executions.
The volume inspection has the same output for both tools.
When inspecting the containers, I saw that with docker-compose the volume has the RW flag as false, which seems to be the cause of the error I got. 

[podman.log](https://github.com/containers/podman/files/7619707/podman.log)
[docker.log](https://github.com/containers/podman/files/7619708/docker.log)

**Comment by mheon** [comment]
Potentially a volume option issue in the Docker API, then.

**Comment by mheon** [comment]
@jwhonce I think API logs would help here. Is your improved API logging at trace level, or debug level?

**Comment by rhatdan** [comment]
I think this was answered on how to descover, since there has been no recent action, I am going to close.
