### ISSUE TITLE
Permission denied to volume directory in rootless mode

### ISSUE THREAD

**Issue by sebelk** [containers/podman#12427]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Container exists immediately because of entrypoint command exits due permissions/ownership(?) issues.

**Steps to reproduce the issue:**

1. `podman run --rm -p 4100:4100  -v $PWD:/src registry.gitlab.com/mpolitze/backslide-docker:latest serve -s -p 4100`

**Describe the results you received:**
EACCES: permission denied, scandir '/src'

**Describe the results you expected:**

Something as in docker:

```[Browsersync] Access URLs:
 --------------------------------
    Local: http://localhost:4100
 External: http://172.17.0.2:4100
 --------------------------------
[Browsersync] Serving files from: .tmp
[Browsersync] Serving files from: template
[Browsersync] Serving files from: .
[Browsersync] Watching files...


```

**Additional information you deem important (e.g. issue happens only occasionally):**

Some command outputs:

` ` `
$ cat /etc/subgid
sergio:100000:65536

$ ls -ld $PWD
drwxrwxr-x+ 1 sergio sergio 348 nov 27 17:40 /home/sergio/EIT/LinuxOperador/ppts2_bs

$ podman unshare cat /proc/self/uid_map 
         0       1000          1
         1     100000      65536

podman --log-level debug  run --rm -p 4100:4100  -v $PWD:/src registry.gitlab.com/mpolitze/backslide-docker:latest serve -h |& grep -i denied
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied
Cannot start server: EACCES: permission denied, scandir '.tmp'

```
t

**Output of `podman version`:**

```
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.8
Built:        Fri Nov 12 17:25:37 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```

st:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    variant: kde
    version: "35"
  eventLogger: journald
  hostname: munster.belkin.hom
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.18-300.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 23680106496
  memTotal: 33452814336
  ociRuntime:
    name: crun
    package: crun-1.3-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.3
      commit: 8e5757a4e68590326dafe8a8b1b4a584b10a1370
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 2h 13m 27.74s (Approximately 0.08 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/sergio/.config/containers/storage.conf
  containerStore:
    number: 8
    paused: 0
    running: 0
    stopped: 8
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.7.1-2.fc35.x86_64
      Version: |-
        fusermount3 version: 3.10.5
        fuse-overlayfs: version 1.7.1
        FUSE library version 3.10.5
        using FUSE kernel interface version 7.31
    overlay.mountopt: nodev
  graphRoot: /home/sergio/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 12
  runRoot: /run/user/1000/containers
  volumePath: /home/sergio/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 1636748737
  BuiltTime: Fri Nov 12 17:25:37 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.2

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.2-1.fc35.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**


Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

It's a physical machine.

Also I've tried `podman system migrate` without success

**Comment by giuseppe** [comment]
closed as dup of #12428
