### ISSUE TITLE
$GLOBAL_OPTS runlabel is not implemented

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#12436]
`$GLOBAL_OPTS` was added in #2905. Only one month later it got broken, and the test was "temporarily" disabled in #3328:
```
Completely disable global options test
We need to cut a release. We can investigate further next week.
```
Obviously nobody has used this feature since June 2019. It might not be important enough to reimplement. If so, it should be removed from the code and documentation.

Possible reproducer:
```console
$ printf "FROM alpine\nLABEL RUN echo \$GLOBAL_OPTS\n" | bin/podman --log-level error --tmpdir /var/tmp build -t foo:bar -
...
$ bin/podman --log-level error container runlabel RUN foo:bar
[expect: something with `--log-level`. Actual output: nil]
```
(I may have the number of backslashes wrong in the line above. It's impossible to know, because the code doesn't trigger no matter how many backslashes I add).

**Comment by rhatdan** [comment]
GLOBAL_OPTS only works with podman runlabel not with podman build?

**Comment by edsantiago** [comment]
If you find the problem, there's already a test you can un-skip: https://github.com/containers/podman/blob/9af07fd3ed7157f5944c35e83ff96ed8909d7be3/test/e2e/runlabel_test.go#L107-L109

**Comment by vrothberg** [comment]
Thanks!
