### ISSUE TITLE
Allow users to customize storage.conf with a storage.conf.d folder ?

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [containers/podman#12434]
/kind feature

**Description**

Hi,

When testing a scenario of podman inside docker, I ended up needing to change the storage driver to either using vfs, either using overlays with mount_program. In both cases, I need to update the existing file /etc/containers/storage.conf, which (with Fedora at least) seems to be packaged in the "podman" package. Changing a packaged config file is usually not advised. Should a folder /etc/containers/storage.conf.d be added, similarly to /etc/containers/containers.conf.d in order to be able to customize storage.conf with multiple dedicated files ?

Cheers,
Romain

**Comment by giuseppe** [comment]
I think this is a packaging problem.  We need to ship `storage.conf` under `/usr/share/containers/` so that `/etc/containers/storage.conf` can be modified freely.

@lsm5 PTAL

**Comment by rhatdan** [comment]
I agree we need to move to shiping /usr/share/containers/storage.conf

**Comment by rhatdan** [comment]
storage.conf does not inherit fields from other storage.conf files, so making a /etc/containers/storage.d directory makes no sense.

**Comment by rhatdan** [comment]
containers-common-1-36.fc36 now has /usr/share/containers/storage.conf and only ghosts /etc/containers/storage.conf.
I think we will need a change to podman info now.
