### ISSUE TITLE
podman-remote wait: fails with open /proc/PID/cgroup: ENOENT

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#12457]
New podman-remote flake:
```
# # podman-remote [...] wait after_change_cnt
# Error: open /proc/66223/cgroup: no such file or directory
# [ rc=125 (** EXPECTED 0 **) ]
```
### [sys] 166 podman export, alter tarball, re-import
* fedora-34 : sys remote fedora-34 root host [remote]
  * PR #12454
    * [11-30 13:22](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6352096069943296/html/sys-remote-fedora-34-root-host.log.html#t--00166)
  * PR #12433
    * [11-29 11:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5042823440367616/html/sys-remote-fedora-34-root-host.log.html#t--00166)
  * PR #12401
    * [11-29 11:39](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6115760092217344/html/sys-remote-fedora-34-root-host.log.html#t--00166)

**Comment by edsantiago** [comment]
One more:

### Podman run [It] using journald for container with container log_tag
* ubuntu-2110 : int remote ubuntu-2110 root host [remote]
  * PR #12403
    * [11-24 09:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4922925737312256/html/int-remote-ubuntu-2110-root-host.log.html#t--using-journald-for-container-with-container-log_tag--1)

**Comment by giuseppe** [comment]
PR here: container, cgroup: detect pid termination #12464
