### ISSUE TITLE
graphroot and runroot default to current directory

### ISSUE THREAD

**Issue by Hello71** [containers/podman#12467]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

If storage.conf exists but does not contain graphroot or runroot, they will be saved in the database as "." in the first podman invocation, and further invocations will use the current directory for storage.

**Steps to reproduce the issue:**

1. Delete all podman storage.

2. Create storage.conf with the following contents:

```
[storage]
driver = "overlay"
```

2. In an empty directory, run:

```
ls
podman info
ls
podman info
ls
```

**Describe the results you received:**

<details><summary>Output</summary>
<pre>
$ pwd
/tmp/a
$ ls
$ podman info
WARN[0000] Storage configuration is unset - using hardcoded default graph root "/var/lib/containers/storage"
WARN[0000] Storage configuration is unset - using hardcoded default graph root "/var/lib/containers/storage"
WARN[0000] Storage configuration is unset - using hardcoded default graph root "/var/lib/containers/storage"
Error: no storage root specified: missing necessary StoreOptions
$ ls
$ podman info
time="2021-12-01T11:32:33-05:00" level=warning msg="Storage configuration is unset - using hardcoded default graph root \"/var/lib/containers/storage\""
time="2021-12-01T11:32:33-05:00" level=warning msg="Storage configuration is unset - using hardcoded default graph root \"/var/lib/containers/storage\""
time="2021-12-01T11:32:33-05:00" level=warning msg="Storage configuration is unset - using hardcoded default graph root \"/var/lib/containers/storage\""
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: app-emulation/conmon-2.0.30
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.30, commit: v2.0.30'
  cpus: 12
  distribution:
    distribution: gentoo
    version: "2.8"
  eventLogger: journald
  hostname: alex-desktop
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.16.0-rc3-00056-gc679e0bcffc1
  linkmode: dynamic
  logDriver: journald
  memFree: 10379485184
  memTotal: 16721362944
  ociRuntime:
    name: crun
    package: app-emulation/crun-1.2
    path: /usr/bin/crun
    version: |-
      crun version 1.2
      commit: 4f6c8e0583c679bfee6a899c05ac6b916022561b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: app-emulation/slirp4netns-1.1.12
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 1h 9m 37.3s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
  - registry.fedoraproject.org
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /tmp/a
  graphStatus:
    Backing Filesystem: tmpfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /tmp/a
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 1638116867
  BuiltTime: Sun Nov 28 11:27:47 2021
  GitCommit: ""
  GoVersion: go1.17.2
  OsArch: linux/amd64
  Version: 3.4.2
$ ls
mounts  overlay  overlay-containers  overlay-images  overlay-layers  overlay-locks  storage.lock  tmp  userns.lock
</pre>
</details>

**Describe the results you expected:**
Podman does not use the current directory for storage.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.17.2
Built:        Sun Nov 28 11:27:47 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

See above.

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
[binary   R    ] app-emulation/podman-3.4.2-1::gentoo  USE="-apparmor -btrfs -fuse -rootless (-selinux)" 0 KiB
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by flouthoc** [comment]
@Hello71 Above PR should close this.
