### ISSUE TITLE
Docker incompatbility: status message on streamed push

### ISSUE THREAD

**Issue by leahneukirchen** [containers/podman#12468]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Different status string formatting for the compat API than in Docker.

**Steps to reproduce the issue:**

When using the compat API to push an image, podman responds with a status like this:
```
{"status":"mytag: digest: sha256:ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"}
```

However, Docker responds with
```
{"status":"mytag: digest: sha256:ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff size: 1234"}
```

This caused a bug in production software that assumed `size:` is included too.

If you think API differences like this are out of scope for Podman, please close as invalid and I'll stop reporting them.

**Describe the results you received:**

The `status` field has no `size:`.

**Describe the results you expected:**

The status field contains `size: 1234`, like in Docker.

**Output of `podman version`:**

```
podman version 3.4.2

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes, same code in HEAD.

**Comment by rhatdan** [comment]
This seems like a legitimate bug.
