### ISSUE TITLE
docker-compose-like syntax for podman play kube 

### ISSUE THREAD

**Issue by jawnsy** [containers/podman#12475]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Users frequently want a simplified way to develop applications consisting of multiple services. For applications deployed into Kubernetes, users frequently use tools like kind, k3d, or minikube, to create a Kubernetes cluster into which to deploy their application. These tools introduce all the power, but also complexity, of Kubernetes.

`podman play kube` is analogous, in some ways, to `docker-compose`: both tools can start and stop groups of related containers, which frequently constitute parts of a microservice application. This technique for starting multiple containers as a group, defined in a single YAML configuration file, may be a suitable replacement for a full Kubernetes cluster for a subset of Kubernetes applications.

`kubectl` and `docker-compose` have a syntax that that is "isomorphic." For example, `kubectl create -f` and `kubectl delete -f` on the same file are effectively the inverse operations of each other. If you create resources using `kubectl create -f` and a manifest file, the inverse operation (`kubectl delete -f`) should delete everything as well. Similarly, `docker-compose` supports both `up` (running all containers) and `down` (stop all containers) commands. This similarity makes things easier for users to learn and use.

By contrast, `podman play kube` uses a special `--down` flag to perform the inverse operation, which might be confusing, as not all the same flag values are applicable to both. It also does not seem like tearing a deployment down is a special case of `play` operation, but rather, a separate operation entirely.

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Version:      3.4.1
API Version:  3.4.1
Go Version:   go1.17.2
Built:        Wed Dec 31 16:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
Please describe the syntax you would like?

**Comment by rhatdan** [comment]
Or better yet open a PR.

**Comment by jawnsy** [comment]
@rhatdan Thanks for triaging! I'd be happy to open a PR, and we can do it in a compatible way by adding the commands alongside the existing ones, as an alias. Perhaps something like:

```bash
# run the containers in the manifest file.yaml
podman kube up -f file.yaml
# run the containers in a manifest with a default name, like podman-kube.yaml
podman kube up
# then the inverse operations would destroy the pods
podman kube down
podman kube down -f file.yaml
```

It may be preferable to maintain the current hierarchy, in which case we could do `podman play kube up` etc.

As a separate item (#12476), we could consider adding `podman play compose up` to run a docker-compose.yaml file through kompose, and then do the same thing as kube play. In theory this would mean that the whole docker-compose ecosystem would become available for podman users.

**Comment by rhatdan** [comment]
Yes I would prefer podman play kube up and podman play kube down.
Isn't docker-compose (2) now a separate package?  Could podman play compose just use that and exec the docker-compose package?

**Comment by mheon** [comment]
Even better, it's a Docker CLI plugin - if we were to implement that API, we'd have it integrated natively.

We'd still need to resolve the other blockers for Compose v2.0 support first, of course.

**Comment by vrothberg** [comment]
@baude PTAL

I am mostly worried about (yet another) breaking change to existing users. @Luap99, as the cobra expert in team: Is it possible to add sub-commands as described here (i.e., `play-kube-{up,down}`) AND to main the current flags of `play-kube`?

Having written that, it seems like a recipe to create more confusion by mixing apples and oranges.  I sympathize with the suggestion but I am not convinced it's worth a breaking change.

@containers/podman-maintainers PTAL

**Comment by Luap99** [comment]
Yes it should be possible to do this without breaking changes. You would need to create new cobra commands and then you just export the run function and the flag definitions and add them to the new commands.

I personally like `podman kube play` and `podman kube down`. Adding extra features such as the default filename can be added later.

**Comment by mheon** [comment]
I'm a little more in favor of keeping existing subcommand structure, so kmaybe `podman play kube` and `podman down kube` (or even a subcommand of `podman stop`? `podman stop kube`?)

**Comment by Luap99** [comment]
`podman stop kube` is not possible, the cli parser cannot know if kube is a subcommand or the container name used for `podman stop`

**Comment by rhatdan** [comment]
podman down kube seems like a nice compromise.

**Comment by jawnsy** [comment]
Moving [this comment](https://github.com/containers/podman/pull/13295#issuecomment-1046675512) from @vrothberg on the PR here since the rest of the discussion was happening in this issue. The proposed `podman kube [up|down|generate]` command syntax [was supported](https://github.com/containers/podman/pull/13295#issuecomment-1046980370) by @mheon:

> Independent of this PR. I think we should reflect on how to name the commands. I would love to have a `podman kube down` instead of `down kube` (similar to the container, image and pod sub-commands).
> 
> `play kube` and `generate kube` could then be aliases for `kube play/generate`.

I don't personally have any opinion and will defer to you all as the maintainers on the preferred implementation approach. Once we have more consensus on the preferred design, I'll update the PR accordingly. Since this will be part of Podman's API, changing it once merged will be difficult (i.e. this is a difficult-to-reverse decision), and it is thus important that we all agree on the approach.

Thanks everyone for your support getting this feature implemented!

**Comment by rhatdan** [comment]
We should have this discussion at a Cabal meeting.
podman generate kube| systemd (Makes sense to me.
But if we add a podman kube command, then I think we would need

podman kube generate|up|down
Would we want 
podman systemd generate?

**Comment by jawnsy** [comment]
@rhatdan Since there's been a flurry of review activity on the PR (thanks all!), I wanted to ask: do you want me to hold off on this work until the next Podman Community Cabal meeting? I suppose I just missed the meeting last Thursday (Feb 17) according to the [community meeting page](https://podman.io/community/meeting/), and presumably the next one will be around March 17th timeframe?

I can also speculatively just do `podman kube generate|up|down` and change it later if necessary, since it's not a huge amount of work to shuffle things around

**Comment by vrothberg** [comment]
> Would we want podman systemd generate?

I think that `generate kube/systemd` is fine since we are generating data. `generate kube` should alias to `kube generate` though, just to make sure all kube-things would live behind `podman kube ...`.

**Comment by rhatdan** [comment]
@jawnsy No I think you can go forward with your commands, I think we have come to consensus and these are better the podman play kube.

**Comment by vrothberg** [comment]
I agree. We can do the changes after your PR has merged.

**Comment by rhatdan** [comment]
once we get done with bugfix mode, we should tackle this rework of the cobra CLI

**Comment by vrothberg** [comment]
@nicrowe00 PTAL

**Comment by giuseppe** [comment]
with the `podman play` syntax we can add more ways to create pods/containers (e.g. we have a open PR like https://github.com/containers/podman/pull/14729).

We have:

- podman generate (kube|systemd)
- podman play (kube)

We could add a new command `podman down (kind)` and it will be cleaner than a `podman kube` specific subcommand

**Comment by vrothberg** [comment]
@giuseppe, we are more looking into consolidating all kube-related things into `podman kube` (see https://github.com/containers/podman/issues/12475#issuecomment-1047546589).
