### ISSUE TITLE
docker-compose support for podman play

### ISSUE THREAD

**Issue by jawnsy** [containers/podman#12476]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Many users use docker-compose for building applications consisting of multiple containers. While `podman play kube` can do the same things, it requires users to first convert their files over to Kubernetes deployment syntax.

A tool like `kompose` is helpful for converting the docker-compose.yml file into Kubernetes syntax, which `podman play kube` likely supports, but it would be convenient to have the capability to do this automatically. For example, we could introduce a `podman play compose` command that would take a docker-compose file, translate it into Kubernetes syntax, then run `podman play kube` on the result.

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
I am fine with this, if the community wants to take it on.  Since `docker compose` now exists, I would not be surprised if we are pushed to add support for this.

**Comment by vrothberg** [comment]
I am skeptical since we had to translate one format to another, neither of which we control. Those are moving targets. Since there is already `kompose`, I would prefer to leave it up to this tool support translating compose files into K8s yaml.

In other words, I'd appreciate if we wouldn't have to support this scenario and once something has merged, we effectively support it.

@containers/podman-maintainers PTAL

**Comment by Luap99** [comment]
Right supporting/debugging this will be a nightmare.
I think it is more favourable to support `podman compose` directly than converting the file format to k8s yaml first. Compose V2 is a docker cli plugin so adding it to podman should be possible.

**Comment by rhatdan** [comment]
I agree, I would prefer to just support podman compose with the docker-compose plugin.

**Comment by jawnsy** [comment]
Fair enough, thanks for your consideration!
