### ISSUE TITLE
Permission denied when signing image

### ISSUE THREAD

**Issue by aurany** [containers/podman#12494]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I get this error message when i'm trying to push and sign an image. "Error: creating signature: Permission denied". Not sure if this is a "local" problem (like writing to wrong folders) or if it´s related to the repository.

**Steps to reproduce the issue:**

1. Login as rootless
2. podman pull docker.io/alpine
3. podman tag docker.io/alpine myrepo/myimage:latest
4. podman login myrepo -u myuser -p mypass
5.  podman push --tls-verify=false --log-level=debug --authfile=$XDG_RUNTIME_DIR/containers/auth.json --sign-by=mymail@mycompany.se myrepo/myimage:latest

**Describe the results you received:**

last rows from debug:

...
Signing manifest
DEBU[0001] Looking up image "myrepo/testimage:v0.12" in local containers storage
DEBU[0001] Trying "myrepo/testimage:v0.12" ...
DEBU[0001] parsed reference into "[overlay@/home/myusername/.local/share/containers/storage+/run/user/myuserid/containers:overlay.mount_program=/usr/bin/fuse-overlayfs,overlay.mount_program=/usr/bin/fuse-overlayfs]@c059bfaa849c4d8e4aecaeb3a10c2d9b3d85f5165c66ad3a4d937758128c4d18"
DEBU[0001] Found image "myrepo/testimage:v0.12" as "myrepo/testimage:v0.12" in local containers storage
Error: creating signature: Permission denied

**Describe the results you expected:**

Files should be written to the sigstore folder? This folder is empty.
Image is beeing pushed to repo but i guess it's not signed correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**

cat .config/containers/registries.d/default.yaml
```
default-docker:
  #sigstore: http://myrepo
  sigstore-staging: file:///home/myusername/.local/share/containers/sigstore
```

**Output of `podman version`:**

```
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.7
Built:        Tue Sep 21 10:41:42 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.22.3
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.module+el8.5.0+12582+56d94c81.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 0f5bee61b18d4581668e5bf18b910cda3cff5081'
  cpus: 1
  distribution:
    distribution: '"rhel"'
    version: "8.5"
  eventLogger: file
  hostname: <myhostname>
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 16025
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: myuserid
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-348.2.1.el8_5.x86_64
  linkmode: dynamic
  memFree: 30299176960
  memTotal: 33512665088
  ociRuntime:
    name: runc
    package: runc-1.0.2-1.module+el8.5.0+12582+56d94c81.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.2
      spec: 1.0.2-dev
      go: go1.16.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/myuserid/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.5.0+12582+56d94c81.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 2147479552
  swapTotal: 2147479552
  uptime: 16h 44m 11.58s (Approximately 0.67 days)
registries:
  docker.io:
    Blocked: false
    Insecure: false
    Location: myrepo/docker-registry-1.docker.io
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: docker.io
  k8s.gcr.io:
    Blocked: false
    Insecure: false
    Location: myrepo/docker-k8s.gcr.io
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: k8s.gcr.io
  quay.io:
    Blocked: false
    Insecure: false
    Location: myrepo/docker-quay.io
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: quay.io
  registry.access.redhat.com:
    Blocked: false
    Insecure: false
    Location: myrepo/docker-registry.redhat.io
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: registry.access.redhat.com
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/myuserid/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.7.1-1.module+el8.5.0+12582+56d94c81.x86_64
      Version: |-
        fusermount3 version: 3.2.1
        fuse-overlayfs: version 1.7.1
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/myuserid/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/user/myuserid/containers
  volumePath: /home/myuserid/.local/share/containers/storage/volumes
version:
  APIVersion: 3.3.1
  Built: 1632213702
  BuiltTime: Tue Sep 21 10:41:42 2021
  GitCommit: ""
  GoVersion: go1.16.7
  OsArch: linux/amd64
  Version: 3.3.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.3.1-9.module+el8.5.0+12697+018f24d7.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Not possible, only allowed to use official RHEL packages

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Virtual linux machine, on prem
SELinux=Enforcing (same error in permissive-mode)

**Comment by rhatdan** [comment]
@mtrmac PTAL

**Comment by rhatdan** [comment]
This might be podman image sign trying to write to a system directory?

**Comment by mtrmac** [comment]
This is not writing/uploading signatures, this really is a failure _creating_ the signature. It looks like a failure somewhere in/below GPGMe . Running the command under `strace -ff`, or maybe using the `GPGME_DEBUG` variable might reveal more. (I didn’t try reproducing it now.)

> Not possible, only allowed to use official RHEL packages

Consider also contacting official RH support if you are a customer.

**Comment by aurany** [comment]
Thanks @rhatdan and @mtrmac! This was not an issue with podman. I believe this error occured when GPG tries to open the password prompt which was not permitted. I solved it by adding "allow-loopback-pinentry" to gpg-agent.conf.
