### ISSUE TITLE
OCI permission denied when using --subuidname and a bind mount

### ISSUE THREAD

**Issue by MidnessX** [containers/podman#12508]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Trying to run a container using a UID mapping and a bind mount fails with message:
```Error: error stat'ing file `/home/myuser/testdir`: Permission denied: OCI permission denied```

Podman is run as root and the UID mapping to use is specified via the flag:
```--subuidname myuser```
and the volume is mounted with:
```-v /home/myuser/testdir:/mnt/testdir:Z```

**Steps to reproduce the issue:**

1. ```# adduser myuser``` (this also creates a new entry in ```/etc/subuidmap```)

2. *Optional:* ```# cat /etc/subuid``` (to check that an entry for ```myuser``` exists; in my case, it is ```myuser:100000:65536```)

3. ```# mkdir /home/myuser/testdir```

4. ```# chown myuser:myuser /home/myuser/testdir```  

5. ```# podman run -it --rm --subuidname myuser -v /home/myuser/testdir:/mnt/testdir:Z fedora:latest```

**Describe the results you received:**

```Error: error stat'ing file `/home/myuser/testdir`: Permission denied: OCI permission denied```

**Describe the results you expected:**

The container is started.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.8
Built:        Fri Nov 12 21:25:37 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 4
  distribution:
    distribution: fedora
    variant: server
    version: "35"
  eventLogger: journald
  hostname: server-1
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.10-300.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 15199875072
  memTotal: 16512626688
  ociRuntime:
    name: crun
    package: crun-1.3-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.3
      commit: 8e5757a4e68590326dafe8a8b1b4a584b10a1370
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 16m 43.17s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 1636748737
  BuiltTime: Fri Nov 12 21:25:37 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.2-1.fc35.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine running Fedora Server 35 (I've tried both using up-to-date packages and those available after OS install).

If I run the container with ```--uidmap 0:1000:65536``` the container starts successfully.
If, however, I try to use the same  range as in ```/etc/subuid``` by running ```--uidmap 0:100000:65536```, I get the same error.

Thank you in advance for your time!

**Comment by Luap99** [comment]
If you use `--subuidname` it will map the range from /etc/subuid, in your example this range `0:100000:65536`. This means that the uid 100000 on the host is mapped to uid 0 in the container with a range of 65536. Your homedir is owned by uid 1000 so the container has no access rights to this directory because the uid is not mapped into the user namespace.

If you want to mirror the rootless user namespace you need `--uidmap 0:1000:1  --uidmap 1:100000:65536`
