### ISSUE TITLE
init_process = override on command line

### ISSUE THREAD

**Issue by doverride** [containers/podman#12539]
I would argue that if you specifiy `--security-opt label=type:foo` that this should then also apply to `init_process`. Currently it does not. We cannot manually override the 
'init_process = ""' entry from `lxc_contexts` like we can override the 'process = ""' entry from `lxc_contexts`.

Either the above or maybe add a `--security-opy label=init-type:foo` so that we can override the default from `lxc_contexts`

**Comment by rhatdan** [comment]
Containers with container_init_t have different permissions then processes with container_t

**Comment by rhatdan** [comment]
podman run --security-opt label=type:spc_t ubi8-init
Shows me systemd running as spc_t?

Which seems to work in main branch
```
$ podman run --security-opt label=type:spc_t --systemd=always ubi8-init cat /proc/self/attr/current 
system_u:system_r:spc_t:s0:c932,c944
$ podman run --systemd=always ubi8-init cat /proc/self/attr/current 
system_u:system_r:container_init_t:s0:c189,c526
$ rpm -q podman 
podman-3.4.2-1.fc34.x86_64
```

**Comment by doverride** [comment]
hmm not here...
```
root@bullseye2:~# dpkg -l | grep podman
ii  podman                                           3.0.1+dfsg1-3+b2               amd64        engine to run OCI-based containers in Pods
```

**Comment by rhatdan** [comment]
You are using SELinux?

What do these two commands output? 
$ podman run --systemd=always ubi8-init cat /proc/self/attr/current 
$ podman run --security-opt label=type:spc_t --systemd=always ubi8-init cat /proc/self/attr/current

**Comment by doverride** [comment]
Daniel J Walsh ***@***.***> writes:

> You are using SELinux?

Yes

>
> What do these two commands output?
> $ podman run --systemd=always ubi8-init cat /proc/self/attr/current
> $ podman run --security-opt label=type:spc_t --systemd=always ubi8-init cat
> /proc/self/attr/current

The output is identical for both. I will try a newer version of Podman,
maybe the issue was addressed in a later version.

>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
>

-- 
gpg --locate-keys ***@***.***
Key fingerprint = FCD2 3660 5D6B 9D27 7FC6  E0FF DA7E 521F 10F6 4098
Dominick Grift

**Comment by rhatdan** [comment]
What label would podman choose if the installer did not install the default label. If you notice the entire /etc/selinux/contexts directory is default labels according the the policy that is installed.  Hard coding SELinux types into code is frowned upon.

Yes if you disable SElinux by default it should work.

**Comment by doverride** [comment]
Podman would not choose a label at all, That is the point. You would be able to let SELinux take care of transitions manually.

Imagine this scenario. Some once said "confining the unconfined (unconfined_t) is a oxymoron" but by relying on "process =" in "lxc_contexts" you do not have much of a choose.

unconfined_t will transition to the domain specified there by default instead of just running the container in unconfined_t. Granted he is able to override that behavior on the Podman command line but its not the default behavior.

That is why I do not understand why Podman relies on lxc_contexts. Because now you cannot just disable the podman default label and rely on automatic SELinux transtiions and still give people to option to override the automatic transition with a manual transition on the Podman command line.

Also I was not asking whether Podman works for you "with selinux disabled". I was asking instead if Podman works with:

cat >> /etc/containers//containers.conf <<EOF
[[Containers]]
label=disable
EOF

**Comment by rhatdan** [comment]
SELinux when disabled does rely on transitioning, as well as when lxc_contexts file does not exists.  The issue is that all images are labeled the same so transition is setup to spc_t.

$ sesearch -T -s container_runtime_t | grep spc_t
type_transition container_runtime_t container_file_t:process spc_t;
type_transition container_runtime_t container_ro_file_t:process spc_t;
type_transition container_runtime_t container_var_lib_t:process spc_t;
type_transition container_runtime_t fusefs_t:process spc_t;
type_transition container_runtime_t unlabeled_t:process spc_t;

If you want to attempt to get one of the executables in one of these directories to a different label, then you could transition to different types. It is just not easy to do.

**Comment by doverride** [comment]
Daniel J Walsh ***@***.***> writes:

> SELinux when disabled does rely on transitioning, as well as when lxc_contexts file does not
> exists. The issue is that all images are labeled the same so transition is setup to spc_t.

Nice. That is indeed what I meant, and it goes to the heart of my
issue.

By removing lxc_contexts you disable Podman SELinux awareness
unconditionally. In other words: lxc_contexts is a hard requirement for
Podman SELinux awareness.

That means that you cannot default to automatic transitions without
losing the ability to support --security-opt label, and the "process="
entry in lxc_contexts would always's take precendence. (manual
transitions override automatic transitions)

I much rather have podman behave like SELinux does in that sense and:
allow manual transitions to override existing automatic transitions.

That lxc_contexts file has "proceess =" but not every process is
equal. Rootless containers do no need capabilities where rootful
containers often do. So now you have pretty much everyone transition to
what ever domain specified in "process=" by default.



>
> $ sesearch -T -s container_runtime_t | grep spc_t
> type_transition container_runtime_t container_file_t:process spc_t;
> type_transition container_runtime_t container_ro_file_t:process spc_t;
> type_transition container_runtime_t container_var_lib_t:process spc_t;
> type_transition container_runtime_t fusefs_t:process spc_t;
> type_transition container_runtime_t unlabeled_t:process spc_t;
>
> If you want to attempt to get one of the executables in one of these directories to a different
> label, then you could transition to different types. It is just not easy to do.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
>

-- 
gpg --locate-keys ***@***.***
Key fingerprint = FCD2 3660 5D6B 9D27 7FC6  E0FF DA7E 521F 10F6 4098
Dominick Grift

**Comment by doverride** [comment]
defaulting to no manual transitions, and providing the option to override any existing automatic transitions define in policy is more flexible than defaulting to some label manually (and thereby by default overriding any existing automatic transitions defined in policy.

I could tell SElinux to make this the default:

init_t -> (podman_exec-t)podman_t -> (crun_exec_t)crun_t -> (container_file_t)container_t
unconfined_t -> (podman_exec_t)unconfined_t -> (crun_exec_t)unconfined_t ->(fusefs_t)unconfined_t

Easy, flexible and intuitive  Then you can allow people to override that default behavior on the command line.

Now I get defaults forced on me that are really only suitable for one scenario (one size fits no one).

Manual transitions override automatic transitions. As soon as one relies on a manual transition one essentially removes the ability to support automatic transitions unless SELinux awareness is disabled altogether, at which point you cannot override the automatic transitions with manual transitions anymore either.

Between a rock and a hard place....

**Comment by doverride** [comment]
Please do not disable Podman labeling functionality when no (valid) lxc_contexts exists. If no (valid) lxc_contexts exists then just do not manually label anything by default (because it means that the administrator opted to take care of the defaults via automatic SELinux transitions)

**Comment by rhatdan** [comment]
If  you disable SELinux containerization support, you get what you want. (I happen to disagree with what you want.)

You can do this for Podman by changing the label field in containers.conf to false.

```
grep -i label /usr/share/containers/containers.conf 
# label tells the container engine whether to use container separation using
# MAC(SELinux) labeling or not.
# The label flag is ignored on label disabled systems.
#label = true
```
Then SELinux will rely on transition rules like you desire.

The problem with this is that all containers will run with the same label if they use the same transition rules.  This means all containers can attack each other.

In my opinion each container running within its own TYPE along with a unique MCS label, gives the best flexibility, usability, and security. Which is why we default to it.

**Comment by doverride** [comment]
Its not about relying.. its about exercising control over the default behavior

if i do what you say then --security-opt label= will no longer be respected

anyway,  never mind. will make do with the current state.

**Comment by rhatdan** [comment]
Yes --security-opt label=disable will be the default.  You can still activate it if you want. But you would need to specify the types you want your containers to run with.

**Comment by doverride** [comment]
Daniel J Walsh ***@***.***> writes:

> Yes --security-opt label=disable will be the default. You can still activate it if you want. But you would
> need to specify the types you want your containers to run with.

If that is the case then that would also solve my issue (although its
not really transparent as it requires that user adds that to
containers.conf whereas if it would just behave like that if
lxc_contexts is unreadable, then i wouldnt have to rely on user
intervention)

Will try it out, thanks

>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android. 
>

-- 
gpg --locate-keys ***@***.***
Key fingerprint = FCD2 3660 5D6B 9D27 7FC6  E0FF DA7E 521F 10F6 4098
Dominick Grift
