### ISSUE TITLE
podman run config log-driver to syslog

### ISSUE THREAD

**Issue by Loches525** [containers/podman#12537]
Does Podman support to config log-driver to syslog like Docker when run the comman "podman run "? Currently will prompt "Invalid log driver" error.

Podman version: 3.2.3

**Comment by rhatdan** [comment]
No currently Podman only supports k8s-file, journald, and none.

Won't journald driver work for you?  Why do you need the syslog driver?

**Comment by Loches525** [comment]
> 

As we need to collect the container log from system log and it' better that podman can directly generate the log to that position. Any other ways to meet this requirement?

**Comment by vrothberg** [comment]
journald supports forwarding to syslog (see https://www.loggly.com/ultimate-guide/centralizing-with-syslog/).  I haven't tried but that should allow for using `journald` log-driver in Podman.

**Comment by PavelSosin-320** [comment]
@vrothberg Could you revisit this issue and check that conmon uses syslog logging correctly? It ignores all configurations and options of logging destination and always says that the logging will be done to syslog.  Then on Fedora 36 the podman start of existing containers command fails with message "got -1' and "OCI access denied" after conmon starts. I just found the Fedora 36 WS has no rsyslog installed out-of-the-box. Unlike journal the system log never contains any recording about podman's activity starting from Podman 3.4 on Fedora 35.

**Comment by PavelSosin-320** [comment]
@vrothberg P.S. In opposite to the Dan's post in the podman's archives the relations between journald and syslog in the Fedora 36 WS are the following: journald socket is available for writing to everybody and then the log stream can be redirected to any logging destination including r(emote)syslog  using journald.conf adjustment. Syslog socket is located in the /run/systemd/journal/dev-log (via /dev/log slink). Access to dev-log is much more restricted and its node is labeled as object_r:r:devlog_t:s0. I didn't revise podman's behavior but installation of rsyslog and redirection log from journald to syslogd looks not harmful. Unfortunately. podman prioritize syslog also when /run/sytemd/journal/socket can be stat'ed
