### ISSUE TITLE
`podman machine start` freezes on "fails with -accel hvf: invalid accelerator hvf"

### ISSUE THREAD

**Issue by judaew** [containers/podman#12536]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Exec `podman machine start` on M1 with QEMU builded without the `hvf` accelerator.

**Describe the results you received:**

QEMU freezes here:

```console
$ podman machine start
INFO[0000] waiting for clients...
INFO[0000] listening tcp://0.0.0.0:7777
INFO[0000] new connection from  to /var/folders/l0/kfvj485d0lq_0syf2b86b5rh0000gn/T/podman/qemu_podman-machine-default.sock
Waiting for VM ...
qemu-system-aarch64: -accel hvf: invalid accelerator hvf
qemu-system-aarch64: falling back to tcg
```

See https://trac.macports.org/ticket/64131 and https://github.com/macports/macports-ports/pull/13267

**Describe the results you expected:**

If the `hvf` accelerator is not available, then the next one is used.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman --version`:**

```
podman version 3.4.3
```

**Output of `podman info --debug`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v3.4.3/libpod/_ping": dial unix ///var/folders/wf/1v73g2h55x32pt1n0njr27v00000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```console
$ port info podman
podman @3.4.3 (sysutils)

Description:          Podman is a tool for running Linux containers. You can do this
                      from a MacOS desktop as long as you have access to a linux box
                      either running inside of a VM on the host, or available via the
                      network. You need to install the remote client and then setup ssh
                      connection information.
Homepage:             https://github.com/containers/podman

Build Dependencies:   go
Runtime Dependencies: gvisor-tap-vsock, qemu
Platforms:            darwin
License:              Apache-2
Maintainers:          Email: judaew@macports.org, GitHub: judaew
                      Policy: openmaintainer
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

QEMU:

```console
$ qemu-system-aarch64 --version
QEMU emulator version 6.1.0
Copyright (c) 2003-2021 Fabrice Bellard and the QEMU Project developers

$ qemu-system-aarch64 -accel help
Accelerators supported in QEMU binary:
tcg
```

**Comment by judaew** [comment]
I don't know why QEMU freezes up instead of choosing another accelerator. Perhaps, in this case, as a workaround, you can check the output of the command `qemu-system-aarch64 -accel help`, and based on the output, compose the variable opts.

https://github.com/containers/podman/blob/3b21ba2f623da5a4228a6236c684d1d0b245f240/pkg/machine/qemu/options_darwin_arm64.go#L13-L23

**Comment by rhatdan** [comment]
Since we never got further feedback, I am going to close.
