### ISSUE TITLE
Using `pkg/bindings` Go API should not require native dependencies to be installed

### ISSUE THREAD

**Issue by strideynet** [containers/podman#12548]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

As it stands, building an application that uses Podman via the HTTP API  client (`pkg/bindings`) requires native dependencies (e.g `libbtrfs`, `libgpgme` etc) to be available on the machine.  This provides a poor developer experience, especially to those on operating systems other than Linux where they may struggle to source the dependencies, and makes building applications that use this API much more difficult (these dependencies must also be installed as part of CI pipelines etc). As an engineer, I am unable to understand why I need these dependencies to leverage this API client, as they don't seem reasonable dependencies for an API client that makes HTTP requests (e.g `libbtrfs`).

We should explore options that would mean it's possible to use this API without the installation of those native dependencies. As far as I can tell, this is caused by the bindings packages relying on types defined in other packages where those dependencies are required as part of the runtime. If these types were extracted, or copied, and placed in separate packages, it should be possible to build applications using the Podman API Client without installing those native dependencies.

Many thanks,

**Comment by rhatdan** [comment]
We build the remote client with these golang build tags, which should remove most of the heinous stuff you are seeing.

REMOTETAGS ?= remote exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper containers_image_openpgp

Sure we would love to get rid of these bindings leakage, but it is fairly difficult to do, and we have not recently had the engineering time to look into it.

**Comment by strideynet** [comment]
Thanks @rhatdan for providing a work-around, that's greatly appreciated. I'll give that a go in tomorrow's working hours and see if that resolves the issue <3

Does it seem reasonable to you to keep this ticket open long term to track this until the root issue is resolved ?

**Comment by strideynet** [comment]
Interestingly, providing these flags allows me to build, run, and test unless I enable race detection, which then causes a rather interesting cgo error:

```
noah@Noahs-MBP ~/c/k/k/korulet (podman-build-flags)> go test -tags="remote exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper containers_image_openpgp" -race ./containers
objc[51220]: Attempt to use unknown class 0x7ff85284c360.
SIGABRT: abort
PC=0x7ff811018dfe m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4df5330, 0xc00061f118)
        /usr/local/go/src/runtime/cgocall.go:156 +0x6e fp=0xc00061f0f0 sp=0xc00061f0b8 pc=0x4006dae
os/user._Cfunc_mygetpwuid_r(0x1f5, 0xc0004ac280, 0xf808200, 0x1000, 0xc000010278)
        _cgo_gotypes.go:181 +0x85 fp=0xc00061f118 sp=0xc00061f0f0 pc=0x4424ac5
os/user.lookupUnixUid.func1.1(0x1f5, 0x6625108, 0xc000476d50, 0x590f4a0)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:105 +0xdc fp=0xc00061f180 sp=0xc00061f118 pc=0x4425d9c
os/user.lookupUnixUid.func1()
        /usr/local/go/src/os/user/cgo_lookup_unix.go:105 +0x5e fp=0xc00061f1d8 sp=0xc00061f180 pc=0x4425c9e
os/user.retryWithBuffer(0xc000476d50, 0xc00061f330)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:249 +0x42 fp=0xc00061f238 sp=0xc00061f1d8 pc=0x4426ec2
os/user.lookupUnixUid(0x1f5)
        /usr/local/go/src/os/user/cgo_lookup_unix.go:98 +0x1de fp=0xc00061f368 sp=0xc00061f238 pc=0x44259be
os/user.current()
        /usr/local/go/src/os/user/cgo_lookup_unix.go:51 +0x2a fp=0xc00061f398 sp=0xc00061f368 pc=0x4424f2a
os/user.Current.func1()
        /usr/local/go/src/os/user/lookup.go:15 +0x2a fp=0xc00061f3c8 sp=0xc00061f398 pc=0x4426fea
sync.(*Once).doSlow(0x590dea0, 0x5087938)
        /usr/local/go/src/sync/once.go:68 +0x128 fp=0xc00061f4b0 sp=0xc00061f3c8 pc=0x407f4c8
sync.(*Once).Do(0x590dea0, 0x0)
        /usr/local/go/src/sync/once.go:59 +0x47 fp=0xc00061f4d8 sp=0xc00061f4b0 pc=0x407f367
os/user.Current()
        /usr/local/go/src/os/user/lookup.go:15 +0x38 fp=0xc00061f520 sp=0xc00061f4d8 pc=0x4424118
os/user.Lookup({0x503a7fe, 0x40725c5})
        /usr/local/go/src/os/user/lookup.go:33 +0x31 fp=0xc00061f580 sp=0xc00061f520 pc=0x4424251
github.com/containers/storage/pkg/chrootarchive.init.0()
        /Users/noah/go/pkg/mod/github.com/containers/storage@v1.36.0/pkg/chrootarchive/archive.go:23 +0x36 fp=0xc00061f5c0 sp=0xc00061f580 pc=0x4a995d6
runtime.doInit(0x588ada0)
        /usr/local/go/src/runtime/proc.go:6498 +0x123 fp=0xc00061f6f8 sp=0xc00061f5c0 pc=0x4049be3
runtime.doInit(0x588b520)
        /usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc00061f830 sp=0xc00061f6f8 pc=0x4049b31
runtime.doInit(0x588f220)
        /usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc00061f968 sp=0xc00061f830 pc=0x4049b31
runtime.doInit(0x588d680)
        /usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc00061faa0 sp=0xc00061f968 pc=0x4049b31
runtime.doInit(0x588fa00)
        /usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc00061fbd8 sp=0xc00061faa0 pc=0x4049b31
runtime.doInit(0x58871e0)
        /usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc00061fd10 sp=0xc00061fbd8 pc=0x4049b31
runtime.doInit(0x588cd80)
        /usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc00061fe48 sp=0xc00061fd10 pc=0x4049b31
runtime.doInit(0x587f0a0)
        /usr/local/go/src/runtime/proc.go:6475 +0x71 fp=0xc00061ff80 sp=0xc00061fe48 pc=0x4049b31
runtime.main()
        /usr/local/go/src/runtime/proc.go:238 +0x1e6 fp=0xc00061ffe0 sp=0xc00061ff80 pc=0x403c506
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00061ffe8 sp=0xc00061ffe0 pc=0x406f921

rax    0x2000209
rbx    0x80
rcx    0x7ff7bfefe578
rdx    0x0
rdi    0x8
rsi    0x1
rbp    0x7ff7bfefe5c0
rsp    0x7ff7bfefe578
r8     0x600002c00000
r9     0x80
r10    0x0
r11    0x246
r12    0x0
r13    0x0
r14    0x1
r15    0x8
rip    0x7ff811018dfe
rflags 0x246
cs     0x7
fs     0x0
gs     0x0
```

**Comment by strideynet** [comment]
I can confirm that applying these build flags resolves the need to install the native dependencies. It feels like it could be potentially helpful to others to include these instructions in the documentation regarding the API client.

**Comment by rhatdan** [comment]
Interested in opening a PR to fix the documentation?

**Comment by rhatdan** [comment]
BTW Which bindings are you using. If you game me a simple go program that used the bindings I could take a look at where it is pulling in containers/storage and try to fix it.

**Comment by strideynet** [comment]
> BTW Which bindings are you using. If you game me a simple go program that used the bindings I could take a look at where it is pulling in containers/storage and try to fix it.

If you are referring to the comment I made, and then deleted. I resolved that issue, that was just the ol race detector/macos monterey bug (https://github.com/golang/go/issues/49138). If you are referring generally, we are using most of the bindings available in `pkg/bindings, however, those flags resolve any issues so I'm happy with that.

> Interested in opening a PR to fix the documentation?

I'd be happy to do so. I'm technically on leave for Christmas now but I'll have some spare time to whip something up this weekend.

**Comment by rhatdan** [comment]
Which bindings were you using that pulled in this requirement?

**Comment by rhatdan** [comment]
I removed libbtrfs-devel package and can not get this to fail the build.

**Comment by byarbrough** [comment]
Hi @rhatdan I ran in to this on both Fedora and Ubuntu with Podman API v3.2.1 and v4.1.1.
Here are two examples:

1. Simply running the https://github.com/containers/Demos/tree/main/podman_go_bindings demo requires downloading quite a few dependencies, as [linked in the README](https://podman.io/getting-started/installation#build-and-run-dependencies)

2. Even just calling the [system info](https://github.com/containers/podman/blob/v4.1.1/pkg/bindings/system/info.go#L12) binding as show below results in 95 indirect dependencies in go.mod for "just HTTP calls."

```go
package main

import (
	"context"
	"fmt"
	"os"

	"github.com/containers/podman/v4/pkg/bindings"
	"github.com/containers/podman/v4/pkg/bindings/system"
)

func main() {
	fmt.Println("Welcome to the Podman Go bindings tutorial")

	// Get Podman socket location
	sock_dir := os.Getenv("XDG_RUNTIME_DIR")
	if sock_dir == "" {
		sock_dir = "/tmp"
	}
	socket := "unix:" + sock_dir + "/podman/podman.sock"

	// Connect to Podman socket
	ctx, err := bindings.NewConnection(context.Background(), socket)
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	fmt.Println(ctx)

	// Calling this function dramatically increases the dependencies and build complexity
	info, err := system.Info(ctx, &system.InfoOptions{})
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}

	fmt.Print(info)
}

```

As @strideynet mentioned above, it looks like this has to do with crossing boundaries to access structures. `system.Info()` makes use of the `Info` struct in [libpod/define](https://github.com/containers/podman/blob/v4.1.1/libpod/define/info.go#L9). Ideally, pkg bindings could stand on its own.
The podman-py project seems to do this well, likely because it is impossible to pull in things from the Go Podman core. 

All that being said, I did get it working in a container with the build flags you recommended!

```bash
go build -tags exclude_graphdriver_btrfs,btrfs_noversion,exclude_graphdriver_devicemapper,containers_image_openpgp main.go
```

This is something I would be eager to help on.

**Comment by vrothberg** [comment]
> Even just calling the [system info](https://github.com/containers/podman/blob/v4.1.1/pkg/bindings/system/info.go#L12) binding as show below results in 95 indirect dependencies in go.mod for "just HTTP calls."

Thanks for bringing that up, @byarbrough.

It is definitely our goal to trim the (transitive) dependencies of pkg/bindings down as much as possible.

@baude @Luap99 FYI

**Comment by Luap99** [comment]
Using libpod/define is fine and expected, maintaining the same types twice is will cause more work and problems.
The problem here is that unlike libpod/define which only includes types it also uses types from other packages that also contain actual code and even c code, therefore you need the build tags to disable that.

The correct way to fix this is to move all required types into separate packages without extra code. The main works seems to be in c/storage and c/image c/buildah and not podman itself. However those libraries are stable so they must keep backwards compat. Keep that in mind when working on it.

**Comment by StarpTech** [comment]
My few cents. Today, I tried to use the Go binding with Podman. My docker image was bloated to 1GB due to Go dependencies. I also couldn't build my app in a separate Stage because podman bindings are linked statically to a system dependency. For now, I have to work with the podman binary directly.

**Comment by vrothberg** [comment]
@StarpTech 1 GB sounds way too much.  The vendor directory of Podman is around 50MB and compiled Podman is at around 40 MB.

Did you clean up all build artifacts from your container image?

**Comment by StarpTech** [comment]
> Did you clean up all build artifacts from your container image?c

What do you mean specifically?

Basically, I did.

```
# Install some dependencies like btrfs ...
go mod download # took some time
# after that, my image was much bigger than before
```

I gave up after that but I can recheck it.

**Comment by giuseppe** [comment]
I am not sure what is the threshold to consider this fixed, since we can continue trimming dependencies and reduce the binary size.  I've opened a PR to move some definitions around so we drag less stuff in the bindings: https://github.com/containers/podman/pull/21364

I also suggest using the `remote` tag since Podman is accessed through a socket.

Using the same example as in the https://github.com/containers/podman/issues/12548#issuecomment-1183786845:

Using podman main:
```
$ go build && stat -c %s binary
37171920
```

Using the tag `remote` with podman main:

```
$ go build -tags remote && stat -c %s binary
18945552
```

Using the tag `remote` with the code from the PR:

```
$ go build -tags remote && stat -c %s binary
12229416
```

**Comment by rhatdan** [comment]
Nice shrinkage.
