### ISSUE TITLE
podman container rm --auto-named

### ISSUE THREAD

**Issue by allisonkarlitskaya** [containers/podman#12558]
It would be cool if there was a command:

```
podman container rm --auto-named
```

which removed all containers that were automatically assigned their names (these names like `strange_gagarin`, `elegant_colden`, `musing_lamport` and so).

Those are usually created as a result of experimentation (often as a result of forgetting `--rm` to `run`) and it's basically never my intention to keep them around for more than a few minutes.  In contrast, the containers that I explicitly assigned a name to are ones that I tend to want to keep.

This might be supported by a label automatically being set on automatically-named containers.

**Comment by rhatdan** [comment]
Better to just write up a script
```
#!/bin/sh
named() {
	podman inspect --format '{{ .Config.CreateCommand }}' $1 | grep -- --name || podman rm $1
}
for c in $(podman ps -q -a); do named $c; done
```
