### ISSUE TITLE
Cannot disable cgroups with docker-compose

### ISSUE THREAD

**Issue by pclass-sensonix** [containers/podman#12550]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The 'cgroups' configuration setting in **/etc/containers/containers.conf** is not used by the podman system service when containers are started with docker-compose. I need to be able to disable cgroups for a collection of containers started with docker-compose.

In my **/etc/containers/containers.conf**, I have this line under the [containers] table:
`cgroups = "disabled"`

When I run a container, the system setting takes affect and my container shows cgroups as disabled:

```
root@device:~# podman container inspect wizardly_rosalind | grep -i cgroup
"--cgroup-manager",
"CgroupManager": "disabled",
"CgroupMode": "private",
"Cgroup": "",
"Cgroups": "disabled",
"CgroupParent": "",
"CgroupConf": null
```

However, when I start the same container with docker-compose, the container starts but it has cgroups enabled.

```
root@device:~# podman container inspect data_collector  | grep Cgroup
"CgroupManager": "systemd",
"CgroupMode": "private",
"Cgroup": "",
"Cgroups": "default",
"CgroupParent": "",
"CgroupConf": null
```

I cannot set 'cgroups: disabled' in docker-compose.yml, it is not a recognized configuration key. How can I get docker-compose to honor the setting in containers.conf?

**Steps to reproduce the issue:**

1. Set **cgroups = "disabled"** in **/etc/containers/containers.conf**

2. Start any container with docker-compose

3. Inspect the container and note that cgroups are still enabled

**Describe the results you received:**

cgroups are enabled in containers started with docker-compose.

**Describe the results you expected:**

cgroups would be disabled in containers started with docker-compose because the system setting in containers.conf indicates it should.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
root@device:~# podman version
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.16.5
Built:        Thu Dec  2 15:45:42 2021
OS/Arch:      linux/arm
```

**Output of `podman info --debug`:**

```
root@device:~# podman info --debug
host:
  arch: arm
  buildahVersion: 1.23.0
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: disabled
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 7e6de6678f6ed8a18661e1d5721b81ccee293b9b-dirty'
  cpus: 1
  distribution:
    distribution: unknown
    version: unknown
  eventLogger: journald
  hostname: device
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.50-linux4sam-2021.04
  linkmode: dynamic
  logDriver: journald
  memFree: 60579840
  memTotal: 253427712
  ociRuntime:
    name: crun
    package: Unknown
    path: /usr/bin/crun
    version: |-
      crun version 1.0.10-1453a
      commit: 1453a0edd690fc34d0bc829b194a55f11245be9b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 0.4.1
      commit: unknown
  swapFree: 189530112
  swapTotal: 251654144
  uptime: 4h 58m 40.89s (Approximately 0.17 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 1
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /container-storage/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /container-storage/downloaded
  imageStore:
    number: 4
  runRoot: /container-storage/containers/storage
  volumePath: /container-storage/containers/storage/volumes
version:
  APIVersion: 4.0.0-dev
  Built: 1638459942
  BuiltTime: Thu Dec  2 15:45:42 2021
  GitCommit: ""
  GoVersion: go1.16.5
  OsArch: linux/arm
  Version: 4.0.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
N/A ( built with Yocto )
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Embedded Linux ARM

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by pclass-sensonix** [comment]
Is the podman system service expected to honor the containers.conf file? Or is there a different way to disable cgroups for an environment started with docker-compose and podman? Thank you.

**Comment by mheon** [comment]
I think we expect the Podman APIs to honor containers.conf. I don't think it's as clear with the Docker-compatible APIs.

**Comment by rhatdan** [comment]
Yes it should follow containers.conf.

**Comment by rhatdan** [comment]
@umohnani8 Did you ever look into this?
