### ISSUE TITLE
Understand how the cgroup-sandbox bug made it through CI

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#12561]
The problem: issue #12535 (fixed by #12538). Nasty bug that was not caught in CI, yet manifested itself 100% reliably on a 1minutetip VM. I believe we should try to understand why the problem never showed up in CI.

It does not seem to be a package difference:

| package | CI | 1minutetip | ... |
| --- | --- | --- | --- |
| kernel | 5.14.18-300.fc35 | = | Also tried 5.15.6-200.fc35 |
| systemd | 249.4-6.fc35 | 249.4-2.fc35 | I also tried 249.4-7 |
| crun | 1.3-1.fc35 | = |
| conmon | 2.0.30-2.fc35 | = |
| containers-common | 1-32.fc35 | = |

Working on a 1minutetip VM, with setup as above, I cannot find any way to silence the warning.

One difference I noticed is that 1minutetip sessions are through ssh, which sets `$DBUS_*` and `$XDG_*`. (CI jobs do not, AFAICT, have any of those). The offending code lives in `RunUnderSystemdScope()`, so this looked promising. Unfortunately, no luck: I unset all `DBUS` and `XDG` envariables, killed all `dbus` processes, and tried:
```console
# podman system reset
...
# podman run -d --name foo quay.io/libpod/testimage:20210610 top
...
# podman exec foo true
WARN[0000] Failed to add conmon to systemd sandbox cgroup: Unit libpod-conmon-54c059bca2f96b809313626797b2afd0eb59d0a65c1d9440fb5c5a3e1b1c2a94.scope already exists.
```
The `podman run` also magically starts new `dbus` processes:
```
dbus       19771  0.5  0.2   9960  4332 ?        Ss   15:07   0:00 /usr/bin/dbus-broker-launch --scope system --audit
dbus       19772  0.0  0.1   5252  2936 ?        S    15:07   0:00 dbus-broker --log 4 --controller 9 --machine-id 5137e5562f8f48368bb541f7b0d4fb09 --max-bytes 536870912 --max-fds 4096 --max-matches 131072 --audit
```
CI comments out a magic `log_driver` line: https://github.com/containers/podman/blob/4a52a457d1e33a4817e4ce1dca390ba942eaec44/contrib/cirrus/setup_environment.sh#L170-L171

This seems an unlikely culprit, but I tried it anyway. No difference. I also tried:
```console
# echo "mq-deadline" > /sys/block/vda/queue/scheduler
```
I tried building from source. 
I don't know what else to try.

**Comment by rhatdan** [comment]
@giuseppe Any ideas on this one?

**Comment by giuseppe** [comment]
not sure there is any action we can take here.

Opened a PR to verify if it fails without the patch: https://github.com/containers/podman/pull/13196

**Comment by giuseppe** [comment]
@edsantiago it seems warnings do not trigger any failure, as the PR above shows

**Comment by edsantiago** [comment]
So, the problem (as I recall) is that all this very happily passed in CI, but it failed in 1minutetip.

Removing the warning from CI is not going to test anything. What we want to understand is: why does  this code fail in a 1minutetip VM, but pass in CI?

**Comment by edsantiago** [comment]
Nobody has been interested in investigating it, and after eight months it will be impossible to sleuth anyway.
