### ISSUE TITLE
podman container forward ports firewalld

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [containers/podman#12562]
how to run a container with a port so that it is only available inside the host
For example,
1. Сontainer  nginx port look outside and look  to backend port, 
2. Container only inside, backend, but nginx sees it.

**Comment by EvgenyPrikhodko** [comment]
> Do you want to bind the port exclusively to localhost on the host system? As written, your question isn't very clear.

Yes. It's a shame that the port is immediately visible on the physical interface. Administrators need to be given a choice. This is a security issue.

**Comment by Luap99** [comment]
you can use `-p 127.0.0.1:8080:80` to make it inly bind the locahost ip.

**Comment by Luap99** [comment]
If you just want to make the nginx container talk to the backend container use a network instead of port forwarding.

**Comment by EvgenyPrikhodko** [comment]
![image](https://user-images.githubusercontent.com/25795145/146220684-540a7455-d7ed-437f-b78d-c943ab914acc.png)

**Comment by EvgenyPrikhodko** [comment]
up
