### ISSUE TITLE
Internal rootless network DNS

### ISSUE THREAD

**Issue by pdavid31** [containers/podman#12565]
Sorry if this questions is a duplicate or I am just not seeing the bigger picture, but how would you go about using DNS name resolution of containers in a rootless internal network?

As I see [here](https://github.com/containers/podman/pull/9057), the dnsname plugin is generally disabled for networks that are created with the `--internal` flag.

**Comment by Luap99** [comment]
see https://github.com/containers/podman/issues/10672

we are working on supporting that in the future maybe with podman v4.0 or v4.1
