### ISSUE TITLE
Podman in Debian Bullseye is heavily outdated

### ISSUE THREAD

**Issue by dimon222** [containers/podman#12575]
Podman in Debian Bullseye repositories is still of version 3.0.1, while 3.4.4 is now around.
Any ETA when its going to be updated? Barely anyone is on `testing` branches of future Debian.

**Comment by vrothberg** [comment]
Thanks for reaching out. I think that Debian won't update Podman for a given release cycle, so Bullseye will continue using Podman 3.0.1 until EOL.  @siretart, please correct me if I am wrong.

**Comment by vrothberg** [comment]
If you like the Debian universe, Ubuntu has more recent versions of Podman.

**Comment by siretart** [comment]
> I think that Debian won't update Podman for a given release cycle, so Bullseye will continue using Podman 3.0.1 until EOL

that is accurate. However, I do intend to update the podman 3.0.1 package with appropriate fixes as necessary. For instance the glibc issue is on my list of things to fix for an upcoming stable update.

> Barely anyone is on testing branches of future Debian.

I'd like to challenge that statement. Using debian testing is actually a more conservative choice than tracking unstable directly, which is a rather popular choice in itself. I personally use a testing/unstable pinning configuration for my daily driver laptop (cf. https://manpages.debian.org/bullseye/apt/apt_preferences.5.en.html#Tracking_Testing_or_Unstable).
