### ISSUE TITLE
podman checkpoint error

### ISSUE THREAD

**Issue by MrErr** [containers/podman#12574]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1.podman container checkpoint dhcp-host -e dhcp-host.tar.gz --tcp-established

2.

3.

**Describe the results you received:**
[root@xroads irlanet]# podman container checkpoint dhcp-host -e dhcp-host.tar.gz --tcp-established; grep -i error /home/podstorage/overlay-containers/8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a/userdata/dump.log
2021-12-10T19:44:11.000769972Z: CRIU checkpointing failed -52.  Please check CRIU logfile /home/podstorage/overlay-containers/8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a/userdata/dump.log
Error: `/usr/bin/crun checkpoint --image-path /home/podstorage/overlay-containers/8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a/userdata/checkpoint --work-path /home/podstorage/overlay-containers/8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a/userdata --tcp-established 8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a` failed: exit status 1
(00.007567) Error (criu/mount.c:625): mnt: FS mnt ./sys/kernel/config dev 0x23 root / unsupported id 3017
(00.008828) Error (criu/cr-dump.c:1781): Dumping FAILED.

**Describe the results you expected:**
I expected the container to be checkpointed. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
[root@xroads irlanet]# podman version
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.8
Built:        Sat Nov 13 18:16:48 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
[root@xroads irlanet]# podman info --debug
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 4
  distribution:
    distribution: fedora
    variant: workstation
    version: "34"
  eventLogger: journald
  hostname: xroads
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.4-101.fc34.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 333701120
  memTotal: 33406357504
  ociRuntime:
    name: crun
    package: crun-1.3-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.3
      commit: 8e5757a4e68590326dafe8a8b1b4a584b10a1370
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc34.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 24551612416
  swapTotal: 24589099008
  uptime: 42h 17m 40.54s (Approximately 1.75 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 24
    paused: 0
    running: 21
    stopped: 3
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /home/podstorage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 79
  runRoot: /home/runpodstorage
  volumePath: /home/podstorage/volumes
version:
  APIVersion: 3.4.2
  Built: 1636849008
  BuiltTime: Sat Nov 13 18:16:48 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
[root@xroads irlanet]# rpm -q podman
podman-3.4.2-1.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It is a physical box running fedora34. 
[dump.log](https://github.com/containers/podman/files/7695162/dump.log)

**Comment by giuseppe** [comment]
@adrianreber PTAL

**Comment by adrianreber** [comment]
A quick look at the log seems to indicate that CRIU has problems handling `/sys/kernel/config`. I have not seen this before.

@MrErr any ideas why `/sys/kernel/config` is mounted in your container. My containers do not have `/sys/kernel/config` mounted.

**Comment by MrErr** [comment]
Probably because the container is run with the --privileged flag. It is a DHCP server, so requires some hardware accesses and therefore need of the privileged flag.

**Comment by adrianreber** [comment]
Even with a `--privileged` I do not see `/sys/kernel/config` mounted in my containers. Can you tell us how you start your container?

I am also a bit worried about the DHCP server. CRIU can handle raw sockets to a certain degree. Not sure checkpointing of DHCP will work.

Anyway, can you provide detailed information how to replicate your setup for me to try locally?

**Comment by MrErr** [comment]
Here are the flags I used to create the container.
podman create \
	--name $NAME \
    --hostname $NAME \
    --network host \
    --privileged \
    --mount type=volume,src=$NAME-conf,dst=/etc/dnsmasq.d \
    --mount type=volume,src=$NAME-status,dst=/var/lib/dnsmasq \
	--restart always \
    $IMAGE:$VER

$NAME is the container name. The image is an almalinux 8.4 with dnsmasq installed in it.

**Comment by adrianreber** [comment]
Using your example my container still does not has `/sys/kernel/config` mounted.

Can you share `config.json` of your container? See `podman inspect`.

Can you share `podman exec dhcp-host mount`?

Can you try `podman exec dhcp-host umount /sys/kernel/config` and try to checkpoint again?

Running a DHCP server should be possible without `--privileged`. Can you try to only give the container the capabilities needed using `--cap-add`?

Just a few different ideas how to get this working.

**Comment by MrErr** [comment]
Here is what you asked for
[root@xroads irlanet]# podman inspect dhcp-host
[
    {
        "Id": "8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a",
        "Created": "2021-11-24T16:18:42.209146777-06:00",
        "Path": "/usr/sbin/init",
        "Args": [
            "/usr/sbin/init"
        ],
        "State": {
            "OciVersion": "1.0.2-dev",
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 1123038,
            "ConmonPid": 1123032,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-12-12T07:30:29.168382787-06:00",
            "FinishedAt": "2021-12-12T07:30:27.587804401-06:00",
            "Healthcheck": {
                "Status": "",
                "FailingStreak": 0,
                "Log": null
            }
        },
        "Image": "763a49fc0509fe45922a499f6531e0ae1dc2af338642135fea28bf717894eeb2",
        "ImageName": "localhost/dhcp:1-2",
        "Rootfs": "",
        "Pod": "",
        "ResolvConfPath": "/home/runpodstorage/overlay-containers/8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a/userdata/resolv.conf",
        "HostnamePath": "/home/runpodstorage/overlay-containers/8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a/userdata/hostname",
        "HostsPath": "/home/runpodstorage/overlay-containers/8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a/userdata/hosts",
        "StaticDir": "/home/podstorage/overlay-containers/8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a/userdata",
        "OCIConfigPath": "/home/podstorage/overlay-containers/8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a/userdata/config.json",
        "OCIRuntime": "crun",
        "ConmonPidFile": "/home/runpodstorage/overlay-containers/8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a/userdata/conmon.pid",
        "PidFile": "/home/runpodstorage/overlay-containers/8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a/userdata/pidfile",
        "Name": "dhcp-host",
        "RestartCount": 0,
        "Driver": "overlay",
        "MountLabel": "system_u:object_r:container_file_t:s0:c1022,c1023",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "EffectiveCaps": [
            "CAP_AUDIT_CONTROL",
            "CAP_AUDIT_READ",
            "CAP_AUDIT_WRITE",
            "CAP_BLOCK_SUSPEND",
            "CAP_BPF",
            "CAP_CHECKPOINT_RESTORE",
            "CAP_CHOWN",
            "CAP_DAC_OVERRIDE",
            "CAP_DAC_READ_SEARCH",
            "CAP_FOWNER",
            "CAP_FSETID",
            "CAP_IPC_LOCK",
            "CAP_IPC_OWNER",
            "CAP_KILL",
            "CAP_LEASE",
            "CAP_LINUX_IMMUTABLE",
            "CAP_MAC_ADMIN",
            "CAP_MAC_OVERRIDE",
            "CAP_MKNOD",
            "CAP_NET_ADMIN",
            "CAP_NET_BIND_SERVICE",
            "CAP_NET_BROADCAST",
            "CAP_NET_RAW",
            "CAP_PERFMON",
            "CAP_SETFCAP",
            "CAP_SETGID",
            "CAP_SETPCAP",
            "CAP_SETUID",
            "CAP_SYSLOG",
            "CAP_SYS_ADMIN",
            "CAP_SYS_BOOT",
            "CAP_SYS_CHROOT",
            "CAP_SYS_MODULE",
            "CAP_SYS_NICE",
            "CAP_SYS_PACCT",
            "CAP_SYS_PTRACE",
            "CAP_SYS_RAWIO",
            "CAP_SYS_RESOURCE",
            "CAP_SYS_TIME",
            "CAP_SYS_TTY_CONFIG",
            "CAP_WAKE_ALARM"
        ],
        "BoundingCaps": [
            "CAP_AUDIT_CONTROL",
            "CAP_AUDIT_READ",
            "CAP_AUDIT_WRITE",
            "CAP_BLOCK_SUSPEND",
            "CAP_BPF",
            "CAP_CHECKPOINT_RESTORE",
            "CAP_CHOWN",
            "CAP_DAC_OVERRIDE",
            "CAP_DAC_READ_SEARCH",
            "CAP_FOWNER",
            "CAP_FSETID",
            "CAP_IPC_LOCK",
            "CAP_IPC_OWNER",
            "CAP_KILL",
            "CAP_LEASE",
            "CAP_LINUX_IMMUTABLE",
            "CAP_MAC_ADMIN",
            "CAP_MAC_OVERRIDE",
            "CAP_MKNOD",
            "CAP_NET_ADMIN",
            "CAP_NET_BIND_SERVICE",
            "CAP_NET_BROADCAST",
            "CAP_NET_RAW",
            "CAP_PERFMON",
            "CAP_SETFCAP",
            "CAP_SETGID",
            "CAP_SETPCAP",
            "CAP_SETUID",
            "CAP_SYSLOG",
            "CAP_SYS_ADMIN",
            "CAP_SYS_BOOT",
            "CAP_SYS_CHROOT",
            "CAP_SYS_MODULE",
            "CAP_SYS_NICE",
            "CAP_SYS_PACCT",
            "CAP_SYS_PTRACE",
            "CAP_SYS_RAWIO",
            "CAP_SYS_RESOURCE",
            "CAP_SYS_TIME",
            "CAP_SYS_TTY_CONFIG",
            "CAP_WAKE_ALARM"
        ],
        "ExecIDs": [],
        "GraphDriver": {
            "Name": "overlay",
            "Data": {
                "LowerDir": "/home/podstorage/overlay/a7ae67f75ae06bb5f1917b00e1fdd061ba9e0c1804b6dbba2a9bc31d07cbb75d/diff",
                "MergedDir": "/home/podstorage/overlay/f0403ffe678e121b22068816cb005efd72009a15a91e00ed205052665d7bc7a0/merged",
                "UpperDir": "/home/podstorage/overlay/f0403ffe678e121b22068816cb005efd72009a15a91e00ed205052665d7bc7a0/diff",
                "WorkDir": "/home/podstorage/overlay/f0403ffe678e121b22068816cb005efd72009a15a91e00ed205052665d7bc7a0/work"
            }
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "dhcp-host-conf",
                "Source": "/home/podstorage/volumes/dhcp-host-conf/_data",
                "Destination": "/etc/dnsmasq.d",
                "Driver": "local",
                "Mode": "",
                "Options": [
                    "nosuid",
                    "nodev",
                    "rbind"
                ],
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "dhcp-host-status",
                "Source": "/home/podstorage/volumes/dhcp-host-status/_data",
                "Destination": "/var/lib/dnsmasq",
                "Driver": "local",
                "Mode": "",
                "Options": [
                    "nosuid",
                    "nodev",
                    "rbind"
                ],
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Dependencies": [],
        "NetworkSettings": {
            "EndpointID": "",
            "Gateway": "",
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "MacAddress": "",
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": ""
        },
        "ExitCommand": [
            "/usr/bin/podman",
            "--root",
            "/home/podstorage",
            "--runroot",
            "/home/runpodstorage",
            "--log-level",
            "warning",
            "--cgroup-manager",
            "systemd",
            "--tmpdir",
            "/run/libpod",
            "--runtime",
            "crun",
            "--storage-driver",
            "overlay",
            "--storage-opt",
            "overlay.mountopt=nodev,metacopy=on",
            "--events-backend",
            "journald",
            "container",
            "cleanup",
            "8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a"
        ],
        "Namespace": "",
        "IsInfra": false,
        "Config": {
            "Hostname": "dhcp-host",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "TERM=xterm",
                "container=podman",
                "HOSTNAME=dhcp-host",
                "HOME=/root"
            ],
            "Cmd": [
                "/usr/sbin/init"
            ],
            "Image": "localhost/dhcp:1-2",
            "Volumes": null,
            "WorkingDir": "/temp",
            "Entrypoint": "",
            "OnBuild": null,
            "Labels": {
                "io.buildah.version": "1.22.0",
                "maintainer": "Sam Irlapati \u003cirlapati@gmail.com\u003e"
            },
            "Annotations": {
                "io.container.manager": "libpod",
                "io.kubernetes.cri-o.Created": "2021-11-24T16:18:42.209146777-06:00",
                "io.kubernetes.cri-o.TTY": "false",
                "io.podman.annotations.autoremove": "FALSE",
                "io.podman.annotations.init": "FALSE",
                "io.podman.annotations.privileged": "TRUE",
                "io.podman.annotations.publish-all": "FALSE",
                "org.opencontainers.image.stopSignal": "37"
            },
            "StopSignal": 37,
            "CreateCommand": [
                "podman",
                "create",
                "--name",
                "dhcp-host",
                "--hostname",
                "dhcp-host",
                "--network",
                "host",
                "--privileged",
                "--mount",
                "type=volume,src=dhcp-host-conf,dst=/etc/dnsmasq.d",
                "--mount",
                "type=volume,src=dhcp-host-status,dst=/var/lib/dnsmasq",
                "--restart",
                "always",
                "dhcp:1-2"
            ],
            "SystemdMode": true,
            "Umask": "0022",
            "Timeout": 0,
            "StopTimeout": 10
        },
        "HostConfig": {
            "Binds": [
                "dhcp-host-conf:/etc/dnsmasq.d:rw,rprivate,nosuid,nodev,rbind",
                "dhcp-host-status:/var/lib/dnsmasq:rw,rprivate,nosuid,nodev,rbind"
            ],
            "CgroupManager": "systemd",
            "CgroupMode": "private",
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "k8s-file",
                "Config": null,
                "Path": "/home/podstorage/overlay-containers/8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a/userdata/ctr.log",
                "Tag": "",
                "Size": "0B"
            },
            "NetworkMode": "host",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "always",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [],
            "CapDrop": [],
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": [],
            "GroupAdd": [],
            "IpcMode": "private",
            "Cgroup": "",
            "Cgroups": "default",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "private",
            "Privileged": true,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [],
            "Tmpfs": {},
            "UTSMode": "private",
            "UsernsMode": "",
            "ShmSize": 65536000,
            "Runtime": "oci",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": 0,
            "OomKillDisable": false,
            "PidsLimit": 2048,
            "Ulimits": [
                {
                    "Name": "RLIMIT_NOFILE",
                    "Soft": 1048576,
                    "Hard": 1048576
                },
                {
                    "Name": "RLIMIT_NPROC",
                    "Soft": 4194304,
                    "Hard": 4194304
                }
            ],
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "CgroupConf": null
        }
    }
]
[root@xroads irlanet]# podman exec dhcp-host mount
overlay on / type overlay (rw,relatime,context="system_u:object_r:container_file_t:s0:c1022,c1023",lowerdir=/home/podstorage/overlay/l/VBE6OCA35IETYPJXDOU7AP3LGB,upperdir=/home/podstorage/overlay/f0403ffe678e121b22068816cb005efd72009a15a91e00ed205052665d7bc7a0/diff,workdir=/home/podstorage/overlay/f0403ffe678e121b22068816cb005efd72009a15a91e00ed205052665d7bc7a0/work,metacopy=on)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev,relatime,context="system_u:object_r:container_file_t:s0:c1022,c1023",inode64)
tmpfs on /dev type tmpfs (rw,nosuid,context="system_u:object_r:container_file_t:s0:c1022,c1023",size=65536k,mode=755,inode64)
tmpfs on /run type tmpfs (rw,nosuid,nodev,relatime,context="system_u:object_r:container_file_t:s0:c1022,c1023",inode64)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime,seclabel)
/dev/sdb1 on /run/secrets type ext4 (rw,relatime,seclabel)
/dev/sdb1 on /etc/dnsmasq.d type ext4 (rw,nosuid,nodev,relatime,seclabel)
/dev/sdb1 on /etc/hosts type ext4 (rw,relatime,seclabel)
/dev/sdb1 on /run/.containerenv type ext4 (rw,relatime,seclabel)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime,seclabel)
shm on /dev/shm type tmpfs (rw,relatime,context="system_u:object_r:container_file_t:s0:c1022,c1023",size=64000k,inode64)
/dev/sdb1 on /etc/hostname type ext4 (rw,relatime,seclabel)
/dev/sdb1 on /etc/resolv.conf type ext4 (rw,relatime,seclabel)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,context="system_u:object_r:container_file_t:s0:c1022,c1023",gid=5,mode=620,ptmxmode=666)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,relatime,context="system_u:object_r:container_file_t:s0:c1022,c1023",inode64)
/dev/sdb1 on /var/lib/dnsmasq type ext4 (rw,nosuid,nodev,relatime,seclabel)
tmpfs on /var/log/journal type tmpfs (rw,nosuid,nodev,relatime,context="system_u:object_r:container_file_t:s0:c1022,c1023",inode64)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,relatime,seclabel)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=74431546)
debugfs on /sys/kernel/debug type debugfs (rw,relatime,seclabel)
configfs on /sys/kernel/config type configfs (rw,relatime)

[root@xroads irlanet]# podman exec dhcp-host umount /sys/kernel/config
[root@xroads irlanet]# podman container checkpoint dhcp-host -e dhcp-host.tar.gz --tcp-established
2021-12-12T22:38:01.000322163Z: CRIU checkpointing failed -52.  Please check CRIU logfile /home/podstorage/overlay-containers/8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a/userdata/dump.log
Error: `/usr/bin/crun checkpoint --image-path /home/podstorage/overlay-containers/8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a/userdata/checkpoint --work-path /home/podstorage/overlay-containers/8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a/userdata --tcp-established 8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a` failed: exit status 1
[root@xroads irlanet]# grep -ie error /home/podstorage/overlay-containers/8831da0e28f631b5538184c250f814eb2e507e82511fbfda1bb63cd0756f038a/userdata/dump.log
(00.032375) Dumping path for -3 fd via self 15 [/usr/lib64/libgpg-error.so.0.24.2]
(00.052965) Error (criu/sk-unix.c:479): unix: Dangling connection 74431527
(00.053007) Error (criu/cr-dump.c:1361): Dump files (pid: 1123038) failed with -1
(00.053725) Error (criu/cr-dump.c:1781): Dumping FAILED.

I could try the --cap-add option, but I don't have a spare machine to experiment on. 

I have tried to see if dhcp functionaility works after unmounting /sys/kernel/config, so I don't think it is nessecary to be mounted for the contaier to run. 

For some reason, I am unable to upload the dump.log, I get the error "Something went really wrong, and we can't process tjay file."  So I am going to try and paste the file in another message.

**Comment by MrErr** [comment]
[dump.log](https://github.com/containers/podman/files/7700030/dump.log)

**Comment by MrErr** [comment]
Is there a quick way to stop container, remove the --privileged flag and the "--cap-add=NET_ADMIN" flag? If that is the wrong flag for DHCP, what would be the right flag? Would --cap-add="CAP_NET_BIND_SERVICE" be the right one?

**Comment by adrianreber** [comment]
From what I see in the log you might have found a situation that CRIU does not support. The mount point problem is gone as you unmounted `/sys/kernel/config`. It seems you are using systemd in the container and checkpointing systemd seems to fail. There is not much Podman can do. Using a simpler init system in the container might help, but your current setup is something CRIU cannot handle.

**Comment by MrErr** [comment]
OK. 
Also I got the container to run without the --privileged flag. I had to add both "--cap-add NET_ADMIN" and "--cap-add NET_RAW" for dhcp functionality to work.

**Comment by vrothberg** [comment]
> From what I see in the log you might have found a situation that CRIU does not support. The mount point problem is gone as you unmounted `/sys/kernel/config`. It seems you are using systemd in the container and checkpointing systemd seems to fail. There is not much Podman can do. Using a simpler init system in the container might help, but your current setup is something CRIU cannot handle.

@adrianreber is that something we should document in the man pages?

**Comment by adrianreber** [comment]
> > From what I see in the log you might have found a situation that CRIU does not support. The mount point problem is gone as you unmounted `/sys/kernel/config`. It seems you are using systemd in the container and checkpointing systemd seems to fail. There is not much Podman can do. Using a simpler init system in the container might help, but your current setup is something CRIU cannot handle.
> 
> @adrianreber is that something we should document in the man pages?

Probably. I will open a PR mentioning it.

**Comment by rhatdan** [comment]
@adrianreber @MrErr Can this issue be closed now?

**Comment by MrErr** [comment]
I read the documentation change bug mentioned above. So just to understand this right, systemd is discouraged and instead to rely on other flags?

**Comment by rhatdan** [comment]
Since this is now documented closing.
