### ISSUE TITLE
--security-opt label=role: inconsistency

### ISSUE THREAD

**Issue by ghost** [containers/podman#12578]
```
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.17.3
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**
```
podman run --privileged -ti --security-opt label=type:unprivcontainer.subj --security-opt label=user:wheel.id --security-opt label=role:wheel.role --security-opt label=level:s0 docker.io/library/debian:bullseye-slim
```
**Describe the results you received:**
```
Dec 11 16:54:18 brutus conmon[167588]: touch: cannot touch 'test': Permission denied
Dec 11 16:54:18 brutus audit[167608]: AVC avc:  denied  { create } for  pid=167608 comm="touch" name="test" scontext=wheel.id:wheel.role:unprivcontainer.subj:s0 tcontext=wheel.id:sys.role:containers.state.file:s0 tclass=file permissive=0
```
The file is not created with the specified role

**Describe the results you expected:**

File test with context `wheel.id;wheel.role:containers.state.file:s0` instead of it trying to create file test with context `wheel.id:sys.role:containers.state.file:s9`

**Additional information you deem important (e.g. issue happens only occasionally):**

SELinux roles can be used for container separation (Similar to MCS)

```
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.17.3
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 8
  distribution:
    distribution: debian
    version: unknown
  eventLogger: journald
  hostname: brutus
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.0-2-amd64
  linkmode: dynamic
  logDriver: journald
  memFree: 9664897024
  memTotal: 15662645248
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 7830761472
  swapTotal: 7830761472
  uptime: 69h 1m 22.39s (Approximately 2.88 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/kcinimod/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/kcinimod/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 4
  runRoot: /run/user/1000/containers
  volumePath: /home/kcinimod/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 3.4.2

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
ii  podman                               3.4.2+ds1-1                       amd64        engine to run OCI-based containers in Pods
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Comment by vrothberg** [comment]
@rhatdan PTAL

**Comment by doverride** [comment]
I read somewhere in the docs that "podman guarantees uniq categrories for separation" but I highly doubt that.

Say you have four users all running Podman, then how would these four Podman instances be aware of what sets of compartments they use?

That is where separation using roles comes in: In the event that two Podman user instance use the same sets of compartments, the instances will still be separated based on roles (if leveraged)

**Comment by doverride** [comment]
One should also ensure that if label=user: and label=role: is specified on the command line that the overlay is mounted with context= taking the user and role into account.

**Comment by rhatdan** [comment]
Correct if you had multiple users on the same machine at the same time, then there is a chance that the MCS Labels would conflict.

Podman mount label only supports a single label mount_file_t, specified in 
```
$ cat /usr/share/containers/selinux/contexts
process = "system_u:system_r:container_t:s0"
file = "system_u:object_r:container_file_t:s0"
ro_file="system_u:object_r:container_ro_file_t:s0"
kvm_process = "system_u:system_r:container_kvm_t:s0"
init_process = "system_u:system_r:container_init_t:s0"
engine_process = "system_u:system_r:container_engine_t:s0"
```

**Comment by rhatdan** [comment]
Separation on users would be handled by DAC.  Luckily it is very rare that multiple users would be running multiple containers on a single machine.

**Comment by rhatdan** [comment]
SELinux library does not handle file system roles and users at this point. PRs welcome.

**Comment by doverride** [comment]
> SELinux library does not handle file system roles and users at this point. PRs welcome.

Users and levels work fine, it's just roles that is lacking.

**Comment by doverride** [comment]
> Separation on users would be handled by DAC. Luckily it is very rare that multiple users would be running multiple containers on a single machine.

Exactly and that is also why I argued in another thread that Podman should rely on SELinux if no `lcx_contexts` exists. It is like you said: `lxc_contexts` only "supports one label" and that imay have been suffice in the past but these day's with per-user instances it is just no longer helpful.

Anyway's luckily users can disable the label feature in `~/.config/containers/containers.conf`, and guess what. Ironically separation based on roles works fine them.

**Comment by doverride** [comment]
> Correct if you had multiple users on the same machine at the same time, then there is a chance that the MCS Labels would conflict.
> 
> Podman mount label only supports a single label mount_file_t, specified in
> 
> ```
> $ cat /usr/share/containers/selinux/contexts
> process = "system_u:system_r:container_t:s0"
> file = "system_u:object_r:container_file_t:s0"
> ro_file="system_u:object_r:container_ro_file_t:s0"
> kvm_process = "system_u:system_r:container_kvm_t:s0"
> init_process = "system_u:system_r:container_init_t:s0"
> engine_process = "system_u:system_r:container_engine_t:s0"
> ```

Yes there is no such thing as a "single label". You could atleast have omited to user role and level for `lxc_contexts`:

```
$ cat /usr/share/containers/selinux/contexts
process = "container_t"
file = "container_file_t"
ro_file="container_ro_file_t"
kvm_process = "container_kvm_t"
init_process = "container_init_t"
engine_process = "container_engine_t"
```
But aside from the fact that there is just no such thing as a single label, you would still get into `context=` mount label issues because ideally one would really be able to specify mount label user, roles, types and levels

**Comment by rhatdan** [comment]
Most of this conversation should be taking place in github.com/opencontainers/selinux

**Comment by doverride** [comment]
Two more observations:

Cannot manually override:

* pod infra container context (uses process =)
* volume (create) context (uses file =)

**Comment by mheon** [comment]
@rhatdan What's going on here? Can we close?

**Comment by rhatdan** [comment]
Yes this should be working now.  Reopen if I am mistaken.
