### ISSUE TITLE
error locating item named "manifest" for image with ID .... when parallel pulling images and listing them

### ISSUE THREAD

**Issue by Hendrik-H** [containers/podman#12582]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When I pull multiple images in parallel and at the same time invoke `podman image ls` the later sometimes fails with an error like
```
Error: error locating item named "manifest" for image with ID "73cdb17d7c55ea37c6d9b24adb900bc0fbff828b179e1ff04bb0fe735743ba13": file does not exist
```

**Steps to reproduce the issue:**

1. `podman image prune --all -f`

2. start `while podman image ls; do echo ""; done` in one terminal window

3. pull multiple images in parallel in another window. in my test I pulled 4 images with around 5 layers each from a docker registry running on the same host.

**Describe the results you received:**
all pull requests to work and no `podman image ls` call to fail.

**Describe the results you expected:**
sometimes the image listing fails with the above error. I was so far only able to reproduce this once, so it does not fail all the time.

**Additional information you deem important (e.g. issue happens only occasionally):**
I'm using the vfs storage driver.
As stated the issue only happens occasionally.

**Output of `podman version`:**

```
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.15.14
Built:        Tue Oct 19 13:00:58 2021
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.21.3
  cgroupControllers: []
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.29-1.el8.ibm.1.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: unknown'
  cpus: 4
  distribution:
    distribution: '"base"'
    version: "9"
  eventLogger: journald
  hostname: testhost
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 65534
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-305.19.1.el8.zhmc9_0.5.x86_64
  linkmode: dynamic
  memFree: 709062656
  memTotal: 16811765760
  ociRuntime:
    name: crun
    package: crun-0.20.1-1.el8.ibm.1.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.20.1
      commit: 38271d1c8d9641a2cdc70acfa3dcb6996d124b3d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.1.8-1.el8.ibm.2.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 8387772416
  swapTotal: 8589930496
  uptime: 8h 54m 11.21s (Approximately 0.33 days)
registries:
  localhost:5000:
    Blocked: false
    Insecure: true
    Location: localhost:5000
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: localhost:5000
  search:
  - registry.access.redhat.com
  - registry.fedoraproject.org
  - registry.centos.org
  - docker.io
store:
  configFile: /home/testuser/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /data/container
  graphStatus: {}
  imageStore:
    number: 4
  runRoot: /run/user/1000/containers
  volumePath: /data/container/volumes
version:
  APIVersion: 3.2.3
  Built: 1634662858
  BuiltTime: Tue Oct 19 13:00:58 2021
  GitCommit: ""
  GoVersion: go1.15.14
  OsArch: linux/amd64
  Version: 3.2.3
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.2.3-0.11.el8.zhmc9_0.2.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@vrothberg This is a corrupted c/storage situation, right?

**Comment by Hendrik-H** [comment]
If the storage was really corrupted I would expect that it stays that way. To me it looks like the image listing code is reading data from the container storage that is not correctly locked by some lock file and thus sees some image data that it should not see (yet).

**Comment by vrothberg** [comment]
> @vrothberg This is a corrupted c/storage situation, right?

Probably, yes. What I "suspect" is a race between pruning (removing image data) and looking up image data.
```
process 1      lookup image                            inspect manifest
process 2                          remove image
time           ---------------------------------------------------------------->
```

Looking up an image and inspecting it is not an atomic operation, so I think we have to optimize the image-listing code path to make these errors non-fatal as we've done for other code paths already.

**Comment by Hendrik-H** [comment]
I'm actually doing the pruning before the parallel pulls. But the problem should be still the same following your description.

**Comment by vrothberg** [comment]
> I'm actually doing the pruning before the parallel pulls. But the problem should be still the same following your description.

If both commands run in parallel, the upper race would still apply.  I need to check further though since we have optimized many code paths for such errors already.

**Comment by vrothberg** [comment]
Found the location: https://github.com/containers/common/blob/main/libimage/filters.go#L34-L36

We need to add some further error checks here when filtering images.  There is a number of PR extending the filters.  Once merged, I'll prepare a PR to fix this issue.
