### ISSUE TITLE
Using audio on a container with Podman, on Mac OS

### ISSUE THREAD

**Issue by clementremillieux** [containers/podman#12580]
Hello,

I'm trying to use audio on a container launched with Podman on MacOS. 

The container is jess/pulseaudio
I am using a big Sur OS with an Apple M1 chip ( also tested on an INTEL chip)
I use podman in version 3.4.4

The commmand `podman run hello world` works well

After launching podman ( `podman machine init` and `podman machine start`),  I connect with ssh to the VM and `install pulseaudio alsa-utils pulseaudio-utils`. Then I launch pulseaudio on the host Mac OS and on the podman VM with the command

`pulseaudio --load=module-native-protocol-tcp --exit-idle-time=-1 --daemon`

Then I run the following command to launch the container: 

`podman run -it -e PULSE_SERVER=docker.for.mac.localhost -v /home/core/.config/pulse:/home/pulseaudio/.config/pulse --entrypoint speaker-test --rm jess/pulseaudio -c 2 -l 1 -t wav`

and I get this error on my host terminal (the containers is then not launch): 

`{"msg": "exec container process "/usr/bin/speaker-test": Exec format error","level":"error","time":"2021-12-13T12:40:09.000532852Z"}`

when I run the following command 

`podman run -it -e PULSE_SERVER=docker.for.mac.localhost -v /home/core/.config/pulse:/home/pulseaudio/.config/pulse --rm jess/pulseaudio`

I got:

`{"msg":"exec container process "/usr/bin/pulseaudio": Exec format error","level":"error","time":"2021-12-13T13:00:04.000533324Z"}`

I would like to point out that the following command works for me with Docker, on the same macOS: 

`docker run -it -e PULSE_SERVER=docker.for.mac.localhost -v ~/.config/pulse:/home/pulseaudio/.config/pulse --entrypoint speaker-test --rm jess/pulseaudio -c 2 -l 1 -t wav. `

I know that Podman uses a virtual machine on Mac OS. So I think I should first link the audio of the virtual machine with the audio of the MacOS host like when I mount volumes (first I mount the volume on the VM and then on the container) but I'm not sure. Is there some specific podman configuration or command to use audio, or should I do it manually ?

Do you have an idea? 

**Output of `podman version`:**

```
Client:
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Wed Dec  8 19:41:11 2021
OS/Arch:      darwin/arm64

Server:
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.8
Built:        Fri Nov 12 21:26:31 2021
OS/Arch:      linux/arm64
```

**Output of `podman info --debug`:**

```
host:
  arch: arm64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc35.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "35"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.6-200.fc35.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 160489472
  memTotal: 2048565248
  ociRuntime:
    name: crun
    package: crun-1.3-1.fc35.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.3
      commit: 8e5757a4e68590326dafe8a8b1b4a584b10a1370
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.aarch64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 1h 22m 25.03s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 12
    paused: 0
    running: 0
    stopped: 12
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 5
  runRoot: /run/user/1000/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 1636748791
  BuiltTime: Fri Nov 12 20:26:31 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/arm64
  Version: 3.4.2
```

**Comment by mheon** [comment]
@baude @ashley-cui PTAL

**Comment by TomSweeneyRedHat** [comment]
IDK but two quick thoughts.  I noticed you fully specified your volume in the Podman  command:`-v /home/core/.config/pulse:/home/pulseaudio/.config/pulse`, but not in Docker: `-v ~/.config/pulse:/home/pulseaudio/.config/pulse`.  I can't imagine that's the problem, but maybe if they're two different files?

My other question is this:  `-e PULSE_SERVER=docker.for.mac.localhost`.  Is that pointing toward the local Mac?  I'm assuming that's where the pulse sever is located.

**Comment by clementremillieux** [comment]
When I use `~` with the Podman command, this corresponds to `/Users/user` path of the MacOs files, this path does not exist in the Podman VM. That's why I put the user path of the VM, but I'm not sure about it. 

I forgot to mention that directly from the Podman VM (via ssh) I can't even play audio with the `aplay` command. 

`docker.for.mac.localhost` is an internal docker DNS, it corresponding to 192.168.127.1 in my case ( when I run 
`dig docker.for.mac.localhost` inside the running container I get this address) , when I try the Podman command with the adresse `192.168.127.1` it's not working too ...

**Comment by rhatdan** [comment]
Just throwing it out there that there is potential for SELinux issues with this.

**Comment by rhatdan** [comment]
Since I never heard back, I am closing this issue.  Reopen if there is more feedback.
