### ISSUE TITLE
MacOS Hackintosh  qemu-system-x86_64: Error: HV_ERROR

### ISSUE THREAD

**Issue by lou-lan** [containers/podman#12617]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

```
podman machine start
INFO[0000] waiting for clients...                       
INFO[0000] listening tcp://127.0.0.1:7777               
INFO[0000] new connection from  to /var/folders/lx/94z03_f97vn0zydky3xr0kxw0000gn/T/podman/qemu_podman-machine-default.sock 
Waiting for VM ...
qemu-system-x86_64: Error: HV_ERROR
Error: dial unix /var/folders/lx/94z03_f97vn0zydky3xr0kxw0000gn/T/podman/podman-machine-default_ready.sock: connect: connection refused
ERRO[0003] cannot receive packets from , disconnecting: cannot read size from socket: EOF 
ERRO[0003] cannot read size from socket: EOF   
```

**Steps to reproduce the issue:**

1. brew install podman

2. podman machine init

3. podman machine start

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: Connection to bastion host (ssh://core@localhost:56589/run/user/1000/podman/podman.sock) failed.: dial tcp [::1]:56589: connect: connection refused
```

**Output of `podman info --debug`:**

```
podman info --debug

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: Connection to bastion host (ssh://core@localhost:56589/run/user/1000/podman/podman.sock) failed.: dial tcp [::1]:56589: connect: connection refused
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
brew list podman

/usr/local/Cellar/podman/3.4.4/bin/podman
/usr/local/Cellar/podman/3.4.4/bin/podman-remote
/usr/local/Cellar/podman/3.4.4/etc/bash_completion.d/podman
/usr/local/Cellar/podman/3.4.4/libexec/gvproxy
/usr/local/Cellar/podman/3.4.4/share/fish/vendor_completions.d/podman.fish
/usr/local/Cellar/podman/3.4.4/share/man/ (160 files)
/usr/local/Cellar/podman/3.4.4/share/zsh/site-functions/_podman
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is macos `Hackintosh`.

**Comment by vrothberg** [comment]
Thanks for opening the issue, @lou-lan!

@ashley-cui, @baude, PTAL

**Comment by ashley-cui** [comment]
Looks like qemu itself doesn't like the hackintosh system... A quick google shows this: https://stackoverflow.com/questions/67264212/android-emulator-crash-when-start-hvf-error-hv-error

Could you try that out?

**Comment by lou-lan** [comment]
> Looks like qemu itself doesn't like the hackintosh system... A quick google shows this: https://stackoverflow.com/questions/67264212/android-emulator-crash-when-start-hvf-error-hv-error
> 
> Could you try that out?

Thanks. I am try it, but it not work for me.

If just run `./qemu-system-x86_64`, it work.

<img width="722" alt="截屏2021-12-16 下午11 43 05" src="https://user-images.githubusercontent.com/13095837/146402539-9bc9e9da-4f03-455e-9fcf-efd7df17afb2.png">

**Comment by ginigangadharan** [comment]
Facing the same issue. Anyone else found a solution ?

@lou-lan  ?

**Comment by lou-lan** [comment]
> 

I haven't found a solution yet, but if qemu is not using Apple virtualization, then he should be able to run.

**Comment by lou-lan** [comment]
@ginigangadharan  I haven't found a solution yet, but if qemu is not using Apple virtualization, then he should be able to run.

**Comment by ginigangadharan** [comment]
> @ginigangadharan  I haven't found a solution yet, but if qemu is not using Apple virtualization, then he should be able to run.
> 
> 
> 
> 

Oh okay. Actually it was perfectly working, Now I think the issues started after some some macOS update. I will check that as well.

**Comment by imjuanleonard** [comment]
Why this is closed? Do we have solution for this?

**Comment by baude** [comment]
it was fixed.

**Comment by oxycoder** [comment]
> it was fixed.

I still face same issue

```
podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Error: dial unix /var/folders/nc/sz5g1ck1187253n6cys_hn3m0000gn/T/podman/podman-machine-default_ready.sock: connect: connection refused
```

**Comment by BenDev1001** [comment]
i faced this same error... how can i fix it? I'm not sure why this was closed.

**Comment by BenDev1001** [comment]
> it was fixed.

please tell me how to fix it ?
I 've installed podman on vmware macOS based on windows10.
