### ISSUE TITLE
Return of the Evil Dead Pprof

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#12624]
Sorry, @vrothberg and @jwhonce. This one just won't die.
```
         • Failure [24.380 seconds]
         podman system service
         /var/tmp/go/src/github.com/containers/podman/test/e2e/system_service_test.go:18
           verify pprof endpoints
           /var/tmp/go/src/github.com/containers/podman/test/e2e/system_service_test.go:56
             are available [It]
             /var/tmp/go/src/github.com/containers/podman/test/e2e/system_service_test.go:60
         
             Timed out after 20.001s.
             Expected process to exit.  It did not.
```
[link](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5837420917686272/html/int-podman-fedora-35-rootless-host.log.html#t--are-available--1)

**Comment by vrothberg** [comment]
I think it's time to have a closer look. Bumping the timeouts clearly does not help.

:cry:

**Comment by edsantiago** [comment]
### podman system service verify pprof endpoints [It] are not available
* fedora-34 : int podman fedora-34 rootless host
  * PR #12748
    * [01-10 15:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5905820184477696/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--1)
    * [01-10 15:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5905820184477696/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--2)
    * [01-10 15:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5905820184477696/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--3)
* fedora-35 : int podman fedora-35 rootless host
  * PR #12726
    * [01-06 11:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6268668047785984/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--1)
    * [01-06 11:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6268668047785984/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--2)
    * [01-06 11:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6268668047785984/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--3)
* ubuntu-2110 : int podman ubuntu-2110 rootless host
  * PR #12735
    * [01-04 11:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6747417012862976/html/int-podman-ubuntu-2110-rootless-host.log.html#t--are-not-available--1)

### podman system service verify pprof endpoints [It] are available
* fedora-34 : int podman fedora-34 rootless host
  * PR #12783
    * [01-09 22:51](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5297636172365824/html/int-podman-fedora-34-rootless-host.log.html#t--are-available--1)
    * [01-09 22:51](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5297636172365824/html/int-podman-fedora-34-rootless-host.log.html#t--are-available--2)
    * [01-09 22:51](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5297636172365824/html/int-podman-fedora-34-rootless-host.log.html#t--are-available--3)
* fedora-35 : int podman fedora-35 rootless host
  * PR #12726
    * [01-06 11:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6268668047785984/html/int-podman-fedora-35-rootless-host.log.html#t--are-available--1)
  * PR #12208
    * [12-27 14:28](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5224144684974080/html/int-podman-fedora-35-rootless-host.log.html#t--are-available--1)
    * [12-27 14:28](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5224144684974080/html/int-podman-fedora-35-rootless-host.log.html#t--are-available--2)
    * [12-27 14:28](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5224144684974080/html/int-podman-fedora-35-rootless-host.log.html#t--are-available--3)
* ubuntu-2110 : int podman ubuntu-2110 rootless host
  * PR #12735
    * [01-04 11:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6747417012862976/html/int-podman-ubuntu-2110-rootless-host.log.html#t--are-available--1)
    * [01-04 11:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6747417012862976/html/int-podman-ubuntu-2110-rootless-host.log.html#t--are-available--2)
    * [01-04 11:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6747417012862976/html/int-podman-ubuntu-2110-rootless-host.log.html#t--are-available--3)

**Comment by edsantiago** [comment]
A friendly reminder that this bug still exists

### podman system service verify pprof endpoints [It] are not available 
* fedora-34 : int podman fedora-34 rootless host
  * PR #13155
    * [02-07 01:48](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6730236153823232/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--1)
    * [02-07 01:48](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6730236153823232/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--2)
    * [02-07 01:48](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6730236153823232/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--3)
  * PR #13117
    * [02-02 14:22](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5359563309318144/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--1)
    * [02-02 14:22](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5359563309318144/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--2)
    * [02-02 14:22](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5359563309318144/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--3)
* fedora-35 : int podman fedora-35 rootless host
  * PR #12991
    * [01-24 11:43](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6266060247662592/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--1)
    * [01-24 11:43](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6266060247662592/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--2)
    * [01-24 11:43](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6266060247662592/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--3)
  * PR #12887
    * [01-19 12:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5082783251955712/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--1)
    * [01-19 12:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5082783251955712/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--2)
    * [01-19 12:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5082783251955712/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--3)

**Comment by edsantiago** [comment]
### podman system service verify pprof endpoints [It] are available 
* fedora-34 : int podman fedora-34 rootless host
  * PR #13255
    * [02-17 13:24](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6225309799284736/html/int-podman-fedora-34-rootless-host.log.html#t--are-available--1)
    * [02-17 13:24](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6225309799284736/html/int-podman-fedora-34-rootless-host.log.html#t--are-available--2)
    * [02-17 13:24](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6225309799284736/html/int-podman-fedora-34-rootless-host.log.html#t--are-available--3)
* fedora-35 : Netavark int podman rootless
  * PR #13247
    * [02-22 16:03](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6507478346104832/html/int-podman-fedora-35-rootless-host-netavark.log.html#t--are-available--1)
    * [02-22 16:03](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6507478346104832/html/int-podman-fedora-35-rootless-host-netavark.log.html#t--are-available--2)
    * [02-22 16:03](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6507478346104832/html/int-podman-fedora-35-rootless-host-netavark.log.html#t--are-available--3)
* fedora-35 : int podman fedora-35 rootless host
  * PR #13210
    * [02-10 21:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6042189472989184/html/int-podman-fedora-35-rootless-host.log.html#t--are-available--1)
* ubuntu-2110 : int podman ubuntu-2110 rootless host
  * PR #13263
    * [02-17 09:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6544540021555200/html/int-podman-ubuntu-2110-rootless-host.log.html#t--are-available--1)
    * [02-17 09:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6544540021555200/html/int-podman-ubuntu-2110-rootless-host.log.html#t--are-available--2)
    * [02-17 09:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6544540021555200/html/int-podman-ubuntu-2110-rootless-host.log.html#t--are-available--3)


### podman system service verify pprof endpoints [It] are not available 
* fedora-34 : int podman fedora-34 rootless host
  * PR #13202
    * [02-10 16:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4574392721080320/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--1)
    * [02-10 16:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4574392721080320/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--2)
    * [02-10 16:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4574392721080320/html/int-podman-fedora-34-rootless-host.log.html#t--are-not-available--3)
* fedora-35 : Netavark int podman rootless
  * PR #13214
    * [02-11 11:15](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5406823686602752/html/int-podman-fedora-35-rootless-host-netavark.log.html#t--are-not-available--1)
    * [02-11 11:15](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5406823686602752/html/int-podman-fedora-35-rootless-host-netavark.log.html#t--are-not-available--2)
    * [02-11 11:15](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5406823686602752/html/int-podman-fedora-35-rootless-host-netavark.log.html#t--are-not-available--3)
  * PR #13210
    * [02-11 07:35](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5253070870282240/html/int-podman-fedora-35-rootless-host-netavark.log.html#t--are-not-available--1)
    * [02-11 07:35](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5253070870282240/html/int-podman-fedora-35-rootless-host-netavark.log.html#t--are-not-available--2)
    * [02-11 07:35](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5253070870282240/html/int-podman-fedora-35-rootless-host-netavark.log.html#t--are-not-available--3)
*  fedora-35 : int podman fedora-35 rootless host
  * PR #13239
    * [02-15 17:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6564481848311808/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--1)
    * [02-15 17:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6564481848311808/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--2)
    * [02-15 17:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6564481848311808/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--3)
  * PR #13210
    * [02-10 21:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6042189472989184/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--1)
    * [02-10 21:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6042189472989184/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--2)
    * [02-10 21:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6042189472989184/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--3)
  * PR #13059
    * [02-20 22:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6432795131117568/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--1)
    * [02-20 22:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6432795131117568/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--2)
    * [02-20 22:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6432795131117568/html/int-podman-fedora-35-rootless-host.log.html#t--are-not-available--3)

**Comment by kousu** [comment]
* PR https://github.com/containers/podman/pull/13375
  * [03-01 14:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5915070445125632/html/int-podman-fedora-35-rootless-host-netavark.log.html#t--are-not-available--1)
  * [03-01 14:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5915070445125632/html/int-podman-fedora-35-rootless-host-netavark.log.html#t--are-not-available--2)
  * [03-01 14:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5915070445125632/html/int-podman-fedora-35-rootless-host-netavark.log.html#t--are-not-available--3)

**Comment by edsantiago** [comment]
Note for future: the flaking test was disabled by #13460. 

We are going to get monthly "friendly reminders" from github. **KEEP THIS BUG OPEN**. If you get tired of the friendly reminders, either fix the bug or completely remove the offending test (as in, remove the code entirely, don't just skip).

**Comment by Luap99** [comment]
The tests are skipped so what point thus this serve? pprof are debugging endpoints only and given we survived without tests for over two years I would say remove the tests and close this one out, objections?

**Comment by edsantiago** [comment]
The tests are skipped because of this flake. They've been skipped for over two years, and nobody has complained about pprof, so I'm okay removing the tests and closing this. @jwhonce, this is your code, any objection?
