### ISSUE TITLE
Docker incompatibility: events API uses Action="died", not Action="die"

### ISSUE THREAD

**Issue by leahneukirchen** [containers/podman#12628]
This is essentially the same issue as #10168 (fixed in 3.2.0), but for the `Action` field of the event. I suggest to change it for the legacy API as well.

**Comment by leahneukirchen** [comment]
also podman sets `containerExitCode`, but docker sets `exitCode`.

**Comment by rhatdan** [comment]
Please open a PR to change.  4.0 is your time to fix these. Although if they are compat then they can be fixed at any time.
