### ISSUE TITLE
podman ps is empty if container got started via crontab

### ISSUE THREAD

**Issue by weitlich** [containers/podman#12630]
/kind bug

**Description**
I am trying to automate the restart of my podman containers after reboot via an entry in the crontab (@reboot) for my application userid (not root).

I had to add 
   #!/bin/sh --login
to the shell script that is called from cron and that in turn executes 
   podman run ....
to make it work at all.

Now, the containers are started and running after a reboot, but I cannot see them or open a shell in them.

The service provided by the containers is available.
However,
   podman ps 
is empty.

ps -ef shows the container process as running:
   <userid>   <pid>   1   0  Dec09  ?   00:00:00  /usr/bin/conmon --api-version 1
I can also see the java and httpd processes running in my containers in the normal system ps output.

When trying to get a shell in the container via
    podman  exec -it <containername> bash
I get the error message
   Error: can only create exec sessions on running containers: container state improper

I am using podman version 3.2.3 on Red Hat Enterprise Linux 8.3 (Ootpa).

What do I need to do to make sure that my containers are properly restarted after a reboot?
I am not root, so defining a systemd entry is not that easy for me.

Thanks for any help!

**Comment by rhatdan** [comment]
Did you become the user before executing podman ps?  Rootfull containers and rootless containers are different.

**Comment by weitlich** [comment]
Yes, I am trying the 
   podman ps
as the user for which the crontab is defined that has started the containers.

**Comment by rhatdan** [comment]
I would do podman info in both locations.

Does podman ps -a
Show the containers?

**Comment by Luap99** [comment]
Rootless podman needs a user login session to work properly. If you just want to start your container at boot look at `podman-generate-systemd(1)`. You should use the systemd user session, there are no root privileges needed. You also need to run `loginctl enable-linger <username>` to make sure that the containers are started at boot and keep running after user logout.

**Comment by Luap99** [comment]
Also please provide `podman info` it is likely that your storage paths are not ideal when you run podman the first time without the systemd user session.

**Comment by weitlich** [comment]
Hi all, thanks for trying to help me.
My system admins have upgraded podman to version 3.3.1.
Since then, it works as expected.
