### ISSUE TITLE
name resolve failed.

### ISSUE THREAD

**Issue by Arryboom** [containers/podman#12639]
- enviroment
```
CentOS Linux release 8.5.2111      with all yum upgrade up-to-date 
podman version 3.3.1
firewalld enabled
```
- problem
**cannot resolve container hostname in created network**

- steps to prove:

```
docker create network rkshare
docker run -td --name rkdb --hostname mongork --network rkshare mongo
docker run -td --name rk --hostname rk --network rkshare --env ROOT_URL=http://localhost --env MONGO_URL=mongodb://rkdb:27017/db --env MONGO_OPLOG_URL=mongodb://rkdb:27017/local  rocket.chat
```
then got follow error from container rk:

```
docker logs rk

MongoServerSelectionError: getaddrinfo ENOTFOUND rkdb
    at Timeout._onTimeout (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/sdam/topology.js:437:30)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map {
      'rkdb:27017' => ServerDescription {
        address: 'rkdb:27017',
        error: Error: getaddrinfo ENOTFOUND rkdb
            at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
          name: 'MongoNetworkError'
        },
```
it's clear container doesnt has "rkdb" hostname resolve to rkdb container.
since I've use another setting ``--hostname mongork``,so I tried this one to create rk container again 
```
docker run -td --name rk --hostname rk --network rkshare --env ROOT_URL=http://localhost --env MONGO_URL=mongodb://mongork:27017/db --env MONGO_OPLOG_URL=mongodb://mongork:27017/local  rocket.chat
```
and still got the same error:

```
docker logs rk

MongoServerSelectionError: getaddrinfo ENOTFOUND mongork
    at Timeout._onTimeout (/app/bundle/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/sdam/topology.js:437:30)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map {
      'mongork:27017' => ServerDescription {
        address: 'mongork:27017',
        error: Error: getaddrinfo ENOTFOUND rkdb
            at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
          name: 'MongoNetworkError'
        },
```
and by execute ```ping rkdb``` ```ping mongork``` in container rk got same result 
```
Name or service not known
```

---
the way I think this doesn't work might be:

1. by checking the /etc/hosts in rk container you can see there doesn't has the desired hostname keypair too(although they may should resolve by internal dns system in podman?)

2. by then checking /etc/resolve.conf in rk container you can see the container copied the podman host's /etc/resolve.conf in to itself,so this might got some point?

3.  the firewalld in podman's host system might droped/misstransed pods's internal dns system's packet?

----
## the way I used to sovle this,but now I dont want to solve by these 'dirty way':  
dont really want to use ```--add-host rkdb:10.89.0.2``` to solve this since the ipaddress will change often.
and dont want to use ```--link rkdb:rkdb``` too,since those two container already assaigned to a same network by ```--network rkshare``` options.
and ofcourse dont really want to manually edit /etc/hosts in the container too

--
**is there any misunderstanding about the two options?  Really wonder why neither ``--name`` and ``--hostname`` working,I think I encounter this same problem for years,too many times.**

**Comment by Luap99** [comment]
Do you have `podman-plugins` installed? Please provide the output of `podman network inspect rkshare`.

**Comment by Arryboom** [comment]
> Do you have `podman-plugins` installed? Please provide the output of `podman network inspect rkshare`.

everything is default  as the network rkshare was created by ```docker network create rkshare```
```
[root@Max ~]# podman network inspect rkshare
[
    {
        "cniVersion": "0.4.0",
        "name": "rkshare",
        "plugins": [
            {
                "bridge": "cni-podman1",
                "hairpinMode": true,
                "ipMasq": true,
                "ipam": {
                    "ranges": [
                        [
                            {
                                "gateway": "10.89.0.1",
                                "subnet": "10.89.0.0/24"
                            }
                        ]
                    ],
                    "routes": [
                        {
                            "dst": "0.0.0.0/0"
                        }
                    ],
                    "type": "host-local"
                },
                "isGateway": true,
                "type": "bridge"
            },
            {
                "capabilities": {
                    "portMappings": true
                },
                "type": "portmap"
            },
            {
                "backend": "",
                "type": "firewall"
            },
            {
                "type": "tuning"
            }
        ]
    }
]
```

**Comment by Luap99** [comment]
You have to install the dnsname plugin which is provided by `podman-plugins`, if you have dnsname installed you need to recreate the network.
see https://github.com/containers/dnsname

**Comment by Arryboom** [comment]
> You have to install the dnsname plugin which is provided by `podman-plugins`, if you have dnsname installed you need to recreate the network. see https://github.com/containers/dnsname

ok,so by default this plugin won't be installed with podman?

**Comment by Arryboom** [comment]
ok,seems dns resolver plugin got another problem when a container connected to more than one network...it's good it's not enabled by default....
