### ISSUE TITLE
Loading multiple Images via the Docker compatible REST-API does not work

### ISSUE THREAD

**Issue by adippel** [containers/podman#12638]
**Is this a BUG REPORT or FEATURE REQUEST?**

/kind bug

**Description**

Loading a tar docker-archive with multiple exported images using the docker compatibility REST-API does not work although this is possible using the original Docker REST API and is stated in Podman's API Spec. Additionally, loading the very same archive using Podman's CLI works without any problems.

The problematic lines start with the following line: 

https://github.com/containers/podman/blob/b8fde5c5b2a94beac20cd37cab0b59ea0124249c/pkg/api/handlers/compat/images.go#L460

Such an if statement is missing in the CLI command implementation. Having multiple Names is even used for presenting the result:

https://github.com/containers/podman/blob/17788ed058fdcb15549bdc2b9fa831f9bfa26ca2/cmd/podman/images/load.go#L96

In a local build, I removed the three lines in the API code and then, the import works without a problem. I'd be happy to create a PR for this :) 

**Steps to reproduce the issue:**

1. `podman pull docker.io/library/alpine:latest docker.io/library/busybox:latest`

2. `podman save -o test.tar docker.io/library/alpine:latest docker.io/library/busybox:latest`

3. In a second terminal window start: `podman system service -t 0 unix:///tmp/podman-test.sock`

4. `curl -X POST --data-binary @test.tar -H "Content-Type: application/x-tar" --unix-socket /tmp/podman-test.sock "http:/v1.35/images/load"`

**Describe the results you received:**

`{"cause":"2 instead of 1 were loaded","message":"2 instead of 1 were loaded","response":500}`

**Describe the results you expected:**

A successful load of all images contained within the tar archive as specified in the API Spec https://docs.podman.io/en/latest/_static/api.html#operation/ImageLoad. Likewise, Docker native API supports this. Since this is the Docker Compatibility API, the behavior is not expected. Additionally, importing using `podman load -i test.tar` works as expected.

**Additional information you deem important:**

In a local build, I removed the three lines in the API code and then, the import works without a problem. I'd be happy to create a PR for this :) 

**Output of `podman version`:**

```
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.6
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 1
  distribution:
    codename: focal
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: dippalde-fit
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.4.0-91-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 6223978496
  memTotal: 7118114816
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: ea1fe3938eefa14eb707f1d22adff4db670645d6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 2m 26.04s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/xxxx/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.9.0
        fuse-overlayfs: version 1.5
        FUSE library version 3.9.0
        using FUSE kernel interface version 7.31
  graphRoot: /home/xxxx/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /home/xxxx/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.4.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 100:3.4.2-1 amd64 [installed]
podman/unknown 100:3.4.2-1 arm64
podman/unknown 100:3.4.2-1 armhf
podman/unknown 100:3.4.2-1 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

-/-

**Comment by flouthoc** [comment]
@adippel Thanks for reporting and debugging this. You are right but I think compat API should have this instead of removing error handling

```diff
-if len(loadReport.Names) != 1 {
+if len(loadReport.Names) < 1 {
```  
But yes please open a PR with what worked for you. Lets discuss it on the PR :smile:

**Comment by flouthoc** [comment]
@adippel Above PR should close this.

**Comment by adippel** [comment]
@flouthoc sorry for being late pushing a PR. Your PR should definitely do it, thanks a lot for taking care! Are there any plans on when this change will be part of a release?

**Comment by flouthoc** [comment]
I am not sure if this is gonna be part of `4.0` @mheon can comment on this.

**Comment by mheon** [comment]
It made it in before the branch so it will be in 4.0
