### ISSUE TITLE
jenkins pipeline error from podman in podman: error in copier subprocess: error changing to intended-new-root directory \"/var/lib/containers/storage/overlay/5d...f1/merged\": chdir /var/lib/containers/storage/overlay/5d...f1/merged: no such file or directory 

### ISSUE THREAD

**Issue by 321sp** [containers/podman#12645]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

/kind feature

**Description**

**Steps to reproduce the issue:**

1. running multiple builds with Copy --chown statement in Dockerfile. 

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.15.7
Built:        ThuJuly 29 22:30:40 2021
OS/Arch:      linux/amd64
**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**
yes

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by flouthoc** [comment]
@321sp Does this happens intermittently or always ?

I am suspecting intermittently as there were few race conditions in `c/storage` in past but they were fixed.

I tried running multiple builds with `COPY --chown=` concurrently but i was unable to reproduce this with `main` branch.

I believe the most common race was fixed here https://github.com/containers/storage/pull/1037 and fix is not on the release which you are using.

Could you please try using the podman from `main` branch  ?

**Comment by 321sp** [comment]
@flouthoc This is happening intermittently when running multiple builds remotely and running under Jenkins as a CI/CD pipeline

**Comment by flouthoc** [comment]
@321sp Would it be possible to try running `main` branch on your jenkins. I am playing with `main` and unable to reproduce this issue.
