### ISSUE TITLE
v3.4.2 API  containers/wait route does not accept any conditions .

### ISSUE THREAD

**Issue by dmikov** [containers/podman#12652]
/kind bug

**Description**

When calling API containers/wait endpoint it always fails with 400 error when condition is specified. The podman image `quay.io/podman/stable`  is running in docker with 
`podman system service tcp:0.0.0.0:2376 -t=0` command.

<pre><font color="#4E9A06"><b>dmikov@ubuntu</b></font>:<font color="#3465A4"><b>~</b></font>$ curl -X POST http://localhost:2376/v3.0.0/containers/a8ab55360df881ef4d7e8c474d86f8de00635e0a0c4a27a76d866fb4376517b0/wait?condition=stopped
{&quot;cause&quot;:&quot;not a valid docker condition&quot;,&quot;message&quot;:&quot;failed to parse query parameter &apos;condition&apos;: \&quot;stopped\&quot;: not a valid docker condition&quot;,&quot;response&quot;:400}
<font color="#4E9A06"><b>dmikov@ubuntu</b></font>:<font color="#3465A4"><b>~</b></font>$ 
</pre>

**Steps to reproduce the issue:**

1. Run a container in podman,

2. Ask API to  wait for stopped or exited condition

3. Get 400 error.

**Describe the results you received:**

{"cause":"not a valid docker condition","message":"failed to parse query parameter 'condition': \"stopped\": not a valid docker condition","response":400}

**Describe the results you expected:**

{"StatusCode":0,"Error":null} - Same as if you run post without the condtion parameter.

**Output of `podman version`: 

```
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.8
Built:        Fri Nov 12 20:25:37 2021
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.30-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    variant: container
    version: "35"
  eventLogger: file
  hostname: d60906cb30e1
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.11.0-43-generic
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 389324800
  memTotal: 16750665728
  ociRuntime:
    name: crun
    package: crun-1.3-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.3
      commit: 8e5757a4e68590326dafe8a8b1b4a584b10a1370
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 2145632256
  swapTotal: 2147479552
  uptime: 51h 50m 22.18s (Approximately 2.12 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /var/lib/shared
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.7.1-2.fc35.x86_64
      Version: |-
        fusermount3 version: 3.10.5
        fuse-overlayfs: version 1.7.1
        FUSE library version 3.10.5
        using FUSE kernel interface version 7.31
    overlay.mountopt: nodev,fsync=0
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 1636748737
  BuiltTime: Fri Nov 12 20:25:37 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.2

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.2-1.fc35.x86_64

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/

**Additional environment details (AWS, VirtualBox, physical, etc.):**

podman image from Quay.io

**Comment by Luap99** [comment]
`/v3.0.0/containers/<ID>/wait` is the docker compat endpoint. The docker endpoint accepts only "next-exit", "removed", or "not-running" as wait condition. If you want to talk to the libpod api you have to use `/v3.0.0/libpod/containers/<ID>/wait`
