### ISSUE TITLE
Clarify documentation on uid mapping with several subuid maps per user

### ISSUE THREAD

**Issue by ibukanov** [containers/podman#12676]
/kind bug

**Description**

[Documentation](https://docs.podman.io/en/latest/markdown/podman-run.1.html) for podman run --uidmap does not describe what happens with multiple mappings per user in /etc/subuid with rootless containers. It is not even clear if it is supported.

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/podman/pull/12692
