### ISSUE TITLE
podmanimage: Enable podman.sock

### ISSUE THREAD

**Issue by jpf91** [containers/podman#12686]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

It would be nice if the podman docker image had `podman.sock` enabled by default. It would then be possible to just start the container with `/sbin/init` and mount `/var/run/podman` to make `podman.sock` externally available.

**Comment by mheon** [comment]
@TomSweeneyRedHat @rhatdan PTAL

**Comment by rhatdan** [comment]
The podman image (No need for docker adjective) does not include systemd.  So I am not sure it is worth adding the overhead to add systemd, perhaps we could add a podman-init image along with Podman which would do what you want.

You do not need systemd within the container to do what you want though, try:

$ podman run --privileged -v /run:/run quay.io/podman/stable podman system service -t 0

**Comment by jpf91** [comment]
> No need for docker adjective

good catch ;-)

> The podman image does not include systemd

I tested this previously and it seemed to be available in the image, so I guess it's in the base image. But anyway, your solution is indeed much better, thanks!

Maybe this information could be added to the article which actually caused my interest in exporting the socket from a container: https://www.redhat.com/sysadmin/podman-inside-container ? Great article by the way and great work on podman, I'm surprised by cool new features all the time :-)

**Comment by jpf91** [comment]
Unfortunately, further testing shows that for some use cases, running systemd in the image seems to be necessary. I want to use the podman-in-podman setup as a backend for drone-ci. Using the `podman system service -t 0` command as suggested causes this error when trying to run images in drone-ci:
> default: Error response from daemon: writing file `/sys/fs/cgroup/libpod_parent/libpod-9565c84bedfdb07cbd84060ee9ec53e8c839500ff237993746706f5ef25664c8/cgroup.procs`: Operation not supported: OCI runtime error

It works perfectly fine when I use "/sbin/init" as entry point for the container and run `systemctl enable podman.socket` once. I think there's no real drawback from adding `systemctl enable podman.socket` in the image Dockerfile, as it won't have any effect as long as users are not explicitly starting `/sbin/init`. What do you think?

**Comment by rhatdan** [comment]
Try to build a container use this Containerfile

```
cat > Containerfile << _EOF
from quay.io/podman/stable
run dnf -y install systemd; dnf -y clean all;
run systemctl enable podman.socket; systemctl disable console-getty systemd-logind; mkdir -p /var/lib/systemd/linger; touch /var/lib/systemd/linger/podman
run su podman -c "systemctl --user enable podman.socket"
entrypoint [ "/sbin/init" ]
_EOF
```
Now Build it
```
podman build -t podman-init .
```
And try it out.

**Comment by jpf91** [comment]
Seems to work for me :+1: (I've only tested root-mode podman) 

> systemctl disable console-getty systemd-logind

Didn't have an effect for me if the intention was to disable the login console. `mask` instead of `disable` deactivated it properly.

**Comment by rhatdan** [comment]
Great to know, I was fooling around with trying to disable them.  But lost time (and interest)...
Glad you were successful.
