### ISSUE TITLE
add option to bind mount (pod managed) /etc/* files to nonstandard locations

### ISSUE THREAD

**Issue by LStandman** [containers/podman#12691]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

There are programs that allow some daemons to run chrooted for some added security *within* the program. (e.g., Postfix.)
Within a pod /etc/hosts is managed by the pod and automatically bind mounted to guest:/etc/hosts.

Perhaps *podman run* should expose an option to bind mount that pod-managed hosts file into alternative/additional locations within the guest. E.g., *podman run --hostsfile-targets=/var/run/foo bar*

Best regards,
LS

**Comment by rhatdan** [comment]
Not sure what the issue you are attempting to fix.  Do you want to have a chroot within a container which would see the hosts file created within the pod?
BTW Not sure how much security a chroot within a container adds.  A container is already a super secure chroot.

**Comment by LStandman** [comment]
> Not sure what the issue you are attempting to fix. Do you want to have a chroot within a container which would see the hosts file created within the pod? 
Exactly

> BTW Not sure how much security a chroot within a container adds. A container is already a super secure chroot.
I believe that a container separates an abstract service (e.g., an SMTP server) from the host that runs the server.
A within-container chroot would create a layer of separation between the processes that comprise that abstract service (assuming you cannot neatly containerize these processes).

**Comment by rhatdan** [comment]
In this case you would want the hosts file mounted twice. What about the resolv.conf and other files created by Podman to be mounted into the container.

**Comment by LStandman** [comment]
Then I suppose we should generalize the issue. :)
Maybe the command line option should be used point to all "etc/" directories, and then podman will mount *all* those specially-treated files more than once. E.g., *podman run --etc-targets=/etc,/var/run/foo,/var/run/bar*

**Comment by rhatdan** [comment]
Are you mounting these in the same location under the chroot IE would 
--rootfstargets=/, /var/run/foo

And you end up with /var/run/foo/etc/hosts?

**Comment by LStandman** [comment]
I hope I am understanding you correctly.
Yes, there is always a corresponding etc/ folder under the chroot

**Comment by rhatdan** [comment]
I just don't want to be specific to etc. Not that we currently generate other files, I believe but keep out options open.
I think keeping it 
--altrootfs=/var/run/foo and still mounting in / would be a better alternative.

**Comment by LStandman** [comment]
Indeed, yours is the better alternative. :)

**Comment by rhatdan** [comment]
@vrothberg @giuseppe Thoughts?

**Comment by vrothberg** [comment]
I am OK with it.

**Comment by rhatdan** [comment]
@LStandman interested in opening a PR for this?

**Comment by LStandman** [comment]
> @LStandman interested in opening a PR for this?

Sure why not

**Comment by rhatdan** [comment]
@LStandman did you ever make any progress?

**Comment by LStandman** [comment]
> @LStandman did you ever make any progress?

Hi, yes I'm about done with it.
I expect to PR in a couple of weeks
