### ISSUE TITLE
podman container forward ports vs firewalld 

### ISSUE THREAD

**Issue by EvgenyPrikhodko** [containers/podman#12700]
https://github.com/containers/podman/issues/12562 - History of the issue

![image](https://user-images.githubusercontent.com/25795145/147373743-cd1cdc15-df3f-401c-8d9e-6f55615cdd96.png)

**Comment by Luap99** [comment]
Can you provide a reproducer?
`sudo podman run -p 127.0.0.1:8080:80 -d nginx` and `curl 127.0.0.1:8080` works for me

**Comment by EvgenyPrikhodko** [comment]
> Can you provide a reproducer? `sudo podman run -p 127.0.0.1:8080:80 -d nginx` and `curl 127.0.0.1:8080` works for me

Thank you. All work
