### ISSUE TITLE
Publishing a port on localhost with `podman run` causes immediate client disconnections

### ISSUE THREAD

**Issue by nicolasff** [containers/podman#12701]
## Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)

/kind bug

## Description

Hello! I am trying to use Podman to run a service that serves requests on a TCP port, but I need to avoid letting unknown clients connect from some other host on the same network.

To enforce that the port is **only opened locally**, I use `-p` as described in the [Podman documentation](https://docs.podman.io/en/latest/markdown/podman-run.1.html#publish-p-ip-hostport-containerport-ip-containerport-hostport-containerport-containerport) which says the parameter can be in the format `ip:hostPort:containerPort`.

But when I set `127.0.0.1` as the interface to bind to, connections from the host to the published port are **closed as soon as a client sends data**. When I omit the interface, I'm able to connect but now so is everyone else on the same network…

## Steps to reproduce the issue:

This example uses the [Redis 6.2.6 image from Docker Hub](https://hub.docker.com/layers/redis/library/redis/6.2.6/images/sha256-563888f63149e3959860264a1202ef9a644f44ed6c24d5c7392f9e2262bd3553?context=explore).

When the port is exposed on all interfaces (`-p 6379:6379`), clients work fine:
```
$ podman run --rm -d --name redis-test -p 6379:6379 redis:6.2.6
79ccf49b5805b3efbdf13253e31e6d878703c88089ced5c69854a44044c688bc
$ redis-cli ping
PONG
$ podman stop redis-test
redis-test
```

When the port is exposed on loopback only (`-p 127.0.0.1:6379:6379`), the server disconnects very quickly:
```
$ podman run --rm -d --name redis-test -p 127.0.0.1:6379:6379 redis:6.2.6
1783ce5d6a7ef90fefcd9619093d9a9690cabff12468681d4a3b3fb3097d79f1
$ redis-cli ping
Error: Connection reset by peer
```

⚠️ Note that these repro steps won't work if you already have Redis running locally. If that's the case, change the first `6379` after `-p` to another port (e.g. port 6380 so the `-p` parameter should _end_ with `6380:6379`) and use `redis-cli -h 127.0.0.1 -p 6380 PING`.

I captured the traffic with Wireshark and saw a `RST`:  
1. 63562 → 6379 `SYN`
2. 6379 → 63562 `SYN`, `ACK`
3. 63562 → 6379 `ACK`
4. 6379 → 63562 `ACK` (TCP window update)
5. 63562 → 6379 `PSH`, `ACK` (length; 14 bytes, contents: `*1\r\n$4\r\nPING\r\n`
6. 6379 → 63562 `ACK`
7. 6379 → 63562 `RST`, `ACK`

It looks like "Redis" closed the connection, or more likely the part of Podman that handles port forwarding.

`pcap` file with these 7 packets: [podman-reset.pcap.zip](https://github.com/containers/podman/files/7775552/podman-reset.pcap.zip)

## Describe the results you received:

Immediate disconnection after sending data to a port "published" with `-p 127.0.0.1:host_port:container_port`.

## Describe the results you expected:

I expected the service to be available on this port using the loopback interface, without having to listen on all interfaces to be able to connect. I've been using this format with `docker run` without issues, and am not sure what I am missing to be able to do this with Podman instead.

## Additional information you deem important (e.g. issue happens only occasionally):

This is 100% reproducible for me. I originally encountered this problem with a different image, so tried it with Redis to see if this was an issue with my service or with Podman. Both images have the same issue.

## Output of `podman version`:

```
Client:
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Wed Dec  8 10:41:11 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.8
Built:        Fri Nov 12 12:25:37 2021
OS/Arch:      linux/amd64
```

## Output of `podman info --debug`:

<details>

<summary>Click to expand</summary>

```yaml
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "35"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.7-200.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1123721216
  memTotal: 2061385728
  ociRuntime:
    name: crun
    package: crun-1.3-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.3
      commit: 8e5757a4e68590326dafe8a8b1b4a584b10a1370
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 43h 33m 3.08s (Approximately 1.79 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 3
  runRoot: /run/user/1000/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 1636748737
  BuiltTime: Fri Nov 12 20:25:37 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.2
```

</details>

## Package info (e.g. output of `rpm -q podman` or `apt list podman`):

```
$ brew info podman
podman: stable 3.4.4 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/usr/local/Cellar/podman/3.4.4 (170 files, 40MB) *
  Poured from bottle on 2021-12-23 at 02:47:26
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0
==> Dependencies
Build: go ✘, go-md2man ✘
Required: qemu ✔
==> Options
--HEAD
	Install HEAD version

==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
```

## Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)

Yes and yes.

## Additional environment details (AWS, VirtualBox, physical, etc.):

Host is an iMac (year 2020, Intel CPU)  running macOS 11.6 Big Sur 20G165.

**Comment by Luap99** [comment]
It looks like you use podman machine, port forwarding with host ip is not yet supported for machine. Podman 4.0 will fix this
