### ISSUE TITLE
"potentially insufficient UIDs or GIDs available in user namespace" when pulling

### ISSUE THREAD

**Issue by alaviss** [containers/podman#12715]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Pulling any image fails with `potentially insufficient UIDs or GIDs available in user namespace`. I have verified that subgid/subuid has been setup correctly.

**Steps to reproduce the issue:**

1. `podman pull docker.io/debian:testing-slim`

**Describe the results you received:**

```
Trying to pull docker.io/library/debian:testing-slim...
Getting image source signatures
Copying blob 3331450fb84f done  
Error: writing blob: adding layer with blob "sha256:3331450fb84fde695e565405a554d5cf213a33826da197b29aabde08be012f8b": Error processing tar file(exit status 1): potentially insufficient UIDs or GIDs available in user namespace (requested 0:42 for /etc/gshadow): Check /etc/subuid and /etc/subgid: lchown /etc/gshadow: invalid argument
```

**Additional information you deem important (e.g. issue happens only occasionally):**

```
$ podman unshare cat /proc/self/uid_map
         0      60252          1
         1     200000      65536

$ podman unshare cat /proc/self/gid_map
         0      60252          1
         1     200000      65536

$ cat /etc/subuid
leorize:200000:65536

$ cat /etc/subgid
leorize:200000:65536
```

**Output of `podman version`:**

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.5
Built:        Fri Dec 24 03:50:42 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: app-containers/conmon-2.0.31
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.31, commit: v2.0.31'
  cpus: 12
  distribution:
    distribution: gentoo
    version: "2.8"
  eventLogger: journald
  hostname: leorize-lnx-workstation
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 60252
      size: 1
    - container_id: 1
      host_id: 200000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 60252
      size: 1
    - container_id: 1
      host_id: 200000
      size: 65536
  kernel: 5.15.11-gentoo
  linkmode: dynamic
  logDriver: journald
  memFree: 12275621888
  memTotal: 16773726208
  ociRuntime:
    name: crun
    package: app-containers/crun-1.3
    path: /usr/bin/crun
    version: |-
      crun version 1.3
      commit: 4f6c8e0583c679bfee6a899c05ac6b916022561b
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/60252/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: app-containers/slirp4netns-1.1.12
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 15032381440
  swapTotal: 15032381440
  uptime: 4m 8.45s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/leorize/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: sys-fs/fuse-overlayfs-1.8
      Version: |-
        fusermount3 version: 3.10.5
        fuse-overlayfs: version 1.8
        FUSE library version 3.10.5
        using FUSE kernel interface version 7.31
  graphRoot: /home/leorize/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/60252/containers
  volumePath: /home/leorize/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 1640339442
  BuiltTime: Fri Dec 24 03:50:42 2021
  GitCommit: ""
  GoVersion: go1.17.5
  OsArch: linux/amd64
  Version: 3.4.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
app-containers/podman-3.4.4
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine

**Comment by flouthoc** [comment]
Hi @alaviss thanks for creating the issues.

This is new i have never seen this error while pulling an image. Does it happen if you try to pull other images as well ? Like `podman pull alpine` ?

If you configured your range after the first error. Then you must also run `podman system migrate`.

Could you try doing `podman system migrate` and repull ?

**Comment by alaviss** [comment]
> This is new i have never seen this error while pulling an image. Does it happen if you try to pull other images as well ? Like `podman pull alpine` ?

I got a similar issue with alpine image too:

```
Error: writing blob: adding layer with blob "sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3": Error processing tar file(exit status 1): potentially insufficient UIDs or GIDs available in user namespace (requested 0:42 for /etc/shadow): Check /etc/subuid and /etc/subgid: lchown /etc/shadow: invalid argument
```

> Could you try doing `podman system migrate` and repull ?

```
$ podman system migrate

$ podman pull docker.io/debian:testing-slim
Trying to pull docker.io/library/debian:testing-slim...
Getting image source signatures
Copying blob 3331450fb84f done  
Error: writing blob: adding layer with blob "sha256:3331450fb84fde695e565405a554d5cf213a33826da197b29aabde08be012f8b": Error processing tar file(exit status 1): potentially insufficient UIDs or GIDs available in user namespace (requested 0:42 for /etc/gshadow): Check /etc/subuid and /etc/subgid: lchown /etc/gshadow: invalid argument

$ podman pull docker.io/alpine
Trying to pull docker.io/library/alpine:latest...
Getting image source signatures
Copying blob 59bf1c3509f3 done  
Error: writing blob: adding layer with blob "sha256:59bf1c3509f33515622619af21ed55bbe26d24913cedbca106468a5fb37a50c3": Error processing tar file(exit status 1): potentially insufficient UIDs or GIDs available in user namespace (requested 0:42 for /etc/shadow): Check /etc/subuid and /etc/subgid: lchown /etc/shadow: invalid argument
```

It doesn't seem to work :(

**Comment by flouthoc** [comment]
Does it works when you run with `sudo` ? I definently think now its the issue with your `subuid` and `subgid` setup.

**Comment by alaviss** [comment]
Yep it works with `sudo`, but I would like to use `toolbox`, so `sudo` is a no-go for this...

Do you have any tips for diagnosing `sub*id` setups? The error messages are very unhelpful for this.

**Comment by flouthoc** [comment]
Do you have ` newuidmap/newgidmap` binaries installed ?
Could you share output of following commands ?
* `getcap /usr/bin/newuidmap /usr/bin/newgidmap`
* `id`
* `podman unshare cat /proc/self/uid_map` after `podman system migrate`
* `podman unshare cat /proc/self/gid_map` after `podman system migrate`
* also try reinstalling `shadow-utils` and run `podman system migrate` after reinstall.

**Comment by alaviss** [comment]
> * getcap /usr/bin/newuidmap /usr/bin/newgidmap

No output.

These two binaries are owned by `root:root` and have setuid bit set.

> * id

```
uid=60252(leorize) gid=60252(leorize) groups=60252(leorize),10(wheel),18(audio),78(kvm),100(users),226(i2c),250(portage),272(plugdev),385(gamemode),993(adbusers),999(sudo)
```

> * `podman unshare cat /proc/self/uid_map` after `podman system migrate`

```
         0      60252          1
         1     200000      65536
```

> * `podman unshare cat /proc/self/gid_map` after `podman system migrate`

```
         0      60252          1
         1     200000      65536
```

> * also try reinstalling `shadow-utils` and run `podman system migrate` after reinstall.

No change, unfortunately :(

**Comment by giuseppe** [comment]
do you get any error if you try running as rootless these commands`$ touch foo; podman unshare chown 0:42 foo`?

**Comment by alaviss** [comment]
I get the same error:

```
$ touch foo; podman unshare chown 0:42 foo
chown: changing ownership of 'foo': Invalid argument
```

**Comment by giuseppe** [comment]
Can you confirm there are enough IDs in /proc/self/uid_map and /proc/self/gid_map?  If so, then the error is coming from the underlying file system and there is nothing podman can do about it

**Comment by alaviss** [comment]
As shown in this comment https://github.com/containers/podman/issues/12715#issuecomment-1003135032, I have 65535 IDs at my disposal, so I think I have enough.

> If so, then the error is coming from the underlying file system and there is nothing podman can do about it

Do you know of any good way to debug this? I'm using Btrfs for the backing storage.

**Comment by alaviss** [comment]
Closing as I traced it down to systemd instead https://github.com/systemd/systemd/issues/21952

**Comment by zwn** [comment]
I was also getting this error when trying to pull any image. In my case I could see there is some problem with the subuids:

```
$ podman unshare cat /proc/self/uid_map
         0       1002          1
```

After countless hours looking for a solution (including purging all the podman-related packages, restarting the server etc) I ran across 

> Could you try doing `podman system migrate` and repull ?

Which finally fixed the problem for me. Now I am able to pull images and 

```
$ podman unshare cat /proc/self/uid_map
         0       1002          1
         1     231072      65536
```

I am not sure how a command designed "Migrate existing containers to a new podman version" helps in a situation when there are no existing containers (since there are no images) but I am happy it finally works.

For the record, this was on Ubuntu 20.04 and podman 3.4.2.

**Comment by guedressel** [comment]
For me it helped to remove the users container storage and let `podman` rebuild it:

    rm -rf $HOME/.local/share/containers/storage

After this `podman pull` worked as expected.

**Comment by brianjmurrell** [comment]
My uid on this system is 11412345.  Might that have something to do with the problem?

**Comment by giuseppe** [comment]
what is in your `/etc/subuid` and /etc/subgid` files?

**Comment by brianjmurrell** [comment]
I've actually opened containers/buildah#3834 about my current problems and those files are at the end of that report.

**Comment by clicktechnology** [comment]
I have a '.' in my username which was not added in the /etc/subuid or /etc/subgid, so  it appeared as

joepublic:165536:65536

and not

**Comment by jdptechnc** [comment]
I solved by 

- Adding entries to `/etc/subuid` and `/etc/subgid` (I was using logging in via SSSD and not a local user, so the entries for my user were not automatically present
- Ran `podman system migrate`

I was actually running ansible-builder, which I presume is actually using podman underneath.

**Comment by gregorydulin** [comment]
The subuid and subgid fixed it for me.

```
$ sudo usermod --add-subuids 10000-75535 USERNAME
$ sudo usermod --add-subgids 10000-75535 USERNAME
```
https://docs.podman.io/en/latest/markdown/podman.1.html?highlight=usermod#rootless-mode

**Comment by fdfytr** [comment]
> The subuid and subgid fixed it for me.
> 
> ```
> $ sudo usermod --add-subuids 10000-75535 USERNAME
> $ sudo usermod --add-subgids 10000-75535 USERNAME
> ```
> 
> https://docs.podman.io/en/latest/markdown/podman.1.html?highlight=usermod#rootless-mode

there is [a good manual ](https://wiki.archlinux.org/title/Podman)in arch wiki

**Comment by bverkron** [comment]
> there is [a good manual ](https://wiki.archlinux.org/title/Podman)in arch wiki

Those instructions (and more specifically `usermod --add-subuids 100000-165535 --add-subgids 100000-165535 $USER && podman system migrate`) fixed the issue for me for _some_ images (such as `alpine`) but not for some internally built images we have. I noticed that earlier in the process the `hello-world` worked but alpine would not until I ran those commands. 

Is there something that would cause this issue to only apply to some images?

**Comment by rhatdan** [comment]
If an image includes more then 65k UIDs it will not work. Basically if you have an image that wants to place a UID of 70k on disk, The kernel will stop the  user namespace from creating it, because the user namespace only has 65k UIDs available.

**Comment by bverkron** [comment]
How do we confirm if that’s what is happening? Does this part of the error indicate how many UIDs are being requested?

`requested 164188:164188`

If yes that’s lower that the 165535 that was set by the user add command.

What would the workaround be? This works with Docker. How are we expected to move from Docker to podman in RHEL 8 and beyond if it cannot even pull images we’ve created in Docker previously?

**Comment by rhatdan** [comment]
It works with docker, because docker is running in the host user namespace as root.

Try running Podman as root and it will work.

The problem with your configuration is that the User UID is within the range of UIDs allocated.

Can you specify a range of UIDs which does not include your users UID.  IE Start at 200000

**Comment by bverkron** [comment]
Meant to edit my comment shortly after posting but didn't hit submit apparently. Read this article and it makes a bit more sense. https://www.redhat.com/sysadmin/rootless-podman

As such I tried clearing out the lines for my user account in /etc/subuid and /etc/subgid and rerunning the command with a higher range
`sudo usermod --add-subuids 200000-265535 --add-subgids 200000-265535 $USER && podman system migrate`

For some reason the command continued to put the original top end of the range. I am not sure why.
`myusername:200000:65536`

... but once I manually edited those files and set it the right way it worked.
`myusername:200000:265536`

```
$ docker pull <private-registry-image>
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Trying to pull <private-registry-image>:latest...
Getting image source signatures
Copying blob 159a7b5d1b30 skipped: already exists
Copying blob 96bd051f1942 skipped: already exists
Copying blob ba9ed3079fc2 done
Copying blob b17b2eb4d9bc done
Copying blob 8725baa6d367 done
Copying config 8f41cd279e done
Writing manifest to image destination
Storing signatures
8f41cd279ead2ebb350e83433eede62d204f63cc00a46743edc9db0456fd1d69
```

Thanks for the assistance.

**Comment by rhatdan** [comment]
LGTM

**Comment by Bhawyya** [comment]
I got the same error - which is not happening for other users following the same steps/command - 

![image](https://user-images.githubusercontent.com/71708460/191042858-3bd37447-1c8d-4a20-b3b4-b5d989a5b5db.png)

**Comment by mdwajid095** [comment]
I have also faced the same issue. My issue resolved when I execute: "sudo -E podman pull image-name"

**Comment by giuseppe** [comment]
that is not a fix.  You are running as root.

You need to make sure your unprivileged user has enough IDs assigned and then run `podman system migrate` to reload the user namespace.

**Comment by Sejoslaw** [comment]
If anyone needs it:

sudo usermod --add-subgids 10000-75535 USERNAME
sudo usermod --add-subuids 10000-75535 USERNAME
podman system migrate
podman pull ....

**Comment by harryssuperman** [comment]
> If anyone needs it:
> 
> sudo usermod --add-subgids 10000-75535 USERNAME sudo usermod --add-subuids 10000-75535 USERNAME podman system migrate podman pull ....

@Sejoslaw Thanks for the commands, help me to solve the problem

**Comment by xpufx** [comment]
> If anyone needs it:
> 
> sudo usermod --add-subgids 10000-75535 USERNAME sudo usermod --add-subuids 10000-75535 USERNAME podman system migrate podman pull ....

If anybody using alpine on the host comes across this error and this solution,   there are a few more things necessary.   https://wiki.alpinelinux.org/wiki/Podman
