### ISSUE TITLE
How can I increase number of CPUs?

### ISSUE THREAD

**Issue by tbrodbeck** [containers/podman#12713]
I have been trying to increase the amount of cpus of my podman because I am not able to start minikube:
```
minikube start --driver=podman --container-runtime=cri-o

😄  minikube v1.24.0 on Darwin 12.0.1
✨  Using the podman (experimental) driver based on user configuration

⛔  Exiting due to RSRC_INSUFFICIENT_CORES: Requested cpu count 2 is greater than the available cpus of 1
```
How can I fix this? I am temporarily have to switch back to docker where it runs without a problem.

I could not find a reliable resource or explanation how to increase the amount of cpus podman uses. 
I have tried 
```
➜  ~ podman system renumber
Error: unrecognized command `podman system renumber`
```

Version (latest from brew):
```
➜  ~ podman --version
podman version 3.4.4
```

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
I don't think that error is coming from Podman.  It looks like a check in Minikube itself.  Are you running Podman as rootless?  Does it work differently if you run as root?

**Comment by afbjorklund** [comment]
The amount of cpus and memory is set when the machine is created, so you will need to re-create it:

```
podman machine stop
podman machine rm
podman machine init --cpus 2 --memory 2048 --disk-size 20
podman machine start
```

 Make sure to save any images and such before deleting, it _might_ be possible to edit the json directly.

**Comment by afbjorklund** [comment]
> I don't think that error is coming from Podman. It looks like a check in Minikube itself

Podman defaults to 1 vCPU and 2 GiB RAM, while `kubeadm` requires 2 vCPU + 2 GiB

**Comment by afbjorklund** [comment]
If there existed any Podman Machine documentation for this, minikube could be linking to it:

```go
        if availableCPUs < cpuCount {
                if driver.IsDockerDesktop(drvName) {
                        out.Styled(style.Empty, `- Ensure your {{.driver_name}} daemon has access to enough CPU/memory resources.`, out.V{"driver_name": drvName})
                        if runtime.GOOS == "darwin" {
                                out.Styled(style.Empty, `- Docs https://docs.docker.com/docker-for-mac/#resources`)
                        }
                        if runtime.GOOS == "windows" {
                                out.String("\n\t")
                                out.Styled(style.Empty, `- Docs https://docs.docker.com/docker-for-windows/#resources`)
                        }
                }

                exitIfNotForced(reason.RsrcInsufficientCores, "Requested cpu count {{.requested_cpus}} is greater than the available cpus of {{.avail_cpus}}", out.V{"requested_cpus": cpuCount, "avail_cpus": availableCPUs})
        }

```

**Comment by rhatdan** [comment]
Interested in adding documentation?

**Comment by tbrodbeck** [comment]
Thanks. I was able to fix the error!
Still, I cannot get minikube starting. So I opened an issue in the minikube Repo, FYI: https://github.com/kubernetes/minikube/issues/13261

**Comment by giuseppe** [comment]
Would it make sense to change the podman machine configuration to use 2 cpus?

**Comment by afbjorklund** [comment]
> Would it make sense to change the podman machine configuration to use 2 cpus?

Possibly, if you want it to run kubeadm ? Otherwise 1 vCPU and 1 GiB _used_ to be fine...

But Lima uses 4 vCPU and 4 GiB by default, so I guess it depends on the situation.

i.e. the available resources on the local laptop, and how many VMs you plan to run ?

**Comment by afbjorklund** [comment]
> Interested in adding documentation?

I think it is documented in the man page:

https://docs.podman.io/en/latest/markdown/podman-machine-init.1.html

But there is no User Manual, as such.

**Comment by rhatdan** [comment]
Aren't these settings available in the containers.conf?

**Comment by afbjorklund** [comment]
> Still, I cannot get minikube starting. So I opened an issue in the minikube repo,

I don't think minikube works with podman machine yet, it failed for me as well.

**Comment by afbjorklund** [comment]
> I could not find a reliable resource or explanation how to increase the amount of cpus podman uses.

https://podman.io/getting-started/installation#macos links to this page for "advanced":

https://github.com/containers/podman/blob/main/docs/tutorials/mac_experimental.md

It doesn't mention either --cpus or containers.conf, for changing the machine init.

**Comment by giuseppe** [comment]
https://github.com/containers/podman/pull/12718 was merged.  Closing the issue

**Comment by tpoxa** [comment]
```podman machine set podman-machine-default --cpus=2```
