### ISSUE TITLE
New race: podman rm -t 0 --all --force: container does not exist in database

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#12740]
This is starting to hit us badly in CI. Super-trivial to reproduce:
```console
$ while :;do bin/podman run --rm -d --name foo quay.io/libpod/testimage:20210610 top; bin/podman kill foo; bin/podman rm -t 0 --all --force || break;done
...
4642ba927711e9f396ee77eff476ec735e1459298193991acc36e58897d2b9b9
foo
b2f95effbf7ba61d91c415d9d3ff9796fba6ea8e30779113167f01a3590ffb28
foo
Error: container b2f95effbf7ba61d91c415d9d3ff9796fba6ea8e30779113167f01a3590ffb28 does not exist in database: no such container
```
For reasons not clear to me, it seems to take 10-15 iterations to fail as rootless, but 1-2 root.

CI failures happen unpredictably, in no specific test, so they're very hard to find and classify. 

### [sys] 177 podman kill - print IDs or raw input
* fedora-35 : sys podman fedora-35 root host
  * PR #12725
    * [12-31 10:12](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5935143033503744/html/sys-podman-fedora-35-root-host.log.html#t--00177)

Another one just now in an in-flight PR: [fedora 35 root host](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4508811338711040/html/sys-podman-fedora-35-root-host.log.html)

**Comment by Luap99** [comment]
I do not understand why we run `podman run --rm ...` followed by `podman rm ...`. Now two processes will try to remove the container (the cleanup process spawned when conmon exits and podman rm). If the cleanup process is faster, `podman rm` will fail because it cannot find the container anymore.

**Comment by Luap99** [comment]
Although this is `podman rm --all`, so I think we should ignore such errors.

**Comment by edsantiago** [comment]
>I do not understand why we run podman run --rm ... followed by podman rm ...

Test `teardown()` runs `rm -t 0 --all --force` as a standard way to clean up and restore to known state.

**Comment by mheon** [comment]
This does strike me as a bug in `podman rm --all`, yeah - classic TOCTOU between database lookup of containers and trying to remove them.

**Comment by rhatdan** [comment]
We are attempting to catch this error everywhere I looked yesterday.  So this must be berried somewhere deep.

**Comment by rhatdan** [comment]
The error is here I believe https://github.com/containers/podman/blob/main/pkg/domain/infra/abi/containers.go#L333-L346

Can you change your script to add --ignore, should fix the problem.

**Comment by rhatdan** [comment]
Should --all imply --ignore?

**Comment by Luap99** [comment]
If the error comes from getContainersByContext then ignoring the error is useless since it will only try to remove the containers that were given by name not **all**
