### ISSUE TITLE
[RFE] `podman volume mount|unmount` command

### ISSUE THREAD

**Issue by mskarbek** [containers/podman#12768]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I would like to be able to mount a volume  independently of the container.
Use case: creation of a volume that is then mounted and populated with autogenerated config files before it is attached to the newly created container.
Yes, I know that I can just create directory, put config files there and just use `-v` or `tar` content of that directory and `volume import` it. 
The above is a convenience request that will simplify a little dealing with volumes (skipping `tar` steps) and allow keeping everything as a programmatically declared volume without tracking separately random directories populated outside the `podman volume` functionality.

**Comment by flouthoc** [comment]
@mskarbek Thanks for creating the issues.

Could we use `volume` with `type=bind` ? https://github.com/containers/podman/pull/12687
It should allow `bind` mount of arbitrary location from `host` as a `podman volume`

**Comment by rhatdan** [comment]
Do you want `podman volume mount NAME destination`?

**Comment by rhatdan** [comment]
Or would 
$mntpnt=$(podman volume mount NAME)
$podman volume umount NAME

Be enough?

**Comment by mskarbek** [comment]
@rhatdan this can behave the same way as `podman mount`/`buildah mount` so `$mntpnt=$(podman volume mount NAME)` will be ok.

**Comment by rhatdan** [comment]
I am fine with adding it.  Interested in opening a PR?

**Comment by flouthoc** [comment]
@mskarbek @rhatdan 
I might be missing something but all the volumes should be already accessible by host. Especially if driver is `local` and for any other driver src of mountpoint must be accessible from host first.

So if you do `podman volume inspect $myvol` we should able to see the mountpoint.

If only `mountpoint` is needed this should be pretty enough right ? 
```bash
$ podman volume inspect myvol | jq '.[0].Mountpoint'
``` 

Again i might be interpreting the issue wrongly. But this is what I remember while discussing something with @mheon in past over an older PR.

**Comment by mskarbek** [comment]
@flouthoc your logic is sound when it comes to the plain `local` volumes, I don't need to mount them, they are just directories, but:
```
podman volume inspect eb712af1-acfa-4eb7-9c99-3ab3e5777d9c
[
    {
        "Name": "eb712af1-acfa-4eb7-9c99-3ab3e5777d9c",
        "Driver": "local",
        "Mountpoint": "/var/lib/volumes/storage/eb712af1-acfa-4eb7-9c99-3ab3e5777d9c/_data",
        "CreatedAt": "2021-12-20T22:11:38.745502358+01:00",
        "Labels": {},
        "Scope": "local",
        "Options": {
            "device": "dfe93b5a-632d-44c4-98b9-7cff969b3a1d/datafs/var/lib/volumes/storage/eb712af1-acfa-4eb7-9c99-3ab3e5777d9c",
            "type": "zfs"
        }
    }
]
```
This is a ZFS dataset with `mountpoint=legacy` declared as a volume in podman. Such dataset will be mounted during container start, the content of that file system is not always available under `"Mountpoint": "/var/lib/volumes/storage/eb712af1-acfa-4eb7-9c99-3ab3e5777d9c/_data"`.
Yes, I can automate everything, but the issue is about keeping user experience as podman-focused as possible.
Besides of test/prod envs we use VMs for our developers with RHEL 8 prebuild image with ZFS - ZFS is important part providing snapshots and send/receive functionality for datasets that are used on developers VM-s, it's a convenient way of shipping test database content for example.
Those VMs are partially automated with Ansible, but developers need normal access to them, and they interact with podman daily. It would be much easier for them to not think about looking for datasets, mounting them, unmounting, but to keep everything nice and tidy under one coherent podman experience. They are familiar with `podman mount` functionality, so replicating that experience would be appreciated. 
As I previously stated it is a convenience request not a dealbreaker. ;)

**Comment by flouthoc** [comment]
@mskarbek Ah fair got it. You want mounting experience to be more podman oriented. That's a fair request.

**Comment by rhatdan** [comment]
@flouthoc Yes,certain non local file systems are mounted (tmpfs, bind, nfs, and fancy docker-volume-plugins) could be mounted.

Currently when  you run a container for the first time with a volume podman mounts the volume in container/storage then setup a bind mount into the container.  @mskarbek is looking to only do step 1, where we do the mount.  All of the code is there to do this, but someone needs to implement the CLI and then call into the functions to make it happen.  

CLI should only be local,  not remote API.

**Comment by boaz0** [comment]
@rhatdan can I work on this?

**Comment by rhatdan** [comment]
Yup

**Comment by rhatdan** [comment]
@boaz0 any progress?
