### ISSUE TITLE
Error: exec: "qemu-system-x86_64": executable file not found in $PATH after installing via homebrew on MacOS Monterey

### ISSUE THREAD

**Issue by alphabet5** [containers/podman#12775]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Install homebrew

2. run `brew install podman`

3. run `podman machine init`

**Describe the results you received:**

```bash
Error: exec: "qemu-system-x86_64": executable file not found in $PATH
```

**Describe the results you expected:**

```bash
Downloading VM image: fedora-coreos-35.20220103.2.0-qemu.x86_64.qcow2.xz
```

**Additional information you deem important (e.g. issue happens only occasionally):**

The fix was running `brew link qemu && brew reinstall qemu` but it would be ideal if this wasn't necessary.

Error when trying to start the machine after running `brew link qemu` and before `brew reinstall qemu`

```
j@MacBook-Pro ~ % podman machine start
INFO[0000] waiting for clients...
INFO[0000] listening tcp://127.0.0.1:7777
INFO[0000] new connection from  to /var/folders/b5/yrr83mns5fs6sz4vykhjxgfm0000gn/T/podman/qemu_podman-machine-default.sock
Waiting for VM ...
qemu-system-x86_64: Unknown Error
Error: dial unix /var/folders/b5/yrr83mns5fs6sz4vykhjxgfm0000gn/T/podman/podman-machine-default_ready.sock: connect: connection refused
ERRO[0003] cannot receive packets from , disconnecting: cannot read size from socket: EOF
ERRO[0003] cannot read size from socket: EOF
```

I'm not yet sure if this is reproducible, if not I will close this but hoping this would provide some help if someone runs into the same issue.

**Output of `podman version`:**

```
j@MacBook-Pro ~ % podman version
Client:
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Wed Dec  8 12:41:11 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 15:45:07 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
% podman info --debug
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "35"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.12-200.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1337417728
  memTotal: 2061381632
  ociRuntime:
    name: crun
    package: crun-1.4-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4
      commit: 3daded072ef008ef0840e8eccb0b52a7efbd165d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 4m 12.67s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 1638999907
  BuiltTime: Wed Dec  8 21:45:07 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
j@MacBook-Pro ~ % brew list podman
/usr/local/Cellar/podman/3.4.4/bin/podman
/usr/local/Cellar/podman/3.4.4/bin/podman-remote
/usr/local/Cellar/podman/3.4.4/etc/bash_completion.d/podman
/usr/local/Cellar/podman/3.4.4/libexec/gvproxy
/usr/local/Cellar/podman/3.4.4/share/fish/vendor_completions.d/podman.fish
/usr/local/Cellar/podman/3.4.4/share/man/ (160 files)
/usr/local/Cellar/podman/3.4.4/share/zsh/site-functions/_podman
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@ashley-cui PTAL

**Comment by michaelkrasa** [comment]
I have an issue almost identical to this on M1 Max:
```
➜  ~ podman machine start
INFO[0000] waiting for clients...
INFO[0000] listening tcp://127.0.0.1:7777
INFO[0000] new connection from  to /var/folders/_r/ym4h63j94l7b305575s09q200000gq/T/podman/qemu_podman-machine-default.sock
Error: fork/exec /usr/local/bin/qemu-system-x86_64: no such file or directory
ERRO[0000] cannot receive packets from , disconnecting: cannot read size from socket: EOF
ERRO[0000] cannot read size from socket: EOF
```

**Comment by ashley-cui** [comment]
Let me update my mac and see if I can reproduce it, it might be a weird path error. 

@michaelkrasa, yours seems like a different issue, do you happen to have rosetta installed?

**Comment by ssanchez1-godaddy** [comment]
Same issue on mine 
Error: exec: "qemu-system-x86_64": executable file not found in $PATH

**Comment by baude** [comment]
@michaelkrasa i would guess you do have rosetta installed which is why you are seeing calls to the intel qemu system.

**Comment by vrothberg** [comment]
Friendly ping.

**Comment by marcoblos** [comment]
I was running into the same problem for few hours today @michaelkrasa - my first time trying to install/use podman.

I fixed it uninstalling podman, uninstalling brew, etc, and then installing all over again.

I'm assuming I had an old version of brew which I installed under emulation "arch -x86_64 zsh" January last year.

After that, I got the correct version of qemu when running podman machine init and podman machine start.

**Comment by michaelkrasa** [comment]
I'll give it one more try, already reinstalled the whole lot. I migrated
from an Intel MacBook and I can't think of anything it could be. I don't
have Rosetta installed btw.

**Comment by marcoblos** [comment]
@michaelkrasa I have rosetta installed here, not sure that is needed or not, as I mentioned, first time using/installing podman. One important thing I found is that you have to install homebrew in a specific path when using Apple M1. It must be cloned and installed from /opt/homebrew.

**Comment by michaelkrasa** [comment]
I've finally fixed this issue, I reinstalled homebrew but that most likely wasn't the problem. I never removed the initial container that I was trying to start. Once I realized this mistake I just deleted it using `podman machine rm podman-machine-default` and ran `podman machine start` to finish the usual installation sequence.

**Comment by rhatdan** [comment]
I am assuming this is not an issue that Podman can fix, so closing.  Reopen if I am mistaken.

**Comment by pvgb** [comment]
@millawell I tried reinstalling Homebrew and it did not solve the issue that was first reported. I am using qemu 6.2 and podman 4.03

**Comment by baude** [comment]
@pvgb if you do a `which qemu-system-x86_64` does it return anything?

**Comment by Maransatto** [comment]
@baude 
I'm facing the same issue but on Linux Ubuntu, I ran the commend you suggested but it was unable to locate the package.

❯ which qemu-system-x86_64
qemu-system-x86_64 not found

**Comment by rafapolo** [comment]
Had the same error on Ubuntu but here, but ` sudo apt install qemu-system-x86` did the job.

maybe a  `brew install qemu` works for you?

**Comment by vijaypratapsingh007** [comment]
Here is the final fix for everyone... coming to this page later on...

```
brew install qemu
brew link qemu
```

**Comment by FairyPenguin** [comment]
Linux Mint (Ubuntu based) 

This worked for me:

```
sudo apt-get install qemu-system-x86

```
