### ISSUE TITLE
How do communicate podman from server1 to podman from server2

### ISSUE THREAD

**Issue by Taymindis** [containers/podman#12785]
I am currently designing a podman architecture, if I have 2 vm system with podman support. 

how can I communicate each other via cni network? Should I either use `network=host` or `published port` approach, or am I missing out of some podman feature ??

Giving an illustration below, How should I clustered the connection? By using which ip interface?

![image](https://user-images.githubusercontent.com/14217761/148745354-9126228c-3f9a-4026-b48b-b59c7e3ac5fa.png)

**Comment by mheon** [comment]
Theoretically, you could use a multi-tenant-capable CNI driver to do this - CNI was originally designed to work with Kubernetes, so it's definitely capable of this sort of work.

However, Podman in general is very much focused on single-node only use, so I can say that I personally have never seen this done before, and I don't think anyone on the Podman team has much in the way of expertise about this.

**Comment by Luap99** [comment]
Yeah likely possible with the right cni plugins but this is not really supported by us. I recommend to just forward the needed ports from the host into the container and then connect to the host ip.
