### ISSUE TITLE
Cannot pause rootless container (cgroup_manager = "cgroupfs"), container cgroup is empty

### ISSUE THREAD

**Issue by gdm85** [containers/podman#12782]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Using rootless podman, cannot pause a container. All containers have an empty cgroup, which seems to be the root cause of the problem.

System is using cgroups v2 (without systemd) but they do not really seem to be used at all.

**Steps to reproduce the issue:**

This is a stock Debian Bullseye with some configuration hardening.
Kernel has command-line options `cgroup_enable=memory swapaccount=1` and sysctl option `kernel.unprivileged_userns_clone=0`
`/proc` is mounted with options `hidepid=2,gid=procadmin` and non-root user is **not** in `procadmin` group

1. `podman run --name=sleeper -d --rm debian:buster sleep inf`
2. `podman pause sleeper`
3. see error

**Describe the results you received:**
```
2022-01-09T18:45:49.000950560Z: cannot pause the container without a cgroup
Error: `/usr/bin/crun pause b4e7e2a6613a46fafb11ffd17576e67081ec6e1d1f63232f35cd1170f2a32ed0` failed: exit status 1
```

**Describe the results you expected:**

No error and `podman pause` should successfully pause the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

The machine is using cgroups v2 but when I inspect the running container I see that there is no cgroup path so this container never got one; I am using `cgroupfs` as manager and not `systemd`.

The user is logged in via SSH (root) and then switched to non-root with `su -l non-root-user`

**Output of `podman version`:**

```
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.6
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 8
  distribution:
    codename: bullseye
    distribution: debian
    version: "11"
  eventLogger: file
  hostname: melusine
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.84
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 3938795520
  memTotal: 16432111616
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: ea1fe3938eefa14eb707f1d22adff4db670645d6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /tmp/podman-run-1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.4
  swapFree: 18187878400
  swapTotal: 18187878400
  uptime: 5h 51m 15.72s (Approximately 0.21 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/debuser/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.10.3
        fuse-overlayfs: version 1.5
        FUSE library version 3.10.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/debuser/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 39
  runRoot: /tmp/podman-run-1000/containers
  volumePath: /home/debuser/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.4.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 100:3.4.2-1 amd64 [installed]
podman/unknown 100:3.4.2-1 arm64
podman/unknown 100:3.4.2-1 armhf
podman/unknown 100:3.4.2-1 i386
podman/unknown 100:3.0.1-2 ppc64el
podman/unknown 100:3.4.2-1 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

I am using the latest version released (`deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_11/ /`) and checked that changelog between 3.4.2 and 3.4.4 does not have relevant changes.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical

**Comment by mheon** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
cgroups are not used by rootless when running with cgroupfs.   You need to setup one manually and then use `--cgroup-parent` if you really want to use them

**Comment by gdm85** [comment]
@giuseppe thanks, I start to understand things better. Shall we update documentation about this? I could not find anything (my bad if documentation is already clear and I am failing to find/interpret it).

Current docs say (https://docs.podman.io/en/latest/markdown/podman.1.html?highlight=cgroupfs#cgroup-manager-manager):
> Note: CGroup manager is not supported in rootless mode when using CGroups Version V1.

Instead it could say:
> Note: CGroup manager is not supported in rootless mode when using CGroups Version V1; when using 'cgroupfs' in rootless mode you must use --cgroup-parent to with a manually-setup cgroup

The in-comments documentation in containers.conf could also mention something about this.

**Comment by giuseppe** [comment]
@gdm85 are you interested in opening a PR to improve the documentation?

**Comment by gdm85** [comment]
Sure, why not. I am just new around here: would changing some file under `docs/` in this repository be sufficient? (and perhaps the default `containers.conf`, if I manage to find it).

The Wiki does not seem to contain much about this so I guess I do not need to improve it.

**Comment by giuseppe** [comment]
> Sure, why not. I am just new around here: would changing some file under `docs/` in this repository be sufficient? (and perhaps the default `containers.conf`, if I manage to find it).

yes thanks, that would be enough.
