### ISSUE TITLE
it's difficult to find API documentation for specific release

### ISSUE THREAD

**Issue by dwmarshall** [containers/podman#12796]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

See #12777 in which it is very difficult to determine the API for the version of podman I am using.

The API links in documentation point to https://docs.podman.io/en/latest/_static/api.html and there's no way to change version as one can ordinarily do on https://docs.podman.io/en/latest/ where there's a dropdown in the lower-right of the page.

You can manually munge the the URL for api.html in an effort to locate the documentation for previous versions, but that's not always effective or accurate. (To wit, I can access much older documentation that shows the request syntax that I was given to resolve #12777, but it's not clear how to see the full API that matches my exact version: `APIVersion: 3.3.1`

**Steps to reproduce the issue:**

1. Try to find the API documentation for the version of podman you are using.

**Describe the results you received:**

I get the latest API documentation, which is not accurate for the version I am using.

**Describe the results you expected:**

I would like to see the complete API for the version I am using with confidence that the request parameters and bodies are correct.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

See #12777 for `podman version` and `podman info --debug` for this issue.

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@baude was looking into this
