### ISSUE TITLE
Add dependencies to `podman generate systemd`

### ISSUE THREAD

**Issue by tdobrovolny** [containers/podman#12809]
/kind feature

**Description**
A commonly generated service unit configuration file contains `network-online.target` and mounts for `/var/run/container/storage` dependencies only. The container often needs other dependencies to run, and these must be added to the generated file manually.

I suggest adding the following options to the `podman generate systemd` command, which would represent the appropriate option in the [[Unit] section](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#%5BUnit%5D%20Section%20Options) (for example `--wants <systemd-uinit-name>`, `--requires <systemd-uinit-name>`, `--after <systemd-uinit-name>`).

**Comment by rhatdan** [comment]
Please open a PR to add them.

**Comment by Luap99** [comment]
It looks like this is merged so we can close this issue
