### ISSUE TITLE
why podman start exit with 125 in a crontab job

### ISSUE THREAD

**Issue by Loches525** [containers/podman#12800]
I want to have a container monitor script to auto start container if container was down. I run podman stop to shut down a container in advance. Then I set the job into crontab, the podman start command will failed with an exit code of 125, rather than 0. The crontab job is set under root, and the start command in the script is running normally with exit code of 0 if I directly run "bash test_start.sh" in the terminal. Why only will exit with 125 in a crontab job?

[script]
test_start.sh
#! /bin/bash
podman start test
echo $? >> /tmp/test.txt

[crontab]
* * * * * /bin/bash /app/test_start.sh

OS version: redhat 8.2
podman version: 3.2.3

**Comment by rhatdan** [comment]
Do you see anything in the log files?
Can you do this with the --restart option?

**Comment by Luap99** [comment]
The best way to monitor a container is using systemd units, check out the `podman generate systemd` command.
If you get a 125 exit code you should get a error message on stderr. We need this to understand your issue.

**Comment by zhangguanzhang** [comment]
[script]
test_start.sh
```
#! /bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin # add this line
podman start test
echo $? >> /tmp/test.txt
```

**Comment by rhatdan** [comment]
Do you see anything reported on stderr in syslog from this podman command?

podman start test 2> /tmp/errors.log

Might show you something as well.

I have a feeling this might be SELinux.

**Comment by Loches525** [comment]
> [script] test_start.sh
> 
> ```
> #! /bin/bash
> export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin # add this line
> podman start test
> echo $? >> /tmp/test.txt
> ```

Thanks, it works. How do you know that😺

**Comment by zhangguanzhang** [comment]
> > [script] test_start.sh
> > ```
> > #! /bin/bash
> > export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin # add this line
> > podman start test
> > echo $? >> /tmp/test.txt
> > ```
> 
> Thanks, it works. How do you know that😺

This is a very common problem with Linux, just like the first contact Linux is searching to withdraw from the interaction of the VI command.
/close
