### ISSUE TITLE
API: Wrong definition of docker compatible API in podman swagger

### ISSUE THREAD

**Issue by idleroamer** [containers/podman#12804]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I know there has been substantial effort into providing docker compatible API in podman 2.0 but it seems the swagger/OpenAPI definition of those APIs are not updated accordingly.
The only swagger definition of podman I could get my hand on https://storage.googleapis.com/libpod-master-releases/ has many regressions from Docker API even though podman engine itself actually behaves compliant to Docker API.

The list of those incompatibilities is long just some examples to check:

Operations: 
* ExecInspect: response "200" is missing the output schema
* ContainerCreate: is missing input parameters
* ContainerList: input parameters digress from Docker API
* NetworkCreate: resonse value "200" instead of "201 with wrong definition
...

**Steps to reproduce the issue:**

Check https://storage.googleapis.com/libpod-master-releases/<any release> against [Docker API](https://github.com/containers/podman/blob/v3.1/vendor/github.com/docker/docker/api/swagger.yaml)

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes, `v4.0.0-rc1` have still lots of inconsistencies.

**Comment by rhatdan** [comment]
Care to open a PR to fix this?

**Comment by idleroamer** [comment]
@rhatdan Thanks for quick reply.
Hopefully I can help with some of those but can't image short-term to be able to help with all.
I appreciate some guide where to start. Like how those APIs are generated, I can't locate them in this repo.

**Comment by mheon** [comment]
@idleroamer They live in https://github.com/containers/podman/tree/main/pkg/api/server - for example https://github.com/containers/podman/blob/main/pkg/api/server/register_exec.go#L11-L76 has full swagger for our Docker-compatible Exec endpoint.

Please be aware that only the endpoints marked "compat" (e.g. on line 11 of the snippet I linked) are Docker-compatible, the others are Podman-specific and we do not expect those to conform to the Docker API. Please also be aware that we're presently targeting v1.40 of the Docker API, and whatever changes were in v1.41 haven't landed yet.

**Comment by rhatdan** [comment]
@idleroamer Any progress?

**Comment by idleroamer** [comment]
not yet found the time, kind of busy recently. Hopefully in near future.

**Comment by rhatdan** [comment]
@idleroamer Progress?

**Comment by jwhonce** [comment]
@idleroamer I have picked up this issue. 

ContainerCreate appears to have all the options for the compatibility API listed. Were you looking for documentation on the fields?

**Comment by jwhonce** [comment]
@idleroamer I see two differences in ContainerList, we support an additional query parameter `external` which need not be used. And the filter `isolation`, is not supported as podman service does not support windows. Did you expect the unsupported filter to be ignored?

**Comment by jwhonce** [comment]
@idleroamer Do you have an audit tool you were using or did you find these issues coding against the API?
