### ISSUE TITLE
Can't copy files to rootless container using `podman cp`.

### ISSUE THREAD

**Issue by KoxSosen** [containers/podman#12816]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Install Debian 11, and follow the rootless install guide.

2. Create a named volume.

3. Start a container with the `-v named_volume:/path/` command option, and the ` userns=keep-id` flag. Make sure to use an image that sets an unique user that is not present on the host machine, and is not root.

4. Make a file on the host machine, and use `podman cp` to copy the file. Example: 
```bash
touch test.txt && \
podman cp test.txt named_volume:/path/
```

**Describe the results you received:**

```
Error: 2 errors occurred:
        * error determining run uid: user: unknown user error looking up user "runner"
        * error copying from host: copier: get: "/home/admin/transfer/import/tmpproxy/data/test.txt": error copying /home/admin/transfer/import/tmpproxy/data/test.txt: io: read/write on closed pipe
```

**Describe the results you expected:**

The files get copied to the named volume/container filesystem.

**Additional information you deem important (e.g. issue happens only occasionally):**

This seems to happen with every kind of file/folder.

**Output of `podman version`:**

```
podman version v3.0.1
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

No, I'll do futher testing soon.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Bare metal server running Debian 11.

**Comment by vrothberg** [comment]
Thanks for reaching out! I've not seen this specific error yet. Can you try with a more recent version of Podman?

**Comment by KoxSosen** [comment]
Sure. May I ask, is there any specific reason why the official Debian packages aren't updated to a newer release?

**Comment by vrothberg** [comment]
> Sure. May I ask, is there any specific reason why the official Debian packages aren't updated to a newer release?

If you want to have more recent packages in the Debian universe, you can use Debian testing or Debian experimental. Debian stable does not update packages to new version in general but only fixes security issues.

I run Fedora as I enjoy the mix of stability while getting regular updates on things I care about (Firefox, kernel, developer tools, container tools etc.).
