### ISSUE TITLE
Equivalent command for `docker context`

### ISSUE THREAD

**Issue by benatshippabo** [containers/podman#12811]
There does not seem to be an equivalent command in Podman for `docker context`. Various vscode extensions use this in some form such as the vscode Docker extension.

_Originally posted by @mheon in https://github.com/containers/podman/discussions/12745#discussioncomment-1948110_

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by rhatdan** [comment]
@benatshippabo interested in working on it?

**Comment by mheon** [comment]
The full suite is documented at https://docs.docker.com/engine/reference/commandline/context/

They seem to be vaguely analogous to our `podman system connection` commands, but with additional features on top.

**Comment by jwhonce** [comment]
@mheon @baude 

After a quick review, I think we should target this for 4.1+. If we do not implement the deprecated flags/fields then our `system connection` data appears to be subset of the `context` data. Implying no breaking changes required, just adding fields or aliases to fields, and commands. 

This would also allow us to encapsulate the connection/context handling in a c/common package. Something the gvproxy author was also interested in having.  /cc @ashley-cui @cdoern 

**Action Item:**

1. How are the context Storage fields used?
2. _--docker_ should be aliased to _--podman_ flag

**Comment by rhatdan** [comment]
We could handle this like we do with podman buildx and attempt to hide the implementation.  IE if a user has a script that executes it will work, but we don't document it.

I am not sure how complex it is.

**Comment by rhatdan** [comment]
@Luap99 Do you have time to take a stab at this?  I think the main goal would be to allow vscode to work with it.

**Comment by rhatdan** [comment]
@flouthoc Any time to work on this?

**Comment by rhatdan** [comment]
@cdoern Interested in this one?

**Comment by ankanroy-code** [comment]
hello everyone i am trying to contribute into this project. I am new to go-lang so its taking time. i already create a command called context, using the README file in the _cmd/podman_ . also create sub commands for it for it. I am just playing around with the source code, trying to understand how things work. Can anyone tell me what should i do next. Especially to solve this issue or another, that you think would be better. how can i contribute. I am currently fully free, so can spend good amount of time on the project.

**Comment by ankanroy-code** [comment]
@cdoern  the command i created was a random command that i named `context` it has nothing to do with `podman context` I was just trying to understand the code base.

**Comment by rhatdan** [comment]
The basic idea is to implement the commands that docker context implements, but tie it into podman system connection.
```
$ docker context --help

Usage:  docker context COMMAND

Manage contexts

Commands:
  create      Create a context
  export      Export a context to a tar or kubeconfig file
  import      Import a context from a tar or zip file
  inspect     Display detailed information on one or more contexts
  ls          List contexts
  rm          Remove one or more contexts
  update      Update a context
  use         Set the current docker context

Run 'docker context COMMAND --help' for more information on a command.

$ podman system connection --help
Manage remote API service destinations

Description:
  Manage remote API service destination information in podman configuration

Usage:
  podman system connection [command]

Available Commands:
  add         Record destination for the Podman service
  default     Set named destination as default
  list        List destination for the Podman service(s)
  remove      Delete named destination
  rename      Rename "old" to "new"
```

docker context create -> podman system connection add
docker context use -> podman system connection default
docker context ls -> podman system connection list
docker context rm -> podman system connection remove

Would need to look at docker context inspect and see if we can do something similar with podman.

export, import, update would need to be examined to see if they apply to Podman, or should be just implemented as not supported.

**Comment by rhatdan** [comment]
I would also prefer that these be hidden for now, so they would work if someone scripted, but we don't need to advertise use of these.

**Comment by ankanroy-code** [comment]
hey i am trying to solve this issue, but could not for now. i asked this question on cobra GitHub issue, about how can i Alias
`docker context create -> podman system connection add` [here](https://github.com/spf13/cobra/issues/1725). its seems we have to re implement a lot of the code from `system connection`

**Comment by rhatdan** [comment]
Looker for podman buildx.
./cmd/podman/images/buildx.go

This is linking podman buildx->podman build.

Bottom line to this is just to add the cobra calls and then have them call into the system connection functions.

**Comment by stweil** [comment]
[`ddev`](https://ddev.readthedocs.io/en/stable/) requires `docker context inspect`. Maybe more is missing to use `ddev` with `podman`, but that's the first problem.

**Comment by cdoern** [comment]
> @cdoern @ashley-cui @vrothberg @umohnani8 I thought we had an intern working on this? I think we should raise the priority if noone is working on it.

on the backlog document we were looking at last week I noticed that no one got assigned to this. I think there is a debate of how this is to be implemented. I should probably work on it since I am currently redesigning how podman system connection works.

**Comment by rhatdan** [comment]
A patch supporting podman context was just merged.

**Comment by chughts** [comment]
is this `podman context` supported as of podman 4.2 ?  

https://podman.io/releases/2022/08/17/podman-release-v4.2.0.html

**Comment by rhatdan** [comment]
Nope looks like it is in 4.3.0
https://github.com/containers/podman/releases/tag/v4.3.0
