### ISSUE TITLE
Vscode docker extension has trouble connecting to Podman

### ISSUE THREAD

**Issue by benatshippabo** [containers/podman#12810]
Hi, so I ran the following commands:

```sh
# based on this blog post https://www.redhat.com/sysadmin/podman-mac-machine-architecture
brew install podman
pip3 install podman-compose
podman machine init
podman machine start

# adding the Podman ssh key to the ssh agent
# as instructed here: https://github.com/microsoft/vscode-docker/issues/3367#issuecomment-1005993552
ssh-add ~/.ssh/podman-machine-default

# to get the ssh path
podman system connection ls
```

And it seems to work fine when testing in the cli with `podman` and `podman-compose`, but when I try to integrate Podman with the vscode Docker extension and the Remote Containers extension, that is where I start encountering trouble.

For the record, I have the following configs set in attempt to get everything working:

```json
{
  "docker.dockerPath": "podman",
  "docker.host": "ssh://core@localhost:50685",
  "docker.explorerRefreshInterval": 5000,
  "docker.dockerodeOptions": {
    "socketPath": "ssh://core@localhost:50685/run/user/1000/podman/podman.sock"
  }
}
```

And then I restarted the extension host. But the Docker extension just keeps getting ENOENT when trying to retrieve the containers, any idea why the extension is having trouble connecting? [I have worked with the extension author and they helped me as much as they could, but we are stuck on why the extension is having trouble connecting to the socket.](https://github.com/microsoft/vscode-docker/issues/3367#issuecomment-1006826438)

_Originally posted by @benatshippabo in https://github.com/containers/podman/discussions/12745_

**Comment by baude** [comment]
can you provide more detailed instruction on how to set this up?  I have not used this before.  For example, I have no idea what to do with the config you provided.

**Comment by benatshippabo** [comment]
> can you provide more detailed instruction on how to set this up? I have not used this before. For example, I have no idea what to do with the config you provided.

Thanks for looking into this @baude, here are the steps to insert the settings:

1. `cmd shift p` to access the command menu
2. type "settings" into the search and then select the "Preferences: Open Settings (JSON)" option 
![image](https://user-images.githubusercontent.com/66273043/149404865-706ad3e3-1e5c-4f48-87c7-af2f03acd76e.png)
3. once you have that json file open, you can just append the specified settings into the file

**Comment by baude** [comment]
then what?

**Comment by benatshippabo** [comment]
> then what?

And then install the docker extension, you can do this by 
1. clicking on the extensions icon
2. searching docker for the extension
3. once installed, please click on the docker extension and then you will get the ENOENT error message
![image](https://user-images.githubusercontent.com/66273043/149418926-b143085a-bdf3-459f-9b7b-254054f5c6ee.png)

**Comment by benatshippabo** [comment]
Closing this based on https://github.com/microsoft/vscode-docker/issues/3367#issuecomment-1017781332
