### ISSUE TITLE
podman image scp should not use machinectl

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#12829]
Followon to #12827.

`podman image scp`, when run as root, uses machinectl. machinectl is evil:
```console
# machinectl shell -q esm@.host /usr/bin/false;echo $?

0
```
That is: (1) it always spits out a useless unwanted blank line; and (2) it does not propagate exit status. This is actually documented:
```
        Note that machinectl shell does not propagate the exit code/status
        of the invoked shell process. Use systemd-run instead if that
        information is required (see below).
```
I don't know anything about `machinectl` nor `systemd-run`. I don't know why it was necessary to use `machinectl` in this code. Someone with that expertise will need to figure out how to resolve this.

**Comment by Luap99** [comment]
I looked at this and if I remember correctly systemd-run will not create the needed login session only machinectl does.
Not getting the correct exit code is definitely a problem, maybe we can combine both machinectl and systemd-run, e.g. run `machinectl sleep` to spawn the session and then use systemd-run to connect to it.

**Comment by Luap99** [comment]
Mhh `systemd-run --machine user@.host ...` always errors for me so I have no idea how this is supposed to be used instead of machinectl.

**Comment by cdoern** [comment]
There was a version without machinectl, I will go back and see if I can find that code. We can always just error out if `su` does not work.

**Comment by akhilles** [comment]
Would it be possible to not depend on systemd at all for `podman image scp`? It makes it quite difficult to use in Alpine for example.

**Comment by Luap99** [comment]
It should not depend on systemd, this is only required to create a proper login session on systemd systems.

**Comment by cdoern** [comment]
I did not realize this one was still open. Now that scp is in a much more developed state, let me look back and see if withering away systemd dependencies is at all possible.

**Comment by rhatdan** [comment]
@cdoern any progress?

**Comment by edsantiago** [comment]
Looks abandoned.
