### ISSUE TITLE
docker incompatibility: commit --change is split on spaces.

### ISSUE THREAD

**Issue by leahneukirchen** [containers/podman#12830]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The `changes=` parameter of  `/commit` of the compat API is parsed incorrectly, making it impossible to use some dockerfile commands.

**Steps to reproduce the issue:**

1. Send a request `POST /v1.40/commit?changes=EXPOSE+9999&container=$someid`

2. Alternatively use docker to speak to podman: 
`DOCKER_HOST=unix:///run/podman.sock docker commit --change 'EXPOSE 9999' $someid`

**Describe the results you received:**

500 Internal Error
`CommitFailure: invalid change "EXPOSE" - must be formatted as KEY VALUE`

**Describe the results you expected:**

That it commits a new image with the changes applied.

**Additional information you deem important (e.g. issue happens only occasionally):**

This happens because the changes string is split on any whitespace, instead of newlines:
https://github.com/containers/podman/blob/2cdab5d53923784e72020d70ee9375518f19f9b6/pkg/api/handlers/compat/images.go#L140

Then `util.GetImageConfig` parses `EXPOSE` and `9999` separately and errors.

Note that the libpod API works correctly: 
https://github.com/containers/podman/blob/main/pkg/api/handlers/libpod/images.go#L542

**Output of `podman version`:**

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.5
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes

**Comment by leahneukirchen** [comment]
Upon further investigation, it shows that libpod doesn't split the string at all, but expects multiple occurrences of the parameter. So it behaves differently than docker in yet another way.

**Comment by rhatdan** [comment]
Is this a different API IE the libpod api or the compat api or requiring multiple occurrences?

**Comment by leahneukirchen** [comment]
Official Docker API: one parameter, split on newline
Podman compat API: one parameter, split on whitespace (definitely wrong)
Podman libpod API: multiple parameter, not split at all

I guess the libpod API is ok, albeit different.

**Comment by rhatdan** [comment]
Care to open a PR to fix?

**Comment by jwhonce** [comment]
@leahneukirchen I believe the libpod API makes the most sense. But a fix for the compat API would be great. Are you interested or should I work on it?

**Comment by leahneukirchen** [comment]
There are more issues with the compat API. It seems to parse the body for a container config, but never uses it after:
https://github.com/containers/podman/blob/2cdab5d53923784e72020d70ee9375518f19f9b6/pkg/api/handlers/compat/images.go#L131

I don't have time to go down this rabbit hole for now, I switched our software to use the libpod API for commit.
