### ISSUE TITLE
podman-remote build, with dockerignore, unexpected (wrong) diagnostic

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#12838]
https://github.com/containers/buildah/pull/3576 added an error message and a test for it. This is failing in podman-remote (not podman).

The error emitted by buildah and regular podman:
```
Error: error building at STEP "COPY test1.txt /upload/test1.txt": 
   no items matching glob "[SOURCEPATH]/bud/dockerignore3/test1.txt" copied
   (1 filtered out using [SOURCEPATH]/bud/dockerignore3/.dockerignore):
    no such file or directory
```
The error emitted by podman-remote:
```
Error: error building at STEP "COPY test1.txt /upload/test1.txt":
    checking on sources under "/var/tmp/libpod_builder317490355/build":
    copier: stat: "/test1.txt": no such file or directory
```
(line breaks added for readability)

**Comment by vrothberg** [comment]
I'll take a look. Thanks for opening an issue, @edsantiago!

**Comment by vrothberg** [comment]
Ah, OK.

Since https://github.com/containers/podman/issues/8374, the remote client is parsing the ignore files and excludes matches from being tar'ed up.  This explain the stat error: the file is really not there.

Not sure if we should massage the test OR if we should send the entire context over and let the server exclude the files.

@baude @rhatdan WDYT?

**Comment by rhatdan** [comment]
As long as podman --remote build is doing what is supposed to.

**Comment by vrothberg** [comment]
> As long as podman --remote build is doing what is supposed to.

I am not entirely sure if the context should be pre-processed on the client side. @jwhonce WDYT?

**Comment by rhatdan** [comment]
The issue would then be sending files over that are not needed, so you are wasting bandwidth.  But then again, the excludes also have to happen when you call in with the API.

**Comment by jwhonce** [comment]
@vrothberg I put the pre-processing on the client to not waste bandwidth. Otherwise there is the risk of copying a huge file to the server and then ignoring it.

@rhatdan podman-py processes the ignores on the client.

**Comment by rhatdan** [comment]
Works for me.

**Comment by rhatdan** [comment]
@jwhonce @edsantiago @vrothberg Where are with this one?

**Comment by edsantiago** [comment]
The test is currently disabled in podman: https://github.com/containers/podman/blob/c39dffe83db9fa3cfa6897b971956821f1bbcce2/test/buildah-bud/apply-podman-deltas#L196-L197

Although I have provisions in `apply-podman-deltas` to change the expected error message, I don't have any mechanism to do so only for podman-remote. I'm not especially keen on adding that complexity. If the team's recommendation is to live with that new changed error message, I would suggest just keeping the test as skipped in podman. (But will implement change-error-if-remote or whatever the team recommends)

**Comment by rhatdan** [comment]
I think we can live with the difference and should close this issue.

**Comment by vrothberg** [comment]
> I think we can live with the difference and should close this issue.

OK
