### ISSUE TITLE
Rename pods

### ISSUE THREAD

**Issue by Henry78** [containers/podman#12843]
Allow renaming of pods, i.e. by adding a podman pod rename command.

**Comment by rhatdan** [comment]
@mheon WDYT?

**Comment by cdoern** [comment]
do we treat pods (at least their config) as immutable like we do with containers? Could do a `podman pod clone`...

**Comment by mheon** [comment]
I really dislike the existing `podman rename` command, so I will naturally argue that we should avoid a `podman pod rename` command. A `podman pod clone` does seem useful.

**Comment by rhatdan** [comment]
SGTM

**Comment by cdoern** [comment]
ok I will work on container clone and then pod clone.
