### ISSUE TITLE
robustness: podman image list fails with `Error: error locating item named "manifest" for image with ID "xxx"`

### ISSUE THREAD

**Issue by martinetd** [containers/podman#12854]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Trying to list my images today failed with this error:
```
$ podman image list
Error: error locating item named "manifest" for image with ID "8cd75c2a87b554fae32b28584346db22a5654a47d8e622ddaa13e8e2f839f572": file does not exist
$ podman image inspect 8cd75c2a87b554fae32b28584346db22a5654a47d8e622ddaa13e8e2f839f572
WARN[0000] error determining if an image is a manifest list: error locating item named "manifest" for image with ID "8cd75c2a87b554fae32b28584346db22a5654a47d8e622ddaa13e8e2f839f572": file does not exist, ignoring the error 
Error: error locating item named "manifest" for image with ID "8cd75c2a87b554fae32b28584346db22a5654a47d8e622ddaa13e8e2f839f572": file does not exist
```

**Steps to reproduce the issue:**

1. Not sure how I got there :/ Looking at the timestamp I was happily building images around that time (podman build ...), I probably hit ^c on some of these? and some partial cleanup fudged things up? There was no computer crash involved.
  
2. ... but simply removing any of `$HOME/.local/share/containers/storage/overlay-images/*/manifest` would likely reproduce the issue

3. note `podman image rm` worked with a few warnings, after which listing works again

```
WARN[0000] error determining if an image is a manifest list: error locating item named "manifest" for image with ID "8cd75c2a87b554fae32b28584346db22a5654a47d8e622ddaa13e8e2f839f572": file does not exist, ignoring the error 
WARN[0000] error determining if an image is a parent: error locating item named "manifest" for image with ID "8cd75c2a87b554fae32b28584346db22a5654a47d8e622ddaa13e8e2f839f572": file does not exist, ignoring the error 
WARN[0000] error determining parent of image: error locating item named "manifest" for image with ID "8cd75c2a87b554fae32b28584346db22a5654a47d8e622ddaa13e8e2f839f572": file does not exist, ignoring the error 
Deleted: 8cd75c2a87b554fae32b28584346db22a5654a47d8e622ddaa13e8e2f839f572
```

**Describe the results you received:**

listing images fails

**Describe the results you expected:**

The failed image could just be skipped with a warning?
possibly hinting to remove the image to cleanup.

**Additional information you deem important (e.g. issue happens only occasionally):**

`$HOME/.local/share/containers/storage/overlay-images/images.json` had this content pertaining the culprit:
```
   {
      "big-data-digests" : {
         "sha256:8cd75c2a87b554fae32b28584346db22a5654a47d8e622ddaa13e8e2f839f572" : "sha256:8cd75c2a87b554fae32b28584346db22a5654a47d8e622ddaa13e8e2f839f572"
      },
      "big-data-names" : [
         "sha256:8cd75c2a87b554fae32b28584346db22a5654a47d8e622ddaa13e8e2f839f572"
      ],
      "big-data-sizes" : {
         "sha256:8cd75c2a87b554fae32b28584346db22a5654a47d8e622ddaa13e8e2f839f572" : 1606
      },
      "created" : "2022-01-06T05:50:58.576981129Z",
      "id" : "8cd75c2a87b554fae32b28584346db22a5654a47d8e622ddaa13e8e2f839f572",
      "layer" : "0e5d06a26543bbc89dd2117f7134bac413600f5a8e4864ddd1d64aebce71a435"
   },
```

**Output of `podman version`:**

tried both debian's 3.4.4 and last week's main branch.

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 8
  distribution:
    distribution: debian
    version: unknown
  eventLogger: journald
  hostname: pc-0115
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.0-2-amd64
  linkmode: dynamic
  logDriver: journald
  memFree: 327790592
  memTotal: 16555606016
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 27279302656
  swapTotal: 28276236288
  uptime: 79h 34m 7.69s (Approximately 3.29 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/myuser/.config/containers/storage.conf
  containerStore:
    number: 11
    paused: 0
    running: 1
    stopped: 10
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.10.5
        fuse-overlayfs: version 1.7.1
        FUSE library version 3.10.5
        using FUSE kernel interface version 7.31
  graphRoot: /home/myuser/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 295
  runRoot: /run/user/1000/containers
  volumePath: /home/myuser/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Thu Jan  1 09:00:00 1970
  GitCommit: ""
  GoVersion: go1.17.5
  OsArch: linux/amd64
  Version: 3.4.4
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/master/troubleshooting.md)**

Yes/Yes

**Comment by vrothberg** [comment]
> Not sure how I got there :/ Looking at the timestamp I was happily building images around that time (podman build ...), I probably hit ^c on some of these? and some partial cleanup fudged things up? There was no computer crash involved.

Yes, that is likely the cause.  Such issues usually happen when the process gets killed while writing an image to the storage. Can be a build, pull, commit, etc.

> The failed image could just be skipped with a warning?
> possibly hinting to remove the image to cleanup.

I think that listing should continue to fail.  Warnings are "dangerous" since they can easily be hidden when using the REST API.  I think that users should know immediately when an image has been corrupted.

The problem dealing with such corrupted images is that it's quite a whack-a-mole; such errors can pop up at various places in the stack.  This one is fairly easy to locate though, so I vote for improving the error message to suggest to remove the image to resolve the issue.

**Comment by martinetd** [comment]
hmm and I guess we wouldn't want to automatically remove it in case there's some data to salvage in there.
Might be possible to just remove the bit from the json but that'd leave orphans around -- there's no podman storage fsck, right? And it'd be just as bad as a warning anyway as far as REST API users are concerned.

Okay, fair enough -- I wish better could be done but I can understand your argument, once we get there it's already too late and efforts would better be spent not getting there in the first place (but even then I don't see how images could be added atomically)
Thanks for the added note! :)

**Comment by vrothberg** [comment]
> hmm and I guess we wouldn't want to automatically remove it in case there's some data to salvage in there. Might be possible to just remove the bit from the json but that'd leave orphans around -- there's no podman storage fsck, right? 

Not yet but we've been discussing it a number of times (Cc: @giuseppe @rhatdan)

> Okay, fair enough -- I wish better could be done but I can understand your argument, once we get there it's already too late and efforts would better be spent not getting there in the first place (but even then I don't see how images could be added atomically) Thanks for the added note! :)

Thanks for your understanding.  It really is a hairy thing.  _Ideally_, `podman images` would return the image but report is as corrupted.  I think this could be a nice addition in the future.

**Comment by stellarpower** [comment]
> _Ideally_, `podman images` would return the image but report is as corrupted. I think this could be a nice addition in the future.
I think this is important. Without being able to list images, without digging into the graphroot I'm more or less flying blind. I would happily remove the offending image, but, without being able to see what other images are still okay on my system, what containers use them, etc., it's impossible to know if this image is important or not, work out what the consequences would be of removing it, etc., and begin to decide on how to restore the system to a usable state. I'd understand if say `podman image inspect` just flat out didn't work, but I don't think failure in one image should then spill across to unrelated images and prevent working with them.
