### ISSUE TITLE
CI VMs: need git-daemon

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#12851]
I'd like to point out that the new `git://` tests are not actually running. That's because they require `git-daemon` which is not installed by default.

@cevich I know you've been busy building new CI VMs, and I'm sorry to catch this so late, but when you next build VMs could you please make sure they rpm- and apt-install `git-daemon`?

@jnovy same thing needs to happen with buildah and podman specfiles, in the `-tests` subpackage.

**Comment by cevich** [comment]
> I know you've been busy building new CI VMs

Actually once we're past updating to a new OS version, building updated images becomes boring/routine.  In any case, almost always the real challenge is actually getting the target repo.'s CI to pass with the updated images - though recently that's been pretty smooth as well.

> make sure they rpm- and apt-install git-daemon

I can't add those w/o also building new images.  But we can ignore the result if you wish (assuming it builds successfully)...

**Comment by cevich** [comment]
...k, there ya go.

**Comment by jnovy** [comment]
Also done in CentOS Stream 9: https://gitlab.com/redhat/centos-stream/rpms/podman/-/merge_requests/140

**Comment by rhatdan** [comment]
This looks like it was done. Reopen if I am mistaken.
