### ISSUE TITLE
The podman does not support the socks5h protocol

### ISSUE THREAD

**Issue by pinghe** [containers/podman#12883]
```
https_proxy=socks5h://myproxy:myport  podman pull ....
```
failure

```
https_proxy=socks5://myproxy:myport  podman pull ....
```
success

Differentiate socks5h from socks5. In a proxy string, socks5h:// means that the hostname is resolved by the SOCKS server. socks5:// means that the hostname is resolved locally.

**Comment by vrothberg** [comment]
Thank you for reaching out.

Please provide the requested data in the issue template. Can you share the output of `podman info --debug`? `socks5h` support is fairly new in Golang (https://github.com/golang/net/commit/395948e2f546cb82afa9e1f6d1a6e87849b9af1d).

**Comment by mheon** [comment]
Concur, we have no interaction with HTTP proxy environment variables directly; this is all handled via the Golang standard library. If there is an issue, it's with the Go language.
