### ISSUE TITLE
podman volume directive seems not to allow the container to write data

### ISSUE THREAD

**Issue by groovyman** [containers/podman#12896]
/kind bug
**Description**
I am running an actual  Fefora F35 distribution (with enabled selinux). I want to run a little Weblogic testcluster for to solve some open config issues. My first milestone would be to run the admin node (Weblogic with the admin console), but the container seems to have problems to write into the given volume.

So the setup Dockerfiles haven been taken from https://github.com/oracle, The very dynamic domain folder has been linked to the local workDir directory. In order to allow the container (with its different user inside) i 
did the following:

```
$ mkdir workDir
$ chcon -t container_file_t -R $PWD/workDir
$ sudo setsebool -P container_manage_cgroup true
```

The i run the i was trying to run the node:
```
$ podman run -d -ti --name wlsadmin --hostname=node00 -p 7001:7001 --env-file $PWD/properties/domain.properties --env ADMIN_PASSWORD=weblogic00 --volume $PWD/workDir:/u01/oracle/user_projects:z --volume $PWD/properties:/u01/oracle/properties:z   12213-simple
```
As you may noticed i added a z to the volume directive. So what goes wong?
The container starts using the worDir volumen, because i notived, that a _domains_ appears inside the workDir directory, great ...  but i would expect now, that the defined domain would appear as a domain inside the workDir directory. 
In order to get some information i used podman inspect to find out, what has been configured:

```
$ podman inspect  wlsadmin  | less
....
...
       "Mounts": [
            {
                "Type": "volume",
                "Name": "c139c4fcf736f6985726135e06276be183238f0b7842a5b1c8fe0115e54b950a",
                "Source": "/home/cgroove/.local/share/containers/storage/volumes/c139c4fcf736f6985726135e06276be183238f0b7842a5b1c8fe0115e54b950a/_data",
                "Destination": "/u01/oracle/user_projects/domains",
                "Driver": "local",
                "Mode": "",
                "Options": [
                    "nodev",
                    "exec",
                    "nosuid",
                    "rbind"
                ],
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/cgroove/Projects/asFreelancer/44_bayJustiz_virtual7/Dokumente/10_Projekte/LfSt_Bayern/20_Aufgaben/20220105_Queuing_Auslagern/20_Kodierung/10_DemoDocker/00_demoBase/001_simpleWlsNode/12213-domain/workDir",
                "Destination": "/u01/oracle/user_projects",
                "Driver": "",
                "Mode": "",
                "Options": [
                    "rbind"
                ],
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/home/cgroove/Projects/asFreelancer/44_bayJustiz_virtual7/Dokumente/10_Projekte/LfSt_Bayern/20_Aufgaben/20220105_Queuing_Auslagern/20_Kodierung/10_DemoDocker/00_demoBase/001_simpleWlsNode/12213-domain/properties",
                "Destination": "/u01/oracle/properties",
                "Driver": "",
                "Mode": "",
                "Options": [
                    "rbind"
                ],
                "RW": true,
                "Propagation": "rprivate"
            }
```
So that is strange, why are there two bind structures, another one that links the desired destination "/u01/oracle/user_projects/domains" into another source? 
And yes, the domain appears under `/home/cgroove/.local/share/containers/storage/volumes/c139c4fcf736f6985726135e06276be183238f0b7842a5b1c8fe0115e54b950a/_data`

**Steps to reproduce the issue:**

1. create a local directory and mark it  as container-usable with `chcon -t container_file_t -R $PWD/workDir`

2. run the container with podman run ... with the above prepared volume source

3. 

**Describe the results you received:**
I would exprect to see the domain-directory under my declared volume

**Describe the results you expected:**
The system mounted the container created domain directory under the host directory ``/home/cgroove/.local/share/containers/st`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
```
podman version 3.4.4
```

**Output of `podman info --debug`:**

```
[cgroove@dakar 12213-domain]$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 4
  distribution:
    distribution: fedora
    variant: workstation
    version: "35"
  eventLogger: journald
  hostname: dakar
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.14-200.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 22377730048
  memTotal: 33137872896
  ociRuntime:
    name: crun
    package: crun-1.4-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4
      commit: 3daded072ef008ef0840e8eccb0b52a7efbd165d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 1h 5m 2s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/cgroove/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/cgroove/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 33
  runRoot: /run/user/1000/containers
  volumePath: /home/cgroove/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 1638999907
  BuiltTime: Wed Dec  8 22:45:07 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.4

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
#podman-3.4.4-1.fc35.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No i only reply on the packages i received from Fedora

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
This looks like Podman is getting confused and thinking the source volume is not a path, and creating a named volume.

Is $PWD an actual Path?

BTW No need to do the chcon stuff.  The :z will take care of that.

**Comment by rhatdan** [comment]
Could you try the mounts with an image like Fedora and see if it works correctly.

One potential issue is if the three mountpoints of the image are builtinvolumes, then there could be a bug in Podman where we don't notice that the bind mount volumes should take precedence over building volumes of an image.

**Comment by mheon** [comment]
I think the first volume is an image volume - can you provide a `podman image inspect` of the image you're running to be sure?

No two volumes are mounted at the same spot in the container, this is perfectly fine. I don't see any bug there? If both volumes were pointed at `/u01/oracle/user_projects/domains` or `/u01/oracle/user_projects/` we'd detect a conflict between the image volume and the user-requested bind mount and the user-requested mount would win, leading to only one mount; instead, since they target different directories, we layer them, and the more-specific mount (in this case the image volume) wins.

The best resolution is to change your bind mount to `/u01/oracle/user_projects/domains` instead of `/u01/oracle/user_projects`. That will cause it to be mounted instead of the image volume created automatically by the container image.

**Comment by rhatdan** [comment]
Great job. @mheon I am closing this since you have a solution.  We can continue discussion in the issues.  Will reopen if we actually find a bug in Podman

**Comment by groovyman** [comment]
Thank you from my side for your quick reply and the helpful idea.
The domains directory was created by the container, so it was a good idea to do this from my sde and bind with the container path /u01/oracle/user_projects/domains.

Thanks!
