### ISSUE TITLE
API server crashes with race condition in logging code

### ISSUE THREAD

**Issue by riyad** [containers/podman#12904]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Running the [docker-py](https://github.com/docker/docker-py) integration tests against Podman's API it crashes with the following error roughly 3 out of 4 times:

>  panic: send on closed channel
> 
> goroutine 1199 [running]:
> github.com/containers/podman/v3/libpod.(*Container).readFromJournal.func1()
> 	/home/riyad/src/podman/libpod/container_log_linux.go:242 +0x5ae
> created by github.com/containers/podman/v3/libpod.(*Container).readFromJournal
> 	/home/riyad/src/podman/libpod/container_log_linux.go:118 +0x812

All following requests receive `111 Connection refused` responses.

When it happens it seems to always happen on the [`AttachContainerTest.test_run_container_reading_socket` test](https://github.com/docker/docker-py/blob/master/tests/integration/api_container_test.py#L1203).
Sadly only running this test in isolation doesn't trigger the crash. I tried including some of the preceding tests (see below for reproduction) until it crashes roughly 1/3 of the time.

**Steps to reproduce the issue:**

Run Podman API server

1. `./bin/podman system service -t 0`

Run tests against API

2. `DOCKER_HOST=unix:/run/user/1000/podman/podman.sock pytest -v -k 'RestartContainerTest or AttachContainerTest' tests/integration/api_container_test.py`

Triggers the race condition roughly 1 out of 3 times.

**Describe the results you received:**

Podman API server crashes with:

>  panic: send on closed channel
> 
> goroutine 1199 [running]:
> github.com/containers/podman/v3/libpod.(*Container).readFromJournal.func1()
> 	/home/riyad/src/podman/libpod/container_log_linux.go:242 +0x5ae
> created by github.com/containers/podman/v3/libpod.(*Container).readFromJournal
> 	/home/riyad/src/podman/libpod/container_log_linux.go:118 +0x812

All following requests receive `111 Connection refused` responses.

**Describe the results you expected:**

Should not crash.

**Additional information you deem important (e.g. issue happens only occasionally):**

Looking around in [old docker-py integration test logs](https://github.com/riyad/podman-integration-test-utils/tree/logs/logs) the first occurrence of this crash I can find is running against 49cfed756f5dfb6d9267eb29d31f651578c9037c ... which kind of coincides with #11263 being merged the day before. I don't know whether it may have caused or just uncovered this race condition. :thinking:
Maybe it helps narrowing it down.

**Output of `podman version`:**

Last tested on:

```
Client:       Podman Engine
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.17.6
Git Commit:   d7492f1514674825a63c89ae635e57f535800c8d
Built:        Mon Jan 17 22:17:30 2022
OS/Arch:      linux/amd64
```

**Comment by vrothberg** [comment]
Thanks for the report, I will take a look.

**Comment by riyad** [comment]
thanks for the fix :slightly_smiling_face:

**Comment by vrothberg** [comment]
Thanks for the great report!  Feel free to open more issues in case you hit some :)
