### ISSUE TITLE
Allow to use tar ball as build context

### ISSUE THREAD

**Issue by weyert** [containers/podman#12911]
**Description**

The `build`-command is not accepting tar ball build contexts, the Build Kit supports this, and commands like `cat ./my-build-context.tar.gz | docker build --progress=plain - -t experiment-tag` only when I try to use a similar command via `Podman` like: `cat ./my-build-context.tar.gz | podman build --log-level=debug` 

*Note*: See attached `my-build-context.tar.gz` for an example of the tar ball build context

**Steps to reproduce the issue:**
1. Download the `my-build-context.tar.gz` listed below
2. Run `cat ./my-build-context.tar.gz | docker build --progress=plain - -t experiment-tag`
3. Notice that the build succeeds and display `1.0.0` for the `RUN cat ./VERSION` command in the `Dockerfile`
4. Try to do the same command using Podman: `cat ./my-build-context.tar.gz | podman build --log-level=debug`
5. Notice that the build fails with `Error: no context directory and no Containerfile specified`

 [my-build-context.tar.gz](https://github.com/containers/buildah/files/7890265/my-build-context.tar.gz)

Alternatively, you can make your own tar ball with the following contents:

*`Dockerfile`*
```
# syntax = docker/dockerfile:1.3
FROM node:16-alpine

WORKDIR /root/monorepo

COPY . .

RUN ls -la

RUN cat ./VERSION
```

*`VERSION`*
```
1.0.0
```

**Describe the results you received:**
I received the following output when try to build a image using a tar ball build context:

```bash
❯ cat ./my-build-context.tar.gz | podman build --log-level=debug
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called build.PersistentPreRunE(podman build --log-level=debug) 
DEBU[0000] SSH Ident Key "/Users/weyert/.ssh/podman-machine-default" SHA256:RYRz+9HX5154MUdSScjsv5jwNNx0QpISpN4KwwZCIDs ssh-ed25519 
DEBU[0000] Found SSH_AUTH_SOCK "/private/tmp/com.apple.launchd.v1vVYesJwy/Listeners", ssh-agent signer(s) enabled 
DEBU[0000] DoRequest Method: GET URI: http://d/v3.4.4/libpod/_ping 
Error: no context directory and no Containerfile specified
```

**Describe the results you expected:**
I would expect the building of the image would succeed

**Output of `rpm -q buildah` or `apt list buildah`:**

```
Not available
```

**Output of `buildah version`:**

```
Not available
```

**Output of `podman version` if reporting a `podman build` issue:**

```
❯ podman version
Client:
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Wed Dec  8 18:41:11 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 21:45:07 2021
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
Not available
```

**Output of `uname -a`:**

```
Darwin MacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
```

**Output of `cat /etc/containers/storage.conf`:**

```
Not available
```

**Comment by weyert** [comment]
Cool, thank you, I wasn't aware of `-` :)

**Comment by rhatdan** [comment]
Actually it looks like this works as long as the server and client are podman 4.0.

**Comment by weyert** [comment]
@rhatdan Nice to know, need to find out how to get a newer version of Podman for Homebrew (macOS) then :)

**Comment by rhatdan** [comment]
Yes that is going to be a bit of a challenge until 4.0 is released.  Sometime in February.
