### ISSUE TITLE
swagger has missing schemas

### ISSUE THREAD

**Issue by tmds** [containers/podman#12927]
Some end points are missing schemas. For example the `200` response for `/images/create` below.

The swagger client library assumes there will be no response after receiving 200 and closes the connection, which causes the operation to get aborted.

```yaml
  /images/create:
    post:
      summary: "Create an image"
      description: "Create an image by either pulling it from a registry or importing it."
      operationId: "ImageCreate"
      consumes:
        - "text/plain"
        - "application/octet-stream"
      produces:
        - "application/json"
      responses:
        200:
          description: "no error"
        404:
          description: "repository does not exist or no read access"
          schema:
            $ref: "#/definitions/ErrorResponse"
        500:
          description: "server error"
          schema:
            $ref: "#/definitions/ErrorResponse"
```

I can patch the schema so the generated client is aware there will be a response:
```yaml
        200:
          description: "no error"
          schema:
            type: "string"
            format: "binary"
```

cc @jwhonce @mheon @baude

**Comment by jwhonce** [comment]
@tmds I suspect that is as good as it gets. We are following the Docker API for compatibility and swagger2 does not appear to have a way to define these concatenated json blobs. What do you think about adding a json template to the description describing the output stream? Since the blobs are not wrapped in an array or map, even adding a swagger:model would be incorrect.

**Comment by tmds** [comment]
> What do you think about adding a json template to the description describing the output stream?

I need something that causes the generated client to read the response.

I've created an issue suggesting it should always read the response, and I'm waiting for feedback from the maintainer: https://github.com/RicoSuter/NSwag/issues/3840

Otherwise, something like the `string+binary` schema may do the trick as well. I'm not a swagger expert, so I don't know if it is the most appropriate way to describe this response.

**Comment by jwhonce** [comment]
@tmds Do you want to create a PR with your suggested changes -- schema: string+binary? 

My idea of adding the json template to the description could be a follow-on PR.

swagger2 is limited regarding defining streaming.

**Comment by tmds** [comment]
> Do you want to create a PR with your suggested changes -- schema: string+binary?

Are you aware of other APIs that have the same issue? Is there a way I can identify them?

**Comment by tmds** [comment]
@jwhonce I can add it, are there others I should add it to?

**Comment by rhatdan** [comment]
Looks like this was fixed.
