### ISSUE TITLE
Support volumeMounts.subPath in podman kube play

### ISSUE THREAD

**Issue by fpoirotte** [containers/podman#12929]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Please consider adding support for `volumeMounts.subPath` in `podman kube play`.
This topic was briefly discussed in 2020 (#5654) but the request was rejected at the time.
I would like to request it again to improve compatibility between kubernetes and podman.

**Steps to reproduce the issue:**

1. Create `/tmp/my-lamp-site.yaml` with this content:
```
apiVersion: v1
kind: Pod
metadata:
  name: my-lamp-site
spec:
    containers:
    - name: mysql
      image: docker.io/library/mysql
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: "rootpasswd"
      volumeMounts:
      - mountPath: /var/lib/mysql
        name: site-data
        subPath: mysql
    - name: php
      image: docker.io/library/php:7.0-apache
      volumeMounts:
      - mountPath: /var/www/html
        name: site-data
        subPath: html
    volumes:
    - name: site-data
      persistentVolumeClaim:
        claimName: my-lamp-site-data
```

2. Create a volume : `podman volume create my-lamp-site-data`

3. `podman play kube /tmp/my-lamp-site.yaml`

**Describe the results you received:**

mysql's data is written at the root of the `my-lamp-site-data` volume

**Describe the results you expected:**

mysql's data should have been stored in a subfolder named `mysql` inside the volume because that's what `subPath` points to.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.17.5
Built:        Fri Jan 14 16:29:25 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.30-1.module_el8.6.0+944+d413f95e.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: e28f6ed9f4a6f18e27f3efdab92de483806e6b9c'
  cpus: 48
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: <redacted>
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1501
      size: 1
    - container_id: 1
      host_id: 200000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 5125
      size: 1
    - container_id: 1
      host_id: 200000
      size: 65536
  kernel: 4.18.0-348.7.1.el8_5.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 104679890944
  memTotal: 134499938304
  ociRuntime:
    name: runc
    package: runc-1.0.2-1.module_el8.6.0+926+8bef8ae7.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.2
      spec: 1.0.2-dev
      go: go1.16.7
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/5125/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module_el8.6.0+926+8bef8ae7.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 320h 19m 23.36s (Approximately 13.33 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/fpoirotte/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 4
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/fpoirotte/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 52
  runRoot: /run/user/5125/containers
  volumePath: /home/fpoirotte/.local/share/containers/storage/volumes
version:
  APIVersion: 4.0.0-dev
  Built: 1642174165
  BuiltTime: Fri Jan 14 16:29:25 2022
  GitCommit: ""
  GoVersion: go1.17.5
  OsArch: linux/amd64
  Version: 4.0.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.0.0-0.10.el8.x86_64 (manually-built based on https://src.fedoraproject.org/rpms/podman/blob/rawhide/f/podman.spec)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

irrelevant

**Comment by rhatdan** [comment]
@umohnani8 @vrothberg WDYT?

**Comment by rhatdan** [comment]
@vrothberg @umohnani8 Thoughts?

**Comment by vrothberg** [comment]
Apologies for missing the ping last month.  I will defer to @mheon since he is the volumes expert.

**Comment by fpoirotte** [comment]
From a user's point of view, it seems to do exactly what you described.
Not sure if it does anything funny behind the scene though.

**Comment by rhatdan** [comment]
@fpoirotte interested in opening a PR to add this?

**Comment by fpoirotte** [comment]
I don't really have any experience with the Go language so I'm not sure I would be up to the task? I would feel much safer knowing someone with more experience is taking over this subject.

**Comment by rhatdan** [comment]
No problem. Thanks for reporting it.
@umohnani8 PTAL

**Comment by MyForest** [comment]
I can see it in the struct:

https://github.com/containers/podman/blob/698cb730a1a7d36bc36e447969928ccb0a6317df/pkg/k8s.io/api/core/v1/types.go#L748

but I don't think I can see any code consuming it.

In my case I'm probably going a bit too far off the well-trodden track because I'm using `KIND_EXPERIMENTAL_PROVIDER=podman` with `kind`.

https://kind.sigs.k8s.io/docs/user/rootless/#creating-a-kind-cluster-with-rootless-podman

I'm seeing this error:

> Error: failed to prepare subPath for volumeMount "foo" of container "bar"

when doing:

```
          volumeMounts:
            - name: foo
              mountPath: /app/
              subPath: subby
```

Even if I set `subPath` to be `.` which should be innocuous it causes the error.

Note that I'm not using [podman play kube](https://docs.podman.io/en/latest/markdown/podman-play-kube.1.html) because I'm using Kinds it doesn't handle yet, such as `Service`.

**Comment by rhatdan** [comment]
Agreed. Or @cdoern

**Comment by cdoern** [comment]
I'd be happy to take this one but if @jakecorrenti or @karthikelango137 want it, just let me know

**Comment by rhatdan** [comment]
@cdoern this is in your hands?

**Comment by cdoern** [comment]
wait @fpoirotte so you are just looking for the `mountPath` and the `subPath` to be joined in the container?

**Comment by fpoirotte** [comment]
``subPath`` refers to a path inside the host's volume (rather than inside the container's mount point).

Given we have a named volume ``myvolume`` defined on the host with the following contents:
* website/
  * index.html
* mysql/
  * binlog.000001
  * somedb/
    * sometable.MYD
    * sometable.MYI
    * ...
  * ...

Now suppose we run podman play kube with the following manifest:
```
apiVersion: v1
kind: Pod
metadata:
  name: my-lamp-website
spec:
    containers:
    - name: php
      image: docker.io/library/php:7.0-apache
      volumeMounts:
      - mountPath: /var/www/html
        name: website-data
        subPath: website
    volumes:
    - name: website-data
      persistentVolumeClaim:
        claimName: myvolume
```

Without the ``subPath`` option, the whole structure would be mounted inside the container.
With the ``subPath`` option, only the subset of files/directories anchored at the given subpath gets mounted inside the container.
I.e. using the example above, ``/var/www/html/`` only contains ``index.html`` due to the use of ``subPath: website``.

Note: in my example above, I used a ``persistentVolumeClaim`` (i.e. a named volume from podman's pov), but this should also work for other volume types (e.g. ``hostPath``)

**Comment by gsalvatella** [comment]
Just for the record, `subPath` can also be used to mount individual `files` in a ConfigMap as explained (here)[https://dev.to/joshduffney/kubernetes-using-configmap-subpaths-to-mount-files-3a1i]. It's pretty much the same idea that @fpoirotte mentions but it's worth noting since the behavior may change depending on how you implement it. 

An important use case is when you want to add a configuration file inside a container folder that has other default files you want to maintain. Without subPath, the whole ConfigMap volume is bind mounted on top of the folder and any default configs are left hidden. Unfortunately this is the case for many real life containers, so this feature would really improve usability of `play kube`.

**Comment by rhatdan** [comment]
SGTM

**Comment by jesselang** [comment]
I'm familiar with how `subPath` behaves in the Kubernetes pod spec. I'm new to podman/libpod, but I'd be happy to take a swing at a PR for this. That being said, if there's WIP toward it, I'd love to see that carried forward!

**Comment by cdoern** [comment]
@jesselang I will push my code that I have and you can take a look at what I was thinking

**Comment by gilfrade** [comment]
I don't have the know how to help developing this feature but i can help testing this PR.

**Comment by umohnani8** [comment]
@cdoern any progress here?

**Comment by gilfrade** [comment]
Any news about this feature? Thanks

**Comment by gsalvatella** [comment]
This is probably the only remaining feature that will make `docker compose` obsolete. With `subPath` we can finally have *all* our configuration inside a single Kubernetes YAML. Looking forward to it!

**Comment by cdoern** [comment]
@gsalvatella so sorry about this one, I'll make this a top priority this week, thanks for being consistent!!!!!

**Comment by cdoern** [comment]
@gsalvatella @gilfrade just an update, I have this *almost* working with names volumes in podman, will have a PR you can try out by weeks end.
