### ISSUE TITLE
Error adding build tags

### ISSUE THREAD

**Issue by prayingmantis287** [containers/podman#12932]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am new to Podman, and am attempting to build the latest version on a Debian 11 VM by following the instructions at [https://podman.io/getting-started/installation](https://podman.io/getting-started/installation) </p>

At the `make BUILDTAGS=` step, regardless of the options used (e.g. `"seccomp apparmor"` or `""`) the following error is generated:

```
vendor/github.com/opencontainers/runc/libcontainer/cgroups/getallpids.go:4:2: cannot find package "." in:
        /home/<username_redacted>/podman/vendor/io/fs
make: *** [Makefile:309: bin/podman] Error 1
```

**Steps to reproduce the issue:**

1. Follow build instructions at [https://podman.io/getting-started/installation](https://podman.io/getting-started/installation)

2. During 'Get Source Code' phase, run `make BUILDTAGS="seccomp apparmor"` or `make BUILDTAGS=""`

**Describe the results you received:**
```
$ make BUILDTAGS="seccomp apparmor"
Podman is being compiled without the systemd build tag.         Install libsystemd on Ubuntu or systemd-devel on rpm based      distro for journald support.
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build \
        -mod=vendor  \
        -ldflags '-X github.com/containers/podman/v4/libpod/define.gitCommit=5e2fcf813d54980df00976a01fca571b7007ae16 -X github.com/containers/podman/v4/libpod/define.buildInfo=1642620983 -X github.com/containers/podman/v4/libpod/config._installPrefix=/usr/local -X github.com/containers/podman/v4/libpod/config._etcDir=/usr/local/etc ' \
        -tags "seccomp apparmor" \
        -o bin/podman ./cmd/podman
vendor/github.com/opencontainers/runc/libcontainer/cgroups/getallpids.go:4:2: cannot find package "." in:
        /home/<username_redacted>/podman/vendor/io/fs
make: *** [Makefile:309: bin/podman] Error 1
```

**Describe the results you expected:**

Successfully add build tags

**Additional information you deem important (e.g. issue happens only occasionally):**

All dependencies in the instructions are installed and verified Go version is `go1.15.15 linux/amd64`

**Output of `podman version`:**

```
N/A
```

**Output of `podman info --debug`:**

```
N/A
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
N/A
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by afbjorklund** [comment]
Your version of `go` is probably too old, since `io/fs` was added in go1.16

**Comment by Luap99** [comment]
Yeah I think we require 1.16 now.

**Comment by afbjorklund** [comment]
Docs say 1.12, but go.mod says 1.16

**Comment by Luap99** [comment]
The version in go.mod is generated by go itself so this should always be the correct one

**Comment by mheon** [comment]
Concur that we need to update the installation page. Maybe change it from a static version to a link to the specific line of `go.mod`? That might be confusing for users, though...

**Comment by Luap99** [comment]
I will open a PR

**Comment by prayingmantis287** [comment]
Just confirming that upgrading the go version resolved my issue. Many thanks.
