### ISSUE TITLE
RFE: option in `podman exec` to preserve working directory

### ISSUE THREAD

**Issue by castedo** [containers/podman#12944]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Both [toolbox](https://github.com/containers/toolbox) and [cnest](https://github.com/castedo/cnest) implement a feature which probably makes sense to be implemented inside podman. It's clumsy to implement in wrapper scripts but likely easy and more robust if done by podman. I can personally attest that not having this feature is very annoying in my work flow (it's what motivated me to hack together a solution around `podman exec`).

The proposed feature for `podman exec` is an option to perserve the same working after entering the container. In other words, if the $PWD starting `podman exec` exists with the same path inside the container, then set the working directory in the container to the same directory.

There is some divergence in exactly how toolbox and cnest implment this. Toolbox will perserve the working directory if the path is the same and ignores whether or not the directory is actually on the same device with the same inode (https://github.com/containers/toolbox/issues/988).  In contrast cnest will only preserve the working directory if the path and the device number and the inode of the directory are all the same. Both tools change to the home directory if the required condition is not met.

The implementation in cnest outside the container is here:
https://github.com/castedo/cnest/blob/223ee50a4d429a940ebde743be4fc37bc5395c64/bin/cnest#L47
and inside the container it is this:
https://github.com/castedo/cnest/blob/223ee50a4d429a940ebde743be4fc37bc5395c64/cnest/data/cnest-entry

Although the code outside the container seems fine, it's a bit clumsy trying to get something inside the container to handle the information about the current working directory outside the container. This is where it seems like podman is a more appropriate place for both sides of this to be implemented in the lower level tool of `podman exec`.

**Comment by giuseppe** [comment]
this is not currently supported by the OCI runtime specs, so it is not something podman can really do.

Couldn't you wrap podman with another check `podman exec $CID test -e $PWD` and if it succeeds use `$PWD` as working directory?

**Comment by castedo** [comment]
> wrap podman with another check

Oh! Why didn't I think of that! :facepalm: Thank you for thinking of that! I should have taken, or at least tried, that approach first. I was probably too obsessed with keeping the `podman exec` wrapper small.

To capture the current functionality in cnest, the exec needs to be to `stat` to get dev num and inode, rather than call `test`. But same basic idea.
