### ISSUE TITLE
bind mounting an external overlayFS to a container causes huge copy operations into overlayfs-upper/workdir

### ISSUE THREAD

**Issue by slartibart70** [containers/podman#12953]
Hi,
i am trying this on fedora34 and centos 8.4

Since podman 3.3.1 i have a strange problem with an external overlayfs.

SETUP:
I use a host created overlayFS like so:
```
lowerdir=/scratch/hisinone/repo/hisinone/muster/202112/config/cust:/scratch/hisinone/repo/cu/hisinone_releases/H1-2021.12
mkdir -p /scratch/hisinone/data/{upper,work}
mkdir /scratch/hisinone/overlay
mount -t overlay -o lowerdir=${lowerdir},upperdir=/scratch/hisinone/data/upper,workdir=/scratch/hisinone/data/work overlay /scratch/hisinone/overlay
```

This is working ok, looking into 'overlay' shows the layered files i need, the 'data/{upper,work}' dir is nearly empty.
Using the FS within 'overlay' (e.g. creating new files) is reflected in the data-dirs as expected.

Now, the problem:
Using podman 3.2.3 or docker 20.10.7 and bind-mounting this external overlayfs to a container does what i expect:

```
podman run -it -v /scratch/hisinone/overlay:/test:z  alpine sh
```
What happens?
- the container sees the files (the overlayfs) in /test
- any new file written by the container to overlay (in /test) lands in the container-external data/{upper,work} folders as expected.

BUT, starting with podman 3.3.1 up to podman 3.4.4 the behaviour is different
When i do the same
```
podman run -it -v /scratch/hisinone/overlay:/test:z  alpine sh
```
ALL FILES of the overlayFS will be COPIED to the external data/{upper,work} directories immediately at startup of the container.
If there are several GBs of files this causes a huge startup delay of the container, and the advantages of the overlayFS are gone, because of the copying 
Previous podman or docker versions did not copy anything, the were just using the overlay as such

What am i doing wrong since podman 3.3.1?
Are there any options to get the behaviour of podman 3.2.3 or docker 20.10.7 with newer releaeses of podman?

Looking forward for help!

**Comment by slartibart70** [comment]
one important thing:
my tests above are done as root, not as a user (so, no additional problems with rootless-containers!)

**Comment by giuseppe** [comment]
I think the `:z` is causing the relabelling of all the files in the volume so they are copied to the upper layer.

It might be that in older versions we didn't handle correctly the option flag

**Comment by slartibart70** [comment]
yes, i found this one already to be true (yesterday night while testing....)
But, without the :z label, my container is not allowed to access the folders inside the overlay on centos 8.4

docker on ubuntu does not use labeliing (se-linux), so this is the reason for it to work

Is there a possibility to disable the label-check for specific containers only?
I don't want to disable se-linux globally only for this feature to work...

**Comment by slartibart70** [comment]
one thing is strange:

on fedora34 / podman 3.4.4 this seems to work without :z ?
My container is a tomcat based on an ubuntu base-image, the webapps folder is the overlay coming from outside

Looking at the labels:
centos:
```
drwxrwxrwx. 2 root root system_u:object_r:container_file_t:s0:c554,c779  4096 Jan 28  2021 logs/
drwxr-xr-x. 2 root root system_u:object_r:container_file_t:s0:c554,c779  4096 Feb 10  2021 native-jni-lib/
drwxrwxrwx. 2 root root system_u:object_r:container_file_t:s0:c554,c779  4096 Feb 10  2021 temp/
drwxr-xr-x. 1 root root system_u:object_r:container_file_t:s0:c487,c587  4096 Jan 21 10:39 webapps/    ##### !!!! ####
drwxr-xr-x. 7 root root system_u:object_r:container_file_t:s0:c554,c779  4096 Jan 28  2021 webapps.dist/
drwxrwxrwx. 2 root root system_u:object_r:container_file_t:s0:c554,c779  4096 Jan 28  2021 work/
```

fedora34:
```
rwxr-xr-x. 2 root root system_u:object_r:container_file_t:s0:c31,c575  4096 Feb 10  2021 native-jni-lib/
drwxrwxrwx. 2 root root system_u:object_r:container_file_t:s0:c31,c575  4096 Feb 10  2021 temp/
drwxr-xr-x. 1 root root unconfined_u:object_r:container_file_t:s0       4096 Jan 21 10:28 webapps/    #### !!! ####
drwxr-xr-x. 7 root root system_u:object_r:container_file_t:s0:c31,c575  4096 Jan 28  2021 webapps.dist/
drwxrwxrwx. 2 root root system_u:object_r:container_file_t:s0:c31,c575  4096 Jan 28  2021 work/
```

on fedora/podman3.4.4 i am allowed to enter the webapps folder, on centos not

**Comment by slartibart70** [comment]
i just tested with 'setenforce permissive' on centos
Yep, doing allright, i can access the webapp folder
(oh man, centos being the problem again with old repos? )

**Comment by slartibart70** [comment]
another try:

on centos, i use the option
```
--security-opt label=disable
```

with selinux enforcing right now, this seems to help.
Any side-effects i should know of when using this option?

**Comment by rhatdan** [comment]
Nope, you loose SECCOMP protections, but still have the rest.

**Comment by slartibart70** [comment]
ok, thanks for the help!!
