### ISSUE TITLE
Cannot pull or build images due to "Error: writing blob: storing blob to file '/var/tmp/storage813872647/1': happened during read: unexpected EOF"

### ISSUE THREAD

**Issue by kevinleary** [containers/podman#12962]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Any attempt I make to pull an image results in this same error...
`Error: writing blob: storing blob to file "/var/tmp/storage813872647/1": happened during read: unexpected EOF`
I have tried looking into dozens of GitHub issues and tutorials on trying to fix the issue. Those that require setting `TMPDIR` looked promising but I have tried it and have gotten no-where. 

I am on MacOs.

**Steps to reproduce the issue:**

1. `podman machine init -m 8192 --cpus 4 --disk-size=75`

2. `podman machine start`

3. `podman pull node:12-slim`

**Describe the results you received:**

I receive 
`Error: writing blob: storing blob to file "/var/tmp/storage813872647/1": happened during read: unexpected EOF`

**Describe the results you expected:**

I expect an image to be pulled. 

**Additional information you deem important (e.g. issue happens only occasionally):**

I am on MacOs on a company laptop. I have tried to look into how to change where the images are being stored and have gotten no-where. 

**Output of `podman version`:**

```
podman version
Client:
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Wed Dec  8 13:41:11 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 16:45:07 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 4
  distribution:
    distribution: fedora
    variant: coreos
    version: "35"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.10-200.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 7377997824
  memTotal: 8325091328
  ociRuntime:
    name: crun
    package: crun-1.4-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4
      commit: 3daded072ef008ef0840e8eccb0b52a7efbd165d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 37m 52.52s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 1638999907
  BuiltTime: Wed Dec  8 21:45:07 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@vrothberg PTAL

**Comment by kevinleary** [comment]
It appears that pulling working behinds my company's Cisco VPN. Any workarounds for requiring the VPN to pull images?

**Comment by rhatdan** [comment]
That is up to you to setup the nextwork stack.  We have no control over that.

**Comment by kevinleary** [comment]
How could I configure the network stack properly to not require my VPN to be used?

**Comment by vrothberg** [comment]
There is nothing Podman can do. `unexpected EOF` can also happen with misconfigured proxies.

**Comment by hakanai** [comment]
I have the same issue here, and in my case it seems like the registry is kicking me off for taking too long to fetch the image. I can't exactly speed it up though - the network isn't under my control.

What podman (or at least the underlying fetching code) _should_ be doing is resuming the download if the connection is broken (see fallacies of distributed computing #1 "The network is reliable", #3 "Bandwidth is infinite"). At the moment, though, it seems like it just dies after the first issue of any kind.

**Comment by dpnishant** [comment]
As @hakanai described, this is indeed true. I was trying to switch to podman from docker cli and realized the same issue while pulling images from my workplace's private container repo. I tried to pull a specific image numerous times and every time the pull fails with above mentioned error. I re-installed docker desktop and tried to repeat steps with docker CLI on the same hour of the day, same system, same network, same image and noticed that docker CLI was able to pull the image. However the important thing I noted was that docker kept retrying incrementally whenever there was an error, but eventually the pull succeeds, in more or less the same time it takes podman to notify that the pull failed. So this something definitely needs to improve with Podman.

**Comment by vrothberg** [comment]
@dpnishant would you open a new issue? If Docker works in the same environment, it really suggests Podman needs some more massaging in the retry semantics.

**Comment by weiwongfaye** [comment]
I encountered this issue today,  the image I pull is bigger than 1GB.  Everytime, podman pull failed to pull the image at the end with the error mentioned in this thread.  

tried multiple times, it seems doesn't using any cache from previous, and failed at the end.

**Comment by rhatdan** [comment]
Please open a new issue.  We don't like to work on old closed issues, your problem might be different.

**Comment by Divya1388** [comment]
@weiwongfaye is there a new issue for this? i am having the same issue :(
