### ISSUE TITLE
Allow annotations for podman play kube

### ISSUE THREAD

**Issue by vbence** [containers/podman#12968]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

When using `podman play kube` allow to specify annotations similarly to `podman run --annotation run.oci.keep_original_groups=1` so full functionality could be utilized.

**Comment by vrothberg** [comment]
Thanks for reaching out, @vbence!  I like your proposal.  @rhatdan @baude something for interns?

**Comment by rhatdan** [comment]
SGTM, you are in charge of one...
