### ISSUE TITLE
Can  not find `podman image trust` command in MacOS.

### ISSUE THREAD

**Issue by threen134** [containers/podman#12981]
hi team 
my MacOs version is Monterey 12.1 
and I use brew install podman to installed.
I can find podman container trust command 
do I miss any plugin to install ? 
localhost:~ spark$ podman image trust
Error: unrecognized command `podman image trust`
Try 'podman image --help' for more information.
localhost:~ spark$ podman version
Client:
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Thu Dec  9 02:41:11 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Thu Dec  9 05:45:07 2021
OS/Arch:      linux/amd64
localhost:~ spark$

**Comment by vrothberg** [comment]
Thanks for reaching out.

The `image trust` command is not available for the remote clients (as on Mac OS).  It is only available on the native Linux client.

**Comment by rhatdan** [comment]
I am not sure we want to allow clients to modify which images are trusted.  Seems like something that should be handled on the server side.

**Comment by threen134** [comment]
@vrothberg  but man page include trust command in client side, can you add some comments on man page to told Mac OS user who can't use "trust" command on MacOS(client)

**Comment by rhatdan** [comment]
Interested in opening a PR to make the change?

**Comment by vrothberg** [comment]
Note that it is mentioned in the man pages that it's not supported for remote clients but I think it's worth adding Mac OS explicitly.

**Comment by rhatdan** [comment]
SGTM, it would be great if there was a way to remove these lines from Mac Man pages, but I am not sure if there is a way to do this easily.  Perhaps a CPP stuff.
