### ISSUE TITLE
Rootless user can't start Quay test container on Fedora Workstation due to conmon limitations. 

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/podman#12986]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Podman fails to start container just created from the Test container Image pulled from Quay with Error: OCI runtime error: unable to start container 1ae2cf34e4b6ae3eb9659c4d356bcdf6a1c2db1326216fac19b780c53f8a68d4: cannot disable OOM killer with cgroupv2. 

**Steps to reproduce the issue:**

1. Run Fedora Workstation rootless user session and invoke Terminal application
2. Pull quay.io/ansible/fedora30-test-container image
3. Create container using podman container create ... test-container-image-id -> container created. Memorize its id
4. Start container using podman container start --log-level=debug container-id

**Describe the results you received:**
Error: OCI runtime error: unable to start container 1ae2cf34e4b6ae3eb9659c4d356bcdf6a1c2db1326216fac19b780c53f8a68d4: cannot disable OOM killer with cgroupv2. 
With log:
...
INFO[0000] Running conmon under slice user.slice and unitName libpod-conmon-196ca6f0abd234d8a716cb3d23cf59ee63c1b119d3f8055215f17d52c888df4a.scope 
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

DEBU[0000] Received: -1     
...

**Describe the results you expected:**
Started container
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Podman 3.4.4
```

**Output of `podman info --debug`:**

```
ociRuntime:
    name: crun
    package: crun-1.4.1-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.1
      commit: 802613580a3f25a88105ce4b78126202fef51dfb
      spec: 1.0.0
**conmon:
    package: conmon-2.0.30-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '**

podman version
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 23:45:07 2021
OS/Arch:      linux/amd64


```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 35 Workstation after routine update January 24 2022

1. Conmon version is too old
2. Why Conmon tries to play with Early OOM service in the userspace of rootless user when it must adhere with [uresourced service proposal](https://fedoraproject.org/wiki/Changes/Reserve_resources_for_active_user_WS) ? Is it safe?
3. uresourced.service - User resource assignment daemon
     Loaded: loaded (/usr/lib/systemd/system/uresourced.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2022-01-24 09:56:09 IST; 2h 47min ago
   Main PID: 924 (uresourced)
      Tasks: 3 (limit: 9308)
     Memory: 1016.0K
        CPU: 39ms
     CGroup: /system.slice/uresourced.service
             └─924 /usr/libexec/uresourced
and
INFO[0000] Running conmon under slice user.slice and unitName libpod-conmon-196ca6f0abd234d8a716cb3d23cf59ee63c1b119d3f8055215f17d52c888df4a.scope 
3. The option --oom-kill-disable doesn't work too but it is not relevant for the desktop user.
4. Is reconfiguration of /etc/sysctl.conf like in Oracle's guidelines is safe ?

**Comment by PavelSosin-320** [comment]
@mheon During this morning dnf update I saw that the new CRun version came - 1.4.1. I suspect that CRun causes 2 errors, both related tp SELinux: 1. Rootless user can't create container, but today it is possible. 2. Now "failed to write to /proc/self/oom_score_adj: Permission denied". I will try to play with CRun standalone. But what is it "OCI Permission denied? CRun has explicit dependency with libseccomp-devel that has very recent release for the Kernel 5.15. If CRun can be upgraded separately I would like to test after "Incremental" Podman upgrade.

**Comment by giuseppe** [comment]
can you please provide the options you've passed to `container create`?

**Comment by giuseppe** [comment]
have you used `--oom-kill-disable`?

**Comment by giuseppe** [comment]
@PavelSosin-320 any update on this issue?

**Comment by giuseppe** [comment]
but is the error above happening when you do not specify `--oom-kill-disabled`?

**Comment by giuseppe** [comment]
you don't need `--oom-kill-disabled` to support earlyoom, you can just use `--oom-score-adj` to give different weights to containers.

**Comment by PavelSosin-320** [comment]
@giuseppe 1. systemd-oomd is active in Fedora35 as "**Userspace** preemptive OOM killer" and I . 2. Attempt to write --oom-score-adj by rootless user fails according the log. Why Podman do it if rootless Podman is development tool?  Service's oomd.conf manages both VM and Swap. These 2 mechanisms conflict and cause the error. Why I can't run container as big as my session's resource limits allow me?

**Comment by giuseppe** [comment]
you cannot use a `oom_score_adj` lower than your current one:

```
$ cat /proc/self/oom_score_adj
0
$ podman run --oom-score-adj=1000 --rm -ti fedora echo hello
hello
$ podman run --oom-score-adj=-1 --rm -ti fedora echo hello
Error: write to /proc/self/oom_score_adj: Permission denied: OCI permission denied
```

Still it is not clear if you've used `--ook-kill-disabled`.  Can you please provide the full command line?

**Comment by PavelSosin-320** [comment]
I did it in 2 steps to have separate logs: create & start:
podman container start 370d09de1052b324af9fb07b20b9c8d01dae29e64792e79f29f92d254dd05c57
Error: OCI runtime error: unable to start container "370d09de1052b324af9fb07b20b9c8d01dae29e64792e79f29f92d254dd05c57": cannot disable OOM killer with cgroupv2
The result is always is "cannot disable OOM killer with cgroupv2". It is true! Fedora WS has own **userspace** OOM killer service. It works smarter than server and triggers swap when memory pressure is high. Container can be suspended too instead of killed. Otherwise podman can't run with Chrome or Desktop (many processes) on the same machine.

**Comment by giuseppe** [comment]
I understood you use "podman create && start" but can you please provide the full command line you have used for `podman create`?

I don't see how you can get `cannot disable OOM killer with cgroupv2` without using `--oom-kill-disabled`, and that is expected on cgroup v2.

**Comment by PavelSosin-320** [comment]
I got it at the start step, as expected because start runs conmon 1st and conmon tries to write "failed to write to /proc/self/oom_score_adj". I teste and /proc/self/oom_score_adj is writable from bash but not from container using run or exec. I suppose, Kernel's OOM Killer is dedicated to servers and protects Kernel. Userspace OOM killer prevents sessions from freeze. I found plenty of OOM killers including Chrome built-in. If WS Desktop will be frozen because running container by Podman it will be mess, so Fedora already prevents it.

**Comment by giuseppe** [comment]
sure but how difficult can it be to answer my question that I've already asked 5 times?

Can you provide the full command line you've passed to `podman create`?  Have you use `--oom-kill-disabled`?

If you used `--oom-kill-disabled` that error message is expected on cgroup v2.

**Comment by giuseppe** [comment]
thanks for sharing the detailed steps with me.

From the document you've shared, I see you've used `--oom-kill-disabled` and that it just not supported with cgroupv2 since there is no knob offered from the kernel.

So the failure you've got is expected.

**Comment by PavelSosin-320** [comment]
@giuseppe It can hardly be called "the solution". Is it possible to correct crun and make Podman useful in the  Fedora or the right thing is to configure Podman to use runc as the container runtime?

**Comment by giuseppe** [comment]
> @giuseppe It can hardly be called "the solution". Is it possible to correct crun and make Podman useful in the Fedora or the right thing is to configure Podman to use runc as the container runtime?

There is really no difference with runc, AFAICS runc ignores oomKillDisabled for cgroup v2.  So whether you set it or not, you get the same result.

What is your expectation on cgroup v2 when you set `--oom-kill-disable` if that knob is not available in the kernel?

**Comment by PavelSosin-320** [comment]
@giuseppe It is exactly as #https://github.com/containers/podman/issues/4924 - rootless containers can't start... opened by disaster123 and closed without solution. The only difference is the Linux distro: in my case Fedora 35 WS with GNOME  4 out-of-the-box. I tried with SELinux permissive and enforced with the same result. Nothing relevant is written to the SELinux alerts in both cases. If it is related to D-bus please, take into account that in Fedora there is Bus-broker instead of D-Bus running inside GNOME session. It starts with some issue systemd[2777]: Starting D-Bus User Message Bus...
Feb 08 11:19:06 Dell _dbus-broker-launch[4699]: Service file '/usr/share//dbus-1/services/sealert.service' is not named after the D-Bus name 'org.f>
Feb 08 11:19:06 Dell systemd[2777]: Started D-Bus User Message Bus.
Feb 08 11:19:06 Dell dbus-broker-launch[4699]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +31: Eavesdropping is deprecated an>
Feb 08 11:19:06 Dell dbus-broker-launch[4699]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +33: Eavesdropping is deprecated an>dbus-broker-launch[4699]: Service file '/usr/share//dbus-1/services/sealert.service' is not named after the D-Bus name 'org.f>

Feb 08 11:19:06 Dell systemd[2777]: Started D-Bus User Message Bus.
Feb 08 11:19:06 Dell dbus-broker-launch[4699]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +31: Eavesdropping is deprecated an>
Feb 08 11:19:06 Dell dbus-broker-launch[4699]: Policy to allow eavesdropping in /usr/share/dbus-1/session.conf +33: Eavesdropping is deprecated an>
Feb 08 11:19:06 Dell dbus-broker-lau[4699]: Ready
Feb 08 11:19:06 Dell dbus-broker-lau[4699]: Ready_
**Session's DBus socket** is started with some issue that may cause alerts recording missing.
Starting D-Bus User Message Bus Socket...
Listening on D-Bus User Message Bus Socket.
ls -alZ /run/user/1000/bus
srw-rw-rw-. 1 pavelsosin pavelsosin unconfined_u:object_r:session_dbusd_tmp_t:s0 0 Feb  8 11:19 /run/user/1000/bus.
Does crun communicated with D_Bus via rootless user's bus socket correctly?

**Comment by giuseppe** [comment]
```
Session's DBus socket is started with some issue that may cause alerts recording missing.
```

that looks like something is not configured properly on your system.  Have you performed any tweak to the default configuration?

**Comment by PavelSosin-320** [comment]
@giuseppe Indeed, it looks like SELinux labelling issue: container files created by root and rootless user in the Podman runtime are labeled very different:
For the rootless user unconfined_u:object_r:user_tmp_t:s0, with tmp
For the root unconfined_u:object_r:root_t:s0, i.e. without tmp 
For the DBus socket: unconfined_u:object_r:session_dbusd_tmp_t:s0   0 Feb 13 12:19 bus

There is not a surprise - systemd manages tmpfs differently for the root and "human" users: Root's tmpfs is mounted on /run directly. It is going to be very complex in congestion with separate systemd ...
I have idea: maybe creation of Podman runtime_root   using containers.mount unit is simpler, flexible and gives more freedom?

**Comment by PavelSosin-320** [comment]
Maybe it is Journald issue:
time->Wed Feb 16 19:58:46 2022
type=PROCTITLE msg=audit(1645034326.299:930): proctitle="/usr/lib/systemd/systemd-journald"
type=PATH msg=audit(1645034326.299:930): item=0 name="/proc/184768/exe" inode=1188819 dev=00:16 mode=0120777 ouid=1000 ogid=1000 rdev=00:00 obj=unconfined_u:system_r:container_runtime_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=CWD msg=audit(1645034326.299:930): cwd="/"
type=SYSCALL msg=audit(1645034326.299:930): arch=c000003e syscall=267 success=no exit=-13 a0=ffffff9c a1=7ffd95f46b30 a2=55f2c999bf40 a3=1000 items=1 ppid=1 pid=591 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-journal" exe="/usr/lib/systemd/systemd-journald" subj=system_u:system_r:syslogd_t:s0 key=(null)
type=AVC msg=audit(1645034326.299:930): avc:  denied  { sys_ptrace } for  pid=591 comm="systemd-journal" capability=19  scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:system_r:syslogd_t:s0 tclass=cap_userns permissive=0
----
time->Wed Feb 16 19:58:46 2022
type=PROCTITLE msg=audit(1645034326.448:931): proctitle="/usr/lib/systemd/systemd-journald"
type=PATH msg=audit(1645034326.448:931): item=0 name="/proc/184773/exe" inode=1193016 dev=00:16 mode=0120777 ouid=1000 ogid=1000 rdev=00:00 obj=unconfined_u:system_r:container_runtime_t:s0 nametype=NORMAL cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
type=CWD msg=audit(1645034326.448:931): cwd="/"
type=SYSCALL msg=audit(1645034326.448:931): arch=c000003e syscall=267 success=no exit=-13 a0=ffffff9c a1=7ffd95f46ba0 a2=55f2c99d3ee0 a3=1000 items=1 ppid=1 pid=591 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="systemd-journal" exe="/usr/lib/systemd/systemd-journald" subj=system_u:system_r:syslogd_t:s0 key=(null)
**type=AVC msg=audit(1645034326.448:931): avc:  denied  { sys_ptrace } for  pid=591 comm="systemd-journal" capability=19  scontext=system_u:system_r:syslogd_t:s0 tcontext=system_u:system_r:syslogd_t:s0 tclass=cap_userns permissive=0**
[root@Dell ~]# systemctl status systemd-journald
● systemd-journald.service - Journal Service
     Loaded: loaded (/usr/lib/systemd/system/systemd-journald.service; static)
     Active: active (running) since Sun 2022-02-13 12:19:14 IST; 3 days ago
TriggeredBy: ● systemd-journald-dev-log.socket
             ● systemd-journald.socket
             ● systemd-journald-audit.socket
       Docs: man:systemd-journald.service(8)
             man:journald.conf(5)
   Main PID: 591 (systemd-journal)
     Status: "Processing requests..."
      Tasks: 1 (limit: 9307)
     Memory: 35.2M
        CPU: 6.094s
     CGroup: /system.slice/systemd-journald.service
             └─591 /usr/lib/systemd/systemd-journald

Feb 13 12:19:14 Dell systemd-journald[591]: Journald service is started but writing to the journald socket is restricted by SELinux. Something like [Journald related bugzilla](https://bbs.archlinux.org/viewtopic.php?id=187602). Indeed, some log files are corrupted and it causes systemctl status "degraded". I tried to reset logs state but it went not well.

**Comment by PavelSosin-320** [comment]
@mheon I almost sure that the root cause is one of the systemd-journald issues that prevents writing log message and causes recursive error. Once one of the log files is corrupted the journald service becomes unusable and causes error propagation to all applications. One of the candidate is [Journal corruption problem](https://access.redhat.com/solutions/2649461). The solution is "UNVERIFIED" and doesn't work. Could somebody from systemd-journald developers propose the better way to restore journald state and fallback for the failing logctl call. I will be greatly appreciated.

**Comment by PavelSosin-320** [comment]
@giuseppe Some news as well as for https://bugzilla.redhat.com/show_bug.cgi?id=1425278. It looks amazingly similar - I can't start container as rootless user. I suspected some conflict between SELinux and XDG file layout in GNOME and so,  investigated everything related to SELiunux container runtime files labeling, CRun process domain but everything looks OK. If you need some checks in Fedora 35 WS I'm here.
