### ISSUE TITLE
podman --userns=keep-id broken

### ISSUE THREAD

**Issue by cjreyn** [containers/podman#12992]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Running rootless "podman run" on RHEL8 has non consistent behavior and seems broken for some container images.

**Steps to reproduce the issue:**

1. On a RHEL8/Centos8 Machine, run "podman run -it --userns=keep-id  centos:7 /bin/bash"

2. On a RHEL8/Centos8 Machine, run "podman run -it --userns=keep-id  quay.io/ansible/awx-ee:latest /bin/bash"

3. Run "id" inside the bash shells and compare output

**Describe the results you received:**
Run the following as "myuser" on a Centos8 host:
`podman run -it --userns=keep-id  centos:7 /bin/bash
bash-4.2$ id
uid=1214320(myuser) gid=1214320(myuser) groups=1214320(myuser)
`
From the AWX container, run the following as "myuser":
`podman run -it --userns=keep-id  quay.io/ansible/awx-ee:latest /bin/bash
bash-4.4$ id
uid=1000(1000) gid=0(root) groups=0(root)
`

**Describe the results you expected:**
I would expect the same result for both container images, i.e. for the container to use "myuser" inside the container process.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```

Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.7
Built:        Tue Sep 21 09:41:42 2021
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.22.3
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.module+el8.5.0+12582+56d94c81.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 0f5bee61b18d4581668e5bf18b910cda3cff5081'
  cpus: 8
  distribution:
    distribution: '"rhel"'
    version: "8.5"
  eventLogger: file
  hostname: myhost
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1214320
      size: 1
    - container_id: 1
      host_id: 10000000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1214320
      size: 1
    - container_id: 1
      host_id: 10000000
      size: 65536
  kernel: 4.18.0-348.7.1.el8_5.x86_64
  linkmode: dynamic
  memFree: 545984512
  memTotal: 16263757824
  ociRuntime:
    name: runc
    package: runc-1.0.2-1.module+el8.5.0+12582+56d94c81.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.2
      spec: 1.0.2-dev
      go: go1.16.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/user/1214320/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.5.0+12582+56d94c81.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 338h 55m 31.83s (Approximately 14.08 days)
registries:
  search:
  - docker.io
store:
  configFile: /home/myuser/.config/containers/storage.conf
  containerStore:
    number: 34
    paused: 0
    running: 2
    stopped: 32
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /scratch/myuser
  graphStatus: {}
  imageStore:
    number: 7
  runRoot: /run/user/1214320
  volumePath: /scratch/myuser/volumes
version:
  APIVersion: 3.3.1
  Built: 1632213702
  BuiltTime: Tue Sep 21 09:41:42 2021
  GitCommit: ""
  GoVersion: go1.16.7
  OsArch: linux/amd64
  Version: 3.3.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.3.1-9.module+el8.5.0+12697+018f24d7.x86_64
pcp-pmda-podman-5.3.1-5.el8.x86_64
podman-catatonit-3.3.1-9.module+el8.5.0+12697+018f24d7.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Were the Podman commands run on different systems? The results of `keep-id` vary based on the system in use, it makes the running user's UID the UID of the user running podman - so running on different users, with different UIDs, will have different results

**Comment by cjreyn** [comment]
Same user

**Comment by mheon** [comment]
From the image config of the Ansible image:
`            "User": "1000",`

I'm betting this is it.
@rhatdan Should User from the image override the default UID/GID set by `--userns=keep-id`?

**Comment by rhatdan** [comment]
Yes.
--userns=keep-id should only setup the user namespace, and leave the default be we run as the user who ran the podman command, in the case of no `keep-id`, this would be Your UID but root within the user namespace.  If you run with --userns=keep-id, it should again be your UID. but this time it is mapped to the same UID inside of out of the User Namespace.
If the user specifies --user foobar in either case it should run as the foobar user and if the image has USER foobar, it likewise should run that way.

**Comment by rhatdan** [comment]
I don't think we can change the default at this point. Just because a lot of the world has been using this default for a while (toolbox)

You could run your container with --user root and get the behaviour you want.

**Comment by rhatdan** [comment]
podman run --user root --userns=keep-id 0bae8b30b4bc76bb2ed4ba4b11f1f0a25cb7b3db176668578112e47b485d9e9e id
uid=0(root) gid=0(root) groups=0(root)
