### ISSUE TITLE
Default network gets created when using Docker Compose

### ISSUE THREAD

**Issue by vikas-goel** [containers/podman#12994]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

Regression

**Description**

When creating a container using Docker Compose, a default network gets created. This issue was not observed with earlier versions of podman.

**Steps to reproduce the issue:**

1. Make sure all (macvlan) network interfaces are created beforehand
```
# podman network ls
NETWORK ID    NAME        DRIVER
39093c071800  ens160      macvlan
22e496b0a5ff  ens192      macvlan
2f259bab93aa  podman      bridge
#
```

2. Create a Docker Compose file with one of the macvlan network
```
# cat docker-compose.yml
    networks:
      ens160:
        ipv4_address: 10.xx.xxx.xxx
...
networks:
  ens160:
    external:
      name: ens160
...
```

3. Start a container using Docker Compose using the network interfaces
```
# docker-compose up -d --no-deps mycont
Creating network "tmp_default" with the default driver
Creating mycont ...
Creating mycont ... error

ERROR: for mycont  Cannot create container for service mycont_tool: container create: cannot set network aliases for network "tmp_default" because dns is disabled: invalid argument

ERROR: for mycont  Cannot create container for service mycont_tool: container create: cannot set network aliases for network "tmp_default" because dns is disabled: invalid argument
ERROR: Encountered errors while bringing up the project.

# podman network ls
NETWORK ID    NAME         DRIVER
39093c071800  ens160       macvlan
22e496b0a5ff  ens192       macvlan
2f259bab93aa  podman       bridge
89934527af27  tmp_default  bridge
#
```

**Describe the results you received:**
A new unexpected tmp_default network is auto created that fails for some DNS reasons

**Describe the results you expected:**
The container should get started without creating any new network interface

**Additional information you deem important (e.g. issue happens only occasionally):**
Always

**Output of `podman version`:**

```
# podman version
Client:       Podman Engine
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.17.5
Git Commit:   d847ad598d752dad479250b7f289858cc272cb04
Built:        Fri Jan 21 13:33:54 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
# podman info --debug
host:
  arch: amd64
  buildahVersion: 1.24.0-dev
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.module+el8.5.0+12582+56d94c81.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 0f5bee61b18d4581668e5bf18b910cda3cff5081'
  cpus: 8
  distribution:
    distribution: '"rhel"'
    version: "8.5"
  eventLogger: file
  hostname: myhost
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-348.12.2.el8_5.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 15552282624
  memTotal: 33511686144
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.0.2-1.module+el8.5.0+12582+56d94c81.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.2
      spec: 1.0.2-dev
      go: go1.16.7
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.5.0+12582+56d94c81.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 20002631680
  swapTotal: 20002631680
  uptime: 50h 30m 23.98s (Approximately 2.08 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
  - filevol
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 3
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.0-dev
  Built: 1642800834
  BuiltTime: Fri Jan 21 13:33:54 2022
  GitCommit: d847ad598d752dad479250b7f289858cc272cb04
  GoVersion: go1.17.5
  OsArch: linux/amd64
  Version: 4.0.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Local build of podman on 01/21/2022 using latest mainline source code
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

RHEL 8.5 VM

**Comment by Luap99** [comment]
Can you share the podman service logs. I think docker-compose is calling network create endpoint. Podman will/should never create a network on its own.

**Comment by Luap99** [comment]
https://docs.docker.com/compose/networking/#use-a-pre-existing-network I think this is the solution here, you have to specify your external network as default otherwise compose will always create a default

**Comment by vikas-goel** [comment]
> https://docs.docker.com/compose/networking/#use-a-pre-existing-network I think this is the solution here, you have to specify your external network as default otherwise compose will always create a default

The Docker Compose has been working with Docker and previous Podman. Is this an intended change in the new podman?

**Comment by Luap99** [comment]
Please provide the server log, podman cannot create the network on its own docker-compose makes the api calls.

**Comment by vikas-goel** [comment]
Where can I find those logs?

**Comment by Luap99** [comment]
`journalctl -u podman.service` if you run it as systemd service otherwise just run `podman system service -t0 --log-level debug` in another terminal

**Comment by vikas-goel** [comment]
Logs attached

```
# docker-compose -f /tmp/mycont.yml up -d --no-deps mycont
Creating network "tmp_default" with the default driver
Creating mycont ...
Creating mycont ... done
[root@flex-vm-02 flex-vm-02]# podman network ls
NETWORK ID    NAME         DRIVER
39093c071800  ens160       macvlan
22e496b0a5ff  ens192       macvlan
2f259bab93aa  podman       bridge
89934527af27  tmp_default  bridge
```
[tmp_default.txt](https://github.com/containers/podman/files/7937074/tmp_default.txt)

**Comment by vikas-goel** [comment]
The change in behavior is that same Docker Compose file and binary with earlier versions of Podman would not create this tmp_default network.

**Comment by vikas-goel** [comment]
@Luap99 ,
Can we re-open the issue to see if backward compatibility can be maintained?

**Comment by Luap99** [comment]
I still do not believe that this is a podman issue. If you look at the docker-compose output you see that it creates the network. This also matches the docker-compose documentation as linked above you have to declare your network as default.

If this work previously then this was a bug and is now fixed compose clearly makes the api call to create a network cvalled tmp_default
