### ISSUE TITLE
Consider adding hint to podman run -h

### ISSUE THREAD

**Issue by danielhelfand** [containers/podman#13002]
/kind feature

**Description**

It would be nice to provide an improved error message when users run `podman run -h`. The current cli output makes it unclear that, unlike other commands, `-h` does not correspond to `--help` for this command.

**Steps to reproduce the issue:**

1. `podman run -h`

**Describe the results you received:**

When I run `podman run -h`, I get the following response:

```
Error: flag needs an argument: 'h' in -h
```

**Describe the results you expected:**

While the error itself is confusing, my main source of confusion is I expect to be presented with the `--help` information for the `podman run` command. The issue is that the `--hostname` flag has a `-h` shorthand, which conflicts with the `--help` command's shorthand of `-h`.

This is consistent with the docker cli, which also has a `-h` shorthand for `--hostname` for the `docker run` command. However, it looks like the docker cli adds the following hint to all docker commands resulting in an error:

```
flag needs an argument: 'h' in -h
See 'docker run --help'.
```

The docker cli attempts to make it clear that `docker run` has this conflict by calling out to use `docker run --help`. While it's still confusing and may not have been added for this specific case, the message at least more directly says to run the full `--help` option.

It would be helpful to improve on the docker cli's error message to make this issue more clear to users.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Wed Dec  8 12:41:11 2021
OS/Arch:      darwin/arm64

Server:
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 15:48:10 2021
OS/Arch:      linux/arm64
```

**Comment by danielhelfand** [comment]
> This seems to be from lowlevel of cobra. I think the issue would be finding the actually command that is executed to put out a decent help messages.

Yes, I see your point. Makes sense to me. 

I do wonder if something else could be done for this specific case of the `-h` conflict, but perfectly fine if the answer is adding the `podman run --help` message is enough. 

Thanks for triaging this.

**Comment by Luap99** [comment]
There are definitely ways to do this but I would have to look that up. I am busy with the network work at the moment but I can take a look if I find some time in the next weeks.

**Comment by rhatdan** [comment]
THanks, I would say this is low priority.
