### ISSUE TITLE
Cannot ssh to container for operation permitted on /proc/self/loginuid

### ISSUE THREAD

**Issue by vikas-goel** [containers/podman#13012]
/kind bug

Regression

**Description**

I have a container with SSH running inside. I have added AUDIT_WRITE capability to the container. After updating podman to mainline, unable to SSH to the container.

**Steps to reproduce the issue:**

1. Add "AUDIT_WRITE" to the default_capabilities list in /usr/share/containers/containers.conf file

2. Put SELinux in Permissive mode

3. Start a container with public IP address and run sshd inside

4. Login to the container using the public IP address

**Describe the results you received:**
SSH connection breaks as soon after credentials is verified and PAM tries to open session.

/var/log/secure log
```
Jan 25 20:12:17 myhost sshd[278]: Accepted password for myuser from 1x.yy.aa.bb port 51250 ssh2
Jan 25 20:12:17 myhost sshd[278]: pam_loginuid(sshd:session): Error writing /proc/self/loginuid: Operation not permitted
Jan 25 20:12:17 myhost sshd[278]: pam_loginuid(sshd:session): set_loginuid failed
Jan 25 20:12:17 myhost sshd[278]: pam_unix(sshd:session): session opened for user myuser by (uid=0)
Jan 25 20:12:17 myhost sshd[278]: error: PAM: pam_open_session(): Cannot make/remove an entry for the specified session
Jan 25 20:12:17 myhost sshd[280]: Received disconnect 1x.yy.aa.bb port 51250:11: disconnected by user
Jan 25 20:12:17 myhost sshd[280]: Disconnected from 1x.yy.aa.bb port 51250
```

SSH server logs when run in debug mode
```
debug1: userauth-request for user myuser service ssh-connection method password [preauth]
debug1: attempt 1 failures 0 [preauth]
debug1: PAM: password authentication accepted for myuser
debug1: do_pam_account: called
Accepted password for appadmin from 1x.yy.aa.bb port 51228 ssh2
debug1: monitor_child_preauth: myuser has been authenticated by privileged process
debug1: monitor_read_log: child log fd closed
debug1: temporarily_use_uid: 1000/100 (e=0/0)
debug1: ssh_gssapi_storecreds: Not a GSSAPI mechanism
debug1: restore_uid: 0/0
debug1: SELinux support disabled
debug1: PAM: establishing credentials
PAM: pam_open_session(): Cannot make/remove an entry for the specified session
User child is on pid 311
debug1: PAM: establishing credentials
debug1: permanently_set_uid: 1000/100
debug1: rekey after 4294967296 blocks
debug1: rekey after 4294967296 blocks
debug1: ssh_packet_set_postauth: called
debug1: Entering interactive session for SSH2.
debug1: server_init_dispatch
debug1: server_input_channel_open: ctype session rchan 0 win 1048576 max 16384
debug1: input_session_request
debug1: channel 0: new [server-session]
debug1: session_new: session 0
debug1: session_open: channel 0
debug1: session_open: session 0: link with channel 0
debug1: server_input_channel_open: confirm session
debug1: server_input_global_request: rtype no-more-sessions@openssh.com want_reply 0
debug1: server_input_channel_req: channel 0 request pty-req reply 1
debug1: session_by_channel: session 0 channel 0
debug1: session_input_channel_req: session 0 req pty-req
debug1: Allocating pty.
debug1: session_new: session 0
debug1: SELinux support disabled
debug1: session_pty_req: session 0 alloc /dev/pts/2
debug1: server_input_channel_req: channel 0 request env reply 0
debug1: session_by_channel: session 0 channel 0
debug1: session_input_channel_req: session 0 req env
debug1: server_input_channel_req: channel 0 request shell reply 1
debug1: session_by_channel: session 0 channel 0
debug1: session_input_channel_req: session 0 req shell
Starting session: shell on pts/2 for myuser from 1x.yy.aa.bb port 51228 id 0
debug1: Setting controlling tty using TIOCSCTTY.
debug1: Received SIGCHLD.
debug1: session_by_pid: pid 312
debug1: session_exit_message: session 0 channel 0 pid 312
debug1: session_exit_message: release channel 0
debug1: session_by_tty: session 0 tty /dev/pts/2
debug1: session_pty_cleanup: session 0 release /dev/pts/2
Received disconnect from 1x.yy.aa.bb port 51228:11: disconnected by user
Disconnected from 1x.yy.aa.bb port 51228
debug1: do_cleanup
debug1: do_cleanup
debug1: PAM: cleanup
debug1: PAM: deleting credentials
```

**Describe the results you expected:**
SSH connection should work.

**Additional information you deem important (e.g. issue happens only occasionally):**
Always
**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.17.5
Git Commit:   be722e59eca6cf4b8f9249825e044930d6534f74
Built:        Mon Jan 24 12:57:44 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.0-dev
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.module+el8.5.0+12582+56d94c81.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 0f5bee61b18d4581668e5bf18b910cda3cff5081'
  cpus: 8
  distribution:
    distribution: '"rhel"'
    version: "8.5"
  eventLogger: file
  hostname: myhost
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-348.12.2.el8_5.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 14842597376
  memTotal: 33511686144
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.0.2-1.module+el8.5.0+12582+56d94c81.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.2
      spec: 1.0.2-dev
      go: go1.16.7
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.5.0+12582+56d94c81.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 20002631680
  swapTotal: 20002631680
  uptime: 152h 25m 6s (Approximately 6.33 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
  - filevol
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 2
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 5
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.0-dev
  Built: 1643057864
  BuiltTime: Mon Jan 24 12:57:44 2022
  GitCommit: be722e59eca6cf4b8f9249825e044930d6534f74
  GoVersion: go1.17.5
  OsArch: linux/amd64
  Version: 4.0.0-dev

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Local podman build from mainline
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
RHEL 8.5 VM

**Comment by giuseppe** [comment]
you need to have CAP_AUDIT_WRITE in the initial user namespace.  How was the container created?

Is `loginuid_immutable` set?  You can verify it with `auditctl -s`

**Comment by giuseppe** [comment]
and for the container use case, you also need `CAP_AUDIT_CONTROL`, since it is required to change the `loginuid` once it is set

**Comment by giuseppe** [comment]
an example:

```
# podman run --cap-add AUDIT_WRITE --rm fedora sh -c 'echo 2 > /proc/1/loginuid && echo ok'
sh: line 1: echo: write error: Operation not permitted
# podman run --cap-add AUDIT_CONTROL --rm fedora sh -c 'echo 2 > /proc/1/loginuid && echo ok'
ok
```

**Comment by giuseppe** [comment]
given the above, I am closing the issue, but feel free to comment further and reopen if there is still something we should look at

**Comment by giuseppe** [comment]
I don't think it depends from podman, was the kernel changed as well?

Adding capabilities reduce the security, it would be better if you didn't need to, but in your case I am not sure how to achieve that, is the error fatal or ssh still work?  If it is just noise, I would ignore it and not add capabilities.  Another possibility is to teach sshd it is running in a container and ignore such failures

**Comment by rhatdan** [comment]
In podman 3.0 we gave every container AUDIT_WRITE by default, we don't do that in podman 3.4, since the only containers needing it are SSH containers, which is kind of an anti-pattern.
AUDIT_CONTROL allows the processes within the container to modify the Audit subsystem, for people who care about audit this is a very big deal, for those that don't it is not.

**Comment by giuseppe** [comment]
but that won't still explain why AUDIT_WRITE was enough before.

I've looked at the kernel and it seems AUDIT_CONTROL was always required to change the loginuid.

How was it working before without that capability?

**Comment by giuseppe** [comment]
maybe it depended on something else, since I can reproduce the same error on CentOS Stream 8:

```
# podman --version
podman version 3.0.2-dev

# podman run --rm fedora sh -c 'getpcaps 1'
1: cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_setfcap=eip

#  podman run --rm fedora sh -c 'echo 2 > /proc/self/loginuid'
sh: line 1: echo: write error: Operation not permitted
```

**Comment by mheon** [comment]
OpenSSH versions, maybe?

I encountered this on a personal system - I had an image based on an old (~29-30) Fedora release, that I finally upgraded to F35. When I recreated the container, the old command-line invocation didn't work after the upgrade, and I had to add the `AUDIT_CONTROL` capability to restore functionality.

**Comment by vikas-goel** [comment]
I can tell that the SSH version (openssh-7.4p1-21.el7.x86_64) inside the container stays same while updating the podman version. The host SSH version, that should not matter in this case, is also same when updating podman version from 3.3.1 to mainline.

**Comment by rhatdan** [comment]
I told you we tightened the security with the express understanding that this would break sshd inside of the container.

You have to add the CAP_AUDIT_WRITE.

The CAP_AUDIT_CONTROL, should not cause issues.

**Comment by rhatdan** [comment]
If you want to change back to the previous defaults you can go modify the default cap list in containers.conf.

**Comment by vikas-goel** [comment]
I added the AUDIT_WRITE capability in the conf file that worked with podman 3.3.1 (default version of RHEL8.5).

However, after updating just the podman to mainline (no other change in the system), it requires additional AUDIT_CONTROL capability without which SSH session does not open.

**Comment by rhatdan** [comment]
That makes no sense, since neither version ever allowed AUDIT_CONTROL. Something else has changed.  Unless we are leaking information into the container which makes the container think it can set AUDIT_CONTROL.
Are you running this container by hand or under systemd?

**Comment by vikas-goel** [comment]
Manually always using podman run command

**Comment by giuseppe** [comment]
I've tried installing openssh-server from Fedora 35 in a container and used systemd to start it.  I've traced it and I don't see it is attempting to write to `/proc/self/loginuid` if it has already a value:

```
[pid 1047883] openat(AT_FDCWD, "/proc/self/loginuid", O_RDWR|O_NOFOLLOW) = 3
[pid 1047883] read(3, "1000", 24)       = 4
[pid 1047883] read(3, "", 20)           = 0
[pid 1047883] close(3)                  = 0
```

This is the Containerfile I've used:

```
FROM fedora
RUN yum install -y systemd openssh-server && yum clean all -y \
&& systemctl enable sshd \
&& adduser foo -p '$y$j9T$qs3an4DwYukN5egjZMvQe0$lrrYNXm/zCXqMqwAK9bZ551tYUAXth9pHOyTLjdaXJ/'
```

The password is `foo`

```
# podman run -d  --cap-add AUDIT_WRITE -p 2222:22  --rm fedora-ssh /usr/lib/systemd/systemd
70823234a41463b426600edd43c7a21f14ff6e35e683439abc459994929ea4e2

$ ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 2222 foo@localhost
Warning: Permanently added '[localhost]:2222' (ED25519) to the list of known hosts.
foo@localhost's password: 
[foo@70823234a414 ~]$ 
```

It even works with rootless.

**Comment by rhatdan** [comment]
I believe loginuid would only be set on a new login user, iff the loginuid is set to 0 before the user is launched.
If a user launches sshd (even via a container) then the sshd would have the users loginuid, and when it launches a process, would not attempt to write the loginuid.  (AT least that is my understanding on how this is supposed to work).
If loginuid is set to 0 (being launched directly from systemd), then I would think sshd would attempt to set the loginuid.

**Comment by vikas-goel** [comment]
I tried this with the latest podman mainline on vanilla RHEL8.5. But still running into the issue same issue without AUDIT_CONTROL capability.

**Comment by vikas-goel** [comment]
As I mentioned earlier, it was working with podman 3.3.1. It works with Docker too with exactly same container image without adding AUDIT_CONTROL capability.

From Docker container where SSH works:
```
$ capsh --print
Current: = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_sys_admin,cap_mknod,cap_audit_write,cap_setfcap+i
Bounding set =cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_sys_admin,cap_mknod,cap_audit_write,cap_setfcap
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
uid=1000(appadmin)
gid=100(users)
groups=0(root),10(wheel),100(users)
```

From Podman (mainline) container where SSH does not work:
```
bash-4.2# capsh --print
Current: = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_audit_write,cap_setfcap+eip
Bounding set =cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_audit_write,cap_setfcap
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
uid=0(root)
gid=0(root)
groups=
bash-4.2#
```

In both cases the command output is from inside the container with exactly same image.

**Comment by giuseppe** [comment]
the docker container has CAP_SYS_ADMIN, I believe Podman will work in the same way if you add CAP_SYS_ADMIN (that is almost equivalent to running as root on the host).

**Comment by vikas-goel** [comment]
Podman container with SYS_ADMIN capability didn't help. Received exactly same error with the following container.
```
# podman exec -it mycontainer capsh --print
Current: = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_sys_admin,cap_audit_write,cap_setfcap+eip
Bounding set =cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_sys_admin,cap_audit_write,cap_setfcap
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
uid=0(root)
gid=0(root)
groups=
```

On the other hand, I can SSH in Docker environment without SYS_ADMIN capability
```
$ id
uid=1000(appadmin) gid=100(users) groups=100(users),0(root),10(wheel)
$ capsh --print
Current: = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap+i
Bounding set =cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
uid=1000(appadmin)
gid=100(users)
groups=0(root),10(wheel),100(users)
```

**Comment by mheon** [comment]
First, largest observation: UID and GID are different in the Podman container and Docker container. Were the containers in Docker vs Podman started differently?

The capabilities are definitely different as well, will get a more detailed diff

**Comment by giuseppe** [comment]
what is the content of `/proc/$PID/loginuid` for the current shell where you launch podman and for the dockerd process?

**Comment by rhatdan** [comment]
Yup, the issue is if /proc/$PID/loginuid is set, IE not -1, then modifying this field requires AUDIT_CONTROL. 
If the loginuid you are attempting to change is -1, then you ownly need AUDIT_WRITE.

Since dockerd is started by systemd, it will work, and since Podman is started by a logged in user, it will not.

If you setup podman.socket and podman.service and run your container with podman --remote, it will probably work.

**Comment by vikas-goel** [comment]
> First, largest observation: UID and GID are different in the Podman container and Docker container. Were the containers in Docker vs Podman started differently?
> 
> The capabilities are definitely different as well, will get a more detailed diff

The UID and GID are different because I had to run `capsh` in Podman using `podman exec` as I was not able to SSH. Running that command landed me to `root` account. Whereas, in case of Docker I ran the same `capsh` command after doing SSH to the container as non-root user.
If I run the `capsh` command using `docker exec`, then the UID/GID will be same.

**Comment by vikas-goel** [comment]
> Differences are: Docker has `cap_mknod` and `cap_setfcap+i` - Podman has `cap_sys_admin` and `cap_setfcap+eip`

The cap_sys_admin is not making any difference. SSH is possible in Docker env with and without this capability. Whereas, cannot SSH in Podman in either case.

Will other capability differences make any change in ability to SSH?

**Comment by vikas-goel** [comment]
> what is the content of `/proc/$PID/loginuid` for the current shell where you launch podman and for the dockerd process?

Its `0` in both cases.

**Comment by vikas-goel** [comment]
It's 0 for podman and 4294967295 for dockerd

**Comment by vikas-goel** [comment]
> what is the content of `/proc/$PID/loginuid` for the current shell where you launch podman and for the dockerd process?

It's 0 for podman and 4294967295 for dockerd

**Comment by vikas-goel** [comment]
> Yup, the issue is if /proc/$PID/loginuid is set, IE not -1, then modifying this field requires AUDIT_CONTROL. If the loginuid you are attempting to change is -1, then you ownly need AUDIT_WRITE.
> 
> Since dockerd is started by systemd, it will work, and since Podman is started by a logged in user, it will not.
> 
> If you setup podman.socket and podman.service and run your container with podman --remote, it will probably work.

This works. Is there a configuration parameter that can be tuned to achieve the same without running podman.socket and podman.service (and --remote)?

**Comment by giuseppe** [comment]
you may need to tweak the pam configuration to not require `pam_loginuid.so`

**Comment by vikas-goel** [comment]
Host level configuration change is in the control, not inside the container. Is there is a way to achieve with host configuration change?
If not, can we take this is an RFE?

**Comment by vikas-goel** [comment]
How shall I proceed? Create a new RFE or convert this one?

**Comment by giuseppe** [comment]
I don't think there is anything we should do in Podman to address it.

The configuration could be done on the host too, if ssh on the host doesn't write to loginuid then the container is free to do so (but I'd suggest to not do it).

Another alternative is to delegate the container startup to a systemd unit, like: `systemd-run podman run ....`

Opened a PR to document it: https://github.com/containers/podman/pull/13197

**Comment by rhatdan** [comment]
Does SSHD actually fail, or does it print an error?

**Comment by rhatdan** [comment]
BTW I wish that the kernel would just block setting the loginuid altogether, I think it ruins the security of the system allowing any process to modify this.

**Comment by SadPencil** [comment]
Additional notes:

Besides enabling `AUDIT_WRITE`, there is another way to solve this problem.
Editing the `/etc/ssh/sshd_confilg` file and find the following line:
```
SyslogFacility AUTHPRIV
```
and change it to
```
SyslogFacility AUTH
```
So writting this line in the dockerfile
```
RUN sed -i -e 's/^SyslogFacility AUTHPRIV/SyslogFacility AUTH/' /etc/ssh/sshd_config
```

Then, sshd will no longer requires `AUDIT_WRITE` and it is totally acceptable for containers.

**Comment by rhatdan** [comment]
Very nice would like to get this into the troublshoot.md file.

**Comment by tobwen** [comment]
> BTW I wish that the kernel would just block setting the loginuid altogether, I think it ruins the security of the system allowing any process to modify this.

I think you can set `AUDIT_FEATURE_LOGINUID_IMMUTABLE` to disallow changes:
https://github.com/torvalds/linux/blob/e359bce39d9085ab24eaa0bb0778bb5f6894144a/Documentation/ABI/stable/procfs-audit_loginuid#L12-L15

**Comment by rhatdan** [comment]
Is this available as a sysctl or just at kernel build time?

I think this should be default in Fedora BTW.

**Comment by tobwen** [comment]
> Is this available as a sysctl or just at kernel build time?

```auditctl --loginuid-immutable```
