### ISSUE TITLE
Failed to restart podman container: Error adding network: failed to allocate for range 

### ISSUE THREAD

**Issue by ghost** [containers/podman#13022]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

kind bug

**Description**

**Steps to reproduce the issue:**

1. sudo podman generate systemd --name application_frontend_1 --files (This will generate container-application_frontend_1.service)

2. sudo mv container-application_frontend_1.service  /etc/systemd/system/application_frontend_1.service

3. Command 1: sudo systemctl enable application_frontend_1

4. Command 2: sudo systemctl start application_frontend_1

5. Command 3: sudo systemctl status application_frontend_1

6. Sudo reboot

**Describe the results you received:**

1. podman ps (after reboot) => show no active containers

2. podman ps -a (after reboot) => show 2 containers application_frontend_1 and the podman infra container
 
```
cd10e78503ac  git.company.com:5050/apps/application-frontend:latest  nginx -g daemon o...  3 hours ago     Exited (0) 17 minutes ago  0.0.0.0:4051->80/tcp  application_frontend_1
137113410c17  k8s.gcr.io/pause:3.1                                                      3 hours ago     Created                    0.0.0.0:4051->80/tcp  b6094df0a429-infra
```

When running manually the following command: podman start application_frontend_1 

```

ERRO[0000] Error adding network: failed to allocate for range 0: 10.85.3.180 has been allocated to 137113410c17a15f40e3f07c471f2884c5a9404f4664d2fa5e993278f502d73b, duplicate allocation is not allowed 
ERRO[0000] Error while adding pod to CNI network "podman": failed to allocate for range 0: 10.85.3.180 has been allocated to 137113410c17a15f40e3f07c471f2884c5a9404f4664d2fa5e993278f502d73b, duplicate allocation is not allowed 
ERRO[0000] error starting some container dependencies   
ERRO[0000] "error configuring network namespace for container 137113410c17a15f40e3f07c471f2884c5a9404f4664d2fa5e993278f502d73b: failed to allocate for range 0: 10.85.3.180 has been allocated to 137113410c17a15f40e3f07c471f2884c5a9404f4664d2fa5e993278f502d73b, duplicate allocation is not allowed" 
Error: unable to start container "application_frontend_1 ": error starting some containers: internal libpod error

```

The following container ID (137113410c17a15f40e3f07c471f2884c5a9404f4664d2fa5e993278f502d73b) correspond to the podman infra container.

**Describe the results you expected:**

I would expect that podman container restarted successfully after reboot.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:** 1.6

```
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.6.4
host:
  BuildahVersion: 1.11.5
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.15-1.el7_8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.15, commit: 372b4a12f1c2df4f70c280d41173b60acd3f1260'
  Distribution:
    distribution: '"rhel"'
    version: "7.9"
  MemFree: 29837733888
  MemTotal: 33567277056
  OCIRuntime:
    name: runc
    package: runc-1.0.0-67.rc10.el7_8.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 2147479552
  SwapTotal: 2147479552
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: xyz
  kernel: 3.10.0-1160.24.1.el7.x86_64
  os: linux
  rootless: false
  uptime: 47m 15.96s
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 11
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 7
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.4-29.el7_9.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

N/A

**Comment by mheon** [comment]
Please try a more recent Podman. 1.6.4 is very old at this point; I can recall at least two potential solutions to this that have landed since then, discounting the network stack rewrite in the upcoming v4.0 that will completely eliminate the code that could cause it.
