### ISSUE TITLE
how do i put multiple commands in entrypoint?

### ISSUE THREAD

**Issue by imperialguy** [containers/podman#13026]
i am looking for something like this: 
podman run --entrypoint "/sbin/init && /path/to/my/script.sh"

**Comment by flouthoc** [comment]
Hi @imperialguy , Thanks for opening the issue.

I think you can only choose one executable but you could provide other commands as arguments.

For example my image contains `sh` and `bash`.

So i do it like
```console
podman run -it --rm --entrypoint "/bin/sh" test -c 'echo hello && echo world'
```

similarly if your init accepts scripts as argument you could provide it as arguments.

**Comment by imperialguy** [comment]
> 

I don't think `podman run` has any option called `-c`, did you mean this? I don't think this works either. 

```
podman run -it --rm --entrypoint "/bin/sh test -c 'echo hello && echo world'"
```

Also, `/sbin/init` basically is a shortcut to calls `systemd`. What I want is the ability to run commands right after `systemd` initializes. Any ideas?

**Comment by flouthoc** [comment]
@imperialguy `-c` is not a podman option but argument to my entrypoint binary which is `/bin/sh`. and `test` is my image name.

I'll use `alpine` so its not confusing, try below command as it is.

```console
podman run -it --rm --entrypoint "/bin/sh" alpine -c 'echo hello && echo world'
```

**Comment by Luap99** [comment]
You can use `--entrypoint '["command", "with", "args"]'`, see https://github.com/containers/podman/blob/main/docs/source/markdown/podman-create.1.md#--entrypointcommand--command-arg1-

**Comment by imperialguy** [comment]
This solution doesn't work with `/sbin/init`. Please re-open.

```
podman run -d --name mycontainer --entrypoint "/bin/sh" myimage -c '/sbin/init && echo hello'
```

The above will result in a container that exits immediately. I don't want the container exiting. For example, if I do the following, the container stays up and running. 

```
podman run -d --name mycontainer --entrypoint "/bin/sh" myimage -c '/sbin/init'
```

But, what I want is to be able to run commands after the `/sbin/init`.

**Comment by rhatdan** [comment]
If you run a container with the init system, then the secondary script should be put into a unit file if the system is using systemd, if it is not then it should be put into an rc script that the init system launches.  Bottom line what you are trying to do  is not going to work.
