### ISSUE TITLE
[RFE] Include pod name in `podman ps` `--format` and `--sort`

### ISSUE THREAD

**Issue by mskarbek** [containers/podman#13033]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I would like to use pod name not only id in formatted `podman ps` output and be able to sort that output based on pod name and id. The current alternative is to print pod id first and just pipe that output to `sort`. ;) Usable, but UX could be better, especially considering the fact that I have to match pod id with the pod name after in the second step.
```
#  podman ps -a --format "{{.Pod}}\t{{.Names}}\t{{.Image}}\t{{.Status}}"|sort
40ba88f1b135  inf-gitlab-2201251034-app       registry.lab.skarbek.name/bootstrap/gitlab:latest     Up 2 days ago
40ba88f1b135  inf-gitlab-2201251034-infra     registry.lab.skarbek.name/pause:8.5-1                 Up 2 days ago
40ba88f1b135  inf-gitlab-2201251034-mesh      registry.lab.skarbek.name/bootstrap/kuma-dp:latest    Up 2 days ago
40dc4fdebf52  inf-minio-2201251034-app        registry.lab.skarbek.name/bootstrap/minio:latest      Up 2 days ago
40dc4fdebf52  inf-minio-2201251034-infra      registry.lab.skarbek.name/pause:8.5-1                 Up 2 days ago
40dc4fdebf52  inf-minio-2201251034-mesh       registry.lab.skarbek.name/bootstrap/kuma-dp:latest    Up 2 days ago
4abd13034fc2  inf-nginx-2201251034-app        registry.lab.skarbek.name/bootstrap/nginx:latest      Up 2 days ago
4abd13034fc2  inf-nginx-2201251034-infra      registry.lab.skarbek.name/pause:8.5-1                 Up 2 days ago
4abd13034fc2  inf-nginx-2201251034-mesh       registry.lab.skarbek.name/bootstrap/kuma-dp:latest    Up 2 days ago
4d598b8287dc  inf-kuma-2201251034-app         registry.lab.skarbek.name/bootstrap/kuma-cp:latest    Up 2 days ago
4d598b8287dc  inf-kuma-2201251034-infra       registry.lab.skarbek.name/pause:8.5-1                 Up 2 days ago
4d598b8287dc  inf-kuma-2201251034-mesh        registry.lab.skarbek.name/bootstrap/kuma-dp:latest    Up 2 days ago
b4ec41011436  inf-nexus-2201251034-app        registry.lab.skarbek.name/bootstrap/nexus:latest      Up 2 days ago
b4ec41011436  inf-nexus-2201251034-infra      registry.lab.skarbek.name/pause:8.5-1                 Up 2 days ago
b4ec41011436  inf-nexus-2201251034-mesh       registry.lab.skarbek.name/bootstrap/kuma-dp:latest    Up 2 days ago
fed1abdb00b5  inf-tinyproxy-2201251034-app    registry.lab.skarbek.name/bootstrap/tinyproxy:latest  Up 2 days ago
fed1abdb00b5  inf-tinyproxy-2201251034-infra  registry.lab.skarbek.name/pause:8.5-1                 Up 2 days ago
fed1abdb00b5  inf-tinyproxy-2201251034-mesh   registry.lab.skarbek.name/bootstrap/kuma-dp:latest    Up 2 days ago
```

**Comment by rhatdan** [comment]
Does `podman pod ps` help?

**Comment by mheon** [comment]
`podman ps` already has a `--pod` flag that shows pod ID in the output - is this acceptable?

**Comment by Luap99** [comment]
To get the pod name you have to use `{{.PodName}}`

**Comment by mheon** [comment]
Ahh, this is definitely a bug, then. I think we're not fetching the relevant fields from the DB unless `--pod` is specified, which means that `--format` and `--pod` being incompatible results in being unable to get pod identifying information via `--format`. Solution is probably to fetch those bits from the DB if `--format` is used, as well as `--pod`; there may be some small performance implications about this, though, it requires more DB operations for each container.

**Comment by Luap99** [comment]
IIRC we changed that for the remote api so that pod is always set for remote. I think we could string search the format and only set pod when the format contains `PodName`,

**Comment by rhatdan** [comment]
This seems to work correctly in current podman. Closing.
