### ISSUE TITLE
incorrect default infra-image in the message of podman pod create --help

### ISSUE THREAD

**Issue by noracenofun** [containers/podman#13037]
The new default image in 4.0.0-rc2 is a locally built one based on a local pause binary, build result e.g. "localhost/podman-pause:4.0.0-rc2-1642795764" and no longer the image "k8s.gcr.io/pause:3.5" (DefaultInfraImage = "k8s.gcr.io/pause:3.5"), but the command podman pod create --help does not yet support this feature for the output of the default infra-image.

If the user does not specify an image, the builtin image is now used.

The default hardcoded image defined via DefaultInfraImage is no longer pulled.

<br />

But the command `podman pod create --help` does not yet support this feature for the output of the default infra-image.

no default configuration of infra_image in any containers.conf
```
$ podman pod create --help | grep infra-image
      --infra-image string            The image of the infra container to associate with the pod (default "k8s.gcr.io/pause:3.5")
```

**expected output for example: ... (default "localhost/podman-pause:4.0.0-rc2-1642795764") or (default "builtin") or nothing
received output: ... (default "k8s.gcr.io/pause:3.5")**

<br />

default configuration of infra_image set in local containers.conf
```
$ grep infra_image .config/containers/containers.conf
infra_image = "registry.access.redhat.com/ubi8/pause"

$ podman pod create --help | grep infra-image
      --infra-image string            The image of the infra container to associate with the pod (default "registry.access.redhat.com/ubi8/pause")
```
**output as expected: ... (default "registry.access.redhat.com/ubi8/pause")**

<br />

The output message should be corrected.

<br />

_Originally posted by @noracenofun in https://github.com/containers/podman/issues/12771#issuecomment-1021355022_

**Comment by Luap99** [comment]
Fixed in https://github.com/containers/podman/pull/13064
