### ISSUE TITLE
docs: make clear that "remote client" implies Mac

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#13060]
/kind bug

This week, I've seen two issues where the man pages were not clear to users that "remote client" implies Mac OS and to some degree Windows (unless WSL2).

@TomSweeneyRedHat WDYT?

**Comment by afbjorklund** [comment]
You can run `podman --remote` on Linux ? Must be missing something here.

**Comment by vrothberg** [comment]
What I mean is that the docs mention a lot that "feature A is not available for the remote client".  It's not clear to most readers that this implies the Mac client, so I think it should be made explicit.

**Comment by rhatdan** [comment]
Attempting to clarify this with https://github.com/containers/podman/pull/13066

**Comment by afbjorklund** [comment]
OK, so when you say "implies" you mean "includes". Then agreed.

(I guess WSL2 is technically **Linux**, but most users wouldn't know)

**Comment by vrothberg** [comment]
> OK, so when you say "implies" you mean "includes". Then agreed.

Yes, thanks for clarifying :)

> (I guess WSL2 is technically **Linux**, but most users wouldn't know)

Agreed.

**Comment by afbjorklund** [comment]
We have another set of confusion, and that is those users that do "lima podman" or "podman machine ssh podman".

_Then_ we could argue if it is Mac or Linux (since the command is run on the other end of `ssh`, it would be: Linux)

**Comment by TomSweeneyRedHat** [comment]
I like the thinking, I've found the remote client/macOS bit to be confusing.  I just don't want us to go too strong and make people think we're not Windows too.

**Comment by Luap99** [comment]
The PR https://github.com/containers/podman/pull/13066 is merged
