### ISSUE TITLE
rootless libpod (v3.4.4) does not always configure an image store

### ISSUE THREAD

**Issue by entrope** [containers/podman#13086]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

A libpod-using program (written in Go) can only call `(*Runtime).LibimageRuntime().LookupImage()` the first time it runs.  Later executions of the program panic with a nil pointer dereference.

**Steps to reproduce the issue:**

1. In rootless mode, call `podman, err := libpod.NewRuntime(ctx, ...)`.

2. Call `_, _, err = podman.LibimageRuntime().LookupImage(...)`.

3. Run the program a second time.

**Describe the results you received:**

The LookupImage() call works during the program's first execution, but panics the second (and later) times the program runs.

**Describe the results you expected:**

LookupImage() should consistently succeed or consistently fail, independent of previous program executions.

**Additional information you deem important (e.g. issue happens only occasionally):**

`(Runtime).libimageRuntime` is only sometimes assigned (by calling `(*Runtime).configureStore()`): Namely, when executed with `CAP_SYS_ADMIN` or when `runtimeAliveFile` needs to be re-created.  In rootless mode, when `runtimeAliveFile` already exists, `configureStore()` is never called and so `libimageRuntime` remains nil.

**Output of `podman version`:**

```
ersion:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.5
Built:        Wed Dec 31 19:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 48
  distribution:
    distribution: debian
    version: unknown
  eventLogger: journald
  hostname: sanosuke
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.0-3-amd64
  linkmode: dynamic
  logDriver: journald
  memFree: 83681480704
  memTotal: 134987735040
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 68582109184
  swapTotal: 68582109184
  uptime: 17h 9m 59.24s (Approximately 0.71 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/mdpoole/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/mdpoole/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 34
  runRoot: /run/user/1000/containers
  volumePath: /home/mdpoole/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Wed Dec 31 19:00:00 1969
  GitCommit: ""
  GoVersion: go1.17.5
  OsArch: linux/amd64
  Version: 3.4.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/testing,now 3.4.4+ds1-1 amd64 [installed]
podman/testing 3.4.4+ds1-1 i386
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Rootless mode on a physical x86_64 system.

**Comment by Luap99** [comment]
I am not sure if we support using libpod as library, at least it does not have a stable interface so you could run into breaking changes on every update.
There is some special code in https://github.com/containers/podman/blob/main/pkg/rootless/rootless_linux.c which should make podman join the user ns without having to rexec.

**Comment by Luap99** [comment]
I think you need to call this https://github.com/containers/podman/blob/905d31ddd358bb6c40082c391102bbf92a04fad6/cmd/podman/root.go#L263-L275

**Comment by rhatdan** [comment]
I agree.

**Comment by rhatdan** [comment]
Or at least say it has to be used as root inside of a user namespace.

**Comment by entrope** [comment]
Thank you for the feedback.

From my perspective, it is fine if libpod is not supported, or only supported as root -- I can call out to the system podman executable from my program.  It would be helpful if any such limitation is documented in a libpod package-level documentation comment.
