### ISSUE TITLE
"podman randomstring --someflag" complains about the flag, not the command

### ISSUE THREAD

**Issue by eriksjolund** [containers/podman#13082]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

A misleading error message is shown when running

```
podman randomstring --someflag
```

Podman complains about the unknown flag `--someflag`. It would be better if Podman would complain about the unknown command `randomstring`.

**Steps to reproduce the issue:**

1.

```
$ podman randomstring --someflag
Error: unknown flag: --someflag
$ 
```

**Describe the results you received:**

```
Error: unknown flag: --someflag
```

**Describe the results you expected:**

```
Error: unknown command: randomstring
```

**Output of `podman version`:**

```
podman version 4.0.0-rc2
```

**Comment by Luap99** [comment]
I think this is something which must be fixed in the cobra library, see https://github.com/spf13/cobra/issues/1409

**Comment by eriksjolund** [comment]
@Luap99 Sure, it's a bit better.
