### ISSUE TITLE
Search DNS not working correctly.

### ISSUE THREAD

**Issue by rhatdan** [containers/podman#13103]
```
$ podman run -ti alpine ping help
PING help (209.132.183.105): 56 data bytes
64 bytes from 209.132.183.105: seq=0 ttl=42 time=64.800 ms
64 bytes from 209.132.183.105: seq=1 ttl=42 time=123.429 ms
$ podman run -ti alpine ping help.redhat.com
PING help.redhat.com (209.132.183.105): 56 data bytes
64 bytes from 209.132.183.105: seq=0 ttl=42 time=65.246 ms
64 bytes from 209.132.183.105: seq=1 ttl=42 time=64.677 ms
$ podman run -ti --network podman1 alpine ping help.redhat.com
PING help.redhat.com (209.132.183.105): 56 data bytes
64 bytes from 209.132.183.105: seq=0 ttl=42 time=64.744 ms
64 bytes from 209.132.183.105: seq=1 ttl=42 time=66.691 ms
```
No Work:

```
$ podman run -ti --network podman1 alpine ping help
ping: bad address 'help'
```
Aardvark is failing to handle search dns record.
```
$ cat /etc/resolv.conf 
...
nameserver 127.0.0.53
options edns0 trust-ad
search redhat.com
```

**Comment by flouthoc** [comment]
@rhatdan Yes i think this issue is agnostic of `netavark` or `cni` and more of podman behavior issue. It seems podman does not inherits host's `/etc/resolv.conf` , i can reproduce it with CNI as well. Could someone else also confirm if they are able to reproduce this with CNI.

**Comment by Luap99** [comment]
Yes podman removes the other search domains. I think we have to append them.
IIRC I added this logic originally and just followed the way how it was done for the nameserver ips since we will also remove the other servers.

**Comment by Luap99** [comment]
I will open a PR

**Comment by Luap99** [comment]
When we set `--dns 1.1.1.1` should we add our nameserver first or use the one from the user first, same for the search domain?
