### ISSUE TITLE
play kube: container resources (cpu, memory) do not have defaults

### ISSUE THREAD

**Issue by ydayagi** [containers/podman#13115]
/kind bug

**Description**
k8s container resources seem to have defaults. For memory, it is entire appliance memory. For CPU it is all CPUs. Executing 'play kube' with kind Pod shows that our defaults are '0'. I think we should set defaults as k8s does so 'play kube' will be consistent with k8s. Features such as setting env vars from resource values will not function properly.

**Output of `podman version`:**
using latest podman code
```
Client:       Podman Engine
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.16.8
Git Commit:   2ceab119478502fd06703036bc79953ed6f37f74-dirty
Built:        Wed Feb  2 16:59:29 2022
OS/Arch:      linux/amd64
```

**Comment by baude** [comment]
care to submit a pr ?

**Comment by ydayagi** [comment]
> care to submit a pr ?

gladly :-) already on it

**Comment by ydayagi** [comment]
The actual CPU and memory assigned to the pod seem to be OK. The only problem that needed to be fixed was the field values in the Container object in code.
