### ISSUE TITLE
ipvlan does not see dhcp.sock

### ISSUE THREAD

**Issue by Loader009** [containers/podman#13135]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

As a workaround of the other issue - now I wanted to try out ipvlan (L3/L3s), since I could use firewall rules and masquerading.
I create the network "public" for that.
reverse-proxy container added to that - but the container doesn't start because dhcp.sock canot be found.

looked where dhcp is -> /opt/cni/bin/dhcp
started dhcp with root and later as a normal user - no success

**Steps to reproduce the issue:**

1. `podman network create -d ipvlan -o mode=l3 --ipv6 public`

2. `podman create --name=reverse-proxy --net public -p 8080:80 -p 8443:443 docker.io/library/nginx:1-alpine`

3. make sure `/run/cni` is writable by the same user
4. `/opt/cni/bin/dhcp daemon`
5. open a second terminal/session:\
`podman start reverse-proxy`
6. error appears immediately

**Describe the results you received:**
```
WARN[0000] Failed to load cached network config: network public not found in CNI cache, falling back to loading network public from disk 
WARN[0000] 1 error occurred:
	* plugin type="ipvlan" failed (delete): cni plugin ipvlan failed: error dialing DHCP daemon: dial unix /run/cni/dhcp.sock: connect: no such file or directory
```

**Describe the results you expected:**
container should be started and should get an IP from dhcp(?)
That's my theory - I wanted to experiment first.

**Additional information you deem important (e.g. issue happens only occasionally):**
```shell
$ ls -l /run/cni/dhcp.sock
srwxr-x--- 1 pods pods 0 Feb  3 23:05 /run/cni/dhcp.sock
```
**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.17.6
Git Commit:   c2f4747fea508a6c6b0fdbf7a51eb6c80ba57f02
Built:        Fri Jan 28 17:38:52 2022
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.0-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: bdb4f6e56cd193d40b75ffc9725d4b74a18cb33c'
  cpus: 4
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: xxx
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.15.15-hardened1-1-hardened
  linkmode: dynamic
  logDriver: journald
  memFree: 123461632
  memTotal: 4035624960
  networkBackend: cni
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.4.2-1
    path: /usr/bin/crun
    version: |-
      crun version 1.4.2
      commit: f6fbc8f840df1a414f31a60953ae514fa497c748
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1002/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /sbin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.1.12-1
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 317h 56m 46.99s (Approximately 13.21 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - ghcr.io
  - quay.io
  - docker.io
store:
  configFile: /home/pods/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 1
    stopped: 1
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /home/pods/.local/share/containers/storage
  graphStatus:
    Build Version: 'Btrfs v5.16 '
    Library Version: "102"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 7
  runRoot: /run/user/1002/containers
  volumePath: /home/pods/.local/share/containers/storage/volumes
version:
  APIVersion: 4.0.0-dev
  Built: 1643387932
  BuiltTime: Fri Jan 28 17:38:52 2022
  GitCommit: c2f4747fea508a6c6b0fdbf7a51eb6c80ba57f02
  GoVersion: go1.17.6
  OsArch: linux/amd64
  Version: 4.0.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ pacman -Qs podman-git
local/podman-git 4.0.0_dev.r14158.gc2f4747fe-1
    Tool and library for running OCI-based containers in pods (git)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by Luap99** [comment]
You cannot really use ipvlan/macvlan as rootless user. To make the rootless networking work we have to use an extra network and mount namespace. The network namespace will be connected via slirp4netns to the host. see `podman unshare --rootless-netns` to join this ns.
To make cni work we have to bind mount new cni directories to into this namespace so that we can write to it. That is why it cannot find the dhcp socket. But even if it were there you could still not use it since it requires root permissions to use it. Also the ipvlan/macvlan plugin would be unable to find your host device in this namespace.

**Comment by Luap99** [comment]
The rootless container ip addresses are not routeable anyway so it does not make sense to use dhcp. Eveything has to be proxied trough slirp4netns.

**Comment by Loader009** [comment]
Then the only workaround would be:
- create a host-reverse proxy (without podman) with proxy-headers
- forward all traffic to the published ports of the reverse-proxy container (with multiple networks)
- use the proxy-headers to regain the original IP

While this will "somehow" work with http/https traffic, this won't work for the mailserver. There I cannot even use fail2ban because of podmans limitations with multiple networks and port_handler=slirp4netns.

No other workaround comes in my mind...
The mailserver container must not have multiple networks - then I have to publish the DB-port also, to be able to let them connect.


Feels like every workaround I try - is a dead end.
