### ISSUE TITLE
podman inspect does not show network info on a joined network namespace

### ISSUE THREAD

**Issue by idleroamer** [containers/podman#13150]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

On a joined network namespace mode `--net ns:<path>` podman inspect fails to report the network info like `IPAddress`.

**Steps to reproduce the issue:**

1. create a named network namespace and setup a veth interface
```
ip netns add test
ip netns exec test /bin/bash
ip link add enp2s0 type veth peer name eth0
ip addr add 10.0.1.0/24 dev eth0
ip link set eth0 up
exit
```
2. run a container and join the created network namespace
`podman run --net ns:/run/netns/test --name test -it alpine /bin/sh`
3. check proper association `ip addr show`
```
eth0      Link encap:Ethernet  HWaddr BA:AF:09:0E:F6:96  
          inet addr:10.0.1.0  Bcast:0.0.0.0  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
4. Check output of `podman inspect test | grep -i IPAddress`

**Describe the results you received:**

No `IPAddress` information

**Describe the results you expected:**

Expect to see the `IPAddress` of the network namespace `10.0.1.0`

**Output of `podman version`:**
`podman version 3.4.5-dev`
```
(paste your output here)
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - pids
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.27+git0+3efab3e71c-r0.core2_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.28-dev, commit: 3efab3e71c4c29f127cd7b8e8a5a885fc17dec88'
  cpus: 6
  distribution:
    distribution: mbient
    version: "1.0"
  eventLogger: journald
  hostname: qemux86-64
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.30-yocto-standard
  linkmode: dynamic
  logDriver: journald
  memFree: 19393208320
  memTotal: 23417106432
  ociRuntime:
    name: crun
    package: crun-0.18+gitf302dd8c02c6fddd2c50d1685d82b7a19aae8afe-r0.core2_64
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: f302dd8c02c6fddd2c50d1685d82b7a19aae8afe
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-0.4.1-r0.core2_64
    version: |-
      slirp4netns version 0.4.1
      commit: unknown
  swapFree: 52424704
  swapTotal: 52424704
  uptime: 1h 34m 3.16s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  localhost:5000:
    Blocked: false
    Insecure: true
    Location: localhost:5000
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: localhost:5000
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 26
    paused: 0
    running: 6
    stopped: 20
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 53
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.5-dev
  Built: 1642150595
  BuiltTime: Fri Jan 14 09:56:35 2022
  GitCommit: 63134a1ef8e85395fb0aedbe966fb6b4f1d91470-dirty
  GoVersion: go1.16.3
  OsArch: linux/amd64
  Version: 3.4.5-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.0+git0+63134a1ef8-r0.core2_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes, same defect reproducible with 4.0.0.

**Comment by mheon** [comment]
This isn't possible with the current code we're using, we'd require an ability to nsenter into the container's namespace and parse the current network config; potentially a significant amount of work, there.

**Comment by Luap99** [comment]
This sounds like a feature to me. At the moment we only use the info we have when podman configures the network via cni/netavark.

I am not sure if this would even make sense to display information on an arbitrary namespace.
First, it can have n interfaces with n ip addresses, so I have no idea what podman should display (all of them?).
Second, we do not even know how the netns is connected. It is possible that the ip address is not routable from the host.

IMO, if you use a custom netns you should not rely podman to display information about it. Since you manually configured the netns you should already know how it was configured.

**Comment by idleroamer** [comment]
Thanks for the prompt answer and transparent info.
I hoped it is a low-hanging fruit which could be easily fixed by just collecting the network config via netns but looking around in podman code-base and your input it seems not to be the case.
I will try to give it more in-depth analysis if a relatively small patch is feasible without causing so much ripples otherwise I would not oppose to be postponed or eventually closed.

**Comment by idleroamer** [comment]
PR here https://github.com/containers/podman/pull/13361/
