### ISSUE TITLE
Podman build gives "ERRO[0378] error unmounting /var/lib/containers/storage/overlay/..."

### ISSUE THREAD

**Issue by aakash086** [containers/podman#13166]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Create a dockefile with following contents : 
FROM python:3.8
RUN apt-get update && apt-get -y upgrade
RUN pip install --upgrade pip
WORKDIR /app .
EXPOSE 8000
RUN chmod 777 -R /app
CMD [ "python", "./server.py" ]
(server.py contains simple print of a list)

2. Execute sudo podman build -t aakash .

3. Receiving below error : 
ERRO[0378] error unmounting /var/lib/containers/storage/overlay/4722e4f1d0cfe2e9d4ff26241a74eb0750c7d6bb187bbf7c6692bda3a875f849/merged: invalid argument
Error: error mounting new container: error mounting build container "01bdc8df7dc81adc19602239c90c843d39d58458b2cdf2f11eefd53948c73ebc": error creating overlay mount to /var/lib/containers/storage/overlay/4722e4f1d0cfe2e9d4ff26241a74eb0750c7d6bb187bbf7c6692bda3a875f849/merged, mount_data="nodev,metacopy=on,lowerdir=/var/lib/containers/storage/overlay/l/ZMEF63F2NGZJFXNRVVPKZMZ4KM:/var/lib/containers/storage/overlay/l/D3CM2BWNOXVMJ6MOUE45YZR6RF:/v......."

**Describe the results you received:**

Error

**Describe the results you expected:**
 Image should be created successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
podman version 3.4.2
```
(paste your output here)
```

**Output of `podman info --debug`:**
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - devices
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 8
  distribution:
    codename: focal
    distribution: ubuntu
    version: "20.04"
  eventLogger: file
  hostname: ITEM-s94666
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.4.0-18362-Microsoft
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 1288380416
  memTotal: 8386789376
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: ea1fe3938eefa14eb707f1d22adff4db670645d6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: false
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 11925647360
  swapTotal: 13122793472
  uptime: 5h 19m 31.91s (Approximately 0.21 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: <unknown>
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 0
  BuiltTime: Thu Jan  1 05:30:00 1970
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.4.2
```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by aakash086** [comment]
The docker would run fine , but the podman gives error for simplest of docker files.

**Comment by flouthoc** [comment]
Hi @aakash086 Could you please paste the full error, you have pasted incomplete error so its hard to tell what's failing. But it seems something is going wrong while using `overlay` on your system, full error message would help us debug this better.

Also try using latest `podman` since `3.4.2` looks old and lot of changes went after that. https://github.com/containers/podman/releases/tag/v3.4.4

**Comment by aakash086** [comment]
Hi @flouthoc  : I have uninstalled everything and going to install Podman from scratch today, allow me 1 day of time and if I get the same error , I am going to put it here. Thanks for acknowledging though.

**Comment by rhatdan** [comment]
Since we got no more feedback, I am assuming the error went away,  Reopen if I am mistaken.
