### ISSUE TITLE
Not Possible to Use Multiple slirp4netns Networks

### ISSUE THREAD

**Issue by scolby33** [containers/podman#13169]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I would like to create a rootless container with multiple slirp tun devices, so that I can use the `outbound_addr=INTERFACE` option to route outbound traffic to specific interfaces within the container.

**Steps to reproduce the issue:**

1. `podman run --network=slirp4netns:outbound_addr=en1 --network=slirp4netns:outbound_addr=en2 -- debian ls /sys/class/net`

**Describe the results you received:**

1. Notice that there is only `lo` and `tun0`
2. Check `podman inspect` to see that only one network is configured (as far as I can tell, the last `--network` option passed takes precedence

**Describe the results you expected:**
There would be two `tun?` devices configured, two instances of `slirp4netns` running with the appropriate `--outbound-addr` option, two networks would be visible in `podman inspect`

**Additional information you deem important (e.g. issue happens only occasionally):**
An alternative solution using networks explicitly created with `podman network create` and/or manually configuring the CNI network definition would work for me as well. (But I looked at the CNI docs and couldn't see a way to specify the outbound interface for a bridge network.)

**Output of `podman version`:**

```
$ podman version
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.9
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

(I know it's old, but that's what I've got on Debian 11)

**Output of `podman info --debug`:**

```
$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.19.6
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 16
  distribution:
    distribution: debian
    version: "11"
  eventLogger: journald
  hostname: debian11
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.0-11-amd64
  linkmode: dynamic
  memFree: 53845733376
  memTotal: 135018254336
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /home/scott/slirp4netns/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.3.3
  swapFree: 17179865088
  swapTotal: 17179865088
  uptime: 47h 40m 14.48s (Approximately 1.96 days)
registries: {}
store:
  configFile: /home/scott/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.10.3
        fuse-overlayfs: version 1.4
        FUSE library version 3.10.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/scott/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 3
  runRoot: /run/user/1000/containers
  volumePath: /home/scott/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.9
  OsArch: linux/amd64
  Version: 3.0.1

```

(Notice that I'm using a newer version of slirp4netns than is available in the Debian repos to get the `outbound_addr` feature.)

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/stable,now 3.0.1+dfsg1-3+b2 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No--I have not tried an updated Podman, but I don't believe this feature has been implemented from a reading of the release announcements

Yes--I have read the troubleshooting guide

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine

**Comment by Luap99** [comment]
I do not think this is possible. What is your goal here?

Even if there would be two slirp4netns interfaces in the container with different outbound interfaces the container still has only one default route so all the traffic would only be routed through one of them.

**Comment by scolby33** [comment]
In my particular case, I would like to configure dnsdist to connect to an upstream DNS server via a specific interface without altering the host's routing table (https://dnsdist.org/guides/downstreams.html#source-address-selection).

However, in general, it would also be possible to configure a routing table inside the container, would it not? For example, if you wanted to use a different default route in the container than on the host.

When you say this is not possible, do you mean truly impossible given the constraints on rootless networking in the current Linux Kernel or not possible without changes to Podman?

**Comment by Luap99** [comment]
Well it is possible from the kernel point of view but I really do not see how podman could expose this. I also do not know if slirp4netns supports this but I see no reason why it would not support it.

The problem is that I see no good way to integrate this into podman, there can only be one default gateway. Altering the routing table in the container netns to support some special rules is out of scope IMO.

**Comment by Luap99** [comment]
You can always use your own custom network namespace via --network ns:/path/to/netns

**Comment by Luap99** [comment]
Closing since I consider this out of scope for podman. You can always setup the network namespace yourself and use it via `--network ns:/path/to/netns`
