### ISSUE TITLE
rootless `podman run --network=none` from inside a container due to `default_sysctls` `ping_group_range`

### ISSUE THREAD

**Issue by bburky** [containers/podman#13194]
**Description**

Inside a container `/proc/sys/net/ipv4/ping_group_range` may not exist. The [`default_sysctls` include `net.ipv4.ping_group_range=0 0`](https://github.com/containers/common/blob/f34973f3d54cf4e7c7e14dac36f32fb6d46d9dd6/pkg/config/containers.conf#L66-L68). If rootless podman is run inside a container, accessing this file may fail.

I discovered this when trying to run a rootless `podman run --network=none ...` inside a Kubernetes container.

**Steps to reproduce the issue:**

To reproduce the issue, run the following command which fails with `Error: OCI runtime error: open /proc/sys/net/ipv4/ping_group_range: Read-only file system`:

```
podman run --rm -it \
    --security-opt=label=disable \
    --security-opt=seccomp=unconfined \
    --env STORAGE_DRIVER=vfs \
    --user=podman \
    quay.io/podman/stable:v3.4.4 \
        podman run --rm -it --network=none alpine
```

A workaround is editing `~/.config/containers/containers.conf` inside the container to not include `net.ipv4.ping_group_range`:

```
[containers]
volumes = [
	"/proc:/proc",
]
default_sysctls = []
```

**Describe the results you received:**

```
Error: OCI runtime error: open /proc/sys/net/ipv4/ping_group_range: Read-only file system
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 21:45:07 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

<details>
  <summary>podman info --debug</summary>
<code><pre>
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpus: 1
  distribution:
    distribution: fedora
    variant: container
    version: "35"
  eventLogger: file
  hostname: 0258298c13b6
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 10000
      size: 5000
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 10000
      size: 5000
  kernel: 5.15.17-200.fc35.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 543858688
  memTotal: 2061381632
  ociRuntime:
    name: crun
    package: crun-1.4.2-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.2
      commit: f6fbc8f840df1a414f31a60953ae514fa497c748
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /tmp/podman-run-1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 25m 43.5s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/podman/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/podman/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 1
  runRoot: /tmp/podman-run-1000/containers
  volumePath: /home/podman/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 1638999907
  BuiltTime: Wed Dec  8 21:45:07 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.4
</pre></code>
</details>

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.4-1.fc35.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?** 

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Rootless podman running inside a containerized environment without `/proc/sys/net/ipv4/ping_group_range`

This is mostly a duplicate of https://github.com/containers/podman/issues/8482, but for `--network=none` this time. 0d70df119539d818224b0d014602aaad2bd1b95e fixed this only for `--network=host`. Adding a check for network=none in [`specgen/generate/security.go`](https://github.com/containers/podman/blob/main/pkg/specgen/generate/security.go#L210-L212) may fix this?

/kind bug

**Comment by rhatdan** [comment]
I am not sure what you want Podman to fix here.   Are you looking at quay.io/podman/stable?

**Comment by bburky** [comment]
Basically the same as #8482, which updated podman to not sysctls when  rootless `--network=host` is set. Similarly, don't set sysctls when rootless `--network=none`.

**Comment by giuseppe** [comment]
I think it makes sense.  Opened a PR: https://github.com/containers/podman/pull/13250

**Comment by giuseppe** [comment]
since the fix was not accepted, should we close this issue?
