### ISSUE TITLE
--log-driver=journald --log-opt tag does not work with podman-conmon

### ISSUE THREAD

**Issue by asm0deuz** [containers/podman#13200]
From the podman RELEASE_NOTES.md

### Features
- Support for `--log-opt tag=` to set logging tags has been added to the `journald` log driver

podman version used is 3.4.4

This feature does not seem to work:

When I run:
#podman run --rm --log-driver=journald --log-opt tag="{{.ImageName}}/{{.Name}}/{{.ID}}" fedora echo "TEO was here"
                                                                               
Feb 10 15:51:12 localhost.localdomain systemd[1]: Started libpod-conmon-eff909743b4b2fee8e3cf6df5468e58986ee837013897b52a487c316983499b2.scope.                                                                                                         
Feb 10 15:51:12 localhost.localdomain systemd[1]: Started libcontainer container eff909743b4b2fee8e3cf6df5468e58986ee837013897b52a487c316983499b2.                                                                                                      
Feb 10 15:51:12 localhost.localdomain systemd[1]: Couldn't stat device /dev/char/10:200: No such file or directory                                                                                                                                      
**Feb 10 15:51:13 localhost.localdomain conmon[20419]: TEO is here**
Feb 10 15:51:13 localhost.localdomain systemd[1]: libpod-eff909743b4b2fee8e3cf6df5468e58986ee837013897b52a487c316983499b2.scope: Succeeded.       

I am expecting to have these tag on the conmon line.

Doing the same with docker:

Feb 10 14:50:03 localhost.localdomain kernel: IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
Feb 10 14:50:03 localhost.localdomain kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Feb 10 14:50:03 localhost.localdomain kernel: IPv6: ADDRCONF(NETDEV_CHANGE): vethbf4b7b1: link becomes ready
Feb 10 14:50:03 localhost.localdomain kernel: docker0: port 1(vethbf4b7b1) entered blocking state
Feb 10 14:50:03 localhost.localdomain kernel: docker0: port 1(vethbf4b7b1) entered forwarding state
Feb 10 14:50:03 localhost.localdomain NetworkManager[685]: <info>  [1644504603.8928] device (vethbf4b7b1): carrier: link connected
Feb 10 14:50:03 localhost.localdomain NetworkManager[685]: <info>  [1644504603.8956] device (docker0): carrier: link connected
**Feb 10 14:50:03 localhost.localdomain _fedora/nifty_hamilton/3c34ab694aa7_[1545]: TEO was here**
Feb 10 14:50:04 localhost.localdomain dockerd[1545]: time="2022-02-10T14:50:04.045823688Z" level=info msg="ignoring event" container=3c34ab694aa73620d61fe8ca16bbf552ae86473926832ff5b544b4624fe177e5 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Feb 10 14:50:04 localhost.localdomain containerd[1534]: time="2022-02-10T14:50:04.072723027Z" level=info msg="shim disconnected" id=3c34ab694aa73620d61fe8ca16bbf552ae86473926832ff5b544b4624fe177e5

I try to use this feature to split the log of multiple containers running on the same host. All logs are coming from conmon but you cannot determine from what container. Using tags would allow to filter on these tags

**Comment by asm0deuz** [comment]
@rhatdan Latest version is 3.4, where can I get podman 4? Thx

**Comment by mheon** [comment]
4.0 is still in Release Candidate phase, but we should be making a final release this week.

**Comment by asm0deuz** [comment]
Why did you close this issue?

**Comment by rhatdan** [comment]
Because, I thought it was stated that this works in Podman 4.0

**Comment by asm0deuz** [comment]
I didn't have the chance to test, this is why I was wondering where I could get Podman 4 rpms? Thx

**Comment by overshareware** [comment]
FWIW I am using Podman 4.1.1 and it doesn't seem to be working.

**Comment by Icephale** [comment]
Also using podman based on upstream version 3.4.4, on Ubuntu 22.04, I ran into this problem too.
I suspect this is related to mismatch between packaged versions of podman and conmon.
On Ubuntu 22.04, conmon is based on upstream 2.0.25 which seems not to alter SYSLOG_IDENTIFIER according to tag property.
Just tried with a naive patch to confirm this is not a problem with podman 3.4.4 as modifying conmon is enough to get logs with tag specified in command line.
```
Date: Tue, 25 Oct 2022 13:47:06 +0200
Subject: Backport logging

---
 src/ctr_logging.c | 27 +++++++++++++++++++--------
 1 file changed, 19 insertions(+), 8 deletions(-)

diff --git a/src/ctr_logging.c b/src/ctr_logging.c
index c3fd5d2..69d5ea3 100644
--- a/src/ctr_logging.c
+++ b/src/ctr_logging.c
@@ -44,6 +44,7 @@ static char *k8s_log_path = NULL;
 #define CID_EQ_LEN 13
 #define NAME_EQ_LEN 15
 #define PARTIAL_MESSAGE_EQ_LEN 30
+#define SYSLOG_IDENTIFIER_EQ_LEN 18
 static char short_cuuid[TRUNC_ID_LEN + 1];
 static char *cuuid = NULL;
 static char *name = NULL;
@@ -54,6 +55,8 @@ static char *container_id = NULL;
 static char *container_name = NULL;
 static char *container_tag = NULL;
 static size_t container_tag_len;
+static char *syslog_identifier = NULL;
+static size_t syslog_identifier_len;
 
 typedef struct {
        int iovcnt;
@@ -114,18 +117,23 @@ void configure_log_drivers(gchar **log_drivers, int64_t log_size_max_, char *cuu
                /* Setup some sd_journal_sendv arguments that won't change */
                container_id_full = g_strdup_printf("CONTAINER_ID_FULL=%s", cuuid);
                container_id = g_strdup_printf("CONTAINER_ID=%s", short_cuuid);
-               if (tag) {
-                       container_tag = g_strdup_printf("CONTAINER_TAG=%s", tag);
-                       container_tag_len = strlen(container_tag);
-               }
 
-               /* To maintain backwards compatibility with older versions of conmon, we need to skip setting
-                * the name value if it isn't present
-                */
+               /* Priority order of syslog_identifier (in order of precedence) is tag, name, `conmon`. */
+               syslog_identifier = g_strdup_printf("SYSLOG_IDENTIFIER=%s", short_cuuid);
+               syslog_identifier_len = TRUNC_ID_LEN + SYSLOG_IDENTIFIER_EQ_LEN;
                if (name) {
-                       /* save the length so we don't have to compute every sd_journal_* call */
                        name_len = strlen(name);
                        container_name = g_strdup_printf("CONTAINER_NAME=%s", name);
+
+                       syslog_identifier = g_strdup_printf("SYSLOG_IDENTIFIER=%s", name);
+                       syslog_identifier_len = name_len + SYSLOG_IDENTIFIER_EQ_LEN;
+               }
+               if (tag) {
+                       container_tag = g_strdup_printf("CONTAINER_TAG=%s", tag);
+                       container_tag_len = strlen(container_tag);
+
+                       syslog_identifier = g_strdup_printf("SYSLOG_IDENTIFIER=%s", tag);
+                       syslog_identifier_len = strlen(syslog_identifier);
                }
        }
 }
@@ -257,6 +265,9 @@ int write_journald(int pipe, char *buf, ssize_t buflen)
                if (name && writev_buffer_append_segment(dev_null, &bufv, container_name, name_len + NAME_EQ_LEN) < 0)
                        return -1;
 
+               if (writev_buffer_append_segment(dev_null, &bufv, syslog_identifier, syslog_identifier_len) < 0)
+                       return -1;
+
                /* per docker journald logging format, CONTAINER_PARTIAL_MESSAGE is set to true if it's partial, but otherwise not set. */
                if (partial && writev_buffer_append_segment(dev_null, &bufv, "CONTAINER_PARTIAL_MESSAGE=true", PARTIAL_MESSAGE_EQ_LEN) < 0)
                        return -1;
```

**Comment by jazoom** [comment]
I can confirm tags don't work with Debian stable's current versions of packages
