### ISSUE TITLE
Podman rmi very slow for both single image delete and for all image delete

### ISSUE THREAD

**Issue by vinusorout** [containers/podman#13204]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
podman rmi imageid -f, takes a lot of time to remove only one image and if we use podman rmi -a -f, takes hours to remove all the images

We run podman as rootless.

**Steps to reproduce the issue:**

Run podman rmi command for a single or all images.

**Describe the results you received:**
time podman rmi df123ccdd678 -f
Deleted: df123ccdd678f3ad5a34226f451d5651263c61605e77cad23cf7ff1d11129d5e

real    11m7.606s
user    0m2.140s
sys     0m7.720s

**Describe the results you expected:**
it should run faster.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.15.7
Built:        Thu Jul 29 10:02:43 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.21.3
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.module+el8.4.0+11822+6cc1e7d7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: ae467a0c8001179d4d0adf4ada381108a893d7ec'
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "8.4"
  eventLogger: file
  hostname: rhelmachine
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1813400513
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1813463994
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-305.19.1.el8_4.x86_64
  linkmode: dynamic
  memFree: 1713909760
  memTotal: 3917103104
  ociRuntime:
    name: runc
    package: runc-1.0.0-74.rc95.module+el8.4.0+11822+6cc1e7d7.x86_64
    path: /usr/bin/runc
    version: |-
      runc version spec: 1.0.2-dev
      go: go1.15.13
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/user/1813463994/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.4.0+11822+6cc1e7d7.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 8173907968
  swapTotal: 8485072896
  uptime: 246h 13m 42.27s (Approximately 10.25 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/service_account@abc.com/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.6-1.module+el8.4.0+11822+6cc1e7d7.x86_64
      Version: |-
        fusermount3 version: 3.2.1
        fuse-overlayfs: version 1.6
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/service_account@abc.com/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 34
  runRoot: /tmp/podman-run-1813463994/containers
  volumePath: /home/service_account@abc.com/.local/share/containers/storage/volumes
version:
  APIVersion: 3.2.3
  Built: 1627570963
  BuiltTime: Thu Jul 29 10:02:43 2021
  GitCommit: ""
  GoVersion: go1.15.7
  OsArch: linux/amd64
  Version: 3.2.3


```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.2.3-0.11.module+el8.4.0+12050+ef972f71.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

OS: Red Hat
Red Hat Enterprise Linux release 8.4 (Ootpa)

**Comment by vinusorout** [comment]
And when "podman rmi -af" is running, the "podman build" command waits for the "rmi" command to finish first. At least let me know how can I run "podman build" command parallel if the "podman rmi" command is in process?

**Comment by baude** [comment]
If you are reporting a bug on RHEL operating systems, please report them in the RH bugzilla system -> https://bugzilla.redhat.com/

There is clearly something wrong/different with your image storage.  Generally, rmi is impacted only by the number of images you have in your store and the size of those images.  For example, here is me deleting a 6.5GB image on my laptop:

```
time podman rmi quay.io/coreos-assembler/coreos-assembler
Untagged: quay.io/coreos-assembler/coreos-assembler:latest
Deleted: f6bcef5d1fe47d99fbf8dbb2fb170cacb44febd43e4ac10d7830e2c62f19c5a2

real	0m3.865s
```

Build and rmi cannot be run at the same time because rmi takes a lock on the image storage.  Perhaps this is what you are seeing.

There are other factors that can impact speed.  Obviously disk i/o speeds, networked directories, as well as specific storage options, and finally a corrupted image store.  If there is nothing important to you in terms of containers and images, I would first try a `podman system reset --force` which will blow away your image and container store.  Then try again.

If you feel there is an actual bug here, please file the bugzilla so it can be addressed properly.

**Comment by rhatdan** [comment]
Since we got no further feedback and this is not something upstream can easily fix, I am closing.
