### ISSUE TITLE
Prevent host.containers.internal entry inside container

### ISSUE THREAD

**Issue by vikas-goel** [containers/podman#13224]
/kind feature

**Description**

Podman adds host.containers.internal entry, that maps to the host’s IP address, in containers /etc/hosts file automatically. The containers are connected to macvlan networks. This entry is not desired and behavior is different from Docker.

How can it be prevented?

**Steps to reproduce the issue:**

1. Start a container with macvlan network.

2. Check /etc/hosts file inside container

**Describe the results you received:**

host.containers.internal mapped to host’s IP address

**Describe the results you expected:**

No such entry should be present

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Podman 4.0RC* mainline 

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

RHEL8.5

**Comment by Luap99** [comment]
Is there any specific reason why we should not add this? https://github.com/containers/podman/pull/12807 changed this so that we the correct host ip address instead of the macvlan gateway.

**Comment by vikas-goel** [comment]
What is the use-case of host.containers.internal inside containers with macvlan networks only?

The only concern is about exposing the host IP address inside the containers. My ask is to not add this entry altogether.

**Comment by Luap99** [comment]
host.container.internal is added for bridge and slirp4netns as well

**Comment by vikas-goel** [comment]
That makes sense for the two interface types. In case of macvlan, how I can avoid leaking the host IP to containers that works with Docker Compose?

**Comment by Luap99** [comment]
@vikas-goel Would a container.conf option work for you?

**Comment by vikas-goel** [comment]
Yes.
