### ISSUE TITLE
Permission denied when running "podman machine ssh" on macOS

### ISSUE THREAD

**Issue by djnotes** [containers/podman#13225]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug  

**Description**

When trying to run podman for the first time on Mac, I get denied permission to ssh into the VM. 

**Steps to reproduce the issue:**

1. Run podman machine init

2. Run podman machine start

3. Run podman machine ssh

**Describe the results you received:**
Got this error: 

```
me@MacBook ~ % podman machine ssh        
Connecting to vm podman-machine-default. To close connection, use `~.` or `exit`
Warning: Permanently added '[localhost]:49886' (ED25519) to the list of known hosts.
johndoe@localhost: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
Error: exit status 255
```

**Describe the results you expected:**
To show a shell for the default user in the vm.

**Additional information you deem important (e.g. issue happens only occasionally):**

I think Podman is making a mistake here. I had a user called johndoe on a remote system at 10.10.10.10:12345(ssh). It appears Podman is mistaking it with the user that it's creating for the VM, hence the permission error. 
**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: Connection to bastion host (ssh://johndoe@10.10.10.10:12345/run/user/1000/podman/podman.sock) failed.: ssh: handshake failed: read tcp 10.18.0.3:50267->10.10.10.10:12345: read: connection reset by peer 
```

**Package info (e.g. output of `brew info podman`):**

```
podman: stable 3.4.4 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/usr/local/Cellar/podman/3.4.4 (170 files, 40MB) *
  Poured from bottle on 2022-01-14 at 09:31:35
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0
==> Dependencies
Build: go ✘, go-md2man ✘
Required: qemu ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Analytics
install: 16,336 (30 days), 40,310 (90 days), 96,874 (365 days)
install-on-request: 16,333 (30 days), 40,310 (90 days), 96,863 (365 days)
build-error: 4 (30 days)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):** 

**OS**  
macOS Monterey (12.1)

**Comment by baude** [comment]
any chance you have more than a couple of ssh keys?

**Comment by djnotes** [comment]
Yes, I suppose I do. I have several ssh keys for connecting to different git repositories online for example, and they start with id_rsa_*. Can this cause problems?

    On Sunday, February 13, 2022, 10:46:31 AM PST, Brent Baude ***@***.***> wrote:  
 
 


any chance you have more than a couple of ssh keys?

**Comment by djnotes** [comment]
I was able to log into the VM by running:  
```
podman machine ssh podman-machine-default
```
podman-machine-default was the only vm I saw in the output for `podman machine list`.  I don't know what was happening previously.

**Comment by djnotes** [comment]
Just a question I'm wondering is, "how is port forwarding done inside the VM to macOS?" I imagine when inside the VM, host is the VM itself not macOS. So, how come using "--publish 8000:80" actually forwards port 80 from the container running inside the VM to the macOS operating system?

**Comment by baude** [comment]
gvproxy does this.

**Comment by rhatdan** [comment]
Is this fixed now?  Can we close this issue?

**Comment by djnotes** [comment]
Yes, my problem is fixed. I left the issue open in case you want to add something on why this happens or how this can be prevented.

**Comment by ashley-cui** [comment]
Closing, looks like this has been resolved.
