### ISSUE TITLE
unrecognized command `podman network exists`

### ISSUE THREAD

**Issue by extsalt** [containers/podman#13248]
`podman machine` command does not exists
`podman network exists` command does not exists

**Comment by vrothberg** [comment]
Please fill out the data as requested in the issue template.

Without further data, we don't know on which system and in which environment you try to run which version of Podman.

I suggest to open a new issue.

**Comment by rhatdan** [comment]
Also some of these commands do not exists on older versions of podman and on podman-remote Which is the version on MAC and Windows.
