### ISSUE TITLE
Issue with podman machine init and option --volume on macOS (virtfs support is disabled, says qemu)

### ISSUE THREAD

**Issue by fc7** [containers/podman#13256]
/kind bug

(4.0.0-dev version)

**Description**

I tested the current 4.0.0-dev version on a Mac using `brew install --head podman` (after unlinking the 3.4.4 version).
My objective was to try the [forthcoming feature with the option `--volume`](https://docs.podman.io/en/latest/markdown/podman-machine-init.1.html#volume-v-source-target). Unfortunately in so doing I encountered the following error:

```
% podman machine start experimental                            
Starting machine "experimental"
INFO[0000] waiting for clients...                       
INFO[0000] new connection from  to /var/folders/6x/0bjf97xs2210ll8zxggh1v040000gn/T/podman/qemu_experimental.sock 
Waiting for VM ...
qemu-system-x86_64: -virtfs local,path=/Users/fch,mount_tag=vol0,security_model=mapped-xattr: There is no option group 'virtfs'
qemu-system-x86_64: -virtfs local,path=/Users/fch,mount_tag=vol0,security_model=mapped-xattr: virtfs support is disabled
Error: dial unix /var/folders/6x/0bjf97xs2210ll8zxggh1v040000gn/T/podman/experimental_ready.sock: connect: no such file or directory
ERRO[0003] cannot receive packets from , disconnecting: cannot read size from socket: EOF 
ERRO[0003] cannot read size from socket: EOF 
```

Question: how can I enable **virtfs** support in qemu? I have the latest stable version of qemu installed via `brew`:

```
% brew info qemu  
qemu: stable 6.2.0 (bottled), HEAD
```

Or is there maybe another supported driver than virtfs for macOS that can be passed to `--volume-driver`?

**Steps to reproduce the issue:**

1. Install dev version of podman on macOS with `brew install --head podman`
2. Run `podman machine init experimental --volume /Users/foo:/mnt/foo`
3. Run `podman machine start experimental`

**Output of `podman version`:**

```
podman version 4.0.0-dev
```

**Output of `podman info --debug`:**

Cannot be executed due to above issue. However  when creating and starting a different machine without the `--volume` option, I get this error (though this might be unrelated to the above and can be ignored for the moment):

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: Connection to bastion host (ssh://core@localhost:63038/run/user/1000/podman/podman.sock) failed.: dial tcp [::1]:63038: connect: connection refused
```

Any help appreciated on this!

**Comment by afbjorklund** [comment]
See #8016

**Comment by afbjorklund** [comment]
> Or is there maybe another supported driver than virtfs for macOS that can be passed to `--volume-driver`?

There are no other drivers at the moment. I _planned_ on doing one for [sshocker](https://github.com/lima-vm/sshocker), but it was better to run as a command.

Theoretically one could add drivers for NFS and for SMB, but I don't think anyone has volunteered to do it yet.

Eventually we are hoping for a [virtio-fs](https://virtio-fs.gitlab.io/) driver for darwin (using vsock), but that could be well in the future (no time plan).

**Comment by fc7** [comment]
Thanks a lot @afbjorklund that looks promising. I will try that formula and report back.

**Comment by afbjorklund** [comment]
I tested it myself with qemu v6.0.0, but haven't seen any feedback with v6.2.0 so far

**Comment by fc7** [comment]
@afbjorklund I get this issue with your patch when installing your formula for qemu with virtfs (build-from-source):
```
patching file hw/9pfs/9p-util-darwin.c
can't find file to patch at input line 818
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/hw/9pfs/9p-util-linux.c b/hw/9pfs/9p-util-linux.c
|index defa3a413075..3902378e627c 100644
|--- a/hw/9pfs/9p-util-linux.c
|+++ b/hw/9pfs/9p-util-linux.c
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
patching file hw/9pfs/9p-util.h
patching file hw/9pfs/9p.c
Hunk #1 succeeded at 27 (offset 5 lines).
patching file hw/9pfs/9p-local.c
Hunk #1 succeeded at 673 (offset 5 lines).
Hunk #2 succeeded at 688 (offset 5 lines).
Hunk #3 succeeded at 701 (offset 5 lines).
patching file hw/9pfs/9p-util-darwin.c
can't find file to patch at input line 960
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/hw/9pfs/9p-util-linux.c b/hw/9pfs/9p-util-linux.c
|index 3902378e627c..06399c59199c 100644
|--- a/hw/9pfs/9p-util-linux.c
|+++ b/hw/9pfs/9p-util-linux.c
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
```
I did not have the time to investigate in details but at first sight the files to patch should be present in the upstream branch: https://gitlab.com/wwcohen/qemu/-/tree/9p-darwin/hw/9pfs but there were some commits a week ago, so could it be that the patch is no longer compatible? Should I try to use the upstream branch on gitlab without your patch?

**Comment by afbjorklund** [comment]
Hmm, I thought I tested it (on Linux, but anyway). There is a v6.0.0 version in the same place that might work better ?

And yes, using the upstream version for 7.0 is better. There is a more official backport to 6.2.0 coming, as well... Thanks!

**Comment by afbjorklund** [comment]
@fc7 : I found the problem, I was using ".patch" in the link to generate the patch when I should have used ".diff".

Otherwise github was trying to recreate some kind of commit, and failed to include the merge conflict resolution...

So the real patches are:

https://github.com/qemu/qemu/compare/v6.0.0...afbjorklund:9p-darwin-v6.0.0.diff
`d13866db35ffff738f4e9e06c89f7c4737b1b5a62b613447927104c1b25fe646  v6.0.0...afbjorklund:9p-darwin-v6.0.0.diff`

https://github.com/qemu/qemu/compare/v6.2.0...afbjorklund:9p-darwin-v6.2.0.diff
`de2d99711e46036c35f569995ef12cb5e6e0046cdda10d67817eea6d4389a68f  v6.2.0...afbjorklund:9p-darwin-v6.2.0.diff`

```
patching file fsdev/file-op-9p.h
patching file fsdev/meson.build
patching file hw/9pfs/9p-local.c
patching file hw/9pfs/9p-proxy.c
patching file hw/9pfs/9p-synth.c
patching file hw/9pfs/9p-util-darwin.c
patching file hw/9pfs/9p-util-linux.c (renamed from hw/9pfs/9p-util.c)
patching file hw/9pfs/9p-util.h
patching file hw/9pfs/9p.c
patching file hw/9pfs/codir.c
patching file hw/9pfs/meson.build
patching file include/qemu/statfs.h
patching file include/qemu/xattr.h
patching file meson.build

```

**Comment by fc7** [comment]
Oh thanks! I am building from git right now using branch v6.2.0-9p-darwin (`brew install --head <your-formula-without-the-patch>` ... let's see how it goes. I'll keep your diffs as a fallback.

**Comment by afbjorklund** [comment]
Any misapplies are all mine, I just copied from git-branches-on-gitlab and patches-on-mailing-list over to regular github...

**Comment by willcohen** [comment]
Latest branch is here: https://gitlab.com/wwcohen/qemu/-/commits/v6.2.0-9p-darwin
Still running the build. If it works okay I'll get it over to a github repo so that you can generate the patch with one URL

**Comment by afbjorklund** [comment]
Thanks! I changed my brew formula to use your backport branch, `v6.2.0-9p-darwin`.

https://github.com/qemu/qemu/compare/v6.2.0...willcohen:0024dfc24f88410fe9d85ef8e4a27cbc7283b87a

**Comment by fc7** [comment]
Thansk @willcohen ! I was successful in building your branch v6.2.0-9p-darwin this morning, using a modifed brew formula (without any patch). (I had a compile error yesterday regarding an undeclared symbol but after a new pull this morning it went away, which is consistent with your comment above). 
Same experience as @afbjorklund regarding build time (worse actually, as I am on an older Intel Macbook).

**Comment by fc7** [comment]
I forgot the most important: with podman 4.0.0-dev (also rebuilt this morning) the --volume option works like a charm. But before closing this, I should point out that the [podman documentation](https://docs.podman.io/en/latest/) is only describing the latest unreleased version, which can be confusing to many people, as more and more users are migrating from Docker to podman (at least this is the case in my company). It would be good to be able to switch the documentation from "latest" to the current stable version (3.x). At least it had the nice side-effect of my discovering the new `--volume` option, hence my attempt to use it and the above report. Thanks again for your help!

**Comment by afbjorklund** [comment]
The confusing documentation is a known issue:

* https://github.com/containers/podman.io/issues/485

**Comment by afbjorklund** [comment]
Too bad that the volumes couldn't be added to 3.5 along with the docker fixes, but I guess there wasn't enough interest back then when Docker was still free

**Comment by afbjorklund** [comment]
Found the issue with the patch, it wasn't renaming the file - which was an issue on darwin, but not on linux.

Fixed: https://github.com/afbjorklund/homebrew-core/blob/qemu-9p-darwin/Formula/qemu.rb

```
🍺  /opt/homebrew/Cellar/qemu/6.2.0: 162 files, 556.8MB, built in 4 minutes 35 seconds
```

**Comment by willcohen** [comment]
Is this something I need to correct for v9?

**Comment by afbjorklund** [comment]
> Is this something I need to correct for v9?

It was just how git creates patches, you need to use `git am` to apply them - simple GNU `patch` is not smart enough:

```
 fsdev/file-op-9p.h                     |  9 ++++++++-
 fsdev/meson.build                      |  1 +
 hw/9pfs/9p-local.c                     | 27 +++++++++++++++++++++------
 hw/9pfs/9p-proxy.c                     | 38 +++++++++++++++++++++++++++++++++++---
 hw/9pfs/9p-synth.c                     |  6 ++++++
 hw/9pfs/9p-util-darwin.c               | 64 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 hw/9pfs/{9p-util.c => 9p-util-linux.c} |  2 +-
 hw/9pfs/9p-util.h                      | 35 +++++++++++++++++++++++++++++++++++
 hw/9pfs/9p.c                           | 42 ++++++++++++++++++++++++++++++++++++------
 hw/9pfs/9p.h                           | 18 ++++++++++++++++++
 hw/9pfs/codir.c                        |  4 +++-
 hw/9pfs/meson.build                    |  3 ++-
 include/qemu/osdep.h                   | 12 ++++++++++++
 include/qemu/xattr.h                   |  4 +++-
 meson.build                            | 15 +++++++++++----
 os-posix.c                             | 35 +++++++++++++++++++++++++++++++++++
 tests/qtest/virtio-9p-test.c           |  2 +-
 17 files changed, 292 insertions(+), 25 deletions(-)
```

```
==> Patching
==> Applying v6.2.0...willcohen:0024dfc24f88410fe9d85ef8e4a27cbc7283b87a.patch
patching file fsdev/file-op-9p.h
patching file hw/9pfs/9p-local.c
patching file hw/9pfs/9p.c
patching file include/qemu/xattr.h
patching file hw/9pfs/9p-util.c
patching file hw/9pfs/meson.build
patching file hw/9pfs/9p-proxy.c
patching file hw/9pfs/9p-synth.c
patching file hw/9pfs/9p.c
patching file hw/9pfs/9p-local.c
patching file hw/9pfs/9p-proxy.c
patching file hw/9pfs/9p-synth.c
patching file hw/9pfs/9p-util.h
patching file hw/9pfs/9p.c
patching file hw/9pfs/codir.c
patching file hw/9pfs/9p-util.h
patching file hw/9pfs/9p.c
patching file hw/9pfs/9p.c
patching file hw/9pfs/9p.h
patching file hw/9pfs/9p-util-darwin.c
patching file hw/9pfs/meson.build
patching file hw/9pfs/9p-local.c
patching file hw/9pfs/9p-util.h
patching file hw/9pfs/9p-local.c
patching file include/qemu/osdep.h
patching file meson.build
patching file os-posix.c
patching file tests/qtest/virtio-9p-test.c
patching file fsdev/meson.build
patching file meson.build

```

**Comment by afbjorklund** [comment]
Did get a build error with the latest version, not sure if I need to update something ?

```
Last 15 lines from /Users/m1/Library/Logs/Homebrew/qemu/02.make:
        return -ENOTSUPP;
                ^
1 error generated.
```

**Comment by willcohen** [comment]
Oh — quick first question. What version of macOS are you on?

**Comment by afbjorklund** [comment]
```console
% sw_vers 
ProductName:	macOS
ProductVersion:	12.2.1
BuildVersion:	21D62
```

**Comment by willcohen** [comment]
Does it work if you replace it with `-EOPNOTSUPP` rather than `-ENOTSUPP`? I suspect that upstream will still want an error message rather than -1.

**Comment by willcohen** [comment]
Ah. It's a typo on master versus a patch version. It is supposed to be `-ENOTSUP`! Will fix when I submit v9.

**Comment by baude** [comment]
@willcohen was test driving the  patch today ... can qemu do anything for us to help with the difference on uid/guid between the mac and the linux vm where the mount is made.

**Comment by willcohen** [comment]
I’ve seen this mentioned a few places but haven’t fully wrapped my head around it. To my knowledge the uid is just passed through directly. Is the idea here that qemu could reassign the number en route so it looks like one thing on the host and one thing on the guest? Is it always going to be predicable on the coreos side, so that hypothetically it’d be something we’d want to see invoked on the command line when starting up qemu?

**Comment by baude** [comment]
I believe it would be predictable but it is always nice to allow it to be made by entry.

**Comment by willcohen** [comment]
For existing qemu functionality, the closest thing I can find in https://wiki.qemu.org/Documentation/9psetup is to use `-o access=<uid>` when running mount on the Linux side. At first glance that seems like it should work, rather than relying on the uid being passed through from QEMU. I assume that that basically just ignores the macOS attributes being passed through. Has this been tried?

I submitted `v9` today and hopefully there’s no more changes to it. If we need to sneak other flag into 9p on the qemu side we’ve got a week or two to put together another patch set before soft freeze!

**Comment by baude** [comment]
@willcohen would you mind providing a link to your v9  submission?

**Comment by willcohen** [comment]
Yep!

https://github.com/containers/podman/issues/8016#issuecomment-1053746217

https://lists.gnu.org/archive/html/qemu-devel/2022-02/msg05978.html

**Comment by afbjorklund** [comment]
I tested both the 6.2.0 version and the 7.0.0 (well, "to be") and besides the file rename in the patch and the typo they worked fine.

Fixing the qemu formula to cope with these changes was not so hard either, and after that it worked just like the linux version ?

```ruby
    system "mv hw/9pfs/9p-util.c hw/9pfs/9p-util-linux.c" unless build.head?
    inreplace "os-posix.c", "-ENOTSUPP", "-ENOTSUP" if build.head?
```

I don't think there should be any more unrelated changes done to it, mapping uid and gid sounds like a separate new feature ?

It seemed perfectly predictable, the files were owned by nobody (or 501) in the VM and had nice xattr attached on the host:


```console
% touch /tmp/podman/foo
% podman run -it -v /mnt/host:/mnt busybox touch /mnt/bar
 
% ls -l@ /tmp/podman/
total 0
-rw-------@ 1 m1  wheel  0 27 Feb 18:30 bar
        user.virtfs.gid 4
        user.virtfs.mode        2
        user.virtfs.uid 4
-rw-r--r--  1 m1  wheel  0 27 Feb 18:30 foo

```

**Comment by willcohen** [comment]
Okay. I’ll try to look a little more into this.

For what it’s worth, with the v9 patch the ENOTSUP typo shouldn’t be an issue anymore and I think you can remove it from the formula. The typo was in my older version of the branch on top of master, not in upstream HEAD itself.

**Comment by afbjorklund** [comment]
Sorry, which error ?

**Comment by willcohen** [comment]
The `CONFIG_LINUX` issue which prevents you from building without moving `9p-util.c` to `9p-util-linux`. It seems like there may be some other issue where QEMU is incorrectly setting `CONFIG_LINUX` on Mac with nix and brew, but I can't quite pin down what it is, and perhaps it was never relevant until this feature. Similarly, my WIP pr for nix has to [remove the file from meson too](https://github.com/NixOS/nixpkgs/pull/162243/files#diff-f885f3c7293fd60915aa7c2d28eea89dea548af3d732700fa1224b0cafa55a0aR131-R137).

**Comment by afbjorklund** [comment]
Right, normally it would build from a release tarball

**Comment by afbjorklund** [comment]
@willcohen : it doesn't matter what the value is, the meson.build won't "compile" if the file is missing.

```
../hw/9pfs/meson.build:16:6: ERROR: File 9p-util-linux.c does not exist.
```

`fs_ss.add(when: 'CONFIG_LINUXXX', if_true: files('9p-util-linux.c'))`

**Comment by willcohen** [comment]
Got it -- then I'll tentatively assume that this is a backport-only issue affecting only those applying these generated patches, and it won't be an issue after 6.2.
