### ISSUE TITLE
podman pod logs enhancements: option to display names

### ISSUE THREAD

**Issue by muayyad-alsadi** [containers/podman#13261]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

the ability for `podman pod logs -f` to 

* an option to display names instead of ids
* color different containers
* follow new containers started after log started
* do not exit if pod is empty (as long as pod is up, should not exit)

**Steps to reproduce the issue:**

```
podman pod create --name=pod_testlogs 
podman run --name=testlogs_loop1_1 -d --pod=pod_testlogs busybox /bin/sh -c 'for i in `seq 1 10000`; do echo "loop1: $i"; sleep 1; done'
podman run --name=testlogs_loop2_1 -d --pod=pod_testlogs busybox /bin/sh -c 'for i in `seq 1 10000`; do echo "loop2: $i"; sleep 3; done'
podman pod logs --tail=100 -f pod_testlogs
```

and then on another screen

```
podman run --name=testlogs_loop3_1 -d --pod=pod_testlogs busybox /bin/sh -c 'for i in `seq 1 10000`; do echo "loop3: $i"; sleep 3; done'
```

**Describe the results you received:**

* ids instead of names
* logs for `loop3` is not followed
* exit instantly when running `podman pod logs --tail=100 -f pod_testlogs` after `podman pod create --name=pod_testlogs`

**Describe the results you expected:**

* away to display names and preferably colors
* logs for `loop3` should be followed
* should not exit instantly when running `podman pod logs --tail=100 -f pod_testlogs` after `podman pod create --name=pod_testlogs`

**Comment by rhatdan** [comment]
Seems reasonable to me, although breaking these into multiple RFEs might make it easier to consume and deliver.
I think podman logs --names ...

Should be fairly easy to add.

**Comment by muayyad-alsadi** [comment]
>  multiple RFEs

thank you, I've just did that.

**Comment by keonchennl** [comment]
May I work on this?

**Comment by rhatdan** [comment]
Yes @keonchennl I assigned it to you.
