### ISSUE TITLE
podman pod logs enhancements: option to color logs

### ISSUE THREAD

**Issue by muayyad-alsadi** [containers/podman#13266]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

an option for "podman pod logs" to color output of each container in different colors when in TTY

**Steps to reproduce the issue:**

```
podman pod create --name=pod_testlogs 
podman run --name=testlogs_loop1_1 -d --pod=pod_testlogs busybox /bin/sh -c 'for i in `seq 1 10000`; do echo "loop1: $i"; sleep 1; done'
podman run --name=testlogs_loop2_1 -d --pod=pod_testlogs busybox /bin/sh -c 'for i in `seq 1 10000`; do echo "loop2: $i"; sleep 3; done'
podman pod logs --tail=100 -f pod_testlogs
```

and then on another screen

```
podman run --name=testlogs_loop3_1 -d --pod=pod_testlogs busybox /bin/sh -c 'for i in `seq 1 10000`; do echo "loop3: $i"; sleep 3; done'
```

**Describe the results you received:**

* no colors

**Describe the results you expected:**

* loop1 different color than loop2

related issue

https://github.com/containers/podman/issues/13261

**Comment by TomSweeneyRedHat** [comment]
Setting this issue aside for Krzysztof Baran and fellow students.  Please contact @TomSweeneyRedHat if you have questions.

**Comment by TomSweeneyRedHat** [comment]
@kbaran1998 Welcome!  In case you're looking for Brent Baude on GitHub, he's at @bbaude.  I also tried to assign to @gcalin, but GitHub wouldn't let me.  I think he needs to make a comment or similar action in the project before I can assign stuff to him.

**Comment by gcalin** [comment]
Hello @TomSweeneyRedHat, leaving a comment to get assigned. We'll start working on this feature this week.

**Comment by kbaran1998** [comment]
Created a [PR](https://github.com/containers/podman/pull/13490) for this issue.
