### ISSUE TITLE
Container hostname inconsistent between being assigned to a pod and not

### ISSUE THREAD

**Issue by lovette** [containers/podman#13275]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I've only recently begun working with podman so I don't know if this is a bug, feature or desired function, but I notice the `hostname` is inconsistent between when containers are assigned to a pod and when they're not.

When in a pod, hostname is set to the pod's `--name` but for non-pod containers `hostname` is set to the container's *short ID*.

Of course, this can be remidied by using the `--hostname` option.

**Steps to reproduce the issue:**

	$ sudo podman run -it --rm --name mycontainer ubi8 sh -c 'echo "$HOSTNAME"'
	b8c9b42fa6f9

	$ sudo podman pod create --name mypod
	$ sudo podman run -it --rm --name mycontainer --pod mypod ubi8 sh -c 'echo "$HOSTNAME"'
	mypod

	$ sudo podman run -it --rm --name mycontainer --hostname mycontainer ubi8 sh -c 'echo "$HOSTNAME"'
	mycontainer

**Describe the results you received:**

	$ sudo podman run -it --rm --name mycontainer ubi8 sh -c 'echo "$HOSTNAME"'
	b8c9b42fa6f9

**Describe the results you expected:**

	$ sudo podman run -it --rm --name mycontainer ubi8 sh -c 'echo "$HOSTNAME"'
	mycontainer

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.0-rc5
API Version:  4.0.0-rc5
Go Version:   go1.17.5

Built:      Sat Feb 12 01:12:41 2022
OS/Arch:    linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
	package: conmon-2.1.0-1.el9.x86_64
	path: /usr/bin/conmon
	version: 'conmon version 2.1.0, commit: 8ef5de138efb6f0aad657082cdea22cf037792cb'
  cpus: 2
  distribution:
	distribution: '"centos"'
	version: "9"
  eventLogger: journald
  hostname: dd-grogu-dev
  idMappings:
	gidmap: null
	uidmap: null
kernel: 5.14.0-47.el9.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 2074648576
  memTotal: 4073611264
  networkBackend: netavark
  ociRuntime:
	name: crun
	package: crun-1.4.2-1.el9.x86_64
	path: /usr/bin/crun
	version: |-
	  crun version 1.4.2
	  commit: f6fbc8f840df1a414f31a60953ae514fa497c748
	  spec: 1.0.0
	  +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
	exists: true
	path: /run/podman/podman.sock
  security:
	apparmorEnabled: false
	capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
	rootless: false
	seccompEnabled: true
	seccompProfilePath: /usr/share/containers/seccomp.json
	selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
	executable: /bin/slirp4netns
	package: slirp4netns-1.1.8-3.el9.x86_64
	version: |-
	  slirp4netns version 1.1.8
	  commit: d361001f495417b880f20329121e3aa431a8f90f
	  libslirp: 4.4.0
	  SLIRP_CONFIG_VERSION_MAX: 3
	  libseccomp: 2.5.2
  swapFree: 2146430976
  swapTotal: 2147479552
  uptime: 50h 19m 42.78s (Approximately 2.08 days)
plugins:
log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
	number: 15
	paused: 0
	running: 15
	stopped: 0
  graphDriverName: overlay
  graphOptions:
	overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
	Backing Filesystem: xfs
	Native Overlay Diff: "false"
	Supports d_type: "true"
	Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
	number: 24
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.0-rc5
  Built: 1644628361
  BuiltTime: Sat Feb 12 01:12:41 2022
  GitCommit: ""
  GoVersion: go1.17.5
  OsArch: linux/amd64
  Version: 4.0.0-rc5
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.0.0-0.7.rc5.el9.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on CentOS 9 Stream in a VMware Fusion VM.

**Comment by lovette** [comment]
Yeah, the hostname for pods makes sense to me. For non-pod containers, why not default the hostname to its --name if it's defined? Just curious.

**Comment by baude** [comment]
the difference here is about the term 'hostname'.  If i launch a container like so:

`$ sudo podman run -dt --network podman2 --name aone --network-alias=a1 alpine top`

A dns record is created for that containers, where aone is the hostname, and the short container id as well as a1 are name aliases.   So another container could resolve that container with aone, a1, or 1721bfd872

You are referring to the hostname as displayed on the command line of the container.  I think the short container id is basically the standard there.

**Comment by lovette** [comment]
Yeah, I am referring to $HOSTNAME inside the container. It's one thing inside a pod container and something different in a standalone container. I have no issue with that, just wanted to get clarification that it was intentional 😁

**Comment by rhatdan** [comment]
I think it is unintentional and/or might be based on Docker.

$ podman run --name test1 alpine printenv HOSTNAME
bf243f68d1d5
Should be
$ podman run --name test1 alpine printenv HOSTNAME
test1

**Comment by rhatdan** [comment]
Because Docker standardized on setting the hostname based on the container name when creating the containers, I think we can stick with this standard.  Podman creating pods based on the name is also our standard, and we use hostname, which I think is a better long term solution, so I don't believe there is anything to change here.
