### ISSUE TITLE
Prevent automatic image building in kube play

### ISSUE THREAD

**Issue by Korijn** [containers/podman#13285]
/kind feature

**Description**

In #11180 support was added to build images automatically in `podman play kube`.

However, this is undesirable if your images cannot be built without additional custom commands such as build secrets/arguments.

Our project's repository structure just happens to be organized according to the structure described the command's reference:

```
If there is a directory named foobar in the current working directory with a file
named Containerfile or Dockerfile, Podman play kube will build that image and name it foobar. 
```

So, if no prebuilt image is available, and can be pulled, podman still decides to try and build, and of course fail.

The only workaround is to manually pull the individual images beforehand, or build them manually. Annoying and time consuming!

This is on `podman version 3.4.2`.

I see a couple of options:

* Instead of building automatically, add a flag `--build-missing` to opt-in
* Add a flag to opt-out of automatic building `--no-build`

**Comment by Luap99** [comment]
I think you can use `--build=false` already

**Comment by Luap99** [comment]
All bool flags can be used with `=true|false`
Looking at the code the default is already false so there is something wrong here if it builds without setting --build.

**Comment by Korijn** [comment]
(I haven't found time to try yet)

Well, in `pkg/domain/infra/abi/play.go` the following `if` statement is used:

`if (len(buildFile) > 0 && !existsLocally) || (len(buildFile) > 0 && options.Build) {`

That doesn't seem to really honor the `--build=false` case.

**Comment by flouthoc** [comment]
@Korijn I think above PR should close this. I think `--build` was meant to be `true` by default according to `docs` here https://github.com/containers/podman/blob/main/docs/source/markdown/podman-play-kube.1.md but I agree it should honor `false` value.

**Comment by Korijn** [comment]
Sure, thanks !
