### ISSUE TITLE
build podman image behind a proxy 

### ISSUE THREAD

**Issue by medas19** [containers/podman#13292]
/kind bug
build container fail behind a proxy 
/kind feature

**Description**

**Steps to reproduce the issue:**

1.[asmiiadm@pod-as101-dev ~]$ sudo podman build -t app . --http-proxy

2.

3.

**Describe the results you received:**

STEP 1: FROM registry.access.redhat.com/ubi8
STEP 2: RUN yum update -y
Updating Subscription Management repositories.
Unable to read consumer identity
Subscription Manager is operating in container mode.
Editis_Tools_RHEL8                               75 kB/s |  23 kB     00:00
Red Hat Enterprise Linux 8 for x86_64 - AppStre  38 MB/s |  38 MB     00:00
Red Hat Enterprise Linux 8 for x86_64 - BaseOS   37 MB/s |  43 MB     00:01
Red Hat Universal Base Image 8 (RPMs) - BaseOS  0.0  B/s |   0  B     01:30
Errors during downloading metadata for repository 'ubi-8-baseos':
  - Curl error (7): Couldn't connect to server for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/baseos/os/repodata/repomd.xml [Failed to connect to cdn-ubi.redhat.com port 443: Connection timed out]
Error: Failed to download metadata for repo 'ubi-8-baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Error: error building at STEP "RUN yum update -y": error while running runtime: exit status 1
[asmiiadm@pod-as101-dev ~]$

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rbagd** [comment]
Maybe ubi-8 repos are not allowed by the proxy?  Is the issue solved if you prepend this to your Dockerfile?

```
RUN dnf config-manager --set-disabled ubi-8-appstream && \
    dnf config-manager --set-disabled ubi-8-baseos && \
    dnf config-manager --set-disabled ubi-8-codeready-builder
```

**Comment by vrothberg** [comment]
Closing as there was no further feedback. We can reopen if needed.
