### ISSUE TITLE
Defining image metadata during import

### ISSUE THREAD

**Issue by jpalus** [containers/podman#13291]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

`podman build` allows defining various information about the image like `--os`, `--arch`, `--variant` (or single `--platform`). It would be nice if these options were available during `podman import` as well

**Comment by rhatdan** [comment]
Please expand what you mean.  Currently these fields are not set on import?  So you would want to be able to set them?
A tar ball would be for a particular OS/Arch/Variant, and we have no way to verify that these fields would be correct.

**Comment by rhatdan** [comment]
With Build we can control the image that we are building to match the OS/ARCH/Var.

**Comment by flouthoc** [comment]
I think following might is useful for cases when user is already aware about the tar which is being imported, above PR closes this issues: https://github.com/containers/podman/pull/13588
