### ISSUE TITLE
Release v4.0.0 packages on Kubic PPA for Ubuntu?

### ISSUE THREAD

**Issue by Korijn** [containers/podman#13302]
The v4.0.0 release landed, but it is not available yet via the Kubic project PPA for Ubuntu. Is there a trigger that was missed somewhere, or something needs to be done to move this forward?

**Comment by vrothberg** [comment]
@lsm5 PTAL

**Comment by Korijn** [comment]
Can you at least indicate what the new preferred method of installation will be for up-to-date podman releases on Ubuntu?

**Comment by benridley** [comment]
@Korijn I've created a repo/CI pipeline for building the latest versions of podman, conmon, runc and cni-plugins as .deb packages. You can find them here: https://gitlab.com/benridley/podman-deb/-/packages.

Just note they are mostly for my own use, so no guarantees about the quality of the packages etc. If you have any issues with them let me know, I've tested then with Debian bullseye successfully.

**Comment by afbjorklund** [comment]
It looks like Ubuntu 22.04 LTS will ship with Podman 3.4, just like Ubuntu 21.04 provided Podman 3.0.

**Comment by Korijn** [comment]
I'll see how much effort it is to maintain a PPA of my own and post back here later.

**Comment by heyakyra** [comment]
> Hi all, I've setup a repository that contains deb packages at https://repo.bridsy.xyz. The distribution is 'bullseye' because I built and tested it on Debian 11, but I expect it would work on Ubuntu and if people are interested I'll publish specific packages for it.

Doesn't seem to work on the latest 22.04 LTS

```
$ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  podman
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/36.4 MB of archives.
After this operation, 38.1 MB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 100240 files and directories currently installed.)
Preparing to unpack .../podman_4.0.3-1_amd64.deb ...
Unpacking podman (4.0.3-1) over (3.4.4+ds1-1ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/podman_4.0.3-1_amd64.deb (--unpack):
 trying to overwrite '/etc/containers/policy.json', which is also in package golang-github-containers-common 0.44.4+ds1-1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Could not execute systemctl:  at /usr/bin/deb-systemd-invoke line 142.
Errors were encountered while processing:
 /var/cache/apt/archives/podman_4.0.3-1_amd64.deb
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by lsm5** [comment]
@heyakyra looks like a conflict with golang-github-containers-common. Might need to remove that package and retry installation.

@benridley is your repo at a point where we could list this in the official podman installation docs? Also, are you looking for people to help you out with packaging, any other support for this repo?

**Comment by liebig** [comment]
I have created [my own fork](https://github.com/liebig/podman) and have the Linux AMD64 binaries (releases and nightly builds) built here automatically:

* [Nightly Builds](https://github.com/liebig/podman/actions/workflows/build_linux_nightly.yml)
* [Latest Version: 4.1.0](https://github.com/liebig/podman/releases/tag/v4.1.0-release)
* [Version: 4.0.3](https://github.com/liebig/podman/releases/tag/v4.0.3-release)
* [Version: 3.4.7](https://github.com/liebig/podman/releases/tag/v3.4.7-release)

**Comment by arogozhnikov** [comment]
@liebig thank you for making builds.
I believe those will work for ubuntu22, but not ubuntu 20.04. At least that's what I get:
```
~/podman-v4.1.0/usr/bin$ ./podman
./podman: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./podman)
./podman: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./podman)
./podman: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./podman)
```

Ubuntu 20.04 indeed stops at glibc 2.31

**Comment by rishubn** [comment]
@liebig Thanks for your efforts!

Any possibility to add ARM architectures to your builds?

**Comment by liebig** [comment]
@rishubn 
Good idea, I must take a look if this is easy to implement. Currently, I unfortunately do not have much time, but I have created an issue for tracking. Thanks for your feedback.
