### ISSUE TITLE
brew install results in error due to missing dependency

### ISSUE THREAD

**Issue by dav009** [containers/podman#13300]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

doing `brew install podman`

results in the error below:

```
Error: qemu-virgl: Failed to download resource "qemu-virgl--test-image"
Download failed: https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/FD12FLOPPY.zip
```
This is because the given url returns 404

**Steps to reproduce the issue:**

1. `brew install podman`

2. installation does not complete

3.

**Describe the results you received:**

404 on a dependency:
Download failed: https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.2/FD12FLOPPY.zip

**Describe the results you expected:**

podman to be installed in my system

**Comment by vrothberg** [comment]
@ashley-cui PTAL

**Comment by Luap99** [comment]
@dav009 Does your linked PR already fixes the issue?
We do not control brew packaging directly so it is best to report bugs against brew and not here.

**Comment by dav009** [comment]
@Luap99  @vrothberg  yes mentioned PR solved the issue for me. not sure if it takes place after homebrew does a release tho.
