### ISSUE TITLE
[Windows] v4.0.0 env variable set to x86 instead x64

### ISSUE THREAD

**Issue by nunix** [containers/podman#13303]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

After installing `podman.msi`, the path for `podman.exe` in the Environment Variables is set to `C:\Program Files (x86)\RedHat\Podman`.
However, the binaries are installed in `C:\Program Files\RedHat\Podman` (the x64 binaries path).

Here is a screenshot showing the "working path" and the listing of the directory present in the Environment Variables
![image](https://user-images.githubusercontent.com/905874/154965200-bc3d22ba-70f6-407b-9e66-a6ce1e3e4126.png)

**Steps to reproduce the issue:**

1. Build `podman.msi` from source (currently)
2. Install `podman.msi`
3. Open a shell (`cmd` or `powershell`) and type `podman.exe`

**Describe the results you received:**
Typing `podman.exe` results in a `command not found` error.
![image](https://user-images.githubusercontent.com/905874/154965619-517b7964-e8b5-458a-aab4-8265e147a4a0.png)

**Describe the results you expected:**
Typing `podman.exe` should show the help.
![image](https://user-images.githubusercontent.com/905874/154965755-ef29c675-a397-450d-9dbb-f2a60df6af8b.png)

**Additional information you deem important (e.g. issue happens only occasionally):**
The installer also adds `C:\Program Files (x86)\RedHat\` which is not used/useful.

**Output of `podman version`:**

```
podman.exe -v
podman.exe version 4.0.0-dev
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Installed on Windows 11 x64.

**Comment by Luap99** [comment]
Did you already had podman 3.X installed before?

**Comment by Luap99** [comment]
@n1hility PTAL

**Comment by nunix** [comment]
@Luap99 good point, I uninstalled it some time ago, when I tried v4.0.0-rc2 (and then tried rc4 too).

**Comment by n1hility** [comment]
@nunix I suspect what is happening is that you ended up with two path entries, one for the old release of podman (which used to reference the 32 bit loc) and one for the new one. The installer on the new only manipulates the path elements it is authoritative of, so it would leave old entries behind. Can you confirm running : 
`reg query hkcu\environment /v path`

**Comment by n1hility** [comment]
Another thing that would be helpful is if you could look at add/remove programs and see if there is lingering multiple installers installed

**Comment by nunix** [comment]
@n1hility thanks a lot for your feedback and here are the information requested:
1. Yes, there's the following entries in path (the last one, I added it manually)
```powershell
reg query hkcu\environment /v path

HKEY_CURRENT_USER\environment
    path    REG_EXPAND_SZ    C:\Program Files (x86)\Microsoft\Edge\Application;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\PowerShell\7-preview\preview;C:\Program Files (x86)\RedHat\Podman\;C:\Users\corsair\AppData\Local\Microsoft\WindowsApps;C:\Users\corsair\AppD;c:\hugo\bin;C:\Users\corsair\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\corsair\bin;C:\Program Files\RedHat;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;C:\Program Files\RedHat\Podman;
```

Here is a screenshot for a better view:
![image](https://user-images.githubusercontent.com/905874/155086951-f1f02435-e6ce-4dc7-9ec9-dbb95cbf878a.png)

2. I only have the uninstallers for v4.0.0-rc2 and v4.0.0-dev
![image](https://user-images.githubusercontent.com/905874/155087186-6102ce01-93c0-401f-9291-7b09490326c9.png)

Let me know if you want me to uninstall everything and re-install the versions in specific order (v3 and then v4 + uninstall v3)

**Comment by n1hility** [comment]
@nunix if you uninstall both and then remove the podman path entries, then reinstall everything should be ok. Let me know if that still fails. As a separate issue this points to, the installer should be enhanced to support major upgrades so you don't end up in this sort of situation with duplicate installs

**Comment by nunix** [comment]
@n1hility yes, did the uninstall and removed all the PATH entries. Will wait today or tomorrow to see if v4.0.1 will have the binaries available and redo the install.

Thanks a lot for all the feedback, really appreciated.
