### ISSUE TITLE
How to run container without default gateway when network use macvlan

### ISSUE THREAD

**Issue by susanatgit** [containers/podman#13319]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

If there is a way to run container without default gateway, when network use macvlan. There is a scenario, if I want to create a container that only can be accessed by the same subnet, I would create macvlan network without gateway, but it would add default gateway (the first ip of the subnet) after run container.

**Steps to reproduce the issue:**

1. Run "podman network create -d macvlan --subnet=192.168.1.0/24 -o parent=ens192 -o mode=bridge ens192"

2. Run "podman run -itd --name=test --network=ens192 <image_id> /bin/bash"

3. Run "podman exec -it <container_id> /bin/bash"
4. Run "ip route"

**Describe the results you received:**
bash-4.2# ip route
default via 192.168.1.1 dev eth0
192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.5

**Describe the results you expected:**
I hope it wouldn't add the default gateway as following:
bash-4.2# ip route
192.168.1.0/24 dev eth0 proto kernel scope link src 192.168.1.5

If we only set ip address on redhat "ip addr add 192.168.1.5/24 dev ens192", it wouldn't add default gateway. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```

```

**Output of `podman info --debug`:**

```

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Luap99** [comment]
What podman version do you use? Do you use CNI or netavark? If CNI, how does your config file looks like?

**Comment by susanatgit** [comment]
The podman version is :
[root@centos8 libpod]# ./bin/podman version
Client:       Podman Engine
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.17.7
Git Commit:   a88ea2c68b1ef01077a53b1c568b85667dcbc1e2
Built:        Tue Feb 22 04:02:18 2022
OS/Arch:      linux/amd64
[root@centos8 libpod]#

I use CNI, config file as following:
{
   "args": {
      "podman_options": {
         "mode": "bridge"
      }
   },
   "cniVersion": "0.4.0",
   "name": "ens192",
   "plugins": [
      {
         "type": "macvlan",
         "master": "ens192",
         "ipam": {
            "type": "host-local",
            "routes": [
               {
                  "dst": "0.0.0.0/0"
               }
            ],
            "ranges": [
               [
                  {
                     "subnet": "192.168.1.0/24",
                     "gateway": "192.168.1.1"
                  }
               ]
            ]
         },
         "mode": "bridge",
         "capabilities": {
            "ips": true
         }
      }
   ]
}

**Comment by Luap99** [comment]
You can remove the default route `"dst": "0.0.0.0/0"` and the gateway from this config.

**Comment by Luap99** [comment]
@mheon I think we need a way to do the same for netavark.

**Comment by flouthoc** [comment]
If config could pass additional property or empty route array then netavark could avoid adding a default route and I guess hopefully this is only needed for `macvlan` cause `bridge` might always need a default route.

**Comment by Luap99** [comment]
Bridge already supports internal via `--internal` I guess we should use the same for macvlan.

**Comment by flouthoc** [comment]
@Luap99 Sure, if we could use `--internal` then its a small patch on `netavark`. I'll try this out.

**Comment by mheon** [comment]
Using `--internal` WFM

**Comment by Luap99** [comment]
This will also require patches in libnetwork. I think we error right now when you use --internal and macvlan, and we also have to fix it for CNI as well.

**Comment by susanatgit** [comment]
@Luap99 , it work as expected after remove the route and gateway in cni file. thanks.

**Comment by flouthoc** [comment]
If CLI validation is removed from `podman` for `--internal` and `macvlan` following PR enables this feature: https://github.com/containers/netavark/pull/246

**Comment by Luap99** [comment]
Note that this is not safe when you run a privileged container since it can always add the default route back. For bridge networks we block routing so this secure even for privileged containers. I don't think we can do the same for macvlan, we should not change the host macvlan device to block routing because this could break many other things.

**Comment by susanatgit** [comment]
@Luap99 , do you mean podman wouldn't fix it when create macvlan?
