### ISSUE TITLE
podman-4.x: did not get container create message from subprocess

### ISSUE THREAD

**Issue by srcshelton** [containers/podman#13327]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman aborts with `did not get container create message from subprocess`.

The release version of `podman-4.0.0` seems to have a regression vs. RC5 which causes `podman build` failures.  I've completed this process many times with RC5 and previous RCs, but the new release version is the first time I've seen this particular issue.

N.B. The inherited images in the `FROM` clause were (successfully) built with `podman-4.0.0`.

**Steps to reproduce the issue:**

1. `git clone https://github.com/srcshelton/docker-gentoo-build`

2. `cd docker-gentoo-build && sudo ./gentoo-init.docker`

(Apologies, working on a quicker, simpler reproducer)

**Describe the results you received:**

Variously:

```
# podman image build --build-arg env_id=328e90b0c696 --build-arg 'environment_filter=^(declare -x|export) (COLUMNS|EDITOR|GENTOO_PROFILE|HOME|HOSTNAME|LESS(OPEN)?|LINES|LS_COLORS|(MAN)?PAGER|(OLD)?PWD|PATH|(|SYS|PORTAGE_CONFIG)ROOT|SHLVL|TERM)=' --compress --file Dockerfile.build --loglevel 3 --network none --no-cache --platform linux/amd64 --squash-all --tag localhost/gentoo-build-root:latest .
[1/2] STEP 1/3: FROM localhost/gentoo-base:latest AS base
[1/2] STEP 2/3: ARG ROOT
[1/2] STEP 3/3: RUN test -s "${ROOT}"/usr/libexec/environment.sh
[2/2] STEP 1/24: FROM localhost/gentoo-env:latest
[2/2] STEP 2/24: ARG env_name
[2/2] STEP 3/24: ARG env_id
[2/2] STEP 4/24: ARG environment_filter
[2/2] STEP 5/24: ARG ROOT
[2/2] STEP 6/24: ARG SYSROOT
[2/2] STEP 7/24: ARG PORTAGE_CONFIGROOT
[2/2] STEP 8/24: COPY --from=base "${ROOT}" /
[2/2] STEP 9/24: RUN test -s /usr/libexec/environment.sh
time="2022-02-23T16:39:37Z" level=error msg="did not get container create message from subprocess: read |0: i/o timeout"
error running container: write containercreatepipe: broken pipe
Error: error building at STEP "RUN test -s /usr/libexec/environment.sh": error while running runtime: exit status 1
```

... just once:

```
# podman image build --build-arg env_id=328e90b0c696 --build-arg 'environment_filter=^(declare -x|export) (COLUMNS|EDITOR|GENTOO_PROFILE|HOME|HOSTNAME|LESS(OPEN)?|LINES|LS_COLORS|(MAN)?PAGER|(OLD)?PWD|PATH|(|SYS|PORTAGE_CONFIG)ROOT|SHLVL|TERM)=' --compress --file Dockerfile.build --loglevel 3 --network none --no-cache --platform linux/amd64 --squash-all --tag localhost/gentoo-build-root:latest .
[1/2] STEP 1/3: FROM localhost/gentoo-base:latest AS base
[1/2] STEP 2/3: ARG ROOT
[1/2] STEP 3/3: RUN test -s "${ROOT}"/usr/libexec/environment.sh
[2/2] STEP 1/24: FROM localhost/gentoo-env:latest
[2/2] STEP 2/24: ARG env_name
[2/2] STEP 3/24: ARG env_id
[2/2] STEP 4/24: ARG environment_filter
[2/2] STEP 5/24: ARG ROOT
[2/2] STEP 6/24: ARG SYSROOT
[2/2] STEP 7/24: ARG PORTAGE_CONFIGROOT
[2/2] STEP 8/24: COPY --from=base "${ROOT}" /
[2/2] STEP 9/24: RUN test -s /usr/libexec/environment.sh
[2/2] STEP 10/24: RUN rm -rf /var/db/pkg/acct-* /var/empty/.keep_acct-user_sshd-0
[2/2] STEP 11/24: LABEL maintainer="stuart@xxx"
[2/2] STEP 12/24: LABEL Description="Gentoo base @system image"
[2/2] STEP 13/24: LABEL envrionment_from="${env_name}:${env_id}"
[2/2] STEP 14/24: RUN { set -o pipefail 2>/dev/null || true ; } ;     test -s /usr/libexec/environment.sh && ...
[2/2] STEP 15/24: RUN test -d /etc/portage/package.use.build &&     rm -r /etc/portage/package.use &&     mv /etc/portage/package.use.build /etc/portage/package.use
[2/2] STEP 16/24: ENV ROOT="/"
[2/2] STEP 17/24: ENV SYSROOT="${ROOT}"
[2/2] STEP 18/24: ENV PORTAGE_CONFIGROOT="${SYSROOT}"
[2/2] STEP 19/24: RUN { set -o pipefail 2>/dev/null || true ; } ;     test -s /usr/libexec/environment.sh && ...
 * Switching native-compiler to x86_64-pc-linux-gnu-11.2.0 ...>>> Regenerating /etc/ld.so.cache... [ ok ]
 * Generating 6 locales (this might take a while) with 6 jobs
 *  (1/6) Generating en_GB.ISO-8859-1 ... [ ok ]
 *  (2/6) Generating en_GB.ISO-8859-15 ... [ ok ]
 *  (4/6) Generating en_US.ISO-8859-1 ... [ ok ]
 *  (6/6) Generating C.UTF-8 ... [ ok ]
 *  (5/6) Generating en_US.UTF-8 ... [ ok ]
 *  (3/6) Generating en_GB.UTF-8 ... [ ok ]
 * Generation complete
 * Adding locales to archive ... [ ok ]
[2/2] STEP 20/24: COPY entrypoint.sh.build /usr/libexec/entrypoint.sh
[2/2] STEP 21/24: RUN test -s /usr/libexec/entrypoint.sh
time="2022-02-23T16:38:22Z" level=error msg="did not get container create message from subprocess: read |0: i/o timeout"
error running container: write containercreatepipe: broken pipe
Error: error building at STEP "RUN test -s /usr/libexec/entrypoint.sh": error while running runtime: exit status 1
```

**Describe the results you expected:**

Compared to RC5 and all prior 4.0.0 RCs and 3.x releases, this failure mode is new.

Downgrading back to RC5 (without changing any other component on the system) resolves the problem.

**Additional information you deem important (e.g. issue happens only occasionally):**

In all testing so far, the issue has occurred on every attempt, although it occasionally happens later in the process, as above.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.17.5
Git Commit:   84c8870ac236578c41713113fc09a29a5f727bdd
Built:        Mon Feb 21 13:13:07 2022
OS/Arch:      linux/amd64
```

(N.B. Version has `-dev` suffix despite coming from the 4.0.0 release-tag)

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: app-containers/conmon-2.1.0
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: bdb4f6e56cd193d40b75ffc9725d4b74a18cb33c'
  cpus: 8
  distribution:
    distribution: gentoo
    version: unknown
  eventLogger: file
  hostname: dellr330
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.16.8-gentoo
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 3505455104
  memTotal: 68105170944
  networkBackend: cni
  ociRuntime:
    name: crun
    package: app-containers/crun-1.4.2
    path: /usr/bin/crun
    version: |-
      crun version 1.4.2
      commit: f6fbc8f840df1a414f31a60953ae514fa497c748
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: app-containers/slirp4netns-1.1.12
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 22792142848
  swapTotal: 25769787392
  uptime: 196h 3m 29.43s (Approximately 8.17 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  localhost:5000:
    Blocked: false
    Insecure: true
    Location: localhost:5000
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: localhost:5000
  search:
  - docker.io
  - docker.pkg.github.com
  - quay.io
  - public.ecr.aws
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 25
    paused: 0
    running: 23
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /space/podman/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp/.private/root
  imageStore:
    number: 185
  runRoot: /var/run/podman
  volumePath: /space/podman/volumes
version:
  APIVersion: 4.0.0-dev
  Built: 1645449187
  BuiltTime: Mon Feb 21 13:13:07 2022
  GitCommit: 84c8870ac236578c41713113fc09a29a5f727bdd
  GoVersion: go1.17.5
  OsArch: linux/amd64
  Version: 4.0.0-dev

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Comment by srcshelton** [comment]
Bah - it's just happened on RC5 too 😩


It seems to happen more often on the release version, but it now seems that the RCs can be affected too (but not so frequently?)

**Comment by mheon** [comment]
Any chance you can go back to 3.4.4 and verify it still happens? The mssage makes me suspicious of Conmon which would be independent of Podman version

**Comment by srcshelton** [comment]
Sure thing - I'll probably need to schedule a reboot due to the 3.x -> 4.x database format changes in podman, but I'll see if I can try this later tonight.

**Comment by Luap99** [comment]
No this my network setup code in buildah which is failing, it is not related to conmon.

We spawn a subprocess a with two pipes attached, it will wait until the subprocess creates the oci runtime container then sends a message to the parent that the container is created. The parent will now start the network setup, afterwards it will write to the other pipe to send the subprocess that it should start the build container.

**Comment by Luap99** [comment]
@srcshelton Can you try to reproduce with the latest buildah?

**Comment by Luap99** [comment]
Relevant code:
https://github.com/containers/buildah/blob/f85e52332299abec18c6cc24d18df75d68b504d7/run_linux.go#L949-L960
https://github.com/containers/buildah/blob/f85e52332299abec18c6cc24d18df75d68b504d7/run_linux.go#L2289-L2320

@srcshelton You should be able to get a working build with `--network host`

**Comment by Luap99** [comment]
@srcshelton Is your host under high load? Buildah waits 5 seconds for the child process to report that it created the oci container. It looks like it times out on your pc. Maybe 5 seconds is not enough.

**Comment by srcshelton** [comment]
> @srcshelton Is your host under high load?

Hmm - it's a Skylake Xeon so it's not the fastest machine around, but I wouldn't have said it was under abnormally high load (although it was building in two containers at once when the error occurred - but this has been fine previously).

> Maybe 5 seconds is not enough.

I'm rebuilding now with a patch to change the deadline from 5 seconds to 30, to see  what happens…

**Comment by srcshelton** [comment]
I don't think it's load-related - I just got this on an 8GB Raspberry Pi:

```
time="2022-02-25T10:52:40Z" level=error msg="did not get container create message from subprocess: read |0: i/o timeout"
error running container: write containercreatepipe: broken pipe
Error: error building at STEP "RUN test ! -e /var/db/repos || rm -r /var/db/repos": error while running runtime: exit status 1

$ uptime
 10:53:50 up 108 days, 23:28, 23 users,  load average: 0.49, 0.97, 0.73
```

**Comment by Luap99** [comment]
Does it work with a higher timeout?

**Comment by srcshelton** [comment]
> Does it work with a higher timeout?

The version with the 30s timeout is on the Skylake system and looks okay so far - I'm just building it for the smaller systems to see whether it's effective there...

**Comment by Luap99** [comment]
OK I just looked in the podman source and there we wait for a maximum of 4 minutes. So I guess when we bump it in buildah to match this it should be fine.

**Comment by Luap99** [comment]
@srcshelton Any update? Should we just go ahead and increase the timeout in buildah?

**Comment by srcshelton** [comment]
> @srcshelton Any update? Should we just go ahead and increase the timeout in buildah?

Sorry, I thought you were already planning to do this!

I'm patching my podman builds with a timeout of 30s, which seems fine so far - but if a value of 4m is used elsewhere then this sounds like the most compatible value to use permanently.
