### ISSUE TITLE
Issue with TLS Verification: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by DanielViglione** [containers/podman#13330]
/kind bug

**Description**

I rebooted my Mac OSX Big Sur 11.6 today and now I am getting the following error when trying to pull images with podman:

Error: initializing source docker://python:3.8.1: pinging container registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": x509: certificate signed by unknown authority

**Steps to reproduce the issue:**

1. brew install podman

2. podman machine start

3. podman machine init

4. podman pull python:3.8.1
Trying to pull docker.io/library/python:3.8.1...
Error: initializing source docker://python:3.8.1: pinging container registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": x509: certificate signed by unknown authority

**Output of `podman version`:**

```
podman version
Client:
Version:      3.4.1
API Version:  3.4.1
Go Version:   go1.17.2
Built:        Tue Oct 19 17:14:42 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 16:45:07 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
podman info --debug
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "35"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.18-200.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1647390720
  memTotal: 2061381632
  ociRuntime:
    name: crun
    package: crun-1.4.2-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.2
      commit: f6fbc8f840df1a414f31a60953ae514fa497c748
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 22m 49.76s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 0
    stopped: 5
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 91
  runRoot: /run/user/1000/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 1638999907
  BuiltTime: Wed Dec  8 21:45:07 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.4
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? 
I am using the podman available on brew.

Why did I start getting this error today? I have been using podman for months now without issue.

**Comment by vrothberg** [comment]
Thanks for reaching out, @DanielViglione!

@baude can you take a look?

**Comment by DanielViglione** [comment]
@vrothberg any update on this?

**Comment by zhangguanzhang** [comment]
could you try this command ?
```
curl -v https://registry-1.docker.io/v2/
```

**Comment by vrothberg** [comment]
@baude ping.

**Comment by DanielViglione** [comment]
@zhangguanzhang 

Running curl gives me this (note I specify --cacert flag):

curl -v --cacert MyCompany_proxy_G3.pem  https://registry-1.docker.io/v2/
* Uses proxy env variable no_proxy == 'localhost,127.0.0.1,localaddress,.local,.availity.net,.availity.com,192.168.1.2,C02FVHB2MD6M'
* Uses proxy env variable https_proxy == 'http://proxy-corp.availity.net:8080'
*   Trying 172.28.5.130:8080...
* Connected to proxy-corp.availity.net (172.28.5.130) port 8080 (#0)
* allocate connect buffer!
* Establish HTTP proxy tunnel to registry-1.docker.io:443
> CONNECT registry-1.docker.io:443 HTTP/1.1
> Host: registry-1.docker.io:443
> User-Agent: curl/7.79.1
> Proxy-Connection: Keep-Alive
> 
< HTTP/1.1 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: Availity_proxy_G3.pem
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=*.docker.com
*  start date: Nov 30 00:00:00 2021 GMT
*  expire date: Dec 29 23:59:59 2022 GMT
*  subjectAltName: host "registry-1.docker.io" matched cert's "*.docker.io"
*  issuer: C=US; ST=Florida; L=Jacksonville; O=Availity LLC; OU=Infrastructure; CN=Availity Proxy G3
*  SSL certificate verify ok.
> GET /v2/ HTTP/1.1
> Host: registry-1.docker.io
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< content-type: application/json
< docker-distribution-api-version: registry/2.0
< www-authenticate: Bearer realm="https://auth.docker.io/token",service="registry.docker.io"
< date: Wed, 16 Mar 2022 14:45:15 GMT
< content-length: 87
< strict-transport-security: max-age=31536000
< Cache-Control: proxy-revalidate
< Proxy-Connection: Keep-Alive
< Connection: Keep-Alive
< Proxy-support: Session-based-authentication
< 
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
* Connection #0 to host proxy-corp.availity.net left intact

**Comment by DanielViglione** [comment]
@zhangguanzhang 

curl -v --cacert Availity_proxy_G3.pem  https://registry-1.docker.io/v2/

* Uses proxy env variable no_proxy == 'localhost,127.0.0.1,localaddress,.local,.availity.net,.availity.com,192.168.1.2,C02FVHB2MD6M'

* Uses proxy env variable https_proxy == '[http://proxy-corp.availity.net:8080']()

*   Trying 172.28.5.130:8080...

* Connected to proxy-corp.availity.net (172.28.5.130) port 8080 (#0)

* allocate connect buffer!

* Establish HTTP proxy tunnel to registry-1.docker.io:443

> CONNECT registry-1.docker.io:443 HTTP/1.1

> Host: registry-1.docker.io:443

> User-Agent: curl/7.79.1

> Proxy-Connection: Keep-Alive

>

< HTTP/1.1 200 Connection established

<

* Proxy replied 200 to CONNECT request

* CONNECT phase completed!

* ALPN, offering h2

* ALPN, offering http/1.1

* successfully set certificate verify locations:

*  CAfile: Availity_proxy_G3.pem

*  CApath: none

* TLSv1.3 (OUT), TLS handshake, Client hello (1):

* TLSv1.3 (IN), TLS handshake, Server hello (2):

* TLSv1.2 (IN), TLS handshake, Certificate (11):

* TLSv1.2 (IN), TLS handshake, Server key exchange (12):

* TLSv1.2 (IN), TLS handshake, Server finished (14):

* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):

* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):

* TLSv1.2 (OUT), TLS handshake, Finished (20):

* TLSv1.2 (IN), TLS handshake, Finished (20):

* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384

* ALPN, server did not agree to a protocol

* Server certificate:

*  subject: CN=*.docker.com

*  start date: Nov 30 00:00:00 2021 GMT

*  expire date: Dec 29 23:59:59 2022 GMT

*  subjectAltName: host "registry-1.docker.io" matched cert's "*.docker.io"

*  issuer: C=US; ST=Florida; L=Jacksonville; O=Availity LLC; OU=Infrastructure; CN=Availity Proxy G3

*  SSL certificate verify ok.

> GET /v2/ HTTP/1.1

> Host: registry-1.docker.io

> User-Agent: curl/7.79.1

> Accept: */*

>

* Mark bundle as not supporting multiuse

< HTTP/1.1 401 Unauthorized

< content-type: application/json

< docker-distribution-api-version: registry/2.0

< www-authenticate: Bearer realm="[https://auth.docker.io/token",service="registry.docker.io"](https://auth.docker.io/token%22,service=%22registry.docker.io%22)

< date: Wed, 16 Mar 2022 14:45:15 GMT

< content-length: 87

< strict-transport-security: max-age=31536000

< Cache-Control: proxy-revalidate

< Proxy-Connection: Keep-Alive

< Connection: Keep-Alive

< Proxy-support: Session-based-authentication

<

{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}

* Connection #0 to host proxy-corp.availity.net left intact

**Comment by DanielViglione** [comment]
It turns out it was a corporate proxy issue. Keep up the good work on Podman guys! I am using it more and more as an alternative to Docker.
