### ISSUE TITLE
Add option to prettify systemd units

### ISSUE THREAD

**Issue by AlphaJack** [containers/podman#13337]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Systemd units generated by `podman generate systemd --new --name --files POD` are useful but not human friendly, as all options are printed in one line. It would be great to have a `--pretty` flag (or similar) so different options are printed on different lines (with some indentation if possible) to improve readability.

**Steps to reproduce the issue:**

1. Run `podman generate systemd --new --name --files POD` 

2. Run `systemctl edit --full pod-POD.service`

**Describe the results you received:**
```ini
# container-authentik-server.service
# autogenerated by Podman 3.4.4
# Sun Feb 20 22:03:19 CET 2022

[Unit]
Description=Podman container-authentik-server.service
Documentation=man:podman-generate-systemd(1)
Wants=network-online.target
After=network-online.target
RequiresMountsFor=%t/containers
BindsTo=pod-authentik.service container-authentik-postgres.service container-authentik-redis.service
After=pod-authentik.service container-authentik-postgres.service container-authentik-redis.service

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
TimeoutStopSec=70
ExecStartPre=/bin/rm -f %t/%n.ctr-id
ExecStart=/usr/bin/podman run --cidfile=%t/%n.ctr-id --cgroups=no-conmon --rm --pod-id-file %t/pod-authentik.pod-id --sdnotify=conmon -d --replace --name authentik-server --requires authentik-postgres --requires authentik-redis --memory=1G --entrypoint "[\"/lifecycle/ak\", \"server\"]" --env-file /home/podman/containers/config/authentik/server/env --volume /home/podman/containers/storage/authentik/server/media:/media --volume /home/podman/containers/storage/authentik/server/templates:/templates ghcr.io/goauthentik/server:latest
ExecStop=/usr/bin/podman stop --ignore --cidfile=%t/%n.ctr-id
ExecStopPost=/usr/bin/podman rm -f --ignore --cidfile=%t/%n.ctr-id
Type=notify
NotifyAccess=all

[Install]
WantedBy=default.target
```

**Describe the results you expected:**

```ini
# container-authentik-server.service
# autogenerated by Podman 3.4.4
# Sun Feb 20 22:03:19 CET 2022

[Unit]
Description=Podman container-authentik-server.service
Documentation=man:podman-generate-systemd(1)
Wants=network-online.target
After=network-online.target
RequiresMountsFor=%t/containers
BindsTo=pod-authentik.service \
    container-authentik-postgres.service \
    container-authentik-redis.service
After=pod-authentik.service \
    container-authentik-postgres.service \
    container-authentik-redis.service

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
TimeoutStopSec=70
ExecStartPre=/bin/rm -f %t/%n.ctr-id
ExecStart=/usr/bin/podman run \
    --cidfile=%t/%n.ctr-id \
    --cgroups=no-conmon \
    --rm \
    --pod-id-file %t/pod-authentik.pod-id \
    --sdnotify=conmon \
    -d \
    --replace \
    --name authentik-server \
    --requires authentik-postgres \
    --requires authentik-redis \
    --memory=1G \
    --entrypoint "[\"/lifecycle/ak\", \"server\"]" \
    --env-file /home/podman/containers/config/authentik/server/env \
    --volume /home/podman/containers/storage/authentik/server/media:/media \
    --volume /home/podman/containers/storage/authentik/server/templates:/templates \
    ghcr.io/goauthentik/server:latest
ExecStop=/usr/bin/podman stop --ignore --cidfile=%t/%n.ctr-id
ExecStopPost=/usr/bin/podman rm -f --ignore --cidfile=%t/%n.ctr-id
Type=notify
NotifyAccess=all

[Install]
WantedBy=default.target
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.4
Git Commit:   f6526ada1025c2e3f88745ba83b8b461ca659933
Built:        Thu Dec  9 20:21:17 2021
OS/Arch:      linux/arm64
```

**Output of `podman info --debug`:**

```
not relevant
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
not relevant
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

not relevant

**Comment by vrothberg** [comment]
Thanks for reaching out, @AlphaJack!

I really like the idea. It'll need some investigation on how to prettify. Probably via the templates, @Luap99 ?

**Comment by Luap99** [comment]
Yes like that idea, I don't think we need a option for this. We should do it by default I do not see any harm or why someone would want to stick with the old format.

**Comment by vrothberg** [comment]
> Yes like that idea, I don't think we need a option for this. We should do it by default I do not see any harm or why someone would want to stick with the old format.

I concur. If we can make it pretty, let's make it pretty :) There's no guarantee on the output format other than systemd must be able to eat it.

**Comment by Luap99** [comment]
For the implementation I think we can replace `[space]-` with `[space][backslash][newline][tab]-`

**Comment by rhatdan** [comment]
@vrothberg @Luap99 any movement on this?

**Comment by vrothberg** [comment]
Nope.

**Comment by Akasurde** [comment]
@rhatdan @vrothberg I am interested in working on this.

**Comment by rhatdan** [comment]
Replacing this PR.

**Comment by AlphaJack** [comment]
Is it possible to also prettify pod units other than container ones?
Also, is there no option to have the image on a new line instead of the same line of the last option?
