### ISSUE TITLE
Image search filter `stars` only matches on "equal" not on "equal or greater" anymore

### ISSUE THREAD

**Issue by arctic-alpaca** [containers/podman#13340]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
The `stars` filter seems to only match exact stars, not equal or greater stars. I think this changed from 3.4.4 to 4.0.
Searching for an exact number of stars doesn't seem really useful as you probably just want a lower limit.

**Steps to reproduce the issue:**

1. `podman image search -f=is-official=true -f=is-automated=false -f=stars=1 hello-world`

**Describe the results you received:**
No result.

**Describe the results you expected:**
All official, non-automated images called `hello-world`. 

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm pretty sure this behavior is new in 4.0 and 3.4.4 worked with equal or greater.

Using negative input ignores the `stars` filter, this should probably return an error.

If searching for exactly the stars in the filter is intentional, the [API reference](https://docs.podman.io/en/latest/_static/api.html?version=v4.0#operation/ImageSearchLibpod) is incorrect as it states: "Matches images that has at least 'number' stars."

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.0
API Version:  4.0.0
Go Version:   go1.16.13

Built:      Mon Feb 21 19:31:38 2022
OS/Arch:    linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpus: 12
  distribution:
    distribution: fedora
    variant: kde
    version: "35"
  eventLogger: journald
  hostname: arctic-alpaca-Desktop
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.16.9-200.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 711036928
  memTotal: 16689451008
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.2-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.2
      commit: f6fbc8f840df1a414f31a60953ae514fa497c748
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 8587571200
  swapTotal: 8589930496
  uptime: 2h 11m 6.06s (Approximately 0.08 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/arctic-alpaca/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/arctic-alpaca/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 9
  runRoot: /run/user/1000/containers
  volumePath: /home/arctic-alpaca/.local/share/containers/storage/volumes
version:
  APIVersion: 4.0.0
  Built: 1645468298
  BuiltTime: Mon Feb 21 19:31:38 2022
  GitCommit: ""
  GoVersion: go1.16.13
  OsArch: linux/amd64
  Version: 4.0.0

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.0.0-10.fc35.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 35 using [rhcontainerbot](https://copr.fedorainfracloud.org/coprs/rhcontainerbot/)/[podman4](https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman4/) copr.

**Comment by vrothberg** [comment]
Works on my end. Can you try again? Maybe `docker.io` had a temporary hiccup.

**Comment by arctic-alpaca** [comment]
@vrothberg Can confirm this is working as expected again. Thanks for looking into it.
