### ISSUE TITLE
Podman ps error

### ISSUE THREAD

**Issue by fantastic2085** [containers/podman#13345]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Start a Registry using Podman, and after openstack is deployed on the same host as Podman, the Podman ps command displays an error

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**
An error is returned after executing the podman ps command
![image](https://user-images.githubusercontent.com/4116773/155968751-78aeda46-0f3a-4f53-8d5d-49972dfe2661.png)

**Describe the results you expected:**
![image](https://user-images.githubusercontent.com/4116773/155968875-bea709c7-ed65-4859-9584-16709796bdbb.png)

**Additional information you deem important (e.g. issue happens only occasionally):**
Openstack also exists in the environment

**Output of `podman version`:**
![image](https://user-images.githubusercontent.com/4116773/155968967-1c8f6317-4198-4d8d-97a6-52d62d0161cb.png)

```
(paste your output here)
```

**Output of `podman info --debug`:**
[podman-info-debug.txt](https://github.com/containers/podman/files/8152625/podman-info-debug.txt)

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**
![image](https://user-images.githubusercontent.com/4116773/155969593-83077a82-8fef-4698-9f61-5853e17bc71d.png)

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**
No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
system:
![image](https://user-images.githubusercontent.com/4116773/155969433-5fe0fc30-d5f4-45c7-b42f-e8235feb9674.png)

openstack：
![image](https://user-images.githubusercontent.com/4116773/156090481-4cee1c5e-c535-4feb-8e49-a8609236cecd.png)

docker version:
![image](https://user-images.githubusercontent.com/4116773/156090537-a2b46f64-ed4a-4be1-b565-d4d88158c8ba.png)

**Comment by Luap99** [comment]
Please provide the information as requested in the issue template.

**Comment by rhatdan** [comment]
Since we have had no feedback, closing reopen if  you want to provide the feedback.
