### ISSUE TITLE
Implement "podman build --output type=local,dest=path ." à la docker buildx

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [containers/podman#13359]
/kind feature

**Description**

I find the "local ouput" feature of buildx quite useful and use it extensively for my "short builds" (typically creating some .rpm/.deb packages of some of our internal tools already delivered as tarballs). I use a dockerfile with multi stage builds, where the very final target is "scratch" as base image, and I copy into this image the "result" of my build. When coupled with docker buildx `--output type=local,dest=path` feature, I can very easily get the result of my build in a local folder, without using things like "docker cp" or "podman mount". Plus, using "docker build" allows to benefit from docker caching so the same input instantely produces the same output when I have run it already (while I could use "docker run" in more complex builds like the ones I describe in #13358).

I understand you don't want to implement all the complexity of the buildx --ouput flag (actually, even on buildx side, this --output flag is half implemented as soon as you try doing multi-arch builds), but would it make sense to implement only the `type=local` output, or any equivalent podman flag ?

**Comment by Romain-Geissler-1A** [comment]
Actually I think I should have rather opened a buildah issue, and it seems a duplicate of this feature request: https://github.com/containers/buildah/issues/3789

**Comment by rhatdan** [comment]
Yes lets concentrate over there.
