### ISSUE TITLE
Podman loglevel when using HTTP to spawn execs

### ISSUE THREAD

**Issue by bprimekey** [containers/podman#13352]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature request

**Description**

We are using the podman api to spawn container execs, but apparently the log-level is not propagated to the exec instance.
We are trying to control logging output for this scenario, but couldn't find any information about it in the codebase or documentation. Is this supported? Is there some code to checkout, so we can submit a PR?
Any help would be appreciated.

Thank you!

**Steps to reproduce the issue:**

1. Start the podman system service

```ExecStart=/usr/bin/env podman --log-level=warn system service tcp:0.0.0.0:8090 --time=0```

2. Create a container
```curl -X POST -H 'Content-Type: application/json' -d '<payload>' http://0.0.0.0:8090/v1/crs/exec/{containerInstanceName}```

payload: any exec request

3. receive the logs
```journalctl -u podman-system.service```

**Describe the results you received:**

The podman system service is set to warn level as expected and the sample below does not contain any lines for the exec lifecyle, but the underlying podman process still logs them:

```
Feb 24 10:42:12 localhost.localdomain podman[9362]: 2022-02-24 10:42:12.844037402 +0100 CET m=+20.354383714 container exec aaabbb (image=path/to/container:latest, name=container, io.openshift.tags=minimal rhel8, build-date=2021-06-01T12:12:31.484655, io.k8s.display-name=Red Hat Universal Base Image 8 Minimal, description=...)
Feb 24 10:42:12 localhost.localdomain podman[9362]: 2022-02-24 10:42:12.881037613 +0100 CET m=+20.391383945 container exec_died aaabbb (image=path/to/container:latest, name=container, execID=aaabbb1)
Feb 24 10:42:15 localhost.localdomain podman[9362]: 2022-02-24 10:42:15.185649964 +0100 CET m=+22.695996277 container remove cccddd (image=path/to/container2:latest, name=container2, io.buildah.version=1.18.0)
```

**Describe the results you expected:**

We expected not to find the podman exec log lines, since they do show up additionally for the system service, if we configure it with info level and don't with warn level.

**Output of podman version:**
```
podman version
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.7
Git Commit:   f6526ada1025c2e3f88745ba83b8b461ca659933
Built:        Mon Feb 21 15:12:05 2022
OS/Arch:      linux/amd64
```

**Output of podman info --debug:**
```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/local/bin/conmon
    version: 'conmon version 2.0.32, commit: 436b460d1586c2e4ab4e845448449ddd9136767a'
  cpus: 8
  distribution:
    distribution: '"almalinux"'
    version: "8.5"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-348.12.2.el8_5.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 3046858752
  memTotal: 16600264704
  ociRuntime:
    name: runc
    package: runc-1.0.0-377.rc93.el8.8.1.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc93
      commit: cc8939575b80a6f87d165375a910bb29d996ba08
      spec: 1.0.2-dev
      go: go1.14.12
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-4.el8.7.6.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 0
  swapTotal: 0
  uptime: 23h 13m 37.71s (Approximately 0.96 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 35
    paused: 0
    running: 35
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 313
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 1645452725
  BuiltTime: Mon Feb 21 15:12:05 2022
  GitCommit: f6526ada1025c2e3f88745ba83b8b461ca659933
  GoVersion: go1.16.7
  OsArch: linux/amd64
  Version: 3.4.4
```

**Package info (e.g. output of rpm -q podman or apt list podman):**

none

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

We are using AlmaLinux8.5

**Comment by mheon** [comment]
Can you provide more details - do you want to set log level for the exec session on the server from the client? We don't have a way of doing this at the moment. If this is correct, why do you want this - I'm having trouble understanding what you're doing that you'd want split log levels for different server commands?

**Comment by bprimekey** [comment]
We have provided more information to this ticket. We don't necessarily need to control the log level on a per-request basis. The issue is that the log level that we start the system service with is not applied to the spawned execs.
Hopefully this and the added information are sufficent enough to solve this.
Thanks!

**Comment by rhatdan** [comment]
@jwhonce @mheon Still not totally sure on this one.  Do you have more ideas?

**Comment by Luap99** [comment]
The logged lines are podman events, these are not related to the actual log-level since they are required for podman events. You could change the event logger type to file. In this case you would no longer see the messages in journald. However I would recommend to keep it journald since this has built in rotation. Rotation for the file backend will only be added in v4.1.
