### ISSUE TITLE
Implement a "best effort" bind mount feature that would work for remote clients

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [containers/podman#13358]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

The idea would be to implement a "best effort" bind mount feature that would work for remote clients. The goal is to be able to use "podman run -v /path/local/to/client/machine:/path/inside/container" and that on the local machine "/path/local/to/client/machine" acts as on "input/output" folder, wether the actual podman server is running remotely or on the local machine.

I see myself needing quite often to have a folder that either carries some input for my program, or where my program is meant to deliver an output (for example, a set of .rpm packages of my own software being packaged), or sometimes both. More and more, I need to consider two architectures: x86_64 and aarch64, and I wish to deliver my software once for these two architecture, from the same client machine, while I have remote "build" machines available for each arch. Sometimes for my very long build processes (like when I build a whole gnu toolchain for my company), I need to investigate live what are the partial build output being produced by my build, test things inside the container, and then exchange files between the container and the host during develoment and bug fix. So ideally, when my podman client runs on the same machine than my podman server, I use bind mount for my input/output folder. And when I have to use a remote machine (typically, another arch), I replace this by a podman create + podman cp for "input" folder + podman run + podman cp for "output" folder + podman rm. And I have put in place some automatic mechanism to check if bind mount works in general (I generate a random file with a random content, I try to bind mount it, and if I can't, I consider that the podman server is actually remote).

The above scenarios would be a bit more user friendly if we had some special bind mount flag that would consider we want it to be best effort: ideally, we want a real bind mount, but, if the podman server is remote, or belongs to another user on the same machine which have no access to the "client" folder, then it would be automatically replaced by equivalent "podman cp" commands at start and end of the container. Is it something that would make sense ?

**Comment by vrothberg** [comment]
@baude, PTAL

**Comment by Romain-Geissler-1A** [comment]
Brew ? You mean on Mac OS ?

It might be confusing because of my Github photo , but I am considering mainly Linux (for the both the podman client and the server), though I think this need is rather generic between any kind of podman client and podman server running on different machines.

To explain a bit more my configuration: I am in a corporate environment, where "development servers" are being made available to developers. These development servers are RHEL 8 ones, where podman is installed. We have mainly x86_64 servers, but now we start to have a few aarch64 machines. And from a single of these machines (either x86_64 or aarch64) we want to run builds targetting both architectures, so remote build becomes more common now. We don't use podman machine at all, we directly run podman as a server (with systemctl) on the RHEL 8 servers.

**Comment by mheon** [comment]
So the ask here is for a remote volume mount solution that is *independent* of `podman machine`?

**Comment by rhatdan** [comment]
@baude weren't you working on this at one time?

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by vrothberg** [comment]
Going through some old issues. @Romain-Geissler-1A, are you still looking out for this?

**Comment by Romain-Geissler-1A** [comment]
It's still something that I would like to have, but as for #16801 which is very similar but for ports, I am ok to close this as "won't fix" as indeed it seems to be a niche use case and far from trivial to implement, and not sure the added value is huge.
