### ISSUE TITLE
podman machine init is failing to download VM image on MI MacOS machine with error - file too large

### ISSUE THREAD

**Issue by alanfx** [containers/podman#13351]
/kind bug

**Description**

Running `podman machine init` fails while downloading the VM image with the following error on MacOS on an M1 MacBook Air:

```
afield@MacBook-Air ~ % podman machine init
Downloading VM image: fedora-coreos-35.20220213.2.0-qemu.aarch64.qcow2.xz  29.9…
Error: write /Users/afield/.local/share/containers/podman/machine/qemu/fedora-coreos-35.20220213.2.0-qemu.aarch64.qcow2.xz: file too large
```

This is not a disk space issue. The machine has 500GB of free space.

**Steps to reproduce the issue:**

1. Execute `podman machine stop` and `podman machine rm` if you have an existing podman install that works

2. Execute `podman machine init`

**Describe the results you received:**

```
afield@MacBook-Air ~ % podman machine init
Downloading VM image: fedora-coreos-35.20220213.2.0-qemu.aarch64.qcow2.xz  29.9…
Error: write /Users/afield/.local/share/containers/podman/machine/qemu/fedora-coreos-35.20220213.2.0-qemu.aarch64.qcow2.xz: file too large
```

**Describe the results you expected:**

The image should be downloaded and expanded, so podman will work.

**Additional information you deem important (e.g. issue happens only occasionally):**

I don't have a working podman at this point, so none of these commands work.

**Output of `podman version`:**

```
v3.4.4
```

**Output of `podman info --debug`:**

```
See above
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Running on an M1 machine on MacOS. Podman was installed via HomeBrew
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No, Podman 4.0 is not available via HomeBrew yet

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is on a physical machine

**Comment by baude** [comment]
how much ram do you have?

**Comment by baude** [comment]
any chance this might be it? -> https://stackoverflow.com/questions/64826396/macos-big-sur-error-installing-puppeteer-with-efbig-file-too-large-write

**Comment by alanfx** [comment]
Hey @baude my machine has 16GB of RAM and changing `ulimit` helped with downloading the image archive, but I still got this error:

```
afield@MacBook-Air ~ % ulimit -c 2097152 && ulimit -f 2097152
afield@MacBook-Air ~ % podman --log-level=debug machine init 
INFO[0000] podman filtering at log level debug          
Downloading VM image: fedora-coreos-35.20220227.2.0-qemu.aarch64.qcow2.xz: done  
Extracting compressed file
ERRO[0035] write /Users/afield/.local/share/containers/podman/machine/qemu/podman-machine-default_fedora-coreos-35.20220227.2.0-qemu.aarch64.qcow2: file too large 
```

**Comment by baude** [comment]
i was just going to ask you to run that.  could you provide the ulimits you had prior to going unlimited?  and do you know if that ulimit is standard on macs?

**Comment by rhatdan** [comment]
Since we recieved no feedback, I am closing.  Reopen if you want to continue working on this issue.
