### ISSUE TITLE
RPM packages for CentOS 8 Stream

### ISSUE THREAD

**Issue by fpoirotte** [containers/podman#13350]
/kind question

**Description**

I apology in advance if this is the wrong place to ask.
I am aware of the work done by @lsm5 in https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman4/ (thanks again for that!) but that repository only targets CentOS 9 Stream & Fedora 35.
Are there any plans to make podman 4 available for CentOS 8 Stream in an official repository? (or close to an official one like the repository above)

PS : please note that this specifically calls for RPM packages for C8 Stream and not CentOS Linux 8 since the latter has reach EOL status since Dec. 31st, 2021.

Best regards,
François

**Comment by mlegenovic** [comment]
http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/

**Comment by fpoirotte** [comment]
> http://mirror.centos.org/centos/8-stream/AppStream/x86_64/os/Packages/

Yeah... except I'm not really sure what version this actually is because the package was built in October 2021, but podman 4 wasn't actually released until this month!
So it seems a bit fishy even though it's part of the official repositories.

**Comment by mheon** [comment]
Podman v4.0 is scheduled for RHEL 8.6.0, so I presume it should be filtering into Cent Stream 8 in advance of that.

**Comment by afbjorklund** [comment]
I think that `4.0.0-0.10.module_el8.6.0+944+d413f95e` was some kind of packaging accident, built from 4.0.0-dev.

https://koji.mbox.centos.org/koji/buildinfo?buildID=19463

**Comment by lsm5** [comment]
@fpoirotte Let me try enabling the podman4 copr for c8s. If it proves too painful to maintain, I probably will disable it back. Let's see how it goes.

**Comment by afbjorklund** [comment]
Some dependencies are missing:
```
DEBUG util.py:444:  No matching package to install: 'go-rpm-macros'
DEBUG util.py:444:  No matching package to install: 'golang-github-cpuguy83-md2man'
```

**Comment by lsm5** [comment]
Instructions updated on the copr description: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman4/ . It's a little different for centos 8 stream. I'll update the install docs on podman.io as well. I won't be able to account for mix-n-match between copr packages and the container-tools module available by default in centos 8. So, I would suggest disabling container-tools module before installing this.

@fpoirotte and others, please give it a try and let me know.

**Comment by nivekuil** [comment]
Getting this error with `podman run`, doesn't go away with ` --security-opt=seccomp=unconfined`: `Error: loading seccomp profile (/usr/share/containers/seccomp.json) failed: seccomp not enabled in this build`

**Comment by lsm5** [comment]
> Getting this error with `podman run`, does go away with ` --security-opt=seccomp=unconfined`: `Error: loading seccomp profile (/usr/share/containers/seccomp.json) failed: seccomp not enabled in this build`

I do see that podman is built with seccomp in the rpm, but for whatever reason podman info shows `seccompEnabled: false`.  Both c9s and c8s builds use the same rpm source, but seccomp info looks different on both.

Centos 9 Stream
```
$ podman info | grep seccomp
 seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
      libseccomp: 2.5.2
```

CentOS 8 Stream
```
$ podman info | grep seccomp
    seccompEnabled: false
    seccompProfilePath: /usr/share/containers/seccomp.json
```

@mheon any idea what else would be missing ?


> 
> `podman logs` seem to be broken: `Error: Journald logging only enabled with systemd on linux: no support for this OS yet`

I have commented out `log_driver = journald` from containers.conf. If you update your containers-common package to `4:1-46` this should be resolved.

> 
> Also, it seems you need to install podman from container-tools first before using this repo.

I have added missing dependencies to the copr itself, so you shouldn't need to install podman or any other packages from container-tools before installing from the copr.

> 
> One more weird thing:
> 
> ```
> # podman -v
> podman version 4.0.2
> # podman network create -d ipvlan
> Error: unsupported driver ipvlan: invalid argument
> ```
> 
> other 4.0 flags like --ip6 work though

@Luap99 @mheon is the ipvlan network plugin expected on centos 8? I find it on fedora but not on centos 8 stream and 9 stream

**Comment by Luap99** [comment]
ipvlan does not work with netavark, only cni supports ipvlan

**Comment by mheon** [comment]
Re: seccomp - either the default profile listed is missing, or Podman was built without libseccomp support (bad buildtags?)

**Comment by Luap99** [comment]
> `podman logs` seem to be broken: `Error: Journald logging only enabled with systemd on linux: no support for this OS yet`

This sounds like podman was compiled without systemd build tag.

**Comment by lsm5** [comment]
hmm, in the build logs I do see the buildtags being used : ` BUILDTAGS='seccomp exclude_graphdriver_devicemapper selinux systemd libsubid exclude_graphdriver_btrfs btrfs_noversion` is present in https://download.copr.fedorainfracloud.org/results/rhcontainerbot/podman4/centos-stream-8-x86_64/03670783-podman/build.log.gz . I'll look further though.



> > `podman logs` seem to be broken: `Error: Journald logging only enabled with systemd on linux: no support for this OS yet`
> 
> This sounds like podman was compiled without systemd build tag.

@Luap99  I see that in rhel8, we have set log_driver to k8s-file https://git.centos.org/rpms/containers-common/blob/c8s-stream-rhel8/f/SOURCES/containers.conf#_156 . Should we prefer k8s-file in the centos 8 copr, or would journald be preferable assuming systemd build tag is doable.

**Comment by Luap99** [comment]
Just do not explicitly set this field at all, the build-in default should be able to figure this out on its own

**Comment by lsm5** [comment]
> Just do not explicitly set this field at all, the build-in default should be able to figure this out on its own

great, the latest build on the copr leaves it commented.

**Comment by rhatdan** [comment]
Is this still an issue?

**Comment by zmc** [comment]
I installed the COPR build on centos 8 stream, looking for a fix for https://github.com/containers/podman/issues/14054 - even `podman run alpine` now fails with `Error: loading seccomp profile (/usr/share/containers/seccomp.json) failed: seccomp not enabled in this build`. Maybe not worth publishing them after all.

**Comment by lsm5** [comment]
podman 4 is now on centos 8 stream's default repos. So I'm getting rid of them from the copr.
