### ISSUE TITLE
Using port_handler=slipr4netns in pod prevents TCP connections

### ISSUE THREAD

**Issue by beewoolie** [containers/podman#13367]
/kind bug

**Description**

We want to build a POD with two containers, one of them a database and the other the application using this local database.  We also want to allow the application to see the source IP address for connections in order to enforce policy based on the requesting host.

The applications and DB can communicate within the POD and accept connections from outside hosts, but when we enable the port_handler=slirp4netns feature, the DB and application can no longer communicate within the POD and external requests are not routed to the application.

The attached script provides a test case that demonstrates the issue.  Use =gch-t info= for an explanation of the commands.

[gch-t.zip](https://github.com/containers/podman/files/8150025/gch-t.zip)

**Steps to reproduce the issue:**

1. =gch-t image= to create OS image with ncat.

2. =gch-t -p launch= to run the image with ncat as the application.

3. =gch-t log= to watch the progress of ncat.  From another shell, use =netcat localhost 3000= to connect to the server in the pod.  It will report that there was a connection from 10.0.2.100.

4. =gch-t shutdown= to terminate the container.

5. =gch-t -px launch= to run the image with ncat as the application and the port_handler changed to slirp4netns.

6. =gch-t-log= to watch the progress of ncat.  From another shell, use =netcat localhost 3000= to connect to the server in the pod.  No connection is made.

The script also allows you to test ncat with and without the port_handler change and without a POD.  In both of these cases, the ncat operates correctly.

**Describe the results you received:**

Without a containing POD, the port_handler slirp4netns behaves as expected, forwarding the source IP to the application.

Within a containing POD, the port_handler slirp4netns appears to break connections to applications within containers in the POD.

**Describe the results you expected:**

We expect that the use of a POD and the port-handler would not be mutually exclusive.

**Output of `podman version`:**

```
podman version 3.4.4
```

We know that there is a newer version of podman.  It isn't yet available in Debian sid.

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 8
  distribution:
    codename: bullseye
    distribution: debian
    version: "11"
  eventLogger: journald
  hostname: floe
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 558752
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 558752
      size: 65536
  kernel: 5.10.0-3-amd64
  linkmode: dynamic
  logDriver: journald
  memFree: 394760192
  memTotal: 33646141440
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.4.0
  swapFree: 13597405184
  swapTotal: 17149456384
  uptime: 1960h 48m 39s (Approximately 81.67 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /a/gala/elf/home/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 4
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.10.3
        fuse-overlayfs: version 1.4
        FUSE library version 3.10.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/elf/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 106
  runRoot: /run/user/1000/containers
  volumePath: /home/elf/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Wed Dec 31 16:00:00 1969
  GitCommit: ""
  GoVersion: go1.17.5
  OsArch: linux/amd64
  Version: 3.4.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unstable,now 3.4.4+ds1-1 amd64 [installed]
podman/stable 3.0.1+dfsg1-3+b2 amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

[Yes]

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Nothing special.  This is running on Debian bullseye.

**Comment by mheon** [comment]
I assume it works with rootlesskit?

I'm assuming this is related to the shared network namespace; can you confirm that creating the two containers outside of a pod, but having one use `--net container=<ID>` to share the network namespace of the other, does not work?

@AkihiroSuda PTAL

**Comment by beewoolie** [comment]
The default port_handler is rootlesskit, so I expect that, yes, it is fine in this vase.

The example has only one container in a pod.  With the sample script, there isn't a meaningful way to perform the test you suggest.

However, you can use the sample script to verify that, without a pod, the port_handler change exhibits the behavior as documented.  This is described in the script as well.

**Comment by mheon** [comment]
Unless you are creating a pod without an infra container, there are at least 2 containers in the pod, and the one you created is sharing a network namespace with the infra container.

**Comment by beewoolie** [comment]
I am corrected. 

I create only one container in the pod, so I don't know how I could perform the test you suggest.

**Comment by Luap99** [comment]
Do you set --network on the container? If so this is incorrect, you should only use --network on the pod. If you also set it on the container you will overwrite the pod net namespace.

**Comment by beewoolie** [comment]
Excellent.  That seems to be the issue.  I guess I didn't try /all/ of the possible combinations.
