### ISSUE TITLE
Make pods stoppable using generated systemd units

### ISSUE THREAD

**Issue by jayache80** [containers/podman#13368]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

When using `podman-generate-systemd` with a pod, the systemd service units are generated "in isolation" and the user has no way to easily stop all containers once the pod is started.

It would be great if a "parent" unit is automatically generated that knows how to not only start all containers but also be able to stop all containers at once.

**Steps to reproduce the issue:**

1. Create a pod with several containers using `--infra=true`
1. Run `podman generate systemd <pod> --files --name` to generate systemd unit files.
1. Start the pod using the generated pod service unit file: `systemctl --user start <pod>.service`
1. Attempt to stop the containers by stopping the pod service unit: `systemctl --user stop <pod>.service`

**Describe the results you received:**
The pod becomes "degraded" and containers are still running after issuing the `systemctl --user stop <pod>.service`.

**Describe the results you expected:**
All containers are stopped when the pod service is stopped.

**Additional information you deem important (e.g. issue happens only occasionally):**

The desired behavior of this feature request can be obtained by manually creating a "parent" target unit that has `Requires` and `After` fields referencing the generated container and pod services, and amending the generated service units with `PartOf=<parent>.target`. It would be great if `podman` could generate something like that automatically if the user desired.

**Output of `podman version`:**

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.4
Git Commit:   f6526ada1025c2e3f88745ba83b8b461ca659933
Built:        Thu Dec  9 10:30:40 2021
OS/Arch:      linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman 3.4.4-1
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Comment by vrothberg** [comment]
Thanks for reaching out, @jayache80.

It already works.  The top-level `pod-xxx.service` unit does exactly what you are asking for.  If it doesn't work for you, please share an exact reproducer.

**Comment by rhatdan** [comment]
Is there a nice blog written up describing using Pods with systemd and Podman?

**Comment by vrothberg** [comment]
> Is there a nice blog written up describing using Pods with systemd and Podman?

There is no post dedicated to _pods_ only but I see where you are going :^)

**Comment by jayache80** [comment]
Thanks @vrothberg. It indeed was a combination of user error and perhaps not-fully-implemented features (or maybe even a bug) of `podman-compose`.

The following will work as expected and generates systemd unit files that are properly "grouped together" and can be stopped in concert by issuing a `stop` to the pod service alone:
```
# Create pod
podman pod create --infra=true --name foo

# Create containers and run them in the pod
podman run --name app -dt --pod foo docker.io/python
podman run --name web -dt --pod foo docker.io/nginx

# The pod will be running now, so let's stop it:
podman pod stop foo

# Generate systemd unit files
podman generate systemd foo --files --name
```

The service files generated from that look like this:
```
# pod-foo.service
# autogenerated by Podman 3.4.4
# Mon Feb 28 20:40:12 PST 2022

[Unit]
Description=Podman pod-foo.service
Documentation=man:podman-generate-systemd(1)
Wants=network-online.target
After=network-online.target
RequiresMountsFor=
Requires=container-app.service container-web.service
Before=container-app.service container-web.service

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
TimeoutStopSec=70
ExecStart=/usr/bin/podman start f1292dabc396-infra
ExecStop=/usr/bin/podman stop -t 10 f1292dabc396-infra
ExecStopPost=/usr/bin/podman stop -t 10 f1292dabc396-infra
PIDFile=/run/user/1000/containers/overlay-containers/e24a0d50b5666215946963a9219bb35b4f26f1ae75c1d09c151ea381f0155eab/userdata/conmon.pid
Type=forking

[Install]
WantedBy=default.target
```

```
# container-app.service
# autogenerated by Podman 3.4.4
# Mon Feb 28 20:40:12 PST 2022

[Unit]
Description=Podman container-app.service
Documentation=man:podman-generate-systemd(1)
Wants=network-online.target
After=network-online.target
RequiresMountsFor=/run/user/1000/containers
BindsTo=pod-foo.service
After=pod-foo.service

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
TimeoutStopSec=70
ExecStart=/usr/bin/podman start app
ExecStop=/usr/bin/podman stop -t 10 app
ExecStopPost=/usr/bin/podman stop -t 10 app
PIDFile=/run/user/1000/containers/overlay-containers/6ed0b973ec269542c7376eca7e302679f565cb292d703525b70884bf74513ada/userdata/conmon.pid
Type=forking

[Install]
WantedBy=default.target
```

```
# container-web.service
# autogenerated by Podman 3.4.4
# Mon Feb 28 20:40:12 PST 2022

[Unit]
Description=Podman container-web.service
Documentation=man:podman-generate-systemd(1)
Wants=network-online.target
After=network-online.target
RequiresMountsFor=/run/user/1000/containers
BindsTo=pod-foo.service
After=pod-foo.service

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
TimeoutStopSec=70
ExecStart=/usr/bin/podman start web
ExecStop=/usr/bin/podman stop -t 10 web
ExecStopPost=/usr/bin/podman stop -t 10 web
PIDFile=/run/user/1000/containers/overlay-containers/1c36d668d474366f427ccde2b344728c63bf1dc9d68bf30af34dabb2fe82ca1d/userdata/conmon.pid
Type=forking

[Install]
WantedBy=default.target
```

Notice that the units for the containers have `BindsTo` and `After` referencing `pod-foo.service` which are the "glue".

Where I went wrong before was when I was using `podman-compose` to create the pod and containers with a `foo.yaml` "compose" file like this:

```
version: "2.1"
services:
  app:
    image: docker.io/python
    container_name: app
    ports:
      - 5000:5000
  web:
    image: docker.io/nginx
    container_name: web
    ports:
      - 8080:80
```

Right off the bat, `podman-compose` doesn't yet support `infra=true` (and generating systemd unit files for a pod requires that the pod be created with `infra=true`) so I had to hack the script for that. Then, running:

    podman-compose -f foo.yaml -p foo up -d

will create the pod and containers just fine. Note that `podman-compose` makes the executive decision to name the pod based on the `-p` project argument and prepend it with `pod_`. I can easily start and stop the whole pod in concert with

    podman pod start pod_foo
    podman pod stop pod_foo

But when I generated systemd files using that pod:

    podman generate systemd pod_foo --files --name

I ended up with these:

```
# pod-pod_foo.service
# autogenerated by Podman 3.4.4
# Mon Feb 28 21:15:15 PST 2022

[Unit]
Description=Podman pod-pod_foo.service
Documentation=man:podman-generate-systemd(1)
Wants=network-online.target
After=network-online.target
RequiresMountsFor=
Requires=container-app.service container-web.service
Before=container-app.service container-web.service

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
TimeoutStopSec=70
ExecStart=/usr/bin/podman start caf63e041bfc-infra
ExecStop=/usr/bin/podman stop -t 10 caf63e041bfc-infra
ExecStopPost=/usr/bin/podman stop -t 10 caf63e041bfc-infra
PIDFile=/run/user/1000/containers/overlay-containers/3e02551e71997ec7739d62405961a6761bbad34e73e7a348f6434330bd5a58bd/userdata/conmon.pid
Type=forking

[Install]
WantedBy=default.target
```

```
# container-app.service
# autogenerated by Podman 3.4.4
# Mon Feb 28 21:15:15 PST 2022

[Unit]
Description=Podman container-app.service
Documentation=man:podman-generate-systemd(1)
Wants=network-online.target
After=network-online.target
RequiresMountsFor=/run/user/1000/containers

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
TimeoutStopSec=70
ExecStart=/usr/bin/podman start app
ExecStop=/usr/bin/podman stop -t 10 app
ExecStopPost=/usr/bin/podman stop -t 10 app
PIDFile=/run/user/1000/containers/overlay-containers/1ab907341ee16531bace29b1ba64031f31eae0b21edbd9b60c5be6eb0af43c42/userdata/conmon.pid
Type=forking

[Install]
WantedBy=default.target
```

```
# container-web.service
# autogenerated by Podman 3.4.4
# Mon Feb 28 21:15:15 PST 2022

[Unit]
Description=Podman container-web.service
Documentation=man:podman-generate-systemd(1)
Wants=network-online.target
After=network-online.target
RequiresMountsFor=/run/user/1000/containers

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
TimeoutStopSec=70
ExecStart=/usr/bin/podman start web
ExecStop=/usr/bin/podman stop -t 10 web
ExecStopPost=/usr/bin/podman stop -t 10 web
PIDFile=/run/user/1000/containers/overlay-containers/116a9f7f05750d890dbff368dcfe3e28b0157c848ca9cc42df925d35c9954652/userdata/conmon.pid
Type=forking

[Install]
WantedBy=default.target
```

Because the units for the containers aren't properly referencing the "parent" `foo` pod, the entire pod and its containers aren't easily stoppable with systemd alone. I'll discuss this with the `podman-compose` maintainer.

Thanks again. Closing.
