### ISSUE TITLE
What's the podman equivalent of Docker's `volume-opt` parameter in mount strings?

### ISSUE THREAD

**Issue by rhatdan** [containers/podman#13387]
### Discussed in https://github.com/containers/podman/discussions/13378

<div type='discussions-op-text'>

<sup>Originally posted by **dstaley** February 28, 2022</sup>
I'm trying to translate the following `--mount` string from Docker to podman:

```
"src=services,dst=/services,volume-opt=device=:/volume3/Services,\"volume-opt=o=addr=ganymede.localdomain,vers=3,soft\",type=volume,volume-driver=local,volume-opt=type=nfs"
```

When running a container with this mount string, I get the error:

```
Error: volume-opt: invalid mount option
```

I understand that the options passed to `--mount` are basically parsed out and passed to the OS's underlying `mount` command, so I assume that `volume-opt` isn't getting translated to whatever it needs to be for `mount` to understand it.

I've seen a few sample commands that create volumes using `--opt`, however I don't see anything like that in the [docs](https://docs.podman.io/en/latest/markdown/podman-run.1.html#mount-type-type-type-specific-option) for the `--mount` argument.</div>

**Comment by rhatdan** [comment]
@flouthoc PTAL

**Comment by rhatdan** [comment]
@flouthoc have you had a chance to look at this?

**Comment by flouthoc** [comment]
@rhatdan Above PR should close this. I am wondering why is this not documented by docker.
