### ISSUE TITLE
[Question] How to let podman use the local image

### ISSUE THREAD

**Issue by jianzhangbjz** [containers/podman#13400]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

/kind feature

**Description**

**Steps to reproduce the issue:**

1. There is `registry:2.7.0` image in the local.
```yaml
[cloud-user@preserve-olm-env ~]$ podman images|grep -E 'registry.*2.7.0'
docker.io/library/registry                                                                       2.7.0            33fbbf4a24e5  3 years ago    24.8 MB
```
2. But, podman still pulls it from the remote registry. My question is how to let podman use the local image, thanks!
```yaml
[cloud-user@preserve-olm-env jian]$ podman run -d --name registry_native_auth -p 5000:5000 -v /data/jian/auth:/auth -e "REGISTRY_AUTH=htpasswd" -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd -v /data/jian/certs:/certs -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt -e REGISTRY_HTTP_TLS_KEY=/certs/domain.key --privileged registry:2.7.0
Resolved "registry" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/registry:2.7.0...
WARN[0030] failed, retrying in 1s ... (1/3). Error: initializing source docker://registry:2.7.0: reading manifest 2.7.0 in docker.io/library/registry: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit 
...
```

3.

**Describe the results you received:**
Podman stills pull the remote image even if it exists in the local.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
[cloud-user@preserve-olm-env ~]$ podman version
Version:      3.0.2-dev
API Version:  3.0.0
Go Version:   go1.15.13
Built:        Tue Jun  8 03:52:06 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by flouthoc** [comment]
@jianzhangbjz I think `podman run --pull missing ... ... ` should solve your use-case ? It will pull only if `image` is missing from the `local` store.

**Comment by vrothberg** [comment]
There is something else going on.

@jianzhangbjz, if possible, please share the _entire_ requested information, especially `podman info --debug`.

**Comment by vrothberg** [comment]
Thanks, @jianzhangbjz.  `podman info` looks good.  Could you rerun with `podman --log-level=debug` and share that output?

**Comment by vrothberg** [comment]
@jianzhangbjz, the logs indicate that the image has not been found in the local storage.

Could it be that the `podman images` is executed as the rootless user but the container is run with `sudo` (i.e., rootless)?

**Comment by jianzhangbjz** [comment]
@vrothberg Yes, I think so, thanks for your checking. Close it.

**Comment by vrothberg** [comment]
Glad we could resolve the issue, @jianzhangbjz.
