### ISSUE TITLE
When will you release v4 binaries (ie v4.0.2) ?

### ISSUE THREAD

**Issue by jradxl** [containers/podman#13407]
When will you release v4 binaries (ie v4.0.2) to this repository, in my case for Ubuntu 21.10

`https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman`

Or am I looking in the wrong place?

```
REF Your documentation:
https://podman.io/getting-started/installation
CAUTION: On Ubuntu 20.10 and newer, we highly recommend you use Buildah, Podman and Skopeo ONLY from EITHER the Kubic repo OR the official Ubuntu repos
```

**Comment by afbjorklund** [comment]
Possibly never:

* https://github.com/containers/podman/issues/13302

See also:

https://packages.ubuntu.com/impish/podman (3.2.1)

**Comment by vrothberg** [comment]
@lsm5 PTAL

**Comment by lsm5** [comment]
@jradxl what @afbjorklund said.

Let me also copy @benridley and @bbalp (I'm reusing your gitlab ids so apologies if you're not the right people) . They are working on https://gitlab.com/benridley/podman-deb and perhaps you or anyone else interested can reach out there and help out.

Closing ...

**Comment by lsm5** [comment]
I will update the podman docs.

**Comment by lsm5** [comment]
> Possibly needs an updated blog post about it: https://podman.io/blogs/2021/03/02/podman-support-for-older-distros.html

@afbjorklund wip blog post for v4.0 is happening at https://github.com/containers/podman/pull/13310

**Comment by afbjorklund** [comment]
As far as I know, the system packages will stay at the current versions:

Ubuntu | Podman
--- | ---
20.04 | ---
21.04 | 3.0
21.10 | 3.2
22.04 | 3.4


And then it is up to third parties, to supply the packaging for Podman 4.
