### ISSUE TITLE
error while loading shared libraries: librt.so.1: cannot change memory protections

### ISSUE THREAD

**Issue by EdDev** [containers/podman#13401]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
When changing the storage location for graphroot (in `/etc/containers/storage.conf`) to a path under `/var/run/...`, a permission error is raised.

Following the documentation/[troubleshooting](https://github.com/containers/podman/blob/main/troubleshooting.md#11-changing-the-location-of-the-graphroot-leads-to-permission-denied) instructions, did not help.

I'm running this on RHEL 8.5 (kernel 4.18.0-348.12.2.el8_5.x86_64) with podman version 3.4.2.

**Steps to reproduce the issue:**

1. Change graphroot in the configuration file to: `graphroot = "/var/run/podman/containers/storage`

2. Label content:
```
sudo semanage fcontext -a -e /var/lib/containers /var/run/podman/containers/storage
sudo restorecon -R -v /var/run/podman/containers/storage
```

3. Run a container: `sudo podman run -ti --rm centos:stream8`

**Describe the results you received:**
`/usr/bin/coreutils: error while loading shared libraries: librt.so.1: cannot change memory protections`

Output from `$ sudo ausearch -m avc -ts recent`:
```
----
time->Wed Mar  2 11:17:03 2022
type=PROCTITLE msg=audit(1646212623.548:854): proctitle=2F7573722F62696E2F636F72657574696C73002D2D636F72657574696C732D70726F672D73686562616E673D6C73002F7573722F62696E2F6C73002D6C61
type=SYSCALL msg=audit(1646212623.548:854): arch=c000003e syscall=10 success=no exit=-13 a0=7fbadd925000 a1=1ff000 a2=0 a3=2 items=0 ppid=65638 pid=65650 auid=27630 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=3 comm="ls" exe="/usr/bin/coreutils" subj=system_u:system_r:container_t:s0:c631,c968 key=(null)
type=AVC msg=audit(1646212623.548:854): avc:  denied  { read } for  pid=65650 comm="ls" path="/usr/lib64/librt-2.28.so" dev="tmpfs" ino=1263636 scontext=system_u:system_r:container_t:s0:c631,c968 tcontext=unconfined_u:object_r:var_run_t:s0 tclass=file permissive=0
----
time->Wed Mar  2 11:25:27 2022
type=PROCTITLE msg=audit(1646213127.957:889): proctitle="/bin/bash"
type=SYSCALL msg=audit(1646213127.957:889): arch=c000003e syscall=10 success=no exit=-13 a0=7f2a4a1a5000 a1=1ff000 a2=0 a3=2 items=0 ppid=66354 pid=66367 auid=27630 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=3 comm="bash" exe="/usr/bin/bash" subj=system_u:system_r:container_t:s0:c125,c570 key=(null)
type=AVC msg=audit(1646213127.957:889): avc:  denied  { read } for  pid=66367 comm="bash" path="/usr/lib64/libtinfo.so.6.1" dev="tmpfs" ino=1247673 scontext=system_u:system_r:container_t:s0:c125,c570 tcontext=unconfined_u:object_r:var_run_t:s0 tclass=file permissive=0
```

**Describe the results you expected:**
No errors.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.7
Built:        Thu Jan 13 12:15:49 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.32-1.module+el8.5.0+13852+150547f7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.32, commit: 4b12bce835c3f8acc006a43620dd955a6a73bae0'
  cpus: 12
  distribution:
    distribution: '"rhel"'
    version: "8.5"
  eventLogger: file
  hostname: myname.tlv.csb
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-348.12.2.el8_5.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 53391048704
  memTotal: 67079102464
  ociRuntime:
    name: runc
    package: runc-1.0.3-1.module+el8.5.0+13556+7f055e70.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.3
      spec: 1.0.2-dev
      go: go1.16.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.5.0+12582+56d94c81.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 33709617152
  swapTotal: 33709617152
  uptime: 25h 45m 41.14s (Approximately 1.04 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/run/podman/containers/storage
  graphStatus:
    Backing Filesystem: tmpfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/run/podman/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 1642068949
  BuiltTime: Thu Jan 13 12:15:49 2022
  GitCommit: ""
  GoVersion: go1.16.7
  OsArch: linux/amd64
  Version: 3.4.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.2-9.module+el8.5.0+13852+150547f7.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

I checked with the [troubleshooting guide](https://github.com/containers/podman/blob/main/troubleshooting.md#11-changing-the-location-of-the-graphroot-leads-to-permission-denied), but the issues is not resolved when applying the labeling instructions.
Not tested with a newer version of podman.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine (laptop).

**Comment by rhatdan** [comment]
Could you try
sudo semanage fcontext -a -e /var/lib/containers /run/podman/containers/storage
sudo restorecon -R -v /run/podman/containers/storage

The /var/run is ignored and is a symbolic link to /run.

You should see a lot of changes when you run the resorecon.

**Comment by EdDev** [comment]
That was my first try and it gave me this error:
`$ sudo semanage fcontext -a -e /var/lib/containers /run/podman/containers/storage
ValueError: File spec /run/podman/containers/storage conflicts with equivalency rule '/run /var/run'; Try adding '/var/run/podman/containers/storage' instead`

**Comment by EdDev** [comment]
Ok, this one worked:
```
sudo mkdir /volatile
sudo mount -t tmpfs -o size=32G tmpfs /volatile
sudo vim /etc/containers/storage.conf 
sudo mkdir -p /volatile/podman/containers/storage
sudo semanage fcontext -a -e /var/lib/containers /volatile/podman/containers/storage
sudo restorecon -R -v /volatile/podman/containers/storage
```
Output: `Relabeled /volatile/podman/containers/storage from unconfined_u:object_r:user_tmp_t:s0 to unconfined_u:object_r:container_var_lib_t:s0`

**Comment by EdDev** [comment]
@rhatdan , is this suppose to work with `rootless_storage_path` as well?

I tried the equivalent, but it does not work. Giving me this error:
`Error: writing blob: adding layer with blob "sha256:ce419f530850a57ffb757cd9dfc06b6645124d63f1c15459ec799d0555815f77": Error processing tar file(exit status 1): operation not supported`.

This does not seem to be SELinux related.

Should I open a different issue to raise this?

**Comment by rhatdan** [comment]
Well are you sure this is not SELinux?  Run a container in permissive mode.

**Comment by EdDev** [comment]
I’m sure. I set it to permissive and it had no effect.

Another strange thing I noticed is that trying to delete the folder without ‘sudo’ fails as well. (rm -rf …)
But the owner is the right user. Very strange.

**Comment by rhatdan** [comment]
I think I would reboot your machine and start over.  Operation not supported seems strange.

**Comment by EdDev** [comment]
I rebooted several times already.
The followed the following procedure, but it fails the same every-time:
```
USER_VOLATILE="$HOME/.volatile"
mkdir -p $USER_VOLATILE
sudo mount -t tmpfs -o size=32G tmpfs $USER_VOLATILE
mkdir -p $USER_VOLATILE/podman/containers/storage
sudo semanage fcontext -a -e $HOME/.local/share/containers $USER_VOLATILE/podman/containers/storage
sudo restorecon -R -v $USER_VOLATILE/podman/containers/storage
podman run -ti --rm centos:stream8
```

Outcome is:
```
Resolved "centos" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull quay.io/centos/centos:stream8...
Getting image source signatures
Copying blob 73797a02aeb8 done  
Copying blob f36484499d9d done  
Copying blob d3b93ca88f5c done  
Copying blob ce419f530850 done  
Error: writing blob: adding layer with blob "sha256:ce419f530850a57ffb757cd9dfc06b6645124d63f1c15459ec799d0555815f77": Error processing tar file(exit status 1): operation not supported
```

It worth mentioning that stuff did got in that path, but something is not allowing modifying things at some point.

**Comment by 0xFelix** [comment]
It could have something todo with this bug https://github.com/containers/buildah/issues/1709

When running your setup with vfs as storage driver it works for me.

```
podman system reset
podman run --storage-driver=vfs -ti --rm centos:stream8
```

**Comment by EdDev** [comment]
It seems that if the storage path is changed for rootless containers on RHEL8, things stop working.
With @0xFelix tip above, I managed to explicitly set `mount_program = "/usr/bin/fuse-overlayfs"` and from here on it started working.

I think this is a workaround, not a solution.

Regarding the original problem of this issue, It will be nice to update the manual to reflect the results seen here.
