### ISSUE TITLE
Podman 4.0.2 MSI bundled dependency detected as a threat by antivirus

### ISSUE THREAD

**Issue by albertdb** [containers/podman#13415]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Trying to install Podman 4.0.2 on Windows results in:

![image](https://user-images.githubusercontent.com/11670727/156571839-36cfb40e-874a-43a9-9c3c-2cf72e28e081.png)

![image](https://user-images.githubusercontent.com/11670727/156571794-d4432511-bfb9-48ea-8a07-d2d8f2de7133.png)

**Steps to reproduce the issue:**

1. Have CloudStrike Falcon Sensor antivirus (maybe other shows the same behavior)

2. Run Podman 4.0.2 MSI.

**Describe the results you received:**

Installer failing

**Describe the results you expected:**

Podman installed.

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Comment by albertdb** [comment]
Side question: podman-remote-client bundles podman machine?

**Comment by rhatdan** [comment]
@n1hility PTAL

**Comment by n1hility** [comment]
@albertdb does this happen with older podman msi releases or just 4.0.2?

**Comment by albertdb** [comment]
> @albertdb does this happen with older podman msi releases or just 4.0.2?

Just 4.0.2

**Comment by n1hility** [comment]
@albertdb Are you running the latest version and virus definitions? The CrowdStrike Falcon scanner that runs as part of VirusTotal.com, which its supposed to be always current, does not pick it up.

Another idea to try is a version built with go 1.16, golang executable do often trip up virus scanners requiring allow listing.

I built one for you if you want to try here in case you don't have a linux build setup:
https://github.com/n1hility/podman-builds/blob/main/podman-v4.0.2-jason.msi?raw=true

sha1sum is:
bf0a19292db97dfe4c9f18418b28888a9182bba2  podman-v4.0.2-jason.msi

**Comment by albertdb** [comment]
> @albertdb Are you running the latest version and virus definitions? The CrowdStrike Falcon scanner that runs as part of VirusTotal.com, which its supposed to be always current, does not pick it up.
> 
> Another idea to try is a version built with go 1.16, golang executable do often trip up virus scanners requiring allow listing.
> 
> I built one for you if you want to try here in case you don't have a linux build setup: https://github.com/n1hility/podman-builds/blob/main/podman-v4.0.2-jason.msi?raw=true
> 
> sha1sum is: bf0a19292db97dfe4c9f18418b28888a9182bba2 podman-v4.0.2-jason.msi

Same happens with that binary. Version 6.34.14806 and latest definitions.

**Comment by n1hility** [comment]
@albertdb ok thanks. Perhaps their ML engine isn’t used in their virustotal report and that’s why it checks out ok. I’ll send a false positive report to their contact email. If you have a support contract with them you might be able to get a faster response via a bug report / issue. If you have the ability to alter the config / policy they should have an exemption setting you might be able to use to work around this.

**Comment by n1hility** [comment]
@albertdb I took a look at contacting them to report the false positive but it looks like only customers can do so unless it shows up on VirusTotal. Skimming the docs I can see it looks like their ML engine has a tuning parameter for how paranoid it is when detecting whether an executable is malicious so I suspect this is why it happens for you and not on VT. Not sure if you have the ability to tune settings (or if these are managed by an IT org), but if so you could try reducing the aggressiveness and/or adding an exemption rule (supposedly have a way to generate an exemption rule off of a detection/quarantine event).

**Comment by Luap99** [comment]
Closing, feel free to continue the discussion here.
