### ISSUE TITLE
rootless podman internal GID is one higher than external user sometimes

### ISSUE THREAD

**Issue by jahamilton12121** [containers/podman#13419]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Sometimes the gid map inside of the user is one more than it should be. Sometimes it will work as expected
For ex it will be correctly set to 30000 sometimes 
```
su -s /bin/bash - myuser -c "podman unshare cat /proc/self/gid_map"
         0      30000          1
         1     165536      65536
```

Other times it will be 30001
```
su -s /bin/bash - myuser -c "podman unshare cat /proc/self/gid_map"
         0      30001          1
         1     165536      65536
```

**Steps to reproduce the issue:**

1. I am creating users with `/usr/sbin/adduser --shell /usr/sbin/nologin --gid 30000 --gecos "" --disabled-password myuser`

2. I create a container `/usr/bin/su -s /bin/bash - username -c "podman load --input image.tar.gz"`

**Describe the results you received:**
```
su -s /bin/bash - myuser -c "podman unshare cat /proc/self/gid_map"
         0      30001          1
         1     165536      65536
```

**Describe the results you expected:**
```
su -s /bin/bash - myuser -c "podman unshare cat /proc/self/gid_map"
         0      30000          1
         1     165536      65536
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue only happens occasionally

**Output of `podman version`:**

```
podman version 3.2.1
```

**Output of `podman info --debug`:**
I dont want to put all of the info here
```
arch: amd64
  buildahVersion: 1.21.3
 GoVersion: go1.13.8
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 3.2.1+ds1-2ubuntu2
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Modified version of ubuntu

**Comment by giuseppe** [comment]
could you share the output of `id` when the issue happens (`su -s /bin/bash - myuser -c "id; podman unshare cat /proc/self/gid_map"`)?

**Comment by vrothberg** [comment]
@jahamilton12121, friendly ping.

**Comment by jahamilton12121** [comment]
I am trying to get another user to demonstrate this however it only happens infrequently. The project I am working on creates and removes users frequently.

**Comment by jahamilton12121** [comment]
```
user@machine$ id
uid=1009(myuser) gid=40000(mygroup) groups=40000(mygroup)
```

```
user@machine$ ps -o uid,gid -p $(pidof process_podman_is_running)
  UID   GID
 1009 40001
```

**Comment by giuseppe** [comment]
could it be a race condition?

What was the first session that created the podman pause process?  e.g. was it running in a separate ssh session?

rootless podman cannot use any GID it wishes to, newgidmap would not allow using a gid if it not already allocated to the user.

what is the parent process of `catatonit -P` process that keeps the rootless user namespace alive and what is its UID/GID?

**Comment by giuseppe** [comment]
I am closing this issue since I don't see how it could be caused by Podman.  Podman runs as unprivileged user and it cannot change its UID/GID (except to the ones configured in `/etc/sub?id` through the newuidmap/newgidmap tools).

Please add more comments and we try to help debug what is going on

**Comment by jahamilton12121** [comment]
@giuseppe I have it set up so the user and podman containers are created by a systemd job running a single threaded python script and not initiated by ssh sessions/direct user input. Basically it creates a user, then loads a podman image inside of it, then a new systemd job will load podman run inside the user.

Creating a user
```
cmd = shlex.split(f'/usr/sbin/adduser --shell /usr/sbin/nologin --gid {gid} --gecos "" --disabled-password {username}')
```

How I load the container image inside the user. (the image is copied from root into the user directory and chown is ran on it `chown {username} {tmp_image}`)
```
cmd = ["podman", "load", "--input", tmp_image]
cmd = ["/usr/bin/su", "-s", "/bin/bash", "-", username, "-c"] + [" ".join(cmd)]
```

snippet of start script that new systemd job will run
```
su -s /bin/bash - {username} -c "podman run --network=host -d --restart on-failure --log-opt=path=${{LOG}} --log-driver=journald --name {name} ${{ENV}} --conmon-pidfile=${{PID_FILE}} {name}"
```

Another design element is that some GIDs are supposed to be 40000 and some are 40001. The issue of this post is that somehow a user which is correctly assigned GID 40000, has its podman process be 40001 which is a rare occurrence but will break some things.

> what is the parent process of catatonit -P process that keeps the rootless user namespace alive and what is its UID/GID?
How do I find this? `catatonit -P` isn't a command on my system.

**Comment by jahamilton12121** [comment]
Also I have two users with different names that run the same image. These users are the only ones that are problematic
```
$ ps -e -o pidns,pid,args
29153 ./binaryfile
27708 ./binaryfile
```
```
$ ps -o gid 29153
  GID
40000
$ ps -o gid 27708
  GID
40001
```

**Comment by jahamilton12121** [comment]
```
root@machine:~# su -s /bin/bash - name-thing -c "podman unshare cat /proc/self/gid_map"
         0      40001          1
         1     231072      65536
root@machine:~# su -s /bin/bash - name -c "podman unshare cat /proc/self/gid_map"
         0      40000          1
         1     296608      65536
root@machine:~# su -s /bin/bash - name-thing -c "id"
uid=1010(name-thing) gid=40000(group_0) groups=40000(group_0)

root@machine:~# su -s /bin/bash - name -c "id"
uid=1011(name) gid=40000(group_0) groups=40000(group_0)
```

**Comment by giuseppe** [comment]
can you share the content of `/etc/passwd` and `/etc/group` when that happens (at least the portion for `name` and `name-thing`)?

**Comment by jahamilton12121** [comment]
```
root@machine# su -s /bin/bash - name-thing -c "podman unshare cat /proc/self/gid_map"
         0      40001          1
         1     231072      65536

root@machine# cat /etc/passwd | grep "name"
name-thing:x:1010:40000:,,,:/home/name-thing:/usr/sbin/nologin
name:x:1011:40000:,,,:/home/name:/usr/sbin/nologin

root@machine# cat /etc/group
group_0:x:40000:
group_1:x:40001:
```

**Comment by jahamilton12121** [comment]
@giuseppe After testing a reproduction script for a while it seems it only happens when the virtual machine undergoes a custom ssd reset which deletes several things. The service files to the systemd jobs are removed but the jobs themselves can stay running. Users are not affected and the container keeps running. But I have a script which will remove them after a reset

Currently this happens:
reset which removes service and script files instantly but containers are still running fine
a script detects reset and begins to remove the containers with podman rm and then stops systemd jobs and removes service file, and then forcibly removes users.
 _About 3 minutes later (well after removal and reset stuff)_
name-thing is installed
name is installed
othername is installed

I didn't realize at first but othername has incorrect GID as well. it is supposed to have gid 40001 and instead has the name-thing's GID of 40000. Like they switched. When running "id" on both, they both have the correct respective id's of 40000 for name-thing and 40001 for othername. "name" which is basically the same as "name-thing" has the correct gid in this specific instance but in other repros it is the opposite. Other repros can be just one that is wrong as well. They do not have to switch. I have never seen a GID out of the range of 40000 to 40001. Those are the only GIDs that are ever assigned though more groups with GIDs do exist above that number.

**Comment by jahamilton12121** [comment]
I forgot to mention, a reboot fixes the GID issue. Just leaving everything as is and rebooting without doing anything else

**Comment by rhatdan** [comment]
The 40001 is the GID of the "othername" user, so yes this is normal.

**Comment by jahamilton12121** [comment]
I mean 231072      296608     362144

**Comment by rhatdan** [comment]
Yes these come from the /etc/subgid files for each user. useradd automatically generates them.

**Comment by jahamilton12121** [comment]
More information, I can repro without doing a reset and just uninstalling and reinstalling. I uninstall all 3 agents in synchronously and reinstall about 60 seconds after the last one is finished being removed. The issue doesn't seem to happen when alternating the uninstall and reinstall.

**Comment by jahamilton12121** [comment]
uninstall process: `systemctl stop jobname` -> remove service file and script file -> remove podman container then image -> remove user. 
```
def remove_image(name, username, image_name):
        try:
            cmd = [PodmanCommand.podman, "rm", "--force", name]
            cmd = ["/usr/bin/su", "-s", "/bin/bash", "-c"] + [" ".join(cmd)] + ["-", f"{username}"]
            run_command(cmd)
        except Exception as e:
            logger.error(f"remove container failed with exception {e}")
        # as we are using podman tagging, we need to remove all tags
        try:
            images = _get_images_by_name(image_name)
            cmd = [PodmanCommand.podman, "rmi", "--force"] + images
            cmd = ["/usr/bin/su", "-s", "/bin/bash", "-c"] + [" ".join(cmd)] + ["-", f"{username}"]
            run_command(cmd)
        except Exception as e:
            logger.error(f"remove image failed with exception {e}")
```

remove user
```
f"/usr/sbin/userdel -f -r {username}"
```

**Comment by jahamilton12121** [comment]
UPDATE: If I kill podman pause before removing the user then I no longer run into this issue. I believe it is an issue with podman and not my code.

**Comment by giuseppe** [comment]
when you delete the user, you also need to ensure all its processes are terminated.  Otherwise, you reuse the UID/GID for a different user causing a potential security issue.
