### ISSUE TITLE
Rootless podman and authbind

### ISSUE THREAD

**Issue by wh6b** [containers/podman#13426]
**BUG REPORT**

/kind bug

**Description**
Hello all, podman rootless container wont bind to port 80 with authbind configured while it works with another commands like python3 -m http.server 80
I dont want use ip_unprivileged_port_start (I just need to exposed few ports) to or firewall rules (I use firewalld and local processes dont follow firewalld port forwarding without adding iptables/nft rules in parrallel, no process attached to port with netstat)
Is it podman internals which refuse to bind before trying it or some podman specificity ?

**Steps to reproduce the issue:**
1. ```touch /etc/authbind/byport/80```
2. ```chown debian /etc/authbind/byport/80```
3. ```chmod 700 /etc/authbind/byport/80```
4. ```authbind podman run -d -p 80:80 docker.io/traefik/whoami```
or
5. ```authbind --deep podman run -d -p 80:80 docker.io/traefik/whoami```

**Describe the results you received:**
```Error: rootlessport cannot expose privileged port 80, you can add 'net.ipv4.ip_unprivileged_port_start=80' to /etc/sysctl.conf (currently 1024), or choose a larger port number (>= 1024): listen tcp 0.0.0.0:80: bind: permission denied```

**Describe the results you expected:**
run this container on port 80 as expected

**Additional information you deem important (e.g. issue happens only occasionally):**
It works well with others softwares like python's http.server
```authbind python3 -m http.server 80```

**Output of `podman version`:**
Debian 11 podman by apt
```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.9
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**
```
host:
  arch: amd64
  buildahVersion: 1.19.6
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 4
  distribution:
    distribution: debian
    version: "11"
  eventLogger: journald
  hostname: dev-1
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.10.0-11-amd64
  linkmode: dynamic
  memFree: 3324760064
  memTotal: 4121751552
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.4.0
  swapFree: 1022357504
  swapTotal: 1022357504
  uptime: 6m 59.49s
registries:
  docker.io:
    Blocked: false
    Insecure: false
    Location: docker.io
    MirrorByDigestOnly: false
    Mirrors:
    - Insecure: false
      Location: docker.mirrors.ustc.edu.cn
    Prefix: docker.io
  search:
  - docker.io
store:
  configFile: /home/debian/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.10.3
        fuse-overlayfs: version 1.4
        FUSE library version 3.10.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/debian/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1001/containers
  volumePath: /home/debian/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.9
  OsArch: linux/amd64
  Version: 3.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**
```
Listing... Done
podman/stable,now 3.0.1+dfsg1-3+b2 amd64 [installed]
```
**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**
Yes

**Comment by Luap99** [comment]
From http://manpages.ubuntu.com/manpages/trusty/man1/authbind.1.html
> if  the  program  doesn't  already  have  an  effective uid of 0

Rootless podman will always run in a userns namespace with your user mapped to root, so the euid is always 0.
Also since podman runs in the user namespace the setuid authbind program will not work correctly because the hosts root is not mapped into this namespace.

I don't think authbind can work correctly with "newer" kernel features. It looks to me that authbind was written before namespaces and capabilities existed.

I think redirecting the ports via firewall is the best solution.

**Comment by djarbz** [comment]
@Luap99 would the "Docker" solution work provided [here](https://docs.docker.com/engine/security/rootless/#exposing-privileged-ports) as an alternative?

`sudo setcap cap_net_bind_service=ep $(which rootlesskit)`

If my understanding of setcap is correct, we would need to reapply this whenever the rootlesskit binary was updated?

**Comment by Luap99** [comment]
Podman does not use the rootlesskit binary. Podman 4.0 added a rootlessport binary to /usr/libexec/podman/rootlessport where this might work but I do not know.

**Comment by djarbz** [comment]
Ahh rootlessport, I thought that seemed familiar, so I figured I'd ask.
I might give this a try in a dev environment.

**Comment by rhatdan** [comment]
Adding a File Capability requires approval of the distributions. We would need to get multiple distributions to agree to allow a new program with file caps to be installed, if we did this in Podman.

**Comment by djarbz** [comment]
@rhatdan I would think that this would be best left up to the server administrator. I'm sure they wouldn't want just any user to be able to bind to any low level port.

**Comment by rhatdan** [comment]
Sure if you want to document how to do this, I am fine with that.  If it happens by default, is where I have a problem.

**Comment by djarbz** [comment]
Yeah, I would not want that to happen by default in a rootless environment.

**Comment by djarbz** [comment]
For anyone that finds this in the future, I could not get this to work. With my research, it is because rootlessport is executed in a user namespace.

`sudo setcap cap_net_bind_service=+ep /usr/libexec/podman/rootlessport`
