### ISSUE TITLE
podman-v4.0.2.msi issues

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman#13434]
This may be me just having issues with Windows, but when running Podman on Windows after installing the 4.2 msi, I'm seeing 

A complaint about /tmpfs, which I wasn't able to make happy using the `--tmpfs` option.  I get the same error with or without the `--tmpfs`.

```
PS C:\Users\sween> podman run --tmpfs=mytmpfs ubi8-micro date
time="2022-03-05T19:51:45-05:00" level=warning msg="Failed to retrieve default tmp dir: invalid image_copy_tmp_dir value \"/var/tmp\" (relative paths are not accepted)"
Error: invalid container path "mytmpfs", must be an absolute path
```

Then when I try to use the `-d` option, the container runs until I try to exec into it and it appears to drop into a "Created" rather than "Up" state:

```
PS C:\Users\sween>  podman run -d --privileged --name myctr  -v mycontainers:/var/lib/containers quay.io/podman/stable:v3.3.1 sleep 600
time="2022-03-05T19:53:06-05:00" level=warning msg="Failed to retrieve default tmp dir: invalid image_copy_tmp_dir value \"/var/tmp\" (relative paths are not accepted)"
7760294587b7f17f930e95d7fa95c08b631f689ea442d3e48e7449277c3644b8

PS C:\Users\sween> podman ps
time="2022-03-05T19:53:15-05:00" level=warning msg="Failed to retrieve default tmp dir: invalid image_copy_tmp_dir value \"/var/tmp\" (relative paths are not accepted)"
CONTAINER ID  IMAGE                         COMMAND     CREATED        STATUS            PORTS       NAMES
7760294587b7  quay.io/podman/stable:v3.3.1  sleep 600   9 seconds ago  Up 9 seconds ago              myctr

PS C:\Users\sween> podman exec -it myctr /bin/sh
time="2022-03-05T19:53:42-05:00" level=warning msg="Failed to retrieve default tmp dir: invalid image_copy_tmp_dir value \"/var/tmp\" (relative paths are not accepted)"
Error: can only create exec sessions on running containers: container state improper

PS C:\Users\sween> podman ps
time="2022-03-05T19:53:47-05:00" level=warning msg="Failed to retrieve default tmp dir: invalid image_copy_tmp_dir value \"/var/tmp\" (relative paths are not accepted)"
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES

PS C:\Users\sween> podman ps -a
time="2022-03-05T19:55:21-05:00" level=warning msg="Failed to retrieve default tmp dir: invalid image_copy_tmp_dir value \"/var/tmp\" (relative paths are not accepted)"
CONTAINER ID  IMAGE                                         COMMAND     CREATED        STATUS                    PORTS       NAMES
7760294587b7  quay.io/podman/stable:v3.3.1                  sleep 600   2 minutes ago  Created                               myctr
```

Finally, this is almost definitely me, I could not find `containers.conf`, is there a location for it on Windows?

**Comment by TomSweeneyRedHat** [comment]
And fwiw, if I don't use the `-d` option and then open a new window, I can exec into the container without issue.

@n1hility @baude @ashley-cui any thoughts?

**Comment by n1hility** [comment]
@TomSweeneyRedHat Sorry I have been meaning to but haven’t gotten around to fixing that tmp warning yet. It should be a small patch to common. The containers.conf is in your windows users home under AppData\Roaming\containers\containers.conf 

The other container state issue I had not run into yet. Does it happen when using —remote on Linux or Mac?

**Comment by peerasan** [comment]
I also face the issue on Windows 11.  I wonder if is it effect to usage or not?   or just annoy message.

```
podman run busybox date
time="2022-03-06T11:34:08+07:00" level=warning msg="Failed to retrieve default tmp dir: invalid image_copy_tmp_dir value \"/var/tmp\" (relative paths are not accepted)"
Sun Mar  6 04:34:08 UTC 2022
```

**Comment by n1hility** [comment]
@peerasan it’s harmless just annoying. You should be able  override the config setting to make it go away.

**Comment by TomSweeneyRedHat** [comment]
@n1hilty I'm not able to get qemu to standup on my Fedora system, it could be user error.  I don't have a mac to test with.

**Comment by TomSweeneyRedHat** [comment]
and just to be sure, I'm using version 6.1.0 of qemu on Fedora, IDK if that might be part of the problem or not.

**Comment by TomSweeneyRedHat** [comment]
reopening.  The fix took care of the tmpdir issue, but the `podman run -d` not working is still present.

**Comment by n1hility** [comment]
@TomSweeneyRedHat I briefly tried mac today with 4.0.2 and it did not happen there, so probably is win specific. I'll take a look and see what's going on

**Comment by n1hility** [comment]
Finally got a chance to try it out and it works for me, although there is a tty warning I need to look into.
```
PS C:\Users\jason> podman exec -it myctr /bin/sh
time="2022-03-09T23:35:52-06:00" level=warning msg="Failed to obtain TTY size: The handle is invalid."
time="2022-03-09T23:35:53-06:00" level=warning msg="Failed to obtain TTY size: The handle is invalid."
sh-5.1#
```

@TomSweeneyRedHat can you do a podman version? I'm just wondering if you have a stale machine.

**Comment by n1hility** [comment]
@TomSweeneyRedHat I have a local fix for the TTY issue, will send a PR tomorrow

**Comment by TomSweeneyRedHat** [comment]
@n1hility I had install 3.3* at one point, but when I went to install 4.0.2, I removed the Podman directory from the machine first and then install 4.0.2.  Perhaps leftover bits from the 3 install were still hanging around?

**Comment by n1hility** [comment]
@TomSweeneyRedHat sorry I meant the wsl based podman machine instance, if there was any chance you had a podman 3 based linux on the backend that the windows remote was talking to.  If so it could be explained by a 4 to 3 api compat issue. If you are using the wsl machine, you should be able to just podman machine rm and podman machine init. Normally you would be able to do a podman machine ssh dnf update to pull down the latest but I only added the copr repo right before 4.0.1 (IIRC)

**Comment by n1hility** [comment]
PR for TTY issues: #13494
