### ISSUE TITLE
Running a pod on OSX leaves infra container running forever

### ISSUE THREAD

**Issue by dav009** [containers/podman#13464]
I am running a pod via play kube. My container exits, but the companion infra container keeps running forever, meaning that the whole pod keeps running forever

Is there a way to make infra container exit once pod's containers exit?

I am running on OSX

**Comment by baude** [comment]
OSX has nothing to do with it.  And fwiw, this is normal pod behavior.  I don't recall offhand that it is possible to do what you are asking; though it is getting late in the day and maybe someone will remember something.

**Comment by rhatdan** [comment]
We have talked a while about instrumenting what should happen in a Pod when containers exit.

1 Pod exits
2 Pod restarts container
3 Pod does nothing 

I think we should add a feature to Pod/Containers for them to specify this.
Default should be for the Pod to exit when it has no containers running.

**Comment by baude** [comment]
captured in RUN-1458

**Comment by vrothberg** [comment]
We need such kind of behavior to make `play-kube` play nicely with systemd as well. Getting this done will probably be a by-product the Edge work unless tackled before.

It's probably also a better experience using a single pod in a systemd unit (from podman-generate-systemd).

**Comment by cdoern** [comment]
yeah I can easily add a flag that changes this behavior

**Comment by baude** [comment]
@cdoern the stuff @rhatdan describes above should be the default ... as such I dont think a flag is needed?

**Comment by rhatdan** [comment]
I would like a default for pod creation, how to handle containers. I don't know what the option shouldbe called.

--cfinish=[exit | ignore| restart]
I guess for cosistancy we would need to default to ignore. Should be in containers.conf.

**Comment by cdoern** [comment]
@baude @rhatdan currently the default is as described where the pod keeps running when a container exits. I was thinking of adding a flag for containers (?) where one can specify that when a specific container exits maybe the pod stops as well?

**Comment by vrothberg** [comment]
I don't understand why we would keep a Pod running when all containers exited.  If users make heavy use of pods, they will have a lot of processes running that don't do much more than creating (a small amount of) heat.

I see an argument for keeping it running if no containers have been added yet though. But if we added a flag, I'd prefer calling it `--keep-running`.

**Comment by rhatdan** [comment]
Let's discuss at Cabal.

**Comment by cdoern** [comment]
@rhatdan what was our decision on this one? I can implement this.

**Comment by dav009** [comment]
@rhatdan  @cdoern  happy to contribute and learn if some hints are given. TA!

**Comment by rhatdan** [comment]
The decision was to do the following.  When a container exits, podman container cleanup is executed.

This program needs to be changed to check if the container is running within a Pod, if so, and the pod has no other containers running, it should stop the pod.  If there are other containers running, then it should just exit.

A Pod with no containers should continue to run, which it will.

We need to make sure that a container start with a restart policy works correctly when run within a Pod. 

@cdoern and @dav009 you are both welcome to work on this. (I was planning on looking at it next, but I don't have the time now.)

**Comment by vrothberg** [comment]
I need this behavior for enabling `play-kube` in systemd units. I haven't seen work starting on it yet, so I will tackle it.

**Comment by cdoern** [comment]
@vrothberg I am working on it but hit a snag so feel free to open a PR. I will follow up with a comment containing the code I have so far

**Comment by vrothberg** [comment]
Apologies, Charlie!  I didn't know you were already on it.

**Comment by cdoern** [comment]
No worries, do you want to continue with it? I haven't gotten too far.

**Comment by vrothberg** [comment]
If you're cool, I can continue.  I think I am close to completion but it is tricky ... dead locks lie behind each and every corner.

**Comment by cdoern** [comment]
Sounds good @vrothberg I was running into a bunch of deadlocks too!
