### ISSUE TITLE
Error: could not find "rootlessport" with podman 4.0 on WSL Ubuntu 20.04

### ISSUE THREAD

**Issue by keonchennl** [containers/podman#13462]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

While trying to run any container with podman 4.0, the error "could not find 'rootlessport'" shows up. The latest distribution does not have this problem.
This is the same as described in this issue #13347 
I tried manually building 'rootlessport' by `make rootlessport` but got the following error: 
`make: *** No rule to make target 'rootlessport'.  Stop.`

**Steps to reproduce the issue:**

1. podman run --restart=always --name nginx -p 80:80 nginx:1.21.6-alpine

**Describe the results you received:**

> Error: could not find "rootlessport" in one of [/usr/local/libexec/podman /usr/local/lib/podman /usr/libexec/podman /usr/lib/podman].  To resolve this error, set the helper_binaries_dir key in the `[engine]` section of containers.conf to the directory containing your helper binaries.

**Describe the results you expected:**

The container gets created without problem

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.2-dev
API Version:  4.0.2-dev
Go Version:   go1.17.7
Git Commit:   49d511b6ee88ceff70cc6786c467bed39da35a61
Built:        Fri Mar  4 17:06:04 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 12
  distribution:
    codename: focal
    distribution: ubuntu
    version: "20.04"
  eventLogger: file
  hostname: DESKTOP-LAP2
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.16.3-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 14382817280
  memTotal: 26694303744
  networkBackend: cni
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: ea1fe3938eefa14eb707f1d22adff4db670645d6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /tmp/podman-run-1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 7516192768
  swapTotal: 7516192768
  uptime: 125h 50m 26.47s (Approximately 5.21 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/keon/.config/containers/storage.conf
  containerStore:
    number: 33
    paused: 0
    running: 0
    stopped: 33
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.9.0
        fuse-overlayfs: version 1.5
        FUSE library version 3.9.0
        using FUSE kernel interface version 7.31
  graphRoot: /home/keon/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 12
  runRoot: /tmp/podman-run-1000/containers
  volumePath: /home/keon/.local/share/containers/storage/volumes
version:
  APIVersion: 4.0.2-dev
  Built: 1646409964
  BuiltTime: Fri Mar  4 17:06:04 2022
  GitCommit: 49d511b6ee88ceff70cc6786c467bed39da35a61
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.2-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 100:3.4.2-1 amd64 [installed]
podman/unknown 100:3.4.2-1 arm64
podman/unknown 100:3.4.2-1 armhf
podman/unknown 100:3.4.2-1 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

But the problem is on version v4.0 (I tested the binaries built from main, v4 branch and the release.)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by keonchennl** [comment]
I am also interested in working on this but not sure where to start... Is updating the make file (to include rootlessport) helpful?

**Comment by rhatdan** [comment]
rootlessport should be shipped as part of the distribution.
What distro are you using?

**Comment by rhatdan** [comment]
This is not an upstream issue, but more to do with the distro you are using. We can continue the conversation here.

**Comment by keonchennl** [comment]
@rhatdan Thanks for explaining!

> This is not an upstream issue, but more to do with the distro you are using. We can continue the conversation here.
