### ISSUE TITLE
Upgrade version 1.6.4 to latest or Podman 3 at least on RHEL 8.2

### ISSUE THREAD

**Issue by madhadee** [containers/podman#13472]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug
sorry may not be bug request, but could not find information to upgrade on RHEL8.2

**Description**

can't seem to upgrade to latest version of podman 3, followed instructions to install podman on installation guide but only 1.6.4 version is available. would be great help if can get some help on this. I have tried to build from source but that seems a little complex as my VM is in a managed environment and has limitations to download packages over github. 

**Steps to reproduce the issue:**

1. sudo yum module enable -y container-tools:rhel8
sudo yum module install -y container-tools:rhel8

2.  

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.13.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.4
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module+el8.2.0+6368+cf16aa14.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: 9adfe850ef954416ea5dd0438d428a60f213                                                                                                             9473'
  Distribution:
    distribution: '"rhel"'
    version: "8.2"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 100
      size: 1
    - container_id: 1
      host_id: 15107744
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 35005
      size: 1
    - container_id: 1
      host_id: 15107744
      size: 65536
  MemFree: 26934374400
  MemTotal: 33555415040
  OCIRuntime:
    name: runc
    package: runc-1.0.0-65.rc10.module+el8.2.0+6368+cf16aa14.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 8493461504
  SwapTotal: 8493461504
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: xx.xxx.uat.xxx.com
  kernel: 4.18.0-193.75.1.el8_2.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.2-3.git21fdece.module+el8.2.0+6368+cf16aa14.x86_64
    Version: |-
      slirp4netns version 0.4.2+dev
      commit: 21fdece2737dc24ffa3f01a341b8a6854f8b13b4
  uptime: 108h 37m 36.79s (Approximately 4.50 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  ConfigFile: /home/xx/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-5.module+el8.2.0+6368+cf16aa14.x86_64
      Version: |-
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  GraphRoot: /home/xx/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /run/user/35005
  VolumePath: /home/xx/.local/share/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.4-12.module+el8.2.0+6669+dde598ec.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
virtual machine in VPC.

**Comment by rhatdan** [comment]
This is not an upstream issue, you should open a bugzilla for RHEL problems. The latest Podman is available on RHEL every 12 weeks, you just need to move the modules stream.
