### ISSUE TITLE
Improve tracking events from podman machines from external tooling

### ISSUE THREAD

**Issue by benoitf** [containers/podman#13491]
/kind feature

**Description**

Starting/stopping and all the management of podman machines is an easy task when using the CLI.

But from external tooling wanted to track CRUD operation on the machines there is no 'event' AFAIK.

For example there is a socket where we can listen events when containers are added/removed,etc. but there is no such activity tracker on machines.

**Steps to reproduce the issue:**

Start podman machines, and then except launching 'podman machine list' at periodic time it's quite hard to get notification when a machine has been stopped or started. (There is like complicated way tracking pid of qemu machines but it looks like a fragile process)

**Describe the results you expect:**

Simple "push" operation to listen to machine activity without having to pull every x second the result of `podman machine list --format json`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
4.0.0-dev
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

macOS

**Comment by vrothberg** [comment]
Thanks for reaching out, @benoitf.

Currently, when running `podman events`, events of a specific machine will be listed.  As you stated above, there are no "meta" events for `podman machine` commands.

I could image a `podman machine events` command that would return/stream machine-events only though.

@baude @containers/podman-maintainers WDYT?

**Comment by benoitf** [comment]
@baude I think the same pattern used for `podman events` would fit

**Comment by baude** [comment]
well, podman events now are written to journald, which will not work on a mac ... are you proposing an events based file ?

**Comment by vrothberg** [comment]
@baude, yes, we need an eventer on the client side. A somehow additional/separate mechanism.

**Comment by benoitf** [comment]
For now on mac if I use
`podman events`

Events are added on the command output like
```
2022-03-16 00:31:49.843805529 +0100 CET image pull  http
```

so if I run `podman machine events` I would expect to receive events like
```
2022-03-16 00:31:49.843805529 +0100 CET machine start podman-machine-default
2022-03-16 00:31:49.843805529 +0100 CET machine stop podman-machine-default
2022-03-16 00:31:49.843805529 +0100 CET machine init foo
```

**Comment by baude** [comment]
@benoitf are you ok with tailing a file?

**Comment by baude** [comment]
@benoitf our current proposal and likeliest implementation will be that we will watch a given directory for sockets.  Should a socket be in the directory, we will write events to it.  This way, readers can opt in and out and there will be no collisions.  As a consequence of this approach, there will also be no history for those events.

**Comment by rhatdan** [comment]
@jwhonce Any updates?

**Comment by rhatdan** [comment]
@baude @jwhonce Where are we on this one?

**Comment by ashley-cui** [comment]
Closed via: https://github.com/containers/podman/pull/14085
