### ISSUE TITLE
Docs : podman-run.1.md option "--log-driver", bad command to get default log driver

### ISSUE THREAD

**Issue by a-vivona** [containers/podman#13503]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

In the podman documentation, page **"podman-run-1.md"**, option **"--log-driver"**, it is indicated a command to display the default driver. This command does not work anymore.

https://github.com/containers/podman/blob/33d808108f837e70dc7cc0803bfa4684953fe05e/docs/source/markdown/podman-run.1.md?plain=1#L541-L549

**Steps to reproduce the issue:**

1. Type the command: podman info --format '{{ .Host.LogDriver }}'

**Describe the results you received:**

Error: template: info:1:8: executing "info" at <.Host.LogDriver>: can't evaluate field LogDriver in type *define.HostInfo

**Describe the results you expected:**

According to the documentation, I should get the name of the default driver used by the system, for example "journald"

**Additional information you deem important (e.g. issue happens only occasionally):**

**Is ".Host.EventLogger" the replacement for ".Host.LogDriver"?**
```
podman info --format '{{ .Host.EventLogger }}'
```

**Output of `podman version`:**

```
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.16.7
Built:        Tue Nov  9 20:48:06 2021
OS/Arch:      linux/amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Luap99** [comment]
You are using an older version of podman. I think this field is present in at least podman 3.4.
I recommend you use the man pages shipped by your distro so they have the same version as the binary or you select the correct version in the right lower corner on https://docs.podman.io/
