### ISSUE TITLE
Missing specific Podman named pipe on Windows if DockerDesktop engine is not installed

### ISSUE THREAD

**Issue by benoitf** [containers/podman#13502]
/kind feature

**Description**

When a podman machine starts on Windows, it checks if there is DockerDesktop or not and then if Docker Desktop is not there it will create the named pipe `//./pipe/docker_engine`

But if Docker Desktop engine is there, it will register the named pipe `//./pipe/podman-<name-of-the-machine>`

The problem is that the 'Docker emulation mode' should not prevent the specific podman channel to be created.

For example if I may want to always use the 'podman' channel to discuss on its own REST API.

**Describe the results you received:**

Podman named pipe is either  `//./pipe/podman-<name-of-the-machine>` or `//./pipe/docker_engine` depending of if DockerDesktop is there or not.

**Describe the results you expected:**

Podman named pipe `//./pipe/podman-<name-of-the-machine>` should always be there (no matter if DockerDesktop is there or not)

**Additional information you deem important (e.g. issue happens only occasionally):**

I checked the named pipe available using on PowerShell the command `[System.IO.Directory]::GetFiles("\\.\\pipe\\")`

https://github.com/containers/podman/blob/f918a9418f5eeb00b289c127142953da2c394867/pkg/machine/wsl/machine.go#L805-L811

**Output of `podman version`:**

```
4.0.2
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@n1hility PTAL
