### ISSUE TITLE
Put an "installing" section on the website

### ISSUE THREAD

**Issue by skorokithakis** [containers/podman#13508]
I'm trying to install Podman and am looking around the website for instructions but can't easily find any. It would be good if there were a short section telling me how to get Podman and install it locally.

There aren't even installation instructions in the repo README, and clicking to the releases shows me a "podman-remote" binary, but I don't want Podman Remote, I want Podman itself? Or do I?

At that point, the average interested user has closed the window and given up on Podman.

**Comment by Luap99** [comment]
https://podman.io/getting-started/installation.html

**Comment by skorokithakis** [comment]
Thanks. Now please point to the link on the page:

![image](https://user-images.githubusercontent.com/23648/158351122-cd13bd84-640f-4859-913f-aa5c7a8a10af.png)

**Comment by Luap99** [comment]
It is linked under Getting Started in the sidebar

**Comment by skorokithakis** [comment]
There is no sidebar on my screen, as you can see in the screenshot. I assume I am getting the mobile view, where the link is hidden. Anyway, if that works for you, fine.

**Comment by Luap99** [comment]
just press on top right corner

**Comment by vrothberg** [comment]
@TomSweeneyRedHat PTAL

I agree that the "mobile" version should also point directly to installing Podman.

**Comment by TomSweeneyRedHat** [comment]
I'm a cellphone Luddite when it comes to web browsing.  I need to remember to make an effort to check/fix stuff for that going forward.
