### ISSUE TITLE
Podman on MacOS: Couldn't restablish ssh tunnel on path (when a machine already exists)

### ISSUE THREAD

**Issue by orpiske** [containers/podman#13510]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

This seems to happen when upgrading from Podman 3.x to 4.x. 

When starting a machine on MacOS, it prints an error saying it couldn't re-establish ssh tunnel on path. 

The problem seems to go away after deleting the machine and creating it again (so, probably, just need to be documented). 

**Steps to reproduce the issue:**

1. Create a machine on Podman 3.x and upgrade to podman 4.x.

2. Start the machine

**Describe the results you received:**

It prints the following error: 

```
Starting machine "podman-machine-default"
INFO[0000] waiting for clients...                       
INFO[0000] new connection from  to /var/folders/9h/q89zvsb57rx6603dm6ggk4m80000gp/T/podman/qemu_podman-machine-default.sock 
Waiting for VM ...
2022/03/15 10:47:50 tcpproxy: for incoming conn [::1]:52555, error dialing "192.168.127.2:22": connect tcp 192.168.127.2:22: no route
...
INFO[0015] Socket forward established: /Users/opiske/.local/share/containers/podman/machine/podman-machine-default/podman.sock to /run/user/0/podman/podman.sock 
ERRO[0015] Couldn't restablish ssh tunnel on path: /run/user/0/podman/podman.sock: ssh: rejected: connect failed (open failed) 
```

It seems this prevent the socket from being created/accessed with breaks tools such as docker-compose.

**Describe the results you expected:**

I would expect no error and the socket to be created.

**Additional information you deem important (e.g. issue happens only occasionally):**

Podman version: 4.0.2
Installed from: brew
MacOS: Monterrey 12.3 (Darwin Kernel Version 21.4.0)
Arch: ARM (M1)

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.8

Built:      Wed Mar  2 15:04:36 2022
OS/Arch:    darwin/arm64

Server:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.16.14

Built:      Thu Mar  3 15:58:50 2022
OS/Arch:    linux/arm64

```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AddictArts** [comment]
I had this same issue. I ended up performing, NOTE: Containers will be removed.

```shell
podman machine rm
podman machine init
podman machine start
```

There may be a way to save your containers, but it didn't matter for me.

**Comment by n1hility** [comment]
I can confirm the bug. Issue is likely additional state. Will look into a fix.

/assign

**Comment by leblancfg** [comment]
> 

:eyes: Had to `podman machine stop` beforehand. Obvious in hindsight.
