### ISSUE TITLE
Error running multiple commands with podman machine ssh on macOS

### ISSUE THREAD

**Issue by kgibm** [containers/podman#13517]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I have a lab that uses `podman` and one of the steps is to disable systemd-coredump in the podman machine on macOS. This works using the following 2 commands:

1. `podman machine ssh ln -sf /dev/null /etc/sysctl.d/50-coredump.conf`
2. `podman machine ssh sysctl -w kernel.core_pattern=core`

However, if I try to combine the two commands like so, it fails:

```
$ podman machine ssh sh -c "ln -sf /dev/null /etc/sysctl.d/50-coredump.conf && sysctl -w kernel.core_pattern=core"
Warning: Permanently added '[localhost]:55402' (ED25519) to the list of known hosts.
ln: missing file operand
Try 'ln --help' for more information.
Error: exit status 1
```

When running the `ln` command on its own, it works fine and the exit code is 0:

```
$ podman machine ssh ln -sf /dev/null /etc/sysctl.d/50-coredump.conf
Warning: Permanently added '[localhost]:55402' (ED25519) to the list of known hosts.
$ echo $?
0
```

This makes me think there's a bug in the processing of the `podman machine ssh sh -c` command line arguments.

**Steps to reproduce the issue:**

1. `podman machine init --rootful=true`
2. `podman machine start`
3. podman machine ssh sh -c "ln -sf /dev/null /etc/sysctl.d/50-coredump.conf && sysctl -w kernel.core_pattern=core"

**Describe the results you received:**

Error in the `ln` command.

**Describe the results you expected:**

The command should work the same whether run standalone or as part of a shell execution.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
% podman version
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.8

Built:      Wed Mar  2 08:04:36 2022
OS/Arch:    darwin/amd64

Server:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.16.14

Built:      Thu Mar  3 08:56:56 2022
OS/Arch:    linux/amd64
```

**Output of `podman info --debug`:**

<details>

```
kevin@Kevins-MBP dockerdebug % podman info --debug
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpus: 4
  distribution:
    distribution: fedora
    variant: coreos
    version: "35"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.18-200.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 3257647104
  memTotal: 10426429440
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.2-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.2
      commit: f6fbc8f840df1a414f31a60953ae514fa497c748
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 3h 31m 35.22s (Approximately 0.12 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1646319416
  BuiltTime: Thu Mar  3 08:56:56 2022
  GitCommit: ""
  GoVersion: go1.16.14
  OsArch: linux/amd64
  Version: 4.0.2
```

</details>

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

N/A

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

**Yes**/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@jwhonce PTAL

**Comment by ashley-cui** [comment]
I don't think this is a bug, as this is the behavior and syntax regular ssh does: 

```
$ /usr/bin/ssh -i /Users/acui/.ssh/podman-machine-default -p 53696 core@localhost -o "UserKnownHostsFile /dev/null" -o "StrictHostKeyChecking no" sh -c echo hello; echo hello2

hello2
```

However, doing this command without the `sh -c` works correctly both in `podman machine ssh` and  regular ssh: 

```
$ podman machine ssh echo hello; echo hello2
hello
hello2
```

Feel free to re-open if you think there is more to this.

**Comment by kgibm** [comment]
@ashley-cui 

The point is to run multiple commands in the podman machine using a single `ssh` execution. Your examples are executing one command on the podman machine and the other command on your macOS machine. This point can be more easily explained by changing your `echo` to `uname`:

```
% ssh -i ~/.ssh/podman-machine-default -p 55402 core@localhost -o "UserKnownHostsFile /dev/null" -o "StrictHostKeyChecking no" sh -c uname; uname
Warning: Permanently added '[localhost]:55402' (ED25519) to the list of known hosts.
Linux
Darwin
```

The semicolon after your first example command ends the `ssh` (or `podman ssh`) command and then executes the next command on your machine.

Instead, what my example shows is a failure when running both commands on the `podman machine`; in other words, converting your example would lead to (notice the additional double quotes):

```
% ssh -i ~/.ssh/podman-machine-default -p 55402 core@localhost -o "UserKnownHostsFile /dev/null" -o "StrictHostKeyChecking no" sh -c "uname; uname"
Warning: Permanently added '[localhost]:55402' (ED25519) to the list of known hosts.
Linux
Linux
```

However, as I continued doing some testing, it seems the underlying issue might be a bug in `ssh` itself! I will open a bug report with the `ssh` team. Running on vanilla Linux shows that the direct `ln` command works:

```
$ ssh root@localhost ln -sf /dev/null /etc/sysctl.d/50-coredump.conf
```

But wrapping it doesn't:

```
$ ssh root@localhost sh -c "ln -sf /dev/null /etc/sysctl.d/50-coredump.conf"
ln: missing file operand
Try 'ln --help' for more information.
```

**Comment by kgibm** [comment]
Found the solution. Additional quoting was needed:

```
$ podman machine ssh "sh -c 'ln -sf /dev/null /etc/sysctl.d/50-coredump.conf && sysctl -w kernel.core_pattern=core'"
```
