### ISSUE TITLE
Podman on MacOS: podman-mac-helper missing?

### ISSUE THREAD

**Issue by orpiske** [containers/podman#13511]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

During the machine startup, podman prints a warning that the system helper service is not installed. However, the file is not present the in the location provided in the warning message.

**Steps to reproduce the issue:**

1. Start the podman machine: `podman machine start` 

2. Check the output

3. Try to run the suggested command: `sudo /opt/homebrew/Cellar/podman/4.0.2/bin/podman-mac-helper install` 

**Describe the results you received:**

```
...

The system helper service is not installed; the default Docker API socket
address can't be used by podman. If you would like to install it run the
following command:

	sudo /opt/homebrew/Cellar/podman/4.0.2/bin/podman-mac-helper install
...
```

Then, trying to run the command:

```
sudo: /opt/homebrew/Cellar/podman/4.0.2/bin/podman-mac-helper: command not found
```

**Describe the results you expected:**

Running the suggested command should succeed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.8

Built:      Wed Mar  2 15:04:36 2022
OS/Arch:    darwin/arm64

Server:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.16.14

Built:      Thu Mar  3 15:58:50 2022
OS/Arch:    linux/arm64

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

Output from `brew info podman`:

```
podman: stable 4.0.2 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/opt/homebrew/Cellar/podman/4.0.2 (171 files, 43.5MB) *
  Poured from bottle on 2022-03-15 at 10:11:35
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0
==> Dependencies
Build: go ✘, go-md2man ✘
Required: qemu ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Analytics
install: 9,130 (30 days), 35,211 (90 days), 102,353 (365 days)
install-on-request: 9,122 (30 days), 35,194 (90 days), 102,335 (365 days)
build-error: 13 (30 days)

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@n1hility PTAL

**Comment by baude** [comment]
> @n1hility PTAL

We got this -> https://github.com/Homebrew/homebrew-core/pull/96902
