### ISSUE TITLE
Difference between podman machine set --rootful and podman system connection default podman-machine-default-root?

### ISSUE THREAD

**Issue by kgibm** [containers/podman#13515]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I just upgraded to podman 4.0.2 (on macOS). When I start the machine, I see the following:

> This machine is currently configured in rootless mode. If your containers
> require root permissions (e.g. ports < 1024), or if you run into compatibility
> issues with non-podman clients, you can switch using the following command: 
> 
> 	podman machine set --rootful

In the past, I had run the following command to switch to rootful:

```
podman system connection default podman-machine-default-root
```

So I ran `podman system connection default podman-machine-default-root`, and then I see that I am `root` as expected:

```
$ podman run --rm fedora whoami
root
```

However, if I stop the machine and restart it, I still see the message about `podman machine set --rootful`.

What's the difference between `podman machine set --rootful` and `podman system connection default podman-machine-default-root`?

**Steps to reproduce the issue:**

1. `podman machine init`
2. `podman machine start`

**Describe the results you received:**

Confusing help message on `podman machine start`

**Describe the results you expected:**

Unclear

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
% podman version
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.8

Built:      Wed Mar  2 08:04:36 2022
OS/Arch:    darwin/amd64

Server:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.16.14

Built:      Thu Mar  3 08:56:56 2022
OS/Arch:    linux/amd64
```

**Output of `podman info --debug`:**

<details>

```
% podman info --debug
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpus: 4
  distribution:
    distribution: fedora
    variant: coreos
    version: "35"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.18-200.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 191401984
  memTotal: 10426429440
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.2-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.2
      commit: f6fbc8f840df1a414f31a60953ae514fa497c748
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 14m 20.99s
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1646319416
  BuiltTime: Thu Mar  3 08:56:56 2022
  GitCommit: ""
  GoVersion: go1.16.14
  OsArch: linux/amd64
  Version: 4.0.2
```

</details>

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
N/A
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

**Yes**/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Luap99** [comment]
I guess there are identical, no idea why an extra command for this was added.
cc @n1hility

**Comment by Luap99** [comment]
I see, I guess this should be added in https://github.com/containers/podman/blob/main/docs/source/markdown/podman-machine-set.1.md.

@kgibm Also `podman run --rm fedora whoami` will always show you root since this is inside the container. The difference about root/rootless is if podman itself is run as root or rootless user in the VM.

**Comment by kgibm** [comment]
@n1hility  Thanks, so if I understand correctly, it seems I should use `podman machine set --rootful` or `podman machine init --rootful=true` instead of `podman system connection default podman-machine-default-root`.

I'm building a lab using `podman` and some of my users may be on older versions of `podman` (e.g. 3). How long has this `podman machine init --rootful=true` command been around, or is it new to 4?

@Luap99 Thanks, that makes.

**Comment by n1hility** [comment]
@kgibm yes this is new in 4 so if you are building automation for 3 and 4, what I would recommend doing is to prefer setting it via init or set and just having a fallback piece of logic if you get a non-zero exit code. Although if you aren't using API forwarding then you can still do it the old way with 4. Over time other things may reference the stored config setting.

@Luap99 there is a description there about how it syncs connections in the --rootful option. Where you thinking we should add some sort of explicit note to recommend using this over podman system connection?
