### ISSUE TITLE
Docs: podman-system-service, podman-run documentation inconsistency

### ISSUE THREAD

**Issue by lemmi** [containers/podman#13526]
/kind bug

In order to mount the system socket into a container `podman-system-service.1.md` suggests to provide `--security-opt label:disable`, while `podman-run.1.md` suggest the option should be of the form `--security-opt=label=disable`

https://github.com/containers/podman/blob/dc0c72a48b50fd43594928172d88182fd81f3e8b/docs/source/markdown/podman-system-service.1.md?plain=1#L18

https://github.com/containers/podman/blob/dc0c72a48b50fd43594928172d88182fd81f3e8b/docs/source/markdown/podman-run.1.md?plain=1#L901

I haven't searched for more instances, I just happend to notice this one and I'm unsure what the correct syntax is.

**Comment by vrothberg** [comment]
Thanks for reporting the issue!  Interested in opening a pull request?
