### ISSUE TITLE
Compile error on slackware

### ISSUE THREAD

**Issue by notklaatu** [containers/podman#13525]
/kind bug

**Description**

Compile fails with "Error 2"

**Steps to reproduce the issue:**

1. Download source code for 4.0.2
2. Install libseccomp, libslirp, slirp4netns, cni plugins, conmon, runc, go version 1.18
3. `cd podman-4.0.2`
4. `make BUILDTAGS="seccomp"`
5. Build fails with "Error 2" Makefile line 317 (a warning about installing on a non-systemd platform, but I don't think this is actually the cause of the error)

```
Podman is being compiled without the systemd build tag.         Install libsystemd on Ubuntu or systemd-devel on rpm based      distro for journald support.
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build \
        -mod=vendor  \
        -gccgoflags '-X github.com/containers/podman/v4/libpod/define.gitCommit=342c8259381b63296e96ad29519bd4b9c7afbf97 -X github.com/containers/podman/v4/libpod/define.buildInfo=1647394514 -X github.com/containers/podman/v4/libpod/config._installPrefix=/usr/local -X github.com/containers/podman/v4/libpod/config._etcDir=/usr/local/etc ' \
        -tags "      exclude_graphdriver_devicemapper seccomp" \
        -o bin/podman ./cmd/podman
# github.com/containers/storage/pkg/unshare
unshare.c: In function ‘parse_proc_stringlist’:
unshare.c:137:23: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
  137 |         for (n = 0; n < used; n++) {
      |                       ^
unshare.c:148:23: warning: comparison of integer expressions of different signedness: ‘int’ and ‘size_t’ {aka ‘long unsigned int’} [-Wsign-compare]
  148 |         for (n = 0; n < used; n++) {
      |                       ^
# github.com/containers/podman/v4/libpod
libpod/options.go:81:33: error: ‘copy’ defined as both imported name and global name
   81 |                                 copy(rt.storageConfig.GraphDriverOptions, config.GraphDriverOptions)
      |                                 ^
libpod/container_stat_linux.go:13:49: note: ‘copy’ imported here
   13 |         "github.com/containers/podman/v4/pkg/copy"
      |                                                 ^
make: *** [Makefile:317: bin/podman] Error 2
```

## Expected

Successful compile.

## What else I've tried

From what research I've been able to do, this may be a gccgo error and not a Podman error.

## Environment details

```
$ cat /etc/os-release
NAME=Slackware
VERSION="15.0"
ID=slackware
VERSION_ID=15.0
PRETTY_NAME="Slackware 15.0 x86_64"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:slackware:slackware_linux:15.0"
HOME_URL="http://slackware.com/"
SUPPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
BUG_REPORT_URL="http://www.linuxquestions.org/questions/slackware-14/"
VERSION_CODENAME=stable
```

**Comment by baude** [comment]
it sure looks like it to me ... i was going to try compiling it inside a slackware container ... but  the setup looks steeper than dnf -y or apt-get :) maybe look at the toolchain for fedora 35 and try to do similar. i can look tomorrow but maybe some more slackware friendly can help in  the by and by.

**Comment by vrothberg** [comment]
@vbatts may be able to help :)

**Comment by vrothberg** [comment]
After a closer inspection of the compilation error, I seems more like a Slackware setting to me.
> libpod/options.go:81:33: error: ‘copy’ defined as both imported name and global name
   81 |                                 copy(rt.storageConfig.GraphDriverOptions, config.GraphDriverOptions)
      |                                 ^
libpod/container_stat_linux.go:13:49: note: ‘copy’ imported here
   13 |         "github.com/containers/podman/v4/pkg/copy"
   
That is even in different files and I have never seen Go complain about it - even Go 1.18.  I don't have a quick way to get a Slackware machine up to see which settings may cause the issue.
