### ISSUE TITLE
Add option to easily capture syslog/journald from within container

### ISSUE THREAD

**Issue by aragilar** [containers/podman#13550]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Currently getting logs out from a container is somewhat painful. Either:
* You log to stdout/stderr, implicitly losing log level information/context.
* You log to files/syslog/journald, and set up mounts to map host paths to container paths, complicating running the container.
Instead, if there was a simple option/setting (e.g. `--include-journald`) to handle mounts in the most common cases, then this would increase the usability of container logging (and allow captured logs to be forwarded on to a central system etc.).

**Comment by giuseppe** [comment]
how would you expect it to look?

Something like https://github.com/projectatomic/oci-register-machine ?

**Comment by aragilar** [comment]
Sure. I wouldn't mind further inspectability, it's mainly around the need to futz around with mount paths and ensure permissions match etc.

**Comment by rhatdan** [comment]
I really am not sure what would happen here.  In order for syslog or journald to work inside of the container, you would need to have something listening on those sockets like systemd.

**Comment by aragilar** [comment]
I wasn't thinking of running syslogd/journald/systemd inside the container (although, if that was the best way to pass all the context from inside the container to outside the container, it wouldn't be too bad), instead that somehow the sockets that are used for logging appear inside the container and forward the logs outside the container (I was thinking using mountpoints, but maybe there's a better way?). If systemd is required to be running outside the container, I don't think that's an issue (as presumably non-systemd users could take the code which handles syslog messages and modify for their needs).

**Comment by rhatdan** [comment]
You could  volume mount /dev/log and /run/systemd from the host into the container and then this information would end up in the host system.  Most likely you would need to disable SELinux in this situation, since SELinux would block containers from talking to the host processes.

**Comment by rhatdan** [comment]
This is not something that Podman does, so I am closing.  I think this needs to be done with other tools potentially side car containers.
