### ISSUE TITLE
podman restore --keep sometimes fails

### ISSUE THREAD

**Issue by alanruttenberg** [containers/podman#13566]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I want to be able to restore a container multiple times. As I understand it, in order to enable this I need to use the --keep argument with podman container restore. For one image, ubuntu:1604, this works. I can restore with --keep, attach, exit, and do it again. However with another container I've built, this fails. 

However if, instead of exiting the container, I use podman container stop, then restore --keep works.

**Steps to reproduce the issue:**
lsw2/lisp is an image I have built.
```
podman container run -it --name foo lsw2/lisp
```
enters bash
run java application with interactive prompt
in another shell,
```
sudo podman container checkpoint --keep --file-locks --tcp-established foo
sudo podman container restore --keep --file-locks --tcp-established foo
podman container attach foo
```
quit the java application
now back at bash prompt 
```
exit
sudo podman container restore --keep --file-locks --tcp-established foo
```

**Describe the results you received:**
```

Error: crun: CRIU restoring failed -52.  Please check CRIU logfile /var/lib/containers/storage/overlay-containers/5d6ec6f7eaf52371daa88b2dd21c8f00ae8a452a2c7fa998c49df32a6cb67319/userdata/restore.log: OCI runtime error
```
The tail of restore.log says:

```
(00.040650)      9: Error (criu/files-reg.c:2143): Can't open file tmp/hsperfdata_lsw/9 on restore: No such file or directory
(00.040668)      9: Error (criu/files-reg.c:2086): Can't open file tmp/hsperfdata_lsw/9: No such file or directory
(00.040671)      9: Error (criu/mem.c:1349): `- Can't open vma
(00.041773) pie: 6: Task 9 exited, status= 1
(00.041914) pie: 2: Task 6 stopped with 19
(00.042751) mnt: Switching to new ns to clean ghosts
(00.042788) Unlink remap home/lsw/abcl-felix-cache/cache.lock.cr.1.ghost
(00.042873) Error (criu/cr-restore.c:2447): Restoring FAILED.
```

**Describe the results you expected:**

Able to attach and continue to interact with java program, same as if I stopped the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

If, instead of quitting the java application and exiting bash I do, from another shell
```sudo podman container stop foo```
the second restore succeeds.

**Output of `podman version`:**

```
podman version 4.0.0-dev
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    variant: coreos
    version: "35"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.18-200.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 14998118400
  memTotal: 16767217664
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.2-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.2
      commit: f6fbc8f840df1a414f31a60953ae514fa497c748
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 48m 15.24s
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 48
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1646319416
  BuiltTime: Thu Mar  3 09:56:56 2022
  GitCommit: ""
  GoVersion: go1.16.14
  OsArch: linux/amd64
  Version: 4.0.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

Installed using MacPorts. This is the output of ```port info podman```
```
podman @4.0.0 (sysutils)

Description:          Podman is a tool for running Linux containers. You can do this from a MacOS desktop as long as you have access to a linux box
                      either running inside of a VM on the host, or available via the network. You need to install the remote client and then setup
                      ssh connection information.
Homepage:             https://github.com/containers/podman

Build Dependencies:   go
Runtime Dependencies: gvisor-tap-vsock, qemu
Platforms:            darwin, freebsd, linux
License:              Apache-2
Maintainers:          Email: judaew@macports.org, GitHub: judaew
                      Policy: openmaintainer

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I am running MacOS 15. podman is installed from macports. podman machine initialized with 8 cores, 16G memory, rootful

**Comment by Luap99** [comment]
@adrianreber @rst0git PTAL

**Comment by adrianreber** [comment]
This sounds like a misunderstanding. `--keep` cannot be used the way you want to use it. Or better, it can work, but it can also fail.

The idea behind the `--keep` option is to keep log files and also the checkpoint data for error analysis. The way you are using it was not the intend.

To restore a checkpoint all files need to be the same as during checkpointing or else your restored process is accessing a file with changed content and that might lead to errors. Therefore CRIU checks at least the file size to have some confidence that the file did not change.

In your case it is a known thing with JVM and restore. The JVM has something called the `perfdata feature` which creates the files CRIU detects the file size changes. In your case you could tell the JVM to not creates those files using `-XX:-UsePerfData`.
That would probably fix the problem you are seeing, but you still use the restore feature in a way it is not supposed to be used and potentially unsafe.

What you want to do can only be done using the checkpoint `--export` feature. That would create a checkpoint archive which contains the actual checkpoint and the state of the filesystem during checkpointing. Only the combination of checkpoint and corresponding filesystem changes gives you a reliable restore.

Podman knows internally that the container has been checkpointed or not and probably should just refuse to do a restore for a container that is not in the `Checkpointed: true` state.

You can try to set `-XX:-UsePerfData` for the JVM in your container to see if that works for you, but you still would use potentially unsafe restores if other files are changing. Worse would be if the file changes, but not the file size. CRIU cannot detect this and your process is restored, but the content of the file is different than the restored application expects.

**Comment by alanruttenberg** [comment]
Thank you very much @adrianreber for the explanation! Yes, using -XX:-UsePerfData does let it work.  Repeating to make sure I understand: If I change any file after I resume a checkpoint, I won't be able to resume it again.

I had done some experiments with --export but the performance was too slow for what I'm aiming for. It took at least 10 seconds and sometimes low 20 seconds to import and restart a container, the longer times, IIRC. after I had done it a few times. I also saw the machine qcow2 file grow a lot more than it seemed it should have. That's anecdotal, I know. I will try to reproduce reliably.

Restoring from checkpoint using --keep is much much faster - 2 or 3 seconds - which is what I'm aiming for since I want to turn this into a command line tool for quick tasks (that happen to need a lot of state in order to be fast).

A few questions: 
1. Is the slow time for restore from export due to transferring the files to the host file system and, if so, can the exported checkpoint be saved within the podman machine image to reduce the time?
2. Along the lines of (1), can the checkpoint directories be cloned under a new id, and then resume on the new id, leaving leaving the original checkpoint untouched?
3. I haven't studied overlays so apologies if this makes no sense, but  I'm wondering whether I can, on resuming a checkpoint, add an overlay to capture any changes that happen once the checkpoint is resumed, which could be tossed before the next resume. 
4. Along the lines of (2), are there any places in the file system that can be written where the CRIU file checks won't be done, say in /tmp or in another volume?

**Comment by adrianreber** [comment]
> Thank you very much @adrianreber for the explanation! Yes, using -XX:-UsePerfData does let it work. Repeating to make sure I understand: If I change any file after I resume a checkpoint, I won't be able to resume it again.

Yes, if any file which is opened by any of the checkpointed processes changes in size, CRIU will not restore the process to avoid unnecessary possible failures. It could work but CRIU stays on the safe side.

> I had done some experiments with --export but the performance was too slow for what I'm aiming for. It took at least 10 seconds and sometimes low 20 seconds to import and restart a container, the longer times, IIRC. 

With export there is usually a compress/decompress (which can be disabled, by the way) and copying involved. Try to disable compression during checkpointing with `--compress none` (I think).

> A few questions:

One thing I need to mention, I am not familiar with MacOS and the whole podman setup on a Mac.

>     1. Is the slow time for restore from export due to transferring the files to the host file system and, if so, can the exported checkpoint be saved within the podman machine image to reduce the time?

Not sure how that works on a Mac.

>     2. Along the lines of (1), can the checkpoint directories be cloned under a new id, and then resume on the new id, leaving leaving the original checkpoint untouched?

You can manually create copies. That should work. You need the `checkpoint` directory and a couple of metadata files. It can be done.

>     3. I haven't studied overlays so apologies if this makes no sense, but  I'm wondering whether I can, on resuming a checkpoint, add an overlay to capture any changes that happen once the checkpoint is resumed, which could be tossed before the next resume.

Probably yes, but the checkpointing code does not really touch anything concerning the underlying file systems. In theory something like you suggested could be done.

>     4. Along the lines of (2), are there any places in the file system that can be written where the CRIU file checks won't be done, say in /tmp or in another volume?

If the changed files are only in directories mounted from the outside of the container, then it can work. Then you can ensure that the files have the correct content. Everything outside of the container which is usually bind mounted in the container is your responsibility, the checkpoint code tries to restore all files inside of the container as they were before.

**Comment by Luap99** [comment]
@alanruttenberg If you want to skip the copy to your host os from the VM you have to use `podman machine ssh podman ...`

**Comment by alanruttenberg** [comment]
@Luap99 Thanks. I just tried that but get an error on restore. The last bit of the log is below. I presume that since I exported within podman machine I needed to import it in same. The commands, within a shell started with podman machine ssh```. Note that I verified that the export/import I did on my host does succeed. FWIW I have updated to 4.02. between my last comment and this one.

```sh
podman container checkpoint --file-locks --tcp-established --compress none a89615250f38 -e lsw-checkpoint.tar
podman container rm a89615250f38
podman container restore --keep --file-locks --tcp-established --import lsw-checkpoint.tar
```
Log:
```sh
(00.241509) pie: 2: Preadv 0x400000:4096... (15 iovs)
(00.241509)      9: File usr/share/java/slf4j-api.jar could only be validated with file size
(00.241528)      9: 		Create fd for 117
(00.241528) pie: 6: Error (criu/pie/restorer.c:180): can't write lsm profile -13
(00.241609)      9: File usr/share/java/sisu-plexus.jar could only be validated with file size
(00.241655)      9: 		Create fd for 118
(00.241731) pie: 6: Error (criu/pie/restorer.c:1925): Restorer fail 6
(00.241731)      9: File usr/share/java/sisu-inject.jar could only be validated with file size
(00.241787)      9: 		Create fd for 119
(00.241830)      9: File usr/share/java/plexus-utils2.jar could only be validated with file size
(00.241859)      9: 		Create fd for 120
(00.241943)      9: File usr/share/java/plexus-sec-dispatcher.jar could only be validated with file size
(00.241964)      9: 		Create fd for 121
(00.242005)      9: File usr/share/java/plexus-interpolation.jar could only be validated with file size
(00.242052)      9: 		Create fd for 122
(00.242095)      9: File usr/share/java/plexus-component-annotations-1.5.jar could only be validated with file size
(00.242095) pie: 2: Task 6 exited, status= 1
(00.242117)      9: 		Create fd for 123
(00.242152)      9: File usr/share/java/plexus-cipher.jar could only be validated with file size
(00.242174)      9: 		Create fd for 124
(00.244154) mnt: Switching to new ns to clean ghosts
(00.244237) Unlink remap home/lsw/abcl-felix-cache/cache.lock.cr.1.ghost
(00.244420) Error (criu/cr-restore.c:2447): Restoring FAILED.
```

**Comment by alanruttenberg** [comment]
In case it matters, my podman machine is initialized with

```podman machine init --cpus 8 --memory 16384 --rootful -v /Users:/mnt/Users```

**Comment by vrothberg** [comment]
@adrianreber @alanruttenberg shall we keep this issue open?  I am not sure how to proceed.

**Comment by adrianreber** [comment]
Looking at the last error message:
```
(00.241528) pie: 6: Error (criu/pie/restorer.c:180): can't write lsm profile -13
```

This means that the restore is happening on a system with a different LSM setup. Either no SELinux or no Apparmor. CRIU tries to restore the LSM labels and fails.

@alanruttenberg You have to make sure you restore on a system with the same LSM setup.

**Comment by alanruttenberg** [comment]
I have recently tested this,  successfully, in Podman 4.3.1 MacOS  10.15.7.
Thank you!

**Comment by vrothberg** [comment]
Thanks for checking @alanruttenberg and @adrianreber !
