### ISSUE TITLE
podman unshare does not work on standard user account added to coreos on pi4.

### ISSUE THREAD

**Issue by millerthegorilla** [containers/podman#13571]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am unable to run podman unshare.  I have su'd to a standard user account from the core user of coreos on a pi4b.  I get the following errors when running the podman unshare command.
```Failed to connect to bus: Operation not permitted (consider using --machine=<user>@.host --user to connect to bus of other user)```
I shown a root prompt, and I run ```podman image mount "container_name"```:
```ERRO[0000] stat /run/user/0: no such file or directory```
my standard user account had a similar error, and on asking the coreos matrix, I was told to linger the user, which I did, and this got me a /run/user/uid directory.   I am inclined to suspect that this is a coreos configuration issue.
I have tried using systemd-run and the other suggestions from the troubleshooting advice, but to no avail.

**Steps to reproduce the issue:**

1.  login to coreos core user by using ssh

2. su into standard user account

3. run podman unshare

**Describe the results you received:**
error msg - ```Failed to connect to bus: Operation not permitted (consider using --machine=<user>@.host --user to connect to bus of other user)```
+ root prompt.   run podman image mount container_name or any other podman command and get error ```ERRO[0000] stat /run/user/0: no such file or directory``` 
 
**Describe the results you expected:**
functional uid root prompt 

**Additional information you deem important (e.g. issue happens only occasionally):**
I am on coreos, on pi4b and it may not be configured correctly, although it is the standard configuration.  I couldn't get a systemd session using the user with /run/user/uid not existing, until I lingered the user using loginctl.  I think this may be coreos misconfigured.
Also, to get a systemd session working in the standard user account I had to append the following lines to the standard user's .bashrc:
```
export XDG_RUNTIME_DIR="/run/user/$UID"
export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"
```

**Output of `podman version`:**

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 21:48:10 2021
OS/Arch:      linux/arm64
```

**Output of `podman info --debug`:**

```
host:
  arch: arm64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc35.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpus: 4
  distribution:
    distribution: fedora
    variant: coreos
    version: "35"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.16.13-200.fc35.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 6506102784
  memTotal: 8147423232
  ociRuntime:
    name: crun
    package: crun-1.4.2-1.fc35.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.2
      commit: f6fbc8f840df1a414f31a60953ae514fa497c748
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.aarch64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 1h 14m 28.99s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /var/home/user/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/user/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 47
  runRoot: /run/user/1001/containers
  volumePath: /var/home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 1639000090
  BuiltTime: Wed Dec  8 21:48:10 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/arm64
  Version: 3.4.4

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
coreos - rpm-ostree so no.
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
latest coreos on pi4b

**Comment by flouthoc** [comment]
Hi @millerthegorilla , I think this is because somehow the systemd session is not created properly.

Could you share output of `echo $XDG_RUNTIME_DIR $UID` please ?
I think you would either need to do `ssh` into the user which are using or create a valid session using `machinectl login`.

I'm not at all sure but I don't think this is a podman issue looks more like issue with `systemd` configuration issue.

**Comment by Luap99** [comment]
Inside podman unshare $UID will always be 0, thus your `export XDG_RUNTIME_DIR="/run/user/$UID"` in bashrc will point to the wrong location.

Using su is not recommended, even if you enable lingering you still have to at least use `su --login` to set the proper env vars.
It is best to use `machinectl shell -q username@` to change the user with systemd or setup ssh for localhost.

If you want to use your `export` hack in .bashrc you should check for the `_CONTAINERS_ROOTLESS_UID` env var and use this when defined.

**Comment by millerthegorilla** [comment]
@Luap99   I did as you said, removing the 'hack' from .bashrc, and used ```sudo machinectl shell -q username@``` to login.  It logged in ok, but when I ran podman unshare, I got the following error.
```
Failed to connect to bus: Operation not permitted (consider using --machine=<user>@.host --user to connect to bus of other user)
```
I did manage to get the podman unshare command to work, but that was when the 'hack' was in .bashrc, and I su'd into the user account, then commented out the 'hack'.  I was then able to run the podman unshare command.
I looked for the env var _CONTAINERS_ROOTLESS_UID but it was not defined.

**Comment by millerthegorilla** [comment]
With that in mind, and because I need to be able to run commands in the standard user account from scripts that are based in the core account, I used the following different 'hack' to get the podman unshare command working.
```bash
if [[ ${UID} -eq 1001 ]]
then
    export XDG_RUNTIME_DIR="/run/user/$UID"
    export DBUS_SESSION_BUS_ADDRESS="unix:path=${XDG_RUNTIME_DIR}/bus"
fi
```

**Comment by Luap99** [comment]
machinectl should set the correct `XDG_RUNTIME_DIR` and `DBUS_SESSION_BUS_ADDRESS` values, what are the values when you run it without the export in your bashrc?

**Comment by millerthegorilla** [comment]
```
XDG_CONFIG_HOME=/var/home/user_name/.config
XDG_SESSION_TYPE=tty
XDG_SESSION_CLASS=user
XDG_SESSION_ID=9
XDG_RUNTIME_DIR=/run/user/1001

DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus
```

**Comment by millerthegorilla** [comment]
does it make any difference if this user is lingering?
