### ISSUE TITLE
quay.io/podman/stable is outdated

### ISSUE THREAD

**Issue by Luap99** [containers/podman#13579]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The podman stable image is not on 4.X and is still based on fedora 34.

**Steps to reproduce the issue:**

1. `podman run --pull always quay.io/podman/stable:latest podman version`

**Describe the results you received:**
podman version 3.4.4 on fedora 34

**Describe the results you expected:**
We should have 4.0 in the stable image (maybe also update to fedora 36)

**Comment by lsm5** [comment]
@cevich @TomSweeneyRedHat how do we wanna do this? fedora 35 + copr or fedora 36?

**Comment by rhatdan** [comment]
Looks like this is fixed now.

$ ./bin/podman run --rm quay.io/podman/stable:latest cat /etc/redhat-release
Fedora release 35 (Thirty Five)

**Comment by Luap99** [comment]
This is still a poor ux IMO.

**Comment by rhatdan** [comment]
I agree, but I don't think pulling in a non improved package into fedora is a great improvement.

**Comment by cevich** [comment]
Certainly, and perhaps that need extends beyond 4.0 + current fedora?  Should we do a `:rawhide` (assuming it exists) + upstream podman maybe?  In any case, F36 will be here shortly and I'm sure we'll get more "feedback" than we're able to handle in a day :grinning:

**Comment by lsm5** [comment]
> Certainly, and perhaps that need extends beyond 4.0 + current fedora? Should we do a `:rawhide` (assuming it exists) + upstream podman maybe? In any case, F36 will be here shortly and I'm sure we'll get more "feedback" than we're able to handle in a day grinning

rawhide tag does exist in the fedora container image and seems to get built regularly (maybe with every compose) as dnf update doesn't seem to update anything.

**Comment by rhatdan** [comment]
Problem with that, is I believe Rawhide now == f37, so there is no f36 release.  If everyone wants to hack this until f36 is released, I can live with it.

**Comment by lsm5** [comment]
there's also a fedora:36 published btw.
