### ISSUE TITLE
Documentation: setup with VS Code

### ISSUE THREAD

**Issue by fulldecent** [containers/podman#13589]
I am requesting please that a complete setup guide for podman with VS Code be added and maintained as part of our official documentation. Just like this but substituting Docker for podman: https://code.visualstudio.com/docs/remote/create-dev-container

# Why

VS Code is a major use case, they have excellent support for containers and their support is viral. **When you open a git repo configured for containers, VS Code encourages you to set up containers.**

By default they recommend Docker and have one-click install. They also support podman but it is not as easy and when something goes wrong people are very likely to give up. 

Most people I see considering podman in this scenario are doing so because they do not want to install a daemon or grant root access (running random repositories you download from the internet is dangerous, especially this week when millions of random projects unwittingly include a `rm -rf` in the install process as part of a Russia protest), or don't like Docker Desktop licensing.

**An official support document is a large opportunity to grow adoption of podman.**

# How

Part 1—make it work

- [X] Identify a popular devops scenario that podman can make 10× better. ✅ DONE, GitHub pages is such a scenario.
- [x] Implement a `.devcontainer` for this devops scenario. ✅ DONE, implemented at https://github.com/fulldecent/blog.phor.net/tree/main/.devcontainer
- [X] Confirm it works locally in VS Code with Docker Desktop on macOS/M1 and on the web with GitHub Codespaces. ✅ DONE, testing successful
- [ ] Figure out how to install podman and configure podman in VS Code so that it works the way it is currently ^^ working with Docker Desktop

Part 2—document it

1. Buy a new MacBook. 
1. Install VS Code. 
1. Do not install Xcode tools or ANYTHING else. 
1. Begin documenting every step now. 
1. Do things, make the fun project above run inside VS Code. 
1. End documenting, publish to podman website and feature prominently. 

Follow on work

- [ ] Repeat this process on latest Windows. 
- [ ] Repeat this process on latest Ubuntu.

**Comment by baude** [comment]
@fulldecent thanks for the submission.  We are actually in the process of writing that exact kind of thing!  your request suggests we are on the right track!  assigning to @jwhonce as the author

**Comment by TomSweeneyRedHat** [comment]
@fulldecent, IDK if it's of use, but we have a video by Chris Short on our YouTube channel demoing how he does it.  I know it doesn't take the place of a document, but it might be a stop-gap for you or others finding this issue:  https://www.youtube.com/watch?v=FnBzu3X9AMs&t=2s

**Comment by fulldecent** [comment]
Thank you. I have watched the video and it does not appear to have anything to do with podman integration. It seems like he is just using VS Code to SSH into another box. And he is running manual podman commands in the terminal on those boxes.

The possibilities for VS Code integration are much greater. You are able to open a repository, not know anything about podman, not have access to other servers, not have Go installed, and then suddenly you are compiling Go programs in a safe container.

**Comment by fulldecent** [comment]
A great use case for Podman + VS code + GitHub will be for GitHub Pages repositories.

Here is one example GitHub Pages repository: https://github.com/fulldecent/blog.phor.net

GitHub Pages is hosted with Jekyll which can be difficult to install, especially on macOS. Also, this installation has been related some security issues in the past.

A simple podman, no-root install would be a blessing for this application and it allows people to run these websites locally without installing any tools other than podman and it will integrate beautifully with VS Code.

**Comment by fulldecent** [comment]
BOUNTY NOTICE:

Pacific Medical Training commits a USD 200 bounty to whoever can resolve this issue.

Terms:

- Offer is effective for 60 days, through May 30th.
- Output includes: creating the documentation for setting up podman+VS Code+Jekyll for https://github.com/fulldecent/blog.phor.net to build and run the GitHub Pages website locally, result must be accepted/published by the podman project.
- Recipient must be allowed to receive payments from the United States (i.e. from PayPal).

**Comment by fulldecent** [comment]
Now doubling the bounty to USD 400. Same deadline.

**Comment by baude** [comment]
@fulldecent not interested in the money ... is there a docker version of this document?

**Comment by fulldecent** [comment]
@baude Yes, there is lot's of progress here https://code.visualstudio.com/docs/remote/create-dev-container

---

My goal here is to get a better version of that (I know it's hard to compete with VS Code documentation!) sporting a very practical example (GitHub Pages) and using our favored container manager (Podman).

And I know I didn't share this goal above, but after we are done with this issue, then the goal is to replace VS Code's default from Docker to Podman.

**Comment by rhatdan** [comment]
@fulldecent @baude What is the state of this?

**Comment by baude** [comment]
nothing from my side

**Comment by fulldecent** [comment]
Have made some progress here.

Updated the top issue and published a repo that works with Docker Desktop and GitHub Codespaces.

UPDATE AT https://github.com/containers/podman/issues/13589#issue-1176685876

**Comment by rhatdan** [comment]
Please open a PR to add this document.

**Comment by fulldecent** [comment]
@rhatdan PR started at https://github.com/containers/podman/pull/15254

**Comment by Luap99** [comment]
https://blog.podman.io/2024/10/support-for-dev-containers-features-on-macos-and-windows/
