### ISSUE TITLE
Support seccomp-notify-socket and seccomp-notify-plugins option sent to conmon

### ISSUE THREAD

**Issue by sfc-gh-hyu** [containers/podman#13603]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
Latest conmon support two new options: `--seccomp-notify-socket` and `--seccomp-notify-plugins` which allows user to load a dynamic library as a plugin to handle seccomp user notification. However, there is no way to pass those two options to conmon. [Here](https://www.scrivano.org/posts/2020-08-10-seccomp-notifications/) is a good blog post describing what those two options are used for. More generally, I see that `podman run` support general `--runtime-arg` for arguments being sent to runc. Wondering if it make sense to have something like `--conmon-arg` to so that I can pass those two options to conmon.

**Comment by vrothberg** [comment]
Thanks for reaching out, @sfc-gh-hyu!

@giuseppe PTAL

**Comment by giuseppe** [comment]
I've tried to do that in the past but I've not come up with a nice UX.  Do you have any suggestions how this should look like without the user having to know about internal details as seccomp-notify-socket)?

**Comment by sfc-gh-hyu** [comment]
@giuseppe Can we just add a new option `--conmon-seccomp-notify-plugin`?

**Comment by giuseppe** [comment]
sure.

Would you like to open a PR?  That would be the quickest way to move forward

**Comment by sfc-gh-hyu** [comment]
Sure. Do you have any recommendation/best practice on where to put this `seccomp-notify-socket`?

**Comment by giuseppe** [comment]
do you mean `--conmon-seccomp-notify-plugin`?

To start playing with it, I'd suggest it becomes part of `--security-opt`, e.g. `--security-opt seccomp-notify-plugins=....`

**Comment by sfc-gh-hyu** [comment]
No what I mean is that ideally, we want to hide `seccomp-notify-socket` from end users. End users only need to pass the path to the plugin ( a.k.a. a dynamic library). But conmon need to unix domain socket so that kernel can return the notification back to userspace. I think podman should mange this unix domain socket, i.e. create this unix domain socket somewhere in the filesystem, and pass this unix domain socket to conmon. I am asking do you have an idea on where we should create a such unix domain socket file?

**Comment by giuseppe** [comment]
it should probably be some internal path under the podman rundir (e.g. `/run/user/1000/libpod/tmp/$CONTAINER_ID-notify`)

**Comment by sfc-gh-hyu** [comment]
Sounds good. I will see if I can figure something out and submit a pr.

**Comment by sfc-gh-hyu** [comment]
@rhatdan I am not sure if I understand question correctly. I am thinking that if `--conmon-seccomp-notify-plugins` is provided to podman during the run or exec command, then podman should try to setup socket, and pass to both plugins and socket to conmon?

**Comment by rhatdan** [comment]
Ok so you are saying the user would do somethin like:

podman run --security-opt seccomp:notify ...

**Comment by sfc-gh-hyu** [comment]
I would imagine that for certain syscalls, user will say ALLOW or KILL directly, but for other syscalls, it will deferred the decision to the user space. Check example here: https://man7.org/linux/man-pages/man2/seccomp_unotify.2.html It really just depends on how user write the seccomp bpf program, ( or how the seccomp policy file is written ). So I think user would do something like `podman run --security-opt seccomp=profile.json`, while json will say for syscall like `clone`, it will do a `SECCOMP_RET_USER_NOTIF`. However, if customer do something like `podman run --security-opt seccomp=profile.json --conmon-seccomp-notify-plugins /usr/local/lib64/syscall_handle.so ...` then podman will setup the unix domain socket to receive the notification from kernel.

**Comment by rhatdan** [comment]
Shouldn't Podman just review the profile.json file looking for SECCOMP_RET_USER_NOTIF and setup the socket?  User would not need to add input?

**Comment by sfc-gh-hyu** [comment]
Yeah, I think that should work as well. I am not aware that podman has the capability to parse the content of profile.json.

**Comment by rhatdan** [comment]
It doesn't but it could be added, WDYT @giuseppe

**Comment by giuseppe** [comment]
podman uses the content of `profile.json`.  The content in `profile.json` is parsed by Podmand and converted to a configuration usable by the OCI runtime.

We would still need to pass the plugins though (or configure them in `containers.conf`).

@haircommander would it be possible with `conmon-rs` to load `.so` files so we can support seccomp plugins as well?

**Comment by rhatdan** [comment]
@giuseppe @haircommander Did anything ever happen with this?

**Comment by giuseppe** [comment]
not that I am aware of.

@sfc-gh-hyu are you still interested?
