### ISSUE TITLE
Container signing against an HSM.

### ISSUE THREAD

**Issue by countofsanfrancisco** [containers/podman#13601]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

** Container Signing against an HSM (Hardware Security Module) **

According to docs/tutorials/image_signing.md, the private key needs to be on the same server as the signing server. In my infrastructure this is not possible as the private key is protected by an HSM. Is it possible to either (a) produce a document that outlines the format of a signed container so that we can write the code ourselves to produce the same format that podman expects or (b) provide hook points in the signing process to send the hash(es) for signing and expect a signature back.

I prefer option (a)

**Describe the results you received:**

Does not look like it is possible today according to image_signing.md.

**Describe the results you expected:**

The ability to sign a container against a private key held on an HSM.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes but found nothing mentioning how to do what i want to do.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
I'll tag @mtrmac and @vrothberg given their work on cosign

**Comment by mtrmac** [comment]
a) https://github.com/containers/image/tree/main/docs 

b) see #6259 .

Cosign would entirely change a); as for b), the supportability/testing concerns would stay the same, and continue to likely be a blocker; the _technology_ is very different (quite likely impacting which HSMs are usable).

**Comment by mheon** [comment]
Any chance Cosign would let us delegate the HSM bits to their upstream? Or was that too much to hope?

**Comment by mheon** [comment]
Regardless, closing as dupe of #6259

**Comment by mtrmac** [comment]
> Any chance Cosign would let us delegate the HSM bits to their upstream? Or was that too much to hope?

To an extent. There is quite a lot of various interoperability code there (including _some_ PKCS#11 support); but most of that is something we can’t practically test, so it’s unclear that we would want to ship it in Podman. It’s definitely not going to be a part of our _first_ version.

Cosign could help in the sense that it would be possible to use Podman to create an image, and then use the the upstream `cosign` utility to sign images (**assuming they are on a trusted storage mechanism (e.g. a registry) between creating and signing**) — and the two are expected to be interoperable.
