### ISSUE TITLE
Improving directory structure within libpod

### ISSUE THREAD

**Issue by kbaran1998** [containers/podman#13612]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

While going through the `libpod` directory, I saw that 72 `.go` files were not placed into sub-directories, making it challenging to go through it and find a specific file within some logical structure. It is a bit of a nit, but I think it could improve the development experience.

**Steps to reproduce the issue:**

1. Install `tree` if needed:
```bash
sudo apt install tree
```
2. Run:
```bash
cd libpod
tree -L 1 .
```

**Describe the results you received:**

```
.
├── boltdb_state.go
├── boltdb_state_internal.go
├── boltdb_state_linux.go
├── common
├── common_test.go
├── container.go
├── container_api.go
├── container_commit.go
├── container_config.go
├── container_copy_linux.go
├── container_exec.go
├── container_graph.go
├── container_graph_test.go
├── container_inspect.go
├── container_internal.go
├── container_internal_linux.go
├── container_internal_linux_test.go
├── container_internal_test.go
├── container_linux.go
├── container_log.go
├── container_log_linux.go
├── container_log_unsupported.go
├── container_path_resolution.go
├── container_stat_linux.go
├── container_top_linux.go
├── container_validate.go
├── define
├── diff.go
├── driver
├── events
├── events.go
├── healthcheck.go
├── healthcheck_linux.go
├── info.go
├── kube.go
├── layers
├── linkmode
├── lock
├── logs
├── mounts_linux.go
├── networking_linux.go
├── networking_linux_test.go
├── networking_machine.go
├── networking_slirp4netns.go
├── oci.go
├── oci_attach_linux.go
├── oci_conmon.go
├── oci_conmon_exec_linux.go
├── oci_conmon_linux.go
├── oci_missing.go
├── oci_util.go
├── options.go
├── plugin
├── pod.go
├── pod_api.go
├── pod_internal.go
├── pod_status.go
├── pod_top_linux.go
├── reset.go
├── runtime.go
├── runtime_cstorage.go
├── runtime_ctr.go
├── runtime_img.go
├── runtime_migrate.go
├── runtime_pod.go
├── runtime_pod_linux.go
├── runtime_renumber.go
├── runtime_volume.go
├── runtime_volume_linux.go
├── shutdown
├── state.go
├── state_test.go
├── stats.go
├── storage.go
├── util.go
├── util_linux.go
├── util_linux_test.go
├── util_test.go
├── volume.go
├── volume_inspect.go
├── volume_internal.go
└── volume_internal_linux.go
```

**Describe the results you expected:**

A rough proposal:

```
.
├── boltdb
├── common
├── container
├── define
├── diff.go
├── driver
├── events
├── events.go
├── healthcheck
├── info.go
├── kube.go
├── layers
├── linkmode
├── lock
├── logs
├── mounts_linux.go
├── networking
├── oci
├── options.go
├── plugin
├── pod
├── reset.go
├── runtime
├── shutdown
├── state
├── stats.go
├── storage.go
├── util
└── volume
```

**Comment by Luap99** [comment]
While I agree that libpod package is supper big and hard to browse most stuff needs to be there. The way go code works each directory is one package.

Splitting this would be a huge amount of work for almost no benefit

**Comment by mheon** [comment]
The Libpod god-package is also mostly deliberate, and due to Go's visibility rules. The original Libpod API design (from waaaay back - I don't think it was ever committed to Git) had libpod/containers, libpod/pods, libpod/images, but that required making a lot of implementation details (e.g. direct access to the public container store) in Libpod become public, and we did not want these in the public API. I really wish that Go had an additional visibility setting (a bit similar to Java's `protected`) that let us declare functions as available to a package and all its subpackages only.

**Comment by vrothberg** [comment]
> I really wish that Go had an additional visibility setting (a bit similar to Java's protected) that let us declare functions as available to a package and all its subpackages only.

Go supports that if a package is placed under a `internal` directory.  In theory, there could be a `libpod/internal` package: everything behind that is only accessible to `libpod` but not to the outside.

**Comment by vrothberg** [comment]
> AFAIK everything inside the go module can access it, so pkg/ and cmd/podman could still see it.

Nope that's not allowed:
```
test $ tree
.
├── foo
│   └── internal
│       └── bar
│           └── bar.go
├── go.mod
└── main.go

3 directories, 3 files
test $ cat main.go 
package main

import (
        "fmt"

        "foo.com/foo/internal/bar"
)

func main() {
        fmt.Println("vim-go")
        bar.Bar()
}
test $ go run main.go
package command-line-arguments
        main.go:6:2: use of internal package foo.com/foo/internal/bar not allowed
```

**Comment by vrothberg** [comment]
We're making quite some use of that in containers/image to evolve the internal API without breaking the external one.

**Comment by vrothberg** [comment]
I am going to close the issue. `libpod` is a large package but I am convinced the code can be browsed conveniently when using proper tooling (IDEs, vim-go, vgrep, etc.).
