### ISSUE TITLE
Allow `podman wait` to wait on healthy state

### ISSUE THREAD

**Issue by svenstaro** [containers/podman#13627]
/kind feature

**Description**

I'd like for `podman wait` to be able to wait until a container is healthy. Currently we are using an external blocking command that's exactly the same as the health command and I think this could be made to be more elegant. This scenario crops up if starting a container in detached mode for integration testing, for instance.

I think this might be easy to add considering podman is already internally aware of the health state. I know that `podman wait` has the tag line "Block until one or more containers stop and then print their exit codes." but why limit it to just that?

**Steps to reproduce the issue:**

1. `podman wait --condition healthy`

**Describe the results you received:**

Currently this is not supported.

**Describe the results you expected:**

Would be great if `podman wait` could block until the container is considered healthy.

**Comment by rhatdan** [comment]
@vrothberg @baude @mheon Thoughts?

**Comment by vrothberg** [comment]
I like the idea, thanks for proposing

**Comment by keonchennl** [comment]
May I work on this?

**Comment by rhatdan** [comment]
Sure

**Comment by svenstaro** [comment]
@keonchennl Did you get some work done on this?

**Comment by vrothberg** [comment]
Sure, I can take a look.

**Comment by vrothberg** [comment]
@mheon, are you cool if I add new container states (ContainerStatus{Healthy,Unhealthy})?

Unfortunately, the (remote) API uses `[]define.ContainerStatus` for the waiting conditions instead of strings.  Without breaking the API or ugly workarounds, I don't see another way.

**Comment by vrothberg** [comment]
@mheon ping

**Comment by mheon** [comment]
Github somehow ate my response. Copying and pasting:

Feels like a bad idea, we'd be enshrining a hack into the API and forcing us to support it for the foreseeable future. Maybe add an extra bool flag for "Healthy" state, so we can wait on ContainerStateRunning and Healthy=true?

**Comment by vrothberg** [comment]
> Feels like a bad idea, we'd be enshrining a hack into the API and forcing us to support it for the foreseeable future. Maybe add an extra bool flag for "Healthy" state, so we can wait on ContainerStateRunning and Healthy=true?

Not sure how to do that without breaking the (remote) API and the bindings:
```golang
type WaitOptions struct {                 
        Condition []define.ContainerStatus
        Interval  time.Duration           
        Latest    bool                    
}                                         
```

**Comment by vrothberg** [comment]
@rhatdan I am freeing this for interns since I'll be on PTO next week but let's first discuss what needs to be done before re-assigning it.

**Comment by svenstaro** [comment]
I still have interest in getting this feature request filled and there seemed to be some interest from upstream to implement it.

**Comment by rhatdan** [comment]
@ashley-cui @vrothberg @mheon @umohnani8 Something for interns?

**Comment by vrothberg** [comment]
Maybe but it must be groomed/designed.  There is also a request to support restart policies (i.e., restart when unhealthy) which would be considered.

**Comment by svenstaro** [comment]
Bump

**Comment by vrothberg** [comment]
@baude @rhatdan 

I think this is adjacent to https://bugzilla.redhat.com/show_bug.cgi?id=2097708.  Probably worth keeping in mind when planning/designing work.

**Comment by svenstaro** [comment]
Bump

**Comment by rhatdan** [comment]
Since we now have the restart policy, does it make sense to move forward on this?

**Comment by vrothberg** [comment]
> Since we now have the restart policy, does it make sense to move forward on this?

They are conceptually unrelated.  In order to work on it we need to find consensus on how to implement it, see https://github.com/containers/podman/issues/13627#issuecomment-1139545682.

**Comment by rhatdan** [comment]
@mheon Thoughts?

**Comment by mheon** [comment]
IMO: Add a `Healthy` bool to the existing struct (or create a new, separate array just of strings, to allow more versatile argument passing), and allow that to be set instead of the existing conditions array. That allows us to not make a breaking change, but support new functionality.

**Comment by rhatdan** [comment]
Seems like we would have three states, unkown, healthy and unhealthy.  So I don't think a bool would work

**Comment by mheon** [comment]
Feels like a bad idea, we'd be enshrining a hack into the API and forcing
us to support it for the foreseeable future. Maybe add an extra bool flag
for "Healthy" state, so we can wait on ContainerStateRunning and
Healthy=true?

**Comment by svenstaro** [comment]
Has there been any movement on this?

**Comment by rhatdan** [comment]
Not that I am aware of, interested in opening a PR?

**Comment by svenstaro** [comment]
There seems to have been some back and forth on the design of this and until that's decided on ideally by the project, I think a PR would likely not get merged.

**Comment by rhatdan** [comment]
I think if you opened a PR matching what @mheon suggested it would be more likely to get merged.

**Comment by vrothberg** [comment]
I'm no fan of adding a single boolean since it allows for only one state but I think we need means to further extend the wait endpoint to handle more conditions.

Currently, the endpoint uses define.ContainerStatus which @mheon does not want to extend with non-status conditions (e.g., health):
```golang
type WaitOptions struct {                 
        Condition []define.ContainerStatus
        Interval  time.Duration           
        Latest    bool                    
}                                         
```

Hence, I think we should add a new field `Conditions []string`:
```golang
type WaitOptions struct {                 
        // Condition is deprecated, please use the `Conditions` field instead.
        Condition []define.ContainerStatus
        // ...
        Conditions []string
        Interval  time.Duration           
        Latest    bool                    
}  
```

The untyped string can be easier dealt with and extended.

Since this is blocking  #6160, I'd like to push things forward.

@Luap99 @mheon @rhatdan WDYT?

**Comment by Luap99** [comment]
Adding a new field sounds good to me.

**Comment by danishprakash** [comment]
@vrothberg are you still looking into this?

**Comment by vrothberg** [comment]
Yes, currently waiting for feedback from more maintainers.  Once the design is agreed on, we can implement it.

**Comment by vrothberg** [comment]
Great, I'll take a stab at it.

**Comment by vrothberg** [comment]
Opened https://github.com/containers/podman/pull/18974
