### ISSUE TITLE
Allow to manage existing podman machine cpu/memory/disk through cli

### ISSUE THREAD

**Issue by benoitf** [containers/podman#13633]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

As a user, you start a podman machine (probably using defaults)

Then at some point, you want to increase the memory or cpu or even the disk size
Or also decrease the settings because you want to adjust to your needs.

But this is not possible easily today.

`podman machine set` command allows only to update `--rootful` option

you may delete and recreate a machine but then you're losing all containers/existing images so this is not an expected behaviour.

It seems to be possible to tweak `$HOME.config/containers/podman/machine/qemu/podman-machine-default.json` by editing CPUs and smp parameter for the cpu but from a user point of view, we shouldn't edit qemu files.

**Steps to reproduce the issue:**

1. Create and start a podman machine

2. Wants to tweak cpu/memory/disk settings

**Describe the results you received:**

not possible through cli

**Describe the results you expected:**

it should be possible to do for example

```
podman machine set --cpus=2
podman machine set --disk-size=20
podman machine set --memory=4096
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
4.0.2
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Luap99** [comment]
Disk could be difficult because we would need to change the file system size as well.

The other ones should be easy to implement.
