### ISSUE TITLE
[macOS] Error: for attach: setxattr

### ISSUE THREAD

**Issue by fithisux** [containers/podman#13631]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I tried to attach a folder for busybox ls (sanity check) in my MacOS laptop through podman

**Steps to reproduce the issue:**

1. podman machine init -v /Users/vassilisanagnostopoulos:/mnt/Users/vassilisanagnostopoulos foo

2.podman run -it --volume /mnt/Users/vassilisanagnostopoulos/work:/share:z busybox ls

3.

**Describe the results you received:**

Error: error preparing container cf050ad434f57d762d589b0bee8e4aee68682d7676f7ceaeb7b16ab8970b7d30 for attach: setxattr /mnt/Users/vassilisanagnostopoulos/work: operation not supported

**Describe the results you expected:**

To be an empty list, afterall work is empty

**Additional information you deem important (e.g. issue happens only occasionally):**

Podman installed through brew and updated everything through `brew update && brew upgrade`

**Output of `podman version`:**

```
podman version
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.8

Built:      Wed Mar  2 16:04:36 2022
OS/Arch:    darwin/amd64

Server:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.16.14

Built:      Thu Mar  3 16:56:56 2022
OS/Arch:    linux/amd64
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "35"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 502
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 5.15.18-200.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1340514304
  memTotal: 2061381632
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.2-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.2
      commit: f6fbc8f840df1a414f31a60953ae514fa497c748
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/502/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 2h 31m 48.63s (Approximately 0.08 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 0
    stopped: 6
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/502/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1646319416
  BuiltTime: Thu Mar  3 16:56:56 2022
  GitCommit: ""
  GoVersion: go1.16.14
  OsArch: linux/amd64
  Version: 4.0.2
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Darwin C02CH2W2MD6R.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

**Comment by Luap99** [comment]
Does it work when you remove the `:z`?

**Comment by fithisux** [comment]
> Does it work when you remove the `:z`?

Yes it does. What is this z ?

**Comment by Luap99** [comment]
z stand for selinux relabeling which requires extended attributes. I am not sure if virtiofs support this.
https://github.com/containers/podman/blob/main/docs/source/markdown/podman-run.1.md#--volume--vsource-volumehost-dircontainer-diroptions

If it works without out it you do not need it.

cc @baude @rhatdan

**Comment by rhatdan** [comment]
Mac file systems based on Plan 9 does not support SELinux labeling `z` and `Z` should not be used.  When we transition to use virtiofsd, it should support SELinux labeling, and then we can use it for better container separation on the MAC.

Currently the volumes mounted into the VM are labeled as nfs_t, and all containers are allowed to read/write the content.

**Comment by arlyon** [comment]
Hey

I am currently trying to support macOS and linux (fedora) machines using the same `play kube` file. Is there a recommended approach here? Or is the answer "not cross platform _yet_"

**Comment by rhatdan** [comment]
Please open a new issue.  Do not add to a closed issue.  Podman play kube should work on a MacOS

**Comment by ActuallyHappening** [comment]
To save people from struggling,
use docker.
