### ISSUE TITLE
--sysctl kernel.msgmax=<value> in rootless container

### ISSUE THREAD

**Issue by mlegenovic** [containers/podman#13661]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind question

**Description**

Is it possible to use --sysctl argument for rootless container?

From documentation:

_--sysctl=name=value_

_Configure namespaced kernel parameters at runtime._

_For the IPC namespace, the following sysctls are allowed:_

_- kernel.msgmax_
_- ..._

There is no hint that this argument is not usable for rootless containers, but if I try to set a value, I get error message:

```
podman run -it --rm --sysctl kernel.msgmax=16384 registry.fedoraproject.org/fedora:35
Error: open /proc/sys/kernel/msgmax: Permission denied: OCI permission denied
```

--privileged flag also does not help:

```
podman run -it --rm --privileged --sysctl kernel.msgmax=16384 registry.fedoraproject.org/fedora:35
Error: open /proc/sys/kernel/msgmax: Permission denied: OCI permission denied
```

On my host msgmax is set to larger value, so I'm not trying to set larger value in container then on host.

Is the only option to have other value for msgmax to use --ipc=host?

**Comment by mheon** [comment]
Because of the inherently unprivileged nature of rootless Podman, most sysctls are not going to work (it might even be *all* sysctls, but I don't know enough to answer that definitively, and will defer to @giuseppe for that). It seems like we need to update the manpages to indicate the `--sysctl` generally requires root privileges.

**Comment by giuseppe** [comment]
it depends on the sysctl.  Some of them are namespace, some others are not.

In the specific case of `kernel.msgmax`, it is namespace but only root in the initial user namespace (i.e. the real root), can write to it:

```
$ podman run --privileged -it --rm  fedora sh
sh-5.1# cat /proc/sys/kernel/msgmax
8192
sh-5.1# echo 8193 > /proc/sys/kernel/msgmax
sh: /proc/sys/kernel/msgmax: Permission denied

(from another terminal)
$ sudo nsenter -m -i  -t `podman inspect -l -f '{{.State.Pid}}'` bash

(and back to the container tty)

sh-5.1# cat /proc/sys/kernel/msgmax
8193
```
