### ISSUE TITLE
Unexpected output from `quay.io/libpod/banner` in Basic Networking Guide for Podman tutorial

### ISSUE THREAD

**Issue by robin-a-meade** [containers/podman#13685]
/kind bug

**Description**

I receive unexpected output when carrying out the steps of the tutorial [Basic Networking Guide for Podman](https://github.com/containers/podman/blob/main/docs/tutorials/basic_networking.md).

**Describe the results you received:**

```
$ curl http://127.0.0.1:8080
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
And same for `curl http://127.0.0.1:8081`.

**Describe the results you expected:**

```
$ curl http://127.0.0.1:8080
   ___           __
  / _ \___  ___/ /_ _  ___ ____
 / ___/ _ \/ _  /  ' \/ _ `/ _ \
/_/   \___/\_,_/_/_/_/\_,_/_//_/
```
And same for `curl http://127.0.0.1:8081`.

**Additional information you deem important (e.g. issue happens only occasionally):**

It's probably a problem with the image `quay.io/libpod/banner`. (Where is the source code for the image located?)

**Output of `podman version`:**

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 11:45:07 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    variant: workstation
    version: "35"
  eventLogger: journald
  hostname: nuc
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.16.16-200.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 17559465984
  memTotal: 33536753664
  ociRuntime:
    name: crun
    package: crun-1.4.3-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.3
      commit: 61c9600d1335127eba65632731e2d72bc3f0b9e8
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 54h 10m 4.93s (Approximately 2.25 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/robin/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/robin/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /home/robin/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 1638999907
  BuiltTime: Wed Dec  8 11:45:07 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.4-1.fc35.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

bare metal

**Comment by Luap99** [comment]
@baude PTAL

**Comment by rhatdan** [comment]
Could you try this on podman 4.0?

**Comment by robin-a-meade** [comment]
I got the same result using `podman 4.0.2` (I used the latest pre-release iso of Fedora 36 running in a Gnome Boxes VM.)

I'm pretty sure the problem is that the `quay.io/libpod/banner` image has been broken for the past 6 months. It does not print a banner. It only prints a 404 error page.

I got further through this tutorial when I switched from `quay.io/libpod/banner` to the Nginx Docker image discussed in Podman's [Introduction](https://docs.podman.io/en/latest/Introduction.html). (except that image does not include `curl` so I couldn't perform the last step about _"From another rootless container..."_)

**Comment by Luap99** [comment]
@baude please fix the image

**Comment by TerraTech** [comment]
I too ran into this today while I was working with Podman + netavark and needed a quick-n-dirty http response server.

The problem within the container is that the file:  `/etc/nginx/conf.d/default.conf` should have been placed in `/etc/nginx/http.d/default.conf`.  The existing `http.d/default.conf` is hardwired to only return a 404 result.

Once I moved it (`conf.d/default.conf`) and invoked:  `nginx -s reload`, the banner worked correctly.

HTH.

**Comment by rhatdan** [comment]
Where is this image defined?

**Comment by rhatdan** [comment]
@baude did you ever get to this?

**Comment by baude** [comment]
yup.
