### ISSUE TITLE
Podman and VPN IP Address conflicts

### ISSUE THREAD

**Issue by edowado** [containers/podman#13702]
/kind bug

**Description**

I'm running fedora 34 and installing podman and podman compose broke my VPN (removing it the same way I installed it - with dnf- did not fix the issue).
Is there a way to completely purge podman from my system and bring the changes back?

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Comment by Luap99** [comment]
If you run as root, the default cni network with the `10.88.0.0/16` subnet is used.
A reboot should fix the temporary interfaces and iptables rules. Otherwise you need to remove the cni-podman0 interface manually.

If podman is run rootless it should not conflict with any host network settings.

**Comment by baude** [comment]
this can be avoided by changing the default subnet in containers.conf.  I believe, however, you will need a newer version that what is available with F34.

**Comment by edowado** [comment]
Thanks for the replies everyone, 
I still haven't found the issue, but purging and installing the vpn from scratch seems like it solved my issue :shrug: 
I will re-open if it reoccures.
