### ISSUE TITLE
podman info --format does not work with go template format with store/host

### ISSUE THREAD

**Issue by martinetd** [containers/podman#13709]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'd like to print some specific field of podman info with --format and it doesn't seem to work, or I couldn't figure out the correct syntax:
```
$ ./bin/podman info --format '{{.store.runRoot}}'
Error: template: info:1:8: executing "info" at <.store.runRoot>: can't evaluate field store in type *define.Info
```

compared to the json output or version:
```
$ ./bin/podman info --format json | jq '.store.runRoot'
"/run/user/1000/containers"
$ ./bin/podman info -f "{{.Version}}"
{4.0.0-dev 4.0.0-dev go1.17.8 a2d7fb0c66441450c9169bebdefa07993759fa5b Tue Mar 29 17:01:09 2022 1648540869 linux/amd64}
```

**Steps to reproduce the issue:**

1. `podman info --format '{{.store.runRoot}}'`

2. notice error

**Describe the results you received:**

It failed.

**Describe the results you expected:**

It should report the store.runRoot? (did I already say I hate these bug templates?)

**Additional information you deem important (e.g. issue happens only occasionally):**

Looking at the type info definition here:
https://github.com/containers/podman/blob/main/libpod/define/info.go#L7
and the solution to #11265 , I've confirmed that direct objects e.g. `.Version` works, it's just the pointers (or whatever that wildcard character means) that fail to be found.
I tried various variants (StoreInfo, *StoreInfo, without capitalization etc) to no avail.

I'm not sure how that introspection is supposed to work, so advice on proper syntax (if there is one) would be appreciated.
If not, just writing in the documentation it won't work is good enough for me, I can scrape the json for this particular usecase and just wanted to report the error ot make sure it's intended.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.17.8
Git Commit:   a2d7fb0c66441450c9169bebdefa07993759fa5b
Built:        Tue Mar 29 17:01:09 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

not relevant here

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

built from git

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Comment by Luap99** [comment]
The golang struct field in a template must always be exported (aka start with an upercase letter). So the naming convention is pascal case.

`podman info --format {{.Store.RunRoot}}` works,
btw you get shell completion for this when you type `podman info --format {{.` and press tab.
