### ISSUE TITLE
podman machine list report machine being running before machine is really usable

### ISSUE THREAD

**Issue by benoitf** [containers/podman#13711]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Start a podman machine (like the default one) using `podman machine start`

And check 'podman machine list' result
You'll notice that the machine goes in state 'Running' before that the machine is really Running.

**Steps to reproduce the issue:**

1. run script `while true;do clear; podman machine list; sleep 1;done` in one terminal

2.`podman machine start` in another terminal

3. Check that the machine goes in 'up/running' state before we see the message stating the machine is running in the terminal where we launched the podman machine.

https://user-images.githubusercontent.com/436777/160791334-9a17621c-0b72-468f-8682-9027c31b9a6e.mp4

**Describe the results you received:**

Running state is displayed too early. For example socket isn't available while it says it's 'Running'

**Describe the results you expected:**

Machine should be in `Running` state when we see the message

```
Machine "podman-machine-default" started successfully
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
4.0.2 / macOS
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@baude PTAL

**Comment by cdoern** [comment]
yes @baude sorry for the late reply I will look at this first thing in the morning

**Comment by benoitf** [comment]
also it would be interesting to get intermediate step like `Starting` before it goes to `Running` state
And the same with `Stopping` before it goes to `Stopped`

**Comment by rhatdan** [comment]
@cdoern Did you open a PR?

**Comment by cdoern** [comment]
@rhatdan no I am working on it tonight I will ping if I get one open in time for demos

**Comment by cdoern** [comment]
There are a couple ways I could fix this @baude @rhatdan do you think I should submit a PR in qemu to add a `Starting` status? that would fit the best with the way `checkStatus` currently works

**Comment by rhatdan** [comment]
What does checkStatus currently say when the qemu is starting?  Started?

**Comment by benoitf** [comment]
I think the Starting/Started may be different than the qemu one

podman machine start : goes in `Starting` mode and it reaches `Started` only when everything is fully setup on podman machine side (it may be a couple of seconds after qemu says the VM is Started as it'll when machine can be used from a podman side)

**Comment by cdoern** [comment]
figured out a fix without having to go into qemu... will make a PR tonight
