### ISSUE TITLE
Can't install dependency python?

### ISSUE THREAD

**Issue by minesunny** [containers/podman#13736]
==> Pouring python@3.9-3.9.10.arm64_monterey.bottle.tar.gz
Error: No such file or directory @ rb_sysopen - /Users/mine/Library/Caches/Homebrew/downloads/cdd0b8d6d70c23220e916efb061f7619dd11a7bb369672723e538e9da834a79c--python@3.9-3.9.10.arm64_monterey.bottle.tar.gz

Library/Caches/Homebrew took 13s
➜ ls -lat | grep python
lrwxr-xr-x   1 mine  staff   123  3 31 21:17 python@3.9--3.9.10 -> downloads/c5993775e86a17f3dcea970efc004a3c2210790a255040e60d9c392c55e7df1a--python@3.9--3.9.10.arm64_monterey.bottle.tar.gz

lrwxr-xr-x   1 mine  staff   114  3 31 21:17 python@3.9_bottle_manifest--3.9.10 -> downloads/269953377ed89335a8cd22c98d16643eef3425b93f01c77109e4f261a36439d8--python@3.9-3.9.10.bottle_manifest.json

Sorry I can't upload image successfully. So I write some code logs.  there are two python directory downloaded when I run cmd "brew install podman",but at  the last step, it reports that "No such file or directory....", I don't know if I'm missing a file to download, or if something went wrong with the file naming. it is not only just Python, there are other files have the same problems。

**Comment by vrothberg** [comment]
@jwhonce PTAL

**Comment by vrothberg** [comment]
@ashley-cui PTAL

**Comment by rhatdan** [comment]
@minesunny are you still seeing this issue?  You are the only one to ever report this and we know thousands of users have been successful. I think there is something going on with your configuration. I am going to close, because I do not believe this is something that we can fix.  Conversation can continue here.
