### ISSUE TITLE
Most podman commands as user abort with "Error: cannot re-exec process"

### ISSUE THREAD

**Issue by m3nu** [containers/podman#13737]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Most podman commands as user abort with "Error: cannot re-exec process". E.g. `podman ps`. Using a **rootless** setup.

**Steps to reproduce the issue:**
Not fully sure how to reproduce this reliably. It seems to happen under high load. E.g. after rebooting a server with hundreds of rootless pods, about 10% will show this error. The root cause is a leftover PID file in `/run/user/$UID/libpod/tmp/pause.pid`, as described [here](https://github.com/containers/podman/issues/8647#issuecomment-881911751). The process in this PID file doesn't exist. Maybe it crashed or was killed for some reason.

**Describe the results you received:**
All Podman commands fail with "Error: cannot re-exec process". If Systemd is set up for this container, it will constantly try to restart, which causes high CPU load on the server. Simply deleting `pause.pid` resolves the error.

**Describe the results you expected:**
Podman should recover from a stale PID file.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.5

Built:      Fri Mar 18 11:51:13 2022
OS/Arch:    linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 8ef5de138efb6f0aad657082cdea22cf037792cb'
  cpus: 12
  distribution:
    distribution: '"centos"'
    version: "9"
  eventLogger: journald
  hostname: podhost6.eu.pikapods.com
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 3685
      size: 1
    - container_id: 1
      host_id: 38897312
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 3685
      size: 1
    - container_id: 1
      host_id: 38897312
      size: 65536
  kernel: 5.14.0-75.el9.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 114061340672
  memTotal: 269604548608
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun-1.4.4-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.4
      commit: 6521fcc5806f20f6187eb933f9f45130c86da230
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/3685/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.1.12-4.el9.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 73009192960
  swapTotal: 73009192960
  uptime: 7h 57m 2.11s (Approximately 0.29 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
  - docker.io
store:
  configFile: /srv/pods/p3685/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /var/lib/containers/storage
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.8.2-1.el9.x86_64
      Version: |-
        fusermount3 version: 3.10.2
        fuse-overlayfs: version 1.8.2
        FUSE library version 3.10.2
        using FUSE kernel interface version 7.31
  graphRoot: /srv/pods/p3685/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 56
  runRoot: /run/user/3685/containers
  volumePath: /srv/pods/p3685/.local/share/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1647604273
  BuiltTime: Fri Mar 18 11:51:13 2022
  GitCommit: ""
  GoVersion: go1.17.5
  OsArch: linux/amd64
  Version: 4.0.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.0.2-3.el9.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes. No related item found.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Centos Stream 9 with all updates applied and SELinux enabled.

`/run/user` folders are mounted as tmpfs and cleared during reboot.

```
tmpfs on /run/user/4275 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=26328568k,nr_inodes=6582142,mode=700,uid=4275,gid=4275,inode64)
tmpfs on /run/user/4276 type tmpfs (rw,nosuid,nodev,relatime,seclabel,size=26328568k,nr_inodes=6582142,mode=700,uid=4276,gid=4276,inode64)
```

**Comment by Luap99** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
could you verify if catatonit supports the `-P` flag?  Does `/usr/libexec/podman/catatonit -P` work fine for you (you can Ctrl-C the process once you verify it works)?

**Comment by rhatdan** [comment]
Does it work in permissive mode? Does it work as root.

**Comment by rhatdan** [comment]
@giuseppe What should we do with this issue?

**Comment by giuseppe** [comment]
we got no feedback, let's close for now

**Comment by m3nu** [comment]
Short update on this: Restarted another server today (CentOS 9) with the same setup and there was no issue with this. It has about 700 rootless pods and they all came up flawlessly. There wasn't a single stale pause.pid file to be found by my script.

Thanks anyways for looking into this! 🙏
