### ISSUE TITLE
IPv4 address is assigned automatically inside container when start the container with only ipv4 address specified

### ISSUE THREAD

**Issue by leolovejj** [containers/podman#13746]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I created the dual stack macvlan. While starting the container, only specifiy the ipv4 address, however, the IPv6 address is assigned automatically.

**Steps to reproduce the issue:**
1. Create dual stack macvlan with the following command:
[root@centos8 bin]# ./podman network create -d macvlan -o parent=ens192 --subnet=192.168.1.10/24 --gateway=192.168.1.1 --subnet=2630:210:f021:9011::/64 --gateway=2630:210:f021:9011::1 ens192
ens192
2. Inspect the network:
[root@centos8 bin]# ./podman inspect ens192
[
     {
          "name": "ens192",
          "id": "22e496b0a5ffb7abbe918389cdbad3e10e9961f562b4c3e59cd8bfb50773d055",
          "driver": "macvlan",
          "network_interface": "ens192",
          "created": "2022-04-02T02:09:38.745993904+08:00",
          "subnets": [
               {
                    "subnet": "192.168.1.0/24",
                    "gateway": "192.168.1.1"
               },
               {
                    "subnet": "2630:210:f021:9011::/64",
                    "gateway": "2630:210:f021:9011::1"
               }
          ],
          "ipv6_enabled": true,
          "internal": false,
          "dns_enabled": false,
          "ipam_options": {
               "driver": "host-local"
          }
     }
]
3. Start a container with only IPv4 address specified 
[root@centos8 bin]# docker image ls
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
REPOSITORY                TAG         IMAGE ID      CREATED       SIZE
localhost/netbackup/main  9.1         32572d8c0408  7 months ago  5.81 GB
[root@centos8 bin]# docker ps -a
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
[root@centos8 bin]# ./podman run -itd --name=master --network=ens192 **--ip=192.168.1.5** 32572d8c0408 /bin/bash
0863497a57ceee26362efae0cd5d85c497943a009193244761807341723b20ce
[root@centos8 bin]# docker ps -a
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
CONTAINER ID  IMAGE                         COMMAND     CREATED        STATUS            PORTS       NAMES
0863497a57ce  localhost/netbackup/main:9.1  /bin/bash   9 seconds ago  Up 6 seconds ago              master

**Describe the results you received:**
IPv6 address is assigned automatically
[root@centos8 bin]# ./podman exec -it 0863497a57ce /bin/bash
bash-4.2# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.5  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::cc5:84ff:fe6a:5498  prefixlen 64  scopeid 0x20<link>
        inet6 **2630:210:f021:9011::3**  prefixlen 64  scopeid 0x0<global>
        ether 0e:c5:84:6a:54:98  txqueuelen 0  (Ethernet)
        RX packets 796  bytes 56417 (55.0 KiB)
        RX errors 0  dropped 166  overruns 0  frame 0
        TX packets 16  bytes 1356 (1.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Describe the results you expected:**
Only IPv4 address should be assigned.

**Output of `podman version`:**
[root@centos8 bin]# ./podman version
Client:       Podman Engine
Version:      4.0.0-dev
API Version:  4.0.0-dev
Go Version:   go1.17.7
Git Commit:   a88ea2c68b1ef01077a53b1c568b85667dcbc1e2
Built:        Tue Feb 22 04:02:18 2022
OS/Arch:      linux/amd64

**Output of `podman info --debug`:**
[root@centos8 bin]# ./podman info --debug
host:
  arch: amd64
  buildahVersion: 1.24.2
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.module_el8.5.0+890+6b136101.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 84384406047fae626269133e1951c4b92eed7603'
  cpus: 4
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: centos8
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-348.7.1.el8_5.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 5882843136
  memTotal: 8145420288
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.0.2-1.module_el8.5.0+911+f19012f9.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.2
      spec: 1.0.2-dev
      go: go1.16.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module_el8.5.0+890+6b136101.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 8497655808
  swapTotal: 8497655808
  uptime: 863h 42m 13.82s (Approximately 35.96 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.0-dev
  Built: 1645473738
  BuiltTime: Tue Feb 22 04:02:18 2022
  GitCommit: a88ea2c68b1ef01077a53b1c568b85667dcbc1e2
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.0-dev

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

I compiled the podman by myself

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by leolovejj** [comment]
Same issue when only specify IPv6 address when start container
============================================
[root@centos8 bin]# ./podman run -itd --name=master --network=ens192 **--ip6=2630:210:f021:9011::6** 32572d8c0408 /bin/bash
63d4a099245c7f4a5f622a8cdcb5b3ccf39215f75a2707efc74d327a273faabc
[root@centos8 bin]# docker ps -a
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
CONTAINER ID  IMAGE                         COMMAND     CREATED        STATUS            PORTS       NAMES
63d4a099245c  localhost/netbackup/main:9.1  /bin/bash   7 seconds ago  Up 4 seconds ago              master
[root@centos8 bin]# ./podman exec -it 63d4a099245c /bin/bash
bash-4.2# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet **192.168.1.6**  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 2630:210:f021:9011::6  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::a8a1:3dff:fe90:eedb  prefixlen 64  scopeid 0x20<link>
        ether aa:a1:3d:90:ee:db  txqueuelen 0  (Ethernet)
        RX packets 864  bytes 61988 (60.5 KiB)
        RX errors 0  dropped 157  overruns 0  frame 0
        TX packets 21  bytes 1658 (1.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by leolovejj** [comment]
Issue does not occur with pure IPv4 or IPv6 macvlan
==================================
[root@centos8 bin]# ./podman network create -d macvlan -o parent=ens192 --subnet=192.168.1.10/24 --gateway=192.168.1.1 ens192
ens192
[root@centos8 bin]# ./podman run -itd --name=master --network=ens192 --ip=192.168.1.5 32572d8c0408 /bin/bash
0f148ba61fb03fd48666de0feba0bbb2cd11e90ece001b25e2c59e6a38160ef4
[root@centos8 bin]# ./podman inspect ens192
[
     {
          "name": "ens192",
          "id": "22e496b0a5ffb7abbe918389cdbad3e10e9961f562b4c3e59cd8bfb50773d055",
          "driver": "macvlan",
          "network_interface": "ens192",
          "created": "2022-04-02T02:47:57.340811508+08:00",
          "subnets": [
               {
                    "subnet": "192.168.1.0/24",
                    "gateway": "192.168.1.1"
               }
          ],
          "ipv6_enabled": false,
          "internal": false,
          "dns_enabled": false,
          "ipam_options": {
               "driver": "host-local"
          }
     }
]
[root@centos8 bin]# docker ps -a
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
CONTAINER ID  IMAGE                         COMMAND     CREATED         STATUS             PORTS       NAMES
0f148ba61fb0  localhost/netbackup/main:9.1  /bin/bash   17 seconds ago  Up 16 seconds ago              master
[root@centos8 bin]# ./podman exec -it 0f148ba61fb0 /bin/bash
bash-4.2# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.5  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::60a4:2cff:fea0:8833  prefixlen 64  scopeid 0x20<link>
        ether 62:a4:2c:a0:88:33  txqueuelen 0  (Ethernet)
        RX packets 1134  bytes 85834 (83.8 KiB)
        RX errors 0  dropped 214  overruns 0  frame 0
        TX packets 18  bytes 1424 (1.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@centos8 bin]# ./podman network create -d macvlan -o parent=ens192 --subnet=2630:210:f021:9011::/64 --gateway=2630:210:f021:9011::1 ens192
ens192
[root@centos8 bin]# ./podman run -itd --name=master --network=ens192 --ip6=2630:210:f021:9011::7 32572d8c0408 /bin/bash
32953dc89f09c107b44790dbcd2110d599171d501d30937e7fe5f4574333f751
[root@centos8 bin]# ./podman inspect ens192
[
     {
          "name": "ens192",
          "id": "22e496b0a5ffb7abbe918389cdbad3e10e9961f562b4c3e59cd8bfb50773d055",
          "driver": "macvlan",
          "network_interface": "ens192",
          "created": "2022-04-02T02:50:33.112799147+08:00",
          "subnets": [
               {
                    "subnet": "2630:210:f021:9011::/64",
                    "gateway": "2630:210:f021:9011::1"
               }
          ],
          "ipv6_enabled": true,
          "internal": false,
          "dns_enabled": false,
          "ipam_options": {
               "driver": "host-local"
          }
     }
]
[root@centos8 bin]# docker ps -a
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
CONTAINER ID  IMAGE                         COMMAND     CREATED         STATUS             PORTS       NAMES
32953dc89f09  localhost/netbackup/main:9.1  /bin/bash   34 seconds ago  Up 31 seconds ago              master
[root@centos8 bin]# ./podman exec -it 32953dc89f09 /bin/bash
bash-4.2# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 2630:210:f021:9011::7  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::f05b:b3ff:fecc:da45  prefixlen 64  scopeid 0x20<link>
        ether f2:5b:b3:cc:da:45  txqueuelen 0  (Ethernet)
        RX packets 1564  bytes 113425 (110.7 KiB)
        RX errors 0  dropped 290  overruns 0  frame 0
        TX packets 18  bytes 1548 (1.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by Luap99** [comment]
This is the expected behavior. Why do you create a network with a ipv4 and ipv6 subnet but only want one ip assigned.
--ip just set a single static ip, the other subnets will always get the other ips assigned automatically.

Just create a subnet with only ipv4/ipv6 if you want this.

**Comment by leolovejj** [comment]
Thanks for the quick response. I think the macvlan can has the ability to support both ipv4 and ipv6 subnet, but customer should be able to decide use one of them or both. The macvlan setting should be independent with the network setting inside the container. What do you think?

We have the following use case:
Customer created dual stack IPv4/IPv6 macvlan, while creating the instance container, they could specify pure IPv4 or IPv6 address, or dual stack in the beginning. Later they can also add IPv4/IPv6 address based on their needed.

**Comment by leolovejj** [comment]
Any comments?

**Comment by Luap99** [comment]
The network says what subnets will be used.

You need to create/use different networks for the containers if some should only have ipv4/ipv6 addresses, create a ipv4, ipv6 and dual stack networks and then you can specify --network ipv4 or --network ipv6 to choose the correct subnets.

--ip only sets one static ip all others will always be automatically assigned.

**Comment by mheon** [comment]
I can potentially see an argument that we should add a `none` option to `--ip` and `--ip6` (and their counterparts in `--net`) to explicitly specify that a container should not acquire an IPv4 or IPv6 address (not specific to macvlan). This would need support with the network tool, which would make it Netavark-only. I would consider it a feature request and not a bug, though.

**Comment by Luap99** [comment]
Why should we make things more complicated for us? First of this would be netavark only and not cni. Second you can already get the same result by using multiple networks. I don't see why a `podman run --ip none` would be better than a `podman run --network ipv6`

Also note that there is nothing in the backend which can differentiate between --ip and --ip6, they all end up in the static ip slice. If we need such functionality it would require bigger changes.

**Comment by mheon** [comment]
I said that this would make sense as a feature request, not that I had any particular desire to implement it :smile: 

If someone wanted to add support I'd merge it. I don't see the team spending time to add it, though.

**Comment by leolovejj** [comment]
[root@centos8 bin]# ./podman run -itd --name=master --network=ens192 --ipv4=192.168.1.5 32572d8c0408 /bin/bash
Error: unknown flag: --ipv4

Can you tell me the exact commands?

How to specify the container to use specific IPv4 or IPv6 network if use docker compose yaml?

**Comment by mheon** [comment]
It's `--ip` not `--ipv4`.

**Comment by mheon** [comment]
You would have 2 separate networks, one with a v4 subnet and one with a v6 subnet, and connect only to the relevant network. This does present major complications for the macvlan backend as you'll need a separate physical interface for each network, but it resolves the problem for typical networks without issue.

**Comment by Luap99** [comment]
You do not need separate interfaces! You can create different macvlan networks with different subnets but still use the same network interface.

**Comment by rhatdan** [comment]
This would seem to be a good blog or howto...

**Comment by leolovejj** [comment]
So the only solution to use pure IPv4 or IPv6 ip address in container is to create pure IPv4 or IPv6 macvlan, right?
For example, we have a nic1 interface, we can create nic1.1 for pure IPv4 and nic1.2 for pure IPv6, container a can connect nic1.1 for pure IPv4 address and container b can connect to nic1.2 for pure IPv6 address, right?


If we create dual stack macvlan for nic1, the container connected to nic1 will have both IPv4 and IPv6 address, this cannot be fixed with current design?
