### ISSUE TITLE
Unable to create anonymous volumes with --mount

### ISSUE THREAD

**Issue by andrewaylett** [containers/podman#13756]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. When running a tool which is provided as a Docker image (in my case, jetbrains/qodana-gradle-plugin)

2. The tool attempts to start a container with an anonymous volume mount: `--mount type=volume,dst=/data/project/.gradle`
    The full command executed is:

```
docker run --rm --name idea-inspections -p 8080:8080 -v /home/axa/dev/github.com/andrewaylett/asmble:/data/project -v /home/axa/dev/github.com/andrewaylett/asmble/build/results:/data/results --mount type=volume,dst=/data/project/.gradle jetbrains/qodana:latest
```

3. This fails

**Describe the results you received:**

Podman reports:

```
Error: must set source volume
```

**Describe the results you expected:**

The container is created with an anonymous volume

**Additional information you deem important (e.g. issue happens only occasionally):**

This has been reported against Qodana in https://youtrack.jetbrains.com/issue/QD-2325

I have a local fix for this issue and intend to raise a PR for it shortly.

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
I’ll take this one
