### ISSUE TITLE
podman commands don't work - outputting wrong directory

### ISSUE THREAD

**Issue by optimizasean** [containers/podman#13772]
I moved my user files and accounts testing something and now podman doesn't work.

To reproduce on macOS:
1. Create a podman machine and at least one container in it.
2. Move your path i.e. `/Users/<user_name>/.....` like to `/Users/<new_user_name>` or `/Data/PodmanDeveloper/<username>` and relink your accounts.
3. Even if you uninstall and reinstall podman, it will fail on `podman machine ls`, `podman machine init`, and many other commands.

To fix I deleted the podman configurations in local share and in .local/containers.
Possible fix: You should be able to rename the path in all of them from old to new to fix it, however that may not fix it - I didn't test that.

The source of the error is in the configuration files pointing to the old directory which the podman command reads to identify where to find the containers and vms (which are no longer there).  Super edge case I accidentally stumbled onto.

Putting this here in case anyone else accidentally bricks a mac on the upgrades or testing something and can't figure out why podman is busted after they restore it 😁

**Comment by optimizasean** [comment]
Found a new problem - create new VM successfully after deleting files, however: `/path/to/user/.config/containers/podman/machine/qemu/podman-machine-default.ign` cannot be found...how does one regenerate this file?

**Comment by optimizasean** [comment]
Solved - then you must delete through `podman system connection ls` all of the connections with `podman system connection rm <name>` and then `podman machine rm` - and also delete other machines if you have them.  Then, when you create a new machine, it will set it all up and work.

**Comment by Luap99** [comment]
@baude @ashley-cui PTAL
I guess changing you home directory is not supported because podman stores absolute paths in the machine config files.

**Comment by baude** [comment]
correct.

**Comment by rhatdan** [comment]
I don't see us fixing this, so I am going to close.  Bottom line, if you move your homedir after you run containers, you will need to clean everything out and start from scratch.  podman system reset should help here

**Comment by optimizasean** [comment]
Ahhh thats the command I was looking for. Makes it much easier than doing everything by hand.

Probably not a concern for the majority of users...although there are quite a few fringe developers that do weird things (all developers - some weirder than others) but probably not enough that would run into this to do something about it 😆 

Thanks!
