### ISSUE TITLE
size mismatch between 'podman images' and 'docker images'

### ISSUE THREAD

**Issue by benoitf** [containers/podman#13777]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When pulling an image from docker or from podman, the size is not the same

**Steps to reproduce the issue:**

1. `docker pull docker.io/redhat/ubi8-micro:8.5-833`

2. `podman pull docker.io/redhat/ubi8-micro:8.5-833`

3. then check the sizes

```
$ podman images | grep 8.5-833 
docker.io/redhat/ubi8-micro        8.5-833        2d9a3a00bcc6  3 weeks ago   38.7 MB
```

```
$ docker images | grep 8.5-833
redhat/ubi8-micro                     8.5-833                                    2d9a3a00bcc6   3 weeks ago    36.5MB
```

**Describe the results you received:**
Image has not the same size

**Describe the results you expected:**
Image has the same size

**Additional information you deem important (e.g. issue happens only occasionally):**

extracting the image to a tar file is the same size
```
$ podman save docker.io/redhat/ubi8-micro:8.5-833 > /tmp/podman-size.tar
$ docker save docker.io/redhat/ubi8-micro:8.5-833 > /tmp/docker-size.tar

-rw-r--r--  1 benoitf  wheel  38749184 Apr  5 14:50 /tmp/docker-size.tar
-rw-r--r--  1 benoitf  wheel  38749184 Apr  5 14:49 /tmp/podman-size.tar

```

**Output of `podman version`:**

```
4.0.2 / macOS
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
The size of both tarballs is equal to 38.7MB, which is what we report, so an argument could be made that our figures are more accurate here?

@vrothberg PTAL

**Comment by vrothberg** [comment]
I have no explanation at the time of writing; needs further investigation what Docker does.

@mtrmac @nalind do you know?

**Comment by benoitf** [comment]
Also I tried
```
 DOCKER_HOST="unix://$HOME/.local/share/containers/podman/machine/podman-machine-default/podman.sock" docker images
REPOSITORY          TAG       IMAGE ID       CREATED       SIZE
redhat/ubi8-micro   8.5-833   2d9a3a00bcc6   4 weeks ago   38.7MB
```

and I have the same result with podman cli (so issue is coming from the server side, not CLI part)

**Comment by giuseppe** [comment]
what do you use the size for?

I've pulled the image into an empty storage, and I can replicate the docker result with:

```
$ podman system reset -f
$ podman pull docker.io/redhat/ubi8-micro:8.5-833
$ du --count-links --apparent --summarize ~/.local/share/containers/storage/overlay
36867	~/.local/share/containers/storage/overlay
```

I am not sure this size is helpful, it doesn't reflect the disk usage and it doesn't account for hard links.

IMO, the Podman way of reporting the size is more correct.   From what I can see above, it uses the tarball size which is replicable and it doesn't have to worry about file system details.
