### ISSUE TITLE
Docker APIv2 `/commit` ignores uploaded config

### ISSUE THREAD

**Issue by matejvasek** [containers/podman#13770]
As consequence the `s2i` utility is not working with `podman` when used as a `docker` daemon,
because resulting image has incorrect `Cmd`.

Related to https://github.com/openshift/source-to-image/issues/1082

**Comment by matejvasek** [comment]
The endpoint loads container state including config from DB. The config from request body is ignored.

**Comment by vrothberg** [comment]
Thanks for reaching out, @matejvasek.  Do you have cycles to open a PR?

**Comment by matejvasek** [comment]
@vrothberg I don't know how to fix this from top of my head.
I can think of hack solution: write `ENTRYPOINT/CMD/ENV` to the `Changes` option as `Dockerfile` commands, but I don't think that's good idea. Any hint how to approach this?

**Comment by matejvasek** [comment]
The container structure is pretty much immutable so I cannot easily overwrite fields in the ctr config.

**Comment by vrothberg** [comment]
Apologies, I do not have time to look into the issue at the moment.

**Comment by rhatdan** [comment]
@matejvasek is this still an issue.  It got lost because the stale-issue flag was set and no one noticed, so it was lost in the flood of issues.

**Comment by matejvasek** [comment]
@rhatdan I don't know. I just decided not to use this this endpoint.

**Comment by vrothberg** [comment]
I'll take a look now.

**Comment by vrothberg** [comment]
Works with changes on my end:
```
podman (fix-13770) $ DOCKER_HOST=unix:///run/user/1000/podman/podman.sock docker commit --change CMD=xxx af
9f6254c2e22e02deaf5ca275c12598174972218b6abe2a6f006f0f92c5092061
podman (fix-13770) $ podman image inspect 9f|less
podman (fix-13770) $ podman image inspect 9f --format "{{.Config.Cmd}}"
[/bin/sh -c xxx]
```

What does not work though - as implied above - is that the compat endpoint entirely ignores the upload container config, see https://docs.docker.com/engine/api/v1.43/#tag/Image/operation/ImageCommit.

**Comment by vrothberg** [comment]
OK, I do not have enough time to tackle it but I can propose a solution.  We can extend libpod's `Commit()` API to account for the config of the compat endpoint and use the imported builder (see https://github.com/containers/podman/blob/main/libpod/container_commit.go#L70-L80) to set the specific fields of the docker config.
