### ISSUE TITLE
There is no `get` command on podman machine

### ISSUE THREAD

**Issue by benoitf** [containers/podman#13782]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I can set the rootless/rootful mode on a podman machine with `podman machine set --rootful`
But I am unable to get that parameter

podman machine list --format json is also not showing these parameters. 

**Steps to reproduce the issue:**

1.`podman machine set --rootful`

then try to know in which mode the machine is with a command.

**Describe the results you received:**
N/A

**Describe the results you expected:**
Able to see in which mode a podman machine is

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.3
API Version:  4.0.3
Go Version:   go1.18
Built:        Fri Apr  1 17:28:59 2022
OS/Arch:      darwin/amd64
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
Thanks for reaching out, @benoitf.  The request makes total sense to me.

@ashley-cui, can you take a look?

**Comment by ashley-cui** [comment]
I think @baude is working on a `podman machine inspect` that should include this info, I'll like that PR when he opens it.

**Comment by baude** [comment]
@benoitf does podman machine inspect satisfy your requirements?

**Comment by benoitf** [comment]
@baude so yes and no.

yes because I'm able to get the value of `Rootful` so this is great.

And no because it seems configuration and state are merged. So for example I don't know the list of properties that I can apply on a machine.

but the goal of this issue was to have the ability to query the 'rootful' and now there is way so we can close the issue.

Missing stuff is to know the list of properties that can be configured on a machine but I would say it's somehow also tracked by https://github.com/containers/podman/issues/13633
