### ISSUE TITLE
e2e tests create files in tree

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#13789]
I just noticed that the e2e tests create files in the tree:
```
test/e2e/default.yaml
test/e2e/hello.tar
test/e2e/relative/
```

I did not examine it any further but want to leave the breadcrumbs here.  Tests should only create temporary files/directories and not alter the local tree.

**Comment by cdoern** [comment]
`/test/e2e/relative` is from me in #12853 and #13531. For that PR putting the relative dir in the tmpdir failed because for some reason `build -f`... could not find the directory if it was in there.  Not sure if I was just doing it wrong, if so I can make a quick patch resolving it.

**Comment by rhatdan** [comment]
@cdoern @vrothberg were these cleared up?
