### ISSUE TITLE
podman-remote doesn't support newest ssh key exchange algorthims

### ISSUE THREAD

**Issue by sanyer** [containers/podman#13780]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

According to `journalctl -u sshd` on a host machine, `podman system connection add` offers only these key exchange algorithms:

```txt
diffie-hellman-group14-sha1
diffie-hellman-group-exchange-sha1
diffie-hellman-group1-sha1
```

And according to Fedora, SHA1 is considered LEGACY since FF33: <https://fedoraproject.org/wiki/Changes/StrongCryptoSettings2>

There two work arounds for this situation:

1. [NOT GOOD BUT FAST]: Make Fedora use LEGACY KexAlgorithms: `ln -svf /usr/share/crypto-policies/LEGACY/opensshserver.txt /etc/crypto-policies/back-ends/opensshserver.config`
2. [NOT FAST BUT GOOD]: Generate ssh key (make sure key type is either `ecdsa` or `ed25519`) locally first and then upload it to AWS and use it for a new Fedora VM.

**Steps to reproduce the issue:**

1. Create a Fedora CoreOS instance on AWS.

2. Let AWS generate a SSH key for it.

3. Try to add this VM using the SSH key to Podman machine list.

**Describe the results you received:**

`podman system connection add ssh://...` without socket path it failed with:

```txt
...
Error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
failed to connect
github.com/containers/podman/v4/cmd/podman/system/connection.getUDS
 /private/tmp/podman-20220402-80792-14flg0w/podman-4.0.3/cmd/podman/system/connection/add.go:214
github.com/containers/podman/v4/cmd/podman/system/connection.add
 /private/tmp/podman-20220402-80792-14flg0w/podman-4.0.3/cmd/podman/system/connection/add.go:115
...
```

`podman --connection=<CONNECTION> info` on previously added connection with socket path it failed with:

```txt
...
Error: unable to connect to Podman. failed to create sshClient: Connection to bastion host (ssh://<USER>@<HOST>:22/run/user/1000/podman/podman.sock) failed.: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
github.com/containers/podman/v4/pkg/bindings.sshClient
 /private/tmp/podman-20220402-80792-14flg0w/podman-4.0.3/pkg/bindings/connection.go:292
github.com/containers/podman/v4/pkg/bindings.NewConnectionWithIdentity
 /private/tmp/podman-20220402-80792-14flg0w/podman-4.0.3/pkg/bindings/connection.go:106
github.com/containers/podman/v4/pkg/domain/infra.newConnection
 /private/tmp/podman-20220402-80792-14flg0w/podman-4.0.3/pkg/domain/infra/runtime_tunnel.go:25
github.com/containers/podman/v4/pkg/domain/infra.NewImageEngine
 /private/tmp/podman-20220402-80792-14flg0w/podman-4.0.3/pkg/domain/infra/runtime_tunnel.go:51
github.com/containers/podman/v4/cmd/podman/registry.NewImageEngine
 /private/tmp/podman-20220402-80792-14flg0w/podman-4.0.3/cmd/podman/registry/registry.go:53
...
```

**Describe the results you expected:**

Destination for the Podman service is successfully added.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS
MacOS 12.3.1
podman version 4.0.3

**Comment by vrothberg** [comment]
@baude FYI

**Comment by rhatdan** [comment]
@jwhonce This is again caused by using builtin ssh in golang versus execing ssh.  Is there any change of improving the ssh bindings?

**Comment by jwhonce** [comment]
@rhatdan We could enhance the current ssh code to either exec ssh or use the golang library. Exec'ing would be slower, but would allow the developer to decide how to use ssh.

**Comment by rhatdan** [comment]
Would it be possible to do both?  Would it be make sense or be too much work?

**Comment by rhatdan** [comment]
@sanyer did you ever get a chance to work on this?

**Comment by sanyer** [comment]
@sanyer no, not yet really :-(

**Comment by cdoern** [comment]
@rhatdan @jwhonce looking at this, I think it would make sense to first `exec.LookPath(ssh)` and if that fails, default to golang's package? basically everywhere we use ssh. we should also try to exec.

**Comment by rhatdan** [comment]
I am fine with that.  But I do worry about how well the ssh on MAC and Windows work versus Linux.

**Comment by cdoern** [comment]
@rhatdan that is true. I guess if ssh fails as well we can default to the go libraries?

**Comment by sanyer** [comment]
@cdoern I'll try again too then.

**Comment by sanyer** [comment]
Yes, I still remember about it, will check it again this week.

**Comment by cdoern** [comment]
@sanyer I am working on a fix for this

**Comment by cdoern** [comment]
This should be solved by using the `--ssh=native` flag closing as completed
