### ISSUE TITLE
`podman port` and `podman container ls` port mapping direction is not clear

### ISSUE THREAD

**Issue by markstos** [containers/podman#13802]
/kind feature

**Description**

To be bug-for-bug compatible with Docker `podman` shows port mappings happening in opposite directions in `podman container ls` and `podman ps`:

From `podman container ls`:

     0.0.0.0:8080->8080/tcp 

From `podman ps`:

     `8080/tcp -> 0.0.0.0:8080`

It's not obvious which direction the port mapping notation works in the output of `podman port -a` and `podman container ls`. Does the the arrow point from host to container, or container to host? Neither the man pages for `podman-ps` or `podman-port` clarify this point. It seems especially worth a mention since the two formats are reversed!  (This is a not a support request-- I figured it out).

This detail matters for security as running a service on `0.0.0.0` on the host may be a security problem, while it's not a problem in a container that doesn't have networking to the outside world beyond port mappings. 

Perhaps the output format of either command can't be changed for compatibility with tools that might be parsing the output. 

The UX would be improved considerably if a clear headings saved a trip to the main pages to confirm:

## Proposal for `podman ps` header

     HOST->CONTAINER PORTS
     0.0.0.0:8080->8080/tcp 

**Describe the results you expected:**

I expected consistent port mapping formatting and clear docs about which direction the mappings are going. 

**Output of `podman version`:**

```
podman 4.0.3
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Comment by Luap99** [comment]
I don't understand what you are asking for?
`podman ps` and `podman container ls` display the port exactly the same. Are you saying docker displays this different so we should too? If so I cannot reproduce this on my docker install. They also show `0.0.0.0:8080->8080/tcp`

Also note that always the part with the host ip (.e.g 0.0.0.0) is always the host port. We cannot show the container ip because that depends where you application would actually bind to.

**Comment by rhatdan** [comment]
I am going to close this as it seems to work correctly.  Continue conversation here, and reopen if I am mistaken.
