### ISSUE TITLE
Need deveoper verification for macos

### ISSUE THREAD

**Issue by psadi** [containers/podman#13815]
<img width="262" alt="Screenshot 2022-04-08 at 11 53 37 PM" src="https://user-images.githubusercontent.com/22428691/162503779-67ac26cf-c369-43bc-bde6-d2ac6492f3d7.png">

Im unable to use podman executable in company provided macbook, and i coudnt allow it under System Preferences > Security & Privacy > Allow apps from etc.

Please let me know if this can be sorted in upcoming releases

**Comment by robbiemu** [comment]
if you cannot trust the application this is a problem your it department needs to address. it does run just fine on a personal mac.

how did you get it, homebrew?

**Comment by psadi** [comment]
Hi @robbiemu 

I directly downloaded from releases and tried to execute them, Brew do-sent play with with our internet.
Its works fine on my personal mac as well (I granted access from system preferences), Just facing this weird issue in my office mac.

**Comment by Luap99** [comment]
@baude @ashley-cui PTAL I tought the mac release was signed by us?

**Comment by ashley-cui** [comment]
I think we signed a few of the previous releases manually but haven't done signing in CI yet.

**Comment by baude** [comment]
What version of Podman is this please?

**Comment by psadi** [comment]
can this be sorted next release ?

**Comment by rhatdan** [comment]
We are just releaseing podman 4.1 @baude @mheon @ashley-cui Can we sign it?

**Comment by ashley-cui** [comment]
Signed the .dmg!

**Comment by psadi** [comment]
Thank you all 😀

**Comment by psadi** [comment]
Hello All,

Just downloaded from the latest release and the issue still remains, Am i missing anything here ?

<img width="886" alt="Screenshot 2022-06-21 at 12 19 00 AM" src="https://user-images.githubusercontent.com/22428691/174662606-b5e7759f-6889-4902-8284-6ead72022f18.png">

**Comment by ashley-cui** [comment]
@psadi Every release needs to be signed manually, let me sign 4.1.1 today

**Comment by psadi** [comment]
@ashley-cui  - Thanks !!
