### ISSUE TITLE
configure timeout for ssh connection for podman remote

### ISSUE THREAD

**Issue by alicefr** [containers/podman#13812]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
The ssh connection to my VM where podman is running is relatively slow and podman-remote times out from times to time. I'd like to be able to increase the timeout.

**Describe the results you expected:**
I'd like to be able to configure the timeout for podman-remote

**Comment by mheon** [comment]
@jwhonce PTAL

**Comment by alicefr** [comment]
This is still a valid option. Anyone interested in adding it or should I closed this?

**Comment by jwhonce** [comment]
This should be put on the roadmap with the podman context implementation. Items required:

- Add flag to CLI
- Add flag to `podman context add` and `podman connection add` for timeout
- Store timeout value with context/connection other values

**Comment by liuxuc63** [comment]
I have had the same issue. In my case, the client will disconnect when run container more than about 4mins. The comman `podman run --name task image:tag my-cmd.
I run the tcp protocol on podman server....

**Comment by liuxuc63** [comment]
> man run --name task image:tag my-cmd.
> I run the tcp protocol on podman server....

Sorry, it is my mistake. I put a proxy between podman-server and podman-client for security (ip white list), and the proxy has timeout settings. I increase the timeout value, it works good now.

Thanks all of the podman contributors and podman org.
