### ISSUE TITLE
Launching GUI apps from a container

### ISSUE THREAD

**Issue by kisccz** [containers/podman#13830]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature
launch GUI apps from inside a container

**Description**
I can't launch GUI apps from inside containers. Is it possible to add this feature?

**Comment by debarshiray** [comment]
If you are trying to run graphical desktop applications interactively, then you should definitely try [Toolbx](https://containertoolbx.org/).

The [above](https://major.io/2021/10/17/run-xorg-applications-with-podman/) blog post only shows how to get access to the X11 server by sharing the socket and the `DISPLAY` environment variable from the host, and in a post-pandemic world, where even RHEL 8 tries to default to Wayland, I'd hope that X11 will no longer be synonymous with *GUI apps on Linux*.  :)

Getting Wayland access will require more knobs, then D-Bus access, audio access, icons, themes, fonts, so and so forth.  Toolbx wraps Podman to take care of those details.

If you really want to ship graphical desktop applications in containers, then I'd suggest [Flatpak](https://flatpak.org/).

**Comment by rhatdan** [comment]
I agree for this use case Toolbx has done all of the heavy lifting.
