### ISSUE TITLE
No linux binary in the asset list

### ISSUE THREAD

**Issue by BlauerPulli** [containers/podman#13833]
/kind bug

Hey, i'm just wondering why there is no more linux built published? Since v4 release the [podman-remote-static.tar.gz](https://github.com/containers/podman/releases/download/v4.0.3/podman-remote-static.tar.gz) asset contains a windows executable:

abc@def:~/Downloads$ file podman-remote-static
podman-remote-static: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows

I assume this is a bug because this was fine in v3 releases.

**Comment by vrothberg** [comment]
@mheon PTAL

**Comment by wfchair** [comment]
I hope podman itself released in static binary for linux, as the way that consul, traefik etc. other go apps did.

**Comment by vrothberg** [comment]
> I hope podman itself released in static binary for linux, as the way that consul, traefik etc. other go apps did.

Only the remote client. The native `podman` binary would be much too restricted to reasonably support it.

**Comment by rhatdan** [comment]
How does that binary get there?  Is this done by computer script or human?

**Comment by mheon** [comment]
Human, I build it via the ‘make podman-remote-static’ target

**Comment by rhatdan** [comment]
When I build with that command in makefile, it works for me and the executable is correct.

**Comment by mheon** [comment]
I'm going to close this. We've fixed the release scripts and makefile to generate correct binaries, so new releases are fixed.
