### ISSUE TITLE
Doc Issue:  Missing the "missing" option in pull

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman#13864]
The value "missing" is not documented for the `--pull` option in the man pages.  The functionality should be equivalent to `--pull=false`.  That is if used, the image is not pulled if it is already present in local storage.  There is some question as to whether or not the registry should ever be checked if the image is present locally.  I don't know the definitive behavior, but I don't think the registry should be pinged at all if `--pulled=missing` is invoked unless the local storage does not contain the image.

**Comment by rhatdan** [comment]
I agree --pull=false should not hit the regestry
            --pull=missing should not hit the registry, if image is local
