### ISSUE TITLE
running foreign architecture containers hits the network every time and confuses future `podman run` invocations

### ISSUE THREAD

**Issue by terceiro** [containers/podman#13897]
/kind bug

**Description**

When running containers for a foreign architecture, podman run will hit the network looking for images on every invocation:

```
terceiro@host:~$ podman run --arch=arm64 debian arch
Resolved "debian" as an alias (/etc/containers/registries.conf.d/shortnames.conf)
Trying to pull docker.io/library/debian:latest...
Getting image source signatures
Copying blob fa223d8c149d done
Copying config 05e8051d05 done
Writing manifest to image destination
Storing signatures
aarch64
terceiro@host:~$ podman run --arch=arm64 debian arch
Resolved "debian" as an alias (/etc/containers/registries.conf.d/shortnames.conf)
Trying to pull docker.io/library/debian:latest...
Getting image source signatures
Copying blob fa223d8c149d [-----------------] 0.0b / 0.0b
Copying config 05e8051d05 done
Writing manifest to image destination
Storing signatures
aarch64
```
This means that if I try run a foreign container while I'm offline, I can't (even if I have pulled it before):

```
terceiro@host:~$ podman run --arch=arm64 debian arch
Resolved "debian" as an alias (/etc/containers/registries.conf.d/shortnames.conf)
Trying to pull docker.io/library/debian:latest...
Error: initializing source docker://debian:latest: pinging container registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 10.0.2.3:53: dial udp 10.0.2.3:53: connect: network is unreachable
```

Weirder than that, is that from this point on, a plain `podman run` will run the foreign container, instead of a native one (but will not hit the network, as I'm able to do that while still offline):

```
terceiro@host:~$ podman run debian arch
aarch64
```

To "fix" this, I have to explicitly pull the same image without any architecture request after coming online again:

```
terceiro@host:~$ podman pull debian
Trying to pull docker.io/library/debian:latest...
Getting image source signatures
Copying blob dbba69284b27 done
Copying config d69c6cd3a2 done
Writing manifest to image destination
Storing signatures
d69c6cd3a20d21ec91b677c3bcd10d9975f4fe67eff81afb5a09bdef5134afeb
terceiro@host:~$ podman run debian arch
x86_64
```

I can reproduce this on Debian, with both podman 3.4.4 (currently in testing) and podman 4.0.1 (currently in experimental)

**Comment by terceiro** [comment]
FWIW, I just tested 4.0.3 on a fedora rawhide VM.

Using foreign architecture container while offline works:

```
[terceiro@fedora ~]$ podman run --arch=arm64 debian arch
aarch64
```

However, the foreign architecture container still shadows the "expected" native container, and I have to do a podman pull to fix it:

```
[terceiro@fedora ~]$ podman run debian arch
aarch64
[terceiro@fedora ~]$ podman pull debian 
Trying to pull docker.io/library/debian:latest...
Getting image source signatures
Copying blob dbba69284b27 done  
Copying config d69c6cd3a2 done  
Writing manifest to image destination
Storing signatures
d69c6cd3a20d21ec91b677c3bcd10d9975f4fe67eff81afb5a09bdef5134afeb
[terceiro@fedora ~]$ podman run debian arch
x86_64
```

**Comment by Luap99** [comment]
> However, the foreign architecture container still shadows the "expected" native container, and I have to do a podman pull to fix it

I think this is the expected behavior unfortunately, see https://github.com/containers/podman/issues/12682

I am not sure about the network access? Does it work with `--pull=never`?

@vrothberg PTAL

**Comment by vrothberg** [comment]
Thanks for reaching out, @terceiro!

Let's continue over in https://github.com/containers/podman/issues/12682 to have one issue to track multi-arch handling. In short: a number of images of arch A claim to be of arch B which completely breaks/broke multi-arch use cases.  We decided to pessimistically never trust any image, so we're pulling them down. But, Podman can be made smarter than it is today.
