### ISSUE TITLE
High frequency of SELinux faults after restoring a checkpointed container

### ISSUE THREAD

**Issue by berndbausch** [containers/podman#13907]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

After restoring a container, it generates SElinux violations that lead to up to 100% CPU utilization by processes running on the container host, such as setroubleshootd or logging processes. The audit log file is swamped with identical AVC messages. I suspect that the high CPU utilization has the side effect that the container can't be checkpointed anymore.

**Steps to reproduce the issue:**

1. Start with the httpd container used in the [podman intro tutorial](https://github.com/containers/podman/blob/main/docs/tutorials/podman_tutorial.md)
`$ sudo podman run -dt -p 8001:8080/tcp -e HTTPD_VAR_RUN=/run/httpd -e HTTPD_MAIN_CONF_D_PATH=/etc/httpd/conf.d -e HTTPD_MAIN_CONF_PATH=/etc/httpd/conf -e HTTPD_CONTAINER_SCRIPTS_PATH=/usr/share/container-scripts/httpd/ registry.fedoraproject.org/f29/httpd /usr/bin/run-httpd`

2. Create a checkpoint 
```
$ sudo podman container checkpoint --latest -e httpd-checkpoint.tgz
WARN[0001] archive: skipping "/var/lib/containers/storage/overlay/c89ccbefbc2264eca9f29adff9e890abb11252e5ab2f0675598b9af09a5339db/merged//run/httpd/cgisock.1" since it is a socket
c9941e7c4070f8a0aaaf1a8157066e9121ddd2cb67345f5251252e2dc7c28d2e
```

3. Restore the container `$ sudo podman container restore --latest`

4. On the container host, check CPU usage and list SELinux audit records
```
$ sudo tail -f /var/log/audit/audit.log
...
type=AVC msg=audit(1650172117.705:44716): avc:  denied  { accept } for  pid=31735 comm="httpd" path="/run/httpd/cgisock.1" scontext=system_u:system_r:container_t:s0:c170,c1013 tcontext=unconfined_u:system_r:container_runtime_t:s0 tclass=unix_stream_socket permissive=0
```

**Describe the results you received:**

Plenty of identical AVC messages like the one above, and high CPU usage such as 100% on small hosts, caused by a container process.

**Describe the results you expected:**

No SELinux violations after restoring the checkpoint

**Additional information you deem important (e.g. issue happens only occasionally):**

The problem occurs consistently.

SELinux labels of process and socket mentioned in the AVC messages:
```
$ sudo podman exec --latest ps -efZ | grep httpd
system_u:system_r:container_t:s0:c170,c1013 default 1  0  0 04:58 pts/0    00:00:00 httpd -D FOREGROUND
system_u:system_r:container_t:s0:c170,c1013 default 22 1  0 04:58 pts/0    00:00:00 httpd -D FOREGROUND
...
$ sudo podman exec --latest ls -lZ /run/httpd/cgisock.1
srwx------. 1 default root system_u:object_r:container_file_t:s0:c170,c1013 0 Apr 17 05:07 /run/httpd/cgisock.1
```
Strangely, the socket's label is different from the tcontext in the AVC messages.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.3
API Version:  4.0.3
Go Version:   go1.16.15
Built:        Sat Apr  2 03:21:14 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.3
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpus: 2
  distribution:
    distribution: fedora
    variant: server
    version: "35"
  eventLogger: journald
  hostname: fed-podman
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.10-300.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 4777578496
  memTotal: 8325742592
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.4-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.4
      commit: 6521fcc5806f20f6187eb933f9f45130c86da230
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 8325689344
  swapTotal: 8325689344
  uptime: 2h 59m 28.24s (Approximately 0.08 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.3
  Built: 1648837274
  BuiltTime: Sat Apr  2 03:21:14 2022
  GitCommit: ""
  GoVersion: go1.16.15
  OsArch: linux/amd64
  Version: 4.0.3
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.0.3-1.fc35.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes to both questions. 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The container host is a KVM VM running Fedora 35. It has 2 vCPUs and 8GB of RAM. The problem doesn't prevent the httpd to serve static web pages (I have not tested CGI).

**Comment by rhatdan** [comment]
Fixed in container-selinux v2.183.0
