### ISSUE TITLE
Podman doesn’t support CSV escaping in `--mount` arguments

### ISSUE THREAD

**Issue by DemiMarie** [containers/podman#13922]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. See that Docker documents that arguments to `--mount` use CSV syntax.

2. Try to CSV-escape an argument to `--mount` that contains commas

**Describe the results you received:**
Does not work

**Describe the results you expected:**
Works

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.16.8
Built:        Wed Dec  8 16:45:07 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

Not applicable as this is a command line parsing problem.

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.4-1.fc35.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 35 Qubes OS VM

**Comment by DemiMarie** [comment]
```sh
podman run '--mount=type=tmpfs,tmpfs-size=512M,"destination=/run,"' --interactive --rm -- registry.access.redhat.com/ubi8/ubi:latest sh
```

Podman complains that `"destination` is an invalid mount option.  Since such commands currently do not work at all in Podman, fixing them should not cause backwards compatibility problems.

**Comment by rhatdan** [comment]
encoding/csv should be used to look at the mount type.
@flouthoc PTAL

**Comment by flouthoc** [comment]
Thanks above PR should close this.
