### ISSUE TITLE
Unexpected behavior when setting mount propagations for named volumes

### ISSUE THREAD

**Issue by Project0** [containers/podman#13939]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I am very confused when following the documentation for creating a pod/container and volumes/mounts.

The documentation clearly tells me i cannot set the propagation when using named volumes and it is only supported on binds. 

> Propagation property can be specified **only for bind mounted volumes** and not for internal volumes or named volumes.

However, podman does not really care and accepts a custom propagation for named volumes without any issue.
Either the documentation is outdated, the behavior is different as the "named" volume is technically a mounted bind directory or it is a  unexpected behavior and the request should actually be rejected with a error. 

**Steps to reproduce the issue:**

```
podman volume create bug
podman container create -v bug:/path:slave --name bug docker.io/nginx
```

**Describe the results you received:**
```json
          "Mounts": [
               {
                    "Type": "volume",
                    "Name": "bug",
                    "Source": "/home/rhillmann/.local/share/containers/storage/volumes/bug/_data",
                    "Destination": "/path",
                    "Driver": "local",
                    "Mode": "",
                    "Options": [
                         "nosuid",
                         "nodev",
                         "rbind"
                    ],
                    "RW": true,
                    "Propagation": "slave"
               }
          ],


```

**Describe the results you expected:**

A error message or reflected documentation

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.3
API Version:  4.0.3
Go Version:   go1.18
Git Commit:   62534053086fdeba7b93117e7c4dc6e797835a3e
Built:        Mon Apr  4 14:54:02 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.3
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.0-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: bdb4f6e56cd193d40b75ffc9725d4b74a18cb33c'
  cpus: 8
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: mucn1122
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 100000
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 100000
  kernel: 5.17.3-arch1-1
  linkmode: dynamic
  logDriver: journald
  memFree: 14479036416
  memTotal: 33375592448
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.4.4-1
    path: /usr/bin/crun
    version: |-
      crun version 1.4.4
      commit: 6521fcc5806f20f6187eb933f9f45130c86da230
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.1.12-1
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 15h 40m 42.14s (Approximately 0.62 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/rhillmann/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/rhillmann/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  volumePath: /home/rhillmann/.local/share/containers/storage/volumes
version:
  APIVersion: 4.0.3
  Built: 1649076842
  BuiltTime: Mon Apr  4 14:54:02 2022
  GitCommit: 62534053086fdeba7b93117e7c4dc6e797835a3e
  GoVersion: go1.18
  OsArch: linux/amd64
  Version: 4.0.3
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Same result in rootfull and rootless mode

**Comment by mheon** [comment]
I'd consider it a bug that we accept these flags on named volumes. Under the hood, they are technically bind mounts, but they should not be used in a way such that mount propagation would be required.

**Comment by rhatdan** [comment]
Yes for named volumes we should throw an error on propagation options.  They probably work, but there really is limited ability to access them.

**Comment by nivekuil** [comment]
> they should not be used in a way such that mount propagation would be required.

Why not? I use rshared on volumes to share a FUSE mount deployed as a sidecar between containers in a pod.

**Comment by rhatdan** [comment]
Are you using a named volume for sharing between the containers, with on as --privileged?

**Comment by nivekuil** [comment]
yep, ---privileged for the fuse mount, which mounts to somewhere under the volume, then the other containers mount that same volume. Open to a better way to do it but this change would break my workflow today

**Comment by rhatdan** [comment]
No I think that is reasonable.  And makes sense in kubernetes world,  I guess.  @nivekuil Have you tried your method with Podman?  If it works, then we just need to fix the documentation.

**Comment by nivekuil** [comment]
Yes, I'm doing this on podman. Actually trying to build a kubernetes replacement on top of it, so it makes sense in my world too :)

**Comment by rhatdan** [comment]
So could you open a PR to fix the documentation?

**Comment by Project0** [comment]
Interesting how quickly this discussion went into :grinning: 

:thinking: Do i assume correct that setting this for named volumes may depend on the underlying storage/volume driver? I can imagine this would fail for some drivers or filesystems.

**Comment by rhatdan** [comment]
Perhaps, but I think the propagations should work on all arches.  :Z and :z would fail on systems that do not support XAttrs.
