### ISSUE TITLE
running podman system reset breaks podman machine

### ISSUE THREAD

**Issue by Luap99** [containers/podman#13946]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

If you have podman machines and run `podman system reset` it will only remove one part of the machine files.

The problem is that system reset will delete `~/.local/share/containers/` and some machine files are also stored there. I have no problem with removing them however since the machine config files are stored under `~/.config/containers/podman/machine` all machine commands now fail.

So either podman system reset should not delete machine files or it should delete all of them (must make sure to stop the vms before)

**Steps to reproduce the issue:**

1. `podman machine init`

2. `podman system reset -f`

3. `podman machine ls`

**Describe the results you received:**
```
Error: error listing vms: stat /home/pholzing/.local/share/containers/podman/machine/qemu/podman-machine-default_fedora-coreos-35.20220305.dev.0-qemu.x86_64.qcow2: no such file or directory
```

**Describe the results you expected:**
It should work.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
latest main

**Comment by Luap99** [comment]
@baude @ashley-cui PTAL

**Comment by rhatdan** [comment]
It should remove all of them and stop the machines.

**Comment by sanyer** [comment]
I wanted to check this bug on my mac, but apparently `podman system reset` is not available on my installation of podman:

```sh
podman system --help
Manage podman

Description:
  Manage podman

Usage:
  podman system [command]

Available Commands:
  connection  Manage remote ssh destinations
  df          Show podman disk usage
  info        Display podman system information
  prune       Remove unused data
```

Am I missing something?

**Comment by Luap99** [comment]
podman system reset is a local podman command only. It is not supported with the remote client.

**Comment by Luap99** [comment]
Fixed in https://github.com/containers/podman/pull/14066, the PR did not link this issue.
