### ISSUE TITLE
Mounted USB directory passed into container, is there support for unplugging and plugging back in the USB drive to a running container? 

### ISSUE THREAD

**Issue by KCSesh** [containers/podman#13940]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I have a USB drive with an `ext4` file system mounted at: `/mnt/usbstick` on my host machine. 
When I run my container, I bind mount that location into the container: 
`-v /mnt/usbstick:/mnt/usbstick`

This works when the container launches, the mounted location is correctly setup and I have USB read/write access. 
However, when the USB drive is unplugged, I no longer can read from that directory,I recieve the error: 

```
root@90f695e33f7b:/mnt/usbstick# ls
ls: reading directory '.': Input/output error
```
This error persists if I plug the USB drive back in and mount it at: `/mnt/usbstick`

I am trying to give read/write access to a USB without exposing the device management to a container. 
Do I have any options?
For my particular use case, I am looking for a directory that is readable/writeable so long as the USB is connected, and supports unplug/replug.
Ideally, I want a mount point in a container that gets "updated" during the lifetime of a running container.

Or is the only way to achieve this, to expose the actual devices to the containers and let the containers properly mount/unmount the locations?

**Steps to reproduce the issue:**

1. Mount a USB drive to: `/mnt/usbstick`

2. Start a container with: `-v /mnt/usbstick:/mnt/usbstick`

3. Unplug usb drive

4.  `/mnt/usbstick` is no longer readable or writeable from the container, even if device is plugged back in. 

**Describe the results you received:**
Unplugging the device seems to disconnect the mount entirely, and can not be brought back. 

I notice opposite behavior if I start the container with the USB unplugged, the container just mounts the host directory.
When a USB is plugged in and mounted at `/mnt/usbstick`, the host is updated with the USB contents, but the container still has the contents of the host, and not the usb. 

**Describe the results you expected:**
Ideally, I want a mount point in a container that gets "updated" during the lifetime of a running container. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.3.0-dev
API Version:  3.3.0-dev
Go Version:   go1.16
Git Commit:   dffbf16b24ba971a96db753100b7f43f5d6df3f8
Built:        Thu Jun 10 16:39:20 2021
OS/Arch:      linux/arm64

```

**Output of `podman info --debug`:**

```
host:
  arch: arm64
  buildahVersion: 1.21.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - debug
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/local/bin/conmon'
    path: /usr/local/bin/conmon
    version: 'conmon version 2.0.29-dev, commit: '
  cpus: 4
  distribution:
    distribution: ubuntu
    version: "18.04"
  eventLogger: file
  hostname: pan-appliance
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.9.140
  linkmode: dynamic
  memFree: 31615795200
  memTotal: 33424560128
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 16712269824
  swapTotal: 16712269824
  uptime: 22h 9m 45.72s (Approximately 0.92 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /data/podman/test/root
  graphStatus: {}
  imageStore:
    number: 0
  runRoot: /data/podman/test/run
  volumePath: /data/podman/test/root/volumes
version:
  APIVersion: 3.3.0-dev
  Built: 1623343160
  BuiltTime: Thu Jun 10 16:39:20 2021
  GitCommit: dffbf16b24ba971a96db753100b7f43f5d6df3f8
  GoVersion: go1.16
  OsArch: linux/arm64
  Version: 3.3.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Manual build of podman for Ubuntu 18.04 ARM.
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes I have looked troubleshooting. 
No I haven't tried the latest podman. 

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by KCSesh** [comment]
Essentially I am trying to have the host handle the lifecycle of USB events, and then have my containers just know if they are writing to a specific area it is to a USB. I am wondering if this is possible. 

OR do I need to have each container handle that logic, which my understanding of it would be to pass in the specific `--device` and then let the container mount and umount it as necessary.

**Comment by rhatdan** [comment]
Can you attempt to mount /mnt instead of /mnt/usbstick with the slave option.


`-v /mnt:/mnt:slave`

And see if this works.

**Comment by rhatdan** [comment]
The issue in the second case is the mount namespace is different and does not leak into the container.

The first one says to mount /mnt into the container, if any mounts happen to directories in /mnt, then they will show up in the container.  I guess the kernel does not handle the case where the mount point gets overmounted.
