### ISSUE TITLE
Using podman unshare with root? 

### ISSUE THREAD

**Issue by KCSesh** [containers/podman#13941]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

If I am creating a container with root, but using the commands to create a new user namespace: 
`sudo podman create -it -rm --uidmap=0:1001:1 --uidmap=1:100000:65536 --gidmap=0:1001:1 --gidmap=1:100000:65536 --rootfs /path/to/rootfs /bin/bash`

Doesn't it make sense for `unshare` to work since I am creating a user namespace? 

**Steps to reproduce the issue:**

1. Create a container: `sudo podman create -it -rm --uidmap=0:1001:1 --uidmap=1:100000:65536 --gidmap=0:1001:1 --gidmap=1:100000:65536 --rootfs /path/to/rootfs /bin/bash`

2.sudo podman unshare id
Error: please use unshare with rootless

**Describe the results you received:**
I was not able to use unshare command with root. 

**Describe the results you expected:**
I would expect to be able to use the unshare command with root. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.3.0-dev
API Version:  3.3.0-dev
Go Version:   go1.16
Git Commit:   dffbf16b24ba971a96db753100b7f43f5d6df3f8
Built:        Thu Jun 10 16:39:20 2021
OS/Arch:      linux/arm64

```

**Output of `podman info --debug`:**

```
host:
  arch: arm64
  buildahVersion: 1.21.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - debug
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/local/bin/conmon'
    path: /usr/local/bin/conmon
    version: 'conmon version 2.0.29-dev, commit: '
  cpus: 4
  distribution:
    distribution: ubuntu
    version: "18.04"
  eventLogger: file
  hostname: pan-appliance
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.9.140
  linkmode: dynamic
  memFree: 31615795200
  memTotal: 33424560128
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 16712269824
  swapTotal: 16712269824
  uptime: 22h 9m 45.72s (Approximately 0.92 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /data/podman/test/root
  graphStatus: {}
  imageStore:
    number: 0
  runRoot: /data/podman/test/run
  volumePath: /data/podman/test/root/volumes
version:
  APIVersion: 3.3.0-dev
  Built: 1623343160
  BuiltTime: Thu Jun 10 16:39:20 2021
  GitCommit: dffbf16b24ba971a96db753100b7f43f5d6df3f8
  GoVersion: go1.16
  OsArch: linux/arm64
  Version: 3.3.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Manual install
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes @ troubleshooting.
No @ latest. 

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical

**Comment by Luap99** [comment]
How should unshare know what user namespace to join? As rootless we always have to run inside a user namespace so unshare will join it.

**Comment by rhatdan** [comment]
We could look to start adding options to podman unshare.

I have been thinking about `$ podman unshare --userns=keep-id` for example to allow users to see what the user namespace looks like. I think it makes sense to also allow specification of the UID mappings as well.

@giuseppe WDYT?

**Comment by giuseppe** [comment]
The user namespace you are creating is specific to the container.

`podman unshare` is used to join the user namespace created for the rootless context to gain capabilities.  That is the environment created for the user, not per container/pod.

For root, it would be equivalent to the same initial environment you are running in, since podman is already running with capabilities.

If you want to join only the container user namespace, you could use `nsenter` as `nsenter -U /proc/$CONTAINER_PID/ns/user $CMD`.

@rhatdan why would we need `podman unshare --userns=keep-id` instead of doing something like `podman run --userns=keep-id --rm  fedora grep . /proc/self/?id_map`?

**Comment by rhatdan** [comment]
I see podman unshare as a means to explore the user namespace as opposed to running within a container.  While I am in in a user namespace I can look at my homedir and files on disk.  I can experiment.  It would also allow me to mount images while in the specific user namespace.

nsenter does not allow me to create the specific user namespace like podman unshare would allow.

**Comment by rhatdan** [comment]
@giuseppe any further comment on this, or should we close.

**Comment by Luap99** [comment]
I don't think it makes sense to have podman unshare as root, it is only used to run in the podman rootless user namespace. 

As mentioned above to join an existing container ns `nsenter` can be used. To create a new userns there is the real `unshare` command that can be used with `--map-users` and `--map-groups` for custom mappings.

**Comment by rhatdan** [comment]
You can continue the conversation here.
