### ISSUE TITLE
Cannot start containers. OCI Runtime Error. 

### ISSUE THREAD

**Issue by ted1922** [containers/podman#13987]
**BUG REPORT**

**Description**

Consistent error - 
`Error: OCI runtime error: unable to start container "xxx": container_linux.go:380: starting container process caused: process_linux.go:393: copying bootstrap data to pipe caused: write init-p: broken pipe` 

This error causes the containers not to start, and as such also causes the systemd server to fail. 

This is on a fresh install (<24hrs) of Alma Linux 8.5 on physical hardware with the container features installed. I have a security profile enabled - [ACSC Essential Eight](https://www.redhat.com/en/resources/acsc-essential-eight-overview). 

**Steps to reproduce the issue:**

1. Attempt to start a container or start  podman-restart.service

**Describe the results you received:**
Within a few seconds of attempting to start a container or the restart.service the error appears in journalctl. 

**Additional information you deem important (e.g. issue happens only occasionally):**
One container (jellyfin) ran at first without issue, but cannot restart. 

Issue persists across restarts of the device. 

**Output of `podman version`:**

```
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.7
Built:        Wed Feb  2 22:32:09 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.32-1.module_el8.5.0+2613+1b78b731.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.32, commit: b3fe0cd74973571b446f22062571b773c021123e'
  cpus: 4
  distribution:
    distribution: '"almalinux"'
    version: "8.5"
  eventLogger: file
  hostname: alma-server
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-348.20.1.el8_5.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 6378557440
  memTotal: 8047263744
  ociRuntime:
    name: runc
    package: runc-1.0.3-1.module_el8.5.0+2613+1b78b731.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.3
      spec: 1.0.2-dev
      go: go1.16.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module_el8.5.0+2613+1b78b731.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 8384409600
  swapTotal: 8384409600
  uptime: 36m 8.65s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/edward/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 0
    stopped: 3
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/edward/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /home/edward/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 1643801529
  BuiltTime: Wed Feb  2 22:32:09 2022
  GitCommit: ""
  GoVersion: go1.16.7
  OsArch: linux/amd64
  Version: 3.4.2


```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.2-9.module_el8.5.0+2613+1b78b731.x86_64

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Not running latest version. 

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on Physical Hardware.

**Comment by Luap99** [comment]
Please try if it works with crun instead.

**Comment by ted1922** [comment]
I'm not sure if installing crun helped. But things now seem to be working? I'm starting/monitoring the containers via the cockpit podman applet. Does crun affect containers started by this method?

**Comment by flouthoc** [comment]
> I'm not sure if installing crun helped. But things now seem to be working even though I'd not tried anything after install crun?

I'm closing this issue since this is resolved. But feel free to re-open.

> Does crun affect containers created & started by this method?
@ted1922 In theory and documentation behavior of `crun` and `runc` is similar but there are instances where podman specific bugs are fixed and merged quickly into upstream crun.

But feel free to re-open this issue if something is unresolved.
