### ISSUE TITLE
Custom volumes configuration in containers.conf is ignored if a container is started with additional volumes

### ISSUE THREAD

**Issue by vikas-goel** [containers/podman#14025]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The customized [containers]::volumes in /etc/containers/containers.conf file setting is disregarded if a container is started with additional container specific volumes. The setting is honored only when no volumes are specified at the time of starting containers.

**Steps to reproduce the issue:**

1. Customize /etc/containers/containers.conf
[containers]
volumes = ["/dev/log:/dev/log",]

2. Start a container with some volumes using `podman run -v ...` option

**Describe the results you received:**

`podman inspect` does not show the /dev/log bind mounted

**Describe the results you expected:**

`podman inspect` should bind mount /dev/log from host inside container

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7

Built:      Tue Mar 15 15:15:06 2022
OS/Arch:    linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.0-1.module+el8.6.0+14131+b9baa4cc.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 69671bb13ee783c4924db64b241139d61db0                                          7321'
  cpus: 8
  distribution:
    distribution: '"rhel"'
    version: "8.6"
  eventLogger: file
  hostname: rhel-vm
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-369.el8.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 31864328192
  memTotal: 33506676736
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.0.3-2.module+el8.6.0+14276+008f0e37.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.3
      spec: 1.0.2-dev
      go: go1.17.5
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_MKNOD,CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRI                                          DE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CA                                          P_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-2.module+el8.6.0+14272+4d6325e6.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 11731464192
  swapTotal: 11731464192
  uptime: 26h 48m 37.3s (Approximately 1.08 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
  - filevol
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 3
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1647371706
  BuiltTime: Tue Mar 15 15:15:06 2022
  GitCommit: ""
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.0.2-1.module_el8.7.0+1106+45480ee0.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM

**Comment by flouthoc** [comment]
Hi @vikas-goel , Thanks for creating the issue.

I think containers.conf is usually configured to set default values and any cli flags we set usually tends to override it but If we want to keep default volumes if they are configured then above PR should close this when it is approved and merged by maintainers https://github.com/containers/podman/pull/14027

**Comment by flouthoc** [comment]
> I think containers.conf is usually configured to set default values and any cli flags we set usually tends to override

After checking this issue again above issue requests for a feature that does not aligns with how defaults are expected to work with `containers.conf` afaik, if a default is configured and cli overrides it using `-v` should newly added volume override the default or should it get merged with default ?  @containers/podman-maintainers WDYT

**Comment by flouthoc** [comment]
Also https://github.com/containers/common/blob/main/docs/containers.conf.5.md explicitly states that it is a default configuration file so if we do anything like `-v` I think we are requesting not to follow the default hence I don't think we could do this as of now since that would leave no way for users to override `containers.conf` they will always inherit the volumes which are meant to be the defaults in `containers.conf`.

But lets wait for other maintainers to reply on this issue.

**Comment by Luap99** [comment]
I guess for default mounts there is already the `mounts.conf` file

**Comment by flouthoc** [comment]
@Luap99 Yes thanks `mounts.conf` solves what is requested in this issue verified with upstream `podman`. 

@vikas-goel I think you should use `mounts.conf` for this exact problem I don't think definition of `containers.conf` aligns with the use-case but please feel free re-open this issue if you still think this needs to be fixed for `containers.conf`.

**Comment by vikas-goel** [comment]
I am observing inconsistent behavior of podman with respect to custom settings in containers.conf. For example, my  /etc/containers/containers.conf file has the below entries:
```
[containers]

default_capabilities = [
  "AUDIT_WRITE",
  "MKNOD",
  "NET_RAW",
  "CHOWN",
  "DAC_OVERRIDE",
  "FOWNER",
  "FSETID",
  "KILL",
  "NET_BIND_SERVICE",
  "SETFCAP",
  "SETGID",
  "SETPCAP",
  "SETUID",
  "SYS_CHROOT"
]

default_sysctls = [
  "net.ipv4.conf.all.forwarding=0",
  "net.ipv4.ip_forward=0",
  "net.ipv4.ping_group_range=0 0",
  "net.ipv6.conf.all.forwarding=0",
]
```

When I start a container with `podman run --cap-add=SYS_ADMIN --sysctl "net.ipv4.tcp_keepalive_time=900`, then both settings (in containers.conf and podman run) are honored.

Is the `volumes` only exception to that?

**Comment by vikas-goel** [comment]
This seems to be working :)
I was comparing the inode of /dev/log inside container and on host. Whereas, it is /dev/log inside container and /run/systemd/journal/dev-log on host.
