### ISSUE TITLE
[Automation] Makefile can give false-positive exit status

### ISSUE THREAD

**Issue by cevich** [containers/podman#14021]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

A handful of lines in Podman's makefile make use of the `$(shell ...)` function simply, or in conjunction with pipes (`|`).  This is especially dangerous for most automation, as it nearly universally assumes "Exit zero means good" and "Exit non-zero means bad".  However, I'm pretty sure (based on experimentation) that the nested-shell environment is neither `set -e` nor `set -o pipefail`.  Therefore, the podman `Makefile` as-is, can very easily give a false-positive exit status and/or produce unexpected compiler output.

**Steps to reproduce the issue:**

1. Instrument `Makefile`, changing `COMMIT_NO ?= $(shell false || true)` and `GIT_COMMIT ?= $(if $(shell false),${COMMIT_NO}-dirty,${COMMIT_NO})` (simulating a broken git or git-configuration).

3. Run `make podman-remote-static; echo $?`

**Describe the results you received:**

Make will exit successfully (0) having built `bin/podman-remote-static` with the linker flag `github.com/containers/podman/v4/libpod/define.gitCommit= ` (empty)

**Describe the results you expected:**

Make should either exit non-zero if there was a consequential failure, or otherwise fail to produce useful artifacts if there was a `$(shell ...)` failure.

**Additional information you deem important (e.g. issue happens only occasionally):**

I have not done an exhaustive analysis of the Makefile to see what other areas may be subject to this "gotcha".

**Output of `podman version`:**

N/A

**Output of `podman info --debug`:**

N/A

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

N/A

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora 34

**Comment by Luap99** [comment]
GIT_COMMIT is a bad example, we should not fail if no commit is found. We had this problem in netavark/aardvark (https://github.com/containers/netavark/issues/247)

If someone downloads the source from the github release page it will not contain the git repo. A make call should not fail because of this.

**Comment by cevich** [comment]
Yes, thanks @Luap99 that's what I was getting at, but more broadly: All `$(shell ...)` errors/exceptions should be handled gracefully in the `Makefile`.  I think this may simply imply more generous use of `$(call err_if_empty,$(shell ...))` (as appropriate)
