### ISSUE TITLE
Invalid cross-device link with named volume

### ISSUE THREAD

**Issue by giuseppe** [containers/podman#14049]
Copied from: https://github.com/coreos/fedora-coreos-tracker/issues/1168

**Describe the bug**
Running a container in podman on fcos next, fails with an exdev error when it tries to rename a file mounted under a named volume to something in the same directory.

**Reproduction steps**

sudo podman run -v "redpanda-test:/var/lib/redpanda/data" docker.io/vectorized/redpanda:v21.11.12
the first run, it will start ok, you should see a log line with "Successfully started Redpanda!"
the second run, the container exits with `Failure during startup: std::__1::__fs::filesystem::filesystem_error (error system:18, filesystem error: rename failed: Invalid cross-device link [/var/lib/redpanda/data/redpanda/kvstore/0_0/snapshot.partial.1649900837775.a1ZO] [/var/lib/redpanda/data/redpanda/kvstore/0_0/snapshot])`
**Expected behavior**
Container should restart without issue, being able to rename the file.

**Actual behavior**
Container dies with an odd error

**System details**

- Bare Metal/QEMU/AWS/GCP/etc. Proxmox VM

- Fedora CoreOS version next (v 36.20220410.1.1)

**Ignition config**
very sparse, just ssh keys, networkmanager configs (would be sanitized) and podman.socket.

**Additional information**
The container starts without issue if I point the directory to a bind mount instead of a named volume. I can only reproduce this on fcos, not on Arch Linux with podman 4.0.3, kernel 5.17.1 or centos 8 stream with podman 4.0.2.

**Comment by nivekuil** [comment]
Should volumes default to noquota for docker compatibility?
