### ISSUE TITLE
podman machine init fails on Mac M1: Error: exec: "qemu-system-x86_64": executable file not found in $PATH

### ISSUE THREAD

**Issue by pvgb** [containers/podman#14079]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Fresh install of Homebrew

2. run brew install qemu 

3. run brew install podman

4. run podman machine init

**Describe the results you received:**
```
Error: exec: "qemu-system-x86_64": executable file not found in $PATH
```

**Describe the results you expected:**
```
Downloading VM image: fedora-coreos-35.20220103.2.0-qemu.x86_64.qcow2.xz
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue has happened multiple times. I have tried to reinstall Homebrew a couple of times and reinstall qemu and podman but it hasnt resolved the issue

Once this happens, any 'podman' command returns the following error:

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.0.3/libpod/_ping": dial unix ///var/folders/5j/twk9tx0d6rs3x4f_f3w5mlhc0000gq/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```

**Output of `podman version`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.0.3/libpod/_ping": dial unix ///var/folders/5j/twk9tx0d6rs3x4f_f3w5mlhc0000gq/T/podman-run--1/podman/podman.sock: connect: no such file or directory
P20VC902R7:adaptor prashanth.vishwanath$ podman --log-level=debug version
INFO[0000] podman filtering at log level debug
DEBU[0000] Called version.PersistentPreRunE(podman --log-level=debug version)
DEBU[0000] DoRequest Method: GET URI: http://d/v4.0.3/libpod/_ping
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.0.3/libpod/_ping": dial unix ///var/folders/5j/twk9tx0d6rs3x4f_f3w5mlhc0000gq/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```

**Output of `podman info --debug`:**

```

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ brew info podman
podman: stable 4.0.3 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/usr/local/Cellar/podman/4.0.3 (172 files, 47.6MB) *
  Poured from bottle on 2022-05-02 at 13:34:47
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0
==> Dependencies
Build: go ✘, go-md2man ✘
Required: qemu ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Analytics
install: 19,178 (30 days), 49,495 (90 days), 130,608 (365 days)
install-on-request: 19,182 (30 days), 49,479 (90 days), 130,587 (365 days)
build-error: 3 (30 days)

$ brew list podman
/usr/local/Cellar/podman/4.0.3/bin/podman
/usr/local/Cellar/podman/4.0.3/bin/podman-mac-helper
/usr/local/Cellar/podman/4.0.3/bin/podman-remote
/usr/local/Cellar/podman/4.0.3/etc/bash_completion.d/podman
/usr/local/Cellar/podman/4.0.3/libexec/gvproxy
/usr/local/Cellar/podman/4.0.3/share/fish/vendor_completions.d/podman.fish
/usr/local/Cellar/podman/4.0.3/share/man/ (161 files)
/usr/local/Cellar/podman/4.0.3/share/zsh/site-functions/_podman
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by baude** [comment]
m1's are apple silicon as you know, which is aarc64 (arm64).  The fact that it is trying to run x86_64 qemu (and does not find it) is likely a result of you migrating something to this mac from a previous one or rosetta is being used with brew.  i would recommend you get the aarch64 version of brew installed.

**Comment by rhatdan** [comment]
I don't think this is an issue with our Podman, so closing.  Reopen if I am mistaken. Conversation can continue here.

**Comment by pvgb** [comment]
> m1's are apple silicon as you know, which is aarc64 (arm64). The fact that it is trying to run x86_64 qemu (and does not find it) is likely a result of you migrating something to this mac from a previous one or rosetta is being used with brew. i would recommend you get the aarch64 version of brew installed.

I did a fresh install of Homwbrew, Qemu and podman which should have caught that. And the brew version I have supports aarch64

**Comment by pvgb** [comment]
After a 4th install of Homebrew, and reinstalling qemu and podman, it finally works.

I have no idea what was different this time.
