### ISSUE TITLE
go bindings cannot be used on all v3.0.x releases

### ISSUE THREAD

**Issue by edoput** [containers/podman#14090]
/kind bug

**Description**

Adding a dependency on v3.0.x in a go project results in an error because of incompatible major version between the go module and the git release.

```bash
$ go get -d github.com/containers/podman/v2@v3.0.0
go get: github.com/containers/podman/v2@v3.0.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v2, not v3
```

From release v3.1.0-rc1 the module version becomes v3 and the go bindings become usable.

This means that it's not possible to use the releases v3.0.x as go bindings. If the API check in the client does not allow for retrocompatibility then any podman v3.0.x server cannot be reached using the official bindings.

I am also unable to use the combination of v3.1.0 as client and v3.0.1 as server because the API version was bumped from 3.0.0 to 3.1.0  and the client will not use the older API.

**Steps to reproduce the issue:**

1. Start a new go project with modules
2. Add a dependency on podman/v2@v3.0.0

**Describe the results you received:**

Go toolchain refuses to add the dependency because of a mismatch between the go module version (v2) and the git release (v3.0.0).

**Describe the results you expected:**

Same as received.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.15
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.6
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 2
  distribution:
    distribution: debian
    version: "11"
  eventLogger: journald
  hostname: scw-fervent-panini
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.28-scaleway
  linkmode: dynamic
  memFree: 417705984
  memTotal: 2075570176
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 39h 39m 41.4s (Approximately 1.62 days)
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 11
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.15
  OsArch: linux/amd64
  Version: 3.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/stable,now 3.0.1+dfsg1-3+deb11u1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes I have read the troubleshooting. Does not apply to latest podman.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

scaleway VPS

**Comment by edoput** [comment]
I am not sure what is the right course of action. The go modules published under v3.0.x could be retracted but this is also an issue with downstream users of podman.

Debian stable ships v3.0.1 as the podman server and this means that third party tools cannot use it.

**Comment by Luap99** [comment]
I don't think there is much we can do to fix it.
The only option I see is bumping the module version to v3 on the 3.0 branch
cc @vrothberg

**Comment by vrothberg** [comment]
I asked @edoput on IRC to open the issue to have an async conversation with more folks.

> The only option I see is bumping the module version to v3 on the 3.0 branch

Totally agree.  That is the only option I see.

If others agree, we should probably create a BZ so we can merge into the v3.0.1-rhel branch.

**Comment by vrothberg** [comment]
@containers/podman-maintainers PTAL

**Comment by Luap99** [comment]
Why do you want to merge this into the rhel branch? We do not tag anything there. People that use the bindings want a tag so they can specify it in their go.mod. Therefore I think we should just cut from the v3.0 branch. I don't think the rhel version requires any change.

**Comment by mheon** [comment]
v3.0 branch SGTM

**Comment by vrothberg** [comment]
> Why do you want to merge this into the rhel branch? We do not tag anything there. People that use the bindings want a tag so they can specify it in their go.mod. Therefore I think we should just cut from the v3.0 branch. I don't think the rhel version requires any change.

Debian is using that branch AFAIK.  But I think your point is valid.

v3.0 branch sounds good to me.

**Comment by vrothberg** [comment]
Good news, apparently I already performed this change in the v3.0 branch (see https://github.com/containers/podman/commit/cb475b82ab759d5dd0302de8c3b78e7337a6b2e2).

@mheon, would you cut a `v3.0.2` from that branch?

**Comment by edoput** [comment]
Is there a reason the fix release has not been tagged yet?

**Comment by rhatdan** [comment]
@mheon PTAL

**Comment by mheon** [comment]
https://github.com/containers/podman/pull/14257

**Comment by vrothberg** [comment]
Closing as v3.0.2 has been released.
