### ISSUE TITLE
Using --since and -f in combination when using podman logs

### ISSUE THREAD

**Issue by Morgyn** [containers/podman#14104]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Using --since/--tail together with -f when issuing `podman logs`

Currently when you use both in combination, only since is observed and the log is not followed.

When viewing logs it's handy to get the last few lines before following to get context of the current lines, similar to the GNU `tail -n 10 -f command`

This combination works with docker, and it was very useful.

**Steps to reproduce the issue:**

tail -n 10 -f <file>
podman logs --since 1h -f <container>
docker logs --since 1h -f <container>

**Comment by vrothberg** [comment]
Thanks for reaching out, @Morgyn!

Please fill out the entire issue template (e.g., `podman info --debug` etc.) so we have all the data at hand.  Can you share the output of `podman info --debug` and paste it here?  I assume you are using an older version of Podman.  I cannot reproduce on v4.0.

**Comment by Morgyn** [comment]
```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpus: 2
  distribution:
    distribution: fedora
    variant: server
    version: "35"
  eventLogger: journald
  hostname: sebbyk
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.16.20-200.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 169525248
  memTotal: 10400415744
  ociRuntime:
    name: crun
    package: crun-1.4.4-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.4
      commit: 6521fcc5806f20f6187eb933f9f45130c86da230
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 8018718720
  swapTotal: 8589930496
  uptime: 6h 49m 7.28s (Approximately 0.25 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 2
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.7
  Built: 1650546866
  BuiltTime: Thu Apr 21 14:14:26 2022
  GitCommit: ""
  GoVersion: go1.16.15
  OsArch: linux/amd64
  Version: 3.4.7

```

It's 3.4.7 which I believe is the latest released version, obviously something could have changed since the release. 

I note that it's mentioned in the ```podman logs --help``` as an example:
```podman logs --follow=true --since 10m ctrID```

But this doesn't work for me, as it performs just the ```--since``` part with no ```--follow```

**Comment by vrothberg** [comment]
Thanks, @Morgyn.  Can you share a reproducer?  I cannot reproduce with v3.4.7 either.

**Comment by Morgyn** [comment]
```
# podman run -d --name followtest --rm docker.io/morgyn/followtest
d5468447c7c15391ba416a5d8ab0b140068cd5288699285b46eb4e9a91830091
# podman ps
CONTAINER ID  IMAGE                                   COMMAND               CREATED             STATUS                 PORTS                                               NAMES
d5468447c7c1  docker.io/morgyn/followtest:latest      /start.sh             About a minute ago  Up About a minute ago                                                      followtest
# podman logs -f followtest
Wed May  4 10:59:06 UTC 2022
Wed May  4 11:00:06 UTC 2022
Wed May  4 11:01:06 UTC 2022
^C# podman logs --since 2m followtest
Wed May  4 11:00:06 UTC 2022
Wed May  4 11:01:06 UTC 2022
# podman logs --follow=true --since 2m followtest
Wed May  4 11:00:06 UTC 2022
Wed May  4 11:01:06 UTC 2022
# podman logs -f --since 2m followtest
Wed May  4 11:00:06 UTC 2022
Wed May  4 11:01:06 UTC 2022
# podman logs --since 2m -f followtest
Wed May  4 11:01:06 UTC 2022
Wed May  4 11:02:06 UTC 2022
```

Note the only one I had to ctrl+c was the one with only follow, all the others terminated after displaying the last 2 mins of logs.

**Comment by Morgyn** [comment]
https://github.com/Morgyn/followtest

Is the source of the test container, if you need to check it for some reason

**Comment by vrothberg** [comment]
Thanks!

I am still unable to reproduce. Tested Podman v3.4.7 and v4.0.3 and the k8s-file and the journald log driver.

@containers/podman-maintainers can you have a look?

**Comment by Luap99** [comment]
I also can not reproduce. I tried latest main with both journald and k8s-file driver.

**Comment by Morgyn** [comment]
I've just performed a clean install of fedora 35 + podman 3.4.7 on a freshly installed VM and the problem isn't there...

So this appears a unique problem to this install.

**Comment by vrothberg** [comment]
@Morgyn, does the container continue to run _after_ `podman logs` exited?

**Comment by rhatdan** [comment]
Reopen if you get it to happen again.

**Comment by vrothberg** [comment]
Re-opening as we don't know what's going on.

**Comment by Morgyn** [comment]
I have resolved the issue by uninstalling and reinstalling podman with a reboot. I feel an older binary must have been sticking around.

Apologies for wasting peoples time.

**Comment by vrothberg** [comment]
Not at all. Thanks for reaching out!

**Comment by p-himik** [comment]
I can reproduce it on Ubuntu 22.04 with both the default 3.4.7 and the latest 4.3.0, even after removing `~/.local/share/containers`.

**Comment by Luap99** [comment]
@p-himik Please create a new issue with a reproducer. As mentioned above, we are unable to reproduce.
