### ISSUE TITLE
cant make?

### ISSUE THREAD

**Issue by dvg06** [containers/podman#14105]
[ec2-user@ip-10-250-192-14 podman]$ make BUILDTAGS=""
Podman is being compiled without the systemd build tag.         Install libsystemd on Ubuntu or systemd-devel on rpm based      distro for journald support.
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build \
        -mod=vendor  \
        -ldflags '-X github.com/containers/podman/v4/libpod/define.gitCommit=3d84661195aa8fbf3dab67375099cb991fd7fe81-dirty -X github.com/containers/podman/v4/libpod/define.buildInfo=1651637810 -X github.com/containers/podman/v4/libpod/config._installPrefix=/usr/local -X github.com/containers/podman/v4/libpod/config._etcDir=/usr/local/etc -X github.com/containers/common/pkg/config.additionalHelperBinariesDir= ' \
        -tags "" \
        -o bin/podman ./cmd/podman
# github.com/proglottis/gpgme
vendor/github.com/proglottis/gpgme/data.go:176:12: could not determine kind of name for C.gogpgme_data_seek
vendor/github.com/proglottis/gpgme/data.go:176:38: could not determine kind of name for C.gpgme_off_t
cgo:
gcc errors for preamble:
In file included from vendor/github.com/proglottis/gpgme/data.go:6:0:
./go_gpgme.h:15:8: error: unknown type name 'gpgme_off_t'
 extern gpgme_off_t gogpgme_data_seek(gpgme_data_t dh, gpgme_off_t offset, int whence);
        ^~~~~~~~~~~
./go_gpgme.h:15:55: error: unknown type name 'gpgme_off_t'; did you mean 'gpgme_key_t'?
 extern gpgme_off_t gogpgme_data_seek(gpgme_data_t dh, gpgme_off_t offset, int whence);
                                                       ^~~~~~~~~~~
                                                       gpgme_key_t

make: *** [bin/podman] Error 2

**Comment by Luap99** [comment]
Please provide more details. What version are you trying to compile and on which distro?
Have you installed the dependencies listed here https://podman.io/getting-started/installation#build-and-run-dependencies?

**Comment by otterley** [comment]
Looks like this is an issue with compiling Podman 4.1.0 (possibly other versions as well) on Amazon Linux 2. I encountered the same problem just now.

**Comment by dvg06** [comment]
It worked for me on a centos, just couldn’t make it work on amazon linux

**Comment by otterley** [comment]
It appears to be an underlying issue with the [Go gpgme bindings](http://github.com/proglottis/gpgme). Looks like it doesn't have backward compatibility with some older gpgme versions, such as the one that ships with AL2.

**Comment by Luap99** [comment]
We can cannot reasonable support such old versions, including RHEL7 which seems to be the base for AL2.
You could try to use the `containers_image_openpgp` build tag to make it not use the c lib..
