### ISSUE TITLE
How to grab runtime directory ?

### ISSUE THREAD

**Issue by benoitf** [containers/podman#14113]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Following the discussion there https://github.com/containers/podman/pull/14085#issuecomment-1116981185
It's possible to add sockets to receive machine events notifications
But how to get that folder from a podman command ? (the path is computed with 56 lines https://github.com/containers/podman/blob/main/vendor/github.com/containers/common/pkg/util/util_supported.go#L30-L86)

**Steps to reproduce the issue:**

1. Want to add socket file for listening to machine events

2. How to find the path ?

**Describe the results you received:**

Unable to grab the value of the runtime directory easily

**Describe the results you expected:**

Get that path with a podman command

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@ashley-cui PTAL

**Comment by ashley-cui** [comment]
@baude I vaguely recall discussion on this, on how it can't be an env var or in machine inspect because of the chicken-and-egg problem. Do you recall what the consensus was on this?
