### ISSUE TITLE
CI corner-case: Rootless testing on non-main branches

### ISSUE THREAD

**Issue by cevich** [containers/podman#14131]
/kind bug

**Description**

  [This resulted in the following output](https://cirrus-ci.com/task/4752844124323840?logs=main#L13) from the 'Rootless unit on fedora-36':

**Steps to reproduce the issue:**

1. Branching from `main` to `v4.1` the `$DEST_BRANCH` variable is properly updated in `.cirrus.yml` along with a change to `GIT_BASE_BRANCH ?= origin/v4.1` in the `Makefile`.  This is all good and expected.

2. Run the 'Rootless unit on fedora-36' test in CI

3. When running as the rootless user, most/all Cirrus-CI env. vars. are lost by the ssh-exec.  Critically, it seems `$DEST_BRANCH` defaults to main (by way of `lib.sh`).

**Describe the results you received:**

```
/usr/bin/time --verbose --output="$STATS_LOGFILE" $GOSRC/$SCRIPT_BASE/runner.sh
************************************************************
Runner executing unit podman-tests as rootless on fedora-35(fedora-35)
Current environment VM image: fedora-c4831699639992320
************************************************************
Re-executing runner through ssh as user 'some3201dude'
************************************************************
+ exec ssh some3201dude@localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o CheckHostIP=no /var/tmp/go/src/github.com/containers/podman/./contrib/cirrus/runner.sh
Warning: Permanently added 'localhost' (ED25519) to the list of known hosts.
************************************************************
Runner executing unit podman-tests as rootless on fedora-35(fedora-35)
Current environment VM image: fedora-c4831699639992320
************************************************************
fatal: Not a valid object name main
Exit status: 128
```

**Describe the results you expected:**

```
/usr/bin/time --verbose --output="$STATS_LOGFILE" $GOSRC/$SCRIPT_BASE/runner.sh
************************************************************
Runner executing unit podman-tests as rootless on fedora-36(fedora-36)
Current environment VM image: fedora-c4955393725038592
************************************************************
Recursively chowning $GOPATH and $GOSRC to some25741dude
Re-executing runner through ssh as user 'some25741dude'
************************************************************
+ exec ssh some25741dude@localhost -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o CheckHostIP=no /var/tmp/go/src/github.com/containers/podman/./contrib/cirrus/runner.sh
Warning: Permanently added 'localhost' (ED25519) to the list of known hosts.
************************************************************
Runner executing unit podman-tests as rootless on fedora-36(fedora-36)
Current environment VM image: fedora-c4955393725038592
************************************************************
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -mod=vendor  -ldflags '-X ...cut...
```

**Additional information you deem important (e.g. issue happens only occasionally):**

The error is coming from [_bail_if_test_can_be_skipped()](https://github.com/containers/podman/blob/3e5e0d2626145c7dad7a1de29982a2f513262a1b/contrib/cirrus/runner.sh#L390-L392).  

**Output of `podman version`:**

```
N/A
```

**Output of `podman info --debug`:**

```
N/A
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
N/A
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

When preparing a new branch for CI, it's unreasonable to expect developers to remember to update much more than `.cirrus.yml` and maybe the `Makefile`.  We should either ensure the necessary env. vars. are passed to the rootless user or bypass the `_bail` optimization all together.  Pass-through env. vars. can be set in the rootless user's environment by ensuring they get written during `setup_environment.sh`, [so they are loaded properly later](https://github.com/containers/podman/blob/3e5e0d2626145c7dad7a1de29982a2f513262a1b/contrib/cirrus/lib.sh#L37).

**Comment by cevich** [comment]
@edsantiago do you have an opinion on this?

**Comment by Luap99** [comment]
Also looks like the bloat check is not working correctly, https://github.com/containers/podman/pull/14132 triggered this for some reason. I guess it uses the wrong base commit to compare to, it reabes 30 commits but the PR only has 8 commits in it. https://cirrus-ci.com/task/5208209660051456?logs=main#L499

**Comment by cevich** [comment]
@Luap99 the bloat-detector issue appears to be something different, though definitely an unaccounted for corner-case.  I think it's caused by referencing the HEAD of the branch at the time when the task in the PR runs.  So especially if a PR is against a new branch, or hasn't been rebased in a while, strange/unexpected things can happen (from a PR-author perspective, whom doesn't grok the clashing repo. states).  That's why I recommended @edsantiago make this check be based on the actual `bin/*` artifacts we upload in CI.  Or at least be based on `$CIRRUS_CHANGE_IN_REPO` or `$CIRRUS_BASE_SHA` instead of `origin/"${DEST_BRANCH}^` so it's checking relative to the PR instead of the branch HEAD (i.e. a constantly moving target).
