### ISSUE TITLE
Include podman server version in podman -v 

### ISSUE THREAD

**Issue by katywings** [containers/podman#14149]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I was checking my podman version with `podman -v` and it showed me `podman version 4.1.0` so I was expecting that I am indeed running 4.1.0. Later I figured out, that podman inside the podman machine actually still was on `4.0.3` 😂.

My suggestion is to include the server version in `podman -v`. This would make `podman -v` consistent with `podman version` which actually already does show the client *and* the server version.

**Describe the results you received:**

`podman version 4.1.0`

**Describe the results you expected:**

`podman version client: 4.1.0 / server: 4.0.3`

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- macOS 10.15.7 (Catalina) with podman machine

**Comment by rhatdan** [comment]
podman -v currently does not communicate with the server, I believe.

`podman version` should, and would show you the version.
