### ISSUE TITLE
Podman machine init fails on Windows (v4.0.3 & v4.1.0)

### ISSUE THREAD

**Issue by AledLewis** [containers/podman#14155]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`podman machine init` fails to execute successfully and instead loops through infinite iterations of: 

```
error: cannot open Packages index using sqlite - No such file or directory (2)
error: cannot open Packages database in /var/lib/rpm
error: sqlite failure: CREATE TABLE IF NOT EXISTS 'Packages' (hnum INTEGER PRIMARY KEY AUTOINCREMENT,blob BLOB NOT NULL): locking protocol
```

Just before the loop starts, the below logs appear: 

```
Copr repo for podman4 owned by rhcontainerbot                                                         11 kB/s | 1.0 kB     00:00
Importing GPG key 0x2F6C3CBA:
 Userid     : "rhcontainerbot_podman4 (None) <rhcontainerbot#podman4@copr.fedorahosted.org>"
 Fingerprint: 79B5 022D 580F B1D6 B527 CB83 3BB2 485A 2F6C 3CBA
 From       : https://download.copr.fedorainfracloud.org/results/rhcontainerbot/podman4/pubkey.gpg
Key imported successfully
error: sqlite failure: CREATE TABLE IF NOT EXISTS 'Packages' (hnum INTEGER PRIMARY KEY AUTOINCREMENT,blob BLOB NOT NULL): locking protocol
error: cannot open Packages index using sqlite - No such file or directory (2)
error: cannot open Packages database in /var/lib/rpm
Import of key(s) didn't help, wrong key(s)?
```

**Steps to reproduce the issue:**
Windows 10 19044.1682 + WSL2

* Run `podman machine init`

**Describe the results you received:**

Infinite loop of error messages

**Describe the results you expected:**

Podman machine inits.

**Additional information you deem important (e.g. issue happens only occasionally):**

Tested across two versions of Podman v4.1.0 and v4.0.3

**Output of `podman version`:**

```
podman.exe version 4.0.3
```

**Output of `podman info --debug`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: failed to parse identity "C:\\Users\\aled.lewis\\.ssh\\podman-machine-default": open C:\Users\aled.lewis\.ssh\podman-machine-default: The system cannot find the path specified.
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Comment by n1hility** [comment]
@AledLewis that sounds like you are having some sort of storage issue. 

Do you have any other WSL distributions installed? Or is podman the first user of it on your system? If you do are they working ok?

Can you try the following:

1. Start from a clean system reboot (if hyper-v (used by WSL) ever gets into a strange state, shutting down and restarting is sometimes necessary)
2. Delete the machine which is half created (podman machine rm - say yes)
3. Confirm you have a decent amount of freespace on your windows system drive (assuming c)-
4. Grab and paste the output of `wsl --status`
5. Repeat the podman machine init
6. if it fails again ctrl c or start another window and run wsl dmesg > dmesg.log 
6b. Create a gist and link it here

Thanks!

**Comment by danvenn** [comment]
I'm having the same error after a reboot! Latest release.
![image](https://user-images.githubusercontent.com/6608960/170956253-2d7c2fe4-30ba-4bc3-8d86-dda499100709.png)

**Comment by findziliao** [comment]
I'm having the same error after a reboot! Latest release.
![image](https://user-images.githubusercontent.com/35827985/174435820-01b6014f-f3a2-4468-acfe-a4f051785b46.png)

**Comment by findziliao** [comment]
It started to work after making WSL2 the default.

wsl --set-default-version 2

**Comment by rhatdan** [comment]
Podman only works with WSL2.

**Comment by phvajjha** [comment]
> It started to work after making WSL2 the default.
> 
> wsl --set-default-version 2

I had the same problem. I have been using WSL for a while now with multiple machines. Moved from WSL1 to WSL2. Did not realize that the default was still set to WSL1. Thanks for the tip!

**Comment by sereneshikari** [comment]
Hello @n1hility, I'm trying to install Podman on Windows but am facing the same error as the original poster did. I tried following the steps you mentioned and am still facing this error. Here is my configuration:

| Name | Value |
| --- | --- |
| Podman version |  `4.1.1` |
| WSL Kernel version | `4.19.128` |
| WSL Default version | 2 |

I _do_ have other WSL distributions installed, namely the ones that come with Docker Desktop, and Ubuntu 20.04. Not sure if this is a problem.

I am certain I have sufficient space in my `C:\` drive (the _Properties_ window shows 758GB)

**Output from `wsl --status`**:
```console
> wsl --status
Default Distribution: Ubuntu-20.04
Default Version: 2

Windows Subsystem for Linux was last updated on 13-10-2020
WSL automatic updates are on.

Kernel version: 4.19.128
```

I have also created [a gist](https://gist.github.com/sereneshikari/5f912b5cd0d9d015f56f9d03cd1fe90b) that contains the `dmesg.log` from WSL.
Could you please take a look?

**Comment by sereneshikari** [comment]
@n1hility, it turns out _it's not_! Very surprising but:
```console
> wsl -l -v
  NAME                      STATE           VERSION
* Ubuntu-20.04              Stopped         2
  docker-desktop-data       Stopped         2
  podman-machine-default    Stopped         1
  docker-desktop            Stopped         2
```

I'm not very familiar with WSL so could you please tell me what I should do to make sure the WSL instance gets created as v2?

**Comment by n1hility** [comment]
@sereneshikari cool that explains it then. Try the following:

```
podman machine rm
wsl —shutdown
# confirm it’s gone 
wsl -l -v
# recreate it
podman machine init 
```

**Comment by phvajjha** [comment]
> @sereneshikari cool that explains it then. Try the following:
> 
> ```
> podman machine rm
> wsl —shutdown
> # confirm it’s gone 
> wsl -l -v
> # recreate it
> podman machine init 
> ```

You might have to run this after shutting down WSL:
wsl --set-default-version 2

**Comment by sereneshikari** [comment]
Thank you @n1hility and @phvajjha, it's working now 🥳 
I wanted to try out a few `podman` commands before I could post here that it was working so thanks for your patience, advice, and time!

**Comment by sereneshikari** [comment]
Ack, I guess I spoke too soon! When I want to exit by running `podman machine stop`, I get:
```
> podman machine stop
Could not stop API forwarding service (win-sshproxy.exe): open C:\Users\<USER>\.local\share\containers\podman\machine\wsl\podman-machine-default\win-sshproxy.tid: The system cannot find the file specified.
Error: Error stopping sysd: exit status 1
```

And `wsl -l -v` shows that it's still running:
```
> wsl -l -v
  NAME                      STATE           VERSION
* Ubuntu-20.04              Stopped         2
  podman-machine-default    Running         2
  docker-desktop-data       Stopped         2
  docker-desktop            Stopped         2
```

I recognise this may be a different, unrelated issue. Should I create a new issue for this?

**Comment by n1hility** [comment]
@sereneshikari this is probably a defunct hold over process from when things were running as WSL1. Try doing 
``` 
taskkill /im win-sshproxy.exe 
wsl --shutdown
podman machine start
```

**Comment by sereneshikari** [comment]
@n1hility, thanks for your response. Unfortunately, running `taskkill` doesn't seem to work; I get this error:
```console
> taskkill /im win-sshproxy.exe
ERROR: The process "win-sshproxy.exe" not found.
```

The remaining commands work fine but once the machine is started and I want to stop it again using `podman machine stop`, I get just the `sysd` error and if I try running the stop command again, I get the same error as before:
```console
> podman machine stop
Error: Error stopping sysd: exit status 1

> podman machine stop
Could not stop API forwarding service (win-sshproxy.exe): open C:\Users\<USER>\.local\share\containers\podman\machine\wsl\podman-machine-default\win-sshproxy.tid: The system cannot find the file specified.
Error: Error stopping sysd: exit status 1
```

**Comment by sereneshikari** [comment]
@n1hility, thanks for your reply. Unfortunately, the instructions didn't help. Running the `taskkill` command just gives me:
```console
ERROR: The process "win-sshproxy.exe" not found.
```

**Comment by n1hility** [comment]
@sereneshikari what does the systemctl status look like after these commands
```
wsl --shutdown
podman machine start
wsl enterns systemctl status
```

**Comment by sereneshikari** [comment]
@n1hility, sincere apologies for the delayed response. It seems you've already found (and resolved) the issue but for the sake of completeness, I'll post the output:
```console
> wsl nsenter systemctl status
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

PS: Between my last message and now, I destroyed the `podman-machine-default` VM and recreated it again today using `podman machine init`

PPS: When I ran `enterns` instead of `nsenter`, I got an error:
```console
/bin/bash: enterns: command not found
```
but when I looked it up online, I realised you probably meant `nsenter`
