### ISSUE TITLE
Regression: podman 4.0.3 -> 4.1.0 - fuse-overlayfs used instead of native overlayfs

### ISSUE THREAD

**Issue by alxchk** [containers/podman#14165]
> podman --version
podman version 4.1.0

After updating to 4.1.0 podman began to start fuse-overlayfs instead of native overlayfs driver in rootless mode.
Config remains the same. Running podman --loglevel DEBUG ... 2>/tmp/log ; grep fuse /tmp/log gives nothing.

If you are interesting in some particular traces please let me know.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
I cannot reproduce locally.  Was the kernel updated/changed as well?

Do you have any `~/.config/containers/storage.conf` file?

Could you run `podman --log-level debug ...` and attach the output?

**Comment by alxchk** [comment]
No, kernel and configuration files remains the same.
Kernel is 5.17.

I made diff, and 4.0.3 shows strings like "Cached value indicated that overlay is supported", which are missing from 4.1.0 log.

[podman-4.0.3.log](https://github.com/containers/podman/files/8659348/podman-4.0.3.log)
[podman-4.1.0.log](https://github.com/containers/podman/files/8659349/podman-4.1.0.log)
[storage.conf.txt](https://github.com/containers/podman/files/8659360/storage.conf.txt)

**Comment by giuseppe** [comment]
could you temporarily try without the storage.conf file and removing all the files under `/run/user/$UID/containers/overlay`?  You can rename it to something else.

The only change I see that could have caused this problem is https://github.com/containers/storage/pull/1165

**Comment by alxchk** [comment]
Yes, without storage.conf (and as graphroot becomes non default this also means that it's fresh) fuse-overlayfs is not running.

**Comment by giuseppe** [comment]
could you try removing the file `.has-mount-program` that is inside the graphroot (`/mnt/vm/libpod/avatar/graph/overlay`)?

**Comment by alxchk** [comment]
Removed, fuse-overlayfs still launched. It's created again with "true" inside.
However, when true changed to false, fuse-overlayfs is not started

**Comment by giuseppe** [comment]
not sure why it is not detected on your system.  What is the output of `podman info`?

To make sure the test is performed again, you need to remove that file then remove any file under `/run/user/$UID/containers/overlay`.

Would it be feasible for you to run `podman system reset`?  In case you can run that, does the issue still persist?

**Comment by giuseppe** [comment]
thanks for confirming it.

Can this issue be closed now?

**Comment by rhatdan** [comment]
Could be an upgrade issue.  Will see if it happens to anyone else.
