### ISSUE TITLE
networking broken in rawhide?

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#14169]
Trivially reproduces on rawhide (f37):
```console
# podman run -d --name foo  -p 127.0.0.1:52515:52515 quay.io/libpod/testimage:20210610 nc -l -n -v -p 52515
b7b068b6b8b313c087d4e7c884f92c229b1130cdf24a6e4d0b687b9ab85a86fb
# echo hi | nc 127.0.0.1 52515     <--- returns immediately, i.e., does not hang or time out
# podman logs foo
listening on [::]:52515 ...
connect to [::ffff:10.88.0.29]:52515 from [::ffff:10.88.0.1]:57764 ([::ffff:10.88.0.1]:57764)
```
(expected to see `hi`).

Note that the command-line `nc` returns immediately (as opposed to hanging/timeout, which is what we see when there's a `cni-podman0` interface on the system). 

On the slim chance that it's helpful:
```
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether fa:16:3e:77:54:28 brd ff:ff:ff:ff:ff:ff
    altname enp0s3
    altname ens3
    inet 10.0.137.112/22 brd 10.0.139.255 scope global dynamic noprefixroute eth0
       valid_lft 35237sec preferred_lft 35237sec
    inet6 2620:52:0:88:f816:3eff:fe77:5428/64 scope global dynamic noprefixroute 
       valid_lft 2591895sec preferred_lft 604695sec
    inet6 fe80::f816:3eff:fe77:5428/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

aardvark-dns-1.0.3-1.fc37.x86_64
netavark-1.0.3-3.fc37.x86_64

This is causing gating-test failures for podman on f37.

**Comment by Luap99** [comment]
I am unable to reproduce on rawhide. What is the podman version you are using?

**Comment by edsantiago** [comment]
The one we were discussing yesterday: [4.1.0-2.fc37](https://bodhi.fedoraproject.org/updates/FEDORA-2022-874912dc1e)

**Comment by Luap99** [comment]
For future readers, the problem is caused by this patch: https://src.fedoraproject.org/rpms/nmap/c/5a4dbdf721c79fdcfc75cd55a72b1be1bb2db5ca?branch=rawhide

**Comment by edsantiago** [comment]
Let's leave this open: if they don't fix the `nc` bug, we will have to panic-scramble to find a new way to run tests.
