### ISSUE TITLE
Aardvark Test 5: Two containers on their own subnets, one container on both

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#14171]
```
  Aardvark Test 5: Two containers on their own subnets, one container on both
...
? Failure [9.418 seconds]
         Podman run networking
         /var/tmp/go/src/github.com[/containers/podman/test/e2e/run_aardvark_test.go:14](https://github.com/containers/podman/blob/8ecd0b5bc8b230dd9d213fb252178d1344744511/test/e2e/run_aardvark_test.go#L14)
           Aardvark Test 5: Two containers on their own subnets, one container on both [It]
           /var/tmp/go/src/github.com[/containers/podman/test/e2e/run_aardvark_test.go:204](https://github.com/containers/podman/blob/8ecd0b5bc8b230dd9d213fb252178d1344744511/test/e2e/run_aardvark_test.go#L204)
         
           Expected
               <string>: 
           to match regular expression
               <string>: (25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}
         
           /var/tmp/go/src/github.com[/containers/podman/test/e2e/common_test.go:1057](https://github.com/containers/podman/blob/8ecd0b5bc8b230dd9d213fb252178d1344744511/test/e2e/common_test.go#L1057)
```
### Podman run networking [It] Aardvark Test 5: Two containers on their own subnets, one container on both 
* fedora-35 : Netavark int podman root
  * PR #13662
    * [03-25 11:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4594481012932608/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--1)
    * [03-25 11:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4594481012932608/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--2)
    * [03-25 11:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4594481012932608/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--3)
  * PR #13575
    * [03-21 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4749337602293760/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--1)
    * [03-21 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4749337602293760/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--2)
    * [03-21 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4749337602293760/html/int-podman-fedora-35-root-host-netavark.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--3)
* fedora-36 : int podman fedora-36 root container
  * PR #14059
    * [05-03 23:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4984424818278400/html/int-podman-fedora-36-root-container.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--1)
* fedora-36 : int podman fedora-36 root host
  * PR #14163
    * [05-09 13:02](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6619009629028352/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--1)
    * [05-09 13:02](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6619009629028352/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--2)
    * [05-09 13:02](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6619009629028352/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--3)
  * PR #14066
    * [05-04 11:25](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5054796112592896/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--1)
    * [05-04 11:25](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5054796112592896/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--2)
   * PR #14060
     * [05-04 08:52](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4685276319580160/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--1)
     * [05-04 08:52](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4685276319580160/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--2)
     * [05-04 08:52](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4685276319580160/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--3)
  * PR #14040
    * [04-28 08:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5047243462934528/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--1)
    * [04-28 08:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5047243462934528/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--2)
    * [04-28 08:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5047243462934528/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--3)

**Comment by edsantiago** [comment]
### Podman run networking [It] Aardvark Test 5: Two containers on their own subnets, one container on both 
* fedora-36 : int podman fedora-36 root host
  * PR #14533
    * [06-09 10:01](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5797344032587776/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--1)
    * [06-09 10:01](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5797344032587776/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--2)
    * [06-09 10:01](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5797344032587776/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--3)
  * PR #14477
    * [06-03 09:58](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6481516686475264/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--1)
    * [06-03 09:58](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6481516686475264/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--2)
    * [06-03 09:58](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6481516686475264/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--3)
  * PR #14256
    * [05-16 12:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4750591279759360/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--1)
    * [05-16 12:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4750591279759360/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--2)
    * [05-16 12:33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4750591279759360/html/int-podman-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--3)
* fedora-36 : int remote fedora-36 root host [remote]
  * PR #14455
    * [06-02 09:17](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4795978581540864/html/int-remote-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--1)
    * [06-02 09:17](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4795978581540864/html/int-remote-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--2)
    * [06-02 09:17](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4795978581540864/html/int-remote-fedora-36-root-host.log.html#t--Aardvark-Test-5--Two-containers-on-their-own-subnets--one-container-on-both--3)

**Comment by flouthoc** [comment]
There is a bigger design change under discussion which should help in this as well as some other issue, please track it here. However it will take some time to get merged: https://github.com/containers/aardvark-dns/pull/148
