### ISSUE TITLE
volume leaking cause "error allocating lock for new container: allocation failed; exceeded num_lock"

### ISSUE THREAD

**Issue by ttys3** [containers/podman#14195]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I got this recently.

```shell
# podman run --rm -ti  alpine sh
Error: error allocating lock for new container: allocation failed; exceeded num_locks (2048)
```

concurrent to create about < 30 containers, then I got deadlock, all containers can not create now.

here's the containers created after one by one total:
```
# podman ps | wc -l
22
```

I changed `num_locks` limit from 2048 to 4096, but this does not help at all.
```
allocation failed; exceeded num_locks (4096)
```

after changed to `num_locks = 8192`, things seems to work.

I put some debug logging into podman code. so when it try to get a shm lock and success, it print a log with special prefix `xxdebug`.

when it try to get a shm lock and failed, it also print a log with special prefix `xxdebug`.

```diff
diff --git a/libpod/runtime_ctr.go b/libpod/runtime_ctr.go
index df7174ac6..68e9041c7 100644
--- a/libpod/runtime_ctr.go
+++ b/libpod/runtime_ctr.go
@@ -299,7 +299,7 @@ func (r *Runtime) setupContainer(ctx context.Context, ctr *Container) (_ *Contai
        }
        ctr.lock = lock
        ctr.config.LockID = ctr.lock.ID()
-       logrus.Debugf("Allocated lock %d for container %s", ctr.lock.ID(), ctr.ID())
+       logrus.Infof("xxdebug Allocated lock %d for container %s name: %s", ctr.lock.ID(), ctr.ID(), ctr.Name())
 
        defer func() {
                if retErr != nil {
@@ -774,6 +774,9 @@ func (r *Runtime) removeContainer(ctx context.Context, c *Container, force, remo
                } else {
                        logrus.Errorf("Free container lock: %v", err)
                }
+               logrus.Errorf("xxdebug Free container lock failed, %d for container %s name: %s err: %v", c.lock.ID(), c.ID(), c.Name(), err)
+       } else {
+               logrus.Infof("xxdebug Free container lock success, %d for container %s name: %s", c.lock.ID(), c.ID(), c.Name())
        }
```

I counted the log items total, it is `68` only, why does it need 8192 num_locks limit ?

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.0-dev
API Version:  4.2.0-dev
Go Version:   go1.18.1
Git Commit:   c379014ee4e57dc19669ae92f45f8e4c0814295b-dirty
Built:        Wed May 11 23:08:15 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.0-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpuUtilization:
    idlePercent: 96.93
    systemPercent: 0.94
    userPercent: 2.13
  cpus: 20
  distribution:
    distribution: arch
    version: unknown
  eventLogger: file
  hostname: wudeng
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.17.5-arch1-2
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 14855860224
  memTotal: 33387909120
  networkBackend: cni
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.4.5-1
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.2.0-1
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 17179865088
  swapTotal: 17179865088
  uptime: 23m 10.17s
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  hub.k8s.lan:
    Blocked: false
    Insecure: true
    Location: hub.k8s.lan
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: hub.k8s.lan
    PullFromMirror: ""
  search:
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 36
    paused: 0
    running: 21
    stopped: 15
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 178534772736
  graphRootUsed: 136645885952
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 63
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.2.0-dev
  Built: 1652281695
  BuiltTime: Wed May 11 23:08:15 2022
  GitCommit: c379014ee4e57dc19669ae92f45f8e4c0814295b-dirty
  GoVersion: go1.18.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0-dev

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
build from main branch
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I use nomad podman driver to create containers, which maybe concurrent request libpod rest api.

**Comment by Luap99** [comment]
@mheon PTAL

**Comment by Luap99** [comment]
If you reboot it should clear all locks (maybe you could also try podman system renumber?)

Also note that not only containers have locks, pods and volumes also use them, so be sure to check them as well.

**Comment by ttys3** [comment]
I use `num_locks = 8192` now , currently it works fine.

```
sudo podman ps | wc -l
21
```

**Comment by rhatdan** [comment]
Can we close this issue?

**Comment by banool** [comment]
I'm hitting this issue also, similar thing where the actual number of containers I have is very small:
```
$ podman container ls | wc -l
17
$ sudo podman container ls | wc -l
1
```

I set num_locks to a 8192 for now but will report in if the issue appears again.

In my use case I'm creating a container every few seconds with `podman run`, but as you can see above, they don't persist. Calling `podman system renumber` doesn't help. I am going to try running with the `--rm` flag to see if it helps.

**Comment by mheon** [comment]
Any chance you're leaking volumes? `podman volume ls` would show them

**Comment by ttys3** [comment]
@mheon  I checked volume, yes, it is leaking.  so this is why "allocation failed; exceeded num_lock" happend.

```
sudo podman volume ls | wc -l
6617
```

that's why 4096 is not enough.

but here there must be other problems.

if a container got removed, the volume should removed to.

because I have no explicit created volume using `sudo podman volume create`

like I previous menthioned:
> I do not have pods. only containers + volumes
> the max volumes num of all the containers is 11

I have 22 running containers, total containers (including dead) is 37:

so the lock num should be max to (11+1)*37=444

so the problem is, why there's so many volume leaking ?

**Comment by mheon** [comment]
The containers in question are set to autoremove, right? Autoremove via CLI should be removing volumes (had to check the code, but it's definitely set to remove dependent volumes); I suppose it's possible that autoremove via API might not be doing so? Any chance you can verify that volumes only leak via API?

**Comment by ttys3** [comment]
no. all the container is created via libpod REST api.  

after `sudo podman volume prune`, now the volumes only have 12:

```
❯ sudo podman volume ls | wc -l
12
```

so there's 6605 volumes leaking.

I checked that only have 10+ dead containers, so it can not leak so much volume.

The leaking volume must be taken a rather long time to reach this situation.
