### ISSUE TITLE
network namespace issue when used with Gitlab runner

### ISSUE THREAD

**Issue by imperialguy** [containers/podman#14192]
### Discussed in https://github.com/containers/podman/discussions/14186

<div type='discussions-op-text'>

<sup>Originally posted by **imperialguy** May 10, 2022</sup>
Using podman 3.4 on rhel8

**Scenario 1**
I have a shell script (let's call it `prepare.sh`) with just the following line in it:

`podman run -d docker.io/library/alpine:latest`

The above script is called by: a.) shell; b.) a Gitlab runner ([example](https://docs.gitlab.com/runner/executors/custom_examples/lxd.html#prepare)) as well. And it works perfectly fine in both cases.

**Scenario 2**
I make the following minor change:

`podman run -d --entrypoint /sbin/init docker.io/library/alpine:latest`

or 

`podman run -d -it docker.io/library/alpine:latest`

In other words, the above two modified commands are calling for a perpetual running of the container.

Now, when the above script is called by a.) local shell - it works perfectly fine; b.) But, when it is called by a Gitlab runner, and then when the Gitlab runner does execute that `prepare.sh` script, the following happens:

```
ERRO[0000] error joining network namespace for container f62f7b061205dce066156cf4ea90f3a90ab417b45cf8b3a5f745ffd6fca13fe7: error retrieving network namespace at /tmp/custom-executor886608394/podman-run-1001/netns/cni-e606bcb7-7156-feeb-0866-15415ebab091: failed to Statfs "/tmp/custom-executor886608394/podman-run-1001/netns/cni-e606bcb7-7156-feeb-0866-15415ebab091": no such file or directory
```

The problem, I think is, for some reason when the same script is called by the Gitlab runner, podman is looking for a network namespace inside a different folder. 

So, in the above case, it's looking for a network namespace inside `/tmp/custom-executor886608394/podman-run-1001/netns` instead of  just`/tmp/podman-run-1001/netns` which is the default location for that user.

Also, both the Gitlab runner and manual execution are using the same user.

Not sure if I can really blame it on Gitlab runner, because it ran **Scenario 1** without any hiccups. The only modification I made in **Scenario 2** is the addition of `--entrypoint` or `-it` flags, and all of a sudden it leads to the network namespace error i.e., only when called by the Gitlab runner.

Any ideas/thoughts?</div>

**Comment by rhatdan** [comment]
@Luap99 PTAL

**Comment by Luap99** [comment]
If it is using paths under /tmp then already something is not properly set up. Please run `podman syetem reset` and use a proper login session (do not change the user with su). If you run `podman info` the runroot should be under `/run/user/$UID/containers`

I have no idea what the gitlab runner script is doing but it looks like it is messing around with the TMPDIR.  `/tmp/podman-run-1001` should be the correct path, no idea where the `/tmp/custom-executor886608394/podman-run-1001/netns` comes from.

I also do not see how your changes to the podman run command would affect any of this.

**Comment by rhatdan** [comment]
Could gitlab be setting XDG_RUNTIME_DIR?

**Comment by imperialguy** [comment]
> Could gitlab be setting XDG_RUNTIME_DIR?

It's entirely possible. Not sure about the inner workings of Gitlab runner. If that's the case, is there a workaround for this issue? 

I opened the same issue in Gitlab forums as well [here](https://forum.gitlab.com/t/gitlab-runner-custom-renders-podman-to-look-in-the-wrong-network-namespace/69477). No response from them yet.


> I also do not see how your changes to the podman run command would affect any of this.

Well, it's not exactly that the run itself is failing. Coz, the run command finishes the execution and also provides us with the container id. But, that resulting container cannot join a network namespace. So, if you execute (say) `podman ps -a` or `podman exec -it <ctr_id> bash` or any podman command for that matter, then it throws that network namespace error first.

Below is the `podman info` output. As you can see, even in the output of this command, the network namespace problem of a container (that was spun up using Gitalb runner) is being spit out first, and then it spits out the rest of the podman info part. 

```
[testuser@testmachine ~]$ podman info
ERRO[0000] error joining network namespace for container 9515c12a3695834cd94c9c55d33fbc1e7e7a5cc000f9611cbe8e244f44babba2: error retrieving network namespace at /tmp/custom-executor3457174436/podman-run-1001/netns/cni-1dc351e8-ee7c-e09c-02a6-becb06028b17: failed to Statfs "/tmp/custom-executor3457174436/podman-run-1001/netns/cni-1dc351e8-ee7c-e09c-02a6-becb06028b17": no such file or directory

host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.32-1.module+el8.5.0+13852+150547f7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.32, commit: 4b12bce835c3f8acc006a43620dd955a6a73bae0'
  cpus: 2
  distribution:
    distribution: '"rhel"'
    version: "8.5"
  eventLogger: file
  hostname: **redacted**
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 4.18.0-240.22.1.el8_3.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 2527010816
  memTotal: 8147472384
  ociRuntime:
    name: runc
    package: runc-1.0.3-1.module+el8.5.0+13556+7f055e70.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.3
      spec: 1.0.2-dev
      go: go1.16.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /tmp/podman-run-1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.5.0+12582+56d94c81.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 3516133376
  swapTotal: 3644846080
  uptime: 3194h 42m 37.34s (Approximately 133.08 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/testuser/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.8-1.module+el8.5.0+13754+92ec836b.x86_64
      Version: |-
        fusermount3 version: 3.2.1
        fuse-overlayfs: version 1.8
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/testuser/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /tmp/podman-run-1001/containers
  volumePath: /home/testuser/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 1642068949
  BuiltTime: Thu Jan 13 05:15:49 2022
  GitCommit: ""
  GoVersion: go1.16.7
  OsArch: linux/amd64
  Version: 3.4.2
```

**Comment by imperialguy** [comment]
> Please run podman syetem reset and use a proper login session (do not change the user with su). 

This seems to have done the trick. The issue was with the runRoot being set to /tmp dir due to improper login session. After the reset, it went back to /run path. 

Anyways, this whole thing at the very least has revealed that Gitlab runner is tampering with the /tmp dir, but that's something I will deal with Gitlab separately in their forums.

From `podman` perspective, I think this issue can be closed now. Thanks for your help.
