### ISSUE TITLE
nothing provides libsubid.so.3()(64bit) needed by podman-2:4.0.2-6

### ISSUE THREAD

**Issue by sebrandon1** [containers/podman#14202]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Using `ubi8:latest` as my base image, I'm attempting to run `yum install podman` and it fails with: 

```
Step 2/16 : RUN yum install -y wget make hostname iproute iputils openssh openssh-clients podman psmisc
 ---> Running in 185a9a208f29
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Red Hat Universal Base Image 8 (RPMs) - BaseOS  2.0 MB/s | 780 kB     00:00    
Red Hat Universal Base Image 8 (RPMs) - AppStre  12 MB/s | 2.7 MB     00:00    
Red Hat Universal Base Image 8 (RPMs) - CodeRea  71 kB/s |  15 kB     00:00    
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Error: 
 Problem: conflicting requests
  - nothing provides libsubid.so.3()(64bit) needed by podman-2:4.0.2-6.module+el8.6.0+14877+f643d2d6.x86_64
The command '/bin/sh -c yum install -y wget make hostname iproute iputils openssh openssh-clients podman psmisc' returned a non-zero code: 1
```

**Steps to reproduce the issue:**

1. Use ubi8:latest as base image.

2. Attempt to install podman using `yum install`

3.

**Describe the results you received:**

Fails with error: `nothing provides libsubid.so.3()(64bit) needed by podman-2:4.0.2-6.module+el8.6.0+14877+f643d2d6.x86_64`

**Describe the results you expected:**

Expect it to install podman package as usual.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Failing run from Github Actions: https://github.com/test-network-function/cnf-certification-test-partner/runs/6393280162?check_suite_focus=true

**Comment by rhatdan** [comment]
@jnovy PTAL
@fatherlinux PTAL

**Comment by baude** [comment]
this really should be written up in bugzilla ...

**Comment by vrothberg** [comment]
> this really should be written up in bugzilla ...

I concur.  The issue is unrelated to Podman.

**Comment by sebrandon1** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2084179
