### ISSUE TITLE
v4.1.0 static binary is windows not linux

### ISSUE THREAD

**Issue by gmarcy** [containers/podman#14201]
### Discussed in https://github.com/containers/podman/discussions/14200

<div type='discussions-op-text'>

<sup>Originally posted by **gmarcy** May 11, 2022</sup>
```
# file v4.*/podman-remote-static
v4.0.2/podman-remote-static: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, BuildID[sha1]=b604c7916365eac339ca59b169b1c252d35f53d5, for GNU/Linux 3.2.0, not stripped, too many notes (256)
v4.1.0/podman-remote-static: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```
</div>

**Comment by gbraad** [comment]
Which steps did you take to determine this?
Is this from what you found in a download folder?

I do not observe an issue when using `make cross` and `make podman-remote-windows`.

**Comment by gmarcy** [comment]
downloaded the release artifact
```
wget https://github.com/containers/podman/releases/download/v4.1.0/podman-remote-static.tar.gz
```

**Comment by Luap99** [comment]
@mheon PTAL I think we had the same problem before?

**Comment by randombenj** [comment]
I encountered the same problem, and I get https://github.com/containers/podman/issues/13557 when using 4.0.2 which is the latest Linux static binary. So 4.X is not really usable for me on linux :) 
4.X has some really great features! But it is not entirely clear how one should install it, as the repos in https://podman.io/getting-started/installation still only provide 3.X versions and the static binaries seem to be broken. Is there any official 4.X installation guide?

**Comment by rhatdan** [comment]
@mheon Can you force a fix up to github?
