### ISSUE TITLE
podman machine init fails on Intel Macbook Pro with Error: downloading VM

### ISSUE THREAD

**Issue by arwinters** [containers/podman#14210]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. brew install podman

2. podman init machine

**Describe the results you received:**
```
Error: downloading VM image https://fedorapeople.org/groups/podman/next-devel/builds/36.20220511.dev.0/x86_64/fedora-coreos-36.20220511.dev.0-qemu.x86_64.qcow2.xz: 404 Not Found
```

**Describe the results you expected:**
Expected to init a new virtual machine

**Additional information you deem important (e.g. issue happens only occasionally):**
I checked the Fedora url, and it is not reachable. Seems the builds are completely removed.

**Output of `podman --version`:**

```
podman version 4.1.0
```

**Output of `podman version`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.1.0/libpod/_ping": dial unix ///var/folders/gs/zhlk6h152dv48vd4yy5nlvw00000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```

**Output of `podman info --debug`:**

```
same output ad podman version.
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman: stable 4.1.0 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/usr/local/Cellar/podman/4.1.0 (174 files, 47.7MB) *
  Poured from bottle on 2022-05-12 at 02:22:52
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

```
Yes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
MacOS Montery version 12.3.1
```

**Workarround for development or testing environment**

Add parameter --image-path
```
podman machine init --image-path=https://fedorapeople.org/groups/podman/testing/builds/36.20220511.dev.0/x86_64/fedora-coreos-36.20220511.dev.0-qemu.x86_64.qcow2.xz

Downloading VM image: fedora-coreos-36.20220511.dev.0-qemu.x86_64.qcow2.xz: done  
Extracting compressed file
Image resized.
Machine init complete
To start your machine run:

        podman machine start
```

**Comment by Luap99** [comment]
@baude PTAL

**Comment by ITD27M01** [comment]
For some reason podman 4.1.0 ignores image-path keyword:

```
> podman machine init --image-path=stable
Error: downloading VM image https://fedorapeople.org/groups/podman/next-devel/builds/36.20220511.dev.0/x86_64/fedora-coreos-36.20220511.dev.0-qemu.x86_64.qcow2.xz: 404 Not Found
```

**Comment by praveenkumar** [comment]
As a workaround something can be used
```
$ curl -L -O https://builds.coreos.fedoraproject.org/prod/streams/next/builds/36.20220507.1.0/x86_64/fedora-coreos-36.20220507.1.0-qemu.x86_64.qcow2.xz 
$ podman machine init --image-path=fedora-coreos-36.20220507.1.0-qemu.x86_64.qcow2.xz 
```

**Comment by outadoc** [comment]
Worked around by going to the CoreOS download page, finding the URL for the QEMU image in my architecture, and passing that to `podman machine init`.

e.g. for M1 Macs:

```sh
podman machine init --image-path=https://builds.coreos.fedoraproject.org/prod/streams/testing/builds/36.20220505.2.0/aarch64/fedora-coreos-36.20220505.2.0-qemu.aarch64.qcow2.xz
```

**Comment by vladdoster** [comment]
Should be ```https://fedorapeople.org/groups/podman/testing/builds/36.20220511.dev.0/x86_64/fedora-coreos-36.20220511.dev.0-qemu.x86_64.qcow2.xz```
