### ISSUE TITLE
Enhancement: Podman .pkg for macOS (tracking purpose)

### ISSUE THREAD

**Issue by gbraad** [containers/podman#14225]
*This is an issue that exists for tracking purpose and follow-up discussion.*

We have been working on a basic installer for macOS that takes care of the installation of the `podman`-remote client on macOS and prepare the system for use with `podman machine`.

For the `podman machine` functionality you currently have to rely on manual steps to install Qemu rom brew. Ideally we want to provide a `brew`-less `qemu` binary.

~~The initial work for this exists in https://github.com/containers-contribs/podman-installer. After completion of the `brew`-less `qemu` binary we will propose this for inclusion as a `contrib`.~~

----

So far @anjannath was able to build most of the dependencies of qemu and `qemu` itself manually, but 3 dependencies were a bit complicated to build: `gnutls`, `libssh`, `libncurses` and still need to find the exact build steps for these.

haven't made progress after this.

initial manual build notes are at: https://gist.github.com/anjannath/cea4dab84e375a57364bf55df9ba9a15
unfinished script to automated the steps at: https://github.com/containers-contribs/qemu-macos-build

/cc: @n1hility as discussed.

**Comment by gbraad** [comment]
@baude FYI: https://github.com/anjannath/podman/commit/e4bbf4c0fa8cdbfe550d6f64374bb12fb3c9c021

**Comment by rhatdan** [comment]
@gbraad glad to see progress being made.

**Comment by gbraad** [comment]
We have been held back by other installer related work, but this has been resolved. The pkg is currently under test and will be proposed soon.

We also have some follow up questions for virtiofs. Will deal with those next week.

**Comment by gbraad** [comment]
@rhatdan these are for testing purposes: https://github.com/containers-contribs/podman-installer/releases

**Comment by rhatdan** [comment]
When I try to install it, The mac refuses because it is not sure the app does not have malware?

**Comment by gbraad** [comment]
These packages are unsigned. This is a known issue until they can be
signed. You need to allow the installation from the preferences security
tab.

**Comment by gbraad** [comment]
@anjannath please propose as a PR to contrib

**Comment by gbraad** [comment]
We have merged the multi-arch build of gvisor:  https://github.com/containers/gvisor-tap-vsock/issues/130, and looking at the publication of a new release, however manual tests are needed.

**Comment by anjannath** [comment]
So, `qemu` is updated to 7.0.0 now, and also the PR https://github.com/containers/podman/pull/14540 uses this version along with the newly released universal binary of `gvproxy` 0.4.0

tested locally and everything is working as expected

**Comment by gbraad** [comment]
PR got merged
