### ISSUE TITLE
Improvement: provide an option to allow WSL2 to be installed with the MSI

### ISSUE THREAD

**Issue by gbraad** [containers/podman#14224]
At the moment the podman.msi, the installer for WIndows, does not enforce any prereqs. This is because the `podman`-remote client can work on its own using `connections` to deal with remote hosts. However, for the situation of using `podman machine` it relies on `WSL2`. At the moment the user is not informed about this need during the installation phase, instead the user will see this necessity as part of the `podman machine init`.

As an improvement we might wanna add a checkbox (or variable that can be passed) to enforce the installation of WSL2. This open could be a non-default checkbox, with clear description why this might be needed. This would provide a nicer experience to indicate to the user about a requirement for podman machine, and without having to request admin privileges multiple times.

----

This would need an action or so to call `dism` and setup `Microsoft-Windows-Subsystem-Linux`.

/cc: @n1hility as discussed. WDYT?

**Comment by gbraad** [comment]
Hi @hughsie, I went over the msitools docs but didn't see any hint this is possible.

**Comment by hughsie** [comment]
No idea I'm afraid, my knowledge of Wix and msitools is recent and incomplete.

**Comment by gbraad** [comment]
@hughsie, no worries. My colleague teuf (@cfergeau) already mentioned he would meet Marc André soon and might drop this.

**Comment by n1hility** [comment]
@gbraad it's a view panel, so the main UI has a set of can dialogs and flow but you can customize them to add additional Control elements so could be a checkbox.

(e.g. see https://github.com/GNOME/msitools/blob/master/data/ext/ui/WelcomeEulaDlg.wxs)

Here is an example of customizing: http://www.dizzymonkeydesign.com/blog/misc/adding-and-customizing-dlgs-in-wix-3/

**Comment by gbraad** [comment]
One of the issues with the installer is that no confirmation is given of success. Adding  a 'start after install', like opening a release notes file... while not very 'helpful' does allow to indicate something happened:

```
<CustomAction Id="OpenReleaseNotesOnExit" FileKey="ReleaseNotes" ExeCommand="" Execute="immediate" Impersonate="yes" Return="asyncNoWait" />
<Property Id="WIXUI_EXITDIALOGOPTIONALCHECKBOXTEXT" Value="Open release notes when setup exits." />
<UI>
    <Publish Dialog="ExitDialog" Control="Finish" Order="1" Event="DoAction" Value="StartAppOnExit">WIXUI_EXITDIALOGOPTIONALCHECKBOXTEXT</Publish>
</UI>
```

**Comment by n1hility** [comment]
@gbraad yes I totally agree on that. I think we have three options we could auto open:

1. Launch release notes 
2. Launch tutorial
3. Open terminal, perhaps printing a small tip segment

Any preference?

**Comment by gbraad** [comment]
Anything to indicate it ended is great. Something that can be shared with the macOS package might be good approach/consistency. But it should be suppressed for a 'quiet' install.

**Comment by n1hility** [comment]
This is blocked until the new msitools release is cut.

**Comment by n1hility** [comment]
This is in progress should be completed soon.

**Comment by gbraad** [comment]
Moving from msitools to wix.
