### ISSUE TITLE
Expose host .sock/named pipe of the podman machine through a podman command

### ISSUE THREAD

**Issue by benoitf** [containers/podman#14231]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

Today, we have a message when starting a podman machine with the path to the 'host socket'
like 
```
API forwarding listening on: $HOME/.local/share/containers/podman/machine/my-machine/podman.sock
```

But then I'm unable to find the path of this socket through a podman command

We may assume socket could be in `$HOME/.local/share/containers/podman/machine/<name-of-the-machine>` but for example on Windows we remove `podman` from the machine name for the name of the named pipe so it's making errorprone the guess on the client side.

**Steps to reproduce the issue:**

1. Start a podman machine

2. Now try with a command to get that path

For example I tried `podman machine inspect` and `podman machine list --format json` but none of these commands were reporting the socket.

**Describe the results you received:**
No command is showing that socket path

**Describe the results you expected:**

A command should expose it

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
current main branch
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

cc @n1hility

**Comment by vrothberg** [comment]
@baude @ashley-cui @jwhonce PTAL

**Comment by baude** [comment]
we are working on this ... there is no easy button here.  @benoitf wants podman to tell where the socket should go, and podman devs want podman-desktop to tell us where to put the socket .... nevertheless, we should be able to find some compromise.  currently @n1hility and @jwhonce have also been discussing.

**Comment by n1hility** [comment]
@baude I think you are referring to the machine event socket. @benoitf is talking about the Docker API Forwarding socket that we compute based on a few factors. I think that one we should just add to inspect, it's only needed after the machine is started, and is machine specific.

**Comment by benoitf** [comment]
Hello, here it's about the Host socket, not the socket for machine events. So socket can be where podman wants. We only need to know the location.

**Comment by baude** [comment]
Ah! Ok, yes ... @n1hility is that computed on the fly or saved somewhere? I can do the work ...

**Comment by benoitf** [comment]
It would be nice if that's stored in the json output of `machine list` output as well

**Comment by n1hility** [comment]
@baude cool! it's computed on the fly. On mac its just podman.sock in the machine dir:
https://github.com/containers/podman/blob/bde8dba877fe97130faf9c8bee678b9cfc23219a/pkg/machine/qemu/machine.go#L1240

On windows it's in a global location, so it prefixes podman to the machine name to try to prevent conflicts (but only if its not already starting with podman):
https://github.com/containers/podman/blob/bde8dba877fe97130faf9c8bee678b9cfc23219a/pkg/machine/wsl/machine.go#L864

There are cases where forwarding might be disabled (something else is listening, or its linux where we don't yet support it).

One other thing worth mentioning is that @benoitf does not want the global docker locations (we attempt to publish on both the global and a machine specific), he only wants the machine local one.

Ping me if you want me to test or implement anything!

-Jason
