### ISSUE TITLE
Set system wide default behavior of podman run --image-volume to one of the available options

### ISSUE THREAD

**Issue by vikas-goel** [containers/podman#14230]
/kind feature

**Description**
Podman has this nice feature to ignore the builtin image volumes using  `--image-volume, builtin-volume=bind|tmpfs|ignore`. This is handy in a hardened system. However, when using Docker Compose, this option cannot be used. It will be very useful if this option can be set in containers.conf so that it is effective by default for every container.

**Comment by vrothberg** [comment]
Thanks for reaching out, @vikas-goel!

The proposal sounds good to me. @rhatdan @baude WDYT?

**Comment by rhatdan** [comment]
I agree.

**Comment by vrothberg** [comment]
@vikas-goel, are you interested in opening a PR?

**Comment by rhatdan** [comment]
No dea why this was closed automatically.  Opened a PR for common, If @vikas-goel is interested in plugging this into Podman, go for it, once the common patch merges.
