### ISSUE TITLE
tmpfs designation truncates files to 4096 bytes

### ISSUE THREAD

**Issue by bridgesense** [containers/podman#14243]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Any files that are altered during operation of the box are truncated to 4096 bytes.

**Steps to reproduce the issue:**

1. run this [script](https://github.com/bridgesense/lampready/blob/master/fedora-36-test) with 'bash box up' from a Fedora 36 workstation

**Describe the results you received:**

This [script](https://github.com/bridgesense/lampready/blob/master/fedora-36-test) installs several packages from the RHEL repo using the ubi8-init image.  I've clipped a few of the packages not available to other distros in this version of the script.  

On Fedora 36, all files in /var/lib/rpm are truncated to 4096 bytes, which corrupts the rpm database.   Many of the configuration files like /etc/httpd/conf/httpd.conf have also been clipped to 4096 bytes.

**Describe the results you expected:**

The [original script](https://github.com/bridgesense/lampready/blob/master/box) runs without any issues on a RHEL 8 workstation.  On a Fedora 36 workstation, any files added or altered are truncated to 4096 -- regardless of ulimit configurations.

I'm expecting there are some stock configuration items on my Fedora 36 that need to be altered to get the newer version of podman working optimally under this environment (and others).  I just need a direction to investigate in?

The RHEL development is traveling through some rough kernels atm, which have rendered most of my workstations inoperable, otherwise I wouldn't be  trying to scope this out under Fedora.

**Additional information you deem important (e.g. issue happens only occasionally):**

My apologies for including such a bloated script as part of the question here.  At it's core, I'm just waking up an instance of the ubi8-init image and setting up a basic web server.

I'm not interested in debugging the [script](https://github.com/bridgesense/lampready/blob/master/fedora-36-test).  This version is no where close to being completed yet.  I only include it as a reference to the podman run parameters mainly between lines 616 - 635.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.3
API Version:  4.0.3
Go Version:   go1.18
Built:        Fri Apr  1 11:21:54 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.3
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpus: 4
  distribution:
    distribution: fedora
    variant: workstation
    version: "36"
  eventLogger: journald
  hostname: fedora
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.17.6-300.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 21674680320
  memTotal: 33281581056
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.4-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.4
      commit: 6521fcc5806f20f6187eb933f9f45130c86da230
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 1h 34m 39.06s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/francis/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/francis/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /tmp
  imageStore:
    number: 31
  runRoot: /run/user/1000/containers
  volumePath: /home/francis/.local/share/containers/storage/volumes
version:
  APIVersion: 4.0.3
  Built: 1648837314
  BuiltTime: Fri Apr  1 11:21:54 2022
  GitCommit: ""
  GoVersion: go1.18
  OsArch: linux/amd64
  Version: 4.0.3

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.0.3-1.fc36.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This script runs fine on RHEL 8 using the following installed tools:
```
dnf module install container-tools
```

Having an issue on a Fedora 36 workstation with the following installed tools:
```
buildah conmon container-selinux containernetworking-plugins containers-common criu crun fuse-overlayfs libslirp podman python3-podman runc skopeo slirp4netns toolbox udica
```

**Comment by bridgesense** [comment]
I just realized that it's all the files in the directories that are designated with --tmpfs that are getting truncated to 4096 bytes.

**Comment by rhatdan** [comment]
@giuseppe PTAL
This seems pretty bizarre and we have never heard of something like this.

**Comment by bridgesense** [comment]
**A little background:**

_Running on a T-490 with Intel® Core™ i7-10510U_

According to Red-Hat's documentation, the UBI init images are designed to work cross-platform on the same architecture.   I have a working [script](https://github.com/bridgesense/lampready/blob/master/box) here that runs on a few systems I've tested: Rhel 8, Rhel 9 and Fedora 36.

When working on a Rhel 9 or Fedora 36, both the ubi7-init and ubi8-init images truncate any files designated in a tmpfs directory to 4096 bytes.  So this must have something to do with working around kernel architecture.

**Steps to Reproduce:**

```
podman login registry.redhat.io
```

```
podman pull registry.redhat.io/ubi8/ubi-init
```

_a basic docker file example written to:_ Dockerfile.tmpfs.bug

```
FROM registry.access.redhat.com/ubi8/ubi-init
LABEL maintainer='xxxx'
LABEL description='xxxx'
LABEL io.k8s.display-name='xxx'
```

```
podman build -t "tmpfs.bug:private" -f Dockerfile.tmpfs.bug
```

```
podman run -d --hostname tmpfs.bug --name tmpfs.bug --tmpfs /var/lib/rpm "localhost/tmpfs.bug:private"
```

```
podman generate systemd --name tmpfs.bug --new > "$HOME/.config/systemd/user/container-tmpfs.bug.service"
```

```
systemctl --user daemon-reload
```

```
systemctl --user start "container-tmpfs.bug"
```

```
podman exec -it "tmpfs.bug" /bin/bash
```

```
ls -l /var/lib/rpm
```

_All the files in the tmpfs designation are truncated:_

![image of truncation](https://i.imgur.com/B6P4FsE.png)

**Comment by rhatdan** [comment]
@nalind any ideas?

**Comment by nalind** [comment]
At first glance, crun's handling of the "tmpcopyup" option has some bugs in its `copy_from_fd_to_fd()` function, and it's being called incorrectly by `copy_recursive_fd_to_fd()`.
