### ISSUE TITLE
podman events --filter type= or event= not validated

### ISSUE THREAD

**Issue by Luap99** [containers/podman#14269]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Just putting it here so it is not forgotten.
`podman events --filter type=` or `event=` do not validate the input.

I noticed this because the shell completion provides incorrect suggestions.

**Steps to reproduce the issue:**

1. `podman events --filter type=abc`

2. `podman events --filter event=abc`

3.

**Describe the results you received:**
no error and no events since they will never match the bogus filter. 

**Describe the results you expected:**
should error

**Output of `podman version`:**

latest main

**Comment by vrothberg** [comment]
Note that it's compatible with Docker (which does not error out either).  Filters keys are validated but values are not.  I do not fully understand the reasoning for it but let's explore the reasoning before changing.

**Comment by rhatdan** [comment]
@Luap99 @vrothberg is this still an issue?

**Comment by vrothberg** [comment]
Requires more investigation.  As mentioned above, Docker doesn't validate values either.

**Comment by Luap99** [comment]
I am totally fine with closing this, so far no user has complained and I only noticed this in tests with the shell completion.
