### ISSUE TITLE
Outdated documentation for podman networking rootless

### ISSUE THREAD

**Issue by sebastien-coavoux** [containers/podman#14279]
Hi folks, 

I was advised to report an issue here from the Kubernetes slack (crio channel) .
A couple of document / article I found about rootless networking led me to think that it was compulsory to use slirp4netns when doing rootless podman .

For example : 
- "[without root privileges, network association is not allowed](https://podman.io/getting-started/network#rootless-networking)"
-  "[networking uses slirp4netns by default](https://github.com/containers/podman/blob/main/docs/tutorials/basic_networking.md#differences-between-rootful-and-rootless-container-networking)"
-  "[all 'podman network' commands are for rootfull containers only.](https://www.redhat.com/sysadmin/container-networking-podman)"

On my side , my "deploy" user (created for deploy purposes :sunglasses:) is able to do so, or at least I have right now pod running in a network named podman with that user that "works". Working meaning : I can ping outside and ping other containers in the network (dns plugin).
When checking the interface of a container, it uses a veth but on eth0, my primary interface (I previously removed podman network in my root user and created it in my deploy user)

You can confirm me that I am in the good and it's just a matter of updating the doc ? :slightly_smiling_face:

**Comment by vrothberg** [comment]
Thank you for opening the issue, @sebastien-coavoux!

@flouthoc @Luap99 PTAL

**Comment by Luap99** [comment]
The blog you link if from 2019, keep in mind the podman is developed quickly so if you find older documents describing limitations they may no longer apply.

https://github.com/containers/podman/blob/main/docs/tutorials/basic_networking.md mentions that you can also use networks as rootless. This doesn't change the fact the slirp4netns is still the default and even if you use the custom network it still requires slirp4netns to provide them with internet connectivity.

The podman.io network guide definitely outdated and must be fixed. I think replacing it with the basic_networking.md tutorial from this repo would be better.
