### ISSUE TITLE
apt-get reports wrong file size for podman_3.4.2-1_amd64.deb in provo-mirror.opensuse.org

### ISSUE THREAD

**Issue by rigelmadraswalla** [containers/podman#14278]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm unable to install Podman from Kubic repo on Ubuntu 20.04 LTS. I've tried on multiple Ubuntu machines many times today, but I get the same error each time.

**Steps to reproduce the issue:**

1. Run installation commands from Podman docs
```
echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
curl -L "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key" | sudo apt-key add -
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install podman
```

**Describe the results you received:**
Podman installation fails with error:
```
Err:1 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  podman 100:3.4.2-1
  File has unexpected size (17679080 != 17706544). Mirror sync in progress? [IP: 91.193.113.70 443]
  Hashes of expected file:
   - SHA256:4eb9b58413f602cf18ec21a742acd99ae10e71df467e7b9a63c3b1f7e8229f16
   - SHA1:cf1fefe5c85321fe9b562339a79494c9eda9dd60 [weak]
   - MD5Sum:58fa232055dff2700aa55e13c7932536 [weak]
   - Filesize:17706544 [weak]
E: Failed to fetch https://provo-mirror.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/amd64/podman_3.4.2-1_amd64.deb  File has unexpected size (17679080 != 17706544). Mirror sync in progress? [IP: 91.193.113.70 443]
   Hashes of expected file:
    - SHA256:4eb9b58413f602cf18ec21a742acd99ae10e71df467e7b9a63c3b1f7e8229f16
    - SHA1:cf1fefe5c85321fe9b562339a79494c9eda9dd60 [weak]
    - MD5Sum:58fa232055dff2700aa55e13c7932536 [weak]
    - Filesize:17706544 [weak]
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
I've tried on multiple Ubuntu machines many times today, but I get the same error each time. I have found a similar issue with Opensuse hosted repo recently, but none regarding podman: https://github.com/cri-o/cri-o/issues/5802 

**Output of `podman version`:**
N/A - podman cannot be installed

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**
```
user@user-dev:~$ apt list podman
Listing... Done
podman/unknown 100:3.4.2-1 amd64
podman/unknown 100:3.4.2-1 arm64
podman/unknown 100:3.4.2-1 armhf
podman/unknown 100:3.4.2-1 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No - Cannot install podman

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Device environment: 
``` 
Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-40-generic x86_64)
```

**Comment by jyhyvari** [comment]
I can verify this one too, I'm having exactly the same issue with same hashes and file sizes. Cannot proceed with the installation due to security risks.

**Comment by al-cheb** [comment]
We have the same issue - https://github.visualstudio.com/virtual-environments/_build/results?buildId=125926&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=5431112d-2b61-5a5f-7042-ef698f761043

```
==> azure-arm: E: Failed to fetch https://provo-mirror.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/amd64/podman_3.4.2-1_amd64.deb  File has unexpected size (17679080 != 17706544). Mirror sync in progress? [IP: 91.193.113.70 443]
==> azure-arm:    Hashes of expected file:
==> azure-arm:     - SHA256:4eb9b58413f602cf18ec21a742acd99ae10e71df467e7b9a63c3b1f7e8229f16
==> azure-arm:     - SHA1:cf1fefe5c85321fe9b562339a79494c9eda9dd60 [weak]
==> azure-arm:     - MD5Sum:58fa232055dff2700aa55e13c7932536 [weak]
==> azure-arm:     - Filesize:17706544 [weak]
==> azure-arm: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
    azure-arm: [registries.search]
```

**Comment by al-cheb** [comment]
@lsm5, Could you please take a look?

**Comment by ramesp71** [comment]
I'm having the same issue:  
==> azure-arm: E: Failed to fetch https://provo-mirror.opensuse.org/repositories                            /devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/amd64/podman_3.4.2-1_amd64.de                            b  File has unexpected size (17679080 != 17706544). Mirror sync in progress? [IP                            : 91.193.113.70 443]
==> azure-arm:    Hashes of expected file:
==> azure-arm:     - SHA256:4eb9b58413f602cf18ec21a742acd99ae10e71df467e7b9a63c3                            b1f7e8229f16
==> azure-arm:     - SHA1:cf1fefe5c85321fe9b562339a79494c9eda9dd60 [weak]
==> azure-arm:     - MD5Sum:58fa232055dff2700aa55e13c7932536 [weak]
==> azure-arm:     - Filesize:17706544 [weak]
==> azure-arm: E: Unable to fetch some archives, maybe run apt-get update or try                             with --fix-missing?

**Comment by srd424** [comment]
If anyone wants the beginnings of an insecure bodgy script to manually download the debs, try:

```
#! /bin/bash -x

baseurl=http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/amd64/
idxfile=`mktemp`
wget -O $idxfile $baseurl

getpkg () {
        local pkg=$1
        grep $pkg_*.deb $idxfile | sed -re 's/^.*href="([^"]*.deb)".*$/\1/'
}

tmpdir=`mktemp -d`
pkglist="podman catatonit conmon containers-common podman-plugins podman-machine-cni criu crun"

for p in $pkglist; do
        pkgname=$(getpkg $p)
        wget -O $tmpdir/$pkgname $baseurl/$pkgname
done

echo $tmpdir

```

**Comment by srd424** [comment]
FWIW, the 22.04 repository seems to be broken too, some packages missing?

**Comment by dokuhebi** [comment]
> FWIW, the 22.04 repository seems to be broken too, some packages missing?

"NOTE: Kubic packages have been discontinued for Ubuntu 22.04 LTS. Current users of the Kubic repos for Ubuntu are highly recommended to uninstall the packages from the Kubic repos before upgrading to Ubuntu 22.04 LTS."

You should be able to just install from the Ubuntu repos if I'm reading the [installation instructions](https://podman.io/getting-started/installation#installing-on-linux) correctly.

**Comment by lsm5** [comment]
Thanks @dokuhebi.

@srd424 the 22.04 Kubic repository enablement was a mistake. That project is shared with the cri-o maintainers and they enabled 22.04 which ended up with podman getting enabled as well. For 22.04, you're way better off using ubuntu's own repos.


The hash mismatch looks like a stale /  out-of-sync mirror to me. Perhaps best to download the debs like @srd424 mentioned or try a different mirror https://mirrors.opensuse.org/list/bs.html 

I realize the presence of the podman package on that Kubic repo is causing more problems than solving. So, come Monday, I'll delete the package from there. Please download the debs from there before then.

There are also a few other options:

1. switch to 22.04 LTS
2. build from source
3. Try installing the package from another repo (either 22.04 LTS or debian experimental). The debian/ubuntu maintainer has mentioned that as a possible workaround in case packages aren't available in the default repos.
4. See: https://github.com/containers/podman/issues/13302#issuecomment-1066545852


**Proceed with caution**:
If you're feeling adventurous and would like to help out with testing, I have a wip repo at https://build.opensuse.org/project/show/devel:kubic:libcontainers:unstable which looks to be a much more maintainable option for me. I can't yet comment on if this will be maintainable long-term so I won't post about this on the official installation docs anytime soon. And if I realize this also ends up in a hard-to-maintain state, I might just get rid of it without any prior notice.

**Comment by lsm5** [comment]
> Ah, good catch, thanks :( Does anyone know what the rationale is? Unless Canonical are going upgrade podman in SRUs (seems unlikely given it seems to be in 'universe'), this is going to make it a lot harder to track the latest release :(

@srd424 the debian way of packaging was proving to be just too painful to maintain and automate. My wip repo in the last comment generates deb packages using fedora's packaging sources which should be a lot easier to maintain and update (I hope). The initial plan was to only use it for ubuntu testing in upstream CI but if anyone in the community is willing to try things out then I figured why not.

**Comment by srd424** [comment]
OK, I will bookmark these various issues, and if I ever get a sensible amount of free time I will investigate the various other options. Even the worst case of using the static binaries shouldn't be the end of the world, I doubt the shared binaries end up sharing significantly sized libraries with other processes, and with no long-running daemon memory spikes should be limited to container (re)start.

**Comment by Ap0th0cary** [comment]
Hey everyone!  I am getting the same issue on 20.04lts.  I am fairly new to this whole thing, so if anyone could give me instruction on "how to get the debs"  It would be greatly appreciated.  I can get the tar.gz from the repo by putting the url http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ in the browser but not really sure if that is what i need to do, or how to proceed from there.  Can someone help me out with the "for dummies" version of a workaround.   Thanks in advance

**Comment by lsm5** [comment]
@Ap0th0cary see https://github.com/containers/podman/issues/14278#issuecomment-1131493808 and https://github.com/containers/podman/issues/14278#issuecomment-1131743956

**Comment by lsm5** [comment]
> @lsm5 Will this be reverted in kubic for xUbuntu_18.04 as well (https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/) ?

Yes, i'm fixing that up right now. There should be a build in sometime.

**Comment by lsm5** [comment]
18.04 should be fixed now. Let me know if any issues.

**Comment by ppadashe** [comment]
@lsm5  Now I see this error when trying to install from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ 

```
sudo apt-get -y install  podman
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 podman : Depends: crun (>= 100:0.19.1-1) but it is not going to be installed
          Recommends: slirp4netns (>= 100:1.1.8-3) but it is not going to be installed
          Recommends: containernetworking-plugins (>= 100:1.0.0-1) but it is not going to be installed
          Recommends: fuse-overlayfs but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by ppadashe** [comment]
@lsm5  I think initially podman version was 3.0.1  here : https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ but you have reverted bit higher version which might be causing this dependency error above ? Can you please revert back the version which was existing earlier ?

**Comment by rachnajain-ibm** [comment]
@lsm5 

Podman install is going through now but I see following error post that on doing Podman login to image registry

```
+echo 'Login Docker Registry'
548Login Docker Registry
549+exec_cmd 'podman login --authfile=/home/travis/.docker/config.json -u iamapikey -p [secure] cp.stg.icr.io/cp'
550+CMD='podman login --authfile=/home/travis/.docker/config.json -u iamapikey -p [secure] cp.stg.icr.io/cp'
551+eval podman login --authfile=/home/travis/.docker/config.json -u iamapikey -p [secure] cp.stg.icr.io/cp
552++podman login --authfile=/home/travis/.docker/config.json -u iamapikey -p [secure] cp.stg.icr.io/cp
553WARN[0000] Error validating CNI config file /home/travis/.config/cni/net.d/87-podman.conflist: [failed to find plugin "bridge" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "portmap" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "firewall" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "tuning" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin]] 
554WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with [secure]less containers 
555Error: kernel does not support overlay fs: unable to create kernel-style whiteout: operation not permitted
556+'[' 125 -ne 0 ']'
557+echo 'Error : failed to execute the command: podman login --authfile=/home/travis/.docker/config.json -u iamapikey -p [secure] cp.stg.icr.io/cp'
558Error : failed to execute the command: podman login --authfile=/home/travis/.docker/config.json -u iamapikey -p [secure] cp.stg.icr.io/cp
541+exit 1
```
How can this be fixed?

**Comment by rachnajain-ibm** [comment]
@lsm5 

This is on 18.04

```
Operating System Details
16Distributor ID:	Ubuntu
17Description:	Ubuntu 18.04.6 LTS
18Release:	18.04
19Codename:	bionic
```
Why rootful mode is required now? 
Earlier the same code was working fine.

**Comment by rayankiy** [comment]
@lsm5 : We are also blocked by the same error reported . Can you help us to get unblocked and proceed ?
```
Login Docker Registry
538WARN[0000] Error validating CNI config file /home/travis/.config/cni/net.d/87-podman.conflist: [failed to find plugin "bridge" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "portmap" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "firewall" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "tuning" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin]] 
539WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
540Error: kernel does not support overlay fs: unable to create kernel-style whiteout: operation not permitted
541Login to registry.redhat.io
542WARN[0000] Error validating CNI config file /home/travis/.config/cni/net.d/87-podman.conflist: [failed to find plugin "bridge" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "portmap" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "firewall" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "tuning" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin]] 
543WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
544Error: kernel does not support overlay fs: unable to create kernel-style whiteout: operation not permitted
```

**Comment by lsm5** [comment]
working on it, will update here once it's done.

**Comment by lsm5** [comment]
@rachnajain-ibm @rayankiy rootless should be fixed now, please refresh your repos and try again. Thanks.

**Comment by lospringliu** [comment]
By default it does not work, we need a working default one on ubuntu 18.04
```
$ podman info || ls -l /dev/fuse
WARN[0000] Error validating CNI config file /home/travis/.config/cni/net.d/87-podman.conflist: [failed to find plugin "bridge" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "portmap" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "firewall" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "tuning" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin]] 
WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
Error: kernel does not support overlay fs: unable to create kernel-style whiteout: operation not permitted
crw-rw-rw- 1 root root 10, 229 May 25 17:23 /dev/fuse
```

**Comment by lsm5** [comment]
@lospringliu can you confirm you have:
```
$ apt list fuse-overlayfs podman
Listing... Done
fuse-overlayfs/unknown,now 100:1.5.0-2 amd64 [installed,automatic]
podman/unknown,now 100:3.4.2-4 amd64 [installed]
```

I have these on my 18.04 instance with the Kubic repo and the command you gave works for me.

**Comment by rayankiy** [comment]
@lsm5 : Still failing with 
```
WARN[0000] Error validating CNI config file /home/travis/.config/cni/net.d/87-podman.conflist: [failed to find plugin "bridge" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "portmap" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "firewall" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "tuning" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin]] 
507WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
508Error: kernel does not support overlay fs: unable to create kernel-style whiteout: operation not permitted
```

**Comment by lospringliu** [comment]
@lsm5 , actually there is no `fuse-overlayfs` yesterday, but does have now

I think there is differences when users use different mirrors

**Comment by lsm5** [comment]
@lospringliu mirror syncing may take a while I guess.

@rayankiy do you have those podman and fuse-overlayfs packages I posted in the earlier comment?

**Comment by lsm5** [comment]
@lospringliu yes, but hope that works for you though. The latest version of fuse-overlayfs needed fuse3 and restoring the archive was gonna be a lot more painful than I imagined. And I also had to build for newer ubuntu, so that's why.

**Comment by lospringliu** [comment]
understand and thanks, it works anyway with warnings

**Comment by rachnajain-ibm** [comment]
@lsm5 

It is still not working getting same error.

```
Login Docker Registry
205+exec_cmd 'podman login --authfile=/home/travis/.docker/config.json -u iamapikey -p [secure] cp.stg.icr.io/cp'
206+CMD='podman login --authfile=/home/travis/.docker/config.json -u iamapikey -p [secure] cp.stg.icr.io/cp'
207+eval podman login --authfile=/home/travis/.docker/config.json -u iamapikey -p [secure] cp.stg.icr.io/cp
208++podman login --authfile=/home/travis/.docker/config.json -u iamapikey -p [secure] cp.stg.icr.io/cp
209WARN[0000] Error validating CNI config file /home/travis/.config/cni/net.d/87-podman.conflist: [failed to find plugin "bridge" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "portmap" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "firewall" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "tuning" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin]] 
210WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with [secure]less containers 
211Error: kernel does not support overlay fs: unable to create kernel-style whiteout: operation not permitted
212+'[' 125 -ne 0 ']'
213+echo 'Error : failed to execute the command: podman login --authfile=/home/travis/.docker/config.json -u iamapikey -p [secure] cp.stg.icr.io/cp'
214Error : failed to execute the command: podman login --authfile=/home/travis/.docker/config.json -u iamapikey -p [secure] cp.stg.icr.io/cp
197+exit 1
198
```

**Comment by ppadashe** [comment]
@rachnajain-ibm  Try to install podman with  --install-recommends  option. Something like this 
```
sudo apt-get -qq install --yes --install-recommends podman
```

**Comment by rachnajain-ibm** [comment]
@lsm5 

We see issue in running below command

`podman login --authfile=${HOME}/.docker/config.json -u $DOCKER_USERNAME -p $DOCKER_API_KEY $DOCKER_REGISTRY
`
Need the flag --authfile= to save the config.json which is not working as per our requirement.
Can this be fixed at your end?

**Comment by rachnajain-ibm** [comment]
@lsm5 

With latest Podman, we see `.docker/config.json` content in the format:
```
{
	"auths": {
		"cp.stg.icr.io/cp": {
			"auth": "<removed>"
		}
	}
}
```

But in older version of Podman , this config.json was generated in the format below:

```
{
	"auths": {
		"cp.stg.icr.io": {
			"auth": "<removed>",
			"identitytoken": "<removed>"
		}
	}
}
```

This is causing failure. Can this be fixed ASAP?

**Comment by JMSamudio** [comment]
thanks @lsm5 , work for me with the 18.04 repo and install with the `--fix-missing` option

**Comment by al-cheb** [comment]
@lsm5, Looks like the mirror is broken again.
Ubuntu1804:
```
    azure-arm:   File has unexpected size (18660200 != 18684404). Mirror sync in progress? [IP: 91.193.113.70 443]
    azure-arm:   Hashes of expected file:
    azure-arm:    - SHA256:260ac686758f6ed9160b99642ce278d7b175e3f354b31c7b3076653449e53ca4
    azure-arm:    - SHA1:a46da407925b088b8e2f3ec02a83817ce9003cf0 [weak]
    azure-arm:    - MD5Sum:1e98238abb397cbd3b006906ddd9a433 [weak]
    azure-arm:    - Filesize:18684404 [weak]
    azure-arm: Get:19 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  skopeo 100:1.5.0-3 [6319 kB]
    azure-arm: Get:20 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  slirp4netns 100:1.1.8-4 [691 kB]
    azure-arm: Get:21 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  containernetworking-plugins 100:1.1.1~1 [7006 kB]
    azure-arm: Fetched 26.5 MB in 10s (2605 kB/s)
==> azure-arm: E: Failed to fetch https://provo-mirror.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/amd64/podman_3.4.2-4_amd64.deb  File has unexpected size (18660200 != 18684404). Mirror sync in progress? [IP: 91.193.113.70 443]
==> azure-arm:    Hashes of expected file:
==> azure-arm:     - SHA256:260ac686758f6ed9160b99642ce278d7b175e3f354b31c7b3076653449e53ca4
==> azure-arm:     - SHA1:a46da407925b088b8e2f3ec02a83817ce9003cf0 [weak]
==> azure-arm:     - MD5Sum:1e98238abb397cbd3b006906ddd9a433 [weak]
==> azure-arm:     - Filesize:18684404 [weak]
==> azure-arm: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing? 
```

Ubuntu2004:
```
    azure-arm: Err:22 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  podman 100:3.4.2-4
    azure-arm:   File has unexpected size (18676884 != 18659032). Mirror sync in progress? [IP: 91.193.113.70 443]
    azure-arm:   Hashes of expected file:
    azure-arm:    - SHA256:ef68bbab3752d524ec6be1b94f47a645dfc985b1ac497fc8ef7768278f560048
    azure-arm:    - SHA1:abe4b75985be6e70a1768032df4fcfc27f0f0d30 [weak]
    azure-arm:    - MD5Sum:aa95d7eb1bc9ca28edd3ef9b3a37805c [weak]
    azure-arm:    - Filesize:18659032 [weak]
    azure-arm: Get:23 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  skopeo 100:1.5.0-3 [6325 kB]
    azure-arm: Get:24 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  slirp4netns 100:1.1.8-4 [708 kB]
    azure-arm: Get:25 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  containernetworking-plugins 100:1.1.1~1 [7009 kB]
    azure-arm: Fetched 27.1 MB in 9s (2910 kB/s)
==> azure-arm: E: Failed to fetch https://provo-mirror.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/amd64/podman_3.4.2-4_amd64.deb  File has unexpected size (18676884 != 18659032). Mirror sync in progress? [IP: 91.193.113.70 443]
==> azure-arm:    Hashes of expected file:
==> azure-arm:     - SHA256:ef68bbab3752d524ec6be1b94f47a645dfc985b1ac497fc8ef7768278f560048
==> azure-arm:     - SHA1:abe4b75985be6e70a1768032df4fcfc27f0f0d30 [weak]
==> azure-arm:     - MD5Sum:aa95d7eb1bc9ca28edd3ef9b3a37805c [weak]
==> azure-arm:     - Filesize:18659032 [weak]
==> azure-arm: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by lsm5** [comment]
I'm fixing the hash mismatch issue now.

Long term I think it's best I just get https://build.opensuse.org/project/show/devel:kubic:libcontainers:unstable in good enough shape that ubuntu users can just use that one. That should make everyone happy including myself.

**Comment by lsm5** [comment]
`3.4.2-5` has just been built and should now be available. Please give it a try. Thanks.

**Comment by earlev4** [comment]
> `3.4.2-5` has just been built and should now be available. Please give it a try. Thanks.

@lsm5 - Now working. Thank you very, very much! I appreciate you.

**Comment by lsm5** [comment]
@al-cheb hi, so the new repo at https://build.opensuse.org/project/show/devel:kubic:libcontainers:unstable does seem to have packages built successfully and if everything goes well, it would be nice to use it (or a branch of it) in github actions and wherever else people need to use container tools on ubuntu 20.04, 18.04 and also debian 11. **But** we would really need some prior testing done. So, could you let me know if github actions has a workflow to determine if this repo is ready for deployment?

**Comment by srd424** [comment]
I've rather lost track of where we are with this, but the Ubuntu 20.04 and 22.04 arm64 repos seem to be broken - not sure if they're supposed to be working or not at this point!

**Comment by lsm5** [comment]
> I've rather lost track of where we are with this, but the Ubuntu 20.04 and 22.04 arm64 repos seem to be broken - not sure if they're supposed to be working or not at this point!

@srd424 Can you let me know which exact repo you are trying to use for each and also the error messages you see? Ubuntu 22.04 has packages in its default repo itself, so if you're using it in production, please use only the official Ubuntu packages.

**Comment by ambiamber** [comment]
Pardon the necro but you can install Podman 4.1.1 on Ubuntu 22.04 by using the alvistack repo.
```bash
wget https://downloadcontent.opensuse.org/repositories/home:alvistack/xUbuntu_22.04/Release.key -O alvistack_key
gpg --dearmor < alvistack_key | sudo tee /etc/apt/trusted.gpg.d/alvistack.gpg  >/dev/null
echo "deb https://downloadcontent.opensuse.org/repositories/home:alvistack/xUbuntu_22.04/ /" | sudo tee  /etc/apt/sources.list.d/alvistack.list
sudo apt update
sudo apt upgrade
sudo apt install podman python3-podman-compose 
```
