### ISSUE TITLE
podman in rootful mode containers using docker java client cant find images but in rootless mode images are found.

### ISSUE THREAD

**Issue by fuzails** [containers/podman#14270]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When running podman in rootfull mode, a container that uses the Docker Java Client API can not find any images from the docker.io registry. However in rootless mode this works as expected.

**Steps to reproduce the issue:**

1. podman machine init --cpus=4 -m=8192 --rootful=true

2. podman machine start

3. podman-compose -f podman-compose.yaml up, unfortunately the content of this yaml file and the containers used are private so cannot be supplied. but in step 4 the simplified java code that executes is provided. 

4. Sample Java code executed in the container

```
DefaultDockerClientConfig.createDefaultConfigBuilder().withDockerHost("unix:////run/user/501/podman/podman.sock")

CreateContainerCmd cmd = dockerClient
                .createContainerCmd("postgres")
                .withName("my_postgres")
```

**Describe the results you received:**
Got an exception: 

com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"No such image: ....

**Describe the results you expected:**
Expected the image to be found and the container to be created/running

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue only happens when running in rootfull mode, running in rootless mode images are found and containers created/running, verified that DNS lookups from the container work.

This may not be a bug, but as I can't find any information in the docs to suggest otherwise I am raising it as a bug.

**Output of `podman version`:**

```
podman version 4.1.0
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpuUtilization:
    idlePercent: 67.96
    systemPercent: 12.29
    userPercent: 19.76
  cpus: 4
  distribution:
    distribution: fedora
    variant: coreos
    version: "36"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.17.5-300.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 194445312
  memTotal: 8330518528
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.4-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.4
      commit: 6521fcc5806f20f6187eb933f9f45130c86da230
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 1h 15m 5.23s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 9
    paused: 0
    running: 5
    stopped: 4
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 106825756672
  graphRootUsed: 6014754816
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 7
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.1.0
  Built: 1651853754
  BuiltTime: Fri May  6 18:15:54 2022
  GitCommit: ""
  GoVersion: go1.18
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.1.0-1.fc36.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes
**Additional environment details (AWS, VirtualBox, physical, etc.):**
Intel Mac OSX installed via brew

**Comment by mheon** [comment]
Does pulling images from the Podman CLI work? Is it just a few images that fail, or all of them?

**Comment by Luap99** [comment]
> withDockerHost("unix:////run/user/501/podman/podman.sock")

Do you bind mount the socket into the container? This path is only for rootless. As root you would have to use the rootful socket.

**Comment by fuzails** [comment]
> Does pulling images from the Podman CLI work? Is it just a few images that fail, or all of them?

Yep pulling images from the CLI works

**Comment by fuzails** [comment]
> > withDockerHost("unix:////run/user/501/podman/podman.sock")
> 
> Do you bind mount the socket into the container? This path is only for rootless. As root you would have to use the rootful socket.

Ah, when I go into the podman machine using podman machine ssh, I only see that socket, what is the location of the rotfull socket?

**Comment by Luap99** [comment]
`/run/podman/podman.sock` should be the rootful socket by default

**Comment by fuzails** [comment]
Thanks, that works, just saw that in another logged issue now as well. 

Closing as this is resolved.
