### ISSUE TITLE
Question: persistent state on macOS after running `podman machine init`?

### ISSUE THREAD

**Issue by cmacrae** [containers/podman#14282]
**Description**
I'm wanting to make my podman installation & configuration on macOS fully declarative.  
I wanted to know if there was any persistent state I can check to see if `podman machine init` has already been run. Perhaps a file or directory gets written to disk somewhere?

Thanks in advance!

**Comment by Luap99** [comment]
Can you just run `podman machine ls` to check if the VM is listed?

**Comment by cmacrae** [comment]
Ah, perfect!
