### ISSUE TITLE
libpod: unused auto-update event status

### ISSUE THREAD

**Issue by Luap99** [containers/podman#14283]
**Description**

While working on completion changes I noticed that we have an auto-update event status but it is unused,
https://github.com/containers/podman/pull/14272#discussion_r874924744

I cannot find any references that this was ever used so the question is do we want auto-update events or just remove this status? 

**Output of `podman version`:**

latest main

**Comment by vrothberg** [comment]
I want auto-update events.  I didn't check the git history if it has ever been used but I really want it to be used.
