### ISSUE TITLE
Unable to su as root to any other user - RHEL 6.9

### ISSUE THREAD

**Issue by sentry124** [containers/podman#14286]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When running a container, after creating a user I am unable to su to that user as root. I will simply receive an su: incorrect password. I installed syslog to see if there were any errors and I had received:

su: pam_rootok(su:auth): authentication succeeded
su: PAM audit_log_acct_message() failed: Operation not permitted

I believe the second line is due to not having audit installed, but I had seen in various other posts that auditd does not work with docker containers (I am not sure if that is also the case with podman) and was unable to get auditd to work in my container.

**Steps to reproduce the issue:**

1. Pull a RHEL 6.9 image

2. Run container "podman run -ti IMAGE_ID /bin/bash"

3. Create user "useradd usera"

4. Here I've attempted two things:
i. passwd usera -> this results in a "passwd: System error" but it appears as though /etc/shadow has changed.
ii. I map the host's /etc/shadow to the container, since I have the same users in both I'd expect that the passwords would work.

5. su to usera "su usera"

**Describe the results you received:**
su: incorrect password

**Describe the results you expected:**
Switching users to usera

**Additional information you deem important (e.g. issue happens only occasionally):**
After creating usera and saving as a new image, I was able to run the container as usera and su to both root and usera when prompted with a password. This worked when using my host's /etc/shadow mapped to the container. However, as root I was still unable to su to usera. I've attempted turning off SELinux on both the host and container, and disabling firewalls on both host and container. I attempted to bypass PAM by including "skip-authentication" at the beginning of /etc/pam.d/su. I've checked to make sure /bin/su has proper permissions. I ran both pwck and grpck to verify /etc/passwd and /etc/group. I checked to make sure usera is using /bin/bash and not /bin/nologin in /etc/passwd. I am just quite perplexed and hadn't been able to find any mentions of su as root in relation to containers, so I was curious if this is a container issue or a me issue.

**Output of `podman version`:**

```
podman version 4.0.2
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.32-1.module+el8.5.0+13852+150547f7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.32, commit: 4b12bce835c3f8acc006a43620dd955a6a73bae0'
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "8.5"
  eventLogger: file
  hostname: txvpimgr801.txt.textron.com
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-348.20.1.el8_5.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 3869286400
  memTotal: 8117874688
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.0.3-1.module+el8.5.0+13556+7f055e70.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.3
      spec: 1.0.2-dev
      go: go1.16.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.5.0+12582+56d94c81.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 5368705024
  swapTotal: 5368705024
  uptime: 7h 31m 54.25s (Approximately 0.29 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 5
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1650363392
  BuiltTime: Tue Apr 19 06:16:32 2022
  GitCommit: ""
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.0.2-6.module+el8.6.0+14877+f643d2d6.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
Thanks for reaching out, @sentry124.

The following article should answer your question: https://www.redhat.com/sysadmin/sudo-rootless-podman

Since you are using RHEL, I want to encourage to go through the Red Hat customer channels for issues in the future.  This allows for prioritizing your issues.

**Comment by vrothberg** [comment]
Apologies, @sentry124.

@rhatdan may be able to help.

**Comment by sentry124** [comment]
It appears to be an issue exclusive to RHEL 6 containers. I grabbed an ubuntu and RHEL 7.6 container and they appeared to function as expected. I am not sure if there is anything that can be done on your guys' end, but any feedback would be appreciated.

**Comment by rhatdan** [comment]
Does it work if you run in --privileged mode?

**Comment by rhatdan** [comment]
I am just trying to figure out what is blocking su.

I would now try 

--cap-add=all without --privileged.

If this does not work try with SELinux disabled.

--security-opt label=disabled

And try with SECCOMP disabled

--security-opt seccomp=unconfined

**Comment by rhatdan** [comment]
It might be

podman run --cap-add AUDIT_WRITE ...

**Comment by sentry124** [comment]
Both --cap-add=all and --cap-add AUDIT_WRITE allowed for su

**Comment by rhatdan** [comment]
This means that RHEL6 su wants to do AUDIT_WRITE or fails.  Thus add the capability and you are all set.  Newer versions ignore this error or do not attempt.
