### ISSUE TITLE
podman image scp should be allowed in the remote client

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [containers/podman#14312]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

`podman image scp connection1::$IMAGE_NAME connection2` should work with the static remote client. From what I understand of https://www.redhat.com/sysadmin/podman-transfer-container-images-without-registry this is implemented by forking two podman client, one to run `podman image save` piped into a second one running `podman image load`, so there is no reason this can't work properly with a remote client (actually two remote clients, targetting two different connections).

**Steps to reproduce the issue:**

1. Setup two connections, in my case `aarch64` and  `x86_64`.

2. Try without using "--remote", it works:

```
[root@e988f777948b /]# podman image scp x86_64::fedora aarch64::
Loaded image(s): registry.fedoraproject.org/fedora:latest
```

3. Simulate the remote client (for example, the statically linked podman-remote client), by using `--remote`, it doesn't work anymore:

```
[root@e988f777948b /]# podman --remote image scp x86_64::fedora aarch64::
Error: cannot use command "podman image scp" with the remote podman client
```

**Describe the results you received:**

Error: cannot use command "podman image scp" with the remote podman client

**Describe the results you expected:**

It should work, even with the remote client.

**Additional information you deem important (e.g. issue happens only occasionally):**

This was tried with a self compiled static podman-remote-client (4.0.3), and also with the podman found in `quay.io/podman/upstream`.

**Output of `podman version`:**

```
[root@e988f777948b /]# podman version
Client:       Podman Engine
Version:      4.2.0-dev
API Version:  4.2.0-dev
Go Version:   go1.16.15
Git Commit:   68e45555b3dfc9662ce71b6ff548b43c9ea8d50c
Built:        Mon May  9 18:23:55 2022
OS/Arch:      linux/amd64```

**Comment by cdoern** [comment]
this is in the works this week :)

**Comment by cdoern** [comment]
@rhatdan waiting on #14400 to be merged cc / @jwhonce
