### ISSUE TITLE
Make these directories adjustable through podman conf files

### ISSUE THREAD

**Issue by jahamilton12121** [containers/podman#14317]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

/tmp/containers-user-$UID
/tmp/podman-run-$UID
/tmp/run-$UID

looks like only way is to change env var $TMPDIR
here is the source:

```
func getRootlessRuntimeDir(rootlessUID int) (string, error) {
	return getRootlessRuntimeDirIsolated(
		rootlessRuntimeDirEnvironmentImplementation{
			"/proc/1/comm",
			fmt.Sprintf("/run/user/%d", rootlessUID),
			fmt.Sprintf("%s/containers-user-%d", os.TempDir(), rootlessUID),
		},
	)
}
```
**Steps to reproduce the issue:**

1. run rootless podman commands

**Describe the results you received:**
it creates unwanted files in /tmp

**Describe the results you expected:**
I want to change it to /var/tmp

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Can you clarify more what the ask here is? It's not really clear.

**Comment by Luap99** [comment]
also by default these directories should already be under XDG_RUNTIME_DIR?

**Comment by jahamilton12121** [comment]
Running rootless podman commands results in the creation of these three directories which are non-configurable
```
/tmp/containers-user-$UID
/tmp/podman-run-$UID
/tmp/run-$UID
```
I assumed by the code snippet yesterday that they could still be changed through $TMPDIR but it doesn't seem to be the case as changing that variable has no effect. Setting $XDG_RUNTIME_DIR has no effect either. 
I want to change them to be 
```
/var/tmp/containers-user-$UID
etc
```

**Comment by jahamilton12121** [comment]
Also under my user XDG_RUNTIME_DIR is set to /var/tmp.
```
su -s /bin/bash - ubuntu_w_nc -c "echo $XDG_RUNTIME_DIR"
/var/tmp
```

**Comment by Luap99** [comment]
First you have to run podman system reset because it caches the paths. You cannot change them on the fly because this will break about everything. 

Second it is important that the path is on tmpfs because podman will check for a given file to know if there was reboot. If you put this on a persistent file system this will no longer work and result in many bugs. You could work around that by deleting the directories on each boot.

**Comment by jahamilton12121** [comment]
The /tmp on our system is not on tmpfs

Also I don't think I need to do a reset because I am working with a program that dynamically builds and destroys rootless containers. I test the env variable changes by having my scripts fully remove the user and container and then making a new user and loading a new container inside of it. Running a reset inside the user won't seem to do anything, running outside the user will mess with rootful containers I have running.

**Comment by jahamilton12121** [comment]
```
:~# df -h /tmp
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda3        14G  9.5G  3.6G  73% /

```

**Comment by jahamilton12121** [comment]
okay I was able to fix it by modifying the .profile of the user before running any podman commands. 
just added this `export TMPDIR="/run/user/myuser"`

**Comment by jahamilton12121** [comment]
This moved /tmp/containers-user-$UID but the other two directories seemed to have disappeared entirely. I don't know if that is normal

/tmp/podman-run-$UID
/tmp/run-$UID

**Comment by jahamilton12121** [comment]
changing the env variable causes docker-tar files to go into /run/user as well which is not wanted. Is there anyway to get the directories I mentioned into /run/user, and docker-tar files into /var/tmp?

**Comment by jahamilton12121** [comment]
closing again sorry. Using XDG_RUNTIME_DIR instead of TMPDIR worked for above comment
