### ISSUE TITLE
podman --remote build --quiet outputs containers build's stderr ouput in client's stdout

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [containers/podman#14315]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When using a remote client, it seems that anything logged in stderr when building the container is being logged to the stdout of the client, even if --quiet was used. This result in an unuseable container image id. Note that without using a remote client, it works as expected (stderr of the container is logged in the stderr stream of the client)

**Steps to reproduce the issue:**

Tested from a `quay.io/podman/upstream` image run with privileged mode:

1. 
```
[root@b561b4a44dcf /]# mkdir /src
[root@b561b4a44dcf /]# cat >/src/Dockerfile <<END_OF_FILE
FROM quay.io/fedora/fedora
RUN echo 'some error' >&2
END_OF_FILE
[root@b561b4a44dcf /]# podman system service -t 0 &
[1] 23
```

2. When trying to build without the remote mode, it works fine:

```
[root@b561b4a44dcf /]# podman build --quiet --no-cache src | sed -e 's/^/Log from stdout: /'
some error
Log from stdout: e3979e0a57b619d9e6d2035e9fb0c4f8df7c9eed480ba93d6c23b730ef24ce43
```

3. However when trying to build with the remote mode, stdout is being corrupted by "some error" while it should not:

```
[root@b561b4a44dcf /]# podman --remote build --quiet --no-cache src | sed -e 's/^/Log from stdout: /'
Log from stdout: some error
Log from stdout: e5431e43fc7a867e33f83475f5a2fe7ab47c6747d9eef736d11d18e8b677669c
```

**Describe the results you received:**

stdout is corrupted in remote mode.

**Describe the results you expected:**

stdout should contain only the final built image id.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
[root@b561b4a44dcf /]# podman version
Client:       Podman Engine
Version:      4.2.0-dev
API Version:  4.2.0-dev
Go Version:   go1.16.15
Git Commit:   68e45555b3dfc9662ce71b6ff548b43c9ea8d50c
Built:        Mon May  9 18:23:55 2022
OS/Arch:      linux/amd64
```

**Comment by flouthoc** [comment]
@Romain-Geissler-1A Docker API suppress step errors when `quiet` is set, above PR should fix this.
