### ISSUE TITLE
aarch64 podman + qemu-user-static can't run x86_64 RHEL 9 image by default

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [containers/podman#14314]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Hi,

Right now, podman running on a aarch64 host with the package `qemu-user-static` installed can't run a RHEL 9 (or CentOS 9, or UBI 9) image by default. When you try, you get this error:

```
[rgeissler@ncearmdev002]~% podman run -t -i --rm --arch x86_64 --pull=always quay.io/centos/centos:stream9                                                                           Trying to pull quay.io/centos/centos:stream9...
Getting image source signatures
Copying blob 308c19e32648 skipped: already exists
Copying config db6c66d6fd done
Writing manifest to image destination                                                                                                                                                Storing signatures
Fatal glibc error: CPU does not support x86-64-v2
```

It's a well known problem at Red Hat: RHEL 9 now requires the ABI level x86-64-v2, and qemu by default emulates a "base" CPU. If you force qemu to update the CPU model, it works (by setting the env variable QEMU_CPU):

```
[rgeissler@ncearmdev002]~% podman run -t -i --rm --arch x86_64 --pull=always -e QEMU_CPU=max quay.io/centos/centos:stream9 uname -m
Trying to pull quay.io/centos/centos:stream9...
Getting image source signatures
Copying blob 308c19e32648 skipped: already exists
Copying config db6c66d6fd done
Writing manifest to image destination
Storing signatures
x86_64
```

Someone already asked Fedora folks to change the default CPU model to match at least the ABI x86-64-v2, but it was refused last time as Fedora maintainers didn't want to change the default behavior compared to upstream QEMU, and at that time upstream QEMU folks seemed unsure about changing this: https://bugzilla.redhat.com/show_bug.cgi?id=2080133 and https://lore.kernel.org/qemu-devel/20210607135843.196595-1-berrange@redhat.com/

So, if indeed now in 2022 the QEMU folks (and apparently some of them work in Red Hat, since you also work in Red Hat, maybe you can see internally between both the container and virtualization teams what's the best course of action here) still didn't find a consensus on upgrading the default x86_64 ABI, would it make sense that podman sets by default the environment variable QEMU_CPU when running on a non x86_64 host a container for the x86_64 architecture ? Thus, avoiding that this problem is met by users, and somehow hardcoded in the default podman config so it just works by default ?

**Comment by vrothberg** [comment]
`x86_64` does not exist in the open containers specification.  Instead you should use `--arch amd64`. Maybe that will work.

As for the Red Hat related questions: please go through the Red Hat customer channels (e.g., Bugzilla, Customer Portals, etc.).

**Comment by Romain-Geissler-1A** [comment]
Ok will open a Red Hat ticket then.

Note: podman accepts `x86_64` since version 4.x, it internally maps it to `amd64`. It was actually implemented after one of the ticket I have opened to support this (as docker does).

**Comment by Romain-Geissler-1A** [comment]
Internal Red Hat case opened by Amadeus: https://access.redhat.com/support/cases/#/case/03226284 (not public obviously).

**Comment by kirbyzhou** [comment]
> [rgeissler@ncearmdev002]~% podman run -t -i --rm --arch x86_64 --pull=always quay.io/centos/centos:stream9                                                                           Trying to pull quay.io/centos/centos:stream9...

Hi, can you tell me where you download qemu-user-static for aarch64-x86_64 ?
I can only find x86_64-aarch64

**Comment by kirbyzhou** [comment]
> > [rgeissler@ncearmdev002]~% podman run -t -i --rm --arch x86_64 --pull=always quay.io/centos/centos:stream9                                                                           Trying to pull quay.io/centos/centos:stream9...
> 
> Hi, can you tell me where you download qemu-user-static for aarch64-x86_64 ? I can only find x86_64-aarch64

docker run --rm --privileged alekitto/qemu-user-static --reset -p yes

**Comment by testn** [comment]
Is there a workaround for this?

**Comment by Romain-Geissler-1A** [comment]
Hi,

In my opinion (but people might disagree), the qemu project shall increase it's default level of emulated CPU features as now recent distro tend to raise the bar to x86_64-v2 rather than good old v1. However I don't know if this will ever happen.

One possible workaround on podman side is what @rhatdan suggested me in the Red Hat bugzilla (I doubt you can see it, most likely it's private to my company and Red Hat). I will copy here what he suggested, it works:

> Daniel Walsh 2022-08-16 13:22:31 UTC
> Can you try
> 
> # mkdir /etc/containers/containers.conf.d/
> # cat > /etc/containers/containers.conf.d/arch.conf << EOF
> [containers]
> env = [
>   "QEMU_CPU=max",
> ]
> EOF
> 
> # podman run --rm ubi8-micro printenv
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> TERM=xterm
> container=podman
> QEMU_CPU=max
> HOME=/root
> HOSTNAME=5c2a71a59920
> sh-5.1# 
> exit
> 
> $  podman run --rm ubi8-micro printenv
> QEMU_CPU=max
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> TERM=xterm
> container=podman
> HOME=/root
> HOSTNAME=1f2a00565f8e

Cheers,
Romain
