### ISSUE TITLE
timeout in sctp? forward expose?

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#14331]
There's a flake that seems to be having cascading flake effects. I think, but am not sure, that the problem begins with the `  podman run forward sctp protocol` test:
```
podman run forward sctp protocol
           /var/tmp/go/src/github.com/containers/podman/test/e2e/run_networking_test.go:542
         
         [BeforeEach] Podman run networking
           /var/tmp/go/src/github.com/containers/podman/test/e2e/run_networking_test.go:28
         [It] podman run forward sctp protocol
           /var/tmp/go/src/github.com/containers/podman/test/e2e/run_networking_test.go:542
         # podman [options] --log-level=info run --name=test -p 80/sctp -p 81/sctp quay.io/libpod/alpine:latest
         time="2022-05-23T11:18:18-05:00" level=info msg="/var/tmp/go/src/github.com/containers/podman/bin/podman filtering at log level info"
         time="2022-05-23T11:18:18-05:00" level=info msg="Setting parallel job count to 7"
         [AfterEach] Podman run networking
           /var/tmp/go/src/github.com/containers/podman/test/e2e/run_networking_test.go:37
         # podman [options] pod rm -fa -t 0
         # podman [options] rm -fa -t 0
         time="2022-05-23T11:20:24-05:00" level=info msg="Port reservation for SCTP is not supported"
         time="2022-05-23T11:20:24-05:00" level=info msg="Got Conmon PID as 347928"
         time="2022-05-23T11:20:24-05:00" level=info msg="Received shutdown.Stop(), terminating!" PID=347560
         c0b3e2b742ed097e53f23d3bde2379386a2c959f9c739feb573c3a1e5556f4ee
         output: c0b3e2b742ed097e53f23d3bde2379386a2c959f9c739feb573c3a1e5556f4ee
         
         

         ? Failure [126.689 seconds]
         Podman run networking
         /var/tmp/go/src/github.com/containers/podman/test/e2e/run_networking_test.go:20
           podman run forward sctp protocol [It]
           /var/tmp/go/src/github.com[/containers/podman/test/e2e/run_networking_test.go:542](https://github.com/containers/podman/blob/b7dbc505b6a7fbc14ba559acab31baf7d37f8b62/test/e2e/run_networking_test.go#L542)
         
           Timed out after 90.001s.
           Expected process to exit.  It did not.
         
           /var/tmp/go/src/github.com/containers/podman/test/utils/utils.go:368
         
           Full Stack Trace
           github.com/containers/podman/v4/test/utils.(*PodmanSession).WaitWithTimeout(0xc001b6a408, 0x5a)
           	/var/tmp/go/src/github.com/containers/podman/test/utils/utils.go:368 +0x10b
           github.com/containers/podman/v4/test/utils.(*PodmanSession).WaitWithDefaultTimeout(...)
           	/var/tmp/go/src/github.com[/containers/podman/test/utils/utils.go:363](https://github.com/containers/podman/blob/b7dbc505b6a7fbc14ba559acab31baf7d37f8b62/test/utils/utils.go#L363)
           github.com/containers/podman/v4/test/e2e.glob..func84.41()
           	/var/tmp/go/src/github.com[/containers/podman/test/e2e/run_networking_test.go:545](https://github.com/containers/podman/blob/b7dbc505b6a7fbc14ba559acab31baf7d37f8b62/test/e2e/run_networking_test.go#L545) +0x157
           github.com/containers/podman/v4/test/e2e.TestLibpod(0xc000106c00)
           	/var/tmp/go/src/github.com[/containers/podman/test/e2e/common_test.go:102](https://github.com/containers/podman/blob/b7dbc505b6a7fbc14ba559acab31baf7d37f8b62/test/e2e/common_test.go#L102) +0xc5
           testing.tRunner(0xc000106c00, 0x15e4f20)
           	/usr/lib/golang/src/testing/testing.go:1203 +0xe5
           created by testing.(*T).Run
           	/usr/lib/golang/src/testing/testing.go:1248 +0x2b3
```
When this happens, it seems to trigger flakes in ` podman run network expose host port 80 to container port ` and `podman run network expose duplicate host port results in error ` tests

I'm just going to link to the `sctp` failures here. In each of the logs below, the `sctp` failure is not alone: there are always associated `expose` failures. I don't know which causes which.

### Podman run networking [It] podman run forward sctp protocol 
* fedora-35 : int podman fedora-35 root host
  * PR #14321
    * [05-23 12:22](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5611015231504384/html/int-podman-fedora-35-root-host.log.html#t--podman-run-forward-sctp-protocol--1)
  * PR #14300
    * [05-19 17:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4955487861997568/html/int-podman-fedora-35-root-host.log.html#t--podman-run-forward-sctp-protocol--1)
  * PR #14297
    * [05-19 19:27](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6233357066436608/html/int-podman-fedora-35-root-host.log.html#t--podman-run-forward-sctp-protocol--1)
  * PR #14288
    * [05-19 09:01](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6437230574043136/html/int-podman-fedora-35-root-host.log.html#t--podman-run-forward-sctp-protocol--1)
  * PR #14258
    * [05-16 11:58](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5347076337827840/html/int-podman-fedora-35-root-host.log.html#t--podman-run-forward-sctp-protocol--1)
  * PR #14232
    * [05-13 11:50](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5673136917053440/html/int-podman-fedora-35-root-host.log.html#t--podman-run-forward-sctp-protocol--1)
    * [05-13 10:43](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4575391712018432/html/int-podman-fedora-35-root-host.log.html#t--podman-run-forward-sctp-protocol--1)
  * PR #14229
    * [05-13 14:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5735935093506048/html/int-podman-fedora-35-root-host.log.html#t--podman-run-forward-sctp-protocol--1)
    * [05-13 14:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5735935093506048/html/int-podman-fedora-35-root-host.log.html#t--podman-run-forward-sctp-protocol--2)
  * PR #14228
    * [05-16 11:03](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4758614479994880/html/int-podman-fedora-35-root-host.log.html#t--podman-run-forward-sctp-protocol--1)
  * PR #13870
    * [05-17 18:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5306351088828416/html/int-podman-fedora-35-root-host.log.html#t--podman-run-forward-sctp-protocol--1)
  * PR #13808
    * [05-13 22:01](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5615837137600512/html/int-podman-fedora-35-root-host.log.html#t--podman-run-forward-sctp-protocol--1)

**Comment by cevich** [comment]
Ya, that's within the 30-day window so the old images should still be around...

**Comment by edsantiago** [comment]
Here's a failure in just the `expose` and `hostname` tests, without `sctp`: again, [f35](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5631511352311808/html/int-podman-fedora-35-root-host.log.html#t--podman-run-network-expose-host-port-80-to-container-port--1)

**Comment by cevich** [comment]
From [the current `main`](0f5c06dac58645943469c63999931c165dba9031):
+ kernel `5.17.4-200.fc35`
+ iptables-legacy `1.8.7-13.fc35`, nftables `1.0.0-1.fc35`
+ containernetworking-plugins `1.1.0-1.fc35`

From PR #14178:
+ kernel `5.16.20-200.fc35`
+ iptables-legacy `1.8.7-13.fc35`, nftables `1:1.0.0-1.fc35`
+ containernetworking-plugins `1.1.0-1.fc35`

From the [f35](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5631511352311808/html/int-podman-fedora-35-root-host.log.html#t--podman-run-network-expose-host-port-80-to-container-port--1) Ed just posted:
+ kernel `5.17.4-200.fc35`
+ iptables `legacy-1.8.7-13.fc35`, nftables `1.0.0-1.fc35`
+ containernetworking-plugins `1.1.0-1.fc35`

**Comment by edsantiago** [comment]
This is our number one flake right now and it's happening multiple times per PR

**Comment by Luap99** [comment]
Thanks @cevich. Can I just replace the image id in cirrus.yaml and run the `get_ci_vm` script to get the old VM image?

**Comment by cevich** [comment]
> Can I just replace the image id in cirrus.yaml

Sometimes :stuck_out_tongue_winking_eye: It depends on if there were script changes associated with the image update, or not.  The safest thing to do is check out the commit that has the image you want, and use the script from there.  Also, if you just need to poke around in the VM and don't intend to execute `./contrib/cirrus/runner.sh` you can speed things up a bit by hitting `ctrl-c` when it starts to compile podman...unless of course you need a compiled podman :smiley:

**Comment by Luap99** [comment]
@edsantiago Is this fixed?

**Comment by edsantiago** [comment]
The last instance I see is on May 25, so I'll treat it as fixed. Thank you!
