### ISSUE TITLE
Mount image filesystem

### ISSUE THREAD

**Issue by lachmanfrantisek** [containers/podman#1433]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Description**

It would be nice to be able to mount the filesystem of the image with `podman mount`.

Is there some easy way to achieve this? (Now, I am doing `podman create` + `podman mount`.)

Thanks.

**Comment by mheon** [comment]
This is possible with containers/storage, though I believe the mounts will have to be read-only given that there's no container associated with them - if you want to alter the filesystem and make new images, you could have to create a container and `podman commit` after mounting and changing.

**Comment by lachmanfrantisek** [comment]
@mheon Thanks, the read-only state is what I need.

For now, `podman create`+`podman mount` is easier than building the containers-storage cli.

It would be nice to have it in `podman mount` directly. (in the future)

**Comment by rhatdan** [comment]
@nalind WDYT?

**Comment by sghosh151** [comment]
Would be nice to be able to do this inside a container. 
usage: Deploy a container scanning tool in a image - image receives API call, downloads image (ephemeral), mounts image, examines filesystems - returns result on API

**Comment by mheon** [comment]
Rootless podman inside of the container should do what you need once mounting images is implemented, especially given there's no real need to share storage between podman in the image and podman outside of the image.

**Comment by rhatdan** [comment]
Right, you can do this now by just running podman inside of container.

**Comment by baude** [comment]
should we just implement this with a container create and a mount?

**Comment by mheon** [comment]
Do we need to? I think c/storage might support mounting images already, in which case it's just wiring up a command to do the heavy lifting

**Comment by rhatdan** [comment]
@nalind How hard would this be to do?  Just mount the image layer Read/Only?

**Comment by rhatdan** [comment]
I think this could be done, fairly easily but we would need interfaces added to containers/storage to mount an image read/only with no upper container.
If someone wants to look into this it would be great.

**Comment by rhatdan** [comment]
Still no one has worked on this one for a year.  I am adding some support for mounting container storage read/only in https://github.com/containers/storage/pull/404

**Comment by kunalkushwaha** [comment]
If no one is working on this, I can work on this. 

> I think this could be done, fairly easily but we would need interfaces added to containers/storage to mount an image read/only with no upper container.

Can this be done with a dummy container config without new top layer, which will be deleted with umount?

**Comment by rhatdan** [comment]
It could be, but it would seem better to just be able to mount the image read/only.

**Comment by vrothberg** [comment]
@kunalkushwaha, are you planning to work on that?

I'm going through old issues and do some cleanups.

**Comment by kunalkushwaha** [comment]
Hi @vrothberg Yes, I started working on this now.

/assign

**Comment by rhatdan** [comment]
@kunalkushwaha I still working on this, correct?

**Comment by kunalkushwaha** [comment]
@rhatdan Yes, I am working on this. 
The https://github.com/containers/storage/pull/438 & https://github.com/containers/libpod/pull/4209 PRs to fix this issue.

Once c/storage  have `ImageMount()` interface, #4209 can be fixed.

**Comment by rhatdan** [comment]
The storage PR needs a rebase.

**Comment by rhatdan** [comment]
@ashley-cui PTAL

**Comment by rhatdan** [comment]
I have a PR up for this one. https://github.com/containers/podman/pull/6851

**Comment by baude** [comment]
this can now be done by podman
