### ISSUE TITLE
podman play --service-container : is not stopping (flake)

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#14351]
Three flakes in my PR, finally passed on the fourth try:
```
# #| FAIL: Timed out waiting for container b9180307e1fd-service to enter state running=false
```
Unfortunately, #14338 (timeout bump) did not work. Sorry @vrothberg.

### [sys] 341 podman play --service-container
  * PR #14346
    * [05-24 14:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4638046896259072/html/sys-podman-ubuntu-2110-rootless-host.log.html#t--00341)
    * [05-24 13:20](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5950318889402368/html/sys-podman-ubuntu-2110-rootless-host.log.html#t--00341)
    * [05-24 12:46](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5224984107810816/html/sys-podman-ubuntu-2110-rootless-host.log.html#t--00341)

**Comment by vrothberg** [comment]
Thanks, @edsantiago. I am going to take a look immediately.

**Comment by vrothberg** [comment]
I smell where it's coming from. Will prepare a PR in a jiffy.
