### ISSUE TITLE
tail 800 lines journald: incomplete output

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#14362]
Two flakes in one week:
```
# podman-remote [options] logs --tail 800 <CID>
...
...makes it only to 400-something, or perhaps even just zero lines
? Failure [3.295 seconds]
         Podman logs
         /var/tmp/go/src/github.com[/containers/podman/test/e2e/logs_test.go:26](https://github.com/containers/podman/blob/e874fc105c0fcfa291e256071be8b48dc4f347f8/test/e2e/logs_test.go#L26)
           tail 800 lines: journald [It]
           /var/tmp/go/src/github.com[/containers/podman/test/e2e/logs_test.go:116](https://github.com/containers/podman/blob/e874fc105c0fcfa291e256071be8b48dc4f347f8/test/e2e/logs_test.go#L116)
         
           Expected [long string] to have length 800
```

### Podman logs [It] tail 800 lines: journald 
* fedora-35 : int remote fedora-35 root host [remote]
  * PR #14272
    * [05-19 09:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4855020456771584/html/int-remote-fedora-35-root-host.log.html#t--tail-800-lines--journald--1)
    * [05-19 09:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4855020456771584/html/int-remote-fedora-35-root-host.log.html#t--tail-800-lines--journald--2)
    * [05-19 09:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4855020456771584/html/int-remote-fedora-35-root-host.log.html#t--tail-800-lines--journald--3)
* fedora-36 : int remote fedora-36 root host [remote]
  * PR #13808
    * [05-25 09:10](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5626273706803200/html/int-remote-fedora-36-root-host.log.html#t--tail-800-lines--journald--1)
    * [05-25 09:10](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5626273706803200/html/int-remote-fedora-36-root-host.log.html#t--tail-800-lines--journald--2)
    * [05-25 09:10](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5626273706803200/html/int-remote-fedora-36-root-host.log.html#t--tail-800-lines--journald--3)

**Comment by Luap99** [comment]
I think I saw this on many PRs recently.
@edsantiago Can you post the recent failures to check if it is only on remote?

**Comment by edsantiago** [comment]
Two more on 05-25, none since then (but then again, long weekend with very very few PRs)

### Podman logs [It] tail 800 lines: journald 
* fedora-35 : int podman fedora-35 root host
  * PR #14364
    * [05-25 12:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5350891510300672/html/int-podman-fedora-35-root-host.log.html#t--tail-800-lines--journald--1)
* fedora-35 : int remote fedora-35 root host [remote]
  * PR #14366
    * [05-25 15:27](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4762366268145664/html/int-remote-fedora-35-root-host.log.html#t--tail-800-lines--journald--1)
    * [05-25 15:27](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4762366268145664/html/int-remote-fedora-35-root-host.log.html#t--tail-800-lines--journald--2)
    * [05-25 15:27](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4762366268145664/html/int-remote-fedora-35-root-host.log.html#t--tail-800-lines--journald--3)

**Comment by edsantiago** [comment]
Ah yes, I should've mentioned my flake logger only captures merged PRs. Identifying flakes on in-progress PRs was an exercise I deferred "for later" (and has not happened yet).

**Comment by edsantiago** [comment]
Anyhow: the logs above show one instance on non-remote, and curiously it was a one-time-only: the remote failures are all three-time failures.

**Comment by Luap99** [comment]
Just any idea but the test never actually waits for the container to complete. It call `podman run -d ...` followed by `podman logs`.
I think it is likely that the container/conmon did not write all the output before we call logs.

Let me open a PR with an extra `podman wait` then we will see if that worked or not.
