### ISSUE TITLE
Error: error opening file (after reboot)

### ISSUE THREAD

**Issue by ocafebabe** [containers/podman#14403]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I can't execute commands on the container after a system reboot (even though the container has been started successfully by systemd and I see that the database is running correctly as well).

**Steps to reproduce the issue:**

1. start oracle container

2. reboot

3. podman exec -it oracle bash

**Describe the results you received:**

Error: error opening file `/run/user/1001/crun/90572a963eaf6fd5ce3fecdaa1ef5fa064f6b00f9888817ebab0575759c9d254/status`: No such file or directory: OCI runtime attempted to invoke a command that was not found

**Describe the results you expected:**

A shell prompt...

**Additional information you deem important (e.g. issue happens only occasionally):**

This is not an intermittent issue, it happens on every reboot. Linger is already enabled for this user.

**Output of `podman version`:**

```
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.1.0, commit: '
  cpus: 8
  distribution:
    codename: focal
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: xxxxxxxx
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
  kernel: 5.4.0-113-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 46813392896
  memTotal: 135090352128
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: ea1fe3938eefa14eb707f1d22adff4db670645d6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 2147479552
  swapTotal: 2147479552
  uptime: 52m 49.63s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/oracle/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.9.0
        fuse-overlayfs: version 1.5
        FUSE library version 3.9.0
        using FUSE kernel interface version 7.31
  graphRoot: /home/oracle/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /tmp/podman-run-1001/containers
  volumePath: /home/oracle/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 3.4.2

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 100:3.4.2-4 amd64 [installed]
podman/unknown 100:3.4.2-4 arm64
podman/unknown 100:3.4.2-4 armhf
podman/unknown 100:3.4.2-4 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

KVM

**Comment by rhatdan** [comment]
Could you try this against the latest versiom of podman 4.1?

**Comment by rhatdan** [comment]
@giuseppe any idea what is going on?  Could there be a remnant of crun that is required and removed on reboot?

**Comment by giuseppe** [comment]
is `/run` on a tmpfs?  Could you share the output of `cat /proc/self/mountinfo` ?

**Comment by Luap99** [comment]
> runRoot: /tmp/podman-run-1001/containers

Is /tmp on a tmpfs? The podman runroot should be on a tmps otherwise it cannot detect a reboot.

Also this means that you did not create a proper login session for this user (at least when you first run podman). I recommend to start from scratch, run `podman system reset` to delete the stuff. Then make sure $XDG_RUNTIME_DIR is set and points to /run/user/$UID. Now run podman info and make sure the runroot now is under /run/....

**Comment by ocafebabe** [comment]
@rhatdan I'd like to but 3.4.2 is the latest version available on the Kubic repo for Ubuntu...

@giuseppe yes, please find the output of mountinfo here: [mountinfo.txt](https://github.com/containers/podman/files/8799599/mountinfo.txt)

@Luap99 no, but /tmp is cleared on every boot (Ubuntu) so it should have the same effect. FYI I have other Ubuntu server deployments with the same podman setup and never had this problem before. I have yet to find out why this one is behaving like this...

**Comment by giuseppe** [comment]
if the runroot is configured as `runRoot: /tmp/podman-run-1001/containers` there was a problem with `/run/user/$UID` directory wasn't present when Podman created its storage.

Is `/tmp/podman-run-1001` still used if you start with a fresh storage (`podman system reset -f`)?  What is the value of `XDG_RUNTIME_DIR`?

**Comment by ocafebabe** [comment]
Strangely enough, XDG_RUNTIME_DIR isn't set at all, but I guess this is because it's a service account and that we access it using _sudo_ exclusively.

I tried `podman system reset` and indeed it seems to have fixed the issue, now I get this: `runRoot: /run/user/1001/containers`

This raises the following question: is there a proper way of using podman in rootless mode with a service account accessed with sudo?

Is `machinectl shell --uid=serviceuser` a better option than `sudo`?

**Comment by giuseppe** [comment]
`machinectl shell --uid=serviceuser` is a better option because it creates the user session, while `sudo` just changes the euid.
