### ISSUE TITLE
Podman 4.1 machine init fails when run in C:\Windows\System32

### ISSUE THREAD

**Issue by StanEgo** [containers/podman#14416]
/kind bug

**Description**

Simple setup and machine initialization results in error and some warnings.

**Steps to reproduce the issue:**

1. Download podman 4.1.0 MSI for Window.

2. Execute "podman machine init" in command shell.

**Describe the results you received:**

> Error: could not create ssh keys: exec: "C:\\Users\\stani\\.ssh\\wsl.exe": file does not exist

Looks like error is fatal, because none of other podman command are working with message "Cannot connect to Podman...".

**Describe the results you expected:**

Running podman machine.

**Output of `podman version`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: failed to parse identity "C:\\Users\\stani\\.ssh\\podman-machine-default": open C:\Users\stani\.ssh\podman-machine-default: The system cannot find the file specified.
```

**Output of `podman info --debug`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: failed to parse identity "C:\\Users\\stani\\.ssh\\podman-machine-default": open C:\Users\stani\.ssh\podman-machine-default: The system cannot find the file specified.
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
PS C:\Windows\System32>  Get-CimInstance -ClassName Win32_Product -Filter "name like 'Podman%'"

Name             Caption                   Vendor                    Version                   IdentifyingNumber
----             -------                   ------                    -------                   -----------------
Podman 4.1.0     Podman 4.1.0              Red Hat Inc.              4.1.0                     {F0C12B5B-290B-4C15-A0D…
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Comment by Luap99** [comment]
@n1hility PTAL

**Comment by Clivar** [comment]
This is caused by executing `podman machine init` in the same folder as wsl.exe (C:/windows/system32).
As a workaround you can navigate to any other folder and try again.

The problem seems to be caused by the Dir function. I provided a fix that omits the use of this function: https://github.com/containers/podman/pull/14570.

**Comment by n1hility** [comment]
good catch @Clivar , I added a comment to the PR.
