### ISSUE TITLE
auto-update: allow to use custom command when stopping container

### ISSUE THREAD

**Issue by gdesmott** [containers/podman#14413]
/kind feature

**Description**

I manually implemented a script very similar to [podman-auto-update](https://docs.podman.io/en/latest/markdown/podman-auto-update.1.html). The only thing blocking me from switching to it is the ability to use a custom command to stop the running container.
I send a request to my server telling it to set itself in "maintenance" mode so it will stop accepting new requests from clients and automatically shutdown itself when all the clients have been disconnected. This ensure seamless upgrades as clients are not disconnected right away when upgrading.

Would it be possible to have something like this with `auto-update`? Something a bit similar to [watchtower's hooks](https://containrrr.dev/watchtower/lifecycle-hooks/) may do.

**Comment by vrothberg** [comment]
Thanks for reaching out, @gdesmott!

What you could do is to change the generated systemd unit:
### Before
```
ExecStop=/usr/bin/podman stop --ignore --cidfile=%t/%n.ctr-id
ExecStopPost=/usr/bin/podman rm -f --ignore --cidfile=%t/%n.ctr-id
```

### After
```
ExecStop= *** CUSTOM SHUTDOWN LOGIX ***
ExecStopPost=/usr/bin/podman stop --ignore --cidfile=%t/%n.ctr-id
ExecStopPost=/usr/bin/podman rm -f --ignore --cidfile=%t/%n.ctr-id
```

Note that customizing the generated units will leave supported territory.  Any chance your workload can handle SIGTERM?  That's what `podman stop` sends to the container initially.

**Comment by vrothberg** [comment]
@gdesmott, can you elaborate on the problems you faced trying to forward the signal?  Did you run the container with `--init`?

That is the only idea (for a supported solution) I have at the moment.

**Comment by gdesmott** [comment]
> Did you run the container with `--init`?

I did not. Will that automatically signal from `entrypoint.sh` to the server binary it started?

**Comment by vrothberg** [comment]
> I did not. Will that automatically signal from entrypoint.sh to the server binary it started?

I can't tell for sure but it's worth testing.  The `--init` binary will only forward to spawned process but some shells exec on the last command instead of forking (see https://github.com/containers/podman/issues/13324#issuecomment-1049832760), so it may "just work".

**Comment by Luap99** [comment]
I don't think that adding hooks to podman auto-update is more useful then just running the commands before/afterwards.

You can also just put this into a script:
```
custom command
podman auto-update
custom command
```

**Comment by Luap99** [comment]
Ah, that's true.

**Comment by vrothberg** [comment]
> > I did not. Will that automatically signal from entrypoint.sh to the server binary it started?
> 
> I can't tell for sure but it's worth testing. The `--init` binary will only forward to spawned process but some shells exec on the last command instead of forking (see [#13324 (comment)](https://github.com/containers/podman/issues/13324#issuecomment-1049832760)), so it may "just work".

@gdesmott did it work using `--init`?

**Comment by gdesmott** [comment]
I didn't have a chance to test it yet. It's definitely on my TODO list but it makes take a while, so feel free to close this ticket for now if you think adding such feature does not make sense.

**Comment by vrothberg** [comment]
Sounds good to me.  Please let us know how it worked out.
