### ISSUE TITLE
Machine start fails on macOS AWS EC2 instance

### ISSUE THREAD

**Issue by alexbde** [containers/podman#14428]
BUG REPORT

/kind bug

**Description**

Command `podman machine start` fails with non-root user on macOS AWS EC2 instance with the following message: `Error: dial unix /tmp/podman/qmp_podman-machine-default.sock: connect: no such file or directory`.

**Steps to reproduce the issue:**

It's basically following the installation instructions (https://podman.io/getting-started/installation#macos):

1. install podman with `brew install podman` as user `ec2-user` (this is the built-in user for running those commands)
2. switch to user `jenkinsagent` (because this is the user which should run docker commands in the end)
3. run
```
jenkinsagent$ podman machine init
Downloading VM image: fedora-coreos-36.20220511.dev.0-qemu.x86_64.qcow2.xz: done  
Extracting compressed file
Image resized.
Machine init complete
To start your machine run:

        podman machine start

```
4. run
```
jenkinsagent$ podman machine start
Starting machine "podman-machine-default"
Error: dial unix /tmp/podman/qmp_podman-machine-default.sock: connect: no such file or directory
```

**Describe the results you received:**

`Error: dial unix /tmp/podman/qmp_podman-machine-default.sock: connect: no such file or directory`

**Describe the results you expected:**

Podman machine started.

**Additional information you deem important (e.g. issue happens only occasionally):**

```
jenkinsagent$ id
uid=503(jenkinsagent) gid=501(jenkinsagent) groups=501(jenkinsagent),12(everyone),61(localaccounts),100(_lpoperator)
jenkinsagent$ podman machine list
NAME                     VM TYPE     CREATED        LAST UP        CPUS        MEMORY      DISK SIZE
podman-machine-default*  qemu        3 minutes ago  3 minutes ago  1           2.147GB     107.4GB
jenkinsagent$ podman system connection list
Name                         URI                                                         Identity                                         Default
podman-machine-default       ssh://core@localhost:50813/run/user/503/podman/podman.sock  /Users/jenkinsagent/.ssh/podman-machine-default  true
podman-machine-default-root  ssh://root@localhost:50813/run/podman/podman.sock           /Users/jenkinsagent/.ssh/podman-machine-default  false
```

Running above commands as user `ec2-user` is working. Note the user `jenkinsagent` is not in the sudo group.

**Output of `podman version`:**

```
jenkinsagent$ podman version
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: connection to bastion host (ssh://core@localhost:50813/run/user/503/podman/podman.sock) failed: dial tcp [::1]:50813: connect: connection refused
jenkinsagent$ brew list --versions | grep podman
podman 4.1.0
```

The version is 4.1.0.

**Output of `podman info --debug`:**

```
jenkinsagent$ podman info --debug
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: connection to bastion host (ssh://core@localhost:50813/run/user/503/podman/podman.sock) failed: dial tcp [::1]:50813: connect: connection refused
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
jenkinsagent$ brew list
==> Formulae
awscli          docker-compose  gmp             kubernetes-cli  libnghttp2      libtool         m4              node            pcre            python@3.9      sqlite
bdw-gc          docker-machine  gnutls          libev           libpng          libunistring    mono            nuget           pixman          qemu            unbound
brotli          gdbm            guile           libevent        libslirp        libusb          mpdecimal       openjdk@11      pkg-config      readline        vde
c-ares          gettext         icu4c           libffi          libssh          libuv           ncurses         openssl@1.1     podman          six             xmlstarlet
ca-certificates glib            jpeg            libidn2         libtasn1        lzo             nettle          p11-kit         python@3.10     snappy          xz

==> Casks
amazon-ena-ethernet             amazon-ssm-agent                android-commandlinetools        ec2-macos-init                  ec2-macos-system-monitor        temurin
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
jenkinsagent$ uname -a
Darwin jenkins_agent_mac01 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
```

**Comment by baude** [comment]
any chance the instance is already a vm? that would entail nested virt, which i dont think is supported?

**Comment by rhatdan** [comment]
Since we never heard back, I am going to close,  Reopen if you have more information.

**Comment by alexbde** [comment]
> any chance the instance is already a vm? that would entail nested virt, which i dont think is supported?

Hi! Sorry for the super late answer. No, it is no VM, it is a macOS AWS EC2 instance as stated in the original text. It is running on a dedicated host, from the [docs](https://aws.amazon.com/en/ec2/instance-types/mac/): "x86-based EC2 Mac instances are built on Apple Mac mini computers featuring Intel Core i7 processors and are powered by the [AWS Nitro System](https://aws.amazon.com/ec2/nitro/)."

> Since we never heard back, I am going to close, Reopen if you have more information.

Yes, please reopen. Sorry again for not answering in the first place.

**Comment by Luap99** [comment]
I this still an issue? At least with the latest version it should return a qemu error message.

**Comment by vrothberg** [comment]
Going through old issues at the moment.  With the advent of Podman Desktop, podman has much more exposure on Mac OS now.  While I only have an ARM Mac, I am sure the issue has been fixed.

**Comment by vrothberg** [comment]
He, coincidentally looked at the same issue @Luap99 :^)
