### ISSUE TITLE
podman cp can overwrite existing files/directories 

### ISSUE THREAD

**Issue by Luap99** [containers/podman#14420]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

using podman cp incorrect can lead to very easy data loss.
Currently it is possible to overwrite an existing file/directory on the host without any warnings.

I noticed this while looking at https://github.com/containers/podman/pull/14393.
So my question is why is this an option, and why it is not the default? I cannot imagine that somebody actually would want this and if they do it is simple to just remove the file/directory beforehand.

**Steps to reproduce the issue:**

1.
```
podman run --name test alpine touch /test1
$ bin/podman cp ^C
$ mkdir test1
$ bin/podman cp test:/test1 .
$ ls -l test1 
-rw-r--r--. 1 pholzing pholzing 0 May 30 17:36 test1
```

2.
```
$ podman run --name test alpine mkdir /test1
$ touch test1
$ bin/podman cp test:/test1 .
$ ls -ld test1
drwxr-xr-x. 1 pholzing pholzing 0 May 30 17:39 test1
```

**Describe the results you received:**
The original file/directory is gone.

**Describe the results you expected:**
An error like the one from `cp`:
`cp: cannot overwrite non-directory './test1' with directory 'test/test1'`

**Additional information you deem important (e.g. issue happens only occasionally):**
Looks like we regressed on this one, I already reported this a long time ago: https://github.com/containers/podman/issues/7790

Also I verified that `docker cp` works as I would expect and errors correctly in both cases.

**Comment by vrothberg** [comment]
It screams for regression tests.

**Comment by Luap99** [comment]
A option is fine for me but the default should be to not overwrite.

**Comment by rhatdan** [comment]
SGTM

**Comment by nalind** [comment]
It needs to be a separate option.  This logic backends our handling of COPY and ADD instructions in Dockerfiles, and we definitely don't want to change how they behave.

**Comment by vrothberg** [comment]
-> https://github.com/containers/buildah/pull/4043
