### ISSUE TITLE
--filter flag for `podman stop

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#14452]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

To not forget it: a `--filter` flag for `podman stop` would simplify the `podman-restart.service` which is currently doing a `podman list --filter` before `podman stop`.

Cc: @rhatdan

**Comment by rhatdan** [comment]
Interns...

**Comment by karthikelango137** [comment]
got it

**Comment by rhatdan** [comment]
@karthikelango137 Any movement on this?

**Comment by karthikelango137** [comment]
> @karthikelango137 Any movement on this?

Yes, I will be opening a PR shortly

**Comment by rhatdan** [comment]
This was fixed in https://github.com/containers/podman/pull/14832 I believe.
