### ISSUE TITLE
document how to enable dns in default netavark network

### ISSUE THREAD

**Issue by ibotty** [containers/podman#14473]
/kind bug

**Description**

I want to enable dns resolution in the default network created by (rootful) podman.  I did not find documentation on how to do that.

Ideally it would also include the name of the configfiles to use to allow easy autoprovisioning via ignition file (without having to create `OneShot`-Units).

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.18beta2

Built:      Thu Mar  3 14:56:09 2022
OS/Arch:    linux/amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Comment by flouthoc** [comment]
Hi @ibotty , Thanks for creating the issue. 
Afaik `dns` on default network is always disabled and it was like this to match docker compatibility.

**Comment by Luap99** [comment]
@ibotty That depends if you use cni or netavark please provide the `podman info` output.

You can create the default config on disk and change the settings in there to enable dns.
For netavark this should do it: https://github.com/containers/podman/discussions/13488#discussioncomment-2358133

**Comment by ibotty** [comment]
Sorry, I was talking about netavark.  Thank you for the link.  I'll try to create a pull request to add it to the FAQ.

**Comment by ibotty** [comment]
I did not find a FAQ.  Is the basic networking file the right place?

**Comment by Luap99** [comment]
Yes that should be a good place.

**Comment by ibotty** [comment]
See #14479
