### ISSUE TITLE
Podman 4.0.2 with docker-compose 2.6.0 does not update network MTU (rootful)

### ISSUE THREAD

**Issue by rskntroot** [containers/podman#14482]
/kind bug

**Description**

The following network block does not update using docker-compose
```
networks:
  default:
    driver: bridge
    driver_opts:
      mtu: 9000
```
**Steps to reproduce the issue:**

1. `vi docker-compose.yml`
```
version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80

networks:
  default:
    driver: bridge
    driver_opts:
      mtu: 9000

```
2. `docker-compose up -d`

**Describe the results you received:**

```
[ ]# podman network inspect nginx_default
[
     {
          "name": "nginx_default",
          "id": "2e2c8c93df9add0ae49c0658c00bc0eee55ff28ba253677c6fa1272601f00c23",
          "driver": "bridge",
          "network_interface": "cni-podman1",
          "created": "2022-06-03T11:36:24.318423681-04:00",
          "subnets": [
               {
                    "subnet": "10.89.0.0/24",
                    "gateway": "10.89.0.1"
               }
          ],
          "ipv6_enabled": false,
          "internal": false,
          "dns_enabled": true,
          "labels": {
               "com.docker.compose.network": "default",
               "com.docker.compose.project": "nginx",
               "com.docker.compose.version": "2.6.0"
          },
          "ipam_options": {
               "driver": "host-local"
          }
     }
]

```

```
[ ]#  ip a s dev cni-podman1
215: cni-podman1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
...
```
**Describe the results you expected:**

```
"mtu": "9000"
```
```
[ ]#  ip a s dev cni-podman1
215: cni-podman1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc noqueue state UP group default qlen 1000
...
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Tested on multiple versions (up to 4.0.2)
Tested on multiple systems (all 10Gbps capable)

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7

Built:      Tue Apr 19 06:16:32 2022
OS/Arch:    linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.0.2-6.module+el8.6.0+14877+f643d2d6.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes (latest available version of podman for RHEL 8)

**Comment by mheon** [comment]
Can you get a `podman network inspect` of the network made by Compose?

**Comment by rskntroot** [comment]
> Can you get a `podman network inspect` of the network made by Compose?

It is in the original post under "Describe the results you received"

**Comment by mheon** [comment]
@jakecorrenti This looks like a good bug to look at next

**Comment by rhatdan** [comment]
@jakecorrenti Still working on this?

**Comment by jakecorrenti** [comment]
> @jakecorrenti Still working on this?

Looks like some 2 failing tests that I lost track of. I'll get that going green today.
