### ISSUE TITLE
`OCI permission denied` if volume is located within user mount

### ISSUE THREAD

**Issue by alexanderadam** [containers/podman#14488]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm trying to put Podman bind volumes of a rootless container within a [gocryptfs](https://nuetzlich.net/gocryptfs/) user mount run by the same user.
Everything works fine if the volume bind is located outside the mount but it fails with `OCI permission denied` if it is within the mount.

**Steps to reproduce the issue:**

1. create a gocryptfs mount
2. try to mount a volume within the mount

But I [created a repository with Vagrant an Ansible to reproduce the issue reliably](https://github.com/alexanderadam/podman_oci_permission_denied#creating-podman-bind-volume-within-user-mount) since this is probably better to debug.

**Describe the results you received:**

The container isn't starting and complains with

```
Error: unable to start container "…": error stat'ing file `/home/podman_user/decrypted/postgres`: Permission denied: OCI permission denied
```
which seem to be [a common error message](https://github.com/containers/podman/issues?q=%22OCI+permission+denied%22).

**Describe the results you expected:**

The container runs.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

<details>
  <summary>Click to show</summary>

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 1
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: ubuntu
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.15.0-27-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 28434432
  memTotal: 490627072
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 0
  swapTotal: 0
  uptime: 13m 34.14s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/podman_user/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/podman_user/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/user/1001/containers
  volumePath: /home/podman_user/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 3.4.4
```

</details>

**Package info (output of `apt list podman`):**

```
podman/jammy,now 3.4.4+ds1-1ubuntu1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No, I don't know how to properly get a more recent version on Ubuntu 22.04 since the PPA isn't available for this version any more.
Is there any new, production-ready and reliable variant to do this?

**Additional environment details (AWS, VirtualBox, physical, etc.):** Libvirt

**Comment by alexanderadam** [comment]
I created [an Ansible repo](/home/{{ podman_user }}/decrypted) for easy reproducibility and the volume line is [`"/home/podman_user/decrypted/postgres:/var/lib/postgresql/data:Z,U,rbind,noexec"`](https://github.com/alexanderadam/podman_oci_permission_denied/blob/main/roles/podman/tasks/postgres.yml#L31).

I didn't try with privileged since I want to achieve this combination within an unprivileged context.

**Comment by mheon** [comment]
Please try with `--privileged` - knowing whether elevated privileges solve the problem is very relevant to determining where the problem could be.

**Comment by alexanderadam** [comment]
`--privileged` doesn't help. It doesn't even work when I prepend `sudo`.

I thought that the Ansible repo would help you to test it yourself.
But if you rather want to setup everything manually, you could simply follow this:

```bash
mkdir decrypted
mkdir encrypted
gocryptfs -init encrypted
gocryptfs encrypted decrypted
podman pod create --name harry-podder
podman run --privileged --name postgres --pod harry-podder -e POSTGRES_USER=foo -e POSTGRES_PASSWORD=bar -v "$HOME/decrypted/postgres:/var/lib/postgresql/data:Z,U,rbind,noexec" docker.io/postgres:14
```

**Comment by rhatdan** [comment]
Does this work if  you run the container outside of a Pod?

**Comment by rhatdan** [comment]
Trying this without the gocryptfs, it works fine for me.

**Comment by alexanderadam** [comment]
> Does this work if you run the container outside of a Pod?

No, it doesn't. Neither with nor without `--privileged` and/or `sudo`.

> Trying this without the gocryptfs, it works fine for me.

Exactly, this is only happening within the GoCryptfs user mount.
That's why I explicitly wrote in the issue

> Everything works fine if the volume bind is located outside the mount but it fails with OCI permission denied if it is within the mount.

So the mentioned user mount is definitely relevant.

**Comment by rhatdan** [comment]
I would figure there is some rootless interaction going on here.

Does the blow up if you switch the runtime to runc?

podman --runtime=runc ...

**Comment by alexanderadam** [comment]
> Does the blow up if you switch the runtime to runc?

It gives a different error
```bash
$ podman run --runtime=runc --privileged --name postgres --pod harry-podder -e POSTGRES_USER=foo -e POSTGRES_PASSWORD=bar -v "$HOME/decrypted/postgres:/var/lib/postgresql/data:Z,U,rbind,noexec" docker.io/postgres:14
chown: changing ownership of '/var/lib/postgresql/data': Operation not permitted
```

and with sudo it gives `Error: statfs /home/vagrant/decrypted/postgres: permission denied` again.

**Comment by rhatdan** [comment]
Could yo try to remove the :Z and see if this changes anything?  How about :U? :rbind? :noexec?

**Comment by alexanderadam** [comment]
It's always `Operation not permitted`

**Comment by alexanderadam** [comment]
> Could you give me podman info?

It's included in [the first post](https://github.com/containers/podman/issues/14488#issue-1260899749).

You can click below "Output of podman info --debug" on "Click to show" to see the whole response.

> What is the storage driver?

It's [`overlay`](https://github.com/alexanderadam/podman_oci_permission_denied/blob/main/roles/podman/tasks/main.yml#L26-L31)

**Comment by rhatdan** [comment]
@giuseppe Ideas?

**Comment by giuseppe** [comment]
could you try creating the mount inside the user namespace?

Otherwise it is running on the host, where the user has access to only one UID/GID and chown fails.

What you'd have to do is:

```
podman unshare <------------- brings you in the rootless user namespace
mkdir decrypted
mkdir encrypted
gocryptfs -init encrypted
gocryptfs encrypted decrypted
mkdir decrypted/postgres
podman pod create --name harry-podder
podman run --privileged --name postgres --pod harry-podder -e POSTGRES_USER=foo -e POSTGRES_PASSWORD=bar -v "$HOME/decrypted/postgres:/var/lib/postgresql/data:Z,U,rbind,noexec" docker.io/postgres:14
```

**Comment by alexanderadam** [comment]
> another thing to check: the FUSE file system must be mounted with `allow_other` otherwise other users cannot access it.

oh no! This was it! Thank you so much for going through the debugging process with me.
I'm very sorry that I didn't see this and I hope I didn't waste your time.

Thank you for working on the container ecosystem! :raised_hands:

**Comment by kkharji** [comment]
hmmm getting similar issue. I'm using podman on macos, not sure what I do `allow_other` or where to execute. It would be great if someone can give more hint. Thanks

**Comment by alexanderadam** [comment]
I'm also still getting this issue with `:U` volume mounts or when trying to do [`podman unshare`](https://docs.podman.io/en/latest/markdown/podman-unshare.1.html).

But I'll open a separate issue for this at one point since it's slightly different.

**Comment by mtalexan** [comment]
> hmmm getting similar issue. I'm using podman on macos, not sure what I do `allow_other` or where to execute. It would be great if someone can give more hint. Thanks

@kkharji  
When you're calling to mount the FUSE filesystem, you need to make sure to add the extra mount option `allow_other` to the mount command.  How you do that depends on the particulars of your system type and how you mounted the FUSE filesystem.

**Comment by kkharji** [comment]
Thanks @mtalexan for clearing this out.

**Comment by alexanderadam** [comment]
Btw @rhatdan & @giuseppe would it make sense and be possible to give a hint with the error message?
Something like `OCI permission denied (ensure that 'allow_other' is set if this happens on a FUSE mount)` to improve user experience?

**Comment by mtalexan** [comment]
The error isn't specific to FUSE file systems, so that's not always the fix. I don't this because I was experiencing the issue on am EXT4 filesystem that doesn't even have that mount option. It's also the same error if you don't have permissions to the mount, or to the directory you're trying to mount.

**Comment by ravikhetani** [comment]
Hi,

Any updates on this, I'm getting the same issue running on Mac - output of podman version:

`podman run -p 4000:5432 --sysctl kernel.shmmax=100663296 postgres:13.11 postgres -c shared_buffers=2024MB -c max_connections=1000`

The error I receive: 

`Error: preparing container b42666560fd49168ce26901f7d47e5eec728df4507675a3fd4f6a36682020431 for attach: crun: open /proc/sys/kernel/shmmax: Permission denied: OCI permission denied`

`Client:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.20.4
Git Commit:   9eef30051c83f62816a1772a743e5f1271b196d7
Built:        Fri May 26 16:10:12 2023
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.20.4
Built:        Fri May 26 18:58:19 2023
OS/Arch:      linux/arm64`
