### ISSUE TITLE
Pull big layers from gitlab (>1GiB)

### ISSUE THREAD

**Issue by qdel** [containers/podman#14481]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Cannot download layers of more than 1GiB from gitlab as it seems to cut layers in different http calls.

**Steps to reproduce the issue:**

1. Get a gitlab instance

2. pull an image with a layer of, say, 1.4Gib

3. download will always fail at 1.0Gib

**Describe the results you received:**

```
$> podman pull instance/image:latest
Trying to pull instance/image:latest...
Getting image source signatures
Copying blob 2cba8f394bae done
Copying blob a53e1a350ebd done
Copying blob b6b0e5bba19c done
Copying blob e59c28769f97 done
Copying blob dbba69284b27 done
Copying blob 3cd53964ee48 done
Copying blob f7596f8333b0 done
Copying blob e71d156c1f99 done
Copying blob 5c7083529f82 done
Copying blob dd7310ba3488 done
Copying blob d44c1954521c [==========================>-----------] 1.0GiB / 1.4GiB
Copying blob 9f8a3fa66ed2 done
Copying blob d95c372a50ba done
Error: writing blob: storing blob to file "/var/tmp/storage3555584973/11": happened during read: unexpected EOF
```

**Describe the results you expected:**

No errors.

**Additional information you deem important (e.g. issue happens only occasionally):**

Pulling with the docker binary is fine.

Gitlab registry seems to this intentionnaly, in the log we can see that the layer is detected to it's correct size. The http request seems to have behaved correctly according to logs, there is no error. But the size is of 1GiB.
Maybe podman need to retry?

**Output of `podman version`:**

```
podman version 4.1.0
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2.1.0+ds1-1_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: unknown'
  cpuUtilization:
    idlePercent: 16.51
    systemPercent: 22.06
    userPercent: 61.43
  cpus: 4
  distribution:
    distribution: debian
    version: unknown
  eventLogger: journald
  hostname: linlap
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.17.0-3-amd64
  linkmode: dynamic
  logDriver: journald
  memFree: 159739904
  memTotal: 12429676544
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun_0.17+dfsg-1.1+b1_amd64
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.0.1-2_amd64
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.7.0
  swapFree: 7130603520
  swapTotal: 14005825536
  uptime: 4h 3m 13.22s (Approximately 0.17 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/rholk/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/rholk/.local/share/containers/storage
  graphRootAllocated: 202694922240
  graphRootUsed: 139573534720
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/rholk/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.18.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/experimental,now 4.1.0+ds2-2 amd64 [installed]
```

Bug is existing also on podman 3.4.7

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes, seems debian experimental provides the latest podman

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Note that is is maybe a weird behaviour of gitlab. If proven so, I can open a bug there. But as docker works fines with it...

**Comment by qdel** [comment]
A good sample is this image: docker.io/reactnativecommunity/react-native-android:latest

**Comment by mheon** [comment]
@vrothberg @mtrmac PTAL

**Comment by vrothberg** [comment]
@qdel, thanks for reaching out.  Are you running behind a proxy?  If so, could you try without it?

**Comment by qdel** [comment]
Hi,

I am not using a proxy on the client side.

I have 2 gitlab instances. One with a reverse proxy, one without.

Both experience the same issue.

**Comment by vrothberg** [comment]
Does wireshark indicate whether the connection to the registry dropped?

**Comment by qdel** [comment]
I am not a pro of wireshark and i will try to create a testing environment for it.

But indeed, in the instance using my reverse proxy, I encouter this error:

```
upstream prematurely closed connection while reading upstream, client: XX.XX.XX.XX, server: XXXXX, request: "GET /v2/dockerbases/debian-qt-builders/blobs/sha256:18c6995dfe2f865881316f5c6ddcb26b54acf76ff9bd1521b9e803be6f1c53ed HTTP/1.1", upstream: "http://192.168.125.14:8881/v2/dockerbases/debian-qt-builders/blobs/sha256:18c6995dfe2f865881316f5c6ddcb26b54acf76ff9bd1521b9e803be6f1c53ed", host: "XXXXXX"
```

When requesting directly my registry in http using following command, the process go to the end.
```
$> podman pull --tls-verify=false 192.168.125.14:8881/dockerbases/debian-qt-builders:latest
```

I am searching if there is configuration in my reverse proxy which can create the hassle.
Not that in the instance of gitlab without reverse proxy, ssl is enabled by gitlab config. I think it host a nginx itself for ssl-isation. (so, there is a reverse proxy also in this case)

Maybe not a podman issue!

**Comment by qdel** [comment]
Hi,

Indeed, this was the case. Note that this post helped me:
https://trac.nginx.org/nginx/ticket/1472

Switching configuration of my proxy with `proxy_max_temp_file_size 0;` correct this issue.
I will provide the info to gitlab in case of...

Note that I am still quite surprised docker does not meet this error. maybe I should check the differences in the http request of both clients. Maybe docker puts a magic header!

Thanks anyway for your help!

**Comment by mtrmac** [comment]
Docker does have some per-layer retry logic that seems to reuse data from previous aborted pull attempts.
