### ISSUE TITLE
Podman Init wont Resolve DNS Windows WSL

### ISSUE THREAD

**Issue by Siythrun** [containers/podman#14495]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman machine unable to resolve DNS

**Steps to reproduce the issue:**

1. podman machine init

**Describe the results you received:**

When trying to install packages for Fedora 35 the WSL VM is unable to resolve the repo mirrors

```
Errors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Error: package upgrade on guest OS failed: exit status 1
```

**Describe the results you expected:**

I would expect it to use the hosts DNS server settings to resolve

**Additional information you deem important (e.g. issue happens only occasionally):**

This might be related to an issue with WSL https://github.com/microsoft/WSL/issues/3438
It is important not for me to be able to access the Internet on any WSL instance I always need to config the resolve.conf to have the appropriate DNS nameservers

**Output of `podman version`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.1.0/libpod/_ping": dial unix /wsl$/Fedora34/run/podman/podman.sock: connect: A socket operation encountered a dead network.
```

**Output of `podman info --debug`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.1.0/libpod/_ping": dial unix /wsl$/Fedora34/run/podman/podman.sock: connect: A socket operation encountered a dead network.
P
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
N/A
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The ability to update the resolve conf as part of the init would be appreciated or to run init wait for it to fail fix the VM manually and then continue the setup

**Comment by mheon** [comment]
@baude @ashley-cui PTAL

**Comment by nobodyman1** [comment]
I tested version 4.0.3, both version have same issue.

**Comment by Siythrun** [comment]
I actualy have to do this alot and wrote a script to auto config our Dev Laptops to provision new instances of WSL Fedora35 for general dev work here is a powershell snippet for making it persists however it requires killing the WSL instance


```
if (Test-Path \\wsl$\podman-machine-default\){
    Write-Host -BackgroundColor Gray -ForegroundColor Black "Patching podman-machine-default Network"
    wsl -d Fedora35 rm -f \\wsl$\podman-machine-default\etc\wsl.conf \\wsl$\podman-machine-default\etc\resolv.conf
    wsl -d Fedora35 echo -e "[network]\ngenerateResolvConf = false" | tee -a \\wsl$\podman-machine-default\etc\wsl.conf
    ((Get-Content "\\wsl$\podman-machine-default\etc\wsl.conf") -join "`n") + "`n" | Set-Content -NoNewline "\\wsl$\podman-machine-default\etc\wsl.conf"
    wsl -t podman-machine-default
    wsl -d podman-machine-default unlink /etc/resolv.conf
    $DNSList=Get-DnsClientServerAddress -AddressFamily IPv4 | Select-Object -ExpandPropert ServerAddresses
    foreach ($DNS in $DNSList) {
        wsl -d podman-machine-default echo -e "nameserver $DNS" | tee -a \\wsl$\podman-machine-default\etc\resolv.conf
    }
    wsl -d podman-machine-defaultecho -e "search lan nti.internal" | tee -a \\wsl$\podman-machine-default\etc\resolv.conf
    ((Get-Content "\\wsl$\podman-machine-default\etc\resolv.conf") -join "`n") + "`n" | Set-Content -NoNewline "\\wsl$\podman-machine-default\etc\resolv.conf"
}else{
    Write-Host -ForegroundColor Red "Cant access \\wsl$\podman-machine-default\"
    exit;
}

```
But due to it killing the WSL instance the machine startup has not progressed and will not start it would be better if there was some way we could configure the resolve.conf before the init command trys to update fedora or if there was some way to make an existing WSL instance into a podman machine

**Comment by nobodyman1** [comment]
I´m not able to use your example code.
`wsl -d podman-machine-default unlink /etc/resolv.conf` is working (although I think it´s not needed), but
`wsl -d podman-machine-default echo -e "nameserver 8.8.8.8" | tee -a \\wsl$\podman-machine-default\etc\resolv.conf` doesn´t work!
And take a look at ` wsl -d podman-machine-defaultecho -e "search lan example.com" ...` this can´t work.
Did you post the correct code?

**Comment by b03602036** [comment]
Had the same issue with 4.1.0 on windows.
Even if I can `wsl` into `podman-machine-default` and modify the /etc/resolv.conf to make it possible to download from "mirrors.fedoraproject.org". 
It failed when I run "podman machine start" 

I followed [here](https://superuser.com/questions/1533291/how-do-i-change-the-dns-settings-for-wsl2) to change the `/etc/resolv.conf` and set it immutable.
Once I ran `yum install e2fsprogs`, it downloaded the fedora files automatically.

I exit podman-machine-default and ran `podman machine start` from Powershell, and it showed like this.
```
> podman machine start
Starting machine "podman-machine-default"
/bin/bash: line 1: /root/bootstrap: No such file or directory
Error: WSL bootstrap script failed: exit status 127
```

**Comment by JerryMWeeks** [comment]
@b03602036 I arrived at /root/bootstrap etc. without having to do as much!
But I had to manually generate the ssh files
`ssh-keygen -f podman-machine-default`
Copy the priv key file to .ssh
`wsl -d podman-machine-default`
in the Linux machine 
`mkdir .ssh
touch .ssh/known_hosts
vi .ssh/known_hosts`
Paste the pub key into the file and :wq
exit the container
run `podman machine start`

**Comment by JerryMWeeks** [comment]
I got suspicious with WSL and Windows Firewall (depending on your Windows build)
Admin PowerShell and run
`New-NetFirewallRule -DisplayName "WSL" -Direction Inbound  -InterfaceAlias "vEthernet (WSL)"  -Action Allow
New-NetFirewallRule -DisplayName "WSL" -Direction Outbound  -InterfaceAlias "vEthernet (WSL)"  -Action Allow`
Then start type windows firewall and run
choose advanced advanced settings
click on `windows defender firewall properties`

![image](https://user-images.githubusercontent.com/19207251/174079686-75f3c432-cd74-4e04-9de8-13e42bd573dc.png)

Click on `Protected network settings`

![image](https://user-images.githubusercontent.com/19207251/174080109-858e7907-69cd-432a-8118-738db64ef9ce.png)

Untick vEthernet WSL

![image](https://user-images.githubusercontent.com/19207251/174080307-941c5e12-70ac-4f1f-ab29-88a6fe8093df.png)

Didn't make any difference though! :( 

Found it suggested somewhere when you search for `WSL 2 Windows Firewall blocked
`

**Comment by JerryMWeeks** [comment]
Is this where the error comes from?
Inside the Fedora WSL machine run the following:
```
sudo dnf -y install podman
Fedora 35 - x86_64                                                                      0.0  B/s |   0  B     02:00
Errors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
```

**Comment by JerryMWeeks** [comment]
I just reset my dev machine, reinstalled WSL, followed by podman 4.1.1 and then ran init - 
still getting this irritating message! 
`podman machine init
Downloading VM image: fedora-35-x86_64.tar.xz: done
Extracting compressed file
Importing operating system into WSL (this may take 5+ minutes on a new WSL install)...
The process cannot access the file because it is being used by another process.
Error: WSL import of guest OS failed: exit status 4294967295`

**Comment by Luap99** [comment]
@n1hility PTAL

**Comment by nobodyman1** [comment]
> I just reset my dev machine, reinstalled WSL, followed by podman 4.1.1 and then ran init - still getting this irritating message! `podman machine init Downloading VM image: fedora-35-x86_64.tar.xz: done Extracting compressed file Importing operating system into WSL (this may take 5+ minutes on a new WSL install)... The process cannot access the file because it is being used by another process. Error: WSL import of guest OS failed: exit status 4294967295`
> 
> Is there any approach I can use to debug the install and find this locked file? I have switched off followed by reboot 3 times before getting this (before doing anything else) Antivirus perhaps?

You will find the downloaded files in `%USERPROFILE%\.local\share\containers\podman\machine\wsl`.
I think you should check `wsl -l -v` if the state of the machine is `Stopped`.

**Comment by JerryMWeeks** [comment]
Thanks @nobodyman1  - actually between each init I have been running
 wsl --unregister  podman-machine-default
followed by
deleting the sub-folder podman and all contents under 
%USERPROFILE%\.local\share\containers , %USERPROFILE%\.config\share\containers ,and the file: %USERPROFILE%\appdata\roaming\containers\containers.conf
Without deleting these podman machine init fails on machine exists or similar.
Oddly my work laptop I can repeatedly delete, experiment, recreate etc. (but dns lookup to mirrors.fedoraproject.org always fails). But on the dev machine I always get the file locked message - I am now suspecting it is because I am RDP connected, via a double login (first local followed by domain logins).

**Comment by n1hility** [comment]
Other related WSL Issues: #4385 #8265

We can provide a way for you to perform manual configuration actions through init, but if you need to overwrite resolv.conf there is likely a WSL networking problem at play. Are any of you who are experiencing this problem using a VPN or special firewall? 

A common cause for this sort of thing is that your windows defender policy is dropping packets. 

Could you guys check the following

1. cat /etc/resolv.conf (before patching it)
2. Output of ifconfig (you will need to dns install net-tools first - after patching resolv.conf)
3. Output of netstat -rn
4. On a Windows powershell prompt: Output of ipconfig 

What you should see is that these are consistent. The value of resolv.conf matches the gateway address which also matches the windows WSL vEthernet interface IP. 

This is just a rudimentary check that the file is generated correctly and still in sync with the active network.

Next try

1. wsl --shutdown
2. wsl -d podman-machine-default
3. curl www.google.com # Does DNS work yet?

Then reboot the system completely and try the same, does it work then?

Assuming there is no special firewalls or a VPN, the next thing to look at is your Windows Defender Firewall policy. 

A simple first test is to try completely fully disabling windows defender off (not just the interface). Go to Control Panel\System and Security\Windows Defender Firewall. Turn off for everything. If you do so does DNS start working?

If so you can turn it back on and try to figure out why:

After you start a wsl command, If you look at the inbound rules, using the following powershell command:
```
Get-NetFirewallRule -Name HNS* |
 Format-Table -Wrap -Autosize -Property Profile, Direction,
 @{Name='Intf';e={($PSItem | Get-NetFirewallInterfaceFilter).InterfaceAlias}}, 
 @{Name='LPrt';e={($PSItem | Get-NetFirewallPortFilter).LocalPort}},
 @{Name='RPrt';e={($PSItem | Get-NetFirewallPortFilter).RemotePort}},
 @{Name='Prot';e={($PSItem | Get-NetFirewallPortFilter).Protocol}},
 @{Name='RAdd';e={($PSItem | Get-NetFirewallAddressFilter).RemoteAddress}},
 @{Name='LAdd';e={($PSItem | Get-NetFirewallAddressFilter).LocalAddress}},
 @{Name='Prog';e={($PSItem | Get-NetFirewallApplicationFilter).Program}},
 Name

```

You should see something like this (when WSL is running)

```
Profile Direction Intf            LPrt RPrt Prot RAdd LAdd Prog                              Name
------- --------- ----            ---- ---- ---- ---- ---- ----                              ----
    Any   Inbound Any             53   Any  TCP  Any  Any  %SystemRoot%\system32\svchost.exe HNS Container Networking -
                                                                                             ICS DNS (TCP-In) - E152AFC2-7
                                                                                             93D-4750-A09F-8123F6404192 -
                                                                                             0
    Any   Inbound vEthernet (WSL) 53   Any  UDP  Any  Any  Any                               HNS Container Networking -
                                                                                             DNS (UDP-In) - E152AFC2-793D-
                                                                                             4750-A09F-8123F6404192 - 0
```

The interface for the UDP rule should match the name in your ipconfig output. If instead you have a UID that does not exist, then that would be a problem.

If that or anything else with the rules looks off, you could create your own DNS rules just apply them to the any interface.

If everything looks correct you could still confirm its dropping the packets, you can enable logging by launching windows defender firewall -> advanced settings -> right clicking on the (Windows Defender Firewall with) icon above the Rules icons, and choose properties, then pick the public tab, then logging, enable log dropped packets, and specify a file location for the log. It rotates so depending on how much dropped traffic you have it might fly by. Then you attempt a dns query and if its logged then you confirm thats the source of the problem. 

If it is dropping then you can try the same solution, create a custom rule to get it working. 

If you exhaust the Windows Defender route then it likely is some other networking issue, a VPN client, a firewall in an AV tool, or some other network interface that might be mucking with the routing.

**Comment by n1hility** [comment]
> and more Now to find if it works! phew. which it doesn't where is this file? ` podman machine start Starting machine "podman-machine-default" /bin/bash: line 1: /root/bootstrap: No such file or directory Error: WSL bootstrap script failed: exit status 127`

Podman machine does a number of customization steps, so thats why you are receiving this error. Until we have a simpler override mechanism, what might work as a temporary hack, is you could modify the rootfs that we start from: 

https://github.com/fedora-cloud/docker-brew-fedora/blob/35/x86_64/fedora-35-x86_64.tar.xz

If you add your custom resolv.conf and a /etc/wsl.conf to the tarball with 

```
[network]
generateResolvConf = false
```

then you pass that the new tar.xz to 

`podman machine init --image-path custom.tar.xz`

I'm not completely sure if those files will survive, but worth a try.

**Comment by JerryMWeeks** [comment]
> Other related WSL Issues: [microsoft/WSL#4285](https://github.com/microsoft/WSL/issues/4285) [microsoft/WSL#8365](https://github.com/microsoft/WSL/issues/8365)
> 
> We can provide a way for you to perform manual configuration actions through init, but if you need to overwrite resolv.conf there is likely a WSL networking problem at play. Are any of you who are experiencing this problem using a VPN or special firewall?
> 
> A common cause for this sort of thing is that your windows defender policy is dropping packets.
> 
> Could you guys check the following
> 
> 1. cat /etc/resolv.conf (before patching it)
> 2. Output of ifconfig (you will need to dns install net-tools first - after patching resolv.conf)
> 3. Output of netstat -rn
> 4. On a Windows powershell prompt: Output of ipconfig
> 
> What you should see is that these are consistent. The value of resolv.conf matches the gateway address which also matches the windows WSL vEthernet interface IP.
> 
> This is just a rudimentary check that the file is generated correctly and still in sync with the active network.
> 
> Next try
> 
> 1. wsl --shutdown
> 2. wsl -d podman-machine-default
> 3. curl [www.google.com](http://www.google.com) # Does DNS work yet?
> 
> Then reboot the system completely and try the same, does it work then?
> 
> Assuming there is no special firewalls or a VPN, the next thing to look at is your Windows Defender Firewall policy.
> 
> A simple first test is to try completely fully disabling windows defender off (not just the interface). Go to Control Panel\System and Security\Windows Defender Firewall. Turn off for everything. If you do so does DNS start working?
> 
> If so you can turn it back on and try to figure out why:
> 
> After you start a wsl command, If you look at the inbound rules, using the following powershell command:
> 
> ```
> Get-NetFirewallRule -Name HNS* |
>  Format-Table -Wrap -Autosize -Property Profile, Direction,
>  @{Name='Intf';e={($PSItem | Get-NetFirewallInterfaceFilter).InterfaceAlias}}, 
>  @{Name='LPrt';e={($PSItem | Get-NetFirewallPortFilter).LocalPort}},
>  @{Name='RPrt';e={($PSItem | Get-NetFirewallPortFilter).RemotePort}},
>  @{Name='Prot';e={($PSItem | Get-NetFirewallPortFilter).Protocol}},
>  @{Name='RAdd';e={($PSItem | Get-NetFirewallAddressFilter).RemoteAddress}},
>  @{Name='LAdd';e={($PSItem | Get-NetFirewallAddressFilter).LocalAddress}},
>  @{Name='Prog';e={($PSItem | Get-NetFirewallApplicationFilter).Program}},
>  Name
> ```
> 
> You should see something like this (when WSL is running)
> 
> ```
> Profile Direction Intf            LPrt RPrt Prot RAdd LAdd Prog                              Name
> ------- --------- ----            ---- ---- ---- ---- ---- ----                              ----
>     Any   Inbound Any             53   Any  TCP  Any  Any  %SystemRoot%\system32\svchost.exe HNS Container Networking -
>                                                                                              ICS DNS (TCP-In) - E152AFC2-7
>                                                                                              93D-4750-A09F-8123F6404192 -
>                                                                                              0
>     Any   Inbound vEthernet (WSL) 53   Any  UDP  Any  Any  Any                               HNS Container Networking -
>                                                                                              DNS (UDP-In) - E152AFC2-793D-
>                                                                                              4750-A09F-8123F6404192 - 0
> ```
> 
> The interface for the UDP rule should match the name in your ipconfig output. If instead you have a UID that does not exist, then that would be a problem.
> 
> If that or anything else with the rules looks off, you could create your own DNS rules just apply them to the any interface.
> 
> If everything looks correct you could still confirm its dropping the packets, you can enable logging by launching windows defender firewall -> advanced settings -> right clicking on the (Windows Defender Firewall with) icon above the Rules icons, and choose properties, then pick the public tab, then logging, enable log dropped packets, and specify a file location for the log. It rotates so depending on how much dropped traffic you have it might fly by. Then you attempt a dns query and if its logged then you confirm thats the source of the problem.
> 
> If it is dropping then you can try the same solution, create a custom rule to get it working.
> 
> If you exhaust the Windows Defender route then it likely is some other networking issue, a VPN client, a firewall in an AV tool, or some other network interface that might be mucking with the routing.

thanks @n1hility 
I was looking at this issue #14593 - it just happens that I have to use zScaler and another VPN type of app. These are disabled when I run the init, but policy prevents me from fully exiting them (prior to init I do an ipconfig /flushdns and restart PowerShell in an attempt to avoid hanging routes)

**Comment by JerryMWeeks** [comment]
> > and more Now to find if it works! phew. which it doesn't where is this file? ` podman machine start Starting machine "podman-machine-default" /bin/bash: line 1: /root/bootstrap: No such file or directory Error: WSL bootstrap script failed: exit status 127`
> 
> Podman machine does a number of customization steps, so thats why you are receiving this error. Until we have a simpler override mechanism, what might work as a temporary hack, is you could modify the rootfs that we start from:
> 
> https://github.com/fedora-cloud/docker-brew-fedora/blob/35/x86_64/fedora-35-x86_64.tar.xz
> 
> If you add your custom resolv.conf and a /etc/wsl.conf to the tarball with
> 
> ```
> [network]
> generateResolvConf = false
> ```
> 
> then you pass that the new tar.xz to
> 
> `podman machine init --image-path custom.tar.xz`
> 
> I'm not completely sure if those files will survive, but worth a try.

I patched the tar.xz with wsl.conf, but then get this 

`podman machine init --image-path C:\Users\myname\fedora.tar.xz
Error: open C:\Users\myname\.local\share\containers\podman\machine\wsl: is a directory`

So I tried intercepting the init by pasting the tar (with same name) into 
C:\Users\myname\.local\share\containers\podman\machine\wsl
as soon as extract completed - but I suspect there is a CRC check or similar as it then responded:

`podman machine init
Downloading VM image: fedora-35-x86_64.tar.xz: done
Extracting compressed file`
Paste of patched file named _podman-machine-default_fedora-35-x86_64.tar_
`Importing operating system into WSL (this may take 5+ minutes on a new WSL install)...
Installing packages (this will take awhile)...
Error: package upgrade on guest OS failed: exit status 1`

**Comment by JerryMWeeks** [comment]
I found an alternative way - for those urgently needs to get Podman to run.

1. Go to Azure or AWS, spin up a VM - Win 10 or whatever your os is.
2. Run PowerShell
3. Run WSL --install
4. Reboot
5. Download an install podman
6. run podman machine init
7. allow setup to complete
8. run podman machine start
9. observe if start is successful
10. if yes, run podman machine stop
11. 7zip up c:\users\<remote login name>.local and .config (you might need to enable viewing hidden / system files)
12. Copy the .7z file (or zip if you prefer that)
13. Paste in your local laptop at as suitable location
14. Copy containers.conf from c:\users\<your remote login>\AppData\roaming\containers
15. paste that in the same suitable location
16. Edit the json file podman-machine-default.json in the unzipped .config\containers\podman\machine\wsl updating the path in 3 places to match your local machine login / user name (unless you set up your VM in Azure to have the same  login name)
17. e.g. "C:\\Users\\remote-vm-login-name\\.ssh\\podman-machine-default becomes "C:\\Users\\local-login-name\\.ssh\\podman-machine-default
18. Copy .config to c:\users\<your local login>
19. Copy .local to c:\users\<your local login>
20. copy the edited / saved podman-machine-default.json to c:\users\<your local login>\AppData\roaming\containers
21. run podman machine stop
22. run podman machine start

and if you get as lucky as me ... 
 ```
podman machine start
Starting machine "podman-machine-default"

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

        podman machine set --rootful

API forwarding for Docker API clients is not available due to the following startup failures.
        CreateFile \\.\pipe\docker_engine: All pipe instances are busy.

Podman clients are still able to connect.
Machine "podman-machine-default" started successfully
```
Now to get on with the next step ;-)

**Comment by Bindernews** [comment]
Here's my workaround, it requires a separate WSL instance (I used ubuntu) and you'll need to run the commands as **root** so the owner bits are properly saved.

1. Download the fedora image as mentioned in [@JerryMWeeks post](https://github.com/containers/podman/issues/14495#issuecomment-1160105214) - https://github.com/fedora-cloud/docker-brew-fedora/blob/35/x86_64/fedora-35-x86_64.tar.xz
2. Open WSL instance as root and `cd` to directory where you downloaded the fedora tar file
3. `mkdir /fed && tar xfJ fedora-35-x86_64.tar.xz -C /fed` - Extract the tar
4. `cd /fed`
5. `echo -e "nameserver 1.1.1.1\n" >./etc/resolv.conf` - Use cloudflare DNS (replace IP as required)
6. `echo -e "[network]\ngenerateResolvConf = false\n" >./etc/wsl.conf` - Tell WSL not to mess with our DNS
7. `tar cfJ /fedora.tar.xz *` - Rebuild the tar
8. `mv /fedora.tar.xz <windows_folder>` - Put it where podman can get at it
9. (In powershell/cmd) `podman machine init --image-path fedora.tar.xz` - init podman

And here's a scripty version of it. May contain typos.
```bash
#!/bin/bash
TAR_IN="fedora-35-x86_64.tar.xz"
TAR_OUT="fedora.tar.xz"
mkdir /fed && tar xfJ "$TAR_IN" -C /fed
pushd /fed
echo -e "nameserver 1.1.1.1\n" >./etc/resolv.conf
echo -e "[network]\ngenerateResolvConf = false\n" >./etc/wsl.conf
tar cvfJ "/$TAR_OUT" *
popd
mv "/$TAR_OUT" .
```

**Comment by davdr** [comment]
> I patched the tar.xz with wsl.conf, but then get this
> 
> podman machine init --image-path C:\Users\myname\fedora.tar.xz
> Error: open C:\Users\myname\.local\share\containers\podman\machine\wsl: is a directory

For other people trying this: turns out that this works with `--image-path \Users\...` but not `--image-path C:\Users\...`.

**Comment by nobodyman1** [comment]
It doesn´t work for me. If I use `--image-path \Users\...` podman still downloads fedora-35-x86_64.tar.xz to the wsl directory.
And I think the `--image-path` is a relative path to `%USERPROFILE%\.local\share\containers\podman\machine\wsl`.

**Comment by davdr** [comment]
The `--image-path` is the path to the file you want `podman machine init` to use as image for the WSL distro it creates. This is if you want to use your own custom image instead of the default Fedora 35 image that's dowloaded over http.

**Comment by nobodyman1** [comment]
But how does it work? There is no documentation available!
Where should I save the template? `--image-path C:\Users\...` and `--image-path \Users\...` are not working!
Did you try it?

**Comment by davdr** [comment]
@nobodyman1 it's documented here: https://docs.podman.io/en/latest/markdown/podman-machine-init.1.html and yes, I've already used it in another context

**Comment by nobodyman1** [comment]
Thanks a lot. Now it works with `--image-path \Users\...` and `--image-path /Users/..` (but not if a drive letter is specified).

**Comment by majidaldo** [comment]
> 

need the ```echo -e "[network]\ngenerateResolvConf = false\n" >./etc/wsl.conf``` in the script.

**Comment by majidaldo** [comment]
> Here's my workaround, it requires a separate WSL instance (I used ubuntu) and you'll need to run the commands as **root** so the owner bits are properly saved.
> 
> 1. Download the fedora image as mentioned in [@JerryMWeeks post](https://github.com/containers/podman/issues/14495#issuecomment-1160105214) - https://github.com/fedora-cloud/docker-brew-fedora/blob/35/x86_64/fedora-35-x86_64.tar.xz
> 2. Open WSL instance as root and `cd` to directory where you downloaded the fedora tar file
> 3. `mkdir /fed && tar xfJ fedora-35-x86_64.tar.xz -C /fed` - Extract the tar
> 4. `cd /fed`
> 5. `echo -e "nameserver 1.1.1.1\n" >./etc/resolv.conf` - Use cloudflare DNS (replace IP as required)
> 6. `echo -e "[network]\ngenerateResolvConf = false\n" >./etc/wsl.conf` - Tell WSL not to mess with our DNS
> 7. `tar cfJ /fedora.tar.xz *` - Rebuild the tar
> 8. `mv /fedora.tar.xz <windows_folder>` - Put it where podman can get at it
> 9. (In powershell/cmd) `podman machine init --image-path fedora.tar.xz` - init podman
> 
> And here's a scripty version of it. May contain typos.
> 
> ```shell
> #!/bin/bash
> # In powershell: cd to where TAR_IN is located, run 'wsl -d <distro> -u root --', then run this script
> TAR_IN="fedora-35-x86_64.tar.xz"
> TAR_OUT="fedora.tar.xz"
> mkdir /fed && tar xfJ "$TAR_IN" -C /fed
> pushd /fed
> echo -e "nameserver 1.1.1.1\n" >./etc/resolv.conf
> echo -e "[network]\ngenerateResolvConf = false\n" >./etc/wsl.conf
> tar cvfJ "/$TAR_OUT" *
> popd
> mv "/$TAR_OUT" .
> ```


need the echo -e "[network]\ngenerateResolvConf = false\n" >./etc/wsl.conf in the script.

**Comment by n1hility** [comment]
podman 4.2 (just released) now fetches a prebuilt image with no package downloads. If you run into a routing or firewall issue that prevents wsl from functioning, machine init should still succeed. You can use podman machine ssh or the wsl prompt to provide custom dns settings after the init process completes.

**Comment by rhatdan** [comment]
@n1hility Can we close this issue?

**Comment by n1hility** [comment]
@rhatdan Yes I think so. There is a follow-up feature request we could potentially do that allowed a user to provide a custom dns server on init vs manually editing wsl.conf and resolv.conf. This issue has gone on pretty long though, so probably makes sense to split that into another issue.

**Comment by majidaldo** [comment]
> 

please

**Comment by majidaldo** [comment]
> @rhatdan Yes I think so. There is a follow-up feature request we could potentially do that allowed a user to provide a custom dns server on init vs manually editing wsl.conf and resolv.conf. This issue has gone on pretty long though, so probably makes sense to split that into another issue.

please
