### ISSUE TITLE
Alignment with moby swagger definition for `ContainerConfig.entrypoint`

### ISSUE THREAD

**Issue by milenkovicm** [containers/podman#14513]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

running `podman inspect <running container>` returns schema which is not aligned to current https://github.com/moby/moby/blob/master/api/swagger.yaml definition. Json returned by `inspect` command diverges from schema in at least two situations:

1.  `ContainerConfig.entrypoint` which is returned by `podman` as string but according to definition https://github.com/moby/moby/blob/master/api/swagger.yaml#L1271-L1281` it should be array of strings. `"Entrypoint": "",`
2. `ContainerConfig.StopSignal` is returned as integer, schema defines it as string at it might be integer value of signal or string value. https://github.com/moby/moby/blob/aca813e1359f1a3501f1b7453e05b10b3425a90d/api/swagger.yaml#L1306-L1311

This problem is annoying as strongly typed languages (e.g `rust`) do not like having discrepancy between types. 

**Steps to reproduce the issue:**

1. run any container
2. `podman inspect <container_id>` 
3. observe `Entrypoint` and `StopSignal` returned in output

**Describe the results you received:**

`entrypoint` and `stopsignal` have wrong types (as per swagger definition)

**Describe the results you expected:**

I'd expect them to be string array and string

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 4.1.0
```
but issues is available in earlier versions as well

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Luap99** [comment]
Changing the podman inspect format will break the podman API, see https://github.com/containers/podman/pull/13811

If you need 100% compatible docker output I recommend to use the compat API.

**Comment by milenkovicm** [comment]
@Luap99 if compat API is `podman-docker`, it has the same problem, those two properties have wrong type there as well

**Comment by Luap99** [comment]
No the compat API is the actual podman api service, podman-docker just calls podman ...

The podman rest API which provides all docker API endpoints (except swarm), https://docs.podman.io/en/latest/_static/api.html

**Comment by milenkovicm** [comment]
all right @Luap99 , will have a look at it.
as far as i can see types align there.

feel free to close this one if you wish
