### ISSUE TITLE
--userns=keep-id no longer working for privileged containers

### ISSUE THREAD

**Issue by fbezdeka** [containers/podman#14515]
/kind bug

**Description**

The [kas](https://github.com/siemens/kas) project uses `--userns=keep-id` to get a user mapping between the user calling padman run on the host and a specific user (build) inside the container. This worked quite well in the past, but got broken with 80c0fceb24b70a85f3f2ca8be29f4a131c0881d4. We now end up in the error

```
Error: keep-id is only supported in rootless mode
```

As the mentioned commit is talking about adding support for --userns=nomap it's not clear if this change was intended. If this change was really intended: Is there a convenient way of ending up with this user mapping in both podman version worlds?

@rhatdan is the author of the mentioned commit. I hope it's quite easy for him to answer that...

**Steps to reproduce the issue:**

1. podman 3.4.7 (Fedora 35)
```
sudo podman run -i -t --userns=keep-id debian:11
root@994d1ea087de:/#
```
2. podman 4.1.0 (Fedora 36)
```
sudo podman run -i -t --userns=keep-id debian:11
[...]
Error: keep-id is only supported in rootless mode
```

**Describe the results you received:**
```
Error: keep-id is only supported in rootless mode
```

**Describe the results you expected:**
The root user (inside the container) should be mapped to the host-user that executed podman run.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 4.1.0
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpuUtilization:
    idlePercent: 93.41
    systemPercent: 1.48
    userPercent: 5.11
  cpus: 12
  distribution:
    distribution: fedora
    variant: workstation
    version: "36"
  eventLogger: journald
  hostname: flo
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.17.12-300.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 6008049664
  memTotal: 16241545216
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun-1.4.5-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 17179860992
  swapTotal: 17179860992
  uptime: 48m 1.05s
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/flo/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.8.1-3.fc36.x86_64
      Version: |-
        fusermount3 version: 3.10.5
        fuse-overlayfs: version 1.8.1
        FUSE library version 3.10.5
        using FUSE kernel interface version 7.31
  graphRoot: /home/flo/.local/share/containers/storage
  graphRootAllocated: 322391203840
  graphRootUsed: 67642916864
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 5
  runRoot: /run/user/1000
  volumePath: /home/flo/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.0
  Built: 1651853754
  BuiltTime: Fri May  6 18:15:54 2022
  GitCommit: ""
  GoVersion: go1.18
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.1.0-1.fc36.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No (I'm quite sure it will would not help)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Good old bare metal, running Fedora 35/36.

**Comment by rhatdan** [comment]
There is no way to know guaranteed who the user is running the container.

You should just do 
$ sudo podman run --user $(id -u):$(id -g) fedora id
uid=3267(3267) gid=3267(3267) groups=3267(3267)

**Comment by fbezdeka** [comment]
Thanks for all the super fast support. It seems that we need `--userns=keep-id` for rootless containers only, so we should be able to deal with that.

The proposed `--user $(id -u):$(id -g)` did not work because the username inside the container would become the numerical value, which does not work together with expectations (like sudo configuration) inside the container.

The documentation about `keep-id` tells me that it should simply be ignored in containers created by the root user. Taken from https://docs.podman.io/en/latest/markdown/podman-pod-create.1.html?highlight=keep-id#userns-mode
```
keep-id: creates a user namespace where the current rootless user’s UID:GID are mapped to the same 
values in the container. This option is ignored for containers created by the root user.
```
It's definitly no longer ignored. Might be a documentation bug now, but it's definitely an API change.
