### ISSUE TITLE
image digest built using podman is different to digest of image built using docker

### ISSUE THREAD

**Issue by amokkara** [containers/podman#14511]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I built an image using podman and also docker.
image built using podman has different digest compared to image built using docker.
is this expected? is there any middle ground where both these can have common digest? (may be using some parameter)?

**Steps to reproduce the issue:**

1. build image using podman

2. build image using docker

3. compare the image digests

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
Thanks for reaching out, @amokkara.

> image built using podman has different digest compared to image built using docker.
> is this expected? is there any middle ground where both these can have common digest? (may be using some parameter)?

That is a "known" issue: the digest of an image depends, among other things, on the digest of the layers. The digest of the layers is further determined by the compression algorithm. The compression algorithm may (slightly) change at any given time - even when using the `gzip` package of Go's standard library.

That being said: there is no guarantee that any tool will generate the same digest over time (and over multiple versions).

I am closing the issue as there's not much we can do but we can continue the conversation.  May I ask why you are looking for the tools to generate the same digest?  Maybe we can find an alternative.

**Comment by amokkara** [comment]
@vrothberg thanks for quick reply. let me explain my situation and may be you can provide a solution.
we first build images using podman, save them to tar file and also provides the image digest  for each image and ship it.
the user loads these images in docker env (docker load) and pushes them to a registry.

once user pushes the images, the digest is not matching to the digest we sent when we shipped it.
how do i overcome this problem? any help is much appreciated

Note: we cant stick to either podman or docker when building them. Thats not an option we have.

**Comment by vrothberg** [comment]
Thanks for elaborating, @amokkara.

I do not know a solution to this problem.  If you do a `skopeo inspect --raw docker://$yourImage` on the original image and the final one, you should see what has changed. I am 99 percent sure the digests differ.

@mtrmac, WDYT?

**Comment by mtrmac** [comment]
Yeah, the `docker-archive` format preserves neither the compression format nor the manifest representation. It’s not possible to preserve a digest using that format.

For syncing between registries, use a direct registry-to-registry copy using `skopeo` (possibly using a temporary localhost registry for transfer to an off-line site), or perhaps a `dir:` format via `skopeo copy` or `skopeo sync`.
