### ISSUE TITLE
podman push not working on same tag

### ISSUE THREAD

**Issue by eshaingle** [containers/podman#14510]
I have  below podman version on M1 macbook pro
```Client:       Podman Engine
Version:      4.1.0
API Version:  4.1.0
Go Version:   go1.18.1
Built:        Thu May  5 22:07:47 2022
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.16.14
Built:        Thu Mar  3 15:58:50 2022
OS/Arch:      linux/arm64
```

I am building an image and pushing it to a particular tag. It works fine.
However, when i make few changes to Dockerfile or related files and try to push the image with same tag, the changes are not available. I have to build a new image tag and push.

Please let me know if there is any way to push changes to same tag as I don't want to populate the gitlab registry with multiple tags

**Comment by rhatdan** [comment]
Could you update your machine by rerunning podman machine init.  I believe this will update the machine to match the client.  Don't know if this will fix your problem or not.

**Comment by eshaingle** [comment]
Hello, Thank you for your reply.
I did reran the podman machine init and now both the versions are same.
But now I am not able to push. Its like hanging for hours whenever I run push command.

I ram below commands are well in order to make the push work but it didnt work
```podman machine ssh sudo rpm-ostree install qemu-user-static
podman machine ssh sudo systemctl reboot```

My machine is Mac M1 monterey

**Comment by eshaingle** [comment]
Update:
Reinstalling podman and performing all actions again resolved the issue for me.
Thank you.
