### ISSUE TITLE
Add an option to run podman play kube in the foreground. Stop pod when process is terminated.

### ISSUE THREAD

**Issue by 1player** [containers/podman#14522]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Requesting a command line option to run `podman play kube` in the foreground. All containers are started normally, and when the podman process is terminated, all pods are stopped. This is so I don't have to remember to run `podman play kube --down` every time.

The goal is to have a similar behaviour as `docker-compose up`, which runs all services and stops them when the process is stopped, unless `--detach` is passed.

The use case is for local development. I would like to start my dev pods, and for them to be stopped automatically if I close the terminal. With the current behaviour, more than one time I've forgot to call `podman play kube --down` and I had my dev containers consuming resources in the background.

**Comment by rhatdan** [comment]
Makes sense to me. but we may need to default to --detach=true, since we would not wan to break existing scripts.

**Comment by vrothberg** [comment]
Starting with Podman v4.2, the pods terminate on their own.  They won't be removed but they terminate.  Would that address your issue?

**Comment by 1player** [comment]
> Starting with Podman v4.2, the pods terminate on their own. They won't be removed but they terminate. Would that address your issue?

Does this mean that on Podman 4.2 `play kube` stays in the foreground until stopped with Ctrl-C, and at that point pods are terminated? That would indeed address this issue.

**Comment by vrothberg** [comment]
> Does this mean that on Podman 4.2 play kube stays in the foreground until stopped with Ctrl-C, and at that point pods are terminated? That would indeed address this issue.

No, nothing runs in the foreground.  But if all containers in a pod exited, then the pod gets stopped automatically.

**Comment by 1player** [comment]
Ah, then what I'm requesting is different. This issue is to have a mode that all pods are started with `play kube`, and they stay running until the `play kube` process is stopped. At that point the pod is terminated. In other words:

1. Start pod
2. Wait for signal
3. Stop pod

Currently `play kube` only provides a "detach" mode, and users need to remember to do a `play kube --down` manually or everything keeps running indefinitely.

**Comment by vrothberg** [comment]
Thanks for elaborating.  That sounds doable: `play kube` waits for a sigstop and runs `play kube --down` when receiving the signal.

**Comment by 1player** [comment]
Ugh. Not stale.

**Comment by rhatdan** [comment]
@umohnani8 Could you take a look at this or assign an intern?
@ashley-cui @vrothberg ^^

**Comment by 1player** [comment]
You can assign this to me, I have a PR ready to go but I can't test properly until #15071 is fixed.

**Comment by 1player** [comment]
The PR is still open, I've answered there, but I don't see why this issue needs to be closed. It's still a valid request with related PR.

**Comment by rhatdan** [comment]
It does not need to be closed.  I like the proposed fix, just want to get it's status.
