### ISSUE TITLE
Podman login tries to map uid of user that I use to login instead of build user

### ISSUE THREAD

**Issue by GolanTrevize10** [containers/podman#14568]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When running podman login -u myuser -p password myregistry I get the following error:

17:29:51  time="2022-06-10T17:29:51+02:00" level=warning msg="\"/\" is not a shared mount, this could cause issues or missing mounts with rootless containers"
17:29:51  time="2022-06-10T17:29:51+02:00" level=error msg="cannot find UID/GID for user mysuer: No subuid ranges found for user \"myuser\" in /etc/subuid - check rootless mode in man pages."
17:29:51  time="2022-06-10T17:29:51+02:00" level=warning msg="Using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding sub*ids if not using a network user"
17:29:51  Login Succeeded!

I am running podman rootless on a Kubernetes pod. Podman is running with build user so I have the build user in subuid and subgid

cat /etc/subuid
  build:2000:50000
cat /etc/subgid
 build:2000:50000

But obviously I don't have myuser.

If I run the id command then it shows me build user

id
uid=1000(build) gid=1000(build) groups=1000(build),1000680000

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
Runnig podman build in Kubernetes agent in Jenkins. Some jobs work but other don't work. It is same pod template

**Output of `podman version`:**

```
17:39:28  Version:      3.4.2
17:39:28  API Version:  3.4.2
17:39:28  Go Version:   go1.16.7
17:39:28  Built:        Thu Jan 13 11:15:49 2022
17:39:28  OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
17:39:28  + podman info
17:39:28  host:
17:39:28    arch: amd64
17:39:28    buildahVersion: 1.23.1
17:39:28    cgroupControllers: []
17:39:28    cgroupManager: cgroupfs
17:39:28    cgroupVersion: v1
17:39:28    conmon:
17:39:28      package: conmon-2.0.32-1.module+el8.5.0+13852+150547f7.x86_64
17:39:28      path: /usr/bin/conmon
17:39:28      version: 'conmon version 2.0.32, commit: 4b12bce835c3f8acc006a43620dd955a6a73bae0'
17:39:28    cpus: 20
17:39:28    distribution:
17:39:28      distribution: '"rhel"'
17:39:28      version: "8.2"
17:39:28    eventLogger: file
17:39:28    hostname: overlay-5lwdj
17:39:28    idMappings:
17:39:28      gidmap:
17:39:28      - container_id: 0
17:39:28        host_id: 1000
17:39:28        size: 1
17:39:28      - container_id: 1
17:39:28        host_id: 100000
17:39:28        size: 65536
17:39:28      uidmap:
17:39:28      - container_id: 0
17:39:28        host_id: 1000
17:39:28        size: 1
17:39:28      - container_id: 1
17:39:28        host_id: 100000
17:39:28        size: 65536
17:39:28    kernel: 3.10.0-1160.59.1.el7.x86_64
17:39:28    linkmode: dynamic
17:39:28    logDriver: k8s-file
17:39:28    memFree: 11162042368
17:39:28    memTotal: 84279005184
17:39:28    ociRuntime:
17:39:28      name: runc
17:39:28      package: runc-1.0.3-1.module+el8.5.0+13556+7f055e70.x86_64
17:39:28      path: /usr/bin/runc
17:39:28      version: |-
17:39:28        runc version 1.0.3
17:39:28        spec: 1.0.2-dev
17:39:28        go: go1.16.7
17:39:28        libseccomp: 2.4.1
17:39:28    os: linux
17:39:28    remoteSocket:
17:39:28      path: /tmp/podman-run-1000/podman/podman.sock
17:39:28    security:
17:39:28      apparmorEnabled: false
17:39:28      capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
17:39:28      rootless: true
17:39:28      seccompEnabled: true
17:39:28      seccompProfilePath: /usr/share/containers/seccomp.json
17:39:28      selinuxEnabled: false
17:39:28    serviceIsRemote: false
17:39:28    slirp4netns:
17:39:28      executable: /usr/bin/slirp4netns
17:39:28      package: slirp4netns-1.1.8-1.module+el8.5.0+12582+56d94c81.x86_64
17:39:28      version: |-
17:39:28        slirp4netns version 1.1.8
17:39:28        commit: d361001f495417b880f20329121e3aa431a8f90f
17:39:28        libslirp: 4.4.0
17:39:28        SLIRP_CONFIG_VERSION_MAX: 3
17:39:28        libseccomp: 2.4.1
17:39:28    swapFree: 0
17:39:28    swapTotal: 0
17:39:28    uptime: 1426h 40m 16.43s (Approximately 59.42 days)
17:39:28  plugins:
17:39:28    log:
17:39:28    - k8s-file
17:39:28    - none
17:39:28    - journald
17:39:28    network:
17:39:28    - bridge
17:39:28    - macvlan
17:39:28    volume:
17:39:28    - local
17:39:28  registries:
17:39:28    search:
17:39:28    - registry.fedoraproject.org
17:39:28    - registry.access.redhat.com
17:39:28    - registry.centos.org
17:39:28    - docker.io
17:39:28  store:
17:39:28    configFile: /home/jenkins/.config/containers/storage.conf
17:39:28    containerStore:
17:39:28      number: 0
17:39:28      paused: 0
17:39:28      running: 0
17:39:28      stopped: 0
17:39:28    graphDriverName: vfs
17:39:28    graphOptions: {}
17:39:28    graphRoot: /home/jenkins/.local/share/containers/storage
17:39:28    graphStatus: {}
17:39:28    imageStore:
17:39:28      number: 0
17:39:28    runRoot: /tmp/podman-run-1000/containers
17:39:28    volumePath: /home/jenkins/.local/share/containers/storage/volumes
17:39:28  version:
17:39:28    APIVersion: 3.4.2
17:39:28    Built: 1642068949
17:39:28    BuiltTime: Thu Jan 13 11:15:49 2022
17:39:28    GitCommit: ""
17:39:28    GoVersion: go1.16.7
17:39:28    OsArch: linux/amd64
17:39:28    Version: 3.4.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
@GolanTrevize10 what happens if you specify another user (e.g., `-u foobar`)?

**Comment by GolanTrevize10** [comment]
If I put `-u foobar` then it is trying also to map myuser instead of foobar. Don't understand why. Maybe there is some podman configuration file somewhere

**Comment by vrothberg** [comment]
Thanks for checking, @GolanTrevize10.  So it's not related to the CLI option.

@rhatdan @giuseppe PTAL

**Comment by rhatdan** [comment]
Could you try with a newer version of POdman within the container?  Myuser should not be looked up in /etc/subuid and /etc/subgid.  As a matter of fact podman login should not be entering the user namespace at all.

**Comment by GolanTrevize10** [comment]
Strange thing, if I run `podman info` before `podman login` then it works. I am running podman on ubi8 container and I think the newer version is not available as a package for ubi yet.

**Comment by rhatdan** [comment]
So this looks like podman info created the user namespace, and then podman login can just join it.

**Comment by GolanTrevize10** [comment]
And what can be the reason for that? I tried with podman 4.0.2 and same
issue

**Comment by giuseppe** [comment]
could you please show what is the output of `id` as well as the output of `env`?

**Comment by rhatdan** [comment]
Since we never heard back, I am assuming this is fixed and closing.
