### ISSUE TITLE
`podman events --last`

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#14579]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am seeking a `--last` flag for `podman events` which prints the last event. This could be especially helpful when looking for a specific event of a specific container.

The desire is motivated after having debugged the latest CI failures in https://github.com/containers/podman/pull/14559.  When waiting for the exit file of a container, we may run into the situation where the exit file has already been removed (e.g., via auto-removal).  In this case, Podman has to consult the logs and look at the _last_ exited event of the container which includes the exit code.  As it turns out in https://github.com/containers/podman/pull/14559, Podman is not very efficient in looking up the event, more below.

Instead of reading the events in reverse order (which we can do since we know the container is gone), events are read from head to tail which is extremely expensive and seems to reliably exceed the 90 seconds per-test timeout in the e2e tests.

The `--last` flag should read the events from tail to head and return the first match which would ultimately resolve the performance issue.  I think I can find a workaround in https://github.com/containers/podman/pull/14559 but the solution to the issue is fixing this issue.

NOTE: I marked it as a bug since IMHO it is one.  Hitting the described race (exit file and container removed before reading the exit code) seems to be extremely rare but https://github.com/containers/podman/pull/14559 makes it more likely.

**Comment by vrothberg** [comment]
@mheon FYI

**Comment by vrothberg** [comment]
> So, in theory, what we need to do is rewrite that function such that instead of using the existing events code it uses an alternate algorithm that reads backwards. Unfortunately we'll need separate implementations for Journald and File events.

Yes, that what drove me to generalize it into a new flag/feature. This way, we can properly (and independently) test it.

**Comment by vrothberg** [comment]
Closing as we found an alternative approach.

**Comment by mheon** [comment]
Reopening. We can investigate this as an improvement in the future.

**Comment by vrothberg** [comment]
@mheon, I think we can close as it's not needed anymore.  We can reopen if there's a need in the future.

**Comment by mheon** [comment]
@vrothberg I'm OK with closing, but I don't mind leaving RFEs open. If we have 500 open issues but they're all RFEs I would be quite happy with that.

**Comment by vrothberg** [comment]
>  If we have 500 open issues but they're all RFEs I would be quite happy with that.

I concur.  In this case, I think it's just noise.
