### ISSUE TITLE
Podman cli disconnected from machine

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman#14587]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
/kind bug

**Description**
I have podman and podman desktop installed. Last week I was using the cli and desktop interchangeably.

Today, desktop is working fine and I can start/stop containers or the whole podman machine, but the cli fails and output doesn't help me figure out how to fix it.

**Steps to reproduce the issue:**
Unknown

**Describe the results you received:**
```
my-mac ~ % podman version               
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.0.2/libpod/_ping": dial unix ///var/folders/kl/mjb_x3511yd21w18ht4sz62m0000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory
my-mac ~ % podman system connection list
Name        URI         Identity    Default
my-mac ~ %
```

**Describe the results you expected:**
First, the cli shouldn't 'lose' connection to podman machine.

Second, the output wasn't helpful in helping me determine what the problem is or how to fix it.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.0.2/libpod/_ping": dial unix ///var/folders/kl/mjb_x3511yd21w18ht4sz62m0000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```

**Output of `podman info --debug`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.0.2/libpod/_ping": dial unix ///var/folders/kl/mjb_x3511yd21w18ht4sz62m0000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
% apt list podman
The operation couldn’t be completed. Unable to locate a Java Runtime that supports apt.
Please visit http://www.java.com for information on installing Java.
```
(I have multiple versions of Java installed...)

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

As far as I know I have the latest version, and didn't see anything that looked like it matched while scanning the troubleshooting guide.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Macbook M1 with macOS 12.4

**Comment by mheon** [comment]
@ashley-cui PTAL

**Comment by ashley-cui** [comment]
This looks extremely strange, because without a connection, there shouldn't be a way to communicate to the machine at all, so Desktop shouldn't be working either.. I'm not quite sure what's going on here ATM

**Comment by Luap99** [comment]
The connections are stored in `~/.config/containers/containers.conf` (at least on linux not sure about macos). I guess something removed or changed this file?

**Comment by baude** [comment]
does machine ls show it running? what does inspect show?

**Comment by deboer-tim** [comment]
`podman machine list` shows what I would expect:
```
NAME                    VM TYPE     CREATED       LAST UP            CPUS        MEMORY      DISK SIZE
podman-machine-default  qemu        3 months ago  Currently running  1           2.147GB     107.4GB
my-machine              qemu        2 months ago  2 months ago       1           1.074GB     107.4GB
```
I don't know what 'inspect' is.

I just remembered that I tried an early M1 podman installer from the CRC team a couple weeks ago that failed, so maybe that's related? (ping me if you want a link to the internal slack) Even assuming that is the cause though, I can't understand how I'd end up with a failing cli but underlying machine and socket still working perfectly.

**Comment by ashley-cui** [comment]
Try `podman machine inspect podman-machine-default`

**Comment by deboer-tim** [comment]
I had checked --help (inspect isn't listed as a command) and tried combinations like that, but it's not there:
```
Error: unrecognized command `podman machine inspect`
Try 'podman machine --help' for more information.
```
Assuming the missing command is a red flag that I've somehow gotten a back-level cli?

**Comment by Luap99** [comment]
Update to podman v4.1 for the inspect command.
Please check the containers.conf content as mentioned above. Most likely it was removed?!

**Comment by Luap99** [comment]
Well containers.conf is there but it is missing the connection settings.
`podman machine rm` followed by `podman machine init` should make it work.

I guess it got replaced by the experimental CRC installer you were mentioning.
@gbraad FYI

**Comment by deboer-tim** [comment]
Not out of the woods yet?

I'm sad b/c the running machine is working perfectly fine and has containers deployed that I was using; I'd rather just keep using it. But ok, I figured I'd delete my second machine and create another one. EOF error during creation. It seems to be created ok (and is in containers.conf now), but won't start:
```
% podman machine init another-one
Downloading VM image: fedora-coreos-36.20220605.2.0-qemu.aarch64.qcow2.xz: done  
Extracting compressed file
Error: EOF
% podman machine list            
NAME                    VM TYPE     CREATED             LAST UP             CPUS        MEMORY      DISK SIZE
podman-machine-default  qemu        19 minutes ago      Currently running   1           2.147GB     107.4GB
another-one*            qemu        About a minute ago  About a minute ago  1           2.147GB     107.4GB
% podman machine start another-one
Starting machine "another-one"
Waiting for VM ...
Error: dial unix /var/folders/kl/mjb_x3511yd21w18ht4sz62m0000gn/T/podman/another-one_ready.sock: connect: no such file or directory
```
Took a look in podman desktop, it thinks the socket is `/Users/deboer/.local/share/containers/podman/machine/another-one/podman.sock`, but can't start it either.

**Comment by gbraad** [comment]
What I do not understand is how the overwritten `containers.conf` leads to removal of the connections.
Are these persisted inside the main config?

**Comment by Luap99** [comment]
Yes, system connections are stored in `~/.config/containers/containers.conf`

**Comment by gbraad** [comment]
would it not be better to store those as part of `$HOME/.config/containers/containers.conf.d/` to preserve them?

**Comment by rhatdan** [comment]
Yes, but I think this change predates the conf.d stucture.  Having connections moved to a drop in makes sense.

**Comment by Luap99** [comment]
Connections are only sourced from `~/.config/containers/containers.conf` as rootless or `/etc/containers/containers.conf` as root.
When the file is written it adds the connection to the current settings and does not overwrite the file so it should work fine for podman. I am not sure if there is much benefit changing this behaviour given the the amount of work needed.

If this should be changed we should just avoid using containers.conf as "db" entirely and use a different file for only connections instead.

**Comment by gbraad** [comment]
> If this should be changed we should just avoid using containers.conf as "db" entirely and use a different file for only connections instead.

Where would this file be located and what would it be called?

**Comment by Luap99** [comment]
> > If this should be changed we should just avoid using containers.conf as "db" entirely and use a different file for only connections instead.
> 
> Where would this file be located and what would it be called?

I don't know, it could be in the same ~/.config/containers directory. My point is that automatically editing user config files is a bad idea. At least we will remove the comments every time a connection is created.

**Comment by slemeur** [comment]
FWIW, I faced the same issue.

**Comment by rhatdan** [comment]
Since  ~/.config/containers/containers.conf.d/ is now supported is this still an issue?

**Comment by anjannath** [comment]
No this will not happen anymore, we don't write to the config file, the helper binaries location is set at build time https://github.com/containers/podman/blob/468aa6478c73e4acd8708ce8bb0bb5a056f329c2/contrib/pkginstaller/package.sh#L24

**Comment by deboer-tim** [comment]
Ok, thanks for the help and all the information! Closing.
