### ISSUE TITLE
Proxy support for podman machine on Windows

### ISSUE THREAD

**Issue by Sebbiedu** [containers/podman#14589]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Description
I used the podman-v4.1.0.msi to install podman on windows.
I'm sitting behind a corporate proxy.
I open the terminal and set the environment variables
- $env:http_proxy="<corporate-proxy"
- $env:https_proxy="<corporate-proxy"

I type podman machine init

Describe the results you received:

It downloads the fedora image so initially proxy works but then in endless loop

Fedora 35 - x86_64                                                                             0.0  B/s |   0  B     03:21

So proxy isnt set for curl as it looks.

After ctrl+c

Curl error (7): Couldn't connect to server for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [Failed to connect to mirrors.fedoraproject.org port 443 after 20157 ms: Connection refused]

It seems there is no proxy set for installing updating packages

**Comment by MissaouiChedy** [comment]
I am having the same issue/feature request:
- Podman v4.1.1
- Windows 10
- Running behind a corporate proxy

After setting the `HTTP_PROXY` env var in Powershell `podman machine init` **fails to download the packages.**

**Comment by gbraad** [comment]
using the version on current master (merged #14806)

To confirm the proxy is reachable and working I check the following from the podman VM.
```
PS> wsl -d podman-machine-default
# curl https://postman-echo.com/get\?foo\=bar -x 10.0.21.80:3213
{"args":{"foo":"bar"},"headers":{"x-forwarded-proto":"https","x-forwarded-port":"443","host":"postman-echo.com","x-amzn-trace-id":"Root=1-62c522eb-54dfd52477b4468531e323bf","user-agent":"curl/7.82.0","accept":"*/*"},"url":"https://postman-echo.com/get?foo=bar"}%
# exit
PS> podman machine stop
```

To setup the proxy variables and start the environment
```
PS> $env:http_proxy="10.0.21.80:3213"
PS> $env:https_proxy="10.0.21.80:3213"
PS> podman machine start
Starting machine "podman-machine-default"
Installing proxy support
...
```
Note that the message `Installing proxy support` is shown.

After which:
```
PS> wsl -d podman-machine-default
# cat /etc/profile.d/default-env.sh
export http_proxy="10.0.21.80:3213"
export https_proxy="10.0.21.80:3213"
export HTTP_PROXY="10.0.21.80:3213"
export HTTPS_PROXY="10.0.21.80:3213"
# curl https://postman-echo.com/get\?foo\=bar
# podman pull fedora
```

should work with proxy

**Comment by gbraad** [comment]
@n1hility The message `Installing proxy support` is not shown on successive starts, even with new values. This is because the `proxyConfigAttempt` is passing. Perhaps to allow the write values to be logged?

**Comment by gbraad** [comment]
On Windows you can quickly test this:
```
PS> git clone https://github,com/elazarl/goproxy
PS> go run .\examples\goproxy-basic\main.go -v
```

Open another terminal session
```
PS> $env:http_proxy="10.0.21.80:8080"
PS> $env:https_proxy="10.0.21.80:8080"
PS> podman machine start
PS> wsl -d podman-machine-default
# podman pull fedora:latest
```

You should see the incoming `CONNECT` request for HTTPS:

![image](https://user-images.githubusercontent.com/1894/177499343-5e71c684-62db-470e-9e4f-7c235a76b78e.png)

If you would break the proxy in the first session the connection should be interrupted.

**Comment by jolyons123** [comment]
> @n1hility The message `Installing proxy support` is not shown on successive starts, even with new values. This is because the `proxyConfigAttempt` is passing. Perhaps change to log when writing the values?
> 
> ```powershell
> PS> $env:http_proxy="10.0.21.80:3213"
> PS> $env:https_proxy="10.0.21.80:3213"
> PS> podman machine start
> Starting machine "podman-machine-default"
> Installing proxy support
> ...
> Machine "podman-machine-default" started successfully
> PS> wsl -d podman-machine-default cat /etc/profile.d/default-env.sh
> export http_proxy="10.0.21.80:3213"
> export https_proxy="10.0.21.80:3213"
> export HTTP_PROXY="10.0.21.80:3213"
> export HTTPS_PROXY="10.0.21.80:3213"
> PS> podman machine stop
> Machine "podman-machine-default" stopped successfully
> PS> $env:https_proxy="10.0.21.120:3213"
> PS> $env:http_proxy="10.0.21.120:3213"
> PS>  .\podman.exe machine start
> Starting machine "podman-machine-default"
> ...
> Machine "podman-machine-default" started successfully
> PS> wsl -d podman-machine-default cat /etc/profile.d/default-env.sh
> export http_proxy="10.0.21.120:3213"
> export https_proxy="10.0.21.120:3213"
> export HTTP_PROXY="10.0.21.120:3213"
> export HTTPS_PROXY="10.0.21.120:3213"
> ```
> 
> No intermediate message for the proxy values was shown. Though when someone is experimenting or trying to make it work, this information could be helpful.

Thanks! Do you have any advice on how to find out the Windows host IP within the podman VM? I am using cntlm on windows and it listens on localhost:3128 . I tried the command you posted but there is no response, I assume that the IP does not match in my case
