### ISSUE TITLE
podman volume list, filtering by wildcard in name

### ISSUE THREAD

**Issue by bertmelis** [containers/podman#14583]
/kind bug

**Description**

According to the [docs](https://github.com/containers/podman/blob/main/docs/source/markdown/podman-volume-ls.1.md) you can use a regex/wildcard for filtering `podman volume list` by name.

**Steps to reproduce the issue:**

```
[user@server ~]$ podman volume create testvolume_1
testvolume_1
[user@server ~]$ podman volume create testvolume_2
testvolume_2
[podmanager@server ~]$ podman volume list --filter name=testvolume*
<emtpy>
```

**Describe the results you expected:**
```
[podmanager@server ~]$ podman volume list --filter name=testvolume*
DRIVER      VOLUME NAME
local       testvolume_1
local       testvolume_2
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7

Built:      Sun May 15 18:45:11 2022
OS/Arch:    linux/amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Comment by rhatdan** [comment]
This works on Docker, so we should fix.

@ashley-cui @vrothberg @mheon @umohnani8 Need an intern for this.
