### ISSUE TITLE
Some keypresses interpretted wrongly in podman machine (mac os)

### ISSUE THREAD

**Issue by apkumar** [containers/podman#14590]
/kind bug

**Description**

Some keypresses do not get passed through to the VM correctly. In my case, for example, Ctrl-M gets passed through as enter.

**Steps to reproduce the issue:**

1. Run podman machine ssh

2. Enter keypresses (e.g ctrl-M)

3. See that the keypress is interpretted incorrectly

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.1.0
API Version:  4.1.0
Go Version:   go1.18.1
Built:        Thu May  5 16:07:47 2022
OS/Arch:      darwin/amd64

Server:       Podman Engine
Version:      4.1.0
API Version:  4.1.0
Go Version:   go1.18
Built:        Fri May  6 12
```

**Output of `podman info --debug`:**

```
Client:       Podman Engine
Version:      4.1.0
API Version:  4.1.0
Go Version:   go1.18.1
Built:        Thu May  5 16:07:47 2022
OS/Arch:      darwin/amd64

Server:       Podman Engine
Version:      4.1.0
API Version:  4.1.0
Go Version:   go1.18
Built:        Fri May  6 12:15:54 2022
OS/Arch:      linux/amd64
Ankits-MacBook-Air:src ankitkumar$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpuUtilization:
    idlePercent: 98.72
    systemPercent: 0.95
    userPercent: 0.33
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "36"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 5.17.5-300.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 353243136
  memTotal: 2066817024
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.4-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.4
      commit: 6521fcc5806f20f6187eb933f9f45130c86da230
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/501/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 26h 38m 27.55s (Approximately 1.08 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 2
    stopped: 2
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106825756672
  graphRootUsed: 4903301120
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/user/501/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.0
  Built: 1651853754
  BuiltTime: Fri May  6 09:15:54 2022
  GitCommit: ""
  GoVersion: go1.18
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.0
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

macbook air

**Comment by apkumar** [comment]
It seems that some programs are having a hard time interpretting these characters differently. For example, in docker vim can interpret control-m and handle it different (I use control m as a keybind)

**Comment by mtrmac** [comment]
> It seems that some programs are having a hard time interpretting these characters differently.

“some programs” are hard to investigate without a specific isolated reproducer. What commands, what versions, …?

---

The next steps here would be to track the differences in `stty [-f $TTY] -a` on all the relevant (pseudo)terminal devices at that time, vaguely:
- on the host, run `tty` (call that $TTY_HOST)
- Invoke the remote command, whatever it is (`vim`?)
- On the macOS host, run `stty -f $TTY_HOST -a`
- With the remote command still running, connect inside the machine using a separate connection
- On the machine VM, figure out which TTY is used by the remote `vim` command (using e.g. `ps` + `ls -la /proc/$PID/fd`); call that $TTY_MACHINE
- On the machine VM, run `stty -F $TTY_MACHINE -a`

And then compare the flags between Podman and Docker, both on the host, and inside the VM; in particular pay attention to the `icrnl` and `inlcr` flags (which affect mapping between CR and NL).

That would, at least, allow identifying whether it’s the host-level TTY or the machine VM TTY that is set incorrectly.

**Comment by mtrmac** [comment]
Testing this, already on macOS in the standard Terminal.app:
```console
% (save_state=$(stty -g); stty raw; xxd -g1 -l10; f=$(stty -a); stty "$save_state"; echo "$f")
0d 0a 0d 61 61 61 61 61 61 61
```
(pressing Ctrl-M, Ctrl-J, Enter, aaaaa…)

I.e. the Enter key _generates_ Ctrl-M (which is, to my knowledge, correct and traditional). Already at that point there is no distinction between Ctrl-M and Enter, so `podman machine` running in that terminal couldn’t possibly differentiate between the two.

**Comment by Luap99** [comment]
Closing based on @mtrmac answer.
