### ISSUE TITLE
Podman should detect and warn when used with su/sudo

### ISSUE THREAD

**Issue by mheon** [containers/podman#14603]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

One of the most persistent issues we see reported is people using rootless Podman with `sudo` or `su`, resulting in a bad environment (environment variables being set incorrectly or not at all, missing login session, and many other issues) that prevents Podman from running. We're fielding a few of these issues every month, which means it is almost certainly worth our time to consider a solution in the code. We can't fix the environment ourselves, but we can at least feed the user meaningful errors when Podman is used in an environment where we cannot run sanely.

In a discussion with Valentin, he suggested that it could be worth looking at `XDG_RUNTIME_DIR` and checking to make sure that, if it points at `/run/user/$UID/`, that UID is actually the UID of the user running Podman - `XDG_RUNTIME_DIR=/run/user/0` when running as UID 1000 would print an error for the user, for example.

I'm sure there are other things we can do here as well, to detect common failure cases and warn the user about them.

**Comment by Luap99** [comment]
Sounds like a good idea to make this more obvious to end users. AFAIK we already have a check for a non writeable XDG_RUNTIME_DIR.

IMO the bigger problem is that we automatically fall back to /tmp/podman... when XDG_RUNTIME_DIR is not set. This is causing issues when /tmp is not a tmpfs. The problem is also that it is enough to do it incorrectly on first podman command since afterwards these paths are stored in the db.

**Comment by flouthoc** [comment]
Afaik we did a warn for cases where XDG_RUNTIME_DIR is set but not write-able https://github.com/containers/podman/pull/11327

**Comment by giuseppe** [comment]
the hack we have for `/tmp` was mostly because we wanted to allow podman in a nested container without any conf change.

Perhaps we can fallback to `/tmp` only when the `container` env variable is set

**Comment by rhatdan** [comment]
@giuseppe want to make that change, or would that be a breaking change?

**Comment by giuseppe** [comment]
I am in favor of this change, but let's permit the fallback when the env variable `container` is defined so we don't break nested podman

**Comment by flouthoc** [comment]
I am not entirely sure but could we check if `pid 2` is `kthreaded` or does not exists, maybe something like check if `/proc/2/status` does not contains `kthreaded` it can be assumed that this is running inside a container. Ref: https://stackoverflow.com/a/72136877

Still I am not sure so another approach could be to maintain a check list for known container manager like `docker` containers contains `.dockerenv` and so on.

**Comment by giuseppe** [comment]
could it work if we just check the file system type for `/run`?  If it is not a tmpfs then we use the fallback to `/tmp`

**Comment by rhatdan** [comment]
@mheon @Luap99 @giuseppe Any movement on this?

**Comment by vrothberg** [comment]
Bump.  Just crossed this issue again with people reaching out why rootless fails but rootful works.  A warning would really be great improvement.

**Comment by rhatdan** [comment]
I agree, can we just look at the environment settings and tell?

**Comment by noelmiller** [comment]
Do we have a technical write-up (or quick explainer) as to why `su` or `su -` to a different user does not configure the environment correctly as it does when you ssh or log in directly as the user? I just find this to be a very strange behavior as I haven't run into issues with other programs in the past when using `su`.

**Comment by rhatdan** [comment]
Well it is caused by the pam configurations not using libsystemd, I believe.  I am sure this was documented somewhere why su and sudo do not setup full login sessions.

**Comment by noelmiller** [comment]
I see, I found a serverfault article discussing something similar: https://serverfault.com/questions/892465/starting-systemd-services-sharing-a-session-d-bus-on-headless-system#:~:text=The%20lightweight%20environments%20created%20by%20su%20-..%20--login,a%20full%20systemd%20environment%20in%20your%20current%20shell.

Important bit: 

"For systemctl --user .. to work, you need to have a full systemd login environment for the /run/user/{uid} to exist. The lightweight environments created by su - .. --login or sudo do not set this up. You need to ssh in, log into a console or, if you run a properly set up systemd distribution, you can grab and use machinectl shell to create a full systemd environment in your current shell."

**Comment by noelmiller** [comment]
I have found a workaround which does not require using `su` or `su -` and instead using `machinectl shell`.

On a RHEL 8 System:
```bash
# Install systemd-container package (this provides the machinectl package for RHEL 8)
yum install systemd-container

# Run machinectl shell for the user you want to switch to (example bob)
machinectl shell bob@.host

# You should now have an interactive session for the user. 
# This should properly map your $XDG_RUNTIME_DIR to the correct user
echo $XDG_RUNTIME_DIR
/run/user/$uid

# Running your container should now work!
```

All this being said, I still think it would be important to have a warning provided by podman when `su`ed into a different user account and attempting to run podman.

**Comment by vrothberg** [comment]
Thanks for sharing, @noelmiller!

I agree that Podman should log a warning.  @mheon can we schedule working on this?  I think we'll save time on the long run as it's a frequent trap users step into.

**Comment by mheon** [comment]
Sure.

**Comment by vrothberg** [comment]
@mheon @baude @rhatdan this issue keeps popping up when debugging user/customer issues.  Recently when looking into some Ansible issue.  Warning users when running in an incomplete login session could save a lot of debugging time.

**Comment by mheon** [comment]
I'll get a card made up and start agitating about priority. Can't promise it before 5.1, but it does seem like a good 5.1 feature candidate?

**Comment by rhatdan** [comment]
SGTM

**Comment by mheon** [comment]
I think we can close this now, Podman 5.1 will detect improperly-handled reboots (which is the main reason not having a tmpfs is problematic).

**Comment by vrothberg** [comment]
> I think we can close this now, Podman 5.1 will detect improperly-handled reboots (which is the main reason not having a tmpfs is problematic).

Can you share the PR?  I don't see how addressing improper reboots would address the issue, so I am curious.  To me, the main source of the issue is using `su` to change to another user and running in an incomplete login session.

**Comment by Luap99** [comment]
I don't think it will solve the issue fully, but what it does fix is the improper /tmp is not cleared and thus causes all kind of weird things which was one symptom of su/sudo as they did not use the proper /run/user/... tmpdir paths
https://github.com/containers/podman/pull/22278

However this fix will kick in to late IMO as it requires a full reboot before the users known they did something "wrong" and the runroot/tmpdir are part of the db and will not change until they run podman system reset which is a bad user experience.
