### ISSUE TITLE
podman machine init command with proxy on macOS

### ISSUE THREAD

**Issue by benoitf** [containers/podman#14604]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Trying to use podman machine init command behind a proxy

I'm able to have something that work if I add the https_proxy variable on the command line

But I would like to specify proxy settings in the `~/.config/containers/containers.conf` file

**Steps to reproduce the issue:**

1. add env variable in  `~/.config/containers/containers.conf` file
```
 [containers]
  env = ["https_proxy=http://10.0.0.244:9090"]
```

based on https://github.com/containers/common/blob/main/pkg/config/containers.conf

2. launch podman machine init command

3. podman machine init test                  
Error: Get "https://fedorapeople.org/groups/podman/testing/podman4.json": dial tcp 152.19.134.199:443: i/o timeout

**Describe the results you received:**
Error

**Describe the results you expected:**
Should be able to use proxy settings

Using the way
```
https_proxy=http://10.0.0.244:9090 podman machine init test
Extracting compressed file
```
is working but I would like to configure the proxy once for it in the containers.conf and do not want to have to export env variable/etc before each podman command

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version
Client:       Podman Engine
Version:      4.1.0
API Version:  4.1.0
Go Version:   go1.18.1
Built:        Thu May  5 22:07:47 2022
OS/Arch:      darwin/amd64

Server:       Podman Engine
Version:      4.1.0
API Version:  4.1.0
Go Version:   go1.18
Built:        Fri May  6 18:15:54 2022
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@ashley-cui PTAL

**Comment by Luap99** [comment]
The `[containers]` section is for containers settings only. Try using `env` under the `[engine]` section.

**Comment by benoitf** [comment]
@Luap99 adding `env` in [engine] is working 👍 

might be good to have it illustrated in https://github.com/containers/common/blob/main/pkg/config/containers.conf as well.

**Comment by rhatdan** [comment]
You mean mention in the container ENV section, that there is a Engine ENV section and vice-versa.  Explain the difference in both places.
