### ISSUE TITLE
Version specific command line reference

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman#14607]
/kind feature

**Description**
The Podman command reference only shows the latest cli, and includes commands that weren't available in the previous version. Sometimes companies need to stick on a version for a while (a few months, or even a year) and there should be a way to view matching documentation.

**Steps to reproduce the issue:**
Go to podman.io, Documentation > Commands.

**Describe the results you received:**
The documentation lists a `podman machine inspect` that didn't exist in 4.0x (which is what I'm assuming I still have; version command is broken).

**Describe the results you expected:**
Defaulting to the current/latest release is fine, but there should be a way to view commands from previous major versions, especially when previous = "last month".

If that's not possible, assuming the command line is always backward compatible it would be enough to include tags like "Added in 4.1" to anything new.

**Comment by Luap99** [comment]
https://docs.podman.io allows you to change the version in the lower right corner.

**Comment by deboer-tim** [comment]
🤦🏼‍♂️ I'll admit I'm an idiot, but any chance we could spell out 'version' or make it more prominent? I even looked for an option like this but it was not prominent/obvious enough.

**Comment by Luap99** [comment]
This is the default readthedocs behaviour AFAIK. I have no idea if this can be changed but I agree that it is not very obvious.

**Comment by rhatdan** [comment]
Since the docs.podman.io allows you to change the version I don't see us changing it, unless someone comes in with a way to make it more prominant.
