### ISSUE TITLE
podman image rm -f returns an status code of 1 when it should return 0

### ISSUE THREAD

**Issue by crowleydi** [containers/podman#14612]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

If you run `podman image rm -f non_existent_image` and the image doesn't exist, it returns a status code of 1.
If you run `docker image rm -f non_existent_image` and the image doesn't exist, it returns a status code of 0.

For scripting compatibility between `docker` and `podman`, `podman` should return a status code of 0 for this situation. That is one of the points of specifying `-f`.

**Steps to reproduce the issue:**

1. `podman image rm -f foobar`

2. `echo $?`

**Describe the results you received:**

return code is 1
**Describe the results you expected:**
return code should be 0

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 4.1.1
```

affects older versions as well
```
podman version 3.4.2
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

RHEL 8 VM, Mac OSX

**Comment by vrothberg** [comment]
Thanks for reaching out, @crowleydi.

@containers/podman-maintainers WDYT?

**Comment by rhatdan** [comment]
I think Docker is correct, as long as when the command ends the images is gone, with --force podman should exit with 0.

**Comment by rhatdan** [comment]
We should not just do containers either

```
sh-5.1# docker rmi --force bogus; echo $?
Error: No such image: bogus
0
sh-5.1# podman rmi --force bogus; echo $?
Error: bogus: image not known
1
```

```
sh-5.1# podman volume rm --force bogus; echo $?
Error: no volume with name "bogus" found: no such volume
1
sh-5.1# docker volume rm --force bogus; echo $?
bogus
0
```

docker network rm does not support --force, but we should exit with 0.
``` 
sh-5.1# podman network rm --force bogus; echo $?
Error: unable to find network with name or ID bogus: network not found
1
sh-5.1# docker network rm --force bogus; echo $?
unknown flag: --force
See 'docker network rm --help'.
125
sh-5.1# docker network rm bogus; echo $?
Error: No such network: bogus
1
```

podman pod rm --force
Should exit with 0.

This calls for interns to fix up. Or if @crowleydi wants to open a PR.  Hint Hint.

**Comment by maknop** [comment]
Could I take a shot at this one?

**Comment by vrothberg** [comment]
> Could I take a shot at this one?

Sure, thank you!

**Comment by rhatdan** [comment]
@maknop @aonoa What is the status on this?

**Comment by maknop** [comment]
I thought I was going to have some time to work on this but I was wrong. I'll remove myself.
