### ISSUE TITLE
Cirrus: rootless remote system test: "I see everything thrice!"

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#14623]
The `sys remote fedora-36 rootless host` task is running three times:

![sys-sys-sys](https://user-images.githubusercontent.com/265639/174135153-c0aa12d5-f92c-4f48-9a97-a91d7a58feaa.png)

I suspect this has something to do with `matrix` or something like that. I can probably look into it next week, but I bet it's something very easy for @cevich to find and fix, and maybe it'll magically be solved by next week :)

**Comment by edsantiago** [comment]
This is a problem because sometimes one of those will flake and will block merging. It's also a problem because time & energy waste.

**Comment by cevich** [comment]
This looks like some kind of parsing bug.  Contacting Cirrus-support about it...
