### ISSUE TITLE
Feature request: Expose raw cgroup paths for container stats

### ISSUE THREAD

**Issue by bduffany** [containers/podman#14630]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I would like to directly access cgroup paths to get container stats rather than using `podman stats`, because
* I want to get only the stats I need
* I want to avoid the overhead of having a subprocess (`podman stats`)
* I want to avoid having to parse the output of `podman stats` (even with `--format=json`, the output needs parsing, since it prints human-readable abbreviations).
* I need to sample stats at a higher rate than `podman stats` allows (as far as I can tell, podman stats can sample only at most once per second -- specifying a decimal value like `--interval=0.1` doesn't work, and neither does a `time.Duration` value like `--interval=100ms`)

But it is hard to know where to look, because `podman system info` and `podman container inspect` don't expose the full cgroup paths.

Hard-coding the cgroup path is not super feasible because it depends on a number of dimensions: rootfull vs. rootless, systemd vs. cgroupfs, cgroupv1 vs. cgroupv2.

I would love if the cgroup paths were somehow exposed by podman, either via `podman container inspect` or `podman stats`. Preferably in such a way that I could write functions like `GetCPUUsageNanos(containerID string)` and `GetMemoryUsageBytes(containerID string)` and avoid spinning up a subprocess for these (assuming I precomputed the path template using something like `podman system info`, which could then show something like `cgroupPathTemplate: /sys/fs/cgroup/{{.Controller}}/libpod_parent/libpod-{{.ContainerID}}`

**Comment by giuseppe** [comment]
could you read this information from `/proc/$CONTAINER_PID/cgroup`?

e.g.

```
$ podman run --name foo --rm -d alpine top
$ cat /proc/$(podman inspect --format '{{.State.Pid}}' foo)/cgroup
0::/user.slice/user-1000.slice/user@1000.service/user.slice/libpod-abddba1ad07338f5ae4c9d64dd54d3513dd7c06c211dc6d627f9c32179415dd0.scope/container
```

**Comment by bduffany** [comment]
That mostly works, but that `cgroup` file doesn't include the absolute cgroup path, which IIUC can vary (e.g. it can be either `/sys/fs/cgroup` or `/sys/fs/cgroup/unified` depending on the distro?)

**Comment by giuseppe** [comment]
> Thanks for the quick reply! That mostly works, but that `cgroup` file doesn't include the absolute cgroup path, which IIUC can vary depending on the system (e.g. `cgroup2` can be mounted to either `/sys/fs/cgroup` or `/sys/fs/cgroup/unified` depending on the distro -- for example ubuntu 20.04 has cgroup2 mounted to `/sys/fs/cgroup/unified` in my testing but ubuntu 22.04 has cgroup2 mounted to `/sys/fs/cgroup`). (Also I'm not sure whether it depends on systemd vs cgroupfs?)
> 
> Given that figuring this out is a bit complex and `podman` is the source of truth for the full cgroup path anyway (for example, what happens if there are 2 different cgroup2 mounts on the system? podman will pick one of the two), it'd be super handy if podman could expose the actual paths that it chose. Or if there is some other way to figure out the full cgroup path for a PID, that'd also work

when the mount exists at `/sys/fs/cgroup/unified`, then the system is using a hybrid mode with both cgroupv1 and cgroupv2 mounted.  This configuration is not supported by Podman and most other container tools.

cgroupv2 is used only when the following condition is met:

```
$ stat -f -c %T /sys/fs/cgroup
cgroup2fs
```

Another way would be to use the CgroupPath returned by `podman inspect`:

```
$ podman inspect -l -f '{{.State.CgroupPath}}'
/user.slice/user-1000.slice/user@1000.service/user.slice/libpod-d20e74d50664b6213c973940a937e90c8891b1b78012b435bd4047221042b582.scope
```

In this case, you would have to prepend `/sys/fs/cgroup` when `$(stat -f -c %T /sys/fs/cgroup) == cgroup2fs` or `/sys/fs/cgroup/$CONTROLLER` on cgroup v1

**Comment by bduffany** [comment]
@giuseppe Ah, I guess `{{.State.CgroupPath}}` is the piece of the puzzle I was missing. Looks like that is not present in the version of podman I am using (3.4.2), but I see that it's there in 4.1.1. Thank you!
