### ISSUE TITLE
podman commands fail when run as non-root user with "Error: cannot re-exec process"

### ISSUE THREAD

**Issue by guits** [containers/podman#14635]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1.  I'm not sure how to reproduce this issue, it has suddenly begun to show up on nodes that are part of a Jenkins CI

**Describe the results you received:**
```
$ podman ps -a
Error: cannot re-exec process
$
```

**Describe the results you expected:**
```
$ podman ps -a
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
$
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7

Built:      Tue Mar 15 19:15:06 2022
OS/Arch:    linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.0-1.module_el8.7.0+1106+45480ee0.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 235fd1687e002bf8eaa7ea2f999104be869858b4'
  cpus: 8
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: smithi054
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-240.el8.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 18222190592
  memTotal: 33399689216
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.0.3-3.module_el8.7.0+1106+45480ee0.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.3
      spec: 1.0.2-dev
      go: go1.17.7
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.1.8-2.module_el8.7.0+1106+45480ee0.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 0
  swapTotal: 0
  uptime: 1210h 57m 12.97s (Approximately 50.42 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  docker.io:
    Blocked: false
    Insecure: false
    Location: docker.io
    MirrorByDigestOnly: false
    Mirrors:
    - Insecure: false
      Location: docker-mirror.front.sepia.ceph.com:5000
    Prefix: docker.io
  search:
  - docker.io
  - registry.access.redhat.com
  - registry.centos.org
  - registry.fedoraproject.org
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1647371706
  BuiltTime: Tue Mar 15 19:15:06 2022
  GitCommit: ""
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.0.2-1.module_el8.7.0+1106+45480ee0.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

The latest version available of podman is 4.0.2 on my system.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

seen on a physical machine running CentOS Stream 8 (the system is up-to-date)

```
$ sudo dnf update
Last metadata expiration check: 0:06:30 ago on Fri 17 Jun 2022 04:49:35 AM UTC.
Dependencies resolved.
Nothing to do.
Complete!
```
no containers are running and the system isn't running under a high load.

I thought it could be https://github.com/containers/podman/issues/13737 but I don't see any `pause.pid` file in `/run/user` :

```
$ id -u
10102
$ find /run/user/10102/ -name "*.pid"
$ sudo find /run/user/ -name "*.pid"
$
```

so I'm opening a new issue for that. Let me know if I have to share any other detail.

**Comment by Luap99** [comment]
can you strace the process with `strace -f podman ps -a`

**Comment by giuseppe** [comment]
do you have any file under `/run/containers/storage` (as it seems to be the runroot path from the info you posted above)?

**Comment by guits** [comment]
```
# ls -l /run/containers/storage/*
/run/containers/storage/overlay:
total 4
-rw-r--r--. 1 root root   0 May  9 08:27 'metacopy(nodev,metacopy=on)-true'
-rw-r--r--. 1 root root 141 May  9 08:27 'native-diff(nodev,metacopy=on)-false'
-rw-r--r--. 1 root root   0 May  9 08:27  overlay-true

/run/containers/storage/overlay-containers:
total 0

/run/containers/storage/overlay-layers:
total 0
-rw-r--r--. 1 root root 0 May  9 08:27 mountpoints.lock

/run/containers/storage/overlay-locks:
total 0
```

**Comment by guits** [comment]
> can you strace the process with `strace -f podman ps -a`

[strace_podman_ps_-a.log](https://github.com/containers/podman/files/8927210/strace_podman_ps_-a.log)

**Comment by giuseppe** [comment]
I've opened a PR that could help to understand what is going on here: https://github.com/containers/podman/pull/14638

**Comment by giuseppe** [comment]
the problem with strace is that `newuidmap/newgidmap` will fail since they are traced, so the error we are seeing is probably caused by that.

Could you try to strace the parent process (the shell where you run the podman command in) as root (`sudo strace -v -s 10000 -f -p $PARENT_PID`)?

**Comment by strluck** [comment]
[https://github.com/containers/podman/issues/9137#issuecomment-771859402](https://github.com/containers/podman/issues/9137#issuecomment-771859402)
This worked for me but the path of `pause.pid` is in `/tmp/podman-run-1000/libpod/tmp/pause.pid`. Maybe you can find for `pause.pid` in `tmp`.

**Comment by guits** [comment]
sorry i didn't update that issue before but yes, it turns out `pause.pid` was in `/tmp` too in my case.
@giuseppe suspects this is because the machine running podman was probably provisioned with a 'golden image'.

**Comment by enyineer** [comment]
Deleting the pid-file is also a workaround for us. But this is only temporary and it sporadically happens again. We do have multiple build agents running a lot of jobs, which is why it happens more often. Might have to open an official business-case bug-ticket with RedHat soon if nobody has an idea how to permanently fix this...

**Comment by guits** [comment]
> Deleting the pid-file is also a workaround for us. But this is only temporary and it sporadically happens again. We do have multiple build agents running a lot of jobs (also Jenkins), which is why it happens more often. 

indeed, the situation I'm facing is quite similar. I had to do something like this [1] to work around this issue.

[1] https://github.com/ceph/ceph-container/commit/a0d1e714aaa813db6cdf15a4a6ea87ba9525d803

**Comment by enyineer** [comment]
This is kind of the same workaround we do use. But still, this is only a workaround and podman sporadically breaks our build pipelines stopping the devs from being able to work thus costing money until the workaround script was started. We do need a permanent fix for this.

**Comment by giuseppe** [comment]
please provide the output of `podman info` from the same environment where the issue appears.

In the original issue, I see the `podman info` output when it is executed as root, but the error is clearly happening as rootless in a different environment.

**Comment by rhatdan** [comment]
Since we never heard back, I am closing this issue,  Reopen if you have feedback for @giuseppe
