### ISSUE TITLE
containers list api route response header is text/plain instead of application/json

### ISSUE THREAD

**Issue by iongion** [containers/podman#14647]
/kind bug

**Description**

Response content-type header is not `application/json` for containers list endpoint, although negotiation requests it.
Some client libraries do attempt deserializing automatically to their data structures. Although it can be mitigated as an exception for this route, it should respect the negotiation. (v3 and v4 have the same behavior)

**Steps to reproduce the issue:**

1. base url `v3.0.0`  -  `curl -v -X GET --unix-socket "/run/user/1000/podman/podman.sock" "http://d/v3.0.0/libpod/containers/json" -H "Accept: application/json" -H "Content-Type: application/json"`

2. base url `v4.0.0`  -  `curl -v -X GET --unix-socket "/run/user/1000/podman/podman.sock" "http://d/v4.0.0/libpod/containers/json" -H "Accept: application/json" -H "Content-Type: application/json"`

**Describe the results you received:**

```
> GET /v4.0.0/libpod/containers/json HTTP/1.1
...
< Content-Type: text/plain; charset=us-ascii
< Libpod-Api-Version: 4.1.0
...
```

**Describe the results you expected:**

```
> GET /v4.0.0/libpod/containers/json HTTP/1.1
...
< Content-Type: application/json; charset=us-ascii
< Libpod-Api-Version: 4.1.0
...
```

If any use, issued the same for docker api and it does have `application/json` as response content-type header

```
docker --version
Docker version 20.10.16, build aa7e414fdc
```

```
curl -v -X GET --unix-socket "/var/run/docker.sock" "http://localhost/containers/json" -H "Accept: application/json" -H "Content-Type: application/json"
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying /var/run/docker.sock:0...
* Connected to localhost (/run/docker.sock) port 80 (#0)
> GET /containers/json HTTP/1.1
> Host: localhost
> User-Agent: curl/7.83.1
> Accept: application/json
> Content-Type: application/json
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Api-Version: 1.41
< Content-Type: application/json
< Docker-Experimental: false
< Ostype: linux
< Server: Docker/20.10.16 (linux)
< Date: Fri, 17 Jun 2022 15:57:22 GMT
< Transfer-Encoding: chunked
```

> IMPORTANT EDIT - It only happens when the list of containers is empty, as soon as at least one is present it respects!

**Comment by Luap99** [comment]
#14662 should fix it
