### ISSUE TITLE
proxy settings are not applied when using `podman machine init --now` while it is using `init` and then `start`

### ISSUE THREAD

**Issue by benoitf** [containers/podman#14640]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Instead of doing `podman machine init` and then `podman machine start`, do `podman machine init --now`
**Steps to reproduce the issue:**

1. edit containers.conf file and add http_proxy/https_proxy env variables

```
[containers]

[engine]
  env = ["https_proxy=http://10.0.0.123:9090", "http_proxy=http://10.0.0.123:9090"]
```

2. do `podman machine init --now`

3. then connect to ssh to the machine
```
$ podman machine ssh
```

4. check environment variables
```
 env | grep http
```
there is nothing !

5. now, instead of doing `podman machine init --now`, do that in two steps

`podman machine init` and then `podman machine start`

connect to the ssh machine:
`podman machine ssh`

and check env 
```
 env | grep http
https_proxy=http://10.0.0.123:9090
http_proxy=http://10.0.0.123:9090
```

env variables are set

**Describe the results you received:**
proxy settings are not set

**Describe the results you expected:**
proxy settings are set

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by n1hility** [comment]
FYI issue for the same feature on Windows #14589, not sure if we want to keep these separate or merge them.

**Comment by Luap99** [comment]
@benoitf Can you test https://github.com/containers/podman/pull/14665?

**Comment by benoitf** [comment]
@baude I replied on the PR that it was working https://github.com/containers/podman/pull/14665#issuecomment-1160552055
