### ISSUE TITLE
podman returns "Error processing tar file(exit status 1): operation not supported" on some images but not others (rootless)

### ISSUE THREAD

**Issue by ebryerwork** [containers/podman#14655]
/kind bug

When starting the images alpine and ubuntu, podman works. If starting the images ubi8 and grafana/grafana-oss, it fails with 

```
Error: copying system image from manifest list: writing blob: adding layer with blob "sha256:de63ba066b7c0c23e2434efebcda7800d50d60f33803af9c500f75a69fb76ffa": Error processing tar file(exit status 1): operation not supported
```

Why is it failing with some images but not others? This is being done rootless. The calling user's home dir is on a local (in-memory rootfs/tmpfs type) file system.

**Steps to reproduce the issue:**

1.
podman run --runtime=/usr/bin/crun --group-add=keep-groups --volume=/storage/ezb_test:/ezb --userns=keep-id -it ubi8

**Describe the results you received:**
Error: writing blob: adding layer with blob "sha256:de63ba066b7c0c23e2434efebcda7800d50d60f33803af9c500f75a69fb76ffa": Error processing tar file(exit status 1): operation not supported

**Describe the results you expected:**
shell prompt

**Additional information you deem important (e.g. issue happens only occasionally):**
Works with the default alpine and ubuntu images. Fails with at least ubi8 and grafana/grafana-oss images.

**Output of `podman version`:**
```
podman version 4.2.0-dev
```
I have also tried this with the standard RHEL 8.6 podman.

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.27.0-dev
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.0-1.module+el8.6.0+14877+f643d2d6.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 87b7a9037cbd1d81288bdf2d6705dfda889f7cf9'
  cpuUtilization:
    idlePercent: 99.97
    systemPercent: 0.01
    userPercent: 0.02
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "8.6"
  eventLogger: file
  hostname: ezb5568
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-348.23.1.el8_5.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 8576540672
  memTotal: 16801886208
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.0.3-2.module+el8.6.0+14877+f643d2d6.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.3
      spec: 1.0.2-dev
      go: go1.17.7
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /tmp/podman-run-1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-2.module+el8.6.0+14877+f643d2d6.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 0
  swapTotal: 0
  uptime: 263h 2m 58.00s (Approximately 10.96 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/foo/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/foo/.local/share/containers/storage
  graphRootAllocated: 8400941056
  graphRootUsed: 6303367168
  graphStatus:
    Backing Filesystem: tmpfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /tmp/podman-run-1000/containers
  volumePath: /home/foo/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0-dev
  Built: 1655492806
  BuiltTime: Fri Jun 17 15:06:46 2022
  GitCommit: ff06c791ad7fb32b6a055e0d005f7354df43a5d1-dirty
  GoVersion: go1.17.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Built from source.
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Host system is an in-memory image of a RHEL 8.6 OS on top of a VMWare VM. 
Kernel 4.18.0. 
Host system disk storage is in-memory rootfs type file system. 
XDG_RUNTIME_DIR is null.

**Comment by giuseppe** [comment]
tmpfs doesn't allow to set `user.` extended attributes and they are needed to set overlay opaque directories.

If you want to use tmpfs, you could try to set the mount program to fuse-overlayfs, but in general it is better to avoid using tmpfs given the limitation with extended attributes.

**Comment by ebryerwork** [comment]
Thanks for your response. I did a lot of reading. Let me see if I understand. 'A directory is made opaque by setting the xattr “trusted.overlay.opaque” to “y”. Where the upper filesystem contains an opaque directory, any directory in the lower filesystem with the same name is ignored.' This seems to suggest that marking a directory as opaque is done by altering the xattr on the upper file system, which isn't tmpfs. But the lower filesystem is tmpfs, and that's the source of the problem. I'm confused. Does marking a directory as opaque alter the xattrs on the lower filesystem, the upper, or both? Also, what am I risking by using fuse-overlayfs as long as I don't create any duplicate directory paths? Thanks.

**Comment by giuseppe** [comment]
the upper and lower directories are stored in the graph root directory, in your case under `/home/foo/.local/share/containers/storage`, so there is no difference and the `"user.*"` extended attributes cannot be used.

The main disadvantage with `fuse-overlayfs` is performance.  A FUSE file system is significantly slower than a native file system.

**Comment by ebryerwork** [comment]
I'm sorry to bother you with this again, but I think it's an offshoot of this "issue" (actually misunderstanding by me). I don't understand why the alpine image works with tmpfs without `--storage-opt "overlay.mount_program=/usr/bin/fuse-overlayfs"` while ubi8 does not...
```
$ export XDG_DATA_HOME=/var/tmp/
$ df /var/tmp
Filesystem     1K-blocks    Used Available Use% Mounted on
rootfs           8204044 4035696   4168348  50% /
$ podman system reset
$ podman pull alpine  # works
$ podman run -it alpine
/ # df /
Filesystem           1K-blocks      Used Available Use% Mounted on
overlay                8204044   4041508   4162536  49% /
```
It looks like it's using the kernel overlayfs driver. I thought that didn't work with tmpfs though, so I'm baffled there. If I try with ubi8, it's a different story.
```
$ podman pull ubi8
...
Error: writing blob: adding layer with blob "sha256:028bdc977650c08fcf7a2bb4a7abefaead71ff8a84a55ed5940b6dbc7e466045": Error processing tar file(exit status 1): operation not supported
```
I must use the fuse-overlayfs driver, and the / file system is shown in the container as type fuse-overlayfs, not overlay. Why the discrepancy? The only thing I can think of is alpine is using the latest overlayfs driver and that is able to mount tmpfs without fuse, but my conception of the driver was determined for the container during `podman run`, not from inside the container, but I may be confused (probably).

**Comment by ebryerwork** [comment]
Maybe I'm just badly confused and the fuse driver in question is not on the host system but in the container. Supporting the idea it's the driver in the container, if I do "podman run -it alpine" after a "podman system reset" and type lsmod in the container, I get
```
/ # lsmod | egrep "(fuse|overlay)"
overlay               139264  1 
fuse                  155648  1 
```
If I use fuse-overlayfs to start the container I get
```
/ # lsmod | egrep "(fuse|overlay)"
overlay               139264  0 
fuse                  155648  3 
```
If so, perhaps alpine has a newer overlay driver that can handle NFS natively.

**Comment by giuseppe** [comment]
I think the difference is that the alpine image doesn't have any opaque directory, while ubi has.

What matters is fuse-overlayfs on the host, not inside the container

**Comment by ebryerwork** [comment]
You're the best. Thanks!
