### ISSUE TITLE
New checkpoint flake

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#14653]
We have a new checkpoint flake, and it's hitting us hard this week. Unfortunately it's one of those ginkgo tests that offer zero visibility into the problem, and I don't have the time or motivation today (this is my day off) to come up with a reproducer and full log. So here you go.

### Podman checkpoint [It] podman checkpoint a container with volumes 
* fedora-35 : int remote fedora-35 root host [remote]
  * PR #14637
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-a-container-with-volumes--1)
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-a-container-with-volumes--2)
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-a-container-with-volumes--3)
  * PR #14627
    * [06-16 17:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4752444994355200/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-a-container-with-volumes--1)
    * [06-16 17:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4752444994355200/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-a-container-with-volumes--2)
    * [06-16 17:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4752444994355200/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-a-container-with-volumes--3)
* fedora-36 : int remote fedora-36 root host [remote]
  * PR #14637
    * [06-17 10:20](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4546427526316032/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-a-container-with-volumes--1)
    * [06-17 10:20](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4546427526316032/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-a-container-with-volumes--2)
    * [06-17 10:20](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4546427526316032/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-a-container-with-volumes--3)
  * PR #14608
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-a-container-with-volumes--1)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-a-container-with-volumes--2)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-a-container-with-volumes--3)

### Podman checkpoint [It] podman checkpoint and restore container with root file-system changes using --ignore-rootfs during checkpoint 
* fedora-35 : int remote fedora-35 root host [remote]
  * PR #14637
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes-using---ignore-rootfs-during-checkpoint--1)
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes-using---ignore-rootfs-during-checkpoint--2)
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes-using---ignore-rootfs-during-checkpoint--3)
* fedora-36 : int remote fedora-36 root host [remote]
  * PR #14637
    * [06-17 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5744483655483392/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes-using---ignore-rootfs-during-checkpoint--1)
    * [06-17 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5744483655483392/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes-using---ignore-rootfs-during-checkpoint--2)
    * [06-17 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5744483655483392/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes-using---ignore-rootfs-during-checkpoint--3)
  * PR #14608
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes-using---ignore-rootfs-during-checkpoint--1)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes-using---ignore-rootfs-during-checkpoint--2)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes-using---ignore-rootfs-during-checkpoint--3)
 
 
### Podman checkpoint [It] podman checkpoint and restore dev/shm content with --export and --import 
* fedora-35 : int remote fedora-35 root host [remote]
  * PR #14637
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-and-restore-dev-shm-content-with---export-and---import--1)
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-and-restore-dev-shm-content-with---export-and---import--2)
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-and-restore-dev-shm-content-with---export-and---import--3)
  * PR #14627
    * [06-16 17:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4752444994355200/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-and-restore-dev-shm-content-with---export-and---import--1)
    * [06-16 17:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4752444994355200/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-and-restore-dev-shm-content-with---export-and---import--2)
* fedora-36 : int remote fedora-36 root host [remote]
  * PR #14637
    * [06-17 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5744483655483392/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-restore-dev-shm-content-with---export-and---import--1)
  * PR #14608
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-restore-dev-shm-content-with---export-and---import--1)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-restore-dev-shm-content-with---export-and---import--2)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-restore-dev-shm-content-with---export-and---import--3)

### Podman checkpoint [It] podman checkpoint container with export and different compression algorithms 
* fedora-35 : int remote fedora-35 root host [remote]
  * PR #14637
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-container-with-export-and-different-compression-algorithms--1)
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-container-with-export-and-different-compression-algorithms--2)
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root
-host.log.html#t--podman-checkpoint-container-with-export-and-different-compression-algorithms--3)
* fedora-36 : int remote fedora-36 root host [remote]
  * PR #14637
    * [06-17 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5744483655483392/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-container-with-export-and-different-compression-algorithms--1)
    * [06-17 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5744483655483392/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-container-with-export-and-different-compression-algorithms--2)
    * [06-17 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5744483655483392/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-container-with-export-and-different-compression-algorithms--3)
  * PR #14608
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-container-with-export-and-different-compression-algorithms--1)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-container-with-export-and-different-compression-algorithms--2)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-container-with-export-and-different-compression-algorithms--3)
 
 
### Podman checkpoint [It] podman checkpoint and run exec in restored container 
* fedora-35 : int remote fedora-35 root host [remote]
  * PR #14637
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-and-run-exec-in-restored-container--1)
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-and-run-exec-in-restored-container--2)
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-and-run-exec-in-restored-container--3)
  * PR #14627
    * [06-16 17:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4752444994355200/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-and-run-exec-in-restored-container--1)
* fedora-36 : int remote fedora-36 root host [remote]
  * PR #14637
    * [06-17 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5744483655483392/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-run-exec-in-restored-container--1)
  * PR #14608
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-run-exec-in-restored-container--1)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-run-exec-in-restored-container--2)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-run-exec-in-restored-container--3)
 
### Podman checkpoint [It] podman checkpoint container with export and statistics 
* fedora-35 : int remote fedora-35 root host [remote]
  * PR #14637
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-container-with-export-and-statistics--1)
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-container-with-export-and-statistics--2)
* fedora-36 : int remote fedora-36 root host [remote]
  * PR #14637
    * [06-17 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5744483655483392/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-container-with-export-and-statistics--1)
  * PR #14608
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-container-with-export-and-statistics--1)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-container-with-export-and-statistics--2)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-container-with-export-and-statistics--3)
 
 
### Podman checkpoint [It] podman checkpoint and restore container with root file-system changes 
* fedora-35 : int remote fedora-35 root host [remote]
  * PR #14637
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes--1)
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes--2)
* fedora-36 : int remote fedora-36 root host [remote]
  * PR #14637
    * [06-17 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5744483655483392/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes--1)
    * [06-17 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5744483655483392/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes--2)
    * [06-17 09:09](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5744483655483392/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes--3)
 
 
### Podman checkpoint [It] podman checkpoint and restore container with root file-system changes using --ignore-rootfs during restore 
* fedora-35 : int remote fedora-35 root host [remote]
  * PR #14637
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes-using---ignore-rootfs-during-restore--1)
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes-using---ignore-rootfs-during-restore--2)
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes-using---ignore-rootfs-during-restore--3)
* fedora-36 : int remote fedora-36 root host [remote]
  * PR #14608
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes-using---ignore-rootfs-during-restore--1)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes-using---ignore-rootfs-during-restore--2)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-and-restore-container-with-root-file-system-changes-using---ignore-rootfs-during-restore--3)

### Podman checkpoint [It] podman checkpoint container with export (migration) 
* fedora-35 : int remote fedora-35 root host [remote]
  * PR #14637
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-container-with-export--migration---1)
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-container-with-export--migration---2)
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-container-with-export--migration---3)
* fedora-36 : int remote fedora-36 root host [remote]
  * PR #14608
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-container-with-export--migration---1)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-container-with-export--migration---2)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-container-with-export--migration---3)
 
 
### Podman checkpoint [It] podman checkpoint container with export (migration) and --ipc host 
* fedora-35 : int remote fedora-35 root host [remote]
  * PR #14637
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-container-with-export--migration--and---ipc-host--1)
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-container-with-export--migration--and---ipc-host--2)
    * [06-17 09:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5181533702062080/html/int-remote-fedora-35-root-host.log.html#t--podman-checkpoint-container-with-export--migration--and---ipc-host--3)
* fedora-36 : int remote fedora-36 root host [remote]
  * PR #14608
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-container-with-export--migration--and---ipc-host--1)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-container-with-export--migration--and---ipc-host--2)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-container-with-export--migration--and---ipc-host--3)

### Podman checkpoint [It] podman checkpoint a container started with --rm 
* fedora-36 : int remote fedora-36 root host [remote]
  * PR #14608
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-a-container-started-with---rm--1)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-a-container-started-with---rm--2)
    * [06-16 09:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6558471024803840/html/int-remote-fedora-36-root-host.log.html#t--podman-checkpoint-a-container-started-with---rm--3)

**Comment by edsantiago** [comment]
Well, AFAICT this is just a simple trivial race condition, a difference between podman and podman-remote.
* **podman** guarantees that, after `checkpoint` runs, the container is 100% gone
* **podman-remote** does not. There is a brief window in which the container is `Exited`.

(This may be a bug in `run --rm`, not `checkpoint`: historically there have been a number of races in `podman-remote run --rm`).

Reproducer: save this as `/tmp/doit`:
```bash
#!/bin/bash

REMOTE=
if [[ -n "$1" ]]; then
    REMOTE=remote
fi

pm() {
    if [[ -n "$REMOTE" ]]; then
        podman-remote "$@"
    else
        podman "$@"
    fi
}

while :;do
    cid=$(pm run -d --rm quay.io/libpod/testimage:20220615 top)
    rm -f /tmp/foo.tar.gz
    pm container checkpoint $cid -e /tmp/foo.tar.gz
    psa=$(pm ps -a --noheading)
    if [[ -n "$psa" ]]; then
            echo "************** FAILED  $psa"
            exit 1
    fi
done
```
Fire up a server (`podman system service -t 0 &`), then run `/tmp/doit remote`. It will fail pretty quickly. If you run it without `remote`, it seems to run forever.

Side note: `podman container checkpoint` spits out a CID. `podman-remote` spits out an empty line. Seems like a bug to me. If someone fixes this issue, could you piggyback that fix into your PR?

**Comment by edsantiago** [comment]
We haven't been seeing this flake because I committed a horrible workaround, #14718.  Shall I remove the workaround, as a way to incentivize an actual fix?

**Comment by rst0git** [comment]
@edsantiago I can add this issue to my todo list and work on it next week.

**Comment by edsantiago** [comment]
@rst0git thank you! But please see my comment above https://github.com/containers/podman/issues/14653#issuecomment-1164799694 suggesting that the bug may be in `podman-remote` itself, not checkpoint. (And, after you read that, please remember that I have no clue what I'm talking about).
