### ISSUE TITLE
Image works in docker but not in podman

### ISSUE THREAD

**Issue by codemeddler** [containers/podman#14693]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

There seems to be some critical difference in podman and docker defaults, that makes an image work in docker but not podman. Doing ```podman run -ti docker.io/wickr/bot-cloud:5.92.06.01``` has the container output nodejs version strings and then exits/dies. Doing ```docker run -ti docker.io/wickr/bot-cloud:5.92.06.01``` successfully launches the container to a welcome screen.

**Steps to reproduce the issue:**

1. Run ```podman run -ti docker.io/wickr/bot-cloud:5.92.06.01```

2. Watch it fail.

**Describe the results you received:**
Container prints which nodejs version it is running and then dies/exits.

**Describe the results you expected:**
Container runs and shows a welcome screen after the initial node version and other setup prints.

**Additional information you deem important (e.g. issue happens only occasionally):**
I have tried using privileged=true, running podman as sudo, forcing drivers to match what I observe as docker defaults (json-file for log driver, overlay2 for storage driver), and whatever other run options I thought that could be the culprit. So far, to no avail. Both podman logs and journalctl showed nothing helpful, though not a master of either.

I poked around the run script, and the step following the nodejs version is related to shuffling some sql files around. As my expectation was for podman to work, I did my first tries as more proper, doing a mount with ```-v mydir:/opt/WickrIO```. Checking ```mydir```, I can see some database files there. The run script has some echos after the file shuffle, but those never show up. Makes me think this could be filesystem related. Or maybe there is some stop signal problem and the script triggers what podman thinks is an exit.

Note: I do not work for Wickr, just poked around the run script.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.1.0
API Version:  4.1.0
Go Version:   go1.17.5
Built:        Wed May 25 07:40:16 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.1-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.1, commit: bb7e4979ae5b33d8c8793618965018f335af0827'
  cpuUtilization:
    idlePercent: 99.58
    systemPercent: 0.13
    userPercent: 0.28
  cpus: 3
  distribution:
    distribution: '"centos"'
    version: "9"
  eventLogger: journald
  hostname: wickr
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.0-86.el9.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 796491776
  memTotal: 4002238464
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.5-2.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.el9.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 0
  swapTotal: 0
  uptime: 13h 16m 4.4s (Approximately 0.54 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 80509460480
  graphRootUsed: 3494494208
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.1.0
  Built: 1653464416
  BuiltTime: Wed May 25 07:40:16 2022
  GitCommit: ""
  GoVersion: go1.17.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.1.0-4.el9.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes to troubleshooting, no to latest as the latest is not available on CentOS 9 Stream. Checked the release notes for was it 4.2 that is latest, and didn't see changes that would fix this.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtual server.

**Comment by rhatdan** [comment]
I am on Fedora 36 with podman 4.1.

**Comment by codemeddler** [comment]
Interesting. I wonder if the problem could be that as it was a fresh server for testing the account logged in was the root and not a "regular" admin user account? I can try with an admin user later today if you think that could be it.

**Comment by codemeddler** [comment]
What is the proper way for rootful mode: sudo podman, passing -root, doing -priviliged=true, or a combination of these? Want to make sure I test the right way.

**Comment by rhatdan** [comment]
sudo podman 
should work.

**Comment by baude** [comment]
fails in rootful for me too ... rootless works. looking for a reason

**Comment by codemeddler** [comment]
I managed to get rootless to fail too. If I mount a directory not owned by the current user (e.g. owned by root), the process exits with code 1 after printing the nodejs stuff. If I mount a directory owned by the current user/group (creating new dir in user home), the container works.

Example: ```podman run --name wickr -v /mnt/apps/opt/wickr-io:/opt/WickrIO -ti wickr/bot-cloud:5.92.06.01``` fails (/mnt/apps/opt/wickr-io owned by root, but drwxrwxrwx permissions), but ```podman run --name wickr -v ~/wickr:/opt/WickrIO -ti wickr/bot-cloud:5.92.06.01``` works (just mkdir in home folder as current user).

I can probably work around this issue, but would be nice to kind of know why and where it fails, or get like a helpful error message somewhere.

**Comment by rhatdan** [comment]
If this is an SELinux system, then SELinux would block the access. Try with a :Z.

**Comment by codemeddler** [comment]
No need, sorted the issue out. I had forgotten to nuke the files created by the initial attempt, and those were owned and only modifiable by root. The rootless now works without a hitch.

As the proper use will be running on a dedicated user and group, the rootful not working doesn't really matter to me. Feel free to keep the issue open if you think there's something to it though (maybe some default setting in rootful is wrong).
