### ISSUE TITLE
tests: stop harassing fubar.com

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#14699]
There are many instances of `server.fubar.com` in the tests. I'm sure this is intended as `no-such-host`, but there is an actual A record for this. It is a genuine live system.

In `system connection test` this usage is uncomfortable but harmless: there is no actual connection. In [image scp](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5977150636425216/html/int-podman-fedora-36-root-host.log.html#t--podman-image-scp-with-proper-connection--1) there is an actual attempt to `scp`, which the server owner could, quite rightly, see as an attack.

@cdoern please make it a priority to fix this ASAP. I would also encourage you to fix system connection tests as well, simply as much-needed cleanup.

(As a bonus, this will give us back 30-40 seconds).

**Comment by cdoern** [comment]
on it, will work on a fix today

**Comment by cdoern** [comment]
@edsantiago is `server.foobar.com` a real host? I see that `foobar.com` is (just `ping foobar.com`) but any sort of connection attempt to server.foobar.com fails. I am assuming the subset of .foobar.com is causing some damage even though server.foobar.com is not real?

**Comment by edsantiago** [comment]
```console
$ dig  server.fubar.com

; <<>> DiG 9.16.27 <<>> server.fubar.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60132
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;server.fubar.com.              IN      A

;; ANSWER SECTION:
server.fubar.com.       3564    IN      A       66.151.147.142

;; Query time: 36 msec
;; SERVER: 192.168.1.46#53(192.168.1.46)
;; WHEN: Wed Jun 22 12:12:30 MDT 2022
;; MSG SIZE  rcvd: 61

```
Translation: there is an A record. It's a wildcard, but even so, it resolves. Even if it didn't, we're running network commands against a domain which is not owned by us, and we do not do that. Connections time out (as shown in test logs); I haven't bothered to find out if it's because that IP is not routable, or they're firewalled. It doesn't matter. We just don't do that.

**Comment by cdoern** [comment]
ok, I will change all of the tests to be a domain that can't even exist because of an invalid extension

**Comment by giuseppe** [comment]
would it be acceptable to use `example.com`?

**Comment by edsantiago** [comment]
Of course. That's explicitly defined in RFC2606.

**Comment by cdoern** [comment]
I will change to that on the PR. I didn't know those reserved urls were a thing, you learn something new everyday!
