### ISSUE TITLE
Auto-start podman machine on Windows startup

### ISSUE THREAD

**Issue by rcsilva83** [containers/podman#14702]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

**Steps to reproduce the issue:**

1. Start Windows

2. Run `podman ps` on a Terminal

**Describe the results you received:**

The following error message:
```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
```

**Describe the results you expected:**

A list with the running containers:
```
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
```

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.1.0
API Version:  4.1.0
Go Version:   go1.16.15
Git Commit:   e4b03902052294d4f342a185bb54702ed5bed8b1
Built:        Fri May  6 10:47:05 2022
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.16.15
Built:        Wed Jun 15 11:32:06 2022
OS/Arch:      linux/amd64
```

**Comment by mheon** [comment]
@n1hility PTAL.

**Comment by rhatdan** [comment]
@n1hility Any thoughts on this?

**Comment by djarbz** [comment]
+1

Also, is there a best practice to have it start containers when the Podman Machine is started?
And hooks that we can run for the Windows PortProxy?

**Comment by n1hility** [comment]
The current strategy we had in mind for this was that containers/podman-desktop would govern start stop. It adds a taskbar control and everything. 

As to containers starting right away, we could look at adding [the restart policy start service we ship in contrib to podman machine](https://github.com/containers/podman/blob/main/contrib/systemd/system/podman.service.in)

**Comment by djarbz** [comment]
Ok cool, I just downloaded it to check it out.
I would have no problem setting up systemd services for each, that is how I manage my Linus Podman hosts, unfortunately this particular host is Windows.

**Comment by n1hility** [comment]
You could technically do it that way as well. We use systemd to host the podman service so if you access the wsl instance you can install additional services.

**Comment by djarbz** [comment]
I guess I don't understand what you were referencing with that contrib file then.

**Comment by n1hility** [comment]
the contrib file is something we could potentially include in machine that would allow you to control which services are started via podman commands (setting a container restart policy).

Manually managing your own systemd service (or generating them via podman generate systemd) would be a lower level alternative. The latter approach you can do more customization in behavior but on the downside you have to migrate that between new machine instances.

**Comment by rhatdan** [comment]
@n1hility What do you think we should do with this issue?

**Comment by holly-cummins** [comment]
This would also be useful on Mac. I'm experimenting with running `podman machine start` with `launchd`, but without much success yet.

**Comment by n1hility** [comment]
It's likely better to have a single auto-start mechanism, so I am going to close this in favor of https://github.com/containers/podman-desktop/issues/225

I assume this will cover Mac as well but will add a note
