### ISSUE TITLE
Error when trying to get container running on Debian11 -> Error:  /usr/bin/slirp4netns failed: "open(\"/dev/net/tun\"): Permission denied

### ISSUE THREAD

**Issue by dennis605** [containers/podman#14701]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. install podman

2. run container : podman run hello-world

**Describe the results you received:**
Error thrown:
ERRO[0001] Error preparing container caa955a1419df75eb53018b35d4a0d891759436c5057b55422c4286e7c35120c: /usr/bin/slirp4netns failed: "open(\"/dev/net/tun\"): Permission denied\nWARNING: Support for seccomp is experimental\nchild failed(1)\nWARNING: Support for seccomp is experimental\n" 
Error: error resolving storage path for container caa955a1419df75eb53018b35d4a0d891759436c5057b55422c4286e7c35120c: lstat /home/dennis/.local/share/containers/storage/overlay/d05bc36a0a8b23cdb9a1b5c56aa371406c81ae204cb52f8d82f877e11c1e39de/merged: invalid argument

Container not getting up and running
**Describe the results you expected:**
I'd expect to get the container up and running

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.15.15
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.1.2, commit: '
  cpus: 4
  distribution:
    codename: bullseye
    distribution: debian
    version: "11"
  eventLogger: journald
  hostname: h2977318.stratoserver.net
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.19.0
  linkmode: dynamic
  logDriver: journald
  memFree: 8006328320
  memTotal: 8589934592
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: ea1fe3938eefa14eb707f1d22adff4db670645d6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 0
  swapTotal: 0
  uptime: 23h 34m 25.33s (Approximately 0.96 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/dennis/.config/containers/storage.conf
  containerStore:
    number: 14
    paused: 0
    running: 0
    stopped: 14
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.10.3
        fuse-overlayfs: version 1.5
        FUSE library version 3.10.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/dennis/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  volumePath: /home/dennis/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.15
  OsArch: linux/amd64
  Version: 3.4.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Auflistung… Fertig
podman/unbekannt,now 100:3.4.2-4 amd64 [Konfiguration-verbleibend]
podman/unbekannt 100:3.4.2-4 arm64
podman/unbekannt 100:3.4.2-4 armhf
podman/unbekannt 100:3.4.2-4 i386
podman/unbekannt 100:3.4.2-4 ppc64el
podman/unbekannt 100:3.4.2-4 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Output of `sudo ls -al /dev/net/tun`:**

```
[sudo] Passwort für dennis: 
crw-rw-rw- 1 root root 10, 200 21. Jun 18:59 /dev/net/tun
```

also tun module is loaded
**Output of `sudo lsmod |grep tun`:** -> 

```
tun                     4242  -2
vznetstat               4242  -2 tun,ip_vznetstat,ip6_vznetstat
```

Thank you so much for your support in advance.

**Comment by mheon** [comment]
Any chance access is being blocked by SELinux / Apparmor?

**Comment by dennis605** [comment]
Hi @mheon thanks for your reply, but I don‘t think so, because output of `podman info --debug` saying 
```
security:
    **apparmorEnabled: false**
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    **selinuxEnabled: false** 
```

**Comment by mheon** [comment]
But are they enabled on the system itself? That tells us that Podman is not enforcing them for containers, but not that the system overall is does not have them enabled.

**Comment by dennis605** [comment]
oh, I was interpreting that this information is regarding Debian not regarding the container environment. I‘ll check that, thanks

**Comment by dennis605** [comment]
oh, unfortunately it seems to be, that neither apparmor or selinux are causing the issue:

`sudo getenforce
->
Disabled
`

`sudo aa-status
->
apparmor not present.
`

**Comment by rhatdan** [comment]
Do rootful containers work?
`$ sudo  podman run hello-world`
Does 
`$ podman unshare cat /proc/self/uid_map `
work?

**Comment by rhatdan** [comment]
Is there anything strange about the setup of your homedir?
@giuseppe Could this be a fuse-overlayfs problem?

**Comment by dennis605** [comment]
Can you be more specific what you mean with: 
> Is there anything strange about the setup of your homedir?

can I check this somehow?

**Comment by giuseppe** [comment]
does `/dev/net/tun` exist?

You may need to load the kernel module

**Comment by dennis605** [comment]
> does `/dev/net/tun` exist?
> 
> You may need to load the kernel module

yes it exists:

```
Output of sudo ls -al /dev/net/tun:

[sudo] Passwort für dennis: 
crw-rw-rw- 1 root root 10, 200 21. Jun 18:59 /dev/net/tun
```
and also tun module is loaded

```
Output of sudo lsmod |grep tun: ->

tun                     4242  -2
vznetstat               4242  -2 tun,ip_vznetstat,ip6_vznetstat
```

**Comment by rhatdan** [comment]
This is feeling a lot like the kernel is out of date or does not have support for some of the overlay fields we are using?

**Comment by giuseppe** [comment]
also `Version:      3.4.2` is ancient.  Could you try with podman from upstream?

**Comment by giuseppe** [comment]
what is the content of `/home/dennis/.config/containers/storage.conf`?  I'd suggest to delete it and use the default configuration generated by podman

**Comment by dennis605** [comment]
> what is the content of `/home/dennis/.config/containers/storage.conf`? I'd suggest to delete it and use the default configuration generated by podman

This is strange... 

`/home/dennis/.config/containers/storage.conf`

does not exist.

**Comment by dennis605** [comment]
oh it is working now.
 I could get it working installing fuse-overlayfs.
And after that I needed to create /dev/fuse again with:

`sudo mknod /dev/fuse -m 0666 c 10 229
`
