### ISSUE TITLE
Windows installer not working due to SSH issues

### ISSUE THREAD

**Issue by matbennion** [containers/podman#14708]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. As per:
https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md
downloaded and ran podman-v4.1.1.msi 

2. At the powershell, ran "podman machine init"

**Describe the results you received:**

Lots of activity, but a few errors were reported, including some mentioning SSH.  I don't have the log because I tried restarting the computer, uninstalling and re-installing, but it's not possible to repeat the process because even after uninstalling, the VM persists so can't be re-created.

I can stop and start the mahine ("podman machine stop", "podman machine start") but get the following error on starting:

> API forwarding for Docker API clients is not available due to the following startup failures.
>         win-sshproxy.exe failed to start, exit code: 1 (see windows event logs)
> 
> Podman clients are still able to connect.
> Machine "podman-machine-default" started successfully
> 

The suggested first command fails:

> 
> PS C:\Users\dev> podman run ubi8-micro date
> Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
> Error: unable to connect to Podman. failed to create sshClient: failed to parse identity "C:\\Users\\dev\\.ssh\\podman-machine-default": open C:\Users\dev\.ssh\podman-machine-default: The system cannot find the file specified.

**Describe the results you expected:**
Software to install without errors; suggested first command to work without errors.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is a new installation of Windows 10, downloaded from MIcrosoft website this week, so is the latest version.

**Output of `podman version`:**

```
PS C:\Users\dev> podman version
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: failed to parse identity "C:\\Users\\dev\\.ssh\\podman-machine-default": open C:\Users\dev\.ssh\podman-machine-default: The system cannot find the file specified.
```

**Output of `podman info --debug`:**

```
PS C:\Users\dev> podman info --debug
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: failed to parse identity "C:\\Users\\dev\\.ssh\\podman-machine-default": open C:\Users\dev\.ssh\podman-machine-default: The system cannot find the file specified.
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
These commands not recognised in the Windows terminal.
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by timlew** [comment]
I just ran into what I believe is the same issue. Here is the end of the output after I ran 'podman machine init'.

Everything up to this point shows no errors. Then we get...

... <much output> ...
Complete!
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 0:00:18 ago on Thu Jun 23 20:35:45 2022.
Dependencies resolved.
======================================================================================================================================
 Package                           Architecture                Version                             Repository                    Size
======================================================================================================================================
Reinstalling:
 shadow-utils                      x86_64                      2:4.9-9.fc35                        updates                      1.1 M

Transaction Summary
======================================================================================================================================

Total download size: 1.1 M
Installed size: 3.7 M
Downloading Packages:
shadow-utils-4.9-9.fc35.x86_64.rpm                                                                    2.3 MB/s | 1.1 MB     00:00
--------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                 1.8 MB/s | 1.1 MB     00:00
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                              1/1
  Reinstalling     : shadow-utils-2:4.9-9.fc35.x86_64                                                                             1/2
  Cleanup          : shadow-utils-2:4.9-9.fc35.x86_64                                                                             2/2
  Running scriptlet: shadow-utils-2:4.9-9.fc35.x86_64                                                                             2/2
  Verifying        : shadow-utils-2:4.9-9.fc35.x86_64                                                                             1/2
  Verifying        : shadow-utils-2:4.9-9.fc35.x86_64                                                                             2/2

Reinstalled:
  shadow-utils-2:4.9-9.fc35.x86_64

Complete!
Configuring system...
Error: could not create ssh keys: exec: "C:\\Users\\tim\\.ssh\\wsl.exe": file does not exist
PS C:\WINDOWS\system32>

**Comment by n1hility** [comment]
This is the same issue as #14416, which is fixed in main. The workaround is to either use powershell or if you use cmd, to change the directory to not be in system32 (for example %userprofile%)

**Comment by matbennion** [comment]
Hi, thanks for the prompt reply! However:

1. I did use powershell, so wasn't in system32
2. It's not possible to try again (just in case my memory isn't perfect, and to get the full log): if I try podman machine init again, I get 'error: podman-machine-default: VM already exists'. I tried uninstalling podman via Windows add/remove programs but this didn't remove the VM.

So the proposed solution doesn't fix it, and there's a second issue with the uninstaller (unless there's some documentation somewhere that explains the uninstall process?)

**Comment by n1hility** [comment]
Sorry @matbennion I missed that line and conflated this with @timlew's comment!

You should be able to kill the failed vm with `podman machine rm -f` These arent removed on Windows uninstall to avoid unintentional data loss and prevent upgrade problems. 

If for some reason that doesn't work you can remove the wsl instance and files manually:

```
wsl --unregister podman-machine-default
rmdir .\.local\share\containers\podman\machine\wsl
rmdir .config\containers\podman\machine
rmdir .\AppData\Roaming\containers\
```

**Comment by timlew** [comment]
I removed mine and per what it says in 14416 recreated it in a directory other than /windows/system32 (My directory was /users/tim/podman) 
When a 'podman machine init' from the new directory I did not get the ssh error, so I think until there is a good solution consider adding to the instructions that you should not run from system32.

**Comment by n1hility** [comment]
Glad this is working for you now. The fix will be included in the next release.
