### ISSUE TITLE
podman build --squash always rebuilds every layer

### ISSUE THREAD

**Issue by lucasbaile** [containers/podman#14712]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

So I'm having a problem were the behaviour of the `--squash` flag is very different between `docker build` and `podman build`

With `docker build --squash`, when I try to build the same Dockerfile multiple times in sequence (without any changes to it, nor any file), the layers are only actually built the first time, while the following builds only reuse the cached layers and re-squash them at the end, resulting in a new image hash, but with a drastically smaller build time, since the layers were used from cache.

With `podman build --squash`, the behaviour is different. When I take the same Dockerfile and try to build it multiple times in sequence (again, no changes whatsoever), all the layers are rebuilt everytime, on top of the expected squash at the end, as if I had passed the `--no-cache` flag as well.

I'm not sure if this difference is expected, but if so, I would kindly like to ask the reasoning, because it seems like the current behaviour with podman could easily be replicated with `--no-cache --squash`, without having to force the rebuild of all layers when using only `--squash`

**Steps to reproduce the issue:**

1. In my testing, any Dockerfile seems to reproduce this issue, but I'll leave a really simple one I'm using:
```
FROM fedora:36
WORKDIR /app

RUN dnf update -y

RUN dnf install -y \
python3-pip \
libpq-devel

RUN dnf clean all
```

2. Using any environment with docker, call this command twice in a row:
```bash
docker build --squash -f Dockerfile . -t myimage
```
The second execution should be significantly faster, using the cached layers, and resulting in an output roughly like this:
```bash
Sending build context to Docker daemon  1.674MB
Step 1/5 : FROM fedora:36
 ---> 98ffdbffd207
Step 2/5 : WORKDIR /app
 ---> Using cache
 ---> 6f3050febb4c
Step 3/5 : RUN dnf update -y
 ---> Using cache
 ---> eb0c3421bcb3
Step 4/5 : RUN dnf install -y python3-pip libpq-devel
 ---> Using cache
 ---> 6a82d35bc559
Step 5/5 : RUN dnf clean all
 ---> Using cache
 ---> a1c80f141586
Successfully built bb03750eaeda
Successfully tagged myimage:latest
```

3. Now in an envinronment using podman, do the same step of calling the build twice in a row, and the build process should be roughly the same duration both times, with the output of a full build both times:
```bash
podman build --squash -f Dockerfile . -t myimage
```

**Describe the results you received:**

Using the `--squash` results in the cached layers never being used, causing high times on rebuilds that could be avoided.

**Describe the results you expected:**

I expected the `--quash` to work the same as docker's, with the cached layers still being used, but with the squash at the end

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7
Built:      Tue Mar 15 19:15:06 2022
OS/Arch:    linux/amd64
```

**Output of `podman info --debug`:**
```
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-1.module_el8.7.0+1106+45480ee0.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 235fd1687e002bf8eaa7ea2f999104be869858b4'
  cpus: 8
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: centosbox
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.0-39-generic
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 52307947520
  memTotal: 52832645120
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.0.3-3.module_el8.7.0+1106+45480ee0.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.3
      spec: 1.0.2-dev
      go: go1.17.7
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-2.module_el8.7.0+1106+45480ee0.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 0
  swapTotal: 0
  uptime: 34m 44.45s
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.8.2-1.module_el8.7.0+1106+45480ee0.x86_64
      Version: |-
        fusermount3 version: 3.3.0
        fuse-overlayfs: version 1.8.2
        FUSE library version 3.3.0
        using FUSE kernel interface version 7.26
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: zfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 8
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1647371706
  BuiltTime: Tue Mar 15 19:15:06 2022
  GitCommit: ""
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**
```
podman-4.0.2-1.module_el8.7.0+1106+45480ee0.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes (It's the latest version of podman on CentOS Stream 8)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Tests were executed on physical machines running, respectively:
- Docker: Ubuntu 22.04
- Podman: CentOS Stream 8

**Comment by mheon** [comment]
@flouthoc PTAL

**Comment by lucasbaile** [comment]
Hey, @flouthoc!

Thanks for replying so fast!

I'm not sure if I'm doing something wrong or if the mentioned feature is not present on my 4.0.2 podman, but I'm getting this error when running that command:

```
[root@centos ~]# podman build --layers --squash-all -f Dockerfile . -t myimage
Error: cannot specify --squash, --squash-all and --layers options together
```

**Comment by flouthoc** [comment]
Your podman seems old to me this patch was recently merged. Could you build source from upstream ?

**Comment by flouthoc** [comment]
Hi @lucasbaile , I checked this again this is working in upstream and we already have a test for this added here https://github.com/containers/podman/pull/14320 . 

I am closing this since this should not persist in upstream but please comment back here if this does not works for you and I'll re-open the issue :smile: 

Thanks
