### ISSUE TITLE
podman machine `Starting` field not updated (on macOS)

### ISSUE THREAD

**Issue by benoitf** [containers/podman#14738]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I've tested on macOS

`podman machine` start command is not updating the `starting` field
**Steps to reproduce the issue:**

1. execute `podman machine start`

2. run `podman machine list --format json` command

3. `Starting` is set to false

It never reached `true`

**Describe the results you received:**

I receive `"Starting": false` all the time

**Describe the results you expected:**
I should get `Starting: true` as soon as I enter the command `podman machine start` and it should be set to true until machine is `Running` (or fails due to an error)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
v4.1.1
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by benoitf** [comment]
I'm reopening the issue as I can still reproduce the issue on Podman 4.2.1 on macOS

I launch `podman machine start` command in terminal and in another tab `podman machine ls --format=json` and `Starting` field is never set to true I always have `"Starting": false`

**Comment by rhatdan** [comment]
@ashley-cui PTAL

**Comment by ashley-cui** [comment]
Closed via https://github.com/containers/podman/pull/15916
