### ISSUE TITLE
[FEATURE REQUEST]: Support manifest deletion on golang bindings

### ISSUE THREAD

**Issue by YoitoFes** [containers/podman#14735]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

As of v4.0.0, RESTful API supports manifest deletion.

- https://docs.podman.io/en/latest/_static/api.html?version=v4.0#operation/ManifestDeleteLibpod

Though, [podman/v4/pkg/bindings/manifests](../blob/master/pkg/bindings/manifests/manifests.go) does not support it currently. It would be grateful if golang bindings added support for manifest deletion.

**Comment by flouthoc** [comment]
Hi @YoitoFes , I think From `pkg` it looks `manifests` already supports `Remove(` is there anything else which you are looking for https://github.com/containers/podman/blob/main/pkg/bindings/manifests/manifests.go#L115
