### ISSUE TITLE
'podman pod ps' fails with 'no such pod'

### ISSUE THREAD

**Issue by ydayagi** [containers/podman#14736]
/kind bug
**Description**
listing pods while pods are deleted causes 'pod ps' to fail with exit code 125 and message 'no such pod'
This is much like https://github.com/containers/podman/issues/12034. However, it seems that in the other bug there was a focus on the deletion and not the 'pod ps' command.

**Steps to reproduce the issue:**

1. create 10 pods

2. delete 10 pods

3. during deletion do 'podman pod ps'

**Describe the results you received:**
[ydayagi@fedora ~]$ sudo podman pod ps
Error: pod ea52fce12a3ce0c345aec62737c6e7819c2ced233cf822434706eca4db81c5c9 not found in database: no such pod

**Describe the results you expected:**
[ydayagi@fedora ~]$ sudo podman pod ps
POD ID      NAME        STATUS      CREATED     INFRA ID    # OF CONTAINERS
<pods-that-were-not-deleted>

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
[ydayagi@fedora ~]$ podman version
Version:      3.4.0
API Version:  3.4.0
Go Version:   go1.16.8
Built:        Thu Sep 30 22:32:16 2021
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.0-1.fc35.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Checked troubleshooting. Did not test latest version.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM with fedora 35

**Comment by giuseppe** [comment]
we have to ignore `define.ErrNoSuchPod`.

I'll work on a PR

**Comment by giuseppe** [comment]
PR: https://github.com/containers/podman/pull/14741
