### ISSUE TITLE
Both IPv4 and IPv6 address are assigned automatically even it has been specified in docker compose file

### ISSUE THREAD

**Issue by leolovejj** [containers/podman#14737]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Both IPv4 and IPv6 address are assigned automatically even it has been specified in docker compose file

**Steps to reproduce the issue:**

1. Created the following docker compose yaml file:
    [root@net182-host183 ~]# cat /system/config/instances/iSltd_9-1-0-1/iSltd_9-1-0-1.yml
version: "2.2"
services:
    Sltd_tool:
        container_name: Sltd_tool
        image: localhost/netbackup/tool:9.1.0.1
        labels:
            flex.internal.addons: "1"
        networks: {}
        volumes: []
        volumes_from: []
        ports: []
        hostname: ""
        environment: []
        tty: false
        stdin_open: false
        storage_opt: {}
        security_opt: []
        healthcheck: {}
    iSltd_9-1-0-1:
        container_name: iSltd_9-1-0-1
        image: localhost/netbackup/main:9.1.0.1
        domainname: verizon.com
        dns:
            - 172.17.0.5
            - 2200::5
        dns_search:
            - verizon.com
        labels:
            flex.instance.info: NetBackup Master Server:9.1.0.1
        networks:
            iSltd_9-1-0-1_nic0:
                **ipv4_address: 172.17.0.11
                ipv6_address: 2200::11**
        volumes:
            - vSltd_logs:/mnt/nblogs
            - vSltd_catalog:/mnt/nbdata
            - /etc/vxos-release:/etc/flex-release:ro
            - /opt/veritas/appliance/appha/status-codes:/opt/veritas/vxplat-manage/health-include:ro
            - /opt/veritas/flex/tools/instance-vxapp-addons.sh:/opt/veritas/vxplat-manage/add-ons:ro
            - /opt/VRTSperl:/opt/VRTSperl:ro
            - /mnt/data/apps/.lockdown-mode.conf:/opt/veritas/vxplat-manage/lockdown-mode.conf:z,ro
        volumes_from:
            - service:Sltd_tool:z,ro
        ports: []
        hostname: master-1
        environment: []
        tty: true
        stdin_open: true
        cap_add:
            - SYS_ADMIN
        sysctls:
            - kernel.sem=400 307200 32 1024
            - net.core.somaxconn=1024
            - net.ipv4.tcp_keepalive_intvl=10
            - net.ipv4.tcp_keepalive_probes=5
            - net.ipv4.tcp_keepalive_time=900
        ulimits:
            nofile:
                hard: 16384
                soft: 8192
        storage_opt:
            size: 10G
        security_opt:
            - label=level:s0:c651
            - unmask=/sys/dev/block
        healthcheck:
            test:
                - CMD
                - /usr/bin/healthcheck
networks:
    iSltd_9-1-0-1_nic0:
        external:
            name: nic0
volumes:
    vSltd_catalog:
        external: true
    vSltd_logs:
        external: true
2. run the following command to create and start the container:
   docker-compose -f /system/config/instances/iSltd_9-1-0-1/iSltd_9-1-0-1.yml down -d --force-recreate --always-recreate-deps -V --no-deps iSltd_9-1-0-1

3. Go the container by running the following command:
    [root@net182-host183 ~]# docker exec -it 3a096ebe6820 bash
bash-4.2# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet **172.17.0.2**  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::94b4:fbff:fe3f:af64  prefixlen 64  scopeid 0x20<link>
        inet6 **2200::2**  prefixlen 64  scopeid 0x0<global>
        ether 96:b4:fb:3f:af:64  txqueuelen 0  (Ethernet)
        RX packets 105  bytes 8549 (8.3 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 18  bytes 1488 (1.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Describe the results you received:**
The IPv4 and IPv6 addresses of eth0 are both auto assigned and not configured according to the yml file.

**Describe the results you expected:**
The IPv4 and IPv6 addresses of eth0 should be configured according to the value specified in yml file.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
[root@net182-host183 ~]# podman version
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7

Built:      Tue Apr 19 10:16:32 2022
OS/Arch:    linux/amd64

**Output of `podman info --debug`:**
[root@net182-host183 ~]# podman info --debug
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.0-1.module+el8.6.0+14877+f643d2d6.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 87b7a9037cbd1d81288bdf2d6705dfda889f7cf9'
  cpus: 8
  distribution:
    distribution: '"rhel"'
    version: "8.4"
  eventLogger: file
  hostname: net182-host183
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-305.49.1.el8_4.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 18719035392
  memTotal: 33444614144
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.0.0-74.rc95.module+el8.4.0+11822+6cc1e7d7.x86_64
    path: /usr/bin/runc
    version: |-
      runc version spec: 1.0.2-dev
      go: go1.15.13
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /etc/opt/veritas/flex/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.4.0+11822+6cc1e7d7.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 17135845376
  swapTotal: 17179865088
  uptime: 4h 6m 37.06s (Approximately 0.17 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
  - veritas
  - filevol
registries:
  console:8443:
    Blocked: false
    Insecure: false
    Location: console:8443
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: console:8443
  docker.io:
    Blocked: true
    Insecure: false
    Location: docker.io
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: docker.io
  registry.access.redhat.com:
    Blocked: true
    Insecure: false
    Location: registry.access.redhat.com
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: registry.access.redhat.com
  registry.redhat.io:
    Blocked: true
    Insecure: false
    Location: registry.redhat.io
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: registry.redhat.io
  search:
  - console:8443
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 10
    paused: 0
    running: 9
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /tmp
  imageStore:
    number: 11
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1650363392
  BuiltTime: Tue Apr 19 10:16:32 2022
  GitCommit: ""
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.2

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**
[root@net182-host183 ~]# rpm -q podman
podman-4.0.2-6.module+el8.6.0+14877+f643d2d6.x86_64

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Comment by leolovejj** [comment]
This issue does not for Pure IPv4 and IPv6 and only occur for dual stack. Just wanted to confirm if Podman support dual stack config in docker compose yml file.

**Comment by Luap99** [comment]
Please trim down the compose file to the absolute minimum needed to reproduce this. I doubt that all the specific options are required. And if you use an external network provide the podman network inspect output.
Also please format your file content properly with three backticks ````, right now this is very hard to read.

**Comment by leolovejj** [comment]
[root@net182-host183 ~]# docker inspect nic0
[
     {
          "name": "nic0",
          "id": "84ed3baa52eac40113c6698b057ddf9db5d28691d540cde8b06112f478f33c2c",
          "driver": "macvlan",
          "network_interface": "nic0",
          "created": "2022-06-27T12:10:43.891231737Z",
          "subnets": [
               {
                    "subnet": "172.17.0.0/16",
                    "gateway": "172.17.0.1"
               },
               {
                    "subnet": "2200::/64",
                    "gateway": "2200::1"
               }
          ],
          "ipv6_enabled": true,
          "internal": false,
          "dns_enabled": false,
          "options": {
               "mode": "bridge"
          },
          "ipam_options": {
               "driver": "host-local"
          }
     }
]

**Comment by leolovejj** [comment]
The static IPv4 and IPv6 address cannot be assigned even by running "podman run" command.
![image](https://user-images.githubusercontent.com/100113781/175947296-bc42f536-b24b-4598-88ba-fa7c87cea623.png)

**Comment by Luap99** [comment]
What cni version is installed?

**Comment by leolovejj** [comment]
Output of podman version:
[root@net182-host183 ~]# podman version
Client: Podman Engine
Version: 4.0.2
API Version: 4.0.2
Go Version: go1.17.7

Built: Tue Apr 19 10:16:32 2022
OS/Arch: linux/amd64

Package info (e.g. output of rpm -q podman or apt list podman):
[root@net182-host183 ~]# rpm -q podman
podman-4.0.2-6.module+el8.6.0+14877+f643d2d6.x86_64

**Comment by leolovejj** [comment]
We are still using docker-compose on our machine. I tried to install the stable 1.0.3 version podman-compose and it will prompt error while creating container with the compose file, so I installed the latest 1.0.4 dev version podman-compose.

Even I have specified the static IP address for both IPv4 and IPv6, only IPv4 address is recognized and configured, seems the podman-compose can only recognize the ipv4_address and will ignore the ipv6_address in the docker-compose file. This can be confirmed by the command output printed.
![image](https://user-images.githubusercontent.com/100113781/176092425-d04b4275-eb6c-42fe-ad15-3c9eeee0d90c.png)

Also tried to only specify the static IP address for IPv6, the podman-compose still cannot recognize it.
![image](https://user-images.githubusercontent.com/100113781/176092938-83067c36-6209-4fba-b288-44633aea6c0b.png)

So there are two issues:
1. podman cannot set dual stack static IP address by using the following command:
    podman run -itd --name=master --network=nic1 --ip 172.17.0.11 --ip6 2200::11 78e580790333 /bin/bash
2. podman-compose does not support to set static IPv6 address from docker-compose file. 

For the 1st issue, I tried to compile the latest podman with the latest code downloaded from github, the command can work well.
![image](https://user-images.githubusercontent.com/100113781/176095689-3fbbcd18-99f6-4a82-a861-715840a70847.png)
For the 2nd issue, please confirm if podman-compose support to set static IPv6 address from docker-compose file.

**Comment by leolovejj** [comment]
Checked /usr/local/lib/python3.6/site-packages/podman_compose.py, it indeed only support ipv4_address now.
![image](https://user-images.githubusercontent.com/100113781/176112466-88428d72-95a5-44d4-9f8c-ae4e5a285150.png)

May I know when ipv6_address will be supported by podman_compose?

**Comment by Luap99** [comment]
You need at least cni version 1.0 or use netavark.

Podman compose is not developed by us so I cannot answer that.

**Comment by leolovejj** [comment]
How to check the cni version and netavark?

**Comment by Luap99** [comment]
`rpm -q containernetworking-plugins`

You can check if podman is using netavark or cni with `podman info --format {{.Host.NetworkBackend}}`

**Comment by leolovejj** [comment]
We are using CNI 0.9.1, after upgrading to CNI 1.0.0, the static IP address for dual stack can be configured successfully.  Thanks for your support.
