### ISSUE TITLE
chromium --shm-size vs pod catch 22

### ISSUE THREAD

**Issue by deanpeterson** [containers/podman#14746]
I am running into an issue with a customer using electronjs in a container. Chromium is immediately using up all of the memory allowed for /dev/shm. Outside a pod formation I can set --shm-size=1g and get around the problem. However, the electronjs pod has to communicate on "localhost" to another pod and we can't change the code. If I try to use --shm-size in a pod, I get the error: cannot set shmsize when running in the host IPC Namespace. So, i'm in a bit of a cache 22 situation. Is there a good solution for this out of memory issue involving chromium?

**Comment by cdoern** [comment]
can you try `--net=slirp4netns` in conjunction with `--shm-size` on the pod level? This should allow you to still be able to communicate on localhost and set the shm.
