### ISSUE TITLE
Windows Podman 4.1.1 MSI Installer has postive virus scan result

### ISSUE THREAD

**Issue by TacticalPenGuinn** [containers/podman#14759]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

/kind feature

**Description**

Doing a virus scan on the windows podman msi installer triggers two findings. winpath.exe and win-sshproxy.exe

podman-v4.1.1.msi
![image](https://user-images.githubusercontent.com/5886548/176230206-b1b199cb-cde2-42d8-8c91-330bf2dcb5bf.png)

Winpath.exe
![image](https://user-images.githubusercontent.com/5886548/176229902-761d1aec-25db-46f2-811f-39507eadf9cf.png)

win-sshproxy.exe
![image](https://user-images.githubusercontent.com/5886548/176230076-46317cdd-ffc3-4eb2-aa95-ef467ee7b96d.png)

**Steps to reproduce the issue:**

1. Download msi 

2. upload msi to Virus Total: https://www.virustotal.com/gui/home/upload (if installed, navigate to install directory and upload winpath.exe and win-sshproxy.exe to virus total.)

3. view report

**Describe the results you received:**

Positive scan result for mis installer  and/or winpath.exe and win-sshproxy.exe

**Describe the results you expected:**

A clean virus scan

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.16.15
Git Commit:   f73d8f8875c2be7cd2049094c29aff90b1150241
Built:        Wed Jun 15 08:17:12 2022
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.16.15
Built:        Wed Jun 15 09:32:06 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.1-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.1, commit: '
  cpuUtilization:
    idlePercent: 99.71
    systemPercent: 0.22
    userPercent: 0.07
  cpus: 12
  distribution:
    distribution: fedora
    variant: container
    version: "35"
  eventLogger: file
  hostname: Zachary-ThinkPad
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.4.72-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 26383814656
  memTotal: 26673844224
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.5-2.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 7516192768
  swapTotal: 7516192768
  uptime: 45.32s
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 269490393088
  graphRootUsed: 677715968
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1655303526
  BuiltTime: Wed Jun 15 09:32:06 2022
  GitCommit: ""
  GoVersion: go1.16.15
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-v4.1.1.ms
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Luap99** [comment]
I think this is pretty much the same as #13415.
Is there anything podman can do about that?
@n1hility PTAL

**Comment by n1hility** [comment]
Right. False positives for ML-based scanners are very common, so there is not much we can do. If you are using one of these platforms, you can flag it as a false positive in your client or admin policy to let it through.  In the future, we can look at codesigning our artifacts, which will help since they tend to lower suspicion with these tools.

**Comment by TacticalPenGuinn** [comment]
Are winpath.exe and win-sshproxy.exe compiled as part of the podman build process or are the provided dependencies?

**Comment by n1hility** [comment]
Both are compiled as part of the build of podman.

To add more detail. The ML scanners are trained models which are fed “normal” and “abnormal” binaries. Effectively that amounts to statistical similarity. A small exe file, like what Golang produces, with a different structure than a typical vscode native app looks different to it, so suspected malware. 

See also: https://go.dev/doc/faq#virus

**Comment by n1hility** [comment]
Closing this since there is not much we can do. My hope is that once we look at signing many of these false flags will be suppressed.
