### ISSUE TITLE
podman wait: new timeout, possibly deadlock

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#14761]
Started right after #14685, but please don't anybody get tunnel vision on it: correlation causation etc.
```
# podman-remote run ...
# podman-remote kill ...
# podman-remote wait ...
timeout: sending signal TERM to command ?/var/tmp/go/src/github.com/containers/podman/bin/podman-remote?
```
Seen root and rootless; fedora 35, 36, and ubuntu. So far, `podman-remote` only.

Once it triggers, the entire system is unusable, podman-everything hangs, and tests die after the Cirrus timeout.

### [sys] 101 podman stop - unlock while waiting for timeout
* fedora-35 : sys remote fedora-35 root host [remote]
  * PR #14597
    * [06-27 16:49](https://api.cirrus-ci.com/v1/task/6006984553005056/logs/main.log)
* fedora-36 : sys remote fedora-36 rootless host [remote]
  * PR #14742
    * [06-27 11:46](https://api.cirrus-ci.com/v1/task/6755034766508032/logs/main.log)
  * PR #14717
    * [06-28 12:24](https://api.cirrus-ci.com/v1/task/6116050067521536/logs/main.log)
* ubuntu-2110 : sys remote ubuntu-2110 root host [remote]
  * PR #14733
    * [06-27 10:37](https://api.cirrus-ci.com/v1/task/5565201654218752/logs/main.log)
 
(Labeling `remote`, and waiting to see if stupid bot removes the tag. I'm betting it will.)

**Comment by Luap99** [comment]
> Sigh. Does anyone know why the bot removes my `remote` label?

Yes, because the action for some reason automatically removes the label if the regex is not matched and at least from my quick look there is no reason to turn this off.

**Comment by edsantiago** [comment]
Ohhhhhhhh..... this: https://github.com/containers/podman/blob/d095053b9cda99b009d102c5b595e77b980ee1a0/.github/issue-labeler.yml#L11-L13

...which, in its [documentation](https://github.com/github/issue-labeler), states
>Should the regular expression not match, the label will be removed.

...which seems stupid to me: if the reporter has taken the time to explicitly set a label, an inflexible rule must not override. This is such an obvious bug that there's already [an issue open for it](https://github.com/github/issue-labeler/issues/12). Unfortunately, it's been ignored for two years.

Oh well. Thanks for the pointer @Luap99. I guess we have to live with that for now.

**Comment by vrothberg** [comment]
I extracted the following reproducer:
```bash
echo "..."                                                                                                                                
date                                                                                                                                      
echo run                                                                                                                                  
$PODMAN run -d --replace --name=123 alpine sh -c "trap 'echo Received SIGTERM, ignoring' SIGTERM; echo READY; while :; do sleep 0.2; done"
echo stop                                                                                                                                 
$PODMAN stop -t 3 123 &                                                                                                                   
echo kill                                                                                                                                 
$PODMAN kill 123                                                                                                                          
echo wait                                                                                                                                 
$PODMAN wait 123                                                                                                                          
```

Works with local podman.  Failed on the 2nd run with podman-remote.  `podman ps` etc. hangs which lets me believe there is some deadlock.  I did not further analyze yet.

**Comment by vrothberg** [comment]
Note that the concurrent `stop` and `kill` trigger the deadlock.  It somehow aligns with the observations in the CI where all subsequent attempts to remove the container time out.

**Comment by vrothberg** [comment]
Another thing that looks suspicious when running podman-remote:
> WARN[0023] StopSignal SIGTERM failed to stop container 123 in 3 seconds, resorting to SIGKILL

The default stop timeout is 10 seconds.  Not yet sure why it's 3 for remote.

**Comment by vrothberg** [comment]
The deadlock happens when the container is in "stopping" state during kill.

**Comment by vrothberg** [comment]
Ah, got it. I'll wrap up a PR.

The problem was that `kill` didn't collect the exit code. Neither does `stop` when `kill` kicks in in the "stopping" state.
