### ISSUE TITLE
Podman exits with success when there is nothing to do

### ISSUE THREAD

**Issue by jhsware** [containers/podman#14771]
podman 4.0.2

### Background
We had a common template for our systemd service unit files where we sometimes pass an env-var as extra params when starting podman. If the env var isn't defined it is passed as an empty string. Spent two days trying to figure out why the container never started running.

### What happened
Podman looked for ENTRYPOINT (which didn't exist) instead of CMD (which did exist) due to the empty env-var. Podman didn't believe there was anything to do and exited with **success**.

### What I expected to happen
If podman doesn't find anything to do it should exit with **fail** and reason "no ENTRYPOINT found"

**Comment by baude** [comment]
reproducer please ...

**Comment by rhatdan** [comment]
Since we never got any additional feedback, closing.
