### ISSUE TITLE
When using :z mount option, avoid relabeling files with lsetxattr() unless required

### ISSUE THREAD

**Issue by jkroon81** [containers/podman#14786]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When using ":z" mount option, podman will recursively relabel the SELinux context of all mounted files, causing the "Change" timestamp to be updated, even if the files would have the correct SELinux context to begin with. This is not so great since it tricks tools like git/gitk into thinking that the file content might have changed. Also I guess it inflicts a little more "wear and tear" on the disk.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.3
Built:        Wed Jun 15 16:31:58 2022
OS/Arch:      linux/amd64
```

**Comment by giuseppe** [comment]
it adds a cost for the general use case where the files have the wrong label.  We'd have first to first to read the extended attribute and then overwrite it.  Can't it be addressed outside of Podman and then just use the volume without relabelling?

**Comment by jkroon81** [comment]
Is it really true that the "general" case is that they have the wrong label ? At least in my case, where I run podman multiple times with the same "environment", it is only the first run that actually changes the file selinux contexts. I don't modify them outside of podman. Sure, it can be addressed outside of podman, but having podman do the check would relieve the user from taking on that responsibility. But I understand that maybe there is not a clear "yes" or "no" here.

**Comment by jkroon81** [comment]
And if I understand correctly, it would only add an additional cost the *first* time, when it is doing the relabeling. Subsequent runs would just read the context, which I guess would be slightly cheaper than updating the new context all the time.

**Comment by giuseppe** [comment]
maybe we could just check the root mount, if the label is wrong, then we assume it was never relabelled and we always setxattr, as we do now.  Instead if the root mount has the correct label, we assume it was already relabelled and we can enter the new mode where we do a getxattr first.

**Comment by rhatdan** [comment]
We should do this at the Podman side not in go-selinux.

**Comment by rhatdan** [comment]
This does leave the risk, that files under the top level directory are mislabeled, and :z will not fix.  But I think this is reasonable to allow.

**Comment by rhatdan** [comment]
In Podman we are already doing this here:

**Comment by rhatdan** [comment]
I can update my PR for goselinux with your improvement.

**Comment by giuseppe** [comment]
> In Podman we are already doing this here:
> https://github.com/containers/podman/blob/main/libpod/container_internal_linux.go#L3239-L3255

but that doesn't cover bind mounts that are used by different containers.

Said so, I'd personally leave it as it is now, if you specify `:z` then you get the files relabelled.

The user could also fix it with something like `podman run -v $PATH:/foo:z alpine true` to relabel the path then always use it without `:z`.

**Comment by jkroon81** [comment]
> This does leave the risk, that files under the top level directory are mislabeled, and :z will not fix. But I think this is reasonable to allow.

Assuming I understood the comment above, with the suggested "new" mode suggested by Giuseppe, why would :z not relabel files under the top level directory ?

**Comment by jkroon81** [comment]
Looking at the increased complexity introduced by the proposed patches, I'd say it is a small price to pay for relieving the user from having to remember whether or not he has run podman with :z at some point before.

**Comment by rhatdan** [comment]
New mode by Giuseppe will update labels. if they are different.

**Comment by jkroon81** [comment]
Was there some improvement merged for the "bug" I reported ?

**Comment by rhatdan** [comment]
Yes this should be optimized in podman 4.2

**Comment by jkroon81** [comment]
Thanks Daniel!

**Comment by jkroon81** [comment]
I'm using podman v4.2.0, latest in Fedora 36, but I am still seeing that gitk thinks that files have changed. The folder I mount bind into the container does contain relative symlinks that point to other folders inside the top directory I am mounting. Does this somehow trick the optimization in some way, making podman still relabel files unnecessarily ?

**Comment by rhatdan** [comment]
Could you give an example podman command where this is happening, and show the volume you are mounting?

**Comment by jkroon81** [comment]
I pushed a repo here: https://github.com/jkroon81/podman-issue-14786

You can clone it, then do:
make
stat dir/foobar
make
stat dir/foobar

and you will see that the "Change" timestamp is updated after every "make".

**Comment by jkroon81** [comment]
I understand that I can handle this outside of podman, by using an approach like I've done in the branch "optimize-relabel-outside-podman" in the "podman-issue-14786" repo, but if possible I would prefer if podman could just handle it automatically.
