### ISSUE TITLE
Rootless networking setup not fully working with netavark

### ISSUE THREAD

**Issue by sebastien-coavoux** [containers/podman#14780]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

NB : can't test on 4.1.1 because no binaries available for Linux / can't compile it at the moment. 
Looking at the changelog however does not make me believe it is fixed right now

When running in non root, podman, with backend netavark seems to not lookup the network properly leading to 2 issue that prevent rootless container to have dns  with aardvark-dns.  As far as I can see dns for rootless is supported : https://github.com/containers/netavark/pull/168

**Steps to reproduce the issue:**
```bash
# As non root user

#1st issue
podman system reset
podman network create rootless
podman --log-level=trace run -d --rm --name test0 --network=rootless jonlabelle/network-tools sleep infinity

# 2nd issue
# I Manually generated podman.json with 
# podman network inspect podman | jq '.[0] | .dns_enabled = true' --indent 5 > $HOME/.local/share/containers/storage/networks/podman.json
# to have dns_enabled for podman network. 
# podman network inspect podman show dns_enabled to true after that
podman --log-level=trace run -d --rm --name test2 --network=podman jonlabelle/network-tools sleep infinity
```

**Describe the results you received:**
1 > https://gist.github.com/sebastien-coavoux/91d4cffc30d8bde86a0ed20acaed6cd1
I would like to highlight in addition of the stack track at the end the lines
```
DEBU[0000] Successfully loaded 2 networks               
[...]
DEBU[0000] Successfully loaded 1 networks               
```
Which make me believe that network are found but somewhere in the validation info is not passed on

2 > https://gist.github.com/sebastien-coavoux/77cd3cf6f8df6ba112115eca799113f0
Highlighting netavark line :  
```
DEBU[0000] Successfully loaded network podman: &{podman 2f259bab93aaaaa2542ba43ef33eb990d0999ee1b9924b557b7be53c0b7a1bb9 bridge podman0 2022-06-29 21:12:46.176281014 +0000 UTC [{{{10.88.0.0 ffff0000}} 10.88.0.1 <nil>}] false false true map[] map[] map[driver:host-local]}
 
[...]

TRAC[0000] netavark command: printf '{"container_id":"1a2911922faf64a1d8b2bc4fb5455c531288f1a19ea0ac7e7019e02a04c97452","container_name":"test2","networks":{"podman":{"static_ips":["10.88.0.4"],"aliases":["1a2911922faf"],"interface_name":"eth0"}},"network_info":{"podman":{"name":"podman","id":"2f259bab93aaaaa2542ba43ef33eb990d0999ee1b9924b557b7be53c0b7a1bb9","driver":"bridge","network_interface":"podman0","created":"2022-06-29T21:19:45.707958376Z","subnets":[{"subnet":"10.88.0.0/16","gateway":"10.88.0.1"}],"ipv6_enabled":false,"internal":false, "dns_enabled":false, "ipam_options":{"driver":"host-local"}}}}' | /usr/libexec/podman/netavark setup /run/user/8000/netns/netns-ca2d29de-1421-395d-d4b6-ab091cb80980 
```
Here dns_enabled is false on the last line but true on the first (third boolen is true)

**Describe the results you expected:**
1 > The pod running and aardvark-dns started as low user
2 > aardvark-dns started as low user

**Additional information you deem important (e.g. issue happens only occasionally):**
Logic setup seems to reside in common. Some snippet in  believe the code end up reaching : 

https://github.com/containers/common/blob/0b482d01472ecf915fec93aed49c385b68c3a740/libnetwork/netavark/run.go#L32 (validation)
https://github.com/containers/common/blob/0b482d01472ecf915fec93aed49c385b68c3a740/libnetwork/netavark/run.go#L65 (log dumping command)
https://github.com/containers/common/blob/main/libnetwork/netavark/network.go#L272 (get network)

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7

Built:      Tue May 10 14:40:19 2022
OS/Arch:    linux/amd64

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.0-1.module_el8.6.0+2878+e681bc44.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 06c32370025d64d0d05684a247e9aec66a049fae'
  cpus: 8
  distribution:
    distribution: '"almalinux"'
    version: "8.4"
  eventLogger: file
  hostname: app05.prod.novalocal
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-305.3.1.el8_4.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 13411139584
  memTotal: 15745335296
  networkBackend: netavark
  ociRuntime:
    name: runc
    package: runc-1.0.3-2.module_el8.6.0+2878+e681bc44.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.3
      spec: 1.0.2-dev
      go: go1.17.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-2.module_el8.6.0+2878+e681bc44.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 0
  swapTotal: 0
  uptime: 705h 43m 52.28s (Approximately 29.38 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1652193619
  BuiltTime: Tue May 10 14:40:19 2022
  GitCommit: ""
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.2

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.0.2-6.module_el8.6.0+2878+e681bc44.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No - See Note at the very beginning

**Comment by flouthoc** [comment]
Hi @sebastien-coavoux , Thanks for creating the issue.

For the 1st part i,e panic in podman i think issue is with older libnetwork could you please try using newer version. @Luap99 Could confirm this better.

For the 2nd part I don't think `dns` in supported on default network i.e network : `podman` see https://github.com/containers/podman/blob/main/docs/tutorials/basic_networking.md#default-network

**Comment by Luap99** [comment]
There is no panic. This is a simple stack trace from the error which is the normal behaviour on log level trace.

@flouthoc dns can/should work on any network when the setting is turned on


Both issues are likely the same, the problem is that podman cannot see the networks in the rootless netns which is weird.
Please run `podman unshare --rootless-netns` and check if the `$HOME/.local/share/containers/storage/networks/` is there?

**Comment by sebastien-coavoux** [comment]
Good news, I have a workaround !

@Luap99 the rootless-netns shell made me realize that it was not able to access $HOME in it. This is because that use has an "exotic" home in `/var/lib/deploy` . Creating a `seb` user with defaults worked well. 

Not sure if there is a fix to have in podman like add a warning. Maybe a simple note in the doc saying "home directory should / should not be X" ?
