### ISSUE TITLE
Replace `github.com/pkg/errors` dependency with native error wrapping

### ISSUE THREAD

**Issue by saschagrunert** [containers/podman#14784]
The package `github.com/pkg/errors` is now in maintenance mode due to the existence of golang native error wrapping. The goal is to do that on a package-by-package basis, where everyone is welcome to contribute.

#### Conversion rules

- use the `errors` import in favor of `github.com/pkg/errors`
- convert `errors.Errorf` to `fmt.Errorf`
- convert `errors.Wrap(err, "…")` to `fmt.Errorf("…: %w", err)` and check that `err != nil` before
- convert `errors.Wrapf(err, "… %s: %s", foo, bar)` to `fmt.Errorf("… %s: %s: %w", foo, bar err)` and check that `err != nil` before
- prefer `errors.New` if no additional format is required
- convert `errors.Cause` to `errors.Is` checks

#### Packages to be converted

- [x] cmd: https://github.com/containers/podman/pull/14785
- [x] hack/test/utils: https://github.com/containers/podman/pull/14829
- [x] libpod:
  - [x] https://github.com/containers/podman/pull/14789
  - [x] https://github.com/containers/podman/pull/14828
- [ ] pkg: https://github.com/containers/podman/pull/14839

**Comment by vrothberg** [comment]
@mtrmac, FYI.  I recall you had some thoughts on replacing `errors.Cause` and `errors.Is` but I may be wrong.

**Comment by mtrmac** [comment]
Note the existence of an automated tool described in https://github.com/sigstore/rekor/pull/834#issue-1242258470 (I haven’t looked at how/whether it works, at least that PR looks good).

**Comment by mtrmac** [comment]
> @mtrmac, FYI. I recall you had some thoughts on replacing `errors.Cause` and `errors.Is` but I may be wrong.

In principle: pkg/errors is an archived repo, so I very much support the general effort of migrating away.

---

Concerns:
- `errors.Cause` does not have an exact replacement. `errors.Cause` goes all the way to the bottom of the `pkg/errors` cause stack, and returns that one error to be compared; `errors.Is`/`errors.As` succeeds if anything on the cause stack matches. (The latter behavior is almost certainly more useful, but it _can_ change previously-correct code — or it can be a reason for an unnoticed bug.). So, ideally, this would require a careful review of every single `errors.Cause` replacement — on rare code paths that might not necessarily have ideal test coverage.
- It’s harder for Go libraries returning errors: `pkg/errors.Wrap*` wrapping is visible by `errors.{As,Is}`, so callers of `errors.{As,Is}` don’t care which one is used; but `errors.Cause` only sees the `pkg/errors.Wrap*` wrapping, and so `errors.Cause` callers are broken when an error creator switches from `errors.Wrap*` to `fmt.Errorf(%w)`. Now, was the use of `pkg/errors.Wrap*` an API contract? Probably not explicitly, but broken callers are not going to be happy.

**Comment by rhatdan** [comment]
I think as long as we go through Podman->Buildah->Common->image->storage we should be fine.
