### ISSUE TITLE
Support staged progression of stop signals

### ISSUE THREAD

**Issue by davejwatson** [containers/podman#14800]
/kind feature

Support staged progression of stop signals

When stopping a pod running PostgreSQL as PID 1, it would be useful to send a TERM to trigger a smart shutdown, followed by an INT to trigger a fast shutdown before falling back to a KILL.

The timeouts between each signal should be configurable.

**Comment by rhatdan** [comment]
This would seem to be a fairly difficult UI to implement, do you have any suggestion, that would not involve a new option? 
Perhaps --stop-signal TERM:5,INT:2 ...

**Comment by davejwatson** [comment]
I think as you suggest the single comma delimited argument would be cleanest. If it's a requirement to have a KILL at the end of the progression then a KILL:10 could be appended if there isn't a KILL in the argument.

**Comment by giuseppe** [comment]
Why cannot it be done using some shell scripting and `sleep`?

**Comment by davejwatson** [comment]
A script on the host could certainly find the appropriate process and send signals to it at the appropriate times. Currently I'm managing the pod with a systemd service which uses podman stop in the ExecStop. Adding in some shell scripting to determine the process to send signals to would work, but is a bit of a hack.

If it's not something that is useful to anyone else I can certainly work around it, but since there is already some flexibility in the way podman handles stopping a pod I thought it was worth raising this as a use case.

**Comment by davejwatson** [comment]
Ah I'd use podman kill --signal, rather then looking for a process, so not as messy as I'd originally thought

**Comment by rhatdan** [comment]
Since the scripted podman kill --signal will satisfy this need I am closing.
