### ISSUE TITLE
Podman Machine does not work out of the box on a fresh install of Fedora Workstation 36

### ISSUE THREAD

**Issue by vorburger** [containers/podman#14809]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm new to and learning about _Podman Machine_ and got an error which I haven't further researched much yet, but can't find much interesting about when searching for it online, so I thought I would let you know about it here. Presumably you meant for this to "just work"? Perhaps the experience could be improved with a better error message or even just some doc update somewhere. I'm happy to help contribute it, once I understand the root cause better.

**Steps to reproduce the issue:**

1. Fresh install of Fedora Workstation 36, all packages up to date, no additional new packages installed yet
1. `podman machine init`
1. `podman machine start`

**Describe the results you received:**

`Error: unable to start host networking: "could not find \"gvproxy\" in one of [/usr/local/libexec/podman /usr/local/lib/podman /usr/libexec/podman /usr/lib/podman].  To resolve this error, set the helper_binaries_dir key in the `[engine]` section of containers.conf to the directory containing your helper binaries."`

**Describe the results you expected:**

No error, working podman machine.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.3
Built:        Wed Jun 15 16:31:58 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpuUtilization:
    idlePercent: 92.83
    systemPercent: 2.68
    userPercent: 4.49
  cpus: 12
  distribution:
    distribution: fedora
    variant: workstation
    version: "36"
  eventLogger: journald
  hostname: think
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.18.7-200.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 55224799232
  memTotal: 66868674560
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.5-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 10h 25m 24.19s (Approximately 0.42 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/vorburger/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 1
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/vorburger/.local/share/containers/storage
  graphRootAllocated: 510389125120
  graphRootUsed: 9167990784
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /home/vorburger/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1655303518
  BuiltTime: Wed Jun 15 16:31:58 2022
  GitCommit: ""
  GoVersion: go1.18.3
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.1.1-1.fc36.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical / bare metal host, no VM.

**Comment by rhatdan** [comment]
@lsm5 PTAL

**Comment by vorburger** [comment]
Oh OK I see, I just poked around this a little bit... so this `gvproxy` thing is from https://github.com/containers/gvisor-tap-vsock (from https://gvisor.dev), and it's missing on a fresh install of Fedora Workstation 36. 

I was able to get it to work after:

    sudo dnf install -y podman-gvproxy

Perhaps the "first user experience" could be improved here. Perhaps you would like to consider making `podman-gvproxy` a dependency of the `podman` package, if there is no reason not to?

**Comment by rhatdan** [comment]
I am not sure if it should be a recommends or not, definitely not a requires.  I agree, podman machine should throw an error or warning when it is not installed, and clearly as the user to install it.

@ashley-cui PTAL

**Comment by lsm5** [comment]
> I am not sure if it should be a recommends or not, definitely not a requires. I agree, podman machine should throw an error or warning when it is not installed, and clearly as the user to install it.

@rhatdan currently `podman-plugins` does have `Recommends: podman-gvproxy` but `podman` itself has no dependency on podman-plugins or podman-gvproxy. If the main podman package provides the `podman machine` command, then I think podman should have a hard requirement on podman-gvproxy. @mheon @vrothberg wdyt?

**Comment by rhatdan** [comment]
Can we make podman recommends podman-plugins?

**Comment by lsm5** [comment]
> Can we make podman recommends podman-plugins?

@rhatdan Sure. I can go ahead with it if no objections.

> IMHO There is no reason to install it by default. I mean how many people want to run podman machine on fedora?

@Luap99 if we're cool with a helpful error message pointing to the right package (may need to account for multiple distros), then that's fine by me too.

**Comment by Luap99** [comment]
podman-plugins only contains the dnsname cni plugin, we do not need/want this on netavark/aardvark systems.

**Comment by rhatdan** [comment]
Ok let's just add recommends gvproxy to podman.

**Comment by lsm5** [comment]
> Ok let's just add recommends gvproxy to podman.

added to rawhide, will add to f36 whenever we cut a new release.

**Comment by lsm5** [comment]
I'm gonna close this issue as the fix will land in fedora soon and it's not really an upstream issue.

Reopen if anything..
