### ISSUE TITLE
TestEnvVarValue fails on several architectures

### ISSUE THREAD

**Issue by siretart** [containers/podman#14819]
/kind bug
**Description**

I've updated the Debian package to version 4.1, and while the package builds and seeimgly  works fine on amd64 and arm64, any other architectures fail while running the testsuite. I've seen two kind of failures:

On:
 - i386 (32bit intel)
 - armel
 - armhf
 - mipsel

The test TestEnvVarValue fails with this output:

```
=== RUN   TestEnvVarValue/ResourceFieldRefNoLimitMemory
-246611968 8343322624
    play_test.go:787: 
        	Error Trace:	play_test.go:787
        	Error:      	Not equal: 
        	            	expected: (*string)(0xa3f73ec)
        	            	actual  : (*string)(0xa3491c8)
        	            	
        	            	Diff:
        	Test:       	TestEnvVarValue/ResourceFieldRefNoLimitMemory
=== RUN   TestEnvVarValue/ResourceFieldRefNoRequestMemory
-246611968 8343322624
    play_test.go:787: 
        	Error Trace:	play_test.go:787
        	Error:      	Not equal: 
        	            	expected: (*string)(0xa3f752c)
        	            	actual  : (*string)(0xa349260)
        	            	
        	            	Diff:
        	Test:       	TestEnvVarValue/ResourceFieldRefNoRequestMemory
=== RUN   TestEnvVarValue/ResourceFieldRefNoLimitCPU
4 4
=== RUN   TestEnvVarValue/ResourceFieldRefNoRequestCPU
4 4
--- FAIL: TestEnvVarValue (0.01s)
```

I note that these are all 32bit architectures, and the test fails while comparing a pointer.

There is a different failure signature on:

- s390x
- mips64el
- ppc64el

```
=== RUN   TestMonitorTwoDirGood/bad-primary-new-addition
time="2022-07-03T23:35:24Z" level=error msg="Failed loading hooks for /tmp/hooks-test-primary-1983903746/0a.json: parsing hook \"/tmp/hooks-test-primary-1983903746/0a.json\": unrecognized hook version: \"-1\""
time="2022-07-03T23:35:24Z" level=error msg="Failed loading hooks for /tmp/hooks-test-primary-1983903746/0a.json: parsing hook \"/tmp/hooks-test-primary-1983903746/0a.json\": unrecognized hook version: \"-1\""
expected:  <nil>
actual:  &{[{/bin/sh [] [] 0xc00001a458}] [] [] [] [] []}
```

(at least that's what I think fails).

I note that all these architectures are 64bit.

**Comment by siretart** [comment]
All build logs can be seen from https://buildd.debian.org/status/package.php?p=libpod&suite=experimental which currently looks like this:

![image](https://user-images.githubusercontent.com/1878436/177148820-ba0a41c9-d9d7-46c8-b02a-345eb43f3d8f.png)

**Comment by siretart** [comment]
Also, this has been reported as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1014309

**Comment by Luap99** [comment]
I don't think the TestEnvVarValue test is correct. It should not compare pointers there, I don't understand how this even works on x86_64.

**Comment by siretart** [comment]
I tend to concur:

https://github.com/containers/podman/blob/5d5cb402cb6be818d6efd52d2198b00a55df0f1b/pkg/specgen/generate/kube/play_test.go#L781

indicates that `result` is actually a pointer that needs to be dereferenced instead of comparing to the pointer of the reference value. How can this possibly match?

**Comment by siretart** [comment]
I can (probably) upload a new package with that patch applied later today.

I guess the failure in TestMonitorTwoDirGood is unrelated? -- would you prefer a separate issue for that?

**Comment by Luap99** [comment]
Yes a new issue for the other failure would be good, I haven't looked at that one.

**Comment by siretart** [comment]
@Luap99 yes, I can confirm that your patch makes the test pass on `i386`,  but now it is failing on the TestMonitorTwoDirGood issue:

```
=== RUN   TestMonitorTwoDirGood                                                                                                                                                               
=== RUN   TestMonitorTwoDirGood/good-fallback-addition                                                                                                                                        
=== RUN   TestMonitorTwoDirGood/good-primary-override                                                                                                                                         
=== RUN   TestMonitorTwoDirGood/good-fallback-removal                                                                                                                                         
=== RUN   TestMonitorTwoDirGood/good-fallback-restore                                                                                                                                         
=== RUN   TestMonitorTwoDirGood/bad-primary-new-addition                                                                                                                                      
time="2022-07-04T15:04:04Z" level=error msg="Failed loading hooks for /tmp/hooks-test-primary-2603618593/0a.json: parsing hook \"/tmp/hooks-test-primary-2603618593/0a.json\": unrecognized ho
ok version: \"-1\""                                                                                                                                                                           
time="2022-07-04T15:04:04Z" level=error msg="Failed loading hooks for /tmp/hooks-test-primary-2603618593/0a.json: parsing hook \"/tmp/hooks-test-primary-2603618593/0a.json\": unrecognized ho
ok version: \"-1\""                                                                                                                                                                           
expected:  <nil>                                                                                                                                                                              
actual:  &{[{/bin/sh [] [] 0x963a2b8}] [] [] [] [] []}                                                                                                                                        

```

**Comment by Luap99** [comment]
> @Luap99 yes, I can confirm that your patch makes the test pass on `i386`, but now it is failing on the TestMonitorTwoDirGood issue:
> 
> ```
> === RUN   TestMonitorTwoDirGood                                                                                                                                                               
> === RUN   TestMonitorTwoDirGood/good-fallback-addition                                                                                                                                        
> === RUN   TestMonitorTwoDirGood/good-primary-override                                                                                                                                         
> === RUN   TestMonitorTwoDirGood/good-fallback-removal                                                                                                                                         
> === RUN   TestMonitorTwoDirGood/good-fallback-restore                                                                                                                                         
> === RUN   TestMonitorTwoDirGood/bad-primary-new-addition                                                                                                                                      
> time="2022-07-04T15:04:04Z" level=error msg="Failed loading hooks for /tmp/hooks-test-primary-2603618593/0a.json: parsing hook \"/tmp/hooks-test-primary-2603618593/0a.json\": unrecognized ho
> ok version: \"-1\""                                                                                                                                                                           
> time="2022-07-04T15:04:04Z" level=error msg="Failed loading hooks for /tmp/hooks-test-primary-2603618593/0a.json: parsing hook \"/tmp/hooks-test-primary-2603618593/0a.json\": unrecognized ho
> ok version: \"-1\""                                                                                                                                                                           
> expected:  <nil>                                                                                                                                                                              
> actual:  &{[{/bin/sh [] [] 0x963a2b8}] [] [] [] [] []}                                                                                                                                        
> ```

Isn't this the same failure you mentioned above already?

**Comment by Luap99** [comment]
I took a look at the full log and I do not see any errors with the TestMonitorTwoDirGood tests. All are passing. The output are just logs that are expected.

If you scroll further you find this:
```
FAIL	github.com/containers/podman/pkg/machine [build failed]
FAIL	github.com/containers/podman/pkg/machine/qemu [build failed]
```

**Comment by siretart** [comment]
Indeed, it is.

Thanks, the log is quite long, and I was mistakenly looking for `FAIL:`, whereas I really should have looked for `build failed`. It is, however, quite surprising that the test is producing output about mismatching values, without the test is  actually failing. 

Further down in the log, I see this:

```
# github.com/containers/podman/pkg/machine [github.com/containers/podman/pkg/machine.test]
src/github.com/containers/podman/pkg/machine/config_test.go:25:8: undefined: RemoteConnectionType
# github.com/containers/podman/pkg/machine/qemu [github.com/containers/podman/pkg/machine/qemu.test]
src/github.com/containers/podman/pkg/machine/qemu/config_test.go:41:18: undefined: machine.VMFile
src/github.com/containers/podman/pkg/machine/qemu/config_test.go:83:15: undefined: machine.VMFile
src/github.com/containers/podman/pkg/machine/qemu/config_test.go:94:20: undefined: machine.VMFile
src/github.com/containers/podman/pkg/machine/qemu/config_test.go:106:22: undefined: machine.VMFile
src/github.com/containers/podman/pkg/machine/qemu/config_test.go:124:22: undefined: machine.VMFile
src/github.com/containers/podman/pkg/machine/qemu/config_test.go:131:24: undefined: machine.NewMachineFile
src/github.com/containers/podman/pkg/machine/qemu/machine_test.go:10:12: undefined: MachineVM
```

It seems that this test was written to only compile on `amd64` and `arm64`, maybe qemu support wasn't written for other platforms? -- given that `pkg/machine` code is not used in the Debian package, I'm inclined to just skip that test.

Thanks for helping me navigate reading the log!

**Comment by Luap99** [comment]
You can just skip the pkg/machine test for now. AFAIK the code should be used but only for amd64 and arm64 builds.
You could just check if the `podman machine` command is available.

I will open a PR to fix the missing build tags on the tests.

**Comment by Luap99** [comment]
@siretart I think #14823 should fix all your issues, you can use this patch: https://patch-diff.githubusercontent.com/raw/containers/podman/pull/14823.patch

**Comment by siretart** [comment]
Awesome, I've uploaded your patch as version `4.1.1+ds1-2`, let's see how it goes at https://buildd.debian.org/status/package.php?p=libpod&suite=experimental this time. It seems that at least i386, armhf and ppc64el have already succeeded!

Thank you!
