### ISSUE TITLE
Podman Fails to Mount Volume in `/tmp` on macOS

### ISSUE THREAD

**Issue by Alexhuszagh** [containers/podman#14815]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am currently using Podman version 4.1.1.

**Steps to reproduce the issue:**

The following 2 commands fail:

```bash
$ podman run --rm -it -v /tmp:/tmp ubuntu:20.04 bash
$ podman run --rm -it -v /private/tmp:/tmp ubuntu:20.04 bash
```

This is because `/tmp` is a symlink to `/private/tmp` on macOS. However, the following works fine:

```bash
$ podman run --rm -it -v /Users:/Users ubuntu:20.04 bash
```

**Describe the results you received:**

Podman reports the following:

```text
Error: statfs /tmp: no such file or directory
Error: statfs /private/tmp: no such file or directory
```

**Describe the results you expected:**

Podman should be able to mount tmp directories on macOS, whether if using the canonicalized path (`/private/tmp`) or just using `/tmp`. In case additional debugging information is required, the podman info, version, and brew info for the install is available [here](https://github.com/containers/podman/issues/14492). The macOS version is 10.15.7 (Catalina).

**Comment by rhatdan** [comment]
Could you try the following first:

podman machine init -v /tmp:/tmp -v /private:/private 

We are only defaulting to mounting $HOME into the VM at this time, other directories would need to be added separately.  These directories can be specified in containers.conf.

**Comment by Alexhuszagh** [comment]
I don't have access to my macOS computer today, but this is almost certainly the issue. Can we have a change in error message then, to make it easier for users to understand? Rather than say, "Error: statfs $dir: no such file or directory", it could say, "Error: $dir is not mounted in the VM, you must add the directory when running `podman machine init`".

It would make it much clearer that this is not a bug, and an implementation detail.

**Comment by rhatdan** [comment]
Podman service in the VM has no way of knowing what the user was attempting to do, and does not even realize that it is in a VM. It is reporting the error. Also know way to differentiate a typo from what the user intended.

**Comment by steveoh** [comment]
How do you do this if the machine is already running?
