### ISSUE TITLE
could not start api proxy since expected pipe is not available: podman-westie

### ISSUE THREAD

**Issue by mwoodpatrick** [containers/podman#14811]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

On Windows 11 under WSL-2 when starting machine I'm getting the error

      could not start api proxy since expected pipe is not available: podman-westie

**Steps to reproduce the issue:**

1. In powershell run: podman machine start westie.

**Describe the results you received:**

Starting machine "westie"
API forwarding for Docker API clients is not available due to the following startup failures.
        could not start api proxy since expected pipe is not available: podman-westie

Podman clients are still able to connect.
Machine "westie" started successfully

**Describe the results you expected:**

machine would start without proxy error

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.16.15
Git Commit:   f73d8f8875c2be7cd2049094c29aff90b1150241
Built:        Wed Jun 15 06:17:12 2022
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.16.15
Built:        Wed Jun 15 07:32:06 2022
OS/Arch:      linux/amd64

**Output of `podman info --debug`:**

host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.1-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.1, commit: '
  cpuUtilization:
    idlePercent: 99.91
    systemPercent: 0.07
    userPercent: 0.02
  cpus: 8
  distribution:
    distribution: fedora
    variant: container
    version: "35"
  eventLogger: file
  hostname: MarkSpectre14
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.102.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 1223491584
  memTotal: 2002829312
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.5-2.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 1073741824
  swapTotal: 1073741824
  uptime: 15m 37.39s
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 15
    paused: 0
    running: 0
    stopped: 15
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 1081180868608
  graphRootUsed: 13338923008
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 15
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1655303526
  BuiltTime: Wed Jun 15 07:32:06 2022
  GitCommit: ""
  GoVersion: go1.16.15
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

podman-v4.1.0.msi

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mwoodpatrick** [comment]
After running 

 podman machine stop westie

podman machine start westie

I got the expected result, where can I find info on what the error means any suggestions on how to debug why this issue happens I have seen this issue a few times now

podman machine start westie
Starting machine "westie"
API forwarding listening on: npipe:////./pipe/docker_engine

Docker API clients default to this address. You do not need to set DOCKER_HOST.
Machine "westie" started successfully

**Comment by n1hility** [comment]
Since the pipe file it’s complaining about is the machine named file this would mean that a previous run was still holding the pipe file. There is two possibilities where that might happen. One is a race, where the exiting process still held the file briefly. The other possibility is that you had a stale win-sshproxy process that was somehow still running (it’s normally shut down as part of stop)

Since it cleared up after a restart it sounds more like a race. Are you automating start and stop with scripting or running in two terminal Windows? If you were seeing this just from serial start and stop in the same terminal session, there’s a possibility there are conditions Windows is delayed in releasing the pipe after process exit. If that is indeed the case we could look at retrying to resolve the race (at least for the machine named pipe)

**Comment by mwoodpatrick** [comment]
Many thanks for the info, much appreciated. I was just manually starting and stopping the machine, I will see if I can figure out more about the conditions under which this is happening and update the bug report

**Comment by n1hility** [comment]
I looked into this and see the underlying problem. Will follow up with a PR

**Comment by beerai** [comment]
I seem to randomly run into this from time to time. Recreating the podman machine is the only thing I've found to resolve this. Is there another way to find what's using the pipe and kill it?
