### ISSUE TITLE
.containerenv

### ISSUE THREAD

**Issue by loynoir** [containers/podman#14812]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

```bash
$ cd "$(mktemp -d)"
$ echo 'FROM ubuntu' > Dockerfile
$ podman run -v "${PWD}":/run docker.io/safewaters/docker-lock lock generate
```

**Describe the results you received:**
```bash
$ ls .containerenv
.containerenv
```

**Describe the results you expected:**
```bash
$ ls .containerenv
ls: cannot access '.containerenv': No such file or directory
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 4.1.1
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
pacman -S podman podman-compose
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by giuseppe** [comment]
already fixed upstream with #14582

**Comment by loynoir** [comment]
@giuseppe
But isn't pr merged 20 days ago, and 4.1.1 is released 19 days ago?
This still appear in 4.1.1.

**Comment by loynoir** [comment]
BTW, if `.containerenv` is something like `/.dockerenv`, I suggest maybe create it at not mount-bind-able location like `/`.

**Comment by giuseppe** [comment]
> @giuseppe
> But isn't pr merged 20 days ago, and 4.1.1 is released 19 days ago?
> This still appear in latest 4.1.1.

the release branch for 4.1 doesn't include that fix, we would have to backport it, or wait for the next release

**Comment by giuseppe** [comment]
> BTW, if `.containerenv` is something like `/.dockerenv`, I suggest maybe create it at not mount-bind-able location like `/`.

the disadvantage with that solution is that the file will end-up in all the images when you snapshot a container, instead `/run` is likely to be on a `tmpfs`

**Comment by rhatdan** [comment]
I think this can wait until next release.
