### ISSUE TITLE
Windows Podman is using the default user to control created machines

### ISSUE THREAD

**Issue by mwoodpatrick** [containers/podman#14814]
/kind bug

**Description**

It looks like windows podman is using the default user to control created machines/distros. I hit a [WSL issue](https://github.com/microsoft/WSL/issues/8573) when trying to run vscode from the Linux command line inside a podman machine. So I tried running vscode from the PowerShell command line:

    code --remote wsl+podman-westie /home/user

This did open vscode in the desired directory but ran as root. I added a wsl.conf directory in /etc/ setting the default user. Rerunning the above command line did open vscode in the podman machine at the correct directory and running as user "user". However later I tried to restart the machine using "podman machine start westie" and it failed with a permissions error. It seems like the podman command line should specify the root user when sending wsl requests

**Steps to reproduce the issue:**

1. Create a wsl.conf file specifying default user as "user"

2. Run podman machine start <machinename>

**Describe the results you received:**

	PS C:\Users\mlwp> podman machine start westie
	Starting machine "westie"
	/bin/bash: line 1: /root/bootstrap: Permission denied
	Error: WSL bootstrap script failed: exit status 126

**Describe the results you expected:**

Podman machine should be started

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.16.15
Git Commit:   f73d8f8875c2be7cd2049094c29aff90b1150241
Built:        Wed Jun 15 06:17:12 2022
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.16.15
Built:        Wed Jun 15 07:32:06 2022
OS/Arch:      linux/amd64

**Output of `podman info --debug`:**

host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.1-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.1, commit: '
  cpuUtilization:
    idlePercent: 99.89
    systemPercent: 0.08
    userPercent: 0.03
  cpus: 8
  distribution:
    distribution: fedora
    variant: container
    version: "35"
  eventLogger: file
  hostname: MarkSpectre14
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.102.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 1303953408
  memTotal: 2002829312
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.5-2.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 1073741824
  swapTotal: 1073741824
  uptime: 51m 55.65s
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 15
    paused: 0
    running: 0
    stopped: 15
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 1081180868608
  graphRootUsed: 14505598976
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 20
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1655303526
  BuiltTime: Wed Jun 15 07:32:06 2022
  GitCommit: ""
  GoVersion: go1.16.15
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

podman-v4.1.0.msi

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@n1hility PTAL

**Comment by n1hility** [comment]
Similar topic: https://github.com/containers/podman/discussions/14571

While ideally our WSL integration could be enhanced so that the wsl prompt takes you in as a standard user, its likely to still have problems if vscode is using wsl.exe to directly execute commands (most likely). The issue is that podman is running inside of systemd inside of a nested namespace we create. We can use /etc/profile.d/ to auto enter a login from wsl, but in the case of a direct command execution, bash is bypassed. If they allow you to customize the wsl command we have a wrapper script called enterns that can be used (e.g. wsl enterns podman info). I haven't looked at it to know if they have any flexibility here.

It might be possible to get it working if this is launched from inside wsl (e.g. code .) 

The remote ssh or container backends to vscode might be worth exploring until we have a solution.
