### ISSUE TITLE
win11上安装初始化后出现问题

### ISSUE THREAD

**Issue by git136975643** [containers/podman#14820]
podman machine init命令执行后，由于网速问题有fail。
然后重新执行podman machine init就提示“Error: podman-machine-default: VM already exists”

然后我执行 podman machine start命令就提示“安装其中一个文件系统时出现错误。有关详细信息，请运行'dmesg'。
/bin/bash: line 1: /root/bootstrap: No such file or directory
Error: WSL bootstrap script failed: exit status 127”

**Comment by git136975643** [comment]
podman machine rm 后再 podman machine init：“Failed to set locale, defaulting to C.UTF-8”
“Reinstalled:
  shadow-utils-2:4.9-9.fc35.x86_64

Complete!
Configuring system...
Error: could not create ssh keys: exec: "C:\\Users\\13697\\.ssh\\wsl.exe": file does not exist”

**Comment by zhangguanzhang** [comment]
please use the English to report your question

**Comment by n1hility** [comment]
This sounds like #14416 

Are you running the podman command in the c:\Windows\System32 directory? If so change directories to somewhere else and rerun. Alternatively you can use powershell which does not start in system32.

**Comment by git136975643** [comment]
我删了podman machine 重新在D盘初始化【成功了】但是遇到2个小问题：
第一个，下载问题，需要翻墙，不然就报错如下：
PS D:\> podman machine init
Error: Get "https://github.com/fedora-cloud/docker-brew-fedora/tree/35/x86_64/": read tcp 192.168.28.122:61234->20.205.243.166:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
PS D:\> podman machine init
Error: Get "https://github.com/fedora-cloud/docker-brew-fedora/tree/35/x86_64/": dial tcp 20.205.243.166:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
PS D:\> podman machine init
Error: Get "https://github.com/fedora-cloud/docker-brew-fedora/tree/35/x86_64/": dial tcp 20.205.243.166:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
PS D:\> podman machine init
Error: head request failed: http://github.com/fedora-cloud/docker-brew-fedora/raw/35/x86_64/fedora-35-x86_64.tar.xz: Head "https://raw.githubusercontent.com/fedora-cloud/docker-brew-fedora/35/x86_64/fedora-35-x86_64.tar.xz": net/http: TLS handshake timeout
PS D:\> podman machine init
Error: Get "https://github.com/fedora-cloud/docker-brew-fedora/tree/35/x86_64/": dial tcp 20.205.243.166:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
PS D:\> podman machine init
Error: read tcp 192.168.28.122:61282->20.205.243.166:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

第二个问题，设置utf-8失败：
PS D:\> podman machine init
Extracting compressed file
Importing operating system into WSL (this may take 5+ minutes on a new WSL install)...
Installing packages (this will take awhile)...
安装其中一个文件系统时出现错误。有关详细信息，请运行'dmesg'。
Failed to set locale, defaulting to C.UTF-8

**Comment by n1hility** [comment]
@git136975643 thanks. Could you paste the output of `wsl -l -v` and `wsl --status`. I could be wrong, but those errors look like version 1 of WSL is in use. Podman machine requires WSL2. If that is the case, you can switch to wsl 2 by doing 

```
wsl --set-default-version 2
podman machine rm
podman machine init
```

**Comment by git136975643** [comment]
PS C:\Users\13697> wsl -l -v
  NAME                      STATE           VERSION
* Solus                     Stopped         2
  podman-machine-default    Stopped         2
PS C:\Users\13697> wsl --status
默认分发：Solus
默认版本：2

适用于 Linux 的 Windows 子系统最后更新于 2022/7/5
适用于 Linux 的 Windows 子系统内核可以使用“wsl --update”手动更新，但由于你的系统设置，无法进行自动更新。
 若要接收自动内核更新，请启用 Windows 更新设置:“在更新 Windows 时接收其他 Microsoft 产品的更新”。
 有关详细信息，请访问https://aka.ms/wsl2kernel。

内核版本： 5.10.102.1

**Comment by n1hility** [comment]
@git136975643 ok thanks for checking that. Are you able to manually download https://github.com/fedora-cloud/docker-brew-fedora/raw/35/x86_64/fedora-35-x86_64.tar.xz? The earlier errors indicate a connectivity problem fetching it.

If that download completes successfully you could use it to manually init like so (or alternatively retry podman machine init)
```
podman machine init --image-path .\fedora-45-x86_64.tar.xz
```

**Comment by elkan1788** [comment]
> @git136975643 ok thanks for checking that. Are you able to manually download https://github.com/fedora-cloud/docker-brew-fedora/raw/35/x86_64/fedora-35-x86_64.tar.xz? The earlier errors indicate a connectivity problem fetching it.
> 
> If that download completes successfully you could use it to manually init like so (or alternatively retry podman machine init)
> 
> ```
> podman machine init --image-path .\fedora-35-x86_64.tar.xz
> ```

@n1hility Hi guys, I was meet  the podman init failed on Windows10 system, then try you give step with special image path parameter, but stilled got failed. Some error message output on console like below:

```
C:\Users\senhui.li>wsl --update
正在安装: 适用于 Linux 的 Windows 子系统
已安装 适用于 Linux 的 Windows 子系统。

C:\Users\senhui.li>wsl -l -v
  NAME                      STATE           VERSION
* podman-machine-default    Stopped         2

C:\Users\senhui.li>podman machine list
NAME        VM TYPE     CREATED     LAST UP     CPUS        MEMORY      DISK SIZE

C:\Users\senhui.li>podman machine init --image-path .\Downloads\fedora-39-x86_64.tar.xz
Extracting compressed file
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
正在导入，这可能需要几分钟时间。
已存在具有所提供名称的分发。
Error code: Wsl/Service/0x800700b7
Error: the WSL import of guest OS failed: exit status 0xffffffff

C:\Users\senhui.li>podman --version
podman version 4.6.2

```

There was my first time to tried used podman tool, and then I also tried use the Podman Desktop app try to initialized the podman machine, but waited for long time couldn't get any reponse messge. 

![image](https://github.com/containers/podman/assets/1217096/36385e92-c7d7-4359-928e-f665654188e9)

Click the troubleshooting icon got logs like below:

```
error : main ↪️ Kubeconfig path C:\Users\senhui.li\.kube\config provided does not exist. Skipping.
warn : MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 extensions-started listeners added. Use emitter.setMaxListeners() to increase limit
log : main ↪️ PluginSystem: received dom-ready event from the UI
log : main ↪️ Telemetry request error: Error: read ECONNRESET
log : main ↪️ Delayed startup, flushing 7 events
log : main ↪️ System ready. Loading extensions...
log : main ↪️ Activating extension (podman-desktop.compose)
log : main ↪️ Activating extension (podman-desktop.docker)
log : main ↪️ Activating extension (podman-desktop.kind)
log : main ↪️ Activating extension (podman-desktop.kube-context)
log : main ↪️ [kube-context] starting extension kube-context
log : main ↪️ Activating extension (podman-desktop.lima)
error : main ↪️ [lima] Could not find socket at C:\Users\senhui.li\.lima\podman\sock\podman.sock
error : main ↪️ [lima] Could not find config at C:\Users\senhui.li\.lima\podman\copied-from-guest\kubeconfig.yaml
log : main ↪️ Activating extension (podman-desktop.podman)
log : main ↪️ Activating extension (podman-desktop.registries)
log : main ↪️ Activating extension (podman-desktop.compose) ended
log : main ↪️ Activating extension (podman-desktop.docker) ended
log : main ↪️ Activating extension (podman-desktop.kube-context) ended
log : main ↪️ Activating extension (podman-desktop.lima) ended
log : main ↪️ Activating extension (podman-desktop.registries) ended
log : main ↪️ [kind] kind extension is active
log : main ↪️ Activating extension (podman-desktop.kind) ended
log : main ↪️ [kind] kind extension is active
debug : main ↪️ [podman] Error while pinging docker as podman Error: connect ENOENT //./pipe/docker_engine
error : main ↪️ (node:7740) UnhandledPromiseRejectionWarning: Error: EINVAL: invalid argument, stat '//./pipe/'
(Use `Podman Desktop --trace-warnings ...` to show where the warning was created)
error : main ↪️ (node:7740) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
log : main ↪️ [kind] kind extension is active
debug : main ↪️ [compose] Error while pinging docker Error: connect ENOENT //./pipe/docker_engine
log : main ↪️ Activating extension (podman-desktop.podman) ended
log : main ↪️ PluginSystem: initialization done.
log : main ↪️ Autostarting container engine
log : main ↪️ [kind] kind extension is active
error : main ↪️ Unable to fetch the available extensions: Timeout awaiting 'secureConnect' for 500ms
error : main ↪️ Unable to fetch the available extensions: Timeout awaiting 'secureConnect' for 500ms
error : main ↪️ Unable to fetch the available extensions: Timeout awaiting 'secureConnect' for 500ms
log : main ↪️ Telemetry request error: Error: read ECONNRESET
log : main ↪️ Telemetry request error: Error: read ECONNRESET
log : main ↪️ Telemetry request error: Error: read ECONNRESET
log : main ↪️ Telemetry request error: Error: read ECONNRESET
log : main ↪️ Telemetry request error: Error: read ECONNRESET
```

Seems that not friendly for Chinese user to run podman app and environment. I just want to use Podman to build different virtual environments on my computer for experiments, how can I do to fixed these meet error. Please give some suggestions. 

Thanks.

**Comment by elkan1788** [comment]
There were seems podman machine init command failed, I was use wsl list command found that podman-machine-default name in list, why? So I removed this strange VM throught used wsl command, and then retried the podman machine init command , but stilled got failed result, the output error message like below:

```
C:\Users\senhui.li\Downloads>podman machine init --image-path=.\fedora-39-x86_64.tar.xz       "
Extracting compressed file
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
正在导入，这可能需要几分钟时间。
操作成功完成。
Configuring system...
grep: /etc/ssh/sshd_config: No such file or directory
sh: line 1: /etc/ssh/sshd_config: No such file or directory
Error: could not configure SSH port for guest OS: exit status 1
```

So is that the VM image somethings wrong?
