### ISSUE TITLE
CI: runc is not being tested

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#14833]
Root cause, as best I can tell, is https://github.com/containers/automation_images/pull/115. This was supposed to make ubuntu use runc, but it didn't. ubuntu is using crun. Confirmation: #13376 brought in those new VM images, but the [ubuntu sys log](https://cirrus-ci.com/task/4867185968414720?logs=main#L11) clearly shows:
```
[+0006s] # Arch:amd64 OS:ubuntu21.10 Runtime:crun Rootless:false Events:journald Logdriver:journald Cgroups:v2+systemd Net:cni
                                             ^^^^
```
Solution is going to require a VM dance, and some way to actually log in to ubuntu to confirm, so it's not something I can do. It will have to wait for @cevich's return.

**Comment by edsantiago** [comment]
@cevich we cannot do that. `criu` is completely broken. There is an [f35 build](https://bodhi.fedoraproject.org/updates/FEDORA-2022-e5cc3b49e9) but it's not stable yet. And, I have no idea where things stand on Ubuntu.

**Comment by cevich** [comment]
> There is a criu issue

Excellent.  Yep, just gotta be the "squeeky wheel" sometimes to get things done.  As you probably realize, this will take a while to move through the "prior-fedora" repository workflows and be released.  However, if you want to speed that up, there's no shame in fudging our image-build scripts to temporary `dnf install -y $PRERELEASE_URL` for F35.

> Too many confusing places to track

OMG, I've had to start grouping and color-coding my browser tabs :frowning_face:

**Comment by cevich** [comment]
If I wasn't clear (and if you don't want to wait weeks), I'm totally okay with a temporary `dnf install -y $BODHI_URL` in the cache-image packaging scripts.  At least if we can get the Fedora's squared away, adding a `skip("TODO: issue https://blah.blah")` for Ubuntu tests isn't unprecedented.

**Comment by mihalicyn** [comment]
@edsantiago Ed, please let me know if you have any problems with CRIU and help if help is needed. We haven't changed anything in the CRIU code, this is was just a build issue, because CRIU was build against old version of Glibc. From my point of view, after Adrian @adrianreber detected the problem and triggered CRIU rebuild all should start fork flawlessly.

What's the problem with Ubuntu?

**Comment by edsantiago** [comment]
@mihalicyn thank you! As I wrote in bodhi, the criu f35 build works perfectly. Unfortunately it's stuck in bodhi limbo.

Ubuntu: my recollection is that podman checkpoint tests failed on Ubuntu also. The error messages give no visibility into the reason, so I (perhaps naïvely) assumed that it was the same glibc problem. I have no way to log into an Ubuntu system, so there's no way for me to investigate further. My plan was: as soon as criu f35 gets into stable, re-run my VM-building PR, then run podman tests on those VMs, and see how things go.

If you have a way to un-stuckify bodhi, such as forcing gating tests to run, that would speed things up - but I've been in the bodhi-hell game before and know how difficult it can be to get it unstuck.

**Comment by mihalicyn** [comment]
> thank you! 

It's my pleasure!

>Ubuntu: my recollection is that podman checkpoint tests failed on Ubuntu also. 

hm... I can recall some problem with overlayfs on Ubuntu kernels.
https://bugs.launchpad.net/ubuntu/impish/+source/linux/+bug/1967924

If overlayfs was used in the podman containers then I'm almost sure that it's the same problem.

**Comment by cevich** [comment]
If Ed's speaking of our podman CI tests, those all use the vfs driver, not overlay.  Though I believe the system tests would use overlay.
