### ISSUE TITLE
--pull=newer is undocumented

### ISSUE THREAD

**Issue by rptaylor** [containers/podman#14846]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
There are 3 [options](https://docs.podman.io/en/latest/markdown/podman-run.1.html#pull-always-missing-never) for --pull: always, missing, never.

In my application I have a preference to check for a new image from the registry if it is available, but a strong requirement that the application has to run without a dependency on the registry, in case it might be unavailable.

In my application script I have found myself writing this because there is no other way AFAICT to achieve the desired behaviour:
```
podman pull  registry/image ; podman run --pull=never registry/image
```
That doesn't seem right, an option `podman run --pull=try`  would be better, with behaviour similar to `always`, but just print a warning if the image was not found in the registry, and still run the image if present locally.

```
try:  Pull the image from the first registry it is found in as listed in registries.conf. Print a warning if it is not found in the registries. Then run the image if it is present locally, otherwise raise an error.
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

I read the latest documentation for available pulling options.

**Comment by rptaylor** [comment]
Another option would be --pull=always  with another option like --fallback-to-local-images which ignores the error raised about the image missing from the registry.

**Comment by TomSweeneyRedHat** [comment]
@rptaylor it might be late night brain on my end, but I'm not 100% sure what you're suggesting.  Is what you are suggesting that --try would do is:

1)  Attempt to pull the image from the registry
    a)  If found, ignore the local image (if any) and use the new image.
    b)  skip following steps

2) Check to see if the image exists already on local storage.
     a) If found, use the local image
     b) if not found (either in Registry or Local Storage), Raise "image not found" error.

**Comment by rptaylor** [comment]
@TomSweeneyRedHat  Basically yes. In pseudo code:
```
attempt to pull image from the registry
if pull succeeded:
  run pulled image
else:
  print "warning failed to pull image, trying local storage"
  look in local storage
  if found in local storage:
    run found image
  else:
    raise error "image not found from registry or local storage"
```

**Comment by giuseppe** [comment]
> In my application script I have found myself writing this because there is no other way AFAICT to achieve the desired behaviour:
> 
> ```
> podman pull  registry/image ; podman run --pull=never registry/image
> ```

I'd suggest doing what you are already doing.  Why do you think it is wrong?

**Comment by vrothberg** [comment]
```
$ podman tag alpine does.not.exist/alpine
$ podman run --rm --pull=newer does.not.exist/alpine true
```

**Comment by vrothberg** [comment]
Opened https://github.com/containers/common/pull/1085 to improve the code comments.  We can copy that over to man pages of Buildah & Podman.

**Comment by rptaylor** [comment]
Aha a secret option! 

> I'd suggest doing what you are already doing. Why do you think it is wrong?

I thought it did not seem like a good pattern to use two commands when it should be possible with one. To pull , then run, when run has a parameter specifying how to pull, yet none of the possible options appeared to match the desired behaviour, implied to me there should be another option.

Anyway --newer works, thanks!

**Comment by rhatdan** [comment]
Shucks now the secret is out.
