### ISSUE TITLE
podman-remote wait: Error getting exit code from DB: no such exit code

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#14859]
Seen just now:
```
$ podman-remote --url unix:/tmp/podman_tmp_mnLg wait gfKskJHy37
Error: getting exit code of container ebff09951585fcda59dfeceabfaab084751a8303a7cd981420c32c1d0c38b656 from DB: no such exit code
```
Only one so far. Seems suspiciously related to issue #14761 and PR #14830.

### [sys] 203 podman kill - concurrent stop
* fedora-36 : sys remote fedora-36 rootless host [remote]
  * PR #14852
    * [07-07 12:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5862726869188608/html/sys-remote-fedora-36-rootless-host.log.html#t--00203)

**Comment by vrothberg** [comment]
Thanks for filing, @edsantiago.

@mheon FYI

**Comment by vrothberg** [comment]
Another one here https://github.com/containers/podman/pull/14839

**Comment by vrothberg** [comment]
I just noticed that the test used `alpine` instead of `$IMAGE`. I'll fix that as well.

**Comment by edsantiago** [comment]
Reopening, sorry. Seen again in two PRs which, as best I can tell, had a branch base that included #14874 

 
### [sys] 203 podman kill - concurrent stop
* fedora-35 : sys remote fedora-35 root host [remote]
  * PR #14932
    * [07-14 12:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5023966229168128/html/sys-remote-fedora-35-root-host.log.html#t--00203)
  * PR #14919
    * [07-13 20:00](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5553131869175808/html/sys-remote-fedora-35-root-host.log.html#t--00203)

**Comment by vrothberg** [comment]
I opened https://github.com/containers/podman/pull/15038 in hope that it will help us get a better understanding of the issue.

**Comment by vrothberg** [comment]
@edsantiago, since https://github.com/containers/podman/pull/15038 merged, I am curious to see new cases of the error with the updated error message.  My hope is that the added container state will help isolate the error source.

**Comment by edsantiago** [comment]
Here you go - hth. [remote f36 rootless](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6210434704343040/html/sys-remote-fedora-36-rootless-host.log.html#t--00205):
```
[+1187s] not ok 205 podman kill - concurrent stop
...
# $ podman-remote --url unix:/tmp/podman_tmp_wJ2p wait 9yvX8WUvps
# Error: getting exit code of container fc1bf1ba67e1366f00f76d5ed4993145573efe1f1c7450240b679d77b245f719 from DB: no such exit code (container in state stopping)
```

**Comment by vrothberg** [comment]
That is indeed _extremely_ helpful. Thank you so much, @edsantiago!

**Comment by vrothberg** [comment]
Taking another look.  I parsed the code yesterday but could not find something.

**Comment by joanbm** [comment]
(Posting for discoverability) With Podman 5.2.1 and Docker-Compose 2.11.0, pressing CTRL+C on `docker-compose up` caused the container to remain in "Stopped" state and further CTRL+C presses just print "no container to kill", 389a4a6cc6ce560c805338e1af6d4f78df57bdb9 fixes it

**Comment by rhatdan** [comment]
@joanbm I changed podman 5.2.1 to podman 4.2.1 Unless your from the future, I think this is what you meant :^)
