### ISSUE TITLE
Podman: Recommended space for /usr ?

### ISSUE THREAD

**Issue by RodGaiotto** [containers/podman#14858]
Folks, I'm kind of desperate.

I'm getting the following error when I try to PULL an image to my server:

podman pull icr.io/ibmz/ibmz-optimized-for-tensorflow:1.0
Trying to pull icr.io/ibmz/ibmz-optimized-for-tensorflow:1.0...
Getting image source signatures
Copying blob bf0ba31193b7 done  
Copying blob 547073c64450 done  
Copying blob 0df320e2d3ad done  
Copying blob 914140142ed8 done  
Copying blob 3d3424784232 done  
Copying blob c5b1aedd8c49 done  
Copying blob f38a90246035 done  
Copying blob 69150699893a done  
Copying config 0bcbb0ac98 done  
Writing manifest to image destination
Storing signatures
ERRO[0008] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: write /usr/bin/chsh: no space left on device 
  ApplyLayer exit status 1 stdout:  stderr: write /usr/bin/chsh: no space left on device
Error: Error committing the finished image: error adding layer with blob "sha256:914140142ed8e3ef55ee37db043a980f8731728e56e161aafeb42b7a08ef1ec9": ApplyLayer exit status 1 stdout:  stderr: write /usr/bin/chsh: no space left on device
vezio@aqlinux1:~> sudo podman pull icr.io/ibmz/ibmz-optimized-for-tensorflow:1.0
Trying to pull icr.io/ibmz/ibmz-optimized-for-tensorflow:1.0...
  unable to retrieve auth token: invalid username/password: unauthorized: The login credentials are not valid, or your IBM Cloud account is not active.
Error: Error initializing source docker://icr.io/ibmz/ibmz-optimized-for-tensorflow:1.0: unable to retrieve auth token: invalid username/password: unauthorized: The login credentials are not valid, or your IBM Cloud account is not active.
vezio@aqlinux1:~> podman --log-level=debug pull icr.io/ibmz/ibmz-optimized-for-tensorflow:1.0
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called pull.PersistentPreRunE(podman --log-level=debug pull icr.io/ibmz/ibmz-optimized-for-tensorflow:1.0) 
DEBU[0000] Reading configuration file "/usr/share/containers/containers.conf" 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf": &{Containers:{Devices:[] Volumes:[] ApparmorProfile:containers-default-0.29.0 Annotations:[] CgroupNS:host Cgroups:enabled DefaultCapabilities:[CAP_AUDIT_WRITE CAP_CHOWN CAP_DAC_OVERRIDE CAP_FOWNER CAP_FSETID CAP_KILL CAP_MKNOD CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETFCAP CAP_SETGID CAP_SETPCAP CAP_SETUID CAP_SYS_CHROOT] DefaultSysctls:[] DefaultUlimits:[] DefaultMountsFile: DNSServers:[] DNSOptions:[] DNSSearches:[] EnableKeyring:true EnableLabeling:false Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin TERM=xterm] EnvHost:false HTTPProxy:false Init:false InitPath:/usr/bin/catatonit IPCNS:private LogDriver:k8s-file LogSizeMax:-1 NetNS:slirp4netns NoHosts:false PidsLimit:2048 PidNS:private SeccompProfile:/usr/share/containers/seccomp.json ShmSize:65536k TZ: Umask:0022 UTSNS:private UserNS:host UserNSSize:65536} Engine:{ImageBuildFormat:oci CgroupCheck:false CgroupManager:cgroupfs ConmonEnvVars:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] ConmonPath:[/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon] DetachKeys:ctrl-p,ctrl-q EnablePortReservation:true Env:[] EventsLogFilePath:/run/user/20729/libpod/tmp/events/events.log EventsLogger:journald HooksDir:[/usr/share/containers/oci/hooks.d] ImageDefaultTransport:docker:// InfraCommand: InfraImage:k8s.gcr.io/pause:3.2 InitPath:/usr/libexec/podman/catatonit LockType:shm MultiImageArchive:false Namespace: NetworkCmdPath: NoPivotRoot:false NumLocks:2048 OCIRuntime:runc OCIRuntimes:map[crun:[/usr/bin/crun /usr/sbin/crun /usr/local/bin/crun /usr/local/sbin/crun /sbin/crun /bin/crun /run/current-system/sw/bin/crun] kata:[/usr/bin/kata-runtime /usr/sbin/kata-runtime /usr/local/bin/kata-runtime /usr/local/sbin/kata-runtime /sbin/kata-runtime /bin/kata-runtime /usr/bin/kata-qemu /usr/bin/kata-fc] runc:[/usr/bin/runc /usr/sbin/runc /usr/local/bin/runc /usr/local/sbin/runc /sbin/runc /bin/runc /usr/lib/cri-o-runc/sbin/runc /run/current-system/sw/bin/runc]] PullPolicy:missing Remote:false RemoteURI: RemoteIdentity: ActiveService: ServiceDestinations:map[] RuntimePath:[] RuntimeSupportsJSON:[crun runc] RuntimeSupportsNoCgroups:[crun] RuntimeSupportsKVM:[kata kata-runtime kata-qemu kata-fc] SetOptions:{StorageConfigRunRootSet:false StorageConfigGraphRootSet:false StorageConfigGraphDriverNameSet:false StaticDirSet:false VolumePathSet:false TmpDirSet:false} SignaturePolicyPath:/etc/containers/policy.json SDNotify:false StateType:3 StaticDir:/home/vezio/.local/share/containers/storage/libpod StopTimeout:10 TmpDir:/run/user/20729/libpod/tmp VolumePath:/home/vezio/.local/share/containers/storage/volumes} Network:{CNIPluginDirs:[/usr/lib/cni] DefaultNetwork:podman NetworkConfigDir:/home/vezio/.config/cni/net.d}} 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /home/vezio/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver vfs                       
DEBU[0000] Using graph root /home/vezio/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/20729/containers    
DEBU[0000] Using static dir /home/vezio/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/20729/libpod/tmp     
DEBU[0000] Using volume path /home/vezio/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] Not configuring container store              
DEBU[0000] Initializing event backend journald          
WARN[0000] Error initializing configured OCI runtime kata: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] using runtime "/usr/bin/runc"                
WARN[0000] Error initializing configured OCI runtime crun: no valid executable found for OCI runtime crun: invalid argument 
INFO[0000] Setting parallel job count to 25             
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called pull.PersistentPreRunE(podman --log-level=debug pull icr.io/ibmz/ibmz-optimized-for-tensorflow:1.0) 
DEBU[0000] Reading configuration file "/usr/share/containers/containers.conf" 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf": &{Containers:{Devices:[] Volumes:[] ApparmorProfile:containers-default-0.29.0 Annotations:[] CgroupNS:host Cgroups:enabled DefaultCapabilities:[CAP_AUDIT_WRITE CAP_CHOWN CAP_DAC_OVERRIDE CAP_FOWNER CAP_FSETID CAP_KILL CAP_MKNOD CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETFCAP CAP_SETGID CAP_SETPCAP CAP_SETUID CAP_SYS_CHROOT] DefaultSysctls:[] DefaultUlimits:[] DefaultMountsFile: DNSServers:[] DNSOptions:[] DNSSearches:[] EnableKeyring:true EnableLabeling:false Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin TERM=xterm] EnvHost:false HTTPProxy:false Init:false InitPath:/usr/bin/catatonit IPCNS:private LogDriver:k8s-file LogSizeMax:-1 NetNS:slirp4netns NoHosts:false PidsLimit:2048 PidNS:private SeccompProfile:/usr/share/containers/seccomp.json ShmSize:65536k TZ: Umask:0022 UTSNS:private UserNS:host UserNSSize:65536} Engine:{ImageBuildFormat:oci CgroupCheck:false CgroupManager:cgroupfs ConmonEnvVars:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] ConmonPath:[/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon] DetachKeys:ctrl-p,ctrl-q EnablePortReservation:true Env:[] EventsLogFilePath:/run/user/20729/libpod/tmp/events/events.log EventsLogger:journald HooksDir:[/usr/share/containers/oci/hooks.d] ImageDefaultTransport:docker:// InfraCommand: InfraImage:k8s.gcr.io/pause:3.2 InitPath:/usr/libexec/podman/catatonit LockType:shm MultiImageArchive:false Namespace: NetworkCmdPath: NoPivotRoot:false NumLocks:2048 OCIRuntime:runc OCIRuntimes:map[crun:[/usr/bin/crun /usr/sbin/crun /usr/local/bin/crun /usr/local/sbin/crun /sbin/crun /bin/crun /run/current-system/sw/bin/crun] kata:[/usr/bin/kata-runtime /usr/sbin/kata-runtime /usr/local/bin/kata-runtime /usr/local/sbin/kata-runtime /sbin/kata-runtime /bin/kata-runtime /usr/bin/kata-qemu /usr/bin/kata-fc] runc:[/usr/bin/runc /usr/sbin/runc /usr/local/bin/runc /usr/local/sbin/runc /sbin/runc /bin/runc /usr/lib/cri-o-runc/sbin/runc /run/current-system/sw/bin/runc]] PullPolicy:missing Remote:false RemoteURI: RemoteIdentity: ActiveService: ServiceDestinations:map[] RuntimePath:[] RuntimeSupportsJSON:[crun runc] RuntimeSupportsNoCgroups:[crun] RuntimeSupportsKVM:[kata kata-runtime kata-qemu kata-fc] SetOptions:{StorageConfigRunRootSet:false StorageConfigGraphRootSet:false StorageConfigGraphDriverNameSet:false StaticDirSet:false VolumePathSet:false TmpDirSet:false} SignaturePolicyPath:/etc/containers/policy.json SDNotify:false StateType:3 StaticDir:/home/vezio/.local/share/containers/storage/libpod StopTimeout:10 TmpDir:/run/user/20729/libpod/tmp VolumePath:/home/vezio/.local/share/containers/storage/volumes} Network:{CNIPluginDirs:[/usr/lib/cni] DefaultNetwork:podman NetworkConfigDir:/home/vezio/.config/cni/net.d}} 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /home/vezio/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver vfs                       
DEBU[0000] Using graph root /home/vezio/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/20729/containers    
DEBU[0000] Using static dir /home/vezio/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/20729/libpod/tmp     
DEBU[0000] Using volume path /home/vezio/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "vfs"   
DEBU[0000] Initializing event backend journald          
WARN[0000] Error initializing configured OCI runtime kata: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] using runtime "/usr/bin/runc"                
WARN[0000] Error initializing configured OCI runtime crun: no valid executable found for OCI runtime crun: invalid argument 
INFO[0000] Setting parallel job count to 25             
WARN[0000] Failed to add podman to systemd sandbox cgroup: dbus: authentication failed 
DEBU[0000] parsed reference into "[vfs@/home/vezio/.local/share/containers/storage+/run/user/20729/containers]icr.io/ibmz/ibmz-optimized-for-tensorflow:1.0" 
Trying to pull icr.io/ibmz/ibmz-optimized-for-tensorflow:1.0...
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf" 
DEBU[0000] Trying to access "icr.io/ibmz/ibmz-optimized-for-tensorflow:1.0" 
DEBU[0000] Returning credentials from /run/user/20729/containers/auth.json 
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]  No signature storage configuration found for icr.io/ibmz/ibmz-optimized-for-tensorflow:1.0, using built-in default file:///home/vezio/.local/share/containers/sigstore 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/icr.io 
DEBU[0000] GET https://icr.io/v2/                       
DEBU[0000] Ping https://icr.io/v2/ status 401           
DEBU[0000] GET https://icr.io/oauth/token?account=iamapikey&scope=repository%3Aibmz%2Fibmz-optimized-for-tensorflow%3Apull&service=registry 
DEBU[0000] GET https://icr.io/v2/ibmz/ibmz-optimized-for-tensorflow/manifests/1.0 
DEBU[0000] Content-Type from manifest GET is "application/vnd.oci.image.manifest.v1+json" 
DEBU[0000] Using blob info cache at /home/vezio/.local/share/containers/storage/cache/blob-info-cache-v1.boltdb 
DEBU[0000] IsRunningImageAllowed for image docker:icr.io/ibmz/ibmz-optimized-for-tensorflow:1.0 
DEBU[0000]  Using default policy section                
DEBU[0000]  Requirement 0: allowed                      
DEBU[0000] Overall: allowed                             
DEBU[0000] Downloading /v2/ibmz/ibmz-optimized-for-tensorflow/blobs/sha256:0bcbb0ac98af3a0cb85d83cc482333079dd7d7ed85b7e52a0ee1528e51e2da88 
DEBU[0000] GET https://icr.io/v2/ibmz/ibmz-optimized-for-tensorflow/blobs/sha256:0bcbb0ac98af3a0cb85d83cc482333079dd7d7ed85b7e52a0ee1528e51e2da88 
Getting image source signatures
DEBU[0000] GET https://icr.io/extensions/v2/ibmz/ibmz-optimized-for-tensorflow/signatures/sha256:cd2bf6b37bc72c52712bf96c22c959372549d419c835d71d6e5d4b94aa7e4cf1 
DEBU[0000] Manifest has MIME type application/vnd.oci.image.manifest.v1+json, ordered candidate list [application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.docker.distribution.manifest.v1+json] 
DEBU[0000] ... will first try using the original manifest unmodified 
DEBU[0000] Downloading /v2/ibmz/ibmz-optimized-for-tensorflow/blobs/sha256:3d342478423248da00d2ee22e1a082dcc617292765d007b151a41207681e9cce 
DEBU[0000] GET https://icr.io/v2/ibmz/ibmz-optimized-for-tensorflow/blobs/sha256:3d342478423248da00d2ee22e1a082dcc617292765d007b151a41207681e9cce 
DEBU[0000] Downloading /v2/ibmz/ibmz-optimized-for-tensorflow/blobs/sha256:0df320e2d3ad60ae06a99867c585adc8d981755cc23acf756c2bde1dd6b6f403 
DEBU[0000] GET https://icr.io/v2/ibmz/ibmz-optimized-for-tensorflow/blobs/sha256:0df320e2d3ad60ae06a99867c585adc8d981755cc23acf756c2bde1dd6b6f403 
DEBU[0000] Downloading /v2/ibmz/ibmz-optimized-for-tensorflow/blobs/sha256:914140142ed8e3ef55ee37db043a980f8731728e56e161aafeb42b7a08ef1ec9 
DEBU[0000] GET https://icr.io/v2/ibmz/ibmz-optimized-for-tensorflow/blobs/sha256:914140142ed8e3ef55ee37db043a980f8731728e56e161aafeb42b7a08ef1ec9 
DEBU[0000] Downloading /v2/ibmz/ibmz-optimized-for-tensorflow/blobs/sha256:547073c644502e0447a015ed06ce2df5a0b9eb92bc89179f4fff509437731a15 
DEBU[0000] GET https://icr.io/v2/ibmz/ibmz-optimized-for-tensorflow/blobs/sha256:547073c644502e0447a015ed06ce2df5a0b9eb92bc89179f4fff509437731a15 
DEBU[0000] Downloading /v2/ibmz/ibmz-optimized-for-tensorflow/blobs/sha256:c5b1aedd8c4992e85732416b2e71be01d69e12758ec95bfffc0baed14aa7e19a 
DEBU[0000] GET https://icr.io/v2/ibmz/ibmz-optimized-for-tensorflow/blobs/sha256:c5b1aedd8c4992e85732416b2e71be01d69e12758ec95bfffc0baed14aa7e19a 
DEBU[0000] Downloading /v2/ibmz/ibmz-optimized-for-tensorflow/blobs/sha256:bf0ba31193b7f3828924c2c0389b758a3114c0ffd95cc0d0583100665ea3a986 
DEBU[0000] GET https://icr.io/v2/ibmz/ibmz-optimized-for-tensorflow/blobs/sha256:bf0ba31193b7f3828924c2c0389b758a3114c0ffd95cc0d0583100665ea3a986 
DEBU[0001] Detected compression format gzip             
DEBU[0001] Using original blob without modification     
DEBU[0001] Detected compression format gzip             
DEBU[0001] Using original blob without modification     
Copying blob bf0ba31193b7 [>-------------------------------------] 3.2KiB / 182.7KiB
Copying blob 547073c64450 done  
Copying blob bf0ba31193b7 done  
Copying blob 547073c64450 done  
DEBU[0001] Downloading /v2/ibmz/ibmz-optimized-for-tensorflow/blobs/sha256:69150699893a9922ca9bffd6de5fad4f98a0cdcd642ee8e5c08e8699fd718da6 
DEBU[0001] GET https://icr.io/v2/ibmz/ibmz-optimized-for-tensorflow/blobs/sha256:69150699893a9922ca9bffd6de5fad4f98a0cdcd642ee8e5c08e8699fd718da6 
Copying blob bf0ba31193b7 done  
Copying blob 547073c64450 done  
Copying blob 0df320e2d3ad [--------------------------------------] 188.1KiB / 172.2MiB
DEBU[0001] Detected compression format gzip             
Copying blob bf0ba31193b7 done  
Copying blob 547073c64450 done  
Copying blob 0df320e2d3ad [>-------------------------------------] 4.1MiB / 172.2MiB
Copying blob 3d3424784232 done  
Copying blob bf0ba31193b7 done  
Copying blob 547073c64450 done  
Copying blob bf0ba31193b7 done  
Copying blob 547073c64450 done  
Copying blob 0df320e2d3ad done  
Copying blob 3d3424784232 done  
Copying blob c5b1aedd8c49 done  
Copying blob 914140142ed8 done  
Copying blob 69150699893a done  
Copying blob f38a90246035 done  
DEBU[0010] No compression detected                      
DEBU[0010] Using original blob without modification     
Copying config 0bcbb0ac98 done  
Writing manifest to image destination
Storing signatures
DEBU[0010] Start untar layer                            
ERRO[0010] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: write /usr/bin/chsh: no space left on device 
DEBU[0011] Error pulling image ref //icr.io/ibmz/ibmz-optimized-for-tensorflow:1.0: Error committing the finished image: error adding layer with blob "sha256:914140142ed8e3ef55ee37db043a980f8731728e56e161aafeb42b7a08ef1ec9": ApplyLayer exit status 1 stdout:  stderr: write /usr/bin/chsh: no space left on device 
  ApplyLayer exit status 1 stdout:  stderr: write /usr/bin/chsh: no space left on device
Error: Error committing the finished image: error adding layer with blob "sha256:914140142ed8e3ef55ee37db043a980f8731728e56e161aafeb42b7a08ef1ec9": ApplyLayer exit status 1 stdout:  stderr: write /usr/bin/chsh: no space left on device
vezio@aqlinux1:~>

Please how much is it needed on the /usr to have it working? I don't think that this is a normal behavior considering my /usr has 10 GBs of free space. I'm wondering if it could be related with any Podman setup error on my side.

`vezio@aqlinux1:~> podman info --debug
host:
  arch: s390x
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.20, commit: unknown'
  cpus: 8
  distribution:
    distribution: '"sles"'
    version: "12.5"
  eventLogger: journald
  hostname: aqlinux1
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 100
      size: 1
    - container_id: 1
      host_id: 1083040
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 20729
      size: 1
    - container_id: 1
      host_id: 1083040
      size: 65536
  kernel: 4.12.14-122.113-default
  linkmode: dynamic
  memFree: 58390163456
  memTotal: 67594760192
  ociRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.3
      spec: 1.0.2-dev
      go: go1.16.10
      libseccomp: 2.4.1
  os: linux
  remoteSocket:
    path: /run/user/20729/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 24h 1m 53.5s (Approximately 1.00 days)
registries:
  search:
  - registry.opensuse.org
  - docker.io
store:
  configFile: /home/vezio/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/vezio/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 2
  runRoot: /run/user/20729/containers
  volumePath: /home/vezio/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1612501938
  BuiltTime: Fri Feb  5 00:12:18 2021
  GitCommit: ""
  GoVersion: go1.13.15
  OsArch: linux/s390x
  Version: 2.2.1`
  
  
  Thank you very much!

**Comment by rhatdan** [comment]
You are using the vfs driver, which is probably using up all of the space on your system.
Make sure you  have fuse-overlayfs installed.  You need to reset your storage, this will remove all containers and images.
$ podman system reset
Then check podman info to make sure you are using the overlay driver
$ podman info

**Comment by RodGaiotto** [comment]
Hi again Dan, thanks again for the help.

I managed to implement fuse-overlayfs:

aqlinux1:~ # fuse-overlayfs --version
fuse-overlayfs: version 1.1.0
FUSE library version 3.6.1
using FUSE kernel interface version 7.29
aqlinux1:~ #

However the result was the same. 

Storing signatures
  Error processing tar file(exit status 1): write /usr/bin/chsh: no space left on device
Error: Error committing the finished image: error adding layer with blob "sha256:914140142ed8e3ef55ee37db043a980f8731728e56e161aafeb42b7a08ef1ec9": Error processing tar file(exit status 1): write /usr/bin/chsh: no space left on device.

Dumb question. When you mention "homedir" you refer to the folder where the containers will be hosted, right?

Thanks!

**Comment by rhatdan** [comment]
Yes your container content is being stored in 
/home/vezio/.local/share/containers/storage

**Comment by vrothberg** [comment]
Did you make sure that the rootless Podman storage driver was set to overlayfs?  You may need to run `podman system reset` before but note that it will remove all local images, containers etc.

Regarding fuse-overlayfs on SLES.  I recommend reaching out through the SUSE customer channels (e.g., Bugzilla).  There is nothing we can do upstream.

**Comment by RodGaiotto** [comment]
@vrothberg Valentin, thank you too for your attention and help!

Please, is there any recommended documentation about  _how to setup rootless Podman storage driver to overlayfs_ ?

Thanks folks!

**Comment by vrothberg** [comment]
@RodGaiotto, to the best of my knowledge there is no tutorial for that.

The [storage.conf man page](https://github.com/containers/storage/blob/main/docs/containers-storage.conf.5.md) is the best shot for docs.

But Podman should be smart enough to default to using `overlay` if the kernel supports rootless overlay fs or when fuse-overlayfs is installed.

**Comment by RodGaiotto** [comment]
Thanks for all the clarifications @vrothberg  and @rhatdan  I appreciate that!
