### ISSUE TITLE
podman pull: can't talk to a V1 container registry

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#14864]
New flake in `int` test setup:
```
Running: podman [options] pull registry.access.redhat.com/ubi8-init
Trying to pull registry.access.redhat.com/ubi8-init:latest...
time="2022-07-07T18:22:15-05:00" level=warning msg="Failed, retrying in 1s ... (1/3). Error: copying system image from manifest list: determining manifest MIME type for docker://registry.access.redhat.com/ubi8-init:latest: Get \"https://registry.access.redhat.com/v2/ubi8-init/manifests/sha256:aaa17f9f2c8c628601688a830df297bf3548236efd7095b6448247bd759aed50\": net/http: TLS handshake timeout"
Error: initializing source docker://registry.access.redhat.com/ubi8-init:latest: can't talk to a V1 container registry
```

log: https://api.cirrus-ci.com/v1/task/5147934521032704/logs/main.log

**Comment by vrothberg** [comment]
Looks like a temporary fart on `registry.access.redhat.com`.

**Comment by vrothberg** [comment]
@edsantiago, have you seen this flake again?

**Comment by edsantiago** [comment]
Last seen July 14 on two tests, all at the same time: [f35 rootless](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6009128647655424/html/int-podman-fedora-35-rootless-host.log.html), [f35 root](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6290603624366080/html/int-podman-fedora-35-root-container.log.html). The common timestamp strongly indicates a problem on the registry.

**Comment by rhatdan** [comment]
@edsantiago any update?

**Comment by vrothberg** [comment]
I think this is a flake on the registry rather than Podman.

**Comment by rhatdan** [comment]
Ok I will close and hope it has gone away.

**Comment by edsantiago** [comment]
Sorry for the late response. My (incomplete) logs do not show any instances since July 14.
