### ISSUE TITLE
Yet another mysterious permissions problem when running rootless

### ISSUE THREAD

**Issue by softwareplumber** [containers/podman#14867]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
 When running a rocky or alma 8.6 container rootles (on a centos stream 8 host), `yum install openssh` consistently fails

`Error: cpio: chown failed - Inappropriate ioctl for device`

when running yum install openssh in a podman container.

**Steps to reproduce the issue:**

1.  using podman 4.0.2 on centos stream 8, run` podman run --rm -it rockylinux:8.6 bash`

2. run `yum install openssh`

**Describe the results you received:**

Install will fail with: 

```
wrror: unpacking of archive failed on file /usr/libexec/openssh/ssh-keysign;62c7b29c: cpio: chown failed - Inappropriate ioctl for device
error: openssh-8.0p1-13.el8.x86_64: install failed
```

**Describe the results you expected:**

openssh will install. Error occurs even when openssh is just a dependency (e.g. when installing git). podman therefore about as useful as a chocolate teapot.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7

Built:      Tue Mar 15 15:15:06 2022
OS/Arch:    linux/amd64
```

**Output of `podman info --debug`:**

```
ERRO[0000] Joining network namespace for container 72e2e9bfe95d05db433a868bae6e68bed700dc734fda23e1588155dc32a31ee7: error retrieving network namespace at /run/user/5001/netns/netns-04c019ca-2f10-b5ee-d4c6-2a16664de571: unknown FS magic on "/run/user/5001/netns/netns-04c019ca-2f10-b5ee-d4c6-2a16664de571": 1021994 
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.0-1.module_el8.7.0+1106+45480ee0.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 235fd1687e002bf8eaa7ea2f999104be869858b4'
  cpus: 48
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: compute2.galifrey.net
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 5000
      size: 1
    - container_id: 1
      host_id: 20000
      size: 400
    uidmap:
    - container_id: 0
      host_id: 5001
      size: 1
    - container_id: 1
      host_id: 20000
      size: 400
  kernel: 4.18.0-394.el8.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 250452189184
  memTotal: 270089506816
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.0.3-3.module_el8.7.0+1106+45480ee0.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.3
      spec: 1.0.2-dev
      go: go1.17.7
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /run/user/5001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-2.module_el8.7.0+1106+45480ee0.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 68719472640
  swapTotal: 68719472640
  uptime: 27h 38m 54.99s (Approximately 1.12 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/jonathan/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.ignore_chown_errors: "true"
  graphRoot: /var/containers/user/jonathan/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 12
  runRoot: /run/user/5001/containers
  volumePath: /var/containers/user/jonathan/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1647371706
  BuiltTime: Tue Mar 15 15:15:06 2022
  GitCommit: ""
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.2

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.0.2-1.module_el8.7.0+1106+45480ee0.x86_6
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No. Its the version in Centos Stream 8. That's a big deal even if the bug is fixed upstream.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by giuseppe** [comment]
```
$ ls -ln /usr/libexec/openssh/ssh-keysign
-r-xr-sr-x. 1 0 ssh_keys 330152 Jan 20 23:51 /usr/libexec/openssh/ssh-keysign
```

the file is owned by ID 0:982 (on my system, the GID might be different for you) but you have only 401 IDs available in the user namespace.

One workaround it is to run something like:

```
$ podman run --uidmap 0:0:100 --uidmap 800:100:300 --rm -it rockylinux:8.6 bash
```

a better fix is to allocate more additional IDs to your user (through `/etc/subuid` and `/etc/subgid` then run `podman system migrate`)

**Comment by softwareplumber** [comment]
Awesome! I completely misunderstood how the id mapping works. Can’t believe how much time I spend on this, really appreciate your help.

Many thanks

**Comment by pcrosemurgy** [comment]
@giuseppe I'm having the same issue was OP and am not sure I follow your solution. I likely have some misunderstanding about how podman works but why would the host's `/usr/libexec/openssh/ssh-keysign` be of concern here? I would expect the container to not depend on the host's `ssh-keysign`.

Thanks in advance!

**Comment by softwareplumber** [comment]
It's not the hosts file but the file that I was attempting to install in the container. The installer - which remember is running inside the podman runtime - attempts to assign a GID outside the range allowed by the ID mapper.

**Comment by pcrosemurgy** [comment]
@softwareplumber Thanks, very helpful!

But how do you know what range of mappings to use – or what GID the installer is trying to use? `podman info --debug` reports:
```yaml
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 10034
      size: 1
    uidmap:
    - container_id: 0
      host_id: 66563
      size: 1
```
Is it possible to determine a valid `--uidmap` range from this?

**Comment by giuseppe** [comment]
you've only one UID and GID available.
