### ISSUE TITLE
exit code of 0 if container failed to start

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#14873]
```
$ podman create --name=123 alpine /123
# Return 0 on a created container is expected.
$ podman wait
0
$ podman start 123
Error: unable to start container "c35e9c150e0d8b749793c9ef8d95872beb8a2be8efbcfb124cf026cb8dfaffd4": crun: executable file `123123` not found in $PATH: No such file or directory: OCI runtime attempted to invoke a command that was not found 
# Return 0 is unexpected since the container clearly exited non-0.
$ podman wait 123
0
```

Note that this behavior predates the recent exit-code changes but I found the behavior while adding new tests.  Docker properly returns/exits with 127 in the upper example.

I'll soon add a new test with a reference on this issue.

@mheon FYI

**Comment by mheon** [comment]
We can, at the very least, refuse to exit cleanly if the OCI runtime did not exit cleanly when starting. To me, this smells like a failure in our parsing logic that attempts to determine if the OCI runtime failure was ENOENT - either it's not parsing that error correctly, or it's not running at all for `podman start`.

**Comment by vrothberg** [comment]
Cannot reproduce anymore.  Podman behaves exactly as Docker does.
