### ISSUE TITLE
`podman-4.1.1` rejects one of only two non-alphanumeric Label characters Docker accepts as valid

### ISSUE THREAD

**Issue by srcshelton** [containers/podman#14883]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

In the [Docker documentation](https://docs.docker.com/config/labels-custom-metadata/), it is stated that the only valid (but currently unenforced) Label format is to start and end with a lower-case letter and contain only lower-case letters, numbers, and periods or hyphens.

On reading this, I updated my labels to fulfil the lower-case requirement and changed underscores for hypens.

However, the output I then get from `podman` is:

```
$ sudo podman image inspect '--format={{.Config.Labels.entrypoint-sum}}' localhost/init:latest
ERRO[0000] Printing inspect output: template: image inspect:1: bad character U+002D '-'
```

… now I understand that this project may not wish to be as opinionated as the Docker project as to the formatting of labels (especially when this is unenforced), but it would be beneficial to at least support the format which Docker has settled on?

**Steps to reproduce the issue:**

1. Create a Container image with a Label in a Docker-recommended format (containing a hyphen);

2. Attempt to `inspect` the image to retrieve the specific label (only).

**Describe the results you received:**

```
ERRO[0000] Printing inspect output: template: image inspect:1: bad character U+002D '-'
```

**Describe the results you expected:**

The label contents to by printed, e.g.

```
$ sudo podman image inspect '--format={{.Config.Labels.maintainer}}' localhost/init:latest
xxx@xxx.me
```

(This being the same image: Labels without a hyphen do work)

Additionally, there should not be a discrepancy between what can be added as a Label and what can be retrieved… unless this is a Go command-line escaping issue, or similar?

**Output of `podman version`:**

```
podman version 4.1.1
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: app-containers/conmon-2.1.2
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.1.2, commit: 99eac3e82289c18465adeab5c522469ad14e5725'
  cpuUtilization:
    idlePercent: 94.63
    systemPercent: 2.82
    userPercent: 2.55
  cpus: 8
  distribution:
    distribution: gentoo
    version: "2.8"
  eventLogger: file
  hostname: dellr330
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.18.0-gentoo
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 1028354048
  memTotal: 68088496128
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: app-containers/crun-1.4.5
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 22949953536
  swapTotal: 25769787392
  uptime: 815h 34m 50.24s (Approximately 33.96 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  localhost:5000:
    Blocked: false
    Insecure: true
    Location: localhost:5000
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: localhost:5000
    PullFromMirror: ""
  search:
  - docker.io
  - docker.pkg.github.com
  - quay.io
  - public.ecr.aws
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 24
    paused: 0
    running: 23
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /space/podman/storage
  graphRootAllocated: 1689739415552
  graphRootUsed: 141281505280
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp/.private/root
  imageStore:
    number: 159
  runRoot: /var/run/podman
  volumePath: /space/podman/volumes
version:
  APIVersion: 4.1.1
  Built: 1655770751
  BuiltTime: Tue Jun 21 01:19:11 2022
  GitCommit: f73d8f8875c2be7cd2049094c29aff90b1150241
  GoVersion: go1.18.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Comment by Luap99** [comment]
This is not valid go template syntax, I would be very surprised if this works with docker.

https://pkg.go.dev/text/template

> The name of a key of the data, which must be a map, preceded by a period, such as .Key The result is the map element value indexed by the key. Key invocations may be chained and combined with fields to any depth: .Field1.Key1.Field2.Key2 Although the key must be an alphanumeric identifier, unlike with field names they do not need to start with an upper case letter. Keys can also be evaluated on variables, including chaining: $x.key1.key2

You have to use the index function:
`{{index .Config.Labels "entrypoint-sum"}}`

**Comment by srcshelton** [comment]
> This is not valid go template syntax
> 
> You have to use the index function: `{{index .Config.Labels "entrypoint-sum"}}`

This would be great to add to the `podman inspect` man-page, which currently says only:

> The keys of the returned JSON can be used as the values for the --format flag (see examples below).

… with the examples not including anything more complex such as the syntax you’ve suggested!
