### ISSUE TITLE
Create a Podman performance tips tutorial

### ISSUE THREAD

**Issue by eriksjolund** [containers/podman#14902]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Add a Podman tutorial that discusses factors that might impact the speed of Podman.

Some sketchy ideas:

* use __--uidmap__ and __--gidmap__ instead of the __--volume__ option `:U`
* use `:O` to avoid local disk
* use a fast OCI runtime (crun)
* use a fast storage driver (native overalyfs)
* reuse the package repository cache with an overlay mount when building container images
* network performance for rootless Podman
  + slirp4netns comes with a performance penalty
  + use socket activation to avoid slirp4netns
  + maybe use rootful Podman with `--user $user` (where __$user != 0__) to avoid slirp4netns
* choosing a host file system (is reflink support important?)
*  whether to use the __podman run__ option __--new__
* use smaller container images
* lazy pulling of container images
* benchmark tip: create a separate account with `sudo useradd testuser &&   sudo machinectl testuser@`

**Comment by afbjorklund** [comment]
Or maybe "use root" ? 😀

At least it could be interesting to at least mention the cost of rootless, when discussing the mitigations ?

Preferably with some benchmarks.
