### ISSUE TITLE
GitHub Actions: Ubuntu: Podman build failed: Connection reset by peer

### ISSUE THREAD

**Issue by ebattat** [containers/podman#14920]
There is a critical but in your latest version on 
Ubuntu version: 22.04
Podman version: 3.4.4+ds1-1ubuntu1
The command that failed:
`podman build -t quay.io/ebattat/benchmark-runner:latest .`
The error:
`error running container: error from /usr/bin/crun creating container for [/bin/sh -c dnf update -y --nobest]: sd-bus call: Connection reset by peer #1994`

Connection reset by peer
Got the following error, while running container
The full GitHub actions [link](https://github.com/redhat-performance/benchmark-runner/runs/7306853603?check_suite_focus=true)

The same workflow run successful several days ago, [link](https://github.com/redhat-performance/benchmark-runner/runs/7229627245?check_suite_focus=true)

**Comment by Luap99** [comment]
Running inside a container requires more setup. see https://www.redhat.com/sysadmin/podman-inside-container

**Comment by ebattat** [comment]
Looks that latest update of podman inside ubuntu container in GitHub Actions cause it.
Can I downgrade podman version or install manually 3.4.2 instead of 3.4.4 ?

**Comment by ebattat** [comment]
Resolved by using docker instead of podman.
I think that Podman team should be synchronized with GitHub actions team regarding issue like that.
 !!!

**Comment by rst0git** [comment]
@mheon This problem looks related to https://github.com/containers/podman/issues/14603.
The current workaround is to use `sudo -E XDG_RUNTIME_DIR= podman ...`

**Comment by rhatdan** [comment]
I believe this is now fixed, or not something Podman needs to/can fix.

Closing, reopen if I am mistaken.

**Comment by samskiter** [comment]
Think I'm seeing this on MS Azure agents - i think the XDG_RUNTIME_DIR is needed if connecting to an external repository? @rhatdan (the auth details after login are stored in `${XDG_RUNTIME_DIR}/containers/auth.json`)
