### ISSUE TITLE
[RFC] `kube play $URL`

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#14955]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Similar to `kubectl apply` I want `podman kube play` to read the K8s yaml from a URL, for instance, `podman kube play https://k8s.io/examples/application/guestbook/redis-leader-deployment.yaml`.

@rhatdan @umohnani8 WDYT?

**Comment by Luap99** [comment]
Sounds like a useful feature but  it is important to mention that this is basically the same as `bash <(curl -s $URL)` from a security point of view. Just like pulling images you should only use this if you can trust the remote server.

**Comment by vrothberg** [comment]
@nicrowe00, feel free to tackle it if you are interested and find time.

**Comment by nicrowe00** [comment]
@vrothberg Sure, I'll take a look.

**Comment by vrothberg** [comment]
Awesome, thanks!  I suggest having a look at the `podman import` code which is already capable of downloading a file.
