### ISSUE TITLE
podman make test fails on wsl-2 Debian 11

### ISSUE THREAD

**Issue by mwoodpatrick** [containers/podman#14953]
/kind bug

**Description**

I'm building and testing TOT podman on my wsl-2 Debian 11 distro. The build completes without issues and basic sanity checks of the generated podman binary run without issue however when running make test some tests pass but some fail. make install also fails. The details are in the attached logs

**Steps to reproduce the issue:**

1. Fork the repo and setup tools as documented in the  [Contributing](https://github.com/mwoodpatrick/podman/blob/main/CONTRIBUTING.md) document
2.make install.tools
3.make binaries
4.make test 2>&1 |tee make.test.log
5.sudo make install 2>&1 | tee make.install.log

**Describe the results you received:**
See attached logs

**Describe the results you expected:**
test & install should pass without error

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.0-dev
API Version:  4.2.0-dev
Go Version:   go1.18.2
Git Commit:   bbb7d4a9fb6049b1f805880f8aef9f3260987189
Built:        Sat Jul 16 04:22:46 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.27.0-dev
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/local/libexec/podman/conmon
    version: 'conmon version 2.1.1, commit: 546e4dbe78c72754053d4029593e7d9fc59adff1'
  cpuUtilization:
    idlePercent: 97.2
    systemPercent: 0.9
    userPercent: 1.9
  cpus: 8
  distribution:
    codename: bullseye
    distribution: debian
    version: "11"
  eventLogger: file
  hostname: MarkSpectre14
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.102.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 891494400
  memTotal: 2002829312
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun_0.17+dfsg-1_amd64
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /mnt/wslg/runtime-dir/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.0.1-2_amd64
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.4.0
  swapFree: 960114688
  swapTotal: 1073741824
  uptime: 2h 20m 31.00s (Approximately 0.08 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/mwoodpatrick/.config/containers/storage.conf
  containerStore:
    number: 8
    paused: 0
    running: 0
    stopped: 8
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/mwoodpatrick/.local/share/containers/storage
  graphRootAllocated: 1081180868608
  graphRootUsed: 71008788480
  graphStatus: {}
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 15
  runRoot: /mnt/wslg/runtime-dir/containers
  volumePath: /home/mwoodpatrick/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0-dev
  Built: 1657970566
  BuiltTime: Sat Jul 16 04:22:46 2022
  GitCommit: bbb7d4a9fb6049b1f805880f8aef9f3260987189
  GoVersion: go1.18.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Using TOT podman from git repo
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

NA

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running with windows 11 wsl Debian 11 distro
[make.install.log](https://github.com/containers/podman/files/9125678/make.install.log)
[make.test.log](https://github.com/containers/podman/files/9125679/make.test.log)

Default Distribution: Alpine
Default Version: 2
WSL version: 0.61.8.0
Kernel version: 5.10.102.1
WSLg version: 1.0.39
MSRDC version: 1.2.3213
Direct3D version: 1.601.0
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22622.290

**Comment by mwoodpatrick** [comment]
[make_podman.msi.log](https://github.com/containers/podman/files/9126477/make_podman.msi.log)
Looks like make podman.msi also fails see attached log

**Comment by Luap99** [comment]
You cannot run the test on windows, they are only designed to run on linux.

The first error in wsl is because your system is not correctly configured for pulling from `registry.access.redhat.com`, check your policy.json file, you might be missing the required gpg keys. 

The docs install is failing because you did not create them. The correct way should be `make && make install`

Running test in wsl seems like something that is expected to fail. WSL is just missing to much important functionality (i.e. systemd).

**Comment by rhatdan** [comment]
Closing issue.
