### ISSUE TITLE
"--passwd-entry" Type Flag For /etc/group 

### ISSUE THREAD

**Issue by p0da** [containers/podman#14965]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Currently podman has a --passwd-entry flag which allows users to specify/customize the entry that is appended to /etc/passwd file. Would it be possible to also include a --group-entry flag to do the same thing for the /etc/group file?

**Comment by giuseppe** [comment]
`--group-entry` makes sense to have.

Would you like to open a PR to add the feature?

**Comment by p0da** [comment]
Unfortunately I am not familiar enough with go make an attempt.

**Comment by rhatdan** [comment]
How are you testing this? What command is blowing up?

**Comment by giuseppe** [comment]
it is not an issue but a feature request, we have `--passwd-entry` but we do not have `--group-entry`

**Comment by boaz0** [comment]
@cdoern mind if I try my luck and work on it?

**Comment by rhatdan** [comment]
@boaz0 Go for it.

**Comment by boaz0** [comment]
still working on it...

**Comment by KR411-prog** [comment]
@boaz0  are you still working on this? or shall I try this?
