### ISSUE TITLE
Option To Create /etc/passwd If It Does Not Exist

### ISSUE THREAD

**Issue by p0da** [containers/podman#14966]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Currently /etc/passwd is not created if it does not initially exist in the image, even if the --passwd/--passwd-entry flags are specified. Would it be possible to implement some option that enables podman to create /etc/passwd (probably /etc/group too) in order for the --passwd and --passwd-entry flags to have an effect in images that don't initially have a /etc/passwd?

**Comment by rhatdan** [comment]
Seems reasonable, interested in opening a PR?

**Comment by p0da** [comment]
Unfortunately I am not familiar enough with go make an attempt at it. However this functionality could also simply be added to the --passwd flag as that is what toggles the appending of entries.

**Comment by giuseppe** [comment]
I don't see why we don't create the file if it is missing, @mheon is it because of some compatibility with Docker?

If that is the case, we could probably add `--passwd=always` to override this check and always create the file

**Comment by mheon** [comment]
I don’t see any reason to not create it.

**Comment by rhatdan** [comment]
I agree we should create it if it does not exists. I don't think Docker has an equivalent. Most likely we just coded it to expect /etc/passwd exists in the container and do not handle ENOEXIST.

**Comment by mheon** [comment]
Yeah, concur. Not many images are missing a passwd file so it's not something we tested or thought of.

**Comment by giuseppe** [comment]
opened a PR: https://github.com/containers/podman/pull/15003

Keep in mind that `--passwd-entry` won't be enough to trigger the entry, you'll need to specify `--user=` as well
