### ISSUE TITLE
remote push gives no output

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#14971]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
`podman-remote` push does not print any output.

**Steps to reproduce the issue:**

```
podman (main) $ ./bin/podman-remote push localhost:5000/nginx
```

**Describe the results you received:**

No output.

**Describe the results you expected:**

Output.

@containers/podman-maintainers let's fix this before the v4.2 release.

**Comment by vrothberg** [comment]
Also happens with Podman v4.1.1.  I wonder how/why we did not catch that in CI.

**Comment by mheon** [comment]
This is separate from progress bars, yes? Printing a digest?

**Comment by vrothberg** [comment]
I'll tackle this one now.
