### ISSUE TITLE
Cannot create network with name "bridge" because it conflicts with a valid network mode

### ISSUE THREAD

**Issue by albertdb** [containers/podman#14983]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Cannot create a network named bridge to make badly written applications (but not changeable) that depend on Docker default network name work.

**Steps to reproduce the issue:**

1. podman network create bridge

**Describe the results you received:**

Error: cannot create network with name "bridge" because it conflicts with a valid network mode

**Describe the results you expected:**

Network is created.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
4.1.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(42/43) Installing podman (4.1.0-r1)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Podman inside Alpine container.

**Comment by albertdb** [comment]
> You should not have to create a network called bridge. Podman already accepts --network bridge and will automatically map this to the default podman network.

@Luap99  It doesn't seem to be the case though the API.

**Comment by Luap99** [comment]
Please provide a full reproducer

**Comment by albertdb** [comment]
> Please provide a full reproducer

Using this project as a basis https://github.com/devonfw-sample/devon4quarkus-reference

Run inside a Docker container (in my case a GitLab runner) with image: `maven:3-eclipse-temurin-11-alpine`

the following commands: 

    apk add --no-cache podman podman-docker
    echo "export TESTCONTAINERS_RYUK_DISABLED=true" >> ~/.bashrc
    source ~/.bashrc
    podman system service --time=0 unix:/var/run/docker.sock & sleep 5
    podman network ls
    docker run --rm hello-world
    mvn package

**Comment by Luap99** [comment]
I don't have time to run such big complicated reproducers, please provide the exact API call where we error.
You can use `podman system service --log-level debug` to see the calls

**Comment by Luap99** [comment]
Should be fixed in the next release (v4.2).

As workaround you could also try setting the default network name to bridge in containers.conf.
