### ISSUE TITLE
podman freezes during build and run commands

### ISSUE THREAD

**Issue by b3n3w** [containers/podman#14989]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman freezes randomly during build and pull commands, which are executed from jenkins server. Afterwards its not possible to execute any command of podman. It will stuck in CLI until the server gets restarted completely. Furthermore i'am not able to kill the podman process by their PID and if check all running processes by htop, i can see, that about 30 "**storage-chown-by-maps**" commands are pending for a rootless owned overlay. 

I already tried to remove the pending overlay folders by sudo and by executing podman / buildah unshare -> rm -rf *overlay* which also freezed.

I checked the kernel log and found the following message:
**overlayfs: conflicting options: userxattr, metacopy=on** 

We're running all of our containers in rootless mode and using the fuse-overlay storage layer for this. 

**Describe the results you received:**

Podman freezes

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.17.5
Built:        Wed Jun 15 18:59:06 2022
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 6b57a50630ae2b1fcdc88e86f10f93e719042c67'
  cpuUtilization:
    idlePercent: 96.86
    systemPercent: 0.45
    userPercent: 2.69
  cpus: 24
  distribution:
    distribution: '"almalinux"'
    version: "9.0"
  eventLogger: file
  hostname: siljenkinsalma
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 981
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 981
      size: 1
    - container_id: 1
      host_id: 12000
      size: 65536
  kernel: 5.14.0-70.17.1.el9_0.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 43099152384
  memTotal: 43911720960
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.4-2.el9_0.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.4
      commit: 6521fcc5806f20f6187eb933f9f45130c86da230
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/981/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-4.el9.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 25768747008
  swapTotal: 25768747008
  uptime: 1m 21.37s
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
  - docker.io
store:
  configFile: /var/lib/jenkins/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 160981585920
  graphRootUsed: 24563388416
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 109
  runRoot: /run/user/981/containers
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1655312346
  BuiltTime: Wed Jun 15 18:59:06 2022
  GitCommit: ""
  GoVersion: go1.17.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.1.1-1.el9.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

OS: AlmaLinux 9.0 (emerald puma)
Kernel:  5.14.0-70.17.1.e19_0.x86_64
VPC Server with 24 Cores and 40GB Memory

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
I don't see fuse-overlays being used from your configuration.

Are you sure these processes are stuck or just slow?

Could you strace them to see where they are stuck?

**Comment by b3n3w** [comment]
> I don't see fuse-overlays being used from your configuration.

Doesn't graphDriverName: overlay means that we're running on fuse-overlay ? 

> Are you sure these processes are stuck or just slow?

Waited for more than 2 Hours. Unfortunately it happend already multiple times. Also for smaller builds which usually take ~ 2 minutes.  

> Could you strace them to see where they are stuck?

Sure. Currently it is running fine again. I will send send you the tracereport next time.

**Comment by giuseppe** [comment]
> > I don't see fuse-overlays being used from your configuration.
> 
> Doesn't graphDriverName: overlay means that we're running on fuse-overlay ?


no, it must show a mountProgram as well, otherwise it is using native overlay.

**Comment by b3n3w** [comment]
> > > I don't see fuse-overlays being used from your configuration.
> > 
> > 
> > Doesn't graphDriverName: overlay means that we're running on fuse-overlay ?
> 
> no, it must show a mountProgram as well, otherwise it is using native overlay.

Oh thank ! You're right. I used an old storage.conf file.

Now its configured like this:

`graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.8.2-1.el9.x86_64
      Version: |-
        fusermount3 version: 3.10.2
        fuse-overlayfs: version 1.8.2
        FUSE library version 3.10.2
        using FUSE kernel interface version 7.31
    overlay.mountopt: nodev,metacopy=on

`

**Comment by rhatdan** [comment]
Closing since this seems like it is solved.
