### ISSUE TITLE
Show WSL rootfs version when downloading 

### ISSUE THREAD

**Issue by gbraad** [containers/podman#15002]
Currently the download of the rootfs only shows a name.
![image](https://user-images.githubusercontent.com/1894/178897178-8aa51ed8-d62b-4058-82a7-fc7b4723a6c5.png)

Recently a version got included to the image repo that is formatted as `v[Fedora version].[image increment]`, eg. https://github.com/containers/podman-wsl-fedora/releases/tag/v36.0.6

Showing this as part of the download can aid in tracking possible issues.

_Originally posted in https://github.com/containers/podman/issues/14698#issuecomment-1183967519_

**Comment by Luap99** [comment]
I think this was already added in https://github.com/containers/podman/pull/14962?
