### ISSUE TITLE
Creation date of the podman-machine is updated when upgrading podman

### ISSUE THREAD

**Issue by slemeur** [containers/podman#15007]
/kind bug

**Description**

During the upgrade from 4.0.2 to 4.1, my current podman-machine has been kept, but the creation date has been updated to the time I did the upgrade - which seems weird.

**Comment by mheon** [comment]
@ashley-cui PTAL

**Comment by ashley-cui** [comment]
This should not happen in the future. We refactored the machine code in 4.1, and so any machine created before 4.1 was migrated from an old struct to a new struct, and marshalled into a new machine file. Inspect uses the creation time of the file as the machine creation time. This bug should not exist for machines created in 4.1 and up, and upgrading from 4.1 -> 4.1.1 or 4.1 -> 4.2 will not see this bug. 

Please re-open if this is not sufficient.
