### ISSUE TITLE
Ability to bypass proxy setting without removing the configuration from the HTTP_PROXY env variable

### ISSUE THREAD

**Issue by slemeur** [containers/podman#15005]
/kind feature

**Description**

Some users have been reporting that sometime they switch/connect/disconnect from network to another network, and in some case they would like the ability to by-pass the proxy configured, but still be able to keep it in the settings.

For now, when `HTTP_PROXY` environment variable is defined, the podman-machine always use it and there is no way to inform the podman-machine to not use it.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:** 4.1

**Comment by Luap99** [comment]
With the latest changes (https://github.com/containers/podman/pull/14893) the proxy env vars are read at podman machine start time. So when you start the machine again and no longer have HTTP_PROXY set or set to a different value it should use the new value.

I think this already fixes your problem.

**Comment by benoitf** [comment]
the env variables might be stored in the `containers.conf` file so it won't skip the read.

there is no `podman machine start --no-proxy`

**Comment by Luap99** [comment]
But when a user does not want the proxy anymore you could just remove the vars from containers.conf?
Or is the ask here that we should allow this on a per machine basis?

**Comment by slemeur** [comment]
@Luap99 Yeah you are right it's completely possible to remove the vars from `containers.conf` but some users have reported that during their day they change few times the network configuration. Sometime they'll be connected under a VPN then they'll be disconnected.
Hence, having the ability to keep the proxy settings, but by-pass them would avoid users to constantly remove/add them.

**Comment by rhatdan** [comment]
Does `HTTP_PROXY="" podman machine start` solve the issue?

**Comment by rhatdan** [comment]
@benoitf Any update?

**Comment by darkmastermindz** [comment]
@slemeur Could you try this and validate? - curious if this works as well on your end after looking at https://github.com/containers/podman-desktop/issues/319

> Does `HTTP_PROXY="" podman machine start` solve the issue?

**Comment by benoitf** [comment]
On podman desktop side we fixed it by removing settings from containers.conf file with a toggle in the tool.

**Comment by rhatdan** [comment]
Since this was fixed in podman-desktop, closing.
