### ISSUE TITLE
devcontainer fail to start when using podman instead of docker

### ISSUE THREAD

**Issue by loynoir** [containers/podman#15001]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

devcontainer fail to start when using podman instead of docker

**Steps to reproduce the issue:**

0. podman run hello world with normal user and root user, ensure podman is working.

1. vscode generate ubuntu devcontainer config

<details>
  <summary>All choose default</summary>

  <p>
 
1.1. `Ctrl+Shift+P`

1.2. remote-containers: add dev configuration files

1.3. choose ubuntu

1.4. choose default
  </p>
</details>

<details>
  <summary>Generated config</summary>
  <p>
 
`.devcontainer/devcontainer.json`
```jsonc
{
	"name": "Ubuntu",
	"build": {
		"dockerfile": "Dockerfile",
		"args": { "VARIANT": "focal" }
	},
	"settings": {},
	"extensions": [],
	"remoteUser": "vscode"
}
```

`.devcontainer/Dockerfile`
```Docker
ARG VARIANT="focal"
FROM mcr.microsoft.com/vscode/devcontainers/base:0-${VARIANT}
```

  </p>
</details>

2. But, user settings `"remote.containers.dockerPath": "podman"`

<details>
  <summary></summary>
  <p>
 
Also tested failed with `"remote.containers.dockerPath": "sudo-podman"`
  </p>
</details>

3. click right down  `reopen in container` button.

**Describe the results you received:**
Image are built using podman, but devcontainer fail to start when using podman instead of docker

**Describe the results you expected:**
Devcontainer using podman start up working like when using docker.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 4.1.1
```

**Output of `podman info --debug`:**

```

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman 4.1.1-2
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Workaround**
Remove `"remoteUser": "vscode"`.

<details>
  <summary></summary>
  <p>
 
Verified `mcr.microsoft.com/vscode/devcontainers/base:0-focal` has user `vscode`.
  </p>
</details>

**Guess**
```sh
$ podman history --no-trunc --format "{{.CreatedBy}}" localhost/vsc-xxx-uid
/bin/sh -c #(nop) USER $IMAGE_USER
...
/bin/sh -c #(nop) USER root
RUN ... bash /tmp/library-scripts/common-debian.sh "${INSTALL_ZSH}" "${USERNAME}" "${USER_UID}" "${USER_GID}" "${UPGRADE_PACKAGES}" "true" "true" ...
...
```

I guess podman is not switch user correctly?

**Edit**
Reproduce repo

https://github.com/loynoir/reproduce-podman-15001

**Comment by Luap99** [comment]
Can you provide the podman commands that are used to build and run the image? What are the error messages you are seeing?

Do you use it on linux, macos, windows?

**Comment by loynoir** [comment]
I'm on ArchLinux.

Last error is
```txt
mkdir: cannot create directory '/root': Permission denied
Exit code 1
Command in container failed: mkdir -p '/root/.vscode-server/bin' && ln -s '/vscode/vscode-server/bin/x64/{{hashA}}' '/root/.vscode-server/bin/{{hashA}}'
```

**Comment by loynoir** [comment]
Docker
```txt
Start: Run in container: test -d /home/vscode/.vscode-server
Start: Run in container: test -d /home/vscode/.vscode-remote
...
```

Podman
```txt
Start: Run in container: test -d /root/.vscode-server
Start: Run in container: test -d /root/.vscode-remote
...
```

**Comment by rhatdan** [comment]
First are you running both in rootful mode? 
@flouthoc PTAL

**Comment by loynoir** [comment]
@rhatdan

Log updated.

OK in `rootful docker + usermod`.

Fail in both `podman` and `sudo-podman`

**Comment by loynoir** [comment]
Plus, does below affect build or just interactive shell?

It's the only kind of warning appear in `podman` and `sudo-podman` situation.

```txt
STEP 6/9: SHELL ["/bin/sh", "-c"]
WARN[0007] SHELL is not supported for OCI image format, 
[/bin/sh -c] will be ignored. Must use `docker` format
```

**Comment by rhatdan** [comment]
Use --format docker, to not use OCI Format.

**Comment by zephyros-dev** [comment]
On devcontainer you also need to specify the `containerUser`, something like this:
```
	"runArgs": [
		"--userns=keep-id"
	],
	"remoteUser": "vscode",
	"containerUser": "vscode"
```
Because I uses bind mount for the code, I need to add `--userns=keep-id` to access the user in vscode. I uses my default UID and UGID of 1000, which is the same as the `vscode` user inside the container, so the command map the vscode user inside the container to my user outside. If you run without that options, the bind-mounted files will be inaccessible.
Reference: https://blog.lifeishao.com/2021/12/30/replacing-docker-with-podman-for-your-vscode-devcontainers/

**Comment by loynoir** [comment]
Ah, get it working.

settings.json
```
  "remote.containers.dockerPath": "podman-devcontainer-wrapper",
  // "remote.containers.dockerComposePath": "podman-compose-devcontainer-wrapper"
```

devcontainer.json
```
    "remoteUser": "vscode",
    "containerUser": "vscode"
```

podman-devcontainer-wrapper
```
BUILDAH_FORMAT=docker \
PODMAN_USERNS=keep-id \
podman "$@"
```
