### ISSUE TITLE
checkpoint tests time out under $CONTAINER

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#15015]
All checkpoint-related tests are [failing under containerized environment in CI](https://api.cirrus-ci.com/v1/task/6216834272722944/logs/main.log) (note: that is not a colorized/hyperlinked log. It is impossible to read without [my greasemonkey extension](https://github.com/edsantiago/greasemonkey/tree/master/podman-ginkgo-highlight)).
```
Command timed out after 90s.   (basically, every test that uses podman checkpoint/restore)
```

**Comment by vrothberg** [comment]
@edsantiago did the tests pass at some point before?

**Comment by edsantiago** [comment]
Yes, they all worked fine prior to #14972 . That is the recent PR that did the VM switcheroo in CI. Here's an [example](https://api.cirrus-ci.com/v1/artifact/task/5717856447889408/html/int-podman-fedora-36-root-container.log.html) of a PR that ran before 14972. Search in-page for " checkpoint" (space-checkpoint, to eliminate other `checkpoint` strings from podman info).

14972 is a huge monster, so it's impossible to know what changed, but the likely culprit is something different in the `f36` image. Maybe criu, maybe kernel, I really can't begin to guess.

**Comment by vrothberg** [comment]
Thanks, @edsantiago !

**Comment by rst0git** [comment]
@edsantiago Is this problem with checkpoint/restore tests still present?

**Comment by edsantiago** [comment]
@rst0git I assume so. The tests are completely disabled, so there's no way to find out except to reenable them. Since the VM images are unchanged, I don't think that would give us any information we don't already have.

**Comment by rhatdan** [comment]
@edsantiago should we reenable the test, to see if a miracle happened?

**Comment by edsantiago** [comment]
I hate relying on miracles... but both [f37](https://api.cirrus-ci.com/v1/artifact/task/6118403069444096/html/int-podman-fedora-37-root-container-sqlite.log.html) and [f38](https://api.cirrus-ci.com/v1/artifact/task/4992503162601472/html/int-podman-fedora-38-root-container-sqlite.log.html) had a successful CI run in my hammer-sqlite PR, with questionable but valid timings (42:18 and 37:13 respectively, compared to 37:23 / 33:03 on a PR in `main`. Five minutes seems a little concerning, but I guess checkpointing is expensive?)

I verified that tests ran by grepping for 'checkpoint' in the summary lines and eyeballing the results, and by comparing `N tests skipped` in the bottom summary against another PR without the skips removed. It's about 35 tests that were being skipped and no longer are. This is consistent with `grep -wc It test/e2e/checkpoint_{,image_}test.go`.

Real PR now in the works.
