### ISSUE TITLE
test fails under runc: podman pod create --share-parent

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#15013]
Test is [failing under cgroupsv1 with runc](https://api.cirrus-ci.com/v1/artifact/task/6491108266999808/html/int-podman-ubuntu-2204-root-host.log.html#t--podman-pod-create-share-parent-test--1):
```
podman pod create --share-parent test
...
# podman [options] inspect cgroupCtr
# podman [options] inspect 87b3ef9bac3dbfeab1d65b3d5dd856571e0de66a0cdbea6080dd2c9ab5f8724d
Expected
      <string>: host
  to contain substring
      <string>: 1e6d7d50e0d46c60c9906a5518d06969235bf521ea7e71db6dc153131e977e6c
```
The string in question is something to do with cgroups.

Context: we have not been testing with runc. The above test was introduced during this period. #14972 brings back runc.

**Comment by cdoern** [comment]
on it

**Comment by cdoern** [comment]
@edsantiago I cannot reproduce this, running https://github.com/containers/podman/blob/b5612df55060317bcef92de48e5b2cd400374814/test/e2e/pod_create_test.go#L1075-L1087 manually, results in `CgroupMode = container:infraID`


```
[charliedoern@fedora podman]$ bin/podman --runtime=runc pod create --share=cgroup,ipc,net,uts --share-parent=false --infra-name=cgroupCtr
03ac89e5146032a6758e0cf4685ee76c16b6c4a3fc051458f618d796d0ecb3da
[charliedoern@fedora podman]$ bin/podman inspect cgroupCtr
[
     {
          "Id": "208ea6f6c2be003bd73024fb8fabb023ffec4f550b304309ede152600a141329",
...

[charliedoern@fedora podman]$ bin/podman --runtime=runc run -dt --name=123 --pod=03ac89e5146032a6758e0cf4685ee76c16b6c4a3fc051458f618d796d0ecb3da alpine
64c56967d81c96f047205c148831f9936de192060612e2bd124819ce98c34d4b
[charliedoern@fedora podman]$ bin/podman inspect --format='{{.HostConfig.CgroupMode}}' 123
container:208ea6f6c2be003bd73024fb8fabb023ffec4f550b304309ede152600a141329

```

**Comment by cdoern** [comment]
oh is this only failing in your PR as cgroupsv1? I think this is not supported in v1, the test is meant to skip when running v1.

**Comment by cdoern** [comment]
the only guess I have here is that these tests are running with `infra=false`, the only way these tests could be reporting `host` is if `NamespaceMode` is returning that. 

@edsantiago is there a way for me to get access to a cgroupv1 system?

**Comment by edsantiago** [comment]
@cdoern there's a script, `hack/get_ci_vm.sh`, that works for some people (it has never worked for me). If you can get it to work, you should be able to get an Ubuntu VM using the magic `c` number in this PR. Good luck.

**Comment by rhatdan** [comment]
@cdoern Any chance you can follow up on this one?

**Comment by cdoern** [comment]
yep, @rhatdan was just about to circle back

**Comment by rhatdan** [comment]
@cdoern still circling? :^)

**Comment by cdoern** [comment]
@rhatdan sorry, this one slipped through. Will address today.
