### ISSUE TITLE
restore --pod: cannot restore pod container without --pod

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#15018]
Failing in [ubuntu 2204, remote, with cgroupsv1 and runc](https://api.cirrus-ci.com/v1/artifact/task/5879373692665856/html/int-remote-ubuntu-2204-root-host.log.html#t--podman-checkpoint-and-restore-container-out-of-and-into-pod--ipc-net-uts-pid---1):
```
podman checkpoint and restore container out of and into pod (ipc,net,uts,pid)
...
# podman-remote [options] container restore --pod NEW-POD-ID -i /tmp/checkpoint-CONTAINER-ID.tar.gz
Error: cannot restore pod container without --pod
```
(The discerning reader will note that `--pod` is specified in the command line). That error seems to come from https://github.com/containers/podman/blob/039deece50525b1fc812890dfa1ce2fa1f4c98b3/pkg/checkpoint/checkpoint_restore.go#L59-L61

Earlier in that test, I see this warning:
```
# podman-remote [options] container checkpoint -e /tmp/checkpoint-CONTAINER-ID.tar.gz CONTAINER-ID
time="2022-07-20T21:07:00Z" level=warning msg="lstat /sys/fs/cgroup/devices/machine.slice/machine-libpod_pod_OLD-POD-ID.slice/libpod-CONTAINER-ID.scope: no such file or directory"
```
So, yeah, seems to be cgroups-related. Something we just never tested because we haven't been testing runc.

**Comment by cdoern** [comment]
@giuseppe is the attempt to enter `/sys/fs/cgroup/devices...` seem weird to you? that should fail due to permissions, right? This could also be since runc separated out their device handling code.

**Comment by cdoern** [comment]
this is an issue with restore on all podman-remote versions, fixing now
