### ISSUE TITLE
Pomand network issue with more than one network

### ISSUE THREAD

**Issue by MaserUser** [containers/podman#15026]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Need to send mail from inside a container (passbolt), but container can not resolve dns.
Tried also to map ports like 8888:80 4000:443 and 5000:587, put no chang in the behaviour.

**Steps to reproduce the issue:**

1. podman network create network1
2. podman run --rm -ti --name container1 --network network1,podman alpine/curl:latest curl www.google.com

**Describe the results you received:**
curl: (6) Could not resolve host: www.google.com

**Describe the results you expected:**
<!doctype html>...

**Additional information you deem important (e.g. issue happens only occasionally):**
The order of networks is important, since the first one works, but I want most of my container not exposed to the internet. And the other way arround, the internal DNS wont work if the networks are switched.

**Output of `podman version`:**

```
3.4.2
```
waiting for ubuntu 22.04.1 to update
**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

latest version for native package, could not find fixes for similar problems. at leat not for Ubuntu (they suggestest changing the firewall settings)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Luap99** [comment]
This was fixed with the network rewrite. with the You have to update to at least v4.0 and use netavark/aardvark.
