### ISSUE TITLE
Error: OCI runtime error: runc: container_linux.go:349: starting container process caused "error adding seccomp filter rule for syscall bdflush: requested action matches default action of filter"

### ISSUE THREAD

**Issue by lpe110** [containers/podman#15051]
Error: OCI runtime error: runc: container_linux.go:349: starting container process caused "error adding seccomp filter rule for syscall bdflush: requested action matches default action of filter"
$ podman run hello-world
Error: OCI runtime error: runc: container_linux.go:349: starting container process caused "error adding seccomp filter rule for syscall bdflush: requested action matches default action of filter"

**Comment by lpe110** [comment]
$ podman version
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.4
Built:        Thu Jan  1 08:00:00 1970
OS/Arch:      linux/amd64

**Comment by mheon** [comment]
You need a newer runc. This is an error caused by an old (I think pre-1.0? The last time I recall seeing this was at least a year ago...) runc version with a newer Podman.
