### ISSUE TITLE
Allow starting (not creating) a podman play kube deployment

### ISSUE THREAD

**Issue by ctron** [containers/podman#15054]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Using `podman play kube` is great, except when you had something started and restart your machine. In this case the pods exist, but are not started. Executing `podman play kube my-stuff.yaml` doesn't work anymore, as the pods already exists. And there is no "just start existing pods" flag.

It is either necessary to start the pods manually, or recreate them.

It would be nice if existing pods would simply be started. Alternatively a flag like `--activate` or `--reuse` would allow the user to enable this behavior.

**Steps to reproduce the issue:**

1. `podman play kube my-stuff.yaml`

2. Reboot machine

3. `podman play kube my-stuff.yaml`

**Describe the results you received:**

```
$ podman play kube develop/services.yaml
Error: develop/services.yaml: error adding pod to state: name "postgresql" is in use: pod already exists
```

**Describe the results you expected:**

```
$ podman play kube develop/services.yaml
[…]
Pod:
b136988026eec50309905bf69ca277187419f41c86d706ea714fd35c9befaed3
Container:
26f22c1dfd6090ecfcfc59850b382ba4f53c70a243e46c3d9554debd06d81a19

Pod:
229097b299423b1730b387c2a89a6ba2065da448cabb93e96b9876c3d83f4e87
Container:
ede9320dc847ea69655daffe1339e6f0b3ca94bc5e5aa403118a5e13d3a33f51
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Every time.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.3
Built:        Wed Jun 22 18:17:44 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpuUtilization:
    idlePercent: 94.14
    systemPercent: 0.8
    userPercent: 5.05
  cpus: 24
  distribution:
    distribution: fedora
    variant: kde
    version: "36"
  eventLogger: journald
  hostname: brocken
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 110147
      size: 1
    - container_id: 1
      host_id: 120000
      size: 165536
    uidmap:
    - container_id: 0
      host_id: 110147
      size: 1
    - container_id: 1
      host_id: 120000
      size: 165536
  kernel: 5.18.13-200.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 38846910464
  memTotal: 67214053376
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun-1.4.5-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/110147/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 42366656512
  swapTotal: 42366656512
  uptime: 24m 56.62s
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/jreimann/.config/containers/storage.conf
  containerStore:
    number: 39
    paused: 0
    running: 4
    stopped: 35
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/jreimann/.local/share/containers/storage
  graphRootAllocated: 1858947207168
  graphRootUsed: 1155323383808
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 4705
  runRoot: /run/user/110147/containers
  volumePath: /home/jreimann/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1655914664
  BuiltTime: Wed Jun 22 18:17:44 2022
  GitCommit: ""
  GoVersion: go1.18.3
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.1.1-2.fc36.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
Excellent point.  I would see this as either of two ways.  Pod should fully restart on reboot or be fully removed on reboot.
@containers/podman-maintainers @mheon @umohnani8 @vrothberg WDYT?

If you look at Kubernetes, I believe the default is to remove all pods/containers on reboot.

**Comment by giuseppe** [comment]
isn't this the use case for `podman play kube --replace`?

**Comment by vrothberg** [comment]
> isn't this the use case for `podman play kube --replace`?

:+1:

**Comment by rhatdan** [comment]
So you believe that the pods and containers should lie dormant, and the default for a service that is starting a kubernetes.YAML file should be loaded with --replace? Is that what happens currently?  Should we add this information to the podman-kube-play/up man page?

**Comment by vrothberg** [comment]
> Is that what happens currently? 

No, `--replace` defaults to `false`.

> Should we add this information to the podman-kube-play/up man page?

`--replace` is mentioned in the man pages.

**Comment by rhatdan** [comment]
That is a difference between a pod created by hand versus a pod created by play kube.

**Comment by ctron** [comment]
So if pods created by `podman play kube` aren't supposed to be started again, wouldn't it make sense then to imply `--rm` for such pods? In that case a restart of the host would clear out those pods, right?

**Comment by vrothberg** [comment]
> That is a difference between a pod created by hand versus a pod created by play kube.

Correct.  `play kube` tries to follow Kubernetes where "restarting" is not possible.  State must be made persistent outside a container/pod, for instance, on volumes.

> So if pods created by `podman play kube` aren't supposed to be started again, wouldn't it make sense then to imply `--rm` for such pods? In that case a restart of the host would clear out those pods, right?

That would change the current and has a potential to break existing workloads which may rely on podman to error out in case of a name conflict.  But users are free to use `--replace` for that. We do the same in the `podman-kube` systemd template that will be shipped with Podman v4.2: https://github.com/containers/podman/blob/main/contrib/systemd/system/podman-kube%40.service.in#L12

**Comment by ctron** [comment]
But I think using `--rm` would still cause a name conflict (when starting play kube a second time) just after a reboot, one would have a clean system, instead of lingering pods which cannot be re-activated anyway.

True, it is more of a cleanup scenario now, and `--replace` would handle the situation when starting again.

I will close this issue. Thanks for the explanation.

**Comment by vrothberg** [comment]
I think I misinterpreted your `--rm` suggestion, @ctron.  Do you imagine `--rm` to auto-remove the pods once all containers exited?

**Comment by ctron** [comment]
My idea was they would disappear once the host gets restarted. But you are right, the would also disappear once the pod would exit. In which I would expect it to be restarted according to the podspec definition. Which is a different thing though, I guess.

**Comment by rhatdan** [comment]
This is bringing up some interesting ideas on how we should handle pods and podman kube play.

I think we might want to start a design doc on how we handle Pods in different situations.  And then have a meeting to discuss and design the behavior.

**Comment by Luap99** [comment]
Right now you can already use `podman pod {start,stop}` for the pod created by play kube, so if you have to keep the state you can use this.

**Comment by ctron** [comment]
> This is bringing up some interesting ideas on how we should handle pods and podman kube play.
> 
> I think we might want to start a design doc on how we handle Pods in different situations. And then have a meeting to discuss and design the behavior.

I am glad this issue turned into something useful :)

**Comment by vrothberg** [comment]
@rhatdan lets collect some ideas here first.

So far, the only thing that does not work yet is `--rm` which would remove the containers and pods once they're done.

**Comment by rhatdan** [comment]
Perhaps this should be discussed at the face-to-face

**Comment by vrothberg** [comment]
The `--rm` functionality has been implemented with the `--wait` flag which will clean up on receiving SIGTERM or after the pods exited.  So I think we can close the issue.
