### ISSUE TITLE
Connecting multiple NICs into same network

### ISSUE THREAD

**Issue by enhaut** [containers/podman#15062]
/kind feature

**Description**
Some users (me, our team and hopefully others) might find useful connecting container to the same network with multiple NICs (from POV of current situation: connecting container into network multiple times). Currently `podman network connect` allows just one connection of container and network, no matter the network  backend. So i am wondering why is this restricted, the second connection could be done as a first one - new host's interface. Maybe ability to specify host's interface name in `podman network connect` command might be required.

**Steps to reproduce the issue:**

1. `podman network create testnet`

2. `podman build -t nginx https://git.io/Jf8ol`

3. `podman run -d -p 8080:80 nginx` 
4. `6d7369fe40e2537bfbe826dfe0df154cf099ff6f5e0670f946c60422b2ed2d8c` is ID of running container
```
# podman network connect testnet 6d7369fe40e2537bfbe826dfe0df154cf099ff6f5e0670f946c60422b2ed2d8c
# podman network connect testnet 6d7369fe40e2537bfbe826dfe0df154cf099ff6f5e0670f946c60422b2ed2d8c
Error: container 6d7369fe40e2537bfbe826dfe0df154cf099ff6f5e0670f946c60422b2ed2d8c is already connected to network "testnet": network already exists
```

**Describe the results you received:**
Some error message, says that network is already connected.

**Describe the results you expected:**
Connecting the network to the container using another interface.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7

Built:      Fri Apr  1 04:45:37 2022
OS/Arch:    linux/amd64
```

**Output of `podman info --debug`:**

```
# podman info --debug
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 3a898eb433ae426e729088ccdc2bdae44a3164da'
  cpus: 14
  distribution:
    distribution: '"rhel"'
    version: "9.0"
  eventLogger: journald
  hostname: ****
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.0-70.13.1.el9_0.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 62696882176
  memTotal: 66767872000
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun-1.4.4-2.el9_0.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.4
      commit: 6521fcc5806f20f6187eb933f9f45130c86da230
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-4.el9.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 33587982336
  swapTotal: 33587982336
  uptime: 3m 13.52s
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.centos.org
  - quay.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1648802737
  BuiltTime: Fri Apr  1 04:45:37 2022
  GitCommit: ""
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# rpm -q podman
podman-4.0.2-6.el9_0.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I think this is just podman's restriciton so all environments that uses podman's networking are affected

**Comment by Luap99** [comment]
Why do you need this? It doesn't really make sense to have two interfaces on the same subnet. I don't see any benefit in doing this.

Also I don't think this is possible with our current code. Connected networks are stored as map with the name as key. Therefore is is impossible to use the same name twice.

**Comment by olichtne** [comment]
> Why do you need this?

our use case for this is to do simulation of physical hw servers with physical networks. In these cases you often times do have one server connected to the same switch and configure bonding/teaming or various vlans yourself.

We want to do simulations of these setups using containers to speed up our development-testing life cycle as setting up the hardware has restrictions on provisioning but also reservations whereas everyone can quickly create containers to simulate the same scenario before trying it out on hw.

This should be relatively easily possible to do with just normal network namespace configuration just via `ip netns`, however having some nice python abstraction would work for us better so that's why we're asking here...

**Comment by Luap99** [comment]
I don't think it makes sense for podman to support this. If you want more than one interface you can connect to a second (different) network.

I cannot even think how this should work with the podman UI. What happens on `podman network disconnect`, how do we know what interface to remove? Same for connect, how do we know the user wants a new interface vs the user made a typo.
Also we have to keep docker compat for these commands.

@mheon WDYT?

**Comment by enhaut** [comment]
Don't think UI would be problem, depends on implementation.   
As i proposed, `podman network connect` of the already connected network to container, podman could create another one with just higher index (`ethX`), everyone is used to that or there could be another parameter in `podman network connect` command with container's interface name something like `podman network connect NET CONTAINER ethX`.  
The removing interface, without specifying the interface could remove last interface - that's something up to discussion.

**Comment by Luap99** [comment]
Netavark definitely does not support but you could make it work.
The problem is that making `podman network connect NET CON` work two times is already a breaking change.

In general I don't think this usecase is useful to most people. It is very difficult to support many different network scenarios.
Adding something like this will make it much harder.
You can always setup the netns like you want and use `--network ns:/path/to/netns`.

**Comment by mheon** [comment]
is the ask here to have multiple *interface* in the network, or multiple IP addresses? We could change the stack to allow multiple IPs without terribly much difficulty, and I would not mind that. Multiple interfaces seems like a very specialized used-case, and I'm somewhat more hesitant about it.

If we were to do it, I would much rather it be configuration for the individual network in question, and not a way of connecting a container to a network multiple times.

**Comment by Luap99** [comment]
The ask is multiple interfaces, we already support multiple ip addresses.

**Comment by olichtne** [comment]
Yeah, multiple interfaces, again the point is that this simulates a real hw scenario when you have multiple physical cables connected to the same switch. For what it's worth, ip addresses are also something we DON'T want automatically configured, we want to take care of that ourselves too.

Yes, it is a specialized use case, from the container point of view I think there isn't much reason to do this other than situations where you want to use the same configuration scripts that you would use on real hardware where this use case does make sense, and that's basically the simulation scenario that we're describing.

If the feature request doesn't make sense for podman that's fine, we asked just in case... so following from that what would be your recommendation if you wanted to do something like this but without podman? We know we can always fall back to using the `ip netns` commands as I've already described but we're just trying to see if there's anything higher level than that first...

**Comment by Luap99** [comment]
I think your best would be to manually create two network configs with different names but the same bridge and subnet.

Currently netavark fails with `failed to add route: File exists (os error 17)` when I try this but that could be fixed I guess.

**Comment by Luap99** [comment]
Note that would not be something I would call supported but if it works it works. You could also try this with two macvlan networks.

**Comment by fgiorgetti** [comment]
> The ask is multiple interfaces, we already support multiple ip addresses.

@Luap99 How is it supported? Does it require connecting the container to multiple networks?

**Comment by Luap99** [comment]
> > The ask is multiple interfaces, we already support multiple ip addresses.
> 
> @Luap99 How is it supported? Does it require connecting the container to multiple networks?

podman network create --subnet ... --subnet ... --subnet ..., you can give as many subnets as you want

**Comment by rhatdan** [comment]
Looks like this has been answered.
