### ISSUE TITLE
rootless: bps/iops: requested cgroup controller `io` is not available

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#15063]
Four tests failing rootless, common factor is "bps" and "iops":
```
$ podman [options] run --rm --device-read-bps=/dev/zero:1mb quay.io/libpod/alpine:latest sh -c cat /sys/fs/cgroup/$(sed -e 's|0::||' < /proc/self/cgroup)/io.max
Error: OCI runtime error: crun: the requested cgroup controller `io` is not available
```
EDIT: forgot to include [link to failing tests: f36 rootless](https://api.cirrus-ci.com/v1/artifact/task/4828849623007232/html/int-podman-fedora-36-rootless-host.log.html#t--podman-run-device-read-bps-test--1)

**Comment by cdoern** [comment]
I cannot reproduce on main. Is this with crun and cgroupfs or systemd?

**Comment by cdoern** [comment]
I cannot reproduce on main. Is this with crun and cgroupfs or systemd?

Edit: this exact command with runtime=crun and cgroup-manager=systemd works on main for me. Cgroupfs ignores alot of these due to permissions.

**Comment by edsantiago** [comment]
I really have no idea. All I know is the test fails if I remove the `Skip`. See #15058.

**Comment by cdoern** [comment]
@edsantiago I removed the other skip's you added last week in #15035 I think those are purposeful and not bugs. if using cgroupfs I think io is not available on the vms.

**Comment by edsantiago** [comment]
The log in comment 0 shows `--cgroup-manager systemd` on all failing tests.

**Comment by cdoern** [comment]
> 

it might be all backends since at the end of the day, the io controller is the io controller. we should look into enabling this on the VMs for rootless if I am correct in my assumption. I think that is why I made my pod resource limits test rootful only because I was getting non reproducible  errors in my PR.

**Comment by edsantiago** [comment]
@cdoern I'm really sorry, I truly have no idea what any of that means. Let me try to put this another way: I found a bunch of `Skips` that said `FIXME` but without an associated issue number. I created an issue, and updated those `Skips` so they will list the issue number, so if/when the issue gets fixed the `Skips` can be removed.

If this issue will some day be fixed, let's leave it open so we can track the `Skips`.

If this issue will never be fixed, please close it, and I will update those `Skips`, and they will say "This will never be fixed" instead of FIXME.

Sorry for not being clear earlier.

**Comment by giuseppe** [comment]
Let's just skip these tests for rootless.  The default systemd configuration doesn't enable `io` for unprivileged users.

It is fine to not add a check in the code though as the setting could be overridden and we want to take advantage of the `io` controller in this case.

**Comment by edsantiago** [comment]
Ok. I've amended #15058 as follows:
```diff
-       SkipIfRootless("FIXME: requested cgroup controller `io` is not available")
-       SkipIfRootlessCgroupsV1("Setting device-read-bps not supported on cgroupv1 for rootless users")
+       SkipIfRootless("Setting device-read-bps not supported for rootless users")
 ```
The four bps/iops tests are now unconditionally skipped when rootless.
