### ISSUE TITLE
Podman WARN[0000] Failed to decode the keys ["network.network_backend"]

### ISSUE THREAD

**Issue by maestropandy** [containers/podman#15085]
Podman commands throw error "WARN[0000] Failed to decode the keys ["network.network_backend"] from "/usr/share/containers/containers.conf"." Here is my podman and OS version

```
Version:      3.4.2
API Version:  3.4.2
Go Version:   go1.16.12
Built:        Sat Feb  5 00:02:55 2022
OS/Arch:      linux/amd64
OS type: Oracle Linux Server 8.5
```

Is this error only on OL8 OS type, upgrading to podman 4.x will address this issue or how to fix this WARN ?

**Comment by Luap99** [comment]
Just remove this line from containers.conf. Your config is not compatible with v3.X
