### ISSUE TITLE
Ability to use x86_64 Fedora CoreOS image as a base on M1 ARM Macs

### ISSUE THREAD

**Issue by piers-walter-ibm** [containers/podman#15099]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

It would be good if there was the ability to specify `podman machine init` to use an x86_64 image as the machine's VM image rather than using the `aarch64` image which is what it currently uses. Setting a specific image with `--image-path` allows you to set an x86_64 image however podman still sets all of the QEMU options in `~/.config/containers/podman/machine/qemu/machine.json` as if it was an `aarch64` image.

The reason this would be useful is some container images have issues running on the `aarch64` vm with `qemu-x86_64-static` emulator. I've been able to get this to work manually by changing the `CmdLine` section of `machine.json` to the following, using `qemu 6.2.0_1` 

```json
"CmdLine": [
  "/opt/homebrew/bin/qemu-system-x86_64",
  "-m",
  "2048",
  "-smp",
  "1",
  "-fw_cfg",
  "name=opt/com.coreos/config,file=/Users/pierswalter/.config/containers/podman/machine/qemu/intel-new.ign",
  "-qmp",
  "unix://var/folders/vj/ycgbg5p54kd46bkpz2b8nxcm0000gn/T/podman/qmp_intel-new.sock,server=on,wait=off",
  "-netdev",
  "socket,id=vlan,fd=3",
  "-device",
  "virtio-net-pci,netdev=vlan,mac=5a:94:ef:e4:0c:ee",
  "-device",
  "virtio-serial",
  "-chardev",
  "socket,path=/var/folders/vj/ycgbg5p54kd46bkpz2b8nxcm0000gn/T/podman/intel-new_ready.sock,server=on,wait=off,id=intel-new_ready",
  "-device",
  "virtserialport,chardev=intel-new_ready,name=org.fedoraproject.port.0",
  "-drive",
  "file=/opt/homebrew/share/qemu/edk2-x86_64-code.fd,if=pflash,format=raw,readonly=on",
  "-virtfs",
  "local,path=/Users/pierswalter,mount_tag=vol0,security_model=mapped-xattr",
  "-drive",
  "if=virtio,file=/Users/pierswalter/.local/share/containers/podman/machine/qemu/intel-new_fedora-coreos-36.20220703.3.1-qemu.x86_64.qcow2"
 ],
```
The underlying VM does run slower but provides better compatibility with container images which require the x86_64 architecture. 
A command such as `podman machine init --x86_64` would be great for M1 macs to run an x86_64 VM rather than the `aarch64` one. This could in future allow other architectures to be the VM host as well if desired

**Comment by Luap99** [comment]
There was some work here (https://github.com/containers/podman/pull/12430) but it got never finished.

We recommend to use qemu-user-static instead so that you only have to emulate the container application and not the full OS.

**Comment by rhatdan** [comment]
If we move to native Apple virtualization, on M! machines they have supposedly done some enhancements that make running an X86 ARCH more attractive.

**Comment by rhatdan** [comment]
@baude continues to work on this, and it is getting very close.

**Comment by beshkenadze** [comment]
Hey guys! 

Is there any chance of supporting apple virtualization in the near future like colima does?

Thanks.

**Comment by rhatdan** [comment]
Yes we hope to have tech preview in 4.7

**Comment by beshkenadze** [comment]
@rhatdan Hey! Can we expect support in 4.7? Thanks.

**Comment by ashley-cui** [comment]
Closing, as we now use AppleVirtualization with Rosetta support.
