### ISSUE TITLE
podman-mac-helper binary missing from release .dmg files

### ISSUE THREAD

**Issue by mitchellmebane** [containers/podman#15104]
/kind feature

podman-mac-helper binary missing from release .dmg files in podman 4.1.0 and 4.1.1.

**Steps to reproduce the issue:**

1.  Download `podman-4.1.1-amd64.dmg` or `podman-4.1.1-arm64.dmg`

2. Extract .dmg

3. Look for `podman-mac-helper` binary.

**Describe the results you received:**

`podman-mac-helper` binary is not present.

**Describe the results you expected:**

`podman-mac-helper` binary is present.

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I am trying to set up podman in a restricted Mac environment where I am not able to use Homebrew.  I _really_ appreciate that the project provides pre-compiled binaries!  I noticed that when I run podman, it gives me a warning that "the default Docker API socket can't be used" and suggests running `podman-mac-helper install`.  However, this binary is not present in the .dmg files from the GitHub Releases.  Would it be possible to include it for 4.2?

**Comment by vrothberg** [comment]
@ashley-cui PTAL

**Comment by ashley-cui** [comment]
Done!
