### ISSUE TITLE
"podman manifest push" should accept the --compression-format=format flag, like "podman image push" does

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [containers/podman#15109]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

All is in the title: `podman manifest push` should accept the `--compression-format=format` flag, like `podman image push` does. I am in a scenario where I attempt to push a multi-arch image into our own docker registry, using the experimental `zstd:chunked` compression. The images are pushed implicitly to the registry at the same as the manifest is pushed (ie we use the default behavior of flag `--all` to push the images at the same time).

**Describe the results you received:**

`Error: unknown flag: --compression-format`

**Describe the results you expected:**

Push should work, and the chosen compression (in our case `zstd:chunked`) shall be used for all the pushed images of the manifest list.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Like most of my bug report, I tried it with the image `quay.io/podman/upsteam`:

```
[root@842fc1ace592 /]# podman version
Client:       Podman Engine
Version:      4.2.0-dev
API Version:  4.2.0-dev
Go Version:   go1.18.4
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

FYI, it seems the support for this compression flag in `podman image push` was added by this pull request: https://github.com/containers/podman/pull/12450/files from which one might be inspired to add it in `podman manifest push` as well.

Cheers,
Romain

**Comment by rhatdan** [comment]
As always, care to open a PR?

**Comment by Romain-Geissler-1A** [comment]
I will need to find the time, as I don't have a lot.

General question, for such simple needs, you prefer that I open an issue first, then a pull request, or you don't care about formalism and a pull request directly is enough ?

**Comment by rhatdan** [comment]
Don't care about formalism.  I am fine with just a PR.
