### ISSUE TITLE
Can't reinit Podman inside WSL2

### ISSUE THREAD

**Issue by delucca** [containers/podman#15107]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I tried to use Podman within my setup (Windows 11 + WSL2) but was having issues while trying to connect with a container from Windows.

I found this [reply](https://github.com/containers/podman/issues/12292#issuecomment-1114035411), so I updated my Podman version to `4.1.1` and, after that, I ran:

```
podman machine init
```

Them:
```
podman machine start
```

After the `machine start` command, I received the following error:
```
Starting machine "podman-machine-default"
Waiting for VM ...
Error: dial unix /mnt/wslg/runtime-dir/podman/podman-machine-default_ready.sock: connect: connection refused
```

I've already tried to change the permissions of `/dev/kvm` to `666`, but the issue remains.

What should I do? Even with `4.1.1` if I run a Podman container I can connect with its port from within Linux, but I can't access it from Windows.

**Steps to reproduce the issue:**

N/A

**Describe the results you received:**

After running `podman machine start`
```
Starting machine "podman-machine-default"
Waiting for VM ...
Error: dial unix /mnt/wslg/runtime-dir/podman/podman-machine-default_ready.sock: connect: connection refused
```

**Describe the results you expected:**

To be able to interact with my containers ports from the Windows side

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 4.1.1
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.3-1.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.3, commit: '
  cpuUtilization:
    idlePercent: 99.68
    systemPercent: 0.14
    userPercent: 0.18
  cpus: 16
  distribution:
    distribution: fedora
    variant: container
    version: "35"
  eventLogger: file
  hostname: delucca-laptop
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.102.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 10320986112
  memTotal: 16642248704
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /mnt/wslg/runtime-dir/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 4294967296
  swapTotal: 4294967296
  uptime: 5h 25m 0.77s (Approximately 0.21 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/delucca/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/delucca/.local/share/containers/storage
  graphRootAllocated: 269490393088
  graphRootUsed: 85515636736
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 22
  runRoot: /mnt/wslg/runtime-dir/containers
  volumePath: /home/delucca/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1658515434
  BuiltTime: Fri Jul 22 15:43:54 2022
  GitCommit: ""
  GoVersion: go1.16.15
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.1.1-1.fc35.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by n1hility** [comment]
Hi @delucca am I correct in that you are running podman machine init and start *within* WSL2? Those commands need to be run on your Windows host in powershell / windows terminal. 

See the tutorial here: https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md

**Comment by delucca** [comment]
hi @n1hility thanks!

I've followed the steps under the tutorial. I've installed podman on Windows, but how can I access and use that podman machine **inside** WSL?

**Comment by gbraad** [comment]
WSL does not allow nested virtualization, so starting machine inside WSL2 will not work.

I am not so sure what you mean with 'use podman machine inside WSL'. You mean to use the podman command inside the debian/ubuntu environment to handle the WSL2 Fedora environment?

**Comment by delucca** [comment]
> WSL does not allow nested virtualization, so starting machine inside WSL2 will not work.
> 
> I am not so sure what you mean with 'use podman machine inside WSL'. You mean to use the podman command inside the debian/ubuntu environment to handle the WSL2 Fedora environment?
> 
> Have you tried setting the Docker host inside the WSL2 environment?
> 
> ```
> DOCKER_HOST='npipe:////./pipe/podman-machine-default' podman ls
> ```
> 
> Note: unable to test atm.

Docker works (as expected) inside WSL2. To achieve this I need to install Docker in the Windows Machine, and it creates a socket that can be used within WSL2

In any case, I've decided to move away from WSL and go back to Linux. I had several problems with WSL2 (mainly related to the filesystem and USB in general), so this issue is no longer relevant (at least for me)

**Comment by gbraad** [comment]
I forgot that we run `win-sshproxy` for this, so a system connection might have been able to use podman as a remote client. WSL2 is not the same as an actual VM, as it also does not run systemd ATM, which means the init process uses workarounds to make it run daemon services. One of the reasons I still use a dedicated VM alongside on the same machine, ...

I will record that this needs to be described (new issue). Can you otherwise close this one as the described practice is not recommended.

**Comment by n1hility** [comment]
Closing since there was no underlying bug.
