### ISSUE TITLE
Can't run docker-compose after removing Podman

### ISSUE THREAD

**Issue by jjcfrank** [containers/podman#15117]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

/kind feature

**Description**

 I installed Podman to run tests and after tests were finished I `brew uninstall podman`. Then I tried running a docker compose file with `docker-compose up` but got an error.

**Steps to reproduce the issue:**

1. Installed Podman via brew

2. Uninstalled Podman via brew

3. Tried running `docker-compose up` but could not

**Describe the results you received:**
I got the following error:

`error during connect: Get "http://%2Ftmp%2Fpodman.sock/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dtests%22%3Atrue%7D%7D&limit=0": EOF
`
**Describe the results you expected:**
The docker-compose.yml is an application I use daily and know that worked before I installed Podman.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

**No**

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ran locally on macOS Monterey M1

**Comment by mheon** [comment]
I assume you have a working Docker setup on the machine? If so, please see if  the `DOCKER_HOST` environment variable is set - it's probably pointed at the Podman socket.

**Comment by rhatdan** [comment]
Since we never heard back on this issue, I am closing.  Reopen if you have more info on a Podman bug.
