### ISSUE TITLE
Unable to compile podman from main branch (Using WSL)

### ISSUE THREAD

**Issue by mcerverc** [containers/podman#15115]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I cannot compile the current podman version (main branch) using WSL on Windows

**Steps to reproduce the issue:**

1. sudo apt-get update

2. sudo apt-get install   btrfs-progs   git   golang-go   go-md2man   iptables   libassuan-dev   libbtrfs-dev   libc6-dev   libdevmapper-dev   libglib2.0-dev   libgpgme-dev   libgpg-error-dev   libprotobuf-dev   libprotobuf-c-dev   libseccomp-dev   libselinux1-dev   libsystemd-dev   pkg-config   runc   uidmap

3. make BUILDTAGS="selinux seccomp"

**Describe the results you received:**

When executing step 3 i get this error:
build github.com/containers/podman/v4/cmd/podman: cannot load io/fs: malformed module path "io/fs": missing dot in first path element
make: *** [Makefile:295: bin/podman] Error 1

**Describe the results you expected:**
Compiling successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

Followed steps are from https://podman.io/getting-started/installation

**Comment by Luap99** [comment]
Your go version is to old, you have to use at least v1.16
