### ISSUE TITLE
When rootless mode and systemd-home with LUKS, my decision

### ISSUE THREAD

**Issue by denisoster** [containers/podman#15114]
I`m using arch, systemd-home with LUKS and podman with rootless mode.
/etc/passwd do not contain my user due to settings /etc/nsswitch.conf

 ```
passwd: compat systemd
group: files [SUCCESS=merge] systemd
shadow: compat systemd
gshadow: compat systemd

publickey: files

hosts: mymachines resolve [!UNAVAIL=return] files myhostname dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

netgroup: files
```

My decision [patch](https://gist.github.com/denisoster/88a013adca06a9ca6e2af44a0e8dc591)

**Comment by vrothberg** [comment]
Thanks for reaching out, @denisoster.

Can you elaborate on what you request in this issue?

**Comment by denisoster** [comment]
@vrothberg this not bug.
Maybe it will be useful for people who will be in the same situation as me.
I`m created PR in runc

**Comment by giuseppe** [comment]
since there is no action to take from the Podman side and the fix affects only the OCI runtime, I am closing it.
