### ISSUE TITLE
podman machine and WSL desynchronized

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman#15118]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I was testing podman-desktop so it proposed me to upgrade from 4.0.2 to 4.1.1 which I did. But not it seems the machine state and WSL are desynchronized as I can send podman commands but the machine state seems to be done.
```

C:\Users\JeffMAURY\.crc\bin>podman machine list --format json
[
    {
        "Name": "podman-machine-default",
        "Default": true,
        "Created": "2022-07-18T14:29:18.2670252+02:00",
        "Running": false,
        "Starting": false,
        "LastUp": "2022-07-29T10:13:44.990707+02:00",
        "Stream": "35",
        "VMType": "wsl",
        "CPUs": 0,
        "Memory": "0",
        "DiskSize": "3186622464",
        "Port": 56786,
        "RemoteUsername": "user",
        "IdentityPath": "C:\\Users\\JeffMAURY\\.ssh\\podman-machine-default"
    }
]
```
```

C:\Users\JeffMAURY\.crc\bin>podman images
REPOSITORY                                       TAG         IMAGE ID      CREATED        SIZE
docker.io/jeffmaury/java-springboot-odo-example  latest      04684a4a00d1  2 hours ago    407 MB
<none>                                           <none>      e4c755b8efe6  2 hours ago    470 MB
<none>                                           <none>      4bdbf2a2cfc1  2 hours ago    407 MB
<none>                                           <none>      c4c81de2319c  2 hours ago    470 MB
registry.access.redhat.com/ubi8/openjdk-11       latest      0c308464b19e  7 days ago     390 MB
docker.io/library/httpd                          latest      444f7df01ce9  2 weeks ago    149 MB
quay.io/centos/centos                            centos8     300e315adb2f  19 months ago  217 MB
```

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

podman machine state and WSL state are desynchronized

**Describe the results you expected:**

States should be in sync

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
C:\Users\JeffMAURY\.crc\bin>podman version                   
Client:       Podman Engine                                  
Version:      4.1.1                                          
API Version:  4.1.1                                          
Go Version:   go1.16.15                                      
Git Commit:   f73d8f8875c2be7cd2049094c29aff90b1150241       
Built:        Wed Jun 15 15:17:12 2022                       
OS/Arch:      windows/amd64                                  
                                                             
Server:       Podman Engine                                  
Version:      4.2.0-rc1                                      
API Version:  4.2.0-rc1                                      
Go Version:   go1.16.15                                      
Built:        Mon Jul 11 22:58:55 2022                       
OS/Arch:      linux/amd64                                    ```

**Output of `podman info --debug`:**

```
C:\Users\JeffMAURY\.crc\bin>podman info --debug
host:
  arch: amd64
  buildahVersion: 1.27.0-dev
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.1-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.1, commit: '
  cpuUtilization:
    idlePercent: 99.55
    systemPercent: 0.22
    userPercent: 0.23
  cpus: 8
  distribution:
    distribution: fedora
    variant: container
    version: "35"
  eventLogger: file
  hostname: DESKTOP-U2EVGBM
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.16.3-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 14260719616
  memTotal: 16702230528
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.5-2.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 4294967296
  swapTotal: 4294967296
  uptime: 165h 58m 4.00s (Approximately 6.88 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 269490393088
  graphRootUsed: 1783828480
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 11
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0-rc1
  Built: 1657573135
  BuiltTime: Mon Jul 11 22:58:55 2022
  GitCommit: ""
  GoVersion: go1.16.15
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0-rc1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**


Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@n1hility PTAL

**Comment by n1hility** [comment]
If you stop and start the machine on the PowerShell/ Windows Terminal CLI (podman machine stop, podman machine start) does the state recover, or does it still indicate its down when it is not?

**Comment by jeffmaury** [comment]
I can't because if I stop it podman says it's not started and if I start it it fails (probably because the WSL is running)

**Comment by n1hility** [comment]
ah ok in that case do a `wsl --shutdown` then try podman machine start/stop

**Comment by jeffmaury** [comment]
OK now it's back to normal state. The question is what leads to that state ? Will try to reboot as I asked W11 to restore my applications when login

**Comment by n1hility** [comment]
Not sure yet how it got into this state. There is a case where older 4.0.x machines are upgraded since the state format added fields. It could be that the machine was running when the upgrade occurred, and stop isnt on that transition path, so then you are stuck with no transition to go to. 

You probably will also have a stale win-sshproxy.exe hanging around after this. To kill those (after stopping) you can do `taskkill /f /im win-sshproxy.exe`

**Comment by n1hility** [comment]
I wasn’t able to reproduce this one with current releases, so I suspect this issue is no longer present, feel free to reopen if it pops up again.
