### ISSUE TITLE
podman-run terminal output is written to syslog and journald among others

### ISSUE THREAD

**Issue by NetDwarf** [containers/podman#15137]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

If you run any container with podman with terminal output that output is written to `/var/log/syslog`, `/var/log/messages`, `/var/log/user.log` and journald on Debian (on Fedora it's only journald as far as I can tell). 

**Steps to reproduce the issue:**

1. `podman run --rm alpine echo "A message to my syslog"`

**Describe the results you received:**
The message pops up in `/var/log/syslog`, `/var/log/messages`, `/var/log/user.log` and journald on Debian (on Fedora journald).

**Describe the results you expected:**
I would expect to either have no output at all from what happens inside the container or only errors. 

**Additional information you deem important (e.g. issue happens only occasionally):**

The problem is exaggerated if you want to redirect output from the container i.e. `mysqldump` you quickly fill up your whole drive.

`--log-driver=none` is a workaround. `--log-opt max-size=<size>` does nothing (expected).

**Output of `podman version`:**
Debian:
```
Version:      3.4.7
API Version:  3.4.7
Go Version:   go1.18.1
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

Fedora:
```
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.3
Built:        Wed Jun 22 18:17:44 2022
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

Debian
```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: unknown'
  cpus: 4
  distribution:
    distribution: debian
    version: unknown
  eventLogger: journald
  hostname: laptop
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.18.0-2-amd64
  linkmode: dynamic
  logDriver: journald
  memFree: 3624833024
  memTotal: 16661008384
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 8541958144
  swapTotal: 8589930496
  uptime: 2h 37m 45.72s (Approximately 0.08 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/reginald/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/reginald/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 25
  runRoot: /run/user/1000/containers
  volumePath: /home/reginald/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.7
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.18.1
  OsArch: linux/amd64
  Version: 3.4.7
```

Fedora:
```
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpuUtilization:
    idlePercent: 97.38
    systemPercent: 1.26
    userPercent: 1.36
  cpus: 4
  distribution:
    distribution: fedora
    variant: workstation
    version: "36"
  eventLogger: journald
  hostname: fedora
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.18.13-200.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 426528768
  memTotal: 4107026432
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.5-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 4104646656
  swapTotal: 4106219520
  uptime: 1h 36m 23.67s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/testa/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/testa/.local/share/containers/storage
  graphRootAllocated: 41874882560
  graphRootUsed: 5824667648
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  volumePath: /home/testa/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1655914664
  BuiltTime: Wed Jun 22 18:17:44 2022
  GitCommit: ""
  GoVersion: go1.18.3
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

Debian:
```
podman/testing,unstable,now 3.4.7+ds1-3+b1 amd64 [installed]
```

Fedora:
```
podman-4.1.1-2.fc36.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes, with latest version 4.1.1 (on Fedora) and couldn't find anything related in the Troubleshooting Guide.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Luap99** [comment]
This is the expected behaviour. The default log driver is journald and Podman will only log to journald. It is up to journald to rotate the journal and keep a reasonable size of messages. 
If debian then stores the messages three times I would argue that this a debian problem and not Podman.

You can also use `--log-driver=k8s-file` if you still want a log file but not in the journal, this should respect `--log-opt max-size=<size>`

alse see https://github.com/containers/podman/discussions/14743

**Comment by NetDwarf** [comment]
Thanks for the response, however it's weird. The default behavior is practically broken on probably every Debian-based distribution. And even on Fedora you are not able to read your journal anymore once you pipe some amount of data. And it is also writing this data at least twice (five times in the case of Debian). 

This is certainly a feature for debugging, but pretty wasteful as the default I think.

**Comment by Luap99** [comment]
> And it is also writing this data at least twice

Who is writing twice? The conmon process will capture the container stdout/err and writes that to the journal. If anything is written more than once it is not done by us.

**Comment by NetDwarf** [comment]
> Who is writing twice? The conmon process will capture the container stdout/err and writes that to the journal. If anything is written more than once it is not done by us.

The redirection so to speak. `podman run --rm alpine command > file` is writing it once to file and once to log.

**Comment by Luap99** [comment]
That is a fair point but Podman cannot control this. The main reason why we have to log somewhere is because `podman logs` cannot work without it. If you do not plan on using `podman logs` then use `--log-driver=none` you can also set the default in containers.conf.

**Comment by NetDwarf** [comment]
Podman cannot alter its behavior on redirection, that makes sense. It also makes sense that you want the option for verbose logs. What does not make as much sense to me is that these verbose logs are the default.

At this point people might expect this behavior tho, so even if you would agree, it's maybe not changeable anyway if this is a behavior heavily relied upon.

I mean at least it's fixable.
