### ISSUE TITLE
`man podman-stats` improve descriptions 

### ISSUE THREAD

**Issue by TidyData** [containers/podman#15146]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

What do the numbers for Block IO mean when reported by podman-stats  https://docs.podman.io/en/latest/markdown/podman-stats.1.html?highlight=stat

![image](https://user-images.githubusercontent.com/22264476/182257460-355609cf-2644-490a-b5ad-79e1fd73fb77.png)  

Is the the total data read and right total data written?
I am having a hard time understanding Block IO meaning

**Comment by vrothberg** [comment]
Yes, it's the total `block input/block output`. I change the issue title accordingly as I feel the `podman-stats` man page should improve the descriptions.

**Comment by vrothberg** [comment]
The man page also does not show `AVG CPU` at all.  This is something that can be added along with meaningful descriptions for each "placeholder".

**Comment by rhatdan** [comment]
@vrothberg @TomSweeneyRedHat @cdoern Any time to work on this one?
