### ISSUE TITLE
podman-remote ssh:<domain>:22 connection issue

### ISSUE THREAD

**Issue by orangutanga** [containers/podman#15153]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When adding a system connection for use with podman-remote the added connection adds ':22' (without quotes) to the ssh connection DOMAIN. This seems to cause a problem with my DNS lookup, and ssh connection fails.

**Steps to reproduce the issue:**

1. podman-remote system connection add NAME --identity IDENTITY ssh://USER@DOMAIN/run/podman/podman.socket
2. podman-remote system connection list
   ... ssh://USER@DOMAIN:22/run/podman/podman.socket

**Describe the results you received:**
podman-remote ps -a
   ssh: rejected: connect failed

**Describe the results you expected:**
podman-remote ps -a
  ...list of containers

**Additional information you deem important (e.g. issue happens only occasionally):**

I can successfully ssh into DOMAIN without password. I am unsuccessful using DOMAIN:22 as the DNS lookup fails.

Podman socket is running on server.

I tried:
host DOMAIN:22
- unknown.

host DOMAIN
- found.

I cannot avoid having the ':22' added to the end of the DOMAIN.

**Output of `podman version`:**

```
podman version 4.1.1
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpuUtilization:
    idlePercent: 86.14
    systemPercent: 3.49
    userPercent: 10.37
  cpus: 8
  distribution:
    distribution: fedora
    variant: workstation
    version: "36"
  eventLogger: journald
  hostname: max
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.18.13-200.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 196845568
  memTotal: 8012853248
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.5-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 5940236288
  swapTotal: 8012165120
  uptime: 187h 48m 12.29s (Approximately 7.79 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/andrew/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/andrew/.local/share/containers/storage
  graphRootAllocated: 1021922246656
  graphRootUsed: 726736584704
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/andrew/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1655914664
  BuiltTime: Thu Jun 23 00:17:44 2022
  GitCommit: ""
  GoVersion: go1.18.3
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.1.1-2.fc36.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes 4.1.1. No to second question.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Bare Metal

**Comment by rhatdan** [comment]
@cdoern PTAL

**Comment by orangutanga** [comment]
Hi thanks for looking at this. Can I suggest that this is a DNS issue because the DOMAIN is not separated from the port when used in the code?

BTW I have not looked at the podman code yet. I might need some pointers on where to look.

 tried:
host DOMAIN:22

    unknown.

host DOMAIN

    found.

because this is the error:

podman-remote ps -a
ssh: rejected: connect failed

That may mean that you can take your time changing over from golang's ssh engine.

Anyways that was my first though, as I can ssh into the remote fine until I add :22 to the domain. Surely others have seen this?

**Comment by cdoern** [comment]
@orangutanga try using `podman --ssh=native...` if that still does not work I will reopen this and look into it more. I am pretty sure my patches fixed this in both paths.
