### ISSUE TITLE
--iidfile can write just `sha256:` string, without the actual image id

### ISSUE THREAD

**Issue by graywolf-at-work** [containers/podman#15162]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When running `podman build` in parallel, it seems that iidfile can end up with
just the string `sha256:` instead of the expected `sha256:IMAGE_ID`. Seems to
require `--squash` and `--timestamp 0` to reproduce, however that might be just
bad luck on my end, since it is some race condition.

I'm pretty sure this is a bug, but any ideas for a workaround? My current
thinking is basically:

	podman build --squash --timestamp 0 . 2>&1 | tail -n1

I wonder if there is a more elegant way or if there are some problems with ^.

**Steps to reproduce the issue:**

	printf 'from docker.io/library/alpine:3.16\nrun for i in $(seq 0 10000); do touch /$i; done\n' >Containerfile && for i in `seq 1 25`; do podman build --squash --iidfile id.$i --timestamp 0 . & done; wait; ls -al

**Describe the results you received:**

Some id files have 7 bytes (`sha256:`).

**Describe the results you expected:**

All id files should have 71 bytes (`sha256:IMAGE_ID`).

**Additional information you deem important (e.g. issue happens only occasionally):**

Every time the number of 7-byte files is different, so seems to be some race
condition. Gets much worse with the size of the image (I cannot reproduce it
without the `touch /$i` in the Containerfile) and with parallelism (happens
very rarely with just 2 or 3 builds in parallel).

**Output of `podman version`:**

	Client:       Podman Engine
	Version:      4.1.0
	API Version:  4.1.0
	Go Version:   go1.18.4
	Git Commit:   112d29a88c7813a70b55004ec305f48630b43e12
	Built:        Thu Jul 21 20:43:18 2022
	OS/Arch:      linux/amd64

**Output of `podman info --debug`:**

	host:
	  arch: amd64
	  buildahVersion: 1.26.1
	  cgroupControllers:
	  - cpuset
	  - cpu
	  - io
	  - memory
	  - hugetlb
	  - pids
	  cgroupManager: cgroupfs
	  cgroupVersion: v2
	  conmon:
	    package: conmon-2.1.2-r0
	    path: /usr/bin/conmon
	    version: 'conmon version 2.1.2, commit: f25214cda836296fe8695c2e582ca79d2246053a'
	  cpuUtilization:
	    idlePercent: 84.46
	    systemPercent: 3.16
	    userPercent: 12.38
	  cpus: 16
	  distribution:
	    distribution: alpine
	    version: 3.16.1
	  eventLogger: file
	  hostname: HOSTNAME
	  idMappings:
	    gidmap:
	    - container_id: 0
	      host_id: 1234
	      size: 1
	    - container_id: 1
	      host_id: 100000
	      size: 65536
	    uidmap:
	    - container_id: 0
	      host_id: 1234
	      size: 1
	    - container_id: 1
	      host_id: 100000
	      size: 65536
	  kernel: 5.15.57-0-lts
	  linkmode: dynamic
	  logDriver: k8s-file
	  memFree: 4304928768
	  memTotal: 29255086080
	  networkBackend: cni
	  ociRuntime:
	    name: crun
	    package: crun-1.4.5-r0
	    path: /usr/bin/crun
	    version: |-
	      crun version 1.4.5
	      commit: c381048530aa750495cf502ddb7181f2ded5b400
	      spec: 1.0.0
	      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
	  os: linux
	  remoteSocket:
	    path: /var/run/1234-rdir/podman/podman.sock
	  security:
	    apparmorEnabled: false
	    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
	    rootless: true
	    seccompEnabled: true
	    seccompProfilePath: /etc/containers/seccomp.json
	    selinuxEnabled: false
	  serviceIsRemote: false
	  slirp4netns:
	    executable: /usr/bin/slirp4netns
	    package: slirp4netns-1.2.0-r0
	    version: |-
	      slirp4netns version 1.2.0
	      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
	      libslirp: 4.7.0
	      SLIRP_CONFIG_VERSION_MAX: 4
	      libseccomp: 2.5.2
	  swapFree: 34356596736
	  swapTotal: 34359734272
	  uptime: 33h 25m 58.8s (Approximately 1.38 days)
	plugins:
	  log:
	  - k8s-file
	  - none
	  - passthrough
	  network:
	  - bridge
	  - macvlan
	  - ipvlan
	  volume:
	  - local
	registries:
	  search:
	  - docker.io
	store:
	  configFile: /home/user/.config/containers/storage.conf
	  containerStore:
	    number: 4
	    paused: 0
	    running: 0
	    stopped: 4
	  graphDriverName: btrfs
	  graphOptions: {}
	  graphRoot: /home/user/.local/share/containers/storage
	  graphRootAllocated: 989776052224
	  graphRootUsed: 67633455104
	  graphStatus:
	    Build Version: Btrfs v5.17
	    Library Version: "102"
	  imageCopyTmpDir: /var/tmp
	  imageStore:
	    number: 94
	  runRoot: /var/run/1234-rdir/containers
	  volumePath: /home/user/.local/share/containers/storage/volumes
	version:
	  APIVersion: 4.1.0
	  Built: 1658428998
	  BuiltTime: Thu Jul 21 20:43:18 2022
	  GitCommit: 112d29a88c7813a70b55004ec305f48630b43e12
	  GoVersion: go1.18.4
	  Os: linux
	  OsArch: linux/amd64
	  Version: 4.1.0

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

	podman-4.1.0-r2 description:
	Simple management tool for pods, containers and images

	podman-4.1.0-r2 webpage:
	https://podman.io/

	podman-4.1.0-r2 installed size:
	33 MiB

	podman-4.1.0-r3 description:
	Simple management tool for pods, containers and images

	podman-4.1.0-r3 webpage:
	https://podman.io/

	podman-4.1.0-r3 installed size:
	33 MiB

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Laptop, linux, nothing special I would say.

**Comment by mheon** [comment]
@flouthoc PTAL

**Comment by flouthoc** [comment]
I'll take a look thanks.

**Comment by vrothberg** [comment]
That smells like the iid file is just a symptom of something else/bigger.

**Comment by rhatdan** [comment]
The above script exits with success when I run it after setting

export cnt_id=$(buildah from fedora)
Are you sure the script is correct?

**Comment by rhatdan** [comment]
Ok I thought it was a reproducer.

**Comment by flouthoc** [comment]
I was able to reproduce this is an issue with buildah and following PR should close this https://github.com/containers/buildah/pull/4190
