### ISSUE TITLE
install latest stable podman version with a single cmd 

### ISSUE THREAD

**Issue by mingregister** [containers/podman#15169]
Is there a single cmd to install the latest stable podman version?  Specially CentOS or Ubuntu

**Comment by vrothberg** [comment]
Thanks for reaching out, @mingregister.

The latest version of the specific distribution can be installed via the respective package manager.  In case of CentOS, you can do a `dnf install podman`.  It is up to each distribution to decide when to update the packages.  Ubuntu, for instance, is updating packages mostly with each new release of the distribution.  CentOS Stream is updating more frequently.

Upstream we do not provide packages for distributions as the support matrix (and hence the work) is just too big.  But we work closely with the distributions.

> Is there a single cmd to install the latest stable podman version? Specially CentOS or Ubuntu

There is no single command as different distributions use different package managers.
