### ISSUE TITLE
WSL2 on W10, CreateFile \\.\pipe\docker_engine: All pipe instances are busy.

### ISSUE THREAD

**Issue by kerjes** [containers/podman#15176]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Install of podman  v.4.1.1 on WSL2-W10 according to: [Podman for windows](https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md) fails.
First step `podman machine init` works, but not `podman machine start`:

```sh
podman machine start
Starting machine "podman-machine-default"

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

        podman machine set --rootful

API forwarding for Docker API clients is not available due to the following startup failures.
        CreateFile \\.\pipe\docker_engine: All pipe instances are busy.

Podman clients are still able to connect.
Machine "podman-machine-default" started successfully
```

**Steps to reproduce the issue:**

1. Install [podman-v4.1.1.msi](https://github.com/containers/podman/releases/download/v4.1.1/podman-v4.1.1.msi)

2.  In powershell run `podman machine init` 

3.  and `podman machine start`

**Describe the results you received:**

```sh
Starting machine "podman-machine-default"
...
API forwarding for Docker API clients is not available due to the following startup failures.
        CreateFile \\.\pipe\docker_engine: All pipe instances are busy.
...
```

**Describe the results you expected:**

```sh
Starting machine "podman-machine-default"
...
API forwarding listening on: npipe:////./pipe/docker_engine
...
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Window named pipes are created according to
```sh
 [System.IO.Directory]::GetFiles("\\.\\pipe\\") | Select-String 'docker|podman'

\\.\\pipe\\docker_engine
\\.\\pipe\\podman-machine-default
```
but the podman-deamon is never started in the fedora linux distribution. 
If I understand it correctly a psuedo-systemd proccess should have been bootstrapped within fedora.
`wsl -d podman-machine-default enterns su user` does not work either because, when checking `enterns`:  

```sh
wsl -d podman-machine-default
[root@XXXXXXXXXX]# cat /usr/local/bin/enterns
#!/bin/bash
SYSDPID=`ps -eo cmd,pid | grep -m 1 ^/lib/systemd/systemd | awk '{print $2}'`
if [ ! -z "$SYSDPID" ] && [ "$SYSDPID" != "1" ]; then
        nsenter -m -p -t $SYSDPID "$@"
fi
```
no `/lib/systemd/systemd/´ is running.

**Output of `podman version`:**

```
From powershell: 
podman --version
podman.exe version 4.1.1

From fedora
wsl -d podman-machine-default
[root@xxxxxxx]# podman version
Client:       Podman Engine
Version:      4.2.0-rc2
API Version:  4.2.0-rc2
Go Version:   go1.16.15
Built:        Wed Aug  3 16:27:27 2022
OS/Arch:      linux/amd64
```
Wrong version of podman 4.2.0-rc2 inside fedora as it not corresponding to v.4.1.1?

**Output of `podman info --debug`:**

From fedora image using `wsl -d podman-machine-default`
```
host:
  arch: amd64
  buildahVersion: 1.27.0-dev
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.3-1.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.3, commit: '
  cpuUtilization:
    idlePercent: 99.97
    systemPercent: 0.02
    userPercent: 0
  cpus: 8
  distribution:
    distribution: fedora
    variant: container
    version: "35"
  eventLogger: file
  hostname: asus-hem
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.102.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 8139534336
  memTotal: 8335167488
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 2147483648
  swapTotal: 2147483648
  uptime: 0h 12m 12.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 269490393088
  graphRootUsed: 636293120
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.2.0-rc2
  Built: 1659536847
  BuiltTime: Wed Aug  3 16:27:27 2022
  GitCommit: ""
  GoVersion: go1.16.15
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0-rc2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**
From fedora image using `wsl -d podman-machine-default`
```
podman-4.2.0~rc2-1.fc35.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by kerjes** [comment]
Had an offending %USERPROFILE%/.wslconfig
```
[wsl2]

memory=8GB
kernelCommandLine=cgroup_no_v1=named
```
Removed above file and `podman machine start`  works now:
Question is if it okey to run different version of client and server
```
podman version
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.16.15
Git Commit:   f73d8f8875c2be7cd2049094c29aff90b1150241
Built:        Wed Jun 15 15:17:12 2022
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.2.0-rc2
API Version:  4.2.0-rc2
Go Version:   go1.16.15
Built:        Wed Aug  3 16:27:27 2022
OS/Arch:      linux/amd64
```

**Comment by kerjes** [comment]
Closing issue

**Comment by allanp35** [comment]
Hello, I had exactly the same problem! The problem is that I don't have any %USERPROFILE%/.wslconfig.

Can somebody have an issue?

**Comment by sjoerdvandenbos-prodrive** [comment]
> Hello, I had exactly the same problem! But I don't have any %USERPROFILE%/.wslconfig.
> 
> Did somebody have an issue?

Resolved it by stopping the machine, rm'ing the machine, and then run podman init followed by podman machine start.

**Comment by allanp35** [comment]
> > Hello, I had exactly the same problem! But I don't have any %USERPROFILE%/.wslconfig.
> > Did somebody have an issue?
> 
> Resolved it by stopping the machine, rm'ing the machine, and then run podman init followed by podman machine start.
> 
> EDIT: Warning, you will lose all your containers and images.

Yes, we are doing this but that's not the target to lose each time containers. So I wanted to know if there is another solution. Because if I understand the error, maybe if the machine is not properly stop, it continue to listen on npipe:////./pipe/docker_engine.

**Comment by ratzalex** [comment]
> I think my vpn was causing this error. Always starting the podman machine before the vpn solved it for me.
> 
> Hope this helps.

I can confirm: the VPN caused the problem for me too. You have to start the podman machine before establishing the VPN connection.

**Comment by Vivekd7r** [comment]
Got the same problem, resolved by

`podman machine stop`
`wsl --shutdown`

If still issue persists, reboot system after running above commands.
