### ISSUE TITLE
CI: include OSX and windows cross task in CI:DOCS

### ISSUE THREAD

**Issue by Luap99** [containers/podman#15189]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

https://github.com/containers/podman/pull/15174 broke CI because it used CI:DOCS and thus skipped some tasks. In this case the OCX cross task is now failing. Because the OSX cross task also builds docs, it can be effected by docs changes and therefore we should include this in CI:DOCS.

Also excluded is the windows cross task. Since this also builds docs it should be included in CI:DOCS as well.

**Comment by Luap99** [comment]
@edsantiago @cevich PTAL
cc @containers/podman-maintainers

**Comment by gbraad** [comment]
It seems 'override' in the text is interpreted as a statement?

**Comment by cevich** [comment]
> the OSX cross task also builds docs

Ugg, you're right.  This is probably my fault. Taking a look.

**Comment by cevich** [comment]
Okay #15198 will fix this.  Thanks for pointing out the problem.
