### ISSUE TITLE
Error: runc: runc create failed: unable to start container process: exec: "echo": executable file not found in $PATH: OCI runtime attempted to invoke a command that was not found

### ISSUE THREAD

**Issue by ugiwgh** [containers/podman#15204]
I have set additionalimagestores. The article is
https://www.redhat.com/sysadmin/image-stores-podman.
$ podman images
REPOSITORY                                      TAG         IMAGE ID      CREATED        SIZE        R/O
docker.io/library/centos                        7.9.2009    eeb6ee3f44bd  10 months ago  212 MB      true
docker.io/library/python                        3.8         4544558e07c5  39 hours ago   936 MB      false

If I run the image which R/O is true, like the following error.
$ podman run --userns=keep-id eeb6ee3f44bd echo "hello"
Error: runc: runc create failed: unable to start container process: exec: "echo": executable file not found in $PATH: OCI runtime attempted to invoke a command that was not found

If run it without --userns=keep-id, it runs right.
$ podman run  eeb6ee3f44bd echo "hello"
hello

If run the image which R/O is false, it runs right.
$ podman run --userns=keep-id 4544558e07c5 echo "hello"
hello

**Comment by unknowndevQwQ** [comment]
> I have set additionalimagestores. The article is https://www.redhat.com/sysadmin/image-stores-podman. $ podman images REPOSITORY TAG IMAGE ID CREATED SIZE R/O docker.io/library/centos 7.9.2009 eeb6ee3f44bd 10 months ago 212 MB true docker.io/library/python 3.8 4544558e07c5 39 hours ago 936 MB false
> 
> If I run the image which R/O is true, like the following error. $ podman run --userns=keep-id eeb6ee3f44bd echo "hello" Error: runc: runc create failed: unable to start container process: exec: "echo": executable file not found in $PATH: OCI runtime attempted to invoke a command that was not found
> 
> If run it without --userns=keep-id, it runs right. $ podman run eeb6ee3f44bd echo "hello" hello
> 
> If run the image which R/O is false, it runs right. $ podman run --userns=keep-id 4544558e07c5 echo "hello" hello

`podman run --entrypoint sh centos echo "hello"`

**Comment by rhatdan** [comment]
First is the file system with the additional stores marked as NOEXEC?  Could this be an SELinux issue? Any AVCs?

**Comment by ugiwgh** [comment]
$ podman run --rm --userns=keep-id --entrypoint bash  5d0da3dc9764 echo "hello"
Error: runc: runc create failed: unable to start container process: exec: "bash": executable file not found in $PATH: OCI runtime attempted to invoke a command that was not found

**Comment by ugiwgh** [comment]
$ podman images
REPOSITORY                         TAG         IMAGE ID      CREATED        SIZE        R/O
docker.io/library/centos           8.4.2105    5d0da3dc9764  10 months ago  239 MB      true

**Comment by ugiwgh** [comment]
I have login to the host which image R/O is false.

**Comment by ugiwgh** [comment]
I have login to the host which image R/O is false.
$ podman images
REPOSITORY                         TAG         IMAGE ID      CREATED        SIZE
docker.io/library/centos           8.4.2105    5d0da3dc9764  10 months ago  239 MB

$ podman run --rm --userns=keep-id --entrypoint bash  5d0da3dc9764 echo "hello"
Error: chown /home/rsync/.local/share/containers/storage/overlay-containers/8e68d47ef64c8908bb6bff35a2255d8451632e71144a852f617d209f2e352fe7/userdata: operation not permitted

**Comment by rhatdan** [comment]
Please show output of podman info.  Are you using an image in global storage with a rooltess container, there are potentially issues with read and search access by a rootless user.

**Comment by ugiwgh** [comment]
Can I pull image from additionalimagestores to local path? The additionalimagestores is owned by rootless user, which is the same user who run the image.

**Comment by giuseppe** [comment]
have you chowned the additional store to 0755 before using it from rootless? `chmod -R 0755 /path/to/the/additional/store`?

**Comment by ugiwgh** [comment]
No, I haven't do that.

**Comment by ugiwgh** [comment]
> No, I haven't do that.
I have set force_mask="700" through by storage.conf for additionalimagestores.

**Comment by giuseppe** [comment]
700 is not enough, yoy need 755

**Comment by ugiwgh** [comment]
Yes, I change it to 0755, and it works. Thanks.
