### ISSUE TITLE
this issue was closed. was it fixed? i have MacOS 12.4 install on M1 still saw the same errors https://github.com/containers/podman/issues/14429

### ISSUE THREAD

**Issue by jinglichen66** [containers/podman#15203]
is https://github.com/containers/podman/issues/14429 issue fixed? i installed MacOs 12.4 on M1, still got all the errors in issue 14429. 

/kind bug

I have M1 tried to get podman works. i have 

**Description**

podman --version
**Describe the results you received:**
podman version 4.1.1
**Describe the results you received:**
podman version
**Describe the results you received:**
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: connection to bastion host (ssh://core@localhost:56433/run/user/503/podman/podman.sock) failed: dial tcp [::1]:56433: connect: connection refused

podman machine start

**Describe the results you received:**
Starting machine "podman-machine-default"
Waiting for VM ...
Error: dial unix /var/folders/6f/mky_4w3x0y76bh6785kjnsv00000gq/T/podman/podman-machine-default_ready.sock: connect: connection refused

podman version

**Describe the results you received:**

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: connection to bastion host (ssh://core@localhost:56433/run/user/503/podman/podman.sock) failed: dial tcp [::1]:56433: connect: connection refused

podman info --debug
**Describe the results you received:**
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: connection to bastion host (ssh://core@localhost:56433/run/user/503/podman/podman.sock) failed: dial tcp [::1]:56433: connect: connection refused

macos-WDFXKGYXRK:acquisition-gateway jli$ podman machine rm podman-machine-default
**Describe the results you received:**
The following files will be deleted:

/Users/jli/.ssh/podman-machine-default
/Users/jli/.ssh/podman-machine-default.pub
/Users/jli/.config/containers/podman/machine/qemu/podman-machine-default.ign
/Users/jli/.local/share/containers/podman/machine/qemu/podman-machine-default_fedora-coreos-36.20220703.3.1-qemu.aarch64.qcow2
/Users/jli/.local/share/containers/podman/machine/podman-machine-default/podman.sock
/Users/jli/.local/share/containers/podman/machine/qemu/podman-machine-default_ovmf_vars.fd
/Users/jli/.config/containers/podman/machine/qemu/podman-machine-default.json

Are you sure you want to continue? [y/N] y
macos-WDFXKGYXRK:acquisition-gateway jli$ podman machine rm podman-machine-default
Error: podman-machine-default: VM does not exist

macos-WDFXKGYXRK:acquisition-gateway jli$ podman machine list
NAME                     VM TYPE     CREATED     LAST UP     CPUS        MEMORY      DISK SIZE
podman-machine-default*  qemu        8 days ago  8 days ago  4           2.147GB     107.4GB

**Comment by mheon** [comment]
Does starting the VM work?

@baude @ashley-cui PTAL

**Comment by baude** [comment]
did you update qemu?

**Comment by jinglichen66** [comment]
i did update qemu.
macos-WDFXKGYXRK:web-service-integration jli$ qemu-system-aarch64 --version
QEMU emulator version 6.2.0

**Comment by jinglichen66** [comment]
jli$ podman machine init
Downloading VM image: fedora-coreos-36.20220806.2.0-qemu.aarch64.qcow2.xz: done  
Extracting compressed file
Image resized.
Machine init complete
To start your machine run:

	podman machine start

 jli$ podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Error: dial unix /var/folders/6f/mky_4w3x0y76bh6785kjnsv00000gq/T/podman/podman-machine-default_ready.sock: connect: connection refused

**Comment by Jake-Gillberg** [comment]
Experiencing the same issue with podman v 4.1.1 and qemu 7.0.0

**Comment by ashley-cui** [comment]
This should be an issue with qemu 7 and 12.4 on Mac Pros. Please upgrade your OS.
