### ISSUE TITLE
podman machine ssh: Additional layer of quoting is required

### ISSUE THREAD

**Issue by graywolf-at-work** [containers/podman#15212]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Documented usage of podman-machine-ssh is

	podman machine ssh [options] [name] [command [arg ...]]

Therefore I would expect to

	podman machine ssh sh -c 'echo a b c'

be the same as

	sh -c 'echo a b c'

but execute inside the machine. That does not seem to be the case and
additional layer of quoting is required:

	 podman machine ssh sh -c '"echo a b c"'

**Steps to reproduce the issue:**

1. `podman machine ssh sh -c 'echo a b c'`

**Describe the results you received:**

	$ podman machine ssh sh -c 'echo a b c'
	Warning: Permanently added '[localhost]:53014' (ED25519) to the list of known hosts.
	

**Describe the results you expected:**

	$ podman machine ssh sh -c 'echo a b c'
	Warning: Permanently added '[localhost]:53014' (ED25519) to the list of known hosts.
	a b c

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.3
Built:        Tue Jun 14 22:12:46 2022
OS/Arch:      darwin/amd64

Server:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.3
Built:        Wed Jun 22 18:17:44 2022
OS/Arch:      linux/amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

MacOS, amd64.

**Comment by Luap99** [comment]
This is not a podman problem.

ssh always runs the command with the login shell, i.e.  `sh -c` therefore you command becomes `sh -c 'sh -c echo a b c'`
To fix this just run `ssh "echo a b c"`
