### ISSUE TITLE
libpod api will not return stats if the container is exited

### ISSUE THREAD

**Issue by ttys3** [containers/podman#15218]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

according to https://github.com/containers/podman/pull/14580

Non-running containers now report statistics via the podman stats

but I see the result for libpod api is : return nothing.

**Steps to reproduce the issue:**

1.  `podman run --name demo -ti alpine sh -c 'echo hello'`

2.  `sudo podman stats --no-stream demo` get:

```
ID            NAME        CPU %       MEM USAGE / LIMIT  MEM %       NET IO      BLOCK IO    PIDS        CPU TIME    AVG CPU %
9ef32ea2cb0e  demo        0.00%       0B / 0B            0.00%       0B / 0B     0B / 0B     0           0s          0.00%
```

3. but libpod api get nothing:

```
sudo curl -vvv --unix-socket /run/podman/podman.sock http://d/v1.0.0/libpod/containers/demo/stats\?stream\=false
*   Trying /run/podman/podman.sock:0...
* Connected to d (/run/podman/podman.sock) port 80 (#0)
> GET /v1.0.0/libpod/containers/demo/stats?stream=false HTTP/1.1
> Host: d
> User-Agent: curl/7.84.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Api-Version: 1.41
< Libpod-Api-Version: 4.2.0-rc3
< Server: Libpod/4.2.0-rc3 (linux)
< X-Reference-Id: 0xc000014078
< Date: Fri, 05 Aug 2022 17:48:21 GMT
< Transfer-Encoding: chunked
< 
* Connection #0 to host d left intact
```

**Describe the results you received:**

nothing but a 200 code

**Describe the results you expected:**

zero stats just like the cli or it should return http error code ?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman v4.1.1 and podman 4.2.0-rc3
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@mheon PTAL

**Comment by mheon** [comment]
We got a feature request in to allow this for the Docker-compat endpoints, so we enabled it there; never enabled it for the Libpod endpoints because nobody asked. Should be simple enough.

**Comment by mheon** [comment]
Actually, this might be expected behavior... Let me verify against the Docker endpoints.

**Comment by mheon** [comment]
Verified against Docker, this is expected behavior. If the container is not started, we return nothing, same as Docker. Going to close given this.

**Comment by ttys3** [comment]
the problem is, this change bring from cli, maybe related to https://github.com/containers/podman/pull/14580, I do not know.
it is a breaking change for libpod api.

previous version like podman v4.0.3, the cli will result in:  `Error: container state improper`

and the libpod api will return:

```
< HTTP/1.1 409 Conflict
< Api-Version: 1.40
< Content-Type: application/json
< Libpod-Api-Version: 4.0.3
< Server: Libpod/4.0.3 (linux)
< X-Reference-Id: 0xc000518010
< Date: Sun, 07 Aug 2022 20:14:53 GMT
< Content-Length: 89
< 
{"cause":"container state improper","message":"container state improper","response":409}
```

**Comment by mheon** [comment]
It's a change, but I don't know if I would consider it a breaking change? It's a bugfix more than anything, given we did not match existing behavior / expected behavior vs Docker
