### ISSUE TITLE
Problems with Memory Quota

### ISSUE THREAD

**Issue by artemdxc** [containers/podman#15213]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I tried to run a container with the memory quota (--memory) and then tried to run some corresponding tests. But it seems that it is possible to allocate more memory than is was set with the mentioned parameter. Swap is disabled in OS.

**Steps to reproduce the issue:**

1. Build a simple container: Containerfile has the only command: `FROM ubuntu:latest`

2. Disable swap: `sudo swapoff -a` (host OS is Ubuntu too)

3. Start this container with the --memory option:
`podman run -dt --memory=10m -v $HOME:$HOME localhost/test:latest`
`podman attach 12345678`

5. Try to allocate RAM by the following commands:

either
> sh -c "MEMBLOB=\$(dd if=/dev/urandom bs=100MB count=1)"

or

> date ; </dev/zero head -c 100m | tail ; date

6. Try to allocate RAM by the simple C++ program which just uses the `new` operator and catches an exception if any occurs.

**Describe the results you received:**

It is possible to allocate much more memory than it was set with `--memory` before the tests begin to fail.

**Describe the results you expected:**

(Citation from the official documentation: [https://docs.podman.io/en/latest/markdown/podman-run.1.html](https://docs.podman.io/en/latest/markdown/podman-run.1.html) )

> --memory, -m=number[unit]
> ( . . . )
> Allows you to constrain the memory available to a container

Since the `--memory` option is set and swap is disabled I expect that it should be impossible to allocate more than the constrained amount of RAM.

**Output of `podman version`:**

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Thu Jan  1 03:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 1
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: artem-VirtualBox
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.0-43-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 62042112
  memTotal: 1018404864
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 0
  swapTotal: 0
  uptime: 1h 35m 28.64s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/artem/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/artem/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /home/artem/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Thu Jan  1 03:00:00 1970
  GitCommit: ""
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 3.4.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/jammy,now 3.4.4+ds1-1ubuntu1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Using VirtualBox. Host OS for the VirtualBox is Windows 10.
OS inside VirtualBox is Ubuntu 22.04, container has been built with the same one (`ubuntu:latest` refers to 22.04 at the moment)

Also this behavior is reproduced on the ARM-based board working on Linux kernel

**Comment by giuseppe** [comment]
could you show the output of `cat /sys/fs/cgroup/memory.max` inside the container?

**Comment by artemdxc** [comment]
```
artem@artem-VirtualBox:~$ podman run -dt --memory=10m localhost/ololo:latest
66abe8514e450de132e917b2c307d33a63daf5b17898a0ab10f7dbee3b1ea701
artem@artem-VirtualBox:~$ podman attach 66
root@66abe8514e45:/# cat /sys/fs/cgroup/memory.max 
10485760
root@66abe8514e45:/#
```

**Comment by giuseppe** [comment]
the cgroup configuration seems fine.

With a slight modification to your reproducer, could you try `date ; </dev/zero head -c 100m | tail && echo ok ; date` ?

Could you also trying adding `--cgroup-conf memory.oom.group=1` to the run command so the entire container is destroyed on OOM: `podman run ... --cgroup-conf memory.oom.group=1 --memory=10m`

Another thing you'd like to check is the value of `/proc/sys/vm/oom_kill_allocating_task`

**Comment by artemdxc** [comment]
```
artem@artem-VirtualBox:~$ cat /proc/sys/vm/oom_kill_allocating_task 
0
```
Starting the container:
```
artem@artem-VirtualBox:~$ podman run -dt --memory=10m --cgroup-conf memory.oom.group=1 -v $HOME:$HOME localhost/test:latest
```
Trying the test command:
```
root@a4f1d7902950:~# </dev/zero head -c 1m | tail && echo ok

artem@artem-VirtualBox:~$ podman ps -a
CONTAINER ID  IMAGE                   COMMAND     CREATED        STATUS            PORTS       NAMES
a4f1d7902950  localhost/test:latest  bash        3 minutes ago  Up 3 minutes ago              vibrant_moser
artem@artem-VirtualBox:~$
```
If I try to allocate up to 9 MB it causes logout without stopping the container. But when I try to allocate 9 MB or more it causes stopping the container with error code 137.
But this command behaves strange itself. For example, if I run another similar container with 100MB memory quota and try to allocate just 1 MB, this command could cause logout from the container without its stopping:
```
artem@artem-VirtualBox:~$ podman run -dt --memory=100m --cgroup-conf memory.oom.group=1 -v $HOME:$HOME localhost/ololo:latest
d9e6d4e6525a09e9c5676f091272e7c25772910b54ac2aac47b448a3e118bf82
artem@artem-VirtualBox:~$ podman attach d9
root@d9e6d4e6525a:/# </dev/zero head -c 1m | tail && echo ok

artem@artem-VirtualBox:~$ podman ps -a
CONTAINER ID  IMAGE                   COMMAND     CREATED         STATUS                           PORTS       NAMES
a4f1d7902950  localhost/test:latest  bash        29 minutes ago  Exited (137) About a minute ago              vibrant_moser
d9e6d4e6525a  localhost/test:latest  bash        54 seconds ago  Up 54 seconds ago                            silly_meitner
artem@artem-VirtualBox:~$
```
The next command also has an unexpected behaviour.
```
sh -c "MEMBLOB=$(dd if=/dev/urandom bs=10MB count=10)"
```
Trying to allocate 10 of 10MB blocks inside the 100MB-quoted container causes its stopping with exit code 129 **_and logout from the host OS user session._**

And the last test with the following C++ program (which tries to allocate certain amount of RAM and catches an exception):
```
#include <iostream>
#include <exception>
#include <stdlib.h>  // atoi()

int main(int argc, char* argv[]) {
    if (argc < 2) {
        std::cout << "Please specify the 1st argument: size-to-allocate (in MB)\n";
        return 0;
    }
    unsigned int size = atoi(argv[1]);
    std::cout << "Trying to allocate " << size << " MB...\n";
    size *= 1024 * 1024;
    char* blob;
    try {
        blob = new char[size];
    }
    catch (std::exception& e) {
        std::cerr << "Exception caught!\n'" << e.what() << "'\n";
        return 135;
    }
    delete [] blob;
    std::cout << "Memory has been freed\n";
    return 0;
}
```
I tried this program inside the 10MB-quoted container.
It seems that it is able to allocate much more than 10MB, even up to all of free memory (virtual machine has 1 GB RAM total and about 971 MB free).
```
root@a4f1d7902950:/home/artem/test-podman/scripts# ./allocate 10
Trying to allocate 10 MB...
Success!
Memory has been freed
root@a4f1d7902950:/home/artem/test-podman/scripts# ./allocate 100
Trying to allocate 100 MB...
Success!
Memory has been freed
root@a4f1d7902950:/home/artem/test-podman/scripts# ./allocate 1000
Trying to allocate 1000 MB...
Exception caught!
'std::bad_alloc'
root@a4f1d7902950:/home/artem/test-podman/scripts#
```

**Comment by rhatdan** [comment]
@giuseppe any update
