### ISSUE TITLE
remote manifest push gives no output

### ISSUE THREAD

**Issue by YoitoFes** [containers/podman#15210]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`podman-remote manifest push` does not print any output.

**Steps to reproduce the issue:**

```bash
$ podman-remote manifest push localhost/image:latest some.registry.com/image:latest
```

**Describe the results you received:**

No output.

**Describe the results you expected:**

Output.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```bash
$ podman version
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.4
Built:        Sat Jul 23 04:05:59 2022
OS/Arch:      linux/amd64
```

It would be grateful if it was fixed as well as #14971. Tanks.

**Comment by rhatdan** [comment]
@flouthoc PTAL

**Comment by YoitoFes** [comment]
@flouthoc Created a fix for the issue at https://github.com/YoitoFes/podman/tree/fix-15210. Will open PR if you don't mind. Thank you for looking into the issue.

**Comment by flouthoc** [comment]
@YoitoFes Sure, please open a PR :)
