### ISSUE TITLE
[FEATURE REQUEST]: Support writing image push progress to specified io.Writer on golang bindings

### ISSUE THREAD

**Issue by YoitoFes** [containers/podman#15211]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

As of #15022 golang bindings writes image push progress to `os.Stderr`. It would be grateful if bindings added support writing to specified io.Writer as well as image building (https://github.com/containers/podman/blob/main/pkg/bindings/images/build.go#L357-L360).

Tanks.

**Comment by rhatdan** [comment]
Interested in opening a PR?

**Comment by YoitoFes** [comment]
Opened PR #15230. Wrote no unit tests for the added option since I cannot find any existing UT using container registry; e.g. UT for binding manifest push is skipped as TODO.

- https://github.com/containers/podman/blob/main/pkg/bindings/test/manifests_test.go#L175-L177
  ```go
  It("push manifest", func() {
  	Skip("TODO: implement test for manifest push to registry")
  })
  ```

If there is available registry for UT, I would grateful if you could tell me. I will write UT.
