### ISSUE TITLE
Error: writing blob: adding layer with blob "sha256:[ hash ]": Error processing tar file(exit status 1): operation not permitted

### ISSUE THREAD

**Issue by crdoconnor** [containers/podman#15224]
/kind bug

**Description**

Running "podman pull docker.io/localstack/localstack" triggers this error after about 2/3 is downloaded when running podman inside another podman container.

**Steps to reproduce the issue:**

I have created a small repo which reproduces the bug:

https://github.com/crdoconnor/podman-in-podman-bug

I have tried it on ubuntu 22.04 and on mac M1. I saw the same results in both environments.

**Describe the results you received:**

```
Error: writing blob: adding layer with blob "sha256:[ hash ]": Error processing tar file(exit status 1): operation not permitted
```

**Describe the results you expected:**

podman pull should just work.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

4.1.1 (on mac)
3.4.4 (on ubuntu)

**Output of `podman info`:**

```
host:
  arch: arm64
  buildahVersion: 1.26.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc36.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpuUtilization:
    idlePercent: 97.19
    systemPercent: 1.23
    userPercent: 1.58
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "36"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.18.13-200.fc36.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 515596288
  memTotal: 4090580992
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.5-1.fc36.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.aarch64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 2h 53m 43.77s (Approximately 0.08 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 12
    paused: 0
    running: 2
    stopped: 10
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 106825756672
  graphRootUsed: 7091908608
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 43
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1655914710
  BuiltTime: Wed Jun 22 17:18:30 2022
  GitCommit: ""
  GoVersion: go1.18.3
  Os: linux
  OsArch: linux/arm64
  Version: 4.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.1.1-2.fc36.aarch64
```

(run from podman machine ssh)

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Tried on AMD64 (ubuntu 22.04) / AARCH64 (M1).

**Comment by mheon** [comment]
Can you pull *any* image, or is it just the localstack/localstack image that fails?

**Comment by crdoconnor** [comment]
Some pass, some fail. The two that I verified failing multiple times were localstack/localstack and swaggerapi/swagger-ui. porman run hello-world will always run fine.

I'm now investigating the version of podman inside the docker container - it's running version 3.4.4 which may be why this is happening. I will try to upgrade it somehow to 4.1.1. If that fixes it I will close this issue.

**Comment by mheon** [comment]
Can you try using the official Podman image (`quay.io/podman/stable`)? I know we have some magic baked in there to help support Podman-in-container usecases; if it does work, it would support there being an issue with the outer container.

**Comment by crdoconnor** [comment]
That's good to know.

Yeah, that seems to fix it. Shall I close the issue?

**Comment by rhatdan** [comment]
Yes I will close.
