### ISSUE TITLE
enhance the usability of `podman pod` command to align related features (play, pod, generate)

### ISSUE THREAD

**Issue by larrycai** [containers/podman#15232]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

It is a mess in current podman version (`v4.1.1`) for pod management using different sub-command. 

````
podman stop mypod-myapp
podman create --pod --name myapp2 ..
podman rm mypod-myapp
podman pod start mypod
podman play kube
podman generate kube
podman pod ps --ctr-ids
````

BTW: I do not want to cover `podman-compose` package, since I think `podman` shall have new thinking of how to use pod.

It confused the user who is new to podman since those commands are not logically connected or strange sub-command like `play`, `generate`

**Describe the results you expected:**

Below is just some thinking I have.

It could be grouped everything into `podman pod` subcommand and phase out `podman play/generate` command.

Something like (may later use table to compare the command)

````
podman pod create mypod # same podman create --pod
podman pod create|apply -f mypod.yaml # similar with kubectl command and replace podman play
podman pod export mypod -o yaml # replace podman play kube ge
podman pod show -l mypod  # can follow kubectl command  to remove --ctr-ids related parameters
````

surely some commands can be kept even it is related with pod

````
podman create --pod  # it is nice to keep
````

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.3
Built:        Tue Jun 14 22:12:46 2022
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.3
Built:        Wed Jun 22 18:18:30 2022
OS/Arch:      linux/arm64
```

**Comment by vrothberg** [comment]
Thanks for reaching out, @larrycai!

I agree on the disconnect between `podman play kube` and `podman generate kube`.  Starting with Podman v4.3, there will be a `podman kube` command with the `play`, `generate` and `down` sub-commands.

Conceptually, the `kube` commands are implemented by means of using `pods` but a `kube play` may start one or multiple pods. Hence I think that the `kube` functionality should not be moved under `podman pod ...`.

**Comment by rhatdan** [comment]
Yes `podman kube ...` and `podman pod ...` are two different things. We plan on treating kubernetes.yaml in a similar way to the way Kubernetes treats Pods and Containers.
Podman pod is to allow users to manipulate pods in a similar way that they interact with traditional containers.

De-emphasizing/Depracating `podman play` in podman 4.3 is the way to help eliminate some of the confusion.

**Comment by larrycai** [comment]
great, `podman pod` & `podman kube` are good sub commands, will see how it works! 

I think I can close this ticket, if u already have ticket/issue for this topic, please connect it so I can easily monitor for it

Thanks @rhatdan & @vrothberg
