### ISSUE TITLE
podman pull from yocto

### ISSUE THREAD

**Issue by meox** [containers/podman#15238]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Try to run `podman pull` inside yocto give this error:
`cannot setresgid: Invalid argument`

**Steps to reproduce the issue:**

not so easy to reproduce because you need a yocto

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.19
Built:        Thu Aug  4 12:34:08 2022
OS/Arch:      linux/arm64
```

**Output of `podman info`:**

```
host:
  arch: arm64
  buildahVersion: 1.26.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon_2.0.25+ds1-1.1_arm64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpuUtilization:
    idlePercent: 98.71
    systemPercent: 0.33
    userPercent: 0.96
  cpus: 6
  distribution:
    codename: bullseye
    distribution: debian
    version: "11"
  eventLogger: file
  hostname: athonetos
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.0-16-arm64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 5431648256
  memTotal: 8326893568
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun_0.17+dfsg-1_arm64
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.0.1-2_arm64
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.4.0
  swapFree: 1023406080
  swapTotal: 1023406080
  uptime: 1h 35m 2.5s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 261546864640
  graphRootUsed: 88358948864
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1659609248
  BuiltTime: Thu Aug  4 12:34:08 2022
  GitCommit: ""
  GoVersion: go1.19
  Os: linux
  OsArch: linux/arm64
  Version: 4.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman has been compiled from source
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
uname -a: Linux 5.10.0-16-arm64 #1 SMP Debian 5.10.127-2 (2022-07-23) aarch64 GNU/Linux

**Comment by giuseppe** [comment]
Are you running podman as root?  If you are not running podman as root, please show the output of `podman info` when you as the unprivileged user as well as the output of `podman --log-level debug unshare true`

Could you please show also the content of `/proc/self/uid_map`?

**Comment by meox** [comment]
Inside the Yocto:

```
> /usr/local/bin/podman --log-level debug unshare true

"/usr/local/bin/podman filtering at log level debug"
"Called unshare.PersistentPreRunE(/usr/local/bin/podman --log-level debug unshare true)"

"Merged system config \"/usr/share/containers/containers.conf\""

"Using conmon: \"/usr/bin/conmon\""

"Initializing boltdb state at /home/meox/.local/share/containers/storage/libpod/bolt_state.db"

"Using graph driver vfs"
"Using graph root /home/meox/.local/share/containers/storage"
"Using run root /run/user/1000/containers"
"Using static dir /home/meox/.local/share/containers/storage/libpod"
"Using tmp dir /run/user/1000/libpod/tmp"
"Using volume path /home/meox/.local/share/containers/storage/volumes"

"Set libpod namespace to \"\""
"Not configuring container store"
"Initializing event backend file"

"Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument"
"Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument"
"Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument"
"Using OCI runtime \"/usr/bin/crun\""

cannot setresgid: Invalid argument

Error: setting up the process
```

uid_map from the host machine:
```
 cat /proc/self/uid_map
         0          0 4294967295
```


uid_map from inside yocto:
```
+ cat /proc/self/uid_map
      1000       1000          1
```

**Comment by giuseppe** [comment]
so yocto is running in a user namespace where a single user is mapped `1000       1000          1`

With such configuration you are not able to run containers that use IDs != 0.  You'll also need to set `ignore_chown_errors = "true"` in your storage.conf file.

Since the issue depends on your environment, I am going to close the issue but please feel free to comment further

**Comment by meox** [comment]
but why podman pull depends by this environment?
dokcer pull is working well

**Comment by giuseppe** [comment]
Is Docker itself also running in the yocto user namespace or is running on the host?

**Comment by meox** [comment]
> Is Docker itself also running in the yocto user namespace or is running on the host?

both running from yocto

I'm trying to debug what's going on and I found this:

At line 396 of `/pkg/rootless/rootless_linux.go` in `becomeRootInUserNS` function 
b[0]: is '1'
but when I run it outside yocto b[0] is '2'

**Comment by meox** [comment]
What I really need is a simple way to pull from a docker registry using `podman` and have the my root storage filled correctly.
For "filled correctly" I mean that if from the host I do: `podman images --root=<myroot>` I'm able to see it.

**Comment by rhatdan** [comment]
Doesn't the following work?
podman --root=<myroot> pull IMAGE
podman  --root=<myroot> image list

**Comment by meox** [comment]
> podman --root= pull IMAGE
cannot setresgid: Invalid argument

> podman --root= image list
cannot setresgid: Invalid argument

**Comment by rhatdan** [comment]
Sorry I markdown removed my ```<myroot>```

**Comment by meox** [comment]
Setting or not setting the root parameters doesn't change the result (unfortunately).
What I'm trying to do is a "simple" pull. I'm not trying to run the container.

If I try to use `podman --remote` it works but I'd like to avoid it

**Comment by giuseppe** [comment]
> both running from yocto: the `docker pull` is issued from yocto but the docker daemon runs in the host

yes that is the difference.  Since docker runs in the host then it is not limited by the yocto user namespace.

You could do a similar thing with podman and run it as a daemon in the host (`podman system service -t 0`) and connect to it from the yocto environment.

In the yocto user namespace you've access to only one ID. Assuming we manage to get it working, you'd still be forced to squash all your images to just one ID.

**Comment by Razriel3** [comment]
I am having a similar problem.
running on ubuntu 20.04 as build machine.
podman install on this machine is 3.4.2
when running from regular shell podman pull succesful
when running from honister version podman pull succesful
when running same recipe from kirkston version it fails.
see log below.

can you direct me what to change ?


Log data follows:
| DEBUG: Executing shell function do_pull_image
| cannot setresgid: Invalid argument
| panic: runtime error: invalid memory address or nil pointer dereference
| [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5632d0bb17a0]
| 
| goroutine 1 [running]:
| github.com/containers/podman/vendor/github.com/containers/common/libimage.(*Runtime).Pull(0x0, 0x5632d1b3d720, 0xc0007b56e0, 0xc0001f9c90, 0xb, 0x0, 0xc000159a40, 0x0, 0x0, 0x0, ...)
|       /usr/src/packages/BUILD/src/github.com/containers/podman/vendor/github.com/containers/common/libimage/pull.go:117 +0x500
| github.com/containers/podman/pkg/domain/infra/abi.(*ImageEngine).Pull(0xc00012c3d0, 0x5632d1b3d720, 0xc0007b56e0, 0x7ffde5cbbe0c, 0xb, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
|       /usr/src/packages/BUILD/src/github.com/containers/podman/pkg/domain/infra/abi/images.go:231 +0x1e5
| github.com/containers/podman/cmd/podman/images.imagePull(0x5632d26d5e20, 0xc0000894f0, 0x1, 0x1, 0x0, 0x0)
|       /usr/src/packages/BUILD/src/github.com/containers/podman/cmd/podman/images/pull.go:160 +0x2d5
| github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).execute(0x5632d26d5e20, 0xc00003c1a0, 0x1, 0x1, 0x5632d26d5e20, 0xc00003c1a0)
|       /usr/src/packages/BUILD/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:856 +0x47c
| github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x5632d26e7120, 0xc00004a188, 0x5632d1886480, 0x5632d27a98f0)
|       /usr/src/packages/BUILD/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:974 +0x375
| github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).Execute(...)
|       /usr/src/packages/BUILD/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:902
| github.com/containers/podman/vendor/github.com/spf13/cobra.(*Command).ExecuteContext(...)
|       /usr/src/packages/BUILD/src/github.com/containers/podman/vendor/github.com/spf13/cobra/command.go:895
| main.Execute()
|       /usr/src/packages/BUILD/src/github.com/containers/podman/cmd/podman/root.go:91 +0xee
| main.main()
|       /usr/src/packages/BUILD/src/github.com/containers/podman/cmd/podman/main.go:39 +0x94
| WARNING: exit code 2 from a shell command.
