### ISSUE TITLE
Do emit securityContext.runAsNonRoot: true sometimes by `podman kube generate`

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#15231]
When the OCI manifest contains a user as a positive number, then `podman generate kube` shall include in the Pod object spec.containers[*].securityContext.runAsNonRoot = true.

That is, when the `"mediaType":"application/vnd.oci.image.config.v1+json"` file contains: `{{"User":"number:number"…}}`, then
```console
$ podman generate kube
apiVersion: v1
kind: Pod
spec:
  containers:
  - securityContext:
      runAsNonRoot: true
_
```
Note that Kubernetes rejects containers, asking for runAsNonRoot:true, when
* the containers do not run as root, but
* have `User` above as text-user:text-group,

since at the time of the valitadion it is not known, if the text-user:text-group are root.  With other words, `/etc/passwd` is read after the validation for runAsNonRoot=true has finished.

**Comment by mheon** [comment]
I'm gonna label this as kind/bug given that this breaks K8S loading of YAML.

**Comment by dilyanpalauzov** [comment]
It does not break K8S loading of YAML.

**Comment by mheon** [comment]
Really? You noted that K8S rejects the containers?

**Comment by dilyanpalauzov** [comment]
K8S would reject a container/pod, if its YAML has `spec.securityContext:runAsNonRoot: true` and the user in the OCI-image specification is provided as text, not as number.  However currently nothing is rejected, since `podman generate kube` does not include `spec.securityContext:runAsNonRoot: true`.

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by rhatdan** [comment]
@dilyanpalauzov Interested in opengin a PR?

**Comment by dilyanpalauzov** [comment]
> @dilyanpalauzov Interested in opengin a PR?

No

**Comment by rhatdan** [comment]
@haircommander @saschagrunert @mrunalp WDYT?

**Comment by dilyanpalauzov** [comment]
`runAsUser` can be set to a number in different ways, like in the container-YAML file or in the OCI image itself.

When the UID is not set explicitly by podman, `runAsNonRoot` ensures that the OCI image sets the UID > 0.

**Comment by rhatdan** [comment]
@umohnani8 @haircommander @saschagrunert PTAL and verify what we should do here.

**Comment by rhatdan** [comment]
@umohnani8 @haircommander @saschagrunert PTAL and verify what we should do here.
