### ISSUE TITLE
Proposal for taking nydus store plugin as a non-core subproject

### ISSUE THREAD

**Issue by imeoer** [containers/podman#15249]
[Nydus](https://nydus.dev/) image is a container accelerated image format provided by the Dragonfly [image-service](https://github.com/dragonflyoss/image-service) project, which offers the ability to pull image data on demand, without waiting for the entire image pull to complete and then start the container. It has been in production and shown vast improvements over the OCI v1 image format in terms of container launching speed, image space, and network bandwidth efficiency, as well as data integrity. Nydus image can be flexibly configured as a FUSE-based user-space filesystem or in-kernel FS with nydus daemon in user-space:

- Lightweight integration with VM-based containers runtime like [KataContainers](https://katacontainers.io/). KataContainers is [supported](https://github.com/kata-containers/kata-containers/blob/cf53ec2c714d3dd665806c07d92120ae869f1573/docs/design/kata-nydus-design.md) Nydus as a native image acceleration solution.
- Nydus closely cooperates with Linux in-kernel disk filesystem containers' rootfs can directly be set up by [EROFS over Fscache](https://d7y.io/blog/2022/06/06/evolution-of-nydus) with lazy pulling capability. The corresponding changes has been in Linux kernel since v5.19.

Nydus has been running steadily for 3 years in Alibaba Cloud, Ant Group, and ByteDance, supporting large-scale container clusters and the creation of millions of containers per day, serving thousands of customers in various business fields.

Podman is a user-friendly container runtime, we'd like to make it support Nydus images as well, so we created the [nydus store plugin](https://github.com/dragonflyoss/image-service/pull/655) project like [stargz store plugin](https://github.com/containerd/stargz-snapshotter/blob/main/docs/INSTALL.md#install-stargz-store-for-cri-opodman-with-systemd), the project implements an additional layer store plugin for CRI-O/Podman, so that nydus images can be mounted with lazy pulling. The plugin depends on [additional layer store plugin](https://github.com/containers/storage/pull/795) feature, uses go fuse implementation to interact with podman in filesystem, and nydusd does the actual remote mount for nydus image.

Now we would like to ask the community's opinion if we can propose to make the nydus store plugin as a non-core subproject of the containers community, we believe that the donation to containers will attract more users and developers for nydus itself and bring much value to the containers community users.

Looking forward to any feedback, thanks!

**Comment by vrothberg** [comment]
Thanks for reaching out and for providing all the details, @imeoer!

@containers/podman-maintainers WDYT?

**Comment by giuseppe** [comment]
I am in favor of it as long as there is at least one maintainer for the project.

@imeoer who would be the maintainer?

If we agree to move forward, I can help to set up the repository here

**Comment by rhatdan** [comment]
I am fine with this, as long as it has maintainers.  I would also like to see it packaged up into Fedora and made easy to be used by Podman.

**Comment by TomSweeneyRedHat** [comment]
SGTM, assuming a maintainer(s) is identified as @giuseppe noted and that appropriate tests and documentation are included.  Thanks for bringing this forward @imeoer !

**Comment by imeoer** [comment]
@vrothberg @giuseppe @rhatdan @TomSweeneyRedHat 

Many thanks to all, @fatelei and @imeoer will be the initial maintainers, we currently have an [initial version](https://github.com/dragonflyoss/image-service/pull/655) and will continue to refine and add tests and documentation, please let us know if there are any additional details and conduct of community to be aware of, thanks!

**Comment by baude** [comment]
hello @imeoer to be be more clear, when we discussed this as a team, we wanted it to actually work with podman.  how close are you to that?

**Comment by imeoer** [comment]
@baude Thanks for the reply, the [current](https://github.com/dragonflyoss/image-service/pull/655) implementation allows podman to basically run the nydus image, here is a [demo](https://github.com/dragonflyoss/image-service/blob/388b1808b693b64544876a5458436bc0ba1ab824/contrib/crio-nydus-store-plugin/README.md) and simple documentation, currently we need to continue to enhance the stability, functionality, and additional testing and documentation, will reach production availability in the future.

**Comment by baude** [comment]
ok, excellent; @giuseppe i can also help as well.

**Comment by imeoer** [comment]
@baude Thanks :) cc @giuseppe If have any details needed to be provided to create the repository, please help to tell, thanks.

**Comment by giuseppe** [comment]
should I create a new repository or do you prefer if I move an existing project?

If we go for a new repository, what should be its name?  nydus-storage-plugin?

**Comment by imeoer** [comment]
> should I create a new repository or do you prefer if I move an existing project?
> 
> If we go for a new repository, what should be its name? nydus-storage-plugin?

Thanks for the reply, a new repository is good for me, and `nydus-storage-plugin` is ok.

**Comment by giuseppe** [comment]
created https://github.com/containers/nydus-storage-plugin and added both of you as admin.

Welcome aboard!

**Comment by imeoer** [comment]
Thanks all! We are cleaning up the code and will push the initial version soon. cc @fatelei
