### ISSUE TITLE
Podman not cleanly switching from Netavark to CNI network backend

### ISSUE THREAD

**Issue by mattgagliardi** [containers/podman#15245]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

*All of the following as unprivileged/rootless.*

 I've deployed a new RHEL 9 server machine (VM) and installed Podman 4.0.2 from the repo.  For REASONS I'm trying to switch the network backend to CNI, this is *before* deploying any containers, etc.  Immediately after the deployment is finished I edit the containers.conf file(s) as the Podman documentation indicates I should (network_backend="cni").  After performing a "podman system reset" and rebooting the machine I log back in as an unprivileged user.

 Again, following the Podman documentation I inspect/export the default network ("podman") information into a JSON-formatted file and upon CAT'ing the file it appears to be netavark-formatted rather than CNI-formatted.  Upon deploying a container to this network and attaching to it to review the interface configuration I see a tap0 interface and an IP address I've come to associate with a netavark-backed network.  In addition doing a podman inspect <container> shows no IP address, as I'm accustomed to seeing in a netavark-backed container.  This seems wrong.

 If I create a new network (podman create network test-net) and review the config. file for this network it follows the expected CNI formatting. Deploying a new container (same image) on this new network and reviewing its interface/IP shows me the anticipated eth0 interface and an IP address in the range displayed in the config. file of the new network, which I've come to associate with a CNI-backed network.  And a podman inspect <container> shows an IP address assigned.  This seems to be the behavior I'm after.

  In short, it seems as though the default network (podman) is getting "stuck" in netavark mode.

**Steps to reproduce the issue:**

1. Install a fresh Podman 4.0.2 environment on a RHEL 9 server machine.  Log into the machine and edit containers.conf file(s) appropriately, changing the file to reflect network_backend="cni".  Perform a "podman system reset" and reboot the machine.

2. Log back into the machine as an unprivileged user (rootless) and deploy a container onto the default network.  Examine the interface configuration, looking specifically at the interface type and IP address.  If this follows the pattern I've seen the information will reflect information that seems to imply a netavark backend.

3. Create a new Podman network (podman network create test-network) and deploy another container using the same image as before onto the new network.  Examine the container's interface configuration; again if the pattern I've observed holds the interface will now show the expected eth0 interface and an IP address in the ranged defined in the network config. file.

**Describe the results you received:**
The default network ("podman") appears to retain its netavark-formatted config.; when entering a running container and examining the network interface/information I see a tap0 interface and an IP address I'd expect to see in a netavark-based namespace.

**Describe the results you expected:**
Expected the default network ("podman") to have a config. that resembled CNI formatting after issuing issuing "podman network inspect podman | jq .[] > ~/.podman.json".  Likewise after logging into a running container deployed on the default network expected to see an eth0 interface with an IP address as defined in the file resulting from the above command.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7

Built:      Thu May 19 13:18:11 2022
OS/Arch:    linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 3a898eb433ae426e729088ccdc2bdae44a3164da'
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "9.0"
  eventLogger: file
  hostname: rh9-pod-cni
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.14.0-70.17.1.el9_0.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 10961268736
  memTotal: 12514603008
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun-1.4.4-2.el9_0.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.4
      commit: 6521fcc5806f20f6187eb933f9f45130c86da230
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-4.el9.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 6h 31m 13.79s (Approximately 0.25 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
  - docker.io
store:
  configFile: /home/kcservice/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/kcservice/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/1001/containers
  volumePath: /home/kcservice/.local/share/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1652984291
  BuiltTime: Thu May 19 13:18:11 2022
  GitCommit: ""
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.0.2-7.el9_0.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is a new RHEL 9 server VM running on vSphere 6.7.

**Comment by mattgagliardi** [comment]
Something of a refinement/update:
1. When I wrote that I deployed a container to the default network… I issued the run command *without specifying* a network, the container appears to end up connected to a network (as I’d expect, there is a port mapped after all ;) ), that network appears to be a netavark-backed namespace/network. 
2. Just tested actually specifying the default network (--net podman), this works as desired with the container appearing to be attached to a CNI-backed network. 

So…Podman seems to be doing something odd (or at least not something I’d expect) if the network isn’t specified, which I wouldn’t expect to have to do if all I wanted was the container hooked up to the default net.

**Comment by mheon** [comment]
I'm going to tag this for @Luap99 when he gets back

**Comment by mattgagliardi** [comment]
Cool, thank you!

Sent from my iPhone

On Aug 25, 2022, at 1:53 PM, Matt Heon ***@***.***> wrote:

﻿

I'm going to tag this for @Luap99<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FLuap99&data=05%7C01%7C%7C30447022bd5d472c38f908da86cb28bd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637970504368078933%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=mkr3oL62fo%2F84zeVqHdQlrn%2FJLY5alIAdubKXHL7M7Y%3D&reserved=0> when he gets back

**Comment by Luap99** [comment]
rootless podman will not use a bridge network by default, the default is slirp4netns and this creates a tap interface.
slirp4netns has nothing to do with netavark/cni it is just a different network mode.

If you want bridge use `--network bridge` or `--network podman`. The network inspect output format always uses a fix structure now and not the awkward cni configs which were basically impossible to parse for clients.
