### ISSUE TITLE
[Windows] Published UDP Ports Inaccessible

### ISSUE THREAD

**Issue by Narwhalrus** [containers/podman#15257]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

My rootful container is unable to receive UDP packets sent by the windows host.

TCP packets sent by the windows host work, and UDP/TCP packets sent from the `podman-machine-default` WSL2 VM make it through just fine.

**Steps to reproduce the issue:**

Install [ncat](https://nmap.org/ncat/) on Windows host

In powershell:

```
# Setup
PS> podman machine init
PS> podman machine set --rootful
PS> podman machine start
```
```
# Container Server
PS> podman run -it --rm -p 1234:1234/udp docker.io/itsthenetwork/alpine-ncat:latest -vul 1234
Ncat: Version 7.70 ( https://nmap.org/ncat )
Ncat: Listening on :::1234
Ncat: Listening on 0.0.0.0:1234
```

In another powershell instance:

```
# Host Client Test
PS> ncat -vu localhost 1234 # This also fails if I replace localhost with 127.0.0.1
Ncat: Version 7.92 ( https://nmap.org/ncat )
Ncat: Connected to ::1:1234.
typing some stuff here
Ncat: An existing connection was forcibly closed by the remote host. .
```

If I do the same, but from a `podman-machine-default` WSL2 terminal I receive the expected string inside my container

```
# WSL2 Client Test
[root@machine ~]# yum install nmap-ncat
[root@machine ~]# ncat -vu localhost 1234
Ncat: Version 7.92 ( https://nmap.org/ncat )
Ncat: Connected to 127.0.0.1:1234.
typing some stuff here
```

In my container terminal...

```
Ncat: Connection from 10.88.0.1.
typing some stuff here
```

If I do the same but listen on a TCP socket, my container can receive packets from the windows host
```
# Container TCP Server
PS> podman run -it --rm -p 1234:1234/tcp docker.io/itsthenetwork/alpine-ncat:latest -vl 1234
```

In another powershell instance:
```
# Host Client Test
PS> ncat localhost 1234
typing some stuff here
```

In my container terminal...

```
Ncat: Connection from 10.88.0.1.
Ncat: Connection from 10.88.0.1:39018.
typing some stuff here
```

**Describe the results you received:**

UDP data sent from Windows host is not received by container.

**Describe the results you expected:**

UDP data to be received by container regardless of whether I send it from inside of `podman-machine-default` or the Windows host.

**Additional information you deem important (e.g. issue happens only occasionally):**

As detailed above, TCP data can be sent by Windows host, and both TCP and UDP data can be sent from inside of WSL2.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.16.15
Git Commit:   f73d8f8875c2be7cd2049094c29aff90b1150241
Built:        Wed Jun 15 08:17:12 2022
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.2.0-rc3
API Version:  4.2.0-rc3
Go Version:   go1.16.15
Built:        Fri Aug  5 15:18:20 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.27.0-dev
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.3-1.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.3, commit: '
  cpuUtilization:
    idlePercent: 99.33
    systemPercent: 0.4
    userPercent: 0.27
  cpus: 12
  distribution:
    distribution: fedora
    variant: container
    version: "35"
  eventLogger: file
  hostname: machine
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.16.3-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 11968106496
  memTotal: 26765606912
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 7516192768
  swapTotal: 7516192768
  uptime: 24h 51m 8.00s (Approximately 1.00 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 13
    paused: 0
    running: 1
    stopped: 12
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 269490393088
  graphRootUsed: 13891088384
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 6
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.2.0-rc3
  Built: 1659730700
  BuiltTime: Fri Aug  5 15:18:20 2022
  GitCommit: ""
  GoVersion: go1.16.15
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0-rc3
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.2.0~rc3-2.fc35.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Comment by mheon** [comment]
@baude @ashley-cui PTAL

**Comment by Narwhalrus** [comment]
A workaround is to address the podman machine directly instead of trying to address `localhost` or `127.0.0.1`. I'd love for `localhost` to work as it does with TCP because it would save me the trouble of querying the IP from WSL.

**Comment by mheon** [comment]
@n1hility PTAL

**Comment by n1hility** [comment]
This is a limitation currently with WSL2 (loopback forwarding is only supported with TCP)

You can see the issue here:
https://github.com/microsoft/WSL/issues/4825

There are a couple of workarounds you could do:

1. You could install socat via cygwin and setup a script that forwards UDP on a set of ports you commonly use
2. You could setup a script to create an environment variable like WSLHOST that you can reference without looking it up

In the future, we may do a userspace networking layer that overrides WSL's network setup. That would help here. We might also offer a pure Virt solution (no WSL).

**Comment by Narwhalrus** [comment]
Thank you for getting back to me. I'm currently using the second workaround you mention. I'll keep any eye out for those future networking enhancements.

**Comment by igorMIA** [comment]
@Narwhalrus Is there a stable way to get the host machine ip?

**Comment by igorMIA** [comment]
@Narwhalrus Thanks! Unfortunately, it not working with frozen `resolv.conf`

**Comment by igorMIA** [comment]
Found a way how to do it without `resolv.conf`, case someone needed it: 
`host_ip=$(route -n | grep -m1 '^0.0.0.0' | awk '{ print $2; }')`

**Comment by n1hility** [comment]
Closing this for now due to the WSL limitations
