### ISSUE TITLE
[doc] add more explanation for `--userns keep-id` about uid mapping

### ISSUE THREAD

**Issue by larrycai** [containers/podman#15268]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

It is more about a question of understanding uid mapping in the `podman run --userns keep-id` command.

* https://docs.podman.io/en/latest/markdown/podman-run.1.html
* https://www.redhat.com/sysadmin/user-flag-rootless-containers 

```` .bash
~ $ id
uid=5658(guest) gid=54000(users) groups=54000(users)
~ $ cat /etc/subuid
podman:1:999
podman:1001:64535
guest:100000:65536
~ $ podman run -it --userns keep-id alpine
~ $ cat /proc/1/uid_map  # inside container
         0          1       5658
      5658          0          1
      5659       5659      59878
# compare 
$ podman run -it alpine
/ # cat /proc/1/uid_map  # inside container
         0       5658          1
         1     100000      65536
````

It is easily to understand uid mapping output for `root`, but for `keep-id`, how to understand the output.

**Describe the results you received:**

**Describe the results you expected:**

I expect it can be well described in related documentation.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.3
Built:        Wed Jun 22 16:17:44 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
$ podman version
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7

Built:      Tue Apr 19 12:16:32 2022
OS/Arch:    linux/amd64
```

**Comment by rhatdan** [comment]
The issue is you are seeing the mapping within a mapping.

```
$ podman run -it alpine
/ # cat /proc/1/uid_map  # inside container
         0       5658          1
         1     100000      65536
```
Is only doing a single mapping, basically this is joining the default user namespace.

When you use 
```
~ $ podman run -it --userns keep-id alpine
~ $ cat /proc/1/uid_map  # inside container
         0          1       5658
      5658          0          1
      5659       5659      59878
```
Podman is doing a remapping of the user namespace which has 65k UIDs.

It mapps UID 1->5658 (100000-105657) to 0->5657
It mappes your UID 0 (5658) back to UID 5658
Then it mapps the rest of the usernamespace to itself.
5659-59878 (105658-106536) -> 5659-59878

The UIDs inside of the () are the real UIDS on the host outside of all user namespaces.

**Comment by rhatdan** [comment]
Does that help you understand?

**Comment by larrycai** [comment]
I am not good at this part, so I am trying to find the command output to understand uid `5658` (inside) is mapped to uid (`105657 ` ?? ) outside

`````
$ podman run -d ubuntu sleep 80000
$ podman top -l user,huser
USER        HUSER
root          5658               <== this is clear to me
$ podman run -d --userns keep-id ubuntu sleep 80000 
$ podman top -l user,huser
USER        HUSER
guest        guest             <== ?
````

do we have parameter to show uid instead of name, here is always `guest`

**Comment by larrycai** [comment]
add extra uid mapping info https://stackoverflow.com/questions/70770437/mapping-of-user-ids

**Comment by larrycai** [comment]
Now I understand more about it, I explained for myself below

My host env 

```` .bash
~ $ id
uid=5658(guest) gid=54000(users) groups=54000(users)
~ $ cat /etc/subuid
podman:1:999
podman:1001:64535
guest:100000:65536
````

## For simple case, use default `--userns auto`

```` .bash
$ podman run -it ubuntu
/ # cat /proc/1/uid_map  # inside container
         0       5658          1
         1     100000      65536
$ podman run -d ubuntu sleep 80000
$ podman top -l user,huser
USER        HUSER
root        5658  
$ podman run -u 1000 -d ubuntu sleep 80000
$ podman top -l user,huser
USER        HUSER
1000        100999   
````

Now we can see the mapping

| inside container  | host | uid_map | notes |
| ------------- | ------------- | ----- | ---- |
|  root (0)  | guest(5658) | row 1 | 0 -> 5658 |
| 1000  | 100999| row 2 |  1->subuid base 100000, so 1000 -> subuid base 100000 + 1000 -1 

## For special case, use `--userns keep-id`

```` .bash
$ podman run -d --userns keep-id ubuntu sleep 80000
$ podman exec -t -l cat /proc/1/uid_map
         0          1       5658
      5658          0          1
      5659       5659      59878
$ podman top -l user,huser
USER        HUSER
guest        guest  
$ podman run -u 1000 -d --userns keep-id  ubuntu sleep 80000
$ podman top -l user,huser
USER        HUSER
1000        101000   
$ podman run -u 10000 -d --userns keep-id  ubuntu sleep 80000
$ podman top -l user,huser
USER        HUSER
10000       109999   
````

mapping for `5658` is special, others are calculate according to the able (see @rhatdan 's comments)

| inside container  | host | uid_map | notes |
| ------------- | ------------- | -----| -- |
|  guest(5658)  | guest(5658) | row 2 | it is special case with remapping  |
| 1000  | 101000| row 1 | 1000 < 5658,  0 .. 10000, 1000 .. 101000 ?? |
| 10000  | 109999 | row 3 | 10000 > 5659  ??  |

Another simple way to check the mapping is writing to the file 

```` .bash
$ cd $HOME 
$ chmod 777 .  # u can change to other folder
$ podman run -u 5659 -v $HOME:$HOME -d --userns keep-id ubuntu touch $HOME/abc
$ ls -al abc
-rw-r--r-- 1 105658 100000 0 Aug 11 07:44 abc
$  podman run -u 0 -v $HOME:$HOME -d --userns keep-id ubuntu touch $HOME/abc
0d1ea671db1d5f619c9d392593a0d34dfa819e073fbe125a6ff0b021ed2ae751
$ ls -al abc
-rw-r--r-- 1 100000 100000 0 Aug 11 07:51 abc
$ rm -f abc &&  podman run -u 1000 -v $HOME:$HOME -d --userns keep-id ubuntu touch $HOME/abc && ls -al abc
-rw-r--r-- 1 101000 100000 0 Aug 11 08:02 abc
$ rm -f abc &&  podman run -u 10000 -v $HOME:$HOME -d --userns keep-id ubuntu touch $HOME/abc && ls -al abc
-rw-r--r-- 1 109999 100000 0 Aug 11 08:02 abc
````

it is not so straight to understanding the mapping, but it is good enough for me
