### ISSUE TITLE
Almost all packets are lost when create macvlan on balance-alb bond interface

### ISSUE THREAD

**Issue by susanatgit** [containers/podman#15264]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Create balance-alb bond on interface1 and interface2
2. Run "podman network create" to create macvlan on bond interface as following:
podman network create -d macvlan --subnet=[subnet] -o parent=[bond-name] -o mode=bridge --gateway=[gateway][bond-name]
3. Run "podman run " to create container on the network which was created in steps 2 as following:
podman run -itd --name=test --network=[bond-name] --ip=[ipv4-address] [image-id] /bin/bash
4.  Ping the container

**Describe the results you received:**
Request timeout for icmp_seq .  It would use bond interface's mac address to reply, not container's mac address.

**Describe the results you expected:**
The container can be ping. The container can be ping on docker

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

podman version
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7

Built:      Tue Apr 19 10:16:32 2022
OS/Arch:    linux/amd64

**Output of `podman info`:**

host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.0-1.module+el8.6.0+14877+f643d2d6.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 87b7a9037cbd1d81288bdf2d6705dfda889f7cf9'
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "8.4"
  eventLogger: file
  hostname: n71-h200
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-305.49.1.el8_4.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 16866312192
  memTotal: 33445498880
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.0.0-74.rc95.module+el8.4.0+14908+81312c48.x86_64
    path: /usr/bin/runc
    version: |-
      runc version spec: 1.0.2-dev
      go: go1.15.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /etc/opt/veritas/flex/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.4.0+14908+81312c48.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 15813369856
  swapTotal: 16106123264
  uptime: 5h 35m 43.26s (Approximately 0.21 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
  - veritas
  - filevol
registries:
  console:8443:
    Blocked: false
    Insecure: false
    Location: console:8443
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: console:8443
  docker.io:
    Blocked: true
    Insecure: false
    Location: docker.io
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: docker.io
  registry.access.redhat.com:
    Blocked: true
    Insecure: false
    Location: registry.access.redhat.com
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: registry.access.redhat.com
  registry.redhat.io:
    Blocked: true
    Insecure: false
    Location: registry.redhat.io
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: registry.redhat.io
  search:
  - console:8443
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 10
    paused: 0
    running: 10
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /tmp
  imageStore:
    number: 11
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1650363392
  BuiltTime: Tue Apr 19 10:16:32 2022
  GitCommit: ""
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.2

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

podman-4.0.2-6.module+el8.6.0+14877+f643d2d6.x86_64

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
` networkBackend: cni`

Not Netavark, so our ability to help is somewhat limited. Any chance you can test with the Netavark backend?

**Comment by susanatgit** [comment]
Hi Mheon, no, we test using cni.

**Comment by mheon** [comment]
I suggest you open a bug against CNI, then, and provide them with your network's CNI config. If it's an issue with the config, we can investigate a fix to the `podman network create` code, but I somewhat doubt it is.

Going to close, but we can reopen if CNI indicates this is an issue with the config.

**Comment by susanatgit** [comment]
Hi mheon, thanks.

**Comment by susanatgit** [comment]
Hi @mheon , 
I noticed that the CNI project was Deprecated and the code logic has been merged into podman.
https://github.com/containers/podman-machine-cni

**Comment by mheon** [comment]
That project is specific to `podman machine` which runs Linux virtual machines to allow Podman to be used on OS X and Windows systems. It is not related to this at all - your problem is in the core CNI plugins, https://github.com/containernetworking/plugins. We did recently deprecate CNI in Podman in general, but we are not removing support for the foreseeable future, and as a whole this does not change the situation of this bug: the core cause is still in CNI, and the Podman team does not maintain CNI, so you need to contact the CNI maintainers for assistance. If you are on a RHEL system, you can open a support case for priority support.

**Comment by susanatgit** [comment]
Hi @mheon ,
I also verified using the netavark back networkend. It also cannot work. Should I file a new bug or reopen this one?
