### ISSUE TITLE
toolbox: failed to start container fedora-toolbox-RELEASEVER

### ISSUE THREAD

**Issue by discover02** [containers/podman#15262]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

toolbox: failed to start container fedora-toolbox-RELEASEVER

**Steps to reproduce the issue:**

1. Run `toolbox create` command and create a box.

2. And run the box `toolbox enter`

**Describe the results you received:**
toolbox says "failed to start container fedora-toolbox-37"

**Describe the results you expected:**
toolbox running smoothly

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.0-rc3
API Version:  4.2.0-rc3
Go Version:   go1.19
Built:        Fri Aug  5 22:53:26 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.27.0-dev
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.2-3.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.2, commit: '
  cpuUtilization:
    idlePercent: 95.65
    systemPercent: 1.05
    userPercent: 3.3
  cpus: 8
  distribution:
    distribution: fedora
    version: "37"
  eventLogger: journald
  hostname: "190502"
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.19.0-65.fc37.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 262184960
  memTotal: 8222171136
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-5.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 4292861952
  swapTotal: 4294959104
  uptime: 1h 9m 13.00s (Approximately 0.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/fedora/.config/containers/storage.conf
  containerStore:
    number: 9
    paused: 0
    running: 0
    stopped: 9
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/fedora/.local/share/containers/storage
  graphRootAllocated: 210224783360
  graphRootUsed: 96581644288
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /home/fedora/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0-rc3
  Built: 1659729206
  BuiltTime: Fri Aug  5 22:53:26 2022
  GitCommit: ""
  GoVersion: go1.19
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0-rc3
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-gvproxy-4.2.0~rc3-2.fc37.x86_64
podman-plugins-4.2.0~rc3-2.fc37.x86_64
podman-4.2.0~rc3-2.fc37.x86_64
podman-compose-1.0.3-6.fc37.noarch
podman-docker-4.2.0~rc3-2.fc37.noarch
podman-tests-4.2.0~rc3-2.fc37.x86_64
podman-remote-4.2.0~rc3-2.fc37.x86_64
podman-tui-0.5.0-3.fc37.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 37 Rawhide Prerelease

**Comment by discover02** [comment]
Addition: 

podman --log-level debug start fedora-toolbox-37
```
...
DEBU[0000] Created OCI spec for container 2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec at /home/fedora/.local/share/containers/storage/overlay-containers/2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec/userdata/config.json 
DEBU[0000] /usr/bin/conmon messages will be logged to syslog 
DEBU[0000] running conmon: /usr/bin/conmon               args="[--api-version 1 -c 2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec -u 2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec -r /usr/bin/crun -b /home/fedora/.local/share/containers/storage/overlay-containers/2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec/userdata -p /run/user/1000/containers/overlay-containers/2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec/userdata/pidfile -n fedora-toolbox-37 --exit-dir /run/user/1000/libpod/tmp/exits --full-attach -s -l journald --log-level debug --syslog --conmon-pidfile /run/user/1000/containers/overlay-containers/2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /home/fedora/.local/share/containers/storage --exit-command-arg --runroot --exit-command-arg /run/user/1000/containers --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /run/user/1000/libpod/tmp --exit-command-arg --network-config-dir --exit-command-arg  --exit-command-arg --network-backend --exit-command-arg netavark --exit-command-arg --volumepath --exit-command-arg /home/fedora/.local/share/containers/storage/volumes --exit-command-arg --runtime --exit-command-arg crun --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --events-backend --exit-command-arg journald --exit-command-arg --syslog --exit-command-arg container --exit-command-arg cleanup --exit-command-arg 2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec]"
[conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

DEBU[0000] Received: -1                                 
DEBU[0000] Cleaning up container 2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec 
DEBU[0000] Network is already cleaned up, skipping...   
DEBU[0000] Unmounted container "2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec" 
Error: OCI runtime error: unable to start container "2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec": crun: sd-bus call: Unit libpod-2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec.scope already exists.: File exists
```

**Comment by giuseppe** [comment]
it looks like there is already another unit with that name.

What is the output of `systemctl --user status libpod-2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec.scope`?

**Comment by discover02** [comment]
> systemctl --user status libpod-2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec.scope

```
× libpod-2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec.scope - libcrun container
     Loaded: loaded (/run/user/1000/systemd/transient/libpod-2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec.scope; transient)
  Transient: yes
     Active: failed (Result: resources)
        CPU: 0

Aug 10 10:19:38 190502 systemd[1639]: libpod-2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec.scope: Couldn't move process 28239 to requested cgroup '/user.slice/user-1000.slice/user@1000.service/user.slice/libpod-2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec.scope' (directly or via the system bus): Permission denied
Aug 10 10:19:38 190502 systemd[1639]: libpod-2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec.scope: Failed to add PIDs to scope's control group: Permission denied
Aug 10 10:19:38 190502 systemd[1639]: libpod-2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec.scope: Failed with result 'resources'.
Aug 10 10:19:38 190502 systemd[1639]: Failed to start libpod-2ce22b06eace2b0eb0f795b95f8f8a84c7e315c09ac4be2a5a703f0b468cd3ec.scope - libcrun container.
```

**Comment by giuseppe** [comment]
thanks, so systemd cannot move the new process to the target cgroup.

Can you show the output of `cat /proc/self/cgroup` and give it another try disabling temporarily SELinux with `setenforce 0` (after you test you can enable it again with `setenforce 1`)?

**Comment by discover02** [comment]
> thanks, so systemd cannot move the new process to the target cgroup.
> 
> Can you show the output of `cat /proc/self/cgroup` and give it another try disabling temporarily SELinux with `setenforce 0` (after you test you can enable it again with `setenforce 1`)?

```
❯ cat /proc/self/cgroup 
0::/user.slice/user-1000.slice/session-1.scope

❯ sudo setenforce 0
[sudo] password for fedora: 

❯ toolbox enter
Error: failed to start container fedora-toolbox-37

❯ sudo setenforce 1

❯ toolbox enter
Error: failed to start container fedora-toolbox-37
```

**Comment by giuseppe** [comment]
do you get the same error if you do `systemd-run --scope --user echo hello`?

Can you spot anything useful in the journal (`journalctl --user -e`)?

**Comment by discover02** [comment]
> ystemd-run --scope --user echo hello

```
Running scope as unit: run-rda084a86f67344608f20e44644c08160.scope
hello
```

```
Aug 10 11:56:11 190502 systemd[1639]: Started run-rda084a86f67344608f20e44644c08160.scope - /usr/bin/echo hello.
```

**Comment by discover02** [comment]
> do you get the same error if you do `systemd-run --scope --user echo hello`?
> 
> Can you spot anything useful in the journal (`journalctl --user -e`)?

```
Running scope as unit: run-rda084a86f67344608f20e44644c08160.scope
hello
```

```
Aug 10 11:56:11 190502 systemd[1639]: Started run-rda084a86f67344608f20e44644c08160.scope - /usr/bin/echo hello.
```

**Comment by giuseppe** [comment]
could you try `systemd-run --scope --user podman --log-level debug start fedora-toolbox-37`?

How have you configured your system?  It is a fresh installation of Rawhide?  Are you ssh'ing into it?

**Comment by discover02** [comment]
> systemd-run --scope --user podman --log-level debug start fedora-toolbox-37
Not work

> How have you configured your system? It is a fresh installation of Rawhide? Are you ssh'ing into it?
I upgraded system from f36

**Comment by giuseppe** [comment]
is the container freshly created or is it old?  Could you try recreating it?

Do other podman containers work fine?

I am not able to reproduce this issue on Rawhide.

Are you ssh'ing into the Rawhide machine or what environment are you using?

**Comment by discover02** [comment]
> is the container freshly created or is it old? Could you try recreating it?
 
Yes, I deleted the container and recreate it

> Do other podman containers work fine?

I tried to create a debian container with distrobox. The same problem existed there

> I am not able to reproduce this issue on Rawhide.

> Are you ssh'ing into the Rawhide machine or what environment are you using?

I'm using Fedora 37 on my own computer
```
OS : Fedora Linux 37 (Rawhide Prerelease) x86_64 
KR : 5.19.0-65.fc37.x86_64 
PK : 2015 (rpm), 54 (flatpak) 
SH : fish 3.5.0 
WM : sway 
TE : kitty 
MEM: 3210MiB / 7841MiB
```

**Comment by giuseppe** [comment]
I've tried to recreate your environment using sway+fish+kitty on Rawhide with the same kernel but still I cannot reproduce the issue

**Comment by discover02** [comment]
Interesting :thinking:

**Comment by discover02** [comment]
> I've tried to recreate your environment using sway+fish+kitty on Rawhide with the same kernel but still I cannot reproduce the issue

I installed Fedora 37 from scratch. But I got the same error. I suspect there is a missing package(s)

**Comment by giuseppe** [comment]
are the `dbus-broker.service` and `user@1000.service` service running correctly?

**Comment by discover02** [comment]
> are the `dbus-broker.service` and `user@1000.service` service running correctly?

![image](https://user-images.githubusercontent.com/62564400/184115700-ea842f2f-3058-41d9-a541-e5e4c952e672.png)

**Comment by giuseppe** [comment]
I've installed Rawhide again from scratch and I am still not able to see the issue you've reported, so it must be some different configuration or missing package.

Can you reproduce on a standard Fedora installation?

**Comment by discover02** [comment]
> Can you reproduce on a standard Fedora installation?

I didn't understand

**Comment by giuseppe** [comment]
sway+fish+kitty are not part of the default installation

**Comment by discover02** [comment]
I did a normal installation inside the virtual machine and did not encounter any problems.

**Comment by discover02** [comment]
@giuseppe 

We messed with @onuralpszr and found that the problem was with the toolbox. Toolbox goes to wrong dbus address and throws an error. When you define the address manually with the `DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus` variable, the problem disappears. We will need to report this issue under the containers/toolbox project

**Comment by onuralpszr** [comment]
Well, I didn't call "messed" preferably saying "worked" would be better choice plus you have to say that your system is "fedora everything installation" so some of your config yours was not there I don't know that variable should be exist under normal installation of podman or toolbox but closing without proper discussion not a good idea as well.
