### ISSUE TITLE
SELinux broken on aarch64

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#15280]
Another bug found in #14801 (enable aarch64 in CI) but rush-skipped without filing an appropriate issue. [log](https://api.cirrus-ci.com/v1/artifact/task/5555887191359488/html/sys-podman-fedora-36%20%7Baarch64%7D-root-host.log.html#t--00316).

Symptom: lots of these:
```
# #|     FAIL: SELinux type
# #| expected: 'spc_t'
# #|   actual: 'cloud_init_t'
```

**Comment by edsantiago** [comment]
@cevich this could be related to the stuff you've been seeing. (It could also be fixed now with your changes. No way to tell unless someone un-skips the tests).

**Comment by cevich** [comment]
> could be related to the stuff you've been seeing

Yes!  And good catch.  That fix went into the images with ID `c5473162832904192`.  So should be a (hopefully) simple un-skip and image-update fix.

**Comment by edsantiago** [comment]
...but we can't vendor-dance until #15025 is fixed. Switching conversation there.

**Comment by edsantiago** [comment]
Fixed by the Code Fairy. Tests reenabled in #15894.
