### ISSUE TITLE
4.2.0 cannot be built on Ubuntu Focal or Debian Buster

### ISSUE THREAD

**Issue by hoshsadiq** [containers/podman#15293]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Hello, I'm trying to build Podman against Debian Buster (still supported until 2024) and Ubuntu Focal (LTS release; supported until 2025). It seems to be because [v0.1.3](https://github.com/containers/podman/commit/f67ab1eb20ae357fd004815ec25c5350e5813a46#diff-3295df7234525439d778f1b282d146a4f1ff6b415248aaac074e8042d9f42d63L1112-L1114) was recently included (note: it comes from containers/image). 

```
$ make 'BUILDTAGS=seccomp apparmor systemd'
CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build \
	\
	-ldflags '-X github.com/containers/podman/v4/libpod/define.gitCommit=7fe5a419cfd2880df2028ad3d7fd9378a88a04f4 -X github.com/containers/podman/v4/libpod/define.buildInfo=1660244506 -X github.com/containers/podman/v4/libpod/config._installPrefix=/usr/local -X github.com/containers/podman/v4/libpod/config._etcDir=/usr/local/etc -X github.com/containers/common/pkg/config.additionalHelperBinariesDir= ' \
	-tags "seccomp apparmor systemd" \
	-o bin/podman ./cmd/podman
# pkg-config --cflags  -- gpgme
Package gpgme was not found in the pkg-config search path.
Perhaps you should add the directory containing `gpgme.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gpgme' found
pkg-config: exit status 1
```

**Steps to reproduce the issue:**
All the sources are available in https://github.com/hoshsadiq/podman-deb/tree/a4bb3480bcc59a752e2bedd4e9f91e70d3ae3728.
Debian 10 example:
```
$ git clone https://github.com/hoshsadiq/podman-deb /tmp/podman-deb
$ cd /tmp/podman-deb
$ git checkout a4bb3480bcc59a752e2bedd4e9f91e70d3ae3728
$ podman build -t podman-builder:debian_10 -f ./podman/Dockerfile.debian_10 .
$ podman run --env=APP_VERSION=4.2.0 --env=APP_NAME=podman -v "$PWD:/repo" -i podman-builder:debian_10 bash < podman/build.sh
```
Example run is available in the repo: https://github.com/hoshsadiq/podman-deb/runs/7780994059?check_suite_focus=true.

**Describe the results you received:**
Error:
```
Package gpgme was not found in the pkg-config search path.
Perhaps you should add the directory containing `gpgme.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gpgme' found
```

**Describe the results you expected:**
Binary built

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Output of `podman version`:**

```
4.2.0
```

**Output of `podman info`:**

N/A

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**
N/A

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

N/A

**Comment by hoshsadiq** [comment]
Related: https://github.com/proglottis/gpgme/issues/6

**Comment by flouthoc** [comment]
Hi @hoshsadiq ,

Is gpgme not present on the distro or it the old one ? Could you try installing `libgpgme-dev` ?

**Comment by hoshsadiq** [comment]
The issue is that it's an older version that https://github.com/proglottis/gpgme doesn't accept. I'd already installed it.

Either way, I've archived my repo where I needed this, as I ended up using @lsm5's unstable repos. I'll leave this open in case you want to address this issue. If not, feel free to close it!

**Comment by flouthoc** [comment]
Thanks Closing this, feel free to reopen.

**Comment by ErwinP** [comment]
For everybody building on a rapsberry pi 3, you can get over this by adding the build tag `containers_image_openpgp`, as indicated [here](https://github.com/containers/podman/issues/13281#issuecomment-1046700578). Note that "_creating signatures for images is not supported with this tag_".

**Comment by lsm5** [comment]
FYI for debian buster users looking for v4.2.0 on Debian Buster. AFAIK, currently you can install packages from the debian experimental repo.

RE: the kubic `unstable` repo, debian buster build for podman v4.2.0 is currently waiting on a build environment refresh to account for new distro repo paths which are currently blocking golang-1.16 from being installed. I'm checking on that with the OBS admins.

**Comment by StarpTech** [comment]
Any updates about how we can install 4.2 on Ubuntu? Thanks in advance.
