### ISSUE TITLE
Unclear defaults for `--exit-policy`

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#15297]
The release notes for 4.2 contain:

> - Pods now have include an exit policy (configurable via the `--exit-policy` option to `podman pod create`), which determines what will happen to the pod's infra container when the entire pod stops. The default, `continue`, acts as Podman currently does, while a new option, `stop`, stops the infra container after the last container in the pod stops, and is used by default for pods from `podman play kube` ([#13464](https://github.com/containers/podman/issues/13464)).

`Pods now have include an exit policy, which …` does not sound good.

> The default, `continue`, acts as Podman currently does, while a new option, `stop`, stops the infra container after the last container in the pod stops, and is used by default for pods from `podman play kube`

It is unclear what the default is. “…acts as Podman currently does” means the default is always “continue”.

source/markdown/podman-pod-create.1.md  does not make it clearer, either.  Unclear is for instance, if --exit-policy=continue can be used by `kube play`.

**Comment by rhatdan** [comment]
podman kube play will shut down the infra structure container when it exits, as I understand it.

Only podman pod ... is effected by this change.  Currently infra container continues running with --exit-policy=continue, but this can be changed with --exit-policy=stop or by modifying the containers.conf.  Personally if we had to do it all over again, the default should be ==stop, and this might change with podman 5.0.

**Comment by dilyanpalauzov** [comment]
After reading https://github.com/containers/podman/issues/13464 I do not think that the `--exit-policy` flag is described correctly.

In docs/source/markdown/podman-pod-create.1.md.in the behaviour of the pod is described, without referencing the infra-container (pause).  While the behaviour of the pod, once all its containers are terminated, might be the same as the behaviour of the infra container (pause), I think this shall be spelled more explicitly.

The RELEASE_NOTES is more explicit on `--exit-policy` as it mentions explicitly on the infra container.

You might want to extend docs/source/markdown/podman-pod-create.1.md.in by a use-case, when does `--exit-policy=continue` make sense.

>  The default, continue, acts as Podman currently does, while a new option, stop, stops the infra container after the last container in the pod stops, and is used by default for pods from podman play kube

should be

>  The default for `pod create`, continue, acts as what Podman currently does: keeps the infra container running).  A new option, stop, stops the infra container after the last container in the pod stops.  `play kube` does stop the infra container, when all other containers terminate.

**Comment by mheon** [comment]
Yeah, I can definitely see the potential for confusion in the manpages. Want to open a PR to update the text?
