### ISSUE TITLE
"podman images list" doesn't behave as documented

### ISSUE THREAD

**Issue by goeranu** [containers/podman#15309]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The manual page for `podman-images` lists the three forms `podman images`, `podman images list`, and `podman images ls`. Nothing in the text mentions the three forms, so the impression one gets is they are equivalent.

However, `podman images` takes any additional non-option argument as an image name. Only images with this tag are listed, and the `list` argument is treated as a tag name. Similarly for `ls`. Nothing in the manual page mentions the option of adding a tag name.

**Steps to reproduce the issue:**

1. `podman images list`

**Describe the results you received:**
A list of all images tagged _list_. (Normally none, except when testing the feature.)

**Describe the results you expected:**
Based on the manual page I would have expected the same output as from `podman images`. The actual behaviour is probably better though, so I would suggest just updating the manual page.

**Additional information you deem important (e.g. issue happens only occasionally):**
`podman images --help` gives correct information.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.4
Built:        Fri Jul 22 21:05:59 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpuUtilization:
    idlePercent: 99.41
    systemPercent: 0.22
    userPercent: 0.38
  cpus: 12
  distribution:
    distribution: fedora
    version: "36"
  eventLogger: journald
  hostname: mimmi
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1003
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1003
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.18.11-200.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 549335040
  memTotal: 33507659776
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.4-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.4
      commit: 6521fcc5806f20f6187eb933f9f45130c86da230
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1003/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-4.dev.giteecccdb.fc33.x86_64
    version: |-
      slirp4netns version 1.1.4+dev
      commit: eecccdb96f587b11d7764556ffacfeaffe4b6e11
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 34330984448
  swapTotal: 34359730176
  uptime: 302h 42m 31.6s (Approximately 12.58 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/göran/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.2.0-1.fc33.x86_64
      Version: |-
        fusermount3 version: 3.9.3
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.3
        using FUSE kernel interface version 7.31
  graphRoot: /var/tmp/testkatalog/containers/storage
  graphRootAllocated: 1796514123776
  graphRootUsed: 1421136625664
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 5
  runRoot: /run/user/1003
  volumePath: /var/tmp/testkatalog/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1658516759
  BuiltTime: Fri Jul 22 21:05:59 2022
  GitCommit: ""
  GoVersion: go1.18.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.1.1-3.fc36.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Sort of, I checked the [source](https://github.com/containers/podman/blob/main/docs/source/markdown/podman-images.1.md) and the problem is still there.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
The command you are looking for is ‘podman image ls’ - not images, image.
You are calling the ‘podman images’ command with an optional argument as
written.

**Comment by goeranu** [comment]
Right! The manual page actually says `podman image list`. Tricky to document `podman image` on the manual page for `podman images`; it clearly fooled me.

It is still the case though that the manual page does not document the optional argument of the `podman images` command. That part of this report remains valid.

**Comment by mheon** [comment]
I'm going to tag as documentation given that this is mainly a manpage issue
