### ISSUE TITLE
podman stop work after user ID change

### ISSUE THREAD

**Issue by lededev** [containers/podman#15310]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

After change user ID and group ID from 1001 to 1000, podman stop working.

**Steps to reproduce the issue:**

1. change user ID from 1001 to 1000 in /etc/passwd
2. change group ID from 1001 to 1000 in /etc/group
3. chown 1000:1000 -R /home/user
4. reboot
5. `echo $UID` return `1000`
6. run command `podman info`

**Describe the results you received:**
```
podman info --debug
Error: error creating tmpdir: mkdir /run/user/1001: permission denied
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version
Error: error creating tmpdir: mkdir /run/user/1001: permission denied
```

**Output of `podman info`:**

```
podman info
Error: error creating tmpdir: mkdir /run/user/1001: permission denied
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
apt list podman
Listing... Done
podman/jammy,now 3.4.4+ds1-1ubuntu1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by lededev** [comment]
Similar issues I searched for were flagged as not being fixed, so I'll just have to find another way.

**Comment by rhatdan** [comment]
You will need to do `podman system reset` to reinitialize your containers/storage.

**Comment by lededev** [comment]
No, I don't do this because I don't want to lose my data.
Just change UID back is enough, although I still have the needs of changing UID, I will find another way, Thanks.

**Comment by rapenne-s** [comment]
Could we reopen this issue? I have the exact same problem. My user is uid 1003, I installed podman and I get the follow error when trying a podman command

```
Error: error creating tmpdir: mkdir /run/user/1000: permission denied
```

I tried `podman system reset` as root, but didn't solve the problem.

**Comment by rhatdan** [comment]
You do not have a full user session and/or have XDG_RUNTIME_DIR pointing at that path.

Could you log out and log in via ssh or via a full login.

**Comment by mihalyr** [comment]
Did anyone find a fix for this? I have the exact same problem, `podman system reset` didn't work either. More details in https://ask.fedoraproject.org/t/changing-user-uid-gid-broke-toolbox-podman-on-fedora-37-silverblue/30410

**Comment by mihalyr** [comment]
Oh, just had to look a little bit further here is the full solution

### The problem

```plain
➜  ~ id
uid=1985(mihalyr) gid=1985(mihalyr) groups=1985(mihalyr),10(wheel) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
➜  ~ toolbox enter
Error: failed to get the Podman version
➜  ~ podman version
Error: creating tmpdir: mkdir /run/user/1000: permission denied
```

### System reset (Silverblue)

```
➜  ~ podman system reset
Error: creating tmpdir: mkdir /run/user/1000: permission denied
➜  ~ sudo podman system reset
[sudo] password for mihalyr: 
WARNING! This will remove:
        - all containers
        - all pods
        - all images
        - all networks
        - all build cache
        - all machines
        - all volumes
Are you sure you want to continue? [y/N] y
A storage.conf file exists at /usr/share/containers/storage.conf
You should remove this file if you did not modify the configuration.
```

### System reset (Silverblue) again

```
➜  ~ sudo rpm-ostree usroverlay
Development mode enabled.  A writable overlayfs is now mounted on /usr.
All changes there will be discarded on reboot.
➜  ~ rm /usr/share/containers/storage.conf
rm: remove write-protected regular file '/usr/share/containers/storage.conf'? y
rm: cannot remove '/usr/share/containers/storage.conf': Permission denied
➜  ~ sudo rm /usr/share/containers/storage.conf
➜  ~ sudo podman system reset
WARNING! This will remove:
        - all containers
        - all pods
        - all images
        - all networks
        - all build cache
        - all machines
        - all volumes
Are you sure you want to continue? [y/N] y
➜  ~ podman version
ERRO[0000] User-selected graph driver "vfs" overwritten by graph driver "overlay" from database - delete libpod local files to resolve.  May prevent use of images created by other tools 
Error: creating tmpdir: mkdir /run/user/1000: permission denied
````

### Delete local containers

```shell
sudo rm -rf ~/.local/share/containers/
```

I missed this last bit. When `podman version` returned "delete libpod local files to resolve" after the "system reset", I found this issue that had what I was looking for https://github.com/containers/podman/issues/5114#issuecomment-779406347
