### ISSUE TITLE
Hard Crashes on M1 Mac when running "podman machine start"

### ISSUE THREAD

**Issue by evoio** [containers/podman#15329]
/kind bug

**Description**

When I run "podman machine start" with default settings on my M1 Mac it hard crashes the whole system. It has done this every time I have attempted to start the VM.

**Steps to reproduce the issue:**

1. Installed via Brew

2. Run "podman machine init"

3. Run "podman machine start"

**Describe the results you received:**

Host machine hard crashes. Report below:

panic(cpu 3 caller 0xfffffe00253c1814): vm_fault() KERN_FAILURE from guest fault on state 0xfffffe600c36c000 @sleh.c:3117
Debugger message: panic
Memory ID: 0x6
OS release type: User
OS version: 21E258
Kernel version: Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000
Fileset Kernelcache UUID: 0631AF68D2B8D6FEA30E36D7895D4DB4
Kernel UUID: C342869F-FFB9-3CCE-A5A3-EA711C1E87F6
iBoot version: iBoot-7459.101.3
secure boot?: YES
Paniclog version: 13
KernelCache slide: 0x000000001d994000
KernelCache base:  0xfffffe0024998000
Kernel slide:      0x000000001e144000
Kernel text base:  0xfffffe0025148000
Kernel text exec slide: 0x000000001e22c000
Kernel text exec base:  0xfffffe0025230000
mach_absolute_time: 0x14fc057e8
Epoch Time:        sec       usec
  Boot    : 0x62fa6f0e 0x000e0301
  Sleep   : 0x00000000 0x00000000
  Wake    : 0x00000000 0x00000000
  Calendar: 0x62fa6ff2 0x000e5302

Zone info:
  Foreign : 0xfffffe002dc10000 - 0xfffffe002dc20000
  Native  : 0xfffffe1000248000 - 0xfffffe3000248000
  Readonly: 0xfffffe14ccf14000 - 0xfffffe16668ac000
  Metadata: 0xfffffe6ac00e0000 - 0xfffffe6acc02c000
  Bitmaps : 0xfffffe6acc02c000 - 0xfffffe6ad1a94000

CORE 0 PVH locks held: None
CORE 1 PVH locks held: None
CORE 2 PVH locks held: None
CORE 3 PVH locks held: None
CORE 4 PVH locks held: None
CORE 5 PVH locks held: None
CORE 6 PVH locks held: None
CORE 7 PVH locks held: None
CORE 8 PVH locks held: None
CORE 9 PVH locks held: None
CORE 0: PC=0xfffffe002529fae4, LR=0xfffffe002532fa44, FP=0xfffffe60b72cba10
CORE 1: PC=0x00000001b3576748, LR=0x00000001b35d4eb0, FP=0x000000016f3b2010
CORE 2: PC=0xfffffe00252bf41c, LR=0xfffffe00252bf418, FP=0xfffffe6017bb3f00
CORE 3 is the one that panicked. Check the full backtrace for details.
CORE 4: PC=0xfffffe00252bf41c, LR=0xfffffe00252bf418, FP=0xfffffe600c3cbf00
CORE 5: PC=0xfffffe00252bf418, LR=0xfffffe00252bf418, FP=0xfffffe600c45bf00
CORE 6: PC=0xfffffe00252bf41c, LR=0xfffffe00252bf418, FP=0xfffffe60b738bf00
CORE 7: PC=0xfffffe00252bf418, LR=0xfffffe00252bf418, FP=0xfffffe60ba1ebf00
CORE 8: PC=0xfffffe00252bf418, LR=0xfffffe00252bf418, FP=0xfffffe600c433f00
CORE 9: PC=0xfffffe00252bf418, LR=0xfffffe00252bf418, FP=0xfffffe60a245bf00
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Panicked task 0xfffffe24cef50000: 21003 pages, 7 threads: pid 1304: qemu-system-aarc
Panicked thread: 0xfffffe1b30e90968, backtrace: 0xfffffe600c5fb310, tid: 11647
		  lr: 0xfffffe0025289560  fp: 0xfffffe600c5fb380
		  lr: 0xfffffe0025289228  fp: 0xfffffe600c5fb3f0
		  lr: 0xfffffe00253cdecc  fp: 0xfffffe600c5fb410
		  lr: 0xfffffe00253c005c  fp: 0xfffffe600c5fb480
		  lr: 0xfffffe00253bda98  fp: 0xfffffe600c5fb540
		  lr: 0xfffffe00252377f8  fp: 0xfffffe600c5fb550
		  lr: 0xfffffe0025288eac  fp: 0xfffffe600c5fb8f0
		  lr: 0xfffffe0025288eac  fp: 0xfffffe600c5fb960
		  lr: 0xfffffe0025ab2acc  fp: 0xfffffe600c5fb980
		  lr: 0xfffffe00253c1814  fp: 0xfffffe600c5fb9e0
		  lr: 0xfffffe00253c13b0  fp: 0xfffffe600c5fba50
		  lr: 0xfffffe0025242828  fp: 0xfffffe600c5fba60
		  lr: 0xfffffe00253d61c0  fp: 0xfffffe600c5fbe50
		  lr: 0xfffffe00253bdea8  fp: 0xfffffe600c5fbf10
		  lr: 0xfffffe00252377f8  fp: 0xfffffe600c5fbf20

last started kext at 1738067199: com.apple.driver.driverkit.serial	6.0.0 (addr 0xfffffe0025023320, size 3416)
loaded kexts:
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleTopCaseHIDEventDriver	5440.11
com.apple.driver.AppleBiometricServices	1
com.apple.driver.CoreKDL	1
com.apple.driver.DiskImages.ReadWriteDiskImage	493.0.0
com.apple.driver.DiskImages.UDIFDiskImage	493.0.0
com.apple.driver.DiskImages.RAMBackingStore	493.0.0
com.apple.driver.DiskImages.FileBackingStore	493.0.0
com.apple.driver.SEPHibernation	1
com.apple.driver.BCMWLANFirmware4387.Hashstore	1
com.apple.driver.AppleUSBDeviceNCM	5.0.0
com.apple.driver.AppleThunderboltIP	4.0.3
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.nke.l2tp	1.9
com.apple.filesystems.tmpfs	1
com.apple.filesystems.lifs	1
com.apple.filesystems.apfs	1934.101.3
com.apple.IOTextEncryptionFamily	1.0.0
com.apple.filesystems.hfs.kext	583.100.10
com.apple.driver.AppleCS42L84Audio	540.34
com.apple.security.BootPolicy	1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleEmbeddedSimpleSPINORFlasher	1
com.apple.driver.ApplePMP	1
com.apple.driver.AppleSmartIO2	1
com.apple.driver.AppleSN012776Amp	540.34
com.apple.driver.AppleT6000SOCTuner	1
com.apple.driver.AppleT6000CLPCv3	1
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleALSColorSensor	1.0.0d1
com.apple.driver.AppleAOPVoiceTrigger	140.1
com.apple.driver.AppleDPDisplayTCON	1
com.apple.driver.ApplePMPFirmware	1
com.apple.driver.usb.AppleSynopsysUSB40XHCI	1
com.apple.AGXG13X	190.17.3
com.apple.driver.AppleSamsungSerial	1.0.0d1
com.apple.driver.AppleSDXC	3.2.1
com.apple.driver.AppleMCDP29XXUpdateSupport	1
com.apple.driver.AppleSerialShim	1
com.apple.driver.AppleS5L8960XNCO	1
com.apple.driver.AppleAVD	560
com.apple.driver.AppleAVE2	540.44.5
com.apple.driver.AppleEventLogHandler	1
com.apple.driver.AppleProResHW	175.4.0
com.apple.driver.AppleJPEGDriver	4.8.1
com.apple.driver.AppleM68Buttons	1.0.0d1
com.apple.driver.AppleSPMIPMU	1.0.1
com.apple.driver.AppleMobileDispT600X-DCP	140.0
com.apple.driver.AppleT6000PMGR	1
com.apple.driver.AppleS8000AES	1
com.apple.driver.AppleS8000DWI	1.0.0d1
com.apple.driver.AppleInterruptControllerV2	1.0.0d1
com.apple.driver.AppleT8110DART	1
com.apple.driver.AppleBluetoothModule	1
com.apple.driver.AppleBCMWLANBusInterfacePCIe	1
com.apple.driver.AppleS5L8920XPWM	1.0.0d1
com.apple.driver.AudioDMAController-T600x	140.4
com.apple.driver.AppleT6000DART	1
com.apple.driver.AppleSPIMC	1
com.apple.driver.AppleS5L8940XI2C	1.0.0d2
com.apple.driver.AppleT6000	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.usb.AppleUSBUserHCI	1
com.apple.iokit.IOKitRegistryCompatibility	1
com.apple.iokit.EndpointSecurity	1
com.apple.driver.AppleDiskImages2	126.100.13
com.apple.AppleSystemPolicy	2.0.0
com.apple.nke.applicationfirewall	402
com.apple.kec.InvalidateHmac	1
com.apple.kec.AppleEncryptedArchive	1
com.apple.driver.driverkit.serial	6.0.0
com.apple.kext.triggers	1.0
com.apple.iokit.IOAVBFamily	1040.6
com.apple.plugin.IOgPTPPlugin	1040.3
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.driver.AppleHIDKeyboard	228.1
com.apple.driver.AppleActuatorDriver	5440.11
com.apple.driver.AppleMultitouchDriver	5440.11
com.apple.driver.AppleHSBluetoothDriver	5440.11
com.apple.driver.IOBluetoothHIDDriver	9.0.0
com.apple.driver.AppleMesaSEPDriver	100.99
com.apple.iokit.IOBiometricFamily	1
com.apple.driver.DiskImages.KernelBacked	493.0.0
com.apple.driver.AppleTrustedAccessory	1
com.apple.iokit.AppleSEPGenericTransfer	1
com.apple.driver.AppleSEPHDCPManager	1.0.1
com.apple.driver.AppleXsanScheme	3
com.apple.driver.usb.networking	5.0.0
com.apple.driver.AppleThunderboltUSBDownAdapter	1.0.4
com.apple.driver.AppleThunderboltPCIDownAdapter	4.1.1
com.apple.driver.AppleThunderboltDPInAdapter	8.5.1
com.apple.driver.AppleThunderboltDPAdapterFamily	8.5.1
com.apple.nke.ppp	1.9
com.apple.driver.AppleHIDTransportSPI	5440.6
com.apple.driver.AppleHIDTransport	5440.6
com.apple.driver.AppleInputDeviceSupport	5440.6
com.apple.driver.AppleBSDKextStarter	3
com.apple.driver.AppleConvergedIPCOLYBTControl	1
com.apple.driver.AppleConvergedPCI	1
com.apple.driver.AppleBluetoothDebug	1
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleCSEmbeddedAudio	540.34
com.apple.driver.AppleDCPDPTXProxy	1.0.0
com.apple.driver.DCPDPFamilyProxy	1
com.apple.driver.AppleDiagnosticDataAccessReadOnly	1.0.0
com.apple.driver.AppleBTM	1.0.1
com.apple.driver.ApplePassthroughPPM	3.0
com.apple.driver.AppleAOPAudio	140.3
com.apple.driver.AppleEmbeddedAudio	540.34
com.apple.iokit.AppleARMIISAudio	140.2
com.apple.driver.AppleSPU	1
com.apple.driver.DCPAVFamilyProxy	1
com.apple.driver.AppleUSBXDCIARM	1.0
com.apple.driver.AppleUSBXDCI	1.0
com.apple.iokit.IOUSBDeviceFamily	2.0.0
com.apple.driver.usb.AppleSynopsysUSBXHCI	1
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.AppleEmbeddedUSBHost	1
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.AGXFirmwareKextG13XRTBuddy	190.17.3
com.apple.AGXFirmwareKextRTBuddy64	190.17.3
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.AppleNANDConfigAccess	1.0.0
com.apple.driver.AppleSART	1
com.apple.iokit.IOGPUFamily	35.29
com.apple.driver.AppleHPM	3.4.4
com.apple.driver.AppleT6000TypeCPhy	1
com.apple.driver.AppleT8103TypeCPhy	1
com.apple.driver.AppleDialogPMU	1.0.1
com.apple.driver.AppleStockholmControl	1.0.0
com.apple.driver.AppleSPMI	1.0.1
com.apple.iokit.IOMobileGraphicsFamily-DCP	343.0.0
com.apple.driver.AppleDCP	1
com.apple.driver.AppleFirmwareKit	1
com.apple.iokit.IOMobileGraphicsFamily	343.0.0
com.apple.driver.ApplePMGR	1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.driver.AppleARMWatchdogTimer	1
com.apple.driver.AppleDisplayCrossbar	1.0.0
com.apple.iokit.IODisplayPortFamily	1.0.0
com.apple.driver.AppleTypeCPhy	1
com.apple.driver.AppleThunderboltNHI	7.2.81
com.apple.driver.AppleT6000PCIeC	1
com.apple.iokit.IOThunderboltFamily	9.3.3
com.apple.driver.ApplePIODMA	1
com.apple.driver.AppleT600xPCIe	1
com.apple.driver.AppleMultiFunctionManager	1
com.apple.driver.AppleBluetoothDebugService	1
com.apple.driver.AppleBCMWLANCore	1.0.0
com.apple.iokit.IO80211Family	1200.12.2b1
com.apple.driver.IOImageLoader	1.0.0
com.apple.driver.AppleOLYHAL	1
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleEmbeddedPCIE	1
com.apple.driver.AppleMCA2-T600x	640.5
com.apple.driver.AppleEmbeddedAudioLibs	140.1
com.apple.driver.AppleFirmwareUpdateKext	1
com.apple.driver.AppleH13CameraInterface	6.44.0
com.apple.driver.AppleH10PearlCameraInterface	17.0.6
com.apple.driver.AppleGPIOICController	1.0.2
com.apple.driver.AppleFireStormErrorHandler	1
com.apple.driver.AppleMobileApNonce	1
com.apple.iokit.IOTimeSyncFamily	1040.3
com.apple.driver.DiskImages	493.0.0
com.apple.iokit.IOGraphicsFamily	594
com.apple.iokit.IOBluetoothSerialManager	9.0.0
com.apple.iokit.IOBluetoothHostControllerUSBTransport	9.0.0
com.apple.iokit.IOBluetoothHostControllerUARTTransport	9.0.0
com.apple.iokit.IOBluetoothHostControllerTransport	9.0.0
com.apple.driver.IOBluetoothHostControllerPCIeTransport	9.0.0
com.apple.iokit.IOBluetoothFamily	9.0.0
com.apple.driver.FairPlayIOKit	68.16.0
com.apple.iokit.CSRBluetoothHostControllerUSBTransport	9.0.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	9.0.0
com.apple.driver.AppleSSE	1.0
com.apple.driver.AppleSEPKeyStore	2
com.apple.driver.AppleUSBTDM	533.100.11
com.apple.iokit.IOUSBMassStorageDriver	210.101.2
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOSCSIBlockCommandsDevice	456.100.7
com.apple.iokit.IOSCSIArchitectureModelFamily	456.100.7
com.apple.driver.AppleIPAppender	1.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.RTBuddy	1.0.0
com.apple.driver.AppleEmbeddedTempSensor	1.0.0
com.apple.driver.AppleARMPMU	1.0
com.apple.iokit.IOAccessoryManager	1.0.0
com.apple.driver.AppleOnboardSerial	1.0
com.apple.iokit.IOSkywalkFamily	1.0
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.4
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.AppleA7IOP	1.0.2
com.apple.driver.IOSlaveProcessor	1
com.apple.driver.AppleBiometricSensor	2
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.CoreAnalyticsFamily	1
com.apple.driver.AppleANELoadBalancer	5.64.2
com.apple.driver.AppleH11ANEInterface	5.64.2
com.apple.AUC	1.0
com.apple.iokit.IOAVFamily	1.0.0
com.apple.iokit.IOHDCPFamily	1.0.0
com.apple.iokit.IOCECFamily	1
com.apple.iokit.IOAudio2Family	1.0
com.apple.driver.AppleIISController	140.1
com.apple.driver.AppleAudioClockLibs	140.1
com.apple.driver.AppleM2ScalerCSCDriver	265.0.0
com.apple.iokit.IOSurface	302.14
com.apple.driver.IODARTFamily	1
com.apple.security.quarantine	4
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.security.AppleImage4	4.2.0
com.apple.kext.CoreTrust	1
com.apple.iokit.IOCryptoAcceleratorFamily	1.0.1
com.apple.driver.AppleARMPlatform	1.0.2
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOReportFamily	47
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	12.0

** Stackshot Succeeded ** Bytes Traced 349538 (Uncompressed 887072) **

**Describe the results you expected:**

Podman VM starts and I can begin using it.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: connection to bastion host (ssh://core@localhost:49329/run/user/501/podman/podman.sock) failed: dial tcp [::1]:49329: connect: connection refused
```

**Output of `podman info`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: connection to bastion host (ssh://core@localhost:49329/run/user/501/podman/podman.sock) failed: dial tcp [::1]:49329: connect: connection refused
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman: stable 4.2.0 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/opt/homebrew/Cellar/podman/4.2.0 (178 files, 48MB) *
  Poured from bottle on 2022-08-15 at 17:17:02
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0
==> Dependencies
Build: go-md2man ✘, go@1.18 ✘
Required: qemu ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Analytics
install: 17,466 (30 days), 55,324 (90 days), 187,205 (365 days)
install-on-request: 17,254 (30 days), 54,778 (90 days), 186,617 (365 days)
build-error: 47 (30 days)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Comment by mheon** [comment]
@baude @ashley-cui PTAL

**Comment by ashley-cui** [comment]
What version of MacOS and what Mac model do you have?

**Comment by evoio** [comment]
I'm on Monterey 12.3.1.

Its a 14" Macbook Pro 2021 with a M1 Pro.

**Comment by evoio** [comment]
In checking what version I'm on I noticed that there was a newer version. Bumped to 12.5 and its working now.

**Comment by rhatdan** [comment]
Yes qemu and mac 12.3.1 did not work together.
