### ISSUE TITLE
Mechanism to change WSL dns when vpn enabled

### ISSUE THREAD

**Issue by benoitf** [containers/podman#15344]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

This feature has been asked on [Podman Desktop side](https://github.com/containers/podman-desktop/issues/401), here is a transcript:

> DNS resolution error when pulling images with vpn enabled.

> My company requires and enforces a VPN on company hardware. The /etc/resolv.conf in the Podman machine vm that is created by Podman Desktop is initialized with the dns of the host and not the VPN. Tom Sweeny had a great post about getting Podman up and running in WSL and following his post i was able to edit the /etc/resolv.conf nameserver in WSL with the dns of the vpn.

> I know this may be an edge case, but it would be tremendously helpful to have an option in podman desktop to set the nameserver in the /etc/resolv.conf of the podman machine.

**Describe the results you received:**
DNS used = vpn DNS

**Describe the results you expected:**
DNS used = dns of the host

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@n1hility PTAL

**Comment by n1hility** [comment]
This issue has been superseded by the user-mode-networking feature, which will provide a more complete solution (connectivity to services behind the VPN will also work). We could always reopen this if for some reason user-mode is too much.
