### ISSUE TITLE
--amend emulations is missing from the "manifest create" cmd

### ISSUE THREAD

**Issue by snir911** [containers/podman#15346]
Using the `podman-docker` emulation is failing to emulate the following cmd: `docker manifest create <registry>:<tag> --amend <registry>:<tag2>` complain about missing the `--amend` option

what would be the podman way to do this?

(Tested with podman-docker 3.4.7-2 on fedora 35)

**Comment by mheon** [comment]
3.4.7 is a little outdated, can you try with 4.2?

**Comment by rhatdan** [comment]
Looks like --amend is not available in 4.2

$ podman manifest create --help
Create manifest list or image index

Description:
  Creates manifest lists or image indexes.

Usage:
  podman manifest create [options] LIST [IMAGE...]

Examples:
  podman manifest create mylist:v1.11
  podman manifest create mylist:v1.11 arch-specific-image-to-add
  podman manifest create mylist:v1.11 arch-specific-image-to-add another-arch-specific-image-to-add
  podman manifest create --all mylist:v1.11 transport:tagged-image-to-add

Options:
      --all   add all of the lists' images if the images to add are lists

**Comment by rhatdan** [comment]
Docker has
  -a, --amend      Amend an existing manifest list
      --insecure   Allow communication with an insecure registry

**Comment by rhatdan** [comment]
@nalind PTAL
