### ISSUE TITLE
Cirrus: enable F37 testing

### ISSUE THREAD

**Issue by lsm5** [containers/podman#15349]
Fedora 37 has been branched from rawhide. It's best we enable f37 testing way ahead of release so we're not caught off-guard close to release date.

/cc @rhatdan @cevich @edsantiago @baude @mheon

**Comment by rhatdan** [comment]
Agreed, we turned off testing on f35.  F36 should be made previous.  F37 should be made current.

**Comment by lsm5** [comment]
one possible pain-point could be google cloud's availability of f37. Might need some gymnastics with f36 + dnf distro-sync to f37.

**Comment by cevich** [comment]
>  google cloud's availability of f37

Google shouldn't be a problem.  The base-image build-workflow is specifically arranged to work around this.  All we need is [the generic cloud-image QCOW file at a URL.](https://github.com/containers/automation_images/blob/main/base_images/cloud.yml#L36-L37).

AWS is another story, have AMI's been published yet for F37?

**Comment by cevich** [comment]
> AWS is another story, have AMI's been published yet for F37?

Answering my own question...According to https://alt.fedoraproject.org/cloud/ not yet :disappointed: Maybe there's someone we could ask?

**Comment by cevich** [comment]
Another option is we could (somehow) manually import the images ourselves.  It looks like they've got x86_64 and aarch64 generic cloud images and qcow's available:  https://dl.fedoraproject.org/pub/fedora/linux/development/37/Cloud/

(I've never manually imported an image into AWS)

**Comment by lsm5** [comment]
> Another option is we could (somehow) manually import the images ourselves. It looks like they've got x86_64 and aarch64 generic cloud images and qcow's available: https://dl.fedoraproject.org/pub/fedora/linux/development/37/Cloud/
> 
Should be doable AFAICT https://docs.aws.amazon.com/toolkit-for-visual-studio/latest/user-guide/tkv-create-ami-from-instance.html .

**Comment by cevich** [comment]
My hesitation on the manual option is mainly over how many times will we need to do it?  You've seen first-hand how sometimes our build-automation goes all wonky with new OS versions.  Specifically I'm thinking of the ssh-rsa problem in F35 was it?  So this is probably fine for now, to help shoehorn an AMI in for our system to pick up, but if we need to repeat this 3, 4, or 5 times, then again in 6-months, it makes sense to spend time updating our packer-automation to do it for us - albeit at a much higher brain and time cost.

**Comment by lsm5** [comment]
hmm, if packit can do this testing for us for not just rawhide but release branches, that would mean a lot less maintenance for us. I'll first try with packit then for f37

**Comment by rhatdan** [comment]
@lsm5 @cevich any progress on this?

**Comment by cevich** [comment]
Yes, I'm trying to build a fresh set of VM images then will push to my podman PR.  There are some golang 1.19 related issues I could use help fixing, otherwise I can probably figure them out or will ask for more specific help.

**Comment by cevich** [comment]
-sigh- no dumb github bot, all the activity is in #15760, why would I bother to update the linked issue as well?
