### ISSUE TITLE
Machine test failure: `Basic ops` fails regularly

### ISSUE THREAD

**Issue by lsm5** [containers/podman#15347]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`Basic ops` test fails regularly on both x86_64 and aarch64 in CI.

**Steps to reproduce the issue:**

1. make localmachine

**Describe the results you received:**

See: https://cirrus-ci.com/task/5216543754682368

**Describe the results you expected:**

Should pass.

It actually did pass on running tests on a manually created bare metal aarch64 EC2 instance.
Failed on manually created x86_64 EC2 instance.

@baude PTAL
/cc @edsantiago @cevich

**Comment by lsm5** [comment]
Skipping this test with a FIXME note referring to this issue.

**Comment by edsantiago** [comment]
SGTM. This whole situation is absurd. Please write your comment in the form `Skip("FIXME: #15347 - blah blah")` so all my FIXME-finders will be able to track it.

**Comment by cdoern** [comment]
This is the reason 

```
+0248s] Error: error creating host key callback function for /tmp/podman_test4234004347/.ssh/known_hosts: open /tmp/podman_test4234004347/.ssh/known_hosts: no such file or directory
```

@mtrmac this is coming from the change suggested for the known hosts parsing. These tests will continue to fail until a file is generated and properly filled before machine test execution

**Comment by edsantiago** [comment]
@cdoern yes, that's been discussed at huge length in #15031 (please visit to catch up). The question is how to make that fix, and how to test it, and that's not really something @lsm5 should be forced to have to do.

**Comment by baude** [comment]
no no no, *I* am working on this.  But I cannot totally parse the conversation as it is incomplete.  Moreover, we cannot force users to have a known_hosts; imagine new podman machine users trying to work their way around this.

**Comment by baude** [comment]
moreover, it was me that asked @lsm5 to skip the test for now.

**Comment by cdoern** [comment]
Ok sorry, I just got a ping on #15094 informing that the ssh changes broke this so I was just catching up on what I missed. 


The problem with the known hosts patch is that it seems the options are either no validation or the requiring of a known hosts file. Maybe we can allow for a default opt out to maintaint parity with earlier versions but add a flag for enabling host sanity?

**Comment by edsantiago** [comment]
Ah - sorry, I was not aware of that context. Thank you!

**Comment by mtrmac** [comment]
Where do we want to have the design discussion, if any? This seems like a better place than #15031, because it is dedicated to the problem, but the previous history is in the aarch64 PR…

---

> Maybe we can allow for a default opt out to maintaint parity with earlier versions but add a flag for enabling host sanity?

Secure encryption over the internet (and that requires public key validation) _must not_ be a non-default opt-in. (I really don’t know whether `podman machine` is a genuine special case to this; it might well be.)

I’m fine with reverting the #15094 work _temporarily_, to get CI working, until we understand the problem space and know what we want to do, assuming that happens soonish.

I’m no longer really willing to tolerate the previous behavior and everyone, including me, moving on to other things; reverting to the previous behavior and adding a flag to enable verification would be a bit of an improvement over the current state, but for the most part mean likely to end up with “everyone moving on”.

**Comment by cevich** [comment]
>  is a genuine special case to this; it might well be.)

FWIW, I think it is a special case.  Unless we envision that podman-machine will ever permit creating/managing non-local VMs?  I kind of doubt that will ever be in-scope for podman, and it's what `podman connection ...` is intended to support.  

Remember too, with the current workflows, users will be somewhat regularly pulling new images and starting/stopping/deleting VMs.  Every single one of those will have a different host-key.  So I think it's perfectly safe to (somehow) arrange for podman-machine connections to never gripe over not having the host keys or having the wrong ones.

**Comment by mtrmac** [comment]
I agree we want that UX. I have no knowledge to judge whether we can do that in the tempting trivial way, by disabling key verification altogether.

**Comment by lsm5** [comment]
> @lsm5 Any update

it's mostly @cdoern and @baude working on this.
