### ISSUE TITLE
man podman-run.1 --publish-all contains redundant information

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#15356]
https://github.com/containers/podman/blob/main/docs/source/markdown/podman-run.1.md.in#L558 says:

```
#### **--publish-all**, **-P**

Publish all exposed ports to random ports on the host interfaces. The default is **false**.

When set to **true**, publish all exposed ports to the host interfaces. The
default is **false**. 

When using this option, Podman will bind any exposed port to a random port on the host
within an ephemeral port range defined by */proc/sys/net/ipv4/ip_local_port_range*.
```
This is the same information repeated twice:
* it is stated twice that the default is **false**
* it is stated twice that the host-ports are random

**Comment by edsantiago** [comment]
Being worked on as part of my man-page refactoring. Thank you for reporting.

**Comment by edsantiago** [comment]
Still in progress - I have a `docs_dedup_cleanup` local branch that is gathering all the smaller tweaks gathered in the process of docs_dedup.
