### ISSUE TITLE
Add labels on containers that are started within pods

### ISSUE THREAD

**Issue by benoitf** [containers/podman#15374]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

When I create podman pods, I have very few information in the container directly that this container is part of a pod
Inspecting the pod (not using compat mode) I've a single field (but no name as well)
```
"Pod": "140e94e830b192325d4f6778f2a59de255611f8cd776efd9728af9066e1f7e5d",
```
but then I need to go to list of pods, etc

**What I would like:**

1. Add some annotations with `Labels` on the container

2. Then when displaying info of a container (even using compat mode) I will clearly see that this container is part of a pod and the pod name will be part of the Label

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
Great catch, @benoitf!

> Add some annotations with Labels on the container

This would be inconsistent with other Podman-specific fields that we expose via inspect.  I'd prefer making it a real field in the inspect data.

@mheon WDYT?

**Comment by benoitf** [comment]
FYI, compat API won't show these extra fields (only podman API inspect) while labels will be displayed on all inspect tools.
So it might be interesting (not my usecase as I can use Podman API) to expose the grouping of Pods like for Compose with Labels

**Comment by vrothberg** [comment]
That sounds good.  If needed, the compat endpoint can add this information to labels.

**Comment by mheon** [comment]
I'm fine with adding this to Libpod Inspect as a top-level construct.

Should we consider adding it as an environment variable, so the container itself can tell it's part of a pod?

**Comment by rhatdan** [comment]
I agree don't inject it into the container environment.  Lots of cases where a privileged container is monitoring a container.  That information might be an additional risk.

**Comment by boaz0** [comment]
@vrothberg / @rhatdan - if you don't mind, I start working on this.

**Comment by Luap99** [comment]
I don't understand why a docker API caller would be interested in pods?
I think this change would cause problems: https://github.com/containers/podman/pull/15738#issuecomment-1243527931

**Comment by mheon** [comment]
I could see making these OCI annotations instead of labels. That will keep
them out of the compat API, and the OCI runtime might be interested that
the container is in a pod ( I know kata wants to know this, for example).

**Comment by boaz0** [comment]
@benoitf is it OK if the pod name will be shown in `annotations`? Unfortunately, `annotations` are not available through `compat API`.

**Comment by benoitf** [comment]
for me it's ok as I'm using the LibPod API, I was just thinking for people using pure "Docker tools" inspecting containers on podman. They won't have more details on containers that are part of a pod

**Comment by vrothberg** [comment]
Closing as the feature is not needed anymore.
