### ISSUE TITLE
Backwards-incompatible change between 4.0.2 and 4.1.1?

### ISSUE THREAD

**Issue by Elkasitu** [containers/podman#15373]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

My podman version was recently upgraded from (what I assume was) 4.0.2 to 4.1.1, after said upgrade my containers stopped working with the following error:

`Error: invalid config provided: extra host entries must be specified on the pod: network cannot be configured when it is shared with a pod`

I assume that this is due to `podman-compose` version 0.1.x using the `--add-host` flag for networking, this problem does not happen with at least `podman` version 4.0.2 (tested by rolling back package) nor with `podman-compose` version 1.x, as it uses a different networking system.

**Steps to reproduce the issue:**

1. Install podman 4.1.1

2. Install podman-compose 0.1.x

3. Run any compose file that uses intra-container networking with `podman-compose`

**Describe the results you received:**

```
podman run --name=foo -d --pod=foo --label io.podman.compose.config-hash=123 --label io.podman.compose.project=foo --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=foo --label com.docker.compose.project.working_dir=/foo --label com.docker.compose.project.config_files=docker-compose.yml,docker-compose.test.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=foo -e POSTGRESQL_DATABASE=foo -e POSTGRESQL_USER=foo -e POSTGRESQL_PASSWORD=foo -e PGPASSWORD=foo -e POSTGRESQL_HOST=foo -v foo-data:/var/lib/pgsql/data/ --add-host bar:127.0.0.1 --add-host baz:127.0.0.1 --add-host foo:127.0.0.1 --add-host foo:127.0.0.1 --add-host quux:127.0.0.1 --hostname foo registry.redhat.io/rhel8/postgresql-13:1 ./scripts/setup-foo.sh
Error: invalid config provided: extra host entries must be specified on the pod: network cannot be configured when it is shared with a pod
```

**Describe the results you expected:**

```
podman run --name=foo -d --pod=foo --label io.podman.compose.config-hash=123 --label io.podman.compose.project=foo --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=foo --label com.docker.compose.project.working_dir=/foo --label com.docker.compose.project.config_files=docker-compose.yml,docker-compose.test.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=foo -e POSTGRESQL_DATABASE=foo -e POSTGRESQL_USER=foo -e POSTGRESQL_PASSWORD=foo -e PGPASSWORD=foo -e POSTGRESQL_HOST=foo -v foo-data:/var/lib/pgsql/data/ --add-host bar:127.0.0.1 --add-host baz:127.0.0.1 --add-host foo:127.0.0.1 --add-host foo:127.0.0.1 --add-host quux:127.0.0.1 --hostname foo registry.redhat.io/rhel8/postgresql-13:1 ./scripts/setup-foo.sh
<container-id>
0
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Have uninstalled the relevant podman version so I don't have this info other than it was 4.1.1

**Output of `podman info`:**

Same as above

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

Same as above

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Have not checked the latest version as it's not available as a package in my distribution (RHEL 8.6 CSB)
I have checked the troubleshooting guide and didn't find much

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine

**Comment by mheon** [comment]
This was a deliberate change to how networking was handled - I can't find the issue where we discussed it, but we made the change as a bugfix given that the existing behavior seemed to be broken. I'll try to find more details, but @Luap99 (who drove the change) may have more of an idea when he gets back from vacation.

**Comment by Luap99** [comment]
I wasn't aware that this was used by podman-compose. The old podman behaviour was IMO terrible broken, since it would add the hosts for all containers in a pod since /etc/hosts is shared and also never deleted them. Thus restarting a container multiple times would add the same name over and over.

I understand that this was a breaking change but I see no good way around this. Also since 4.1 and 4.2 is out for a while now I think it is unlikely that we revert this.

**Comment by Elkasitu** [comment]
Closing, it's still an issue for me but an acceptable workaround exists (downgrade `podman` to `4.0.x` or upgrade `podman-compose` to `1.x`)
