### ISSUE TITLE
additionalimagestores: while adding image to shared location, image listing and pod creation (on other hosts using shared location) hang

### ISSUE THREAD

**Issue by coco80021** [containers/podman#15380]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am using CRI-O (as part of kubernetes) with the 'additionalimagestores' feature in /etc/containers/storage.conf, with a gluster mountpoint directory for the shared imagestore.   On a gluster client box, I am able to pull new images using podman directly to the gluster mountpoint shared imagestore directory.  (once I bumped up the gluster hardlinks limit).  Everything works fine in the simple case.     So that part is all good.

However, on a gluster client box, while I pull a new image into the gluster mountpoint shared imagestore directory, on other hosts using the shared imagestore directory, I notice two things hang until the image has completed its pull to that shared imagestore directory:
a) the command 'crictl images', as executed on the kubernetes CRI-O nodes, hangs
b) on the kubenetes CRI-O nodes, I cannot start new pods on the node -- presumably because container creation is hanging.  

As soon as the image pull completes, everything resumes/works

**Steps to reproduce the issue:**

1.  Setup simple gluster server environment and volume.  Set gluster hardlinks limit to 0.

2.  Setup gluster client box A.  Install gluster client libraries, as well as podman.  As root, use podman to pull first image to shared imagestore directory on gluster volume mountpoint.

3. On a different box B, setup podman/crio and gluster client, with additionalimagestores directory pointing to gluster volume mountpoint shared imagestore directory.

4. On box B, periodically as root, run 'crictl images / podman images' command.

5. While this is running, on box A, as root, use podman to pull a new image to shared imagestore directory on gluster volume.   This causes the 'crictl images / podman images' command on box B to hang, until the pull completes.  I expect starting a new container will also hang while the image is being pulled to the shared imagestore directory.
 
**Describe the results you received:**
hangs until image push completes

**Describe the results you expected:**
nothing hangs

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.17.12
Built:        Wed Aug  3 16:36:19 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
# podman info
host:
  arch: amd64
  buildahVersion: 1.26.2
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.2-2.module+el8.6.0+20721+d8d917a9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.2, commit: 226e45e4f5c8e763435ceae775bac989048f45e1'
  cpuUtilization:
    idlePercent: 99.56
    systemPercent: 0.19
    userPercent: 0.24
  cpus: 8
  distribution:
    distribution: '"ol"'
    variant: server
    version: "8.6"
  eventLogger: file
  hostname: sroth8gc1
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.17-2136.308.9.el8uek.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 27372888064
  memTotal: 50222469120
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.3-2.module+el8.6.0+20721+d8d917a9.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.3
      spec: 1.0.2-dev
      go: go1.17.12
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.module+el8.6.0+20721+d8d917a9.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 8558473216
  swapTotal: 8558473216
  uptime: 172h 50m 2.44s (Approximately 7.17 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - container-registry.oracle.com
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 202809556992
  graphRootUsed: 17816272896
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1659569779
  BuiltTime: Wed Aug  3 16:36:19 2022
  GitCommit: ""
  GoVersion: go1.17.12
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.1.1-2.module+el8.6.0+20721+d8d917a9.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by giuseppe** [comment]
that happens because Podman takes a write lock on the storage.  Could the additional image store be populated before its images are used on the cluster?

**Comment by coco80021** [comment]
Yes-- our plan is to pull new (dynamic) images to gluster shared imagestore directory first, then kick off a bunch of k8s pods all using that new image. 

So for example, say image A is already in shared imagestore.  We pull new image B to there, then kick off a bunch of k8s pods to use image B.

The problem is that while we are pulling image B to the shared imagestore directory, we cant
a) kick off new pods with image A
or
b) list images in the shared imagestore

both of these hang until the pull of image B completes.

**Comment by coco80021** [comment]
I was thinking one short-term workaround may be to setup say 50 additionalimagestore shared directories, and list them all in /etc/containers/storage.conf under additionalimagestores-- imagestore1, imagestore2, ..., imagestore50

Maybe we could then pull images to these uniquely named shared imagestore directories without impacting the ability to start up pods referencing images in other shared imagestore directories.  For example, pulling image B to shared imagestore2 would likely not affect starting up image A in shared imagestore1 while the pull of image B is occurring.

To make this work properly, we might need to do a bit of magic around the 'appearance' of a new shared imagestore directory -- for example, pulling image B to tmpimagestore2, then renaming tmpimagestore2 to imagestore2 (or moving contents from tmpimagestore2 to imagestore2).   That way the new shared imagestore directory contents would appear atomically to podman/cri-o rather than seeing partial versions of the new image while files are being copied.

**Comment by coco80021** [comment]
For anyone that has the same requirements (loading new images into the additionalimagestore directory while starting up existing images), note it is possible to replace one of the imagestore directories dynamically with a pre-populated one.

For example, say I have additionalimagestoredirectories imagestore1 ... imagestore50 each which can hold a single image.

It seems to work smoothly to replicate a new imagestore directory imagestore4.tmp to the host, using one of several approaches.   Note imagestore4.tmp is not listed in the additionalimagestoredirectories list of directories.

Then with two renames, one can 'activate' this new image:
mv imagestore4 imagestore4.deleteme
mv imagestore4.tmp imagestore4

It's not 100% atomic, but it's pretty fast.  CRI-O/podman seem to detect the new image (in imagestore4) immediately, and existing images keep working as before.

This is a short-term approach.

**Comment by coco80021** [comment]
Regarding the longer-term, it would be nice if podman/CRI-O could handle dynamically adding images without the locks which are preventing images from being used while the new image is being loaded.

Or alternatively, it would be nice if podman/CRI-O supported dynamically adding to the list of additionalimagestore directories.   Say via a file update and a 'reload file' option or something like that.   The detection of the new image would be atomic, as compared to the option I have in place at the moment.   And there would be no locking needed while the imagestore directory is being fetched, which is also nice.

From my perspective, many of the options for sending an image to a node can take awhile (minutes to transfer), and so locking is not ideal.

On the other hand, I understand that a single additionalimagestore directory (rather than 1 per image) has the benefit that layers can be shared.   We lose that when we move to a 1 imagestore directory per image model.

**Comment by rhatdan** [comment]
@giuseppe @nalind @vrothberg @mtrmac PTAL

This looks like a container/storage locking issue.

**Comment by mtrmac** [comment]
That’s more or less just how it works; without additional image stores, using just the primary one, I expect you‘d see the same behavior.

(The behavior is not that the store being written is locked _continuously_ over the time of the pull, but it is locked _almost all of the time_, at least if we are good at optimizing the bottlenecks out; there are brief blips where the write lock is released while we transition across the c/storage API boundary, i.e. about once per layer.)

Changing the design not to keep an exclusive write lock during most of the push is, I guess, plausible, but it would introduce _quite a few_ ways for the store to be modified in unexpected ways during the pull. IMHO adding that complexity is out of the question until we can get at least the _current_ design’s locking correct in corner cases, e.g. https://github.com/containers/storage/issues/1332 / https://github.com/containers/storage/issues .

**Comment by edsantiago** [comment]
Closing, as it seems unlikely to be resolved.

**Comment by yeswalrus** [comment]
Is there any chance we could re-open this? This is kinda a blocker for a use case we have - I need to be able to have a service user periodically add new images to a cache on a shared XFS storage

**Comment by giuseppe** [comment]
could you please file a different issue and provide more information about your use case?
