### ISSUE TITLE
Podman for Windows: machine init fails

### ISSUE THREAD

**Issue by bittracker** [containers/podman#15382]
/kind bug

The machine Init fails:

```powershell
podman machine init --image-path C:\Users\user\Downloads\podman-rootfs.tar.xz
Error: open C:\Users\user\.local\share\containers\podman\machine\wsl\cache: is a directory
```

**Steps to reproduce the issue:**

1. Install Podman using the msi noted below.

2. Start a PowerShell session as non Administrative User

3. Issuing the follwoing podam command:
 
```powershell
podman machine init --image-path C:\Users\user\Downloads\podman-rootfs.tar.xz
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I have also tried to remove the folder structure under `C:\Users\user\.local\share\containers\podman\*`, but without success. :(

**Output of `podman version`:**

```
podman.exe version 4.2.0
```

**Output of `podman info`:**

```
is not useful because machine init fails
```

**Used Package Version and Machine Image:**

```
podman-v4.2.0.msi (sha256hash: 40d506d04b32410da3ac0d570c50fb84b3a6e5157fa131bc8cb66c410cb463e2)
podman-rootfs.tar.xz (sha256hash: 1f45b65128df25b3ec54941e77c353eebc398a64e96b3c63871d6e74349265d1)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : Enterprise
WindowsInstallationType                                 : Client
WindowsProductName                                      : Windows 10 Enterprise
WindowsSystemRoot                                       : C:\WINDOWS
WindowsVersion                                          : 2009
CsSystemType                                            : x64-based PC
```

Thanks for your great work!
bittacker

**Comment by mheon** [comment]
@n1hility PTAL

**Comment by bittracker** [comment]
@n1hility Thanks for taking on this issue. Please let me know if you need any further information.

**Comment by w60001** [comment]
I'm seeing the exact same issue.  Any updates / hints / workarounds?

**Comment by w60001** [comment]
And some more context...

I see the same issue on Podman 4.2.0 and 4.3.0.  Executing `podman machine init` without the image-path flag works fine.

**Comment by w60001** [comment]
This may not be the case for the original post, but for me this only happens when my Windows image path has a space in it.

`podman machine init --image-path "C:\Path with Spaces\rootfs.tar.xz"`

And yes I'll stop posting updates now...  😄

**Comment by n1hility** [comment]
@w60001 i believe this is a bug with fully qualified path handling, you should be able to workaround with a relative path ´—image-path .\rootfs.tar.gs´

**Comment by bittracker** [comment]
I have just tried `podman.exe version 4.3.1` and everything works as expected.

Thanks fixing this :)

**Comment by soft4rchitecture** [comment]
> @w60001 i believe this is a bug with fully qualified path handling, you should be able to workaround with a relative path ´—image-path .\rootfs.tar.gs´

I tried with podman 4.3.1, it didn't work with the fully qualified path. But it worked with relative path. Thank you a lot
