### ISSUE TITLE
Running Podman on Windows Server 2019

### ISSUE THREAD

**Issue by Taymindis** [containers/podman#15400]
Does Podman support windows server 2019 which installed on VM?

**Comment by mheon** [comment]
We require WSL2, and Server 2019 appears to support it, so I would assume yes, but I don't think anyone has tested this before.

**Comment by Taymindis** [comment]
I got the error below on Server 2019

OS Name:                   Microsoft Windows Server 2019 Standard
OS Version:                10.0.17763 N/A Build 17763

> podman machine init
Error: your version of Windows does not support WSL. Update to Windows 10 Build 19041 or later

**Comment by navylover** [comment]
Any updates? I also need install podman on the windows server 2019 and tried almost ways from googled results?
so, the answer is "No"?

**Comment by baude** [comment]
The answer today is you must have WSL.  We have discussed alternatives but nothing has been implemented.
