### ISSUE TITLE
podman macOS pkg installer is displaying an incorrect version

### ISSUE THREAD

**Issue by benoitf** [containers/podman#15406]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I downloaded https://github.com/containers/podman/releases/download/v4.2.0/podman-installer-macos-amd64.pkg

Then I execute it and it's displaying 4.1.0 instead of 4.2.0
![image](https://user-images.githubusercontent.com/436777/185913701-19c1b6b3-a652-4089-9df7-7a9da247095a.png)

**Steps to reproduce the issue:**

1. Download pkg from https://github.com/containers/podman/releases/tag/v4.2.0 (using your arch like podman-installer-macos-amd64.pkg if you're using intel)

2.Execute it

3.

**Describe the results you received:**

4.1.0

**Describe the results you expected:**

4.2.0

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ashley-cui** [comment]
Updated the github artifact pacakges! Will open a PR later to change the makefile, and then after that I'll close this issue.

**Comment by benoitf** [comment]
Thanks @ashley-cui
