### ISSUE TITLE
How to run nested, rootless containers?

### ISSUE THREAD

**Issue by webbnh** [containers/podman#15419]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm trying to come up with a container and a `podman` command line which will allow me to run a container inside a container, and, having done that, I want to be able to run a third container inside the second (and, just for the heck of it, how about a fourth container inside the third?).  And, I would like this to be possible for any appropriately-configured user on my system (i.e., using the same container image for any user and something like the same `podman` command or a suitable wrapper script).  And, finally, after shutting down the containers, I would like to have any files created inside them on file systems mapped in from the host to be owned by the UID of the user who ran the containers.

Shouldn't this be possible?  (The example at the [Enable Sysadmin blog](https://www.redhat.com/sysadmin/podman-inside-container) seems to imply that it is, but it only seems to work by imposing some heavy constraints, and I don't think it will nest more than once.)

My current attempts fail because of some sort of confusion about which mapping to use to create the nested container.  What do I need to do in order to have an arbitrary user inside the container which has available to it enough mappings to support a third (or more) nested container(s)?  (I don't think I need much more than one sub-mapping per container....)

**Steps to reproduce the issue:**

1. Create the outer container (and wait about 20 seconds(!) for the command prompt)
  a. Note that, inside the container, I have UID and GID sub-mappings for my current UID and GID
  b. Note that my current `$USER` is `wscales`, which is not in the `/etc/passwd` file
4. Inside the container, invoke the same command that was used to create the outer container
  a. Ignore the warning about the `"/"` mount point which was dealt with in #15295 
  b. Note the error `cannot find UID/GID for user wscales` -- **Why is it looking for `wscales` instead of UID `1000`??**
7. Note that the inner container creation fails with `Error: potentially insufficient UIDs or GIDs available in user namespace` presumably as a result of the previous warning about `using rootless single mapping into the namespace`.

If I omit the `$USER` environment variable definition, then the inner container invocation dies with `Error: cannot setup namespace using newuidmap: exit status 1`.

**Describe the results you received:**

```
$ podman run --user 1000:1000 --uidmap 1000:0:1 --uidmap 0:1:1000 --uidmap 1001:1001:500 --gidmap 1000:0:1 --gidmap 0:1:1000 --gidmap 1001:1001:500 --volume /home/wscales -w /home/wscales --env HOME=/home/wscales --env USER=wscales --ulimit nofile=65536:65536 --rm -it --rm -v /home/wscales/.local/share/containers --security-opt label=disable --device /dev/fuse quay.io/pbench/pbench-ci-fedora:webb bash
bash-5.1$ cat /etc/subuid 
1000:10000:5000
bash-5.1$ cat /etc/subgid 
1000:10000:5000
bash-5.1$ id
uid=1000(1000) gid=1000(1000) groups=1000(1000)
bash-5.1$ whoami
1000
bash-5.1$ echo $USER
wscales
bash-5.1$ cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
operator:x:11:0:operator:/root:/sbin/nologin
games:x:12:100:games:/usr/games:/sbin/nologin
ftp:x:14:50:FTP User:/var/ftp:/sbin/nologin
nobody:x:65534:65534:Kernel Overflow User:/:/sbin/nologin
tss:x:59:59:Account used for TPM access:/dev/null:/sbin/nologin
systemd-network:x:192:192:systemd Network Management:/:/sbin/nologin
systemd-coredump:x:999:998:systemd Core Dumper:/:/sbin/nologin
systemd-resolve:x:193:193:systemd Resolver:/:/sbin/nologin
systemd-oom:x:998:997:systemd Userspace OOM Killer:/:/sbin/nologin
dbus:x:81:81:System message bus:/:/sbin/nologin
dnsmasq:x:997:996:Dnsmasq DHCP and DNS server:/var/lib/dnsmasq:/sbin/nologin
redis:x:996:995:Redis Database Server:/var/lib/redis:/sbin/nologin
1000:*:1000:1000:container user:/home/wscales:/bin/sh
bash-5.1$ podman run --user 1000:1000 --uidmap 1000:0:1 --uidmap 0:1:1000 --uidmap 1001:1001:500 --gidmap 1000:0:1 --gidmap 0:1:1000 --gidmap 1001:1001:500 --volume /home/wscales -w /home/wscales --env HOME=/home/wscales --env USER=wscales --ulimit nofile=65536:65536 --rm -it --rm -v /home/wscales/.local/share/containers --security-opt label=disable --device /dev/fuse quay.io/pbench/pbench-ci-fedora:webb bash
WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
ERRO[0000] cannot find UID/GID for user wscales: No subuid ranges found for user "wscales" in /etc/subuid - check rootless mode in man pages. 
WARN[0000] using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding sub*ids 
Error: potentially insufficient UIDs or GIDs available in user namespace (requested 1:1 for /home/wscales/.local/share/containers/storage/overlay/l): Check /etc/subuid and /etc/subgid: chown /home/wscales/.local/share/containers/storage/overlay/l: invalid argument
```
Without the `$USER` environment variable:
```
$ podman run --user 1000:1000 --uidmap 1000:0:1 --uidmap 0:1:1000 --uidmap 1001:1001:500 --gidmap 1000:0:1 --gidmap 0:1:1000 --gidmap 1001:1001:500 --volume /home/wscales -w /home/wscales --env HOME=/home/wscales --ulimit nofile=65536:65536 --rm -it --rm -v /home/wscales/.local/share/containers --security-opt label=disable --device /dev/fuse quay.io/pbench/pbench-ci-fedora:webb bash
bash-5.1$ whoami
1000
bash-5.1$ podman run --user 1000:1000 --uidmap 1000:0:1 --uidmap 0:1:1000 --uidmap 1001:1001:500 --gidmap 1000:0:1 --gidmap 0:1:1000 --gidmap 1001:1001:500 --volume /home/wscales -w /home/wscales --env HOME=/home/wscales --ulimit nofile=65536:65536 --rm -it --rm -v /home/wscales/.local/share/containers --security-opt label=disable --device /dev/fuse quay.io/pbench/pbench-ci-fedora:webb bash
WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
Error: cannot setup namespace using newuidmap: exit status 1
```

**Describe the results you expected:**

I expected that I would be able to create a container using the `podman` command executing inside the container and, when that worked, that I would be able to create a third (and possibly a fourth) nested container.  I expected that the `--user` on the outer container invocation would determine the UID value used to look up the sub-UID range defined in the `/etc/subuid` file inside the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

None

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.1
Built:        Thu Jul 28 14:53:18 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.2
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.3-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.3, commit: 8d561e47dd44c98c15c24a5e16aa1fc187df1b75'
  cpuUtilization:
    idlePercent: 99.97
    systemPercent: 0.01
    userPercent: 0.01
  cpus: 8
  distribution:
    distribution: '"centos"'
    version: "9"
  eventLogger: journald
  hostname: pbench-ctr-build
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 296608
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1004
      size: 1
    - container_id: 1
      host_id: 296608
      size: 65536
  kernel: 5.14.0-142.el9.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 59890855936
  memTotal: 66617737216
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun-1.5-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1004/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.el9.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 0
  swapTotal: 0
  uptime: 37h 15m 53.72s (Approximately 1.54 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/wscales/.config/containers/storage.conf
  containerStore:
    number: 29
    paused: 0
    running: 0
    stopped: 29
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/wscales/.local/share/containers/storage
  graphRootAllocated: 429287014400
  graphRootUsed: 109654519808
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 142
  runRoot: /run/user/1004/containers
  volumePath: /home/wscales/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1659019998
  BuiltTime: Thu Jul 28 14:53:18 2022
  GitCommit: ""
  GoVersion: go1.18.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1
```

**Package info (e.g. output of `rpm -q podman`):**

```
podman-4.1.1-6.el9.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes, I have checked the Podman Troubleshooting Guide -- I'm working from entries 33 & 34; no, I have not tried the latest Podman (I don't have root on the machine where I am running, and so I cannot install packages).

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on a VM.

**Comment by rhatdan** [comment]
This was recently fixed to not show the warning. Please try out podman 4.2

**Comment by rhatdan** [comment]
If you are running an image within a container the UID Mappings inside of your container must be large enough to run the container within the container.  Similarly the range of UIDs on the host have to be probably much larger then the 65k allocated by default.

**Comment by webbnh** [comment]
> This was recently fixed to not show the warning. Please try out podman 4.2

@rhatdan, this Issue is not about the warning about the root file system.  Please see my text above in Step 2a under "Steps to reproduce this issue" where I point out that that warning should be ignored and where I reference the issue where it was addressed.  (Unfortunately, that issue hasn't really been resolved...it was just closed and the conversation ended with open questions.)

> If you are running an image within a container the UID Mappings inside of your container must be large enough to run the container within the container.

@rhatdan, can you give me some indication as to how many mappings that would require?  If I read it right (see above), the `/etc/subuid` file inside the container grants 5000 mappings for the UID that I think I'm running under.  It's probably true that the invocation command only provides 500 mappings, but the `/etc/passwd` file inside the container has only 22 entries, and I'm only running a small handful of processes...so, it's not obvious to me how I would need more than about three (me, `root`, `nobody`), plus whatever the nested containers require (which, since they are the same container, should have analogous requirements).  Does the nested invocation have to request/provide fewer mappings because of the limit imposed by the outer one?

> Similarly the range of UIDs on the host have to be probably much larger then the 65k allocated by default.

Could you explain why this is?  (Or, point me to documentation which describes how this stuff works and how to use it?)

The real question is, **why does the inner invocation seem to use the `$USER` value (instead of, e.g., the UID) to index into the container's `/etc/subuid` list?**  It seems like something is broken there...which leaves me confused as to why this Issue was closed without actually providing any sort of resolution....
