### ISSUE TITLE
infra container removal with force option is not removing the container

### ISSUE THREAD

**Issue by benoitf** [containers/podman#15448]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

when removing containers, we can force the removal but it seems it’s not working on the infra containers
like if there is only one container in a pod and there is only one infra container in the pod, we can’t force the removal of this container (assuming it might remove the pod as well) using -f flag
is it something wanted ?

**Steps to reproduce the issue:**

Let say you've a pod with only one container, the infra container

```
$ podman pod ls | grep da07597c8c32
da07597c8c32  mypod       Created     4 days ago  41f3cfd2ee4d  1
```

```
$ podman container ps
41f3cfd2ee4d  localhost/podman-pause:4.1.1-1658516759              4 days ago  Created                    da07597c8c32-infra
```

and you want to force remove it

```
$ podman rm -f da07597c8c32-infra 
Error: container 41f3cfd2ee4dfc79a4350e3558f37d4dd2c009c3f5ed3f3bb72e6f65a74ca7af is the infra container of pod da07597c8c3222dbdf0b1c1117f1b7be9a468aa3568900db5ac9428890a6cda4 and cannot be removed without removing the pod
```

**Describe the results you received:**
infra container of pod `da07` cannot be removed without removing the pod

**Describe the results you expected:**
infra container is removed

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

v4.2.0
```
(paste your output here)
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
Thanks, @benoitf!

The request makes total sense to me.  `podman image rm -f` can also remove infra containers and hence pods, so I think that `podman container rm -f` should be able to as well.

**Comment by mheon** [comment]
This was deliberate. If you want `podman rm` to remove more than one container (or, well, object, given we're removing a pod), you also need to pass `--depends` to remove dependencies as well.

**Comment by benoitf** [comment]
`--depend` is a specific podman thing

using `--force` which is a compat mode, I assume it's forcing the removal of the container.

Like '--force' being superior of `--depend`

**Comment by mheon** [comment]
That is deliberately the opposite of what we did.

The `container rm` existed already, and it did one thing and only one thing: remove a single container (optionally, a single running container, with `--force`). Making it remove multiple containers at once (as removing an infra container must) is a clear break of user expectations, and cannot be default.

**Comment by benoitf** [comment]
@mheon but if I have only one infra container in a pod, forcing the removal of this pod probably means that I want to delete the pod as well.

**Comment by mheon** [comment]
I could be convinced to allow removing pods with only a single container in them, but it still feels iffy. The command has only ever removed containers, and only ever a single container. This feels like a confusing change for users.

**Comment by rhatdan** [comment]
No we can not change the default currently we allow users to add containers to pods, which have no containers.
Adding --depend does not seem like a burden.

**Comment by benoitf** [comment]
I think most of people are assuming force to really remove stuff.
