### ISSUE TITLE
Podman network does not work if the host is running a DNS server

### ISSUE THREAD

**Issue by martdj** [containers/podman#15452]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
When using Podman 4.x, Podman network does not work if the host is running a DNS server

Podman 4.x uses netavark and aardvark-dns for networking. Communication between containers in the same network depend on aardvark-dns to find each other. aardvark-dns tries to bind on port 53. If this port is already taken by a DNS server on the host, requests won't reach aardvark-dns, but are handled by the DNS server., As a result, container names will not be found and networking between the containers fails. 

**Steps to reproduce the issue:**

1. Create and run a DNS server on your host (I use Bind)

2. Create a network: Podman network create Testnet

3. Create 2 pods using this network:
podman run -it --network=Testnet --name busy1 busybox sh
podman run -it --network=Testnet --name busy2 busybox ping busy1

**Describe the results you received:**
PING busy1 (192.168.7.150): 56 data bytes
64 bytes from 192.168.7.150: seq=0 ttl=64 time=0.039 ms
64 bytes from 192.168.7.150: seq=1 ttl=64 time=0.060 ms
(192.168.7.150 is the IP address of the host, which also has the * DNS entry)

**Describe the results you expected:**
PING busy1 (10.89.0.2): 56 data bytes
64 bytes from 10.89.0.2: seq=0 ttl=64 time=0.037 ms
(I actually get this result **if** I stop the DNS server on the host)

**Additional information you deem important (e.g. issue happens only occasionally):**
The podman-compose script no longer creates pods for services that are part of one yaml-file, but instead creates a network which it uses for the communication between containers. On a host with a running DNS server, this breaks podman-compose. The only workaround that I have found so far is to manually create a pod and create the containers inside this pod.

**Output of `podman version`:**
```
podman version 4.1.1
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.2
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.3-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.3, commit: 8d561e47dd44c98c15c24a5e16aa1fc187df1b75'
  cpuUtilization:
    idlePercent: 93.6
    systemPercent: 1.05
    userPercent: 5.35
  cpus: 4
  distribution:
    distribution: '"centos"'
    version: "9"
  eventLogger: journald
  hostname: zeus.olympus.lan
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.0-148.el9.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 354938880
  memTotal: 32923631616
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.el9.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 16409686016
  swapTotal: 16638799872
  uptime: 2h 34m 12.2s (Approximately 0.08 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 17
    paused: 0
    running: 13
    stopped: 4
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 75125227520
  graphRootUsed: 15838117888
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 136
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1659019998
  BuiltTime: Thu Jul 28 16:53:18 2022
  GitCommit: ""
  GoVersion: go1.18.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.1.1-6.el9.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is a CentOS 9 Stream server

**Comment by mheon** [comment]
With Podman 4.2.0 (and Netavark/Aardvark 1.1.0), Aardvark now has the option to bind to non-53 ports with the `dns_bind_port` option in `containers.conf` (with firewall rules being added to ensure containers in the relevant networks still access the correct DNS servers).

Closing as completed.
