### ISSUE TITLE
Recommend registry.fedoraproject.org/fedora-minimal as container image?

### ISSUE THREAD

**Issue by StarpTech** [containers/podman#15451]
Hi, I found out that fedora provides a minimal docker image (99MB). It's half of the size comparison to the official fedora image `registry.fedoraproject.org/fedora` (189MB). This can reduce the download and push time significantly. My initial tests have shown that podman works. Can you confirm that this is supported?

```dockerfile
FROM registry.fedoraproject.org/fedora-minimal:38 as deploy

RUN microdnf distro-sync && \
		microdnf -y install podman shadow-utils && \
    microdnf -y install git podman buildah fuse-overlayfs && \
    microdnf clean all && \
    rm -rf /var/cache /var/log/dnf* /var/log/yum.* /var/lib/dnf/history.*

RUN podman info
```

The recommended dockerfile can be found [here](https://github.com/containers/podman/blob/main/contrib/podmanimage/stable/Containerfile).

**Comment by vrothberg** [comment]
Thanks for reaching out, @StarpTech!

@rhatdan WDYT?

**Comment by rhatdan** [comment]
Fine with me. Please open a PR, are these for the contrib images?  You might also want to do this for buildah.

**Comment by rhatdan** [comment]
We decided against doing this because of potential breakage.
