### ISSUE TITLE
blkio-weight-device is a NOP on pods

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#15464]
Make a block device:
```console
# lofile=/tmp/disk.img;fallocate -l 1k $lofile;losetup --show -f $lofile
/dev/loop0
# echo bfq >/sys/block/loop0/queue/scheduler
```
Create a pod, pass that device, and try to set weight:
```console
# bin/podman pod create --device /dev/loop0 --name foo --blkio-weight-device=/dev/loop0:123
1c90073f619de5bcdb83b6d1ba4caf5cae876f90208b9a6e2d8cd8b646b97468
# x=$(sudo bin/podman pod inspect --format '{{.CgroupPath}}' foo)
# cat /sys/fs/cgroup/$x/io.bfq.weight
default 100    <--- expected a second line '7:0 123'
```
Doesn't work with a running pod either
```console
# bin/podman pod start foo
1c90073f619de5bcdb83b6d1ba4caf5cae876f90208b9a6e2d8cd8b646b97468
# bin/podman run --pod=foo $IMAGE cat /sys/fs/cgroup/io.bfq.weight
default 100
```
(this could very easily be a misunderstanding on my part)

**Comment by mheon** [comment]
@cdoern PTAL

**Comment by cdoern** [comment]
I'm discovering this in a bunch of blkio related things. I need to double check but it might be because we have a separate field in the specgen (similar to throttle devices) that doesn't get translated into the runtime spec

**Comment by cdoern** [comment]
I think I resolved this in my podman update PR (i had to make the patch for update anyway. HOWEVER, if I recall correctly this might be one of the flags that only works with cgroupfs and at that its finicky... 

```
[charliedoern@fedora podman]$ sudo bin/podman --cgroup-manager=cgroupfs pod create --device /dev/loop25 --name foo --blkio-weight-device=/dev/loop0:123
Error: setting device weight "7:0 123": write /sys/fs/cgroup/libpod_parent/872dfdf56c64030e5bd558fb8b1b59cd70b7d4a38dde8311213cfbc554676b84/io.bfq.weight: operation not supported
```
regardless, getting to the point of writing the file and crun and runc rejecting us is the consensus I believe we came to back when this flag was implemented.

**Comment by cdoern** [comment]
resolved by the podman update PR, if any errors persist it is the kernel error we have been seeing
