### ISSUE TITLE
generate kube shall print spec.enableServiceLinks: false

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#15478]
`podman generate kube` shall emit
```yaml
spec:
  enableServiceLinks: false
```

To my knowledge podman does not utilize the XYZ_SERVICE_PORT any XYZ_SERVICE_PORT environment variables per service called XYZ, when running containers/pod.  When the pod created by podman is moved to Kubernetes, these variables will not be needed, too.  The above snippet prevents Kubernetes from creating the unused variables.

https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#accessing-the-service

```console
$ podman version
Client:       Podman Engine
Version:      4.3.0-dev
API Version:  4.3.0-dev
Go Version:   go1.18.5
Git Commit:   c9565b051c3843e5bad63f062f8c3125c548dd63
Built:        Thu Aug 25 10:27:07 2022
OS/Arch:      linux/amd64
```

**Comment by rhatdan** [comment]
@umohnani8 PTAL
Are you saying that `podman generate kube` should be generating
```
spec:
      enableServiceLinks: false
```

@dilyanpalauzov Interested in opening a PR?

**Comment by dilyanpalauzov** [comment]
Yes, I am saying this.  No, I am not going to open PR, since I do not know go and the podman internals.

**Comment by rhatdan** [comment]
Thanks for the report.

**Comment by rhatdan** [comment]
@saschagrunert @haircommander Do  you agree with @dilyanpalauzov assessment?

**Comment by haircommander** [comment]
yes this seems correct. Another future thing is the service created for the pod could populate those env variables, though that'd be more work than this approach

**Comment by saschagrunert** [comment]
Yep, since it defaults to `true` it should be probably turned off via the pod spec.
