### ISSUE TITLE
podman build too slow on macOS

### ISSUE THREAD

**Issue by GDdark** [containers/podman#15472]
![image](https://user-images.githubusercontent.com/15982894/186563766-b6a7196a-6ed4-40be-a43e-eaafdf881289.png)

It took a long time from the start of the build to the process of seeing the output.

How can I know what's going on in between?

Use Macos

**Comment by GDdark** [comment]
Podman Info: 
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpuUtilization:
    idlePercent: 81.48
    systemPercent: 11.77
    userPercent: 6.75
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "36"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 5.18.18-200.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1157304320
  memTotal: 2064896000
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/501/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 1h 37m 31.00s (Approximately 0.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 0
    stopped: 4
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106825756672
  graphRootUsed: 24409559040
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 86
  runRoot: /run/user/501/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1660228937
  BuiltTime: Thu Aug 11 22:42:17 2022
  GitCommit: ""
  GoVersion: go1.18.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0

**Comment by flouthoc** [comment]
I saw a similar issue before for macOS but I'm not sure, @baude @ashley-cui could you please confirm if this something which was encountered in the past as well on macOS.

@GDdark , Could you `time` the execution of a simpler Containerfile and paste output here, try with the containerfile shared below.
```Containerfile
FROM alpine
RUN echo hello
```

**Comment by GDdark** [comment]
sure.
![image](https://user-images.githubusercontent.com/15982894/186570488-41b342df-0027-468b-9f1a-9803e7d971a7.png)

This build takes a short time

Could it be the problem with my project, I use Node JS

**Comment by flouthoc** [comment]
Could you share you Containerfile of your project ?

**Comment by GDdark** [comment]
@flouthoc sure.

FROM node:16.16.0-alpine3.16

RUN mkdir -p /data/code/particle-node-server
WORKDIR /data/code/particle-node-server

COPY .npmrc /root/.npmrc

COPY package.json /data/code/particle-node-server/package.json
COPY yarn.lock /data/code/particle-node-server/yarn.lock
COPY dist /data/code/particle-node-server/dist
COPY ecosystem.config.js /data/code/particle-node-server/ecosystem.config.js
COPY .env.debug /data/code/particle-node-server/.env.debug

RUN yarn install --production=true
RUN npm install --location=global pm2
RUN pm2 install pm2-logrotate
RUN apk add curl

# tail -f /dev/null -> Suspend the process
CMD pm2-runtime ecosystem.config.js --env=$ENVIRONMENT

EXPOSE 3005

**Comment by flouthoc** [comment]
So in you first screenshot base image was `localhost/particle-node-server:latest` and here its `FROM node:16.16.0-alpine3.16` could you time with base as `FROM node:16.16.0-alpine3.16` ?

**Comment by GDdark** [comment]
Both are very slow

I started with Node:16
Later, I thought it was an image problem, so I changed it to the local image and tried it
The results were still slow

**Comment by GDdark** [comment]
![image](https://user-images.githubusercontent.com/15982894/186588129-21a55a65-495b-4c7e-91e9-4fba20cc8063.png)

I found something
It's while I'm waiting for the build output
htop shows that the build process consumes a lot of CPU resources
It's definitely been dealing with something all the time

**Comment by GDdark** [comment]
![image](https://user-images.githubusercontent.com/15982894/186589388-ac6f9d23-1353-40f0-9bd7-50ecef174ea2.png)

I found that this process appears along with the build process
Does it have to do with this?

**Comment by GDdark** [comment]
![image](https://user-images.githubusercontent.com/15982894/186590244-b37fd12d-8deb-4578-b9b3-88c9c371119b.png)

I build with node:16 again.
This time it was a little faster, and waiting for output took most of the time
It ends quickly after the appearance of the output, probably because of caching issues

**Comment by flouthoc** [comment]
You can run with `podman build --no-cache -t particle-node-server .`  to avoid using cache and then check. I think if other containerfile are working fine and only this one is slow then maybe its just that steps in `Containerfile` are expensive.

Its stuck on starting cause you get complete response from server when its done building, `podman` on `macOS` is not same as `podman` on linux it uses a client-server model so I think you only get response on your screen when entire build is completed.

I think its just that steps in you Containerfile are expensive and you get final response on screen when entire build is completed

**Comment by flouthoc** [comment]
You can try with some other Containerfile which writes files inside container and verify the same
```Dockerfile
FROM alpine
RUN echo hello > hello
```
vs
In this case entire output should be 60s delayed however on linux you will see each step on build logs as they are executed.
```Dockerfile
FROM alpine
RUN sleep 60s
```

Could you run two samples above and verify my hypothesis and then we can close this issue if you are convinced.

**Comment by GDdark** [comment]
![image](https://user-images.githubusercontent.com/15982894/186599336-44ee2ee4-d7aa-487c-bd1b-7c0ef90c2886.png)

I tried.
Both outputs appear immediately after executing the command
This is not the same as my project

**Comment by GDdark** [comment]
![image](https://user-images.githubusercontent.com/15982894/186600230-d5e2346e-7842-4e2f-a7c0-bb055775f7b5.png)

I have new discoveries
I changed dockerfile very simply
In other folders build is very fast
It runs very slowly under my project

**Comment by flouthoc** [comment]
I think i got the issue, if i re-call correctly the current context dir is tarred up and copied to remote server, is your project directory too big in size ?

**Comment by GDdark** [comment]
![image](https://user-images.githubusercontent.com/15982894/186601709-9b8cfc13-b785-4790-99c3-9b20decf7894.png)

Yes my entire project size is 4G
But the file I want to copy is very small

**Comment by GDdark** [comment]
You reminded me
I created the .dockerignore
Ignore some large folders
Build gets faster

**Comment by flouthoc** [comment]
> You reminded me I created the .dockerignore Ignore some large folders Build gets faster

Since this looks resolved hence closing this issue :), feel free to re-open.

**Comment by GDdark** [comment]
Thanks

**Comment by heyheyhello** [comment]
> re-call correctly the current context dir is tarred up and copied to remote server

@flouthoc Is this copy using the same subsystem as podman does for volume mounting? The qemu 9p virtfs subsystem. I just opened #16994 where I've seeing 45MB takes 1m30s to copy - maybe this slowness could be more heavily documented as a footgun if it is indeed the same bottleneck issue.
