### ISSUE TITLE
"Ignoring global metacopy option, not supported with booted kernel"

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#15488]
Seen twice this month, ubuntu root only:
```
# podman something
time="2022-08-23T09:23:53Z" level=warning msg="Ignoring global metacopy option, not supported with booted kernel"
```
When this happens, a ton of tests fail.

* ubuntu-2204 : sys podman ubuntu-2204 root host
  * PR #15372
    * [08-23 05:27](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5502323295256576/html/sys-podman-ubuntu-2204-root-host.log.html#t--00322)
  * PR #15319
    * [08-15 09:34](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6130695616593920/html/sys-podman-ubuntu-2204-root-host.log.html#t--00322)

Seems likely to be a system problem, i.e., the Ubuntu VM booted up in some broken manner. Filing as a placeholder but I have no time to poke into Cirrus VMs right now.

**Comment by edsantiago** [comment]
Another one, [f36 aarch64 root](https://api.cirrus-ci.com/v1/artifact/task/5454174631493632/html/sys-podman-fedora-36-aarch64-root-host.log.html)

**Comment by edsantiago** [comment]
[f36 root again](https://api.cirrus-ci.com/v1/artifact/task/4887563923095552/html/sys-podman-fedora-36-root-host.log.html)

**Comment by edsantiago** [comment]
Big flake trio just now, [f36 x86](https://api.cirrus-ci.com/v1/artifact/task/5247040606175232/html/sys-podman-fedora-36-root-host.log.html), [f36 aarch64](https://api.cirrus-ci.com/v1/artifact/task/5420741767200768/html/sys-podman-fedora-36-aarch64-root-host.log.html), and [ubuntu 2204](https://api.cirrus-ci.com/v1/artifact/task/5758832465936384/html/sys-podman-ubuntu-2204-root-host.log.html), all root, all failed on rerun.

**Comment by edsantiago** [comment]
Real flake here: [f36 aarch64 root](https://api.cirrus-ci.com/v1/artifact/task/5626854764707840/html/sys-podman-fedora-36-aarch64-root-host.log.html#t--00324). Begins in **test 324**, "sensitive mount points are masked without --privileged". All tests ran fine up to that point, all tests failed after that point.

**Comment by edsantiago** [comment]
The common factor is that things first go bad in this test: https://github.com/containers/podman/blob/6d8bafe57a65970ead17a83cb1983629b3a2aedb/test/system/400-unprivileged-access.bats#L104

The problem could be triggering there, or in an earlier test. (Definitely not the `podman container storage is not accessible by unprivileged users` test, because that one is skipped on Ubuntu, and we see this flake on Ubuntu). I've been running the 320, 330, and 400 tests in a loop on my f36 laptop, and have not been able to reproduce the flake.

**Comment by Ji993** [comment]
I also experienced a similar issue.
To replicate:
1. Uncomment `mount_program = "/usr/bin/fuse-overlayfs"` in /etc/containers/storage.conf
2. podman container run -d -it <<some_image>>
3. Now every time you do a run or some other container-related operation you will keep getting the warning message "WARN[0000] Ignoring global metacopy option, not supported with booted kernel"

Resolution:
1. Comment the `# mount_program = "/usr/bin/fuse-overlayfs"` in /etc/containers/storage.conf
2. yum remove podman
3. rm -rf /run/containers /var/lib/containers
4. yum install podman

OS: RHEL 9.1
Kernel: 5.14.0-162.6.1.el9_1.x86_64

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
it is fixed upstream with https://github.com/containers/storage/commit/c267eed6a5dff379cfb4e3d0d3ee824a1ec1f7db

that was vendored by eb28a1c08469d56494006d0f2c64933ab7078d01
