### ISSUE TITLE
Impossible to use `v4/cmd/podman/registry` Golang package on OS X

### ISSUE THREAD

**Issue by Sitin** [containers/podman#15509]
I am using the latest Podman for OS X:

```shell
#podman -v
podman version 4.2.0
```

A simple program that tries to get Podman info similar to the [`podman-info`](https://github.com/containers/podman/blob/main/cmd/podman/system/info.go):

```go
package main

import (
	"github.com/containers/podman/v4/cmd/podman/registry"
)

func main() {
	registry.IsRemote()
}
```

fails to build:

```
package podmantest
	imports github.com/containers/podman/v4/cmd/podman/registry
	imports github.com/containers/podman/v4/pkg/domain/infra
	imports github.com/containers/podman/v4/libpod
	imports github.com/containers/common/libnetwork/cni: build constraints exclude all Go files in <my system path>/go/pkg/mod/github.com/containers/common@v0.49.1/libnetwork/cni
package podmantest
	imports github.com/containers/podman/v4/cmd/podman/registry
	imports github.com/containers/podman/v4/pkg/domain/infra
	imports github.com/containers/podman/v4/libpod
	imports github.com/containers/common/libnetwork/network: build constraints exclude all Go files in <my system path>/go/pkg/mod/github.com/containers/common@v0.49.1/libnetwork/network
```

To recreate program dependencies:

```shell
go get github.com/containers/podman/v4 
go mod tidy
```

From a brief inspection it seems that there are no Darwin implementation for [github.com/containers/common/libnetwork/network](https://github.com/containers/common/tree/main/libnetwork/network).

I am wondering, how the OS X version of Podman CLI is even built?

**Comment by baude** [comment]
Podman on Macs and Windows are Podman *clients* that interact with a remote Podman.  For example, the podman client on the mac can do a `podman machine init --now` and then interact with podman on the virtual machine.  Most internal podman code only can be compiled and run on Linux.

**Comment by Sitin** [comment]
I aware about such limitation. However, `github.com/containers/podman/v4/cmd/podman/registry` is a part of the API client. And from my perspective it should work on any machine where Podman can be installed.

**Comment by afbjorklund** [comment]
Compiling "podman-remote" requires a special build flag

**Comment by Sitin** [comment]
@afbjorklund, is there any way to make `github.com/containers/podman/v4/cmd/podman/registry` Go library work on OS X?

**Comment by Sitin** [comment]
I still believe this is a defect. This package returns Podman system information and is essential to writing cross-platform tools that use Podman as a runtime for local services. At the moment I have to parse whatever `podman info` returns to me.

**Comment by afbjorklund** [comment]
Podman is a Linux tool, it is not cross-platform. You can access it remotely (from all platforms), but that's a different story...

For this particular piece of the code, there is a "mode" that tells if it is running locally (ABIMode) or remotely (TunnelMode).

**Comment by afbjorklund** [comment]
There are also a bunch of other secret flags, you can find them by doing `make podman-remote` or similar.

`go build -tags "remote exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper containers_image_openpgp"`

**Comment by vrothberg** [comment]
Yes, using the bindings is the recommended way to interact with Podman programmatically in Go.  `pkg/bindings` was designed to be easy to use and work cross-platform.  Other Go packages in the stack were not necessarily designed in a way to be used outside of podman.

**Comment by afbjorklund** [comment]
The main reason to consider docker was to get a stable API, but I think this is being considered for Podman v5 ?

**Comment by baude** [comment]
> The main reason to consider "docker" (compat) was to get a stable API, but I think this is being considered for Podman v5 ?

What do you mean @afbjorklund ?

**Comment by afbjorklund** [comment]
I meant that if you target Podman v4 API today, it should remain compatible also with Podman v5 ?
