### ISSUE TITLE
machine init: setting security_model not working with MacOS 

### ISSUE THREAD

**Issue by hcbraun** [containers/podman#15519]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When initializing a machine for MacOS the security_model option is ignored.

**Steps to reproduce the issue:**

1. podman machine init --volume="$HOME:$HOME:security_model=passthrough" --image-path=stable

2. 

3.

**Describe the results you received:**

Configuration file contains default security_model settings:
```
"CmdLine": [
  "/opt/homebrew/bin/qemu-system-aarch64",
  ...
  "-virtfs",
  "local,path=/Users/xxx,mount_tag=vol0,security_model=mapped-xattr",
```

**Describe the results you expected:**

`security_model=passthrough` should be set in the configuration file

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 4.2.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
brew info podman
==> podman: stable 4.2.0 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/opt/homebrew/Cellar/podman/4.2.0 (178 files, 48MB) *
  Poured from bottle on 2022-08-11 at 08:15:18
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0
==> Dependencies
Build: go-md2man ✘, go@1.18 ✘
Required: qemu ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@baude @ashley-cui PTAL

**Comment by baude** [comment]
I have no idea what is being asked for here.  @hcbraun can you please elaborate ?

**Comment by hcbraun** [comment]
Thanks for looking at this, @baude !

See the man page for podman-machine-init under --volume there is an option to set the security_model. I want to use this option but setting it has no effect. What I gathered from debugging, is that the option should change the "CmdLine" in the configuration file of the podman machine which starts QEMU. Though that is not happening. Regardless of what I initialize the machine with, the security_model is always set to mapped-xattr in the configuration file.

A trivial work-around is to just edit the security_model option in the configuration file. QEMU than starts with the correct security_model and using the passthrough option then works.

**Comment by rhatdan** [comment]
@ashley-cui PTAL

**Comment by ashley-cui** [comment]
Looks like this has been fixed in the meantime.
