### ISSUE TITLE
Unable to use --secrets with containers that are running --read-only

### ISSUE THREAD

**Issue by joelika** [containers/podman#15541]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman is unable to mount a secret if the container is running as read-only

**Steps to reproduce the issue:**

1. printf "mysecret" | podman secret create mysecret -

2. podman run --read-only --secret mysecret registry.access.redhat.com/ubi8/ubi-minimal

**Describe the results you received:**

Error: OCI runtime error: runc: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/opt/containers/storage/overlay-containers/698d27cb4b2a33b13d321c5b203099f126a15afdca6afac01a389381446d9646/userdata/secrets/mysecret" to rootfs at "/run/secrets/mysecret" caused: open /opt/containers/storage/overlay/5917e60be1609d6560c85ac421e577a0d5e7545e202e030b9d3cb5c0c4b88842/merged/run/secrets/mysecret: read-only file system

**Describe the results you expected:**

Podman should start the container with the secret.

**Additional information you deem important (e.g. issue happens only occasionally):**

As a work around, if I create a volume for /run/secrets, then I can pass the secret into the read-only container.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.17.7
Built:        Mon Jul 11 10:56:53 2022
OS/Arch:      linux/amd6
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.2
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.0-1.module+el8.6.0+14877+f643d2d6.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 87b7a9037cbd1d81288bdf2d6705dfda889f7cf9'
  cpuUtilization:
    idlePercent: 69.66
    systemPercent: 6.68
    userPercent: 23.66
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "8.6"
  eventLogger: file
  hostname: [pghwcmstageauth2.rand.org](http://pghwcmstageauth2.rand.org/)
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-372.19.1.el8_6.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 1457860608
  memTotal: 25159385088
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.0.3-2.module+el8.6.0+14877+f643d2d6.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.3
      spec: 1.0.2-dev
      go: go1.17.7
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.1.8-2.module+el8.6.0+14877+f643d2d6.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 2051915776
  swapTotal: 12884897792
  uptime: 259h 56m 32.21s (Approximately 10.79 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - [registry.fedoraproject.org](http://registry.fedoraproject.org/)
  - [registry.access.redhat.com](http://registry.access.redhat.com/)
  - [registry.centos.org](http://registry.centos.org/)
  - [docker.io](http://docker.io/)
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 8
    paused: 0
    running: 6
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /opt/containers/storage
  graphRootAllocated: 1098972663808
  graphRootUsed: 597396271104
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 84
  runRoot: /var/run/containers/storage
  volumePath: /opt/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1657551413
  BuiltTime: Mon Jul 11 10:56:53 2022
  GitCommit: ""
  GoVersion: go1.17.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.1.1-2.module+el8.6.0+15917+093ca6f8.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

I looked at troubleshooting and change logs. I'm not able to use a newer version of podman 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VM running as part of a corporate environment

**Comment by vrothberg** [comment]
Thanks for reaching out!

**Comment by giuseppe** [comment]
I think it is a limitation/issue in runc.

Could you try if it works using crun `podman --runtime crun run --read-only --secret mysecret registry.access.redhat.com/ubi8/ubi-minimal`?

**Comment by joelika** [comment]
@giuseppe I just tested using crun, and yes, it worked as expected and the secret was mounted into the container without a runtime exception.

**Comment by giuseppe** [comment]
thanks for confirming it.  You may want to report the issue upstream to runc, but I don't think there is anything Podman can do, the generated configuration file passed to runc looks correct to me.

**Comment by joelika** [comment]
@giuseppe FWIW, if I do the same in a docker-compose file, I can pass in a secret to read-only container. So that's why I was surprised I ran into an issue with Podman.

**Comment by rhatdan** [comment]
@AkihiroSuda @kolyshkin PTAL
