### ISSUE TITLE
Add "--preserve-digest" option to podman push

### ISSUE THREAD

**Issue by StarpTech** [containers/podman#15544]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

When running `podman build` and `podman push` multiple times, layers are modified and pushed to the registry even when the image hasn't changed or in other terms was fully cached. To avoid changing digests containers/storage introduce the `--preserve-digest` flag. See https://github.com/containers/image/pull/1413 I'd like to add this flag to the `podman push` command

**Describe the results you expected:**

See https://github.com/containers/podman/discussions/15538

https://github.com/containers/podman/blob/main/pkg/domain/infra/abi/images.go#L285

**Comment by mheon** [comment]
@flouthoc PTAL

**Comment by rhatdan** [comment]
Since we are not going to work on this issue, closing.

**Comment by mtrmac** [comment]
FWIW:

> The directions to investigate from [#15538 (reply in thread)](https://github.com/containers/podman/discussions/15538#discussioncomment-3511821) would help this case, _and_ other cases:
> 
> * For some historical reason, we disable HTTP keep-alive

This is no longer the case.

Also, unfinished https://github.com/containers/image/pull/1968 might reduce the number of necessary round-trips, by up to about a third for images with several but not too many layers.
