### ISSUE TITLE
"Podman pod logs --latest" doesn't work.

### ISSUE THREAD

**Issue by fhwsuper** [containers/podman#15556]
Ubuntu Linux 20.04, Podman 4.2.0
This issue also can be found in Podman 4.1.0, & Podman 3.4.4

./podman pod logs -l
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/containers/podman/v4/cmd/podman/pods.logs(0x240ad20?, {0xc0002aa450, 0x0, 0x1?})
	/home/fanhuawei/podman/podman-4.2.0/cmd/podman/pods/logs.go:124 +0x3d9
github.com/spf13/cobra.(*Command).execute(0x240ad20, {0xc00009e070, 0x1, 0x1})
	/home/fanhuawei/podman/podman-4.2.0/vendor/github.com/spf13/cobra/command.go:872 +0x694
github.com/spf13/cobra.(*Command).ExecuteC(0x2412520)
	/home/fanhuawei/podman/podman-4.2.0/vendor/github.com/spf13/cobra/command.go:990 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/fanhuawei/podman/podman-4.2.0/vendor/github.com/spf13/cobra/command.go:918
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/fanhuawei/podman/podman-4.2.0/vendor/github.com/spf13/cobra/command.go:911
main.Execute()
	/home/fanhuawei/podman/podman-4.2.0/cmd/podman/root.go:99 +0xc5
main.main()
	/home/fanhuawei/podman/podman-4.2.0/cmd/podman/main.go:40 +0x7c

**Comment by vrothberg** [comment]
Thanks for reaching out!  I can reproduce as well.

**Comment by fhwsuper** [comment]
This is a workaround. 
1. change second argument "nameOrID "to an array.  
2. Only get pod[0].ID() from func getPodsByContext() and then invoke when options.Latest = false
I suppose other fileds of Pod struct have some problems when invoke getPodsByContext() with options.Latest = true.

Second method: you could consider move nameOrID into struct PodLogsOptions, like pod inspect -l, pod top -l. 

func (ic *ContainerEngine) PodLogs(ctx context.Context, nameOrID []string, options entities.PodLogsOptions) error {
	// // Implementation accepts slice
	// //podName := []string{nameOrID}	

	var pod []*libpod.Pod
	var err error

	if options.Latest {
		pod, err = getPodsByContext(false, options.Latest, nameOrID, ic.Libpod)
		if err != nil {
			return err
		}
	
		options.Latest = false
		podID := []string{pod[0].ID()}
	        pod, err = getPodsByContext(false, options.Latest, podID, ic.Libpod)
		if err != nil {
			return err
		}
.......

**Comment by jakecorrenti** [comment]
I can give this one a shot while I work on the conmon-rs stuff

**Comment by vrothberg** [comment]
> I can give this one a shot while I work on the conmon-rs stuff

Awesome! Thanks a lot, @jakecorrenti

**Comment by boaz0** [comment]
Hi @jakecorrenti I think I found the problem. Can I work on it? Or you are in a middle of finishing it.
Let me know. Thanks.
If you need help let me know, I don't mind giving you a hint.

**Comment by jakecorrenti** [comment]
> Hi @jakecorrenti I think I found the problem. Can I work on it? Or you are in a middle of finishing it.
> 
> Let me know. Thanks.
> 
> If you need help let me know, I don't mind giving you a hint.

Hey, I'm still working on it. Had my first week back at school last week so just had to find my groove. I plan on trying to finish today. I'll let you know if I want to pass it off!

**Comment by rhatdan** [comment]
Excellent.

**Comment by jakecorrenti** [comment]
Just want to confirm that the expected output here (based on the documentation of `podman pod logs -l`) is going to be the same as `podman logs -l`?

**Comment by rhatdan** [comment]
Not sure what the question is, `podman pod logs -l` should show the logs of the last created pod, same as if  you specified
podman pod logs PODID

**Comment by rhatdan** [comment]
Yes, The use case where this would differ would be if the Pod is older then the latest container and if the Pod contained more then one container.

If latest pod contained only latest container, then they would be the same.

**Comment by jakecorrenti** [comment]
Looks to me like the `ignore` argument to this function is most likely the issue. Changing it to false makes `pod logs -l` work but not `podman logs -l` (just prints blank). Could I get some clarification on the what this argument is for? https://github.com/containers/podman/blob/8f76bc2d739657cf4394cb4d08f314011ba08dab/pkg/domain/infra/tunnel/helpers.go#L15-L25
