### ISSUE TITLE
Getting error message about gcloud.auth.docker-helper when running podman run on macOS

### ISSUE THREAD

**Issue by jamesmortensen** [containers/podman#15563]
BUG REPORT

/kind bug

**Description**

podman run returns an error message about gcloud-auth-docker-helper and the credentials being expired.  I believe these credentials are needed when pushing a built container image to a Google Cloud Platform Artifact registry, but that should only be an issue if I'm actually attempting to push an image to a GCP registry.  I don't plan to push any images for some time, so I don't really think I should be required to re-authenticate here.

**Steps to reproduce the issue:**

1.  `podman machine start`

2.  `podman run --rm -it debian:latest bash`

**Describe the results you received:**

```
ERROR: (gcloud.auth.docker-helper) There was a problem refreshing your current auth tokens: ('invalid_grant: Token has been expired or revoked.', {'error': 'invalid_grant', 'error_description': 'Token has been expired or revoked.'})
Please run:

  $ gcloud auth login

to obtain new credentials.

If you have already logged in with a different account:

    $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
Error: 1 error occurred:
	* error getting credentials - err: exit status 1, out: ``
```

**Describe the results you expected:**

I expected to land in a bash shell in a running container.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
```
$ podman -v
podman version 4.2.0
```

**Output of `podman info`:**

```
$ podman info
host:
  arch: arm64
  buildahVersion: 1.27.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc36.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpuUtilization:
    idlePercent: 99.46
    systemPercent: 0.39
    userPercent: 0.14
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "36"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 502
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 5.18.18-200.fc36.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 1656672256
  memTotal: 2051895296
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.fc36.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/502/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.aarch64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 43m 52.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 0
    stopped: 7
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106825756672
  graphRootUsed: 5747658752
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 8
  runRoot: /run/user/502/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1660228991
  BuiltTime: Thu Aug 11 20:13:11 2022
  GitCommit: ""
  GoVersion: go1.18.4
  Os: linux
  OsArch: linux/arm64
  Version: 4.2.0
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is run locally on macOS M1 12.4 using what I believe is referred to as podman-remote.

**Comment by mheon** [comment]
@baude PTAL - we don't use gcloud in `podman machine`, right?

**Comment by jamesmortensen** [comment]
I apologize for not having more definitive information, but to the best of my knowledge, I've only built and pushed images to the GCP artifact registry using the docker CLI, never podman.  If there's any other data I can get that could help debug this, please let me know.

**Comment by jamesmortensen** [comment]
The workaround I can use is to start the container from within the Fedora VM:

```
$ podman machine ssh
Connecting to vm podman-machine-default. To close connection, use `~.` or `exit`
Fedora CoreOS 36.20220820.2.0
Tracker: https://github.com/coreos/fedora-coreos-tracker
Discuss: https://discussion.fedoraproject.org/tag/coreos

Last login: Wed Aug 31 19:49:18 2022 from 192.x.x.x
[core@localhost ~]$ podman run --rm -it ubuntu:latest bash
root@1f0058df43dc:/# cat /etc/issue
Ubuntu 22.04.1 LTS \n \l

root@1f0058df43dc:/#
```

Hope this helps.

**Comment by rhatdan** [comment]
@mtrmac @vrothberg PTAL

**Comment by mtrmac** [comment]
`podman run` can, in principle, pull images (depending on the `--pull` option), and IIRC for the _remote_ operation we need to list all credentials and forward them to the remote server. The way that currently works, we currently always trigger a “pull” operation on the server, and always send the full set of credentials to the server — letting the server make all the policy decisions.

It would, probably, be possible to change the remote API to avoid the need to collect credentials if the server ends up not needing to actually pull anything; that would be a somewhat intrusive change, and require tighter coordination between the clients’ and servers’ understanding of the policy and of the image store.

**Comment by kybercryst4l** [comment]
With google SDK installed and docker creadential-helpers configured with `gcloud auth configure-docker`, `podman run` tried to use gcloud credentials. After removing credential-helpers from `$HOME/.docker/config.json`, `podman run` is working again.

**Comment by rhatdan** [comment]
I believe this is no longer an issue, closing.
