### ISSUE TITLE
when installing using podman-v4.1.1 and also 4.2.x latest version same issue

### ISSUE THREAD

**Issue by nagkumar** [containers/podman#15561]
Install error

![image](https://user-images.githubusercontent.com/332234/187659571-9630e90f-291e-4358-83f8-cb3965b7ac53.png)

I am on windows 10

**Comment by vrothberg** [comment]
Thanks for reaching out. Could an anti-virus tool be blocking the installation?

Cc: @n1hility

**Comment by n1hility** [comment]
There is a good chance this is the case. @nagkumar are you running a thirdparty ML based virus scanner like Falcon? Do you have the ability to add this to an allow list?

**Comment by nagkumar** [comment]
No, I only have Windows Security

![image](https://user-images.githubusercontent.com/332234/188645154-21f14902-b293-446a-9030-59fc1d753d29.png)

**Comment by vrothberg** [comment]
Thanks, @nagkumar.  Can you try disabling it and install again?  Just to be extra sure.  Maybe it set Podman on a deny list.

**Comment by nagkumar** [comment]
same error..

![image](https://user-images.githubusercontent.com/332234/188652988-563bf873-267f-453f-929d-4e28c6b6a2e7.png)
![image](https://user-images.githubusercontent.com/332234/188653058-19e465dd-baf3-4313-a57a-8aa1cfeddad4.png)

**Comment by n1hility** [comment]
@nagkumar could you run this with logging and post the results to a gist you could link:

msiexec /i podman-v4.2.0-dev.msi /l*v installlog.txt

Thanks!

**Comment by n1hility** [comment]
This should be resolved with our move to the signed installer in 4.3 (to be releaseed soon), which replaces the unsigned msi
