### ISSUE TITLE
Support for signing and verification of "docker-archive" tarball file

### ISSUE THREAD

**Issue by startemplar** [containers/podman#15570]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Would like to check if podman supports signing and verifying "docker-archive" tarball file and if not, any way to do that? Due to some reason, we cannot use container registry and have to export container image as docker-archive tarball and move them around. We are following https://github.com/containers/podman/blob/main/docs/tutorials/image_signing.md, however, seems it only supports podman push --sign-by <gpg key email> image:tag to image registry, once I use "podman push --sign-by <gpg key email> image:tag docker-archive:/tmp/image", it throws ""Cannot determine canonical Docker reference for destination docker-archive:/tmp/image". seems related to https://github.com/containers/podman/blob/main/vendor/github.com/containers/image/v5/copy/sign.go#L58, if we don't use image registry, is there any way to support image signing and verification and what is your suggested approach? Thank you.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
3.4.2

**Comment by mheon** [comment]
@mtrmac PTAL

**Comment by mtrmac** [comment]
It’s impossible, the `docker-archive` format can’t carry the information required for the current signature concept. Besides not having a way to record signatures, it doesn’t have a manifest to sign; there just isn’t any way to transfer a bit-by-bit identical copy of an image using the docker-archive transport, and the bit-by-bit identical copy is what would need to exist for it to be signed.

You can use the `dir` transport to transfer a single image. (Short-term, within somewhat close versions of tools; it’s not really designed as a long-term archival format).

For anything larger-scale I recommend:
- on the source, temporarily run a registry container, with the backing storage mounted into the container as a volume
- do a registry-to-registry copy of the images to that temporary registry
- stop the registry, and archive the storage volume contents, along with lookaside-pending (sigstore-pending) directory structure containing the signature
- transfer that archive around
- on the recipient, temporarily run a registry container, with the backing storage mounted into the container as a volume
- do a registry-to-registry copy of the images from that temporary registry to the final destination
- publish the lookside-pending data on the lookaside web server.

Using a temporary registry this way allows benefiting from the existing cross-image data sharing, and operation parallelism, implemented for registry accesses. And it’s going to be _quite noticeably_ faster than anything involving `docker-archive`.

**Comment by startemplar** [comment]
Thank you, @mtrmac for your suggestion. Would like to check if you see issue or risk in the following process. Thank you
1. Use podman save to docker-archive/tarball file
2. Generate hash1 for the docker-archive/tarball file (e.g. with md5sum)
3. Before podman load docker-archive/tarball file on target machine, compute hash2 and compare with the original hash1 to check docker-archive/tarball file has changed.

**Comment by mtrmac** [comment]
Well, SHA256 instead of broken MD5.

Sure, that’s viable _for what it does_: it doesn’t allow maintaining an end-to-end signature from the original image producer across such a transport mechanism.

**Comment by startemplar** [comment]
Thank you, @mtrmac for your thoughts.

**Comment by vrothberg** [comment]
Closing as outlined above (see https://github.com/containers/podman/issues/15570#issuecomment-1233200869).
