### ISSUE TITLE
How to install podman as a service in MAC OS Server

### ISSUE THREAD

**Issue by Taymindis** [containers/podman#15579]
Whenever the MACOS server restarted, the podman need to manually start again via command

```bash
podman machine start

```

Can I install as a brew service which able to start/stop? how can i do that?

**Comment by vrothberg** [comment]
Thanks for reaching out, @Taymindis.

I'll ping the Mac OS experts who may know how to do that. @ashley-cui @benoitf @baude @rhatdan @gbraad

**Comment by gbraad** [comment]
Thank you for the heads up. There are several ways this can be approached: let podman desktop handle this by means of the tray visibility, or set up a wya for podman itself to handle this.

**Comment by vrothberg** [comment]
@gbraad, thanks!  It sounds nice to have Podman handle it and let Podman-Desktop use it?

On Linux, I'd just use systemd for it :^)

**Comment by gbraad** [comment]
On macos we can use launchd, however the model for windows would be slightly more involved. Centralizing this responsibility in podman sounds better to me to, as that allows Desktop to only handle a flag for containers, instead of the initialization of the engine.

**Comment by benoitf** [comment]
On Podman Desktop, on macOS, we'll allow to launch Podman machine each time we launch Podman Desktop (same lifecycle. So quite easy to start as you just click on an icon and see status/etc).
And next, to allow to Start Podman Desktop on every start. (so by mixing all options you can achieve what you want).

**Comment by rhatdan** [comment]
@n1hility @benoitf @gbraad what is the state of this now?

**Comment by benoitf** [comment]
Podman Desktop has a PR about that https://github.com/containers/podman-desktop/pull/510

ie: start Podman Desktop (that starts Podman Machine) on boot for macOS

**Comment by n1hility** [comment]
Handled by  https://github.com/containers/podman-desktop/issues/225
