### ISSUE TITLE
Regression in podman 4.3.0-dev connection on windows (ssh handshake fails)

### ISSUE THREAD

**Issue by arixmkii** [containers/podman#15585]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman remote on windows stopped working w/o modifying known_hosts file on Windows platform somewhere in 4.3.0-dev. 4.2.0 works as expected

**Steps to reproduce the issue:**

1. Install latest podman 4.2.0 msi

2. create default WSL machine and start it

3. Build locally podman-remote 2 times - one from v4.2.0 tag and one from main HEAD.

4. Remove podman binary from installer (or rename to .bak)

5. Run `podman ps` for both self compiled binaries

```bat
C:\Users\User>podman-4.2.0 ps
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES

C:\Users\User>podman-4.3.0-dev ps
Error: failed to connect: ssh: handshake failed: knownhosts: key is unknown
```

**Describe the results you received:**

```
Error: failed to connect: ssh: handshake failed: knownhosts: key is unknown
```

For binary compiled from main HEAD

**Describe the results you expected:**

The same as for one built from tag
```
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
```

Discovered as part of this experiment https://github.com/containers/podman/issues/13006 but is reproducible for the unmodified podman installation with default feature set.

**Additional information you deem important (e.g. issue happens only occasionally):**

The workaround is to manually add records to trusted hosts. In details described here https://github.com/arixmkii/qcw#2-machine-keys-are-not-added-to-known_hosts-by-default

**Output of `podman version`:**

4.2.0
```
C:\Users\User>podman-4.2.0 version
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18
Git Commit:   7fe5a419cfd2880df2028ad3d7fd9378a88a04f4
Built:        Thu Sep  1 13:57:12 2022
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.4
Built:        Thu Aug 11 17:42:17 2022
OS/Arch:      linux/amd64
```

4.3.0-dev version output  fails due to ssh as well.

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes. Both versions built from sources.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows WSL2

**Comment by arixmkii** [comment]
Please remove feature label. Didn't notice it, while creating issue on my test laptop (to get command output added to the description).

**Comment by mheon** [comment]
@n1hility PTAL

**Comment by n1hility** [comment]
Thanks for the report, sounds like this is likely  related to the new ssh work here:
https://github.com/containers/podman/pull/15094

**Comment by n1hility** [comment]
FYI @baude @ashley-cui @jwhonce. The new stricter approach in #15094 with host key validation probably breaks podman machine since its normal for the machine identify to change as people machine rm/machine init. Not sure if you guys looked at this yet, but I am guessing we should update client server known host keys as part of machine init

**Comment by cdoern** [comment]
@n1hility I have a few PRs in flight to fix the key validation:

containers/common#1136 and #15471. The changes breaking this did not make it into 4.2 so this will be fixed by next major release.

**Comment by n1hility** [comment]
@cdoern great thanks!

**Comment by Qix-** [comment]
Was experiencing this as recently as 4.3.0-rc1. Can confirm that upgrading to 4.3.0 fixed this for me on MacOS. Thanks for the fix!
