### ISSUE TITLE
Podman remote fails to connect over SSH on v4, CentOS 9

### ISSUE THREAD

**Issue by LewisGaul** [containers/podman#15598]
/kind bug

**Description**

Podman remote fails to connect over SSH on v4, CentOS 9.

**Steps to reproduce the issue:**

1. Install podman on CentOS 9: `dnf install -y podman`
2. Start systemd unit: `systemctl start podman.socket`
3. Add remote connection: `podman -r system connection add local ssh://localhost/run/podman/podman.socket --identity ~/.ssh/id_ed25519`
4. Try to connect using podman remote: `podman -r -c local images`

**Describe the results you received:**

Error from podman:
```
[root@localhost ~]# podman -r -c local images
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: connection to bastion host (ssh://root@localhost:22/run/podman/podman.sock) failed: ssh: handshake failed: EOF
```

**Describe the results you expected:**

Successful connection.

**Additional information you deem important (e.g. issue happens only occasionally):**

- The above (connecting over localhost) is only intended as a minimal example - of course in reality I'm actually trying to connect across hosts.
- Confirmed regular ssh is working with the same ssh key.
- Confirmed `podman.socket` is active and using `/run/podman/podman.socket`.
- The same setup works on Ubuntu (18.04, 20.04, 22.04) with podman v3 and CentOS 8 with podman v3.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.1.0
API Version:  4.1.0
Go Version:   go1.17.5
Built:        Wed May 25 03:40:16 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.3-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.3, commit: 8d561e47dd44c98c15c24a5e16aa1fc187df1b75'
  cpuUtilization:
    idlePercent: 96.98
    systemPercent: 2.37
    userPercent: 0.66
  cpus: 6
  distribution:
    distribution: '"centos"'
    version: "9"
  eventLogger: journald
  hostname: localhost
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.0-80.el9.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 3434250240
  memTotal: 5943554048
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.el9.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 0
  swapTotal: 0
  uptime: 1m 3.33s
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 53675536384
  graphRootUsed: 1715613696
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.1.0
  Built: 1653464416
  BuiltTime: Wed May 25 03:40:16 2022
  GitCommit: ""
  GoVersion: go1.17.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.1.0-4.el9.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes, confirmed with v4.1.0 and v4.2.0.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

QEMU VM, image created using cloud-init.

**Comment by cdoern** [comment]
just a usage question: why do you need to add a connection for localhost when you can just curl the socket manually? This might be a corner case I did not consider... However, this does not seem to be using the most recent ssh changes. 

Can you try building from the main branch?

**Comment by LewisGaul** [comment]
> just a usage question: why do you need to add a connection for localhost when you can just curl the socket manually? This might be a corner case I did not consider... However, this does not seem to be using the most recent ssh changes.

See my point in the description:
> The above (connecting over localhost) is only intended as a minimal example - of course in reality I'm actually trying to connect across hosts.

The issue is not confined to connecting over localhost.

> Can you try building from the main branch?

This isn't something I'm currently set up to do I'm afraid. If it's assumed fixed I'll have to wait and try the next release... Seems to have the issue for v4.1 and v4.2.0 though.

**Comment by cdoern** [comment]
@LewisGaul I have done a pretty extensive overhaul of podman's ssh handling, including adding a `--ssh=native` global flag to use openSSH rather than golang's package and `SSH_CONFIG`containers.conf entity to funnel the code in the right direction. I'll check out if this scenario works on main and get back to you. i am sure with one flag or another it will work.

**Comment by LewisGaul** [comment]
Interesting, ok. Is the default case likely to still simply not work though, requiring some custom flag/config?

**Comment by cdoern** [comment]
this is fixed by my currently in flight #15471

**Comment by LewisGaul** [comment]
Is this a testing gap with podman-remote/ssh? Currently unable to run against CentOS 9 with podman and having to revert to using docker, and I'm struggling to follow the chain of changes that caused the issue.

**Comment by cdoern** [comment]
@LewisGaul the issue you are facing is the reason I re-worked the ssh interface in podman. Golang's package is far behind the openSSH implementation. I fixed up the golang implementation and implemented a native one, we do have ssh tests though in the current version, I just do not think a podman-remote -> localhost connection was tested

**Comment by LewisGaul** [comment]
I've just tested this on Fedora 36 and cannot reproduce the issue with podman 4.2.0, so somehow this is specific to centos 9 and/or the environment.

Again, the issue I'm seeing on centos is not specific to the localhost connection, that was just a minimal reproduction of the issue.

Maybe there's some host SSH config preventing the connection podman tries to make? I'm just not sure how to debug that, given regular ssh connections work fine.
