### ISSUE TITLE
Podman-remote reading storage.conf on local host

### ISSUE THREAD

**Issue by LewisGaul** [containers/podman#15600]
/kind bug

**Description**

As raised in #14267, seeing a warning from podman-remote reading the local host's `storage.conf`, which happens to be for the host's podman at v1.6.4 and has an incompatible key:
```
WARN[0000] Failed to decode the keys ["storage.options.override_kernel_check"] from "/etc/containers/storage.conf".
```

According to https://github.com/containers/podman/issues/14267#issuecomment-1128700808:
> Why does podman-remote even read the storage.conf? It should not need it.

Note that the fix #1249 has made it possible to work around this issue by setting `CONTAINERS_STORAGE_CONF`, but it would be preferable if this workaround was no longer required.

**Steps to reproduce the issue:**

1. Set `storage.options.override_kernel_check = true in /etc/containers/storage.conf`
2. Run `podman-remote -v`

**Describe the results you received:**

Warning on every `podman-remote` invocation due to reading the old `/etc/containers/storage.conf` (unless overridden by the `CONTAINERS_STORAGE_CONF` env var).

**Describe the results you expected:**

No warning, since `podman-remote` has no need to read the local `storage.conf`.

**Output of `podman-remote --version`:**

```
podman-remote4.2 version 4.2.0
```

**Output of `podman info`:**

n/a

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

n/a

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Comment by mheon** [comment]
@ashley-cui PTAL

**Comment by rhatdan** [comment]
The issue here is podman loading the storage.conf initializer. This could be difficult to fix but should be a goal, in that it should shrink the size of podman.

**Comment by mulongfu** [comment]
v4.7.0-dev still has this problem.
`$ podman -v`

`WARN[0000] Failed to decode the keys ["storage.options.override_kernel_check"] from "/etc/containers/storage.conf"
podman version 4.7.0-dev`

**Comment by rhatdan** [comment]
We no longer support the override_kernel_check, so closing.
