### ISSUE TITLE
Man pages of service_destinations configuration out of date

### ISSUE THREAD

**Issue by iacore** [containers/podman#15615]
Current man pages says:

https://github.com/containers/podman/blob/2cc32742898843fc35d5aae3bf787f2221795735/docs/source/markdown/podman-remote.1.md#L73
https://github.com/containers/podman/blob/d0d1af338a500f2ad00d5ce0638901465602817d/docs/source/markdown/podman.1.md#L185

However, podman is using `[engine.service_destinations]` instead.

I found this problem using Arch Linux's podman package, where the default configuration is wrong.

Here's a part of `/usr/share/containers/containers.conf` on install:
```
# map of service destinations
#
#[service_destinations]
#  [service_destinations.production]
#     URI to access the Podman service
#     Examples:
#       rootless "unix://run/user/$UID/podman/podman.sock" (Default)
#       rootful "unix://run/podman/podman.sock (Default)
#       remote rootless ssh://engineering.lab.company.com/run/user/1000/podman/podman.sock
#       remote rootful ssh://root@10.10.1.136:22/run/podman/podman.sock
#
#    uri = "ssh://user@production.example.com/run/user/1001/podman/podman.sock"
#    Path to file containing ssh identity key
#    identity = "~/.ssh/id_rsa"
```

**Comment by rhatdan** [comment]
Pleas open a PR to fix.

**Comment by vrothberg** [comment]
@rhatdan ^

**Comment by rhatdan** [comment]
SGTM
