### ISSUE TITLE
docker-compose cannot pull images from authenticated private registry via tcp

### ISSUE THREAD

**Issue by Argelbargel** [containers/podman#15620]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm using podman 4.2.0 on windows/wsl (installed according [to the tutorial(https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md). Because of reasons based on our build-structure we're using a remote tcp instead of the socket when connecting docker-cli or docker-compose to podman (or formerly docker-engine). Thus i'm starting an additional instance of the podman-service listening on tcp via podman system service tcp:localhost:<port> -t 0

The images consumed and produced by our builds are stored in a private registry which is password protected.

When starting our containers using docker-compose it fails when it tries to pull a missing image from this registry even though authentication info is present in /run/user/<uid>/containers/auth.json after a successfull podman login. Running a remote pull using podman --url tcp://localhost:<port> pull <image> also works as expected.

**Steps to reproduce the issue:**

1. start a podman service listening to tcp (e.g. podman --log-level debug system service tcp:localhost:2375 -t 0)
2. create a docker-compose-file with an container build from an image in a password protected registry
3. run docker-compose up

**Describe the results you received:**

docker-compose up fails with the error-message  
initializing source docker://<registry>/<path>:<tag>: reading manifest latest in <registry>/<path>: unauthorized: unauthorized to access repository: <path>, action: pull: unauthorized to access repository: <path>, action: pull

**Describe the results you expected:**
docker-compose should pull the image as podman login was successfull

**Additional information you deem important (e.g. issue happens only occasionally):**
If ran the podman service with log-level debug and according to that the problem seems to be the credentials lookup is different for docker-compose up and e.g. podman -url <url> pull <image>

Log-Message when docker-compose up executes the pull:

```
DEBU[0036] Loading registries configuration "/etc/containers/registries.conf"
DEBU[0036] Loading registries configuration "/etc/containers/registries.conf.d/000-shortnames.conf"
DEBU[0036] Loading registries configuration "/home/user/.config/containers/registries.conf.d/<registry>.conf"
127.0.0.1 - - [02/Sep/2022:18:44:36 +0200] "GET /v1.41/info HTTP/1.1" 200 2338 "" "Docker-Client/unknown-version (linux)"
DEBU[0036] IdleTracker:idle 2m+0h/4t connection(s)       X-Reference-Id=0xc000010058
DEBU[0036] IdleTracker:active 2m+0h/4t connection(s)     X-Reference-Id=0xc000010058
DEBU[0036] Looking up image "<registry><path>:latest" in local containers storage
DEBU[0036] Normalized platform linux/amd64 to {amd64 linux  [] }
DEBU[0036] Trying "<registry><path>:latest" ...
DEBU[0036] Trying "<registry><path>:latest" ...
DEBU[0036] Trying "<registry><path>:latest" ...
DEBU[0036] Pulling image <registry><path>:latest (policy: always)
DEBU[0036] Looking up image "<registry><path>:latest" in local containers storage
DEBU[0036] Normalized platform linux/amd64 to {amd64 linux  [] }
DEBU[0036] Trying "<registry><path>:latest" ...
DEBU[0036] Trying "<registry><path>:latest" ...
DEBU[0036] Trying "<registry><path>:latest" ...
DEBU[0036] Normalized platform linux/amd64 to {amd64 linux  [] }
DEBU[0036] Attempting to pull candidate <registry><path>:latest for <registry><path>:latest
DEBU[0036] parsed reference into "[overlay@/home/user/.local/share/containers/storage+/run/user/1000/containers]<registry><path>:latest"
Trying to pull <registry><path>:latest...
DEBU[0036] Copying source image //<registry><path>:latest to destination image [overlay@/home/user/.local/share/containers/storage+/run/user/1000/containers]<registry><path>:latest
DEBU[0036] Using registries.d directory /etc/containers/registries.d
DEBU[0036] Trying to access "<registry><path>:latest"
DEBU[0036] No credentials matching <registry><path> found in /var/tmp/auth.json.2289411610
DEBU[0036] No credentials matching <registry><path> found in /home/user/.config/containers/auth.json
DEBU[0036] No credentials matching <registry><path> found in /home/user/.docker/config.json
DEBU[0036] No credentials matching <registry><path> found in /home/user/.dockercfg
DEBU[0036] No credentials for <registry><path> found
DEBU[0036]  Lookaside configuration: using "default-docker" configuration
DEBU[0036]  No signature storage configuration found for <registry><path>:latest, using built-in default file:///home/user/.local/share/containers/sigstore
DEBU[0036] Looking for TLS certificates and private keys in /etc/docker/certs.d/<registry>
DEBU[0036]  Sigstore attachments: using "default-docker" configuration
DEBU[0036] GET https://<registry>/v2/
DEBU[0037] Ping https://<registry>/v2/ status 401
DEBU[0037] GET https://s0004823.swr.ard/service/token?scope=repository%3Aproduktentwicklung%2Fsophora%2Fdelivery%2Fassets%3Apull&service=harbor-registry
DEBU[0037] GET https://<registry>/v2<path>manifests/latest
DEBU[0037] Content-Type from manifest GET is "application/json; charset=utf-8"
DEBU[0037] Accessing "<registry><path>:latest" failed: reading manifest latest in <registry><path>: unauthorized: unauthorized to access repository: <path>, action: pull: unauthorized to access repository: <path>, action: pull
DEBU[0037] Error pulling candidate <registry><path>:latest: initializing source docker://<registry><path>:latest: reading manifest latest in <registry><path>: unauthorized: unauthorized to access repository: <path>, action: pull: unauthorized to access repository: <path>, action: pull
```

Log-Messages after podman pull:

```
DEBU[0037] IdleTracker:idle 2m+0h/4t connection(s)       X-Reference-Id=0xc000010058
DEBU[0037] IdleTracker:closed 2m+0h/4t connection(s)     X-Reference-Id=0xc000010058
DEBU[0037] IdleTracker:closed 1m+0h/4t connection(s)     X-Reference-Id=0xc0009b1528
DEBU[0125] IdleTracker:new 0m+0h/4t connection(s)        X-Reference-Id=0xc0000114b8
DEBU[0125] IdleTracker:active 0m+0h/5t connection(s)     X-Reference-Id=0xc0000114b8
127.0.0.1 - - [02/Sep/2022:18:46:05 +0200] "GET /v4.2.0/libpod/_ping HTTP/1.1" 200 2 "" "Go-http-client/1.1"
DEBU[0125] IdleTracker:idle 1m+0h/5t connection(s)       X-Reference-Id=0xc0000114b8
DEBU[0125] IdleTracker:closed 1m+0h/5t connection(s)     X-Reference-Id=0xc0000114b8
DEBU[0125] IdleTracker:new 0m+0h/5t connection(s)        X-Reference-Id=0xc0000114c0
DEBU[0125] IdleTracker:active 0m+0h/6t connection(s)     X-Reference-Id=0xc0000114c0
127.0.0.1 - - [02/Sep/2022:18:46:05 +0200] "GET /v4.2.0/libpod/_ping HTTP/1.1" 200 2 "" "Go-http-client/1.1"
DEBU[0125] IdleTracker:idle 1m+0h/6t connection(s)       X-Reference-Id=0xc0000114c0
DEBU[0125] IdleTracker:closed 1m+0h/6t connection(s)     X-Reference-Id=0xc0000114c0
DEBU[0125] IdleTracker:new 0m+0h/6t connection(s)        X-Reference-Id=0xc0009b03c8
DEBU[0125] IdleTracker:active 0m+0h/7t connection(s)     X-Reference-Id=0xc0009b03c8
DEBU[0125] Stored credentials for <registry> in credential helper containers-auth.json
DEBU[0125] Pulling image <registry><path>:latest (policy: always)
DEBU[0125] Looking up image "<registry><path>:latest" in local containers storage
DEBU[0125] Normalized platform linux/amd64 to {amd64 linux  [] }
DEBU[0125] Trying "<registry><path>:latest" ...
DEBU[0125] Trying "<registry><path>:latest" ...
DEBU[0125] Trying "<registry><path>:latest" ...
DEBU[0125] Normalized platform linux/amd64 to {amd64 linux  [] }
DEBU[0125] Attempting to pull candidate <registry><path>:latest for <registry><path>:latest
DEBU[0125] parsed reference into "[overlay@/home/user/.local/share/containers/storage+/run/user/1000/containers]<registry><path>:latest"
DEBU[0125] Copying source image //<registry><path>:latest to destination image [overlay@/home/user/.local/share/containers/storage+/run/user/1000/containers]<registry><path>:latest
DEBU[0125] Using registries.d directory /etc/containers/registries.d
DEBU[0125] Trying to access "<registry><path>:latest"
DEBU[0125] Found credentials for <registry><path> in credential helper containers-auth.json in file /var/tmp/auth.json.1906286197
DEBU[0125]  Lookaside configuration: using "default-docker" configuration
DEBU[0125]  No signature storage configuration found for <registry><path>:latest, using built-in default file:///home/user/.local/share/containers/sigstore

DEBU[0125] Looking for TLS certificates and private keys in /etc/docker/certs.d/<registry>
DEBU[0125]  Sigstore attachments: using "default-docker" configuration
DEBU[0125] GET https://<registry>/v2/
DEBU[0125] Ping https://<registry>/v2/ status 401
DEBU[0125] GET https://s0004823.swr.ard/service/token?account=<account>&scope=<registry>/<path>%3Apull&service=harbor-registry
DEBU[0125] GET https://<registry>/v2<path>manifests/latest
DEBU[0126] Content-Type from manifest GET is "application/vnd.docker.distribution.manifest.v2+json"
DEBU[0126] Using blob info cache at /home/user/.local/share/containers/cache/blob-info-cache-v1.boltdb
DEBU[0126] IsRunningImageAllowed for image docker:<registry><path>:latest
DEBU[0126]  Using default policy section
DEBU[0126]  Requirement 0: allowed
DEBU[0126] Overall: allowed
DEBU[0126] Downloading /v2<path>blobs/sha256:0565e1b94a47a9fdc41dff1d250ae060cb015eb817a1fd0614484e611c639d38
```

A workaround seems to be to simply sym-link /run/users/<uid>/containers/auth.json to <user-home>/.config/containers/auth.json - this works for me for now but seems a bit hackish :-)

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.4
Built:        Thu Aug 11 16:42:17 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**
```
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.0-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpuUtilization:
    idlePercent: 88.12
    systemPercent: 4.18
    userPercent: 7.7
  cpus: 2
  distribution:
    distribution: fedora
    variant: container
    version: "36"
  eventLogger: file
  hostname: PC150287
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.4.72-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 3736936448
  memTotal: 6232866816
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 2146947072
  swapTotal: 2147483648
  uptime: 2h 43m 50.00s (Approximately 0.08 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  registry.swr.ard:
    Blocked: false
    Insecure: true
    Location: registry.swr.ard
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: registry.swr.ard
    PullFromMirror: ""
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 269490393088
  graphRootUsed: 2747301888
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 75
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1660228937
  BuiltTime: Thu Aug 11 16:42:17 2022
  GitCommit: ""
  GoVersion: go1.18.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```
(same for the podman service listening to the unix-socket as when executed with podman --url tcp://localhost:<port> info)

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Latest Version: No
Troubleshooting Guide: Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows 10, WSL2, besides the above changes a vanilla wsl2 distribution as created by podman machine init & start
docker-compose 2.10.2 (but did not work with a somewhat older 2.x-version, do not remember which one exactly)

**Comment by vrothberg** [comment]
I suspect that the XDG_RUNTIME_DIR env variable isn't set for the service. It remains unclear why that would be.

@mtrmac WDYT?

**Comment by Argelbargel** [comment]
Okay. So i've i export XDG_RUNTIME_DIR to /run/containers/users/$(id -u)/ explicitly it should work? I'll try that an provide feedback...

**Comment by Argelbargel** [comment]
Starting podman service with:

```
/usr/bin/podman --runroot=/run/user/$(uid -u)/containers/ --log-level=debug system service tcp:localhost:2375 -t 0
```

does not make a difference. Setting the env var explicitly does neither:

```
/usr/bin/env XDG_RUTIME_DIR=/run/user/$(id -u)/containers /usr/bin/podman --log-level=debug system service tcp:localhost:2375 -t 0
```

As a `podman -url tcp://localhost:2375 pull ...` works this seems to be restricted to either a specific api-endpoint the (only) docker-compose uses and not that some setting is ignored for the whole service

**Comment by mtrmac** [comment]
> When starting our containers using docker-compose it fails when it tries to pull a missing image from this registry even though authentication info is present in /run/user//containers/auth.json after a successfull podman login. Running a remote pull using podman --url tcp://localhost: pull  also works as expected.

So the `auth.json` file exists on the client? And `docker-compose` is connecting over the API? I’d expect `docker-compose` to read config files and provide credentials over the API, then (it has to, if there are no server-side credentials).

I haven’t checked, but I wouldn’t expect `docker-compose` to be reading `containers/auth.json`. Does it work when placing the credentials to the traditional `.docker/config.json` file?

---

> I suspect that the XDG_RUNTIME_DIR env variable isn't set for the service. It remains unclear why that would be.

That should be visible in Podman’s logs, on the computer that is reading the config files. See the `No credentials matching <registry><path> found in` log entries. But I assume those are server-side logs, aren’t they?

**Comment by Argelbargel** [comment]
`auth.json` exists in the container. When calling the API via tcp podman tries to find auth.json in the container but instead of looking in `/run/user/<uid>/containers/auth.json` it looks in `<homedir>/.config/containers/auth.json` according to the logs. Symlinking `/run/user/<uid>/containers/auth.json` to `<homedir>/.config/containers/auth.json` resolves the problem (symlinking to `<homedir>/.docker/config.json` would work also, i assume....

Yes, these are the logs of the server - as docker-compose does call the API via tcp there should be no client involved - or should it? I'll have a look if there is a docker.exe somewhere still in the path on the client...

**Comment by mtrmac** [comment]
> In the container.

I don’t understand how containers figure into this. Is `docker-compose`, or the Podman server, running in a container of some kind?

---

> podman pull from the client via tcp (which also should use the API, shouldn'it) looks correctly for /run/user<uid>/containers... it seems. 

That’s not what I see happening _on the server_, per those logs. I _would_ expect the podman _client_ to do that, sure.

---

> as docker-compose does call the API via tcp there should be no client involved 

Well _something_ calls the server’s API. `docker-compose`, or something invoked by it, serves as a client to Podman’s server.

---

Or maybe I’m completely wrong about the location of credentials in the client-server scenario??

Still, on success
```
Found credentials for <registry><path> in credential helper containers-auth.json in file /var/tmp/auth.json.1906286197
```
(_not_ the primary `auth.json`, a temporary single-use file), I think, suggests use of https://github.com/containers/podman/blob/8882b7664d225bf7f8efac6ab10e8d583e48c712/pkg/auth/auth.go#L236 , i.e. that the credentials come from the client as part of the API request.

**Comment by vrothberg** [comment]
> , i.e. that the credentials come from the client as part of the API request.

Great catch.  So it works with the podman _client_ as it sends the credentials in the request. `docker-compose` does not see these credentials.

Why does symlinking to `<homedir>/.config/containers/auth.json` work?

**Comment by vrothberg** [comment]
> So basically what i'll have to do is somehow tell docker-compose to use the podman on the client instead of the docker.exe and then it should work ich the podman on the client is logged into the registry, right?

I would try using `podman login --authfile $WhatDockerComposeWants`.  This way, docker-compose can read the authfile from where it wants, which very likely is `<homedir>/.docker/config.json`.

**Comment by Argelbargel** [comment]
When doing that on the client with an empty/non-existing file, podman complains that the registry (or any registry?) is not known:

```
podman login --authfile C:\Users\<user>\.docker\config.json
Error: no registries found in registries.conf, a registry must be provided
```
Is that correct? Why does podman (on the client) expect the registries.conf on the client when using --authfile but uses the configuration form the server/inside the wsl2-distribution when executing the login without the `--authfile`-parameter?

**Comment by vrothberg** [comment]
`podman login --authfile C:\Users\<user>\.docker\config.json`


Did you specify which registry you want to login to?

**Comment by Argelbargel** [comment]
Whaa. Sorry, been responding here while working through our own support-tickets and -messages at work - never a good idea :-/ 

When running `podman login --authfile C:\Users\<user>\.docker\config.json <registry>` the command works without error-message. But it simply ignores the `--authfile`-parameter as long as `C:\Users\<user>\.config\containers\auth.json` contains an entry for the registry. After removing that file, docker-compose works as expected!

**Comment by vrothberg** [comment]
Excellent, thanks for confirming!  I will create a follow-up issue for the --authfile issue.
