### ISSUE TITLE
Exposed container ports are accessible to the entire world

### ISSUE THREAD

**Issue by skerit** [containers/podman#15623]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm installing a new home server. Because the server is publically accessible to the internet I'm using firewalld.
My rules are pretty simple: I'm just allowing things like 80, 433 & 22.

As soon as I start a container though, the ports exposed on it are publicly visible!
For example:

```
podman run --detach \
    --name mongo-dev\
    --restart unless-stopped\
    -v /srv/database/mongo-dev/data:/data/db\
    -v /srv/database/mongo-dev/conf:/data/configdb\
    --publish 27017:27017\
    -d\
    docker.io/library/mongo\
    --config /data/configdb/mongod.conf
```

Nothing comes up in firewalld: I don't see this port being added as a rule after starting this container... but when I scan the port from a remote server, it's open!

(The only way I found out was because after a few hours the database already get "hacked". Luckily it's a dev database with no real data in it)

How can I stop this from happening?
I don't want any exposed port to ever override the firewalld configuration. (Doing `--public 127.0.0.1:27017:27017` might bind it to the localhost, but that's not what I want either)

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.19
Git Commit:   7fe5a419cfd2880df2028ad3d7fd9378a88a04f4-dirty
Built:        Sat Aug 13 12:26:55 2022
OS/Arch:      linux/amd64

```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.4-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: bd1459a3ffbb13eb552cc9af213e1f56f31ba2ee'
  cpuUtilization:
    idlePercent: 99.64
    systemPercent: 0.14
    userPercent: 0.22
  cpus: 16
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: kumulus
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.19.6-arch1-1
  linkmode: dynamic
  logDriver: journald
  memFree: 37321400320
  memTotal: 67345678336
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.5-2
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.2.0-1
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 4h 59m 22.00s (Approximately 0.17 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 463407677440
  graphRootUsed: 30376415232
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 5
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1660386415
  BuiltTime: Sat Aug 13 12:26:55 2022
  GitCommit: 7fe5a419cfd2880df2028ad3d7fd9378a88a04f4-dirty
  GoVersion: go1.19
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
community/podman 4.2.0-1 [installed]
    Tool and library for running OCI-based containers in pod
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Comment by baude** [comment]
the command you are running exposes that port to the world by publishing on the host.  this is not a bug.  perhaps explaining what you want to do would be more informative ....

**Comment by rhatdan** [comment]
Is podman manipulating the firewalld rules to expose the ports to the internet or just within the host?

@mheon @Luap99 WDYT?

**Comment by mheon** [comment]
Considering they're on arch, I don't think they're using firewalld, though confirmation of that from @skerit would help.

Our current behavior here mirrors CNI and Docker; a lot of our forwarding rules are prepended to iptables, which (usually - it's very difficult to guarantee anything with iptables operations via API) guarantees that port forwards are exposed through the firewall. I would characterize this as expected behavior, as again, it's what Docker and CNI do; `-p 80` implies that you are exposing that port to the internet. If you did not want to do that, restricting to localhost with `127.0.0.1:80:80` would prevent it.

Docker does implement a user-hookable chain which is created ahead of every other rule they use and can be used to filter traffic to these forwarded ports, which seems like a good way of handling this in a sane manner for iptables. The upcoming firewalld and nftables drivers can do even better, given that they have proper APIs and are not saddled with the legacy baggage of iptables.

**Comment by skerit** [comment]
I was using firewalld at the time.
I've switched to ufw now, and I don't have the same issue there.

**Comment by rhatdan** [comment]
At this point this seems like it is settled, feel free to continue conversation here.
