### ISSUE TITLE
Podman becomes randomly unusable for some users

### ISSUE THREAD

**Issue by RomainLyon1** [containers/podman#15641]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

After running some containers, podman becomes unusable for some user. In our workflows it's root user

**Steps to reproduce the issue:**

Currently, I have no idea why the problem happens. Just the only workaround we found is to reinstall the node. Removing `/var/lib/containers/` does not change anythging and root user has no `~/.config`, `~/.local`, `~/.cache`

EDIT: Finally I figured out, the problem appears if an usb block device is connected to the node...

**Describe the results you received:**
`ERRO[0000] [graphdriver] prior storage driver overlay failed: kernel does not support overlay fs: 'overlay' is not supported over extfs at "/var/lib/containers/storage/overlay": backing file system is unsupported for this graph driver 
Error: kernel does not support overlay fs: 'overlay' is not supported over extfs at "/var/lib/containers/storage/overlay": backing file system is unsupported for this graph driver`

**Describe the results you expected:**
Expecting `podman ps` to work as `root` (stil working as `ubuntu`)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 4
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: tpr-test
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.0-47-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 7187546112
  memTotal: 8212443136
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 1m 46.6s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/ubuntu/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/ubuntu/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/ubuntu/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 3.4.4

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
root@tpr-test:/home/ubuntu# apt list podman
Listing... Done
podman/jammy,now 3.4.4+ds1-1ubuntu1 amd64 [installed]

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical ubuntu 22

**Comment by giuseppe** [comment]
> EDIT: Finally I figured out, the problem appears if an usb block device is connected to the node...

does it affect the file system under `/var/lib/containers/storage`?  Or where is it mounted?

**Comment by vrothberg** [comment]
Friendly ping, @RomainLyon1

**Comment by RomainLyon1** [comment]
To answer the USB is not really directly mounted. When the device is connected a script does mknod, set permissions and the mount inside the container.

I did more test and the problem does not happen all the time. The workaround works when the problem occurs but having the USB drive connected does not cause the problem.

**Comment by rhatdan** [comment]
Sorry this got lost because of the stale-issue flag.
@RomainLyon1 is this still an issue>

**Comment by RomainLyon1** [comment]
Hello,

I'm currently not able to access these  machines, they are in a temporally closed area (for weeks). When I will be able to access it again I will test and update you back.

**Comment by vrothberg** [comment]
@RomainLyon1, did you get access to the machines?

**Comment by RomainLyon1** [comment]
I got access back but I didn't manage to reproduce the issue. I did several tests and it always boot successfully. But the podman API is currently is 3.4.4+ds1-1ubuntu1.22.04.2. Do you want me to downgrade and try again?

**Comment by vrothberg** [comment]
I think we can close the issue then.  Feel free to reopen in case it happens again.
