### ISSUE TITLE
Fail to remove image with command "podman container cleanup --rmi xxx"

### ISSUE THREAD

**Issue by fhwsuper** [containers/podman#15640]
This issue is found in Podman 3.4.4. 

The code logic is that remove image directly, but the container is still using the image. I suppose it should remove the container first and then remove the image in code. Or is it work as design? 

func (ic *ContainerEngine) ContainerCleanup()

Ubuntu Linux 20.04
root@fanhuawei-Standard-PC-i440FX-PIIX-1996:/home/fanhuawei/podman/podman-3.4.4/bin# ./podman container cleanup --rmi b11c6311eaf7
ERRO[0000] Error removing image: Image used by b11c6311eaf74ea64ca500781fb96207ec41ec01a5d8311ccf20e93c4b4a6401: image is in use by a container
Error: Image used by b11c6311eaf74ea64ca500781fb96207ec41ec01a5d8311ccf20e93c4b4a6401: image is in use by a container

**Comment by vrothberg** [comment]
Thanks for reaching out, @fhwsuper.

@mheon WDYT?

**Comment by mheon** [comment]
This sounds like a bug, yeah. Also points out that our testing for the `--rmi` flag is probably not working as expected.

**Comment by mheon** [comment]
To be clear, the solution of swapping the ordering - remove the container first, image second - sounds completely correct.

**Comment by vrothberg** [comment]
@mheon the ordering in the backend looks good to me.  I think `--rmi` can only work with `--rm`.  Not sure if `--rmi` should imply `--rm` or if we should check that on the CLI (or backend) and error out.

**Comment by mheon** [comment]
Given that `podman container cleanup` is only really meant to be invoked automatically by Conmon, I'd be perfectly fine making `--rmi` require `--rm`. We'll have to catch this in `podman run` and `podman create` as well, though, because otherwise the error messages will be lost.

**Comment by boaz0** [comment]
What if we have two containers: `container1` and `container2` and both are using image `image1`.
I would rather `podman container cleanup --rm --rmi container1` to fail instead of deleting `container1`, `container2` and `image1`.

**Comment by rhatdan** [comment]
@mheon @boaz0 @fhwsuper @vrothberg Is this still an issue?

**Comment by mheon** [comment]
Yep, still an issue. `podman run -t -i --rmi fedora ls /` fails to successfully remove the image because the container still exists.
