### ISSUE TITLE
podman events: --format is broken

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#15648]
Looks like nobody ever actually tested it:
```console
# podman events --stream=false --format='{{.ID}}'
Error: template: events:1:8: executing "events" at <.>: range can't iterate over {0 e06c985f70b9bf4f76c9c55d846274c9e83d9af999e0cc598ba966cd99ff09d9    history 2022-09-06 09:24:39.692735139 -0400 EDT container  { map[]}}
```
Same with `.Image`, `Name`, `Status`, even `.Foo`. This is on a brand-brand-new VM, where the *only* thing I've done is:
```console
# dnf install podman
# podman run quay.io/libpod/testimage:20220615 date
```
(but yes, it also fails on my laptop, root and rootless, git@main as well as released-from-rpm)

**Comment by vrothberg** [comment]
@Luap99 is working on a fix for that in https://github.com/containers/podman/pull/15644
