### ISSUE TITLE
investigate: `podman login --authfile` not writing credentials if another authfile contains credentials

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#15642]
When running `podman login --authfile C:\Users\<user>\.docker\config.json <registry>` the command works without error-message. But it simply ignores the `--authfile`-parameter as long as `C:\Users\<user>\.config\containers\auth.json` contains an entry for the registry. After removing that file and logging in with `--authfile`, docker-compose works as expected!

_Originally posted by @Argelbargel in https://github.com/containers/podman/issues/15620#issuecomment-1237820598_

**Comment by vrothberg** [comment]
FYI @mtrmac

**Comment by mtrmac** [comment]
At a first glance, without testing in practice:
- c/common/pkg/auth has some logic not to log in if credentials already already exist, and are working
- That uses `c/image/pkg/docker.GetCredentials`, which looks in various places _in addition to_ `AuthFilePath`.

To _some_ extent, this is a misunderstanding of what `AuthFilePath` does: it does not override the legacy Docker locations, nor does it prevent their use (e.g. we have _no_ way to override the location of the very old `~/.dockercfg`).

A bit more importantly, regardless of what `AuthFilePath` is set to, `registries.conf` can contain a `credential-helpers` list that does not contain `containers-auth.json` and in that case `AuthFilePath` does not make a difference _at all_. So, in that sense, the expectation that  `podman login --authfile` will direct both reads and writes _only_ to that file is just incorrect. Files are not the only possible credential storage.

---

That said, yes, this is a problematic corner case. I think we do the right thing if `~/.docker/config.json` contains _invalid_ credentials (we ignore them and write to `AuthFilePath`), but in the case where the right credentials are already available, and we just want to write them to _another_ location _as well_, this logic breaks.

**Comment by vrothberg** [comment]
This should now be fixed given that c/image is only using the specified authfile.
