### ISSUE TITLE
macOS: GPG error when pulling RH operator index (OperatorHub) images

### ISSUE THREAD

**Issue by jsm84** [containers/podman#15651]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'll preface this by stating that I'm a Fedora user and not too familiar with macOS, and specifically how podman is wired to run on a mac. But regardless, colleagues of mine who use mac (and which I've confirmed on a 10th-gen Intel-based macbook air) have reported an inability to pull the following images w/podman:

registry.redhat.io/redhat/certified-operator-index:<v4.x>
registry.redhat.io/redhat/redhat-marketplace-index:<v4.x>

Pulling these images (once the proper GPG key is setup) on Fedora works just fine. Performing the same `podman pull` command on macOS yields a GPG error. I'm not sure if podman respects the `/usr/local/containers/policy.json` file, but I've tried installing `skopeo` via homebrew in order to obtain that file, and editing it to reference the ISV Container Signing Key for the pull specs listed above.

Nothing seems to resolve the GPG error.

**Steps to reproduce the issue:**

1. Install the latest podman on macOS [via homebrew](https://podman.io/getting-started/installation#macos):

```
$ brew install podman
```

2. Attempt to pull any of the operator index images, used to populate OperatorHub on OpenShift:

```
$ podman pull registry.redhat.io/redhat/certified-operator-index:v4.11
```

3. Observe output.

**Describe the results you received:**

When performing the above steps, I receive the following GPG related error:

```
Trying to pull registry.redhat.io/redhat/certified-operator-index:v4.11...
Error: Source image rejected: Invalid GPG signature: gpgme.Signature{Summary:128, Fingerprint:"1AC4971355A34A82", Status:gpgme.Error{err:0x9}, Timestamp:time.Date(2022, time.August, 9, 8, 13, 51, 0, time.Local), ExpTimestamp:time.Date(1969, time.December, 31, 17, 0, 0, 0, time.Local), WrongKeyUsage:false, PKATrust:0x0, ChainModel:false, Validity:0, ValidityReason:error(nil), PubkeyAlgo:1, HashAlgo:8}
ERROR: Failed to launch index container
Exiting...
```

**Describe the results you expected:**

I expect `podman` to pull the image as it would on other platforms.

**Additional information you deem important (e.g. issue happens only occasionally):**

I have a feeling that the VM used by podman-machine is lacking the ISV-Container-Signing-Key ([provided by Red Hat](https://www.redhat.com/security/data/55A34A82.txt)) and having the proper config for the affected image repos in `/etc/containers/policy.json` in the virtual machine. I'm not versed on how to access or configure the podman VM in such case.

I'm not sure if the the `policy.json` file or any GPG related libraries are at all referenced from the macOS host environment, or if these are contained and utilized entirely within the podman-machine VM.

**Output of `podman version`:**
The below output is from the macbook air:

```
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.5
Built:        Wed Aug 10 16:46:05 2022
OS/Arch:      darwin/amd64

Server:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.4
Built:        Thu Aug 11 10:42:17 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpuUtilization:
    idlePercent: 99.56
    systemPercent: 0.34
    userPercent: 0.09
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "36"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 5.18.18-200.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1660223488
  memTotal: 2064896000
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/501/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 14h 40m 52.00s (Approximately 0.58 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106825756672
  graphRootUsed: 3179806720
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/501/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1660228937
  BuiltTime: Thu Aug 11 10:42:17 2022
  GitCommit: ""
  GoVersion: go1.18.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ brew list podman
/usr/local/Cellar/podman/4.2.0/bin/podman
/usr/local/Cellar/podman/4.2.0/bin/podman-mac-helper
/usr/local/Cellar/podman/4.2.0/bin/podman-remote
/usr/local/Cellar/podman/4.2.0/etc/bash_completion.d/podman
/usr/local/Cellar/podman/4.2.0/libexec/gvproxy
/usr/local/Cellar/podman/4.2.0/share/fish/vendor_completions.d/podman.fish
/usr/local/Cellar/podman/4.2.0/share/man/ (167 files)
/usr/local/Cellar/podman/4.2.0/share/zsh/site-functions/_podman
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

macOS Catalina 10.15.7

**Comment by rhatdan** [comment]
@baude @ashley-cui PTAL

**Comment by jsm84** [comment]
For anyone else who may have run into this using podman and enforcing GPG signatures on images (on macOS), here's the workaround [sic]:

"you can do `podman machine ssh`, then do `sudo su -`, and edit `/etc/containers/policy.json` to change the entry type for registry.redhat.io from `"type": "signedby"` to `"type": "insecureAcceptAnything"`, delete the trailing comma and the `keyType` and `keyPath` lines, and exit out of the VM. Then the podman pull command will work."
