### ISSUE TITLE
cannot remove container: error sending SIGKILL

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#15661]
New (to me) flake seen in [remote f36 aarch64 root](https://api.cirrus-ci.com/v1/artifact/task/6047415747739648/html/sys-remote-fedora-36-aarch64-root-host.log.html)
```
# podman-remote  rm -t 0 -f cpcontainer
Error: cannot remove container <sha> as it could not be stopped: \
     error sending SIGKILL to container <same sha>: %!w(<nil>)
```
(line break and edits for readability). (the percent-bang-double-u-nil is verbatim.)

Unlike #15367, this did NOT leave the system hosed. It failed, but all subsequent tests passed.

**Comment by vrothberg** [comment]
Thanks, @edsantiago!  Is it remote only so far?

**Comment by edsantiago** [comment]
No, here's a local-podman one: [int f36 root](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6531448663441408/html/int-podman-fedora-36-root-container.log.html#t--podman-run-network-connection-with-default-bridge--1). Another remote: [int remote ubuntu 2204 root](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6389994871848960/html/int-remote-ubuntu-2204-root-host.log.html#t--podman-run-network-connection-with-default-bridge--1). Both of those in the `podman run network connection with default bridge` test, which is suspicious. 

Only three instances in my logs. First one is the ubuntu one, August 2. This is going to be a hard one to track, because it only triggers a CI failure in `sys` tests, not `int` (because `int` tests do not do error-checking on cleanup).

**Comment by vrothberg** [comment]
Turned out to be an easy fix https://github.com/containers/podman/pull/15716.
