### ISSUE TITLE
Exponential grow of leaked mounts when mounting file and parent directory with `shared`

### ISSUE THREAD

**Issue by jhernand** [containers/podman#15671]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Bind mount points created with `-v /myroot/myfile:/root/myfile:ro -v /root:/root,rw,shared` aren't cleaned up when the container finishes and grow exponentially.

**Steps to reproduce the issue:**

1. Run the following command as root:

    ```
    # podman run -v /myroot/myfile:/root/myfile:ro -v /myroot:/root:rw,shared busybox
    ```

2. Check the mounts:

    ```
    # grep myroot /proc/mounts | sort | uniq -c
      1 /dev/mapper/local-root /myroot/myfile xfs rw,seclabel,relatime,attr2,inode64,logbufs=8,logbsize=64k,sunit=128,swidth=256,noquota 0 0
    ```

3. Run the same command again.

4. Check the mounts again:

    ```
    3 /dev/mapper/local-root /myroot/myfile xfs rw,seclabel,relatime,attr2,inode64,logbufs=8,logbsize=64k,sunit=128,swidth=256,noquota 0 0
   ```

**Describe the results you received:**

The bind mount for `/myroot/myfile` isn't removed when the container terminates, and actually it duplicated each time the same command is executed. For example, after running that command 6 times the number of mount points is 63:

```
# grep myroot /proc/mounts | sort | uniq -c
     63 /dev/mapper/local-root /myroot/myfile xfs rw,seclabel,relatime,attr2,inode64,logbufs=8,logbsize=64k,sunit=128,swidth=256,noquota 0 0
```

**Describe the results you expected:**

Expected the mount points to be removed when the container finishes.

**Additional information you deem important (e.g. issue happens only occasionally):**

The `/myroot` directory used in the command above only contains the empty `myfile` file:

```
# mkdir /myroot
# touch /myroot/myfile
```

This only reproduces when both a directory and its parent are mounted as volumes, and when that parent is mounted with the `shared` mount propagation option.

When the number of mount points grows (and it is quick, as it is exponential) it becomes impossible to start/restart systemd services because one of the first things it does is reading `/proc/self/mountinfo`. In my environment, for example, I saw more than 90000 entries in that file, which caused systemd to timeout while reading those files.

Note that using `-v` to mount a file and also the directory that contains it is probably wrong. We shouldn't probably be doing it, but I wanted to share this anyhow in case it is something you want to handle in podman.

**Output of `podman version`:**

```
# podman version
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.18.4

Built:      Wed Aug 24 02:18:50 2022
OS/Arch:    linux/amd64
```

**Output of `podman info`:**

```
# podman info
host:
  arch: amd64
  buildahVersion: 1.24.4
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.3-1.module+el8.7.0+16431+bb67d067.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.3, commit: e191fe4b86a7ab9369aee735ca95496767dd2518'
  cpus: 8
  distribution:
    distribution: '"rhel"'
    version: "8.7"
  eventLogger: file
  hostname: edge-04.edge.lab.eng.rdu2.redhat.com
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-423.el8.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 58247475200
  memTotal: 66901512192
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.3-2.module+el8.7.0+16431+bb67d067.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.3
      spec: 1.0.2-dev
      go: go1.18.4
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-2.module+el8.7.0+16431+bb67d067.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 30968897536
  swapTotal: 33621536768
  uptime: 29h 8m 41.58s (Approximately 1.21 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 20
    paused: 0
    running: 1
    stopped: 19
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 50
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1661321930
  BuiltTime: Wed Aug 24 02:18:50 2022
  GitCommit: ""
  GoVersion: go1.18.4
  OsArch: linux/amd64
  Version: 4.0.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# rpm -q podman
podman-4.0.2-8.module+el8.7.0+16431+bb67d067.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

I checked the latest Fedora package (`podman-4.2.0-2.fc36.x86_64`) and the result is the same.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by jhernand** [comment]
@giuseppe I am inclined to think that using `shared` in our case isn't necessary, and probably a bug in our code. But anyhow I would expect podman to clean up the mounts that it creates. For example, if I do it manually it works and the mount points aren't duplicated:

```
# mount --bind --make-shared /myroot /yourroot
# mount --bind /myroot/myfile /yourroot/myfile

# grep -E '(my|your)' /proc/mounts
/dev/mapper/local-root /yourroot xfs rw,seclabel,relatime,attr2,inode64,logbufs=8,logbsize=64k,sunit=128,swidth=256,noquota 0 0
/dev/mapper/local-root /yourroot/myfile xfs rw,seclabel,relatime,attr2,inode64,logbufs=8,logbsize=64k,sunit=128,swidth=256,noquota 0 0
/dev/mapper/local-root /myroot/myfile xfs rw,seclabel,relatime,attr2,inode64,logbufs=8,logbsize=64k,sunit=128,swidth=256,noquota 0 0

# umount /yourroot/myfile
# umount /yourroot

# grep -E '(my|your)' /proc/mounts
```

After the manual umount there are no leftovers. What is the different between that and and what podman is doing?

**Comment by giuseppe** [comment]
podman doesn't do any umount.  It is performed in a new `mount` namespace that is cleaned up when all the processes there are terminated

**Comment by jhernand** [comment]
I see, thanks @giuseppe. I also see that docker does exactly the same. Feel free to close this issue.
