### ISSUE TITLE
creating container in network with API fails: invalid config provided: networks and static ip/mac address can only be used with Bridge mode networking

### ISSUE THREAD

**Issue by martinpitt** [containers/podman#15689]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

It does not seem possible to create a user container in a user network with the API.

**Steps to reproduce the issue:**

As user:

1. `podman network create n1`

This works, and creates a bridge, visible in `podman network ls`.

2. `podman pull quay.io/libpod/busybox`

3. `curl -v --unix-socket $XDG_RUNTIME_DIR/podman/podman.sock --json '{"image": "quay.io/libpod/busybox", "name": "c1", "command": ["sleep", "infinity"], "remove": true, "Networks": {"n1": {}}}' http://nothing/v1.12/libpod/containers/create`

**Describe the results you received:**

Fails with

```
< HTTP/1.1 500 Internal Server Error
{"cause":"networks and static ip/mac address can only be used with Bridge mode networking","message":"invalid config provided: networks and static ip/mac address can only be used with Bridge mode networking","response":500}
```

**Describe the results you expected:**

(1) this is a bridge mode networking (even though I expect this to be somehow be an emulated stack, as it's all as user). (2) I am not giving any "static IP/mac" here.

**Additional information you deem important (e.g. issue happens only occasionally):**

I think this is just the API getting confused. If I do this on the CLI:

    podman create --name c1 --network n1 quay.io/libpod/busybox

it works:

    45a6146aec8c  quay.io/libpod/busybox:latest      sh                    2 seconds ago   Created                        c1

It also works if I do this with system containers. Run the `pull` and `network create` with `sudo`, and try:

    sudo curl -v --unix-socket /run/podman/podman.sock --json '{"image": "quay.io/libpod/busybox", "name": "c1", "command": ["sleep", "infinity"], "remove": true, "Networks": {"n1": {}}}' http://nothing/v1.12/libpod/containers/create

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.4
Built:        Thu Aug 11 16:42:17 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
ost:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: '
  cpuUtilization:
    idlePercent: 84.33
    systemPercent: 3.4
    userPercent: 12.26
  cpus: 8
  distribution:
    distribution: fedora
    version: "36"
  eventLogger: journald
  hostname: abakus
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.19.6-200.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 2801012736
  memTotal: 16535433216
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 77h 55m 38.00s (Approximately 3.21 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /var/home/martin/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 3
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/martin/.local/share/containers/storage
  graphRootAllocated: 228501188608
  graphRootUsed: 189908901888
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 21
  runRoot: /run/user/1000/containers
  volumePath: /home/martin/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1660228937
  BuiltTime: Thu Aug 11 16:42:17 2022
  GitCommit: ""
  GoVersion: go1.18.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-4.2.0-2.fc36.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical Fedora 36 x86_64

**Comment by Luap99** [comment]
You still have to set the network mode to bridge in the spec.
It would properly make sense to automatically change this to bridge when the network mode is unset but networks are given.

**Comment by martinpitt** [comment]
I tried to use the deprecated `cni_networks` option:
```
curl -v --unix-socket $XDG_RUNTIME_DIR/podman/podman.sock --json '{"image": "quay.io/libpod/busybox", "name": "c1", "command": ["sleep", "infinity"], "remove": true, "cni_networks": ["n1"]}' http://nothing/v1.12/libpod/containers/create
```

That does not fail, but the container has a "10.0.2.100" IP and no internal pod DNS, which smells like a slirp network. In the `podman create` reproducer I get inet 10.89.1.9 and can reach c1.dns.podman, which is what I expect from a bridge-type network.

**Comment by martinpitt** [comment]
@Luap99 : That sounds promising! How would I do that? https://docs.podman.io/en/latest/_static/api.html#tag/containers/operation/ContainerCreateLibpod does not document how I'd set a network mode in the /create API, just in the "play kubernetes yaml" section.

This still smells wrong: (1) why does this work as root? and (2) there is no choice about this value. If I specify an existing network, that has a type. If you'd set anything else than the type, it would/should fail anyway, right?

**Comment by Luap99** [comment]
> why does this work as root?

because network mode bridge is the default for root, rootless uses slirp4netns

> there is no choice about this value.

WDYM? you have to set the network mode as `"netns": { "nsmode": "bridge"}`, other options are host or none for example.

**Comment by martinpitt** [comment]
Thanks @Luap! Indeed this works! :tada: 

    curl -v --unix-socket $XDG_RUNTIME_DIR/podman/podman.sock --json '{"image": "quay.io/libpod/busybox", "name": "c1", "command": ["sleep", "infinity"], "remove": true, "netns": { "nsmode": "bridge" }, "Networks": {"n1": {}}}' http://nothing/v1.12/libpod/containers/create

> there is no choice about this value.

I meant that the "n1" network that I attach the container to defines the network mode already, no? I might misunderstand that.
