### ISSUE TITLE
feature request: Linux installable binaries in Release page

### ISSUE THREAD

**Issue by Trikenstein** [containers/podman#15682]
/kind feature

**Description**

The release page https://github.com/containers/podman/releases/tag/v4.2.1 seems not to have an installable  Linux binaries. The instructions in [install.md](https://github.com/containers/podman/blob/main/install.md) sends to a link which basically suggests 

```shell
sudo apt install podman
```

Which, as of 2022-09-07 on Ubuntu 22.04.1 installed Podman 3.4.4 (Current version is 4.2.1)

REQUEST: is it OK to provide a Linux binary directly in this repository in https://github.com/containers/podman/releases/ ?

Thanks in advance

**Comment by mheon** [comment]
We don't do this for a variety of reasons, including the fact that Podman
isn't just one binary - we'd need to package Conmon, Netavark, slirp4netns,
a few config files, and probably more I'm forgetting, to get a usable
installation. It's a lot more feasible to let distributions handle
packaging as opposed to trying to provide an installable static binary and
all relevant dependencies as a release artifact here.

**Comment by giuseppe** [comment]
we would also need stuff like the OCI runtime, as well as `newuidmap/newgidmap` for rootless.

**Comment by Luap99** [comment]
Even disregarding the dependencies if we want to publish a binary we would have to statically link it in order to make it work on all distros. However I don't think you can reasonable statically link podman without loosing functionality.
We had a static nix build in the past but it started failing and nobody stepped up to fix it so we removed it.

**Comment by rhatdan** [comment]
Agreed, this is a non goal for this project.  If you want to run newer binaries then use the container images, then you can run it via Docker or older versions of Podman.

Podman is a lot more then just the executable, so it requires many other components, and these componants often need to be updated with updated Podman.

Having a distro or a container image is the only way we can support this.

**Comment by Trikenstein** [comment]
@rhatdan  The release page  https://github.com/containers/podman/releases/ lists

- podman-installer-macos-aarch64.pkg
- podman-installer-macos-amd64.pkg 
- podman-v4.2.1.msi 

I just assumed that macOS and Windows have an installer and wonder maybe Linux could have one too.

**Comment by rhatdan** [comment]
Understood, but Linux is not one single vendor.  We rely on distributions to ship their selected group of projects.  In the perfect world Apple and Microsoft would take care of the packaging of Podman for their "distros" but sadly they do not.  In the Linux world their ware way too many variants for the upstream project to handle, and building static versions that are fully featured is impossible.  So best we can do is make a containerized version available of the latest released version.
