### ISSUE TITLE
podman events missbehaving when there are zero events

### ISSUE THREAD

**Issue by Luap99** [containers/podman#15688]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman events --stream=false is used for many test to make sure that we do not hang in the tests.
However as I found out while working on https://github.com/containers/podman/pull/15673 that --events-backend=file hangs if the event log file does not exists.
For --events-backend=none it also hangs for some reason? I would expect an error since there are no events.
Lastly with --events-backend=journald it just errors out right away when there are no events.

**Steps to reproduce the issue:**
file, as rootless:
```
$ rm $XDG_RUNTIME_DIR/libpod/tmp/events/events.log
$ podman events --events-backend=file --stream=false <--just hangs until you create events or create the file
```

journald:
first empty the journal
```
$ sudo journalctl --rotate
$ sudo journalctl --vacuum-time=1s
```
```
$ podman events --events-backend=journald --stream=false
Error: failed to get journal cursor: failed to get cursor: cannot assign requested address
$ podman events --events-backend=journald <--same error without stream=false
Error: failed to get journal cursor: failed to get cursor: cannot assign requested address
```

none:
```
$ podman events --events-backend=none --stream=false  <-- hangs without error
$ podman events --events-backend=none  <-- also hangs without error
```

**Describe the results you expected:**
The file backend with --stream=false should not hang as this can/will break tests.

The journald backend just not fail when there are no events.

The podman events with none backend should just error, there is no reason to ever run this command.

**Output of `podman version`:**

```
latest main
```

**Comment by edsantiago** [comment]
Suggestion please: when podman is hanging, please print the path to the log file. (Correction: preferably before podman hangs).

**Comment by Luap99** [comment]
> Suggestion please: when podman is hanging, please print the path to the log file. (Correction: preferably before podman hangs).

you mean on debug or info log level?
