### ISSUE TITLE
CreateExitCommandArgs's podmanPath can be invalid

### ISSUE THREAD

**Issue by KenMacD** [containers/podman#15707]
/kind bug

**Description**

The exit command created by `CreateExitCommandArgs` uses `os.Executable()`. Unfortunately this misses the context in which `podman` was originally called.

In NixOS the `podman` executable is actually named `podman-unwrapped`, and a wrapper exists named `podman` that sets paths to dependencies like `crun`. The end result is that the exit-command call doesn't actually work and the container takes 10 seconds to shutdown.

**Comment by vrothberg** [comment]
Thanks for reaching out, @KenMacD.

Can you elaborate on what the `podman` wrapper does in detail?  Is it setting env variables or global flags?

Cc: @mheon

**Comment by vrothberg** [comment]
Thanks for elaborating, @KenMacD, that was quite helpful.

Ultimately, we are a bit in between a rock and a hard place.  If we would execute only the `podman` in $PATH, we'd break backwards compatibility.  The only way I see (at the moment) is to inject $PATH into conmon.

**Comment by mheon** [comment]
Adding environment variables to the exit command would seem to be the safest option, but that will require Conmon changes.

**Comment by Luap99** [comment]
Can't we just keep the environment variables for conmon? Is there any reason to unset them specifically? Not using $PATH seems already problematic on "normal" distros considering that the cleanup process calls network cleanup which will invoke iptables for example.

**Comment by rhatdan** [comment]
Isn't conmon executing `podman-unwrapped cleanup ...`

**Comment by KenMacD** [comment]
@rhatdan sorry, I don't fully understand your question. Yes conmon is running `podman-unwrapped ...`, but then `podman-unwrapped` is unable to find the runtime because it doesn't have the same `$PATH`.

As a test I added the following patch to `v4.2.0` to pass the PATH to conmon, and it seems to work. Not sure of the implications though.

```diff
--- a/libpod/oci_conmon_linux.go
+++ b/libpod/oci_conmon_linux.go
@@ -1297,6 +1297,7 @@ func (r *ConmonOCIRuntime) configureConmonEnv(runtimeDir string) []string {
 	if ok {
 		env = append(env, fmt.Sprintf("CONTAINERS_CONF=%s", conf))
 	}
+	env = append(env, fmt.Sprintf("PATH=%s", os.Getenv("PATH")))
 	env = append(env, fmt.Sprintf("XDG_RUNTIME_DIR=%s", runtimeDir))
 	env = append(env, fmt.Sprintf("_CONTAINERS_USERNS_CONFIGURED=%s", os.Getenv("_CONTAINERS_USERNS_CONFIGURED")))
 	env = append(env, fmt.Sprintf("_CONTAINERS_ROOTLESS_UID=%s", os.Getenv("_CONTAINERS_ROOTLESS_UID")))
```

**Comment by mheon** [comment]
That seems like a perfectly reasonable patch. I thought we'd need actual Conmon changes, but it does make sense that it already passes along the environment variables it knows about.

**Comment by rhatdan** [comment]
Please open a PR?
