### ISSUE TITLE
Push operation not compatible with serverless framework

### ISSUE THREAD

**Issue by skorhone** [containers/podman#15705]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Podman authentication failure message differs from docker error message. This sifference causes compatibility issue.

Docker used error message ’no basic auth credentials’ and podman uses ’unauthorized: authentication required’

Project would accept documentation update that explains how to use podman with the framework

**Steps to reproduce the issue:**

1. See https://github.com/serverless/serverless/issues/11120

**Describe the results you received:**
Didn’t test. Just reporting issue reported in another project 😬

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
Thanks for reaching out, @skorhone!

As a quick fix, I suggest serverless to check for both error messages.  Changing the error message of Podman can break existing users, and needs careful consideration.

@mtrmac @rhatdan WDYT?

**Comment by mtrmac** [comment]
I’m _quite strongly_ opposed to making error text in CLI a guaranteed-stable API.

For one thing, https://github.com/containers/image/pull/1299 is in flight, which will among other things, shorten error messages to be less repetitive, and it includes that message as well.

---

That said, I don’t know what the Docker Engine API error reporting mechanism does, and that might not necessarily use exactly the same text as the CLI. At least looking at https://docs.docker.com/engine/api/v1.41/#section/Errors , there seems to be no stable API mechanism either.

**Comment by rhatdan** [comment]
I agree serverless should check both messages.

**Comment by skorhone** [comment]
I agree that it might not be the best idea to check error from error message. Error code would be a far better alternative.

Unfortunatley docker api provides none. Considering podman is emulating docker api, it would be ideal returned errors were same. If error message is checked by one application, who knows how many do the same. Better compatibility improves adoption

If I read original issue right, it was about using podman as daemon (via socket) And if I remember correctly, podman socket was divided to docker compatible api & podman api by request path. Error message could be changed only in docker compatible api. This wouldn’t cause problems with existing api clients as they are expecting to be communicating with docker

Podman team has done awesome job with api compatibility. I guess the question here is about where to draw the line. Is it enough to cover happy case scenarios or should major fail paths also be included.

The documentation part is also something you could assist serverless team. Would I not write so many typos, I might do it myself 😂

**Comment by mtrmac** [comment]
If this is some kind of command that interactively wraps the API and restarts on failures, I think the _ultimately right_ thing to do here is to have a specific “validate credentials” call that returns relevant values. Trying to push, doing all kinds of preparatory work, and then failing, and having to restart that, seems wasteful.

That would be an entirely new feature, probably in a Podman-specific API.

---

Looking at the Docker API compatibility aspect: Docker does have _a_ way to determine if the error is lack of credentials: https://github.com/moby/moby/blob/924edb948c2731df3b77697a8fcc85da3f6eef57/client/image_push.go#L39 , and that’s ultimately decide by checking the HTTP status code: https://github.com/moby/moby/blob/924edb948c2731df3b77697a8fcc85da3f6eef57/errdefs/http_helpers.go#L21 , _not_ the error text.

Now, the 401 value is not actually documented in https://docs.docker.com/engine/api/v1.41/#tag/Image/operation/ImagePush , but looking at the other errors, it does seem that the HTTP statuses is what API callers are supposed to be using.

---

But, uh, does the API matter at all here? A simple search for that string ends up at https://github.com/serverless/serverless/blob/bb37f4fe75ff5234fae48ada433cd52ddf51cb91/lib/plugins/aws/provider.js#L1977-L1987, which seems like invoking the Docker CLI binary (or `podman-docker` I suppose), and substring matching on the CLI output.

My purely personal opinion is that I’m not really interested in that kind of compatibility, but I can’t speak for the Podman project.

**Comment by vrothberg** [comment]
@skorhone, can you work with the provided information?

**Comment by rhatdan** [comment]
@vrothberg @mtrmac any update on this?

**Comment by vrothberg** [comment]
No, waiting for feedback.

**Comment by rhatdan** [comment]
Since we have never heard any feedback, I am closing.  Reopen if you want to continue working on this.
