### ISSUE TITLE
REST API /system/df UsageData.RefCount on volumes is always 1

### ISSUE THREAD

**Issue by benoitf** [containers/podman#15720]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

In order to see who is using a volume, I'm using the `RefCount` attribute of `UsageData` field 

But even if you create a volume without using it, it returns 1.
And if you create multiple containers using that volume, it's still using 1

**Steps to reproduce the issue:**

1. Create a volume without using it

```bash
$ dummyVolume=$(podman volume create)
```

2.
Use REST api to see refCount

```
$ curl --silent --unix-socket /Users/benoitf/.local/share/containers/podman/machine/podman-machine-default/podman.sock "http:/v1.41/system/df" | jq --arg volumeName $dummyVolume '.Volumes[] | select(.Name == ($volumeName))'
{
  "Driver": "",
  "Labels": {},
  "Mountpoint": "",
  "Name": "413f47a2d1656a4ec6e876543dc8a0caa5256c670a425638eff7be9730da0229",
  "Options": null,
  "Scope": "local",
  "UsageData": {
    "RefCount": 1,
    "Size": 0
  }
}
```

It's already invalid

3. Now, try to start containers using that volume

```bash
$ podman run -d --mount "type=volume,src=$dummyVolume,target=/foo" docker.io/library/httpd
$ podman run -d --mount "type=volume,src=$dummyVolume,target=/foo" docker.io/library/httpd
```

4. Rest API is still invalid

```bash
$ curl --silent --unix-socket /Users/benoitf/.local/share/containers/podman/machine/podman-machine-default/podman.sock "http:/v1.41/system/df" | jq --arg volumeName $dummyVolume '.Volumes[] | select(.Name == ($volumeName))'
{
  "Driver": "",
  "Labels": {},
  "Mountpoint": "",
  "Name": "413f47a2d1656a4ec6e876543dc8a0caa5256c670a425638eff7be9730da0229",
  "Options": null,
  "Scope": "local",
  "UsageData": {
    "RefCount": 1,
    "Size": 0
  }
}
```

And we still have our container using it

```bash
$ podman inspect 18e7216f21ab0eddb5fab99c388ba04030809b6870cd0c595e7bc84008c7fb3d | jq '.[0].Mounts'
[
  {
    "Type": "volume",
    "Name": "413f47a2d1656a4ec6e876543dc8a0caa5256c670a425638eff7be9730da0229",
    "Source": "/var/home/core/.local/share/containers/storage/volumes/413f47a2d1656a4ec6e876543dc8a0caa5256c670a425638eff7be9730da0229/_data",
    "Destination": "/foo",
    "Driver": "local",
    "Mode": "",
    "Options": [
      "nosuid",
      "nodev",
      "rbind"
    ],
    "RW": true,
    "Propagation": "rprivate"
  }
]
```

**Describe the results you received:**
 RefCount = 1

**Describe the results you expected:**
Valid RefCount

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
4.2.1
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by benoitf** [comment]
https://github.com/containers/podman/blob/29d7ab3f82e38c442e449739e218349b9a4a16ea/pkg/api/handlers/compat/system.go#L79

**Comment by vrothberg** [comment]
Thanks for reaching out, @benoitf!

@mheon PTAL

**Comment by mheon** [comment]
We can get an array of containers referencing a volume via `VolumeInUse()` from the state. Get the length of the array, and we have the refcount. I can take this.
