### ISSUE TITLE
Securing API service for remote access through REST API

### ISSUE THREAD

**Issue by jonganej** [containers/podman#15724]
/kind bug

**Description**

I was trying to set up the API service of Podman to be able to manage individual containers on a server from a remote client and wanted to ensure that TLS and client certificate authentication was enabled but was not able to find any documentation on that that maps to the Docker version of [this documentation](https://docs.docker.com/engine/security/protect-access/#use-tls-https-to-protect-the-docker-daemon-socket). It seems like the `--tlsverify` flags are not implemented on podman to begin with too.

Is there a way to secure the TCP socket for podman's API service?

**Comment by mheon** [comment]
Our recommendation so far has been to not expose the socket and instead to use SSH tunneling to access it; as such I don't think we have implemented cert auth for the socket.

**Comment by rhatdan** [comment]
Correct we recommend that you rely on ssh connections and tunneling through them.

**Comment by thmo** [comment]
It might be possible to secure the service by wrapping it with `socat`, see <http://www.dest-unreach.org/socat/doc/socat-openssltunnel.html>.

**Comment by fsdrw08** [comment]
it should better to implement the `tlsverify`, because some docker related tools, e.g. jenkins docker plugin, the only supported secure connect option is x509 client cert
