### ISSUE TITLE
Podman 4.2.1 in MacOS Intel cannot connect to Podman VM

### ISSUE THREAD

**Issue by kairu97** [containers/podman#15732]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. podman images

2. podman ps

3. podman info

**Describe the results you received:**
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: connection to bastion host (ssh://core@localhost:50693/run/user/501/podman/podman.sock) failed: dial tcp: lookup localhost: i/o timeout

**Describe the results you expected:**
It should output if there are any images or containers even if there is none. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: connection to bastion host (ssh://core@localhost:50693/run/user/501/podman/podman.sock) failed: dial tcp: lookup localhost: i/o timeout
```

**Output of `podman info`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: connection to bastion host (ssh://core@localhost:50693/run/user/501/podman/podman.sock) failed: dial tcp: lookup localhost: i/o timeout
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes (Issue Not listed and tried other options based on the file)

**Additional environment details (AWS, VirtualBox, physical, etc.):**
MacOS Monterey 12.5 / Intel i7 10th Gen

![image](https://user-images.githubusercontent.com/63029919/189486898-915a8fd2-8e95-4c18-852e-9f83f3ae4364.png)
![image](https://user-images.githubusercontent.com/63029919/189486906-5463f9c0-7374-40fe-96d0-c9043a4aa2ec.png)

**Comment by baude** [comment]
do you see the gvproxy process running ?

**Comment by kairu97** [comment]
Hi @baude , what command do I use to check if the gvproxy process is running? Looks like there is none.

**Comment by kairu97** [comment]
Hi @baude , it's running. I checked in ps aux. 
![image](https://user-images.githubusercontent.com/63029919/189782120-4bd1041f-7590-41b3-92cd-5d211f22f534.png)

**Comment by baude** [comment]
did it ever work?

**Comment by kairu97** [comment]
@baude , it used to work last May when it was 4.1 point something. But when I upgraded it to 4.2, it did not work anymore. I am also running OpenShift Local (CRC), but also uninstalled it to see if it is the issue. Unfortunately it isn't.

**Comment by baude** [comment]
If you stop your machine, and then do a `podman machine init --now foobar` does it work?

**Comment by kairu97** [comment]
Hi @baude , sorry for the late reply. I tried uninstalling and reinstalling it. Now it's outputting a different error.

Error: dial unix /var/folders/n3/zyhygp5x0h9d0s02gtn0b6gc0000gn/T/podman/foobar_ready.sock: connect: no such file or directory

Error: unable to connect to Podman. failed to create sshClient: connection to bastion host (ssh://core@localhost:50162/run/user/501/podman/podman.sock) failed: dial tcp: lookup localhost: i/o timeout

![image](https://user-images.githubusercontent.com/63029919/190032085-bd4ad8e0-bd48-490f-8c46-1804884cb307.png)
![image](https://user-images.githubusercontent.com/63029919/190032094-f87928c7-82ed-4142-819f-9091195792ec.png)

**Comment by kairu97** [comment]
It's still the same error. But here is my containers.conf file. I don't even know why it isn't even working. 
![image](https://user-images.githubusercontent.com/63029919/190033862-1d3da325-d585-4b9a-9428-ec6c81caedb2.png)

**Comment by kairu97** [comment]
Hi @baude , this is the guide that I found with similar error. https://www.iamgini.com/podman . But even if I unset it, it still does not work.

**Comment by kairu97** [comment]
This remains unresolved @baude . I decided to do a clean re-install of MacOS since I also have Docker Desktop which might have interfered. After doing a clean reinstall it's now working nice. Thanks for the help!

**Comment by Aldiuser** [comment]
Hey guys,

I had this problem too and came across a solution that solved my problem. It has to do with the DNS entry on macOS. Maybe it helps with you guys: https://github.com/helm/helm/issues/11306#issuecomment-1256745270

**Comment by ashley-cui** [comment]
Since it seems to be working after a clean re-install, I'm going to close this issue.
