### ISSUE TITLE
Podman fails to remove old install-components preventing reinstall/update (35 to 36) / re-init

### ISSUE THREAD

**Issue by claudiusraphael** [containers/podman#15742]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

After unregistering all distros in WSL2 and complete uninstall of all related software - (Podman Desktop, Podman for Windows (WSL2), Ubuntu (Default), WSLg, WSL-Update - it was not possible to initialize podman, although the reinstall went without errors.

Using ```podman system info``` showed me it failed to establish a connection. The ```podman system connection list``` showed the default connections.

In hope to force a machine-init, i then removed the connections via:
```podman system connection remove podman-machine-default```
```podman system connection remove podman-machine-default-root```
.. just to see if ```podman machine init``` will then complete, but it did not - it again showed me:
```Error: podman-machine-default: VM already exists```

As the VM was not listed via ```wsl --list``` i then used ```podman machine list```, which showed:
```
NAME                    VM TYPE     CREATED     LAST UP     CPUS        MEMORY      DISK SIZE
podman-machine-default  wsl         8 days ago  7 days ago  0           0B          0B
```

So to cleanup manually i then utilized:
```podman machine rm podman-machine-default```, which resulted in:

```
The following files will be deleted:

C:\Users\claudiusraphael\.ssh\podman-machine-default
C:\Users\claudiusraphael\.ssh\podman-machine-default.pub
C:\Users\claudiusraphael\.local\share\containers\podman\machine\wsl\podman-machine-default_fedora-35-x86_64.tar
C:\Users\claudiusraphael\.config\containers\podman\machine\wsl\podman-machine-default.json
C:\Users\claudiusraphael\.local\share\containers\podman\machine\wsl\wsldist\podman-machine-default


Are you sure you want to continue? [y/N] y
time="2022-09-12T06:08:23+02:00" level=error msg="unable to find connection named \"podman-machine-default\""
time="2022-09-12T06:08:23+02:00" level=error msg="unable to find connection named \"podman-machine-default-root\""
Unregistering...
There is no distribution with the supplied name.
time="2022-09-12T06:08:23+02:00" level=error msg="exit status 4294967295"
```

The ```unable to find connection``` parts are expected as i removed them manually, but it is noteworthy that the intermittent podman init did not reestablish the connections and gave no warning.

Since the error ```Error: podman-machine-default: VM already exists``` remained, i checked the folders given when trying to remove the "podman-machine-default"-VM.

After removing any of the given folders completely finally ```podman machine init``` processed and returned:

```
podman machine init
Downloading VM image: fedora-podman-v36.0.40.tar.xz: done
Extracting compressed file
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
Configuring system...
```

**Steps to reproduce the issue:**

I summarized what i have done in the description, because due to no immediate errors given there are no exact reproducible steps i can list which lead to the problem.

**Describe the results you received:**

The checks ```podman machine init``` does are not sufficient.
The uninstaller does not cleanup at all, which later blocks a reinitialization.

**Describe the results you expected:**

```podman machine init``` should do a thorough investigation/report to point out what the actual problem is that hinders it to init. Since i utilized a complete uninstall of all wsl-components after podman failed to init, at least a hint towards the custom directories should be given, so one has at least a chance to manually remove it without literally have to go through any given option by trial and error just to accidentally stumble over those directories - ALSO these custom directories should be at least MENTIONED on the front-page AND in any way reflected in the terminal outputs.

**Additional information you deem important (e.g. issue happens only occasionally):**

This happens also when removing the Ubuntu (Default) wsl and then remove podman via uninstaller and try to podman machine init after reinstall.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.16.15
Git Commit:   62b324ddf718411b1d4d0ba8117c632f7f984a38
Built:        Wed Sep  7 15:08:04 2022
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.4
Built:        Thu Aug 11 16:42:17 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.4-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: '
  cpuUtilization:
    idlePercent: 99.86
    systemPercent: 0.09
    userPercent: 0.04
  cpus: 4
  distribution:
    distribution: fedora
    variant: container
    version: "36"
  eventLogger: journald
  hostname: [REDACTED]
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.62.1-microsoft-snapd+
  linkmode: dynamic
  logDriver: journald
  memFree: 7549640704
  memTotal: 8018194432
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 2147209216
  swapTotal: 2147483648
  uptime: 0h 37m 32.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 269427478528
  graphRootUsed: 310738944
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1660228937
  BuiltTime: Thu Aug 11 16:42:17 2022
  GitCommit: ""
  GoVersion: go1.18.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

Yeah, well turns out that podman still didn't init correctly and does not let me exec/stop or ssh into the now created podman-machine-default, stating that it cannot stop the machine and ssh is forbidden because it expects the former password which is obviously not present anymore, besides the fact that the win-sshproxy can neither be stopped nor reinitialized/setup.

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Bare Metal Windows 11 Pro latest updates applied

Seriously, what is it with you folks to always crush a perfectly fine product and trying to unmodularize software ...

I will give it one more try on a complete fresh system setup virgin install, but since i already basically did that by using another user-account as well, after podman basically murdered my main users wsl setup, i won't get my hopes up and will most probably rely on the former release.

**Comment by vrothberg** [comment]
Thanks for reaching out, @claudiusraphael!

@ashley-cui  @baude @n1hility WDYT?

**Comment by n1hility** [comment]
@claudiusraphael Did you get `VM already exists` *after* a `podman machine rm`? The way the VM exists check works is it just looks for a json file containing the state of the machine. This file is removed as part of `podman machine rm` so init should not throw that error unless something prevented the file deletion.

**Comment by n1hility** [comment]
Sorry, I can't seem to recreate this one, and don't see an obvious cause (other than perhaps something was holding a lock preventing removal of the json file). If you run into it again and can expand more on the conditions or even better provide a reproducer ill take another look thanks!

**Comment by claudiusraphael** [comment]
> @claudiusraphael Did you get `VM already exists` _after_ a `podman machine rm`? The way the VM exists check works is it just looks for a json file containing the state of the machine. This file is removed as part of `podman machine rm` so init should not throw that error unless something prevented the file deletion.

Yes, "VM already exists" is mentioned (as i already noted in my first report) although no machine-definition is any more existent, whereas the actual images are still existent. When attempting to re-initialize the same behavior shows. After deleting ALL files manually the problem persists, only difference that "VM already exists" is not shown anymore, it produces the default status (as if everything was fine) but it is not working, because the re-initialization fails.

The main problem is NOT that the machine-definition is not cleaned up/replaced/removed BUT that the images stay in place and are not removed/removable neither by the uninstaller, nor manually and that SOMEWHERE besides the mentioned locations podman stores files which do not let it leave its state and/or renew/update the images even after manually enforce cleaning up all residues. - I do not see how i can be anymore clear about that.

Other than what i already noted in detail before i can not provide as there simply is none to find (asides from the registry, the ntfs-stack/-streams, the app-/package-cache or in another completely unexpected place, so i guess that is indeed a possibility considering the actual placement of files).

I have recreated/reproduced the exact same behavior on three separate fresh installs of Windows 11 on 3 different machines - exactly same effects as already mentioned:

1. by deleting the former primary default Ubuntu - results in podman not starting anymore, rm and init fail - uninstall of all components and manually removing the residues (which are not deleted by the uninstaller) does not solve the problem. - wsl2 partly broken, podman not recoverable by any means

2. by installing podman first then add another wsl2 distro and set that as primary/default - same behaviour podman can not connect to pods anymore - rm/init and uninstall fail -  wsl2 broken, podman not recoverable by any means

3. by adding a custom made distro with a custom kernel - same behavior - rm/init fails - uninstall does not clean up

I will not do another attempt for now, as WSL2 is completely broken in some variations after having used podman and cannot be restored even by manually clearing the app-/package-cache for the wsl-packages and kernel and manually editing system-configs and registry to simulate a fresh install.

It is obvious that podman does actively check something and falsely interprets the results - only place i haven't dug in depth into was the registry simply because i do not know which keys/values podman might use if at all.

Once the aforementioned happens it is not possible to refresh/reinstall WSL2 at all and make it usable again.

I was quite detailed in all the steps taken. The bug is reproducible and happens since the mentioned release which as far as i was able to identify introduced some linking/handles for the gui-client - if that has anything to do with it, i can't tell - documentation on the code is basically non-existent or where it exists implies knowledge not linked anywhere in-place.

I already offered to help IF you provide concise and clear steps to allow full debugging, but i won't waste my time reinstalling Windows over and over to come up with the exact same end-effect as it just makes no sense without knowing how to enable full-logging/having a confugurable debug-release and at least a guess on your end which procedures might cause the issue.

BUG: REPRODUCIBLE as described in short at the beginning of this comment.

Provide clear guidance how to fully debug this and i may consider another attempt.

Additional info:

- The later attempts were done on Desktop-Kabylake, Laptop-SandyBridge, Convertible-CherryTrail to see if the hardware makes a difference. It did not.

- The version of Windows 11 installer/iso used was latest mainline stable base release 22000.675 Cobalt Default English (EN-US): The system was in all cases fully updated before install of WSL2 and the mentioned variants of installing wsl distros and podman. - The only time i was able to run the bugged version without immediately having a broken system was when utilizing the original release/first release-rendition of Windows 11; which can not be considered a workaround as this is not even provided for regular users and only deployed that way in/by enterprises/oem sometimes, but even in that environment it is normally not the case anymore - that is as far as it goes regarding wild-guesses why you were not able to reproduce the error.


IF you get back at me provide what i asked for - CLEAR procedures for debugging this including accompanying releases and links to references to make sense of the underlying structure to be able to follow the data-flow
ELSE don't even bother to answer.

Thanks, and you are welcome.

**Comment by n1hility** [comment]
@claudiusraphael Thanks for sharing these scenarios. Unfortunately, they all work for me. I included some notes on the steps I took. To figure out what's going wrong, and why you have different behavior,  I would really need to see the exact list of commands that you ran and in what sequence, and when the first sign of failure occurred. I realize you have invested enough time in this, so I understand if you prefer not to. Perhaps a difference will stand out in my notes.

> I have recreated/reproduced the exact same behavior on three separate fresh installs of Windows 11 on 3 different machines - exactly same effects as already mentioned:
> 
> 1. by deleting the former primary default Ubuntu - results in podman not starting anymore, rm and init fail - uninstall of all components and manually removing the residues (which are not deleted by the uninstaller) does not solve the problem. - wsl2 partly broken, podman not recoverable by any means

Here are the steps I took

1. Stock Win 11 Pro Install
2. Launched powershell in admin mode
3. Ran standard WSL install that includes Ubuntu `wsl --install`
4. Reboot
5. Completed Ubuntu setup wizard 
6. Went to github.com/containers/podman and installed podman 4.3.0 via podman-4.3.0-setup.exe
7. Relaunched powershell in admin mode
8. Ran `podman machine init`, also did a a start and stop, which completed successfully and verified Ubuntu is the default
``` 
PS C:\Users\jason> wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
podman-machine-default
```
9. Deleted Ubuntu and started podman machine successfully
```
PS C:\Users\jason> wsl --unregister Ubuntu
Unregistering...
PS C:\Users\jason> podman machine start
Starting machine "podman-machine-default"
<snip>
Machine "podman-machine-default" started successfully
```
10. Executed a container operation succesfully 
```
PS C:\Users\jason>  podman run -it ubi8-micro date
<snip pull verbose output>
Sun Oct 30 18:30:25 UTC 2022
```
11. Verified rm still works 
```
PS C:\Users\jason> podman machine stop
Machine "podman-machine-default" stopped successfully
PS C:\Users\jason> podman machine rm
The following files will be deleted:
<snip>
Are you sure you want to continue? [y/N] y
Unregistering...
```
12. And that init afterwords still works
```
PS C:\Users\jason> podman machine init
<snip>
Machine init complete
```
13. Repeated starting and running a container and everything worked 
```
PS C:\Users\jason> podman machine start
<snip>
PS C:\Users\jason> podman run -it ubi8-micro date
<snip pull messages>
Sun Oct 30 18:33:22 UTC 2022
```

> 2. by installing podman first then add another wsl2 distro and set that as primary/default - same behaviour podman can not connect to pods anymore - rm/init and uninstall fail -  wsl2 broken, podman not recoverable by any means

1. This time started out with no distros
```
PS C:\Users\jason> wsl -l
Windows Subsystem for Linux has no installed distributions.
Distributions can be installed by visiting the Microsoft Store:
https://aka.ms/wslstore
```
2. Then did a `podman machine init` to get podman-machine-default created. Afterwords, verified:
```
PS C:\Users\jason> wsl -l
Windows Subsystem for Linux Distributions:
podman-machine-default (Default)
```
3. Tested machine start, run, container, stop: everything worked as expected
4.  Installed Ubuntu
```
PS C:\Users\jason> wsl --install -d Ubuntu
Launching Ubuntu...
```
5. Made it the default, and verified,
```
PS C:\Users\jason> wsl --set-default Ubuntu
PS C:\Users\jason> wsl -l
Windows Subsystem for Linux Distributions:
Ubuntu (Default)
podman-machine-default
```
6. Started podman, and ran a container:
```
PS C:\Users\jason> podman machine start
Starting machine "podman-machine-default"
<snip>
Machine "podman-machine-default" started successfully
PS C:\Users\jason> podman r
un -it ubi8-micro date
<snip pull logs>
Sun Oct 30 18:39:21 UTC 2022
```
7. Stop and rm also work 
```
PS C:\Users\jason> podman machine stop
Machine "podman-machine-default" stopped successfully

PS C:\Users\jason> podman machine rm
<snip>
```
8. Ubuntu also still works: 
```
wsl cat /etc/os-release
NAME="Ubuntu"
<snip>
```

The only other thing I thought to look into was some sort of state issue where podman-machine-default is unregistered manually and rm refuses to clean-up, but that also worked for me:

```
PS C:\Users\jason> wsl --unregister podman-machine-default
Unregistering...
PS C:\Users\jason> podman machine rm

The following files will be deleted:
<snip>
Are you sure you want to continue? [y/N] y
Unregistering...
There is no distribution with the supplied name.
time="2022-10-30T13:41:02-05:00" level=error msg="exit status 0xffffffff"
```

In spite of the expected error from the dist not existing, the files are cleaned up, and a subsequent init succeeds:
```
PS C:\Users\jason> podman machine init
<snip>
Machine init complete
```


> I will not do another attempt for now, as WSL2 is completely broken in some variations after having used podman and cannot be restored even by manually clearing the app-/package-cache for the wsl-packages and kernel and manually editing system-configs and registry to simulate a fresh install.

Sure, I totally understand not wanting to take this further.  FWIW there isnt much special stored elswhere. Registry settings aren't used, and no special ntfs entries. It just uses the files that rm lists and a WSL distro which is managed via standard  WSL operations.
