### ISSUE TITLE
missing online CPU information w/ compat REST API

### ISSUE THREAD

**Issue by benoitf** [containers/podman#15754]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Looking at Compat API
https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerStats

it says `number_cpus = length(cpu_stats.cpu_usage.percpu_usage) or cpu_stats.online_cpus`

and
```
If either precpu_stats.online_cpus or cpu_stats.online_cpus is nil then for compatibility with older daemons the length of the corresponding cpu_usage.percpu_usage array should be used.
```

but it seems podman is not providing any of `percpu_usage` or `online_cpus`

**Steps to reproduce the issue:**

1. launch a container like `httpd`

```bash
myContainer=$(podman run -d docker.io/library/httpd)
```

3.
grab cpu_stats

```
$ curl --silent --unix-socket /Users/benoitf/.local/share/containers/podman/machine/podman-machine-default/podman.sock "http:/v1.41/containers/$myContainer/stats?stream=false"  | jq .cpu_stats
{
  "cpu_usage": {
    "total_usage": 192517000,
    "usage_in_kernelmode": 167090,
    "usage_in_usermode": 192349910
  },
  "system_cpu_usage": 2518699606000,
  "cpu": 0,
  "throttling_data": {
    "periods": 0,
    "throttled_periods": 0,
    "throttled_time": 0
  }
}
```

or pre_cpu_stats
```
$ curl --silent --unix-socket /Users/benoitf/.local/share/containers/podman/machine/podman-machine-default/podman.sock "http:/v1.41/containers/$myContainer/stats?stream=false"  | jq .precpu_stats
{
  "cpu_usage": {
    "total_usage": 0,
    "usage_in_kernelmode": 0,
    "usage_in_usermode": 0
  },
  "cpu": 0,
  "throttling_data": {
    "periods": 0,
    "throttled_periods": 0,
    "throttled_time": 0
  }
}
```

**Describe the results you received:**

I don't see the number of cpus

**Describe the results you expected:**

I can get get the number of cpus and compute cpu usage

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
4.2.1 / macOS
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
This continues to be worked on.

**Comment by rhatdan** [comment]
Getting closer.
