### ISSUE TITLE
Unclear default value for --userns

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#15764]
The manual page of podman-run says about `--userns`: “Set the user namespace mode for the container. It defaults to the `PODMAN_USERNS` environment variable.”  I have no PODMAN_USERNS environment variable.

What is the default value for `--userns` (in rootless and rootful mode)?

Podamn Version:      4.3.0-dev

**Comment by giuseppe** [comment]
```
Set the user namespace mode for the container. It defaults to the **PODMAN_USERNS** environment variable. An empty value ("") means user namespaces are disabled unless an explicit mapping is set with the **--uidmap** and **--gidmap** options.
```

Since the `PODMAN_USERNS` when unset it is equal to `""`, the default value is to not use user namespaces, so the equivalent of `--userns host`

**Comment by rhatdan** [comment]
Do you think we need this in a man page.  We should change the wording to say that the container runs in the default userns in rootless mode.  Not that there is no user namespace.

--userns and --uidap --gidmap will put the container into an alternative user namespace then the default.

In rootful mode the user namespace is the default user namespace.
In rootless mode the user namespace is the current UID mapped to root and then the contents or /etc/subuid (/etc/subgid) for the user running podman starting at UID=1.

**Comment by dilyanpalauzov** [comment]
For me an unset variable and a variable with value emtpy string are different things in the general case.

**Comment by dilyanpalauzov** [comment]
Addressed at https://github.com/containers/podman/pull/17156.
