### ISSUE TITLE
memory Limit is returning invalid result for `/container/stats` REST API on macOS

### ISSUE THREAD

**Issue by benoitf** [containers/podman#15765]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The field `memory_stats.limit` is returning an invalid value

**Steps to reproduce the issue:**

1. Start a dummy container like fedora

```bash
$ MY_DUMMY_CONTAINER=$(podman run -d fedora sleep 20000)
```

2. Display the memory of the container from inside the container

```bash
$ podman exec -ti $MY_DUMMY_CONTAINER cat /proc/meminfo | head -3
MemTotal:        2018452 kB
MemFree:          860084 kB
MemAvailable:    1556036 kB
```

3. Now, read the value returned by the REST API

```bash
curl --silent --unix-socket /Users/benoitf/.local/share/containers/podman/machine/podman-machine-default/podman.sock "http:/v1.41/containers/$MY_DUMMY_CONTAINER/stats?stream=false&one-shot=true"  | jq .memory_stats
{
  "usage": 94208,
  "max_usage": 18446744073709552000,
  "limit": 18446744073709552000
}
```

**Describe the results you received:**

```
  "limit": 18446744073709552000
```

it seems this value is like the maximum value of the int/long/etc

**Describe the results you expected:**

something displaying around 2GB / 2Gi because it's the size of the machine.
```
  "limit": 2066894848
```
and based from
https://docs.docker.com/engine/api/v1.41/#tag/Container/operation/ContainerStats

```
used_memory = memory_stats.usage - memory_stats.stats.cache
available_memory = memory_stats.limit
Memory usage % = (used_memory / available_memory) * 100.0
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
4.2.1
```

**Output of `podman info`:**

```
4.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
Thanks for reaching out, @benoitf!

@giuseppe, can you take a look?  This looks like a cgroup stats issue at first glance.

**Comment by giuseppe** [comment]
Docker caps the value returned from the cgroup to the maximum available memory, so I guess we are forced to do the same thing for compatibility, opened a PR: https://github.com/containers/podman/pull/15811
