### ISSUE TITLE
Build container images in a rootless container without privileges inside a Kubernetes cluster - cannot clone: operation not permitted

### ISSUE THREAD

**Issue by jornfranke** [containers/podman#15785]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I want to build a container image using podman in a rootless non-privileged container inside Kubernetes.  Starting already the command podman login leads to an error:
``` 
cannot clone: Operation not permitted
Error: cannot re-exec process
```

The setting corresponds roughly to the "Rootless Podman without the privileged flag" described here https://www.redhat.com/sysadmin/podman-inside-kubernetes 

I observe though that the blog never uses podman login

**Steps to reproduce the issue:**

1. Inside the container run: podman login -u test -p test myhost

**Describe the results you received:**
``` 
cannot clone: Operation not permitted
Error: cannot re-exec process
```

**Describe the results you expected:**
Successful login

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
4.2.0
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Kubernetes (latest version)/Gitlab

**Comment by giuseppe** [comment]
the seccomp profile used by the runtime is blocking the `clone(CLONE_NEWUSER)` syscall.  There is nothing we can do from Podman, that syscall is required to create a new user namespace where rootless podman can gain capabilities.
