### ISSUE TITLE
healthcheck kill flake

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#15808]
Today must be new-flake day. Seen just now in [remote f36-aarch64 root](https://api.cirrus-ci.com/v1/artifact/task/6475099321663488/html/sys-remote-fedora-36-aarch64-root-host.log.html#t--00276):
```
not ok 276 podman healthcheck --health-on-failure
...
# podman-remote exec healthcheck_c touch /uh-oh
# podman-remote healthcheck run healthcheck_c
unhealthy
[ rc=1 (expected) ]
# podman-remote inspect healthcheck_c --format {{.State.Status}} {{.Config.HealthcheckOnFailureAction}}
running kill
#/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#|     FAIL: podman inspect healthcheck_c --format {{.State.Status}} {{.Config.HealthcheckOnFailureAction}}
#| expected: != 'running kill'
#|   actual:    'running kill'
#\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Test source: https://github.com/containers/podman/blob/017d81ddd0e8d228aadb949175c0aae1e4b9d925/test/system/220-healthcheck.bats#L122-L124

No other instances of this in my logs.

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Comment by vrothberg** [comment]
My best guess is that it's on aarch64 only which, to the best of recollection, has a number of unresolved signal issues.

**Comment by edsantiago** [comment]
Haven't seen since the first report.
