### ISSUE TITLE
run `quay.io/podman/stable:v4.2.0` with error

### ISSUE THREAD

**Issue by willzhang** [containers/podman#15801]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
run podman in container for cicd environment.
```
**Steps to reproduce the issue:**
```
```
root@ubuntu# docker run -it --rm  quay.io/podman/stable:v4.2.0 podman ps
WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers 
cannot clone: Operation not permitted
Error: cannot re-exec process
```

so what `quay.io/podman/stable:v4.2.0`  used for?

**Describe the results you received:**

error

**Describe the results you expected:**

run success
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@rhatdan PTAL

**Comment by Luap99** [comment]
You need to allow the clone syscall in your seccomp profile.

**Comment by rhatdan** [comment]
Yes disable docker seccomp protections, you an use podmans (Or better yet just use podman.)

**Comment by willzhang** [comment]
how can i enable docker seccomp protections, i can not understand what is  seccomp, i use ubuntu 22.04 server, and this way resolved my problems.

```
 docker run -it --rm --privileged quay.io/podman/stable:v4.2.0 sh
```

**Comment by rhatdan** [comment]
YOu could  have done

docker run -it --rm --security-opt seccomp:unconfined quay.io/podman/stable:v4.2.0 sh

Which would only disable seccomp for docker.

or

docker run -it --rm --security-opt seccomp:/ust/share/containers/seccomp.json quay.io/podman/stable:v4.2.0 sh

Which tells docker to use podman's seccomp.json file if podman is installed.  But if you have podman installed you can do

podman run -it --rm quay.io/podman/stable:v4.2.0 sh
