### ISSUE TITLE
podman-remote start --filter: new flake: not finding the right container?

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#15807]
New flake (no instances at all in my logs). [remote f36-aarch64 root](https://api.cirrus-ci.com/v1/artifact/task/6206305336557568/html/sys-remote-fedora-36-aarch64-root-host.log.html#t--00098):
```
not ok 98 podman start --filter - start only containers that match the filter
# podman-remote run -d quay.io/libpod/testimage:20220615 /bin/true
413057f751442acf5c62e6cfd3a6ab1e52d3abc51b4f7b9d5853000a1893d2cc
# podman-remote start --filter restart-policy=always 413057f751442acf5c62e6cfd3a6ab1e52d3abc51b4f7b9d5853000a1893d2cc
# podman-remote start --filter restart-policy=none 413057f751442acf5c62e6cfd3a6ab1e52d3abc51b4f7b9d5853000a1893d2cc
#/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#|     FAIL: CID of restart-policy=none container
#| expected: '413057f751442acf5c62e6cfd3a6ab1e52d3abc51b4f7b9d5853000a1893d2cc'
#|   actual: ''
#\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
test source: https://github.com/containers/podman/blob/a3876c2f854b6de58c7259f09eff0ec2b126f007/test/system/045-start.bats#L46-L47

Is this another race (note the `-d` in the container run), or is it a real bug in `start --filter`?

No reproducer, sorry.

**Comment by edsantiago** [comment]
Gonna try https://github.com/containers/podman/pull/15794/files#diff-cc7d327518501ed06d8bfbe82a39fe2bff543ca42609c05140bc937a81ed248b

**Comment by vrothberg** [comment]
> Gonna try https://github.com/containers/podman/pull/15794/files#diff-cc7d327518501ed06d8bfbe82a39fe2bff543ca42609c05140bc937a81ed248b

The fix there seemed to have fixed it.  `start` won't return anything when the container is still/already running.
