### ISSUE TITLE
Just curious: has anyone done a build performance comparison between podman and docker?

### ISSUE THREAD

**Issue by usernameisnull** [containers/podman#15819]
Just curious: has anyone done a build performance comparison between podman and docker?
I didn't find any relevant information

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by flouthoc** [comment]
Hi @usernameisnull , Could please elaborate more, did you mean `podman build` vs `docker build` benchmarking ?

**Comment by usernameisnull** [comment]
> yes
I think I have the answer: https://github.com/containers/podman/issues/13226

**Comment by usernameisnull** [comment]
> Hi @usernameisnull , Could please elaborate more, did you mean `podman build` vs `docker build` benchmarking ?

yes.
about ~15% slower than docker, I got it from #13226

**Comment by flouthoc** [comment]
I think benchmarking needs to happen on different parameters like `rootfull vs rootless` , `native overlay vs fuse-overlay` and maybe documented in the repo itself.

**Comment by flouthoc** [comment]
@usernameisnull Just curious are you hitting any bottlenecks while performing builds ?

**Comment by usernameisnull** [comment]
> 



> @usernameisnull Just curious are you hitting any bottlenecks while performing builds ?

No, It's just that we are doing technical selection, one of the thing is the build speed

**Comment by usernameisnull** [comment]
> I know there are many influencing factors, we can make a comparison under the best configuration of the two, or under the general configuration

I know there are many influencing factors, we can make a comparison under the best configuration of the two, or under the general configuration

**Comment by usernameisnull** [comment]
> I think benchmarking needs to happen on different parameters like `rootfull vs rootless` , `native overlay vs fuse-overlay` and maybe documented in the repo itself.

I know there are many influencing factors, we can make a comparison under the best configuration of the two, or under the general configuration

**Comment by rhatdan** [comment]
The comparison should be docker versus rootful buildah
Rootless Buildah is better for security but potentially requires fuse-overlay which will slow it down on older kernels.

**Comment by mheon** [comment]
(Not to mention slirp4netns versus native kernel networking - it your build needs to download anything of significant size, root will have a significant advantage)

I have an open card to do a performance blog on Podman vs Docker, I should try and get that done next week...

**Comment by rhatdan** [comment]
In rootless mode, you could use --network=host during builds, which would eliminate that issue.

**Comment by afbjorklund** [comment]
Make sure to also compare against `docker buildx` just as you want to compare with `buildah` directly ?

Using `docker build` and `podman build` is good for compatibility but not always for performance...

**Comment by usernameisnull** [comment]
> (Not to mention slirp4netns versus native kernel networking - it your build needs to download anything of significant size, root will have a significant advantage)
> 
> I have an open card to do a performance blog on Podman vs Docker, I should try and get that done next week...

very much looking forward to

**Comment by rhatdan** [comment]
@usernameisnull @mheon @afbjorklund What should we do with this one?

**Comment by mheon** [comment]
Keep it open until my blog comes out. Probably next week?

**Comment by corinz** [comment]
+1 looking forward to it @mheon ! Please post the link

**Comment by rhatdan** [comment]
@mheon I am guessing your blog came out, so closing.

**Comment by sanmai-NL** [comment]
@mheon Is this the blog then? https://www.redhat.com/sysadmin/speeding-container-buildah
I couldn't find any other.

**Comment by mheon** [comment]
I am searching, and I can't actually *find* the blog published anywhere. I wrote it and submitted it, but it looks like it was never published? I'll just throw it up on the podman.io blog site.
