### ISSUE TITLE
podman-tag.1.html  contains "<title>NAME &#8212; Podman  documentation</title>"

### ISSUE THREAD

**Issue by eriksjolund** [containers/podman#15822]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The title of the web page 

 https://docs.podman.io/en/latest/markdown/podman-tag.1.html

has changed since 30 July 2022. The word `podman-tag` has been replaced with `NAME`.
I would guess that this is unintentional.

Currently it looks like this
```
$ date
Thu Sep 15 18:47:59 CEST 2022
$ curl -Ls https://docs.podman.io/en/latest/markdown/podman-tag.1.html | grep '<title>' 
    <title>NAME &#8212; Podman  documentation</title>
```

Wayback Machine has a version of the same web page from 30 July 2022
```
$ curl -Ls https://web.archive.org/web/20220730202038/https://docs.podman.io/en/latest/markdown/podman-tag.1.html | grep '<title>'
    <title>podman-tag &#8212; Podman  documentation</title>
```

It seems to be a general problem that is not limited to podman-tag.1.html.
I randomly picked two more web pages (podman-run.1.html,  
podman-create.1.html) and checked. They have the same title as podman-tag.1.html.

```
$ date
Thu Sep 15 19:18:42 CEST 2022
$ curl -Ls https://docs.podman.io/en/latest/markdown/podman-run.1.html | grep '<title>'
    <title>NAME &#8212; Podman  documentation</title>
$  curl -Ls https://docs.podman.io/en/latest/markdown/podman-create.1.html | grep '<title>'
    <title>NAME &#8212; Podman  documentation</title>
$ 
```

**Comment by edsantiago** [comment]
@baude, @TomSweeneyRedHat, @Luap99 PTAL. I wonder if this is connected to #15621? Does anyone know a way to simulate the `readthedocs` build environment locally?

**Comment by edsantiago** [comment]
@Luap99 I've submitted #15825 as a possible fix. Completely untested, because I don't know how to emulate the readthedocs build environment.

**Comment by Luap99** [comment]
You should be able to build it locally with sphinx: https://github.com/containers/podman/blob/main/docs/README.md#local-testing
I think the deps might be out of date, https://github.com/containers/podman/blob/main/docs/requirements.txt should contain the actual pip deps.
