### ISSUE TITLE
podman machine not starting on macOS ventura 13.0 beta7

### ISSUE THREAD

**Issue by benoitf** [containers/podman#15834]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

FYI, I tried to launch Podman on macOS Ventura beta7

But podman machine is not starting due to an error with QEMU
Error: HV_ERROR

it seems to be related to the acceleration flag used.
Removing that flag from the qemu configuration file (removing also the `cpu host` parameter) allows to boot but it's slower.

config file = `$HOME/.config/containers/podman/machine/qemu/podman-machine-default.json`

**Steps to reproduce the issue:**

1. podman machine start

**Describe the results you received:**

```
% podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Error: HV_ERROR
```

**Describe the results you expected:**
machine is started

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
4.2.1 (tried the pkg and the brew version)
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

disabling acceleration is working (but machine is really slow)
![image](https://user-images.githubusercontent.com/436777/190640750-4bad9b7f-010e-4c7b-a6ba-bea545311bac.png)

**Comment by anjannath** [comment]
Could be related with the specific [`Qemu`](https://github.com/containers/podman-machine-qemu) build the pkginstaller uses, i think worth trying to start a VM directly using the `qemu-system` binary just to make sure

**Comment by benoitf** [comment]
closing as it works fine with the final release (13.0 (22A380)) of Ventura.
