### ISSUE TITLE
After using macOS pkg installer `/opt/podman/bin` is not available in my USER path

### ISSUE THREAD

**Issue by benoitf** [containers/podman#15831]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Using the macOS installer on a fresh macOS installation, I run the install flow, it's successfully completing but at the end, when opening a terminal I don't have `podman` being available

Default shell is zsh (fresh install)

I think the issue is because we check if we have some .rc/.env file for a given shell before appending the path to one of this file but as we don't have one, it does nothing

https://github.com/containers/podman/blob/main/contrib/pkginstaller/scripts/postinstall

**Steps to reproduce the issue:**

1. Use a fresh macOS install, no .rc/env shell stuff

2. Install the .pkg

3. Open a terminal and launch `podman` command

**Describe the results you received:**

podman not found

**Describe the results you expected:**

podman binary is there

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

![image](https://user-images.githubusercontent.com/436777/190600915-340b07bb-527f-43a5-9e47-4995d66c5f2d.png)

![image](https://user-images.githubusercontent.com/436777/190600971-74dd8ea4-9851-4226-bf76-ad24105441ca.png)

![image](https://user-images.githubusercontent.com/436777/190601005-99c26d67-0d25-43c9-9a64-a4e5e92a996e.png)

![image](https://user-images.githubusercontent.com/436777/190601039-17c5b0a9-7950-4dfa-a59a-b71ef4634681.png)

**Comment by cfergeau** [comment]
```
% cat /etc/paths.d/podman
/opt/podman/bin
```
should do the trick  (see `man path_helper`) and you can remove most of the postinstall script. Since the installer could create `/opt/podman/bin`, I assume it should be able to write to `/etc/paths.d/podman` as well.

**Comment by praveenkumar** [comment]
> Since the installer could create /opt/podman/bin, I assume it should be able to write to /etc/paths.d/podman as well.

Yes from installer you can able to wright `/etc/paths.d/podman` locations.
