### ISSUE TITLE
RFE: Expose docker-specific network create options via the CLI

### ISSUE THREAD

**Issue by mhdonnelly** [containers/podman#15830]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I am attempting to run an installer script for a product that targets docker but use podman as the container engine. During the install, the script attempts to create a network. When I run the network create command from the script on a host with docker, a bridge gets created that is visible via the `ip link` command on the host.

Using podman version 4.2.1 62b324ddf718411b1d4d0ba8117c632f7f984a38 the command fails:

```
podman network create --subnet 192.168.37.0/24 --internal foo --opt "com.docker.network.bridge.name=foo"
```

The error is:

```
Error: unsupported bridge network option com.docker.network.bridge.name
```

https://github.com/containers/podman/blob/main/pkg/api/handlers/compat/networks.go#L207 appears to show code that would handle the `com.docker.network.bridge.name` option however it does not get used when creating a network via the cli.

**Additional information you deem important (e.g. issue happens only occasionally):**

Related discussion on Slack https://kubernetes.slack.com/archives/CAZH62UR1/p1662106212002589

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.16.15
Git Commit:   62b324ddf718411b1d4d0ba8117c632f7f984a38
Built:        Fri Sep 16 09:32:09 2022
OS/Arch:      linux/amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical host running Fedora 35.

**Comment by Luap99** [comment]
Given that we support this already in the API and we try to be compatible on the cli as well I think this is a good idea. We should move this into the network backend in c/common.

**Comment by rhatdan** [comment]
I agree.

**Comment by rhatdan** [comment]
@Luap99 What is going on with this one?

**Comment by rhatdan** [comment]
@Luap99 What are your current thoughts on this one?

**Comment by Luap99** [comment]
Well someone can work on it if they want, I don't really have time for this and I don't think it is high priority.

**Comment by rhatdan** [comment]
@mhdonnelly Any interest in working on this yourself?
@cdoern care to take a stab?

**Comment by rhatdan** [comment]
@Luap99 Do you have time to work on this one, once exams are done?

**Comment by Luap99** [comment]
probably, remind me in three weeks

**Comment by rhatdan** [comment]
Sure, but really I will remind you the next time Stale timer reminds me.  :^(

**Comment by hasan4791** [comment]
I could take a look if its ok!!!

**Comment by Luap99** [comment]
@hasan4791 Sure, the code for this should be moved here: https://github.com/containers/common/tree/main/libnetwork into the network backend.

**Comment by rhatdan** [comment]
Go for it.

**Comment by hasan4791** [comment]
Just a query?
What would be the parsing/format of the string that we expect for the name?

**Comment by Luap99** [comment]
Not sure if I understand your question. The `com.docker.network.bridge.name` key must be mapped to `NetworkInterface` in the Network struct.

**Comment by hasan4791** [comment]
> Not sure if I understand your question. The `com.docker.network.bridge.name` key must be mapped to `NetworkInterface` in the Network struct.

Right, basically I am looking for, if we need to validate the inputs, like allowing alphanumeric characters or any string. Btw sorry if this sounds dumb.

**Comment by hasan4791** [comment]
And one more option seems to be missing here is "com.docker.network.driver.mtu"
Shall we consider this one too? It just fallthrough with the existing MTU case.

**Comment by Luap99** [comment]
You do not need to validate it, just map them into the options map then the backend will validate correctly if necessary.
Adding other  options such as mtu is great, we should match all docker options that have an equivalent podman one.
