### ISSUE TITLE
Use dedicated configured path for QEMU and gvproxy vlan socket

### ISSUE THREAD

**Issue by arixmkii** [containers/podman#15852]
Currently gvproxy uses QMP socket path to connect to QEMU vlan. Code responsible is here https://github.com/containers/podman/blob/main/pkg/machine/qemu/machine.go#L1227

The process looks like
1. podman binary starts gvproxy listening on this socket
2. podman binary connects to this socket and preserves FD
3. podman binary removes this socket (file) to allow QEMU to use this path
4. podman binary starts QEMU and passes additional FD

There is no strict requirement to use the same path and it could have more meaningful path like `vlan_` prefix in filename. Which will still allow to remove the file to prevent future connections. And there is nothing preventing to save it to config for consistency.

If this is a considered as a tricky "security feature" with reusing same path, then there is a reasonably loud opinion that security through obscurity is not the best thing and especially in OSS.

Changing this would not introduce any behavior breakage, but would unlock some more options for future development. Explored [here](https://github.com/containers/podman/issues/13006). This would allow to: 
1. switch to unix socket netdev and not rely on FD magic, which would make it possible to start podman machine by using plain command line w/o relying on the binary for all sort of troubleshooting
2. potentially simplify codebase (FD is a bit magical and really not needed, podman binary can just invoke needed commands generated based on config data)
3. better cross platform behavior (potential code unification). FD forwarding is not available on Windows platform, but unix socket netdev will work.

Unix socket netdev was recently resubmitted for 7.2.0 dev https://lists.gnu.org/archive/html/qemu-devel/2022-09/msg01713.html and is getting positive reviews, so, it is likely to land for 7.2.0.

As this is still a future work on QEMU side, for now it could still be achieved to decouple paths for QMP and VLAN socket.

This is still a feature, because there should be a config upgrade mechanism to not break the current installations of podman machine.

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

**Steps to reproduce the issue:**

1. Init default machine

6. Check config, there will be no explicit record for VLAN socket

**Describe the results you received:**

VLAN socket record not present in config

**Describe the results you expected:**

VLAN socket record present in config

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
4.3.0-dev compiled from latest sources
```

**Output of `podman info`:**

```
Irrelevant
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
N/A
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

QEMU podman machine

**Comment by rhatdan** [comment]
@baude @ashley-cui PTAL

**Comment by arixmkii** [comment]
I might find time to contribute changes, if this is discussed/approved and the approach confirmed.

**Comment by arixmkii** [comment]
This is still actual. But giving it some more thoughts.

This socket address is only needed between gvproxy started and QEMU started events. So, it might not really need the setting on its own, but could use a temp file with a deferred cleanup (it is deleted by code already, but just additional cleanup for unhappy path execution, would not harm I think). Will prepare PR implementing this variant.

**Comment by arixmkii** [comment]
Tried  with temp files. It works in general, but it is not possible to cleanup the file on Windows hosts (one can't delete opened file on Windows platform), so, there are some leftovers after each run. It is not that critical, but is considered as a bad practice in general. Will refactor it to a well-known file name inside Podman machine temp directory (so, it will be possible to remove it on machine stop). This would still isolate this as implementation detail of QEMU machine, so, there will be no need to add it to public machine config.

**Comment by arixmkii** [comment]
Fixed in latest Podman Machine 5 changes.
