### ISSUE TITLE
Cannot use userns=keep-id together with nvidia-container-toolkit on rootless podman

### ISSUE THREAD

**Issue by Clockwork-Muse** [containers/podman#15863]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Attempting to keep the external user id with a rootless container while using the nvidia-container-toolkit fails.

**Steps to reproduce the issue:**

1. [Install the nvidia-container-toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#step-1-install-podman)

2. Run `podman run --rm  --userns keep-id docker.io/nvidia/cudagl:11.4.2-runtime-ubuntu20.04 nvidia-smi`

**Describe the results you received:**
> Error: OCI runtime error: error executing hook `/usr/bin/nvidia-container-toolkit` (exit code: 1)

**Describe the results you expected:**
The normal output of nvidia-smi

**Additional information you deem important (e.g. issue happens only occasionally):**

 - The use of `--security-opt=label=disable` (as in the nvidia install documentation) does not appear to make a difference.
 - Running the same command without `--userns keep-id` succeeds (generates expected output).
 - Deleting the hook and running `id -u` shows the remapped uid.

The real deployment situation is a devcontainer that contains graphical tools needing to access the X11 port, so mapping the uid to the host user is a requirement.

**Output of `podman version`:**

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Wed Dec 31 16:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 12
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: bumblebee
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.15.0-47-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 9103364096
  memTotal: 33545084928
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 1023406080
  swapTotal: 1023406080
  uptime: 4h 16m 33.83s (Approximately 0.17 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/simhoff/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/simhoff/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/user/1001/containers
  volumePath: /home/simhoff/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Wed Dec 31 16:00:00 1969
  GitCommit: ""
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 3.4.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/jammy,now 3.4.4+ds1-1ubuntu1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

 - Have you tested with the latest version of Podman: No - latest in Ubuntu repo
 - Have you checked the Podman Troubleshooting Guide: Yes.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
N/A

**Comment by vrothberg** [comment]
Thanks for reaching out, @Clockwork-Muse!

By the description, it sounds more like an issue of the hook.  Does the hook leave any logs in the journal indicate why it failed?  Probably, the hook wants to run as root and has  a `uid ==0` check.

**Comment by decandia50** [comment]
There are details here in https://github.com/NVIDIA/nvidia-container-runtime/issues/85 but the summary is that the hook tries to run commands like `mknod` and `modprobe` so it fails.

**Comment by vrothberg** [comment]
Thanks, @decandia50!  So the bottom line is that the hook requires to be run with root privileges.

**Comment by decandia50** [comment]
I'll update the other issue with my findings, but you can just ignore the use of the hook completely and do things manually via bind mounts.  At the end of the day, all the hook does is mount the needed files into the container.  If those files exist on the actual system, you can mount them in.  Here's my one liner that does that:
`podman run --userns keep-id $(for file in $(nvidia-container-cli -k list); do find -L $(dirname $file) -xdev -samefile $file; done | awk '{print " -v "$1":"$1}' | xargs) --rm -ti myimage`

What the above does is run `nvidia-container-cli -k list` and get every file, check the `dirname` and run `find` with `-L` to get all the symlinks to the files.  Then the `awk` portion creates a bunch of `-v` statements for mounting (e.g. `-v /dev/nvidiactl:/dev/nvidiactl).  That completely avoids using the hook at all, and just maps in the necessary libraries, devices, and binaries in `/usr/lib64`, `/dev`, and `/usr/bin`.  If you wanted to do something a little fancier like only let the container see GPU1, then you'd need to adjust the `/dev/nvidia*` devices.  But it's all pretty straightforward once you realize this hook isn't magic.

**Comment by elezar** [comment]
@decandia50 as pointed out in https://github.com/NVIDIA/nvidia-container-runtime/issues/85#issuecomment-1254182638 it is not recommented to bypass the hook like that.

Note that since the hook is defined in the OCI hooks directory, podman will invoke the hook directly and not use the NVIDIA Container Runtime which is why you're not seeing any logs (if the hook is failing). 

@Clockwork-Muse As a matter of interest, which version of the NVIDIA Container Toolkit is being used here? There is an issue with our v1.11.0 package that may result in the `/usr/bin/nvidia-container-runtime-hook` file being deleted if the `nvidia-container-toolkit` package is upgraded from v1.10.0 to v1.11.0. Could you confirm the output of the following:
```
ls /usr/bin/nvidia-container*
```
This should contain *both* `nvidia-container-toolkit` and `nvidia-container-runtime-hook`.

**Comment by elezar** [comment]
> Thanks, @decandia50! So the bottom line is that the hook requires to be run with root privileges.

@vrothberg the `mknod` and `modprobe` operations are not required if the NVIDIA kernel modules are loaded and the device nodes already exist on the host. This can also be disabled by setting the `load-kmods = false` option in `/etc/nvidia-container-runtime/config.toml`.

**Comment by Clockwork-Muse** [comment]
@elezar 
```
 $ nvidia-container-toolkit --version
NVIDIA Container Runtime Hook version 1.11.0
commit: d9de4a0
$ ls -al /usr/bin/nvidia-container*
-rwxr-xr-x 1 root root   47472 Sep  5 06:52 /usr/bin/nvidia-container-cli
-rwxr-xr-x 1 root root 4079040 Sep  6 02:23 /usr/bin/nvidia-container-runtime
-rwxr-xr-x 1 root root 2142088 Sep  6 02:23 /usr/bin/nvidia-container-runtime-hook
lrwxrwxrwx 1 root root      38 Sep 15 15:23 /usr/bin/nvidia-container-toolkit -> /usr/bin/nvidia-container-runtime-hook
```

> This can also be disabled by setting the `load-kmods = false`

Same error.

**Comment by Clockwork-Muse** [comment]
Also affects Podman 4.2.1 installed via the Kubic repo:
```
$ podman version
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.18.1
Built:        Wed Dec 31 16:00:00 1969
OS/Arch:      linux/amd64
```

**Comment by Clockwork-Muse** [comment]
... And in contrast, is working when run against podman (4.2.1) installed on Ubuntu inside WSLg...
