### ISSUE TITLE
Dockerfile with squash: true complains that docker daemon needs experimental flags enabled

### ISSUE THREAD

**Issue by kenyee** [containers/podman#15864]
/kind bug

**Description**

Dockerfile with the squash: true parameter:
```
devprod-ci-android-sdk-gradle-agent:
  squash: true
  build_directory: .
  build: |
    USER root
...
```

fails with 
```
FATAL ERROR: Docker error message:
   400 Client Error for https://127.0.0.1:43211/v1.41/build?t=1.devprod-ci-android-sdk-gradle-agent.dmk%3Aa4880cf3-7877-4303-aa7a-25136d191bcd&q=False&nocache=False&rm=True&forcerm=False&pull=False&squash=True: Bad Request ("squash is only supported with experimental mode")

Using `squash` and/or `secret_files` requires a docker daemon with experimental features enabled. See
    https://github.com/docker/docker-ce/blob/master/components/cli/experimental/README.md
```

**Steps to reproduce the issue:**

1. create Dockerfile with squash parameter set to true

2. try building the docker file (the header to this bug report mentions using buildah but the link is invalid)

3. see error

**Describe the results you received:**
fails with 
```
FATAL ERROR: Docker error message:
   400 Client Error for https://127.0.0.1:43211/v1.41/build?t=1.devprod-ci-android-sdk-gradle-agent.dmk%3Aa4880cf3-7877-4303-aa7a-25136d191bcd&q=False&nocache=False&rm=True&forcerm=False&pull=False&squash=True: Bad Request ("squash is only supported with experimental mode")

Using `squash` and/or `secret_files` requires a docker daemon with experimental features enabled. See
    https://github.com/docker/docker-ce/blob/master/components/cli/experimental/README.md
```

**Describe the results you expected:**
build of dockerfile is successful

**Additional information you deem important (e.g. issue happens only occasionally):**
run via minikube --driver=podman
and then docker build

**Output of `podman version`:**

```
podman version
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.18.6
Built:        Tue Sep  6 15:16:02 2022
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.4
Built:        Thu Aug 11 10:43:11 2022
OS/Arch:      linux/arm64
```

**Output of `podman info`:**

```
podman info
host:
  arch: arm64
  buildahVersion: 1.27.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc36.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpuUtilization:
    idlePercent: 96.57
    systemPercent: 1.73
    userPercent: 1.7
  cpus: 4
  distribution:
    distribution: fedora
    variant: coreos
    version: "36"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.19.6-200.fc36.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 24711098368
  memTotal: 26608050176
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.fc36.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.aarch64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 22m 50.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 106825756672
  graphRootUsed: 5708197888
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1660228991
  BuiltTime: Thu Aug 11 10:43:11 2022
  GitCommit: ""
  GoVersion: go1.18.4
  Os: linux
  OsArch: linux/arm64
  Version: 4.2.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

N.A., installed via Homebrew

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OSX M1 macbook...minikube...did "brew upgrade" to make sure I had the latest.
Also tried adding "experimental":"true" to ~/.docker/config.json and restarting everything w/o luck.

**Comment by mheon** [comment]
That doesn't look like a Podman error message. Are you sure Podman is in use, and not Docker?

**Comment by kenyee** [comment]
"docker version" didn't show any running server until podman and minikube were started.
I did look through the podman and buildah repos for that error msg and couldn't find it so I'm a bit baffled as well.

**Comment by afbjorklund** [comment]
If you run minikube with `--driver=podman`, it will run the default runtime (docker or containerd) in a podman container.

If you want to use "podman" for the kubernetes cluster, then you also need to add `--container-runtime=cri-o`

But it does not actively change your docker configuration, unless you also run something like `minikube docker-env` ?

In this particular issue, I think that "docker info" would give more insight than the output from "docker info"...

**Comment by kenyee** [comment]
> But it does not actively change your docker configuration, unless you also run something like `minikube docker-env` ?

I do use:
"eval $(minikube -p minikube docker-env)"
to set the docker env.
I thought podman also included it's own docker daemon..is it just a wrapper over docker?  
 
> In this particular issue, I think that "docker info" would give more insight than the output from "podman info"...

Looks like regular docker:

docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.10.2)
  extension: Manages Docker extensions (Docker Inc., v0.2.9)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.19.0)

**Comment by flouthoc** [comment]
@kenyee Podman is not a wrapper over docker, its entirely different engine/container manager and the error you are seeing is actually coming from `docker` not `podman`. So your environment is using `docker` and not `podman`.

**Comment by afbjorklund** [comment]
> Also tried adding "experimental":"true" to ~/.docker/config.json and restarting everything w/o luck.

Those are the **client** settings.

To change the server settings, you need to do `minikube ssh` and then edit /etc/docker/daemon.json

And restart the daemon to take effect.

You can also the edit the systemd unit files as usual, the the docker (or the systemd) documentation.

**Comment by afbjorklund** [comment]
> Podman is not a wrapper over docker, its entirely different engine/container manager and the error you are seeing is actually coming from `docker` not `podman`. So your environment is using `docker` and not `podman`.

Actually the environment is using **both** (nested containerization). But since it is not possible to use podman-in-podman (it does not support k8s), you will have to use crio-in-podman if you want to replace the default docker-in-docker configuration...

`minikube start --driver=podman --container-runtime=cri-o`

**Comment by afbjorklund** [comment]
Currently `docker-env` is not supported for cri-o runtime, only `podman-env`

In a future release, the legacy docker api will be available for all of them

You can also use `minikube image`

Most likely, Podman endpoint will be deprecated (in minikube, that is). Too much struggle with the clients and incompatible API.

**Comment by kenyee** [comment]
> To change the server settings, you need to do `minikube ssh` and then edit /etc/docker/daemon.json

Ahh...that was a bit I was missing.

Would love to see all this info above in the podman docs 😄 
thx

**Comment by afbjorklund** [comment]
> Would love to see all this info above in the podman docs 😄

I don't think it has anything to do with Podman, but it would be good to update the minikube docs if you find them missing info

**Comment by kenyee** [comment]
> I don't think it has anything to do with Podman

For the Podman part, the explanation above about how it interacts w/ docker is what I found useful and didn't see it in the docs.

**Comment by afbjorklund** [comment]
It is a bit complex, you are running docker pods in a podman system container running in CoreOS on a macOS system... 4 different layers
