### ISSUE TITLE
Podman save / load across machines causes cache misses and rebuilding of images

### ISSUE THREAD

**Issue by samskiter** [containers/podman#15887]
/kind bug

**Description**

I’m trying to save an image (with layers) on one machine and then load it later on another in order to accelerate our CI build pipeline. However, after loading I'm still getting a cache miss even at the first line of my build file. When I re-run my build locally, podman build get's full cache hits and my builds are super fast.

This is a feature that seems to be supported by docker - I *roughly* followed [this](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/caching?view=azure-devops#docker-images) guide to do this (obviously replacing docker for podman).

**Steps to reproduce the issue:**

1. `podman save image`
1. Switch to another machine
1. `podman load image.tar`
1. podman build

**Describe the results you received:**

All instructions in the build file are run.

**Describe the results you expected:**

Instructions that have not changes should be able to use the cached layers from `podman save`

**Additional information you deem important (e.g. issue happens only occasionally):**

I think this is a supported behaviour with docker - I asked on the #crio slack channel and @mheon suggested this is a bug in buildah/podman and that I should file a bug.

I have tried to narrow my dockerignore file to include only the files my build absolutely needs, but even my first `FROM blah` and `RUN` commands are getting cache misses before any `COPY` command.

Potentially related bug: https://github.com/containers/buildah/issues/2954

**Output of `podman version`:**

```
3.4.2
```

**Output of `podman info`:**

NA

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No - using ubuntu so 3.4.2 is the latest.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on MS hosted build agents on Azure Devops.

Keywords:

Podman
build 
load
save
layers

**Comment by mheon** [comment]
@flouthoc PTAL

**Comment by flouthoc** [comment]
Hi @samskiter , If there is a shared registry between two machine running the CI, I'd suggest a better solution which is `--cache-to` and `--cache-from`. See options `--cache-to` and `--cache-from` here https://github.com/containers/buildah/blob/main/docs/buildah-build.1.md#options


So on one machine you can just do `buildah build --layers --cache-to <yourrepo> --cache-from <yourrepo> -t test .` and on second or any other machine just run same command and it will automatically use cache instead of re-running a step.

This tells me that buildah needs a blog for this.

**Comment by baude** [comment]
@flouthoc so is it a bug or are you saying you have a work around.

**Comment by samskiter** [comment]
Hi @flouthoc I don't currently have a shared registry to easily use so I'd prefer to use `save` / `load` if possible. Also don't want to have to add a bunch of --cache-to and --cache-from to all my scripts

**Comment by flouthoc** [comment]
`save` and `load` does carries intermediate images which buildah uses a cache, afaik so i don't think it will hit the cache as is but let me confirm.

**Comment by flouthoc** [comment]
This will not work as is, buildah caching works differently than docker, In order to support this feature I think we must implement filesystem exporters to `--cache-to` and `--cache-from` and let `save` and `load` silently use them for images with `--layers`.

Another method is sharing storage between two machines or using additional stores which is not possible for your scenario as you mentioned so I think implementing the first feature makes more sense here.

But I'm gonna tag @nalind to confirm or point out if i missed anything.

**Comment by samskiter** [comment]
Thanks @flouthoc for the analysis - it would be great if podman could match docker on this feature, but appreciate it sounds like some work to get there.... if there are other workaround or ways I can get the image caching to line up, let me know!

**Comment by samskiter** [comment]
I also considered using a local root directory and caching that, but in some situations I need to combine multiple different builds into one while ensuring that I'm building the latest code - I wouldn't really know how to combine stores in this situation.... I think I may have to go away and try and work out how to use some container store now, but the access permissions to a repository may be tricky.

**Comment by nalind** [comment]
You can save all images with `podman images -aq | xargs podman save -m -o /tmp/images.tar`.  If you're consistently building with `--format docker`, then `podman load`ing the images from the archive first should let the cache logic recognize the images as cache hits.

I say `--format docker` because `save -m` appears to be limited to using Docker format, minor differences between OCI and Docker formats could keep cache hits from happening, and we default to `--format oci`.

**Comment by flouthoc** [comment]
> You can save all images with `podman images -aq | xargs podman save -m -o /tmp/images.tar`. If you're consistently building with `--format docker`, then `podman load`ing the images from the archive first should let the cache logic recognize the images as cache hits.
> 
> I say `--format docker` because `save -m` appears to be limited to using Docker format, minor differences between OCI and Docker formats could keep cache hits from happening, and we default to `--format oci`.

This is a really nice workaround till this is implemented upstream,  just adding a side-note for workaround this can generate final `.tar` really big in size if local storage contains lot of images.

**Comment by samskiter** [comment]
Thanks all, I will check this out asap. One piece of clarification though -
the docs say that the docker format is the default. Is this wrong? See
here: https://docs.podman.io/en/latest/markdown/podman-save.1.html

**Comment by nalind** [comment]
For `save`, docker format is the default.  For `build`, the default image format is OCI, so conversion happens, and I haven't checked lately how converting on save and then reloading affects the cache evaluation logic.

**Comment by samskiter** [comment]
So does this mean I should save with oci?

**Comment by nalind** [comment]
> So does this mean I should save with oci?

`podman save -m` does not currently support OCI formats, so I would say no.

**Comment by samskiter** [comment]
Gotya, thanks! https://github.com/containers/podman/issues/15887#issuecomment-1254036038 worked great, by the way! Is there any way to narrow only to a specific image and its parent layers?

**Comment by nalind** [comment]
It looks like running `podman image history -q` for the final image, filtering out the "<missing>" parents of the base image, would provide a useful result for builds that don't use multiple stages.  For builds that use multiple stages, by their nature, that wouldn't be the complete list of the involved images.

**Comment by samskiter** [comment]
Awesome, thanks again! It's important because over time if I load in a cache of an old build and then some changes are made, the layers will change, but each time I export I will get all the old AND new image layers....

**Comment by samskiter** [comment]
for anyone who finds this in the future, my build commands look like this:

`podman build --format docker --timestamp 0 --tag $IMAGE_NAME .`

My save commands look like this:

`  podman image history -q "${IMAGE_NAME}" | sed '/<missing>/d' | xargs podman save -m -o "$FILENAME"`

And my load command looks like this:

`podman load -i "$FILENAME"`

I do not think the `--timestamp 0` is required though

**Comment by samskiter** [comment]
A semi-related issue - it seems that any `WORKDIR` command in the will invalidate a cache when I switch to a different machine. It seems [Docker has had a similar issue in the past](https://github.com/moby/moby/issues/30081)... This has been pretty reproducible for me is there any way to avoid this aside from prefixing a bunch of commands with `cd foo`? I ensured that the directory exists before the workdir command (`mkdir -p`) but still get the same issue. Could it be that the absolute path is different? Is there any way to customise the context to avoid this? Here's an example log:

```
STEP 5/41: RUN mkdir -p /build/out
--> Using cache ee5af70dcd2bf0cd2937b88a7c55e10e59a67c803768b4d0308634ce32e7fbe7
--> ee5af70dcd2
STEP 6/41: WORKDIR /build
--> 98b4032cbb3
STEP 7/41: ARG CPL_BRANCH
```

This also seems to be happening with the ENTRYPOINT command - again only when it's occurring on different machines. Here's a log (Notice that the caches match up to Step 8/9):

Machine A:
```
STEP 7/9: RUN cp /tmp/qemu-install/bin/qemu-* /usr/local/bin/
--> Using cache 0f25fb2d30af545cc3a4f7c98b5692c0416b53046a7ad631fa7dfeb2791772e2
--> 0f25fb2d30a
STEP 8/9: COPY entrypoint.bash /usr/local/bin/entrypoint.bash
--> Using cache 9b8d93f0a9d00c1a158b15c1860236315e52387d8e712ea091fd36876f9ca1cf
--> 9b8d93f0a9d
STEP 9/9: ENTRYPOINT ["entrypoint.bash"]
COMMIT qemu-aarch64
--> c66f2b8159e
Successfully tagged localhost/qemu-aarch64:latest
c66f2b8159ed65a5a4ae32f3d4b3a6fbaa4f6dd7b91d8d2fd67ef5638dd65b3b
```
Machine B:
```
STEP 7/9: RUN cp /tmp/qemu-install/bin/qemu-* /usr/local/bin/
--> Using cache 0f25fb2d30af545cc3a4f7c98b5692c0416b53046a7ad631fa7dfeb2791772e2
--> 0f25fb2d30a
STEP 8/9: COPY entrypoint.bash /usr/local/bin/entrypoint.bash
--> Using cache 9b8d93f0a9d00c1a158b15c1860236315e52387d8e712ea091fd36876f9ca1cf
--> 9b8d93f0a9d
STEP 9/9: ENTRYPOINT ["entrypoint.bash"]
COMMIT qemu-aarch64
--> 305cccf5186
Successfully tagged localhost/qemu-aarch64:latest
305cccf51864bdc7fbc2b181554e601741cd46fc365986e108d1cfa6b621b805
```

Unsure whether to leave there here or file 1 or even 2 new bugs.... thoughts?

Thanks

Sam

**Comment by samskiter** [comment]
@nalind more bad news - this also seems to be happening with the `ARG` command in my Dockerfile. While your solution is working in general, I'm now hitting into a second layer of issues. I don't support you have any more of those workarounds have you? Or is there any way to see *what* is causing the cache miss? Like what inputs were different?

![6uro74](https://user-images.githubusercontent.com/1271643/192352834-078d0ee0-ea8d-4681-acc8-45ef8ce144e1.jpg)

**Comment by samskiter** [comment]
I'm also assuming that using a container registry won't help me here as there seems to be something about the way podman is calculating the layer cache from the runtime context that is inconsistent between machines rather than something being lost in the save-load process?

**Comment by nalind** [comment]
The cache evaluation includes the candidate image's history, so instructions that change the entry point, workdir, and such matter.
WORKDIR in particular is used as the default destination when a subsequent COPY or ADD is given a relative destination, and as the working directory for subsequent RUN instructions.
Likewise, changes to ARG values can affect the expansion of RUN instruction commands, so the corresponding history entry in the image's config includes ARGs and their values.  That's done to avoid incorrect cache hits when different build invocations get passed different ARG values on the command line.

When none of that's a factor, it's not really clear why, assuming the final image was copied along with the intermediate images, the final image is not being accepted as a cache hit for the final instruction.

**Comment by samskiter** [comment]
@nalind  thanks for the reply - so all of these are identical between the different builds. So far these have proven to invalidate the cache (when run on a different machine but with the same arguments):

- WORKDIR
- ENTRYPOINT
- ARG (when the ARG is passed or is not at the top of the dockerfile)

The above logs show hits followed by misses for e.g. entrypoint - but the command hasn't changed.

**Comment by samskiter** [comment]
Another update, `ENV` command is also doing this :(

IMO this experience is very broken with podman at the minute... is there's anything I can do to help, let me know!

**Comment by samskiter** [comment]
Just wanted to highlight the podman version I'm using here - 3.4.2 - is there any reason to believe that this would be fixed in 4.2?

**Comment by rhatdan** [comment]
There are lots of changes and fixes in each release, so I guess it is worth a try.

**Comment by samskiter** [comment]
@rhatdan Thanks for the reply - I have had a good go but have been unable to get 4.2 installed and working on the Azure hosted ubuntu 20.04 machines...

**Comment by rhatdan** [comment]
I am going to close this since I assume it is fixed, reopen if I am mistaken.
