### ISSUE TITLE
RFE: Expose `system reset` to the API / remote CLI

### ISSUE THREAD

**Issue by benoitf** [containers/podman#15886]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Sometimes, podman machine is not working as expected. One example is https://github.com/containers/podman/issues/15526
But to call `podman system reset` we need first to ssh into the machine which is not so convenient for users.

**Steps to reproduce the issue:**

1. podman machine ssh

2. podman system reset

3.

**Describe the results you received:**

2 steps

**Describe the results you expected:**

Add a REST API to call the reset command.
It will allow tools like Podman Desktop to add a `reset machine` option

in addition a `podman machine reset` would help end users.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
4.2.1
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ashley-cui** [comment]
Is this a good idea? I feel like allowing users to reset settings from another machine via an API (think in non podman-machine scenarios) feels dangerous. I'd much rather have podman machine do a `podman machine ssh podman system reset` (as a singular command, as podman machine ssh takes args).

**Comment by mheon** [comment]
The request from the desktop team was a way to "factory reset" a VM that is having problems. In that context, it seems reasonable to expose some way to do this - unless we want to require something like `podman machine ssh podman system reset`

**Comment by ashley-cui** [comment]
I'd be okay with something like a podman machine reset command, but that would literally just be a wrapper around `podman machine ssh podman system reset`, which seems like a reasonable command to just run from desktop

**Comment by baude** [comment]
what does factory reset mean? the contents of the vm are reset or the vm itself is reset?

**Comment by benoitf** [comment]
From a 'Client' point of view, after the reset, everything should work again and it includes data loss.

It may include a podman reset or a vm reset as well. (Sometimes podman machine is not starting anymore so podman machine ssh will hang as well as the machine is not responding)

so it may be:
if machine is responding: try to to do the system reset
if machine is not responding: wipe content or reinit it.
