### ISSUE TITLE
CI broken: lint, ioutil

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#15889]
CI Validate is [broken on aarch64](https://cirrus-ci.com/task/4579010779807744?logs=main#L16)

Looks like a merge collision between #15871 and #15842. @cevich, @ashley-cui PTAL.

**Comment by cevich** [comment]
FWIW: I spent some time trying to figure out a way to detect deprecated modules in golang.  There's nothing in golangci-lint that I could find.  I did find some `go list...` magic, but couldn't get it to work in my copy-paste from stackoverflow.  Though I did come across a comment pointing to an (open) RFE in upstream golang that should make this easier in the future.
