### ISSUE TITLE
RFE: Add `--dry-run` mode on `kube play` command/REST API

### ISSUE THREAD

**Issue by benoitf** [containers/podman#15903]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

`podman kube play` command is applying a subset of supported elements from a kubernetes YAML file.
so it might be good to know in advance what will be done, elements that will be skipped, etc before applying the command as we may not want to proceed this command depending on the supported items

**Describe the results you expected:**
`--dry-run` option on CLI/REST API to be able to check what would be done so we can better track/notify/report the user to what will be done

**Additional information you deem important (e.g. issue happens only occasionally):**

https://github.com/containers/podman/issues/15902 is more important

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by rhatdan** [comment]
quadlet --dryrun was just added. https://github.com/containers/podman/pull/16926

**Comment by vrothberg** [comment]
@vyasgun, please wait before opening a PR/starting to work on it.

@containers/podman-maintainers, I am a bit afraid of `--dry-run` making the kube-code even more spaghetti-ish.  I think it's time to think about refactoring the code into a single package; currently the code is scattered over multiple packages and (IMO _very_) hard to read.

I am personally not a fan of a `--dry-run` flag as it will add permanent costs: with each new supported field, we had to update what's being created and how and add tests for it.  Quadlet is a different story as it is a generator where a --dry-run flag is cheap and easy to implement with no future maintenance costs.

As @benoitf mentions above, https://github.com/containers/podman/issues/15902 is more important.

**Comment by rhatdan** [comment]
I don't see this moving forward, I think fixing progress info on pull is the best we can do. Closing.

**Comment by baude** [comment]
for the sake of history,  can you perhaps show what the output of the command would look like?
