### ISSUE TITLE
Podman version 4.2.1 in MacOS Error: missing command 'podman COMMAND

### ISSUE THREAD

**Issue by JulianLeonel3004** [containers/podman#15901]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Issue of MacOs, message Error: missing command 'podman COMMAND

**Steps to reproduce the issue:**

1. delete ssh of macOs
2. uninstall podman with brew
3. install podman 

**Describe the results you received:**
Result:
When finish of installation, prints all normal message about podman use, but in de final line prints
`Error: missing command 'podman COMMAND'`

After if you run `podman ps`, podman response is

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: connection to bastion host (ssh://core@localhost:56601/run/user/1744420170/podman/podman.sock) failed: dial tcp [::1]:56601: connect: connection refused
```
**Describe the results you expected:**
When install podman the result expected is not receive error message in the final line
When run `podman ps` the result expected is the process of container and if there aren't containers, result just be title of description of process.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 4.2.1
```

**Output of `podman info`:**

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: connection to bastion host (ssh://core@localhost:56601/run/user/1744420170/podman/podman.sock) failed: dial tcp [::1]:56601: connect: connection refused
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
el paquete podman no está instalado ---> not found package podman 
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Comment by rhatdan** [comment]
How are you installing Podman Using Brew or the install link?
@ashley-cui @baude PTAL

**Comment by JulianLeonel3004** [comment]
Hi, @rhatdan yes, I runned `brew install podman`

**Comment by rhatdan** [comment]
It would seem that there is a path issue, but I am by far not a Mac expert.

**Comment by ashley-cui** [comment]
The error is also expected behavior, it's reminding you that you need a secondary command after `podman` ie, `podman run alpine` etc.

**Comment by JulianLeonel3004** [comment]
@ashley-cui i stoped and started podman vm 
steps:

1. `podman machine stop`
res: `Machine "podman-machine-default" stopped successfully`

2. `podman machine start`
res:
```
Starting machine "podman-machine-default"
Waiting for VM ...
Error: dial unix /var/folders/wz/wvtknqz9249ct804ffv28bhslzlg__/T/podman/podman-machine-default_ready.sock: connect: no such file or directory
```

**Comment by ashley-cui** [comment]
Please stop your machine before doing a rm.
