### ISSUE TITLE
netavark: unable to append rule '! -d ff00::/8 -j MASQUERADE' to table 'nat'

### ISSUE THREAD

**Issue by JasonCubic** [containers/podman#15950]
/kind bug

**Description**

kind create cluster fails due to a netavark issue that I do not understand very clearly.

Some details:
* I am on a corporate network with a proxy
* Using a rootful podman machine
* I had to set a custom resolv.conf due to our network dns (podman can pull down images now)
* I added a root ca trust to podman machine

**Steps to reproduce the issue:**

1. be on my corporate network (the only way to get to the outside is through a proxy)
2. run kind create cluster

**Describe the results you received:**

kind fails to create a basic network.  If i remove "--net kind" from the command in the error message then that command completes with no error.  So the error scope seems to be with the network.

The error
```bash
λ kind create cluster
enabling experimental podman provider
Creating cluster "kind" ...
 • Ensuring node image (kindest/node:v1.25.2) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.25.2) 🖼
 • Preparing nodes 📦   ...
 ✗ Preparing nodes 📦 
ERROR: failed to create cluster: command "podman run --name kind-control-plane --hostname kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --tmpfs /tmp --tmpfs /run --volume 957df470e84b1edef79cc743e4ac54c42760c13c5ed5297258ad34c8b0c214a0:/var:suid,exec,dev --volume /lib/modules:/lib/modules:ro -e KIND_EXPERIMENTAL_CONTAINERD_SNAPSHOTTER 
--detach --tty --net kind --label io.x-k8s.kind.cluster=kind -e container=podman -e HTTPS_PROXY=http://my.corp.proxy.net:8080/ -e https_proxy=http://my.corp.proxy.net:8080/ -e 'NO_PROXY=fc00:f853:ccd:e793::/64,10.89.0.0/24,localhost,127.0.0.1,afewotheraddresses.com,host.docker.internal,host.container.internal,10.96.0.0/16,10.244.0.0/16,kind-control-plane,.svc,.svc.cluster,.svc.cluster.local' -e 'no_proxy=fc00:f853:ccd:e793::/64,10.89.0.0/24,localhost,127.0.0.1,afewotheraddresses.com,host.docker.internal,host.container.internal,10.96.0.0/16,10.244.0.0/16,kind-control-plane,.svc,.svc.cluster,.svc.cluster.local' -e HTTP_PROXY=http://my.corp.proxy.net:8080/ -e http_proxy=http://my.corp.proxy.net:8080/ --publish=127.0.0.1:51681:6443/tcp -e KUBECONFIG=/etc/kubernetes/admin.conf docker.io/kindest/node@sha256:9be91e9e9cdf116809841fc77ebdb8845443c4c72fe5218f3ae9eb57fdb4bace" failed with error: exit status 127

Command Output: Error: netavark (exit code 1): unable to append rule '! -d ff00::/8 -j MASQUERADE' to table 'nat': code: 2, msg: ip6tables v1.8.7 (legacy): Couldn't load target `MASQUERADE':No such file or directory

Try `ip6tables -h' or 'ip6tables --help' for more information.
```

the network info:

```bash
λ podman network inspect kind
[
     {
          "name": "kind",
          "id": "3f08d6d202bb19911c2f214e43fca44d10e307b1b08a4a9b482faa40e3723d32",
          "driver": "bridge",
          "network_interface": "podman1",
          "created": "2022-09-26T16:30:47.508736-07:00",
          "subnets": [
               {
                    "subnet": "fc00:f853:ccd:e793::/64",
                    "gateway": "fc00:f853:ccd:e793::1"
               },
               {
                    "subnet": "10.89.0.0/24",
                    "gateway": "10.89.0.1"
               }
          ],
          "ipv6_enabled": true,
          "internal": false,
          "dns_enabled": true,
          "ipam_options": {
               "driver": "host-local"
          }
     }
]
```

**Describe the results you expected:**

kind creates a basic cluster

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
λ podman version
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.16.15
Git Commit:   62b324ddf718411b1d4d0ba8117c632f7f984a38
Built:        Wed Sep  7 06:08:04 2022
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.4
Built:        Thu Aug 11 07:42:17 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.4-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: '
  cpuUtilization:
    idlePercent: 99.79
    systemPercent: 0.13
    userPercent: 0.09
  cpus: 12
  distribution:
    distribution: fedora
    variant: container
    version: "36"
  eventLogger: journald
  hostname: CTNAL0064503610
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.19.128-microsoft-standard
  linkmode: dynamic
  logDriver: journald
  memFree: 24493297664
  memTotal: 26707955712
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.6-2.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.6
      commit: 18cf2efbb8feb2b2f20e316520e0fd0b6c41ef4d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 7516192768
  swapTotal: 7516192768
  uptime: 0h 50m 18.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 269490393088
  graphRootUsed: 2131468288
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1660228937
  BuiltTime: Thu Aug 11 07:42:17 2022
  GitCommit: ""
  GoVersion: go1.18.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```
kind version:
```bash
λ kind version
kind v0.16.0 go1.19.1 windows/amd64
```

this is podman on windows

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes 
maybe I don't know what I should be looking for though??

**Additional environment details (AWS, VirtualBox, physical, etc.):**
windows 10 21H2 Build 19044.2006

**Comment by mheon** [comment]
Any more details about the environment Kind is running here? Is that command running straight on the VM, in another container?

Any chance the `ip6table_nat` module is not loaded?

**Comment by JasonCubic** [comment]
I tried it in PowerShell and cmder.  I didn't install kind on the podman machine vm it's in windows.  How do I troubleshoot the ip6table_nat module?

**Comment by mheon** [comment]
Oh, this is WSL2, not a VM.

@n1hility Any idea if WSL2 supports v6 and/or loads the IPv6 NAT kernel modules?

**Comment by n1hility** [comment]
@mheon yes its compiled in:
`zcat /proc/config.gz | grep IP6_NF_NAT
CONFIG_IP6_NF_NAT=y
`

Not sure why the masq rule / load fails. I will try to reproduce

**Comment by n1hility** [comment]
@JasonCubic Ah looks like you are using WSL 1 -  kernel: 4.19.128-microsoft-standard

WSL1 is deprecated and only supports partial emulation of linux system calls 

Try switching to WSL2 like so:
`wsl --set-version podman-machine-default 2`

Depending on the state of your instance you might need to flip the default and recreate it
```
wsl --set-default-version 2
podman machine stop
podman machine rm
podman machine init
podman machine start
```

**Comment by JasonCubic** [comment]
hmm I wonder what's going on there.  I am using WSLv2 as default.

```powershell
> Get-ItemPropertyValue `
      -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss `
      -Name DefaultVersion
```

```bash
λ wsl -l -v
  NAME                      STATE           VERSION
* Ubuntu-22.04              Stopped         2
  Ubuntu-20.04              Stopped         2
  podman-machine-default    Running         2
  Ubuntu-18.04              Stopped         2
  Debian                    Stopped         2
```

I stopped and rm'd the podman machine a few times and it always comes back to 4.19.128-microsoft-standard.  I even toggled the wsl default to 1 and then back to 2.  

I have a win 11 box at home and sure enough the kernel on its `podman info` is WSL2.  

Could there be a bug with podman and my version 10 of windows?  Is there a way to force the newer kernel?

**Comment by JasonCubic** [comment]
@n1hility Good news!  My problem is resolved.  My corp manages my os updates, but I have local admin so I was able to fix this one.  My corp had not sent out any updates to the WSL kernel.  I was using WSLv2 but, even with WSLv2 the older WSL kernel version seems to have been the issue.

If anyone else runs into this here is how I solved it:
- Was able to see the older kernel in WSL by running: `wsl --status`
- I stopped podman machine and rm'd it
- I stopped all running WSL distro's using: `wsl --shutdown`
- Went and got a WSL kernel update here:  <https://www.catalog.update.microsoft.com/Search.aspx?q=wsl>
- I clicked to dowload the newest cab for my architecture x64
- I opened that cab file using 7-zip and extracted the file: wsl_update_x64.msi
- I ran this msi and went through an installer wizard (basically just pressed OK once, there were no options to choose)
- when I ran `wsl --status` the kernel was the newer updated version
- recreated and started podman machine

and kind works now.  :-)

This one is solved, it was my WSL kernel version.  Thank you for the help.

**Comment by tppalani** [comment]
Does any one resolved the issue?
