### ISSUE TITLE
Valid docker image not loading

### ISSUE THREAD

**Issue by chrispyatt** [containers/podman#15963]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am trying to load an image made using docker on a previous system. I know the image works as it has been used for several months in our lab. We've since upgraded the server from RHEL7 to RHEL8 and with that, moved to podman as that is what 'yum install docker' gives us now. The issue is that podman does not seem to like the image we were using previously. The load command is exactly the same as that used previously with docker.

**Steps to reproduce the issue:**

1. set TMPDIR to sufficiently large volume

2. podman load -i image.tar.gz

**Describe the results you received:**

```
Error: payload does not match any of the supported image formats:
 * oci: initializing source oci:megaqc_all4.tar.gz:: open megaqc_all4.tar.gz/index.json: not a directory
 * oci-archive: loading index: open /var/tmp/oci640955690/index.json: no such file or directory
 * docker-archive: writing blob: adding layer with blob "sha256:62a747bf1719d2d37fff5670ed40de6900a95743172de1b4434cb019b56f30b4": Error processing tar file(exit status 1): potentially insufficient UIDs or GIDs available in user namespace (requested 0:42 for /etc/gshadow): Check /etc/subuid and /etc/subgid if configured locally: lchown /etc/gshadow: invalid argument
 * dir: open megaqc_all4.tar.gz/manifest.json: not a directory
tory
```

**Describe the results you expected:**

I expect the image to load and be available via 'podman images'

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7

Built:      Tue Apr 19 11:16:32 2022
OS/Arch:    linux/amd64
/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.24.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.0-1.module+el8.6.0+14877+f643d2d6.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 87b7a9037cbd1d81288bdf2d6705dfda889f7cf9'
  cpus: 2
  distribution:
    distribution: '"rhel"'
    version: "8.6"
  eventLogger: file
  hostname: [removed]
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1678600513
      size: 1
    uidmap:
    - container_id: 0
      host_id: 1678737008
      size: 1
  kernel: 4.18.0-372.16.1.el8_6.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 1152700416
  memTotal: 8140886016
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.0.3-2.module+el8.6.0+14877+f643d2d6.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.3
      spec: 1.0.2-dev
      go: go1.17.7
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /run/user/1678737008/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-2.module+el8.6.0+14877+f643d2d6.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 4203360256
  swapTotal: 4290768896
  uptime: 1030h 24m 11.26s (Approximately 42.92 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /path/to/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /path/to/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1678737008/containers
  volumePath: /path/to/.local/share/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1650363392
  BuiltTime: Tue Apr 19 11:16:32 2022
  GitCommit: ""
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.2
: Tue Apr 19 11:16:32 2022
  GitCommit: ""
  GoVersion: go1.17.7
  OsArch: linux/amd64
  Version: 4.0.2

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman.x86_64             2:4.0.2-6.module+el8.6.0+14877+f643d2d6              @rhel-8-for-x86_64-appstream-rpms
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
This looks like it is fixed in podman 4.2?

**Comment by vrothberg** [comment]
> This looks like it is fixed in podman 4.2?

What exactly?

I see `potentially insufficient UIDs or GIDs available in user namespace (requested 0:42 for /etc/gshadow): Check /etc/subuid and /etc/subgid if configured locally: lchown /etc/gshadow: invalid argument`. @chrispyatt, can you paste the output of the two files?

Cc: @giuseppe

**Comment by mheon** [comment]
From the `podman info` provided:
```
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1678600513
      size: 1
    uidmap:
    - container_id: 0
      host_id: 1678737008
      size: 1
```

No UIDs and GIDs are allocated except for a single one. Not actually a tmpdir problem, then. Sorry @rhatdan 

In my defense, that error message is not particularly readable... Maybe we should de-emphasize the ENOENT errors and emphasize the transport that actually got further and produced a unique error?

@chrispyatt Your user is most likely missing an entry in `/etc/subuid` and `/etc/subgid`. Once added, you will need to run `podman system reset`.

**Comment by chrispyatt** [comment]
I have added the appropriate entry to `/etc/subuid` and `/etc/subgid` and run `podman system reset`.

I now get the following error:

```
Error: payload does not match any of the supported image formats:
 * oci: initializing source oci:megaqc_all4.tar.gz:: open megaqc_all4.tar.gz/index.json: not a directory
 * oci-archive: loading index: open /var/tmp/oci3233845278/index.json: no such file or directory
 * docker-archive: writing blob: adding layer with blob "sha256:d0447645e2e79701b993f151efa7fa893487ee4d49b73fc464febd443af1ca32": Error processing tar file(exit status 1): write /root/.cache/pip/http/1/b/1/2/f/1b12fd6675aa4decf8fb81ec8bf37a69ee5e7e5a8195846d4c3fa6da: no space left on device
 * dir: open megaqc_all4.tar.gz/manifest.json: not a directory
```

Do I need to configure something else to point podman away from /var and /root for the processes mentioned in the error message?

**Comment by giuseppe** [comment]
are you running out of disk space?  Could you use a different directory for the storage (you can override with `podman --root $PATH_TO_STORAGE ...`)

**Comment by chrispyatt** [comment]
Thanks that seems to have fixed the issue. When I actually go to run the image though I get the error below:

```
/usr/bin/env: error while loading shared libraries: libc.so.6: cannot change memory protections
```

I've looked at #3234 (tried reinstalling selinux, etc) but not managed to get past this yet.

**Comment by giuseppe** [comment]
not sure what could be.  That seems to depend from the image payload.  Is the image public so I can access it?

Otherwise, you might need to strace the container process and see what syscall fails.  It could be seccomp, try adding `--security-opt seccomp=unconfined` and see if that helps

**Comment by chrispyatt** [comment]
Disabling SELinux got the container running (ish), but I would prefer to have SELinux enabled. Passing a local volume using `-v` changes the error to one saying `SELinux relabelling of ... is not allowed` (I'm unsure whether this solves or just masks the previous error), so perhaps this is a local server config issue.

**Comment by rhatdan** [comment]
What AVCs are you seeing

sudo ausearch -m avc -ts recent

**Comment by rhatdan** [comment]
You can also run the container with SELinux disabled

podman run --security-opt label=disabled ...

**Comment by chrispyatt** [comment]
Running with `--security-opt label=disable` doesn't seem to change anything. The output of `sudo ausearch -m avc -ts recent` (last entry) is below:
```
time->Fri Sep 30 11:38:59 2022
type=PROCTITLE msg=audit(1664534339.653:566239): proctitle=2F7573722F62696E2F656E76007368002F656E747279706F696E742E7368002F73746172742E7368
type=SYSCALL msg=audit(1664534339.653:566239): arch=c000003e syscall=10 success=no exit=-13 a0=7f4a32d17000 a1=196000 a2=0 a3=802 items=0 ppid=4103349 pid=4103418 auid=1678737008 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=3020 comm="entrypoint.sh" exe="/usr/bin/env" subj=system_u:system_r:container_t:s0:c134,c918 key=(null)
type=AVC msg=audit(1664534339.653:566239): avc:  denied  { read } for  pid=4103418 comm="entrypoint.sh" path="/lib/x86_64-linux-gnu/libc-2.31.so" dev="dm-2" ino=1553194 scontext=system_u:system_r:container_t:s0:c134,c918 tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=0
```

**Comment by rhatdan** [comment]
Could you run 
$ sudo dnf -y reinstall container-selinux
$ restorecon -R -v ~
And then try it again.

**Comment by chrispyatt** [comment]
My IT dept seems to have fixed the SELinux relabelling problem so now it runs (kind of). Thanks for your help.

Is there anything different with Podman vs Docker with respect to external database permissions? The image links out to a postgresql database on the server but is currently giving me Ident Authentication errors that I don't remember seeing before. Just trying to work out whether that's a new server config issue or a Podman difference.

**Comment by rhatdan** [comment]
on Rootful there is no difference.  If you have the database on a volume in rootless mode, then it might not have the correct permissions on the database then expected.  You could attempt to add a volume flag on themount of :U

**Comment by rhatdan** [comment]
Please attach the AVCs you are seeing?

**Comment by aadilayub** [comment]
I think I'm running into this issue right now as well, on Fedora Silverblue 38. Running the command after running `sudo setenforce 0`, as well as running the command with `sudo` yielded the same result.

[aadil@fedora 4-react-app]$ podman image load -i react-app.tar 
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Error: payload does not match any of the supported image formats:
 * oci: initializing source oci:react-app.tar:: open react-app.tar/index.json: not a directory
 * oci-archive: loading index: open /var/tmp/oci2062792976/index.json: no such file or directory
 * docker-archive: Source image rejected: Running image docker-archive:react-app.tar:localhost/react-app:latest is rejected by policy.
 * dir: open react-app.tar/manifest.json: not a directory

Is this caused only by colons in filenames, or does it happen with tags too?

For context:

$ podman version
Client:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.20.4
Built:        Fri May 26 22:58:48 2023
OS/Arch:      linux/amd64
