### ISSUE TITLE
Error message "this function is not implemented for windows"

### ISSUE THREAD

**Issue by dancohen21** [containers/podman#15966]
/kind bug

after running 4.3.0-RC1 MSI

C:\>where podman.exe
C:\Program Files\RedHat\Podman\podman.exe

C:\>podman --help
time="2022-09-27T13:51:19-06:00" level=error msg="this function is not implemented for windows"

C:\>podman machine list
time="2022-09-27T13:51:22-06:00" level=error msg="this function is not implemented for windows"

Running Win 10 20H2 (19042.2006)

**Comment by huangzhenming** [comment]
same issue occurred

**Comment by dancohen21** [comment]
Update - uninstalled 4.3 and reinstalled 4.2.1 and error went away

**Comment by ashley-cui** [comment]
Closed via https://github.com/containers/common/pull/1169
