### ISSUE TITLE
Podman load unnecessarily adds 'docker.io/library' prefix

### ISSUE THREAD

**Issue by jjenne-cisco** [containers/podman#15974]
/kind bug

**Description**

When using podman to load an image from file, unlike docker, it will prefix the image name with `docker.io` unless the repo tag contains a dot (`.`).

**Steps to reproduce the issue:**

1. Create an image tarball, name it `<something>/<something>`
```
root@ubuntu:~# printf 'FROM scratch\n' | podman build -
STEP 1/1: FROM scratch
COMMIT
--> c82a5f2479a
c82a5f2479a6966e8ab70f9e424b385367c17285e00e4eecbf4f8a6b460f9bb1
root@ubuntu:~# podman save c82a > img.tar
root@ubuntu:~# skopeo copy docker-archive:img.tar docker-archive:new-img.tar:abc/def
Getting image source signatures
Copying blob 5f70bf18a086 done
Copying config c82a5f2479 done
Writing manifest to image destination
Storing signatures
```

2. Load that image
```
root@ubuntu:~# podman load -i new-img.tar
Getting image source signatures
Copying blob 5f70bf18a086 [--------------------------------------] 0.0b / 0.0b
Copying config c82a5f2479 done
Writing manifest to image destination
Storing signatures
Loaded image(s): docker.io/abc/def:latest
root@ubuntu:~# podman images
REPOSITORY         TAG         IMAGE ID      CREATED         SIZE
docker.io/abc/def  latest      c82a5f2479a6  45 seconds ago  2.61 kB
```

**Describe the results you received:**

The image repository had been prefixed with the `docker.io` domain when loading an image I have built and named myself.

(Seems to be using something like [`ParseNormalizedNamed`](https://github.com/distribution/distribution/blob/main/reference/normalize.go#L32))

**Describe the results you expected:**

Let's load the exact same image with docker:
```
root@ubuntu:~# docker load -i new-img.tar
5f70bf18a086: Loading layer [==================================================>]  1.024kB/1.024kB
Loaded image: abc/def:latest
root@ubuntu:~# docker images
REPOSITORY   TAG       IMAGE ID       CREATED          SIZE
abc/def      latest    c82a5f2479a6   53 seconds ago   0B
```
This is what I expected. The repository would simply be `abc/def`, as this is just an image loaded from file - unrelated to any registry.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens consistently, even with names that have no repository `abc` would become `docker.io/library/abc`. However, for repository names with a dot (`.`) in it, I get the expected result:
```
root@ubuntu:~# skopeo copy docker-archive:img.tar docker-archive:another.tar:cisco.com/product
Getting image source signatures
Copying blob 5f70bf18a086 done
Copying config c82a5f2479 done
Writing manifest to image destination
Storing signatures
root@ubuntu:~# podman load -i another.tar
Getting image source signatures
Copying blob 5f70bf18a086 skipped: already exists
Copying config c82a5f2479 done
Writing manifest to image destination
Storing signatures
Loaded image(s): cisco.com/product:latest
```

(This is for a use case that distributes images via a file rather than a registry, having to set a RepoTag that looks like a valid registry does not reflect the fact that this image cannot be pulled)

**Output of `podman version`:**

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.1.2, commit: '
  cpus: 6
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: ubuntu
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.0-30-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 2655412224
  memTotal: 6222995456
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: ea1fe3938eefa14eb707f1d22adff4db670645d6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 0
  swapTotal: 0
  uptime: 19m 31.41s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 3.4.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/jammy,now 3.4.4+ds1-1ubuntu1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Comment by mheon** [comment]
Any chance you can try with a more recent Podman - 4.2.x being preferable? 3.4 around a year old, and a lot has happened upstream since then.

**Comment by vrothberg** [comment]
> This is what I expected. The repository would simply be abc/def, as this is just an image loaded from file - unrelated to any registry.

When using docker, `abc/def` implies `docker.io`:
```
~ $ sudo docker push abc/def
Using default tag: latest
The push refers to repository [docker.io/abc/def]
```

You can still refer to the image as `abc/def` in Podman.

Besides the expectation/surprise, is there a specific use case that would break?

At the current time, I see it as expected behavior and not as a bug. But I may be missing a nuance.

**Comment by jjenne-cisco** [comment]
Thanks for taking a look!

> When using docker, `abc/def` implies `docker.io`

I think what I'd say here is that docker implies the default registry at the time of the `push` (which I think is right), whereas podman defaults to it in the local registry, making the output of `podman images` misleading.

My concern would be in our use case:
* we distribute a file unrelated to a registry `abc/def`
* load it with `podman load -i`
* `podman images` indicates that the file that has been distributed belongs to the default registry, `docker.io`
* this may imply that this loaded tarball has a registry associated with it, which is confusing for a user

I understand that providing a default registry is useful when pushing simply-named images, but would `images` when loaded from file be a reasonable exception for name normalisation? By all means, if attempting to push the registry-less image then docker's behaviour can be adopted.

**Comment by vrothberg** [comment]
Thanks for elaborating, @jjenne-cisco.

> I think what I'd say here is that docker implies the default registry at the time of the push (which I think is right), whereas podman defaults to it in the local registry, making the output of podman images misleading.

Yes, there is a difference between the two tools.  I am personally not a fan of the implicit `localhost/` prefix but we need to keep it for backwards compatibility.  Short names (or not fully-qualified image names) are a main difference in how Podman and Docker handle images (more on that in https://www.redhat.com/sysadmin/container-image-short-names).

In this specific case:

The manifest inside `new-img.tar` explicitly mentions `docker.io/abc/def:latest` as the name.  So `podman load` is behaving as expected/correctly in that regard.  The `docker.io` prefix is set by `skopeo copy`.  If the manifest in the tar mentioned `abc/def:latest`, `podman load` would prefix it with `localhost/`.

**Comment by jjenne-cisco** [comment]
Ok great, thanks for your help. I should have checked the `new-img.tar` manifest.

So it looks like my issue is with `skopeo` then. The `localhost/` prefix, though unfortunate, at least doesn't imply a remote registry in my use case.

Out of interest, is there any way to load an image from file without that backwards-compatible prefix? CLI flag or environment variable? Other than that I'm happy to close the issue.

**Comment by vrothberg** [comment]
> Ok great, thanks for your help. I should have checked the `new-img.tar` manifest.

No worries at all.  There are rabbit holes all over the place w.r.t. to name resolution and normalization. `docker images`, for instance, would hide `docker.io` from the output entirely.

> So it looks like my issue is with `skopeo` then. The `localhost/` prefix, though unfortunate, at least doesn't imply a remote registry in my use case.

`localhost/` is special in the sense that it can be "just a local" image or refer to an image on registry running on `localhost` which is a valid use case as well.

In theory, `containers/storage` can store images without `localhost/`. Pulling in @mtrmac, the SME of the `containers/image` library.

> Out of interest, is there any way to load an image from file without that backwards-compatible prefix? CLI flag or environment variable? Other than that I'm happy to close the issue.
 
I do not know of a way.  We generally enforce a fully-qualified name (or none) when storing images.

My recommendation is to use fully-qualified names in all circumstances to avoid running into such issues.  Short names _may_ be interpreted differently due to their inherent ambiguity and the different defaults of Podman, Docker, etc.  In case you want to distinguish "local" from "remote" images, the `localhost/` prefix may actually be a good option.

**Comment by mtrmac** [comment]
> In theory, `containers/storage` can store images without `localhost/`.

No; code all over enforces that `storage.Image.Names` has semantics as per `reference.ParseNormalizedNamed`, i.e. a registry is always specified (even if possibly only implied). That’s basically why we have the `localhost/` prefix for names where a registry is not implied.

---

See https://github.com/containers/image/blob/3a6e77d3097cb9982054ca7b282708c47e01e3e7/docker/internal/tarfile/writer.go#L237-L252 for the history of why the default is specifically `docker.io`; it’s one of the consequences of the (fairly inconsistent) way projectatomic/docker added the concept of search registries.

---

Regardless of what tag is used in the archive, you can have control over the destination name by using `skopeo copy docker-archive:… containers-storage:[$options]$yourname`  instead of `podman load`. Admittedly figuring out, and maintaining, $options, is a hassle.

**Comment by vrothberg** [comment]
@jjenne-cisco are you good to go?

**Comment by legaul-cisco** [comment]
We found that `podman build . -t foo` tags the image with `docker.io/library/foo`, so even if the `podman load` behaviour is explained then there may be something else to look at here? jjenne-cisco should be able to give more detail on Monday.

**Comment by jjenne-cisco** [comment]
Hi @vrothberg, yes I'm happy to close this issue now. Thanks, for pointing me towards the skopeo behaviour.
