### ISSUE TITLE
podman images on Quay lack documentation

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#15989]
The official [Podman images on Quay](https://quay.io/repository/containers/podman?tab=info) lack documentation on how to use them.

I miss some text on how to use them in a specific context. Ideally something to copy-paste. Likely the Skopeo and Buildah images have the same issue.

cc: @cevich @rhatdan @TomSweeneyRedHat

**Comment by cevich** [comment]
Hey! At least they have ***SOME*** documentation :rofl: 

I think I can remedy this pretty easily by just linking to the "how to use" sections of the relevant READMEs.

**Comment by cevich** [comment]
Ha! The description thingy supports markdown.  So I just copy-pasted the README.  I'll do the same for Skopeo and Buildah.

**Comment by cevich** [comment]
Speaking of docs....I found (to my surprise) [some docs on the quay API.](https://docs.projectquay.io/api_quay.html)  Browsing through the Swagger quickly, [there is a call for updating the description.]https://docs.quay.io/api/swagger/#!/repository/updateRepo): `PUT /api/v1/repository/{repository}`.  I'll open a Jira card to add this into our build automation.

**Comment by vrothberg** [comment]
Awesome, thanks a lot @cevich !!!
