### ISSUE TITLE
Create Image without Internet connection on Windows

### ISSUE THREAD

**Issue by brainbytes42** [containers/podman#15995]
_[Thanks @mheon for your quick reply @ [#14698](https://github.com/containers/podman/issues/14698#issuecomment-1262272190)!]_

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug   (... I think?)

**Description**

We're trying to run podman (v. 4.2.1) on a development-machine running Windows 10 / WSL *without internet connection*. (We can push files only manually.)
Even when using a local --image-path, it wouldn't work, as it tries to download several packages on `machine init` or says it has a directory(?!).

Any help how to use completely offline on Windows would be much appreciated. Thanks!

**Steps to reproduce the issue:**

```
C:\>podman machine init
```

**Describe the results you received:**
```
Error: head request failed: https://github.com/containers/podman-wsl-fedora/releases/latest/download/rootfs.tar.xz: Head "https://github.com/containers/podman-wsl-fedora/releases/latest/download/rootfs.tar.xz": dial tcp: lookup github.com: no such host
```

Or for a local image (Or did I mess it up here? New to podman...):
```
C:\>podman machine init --image-path "C:\Austausch\rootfs.tar.xz"
Error: open C:\Users\adminois\.local\share\containers\podman\machine\wsl\cache: is a directory

C:\>podman machine init --image-path "C:\Austausch\fedora-coreos-36.20220522.1.0-qemu.aarch64.qcow2.xz"
Error: open C:\Users\adminois\.local\share\containers\podman\machine\wsl\cache: is a directory
```

**Describe the results you expected:**
Podman-magic :-)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

It is Version 4.2.1, but the output is:
```
C:\>podman version
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.2.1/libpod/_ping": dial unix ///run/podman/podman.sock: connect: Ein ungültiges Argument wurde angegeben.
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine, Win 10 + WSL

**Comment by n1hility** [comment]
@cdoern want to take a look at this one. This issue is that image-path is not properly handling absolute paths.

Relative works (// cc @brainbytes42 for a workaround)

```
podman machine init foo --image-path .\rootfs.tar.xz
```

**Comment by cdoern** [comment]
sure @n1hility ! I will take a look

**Comment by brainbytes42** [comment]
Thanks a lot @n1hility, your workaround saved my day! :-)

> Relative works (// cc @brainbytes42 for a workaround)
> 
> ```
> podman machine init --image-path .\rootfs.tar.xz
> ```

**Comment by rhatdan** [comment]
@cdoern did you ever work on this?

**Comment by cdoern** [comment]
@rhatdan no not yet, I might look at it this week since I have more time and will be home at my windows machine

**Comment by rhatdan** [comment]
@cdoern @n1hility anyone have time to fix his one up?

**Comment by rhatdan** [comment]
@n1hility any progress?

**Comment by n1hility** [comment]
@rhatdan was saving this one for @cdoern. I cal look at it this week.
