### ISSUE TITLE
CI Flake: podman system prune networks: expected string length 1

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#15990]
This _probably_ falls under #14173, but it's hitting us hard so it deserves extra scrutiny:
```
           podman system prune networks
...
? Failure [2.724 seconds]
         Podman prune
         /var/tmp/go/src/github.com[/containers/podman/test/e2e/prune_test.go:24](https://github.com/containers/podman/blob/0fb95f95d2af7bcc2529f896fec9904b3357b580/test/e2e/prune_test.go#L24)
           podman system prune networks [It]
           /var/tmp/go/src/github.com[/containers/podman/test/e2e/prune_test.go:261](https://github.com/containers/podman/blob/0fb95f95d2af7bcc2529f896fec9904b3357b580/test/e2e/prune_test.go#L261)
         
           Expected
               <[]string | len:0, cap:0>: nil
           to have length 1
```
### Podman prune [It] podman system prune networks 
* fedora-36 : int podman fedora-36 root container
  * PR #15753
    * [09-12 17:33](https://api.cirrus-ci.com/v1/artifact/task/5662936743018496/html/int-podman-fedora-36-root-container.log.html#t--podman-system-prune-networks--1)
  * PR #15634
    * [09-06 10:51](https://api.cirrus-ci.com/v1/artifact/task/6558434177843200/html/int-podman-fedora-36-root-container.log.html#t--podman-system-prune-networks--1)
  * PR #15447
    * [08-24 05:53](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5251890999984128/html/int-podman-fedora-36-root-container.log.html#t--podman-system-prune-networks--1)
    * [08-24 05:53](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5251890999984128/html/int-podman-fedora-36-root-container.log.html#t--podman-system-prune-networks--2)
    * [08-24 05:53](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5251890999984128/html/int-podman-fedora-36-root-container.log.html#t--podman-system-prune-networks--3)
* fedora-36 : int podman fedora-36 root host
  * PR #15753
    * [09-12 17:37](https://api.cirrus-ci.com/v1/artifact/task/6173110138306560/html/int-podman-fedora-36-root-host.log.html#t--podman-system-prune-networks--1)
  * PR #15712
    * [09-09 03:04](https://api.cirrus-ci.com/v1/artifact/task/5368497449467904/html/int-podman-fedora-36-root-host.log.html#t--podman-system-prune-networks--1)
    * [09-09 03:04](https://api.cirrus-ci.com/v1/artifact/task/5368497449467904/html/int-podman-fedora-36-root-host.log.html#t--podman-system-prune-networks--2)
    * [09-09 03:04](https://api.cirrus-ci.com/v1/artifact/task/5368497449467904/html/int-podman-fedora-36-root-host.log.html#t--podman-system-prune-networks--3)
  * PR #15511
    * [09-10 08:39](https://api.cirrus-ci.com/v1/artifact/task/5206990463959040/html/int-podman-fedora-36-root-host.log.html#t--podman-system-prune-networks--1)
    * [09-10 08:39](https://api.cirrus-ci.com/v1/artifact/task/5206990463959040/html/int-podman-fedora-36-root-host.log.html#t--podman-system-prune-networks--2)
    * [09-10 08:39](https://api.cirrus-ci.com/v1/artifact/task/5206990463959040/html/int-podman-fedora-36-root-host.log.html#t--podman-system-prune-networks--3)
* fedora-36 : int remote fedora-36 root host [remote]
  * PR #15753
    * [09-12 18:38](https://api.cirrus-ci.com/v1/artifact/task/5593856489029632/html/int-remote-fedora-36-root-host.log.html#t--podman-system-prune-networks--1)
* ubuntu-2204 : int podman ubuntu-2204 root host
  * PR #15793
    * [09-14 11:58](https://api.cirrus-ci.com/v1/artifact/task/4860550952779776/html/int-podman-ubuntu-2204-root-host.log.html#t--podman-system-prune-networks--1)
    * [09-14 11:58](https://api.cirrus-ci.com/v1/artifact/task/4860550952779776/html/int-podman-ubuntu-2204-root-host.log.html#t--podman-system-prune-networks--2)
    * [09-14 11:58](https://api.cirrus-ci.com/v1/artifact/task/4860550952779776/html/int-podman-ubuntu-2204-root-host.log.html#t--podman-system-prune-networks--3)
  * PR #15324
    * [08-16 09:48](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6195249646141440/html/int-podman-ubuntu-2204-root-host.log.html#t--podman-system-prune-networks--1)
* ubuntu-2204 : int podman ubuntu-2204 rootless host
  * PR #15896
    * [09-27 08:38](https://api.cirrus-ci.com/v1/artifact/task/5604420799954944/html/int-podman-ubuntu-2204-rootless-host.log.html#t--podman-system-prune-networks--1)
  * PR #15753
    * [09-12 18:22](https://api.cirrus-ci.com/v1/artifact/task/6406339680272384/html/int-podman-ubuntu-2204-rootless-host.log.html#t--podman-system-prune-networks--1)
    * [09-12 17:34](https://api.cirrus-ci.com/v1/artifact/task/6225886696439808/html/int-podman-ubuntu-2204-rootless-host.log.html#t--podman-system-prune-networks--1)
  * PR #15667
    * [09-08 04:10](https://api.cirrus-ci.com/v1/artifact/task/4609772308660224/html/int-podman-ubuntu-2204-rootless-host.log.html#t--podman-system-prune-networks--1)
  * PR #13808
    * [09-28 21:46](https://api.cirrus-ci.com/v1/artifact/task/5938777561497600/html/int-podman-ubuntu-2204-rootless-host.log.html#t--podman-system-prune-networks--1)
    * [09-28 21:46](https://api.cirrus-ci.com/v1/artifact/task/5938777561497600/html/int-podman-ubuntu-2204-rootless-host.log.html#t--podman-system-prune-networks--2)
    * [09-28 21:15](https://api.cirrus-ci.com/v1/artifact/task/6085306276380672/html/int-podman-ubuntu-2204-rootless-host.log.html#t--podman-system-prune-networks--1)
    * [09-28 21:15](https://api.cirrus-ci.com/v1/artifact/task/6085306276380672/html/int-podman-ubuntu-2204-rootless-host.log.html#t--podman-system-prune-networks--2)
    * [09-28 21:15](https://api.cirrus-ci.com/v1/artifact/task/6085306276380672/html/int-podman-ubuntu-2204-rootless-host.log.html#t--podman-system-prune-networks--3)
* ubuntu-2204 : int remote ubuntu-2204 root host [remote]
  * PR #15752
    * [09-13 05:52](https://api.cirrus-ci.com/v1/artifact/task/6023952165240832/html/int-remote-ubuntu-2204-root-host.log.html#t--podman-system-prune-networks--1)

**Comment by Luap99** [comment]
This is not related to #14173 in any way.

Given that this is a flake I suspect the problem is in the test and not podman. The test uses a shared network config dir so any other parallel running test could remove it and cause this test to flake.
