### ISSUE TITLE
[macos] podman machine start on Apple M1 uses qemu with hvf which is not yet supported by qemu on aarch64

### ISSUE THREAD

**Issue by suulperi** [containers/podman#16006]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman machine start and the other podman machine commands use not supported qemu (brew installed 7.1.0) accelerator tcg:hvf and cpu configuration on aarch64/darwin (MacOS 12.6 on M1).

**Steps to reproduce the issue:**

1. podman machine init 

2. podman machine start

**Describe the results you received:**

```
Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code 1, stderr: qemu-system-x86_64: invalid accelerator hvf
qemu-system-x86_64: falling back to tcg
qemu-system-x86_64: unable to find CPU model 'host'
```

**Describe the results you expected:**

Machine is started with the right qemu parameters.

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue happens every time

**Output of `podman version`:**

```
podman --version
podman version 4.2.1
```

**Output of `podman info`:**

```
podman info --debug
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman. failed to create sshClient: connection to bastion host (ssh://core@localhost:64266/run/user/501/podman/podman.sock) failed: dial tcp [::1]:64266: connect: connection refused
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
brew info podman
==> podman: stable 4.2.1 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/opt/homebrew/Cellar/podman/4.2.1 (178 files, 48MB) *
  Poured from bottle on 2022-09-30 at 08:11:50
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0
==> Dependencies
Build: go-md2man ✘, go@1.18 ✘
Required: qemu ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
==> Analytics
install: 25,328 (30 days), 64,126 (90 days), 211,938 (365 days)
install-on-request: 24,535 (30 days), 62,663 (90 days), 210,166 (365 days)
build-error: 1 (30 days)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by arixmkii** [comment]
@suulperi  Did you by any chance migrate your homebrew installation from Intel based Mac?

I can confirm that latest native homebrew qemu + podman works with this accelerator.

**Comment by suulperi** [comment]
@arixmkii - yes I have migrated homebrew from Intel to M1. But I have uninstalled homebrew and reinstalled it without success. Maybe I have not properly uninstalled everything.

**Comment by arixmkii** [comment]
I can't comment on this as I did clean install w/o restoring anything, when I received Apple Silicon laptop. But may be this discussion will help you https://github.com/Homebrew/discussions/discussions/417

**Comment by suulperi** [comment]
I'm able to tackle accelerator error if using tcg only. but I'm still stuck with qemu cpu configuration 
```Error: qemu exited unexpectedly with exit code 1, stderr: qemu-system-x86_64: unable to find CPU model 'host' ```

**Comment by ashley-cui** [comment]
Looks like you're using `qemu-system-x86_64` which is the incorrect qemu for M1. Are you using Rosetta?

**Comment by suulperi** [comment]
@ashley-cui - Yes I was using Rosetta. I uninstalled it and after it podman works perfectly. Using correct VM image as well. Thanks for your help.
