### ISSUE TITLE
[RFE| podman top: new descriptor for (host) uid

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#16009]
I want `podman top $ctr huid,uid` to display the user IDs.  While there is already (h)user, it tries resolving to a name and prints the uid only as fallback.

I would have loved to use that in a tutorial for explaining user namespaces.

@rhatdan @giuseppe maybe something for an intern?

**Comment by rhatdan** [comment]
I agree, would like to see someone add this. 
PS the place to start is in https://github.com/containers/ps.go

**Comment by presztak** [comment]
@rhatdan @vrothberg I'll be happy to work on this if you don't mind.

**Comment by rhatdan** [comment]
You got it.

**Comment by vrothberg** [comment]
Reopened as the code needs to be vendored, ideally with a regression test.  I cut a new release: https://github.com/containers/psgo/releases/tag/v1.8.0
