### ISSUE TITLE
VS Code : "Remote DEV to podman" errors and "Attach to running container" not working.

### ISSUE THREAD

**Issue by jbhrfx9280** [containers/podman#16000]
**BUG REPORT **

/Access - unable to use vs code with remote podman RHEL platform

/Remote-Containers: Attach to running Container
/Remote-Container: Add Development Container Configuration Files

**Description**
VSC not work with remote RHEL 9 / podman server.
“Remote-Containers: Attach to running Container” 
“Remote-Container: Add Development Container Configuration Files”

**Steps to reproduce the issue:**

1.LOCAL ENV:
   Windows 10 pro Desktop
   VSC: 1.71.2

2.REMOTE ENV:
   RHEL 9
   PODMAN 4.1.1
   podman-composer version  1.0.3
   Python39
   PIP3
   Alias docker=podman
   Alias docker-compose=podman-compose

   I have 3 containers created and running fine. These were created on Linux cli. (1) nginx,  nextc;loud, rhel 9 with python.

2 user accounts tested with:
   root user
   dev_user  with sudo 

3. Problem 2: 
 ctl+shift+P   select “Remote-Container: Add Development Container Configuration Files” 

**Describe the results you received:**
[2022-09-29T16:36:24.044Z] mkdir: cannot create directory ‘/root’: Permission denied
[2022-09-29T16:36:24.045Z] Exit code 1

[2022-09-29T16:36:24.045Z] Stop (10 ms): Run in container: mkdir -p '/root/.vscode-server/bin' && ln -snf '/vscode/vscode-server/bin/linux-x64/74b1f979648cc44d385a2286793c226e611f59e7' '/root/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7'

[2022-09-29T16:36:24.049Z] Command in container failed: mkdir -p '/root/.vscode-server/bin' && ln -snf '/vscode/vscode-server/bin/linux-x64/74b1f979648cc44d385a2286793c226e611f59e7' '/root/.vscode-server/bin/74b1f979648cc44d385a2286793c226e611f59e7'

[2022-09-29T16:36:24.049Z] mkdir: cannot create directory ‘/root’: Permission denied
[2022-09-29T16:36:24.049Z] Exit code 1

**Describe the results you expected:**
for it to complete and create a dev container with python39 installed

**Additional information you deem important (e.g. issue happens only occasionally):**
devcontainer.json  was tested with 3 different configurations:

config 1:
	"remoteUser": "vscode"

config 2:
       //  "remoteUser": "vscode"
        "workspaceMount": "source=${localWorkspaceFolder},target=/workspace,type=bind,Z",
        "workspaceFolder": "/workspace",

        "runArgs": ["--userns=keep-id"],
        "containerUser": "vscode"

config 3:
        "remoteUser": "vscode"
        "workspaceMount": "source=${localWorkspaceFolder},target=/workspace,type=bind,Z",
        "workspaceFolder": "/workspace",

        "runArgs": ["--userns=keep-id"],
        "containerUser": "vscode"

config 4:
        //  "remoteUser": "vscode"
       
        "runArgs": ["--userns=keep-id"],
        "containerUser": "vscode"

**Output of `podman version`:**

```
(paste your output here)
podman version 4.1.1

**Output of `podman info`:**
```
(paste your output here)
```
host:
  arch: amd64
  buildahVersion: 1.26.2
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.2-2.el9_0.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.2, commit: c22a156d8b67bfc2959fafd1ae718134423045ab'
  cpuUtilization:
    idlePercent: 99.87
    systemPercent: 0.06
    userPercent: 0.07
  cpus: 8
  distribution:
    distribution: '"rocky"'
    version: "9.0"
  eventLogger: journald
  hostname: dpai16r9.001
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.0-70.26.1.el9_0.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 5668241408
  memTotal: 16266489856
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.5-2.el9_0.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.el9_0.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 8321495040
  swapTotal: 8321495040
  uptime: 49h 5m 2.39s (Approximately 2.04 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 4
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 75125227520
  graphRootUsed: 10272804864
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 14
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1660063436
  BuiltTime: Tue Aug  9 12:43:56 2022
  GitCommit: ""
  GoVersion: go1.17.12
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```
podman-4.1.1-1.el9_0.x86_64

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**


Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

Please see attachments.
[remoteContainers-2022-09-29T16-35-27.362Z.docx](https://github.com/containers/podman/files/9677758/remoteContainers-2022-09-29T16-35-27.362Z.docx)
[VSC and PODMAN errors..docx](https://github.com/containers/podman/files/9677760/VSC.and.PODMAN.errors.docx)
[devcontainer.json_DEFAULT_VSC_CREATED.docx](https://github.com/containers/podman/files/9677790/devcontainer.json_DEFAULT_VSC_CREATED.docx)


Only success using VSC: SSH into remote server works fine.

**Comment by mheon** [comment]
Any chance you can provide logs from the Podman API service?

**Comment by rhatdan** [comment]
Were you volume mounting in /root or is this failing inside of the container?

**Comment by jbhrfx9280** [comment]
There are 2 issues.
1. cannot create podman dev container on my linux server using vsc.

2: cannot attach to running podman container using vsc.

That's basically it.
John

**Comment by baude** [comment]
how did you get the podman binary on the windows system?  did you use the podman machine installer or just just use the precompiled binary and make some vms?

**Comment by jbhrfx9280** [comment]
Not sure how? Can you provide command(s)?
Thank you

**Comment by rhatdan** [comment]
I don't think this is a podman issue, you are using podman-compose which is not part of Podman, please open issue there.
