### ISSUE TITLE
Podman from LinuxBrew/Homebrew does not work on Linux

### ISSUE THREAD

**Issue by YevheniiPokhvalii** [containers/podman#16017]
I'm using `brew` on Linux a lot since they released it on Linux.
Every package I install on Linux with `brew` works as expected.
However, when I install `podman` with `brew`, there is no error, but there is no podman in the PATH after the installation even after reloading shell:

```
$ brew install podman
Running `brew update --auto-update`...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> New Formulae
autocorrect                   dronedb                       git-machete                   tfel

You have 2 outdated formulae installed.
You can upgrade them with brew upgrade
or list them with brew outdated.

==> Downloading https://ghcr.io/v2/homebrew/core/podman/manifests/4.2.1
Already downloaded: /home/user/.cache/Homebrew/downloads/41eae7d5d84fc62dd4c9906072375f7c5bf1eeec931b44a4adfdc26f0146b4a9--podman-4.2.1.bottle_manifest.json
==> Downloading https://ghcr.io/v2/homebrew/core/podman/blobs/sha256:d64e188e78c05935c6d73713f69ffae54452082e01b9d3f8f7a
Already downloaded: /home/user/.cache/Homebrew/downloads/4591d2d7d499f5e9ffffb2b7359d973ceab7ae7f962ec074f85da20cab864781--podman--4.2.1.x86_64_linux.bottle.tar.gz
==> Pouring podman--4.2.1.x86_64_linux.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /home/linuxbrew/.linuxbrew/etc/bash_completion.d
==> Summary
🍺  /home/linuxbrew/.linuxbrew/Cellar/podman/4.2.1: 176 files, 44.7MB
==> Running `brew cleanup podman`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

In a new shell:
```
$ podman
-bash: podman: command not found
```
```
$ which podman
$ 
```

I can see that `brew` downloads the package for Linux `podman--4.2.1.x86_64_linux.bottle.tar.gz` but something is wrong with the installation.
I'm using Ubuntu 22.04.1 LTS WSL2 on Win11

**Comment by afbjorklund** [comment]
The client program is called `podman-remote`, on Linux. It is renamed to `podman`, on macOS and Windows.

https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb

The "server" program called `podman`, which also has a `podman --remote` client built-in, got stuck in review:

* https://github.com/Homebrew/homebrew-core/pull/84276

**Comment by Luap99** [comment]
I recommend to file this against homebrew since we do not control their packaging.

**Comment by afbjorklund** [comment]
The situation is the same (with podman-remote), if you install podman from elsewhere.

**Comment by YevheniiPokhvalii** [comment]
> The client program is called `podman-remote`, on Linux. It is renamed to `podman`, on macOS and Windows.
> 
> https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
> 
> The "server" program called `podman`, which also has a `podman --remote` client built-in, got stuck in review:
> 
> * [podman: add Linux support Homebrew/homebrew-core#84276](https://github.com/Homebrew/homebrew-core/pull/84276)
> 
> This means that you need to start a VM, with `podman-remote machine`, to use it - also on Linux...
> 
> Alternatively you could connect to a remote podman, by using `podman-remote system connection` ?
> 
> You can also do `sudo apt install podman`, to get the [distribution package](https://packages.ubuntu.com/jammy/podman) (currently version 3.4.4)
> 
> * [Installing Podman via brew doesn't work #15334](https://github.com/containers/podman/discussions/15334)

I could not locate `podman --remote`  in `brew`:
```
$ brew search podman
==> Formulae
podman                  podman-compose          pod2man                 modman                  todoman
```

**Comment by afbjorklund** [comment]
If you want to use the Podman "distribution" instead of Ubuntu, you can install in WSL2:

https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md

**Comment by YevheniiPokhvalii** [comment]
> The "server" program called `podman`, which also has a `podman --remote` client built-in, got stuck in review:

It seems that it was fixed in brew in the next podman releases.
Now it installs both `podman` and `podman-remote` in Linux:
```
$ which podman
/home/linuxbrew/.linuxbrew/bin/podman
$ which podman-remote
/home/linuxbrew/.linuxbrew/bin/podman-remote
```
