### ISSUE TITLE
Unable to pull 4.2.1 from quay.io/containers/podman

### ISSUE THREAD

**Issue by mitchellmaler** [containers/podman#16014]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
/kind bug

**Description**

Trying to use the patched 4.2.1 version of podman image but it is not found. Only 4.2.0 is avaiable.

**Steps to reproduce the issue:**

```
$ podman pull quay.io/containers/podman:v4.2.1
Trying to pull quay.io/containers/podman:v4.2.1...
Error: initializing source docker://quay.io/containers/podman:v4.2.1: reading manifest v4.2.1 in quay.io/containers/podman: manifest unknown: manifest unknown
```

**Describe the results you received:**
Not found

**Describe the results you expected:**
Image available

**Comment by mheon** [comment]
@TomSweeneyRedHat PTAL

**Comment by Luap99** [comment]
The latest version always depends on the fedora version, since 4.2.1 is not yet in fedora stable we do not have an image ready.

**Comment by mitchellmaler** [comment]
Ah okay, I was not aware of that.

**Comment by Luap99** [comment]
Looks like podman v4.2.1 is in fedora 36 now so the automation should create and push a new image in the next 24h.

**Comment by Luap99** [comment]
The v4.2.1 image is available, https://quay.io/repository/podman/stable?tab=tags
