### ISSUE TITLE
Systemd check wrong on systems with hidepid=invisible

### ISSUE THREAD

**Issue by Douile** [containers/podman#16022]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When not using systemd but having procfs option hidepid=invisible enabled, the systemd check we default to assuming it is a systemd system. Which then means slirp4netns will error in `podman-compose up` (#13703).

**Steps to reproduce the issue:**

1. Setup rootless podman on openrc distro

2. Enable hidepid=2: add to /etc/fstab
```
proc    /proc   proc    defaults,hidepid=2      0 0
```
3. Reboot so changes take effect
4. Try to create network with podman 

**Describe the results you received:**

Podman thinks I am using systemd so tries to move slirp4netns with dbus-launch, which fails

**Describe the results you expected:**

Either detection fails to assume no systemd or there is some config override I can set to manually tell podman there is no systemd.

**Additional information you deem important (e.g. issue happens only occasionally):**

https://github.com/containers/podman/blob/12655484e39eadbc0fa0607542aa4a49a21013a1/utils/utils.go#L116-L118

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.19.1
Built:        Thu Sep 29 00:18:43 2022
OS/Arch:      linux/arm64
```

<details><summary>

**Output of `podman info`:**

</summary>

```
host:
  arch: arm64
  buildahVersion: 1.27.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-r0
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: ec6267c70d4b6726c71f850de17f6ccaf1d3896f'
  cpuUtilization:
    idlePercent: 97.87
    systemPercent: 1.12
    userPercent: 1.01
  cpus: 4
  distribution:
    distribution: alpine
    version: 3.16.0_rc2
  eventLogger: file
  hostname: XXXXXXXX
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 113
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 111
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.71-0-rpi
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 638480384
  memTotal: 955727872
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.6-r0
    path: /usr/bin/crun
    version: |-
      crun version 1.6
      commit: 18cf2efbb8feb2b2f20e316520e0fd0b6c41ef4d
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /tmp/podman-run-111/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-r0
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 0
  swapTotal: 0
  uptime: 0h 12m 42.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/lib/grocy/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/grocy/.local/share/containers/storage
  graphRootAllocated: 500104691712
  graphRootUsed: 193254883328
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 7
  runRoot: /tmp/podman-run-111/containers
  volumePath: /var/lib/grocy/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.1
  Built: 1664410723
  BuiltTime: Thu Sep 29 00:18:43 2022
  GitCommit: ""
  GoVersion: go1.19.1
  Os: linux
  OsArch: linux/arm64
  Version: 4.2.1
```

</details>

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
podman-4.2.1-r1 description:
Simple management tool for pods, containers and images

podman-4.2.1-r1 webpage:
https://podman.io/

podman-4.2.1-r1 installed size:
37 MiB
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Raspberry Pi :)

**Comment by giuseppe** [comment]
would you mind to open a PR where we enhance the test to check for `dbus-launch` presence when `/proc/1` doesn't exist?  In this way it will be easier to test it on your environment

**Comment by Luap99** [comment]
According to [`sd_booted(3)`](https://man7.org/linux/man-pages/man3/sd_booted.3.html) it is enough to just check for the directory `/run/systemd/system/`

**Comment by rhatdan** [comment]
@giuseppe @flouthoc @Luap99 any movement on this issue?

**Comment by Luap99** [comment]
I take this, it is an easy fix.
