### ISSUE TITLE
Volume mounting does not work in bash on Windows

### ISSUE THREAD

**Issue by parasyte** [containers/podman#16038]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

After installing Podman Desktop on Windows, a local HTML file is opened with the following information:

<blockquote>
<h2>Volume Mounting</h2>
New in Podman v4.1 is the ability to perform volume mounts from Windows paths into a Linux container. This supports several notation schemes, including:

Windows Style Paths:

`podman run --rm -v c:\Users\User\myfolder:/myfolder ubi8-micro ls /myfolder`

Unixy Windows Paths:

`podman run --rm -v /c/Users/User/myfolder:/myfolder ubi8-micro ls /myfolder`

Linux paths local to the WSL filesystem:

`podman run --rm -v /var/myfolder:/myfolder ubi-micro ls /myfolder`

All of the above conventions work, whether running on a Windows prompt or the WSL Linux shell. Although when using Windows paths on Linux, appropriately quote or escape the Windows path portion of the argument.
</blockquote>

Running these example commands fails in bash on Windows.

**Steps to reproduce the issue:**

1. Install [git-for-windows](https://gitforwindows.org/) or [MSYS2](https://www.msys2.org/) to get a native Windows build of bash.
2. In bash, create a subdirectory named `myfolder` in your home and put a file into it:

```bash
$ cd ~
$ mkdir myfolder
$ touch myfolder/hello.txt
```

3. Run the example command, replacing your username as necessary, e.g.:

```bash
$ podman run --rm -v /c/Users/$(whoami)/myfolder:/myfolder ubi8-micro ls /myfolder
```

3. The error message shown below is seen and the container fails to start.

**Describe the results you received:**

In git bash:

```bash
$ podman run --rm -v /c/Users/$(whoami)/myfolder:/myfolder ubi8-micro ls /myfolder
Error: invalid container path "\\Program Files\\Git\\myfolder", must be an absolute path
```

In MSYS2:

```bash
$ podman run --rm -v /c/Users/$(whoami)/myfolder:/myfolder ubi8-micro ls /myfolder
Error: invalid container path "\\msys64\\myfolder", must be an absolute path
```

And with Windows Style Paths in git bash:

```bash
$ podman run --rm -v C:\\Users\\$(whoami)\\myfolder:/myfolder ubi8-micro ls /myfolder
ls: cannot access 'C:/Program Files/Git/myfolder': No such file or directory
```

Windows Style Paths in MSYS2:

```bash
$ podman run --rm -v C:\\Users\\$(whoami)\\myfolder:/myfolder ubi8-micro ls /myfolder
ls: cannot access 'C:/msys64/myfolder': No such file or directory
```

For some reason, the container path is being interpreted somewhere and ends up becoming a Windows path? Even when the argument is single-quoted so the shell will not attempt to interpret it as anything other than a string.

**Describe the results you expected:**

Running the example commands works correctly in Windows Command Prompt and PowerShell. It also works with Cmder, which I believe is just cmd under the hood. For instance, this was in PowerShell:

```powershell
> podman run --rm -v /c/Users/$env:UserName/myfolder:/myfolder ubi8-micro ls /myfolder
hello.txt
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.16.15
Git Commit:   62b324ddf718411b1d4d0ba8117c632f7f984a38
Built:        Wed Sep  7 06:08:04 2022
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.18.5
Built:        Wed Sep  7 12:58:19 2022
OS/Arch:      linux/amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

I just downloaded and installed Podman for the first time today.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The issue appears to be specific to bash on Windows, which is not an officially supported Windows shell. I use bash in Windows Terminal, but it isn't necessary to reproduce the problem; It also happens in the terminal emulator provided by the `git-for-windows` installer. Which is `mintty` 3.6.1, FWIW. I'm not sure which terminal emulator MSYS2 uses (also looks like mintty 3.6.1).

This is the version of Bash provided in git-for-windows:

```bash
$ bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-msys)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

And it looks identical in MSYS2:

```bash
$ bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-msys)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**Comment by mheon** [comment]
@n1hility PTAL

**Comment by n1hility** [comment]
@parasyte Sorry this one fell through the cracks. What's happening here is that git bash is autoconverting root paths for arguments to point to the c drive location bash is setup to emulate, so its actually "/folder" that is the source of the problem. 

There is a couple solutions. One is you can prepend an additional slash like //folder. Another is you can call shell like so:

`podman run --rm -v C:\\Users\\$(whoami)\\myfolder:/myfolder ubi8-micro sh -c 'ls /myfolder'`

I'm going to close this since it doesn't look like a podman bug, but feel free to reopen if I missed something.

Thanks!

**Comment by parasyte** [comment]
Thanks @n1hility, that does work. I still don't know why "Unixy Windows Paths" do not work in git bash. E.g. `/c/Users/...` style paths and `$PWD` give the error shown in the OP.

**Comment by n1hility** [comment]
@parasyte ah right, on that, you need a colon after the drive letter like this: `/c:/Users'.

**Comment by parasyte** [comment]
Ok! I can work around this issue with something like: `$(echo $PWD | sed 's#^/c/#/c:/#')` to add the colon.
