### ISSUE TITLE
podman-kube@.service template: container exists, it shouldn't

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#16047]
```
$ podman container exists f87e402febb6-service
#/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#| FAIL: exit code is 0; expected 1
#\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Relevant code: https://github.com/containers/podman/blob/43a8f1ae555018b5514af61ed789648afc79a589/test/system/250-systemd.bats#L436-L437

My understanding of systemd is that `systemctl stop` shouldn't return until the unit is really truly stopped? Is this a real bug, or a test bug? (It's easy to add a `wait` to the test, but my gut tells me that's not the right thing to do).

* ubuntu-2204 : sys podman ubuntu-2204 rootless host
  * PR #13808
    * [09-28 22:46](https://api.cirrus-ci.com/v1/artifact/task/4748300137005056/html/sys-podman-ubuntu-2204-rootless-host.log.html#t--00292)
  * PR #15873
    * [09-22 16:56](https://api.cirrus-ci.com/v1/artifact/task/4934893649002496/html/sys-podman-ubuntu-2204-rootless-host.log.html#t--00290)
  * PR #15593
    * [09-06 12:14](https://api.cirrus-ci.com/v1/artifact/task/5983584950419456/html/sys-podman-ubuntu-2204-rootless-host.log.html#t--00285)

**Comment by vrothberg** [comment]
@edsantiago any more flakes on this one?  The initial data indicates it's an Ubuntu-only thing.  Is that still true?

**Comment by edsantiago** [comment]
I don't think we've seen this since we stopped testing Ubuntu, so, I'll close.
