### ISSUE TITLE
healthcheck run: error: ctr does not exist in database: no such container

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#16075]
Seen just now in an [in-flight PR](https://api.cirrus-ci.com/v1/artifact/task/6347492638851072/html/sys-podman-fedora-36-aarch64-root-host.log.html#t--00292):
```
[+1345s] not ok 292 podman create --health-on-failure=kill
...
# podman healthcheck run APUcS4ihNr
Error: container 43712cb6940abc3a35e883961fa79d4632674e40ca72394fec96535842fdf06c does not exist in database: no such container
[ rc=125 (** EXPECTED 0 **) ]
```
f36 local root aarch64. Also seen in my flake logs, but only once so I hadn't filed it:

### [sys] 288 podman create --health-on-failure=kill
* fedora-36-aarch64 : sys podman fedora-36-aarch64 root host
  * PR #15812
    * [09-16 05:06](https://api.cirrus-ci.com/v1/artifact/task/4947692416663552/html/sys-podman-fedora-36-aarch64-root-host.log.html#t--00288)

**Comment by edsantiago** [comment]
Another one on [f36 aarch64 root](https://api.cirrus-ci.com/v1/artifact/task/4707142423281664/html/sys-podman-fedora-36-aarch64-root-host.log.html)

**Comment by edsantiago** [comment]
[and again](https://api.cirrus-ci.com/v1/artifact/task/6455299606315008/html/sys-podman-fedora-36-aarch64-root-host.log.html)

**Comment by edsantiago** [comment]
This one is really blowing up. It has failed seven reruns (eight total) in [nightly cron](https://cirrus-ci.com/task/6234361790988288)

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Comment by vrothberg** [comment]
I'll take a look.

**Comment by vrothberg** [comment]
Opened https://github.com/containers/podman/pull/16112.  Looks like test-side fix to me.
