### ISSUE TITLE
sdnotify play kube policies: podman container wait, hangs

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#16076]
```
[+1368s] not ok 310 sdnotify : play kube - with policies
...
$ podman container inspect test_pod-a --format {{.Config.SdNotifySocket}}
/var/tmp/-podman-notify-proxy.sock54032352
$ podman logs test_pod-a
/run/notify/notify.sock
READY
$ podman exec test_pod-a /bin/touch /stop
$ podman container inspect 9cffc8377ee1-service --format {{.State.ConmonPid}}
98526
$ podman container wait test_pod-a
timeout: sending signal TERM to command ?/var/tmp/go/src/github.com/containers/podman/bin/podman?
[ rc=124 (** EXPECTED 0 **) ]
*** TIMED OUT ***
```
* fedora-36 : sys podman fedora-36 rootless host
  * PR #16034
    * [10-03 15:32](https://api.cirrus-ci.com/v1/artifact/task/4652967281295360/html/sys-podman-fedora-36-rootless-host.log.html#t--00310)
    * [10-03 11:37](https://api.cirrus-ci.com/v1/artifact/task/5594309993955328/html/sys-podman-fedora-36-rootless-host.log.html#t--00310)
 * fedora-36 : sys podman fedora-36 root host
   * PR #15794
     * [09-14 14:10](https://api.cirrus-ci.com/v1/artifact/task/5067724438110208/html/sys-podman-fedora-36-root-host.log.html#t--00305)
* fedora-36 : sys podman fedora-36 rootless host
  * PR #15846
    * [09-29 10:32](https://api.cirrus-ci.com/v1/artifact/task/5592796655517696/html/sys-podman-fedora-36-rootless-host.log.html#t--00305)
  * PR #15844
    * [09-17 08:32](https://api.cirrus-ci.com/v1/artifact/task/6313591002365952/html/sys-podman-fedora-36-rootless-host.log.html#t--00305)
  * PR #15796
    * [09-14 09:34](https://api.cirrus-ci.com/v1/artifact/task/5520403421462528/html/sys-podman-fedora-36-rootless-host.log.html#t--00305)
  * PR #15786
    * [09-14 13:49](https://api.cirrus-ci.com/v1/artifact/task/4825809096540160/html/sys-podman-fedora-36-rootless-host.log.html#t--00305)
  * PR #15072
    * [09-15 09:34](https://api.cirrus-ci.com/v1/artifact/task/5670450922520576/html/sys-podman-fedora-36-rootless-host.log.html#t--00305)
* fedora-36 : sys podman fedora-36 rootless host
  * PR #15933
    * [09-26 12:53](https://api.cirrus-ci.com/v1/artifact/task/6087922045681664/html/sys-podman-fedora-36-rootless-host.log.html#t--00309)
* fedora-36-aarch64 : sys podman fedora-36-aarch64 root host
  * PR #15910
    * [09-24 09:08](https://api.cirrus-ci.com/v1/artifact/task/5557962272931840/html/sys-podman-fedora-36-aarch64-root-host.log.html#t--00308)
* fedora-36 : sys podman fedora-36 rootless host
  * PR #15753
    * [09-12 22:10](https://api.cirrus-ci.com/v1/artifact/task/6085149208084480/html/sys-podman-fedora-36-rootless-host.log.html#t--00304)
* fedora-36 : sys podman fedora-36 root host
  * PR #15695
    * [09-09 07:22](https://api.cirrus-ci.com/v1/artifact/task/5808828905160704/html/sys-podman-fedora-36-root-host.log.html#t--00302)

Looks like Sept 9 is the first logged instance.

So far, f36 only (both amd64 and aarch64), root and rootless.

**Comment by vrothberg** [comment]
I recently attempted to fix some issues down there.  @edsantiago, do you know when the flake happened for the _first_ time?

**Comment by vrothberg** [comment]
> I recently attempted to fix some issues down there. @edsantiago, do you know when the flake happened for the _first_ time?

Just saw it at the bottom "Looks like Sept 9 is the first logged instance."

**Comment by vrothberg** [comment]
Closing as https://github.com/containers/podman/pull/16118 merged.  I am not 100 percent sure it fixes the flake but it's the only potential source for the flake I could spot so far.  Let's reopen in case it continues.

**Comment by edsantiago** [comment]
Reopening: [this is still happening](https://api.cirrus-ci.com/v1/artifact/task/5764449016479744/html/sys-podman-fedora-36-rootless-host.log.html) (and yes, I confirmed that the PR in question is forked from a `main` that includes #16118).

**Comment by vrothberg** [comment]
Can we close https://github.com/containers/podman/issues/16246 as a duplicate, or is there a need to track it separately?

**Comment by edsantiago** [comment]
Seen also in [fedora gating tests](https://artifacts.dev.testing-farm.io/bececdc4-9adf-4e74-ae83-56fbd52f24db/work-tests.ymlXe1Zth/tests-BAqFjn/test.podman-root-cgroupsv2.bats.log).

**Comment by vrothberg** [comment]
Reopening as I don't expect https://github.com/containers/podman/pull/16284 to fix the underlying issue.  It may help to resolve the timeout but should fail.

**Comment by edsantiago** [comment]
* fedora-36 : sys podman fedora-36 rootless host
  * PR #16475
    * [11-10 08:42](https://api.cirrus-ci.com/v1/artifact/task/5146252698976256/html/sys-podman-fedora-36-rootless-host.log.html#t--00314)
  * PR #16202
    * [10-28 10:03](https://api.cirrus-ci.com/v1/artifact/task/6249936885907456/html/sys-podman-fedora-36-rootless-host.log.html#t--00312)
    * [10-28 07:27](https://api.cirrus-ci.com/v1/artifact/task/5988630605856768/html/sys-podman-fedora-36-rootless-host.log.html#t--00312)
  * PR #15918
    * [10-28 15:42](https://api.cirrus-ci.com/v1/artifact/task/5465676998508544/html/sys-podman-fedora-36-rootless-host.log.html#t--00312)
* fedora-37 : sys podman fedora-37 rootless host
  * PR #16389
    * [11-02 23:23](https://api.cirrus-ci.com/v1/artifact/task/5361869853556736/html/sys-podman-fedora-37-rootless-host.log.html#t--00313)

**Comment by edsantiago** [comment]
[f36 rootless](https://api.cirrus-ci.com/v1/artifact/task/6479873261699072/html/sys-podman-fedora-36-rootless-host.log.html#t--00317)

**Comment by edsantiago** [comment]
One of our most popular flakes recently

* fedora-36 : sys podman fedora-36 rootless host
  * PR #16639
    * [11-28 07:55](https://api.cirrus-ci.com/v1/artifact/task/6265604458414080/html/sys-podman-fedora-36-rootless-host.log.html#t--00320)
  * PR #16554
    * [11-21 10:30](https://api.cirrus-ci.com/v1/artifact/task/4867941234114560/html/sys-podman-fedora-36-rootless-host.log.html#t--00319)
  * PR #16512
    * [11-15 16:59](https://api.cirrus-ci.com/v1/artifact/task/6479873261699072/html/sys-podman-fedora-36-rootless-host.log.html#t--00317)
* fedora-37 : sys podman fedora-37 rootless host
  * PR #16723
    * [12-04 06:58](https://api.cirrus-ci.com/v1/artifact/task/4595742782783488/html/sys-podman-fedora-37-rootless-host.log.html#t--00321)
    * [12-03 10:14](https://api.cirrus-ci.com/v1/artifact/task/5311563104518144/html/sys-podman-fedora-37-rootless-host.log.html#t--00321)
  * PR #16714
    * [12-02 11:51](https://api.cirrus-ci.com/v1/artifact/task/4723587583049728/html/sys-podman-fedora-37-rootless-host.log.html#t--00321)
  * PR #16678
    * [12-01 19:35](https://api.cirrus-ci.com/v1/artifact/task/4696017585569792/html/sys-podman-fedora-37-rootless-host.log.html#t--00321)
  * PR #16581
    * [12-01 11:16](https://api.cirrus-ci.com/v1/artifact/task/6496112601726976/html/sys-podman-fedora-37-rootless-host.log.html#t--00321)

**Comment by vrothberg** [comment]
Help is on the way in https://github.com/containers/podman/pull/16709.  This has the highest priority for me this week.  Currently refining tests, so I am hopeful the flake will be buried this week.

**Comment by vrothberg** [comment]
@edsantiago any indications of a flake after the merge?

**Comment by edsantiago** [comment]
In the last ten minutes, no :-)

Patience, grasshopper. Data collection takes time. I'll let you know late December.

**Comment by vrothberg** [comment]
> In the last ten minutes, no :-)

GitHub claims it to be 13 hours :^)

> Patience, grasshopper. Data collection takes time. I'll let you know late December.

Thanks! I intended to be pro-active; it has been quite a flake/ride.

**Comment by edsantiago** [comment]
Two flakes on December 14 (after the Dec 8 merge). Both on PR 16781 which, if I'm gitting correctly, was parented on a Dec 7 commit that did not include #16709. So I think we're good. Thank you @vrothberg!

* fedora-36 : sys podman fedora-36 rootless host
  * PR #16781
    * [12-14 11:41](https://api.cirrus-ci.com/v1/artifact/task/4877426535170048/html/sys-podman-fedora-36-rootless-host.log.html#t--00321)
* fedora-37 : sys podman fedora-37 rootless host
  * PR #16781
    * [12-14 11:42](https://api.cirrus-ci.com/v1/artifact/task/6284801418723328/html/sys-podman-fedora-37-rootless-host.log.html#t--00321)

**Comment by vrothberg** [comment]
That was a tough cookie!  Thanks for your help and patience, @edsantiago
