### ISSUE TITLE
confusing podman+iptables port shenanigans (running rootless https proxy nginx)

### ISSUE THREAD

**Issue by coderofsalvation** [containers/podman#16086]
/kind feature

**Description**

When using iptable's PREROUTING, binding to ports inside containers makes netstat output different ports (ran in that same container).
Maybe some kind of console message could warn/explain when situations like this occur?

> Backstory: I'm trying to run a rootless https proxy server in a podman container, which requires port 443,80,81 (which I need to forward to higher ports, hence the iptable PREROUTING rules).
I'm not sure whether podman is confused here, or whether iptables is responsible for this scenario, but it's hard to debug to say the least. 

> I know for rootless containers, I can simply modify the `net.ipv4.ip_unprivileged_port_start sysctl` to change the lowest port. However, I love the idea of simply using iptables for this, as it gives a nice central overviews of ports.

**Steps to reproduce the issue:**

#### iptables configuration

```
server $ proxyport(){
        iptables -t nat -A PREROUTING -p tcp --dport $1 -j REDIRECT --to-port $2
        iptables -t nat -I OUTPUT -p tcp -d 127.0.0.1 --dport $1 -j REDIRECT --to-ports $2
  }
server $ proxyport 80 8080
server $ proxyport 81 8181
server $ proxyport 443 4443
server $ echo helloworld | nc -lp 8080 

laptop $ telnet myserver 80 
helloworld
```
> NICE! port 80 is redirected to port 8080...so our rootless containers can just run with `-p 8080:80` right?

**Describe the results you received:**

Weirdly, to get it to work, I now need to use `-p 8080:8080` (??) instead of the expected `-p 8080:80`....

```
server $ podman run --name=nginx-proxy-manager -d -p 8080:8080 -p 8181:8181 -p 4443:4443 docker.io/jlesage/nginx-proxy-manager:latest
server $ podman ps
CONTAINER ID  IMAGE                                          COMMAND     CREATED             STATUS                 PORTS                                                                   NAMES
c2f3462cd5d6  docker.io/jlesage/nginx-proxy-manager:v1.26.1  /init       About a minute ago  Up About a minute ago  0.0.0.0:4443->4443/tcp, 0.0.0.0:8080->8080/tcp, 0.0.0.0:8181->8181/tcp  nginx-proxy-manager

laptop $ telnet myserver 80
Trying x.x.x.x...
Connected to myserver
Escape character is '^]'.

server $ podman exec -it nginx-proxy-manager netstat -nap
tcp        0      0 c2f3462cd5d6:8181       c2f3462cd5d6:33238      ESTABLISHED
```

> inside the container nginx is binding to port 81, but netstat shows 8181? =]

**Describe the results you expected:**

What was expected to work (`-p 8080:80`) works rootful+rootless without iptables.
But with above iptables this does no longer work:

```
server $ podman run --name=nginx-proxy-manager -d -p 8080:80 -p 8181:81 -p 4443:443 docker.io/jlesage/nginx-proxy-manager:latest
server $ telnet localhost 80
Trying ::1...
Connection failed: Connection refused
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused

server $ podman exec -it nginx-proxy-manager netstat -nap
tcp        0      0 xxxxxxxxxxx:8080       xxxxxx      LISTEN
```

> same as above, inside the container nginx is binding to port 81, but netstat shows 8181? =]

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Client:       Podman Engine
Version:      4.1.0
API Version:  4.1.0
Go Version:   go1.18.6
Git Commit:   3f8087714f8421ca481497525cd85442ec39a866
Built:        Thu Sep  8 10:24:58 2022
OS/Arch:      linux/amd64

```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.2-r0
    path: /usr/bin/conmon
    version: 'conmon version 2.1.2, commit: f25214cda836296fe8695c2e582ca79d2246053a'
  cpuUtilization:
    idlePercent: 99
    systemPercent: 0.27
    userPercent: 0.73
  cpus: 4
  distribution:
    distribution: alpine
    version: 3.16.2
  eventLogger: file
  hostname: 2wa
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65536
  kernel: 5.15.71-0-lts
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 2953084928
  memTotal: 4120780800
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun-1.4.5-r0
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /tmp/podman-run-1002/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,C
AP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-r0
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.2
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 30m 29.01s
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/2wa/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 2
    stopped: 1
 graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /var/lib/containers
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.8.2-r0
      Version: |-
        fuse-overlayfs: version 1.8.2
        fusermount3 version: 3.11.0
        FUSE library version 3.11.0
        using FUSE kernel interface version 7.31
  graphRoot: /home/2wa/.local/share/containers/storage
  graphRootAllocated: 79626440704
  graphRootUsed: 1769627648
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 6
  runRoot: /tmp/containers-user-1002/containers
  volumePath: /home/2wa/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.0
  Built: 1662625498
  BuiltTime: Thu Sep  8 10:24:58 2022
  GitCommit: 3f8087714f8421ca481497525cd85442ec39a866
  GoVersion: go1.18.6
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.0

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Comment by Luap99** [comment]
Check `netstat -nltp` in the container and on the host to see what ports are binded.

**Comment by coderofsalvation** [comment]
ok, just to be sure:

host # iptables -L && iptables -t nat -L -n -v
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination         
Chain PREROUTING (policy ACCEPT 75073 packets, 10M bytes)
 pkts bytes target     prot opt in     out     source               destination         
   15   788 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 redir ports 8080
   
Chain INPUT (policy ACCEPT 2183 packets, 233K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 142 packets, 7988 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  *      *       0.0.0.0/0            127.0.0.1            tcp dpt:80 redir ports 8080

Chain POSTROUTING (policy ACCEPT 142 packets, 7988 bytes)
 pkts bytes target     prot opt in     out     source               destination         

```

so now the (nonworking) rootless high-to-lowport (`-p 8080:80` e.g.):

```
$ podman run -d --name=notworking -p 8080:80 -p 4443:443 -p 8181:81 -v $(pwd)/data:/data docker.io/jlesage/nginx-proxy-manager:v1.26.1
b8d8346047688506e03aa995040eda3d6191450755006b9c65cdafd01cc705a7

$ podman exec -it notworking netstat -nltp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8181            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:4443            0.0.0.0:*               LISTEN      -
tcp        0      0 :::8080                 :::*                    LISTEN      -
tcp        0      0 :::8181                 :::*                    LISTEN      -
tcp        0      0 :::3000                 :::*                    LISTEN      -
tcp        0      0 :::4443                 :::*                    LISTEN      -
$ telnet localhost 80
Trying ::1...
Connection failed: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.            <--- closed before I could even type anything
```

and in case of the (strange-but-working) rootless `-p 8080:8080`:

```shell
$ podman run -d --name=working -p 8080:8080 -p 4443:4443 -p 8181:8181 -v $(pwd)/data:/data docker.io/jles
age/nginx-proxy-manager:v1.26.1
a7cc0fbfc62004f78b7d535e9248aea97967c7d71b8fce5bab53fc8d8fe46eba
2wa:~/nginx-proxy-manager$ podman exec -it working netstat -nltp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:4443            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8181            0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -
tcp        0      0 :::4443                 :::*                    LISTEN      -
tcp        0      0 :::8181                 :::*                    LISTEN      -
tcp        0      0 :::8080                 :::*                    LISTEN      -

$ telnet localhost 80
Trying ::1...
Connection failed: Connection refused
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
GET / HTTP/1.1

HTTP/1.1 400 Bad Request
Server: openresty
Date: Fri, 07 Oct 2022 15:46:10 GMT
Content-Type: text/html
Content-Length: 154
Connection: close

<html>
```

**Comment by Luap99** [comment]
> ```
> Active Internet connections (only servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
> tcp        0      0 0.0.0.0:4443            0.0.0.0:*               LISTEN      -
> tcp        0      0 0.0.0.0:8181            0.0.0.0:*               LISTEN      -
> tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      -
> tcp        0      0 :::4443                 :::*                    LISTEN      -
> tcp        0      0 :::8181                 :::*                    LISTEN      -
> tcp        0      0 :::8080                 ::
>```

This clearly shows that your application in the container is listening on port 8080 and 8181 and not 80 or 81, that has nothing to do with podman. Therefore you need `-p <host>:8080 ...`

**Comment by coderofsalvation** [comment]
Well that's the crazy thing..it seems the container is not binding to 8080, but to 80.
Nothing in the dockerfile [or even repo](https://github.com/NginxProxyManager/nginx-proxy-manager/search?q=4443) of that image mentions 4443 (only the lower ports 443,80,81).

So I guess the conclusion is: iptables is responsible for these shenanigans.
I didn't know that PREROUTE also affects bind-calls inside containers, in such way that if a container calls`bind(...,80)` then netstat will show 8080.
Probably if I run the container in its own network, then it will just display the lower ports (80,445,81) since it's out of the global iptable scope.

Thanks for the help.

**Comment by Luap99** [comment]
I doubt that iptables has to do anything with it. First, I really don't think it will alter bind calls. Second, in the container namespace you will have clean iptables rules.

**Comment by coderofsalvation** [comment]
Another theory is that the image-application has some kindof fallback-logic to bind to 8080 instead.
I just find it odd that I can't find any occurance of port 4443 in their docs or repo.
The only times port 4443 is introduced is by the podman & iptables cmds.
