### ISSUE TITLE
(rootless) podman stats -- only "net_io" isn't generated !!

### ISSUE THREAD

**Issue by GKSONG** [containers/podman#16095]
All other value is generated except net_io item.

Could you share any idea how to resolve it ?

**Comment by giuseppe** [comment]
could you please share more details on your environment, how you created the container and what commands are you using?

**Comment by GKSONG** [comment]
o. My Environment
    _-- RHEL 8.4 ( dnf module install -y container-tools:rhel8 )
     -- cgroupv2
    -- GPU A40 ( nvidia driver : 510.47.03 )
    -- User Network : 1 G_

 o. Podman Run Script : passthrough 2GPU
 _podman run \
--cpuset-cpus=0-11 -m=128g \
--pid=host \
--security-opt label=disabled \
--security-opt=label=type:nvidia_container_t  \
-e NVIDIA_VISIBLE_DEVICES=GPU-ed8565df-c450-ae7d-878c-31d6b251ed8a,GPU-9338a97a-43f0-a04f-ce71-e92652db5266 -e NVIDIA_DRIVER_CAPABILITIES=compute,utility  \
-v /usr/bin/nvidia-smi:/usr/bin/nvidia-smi -v /home/amdin/testapp:/testapp \
-w /root -p 8888:8888 -ti 2bb045f509d0  bash_

    -- (nvidia) deviceQuery, sample ML application (by jupyter-notebook) is successfully run.

o. Container Creation Method : use "Scratch Method"
    _-- (rootless) "admin" account  <-- but add to "wheel" group
    -- buildah unshare
    -- container=$(buildah from scratch)
    -- mnt=$(buildah mount $container)
    -- cd $mnt
    -- dnf install --releasever=centos-release-8 --installroot $mnt bash coreutils dnf -y 
    -- additionally install cuda-11.6 related library and python39.._

o. In CentOS 8.4, there is no issue on "podman stats" result.

If you want to know the other parameters, I will share with you

**Comment by Luap99** [comment]
Please provide the info as requested in the issue template. This should be fixed in the latest version.

**Comment by GKSONG** [comment]
Thanks @Luap99 
#16110 is informed.
