### ISSUE TITLE
signal flake: Timed out waiting for BYE

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#16091]
Haven't seen this one before (note, "sigkill" in test name is a misnomer, it's actually SIGINT)
```
[+0226s] not ok 81 podman sigkill
...
# #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# #| FAIL: Timed out waiting for BYE from container
# #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Basically, it looks like container is never receiving the INT signal)

[ubuntu root](https://api.cirrus-ci.com/v1/artifact/task/6536729771900928/html/sys-podman-ubuntu-2204-root-host.log.html#t--00081)

**Comment by vrothberg** [comment]
Could be a timeout issue?  We're waiting at most 5 seconds for the container to echo BYE.  Maybe the machine was under heavy load?  There are many syscalls involved and many chances the scheduler could kick in.

**Comment by vrothberg** [comment]
@edsantiago, I wonder if the test could just do a `podman_run wait --condition=running foo` instead of https://github.com/containers/podman/blob/main/test/system/032-sig-proxy.bats#L9-L21.

**Comment by vrothberg** [comment]
@edsantiago can we start the container with `--detach`?

**Comment by vrothberg** [comment]
> Timeout: are you talking load on the host? On the bare-metal? Could be, but is there any way to determine that? (If you're talking about the VM itself: the only thing running is system tests. Should not be high load).

That's the only guess I have.  5 seconds seems like a small timeout compared to other ones.

**Comment by edsantiago** [comment]
`--detach`: no, because we then can't actually test `sig-proxy` :-)

**Comment by vrothberg** [comment]
> `--detach`: no, because we then can't actually test `sig-proxy` :-)

Too late for a coffee for me today :-) Thanks, Ed!

**Comment by edsantiago** [comment]
Failed in [Fedora gating tests](https://artifacts.dev.testing-farm.io/948f365a-a8f1-466b-85e0-e752ffc719e4/work-tests.ymlz1OSKA/tests-TEM3FH/test.podman-root-cgroupsv2.bats.log):
```
# Arch:amd64 OS:fedora38 Runtime:crun Rootless:false Events:journald Logdriver:journald Cgroups:v2+systemd Net:netavark
...
not ok 81 podman sigkill
# (from function `die' in file ./helpers.bash, line 594,
#  in test file ./032-sig-proxy.bats, line 36)
#   `die "Timed out waiting for BYE from container"' failed
# # podman rm -t 0 --all --force --ignore
# # podman ps --all --external --format {{.ID}} {{.Names}}
# # podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
# quay.io/libpod/testimage:20220615 f26aa69bb3f3
# # podman container exists foo
# # podman logs foo
# READY
# # podman logs foo
# READY
# # podman logs foo
# READY
# # podman logs foo
# READY
# # podman logs foo
# READY
# # podman logs foo
# READY
# #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# #| FAIL: Timed out waiting for BYE from container
# #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by vrothberg** [comment]
@edsantiago do the flakes in the gating tests support the theory of the machine being under load (or just sufficiently slow) to justify bumping timeouts?

**Comment by edsantiago** [comment]
I don't know enough about the gating-test environment to answer that. I actually don't know ANYTHING about that environment. But yeah, I guess there's not much choice other than to bump timeouts.

**Comment by edsantiago** [comment]
New symptom in [remote f37-aarch64 root](https://api.cirrus-ci.com/v1/artifact/task/6695273052241920/html/sys-remote-fedora-37-aarch64-root-host.log.html#t--00082):
```
# podman-remote --url unix:/tmp/podman_tmp_pDLe container exists foo
# podman-remote --url unix:/tmp/podman_tmp_pDLe logs foo
# podman-remote --url unix:/tmp/podman_tmp_pDLe inspect --format {{.State.Running}} foo
false
# podman-remote --url unix:/tmp/podman_tmp_pDLe inspect --format {{.State.ExitCode}} foo
READY
0
#/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#| FAIL: Container exited (status: 0) before we saw 'READY':
#\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by vrothberg** [comment]
Should we bump the timeout to 20?  This seems to have worked for other tests - assuming when the nodes are under stress.

**Comment by edsantiago** [comment]
I guess there's not much else we can do right now. I'll open a PR.

**Comment by edsantiago** [comment]
Reopening: failed again in [4.4 gating tests](https://artifacts.dev.testing-farm.io/d89904a0-68b2-4c0c-9b01-946616d4bf6a/work-tests.ymlvrltvmqv/tests-_nqrre07/test.podman-rootless-cgroupsv2.bats.log), and this is 4.4 so it presumably has the timeout bump

**Comment by edsantiago** [comment]
Continuing to fail in [fedora gating](https://artifacts.dev.testing-farm.io/00a349d7-e566-4a1a-a05d-c069127422f1/work-tests.ymlv_87v70h/tests-xkhdxcwc/test.podman-rootless-cgroupsv2.bats.log)

**Comment by vrothberg** [comment]
@edsantiago, does it also happen in CI?  I'd love to see (journal) logs.

**Comment by edsantiago** [comment]
It has happened in CI, but so rarely (most recently Nov 2022) that the logs are unavailable.

**Comment by edsantiago** [comment]
I give up. The only thing I've learned is that sometimes `ps auxww --forest | grep -2 podman` shows two identical nested podman processes, sometimes it shows only one:
```
fedora      6137  0.0  0.2   7416  4224 pts/2    Ss   16:32   0:00          \_ -bash
fedora      6287 13.0  3.3 1280596 67636 pts/2   Sl+  16:33   0:00              \_ podman run -i quay.io/libpod/testimage:20221018 sh -c trap "echo BYE; exit 0" INT;while :;do sleep 1;done
fedora      6308  0.0  0.1   5012  2944 pts/2    S    16:33   0:00                  \_ /usr/bin/slirp4netns --disable-host-loopback --mtu=65520 --enable-sandbox --enable-seccomp --enable-ipv6 -c -e 3 -r 4 --netns-type=path /run/user/1000/netns/netns-99648371-19a3-60bc-88ee-a134fcf858d3 tap0
```
^^^ the good case

In the good case, like this one, killing the child of `bash` works as expected, spits out the `BYE`. In the bad case, with two podman processes, we never get `BYE`.

All tests were run using `podman system reset` in between. Sometimes under `su - fedora`, in which case `runRoot` is `/tmp/something`, sometimes under `ssh`, in which case `runRoot` is `/run/user/something`. I think the latter (ssh) works more often than su, but I've seen cases where `su` works.

This is way beyond me. @containers/podman-maintainers, once again, please look into this.

**Comment by Luap99** [comment]
The extra reexec happens when we cannot join the rootless pause process namespace.

While I cannot reproduce the missing BYE I can still reproduce this behaviour locally by checking the exit code. With the extra reexec we exit 1 while without it we exit as expected 0.
