### ISSUE TITLE
podman push image with error "writing sigstore attachments is disabled by configuration"

### ISSUE THREAD

**Issue by LiZhang19817** [containers/podman#16093]
Hi Guys,

I am trying to push image to image registry, but hit error "**writing sigstore attachments is disabled by configuration"**, what does that means, seems like configuration issue from podman side, pls give some suggestions.

```
[fedora@ip-10-0-1-207 ~]$ podman -v
podman version 4.2.1

podman push myimageregistry.com/quay/demo2 --tls-verify=false --sign-by-sigstore-private-key=./cosign.key
Key Passphrase: 
Getting image source signatures
Copying blob cf1c1d4e7b97 done  
Copying blob afa3537bdcd4 done  
Copying blob fe7b1e9bf792 done  
Copying blob 596139a369da done  
Copying blob a560084a04ef done  
Copying blob 8b56e06d2fd7 done  
Copying blob 421ac1c18bca done  
Copying blob 89be899c57c8 done  
Copying blob acdde886f333 done  
Copying blob ea711c005988 done  
Copying blob 0dfa4efd26e6 done  
Copying blob 3f5562cabc06 done  
Copying blob 8eb479c4888d done  
Copying config e270a11b9c done  
Writing manifest to image destination
Signing manifest using a sigstore signature
Storing signatures
Error: writing signatures: writing sigstore attachments is disabled by configuration
```

**Comment by rhatdan** [comment]
@mtrmac @vrothberg PTAL

**Comment by mtrmac** [comment]
See `use-sigstore-attachments` in https://github.com/containers/image/blob/main/docs/containers-registries.d.5.md#individual-configuration-sections .

Compare https://github.com/containers/image/issues/1613 .

**Comment by LiZhang19817** [comment]
@mtrmac this issue was resolved, thanks a lot for your help.
`podman push 301721915996.dkr.ecr.us-east-2.amazonaws.com/quay:python3 --sign-by-sigstore-private-key=./cosign.key
Key Passphrase: 
Getting image source signatures
Copying blob 8e079fee2186 done  
Copying blob 955c9335e041 done  
Copying blob 186da837555d done  
Copying blob 288cf3a46e32 done  
Copying blob 0c7daf9a72c8 done  
Copying blob 75ba02937496 done  
Copying blob d172a9e6f9e6 done  
Copying blob 793b971ccb99 done  
Copying blob cf399be408ea done  
Copying config da84e66c3a done  
Writing manifest to image destination
Signing manifest using a sigstore signature
Storing signatures`
