### ISSUE TITLE
podman generate systemd --new mishandles the --stop-timeout argument

### ISSUE THREAD

**Issue by nolange** [containers/podman#16149]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Generation a systemd unit file should take the `--stop-timeout` argument and pass it to
`podman stop`.

If the `--new` flag is used, then this is not happening.

**Steps to reproduce the issue:**

```bash
podman run --rm -d --name test debian sleep 10
podman generate systemd test --new  --stop-timeout 100
```

**Describe the results you received:**

```properties
TimeoutStopSec=160
ExecStartPre=/bin/rm -f %t/%n.ctr-id
ExecStart=/usr/bin/podman run \
	--cidfile=%t/%n.ctr-id \
	--cgroups=no-conmon \
	--rm \
	--sdnotify=conmon \
	--replace \
	-d \
	--name test debian sleep 10
ExecStop=/usr/bin/podman stop --ignore --cidfile=%t/%n.ctr-id
ExecStopPost=/usr/bin/podman rm -f --ignore --cidfile=%t/%n.ctr-id
```

**Describe the results you expected:**

```properties
TimeoutStopSec=160
ExecStartPre=/bin/rm -f %t/%n.ctr-id
ExecStart=/usr/bin/podman run \
	--cidfile=%t/%n.ctr-id \
	--cgroups=no-conmon \
	--rm \
	--sdnotify=conmon \
	--replace \
	-d \
	--name test debian sleep 10
ExecStop=/usr/bin/podman stop -t 100 --ignore --cidfile=%t/%n.ctr-id
ExecStopPost=/usr/bin/podman rm -f --ignore --cidfile=%t/%n.ctr-id
```

(I am not sure if the Timeout should be added in `ExecStopPost` aswell)

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue is only appearing if `--new` is used.

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.19.1
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
podman/unknown,now 4.2.1-0.1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@vrothberg PTAL

**Comment by vrothberg** [comment]
Thanks for reaching out, @nolange! I'll wrap up a PR to fix the issue.
