### ISSUE TITLE
Cannot install Podman 4.2.1 on Windows using the MSI Installer

### ISSUE THREAD

**Issue by phillipinman** [containers/podman#16145]
/kind bug

On the latest Podman release (4.2.1) using the Windows MSI the installation fails and rolls back due to an invalid add command in the MSI package, it specifically fails on the "C:\Program Files\Redhat\Podman\winpath.exe"

This occurs on both a clean install (a machine that has never had podman) and a upgrade (4.1.0 MSI works fine).

Due to this taking place on a work machine I can't really provide a screenshot, but if it's essential to provide more info I can work something out.

Many Thanks!

**Steps to reproduce the issue:**

1. Download Podman 4.2.1 MSI on Windows

2. Run the MSI.

3. It will fail to install.

**Describe the results you received:**
MSI failed to install. Event logs show its to do with the path above.

**Describe the results you expected:**
Expected Podman to be installed successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
NA, isnt installed successfully

**Output of `podman info`:**
NA

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

NA

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows 10 Enterprise with Hyper-V and WSL2

**Comment by mheon** [comment]
@n1hility PTAL

**Comment by n1hility** [comment]
we've had reports of ml based security scanning software (e.g. falcon) blocking executable execution of bundled untrusted installer artifacts. To address this we moved to a new installer (coming in 4.3.0) which is fully signed (lowering false positives). I'll close this for now since the legacy msi is retired, but feel free to reopen or file a new issue if it persists after 4.3
