### ISSUE TITLE
kill cpcontainer: could not be stopped... sending SIGKILL... container state improper

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#16142]
```bash
[+0401s] not ok 127 podman cp file from host to container
....
# podman cp /tmp/podman_bats.rNSXlF/cp-test-file-host-to-ctr/hostfile0 cpcontainer:/IdoNotExist/
Error: "/IdoNotExist/" could not be found on container cpcontainer: no such file or directory
[ rc=125 (expected) ]
# podman kill cpcontainer
cpcontainer
# podman rm -t 0 -f cpcontainer
open pidfd: No such process
Error: cannot remove container <ID> as it could not be stopped: sending SIGKILL to container <ID>: container state improper
[ rc=2 (** EXPECTED 0 **) ]
```
### [sys] 127 podman cp file from host to container
* fedora-36-aarch64 : sys podman fedora-36-aarch64 root host
  * PR #16072
    * [10-07 05:31](https://api.cirrus-ci.com/v1/artifact/task/5531884187811840/html/sys-podman-fedora-36-aarch64-root-host.log.html#t--00127)
* fedora-36-aarch64 : sys remote fedora-36-aarch64 root host [remote]
  * PR #15894
    * [09-21 16:44](https://api.cirrus-ci.com/v1/artifact/task/5694475040194560/html/sys-remote-fedora-36-aarch64-root-host.log.html#t--00124)
```
Only two instances so far, both on f36 aarch64 root.

**Comment by vrothberg** [comment]
``` 
        # # podman kill cpcontainer
         # cpcontainer
         # # podman rm -t 0 -f cpcontainer
         # open pidfd: No such process
         # Error: cannot remove container 1ade81d6e299e45fdb601a576ea555afcd674f4670b428dd62385cb54da77041 as it could not be stopped: sending SIGKILL to container 1ade81d6e299e45fdb601a576ea555afcd674f4670b428dd62385cb54da77041: container state improper
         # [ rc=2 (** EXPECTED 0 **) ]
```

That's interesting.  The `podman kill` succeeded and the following `podman rm` fails.

**Comment by vrothberg** [comment]
I opened https://github.com/containers/podman/pull/16151 to improve the error message.  I really want to know which state the container is in.

**Comment by edsantiago** [comment]
You got [lucky!](https://api.cirrus-ci.com/v1/artifact/task/5826842409041920/html/sys-podman-fedora-36-aarch64-root-host.log.html#t--00134):
```
Error: cannot remove container [...]: container state improper: stopped
```

**Comment by vrothberg** [comment]
Wuaaaaaaa ... I expected everything but that O.O

**Comment by edsantiago** [comment]
Failed in [nightly cron, f36 rootless](https://api.cirrus-ci.com/v1/artifact/task/5453346147401728/html/sys-podman-fedora-36-rootless-host.log.html#t--00311). Again, state is `stopped`. So far we've seen this root and rootless, f36 amd64 and aarch64.

**Comment by vrothberg** [comment]
https://github.com/containers/podman/pull/16177 should fix the issue.  I am surprised this didn't flake more.

**Comment by edsantiago** [comment]
Reopening, sorry. Just saw this on #16275, which was based on 589ff20aa3dd68009af5fade3b2b5e1823d4227b, which is very recent and includes #16177. [f36-aarch64 remote root](https://api.cirrus-ci.com/v1/artifact/task/4511754091757568/html/sys-remote-fedora-36-aarch64-root-host.log.html#t--00346):
```
not ok 346 podman selinux: inspect multiple labels
...
# podman-remote  rm -t 0 -f myc
Error: cannot remove container <CID> as it could not be stopped: 
     sending SIGKILL to container <CID>: container state improper: stopped
```

**Comment by vrothberg** [comment]
> Reopening, sorry.

Monsieur, I _love_ your reports and bookkeeping.  Some flakes are more stubborn than others.  The error message strongly suggests another fart/race in the kill code.  I will take a look today.

**Comment by vrothberg** [comment]
https://github.com/containers/podman/pull/16320 should fix the issue.  It's slightly different but effectively a similar scenario as before.  When sending signals to the container, Podman releases the lock to prevent `podman stop` from blocking any other command trying to do something with the container. In the last failure above, the container exited so the container wasn't running anymore.

**Comment by edsantiago** [comment]
That was quick! Thank you!

**Comment by edsantiago** [comment]
Another "container state improper" flake, but I'm not sure if it's the same cause. This time in [int remote f37 root](https://api.cirrus-ci.com/v1/artifact/task/6108071903100928/html/int-remote-fedora-37-root-host.log.html#t--podman-restart-stopped-container-by-ID--1) but it's in `podman restart`:
```console
# podman-remote [options] start 755ed1a8ac74984410bd7817cec045e56038e06a2133ab9592e70bc9da623c62
755ed1a8ac74984410bd7817cec045e56038e06a2133ab9592e70bc9da623c62
# podman-remote [options] restart 755ed1a8ac74984410bd7817cec045e56038e06a2133ab9592e70bc9da623c62
open pidfd: No such process
Error: sending SIGKILL to container 755ed1a8ac74984410bd7817cec045e56038e06a2133ab9592e70bc9da623c62: container state improper: stopped
```

**Comment by vrothberg** [comment]
This one looks different to me.  Would you create a new issue for it?

**Comment by vrothberg** [comment]
Yes, it looks different to me.

**Comment by edsantiago** [comment]
Sorry, I'm having trouble interpreting that. Can you clarify whether I should 
1. assign those three failures to this issue (16142), or 
2. leave those three assigned to the everything-hosed issue (15367)?

**Comment by vrothberg** [comment]
Apologies, I think they look more like #15367 but things are getting blurry a bit.  Some symptoms tend to occur simultaneously at times.
