### ISSUE TITLE
API forwarding not working

### ISSUE THREAD

**Issue by krishnanrajah** [containers/podman#16168]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

After setting up podman, the API forwarding doesn't seem to be working in Windows wsl.

**Steps to reproduce the issue:**

1. Install podman-v4.2.1.msi

2. After podman machine init, do podman machine start.
Starting machine "podman-machine-default"
This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

        podman machine set --rootful

API forwarding listening on: npipe:////./pipe/docker_engine

Machine "podman-machine-default" started successfully

3. run .\docker.exe run -it fedora echo "Hello Podman!"

**Describe the results you received:**
.\docker.exe : The term '.\docker.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ .\docker.exe run -it fedora echo "Hello Podman!"
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\docker.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Describe the results you expected:**
Hello Podman!

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.16.15
Git Commit:   62b324ddf718411b1d4d0ba8117c632f7f984a38
Built:        Wed Sep  7 08:08:04 2022
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.18.5
Built:        Wed Sep  7 14:58:19 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.16.15
Git Commit:   62b324ddf718411b1d4d0ba8117c632f7f984a38
Built:        Wed Sep  7 08:08:04 2022
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.18.5
Built:        Wed Sep  7 14:58:19 2022
OS/Arch:      linux/amd64
PS C:\Users\krajah> podman info
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.4-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: '
  cpuUtilization:
    idlePercent: 99.92
    systemPercent: 0.06
    userPercent: 0.02
  cpus: 12
  distribution:
    distribution: fedora
    variant: container
    version: "36"
  eventLogger: journald
  hostname: INTLWR9110022
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.60.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 25807605760
  memTotal: 26669064192
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.6-2.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.6
      commit: 18cf2efbb8feb2b2f20e316520e0fd0b6c41ef4d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 7516192768
  swapTotal: 7516192768
  uptime: 0h 50m 14.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 269490393088
  graphRootUsed: 826281984
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.1
  Built: 1662580699
  BuiltTime: Wed Sep  7 14:58:19 2022
  GitCommit: ""
  GoVersion: go1.18.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows, WSL2

**Comment by arixmkii** [comment]
```
.\docker.exe : The term '.\docker.exe' is not recognized as the name of a cmdlet, function, script file, or operable
program
```
Looks like you don't have docker binary installed.

**Comment by arixmkii** [comment]
If you don't want to use anything docker you can absolutely stay with podman only. Podman provides its own binary called podman and in many cases you will be good just changing docker to podman.
Example
```
docker run --name some-nginx -d -p 8080:80 some-content-nginx
```
will become
```
podman run --name some-nginx -d -p 8080:80 some-content-nginx
```

It will not utilize this docker socket and work straight with the underlying podman.

As you mentioned API forwarding explicitly my guess was that you are trying to utilize podman to replace something, which was docker before (either command line or some GUI tool). You don't need docker API forwarding to work with podman on Windows.

**Comment by mheon** [comment]
Can you provide further details on what kind of API forwarding you're expecting? Podman machine mounts a Docker-compatible API socket on the host, which thus far has been adequate for most of our use cases.

**Comment by rhatdan** [comment]
Since we have had no feedback, I am closing, reopen if you can give @mheon the feedback.

**Comment by resuarez** [comment]
I am having the same error.  If I understand well, only installing Podman should I have access to docker from powershell, but using docker work, not podman.  However, everything goes like the documentation describes, except that I get the same behavior mentioned here.  I am wondering what I am doing wrong.
