### ISSUE TITLE
Podman's `--dns` + `--network` is different than docker's `--dns`  + `--network` 

### ISSUE THREAD

**Issue by flouthoc** [containers/podman#16172]
I think Podman's `--dns` is behaving differently than how is it supposed to work when comparing with `docker` when a container is started with `--network`.

# What Podman is doing when `--dns` is used with `--network`

Podman's `--dns` is overrding the `nameservers` inside container's `/etc/resolv.conf`

So `podman run --network test --dns 8.8.8.8 ...`   will produce a `/etc/resolv.conf` inside container with following content.
```console
bash-5.1# cat /etc/resolv.conf 
nameserver 8.8.8.8
```

Following behavior mismatches with docker.

# What docker is doing when `--dns` is used with `--network`

Docker is setting the custom dns server instead of host's `/etc/resolv.conf` when container makes request to docker's DNS resolver. Actual `/etc/resolv.conf` inside the container is never changed with `docker` irrespective of `--dns` flag with `--network` flag.

See the text here: https://docs.docker.com/config/containers/container-networking/#dns-services

**Comment by flouthoc** [comment]
@mheon @Luap99 Could you please confirm if I am reading this right.

**Comment by mheon** [comment]
What we are doing matches what Docker does for networks that do not have DNS enabled, last I checked.

It is, as you note, not correct for networks with DNS enabled. In those cases, Docker's internal DNS service takes over.

I don't see any harm in keeping the user-added DNS servers in resolv.conf, though. Just need to make sure that Aardvark is first.

**Comment by flouthoc** [comment]
@mheon Fair enough if container is connected to any network where DNS is enabled then we can keep aardvark's nameserver first, that should be enough to unblock my use-case. I'll open a PR to fix this first. ( cc @baude for info )

**Comment by flouthoc** [comment]
@mheon Upon checking again I like docker's way better since I don't see any value of repeating `nameservers` for case where container is connected to a network where `dns_enabled: true` in `/etc/resolv.conf` instead i see a drawback.

* Resolution via custom DNS server will be already handled by `aardvark-dns` or `dnsname` since its always first entry in `/etc/resolv.conf` additional entry for custom DNS server will just ensure that request fails again ( just decreasing the performance ).
 
Following PR should address this: https://github.com/containers/podman/pull/16175

**Comment by Luap99** [comment]
> Resolution via custom DNS server will be already handled by aardvark-dns or dnsname since its always first entry in /etc/resolv.conf additional entry for custom DNS server will just ensure that request fails again since it be will processed only when aardvark-dns or dnsname fails ( where they have already tried against custom DNS server ) overall this process is just decreasing the lookup performance .

This is only true when aardvark-dns has support for that. Before we add support for that we should not change this IMO

**Comment by mheon** [comment]
Also, should we make this a Netavark-only thing? CNI should probably continue to use the old behavior.

**Comment by flouthoc** [comment]
> Also, should we make this a Netavark-only thing? CNI should probably continue to use the old behavior.

Sure SGTM. I'll add a filter for `netavark` only.

**Comment by rhatdan** [comment]
@flouthoc Any movement on this one?

**Comment by flouthoc** [comment]
I just need to rebase my original PR since new version of netavark and aardvark are already out.

**Comment by rhatdan** [comment]
@flouthoc did the rebase ever happen?

**Comment by flouthoc** [comment]
Waiting for latest version of `nv/av` in the CI.
