### ISSUE TITLE
RFE: Make hack scripts pretty

### ISSUE THREAD

**Issue by cevich** [containers/podman#16190]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Both `hack/install_golangci.sh` and `install_swagger.sh` are fugly, scary, and full of hard-to-maintain secrets.

**Steps to reproduce the issue:**

1. run `make install.tools`

2. wonder why it broke for you

3. Scream after looking at the scripts

**Describe the results you expected:**

A rosy bouquet, smooth on the middle pallet, with a nutty finish and pleasant, lasting after-taste.

**Describe the results you received:**

An emergency eyewash wash from an old, rusty, gasoline can.

**Additional information you deem important (e.g. issue happens only occasionally):**

[In a PR](https://github.com/containers/podman/pull/16161#issuecomment-1278078515) @edsantiago suggested https://github.com/containers/podman/files/9779375/install_swagger.sh.txt (untested)

**Output of `podman version`:**

N/A

**Output of `podman info`:**

N/A

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

N/A

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

CI & every developer's workstation (likely with a `$PREFIX` override)

**Comment by rhatdan** [comment]
@cevich is this still an issue?

**Comment by cevich** [comment]
It is, I'm simply too lazy to fix it.  @edsantiago had posted a suggested fix but I was riding my "urgent-fix steam-roller" at the time, so it's also untested :disappointed:   I'm fine with keeping my head in the sand, but could work on a fix next week if y'all feel it's important.

**Comment by cevich** [comment]
K.  I'm going to take the lazy approach then and close this.  They are "hack" scripts after-all.  If a fix is needed or someone is bored, the links here should help.
