### ISSUE TITLE
Rootless container based on Ubuntu official does not have internet access

### ISSUE THREAD

**Issue by s-m-e** [containers/podman#16193]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Just installed `podman` on a fresh Linux Mint 21 system (more or less equivalent to Ubuntu 22.04 LTS). I am experimenting with the [official ubuntu image from dockerhub](https://hub.docker.com/_/ubuntu) (latest) and the [official alpine image from dockerhub](https://hub.docker.com/_/alpine) (latest).

While rootless containers based on the alpine image can access the internet, rootless containers based on the ubuntu images fail to - though this is not expected as far as I understand. 

Not sure if this is a podman issue or something else. Please excuse if this does not belong here.

**Steps to reproduce the issue:**

1. Try rootless ubuntu:

```
$ podman run ubuntu:22.04 apt update
[...]
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy/InRelease  Could not resolve 'archive.ubuntu.com'
[...]
```

2. Try alpine for comparison:

```
$ podman run alpine wget archive.ubuntu.com
Connecting to archive.ubuntu.com (91.189.91.39:80)
saving to 'index.html'
index.html           100% |********************************|   696  0:00:00 ETA
'index.html' saved
```

3. Try ubuntu with root privileges:

```
$ sudo podman run ubuntu:22.04 apt update
[...]
Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
[...]
Fetched 23.4 MB in 5s (4838 kB/s)
[...]
```

**Describe the results you received:**

Rootless containers based on the alpine image have internet access, rootless containers based on the ubuntu image does not.

**Describe the results you expected:**

Both should have internet access (rootless).

**Additional information you deem important (e.g. issue happens only occasionally):**

Firewall via UFW enabled. Reject incomming (except for TCP on one port >10k), allow outgoing.

**Output of `podman version`:**

```
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 48
  distribution:
    codename: vanessa
    distribution: linuxmint
    version: "21"
  eventLogger: journald
  hostname: e2
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.0-50-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 255237779456
  memTotal: 270119550976
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 0
  swapTotal: 0
  uptime: 13m 44.06s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/ernst/.config/containers/storage.conf
  containerStore:
    number: 14
    paused: 0
    running: 0
    stopped: 14
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.10.5
        fuse-overlayfs: version 1.7.1
        FUSE library version 3.10.5
        using FUSE kernel interface version 7.31
  graphRoot: /home/ernst/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: zfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  volumePath: /home/ernst/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 3.4.4
```

**Package info -> `apt list podman`:**

```
podman/jammy,now 3.4.4+ds1-1ubuntu1 amd64  [installiert]
```

**Have you tested with the latest version of Podman [...]**

Not yet.

**[...] and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Nothing matching found (perhaps I am wrong here).

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical box.

**Comment by Luap99** [comment]
Have you tried ping to verify network connectivity? Right now I only see that dns is not working.
Also try running `podman run --security-opt seccomp=unconfined ...` to disable seccomp.

**Comment by s-m-e** [comment]
@Luap99 Thanks for the reply. `--security-opt seccomp=unconfined` does not change anything.

`ping`: I just mounted a folder containing a copy of the host's `ping` binary into the container since the Ubuntu image is missing it (and getting it via `apt` is a dead end), et voila ... 

```
$ ./mnt/ping archive.ubuntu.com
PING archive.ubuntu.com (185.125.190.36) 56(84) bytes of data.
64 bytes from actiontoad.canonical.com (185.125.190.36): icmp_seq=1 ttl=255 time=39.3 ms
[...]
```

`ping` is resolving hosts, `apt` is not (but then only for rootless containers) ... ? Potentially yet another stupid question: What am I looking at?

`apt`'s entire output might perhaps offer a clue:

```
$ apt update
Ign:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Ign:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Ign:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Ign:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Ign:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Err:1 http://archive.ubuntu.com/ubuntu jammy InRelease
  Could not resolve 'archive.ubuntu.com'
Err:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
  Could not resolve 'security.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
  Could not resolve 'archive.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
  Could not resolve 'archive.ubuntu.com'
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: Problem unlinking the file /var/lib/apt/lists/partial/.apt-acquire-privs-test.AdPzrX - IsAccessibleBySandboxUser (95: Operation not supported)
W: Problem unlinking the file /var/lib/apt/lists/partial/.apt-acquire-privs-test.wsLxaP - IsAccessibleBySandboxUser (95: Operation not supported)
W: Problem unlinking the file /var/lib/apt/lists/partial/.apt-acquire-privs-test.KBYb3N - IsAccessibleBySandboxUser (95: Operation not supported)
W: Problem unlinking the file /var/lib/apt/lists/partial/.apt-acquire-privs-test.LgqCmU - IsAccessibleBySandboxUser (95: Operation not supported)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy/InRelease  Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease  Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/jammy-backports/InRelease  Could not resolve 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease  Could not resolve 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

The line(s) similar to `W: Problem unlinking the file /var/lib/apt/lists/partial/.apt-acquire-privs-test.AdPzrX - IsAccessibleBySandboxUser (95: Operation not supported)` also do not show up when the container runs rootful.

**Comment by Luap99** [comment]
Does `--privileged` work? Either way I highly recommend to update and try again, we cannot support old versions upstream.
Since some images work I suspect it is something like this: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=995777

**Comment by s-m-e** [comment]
@Luap99 `--privileged` does not change stuff, either.

> I highly recommend to update and try again, we cannot support old versions upstream.

[In my case, Ubuntu](https://podman.io/getting-started/installation#ubuntu), this would involve getting the packages from the Kubic project, right? The documentation so wonderfully states "CAUTION: The Kubic repo is NOT recommended for production use" - which makes me wonder what is supported "more"/"better" ;)

Anyway, tried to update. A dependency, `netavark`, is missing. It appears that [its build for Ubuntu 22.04 failed](https://build.opensuse.org/packages/netavark/job_history/devel:kubic:libcontainers:unstable/xUbuntu_22.04/x86_64), hence there is no package in the repo.

**Comment by rhatdan** [comment]
Not sure how the file system would effect the network stack.
@giuseppe any ideas?

**Comment by giuseppe** [comment]
```
Problem unlinking the file /var/lib/apt/lists/partial/.apt-acquire-privs-test.AdPzrX - IsAccessibleBySandboxUser (95: Operation not supported)
```

does the underlying file system misbehave with fuse-overlay?

I'd first try these things in order:
- upgrade Podman/fuse-overlayfs
- try with a new kernel and native overlay
- strace the fuse-overlayfs while the process is running to understand what syscall is failing with `EOPNOTSUP`.  It might be lack of xattrs.

**Comment by dvdsk** [comment]
I can reproduce this issue (also on ZFS)

On my zfs system I can call `fuse-overlayfs` on a bunch of freshly made directories without problems. Even with lowerdirs spread across different types of filesystems (ext4 and zfs) and different zfs datasets. 

- versions
  - podman: version: 3.4.4
  - fuse-overlayfs: version 1.7.1
  - FUSE library version 3.10.5
  - using FUSE kernel interface version 7.31
  - fusermount3 version: 3.10.5
- linux kernel: 6.2.6-76060206-generic
 
I ran strace on podman like this:
```
strace -f podman build -t test:latest . &> out
```

The output is huge, so I grepped it down to only the lines around `EOPNOTSUPP`. Leaving only 1k lines. I put those up in a gist [here](https://gist.github.com/dvdsk/74be010d67ef7bce32e6c135efc951db) in case you need to dig around.

It seems like its indeed the xattr that are the cause of the problem. Of the 311 EOPNOTSUPP fails 155 have to do with xattrs. 

The rest are made up of:
 - connect resumed
 - connect resumed
 - openat resumed
 - stat resumed
 - unlink resumed
 - ioctl

**Comment by giuseppe** [comment]
upgrade to fuse-overlayfs 1.12.  Now it automatically detects when the underlying file system supports ACLs.  If they are not supported, then fuse-overlayfs won't use them.

**Comment by dvdsk** [comment]
that worked! Issue competently went away. Thank you very much for your help! I think this issue can be closed now?  

For anyone else running into this, building fuse-overlayfs is easy using [buildah](https://github.com/containers/fuse-overlayfs#static-build). That should work with sudo as long as you are not running zfs on root.

**Comment by giuseppe** [comment]
thanks for confirming it
