### ISSUE TITLE
Error to run "podman machine init"

### ISSUE THREAD

**Issue by azevedoedison** [containers/podman#16218]
I'm not able to run the "podman machine init" command.

I am using Windows 10, podman-v4.2.1.msi and podman-desktop-0.8.0.

Occur the following error:
`An error occurred attempting the WSL Kernel update, retrying... Could not install the WSL Kernel. See previous output for any potential failure details. If you can not resolve the issue, try rerunning the "podman machine init command". If that fails try the "wsl --update" command and then rerun "podman machine init". Finally, if all else fails, try following the steps outlined in the following article: http://docs.microsoft.com/en-us/windows/wsl/install Error: could not install WSL Kernel: exit status 4294967295`

I installed the [WSL2 Linux kernel update package for x64 machines](https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi)

I already did all these steps on https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-2---check-requirements-for-running-wsl-2

I tried to do https://www.thewindowsclub.com/wsl-process-exited-with-code-4294967295-in-windows-11  but not work for me.

My Docker desktop works very well, but I cannot create a image of podman, I don't know why.

![erro](https://user-images.githubusercontent.com/414878/196471484-5aa7ee9b-5183-4b87-9694-e3fc481e7986.PNG)

**Comment by mheon** [comment]
@n1hility PTAL

**Comment by n1hility** [comment]
Hi @azevedoedison, sorry this isn't working for you. 

Could you post the output of a wsl --status?

**Comment by n1hility** [comment]
If you want to try resetting from a clean slate here is a suggested workflow:
(note: be sure to backup anything you have on docker desktop that you need to keep before doing this)

1. Run  `dism.exe /online /disable-feature /featurename:Microsoft-Windows-Subsystem-Linux /norestart`
2. After completion reboot
3. Run `wsl --install` (it will force you to reboot)
4. Try podman machine init again

**Comment by rhatdan** [comment]
Since we never heard back, I am closing the issue.  Reopen if you have more feedback.

**Comment by thi28** [comment]
> If you want to try resetting from a clean slate here is a suggested workflow: (note: be sure to backup anything you have on docker desktop that you need to keep before doing this)
> 
> 1. Manually remove the windows linux kernel package (control panel -> add/remove software -> uninstall WSL kernel)
> 2. Run  `dism.exe /online /disable-feature /featurename:Microsoft-Windows-Subsystem-Linux /norestart`
> 3. After completion reboot
> 4. Run `wsl --install` (it will force you to reboot)
> 5. Try podman machine init again

Hello, i have the same issue when i run "podman machine init"
I use window 10, build 19042.685

Error: Launching WSL Kernel Install...
Elevated process failed with error: request to elevate privileges was denied
Could not install the WSL Kernel. See previous output for any potential failure details.
If you can not resolve the issue, and rerunning fails, try the "wsl --install" process
outlined in the following article:
http://docs.microsoft.com/en-us/windows/wsl/install
Error: request to elevate privileges was denied
![image](https://user-images.githubusercontent.com/120666340/207911289-28b94a08-4e73-42f4-a2bc-32b30f5385f7.png)

I followed your instructions. But when i run wsl --install, i had the error : Invalid command line option: --install
I tried also wsl.exe --install -d Ubuntu but i had the same error.
Do you have any idea to run podman machine init ?
Thank you in advance!

**Comment by n1hility** [comment]
@thi28 do you have the ability to run windows update on your install? 19042 is 20H2 which is pretty old (past EOL). I would recommend updating if at all possible.

If you can not upgrade you can try to follow the manual WSL install process yourself (pre --install) here:
https://learn.microsoft.com/en-us/windows/wsl/install-manual

Make sure you run these commands with an admin prompt.

**Comment by thi28** [comment]
> @thi28 do you have the ability to run windows update on your install? 19042 is 20H2 which is pretty old (past EOL). I would recommend updating if at all possible.
> 
> If you can not upgrade you can try to follow the manual WSL install process yourself (pre --install) here: https://learn.microsoft.com/en-us/windows/wsl/install-manual
> 
> Make sure you run these commands with an admin prompt.

@n1hility Hello, thank you for your quick response. 
I did already the manual installation http://docs.microsoft.com/en-us/windows/wsl/install
WSL worked, but Podman somehow didn't recognise the installed WSL. Everytime I tried to run "podman machine init" command, I had Error: Launching WSL Kernel Install... and it asked me to install WSL kernel again.
Do you have others options than windows update? I'm not sure if I can do a windows update because it's a computer of my company (I'm not admin).
Thank you in advance,
