### ISSUE TITLE
`podman run` reads /etc/containers/podman-machine

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#16235]
```
podman (main) $ sudo strace -fff ./bin/podman run --rm docker.io/library/alpine:latest true 2>&1 | grep "/etc/containers/podman-machine"
[pid 16323] openat(AT_FDCWD, "/etc/containers/podman-machine", O_RDONLY|O_CLOEXEC <unfinished ...>
[pid 16437] openat(AT_FDCWD, "/etc/containers/podman-machine", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

I did not check the code but I do not see any reason for a `podman run` to trigger reading `/etc/containers/podman-machine`.

FYI @baude @rhatdan @ashley-cui

**Comment by Luap99** [comment]
I cannot speak for all code paths but it is 100% required when ports are forwarded, is it read with --network=host?

**Comment by baude** [comment]
For the wider audience, this file is added by ignition when a new machine is booted.  The purpose of this file is to provide a "marker" so that Podman knows it is running in a machine "context".  There is precedent for doing this in other parts of Podman.  We could happily phase this out if we have better/faster ideas on providing a marker.

**Comment by rhatdan** [comment]
@baude @vrothberg @Luap99 What should we do with this one?

**Comment by vrothberg** [comment]
https://github.com/containers/podman/issues/16235#issuecomment-1285787690 explains why it's needed but I think we should still investigate whether the file is read for `--network=host`

**Comment by vrothberg** [comment]
--network=host drops one read, so I think we're cool?

```
podman (main) $ sudo strace -fff ./bin/podman run --rm --network=host docker.io/library/alpine:latest true 2>&1 | grep "/etc/containers/podman-machine"
[pid 34417] openat(AT_FDCWD, "/etc/containers/podman-machine", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
podman (main) $ sudo strace -fff ./bin/podman run --rm docker.io/library/alpine:latest true 2>&1 | grep "/etc/containers/podman-machine"
[pid 34495] openat(AT_FDCWD, "/etc/containers/podman-machine", O_RDONLY|O_CLOEXEC <unfinished ...>
[pid 34619] openat(AT_FDCWD, "/etc/containers/podman-machine", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
```

**Comment by Luap99** [comment]
The code uses a sync.Once so I would never expect more than one read per process, https://github.com/containers/common/blob/f5d94c3548cbb9100d2759ce354f7225d2f53842/pkg/machine/machine.go#L72

**Comment by rhatdan** [comment]
Can we close this issue?

**Comment by vrothberg** [comment]
Yes, letś close.
