### ISSUE TITLE
'podman exec --tty' and 'podman run --tty' connects the inner stderr to the outer stdout

### ISSUE THREAD

**Issue by debarshiray** [containers/podman#16254]
/kind bug

**Description**

I am not entirely sure about this one, so feel free to correct me if I am wrong.

@HarryMichal and I have been staring at how [Toolbx](https://github.com/containers/toolbox) wires up the standard output and standard error streams via Podman to the final child process running inside the container.  It seems like using the `--tty` flag connects the standard error stream of the inner process to the standard output of the outer.

The command running inside the container can be simplified to this somewhat pathological invocation:
```
$ sh -c 'sh /etc'
/etc: /etc: Is a directory
```

Teasing apart the standard output and output, we see that the error message is being written to the standard error stream:
```
$ sh -c 'sh /etc' 1>/dev/null
/etc: /etc: Is a directory
$ sh -c 'sh /etc' 2>/dev/null
```

When this is run inside a container:
```
$ podman run --rm --interactive --tty fedora:36 sh -c 'sh /etc'
/etc: /etc: Is a directory
$ podman run --rm --interactive fedora:36 sh -c 'sh /etc'
/etc: /etc: Is a directory
```

So far so good, but when we separate out the standard output and error streams, we see something odd.  When `--tty` is used the error message seems to be written to the outer `podman` process' standard output:
```
$ podman run --rm --interactive --tty fedora:36 sh -c 'sh /etc' 1>/dev/null
$ podman run --rm --interactive --tty fedora:36 sh -c 'sh /etc' 2>/dev/null
/etc: /etc: Is a directory
```

If `--tty` is not used, then the error gets written to the outer `podman` process' standard error as expected:
```
$ podman run --rm --interactive fedora:36 sh -c 'sh /etc' 1>/dev/null
/etc: /etc: Is a directory
$ podman run --rm --interactive fedora:36 sh -c 'sh /etc' 2>/dev/null
```

Is this expected behaviour?  Or a bug?  :)

I understand that `--tty` should only be used when there's a controlling terminal attached to the outer `podman` process.  I am using the redirected streams only as a way to understand what's exactly going on.

**Describe the results you expected:**

I expected that running with or without `--tty` wouldn't affect the stream to which the error message is getting written.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.18.5
Built:        Wed Sep  7 21:58:19 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: '
  cpuUtilization:
    idlePercent: 99.61
    systemPercent: 0.08
    userPercent: 0.3
  cpus: 16
  distribution:
    distribution: fedora
    variant: workstation
    version: "36"
  eventLogger: journald
  hostname: topinka
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.19.14-200.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 20732514304
  memTotal: 33554972672
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.6-2.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.6
      commit: 18cf2efbb8feb2b2f20e316520e0fd0b6c41ef4d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 49h 20m 58.00s (Approximately 2.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/rishi/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 1
    stopped: 2
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/rishi/.local/share/containers/storage
  graphRootAllocated: 1695606808576
  graphRootUsed: 150152040448
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 8
  runRoot: /run/user/1000/containers
  volumePath: /home/rishi/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.1
  Built: 1662580699
  BuiltTime: Wed Sep  7 21:58:19 2022
  GitCommit: ""
  GoVersion: go1.18.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
podman-4.2.1-2.fc36.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

I haven't tried Podman from Git, but I did look at the Troubleshooting Guide.  The guide has an entry for *Unexpected carriage returns are outputted on the terminal* but I don't think this is the same thing.  The presence of a nested terminal can affect some behaviour specific to terminals, like whether to use a carriage return or not, but not the standard output and error streams.  I could be wrong, though.

**Comment by mheon** [comment]
`--tty` does not have a separate STDOUT and STDERR. It puts the terminal in raw mode, and both streams write raw data to it, losing all distinction between the streams. This is unavoidable if using `--tty` or other raw terminal applications.

**Comment by debarshiray** [comment]
Oh, yes, of course.  Once you have written to a terminal, it's just a single stream of bytes.  The STDOUT and STDERR distinction is only there before that happens.

Thanks for helping me through the haze, @mheon :)
