### ISSUE TITLE
Allow filtering by image digest in REST API

### ISSUE THREAD

**Issue by pmengelbert** [containers/podman#16255]
/kind feature

**Description**

The [API endpoint](https://docs.podman.io/en/latest/_static/api.html#tag/images/operation/ImageListLibpod) `GET /libpod/images/json` allows filtering by image ID using the query parameter 
```
GET /libpod/images/json?filters={"id":["5d53c..."]}`
```

I propose adding a filter for `digest` in addition to `id`. For example:
```
GET /libpod/images/json?filters={"digest":["sha256:81bf1d..."]}
```

A use-case for this is when scanning images; the user/agent interested in the scan may know, for example, the content-addressable image digest but not the podman image ID. We may want to scan the image regardless of where it is located, whether in podman's store, containerd's store, or docker's store. This is the case in [trivy](https://github.com/aquasecurity/trivy), which will scan images in any of those locations. Without the ability to search by digest, trivy has to be run again after discerning the Image ID from podman.

As a more general benefit, it is always useful to find content-addressable things by a digest of their contents.

**Comment by rhatdan** [comment]
I would be fine with accepting a PR for this, are you interested in implementing this?

**Comment by pmengelbert** [comment]
@rhatdan It was pretty trivial to implement, but what's expected in terms of tests?

**Comment by rhatdan** [comment]
Greate a coule of images, and then filter by id and show that it only shows the one that matches.

**Comment by rhatdan** [comment]
@pmengelbert still working on this?

**Comment by pmengelbert** [comment]
@rhatdan The feature is simple but I haven't been able to write tests for it. I'm not able to work on it at the moment. Relevant diff is here if anyone wants to take over: https://github.com/containers/podman/compare/1c8b40d097a21d028896b913bcee238487a8b7d7...pmengelbert:podman:feat/digest_filter?expand=1

Otherwise I may return to this when time permits
