### ISSUE TITLE
podman machine init fails after fresh install 

### ISSUE THREAD

**Issue by soft4rchitecture** [containers/podman#16267]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

it's impossible to do podman machine init

**Steps to reproduce the issue:**

1. brew install podman

2. podman machine init

**Describe the results you received:**
Downloading VM image: fedora-coreos-36.20221014.2.0-qemu.aarch64.qcow2.xz: done 
Extracting compressed file Error: key generation failed, unable to read from stderr: exit status 1

**Describe the results you expected:**
podman successfully inits

**Additional information you deem important (e.g. issue happens only occasionally):**
podman can not even start, so version comes from `brew info podman`

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
==> podman: stable 4.3.0 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/opt/homebrew/Cellar/podman/4.3.0 (185 files, 47.6MB) *
  Poured from bottle on 2022-10-23 at 18:03:55
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0 and GPL-3.0-or-later
==> Dependencies
Build: go-md2man ✘, go@1.18 ✘
Required: qemu ✔
==> Options
--HEAD
        Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions

To restart podman after an upgrade:
  brew services restart podman
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/podman/bin/podman system service --time=0
==> Analytics
install: 20,540 (30 days), 68,225 (90 days), 214,776 (365 days)
install-on-request: 19,693 (30 days), 66,167 (90 days), 212,314 (365 days)
build-error: 0 (30 days)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
sw_vers yields: 
```
ProductName:    macOS
ProductVersion: 12.6
BuildVersion:   21G115
```

**Comment by mheon** [comment]
@baude @ashley-cui PTAL

**Comment by ashley-cui** [comment]
Looks like an SSH key generation issue, do you know if you're using a standard SSH on your machine?

**Comment by soft4rchitecture** [comment]
running `ssh -V`yields: 
OpenSSH_8.6p1, LibreSSL 3.3.6

**Comment by soft4rchitecture** [comment]
Now it works, so, something went wrong with the fact that the ssh key pair having the same name was already in $HOME/.ssh 
Does that mean anything to you ? Is that ok by you ? I mean, probably it should erase that keypair shouldn't it ? I mean, it's like a reserved name for the keypair? 
How do you approach this question?? 
Thanks

**Comment by benoitf** [comment]
I'm having this issue from time to time as well.
Deleting the machine and performing again `podman machine init` is working

it's hard to reproduce as it happens from time to time.

**Comment by benoitf** [comment]
```
$ podman machine init foo
Downloading VM image: fedora-coreos-36.20221030.2.1-qemu.x86_64.qcow2.xz: done
Extracting compressed file
Error: key generation failed, unable to read from stderr: exit status 1

$ podman machine init foo
Error: foo: VM already exists

$ podman machine rm foo

The following files will be deleted:

/Users/benoitf/.ssh/foo
/Users/benoitf/.ssh/foo.pub
/Users/benoitf/.config/containers/podman/machine/qemu/foo.ign
/Users/benoitf/.local/share/containers/podman/machine/qemu/foo_fedora-coreos-36.20221030.2.1-qemu.x86_64.qcow2
/Users/benoitf/.local/share/containers/podman/machine/foo/podman.sock
/Users/benoitf/.config/containers/podman/machine/qemu/foo.json


Are you sure you want to continue? [y/N] y


$ podman machine init foo
Extracting compressed file
Image resized.
Machine init complete
To start your machine run:

	podman machine start foo
```

**Comment by rhatdan** [comment]
Are we still seeing this?  Perhaps the problem is in qemu on a Mac.

**Comment by soft4rchitecture** [comment]
Well, it’s more related to ssh keys in home directory rather than a problem in qemu but are you suggestions qemu is managing those keys?

**Comment by rhatdan** [comment]
@cdoern @ashley-cui Thoughts?

**Comment by rhatdan** [comment]
I don't see a way to handle this properly so I am closing, since you were able to solve the problem.
