### ISSUE TITLE
Play remote system tests do not test proper failure in unsupported cases

### ISSUE THREAD

**Issue by ygalblum** [containers/podman#16271]
/kind bug

**Description**
Some features, e.g. `podman play --build`, are only supported locally and therefore block the user from using them with podman-remote. However, the system tests skip the relevant tests instead of verifying that the requests properly fail (see https://github.com/containers/podman/blob/main/test/system/700-play.bats#L243)

**Steps to reproduce the issue:**
Run the system test: `PODMAN=./bin/podman-remote bats test/system/700-play.bats`

**Describe the results you received:**
The test "podman play --build --context-dir" is skipped

**Describe the results you expected:**
The test verifies that the request was properly blockes

**Comment by vrothberg** [comment]
Thanks for filing the issue, @ygalblum !

**Comment by rhatdan** [comment]
@ygalblum @vrothberg Is the goal here to fix the tests or implement podman kube play --build for the remote API?

**Comment by vrothberg** [comment]
I don't think that supporting `--build` on remote clients is worth the effort.  At least for now where nobody has asked to support it.

So making sure the tests do proper error checks for remote clients SGTM

**Comment by vrothberg** [comment]
Still a TODO

**Comment by Luap99** [comment]
There is some demand to add remote build support https://github.com/containers/podman/pull/24435
so this here can be closed I would say
