### ISSUE TITLE
podman logs doesn't work (related to #15159?)

### ISSUE THREAD

**Issue by Coachonko** [containers/podman#16279]
I am experiencing this issue on Podman 4.1.1, the system is running RHEL 9.

I run the containers as root

```shell
# Create container instance
podman run \
  --detach \
  --name=percona \
  --publish=29120:3306 \
  --label="io.containers.autoupdate=registry" \
  --tz=local \
  --mount=type=bind,src=/root/percona/my.cnf,dst=/etc/my.cnf.d/my.cnf,readonly=true \
  --mount=type=bind,src=/root/percona/data,dst=/var/lib/mysql \
  --mount=type=bind,src=/root/percona/log,dst=/var/log/mysql \
  --user=2000 \
  percona/percona-server

# Check logs with 
podman logs percona
```
```
Error: initial journal cursor: failed to get cursor: cannot assign requested address
```

I looked at #15159, that person who opened that issue seems to have had a ppermissions issue with the podman user, but on my system the /etc/shadow does not contain any podman user.

Is there a known issue or solution about this?

**Comment by Luap99** [comment]
Can you please fill out the issue template as requested and provide a simpler reproducer which does not depend on that specific image. (I don't know what percona is nor do I have the defined volumes).

Also note that we (upstream) only provide support for the latest versions so please make sure to test with the latest version. If you have problems with the version in RHEL it is best to reach out to Red Hat support or create a [bugzilla](https://bugzilla.redhat.com).

**Comment by Coachonko** [comment]
I have found out the problem was not a bug. It was caused by another completely unrelated process flooding the systemd logs, whenever podman would request access to the log file it would have been rotated before it could be accessed, causing the error.
