### ISSUE TITLE
Netavark: userns: nc: bad address 'nc-server.dns.podman'

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#16272]
In podman int tests:
```
podman Netavark network works across user ns
...
$ podman [options] run --log-driver k8s-file --rm --net 051ae9d9bd --uidmap 0:1:4096 \
       quay.io/libpod/alpine:latest \
       sh -c echo podman | nc -w 1 nc-server.dns.podman 9480
nc: bad address 'nc-server.dns.podman'
```
Probably a race condition in test setup. Rare, but still triggering.

### Podman run networking [It] podman Netavark network works across user ns 
* fedora-36 : int podman fedora-36 root container
  * PR #15131
    * [09-20-2022 17:14](https://api.cirrus-ci.com/v1/artifact/task/5063465407610880/html/int-podman-fedora-36-root-container.log.html#t--podman-Netavark-network-works-across-user-ns--1)
    * [09-20-2022 17:14](https://api.cirrus-ci.com/v1/artifact/task/5063465407610880/html/int-podman-fedora-36-root-container.log.html#t--podman-Netavark-network-works-across-user-ns--2)
    * [09-20-2022 17:14](https://api.cirrus-ci.com/v1/artifact/task/5063465407610880/html/int-podman-fedora-36-root-container.log.html#t--podman-Netavark-network-works-across-user-ns--3)
* fedora-36 : int podman fedora-36 rootless host
  * PR #16234
    * [10-21 00:02](https://api.cirrus-ci.com/v1/artifact/task/5412605295591424/html/int-podman-fedora-36-rootless-host.log.html#t--podman-Netavark-network-works-across-user-ns--1)
    * [10-21 00:02](https://api.cirrus-ci.com/v1/artifact/task/5412605295591424/html/int-podman-fedora-36-rootless-host.log.html#t--podman-Netavark-network-works-across-user-ns--2)
    * [10-21 00:02](https://api.cirrus-ci.com/v1/artifact/task/5412605295591424/html/int-podman-fedora-36-rootless-host.log.html#t--podman-Netavark-network-works-across-user-ns--3)
* fedora-36 : int remote fedora-36 root host [remote]
  * PR #15479
    * [08-29-2022 04:14](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4734581415870464/html/int-remote-fedora-36-root-host.log.html#t--podman-Netavark-network-works-across-user-ns--1)
    * [08-29-2022 04:14](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4734581415870464/html/int-remote-fedora-36-root-host.log.html#t--podman-Netavark-network-works-across-user-ns--2)
    * [08-29-2022 04:14](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4734581415870464/html/int-remote-fedora-36-root-host.log.html#t--podman-Netavark-network-works-across-user-ns--3)
  * PR #15474
    * [08-25-2022 00:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6024322815885312/html/int-remote-fedora-36-root-host.log.html#t--podman-Netavark-network-works-across-user-ns--1)
    * [08-25-2022 00:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6024322815885312/html/int-remote-fedora-36-root-host.log.html#t--podman-Netavark-network-works-across-user-ns--2)
    * [08-25-2022 00:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6024322815885312/html/int-remote-fedora-36-root-host.log.html#t--podman-Netavark-network-works-across-user-ns--3)

**Comment by Luap99** [comment]
I think this is the same as https://github.com/containers/podman/issues/14173,
the dns tests never fails alone which means that some condition is causing aardvark to fail and keep it from working again.
We reworked the start-up so it should be better now? Do we know the netavark/aardvark version from the tests?

**Comment by Luap99** [comment]
Thanks, we keep aardvark and netavark in sync so it should be the same. Using netavark/aardvark v1.2 might fix this but honestly I don't know since the underlying cause is unknown.

**Comment by Luap99** [comment]
@edsantiago Any new instances in your log?

**Comment by edsantiago** [comment]
@Luap99 I'm still working my way through the last few weeks of flakes. I'll try to answer later today.

**Comment by edsantiago** [comment]
Never mind, I forgot about `cirrus-flake-grep`. It shows the last instances on October 20 and 21, so I'm declaring this fixed.

**Comment by edsantiago** [comment]
Reopening. My disable-retries PR (#17831) shows that this is [still happening even on main with updated CI VMs](https://api.cirrus-ci.com/v1/artifact/task/6146559918735360/html/int-podman-fedora-37-root-container-sqlite.log.html#t--podman-Netavark-network-works-across-user-ns--1):
```
podman Netavark network works across user ns
...
# podman [options] network create f48f8e5b27
f48f8e5b27
# podman [options] run --log-driver k8s-file -d --name nc-server --net f48f8e5b27 quay.io/libpod/alpine:latest nc -l -p 9480
117a5425064b2bd6b8417e53c797b8a2271c8fcc2f5f3cfcef9cc89433b60e55
# podman [options] run --log-driver k8s-file --rm --net f48f8e5b27 --uidmap 0:1:4096 quay.io/libpod/alpine:latest sh -c echo podman | nc -w 1 nc-server.dns.podman 9480
nc: bad address 'nc-server.dns.podman'
```
We're probably not seeing it because it passes on retry.

**Comment by edsantiago** [comment]
Another one, [remote f37 root](https://api.cirrus-ci.com/v1/artifact/task/5302134988603392/html/int-remote-fedora-37-root-host-sqlite.log.html#t--podman-Netavark-network-works-across-user-ns--1)

**Comment by edsantiago** [comment]
And another one, [f37 root not-remote](https://api.cirrus-ci.com/v1/artifact/task/5442872476958720/html/int-podman-fedora-37-root-host-sqlite.log.html#t--podman-network-works-across-user-ns--1)

**Comment by Luap99** [comment]
Sure this was never really fixed. There is absolutely no guarantee that aardvark-dns is ready before the container is started.

**Comment by edsantiago** [comment]
>There is absolutely no guarantee that aardvark-dns is ready before the container is started.

This disturbs me. For tests, it's easy to add `sleep(5)` and sweep that under the rug, but I can envision a number of real-world scenarios in which users will want to do DNS queries early on. (In fact I do see a `/remove stale` from an outside party, suggesting there is at least one real-world person experiencing this issue).

Do we have plans to fix this?
