### ISSUE TITLE
stop podman.service: unable to connect to podman socket: dial tcp ECONNREFUSED

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#16277]
Been happening for a while, but [this](https://api.cirrus-ci.com/v1/artifact/task/6125749451620352/html/int-podman-fedora-36-root-container.log.html#t--stop-podman-service--1) is the first time I see it happen without the `fd` flake:
```
stop podman.service
...
Execing /var/tmp/go/src/github.com/containers/podman/bin/podman-remote --url tcp://127.0.0.1:38573 create --tty --name top_XVlBzgba --entrypoint top quay.io/libpod/alpine_labels:latest
         
Listening on 127.0.0.1:38573 as 3.
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.3.0/libpod/_ping": dial tcp 127.0.0.1:38573: connect: connection refused
```
This seems to be a one-off flake: the kind that passes when ginkgo retries. But it seems to have a really odd pattern, a correlation with #15943 (the `fd` flake): nearly every time we see the `fd` flake, we see one of these `stop podman.service` flakes. The difference from the above log excerpt is that when the `fd` flake happens, instead of ECONNREFUSED, the `stop` test flakes with:
```
Error: unexpected fd received from systemd: cannot listen on it
```
The above excerpt and link are the first time I see `stop` flaking without the `fd` flake.

### Systemd activate [It] stop podman.service 
* fedora-36 : int podman fedora-36 root container
  * PR #16238
    * [10-21 09:38](https://api.cirrus-ci.com/v1/artifact/task/6125749451620352/html/int-podman-fedora-36-root-container.log.html#t--stop-podman-service--1)
* fedora-36 : int podman fedora-36 rootless host
  * PR #15753
    * [09-12-2022 17:35](https://api.cirrus-ci.com/v1/artifact/task/5099986789597184/html/int-podman-fedora-36-rootless-host.log.html#t--stop-podman-service--1)
* ubuntu-2204 : int podman ubuntu-2204 rootless host
  * PR #16221
    * [10-18 17:03](https://api.cirrus-ci.com/v1/artifact/task/5882445391200256/html/int-podman-ubuntu-2204-rootless-host.log.html#t--stop-podman-service--1)
  * PR #16219
    * [10-18 11:32](https://api.cirrus-ci.com/v1/artifact/task/5856197304123392/html/int-podman-ubuntu-2204-rootless-host.log.html#t--stop-podman-service--1)
  * PR #16183
    * [10-14 08:52](https://api.cirrus-ci.com/v1/artifact/task/5449597177823232/html/int-podman-ubuntu-2204-rootless-host.log.html#t--stop-podman-service--1)
  * PR #16182
    * [10-14 09:13](https://api.cirrus-ci.com/v1/artifact/task/5010579983695872/html/int-podman-ubuntu-2204-rootless-host.log.html#t--stop-podman-service--1)
  * PR #16165
    * [10-15 08:21](https://api.cirrus-ci.com/v1/artifact/task/6515630206615552/html/int-podman-ubuntu-2204-rootless-host.log.html#t--stop-podman-service--1)
  * PR #16159
    * [10-13 11:39](https://api.cirrus-ci.com/v1/artifact/task/5402266369785856/html/int-podman-ubuntu-2204-rootless-host.log.html#t--stop-podman-service--1)
  * PR #16123
    * [10-12 08:32](https://api.cirrus-ci.com/v1/artifact/task/6174187956994048/html/int-podman-ubuntu-2204-rootless-host.log.html#t--stop-podman-service--1)
  * PR #15994
    * [09-29 09:44](https://api.cirrus-ci.com/v1/artifact/task/5456481188315136/html/int-podman-ubuntu-2204-rootless-host.log.html#t--stop-podman-service--1)
    * [09-29 09:44](https://api.cirrus-ci.com/v1/artifact/task/5456481188315136/html/int-podman-ubuntu-2204-rootless-host.log.html#t--stop-podman-service--2)
    * [09-29 09:44](https://api.cirrus-ci.com/v1/artifact/task/5456481188315136/html/int-podman-ubuntu-2204-rootless-host.log.html#t--stop-podman-service--3)
  * PR #15992
    * [09-29 09:49](https://api.cirrus-ci.com/v1/artifact/task/5015145364586496/html/int-podman-ubuntu-2204-rootless-host.log.html#t--stop-podman-service--1)
    * [09-29 09:01](https://api.cirrus-ci.com/v1/artifact/task/6176700697411584/html/int-podman-ubuntu-2204-rootless-host.log.html#t--stop-podman-service--1)
  * PR #15962
    * [09-27 12:20](https://api.cirrus-ci.com/v1/artifact/task/6091835616526336/html/int-podman-ubuntu-2204-rootless-host.log.html#t--stop-podman-service--1)
  * PR #15907
    * [09-25-2022 22:53](https://api.cirrus-ci.com/v1/artifact/task/5786743352852480/html/int-podman-ubuntu-2204-rootless-host.log.html#t--stop-podman-service--1)
  * PR #15867
    * [10-06 06:00](https://api.cirrus-ci.com/v1/artifact/task/4701632179994624/html/int-podman-ubuntu-2204-rootless-host.log.html#t--stop-podman-service--1)
  * PR #13808
    * [10-12 08:57](https://api.cirrus-ci.com/v1/artifact/task/6512229666258944/html/int-podman-ubuntu-2204-rootless-host.log.html#t--stop-podman-service--1)
    * [09-28 21:46](https://api.cirrus-ci.com/v1/artifact/task/5938777561497600/html/int-podman-ubuntu-2204-rootless-host.log.html#t--stop-podman-service--1)

**Comment by rhatdan** [comment]
Is this the one that @vrothberg was working on?

**Comment by vrothberg** [comment]
@edsantiago are we still seeing this flake?

**Comment by edsantiago** [comment]
No instances since 10-21. Since we no longer test Ubuntu, I'll just close and assume we won't see it again.
