### ISSUE TITLE
using cached config breaks --connection

### ISSUE THREAD

**Issue by cdoern** [containers/podman#16282]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The changes introduced in https://github.com/containers/podman/pull/16238 seem to break --connection, which now when used always results in `Error: failed to resolve active destination: "fedora" service destination not found` due to the blank config that is returned from https://github.com/vrothberg/libpod/blob/7a9c14d6266a0883c8e95d376ffcae71c7e8621e/cmd/podman/registry/config.go#L83 resulting in an empty service destination array

**Steps to reproduce the issue:**

1. podman system connection add

2. podman --connection=name ps

3. error out

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.3.0-dev
API Version:  4.3.0-dev
Go Version:   go1.18.6
Git Commit:   63a8f9aeaacd7ed9aee22d227cc0a68fd9306aba-dirty
Built:        Mon Oct 24 18:55:10 2022
OS/Arch:      linux/amd64
```

**Comment by cdoern** [comment]
I can mock up a fix for this or maybe I am doing something wrong but on my machine this completely breaks any usage of --connection

**Comment by vrothberg** [comment]
Thanks for opening the issue, @cdoern.

The following diff fixes the issue on my machine:
```diff
diff --git a/cmd/podman/root.go b/cmd/podman/root.go                                                                                              
index 7cdc74595ba3..705c1607e077 100644                                                                                                           
--- a/cmd/podman/root.go                                                                                                                          
+++ b/cmd/podman/root.go                                                                                                                          
@@ -176,7 +176,7 @@ func persistentPreRunE(cmd *cobra.Command, args []string) error {                                                             
                                                                                                                                                  
        setupConnection := func() error {                                                                                                         
                var err error                                                                                                                     
-               podmanConfig.URI, podmanConfig.Identity, podmanConfig.MachineMode, err = podmanConfig.ContainersConf.ActiveDestination()          
+               podmanConfig.URI, podmanConfig.Identity, podmanConfig.MachineMode, err = podmanConfig.ContainersConfDefaultsRO.ActiveDestination()
                if err != nil {                                                                                                                   
                        return fmt.Errorf("failed to resolve active destination: %w", err)                                                        
                }                                                                                                                                 
```

@cdoern would you open a PR to fix it along with tests?  CI should have failed IMO.

**Comment by cdoern** [comment]
> Thanks for opening the issue, @cdoern.
> 
> The following diff fixes the issue on my machine:
> ```diff
> diff --git a/cmd/podman/root.go b/cmd/podman/root.go                                                                                              
> index 7cdc74595ba3..705c1607e077 100644                                                                                                           
> --- a/cmd/podman/root.go                                                                                                                          
> +++ b/cmd/podman/root.go                                                                                                                          
> @@ -176,7 +176,7 @@ func persistentPreRunE(cmd *cobra.Command, args []string) error {                                                             
>                                                                                                                                                   
>         setupConnection := func() error {                                                                                                         
>                 var err error                                                                                                                     
> -               podmanConfig.URI, podmanConfig.Identity, podmanConfig.MachineMode, err = podmanConfig.ContainersConf.ActiveDestination()          
> +               podmanConfig.URI, podmanConfig.Identity, podmanConfig.MachineMode, err = podmanConfig.ContainersConfDefaultsRO.ActiveDestination()
>                 if err != nil {                                                                                                                   
>                         return fmt.Errorf("failed to resolve active destination: %w", err)                                                        
>                 }                                                                                                                                 
> ```
> 
> @cdoern would you open a PR to fix it along with tests?  CI should have failed IMO.

Sure will open today!

**Comment by cdoern** [comment]
@vrothberg even with this patch, my --connection is not honored. On my machine running bin/podman-remote --connection=home --log-level=debug info uses my podman machine connection each time... any ideas why this would be happening?

**Comment by vrothberg** [comment]
> @vrothberg even with this patch, my --connection is not honored. On my machine running bin/podman-remote --connection=home --log-level=debug info uses my podman machine connection each time... any ideas why this would be happening?

There's probably another change needed.  Have a look at commit 4e29ce2baf1d287bc136776fa265cc5c10de3260 and connection-related changes. `ContainersConfDefaultsRO` are the default that _must_ be read only.  `ContainersConf` is where we can write values from the CLI to.

**Comment by cdoern** [comment]
I think the issue is config.Default is returning the wrong active service and that is then used in `NewContainerEngine` and `NewConnection`... I am going to look into how to remedy this.
