### ISSUE TITLE
Bash is not reading ~/.bashrc when run as a non-login shell

### ISSUE THREAD

**Issue by debarshiray** [containers/podman#16280]
/kind bug

**Description**

Due to https://github.com/containers/toolbox/issues/1076, I am trying to figure out how `PATH` gets set for processes invoked inside a Podman container.  I cannot understand why invoking `bash` (as a non-login shell) doesn't read the start-up files in `$HOME`, but invoking `bash --login` does.

While it's true that Bash is expected to read a different set of files depending on whether it's a login shell or not, on Fedora, the start-up scripts are set up in a way that `~/.bashrc` and `/etc/bashrc` are always read.

So far, I have seen `DefaultEnvVariables()` in `pkg/env/env.go`, but further investigation is getting hindered by things like `pstree(1)` not being very helpful.

**Steps to reproduce the issue:**

Notice how `bash` doesn't pick up anything from `$HOME`, and has only the defaults from `DefaultEnvVariables()`:
```
$ podman run --interactive --security-opt label=disable --tty --userns=keep-id --volume $HOME:$HOME:rslave fedora:36 bash -c 'echo $PATH'
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

On a recent Fedora, one would expect to see `~/.local/bin` and `~/bin` in `PATH`, because `~/.bashrc` adds them.

However, `bash --login` does pick them up from `$HOME`:
```
$ podman run --interactive --security-opt label=disable --tty --userns=keep-id --volume $HOME:$HOME:rslave fedora:36 bash -l -c 'echo $PATH'
dircolors: no SHELL environment variable, and no shell type option given
/home/rishi/.local/bin:/home/rishi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

I am puzzled because, on Fedora, the start-up scripts are set up in a way that `~/.bashrc` and `/etc/bashrc` are always read, and I am wondering if that message about a missing `SHELL` is related to this.

**Describe the results you expected:**

I expected `bash` (as a non-login shell) to read `~/.bashrc` and pick up `~/.local/bin` and `~/bin` in `PATH`.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.18.5
Built:        Wed Sep  7 21:58:19 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-2.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: '
  cpuUtilization:
    idlePercent: 99.59
    systemPercent: 0.09
    userPercent: 0.32
  cpus: 16
  distribution:
    distribution: fedora
    variant: workstation
    version: "36"
  eventLogger: journald
  hostname: topinka
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.19.14-200.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 10818039808
  memTotal: 33554972672
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.6-2.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.6
      commit: 18cf2efbb8feb2b2f20e316520e0fd0b6c41ef4d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 116h 24m 22.00s (Approximately 4.83 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/rishi/.config/containers/storage.conf
  containerStore:
    number: 29
    paused: 0
    running: 1
    stopped: 28
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/rishi/.local/share/containers/storage
  graphRootAllocated: 1695606808576
  graphRootUsed: 152170045440
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 8
  runRoot: /run/user/1000/containers
  volumePath: /home/rishi/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.1
  Built: 1662580699
  BuiltTime: Wed Sep  7 21:58:19 2022
  GitCommit: ""
  GoVersion: go1.18.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
podman-4.2.1-2.fc36.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

I didn't try a newer version of Podman, but I did go through the Troubleshooting Guide and it didn't have anything regarding this.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I am using Fedora 36 Workstation.

**Comment by Luap99** [comment]
From the bash man page:
>  When an interactive shell that is not a login shell is started, bash reads and executes commands from ~/.bashrc, if that file exists.  This may be inhibited by using the --norc option.  The --rcfile file option will force bash to read and execute  commands  from  file  instead  of
       ~/.bashrc.

Using `-c` means it is not interactive and thus does not read ~/.bashrc. At least this is how I interpret it.

**Comment by debarshiray** [comment]
Yes, you are right, I overlooked this part in the Bash manual:
```
When  bash is started non-interactively, to run a shell script, for example, it looks for the variable BASH_ENV in the environment, expands its value if it appears there, and uses the expanded value as the name of a file to read  and  execute.
```

**Comment by debarshiray** [comment]
> I don't see how this a podman issue?

My apologies, I should have been clearer.  I didn't mean to say that it was definitely a Podman bug.

I was just trying to understand the exact sequence of steps on the way to a process getting invoked inside a container.  From Bash's built-in defaults, to systemd, to GDM, to Podman's built-in defaults and the OCI image's built-in defaults, there seems to be an impressive number of places where `PATH` can get set on a stock graphical Fedora Workstation session.  :)

> Podman starts the process with
> the configured env. If bash decides to read bashrc or not is up to that
> process not podman. I suspect that the problem is that you use `-c`.
> If I just run `bash`, then execute `echo $PATH` it shows the expected path.

Yes, you are right.  It's the `-c` that's the problem.  Toolbx has another layer because it goes through `capsh ... -- -c ...`, and in trying to cut through that I forgot about the `-c`.  Damn, I feel stupid.

Anyway, thanks for clearing it up!
