### ISSUE TITLE
syslog priority not preserved

### ISSUE THREAD

**Issue by virtualized** [containers/podman#16288]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

journald log driver does not persist syslog priority

**Steps to reproduce the issue:**

1. run container with --log-driver=journald producing log output with syslog prio > 3

**Describe the results you received:**

container host journalctl log output is priority=3

**Describe the results you expected:**

priority should be preserved

**Output of `podman version`:**

```
podman version 4.2.1
```

**Comment by Luap99** [comment]
The log driver logs the containers process STDOUT/ERR. So the journald driver has no way of knowing what priority is used. Therefore it assumes 6 (info) for STDOUT and 3 (error) for STDERR.

**Comment by rhatdan** [comment]
Since we had no further response, I am closing. Feel free to carry on the conversation here.
