### ISSUE TITLE
network create test: rootless: bind: address already in use

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#16289]
Seen twice in the last two weeks:
```
not ok 362 podman network create
...
$ podman run -d --network testnet-YQhDKD2ogO -p 127.0.0.1:54322:54322 quay.io/libpod/testimage:20220615 nc -l -n -v -p 54322
Error: rootlessport listen tcp 127.0.0.1:54322: bind: address already in use
```
### [sys] 362 podman network create
* fedora-36 : sys podman fedora-36 rootless host
  * PR #16191
    * [10-24 07:48](https://api.cirrus-ci.com/v1/artifact/task/5021328808869888/html/sys-podman-fedora-36-rootless-host.log.html#t--00362)
* fedora-36 : sys remote fedora-36 rootless host [remote]
  * PR #16188
    * [10-15 06:12](https://api.cirrus-ci.com/v1/artifact/task/6323433507127296/html/sys-remote-fedora-36-rootless-host.log.html#t--00362)

**Comment by Luap99** [comment]
The test using a fixed port but I don't understand why?
https://github.com/containers/podman/blob/589ff20aa3dd68009af5fade3b2b5e1823d4227b/test/system/500-networking.bats#L208-L209
54322 is in the dynamic range, therefore any process with external connections could take it. IMO it has to use $(random_free_port) as well.
The linked issue (https://github.com/containers/podman/issues/10806) has nothing to do with a fixed port, at least I don't understand that reference at all.

**Comment by edsantiago** [comment]
Yeah... I don't get the reference either. I vividly remember wasting a **LOT** of time with this test and with that hang bug, it was in the context of gating, not CI. But I don't remember the connection between the two, and can't figure it out from the discussion. However:

>54322 is in the dynamic range

Not any dynamic range that should be in play during CI. `random_free_port()` defaults to `5000-5999` (5k, not 50k). I can find no tests that override that default with a 50k range. And even if there were, system tests are sequential and clean up after themselves. There should never be collisions.

**Comment by Luap99** [comment]
`cat /proc/sys/net/ipv4/ip_local_port_range` every port inside this range can be taken by any process which will bind port 0, clients usually. That could be anything which creates outgoing tcp connections.
