### ISSUE TITLE
Checkpointing fails when run from container in minikube cluster

### ISSUE THREAD

**Issue by willb7708** [containers/podman#16312]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman checkpoint fails when run from a container in a minikube cluster using crio as the container runtime. I am trying to checkpoint/restore containers that are running in a k8s cluster. To do this, I deploy a container that contains podman (podman added to the ubi8 base image) to the cluster. Then I run the container that I wish to checkpoint from inside this checkpointing container. When I run the checkpoint command 

**Steps to reproduce the issue:**

1. Start a minikube cluster (https://minikube.sigs.k8s.io/docs/start/) with crio container runtime: minikube start --container-runtime=cri-o

2. Deploy checkpointing container with podman to cluster:
kubectl apply -f test.yaml

where test.yaml:
[test.yaml.txt](https://github.com/containers/podman/files/9873506/test.yaml.txt)

4. Start container that I want to checkpoint from inside newly deployed checkpointing container: 

podman run -d registry.k8s.io/echoserver:1.4

5. Checkpoint container:

podman container checkpoint -l -e=test.tar.gz

**Describe the results you received:**
checkpoint fails with:

ERRO[0000] container still running
ERRO[0000] criu failed: type NOTIFY errno 0
log file: /var/lib/containers/storage/overlay-containers/66c9b99687810ac7d43b4b4db5754d8b49255739eaeb0771fd35ed4941ad00fa/userdata/dump.log
Error: `/usr/bin/runc checkpoint --image-path /var/lib/containers/storage/overlay-containers/66c9b99687810ac7d43b4b4db5754d8b49255739eaeb0771fd35ed4941ad00fa/userdata/checkpoint --work-path /var/lib/containers/storage/overlay-containers/66c9b99687810ac7d43b4b4db5754d8b49255739eaeb0771fd35ed4941ad00fa/userdata 66c9b99687810ac7d43b4b4db5754d8b49255739eaeb0771fd35ed4941ad00fa` failed: exit status 1

dump.log from error message here:

[dump.log](https://github.com/containers/podman/files/9873601/dump.log)

**Describe the results you expected:**
Checkpoint file created, able to restore from checkpoint file

**Additional information you deem important (e.g. issue happens only occasionally):**

Checkpointing succeeds if minikube uses docker as the container runtime. 

**Output of `podman version`:**
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.17.7
Built:        Mon Jul 11 14:56:53 2022
OS/Arch:      linux/amd64

**Output of `podman info`:**

host:
  arch: amd64
  buildahVersion: 1.26.2
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.2-2.module+el8.6.0+15917+093ca6f8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.2, commit: 8c4f33ac0dcf558874b453d5027028b18d1502db'
  cpuUtilization:
    idlePercent: 93.26
    systemPercent: 2.75
    userPercent: 3.99
  cpus: 2
  distribution:
    distribution: '"rhel"'
    version: "8.6"
  eventLogger: file
  hostname: checkpointingcontainer-cb5b4988d-kcx86
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-372.9.1.el8.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 330760192
  memTotal: 8342196224
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.3-2.module+el8.6.0+15917+093ca6f8.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.3
      spec: 1.0.2-dev
      go: go1.17.7
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.module+el8.6.0+15917+093ca6f8.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 0
  swapTotal: 0
  uptime: 1709h 14m 26.06s (Approximately 71.21 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 85887791104
  graphRootUsed: 58496413696
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1657551413
  BuiltTime: Mon Jul 11 14:56:53 2022
  GitCommit: ""
  GoVersion: go1.17.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

podman-4.1.1-2.module+el8.6.0+15917+093ca6f8.x86_64

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Luap99** [comment]
Can you test with the latest version v4.3 or try using crun instead of runc?

@adrianreber @rst0git PTAL

**Comment by rhatdan** [comment]
@adrianreber @Luap99 @willb7708 Is this still an issue?

**Comment by willb7708** [comment]
Sorry for the very late response, I am able to successfully checkpoint the container inside the cluster when "--cgroupns=private" to the podman run command, this issue can be closed.

Thanks for the help everyone, big fan of your work
