### ISSUE TITLE
Multiple volume_path options under a single user context

### ISSUE THREAD

**Issue by dnv** [containers/podman#16319]
/kind feature

**Description**

There needs to be a way to specify multiple volume_path options under a single user context.

**Steps to reproduce the issue:**

1. Attach multiple classes of storage (single HDD, RAID10 HDD array, NVME SSD mirror) to Podman host

**Describe the results you received:**

Can point volume_path only towards a single path option at a time.

**Describe the results you expected:**

Need to have a way to have multiple volume_paths in a single user context and the ability to specify which volumes go to what volume_path.

**Additional information you deem important (e.g. issue happens only occasionally):**

A very ugly workaround is to have multiple users running podman with each user having volume_path set to one of the many available storage options. This is less than workable as it's not at all black and white that ALL containers of any particular stack would be best fit a single specific storage option. Often you have a single stack of containers where some volumes really do benefit from fast storage while many others do not.

And obviously this significantly increases administrational overhead.

**Output of `podman version`:**

Client: Podman Engine
Version: 4.1.1
API Version: 4.1.1
Go Version: go1.17.12
Built: Wed Jul 27 17:26:10 2022
OS/Arch: linux/amd64

**Output of `podman info`:**

host:
arch: amd64
buildahVersion: 1.26.2
cgroupControllers:

memory
pids
cgroupManager: systemd
cgroupVersion: v2
conmon:
package: conmon-2.1.2-2.el9_0.x86_64
path: /usr/bin/conmon
version: 'conmon version 2.1.2, commit: 1ed53517f446a779f9d0edafe090ce821a41e255'
cpuUtilization:
idlePercent: 99.87
systemPercent: 0.07
userPercent: 0.06
cpus: 6
distribution:
distribution: '"rhel"'
version: "9.0"
eventLogger: journald
hostname: sigma
idMappings:
gidmap:
container_id: 0
host_id: 1000
size: 1
container_id: 1
host_id: 100000
size: 65536
uidmap:
container_id: 0
host_id: 1000
size: 1
container_id: 1
host_id: 100000
size: 65536
kernel: 5.14.0-70.26.1.el9_0.x86_64
linkmode: dynamic
logDriver: journald
memFree: 15521632256
memTotal: 16549978112
networkBackend: netavark
ociRuntime:
name: crun
package: crun-1.4.5-2.el9_0.x86_64
path: /usr/bin/crun
version: |-
crun version 1.4.5
commit: c381048530aa750495cf502ddb7181f2ded5b400
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
os: linux
remoteSocket:
exists: true
path: /run/user/1000/podman/podman.sock
security:
apparmorEnabled: false
capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
rootless: true
seccompEnabled: true
seccompProfilePath: /usr/share/containers/seccomp.json
selinuxEnabled: true
serviceIsRemote: false
slirp4netns:
executable: /usr/bin/slirp4netns
package: slirp4netns-1.2.0-2.el9_0.x86_64
version: |-
slirp4netns version 1.2.0
commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
libslirp: 4.4.0
SLIRP_CONFIG_VERSION_MAX: 3
libseccomp: 2.5.2
swapFree: 8589930496
swapTotal: 8589930496
uptime: 13h 34m 51.71s (Approximately 0.54 days)
plugins:
log:
k8s-file
none
passthrough
journald
network:
bridge
macvlan
volume:
local
registries:
search:
registry.access.redhat.com
registry.redhat.io
docker.io
store:
configFile: /home/ladm-dnaumov/.config/containers/storage.conf
containerStore:
number: 5
paused: 0
running: 1
stopped: 4
graphDriverName: overlay
graphOptions: {}
graphRoot: /home/ladm-dnaumov/.local/share/containers/storage
graphRootAllocated: 68685922304
graphRootUsed: 3970174976
graphStatus:
Backing Filesystem: xfs
Native Overlay Diff: "true"
Supports d_type: "true"
Using metacopy: "false"
imageCopyTmpDir: /var/tmp
imageStore:
number: 2
runRoot: /run/user/1000/containers
volumePath: /home/ladm-dnaumov/.local/share/containers/storage/volumes
version:
APIVersion: 4.1.1
Built: 1658931970
BuiltTime: Wed Jul 27 17:26:10 2022
GitCommit: ""
GoVersion: go1.17.12
Os: linux
OsArch: linux/amd64
Version: 4.1.1

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

podman-4.1.1-1.el9_0.x86_64

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Comment by Luap99** [comment]
Can you just use regular bind mounts instead, `-v /path/on/host:/path/in/container`?

**Comment by dnv** [comment]
> Can you just use regular bind mounts instead, `-v /path/on/host:/path/in/container`?

Yes, bind mounts work, but bind mounts are not volumes.

**Comment by Luap99** [comment]
Depends on what you are doing, `podman volume create`  without specific mount options will result in a normal bind mount under the volume path.

**Comment by rhatdan** [comment]
I really do not know what you are after here @dnv 
Could you give us a podman example of what you want?

**Comment by rhatdan** [comment]
Since we never heard back, closing, Reopen if you have more feedback.
