### ISSUE TITLE
podman-remote-static v4.3.0 doesn't run on Linux x86_64 and looks to be built for aarch64

### ISSUE THREAD

**Issue by Nemric** [containers/podman#16310]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Running podman-remote-static on a Linux X86_64 Linux machine result in a `bash: ./podman-remote-static: cannot execute binary file: Exec format error`

```
$ file podman-remote-static 
podman-remote-static: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=N-2_yxnVICqrSlgeZ3iI/hDQtpQ8fypd4E5AF61KS/5l9_eCOJ-VQb581DYAhB/bc1mqycsMbu5W8kLcObN, not stripped
```

**Steps to reproduce the issue:**

1. `curl -LO https://github.com/containers/podman/releases/latest/download/podman-remote-static.tar.gz`
   
3.  `tar -xvf podman-remote-static.tar.gz && chmod +x podman-remote-static`

4. `./podman-remote-static`

**Comment by Luap99** [comment]
@mheon PTAL

**Comment by mheon** [comment]
This seems like the inverse of the issue we had a while back, where OS X binaries were coming out as Linux? I'll take a look, but it's probably another makefile problem

**Comment by Nemric** [comment]
I remember an old issue (for 4.0.2 in my memory) where remote was built for windows ...

**Comment by Nemric** [comment]
Did you do something @mheon ? It looks to be ok for 4.3.1, remote-static is ok
Do you think I can rely on it in the future ?

**Comment by mheon** [comment]
We have not actually fixed the problem with the makefile (I suspect that if you run multiple targets at once, they pollute `podman-remote-static` with the architecture and OS of the last release target to run before it). However, I suspect @ashley-cui just ran the release targets individually when making the release, which avoided the problem, and we can continue to do that until a proper solution is written.

**Comment by ashley-cui** [comment]
Yep, ran that one separately.

**Comment by rhatdan** [comment]
fe548dd0b053389829bbd385c64cd580fb378ae4
