### ISSUE TITLE
Issues running podman on Jenkins agent running RHEL OS

### ISSUE THREAD

**Issue by amberjungminlee** [containers/podman#16325]
Hello. We are running a Jenkins agent that is using RHEL 8 and running podman (instead of docker), and we noticed an issue where on the command line, commands such as podman pull node and ```podman image build app --no-cache``` works fine. However, when we run the same exact command through a Jenkins pipeline, we get the following error:
```
Error: error creating build container: error preparing image configuration: error reading image configuration for "containers-storage:[overlay@/var/lib/jenkins/.local/share/containers/storage+/run/user/101/containers:overlay.ignore_chown_errors=true]@ac3dcfe39c7e20f85479935fc56f7b59ce270289fac6de229a3e48bf697e0438": open ~/20287918: no such file or directory
```
We were trying to dig for resources online regarding this specific error, but we couldn't find anything. Is there a way to fix this? Thank you!

**Comment by Luap99** [comment]
Please fill out the issue template. We need to know at least `podman info` for most things.
Also if you a RHEL customer please use the Red Hat support channels instead.

**Comment by rhatdan** [comment]
Since we never heard any feedback, I am closing.  Reopen if you still want us to look at it.

**Comment by amberjungminlee** [comment]
Hello. Yes. I would still like for this issue to be looked at. Here is the output for podman info:

host:
  arch: amd64
  buildahVersion: 1.26.2
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.2-2.module+el8.6.0+15917+093ca6f8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.2, commit: 8c4f33ac0dcf558874b453d5027028b18d1502db'
  cpuUtilization:
    idlePercent: 99.92
    systemPercent: 0.02
    userPercent: 0.07
  cpus: 8
  distribution:
    distribution: '"rhel"'
    version: "8.6"
  eventLogger: file
  hostname: pod1-local
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 100
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 230017193
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-372.26.1.el8_6.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 1584070656
  memTotal: 16490471424
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.3-2.module+el8.6.0+15917+093ca6f8.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.3
      spec: 1.0.2-dev
      go: go1.17.7
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /run/user/230017193/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.module+el8.6.0+15917+093ca6f8.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 10485481472
  swapTotal: 10485755904
  uptime: 508h 39m 17.16s (Approximately 21.17 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  registry1.gesdisc.eosdis.nasa.gov:
    Blocked: false
    Insecure: true
    Location: registry1.gesdisc.eosdis.nasa.gov
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: registry1.gesdisc.eosdis.nasa.gov
    PullFromMirror: ""
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/ajlee8/.config/containers/storage.conf
  containerStore:
    number: 8
    paused: 0
    running: 4
    stopped: 4
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/ajlee8/.local/share/containers/storage
  graphRootAllocated: 102673489920
  graphRootUsed: 11524186112
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 14
  runRoot: /run/user/230017193/containers
  volumePath: /home/ajlee8/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1657551413
  BuiltTime: Mon Jul 11 14:56:53 2022
  GitCommit: ""
  GoVersion: go1.17.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1

**Comment by rhatdan** [comment]
Are you running rootful or rootless?

If rootless did you set the user up as enable-linger?

**Comment by Luap99** [comment]
We should not support RHEL issues upstream unless you you use the latest upstream version.
Please go through the Red Hat support channels, e.g. file a bug against podman on https://bugzilla.redhat.com
Also we need a reproducer, otherwise we can only guess which rarely works.
