### ISSUE TITLE
Podman under windows shows different versions as in the machine

### ISSUE THREAD

**Issue by harryssuperman** [containers/podman#16330]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
/kind bug

**Description**
Versions from machine and out the podman machine under Windows are different.

**Steps to reproduce the issue:**
1. Install Podman from last Version (Current 4.3.0) for Windows.
2. Run podman machine ssh 
3. Inside the machine run podman --version
4. Go outside the machine to windows shell or another shell and run podman --version 

**Describe the results you received:**
The 2 Versions are different

**Describe the results you expected:**
The 2 Versions should be the same

**Output of `podman version`:**
podman version 4.2.1
podman.exe version 4.3.0

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Comment by Luap99** [comment]
I think this is expected, the VM OS is fedora so it will only be updated when podman v4.3 lands there.
@n1hility PTAL

**Comment by TheComputerM** [comment]
Duplicate: https://github.com/containers/podman/issues/15876

**Comment by afbjorklund** [comment]
If you run the regular `podman version` command, it will be more obvious that there is a client and a server

**Comment by n1hility** [comment]
That’s correct for Mac and Windows  it’s expected that the client will temporarily drift ahead of the server until the podman package updates show up. You can still use it during this skew but it does mean that fixes / improvements on the server portion won’t show until the Fedora updates are complete. See my comment on #15876 for the upgrade procedure.
