### ISSUE TITLE
Default detach key sequence wrecks standard shell usage.

### ISSUE THREAD

**Issue by srbaker** [containers/podman#16345]
/kind bug

**Description**

The default key sequence for detaching from `podman run` is Ctrl-p,Ctrl-q.

This means that Ctrl-p when used in a shell for "previous command" does not work.  This is standard shell behaviour, and since using `podman run` to start a shell is a common usage, it's very confusing.

**Steps to reproduce the issue:**

1. `podman run -it bash <container>`

2. `ls`

3. `echo foo`

3. Press Ctrl-p

4. Press Ctrl-p a second time.

**Describe the results you received:**

Nothing happens, because it's waiting for something after the Ctrl-p.  Pressing Ctrl-p a second time yields `ls`.

**Describe the results you expected:**

I expect Ctrl-p to give me the previous command I typed in, in the example above `echo foo`.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 4.2.1
```

**Comment by mheon** [comment]
The original sequence is used for Docker compatibility. We will not be changing it.

If you wish to set a new default, you can do so in containers.conf via the `detach_keys` field.
