### ISSUE TITLE
allow for user provided configuration to be included in containers.conf and registries.conf for podman machine

### ISSUE THREAD

**Issue by viecili** [containers/podman#16364]
** BUG REPORT or FEATURE**

/kind feature

**Description**

When creating a new podman machine (podman machine init) with defaults the contents of configuration files are hardcoded from pkg/machine/ignition.go , specifically lines [442](https://github.com/containers/podman/blob/main/pkg/machine/ignition.go#L442 ) and [303](https://github.com/containers/podman/blob/main/pkg/machine/ignition.go#L303)

This is a request to allow for user data to be provided (rather than a complete custom crafted ignition file) when initialising a podman machine. Perhaps have the Go script [ignition.go](https://github.com/containers/podman/blob/main/pkg/machine/ignition.go) to read contents from local files or templates.

See StackOverflow for real life issue description: https://stackoverflow.com/questions/72832064/podman-only-search-in-docker-io/74270998

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
❯ podman version
Client:       Podman Engine
Version:      4.3.0
API Version:  4.3.0
Go Version:   go1.18.7
Built:        Wed Oct 19 04:55:57 2022
OS/Arch:      darwin/amd64

Server:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.18.5
Built:        Thu Sep  8 05:58:19 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
❯ podman info
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-3.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: '
  cpuUtilization:
    idlePercent: 99.51
    systemPercent: 0.31
    userPercent: 0.18
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "36"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 5.19.15-201.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1666052096
  memTotal: 2066890752
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.6-2.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.6
      commit: 18cf2efbb8feb2b2f20e316520e0fd0b6c41ef4d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/501/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 27m 24.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - quay.io
  - registry.access.redhat.com
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106825756672
  graphRootUsed: 2294214656
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/501/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.1
  Built: 1662580699
  BuiltTime: Thu Sep  8 05:58:19 2022
  GitCommit: ""
  GoVersion: go1.18.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
❯ brew info podman
==> podman: stable 4.3.0 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/usr/local/Cellar/podman/4.3.0 (185 files, 48MB) *
  Poured from bottle on 2022-10-25 at 15:08:24
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0 and GPL-3.0-or-later
==> Dependencies
Build: go-md2man ✘, go@1.18 ✘
Required: qemu ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /usr/local/share/zsh/site-functions

To restart podman after an upgrade:
  brew services restart podman
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/podman/bin/podman system service --time=0
==> Analytics
install: 25,458 (30 days), 73,758 (90 days), 221,083 (365 days)
install-on-request: 24,378 (30 days), 71,317 (90 days), 218,193 (365 days)
build-error: 10 (30 days)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
Thanks for reaching out @viecili!

Apologies for the delayed reply.

Users can change these settings by configuring the VMs once created.  I am a bit reluctant to special-case the config files, so I am looking to generalize the request a bit.

Would a `--mount` option work that would mount specified files/directories to a specified path?  Similar to `podman run --mount...`?  I think that `podman machine init --volume` mounts directory only.

@containers/podman-maintainers PTAL

**Comment by viecili** [comment]
that could work @vrothberg !

for some of these files it may also be necessary to enable overriding/setting environment variables in the VM, e.g. 

`podman machine init -v $CONT_CONF_LOCAL:$CONT_CONF_TGT -e CONTAINERS_CONF=$CONT_CONF_TGT/containers.conf`

what do you think?

**Comment by vrothberg** [comment]
@ashley-cui @rhatdan @baude @mheon PTAL

**Comment by Luap99** [comment]
You should not use CONTAINERS_CONF to overwrite the config. This will cause podman to only use this single config file and thus will not use the correct settings that are set by `podman machine` in `/etc/containers.containers.conf` unless you copy all settings manually into your config.

**Comment by rhatdan** [comment]
You could drop the customer config into a containers.conf.d directory.

**Comment by rhatdan** [comment]
Since we suggested fixes and have not heard any further comment, I am closing.  Reopen if I am mistaken of continue the conversation here.
