### ISSUE TITLE
Build documentation is out of date; `make install.tools` tries to install to read-only directory

### ISSUE THREAD

**Issue by phlummox** [containers/podman#16363]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

A step in the current build instructions from `CONTRIBUTING.md` fails.

**Steps to reproduce the issue:**

  
1. Follow the instructions in [CONTRIBUTING.md](https://github.com/containers/podman/blob/a30c9ef752d956f884b13a4132cb2081dc7072b3/CONTRIBUTING.md), up to "[Install tools](https://github.com/containers/podman/blob/a30c9ef752d956f884b13a4132cb2081dc7072b3/CONTRIBUTING.md?plain=1#L84)"

   https://github.com/containers/podman/blob/a30c9ef752d956f884b13a4132cb2081dc7072b3/CONTRIBUTING.md?plain=1#L82-L87

3. Run `make install.tools`, as suggested by `CONTRIBUTING.md`.

**Describe the results you received:**

Installation fails, because the [`hack/install_swagger.sh`](https://github.com/containers/podman/blob/bb2b47dc70776eeda8d41395a64644c41027d7e4/hack/install_swagger.sh) script tries to write to `/usr/local/bin/swagger`:

```
go install  ./vendor/github.com/onsi/ginkgo/ginkgo
VERSION=1.49.0 ./hack/install_golangci.sh
golangci-lint has version 1.49.0 built from cc2d97f3 on 2022-08-24T10:24:37Z
Using existing ./bin/golangci-lint has version 1.49.0 built from cc2d97f3 on 2022-08-24T10:24:37Z
env VERSION=0.30.3 \
	BINDIR=/usr/local/bin \
	GOOS=linux \
	GOARCH=amd64 \
	./hack/install_swagger.sh
Installing swagger v0.30.3 into /usr/local/bin/swagger
curl: (23) Failed writing body (0 != 1369)
chmod: cannot access '/usr/local/bin/swagger': No such file or directory
./hack/install_swagger.sh: line 15: /usr/local/bin/swagger: No such file or directory
make: *** [Makefile:892: .install.swagger] Error 127
```

**Describe the results you expected:**

Tools should install successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

Either the CONTRIBUTING.md file needs to be updated, stating that `make install.tools` must be run as root, or (better) the Makefile should be fixed to not do this, or (better still) the swagger install directory should be configurable, should default to a path within the repository, and this should be documented in `CONTRIBUTING.md`. It's fairly rude behaviour for a Makefile to try to write to someone's `/usr/local/bin`.

Why not install instead to the `bin` directory within the repo, which is where `golangci-lint` gets installed?

It's already possible to do this by running

```
$ make BINDIR=./bin install.tools
```

But then the user has to remember to supply the same BINDIR when running `make swagger` as well.

&nbsp;

(Also, btw: due to the way your "make help" function is written, "binaries" currently shows up twice:

```
  Target:                     Description:
  --------------              --------------------
  binaries                    Build podman and podman-remote binaries
  binaries                    Build podman, podman-remote and rootlessport binaries quadlet
```

Due to the fact that the `binaries` target is within an `ifeq ... endif`, and does syntactically appear twice.)

&nbsp;

**Output of `podman version`:**

N/A

**Output of `podman info`:**

N/A

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

N/A

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Build environment: Ubuntu 20.04.4, running kernel 5.4.0-122-generic on x86-64.

**Comment by rhatdan** [comment]
I believe this has been fixed, closing.
