### ISSUE TITLE
podman systemd clutters /run with .ctr-id files

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#16387]
podman systemd commands do not clean up leftover `.ctr-id` files:
```console
# bats --filter basic  test/system/250-systemd.bats
[passes]

# ls -l /run
...
-rw-r--r--.  1 root   root     64 Nov  2 12:36 podman_test_HvKVwQfIFo.service.ctr-id
```
After multiple runs of system tests, `/run` is full of these files. Yes, of course these are tests, not representative, but even in the real world people will be creating and removing differently-named containers and may not want these confusing stale files left behind.

Probably a simple fix, adding to one of the `ExecStop` stanzas.

**Comment by vrothberg** [comment]
I'll take a look. Thanks, @edsantiago !

**Comment by vrothberg** [comment]
I opened https://github.com/containers/podman/pull/16394.
