### ISSUE TITLE
podman-remote wait: fails with read /proc/N/cgroup: no such process

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#16383]
Seen just now in [remote f36-aarch64 root](https://api.cirrus-ci.com/v1/artifact/task/4878370822422528/html/sys-remote-fedora-36-aarch64-root-host.log.html). Almost certainly a flake:
```
[+0098s] not ok 53 podman --noout run should print output
...
# podman-remote --noout run -d --name test quay.io/libpod/testimage:20221018 echo hi
# podman-remote wait test
Error: read /proc/14628/cgroup: no such process
[ rc=125 (** EXPECTED 0 **) ]
```
My flake logs find one other instance, [September 14 in f36 rootless](https://api.cirrus-ci.com/v1/artifact/task/5532259007594496/html/sys-remote-fedora-36-rootless-host.log.html#t--00175), but that one is preceded by other errors. This one, no prior indications of failure.

**Comment by edsantiago** [comment]
Another one, also remote, but f37 this time instead of f36

* fedora-37-aarch64 : sys remote fedora-37-aarch64 root host [remote]
  * PR #16471
    * [11-10 04:49](https://api.cirrus-ci.com/v1/artifact/task/5804240277864448/html/sys-remote-fedora-37-aarch64-root-host.log.html#t--00054)

**Comment by vrothberg** [comment]
@giuseppe, any idea what could cause it?

**Comment by giuseppe** [comment]
it is a race when reading the process cgroup using `os.ReadFile()`.

What happens is that the process terminates between the open("/proc/$PID/cgroup") succeded and the following read.

It can be easily reproduced with:

```
$ sleep 1 & (sleep 2; cat -) < /proc/$!/cgroup 
[1] 1083377
cat: -: No such process
```

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/podman/pull/16504
