### ISSUE TITLE
Discussion: Podman Inside Kubernetes - networking issues (unprivileged)

### ISSUE THREAD

**Issue by lalbers** [containers/podman#16405]
### Podman Inside Kubernetes - Networking Issues

As mentioned in the following article, it is possible to run podman inside Kubernetes. 
https://podman.io/blogs/2021/07/01/podman-inside-kubernets.html

There are different variants described, currently I am trying to run podman on a non-privileged pod (_Rootful Podman without the privileged flag_). 

Basically, this works very well. The pod can even reach the internet:
```
# from inside the k8s pod container
>> podman run --rm quay.io/fedora/fedora:38 cat /etc/fedora-release
Fedora release 38 (Rawhide)
```

However, when i try to specify a network it does not work anymore:
```
>> podman run --rm --net default quay.io/fedora/fedora:38 cat /etc/fedora-release
Error: netavark: IO error: failed to configure bridge and veth interface: failed while configuring network interface: failed to create a bridge interface podman0: Received a netlink error message Operation not permitted (os error 1)
```

Similar results with slirp4netns:
```
>> podman run --rm --net slirp4netns quay.io/fedora/fedora:38 cat /etc/fedora-release
WARN[0000] failed to set net.ipv6.conf.default.accept_dad sysctl: open /proc/sys/net/ipv6/conf/default/accept_dad: read-only file system 
Error: /usr/bin/slirp4netns failed: "open(\"/dev/net/tun\"): No such file or directory\nWARNING: Support for seccomp is experimental\nWARNING: Support for IPv6 is experimental\nchild failed(1)\nWARNING: Support for seccomp is experimental\nWARNING: Support for IPv6 is experimental\n"
```

Tested with: 
podman version 4.2.1

**Comment by rhatdan** [comment]
This is a discussion not an issue ...
Podman requires either privileges CAP_NET_ADMIN or perhaps more to setup a network,  With slirp4netns, you probably need to leak the /dev/net/tun into the container.

**Comment by lalbers** [comment]
Thanks @rhatdan, i also added net `NET_ADMIN `. That definitely helped.
```
securityContext:
       capabilities:
         add:
           - "SYS_ADMIN"
           - "MKNOD"
           - "SYS_CHROOT"
           - "SETFCAP"
           - "NET_ADMIN"
 ```

However, there seems to be another problem. If I find out more, I will post it here
```
podman run --rm --net default quay.io/fedora/fedora:38 cat /etc/fedora-release
Error: OCI runtime error: crun: open /proc/sys/net/ipv4/ping_group_range: Read-only file system
```

**Comment by Luap99** [comment]
If /proc is mounted read only in your container podman/netavark cannot set sysctl values. The `ping_group_range` one can be commented out in containers.conf AFAIK.

**Comment by rhatdan** [comment]
Nice

**Comment by lalbers** [comment]
I'll close this issue, since it is working with this workaround. Should I notice further implications, I'll reopen this again.

**Comment by Luap99** [comment]
FYI I think this was fixed in https://github.com/containers/podman/pull/16209 so it should not be needed to manually set it in future versions.

The problem with that is that the `ping` command may not work in your container.
