### ISSUE TITLE
podman generate systemd --restart-sec is not honored by containers

### ISSUE THREAD

**Issue by nivekuil** [containers/podman#16419]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`podman generate systemd --restart-sec pod` only generates `RestartSec=` in the pod service, not the container service. This basically renders it ineffective since the containers are the ones likely to be restarting.

**Steps to reproduce the issue:**

1. `podman generate systemd --restart-sec 3 my-pod` and inspect the service file of its container 

**Describe the results you received:**
```
[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=always
TimeoutStopSec=90
ExecStart=/usr/bin/podman start my-ctr
ExecStop=/usr/bin/podman stop -t 30 my-ctr
ExecStopPost=/usr/bin/podman stop -t 30 my-ctr
PIDFile=/run/containers/storage/overlay-containers/4b6f4efab716b240ea1f6e65d4f672cb83ec426713fc651f34970eafc0a91e4c/userdata/conmon.pid
Type=forking
```

**Describe the results you expected:**
Should have `RestartSec=` in there

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.19
Built:        Wed Sep  7 19:57:53 2022
OS/Arch:      linux/amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
Thanks for reaching out, @nivekuil !

**Comment by Darth-Mera** [comment]
Hi, I'd like to try to take on this one as a first issue, if that's ok :)

**Comment by rhatdan** [comment]
Fine with me.

**Comment by aadi58002** [comment]
Can i also try to work on this issue?

**Comment by vrothberg** [comment]
@Darth-Mera asked first, so I'd very much prefer to keep this order.  Please respect that @aadi58002 before opening a PR next time. It's not race.

**Comment by Darth-Mera** [comment]
I pushed my attempt at solving this issue. Not a fan of duplicating work, but I guess we're both learning.

**Comment by aadi58002** [comment]
> I pushed my attempt at solving this issue. Not a fan of duplicating work, but I guess we're both learning.

It was a leaning experience for me as well. I also looked at your PR which is much better and more better done than mine thanks for providing a good experience and learning.

**Comment by rhatdan** [comment]
Thanks to both of you.  Nice thing is there are plenty more "good first issues" to work on.
Again thanks for contributing.

**Comment by rhatdan** [comment]
https://github.com/containers/podman/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22
