### ISSUE TITLE
podman machine init fails on M1 with Ventura update

### ISSUE THREAD

**Issue by marcosstefani** [containers/podman#16427]
**Is this a  or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I can't boot podman after I updated the OS to Ventura on M1.

**Steps to reproduce the issue:**

1. Run brew install podman && podman machine init

**Describe the results you received:**
```
$ podman machine init
Error: podman-machine-default: VM already exists
```

**Subsequent call results in:**
```
$ podman machine start
Starting machine "podman-machine-default"
Error: dial unix /var/folders/_p/h1g79x650q7b325c6hqrxvhh0000gn/T/podman/qmp_podman-machine-default.sock: connect: no such file or directory
```

**Describe the results you expected:**
Having running usable podman VM on Apple Silicon.

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Output of `podman version`:**
```
$ podman version
Error: failed to connect: dial tcp [::1]:51512: connect: connection refused
```

**Output of `podman info`:**
```
$ podman info
Error: failed to connect: dial tcp [::1]:51512: connect: connection refused
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**
```
Tool for managing OCI containers and pods
https://podman.io/
/opt/homebrew/Cellar/podman/4.3.0 (185 files, 47.6MB) *
  Poured from bottle on 2022-11-07 at 08:45:20
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0 and GPL-3.0-or-later
==> Dependencies
Build: go-md2man ✘, go@1.18 ✘
Required: qemu ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions

To restart podman after an upgrade:
  brew services restart podman
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/podman/bin/podman system service --time=0
==> Analytics
install: 26,761 (30 days), 76,262 (90 days), 224,129 (365 days)
install-on-request: 25,612 (30 days), 73,637 (90 days), 221,032 (365 days)
build-error: 19 (30 days)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**
Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
N/A

<img width="281" alt="Screenshot 2022-11-07 at 09 09 36" src="https://user-images.githubusercontent.com/16294901/200271558-181cf663-0765-478f-b09e-ac76bd424873.png">

**Comment by mheon** [comment]
@ashley-cui PTAL

**Comment by ashley-cui** [comment]
Looks like you have an existing machine from a previous install. If you are not particularly attached to your current machine, try podman machine rm and re-creating your podman machine.

**Comment by rhatdan** [comment]
It looks like you r connection data is wrong or the socket is not listening

**Comment by marcosstefani** [comment]
I ended up giving up on the tool :(

**Comment by rhatdan** [comment]
Sorry to hear it, would love to have you try us a again at some point, along with pdoman-desktop.
