### ISSUE TITLE
rerun_cirrus_cron workflow always fails

### ISSUE THREAD

**Issue by ygalblum** [containers/podman#16426]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The GitHub action retrun_cirros_cron always fails because it is misconfigured. The third step contains both `run` and `uses` which according to the error message is not allowed.

See [this](https://github.com/containers/podman/actions/runs/3408369275) as an example

**Comment by mheon** [comment]
@cevich PTAL
