### ISSUE TITLE
after podman tag , i go an image prefix with localhost.

### ISSUE THREAD

**Issue by mahmut-Abi** [containers/podman#16428]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

when i run `podman tag docker.io/library/registry:latest registry:latest` then i got `localhost/registry:latest`
i am trying to remove the `localhost`, but i can`t.
so, can anyone can help me, how to remove the prefix `localhost`
podman = docker? or podman != docker?
**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.2.3
API Version:  3.2.3
Go Version:   go1.17.10
Built:        Fri Sep  2 12:00:44 2022
OS/Arch:      linux/amd64

```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.21.3
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.module+uelc20+684+69e2632d.02.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 64853bf5aade25a3759e909cfca545eab1dc131b'
  cpus: 2
....
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
Thanks for reaching out @mahmut-Abi.

> when i run podman tag docker.io/library/registry:latest registry:latest then i got localhost/registry:latest
i am trying to remove the localhost, but i cant. so, can anyone can help me, how to remove the prefix localhost`
podman = docker? or podman != docker?

Image short names (i.e., those without a domain etc.) are treated differently in Podman.  The following article goes into some of the details: https://www.redhat.com/sysadmin/container-image-short-names

In your specific case: Podman prefixes images with "localhost/" if the tag is a short name. So `podman tag $image foo` will actually tag the image as `localhost/foo`. If you run `podman tag $image bar.com/foo` it will be tagged exactly as such.

Is the behavior causing issue on your end?

**Comment by mahmut-Abi** [comment]
i found the same issue containers/podman [#1034](https://github.com/containers/buildah/issues/1034)

**Comment by robrich** [comment]
Just got bit by this too. How does this pain me? Kind doesn't assume that `localhost/myimage:v0.1` and `myimage:v0.1` are the same. So now I need to modify all my k8s yaml files to add the `localhost/` prefix because I can't get Podman to remove it.
