### ISSUE TITLE
podman api cause conmon defunct leak

### ISSUE THREAD

**Issue by DanStory** [containers/podman#16431]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
We are using podman-in-docker as a task runner and found that we can easily exhaust our `pid_max` on the host as containers and exec sessions are cycled through their [short] life. Further investigation highlights that the `conmon` (and `fuse-overlayfs`*) processes are not cleaning up properly from container start and exec sessions (after 5min delay) and instead go into a `defunct` state.

This was successfully reproduced (for the sake of `conmon` leak) with the below script using either 3.4.1 or 4.2.1 podman images.

**Steps to reproduce the issue:**

*(excuse my rudimentary bash script, it isn't my forte)*
```bash
#!/usr/bin/env bash

# [re]start podman-in-docker API
docker stop podman 2>> /dev//null

echo "starting podman api"
docker run --privileged -d --rm --name podman -p 2375:2375 quay.io/containers/podman:v4.2.1 podman --log-level info system service tcp:0.0.0.0:2375 -t=0

# wait for podman API to start
echo ""
until curl --output /dev/null --silent --head --fail http://localhost:2375/libpod/_ping; do
    echo -e '\e[1A\e[K'
    echo -n "waiting for podman api"
    sleep 1
done
echo ""

# spin up 5 containers and a exec session for each
for ((i=0;i<5;i++))
do
  container=$(docker --host=localhost:2375 run -d --rm busybox sleep 30)
  docker --host=localhost:2375 exec -d "${container}" sleep 3
done

start="$(date +%s)"
time=0
count=$(($(ps -A | pgrep conmon | wc -l)))

# wait up to 6 minutes for conmon processes count to report zero
echo "conmon: ${count};"
while [ $count -gt 0 ] && [ $time -lt 360 ];
do
  time="$(($(date +%s)-start))"
  echo -e '\e[1A\e[K'

  count=$(($(ps -A | pgrep conmon | wc -l)))
  echo -n "conmon: ${count}; ${time} seconds"
done
echo ""
```

**Describe the results you received:**
`conmon` processes in defunct state after exec sessions end and/or containers themselves stopped/removed, eventually exhausting pids and causing downstream errors in podman and across the host.
from a local (WSLv2) run:
```bash
$ ./conmon-leak.sh
podman
62815be4ed8d72961df9ca97989108ac5e93bdd1853db0577f84e37b7bd1c957

waiting for podman api
Unable to find image 'busybox:latest' locally
22b70bddd3ac: Pulling fs layer
22b70bddd3ac: Download complete
bc01a3326866: Pulling fs layer
bc01a3326866: Download complete
bc01a3326866: Download complete

conmon: 10; 360 seconds

$ ps -A | grep conmon                                                                                                                                                                                             
3478883 ?        00:00:00 conmon <defunct>
3478899 ?        00:00:00 conmon <defunct>
3479082 ?        00:00:00 conmon <defunct>
3479099 ?        00:00:00 conmon <defunct>
3479289 ?        00:00:00 conmon <defunct>
3479306 ?        00:00:00 conmon <defunct>
3479495 ?        00:00:00 conmon <defunct>
3479512 ?        00:00:00 conmon <defunct>
3479698 ?        00:00:00 conmon <defunct>
3479714 ?        00:00:00 conmon <defunct>
```
\* Additionally, in our production (AWS EKS (k8s)) and VSphere CentOS deployments, multiple `fuse-overlayfs` process were in a defunct state as well, see attached [conmon-overlayfs_defunct.txt](https://github.com/containers/podman/files/9952224/conmon-overlayfs_defunct.txt) to get a captured state of our AWS EKS in this instance.

**Describe the results you expected:**
dependent child processes are cleaned up after given exec session (5min) delay and containers ended

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
```bash
$ docker run --privileged --rm  quay.io/containers/podman:v3.4.1 podman version
Version:      3.4.1
API Version:  3.4.1
Go Version:   go1.16.8
Built:        Wed Oct 20 14:31:56 2021
OS/Arch:      linux/amd64
```

```bash
$ docker run --privileged --rm  quay.io/containers/podman:v4.2.1 podman version
Client:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.18.5
Built:        Wed Sep  7 19:58:19 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
$ docker run --privileged --rm  quay.io/containers/podman:v4.2.1 podman info
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.4-3.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: '
  cpuUtilization:
    idlePercent: 99.88
    systemPercent: 0.04
    userPercent: 0.08
  cpus: 24
  distribution:
    distribution: fedora
    variant: container
    version: "36"
  eventLogger: file
  hostname: 41cc245845d2
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.68.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 44836159488
  memTotal: 67429199872
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.6-2.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.6
      commit: 18cf2efbb8feb2b2f20e316520e0fd0b6c41ef4d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 4294967296
  swapTotal: 4294967296
  uptime: 147h 41m 17.00s (Approximately 6.12 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /var/lib/shared
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.9-6.fc36.x86_64
      Version: |-
        fusermount3 version: 3.10.5
        fuse-overlayfs: version 1.9
        FUSE library version 3.10.5
        using FUSE kernel interface version 7.31
    overlay.mountopt: nodev,fsync=0
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 269427478528
  graphRootUsed: 72628584448
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.2.1
  Built: 1662580699
  BuiltTime: Wed Sep  7 19:58:19 2022
  GitCommit: ""
  GoVersion: go1.18.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```bash
$ docker run --privileged --rm  quay.io/containers/podman:v4.2.1 rpm -q podman
podman-4.2.1-2.fc36.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS EKS (k8s), VSphere CentOS VM and WSLv2

**Comment by mheon** [comment]
This is not a leak. See #15377. Closing as a dupe.

If you are actually running out of PIDs, you can adjust the 5 minute timer via the `exit_command_delay` field in containers.conf; lowering to 5 to 10 seconds will probably resolve your issue (depending on how slow your environment is; a heavily-loaded system or a low-spec edge device might need the higher end, but 5 seconds ought to be fine otherwise).

**Comment by DanStory** [comment]
> This is not a leak. See #15377. Closing as a dupe.
> 
> If you are actually running out of PIDs, you can adjust the 5 minute timer via the `exit_command_delay` field in containers.conf; lowering to 5 to 10 seconds will probably resolve your issue (depending on how slow your environment is; a heavily-loaded system or a low-spec edge device might need the higher end, but 5 seconds ought to be fine otherwise).

I am aware of that ticket, however even after 6 minutes (as the script demonstrates) or even 19 minutes they are still around.

```bash
$ date                                                                                                                                                                                                           
Mon Nov  7 07:19:30 AM MST 2022
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
$ docker ps -a | grep podman                                                                                                                                                                                      
927078f346a1   quay.io/containers/podman:v4.2.1                               "podman --log-level …"   19 minutes ago   Up 19 minutes             0.0.0.0:2375->2375/tcp, :::2375->2375/tcp   podman
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
$ ps -eo pid,lstart,cmd | grep conmon                                                                                                                                                                             
4161332 Mon Nov  7 07:00:05 2022 [conmon] <defunct>
4161350 Mon Nov  7 07:00:05 2022 [conmon] <defunct>
4161538 Mon Nov  7 07:00:05 2022 [conmon] <defunct>
4161554 Mon Nov  7 07:00:05 2022 [conmon] <defunct>
4161739 Mon Nov  7 07:00:05 2022 [conmon] <defunct>
4161755 Mon Nov  7 07:00:05 2022 [conmon] <defunct>
4161942 Mon Nov  7 07:00:06 2022 [conmon] <defunct>
4161958 Mon Nov  7 07:00:06 2022 [conmon] <defunct>
4162143 Mon Nov  7 07:00:06 2022 [conmon] <defunct>
4162159 Mon Nov  7 07:00:06 2022 [conmon] <defunct>
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
$ docker --host localhost:2375 ps -a                                                                                                                                                                              
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

```

**Comment by mheon** [comment]
Have you reproduced anywhere that is not WSL? I wonder if this is something about their init environment - I know there are nonstandard things there.

**Comment by DanStory** [comment]
This originally cropped up in our production deployment on AWS EKS and we were able to reproduce it on our vSphere cluster using CentOS VM with the same k8s application deployed. I have only been using my workstation (/w WSL) to try and isolate the issue further. I can further troubleshoot on the CentOS VM (i.e. use the above script to see its outcome as well) later today, to rule out my WSL from any foul play. I did also notice, just the container run itself causing defunct processes, I added the additional exec to replicate our actual application's behavior.

Our production's `ps` output can be seen here: https://github.com/containers/podman/files/9952224/conmon-overlayfs_defunct.txt (filtered to only show conmon, overlay and podman processes).

**Comment by mheon** [comment]
Could be as simple as there being no reaper inside the outer container. If you add `--init` to the outer (Docker) container, does that resolve things?

**Comment by DanStory** [comment]
> Could be as simple as there being no reaper inside the outer container. If you add `--init` to the outer (Docker) container, does that resolve things?

I think you'd be right, the processes cleaned up after 5mins in my local WSL environment. I'll have our CentOS environment reconfigured to do the same and report back.

Is this something we missed in the docs or just different between podman vs docker when having podman-in-x?
Didn't seem to be called out in the [image repo](https://quay.io/repository/containers/podman) or [article](https://www.redhat.com/sysadmin/podman-inside-container).

Thanks for the help and fast responses.

**Comment by mheon** [comment]
This is a thing with almost any container: by default, inside the container, you don't have an init - and thus, you have nothing to reap processes that reparent (like Conmon does in order to daemonize). It's a problem with Podman, Docker, and most Kubernetes containers (the only implementation I can think of that doesn't have it would be LXC) - stems from the model of single-service containers, where you run just the app you're containerizing and nothing else. Docker realized this could be a problem early on and added `--init` to inject a super-minimal init binary into the container to reap, if required (Podman also inherited this, with added support for systemd if you want to stick a full-featured init process in).

**Comment by Luap99** [comment]
@mheon We already have a small reaper built into the podman service, https://github.com/containers/podman/blob/main/pkg/servicereaper/service.go
We could add the conmon pids to it to fix it when run as pid 1 in a container.

**Comment by mheon** [comment]
That seems like a good idea - I don't know how common `podman system service` in a container is, but it does seem like something we ought to support.

**Comment by DanStory** [comment]
We added [`tini` ](https://github.com/krallin/tini) to our custom podman container image and used it as the entrypoint. This removed the need for different container configurations (docker vs k8s, etc.) and we verified that it cleaned up the the defunct `conmon` and `fuse-overlay-s` processes in both environments. We additionally reduced the `exit_command_delay` to help ensure exec session creation rates didn't overwhelm the process count as well.

**Comment by mheon** [comment]
You need to run an init inside the container running `podman system service`

**Comment by TTWShell** [comment]
> You need to run an init inside the container running `podman system service`

Thx!
```version: "3.9"
services:
  podman:
    image: xxxx
    init: true
```
https://docs.docker.com/compose/compose-file/compose-file-v3/#init
https://github.com/krallin/tini
![image](https://user-images.githubusercontent.com/8017604/202385700-4509c520-2e89-40fd-94a0-e33f9352be61.png)
Root cause: A pid 1 process must reap forked child processes correctly. if not use --init, podman service pid is 1.

**Comment by rhatdan** [comment]
Looks like this one was solved.
