### ISSUE TITLE
podman exec via remote ssh call yields to "exec failed: container does not exist"

### ISSUE THREAD

**Issue by UlrichLohrmann** [containers/podman#16454]
/kind bug

**Description**

Starting a interactive session on a running container (rootless) with 

podman exec -it $CONTAINERNAME bash

works if this command is executed from the container host. If same command is executed from a remote host using ssh

ssh -i ~/.ssh/$RSA_KEY_FILE qtcnt01@lvintappt01 'podman --log-level=debug exec -it $CONTAINERNAME bash'

the exec session cannot be started an terminates with the following error message:

Error: OCI runtime error: runc: [conmon:d]: exec with attach is waiting for start message from parent
[conmon:d]: exec with attach got start message from parent
time="2022-11-09T11:36:29+01:00" level=error msg="exec failed: container does not exist"

**Steps to reproduce the issue:**

1. Execute a podman exec command from a remote Server using ssh

**Describe the results you expected:**

If I could start a podman exec to a non-root container from the container host and the Non-root Linux User ID I would expect that I could also start the exec session from a remote Linux machine using the same Linux User ID as ssh login ID.

**Output of `podman version`:**

```
podman version 4.1.1 on Red Hat Linux Enterprise 8.6
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.26.2
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.2-2.module+el8.6.0+15917+093ca6f8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.2, commit: 8c4f33ac0dcf558874b453d5027028b18d1502db'
  cpuUtilization:
    idlePercent: 92.61
    systemPercent: 2.53
    userPercent: 4.86
  cpus: 2
  distribution:
    distribution: '"rhel"'
    version: "8.6"
  eventLogger: file
  hostname: lvintappt02
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 427680
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 3448
      size: 1
    - container_id: 1
      host_id: 427680
      size: 65536
  kernel: 4.18.0-372.19.1.el8_6.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 333164544
  memTotal: 16596619264
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.3-2.module+el8.6.0+15917+093ca6f8.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.3
      spec: 1.0.2-dev
      go: go1.17.7
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /tmp/podman-run-3448/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.2.0-2.module+el8.6.0+15917+093ca6f8.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 16609030144
  swapTotal: 16642994176
  uptime: 1731h 4m 5.65s (Approximately 72.12 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - lvnexust01.dsv-gruppe.de:10443
store:
  configFile: /work/qtcnt01/.config/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 3
    stopped: 3
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/qtcnt01/.local/share/containers/storage
  graphRootAllocated: 51720519680
  graphRootUsed: 18057826304
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 23
  runRoot: /tmp/podman-run-3448/containers
  volumePath: /home/qtcnt01/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1657551413
  BuiltTime: Mon Jul 11 16:56:53 2022
  GitCommit: ""
  GoVersion: go1.17.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
qtcnt01@lvintappt02 [~]: rpm -q podman
podman-4.1.1-2.module+el8.6.0+15917+093ca6f8.x86_64

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No, cannot install another version on the Red Hat as we use the official repositories.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
None

**Comment by vrothberg** [comment]
@giuseppe @rhatdan I'd also expect ssh to work.  May it be a config issue of ssh that renders the session incomplete?

**Comment by UlrichLohrmann** [comment]
Thank you for reply. I don't think this is a SSH issue. For example I can execute

ssh -i ~/.ssh/id_rsa_qtcnt01_lvintappt01 qtcnt01@lvintappt01 'podman inspect $CONTAINERNAME'

and that works without errors.

**Comment by UlrichLohrmann** [comment]
Additional info.

If I execute the podman exec command with --log-level=debug and compare the output of the working call (from the container host) with the output of the Non-working call (from remote via SSH) the following line is in the output of the non working call but NOT in the output of the working call.

Overriding run root \"/run/user/3448/containers\" with \"/tmp/podman-run-3448/containers\" from database"

**Comment by Luap99** [comment]
> runRoot: /tmp/podman-run-3448/containers

This looks wrong and can cause issues. Please run `podman system reset` and make sure you have a proper login session when you run the podman commands, i.e. do not use su or sudo to switch to the user. After the reset run `podman info` again, it should show a path under /run/user/<uid> normally.

**Comment by Luap99** [comment]
Also note that the error comes from runc not podman. So I suspect that runc looks into a different tmp dir in both cases.

**Comment by UlrichLohrmann** [comment]
Thank you for your reply. I will try and give feedback asap

**Comment by UlrichLohrmann** [comment]
I tried "podman system reset" on the system that is accessed by SSH but nothing changes.

I also tried to do a ssh login from another Linux box to the target server and executed "podman exec -it $CONTAINERNAME bash" with the same result. If I do a SSH login from my Windows box with putty to the same target server and also execute "podman exec -it $CONTAINERNAME" this works. That target account in both cases is the same.

So what is the difference between a putty login from Windows and a ssh login from another Linux box?

**Comment by UlrichLohrmann** [comment]
More info.

If I access the Non-root targetuser on the Linux machine directly via ssh the "podman exec $CONTAINERNAME ls -al" fails, if I login with my personal account and switch to the podman targetuser with "sudo -iu $TARGETUSERID" everything works fine.

**Comment by Luap99** [comment]
see https://github.com/containers/podman/blob/main/troubleshooting.md#31-podman-run-fails-with-erro0000-xdg_runtime_dir-directory-runuser0-is-not-owned-by-the-current-user-or-error-creating-tmpdir-mkdir-runuser1000-permission-denied

sudo or su should not be used to switch to a user, they simply do not create a proper systemd user session.
Please make sure your run root points to `/run/user...` and XDG_RUNTIME_DIR is set correctly for all sessions.

**Comment by UlrichLohrmann** [comment]
Thank you for your hint, I enabled linger mode for the system user that is running Non-root containers and now evertything works as expected.

**Comment by vrothberg** [comment]
Nice work debugging and resolving the issue, @UlrichLohrmann and @Luap99 !
