### ISSUE TITLE
Inspecting a network via the REST API does not work

### ISSUE THREAD

**Issue by SoMuchForSubtlety** [containers/podman#16453]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Inspecting a network via the REST API yields this seemingly unrelated error message 
```
getting container from store "9bef809f62af8fe14da2751b1560cf436281fba8b73f3e75d80172e7f6321f98": container not known
```
Inspecting networks via the CLI works as expected.

**Steps to reproduce the issue:**

1. get the ID of a network (for example the default `podman` network) via `podman network inspect`

2. request the same information via the REST API[^1]
```bash
curl --unix-socket /run/user/1000/podman/podman.sock http:/v1.32/networks/network-id-goes-here
```

**Describe the results you received:**
```json
{"cause":"container not known","message":"getting container from store \"9bef809f62af8fe14da2751b1560cf436281fba8b73f3e75d80172e7f6321f98\": container not known","response":500}
```

**Describe the results you expected:**
no error

**Additional information you deem important (e.g. issue happens only occasionally):**
This happens with every network, even if it's not being used by any containers.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.3.0
API Version:  4.3.0
Go Version:   go1.18.7
Built:        Fri Oct 21 10:16:35 2022
OS/Arch:      linux/amd64

```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-3.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: '
  cpuUtilization:
    idlePercent: 92
    systemPercent: 1.71
    userPercent: 6.29
  cpus: 16
  distribution:
    distribution: fedora
    variant: workstation
    version: "36"
  eventLogger: journald
  hostname: honestmistake
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.0.5-200.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 7807201280
  memTotal: 32834928640
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.6-2.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.6
      commit: 18cf2efbb8feb2b2f20e316520e0fd0b6c41ef4d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 1h 3m 42.00s (Approximately 0.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  localhost:50001:
    Blocked: false
    Insecure: true
    Location: localhost:50001
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: localhost:50001
    PullFromMirror: ""
store:
  configFile: /home/jakob/.config/containers/storage.conf
  containerStore:
    number: 49
    paused: 0
    running: 1
    stopped: 48
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/jakob/.local/share/containers/storage
  graphRootAllocated: 510405902336
  graphRootUsed: 310382002176
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 319
  runRoot: /run/user/1000/containers
  volumePath: /home/jakob/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.0
  Built: 1666340195
  BuiltTime: Fri Oct 21 10:16:35 2022
  GitCommit: ""
  GoVersion: go1.18.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
podman-4.3.0-2.fc36.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The "container ID" from the error message is different from the network ID I requested. It's the same every time.

I encountered this trying to get the tests from https://github.com/testcontainers/testcontainers-java working with podman.

[^1]: https://github.com/containers/podman/blob/757fdca77b0fc72e61f7ee69f19a36144bfcac36/vendor/github.com/docker/docker/api/swagger.yaml#L9075-L9077

**Comment by Luap99** [comment]
Sounds like your state is inconsistent. Somehow there is a mismatch between the podman boltdb and the container store.

Running `podman system reset` (will remove everything) should get it working again. Do you have a reproduce how you got into that situation?

**Comment by Luap99** [comment]
you could also try `podman rm -f 9bef809f62af8fe14da2751b1560cf436281fba8b73f3e75d80172e7f6321f98`

**Comment by SoMuchForSubtlety** [comment]
> Sounds like your state is inconsistent. Somehow there is a mismatch between the podman boltdb and the container store.

That seems to be the issue. I debugged the request and the issue is a container that is present in boltdb but not the store.

During the conversion to a docker networks, all containers are requested from boltdb and then inspected.
https://github.com/containers/podman/blob/fbf441affd948e61d2833d05e735367eafcf4274/pkg/api/handlers/compat/networks.go#L68-L75

In my case, the offending container is the infra container of a pod. I remember having trouble with that pod being in an invalid state in the past, after `kube play --replace`.

Maybe the error could be handled more gracefully? For example, just skipping the container on `ErrContainerUnknown` and logging a warning.

**Comment by vrothberg** [comment]
@Luap99 WDYT?

**Comment by Luap99** [comment]
How does this work with other podman commands or API calls? This problem does not look specific to this single endpoint.

**Comment by vrothberg** [comment]
@SoMuchForSubtlety do you have reproducer how you got into this state?

**Comment by SoMuchForSubtlety** [comment]
I can no longer reproduce this, so I think this can be closed.

**Comment by vrothberg** [comment]
Thanks for checking!
