### ISSUE TITLE
podman build for non-host platform stopped working after upgrading

### ISSUE THREAD

**Issue by kgibm** [containers/podman#16451]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

On macOS, previously, I was able to build images for platforms other than my host platform; but, after upgrading to podman 4.3.0, this no longer works.

**Steps to reproduce the issue:**

1. `podman machine init --cpus 4 --memory 10240 --disk-size 100`
2. `podman machine start`
3. `podman system connection default podman-machine-default-root`
4. `podman machine ssh "sudo rpm-ostree install qemu-user-static; sudo systemctl reboot"`
5. `git clone https://github.com/IBM/containerdiag`
6. `cd containerdiag`
7. `podman build --platform linux/ppc64le --jobs=1 --manifest localhost/containerdiag:latest .`

**Describe the results you received:**

For example, running with `--platform linux/ppc64le` on a host platform of `x86_64` shows that the build is using `x86_64` instead:

```
$ podman build --platform linux/ppc64le --jobs=1 --manifest localhost/containerdiag:latest .
[...]
Installing:
 binutils                     x86_64 2.37-36.fc36                 updates 6.0 M
```

However, using `podman run` works as expected:

```
$ for p in linux/amd64 linux/arm64/v8 linux/ppc64le linux/s390x; do podman run --rm --platform $p -it docker.io/fedora uname -m 2>/dev/null; done
x86_64
aarch64
ppc64le
s390x
```

**Describe the results you expected:**

`podman build --platform` should build with the specified platform.

**Output of `podman version`:**

<details>
<summary>podman version</summary>

```
$ podman version
Client:       Podman Engine
Version:      4.3.0
API Version:  4.3.0
Go Version:   go1.18.7
Built:        Tue Oct 18 12:55:57 2022
OS/Arch:      darwin/amd64

Server:       Podman Engine
Version:      4.3.0
API Version:  4.3.0
Go Version:   go1.18.7
Built:        Fri Oct 21 03:16:35 2022
OS/Arch:      linux/amd64
```

</details>

**Output of `podman info`:**

<details>
<summary>podman info</summary>

```
$ podman info
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-3.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: '
  cpuUtilization:
    idlePercent: 92.27
    systemPercent: 3.67
    userPercent: 4.06
  cpus: 4
  distribution:
    distribution: fedora
    variant: coreos
    version: "36"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.0.5-200.fc36.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 7968133120
  memTotal: 10430509056
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.6-2.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.6
      commit: 18cf2efbb8feb2b2f20e316520e0fd0b6c41ef4d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 17m 54.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 106825756672
  graphRootUsed: 4793147392
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 19
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.3.0
  Built: 1666340195
  BuiltTime: Fri Oct 21 03:16:35 2022
  GitCommit: ""
  GoVersion: go1.18.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.0
```

</details>

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

<details>
<summary>brew info podman</summary>

```
$ brew info podman
==> podman: stable 4.3.0 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/usr/local/Cellar/podman/4.3.0 (185 files, 48MB) *
  Poured from bottle on 2022-11-08 at 13:38:17
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
```

</details>

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

**Yes**/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

<details>
<summary>macOS details</summary>

```
$ system_profiler SPSoftwareDataType SPHardwareDataType | grep -v -e UUID -e UDID -e 'User Name' -e 'Computer Name' -e Serial
Software:

    System Software Overview:

      System Version: macOS 12.6 (21G115)
      Kernel Version: Darwin 21.6.0
      Boot Volume: MainDisk
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Disabled
      Time since boot: 5 days 5:51

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro15,1
      Processor Name: 6-Core Intel Core i7
      Processor Speed: 2.6 GHz
      Number of Processors: 1
      Total Number of Cores: 6
      L2 Cache (per Core): 256 KB
      L3 Cache: 9 MB
      Hyper-Threading Technology: Enabled
      Memory: 16 GB
      System Firmware Version: 1731.140.2.0.0 (iBridge: 19.16.16067.0.0,0)
      OS Loader Version: 540.120.3~22
      Activation Lock Status: Enabled
```

</details>

**Comment by kgibm** [comment]
I thought this was related to the `podman` version, but I downgraded to my previous version, and experienced the same issue. Then I realized that upgrading `podman` to 4.3.0 upgraded the version of CoreOS being used by `podman machine` (to an October build), even with the older `podman` version. I found I have some old images in `~/.local/share/containers/podman/machine/qemu/` and created a `podman machine` with `--image-path` with one from May, and the problem was resolved:

1. `podman machine init --cpus 4 --memory 10240 --disk-size 100 --image-path ~/.local/share/containers/podman/machine/qemu/fedora-coreos-36.20220511.dev.0-qemu.x86_64.qcow2.xz`
2. `podman machine start`
3. `podman system connection default podman-machine-default-root`
4. `podman machine ssh "sudo rpm-ostree install qemu-user-static; sudo systemctl reboot"`
5. `git clone https://github.com/IBM/containerdiag`
6. `cd containerdiag`
7. `podman build --platform linux/ppc64le --jobs=1 --manifest localhost/containerdiag:latest .`
   ```
   [...]
    binutils                     ppc64le 2.37-36.fc36                updates 6.7 M
   ```

Is this an issue with CoreOS or podman?

Relatedly, if I didn't have the cached image, how would I have downloaded it? Where are they?

**Comment by Luap99** [comment]
@flouthoc PTAL

**Comment by kgibm** [comment]
I found a list of "Stable" CoreOS builds here: https://builds.coreos.fedoraproject.org/browser?stream=stable&arch=x86_64

Then downloaded the "QEMU" builds, working backwards from the latest build to find where things stopped working, and the problem reproduced all the way back to 36.20220505.3.2 which is before the build that worked above. Maybe there's some sort of race condition when creating the image that puts it into a bad state?

**Comment by kgibm** [comment]
One more wrinkle: I can consistently reproduce the problem with the Stable CoreOS builds, and I can consistently not reproduce the problem using `~/.local/share/containers/podman/machine/qemu/fedora-coreos-36.20220511.dev.0-qemu.x86_64.qcow2.xz` which includes "dev" in the name that stable builds don't, so I'm not even sure where that image came from.

**Comment by kgibm** [comment]
Looks like those dev images come from here: https://fedorapeople.org/groups/podman/testing/builds/
Nothing since May

**Comment by rhatdan** [comment]
I don't believe these are supported, and we rely on fedora coreos for new machines now.
@baude Am I mistaken?

**Comment by rhatdan** [comment]
@dustymabe ^^

**Comment by dustymabe** [comment]
@kgibm There are packages that you need that aren't installed by default. This should fix you up:

```
sudo rpm-ostree install qemu-user-static-aarch64 qemu-user-static-ppc qemu-user-static-s390x
sudo reboot
```

For rationale see:

- https://github.com/coreos/fedora-coreos-tracker/issues/1088
- https://github.com/coreos/fedora-coreos-tracker/issues/1237

**Comment by rhatdan** [comment]
Since you have a suggested solution, closing.
