### ISSUE TITLE
podman-network-create.1.md: inconsistent description of available drivers/backends

### ISSUE THREAD

**Issue by jmtd** [containers/podman#16472]
/kind bug

**Description**

Selectively quoting podman-network-create.1.md (emphasis mine):

> --driver, -d
> 
> Driver to manage the network. Currently **bridge, macvlan and ipvlan are supported**. Defaults to bridge.
> …
> 
> Special considerations for the **netavark** backend:
> 
> * The macvlan driver requires the --subnet option, DHCP is currently not supported.
> * **The ipvlan driver is not currently supported.**

The key problems here are

1. ipvlan is described as both supported and not supported.
2. netavark is introduced for the first time in this page but not defined and there's no reference to any other page describing what it is.
3. netavark is described as a backend, but that is also not defined nor is there a reference to a definition elsewhere

**Steps to reproduce the issue:**

n/a

**Describe the results you received:**

n/a

**Describe the results you expected:**

n/a

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

n/a, issue present in current main (e86cef13a132ab6bb22413e9395fd0e197936f24) and last tag
v4.3.0)

**Output of `podman info`:**

n/a

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

n/a

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

n/a

**Additional environment details (AWS, VirtualBox, physical, etc.):**

n/a

**Comment by Luap99** [comment]
The network backend is described in podman-network(1)

**Comment by rhatdan** [comment]
@jmtd Care to open a PR to fix the man page to better introduce netavark and link to its man page.

**Comment by jmtd** [comment]
@rhatdan:
> @jmtd Care to open a PR to fix the man page to better introduce netavark and link to its man page.

Possibly. I'm not the best person to introduce netavark since I don't know what it is; but I do generally try to fix nits when I find them, so I'll try to schedule having a go.

**Comment by rhatdan** [comment]
@Luap99 Could you take care of this?

**Comment by rhatdan** [comment]
@Luap99 Friendly ping

**Comment by Luap99** [comment]
I don't know what to do, ipvlan support will be added very soon and the backend description is already in podman-network(1). It don't want to duplicate the same information across different man pages.
If somebody wants to improve the docs I am happy to review it but I don't see what I can write to make it better.

**Comment by rhatdan** [comment]
I am going to close this issue, since know one has stepped up to further help with documentation.
