### ISSUE TITLE
podman machine on macOS and default system connection

### ISSUE THREAD

**Issue by benoitf** [containers/podman#16483]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Deleting and adding machines is leading to a missing default connection.

**Steps to reproduce the issue:**

1. Create a machine

2. Create another one

3. Delete the first machine

4. start 'another' machine (so this is the machine being running)

**Describe the results you received:**

```
$ podman ps                                                                                                                                                          
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.3.0/libpod/_ping": dial unix ///var/folders/tg/_5rxbhmj4xncz4szvpgswrmc0000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```

**Describe the results you expected:**

```
$ podman ps
```
should work.
Removing a machine when there is another one should move the default connection to another one
Or when starting a new machine, if all system connections are set to false, it should flag to true the connection to the machine being started.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
V4.3.0
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by arixmkii** [comment]
> Removing a machine when there is another one should move the default connection to another one

Will not be a trivial choice if more than one option is left.

> Or when starting a new machine, if all system connections are set to false, it should flag to true the connection to the machine being started.

Not sure about this either. I'm thinking about scenario of using podman machine on a Linux host, where podman machine is used together with the podman service running on the host - there will be no connection record for accessing host service and `podman ps` will just route to it.

So the behavior you described makes sense only for podman remote (machine is in fact podman remote to the started VM with simplified VM startup process) scenario.

**Comment by benoitf** [comment]
@arixmkii basically yes it should be for Windows and macOS where there is no local podman

**Comment by baude** [comment]
is it not still a valid scenario for mac and windows?  i have some ideas though

**Comment by arixmkii** [comment]
> is it not still a valid scenario for mac and windows?

It could be considered as one. Don't know if it is a good idea to introduce behavior differences between platforms and if Linux platform should be considered as a reference for others. It is for the project team to decide.

**Comment by slemeur** [comment]
cc @vyasgun

**Comment by vyasgun** [comment]
Opened a PR to go through the list of available machines and set the default value to one of those: https://github.com/containers/podman/pull/17677
