### ISSUE TITLE
Podman Machine Init cannot create keys windows 10

### ISSUE THREAD

**Issue by Bshukrallah22** [containers/podman#16487]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I have predownloaded the fedora tar file (rootfs.tar.xz) and run "podman machine init --image-path rootfs.tar.xz" to build the default podman machine. Podman 4.3.0 & 4.3.1

When creating a new podman default machine on windows 10 I get the following error:
Configuring system...
Generating public/private ed25519 key pair.
Saving key "podman-machine-default" failed: Bad address
Error: could not create ssh keys: exit status 1

**Steps to reproduce the issue:**
1.Downloaded rootfs.tar.xz (fedora image)

2. Run "podman machine init --image-path rootfs.tar.xz

**Describe the results you received:**
When creating a new podman default machine on windows 10 I get the following error:
Configuring system...
Generating public/private ed25519 key pair.
Saving key "podman-machine-default" failed: Bad address
Error: could not create ssh keys: exit status 1

**Describe the results you expected:**

podman-machine-default to start

**Additional information you deem important (e.g. issue happens only occasionally):**
This worked on podman 4.2.1...

**Output of `podman version`:**

```
"cannot connect to podman"
```

**Output of `podman info`:**

```
Host:
  Arch: amd64
  CurrentMachine: ""
  DefaultMachine: ""
  EventsDir: C:\Users\user\.local\share\containers\podman\podman
  MachineConfigDir:  C:\Users\user\.config\containers\podman\machine\wsl
  MachineImageDir: C:\Users\user\.local\share\containers\podman\machine\wsl
  MachineState: ""
  NumberOfMachines: 0
  OS: windows
  VMType: wsl
Version:
  APIVersion: 4.3.1
  Built: 1668089925
  BuiltTime: Thu Nov 10 09:18:45 2022
  GitCommit: ""
  GoVersion: go1.18.5
  Os: windows
  OsArch: windows/amd64
  Version: 4.3.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
podman-4.3.1-setup.exe
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
local windows machine

**Comment by vrothberg** [comment]
Did you start the machine via `podman machine start`?

**Comment by Bshukrallah22** [comment]
I'm sorry for some reason my error message wasn't showing up in my initial comment, but when I clicked the edit button it was there. I fixed the initial post. 

For clarification I get an error when creating the podman machine:
Configuring system...
Generating public/private ed25519 key pair.
Saving key "podman-machine-default" failed: Bad address
Error: could not create ssh keys: exit status 1

The machine never completes the creation process, so I cannot manually start the machine.

**Comment by rhatdan** [comment]
@ashley-cui @baude Ideas?

**Comment by ashley-cui** [comment]
If you do a `podman machine init` without specifying the image path, does the init still fail?

**Comment by Bshukrallah22** [comment]
Hi @ashley-cui yes, it happens even with just "podman machine init"

It just downloads the linux image and then fails when trying to create the SSH key.

**Comment by Bshukrallah22** [comment]
Hi @baude 

I ran the command with debug logging. I got this:

"Running command: wsl cm [-u root -d podman-machine-default ssh-keygen -N -t ed25519 -f podman-machine-default] in dir: C:\\Users\\UserName\\.ssh"
Generating public/private ed25519 key pair.
Saving key "podman-machine-default" failed: Bad address
Error: could not create ssh keys: exit status 1

I've tried elevated and non-elevated  command prompt and powershell.

I'm not sure about non-default storage locations.

**Comment by n1hility** [comment]
@Bshukrallah22 where are you downloading rootfs from?

They should be downloaded/derived from https://github.com/containers/podman-wsl-fedora/releases
Stock fedora images will not work correctly.

If you do not specify an --image-path, and let it download does it work correctly?

**Comment by Nocsaron** [comment]
Not, OP, but I am having the same errors. Here's my debug log if it helps:

```
PS C:\Users\1114337> podman --log-level=debug machine init
time="2023-02-26T09:13:33-07:00" level=info msg="C:\\Program Files\\RedHat\\Podman\\podman.exe filtering at log level debug"
Extracting compressed file
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
time="2023-02-26T09:13:52-07:00" level=debug msg="Running command: wsl [--import podman-machine-default C:\\Users\\1114337\\.local\\share\\containers\\podman\\machine\\wsl\\wsldist\\podman-machine-default C:\\Users\\1114337\\.local\\share\\containers\\podman\\machine\\wsl\\podman-machine-default_fedora-podman-amd64-v36.0.133.tar --version 2]"
time="2023-02-26T09:13:58-07:00" level=debug msg="Running command: wsl [-u root -d podman-machine-default rpm -q --restore shadow-utils 2>/dev/null]"
Configuring system...
time="2023-02-26T09:14:01-07:00" level=debug msg="Running command: wsl [-u root -d podman-machine-default sh -c grep -q Port\\ 57610 /etc/ssh/sshd_config || echo Port 57610 >> /etc/ssh/sshd_config]"
time="2023-02-26T09:14:01-07:00" level=debug msg="Running command: wsl [-u root -d podman-machine-default sh]"
time="2023-02-26T09:14:02-07:00" level=debug msg="Running command: wsl [-u root -d podman-machine-default sh -c cat >> /etc/sudoers]"
time="2023-02-26T09:14:02-07:00" level=debug msg="Running command: wsl [-u root -d podman-machine-default sh -c cat > /etc/systemd/system/systemd-sysusers.service.d/override.conf]"
time="2023-02-26T09:14:03-07:00" level=debug msg="Running command: wsl [-u root -d podman-machine-default sh -c cat > /home/user/.config/systemd/user/linger-example.service]"
time="2023-02-26T09:14:03-07:00" level=debug msg="Running command: wsl [-u root -d podman-machine-default sh -c mkdir -p /var/lib/systemd/linger; touch /var/lib/systemd/linger/user]"
time="2023-02-26T09:14:04-07:00" level=debug msg="Running command: wsl [-u root -d podman-machine-default sh]"
time="2023-02-26T09:14:04-07:00" level=debug msg="Running command: wsl [-u root -d podman-machine-default sh -c cat > /etc/containers/containers.conf]"
time="2023-02-26T09:14:05-07:00" level=debug msg="Running command: wsl [-u root -d podman-machine-default sh -c cat > /etc/containers/registries.conf.d/999-podman-machine.conf]"
time="2023-02-26T09:14:05-07:00" level=debug msg="Running command: wsl [-u root -d podman-machine-default sh -c echo wsl > /etc/containers/podman-machine]"
time="2023-02-26T09:14:06-07:00" level=debug msg="Running command: wsl [-u root -d podman-machine-default sh -c cat > /etc/wsl.conf]"
time="2023-02-26T09:14:07-07:00" level=debug msg="Running command: wsl [-u root -d podman-machine-default sh -c cat > /usr/local/bin/enterns; chmod 755 /usr/local/bin/enterns]"
time="2023-02-26T09:14:07-07:00" level=debug msg="Running command: wsl [-u root -d podman-machine-default sh -c cat > /etc/profile.d/enterns.sh]"
time="2023-02-26T09:14:08-07:00" level=debug msg="Running command: wsl [-u root -d podman-machine-default sh -c cat > /etc/wslmotd]"
time="2023-02-26T09:14:08-07:00" level=debug msg="Running command: wsl [-u root -d podman-machine-default sh -c cat > /root/bootstrap; chmod 755 /root/bootstrap]"
time="2023-02-26T09:14:09-07:00" level=debug msg="Running command: wsl [-u root -d podman-machine-default sh -c cat > /usr/local/bin/proxyinit; chmod 755 /usr/local/bin/proxyinit]"
time="2023-02-26T09:14:10-07:00" level=debug msg="Running wsl cmd [-u root -d podman-machine-default ssh-keygen -N  -t ed25519 -f podman-machine-default] in dir: C:\\Users\\1114337\\.ssh"
Generating public/private ed25519 key pair.
Saving key "podman-machine-default" failed: Bad address
Error: could not create ssh keys: exit status 1
time="2023-02-26T09:14:12-07:00" level=debug msg="Shutting down engines"
```

When I run the ssh-keygen command, it fails because the `-N` option isn't recognized:

```
PS C:\Users\1114337\.ssh> wsl -u root -d podman-machine-default ssh-keygen -N  -t ed25519 -f podman-machine-default
Too many arguments.
```

Updating the command to exclude `-N` allows the key to generate, but has the bad address as well

```
PS C:\Users\1114337\.ssh> wsl -u root -d podman-machine-default ssh-keygen -t ed25519 -f podman-machine-default
Generating public/private ed25519 key pair.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Saving key "podman-machine-default" failed: Bad address
```

Like OP, I am unsure about non-standard storage locations.  I am working on a corporate asset, so its possible they have set something up that I am unware of, but I haven't noticed anything like that to date.  Before this issue, the only real problem I ran into was cloning through a proxy. Given the issue comes up even running `wsl` commands directly, I'm wondering if its an issue with `wsl` configuration rather that podman itself.

**Comment by vrothberg** [comment]
@n1hility is this still an issue?

**Comment by n1hility** [comment]
Yeah I don't believe this is an issue anymore. Feel free to reopen if not.
