### ISSUE TITLE
Throwing authentication error while trying to pull image from private server with certificate file.

### ISSUE THREAD

**Issue by cnagesh-arrcus** [containers/podman#16494]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. podman build . --cert-dir /etc/containers/certs.d/ca.crt

**Describe the results you received:**
Error: creating build container: initializing source XXX: reading manifest latest in XXX: errors:
denied: requested access to the resource is denied
unauthorized: authentication required

**Describe the results you expected:**
I'm trying to pull images from the private server and the certificate is placed in /etc/containers/certs.d/ca.crt but it is not able to authenticate. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 4.3.0
```

**Output of `podman info`:**

```
host:
  arch: arm64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-3.fc36.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: '
  cpuUtilization:
    idlePercent: 99.68
    systemPercent: 0.18
    userPercent: 0.14
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "36"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.0.5-200.fc36.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 1702727680
  memTotal: 2049859584
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.6-2.fc36.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.6
      commit: 18cf2efbb8feb2b2f20e316520e0fd0b6c41ef4d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/501/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.aarch64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 8h 5m 35.00s (Approximately 0.33 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106825756672
  graphRootUsed: 2316623872
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/501/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.0
  Built: 1666339972
  BuiltTime: Fri Oct 21 13:42:52 2022
  GitCommit: ""
  GoVersion: go1.18.7
  Os: linux
  OsArch: linux/arm64
  Version: 4.3.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
Tool for managing OCI containers and pods
https://podman.io/
/opt/homebrew/Cellar/podman/4.3.0 (185 files, 47.6MB) *
  Poured from bottle on 2022-11-10 at 10:17:44
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0 and GPL-3.0-or-later
==> Dependencies
Build: go-md2man ✘, go@1.18 ✘
Required: qemu ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions

To restart podman after an upgrade:
  brew services restart podman
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/podman/bin/podman system service --time=0
==> Analytics
install: 29,917 (30 days), 76,656 (90 days), 228,700 (365 days)
install-on-request: 28,036 (30 days), 73,265 (90 days), 224,717 (365 days)
build-error: 26 (30 days)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Macbook M1 pro

**Comment by vrothberg** [comment]
Thanks for reaching out, @cnagesh-arrcus!

> unauthorized: authentication required

The error usually indicates that we are not logged into the registry we attempt to pull from.  Did you do `podman login`?

**Comment by vrothberg** [comment]
Are you running behind a proxy?

**Comment by vrothberg** [comment]
@baude @ashley-cui @benoitf, anything to consider when running `podman machine` in a VPN?  I recall an issue but am unable to find it.

**Comment by vrothberg** [comment]
> @vrothberg one more thing I see, it connects over `https://` how do I make it connect over `http://` ?

Can you be more specific? Are you referring to the registry?

**Comment by benoitf** [comment]
> anything to consider when running podman machine in a VPN? I recall an issue but am unable to find it.

On Windows there is an issue with Machine/VPN https://github.com/containers/podman/issues/14155 / workaround using https://github.com/sakai135/wsl-vpnkit but here it seems it's using Linux

**Comment by ashley-cui** [comment]
There's a draft PR that deals with SSL certs. Related issues perhaps? https://github.com/containers/podman/issues/16041, https://github.com/containers/podman/issues/16413

**Comment by bjorndown** [comment]
@ashley-cui I don't think my PR (https://github.com/containers/podman/pull/16457) will help here. The `no such host` error looks like the podman VM is not aware of DNS servers (and maybe network routes) provided by the VPN on the host.
