### ISSUE TITLE
windows completions not working with shopt -s completion_strip_exe

### ISSUE THREAD

**Issue by patricklx** [containers/podman#16499]
its possible to remove the .exe extension to use binaries in windows git bash by specifying shopt -s completion_strip_exe
but podman is not considering that for the completions.

it registers only podman.exe: `complete -o default -F __start_podman.exe podman.exe`
it should also inlclude without .exe extension: `complete -o default -F __start_podman.exe podman.exe podman`.

**Comment by Luap99** [comment]
Please fill out the issue template as requested.

Podman does not create the completion scripts, they are generated by the https://github.com/spf13/cobra library. The library simply generates the name based of the program name (podman sets it to argv[0]). I don't think it should know about .exe or any other special extensions.
If you run `podman completion bash` it should output the completion script line with just podman as name, that assumes argv[0] is `podman` and not converted to `podman.exe` by git bash before it calls the process.

**Comment by patricklx** [comment]
ah, right its in cobra, I found it in this repo, https://github.com/containers/podman/blob/main/vendor/github.com/spf13/cobra/bash_completionsV2.go#L356 but did not see it was under vendor.
yes, it looks like bash does convert it to podman.exe when calling the process

**Comment by Luap99** [comment]
Did you check how it works in powershell?

**Comment by patricklx** [comment]
just tried it now, does not work either, because its just using `podman.exe` in the variable names, which then turns into a property lookup... so I get this error `The property 'exeCompleterBlock' cannot be found on this object`. 
`Register-ArgumentCompleter -CommandName 'podman.exe' -ScriptBlock $__podman.exeCompleterBlock`

**Comment by Luap99** [comment]
I think you need to run both `podman.exe completion powershell | Out-String | Invoke-Expression` and `podman completion powershell | Out-String | Invoke-Expression` in powershell, at least this is how I remember it when I was working on it.

**Comment by patricklx** [comment]
tried both, same issue

**Comment by rhatdan** [comment]
@n1hility @Luap99 any movement on this one?

**Comment by Luap99** [comment]
I think this must be fixed upstream, https://github.com/spf13/cobra/issues/1853

**Comment by n1hility** [comment]
Note that this is the same issue as #15527. @cdoern was planning to look into the cobra issue not sure if he did yet? @cdoern ?

**Comment by cdoern** [comment]
I will work on both this week @n1hility I just got home from finals :)

**Comment by rhatdan** [comment]
@cdoern @n1hility any chance to work on this?

**Comment by Luap99** [comment]
As best as I can see this is something that cobra upstrem must fix. The shell completion scripts are auto generated by this library.

**Comment by rhatdan** [comment]
Ok I think we can close this issue as we wait for this to be fixed in cobra, once it is fixed there podman will get the fix on a vendor.

**Comment by KongrooParadox** [comment]
In the meantime there is this hacky solution to fix completion : `(podman completion powershell | Out-String) -replace "podman.exe", "podman" | Invoke-Expression`
