### ISSUE TITLE
crun-wasm: Add missing test to podman CI for testing `wasm/wasi` workload.

### ISSUE THREAD

**Issue by flouthoc** [containers/podman#16501]
Following PR https://github.com/containers/podman/pull/16434 went in without any tests in CI. Since we need `crun-wasm` package in CI order to test this. So please add a dedicated test for this.

**Comment by rhatdan** [comment]
@flouthoc any chance to work on this one?

**Comment by rhatdan** [comment]
@flouthoc  reminder

**Comment by rhatdan** [comment]
@flouthoc this should be added now.  @cevich do we have crun-wasm in CI/CD system now?

**Comment by cevich** [comment]
> do we have crun-wasm in CI/CD system now?

I just checked, it's not there.  I'll open a PR to add it, but integrating the images will need to wait until after https://github.com/containers/podman/pull/17305 merges.

**Comment by flouthoc** [comment]
@cevich Thanks as soon as it is done, I'll add a test for this in CI.

**Comment by cevich** [comment]
`c20230220t163742z-f37f36d12` is the new `IMAGE_SUFFIX`, though you'll need to wait and/or rebase on https://github.com/containers/podman/pull/17305 for it to work - script & test updates are needed to support the new Debian VMs.
