### ISSUE TITLE
Podman for Windows install on Enterprise Image - Not fully installing

### ISSUE THREAD

**Issue by rchristman89** [containers/podman#16524]
/kind bug

**Description**

I am installing podman-4.3.1-setup.exe via packer with "/install /quiet /norestart" arguments. This is building an image that is then deployed to multiple VMs. When the image is deployed, I see podman installed in Apps -Installed apps
![image](https://user-images.githubusercontent.com/8922086/201977356-23a7fb26-50df-4db5-865f-477a06942d5b.png)

but it does not show up in the installed location (C:\Program Files\Red Hat)
![image](https://user-images.githubusercontent.com/8922086/201977747-9c796041-d23a-4397-922b-60b4880cc76a.png)

**Steps to reproduce the issue:**

1. Install podman for windows on master image (using packer but it is just an install and then sysprep)

2. Log into VM deployed. Check for podman

**Describe the results you received:**

**Describe the results you expected:**

I would expect podman to be installed since it should be a system wide install. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The image is being built in packer in Azure. The VMs being deployed are in Azure using that Managed image being built.

**Comment by Luap99** [comment]
@n1hility PTAL

**Comment by rchristman89** [comment]
I did a test and took the .msi that is inside the .exe and used that for the install instead and it does not show up. Looks like there is a disconnect between/reason why the msi is not being installed.

**Comment by n1hility** [comment]
@rchristman89 I suspect what is happening here is that if the setup process determines that WSL is not installed, it triggers a multi-boot install process, which requires a reboot in the middle to complete. The sysprep then likely wipes out the second phase installation so the installer does not complete. 

My recommendation would be to disable WSL installation via the installer and perform the wsl installation step in the packer file.

This can be done like so:

`podman-4.3.1-setup.exe /install /quiet WSLCheckbox=0`

 I have an example of manual wsl installation via packer we use for images for testing you can pull from here:


https://github.com/containers/automation_images/blob/main/win_images/win-server-wsl.yml

and

https://github.com/containers/automation_images/blob/main/win_images/win_packaging.ps1
