### ISSUE TITLE
unit for bytes issues

### ISSUE THREAD

**Issue by webarchymeta** [containers/podman#16527]
/kind bug
I seems that some (if not all) command line output does not output bytes computed from correct unit, e.g.
```
sudo podman images
```
command produces, for example, the following output
```
REPOSITORY                TAG        IMAGE ID      CREATED       SIZE
docker.io/library/node    18-alpine  0fa08f92e64b  3 days ago    171 MB
docker.io/library/alpine  3.16.2     9c6f07244728  3 months ago  5.83 MB
etc ...

```
where the sizes `171 MB` or `5.83 MB` are the corresponding actual byte number divided by `1000 * 1000`. The correct size in `MB` should be the said number divided by `1024 * 1024`.

I don't know how wide spread the issue is amongst all the command line apps though ...

**Comment by Luap99** [comment]
A MB (megabyte) is 10^6 == 1 000 000  bytes, that is correct. A MiB (mebibyte) is 2^20 == 1048576 bytes.
At least this is how it is defined by the IEC.

**Comment by webarchymeta** [comment]
you are right
