### ISSUE TITLE
exec /entrypoint.sh: permission denied 

### ISSUE THREAD

**Issue by AParida23** [containers/podman#16537]
After trying to run the sc4s service I'm getting the following error:
Nov 15 20:02:13 host systemd[1]: Starting SC4S Container...
Nov 15 20:02:13 host systemd[1]: Started SC4S Container.
Nov 15 20:02:13 host podman[2269548]: exec /entrypoint.sh: permission denied
Nov 15 20:02:13 host systemd[1]: sc4s.service: Main process exited, code=exited, status=1/FAILURE
Nov 15 20:02:13 host systemd[1]: sc4s.service: Failed with result 'exit-code'.

I checked the permissions on the entrypoint.sh file and it has executable permission -rwxr-xr-x
I'm running the service as root user.
I uninstalled Podman , re-installed it, downloaded the image again but I still get the same error. I'm using podman version 4.2.0
Tried with different container images but got the same error. 
This configuration has been done by me on four other servers but this is the first time this error is being thrown.
The podman version 4.1.1 is running fine on the other servers.
Can anyone please help me with this? Also, can I get the exact command for downloading a specific version of podman?

**Comment by rhatdan** [comment]
Permission denied usually means SELinux or User Namespace.

Could you try in permissive mode?
If it still fails, could you try to run as root?

We also need the output of podman info please.

**Comment by Luap99** [comment]
Also the home dir could be mounted with `noexec`.

**Comment by AParida23** [comment]
Hi @rhatdan 

We are running the service as root and getting the error.
As suggested by you , we ran the service in permissive mode but still getting the same error.

Output from podman info is attached
[podman info.txt](https://github.com/containers/podman/files/10035034/podman.info.txt)

**Comment by AParida23** [comment]
> Also the home dir could be mounted with `noexec`.

Hi @Luap99 checked that but it's not mounted with noexec

**Comment by giuseppe** [comment]
could you try with `--privileged`?  If that works, can you try with `--security-opt seccomp=unconfined`?

Can you share the output of `cat /proc/self/mountinfo` in the host, as well as `podman run --rm $YOUR_IMAGE stat  /entrypoint.sh /`?

**Comment by AParida23** [comment]
Hey @giuseppe Thanks for your help. After running podman run --rm $YOUR_IMAGE stat /entrypoint.sh /  I found that the selinux was on enforcing mode , changing that to permissive mode using setenforce 0 resolved the issue.

**Comment by rhatdan** [comment]
Putting SELinux into Permissive mode should not be the answer.
You can disable SELinux separation for the container with 
podman run --security-opt label=disabled ...

If you see AVC's please report them.
