### ISSUE TITLE
podman does not read ~/.config/containers/registries.conf on Windows 10

### ISSUE THREAD

**Issue by TheRealHnefi** [containers/podman#16532]
/kind bug

**Description**

When running podman on Windows 10, the registries.conf file does not seem to be read.

Note that the documentation contains no information where the global registries.conf file should be located, so only the user-local version in ~/.config/containers/registries.conf can be applied. Creating and editing that file has no effect on podman behavior.

**Steps to reproduce the issue:**

1. Try pulling an image with unqualified repo name. Note that it fails as expected with error: "short-name resolution enforced but cannot prompt without a TTY"

2. Create ~/.config/containers/registries.conf and add the following information: 
```
short-name-mode="permissive"
unqualified-search-registries = ['docker.io']
```
4. Try pulling the image again. Same failure happens.

**Describe the results you received:**
Error: short-name resolution enforced but cannot prompt without TTY

**Describe the results you expected:**
Successfully pulling image from docker.io without qualifying the name

**Additional information you deem important (e.g. issue happens only occasionally):**
This happens even if CONTAINERS_REGISTRIES_CONF is set to a valid location of registries.conf.
I would say there are three issues here:
1: The location of the global registries.conf is undocumented for Windows.
2: The user-local version of registries.conf is not read on Windows.
3: The CONTAINERS_REGISTRIES_CONF version of registries.conf is not read on Windows.

**Output of `podman version`:**
```
Client:       Podman Engine
Version:      4.3.0
API Version:  4.3.0
Go Version:   go1.18.7
Git Commit:   ad42af94903ce4f3c3cd0693e4e17e4286bf094b
Built:        Wed Oct 19 19:53:21 2022
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.2.1
API Version:  4.2.1
Go Version:   go1.18.5
Built:        Wed Sep  7 21:58:19 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.4-3.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: '
  cpuUtilization:
    idlePercent: 99.88
    systemPercent: 0.1
    userPercent: 0.02
  cpus: 12
  distribution:
    distribution: fedora
    variant: container
    version: "36"
  eventLogger: journald
  hostname: LKP2DR20D2
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.16.3-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 53526683648
  memTotal: 53848203264
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.6-2.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.6
      commit: 18cf2efbb8feb2b2f20e316520e0fd0b6c41ef4d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 13958643712
  swapTotal: 13958643712
  uptime: 48h 14m 43.00s (Approximately 2.00 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 269490393088
  graphRootUsed: 1204199424
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.2.1
  Built: 1662580699
  BuiltTime: Wed Sep  7 21:58:19 2022
  GitCommit: ""
  GoVersion: go1.18.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Luap99** [comment]
This file is read where the podman service runs, so in the podman machine (assuming you use podman machine).

**Comment by TheRealHnefi** [comment]
@Luap99 Oooh. That makes sense. I suppose it could have been a bit clearer in the docs, but now I get it. Thank you.

**Comment by Luap99** [comment]
@TheRealHnefi We can always improve the docs. If you have suggestions please let us know or even better open a PR.
