### ISSUE TITLE
Man pages: refactor common options: the rest

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#16536]
Here is the final list of options that I can't consolidate. Maybe one of you can.

| option | where found |
| ---- | ---- |
| --arch* |  build import manifest-add manifest-annotate |
| --compress |  build container-checkpoint push save |
| --cpus* |  container-clone machine-init machine-set pod-clone pod-create |
| --env* |  build generate-systemd secret-create |
| --ignore* |  rmi volume-create |
| ~~--ip*~~ |  ~~kube-play network-connect~~ (the options works differently for these commands and cannot be combined) |
| --noheading |  image-trust images machine-list network-ls pod-ps ps secret-ls volume-ls |
| --os* |  build import manifest-add manifest-annotate |
| --service |  kube-apply kube-generate |
| --username |  login machine-init machine-ssh |
| --volume* |  build machine-init |

Asterisk indicates that there's already an `options/foo.md` file but its content is very different from the option description in the remaining md files.

**Comment by Luap99** [comment]
Thanks for the great work on this @edsantiago.
I will take a look at --ip.

**Comment by Luap99** [comment]
--ip works differently for the listed commands, it is correct that the man page description differs.

**Comment by edsantiago** [comment]
Should anyone care to try, this is the tool I used for every one of the options I refactored (attached below). Usage is:
```console
$ cd docs/source/markdown
[save tool here, as option-refactor, and chmod it 755]
$ clear;./option-refactor username
```
This will show the diffs between all the related `.md.in` files. Once you get them all to match (via hand-editing), the script will create the `options/NAME.md` file, strip out the option from those `.md.in` files, replace with `@@option NAME`, and `git add` (without commit).

For the asterisked options, where there might already be (e.g.) `options/os.md`, append dot-qualifier:
```console
$ clear;./option-refactor os.manifest manifest
```
That indicates that the created file will be `options/os.manifest.md`, to distinguish it from the existing `os.pull.md` and because (see second arg) this is only reading files that match the glob `*manifest*.md.in`. All arguments past the first are globs, used to restrict the files matched - that's how I got all the `*.pod.md` and `*.container.md` separations.

Good luck.

[option-refactor.txt](https://github.com/containers/podman/files/10034271/option-refactor.txt)

**Comment by rhatdan** [comment]
You script is missing cdif?

**Comment by edsantiago** [comment]
`cdif` is a colorizing diff that highlights actual diffs between long lines. Looks like it's now available [here](https://github.com/kaz-utashiro/sdif-tools), although it seems to have changed significantly from the (2014) version I still use.

**Comment by rhatdan** [comment]
How do I install that onto my machine?  Does not seem to have a simple `make install`

**Comment by edsantiago** [comment]
Yeah, it got a lot more complicated over the years. Try downloading [this](https://github.com/containers/podman/files/10339495/cdif.txt), save as `cdif` in your $PATH (`+x` of course), and `dnf install perl-Encode perl-Text-ParseWords`

**Comment by edsantiago** [comment]
Closing, these are never going to be combined
