### ISSUE TITLE
docker system helper / podman-mac-helper installation should be setup by default on macOS

### ISSUE THREAD

**Issue by benoitf** [containers/podman#16547]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Today, if I install podman and start a podman machine
I can read in the output that the Docker socket is not added as I need to setup an extra tool.

something like

```
The system helper service is not installed; the default Docker API socket
address can't be used by podman. If you would like to install it run the
following commands:

        sudo /opt/podman/bin/podman-mac-helper install
        podman machine stop; podman machine start
```

But as the pkg installer is performing installation steps as root, I think that it should also install the mac helper
so we don't need a post-install step.

On Windows the docker socket is automatically bound, while on macOS it requires this extra step.

**Steps to reproduce the issue:**

1. Run brew or pkg installation of podman

**Describe the results you received:**

need to run install as root on podman-mac-helper

**Describe the results you expected:**

podman-mac-helper installation already done

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@gbraad Can this be done within the installer, where if you don't have root passwd, it will still install, or if not, could you set it up such that a user could cancel the attempt to install the `docker system helper` but still successfully install.

**Comment by anjannath** [comment]
Installer always runs with root privileges, we can easily run this command
in the `postinstall` script.

**Comment by n1hility** [comment]
Brew based installs of podman can't do this by default, package installation is purposefully not ran as root, and packages are supposed to indicate root actions as a separate step. So the best we could do is after a brew install is complete, print directions, but these may be ignored.

I agree we should fix the mac installer case, but in the brew case, I think the only solution is if podman-desktop checks and activates it (or tells the user to)
