### ISSUE TITLE
Podman machine won't start due to corrupted config file

### ISSUE THREAD

**Issue by gravityFlower** [containers/podman#16550]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

This problem concerns Podman on Windows. I have seen this problem occur on other occations with other programs on Windows. The content of the original (or changed) config file, every char is replaced with the value '\x00'.

![grafik](https://user-images.githubusercontent.com/12392087/202690422-f7525b24-9f19-4192-8bb9-7e8afe414f4b.png)

**Steps to reproduce the issue:**

unknown

**Describe the results you received:**

Due to the corrupted configuration file the podman wsl container won't start.

**Describe the results you expected:**

Detect that the config file is corrupted, check for existing wsl containers and ask for permission to recreate the config for the machine.
Or maybe create backups of the config file and load the last one.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

![grafik](https://user-images.githubusercontent.com/12392087/202691910-816788d0-dab3-4d9a-9710-21e4763934df.png)

**Output of `podman info`:**

Same as above.

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

Installer used was podman-4.3.0-setup.exe

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
Edition	Windows 10 Pro
Version	22H2
Betriebssystembuild	19045.2251
Leistung	Windows Feature Experience Pack 120.2212.4180.0
```

**Comment by mheon** [comment]
@n1hility PTAL

**Comment by Luap99** [comment]
It would help if you could describe how you got into that situation?
I think it is much better to prevent this problem from happening than to recover a corrupt file which is likely much harder to do.

**Comment by gravityFlower** [comment]
Unfortunately i can't.
Since there was no indication, which config file exactly was affected, i can't look if it was the case i suspect. I also uninstalled this podman version and installed the latest version.
It is my assumption that the file contains all \0  becaus this happened to me with other programs. These cases are extremely rare (i believe they happened to me 3-4 times in 6 years), but they do occur and my assumption is that it has to do with the way windows handles (over)writing (config) files (since affected files where always xml or json config files).
Maybe it should have rather been a feature request in the sense of  "if the config file is corrupted, provide an option to try to fix it". I'm also ok with the issue being closed if you like.

**Comment by n1hility** [comment]
@gravityFlower Thanks for the report. The presence of NULLs in the file indicates an incomplete NTFS write. When NTFS allocates space for a new/overriten it's a multi-step operation that first assigns the space, and later writes the data. If the data is not written reads on the file are zero-filled, leading to the NULLs you observe. While usually, these steps are usually immediate,  there is a slight delay from write caching/buffer, and a power failure, or hard reboot in between them would lead to this observed corruption.

We can improve this with a different approach which is atomic.

**Comment by typedefstructer** [comment]
I just got the same error, how do I get out of it? 
Any commands that I can run, that'll reset podman or wsl?

I did a reinstall, didn't help

**Comment by n1hility** [comment]
You can do a podman machine rm command to get rid of the state and podman machine init to recreate

**Comment by niheaven** [comment]
Hmm, sorry, but `podman machine rm` gives error too.

> Error: invalid character '\x00' looking for beginning of value

So does `podman machine list`

> Error: listing vms: invalid character '\x00' looking for beginning of value

**Comment by yacao** [comment]
> Hmm, sorry, but `podman machine rm` gives error too.
> 
> > Error: invalid character '\x00' looking for beginning of value
> 
> So does `podman machine list`
> 
> > Error: listing vms: invalid character '\x00' looking for beginning of value

same here in my Windows 11, can't resolve the issue in this way

**Comment by gravityFlower** [comment]
Look into the folder `%USERPROFILE%\.config\containers\podman\machine\wsl` (or `C:\Users\<profile>\.config\containers\podman\machine\wsl`)´. It should be the `podman-machine-default.json` file IIRC. Open it and instead of json there should be a lot of `\x00` instead.
Delete either the podman folder or one up, the container folder.
On the terminal `wsl --list --all` should show you a `podman-machine-default`
Execute `wsl --unregister podman-machine-default`
Then try a `podman machine init` again.
At least that was what i did, if i remember correctly.

**Comment by yacao** [comment]
thanks @gravityFlower ! After above steps can init a new podman machine! But there are additional issues in my case, can't build connection to the machine when pull image. I deleted the related .ssh file and execute "podman system connection remove *", all works now~

**Comment by allanp35** [comment]
Thanks @gravityFlower! I tried something else! You can just recreate the file podman-machine-default.json and put the same parameters on it with this template :

{
 "ConfigPath": "{Path_to_json_file}\\podman-machine-default.json",
 "Created": "2023-02-21T17:41:57.9153656+01:00",
 "ImageStream": "custom",
 "ImagePath": "{Path_to_rootfs_file}\\rootfs.tar.xz",
 "LastUp": "2023-03-15T18:14:19.4336118+01:00",
 "Name": "podman-machine-default",
 "Rootful": false, (depend on what you want)
 "IdentityPath": "{Path_to_ssh_key}\\podman-machine-default",
 "Port": {port},
 "RemoteUsername": "user",
 "Version": 3
}

You can find the port by searching it with the command "podman system connection list".

And then you can start again your machine without creating a new one!

**Comment by themr0c** [comment]
I had the same issue: 
The previous day, on a Windows 10 virtual machine, I installed Podman Destkop v0.13.0. Then Podman Desktop installed Podman v4.4.4, and created a new Podman machine. I could use Podman as expected.

Today, the `%USERPROFILE%\.config\containers\podman\machine\wsl\podman-machine-default.json` exists but is empty.

**Comment by themr0c** [comment]
Full cleanup procedure:

1. Find the name of the broken file. 

   ```powershell
   > ls .\.config\containers\podman\machine\wsl\
   ```

1. Delete the broken json file.

   ```powershell
   > rm .\.config\containers\podman\machine\wsl\podman-machine-default.json
   ```

1. List all WSL instances.

   ```powershell
   > wsl --list --all
   ```

1. Delete the Podman WSL instance.

   ```powershell
   > wsl --unregister podman-machine-default
   ```

1. Delete the remaining connection configuration.

   ```powershell
   > podman.exe system connection remove --all
   ```

Now you can initialize a new Podman machine.

I could reproduce the issue on a Windows 10 libvirt instance: 

1. Clean the VM
2. Reinitialize a Podman machine (with Podman Desktop).
3. Halt the hypervisor without first stopping or rebooting the Windows virtual machine.
4. Restart the hypervisor.
5. Start the Windows VM.
6. The `.\.config\containers\podman\machine\wsl\podman-machine-default.json` file is empty.

**Comment by n1hility** [comment]
@themr0c work is in progress on this on #18011

**Comment by themr0c** [comment]
@n1hility Thank you! That's exactly that. I could reproduce the issue today again after an unclean shutdown (press the power button on the laptop while the Windows VM is running).
