### ISSUE TITLE
Podman to run Redpanda

### ISSUE THREAD

**Issue by debu999** [containers/podman#16556]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

to run redpanda ideally we do 
```
brew install redpanda-data/tap/redpanda
rpk container start -n 3
rpk cluster info --brokers 127.0.0.1:58643,127.0.0.1:58651,127.0.0.1:58650
```
It works seamlessly with docker and docker-desktop. With Podman and podman-desktop it asks for no docker daemon. 
Can you help provide details for the sam.

**Steps to reproduce the issue:**

1. install podman/podman-desktop for mac

2. run following commands to install and run redpanda in local.

```
brew install redpanda-data/tap/redpanda
rpk container start -n 3
rpk cluster info --brokers 127.0.0.1:58643,127.0.0.1:58651,127.0.0.1:58650
```

**Describe the results you received:**
no docker daemon found

**Describe the results you expected:**
to create redpanda cluster

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
Can you set the DOCKER_HOST environment variable to point at the Podman socket, and then red panda should work.

**Comment by debu999** [comment]
I did try this
export DOCKER_HOST="`cat ~/.config/containers/containers.conf | grep -ioE "ssh://core@localhost:[0-9]+"`"
and then tried to run rpk container start -n 3
this caused the following error
echo $DOCKER_HOST                                                                                                                                                                                                             
ssh://core@localhost:49523

```
rpk container start -n 3                                                                                                                                                                                                      
Error: error during connect: Get "http://core%40localhost:49523/v1.41/containers/json?all=1&filters=%7B%22name%22%3A%7B%22%5E%2Frp-node-%5B%5C%5Cd%5D%2B%22%3Atrue%7D%7D&limit=0": dial tcp: lookup core@localhost: no such host
Usage:
  rpk container start [flags]

Flags:
  -h, --help           Help for start
  -n, --nodes uint     The number of nodes to start (default 1)
      --retries uint   The amount of times to check for the cluster before considering it unstable and exiting. (default 10)

Global Flags:
  -v, --verbose   Enable verbose logging (default: false)
```

**Comment by debu999** [comment]
please note the following actually helped to make it work.
### **user** is per system so is **port**

1. `alias docker=podman` or `sudo ln -sfv /usr/local/bin/podman /usr/local/bin/docker`
2. `podman system connection ls`  -- <-- This is to get port and user details in my case its user=501 and port=49523
```
Name                         URI                                                         Identity                                             Default
podman-machine-default       ssh://core@localhost:49523/run/user/501/podman/podman.sock  /Users/wwww/.ssh/podman-machine-default  true
podman-machine-default-root  ssh://root@localhost:49523/run/podman/podman.sock           /Users/wwww/.ssh/podman-machine-default  false
```
3. `ssh -fnNT -L/tmp/podman.sock:/run/user/501/podman/podman.sock -i ~/.ssh/podman-machine-default ssh://core@localhost:49523  -o StreamLocalBindUnlink=yes`
4. `export DOCKER_HOST='unix:///tmp/podman.sock'`

### Key Takeaway Commands to execute to make it work
* `ssh -fnNT -L/tmp/podman.sock:/run/user/ZZZ/podman/podman.sock -i ~/.ssh/podman-machine-default ssh://core@localhost:YYYYY  -o StreamLocalBindUnlink=yes`
* `export DOCKER_HOST='unix:///tmp/podman.sock'`
