### ISSUE TITLE
When a container --requires a dependency with a health check, it should block until the dependency is healthy

### ISSUE THREAD

**Issue by nivekuil** [containers/podman#16568]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I'd like a container with `--requires` to not start until the dependency container is fully started, taking into account healthcheck.

**Steps to reproduce the issue:**

1. `podman run --health-cmd "false"  -it --name test docker.io/bash`

2. `podman ps`, see that the status is `(starting)`

3. `podman run --requires test  -it docker.io/bash` succeeds, but I'd like it to block here.

This would be useful for networked mounts or service mesh sidecars for example.

**Comment by rhatdan** [comment]
Could you use a pod with an init container for this?

**Comment by nivekuil** [comment]
No, because init containers are expected to block until they exit cleanly, not start cleanly.

**Comment by rhatdan** [comment]
I think you begin to look to systemd unit files at that point.

**Comment by BonaBeavis** [comment]
@rhatdan `--sdnotify` and `podman generate systemd` look like exactly what I need. Thx.
