### ISSUE TITLE
Podman ssh connection reset by peer M1 Mac

### ISSUE THREAD

**Issue by awhitepl** [containers/podman#16579]
**Steps to reproduce the issue:**

1. run podman ps

2. I have created ssh keys. I tried enabling ssh logins to the machine.

**Describe the results you received:**
Error: failed to connect: ssh: handshake failed: read tcp [::1]:56237->[::1]:49619: read: connection reset by peer

**Describe the results you expected:**
working output.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happen every time.

**Output of `podman version`:**

```
4.3.1
```

**Output of `podman info`:**

```
Error: failed to connect: ssh: handshake failed: read tcp [::1]:56250->[::1]:49619: read: connection reset by peer
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
==> podman: stable 4.3.1 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/opt/homebrew/Cellar/podman/4.3.1 (185 files, 47.6MB) *
  Poured from bottle on 2022-11-21 at 15:09:24
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0 and GPL-3.0-or-later
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

M1 Mac.

**Comment by baude** [comment]
> 2\. I have created ssh keys. I tried enabling ssh logins to the machine.

What exactly does this mean?

**Comment by awhitepl** [comment]
> > 2. I have created ssh keys. I tried enabling ssh logins to the machine.
> 
> What exactly does this mean?

It means I already have an ssh key-pair. I also tried enabling the sshd daemon in case it was expecting ssh connections to localhost.

**Comment by baude** [comment]
if you are trying to create different users and configurations, you are welcome to but it is not something were wouild support.  we support the 'core' user and privileged.  if you do `podman machine init` and then `podman system connection ls` , you should get a good idea on how this is wired up.  Moreover, each new machine you create will use a different port for communicating between the host and machine vm.  Good luck!

**Comment by awhitepl** [comment]
I can run both of those commands fine, but I cannot build an image from a local Dockerfile via:

```
podman build -t name .    
Error: failed to connect: dial tcp [::1]:49619: connect: connection refused
```

**Comment by Luap99** [comment]
looks like a duplicate of https://github.com/containers/podman/issues/16470

**Comment by awhitepl** [comment]
I was able to resolve this by 

```podman machine rm podman-machine-default```

and launching new ones. It would be nice if someone could add this to the troubleshooting docs.
