### ISSUE TITLE
Quadlet kube network support

### ISSUE THREAD

**Issue by alexlarsson** [containers/podman#16596]
Quadlet .container files support a `Network=` key, which allows a container to e.g. share the host network, or has no network. This just maps to the `--network=...` key in podman run. 

I see podman kube play has the same option. Should we wire this up the same way, with a `Network=` key in the `[Kube]` section? I don't see any yaml options that could have similar network setup abilities.

**Comment by vrothberg** [comment]
SGTM
I am also unaware of any means to control that in K8s yaml

**Comment by Luap99** [comment]
Potential yaml support is tracked here: https://github.com/containers/podman/issues/12965
For now using --network is the only option to customize.

**Comment by ygalblum** [comment]
@Luap99 my bad, this one can be closed. I mistook it for the HostPort one #16595
