### ISSUE TITLE
podman pod mount /etc/hosts as snapshots

### ISSUE THREAD

**Issue by obarisk** [containers/podman#16598]
/kind bug

**Description**

podman pod mount `/etc/hosts` as snapshots.
when `/etc/hosts` get modified, pod should reflect the modification as well.

**Steps to reproduce the issue:**

1. create a pod by `podman pod create test-pod`

2. `podman run -it --rm --pod test-pod docker.io/library/alpine cat /etc/hosts` 

3. modify `/etc/hosts` on the host

4. `podman run -it --rm --pod test-pod docker.io/library/alpine cat /etc/hosts`

**Describe the results you received:**

output of 2 is same as `/etc/hosts` at host.

**Describe the results you expected:**

output of 4 is same as `/etc/hosts` instead of same as output of 2.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
4.3.0
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2.1.3+ds1-1_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.3, commit: unknown'
  cpuUtilization:
    idlePercent: 98.21
    systemPercent: 0.59
    userPercent: 1.2
  cpus: 12
  distribution:
    codename: bookworm
    distribution: debian
    version: unknown
  eventLogger: journald
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.0.0-4-amd64
  linkmode: dynamic
  logDriver: journald
  memFree: 73372540928
  memTotal: 101167996928
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun_1.6_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.6
      commit: 18cf2efbb8feb2b2f20e316520e0fd0b6c41ef4d
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.2.0-1_amd64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 0
  swapTotal: 0
  uptime: 6h 48m 31.00s (Approximately 0.25 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 17
    paused: 0
    running: 17
    stopped: 0
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 256000393216
  graphRootUsed: 93072404480
  graphStatus:
    Build Version: Btrfs v6.0
    Library Version: "102"
  imageCopyTmpDir: /dev/shm
  imageStore:
    number: 50
  runRoot: /run/containers/storage
  volumePath: /home/podman
version:
  APIVersion: 4.3.0
  Built: 1666750691
  BuiltTime: Wed Oct 26 10:18:11 2022
  GitCommit: ad42af94903ce4f3c3cd0693e4e17e4286bf094b
  GoVersion: go1.19.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
self built
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Been a while since we discussed this, but I'm pretty sure it's deliberate. If we allow modification based on what the host is doing, what happens if the container is also editing the file? No real sane way to merge changes made by both host and container. We do pick up changes made to `/etc/hosts` on container restart.

If you are really certain you want this, you can pass `--no-hosts` to disable Podman's management of `/etc/hosts` and then mount the host's version of the file directly into the container.
