### ISSUE TITLE
Error 'container ID cannot be mapped to a host ID' on podman pull as root with btrfs storage driver

### ISSUE THREAD

**Issue by j0057** [containers/podman#16617]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When pulling caddy:2.6.2-alpine as root on a system with btrfs storage driver, I get an error
`container ID 1001 cannot be mapped to a host ID`:

    $ sudo podman pull caddy:2.6.2-alpine
    (...snip...)
    Error: copying system image from manifest list: writing blob: adding layer with blob
    "sha256:f1747be7065842ba85f86aed65e75608dfd2f546ab9d8ecd4a8842c8f4634795": ApplyLayer stdout:
    stderr: container ID 1001 cannot be mapped to a host ID exit status 1

Notice I'm NOT running rootless here, so there should be no user namespace in play:

    $ sudo  podman unshare cat /proc/self/uid_map
    Error: please use unshare with rootless

In the sha256:f1747... blob, the file `usr/bin/caddy` is indeed owned by UID 1001:

    $ curl -sL -H "Authorization: Bearer $(curl -s 'https://auth.docker.io/token?scope=repository%3Alibrary%2Fcaddy%3Apull&service=registry.docker.io' | jq -r .access_token)" \
        https://registry-1.docker.io/v2/library/caddy/blobs/sha256:f1747be7065842ba85f86aed65e75608dfd2f546ab9d8ecd4a8842c8f4634795 \
        | tar tvz
    drwx------ 0/0               0 2022-10-14 03:43 root/
    drwx------ 0/0               0 2022-10-14 03:43 root/.step/
    -rwx------ 0/0               0 1970-01-01 01:00 root/.step/.wh..wh..opq
    drwxrwxrwt 0/0               0 2022-10-14 03:43 tmp/
    drwxr-xr-x 0/0               0 2022-08-09 10:47 usr/
    drwxr-xr-x 0/0               0 2022-10-14 03:43 usr/bin/
    -rwxr-xr-x 1001/121   40636416 2022-10-13 19:51 usr/bin/caddy

**Steps to reproduce the issue:**

Full debug log of image pull:

    $ sudo podman --log-level=debug pull docker://docker.io/library/caddy:2.6.2-alpine
    time="2022-11-24T21:27:13+01:00" level=info msg="podman filtering at log level debug"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Called pull.PersistentPreRunE(podman --log-level=debug pull docker://docker.io/library/caddy:2.6.2-alpine)"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Merged system config \"/usr/share/containers/containers.conf\""
    time="2022-11-24T21:27:13+01:00" level=debug msg="Merged system config \"/etc/containers/containers.conf\""
    time="2022-11-24T21:27:13+01:00" level=debug msg="Using conmon: \"/usr/bin/conmon\""
    time="2022-11-24T21:27:13+01:00" level=debug msg="Initializing boltdb state at /var/lib/containers/storage/libpod/bolt_state.db"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Using graph driver btrfs"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Using graph root /var/lib/containers/storage"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Using run root /run/containers/storage"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Using static dir /var/lib/containers/storage/libpod"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Using tmp dir /run/libpod"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Using volume path /var/lib/containers/storage/volumes"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Set libpod namespace to \"\""
    time="2022-11-24T21:27:13+01:00" level=debug msg="[graphdriver] trying provided driver \"btrfs\""
    time="2022-11-24T21:27:13+01:00" level=debug msg="Initializing event backend journald"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Using OCI runtime \"/usr/bin/crun\""
    time="2022-11-24T21:27:13+01:00" level=info msg="Setting parallel job count to 25"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Pulling image docker://docker.io/library/caddy:2.6.2-alpine (policy: always)"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Looking up image \"docker.io/library/caddy:2.6.2-alpine\" in local containers storage"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Normalized platform linux/amd64 to {amd64 linux  [] }"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Trying \"docker.io/library/caddy:2.6.2-alpine\" ..."
    time="2022-11-24T21:27:13+01:00" level=debug msg="Trying \"docker.io/library/caddy:2.6.2-alpine\" ..."
    time="2022-11-24T21:27:13+01:00" level=debug msg="Trying \"docker.io/library/caddy:2.6.2-alpine\" ..."
    time="2022-11-24T21:27:13+01:00" level=debug msg="Loading registries configuration \"/etc/containers/registries.conf\""
    time="2022-11-24T21:27:13+01:00" level=debug msg="Loading registries configuration \"/etc/containers/registries.conf.d/00-shortnames.conf\""
    time="2022-11-24T21:27:13+01:00" level=debug msg="Normalized platform linux/amd64 to {amd64 linux  [] }"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Attempting to pull candidate docker.io/library/caddy:2.6.2-alpine for docker.io/library/caddy:2.6.2-alpine"
    time="2022-11-24T21:27:13+01:00" level=debug msg="parsed reference into \"[btrfs@/var/lib/containers/storage+/run/containers/storage]docker.io/library/caddy:2.6.2-alpine\""
    Trying to pull docker.io/library/caddy:2.6.2-alpine...
    time="2022-11-24T21:27:13+01:00" level=debug msg="Copying source image //caddy:2.6.2-alpine to destination image [btrfs@/var/lib/containers/storage+/run/containers/storage]docker.io/library/caddy:2.6.2-alpine"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Using registries.d directory /etc/containers/registries.d"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Trying to access \"docker.io/library/caddy:2.6.2-alpine\""
    time="2022-11-24T21:27:13+01:00" level=debug msg="No credentials matching docker.io/library/caddy found in /run/containers/0/auth.json"
    time="2022-11-24T21:27:13+01:00" level=debug msg="No credentials matching docker.io/library/caddy found in /root/.config/containers/auth.json"
    time="2022-11-24T21:27:13+01:00" level=debug msg="No credentials matching docker.io/library/caddy found in /root/.docker/config.json"
    time="2022-11-24T21:27:13+01:00" level=debug msg="No credentials matching docker.io/library/caddy found in /root/.dockercfg"
    time="2022-11-24T21:27:13+01:00" level=debug msg="No credentials for docker.io/library/caddy found"
    time="2022-11-24T21:27:13+01:00" level=debug msg=" No signature storage configuration found for docker.io/library/caddy:2.6.2-alpine, using built-in default file:///var/lib/containers/sigstore"
    time="2022-11-24T21:27:13+01:00" level=debug msg="Looking for TLS certificates and private keys in /etc/docker/certs.d/docker.io"
    time="2022-11-24T21:27:13+01:00" level=debug msg="GET https://registry-1.docker.io/v2/"
    time="2022-11-24T21:27:14+01:00" level=debug msg="Ping https://registry-1.docker.io/v2/ status 401"
    time="2022-11-24T21:27:14+01:00" level=debug msg="GET https://auth.docker.io/token?scope=repository%3Alibrary%2Fcaddy%3Apull&service=registry.docker.io"
    time="2022-11-24T21:27:14+01:00" level=debug msg="GET https://registry-1.docker.io/v2/library/caddy/manifests/2.6.2-alpine"
    time="2022-11-24T21:27:14+01:00" level=debug msg="Content-Type from manifest GET is \"application/vnd.docker.distribution.manifest.list.v2+json\""
    time="2022-11-24T21:27:14+01:00" level=debug msg="Using blob info cache at /var/lib/containers/cache/blob-info-cache-v1.boltdb"
    time="2022-11-24T21:27:14+01:00" level=debug msg="Source is a manifest list; copying (only) instance sha256:7992b931b7da3cf0840dd69ea74b2c67d423faf03408da8abdc31b7590a239a7 for current system"
    time="2022-11-24T21:27:14+01:00" level=debug msg="GET https://registry-1.docker.io/v2/library/caddy/manifests/sha256:7992b931b7da3cf0840dd69ea74b2c67d423faf03408da8abdc31b7590a239a7"
    time="2022-11-24T21:27:14+01:00" level=debug msg="Content-Type from manifest GET is \"application/vnd.docker.distribution.manifest.v2+json\""
    time="2022-11-24T21:27:14+01:00" level=debug msg="IsRunningImageAllowed for image docker:docker.io/library/caddy:2.6.2-alpine"
    time="2022-11-24T21:27:14+01:00" level=debug msg=" Using default policy section"
    time="2022-11-24T21:27:14+01:00" level=debug msg=" Requirement 0: allowed"
    time="2022-11-24T21:27:14+01:00" level=debug msg="Overall: allowed"
    time="2022-11-24T21:27:14+01:00" level=debug msg="Downloading /v2/library/caddy/blobs/sha256:006d393a4e6a01f82413e41b3e0f06dfb1872d5ca6a37aba315e4ec9e2cc6c4c"
    time="2022-11-24T21:27:14+01:00" level=debug msg="GET https://registry-1.docker.io/v2/library/caddy/blobs/sha256:006d393a4e6a01f82413e41b3e0f06dfb1872d5ca6a37aba315e4ec9e2cc6c4c"
    Getting image source signatures
    time="2022-11-24T21:27:15+01:00" level=debug msg="Reading /var/lib/containers/sigstore/library/caddy@sha256=7992b931b7da3cf0840dd69ea74b2c67d423faf03408da8abdc31b7590a239a7/signature-1"
    time="2022-11-24T21:27:15+01:00" level=debug msg="Not looking for sigstore attachments: disabled by configuration"
    time="2022-11-24T21:27:15+01:00" level=debug msg="Manifest has MIME type application/vnd.docker.distribution.manifest.v2+json, ordered candidate list [application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v1+json]"
    time="2022-11-24T21:27:15+01:00" level=debug msg="... will first try using the original manifest unmodified"
    Copying blob sha256:db8ee6c4c21d12cd28fcd0e196acb8569f35518dc36c691c91b4c8ca1928bf9d
    Copying blob sha256:5625668cf98fd3e4d769f18d45f27e34fe3d085cfb9927ff7ad2cdc84d8c493f
    Copying blob sha256:213ec9aee27d8be045c6a92b7eac22c9a64b44558193775a1a7f626352392b49
    Copying blob sha256:675d09b34c5347b62625d31b2a458824240b90e51d18bcc38ad37d317e83d64c
    Copying blob sha256:f1747be7065842ba85f86aed65e75608dfd2f546ab9d8ecd4a8842c8f4634795
    time="2022-11-24T21:27:15+01:00" level=debug msg="Checking if we can reuse blob sha256:db8ee6c4c21d12cd28fcd0e196acb8569f35518dc36c691c91b4c8ca1928bf9d: general substitution = true, compression for MIME type \"application/vnd.docker.image.rootfs.diff.tar.gzip\" = true"
    time="2022-11-24T21:27:15+01:00" level=debug msg="Checking if we can reuse blob sha256:f1747be7065842ba85f86aed65e75608dfd2f546ab9d8ecd4a8842c8f4634795: general substitution = true, compression for MIME type \"application/vnd.docker.image.rootfs.diff.tar.gzip\" = true"
    time="2022-11-24T21:27:15+01:00" level=debug msg="Checking if we can reuse blob sha256:5625668cf98fd3e4d769f18d45f27e34fe3d085cfb9927ff7ad2cdc84d8c493f: general substitution = true, compression for MIME type \"application/vnd.docker.image.rootfs.diff.tar.gzip\" = true"
    time="2022-11-24T21:27:15+01:00" level=debug msg="Checking if we can reuse blob sha256:213ec9aee27d8be045c6a92b7eac22c9a64b44558193775a1a7f626352392b49: general substitution = true, compression for MIME type \"application/vnd.docker.image.rootfs.diff.tar.gzip\" = true"
    time="2022-11-24T21:27:15+01:00" level=debug msg="Checking if we can reuse blob sha256:675d09b34c5347b62625d31b2a458824240b90e51d18bcc38ad37d317e83d64c: general substitution = true, compression for MIME type \"application/vnd.docker.image.rootfs.diff.tar.gzip\" = true"
    time="2022-11-24T21:27:15+01:00" level=debug msg="Failed to retrieve partial blob: blob type not supported for partial retrieval"
    time="2022-11-24T21:27:15+01:00" level=debug msg="Downloading /v2/library/caddy/blobs/sha256:db8ee6c4c21d12cd28fcd0e196acb8569f35518dc36c691c91b4c8ca1928bf9d"
    time="2022-11-24T21:27:15+01:00" level=debug msg="GET https://registry-1.docker.io/v2/library/caddy/blobs/sha256:db8ee6c4c21d12cd28fcd0e196acb8569f35518dc36c691c91b4c8ca1928bf9d"
    time="2022-11-24T21:27:15+01:00" level=debug msg="Failed to retrieve partial blob: blob type not supported for partial retrieval"
    time="2022-11-24T21:27:15+01:00" level=debug msg="Downloading /v2/library/caddy/blobs/sha256:f1747be7065842ba85f86aed65e75608dfd2f546ab9d8ecd4a8842c8f4634795"
    time="2022-11-24T21:27:15+01:00" level=debug msg="GET https://registry-1.docker.io/v2/library/caddy/blobs/sha256:f1747be7065842ba85f86aed65e75608dfd2f546ab9d8ecd4a8842c8f4634795"
    time="2022-11-24T21:27:15+01:00" level=debug msg="Skipping blob sha256:5625668cf98fd3e4d769f18d45f27e34fe3d085cfb9927ff7ad2cdc84d8c493f (already present):"
    time="2022-11-24T21:27:15+01:00" level=debug msg="Skipping blob sha256:675d09b34c5347b62625d31b2a458824240b90e51d18bcc38ad37d317e83d64c (already present):"
    time="2022-11-24T21:27:15+01:00" level=debug msg="Skipping blob sha256:213ec9aee27d8be045c6a92b7eac22c9a64b44558193775a1a7f626352392b49 (already present):"
    time="2022-11-24T21:27:15+01:00" level=debug msg="Detected compression format gzip"
    time="2022-11-24T21:27:15+01:00" level=debug msg="Using original blob without modification"
    time="2022-11-24T21:27:15+01:00" level=debug msg="Detected compression format gzip"
    time="2022-11-24T21:27:15+01:00" level=debug msg="Using original blob without modification"
    time="2022-11-24T21:27:16+01:00" level=debug msg="Start untar layer"
    time="2022-11-24T21:27:16+01:00" level=error msg="While applying layer: ApplyLayer stdout:  stderr: container ID 1001 cannot be mapped to a host ID exit status 1"
    time="2022-11-24T21:27:16+01:00" level=debug msg="Error pulling candidate docker.io/library/caddy:2.6.2-alpine: copying system image from manifest list: writing blob: adding layer with blob \"sha256:f1747be7065842ba85f86aed65e75608dfd2f546ab9d8ecd4a8842c8f4634795\": ApplyLayer stdout:  stderr: container ID 1001 cannot be mapped to a host ID exit status 1"
    Error: copying system image from manifest list: writing blob: adding layer with blob "sha256:f1747be7065842ba85f86aed65e75608dfd2f546ab9d8ecd4a8842c8f4634795": ApplyLayer stdout:  stderr: container ID 1001 cannot be mapped to a host ID exit status 1

**Describe the results you received:**

"Container ID 1001 cannot be mapped to a host ID"

**Describe the results you expected:**

No error

**Additional information you deem important (e.g. issue happens only occasionally):**

Did not happen when system was configured to use overlayfs.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19.3
Git Commit:   814b7b003cc630bf6ab188274706c383f9fb9915-dirty
Built:        Sun Nov 20 23:32:45 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.5-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: c9f7f19eb82d5b8151fc3ba7fbbccf03fdcd0325'
  cpuUtilization:
    idlePercent: 96.49
    systemPercent: 1.18
    userPercent: 2.33
  cpus: 8
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: muon
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.0.9-arch1-1
  linkmode: dynamic
  logDriver: journald
  memFree: 20614266880
  memTotal: 33604001792
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.7-1
    path: /usr/bin/crun
    version: |-
      crun version 1.7
      commit: 40d996ea8a827981895ce22886a9bac367f87264
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.2.0-1
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 34357637120
  swapTotal: 34357637120
  uptime: 2h 43m 51.00s (Approximately 0.08 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 274875809792
  graphRootUsed: 151185039360
  graphStatus:
    Build Version: Btrfs v6.0.1
    Library Version: "102"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 4
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 1668983565
  BuiltTime: Sun Nov 20 23:32:45 2022
  GitCommit: 814b7b003cc630bf6ab188274706c383f9fb9915-dirty
  GoVersion: go1.19.3
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
$ pacman -Q podman
podman 4.3.1-2
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

-

**Comment by giuseppe** [comment]
it works for me on Rawhide with btrfs.

I don't see why it should do any mapping.  Have you performed any change under `/etc/containers`?

Could you run podman under strace and attach here the log `sudo strace -f -v -s 1000 -Z podman pull ...` ?

**Comment by j0057** [comment]
After `rm -rf /var/lib/containers/{cache,storage}/*` the problem went away, I can now pull the image fine. This is the strace of when it was still in the broken state: [podman-pull-strace-221125.log](https://github.com/containers/podman/files/10095106/podman-pull-strace-221125.log). 

The configurations I have under `/etc/container` are:

- `storage.conf`: `storage.driver` = `"btrfs"`
- `registries.conf`: `unqualified-search-registries` = `["docker.io"]`

**Comment by j0057** [comment]
I'm still getting this on another host, even after nuking all of `/var/lib/containers/storage` and doing a reboot for good measure: [podman-pull-strace-221126-2.log](https://github.com/containers/podman/files/10096618/podman-pull-strace-221126-2.log).

**Comment by j0057** [comment]
I found something strange; I noticed podman is using UID 113000, which I recognize because (along with 22 other entries) I have this in `/etc/subuid` and `/etc/subgid`:

    minecraft:113000:1000

This because I  create a container using the `--subuidname` and `--subgidname` options:

    podman container create --name minecraft --conmon-pidfile /run/podman/minecraft.pid --log-driver journald --log-opt tag={{.Name}} --net ... --ip ... --dns ... --dns-search ... --subuidname minecraft --subgidname minecraft --volume /srv/minecraft:/srv my.registry.io/minecraft:2209181011-1.19.2

When filtering the strace for %process and %file syscalls, I see this `execve`: 

    [pid  9049] execve("/proc/self/exe", ["storage-applyLayer", "/var/lib/containers/storage/btrfs/subvolumes/70fe049af1bcc2c7eb8f1f6fdd4c67b93d68cd95ffc620c539df67feb3b259f9"], ["LANG=en_US.UTF-8", "TERM=xterm-256color", "PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/jjm/.local/bin:/home/jjm/.cargo/bin", "MAIL=/var/mail/root", "LOGNAME=root", "USER=root", "HOME=/root", "SHELL=/bin/bash", "SUDO_COMMAND=/usr/bin/strace -e %process,%file -f -v -s 1048576 podman pull image docker.io/library/caddy:2.6.2-alpine", "SUDO_USER=jjm", "SUDO_UID=1000", "SUDO_GID=1000", "EDITOR=vim", "TMPDIR=/var/tmp", "OPT={\"IncludeFiles\":null,\"ExcludePatterns\":[],\"Compression\":0,\"NoLchown\":false,\"UIDMaps\":[{\"container_id\":0,\"host_id\":113000,\"size\":1000}],\"GIDMaps\":[{\"container_id\":0,\"host_id\":113000,\"size\":1000}],\"IgnoreChownErrors\":false,\"ChownOpts\":null,\"IncludeSourceDir\":false,\"WhiteoutFormat\":0,\"WhiteoutData\":null,\"NoOverwriteDirNonDir\":false,\"RebaseNames\":null,\"InUserNS\":false,\"CopyPass\":false,\"ForceMask\":null}"] <unfinished ...>
    [pid  9045] <... clone resumed>)        = 9049
    [pid  9049] <... execve resumed>)       = 0

So these JSON keys are being passed in the OPT variable in the environment array:

    ... \"UIDMaps\":[{\"container_id\":0,\"host_id\":113000,\"size\":1000}],
        \"GIDMaps\":[{\"container_id\":0,\"host_id\":113000,\"size\":1000}] ...

This also happens if the subuid/subgid files don't exist. So I'm not really sure where podman is picking up the uidmap and gidmap here.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
do you have libsubid installed?

Try running `getsubids minecraft`.  What do you get?

**Comment by j0057** [comment]
I get `0: minecraft 113000 1000` – still not sure why that is relevant when doing a rootful `podman pull` for docker.io/library/caddy:2.6.2-alpine. They might share a base layer?

**Comment by giuseppe** [comment]
do you have changed anything in `containers.conf`?

**Comment by giuseppe** [comment]
can you show the output of `sudo podman --log-level debug pull docker.io/library/caddy:2.6.2-alpine` ?

**Comment by j0057** [comment]
Hey @giuseppe, sorry for the delay, I did some more experimenting and managed to reproduce the problem with publicly available base images, and found a way as well to work around the problem. Here is the log you requested: [podman-pull-221130.log](https://github.com/containers/podman/files/10139633/podman-pull-221130.log).

As for the configs -- in `storage.conf`, I set `storage.driver` to `btrfs`; in `containers.conf` I have `unqualified-search-registries` set to `["docker.io"]`.

To reproduce the error with publicly available base images, do these steps as root:

1. Stop and destroy all containers
2. Create a clean slate: `rm -rf /var/lib/containers/{cache,storage}`
3. Create an alpine:3.16 container: `podman container create --uidmap 0:113000:1000 --gidmap 0:113000:1000 --name alpine docker://docker.io/library/alpine:3.16.3`
4. Create a caddy:2.6.2-alpine container: `podman container create --uidmap 0:122000:1000 --gidmap 0:122000:1000 --name caddy docker://docker.io/library/caddy:2.6.2-alpine`
5. The `/var/lib/containers/storage` tree now looks like this: [podman-storage-after-create-211202.log](https://github.com/containers/podman/files/10139770/podman-storage-after-create-211202.log)

And see that step 4 fails with `ERRO[0002] While applying layer: ApplyLayer stdout:  stderr: container ID 1001 cannot be mapped to a host ID exit status 1`.

By separately pulling the images first, the containers get created successfully:

1. Again stop and destroy all containers
2. Again create a clean slate: `rm -rf /var/lib/containers/{cache,storage}`
3. Pull both containers: `podman image pull docker://docker.io/library/{alpine:3.16.3,caddy:2.6.2-alpine}`
4. The `/var/lib/containers/storage` tree now looks like this: [podman-storage-after-pull-211202.log](https://github.com/containers/podman/files/10139772/podman-storage-after-pull-211202.log)
5. Create an alpine:3.16 container: `podman container create --uidmap 0:113000:1000 --gidmap 0:113000:1000 --name alpine docker://docker.io/library/alpine:3.16.3`
6. Create a caddy:2.6.2-alpine container: `podman container create --uidmap 0:122000:1000 --gidmap 0:122000:1000 --name caddy docker://docker.io/library/caddy:2.6.2-alpine`
7. The `/var/lib/containers/storage` tree now looks like this: [podman-storage-after-pull-then-create-211202.log](https://github.com/containers/podman/files/10139775/podman-storage-after-pull-then-create-211202.log)

Looking at what's different between the two scenarios, there's a difference in terms of ownership in the directories under `/var/lib/containers/storage/btrfs`, I attached the output of `tree -u -L 3` at different stages during the repros.

**Comment by giuseppe** [comment]
so I looked into the code, when we chown an existing layer we on purpose map not existing IDs to the overflow ID, the same code path is used for BTRFS.

And it is me to blame for such change : https://github.com/containers/storage/commit/28c166fa18ee3ad9286cc5016d01a38c5baac10c

So I am closing since it works as expected
