### ISSUE TITLE
Provide both x86_64 and aarch64 binaries for podman-remote-linux

### ISSUE THREAD

**Issue by cfergeau** [containers/podman#16612]
If I go to https://github.com/containers/podman/releases/tag/v4.3.1 there are aarch64/arm64 and/or amd64 files for macos and Windows, and a lone podman-remote-static.tar.gz file. This one was an aarch64 binary for the 4.3.0 release, and is a x86_64 binary for the 4.3.1 release. Can it be renamed to podman-remote-static-linux_amd64.tar.gz, and can an _arm64 binary be provided alongside of it? 

Also note the inconsistent arch names for macOS: 
podman-installer-macos-aarch64.pkg and podman-remote-release-darwin_arm64.zip

**Comment by gbraad** [comment]
@mheon @ashley-cui FYI

**Comment by rhatdan** [comment]
@cfergeau interested in opening a PR?
