### ISSUE TITLE
rootless podman ERRO[0000] error joining network namespace for container as container restart fails post vm shutdown

### ISSUE THREAD

**Issue by ijewelmas** [containers/podman#16615]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I am running a container using podman 4.1.1 on RHEL 8.6, whenever the system shuts down and restarts the next day container fails to come up automatically in-spite of the restart_policy set to always.

**Steps to reproduce the issue:**

1.  use the ansible module containers.podman.podman_container to spin a container 
tasks:
  -name: install container using podman
   container.podman.podman_container:
     name: x
     image: "x"
     state: started
     restart_policy: "always"
3. shutdown the vm where container runs 

**Describe the results you received:**
error joining network namespace for container: error retrieving network namespace at /tmp/podman-run-1000/netns/XXXX: unknown fs magic: 58465342.

**Describe the results you expected:**
podman should be able to list containers using podman ps -a command irrespective of it being up or down.
Since restart_policy is always , container should be able to come up

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
Client:            Podman Engine
Version:         4.1.1
API Version:   4.1.1
Go Version:    go1.17.7
os/Arch:          linux/amd64

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**
podman-4.1.1-7.module+el8.6.0+16889+9f154fa9.x86_64

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide? (https://github.com/containers/podman/blob/main/troubleshooting.md)**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Azure VM

**Comment by rhatdan** [comment]
This looks like a RHEL bugzilla, please open a Bug not an issue.  Don't know if this is fixed in upstream or not, but we would tell you to verify if it is fixed in the main branch or the current release 4.3.1
