### ISSUE TITLE
Uninstalling Podman in Windows doesn't unregister the WSL2 distribution

### ISSUE THREAD

**Issue by luisdanielmesa** [containers/podman#16635]
I tried using Podman for Windows to connect to the Openshift Local cluster I have in my machine. It didn't work, and I don't really care... I got Docker working, so I can push images to the image-registry. I uninstalled Podman, but the distribution was not unregistered from WSL2.

Reproduce:
install
podman machine init
uninstall
wsl --list

I manually removed the distribution, so I don't really have a problem, but I'm creating this issue to make sure someone at least thinks about cleaning after themselves when uninstalling Podman. *wagging finger*

**Comment by rhatdan** [comment]
@n1hility PTAL

**Comment by n1hility** [comment]
Thanks for the report. This is intentional that we do not destroy user data. If you want to remove the the machine before uninstalling you can do `podman machine rm` first

**Comment by luisdanielmesa** [comment]
> Thanks for the report. This is intentional that we do not destroy user data. If you want to remove the the machine before uninstalling you can do `podman machine rm` first

Perfect, makes more sense. Sorry for the false positive.
