### ISSUE TITLE
catatonit crashes/ends itself after several minutes of running

### ISSUE THREAD

**Issue by martinky82** [containers/podman#16647]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Trying to deploy the ABRT Analytics, the system got into state when the infra container (/catatonit -P) dies/ends for no obvious reason after ~ 2-5 minutes of (re)starting the pod. The catatonit process is so simple, that it croaks silently and there is no logs, no output, no nothing for me to investigate the issue.

I even tried to purge the pod, its volume, all of the podman packages and all of the *podman* files from the system to no avail.

**Steps to reproduce the issue:**

1. run the pod

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19.2
Built:        Sat Nov 26 18:52:32 2022
OS/Arch:      linux/amd64

**Output of `podman info`:**

host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.2-2.el9_0.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.2, commit: 1ed53517f446a779f9d0edafe090ce821a41e255'
  cpuUtilization:
    idlePercent: 86.64
    systemPercent: 2.05
    userPercent: 11.31
  cpus: 16
  distribution:
    distribution: '"rhel"'
    version: "9.0"
  eventLogger: journald
  hostname: faf.lab.eng.brq.redhat.com
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.0-70.30.1.el9_0.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 61518868480
  memTotal: 67059560448
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.5-2.el9_0.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.5
      commit: c381048530aa750495cf502ddb7181f2ded5b400
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.el9_0.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 33755754496
  swapTotal: 33755754496
  uptime: 149h 22m 49.00s (Approximately 6.21 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 2
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 268409241600
  graphRootUsed: 149894328320
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 3
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 1669485152
  BuiltTime: Sat Nov 26 18:52:32 2022
  GitCommit: ""
  GoVersion: go1.19.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

podman-debugsource-4.3.1-2.el9.x86_64
podman-debuginfo-4.3.1-2.el9.x86_64
podman-catatonit-4.3.1-2.el9.x86_64
podman-4.3.1-2.el9.x86_64
podman-gvproxy-4.3.1-2.el9.x86_64
podman-tests-4.3.1-2.el9.x86_64
podman-plugins-4.3.1-2.el9.x86_64
podman-docker-4.3.1-2.el9.noarch
podman-catatonit-debuginfo-4.3.1-2.el9.x86_64
podman-gvproxy-debuginfo-4.3.1-2.el9.x86_64
podman-plugins-debuginfo-4.3.1-2.el9.x86_64
podman-remote-debuginfo-4.3.1-2.el9.x86_64
podman-remote-4.3.1-2.el9.x86_64

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

Yes

IIUC, 4.3.1 is the latest RELEASED version.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical host

**Comment by mheon** [comment]
Can you provide the commands used to reproduce?

Also, I assume you're seeing the container in question immediately exit after its init dies? Or are you seeing some other symptom?

**Comment by martinky82** [comment]
podman pod stop faf-pod
podman pod rm faf-pod
podman system reset
rm /etc/containers/storage.conf
podman system reset
podman volume create faf-volume
podman pod create -p 5432:5432 -p 6379:6379 -p 8080:8080 --name faf-pod
podman run --pod faf-pod -v faf-volume:/var/lib/pgsql/data -e POSTGRESQL_ADMIN_PASSWORD=scrt --name db -dit quay.io/abrt/faf-db
podman run --pod faf-pod --name faf-7b21d9d  -dit -e PGHOST=localhost -e PGUSER=faf -e PGPASSWORD=scrt -e PGPORT=5432 -e PGDATABASE=faf quay.io/fedoraci/faf:7b21d9d

Yes, the container in question exists (no longer being in podman ps, in podman stats all the numbers are 0). With it, all the shared resources in the pod are lost, including network. The only remedy is podman pod restart, but it is quite shortlived as catatonit dies again in several minutes.

I had the service running on the host in the pod for quite a while, but last week after redeploying it to get to the latest version of the abrt/faf container, this issue started. That being said, I strongly suspects there is something in the environment that causes the problem, but as catatonit itself logs/outputs exactly NOTHING I am not even able to say if it exits properly or crashes, let alone to get any hint as to what could possibly be the culprit. I am trying to fix is to no avail for so long now, I am considering OS reinstall on the host to get a clean environment.

**Comment by martinky82** [comment]
This is what appears in the dmesg when catatonit croaks.

[10215.169505] podman0: port 1(veth0) entered disabled state
[10215.175815] device veth0 left promiscuous mode
[10215.180792] podman0: port 1(veth0) entered disabled state

**Comment by mheon** [comment]
That's perfectly normal/expected - Podman's just tearing down the container's network after it exited.

Are you sure nothing is sending catatonit a signal that might cause it to stop the container?

**Comment by martinky82** [comment]
Well, I just start the pod and do exactly nothing with it - and it dies. Every single time. Sometimes one or both of the other containers die, sometimes not. Will try on another host.

**Comment by rhatdan** [comment]
Could this be us executing a random catatonit?

**Comment by martinky82** [comment]
I'm not sure I understand the question...

**Comment by rhatdan** [comment]
Do you only have one catatonit on your system?  Is podman executing it?

**Comment by martinky82** [comment]
There's only on podman-catatonit package installed and only one pod set up and run. I did complete podman wipeout & reinstall twice or so.

**Comment by martinky82** [comment]
[root@faf /]# find . -name *catatonit*
./root/podman/podman-catatonit-4.3.1-3.el9.x86_64.rpm
./root/podman/podman-catatonit-debuginfo-4.3.1-3.el9.x86_64.rpm
./var/lib/containers/storage/overlay/6c9122a608f8f286d21989a63c0057c71e95c3c55cd3a1d0bea284a6b60192e4/diff/catatonit
./usr/lib/debug/usr/libexec/catatonit
./usr/lib/debug/usr/libexec/catatonit/catatonit-4.3.1-3.el9.x86_64.debug
./usr/share/doc/podman-catatonit
./usr/share/licenses/podman-catatonit
./usr/libexec/catatonit
./usr/libexec/catatonit/catatonit
./usr/libexec/podman/catatonit
./usr/src/debug/podman-4.3.1-3.el9.x86_64/catatonit-0.1.7
./usr/src/debug/podman-4.3.1-3.el9.x86_64/catatonit-0.1.7/catatonit.c
[root@faf /]# ll ./usr/libexec/catatonit
total 788
-rwxr-xr-x. 1 root root 806072 Nov 28 13:33 catatonit
[root@faf /]# ll ./usr/libexec/catatonit/catatonit 
-rwxr-xr-x. 1 root root 806072 Nov 28 13:33 ./usr/libexec/catatonit/catatonit
[root@faf /]# ll ./usr/libexec/podman/catatonit
lrwxrwxrwx. 1 root root 32 Nov 28 13:33 ./usr/libexec/podman/catatonit -> /usr/libexec/catatonit/catatonit
[root@faf /]#

**Comment by martinky82** [comment]
So, i the end I tried to redeploy the pod under a different name and it works. Started an hour ago, infra container of the pod is running as expected.

**Comment by rhatdan** [comment]
I have no idea what is going on but it feels like a local issue. Closing, but we can continue the conversation here.

**Comment by martinky82** [comment]
Well, I have no idea either but what I would certainly except would be for catatonit to actually log, escpecially when the pod gets restarted with --log-level=debug. Because it logs exactly NOTHING AT ALL, investigation such issue is virtually impossible and the user is let at mercy of the try-blindly-and-fail-or-succeed approach.
