### ISSUE TITLE
Disable healthcheck, missing global config option for systems without systemd

### ISSUE THREAD

**Issue by mluhmann** [containers/podman#16644]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I have a custom linux build on yocto without systemd and I had to update to podman v4.2.1. But now I am getting lots of errors due to missing systemd like "unable to get systemd connection to add healthchecks". I can work around this with the --no-healthcheck option or disable it in my compose files. But this isn't convenient for legacy containers and developers working with this linux.

**Steps to reproduce the issue:**

Just start any container on a system without systemd.

**Describe the results you received:**

Bunch of errors regarding systemd connection not possible.

**Describe the results you expected:**

Disable healthcheck for my whole linux yocto build by a global config option. No need for --no-healthcheck parameter or comparable for every container.

**Output of `podman version`:**

Client:       Podman Engine
Version:      4.2.1-dev
API Version:  4.2.1-dev
Go Version:   go1.17.13
Git Commit:   754ec89a8a185d308ca5ed08afaf34d6cbda08da
Built:        Tue Aug 16 08:54:44 2022
OS/Arch:      linux/arm

**Output of `podman info`:**

host:
  arch: arm
  buildahVersion: 1.27.0
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - net_prio
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: 4c41ec2a215c502ad6c38ea255ac1082fa1d381d'
  cpuUtilization:
    idlePercent: 93.96
    systemPercent: 2.79
    userPercent: 3.25
  cpus: 2
  distribution:
    distribution: unknown
    version: unknown
  eventLogger: file
  hostname: host
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.193-rt74-pxc
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 126357504
  memTotal: 512741376
  networkBackend: cni
  ociRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.1.2+dev
      commit: v1.1.2-9-gb507e2da-dirty
      spec: 1.0.2-dev
      go: go1.17.13
      libseccomp: 2.5.3
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: unconfined
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.2.0-beta.0+dev
      commit: unknown
      libslirp: 4.6.1.55-888d
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 2h 28m 21.00s (Approximately 0.08 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  '*.docker.io':
    Blocked: false
    Insecure: false
    Location: ""
    MirrorByDigestOnly: false
    Mirrors:
    - Insecure: false
      Location: mirror.gcr.io
      PullFromMirror: ""
    - Insecure: false
      Location: quay.io/libpod
      PullFromMirror: ""
    Prefix: '*.docker.io'
    PullFromMirror: ""
  '*.fedoraproject.org':
    Blocked: false
    Insecure: false
    Location: registry.fedoraproject.org
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: '*.fedoraproject.org'
    PullFromMirror: ""
  localhost:5000:
    Blocked: false
    Insecure: true
    Location: localhost:5000
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: localhost:5000
    PullFromMirror: ""
  search:
  - docker.io
  - quay.io
  - registry.fedoraproject.org
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 0
    stopped: 3
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /media/rfs/rw/data/system/containers
  graphRootAllocated: 7688126464
  graphRootUsed: 778731520
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /media/rfs/rw/data/system/containers/
  imageStore:
    number: 2
  runRoot: /media/rfs/rw/data/system/containers_temp
  volumePath: /media/rfs/rw/data/system/containers/volumes
version:
  APIVersion: 4.2.1-dev
  Built: 1660640084
  BuiltTime: Tue Aug 16 08:54:44 2022
  GitCommit: 754ec89a8a185d308ca5ed08afaf34d6cbda08da
  GoVersion: go1.17.13
  Os: linux
  OsArch: linux/arm
  Version: 4.2.1-dev

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

-

**Comment by vrothberg** [comment]
> However I wonder why this should be needed in the first place? IMO if there is no systemd present we should just ignore healthchecks.

I agree, and also like the idea of the build tag.

**Comment by davdr** [comment]
Also relevant when running Podman under WSL2 (other then Podman's own podman-machine, which adds a separate namespace to be able to run sytemd when you normally can't).
