### ISSUE TITLE
No output when using `docker run hello-world` on Mac/Windows

### ISSUE THREAD

**Issue by rcsilva83** [containers/podman#16656]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

On Windows, when I run `docker run hello-world` with podman backend, I get no output. If I switch to Docker Desktop backend, I get the correct output.

BTW, `podman run hello-world` shows me the output too.

**Steps to reproduce the issue:**

1. Open a CMD or Powershell

2. Run `docker run hello-world`

**Describe the results you received:**

Empty output.

**Describe the results you expected:**

The "Hello from Docker!" message is printed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.3.0
API Version:  4.3.0
Go Version:   go1.18.7
Git Commit:   ad42af94903ce4f3c3cd0693e4e17e4286bf094b
Built:        Wed Oct 19 14:53:21 2022
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.3.0
API Version:  4.3.0
Go Version:   go1.18.7
Built:        Fri Oct 21 05:16:35 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.4-3.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: '
  cpuUtilization:
    idlePercent: 98.93
    systemPercent: 0.66
    userPercent: 0.42
  cpus: 4
  distribution:
    distribution: fedora
    variant: container
    version: "36"
  eventLogger: journald
  hostname: Lenovo-PC
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: [5.10.102.1](https://5.10.102.1/)-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 6296551424
  memTotal: 6580776960
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.7-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.7
      commit: 40d996ea8a827981895ce22886a9bac367f87264
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 2147483648
  swapTotal: 2147483648
  uptime: 0h 6m 37.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - [registry.fedoraproject.org](https://registry.fedoraproject.org/)
  - [registry.access.redhat.com](https://registry.access.redhat.com/)
  - [docker.io](https://docker.io/)
  - [quay.io](https://quay.io/)
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 0
    stopped: 5
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 269490393088
  graphRootUsed: 753303552
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 3
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.0
  Built: 1666340195
  BuiltTime: Fri Oct 21 05:16:35 2022
  GitCommit: ""
  GoVersion: go1.18.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

Podman installed by Podman Desktop.

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by jakegt1** [comment]
I have tried this myself (I have docker CE windows containers installed at the same time, providing me docker cli) and it worked fine for me. 

Where are you getting the docker cli from?

**Comment by rcsilva83** [comment]
I'm using the Docker CLI shipped with Docker Desktop. Where did you get yours?

**Comment by jakegt1** [comment]
Docker CE for windows containers. 

I expect the docker cli for docker desktop is some sort of wrapper around docker cli that works only with docker desktop. If your purpose is for testing out podman desktop while still using "docker", you may be better off setting an alias.

However I don't know enough about how docker desktop and podman desktop integrates together, so maybe worth waiting for someone else to chime in.

**Comment by rcsilva83** [comment]
> Docker CE for windows containers.

@jakegt1, where can I download it? I couldn't find.

**Comment by rhatdan** [comment]
@n1hility PTAL

**Comment by n1hility** [comment]
will take a look. a brief check shows the data is on the wire. Problem seems to affect mac as well, but not moby on linux, perhaps a bug in specific versions. 

@rcsilva83 for a workaround you can do `docker run -i hello-world`

**Comment by n1hility** [comment]
Fix is done but is waiting on a release of gvproxy and merge of a corresponding update PR for the release once created. Tracking issue for the gvproxy release i here:
https://github.com/containers/gvisor-tap-vsock/issues/163

**Comment by n1hility** [comment]
@rcsilva83 thanks, happy new year! I'll get a PR in updating this soon

**Comment by n1hility** [comment]
The only thing that’s left on this one is that we need to update the brew formula as part of the bump to 4.4 cc @ashley-cui FYI

**Comment by rcsilva83** [comment]
I just tested with Podman 4.4.1 on Windows and the problem persists.

**Comment by rhatdan** [comment]
Did it have the new version of gvisor?

**Comment by rhatdan** [comment]
Can  you go into the machine and check the rpm version?

**Comment by rcsilva83** [comment]
The `golang-gvisor` package isn't installed on the podman-machine-default distro. The available version on the repository is 20211129.0.

**Comment by rhatdan** [comment]
I am no expert, but I would figure this was created in 2021-11-29
Not too recent.
@n1hility @lsm5 @baude WDYT?

**Comment by lsm5** [comment]
> Can you go into the machine and check the rpm version?

given that it's a Windows env, it might be getting gvisor from ubuntu / wsl. Maybe their maintainers need to be pinged about this.

**Comment by n1hility** [comment]
This issue should be long resolved. The relevant fixed process that contained the gvisor-tap-vsock update is win-sshproxy.exe on the Windows side, and is included / installed by the installer (or if you are doing a manual installation using  the client zips, you may want to make sure you have copied all binaries over as part of the install as well).

I just doubled checked a clean install of 4.6 and everything looks good there. If this is still happening somehow, feel free to reopen, and any tips on how to reproduce would be appreciated thanks!

**Comment by rcsilva83** [comment]
Hi, @n1hility ! Just tested and it is working!

Thank you very much for the effort!
