### ISSUE TITLE
set insecure registry in macos host

### ISSUE THREAD

**Issue by wodadehencou** [containers/podman#16664]
/macos /Question

**Description**
Help of insecure registry setting in macos.

I use a self registry, ip = 10.206.67.226, and the tls certifcate can not be verified.

I want to use `podman login 10.206.67.226` without `--tls-verify=false` setting in macos (host machine).

I edit config file `.config/containers/registries.conf` in podman machine, and I can use `docker login 10.206.67.226` in podman machine.

```
[[registry]]
location = "10.206.67.226"
insecure = true
```

But I still can not just `podman login` in macos without `--tls-verify=false`.

I wonder which config file I can modify in macos to enable insecure registry .

**Comment by wodadehencou** [comment]
I find the config file is also `${HOME}/.config/containers/registries.conf` in macos.

**Comment by chriswolske** [comment]
For what it's worth: when I had this same problem, it wasn't enough to create/edit registries.conf in my ${HOME}, I needed to add that to .config/containers/ _**inside the podman machine**_. See #16532

**Comment by rhatdan** [comment]
Correct. With podman remote (Podman on MAC and WIndows) you need to configure the registries.conf, containers.conf and storage.conf on the server side, usually within the podman machine.
