### ISSUE TITLE
Describe the use of the --image-path for podman machine init

### ISSUE THREAD

**Issue by gbraad** [containers/podman#16670]
You can use a downloaded image for use with `podman machine init`. This can help with running the setup step in an air-gapped situation.

https://github.com/containers/podman-desktop/issues/185#issuecomment-1330683199

For example:

 1. download a `rootfs.tar.xz` from a release at https://github.com/containers/podman-wsl-fedora/releases/
 2. run `podman machine init --image-path` pointing to this image

**Comment by vrothberg** [comment]
Can you elaborate?  The man page includes docs for the flag so I am not sure what to do.

> --image-path
    Fully qualified path or URL to the VM image.  Can also be set to testing, next, or stable to pull down default image.  Defaults to testing.

**Comment by rhatdan** [comment]
Since we never heard back, I am closing.
