### ISSUE TITLE
Incomplete Instructions

### ISSUE THREAD

**Issue by DonRichards** [containers/podman#16691]
Reviewing this page https://github.com/containers/podman/blob/main/docs/tutorials/mac_experimental.md

**Description**
The start of the page says to fetch 3 items with no references to them.
```makrdown
You must obtain a compressed tarball that contains the following:
- a qcow image
- a podman binary
- a gvproxy binary
```

**Describe the results you received:**
No links founds

**Describe the results you expected:**
Each of these should link to their respective files or a page where they can be located.
```makrdown
You must obtain a compressed tarball that contains the following:
- a [qcow image}(#)
- a [podman binary}(#)
- a [gvproxy binary}(#)
```

**Output of `podman version`:**
N/A
**Output of `podman info`:**
N/A
**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**
N/A
**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**
No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
N/A

**Comment by vrothberg** [comment]
Thanks for reaching out, @DonRichards!

@ashley-cui PTAL

**Comment by Luap99** [comment]
This doc looks completely out of date, please refer to https://podman.io/getting-started/installation#macos

I think we can just remove the doc.

**Comment by DonRichards** [comment]
@Luap99 Does the link you provided cover M1 chips?

**Comment by DonRichards** [comment]
Thanks

**Comment by rhatdan** [comment]
Should we just remove that document?

**Comment by vrothberg** [comment]
@TomSweeneyRedHat @baude WDYT?

**Comment by mhemken-vts** [comment]
> Yes podman machine supports both M1/2 and Intel macs.

The thing is... I'm on an M1 and it still errors whenever I try to install podman.

**Comment by baude** [comment]
@mhemken-vts create a new issue please

**Comment by rhatdan** [comment]
Since this page no longer exists, I am closing.
