### ISSUE TITLE
Building documentation with target OS and native arch looks incorrect

### ISSUE THREAD

**Issue by arixmkii** [containers/podman#16702]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

For release archives `Makefile` builds documentation targeting the selected OS, but using native arch. This doesn't look correct, because it can result with the pair, which just doesn't exist. I can't come up with the currently broken option, but in future if Intel Macs will become unsupported it will not be possible to compile docs on Linux_amd64 for Darwin_arm64, though Darwin_arm64 will be an absolutely valid option.

Currently it manifested, when I tried to build Windows-amd64 on M1 mac, but forgot to fix compilation issues for Windows-arm64.

Discovered trying to build installers for experiment in https://github.com/containers/podman/issues/13006

**Steps to reproduce the issue:**

1. Source code https://github.com/containers/podman/blob/main/Makefile#L689

2. Source code https://github.com/containers/podman/blob/main/Makefile#L710

**Describe the results you received:**

Didn't compile for windows-amd64 on M1 mac, when changes were missing only for windows-arm64

**Describe the results you expected:**

Compile fine for windows-amd64,  but fails for windows-arm64

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
commit: c0f9a923e2011a44c1d7ec752a9b6105905dfe95
```

**Output of `podman info`:**

```
Intentionally omitted
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
Intentionally omitted
```

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Cross-compilation build procedure

**Comment by vrothberg** [comment]
@cevich PTAL

**Comment by cevich** [comment]
As you've (no doubt already) seen, this area of the Makefile is super complex.  The core problem is that we need a binary build of podman that can run on the build-host.  This is needed to generate documentation...which is included in all the release targets :confounded: 

So I'm not surprised you've found trouble here, but unfortunately I have no idea how to (easily) fix it.  Perhaps something could be done with the documentation-building script such that it doesn't require podman, but instead some intermediate binary just for generating docs?  Similar to what we do with `test/version.go`?

I'm open to any/all suggestions.

**Comment by arixmkii** [comment]
Actually my bad. Line 689 is ok (tgz path is not suited for windows and only uses native OS). So, it will be NativeOS + NativeArch, which is naturally supported.

Issue is another case https://github.com/containers/podman/blob/main/Makefile#L710

First we read GOOS from https://github.com/containers/podman/blob/main/Makefile#L706, so this will not be Native, and will not result in a binary, which can run on this host. It should allow us to use GOARCH (read from the same input here https://github.com/containers/podman/blob/main/Makefile#L707) in https://github.com/containers/podman/blob/main/Makefile#L710 instead of NATIVE_ARCH. 

Now I think that $NATIVE_ARCH is a copy-paste like error from tgz buils. 

Replacing https://github.com/containers/podman/blob/main/Makefile#L710 with line below looks legit (or at least harmless) for me.  
```make
	$(MAKE) GOOS=$(GOOS) GOARCH=$(GOARCH) \
```

Runnable binary inside this docs build step https://github.com/containers/podman/blob/main/Makefile#L482 explicitly requesting native GOOS.

But I totally agree, that thing is really complicated.

**Comment by arixmkii** [comment]
@cevich  I will prepare a PR for some other things, so, might add the change mentioned above there and then tag you in review.

**Comment by cevich** [comment]
Sounds good, and thanks for taking the initiative.  I only remember enough of this area of the Makefile to scare me away from wanting to touch it ever again :laughing:
