### ISSUE TITLE
[M1] Podman machine does not seem to run window-less anymore

### ISSUE THREAD

**Issue by mikeymop** [containers/podman#16706]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Recently I have been unable to connect to `podman machine`. I think this is correlated to a recent macos update but I am not sure.
I have been looking through the different Mac M1 issues that have come up recently. I also have been having an issue where `podman machine start` just stops at the 'waiting on VM' step.

I have seen the previous suggestions to
```
podman machine rm -f
podman machine init
podman machine start
```

And this also got stuck at the same step.

I eventually saw that if I
```
podman machine start --loglevel=debug
```
from a fresh vm that a qemu window opens and boots the Fedora coreos image.

So long as I keep this window open I can continue to connect to the podman machine.

**Steps to reproduce the issue:**

1. `podman machine rm -f`

2. `podman machine init`

3. `podman machine start --loglevel=debug`

4. Close the qemu window

5. `podman machine ssh` fails now

**Describe the results you expected:**

I expected that `podman machine start` would succeed as it used to my upgrade to Macos `12.6.1`.

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.18.3
Built:        Tue Jun 14 16:12:46 2022
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19.2
Built:        Fri Nov 11 10:00:31 2022
OS/Arch:      linux/arm64
```

**Output of `podman info`:**

```
host:
  arch: arm64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.5-1.fc37.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 98.05
    systemPercent: 0.83
    userPercent: 1.11
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "37"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 469043561
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.0.9-300.fc37.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 496168960
  memTotal: 2049789952
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.7-1.fc37.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.7
      commit: 40d996ea8a827981895ce22886a9bac367f87264
      rundir: /run/user/469043561/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/469043561/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.aarch64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 1h 50m 30.00s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 4424773632
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/user/469043561/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 1668178831
  BuiltTime: Fri Nov 11 10:00:31 2022
  GitCommit: ""
  GoVersion: go1.19.2
  Os: linux
  OsArch: linux/arm64
  Version: 4.3.1
```

**Package info (`brew info podman`):**

```
podman: stable 4.1.1 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/opt/homebrew/Cellar/podman/4.1.1 (174 files, 46.4MB) *
  Poured from bottle on 2022-06-24 at 08:58:00
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0
==> Dependencies
Build: go ✔, go-md2man ✘
Required: qemu ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
zsh completions have been installed to:
  /opt/homebrew/share/zsh/site-functions
```

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

No, I tried to do this through homebrew but ran into some issues I think are specific to my machine configuration.

**Comment by arixmkii** [comment]
> Close the qemu window

This will stop virtual machine. You can try

1. `podman machine rm -f`
2. `podman machine init`
3. `podman machine start --loglevel=debug`
4. verify that podman is operational
5. `podman machine stop` - stop the machine (the window will disappear)
6. `podman machine start` - start the same machine, but w/o QEMU window
7. check if podman works now

What it tries to achieve - allows you to visually follow the first run and verify that VM is ready (there is some ignition magic running on first launch, so, it is slower) and then start VM as usual.

Also, you might want to designate additional CPU and memory resources in init step to make VM more robust.

**Comment by mikeymop** [comment]
Thanks for the feedback arixmkii.

I just tried that and now podman doesn't hang at waiting on VM and shows an error

```
$ podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Mounting volume... /Users/wz4l0j:/Users/wz4l0j
Error: exit status 255
```

```
$ podman machine start --log-
level=debug
INFO[0000] podman filtering at log level debug
Error: cannot start VM podman-machine-default: VM already running or starting
```

Strangely even after this failure, and the confirmation shows it is already running I can connect to the machine using the default connection.

```
$ podman machine ssh
Connecting to vm podman-machine-default. To close connection, use `~.` or `exit`
Warning: Permanently added '[localhost]:50292' (ED25519) to the list of known hosts.
Fedora CoreOS 37.20221127.2.0
Tracker: https://github.com/coreos/fedora-coreos-tracker
Discuss: https://discussion.fedoraproject.org/tag/coreos

Last login: Wed Nov 30 18:46:37 2022 from 192.168.127.1
[core@localhost ~]$
```

Is there something that could be blocking the happy path when `podman machine start` is called?

**Comment by rhatdan** [comment]
There have been a ton of fixes in machine, so I am going to assume this is fixed and close the issue.
