### ISSUE TITLE
Proxy issue: proxyconnect tcp: dial tcp: lookup my-proxy.com: Temporary failure in name resolution

### ISSUE THREAD

**Issue by PeterGarner** [containers/podman#16703]
/kind bug

Proxy trouble when working through the Windows setup guide.  I initially thought it was related to corporate firewall but I get the same whether I'm on the VPN or not: 

`> podman run ubi8-micro date
Resolved "ubi8-micro" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull registry.access.redhat.com/ubi8-micro:latest...
Error: initializing source docker://registry.access.redhat.com/ubi8-micro:latest: pinging container registry registry.access.redhat.com: Get "https://registry.access.redhat.com/v2/": proxyconnect tcp: dial tcp: lookup my-corp-proxy.com: Temporary failure in name resolution`

**Steps to reproduce the issue:**
This is the 'First Podman Command' step here https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md

I'm running the cmd in Windows Terminal / Powershell whilst on and off the VPN, same result 

**Output of `podman version`:**
```
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.18.5
Git Commit:   814b7b003cc630bf6ab188274706c383f9fb9915
Built:        Thu Nov 10 14:18:45 2022
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.18.7
Built:        Fri Nov 11 15:24:13 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**
```
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.5-1.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 99.88
    systemPercent: 0.09
    userPercent: 0.03
  cpus: 4
  distribution:
    distribution: fedora
    variant: container
    version: "36"
  eventLogger: journald
  hostname: RD-9MQHQF2-LAP
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.72-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 12948553728
  memTotal: 13176123392
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.7-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.7
      commit: 40d996ea8a827981895ce22886a9bac367f87264
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 4294967296
  swapTotal: 4294967296
  uptime: 0h 30m 24.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 269490393088
  graphRootUsed: 374210560
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 1668180253
  BuiltTime: Fri Nov 11 15:24:13 2022
  GitCommit: ""
  GoVersion: go1.18.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1
```

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Windows system, 
```
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      19045  0
```

**Comment by robtail** [comment]
Hi, 
I have the same issue.  I assume corporate policy make restriction on podman or name resolution...
Steps:
1 Having` podman machine init` was success. 
2 but  `podman run ubi8-micro date` failed with `Resolved "ubi8-micro" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull registry.access.redhat.com/ubi8-micro:latest...
Error: initializing source docker://registry.access.redhat.com/ubi8-micro:latest: pinging container registry registry.access.redhat.com: Get "https://registry.access.redhat.com/v2/": dial tcp: lookup registry.access.redhat.com: Temporary failure in name resolution`

if i check how name resolution works in podman vm with `wsl -d podman-machine-default` with curl `curl google.com
curl: (6) Could not resolve host: google.com` then it shows no name resolution works in this vm.

**Comment by PeterGarner** [comment]
I fixed this by upgrading the OS.  I believe the docs state 20.10 as a minimum.  I moved to 22.10 and 'apt install podman' is working

**Comment by robtail** [comment]
Hi, 
Thanks for opening the ticket and more to give hint how to workaround. 
please give me some guidance how to upgrade the OS? Im just begginer on podman yet. :) so i appreciate any link / guide. thx in advance.

**Comment by PeterGarner** [comment]
https://www.layerstack.com/resources/tutorials/How-to-upgrade-from-Ubuntu-20.04-Ubuntu-22.04
