### ISSUE TITLE
podman run -t sends control characters to the terminal

### ISSUE THREAD

**Issue by bowlofeggs** [containers/podman#1671]
**Is this a BUG REPORT or FEATURE REQUEST?**:

[//]: **kind bug**

**Description**

```podman run```'s ```-t``` flag behaves differently than ```docker run```'s ```-t``` flag, in that it sends control characters to the output. If you use another program to run podman and collect the output from it to print to that controlling program's terminal, this will damage the controlling process's terminal. I have observed this problem with [bodhi-ci](https://github.com/fedora-infra/bodhi/blob/3fdbbb4d69e31e25163ad5612257a16b7902f0fc/devel/ci/bodhi-ci), which launches ```podman``` via Python's ```asyncio.create_subprocess_exec()``` and collects the output via a ```subprocess.PIPE```. It later prints the output to the terminal, but the control characters break the terminal (```reset``` must be used to get it functional again). ```bodhi-ci``` also supports ```docker```, and these control characters are not sent in that mode.

As a workaround, I plan to filter the output from ```podman``` to remove control characters, but I thought it would be worth reporting upstream in case ```podman``` wanted to try to emulate ```docker``` here as well.

Honestly, I could see an argument for keeping the current behaviour because ```podman run``` is able to do things like detect the width of the terminal when run directly in a terminal, but I thought it was worth filing about in case the discrepancy between docker and podman here was not desired. docker calls the ```--tty``` flags a "pseudo terminal", which I suppose might be related to why they don't use control characters. Perhaps podman could have both options, something like a ```--tty``` and a ```--real-tty```?

**Comment by vrothberg** [comment]
@mheon, did you find time to check if it's the setup code or conmon?

**Comment by mheon** [comment]
I think it's us, not conmon, but it's been awhile so not 100% sure.

**Comment by rhatdan** [comment]
@mtrmac @vrothberg Any update on this,  Can we close this issue?

**Comment by vrothberg** [comment]
@mheon ^

**Comment by mheon** [comment]
I think we should keep this open. This hasn't become an urgent issue yet, but it's also definitely not fixed.

**Comment by mtrmac** [comment]
BTW it’s not _obviously correct_ to drop control characters: if the container is provided a PTY slave FD, it will reasonably expect that it can actually treat it as a TTY — i.e. use syscalls to ask about the window size, and use terminal control sequences to control the terminal.  Basically, consider a `vi` container — that should be possible in principle, shouldn’t it?

Also, to avoid confusion, “pseudo TTY” just means “a TTY-like object without a physical device (like a serial port) underlying it”; every xterm window is backed by a pseudo-TTY master/slave pair.  It has nothing at all to do with stripping/not stripping control characters.

(To be fair, I haven’t even found the code in `docker run` that strips control characters, so I really have no opinion on the actual Docker/podman behavior difference.)

**Comment by rhatdan** [comment]
Shouldn't we be checking if we have a tty and then not send the control chars?  Or am I misunderstanding what is going on?

**Comment by mheon** [comment]
I think we want to leave this configurable if nothing else - I kind of like having control characters interpreted in some cases.

**Comment by rhatdan** [comment]
@mheon What should we do with this issue?

**Comment by mheon** [comment]
I think adding a flag to handle this is a nice-to-have, but not really a priority unless people start encountering issues with out TTY handling.

**Comment by rhatdan** [comment]
@mheon @baude Should we just close this?

**Comment by mheon** [comment]
Ummm. I think we should leave it open... It could end up affecting compatibility for some applications?

**Comment by vrothberg** [comment]
Added labels to get the attention of the community

**Comment by rhatdan** [comment]
Don't see any reason to close this one.

**Comment by oleksandrborniak** [comment]
@mheon I guess I have faced the same issue on "cockpit-podman". 
<img width="893" alt="Screenshot 2019-11-11 at 16 43 50" src="https://user-images.githubusercontent.com/49722408/68608305-343c8b80-04bb-11ea-909f-16bb7852b0fa.png">
I see "^L" symbols when I am running podman container with a terminal.  
<img width="734" alt="Screenshot 2019-11-11 at 19 46 14" src="https://user-images.githubusercontent.com/49722408/68608589-fc821380-04bb-11ea-8587-6bc6d8547471.png">

```
[root@fc ~]# rpm -qa | grep podman
cockpit-podman-10-1.fc31.noarch
podman-1.6.2-2.fc31.x86_64
podman-manpages-1.6.2-2.fc31.noarch
[root@fc ~]#
```

<img width="1279" alt="Screenshot 2019-11-11 at 19 50 45" src="https://user-images.githubusercontent.com/49722408/68608864-9fd32880-04bc-11ea-888f-e64df1000283.png">

**Comment by baude** [comment]
@mheon any chance your recent work happened to fix this?

**Comment by mheon** [comment]
Nope.

**Comment by rhatdan** [comment]
Will this continue to happen on APIV2?

**Comment by mheon** [comment]
Most likely yes, given the way our copying works, but I'm not 100% certain.

**Comment by rhatdan** [comment]
@ryanchpowell Could you work with @haircommander To fix this one.

**Comment by ryanchpowell** [comment]
Yes I can work on it

**Comment by mheon** [comment]
For reference, I don't know if I consider this one high priority. I think the cockpit errors are probably implementation details on their part, and nobody else has complained about this in two years...

**Comment by rhatdan** [comment]
@ryanchpowell Any movement on this?

**Comment by ryanchpowell** [comment]
I have not gotten to this yet, but can give it higher priority.

**Comment by fhoxh** [comment]
👍

**Comment by rhatdan** [comment]
Are we sure this works differently on Docker?

**Comment by rhatdan** [comment]
Two year old issue, and it looks like it is still with us.

**Comment by rhatdan** [comment]
I am going to close since this is the only time we have ever hear about this issue over many years.
