### ISSUE TITLE
.volume file example and description (Quadlet)

### ISSUE THREAD

**Issue by lfarkas** [containers/podman#16729]
there is not any example how to use .volume files. there is a description in the container section which is working, but there are no description what is the difference when which one is the preferred and how to use the .volumes files? since we can't find any ways how to add a volume with it.

**Comment by vrothberg** [comment]
@alexlarsson should archive the old project or forward it to Podman?

**Comment by ygalblum** [comment]
Volume units are explained here: https://github.com/containers/podman/blob/main/docs/source/markdown/podman-systemd.unit.5.md#volume-units with an example in the Examples section.
Is there anything else that's needed here, or can we close this issue?

**Comment by alexlarsson** [comment]
Yeah. lemme archive the other one.

**Comment by alexlarsson** [comment]
oh, its done already
