### ISSUE TITLE
Docker wrapper script is not portable

### ISSUE THREAD

**Issue by multimeric** [containers/podman#16720]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. `export DESTDIR=/foo`
1. `make install`
1. `make install.docker`
1. `/foo/bin/docker`

**Describe the results you received:**

```
/foo/bin/docker: line 4: /usr/bin/podman: No such file or directory
```

**Describe the results you expected:**

The correct podman should be executed successfully

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

Yes

**Comment by rhatdan** [comment]
Care to open a PR to fix?  Looks like docker should be a symolic link to docker->../podman rather then to docker->/usr/bin/podman.

**Comment by multimeric** [comment]
Happy to make a PR with that fix.

**Comment by multimeric** [comment]
So the issue is that it's not actually a symlink, but rather it's a tiny wrapper bash script: https://github.com/containers/podman/blob/main/docker. This makes it a bit more tricky to make portable though, because I can't just use `../podman` because that will be relative to the cwd and not to the wrapper script. Since we're using `sh` and not `bash`, I can't use the `$BASH_SOURCE`. I could use `readlink -f "$0"` which would then require `readlink` to be present. Alternatively we could do something at compile time using `make` that just hardcodes the path into the bash script based on the `PREFIX`. Let me know which solution you would prefer.

**Comment by rhatdan** [comment]
I think you should just do the PREFIX and Makefile change.

**Comment by multimeric** [comment]
Can I assume that `envsubst` is installed for doing this interpolation? Or should I write something in Go using [`ExpandEnv`](https://pkg.go.dev/os#ExpandEnv)?

**Comment by rhatdan** [comment]
I am finewith interplation.

**Comment by multimeric** [comment]
Yes but I'm unsure about the appropriate method of interpolation.

**Comment by rhatdan** [comment]
@multimeric Are you still working on this?

**Comment by multimeric** [comment]
I will finish it, but I need to know what tools to use to do the interpolation.

**Comment by rhatdan** [comment]
Use envsubst
