### ISSUE TITLE
Include podman-mac-helper binaries on release for airgapped / offline isntall

### ISSUE THREAD

**Issue by cdrage** [containers/podman#16746]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

We have the ability to specify where the binaries are located `helpers_binaries_dir` but no way to actually *get* the official ~`gvproxy`~ and `podman-mac-helper` binaries without building it from source.

Any way to include the binaries? This would make it easier for offline / airgapped installations on macOS machines where ~`gvproxy`~ and `podman-mac-helper` is required.

**Steps to reproduce the issue:**

1. Download Podman from release

2. Try to find ~`gvproxy`~ and `podman-mac-helper` from .zip file

3. Where binary?

**Describe the results you received:**

No location of ~gvproxy~ and podman-mac-helper binaries

**Describe the results you expected:**

A place to download them

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Shouldn't this be opened against the gvproxy repo? That binary isn't built out of our repo; I don't see why we would attach it to our releases.

**Comment by mheon** [comment]
@ashley-cui How does that get built?

**Comment by cdrage** [comment]
@ashley-cui just seeing this issue: https://github.com/containers/podman/issues/15104

I see it's available in the `.dmg` but not the `.zip`

**Comment by ashley-cui** [comment]
Zip releases are currently done via make-podman-remote-release-{os}_{arch}.zip in CI. It should be just a makefile change. I can take care of it.

**Comment by gedw99** [comment]
Does not seem to be in the brew version ?

I installed the engine and then the desktop via brew...

.zshrc with commands commented...
```
### PODMAN

# https://podman-desktop.io/docs/installation/macos-install#installation-steps

# install podman engine
#brew install podman

# install gpgme (needed for podman's Go binding dependenices)
#brew install gpgme

# install podman decktop gui
#brew install podman-desktop

# Final manual setup.
#podman machine init -v $HOME:$HOME
#podman machine start

# if receiving a "too many open files" error on M1 macs, try:
#podman machine stop && ulimit -n unlimited && podman machine start

# make docker and docker compose available to podmam
export PATH="/Users/apple/.local/share/containers/podman-desktop/extensions-storage/compose/bin:$PATH"

```
<img width="1162" alt="Screenshot 2023-03-31 at 12 23 31" src="https://user-images.githubusercontent.com/53147028/229095099-d95c0f2b-799a-43f6-b032-7a4fef2edcf3.png">
