### ISSUE TITLE
Define better error message for container name conflicts with "external" storage

### ISSUE THREAD

**Issue by baude** [containers/podman#16759]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

/kind feature

**Description**

When you have a database failure or the database gets nuked, containers may still "exist" in the filesystem, also referred to as "external storage".  When attempting to recreate a container with the same name as a container in external storage, you receive a poor error message,

**Steps to reproduce the issue:**

1. podman create --name foobar alpine top

2. rm /var/lib/containers/storage/bolt_state.db

3. podman create --name foobar alpine top

**Describe the results you received:**
sudo podman create --name foobar alpine top
Error: creating container storage: the container name "container1" is already in use by e77786c096e083b258bad2e196255f7dc1a2859cfb9dd35436648e1541bdce23. You have to remove that container to be able to reuse that name: that name is already in use

**Describe the results you expected:**

The error message should say it is in external storage.  It should also suggest the use of --replace

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info`:**

```
Client:       Podman Engine
Version:      4.4.0-dev
API Version:  4.4.0-dev
Go Version:   go1.19.3
Git Commit:   c942f7788707ee565b657d8a5c1fb56d7dec0347-dirty
Built:        Mon Dec  5 12:52:27 2022
OS/Arch:      linux/amd64

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
NA, upstream
```

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

Yes
Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
SGTM

We have something similar in `podman rmi`: 

> Error: image used by 532a5cb50062f0056f110e4a0afe14ab18e06fb10414c9a868922d5f2f6353d2: image is in use by a container: consider listing external containers and force-removing image

**Comment by ahmedaabouzied** [comment]
I want to try to tackle this small issue as a way of exploring the code. I managed to replicate the issue. I think the error is being returned in `libpod/container_internal.go:505`. Would it be just enough to modify the error message and suggest using `--replace` in that line?

**Comment by ahmedaabouzied** [comment]
Or do you think it's better to add the part about suggesting using `--replace` in `containers/storage/containers.go:589` since it seems like this where we report that the name is already taken?

**Comment by rhatdan** [comment]
This should only be one in Podman code not in contaners/storage, because all users of containers/storage might not have the --replace option.

**Comment by ahmedaabouzied** [comment]
@rhatdan , Thanks. That's really helpful. I'll try to open a PR for this soon.

**Comment by rhatdan** [comment]
@ahmedaabouzied did you ever get a chance to work on this?

**Comment by Regis-Caelum** [comment]
Hey @rhatdan, I would like to work on this one

**Comment by rhatdan** [comment]
@Regis-Caelum You got it.

**Comment by SourceCodeWhen** [comment]
Hi there @rhatdan,

This looks to have been sitting around for a while so happy to work on it and submit a PR. :)

**Comment by cgiradkar** [comment]
I can change the error message to `the container name <name>is already in use by <container_id>. You have to remove that container to be able to reuse that name: <name>, or use --replace to instruct Podman to do so.`
But I am finding it difficult checking if the container exists externally (External: true). tried checking via `registry.ContainerEngine().ContainerExists` method, but it goes into circular dependency.
Any suggestions are welcome!
