### ISSUE TITLE
podman machine: flaky start

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#16789]
New flake in `podman machine start`. Sorry, I don't know enough about podman-machine to know what to report. Basically, e2e tests failing:
```
         Waiting for VM to exit...
[+0213s] Machine "112b4a8a48f5" stopped successfully
         output: Waiting for VM to exit... Machine "112b4a8a48f5" stopped successfully
         /var/tmp/go/src/github.com/containers/podman/bin/podman-remote machine start 112b4a8a48f5 --no-info
         Starting machine "112b4a8a48f5"
         Waiting for VM ...
[+0229s] Mounting volume... /tmp/podman_test1144977279:/tmp/podman_test1144977279
         Error: exit status 255
```
...followed by a ginkgo "expected 125 to be 0".

### podman machine start [It] start simple machine 
* fedora-37 : machine podman fedora-37 rootless host
  * PR #16749
    * [12-05 16:09](https://api.cirrus-ci.com/v1/artifact/task/4607360870645760/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--1)
    * [12-05 16:09](https://api.cirrus-ci.com/v1/artifact/task/4607360870645760/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--2)
    * [12-05 16:09](https://api.cirrus-ci.com/v1/artifact/task/4607360870645760/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--3)
  * PR #16371
    * [12-06 05:06](https://api.cirrus-ci.com/v1/artifact/task/4863582379180032/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--1)
    * [12-06 05:06](https://api.cirrus-ci.com/v1/artifact/task/4863582379180032/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--2)
    * [12-06 05:06](https://api.cirrus-ci.com/v1/artifact/task/4863582379180032/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--3)
  * PR #13808
    * [11-21 08:13](https://api.cirrus-ci.com/v1/artifact/task/5103185651040256/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--1)
    * [11-21 08:13](https://api.cirrus-ci.com/v1/artifact/task/5103185651040256/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--2)
    * [11-21 08:13](https://api.cirrus-ci.com/v1/artifact/task/5103185651040256/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--3)
* fedora-37-aarch64 : machine podman fedora-37-aarch64 rootless host
  * PR #16713
    * [12-05 03:39](https://api.cirrus-ci.com/v1/artifact/task/5041228534775808/html/machine-podman-fedora-37-aarch64-rootless-host.log.html#t--start-simple-machine--1)
    * [12-05 03:39](https://api.cirrus-ci.com/v1/artifact/task/5041228534775808/html/machine-podman-fedora-37-aarch64-rootless-host.log.html#t--start-simple-machine--2)

**Comment by vrothberg** [comment]
@ashley-cui @baude FYI

**Comment by ashley-cui** [comment]
Initial reaction would be that it's probably SSH related.

**Comment by edsantiago** [comment]
Still seeing it

* fedora-37 : machine podman fedora-37 rootless host
  * PR #16953
    * [01-03 07:24](https://api.cirrus-ci.com/v1/artifact/task/4577850150354944/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--1)
    * [01-03 07:24](https://api.cirrus-ci.com/v1/artifact/task/4577850150354944/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--2)
    * [01-03 07:24](https://api.cirrus-ci.com/v1/artifact/task/4577850150354944/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--3)
    * [01-03 07:24](https://api.cirrus-ci.com/v1/artifact/task/4577850150354944/html/machine-podman-fedora-37-rootless-host.log.html)
    * [01-03 07:24](https://api.cirrus-ci.com/v1/artifact/task/4577850150354944/html/machine-podman-fedora-37-rootless-host.log.html)
  * PR #16911
    * [12-21 07:33](https://api.cirrus-ci.com/v1/artifact/task/6310249737486336/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--1)
    * [12-21 07:33](https://api.cirrus-ci.com/v1/artifact/task/6310249737486336/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--2)
    * [12-21 07:33](https://api.cirrus-ci.com/v1/artifact/task/6310249737486336/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--3)
    * [12-21 07:33](https://api.cirrus-ci.com/v1/artifact/task/6310249737486336/html/machine-podman-fedora-37-rootless-host.log.html)
    * [12-21 07:33](https://api.cirrus-ci.com/v1/artifact/task/6310249737486336/html/machine-podman-fedora-37-rootless-host.log.html)
  * PR #16810
    * [12-30 11:20](https://api.cirrus-ci.com/v1/artifact/task/5848310603317248/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--1)
    * [12-30 11:20](https://api.cirrus-ci.com/v1/artifact/task/5848310603317248/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--2)
    * [12-30 11:20](https://api.cirrus-ci.com/v1/artifact/task/5848310603317248/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--3)
    * [12-30 11:20](https://api.cirrus-ci.com/v1/artifact/task/5848310603317248/html/machine-podman-fedora-37-rootless-host.log.html)
    * [12-30 11:20](https://api.cirrus-ci.com/v1/artifact/task/5848310603317248/html/machine-podman-fedora-37-rootless-host.log.html)

**Comment by edsantiago** [comment]
Ping, can we please get some attention to this?

* fedora-37 : machine podman fedora-37 rootless host
  * PR #17055
    * [01-11 17:13](https://api.cirrus-ci.com/v1/artifact/task/4697143403872256/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--1)
    * [01-11 17:13](https://api.cirrus-ci.com/v1/artifact/task/4697143403872256/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--2)
    * [01-11 17:13](https://api.cirrus-ci.com/v1/artifact/task/4697143403872256/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--3)
    * [01-11 17:13](https://api.cirrus-ci.com/v1/artifact/task/4697143403872256/html/machine-podman-fedora-37-rootless-host.log.html)
    * [01-11 17:13](https://api.cirrus-ci.com/v1/artifact/task/4697143403872256/html/machine-podman-fedora-37-rootless-host.log.html)
  * PR #17022
    * [01-06 14:26](https://api.cirrus-ci.com/v1/artifact/task/5006309242699776/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--1)
    * [01-06 14:26](https://api.cirrus-ci.com/v1/artifact/task/5006309242699776/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--2)
    * [01-06 14:26](https://api.cirrus-ci.com/v1/artifact/task/5006309242699776/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--3)
    * [01-06 14:26](https://api.cirrus-ci.com/v1/artifact/task/5006309242699776/html/machine-podman-fedora-37-rootless-host.log.html)
    * [01-06 14:26](https://api.cirrus-ci.com/v1/artifact/task/5006309242699776/html/machine-podman-fedora-37-rootless-host.log.html)
  * PR #16953
    * [01-03 07:24](https://api.cirrus-ci.com/v1/artifact/task/4577850150354944/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--1)
    * [01-03 07:24](https://api.cirrus-ci.com/v1/artifact/task/4577850150354944/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--2)
    * [01-03 07:24](https://api.cirrus-ci.com/v1/artifact/task/4577850150354944/html/machine-podman-fedora-37-rootless-host.log.html#t--start-simple-machine--3)
    * [01-03 07:24](https://api.cirrus-ci.com/v1/artifact/task/4577850150354944/html/machine-podman-fedora-37-rootless-host.log.html)
    * [01-03 07:24](https://api.cirrus-ci.com/v1/artifact/task/4577850150354944/html/machine-podman-fedora-37-rootless-host.log.html)
* fedora-37-aarch64 : machine podman fedora-37-aarch64 rootless host
  * PR #17064
    * [01-11 18:35](https://api.cirrus-ci.com/v1/artifact/task/6450156988530688/html/machine-podman-fedora-37-aarch64-rootless-host.log.html#t--start-simple-machine--1)
    * [01-11 18:35](https://api.cirrus-ci.com/v1/artifact/task/6450156988530688/html/machine-podman-fedora-37-aarch64-rootless-host.log.html#t--start-simple-machine--2)
    * [01-11 18:35](https://api.cirrus-ci.com/v1/artifact/task/6450156988530688/html/machine-podman-fedora-37-aarch64-rootless-host.log.html)
    * [01-11 18:35](https://api.cirrus-ci.com/v1/artifact/task/6450156988530688/html/machine-podman-fedora-37-aarch64-rootless-host.log.html)
    * [01-11 18:35](https://api.cirrus-ci.com/v1/artifact/task/6450156988530688/html/machine-podman-fedora-37-aarch64-rootless-host.log.html)

**Comment by edsantiago** [comment]
New symptom?
```
  list machine: check if running while starting
Migrating machine ""
         Error: checking VM active: unexpected end of JSON input
         NAME           VM TYPE     CREATED        LAST UP        CPUS        MEMORY      DISK SIZE
         7ad7ab2c8b50*  qemu        7 seconds ago  7 seconds ago  1           2.147GB     107.4GB
```
in [f37 aarch64 rootless](https://api.cirrus-ci.com/v1/artifact/task/5479726072987648/html/machine-podman-fedora-37-aarch64-rootless-host.log.html#t--list-machine--check-if-running-while-starting--1). Same symptom seems to have happened [in November, same setup](https://api.cirrus-ci.com/v1/artifact/task/6374812657385472/html/machine-podman-fedora-37-aarch64-rootless-host.log.html#t--list-machine--check-if-running-while-starting--1).

And no, this issue isn't stale, it's just that the quay.io and "happened during" flakes are much more prevalent.

* fedora-37-aarch64 : machine podman fedora-37-aarch64 rootless host
  * PR #17141
    * [01-17 11:30](https://api.cirrus-ci.com/v1/artifact/task/5665517868941312/html/machine-podman-fedora-37-aarch64-rootless-host.log.html#t--start-simple-machine--1) in podman machine start [It] start simple machine 
    * [01-17 11:30](https://api.cirrus-ci.com/v1/artifact/task/5665517868941312/html/machine-podman-fedora-37-aarch64-rootless-host.log.html#t--start-simple-machine--2) in podman machine start [It] start simple machine

**Comment by vrothberg** [comment]
Did it flake recently?

**Comment by edsantiago** [comment]
Most recently in March:

* fedora-37-aarch64 : machine podman fedora-37-aarch64 rootless host boltdb
  * PR #17954
    * [03-29 19:59](https://api.cirrus-ci.com/v1/artifact/task/5094509734789120/html/machine-podman-fedora-37-aarch64-rootless-host-boltdb.log.html#t--list-machine--check-if-running-while-starting--1) in podman machine list [It] list machine: check if running while starting
    * [03-29 19:59](https://api.cirrus-ci.com/v1/artifact/task/5094509734789120/html/machine-podman-fedora-37-aarch64-rootless-host-boltdb.log.html#t--list-machine--check-if-running-while-starting--2) in podman machine list [It] list machine: check if running while starting
    * [03-29 19:59](https://api.cirrus-ci.com/v1/artifact/task/5094509734789120/html/machine-podman-fedora-37-aarch64-rootless-host-boltdb.log.html#t--list-machine--check-if-running-while-starting--3) in podman machine list [It] list machine: check if running while starting

**Comment by edsantiago** [comment]
Speaking of the King of Rome... it [triggered just now](https://api.cirrus-ci.com/v1/artifact/task/4952869925814272/html/machine-podman-fedora-37-aarch64-rootless-host-boltdb.log.html#t--ssh-to-running-machine-and-check-os-type--1)

**Comment by vrothberg** [comment]
@edsantiago, a lot of work went into making start+stop more robust.  Have you seen this flake again recently?

**Comment by edsantiago** [comment]
Last seen in June.

**Comment by vrothberg** [comment]
> Last seen in June.

That aligns with some of my comments from June-August addressing issues.
