### ISSUE TITLE
Windows won't boot (!?) after installing podman.

### ISSUE THREAD

**Issue by SuriMarks** [containers/podman#16792]
/kind bug

I wanted to try using podman, so I went through the installation instructions and installed https://github.com/containers/podman/releases/download/v4.3.1/podman-4.3.1-setup.exe. After setup complete, it asked to reboot my computer. I agreed, and when it went to restart I now does not turn on.

**Steps to reproduce the issue:**

1. install https://github.com/containers/podman/releases/download/v4.3.1/podman-4.3.1-setup.exe on Windows 11

2. reboot pc when prompted.

**Describe the results you received:**

system fails to reboot, and goes to recovery screen, but has no viable recovery options.

**Describe the results you expected:**

The computer reboots normally into Windows. Even if there is a problem with the podman installation, that is fine, but it should not prevent me from booting my computer.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

n/a - I cannot use my computer.

**Output of `podman info`:**

n/a - I cannot use my computer.

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

n/a - I cannot use my computer.

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows 11 is installed as a guest using QEMU/KVM (Host is Fedora 36 if it matters)

**Comment by vrothberg** [comment]
@n1hility FYI

**Comment by SuriMarks** [comment]
I have regained access to my PC. I don't use windows too often, so after a lot of troubleshooting, I finally found the option to use windows safe mode. Luckily this detected something was wrong with the attempted installation, reverted some things (who knows what. it does not tell you) and allowed me to boot successfully. From there I could uninstall podman. After that my computer returned to booting normally. I am glad to have my computer working again, but A) having the installer crash my system was a very poor experience and B) I am now not going to try using podman on windows because attempting it really wrecks my PC.
I do still like using it on linux though.

**Comment by n1hility** [comment]
hi @SuriMarks. Podman doesn't make any unusual changes to the system, it just turns on two Windows features through the standard DISM interface to turn on WSL (similar to using control panel and picking enable/disable feature). If you encountered a failure like there there was likely something else going on, or there was a problem with a queued windows update / hot fix. I would recommend applying all Windows updates and rebooting, verifying everything is clean from that point. From there you have two options. One is you can reattempt podman install, and let it attempt to enable WSL again. Or if you prefer you can install WSL directly yourself first. The command to do that on windows 'wsl --install'.  After WSL is installed and you have rebooted and completed the subsequent setup process it triggers, you can then run the podman installer. While it should detect and skip WSL installation, you can also just deselect the WSL checkbox in the installer. At that point podman simply installs files on your filesystem and nothing more.

**Comment by n1hility** [comment]
Closing since I am pretty sure this is unrelated to podman, but feel free to reopen if you continue to see this issue.
