### ISSUE TITLE
Implement a new "podman run --publish-local 8080:80" flag

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [containers/podman#16801]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

The idea of this feature request would be to implement a "--publish-local 8080:80" flag to the "podman run" command, which would allow to open a listening port not on the machine where the container really runs, but where the podman client runs. For the "normal" client, this would actually have exactly the same behavior than the "--publish" flag. However for "podman-remote" it would instead have this logic:
 - listen for port 8080 on the machine where "podman-remote" runs
 - each time a connection is accept()'ed on this machine, then it would "proxy/tunnel" to the container running on the remote machine, à la netcat/socat.
 
 Why this very strange demand ? The most used alternative today on the docker area is to start a container remotely, and use somehow docker inspect to be able to guess the public ip of machine where the remote docker is running, hoping that this ip is reachable, and using this ip on client side. This is typically what a project like libssh2 does in its test suite: it starts a classical OS image containing an openssh server using docker, and test the locally build libssh2 client library against this potentially remotely running container. They use this logic https://github.com/libssh2/libssh2/blob/f6694beb21518491fe9d02c56ae14a0319d79a8d/tests/openssh_fixture.c#L256 to try to find the right "public ip" to be able to connect from the client machine. This logic has limits, when you start to have docker-in-docker/docker-in-podman/podman-in-docker/docker-in-docker-in-docker/docker side by side docker with /var/run/docker.sock from somewhere else mapped inside the container/... scenarios you aren't always sure it works. Or you may simply have a firewall allowing just the docker/podman connection and nothing else.
 
 A way to emulate this today without any docker/podman support is to do this:
 - Start any random image serving requests, for example nginx (serves http requests on port 80): `podman run --rm --cidfile=/tmp/container-id nginx `
 - On the client machine, assuming socat is installed, you can run a "local" server waiting for inbound connections on port 8080, and "tunneling" it to inside the remotely running container: `socat tcp-listen:8080,reuseaddr,fork exec:"podman run -i --rm --network=container\:$(cat /tmp/container-id) busybox nc 127.0.0.1 80"`
 - Finally test on client side that this works: `curl "http://localhost:8080"`

Note: this flag doesn't exist at all on docker side, so if accepted, that would be a podman extension compared to docker.

**Comment by mheon** [comment]
@baude We've been discussing gvproxy replacement, is this something that would be covered by that?

**Comment by rhatdan** [comment]
How would this work with the --detach mode, where podman goes away?

**Comment by Romain-Geissler-1A** [comment]
Good question. Actually I thought about it but didn't write it. An "easy" answer would be to say that's is incompatible with the detach mode, and the management of the locally served socket can be implemented in the podman client process. However if such a feature is accepted, undoubably someone will eventually come and ask it to work in --detach mode as well. I guess to make it work podman-client would need to fork/exec into a new process that would be here only to serve the local socket, and this process would somehow need to use the api of "podman wait" to die automatically when the remote container dies.

**Comment by Luap99** [comment]
I think it is to much for us to support. As pointed out by @rhatdan this will get more difficult in detached mode. There are so many different ways to start containers it is extremely complicated to try to cover this on the frontend (podman-remote).
Port forwarding is already way to complicated IMO, I really do not want to deal with yet another layer to worry about especially since this needs to work cross platform.



> @baude We've been discussing gvproxy replacement, is this something that would be covered by that?

I think the request is not about machine but general podman-remote so gvproxy or any replacement will not matter since they only work with VMs on the same host. For podman machine this request is already covered since the ports are already published on the host.

**Comment by Romain-Geissler-1A** [comment]
Hi,

I confirm, this request is not about podman machine (I use only Linux, and my remote podman "servers" aren't seen as podman machines, these are simple Linux hosts I can ssh into and which have a systemd-managed podman.sock).

Shall I close this ticket as "won't implement" ?

Cheers,
Romain

**Comment by Luap99** [comment]
> Shall I close this ticket as "won't implement" ?

Well I am not the only one to decide this. Other maintainers can have different opinions, I would give them some more time to chime in if they want.

**Comment by edsantiago** [comment]
Sorry for replying late. Wow, this is a doozie to wrap my head around. Is the goal here to open a port on **localhost**, or **to the world**? If localhost only, this seems perfectly suited to `ssh -L 8080:localhost:80 host-on-which-container-is-actually-running`. If you're talking about binding to `*`, ... I'll bow out of this conversation.

**Comment by rhatdan** [comment]
Since we have had no more feedback, closing.
