### ISSUE TITLE
Issues using generate systemd for a container that uses volumes

### ISSUE THREAD

**Issue by dancs-dev** [containers/podman#16808]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

A Podman container could not automatically be started up by user's systemd.

**Steps to reproduce the issue:**

1. Attempt to run the docker.io freshrss/freshrss container using this command: `podman run -d --log-opt max-size=10m   -p 44449:80   -e TZ=Europe/London   -e 'CRON_MIN=1,31'   -v freshrss_data:/var/www/FreshRSS/data   -v freshrss_extensions:/var/www/FreshRSS/extensions   --name freshrss   docker.io/freshrss/freshrss`
2. Generate a systemd file using: `podman generate systemd --new --name freshrss -f` while in `.config/systemd/user/`.
4. Enable the service using `systemctl --user enable ...`
3. Stop and remove the container `podman stop freshrss` and `podman container rm freshrss`, and then reboot.

**Describe the results you received:**

The container would keep stopping and starting constantly.

**Describe the results you expected:**

The container would start once I had logged into my user.

**Additional information you deem important (e.g. issue happens only occasionally):**

When I changed the systemd generate to not use `--new`, I instead got this error: `Dec 10 11:43:25 USERNAME systemd[2513]: freshrss.service: New main PID 105697 does not belong to service, and PID file is not owned by root. Refusing.`.  

**Output of `podman version`:**

```
podman version 3.4.4
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 20
  distribution:
    codename: vanessa
    distribution: linuxmint
    version: "21"
  eventLogger: journald
  hostname: USERNAME
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.0-56-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 6567473152
  memTotal: 33579220992
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version 1.1.0-0ubuntu1.1
      spec: 1.0.2-dev
      go: go1.18.1
      libseccomp: 2.5.3
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 2134634496
  swapTotal: 2147479552
  uptime: 11h 49m 31.14s (Approximately 0.46 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/USERNAME/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.10.5
        fuse-overlayfs: version 1.7.1
        FUSE library version 3.10.5
        using FUSE kernel interface version 7.31
  graphRoot: /home/USERNAME/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: ecryptfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 3
  runRoot: /run/user/1000/containers
  volumePath: /home/USERNAME/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 3.4.4

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
Listing... Done
podman/jammy,now 3.4.4+ds1-1ubuntu1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

Yes, I have checked the guide. I have read through the changelog and cannot see anything that mentions a fix to this issue, nor any closed issue.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Linux Mint

**Comment by vrothberg** [comment]
Thanks for reaching out.  I cannot reproduce the error but have the suspicion that the generated unit file has been edited?

Can you share the ouput of the .service file?  I think there may be a `User=` line which isn't supported.

**Comment by vrothberg** [comment]
If the container is already running (and was not started by systemd) the error makes sense for units generated without --new.  Units with --new should just work.

Just to double check, @dancs-dev.  Both cases do not work, right?

**Comment by vrothberg** [comment]
> I am not sure what is wrong with the above, but I think I have a decent workaround (is there anything wrong with this?):

Only units generate by Podman are supported.  There's too much that can go wrong.

**Comment by dancs-dev** [comment]
Both cases don't work unfortunately. Here is the output from the `--new` case:

```
USERNAME@HOSTNAME:~$ systemctl --user status container-freshrss.service 
○ container-freshrss.service - Podman container-freshrss.service
     Loaded: loaded (/home/USERNAME/.config/systemd/user/container-freshrss.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Thu 2022-12-15 10:03:09 GMT; 12min ago
       Docs: man:podman-generate-systemd(1)
    Process: 2359 ExecStartPre=/bin/rm -f /run/user/1000/container-freshrss.service.ctr-id (code=exited, status=0/SUC>
    Process: 2360 ExecStart=/usr/bin/podman run --cidfile=/run/user/1000/container-freshrss.service.ctr-id --cgroups=>
    Process: 2425 ExecStop=/usr/bin/podman stop --ignore --cidfile=/run/user/1000/container-freshrss.service.ctr-id (>
    Process: 2564 ExecStopPost=/usr/bin/podman rm -f --ignore --cidfile=/run/user/1000/container-freshrss.service.ctr>
   Main PID: 2360 (code=exited, status=0/SUCCESS)
        CPU: 252ms

Dec 15 10:02:58 HOSTNAME systemd[1367]: Starting Podman container-freshrss.service...
Dec 15 10:02:58 HOSTNAME systemd[1367]: Started Podman container-freshrss.service.
lines 1-13/13 (END)
```

I tried to update to the latest version, following the [Ubuntu installation guide](https://podman.io/getting-started/installation), however I got this output:

```
USERNAME@HOSTNAME:~$ sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/Release.key \
  | gpg --dearmor \
  | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg]\
    https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/ /" \
  | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null
sudo apt-get update -qq
sudo apt-get -qq -y install podman
curl: (22) The requested URL returned error: 404
gpg: no valid OpenPGP data found.
E: The repository 'https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_21  Release' does not have a Release file.
```

**Comment by vrothberg** [comment]
Thanks for coming back.  I did a fresh install of Mint and couldn't reproduce the issue.  I am a bit clueless at the moment.

**Comment by dancs-dev** [comment]
Thanks for checking that, this is much appreciated! I'm not sure if this is important/useful context, but I have tried this on both my laptop and main desktop PC, and the issue occurred on both. On both machines I previously had Una (20.3) and used the Linux Mint tool to upgrade to Vanessa. I will later try on another laptop that has just Vanessa (never upgraded) and see if it works on that. Also, I don't know if this matters given that I am using `systemctl --user`, but my home partitions are encrypted.

**Comment by vrothberg** [comment]
The upgrade part is interesting.  Looking forward to hear back whether it works on a fresh install for you.  I also ran the service with `--user`.

**Comment by Luap99** [comment]
The unit says
>  Main PID: 2360 (code=exited, status=0/SUCCESS)

So it sounds like the container process exited successfully?

**Comment by dancs-dev** [comment]
> The unit says
> 
> > Main PID: 2360 (code=exited, status=0/SUCCESS)
> 
> So it sounds like the container process exited successfully?

I think the behaviour is that it starts and stops straight away. Further, if I have restart always in there, the container will keep stopping/starting.

>The upgrade part is interesting. Looking forward to hear back whether it works on a fresh install for you. I also ran the service with --user.

It seems to work on my other machine with a fresh install of Vanessa! I wonder what is the cause of the problem in the upgraded version, and if it can be fixed. Would this be a Podman or Linux Mint issue?

**Comment by rhatdan** [comment]
@vrothberg PTAL
