### ISSUE TITLE
Cannot stop machine stuck starting up

### ISSUE THREAD

**Issue by OscarVanL** [containers/podman#16815]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I cannot stop a machine that is stuck starting.

Running `podman machine stop` reports success, but then `podman machine ls` still shows it is stuck starting.

**Steps to reproduce the issue:**

1. Reboot my PC
2. Podman machine gets stuck starting for some reason
3. `docker machine ls` shows a machine `Currently starting`.
4. `docker machine stop` reports success stopping the machine.
5. `docker machine ls` still shows a machine `Currently starting`.

**Describe the results you received:**

The machine does not stop, despite the console log indicating it has.

**Describe the results you expected:**

The machine stops, or an error message is displayed indicating why the machine couldn't be stopped.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Error: failed to connect: dial tcp [::1]:59759: connect: connection refused
```

**Output of `podman info`:**

```
Error: failed to connect: dial tcp [::1]:59759: connect: connection refused
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

(brew)
```
==> podman: stable 4.3.1 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0 and GPL-3.0-or-later
==> Dependencies
Build: go-md2man ✘, go@1.18 ✘
Required: qemu ✘
==> Options
--HEAD
        Install HEAD version
==> Caveats
To restart podman after an upgrade:
  brew services restart podman
Or, if you don't want/need a background service you can just run:
  /usr/local/opt/podman/bin/podman system service --time=0
==> Analytics
install: 26,952 (30 days), 76,459 (90 days), 241,167 (365 days)
install-on-request: 24,997 (30 days), 72,020 (90 days), 235,361 (365 days)
build-error: 8 (30 days)
```

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

4.3.1 is the latest version on brew. This problem isn't in the troubleshooting guide.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

MacOS Ventura 13.0.1

**Comment by mheon** [comment]
@ashley-cui PTAL

**Comment by ashley-cui** [comment]
Does `podman --log-level=debug machine start` work? If not, what's are the log outputs of that? This might be a concurrency issue, so if there are any details on how to reproduce, that would be helpful.

**Comment by OscarVanL** [comment]
Apologies, I needed to get my work done and what resolved it was removing the machine and recreating it. Sorry that this isn't very helpful on my part... Feel free to close if this isn't enough to go by.

**Comment by ashley-cui** [comment]
Sounds good, thanks @OscarVanL! Feel free to re-open if it happens again.

**Comment by zhanglolo** [comment]
Ran into the same issue

<img width="1195" alt="image" src="https://github.com/containers/podman/assets/27875371/de2103bb-eb17-43f8-98e6-43850bde8135">

<img width="249" alt="image" src="https://github.com/containers/podman/assets/27875371/1aa4602b-68c2-4a52-87bf-f41ba5f7dd34">


m1 mac os Ventura 13.4

**Comment by Aenimus** [comment]
I encountered this issue today.
M1 max macOS Ventura 13.3.3.1 (a)
Podman 4.5.0

`podman machine stop` -> told was successful
`podman machine start` -> complaint that machine is already running or starting
`podman machine info` -> machine is perpetually starting; subsequent stops claim success but change nothing

I managed to start the machine again after `podman machine rm`.
