### ISSUE TITLE
Container shows `ls -ld` as "nobody", I think subuid/subgid mappings auto-created are wrong!

### ISSUE THREAD

**Issue by neilspage2** [containers/podman#16836]
Here are some examples:

I ran a container as non-root, and checked its permissions (nobody nobody):

![image](https://user-images.githubusercontent.com/117413887/207639598-843292e9-81a5-4cc3-9790-3721b7e22653.png)

See example (weirdly subuid and subgid mappings are already created, I think they're wrong!)
```
# create dummy directory, chown a dummy user to it.
[rocky@netro ~]$ sudo mkdir /etc/testdir
[rocky@netro ~]$ chown testuser: /etc/testdir
[rocky@netro ~]$ sudo chown testuser: /etc/testdir

# bindmount to directory and check who owns it.
[rocky@netro ~]$ podman run -v /etc/testdir:/etc/testdir centos ls -ld /etc/testdir
drwxr-xr-x 2 nobody nobody 6 Dec 14 15:38 /etc/testdir
[rocky@netro ~]$ cat /etc/subuid
rocky:100000:65536
varnish:165536:65536
testuser:231072:65536
```

**Comment by giuseppe** [comment]
what is the id for `testuser`?

I don't see what is wrong there, `testuser` on the host simply is not mapped into the namespace for the user `rocky` that maps the id for `rocky` and the additional IDs [100000; 100000+65536-1]

**Comment by giuseppe** [comment]
Feel free to comment further, but I am closing the issue as I don't think this is a problem in Podman.
