### ISSUE TITLE
CI: Failed to upload artifacts after multiple tries: rpc error: code = Internal desc = 

### ISSUE THREAD

**Issue by Luap99** [containers/podman#16867]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Seeing a lot of CI flakes recently with this error:
```
Uploading 1 artifacts for /var/tmp/go/src/github.com/containers/podman/*.html
Uploaded /var/tmp/go/src/github.com/containers/podman/compose-podman-fedora-37-rootless-host.log.html
Error from upload stream: %!s(<nil>)
Failed to upload artifacts: rpc error: code = Internal desc = 
Re-trying to upload artifacts...Uploading 1 artifacts for /var/tmp/go/src/github.com/containers/podman/*.html
Uploaded /var/tmp/go/src/github.com/containers/podman/compose-podman-fedora-37-rootless-host.log.html
Error from upload stream: %!s(<nil>)
Failed to upload artifacts: rpc error: code = Internal desc = 
Re-trying to upload artifacts...
Failed to upload artifacts after multiple tries: rpc error: code = Internal desc = 
```

Rerunning the job works so it is a flake.

Some logs from today:
https://cirrus-ci.com/task/5751613239853056
https://cirrus-ci.com/task/5213705630121984

but I saw it a lot more often this week

**Steps to reproduce the issue:**

no idea, only happens sometimes

**Comment by vrothberg** [comment]
Same here.  Have seen it a lot in the past days.

**Comment by cevich** [comment]
Well damn, it's different artifacts it has trouble with too.  `html` here and `repo.tbz` [there](https://github.com/containers/podman/pull/16862#issuecomment-1354450850).  CI heavily depends on the `repo.tbz` artifact so simply disabling it as a workaround will break things.  I'll contact Cirrus-CI support and CC you guys, I don't think there's anything we can do from our end.

**Comment by cevich** [comment]
[Another example (for `repo.tbz).](https://cirrus-ci.com/task/4540299788156928)

**Comment by cevich** [comment]
Update: This issue should be fixed on the Cirrus-CI end, sometimes next week.  I'll check back in when I return from PTO in 3 weeks.

**Comment by Luap99** [comment]
I saw this again for the first time after the holidays:
https://cirrus-ci.com/task/6721358504132608
https://cirrus-ci.com/task/5118141869588480

**Comment by cevich** [comment]
Thanks for the task-links.

**Comment by cevich** [comment]
According to Cirrus, roll-out of the new upload scheme was delayed until the 13th.  So this seems very likely to be the reason for additional occurrences.  Nevertheless, it's deployed now, but I'll leave this issue open just in case it happens again.

**Comment by Luap99** [comment]
I have not seen it since so closing
