### ISSUE TITLE
WSL machine - consider adding pipe address to machine inspect output

### ISSUE THREAD

**Issue by arixmkii** [containers/podman#16860]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Currently pipe address of WSL machine is not published anywhere (it is built using the way one could read in code or documentation), but it would be better to allow this to be retrievable using some interface. There is ConnectionInfo with PodmanSocket path in it, but it is not used by WSL. Code [here](https://github.com/containers/podman/blob/main/pkg/machine/wsl/machine.go#L1616).

If it is used then naming will be a bit confusing (as one may argue that pipe in not a 100% socket), but it will allow some more flexibility. For example Podman Desktop instead of "guessing" [here](https://github.com/containers/podman-desktop/blob/564736e3313722b327b70f5a118b3487a4e5695e/extensions/podman/src/extension.ts#L114) the pipe address will just read using podman cli (like it already does reading list of machines).

This will also simplify things for alternative implementations (like QEMU machine https://github.com/containers/podman/issues/13006) as they will not have to mimic this behavior or Podman Desktop would need to become aware that alternative implementations exist.

**Steps to reproduce the issue:**

1. podman machine inspect --format '{{.ConnectionInfo.PodmanSocket.Path}}' 

**Describe the results you received:**
Outputs null

**Describe the results you expected:**
Outputs pipe address

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
4.3.1 and 4.4.0-dev
```

**Output of `podman info`:**

```
Intentionally skipped
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
Intentionally skipped
```

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

Yes (including built from sources)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

WSL machine

**Comment by arixmkii** [comment]
The most simple implementation - just adding it to output reusing all the available methods in the same file is pretty straightforward. 

The one which involves moving it to machine config structure is a more significant refactoring.

**Comment by arixmkii** [comment]
Still valid. There should be a way to communicate API listening interface address w/o guessing on the client side.

**Comment by arixmkii** [comment]
Did some experiments and due to lack of AF_UNIX support on Windows in nodejs https://github.com/nodejs/node/issues/35008 it is better to extend the structure to expose 2 different endpoints - one for Unix socket and one for named pipe. And then `machine inspect` could populate them accordingly. This is indeed an overhead for all non-Windows versions as the data structure will always be empty there, but it is really small. Alternative implementation would be to refactor this to expose it as a list of endpoints, where path, type and possible other attributes would appear, which would potentially scale better, but doesn't look like a mandatory addition at this point.

Expected result would look like:

```
podman machine inspect --format {{.ConnectionInfo.PodmanSocket.Path}} my-machine
C:\Temp\my-machine.sock

podman machine inspect --format {{.ConnectionInfo.PodmanNamedPipe.Path}} my-machine
//./pipe/my-machine
```

**Comment by rhatdan** [comment]
Care to open a PR to make this happen?

**Comment by arixmkii** [comment]
@rhatdan I will work on this. And after this one is finalized (reviewed and accepted) will submit a fix to Podman Desktop as well.

**Comment by rhatdan** [comment]
Great thanks.
