### ISSUE TITLE
FR/PR: gVisor/runsc-Support for Podman

### ISSUE THREAD

**Issue by SlitEye** [containers/podman#16877]
It would be great if Podman supports officially gVisor (or runsc) as Runtime. gVisor works already with the Docker and Kubernetes runtimes. With official support in Podman, so that Podman pods could also be additional protected with gVisor.

**Comment by rhatdan** [comment]
Try it out and tell us what is broken.

**Comment by vrothberg** [comment]
Thanks for reaching out.  Podman supports all runtimes implementing the OCI runtime specification, including gvisor. Note that gvisor requires root privileges, so I won't work as rootless podman (see https://github.com/google/gvisor/issues/311).
