### ISSUE TITLE
Podman auto-update should support non-systemd containers

### ISSUE THREAD

**Issue by dada513** [containers/podman#16879]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
podman auto-update currently relies on all containers being run by systemd

**Comment by baude** [comment]
I struggle with this.  In one way, it very much makes sense; and in others, not at all.  @vrothberg what say you?

**Comment by vrothberg** [comment]
> I struggle with this. In one way, it very much makes sense; and in others, not at all. @vrothberg what say you?

I say yes :) https://github.com/containers/podman/issues/10875 was/is tracking that.  `podman container clone` is supported now. In theory, the plumbing is there but I did not check how `container clone` deals with images.

I'm closing the issue as duplicate of https://github.com/containers/podman/issues/10875 where we can continue the conversation.
