### ISSUE TITLE
`podman export` to piped command results in `Error: open /dev/stdout: permission denied`

### ISSUE THREAD

**Issue by lancew-q** [containers/podman#16870]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. `podman export container-name | tar -C container-fs -xv`

**Describe the results you received:**

```
Error: open /dev/stdout: permission denied
```

**Describe the results you expected:**
Container export contents should pipe to the following command without error, and export contents should present at the specified location

**Additional information you deem important (e.g. issue happens only occasionally):**

It appears that this is a bug similar to: https://github.com/containers/podman/issues/12402

That issue was fixed by changing the call from `os.Create` to `os.OpenFile` with the correct flags. Likely this issue is fixed with a similar fix to: https://github.com/containers/podman/blob/main/pkg/domain/infra/tunnel/containers.go#L363

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.18.8
Built:        Wed Nov  9 13:43:58 2022
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19.2
Built:        Fri Nov 11 08:00:31 2022
OS/Arch:      linux/arm64```

**Output of `podman info`:**


**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
Have you tried this against the main branch?

**Comment by rhatdan** [comment]
When I execute your command I get

podman export f6 | tar -C container-fs xv
tar: You must specify one of the '-Acdtrux', '--delete' or '--test-label' options
Try 'tar --help' or 'tar --usage' for more information.

I get the same with Docker?

# docker export d3 | tar -C container-fs xv -Acdtrux
tar: You may not specify more than one '-Acdtrux', '--delete' or  '--test-label' optio

**Comment by Luap99** [comment]
Why do we need to open the file at all? We should just use fd 1 without having to call open.

**Comment by lancew-q** [comment]
@rhatdan command typed might be bad, might need `-` in front of xv args, e.g. ```podman export f6 | tar -C container-fs -xv```

@Luap99 My uninformed guess, usually this command is used like this ```podman export container-name -o path-to-tar.tar```, so sometimes it is passed an actual file location.

**Comment by Luap99** [comment]
> @Luap99 My uninformed guess, usually this command is used like this podman export container-name -o path-to-tar.tar, so sometimes it is passed an actual file location.

Sure but if we have `/dev/stderr` as path we can skip the open call since it is already open as fd 1.

**Comment by brad-jones** [comment]
Any idea when this fix will be released? Or are there daily builds of podman somewhere? For Windows?
I just hit this issue with `podman export foo | wsl --import foo bar -`
Anyway, I guess I'll create a temp file for now :(

**Comment by rhatdan** [comment]
We are cutting RC1 of Podman 4.4 this week.  So it should be released by end  of month or early next month.
If you are working on a MAC you might need to wait a couple of more weeks for the package to show up in Fedora CoreOS via Podman machine.
