### ISSUE TITLE
Make command-line options cross-platform

### ISSUE THREAD

**Issue by DaveJarvis** [containers/podman#16881]
While writing up a set of instructions for end users, I noticed that podman suggests different setup/configuration branches for Windows/MacOS than for Linux. While this makes sense from an architectural perspective (Linux doesn't need a Linux VM), it gets exposed as extra branching logic that is then required to be implemented by third-party integrations.

What would be great is being able to run the exact same set of instructions across all platforms to produce the same results. For example, on Linux:

``` bash
podman --fail-with "Skipping initialization (not needed)." machine init
podman --fail-with "Skipping virtual machine start-up (not needed)." machine start
podman load --quiet -i build/typesetter.tar.gz
podman run --network=host --rm -it typesetter /bin/sh --login -c "/usr/bin/ls"
```

Pie-in-the sky, would be a single command that blends all this functionality and "just works" across all platforms while taking into consideration the knowledge of podman's current state. That is:

``` bash
podman \
  --if-needed machine init \
  --if-needed machine start \
  --if-needed load -i build/typesetter.tar.gz --then \
  run --network=host --rm -it typesetter /bin/sh --login -c "ls"
```

That would initialize and start the VM on Windows/MacOS (or whatever other OS needs it) if necessary, load the image if it hasn't already been loaded, then run the given command against the container.

At present, my code includes:

``` java
  @Override
  public void start() throws FileNotFoundException {
    assert !IS_OS_LINUX;
    
    machine( "init" );
    machine( "start" );
  }

  private void machine( final String option ) throws FileNotFoundException {
    run( "machine", option );
  }

  private void run( final String... args ) throws FileNotFoundException {
    try {
      final var exe = CONTAINER.locate();
      final var path = exe.orElseThrow();
      final var commands = new LinkedList<String>();
      commands.add( path.toAbsolutePath().toString() );
      commands.addAll( Arrays.asList( args ) );

      final var builder = new ProcessBuilder( commands );
      final var process = builder.start();

      // etc.
      // process.getOutputStream();
    } catch( final Exception ex ) {
      throw new FileNotFoundException( CONTAINER.toString() );
    }
  }
```

The line that troubles me the most is `assert !IS_OS_LINUX;` because it means podman's operating system requirements have leaked into my software. The other leak is in creating the installation wizard, which needs to add an additional panel, but only for Windows/MacOS (non-Linux?) users:

``` java
    if( !SystemUtils.IS_OS_LINUX ) {
      panes.add( createContainerInitializationPanel() );
    }
```

I'm aware that I could opt to simply run the commands and if they fail on Linux, ignore it, and as they run on Windows/MacOS, let them finish in the background. That wouldn't give a great experience because (a) if something goes wrong, I'd still need to pop a panel with the error message; and (b) init/start takes a while, so it's nice to give users a status update showing what's happening.

**Comment by afbjorklund** [comment]
Be careful that you don't code things such as `machine`, depending on the OS. We had a **lot** of code break, when people started running Docker Desktop also on Linux (and the code was assuming a local Docker Engine). It would be better to have a separate boolean, and then have it default to `true`  on Windows/macOS and to `false` when running on Linux ?

Podman is extreme, since you can't even run the same client program without a special `--remote` parameter or it will run the "server" (well, Engine) locally. But you don't want to embed these things deep in your logic, and then Podman Desktop starts supporting Linux and people start preferring that for some odd reason instead of just running it natively...

**Comment by Luap99** [comment]
> `podman --fail-with "Skipping initialization (not needed)." machine init`
Well podman machine works on linux so I would say it should not skip it.

I don't think this is something podman should support, option parsing is already complicated enough I don't want to add more complexity when there is no real benefit for podman.

Podman works differently if it is remote or not, trying to hide this fact makes IMO things worse. Users must be aware that they are using the remote client when reading the docs. There are a lot of commands/options that only work in local mode.

**Comment by afbjorklund** [comment]
> Users must be aware that they are using the remote client when reading the docs.

Yeah, wouldn't want to do crazy things like renaming `podman-remote` to `podman` 😉

**Comment by DaveJarvis** [comment]
>  Well podman machine works on linux so I would say it should not skip it.

On Arch Linux, it produces an error message:

``` 
$ pacman -S podman
resolving dependencies...
looking for conflicting packages...
... snip ...
:: Proceed with installation? [Y/n] Y
... snip ...
$ podman machine init
Error: exec: "qemu-system-x86_64": executable file not found in $PATH
$  podman machine start
Error: podman-machine-default: VM does not exist
```

What I'd like to do is have a simple installation flow for the wizard that captures all operating systems. Users of my application don't care about containers or virtualization, nor do they want to know the difference between remote and non-remote podman instances. They want high-quality PDFs. Unfortunately, ConTeXt has a [complex setup](https://github.com/DaveJarvis/keenwrite/blob/main/container/Containerfile) that I'm trying to spare users, which is the impetus for using podman.

Here are some (incomplete) screenshots to give you a better idea. The first panel in the wizard tells what's happening (high level):

![install-01](https://user-images.githubusercontent.com/2131950/208476711-358b3140-df1b-4f94-9f37-82702b0b18d5.png)

The wizard branches depending on platform. Here's Windows (incomplete);

![install-02](https://user-images.githubusercontent.com/2131950/208476716-2fa9313b-3c4d-4ef1-ac3e-53c151a60b66.png)

Here's Linux (mostly complete):

![install-linux](https://user-images.githubusercontent.com/2131950/208478508-4c729da7-e6b9-456f-bdee-8637168c0684.png)

At this point, it would be nice if the wizard could converge back to a single flow line. 

![install-03](https://user-images.githubusercontent.com/2131950/208476720-59a7d699-4847-47b6-80ad-44624b754819.png)

On Windows and MacOS running `podman machine init` and `podman machine start` works great. On Arch Linux, users would see the following message:

![install-04](https://user-images.githubusercontent.com/2131950/208476722-16f87f9a-bb25-4357-88f4-c13e309de9c6.png)

That's why I was wondering whether there's anything we can do produce a different message.

**Comment by Luap99** [comment]
We can certainly always improve errors, that just requires us to know which ones.

Your problem here is just that on arch the required qemu dependencies are not installed by default. I don't even know about the other distros like fedora and debian at the moment. It is perfectly fine to not install these dependencies since podman works natively (without an extra VM) on linux. It is really up to you or better your users to decide how they want to use podman.

**Comment by DaveJarvis** [comment]
> It is really up to you or better your users to decide how they want to use podman.

My users are writers, authors, bloggers, and scientists. They really and truly don't care about podman, virtual machines, containers, etc. They care about generating PDFs. Imagine Microsoft Word requiring its users to know about podman before they can generate a PDF.

Pie-in-the-sky part two would be downloading and running podman standalone without going through an installer. This isn't possible for two reasons: (1) the installer has a version number, which prevents linking to the latest version (e.g., https://github.com/containers/podman/releases/latest/download/podman.exe); and (2) there's an installer GUI. From there, I could hide knowledge of podman and ConTeXt altogether, simply asking for permission to install, instead of having users jump through all these hoops, wizards, and other technical minutiae that are barriers to generating PDFs. However, a standalone headless version is an entirely different issue, so let's not get sidetracked. I only mention it to give you a flavour of what I'm trying to accomplish for the end users.

> We can certainly always improve errors, that just requires us to know which ones.

```
$ podman machine init
Error: exec: "qemu-system-x86_64": executable file not found in $PATH
$ podman machine start
Error: podman-machine-default: VM does not exist
```

Can we make those errors not be errors on Linux? Ideally, I'd like to control the message and hide the technical details (my users don't necessarily know about "qemu" or "podman-machine-default" or possibly even a "VM"---all those words are technobabble). For example, on Linux, I'd replace those error messages with the following phrases:

```
$ podman machine init
Note: Initialization is not required (skipping).
$ podman machine start
Note: Starting the virtual machine is not required (skipping).
```

Another idea would be to have a "quiet" argument that can specify a target OS:

```
$ podman --quiet linux machine init
$ podman --quiet linux machine start
```

That would suppress any error messages.

I suspect, though, that we should probably just close this ticket and I'll change my wizard to simply not run those commands on Linux.

**Comment by DaveJarvis** [comment]
> It would be better to have a separate boolean, and then have it default to true on Windows/macOS and to false when running on Linux ?

The wizard panels do that, but note that the installation instructions differ between operating systems, so an explicit check for MacOS is required:

``` java
  private WizardPane[] wizardPanes() {
    final var panes = new LinkedList<WizardPane>();

    panes.add( createIntroductionPane() );

    if( IS_OS_WINDOWS ) {
      panes.add( createContainerDownloadPanelWindows() );
      panes.add( createContainerInstallPanelWindows() );
    }
    else if( IS_OS_MAC ) {
      panes.add( createContainerInstallPanelMac() );
    }
    else if( IS_OS_LINUX ) {
      panes.add( createContainerInstallPanelLinux() );
    }
    else {
      panes.add( createContainerInstallPanelUniversal() );
    }

    panes.add( createContainerInitializationPanel() );
    panes.add( createTypesetterImageDownloadPanel() );

    return panes.toArray( WizardPane[]::new );
  }
```

As per the topic of this ticket, my preference would be to write:

``` java
    panes.add( createContainerInitializationPanel() );
    panes.add( createTypesetterImageDownloadPanel() );
```

(Ultimately, I'd rather not have to force either of these panels onto end users. Qué será, será.)
