### ISSUE TITLE
Opening reference documentation results in error

### ISSUE THREAD

**Issue by biergit** [containers/podman#16884]
Open https://docs.podman.io/en/latest/_static/api.html?version=v4.2 or any other version (propably) results in an error being displayed:

```Something went wrong...
Failed to load https://storage.googleapis.com/libpod-master-releases/swagger-v4.2.yaml: 403 Forbidden

Stack trace

u@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:8:75657
4182/loadExternalRef/<@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:8:76783
s@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:8:74778

ReDoc Version: 2.0.0-rc.75
Commit: d7440fb```

**Comment by Luap99** [comment]
link works for me, maybe some temporary hiccup? Can you try again?

**Comment by biergit** [comment]
Hi @Luap99 I still get the same error.

**Comment by biergit** [comment]
Interesting. I get the whole yaml content.

**Comment by Luap99** [comment]
Are you logged into your google account? Maybe google is blocking for some reason.
https://cloud.google.com/storage/docs/xml-api/reference-status#403%E2%80%94forbidden

**Comment by Luap99** [comment]
Closing as it seems a problem on your end

**Comment by biergit** [comment]
I can confirm it's working on my other device. Sorry for the inconvenience.

**Comment by biergit** [comment]
I logged out of my Google account and opened the page on a incognito window in Chrome. Still not working.

**Comment by Luap99** [comment]
weird, do you have a proxy or VPN configured that could be blocked? Maybe try a different web browser.

**Comment by biergit** [comment]
It was the proxy thank your for your time :)
