### ISSUE TITLE
podman generate kube defaults to no restartPolicy, meaning restartPolicy=always

### ISSUE THREAD

**Issue by mbach04** [containers/podman#16891]
```
podman version  
Client:       Podman Engine 
Version:      4.3.1
API Version:  4.3.1                                                                                                                                          
Go Version:   go1.19.2                                                                                                                                      
Built:        Fri Nov 11 15:01:27 2022
```

/kind bug
The default kube manifest created by podman generate kube has no restartPolicy set. When creating a systemd unit file from this pod, podman warns you that your pod's restartPolicy is set to always, the default when undefined.

**Describe the results you received:**
```
podman generate systemd --files --name nginx-pod                                                                                  WARN[0000] Container 7691df68e80cfb2402b9394fa857b4480a69a43027d0883c0071916abde419be has restart policy "always" which can lead to issues on shutdown: consider recreating the container without a restart policy and use systemd's restart mechanism instead 
```
**Describe the results you expected:**
Expect the default to be more sensible interpretation by podman generate kube or podman generate systemd, one of these should default to a policy that aligns better with controlling pods via systemd.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version  
Client:       Podman Engine 
Version:      4.3.1
API Version:  4.3.1                                                                                                                                          
Go Version:   go1.19.2                                                                                                                                      
Built:        Fri Nov 11 15:01:27 2022
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
podman-4.3.1-1.fc37.x86_64 
```

Yes

**Comment by vrothberg** [comment]
@mbach04, I recommend using the [systemd template](https://docs.podman.io/en/latest/markdown/podman-generate-systemd.1.html#kubernetes-integration) for running K8s YAML in systemd.

For your specific case, I am not sure what Podman could do.  Kubernetes defaults to restart=always so `podman kube play` is using that to remain compatible.  Using that in systemd does not always make sense, so Podman is warning about it.  You can always change the policy via `generate systemd --restart-policy=on-failure`, for instance.

**Comment by vrothberg** [comment]
>  The template generated fails to stop and start the pods unfortunately (maybe a separate bug/issue I should submit).

I'd love to know more about that.  If you find the time and a reproducer, would you open another issue?

> I do think however, there's something missing in the user experience here, though I can't say what the right approach is to fix it.

Since Podman is already warning, the message should probably point to a man page explaining the systemd template.

> Some more extended examples would be incredibly helpful.

I will take a look at the man page and try to elaborate more on the template.

Thanks for your input, @mbach04!

**Comment by vrothberg** [comment]
> Since Podman is already warning, the message should probably point to a man page explaining the systemd template.

That won't work as I had intended.  I will keep thinking.

**Comment by mbach04** [comment]
Circling back here. I embraced the kube systemd template approach. It actually worked out well for my purposes. Thanks!

**Comment by vrothberg** [comment]
> Circling back here. I embraced the kube systemd template approach. It actually worked out well for my purposes. Thanks!

Thanks, I am glad you like it.  Stay tuned for the Podman 4.4 release early next year.  [Quadlet](https://github.com/containers/quadlet/) is now part of Podman and added support for running K8s YAML as well. This will be the recommended way for running Podman workloads in systemd starting with the 4.4 release.
