### ISSUE TITLE
podman system df --format '{{json .}}' is not compliant with docker output

### ISSUE THREAD

**Issue by benoitf** [containers/podman#16902]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I found an extension that parse the output of the JSON generated by `system df` command and the output is not rendered using the same format than `docker` command

**Steps to reproduce the issue:**

1. `podman system df --format '{{json .}}'`

**Describe the results you received:**
{"Type":"Images","Total":5,"Active":1,"Size":1092221757,"Reclaimable":1092139196}

**Describe the results you expected:**
{"Active":"21","Reclaimable":"12.76GB (86%)","Size":"14.79GB","TotalCount":"73","Type":"Images"}

Reclaimable should have the size displayed with unit (like 12.76GB) and then it should have the percentage displayed
The same for the Size field.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19
Git Commit:   814b7b003cc630bf6ab188274706c383f9fb9915
Built:        Thu Nov 10 15:26:55 2022
OS/Arch:      darwin/amd64

Server:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19.2
Built:        Fri Nov 11 16:01:27 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by benoitf** [comment]
It looks like it's missing the percentage in the output

**Comment by rhatdan** [comment]
We must not be printing this out in regular podman system df commands, so open an issue on that, and we can add that output.

**Comment by benoitf** [comment]
ok I will
