### ISSUE TITLE
not possible to share tty (e.g. usb-dongle) devices with privileged containers

### ISSUE THREAD

**Issue by fho** [containers/podman#16925]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I want to run a rootless privileged podman container and access a Sonoff USB zigbee stick in the container.
The container shows up on the host as /dev/ttyACM0.
The host user has access to the device.

In the container the device node is missing.
I found the previous related bugfix https://github.com/containers/podman/pull/3593.
I believe the issue is that in `AddPrivilegedDevices()` devices are skipped if their path starts with `/dev/tty`:
https://github.com/containers/podman/blob/d20dbcd155e09842e8c2c81e14f7a97aed755f44/pkg/util/utils_linux.go#L93-L95

**Steps to reproduce the issue:**

1. have a tty device to share on the host:
```
$ ls -la /dev/ttyACM0
crw-rw---- 1 root dialout 166, 0 Dec 22 18:30 /dev/ttyACM0
$ groups
homeassistant dialout
```
2. run a privilieged podman container and check if /dev/ttyACM0 is available:
```
$ podman run  -i -t --privileged  ghcr.io/home-assistant/home-assistant:2022.12.7 ls /dev/tty*
```

**Describe the results you received:**
/dev/ttyACM0 device file does not exist in the container

**Describe the results you expected:**
/dev/ttyACM0 exists  in the  container

**Additional information you deem important (e.g. issue happens only occasionally):**

I can share the device via `--device` if i start it as unprivileged container.

**Output of `podman version`:**

```
podman version 4.3.1
```

**Output of `podman info`:**

N/A

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

N/A

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

No, same if-condition exist in the latest commit in main (d20dbcd) branch.

**Comment by vrothberg** [comment]
Thanks for reaching out, @fho!

@giuseppe  do you recall the reasoning for excluding tty?

**Comment by giuseppe** [comment]
IIRC they are excluded by default otherwise they could mess up with the ttys on the host

**Comment by rhatdan** [comment]
I wonder if there is a better way to handle this.

If the user specifies `--device /dev/ttyACM0` shouldn't we allow it in?

**Comment by fho** [comment]
https://github.com/containers/podman/issues/15878 is why the check was introduced.

What is if the condition is changed to match only /dev/tty[0-9]+ paths? (as it was also suggested [here](https://github.com/containers/podman/issues/15878#issuecomment-1289994608)).

**Comment by giuseppe** [comment]
that makes sense to me.  Would you like to open a PR with that change?

**Comment by fho** [comment]
great, yes I can create a PR for it.
I should find some time do it latest on the following weekend (until 15.1).

**Comment by mupuf** [comment]
> great, yes I can create a PR for it. I should find some time do it latest on the following weekend (until 15.1).

Sorry, I couldn't wait anymore as I had to create a boot2container release without introducing this regression. I hope you had not spent too long on your patch, and if you did, please share it so that we could improve my patch and make it co-developed by you :)

**Comment by fho** [comment]
@mupuf I haven't, only ~10min to change the condition and give it a quick test.
I had it still open to investigate if I need to change testcases. 
I'm glad that you created the PR, thanks! :-)

**Comment by mupuf** [comment]
Great! This makes you a great reviewer and tested for the PR then ;)

**Comment by scottsweb** [comment]
I think I hit this today. Homeassistant running `priveledged` and trying to pass in `/dev/ttyUSB0` as a device. The container cannot see it at all.

Any idea when this fix may become available and is there anything I can do to fix it in the meantime?

**Comment by mupuf** [comment]
> I think I hit this today. Home assistant running `priveledged` and trying to pass in `/dev/ttyUSB0` as a device. The container cannot see it at all.
> 
> Any idea when this fix may become available and is there anything I can do to fix it in the meantime?

It should be released as part of podman 4.4... which I assume is about to be released any day now!

**Comment by mupuf** [comment]
Well, turns out I should have checked, Podman 4.4 was released 9h ago \o/

https://github.com/containers/podman/releases/tag/v4.4.0

**Comment by scottsweb** [comment]
Fantastic. Thanks @mupuf... with any luck that will be an update for Silverblue shortly.
