### ISSUE TITLE
UBI8-INIT: Systemd Fails with Entrypoint script

### ISSUE THREAD

**Issue by djarbz** [containers/podman#16923]
/kind bug

**Description**

I am attempting to setup a container that runs 2 systemd units that work together.  
I am also working in a rootless environment.  
I need to run an entrypoint script to configure the services based on ENV passed into the container.  
I have learned that by using `exec "@"` to launch the CMD it will take on PID 1.  
I have also learned that Podman will [recognize](https://developers.redhat.com/blog/2019/04/24/how-to-run-systemd-in-a-container#enter_podman:~:text=If%20the%20command,without%20any%20modifications.) the CMD as systemd and perform some magic on the backend.  
I am wondering if, because I have an entrypoint, that podman no longer recognizes systemd and does not perform the magic to make it work.  

**Steps to reproduce the issue:**
  
Containerfile
```Containerfile
FROM registry.redhat.io/ubi8/ubi-init:8.7-9

COPY --chmod=777 entrypoint.sh /

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/sbin/init"]
```

Entrypoint.sh
```bash
#!/bin/bash

echo "Starting ${@}"
exec "$@"
```

Build: `podman build -t localhost/playground:latest .`
Run: `podman run -it --rm --replace --name playground localhost/playground:latest`

**Describe the results you received:**

```
Starting /sbin/init
Failed to mount tmpfs at /run: Operation not permitted
[!!!!!!] Failed to mount API filesystems, freezing.
Freezing execution.
```

**Describe the results you expected:**

My entrypoint script should process correctly and pass on to systemd once it is complete.  
Systemd should then continue to startup and run correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19.4
Built:        Wed Dec 31 18:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```yaml
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon_100:2.1.5-1_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: c9f7f19eb82d5b8151fc3ba7fbbccf03fdcd0325'
  cpuUtilization:
    idlePercent: 95.15
    systemPercent: 2.24
    userPercent: 2.61
  cpus: 4
  distribution:
    codename: bullseye
    distribution: debian
    version: "11"
  eventLogger: file
  hostname: chuwi
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.0-17-amd64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 1331339264
  memTotal: 8157454336
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun_100:1.7.2-1_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.6
      commit: 18cf2efbb8feb2b2f20e316520e0fd0b6c41ef4d
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_100:1.2.0-1_amd64
    version: |-
      slirp4netns version 1.2.0
      commit: unknown
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.1
  swapFree: 1462542336
  swapTotal: 2147479552
  uptime: 2209h 8m 4.00s (Approximately 92.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  docker.io:
    Blocked: false
    Insecure: false
    Location: docker.io
    MirrorByDigestOnly: false
    Mirrors:
    - Insecure: false
      Location: 127.0.0.1:5000
      PullFromMirror: ""
    - Insecure: false
      Location: registry.digitalcloudbackup.net
      PullFromMirror: ""
    - Insecure: false
      Location: mirror.gcr.io
      PullFromMirror: ""
    Prefix: docker.io
    PullFromMirror: ""
  search:
  - docker.io
store:
  configFile: /home/ansible/.config/containers/storage.conf
  containerStore:
    number: 23
    paused: 0
    running: 22
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/ansible/.local/share/containers/storage
  graphRootAllocated: 471384244224
  graphRootUsed: 111601143808
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 424
  runRoot: /run/user/1000/containers
  volumePath: /home/ansible/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 0
  BuiltTime: Wed Dec 31 18:00:00 1969
  GitCommit: ""
  GoVersion: go1.19.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

NOTE: I am using the Alvistack repo to get the latest Podman on Debian.
```
podman/unknown,now 100:4.3.1-1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Debian GNU/Linux 11 (bullseye)

I am also open to suggestions on better ways to enable runtime configuration on the container when systemd is PID1.

**Comment by mheon** [comment]
You'll need to use `--systemd=always` on the Podman command line we cannot autodetect systemd as init if it's not actually init, but run by an entrypoint script.

**Comment by djarbz** [comment]
Excellent, thank you!
That is what I was missing.

Are you able to share what exactly Podman does on the backend?
I'm probably going to have to document how people can get the container I am developing to work on Docker as well.

**Comment by mheon** [comment]
https://github.com/containers/podman/blob/main/libpod/container_internal_linux.go#L195-L306

Highlights:
- Adds the `container_uuid` environment variable
- Ensures that `/tmp`, `/var/log/journal`, `/run`, and `/run/lock` are on separate tmpfs mounts
- Ensures that cgroups are available inside the container (this is where most of the complexity creeps in, given that we have to worry about cgroups v1 vs v2)

**Comment by djarbz** [comment]
Thank you very much for your help!
