### ISSUE TITLE
Podman Go API gives a segmentaion fault when I try to limit a container's memory

### ISSUE THREAD

**Issue by IronMatt97** [containers/podman#16931]
**Is this a BUG REPORT or FEATURE REQUEST? **

/kind bug

**Description**

Hi, I am trying to use the Go Api in order to limit the memory a container at the moment of its creation. It looks like when I try to do it, a segmentation fault occurs. Maybe the problem is just I misunderstood how to use the Api function, but can you tell me if this is the correct way to limit a container's memory?

**Steps to reproduce the issue:**

s := specgen.NewSpecGenerator(image, false)
s.Image = image
memory_limit := (1024 * 1048576)  // Define the memory limit
s.ResourceLimits.Memory.Limit = &memory_limit  // Define the pointer to it
r, err := containers.CreateWithSpec(ctx, s, new(containers.CreateOptions))

**Describe the results you received:**
Indipendentely from the number I use to set memory limit, the container doesn't start and the application crashes giving a segmentation fault. If I comment the lines regarding the limit, everything works fine.

**Describe the results you expected:**
The container should start with the limit set correctly

**Output of `podman version`:**

```
podman version 4.4.0-dev
```

**Output of `podman info`:**

```
host:
  arch: amd64
  buildahVersion: 1.28.1-dev
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2.0.25+ds1-1.1_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpuUtilization:
    idlePercent: 94.83
    systemPercent: 1.02
    userPercent: 4.15
  cpus: 8
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: myron
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.0-56-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 9733828608
  memTotal: 16505917440
  networkBackend: cni
  ociRuntime:
    name: runc
    package: containerd.io_1.6.14-1_amd64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.4
      commit: v1.1.4-0-g5fd4c4d
      spec: 1.0.2-dev
      go: go1.18.9
      libseccomp: 2.5.3
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.0.1-2_amd64
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 2147479552
  swapTotal: 2147479552
  uptime: 0h 18m 30.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/matteo/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/matteo/.local/share/containers/storage
  graphRootAllocated: 502392610816
  graphRootUsed: 155030450176
  graphStatus: {}
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 6
  runRoot: /tmp/containers-user-1000/containers
  volumePath: /home/matteo/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.0-dev
  Built: 1669287925
  BuiltTime: Thu Nov 24 12:05:25 2022
  GitCommit: 34cc61d167fe429eb76383cf2a09701a9b2533dd
  GoVersion: go1.18.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```
podman/jammy,now 3.4.4+ds1-1ubuntu1 amd64 [installato]
```

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

No

**Comment by baude** [comment]
perhaps you could provide the backtrace?

**Comment by baude** [comment]
and a reproducer example that is complete would also speed up the answer

**Comment by IronMatt97** [comment]
Here you go, this is the backtrace when I try to run the code I've written above:
-----------------------------------------------------------------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xf5a359]

goroutine 99 [running]:
github.com/matteo/s/internal/container.(*PodmanFactory).Create(0xc0001d1970, {0xc0000d20f0, 0x2b}, 0xc000328400)
        /home/matteo/Documenti/Workspaces/Tesi/s/internal/container/podman.go:55 +0x219
github.com/matteo/s/internal/container.NewContainer({0xc0000d20f0?, 0x0?}, {0xc0004b7000, 0xaac}, 0x0?)
        /home/matteo/Documenti/Workspaces/Tesi/s/internal/container/container.go:17 +0x56
github.com/matteo/s/internal/node.NewContainerWithAcquiredResources(0xc0001baba0)
        /home/matteo/Documenti/Workspaces/Tesi/s/internal/node/pool.go:195 +0x1a5
github.com/matteo/s/internal/node.NewContainer(0xc0001baba0)
        /home/matteo/Documenti/Workspaces/Tesi/s/internal/node/pool.go:176 +0x5f
github.com/matteo/s/internal/scheduling.handleColdStart(0xc0005b8360)
        /home/matteo/Documenti/Workspaces/Tesi/s/internal/scheduling/scheduler.go:325 +0x2e
github.com/matteo/s/internal/scheduling.(*DefaultLocalPolicy).OnArrival(0xc0001d1660, 0xc0005b8360)
        /home/matteo/Documenti/Workspaces/Tesi/s/internal/scheduling/policy_default.go:80 +0xa5
created by github.com/matteo/s/internal/scheduling.Run
        /home/matteo/Documenti/Workspaces/Tesi/s/internal/scheduling/scheduler.go:96 +0x49e
----------------------------------------------------------------

To reproduce the issue it is enough to run the instruction I've written in my previous message. Removing/commenting the lines 

memory_limit := (1024 * 1048576) // Define the memory limit
s.ResourceLimits.Memory.Limit = &memory_limit // Define the pointer to it

allows the container creation without a segmentation fault.

**Comment by Luap99** [comment]
both `ResourceLimits` and `Memory` are also a pointers so you need to make sure they point to a valid struct before you can set the limit on them

**Comment by IronMatt97** [comment]
Oh silly me, thank you for the help, I added the lines you suggested me and it seems to work now. For people who will read this the code is:

s := specgen.NewSpecGenerator(image, false)
s.Image = image
memory_limit := (1024 * 1048576) // Define the memory limit
s.ResourceLimits = new(specs.LinuxResources)
s.ResourceLimits.Memory = new(specs.LinuxMemory)
s.ResourceLimits.Memory.Limit = &memory_limit // Define the pointer to it
r, err := containers.CreateWithSpec(ctx, s, new(containers.CreateOptions))


Thanks :)
