### ISSUE TITLE
`podman kube play` be a bit like `docker compose`

### ISSUE THREAD

**Issue by alexec** [containers/podman#16957]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Ok. I don't want you to be `docker compose`. Instead I want some of the conveniences of `docker compose`:

* Keep running in the foreground and show me the status of each container.
* Ctrl+C causes all the containers to stop.

**Comment by alexec** [comment]
@ygalblum @vrothberg @umohnani8 @cevich ☝️ thoughts?

**Comment by vrothberg** [comment]
Being worked on in https://github.com/containers/podman/pull/16717 :-)

**Comment by alexec** [comment]
Hi. I'm a project lead for Argo. Argo Workflows also has a  `--wait` option. 

* Waits for SIGTERM.

It also has a `--watch` option:

* Wait for either (a) SIGTERM or (b) all containers to exit.
* Once a second, prints the state off the containers to the terminal (i.e. `watch kubectl get pod`)

I'd love to see both of these features in `podman kube play`

Looking at your PR does it does it implement  `--wait`, not `--watch`?

**Comment by vrothberg** [comment]
Thanks!  Since you commented on the PR, let's continue the conversation in https://github.com/containers/podman/pull/16717#pullrequestreview-1233916223.
