### ISSUE TITLE
`podman kube play` - automatic cold/hot re-load/re-build

### ISSUE THREAD

**Issue by alexec** [containers/podman#16955]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I've been evaluating various tools such as Podman, Gitpod, Codespaces, Skaffold, Draft, DevSpace, Telepresence, Docker Dev Environments, Coder. 

It's a busy space right now! (But who will win eh?)

**Describe the results you received:**

Comparables have a feature where you can edit source code and the container is re-built. E.g.:

* Auto-rebuild on source change.
* Rsync or mirror source code.
* Hot-reload.

**Comment by alexec** [comment]
@ygalblum @vrothberg @umohnani8 @cevich ☝️ thoughts?

**Comment by rhatdan** [comment]
How would you envision this applying to podman kube play? Why wouldn't a higher level tool just watch the kube.yaml file and rerun podman kube play --replace?

**Comment by alexec** [comment]
That would work. I think it would depend on the scope of `kube play`. IHMO making it a more full feature dev tool is probably not what the authors envisaged, yet without this if feels … incomplete.

**Comment by rhatdan** [comment]
I think in another PR you talked about a --watch option, in addition to a --wait option.
Is this what you envision, where we would create pods based on a k8s yaml file, and then have podman monitor the file for changes (potentially via fnotify) and then if the YAML file changes, recreate the pods.

**Comment by alexec** [comment]
No. These are two different features. `--watch` should display the correct state of the pod, similar to `Kubectl describe pod`. Auto-build should monitor the build directory (e.. `image`) and if that changes, re-build.

The challenge is - that directory probably does not contain everything need for the build.

**Comment by rhatdan** [comment]
Would `podman kube describe YAML` make sense for that command?

**Comment by alexec** [comment]
I guess I want that to automatically update. Just like `docker compose up`

**Comment by rhatdan** [comment]
When you say `docker compose up` automatically updates, you are saying that a change to a Dockerfile or the YAML will cause the image to be rebuilt and containers recreated?

Or does the user have to run another `docker compose up` command to trigger this?
