### ISSUE TITLE
RHEL 7.9 and PODMAN 1.6.4 - Not able to make the rootful containers to talk to each other

### ISSUE THREAD

**Issue by manjunathpremkumar** [containers/podman#16975]
Hi,

I tried creating the podman network and ran the pod run command for containers, I am missing something basics with podman 1.6.4. IT WORKS WITH DOCKER PERFECTLY FOR BELOW COMMANDS WHEN REPLACED WITH PODMAN TO DOCKER
a) Creating the network,
sudo podman network create demo
b) I am running 3 containers in this network
Sudo podman run -d -network demo -name -p -e
c) Checked the Sudo podman network inspect demo it defaults bridge type. DO I NEED TO DO PORT MAPPING or ROUTE THE TRAFFIC IN IPTABLES?
sudo podman network inspect sitespeed
[
{
"cniVersion": "0.4.0",
"name": "sitespeed",
"plugins": [
{
"bridge": "cni-podman1",
"ipMasq": true,
"ipam": {
"ranges": [
[
{
"gateway": "10.89.0.1",
"subnet": "10.89.0.0/24"
}
]
],
"routes": [
{
"dst": "0.0.0.0/0"
}
],
"type": "host-local"
},
"isGateway": true,
"type": "bridge"
},
{
"capabilities": {
"portMappings": true
},
"type": "portmap"
},
{
"backend": "",
"type": "firewall"
}
]
}
]

Can someone help here?Guide me pls

**Comment by rhatdan** [comment]
RHEL 7 is in maintanaince mode and will not be updated with new features or bug fixes, except for security fixes. You need to update to RHEL8 or later for newer versions of Podman.
