### ISSUE TITLE
 Error: dial unix qmp_podman-machine-default.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by josefdostal** [containers/podman#16976]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

During ```podman machine start``` I keep getting the following error:

```bash
$ podman machine start
    Starting machine "podman-machine-default"
    Error: dial unix /run/user/{uid}/podman/qmp_podman-machine-default.sock: connect: no such file or directory
```

I have quite limited permissions on the server and I can only request each particular command if root privs are necessary but I was able to create /run/user/{uid}/podman/podman.sock using ```systemctl --user enable podman.socket``` so I guess podman should be able to create necessary .sock files during machine initialization, right?

**Steps to reproduce the issue:**

1. Install the container-tools following the offical guide for RHEL8.

```bash
sudo yum update -y
sudo yum module enable -y container-tools:rhel8
sudo yum module install -y container-tools:rhel8
sudo loginctl enable-linger $(id -un)
```

1. During ```podman machine init``` I kept getting error that qemu-system is missing in $PATH so I installed qemu-kvm and linked qemu-system somewhere in PATH to it, following [this article](https://techviewleo.com/solve-qemu-system-x86_64-executable-file-not-found-in-path/)
So something like this:

```bash
sudo yum install qemu-kvm.x86_64 -y
ln -s /usr/bin/qemu-kvm ~/.local/bin/qemu-system-x86_64
export PATH=${PATH}:~/.local/bin 
```

1. Also gvproxy was apparently missing so I installed that one too

```bash
sudo yum install podman-gvproxy.x86_64 -y
```

1. After this procedure still not being successful I tried to install podman package itself hoping it will fix/add some eventual dependencies but with zero impact.

```bash
sudo yum install podman.x86_64 -y
```

**Describe the results you received:**
Even though I dug through all these error I got stuck on the above mentioned error:

```bash
$ podman machine start
    Starting machine "podman-machine-default"
    Error: dial unix /run/user/{uid}/podman/qmp_podman-machine-default.sock: connect: no such file or directory
```

**Describe the results you expected:**
Honestly, I would at least expect the machine to start

**Additional information you deem important (e.g. issue happens only occasionally):**
In fact I have 2 similar servers with similar permissions I need to setup this way (one of which doesn't have access to internet which doesn't seem to be a problem outside of having to download the machine image manually) and I am getting the same error on both.

**Output of `podman version`:**

```text
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.7
Built:        Wed Oct 26 21:23:47 2022
OS/Arch:      linux/amd64
```

**Output of `podman info`:**

```text
host:
  arch: amd64
  buildahVersion: 1.27.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.3-1.module+el8.6.0+16771+28dfca77.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.3, commit: 3571057ed895294b72709767db30b16722c8c24a'
  cpuUtilization:
    idlePercent: 99.66
    systemPercent: 0.18
    userPercent: 0.16
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "8.6"
  eventLogger: file
  hostname: hostname
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 42
      size: 1
    - container_id: 1
      host_id: 420
      size: 1
    uidmap:
    - container_id: 0
      host_id: 4200
      size: 1
    - container_id: 1
      host_id: 42000
      size: 1
  kernel: 4.18.0-372.19.1.el8_6.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 20049068742
  memTotal: 27507528893
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.3-3.module+el8.6.0+16986+c8760fe3.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.3
      spec: 1.0.2-dev
      go: go1.17.12
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/{uid}/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.module+el8.6.0+16771+28dfca77.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 3687527647
  swapTotal: 3687527647
  uptime: 2554h 13m 1.00s (Approximately 106.42 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: ${HOME}/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: ${HOME}/.local/share/containers/storage
  graphRootAllocated: 1609826304000
  graphRootUsed: 14462459904
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/{uid}/containers
  volumePath: ${HOME}/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1666812227
  BuiltTime: Wed Oct 26 21:23:47 2022
  GitCommit: ""
  GoVersion: go1.18.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman` or `brew info podman`):**

```text
podman-4.2.0-4.module+el8.7.0+17064+3b31f55c.x86_64
```

**Have you tested with the latest version of Podman and have you checked [the Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md)?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

These should be physical servers

**Comment by rhatdan** [comment]
@ashley-cui PTAL

**Comment by ashley-cui** [comment]
Hmm. From what I recall, on the start of the machine, QEMU makes the qmp socket, not us, we just wait to read it, and I'm unable to reproduce this at the current moment. On another note, as you're on RHEL8, is there a reason you're using podman machine instead of regular podman?

**Comment by josefdostal** [comment]
Hello, thank you for looking into the issue.
There were several problems with running the containers because of the environment so I hoped this would solve it.
Anyway I resolved the problems already so I don't need the podman machine anymore. Thank you.

**Comment by ssbarnea** [comment]
This has almost 100% reproduction rate on Github Runners , https://github.com/ansible/vscode-ansible/actions/runs/4365862989/jobs/7635076406 - I also happens with latest 4.2.2 too.

It should be noted that default GHA Runners do have nested virtualization disabled, as this might impact this issue.

**Comment by viplifes** [comment]
I reproduced this on podman version 4.4.4

Step 1 
remove prev podman (version 4.4.4)
```
sudo /opt/podman/bin/podman-mac-helper uninstall && sudo rm /etc/paths.d/podman-pkg && sudo rm -rfv /opt/podman && sudo rm -rfv ~/.config/containers && sudo rm -rfv ~/.local/share/containers && sudo rm -rfv ~/.ssh/podman-machine-default ~/.ssh/podman-machine-default.pub
```

Step2
Install podman from pkg - podman-installer-macos-amd64-v4.4.4.pkg

Step 3
```
dimir@Dmitrys-MacBook-Pro ~ % podman machine init && podman machine start
Downloading VM image: fedora-coreos-37.20230401.2.0-qemu.x86_64.qcow2.xz: done
Extracting compressed file
Image resized.
Machine init complete
To start your machine run:

	podman machine start

Starting machine "podman-machine-default"
Waiting for VM ...
Error: dial unix /var/folders/sf/c_8m_1zn6rlfgqc4cl97rgcr0000gn/T/podman/podman-machine-default_ready.sock: connect: no such file or directory
dimir@Dmitrys-MacBook-Pro ~ % podman machine list
NAME                     VM TYPE     CREATED        LAST UP            CPUS        MEMORY      DISK SIZE
podman-machine-default*  qemu        3 minutes ago  Currently running  1           2.147GB     107.4GB
dimir@Dmitrys-MacBook-Pro ~ % podman machine stop
Waiting for VM to exit...
Machine "podman-machine-default" stopped successfully
dimir@Dmitrys-MacBook-Pro ~ % podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Mounting volume... /Users:/Users
Mounting volume... /private:/private
Mounting volume... /var/folders:/var/folders

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

	podman machine set --rootful

API forwarding listening on: /var/run/docker.sock
Docker API clients default to this address. You do not need to set DOCKER_HOST.

Machine "podman-machine-default" started successfully
```

**Comment by tiararodney** [comment]
A similar problem concerning the same file:

```sh
uname -moprsv 
Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020 arm64 arm
podman --version
podman version 4.5.0
$ podman machine start                                                                  
Error: checking VM active: dial unix /var/folders/vb/3kp9xbzx14g8xc93srd9nm_w0000gn/T/podman/qmp_podman-machine-default.sock: conn
ect: permission denied                      
```
is able to be worked around by removing the default machine and creating a non-default machine. I haven't looked at the sources, but it seems that the default machine is only, and this exception should be caught.

The aforementioned problem occurs in multi-user *NIX environments when using a shared podman installation, as well as separate installations for multiple users.

A wild guess would be that there is some randomization/seeding missing when generating the machine `~/.config/containers/podman/machine/qemu/podman-machine-default.json` polluting the `/var/folders/vb/` directory namespace.

**Comment by ashley-cui** [comment]
Was able to track this down yesterday, it comes from a leftover gvproxy process. Let's see if I can get a fix in for it..

**Comment by vrothberg** [comment]
@ashley-cui can you still reproduce?  I haven't seen this flake but know that quite some work went it making start+stop more robust and fault tolerant.

**Comment by ashley-cui** [comment]
ATM I haven't seen this one in a while.

**Comment by vrothberg** [comment]
I'll take a stab and close assuming this was fixed along with various other flakes.  Please reopen if it pops up again.
