### ISSUE TITLE
[Feature]: Kube Play: add support for Job

### ISSUE THREAD

**Issue by ygalblum** [containers/podman#17011]
### Feature request description

Currently, podman supports `pods` and `deployments`. While `pod` is the base element, K8S users will usually not deploy pods. Instead, they will deploy deployments for long lasting workloads and jobs for single shot operations. 
When using systemd, the behavior of jobs seems to be a better fit as it will not have Podman monitor the pods but instead pass the monitoring and hence the handling of the restart policy to systemd. 
For example, the supported valued for `restartPolicy` for containers in a `Job` are only `Never` or `OnFailure`.  So, a default `restartPolicy` of `Never`, with `parallelism` and `completions` set to 1 will result in propagating the exit status of the pod to systemd, letting it decide whether or not the service should be restarted (depending on the restart policy of the systemd unit)

### Suggest potential solution

Passing a [job](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#job-v1-batch) to `podman kube play` will result in running the containers listed in the Pod specification

### Have you considered any alternatives?

As explained, the user may use deployments or pods directly. But, it will not provide the same experience

### Additional context

While the trigger for this feature request is Quadlet and systemd, podman will directly benefit from this added support as well

**Comment by rhatdan** [comment]
Makes sense to me.

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by fsdrw08** [comment]
any updates?

**Comment by umohnani8** [comment]
A design doc has been created for this and it is on the to do list, targeting this for 4.7.

**Comment by mrgleeco** [comment]
link to design doc / discussions?

**Comment by adelton** [comment]
@umohnani8 Could you please show the link to the design doc?

**Comment by fsdrw08** [comment]
any updates?

**Comment by umohnani8** [comment]
Yup, I have a WIP in PR - will clean it up and open a PR by next week.

**Comment by jaimehrubiks** [comment]
This makes a lot of sense. I believe podman is getting a lot of attention in HPC, I myself find it very flexible and simple for rootless use cases, where developers test their own containers, and in many cases they then send them to kubernetes. For HPC, jobs are the most common kubernetes yaml.

**Comment by rhatdan** [comment]
@umohnani8 Still have the PR?  Maybe someone else can take it over?
