### ISSUE TITLE
Improve basic usage tutorial by mentioning limited support for "--latest" / "-l"

### ISSUE THREAD

**Issue by biergit** [containers/podman#17019]
The commands in the [basic usage tutorial](https://github.com/containers/podman/blob/main/docs/tutorials/podman_tutorial.md) do not work for Windows and probably neither for Mac (see ["--latest"](https://docs.podman.io/en/latest/markdown/podman-inspect.1.html#latest-l) documentation).
I would suggest to either mention the current limitation around using the "--latest" flag or go with something that works in all environments to improve the first impression when picking up Podman.

**Comment by Luap99** [comment]
@biergit I agree, are you interested in opening a PR to fix it?

**Comment by rhatdan** [comment]
The PR for this is still open, but not moving forward.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Care to take a look?
