### ISSUE TITLE
[Bug]: --mount=type=cache RUN caches live in the VM on macOS

### ISSUE THREAD

**Issue by eschnett** [containers/podman#17013]
### Issue Description

I am building an image, which uses a `RUN --mount=type=cache,target=/opt/software ...` command. I am also using macOS, where podman runs in a VM. I find that the cache lives inside this VM and not on the host.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Use podman on macOS
2. Build an image using a `--mount=type=cache`
3. Look into `/var/tmp` on the host -- no cache is found ther
4. Look into `/var/tmp` inside the VM that podman uses (`podman machine ssh`; `ls /var/tmp`): the cache is there

### Describe the results you received

The cache lives inside the VM

### Describe the results you expected

The cache lives on the host

### podman info output

```shell
$ podman --version
podman version 4.3.1
$ uname -a
Darwin redshift.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64 x86_64 i386 Darwin
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

I installed podman via MacPorts

**Comment by flouthoc** [comment]
Hi @eschnett , on `macOS` all the builds are executed inside the VM so cache stays there so other builds can reuse it, otherwise it defeats the purpose of `--mount=type=cache`.

**Comment by eschnett** [comment]
Would it be possible to mount `/var/tmp/buildah-cache` from the host, i.e. the macOS system? This would still work as a cache, and would make managing the cache more similar to what happens on Linux.

**Comment by rhatdan** [comment]
You should be able to do this by yourself via the podman machine command. Or edit the containers.conf, I believe.

**Comment by eschnett** [comment]
The home directory seems to be mounted via this stanza:
```JSON
  {
   "ReadOnly": false,
   "Source": "/Users/eschnett",
   "Tag": "vol0",
   "Target": "/Users/eschnett",
   "Type": "9p"
  }
```

What should I use for `Tag` and `Type`, respectively, for `/var/tmp/buildah-cache`? Do you have a pointer to documentation?

**Comment by rhatdan** [comment]
[machine]
volumes = [
   "$HOME:$HOME",
   "/var/tmp/buildah-cache:/var/tmp/buildah-cache".
]

In containers.conf might work.  You might need to recreate the machine.

**Comment by rhatdan** [comment]
Since you have a solution, I can close.
