### ISSUE TITLE
[Bug]: aarch64-darwin: podman installed from nixpkgs uses wrong path for edk2-aarch64-code.fd

### ISSUE THREAD

**Issue by n8henrie** [containers/podman#17026]
### Issue Description

podman 4.3.1 installed via nixpkgs, I get an error about the path to `edk2-aarch64-code.fd` upon `podman machine start`. Several prior related issues and PRs:

- https://github.com/containers/podman/issues/12379
- https://github.com/containers/podman/issues/13394
- https://github.com/NixOS/nixpkgs/issues/169118
- https://github.com/NixOS/nixpkgs/pull/163015
- https://github.com/containers/podman/issues/12379

It looks like the current code requires minimal changes to work with nixpkgs -- just resolve the symlink to the real location of qemu in the nix path and everything works.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `nix shell nixpkgs#podman`
2. podman machine init
3. podman machine start

### Describe the results you received

Error about path to `edk2-aarch64-code.fd` (sorry, now getting [a different error about the socket](https://github.com/containers/podman/issues/16163) -- will update this with the error output after a reboot).

UPDATE:

```console
$ podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code 1, stderr: qemu-system-aarch64: -drive file=edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on: Could not open 'edk2-aarch64-code.fd': No such file or directory
```

### Describe the results you expected

Podman starts

### podman info output

```shell
$ podman --version
podman version 4.3.1


`podman info` gives an error
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

### Additional environment details

MacOS 13.1, nixpkgs 22.11

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by ashley-cui** [comment]
Reopening, as the patch was reverted.
