### ISSUE TITLE
[Bug]: default runtime mismatches

### ISSUE THREAD

**Issue by binary01010** [containers/podman#17049]
### Issue Description

podman  --runtime string             Path to the OCI-compatible binary used to run containers, default is /usr/bin/runc
podman system info 
ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17

### Steps to reproduce the issue

1.podman --help >--runtime string 
2.podman system info ociRuntime

### Describe the results you received

crun != runc

### Describe the results you expected

default crun

### podman info output

```shell
--runtime string             Path to the OCI-compatible binary used to run containers, default is /usr/bin/runc


ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by giuseppe** [comment]
please fill all the requested information.

Do you have any `/etc/containers/containers.conf` file that overrides the runtime?  What version of Podman?

**Comment by rhatdan** [comment]
Since we never heard back and this works fine for me, closing.
