### ISSUE TITLE
www.podman.io flaking - netavark bug?

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#17044]
Tests trying to fetch from `www.podman.io` are flaking. Sometimes a `curl` timeout, sometimes a DNS name resolution failure:
```
curl: (6) Could not resolve host: www.podman.io
```
I can't tell if it's a real problem with `podman.io` and/or its nameservers, or a connectivity hiccup, or if it's a Neta/Aardvark problem. The latter seems unlikely because I've only seen this with `podman.io`.

* fedora-37 : int podman fedora-37 root container
  * PR #16926
    * [01-03 10:37](https://api.cirrus-ci.com/v1/artifact/task/6109612989480960/html/int-podman-fedora-37-root-container.log.html#t--podman-run-network-connection-with-private--1)
    * [01-03 10:37](https://api.cirrus-ci.com/v1/artifact/task/6109612989480960/html/int-podman-fedora-37-root-container.log.html#t--podman-run-network-connection-with-private--2)
    * [01-03 10:37](https://api.cirrus-ci.com/v1/artifact/task/6109612989480960/html/int-podman-fedora-37-root-container.log.html#t--podman-run-network-connection-with-private--3)
    * [01-03 09:18](https://api.cirrus-ci.com/v1/artifact/task/5391671492345856/html/int-podman-fedora-37-root-container.log.html#t--podman-run-network-connection-with-default-bridge--1)
    * [01-03 09:18](https://api.cirrus-ci.com/v1/artifact/task/5391671492345856/html/int-podman-fedora-37-root-container.log.html#t--podman-run-network-connection-with-default-bridge--2)
    * [01-03 09:18](https://api.cirrus-ci.com/v1/artifact/task/5391671492345856/html/int-podman-fedora-37-root-container.log.html#t--podman-run-network-connection-with-default-bridge--3)
* fedora-37 : int podman fedora-37 root host
  * PR #17025
    * [01-07 10:01](https://api.cirrus-ci.com/v1/artifact/task/5304840541175808/html/int-podman-fedora-37-root-host.log.html#t--podman-run-network-connection-with-private--1)
    * [01-07 10:01](https://api.cirrus-ci.com/v1/artifact/task/5304840541175808/html/int-podman-fedora-37-root-host.log.html#t--podman-run-network-connection-with-private--2)
    * [01-07 10:01](https://api.cirrus-ci.com/v1/artifact/task/5304840541175808/html/int-podman-fedora-37-root-host.log.html#t--podman-run-network-connection-with-private--3)
* fedora-37 : int remote fedora-37 root host [remote]
  * PR #17025
    * [01-07 10:38](https://api.cirrus-ci.com/v1/artifact/task/5446881216561152/html/int-remote-fedora-37-root-host.log.html#t--podman-run-network-connection-with-default--1)
    * [01-07 10:38](https://api.cirrus-ci.com/v1/artifact/task/5446881216561152/html/int-remote-fedora-37-root-host.log.html#t--podman-run-network-connection-with-default--2)
    * [01-07 10:38](https://api.cirrus-ci.com/v1/artifact/task/5446881216561152/html/int-remote-fedora-37-root-host.log.html#t--podman-run-network-connection-with-default--3)
  * PR #16989
    * [01-04 02:27](https://api.cirrus-ci.com/v1/artifact/task/6605324090605568/html/int-remote-fedora-37-root-host.log.html#t--podman-run-network-connection-with-private--1)
    * [01-04 02:27](https://api.cirrus-ci.com/v1/artifact/task/6605324090605568/html/int-remote-fedora-37-root-host.log.html#t--podman-run-network-connection-with-private--2)
    * [01-04 02:27](https://api.cirrus-ci.com/v1/artifact/task/6605324090605568/html/int-remote-fedora-37-root-host.log.html#t--podman-run-network-connection-with-private--3)
  * PR #16985
    * [01-04 10:29](https://api.cirrus-ci.com/v1/artifact/task/5034564356145152/html/int-remote-fedora-37-root-host.log.html#t--podman-run-network-connection-with-private--1)
    * [01-04 10:29](https://api.cirrus-ci.com/v1/artifact/task/5034564356145152/html/int-remote-fedora-37-root-host.log.html#t--podman-run-network-connection-with-private--2)
    * [01-04 10:29](https://api.cirrus-ci.com/v1/artifact/task/5034564356145152/html/int-remote-fedora-37-root-host.log.html#t--podman-run-network-connection-with-private--3)
  * PR #16901
    * [12-20 12:10](https://api.cirrus-ci.com/v1/artifact/task/4828706640756736/html/int-remote-fedora-37-root-host.log.html#t--podman-run-network-connection-with-default-bridge--1)
    * [12-20 12:10](https://api.cirrus-ci.com/v1/artifact/task/4828706640756736/html/int-remote-fedora-37-root-host.log.html#t--podman-run-network-connection-with-default-bridge--2)
    * [12-20 12:10](https://api.cirrus-ci.com/v1/artifact/task/4828706640756736/html/int-remote-fedora-37-root-host.log.html#t--podman-run-network-connection-with-default-bridge--3)
  * PR #16820
    * [12-29 06:40](https://api.cirrus-ci.com/v1/artifact/task/5567758776139776/html/int-remote-fedora-37-root-host.log.html#t--podman-run-network-connection-with-default--1)
    * [12-29 06:40](https://api.cirrus-ci.com/v1/artifact/task/5567758776139776/html/int-remote-fedora-37-root-host.log.html#t--podman-run-network-connection-with-default--2)
    * [12-29 06:40](https://api.cirrus-ci.com/v1/artifact/task/5567758776139776/html/int-remote-fedora-37-root-host.log.html#t--podman-run-network-connection-with-default--3)
    * [12-26 08:29](https://api.cirrus-ci.com/v1/artifact/task/5037528152014848/html/int-remote-fedora-37-root-host.log.html#t--podman-run-network-connection-with-default--1)

There are many more but I'm getting tired of scanning through flake logs.

**Comment by Luap99** [comment]
podman.io is hosted on github infra. I think one easy change would be to switch it to something like `google.com` and hope that this is a server side problem and not a client side bug.

**Comment by rhatdan** [comment]
Should do redhat.com before google.

**Comment by edsantiago** [comment]
@containers/netavark-maintainers PTAL. It's possible that this is a network-infrastructure problem in Cirrus or gcloud... but it's also possible that our networking is broken.

**Comment by Luap99** [comment]
Do you know when this started? I know there was a bug in netavark v1.3 which could cause this. VM image updates should include netavark v1.4 but the automation_image CI is still broken so I cannot update it at the moment.

**Comment by edsantiago** [comment]
First instance of `Could not resolve host: www.podman.io` is [Dec 5](https://api.cirrus-ci.com/v1/artifact/task/5122504415510528/html/int-podman-fedora-37-root-host.log.html#t--podman-run-network-connection-with-default--1)

First instance of `command timed out ... wget www.podman.io` is [Nov 2](https://api.cirrus-ci.com/v1/artifact/task/5073820221440000/html/int-podman-fedora-37-root-host.log.html#t--podman-run-network-connection-with-default--1)

**Comment by edsantiago** [comment]
Reopening, because #17053 is unlikely to fix anything

**Comment by Luap99** [comment]
I agree, the common theme here is that it fails with `--network private` or `bridge` which means it uses netavark on f37, f36 uses CNI and at least from the instances listed here it is not effected. Therefore it it most likely a netavark bug.

**Comment by Luap99** [comment]
@edsantiago New images with a newer netavark were merged last week, does it still happen?
I don't remember it seeing it this week so far.

**Comment by edsantiago** [comment]
Sorry for the late reply: we're having a **LOT** of flakes this week, and I've had to categorize them one by one, which takes time.

The last two instances of this flake were on January 16, both on a PR that did not include #16525 (the update-images PR). I feel comfortable closing. Thank you!
