### ISSUE TITLE
[Bug]: Podman loads but does not remove temporary docker-tar#### files from under tmpdir (e.g. /var/tmp/)

### ISSUE THREAD

**Issue by msbrod** [containers/podman#17078]
### Issue Description

Podman will load temporary image files under tmpdir (e.g. /var/tmp) but does not remove them.  Therefore, the filesystem hosting tmpdir eventually fills up.  Seems like a bug since podman is not cleaning up after itself.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Set variable TMPDIR
2. Load a .tar.gz into storage with podman load --tmpdir=<tmpdir> -i <filename>
3. Check /var/tmp directory for files called docker-tar*

### Describe the results you received

The filesystem hosting tmpdir eventually fills up.  Manual intervention is required to clean the directory.  Reference closed issue #5411 and associated fix #5412 (which is really not a fix, just allows for the problem to be moved somewhere else)

### Describe the results you expected

Unused temporary images should be removed.

### podman info output

```shell
podman version 3.2.3
podman-3.2.3-0.11.module+el8.4.0+12050+ef972f71.x86_64
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Is this issue fixed in an upstream release?

**Comment by mheon** [comment]
Please try a more recent Podman release, we do not support old releases on Github. If this is a RHEL system you can file a support case to have it addressed.

**Comment by Austinpayne** [comment]
> Please try a more recent Podman release, we do not support old releases on Github. If this is a RHEL system you can file a support case to have it addressed.

@mheon Out of curiosity, can you point to the commit that fixed this? I didn't find mention of it in the release changelogs.

**Comment by rhatdan** [comment]
We prefer that you create a new one with all of the info and a reproducer.
