### ISSUE TITLE
CI: timeout in new kube tests

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#17076]
PR #16880 broke CI. There's a new timeout flake, cause unknown, but it is pretty likely to be caused by 16880. @ygalblum please fix or revert ASAP. I looked more closely at the logs this morning, and it's not the known checkpoint bug, this is a new one.

As a side note, this was a bad merge. We should not merge PRs in which there are six retries on a new unexplained flake.

* fedora-36 : int podman fedora-36 rootless host
  * PR #17062
    * [01-10 19:49](https://api.cirrus-ci.com/v1/task/6278617336905728/logs/main.log)
* fedora-36 : int remote fedora-36 root host [remote]
  * PR #17062
    * [01-10 19:49](https://api.cirrus-ci.com/v1/task/6630461057794048/logs/main.log)
* fedora-37 : int podman fedora-37 root container
  * PR #16880
    * [01-10 09:48](https://api.cirrus-ci.com/v1/task/6003133705355264/logs/main.log)
    * [01-10 05:47](https://api.cirrus-ci.com/v1/task/6286027363450880/logs/main.log)
    * [01-10 03:20](https://api.cirrus-ci.com/v1/task/5796602250526720/logs/main.log)
    * [01-09 14:56](https://api.cirrus-ci.com/v1/task/6522168020828160/logs/main.log)
    * [01-09 11:05](https://api.cirrus-ci.com/v1/task/5147689231319040/logs/main.log)
    * [01-08 08:41](https://api.cirrus-ci.com/v1/task/4545583269019648/logs/main.log)

**Comment by ygalblum** [comment]
@edsantiago The retries were added following this comment https://github.com/containers/podman/pull/16880#issuecomment-1373491992 from @Luap99. The reason for the retry is that `podman kube play` may return before the container is ready to get connections. As a result, in the CI, the test fails to connect to the port (while locally it passes all the time).

Furthermore, I don't understand why you think this change causes the test to hang. Looking at the test logs you've provided, these tests pass and most of them are not even marked as "SLOW TEST". Moreover, this PR was merged only yesterday and I've been seeing such issues with the CI before that.

I don't mind reverting the test code, but I don't understand why you think this code is the source of the issue

**Comment by edsantiago** [comment]
Post hoc, ergo propter hoc. Imperfect (to say the least!) reasoning, but I have a pretty good sense for CI flakes and these are new ones. They started with your PR. We are now seeing them in other PRs. There could be a common factor just slightly before your PR, in which the timeout didn't trigger, but the smart money is on it being something in your PR.

**Comment by ygalblum** [comment]
But, look at the commits following the merge of my PR. While they are red, they fail on other tests and the test that timeouts for me passes

**Comment by edsantiago** [comment]
Ah, sorry, this may be a terminology issue. A "test flake" is a condition in which a test is unreliable: it passes sometimes, fails other times, for reasons yet unknown. Test flakes are very hard to reproduce, hence hard to understand or fix.

**Comment by Luap99** [comment]
All I said is that the single test should have a retry for tcp/udp connection, the full suite should never hang like that.

**Comment by Luap99** [comment]
Looking at the code we must likely need to add `conn.SetDeadline()` otherwise a read can block forever.

**Comment by ygalblum** [comment]
Please see #17083

**Comment by edsantiago** [comment]
#17083 is merged, closing this in hopes that the problem is fixed. Thanks @ygalblum.
