### ISSUE TITLE
podman-kube@.service template: expected inactive, got active

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#17093]
New flake in system tests:
```
not ok 318 podman-kube@.service template
...
# podman pod kill test_pod
# 5a7b23b8b7028aa541d7c4643abd78c8bed281101c255b6f182bc75f8871c2e6
# #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# #|     FAIL: systemd service transitioned to 'inactive' state: podman-kube@-tmp-podman_bats.QBwJWn-test.yaml.service
# #| expected: 'inactive'
# #|   actual: 'active'
# #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
### [sys] 305 podman-kube@.service template
* fedora-37 : sys podman fedora-37 rootless host
  * PR #16806
    * [01-05 14:37](https://api.cirrus-ci.com/v1/artifact/task/5889729187545088/html/sys-podman-fedora-37-rootless-host.log.html#t--00305)
    * [01-03 14:35](https://api.cirrus-ci.com/v1/artifact/task/4570588768370688/html/sys-podman-fedora-37-rootless-host.log.html#t--00305)

...as well as a few minutes ago in [f36 root](https://api.cirrus-ci.com/v1/artifact/task/4694960453189632/html/sys-podman-fedora-36-root-host.log.html#t--00318)

**Comment by edsantiago** [comment]
Seen Jan 27 in [f36 root](https://api.cirrus-ci.com/v1/artifact/task/6174523536441344/html/sys-podman-fedora-36-root-host.log.html#t--00320). This is a v4.4 PR, but I've looked at the history and am 99% sure it includes #17108.

**Comment by edsantiago** [comment]
Tuesday, [f37 rootless](https://api.cirrus-ci.com/v1/artifact/task/4943156697890816/html/sys-podman-fedora-37-rootless-host.log.html#t--00321), in a `v4.4.1-rhel` PR.

**Comment by edsantiago** [comment]
Slightly different symptom:
```
$ podman auto-update --format {{.Unit}},{{.Container}},{{.Image}},{{.Updated}},{{.Policy}}
podman-kube@-tmp-podman_bats.7CpZcR-test.yaml.service,8318174f781d (test_pod-a),quay.io/libpod/testimage:20221018,failed,registry
podman-kube@-tmp-podman_bats.7CpZcR-test.yaml.service,fc19694d7b22 (test_pod-b),localhost/image:KITdAADDq7,failed,local
Error: restarting unit podman-kube@-tmp-podman_bats.7CpZcR-test.yaml.service during rollback: error starting systemd unit "podman-kube@-tmp-podman_bats.7CpZcR-test.yaml.service" expected "done" but received "failed"
```
in [f37 rootless sqlite](https://api.cirrus-ci.com/v1/artifact/task/6282826287415296/html/sys-podman-fedora-37-rootless-host-sqlite.log.html#t--00361)

**Comment by vrothberg** [comment]
> in [f37 rootless sqlite](https://api.cirrus-ci.com/v1/artifact/task/6282826287415296/html/sys-podman-fedora-37-rootless-host-sqlite.log.html#t--00361)

I am unable to locate the journal logs. Can you help me @edsantiago ?

**Comment by edsantiago** [comment]
I'm so sorry! This got lost amid other things today. From the colorized log page:
1. Scroll to top (`Home` key)
2. Click the **Task ID**
3. Click the red accordion banner to make it fold up, because it's too long.
4. Click the **run journal** accordion. Then, to view [full logs](https://api.cirrus-ci.com/v1/task/6282826287415296/logs/journal.log), click arrow-in-box icon at top right.

The really important thing to remember is to scroll to the top of the colorized log.

**Comment by vrothberg** [comment]
Thanks so much, @edsantiago!

**Comment by vrothberg** [comment]
The other linked flakes show
> Jan 24 07:08:34 packer-63c7bbc7-e9aa-44a4-c9f5-bca2897e2841 systemd[3374]: Started podman-92305.scope.
Jan 24 07:08:34 packer-63c7bbc7-e9aa-44a4-c9f5-bca2897e2841 podman[92311]: Error: no pod with name or ID test_pod found: no such pod

which I will investigate now.  I suspect something in `kube play --replace`.

**Comment by vrothberg** [comment]
Also seeing 
> Error: open /tmp/podman_bats.BNwBhn/test.yaml: no such file or directory

**Comment by vrothberg** [comment]
OK, I am fairly confident that commit 1541ce56cf2d fixed the issue in main (notice the `s/inactive/failed/` change in the test). 4.4.1-rhel does _not_ have this commit (see https://github.com/containers/podman/blob/v4.4.1-rhel/test/system/250-systemd.bats#L429-L441), so the test will flake there unless we file a BZ and backport.

As mentioned above, the "slightly different symptom" is the the EBUSY fart (see https://github.com/containers/podman/issues/17216) preventing container cleanup.

@edsantiago feel free to double check. The `Error: no pod with name or ID test_pod found: no such pod` are red herrings that popped up when cleaning up the systemd service after the test failure.

**Comment by vrothberg** [comment]
Shall we leave the issue open (i.e., backport to the branches?) or are we cool given main is good?

**Comment by vrothberg** [comment]
Closing as I believe https://github.com/containers/podman/commit/1541ce56cf2d8784f570903a0ac5ea871dc029f5 fixed the issue.  Please reopen if the flake still happens on the main branch.
