### ISSUE TITLE
[Bug]: `--add-host` option of `podman build` command is not effective in the created container

### ISSUE THREAD

**Issue by ljeda** [containers/podman#17092]
### Issue Description

Hi team, I have a feeling that I'm doing something stupid, but I'm not able to understand what I am missing. I'm trying to use the `--add-host` option with the `podman build` command but it has no effect on the container that is then being built based on the produced image. The DOC states that this option should add an entry to the _/etc/hosts_ file, but I don't observe that behavior. The same switch used with the `podman run` command works as expected, so I'm surprised the option used in both commands is not giving similar results.

### Steps to reproduce the issue

`podman_bug_reporting # cat Dockerfile`
FROM alpine:latest
RUN echo "I do not need this line"
`podman_bug_reporting # podman image build --add-host=build_example_host:192.168.100.100 -t bug_example_image .`
STEP 1/2: FROM alpine:latest
Resolved "alpine" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/alpine:latest...
Getting image source signatures
Copying blob sha256:a9eaa45ef418e883481a13c7d84fa9904f2ec56789c52a87ba5a9e6483f2b74f
Copying config sha256:04eeaa5f8c35b8206a15c12425498c37ecd2181e0ef202bea24a2382e4dd240f
Writing manifest to image destination
Storing signatures
STEP 2/2: RUN echo "I do not need this line"
I do not need this line
COMMIT bug_example_image
--> a75d9592534
Successfully tagged localhost/bug_example_image:latest
a75d95925349d29d92076310f36f5e28516f2dd19ec57495ce898588c64ddf3f
`podman_bug_reporting # podman run -d -t bug_example_image`
8014fe73a3820769fd45e7c330e0f77a9bf1a7a85a24a83ee582da6935ff77e1
`podman_bug_reporting # podman exec -it 8014fe73a3820769fd45e7c330e0f77a9bf1a7a85a24a83ee582da6935ff77e1 /bin/sh`
/ # cat /etc/hosts
127.0.0.1	localhost localhost.localdomain localhost4 localhost4.localdomain4
::1	localhost localhost.localdomain localhost6 localhost6.localdomain6
10.88.0.2	8014fe73a382 relaxed_golick
/ # ^C
/ # 
`podman_bug_reporting # podman run -d -t --add-host=run_example_host:192.168.100.100 bug_example_image`
200c64094cdc1ee8e55bf0d2916ad5dceefecaa3df5c904b6142325765185c77
`podman_bug_reporting # podman exec -it 200c64094cdc1ee8e55bf0d2916ad5dceefecaa3df5c904b6142325765185c77 /bin/sh`
/ # cat /etc/hosts
**192.168.100.100	run_example_host**
127.0.0.1	localhost localhost.localdomain localhost4 localhost4.localdomain4
::1	localhost localhost.localdomain localhost6 localhost6.localdomain6
10.88.0.3	200c64094cdc admiring_lamport
/ # ^C
/ # 

### Describe the results you received

The output of the `cat /etc/hosts` command executed in the first container does not contain any custom entry, the output of the same command executed in the second container contains only the entry added with the `podman run` command:
**192.168.100.100	run_example_host**

### Describe the results you expected

The output of the `cat /etc/hosts` command executed in both the containers should include the following line:
**192.168.100.100	build_example_host**

### podman info output

```shell
podman_bug_reporting # podman version
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19
Git Commit:   814b7b003cc630bf6ab188274706c383f9fb9915
Built:        Thu Nov 10 15:31:24 2022
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19.2
Built:        Fri Nov 11 16:00:31 2022
OS/Arch:      linux/arm64
podman_bug_reporting # podman info
host:
  arch: arm64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.5-1.fc37.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 99.69
    systemPercent: 0.23
    userPercent: 0.08
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "37"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.0.16-300.fc37.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 1272381440
  memTotal: 2049794048
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.7.2-3.fc37.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.7.2
      commit: 0356bf4aff9a133d655dc13b1d9ac9424706cac4
      rundir: /run/user/501/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/501/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.aarch64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 2h 52m 17.00s (Approximately 0.08 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 2274508800
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/user/501/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 1668178831
  BuiltTime: Fri Nov 11 16:00:31 2022
  GitCommit: ""
  GoVersion: go1.19.2
  Os: linux
  OsArch: linux/arm64
  Version: 4.3.1

podman_bug_reporting #
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

I'm running podman on my Mac OS laptop with M1 Max Apple Silicon processor.

**Comment by Luap99** [comment]
`--add-host` adds the entry to the build container, i.e. it is only there during your RUN statements. It is never added in the final image. It wouldn't make sense either since podman and docker by default do not use the /etc/hosts file from the image.

```
$ podman build --add-host test:10.0.0.1 .
STEP 1/2: FROM alpine
STEP 2/2: RUN cat /etc/hosts
10.0.0.1        test
127.0.0.1       localhost localhost.localdomain localhost4 localhost4.localdomain4
::1     localhost localhost.localdomain localhost6 localhost6.localdomain6
127.0.0.1       host1
127.0.0.1       host2
192.168.188.25  host.containers.internal
10.0.2.100      c2a92f803d80 alpine-working-container
COMMIT
--> 8250eea3f65
8250eea3f6500cbb0b4fd50341b65785bcd1ea627ef11a2fc87ae75b886911c9
$ cat Containerfile 
FROM alpine
RUN cat /etc/hosts
```

**Comment by ljeda** [comment]
OK, thanks for the explanation. In short, my followup question would be: how then add a custom _/etc/hosts_ entry automatically to every container build from specific image?

In the service I use I don't have any control over the `podman/docker run` statement execution - I'm only providing the image to be used (by means of _docker.io_ repository details) and then I'm presented with a result of running my image by the service.

The problem is, the networking is not correctly set up and the container created from my image cannot resolve the hostname I'm trying to connect to from that container. The IP seems to be visible for it, but unfortunately the server certificate used in secure communication is created based on the hostname of the server I'm connecting to, so when I'm using the IP address instead, the connection cannot be established due to the certificate issue. If I do `podman exec -it <name> /bin/bash` into my container and manually add the entry to the _/etc/hosts_ file, the secure connection can be established successfully, so I'm looking for a way to ensure the hostname of the server is always resolvable out-of-the-box when the container is being created from my image. My first guess was to add `RUN echo "IP hostname" > /etc/hosts` to the Dockerfile but I've learnt that podman is in charge of the _/etc/hosts_ file so I thought the `--add-host` option of `podman build` is exactly what I was looking for (as I'm looking for a way to get the same result as if I would add `--add-host` option to `podman run` command but already encode this custom _/etc/hosts_ file entry during the image creation).

**Comment by Luap99** [comment]
By default podman uses entries from the /etc/hosts on the host so you could also add you desired entry there. 

Alternatively, there is a containers.conf option `base_hosts_file` that can be used to overwrite hosts entries.
https://github.com/containers/common/blob/main/docs/containers.conf.5.md#containers-table

I think you can set this option to `"image"` and then it will actually add the entries to the images hosts file during build and when run is used it will also use the entries from there.

NOTE: Because you use podman machine, this conf file must be changed in the VM, i.e. podman machine ssh.

**Comment by ljeda** [comment]
OK, thanks for the extended help, I appreciate that.
