### ISSUE TITLE
podman run --pod: fatal: systemstack called from unexpected goroutinetimeout: the monitored command dumped core

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#17099]
Not-quite-new flake. First seen in October, but it was a one-off and I swept it under the rug. Happened again today:
```
not ok 292 podman pod create --share
...
# podman pod create --share ipc --name xuez5nsw7r
dc14d7b800ac866b9783692eccf9c0a76675e75015550cfe24a59f2055d53292
# podman pod inspect xuez5nsw7r --format {{.SharedNamespaces}}
[ipc]
# podman run --rm --pod xuez5nsw7r --hostname foobar quay.io/libpod/testimage:20221018 hostname
fatal: systemstack called from unexpected goroutinetimeout: the monitored command dumped core
[ rc=133 (** EXPECTED 0 **) ]
```
### [sys] podman pod create --share
* fedora-36 : sys podman fedora-36 root host
  * PR #16732
    * [01-12 11:10](https://api.cirrus-ci.com/v1/artifact/task/4669776409133056/html/sys-podman-fedora-36-root-host.log.html#t--00292)

I don't expect anyone to do anything about this: it's too infrequent. Am filing because we've seen it twice, so we'll be seeing it again.

**Comment by Luap99** [comment]
I would expect a stack trace from go if the bug was in our code. This sounds like something went wrong in the go runtime. Without a reproducer this will be impossible to debug.

**Comment by rhatdan** [comment]
Since we never heard more feedback, closing.
