### ISSUE TITLE
play kube override with {tcp,udp} should keep {other} from YAML

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#17101]
New e2e test flake:
```
Expected
      <*net.OpError | 0xc000de49b0>: {
          Op: "read",
          Net: "udp",
          Source: <*net.UDPAddr | 0xc00142ae70>{IP: [127, 0, 0, 1], Port: 43120, Zone: ""},
          Addr: <*net.UDPAddr | 0xc00142aea0>{IP: [127, 0, 0, 1], Port: 19012, Zone: ""},
          Err: <*poll.DeadlineExceededError | 0x1fc1a20>{},
      }
  to be nil
```

* fedora-37 : int podman fedora-37 root host
  * PR #17077
    * [01-12 16:44](https://api.cirrus-ci.com/v1/artifact/task/6291458718695424/html/int-podman-fedora-37-root-host.log.html#t--podman-play-kube-override-with-udp-should-keep-tcp-from-YAML-file--1)
    * [01-12 15:35](https://api.cirrus-ci.com/v1/artifact/task/4994621495836672/html/int-podman-fedora-37-root-host.log.html#t--podman-play-kube-override-with-tcp-should-keep-udp-from-YAML-file--1)
    * [01-12 15:35](https://api.cirrus-ci.com/v1/artifact/task/4994621495836672/html/int-podman-fedora-37-root-host.log.html#t--podman-play-kube-override-with-tcp-should-keep-udp-from-YAML-file--2)
    * [01-12 15:35](https://api.cirrus-ci.com/v1/artifact/task/4994621495836672/html/int-podman-fedora-37-root-host.log.html#t--podman-play-kube-override-with-tcp-should-keep-udp-from-YAML-file--3)

@ygalblum PTAL

**Comment by ygalblum** [comment]
Testing a loopback over a UDP connection is not reliable enough for testing. I've change the implementation to use inspect instead of actually sending data. I think it's enough to assume that if the ports are listed correctly in the inspect, the ports are in fact open, right?
