### ISSUE TITLE
[Bug]:Using podman-docker (on a remote host), --device-cgroup-rule is ignored

### ISSUE THREAD

**Issue by yashagacisco** [containers/podman#17106]
### Issue Description

When using the 'docker' client to connect to podman on a remote host via the `DOCKER_HOST` env var the `--device-cgroup-rule` option is ignored, whereas `podman-remote` (connecting via `CONTAINER_HOST`) works as expected.

With podman and podman-docker package setup on a remote host, when you use docker from another host to run a container on the remote host, the option is ignored.

The reason I need it to work with "docker" is I want it to work with docker-compose.

### Steps to reproduce the issue

Steps to reproduce the issue:
1. Setup podman on a remote host. I installed Podman v4.2.0 on Centos 8.
2. Install the podman-docker package on the remote-host.
3. From another host, using the `DOCKER_HOST` env-var to connect to the remote-host, run the command`docker run --rm --device-cgroup-rule 'c 243:* rwm' fedora cat /sys/fs/cgroup/devices/devices.list`

I have tested it with the latest version of podman (v4.3) on Centos9. The issue persists, but the bug is difficult to reproduce because it has cgroups v2. The bug is easy to reproduce if you revert back to cgroups v1 and follow the same steps.

### Describe the results you received

```
c 136:* rwm
c 10:200 rwm
c 5:2 rwm
c 5:0 rwm
c 1:9 rwm
c 1:8 rwm
c 1:7 rwm
c 1:5 rwm
c 1:3 rwm
b *:* m
c *:* m
```

As you can see, the new rule, `c 243:* rwm` isn't added.

### Describe the results you expected

Expected the rule to be added. This is the result I get when I used podman-remote (with the `CONTAINER_HOST` env var set up)
```
c 243:* rwm
c 136:* rwm
c 10:200 rwm
c 5:2 rwm
c 5:0 rwm
c 1:9 rwm
c 1:8 rwm
c 1:7 rwm
c 1:5 rwm
c 1:3 rwm
b *:* m
c *:* m
```

### podman info output

```shell
host:
  arch: amd64
  buildahVersion: 1.27.0
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.29-1.module_el8.5.0+890+6b136101.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.29, commit: 84384406047fae626269133e1951c4b92eed7603'
  cpuUtilization:
    idlePercent: 95.42
    systemPercent: 0.74
    userPercent: 3.84
  cpus: 8
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: localhost
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-305.3.1.el8.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 11418238976
  memTotal: 18714284032
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.0.2-1.module_el8.5.0+911+f19012f9.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.2
      spec: 1.0.2-dev
      go: go1.16.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module_el8.5.0+890+6b136101.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 0
  swapTotal: 0
  uptime: 15h 11m 54.00s (Approximately 0.62 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 53675536384
  graphRootUsed: 5070946304
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 5
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1663766104
  BuiltTime: Wed Sep 21 13:15:04 2022
  GitCommit: ""
  GoVersion: go1.18.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rhatdan** [comment]
$ podman run --rm --device-cgroup-rule 'c 243:* rwm' fedora cat /sys/fs/cgroup/devices/devices.list
cat: /sys/fs/cgroup/devices/devices.list: No such file or directory

**Comment by rhatdan** [comment]
@yashagacisco Could you take the PR I linked to this and recompile podman to see if this fixes your problem.

**Comment by yashagacisco** [comment]
> @yashagacisco Could you take the PR I linked to this and recompile podman to see if this fixes your problem.

It isn't working for me. To revert back to cgroup v1 on a centos 9 machine, I did:
1. `sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"`
2. `sudo reboot`

**Comment by LewisGaul** [comment]
This was closed as completed but the attached PR is not observed to fix the issue, as reported in the comment above.

**Comment by rhatdan** [comment]
Open a new issue with a test, you can use Docker to show what you expect.
