### ISSUE TITLE
[Bug]: possible race condition when bringing up the network

### ISSUE THREAD

**Issue by pbrezina** [containers/podman#17147]
### Issue Description

A possible race condition when creating network over docker-compose and podman docker socket as root.

### Steps to reproduce the issue

The issue is seen when using docker-compose over podman docker socket in github actions with ubuntu-latest (22.04), it did never happened with the previous ubuntu version (20.04).

docker-compose:.yml https://github.com/SSSD/sssd-ci-containers/blob/master/docker-compose.yml

### Describe the results you received

```
docker-compose up --detach dns client
Creating network "sssd-ci" with driver "bridge"
Pulling client (quay.io/sssd/ci-client-devel:fedora-36)...
Pulling dns (quay.io/sssd/ci-dns:latest)...
Creating client ... 
Creating dns    ... 
Creating client ... done
Creating dns    ... error

ERROR: for dns  Cannot start service dns: error configuring network namespace for container 1fe59a75eb0e4f7ebfd19f4a1759abb3d70a56b778429668e13448608c09d449: error adding pod dns_dns to CNI network "sssd-ci": running [/usr/sbin/iptables -t filter -N CNI-ADMIN --wait]: exit status 4: iptables v1.8.7 (nf_tables):  CHAIN_USER_ADD failed (File exists): chain CNI-ADMIN


ERROR: for dns  Cannot start service dns: error configuring network namespace for container 1fe59a75eb0e4f7ebfd19f4a1759abb3d70a56b778429668e13448608c09d449: error adding pod dns_dns to CNI network "sssd-ci": running [/usr/sbin/iptables -t filter -N CNI-ADMIN --wait]: exit status 4: iptables v1.8.7 (nf_tables):  CHAIN_USER_ADD failed (File exists): chain CNI-ADMIN

Encountered errors while bringing up the project.
```

### Describe the results you expected

It should always work fine.

### podman info output

```shell
Github Actions Ubuntu 22.04 github-hosted runner.
Podman 3.4.4
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional information

It happens only occasionally.

**Comment by mheon** [comment]
Please upgrade to Podman 4.x and Netavark/Aardvark - the rewritten network stack should be able to better deal with scenarios like this.

**Comment by vrothberg** [comment]
Yes, this is fixed with Podman 4.x.  I think that the next Ubuntu release will ship with it.
