### ISSUE TITLE
[Feature]: Support HostPID in podman kube play

### ISSUE THREAD

**Issue by fcrozat** [containers/podman#17157]
### Feature request description

In k8s Pod, you can specify HostPID when container need access to Host PID (equivalent to --pid host). 

Currently, this is not supported by podman kube play, which is problematic when trying to migrate Docker compose yaml to k8s yaml usable with podman

**Comment by rhatdan** [comment]
Did you try this against the main branch?

If yes, would you care to open a PR?

**Comment by fcrozat** [comment]
Yes, I checked main branch, it is not implemented.

Unforunately, I don't have enough go skills to implement it myself :(

**Comment by danishprakash** [comment]
I'll take a look at this @fcrozat @rhatdan
