### ISSUE TITLE
[Feature]:  Ability to easily limit **systemwide** podman total resources

### ISSUE THREAD

**Issue by loynoir** [containers/podman#17179]
### Feature request description

Ability to easily limit **systemwide** podman total resources

### Suggest potential solution

https://unix.stackexchange.com/questions/537645/how-to-limit-docker-total-resources

`/etc/systemd/system/docker_limit.slice`
```
[Unit]
Description=Slice that limits docker resources
Before=slices.target

[Slice]
CPUAccounting=true
CPUQuota=700%
#Memory Management
MemoryAccounting=true
MemoryLimit=25G
```

`/etc/docker/daemon.json`
```
{
  "cgroup-parent": "docker_limit.slice"
}
```

### Additional context

Previous QA: Any guide to limit **systemwide** podman total resources? https://github.com/containers/podman/discussions/17173

**Comment by giuseppe** [comment]
You can already somehow achieve it by forcing the `--cgroup-parent` when you create a container.

I think it makes sense to allow overriding it from the `containers.conf` configuration file, and use it when there is no `--cgroup-parent` option specified.

**Comment by rhatdan** [comment]
The best way to handle this is to use the systemd service with a -t 0, and use podman remote, so it would work the same as Docker.

Another way to do this would be to run all of your containers within a container. Which is something I am doing for a different project.

But you might be able to do this now with a simple podman run --privileged --rootfs /:O ... And then run your podman commands in this environment.

If you are running only rootless containers then you could setup the cgroups for the user and control all processes launched by the user including the containers.

**Comment by rhatdan** [comment]
I don't see where this is going, we have suggested some solutions and never heard any feedback about whether the solutions work for you.

**Comment by loynoir** [comment]
@rhatdan

Sorry for late reply, the above answer seems complicated to me, and I don't understand what you mean in https://github.com/containers/podman/issues/17179#issuecomment-1442486841

Could you provide a more detailed, step by step explaination/document on

- Given I also use `podman-compose`, what is the easiest way to limit systemwide podman total resources?

**Comment by rhatdan** [comment]
Modify the podman service script with 
https://www.freedesktop.org/software/systemd/man/systemd.resource-control.html

Fields, and systemd will apply resource constraints to all containers created via the podman service.

As long as you are using podman --remote then all containers will follow this rule.

If you are using normal podman the best you can do is setup containers.conf with common settings and then the podman command's defaults will follow the rules.  There is no way to enforce the rules.

I am closing this issue, but feel welcome to continue the conversation here.

**Comment by loynoir** [comment]
@rhatdan 

So, how can I limit `podman` not launched with `--remote`?

> If you are using normal podman the best you can do is setup containers.conf with common settings and then the podman command's defaults will follow the rules.

I don't understand this. Can you do some explaination?

**Comment by loynoir** [comment]
@rhatdan

> What exactly are you worried about your user doing?

1. Some automation containers sometimes CPU goes high.
2. Sometimes reproduce something and CPU goes high.

> podman does not grant any additional rights to a user. No more then curl or bash do. It just enables what the standard distribution allows non root users to do.

Now I understand your point.

---

Is there a configuration way to enforcing all podman launch with `--remote`, so I can let systemd do the rest works?

I think this way will be more elegant than every launch need a `--remote`.

**Comment by MartinX3** [comment]
@loynoir just write into your yaml something like
```yaml
      resources:
        limits:
          cpu: 10m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 1Gi
```

**Comment by loynoir** [comment]
@MartinX3 If I understand correctly, you mean writing into my **every** compose yaml, which I think
- it's not elegant
- cannot limit non-compose usage, sometimes I use for reproducing

So, @rhatdan suggestion seems better, start podman service under cgroup, and use `podman --remote`.

I think it can be more elegant if podman config can enforce `--remote`.

So, write **overall** limitation once, and limit
- `podman-compose`
- automation script that use `podman`
- shell environment that use `podman`

**Comment by MartinX3** [comment]
Ah @loynoir I don't use compose
I use the podman native kube yaml feature

**Comment by rhatdan** [comment]
set `remote=true` in containers.conf file.
man containers.conf
...
      remote  =  false Indicates whether the application should be running in
       remote mode. This flag modifies the --remote option  on  container  en‐
       gines.  Setting  the flag to true will default podman --remote=true for
       access to the remote Podman service.
