### ISSUE TITLE
[Feature]: Make macvlan network support to obtain addresses from DHCP.

### ISSUE THREAD

**Issue by daiaji** [containers/podman#17170]
### Feature request description

In fact, manually setting the ip address of macvlan makes the entire container configuration process lack portability.

### Suggest potential solution

Let ipam support dhcp for mavlan.

### Have you considered any alternatives?

Manually set the address range of macvlan.

### Additional context

https://www.dasblinkenlichten.com/ipam-dns-cni/

> ```
> user@ubuntu-1:/etc/rkt/net.d$ sudo su
> root@ubuntu-1:/etc/rkt/net.d# cd /etc/rkt/net.d
> root@ubuntu-1:/etc/rkt/net.d#
> root@ubuntu-1:/etc/rkt/net.d# cat > custom_rkt_bridge_dhcp.conf <<"EOF" > {
> \>     "cniVersion": "0.2.0",
> \>     "name": "customrktbridgedhcp",
> \>     "type": "macvlan",
> \>     "master": "ens32",
> \>     "ipam": {
> \>         "type": "dhcp"
> \>     }
> \> }
> \> EOF
> 
> root@ubuntu-1:/etc/rkt/net.d# exit
> exit
> user@ubuntu-1:/etc/rkt/net.d$t
> ```

This article states that this seems to be possible.

**Comment by Luap99** [comment]
DHCP with the CNI backend already works for a long time, what did you try?
We are working on DHCP support for netavark, this is almost done and will be released soon, likely podman v4.5.

see https://docs.podman.io/en/latest/markdown/podman-network-create.1.html#ipam-driver-driver

**Comment by daiaji** [comment]
Thanks for informing! I'll wait for this release of this version
