### ISSUE TITLE
[Bug]: --detach-keys does not work without --tty

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#17184]
### Issue Description

I start rootful podman-4.3.2-dev with:

> \# podman run -d --cap-add=IPC_LOCK --log-driver=none --net=host --read-only --read-only-tmpfs=false --mount type=bind,src=/etc/Z,dst=/conf --rm=true -a=stderr -a=stdout --userns=auto:size=10 localhost/Z:2023-01-14

I only want to read the output of the container, I do not want to send signals to the container, or send data to it.

Then I attach to it with any of
```console
# podman attach -l --detach-keys "c"
# podman attach -l --detach-keys "C"
# podman attach -l --detach-keys "ctrl-c"
# podman attach -l --detach-keys "ctrl-C"
Error: attaching to container d08ef5139377473f832b0d771db95ec5ef45f32e919b06a93f8908932eb599a8: invalid detach keys: Unknown character: 'ctrl-C'
```
and press `c` or `C` after the attachment completes, `podman attach` does not disconnect (detach). Likewise for ctrl-c.  The default `ctrl-p,ctrl-q` also does not work.

When `podman run --tty` then detach-keys does work, the implicit ctrl+p,ctrl+q is also functions.

### Steps to reproduce the issue

See above

### Describe the results you received

Container is not detached on any key combiation, when `--tty` is not passed to `podman run`.

### Describe the results you expected

I expect that `podman attach --detach-keys C` always detaches, irrespective on whether `--tty` is set.  While I have no problem of passing `--tty`, I do not need it, except for handing the detach key combination.

### podman info output

```shell
host:                                                               
  arch: amd64           
  buildahVersion: 1.28.2  
  cgroupControllers:     
  - cpuset                                                          
  - cpu                                                             
  - io                                                              
  - memory            
  - hugetlb          
  - pids                       
  cgroupManager: systemd                                            
  cgroupVersion: v2  
  conmon:
    package: Unknown
    path: /usr/local/libexec/podman/conmon
    version: 'conmon version 2.1.4, commit: '
  cpuUtilization:
    idlePercent: 99.12
    systemPercent: 0.42
    userPercent: 0.46
  cpus: 8
  distribution:
    distribution: unknown
    version: unknown
  eventLogger: journald
  hostname: mail
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.162
  linkmode: dynamic
  logDriver: journald
  memFree: 744443904
  memTotal: 8350863360
  networkBackend: cni
  ociRuntime:
    name: crun
    package: Unknown
    path: /usr/local/bin/crun
    version: |-
      crun version 1.7.2.0.0.0.28-da8f
      commit: 61805dffaf112bf7d883555ea91efac8bcf177a2
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,C
AP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.4
  swapFree: 0
  swapTotal: 0
  uptime: 300h 29m 22.00s (Approximately 12.50 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 519784554496
  graphRootUsed: 410856636416
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 8
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.3.2-dev
  Built: 1673643388
  BuiltTime: Fri Jan 13 20:56:28 2023
  GitCommit: 588c6ecc760558780ec2df4a78efdf02e476a0b2
  GoVersion: go1.19.3
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.2-dev
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by giuseppe** [comment]
I think that is expected, detach-key is meaningful only when a terminal is used

**Comment by dilyanpalauzov** [comment]
It is not expected.  I have a container which generates output (stdout).  Most of the time I am not interested in the output.  But sometimes I ATTACH to the container to read the output.  I cannot detach, since detach-keys do no work.

That said, `podman attach` does work as expected, but there is no way to detach from the container after `podman attach` is called.  This is not expected.

**Comment by giuseppe** [comment]
Closing the issue, I've verified it works in the same way on Docker.

```
# docker run --name foo --rm -i alpine sleep 100
^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z^Z
```

**Comment by deliciouslytyped** [comment]
I would also like if this worked. Must this be (usability) bug-compatible to docker?

**Comment by deliciouslytyped** [comment]
This is apparently explained already in https://github.com/containers/podman/issues/6990#issuecomment-911696145
