### ISSUE TITLE
[Bug]: The podman container update command doesn't seem to work.

### ISSUE THREAD

**Issue by ricardobranco777** [containers/podman#17187]
### Issue Description

The `podman container update` command doesn't seem to work.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman container create --name testing registry.opensuse.org/opensuse/leap /bin/sh -c 'sleep 3600'`
1. `podman container start testing`
1. `podman container inspect -f '{{.HostConfig.BlkioWeight}}' testing`
1. `podman update --blkio-weight 10 testing`
1. `podman container inspect -f '{{.HostConfig.BlkioWeight}}' testing`

NOTE: On Ubuntu 22.04 I had to use `--memory-swap` because ` --blkio-weight` returned an error:
```
2023-01-23T11:07:22.541171Z: opening file `io.weight` for writing: No such file or directory
Error: `/usr/bin/crun update --resources=/var/tmp/podman2282833966 5a3aceff3fa774c996ee639d29028e4b155e923202483600d710f92e1c4efba1` failed: exit status 1
```

### Describe the results you received

The `inspect` command returns the same value before and after `podman update`, which didn't return any error.

### Describe the results you expected

The `inspect` command should return the changed value after `podman update`, otherwise the latter command should fail with an error message.

### podman info output

```shell
podman info on openSUSE Tumbleweed (QEMU VM w/ 2 vCPU's & 1536M RAM):

host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.5-2.1.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: unknown'
  cpuUtilization:
    idlePercent: 99.77
    systemPercent: 0.1
    userPercent: 0.13
  cpus: 2
  distribution:
    distribution: '"opensuse-tumbleweed"'
    version: "20230119"
  eventLogger: journald
  hostname: susetest
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.1.7-1-default
  linkmode: dynamic
  logDriver: journald
  memFree: 534142976
  memTotal: 1542692864
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.4-2.1.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.4
      commit: v1.1.4-0-ga916309fff0f
      spec: 1.0.2-dev
      go: go1.18.6
      libseccomp: 2.5.4
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-1.1.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: unknown
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 5
      libseccomp: 2.5.4
  swapFree: 2148233216
  swapTotal: 2148507648
  uptime: 2h 11m 1.00s (Approximately 0.08 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.opensuse.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 30054285312
  graphRootUsed: 2665611264
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 1673913600
  BuiltTime: Mon Jan 16 19:00:00 2023
  GitCommit: ""
  GoVersion: go1.17.13
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1
```
```


### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Tried on both:
- openSUSE Tumbleweed (QEMU VM w/ 2 vCPU's & 1536M RAM) running as root
- Laptop with Ubuntu 22.04 using [Kubic repo](https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_22.04) running as non-root.

### Additional information

_No response_

**Comment by dcermak** [comment]
This is reproducible with the latest state on main (ebc754ff1f1e89fdc59821af5ba36e85cb0796f8), insofar that neither `--blkio-weight` nor `--memory-swap` succeed, I always receive a:
```
❯ ./bin/podman update --memory-swap 10 testing
2023-01-23T17:24:26.354800Z: error opening file `/run/user/1000/crun/3d028d7c4d98b76a8754a44ad7f3b32556e878a3d749167d21f5fbbdc72a7ee6/status`: No such file or directory
Error: `/usr/bin/crun update --resources=/var/tmp/podman2277971324 3d028d7c4d98b76a8754a44ad7f3b32556e878a3d749167d21f5fbbdc72a7ee6` failed: exit status 1
```

@ricardobranco777 Did you run the commands as root?

**Comment by ricardobranco777** [comment]
> @ricardobranco777 Did you run the commands as root?

On Tumbleweed I ran the commands as root.  On Ubuntu as non-root.

**Comment by dcermak** [comment]
`--blkio-weight` cannot work as non-root according to the manpage, so the failures that we both got in rootless mode are to be expected.

This appears to be an issue with podman's inspect code: if I understand the code correctly, then `podman create` or `podman run` will create the `OCIConfigPath` json file into which the container settings are written. That file does not appear to get updated by `podman container update` (at least I did not find that in the code), however the blkio weight is set correctly:
```ShellSession
# cat /sys/fs/cgroup/machine.slice/libpod-$(podman inspect -f {{.Id}} testing).scope/container/io.bfq.weight
default 10
```

@ricardobranco777 do you know if this used to work? If yes, with which version?

**Comment by ricardobranco777** [comment]
> `--blkio-weight` cannot work as non-root according to the manpage, so the failures that we both got in rootless mode are to be expected.
> 
> This appears to be an issue with podman's inspect code: if I understand the code correctly, then `podman create` or `podman run` will create the `OCIConfigPath` json file into which the container settings are written. That file does not appear to get updated by `podman container update` (at least I did not find that in the code), however the blkio weight is set correctly:
> 
> ```
> # cat /sys/fs/cgroup/machine.slice/libpod-$(podman inspect -f {{.Id}} testing).scope/container/io.bfq.weight
> default 10
> ```
> 
> @ricardobranco777 do you know if this used to work? If yes, with which version?

No.  I just expect it to work like Docker, which updates the HostConfig.

**Comment by ricardobranco777** [comment]
> ```
> cat /sys/fs/cgroup/machine.slice/libpod-$(podman inspect -f {{.Id}} testing).scope/container/io.bfq.weight
> ```

The path is different for me:
- Tumbleweed: `/sys/fs/cgroup/machine.slice/libpod-$(podman inspect -f {{.Id}} testing).scope/`
- Ubuntu: `/sys/fs/cgroup/user.slice/user-$(id -u).slice/user@$(id -u).service/user.slice/libpod-$(podman inspect -f {{.Id}} testing).scope/`

I strongly believe that Podman should behave like Docker here and modify `OCIConfigPath`

**Comment by dcermak** [comment]
This is probably a bug in the update code, because setting `--blkio-weight` on creation yields the correct result:
```
# podman container create --name testing --blkio-weight 50 registry.opensuse.org/opensuse/leap /bin/sh -c 'sleep 3600'
# podman  inspect -f '{{.HostConfig.BlkioWeight}}' testing
50
```

**Comment by Luap99** [comment]
>No. I just expect it to work like Docker, which updates the HostConfig.

Note from the [man page](https://docs.podman.io/en/latest/markdown/podman-update.1.html#description):

> These new options are non-persistent and only last for the current execution of the container; the configuration will be honored on its next run. This means that this command can only be executed on an already running container and the changes made will be erased the next time the container is stopped and restarted, this is to ensure immutability.

I have no idea about update the update/cgroup code so I cannot really comment on real issue, just dropping this info so the inspect part is likely  expected.

**Comment by dcermak** [comment]
> Note from the [man page](https://docs.podman.io/en/latest/markdown/podman-update.1.html#description):
> 
> > These new options are non-persistent and only last for the current execution of the container; the configuration will be honored on its next run. This means that this command can only be executed on an already running container and the changes made will be erased the next time the container is stopped and restarted, this is to ensure immutability.
> 
> I have no idea about update the update/cgroup code so I cannot really comment on real issue, just dropping this info so the inspect part is likely expected.

Hm, this still feels like a bug to me to be frankly honest: I as a user would expect that even if the cgroup settings are not persistent, that they are still visible when I inspect the container.

Currently the behavior is a bit odd, because I as the user have really no way of checking if I have applied any additional settings to a container after I have launched it, as `inspect` will never show these.

**Comment by Luap99** [comment]
I am not disagreeing, just wanted to point to the docs. Why it was done that way? I do not know, you can look up the git/githup history to find out the reasons.

**Comment by rhatdan** [comment]
The update will not update the json file, since it only does the change temporarily, but it would be nice if inspect got the active data.

**Comment by dcermak** [comment]
> The update will not update the json file, since it only does the change temporarily, but it would be nice if inspect got the active data.

It would be possible to retrieve some of the data from the cgroup settings, but I think it would be much easier to update the containers specgen and save it somewhere alongside the json (or somewhere else). What do you think?

**Comment by rhatdan** [comment]
@mheon PTAL

**Comment by mheon** [comment]
We do not save or store the changes made to resource limits, so we can't pull them back up after; it's an architectural limitation of our current database.

We could change the resource limit code in `podman inspect` to pull the limits from the actual container cgroup instead of the DB. That would solve things, but would add a lot of complexity, and likely be a lot slower than the current approach.

**Comment by dcermak** [comment]
> We could change the resource limit code in `podman inspect` to pull the limits from the actual container cgroup instead of the DB. That would solve things, but would add a lot of complexity, and likely be a lot slower than the current approach.

That doesn't sound too compelling, to be honest. Wouldn't it make more sense to modify the database to also store the temporary resource limits alongside the persistent ones?

**Comment by rhatdan** [comment]
well that is a fundamental change to what we have been doing and needs a lot more thought, and will take a lot longer.  Potentially requiring a new majore version to podman 5.0.

**Comment by mheon** [comment]
Modifying resource limits in-place is on the list for the sqlite DB rewrite. I don't see it happening with boltdb, the structure of Podman right now is fundamentally built around immutable containers, and the way `update` works right now is by ignoring that and updating only the OCI runtime, not Podman.

**Comment by dcermak** [comment]
I see. Do you have a rough idea when this sqlite DB rewrite is going to happen and whether it's worth it to refactor inspect to reflect the current container state? To me that sounds like an awful lot of work for an outcome that will land at some point anyway. But I definitely lack a lot of insight into podman's internals…

**Comment by mheon** [comment]
We don't have an exact timeframe, but probably first half of this year?

Refactoring inspect would be a sizable amount of work given the complexity (you need to support cgroups v1 and v2 both, and the various cgroups modes that we support (split cgroups, for example). So I'm going to say "not worth it" unless you have serious time constraints.

**Comment by dcermak** [comment]
> Refactoring inspect would be a sizable amount of work given the complexity (you need to support cgroups v1 and v2 both, and the various cgroups modes that we support (split cgroups, for example). So I'm going to say "not worth it" unless you have serious time constraints.

Sounds reasonable to me. Since there are really no time constraints from my side, I have no intention to work on this given the required amount of work.

**Comment by rhatdan** [comment]
This is being worked on.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
If `container update` is meant to be volatile as it is documented, I don't see why `podman inspect` should show the volatile settings.  If you want to recreate the container from the `podman inspect` data you'll need the static configuration, not the transient state.

On the other hand, I'd expect `podman stats` to show the effective limits from the cgroup.

**Comment by rhatdan** [comment]
Since we have the answer I am going to close.  Feel free to continue the conversation here.
