### ISSUE TITLE
[Feature]: Kube Pod Requiriere other Pod

### ISSUE THREAD

**Issue by MartinX3** [containers/podman#17180]
### Feature request description

I use the kube yaml and systemD.
I would like to define pod requirements.

As example the nextcloud pod should wait for the PostgreSQL pod to be ready.

### Suggest potential solution

Since systemd services support requirement management, the systemd service generator of podman should handle it.

### Have you considered any alternatives?

Currently after the server boot I need to check the running pods.
If podman tried to start the nextcloud pod before the podman pod, it will be stuck in `CREATED` mode.

### Additional context

I don't see this feature in the podman kube docs or the internet.

**Comment by vrothberg** [comment]
Thanks for reaching out!

I recommend waiting for the upcoming Podman 4.4 release which will ship with a new way of running Podman in systemd, including Kube YAMl.  You can find more in the docs: https://github.com/containers/podman/blob/main/docs/source/markdown/podman-systemd.unit.5.md#kube-units

Hence, I'll close the request as not planned as we want to focus on Quadlet going forward.
