### ISSUE TITLE
[Bug]: pull --creds authentication not passed to registry via alias

### ISSUE THREAD

**Issue by hmoffatt** [containers/podman#17185]
### Issue Description

I have configured a registry alias in `/etc/containers/registries.conf.d/aliases.conf`, and I'm trying to use it in `podman pull --creds user:pass`, but the authentication is not passed through. If I use the registry name directly then authentication succeeds.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Configure a registry alias, for example

```
[[registry]]
prefix = "xyx.com/prod"
location = "1234567890ab.dkr.ecr.us-east-2.amazonaws.com"
```

2. Pull using this alias: `podman pull --log-level=debug --creds foo:bar xyz.com/prod/image:tag`

### Describe the results you received

Accessing the registry fails with an authentication error. The trace output shows that the alias was resolved but no credentials matched.

```
Trying to pull xyz.com/prod/image:tag...
DEBU[0000] Copying source image //xyz.com/prod/image:tag to destination image [overlay@/srv/containers+/run/containers/storage:overlay.mount_program=/usr/bin/fuse-overlayfs,overlay.mountopt=nodev]xyz.com/prod/image:tag 
DEBU[0000] Using registries.d directory /etc/containers/registries.d 
DEBU[0000] Trying to access "1234567890ab.dkr.ecr.us-east-2.amazonaws.com/image:tag" 
DEBU[0000] No credentials matching 1234567890ab.dkr.ecr.us-east-2.amazonaws.com/image found in /run/containers/0/auth.json 
DEBU[0000] No credentials matching 1234567890ab.dkr.ecr.us-east-2.amazonaws.com/image found in /root/.config/containers/auth.json 
DEBU[0000] No credentials matching 1234567890ab.dkr.ecr.us-east-2.amazonaws.com/image found in /root/.docker/config.json 
DEBU[0000] No credentials matching 1234567890ab.dkr.ecr.us-east-2.amazonaws.com/image found in /root/.dockercfg 
```

If I pull directly using the real registry name, authentication succeeds:

```
Trying to pull 1234567890ab.dkr.ecr.us-east-2.amazonaws.com/image:tag...
DEBU[0000] Copying source image //1234567890ab.dkr.ecr.us-east-2.amazonaws.com/image:tag to destination image [overlay@/srv/containers+/run/containers/storage:overlay.mount_program=/usr/bin/fuse-overlayfs,overlay.mountopt=nodev]1234567890ab.dkr.ecr.us-east-2.amazonaws.com/image:tag 
DEBU[0000] Using registries.d directory /etc/containers/registries.d 
DEBU[0000] Trying to access "1234567890ab.dkr.ecr.us-east-2.amazonaws.com/image:tag" 
DEBU[0000] Returning credentials for 1234567890ab.dkr.ecr.us-east-2.amazonaws.com/image from DockerAuthConfig 
```

### Describe the results you expected

The authentication should be passed through and applied against the alias.

### podman info output

```shell
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon_100:2.1.5-1_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: c9f7f19eb82d5b8151fc3ba7fbbccf03fdcd0325'
  cpuUtilization:
    idlePercent: 94.7
    systemPercent: 3.15
    userPercent: 2.15
  cpus: 6
  distribution:
    codename: bullseye
    distribution: debian
    version: "11"
  eventLogger: file
  hostname: db5
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.0-20-cloud-amd64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 1855528960
  memTotal: 16788647936
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun_0.17+dfsg-1_amd64
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_100:1.2.0-1_amd64
    version: |-
      slirp4netns version 1.2.0
      commit: unknown
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.1
  swapFree: 4011319296
  swapTotal: 4299157504
  uptime: 96h 11m 53.00s (Approximately 4.00 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  docker.io:
    Blocked: false
    Insecure: false
    Location: docker.io
    MirrorByDigestOnly: false
    Mirrors:
    - Insecure: false
      Location: mirror.gcr.io
      PullFromMirror: ""
    Prefix: docker.io
    PullFromMirror: ""
  xyz.com/prod:
    Blocked: false
    Insecure: false
    Location: 1234567890ab.dkr.ecr.us-east-2.amazonaws.com
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: xyz.com/prod
    PullFromMirror: ""
  xyz.com/stage:
    Blocked: false
    Insecure: false
    Location: dev.vpn.xyz.com
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: xyz.com/stage
    PullFromMirror: ""
  search:
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs_1.4.0-1_amd64
      Version: |-
        fusermount3 version: 3.10.3
        fuse-overlayfs: version 1.4
        FUSE library version 3.10.3
        using FUSE kernel interface version 7.31
    overlay.mountopt: nodev
  graphRoot: /srv/containers
  graphRootAllocated: 334269964288
  graphRootUsed: 204064759808
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /srv/containers/volumes
version:
  APIVersion: 4.3.1
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.19.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
@vrothberg @mtrmac PTAL

**Comment by mtrmac** [comment]
The original report already quotes a debug log:
> ```
> DEBU[0000] No credentials matching 1234567890ab.dkr.ecr.us-east-2.amazonaws.com/image found in /run/containers/0/auth.json 
> ```

I tend to think that is sufficient. We could explicitly look for a case where there are no credentials for the destination location, but there _are_ credentials for the logical location (only for redirects, not for mirrors???), and add an extra debug log entry, but the above already seems sufficient to me to indicate what needs doing.

The above certainly does not explain _why_ the system is designed that way, the way https://github.com/containers/podman/issues/17185#issuecomment-1402118304 tries to do, but I’m doubtful we can fit that explanation into a log line.

**Comment by vrothberg** [comment]
I think that the current debug log leaves space for interpretation that there may be a bug. Something indicating that the "user-specified credentials are not used for mirror for security reasons" should fill this space.

**Comment by mtrmac** [comment]
Note that the credentials what were expected to be used come from `auth.json`; i.e. we would need to do an extra lookup to see if they exist. We did not actively ignore credentials from `SystemContext` (that code path also exists, and actually has no debug log, but it’s irrelevant to this report).

In the worst case, that extra lookup to see if there are credentials we didn’t use could trigger interactive prompts if credential helpers were involved. I guess that could be avoided by adding an extra “never be interactive” parameter to `GetCredentials`, or something. So it’s possible but fairly hairy.

**Comment by hmoffatt** [comment]
> That’s not quite an “alias”, in particular it’s not intended to be transparent for credentials.

Fair enough.
Is there a way to have an alias, so that I can always refer to `1234567890ab.dkr.ecr.us-east-2.amazonaws.com` as `xyz.com/prod`, including credentials (and even on push)?

**Comment by mtrmac** [comment]
Not as a Podman feature, to my knowledge. I suppose a DNS CNAME could work, but not with TLS.

**Comment by hmoffatt** [comment]
> Not as a Podman feature, to my knowledge. I suppose a DNS CNAME could work, but not with TLS.

There's some discussion at https://github.com/aws/containers-roadmap/issues/299 about using a reverse proxy or AWS CloudFront to provide a nicer name for AWS ECR registries, which I guess is the only solution for now then.

**Comment by rhatdan** [comment]
@hmoffatt @mtrmac @vrothberg what should we do with this issue?

**Comment by mtrmac** [comment]
I think the best idea that has come up so far is to detect this situation and to add a warning, but that warning couldn’t be reliable in presence of interactive credential helpers, and we would need new parameters and code paths to avoid referring to the credential helpers, just to warn about a situation that has, to my knowledge, happened once during the past 5 years redirection has existed  — so I think that’s not worth it, or at least I don’t plan to work on it.

**Comment by hmoffatt** [comment]
Is there something that could be added to the documentation?

**Comment by rhatdan** [comment]
@mtrmac what do you think about documenting this issue?

**Comment by mtrmac** [comment]
I’m fairly skeptical that adding a sentence or two somewhere would make much of a difference in practice (see how long `containers-registries.conf(5)` is already); “PRs welcome” I guess.

**Comment by vrothberg** [comment]
I think the source of confusion is that passing `--creds` on the Podman CLI will be used solely for the entered source registry.  A sentence in Podman docs may be more helpful and easier to find than in `containers-registries.conf(5)` (which I agree will be buried in a gigantic man page).

**Comment by rhatdan** [comment]
Lets open a PR for podman * --creds man page and add it.

**Comment by hmoffatt** [comment]
Thanks all, I think the PR is a good solution to my problem.
