### ISSUE TITLE
APIv2 tests: python something != something-podman

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#17204]
Seeing this occasionally since Dec 30:
```
________________________ ContainerTestCase.test_attach _________________________
         
         self = <python.rest_api.test_v2_0_0_container.ContainerTestCase testMethod=test_attach>
         
             def test_attach(self):
                 r = requests.post(
                     self.podman_url + "/v1.40/containers/create?name=topcontainer",
                     json={"Cmd": ["sh", "-c", "echo podman; sleep 100"], "Image": "alpine:latest"},
                 )
                 self.assertEqual(r.status_code, 201, r.text)
                 payload = r.json()
             
                 r = requests.post(
                     self.podman_url
                     + f"/v1.40/containers/{payload['Id']}/start"
                 )
                 self.assertEqual(r.status_code, 204, r.text)
             
                 r = requests.post(
                     self.podman_url
                     + f"/v1.40/containers/{payload['Id']}/attach?logs=true&stream=false"
                 )
                 self.assertIn(r.status_code, (101, 200), r.text)
                 # see the attach format docs, stdout = 1, length = 7, message = podman\n
         >       self.assertEqual(r.content, b"\x01\x00\x00\x00\x00\x00\x00\x07podman\n", r.text)
         E       AssertionError: b'' != b'\x01\x00\x00\x00\x00\x00\x00\x07podman\n' :
         
         test/apiv2/python/rest_api/test_v2_0_0_container.py:155: AssertionError
         =========================== short test summary info ============================
         FAILED test/apiv2/python/rest_api/test_v2_0_0_container.py::ContainerTestCase::test_attach
         =================== 1 failed, 43 passed in 78.37s (0:01:18) ====================
```
If I read the URL correctly, this has something to do with `logs`, and ISTR other flakes in podman-remote logs but can't find the issue number.

* fedora-37 : APIv2 test on fedora-37 (root)
  * PR #17165
    * [01-19 06:53](https://api.cirrus-ci.com/v1/task/5030036521091072/logs/main.log)
  * PR #16997
    * [01-05 03:10](https://api.cirrus-ci.com/v1/task/4694463075844096/logs/main.log)
  * PR #16978
    * [01-04 03:14](https://api.cirrus-ci.com/v1/task/4749243169112064/logs/main.log)
  * PR #16810
    * [12-30 10:43](https://api.cirrus-ci.com/v1/task/5556295575535616/logs/main.log)
    * [12-30 10:30](https://api.cirrus-ci.com/v1/task/5214991905718272/logs/main.log)

**Comment by Luap99** [comment]
This was added in https://github.com/containers/podman/commit/1424f0958f6f685992c27df0ac055599eafdd4b5
Problem is that it needs a running container which already logged the message when it calls call attach to reproduce the bug. I assume that CI is just to slow so the message was not logged yet.

I will fix come up with a fix tomorrow.
