### ISSUE TITLE
[Bug]: When I do podman build from a RHEL 8.6 host, I get a Deban GNU/Linux 11 (bullseye) image

### ISSUE THREAD

**Issue by demongolem-biz2** [containers/podman#17219]
### Issue Description

When not specifying arguments, I would expect a host RHEL 8.6 machine to podman build RHEL 8.6.  Instead I get Debian GNU/Linux 11 (bullseye) even though I do not specify it anywhere

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman build
2. podman run
3. cat /etc/os-release

### Describe the results you received

I find myself in Debian after I do a podman run

### Describe the results you expected

Describe the results you expectedI want RHEL 8.6.  I need to further yum install stuff, but I am forced to use apt-get and hit debian sites to get my stuff.

### podman info output

```shell
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Host OS is RHEL 8.6

**Comment by Luap99** [comment]
I m not sure I understand you. The user must specify what they build in the Dockerfile/Containerfile, the base image is specified there.
`podman build` is not a valid command without such a file. It is totally up to you to take care of that. Podman build has no default images.
