### ISSUE TITLE
[Feature]: Windows install documentation should state that admin rights are necessary to execute 'podman machine init'

### ISSUE THREAD

**Issue by omasseau** [containers/podman#17232]
### Feature request description

The documentation for the Windows installation of podman does not tell that admin rights are absolutely necessary to execute 'podman machine init'.

Executing it without being admin fails with the message 'could not configure systemd settings for guest OS' but still register "podman-machine-default" as a distro and keeps files in \\wsl$\podman-machine-default.

Launching the command again with admin rights fails as Windows then shows an error message telling that the the distribution already exists.
To fix the problem and have 'podman machine init' work again I had to first execute 'wsl --unregister podman-machine-default'.

It took me a long time to understand how to fix this problem.
So it would be a good idea to cleary state in the document which commands need admin rights.
Even better : There should an error message if executing 'podman machine init' without admin rights instead of installing the distro and then failing with an obscur error message :)

### Suggest potential solution

Update the documentation for Windows specifying when admin rights are necessary.

**Comment by vrothberg** [comment]
Thanks for reachingout, @omasseau !

@n1hility @baude do you think Podman can throw a meaningful error in that case?

**Comment by n1hility** [comment]
@omasseau Admin rights shouldn't be required as long as WSL has already been installed on your system. What version of Windows and WSL (wsl --version) are you using? I can't seem to reproduce this.

Thanks!

**Comment by omasseau** [comment]
@n1hility 
Microsoft Windows [Version 10.0.19044.2486]
WSL 2 (Kernel version: 5.10.16)

**Comment by n1hility** [comment]
@omasseau thanks for that info.

When you got the message could not configure systemd settings for guest OS, it shoud have also printed an error with that message as well:

```go
return fmt.Errorf("could not configure systemd settings for guest OS: %w", err)
```

Are you able to reproduce this still by trying again? (e.g. you can `podman machine rm -f, then `podman machine init` to recreate)

The kernel version you are running is a bit behind, so you could also try doing a `wsl --update` to see if that helps.

-Jason

**Comment by rhatdan** [comment]
Since we never heard a response, closing, reopen if you have more feedback.
