### ISSUE TITLE
[Bug]: Cannot get podman to switch to networkBackend netavark

### ISSUE THREAD

**Issue by ulamthelucky** [containers/podman#17236]
### Issue Description

Per this blog post:
https://blog.podman.io/2023/01/podman-begins-cni-plugins-deprecation/

I read that I should be able to switch the networkbackEnd from CNI to netavaark.

I followed those instructions for changing it and after completing the final step:  podman system reset,   CNI was still the network backend.

podman version
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.4
Built:        Thu Jan 12 05:31:26 2023
OS/Arch:      linux/amd64

 rpm -q podman
podman-4.2.0-6.module+el8.7.0+1122+04a7498b.x86_64

Also I have verified netavark and aardvark-dns

 rpm -q netavark
netavark-1.1.0-7.module+el8.7.0+1122+04a7498b.x86_64

 rpm -q aardvark-dns
aardvark-dns-1.1.0-5.module+el8.7.0+1122+04a7498b.x86_64

### Steps to reproduce the issue

Steps to reproduce the issue
1.  Verified my podman version was at least version 4, and ensured the netavark and aarkvark-dns were installed.
2. ran:  podman system reset
3. 

### Describe the results you received

Describe the results you received
The networkBackend is still CNI.

### Describe the results you expected

Describe the results you expected
I expected the networkBackend to change to netavark.

### podman info output

```shell
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.

host:
  arch: amd64
  buildahVersion: 1.27.3
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.4-1.module+el8.7.0+1078+e72fcd4f.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: 6806ea86c9ad5ad2677388246a64dd8079924180'
  cpuUtilization:
    idlePercent: 99.94
    systemPercent: 0.02
    userPercent: 0.04
  cpus: 4
  distribution:
    distribution: '"rocky"'
    version: "8.7"
  eventLogger: file
  hostname: RD1.trxadedev.com
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-425.3.1.el8.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 15169622016
  memTotal: 16199651328
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.4-1.module+el8.7.0+1078+e72fcd4f.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.4
      spec: 1.0.2-dev
      go: go1.18.4
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.module+el8.7.0+1078+e72fcd4f.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 524h 3m 35.00s (Approximately 21.83 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 248982278144
  graphRootUsed: 5692141568
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1673519486
  BuiltTime: Thu Jan 12 05:31:26 2023
  GitCommit: ""
  GoVersion: go1.18.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
RHEL 8 and thus I assume rocky as well still uses CNI, this is forced via containers.conf option. 
If you want to change this you need to change the `network_backend` option in containers.conf yourself.
