### ISSUE TITLE
[Bug]: ignition_linux.go failed on systemd-free Linux due to lack of `timedatectl` executable

### ISSUE THREAD

**Issue by nabbisen** [containers/podman#17244]
### Issue Description

My machine is Artix Linux, based on Arch Linux and using OpenRC instead of systemd.

`getLocalTimeZone` in [`ignition_linux.go`](https://github.com/containers/podman/blob/52d5f367b144f755dd20b18d88c5f79bc6b0c3fe/pkg/machine/ignition_linux.go) executes `timedatectl`, which is a part of systemd. Therefore, it failed in my env, and `.ign` was not created.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Use systemd-free Linux.
2. Install Podman and run `podman machine init`

### Describe the results you received

1. The error was:    
    ```console
    Extracting compressed file
    Image resized.
    Error: exec: "timedatectl": executable file not found in $PATH
    ```
2. Additionally, since `podman-machine-default.ign` was not created, running `podman machine start` in the next step also failed with the error:    
    ```console
    Starting machine "podman-machine-default"
    Waiting for VM ...
    Error: qemu exited unexpectedly with exit code 1, stderr: qemu-system-x86_64: -fw_cfg name=opt/com.coreos/config,file=/home/(...)/.config/containers/podman/machine/qemu/podman-machine-default.ign: can't load /home/(...)/.config/containers/podman/machine/qemu/podman-machine-default.ign: Failed to open file “/home/(...)/.config/containers/podman/machine/qemu/podman-machine-default.ign”: No such file or directory
    ```

### Describe the results you expected

`podman machine init` is successful with systemd-free Linux.

### podman info output

```shell
OS: Artix Linux with OpenRC x86_64
Podman: 4.3.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

\-

### Additional information

I made a custom Rust script to print my timezone named "timedatectl". After it built and placed in `$PATH`, `podman machine init` succeeded. The `.ign` file was created with content written.

In my opinion, on systemd-free Linux, `exec.Command("timedatectl", "show", "--property=Timezone").Output()` should be replaced with `exec.Command("cat", "/etc/timezone").Output()` in `ignition_linux.go`. For example:

```go
var output
o, err := exec.Command("pidof", "systemd").Output()
if string(o) == "1\n" || err != nil {
	// default
	output, err = exec.Command("timedatectl", "show", "--property=Timezone").Output()
} else {
	// systemd-free
	output, err = exec.Command("cat", "/etc/timezone").Output()
}
```

**Comment by vrothberg** [comment]
Thanks for reaching out!

The idea sounds good to me.  I suggest to do a `path.Lookup("timedatectl")` though to check whether it's available.

Are you interested in opening a PR?

**Comment by nabbisen** [comment]
> Thanks for reaching out!
> 
> The idea sounds good to me. I suggest to do a `path.Lookup("timedatectl")` though to check whether it's available.
> 
> Are you interested in opening a PR?

Thanks, too, for your precious time.
Yes, I am. I'll send in a few days.
Well, thank you, again. `path.Lookup("timedatectl")` is nice.

**Comment by Luap99** [comment]
This sounds reasonable but AFAIK /etc/timezone does not have to exist either. It doesn't exists on my fedora install, properly the reason why we used timedatectl in the first place.
Also you should not use exec `cat` to read a file, just read it directly from the go code, i.e. use `os.ReadFile()`.

**Comment by nabbisen** [comment]
> This sounds reasonable but AFAIK /etc/timezone does not have to exist either. It doesn't exists on my fedora install, properly the reason why we used timedatectl in the first place. Also you should not use exec `cat` to read a file, just read it directly from the go code, i.e. use `os.ReadFile()`.

Thank you for your detailed feedbacks. I agree `/etc/timezone` doesn't always exist. To get time zone from it is [OpenRC's way](https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Base#Timezone). I imagine your Fedora uses systemd as init system so `/etc/timezone` is not necessary.

My opinion is not to replace `timedatectl` with `/etc/timezone` but to use the latter **when the former is missing**.
My trial must be like:

```go
if timedatectl is missing {
    read /etc/timezone
} else {
    default aka timedatectl
}
```

It aims to mitigate failure of the specific case. How about it ?

> you should not use exec `cat` to read a file

Definitely 😅 I appreciate you.

**Comment by nabbisen** [comment]
I sent PR #17264 .

Test done:

1. Artix Linux (systemd-free)
  - `podman machine init` was successful.
  - My time zone was written in `podman-machine-default.ign`. 
2. Fedora 37 (systemd) 
  - `podman machine init` was successful, too. (regression testing)
  - Diff was only in passwd - users - sshAuthorizedKeys between original `.go` and modified.
