### ISSUE TITLE
[Bug]: Podman Machine Init fails with Error: exit status 1

### ISSUE THREAD

**Issue by thejtshow** [containers/podman#17261]
### Issue Description

I am attempting to run a podman virtual machine in WSL2 to experiment with aarch64 emulation. I had some success with the version of podman that Ubuntu 22 has, but podman 3.x did not have volume mounting in the virtual machine. Now that I have upgraded to podman `4.3.1`, I am unable to start the virtual machine. 

### Steps to reproduce the issue

Steps to reproduce the issue

1. create new ubuntu WSL2 instance
2. install podman 4.3.1
3. `sudo mount --make-rshared /`
4. `sudo apt install qemu-system qemu-user-static`
5. install gvproxy
6. `sudo chown root:kvm /dev/kvm && sudo chmod 660 /dev/kvm`
7. `sudo usermod -aG kvm $USER`
8. logout and back in
9. podman machine init

### Describe the results you received

```
Extracting compressed file
Image resized.
Error: exit status 1
```
turning up `--log-level=debug` yields nothing new or useful. 

Only `~/.config/containers/podman/machine/qemu/podman-machine-default.json` is created, not the `ign` file or any others. 

### Describe the results you expected

Having the machine initialize correctly.

### podman info output

```shell
WARN[0000] Error validating CNI config file /home/justin/.config/cni/net.d/87-podman.conflist: [failed to find plugin "bridge" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "portmap" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "firewall" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "tuning" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin]]
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon_2:2.1.5-0ubuntu22.04+obs14.26_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 98.3
    systemPercent: 0.44
    userPercent: 1.26
  cpus: 12
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: file
  hostname: <redacted>
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.83.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 12955541504
  memTotal: 16736444416
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun_1.7.2-0ubuntu22.04+obs48.16_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.7.2
      commit: 0356bf4aff9a133d655dc13b1d9ac9424706cac4
      rundir: /mnt/wslg/runtime-dir/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /mnt/wslg/runtime-dir/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 4294967296
  swapTotal: 4294967296
  uptime: 1h 17m 12.00s (Approximately 0.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/<redacted>/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/<redacted>/.local/share/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 5198118912
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /mnt/wslg/runtime-dir/containers
  volumePath: /home/<redacted>/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 0
  BuiltTime: Wed Dec 31 18:00:00 1969
  GitCommit: ""
  GoVersion: go1.18.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1
```
```


### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rhatdan** [comment]
@n1hility PTAL

**Comment by n1hility** [comment]
Are you just wanting to run aarch container images on x86? If so you shouldn't need to do a nested virt podman machine inside of wsl. 

These two options should work if that's the case:

1. Install podman for winodws, letting it create its own WSL instance it uses
    a. From there you can podman machine ssh into the WSL instance (or access it via wsl -d podman-machine-default) and install qemu-user-static
2. Setup a custom WSL dristo like you are doing with podman installed, and then install qemu-user-static however your distro likes. 

The advantage of 1) is that podman can be used from Windows,  and the Fedora streams usually stay more current with the podman backend piece.

**Comment by thejtshow** [comment]
@n1hility thank you for the information. I am attempting what you said, and had switched distros in the middle of my testing. On the first distro, I was unable to get 2) working but more than likely was a PEBCAK. This step did work on my current test, so I am able to continue working. Thank you for the information!

Feel free to close this issue as I can continue on, or keep it open if you want to run the init issue to ground.

**Comment by n1hility** [comment]
Cool thanks @thejtshow . I'll close it for now, but planning to include aarch qemu packages by default in the future, so that this use case will work out of the box for the podman machine case.
