### ISSUE TITLE
[Bug]: Undefined Field containerConfig.Containers.RootlessNetworking at v3.4.7

### ISSUE THREAD

**Issue by HuanMeng0** [containers/podman#17268]
### Issue Description

https://github.com/containers/podman/blob/v3.4.7/pkg/specgen/namespaces.go#L327
```
	ns, cniNets, err := ParseNetworkNamespace(network, containerConfig.Containers.RootlessNetworking == "cni")
```

Line 327 referrers a non-exist field "RootlessNetworking".

### Steps to reproduce the issue

Steps to reproduce the issue
1. import 	"github.com/containers/podman/v3/pkg/specgen" of version 3.4.7 
2. write some code with specgen package
3. build

### Describe the results you received

Build Failed.

```
# github.com/containers/podman/v3/pkg/specgen
PROJECT_DIR/vendor/github.com/containers/podman/v3/pkg/specgen/namespaces.go:327:80: containerConfig.Containers.RootlessNetworking undefined (type "github.com/containers/common/pkg/config".ContainersConfig has no field or method RootlessNetworking)
FAIL	MY_PROJECT_NAME [build failed]
```

### Describe the results you expected

No error. build successfully.

### podman info output

```shell
Podman version: 3.4.7
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rhatdan** [comment]
Can you test this against main branch?

**Comment by vrothberg** [comment]
The internal API and Go packages are not supported for outside use.  Please use the bindings in `pkg/bindings` and the REST API.
