### ISSUE TITLE
[Bug]: WSL2 on W10, CreateFile \\.\pipe\docker_engine: All pipe instances are busy.

### ISSUE THREAD

**Issue by allanp35** [containers/podman#17284]
### Issue Description

Install of podman v.4.3.1 on WSL2-W10 fails.
Podman machine init works, but not podman machine start:
**Sometime it work at the beginning, but then after some days it came in error. So we need to kill the podman machine and init a new one. But we lost containers** 

podman machine start
Starting machine "podman-machine-default" This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility issues with non-podman clients, you can switch using the following command:         

podman machine set --rootful API forwarding for Docker API clients is not available due to the following startup failures.

        CreateFile \\.\pipe\docker_engine: Toutes les instances des canaux de communication sont occupées. 
        
Podman clients are still able to connect.
        
Machine "podman-machine-default" started successfully

There was an issue : [here](https://github.com/containers/podman/issues/15176), but this didn't work for me 

### Steps to reproduce the issue

Steps to reproduce the issue
1. Install [podman](https://github.com/containers/podman/releases/download/v4.3.1/podman-4.3.1-setup.exe)
2. In PowerShell or CMD, run podman machine init
3. Run podman machine run

### Describe the results you received

podman machine start
Starting machine "podman-machine-default" This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:         podman machine set --rootful API forwarding for Docker API clients is not available due to the following startup failures.
        CreateFile \\.\pipe\docker_engine: Toutes les instances des canaux de communication sont occupées. Podman clients are still able to connect.
Machine "podman-machine-default" started successfully

### Describe the results you expected

Starting machine "podman-machine-default"

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

        podman machine set --rootful

API forwarding listening on: npipe:////./pipe/docker_engine

Docker API clients default to this address. You do not need to set DOCKER_HOST.
Machine "podman-machine-default" started successfully

### podman info output

```shell
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.5-1.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 99.94
    systemPercent: 0.04
    userPercent: 0.02
  cpus: 8
  distribution:
    distribution: fedora
    variant: container
    version: "36"
  eventLogger: journald
  hostname: btw85512
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.79.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 7469387776
  memTotal: 8212418560
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.7.2-3.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.7.2
      commit: 0356bf4aff9a133d655dc13b1d9ac9424706cac4
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 2146947072
  swapTotal: 2147483648
  uptime: 2h 41m 48.00s (Approximately 0.08 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 306843648
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 1668180253
  BuiltTime: Fri Nov 11 16:24:13 2022
  GitCommit: ""
  GoVersion: go1.18.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by vrothberg** [comment]
@n1hility PTAL

**Comment by mlmoses** [comment]
I am also experiencing this issue. I'm on Windows 11 Pro (22H2). I'm currently using Podman 4.4.0, but I have previously experienced the same issue with Podman 4.3.1.
```
> podman machine start
Starting machine "podman-machine-default"

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

        podman machine set --rootful

API forwarding for Docker API clients is not available due to the following startup failures.
        CreateFile \\.\pipe\docker_engine: All pipe instances are busy.

Podman clients are still able to connect.
Machine "podman-machine-default" started successfully
```

In my case, however, after starting podman-machine-default, I am unable to use podman with it (i.e. Podman clients are not, in fact, still able to connect). For example:
```
> podman version
Error: failed to connect: dial tcp [::1]:51375: connectex: No connection could be made because the target machine actively refused it.
> podman container ls -a
Error: failed to connect: dial tcp [::1]:51375: connectex: No connection could be made because the target machine actively refused it.
> podman machine ssh
Connecting to vm podman-machine-default. To close connection, use `~.` or `exit`
ssh: connect to host localhost port 51375: Connection refused
```

However, I can still access podman-machine-default directly via wsl:
```
> wsl --distribution podman-machine-default

You will be automatically entered into a nested process namespace where
systemd is running. If you need to access the parent namespace, hit ctrl-d
or type exit. This also means to log out you need to exit twice.

[user@xxxxxxxx ~]$
```

I am able to start and manage containers this way, and I can connect to those containers externally. For example, one of my containers is running Microsoft SQL Server for Linux. I can connect to SQL Server and run queries from DataGrip on the host. It's less convenient, but still useable.

I was able to create a new machine (`podman machine init podman-machine-new`) and am now using that new machine as the default (`podman system connection default podman-machine-new`). This new machine does not, for now, have the same issue as podman-machine-default, but it will require me to migrate all of my containers to the new machine if I want to use it.

I don't plan on deleting podman-machine-default for a while, so I can pull more information from it if needed.

**Comment by mlmoses** [comment]
@n1hility the information you requested is below. However, when I went to use podman today, the issue seems to have cleared up on its own. The first time I've used podman since posting my previous comment was earlier today when I ran a new container using the new machine that I created (podman-machine-new). Since the issue seems to have cleared up, I'm not sure how useful any information I pull from podman-machine-default will be.

```
> podman system connection ls
Name                         URI                                                          Identity                                      Default
podman-machine-default       ssh://user@localhost:51375/run/user/1000/podman/podman.sock  C:\Users\mlmoses\.ssh\podman-machine-default  true
podman-machine-default-root  ssh://root@localhost:51375/run/podman/podman.sock            C:\Users\mlmoses\.ssh\podman-machine-default  false
podman-machine-new           ssh://user@localhost:52056/run/user/1000/podman/podman.sock  C:\Users\mlmoses\.ssh\podman-machine-new      false
podman-machine-new-root      ssh://root@localhost:52056/run/podman/podman.sock            C:\Users\mlmoses\.ssh\podman-machine-new      false
```
```
> wsl -d podman-machine-default grep Port /etc/ssh/sshd_config
grep: /etc/ssh/sshd_config: Permission denied
```
```
> podman machine ls --format json
[
    {
        "Name": "podman-machine-default",
        "Default": true,
        "Created": "2022-12-21T10:17:58.519717-05:00",
        "Running": true,
        "Starting": false,
        "LastUp": "2023-02-08T14:01:00.0711468-05:00",
        "Stream": "35",
        "VMType": "wsl",
        "CPUs": 16,
        "Memory": "611962880",
        "DiskSize": "14261682176",
        "Port": 51375,
        "RemoteUsername": "user",
        "IdentityPath": "C:\\Users\\mlmoses\\.ssh\\podman-machine-default"
    },
    {
        "Name": "podman-machine-new",
        "Default": false,
        "Created": "2023-02-06T10:52:20.1559423-05:00",
        "Running": false,
        "Starting": false,
        "LastUp": "2023-02-08T13:53:37.8911566-05:00",
        "Stream": "35",
        "VMType": "wsl",
        "CPUs": 0,
        "Memory": "0",
        "DiskSize": "12112101376",
        "Port": 52056,
        "RemoteUsername": "user",
        "IdentityPath": "C:\\Users\\mlmoses\\.ssh\\podman-machine-new"
    }
]
```

**Comment by rhatdan** [comment]
@n1hility What should we do with this one?

**Comment by n1hility** [comment]
Lets close. There was likely two different issues at play here. The first issue should be improved in later versions, but there is a timeout factor involved (its essentially just a warning message). If the instance takes too long to come up (WSL is slow to start, system under load etc), it will give up and stop blocking the start() process, and could even still be fine afterwords. If future cases still occur we can increase the timeout window further.

Feel free to reopen if you see this still happening and can provide more details. Thanks!
