### ISSUE TITLE
[Bug]: podman machine with centos7 image on Mac M1 is not starting 

### ISSUE THREAD

**Issue by pkvprakash** [containers/podman#17298]
### Issue Description

Podman machine with centos7 image on Mac M1 is not starting and goes to a hung state. 

Architecture : aarch64

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create a machine `podman machine init --image-path https://cloud.centos.org/centos/7/images/CentOS-7-aarch64-GenericCloud.qcow2.xz centos7`
2. Start the machine  `podman machine start centos7`

### Describe the results you received

The output will be similar to 
```
Starting machine "centos7"
Waiting for VM ...
```
and no progress afterwards

### Describe the results you expected

The machine should be up and running

### podman info output

```shell
podman info
Error: failed to connect: dial tcp [::1]:62023: connect: connection refused
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

```
(base) ➜  ~ podman machine info
Host:
  Arch: arm64
  CurrentMachine: centos7
  DefaultMachine: podman-machine-default
  EventsDir: <REDACTED>
  MachineConfigDir: <REDACTED>
  MachineImageDir: <REDACTED>
  MachineState: Starting
  NumberOfMachines: 2
  OS: darwin
  VMType: qemu
Version:
  APIVersion: 4.3.1
  Built: 1668026638
  BuiltTime: Thu Nov 10 02:13:58 2022
  GitCommit: ""
  GoVersion: go1.18.8
  Os: darwin
  OsArch: darwin/arm64
  Version: 4.3.1
```

### Additional information

```
Arch: aarch64 (arm64)
Machine image: https://cloud.centos.org/centos/7/images/CentOS-7-aarch64-GenericCloud.qcow2.xz 
```

**Comment by Luap99** [comment]
You cannot just use any image, podman machine use fedora CoreOS by default.
AFAIK we depend on ignition support at least and likely other runtime dependecies, i.e. a recent podman must be installed in that image.


That should properly be made clear in the man page for this option. @baude @ashley-cui

**Comment by afbjorklund** [comment]
"Any customer can have a car painted any colour that he wants, so long as it is black."

**Comment by baude** [comment]
closing as not supported
