### ISSUE TITLE
[Feature]: how to install podman 3 on fedora 36/37

### ISSUE THREAD

**Issue by zzguang520520** [containers/podman#17307]
### Feature request description

how to install podman 3 on fedora 36/37

### Suggest potential solution

no rpm package of podman3 on fedora 36/37，how to install podman 3 on fedora 36/37

### Have you considered any alternatives?

no rpm package of podman3 on fedora 36/37，how to install podman 3 on fedora 36/37

### Additional context

no rpm package of podman3 on fedora 36/37，how to install podman 3 on fedora 36/37

**Comment by rhatdan** [comment]
We only support the latest podman package, there is no podman 3 package.  You should just install podman, which will get you a version of podman-4.*
