### ISSUE TITLE
[Feature]: Add functionality to redo network configuration of running containers

### ISSUE THREAD

**Issue by nolange** [containers/podman#17310]
### Feature request description

I run a debian server with several podman instances, those depend on routing via nftables (podman uses iptables which delegates to nftables).
automatic system updates are enabled, so every time nftables is upgraded, it will restart the service and remove all dynamic configuration - in the end no container is reachable.

### Suggest potential solution

I would like a podman command and a systemd service that can be bound to nftables start/stop actions.
It should redo all networking setup for running containers when nftables is startet.

### Have you considered any alternatives?

Well, taking nftables out from automatic updates would be an option.

**Comment by Luap99** [comment]
I think `podman network reload --all` already does what you want.

**Comment by nolange** [comment]
Seems like it, sorry
