### ISSUE TITLE
[Bug]: `--userns nomap` & `keep-id` block `--userns auto`

### ISSUE THREAD

**Issue by 0xF4CED** [containers/podman#17336]
### Issue Description

If a container exists, that was created with `--userns nomap` or `keep-id` any attempt to create a container with the option `--userns auto` fails with: `Error: creating container storage: could not find enough available IDs`.
When the nomap/keep-id container is removed, creating a container with `--userns auto` works as expected.

### Steps to reproduce the issue

1. `podman create --userns nomap alpine` - Create container with `--userns nomap` or `keep-id`
2. `podman create --userns auto alpine` - Try to create one with `--userns auto`

### Describe the results you received

Creation of the `--userns auto` Container fails if a container with `--userns nomap` or `--userns keep-id` exists.
`Error: creating container storage: could not find enough available IDs`

### Describe the results you expected

Successful creation of the container in a unique userns.

### podman info output

```shell
host:
  arch: amd64
  buildahVersion: 1.28.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.5-1.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 98.83
    systemPercent: 0.49
    userPercent: 0.68
  cpus: 4
  distribution:
    distribution: fedora
    variant: iot
    version: "37"
  eventLogger: journald
  hostname: podbook
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 2147483648
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 2147483648
  kernel: 6.1.7-200.fc37.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 492281856
  memTotal: 8090230784
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.7.2-3.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.7.2
      commit: 0356bf4aff9a133d655dc13b1d9ac9424706cac4
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 8085041152
  swapTotal: 8089759744
  uptime: 48h 31m 14.00s (Approximately 2.00 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /var/home/admin/.config/containers/storage.conf
  containerStore:
    number: 9
    paused: 0
    running: 3
    stopped: 6
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/admin/.local/share/containers/storage
  graphRootAllocated: 170259980288
  graphRootUsed: 49255747584
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 56
  runRoot: /run/user/1000/containers
  volumePath: /home/admin/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 1668178887
  BuiltTime: Fri Nov 11 16:01:27 2022
  GitCommit: ""
  GoVersion: go1.19.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional information

Also tested on podman-4.4.0-rc2

**Comment by giuseppe** [comment]
it is working as expected.  `userns=auto` uses distinct IDs that are not shared with other pods/containers.  With `--userns=nomap` and `--userns=keep-id` you are already using all the available IDs so there is nothing left for the new container

**Comment by salevdns** [comment]
Oh okay, so nomap and keep-id are passing all available IDs to the container? In my case all 2.147.383.648?
I did not realize that.

**Comment by salevdns** [comment]
I found [documentation](https://docs.podman.io/en/latest/markdown/options/userns.container.html) mentioning this for keep-id but not for nomap.

**Comment by giuseppe** [comment]
`nomap` passes all the available IDs **except** the current user.

**Comment by salevdns** [comment]
I see, thank you for the clarification.

**Comment by rhatdan** [comment]
I wrote a blog on this recently.
https://www.redhat.com/sysadmin/rootless-podman-user-namespace-modes

**Comment by salevdns** [comment]
This issue got me thinking about whether it would be desirable/practical to have an optional `size` parameter for `nomap` and `keep-id` like we have for `auto`. Like this: `--userns=nomap:size=1024`.
WDYT

**Comment by rhatdan** [comment]
I would be fine with that,  The differnce is userns=auto defaults to size of image, where nomap and keep-id default to all UIDs in /etc/subuid.
