### ISSUE TITLE
[Bug]: podman commit --pause has contradicting documentation

### ISSUE THREAD

**Issue by EvaristeGalois11** [containers/podman#17363]
### Issue Description

The documentation for the [podman commit](https://docs.podman.io/en/latest/markdown/podman-commit.1.html) command states that:

> The container and its processes are paused while the image is committed. This minimizes the likelihood of data corruption when creating the new image. If this is not desired, the --pause OPTION can be set to false. 

It's therefore implied that the default behavior is pausing during the commit.

The problem is that scrolling down to the pause parameter section:

> --pause, -p 
> Pause the container when creating an image. The default is false.

So it seems that the default behavior is not pausing during the commit.

Which part is the correct one?

### Steps to reproduce the issue

Go to https://docs.podman.io/en/latest/markdown/podman-commit.1.html

### Describe the results you received

---

### Describe the results you expected

---

### podman info output

```yaml
---
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

**Comment by rhatdan** [comment]
The default is pause==false, so it is not paused and the man page is wrong.
Please open a PR to fix the man page.
