### ISSUE TITLE
[Feature]: Show network metric from podman inspect NetworkSettings.Networks section

### ISSUE THREAD

**Issue by ypu** [containers/podman#17389]
### Feature request description

We are recently support set metric in our network. It works as expected. But the information can not be checked from podman inspect $container_id. If we can also update the NetworkSettings.Networks of the container it maybe better for user to notice it.

### Suggest potential solution

Show metric info in NetworkSettings.Networks section of container inspect.

### Additional context

Here is same output for current version:
`# podman network create -o=metric=100 test100
test100
# podman network create -o=metric=200 test200
test200
# podman inspect test100
[
     {
          "name": "test100",
          "id": "282cabd4a1d5cf37bae14e0121873a89f0780c0f201d9bb856b25d862c85b11c",
          "driver": "bridge",
          "network_interface": "podman1",
          "created": "2023-01-12T09:52:58.391694201+05:30",
          "subnets": [
               {
                    "subnet": "10.89.0.0/24",
                    "gateway": "10.89.0.1"
               }
          ],
          "ipv6_enabled": false,
          "internal": false,
          "dns_enabled": true,
          "options": {
               "metric": "100"
          },
          "ipam_options": {
               "driver": "host-local"
          }
     }
]
# podman inspect test200
[
     {
          "name": "test200",
          "id": "21b19ff289b05852494a92e3f3238729cba2914a3f8d6ea28761d201d21f0763",
          "driver": "bridge",
          "network_interface": "podman2",
          "created": "2023-01-12T09:53:07.473885022+05:30",
          "subnets": [
               {
                    "subnet": "10.89.1.0/24",
                    "gateway": "10.89.1.1"
               }
          ],
          "ipv6_enabled": false,
          "internal": false,
          "dns_enabled": true,
          "options": {
               "metric": "200"
          },
          "ipam_options": {
               "driver": "host-local"
          }
     }
]
# podman run -dt --network test100 --network test200 quay.io/libpod/busybox top
Trying to pull quay.io/libpod/busybox:latest...
Getting image source signatures
Copying blob 9758c28807f2 done  
Copying config f0b02e9d09 done  
Writing manifest to image destination
Storing signatures
fd04e6b0fc7b895c016a5b1c28f0827ff7623f35d47ad041f0576800e825c086
[root@dell-r430-13 podman]# podman inspect --format "{{json .NetworkSettings.Networks}}" fd04e6b0fc7b895c016a5b1c28f0827ff7623f35d47ad041f0576800e825c086| jq
{
  "test100": {
    "EndpointID": "",
    "Gateway": "10.89.0.1",
    "IPAddress": "10.89.0.2",
    "IPPrefixLen": 24,
    "IPv6Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "MacAddress": "06:53:83:25:6a:53",
    "NetworkID": "test100",
    "DriverOpts": null,
    "IPAMConfig": null,
    "Links": null,
    "Aliases": [
      "fd04e6b0fc7b"
    ]
  },
  "test200": {
    "EndpointID": "",
    "Gateway": "10.89.1.1",
    "IPAddress": "10.89.1.2",
    "IPPrefixLen": 24,
    "IPv6Gateway": "",
    "GlobalIPv6Address": "",
    "GlobalIPv6PrefixLen": 0,
    "MacAddress": "de:c9:ae:cf:43:6e",
    "NetworkID": "test200",
    "DriverOpts": null,
    "IPAMConfig": null,
    "Links": null,
    "Aliases": [
      "fd04e6b0fc7b"
    ]
  }
}
`

**Comment by Luap99** [comment]
Is there a specific reason why you want the mtu there vs just in `podman network inspect`. I ask because there are a lot more network options that are only visible in network inspect and I rather not duplicate them all into the container inspect.
