### ISSUE TITLE
[Bug]: Format of podman-network-create manual need an update in the --opt part

### ISSUE THREAD

**Issue by ypu** [containers/podman#17388]
### Issue Description

The manual of podman-network-create needs an update in the --option part. Currently the format is a little mess up. We need a new line for options introduce like -mtu, -metric and so on:
` --opt, -o=option
       Set driver specific options.

       All drivers accept the mtu and metric options.  - mtu: Sets the Maximum Transmission Unit (MTU) and takes an integer value.  - metric
       Sets  the Route Metric for the default route created in every container joined to this network. Accepts a positive integer value. Can
       only be used with the Netavark network backend.

       Additionally the bridge driver supports the following options: - vlan: This option assign VLAN tag and  enables  vlan_filtering.  De‐
       faults to none.  - isolate: This option isolates networks by blocking traffic between those that have this option enabled.

       The  macvlan  and  ipvlan driver support the following options: - parent: The host device which should be used for the macvlan inter‐
       face. Defaults to the default route interface.  - mode: This option sets the specified ip/macvlan mode on the interface.
         - Supported values for macvlan are bridge, private, vepa, passthru. Defaults to bridge.
         - Supported values for ipvlan are l2, l3, l3s. Defaults to l2.`

### Steps to reproduce the issue

Steps to reproduce the issue
1. man podman-network-create

### Describe the results you received

The manual format is a little mess

### Describe the results you expected

introductions about the options are start with new line and looks more clearly.

### podman info output

```yaml
compiled podman(HEAD: 67305cec9702977828dc8b3d7e0efd55eec2d909)
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by baude** [comment]
@ypu perhaps you could suggest what you would want to see?

**Comment by ypu** [comment]
Thanks @baude for your advice. Following doc looks more clear for me.

`   All drivers accept the mtu and metric options. 
       - mtu: Sets the Maximum Transmission Unit (MTU) and takes an integer value.  
       - metric: Sets  the Route Metric for the default route created in every container joined to this network. Accepts a positive integer value. Can only be used with the Netavark network backend.

   Additionally the bridge driver supports the following options:
     - vlan: This option assign VLAN tag and  enables  vlan_filtering.  Defaults to none. 
     - isolate: This option isolates networks by blocking traffic between those that have this option enabled.

   The  macvlan  and  ipvlan driver support the following options:
      - parent: The host device which should be used for the macvlan interface. Defaults to the default route interface.  
      - mode: This option sets the specified ip/macvlan mode on the interface.
         - Supported values for macvlan are bridge, private, vepa, passthru. Defaults to bridge.
         - Supported values for ipvlan are l2, l3, l3s. Defaults to l2.`

**Comment by rhatdan** [comment]
Yup.  I just opened a PR to clean these up. since I saw them while working on quadlet.
https://github.com/containers/podman/pull/17440

**Comment by Luap99** [comment]
Thanks @rhatdan, PR is merged so we are good to close.
