### ISSUE TITLE
I still have this issue, can not install podman in Amazon Linux 2.

### ISSUE THREAD

**Issue by koalawangyang** [containers/podman#17393]
I still have this issue, can not install podman in Amazon Linux 2. 

"no podman package found" when enabled epel source. Already followed above solutions, no one works for me.

_Originally posted by @koalawangyang in https://github.com/containers/podman/issues/8888#issuecomment-1420357276_

**Comment by lsm5** [comment]
podman is not in epel, it's in the extras repo, but I think amazon linux 2's own extras repo is something totally different from rhel-extras / centos-extras.

It might be best to check with AWS support, or check if you could switch to centos 7. Even better if you could switch to centos stream 8 / 9.

Not much we can do here.

**Comment by koalawangyang** [comment]
> 



> podman is not in epel, it's in the extras repo, but I think amazon linux 2's own extras repo is something totally different from rhel-extras / centos-extras.
> 
> It might be best to check with AWS support, or check if you could switch to centos 7. Even better if you could switch to centos stream 8 / 9.
> 
> Not much we can do here.

Hi lsm5, thanks for your reply.

Okay, I will contact AWS support about this request.
