### ISSUE TITLE
[Bug]: Uninstalling Podman on Windows leaves Podman VM behind

### ISSUE THREAD

**Issue by biergit** [containers/podman#17395]
### Issue Description

Uninstalling Podman on Windows leaves Podman VM behind. I would expect it to be removed as well.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Install Podman on Windows
2. `podman machine init` to create the VM
3. Uninstall Podman

### Describe the results you received

The Podman VM is still accessible after uninstalling

### Describe the results you expected

Podman tries its best to leave no trace.

### podman info output

```yaml
Podman 4.3.1
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
@n1hility PTAL

**Comment by n1hility** [comment]
This is intentional so that you do not have data loss. In some cases, for example, a downgrade, you need to uninstall and reinstall, so this would not be ideal. In the future we could perhaps enhance the installer to provide a clickable cleanup option.

**Comment by biergit** [comment]
Please provide an option to clear everything if that's what the user wants or document what leftovers have to be removed manually.

**Comment by biergit** [comment]
@omasseau I think `wsl --unregister <distro name>` worked for me. You can show the distro name with `wsl -l -v`

**Comment by n1hility** [comment]
You can also run ‘podman machine rm’ (before uninstalling or reinstalling to run it)

**Comment by jeschb** [comment]
Hello guys.

Try it.

`wsl --list --verbose
wsl --unregister podman-machine-default`

So, you can return with the first command and **podman-machine-default** doesn't appear.

Now, youi can type `podman machine init` and it works!.

Regards.

**Comment by sh41** [comment]
> Manually delete these folders: (**C:\Users\Chuss is my windows home folder**). `C:\Users\Chuss\.local\share\containers\podman\machine\wsl` `C:\Users\Chuss\.config\containers\podman\machine` `C:\Users\Chuss\AppData\Roaming\containers`
> 
> And delete this file: `C:\Users\Chuss\.ssh\podman-machine-default.pub`

For convienence you can use %USERPROFILE% to provide your own user path: 

Delete these folders:
```
%USERPROFILE%\.local\share\containers\podman\machine\wsl
%USERPROFILE%\.config\containers\podman\machine
%USERPROFILE%\AppData\Roaming\containers
```

And this file
```
%USERPROFILE%\.ssh\podman-machine-default.pub
```
