### ISSUE TITLE
[Bug]: Changing from cni to netavark breaks port exposing over the podman system rest api

### ISSUE THREAD

**Issue by codemaker219** [containers/podman#17407]
### Issue Description

If I try to start a container via the podman system service, I am not able to expose a port that that binds to `0.0.0.0`

### Steps to reproduce the issue

1.  I played around with the "new" network stack netavark. (Currently using cni). 

So lets create a ipv6 network:  (not sure if ipv6 is the issue, I just want to mention this, I am using ipv6)

`podman network  create --driver bridge --gateway "100.65.1.1" --subnet "100.65.1.0/24" --ipv6 --gateway "fdfb:991c:79de:6501::1" --subnet "fdfb:991c:79de:6501::/64" example`

2. Then start the podman system service 

` podman system service tcp:127.0.0.1:8090 --log-level=debug  --time=0`

3. Create the container:
 `curl -d '{"image":"docker.io/nginx","name":"frontend","hostname":"frontend","networks":{"example":{}},"portmappings":[{"protocol":"tcp","container_port":80,"host_port":80,"host_ip":"0.0.0.0"}]}
' 127.0.0.1:8090/v1.40.0/libpod/containers/create -vvv -H 'Content-Type: application/json'`

5.  Start the container:

` curl -s -X POST 127.0.0.1:8090/v1.40.0/libpod/containers/frontend/start`

6. Try `curl localhost` it hangs until tcp timeout. 

Note: The command equivalent `podman run -p 0.0.0.0:80:80 --rm -d  --network example --name frontend docker.io/nginx
` is working... (but maby i am root?)

### Describe the results you received

TCP timeout

### Describe the results you expected

No TCP timeout up html response (in this case)

### podman info output

```yaml
[root@xxx ~]# podman info
host:
  arch: amd64
  buildahVersion: 1.27.3
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: 24a4eb8c5272ea46c28889a24fc0a9ba1f4b0c74'
  cpuUtilization:
    idlePercent: 99.99
    systemPercent: 0.01
    userPercent: 0.01
  cpus: 9
  distribution:
    distribution: '"almalinux"'
    version: "9.1"
  eventLogger: journald
  hostname: xxxxx
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.0-162.12.1.el9_1.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 15491923968
  memTotal: 16147668992
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.el9_0.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 8275357696
  swapTotal: 8275357696
  uptime: 6h 33m 17.00s (Approximately 0.25 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 75125227520
  graphRootUsed: 1944629248
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1674509457
  BuiltTime: Mon Jan 23 22:30:57 2023
  GitCommit: ""
  GoVersion: go1.18.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Running almalinux 9.1 in a vm

### Additional information

nonen

**Comment by Luap99** [comment]
> Note: The command equivalent podman run -p 0.0.0.0:80:80 --rm -d  --network application --name frontend docker.io/nginx is working... (but maby i am root?)

This command does not use the example network?!

your API query looks ok to me, there should be no difference to the cli.

What is your netavark version? We can only support he latest version upstream, I suggest you try to update to the latest version first, it is possible that this bug is already fixed.
You can also check the iptables rules with `ip6tables -t nat -nvL` and  `ip6tables -nvL` to see if there any difference between netavark and cni.

**Comment by codemaker219** [comment]
> This command does not use the example network?!

Sorry I meant example. 

I created a new VM with all the greatest an latest.

`Installed Packages
Name         : netavark
Epoch        : 2
Version      : 1.1.0
Release      : 7.el9_1
Architecture : x86_64
Size         : 8.7 M
Source       : netavark-1.1.0-7.el9_1.src.rpm
`

**Comment by rhatdan** [comment]
@Luap99 any update on this one?

**Comment by Luap99** [comment]
I have not looked at it yet.

**Comment by Luap99** [comment]
I think https://github.com/containers/netavark/pull/638 may fix it.

**Comment by Luap99** [comment]
Looks like I forgot to close this issue
