### ISSUE TITLE
[Bug]: can't push images to local registry

### ISSUE THREAD

**Issue by 524c** [containers/podman#17406]
### Issue Description

Hello guys,

I have a Docker environment on a MacOS, and among other things, I have a local Registry, with http (insecure) access, which I managed to get working with a lot of effort. Now I'm trying to migrate things to work with Podman and right now when trying to push an image I get this error.
`Error: trying to reuse blob sha256:768661b0a155f63fa8ee46919bb77f90d33cc15ae9e2dd0ea4e9abbe8665940c at destination: pinging container registry registry.local:5000: Get "https://registry.local:5000/v2/": dial tcp: lookup registry.local: Temporary failure in name resolution`

The name `registry.local` is defined in `/etc/hosts`. Apparently Podman tries to access the server, but it cannot resolve the name and the URL looks like this, as shown in the log below:
`DEBU[0000] DoRequest Method: POST URI: http://d/v4.3.1/libpod/images/registry.local:5000/node-web-app/push
`

command:
`podman --log-level=debug push registry.local:5000/node-web-app`

output:
```
INFO[0000] podman filtering at log level debug
DEBU[0000] Called push.PersistentPreRunE(podman --log-level=debug push registry.local:5000/node-web-app)
DEBU[0000] SSH Ident Key "/Users/rlucas/.ssh/podman-machine-default" SHA256:MbhME2ZhzP+DmKSlpbm+yGY+j6FC3k4BDr9WxVFF/t0 ssh-ed25519
DEBU[0000] DoRequest Method: GET URI: http://d/v4.3.1/libpod/_ping
DEBU[0000] Loading registries configuration "/Users/rlucas/.config/containers/registries.conf"
DEBU[0000] Found credentials for rpi4-1:5000 in credential helper containers-auth.json in file /Users/rlucas/.config/containers/auth.json
DEBU[0000] Found credentials for 192.168.1.4:5000 in credential helper containers-auth.json in file /Users/rlucas/.config/containers/auth.json
DEBU[0000] Found credentials for localhost:5000 in credential helper containers-auth.json in file /Users/rlucas/.config/containers/auth.json
DEBU[0000] Found credentials for registry.local:5000 in credential helper containers-auth.json in file /Users/rlucas/.config/containers/auth.json
DEBU[0000] DoRequest Method: POST URI: http://d/v4.3.1/libpod/images/registry.local:5000/node-web-app/push
Getting image source signatures
Copying blob sha256:4197f7214e0170f09df9df2a97fe018f41e4e983a31d5e1cc43664d6c7f7bb08
Copying blob sha256:e2c36140d36a57a8031f9bc31159e83c03ff2ec58433f27f3581fd19a689f2c0
Copying blob sha256:3b7c989449c582820a3b7950661c2df29c92939e831c1399c07e818a2d562552
Copying blob sha256:024c0b0eec0444509f08a93f597ae6cc567f02c374e16d67835668351273a8f3
Copying blob sha256:5767e262c35e18f3a0066028f3e678cb40b04cba6ad087b7fbb7ebbe2d2986f6
Copying blob sha256:768661b0a155f63fa8ee46919bb77f90d33cc15ae9e2dd0ea4e9abbe8665940c
Copying blob sha256:a205a7bbdfe04b552fa353d43847917b308780146718f45ecc2a0e499056f0b4
Copying blob sha256:567d43b0f38b2720b36e4fd8760cbf7b2074431e6e59398463033390c5a103cc
Copying blob sha256:ea91e8fcfcc8aca0218a4b5eb0034841d810fe5d2fd5a147008c1d3464f1dc8e
Copying blob sha256:d8fa520091e2e20ff19c51be2291c31f12368e8339a0b4aa114bfd1650ad957a
Copying blob sha256:5727316e11f1ffa1107c57fc648d5276580144eb1924458ee03f8a9dbf43cc89
Copying blob sha256:2cd8016c912b482b37b702776a5d00953a19966893268f7c2d75b234d1d3306b
Error: trying to reuse blob sha256:768661b0a155f63fa8ee46919bb77f90d33cc15ae9e2dd0ea4e9abbe8665940c at destination: pinging container registry registry.local:5000: Get "https://registry.local:5000/v2/": dial tcp: lookup registry.local: Temporary failure in name resolution
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. Added to $HOME/.config/containers/registries.conf the registry where I intend to pull the image
```
unqualified-search-registries = ["registry.local:5000"]

[[registry]]
insecure = true
location = "registry.local:5000"
```

2. push the image: `podman --log-level=debug push registry.local:5000/node-web-app`
`Error: trying to reuse blob sha256:768661b0a155f63fa8ee46919bb77f90d33cc15ae9e2dd0ea4e9abbe8665940c at destination: pinging container registry registry.local:5000: Get "https://registry.local:5000/v2/": dial tcp: lookup registry.local: Temporary failure in name resolution`

### Describe the results you received

Describe the results you received

### Describe the results you expected

Managed to upload an image to a local registry, connecting via http, in insecure mode.

### podman info output

```yaml
- memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.5-1.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 99.29
    systemPercent: 0.54
    userPercent: 0.17
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "37"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 502
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.1.6-200.fc37.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 199860224
  memTotal: 2065825792
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.7.2-3.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.7.2
      commit: 0356bf4aff9a133d655dc13b1d9ac9424706cac4
      rundir: /run/user/502/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/502/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3

plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 5921193984
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 10
  runRoot: /run/user/502/containers
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 1668178887
  BuiltTime: Fri Nov 11 12:01:27 2022
  GitCommit: ""
  GoVersion: go1.19.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1
```

### Podman in a container

Yes

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

MacOs, Ventura, Intel.

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
The main podman code runs in the podman machine VM (linux), so I assume you would need to add the entry there to /etc/hosts. You can use `podman machine ssh` to access it

**Comment by 524c** [comment]
Hello, thanks for the quick response. I added the entry in hosts, but it still didn't work. I made a video showing step by step.

https://user-images.githubusercontent.com/527641/217292765-59529306-b967-489a-bd05-da4bf81eedcd.mp4

**Comment by 524c** [comment]
Before, I was trying to use podman on both sides: server and client. Now I'm trying to simplify and/or isolate the problem, so on the server side (Linux) I'm using docker with a running docker registry server. Left side of the video.

On the client side, right side of the video, using docker and podman.


https://user-images.githubusercontent.com/527641/217299575-f5db3914-8832-4a1f-9258-64d7ca6d47fa.mp4

**Comment by 524c** [comment]
> Before, I was trying to use podman on both sides: server and client. Now I'm trying to simplify and/or isolate the problem, so on the server side (Linux) I'm using docker with a running docker registry server. Left side of the video.
> 
> On the client side, right side of the video, using docker and podman.
> 
>  podman-2.mp4

Now I just need to know where I save the certificate. I'm going to try something similar that I follow with Docker. If you can, help me by indicating what is the equivalent in Podman, thank you @Luap99

**Comment by 524c** [comment]
As an improvement suggestion, the Podman client side could make these settings automatically in the VM, so we wouldn't even remember that there is a VM doing the work behind the scenes 😁

**Comment by 524c** [comment]
As a suggested improvement, Podman Desktop could allow inserting insecure registers as well 😁

**Comment by rhatdan** [comment]
I would suggest this is something potentially podman machine init could handle.
