### ISSUE TITLE
[Feature]: Quadlet support for relative paths for Volume source

### ISSUE THREAD

**Issue by ygalblum** [containers/podman#17418]
### Feature request description

Currently, the `Volume` key in the Quadlet `Container` group is equivalent to the `-v` parameter of `podman  run` with one exception of depending on Quadlet based volumes (via `.volume` files). 
As a result, the source (if provided) is interpreted the following way:
- If it starts with a `/`, it is an absolute path to a directory on the Host
- Otherwise, it is a named volume
The request is to support relative paths. Quadlet should then translate them based on the location of the location of the `.container` file, similar to the way it handles the `EnvironmentFile` key.

### Suggest potential solution

Unlike other path cases, for `Volume` there is already a meaning for a source value that does not start with `/`. So, to support it, Quadlet will have to require that the relative path starts with a `.`

### Additional context

I'm opening this ticket to continue the discussion in comment: https://github.com/containers/podman/discussions/17177#discussioncomment-4897428

/label quadlet

**Comment by rhatdan** [comment]
SGTM

**Comment by rhatdan** [comment]
@ygalblum Did you try relative paths which begin with ./ or ../?

**Comment by ygalblum** [comment]
Following your comment I just did.
`.container` file:
```
[Container]
Image=registry.fedoraproject.org/fedora:36
Volume=./hello:/hello
```
which produces the `.service` file with `ExecStart` set to:
```
ExecStart=/usr/bin/podman run --name=systemd-%N --cidfile=%t/%N.cid --replace --rm --log-driver passthrough --runtime /usr/bin/crun --cgroups=split --sdnotify=conmon -d -v ./hello:/hello registry.fedoraproject.org/fedora:36
```
Starting the service fails:
```
Error: lstat hello: no such file or directory
```

This is not a surprise since the base directory is not what the user intended it to be. For example, for user services the base directory if `$HOME`.

In addition, since Quadlet looks for `/` to mark a path, the service file does not include the `RequiresMountsFor` key for the path to be mounted.

Having said that, once I created the directory `$HOME/hello`, the container started successfully (but still without setting the `RequiresMountsFor` key)

**Comment by rhatdan** [comment]
We could make quadlet smarter and add $PWD to the front of all relative paths and then resolve it to a real path.

**Comment by ygalblum** [comment]
RequireForMount is a systemd unit key word: https://www.freedesktop.org/software/systemd/man/systemd.unit.html#RequiresMountsFor=

Adding PWD will not solve the issue because it is implicitly inferred anyhow by Podman to the execution directory (for user its `$HOME`). Instead what Quadlet can do is resolve the relative path to an absolute. The base directory that  should be used is where the `.container` file resides.

As I pointed in my initial comment, relative path will have to start with `.` to differentiate it from a Podman volume. This actually aligns with how the `-v` arguments works.

**Comment by rhatdan** [comment]
Agreed
