### ISSUE TITLE
[Feature]: Network Bandwidth Limiter

### ISSUE THREAD

**Issue by CDFN** [containers/podman#17414]
### Feature request description

Bandwidth limiter would allow limiting network traffic for specific pod or sets of pods. Something like [Cilium Bandwidth Manager](https://docs.cilium.io/en/v1.12/gettingstarted/bandwidth-manager/) would be awesome feature to have. It would allow providing better QoS.

### Have you considered any alternatives?

I have considered using parent cgroup for a pod. An `iptables` filter would catch all outgoing packets from that cgroup and mark them. Then `tc` would apply bandwidth limit based on mark assigned by `iptables`. Haven't had much luck trying to make this plan live though.

**Comment by rhatdan** [comment]
@Luap99 @baude @mheon THoughts?

**Comment by baude** [comment]
to me, sounds like a netavark plugin.

**Comment by CDFN** [comment]
I'd love if someone looked whether https://www.cni.dev/plugins/current/meta/bandwidth/ could be used. I'm not too familiar with Podman networking. Looks like this could be possibly applied fairly easy as it's CNI plugin and as far as I know Podman can use those.

**Comment by baude** [comment]
@CDFN you could look at that CNI plugin and then write a netavark plugin -> https://github.com/containers/netavark/blob/main/plugin-API.md
