### ISSUE TITLE
The latest release of podman (v4.4.1) is missing the compiled assets

### ISSUE THREAD

**Issue by MatthewDolan** [containers/podman#17441]
### Issue Description

Comparing https://github.com/containers/podman/releases/tag/v4.4.1 to https://github.com/containers/podman/releases/tag/v4.4.0, the asset section is missing the compiled assets (e.g. `podman-remote-static-linux_arm64.tar.gz`).

![Screenshot 2023-02-08 at 13 11 27](https://user-images.githubusercontent.com/1056326/217651811-4b6f4c80-5281-4832-8072-6f3b0c2bb6a1.png)

### Steps to reproduce the issue

1. Click on the latest release page.

### Describe the results you received

Unable to download the assets.

### Describe the results you expected

Expected to be able to download the assets.

### podman info output

```yaml
N/A
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by MatthewDolan** [comment]
Looks like this has been resolved.

**Comment by rhatdan** [comment]
Glad you are this anxious to get them though. :^)
