### ISSUE TITLE
podman --url ssh:// fails wierdly

### ISSUE THREAD

**Issue by avikivity** [containers/podman#17452]
### Issue Description

`podman --url ssh://...` fails to work in strange ways.

### Steps to reproduce the issue

I have the podman socket listening on localhost. To explore how podman/ssh work, I try connecting to it via ssh. 

To start with, unix: does not have good defaults. I can get it to work with

```sh
podman  --url=unix://run/user/1000/podman/podman.sock ps
```

But things like

```sh
podman --url=unix://
```

or

```sh
podman  --url=unix://avi@ ps
```

Fail with

```
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.3.1/libpod/_ping": dial unix //: connect: permission denied
```

This is a minor usability problem as I have to remember that podman socket path template and supply my uid. I think it could be guessed for unix://user@.

Next, for ssh:

```sh
$ podman  --url=ssh://localhost ps
Error: strconv.Atoi: parsing "": invalid syntax
```

```sh
$ podman  --url=ssh://avi@localhost/ ps
Error: strconv.Atoi: parsing "": invalid syntax
```

I guess it wants the port, but really it should be defaulted.

```sh
$ podman  --url=ssh://avi@localhost:22/ ps
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.3.1/libpod/_ping": ssh: rejected: connect failed (open failed)
```

Now I need to supply the path. Given it's a remote path, I need to know my remote uid.

This works:

```sh
podman  --url=ssh://avi@localhost:22/run/user/1000/podman/podman.sock ps
```

But one needs to supply the default ssh port, the default podman socket path, and their remote uid, which they really shouldn't need to.

### Describe the results you received

Intermingled with the reproducer.

### Describe the results you expected

`--url ssh://avi@localhost` works and no internal error messages.

### podman info output

```yaml
$ rpm -q podman
podman-4.3.1-1.fc37.x86_64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Fully updated Fedora 37.

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
I think the default port thing for ssh was already fixed in 4.4. https://github.com/containers/podman/pull/16526

While we could assume some more defaults I think it makes more sense to just use `podman system connection ...` to manage connection urls. So you can just do `podman -c <CONNAME> ...`

**Comment by avikivity** [comment]
But then I still have to supply those full URLs, no?

I think it's nicer if I don't have to know things like the UID on a remote machine.

**Comment by rhatdan** [comment]
Care to open a PR to handle this?

**Comment by avikivity** [comment]
> Care to open a PR to handle this?

If you mean me, then no. I can't justify the effort to learn the podman codebase and (a small subset of) golang just to fix this wart.

**Comment by dustymabe** [comment]
I agree that not having to know the numerical remote user ID would be nice.
