### ISSUE TITLE
podman4.3.0 compile error in Yocto

### ISSUE THREAD

**Issue by yanglianping** [containers/podman#17467]
### Issue Description

Hi,

I need to add podman4.3.0 to my Yocto project. But when I make the project, it will report "No rule to make target 'pkg/varlink/iopodman.go'" error. The detail message show as bellow:

_ERROR: Logfile of failure stored in: /home/ubuntu18/newfile/yocto-sdk/build_ls1046afrwy/tmp/work/aarch64-fsl-linux/podman/4.3.0+gitAUTOINC+ad42af9490-r0/temp/log.do_compile.6366
Log data follows:
| DEBUG: Executing shell function do_compile
| NOTE: make -j 4 PREFIX=/usr BINDIR=/usr/bin LIBEXECDIR=/usr/libexec ETCDIR=/etc TMPFILESDIR=/usr/lib/tmpfiles.d SYSTEMDDIR=/lib/systemd/system USERSYSTEMDDIR=/lib/systemd/user pkg/varlink/iopodman.go GO=go
| make: *** No rule to make target 'pkg/varlink/iopodman.go'.  Stop.
| ERROR: oe_runmake failed
| WARNING: /home/ubuntu18/newfile/yocto-sdk/build_ls1046afrwy/tmp/work/aarch64-fsl-linux/podman/4.3.0+gitAUTOINC+ad42af9490-r0/temp/run.do_compile.6366:1 exit 1 from 'exit 1'
| ERROR: Execution of '/home/ubuntu18/newfile/yocto-sdk/build_ls1046afrwy/tmp/work/aarch64-fsl-linux/podman/4.3.0+gitAUTOINC+ad42af9490-r0/temp/run.do_compile.6366' failed with exit code 1:
| make: *** No rule to make target 'pkg/varlink/iopodman.go'.  Stop.
| WARNING: /home/ubuntu18/newfile/yocto-sdk/build_ls1046afrwy/tmp/work/aarch64-fsl-linux/podman/4.3.0+gitAUTOINC+ad42af9490-r0/temp/run.do_compile.6366:1 exit 1 from 'exit 1'
|
ERROR: Task (/home/ubuntu18/newfile/yocto-sdk/sources/meta-virtualization/recipes-containers/podman/podman_git.bb:do_compile) failed with exit code '1'
NOTE: Tasks Summary: Attempted 3638 tasks of which 3637 didn't need to be rerun and 1 failed._

Could you please help check the error and give some support, thanks.

The podman.git.bb refer to attachment.
[podman_git.zip](https://github.com/containers/podman/files/10705305/podman_git.zip)

### Steps to reproduce the issue

Steps to reproduce the issue
1. add "IMAGE_INSTALL += "podman"" to my Yocto bb file
2. use bitbake to make project

### Describe the results you received

The error "No rule to make target 'pkg/varlink/iopodman.go'" report when build podman

### Describe the results you expected

Solve the error, build podman4.3.0 into Yocto project

### podman info output

```yaml
podman4.3.0
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by giuseppe** [comment]
where is `pkg/varlink/iopodman.go` coming from?

I think you need to update the bitbake definition to not attempt building that

**Comment by Luap99** [comment]
Varlink is not part of podman since at least v3.0, I suggest that you update your makefile: https://github.com/containers/podman/pull/8400/commits/f62a356515e387b0bbcf1f08b4831d139c2039b7
