### ISSUE TITLE
HTTP Communication Issue between Podman Containers in the same Network

### ISSUE THREAD

**Issue by mdsposadas** [containers/podman#17468]
### Issue Description

The setup is for 2 Containers (Client and Server) under the same Network using Podman. 
We are trying to perform inter-container communication using HTTP Requests.
The Client container is running a python script that uses urllib which tries to send a HTTP Request to the Server Container.
Current issue is that the Client container encounters the following error: **Temporary failure in name resolution**

The same setup was created using Docker and it works perfectly. 
Also, the same setup was used but using Socket Communication instead of HTTP communication and it works for either Podman rootful or rootless containers.

### (1) For the Server and Client, the following files are used:
**Server**
_index.html_: file used to send as response to Client upon HTTP request
![0_nano_index_html](https://user-images.githubusercontent.com/94945936/218048334-74c8c00d-e4bc-4cf4-aea9-01bbb9799aa1.JPG)

_server.py_: script used to create and start the Web Server
![2_nano_server_py](https://user-images.githubusercontent.com/94945936/218048473-503a63a5-289c-400c-9cda-0bc12882f4a1.JPG)

_Dockerfile_: file used to build the podman image for the Server Container
![3_nano_Dockerfile](https://user-images.githubusercontent.com/94945936/218048543-0497bd9f-4b63-46b8-af58-6832e9602b75.JPG)

**Client** 
_client.py_: script used to send request to Web Server, which in turn will acquire the response from the Server
![2_nano_client_py](https://user-images.githubusercontent.com/94945936/218049832-794bbb7d-3d39-4934-afd3-f3389d5d04db.JPG)

_Dockerfile_: file used to build the podman image for the Client Container
![3_nano_Dockerfile](https://user-images.githubusercontent.com/94945936/218050424-ebdde9d1-6316-432a-9728-23d979cdd8ac.JPG)
_____________________________________________________________________________

###  (2) The overall environment was created with the following commands:
**(2.1)**
 To begin, the network is created in which the 2 containers (Client and Server) will operate.
`sudo podman create --name=test_server --network=test-network --ip=172.18.0.2 --network-alias test_server -p 1234:1234 --restart always test_server:00.00.01 python ./server.py`

Here is the network configuration of the network created:
![3_podman_network_inspect_test-network](https://user-images.githubusercontent.com/94945936/218051396-8764ca1a-6f42-431c-ba5b-135c470983a3.JPG)

**(2.2)**
Afterwards, the images are built for the containers of the Server and Client.
_Server_
![4_podman_build_test_server](https://user-images.githubusercontent.com/94945936/218058309-64c75e3a-2bce-49ad-bef7-58d429393537.JPG)

_Client_
![4_podman_build_test_client](https://user-images.githubusercontent.com/94945936/218051628-876b4751-9059-44bb-bd90-46b5a939030c.JPG)

**(2.3)**
The containers are then built for the Server and the Client using the Images built from the previous step.
_Server_
`sudo podman create --name=test_server --network=test-network --ip=172.18.0.2 --network-alias test_server -p 1234:1234 --restart always test_server:00.00.01 python ./server.py`

_Client_
`sudo podman create --name=test_client --network=test-network --ip=172.18.0.3 --network-alias test_client --restart always test_client:00.00.01 python ./client.py`

**(2.4)**
Afterwards, 2 terminals are opened to attach to each containers and the following error was encountered on the Client Container:
_Server_
![6_podman_start_test_server](https://user-images.githubusercontent.com/94945936/218052509-4b3f165e-cab9-4b01-9945-ff77722fd8db.JPG)

_Client_
![6_podman_start_test_client](https://user-images.githubusercontent.com/94945936/218052466-8cca5e77-efed-478b-a11e-7771f3cae13c.JPG)

### Describe the results you received

The Client container once executed encounters an error: **Temporary failure in name resolution**
![6_podman_start_test_client](https://user-images.githubusercontent.com/94945936/218053124-66ba4edb-ba71-4d3a-b280-440b3e57b757.JPG)

### Describe the results you expected

The Client container should not encounter an error and should run smoothly, providing the message shown below which comes as the response from the Server container:
![6_podman_start_test_client_OK](https://user-images.githubusercontent.com/94945936/218054241-54566f84-ddd3-4627-a1f5-edf5b7f9573b.JPG)

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.1.2, commit: '
  cpus: 4
  distribution:
    codename: focal
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: signal5g-VirtualBox
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.0-58-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 192974848
  memTotal: 8335736832
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: ea1fe3938eefa14eb707f1d22adff4db670645d6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 970903552
  swapTotal: 1469710336
  uptime: 76h 39m 56.23s (Approximately 3.17 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/signal5g/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/signal5g/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/signal5g/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 0
  BuiltTime: Thu Jan  1 08:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 3.4.2
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

Additional environment details: 

(1) Virtual Machine (VirtualBox) - Ubuntu 20.04 LTS
> $ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### Additional information

For additional reference, we've provided the interface configuration below:
![4_ifconfig](https://user-images.githubusercontent.com/94945936/218052747-1aadb0e2-3256-45bc-b4cc-84d5fc0c4b94.JPG)

**Comment by Luap99** [comment]
Sorry we cannot support 3.4, it is just way to old at this point. I suggest you update to the latest podman version with the new network stack netavark and test if this works better for you.

**Comment by Luap99** [comment]
AFAIK ubuntu 22.04 still only has podman v3.4.4.
I don't really care what distro you use or how you get podman. As upstream maintainer we simply do not have time to deal with these things. The netavark stack contains a completely new dns server called aardvark-dns which fixed a lot of dns problems.

**Comment by mdsposadas** [comment]
Hello! We tried the same setup only this time we are using the latest version of podman:
![image](https://user-images.githubusercontent.com/94945936/218729952-81f30b88-238e-4897-9a74-4701bfc9fdda.png)

From the previous setup, we encountered the following error:
> Temporary failure in name resolution

However, for the current setup in using the latest podman version, we encountered the following error:
<img width="341" alt="image_1" src="https://user-images.githubusercontent.com/94945936/218731158-9553cd5f-4ca7-498d-8cb9-990604ef7bc9.png">

We tried changing the hostname being used by the client to communicate to the server and encountered the underlying URL errors when the Client container is started:
- http://172.18.0.1:1234/ : 503 Service Unavailable
- http://172.18.0.2:1234/ : 503 Service Unavailable
- http://localhost:1234/ : 403 Forbidden 

We also tried using the following command which connects the Client container to the Network being used:
`sudo podman network connect test-network test_client`

The same errors were encountered as well upon the use of the aforementioned command.

**Comment by mdsposadas** [comment]
Hello @Luap9! Can we have any feedback about this one?

**Comment by Luap99** [comment]
Sorry I don't really understand what you are doing. If you get HTTP responses then as far as podman is concerned networking is working but your application seems to respond with errors.

**Comment by mdsposadas** [comment]
This is a bit weird that the application is not working, considering that it works when docker is used instead of podman. We will check this further on our end. 

Thank you for the feedback @Luap99!

**Comment by mdsposadas** [comment]
Hello @Luap99! Is it ok to post this in the Discussion Section as well? Maybe others will have an idea about it.

**Comment by mdsposadas** [comment]
Hello @Luap99! I am closing this ticket and opened another ticket in the Discussion Section (Q&A).
You can refer to the new ticket here:
[https://github.com/containers/podman/discussions/17637](url)
