### ISSUE TITLE
libpod/containers/create，The api interface does not provide the host network mode for specifying the creation container

### ISSUE THREAD

**Issue by aohanhe** [containers/podman#17475]
I tried to use the podman api to create the container and specify its network mode as host, but could not find the api reference for details on how to do this? Is there any other way? Or am I missing something?

**Comment by Luap99** [comment]
you need to set the netns nsmode to "host":
```
...
"netns": {"nsmode":"host"}
...
```
API reference: https://docs.podman.io/en/latest/_static/api.html#tag/containers/operation/ContainerCreateLibpod

**Comment by aohanhe** [comment]
thanks



At 2023-02-13 22:23:57, "Paul Holzinger" ***@***.***> wrote:

you need to set the netns nsmode to "host":

...
"netns": {"nsmode":"host"}
...


API reference: https://docs.podman.io/en/latest/_static/api.html#tag/containers/operation/ContainerCreateLibpod
