### ISSUE TITLE
podman restore failed when migrating to another host : exited (132)

### ISSUE THREAD

**Issue by limjunho** [containers/podman#17496]
### Issue Description

Hi,

I tried jupyter notebook in container migrates to another host using podman.
The testing host is AWS on-demand t2 and t3.

When starting the container and checkpoint at t2, migrating to t3 is a success, and t2 -> t3 -> t2 migration testing is a success.
However, t3 -> t2 migration is failed

Here are the commands I used.

// create a container
sudo podman run -p 8888:8888 -e GRATN_SUDO=yes --user root --name jupynb docker.io/jupyter/base-notebook start-notebook.sh --NotebookNotary.db_file=':memory:'

// checkpoint
sudo podman container checkpoint --file-locks --tcp-established --keep --export dump.tar.gz jupynb

// restore
sudo podman container restore --file-locks --tcp-established --keep --import dump.tar.gz

Why fail to restore? 

I apologize for my poor English.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Start AWS EC2 Instance(t2, t3)
2. Run container at t3(Execute the commands I used)
3. Migrate t3 to t2 and restore from t2 instance(execute the command used)

### Describe the results you received

[ec2-user@t2-rhel9 podman]$ sudo podman ps -a
CONTAINER ID  IMAGE                                   COMMAND               CREATED            STATUS                          PORTS                   NAMES
e97e6e497596  docker.io/jupyter/base-notebook:latest  start-notebook.sh...  About an hour ago  Exited (132) About an hour ago  0.0.0.0:8888->8888/tcp  jupynb

---
### restore log

/var/lib/containers/storage/overlay-containers/e97e6e497596a019e0124ee006b60d20f367048541648584df3a83088207f857/userdata/restore.log

```
(00.112352) 21517 (native) is going to execute the syscall 3, required is 15
(00.112359) 21516 was trapped
(00.112362) 21516 (native) is going to execute the syscall 3, required is 15
(00.112372) 21494 was trapped
(00.112376) 21494 (native) is going to execute the syscall 202, required is 15
(00.112388) 21516 was trapped
(00.112392) 21516 (native) is going to execute the syscall 3, required is 15
(00.112398) 21494 was trapped
(00.112402) 21494 (native) is going to execute the syscall 202, required is 15
(00.112412) 21516 was trapped
(00.112416) 21516 (native) is going to execute the syscall 3, required is 15
(00.112428) 21494 was trapped
(00.112433) 21494 (native) is going to execute the syscall 3, required is 15
(00.112444) 21516 was trapped
(00.112447) 21516 (native) is going to execute the syscall 3, required is 15
(00.112475) 21517 was trapped
(00.112479) 21517 (native) is going to execute the syscall 3, required is 15
(00.112485) 21516 was trapped
(00.112488) 21516 (native) is going to execute the syscall 11, required is 15
(00.112505) 21517 was trapped
(00.112509) 21517 (native) is going to execute the syscall 3, required is 15
(00.112519) 21517 was trapped
(00.112522) 21517 (native) is going to execute the syscall 11, required is 15
(00.112552) 21517 was trapped
(00.112556) 21517 (native) is going to execute the syscall 11, required is 15
(00.112561) 21494 was trapped
(00.112565) 21494 (native) is going to execute the syscall 3, required is 15
(00.112575) 21517 was trapped
(00.112579) 21517 (native) is going to execute the syscall 15, required is 15
(00.112617) 21517 was stopped
(00.112622) 21516 was trapped
(00.112626) 21516 (native) is going to execute the syscall 11, required is 15
(00.112636) 21494 was trapped
(00.112641) 21494 (native) is going to execute the syscall 3, required is 15
(00.112647) 21516 was trapped
(00.112651) 21516 (native) is going to execute the syscall 15, required is 15
(00.112758) 21516 was stopped
(00.112768) 21494 was trapped
(00.112772) 21494 (native) is going to execute the syscall 3, required is 15
(00.112807) 21494 was trapped
(00.112812) 21494 (native) is going to execute the syscall 11, required is 15
(00.112851) 21494 was trapped
(00.112856) 21494 (native) is going to execute the syscall 11, required is 15
(00.112888) 21494 was trapped
(00.112893) 21494 (native) is going to execute the syscall 15, required is 15
(00.112923) 21494 was stopped
(00.112962) 21494 was trapped
(00.112967) 21494 (native) is going to execute the syscall 11, required is 11
(00.113006) 21494 was stopped
(00.113048) 21516 was trapped
(00.113053) 21516 (native) is going to execute the syscall 11, required is 11
(00.113097) 21516 was stopped
(00.113138) 21517 was trapped
(00.113143) 21517 (native) is going to execute the syscall 11, required is 11
(00.113188) 21517 was stopped
(00.113229) 21518 was trapped
(00.113234) 21518 (native) is going to execute the syscall 11, required is 11
(00.113297) 21518 was stopped
(00.113303) Run late stage hook from criu master for external devices
(00.113306) restore late stage hook for external plugin failed
(00.113308) Run late stage hook from criu master for external devices
(00.113310) restore late stage hook for external plugin failed
(00.113312) Run late stage hook from criu master for external devices
(00.113314) restore late stage hook for external plugin failed
(00.113316) Run late stage hook from criu master for external devices
(00.113318) restore late stage hook for external plugin failed
(00.113320) Running pre-resume scripts
(00.113323)     RPC
(00.113494) Restore finished successfully. Tasks resumed.
(00.113499) Writing stats
(00.113587) Running post-resume scripts
(00.113590)     RPC
```
---

When I started that container, the memory was gone. I want to preserve the memory.

### Describe the results you expected

restored container state is running.

In case of migrating from t2 to t3, it works as I want.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.27.3
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: 56561007b6a59ea175ee9a67384639721499e160'
  cpuUtilization:
    idlePercent: 99.84
    systemPercent: 0.05
    userPercent: 0.11
  cpus: 2
  distribution:
    distribution: '"rhel"'
    version: "9.1"
  eventLogger: journald
  hostname: t2-rhel9
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.0-162.12.1.el9_1.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 3082174464
  memTotal: 4098260992
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.el9_0.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 0
  swapTotal: 0
  uptime: 23h 44m 7.00s (Approximately 0.96 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/ec2-user/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/ec2-user/.local/share/containers/storage
  graphRootAllocated: 20728229888
  graphRootUsed: 2972577792
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/ec2-user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1670843566
  BuiltTime: Mon Dec 12 20:12:46 2022
  GitCommit: ""
  GoVersion: go1.18.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

### Additional environment details

origin host : AWS EC2 t2.medium
target host : AWS EC2 t3.medium
AWS AMI : RHEL-9.0.0_HVM-20230127-x86_64-24-Hourly2-GP2
Container image : docker.io/jupyter/base-notebook

### Additional information

I suspect the CPU support issue due to the following cases.

[Docker containers exit code 132](https://stackoverflow.com/questions/60930359/docker-containers-exit-code-132)

[Docker container exited with code 132](https://forums.docker.com/t/docker-container-exited-with-code-132/113173)

[Mongo 5.0.0 crashes but 4.4.6 works · Issue #485 · docker-library/mongo](https://github.com/docker-library/mongo/issues/485)

[Docker Exited (132)](https://medium.com/@nprch_12/docker-exited-132-e38f9dd2cd0d)

[docker image failing (exited with code 132) · Issue #4602 · RasaHQ/rasa](https://github.com/RasaHQ/rasa/issues/4602)

* t2 /proc/cpuinfo
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm cpuid_fault invpcid_single pti fsgsbase bmi1 avx2 smep bmi2 erms invpcid xsaveopt

* t3 /proc/cpuinfo
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke

**Comment by giuseppe** [comment]
@adrianreber does the user need to do anything to preserve the memory?

**Comment by adrianreber** [comment]
@limjunho The log file you showed looks like CRIU restored the container successfully.

Can you see something that the process crashed in your logs (or dmesg).

If your process in the container is using features of the CPU which the destination does not have the migration can fail. From the information you have collected I would say, that CRIU was restoring the process successfully, but because it uses CPU features which do not exist on the destination the process might have crashed.

Migrating containers has the same limitations as VM migration, if your destination system does not have features your VM or container is using the migration will  not work.

You can migrate to a CPU with more features, but not to a CPU which does not have a certain feature you are using.

The low level tool doing the checkpointing (CRIU) has the possibility to check for CPU compatibility: https://criu.org/Cpuinfo

But just from looking at the CPU flags of both systems it seems obvious that this might be problematic.

**Comment by limjunho** [comment]
> @limjunho The log file you showed looks like CRIU restored the container successfully.
> 
> Can you see something that the process crashed in your logs (or dmesg).
> 
> If your process in the container is using features of the CPU which the destination does not have the migration can fail. From the information you have collected I would say, that CRIU was restoring the process successfully, but because it uses CPU features which do not exist on the destination the process might have crashed.
> 
> Migrating containers has the same limitations as VM migration, if your destination system does not have features your VM or container is using the migration will not work.
> 
> You can migrate to a CPU with more features, but not to a CPU which does not have a certain feature you are using.
> 
> The low level tool doing the checkpointing (CRIU) has the possibility to check for CPU compatibility: https://criu.org/Cpuinfo
> 
> But just from looking at the CPU flags of both systems it seems obvious that this might be problematic.

I was able to get the following results from the ```criu cpuinfo check``` on the instance that failed to restore.
```
[ec2-user@t2-rhel9 ~]$ sudo criu cpuinfo check
Error (criu/arch/x86/cpu.c:247): cpu: FPU feature required by image is not supported on host (fpu:0 fxsr:0 osxsave:0 xsaves:1)
```
And cpuinfo check of the instance that was successfully restored.
```
[ec2-user@t3-rhel9-t2snap ~]$ sudo criu cpuinfo check
Error (criu/arch/x86/cpu.c:274): cpu: CPU xsave size mismatch (832/2696)
```
I suspected it was a CPU problem, but I couldn't confirm it in detail. Thanks to you, I fully understand my problem and thank you very much for this.

**Comment by limjunho** [comment]
@adrianreber I have some additional questions regarding the CPU compatibility check in CRIU. 

While I know that CRIU has a strict capability mode to check that all CPU features match, it seems that this mode is not always used. Instead, CRIU first conducts compatibility checks at the instruction level, and I'm curious about the x86_ins_capability_mask used for this inspection.

Specifically, I'd like to know why it is defined in criu/blob/criu-dev/criu/arch/x86/cpu.c with fewer features than those found in [linux/cpufeatures.h](https://github.com/torvalds/linux/blob/master/arch/x86/include/asm/cpufeatures.h), and what criteria are used to define the instruction set in x86_ins_capability_mask.

Although I have confirmed in some tests that migration can be successful even if all CPU features do not match. In addition, are there any future plans for compatibility checks for ARM architectures?

**Comment by adrianreber** [comment]
> Specifically, I'd like to know why is `x86_ins_capability_mask` defined in criu/blob/criu-dev/criu/arch/x86/cpu.c less than features found in [linux/cpufeatures.h](https://github.com/torvalds/linux/blob/master/arch/x86/include/asm/cpufeatures.h), and what criteria are used to define the instruction set in x86_ins_capability_mask.

This is a very specific question which you should probably ask over at https://github.com/checkpoint-restore/criu

I cannot answer that.

> Although I have confirmed in some tests that migration can be successful even if all CPU features do not match. In addition, are there any future plans for compatibility checks for ARM architectures?

I am not aware of anybody working on it, but again, better ask that at https://github.com/checkpoint-restore/criu

**Comment by rhatdan** [comment]
Since we have heard no further feedback, closing.
