### ISSUE TITLE
QEMU in release assets requires capstone for amd64

### ISSUE THREAD

**Issue by cpolizzi** [containers/podman#17490]
### Issue Description

This is against the Podman 4.4.1 release.

The macOS installable package includes QEMU and the QEMU build since v7.1.0 requires libcapstone as a dynamic library to be present on the system. Capstone is not and should not be required to use QEMU.

This applies only to the AMD64 release and not the ARM64 release which does not have a dependency on libcapstone.

### Steps to reproduce the issue

On a Mac **without** Homebrew installed and **without** libcapstone.

1. `curl -OL# https://github.com/containers/podman/releases/download/v4.4.1/podman-installer-macos-amd64.pkg`
2. `curl -OL# https://github.com/containers/podman/releases/download/v4.4.1/podman-installer-macos-arm64.pkg`
3. `mkdir -p {amd64,arm64}/stage`
4. `xar -C amd64 -xf podman-installer-macos-amd64.pkg`
5. `xar -C arm64 -xf podman-installer-macos-arm64.pkg`
6. `( cd amd64/stage && cpio -id --quiet < ../podman.pkg/Payload )`
7. `( cd arm64/stage && cpio -id --quiet < ../podman.pkg/Payload )`
8. `otool -L amd64/stage/podman/qemu/bin/qemu-system-x86_64 | grep -c capstone`
`1`
9. `otool -L arm64/stage/podman/qemu/bin/qemu-system-aarch64 | grep -c capstone`
`0`

On either an Intel or M1:
10. `sudo mv amd64/stage/podman /opt`
11. `/opt/podman/qemu/bin/qemu-system-x86_64 --version`
```
dyld[58463]: Library not loaded: '/usr/local/opt/capstone/lib/libcapstone.4.dylib'
  Referenced from: '/opt/podman/qemu/bin/qemu-system-x86_64'
  Reason: tried: '/usr/local/opt/capstone/lib/libcapstone.4.dylib' (no such file), '/usr/lib/libcapstone.4.dylib' (no such file)
zsh: abort      /opt/podman/qemu/bin/qemu-system-x86_64 --version
```
12. `sudo rm -rf /opt/podman`

On an M1 only:
13. `sudo mv arm64/stage/podman /opt`
14. `/opt/podman/qemu/bin/qemu-system-aarch64 --version`
```
QEMU emulator version 7.1.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
```
15. `sudo rm -rf /opt/podman`

### Describe the results you received

AMD64 QEMU cannot locate libcapstone because it was built to have a dependency on it whereas this is not the case for ARM64. libcapstone is not provided by Apple.

### Describe the results you expected

Both AMD64 and ARM64 podman releases not requiring libcapstone for the bundled QEMU respectivly.

### podman info output

```yaml
N/A
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Homebrew not installed and is not desired to be installed just to get libcapstone for AMD64 only.

### Additional information

Only occurs with AMD64.

Since the podman project is pulling the pre-built QEMU from:
* https://github.com/containers/podman-machine-qemu/releases/download/v7.1.0-1/podman-machine-qemu-amd64-7.1.0-1.tar.xz

For completeness, the ARM64 pre-built QEMU is at:
* https://github.com/containers/podman-machine-qemu/releases/download/v7.1.0-1/podman-machine-qemu-aarch64-7.1.0-1.tar.xz

This is where the problem lies since this GitHub project handles the build of QEMU and the podman build for the macOS installable package merely bundles the result.

Looks like all that is needed in that proiect is to update `build-qemu.sh` to include `--disable-capstone` flag when invoking `configure` for the QEMU build.

Podman 4.3.1 did not have this problem and thus QEMU 7.0.0.

**Comment by Luap99** [comment]
I guess it is best to report this directly against https://github.com/containers/podman-machine-qemu
cc @anjannath @gbraad

**Comment by cpolizzi** [comment]
I'll link this issue in that project then.

**Comment by anjannath** [comment]
new release has been published with the fix: https://github.com/containers/podman-machine-qemu/releases/tag/v7.2.0-1 will need to also update the qemu version for the pkg

**Comment by FedeHAL** [comment]
Is this issue fixed? I have desktop 0.12.0 and podman 4.4.2 and still getting the libcapstone lib error.

**Comment by cpolizzi** [comment]
@FedeHAL It's been fixed in the podman-machine-qemu repo for about a month now but the podman has yet to provide a release for it that includes that. This is why I'm still staying on Podman 4.3.1 until the project addresses that.

**Comment by jgresham** [comment]
@ashley-cui could we get a `4.4.3` release for this? :)
