### ISSUE TITLE
Inspection of recently tagged image failed if run 3 or more tag/inspect commands in parallel

### ISSUE THREAD

**Issue by iClaus21** [containers/podman#17515]
### Issue Description

I have one image and want to tag it "tag-1", "tag-2",... and then inspect every image in parallel.

Block of commands:
1) Tag image with unique name
2) Inspect the image via "podman image inspect" using the newly created tag

These command block running in parallel in 3 threads or more.
As a result most of inspects failed.
If I run these commands in 3 threads, so the only inspect command will finished correctly.

### Steps to reproduce the issue

Steps to reproduce the issue:
1. Install podman on the UNIX machine
2. Copy or pull any image via podman (e.g. "podman pull quay.io/dougrabson/hello")
3. Tag it "test-image" via "podman tag {image} {new_tag}" command
4. Execute the attached shell script
```
#!/bin/sh
IMAGE_NAME='test-image'
TAG='tagname'

podman_rmi() {
	local TAG="${TAG}-$1"
	podman rmi ${TAG} >/dev/null 2>&1
}

podman_inspect() {
	local TAG="${TAG}-$1"
	podman tag ${IMAGE_NAME} ${TAG}
	podman image inspect ${TAG} >/dev/null
}

for i in 1 2 3 4 5 6 7 8 9 10; do
	podman_rmi $i
done

for i in 1 2 3 4 5 6 7 8 9 10; do
	podman_inspect $i &
done

wait

for i in 1 2 3 4 5 6 7 8 9 10; do
	podman_rmi $i
done
```

### Describe the results you received

- Script failed for part of images - 
```
# sh shellFile.sh 
Error: inspecting object: tagname-1: image not known
Error: inspecting object: tagname-9: image not known
Error: inspecting object: tagname-4: image not known
Error: inspecting object: tagname-5: image not known
Error: inspecting object: tagname-6: image not known
Error: inspecting object: tagname-8: image not known
Error: inspecting object: tagname-10: image not known
Error: inspecting object: tagname-2: image not known
Error: inspecting object: tagname-3: image not known
Press any key to continue...
```

- Only the 'tagname-7' image inspected successfully
- 1 new image appeared in images list (sometimes it can be 2 or 3 images)

### Describe the results you expected

- Script finished correctly, all inspect commands finished successfully
```
# sh shellFile.sh 
Press any key to continue...
```
- 10 new images appeared in images list

### podman info output

```yaml
Client:       Podman Engine
Version:      4.4.1
API Version:  4.4.1
Go Version:   go1.20
Built:        Wed Feb 15 15:52:51 2023
OS/Arch:      freebsd/amd64
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

**Comment by rhatdan** [comment]
@mheon PTAL
