### ISSUE TITLE
Support --configmap in podman kube play with podman remote

### ISSUE THREAD

**Issue by ycouble** [containers/podman#17513]
### Feature request description

Podman enables the use of kube configmaps when replaying a kube yaml file. (https://docs.podman.io/en/latest/markdown/podman-kube-play.1.html#configmap-path)

However, the option is not made available to the remote client, which, if i understood correctly, means macOS and Windows user cannot use the feature.

The request is to support the configmap option in podman-remote

### Suggest potential solution

Same behaviour as podman kube play --configmap

### Have you considered any alternatives?

Alternative solution would be to include the configmap in the main kube yaml file. Only downside is that it is more tedious to do when passing different configmap files in different context (e.g. production stage related environment variables)

### Additional context

Context : fresh install of podman through `brew`

**Comment by rhatdan** [comment]
Interested in opening a PR to fix?

**Comment by ycouble** [comment]
Sorry, I don't think I would be able to implement any fix, by lack of competency in Go :(

**Comment by rhatdan** [comment]
@umohnani8 PTAL
