### ISSUE TITLE
systemctl stop X does not remove container from systemd unit, but podman stop X removes it from the command line

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#17516]
### Issue Description

I have a systemd .service file containing
```
[Service]
OOMScoreAdjust=-900
Nice=-5

Type=forking
TimeoutStartSec=280
TimeoutStopSec=320
ExecStart=/usr/local/bin/podman run -d --cap-add=IPC_LOCK --log-driver=none --net=host --read-only --read-only-tmpfs=false --mount type=bind,src=/etc/k,dst=/conf --tty --rm=true -a=stderr -a=stdout --userns=auto:size=10 --name=k localhost/k:2023-01-25
ExecStop=/usr/local/bin/podman stop k
StandardOutput=null
```
I do:
```
# systemctl start k
... wait, wait, wait
# systemctl stop k
... wait
# podman ps --all
```
With podman 4.4.2-dev (Git Commit: 396c138ce54c425aded8a88d58d7c7c8aa8c6560) the output now is:
```
# podman ps  --all                    
CONTAINER ID  IMAGE                   COMMAND     CREATED         STATUS                    PORTS       NAMES
09be502ebd67  localhost/k:2023-01-25              13 seconds ago  Exited (0) 2 seconds ago              k
```
The image is present, despite started with `run --rm=true`.  I remove the image (podman rm k), so that podman ps --all shows nothing.

If I call instead from the beginnig `podman stop k` inplace of `systemctl stop k`, then
```console
# podman ps  --all                    
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
```
shows no leftovers.

* Calling `systemd stop k` for a service with `ExecStop=/usr/local/bin/podman stop k` terminates the container, but does not remove it, despite being started with `run --rm=true`.  Calling instead `podman stop k` from the command line does stop and remove the container.

I have no systemd podman.service running.

### Steps to reproduce the issue

see above

### Describe the results you received

see above

### Describe the results you expected

see above

### podman info output

```yaml
host:                                                               
  arch: amd64          
  buildahVersion: 1.29.0                                            
  cgroupControllers:      
  - cpuset               
  - cpu                 
  - io                                                              
  - memory                                                          
  - hugetlb          
  - pids       
  cgroupManager: systemd       
  cgroupVersion: v2                                                 
  conmon:                    
    package: Unknown                                                
    path: /usr/local/libexec/podman/conmon
    version: 'conmon version 2.1.4, commit: '
  cpuUtilization:
    idlePercent: 99.16
    systemPercent: 0.41
    userPercent: 0.43
  cpus: 8
  distribution:
    distribution: unknown
    version: unknown
  eventLogger: journald
  hostname: mail
  idMappings:                                                                                                                   
    gidmap: null
    uidmap: null
  kernel: 5.10.162
  linkmode: dynamic
  logDriver: journald
  memFree: 922918912
  memTotal: 8350883840
  networkBackend: cni
  ociRuntime:
    name: crun
    package: Unknown
    path: /usr/local/bin/crun
    version: |-
      crun version 1.7.2
      commit: 61805dffaf112bf7d883555ea91efac8bcf177a2
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_
SETUID
    rootless: false
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.4
  swapFree: 0
  swapTotal: 0
  uptime: 109h 45m 27.00s (Approximately 4.54 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 519784554496 
  graphRootUsed: 412697800704
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 8
  runRoot: /run/containers/storage 
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.4.2-dev
  Built: 1676470800
  BuiltTime: Wed Feb 15 14:20:00 2023
  GitCommit: 396c138ce54c425aded8a88d58d7c7c8aa8c6560
  GoVersion: go1.19.3
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.2-dev
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
We only support unites generated by podman generate systemd or quadlet, there are a lot of things that can go wrong with a unit like yours.
systemd will kill everything in the cgroup including the podman cleanup process which would remove the container once podman stop exited.
I suggest you just use a unit created with `podman generated systemd --new`

**Comment by dilyanpalauzov** [comment]
Thanks for your answer.  Just adding `--cidfile=%t/%n.ctr-id` to `ExecStart=podman run --cidfile=%t/%n.ctr-id …` and `ExecStop=podman stop --cidfile=%t/%n.ctr-id …` did solve the problem: on `systemctl stop k` the container is removed.

Adding
```
ExecStopPost=/usr/local/bin/podman rm \
        -f \
        --ignore -t 10 \
        --cidfile=%t/%n.ctr-id
```
, as suggested by `podman generate systemd --new k`, was not necessary,

> systemd will kill everything in the cgroup including the podman cleanup process which would remove the container once podman stop exited.

The problem is that podman stop has not removed the container, before exiting. I do not see how cgroups interfere here.

**Comment by dilyanpalauzov** [comment]
> The problem is that podman stop has not removed the container, before exiting.

but does remove the container, when --cidfile is passed to `run` and `stop`, or `podman stop` is called outside systemd-service, on the command shell.

**Comment by vrothberg** [comment]
Podman 4.4 ships with Quadlet which makes running containers in systemd significantly easier.  Feel free to have a look at the man pages (https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html) and upcoming blog posts on www.redhat.com/sysadmin.
