### ISSUE TITLE
Add documentation about Volume specifications when working with systemd

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman#17543]
### Issue Description

Please see https://bugzilla.redhat.com/show_bug.cgi?id=2155780 comment # 13(https://bugzilla.redhat.com/show_bug.cgi?id=2155780#c13)

(In reply to Matthew Heon from [comment #11](https://bugzilla.redhat.com/show_bug.cgi?id=2155780#c11))
> Good catch on the VOLUME in the Dockerfile. The VOLUME semantics have not
> changed, this always meant a volume would be mounted at /sys/fs/cgroup, and
> always replaced Podman's inbuilt handling of that mountpoint for systemd
> containers (we will mount something there appropriate to the system cgroup
> configuration if the container is running systemd as PID 1, but only if the
> user does not explicitly request a mount there). Nearest I can tell, this is
> actually a systemd change (it seems like ubi8-init's 8.7 tag works just fine
> with a non-tmpfs volume at /sys/fs/cgroup), but I think the fact that this
> ever worked in this configuration is a bug. Removing the VOLUME directive
> from the Dockerfile and publishing a new image with that change should fix
> the issue.
> 
> I'm going to CLOSED NOTABUG this given that this is not a regression -
> indeed, the fact that this worked originally would likely have been
> considered a bug.

Can we document this somehow? A lot of howtos here and there state that VOLUME [ "/sys/fs/cgroup" ] should be around. But it must not be. And this is quite new in RHEL8.8. Users can hit this when going from RHEL7.X to RHEL8.8 for example.

### Steps to reproduce the issue

Steps to reproduce the issue
NA

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Code working as designed and expected.  The documentation is very unclear though causing confusion and bugs to be filed.

**Comment by giuseppe** [comment]
I've never seen that before.  What Howtos are we referring to?

The same applies to other mounts like `/proc`, `/sys`, `/dev`.

**Comment by rhatdan** [comment]
Since we got no feedback, closing.
