### ISSUE TITLE
instaling podman on Alpine (Alpine Linux) 

### ISSUE THREAD

**Issue by soukainakhalkhouli** [containers/podman#17563]
### Issue Description

I am trying to install podman on Alpine (Alpine Linux) using the below installation commands:
 apk update
 apk add podman
Post installation, when I try checking the podman version I am getting below error.
level=warning msg="\"/\" is not a shared mount, this could cause issues or missing mounts with rootless containers" Error: kernel does not support overlay fs: unable to create kernel-style whiteout: operation not permitted
Could anyone please help me on the same?

### Steps to reproduce the issue

I have actually gone through this article https://wiki.alpinelinux.org/wiki/Podman. Since I am working on CICD(Tekton) which is using Alpine Linux  as base image, on top of which I wanted to install podman.

### Describe the results you received

level=warning msg="\"/\" is not a shared mount, this could cause issues or missing mounts with rootless containers" Error: kernel does not support overlay fs: unable to create kernel-style whiteout: operation not permitted
Could anyone please help me on the same?

### Describe the results you expected

when I try checking the podman version I am getting below error.

### podman info output

```yaml
level=warning msg="\"/\" is not a shared mount, this could cause issues or missing mounts with rootless containers" Error: kernel does not support overlay fs: unable to create kernel-style whiteout: operation not permitted
Could anyone please help me on the same?
```

### Podman in a container

Yes

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Any help please

**Comment by ReeSilva** [comment]
Maybe you could be missing some steps from here: https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md

Specifically, I think that maybe you're missing the step about `fuse-overlayfs` and even the set of subuid and subgid.

**Comment by giuseppe** [comment]
what is the kernel version?  Are you running in a containerized environment?

Is the error the only output you get from `podman info`?

Is fuse-overlayfs installed?

**Comment by rhatdan** [comment]
Since we heard no response closing.
