### ISSUE TITLE
Context is not optional

### ISSUE THREAD

**Issue by StefanD986** [containers/podman#17568]
## Summary
The description if the `build` command states that `CONTEXT` is optional:
https://github.com/containers/podman/blob/2e0ee6ed50aeae7c0219205cbbc6150ccc70448b/cmd/podman/images/build.go#L51

However one can easily prove that this is not true:

## Steps to reproduce
```bash
mkdir example
cd example
touch Containerfile
podman build
```

### Expected result
Podman should discover the Containerfile in the current directory and use current directory as context.

### Actual result
Podman throws error `Error: no context directory and no Containerfile specified`

## Further notes
- Also the [manual states](https://docs.podman.io/en/latest/markdown/podman-build.1.html) that context is optional 
- I am not sure what the intended behavior is.
  - Should podman discover the context/containerfile automatically?
  - or are the docs wrong and context is only optional if a containerfile is specified with `-f`?

**Comment by flouthoc** [comment]
This is a good first issue, I am leaving a short summary here if someone intends to pick it as a starting issue :)

Summary:
So buildah sets cwd as the contextdir https://github.com/containers/buildah/blob/main/pkg/cli/build.go#L155 if context dir is empty while podman throws error https://github.com/containers/podman/blob/main/cmd/podman/images/build.go#L277

So podman just needs to set context as cwd instead of throwing this error, and maybe retrofit some tests.

**Comment by rhatdan** [comment]
Well you could argue that `podman build` is matching the behaviour of `docker build`

Man page shows it as options `podman build --help` shows it as required.

But I am fine with making it match buildah. I don't see this as a breaking change.

**Comment by StefanD986** [comment]
As a user I think its fine either way (either update docs to match docket behavior, or update code to match docs)

Updating the docs and leave the code to match docker behavior probably has slightly less potential for breaking things (and tests don't need to be changed).

I more or less stumbled over the problem. I initially ran it with context and only after reading the docs thought "ah nice I can omit the context", only to scratch my head shortly afterwards what the heck I am doing wrong.

**Comment by flouthoc** [comment]
Then I guess updating docs should be enough for this, since `docker compat` is more important afaics.

**Comment by rhatdan** [comment]
SGTM
@flouthoc Could you open a PR?

**Comment by vyasgun** [comment]
Opened a PR for this: https://github.com/containers/podman/pull/17602
