### ISSUE TITLE
Support netavark firewall driver forcing

### ISSUE THREAD

**Issue by oskarirauta** [containers/podman#17579]
### Feature request description

Netavark for the moment comes with 2 supported variants of firewall, firewalld and iptables; there's also nftables, but if that is enabled, error is thrown that it isn't currently supported. There has been a feature request on netavark for none firewall, meaning possibility to disable all firewall/portmapper related features to allow their management either manually, possibly with firewall that is not supported by netavark - or not to do it at all, if that's what user wants.

Currently iptables is more or less considered as old- modern distros that don't use firewalld, often go with nftables- in my case, I want to run podman on Openwrt, which goes to later mentioned, except that, I want to configure my firewall manually, whether I use iptables or nftables, there is a small issue; when ever any interface renews, firewall is restarted, leading to situation where manually written rules (outside of system specified ways), disappear for good. Let's say, that my netavark interface is podman0, it comes up and firewall rules are written, shortly after this hotplug system triggers firewall restarting and my container(s) loose all their firewalling capabilities. Best solution in this case, is to use system's own firewalling method manually, there's some ways to archieve this, but it would be great if this just could be a configurable option. Ackording to chatter about the subject, this doesn't affect only openwrt, feature is looked up by other os users as well.

### Suggest potential solution

Feature currently is unsupported by netavark, but in progress. I actually wrote a fork that does support this, but name of value for environment variable should be debated by netavark maintainers- and check if they'd be interested in changing some things, even though my patch does seem to do exactly the requested; as they proposed it.

Usage of feature is by exposing a environment variable for netavark, called NETAVARK_FW - supported values are "firewalld", "iptables", "nftables" where last one causes error mentioned before - and in my patch, value is added to list as "none", meaning to disable firewall features completely by stub firewall driver;

https://github.com/containers/netavark/issues/339#issuecomment-1183282798 explains proposing usage solution for this, value in containers.conf for selecting disabled firewall which then would trigger NETAVARK_FW environment variable adding to netavark commands environment.

So could we have a configuration option to containers.conf that passes NETAVARK_FW as environment variable when netavark is executed? Maybe like this
`
firewall_driver = 'your_choice_of_forced_driver'
`
where value would be passed as NETAVARK_FW environment value if value pair is present in containers.conf.

### Have you considered any alternatives?

At the moment, this is do-able with sticking to cni...
Or you could choose a legacy iptables- or change your distribution to something that uses firewalld..

### Additional context

https://github.com/containers/netavark/issues/339](https://github.com/containers/netavark/issues/339

**Comment by oskarirauta** [comment]
I did not know that exec of netavark had moved to containers/common, so I posted this feature request to there
https://github.com/containers/common/issues/1338

And will close this as soon as it's assigned/replied as this is at wrong place..

**Comment by Luap99** [comment]
It is usually fine to report here, the maintainers for both repos are the same people anyway. But since you already created one there I am going to close this one.
