### ISSUE TITLE
How to run a sshd podman container? (my container gets a fatal: chroot("/usr/share/empty.sshd"): Operation not permitted [preauth])

### ISSUE THREAD

**Issue by groovyman** [containers/podman#17575]
### Issue Description

I took an old Podman-Dockerfile, that was able to run under Fedora F34 without any problem. 
But unfortunately this container is running into a problem, when i try to call it from outside,
the container-sshd throws a:

server/container:   fatal: chroot("/usr/share/empty.sshd"): Operation not permitted `[preauth]`

while the client calls the server-contaner by:

`$  ssh  -CY @chasmash -p 9222 ./jlohn31/startjl.sh `

The idea is to run a Java-Desktop-App like a server-app, without the need to installl it on your local system. This configuration ran for 2 years without any problem, but something changed.

In order to enable the sshd i added a cap flag to the podman-exec:

`$ podman run -d -p 192.168.0.137:9222:22 --name app31_002 --cgroup-manager cgroupfs  -v ${DATA_STORE}/storage:/home/techuser/jlohn:z   -v ${DATA_STORE}/cRTE/varLogs:/var/log:z  --cap-add audit_write  jlohn31_002`

But the system is still rejecting the ssh. So my question is, what do i  have to do, to run a sshd on and inside Fedora installation?

------------------------------------
podman-4.4.1-1.fc37.x86_64

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman  build -t app31_002 -v ${DATA_STORE}/lb:/home/techuser/app:z   --cgroup-manager cgroupfs  .
2. podman run -d -p 192.168.0.137:9222:22 --name app31 --cgroup-manager cgroupfs  -v ${DATA_STORE}/lb:/home/techuser/app:z   -v ${DATA_STORE}/cRTE/varLogs:/var/log:z  --cap-add audit_write  app31_002
3.

### Describe the results you received

```
(client) $ ssh  -CY techuser@server -p 9222 ./app/startjl.sh
Connection closed by 192.168.0.137 port 9222

(container) $ systemctl status sshd
...
...
Feb 20 11:40:39 33a5a8d3f34f systemd[1]: Started sshd.service - OpenSSH server daemon.
Feb 20 11:40:42 33a5a8d3f34f sshd[155]: fatal: chroot("/usr/share/empty.sshd"): Operation not permitted [preauth]
Feb 20 12:29:32 33a5a8d3f34f sshd[220]: fatal: chroot("/usr/share/empty.sshd"): Operation not permitted [preauth]

```
A simple `ssh  techuser@server -p 9222 ` fails too with the same result.

### Describe the results you expected

I would like to see my app on my remote client.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.5-1.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 98.02
    systemPercent: 0.8
    userPercent: 1.18
  cpus: 4
  distribution:
    distribution: fedora
    variant: server
    version: "37"
  eventLogger: journald
  hostname: chasmash
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 6.1.11-200.fc37.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 9555382272
  memTotal: 16414547968
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun-1.8-1.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8
      commit: 0356bf4aff9a133d655dc13b1d9ac9424706cac4
      rundir: /run/user/1001/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 42950709248
  swapTotal: 42950709248
  uptime: 8h 48m 46.00s (Approximately 0.33 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /mnt/raider/home2/techuser/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /mnt/raider/home2/techuser/.local/share/containers/storage
  graphRootAllocated: 11965453828096
  graphRootUsed: 127063613440
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 31
  runRoot: /run/user/1001/containers
  transientStore: false
  volumePath: /mnt/raider/home2/techuser/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.1
  Built: 1675940333
  BuiltTime: Thu Feb  9 11:58:53 2023
  GitCommit: ""
  GoVersion: go1.19.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
I guess you also need `--cap-add sys_chroot`

**Comment by groovyman** [comment]
Your guess was right!
Thx
