### ISSUE TITLE
docker login compatibility issue

### ISSUE THREAD

**Issue by stratdev3** [containers/podman#17571]
### Issue Description

There is a docker login registry compatiliby issue.

### Steps to reproduce the issue

using the original docker command, everything works fine : 

```
$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock docker sh
# echo "mypasswd" | docker login -u mylogin --password-stdin

WARNING! Your password will be stored unencrypted in /root/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
```

but it fails with podman :

```
$ podman run -it --rm -v $XDG_RUNTIME_DIR/podman/podman.sock:/var/run/docker.sock docker sh
# echo "mypasswd" | docker login -u mylogin --password-stdin
Error response from daemon: login attempt to https://index.docker.io/v1/ failed with status: pinging container registry index.docker.io/v1/: invalid status code from registry 404 (Not Found)
```

### Describe the results you received

unable to login to registry with podman

### Describe the results you expected

The login to registry should succeed.

### podman info output

```yaml
$ podman version                                                                                                           125 х │ onedev@sdserver │ 09:12:49
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19.5
Built:        Tue Jan  1 01:00:00 1980
OS/Arch:      linux/amd64
```

### Podman in a container

Yes

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Additional environment details

Test with Nixos 22.11 stable release

**Comment by vrothberg** [comment]
Thanks for reaching out, @stratdev3!

The issue seems unrelated to running inside a container but Docker talking to the Podman socket.

`DOCKER_HOST=unix:///$XDG_RUNTIME_DIR/podman/podman.sock docker login` fails with the same error, so there's something wrong in the compat REST API.

**Comment by cristianrgreco** [comment]
I see this PR just been merged, thanks! 🚀 Is there any ETA for when this would be released? 🙂

**Comment by vrothberg** [comment]
@ashley-cui @mheon are there plans for another patch release?

**Comment by stratdev3** [comment]
thanks for patch

**Comment by vrothberg** [comment]
Thanks, @cristianrgreco!

@mheon this fix here sounds important.  It's somehow surprising it didn't blow up before.  It would require some backports in c/common.

**Comment by cristianrgreco** [comment]
Could this issue also be the reason why `IndexServerAddress` is empty when calling "/info"?

**Comment by vrothberg** [comment]
> Could this issue also be the reason why `IndexServerAddress` is empty when calling "/info", or should I raise a new issue?

Please open a new issue. Thank you!
