### ISSUE TITLE
Request for modification to podman-restart service to support restart=unless-stopped in addition to restart=always

### ISSUE THREAD

**Issue by n3gwg** [containers/podman#17580]
### Feature request description

There is no discounting the value of the podman-restart service in pursuance of effectuating a proper restart of containers subsequent to a reboot which have the "restart=always" condition set. However, there are times when it is desirous of always having a container restart on reboot but only restart (in a functioning environment) on unless-stopped. Adding the option for having podman-restart work in this condition would offer great utility.

The most flexible instantiation of such a modification (limited to being just based on restart=whatever) would allow the configuration of any of the three possible cases by the person configuring podman-restart.

1) Function when restart=always
2) Function when restart=unless-stopped
3) Function when restart=always or restart=unless-stopped

By the way, the ultimate modification would be for podman-restart to be able to restart a container based on any set of criteria that could be ascertained via "podman inspect". Why not?

Stuart, N3GWG

**Comment by rhatdan** [comment]
@mheon @vrothberg WDYT?

**Comment by mheon** [comment]
We already support a `unless-stopped` restart policy, but I recall that it was implemented before `podman-restart.service` and as such was not fully functional. What are the issues with is, exactly - does it not restart after reboot at all, or does it always restart after reboot, even when the user manually stopped the container?

**Comment by n3gwg** [comment]
Here is the use case I am encountering:

You boot up Fedora CoreOS (in my case under ProxMox) succeeded by firing up a container with restart=unless-stopped (I do this via portainer). All is good and if the container crashes it restarts automatically.

If you reboot Fedora CoreOS (via say a "sudo reboot") then Fedora CoreOS will stop the container in precedence to rebooting to assure an orderly shutdown. The problem is that upon reboot "unless-stopped is true" (because Fedora CoreOS stopped the container within its process of an orderly shutdown), thus the container does not get restarted.

Now, all I did was a basic systemctl enable --now podman-restart.service to get it functioning and no other configuration thereafter. If there is some configuration required to get podman-restart to also restart things that were stopped when restart=unless-stopped was used to execute the container then I am unaware of how to enunciate a configuration to effectuate that functionality.

Stuart, N3GWG

**Comment by Luap99** [comment]
AFAIK docker does not restart containers with unless-stopped after boot. Their docs states that the container is not started if the docker deamon is restarted. https://docs.docker.com/config/containers/start-containers-automatically/

So I don't think this is something the podman-restart unit should do. If you want this you can always create your own unit for it.

**Comment by n3gwg** [comment]
> AFAIK docker does not restart containers with unless-stopped after boot. Their docs states that the container is not started if the docker deamon is restarted. https://docs.docker.com/config/containers/start-containers-automatically/
> 
> So I don't think this is something the podman-restart unit should do. If you want this you can always create your own unit for it.

You seem to be conflating docker and podman. I am not using docker, I am using podman. Can you disambiguate as to what you mean to say?

**Comment by Luap99** [comment]
A reboot counts as stopped. We try to be docker compatible, and AFAIK docker does not restart the containers after boot. If you want this just use the always policy. unless-stopped is the same as always except that it does not restart after boot.

So I say this is functioning exactly as designed and if we change it there will be zero difference between unless-stopped and always which makes no sense.

**Comment by n3gwg** [comment]
> A reboot counts as stopped. We try to be docker compatible, and AFAIK docker does not restart the containers after boot. If you want this just use the always policy. unless-stopped is the same as always except that it does not restart after boot.

Fair enough.

> So I say this is functioning exactly as designed and if we change it there will be zero difference between unless-stopped and always which makes no sense.

This makes no sense to me. It is my understanding (and do correct me if I am wrong) that if I use restart=unless-stopped and I manually stop a container it will not restart until I restart it. However, if I have restart=always and I stop the container does it not restart anyway? If so, then there is a difference betwixt the two beyond what you state.

Stuart, N3GWG

**Comment by Luap99** [comment]
If you manually stop a container with podman stop it will not be restarted with always. Otherwise it would be impossible to ever stop a container with always policy.
Looking at the doc: https://docs.podman.io/en/latest/markdown/podman-create.1.html#restart-policy
It says they are identical for podman.

**Comment by n3gwg** [comment]
Paul,

Okay, now I understand what you meant, I did not realize that. In that case it makes sense to just use always and I then agree that modification of the podman-restart configuration is of little value. However, it was interesting to learn how it's configuration works now.

Stuart, N3GWG
