### ISSUE TITLE
quadlet doesn't support `--mount` option supported by `podman run` 

### ISSUE THREAD

**Issue by ricardojoaoreis** [containers/podman#17632]
podman version 4.4.1

https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html
https://docs.podman.io/en/latest/markdown/podman-run.1.html#mount-type-type-type-specific-option

**Comment by ygalblum** [comment]
Thanks for reporting this issue.
Yes, Quadlet does not support all the different arguments supported by `podman run`. Having said that, it supports the key [PodmanArgs](https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html#podmanargs) that provided the means to pass any argument that is not directly supported by Quadlet.

**Comment by ricardojoaoreis** [comment]
That's how I got around it, but the UX suffers a bit since you can't define a `mount.volume` unit and then reference it like `Mount=mount.volume:/tmp,type=bind` for example.

**Comment by ygalblum** [comment]
I did not think about this use case. I'll take a look.

**Comment by ricardojoaoreis** [comment]
To be honest my knowledge with podman is quite limited and this probably only applies to to `--mount` with the `type=volume` option and not any of the others, still the option of being able to define a `.volume` unit and reference it on the `.container` unit as is the case for the `Volume` directive seems to make sense, especially since by default the name of the generated volume will have `systemd-` prepended to it.
