### ISSUE TITLE
Podman commands fail with the error "Error: error unmarshalling state for container".

### ISSUE THREAD

**Issue by arata-kokubun** [containers/podman#17634]
### Issue Description

As far as I tried, all podman commands (e.g. podman ps, podman start, podman rm, ...) fail with the following error:

```
Error:` error unmarshalling state for container 5f02d688b8b9859ebab9b2a27ac97d50427e47b95f4cb38ee5ae053b30bfc4c8: libpod.ContainerState.RunDir: ReadString: invalid control character found: 13, error found in #10 byte of ...|"runDir":"/var/run/c|..., bigger context ...|ee5ae053b30bfc4c8/userdata/config.json","runDir":"/var/run/containers/storage/overlay-containers/5f0|...

[error] Command execution failed with an error.
```

Because of this error, I can not run any containers. In addition, `podman rm --force 5f02d688b8b9859ebab9b2a27ac97d50427e47b95f4cb38ee5ae053b30bfc4c8` also fails with the same error and I can not remove the suspecting container `5f02d688b8b9859ebab9b2a27ac97d50427e47b95f4cb38ee5ae053b30bfc4c8`.

I want to know the following points to resolve and prevent this issue.

1. Is there any way to dissolve this error and get to a normal state?
1. What causes the unmarshalling state error?

Thank you for your cooperation.

### Steps to reproduce the issue

1. Install podman and running containers.
2. Restart the server (podman commands return normal output before this step).
3. Execute any podman command(e.g `podman ps`).

Sorry for not providing enough information since the error started to appear suddenly after the server restart.

### Describe the results you received

I got

```
Error: error unmarshalling state for container 5f02d688b8b9859ebab9b2a27ac97d50427e47b95f4cb38ee5ae053b30bfc4c8: libpod.ContainerState.RunDir: ReadString: invalid control character found: 13, error found in #10 byte of ...|"runDir":"/var/run/c|..., bigger context ...|ee5ae053b30bfc4c8/userdata/config.json","runDir":"/var/run/containers/storage/overlay-containers/5f0|...

[error] Command execution failed with an error.
```

### Describe the results you expected

The command result should be outputed. For example, `podman ps` command shows the list of running podman containers.

### podman info output

`podman info` command also gives the same error.

```
Error: error unmarshalling state for container 5f02d688b8b9859ebab9b2a27ac97d50427e47b95f4cb38ee5ae053b30bfc4c8: libpod.ContainerState.RunDir: ReadString: invalid control character found: 13, error found in #10 byte of ...|"runDir":"/var/run/c|..., bigger context ...|ee5ae053b30bfc4c8/userdata/config.json","runDir":"/var/run/containers/storage/overlay-containers/5f0|...

[error] Command execution failed with an error.
```

Instead, the `rpm -qi podman` gives the following package information:

```
Name        : podman
Version     : 3.3.1
Release     : 9.module+el8.5.0+12697+018f24d7
Architecture: x86_64
Install Date: Wed 13 Jul 2022 10:53:18 PM EDT
Group       : Unspecified
Size        : 49984641
License     : ASL 2.0 and GPLv3+
Signature   : RSA/SHA256, Tue 21 Sep 2021 07:35:07 AM EDT, Key ID 199e2f91fd431d51
Source RPM  : podman-3.3.1-9.module+el8.5.0+12697+018f24d7.src.rpm
Build Date  : Tue 21 Sep 2021 04:43:54 AM EDT
Build Host  : x86-038.build.eng.bos.redhat.com
Relocations : (not relocatable)
Packager    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>
Vendor      : Red Hat, Inc.
URL         : https://podman.io/
Summary     : Manage Pods, Containers and Container Images
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

The OS is RHEL 8.4.

The following podman related packages are installed in the system.

```
conmon-2.0.29-1.module+el8.4.0+14908+81312c48.x86_64
containernetworking-plugins-0.9.1-1.module+el8.4.0+14908+81312c48.x86_64
containers-common-1-28.module+el8.6.0+14672+b2f82327.x86_64
podman-catatonit-3.3.1-9.module+el8.5.0+12697+018f24d7.x86_64
runc-1.0.0-74.rc95.module+el8.4.0+14908+81312c48.x86_64
```

### Additional information

A resembling issue was reported, but I got the same error with the recovery command in the tickert `podman rm --force <container id>`.

https://github.com/containers/podman/issues/8618

**Comment by Luap99** [comment]
We do not support older releases on github, I suggest you go through the Red Hat support channels if you need help with RHEL.

Without a reliable reproducer it is impossible for us to check with the latest version. However it sounds like the db is corrupted. The easiest way to fix it is to just remove the podman storage and start from a clean state again.

**Comment by arata-kokubun** [comment]
Thank you for your kind cooperation. I will go through the Red Hat support channels and check if the similar issues are reported.

> The easiest way to fix it is to just remove the podman storage and start from a clean state again.

Could you give me a procedure to remove the podman storage if it's possible? I searched the procedure in the podman document but I could not find it.

**Comment by Luap99** [comment]
Use podman system reset if it still works, otherwise manually rm -rf /var/lib/containers as root or ~/.local/share/containers/ as user.

**Comment by arata-kokubun** [comment]
Thank you for your quick reply. I will try them and report the result.

**Comment by arata-kokubun** [comment]
I could remove the container and uninstall podman with the provided procedure.

Thank you for your kind cooperation and sorry for my late reply.
