### ISSUE TITLE
Why do I need to allow phone home?

### ISSUE THREAD

**Issue by arduino-man** [containers/podman#17645]
### Issue Description

I have a network monitor program to prevent apps from phoning home without my permission.

When I launch Podman, it tries to phone home vie the following 
URL: https://builds.coreos.fedoraproject.org/streams/testing.json
IP Address: 99.86.38.105:443

If I deny this connection Podman just refuses to initialize the podman engine.

I receive the error:
`Error: Get "https://builds.coreos.fedoraproject.org/streams/testing.json": dial tcp 99.86.38.105:443: connect: bad file descriptor`

### Steps to reproduce the issue

Steps to reproduce the issue
1. Launch Podman
2. Deny it from talking to external servers
3. See how you can no longer initialize podman

### Describe the results you received

Impossible to initialize podman without allowing it to talk to external servers

### Describe the results you expected

I expected to be able to launch Podman and initialize its engine without having to allow it to phone home

### podman info output

```yaml
Podman v4.4.2
Mac OS Ventura 13.2.1
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
You didn't provide what podman command you actually run but it looks like you did podman machine init which downloads a VM and it has to get it from somewhere.
There is a `--image-path` option that you can set to specify a local image, see https://docs.podman.io/en/latest/markdown/podman-machine-init.1.html
