### ISSUE TITLE
podman events duplicates events after rotation

### ISSUE THREAD

**Issue by mgjm** [containers/podman#17665]
### Issue Description

When the libpod events file gets rotated in [libpod/events/logfile.go](https://github.com/containers/podman/blob/main/libpod/events/logfile.go#L165-L188), the log file gets truncated by discarding the older half of all events.

But the `podman events` command reads all events again after a log rotation has occurred.

Therefore, the newer half of the logs (which is not discarded) is printed again.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Set `events_logfile_max_size = "4k"` in the `[engine]` section in the `containers.conf` file
2. Watch the events with `podman events`
3. In another terminal: Generate some events (e.g. `podman run --rm hello-world`)

### Describe the results you received

After the second or third `podman run` invocation, the file gets rotated and some events, which have already been printed, get printed again.

### Describe the results you expected

Each event should be printed exactly once. Even after rotating the events file.

### podman info output

```yaml
podman version 4.3.1, alpine 3.17, x86_64
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

**Comment by Luap99** [comment]
@vrothberg PTAL

**Comment by vrothberg** [comment]
I started working on it and found a solution.  Writing tests at this moment.

**Comment by mgjm** [comment]
@vrothberg Awesome, I know it's still a WIP, but just a heads up: the inode number doesn't have to change, if the file isn't renamed, there's `os.Create` as a fallback, so it just truncates the existing file.

**Comment by vrothberg** [comment]
Rename logic can be found here https://github.com/containers/podman/blob/main/libpod/events/logfile.go#L239

**Comment by mgjm** [comment]
That's the normal operation, but if the temp file is created in a different file system there is a fallback to use `os.Create`:
[libpod/events/logfile.go#L329-L353](https://github.com/vrothberg/libpod/blob/5e8c89fabca14defda0dfdedb64c2aaf0e364ee7/libpod/events/logfile.go#L329-L353)

**Comment by vrothberg** [comment]
Nice catch, thank you!  Note that I will be largely out of office next; just in case you wonder about the progress.
