### ISSUE TITLE
Using an image-volume throws "invalid argument" error

### ISSUE THREAD

**Issue by cevich** [containers/podman#17685]
### Issue Description

Based on the `podman-volume` man page, the intended usage of the `image` volume-driver is: 

    The image driver uses an image as the backing store of for the volume.  An overlay 
    filesystem will be created, which allows  changes to  the volume to be committed as a new 
    layer on top of the image.

However, using this volume in a container results in an ugly error message.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman volume create --driver image --opt image=<any local image> imagevol`
2. `podman run -it --rm -v imagevol:/dir alpine:latest`

### Describe the results you received

ERRO[0001] Unmounting /home/cevich/.local/share/containers/storage/overlay/d9c...035/merged: invalid argument
Error: mounting volume imagevol for container 62b...083: mounting volume imagevol image failed: creating overlay mount to /home/cevich/.local/share/containers/storage/overlay/d9c...035/merged, mount_data="lowerdir=/home/cevich/.local/share/containers/storage/overlay/l/DVD...2XR:/home/cevich/.local/share/containers/storage/overlay/l/PKQ...SND:/home/cevich/.local/share/containers/storage/overlay/l/TWV...KER,upperdir=/home/cevich/.local/share/containers/storage/overlay/d9c...035/diff,workdir=/home/cevich/.local/share/containers/storage/overlay/d9c...035/work,,userxattr,context=\"system_u:object_r:container_file_t:s0:s0:c225,c633\"": invalid argument

### Describe the results you expected

The podman run command should function, or A more user-friendly error message displayed.

### podman info output

```yaml
podman-4.4.1-3.fc37.x86_64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

If this is not the intended way to use an image-driver volume, that text would be useful as an example in the volume-create man page.

**Comment by cevich** [comment]
Update: It seems even trying to "mount" an image-driver volume fails in a similar way.  i.e.:

`podman unshare podman volume mount imagevol`

**Comment by rlanting** [comment]
This works for me on Debian testing with podman `4.3.1`. Possibly because I don't have SELinux.

**Comment by rhatdan** [comment]
This looks like a bug in how we are creating volume mounts.  It looks like we are mounting as if they were a container and then we mount the image in to the second container with a different MCS label.

**Comment by rhatdan** [comment]
@cevich still having this problem?
