### ISSUE TITLE
'podman system reset' won´'t work if podman state is weird

### ISSUE THREAD

**Issue by Alveel** [containers/podman#17730]
### Issue Description

When trying to setup rootless containers, I ran into the issue where I configured storage paths in `~/.config/containers/storage.conf`, yet podman would refuse to work.

User errors aside, when I did set up the configuration correctly, I was unable to reset the state with `podman system reset`; I just kept getting `Error: mkdir /run/containers: permission denied`

The `--debug` parameter added no information whatsoever (literally.)

Eventually a user on IRC pointed me at `--log-level trace`. Running `podman system reset --log-level trace` gave me the following:

`DEBU[0000] Overriding run root "/run/user/1000/containers/storage" with "/run/containers/storage" from database`

After manually deleting `.local/share/containers/storage/libpod/bolt_state.db` the command worked, and podman started functioning properly.

### Steps to reproduce the issue

1. Configure storage.conf with a directory where you don't have permissions
2. Fruitlessly try to use podman
3. Change the path in storage.conf
4. Try to reset podman with `podman system reset`
5. Notice the system still doesn't work

### Describe the results you received

Insufficiently informative error messages

### Describe the results you expected

I expected `podman system reset` to function even with a borked state, to "unbork" it.

### podman info output

<details><summary>Open Sesame</summary>

<p>

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.7-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: f633919178f6c8ee4fb41b848a056ec33f8d707d'
  cpuUtilization:
    idlePercent: 90.75
    systemPercent: 2.04
    userPercent: 7.21
  cpus: 8
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: potatobee
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.2.2-zen1-1-zen
  linkmode: dynamic
  logDriver: journald
  memFree: 1582710784
  memTotal: 16421769216
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.8.1-1
    path: /usr/bin/crun
    version: |-
      crun version 1.8.1
      commit: f8a096be060b22ccd3d5f3ebe44108517fbf6c30
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.2.0-1
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 4292055040
  swapTotal: 4294963200
  uptime: 1h 18m 29.00s (Approximately 0.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/alwyn/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /home/alwyn/.local/share/containers/storage
  graphRootAllocated: 404181291008
  graphRootUsed: 290112475136
  graphStatus:
    Build Version: Btrfs v6.1.3
    Library Version: "102"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers/storage
  transientStore: false
  volumePath: /home/alwyn/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.2
  Built: 1677255177
  BuiltTime: Fri Feb 24 17:12:57 2023
  GitCommit: 74afe26887f814d1c39925a1624851ef3590e79c-dirty
  GoVersion: go1.20.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.2
```

</p>
</details>

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

ArchLinux, followed [this guide](https://wiki.archlinux.org/title/Podman) for setting up rootless podman.

### Additional information

Relevant configuration setting is `runroot` under the primary `[storage]` section of `~/.config/containers/storage.conf`.

**Comment by giuseppe** [comment]
I think that is the expected error, your database was pointing to the wrong directory, probably you were copying these files from another user.

**Comment by giuseppe** [comment]
so you get the same error even if  `/home/alwyn/.local/share/containers/storage` is empty?

In that case, could you please attach the log you get from `podman --log-level debug system reset`?

**Comment by giuseppe** [comment]
got no reply to my previous question. Closing the issue
