### ISSUE TITLE
HV_ERROR while initializing podman machine

### ISSUE THREAD

**Issue by CDFN** [containers/podman#17745]
### Issue Description

Whenever I try to initialize a new podman machine on my OS, I'm getting such output:
```
Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Error: HV_ERROR
```
The thing is that qemu itself works, I built it from [containers/podman-machine-qemu](https://github.com/containers/podman-machine-qemu). I'm able to run alpine image using it using command from `podman-machine-qemu` README.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Build https://github.com/containers/podman-machine-qemu and add `bin` directory with fresh build of qemu to PATH
2. Try to initialize podman machine
3. We can see HV_ERROR is returned

### Describe the results you received

HV_ERROR is returned

### Describe the results you expected

Podman machine is getting created

### podman info output

```yaml
Error: failed to connect: dial tcp [::1]:49607: connect: connection refused
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

MacOS based on officially not supported by Apple hardware

### Additional information

Hackintosh based on Ryzen CPU. Specs:

```
OS: macOS 13.2.1 22D68 x86_64
Kernel: 22.3.0
CPU: AMD Ryzen 5 3600
GPU: AMD Radeon RX 480
Podman Version: 4.4.2
```

Thing worth noting is that I'm able to run any other virtual image via `qemu-system-x86_64`, so it seems that podman is forcing some setting using Apple HV which is not supported on Ryzen hackintoshes?

**Comment by CDFN** [comment]
Okay, I did some digging and that's what I found:
https://github.com/containers/podman/blob/25f976e276cc102484a034e6539ba3bc91dd11ec/pkg/machine/qemu/options_darwin_amd64.go#L8
This line makes podman try `hvf` accelerator and if unavailable, fall back to `tcg`. AMD Hackintoshes are known for Apple Hypervisor not supporting them. `hvf` is shortcut for hypervisor framework which basically uses Apple Hypervisor. That's why HV_ERROR is thrown. Simple fix is to use tcg accel as it works just fine on amd-based hackintoshes. However, I don't think that change is suitable for official distribution of podman as it's likely to cause performance issues for people using supported hardware.

**Comment by CDFN** [comment]
![image](https://user-images.githubusercontent.com/41289688/224554991-1797bf86-b417-4e6f-b768-4ddcee8a08bc.png)
Managed to run podman on Ryzen Hackintosh. If someone would like to achieve the same, only change I made is this:
```diff
diff --git a/pkg/machine/qemu/options_darwin_amd64.go b/pkg/machine/qemu/options_darwin_amd64.go
index ff8d10db1..dbdf06647 100644
--- a/pkg/machine/qemu/options_darwin_amd64.go
+++ b/pkg/machine/qemu/options_darwin_amd64.go
@@ -5,7 +5,7 @@ var (
 )

 func (v *MachineVM) addArchOptions() []string {
-       opts := []string{"-machine", "q35,accel=hvf:tcg", "-cpu", "host"}
+       opts := []string{"-machine", "q35,accel=tcg"}
        return opts
 }
 ```
Then all you have to do is follow `build_osx.md` and you should be good to go. Also, note on `-cpu host`: this is supported only in kvm or hvf acceleration so CPU model detection won't be available inside podman machine.

**Comment by dgdosen** [comment]
I tried this - but ran into an issue where podman can't find `gvproxy`.  I followed `build_osx.md` - but no luck... 

Any thoughts?

**Comment by CDFN** [comment]
You need to download [gvproxy](https://github.com/containers/gvisor-tap-vsock) and put it in PATH.
