### ISSUE TITLE
incorrect vm image names when using --image-path

### ISSUE THREAD

**Issue by baude** [containers/podman#17784]
### Issue Description

When you use --image-path, podman copies that file into ~/.local/share/... but when doing so does not prefix the file name with the vm so you end up with two vms trying to use the same image; moreover, the second vm created overwrites (i think?) the existing image.

```
$ podman machine init --image-path ~/fedora-coreos-37.20230205.2.0-qemu.x86_64.qcow2.xz
Image resized.
Machine init complete
To start your machine run:

        podman machine start

$ podman machine init --image-path ~/fedora-coreos-37.20230205.2.0-qemu.x86_64.qcow2.xz foobar
Image resized.
Machine init complete
To start your machine run:

        podman machine start foobar

$ podman machine rm

The following files will be deleted:

/home/redacted/.ssh/podman-machine-default
/home/redacted/.ssh/podman-machine-default.pub
/home/redacted/.config/containers/podman/machine/qemu/podman-machine-default.ign
/home/redacted/.local/share/containers/podman/machine/qemu/fedora-coreos-37.20230205.2.0-qemu.x86_64.qcow2.xz
/home/redacted/.local/share/containers/podman/machine/podman-machine-default/podman.sock
/home/redacted/.config/containers/podman/machine/qemu/podman-machine-default.json


Are you sure you want to continue? [y/N] n
$ podman machine rm foobar

The following files will be deleted:

/home/redacted/.ssh/foobar
/home/redacted/.ssh/foobar.pub
/home/redacted/.config/containers/podman/machine/qemu/foobar.ign
/home/redacted/.local/share/containers/podman/machine/qemu/fedora-coreos-37.20230205.2.0-qemu.x86_64.qcow2.xz
/home/redacted/.local/share/containers/podman/machine/foobar/podman.sock
/home/redacted/.config/containers/podman/machine/qemu/foobar.json


Are you sure you want to continue? [y/N] n
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. provided above

### Describe the results you received

provided above

### Describe the results you expected

see above

### podman info output

```yaml
main
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by BlackHole1** [comment]
Is there any progress? 👀

**Comment by BlackHole1** [comment]
Hey @baude 👋. Is there any progress? 👀
