### ISSUE TITLE
Inspecting a container's exposed ports returns an empty `HostIp`

### ISSUE THREAD

**Issue by cristianrgreco** [containers/podman#17780]
### Issue Description

I am creating a container with exposed ports. To find the container ports, I inspect the started container. I would expect a list where the host IPs represent IPv4/IPv6 bindings, for example Docker returns:

```json
[
  { "HostIp": "0.0.0.0", "HostPort": "50000" },
  { "HostIp": "::1", "HostPort": "50000" },
]
```

Note that the HostPort doesn't always match.

From this I can pick the appropriate port depending on IPv4/6 preference. However instead of returning such a list, Podman in the same case is returning:

```json
[
  { "HostIp": "", "HostPort": "50000" },
]
```

I do not know what is the status of Podman IPv6 support, regardless I guess the `HostIP` should be either `0.0.0.0` or `::1`?

### Steps to reproduce the issue

1. Create a container with exposed ports.
2. Inspect the container.
3. Observe that the HostIp is an empty string.

### Describe the results you received

`{ "HostIp": "", "HostPort": "50000" }`

### Describe the results you expected

`{ "HostIp": "<something>", "HostPort": "50000" }`

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2:2.1.7-0debian9999+obs15.6_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 87.46
    systemPercent: 5.69
    userPercent: 6.84
  cpus: 2
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: fv-az646-90
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 123
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.15.0-1034-azure
  linkmode: dynamic
  logDriver: journald
  memFree: 4857856000
  memTotal: 7281278976
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun_101:1.8.1-0debian9999+obs52.3_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.1
      commit: f8a096be060b22ccd3d5f3ebe44108517fbf6c30
      rundir: /run/user/1001/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.0.1-2_amd64
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 0h 4m 56.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/runner/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/runner/.local/share/containers/storage
  graphRootAllocated: 89297309696
  graphRootUsed: 58336636928
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1001/containers
  transientStore: false
  volumePath: /home/runner/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.2
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.19.6
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.2
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

`DOCKER_HOST=unix:///run/user/$(id -u)/podman/podman.sock`

**Comment by cristianrgreco** [comment]
Hi @Luap99, this is how we're configuring the ports when creating the container:

```
{ [exposedPort] = [{ HostPort: "0" }] };
```

We do this to get a dynamically assigned host port

**Comment by rhatdan** [comment]
@Luap99 any follow up on this?

**Comment by Luap99** [comment]
showing both `::1` and `0.0.0.0` simply makes no sense to me, that totally contradicts each other so I don't know what docker is doing with that.

One can either bind dual stack (no host ip which binds every host address), only ipv4 (0.0.0.0 which means all ipv4 addresses) or only ipv6 (:: which means all ipv6 addresses).
So one can either show a single port with no hostip like we do currently, or two port mapping with a host ip of `0.0.0.0` and `::`

Since you do not request a host ip I do not see where the `::1` ipv6 localhost address comes from and why you would expect that one.

**Comment by Luap99** [comment]
I think that was changed in podman 5.0
