### ISSUE TITLE
podman machine init apparently ignores ignition file completely

### ISSUE THREAD

**Issue by MartinSoto** [containers/podman#17805]
### Issue Description

The `--ignition-path` option to `podman machine init` seems to have no effect at all at least in Windows WSL2 where I'm testing now. The option is accepted by the command but it seems to completely ignore the provided file.

### Steps to reproduce the issue

I created an ignition file using butane and am trying to initialize a Windows WSL2 podman machine based on it, using the following command:

    podman machine init --ignition-path=D:\Podman\podman.ign

The command actually initializes the machine, but the ignition file will be completely ignored. This is the output I get

```
PS D:\Podman> podman machine init --ignition-path=D:\Podman\podman.ign
Extracting compressed file
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
Configuring system...
Generating public/private ed25519 key pair.
Your identification has been saved in podman-machine-default
Your public key has been saved in podman-machine-default.pub
The key fingerprint is:
SHA256:AZYb40CzZUeAFbk/I66wn61C7pzELW9HkJ3lpIYwf/I root@GGDE-014018
The key's randomart image is:
+--[ED25519 256]--+
|   .ooO*o        |
|  o o*=oo        |
|   +.* @.        |
|    * X ..       |
|     * .S        |
| ...  E +        |
| o= .o . o       |
| oo*.oo          |
| .=+*+.          |
+----[SHA256]-----+
Machine init complete
To start your machine run:

        podman machine start
```

As can be seen, contrary to what the documentation says, the command creates a SSH key while, on the other hand, the effects of the ignition file (adding  certificate authorities) are not to be seen in the machine. Furthermore, I can specify any file path, existing or not, to the `--ignition-path` option and the command runs just the same. Nothing happens either if I specify a path to a file that is clearly not an ignition file.

Does this feature work at all in Windows?

### Describe the results you received

See above.

### Describe the results you expected

The ignition file being used to create the machine as described by the documentation.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.5-1.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 99.7
    systemPercent: 0.08
    userPercent: 0.23
  cpus: 10
  distribution:
    distribution: fedora
    variant: container
    version: "36"
  eventLogger: journald
  hostname: GGDE-014018
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.102.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 4467585024
  memTotal: 12549988352
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.1-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.1
      commit: f8a096be060b22ccd3d5f3ebe44108517fbf6c30
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 3220951040
  swapTotal: 3221225472
  uptime: 46h 20m 42.00s (Approximately 1.92 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 269490393088
  graphRootUsed: 535412736
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.1
  Built: 1676629882
  BuiltTime: Fri Feb 17 11:31:22 2023
  GitCommit: ""
  GoVersion: go1.18.10
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by baude** [comment]
@n1hility perhaps we could chat about this one?

**Comment by MartinSoto** [comment]
@baude thanks for the information. The time I lost down this blind alley (fortunately not much) won't come back, but it would be good to have this at least documented property.

**Comment by n1hility** [comment]
@baude I'm thinking logging a warning might be the way to go here, alternatively we could hard error?

**Comment by davdr** [comment]
Thank you @MartinSoto for pointing this out, I was just considering to give this a try.

So, alternatively: what would be the "correct" way to set custom certifcate authorities, http/https proxy... at "podman machine init" time, if not via an ignition file?

**Comment by n1hility** [comment]
In the case of proxy settings. These are automatically picked up from system / user env vars as part of podman machine start. For custom CA certs you can either manually install them via podman machine ssh or wsl prompt. Or, alternatively you can create your own custom image and pass it to image path. If you do the latter you can derive from the code for the official podman image here: https://github.com/containers/podman-wsl-fedora
