### ISSUE TITLE
kube play --wait test: looks like a race

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#17803]
```
[+1250s] not ok 536 podman kube play --wait - wait for pod to exit
...
# podman-remote --url unix:/tmp/podman_tmp_2V6q kube play --wait /tmp/play_kube_wait_j4WBda.yaml
Use ctrl+c to clean up or wait for pods to exit
Pod:
993d1e21bffa86e1c259ef3573ac8c8ada8f9ca1543f1e62af8bab308a90013b
Container:
df47ee2ab1c3beea09bdeae68fe10acdcb55fb979c6307c27731591a0804a684

Cleaning up containers, pods, and volumes...
Pods stopped:
993d1e21bffa86e1c259ef3573ac8c8ada8f9ca1543f1e62af8bab308a90013b
Pods removed:
993d1e21bffa86e1c259ef3573ac8c8ada8f9ca1543f1e62af8bab308a90013b
Secrets removed:
Volumes removed:
# podman-remote --url unix:/tmp/podman_tmp_2V6q ps -aq
bc8ea17032f9
#/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#|     FAIL: There should be no containers
#| expected: '[no output]'
#|   actual: 'bc8ea17032f9'
#\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Seen twice in two days, both in remote f37 aarch64 root:
* [first](https://api.cirrus-ci.com/v1/artifact/task/4801092333076480/html/sys-remote-fedora-37-aarch64-root-host.log.html#t--00536) and 
* [second (just now)](https://api.cirrus-ci.com/v1/artifact/task/6006758338985984/html/sys-remote-fedora-37-aarch64-root-host.log.html)

**Comment by edsantiago** [comment]
And [yet another one](https://api.cirrus-ci.com/v1/artifact/task/5397665135984640/html/sys-remote-fedora-37-aarch64-root-host.log.html), same environment

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by edsantiago** [comment]
Seen just now, [f37 remote aarch64 root[(https://api.cirrus-ci.com/v1/artifact/task/4919322716405760/html/sys-remote-fedora-37-aarch64-root-host-boltdb.log.html#t--00544), in a PR that I _know_ included main with your fixes. Reopening. Sorry.

**Comment by edsantiago** [comment]
[Another one](https://api.cirrus-ci.com/v1/artifact/task/5680354682470400/html/sys-remote-fedora-37-aarch64-root-host-boltdb.log.html)

**Comment by edsantiago** [comment]
@umohnani8 [here ya go](https://api.cirrus-ci.com/v1/artifact/task/5915485888315392/html/sys-remote-fedora-37-aarch64-root-host-boltdb.log.html#t--00548)
```
#/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#|     FAIL: There should be no containers
#| expected: '[no output]'
#|   actual: 'f82470d9fa1c  localhost/podman-pause:4.5.0-dev-1680701373              5 seconds ago  Removing                c08b9f94612d-service'
                                                                                                    ^^^^^^^^
```

**Comment by vrothberg** [comment]
At the same time it suggests that `maybeRemoveServiceContainer()` isn't firing/completing before `podman kube play --wait` exits?

**Comment by vrothberg** [comment]
It doesn't fully add up as the journal show that the service container gets removed right after the pod:

>Apr 05 14:24:46 ip-172-31-27-121.ec2.internal podman[3426]: 2023-04-05 14:24:46.066877723 +0000 UTC m=+1253.922675591 pod remove 5112163e3ccc8c1185ff9461035d7ad2eaa92e3b3aab1877d1accc61856d0bc4 (image=, name=test_pod)
Apr 05 14:24:46 ip-172-31-27-121.ec2.internal podman[3426]: 2023-04-05 14:24:46.124330123 +0000 UTC m=+1253.980127991 container remove f82470d9fa1c1fc5b5a5fa0593d3f3e4069037445fdf846f1c70c225c959770b (image=localhost/podman-pause:4.5.0-dev-1680701373, name=c08b9f94612d-service)

**Comment by vrothberg** [comment]
So the suggested fix in https://github.com/containers/podman/issues/17803#issuecomment-1499200051 will address the issue but it looks like there's more to it.  I will continue to investigate tomorrow morning.

**Comment by vrothberg** [comment]
I had another look and could not find anything else than the upper issue.  The extra removal of the service container in `KubeDown` was only added to give the guarantee of it being gone on return of the REST endpoint.  The service container gets usually removed in the worker queue which will be emptied before Podman exits.
