### ISSUE TITLE
kube play --wait with siginterrupt: takes too long to clean up

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#17820]
```
[+1232s] not ok 535 podman kube play --wait with siginterrupt
...
# podman-remote --url unix:/tmp/podman_tmp_pdvk kube play --wait /tmp/play_kube_wait_0vEOj6.yaml
Use ctrl+c to clean up or wait for pods to exit
...
timeout: sending signal TERM to command ?/var/tmp/go/src/github.com/containers/podman/bin/podman-remote?
Cleaning up containers, pods, and volumes...
...
timeout: sending signal KILL to command ?/var/tmp/go/src/github.com/containers/podman/bin/podman-remote?
```
Probable cause: cleanup is taking too long, and `timeout` is going nuclear with SIGKILL. One way to work around this might be to (globally) add `--kill-after=30` to `run_podman()`, but this would of course impact all tests. I'd prefer to see a fix that involves faster cleanup.

### [sys] podman kube play --wait with siginterrupt
* fedora-37-aarch64 : sys remote fedora-37-aarch64 root host [remote]
  * PR #17770
    * [03-14 06:16](https://api.cirrus-ci.com/v1/artifact/task/6463275060166656/html/sys-remote-fedora-37-aarch64-root-host.log.html#t--00535)
  * PR #17735
    * [03-15 16:36](https://api.cirrus-ci.com/v1/artifact/task/5529271792304128/html/sys-remote-fedora-37-aarch64-root-host.log.html#t--00539)
  * PR #17725
    * [03-09 10:03](https://api.cirrus-ci.com/v1/artifact/task/5161706276519936/html/sys-remote-fedora-37-aarch64-root-host.log.html#t--00533)

**Comment by vrothberg** [comment]
@umohnani8 PTAL

**Comment by umohnani8** [comment]
Should be fixed by https://github.com/containers/podman/pull/18086
