### ISSUE TITLE
Settings or flags to start pods without auto start their containers

### ISSUE THREAD

**Issue by webarchymeta** [containers/podman#17824]
### Feature request description

We are building an infrastructure that, besides other functions, also controls the startup/shutdown of pods and the containers withing. However it seems that in a default setting, a container within a pod starts up whenever the pods get started automatically and there is no obvious way of stop such a behavior.

Is there any way to control such a behavior? If not, here is the feature request:

Having a flag to start/create a pod that does not auto starts its containers (besides the infra one)

### Additional context

By the way, I was working on a Debian 11 box. The official version of podman on it is 3.0x now

**Comment by Luap99** [comment]
Just start the specific container then? `podman start xxx-infra` should be enough.

**Comment by rhatdan** [comment]
You want to create a Pod with containers that are not running at start?  That is a new behaviour?  Could you just add and remove the containers from the Pod when you want them to start and stop?

**Comment by webarchymeta** [comment]
@Luap99 
> Just start the specific container then? `podman start xxx-infra` should be enough.
That's a way to go, a little hacky though since it does not hide the implementation details from a user ...

**Comment by webarchymeta** [comment]
@rhatdan 
> You want to create a Pod with containers that are not running at start? That is a new behaviour? Could you just add and remove the containers from the Pod when you want them to start and stop?

It sound like a bit heavy operation (at least on surface). It's better to do it at the configuration level, I think ...

**Comment by Luap99** [comment]
I think just starting the container is the best if you really need this.
I am not understanding your use case, why do only want to start the infra?  It is really not required to ever start the infra container manually, podman will automatically start it when a container form the pod is started.

**Comment by webarchymeta** [comment]
We are building a networking oriented infra-structure for virtualization mixed environments, including podman, proxmox, etc.

It has its own event based async scheduler to start inter dependent containers and virtual machines, it need a finer grained control over startup, shutdown and life-cycle management of containers and vms. For example, we would like to startup a pod and wait for the network to be ready (e,g. fetching ip addresses from dhcp server, etc), which could take minutes for a complex networking environment, before starting up any container within. This kind of staged startup is especially useful for short lived containers, those that run a specific task and hand over the results over pre-established network and then exist ...

Therefor a formal approach to startup is desired, namely treating the pod as a virtual machine and containers within as programs ..

Your suggestion works (we are using this approach now), but not ideal in our opinion since our automated system would depend on your implementation details, which could has extra risk if your implementation changes in the future ...
