### ISSUE TITLE
how to use oom-kill-disable

### ISSUE THREAD

**Issue by DspringL** [containers/podman#17848]
### Feature request description

when run comtainer use oom-kill-disable=true then error：
Error: OCI runtime error: crun: cannot disable OOM killer with cgroupv2

**Comment by giuseppe** [comment]
`--oom-kill-disable` was mapped to writing 1 to the `memory.oom_control` file on cgroup v1, that is not possible anymore on cgroup v2.

What you can do to achieve a similar result is to specify `--oom-score-adj -1000`
