### ISSUE TITLE
'keep-groups' gets lost with a su/sudo within the container

### ISSUE THREAD

**Issue by ckastner** [containers/podman#17852]
### Issue Description

When launching a container with a bind-mounted file to which the user only has group access on the host, `--group-add keep-groups` enables access to the file from within the container, as expected.

However, when using `su/sudo` in the container, even from root->root, access to the file is suddenly denied with EPERM, suggesting that `keep-groups` lost its effect during the process.

This was discovered when passing a `--device`, but can be reproduced with `--volume` as well, as shown below.

_(It may seem pointless to use su root->root in a container, but I'm told there are reasons for this involving PAM/logind sessions within a larger test automation framework.)_

### Steps to reproduce the issue

On the host, pick an arbitrary secondary group of the user. In this example, I'll use group `video`.

On the host, create a file with `root:video` ownership, and no read permissions for other:
```shell
$ echo "eureka" > /tmp/canary && chmod 640 /tmp/canary && sudo chown root:video /tmp/canary
$ ls -l /tmp/canary 
-rw-r----- 1 root video 6 Mar 19 10:28 /tmp/canary
```

Run a container, bind-mounting the file
```shell
podman run --rm -it --volume=/tmp/canary:/tmp/canary --group-add keep-groups debian:unstable
```

Within the container, regular access to the file works:
```
root@2925ce478c61:/# cat /tmp/canary
eureka
```
But no longer after `su`, even when remaining root:
```
root@2925ce478c61:/# su
root@2925ce478c61:/# cat /tmp/canary
cat: /tmp/canary: Permission denied
```

It's the same with fedora:latest, although `util-linux` must be installed for `/usr/bin/su`.

### Describe the results you received

After the `su`, the file can no longer be accessed.

### Describe the results you expected

When using `su` to root, `keep-groups` should remain in effect. It seems odd that this operation would result in fewer privileges.

Someone else checked this for me on a system with docker, and the issue is not reproducible there. Incidentally, the issue is also not reproducible with podman in root mode.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2.1.6+ds1-1_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.6, commit: unknown'
  cpuUtilization:
    idlePercent: 99.96
    systemPercent: 0.02
    userPercent: 0.02
  cpus: 6
  distribution:
    codename: bookworm
    distribution: debian
    version: "12"
  eventLogger: journald
  hostname: rocm
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.1.0-6-amd64
  linkmode: dynamic
  logDriver: journald
  memFree: 32628101120
  memTotal: 33567768576
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun_1.8.1-1_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.1
      commit: f8a096be060b22ccd3d5f3ebe44108517fbf6c30
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.2.0-1_amd64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 0
  swapTotal: 0
  uptime: 9h 57m 56.00s (Approximately 0.38 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  docker.io:
    Blocked: false
    Insecure: false
    Location: docker.io
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: docker.io
    PullFromMirror: ""
  search:
  - docker.io
store:
  configFile: /home/christian/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/christian/.local/share/containers/storage
  graphRootAllocated: 97825230848
  graphRootUsed: 25474990080
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /home/christian/tmp
  imageStore:
    number: 20
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/christian/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.19.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Host OS is Debian 'sid'.

**Comment by mheon** [comment]
I'm fairly certain this is just the normal behavior of `su`. When run outside a container, if I `su root`, I lose the groups my user has and gain access to the `root` group.

**Comment by mheon** [comment]
I also suspect there's no fix here while retaining `su` - it's likely dropping the groups is deliberate, and there's no easy way to readd them given the container doesn't normally have access to them.

**Comment by ckastner** [comment]
> I'm fairly certain this is just the normal behavior of `su`. When run outside a container, if I `su root`, I lose the groups my user has and gain access to the `root` group.

True, but root accessing a file this way (outside of the container) doesn't get EPERM. The very same `cat /tmp/canary` test can be run outside of a container, and it is successful with and without su.

With root invoking `su`, the `-g` and `-G` options  could be used to specify primary and secondary groups, but these have no effect within the container.

It seems inconsistent that the user invoking podman can access the file on the host (via group membership, see steps to reproduce), and can do so in the container as root, but can no longer do so after su-to-root. My naive assumption would have been that if the process has access on the host (via `keep-groups`), then root should have access in the container, regardless of how root was obtained.

**Comment by rhatdan** [comment]
Are you sure this is not something else blocking access like SELinux?

**Comment by Luap99** [comment]
I think this is expected, the groups are not mapped into the user namespace. You only have access to your won uid and gid plus the ones defined in /etc/sub{u,g}id. They way keep-groups works is by skipping the setgroups call, https://github.com/containers/crun/blob/main/crun.1.md#runocikeep_original_groups1

Once you call su it will do its own setgroups call and thus removes all your current groups. There is no way to regain access to the gid because it is not mapped in the user namesapce.

```
podman run --rm --group-add keep-groups -it alpine 
/ # id
uid=0(root) gid=0(root) groups=65534(nobody),0(root)
/ # su
/ # id
uid=0(root) gid=0(root) groups=0(root),0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
/ #
```

cc @giuseppe to confirm

**Comment by giuseppe** [comment]
yes, this is expected.  If you do a sudo then you override the groups.

Once you are in a new user namespace you can use only the groups that are mapped there.  There is no way to retain the old groups after a `setgroups`.

If you really want to achieve that, then you need to add these groups to `/etc/subgid` for the user and let the user handle them as any other additional gid, without the `keep-groups` injection.

**Comment by ckastner** [comment]
Just do document the solution, in case anyone else stumbles over this: in the end, all that was needed was (1) to map the respective groups in `/etc/subgid` as suggested, and (2) to call podman with the appropriate `--gidmap` of which a few are needed.

`/etc/subgid` was extended by adding one line per desired GID:

```
username:GID1:1
username:GID2:1
username:100000:65536
```

The trickier part was figuring out which `--gidmap` to use. As per `podman-run(1)`, in rootless mode, there are two mappings, one from `/etc/subgid` to intermediate ID, and then from intermediate ID to container ID.

This is where I stumbled, for two reasons:

1. For the intermediate mapping, order of entries in `/etc/subgid` was not relevant on my system; they were ordered by subordinate ID instead. So trying to be clever with structuring this file, to achieve a particular intermediate mapping, and so maybe avoiding the need for explicit `--gidmap`, was fruitless.
2. I realized too late that changes to `/etc/subgid` did not take immediate effect, even with user logout/login. I assumed this was a caching thing, as a side effect of being daemonless.

In addition to the implied mapping for the invoking user (say user $GID=1000), the intermediate mapping for 65536 IDs thus looked like follows:

| hostGID         | intermediateGID | range | 
| ---:            | ---:            | ---:  |
|     1000        |               0 |     1 |
|       GID1        |               1 |     1 |
|      GID2       |               2 |     1 |
|   100000-165532 |         3-65535 | 65533 |

What remained was to simply map container IDs to the intermediate IDs using a few `--gidmap`.
