### ISSUE TITLE
Error: creating named volume "~/.aws": running volume create option: names must match [a-zA-Z0-9][a-zA-Z0-9_.-]*

### ISSUE THREAD

**Issue by arindamghoshal** [containers/podman#17850]
### Issue Description

Trying use AWS Glue 4.0 with podman - based on the documentation here - https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-libraries.html#develop-local-docker-image

The following command works perfectly with docker - 
docker run -it -v ~/.aws:/home/glue_user/.aws -e DISABLE_SSL=true --rm -p 4040:4040 -p 18080:18080 --name glue_pyspark amazon/aws-glue-libs:glue_libs_4.0.0_image_01 pyspark

with podman it fails with Error: creating named volume "~/.aws": running volume create option: names must match [a-zA-Z0-9][a-zA-Z0-9_.-]*: invalid argument

podman run -it -v ~/.aws:/home/glue_user/.aws -e DISABLE_SSL=true --rm -p 4040:4040 -p 18080:18080 --name glue_pyspark amazon/aws-glue-libs:glue_libs_4.0.0_image_01 pyspark

if I omit the volume flag it works

podman run -it -e DISABLE_SSL=true --rm -p 4040:4040 -p 18080:18080 --name glue_pyspark amazon/aws-glue-libs:glue_libs_4.0.0_image_01 pyspark

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman machine start
2. podman pull amazon/aws-glue-libs:glue_libs_4.0.0_image_01
3. podman run --log-level=debug -it -v ~/.aws:/home/glue_user/.aws -e DISABLE_SSL=true --rm -p 4040:4040 -p 18080:18080 --name glue_pyspark amazon/aws-glue-libs:glue_libs_4.0.0_image_01 pyspark

### Describe the results you received

time="2023-03-19T18:29:02Z" level=info msg="podman filtering at log level debug"
time="2023-03-19T18:29:02Z" level=debug msg="Called run.PersistentPreRunE(podman run --log-level=debug -it -v ~/.aws:/home/glue_user/.aws -e DISABLE_SSL=true --rm -p 4040:4040 -p 18080:18080 --name glue_pyspark amazon/aws-glue-libs:glue_libs_4.0.0_image_01 pyspark)"
time="2023-03-19T18:29:02Z" level=debug msg="DoRequest Method: GET URI: http://d/v4.4.2/libpod/_ping"
time="2023-03-19T18:29:02Z" level=debug msg="DoRequest Method: GET URI: http://d/v4.4.2/libpod/networks/pasta/exists"
time="2023-03-19T18:29:02Z" level=debug msg="Adding port mapping from 4040 to 4040 length 1 protocol \"\""
time="2023-03-19T18:29:02Z" level=debug msg="Adding port mapping from 18080 to 18080 length 1 protocol \"\""
time="2023-03-19T18:29:02Z" level=debug msg="Loading registries configuration \"/etc/containers/registries.conf\""
time="2023-03-19T18:29:02Z" level=debug msg="DoRequest Method: POST URI: http://d/v4.4.2/libpod/images/pull"
time="2023-03-19T18:29:02Z" level=debug msg="User mount ~/.aws:/home/glue_user/.aws options []"
time="2023-03-19T18:29:02Z" level=debug msg="DoRequest Method: GET URI: http://d/v4.4.2/libpod/images/amazon%2Faws-glue-libs:glue_libs_4.0.0_image_01/json"
time="2023-03-19T18:29:02Z" level=debug msg="DoRequest Method: POST URI: http://d/v4.4.2/libpod/containers/create"
Error: creating named volume "~/.aws": running volume create option: names must match [a-zA-Z0-9][a-zA-Z0-9_.-]*: invalid argument
time="2023-03-19T18:29:02Z" level=debug msg="Shutting down engines"

### Describe the results you expected

PySpark prompt

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.5-1.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 95.54
    systemPercent: 2.21
    userPercent: 2.25
  cpus: 8
  distribution:
    distribution: fedora
    variant: container
    version: "36"
  eventLogger: journald
  hostname: Horizon
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.90.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 4233490432
  memTotal: 8243838976
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.1-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.1
      commit: f8a096be060b22ccd3d5f3ebe44108517fbf6c30
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 2144837632
  swapTotal: 2147483648
  uptime: 0h 27m 53.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 13077082112
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.4.1
  Built: 1676629882
  BuiltTime: Fri Feb 17 10:31:22 2023
  GitCommit: ""
  GoVersion: go1.18.10
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.1
```

### Podman in a container

Yes

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Microsoft Windows [Version 10.0.22621.1265]

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rhatdan** [comment]
I can not repeat this failure, are you still seeing it in podman 4.5?

**Comment by christianhorn** [comment]
> podman [..] -v ~/.aws:/home/glue_user/.aws [..]
Can you try with an absolute path? Using a relative path turned out to be causing an apparently similar issue for me.

**Comment by rhatdan** [comment]
Are these with older versions of Podman?  I believe this is fixed in podman 4.5.

**Comment by christianhorn** [comment]
> Are these with older versions of Podman? I believe this is fixed in podman 4.5.

In my case podman 3.0.1+dfsg1-3+deb11u1, latest version in Debian stable.

**Comment by gzcwnk** [comment]
I think I have the same problem, but stating a full path doesnt work for me.

RHEL9 has,

[root@vuwunicosftp002 2222]# podman --version
podman version 4.4.1
[root@vuwunicosftp002 2222]#

=======
[root@vuwunicosftp002 2222]# podman-compose up -d
['podman', '--version', '']
using podman version: 4.4.1
** excluding:  set()
podman volume inspect 2222_-/home/steven2222/upload || podman volume create 2222_-/home/steven2222/upload
['podman', 'volume', 'inspect', '2222_-/home/steven2222/upload']
Error: inspecting object: no such volume 2222_-/home/steven2222/upload
['podman', 'volume', 'create', '--label', 'io.podman.compose.project=2222', '--label', 'com.docker.compose.project=2222', '2222_-/home/steven2222/upload']
Error: running volume create option: names must match [a-zA-Z0-9][a-zA-Z0-9_.-]*: invalid argument
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 295, in assert_volume
    try: out = compose.podman.output([], "volume", ["inspect", vol_name]).decode('utf-8')
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 819, in output
    return subprocess.check_output(cmd_ls)
  File "/usr/lib64/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['podman', 'volume', 'inspect', '2222_-/home/steven2222/upload']' returned non-zero exit status 125.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/podman-compose", line 33, in <module>
    sys.exit(load_entry_point('podman-compose==1.0.3', 'console_scripts', 'podman-compose')())
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 1774, in main
    podman_compose.run()
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 1023, in run
    cmd(self, args)
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 1247, in wrapped
    return func(*args, **kw)
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 1414, in compose_up
    podman_args = container_to_args(compose, cnt, detached=args.detach)
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 643, in container_to_args
    podman_args.extend(get_mount_args(compose, cnt, volume))
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 401, in get_mount_args
    assert_volume(compose, fix_mount_dict(compose, volume, proj_name, srv_name))
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 306, in assert_volume
    compose.podman.output([], "volume", args)
  File "/usr/lib/python3.9/site-packages/podman_compose.py", line 819, in output
    return subprocess.check_output(cmd_ls)
  File "/usr/lib64/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['podman', 'volume', 'create', '--label', 'io.podman.compose.project=2222', '--label', 'com.docker.compose.project=2222', '2222_-/home/steven2222/upload']' returned non-zero exit status 125.
[root@vuwunicosftp002 2222]#

**Comment by rhatdan** [comment]
podman-compose is a different project.
