### ISSUE TITLE
allow to set loglevel for healthcheck

### ISSUE THREAD

**Issue by nolange** [containers/podman#17856]
### Feature request description

Currently our server logs are mostly full of healthcheck output, making them hard to navigate.

### Suggest potential solution

I would want the healthcheck service to run with `LogLevelMax=notice`, this would remove the normal output, inclusive the started/stopped messages from systemd itself.

I believe this should be the default, but there could be an option for `podman run` to override the loglevel for healtchecks.

### Have you considered any alternatives?

Filtering the log, but this is cumbersome.

**Comment by Luap99** [comment]
I have no problem with doing this by default, is there any use case where one might need that journal output? I would like to avoid adding a option for this to podman run. Maybe we could change it based on `--log-level` from podman.

@vrothberg @mheon WDYT?

**Comment by mheon** [comment]
I don't see a problem with this.

**Comment by rhatdan** [comment]
I agree these messages should be dropped down a level so they don't normally show up in the logs.

**Comment by vrothberg** [comment]
SGTM

**Comment by Rudd-O** [comment]
Please do this.  Thanks.  My logs are full of garbage because of this.

**Comment by rhatdan** [comment]
Are you talking specifically about this:
		logrus.Infof("Startup healthcheck for container %s passed, recreating timer", c.ID())

**Comment by rhatdan** [comment]
We could drop this to debug level.

**Comment by mheon** [comment]
The `exec_died` event can probably be removed (it's purely extraneous given this is a healthcheck), but we'll have to retain the `health_status` events for logging healthcheck runs.

**Comment by mheon** [comment]
Yes, we do realize this, but these messages (at least, the `health_status` logs) are an essential part of Podman's event logging system and cannot be removed.

**Comment by vrothberg** [comment]
I think we can make this behavior configurable and suppress events emitted by health checks (but opt-in).

Alternatively, you can use `podman --events-backend=file`.  But the journald/systemd backend integrates much nicer into a modern Linux system.

> it worked painless with docker =(

@nolange can you elaborate on that?  Does Docker not emit the `exec` events etc. for health checks even when the events backend is set to journald?

**Comment by nolange** [comment]
I switched from Docker, so I cant easily test now but one machine still has some service running. No, there arent any log entries from health checks (json file) and I dont see why they should show up in logs (unless the checks fail)?
the state starting/healthy is still shown with `docker ps`

I would expect healthchecks to report the state directly to podman/docker and the container framework then deciding whether to log (ideally: only statechange) or stop/restart the container. I don't understand why the system log seems your internal means of communication, and the health state seemingly depending on it.

**Comment by vrothberg** [comment]
> Yes, we do realize this, but these messages (at least, the `health_status` logs) are an essential part of Podman's event logging system and cannot be removed.

@mheon can you elaborate why you think this cannot be removed?

**Comment by mheon** [comment]
These are effectively debug/audit messages that show admins that healthchecks are, in fact, running - it's an important part of debugging when things start to go wrong - the events show the status of the healthcheck, so when debugging you can check for intermittent failures in a monitored container via `podman events`. We could potentially add an opt-in for disabling HC events, but we absolutely cannot do something like that by default, it'd be very confusing to anyone trying to debug a healthcheck issue.

It looks like we can drop the log level of the systemd timers we create, though, which will eliminate the `systemd[1]` messages. That's a clear win for readability and we don't use those at all internally. Ideally we produce only 1 message per HC, the `health_status` event, which should reduce logging output by 75%.

**Comment by nolange** [comment]
> These are effectively debug/audit messages that show admins that healthchecks are, in fact, running - it's an important part of debugging when things start to go wrong - the events show the status of the healthcheck, so when debugging you can check for intermittent failures in a monitored container via `podman events`.

I wouldn't find errors in the sea of noise currently. If healthchecks are failing or not executed then **that** should be detected somehow.

> We could potentially add an opt-in for disabling HC events, but we absolutely cannot do something like that by default, it'd be very confusing to anyone trying to debug a healthcheck issue.

I don't think debugging healthcheck issues should be the default, I am not sure if some container user should even know they exist. For container author of course there should be options for debugging logs.

**Comment by apollo13** [comment]
We'd also love to get rid of:
```
Sep 25 13:52:50 XXX systemd[1]: Started /usr/bin/podman healthcheck run fd61ed0a66e2f8737abbafe5acf223fd0c3c35e135d8876042db6456681fbaa0.
Sep 25 13:52:50 XXX systemd[1]: fd61ed0a66e2f8737abbafe5acf223fd0c3c35e135d8876042db6456681fbaa0.service: Succeeded.
```
this really clutters our logs :/

**Comment by apollo13** [comment]
Could this be considered for backporting to 4.7? (Assuming another release will be cut for 4.7 at all)

**Comment by rhatdan** [comment]
Sure, although I am not sure we will be cutting another release, 4.8 will be cut in November.

/cherry-pick 4.7

**Comment by mailinglists35** [comment]
running LTS systems means we will have to live with this all the lifetime of EL9 ???

**Comment by mheon** [comment]
9.4 is getting Podman 4.9 which will have this fix

**Comment by vrothberg** [comment]
> running LTS systems means we will have to live with this all the lifetime of EL9 ??? (or disabling the healthcheck altogether)

You can also reach out through the customer channels of your distribution of choice and ask for backports if you desire it before 9.4.

**Comment by Luap99** [comment]
Note this fix is causing a regression (https://github.com/containers/podman/issues/20342), so no backports until the regression is fixed.
