### ISSUE TITLE
sqlite: database is locked

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#17859]
Almost certainly related to #17858 but I will let someone else decide and possibly merge.
```
  Podman start after signal kill
  ...
  podman [options] --db-backend sqlite --storage-driver vfs ps -q
  Error: switching journal to WAL mode: database is locked
```
Unfortunately, this is also happening a lot in `cleanup`, where for long and horrible complicated reasons my flake logger cannot detect:
```
$ podman [options] rm -fa -t 0
Error: adding container id to database: database is locked
```

https://api.cirrus-ci.com/v1/artifact/task/4709781731016704/html/int-podman-fedora-37-rootless-host-sqlite.log.html#t--netns--1

https://api.cirrus-ci.com/v1/artifact/task/6409078293921792/html/int-podman-fedora-37-rootless-host.log.html#t--Podman-start-after-signal-kill--1

**Comment by edsantiago** [comment]
Here's one in `podman run --rm` ([f37 root](https://api.cirrus-ci.com/v1/artifact/task/4624128171311104/html/sys-podman-fedora-37-root-host-sqlite.log.html#t--00241)):
```
# podman run --rm -d --name JRhbDObiOp quay.io/libpod/testimage:20221018 top
Error: adding container id to database: database is locked
```
(there's another one in that same log, with `restart`)

Here's one in [podman-remote](https://api.cirrus-ci.com/v1/artifact/task/6031503054864384/html/sys-remote-fedora-37-root-host-sqlite.log.html#t--00241)

**Comment by vrothberg** [comment]
@mheon @baude FYI

**Comment by vrothberg** [comment]
Opened https://github.com/containers/podman/pull/17867 as an anticipated fix.

**Comment by edsantiago** [comment]
Sorry:
```
Podman start after signal kill
...
# podman [options] run --http-proxy=false --name test1 -d quay.io/libpod/alpine:latest top
# podman [options] ps -q
Error: cannot connect to database: database is locked
```
In [f36 root container](https://api.cirrus-ci.com/v1/artifact/task/6178628367548416/html/int-podman-fedora-36-root-container-sqlite.log.html#t--Podman-start-after-signal-kill--1), and this is in my #17831 PR which includes all sqlite fixes so far as of Monday.

**Comment by edsantiago** [comment]
Another one, [f37 rootless host](https://api.cirrus-ci.com/v1/artifact/task/4972258725199872/html/int-podman-fedora-37-rootless-host-sqlite.log.html#t--podman-restart-running-container--1) (not container).

**Comment by edsantiago** [comment]
Sorry. Seen in my no-flake-retries PR, [f37 rootless](https://api.cirrus-ci.com/v1/artifact/task/6674235951677440/html/int-podman-fedora-37-rootless-host-sqlite.log.html#t--podman-container-restart-running-container--1), the usual symptom (in `podman ps`):
```
$ podman [options] ps -q
Error: checking if DB config table exists: database is locked
```
This version of the CI run **DOES NOT** include the WAL diffs, it's just hammering at sqlite. Reopening, sorry.

**Comment by vrothberg** [comment]
Cc: :ambulance: @mheon
