### ISSUE TITLE
Podman container exits immediately when SELinux is set to enforcing

### ISSUE THREAD

**Issue by aristotelos** [containers/podman#17876]
### Issue Description

With SELinux set to enforcing, any container started with Podman (using a rootless user) exits immediately without any error message.

### Steps to reproduce the issue

Steps to reproduce the issue
1. On Red Hat Enterprise Linux 9.1, set SELinux enforcing
2. Run `podman run -it ubi8 bash` (or any other container like busybox)
3. No logs are output, no errors are written, the container just exits

### Describe the results you received

No logs are output, no errors are written, the container just exits.

### Describe the results you expected

The container should start and open bash.

Alternatively, it should give a helpful error message why the container could not start.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.27.3
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: 56561007b6a59ea175ee9a67384639721499e160'
  cpuUtilization:
    idlePercent: 93.55
    systemPercent: 2.51
    userPercent: 3.93
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "9.1"
  eventLogger: journald
  hostname: vdl-workflow-rhel9-test01
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.0-162.18.1.el9_1.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 2074488832
  memTotal: 3832184832
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.el9_0.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 0h 7m 8.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/ansible/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/ansible/.local/share/containers/storage
  graphRootAllocated: 15017705472
  graphRootUsed: 2749833216
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1001/containers
  volumePath: /home/ansible/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1675767401
  BuiltTime: Tue Feb  7 10:56:41 2023
  GitCommit: ""
  GoVersion: go1.18.9
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Using a RHEL 9.1 VM in vSphere.

### Additional information

`sudo yum --showduplicates list podman` does not include 4.4.2, only 4.2.0, so that is why I haven't tested with 4.4.2.

Note also that `/home/ansible/.config/containers/storage.conf` does not exist, nor does `/home/ansible/.local/share/containers/storage/volumes`. The folder `/home/ansible/.local/share/containers/storage` does exist.

**Comment by rhatdan** [comment]
What AVC messaes are you seeing?

**Comment by rhatdan** [comment]
Does `sudo yum -y reinstall container-selinux` throw an error message.

You might need to downgrade container-selinux.

**Comment by aristotelos** [comment]
The strange thing was that there were also no AVC messages.

Today, I recreated my Red Hat Enterprise Linux 9 VM, and the problem was suddenly solved. I think I have logged this issue incorrectly on version 9.1, that it was 9.0 that I could reproduce it on. It may also be that the fresh install of podman on this new VM solved it (yum install podman). Anyways, I'm closing the issue.
