### ISSUE TITLE
play kube: sdnotify: got MAINPID=104055 (expected =0)

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#17882]
Here's one I've never seen before:
```
not ok 363 sdnotify : play kube - no policies
...
$ podman container inspect test_pod-test 2dfde25de330-service --format {{.Config.SdNotifyMode}}
ignore
ignore
socat log:
MAINPID=104055
READY=1
#/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#|     FAIL: sdnotify sent MAINPID and READY
#| expected: 'MAINPID=0
READY=1'
#|   actual: 'MAINPID=104055'
#|         > 'READY=1'
#\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Only one instance, [f37 rootless](https://api.cirrus-ci.com/v1/artifact/task/6534350947221504/html/sys-podman-fedora-37-rootless-host-boltdb.log.html#t--00363) (boltdb obviously because we do not test sqlite in system tests yet).

**Comment by vrothberg** [comment]
> expected: 'MAINPID=0

I didn't check but this looks like a fart in the test.  How could a MAINPID of 0 be expected?
