### ISSUE TITLE
RFE: Print auth file location when invoking `podman login --get-login --verbose`

### ISSUE THREAD

**Issue by jacksgt** [containers/podman#17885]
### Feature request description

Currently, the `podman login registry.example.com --verbose` already prints out the location of the `container-auth.json` file that was used to store the credentials, like this:
```
$ podman login registry.example.com --username foobar --password hunter2 --verbose
Used:  /run/user/1000/containers/auth.json
Login Succeeded!
```

In addition, it would be useful to have the same behavior for when invoking `podman login registry.example.com --get-login --verbose`.
Why?
Because the `container-auth.json` file can be stored in many different places: `$XDG_RUNTIME_DIR/containers/auth.json` (if the env var is set), `${HOME}/.config/containers/auth.json`, `/run/user/$(id -u)/containers/auth.json`, etc.

It would be useful to know the location so we can pass it to other tools, such as Helm:
```
helm push chart.tgz registry.example.com/my-repo --registry-config $PATH
```

### Suggest potential solution

The following simple addition would be helpful:
```
$ podman login registry.example.com --get-login --verbose
Used: /run/user/1000/containers/auth.json
foobar
```

Then the user can trivially re-use the same file for other tools, e.g.:
```
helm push chart.tgz registry.example.com --registry-config /run/user/1000/containers/auth.json
```

### Have you considered any alternatives?

The only alternative I can see is having to re-authenticate (which may be undesired for other reasons, such as usability):

```sh
$ podman login registry.example.com --username foobar --password hunter2 --verbose
Used:  /run/user/1000/containers/auth.json
Login Succeeded!
# aha, my credentials are stored in /run/user/1000/containers/auth.json ....
```

### Additional context

I believe the necessary functions that need to be changed are here:

* https://github.com/containers/common/blob/28ebcc64cf9af714badd8abd5521ed49545642c0/pkg/auth/auth.go#L87
* https://github.com/containers/image/blob/main/pkg/docker/config/config.go#L260

**Comment by vrothberg** [comment]
Thanks for reaching out, @jacksgt!

The use case makes perfect sense to me.  Are you interested in contributing the feature?

@mtrmac PTAL

**Comment by jacksgt** [comment]
Yes, I can give it a try.

I would also like to mention that the path is actually visible when running in debug mode:

```
podman login --verbose registry.example.com --get-login --log-level=debug
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called login.PersistentPreRunE(podman login --verbose registry.example.com --get-login --log-level=debug) 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /home/jack/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Using graph driver btrfs                     
DEBU[0000] Using graph root /home/jack/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000/containers     
DEBU[0000] Using static dir /home/jack/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /home/jack/.local/share/containers/storage/volumes 
DEBU[0000] Using transient store: false                 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "btrfs" 
DEBU[0000] Initializing event backend journald          
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument 
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Configured OCI runtime youki initialization failed: no valid executable found for OCI runtime youki: invalid argument 
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument 
DEBU[0000] Configured OCI runtime crun-wasm initialization failed: no valid executable found for OCI runtime crun-wasm: invalid argument 
DEBU[0000] Configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument 
DEBU[0000] Configured OCI runtime ocijail initialization failed: no valid executable found for OCI runtime ocijail: invalid argument 
DEBU[0000] Using OCI runtime "/usr/bin/crun"            
INFO[0000] Setting parallel job count to 25             
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf" 
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/00-shortnames.conf" 
DEBU[0000] Found credentials for registry.example.com in credential helper containers-auth.json in file /run/user/1000/containers/auth.json 
example
DEBU[0000] Called login.PersistentPostRunE(podman login --verbose registry.example.com --get-login --log-level=debug) 
DEBU[0000] Shutting down engines     
```

Specifically this line: 

> DEBU[0000] Found credentials for registry.example.com in credential helper containers-auth.json in file /run/user/1000/containers/auth.json

**Comment by mtrmac** [comment]
> It would be useful to know the location so we can pass it to other tools, such as Helm:

This parts seems unviable to me. For starters, we already support credential helpers (and there are long-standing thoughts that we should use session-wide credential helpers by default), and those can be specified in `registries.conf`, not in any `auth.json`-like file that could be passed to an external tool. And in general, we don’t want to commit to never adding any new source of credentials.

So, we could, reasonably enough, we could do something like `podman login --verbose` does, just return a text that is only intended for humans, _explicitly not_ promised to be stable, and _explicitly not_ designed to be an API that can be consumed by software. (And those constraints are not clear from the `podman login` documentation, that might be worth emphasizing.)

Or we could, hypothetically, build an actual long-term API that returns a future-extensible enum… with some specific machine-parseable representation (JSON?)_; but every single caller would _have to_ be prepared to handle future currently-unknown values, making usage of the enum fundamentally an unreliable value to consume. That just seems not worth it to me.

---

I’d meekly suggest that long-term, changing your deployment scripts to be fully automated, with credentials managed as a component of the deployment configuration, and not to relying on session state on any particular _human_ user, might be worthwhile.

**Comment by mtrmac** [comment]
Alternatively, it might make more sense to provide `podman get-registry-credentials`, which finds the correct credential and directly produces an `auth.json`-like file containing _only_ that credential (without referring to credential helpers; and in full form, whether it is user+password or an identity token), allowing to turn users’ local state into that managed deployment configuration (or to provide only that credential to a tool).

**Comment by mtrmac** [comment]
… that would _still_ have some forward-compatibility risk, if we ever added more features / more entirely new kinds of credentials to the `auth.json` format, but I don’t see how that can be entirely eliminated.

**Comment by jacksgt** [comment]
Hi @mtrmac ,
thanks for your comments and consideration. I totally get where you're coming from.

My suggestion was based on the fact that `container-auth.json(5)` is already a de-facto interface since it's even described in a manpage.
Hence I think it makes sense to use this file to interoperate between different OCI clients.

> I’d meekly suggest that long-term, changing your deployment scripts to be fully automated, with credentials managed as a component of the deployment configuration, and not to relying on session state on any particular human user, might be worthwhile.

They are fully automated. Basically the CI is doing this:

```
# USERNAME and PASSWORD are injected securely via environment variables

podman login registry.example.com --username $USERNAME --password $PASSWORD
# do some stuff
podman image build ...
podman image push ...
# do more stuff here
helm package ...
helm push registry.example.com/ ...
# hmm, where did podman puts it's credentials file?
```

I could do this as well:
```
podman login registry.example.com ...
...
helm registry login registry.example.com ...
```
But it seems quite unclean to me that I have to login twice when the both tools are relying on the well-defined [containers-auth.json(5)](https://github.com/containers/image/blob/main/docs/containers-auth.json.5.md).

**Comment by mtrmac** [comment]
> Hi @mtrmac , thanks for your comments and consideration. I totally get where you're coming from.
> 
> My suggestion was based on the fact that `container-auth.json(5)` is already a de-facto interface since it's even described in a manpage.

Well, it’s an interface in the sense that `ls` is an interface: the compatibility promise is one-way. (For `ls`, options that are in the man page now are expected to continue working, but new ones may be added at any time, and replacing `ls` with a different implementation that only implements the old ones might, long-term, break.) All fields documented in `auth.json` are expected to continue working, but new ones may be added at any time, and consuming `auth.json` by a different implementation that only implements the old ones might, long-term, break.

---

> Basically the CI is doing this:
> 
> ```
> # USERNAME and PASSWORD are injected securely via environment variables
> 
> podman login registry.example.com --username $USERNAME --password $PASSWORD
> …
> helm push registry.example.com/ ...
> # hmm, where did podman puts it's credentials file?
> ```

I think the best way to deal with this is:
```
authfile=$(mktemp /somewhere/secure)
# trap, or otherwise arrange for authfile to be deleted
podman login --authfile $authfile …
helm push --registry-config $authfile …
```

That way the credentials of the operation don’t leak into the user account (which might be irrelevant if the user account is single-use for the operation), other credentials of the user account don’t leak into the operation (e.g. for mirrors), and it’s clearly traceable where the credentials come from and what uses them.

**Comment by jacksgt** [comment]
Alright, thanks for your input.
