### ISSUE TITLE
Quadlet: discrepancy of container option default values in documentation and code

### ISSUE THREAD

**Issue by xduugu** [containers/podman#17909]
### Issue Description

While playing around with the new quadlet functionality, I noticed that quadlet uses different default values for several options than stated in the [documentation](https://docs.podman.io/en/v4.4/markdown/podman-systemd.unit.5.html). I don't know if these are bugs in the code or the documentation is not correct.

### Documentation

Defaults to `all` according to documentation.

https://github.com/containers/podman/blob/cb18a33f63de2a25d2352fc6a31e38908ac5b647/docs/source/markdown/podman-systemd.unit.5.md?plain=1#L165-L174

### Code

The provided capabilities are correctly dropped, but there is no default of `all`, if the option `DropCapability` is empty or not provided at all.

https://github.com/containers/podman/blob/cb18a33f63de2a25d2352fc6a31e38908ac5b647/pkg/systemd/quadlet/quadlet.go#L431-L435

### Documentation

This one is really strange. In the option title it says `defaults to no`, but in the description below, it states `If enabled (which is the default)`.

https://github.com/containers/podman/blob/cb18a33f63de2a25d2352fc6a31e38908ac5b647/docs/source/markdown/podman-systemd.unit.5.md?plain=1#L329-L332

### Code

The comment in the code suggests that `NoNewPrivileges` should be enabled by default, but `noNewPrivileges` is set to `false` if the lookup fails.

https://github.com/containers/podman/blob/cb18a33f63de2a25d2352fc6a31e38908ac5b647/pkg/systemd/quadlet/quadlet.go#L393-L397

### Documenation

According to the documentation, the default value of `VolatileTmp` depends on the value of `ReadOnly`.

https://github.com/containers/podman/blob/cb18a33f63de2a25d2352fc6a31e38908ac5b647/docs/source/markdown/podman-systemd.unit.5.md?plain=1#L380-L384

https://github.com/containers/podman/blob/cb18a33f63de2a25d2352fc6a31e38908ac5b647/docs/source/markdown/podman-systemd.unit.5.md?plain=1#L459-L463

### Code

But in the code, the default value for `VolatileTmp` is always `false`. If `volatileTmp` should behave as documented, the default value would be `readOnly` and not `false`.

https://github.com/containers/podman/blob/cb18a33f63de2a25d2352fc6a31e38908ac5b647/pkg/systemd/quadlet/quadlet.go#L443-L457

### Steps to reproduce the issue

Steps to reproduce the issue
1.
2.
3.

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by xduugu** [comment]
I think the issue is still valid.

**Comment by rhatdan** [comment]
DropCapabilty="" defaults to the capabilities defined in containers.conf just like normal podman,  If you want all caps then you need to specify 
AddCapability=all

Then you can drop specific capabilities.
DropCapaility=CAP_DAC_OVERRIDE CAP_IPC_OWNER

**Comment by rhatdan** [comment]
```
 ### `NoNewPrivileges=` (defaults to `no`) 
  
 If enabled (which is the default), this disables the container processes from gaining additional privileges via things like 
```
This is a bug in documentation, please open a PR. It is default to disabled, (Actually to the setting in containers.conf
 setuid and file capabilities.

**Comment by rhatdan** [comment]
I think the issue, is when quadlet first got merged, we changed the defaults from Podman, we later decided to stick with Podman defaults as defined in containers.conf.  But no one noticed the man page was wrong.

Are you interested in fixing the man page?

**Comment by xduugu** [comment]
I didn't meant to bug you, @rhatdan, I just didn't want this issue to get closed as stale.
Actually, I already started to fix the documentation. So yes, you can assign this issue to me.
