### ISSUE TITLE
Quadlet: Support `keep-id` options in `RemapUsers`

### ISSUE THREAD

**Issue by xduugu** [containers/podman#17908]
### Feature request description

It is possible to explicitly set the `uid` and `gid` when using the `keep-id` mode with the [`--userns` option of `podman run`](https://docs.podman.io/en/v4.4/markdown/podman-run.1.html#userns-mode). Please make it possible to optionally provide these options for `keep-id` as part of the `RemapUsers` value (e.g. `keep-id:uid=200,gid=210`).

### Have you considered any alternatives?

I currently use `PodmanArgs=` as a workaround.

**Comment by rhatdan** [comment]
What happens when you specify that value now?

**Comment by xduugu** [comment]
When use the option `RemapUsers=keep-id:uid=200,gid=210` in a container file, quadlet prints an error:
```
Error converting 'test.container', ignoring: unsupported RemapUsers option 'keep-id:uid=200,gid=210'
```

**Comment by rhatdan** [comment]
Ok I would say that is a bug.
What do you think @ygalblum @vrothberg

**Comment by xduugu** [comment]
Thanks for the implementation @ygalblum.

You updated the documentation of `RemapGid`/`RemapUid`/`RemapUsers` only for `Kube units`, but it looks like it also applies to `Container units`, right?

https://github.com/containers/podman/blob/11e5c2d0fdc8c0a0c2d2ec3ddb3b5023de9d0bfc/docs/source/markdown/podman-systemd.unit.5.md?plain=1#L386-L401

https://github.com/containers/podman/blob/11e5c2d0fdc8c0a0c2d2ec3ddb3b5023de9d0bfc/docs/source/markdown/podman-systemd.unit.5.md?plain=1#L407-L417

---

By the way, according to the documentation, it is possible to set `RemapGid` to `keep-id` which then translates to the `podman run` argument `--group-add keep-id`. I cannot find this part in the code and according  to the `podman-run` documentation, `keep-id` not a valid value. Maybe I should add this to #17909?

https://github.com/containers/podman/blob/11e5c2d0fdc8c0a0c2d2ec3ddb3b5023de9d0bfc/docs/source/markdown/podman-systemd.unit.5.md?plain=1#L113

https://github.com/containers/podman/blob/11e5c2d0fdc8c0a0c2d2ec3ddb3b5023de9d0bfc/docs/source/markdown/options/group-add.md?plain=1#L5-L15

**Comment by ygalblum** [comment]
@xduugu thanks for pointing out these documentation issues.
Regarding the Container section, you are correct, it applies for both.
Regarding the value for `RemapGid`, while I agree that the sample value in the documentation is incorrect, currently, Quadlet does not have a key that translates to `--group-add`. But, I didn't find such a statement in the documentation either
