### ISSUE TITLE
sqlite: podman container commit: container already exists

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#17905]
Seen just now in [f36 rootless sqlite](https://api.cirrus-ci.com/v1/artifact/task/5923828761624576/html/sys-podman-fedora-36-rootless-host-sqlite.log.html#t--00381)

```
$ podman container commit -q c1
Error: more than one result for container "c1": container already exists
```

**Comment by edsantiago** [comment]
Weird. Two more, again [f36 rootless](https://api.cirrus-ci.com/v1/artifact/task/5624020448575488/html/sys-podman-fedora-36-rootless-host-sqlite.log.html#t--00099), very slightly different symptom:
```
not ok 99 podman logs - multi k8s-file
...
$ podman run --log-driver=k8s-file --rm -d --name c2 quay.io/libpod/testimage:20221018 sh -c sleep 1;echo b;sleep  2;echo c;sleep 3
cb47269f92125ad802705ecf691f58a26b577e323bc94187883893093b0af65b
$ podman logs -f c1 c2
Error: more than one result for container "c2": container already exists
```
...then again, exactly the same error, in the next test ("multi journald").

**Comment by vrothberg** [comment]
Yes, indeed that's a bug in the code.

**Comment by vrothberg** [comment]
Should also add a regression test for it!
