### ISSUE TITLE
Can't access published (host) ports - Netavark

### ISSUE THREAD

**Issue by kmpeterson** [containers/podman#17927]
### Issue Description

Apologize if I've gone down a path the wrong way.  Very briefly: trying to migrate network services in singleton containers, need them to be accessible at fixed IP and usually via https, and also on a dedicated Ethernet interface.  Have assumed the way to do this: podman, Netavark, create a separate network with the macvlan driver.

However, attempting to run containers, published ports (e.g., `--publish=443:5601`) are ignored.  5601 is accessible and operates normally.  Very difficult to work around (one of the containers is for syslog, so 514 needs to work).  

### Steps to reproduce the issue

Steps to reproduce the issue
1.  Verify `network_backend = "netavark"` set in `/etc/containers/containers.conf`. 
2. Create a network, bound to eno2 on the host: `podman network create --driver=macvlan -o parent=eno2 --ipv6 containernet0` (also with IPv4 and IPv6 `--subnet`, `--ip-range`, and `--gateway`).  
3.  Run dwalsh's example Apache container: `podman run --user=root -d -p 80:8080 --name testapa --network=containernet0 --ip=192.168.0.99 registry.access.redhat.com/ubi8/httpd-24:latest` - run by root user.
4.  Check connectivity: from another (or the same) host, `curl http://192.168.0.99`

### Describe the results you received

Describe the results you received
`curl: (7) Failed to connect to 192.168.0.99 port 80: Connection refused`

Tested with `podman run`, with `--user=root`, and `--privileged` and with neither.   

### Describe the results you expected

Describe the results you expected
The RHEL test page.  Note that this _is_ the result from `curl http://192.168.0.99:8080`

### podman info output

```yaml
(This is RHEL 9.1, podman-4.2.0-11.el9_1.x86_64)

host:
  arch: amd64
  buildahVersion: 1.27.3
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: 56561007b6a59ea175ee9a67384639721499e160'
  cpuUtilization:
    idlePercent: 89.71
    systemPercent: 2.12
    userPercent: 8.17
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "9.1"
  eventLogger: journald
  hostname: five.kmpeterson.net
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.0-162.18.1.el9_1.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 14828531712
  memTotal: 33225539584
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.el9_0.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 16814960640
  swapTotal: 16814960640
  uptime: 3h 6m 55.00s (Approximately 0.12 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 10
    paused: 0
    running: 9
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 34342961152
  graphRootUsed: 10065133568
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 48
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1675767401
  BuiltTime: Tue Feb  7 05:56:41 2023
  GitCommit: ""
  GoVersion: go1.18.9
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

- Attempting to specify the IP as part of the `--publish` parameter for the port generates `Error: cannot listen on the TCP port: listen tcp4 192.168.0.99:80: bind: cannot assign requested address`.  
- Same results using IPv6 addresses.
- I have the impression that podman would have to be run as root in order to bind to an external IP, so I have not attempted to do any of this work as a non-privileged user.  So, 
- I have been trying to figure out whether it would be possible to redirect the port with nftables.  However, interestingly, _nothing_ is configured as far as I can tell in this environment by podman with firewalld or iptables or nftables - which I suppose might be expected, but makes it difficult to see what rules might be created and start from there.  
- I'd work around this issue that way if I could.

**Comment by kmpeterson** [comment]
Thanks for the response.  I'm using the developer (free) program for RHEL, so I'm not a "customer" per se; there's not any prioritization involved though probably no reason not to see if I can submit to their Bugzilla.

The model that I currently am migrating from is using docker-compose for a number of infrastructure services, most of which have a DNS entry but for convenience are running in containers that are port-forwarded to 443.  In other words, as if these were all VMs, each with different addresses, etc.  I am directly connecting to the IP, the problem is I want to publish, for example, a container port of 8080 to the assigned IP port 443.  All of the containers I've tested thus far live at their "correct" IPs, just not the ports I need.

Thanks for the confirmation that you're not configuring firewall rules for macvlan - that was confusing me.  However, I would like to ask whether it _should_ be possible to accomplish my port forwarding needs using nftables - I was heading down that path, but didn't want to dead-end if it's actually not possible in macvlan configuration.   My first attempts at locating the correct place to hook weren't productive... but if that's my (only) option I'll stay on it.

I appreciate that everyone is busy working on the newer versions of the code and don't want to divert resources; I'm grateful for any other ideas or pointers.

**Comment by Luap99** [comment]
> Thanks for the response. I'm using the developer (free) program for RHEL, so I'm not a "customer" per se; there's not any prioritization involved though probably no reason not to see if I can submit to their Bugzilla.

It is fine to have this discussion on github then, it is just that we only work on the latest version so if we ever make a change depending on the on the release timing it can take over 6 months until it lands in the latest RHEL version.

---
I haven't worked with the nft tool but I guess something like [this](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-configuring_port_forwarding_using_nftables) should work.

In any case I think our current behaviour of silently ignoring ports with macvlan is not very good. We should either configure port forwarding or throw a warning that the ports are ignored. @mheon WDYT?

**Comment by Luap99** [comment]
Reading more about macvlan I do not think port forwarding works at all. It seems like it is impossible to connect from host to container or from container to host so any forward rule will never work. Only external communication is allowed.
There seems to be some workarounds by certain another macvlan interface on the host which then can talk to the others.

Are sure you really need macvlan? Alternatively you can use two networks one macvlan and one normal bridge on the same container this should make port forwarding work via bridge and direct access via ip with maclvan.

**Comment by kmpeterson** [comment]
Hi @Luap99 - thanks again for your help here.  I've been trying for the last week to understand how macvlan bypasses netfilter, and what seems to be the case is that because podman implements separate network namespaces, the netns's traffic aren't seen by the host.  I've tried every way to even set up nft rules with counters to try to track this, but no... this still doesn't make 100% sense to me, but I think I need to turn towards a workaround.

You asked a really good question, which was "do I really need macvlan".  The functionality I'm trying to get is to have containers "addressable" by IP, on a separate physical interface from that of the primary host - and, of course, to map privileged ports for some of them (5601, 443, 162, 514, and 80) to the container (hopefully running rootless, though that may not be possible).   Literally, I just want (internal) users to type https://xxx as if accessing a service on a physical or virtual host, and not change clients for syslog/snmp/dns/ntp/ipp.  Could put a proxy up for these too, but I'm trying for most simple.  

This just feels to me like a really simple use case, and that I'm missing something... everything works perfectly (even accessing these containers from their host) - just no firewall (to forward ports or of course add any other controls).  It appears this is an obvious barrier to moving things out of VMs and so I'm still puzzled that I've stumbled into this and no one else has.  

Very much appreciate your feedback and efforts here!

**Comment by kmpeterson** [comment]
And, of course, it became clear when I was reading your suggestion about adding another network that I needed to question why I was using forwarding in the first place.

My fundamental use case is that the only problem I have at this point is binding to ports <1024.  All the other pieces work except being able to forward privileged ports externally to a non-privileged port in the container, but I realize the immediate answer  is `--add-cap=CAP_NET_BIND_SERVICE`, and just bind the privileged ports I need directly (e.g. just let apache use 443 for https as if it would by default).  

It'd be helpful to have something in the docs that confirmed what you said: macvlan doesn't interact with the host network stack at all and thus no firewall rules are (or can be) automatically created as with the other drivers.  

So this is worked around.  I appreciate your taking a look at my question; I'd be happy to submit a documentation PR if appropriate to prevent the next person with this idea from spending as much time on it as I have.

**Comment by Luap99** [comment]
Documentation PRs are always welcome, I guess it you could put it in [podman-network-create(1)](https://github.com/containers/podman/blob/main/docs/source/markdown/podman-network-create.1.md#--driver--ddriver)
