### ISSUE TITLE
With Pasta, Infrastructure container entry doesn't manifest

### ISSUE THREAD

**Issue by andrewgdunn** [containers/podman#17922]
### Issue Description

When using `--net=pasta` with a pod the invocation fails to set the infrastructure container hostname. Instead the pod name is set in front of the host name of the next container added to the pod.

I noticed this when attempting to deploy [immich](https://github.com/immich-app/immich), which requires several containers and local hostname resolution within the pod.

### Steps to reproduce the issue

(WORKING) Without Pasta:

```
podman pod create --name immich --publish 127.0.0.1:3300:8080

podman run --replace --detach --pod=immich --name=redis --label "io.containers.autoupdate=image" docker.io/library/redis:latest

podman exec -it redis bash

# cat /etc/hosts 
127.0.0.1	localhost localhost.localdomain localhost4 localhost4.localdomain4
::1	localhost localhost.localdomain localhost6 localhost6.localdomain6
172.22.4.4	host.containers.internal
10.0.2.100	immich 3c0d761ba169-infra
127.0.0.1	redis
```
(FAILURE) With Pasta:

```
podman pod create --name immich --net=pasta --publish 127.0.0.1:3300:8080

podman run --replace --detach --pod=immich --name=redis --label "io.containers.autoupdate=image" docker.io/library/redis:latest

podman exec -it redis bash

# cat /etc/hosts 
127.0.0.1	localhost localhost.localdomain localhost4 localhost4.localdomain4
::1	localhost localhost.localdomain localhost6 localhost6.localdomain6
172.22.4.4	host.containers.internal
127.0.0.1	immich redis
```

### Describe the results you received

Describe the results you received

### Describe the results you expected

I'd expected as I added more containers to the pod to have name resolution work, however whatever container is first added to the pod when using `--net=pasta` has its hostname effectively mangled.

### podman info output

```yaml
$ podman info
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.6-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.6, commit: ae34694dbfd15d1b90e7219e4a964df2f1c6c415'
  cpuUtilization:
    idlePercent: 99.04
    systemPercent: 0.44
    userPercent: 0.52
  cpus: 32
  distribution:
    distribution: '"centos"'
    version: "9"
  eventLogger: file
  hostname: muckle
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 3300
      size: 1
    - container_id: 1
      host_id: 362144
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 3300
      size: 1
    - container_id: 1
      host_id: 362144
      size: 65536
  kernel: 5.14.0-285.el9.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 99337564160
  memTotal: 270122323968
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.1-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.1
      commit: f8a096be060b22ccd3d5f3ebe44108517fbf6c30
      rundir: /run/user/3300/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/3300/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-3.el9.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 34345054208
  swapTotal: 34345054208
  uptime: 70h 22m 31.00s (Approximately 2.92 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /zfs/safe/memory/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 4
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /zfs/safe/memory/.local/share/containers/storage
  graphRootAllocated: 3610553614336
  graphRootUsed: 3122003968
  graphStatus:
    Backing Filesystem: zfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 10
  runRoot: /run/user/3300/containers
  transientStore: false
  volumePath: /zfs/safe/memory/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.1
  Built: 1676977843
  BuiltTime: Tue Feb 21 06:10:43 2023
  GitCommit: ""
  GoVersion: go1.19.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Running podman rootless-as-non-root (using a non-root user).

**Comment by sbrivio-rh** [comment]
Andrew, thanks for reporting this.

I'm not familiar with the name resolution requirements of `immich`. What is exactly the resolution request that needs to be answered differently, or the missing/wrong entry in `/etc/hosts` here?

That is, would you expect `3c0d761ba169-infra` to be resolved, in the container, as `127.0.0.1` and `::1`? Or as the non-loopback addresses given to the container?

**Comment by Luap99** [comment]
See https://github.com/containers/podman/blob/78f1ebb80ba473f4f9bb016aec5d190645089cce/libpod/container_internal_common.go#L2143-L2162 for the current selection, I guess we simply missed adding pasta there.

The only problem is that pasta does not use a static ip, we would actually have to join the netns to get the correct ip for the entry. Not a big deal just some extra steps.

**Comment by sbrivio-rh** [comment]
Assuming I'll have to fix this: no progress yet, but I'm not blocked either, @Luap99 already outlined the steps.

**Comment by dgibson** [comment]
@Luap99, Stefano has been super busy, so I've been taking a look at this.  I'm not familiar enough yet with podman internals to know what I'd need to do to enter the namespace and probe the IP in the pasta case.  Can you give me any pointers here?

**Comment by Luap99** [comment]
I was about to work on this, if you want to take it that is good for me as well.

I already fixed that in buildah you basically just need to do this: https://github.com/containers/buildah/blob/6589be3ba189107e9389c8454951ff38fe9692ab/run_linux.go#L536-L544
The netns path is stored in `c.state.NetNS`

and just add the IsPasta() case to the switch in `getHostsEntries()` I already linked above.

**Comment by dgibson** [comment]
@Luap99 thanks.  I've sent a PR, which I think does the right thing.

I am a bit concerned this may be fragile - I see an entry for the host's public IP in /etc/hosts as well.  This is likely to be the same as the pod IP with pasta, which may break things that need to communicate with both.
