### ISSUE TITLE
I want to curl host server in podman but get network unreachable

### ISSUE THREAD

**Issue by fancy45daddy** [containers/podman#17924]
### Issue Description

I want to curl host server in podman but get network unreachable

### Steps to reproduce the issue

Steps to reproduce the issue
1.in host machine: python3 -m http.server I create http server on host on port 8000
2.in host machine: podman run -it --rm docker.io/library/ubuntu bash
3.inside container: apt update
4.inside container: apt install -y --no-install-recommends curl
5.inside container: curl http://host.containers.internal:8000

### Describe the results you received

curl: (7) Failed to connect to host.containers.internal port 8000 after 0 ms: Network is unreachable

### Describe the results you expected

some html output

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 8
  distribution:
    codename: vera
    distribution: linuxmint
    version: "21.1"
  eventLogger: journald
  hostname: chaowenguo-Alienware-17-R4
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.0-56-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 7907495936
  memTotal: 16642969600
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 472276992
  swapTotal: 472276992
  uptime: 1h 22m 53.67s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/chaowenguo/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/chaowenguo/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  volumePath: /home/chaowenguo/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Wed Dec 31 16:00:00 1969
  GitCommit: ""
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 3.4.4
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by baude** [comment]
this works for me with ping in both rootful and rootless with main branch.  @fancy45daddy your podman is *very* old.  Is it possible to get a newer version on mint?

**Comment by fancy45daddy** [comment]
I can ping too, I want curl working for specific port. I want curl to work. Please help

**Comment by Luap99** [comment]
What ip does `http://host.containers.internal` point to, it should be your eth0 (or however your physical interface is called) ip?
Your reproducer works fine with v4.4 so I suggest you update your podman version.

**Comment by fgimian** [comment]
> What ip does `http://host.containers.internal` point to, it should be your eth0 (or however your physical interface is called) ip? Your reproducer works fine with v4.4 so I suggest you update your podman version.

Sorry to quote on a closed issue but I am facing the same issue with Podman 3.4.4. The issue with suggesting the upgrade to the latest release is that the Ubuntu LTS is 22.04 and it ships with Podman 3.4.4.

The [official instructions](https://podman.io/docs/installation#ubuntu) for Ubuntu suggest installation from the official repos with a clear indication that the Kubic repos are not to be used for production use.

So where does that leave us poor souls attempting to deploy a server environment based on Ubuntu LTS?

I can see that on this older release, the IP of `host.containers.internal` is not correctly populated with my host IP:

```
root@375179e2410f:/# grep -F host.containers /etc/hosts
10.0.2.2 host.containers.internal
```

Most host IP is in the 192.168.x.x range.

I can confirm everything works on Ubuntu 23.04 with Podman 4.3.x which it ships with, but Ubuntu 23.04 is not an LTS release.

I'd really love a recommendation on this point as it's making me more and more nervous about deploying Podman in our environment.

Cheers
Fotis

**Comment by Luap99** [comment]
Your choice of distro is not my upstream dev problem, we support the latest version upstream and that's it. If a distro decides to not update the package and calls that LTS then well there is nothing for us to do. If you have problems with the version shipped in your distro should file the bug against your distro.

I understand that this is not the answer you are looking for but we are upstream devs and have no direct control how our software is a packaged. The kubic repo is not recommended because it is maintained by a single person in his spare time. 
So you can use it and report problems with it but if it does not work don't complain if they are not fixed quickly.

I understand that this may not be answer you are looking for but resources are limited.

**Comment by vrothberg** [comment]
FWIW, we are talking with the Ubuntu community about a potential Podman snap.  But snap has limitations especially when it comes to rootless Podman, so it's not ideal.

We're a bit between a rock and hard place.  As @Luap99 mentioned, we sympathize with the desire to update Podman on Ubuntu LTS versions.  But we have limited resources upstream, so an alternative approach could be to reach out to Ubuntu/Canonical and ask there for updates to Podman.  Ultimately, it's up to the distributions.

**Comment by fgimian** [comment]
@Luap99 and @vrothberg Thank you both for the replies. I do genuinely appreciate it along with your efforts on this project. I suppose the hope has always been that we would see some official APT and DNF repositories for the project much like various other open source projects but I completely understand the time constraint and respect your position on this.

Cheers
Fotis
