### ISSUE TITLE
Assign pod to running podman container

### ISSUE THREAD

**Issue by josnin** [containers/podman#17929]
### Feature request description

it is possible to assign the newly created pod to a running podman container ?
```
[josnin@fedora sweety]$ podman pod ps
POD ID        NAME        STATUS      CREATED       INFRA ID      # OF CONTAINERS
5f7fcc788360  prod-pod    Created     15 hours ago  cdc2fe493071  5

```

should be a able to assign to this running podman container (if we want to)
```
[josnin@fedora sweety]$ podman ps --pod
CONTAINER ID  IMAGE                                COMMAND     CREATED        STATUS             PORTS                                             NAMES                POD ID      PODNAME
1ec7a973347565  docker.io/jenkins/jenkins:lts-jdk11              11 months ago  Up 13 seconds ago  0.0.0.0:8080->8080/tcp, 0.0.0.0:50000->50000/tcp  intelligent_taussig  
```

### Suggest potential solution

Suggest
```
podman assign  --pod=prod-pod intelligent_taussig
```

### Have you considered any alternatives?

I have to run another container with the newly assign pod and just remove the old one

```
podman run --pod=prod-pod -d --name jenkins-prod-svc docker.io/jenkins/jenkins:lts-jdk11
```

**Comment by rhatdan** [comment]
No containers have to be assigned to pods at creation time.  Since the namespaces are already created and processes are running within them, there is no way to move them to a pod, which would be running in different namespaces.
