### ISSUE TITLE
podman machine start/stop without args does not reflect actual default VM

### ISSUE THREAD

**Issue by lukas-vlcek** [containers/podman#17962]
### Issue Description

When I flag my custom VM as a default VM (`podman system connection default <my_vm>`) and then use `podman machine start` or `stop` without arguments it does not try to start/stop <my_vm> but the original `podman-machine-default`.

If this is not a bug but feature, please make sure the [documentation](https://docs.podman.io/en/latest/markdown/podman-machine-start.1.html) is more specific.

```shell
> podman version
Client:       Podman Engine
Version:      4.4.2
API Version:  4.4.2
Go Version:   go1.20.1
Git Commit:   74afe26887f814d1c39925a1624851ef3590e79c
Built:        Thu Feb 23 16:59:21 2023
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.4.2
API Version:  4.4.2
Go Version:   go1.19.6
Built:        Wed Mar  1 12:22:39 2023
OS/Arch:      linux/arm64
```

(see below for `podman info`)

### Steps to reproduce the issue

Steps to reproduce the issue (for `stop`)
1. Verify which VM is the default one using `podman system connection list`
2. `podman machine stop` should stop the default VM

Steps to reproduce the issue (for `start`)
1. Create a custom <my_vm> VM next to existing `podman-machine-default`
3. `podman system connection default <my_vm>`
4. Verify which VM is the default one using `podman system connection list`
5. Make sure all machine VMs are stopped
6. `podman machine start`

### For the `stop` command:

1. My custom VM is running
```shell
% podman machine list
NAME                    VM TYPE     CREATED       LAST UP            CPUS        MEMORY      DISK SIZE
testOpenSearch*         qemu        25 hours ago  Currently running  4           34.36GB     107.4GB
podman-machine-default  qemu        25 hours ago  42 minutes ago     1           2.147GB     107.4GB
```
2. Stop the default VM (it just tells me that the `podman-machine-default` is stipped, but that is not the default VM)
```shell
 % podman machine stop
Machine "podman-machine-default" stopped successfully
```

### For the `start` command:

1. I have two VMs, one of them is custom one and set as the default
```shell
% podman machine list               
NAME                    VM TYPE     CREATED       LAST UP         CPUS        MEMORY      DISK SIZE
testOpenSearch*         qemu        25 hours ago  23 seconds ago  4           34.36GB     107.4GB
podman-machine-default  qemu        25 hours ago  45 minutes ago  1           2.147GB     107.4GB

% podman system connection list  
Name                         URI                                                         Identity                                        Default
podman-machine-default       ssh://core@localhost:60582/run/user/501/podman/podman.sock  /Users/lukas.vlcek/.ssh/podman-machine-default  false
podman-machine-default-root  ssh://root@localhost:60582/run/podman/podman.sock           /Users/lukas.vlcek/.ssh/podman-machine-default  false
testOpenSearch               ssh://core@localhost:60707/run/user/501/podman/podman.sock  /Users/lukas.vlcek/.ssh/testOpenSearch          true
testOpenSearch-root          ssh://root@localhost:60707/run/podman/podman.sock           /Users/lukas.vlcek/.ssh/testOpenSearch          false
```
2. Start the default VM
```shell
% podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Mounting volume... /Users:/Users
Mounting volume... /private:/private
Mounting volume... /var/folders:/var/folders

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command: 

	podman machine set --rootful

API forwarding listening on: /var/run/docker.sock
Docker API clients default to this address. You do not need to set DOCKER_HOST.

Machine "podman-machine-default" started successfully
```
Why does it not start the default VM?

### Describe the results you expected

If `podman machine start/stop` is not given any arguments then it should start the default VM as defined by `podman machine list` or `podman system connection list`. Otherwise it is confusing to me and the [documentation](https://docs.podman.io/en/latest/markdown/podman-machine-start.1.html) does not provide any hint about why this is the case.

### podman info output

```yaml
host:
  arch: arm64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc37.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 99.77
    systemPercent: 0.2
    userPercent: 0.03
  cpus: 4
  distribution:
    distribution: fedora
    variant: coreos
    version: "37"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.1.18-200.fc37.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 33169633280
  memTotal: 33580806144
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.1-1.fc37.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.1
      commit: f8a096be060b22ccd3d5f3ebe44108517fbf6c30
      rundir: /run/user/501/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/501/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.aarch64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 35m 57.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 0
    stopped: 5
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 2360733696
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/501/containers
  transientStore: false
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.2
  Built: 1677669759
  BuiltTime: Wed Mar  1 12:22:39 2023
  GitCommit: ""
  GoVersion: go1.19.6
  Os: linux
  OsArch: linux/arm64
  Version: 4.4.2
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

### Additional environment details

Running podman `4.4.2` since it is the latest that `brew` offers at the moment (I do not feel like messing with `brew` much at this point of my research). I know it is not the most recent release (as of writing) but according to release notes none of `4.4.3` or `4.4.4` brings any fixes in this area. At least the source code of the command looks unchanged: https://github.com/containers/podman/blob/main/cmd/podman/machine/start.go#L51

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
This is expected, podman system connection manages only connections not machine VMs.
I am not aware of any options to change the default machine name. You have to use the machine commands with the VM name as argument.

That said I think your request makes sense as feature request, especially when there is only a single VM I see little reason to require the name to be specified on the cli every time.  

cc @baude @ashley-cui

**Comment by ashley-cui** [comment]
This is the intended behavior, as the default connection is different than the default machine. I can update the docs to reflect this. 

The idea of being able configure the default machine name is interesting.

**Comment by vrothberg** [comment]
@ashley-cui documenting the current behavior sounds like a good idea to me.

I personally don't like to default to some machine when no argument is given. Podman expects arguments for most commands (e.g., container, pod, volume, etc.).

**Comment by Luap99** [comment]
> I personally don't like to default to some machine when no argument is given. Podman expects arguments for most commands (e.g., container, pod, volume, etc.).

I agree, it also makes argument parsing much more complicated then it should be but it is what it is, so we have to live with this design decision now.
