### ISSUE TITLE
Epic: ginkgo: remove -flakeAttempts 3

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#17967]
It's hurting us. We need to make a concerted effort to remove it.

Best I can tell, there are three kinds of e2e flakes:
1. network or registry (or other resource) flakes
2. real podman bugs
3. bugs in the tests themselves

I believe the vast majority of the test failures I'm seeing are **3, test bugs**. Ginkgo runs tests in parallel, and I don't think we're doing enough locking around (e.g.) `podman system reset` or `network` or `gpg` tests. There are also simple race conditions. I suspect, but cannot be certain, that these are test bugs: containers/podman#17940, containers/podman#17946, containers/podman#17957, containers/podman#17958, containers/podman#17966.

Unfortunately, by hiding flakes we also hide **number 2, real podman bugs**. You all know the nightmares we're having right now with sqlite: those were in the test logs all along, we could've caught them earlier if we hadn't been retrying flakes. I hope that's a strong enough argument for my position, because we truly have no idea how many other such bugs are hiding in plain sight.

And, sigh, *network/registry flakes*. This is a valid use case for retrying; I just don't know how to do it. It might be necessary to go test-by-test, looking for `search` or `pull`, and wrap those in a retry mechanism. Thoughts welcome.

Reminder: my flake logger only catches **triple failures**, the ones that force you to press Rerun. When e2e tests single-fail, I have no way of knowing about it. So I'm pretty sure these single-fails are happening every day, on every run, and we're just not seeing them.

And, don't panic: we can't remove `-flakeAttempts` any time soon. We have way way way way way too many test-bug flakes, so many that it takes 4-10 retries, and many hours, just to get CI passing on a single PR. We first need to fix the bug-test flakes, which means we need to identify them, which means I need to find a better way of tracking them. Although Evil-Twin Ed thinks that disabling retries right now would make everyone highly motivated to fix the test-bug flakes...

**Comment by vrothberg** [comment]
+1 from my side

We must _collectively_ pay more attention to flakes.  I also agree that we first need to tackle the known flakes before opening Pandora's box.

**Comment by vrothberg** [comment]
@mheon something to consider for bug week(s).

**Comment by Luap99** [comment]
In general I agree with the assessment however as we talked some weeks ago it is painful having to rerun the full test suite just because a single test flaked, it would be much better if just this single flake was rerun.

> Reminder: my flake logger only catches triple failures, the ones that force you to press Rerun. When e2e tests single-fail, I have no way of knowing about it. So I'm pretty sure these single-fails are happening every day, on every run, and we're just not seeing them.

Is there any reason to not just fix that? Let's take https://api.cirrus-ci.com/v1/artifact/task/5464387922690048/html/int-podman-debian-12-root-host-boltdb.log.html for example, the log exactly shows that there was a single flake so why do you have no way of knowing?

**Comment by edsantiago** [comment]
The **logfile** shows a flake happening... but I do not see logfiles. What I do is ask Cirrus: "for build X, please give me the status of all tasks that ran". ("X" is a long Cirrus number associated with a PR). I then run through that list and fetch logs _only for tasks that failed_.  I do not fetch logs for tasks that passed, hence do not see tasks with retry-and-pass flakes.

I may need to reevaluate that design decision. It will not be easy.

**Comment by edsantiago** [comment]
For future reference: ginkgo v2 includes a [FlakeAttempts decorator](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#flakeattempts-decorator) which could be especially useful in `podman search` tests.

**Comment by Luap99** [comment]
> For future reference: ginkgo v2 includes a [FlakeAttempts decorator](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#flakeattempts-decorator) which could be especially useful in `podman search` tests.

Yes exactly , I was going to suggest this as better solution for this. `FlakeAttempts` should then only be used for flakes we know are unfixable (pull/search on external registries), everything else must be fixed instead.

**Comment by edsantiago** [comment]
With the merge of #18816 we are much, much closer to accomplishing this.

**Comment by edsantiago** [comment]
Current list of blockers:
* #18753 
* #18355 
* #18501 
* #18472
* #18865
* #18831
* #18874
* #17957
* #18484 (not like we can do anything about this one)
* #18448

And of course our old favorite #10927
