### ISSUE TITLE
Quadlet - add UserNS key that may be passed as is to run or kube play

### ISSUE THREAD

**Issue by ygalblum** [containers/podman#17984]
### Feature request description

The current implementation divides the argument that will eventually be passed to `--userns` to different parameters. As a result, any change in the possible values might require changes in Quadlet. In addition, it can cause a proliferation of supported keys.

Before implementing this, we need to decide how to handle backward compatibility

**Comment by vrothberg** [comment]
I am in favor of adding `UserNS` and deprecate the other fields.  From a RHEL perspective, Quadlet is still tech-preview so there no backwards guarantees until GA.

**Comment by vrothberg** [comment]
@giuseppe @rhatdan PTAL

**Comment by giuseppe** [comment]
same for me.  Let's keep it simple and map directly to `UserNS`

**Comment by rhatdan** [comment]
I agree, the other keys just confuse me, and if people are going back and forth, I don't see the value in breaking it up.

**Comment by xduugu** [comment]
I've created a pull request for the new key. Since it deprecates the Remap keys, it would be great if it could be included in v4.5
