### ISSUE TITLE
e2e: podm rm empty pod: error in WalkDir

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#17989]
```
  podman pod rm empty pod
...

Unexpected error:
               <*fs.PathError | 0xc000879530>: 
               open /sys/fs/cgroup/user.slice/user-3004.slice/user@3004.service/user.slice/libpod-conmon-a71b28bb423c68c150e51edc8e578afeda8d12bd770d4190d21a56fcaaa7e676.scope: no such file or directory
               {
                   Op: "open",
                   Path: "/sys/fs/cgroup/user.slice/user-3004.slice/user@3004.service/user.slice/libpod-conmon-a71b28bb423c68c150e51edc8e578afeda8d12bd770d4190d21a56fcaaa7e676.scope",
                   Err: <syscall.Errno>0x2,
               }
```
The code in question is https://github.com/containers/podman/blob/c247b90c4a61a3e4ee38544ea10d5409d805bfbb/test/e2e/pod_rm_test.go#L47-L48

Only one instance that I can find, in [f37 rootless](https://api.cirrus-ci.com/v1/artifact/task/6414147026419712/html/int-podman-fedora-37-rootless-host-boltdb.log.html#t--podman-pod-rm-empty-pod--1)

**Comment by edsantiago** [comment]
Another one, today, [also f37 rootless](https://api.cirrus-ci.com/v1/artifact/task/5548336044834816/html/int-podman-fedora-37-rootless-host-boltdb.log.html#t--podman-pod-rm-empty-pod--1) but slightly different error message:
```
Unexpected error:
      <*fs.PathError | 0xc000962450>: 
      open /sys/fs/cgroup/user.slice/user-5417.slice/user@5417.service/user.slice/podman-48007.scope: no such file or directory
      {
          Op: "open",
          Path: "/sys/fs/cgroup/user.slice/user-5417.slice/user@5417.service/user.slice/podman-48007.scope",
          Err: <syscall.Errno>0x2,
      }
  occurred
```
Difference I see is: in the first one, `user.slice` is `libpod-conmon-CID`. In this one it's `podman-X.scope`.

**Comment by giuseppe** [comment]
@edsantiago thanks for the ping, I think the issue is in the test itself, opened a PR: https://github.com/containers/podman/pull/18277
