### ISSUE TITLE
Cannot bind dir in WSL2

### ISSUE THREAD

**Issue by mario-demontis-inpeco** [containers/podman#17986]
### Issue Description

On Windows, I cannot run a container that binds to a directory in WSL2:

cd \\\\wsl.localhost\podman-machine-default\home\user
podman run -it -v .:/mydir ubuntu:latest
Error: getting absolute path of .: unsupported UNC path

Also this doesn't work:
cd c:\\
podman run -it -v \\wsl.localhost\podman-machine-default\home\user:/mydir ubuntu:latest
Error: getting absolute path of \\\\wsl.localhost\podman-machine-default\home\user: unsupported UNC path

Same thing using podman for linux:
podman machine ssh
podman run -it -v .:/foo ubuntu:latest
Error: getting absolute path of .: unsupported UNC path

### Steps to reproduce the issue

Steps to reproduce the issue
1. cd \\\\wsl.localhost\podman-machine-default\home\user
3. podman run -it -v .:/mydir ubuntu:latest

Error: getting absolute path of .: unsupported UNC path

Also:
1. cd c:\\
2. podman run -it -v \\\\wsl.localhost\podman-machine-default\home\user:/mydir ubuntu:latest

Error: getting absolute path of \\\\wsl.localhost\podman-machine-default\home\user: unsupported UNC path

### Describe the results you received

Error: getting absolute path of .: unsupported UNC path

### Describe the results you expected

Podman should be able to mount a path within WSL

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.5-1.fc36.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.5, commit: '
  cpuUtilization:
    idlePercent: 99.83
    systemPercent: 0.06
    userPercent: 0.11
  cpus: 20
  distribution:
    distribution: fedora
    variant: container
    version: "36"
  eventLogger: journald
  hostname: NB-MDEMONTIS
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.90.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 9380376576
  memTotal: 16599289856
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.1-1.fc36.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.1
      commit: f8a096be060b22ccd3d5f3ebe44108517fbf6c30
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-0.2.beta.0.fc36.x86_64
    version: |-
      slirp4netns version 1.2.0-beta.0
      commit: 477db14a24ff1a3de3a705e51ca2c4c1fe3dda64
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 4293644288
  swapTotal: 4294967296
  uptime: 23h 24m 43.00s (Approximately 0.96 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 0
    stopped: 5
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 19640291328
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 18
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.4.1
  Built: 1676629882
  BuiltTime: Fri Feb 17 11:31:22 2023
  GitCommit: ""
  GoVersion: go1.18.10
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.1
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
@n1hility PTAL

**Comment by n1hility** [comment]
You can bind a directory on the WSL instance by using its fully qualified unix path:

`podman run -it -v /home/user/dir:/mydir <container name>`

Feel free to reopen if this doesnt work for you

Thanks!

**Comment by mario-demontis-inpeco** [comment]
hi @n1hility 
I know it works using the unix path, but docker accepts also the windows one.
This prevents me to use podman as a drop-in replacement for docker.

In particular, I have this issue with CLion for Windows:
https://youtrack.jetbrains.com/issue/CPP-32837/Docker-toolchain-with-podman-and-project-sources-in-WSL-filesystem
In this use case it is crucial to mount a linux directory because the performance of the fs access is too bad otherwise

**Comment by n1hility** [comment]
Ah ok. Thanks for clarifying your use case. We can add support for these paths

**Comment by majidaldo** [comment]
...also visual studio code devcontainers.

**Comment by raist246** [comment]
This is actually the only thing missing if I want to combine CLion on Windows with podman instead of docker with WSLv2. Would be great if this could be implemented.

**Comment by SQLDBAWithABeard** [comment]
I am getting this error when trying to open a devcontainer in Windows. I would love to be able to use Podman but this is stopping me from being able to do so. I am a maintainer of dbachecks so am using the [devcontainer here](https://github.com/dataplat/dbachecks/blob/main/.devcontainer/devcontainer.json) with the [docker-compose here](https://github.com/dataplat/dbachecks/blob/main/.devcontainer/docker-compose.yml. Images are downloaded and dbachecks2 and dbachecks3 run but dbachecks1 fails with 
```
Creating dbachecks1 ... error

ERROR: for dbachecks1  Cannot create container for service dbachecks1: fill out specgen: getting absolute path of \\wsl.localhost\Ubuntu-22.04\run\user\1000
\wayland-0: unsupported UNC path
```
podman info 

```
host:
  arch: amd64
  buildahVersion: 1.31.0
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.7-2.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 98.44
    systemPercent: 0.68
    userPercent: 0.88
  cpus: 24
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: container
    version: "37"
  eventLogger: journald
  hostname: Beard-Desktop
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.90.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 44127449088
  memTotal: 50467405824
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.6-1.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.6
      commit: 73f759f4a39769f60990e7d225f561b4f4f06bcf
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 12884901888
  swapTotal: 12884901888
  uptime: 0h 1m 23.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 12019744768
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.6.0
  Built: 1689942107
  BuiltTime: Fri Jul 21 13:21:47 2023
  GitCommit: ""
  GoVersion: go1.19.10
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.0
```

Windows11 WSL 2 Ubuntu 22.04

**Comment by rasmusir** [comment]
Is there any progress on this? This practically stops you from using Podman to run VSCode devcontainers, which is a real bummer.

**Comment by raist246** [comment]
I think the fix shouldn't be too complicated.
When we run in  to this error, we need to check if the path starts with `\\wsl$\<podman-machine>\...` and just translate that to the root directory `/`.
Since there might be more than a single machine, we need to know which podman-machine currently runs. This information must be available somewhere. 
Could it then be enough to extend the switch statement at https://github.com/containers/podman/blob/348f9fe0d9aa3b636049a1234e32f26ee2c46309/pkg/specgen/winpath.go#L49 with an additional case:
```
// pseudocode since I'm not a go developer and I don't yet know how to get the machineName
case strings.HasPrefix(path, `\\wsl$\` + machineName ):
    path = "/" + path[7 + length(machineName)];
```

**Comment by doraeric** [comment]
> You can bind a directory on the WSL instance by using its fully qualified unix path:
> 
> `podman run -it -v /home/user/dir:/mydir <container name>`

Do you run this commnad from windows or wsl?

When running from windows, the home directory is the one in podman machine, not in default wsl home. I want to bind the directory in default wsl environment.
When running from wsl, `podman` is not found. Do you mean to install podman in default wsl environment?

Compare to docker, when running `docker` command in wsl, there is no need to install docker in wsl. The executable seems to be from docker desktop.
```
readlink -f /usr/bin/docker
/mnt/wsl/docker-desktop/cli-tools/usr/bin/docker
```

**Comment by inur93** [comment]
Is there any update on this issue?
I want to use podman for VS Code devcontainers and got the same issue.

**Comment by slogen** [comment]
Just a "me too" on. This still breaks many VSCODE-dev containers. here little more than a year after the initial report.

@raist246 did you ever manage to turn https://github.com/containers/podman/issues/17986#issuecomment-1721044478 into a patch?


```
....
[246000 ms] Start: Run: docker compose --project-name dotnet-postgres_devcontainer -f /workspaces/dotnet-postgres/.devcontainer/docker-compose.yml -f /tmp/devcontainercli-root/docker-compose/docker-compose.devcontainer.build-1719387082231.yml -f /tmp/devcontainercli-root/docker-compose/docker-compose.devcontainer.containerFeatures-1719387209058-0c4ff757-2966-45b2-83dc-151188d39172.yml up -d
[+] Running 1/15
 ⠿ db Pulled                                                                                                                                                9.4s
   ⠴ 12e1d6a2dd60 Download complete                                                                                                                         7.5s
...
   ⠋ 5b21e2e86aab Download complete                                                                                                                         0.1s
[+] Running 3/3
 ⠿ Network dotnet-postgres_devcontainer_default         Created                                                                                             0.0s
 ⠿ Volume "dotnet-postgres_devcontainer_postgres-data"  Created                                                                                             0.0s
 ⠿ Container dotnet-postgres_devcontainer-db-1          Created                                                                                             0.0s
 ⠋ Container dotnet-postgres_devcontainer-app-1         Creating                                                                                            0.0s
Error response from daemon: fill out specgen: getting absolute path of \\wsl.localhost\Ubuntu-22.04\mnt\wslg\runtime-dir\wayland-0: unsupported UNC path
[255597 ms] Error: Command failed: docker compose --project-name dotnet-postgres_devcontainer -f /workspaces/dotnet-postgres/.devcontainer/docker-compose.yml -f /tmp/devcontainercli-root/docker-compose/docker-compose.devcontainer.build-1719387082231.yml -f /tmp/devcontainercli-root/docker-compose/docker-compose.devcontainer.containerFeatures-1719387209058-0c4ff757-2966-45b2-83dc-151188d39172.yml up -d
[255597 ms]     at QtA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.369.0/dist/spec-node/devContainersSpecCLI.js:429:3355)
[255598 ms]     at runMicrotasks (<anonymous>)
[255598 ms]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
...
[255598 ms]     at async lrA (/root/.vscode-remote-containers/dist/dev-containers-cli-0.369.0/dist/spec-node/devContainersSpecCLI.js:661:13114)
[255679 ms] Exit code 1
[255679 ms] Start: Run: C:\Program Files\RedHat\Podman\podman.exe rm -f 5490b293fa299c7b326fe5320fc5569cfe21e25f847e123d261ff3f8fbdecbc6
[255683 ms] Command failed: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.369.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-614c2af4-3bd1-4ec2-9b28-5becdda8a1e91719386962248 --workspace-folder /workspaces/dotnet-postgres --workspace-mount-consistency cached --id-label vsc.devcontainer.volume.name=dotnet-postgres --id-label vsc.devcontainer.volume.folder=dotnet-postgres --id-label devcontainer.config_file=/workspaces/dotnet-postgres/.devcontainer/devcontainer.json --log-level debug --log-format json --config /workspaces/dotnet-postgres/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-81c2decc-3ff4-4172-8d3d-841ece4126f3.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=dotnet-postgres,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\Ubuntu-22.04\mnt\wslg\runtime-dir\wayland-0,target=/tmp/vscode-wayland-5f909e75-d0dd-4c79-b0ca-a8c954b57b8f.sock --skip-post-create --update-remote-user-uid-default off --mount-workspace-git-root --terminal-columns 161 --terminal-rows 22
[255683 ms] Exit code 1
```

**Comment by lukegeor** [comment]
I'm also running into this while trying to use podman with VSCode dev containers.

**Comment by ben-xD** [comment]
> You can bind a directory on the WSL instance by using its fully qualified unix path:
> 
> podman run -it -v /home/user/dir:/mydir <container name>

Hey @n1hility, I'm not sure if that would work? I've got a Ubuntu WSL alongside my `podman-machine-default` WSL. Doing something like `podman run -it -v /home/user/example:/example debian:bookworm bash` errors with:
```
Error: statfs /home/user/example: no such file or directory
```
even though `ls /home/user/example` is a real directory. I'm not sure how to mount files from my own WSL into a docker container on Podman.

**Comment by uttne** [comment]
This isn't a fundamental solution, but if you only need to use VS Code's Dev Containers, you can try disabling the "Mount Wayland Socket" option. By doing so, the socket won't be mounted, and the container should be able to start.

![Image](https://github.com/user-attachments/assets/c5942d25-c0f1-4155-b46e-a2ce138149f0)

https://github.com/microsoft/vscode-remote-release/issues/8157#issuecomment-1483099183
https://github.com/microsoft/vscode-remote-release/issues/8157#issuecomment-1485704718

**Comment by futuralogic** [comment]
Same issue with devcontainers. Modifying the suggested setting (`Mount wayland socket`) worked but I'd like to avoid custom settings if possible.

**Comment by atorigin** [comment]
I have the same problem, and wayland socket set to false also does not work. 

Does anyone have any other suggestions?

OS: windows10 22H2 , Build 19045.5608
podman desktop: v1.17.2

Note: Runs on WSL2 distro ubuntu 24.04

**Comment by JustinGrote** [comment]
I ran into this issue with vscode devcontainers on windows.
```
fill out specgen: getting absolute path of \\wsl.localhost\podman-machine-default\mnt\wslg\runtime-dir\wayland-0: unsupported UNC path.
```

It occurred because I tried to do X11 forwarding setup. Here's the relevant log lines (truncated for visibility:
```log
[2025-05-15T05:10:49.318Z] Start: Run in container: node /root/.vscode-remote-containers/dist/dev-containers-cli-0.413.0/dist/spec-node/devContainersSpecCLI.js up --container-session-data-folder /tmp/devcontainers-0c6dde6e-208c-4ec4-9a54-a309637944861747285841488 --workspace-folder /workspaces/vscode-powershell --workspace-mount-consistency cached --gpu-availability detect --id-label vsch.local.repository=https://github.com/PowerShell/vscode-powershell.git/tree/build/devcontainer --id-label vsch.local.repository.volume=vsc-remote-containers --id-label vsch.local.repository.folder=vscode-powershell --id-label devcontainer.config_file=/workspaces/vscode-powershell/.devcontainer/devcontainer.json --log-level debug --log-format json --config /workspaces/vscode-powershell/.devcontainer/devcontainer.json --override-config /tmp/devcontainer-3d6ab36b-3d68-4fe3-86ed-e63f907c9d78.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vsc-remote-containers,target=/workspaces,external=true --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\podman-machine-default\mnt\wslg\runtime-dir\wayland-0,target=/tmp/vscode-wayland-63307b84-39fd-47fd-ae2a-f77ffc7cb800.sock --skip-post-create 
[2025-05-15T05:11:00.162Z] Start: Starting container
[2025-05-15T05:11:00.162Z] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount type=volume,src=vsc-remote-containers,dst=/workspaces --mount type=volume,src=vscode,dst=/vscode --mount type=bind,src=\\wsl.localhost\podman-machine-default\mnt\wslg\runtime-dir\wayland-0,dst=/tmp/vscode-wayland-63307b84-39fd-47fd-ae2a-f77ffc7cb800.sock -l vsch.local.repository=https://github.com/PowerShell/vscode-powershell.git/tree/build/devcontainer -l vsch.local.repository.volume=vsc-remote-containers -l vsch.local.repository.folder=vscode-powershell -l devcontainer.config_file=/workspaces/vscode-powershell/.devcontainer/devcontainer.json --entrypoint /bin/sh vsc-vscode-powershell-c9422c9f370d8a452a9f3ca8827ebc0970d66df23329e44fcb5bf0daccadd4c8 -c echo Container started
[2025-05-15T05:11:00.205Z] docker: Error response from daemon: fill out specgen: getting absolute path of \\wsl.localhost\podman-machine-default\mnt\wslg\runtime-dir\wayland-0: unsupported UNC path.
See 'docker run --help'.
```

Unsetting `Forward Wayland Socket` resolves the issue as mentioned.

**Comment by jankap** [comment]
Podman would really benefit by fixing this because it enables better VSCode devcontainer integration. A huge use-case for Windows users which want to get rid of Docker (Desktop).

**Comment by doxxx** [comment]
I also ran into this when migrating from Docker Desktop to Podman on Windows. Strangely enough, initially my DevContainer worked in Podman but after I made some minor adjustments to the DevContainer configuration and rebuilt it, then this error occurred.

The workaround of disabling mounting the wayland socket also worked for me.

**Comment by cagrin** [comment]
> I also ran into this when migrating from Docker Desktop to Podman on Windows. Strangely enough, initially my DevContainer worked in Podman but after I made some minor adjustments to the DevContainer configuration and rebuilt it, then this error occurred.
> 
> The workaround of disabling mounting the wayland socket also worked for me.

I had the exact same problem. It worked at first, then stopped.
Mount Wayland Socket OFF works.

**Comment by halllo** [comment]
After disabling "Mount Wayland Socket" I was able to start the dev container on Windows.

Is that a problem of Podman or of DevContainers?

**Comment by hansmbakker** [comment]
This issues triggers https://github.com/microsoft/vscode-remote-release/issues/8157 for me. Having this issue solved would enable devcontainers to work in VS Code without first having to google what default setting to disable.

Furthermore, it would likely enable Wayland support via WSL2 on Windows in Podman.
