### ISSUE TITLE
Support mixed TTY on STD FDs

### ISSUE THREAD

**Issue by phemmer** [containers/podman#18001]
### Feature request description

Currently when you run a container, you have the option of allocating a TTY. However this causes all of STDIN, STDOUT, & STDERR to go to that TTY. You have no option of only allowing only some of those standard file descriptors to go to the TTY. That may be desired as you may be running an application which you want to pipe data to its STDIN, but which also behaves differently when STDOUT or STDERR is a TTY, and thus you want STDOUT/STDERR to be a TTY.

For example consider this scenario on the host which we want to mimic (pretend `sh` is some arbitrary application):
```
$ sh -c 'test -t 0 && echo 0; test -t 1 && echo 1; test -t 2 && echo 2; cat' <<<"hello world"
1
2
hello world
```

When we run this in a container without `--tty` we get:
```
$ podman run --rm -i busybox sh -c 'test -t 0 && echo 0; test -t 1 && echo 1; test -t 2 && echo 2; cat' <<< "hello world"
hello world
```
When we run with `--tty` we get:
```
$ podman run --rm -t -i busybox sh -c 'test -t 0 && echo 0; test -t 1 && echo 1; test -t 2 && echo 2; cat' <<< "hello world"
WARN[0000] The input device is not a TTY. The --tty and --interactive flags might not work properly 
hello world
0
1
2
hello world
```
^ note this also causes a whole mess of a situation due to what that warning is about

### Suggest potential solution

I'm not sure what the implementation for this would look like, but I can see 2 desired new modes.
1. An "automatic mode" where podman mimics what it sees. Meaning if podman sees it has FD 0 not a tty, and FD 1 & 2 are a tty, then thats what it will set up inside the container.
2. A manual mode where you can explicitly specify which FDs are a TTY, and which are not. There is the question of whether we want the possibility of allocating separate TTYs for each FD. While I don't have this need, and don't see a use case, I imagine the situation this issue is about came up because someone didn't consider the use case.

**Comment by giuseppe** [comment]
I don't think Podman can solve this issue, since the OCI runtime specs just accept a bool for tty mode

**Comment by Luap99** [comment]
> I don't think Podman can solve this issue, since the OCI runtime specs just accept a bool for tty mode

@giuseppe Could we use `--log-driver passthrough` for this? Right now it errors out when the fd is a tty, if we instead remove this check it should be possible to just pass down the fds as is, right? The only reason we block this is because of potential security concerns but I think it could also just be documented instead of blocking it completely.

**Comment by giuseppe** [comment]
would that work though?  The container process is not a child of the shell, I think it will just clobber the terminal.

**Comment by Luap99** [comment]
I do not know, if I patch out the check (both podman and conmon) the reproducer works.
The only thing is I see is this `sh: can't access tty; job control turned off` message when I launch an interactive shell.

**Comment by rhatdan** [comment]
@giuseppe @phemmer @Luap99 What are we to do with this issue?

**Comment by giuseppe** [comment]
I am fine to drop the check and let users deal with it, if it solves the issue reported here.

@phemmer would that be enough for you?

**Comment by phemmer** [comment]
Seems fine with me.

https://github.com/containers/podman/issues/18001#issuecomment-1494097441
> the OCI runtime specs just accept a bool for tty mode

Should this be raised somewhere so that it might be addressed there in the future? Or just stick with the passthrough solution?

**Comment by Luap99** [comment]
we have --log-driver passthrough-tty so I think thi sis good enough, if you want a proper solution you likely need to file this against the oci runtime spec and ask them about it
