### ISSUE TITLE
systests: remote: exec: empty output

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#18025]
There seem to be a number of bugs in podman-remote-exec; this is a new variant:
```
not ok 377 podman update - test all options
...
# podman-remote --url unix:/tmp/podman_tmp_mqPG exec <cid> cat /sys/fs/cgroup/cpuset.mems
#/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#|     FAIL: --cpuset-mems=0 (cpuset.mems)
#| expected: = 0
#|   actual:   ''
```
Seen in [f37 aarch64 root boltdb](https://api.cirrus-ci.com/v1/artifact/task/5351589062377472/html/sys-remote-fedora-37-aarch64-root-host-boltdb.log.html). Only one instance so far.

**Comment by rhatdan** [comment]
@edsantiago still happening?

**Comment by edsantiago** [comment]
I'm not sure. I thought I saw it this week, but lost the link. It hasn't fallen off my radar.

**Comment by edsantiago** [comment]
The other one I saw was in a `v3.0.1-rhel` PR, hence is irrelevant. I'm going to close and hope this was a one-off.
