### ISSUE TITLE
Quadlet should search subdirectories for the unit search path

### ISSUE THREAD

**Issue by Nitrousoxide** [containers/podman#18032]
### Feature request description

Right now Quadlet will search:
/etc/containers/systemd/
/usr/share/containers/systemd/

for rootful container definitions and:
~/.config/containers/systemd/

for non-root container definitions.  However, it will not recursively check subdirectories under these paths.  For a sufficiently large set of containers/networks/volumes this can create a very long and flat list with no (or very little) organization which makes parsing how the containers might be grouped difficult.  It also leads to excessively long lists when attempting to navigate the path and pick out the *.container files to edit.  Allowing the user to create subdirectories to group arbitrary containers/pods together for ease of reference by a human would make management of the files significantly easier. 

Quadlet could still pull together the list of all the relevant .container .volume and .kube files in the origin path and treat them as a flat list when spinning up services, but allowing subdirectories will make human readability much better for larger deployments.

### Suggest potential solution

Allow Quadlet to search subdirectories for *.container *.volume, *.network and *.kube files in the search path.

**Comment by vrothberg** [comment]
Thanks for reaching out, @Nitrousoxide!

The request sounds reasonable to me.  @ygalblum @rhatdan @alexlarsson WDYT?

**Comment by rhatdan** [comment]
I am fine with this change.

**Comment by harikannan512** [comment]
@vrothberg I'd like to have a crack at this, can you please assign this issue?

**Comment by rhatdan** [comment]
@harikannan512 any progress?

**Comment by harikannan512** [comment]
@rhatdan apologies, a bit busy with work, so no progress. Need to work on linting issues to satisfy checks

**Comment by harikannan512** [comment]
@rhatdan please take a look at this new PR. The old one had some issues with a bad merge on my end. I'll get to whatever changes are/would be required

**Comment by rhatdan** [comment]
This has been merged so closing.
