### ISSUE TITLE
[sys] kube play read-only: racy status checks

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#18047]
Flake seen in my hammer-sqlite PR, `f37 aarch64 root`, both [local](https://api.cirrus-ci.com/v1/artifact/task/6384574364647424/html/sys-podman-fedora-37-aarch64-root-host-sqlite.log.html#t--00535) and [remote](https://api.cirrus-ci.com/v1/artifact/task/4625355760205824/html/sys-remote-fedora-37-aarch64-root-host-sqlite.log.html#t--00534):
```
not ok 535 podman kube play read-only from containers.conf
...
# podman inspect --format {{.State.ExitCode}} pod1-test2
0
#/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#|     FAIL: Container / should be read/only   <---- poor message. Should read "exit status from touch /file on RO container"
#| expected: '1'
#|   actual: '0'
```
Root cause: when `podman kube play` runs containers, a container that exits nonzero seems to be infinite-looped: it keeps retrying forever. The above `inspect` caught it in a moment when the container had just started.

Solution: I give up. I've spent an hour trying to play with `restartPolicy` and `container create --restart=no` (which does not get seen by `podman generate kube`) and looking at man pages. I can find no way to tell podman-kube to just run that container once.

I'm astonished that this doesn't flake more often.

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by edsantiago** [comment]
One of our most popular flakes this week. I'm hoping #17627 will let me find a way to fix this.


* debian-12 : sys podman debian-12 root host boltdb
  * PR #17954
    * [04-06 17:04](https://api.cirrus-ci.com/v1/artifact/task/4606272280985600/html/sys-podman-debian-12-root-host-boltdb.log.html#t--00535) in [sys] podman kube play read-only from containers.conf
* debian-12 : sys remote debian-12 root host boltdb [remote]
  * PR #17954
    * [04-07 15:06](https://api.cirrus-ci.com/v1/artifact/task/4575167658065920/html/sys-remote-debian-12-root-host-boltdb.log.html#t--00534) in [sys] podman kube play read-only
* fedora-37-aarch64 : sys podman fedora-37-aarch64 root host boltdb
  * PR #18061
    * [04-06 08:39](https://api.cirrus-ci.com/v1/artifact/task/4840377056755712/html/sys-podman-fedora-37-aarch64-root-host-boltdb.log.html#t--00534) in [sys] podman kube play read-only
* fedora-37-aarch64 : sys podman fedora-37-aarch64 root host sqlite
  * PR #17831
    * [04-07 16:06](https://api.cirrus-ci.com/v1/artifact/task/6606765773553664/html/sys-podman-fedora-37-aarch64-root-host-sqlite.log.html#t--00536) in [sys] podman kube play read-only from containers.conf
    * [04-06 16:57](https://api.cirrus-ci.com/v1/artifact/task/6382579553665024/html/sys-podman-fedora-37-aarch64-root-host-sqlite.log.html#t--00535) in [sys] podman kube play read-only
    * [04-04 12:10](https://api.cirrus-ci.com/v1/artifact/task/6384574364647424/html/sys-podman-fedora-37-aarch64-root-host-sqlite.log.html#t--00535) in [sys] podman kube play read-only from containers.conf
* fedora-37-aarch64 : sys remote fedora-37-aarch64 root host boltdb [remote]
  * PR #18151
    * [04-11 21:32](https://api.cirrus-ci.com/v1/artifact/task/5829429406990336/html/sys-remote-fedora-37-aarch64-root-host-boltdb.log.html#t--00537) in [sys] podman kube play read-only from containers.conf
  * PR #18143
    * [04-12 06:15](https://api.cirrus-ci.com/v1/artifact/task/6725055078465536/html/sys-remote-fedora-37-aarch64-root-host-boltdb.log.html#t--00537) in [sys] podman kube play read-only from containers.conf
  * PR #18140
    * [04-11 10:02](https://api.cirrus-ci.com/v1/artifact/task/5449581727580160/html/sys-remote-fedora-37-aarch64-root-host-boltdb.log.html#t--00536) in [sys] podman kube play read-only from containers.conf
  * PR #18105
    * [04-08 01:39](https://api.cirrus-ci.com/v1/artifact/task/4746923869995008/html/sys-remote-fedora-37-aarch64-root-host-boltdb.log.html#t--00536) in [sys] podman kube play read-only from containers.conf
  * PR #18078
    * [04-06 17:26](https://api.cirrus-ci.com/v1/artifact/task/4874276789026816/html/sys-remote-fedora-37-aarch64-root-host-boltdb.log.html#t--00535) in [sys] podman kube play read-only from containers.conf
    * [04-06 11:07](https://api.cirrus-ci.com/v1/artifact/task/5164233789276160/html/sys-remote-fedora-37-aarch64-root-host-boltdb.log.html#t--00534) in [sys] podman kube play read-only
  * PR #18066
    * [04-05 12:01](https://api.cirrus-ci.com/v1/artifact/task/5435058228559872/html/sys-remote-fedora-37-aarch64-root-host-boltdb.log.html#t--00534) in [sys] podman kube play read-only
  * PR #17954
    * [04-12 07:44](https://api.cirrus-ci.com/v1/artifact/task/5928382668472320/html/sys-remote-fedora-37-aarch64-root-host-boltdb.log.html#t--00537) in [sys] podman kube play read-only from containers.conf
    * [04-07 15:10](https://api.cirrus-ci.com/v1/artifact/task/5701067564908544/html/sys-remote-fedora-37-aarch64-root-host-boltdb.log.html#t--00535) in [sys] podman kube play read-only from containers.conf
* fedora-37-aarch64 : sys remote fedora-37-aarch64 root host sqlite [remote]
  * PR #17831
    * [04-05 10:43](https://api.cirrus-ci.com/v1/artifact/task/6700167554924544/html/sys-remote-fedora-37-aarch64-root-host-sqlite.log.html#t--00535) in [sys] podman kube play read-only from containers.conf
    * [04-04 11:59](https://api.cirrus-ci.com/v1/artifact/task/4625355760205824/html/sys-remote-fedora-37-aarch64-root-host-sqlite.log.html#t--00534) in [sys] podman kube play read-only
