### ISSUE TITLE
[apiv2] play/kube test: name is in use, pod already exists

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#18041]
Two slightly different variants. Possibly a race in the test itself:
```
not ok 1202 [80-kube] POST libpod/play/kube : status
#  expected: 200
#    actual: 500
#  response:
     {"cause":"pod already exists",
      "message":"playing YAML file: adding pod to state: name \"peacefulgoldberg-pod\" is in use: pod already exists",
      "response":500}
```
and
```
# response:
     {"cause":"pod already exists",
      "message":"playing YAML file: encountered while bringing up pod modestfeistel-pod-deployment-pod: adding pod to state: name \"modestfeistel-pod-deployment-pod\" is in use: pod already exists",
      "response":500}
```

### [APIv2] [80-kube] POST libpod/play/kube : status
* fedora-37 : APIv2 test on fedora-37 (rootless)
  * PR #17993
    * [04-03 14:43](https://api.cirrus-ci.com/v1/task/6489412033314816/logs/main.log#t--01209)
  * PR #17925
    * [03-25 06:39](https://api.cirrus-ci.com/v1/task/5563134824415232/logs/main.log#t--01202)

**Comment by vrothberg** [comment]
https://github.com/containers/podman/pull/18043 as an attempt to help debug the flakes

**Comment by vrothberg** [comment]
@edsantiago, did it flake after #18043?

**Comment by edsantiago** [comment]
The last flake I see was the April 3 one

**Comment by rhatdan** [comment]
@edsantiago can we close?

**Comment by edsantiago** [comment]
I don't know. There are more flakes than I can handle right now, and I'm far behind on my sorting.

**Comment by Luap99** [comment]
I assume this can be closed
