### ISSUE TITLE
CI: Verify Win Installer Build task failing on `main`

### ISSUE THREAD

**Issue by cevich** [containers/podman#18048]
### Issue Description

When Cirrus-CI runs the daily job on the `main` branch, this task fails with the error:

```
Remove-Item : Cannot find path 'Env:\CIRRUS_PR_BODY' because it does not exist.
At C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\contrib\c
irrus\win-installer-main.ps1:38 char:1
+ Remove-Item Env:\CIRRUS_PR_BODY
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Env:\CIRRUS_PR_BODY:String) [Re 
   move-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.Remov 
   eItemCommand
```

[Example log](https://cirrus-ci.com/task/6367869559111680)

### Steps to reproduce the issue

Steps to reproduce the issue
1. Wait a day
2.
3.

### Describe the results you received

Task fails

### Describe the results you expected

All tasks pass

### podman info output

```yaml
N/A
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by cevich** [comment]
@n1hility PTAL when you have a moment.  Seems like this error should just be ignored, unless you know a better way to fix it.

**Comment by n1hility** [comment]
@cevich ah yes sorry about that will send a patch
