### ISSUE TITLE
Cirrus:  aarch64: 404 in clone

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#18040]
Occasionally the CI `clone` job will 404:
```
cd /tmp
echo "$ARTCURL/build_aarch64/repo/repo.tbz"
curl --retry 5 --retry-delay 8 --fail --location -O --url https://api.cirrus-ci.com/v1/artifact/build/5921399689183232/build_aarch64/repo/repo.tbz
time $ARTCURL/build_aarch64/repo/repo.tbz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0    70    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
```
Seems to be aarch64 only. (Other arches also have clone flakes, but I haven't seen this 404).

### sys remote fedora-37-aarch64 root host boltdb: unknown failure
* fedora-37-aarch64 : sys remote fedora-37-aarch64 root host boltdb [remote]
  * PR #17993
    * [04-04 01:10](https://api.cirrus-ci.com/v1/task/6647048406040576/logs/clone.log)
    * [04-04 01:10](https://api.cirrus-ci.com/v1/task/4808942258225152/logs/clone.log)
    * [04-03 14:50](https://api.cirrus-ci.com/v1/task/6518674450808832/logs/clone.log)
    * [04-03 14:49](https://api.cirrus-ci.com/v1/task/5398696498561024/logs/clone.log)
  * PR #17951
    * [03-27 17:40](https://api.cirrus-ci.com/v1/task/4562637627850752/logs/clone.log)
    * [03-27 17:39](https://api.cirrus-ci.com/v1/task/6489988766892032/logs/clone.log)

### sys podman fedora-37-aarch64 root host boltdb: unknown failure
* fedora-37-aarch64 : sys podman fedora-37-aarch64 root host boltdb
  * PR #17993
    * [04-04 01:10](https://api.cirrus-ci.com/v1/task/5999876157210624/logs/clone.log)
    * [04-04 01:09](https://api.cirrus-ci.com/v1/task/6281841162846208/logs/clone.log)
    * [04-03 14:50](https://api.cirrus-ci.com/v1/task/5686719421349888/logs/clone.log)
    * [04-03 14:49](https://api.cirrus-ci.com/v1/task/5680171475271680/logs/clone.log)
  * PR #17951
    * [03-27 17:40](https://api.cirrus-ci.com/v1/task/6040278478356480/logs/clone.log)
    * [03-27 17:39](https://api.cirrus-ci.com/v1/task/5082613883338752/logs/clone.log)

**Comment by cevich** [comment]
Thanks @edsantiago I'll take a look into it.

**Comment by cevich** [comment]
Examining a [recent occurence](https://cirrus-ci.com/task/5184715993382912), I see the aarch64 task isn't depending on the `build_aarch64` task (where the archive is being downloaded from).  Looking at [that task](https://cirrus-ci.com/task/6114354618171392) I see there was [a failure in pre-build](https://cirrus-ci.com/task/6066841810894848?logs=prebuild#L176): `dial tcp: lookup cdn03.quay.io: no such host`.

I haven't examined the other reported incidents yet, but the missing dependency is definitely a problem, and certainly one that will cause a 404.  Opened https://github.com/containers/podman/pull/18069

**Comment by cevich** [comment]
Confirmed: Looked at a few more failure logs.  The build_aarch64 tasks are failing in pre-build because of the damn dumb infuriating systemd-resolved + quay DNS problem.  Since the system-test dependencies are wrong, the cirrus artifact-download API will not work right, leading to a 404.  So #18069 will definitely fix this.
