### ISSUE TITLE
Support for usernames in quadlet's user directive

### ISSUE THREAD

**Issue by jackete2** [containers/podman#18096]
### Feature request description

The ability to set the User= directive in a .container file to a username instead of a numeric uid

### Have you considered any alternatives?

Manually specifying the numeric uid, which is annoying when you want to use the same file on multiple machines with potentially different username:uid mappings

### Additional context

If you try to do this now the container will run as root instead without giving any error, which is confusing

**Comment by vrothberg** [comment]
Thanks for reaching out, @jackete2.

The `User=` field only takes numeric values.  Do you want to run with the same user ID inside the container as the user starting/creating it?

**Comment by jackete2** [comment]
@vrothberg No, because the container is started as root (with a file in /etc/containers/systemd) as it needs to be automatically started on boot and needs to bind to privileged ports on the host. However I would like it to run with the same user ID as another user on the host

**Comment by vrothberg** [comment]
@jackete2, changing the user on the host is currently not supported (see https://github.com/containers/podman/issues/12778). The `User=` field of Quadlet in the `[container]` table controls the user inside the container but not outside.

**Comment by jackete2** [comment]
@vrothberg  Seems like I misinterpreted the meaning of that field, is setting User=example NoNewPrivileges=true not enough then to get an unprivileged container?

**Comment by vrothberg** [comment]
@jackete2 what's important is that `User=example` would run the `example` user _inside_ the container (i.e., coming from container image).  But only numeric values are supported for `User=`.

**Comment by vrothberg** [comment]
To elaborate/compare:

The snippet below would attempt to run the command _inside_ the container as user `123`.
```
[Container]
User=123
```

What https://github.com/containers/podman/issues/12778 is about (and you seem to be interested in) is setting the user executing `podman`. Let's consider the snippet below:
```
[Service]
User=host-123
```
That would attempt to run `podman run ...` as host user `host-123`.  Notice that it's under the `[Service]` table.  And that is currently not supported as outlined in https://github.com/containers/podman/issues/12778.

**Comment by jackete2** [comment]
This is indeed a duplicate of that issue then, sorry for wasting your time

**Comment by vrothberg** [comment]
No worries at all.  Thanks for reaching out, @jackete2 !
