### ISSUE TITLE
Disable Dependabot after Renovate trial run

### ISSUE THREAD

**Issue by cevich** [containers/podman#18139]
### Feature request description

This repository is migrating over to Renovate for dependency/security automated updates, given it's enhanced configuration/capabilities and centralized management. For the time being, both tools will be enabled so that we may catch any "missing" update problems.

### Suggest potential solution

After 30-ish days, the .github/dependabot.yml file should be removed and Dependabot disabled in the repo. settings.

### Have you considered any alternatives?

Renovate is the alternative

**Comment by cevich** [comment]
Good catch @Luap99 

I believe the default ignore list includes `test`.  Let me see how best to override that.

**Comment by Luap99** [comment]
Renovate seems to propose updates for retracted releases, https://github.com/containers/podman/pull/18296
Is there any setting to turn that off?

**Comment by cevich** [comment]
Thanks @Luap99 IIRC there was an issue fixed WRT rollback PRs but I still have [a workaround in the default configuration](https://github.com/containers/automation/blob/394eeb9da7edd9f7b9e8a7569183854c723903ed/renovate/defaults.json5#L137-L146).  I'll remove that, but my memory is far from perfect, so please let me know if the problem keeps happening or gets worse.

Opened https://github.com/containers/automation/pull/134
