### ISSUE TITLE
podman rm --all not working with containers that have dependencies

### ISSUE THREAD

**Issue by Luap99** [containers/podman#18180]
### Issue Description

Try to use `podman rm -fa` when you have containers with dependencies, e.g. `--network container:xxx` or any other namespace flag which supports `container:`.  

### Steps to reproduce the issue

1. `podman run --name test1 -d alpine top`
2. `podman run --network container:test1 -d alpine top`
3. `podman rm -fa`

### Describe the results you received

```
a32636dc3e18c522d3f16340801ffb76d4e8acad8f02b32723ce91721dbc50a0
Error: container 8c9cbe82f02577e166187ec899afc6497e3bd551fae1b05df5a437b8ef90d081 has dependent containers which must be removed before it: a32636dc3e18c522d3f16340801ffb76d4e8acad8f02b32723ce91721dbc50a0: container already exists
```

### Describe the results you expected

All containers removed without errors.

### podman info output

```yaml
tested with latest main
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional information

This is causing issues in the e2e integration tests because we only do `rm -fa` as cleanup thus some processes are leaked.

**Comment by vrothberg** [comment]
Ouch!

Can you point where this fails in the e2e tests?  I think this error should be fatal (i.e., let the e2e tests fail).

**Comment by Luap99** [comment]
I pushed some changes for it to https://github.com/containers/podman/pull/18163.
The problem is in `(p *PodmanTestIntegration) Cleanup()` where we only run `pod rm -fa` and `rm -fa`

**Comment by Luap99** [comment]
I think we need to order the container so that they are removed in the right order, looks like we already handle this for pods (https://github.com/containers/podman/commit/e19e0de5faf31137fa0197ea014d4615e641d33a)

Following the comment it should not be used for containers: https://github.com/containers/podman/blob/5e6c0647c0c9e14e2d9f9a45868bce8b21fdf7da/libpod/container_graph.go#L285-L291

I am not sure why?
@mheon Can you take a look please? This is pretty important to fix broken e2e tests.

**Comment by edsantiago** [comment]
OMG if this gets fixed, can you add like actual error checking to cleanup? This has been a flake nightmare for years. #11597

**Comment by Luap99** [comment]
I already have it in my ginkgo update PR, so I could find the problematic ones.

**Comment by mheon** [comment]
We could definitely restructure remove-all to do an ordered removal, but in the meantime, you could just add `--depends` to remove all dependencies and solve the errors that way?

**Comment by mheon** [comment]
Alternatively, we could make the combination of `--all` and `--force` imply `--depends` because if you want every container removed, dependencies are included in "every container".

**Comment by Luap99** [comment]
I only see a `--depend` option and it is not working:
```
$ bin/podman run --name test1 -d alpine top
8d09a1feea5963ecacf888264abd24563ee9f6224b4f39e01f5294494a54385c
$ bin/podman run --network container:test1 -d alpine top
617d47aa6ae7e40abed4dd71cc617b98e2b56890a5f8db6b592376a6bd31c1fa
$ bin/podman rm -fa --depend
617d47aa6ae7e40abed4dd71cc617b98e2b56890a5f8db6b592376a6bd31c1fa
Error: container 8d09a1feea5963ecacf888264abd24563ee9f6224b4f39e01f5294494a54385c has dependent containers which must be removed before it: 617d47aa6ae7e40abed4dd71cc617b98e2b56890a5f8db6b592376a6bd31c1fa: container already exists
$ bin/podman ps
CONTAINER ID  IMAGE                            COMMAND     CREATED         STATUS         PORTS       NAMES
8d09a1feea59  docker.io/library/alpine:latest  top         33 seconds ago  Up 34 seconds              test1
```

**Comment by mheon** [comment]
I checked, and it's already set by default on `rm --all` - so our actual bug is that `--depend` is broken.

**Comment by mheon** [comment]
`--depend` works fine outside of `rm -fa` - interesting.

**Comment by Luap99** [comment]
@mheon When you open a PR please also revert: https://github.com/containers/podman/pull/18163/commits/c4b9f4b34e75da3df5b40fd8e8d42dde224cbd1c

**Comment by mheon** [comment]
Ack
