### ISSUE TITLE
podman-remote-static-linux_arm64.tar.gz don't have same path inside archive

### ISSUE THREAD

**Issue by Nemric** [containers/podman#18215]
### Issue Description

I build an image that use podman remote to drive a podman socket
I use Jenkins to build this image that download latest podman-remote-static-linux_arm64.tar.gz and untargz the file

sometimes, the file is in /bin and sometimes file is without path (/) in archive

I have to "debug" my jenkinsfile on, let's say, every podman release (it was a bit stable with /bin/podman-remote-static-linux_arm64 since some release)

Is there a way for you to make it more "stable"

### Steps to reproduce the issue

Steps to reproduce the issue (extract from with jenkinsfile and Containerfile with full names)
1. curl -LO https://github.com/containers/podman/releases/latest/download/podman-remote-static-linux_arm64.tar.gz
2. tar -xvf podman-remote-static-linux_arm64.tar.gz --directory /
3. mv /bin/podman-remote-static-linux_arm64 /bin/podman

It was working well on previous release (with /bin path in archive) and the one before, path in archive is not always the same ...

### Describe the results you received

file doesn't exists

### Describe the results you expected

Archive file path should be always the same in archive

### podman info output

```yaml
not relevant (podman 4.4.4)
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

not relevant

### Additional information

not relevant

**Comment by lsm5** [comment]
ah I see the issue RE: v4.4.4 v/s v4.5.0.

@mheon @ashley-cui looking at item 7 in RELEASE_PROCESS.md , the tarring happens inside bin/ , so afaict, there should be no `bin/` on untarring it. Let me know how you'd prefer this. I guess we could put all those steps into a script to make things easier.

**Comment by ashley-cui** [comment]
I think historically it's been in `bin/` for the past few releases,  I'm okay with changing it as long as we're consistent for the future so we definitely should make a makefile target for it. I'm also in the process of updating RELEASE_PROCESS.md a little, as some of the steps can be consolidated.

**Comment by Nemric** [comment]
> > ### podman info output
> > ```yaml
> > not relevant (podman 4.4.4)
> > ```
> 
> @Nemric just confirming that you didn't see this in v4.4.4 and you're seeing this only now in v4.5.0 ?

Hi, thanks :)
You're right, I'm know using podman 4.4.4 packaged in Fedora CoreOS and building an image that will content latest podman remote ;) so I use both ;p (see it in action here [Jenkins-Agent](https://github.com/Relativ-IT/Jenkins-Agent))
It's not relevant as the issue is not about podman or podman remote itself

As a workaround I now use `tar -xf $PODMAN_REMOTE_ARCHIVE --transform 's?.*/??g'` that remove the path from file
But the more readable it is the best it is :)

let me know
regards

**Comment by ashley-cui** [comment]
Sure, for consistency's sake, shouldn't be a problem

**Comment by Nemric** [comment]
> @Nemric #18238 should make our release process smoother. Going forward, the `bin/` will be preserved in release artifacts.
> 
> @ashley-cui @mheon I could edit the v4.5.0 release with the `remote-static-linux` tarballs rebuilt. WDYT?

Really ?
Don't you think it's easier/more readable to add `--directory /usr/bin` or `--directory /bin` than `--strip-components=2 --directory /usr/bin` or any `--transform 's?.*/??g'` ? Shouldn't this artefact be "standalone" ?
up to you girls & guys ;) consistency first 💪 

Thanks for all,
regards.

**Comment by lsm5** [comment]
the artifacts are standalone fwiw, unless I'm misreading you. Anyway, I uploaded the updated files to the release few mins ago. PTAL.

**Comment by ashley-cui** [comment]
I don't mind either way, just as long as we're consistent going forward

**Comment by Nemric** [comment]
> the artifacts are standalone fwiw, unless I'm misreading you. Anyway, I uploaded the updated files to the release few mins ago. PTAL.

Is my english so poor 😢 😄 ?
I meant that 'podman remote' doesn't need an installation process and can be used as is from any directory, in $PATH or not

Right, a choice was made a and it's a good choice ;)

Closing issue ...

Thanks,
Regards
