### ISSUE TITLE
Podman has terribly slow internet connection

### ISSUE THREAD

**Issue by playXE** [containers/podman#18237]
### Issue Description

Describe your issue

### Steps to reproduce the issue

Steps to reproduce the issue
1. Clone https://github.com/DavidBurela/riscv-emulator-docker-image
2. Run `podman build .` inside it
3. Everything from apt to git takes eternity to finish, Git does not finish and there are missing bytes always

### Describe the results you received

Everything from apt to Git take eternity to finish. Git fails with missing bytes:
```
STEP 5/8: RUN git clone https://github.com/qemu/qemu && mkdir /root/qemu/build  && cd /root/qemu/build && ../configure --target-list=riscv64-softmmu && make -j3 && make install && rm /root/qemu -r
Cloning into 'qemu'...
error: 780 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Error: building at STEP "RUN git clone https://github.com/qemu/qemu && mkdir /root/qemu/build  && cd /root/qemu/build && ../configure --target-list=riscv64-softmmu && make -j3 && make install && rm /root/qemu -r": while running runtime: exit status 128
```

### Describe the results you expected

Successful build of image. 

### podman info output

```yaml
[root@archlinux riscv-emulator-docker-image]# podman info
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.7-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: f633919178f6c8ee4fb41b848a056ec33f8d707d'
  cpuUtilization:
    idlePercent: 98.96
    systemPercent: 0.59
    userPercent: 0.46
  cpus: 12
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: archlinux
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.2.11-arch1-1
  linkmode: dynamic
  logDriver: journald
  memFree: 15112036352
  memTotal: 16667324416
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.8.3-1
    path: /usr/bin/crun
    version: |-
      crun version 1.8.3
      commit: 59f2beb7efb0d35611d5818fd0311883676f6f7e
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.2.0-1
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 1h 48m 43.00s (Approximately 0.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 250375106560
  graphRootUsed: 6933721088
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 4
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.4.4
  Built: 1680009696
  BuiltTime: Tue Mar 28 13:21:36 2023
  GitCommit: c8223435f49a860c8ac4281a85db39232745a7cb-dirty
  GoVersion: go1.20.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.4

```
```


### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

I am running Podman on Arch Linux x86_64.

```
podman version
Client:       Podman Engine
Version:      4.4.4
API Version:  4.4.4
Go Version:   go1.20.2
Git Commit:   c8223435f49a860c8ac4281a85db39232745a7cb-dirty
Built:        Tue Mar 28 13:21:36 2023
OS/Arch:      linux/amd64

```

### Additional information

_No response_

**Comment by Luap99** [comment]
Do you run as root or rootless? Does it work better in a container with `podman run`? Have you tried `--network=host`?

This sounds like something on your host is setup wrong. Do you have smaller MTU than 1500 by any chance?

**Comment by playXE** [comment]
> Do you run as root or rootless? Does it work better in a container with `podman run`? Have you tried `--network=host`?
> 
> This sounds like something on your host is setup wrong. Do you have smaller MTU than 1500 by any chance?

I run rootless, I haven't tried `--network host` yet. Also I run podman on my home server where ethernet is connected through WiFi,  MTU is 1500

**Comment by sbrivio-rh** [comment]
@playXE note that slirp4netns doesn't support TCP window scaling (meaning that TCP windows are limited to 64 KiB), so the throughput will dramatically decrease as the RTT of the peer increases.

That probably doesn't explain the missing bytes, but if git happens to contact a server with 200ms RTT for you (you can quickly check with `ping` or `traceroute`) you should expect abysmal throughput. See also https://github.com/containers/podman/issues/17865#issuecomment-1477638812

Would you have a chance to try with [pasta](https://passt.top/passt/about/#pasta-pack-a-subtle-tap-abstraction) (`--net=pasta`) as network back-end for Podman? The AUR [package](https://aur.archlinux.org/packages/passt-git) is up to date, and given the setup you described I don't expect that you need to change anything else to use it.

**Comment by Luap99** [comment]
@sbrivio-rh podman build (buildah) does not support pasta.
This on my TODO to migrate all rootless networking code to c/common then make buildah/podman use the same code.

**Comment by rhatdan** [comment]
@Luap99 Does podman build support pasta now?

**Comment by Luap99** [comment]
yes since v4.6

**Comment by rhatdan** [comment]
I guess we have pasta support in buildah now, so I am going to close this issue.
