### ISSUE TITLE
podman container ls --format="{{.State}}" returns the wrong information

### ISSUE THREAD

**Issue by mdhirt** [containers/podman#18244]
Podman version 4.1.1 on RedHat 8.5

Specifying a format to include container State in the output of podman container ls returns the value from the Status field and not the State field.

Actual Result.
podman container ls -a --format="{{json .Names}} {{json .State}} {{json .Status}}"
"test-container" "Up 3 weeks ago" "Up 3 weeks ago"
"stopped-container" "Exited (0) 16 Seconds ago" "Exited (0) 16 Seconds ago"

Expected Result.
podman container ls --format="{{json .Names}} {{json .State}} {{json .Status}}"
"test-container" "running" "Up 3 weeks ago"
"stopped-container" "exited" "Exited (0) 16 seconds ago"

Additional information.
Running podman container ls --format=json does display the correct state=value, however when scripting automated health checks it is useful to limit the returned values using the --filter="{{ }}" option.
podman container ls --format=json
[
  {
    ...
    "Names": [
      "test-container"
    ],
    ...
    "State": "running"
    "Status": "Up 3 weeks ago"
    ...
  },
  {
    ...
    "Names": [
      "stopped-container"
    ],
    ...
    "State": "exited"
    "Status": "Exited (0) 16 seconds ago"
    ...
  }
]

**Comment by vrothberg** [comment]
Thanks for reaching out, @mdhirt!

Since you mention running on RHEL.  If you desire a backport to RHEL, please reach out through the Red Hat customer channels.  We can fix it upstream but downstream is up to the individual distributions/vendors.

**Comment by Luap99** [comment]
`--format "{{.ListContainer.State}}"` should result in the output you want

**Comment by mdhirt** [comment]
Thank you @Luap99 this provides exactly what I need.

Should I close this issue now or is it still a bug that .State and .Status both return the output for .Status?

**Comment by vrothberg** [comment]
> I don't know, looking at the code history podman has this behavior at least since v2.0. So far nobody complained, changing the output now could break existing users that want the current output. Although we try to be docker compatible, if this works with docker it is a valid reason for us to change it.

It works with Docker, so I think we should change it.

**Comment by baude** [comment]
@jwhonce do you recall any history on this one by chance?
