### ISSUE TITLE
Bind mount in a volume?

### ISSUE THREAD

**Issue by francoism90** [containers/podman#18240]
### Issue Description

I would like to use a bind mount into a folder that I'm sharing with my container (https://github.com/containers/podman/discussions/18220):
```
/home/user/project/data <= volume
/home/user/project/data/media <= external bind volume
```
It does work under Docker, but not under Podman when the container itself is run as rootless (so both Podman and the container: `-u 1000:1000 --uidmap 0:1:1 --uidmap 1000:0:1 --gidmap 0:1:1 --gidmap 1000:0:1`). The `/data/media` directory is just empty inside the container. Removing uidmap/gidmap, makes it visible again, however this does not follow my host user (1000), which I do want.

I could use the following workaround, as in simple mount each path individually, now it's visible even when including the uidmap/gidmap:
```
/home/user/project/data/media,U,Z <= volume (external bind volume)
/home/user/project/data/images,U,Z <= mounted volume
```
However I would need to do this for every directory.

### Steps to reproduce the issue

Steps to reproduce the issue
1. sudo mount --bind /path/to/media /home/user/project/data/media
2.  `-v /home/user/project/data:/data:U,z, -u 1000:1000 --uidmap 0:1:1 --uidmap 1000:0:1 --gidmap 0:1:1 --gidmap 1000:0:1`
3. `/data/media` in the container is empty

### Describe the results you received

Empty bind directory

### Describe the results you expected

Bind that works

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 65.73
    systemPercent: 8.48
    userPercent: 25.79
  cpus: 16
  distribution:
    distribution: fedora
    variant: silverblue
    version: "37"
  eventLogger: journald
  hostname: desktop
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.2.10-200.fc37.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 5057523712
  memTotal: 32973389824
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.3-2.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.3
      commit: 59f2beb7efb0d35611d5818fd0311883676f6f7e
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 8582901760
  swapTotal: 8589930496
  uptime: 12h 18m 27.00s (Approximately 0.50 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /var/home/user/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/user/.local/share/containers/storage
  graphRootAllocated: 998483427328
  graphRootUsed: 612302991360
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 132
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /var/home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.4
  Built: 1680521485
  BuiltTime: Mon Apr  3 13:31:25 2023
  GitCommit: ""
  GoVersion: go1.19.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.4
```
```


### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Fedora 37 Silverblue

### Additional information

I use `podman-compose`.

**Comment by Luap99** [comment]
What are the permission on the directory (including parent directories)?

This may be related: https://github.com/containers/podman/issues/17823

cc @giuseppe

**Comment by giuseppe** [comment]
Just try running `podman system migrate` first and run again the command, let's see if that is the reason before digging further into this possible cause

**Comment by francoism90** [comment]
@giuseppe Thanks! This seems to have worked, I can now see the volume inside the container(s). :D

Could you give more details? Why did work? And do I need to run this everything I use a bind mount?

Thanks again for the help.

**Comment by giuseppe** [comment]
could you show the output of `findmnt -R -o PROPAGATION,TARGET /` and `podman unshare findmnt -R -o PROPAGATION,TARGET /`?

I think you might have some mounts that are not using the `shared` propagation, so when a new mount happens on the host, it is not propagated inside the rootless mount namespace.  To see the new mount we need to destroy the old namespace and recreate it, so that it "clones" the current mounts on the host.
