### ISSUE TITLE
Support CDI devices in containers.conf in podman play kube

### ISSUE THREAD

**Issue by andrew-kennedy** [containers/podman#18266]
### Feature request description

Currently, containers created via podman play kube do not seem to correctly resolve fully qualified CDI devices (such as "nvidia.com/gpu=0") that are valid to use with the `--devices` flag or within the `devices` section of `containers.conf`.

specifically, they seem to fail during the build phase of `play kube`'s service container: `Error: image for service container: building local pause image: creating build executor: getting info of source device nvidia.com/gpu=0: stat nvidia.com/gpu=0: no such file or directory`

**Comment by andrew-kennedy** [comment]
More context: Looks like this comes from buildah: https://github.com/containers/buildah/blob/216d6be9633f7d40a0ca722a0959ce69aaf518c4/pkg/parse/parse_unix.go#L23, should I open an issue for CDI devices to be supported there?

**Comment by fpoirotte** [comment]
I think this is already being discussed in #17833 (although that issue does not mention `containers.conf`).
You might want to continue the discussion in that issue or in the associated [discussion thread](https://github.com/containers/podman/discussions/14934).
