### ISSUE TITLE
[e2e]   podman push to local registry with authorization: connection refused

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#18286]
Noticing this one lately in my skip-retries PR:
```
  podman push to local registry with authorization
...
# podman [options] run -d -p 5000:5000 [....]  quay.io/libpod/registry:2.8
[wait for it to come up, which it seems to do just fine]
# podman [options] push --tls-verify=true --format=v2s2 --creds=podmantest:test quay.io/libpod/alpine:latest localhost:5000/tlstest
Getting image source signatures
Copying blob sha256:03901b4a2ea88eeaad62dbe59b072b28b6efa00491962b8741081c5df50c65e0
time="2023-04-20T01:06:27Z" level=warning msg="Failed, retrying in 1s ... (1/3).
          Error: trying to reuse blob sha256:03901b4a2ea88eeaad62dbe59b072b28b6efa00491962b8741081c5df50c65e0 at destination:
          pinging container registry localhost:5000: Get \"https://localhost:5000/v2/\": dial tcp [::1]:5000: connect: connection refused"
```
The test is one of those badly-written ones that just check for `ExitWithError()` with no string check (it should check for "x509: certificate signed by unknown authority" here) so this step actually passes; the test doesn't fail until several steps later.

The use of `:5000` makes me suspect a collision, but if that were the case (1) I would see other tests flaking with a `5000` port, and (2) I would expect to see a different error than `connection refused`?

Have tried to look into this but gotten nowhere. Filing for future followup.

### Podman push [It] podman push to local registry with authorization
* debian-12 : int podman debian-12 root host sqlite
    * [04-11 07:59](https://api.cirrus-ci.com/v1/artifact/task/6633733470552064/html/int-podman-debian-12-root-host-sqlite.log.html#t--podman-push-to-local-registry-with-authorization--1)
* fedora-37 : int podman fedora-37 root container sqlite
    * [04-19 21:20](https://api.cirrus-ci.com/v1/artifact/task/6418865408704512/html/int-podman-fedora-37-root-container-sqlite.log.html#t--podman-push-to-local-registry-with-authorization--1)
* fedora-37 : int podman fedora-37 root host boltdb
    * [04-19 17:33](https://api.cirrus-ci.com/v1/artifact/task/4844648603058176/html/int-podman-fedora-37-root-host-boltdb.log.html#t--podman-push-to-local-registry-with-authorization--1)

**Comment by vrothberg** [comment]
I suspect the `registry:2` container got killed/stopped or has exited.  We also get a `connect: connection refused` when there's nothing on the other end.

**Comment by vrothberg** [comment]
It's hard to tell what's going on since we don't use the journal backend in the e2e tests.  I'd like to see how the container exited but without the events it's rather hard to tell.

@edsantiago @Luap99 any chance we can use the journal and only use `file` one where needed (e.g., for perf reasons)?

**Comment by Luap99** [comment]
I am strongly against using the journald event backend in the e2e tests. This was the case for the remote tests before I fixed it in https://github.com/containers/podman/pull/18283/commits/c9d8610239d2d9d4326ffcb8d498d7588668a531 to match the local one.

Because the journal is persistent I run the test often during debugging my journal was bigger than 1GB. All following podman events calls would take forever so that I cancelled them after about 15 mins. I don't know how many podman events I had but it was practically unusable.

And more importantly there is only one journal but we run tests in parallel which means the events can interfere with each other and cause flakes.

**Comment by vrothberg** [comment]
> Because the journal is persistent I run the test often during debugging my journal was bigger than 1GB. All following podman events calls would take forever so that I cancelled them after about 15 mins. I don't know how many podman events I had but it was practically unusable.

You can clean your local one up if needed.
 
> And more importantly there is only one journal but we run tests in parallel which means the events can interfere with each other and cause flakes.

The tests should be able to deal handle that scenario.  If an exact order/sequence is needed, the system tests can be used.

What I am mostly concerned about is that we currently have no record for events.  I think it's valuable (sometimes necessary) to debug issues such as flakes etc.

We could upload the events file(s) but I find the journal much more helpful as it gives the context of what's happening on the system along with container logs etc.

**Comment by edsantiago** [comment]
Sigh. Haven't seen this since my add-error-checks PR. Will give it one more month.
