### ISSUE TITLE
Implement QEMU version testing inside Podman code

### ISSUE THREAD

**Issue by arixmkii** [containers/podman#18314]
### Feature request description

Sometimes to implement a feature it is needed to have new QEMU version. It was first encountered in https://github.com/containers/podman/pull/17473#discussion_r1162184136 where fresh QEMU version was needed for implementing cross platform support for Windows OS. While other targets could just rely on older code, they also could benefit from the new codebase, which in turn would allow to phase out code supporting older versions, when minimal supported QEMU version is bumped.

### Suggest potential solution

Podman could inspect the output of help commands of QEMU to first collect information on what version is available and even check for specific features as well. Similar thing is implemented in Lima project https://github.com/lima-vm/lima/blob/b03835df403f806e37e56cbf95cc1b8728e91749/pkg/qemu/qemu.go#L183

### Have you considered any alternatives?

Defining minimal baseline, but it is difficult as QEMU will always be a moving target and Podman has to support LTS Linux targets, where QEMU version is frozen, but only backported fixes are provided (no features are normally backported).

**Comment by baude** [comment]
this approach of having a matrix of features that do or don't work is something that would drive me nuts (a claim most people have said already happened).  Nevertheless, perhaps setting a minimal version would work?  As in, if you have x.y, we hard fail.

**Comment by arixmkii** [comment]
In my opinion, just checking the version for some sort of feature level is just fine, but hard fail is not an option at least for the feature in question #17473, because we just can't hard fail for the feature, which would still be valid for older installations. And the minimal version of 7.2.0, will be possible only after RHEL 10 baseline I believe, but I'm not aware for how long newer versions of Podman are published for older RHEL versions.

For now this issue if more sort of RFC. I don't know if the project has a practice, where such issues are prefixed with RFC, I can update the title then.

**Comment by rhatdan** [comment]
@cevich I think there has been some movement on this?

**Comment by cevich** [comment]
Yes, I believe we spoke about it during the planning meeting this week.  Jira cards are being crafted.

**Comment by arixmkii** [comment]
Now that minimal QEMU version is raised to 7.2.0 with Machine 5, this could be delayed and reintroduced, when any new APIs of interest are discovered for machine improvements.
