### ISSUE TITLE
`podman machine rm` for QEMU provider removed connections before confirmation

### ISSUE THREAD

**Issue by arixmkii** [containers/podman#18330]
### Issue Description

After calling `podman machine rm` and pressing `n` to abort, the machine is not functional as connections are erased. Confirmed for QEMU on Windows and macOS.

The code part causing this is https://github.com/containers/podman/blob/main/pkg/machine/qemu/machine.go#L960 which is immediate, but should go inside callback https://github.com/containers/podman/blob/main/pkg/machine/qemu/machine.go#L992 (like in WSL implementation). WSL implementation is not affected.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman machine init`
2. `podman machine rm`
3. press `n`
4. `podman system connection list` (no connections)
5. `podman machine list` (machine still exists)

### Describe the results you received

Connections are erased.

### Describe the results you expected

Connections persisted like in WSL case on Widnows

### podman info output

```yaml
Intentionally skipped as machine was already ruined.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

On Windows was tested with built from latest main + QEMU machine supporting changes on top.

**Comment by baude** [comment]
this is a legit bug ... if anyone on the team can get to this, it'd be great ... the bug is also in the hyperv implementation.

**Comment by Luap99** [comment]
@baude I can take it, I see that it is broken in qemu but it looks correct in hyperV.
