### ISSUE TITLE
MacOS 13.2.1 + podman + podman compose + mongo - volumes are not synchronised

### ISSUE THREAD

**Issue by lukasonokoleg** [containers/podman#18348]
### Issue Description

After upgrading into: 
- podman - 4.5.0
- podman-compose 1.0.6 
- qemu - 8.0.0

Mongo volumes are not synchronised

### Steps to reproduce the issue

Steps to reproduce the issue
1. clone repo -> https://github.com/lukasonokoleg/podman-mac-mongo-volume-issue.git
2. execute ./install.sh
3. execute ./machine-init.sh
4. execute ./machine-start.sh 
5. execute podman-compose -f ./compose.yaml up -d

### Describe the results you received

- mongo container spins up -> it is possible to connect to it
- data/db & data/configdb folders are created
- mongo db data within data/db is not synchronised with host mac 

### Describe the results you expected

- Volume to be synchonise

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc38.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 64.49
    systemPercent: 18.75
    userPercent: 16.75
  cpus: 1
  databaseBackend: ""
  distribution:
    distribution: fedora
    variant: coreos
    version: "38"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.2.9-300.fc38.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 412880896
  memTotal: 2048827392
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.3-2.fc38.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.3
      commit: 59f2beb7efb0d35611d5818fd0311883676f6f7e
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-12.fc38.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 3m 32.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 3336040448
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.4.4
  Built: 1680521349
  BuiltTime: Mon Apr  3 14:29:09 2023
  GitCommit: ""
  GoVersion: go1.20.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.4
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

N/A

### Additional information

N/A

**Comment by lukasonokoleg** [comment]
As much as I could figure out -- it seems: 

- files from mongo container are not copied into machine -> checked it with ssh

**Comment by Luap99** [comment]
Can you provide the `podman inspect` output for the created container?

AFAICT the the mongo image [defines two volumes at `/data/db` and `/data/configdb`](https://github.com/docker-library/mongo/blob/cf85c62df0c753f5c523826aa8b94b5550fb723f/Dockerfile-linux.template#L104) which means podman will automatically create a volume for these paths. Thus your `/data` mount will only contain the directories as the db is on a separate mount point.

To fix this you need to set `./data/db:/data/db` in your compose file as volume.

**Comment by lukasonokoleg** [comment]
@Luap99 

Based on your comment - I've changed mountings in compose.yaml file. 

ROOTFUL CASE - still doesn't work - Within the pod I am getting error: 

```
chown: changing ownership of '/data/db': Operation not permitted
chown: changing ownership of '/data/configdb': Operation not permitted
```

ROOTLESS CASE - works with 2 things in place:

**Comment by Luap99** [comment]
The macos volume only has your uid. As this is used on your host the chown inside the VM to a different user is not allowed.

I suspect you would need to run with something like `--user $UID` when run as root so the container does not try to switch users and sees the volume has already the correct user. But this stuff really depends on what the container image is doing.

Bottom line is you cannot chown paths that are mounted from the mac.
