### ISSUE TITLE
Buildah kills container although SIGTERM signal is handled

### ISSUE THREAD

**Issue by MatsG23** [containers/podman#18346]
**Description**
I run an OCI image created by Buildah as a systemd service with Podman. In the journalctl, there are several logs that seem to belong to a layer added on top to the image by Buildah (they include the Buildah version at the end of the line; I additionally did not notice these logs before using images made with Buildah).

Example:
```
2023-04-22 11:09:45.957612603 +0200 CEST m=+0.931930318 container stop 7fe468112f2cd80a5f06ee6d5daea948975dfad30aaa0e16cfcfa4b99de2e13e (image=ghcr.io/USER/PRIVATE-REPO:dev, name=api, PODMAN_SYSTEMD_UNIT=api_container.service, io.buildah.version=1.23.1)
```

_This is why I believe this issue belongs to the issue tracker of Buildah. Feel free to point me to a different repository if I was wrong._

I feel like that kind of "runner" kills my container when stopping the systemd service although the `SIGTERM` process signal is handled by the container which should therefore be stopped gracefully.
I am running a Node.JS server. According to the logs, the server process has the **PID 1** (the line with a JSON-formatted log comes from my project) meaning that it will receive the process signals for stopping the container. This is the code I use to handle `SIGTERM` (you can double-check that, what is important is that the process is exitted in the handler):
```ts
async function shutdown() {
  fastify.log.info("Shutting down server and database pool...");
  await fastify.close();
  await prisma.$disconnect();
  process.exit(0);
}

process.on("SIGTERM", shutdown);
```

**Steps to reproduce the issue:**
https://github.com/MatsG23/buildah-issue

**Describe the results you received:**
The container seems to be killed. It says "Container died" which sounds like a non-graceful stop to me.

Logs:
```
Apr 22 11:09:44 api-sys systemd[524]: Stopping API Server (Podman Container)...
Apr 22 11:09:45 api-sys podman[6532]: {"level":30,"time":1682154585423,"pid":1,"hostname":"7fe468112f2c","msg":"Shutting down server and database pool..."}
Apr 22 11:09:45 api-sys podman[19623]: 2023-04-22 11:09:45.957612603 +0200 CEST m=+0.931930318 container stop 7fe468112f2cd80a5f06ee6d5daea948975dfad30aaa0e16cfcfa4b99de2e13e (image=ghcr.io/USER/PRIVATE-REPO:dev, name=api, PODMAN_SYSTEMD_UNIT=api_container.service, io.buildah.version=1.23.1)
Apr 22 11:09:46 api-sys podman[19623]: 2023-04-22 11:09:46.011344463 +0200 CEST m=+0.985662177 container died 7fe468112f2cd80a5f06ee6d5daea948975dfad30aaa0e16cfcfa4b99de2e13e (image=ghcr.io/USER/PRIVATE-REPO:dev, name=api)
Apr 22 11:09:46 api-sys podman[19623]: 2023-04-22 11:09:46.27965122 +0200 CEST m=+1.253968934 container cleanup 7fe468112f2cd80a5f06ee6d5daea948975dfad30aaa0e16cfcfa4b99de2e13e (image=ghcr.io/USER/PRIVATE-REPO:dev, name=api, io.buildah.version=1.23.1, PODMAN_SYSTEMD_UNIT=api_container.service)
Apr 22 11:09:46 api-sys podman[19623]: 7fe468112f2cd80a5f06ee6d5daea948975dfad30aaa0e16cfcfa4b99de2e13e
Apr 22 11:09:46 api-sys podman[19634]: 2023-04-22 11:09:46.288696728 +0200 CEST m=+0.366287529 container cleanup 7fe468112f2cd80a5f06ee6d5daea948975dfad30aaa0e16cfcfa4b99de2e13e (image=ghcr.io/USER/PRIVATE-REPO:dev, name=api, PODMAN_SYSTEMD_UNIT=api_container.service, io.buildah.version=1.23.1)
Apr 22 11:09:47 api-sys podman[19658]: 2023-04-22 11:09:47.023012748 +0200 CEST m=+0.426150060 container remove 7fe468112f2cd80a5f06ee6d5daea948975dfad30aaa0e16cfcfa4b99de2e13e (image=ghcr.io/USER/PRIVATE-REPO:dev, name=api, PODMAN_SYSTEMD_UNIT=api_container.service, io.buildah.version=1.23.1)
Apr 22 11:09:47 api-sys podman[19658]: 7fe468112f2cd80a5f06ee6d5daea948975dfad30aaa0e16cfcfa4b99de2e13e
Apr 22 11:09:47 api-sys systemd[524]: api_container.service: Succeeded.
Apr 22 11:09:47 api-sys systemd[524]: Stopped API Server (Podman Container).
Apr 22 11:09:47 api-sys systemd[524]: api_container.service: Consumed 4min 12.616s CPU time.
```

**Describe the results you expected:**
It should stop the container gracefully because the process signal is handled properly, I think.

**Command outputs:**
I use the GitHub action `redhat-actions/buildah-build@v2` on a runner with `ubuntu-latest`. When running the built image, it says `io.buildah.version=1.23.1` in several places in the log.

---

I hope I am not misinterpreting the term "container **died**".
Can someone tell me what Buildah adds to the image?

**Comment by flouthoc** [comment]
Hi @MatsG23 , Looking at this https://github.com/MatsG23/buildah-issue I think you should use `podman kill` instead of `podman stop` , I think `podman kill` should send the single to your node server.

See: https://docs.podman.io/en/latest/markdown/podman-kill.1.html

I think `podman kill` will solve your use-case hence closing this issue but please feel free to re-open.
