### ISSUE TITLE
quadlet fails with a timeout when starting

### ISSUE THREAD

**Issue by keszybz** [containers/podman#18353]
### Issue Description

The example from https://www.redhat.com/sysadmin/quadlet-podman fails on Fedora 38 because the unit times out during start when it is downloading the image. Fedora 38 reduced the start/stop timeouts (https://fedoraproject.org/wiki/Changes/Shorter_Shutdown_Timer), making the failure easier to reach.

<details>

```console
$ systemctl --user status mysleep.service
× mysleep.service - The sleep container
     Loaded: loaded (/home/zbyszek/.config/containers/systemd/mysleep.container; generated)
    Drop-In: /usr/lib/systemd/user/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: timeout) since Wed 2023-04-26 13:52:03 CEST; 11min ago
    Process: 1648289 ExecStart=/usr/bin/podman run --name=systemd-mysleep --cidfile=/run/user/1000/mysleep.cid --replace --rm --c>
    Process: 1648441 ExecStopPost=/usr/bin/podman rm -f -i --cidfile=/run/user/1000/mysleep.cid (code=exited, status=0/SUCCESS)
   Main PID: 1648289 (code=exited, status=0/SUCCESS)
        CPU: 1.526s

Apr 26 13:51:48 x1c systemd[3078]: Starting mysleep.service...
Apr 26 13:51:48 x1c mysleep[1648289]: Trying to pull registry.access.redhat.com/ubi9-minimal:latest...
Apr 26 13:51:56 x1c mysleep[1648289]: Getting image source signatures
Apr 26 13:51:56 x1c mysleep[1648289]: Checking if image destination supports signatures
Apr 26 13:51:56 x1c mysleep[1648289]: Copying blob sha256:7bffb309b4e88826a3c7dc629c1ebd7b3aa6ad861157f4acea7c4f8057fa30d5
Apr 26 13:52:03 x1c systemd[3078]: mysleep.service: start operation timed out. Terminating.
Apr 26 13:52:03 x1c systemd[3078]: mysleep.service: Failed with result 'timeout'.
Apr 26 13:52:03 x1c systemd[3078]: Failed to start mysleep.service.
Apr 26 13:52:03 x1c systemd[3078]: mysleep.service: Consumed 1.526s CPU time.
```
</details>

This was already discussed in https://github.com/containers/podman/issues/11618, and, IIUC, the conclusion was that the user should configure ExecStartTimeout= themselves. I think this is not a sufficient solution, because the user cannot really know what the appropriate timeout is. Depending on the details of a specific machine, network, container type, and phase of the moon, the download may take 10 s or 90 s or 5 minutes. The only reasonable solution is to keep sending EXTEND_TIMEOUT_USEC notifications *as long as the download is progressing*. With the fixed timeout, the user can either set it to something reasonable and have the problem that occasional network or disk slowdowns will result in spurious unit failures, or set it to something very large and have the problem that if the unit does get stuck, it won't be terminated until this very large timeout passes.

### Steps to reproduce the issue

Steps to reproduce the issue
1. create `mysleep.service` following https://www.redhat.com/sysadmin/quadlet-podman
2. `systemctl --user daemon-reload && systemctl --user start mysleep`

To reproduce the issue, the UBI image must not be available locally and the network must be slow enough.

### Describe the results you received

Timeout failure as described above

### Describe the results you expected

No timeout failure

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc38.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 95.36
    systemPercent: 1.15
    userPercent: 3.49
  cpus: 8
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: workstation
    version: "38"
  eventLogger: journald
  hostname: x1c
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.2.6-300.fc38.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 919109632
  memTotal: 33331449856
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.3-2.fc38.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.3
      commit: 59f2beb7efb0d35611d5818fd0311883676f6f7e
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-12.fc38.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 24278982656
  swapTotal: 24301789184
  uptime: 191h 11m 24.00s (Approximately 7.96 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/zbyszek/.config/containers/storage.conf
  containerStore:
    number: 9
    paused: 0
    running: 1
    stopped: 8
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/zbyszek/.local/share/containers/storage
  graphRootAllocated: 494660485120
  graphRootUsed: 337549828096
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 6
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/zbyszek/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.0
  Built: 1681486942
  BuiltTime: Fri Apr 14 17:42:22 2023
  GitCommit: ""
  GoVersion: go1.20.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

podman-4.5.0-1.fc38.x86_64

**Comment by Luap99** [comment]
I agree that this would be nice to send `EXTEND_TIMEOUT_USEC` as long as podman knows that it is still doing something, not only pulling there are also other operations that can take a while.
However it works as designed right now so I change this to a feature request.

**Comment by rhatdan** [comment]
How would podman know to send EXTEND_TIMEOUT_USEC?

**Comment by keszybz** [comment]
> rhatdan closed this as completed 14 hours ago

?

> How would podman know to send EXTEND_TIMEOUT_USEC?

When podman enters a long-running operation, e.g. the download, periodically send `EXTEND_TIMEOUT_USEC=` as long as podman thinks that progress is being made. This could be as simple as: send `EXTEND_TIMEOUT_USEC=30000000` (30 s) when starting, and then at any time after 15 s have passed, send the notification again. podman is doing a download, so it has a loop where it requests data, waits for a reply, and writes the data to disk. It'd need to be inserted somewhere in this loop.

**Comment by Luap99** [comment]
> so it has a loop where it requests data, waits for a reply, and writes the data to disk. It'd need to be inserted somewhere in this loop.

Yes is important to do it inside this loop to only send these messages if there is actual progress being made so we not send them if download is stucked for a long time. Which means this likely has to be done in c/image.

**Comment by rhatdan** [comment]
Well containers/image currently doe not know anything about notify socket. @mtrmac @vrothberg Thoughts?

**Comment by mtrmac** [comment]
- This might not be what the administrator wants. The administrator (of a certain latency-sensitive movable platform) could want to impose a total deadline. Hard-coding the code to override the timeout configured in the unit would make that impossible.
- Assuming a hypothetical opt-in of some kind, this could happen either directly in c/image, or in a c/image caller consuming `copy.Options.Progress`. I don’t care _much_ where that would be — a weak reason to do it in a caller of c/image is that c/image, so far, has had no code to interact with systemd.
  - Isn’t the notify socket a singleton? If so, there should be only a single writer to it (to ensure that concurrent messages can’t be interleaved), and therefore owned and operated at a fairly high level.

**Comment by keszybz** [comment]
> * This might not be what the administrator wants. The administrator (of a certain latency-sensitive movable platform) could want to impose a total deadline. Hard-coding the code to override the timeout configured in the unit would make that impossible.
 
Yes, that is certainly possible. Nevertheless, I think that's an exceptional case and should be configured explicitly. (My thinking that the download of an image is like any other download: if I start `wget`, I want it to continue as long as it's getting some data. If I start `dnf`, it'll keep downloading rpms as long as it's making progress. It'll abort below some boundary (< 100b/s  or something like that), but otherwise it'll take as long as necessary. This might be a fraction on a second on a good network, or a couple of hours for a big update on a slow network. In all cases, the download is managed internally, and the total download time is only limited through some special explicit configuration, also because such a download is very hard to determine in a generic way, so there is no good default for it.)

>    * Isn’t the notify socket a singleton? If so, there should be only a single writer to it (to ensure that concurrent messages can’t be interleaved), and therefore owned and operated at a fairly high level.

No. It uses `sendmsg()` which is atomic.

**Comment by mtrmac** [comment]
I don’t really have an opinion on what the default should be; just that it probably should be configurable.

---

Actually, reading https://github.com/coreos/go-systemd/blob/main/daemon/sdnotify.go, the socket is used with a separate connection for each notification, so I was entirely mistaken about how that works.

**Comment by vrothberg** [comment]
Some unstructured thoughts:
1. We should update the Quadlet man page to at least mention that some distributions have a shorter timeout than others
2. Podman (or c/image) increasing the timeout on pulls sounds OK to me.  But it should be configurable somewhere.
3. Quadlet could also set the timeout (and it be configurable somewhere).

BUT the Fedora change (https://fedoraproject.org/wiki/Changes/Shorter_Shutdown_Timer) was talking about the _shutdown_, yet the change also set the start timeout to 45sec.  IMO, this should be raised on the Fedora side of things.

We can certainly consider 1) 2) and 3) on the Podman side but I am under the impression the Fedora change did too much.

**Comment by rhatdan** [comment]
FYI @vrothberg issue came up again today.

**Comment by vrothberg** [comment]
Let's chat about it tomorrow and iron out how we want it to behave.
