### ISSUE TITLE
podman container restore error

### ISSUE THREAD

**Issue by IDS-Nobody** [containers/podman#18352]
### Issue Description

I hope podman will create checkpoint and restore from checkpoint. Unfortunatly, podman can't restore from the checkpoint for unexpected reason.(maybe from criu) Here are more details. 
restore.log(end of the log)
(00.081134) pie: 1: 	mmap(0x7fff72bbe000 -> 0x7fff72bc0000, 0x7 0x32 -1)
(00.081137) pie: 1: Preadv 0xebb80000:462848... (105 iovs)
(00.086280) Error (criu/cr-restore.c:1492): 18962 stopped by signal 11: Segmentation fault
(00.086947) mnt: Switching to new ns to clean ghosts
(00.091040) Error (criu/cr-restore.c:2447): Restoring FAILED.

### Steps to reproduce the issue

Steps to reproduce the issue
1.podman build -t myjava .
2.podman run --security-opt="seccomp=unconfined" --tmpfs /tmp -d --name test myjava
3.podman container checkpoint test
4.podman container restore -k test

### Describe the results you received

![image](https://user-images.githubusercontent.com/47500029/234455099-3d631908-a758-436f-a68e-e0a24b1fa874.png)
[restore_log.txt](https://github.com/containers/podman/files/11329691/restore_log.txt)

### Describe the results you expected

Describe the results you expected
I set up a count program that  increments the output every 5 seconds, here is output:
![image](https://user-images.githubusercontent.com/47500029/234456985-8d71d52d-7234-4e03-a6b2-15078bef3741.png)

And I hope Podman can continue to increment the number after restoring.
Dockerfile:
```
FROM ubuntu:18.04
RUN apt-get update 
RUN apt-get install -y openjdk-8-jdk 
RUN rm -rf /var/lib/apt/lists/* 
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
ENV PATH $JAVA_HOME/bin:$PATH
COPY Main.java /home/test/
WORKDIR /home/test/
RUN javac Main.java
CMD ["java","Main"]
```
Main.java
```
import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.TimeUnit;

public class Main {
    private static int counter = 0;
    public static void main(String[] args){
        Timer timer = new Timer();
        timer.schedule(new TimerTask() {
            @Override
            public void run() {
                counter ++ ;
                System.out.println(counter);
            }
        },0,5000);
    }
}
```

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
podman info :
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 2
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: criut-virtual-machine
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.19.0-40-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 968880128
  memTotal: 4077686784
  ociRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.1.4
      commit: v1.1.4-0-g5fd4c4d1
      spec: 1.0.2-dev
      go: go1.17.10
      libseccomp: 2.5.4
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 1468862464
  swapTotal: 1469661184
  uptime: 1h 4m 59.63s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  docker.io:
    Blocked: false
    Insecure: true
    Location: registry.docker-cn.com
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: docker.io
  search:
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 10
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Thu Jan  1 08:00:00 1970
  GitCommit: ""
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 3.4.4
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details
VMware Workstation 16

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
Works corretly with podman v4.5 and criu v3.17.1 on my fedora 37 laptop,
I suggest you update to a more recent version.
