### ISSUE TITLE
Podman Secrets Documentation: Available drivers?

### ISSUE THREAD

**Issue by hashkeks** [containers/podman#18387]
### Feature request description

A request not for Podman directly but for the documentation, or rather a question about the _podman secret create_ functionality. Currently the documentation for the _podman secret create_ command lists the option _--driver_, which defaults to _file_. I can't seem to find any other possible drivers and skipping through the code here on Github (with my limited knowledge) I also can't find any other implemented option than _file_.
The way the documentation for the _--driver_ option is phrased ("Specify the secret driver (default file, which is unencrypted)"), it sounds like there should be more drivers available than just _file_, especially some that encrypt the secret with a password or key.

Are there any more drivers available than just _file_ currently? Are there more drivers planned to be implemented in the future?

### Suggest potential solution

I think it would be good to clearly specify the currently available _--driver_ options for the _podman secret create_ command in the documentation, because currently it's not clearly described and leaves room for interpretation.

**Comment by flouthoc** [comment]
There are two more available drivers `pass` and `shell`, but I am not sure if it is being maintained by `podman` maintainers or not. See: https://github.com/containers/common/tree/main/pkg/secrets

Their usage is not documented in `podman`, maybe @trusch could help since he added the support for both of them.

@containers/podman-maintainers PTAL

**Comment by void-spark** [comment]
Was just trying to find this :)
Also a bit more details on file maybe? Where are they stored, and specifically, what kind of permissions/uid/gid will be set? :)

**Comment by ashley-cui** [comment]
The file is created with 0600 perms, under `$GRAPHROOT/secrets/filedriver`. Graphroot by default is `~/.local/share/containers/storage` for rootless and `/var/lib/containers/storage/` for root.

**Comment by maxsatula** [comment]
Adding my 5 cents about other available drivers, which I looked up in the source code. https://github.com/containers/common/tree/c73d138e5848f915539a5369488a2a17c9fb883e/pkg/secrets

**passdriver.** Store passwords in GPG encrypted files, one per secret, like GNU `pass` utility does. Requires GPG to be configured (encryption key pair to be generated), and as far as I understand, `pass` utility does not have to be installed, but it is convenient to have anyway to review what's going on.

Driver options (containers.conf), all optional:
```
[secrets]
driver = "pass"

[secrets.opts]
# can be any existing directory
root = "/home/opc/.password-store"
# public key GPG ID
key = "CC18D94F"
# name speaks for itself, an alternative GPG home directory with keys and stuff
gpghomedir =

```

**shelldriver** Run custom shell scripts to list, retrieve, set, or delete a secret. For all commands except list there is `SECRET_ID` environment variable passed to the scripts, the secret content is communicated via stdin/stdout whenever applicable, depending on the command nature

Driver options (containers.conf), a set of 4 paths to shell scripts:
```
[secrets]
driver = "shell"

[secrets.opts]
list =
lookup =
store =
delete =
```

Besides `containers.conf` file, all these options can be specified/overriden in `podman secret create --driver=... --driver-opts=...`. By the way, during secret create only. After that, podman remembers the options each secret was created with, so even if the options change with time, existing secrets are still accessible. Which allows to have a bunch of secrets with all the variety of drivers and options at the same time.

My apologies for that looking sloppy and it is not ready to go to the docs the way I wrote it, but for now it is better than nothing, I guess.

**Comment by christian-2** [comment]
Perhaps those labels could serve: `documentation`, `volunteers-wanted`, `Good First Issue`

**Comment by rhatdan** [comment]
Yes Man pages and potentially the output of podman secret create --help

**Comment by christian-2** [comment]
@rhatdan I'll have a go at this.

**Comment by rhatdan** [comment]
Thanks
