### ISSUE TITLE
Update APT packages

### ISSUE THREAD

**Issue by Shynamo** [containers/podman#18390]
### Feature request description

The current Podman version available in APT registry is 3.4.4 which is more than two years old. Is it possible to upgrade it to a newer version ?

```cmd
sudo apt list podman -a
Listing... Done
podman/jammy,now 3.4.4+ds1-1ubuntu1 amd64 [installed]
```

I am using Ubuntu 22.04 and run `sudo apt update` right before the command.

### Suggest potential solution

Automate the build of a `.deb` in a release.

Optionally, automate its upload to APT registry when a new version is released, and compile for several architectures (amd64, x86_64, arm64, ...)

### Have you considered any alternatives?

As users, we certainly can download and install a package manually from the [releases](https://github.com/containers/podman/releases), but most Debian users simply use APT because it is more convenient.

The [installation instructions](https://podman.io/getting-started/installation#installing-on-linux) states that it is possible to use APT on Debian 11+ and that newer from the Kubic repo version may not be production ready, but there certainly is a stable production ready version between 3.4.4 and 4.5.0.

### Additional context

While using rootless Podman as a Docker GitLab Runner executor I encountered a bug that got me several hours of research:

`ERROR: Job failed (system failure): unable to upgrade to tcp, received 500`

The `unable to upgrade to tcp` was a bug from Podman. After desperately manually upgrade my version of Podman from 3.4.4 to 4.5.0 this was fixed. The "manual upgrade" was an [installation from source](https://podman.io/getting-started/installation#building-from-scratch).

This is just an example, but I believe all those already-fixed bug can save a lot of headaches to Podman users who simply installed via APT.

**Comment by Luap99** [comment]
We do not control packaging for distributions. It is up to them to ship the packages. If you want ubuntu to ship newer version you should ask them not us.
The kubic repo is not production ready because it is not really tested and only maintained by one person (@lsm5), you can install a version from there just fine but if something breaks don't expect it to be fixed immediately. It is really best effort depending on how @lsm5 has time.

**Comment by lsm5** [comment]
@Shynamo agree with what @Luap99 said. If you need a newer deb package to use in production environments, your best bet would be from the official distro (along with its backport repos if any). You could start off with filing an issue on Ubuntu's launchpad.
