### ISSUE TITLE
Unclear instructions on netavark networking

### ISSUE THREAD

**Issue by inflatador** [containers/podman#18417]
### Issue Description

[The Basic Networking Guide for Podman](https://github.com/containers/podman/blob/main/docs/tutorials/basic_networking.md#default-network) states "To change [podman network] settings, export the in-memory network and change the file." 

But there are no specifics on exactly which values to change in the file, or what to change them to.

A few lines down, in [the "Example" section](https://github.com/containers/podman/blob/main/docs/tutorials/basic_networking.md#example) , the guide states "no network name must be passed to Podman." Does this mean "it is not necessary to pass the network name to Podman" or "you should not pass the network name to Podman"? I'm pretty sure it's the former, but it would help to clear that up.

Thanks for your time and let me know if you need more info.

### Steps to reproduce the issue

Steps to reproduce the issue
N/A

### Describe the results you received

N/A

### Describe the results you expected

N/A

### podman info output

```yaml
N/A
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

N/A

### Additional information

N/A

**Comment by Luap99** [comment]
> But there are no specifics on exactly which values to change in the file, or what to change them to.

Well this just shows you how you can change something in the default config. You see the json file, the field names are very self explanatory in my opinion. Maybe a link to https://docs.podman.io/en/latest/markdown/podman-network-inspect.1.html would help?

> A few lines down, in [the "Example" section](https://github.com/containers/podman/blob/main/docs/tutorials/basic_networking.md#example) , the guide states "no network name must be passed to Podman." Does this mean "it is not necessary to pass the network name to Podman" or "you should not pass the network name to Podman"?

yes the former, as root you use the default network (called `podman`) by default.


Do you want to open a PR to improve the wording in both cases?

**Comment by vrothberg** [comment]
@inflatador are you interested in opening a PR to improve the wording?

**Comment by hugopeixoto** [comment]
I'll open a PR to improve this.

While I'm at it, there's another sentence that I find confusing:

> As mentioned earlier, slirp4netns is the default network configuration for rootless users. But as of Podman version 4.0, rootless users can also use netavark. The user experience of rootless netavark is very akin to a rootful netavark, except that there is no default network configuration provided.

This to me reads like you can use netavark as a replacement for slirp4netns, while what it means is that you don't need to configure the network driver to explicitly be slirp4netns, and that netavark will use it implicitly, right? (I don't know much about networking)

**Comment by Luap99** [comment]
Rootless will always need either slirp4netns/pasta to connect the host namesapce to some rootless netns. netavark/CNI (on older versions) are just used to configure bridged networking for the container.

Thus something like `--network bridge` will use both as rootless so netavark is never a replacement for the rootless networking tool, it just can be used additionally to configure bridges and allow inter container communication
