### ISSUE TITLE
Enable build of RPMs on RHEL 8

### ISSUE THREAD

**Issue by Steve973** [containers/podman#18421]
### Feature request description

RHEL 8.6 app streams include a version of Podman that is nearly a year old, so I want to be able to build an RPM to install a newer version of Podman on RHEL 8.6 and RHEL 8.7 servers.  I have tried cloning the repository and building on the machine (directly), as well as creating a RHEL 8.6 container with installed dependencies for building.  The problem that I am running into when issuing `make package` is that rpkg-utils is no longer available.  I can install fedpkg, but I have not had success in building an RPM.

### Suggest potential solution

Provide instructions, at a minimum, for RPM building on various platforms including RHEL 8.x.  Consider moving away from rpkg-utils, since it is no longer maintained.

### Have you considered any alternatives?

If there are compatible RPMs for RHEL 8.6, I will try them.  However, I do not see any RPMs in the assets that are produced by the builds.

**Comment by lsm5** [comment]
@Steve973 i'm working on switching our downstream Fedora process to a packit workflow, starting with container-selinux at https://github.com/containers/container-selinux/pull/232 . The spec file present upstream, currently `podman.spec.rpkg` and soon `rpm/podman.spec` (see the container-selinux PR for the relevant change there) will be buildable on all active environments (fedora rawhide to rhel 8).

So, with that spec file, it might be easiest for you to stand up your own copr repo and have it autobuild rpms. Would that work for you? I think I could also update `make package` or add a `make rpm` to build using the new spec file.

**Comment by Steve973** [comment]
> @Steve973 i'm working on switching our downstream Fedora process to a packit workflow, starting with container-selinux at [containers/container-selinux#232](https://github.com/containers/container-selinux/pull/232) . The spec file present upstream, currently `podman.spec.rpkg` and soon `rpm/podman.spec` (see the container-selinux PR for the relevant change there) will be buildable on all active environments (fedora rawhide to rhel 8).
> 
> So, with that spec file, it might be easiest for you to stand up your own copr repo and have it autobuild rpms. Would that work for you? I think I could also update `make package` or add a `make rpm` to build using the new spec file.

I'm on an enclave, although this repo gets pulled up on some schedule that I'm not entirely aware of.  At least at this point, I'd like to build on demand, so however I can achieve that, I'd be happy with it.  I'd really like to get the fixes for init containers so that I can use them with my project when using `podman kube play`.  I will try whatever is the simplest solution you can recommend.  Thanks for looking into this.

**Comment by lsm5** [comment]
@Steve973 ack, got it. Given I'm in the middle of a build process change, hope you're cool with waiting a little longer. I'll have a PR up in a bit, with a new Makefile target to build on demand.

**Comment by Steve973** [comment]
@lsm5 Thanks.  It will happen when it happens.  I can still build the source, but I just can't create RPMs.  I could work around that, in the meantime, if I need to.
