### ISSUE TITLE
When running Openshift installer build process, podman fails with "there might not be enough IDs available in the namespace"

### ISSUE THREAD

**Issue by pojoguy** [containers/podman#18447]
/kind bug
### Issue Description

Follow the steps at https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/installing/installing-on-a-single-node

coreos-installer is an alias for a podman call.

alias coreos-installer='podman run --privileged --pull always --rm \
        -v /dev:/dev -v /run/udev:/run/udev -v $PWD:/data \
        -w /data quay.io/coreos/coreos-installer:release'

When:

coreos-installer iso ignition embed -fi iso.ign rhcos-live.x86_64.iso

is executed, ...

### Describe the results you received

the program logs

[administrator@cen-79-pxe rhcos]$ coreos-installer iso ignition embed -fi iso.ign rhcos-live.x86_64.iso
Trying to pull quay.io/coreos/coreos-installer:release...
Getting image source signatures
Copying blob 06c74f6d5eee done
Copying blob 31c6d987c79e done
Copying blob 517a1633feba done
Copying config 7a8aacecfc done
Writing manifest to image destination
Storing signatures
  Error processing tar file(exit status 1): there might not be enough IDs available in the namespace (requested 0:12 for /var/spool/mail): lchown /var/spool/mail: invalid argument
Error: unable to pull quay.io/coreos/coreos-installer:release: unable to pull image: Error committing the finished image: error adding layer with blob "sha256:06c74f6d5eee06a25138eff894434b8497dcb29aa9a2736b607714e59c3c3350": Error processing tar file(exit status 1): there might not be enough IDs available in the namespace (requested 0:12 for /var/spool/mail): lchown /var/spool/mail: invalid argument

### Describe the results you expected

I expected the rhcos-live.x86_64.iso to be created, or sufficient information that I can find and resolve the problem.

### podman info output

Trying to pull quay.io/coreos/coreos-installer:release...
Getting image source signatures
Copying blob 06c74f6d5eee done
Copying blob 31c6d987c79e done
Copying blob 517a1633feba done
Copying config 7a8aacecfc done
Writing manifest to image destination
Storing signatures
  Error processing tar file(exit status 1): there might not be enough IDs available in the namespace (requested 0:12 for /var/spool/mail): lchown /var/spool/mail: invalid argument
Error: unable to pull quay.io/coreos/coreos-installer:release: unable to pull image: Error committing the finished image: error adding layer with blob "sha256:06c74f6d5eee06a25138eff894434b8497dcb29aa9a2736b607714e59c3c3350": Error processing tar file(exit status 1): there might not be enough IDs available in the namespace (requested 0:12 for /var/spool/mail): lchown /var/spool/mail: invalid argument

podman version 1.6.4
CentOS Linux release 7.9.2009 (Core)
architecture x86_64 Intel Core Processor (Haswell, no TSX)

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

unknown

### Additional environment details

Running inside of QEMU emulator version 1.5.3 (qemu-kvm-1.5.3-175.el7_9.6)

### Additional information

So far this happens every time, but I'm only using it in my Ovirt cluster.

**Comment by Luap99** [comment]
This sounds like you did not set up /ets/subuid and /etc/subgid correctly. Alternatively you could try running podman as root.

For example see https://github.com/containers/podman/blob/main/troubleshooting.md#10-rootless-setup-user-invalid-argument.

We only support the latest version upstream, podman 1.6 and centos 7 are super old at this point.

**Comment by pojoguy** [comment]
Thank you
