### ISSUE TITLE
invalid internal status, try resetting the pause process with \"/var/tmp/go/src/github.com/containers/podman/bin/podman system migrate\": setting up the process: open /run/user/3271/libpod/tmp/pause.pid: no such file or directory

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#18448]
New one-off flake, seen in [debian root](https://api.cirrus-ci.com/v1/artifact/task/5561765895864320/html/sys-podman-debian-12-root-host-boltdb.log.html):
```
not ok 232 podman image scp transfer
...
# podman image scp some9724dude@localhost::foo.bar/nonesuch/c_v59yduh5oc:mytag foobar:123
error creating temporary file: No such file or directory
time="2023-05-02T13:25:28Z"
      level=error
      msg="invalid internal status, try resetting the pause process with \"podman system migrate\": 
         setting up the process: open /run/user/3271/libpod/tmp/pause.pid: no such file or directory"
Error: exit status 1
```

**Comment by basilgello** [comment]
Reproducible on Debian 12 / bookworm as well. `$XDG_RUNTIME_DIR/libpod` gets recreated on relogin but `tmp` subfolder of it does not. Recreating the tmp directory prior to running podmn solves the issue but the running containers dont survive logout.

**Comment by edsantiago** [comment]
Last seen June 23. All instances were on Debian 12, and we're now running 13, so I'm tempted to la-la-la sweep this under the rug.

@basilgello does this remain a problem/priority for you? And, have you tried (as root) `loginctl enable-linger YOURUSERNAME`?

**Comment by basilgello** [comment]
I do that and/or tmuxing but the patch is definitely on my list

**Comment by edsantiago** [comment]
No instances of the flake since my last post. All I can do here is close.
