### ISSUE TITLE
Name resolution not working when a DNS container is started

### ISSUE THREAD

**Issue by thyeestes** [containers/podman#18463]
### Issue Description

Hi All,

I have the following situation. I have multiple containers running on the same network, these containers can find and communicate with each other. However as soon as I start a container with a DNS server, all communication breaks.

Any ideas how to solve that? 

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman network create --subnet=192.168.89.0/24 --gateway=192.168.89.1 --dns=192.168.122.1 --driver=bridge proxy
2. podman pod create --name pm --network proxy -p 81:80
3. podman pod create --name db --network proxy -p 3306:3306
4. podman pod create --name dns -p 3000:3000 -p 53:53/tcp -p 53:53/udp --network proxy
5. podman run --name adguardhome --pod=dns   --restart unless-stopped    -v /home/podman/adguard/work:/opt/adguardhome/work    -v /home//podman/adguard/conf:/opt/adguardhome/conf    -d adguard/adguardhome
6. podman run -dt --restart=always --name mariadb --pod=db --secret mysql_root_password -v /home/podman/mariadb/data:/var/lib/mysql -v /home/podman/mariadb/config:/etc/mysql/conf.d -e MARIADB_AUTO_UPGRADE=1 -e MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password mariadb:latest
7. podman run -dt --restart=always --pod=pm --name pma --secret mysql_root_password -e PMA_HOST=db -e PMA_PORT=3306 -e MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password phpmyadmin/phpmyadmin:latest

### Describe the results you received

As soon as I stop Adguard communication between pm and db work, once started communication fails

### Describe the results you expected

Communication continued to work when a DNS server is started

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2:2.1.7-0ubuntu22.04+obs15.24_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 99.67
    systemPercent: 0.1
    userPercent: 0.23
  cpus: 4
  databaseBackend: boltdb
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: UbuntuVM
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.19.0-41-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 3857809408
  memTotal: 8337162240
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun_101:1.8.4-0ubuntu22.04+obs55.10_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.4
      commit: 5a8fa99a5e41facba2eda4af12fa26313918805b
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.2.0-0ubuntu22.04+obs10.63_amd64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 2147479552
  swapTotal: 2147479552
  uptime: 20h 14m 38.00s (Approximately 0.83 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/thyestes/.config/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 6
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/thyestes/.local/share/containers/storage
  graphRootAllocated: 66785456128
  graphRootUsed: 12911439872
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 4
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/thyestes/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.18.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

I also tried using docker-compose (my preferred way) to create the network and spin the containers up, but same results

**Comment by Luap99** [comment]
If you start a dns server yourself it will obviously cause a port conflict with aardvark-dns.
You either have to add you primary interface ip to the port mapping, e.g. `-p 192.168.1.1:53:53/tcp -p 192.168.1.1:53:53/udp` change the ip with the correct one.

Or alternatively you have to change `dns_bind_port` to some high port in containers.conf.

**Comment by thyeestes** [comment]
Thanks for the reply. Changing the dns_bind_port didn't work, first suggestion did.

P.s. with this pull would aardvark not use a different port then 53? [https://github.com/containers/netavark/pull/323](url)

**Comment by Luap99** [comment]
Did you stop all your containers before changing the port, aardvark-dns must be stopped in order for this field to take effect. 53 is the default and will only be changed if you set it in containers.conf

**Comment by Luap99** [comment]
Yes it should be

**Comment by thyeestes** [comment]
Thanks
