### ISSUE TITLE
provide rootless info in podman machine info/inspect

### ISSUE THREAD

**Issue by maxandersen** [containers/podman#18479]
### Feature request description

wether podman runs in rootless or rootful mode affects lot of usecase (such as use of testcontainers).

Today only way to find if rootful is set or not seem to be:

`cat `podman machine info --format json | jq -r .Host.MachineConfigDir`/podman-machine-default.json | jq .Rootful`

would be great if `podman machine info` and `podman machine inspect` would include this info.

**Comment by maxandersen** [comment]
@n1hility as discussed.

**Comment by afbjorklund** [comment]
I thought this was already available, in `podman info` ? Not sure if the actual VM is as interesting

commit https://github.com/containers/podman/commit/615df2ecd7ecc4a211d6293c753eea21cf0baab2

**Comment by n1hility** [comment]
I think the main benefit is just seeing the state regardless of whether the VM is running, which could be useful in an external tool warning or possibly changing based on the value.

**Comment by maxandersen** [comment]
Yeah. One are doing 'podman machine set --rootfull' but can't query that value without actually starting podman.

**Comment by afbjorklund** [comment]
Makes sense. There might be a similar problem regarding the version... (like: last seen version)

**Comment by rhatdan** [comment]
@n1hility Any update on this one?

**Comment by ashley-cui** [comment]
Fixed as a byproduct of https://github.com/containers/podman/pull/19666
