### ISSUE TITLE
[sys] podman play with init container: failed to remove once init container

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#18477]
I'm betting it's a bug in the test, not in podman. Filing so I don't forget:
```
not ok 548 podman play with init container
...
# podman kube play /tmp/podman_bats.lYSvJT/test.yaml
Error: failed to remove once init container CID:
      cannot remove container CID as it is running
        - running or paused containers cannot be removed without force:
           container state improper
```

Only one instance that I know of, just now in [f38 aarch64 root sqlite](https://api.cirrus-ci.com/v1/artifact/task/5167619196583936/html/sys-podman-fedora-38-aarch64-root-host-sqlite.log.html)

**Comment by Luap99** [comment]
maybe fixed by https://github.com/containers/podman/pull/18481?

**Comment by edsantiago** [comment]
I cherry-picked an earlier version of #18481 into my hammer PR. Have not seen the "failed to remove once init container" error since, in about eight CI runs. I think that PR is promising, thanks.

**Comment by edsantiago** [comment]
I see a lot of "failed to remove once init container" in my flake logs, but it seems to be only in logs where unlinkat-EBUSY has already triggered (i.e. where the entire system is hosed already). Closing, will reopen if it reoccurs without unlinkat-EBUSY.
