### ISSUE TITLE
podman machine can't start on Mac M1 with podman-desktop-0.15.0

### ISSUE THREAD

**Issue by LiZhang19817** [containers/podman#18478]
### Issue Description

Can't start podman VM on Mac M1:

Download from https://github.com/containers/podman-desktop/releases/download/v0.15.0/podman-desktop-0.15.0-universal.dmg 

```
podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Unknown Error
```

### Steps to reproduce the issue

podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Unknown Error

### Describe the results you received

podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Unknown Error

### Describe the results you expected

podman machine start successfully.

### podman info output

```yaml
Download from https://github.com/containers/podman-desktop/releases/download/v0.15.0/podman-desktop-0.15.0-universal.dmg
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
> qemu-system-x86_64

Looks like you installed the x86_64 version on your arm machine. You have to install the arm version.

I don't know what the universal installer does but it looks like it installed the wrong arch. I suggest you you report this to podman-desktop as we do not manage this installer.
