### ISSUE TITLE
Quadlet: support for the --hostname parameter

### ISSUE THREAD

**Issue by jklaiho** [containers/podman#18486]
### Feature request description

Would be nice if a `Hostname` (`HostName`?) key was available in the `.container` generators, corresponding to the `--hostname` option to `podman run`. Just another step towards feature parity.

If I had any Go experience at all, I'd send a PR for this myself, but alas.

### Have you considered any alternatives?

Of course, this can be done now using `PodmanArgs`, but its use is not recommended by the documentation.

**Comment by vrothberg** [comment]
Thanks for reaching out, @jklaiho!

I can take this request to keep my hands warm until the next meeting :)
