### ISSUE TITLE
Podman Pod loses network connectivity after some time

### ISSUE THREAD

**Issue by michaeloa** [containers/podman#18504]
### Issue Description

I am setting up a number of containers (grafana and prometheus) in a pod on Oracle Linux 9. After some time (2-3? days), the outbound connectivity stops working and both Prometheus and Grafana (running in separate containers) are not unable to scrape data from other machines.

Stop/starting the pod works, but this seems like a bug of some sort.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Set up grafana and prometheus containers in a pod and leave running
2. A few days later, none of the containers are able to access external servers. ssh, ping, curl/wget, etc are all blocked. 
3. podman pod my-pod stop; podman pod my-pod start fixes the issue.

### Describe the results you received

Lost network connectivity after a few days.

### Describe the results you expected

Network connectivity to continue working.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.27.3
  cgroupControllers:
  - memory
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: 72c22139fbca75534d8c39fd72457900f499ce2b'
  cpuUtilization:
    idlePercent: 57.45
    systemPercent: 30.2
    userPercent: 12.35
  cpus: 2
  distribution:
    distribution: '"ol"'
    variant: server
    version: "9.1"
  eventLogger: journald
  hostname: grafana-test.elhub.cloud
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.15.0-100.96.32.el9uek.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 7349215232
  memTotal: 33375318016
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /tmp/podman-run-1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.2.0-2.el9_0.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 6909423616
  swapTotal: 6937374720
  uptime: 605h 9m 58.00s (Approximately 25.21 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - container-registry.oracle.com
  - docker.io
store:
  configFile: /u01/grafana/.config/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 5
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /u01/grafana/.local/share/containers/storage
  graphRootAllocated: 4327844257792
  graphRootUsed: 28176805888
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 7
  runRoot: /tmp/podman-run-1001/containers
  volumePath: /u01/grafana/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1677582426
  BuiltTime: Tue Feb 28 11:07:06 2023
  GitCommit: ""
  GoVersion: go1.18.9
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Podman version:
Client:       Podman Engine
Version:      4.2.0
API Version:  4.2.0
Go Version:   go1.18.9
Built:        Tue Feb 28 11:07:06 2023
OS/Arch:      linux/amd64

### Additional information

Has occurred 2 times now that we are aware of, and suspect a third occasion.

**Comment by Luap99** [comment]
Can you provide an exact reproducer? How are the pods/containers created.

**Comment by michaeloa** [comment]
It's basically all deployed from ansible. Not so easy to extract the code (I'd have to extract the secrets), but it's basically just ansible commands to deploy the pod + the five containers:

```
- name: Create pod grafana-pod
    containers.podman.podman_pod:
    name: "grafana-pod"
    state: created
    infra_name: "grafana-infra"
    infra_image: "{{ docker_repository }}/rancher/pause:3.6"
    publish:
        - "{{ grafana_port }}:{{ grafana_port }}"
        - "{{ blackbox_exporter_port }}:{{ blackbox_exporter_port }}"
        - "{{ prometheus_port }}:{{ prometheus_port }}"
    become_user: "grafana"
    become: yes

- name: Create postgres container
    containers.podman.podman_container:
    name: "grafana-postgres"
    image: "{{ docker_repository }}/postgres:15.2"
    env: "{{ postgres_environment }}"
    volumes:
        - "{{ postgres_volume_mount }}"
    pod: "grafana-pod"
    restart_policy: always
    become_user: "grafana"
    become: yes

- name: Create prometheus container
    containers.podman.podman_container:
    name: "prometheus"
    image: "{{ docker_repository }}/prom/prometheus/v2.43.0"
    command: "{% for key in prometheus_commandline_args %}--{{key}}={{prometheus_commandline_args[key]}} {% endfor %}"
    volumes:
        - "{{ prometheus_bind_mount }}"
        - "{{ prometheus_volume_mount }}"
    pod: "grafana-pod"
    restart_policy: always
    become_user: "grafana"
    become: yes

- name: Create blackbox-exporter container
    containers.podman.podman_container:
    name: "blackbox-exporter"
    image: "{{ docker_repository }}/prom/blackbox-exporter:v0.23.0"
    command: "{% for key in blackbox_exporter_commandline_args %}--{{key}}={{blackbox_exporter_commandline_args[key]}} {% endfor %}"
    volumes:
        - "{{ blackbox_exporter_bind_mount }}"
    pod: "grafana-pod"
    restart_policy: always
    become_user: "grafana"
    become: yes

- name: Create grafana container
    containers.podman.podman_container:
    name: "grafana"
    image: "{{ docker_repository }}/grafana/grafana-oss:9.5.1"
    volumes: "{{ grafana_mount_volumes }}"
    pod: "grafana-pod"
    restart_policy: always
    become_user: "grafana"
    become: yes
```

With some previous code to set up the VM (adding certificates, etc) + setting up the users and volumes for the containers (also using ansible). It's relatively straightforward stuff.

**Comment by Luap99** [comment]
Sorry this isn't something I can work with.

The first think that looks of is the `runRoot: /tmp/podman-run-1001/containers`. If you are on a systemd distro that should use `/run/user/$UID/containers`. Please run `podman system reset` then make sure you are logged into the user properly, i.e. do not use sudo or su to switch users. see https://github.com/containers/podman/blob/main/troubleshooting.md#31-podman-run-fails-with-erro0000-xdg_runtime_dir-directory-runuser0-is-not-owned-by-the-current-user-or-error-creating-tmpdir-mkdir-runuser1000-permission-denied

Besides that you should check if the slirp4netns process for the pod is still running. Hoe does the cotnianer netns look like when the issue occurs, for example check `podman exec <contianer> ip addr`.

**Comment by michaeloa** [comment]
Thanks - I think this set me on the right track wrt understanding the problem. Spent some time diving down the rabbithole of ansible/podman, and the problem with ansible is of course that it basically uses sudo. So "logging in properly" is easier said than done. But doing this without ansible is really not an option for us.

Will do some more digging and get back.

**Comment by michaeloa** [comment]
Some national holidays interrupting work, but back to looking at this now. As mentioned, the problem with using ansible for scripting this is that there is not really any way one can log into the user "properly"; ansible uses su, and that's pretty hard to fix. 

Network state is unknown when connectivity is lost:
```
    1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    2: tap0: <BROADCAST,UP,LOWER_UP> mtu 65520 qdisc fq_codel state UNKNOWN qlen 1000
```
Comes back up on a restart.

Working theory is that it's the /tmp location that is the problem, since slirp4netns basically looks like this:
`   /bin/slirp4netns --disable-host-loopback --mtu=65520 --enable-sandbox --enable-seccomp --enable-ipv6 -c -e 3 -r 4 --netns-type=path /tmp/podman-run-1003/netns/netns-ec02c9a9-c51d-1f78-7574-42d39f0f767b tap0`

**Comment by michaeloa** [comment]
Well, fixed the rundir issues by setting XDG_RUNTIME_DIR this explicitly in ansible podman (so runRoot is now /run/user/1003/containers as expected); but the connectivity stil dissappears after at most a couple of days.

slirp is running and I can't find any obvious differences between network states while there is an issue, and after I've run a podman pod restart.

Stumped by this. Any suggestions as to what I can look into?

**Comment by rhatdan** [comment]
@Luap99 PTAL

**Comment by Luap99** [comment]
The interface state is always shown as UNKNOWN so that does not say anything.
If you use podman 4.4 you can try `--network pasta` instead of slirp4netns.

If slirp4netns is still running I have no idea, could be a bug in the process. Maybe attach `strace` and see if it shows anything different compared to when it works.

**Comment by rhatdan** [comment]
Not crazy about your setup either.
  runRoot: /tmp/podman-run-1001/containers

Systemd has been known to cause havok with this type of setup.

**Comment by rhatdan** [comment]
Since we gave you workarounds and suggested what could cause the issue and have not heard back, closing.

**Comment by michaeloa** [comment]
Been on vacation during the summer, which is the reason I've not been able to follow up. Will try pasta next. If that doesn't work, I guess we'll just have to drop podman as not being ready for production usage on OL9.

**Comment by deajan** [comment]
Any news on this ?

**Comment by rhatdan** [comment]
This is a closed issue, if you are having issues, please open a new one.
