### ISSUE TITLE
hyperv machine provider not honored

### ISSUE THREAD

**Issue by baude** [containers/podman#18509]
### Issue Description

I believe the following containers.conf should be valid.

```
cat C:\Users\baude\.config\containers\containers.conf
[machine]

provider = "hyperv"
memory = 4096
```

the memory value is honored but the provider is not.  this makes using hyperv impossible via containers.conf

### Steps to reproduce the issue

Steps to reproduce the issue
1.
2.
3.

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by baude** [comment]
@arixmkii ptal ... i believe this is your code?  else, @rhatdan ptal

**Comment by arixmkii** [comment]
I will check. Could you provide a command line sample to init hyperv
machine? Last time I checked it didn't have means to download FCOS
unattended way.

**Comment by baude** [comment]
@arixmkii check out https://fedorapeople.org/groups/podman/testing/hyperv/. ... the image is there.  for podman you can use the main branch.

**Comment by baude** [comment]
btw, in the readme, step 3 is no longer valid.  your code replaced that.

**Comment by arixmkii** [comment]
@baude for QEMU memory settings are honored only for config `C:\Users\Arthu\AppData\Roaming\containers\containers.conf` Could you share the documentation how containers.conf should be stacked on Windows OS?

```
C:\qcw-utils\shells>type C:\Users\Arthu\.config\containers\containers.conf
[containers]

[machine]
  memory = 8192

C:\qcw-utils\shells>podman machine init --username core --image-path testing
Extracting compressed file
Image resized.
Machine init complete
To start your machine run:

        podman machine start


C:\qcw-utils\shells>podman machine list
NAME                     VM TYPE     CREATED         LAST UP         CPUS        MEMORY      DISK SIZE
podman-machine-default*  qemu        58 seconds ago  58 seconds ago  1           2.147GB     107.4GB
```

**Comment by arixmkii** [comment]
@baude I also found this https://github.com/containers/podman/blob/main/vendor/github.com/containers/common/pkg/config/default.go#L623 It looks to me like config in the user directory should not be honored right now. Could you really confirm that memory settings from it were honored during your experiment?

**Comment by arixmkii** [comment]
Tried with HyperV. And the memory part of the config in user dir is not honored either
```

C:\qcw-utils\shells>type C:\Users\Arthu\.config\containers\containers.conf
[containers]

[machine]
  memory = 8192

C:\qcw-utils\shells>podman machine init --log-level=debug --image-path C:\Users\Arthu\Downloads\fedora-coreos\fedora-coreos-37.20230418.dev.0-hyperv.x86_64.vhdx
time="2023-05-09T21:16:08+03:00" level=info msg="podman filtering at log level debug"
time="2023-05-09T21:16:08+03:00" level=debug msg="Using Podman machine with `hyperv` virtualization provider"
time="2023-05-09T21:16:09+03:00" level=debug msg="No compression detected"
Machine init complete
To start your machine run:

        podman machine start

time="2023-05-09T21:16:15+03:00" level=debug msg="Called machine init.PersistentPostRunE(podman machine init --log-level=debug --image-path C:\\Users\\Arthu\\Downloads\\fedora-coreos\\fedora-coreos-37.20230418.dev.0-hyperv.x86_64.vhdx)"
time="2023-05-09T21:16:15+03:00" level=debug msg="Shutting down engines"

C:\qcw-utils\shells>podman machine list
NAME                     VM TYPE     CREATED         LAST UP        CPUS        MEMORY      DISK SIZE
podman-machine-default*  hyperv      10 seconds ago  292 years ago  1           2.147GB     107.4GB
```

**Comment by arixmkii** [comment]
I don't think it is a bug, but rather a change/feature request to also use user home for storing configs. I'm not aware if this was done on purpose because of some hidden bugs or incompatibilities with WSL provider.

**Comment by Luap99** [comment]
Windows uses APPDATA for pretty much all user configs. `~/.config` comes from the xdg spec https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html and I doubt any windows application uses that.
So I think APPDATA is the correct location, also see
https://github.com/containers/common/commit/0e545a1cb87362f291625f5269e4634a035db0bb and https://github.com/containers/common/commit/526ff3f9c59c63b8f013ce498d079693bfb824be
The location definitely needs to be documented in containers.conf though.
