### ISSUE TITLE
Podman can't start on Mac M1 with error message "qemu-system-x86_64: Unknown Error"

### ISSUE THREAD

**Issue by LiZhang19817** [containers/podman#18512]
### Bug description

**On my Mac M1, start podman get following error:**

`Error: Starting machine "podman-machine-default" Waiting for VM ... Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Unknown Error`

### Operating system

MacOS Ventura 13.3.1 Apple M1 Pro

### Version

0.15.0

**Comment by benoitf** [comment]
transfefring the issue to podman repository as it's an issue with starting a podman machine
