### ISSUE TITLE
podman dns does not work for containers that have been created but are not started.

### ISSUE THREAD

**Issue by hcldan** [containers/podman#18553]
### Issue Description

I am using docker-compose with podman.
I have a bridge network for container communication.

Each container has an alias in the network specified.

When I `up` the env the containers get created.
However, if one of them doesn't start or exits unexpectedly, the dns server will not resolve that host.

This leads to issues with my nginx reverse proxy where it won't start if one of the containers in the group is down.

It would be nice if the ip host mapping was cached as long as the container was still around (even if off)

### Steps to reproduce the issue

1. create a compose.yml file with 2 containers both joined to the network with aliases
2. docker-compose up --no-start
3. start only one of them
4. try to resolve the other hostname

### Describe the results you received

The other hosts cannot be resolved when they are down.

### Describe the results you expected

it would be nice for it to continue to resolve to the last known address...  or even better if containers were assigned ip addresses on container creation instead.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.27.3
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.4-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: 56561007b6a59ea175ee9a67384639721499e160'
  cpuUtilization:
    idlePercent: 98.73
    systemPercent: 0.83
    userPercent: 0.44
  cpus: 20
  distribution:
    distribution: '"rhel"'
    version: "9.1"
  eventLogger: journald
  hostname: frisbee
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.0-162.23.1.el9_1.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 18071695360
  memTotal: 66804678656
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.5-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.el9_0.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 33592176640
  swapTotal: 33592176640
  uptime: 45h 47m 22.00s (Approximately 1.88 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/username/.config/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 3
    stopped: 3
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/username/.local/share/containers/storage
  graphRootAllocated: 988412391424
  graphRootUsed: 317585338368
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 209
  runRoot: /run/user/1000/containers
  volumePath: /home/username/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1675767401
  BuiltTime: Tue Feb  7 05:56:41 2023
  GitCommit: ""
  GoVersion: go1.18.9
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

I'm using whatever is available for RHEL 9.1 at the moment.

**Comment by Luap99** [comment]
If anything this is a feature request as this works as designed.

I don't understand the use case here at all. What you are asking sounds wrong. Assigning addresses must happen on start, you can have more containers than available ips on a network so this would just break if we start to assign ips on creation.

Second resolving any address for something which is not currently running is a bad idea. We would just resolve names for something which is not reachable. That may make your nginx config happy but I really do not see how this would not lead to confusion for other callers: `name xxx not found` is a much better error message then `connection timed out`.

This really sound like you should just fix you nginx config, e.g. https://stackoverflow.com/questions/32845674/setup-nginx-not-to-crash-if-host-in-upstream-is-not-found

So overall I don't think this is a good idea and you you should fix it on your application level.

**Comment by Luap99** [comment]
I am very well aware how this works but for an internal dns server this makes no sense, it shouldn't return addresses which do not exists. IP addresses are assigned when you start the container and removed when it is stopped/exits. There is no way to implement what you are asking with the current design how networking works in podman.

Unless you specify a static address there is no point in even continuing to serve the old name when the container is stopped/exited, a new start will get very likely a new ip address thus the "cached" name would point at the wrong ip.
