### ISSUE TITLE
Container root does not have write permissions on /sys/fs/cgroup directory

### ISSUE THREAD

**Issue by starry91** [containers/podman#18550]
### Issue Description

Podman doesn't seem to create an isolated `/sys/fs/cgroup` directory inside the rootless containers and even the container root has only read permission on it. Is there a way to work around this with `cgroups v1`? I only want the container root to able to write to the `/sys/fs/cgroup` since my process (running inside the container as `root`) uses `cgroup` isolation.
Note that its okay even if the `cgroup` isolation doesn't work inside the containers but I at least want my process to be able to run without errors. (basically I want some way to mimic the `cgroup` structure inside the container so that my process does not break).

I also tried using podman's `--cgroupns=private`, but even that didn't work.

### Steps to reproduce the issue

Steps to reproduce the issue:
1. `podman run  --rm -ti fedora`
2. `ls -la /sys/fs/cgroup/` (inside the container - see that the root does not have write permission on the some folders like `memory`)

### Describe the results you received

I see the root inside the container does not have write permission on directories like `/sys/fs/cgroup/memory`, etc not allowing new cgroup directories to be created inside the container.
```
[root@22917e4570bf /]# ls -la /sys/fs/cgroup/
total 0
drwxrwxrwt 13 root   root   340 May 12 12:51 .
drwxr-xr-x  8 nobody nobody   0 May 12 08:50 ..
drwxr-xr-x  2 nobody nobody   0 May  6 01:43 blkio
lrwxrwxrwx  1 root   root    11 May 12 12:51 cpu -> cpu,cpuacct
drwxr-xr-x  2 nobody nobody   0 May  6 01:43 cpu,cpuacct
lrwxrwxrwx  1 root   root    11 May 12 12:51 cpuacct -> cpu,cpuacct
drwxr-xr-x  2 nobody nobody   0 May  6 01:43 cpuset
drwxr-xr-x  2 nobody nobody   0 May  6 01:43 devices
drwxr-xr-x  3 nobody nobody   0 May  6 01:43 freezer
drwxr-xr-x  2 nobody nobody   0 May  6 01:43 hugetlb
drwxr-xr-x  2 nobody nobody   0 May  6 01:43 memory
lrwxrwxrwx  1 root   root    16 May 12 12:51 net_cls -> net_cls,net_prio
drwxr-xr-x  2 nobody nobody   0 May  6 01:43 net_cls,net_prio
lrwxrwxrwx  1 root   root    16 May 12 12:51 net_prio -> net_cls,net_prio
drwxr-xr-x  2 nobody nobody   0 May  6 01:43 perf_event
drwxr-xr-x  2 nobody nobody   0 May  6 01:43 pids
drwxr-xr-x  2 nobody nobody   0 May  9 06:56 systemd
[root@22917e4570bf /]#
```

### Describe the results you expected

I expect the container root to have `rw` permission on the all the files and folders inside the `/sys/fs/cgroup` directory.

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
podman version - 4.4.2
OS Info:

$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
$
```
```


### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

NA

### Additional information

NA

**Comment by rhatdan** [comment]
cgroup v1 is not supported in rootless mode.

**Comment by starry91** [comment]
@rhatdan Thanks for the confirmation. Is there any known workaround (need not be very clean) using other [--cgroupns](https://docs.podman.io/en/latest/markdown/podman-run.1.html#cgroupns-mode) options like `cgroupns=<namespace>`? Some options I can think of is:
1. `cgroupns=<path_of_new_namespace>`
2. create a sub cgroup (ex: `/sys/fs/cgroup/cpu/my-group`) and give the non-root user WRITE access to it and then providing that path (`/sys/fs/cgroup/my-group`) using [--cgroup-parent](https://docs.podman.io/en/latest/markdown/podman-run.1.html#cgroup-parent-path)
3. Create a folder structure similar to `/sys/fs/cgroup/` locally and bind mount it to `/sys/fs/cgroup` inside the container.

Do you think any of the above options might work? (Since cgroupv2 is not feasible to me at the moment)

_[I am assuming these options are supported with cgroups v1 since its not mentioned in the documentation that they aren't. Please do correct me if I am wrong though.]_

**Comment by rhatdan** [comment]
I know of no way to get around this.  @giuseppe thoughts?

**Comment by giuseppe** [comment]
You could chown the files first then bind mount the cgroup structure inside the container.  Be careful though, cgroup delegation is not safe with cgroup v1

**Comment by giuseppe** [comment]
closing the issue since there was no further feedback

**Comment by starry91** [comment]
Thanks @giuseppe for the suggestion. I will try this out.
