### ISSUE TITLE
Expose rootlessport and slirp4netns api sockets by default

### ISSUE THREAD

**Issue by deliciouslytyped** [containers/podman#18562]
`rootlessport`, as part of rootlesskit, supports some kind of administration interface over an api socket:
https://github.com/rootless-containers/rootlesskit/blob/master/docs/port.md
I haven't been able to understand the rootlessport code used by podman too well, does it completely bypass most of rootlessport (and so an administration socket would not be easily usable) and invoke the port forwarding code directly, or could the socket be enabled?

Podman doesn't seem to expose this when invoking rootlessport, though it would be good for inspecting the state of rootlesskit, for debugging or otherwise. For rootful solutions one can at least look at the iptables configuration, but not here. Maybe I'm missing something simple (and no, I don't want to just look at the `podman port` output ;P), the best I've been able to do for an already running container is to dump the memory of the process and find the JSON config string with `strings`.

`slirp4netns `seems to have a similar interface, but that is already used for port forwarding, I just don't know if it's always accessible.
https://github.com/containers/podman/blob/493aac69e06605a26307bb3d774670c0b1fb5e3b/libpod/networking_slirp4netns.go#L649
However, rootlessport is the default solution.

The main rootlessport entry points seem to be these functions and files:
https://github.com/containers/podman/blob/493aac69e06605a26307bb3d774670c0b1fb5e3b/libpod/networking_slirp4netns.go#L553
https://github.com/containers/podman/blob/493aac69e06605a26307bb3d774670c0b1fb5e3b/cmd/rootlessport/main.go

**Comment by Luap99** [comment]
> I haven't been able to understand the rootlessport code used by podman too well, does it completely bypass most of rootlessport (and so an administration socket would not be easily usable) and invoke the port forwarding code directly, or could the socket be enabled?

We bypass that code so it is impossible to expose the socket.

Can you explain why you want this? I don't see the use case here. Ports are defined by the user on container creation and should not be altered at runtime.

**Comment by Luap99** [comment]
Since I didn't get an answer, closing.
