### ISSUE TITLE
e2e: rethink setenforce-0

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#18564]
Found by accident while reviewing #18544:

https://github.com/containers/podman/blob/493aac69e06605a26307bb3d774670c0b1fb5e3b/test/e2e/login_logout_test.go#L45-L50

https://github.com/containers/podman/blob/493aac69e06605a26307bb3d774670c0b1fb5e3b/test/e2e/push_test.go#L248-L252

Let's understand if/why these are needed.
* If not needed: remove
* If needed: explain in comments, and Serialize.

**Comment by Luap99** [comment]
Yes please nuke this, I was also very surprised when I saw it. This by definition also means it skips all these test as rootless  as setenfore is only allowed as root.

**Comment by vrothberg** [comment]
I didn't volunteer (yet) to do the work as time is scarce.  I had a quick look and it seems like a bit of work to get the entire file migrated.

**Comment by Luap99** [comment]
Given that this doesn't work in a parallel context anyway (TOCTOU) I am just going to remove the setenfore calls and see if CI passes (#18607). We can look into using hack/podman-registry-go another time.
