### ISSUE TITLE
wait on restart=always container: semi-undefined behavior

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#18572]
`podman wait`, on a spinning-restart container, seems to take 20s. But why?
```console
$ bin/podman run -d --name test --restart always quay.io/libpod/testimage:20221018 true
824c48800f60d385eca4814d9fe46f6c27cb4416c75afaa94ee4cf991bcd9c7b

$ for i in $(seq 1 10);do time bin/podman wait test;done
0
bin/podman wait test  0.07s user 0.10s system 0% cpu 20.300 total
0
bin/podman wait test  0.08s user 0.08s system 0% cpu 20.230 total
0
bin/podman wait test  0.08s user 0.08s system 0% cpu 20.087 total
0
bin/podman wait test  0.07s user 0.08s system 0% cpu 20.236 total
0
bin/podman wait test  0.07s user 0.09s system 0% cpu 20.302 total
0
bin/podman wait test  0.08s user 0.07s system 0% cpu 20.288 total
0
bin/podman wait test  0.08s user 0.08s system 0% cpu 20.333 total
0
bin/podman wait test  0.08s user 0.07s system 0% cpu 20.231 total
0
bin/podman wait test  0.08s user 0.08s system 0% cpu 20.113 total
0
bin/podman wait test  0.07s user 0.10s system 0% cpu 20.249 total
```
I'm not sure what the expectation should be: hang forever? Exit as soon as the container exits the first time? Abort with "this container will never exit"? (That last one is complicated by `restart=on-failure` containers).

The example above is contrived, but this behavior is important when working with pods and `play kube`.

**Comment by rhatdan** [comment]
We could try this test with Docker and see how it behaves.

**Comment by Luap99** [comment]
20 seconds is the timeout in the code: https://github.com/containers/podman/blob/e0890cae1404ede326add37ded3a3165949413d7/libpod/container_api.go#LL599C2-L599C2

**Comment by edsantiago** [comment]
Thanks for the clue. That, then, leads to a few lines down: https://github.com/containers/podman/blob/e0890cae1404ede326add37ded3a3165949413d7/libpod/container_api.go#L618-L619

...which passes, because there's an exit code in the DB even if container **state** is not actually `StateExited`.

**Comment by vrothberg** [comment]
I would expect `podman wait` to eventually exit.  The restart and wait will race with each other.

> ...which passes, because there's an exit code in the DB even if container state is not actually StateExited.

Are you sure?  If the timeout was fired, conmon has exited.

The wait code probably need some massaging.

**Comment by vrothberg** [comment]
> I would expect `podman wait` to eventually exit. The restart and wait will race with each other.

That's how docker behaves as well, see
```
[root@nebuchadnezzar vrothberg]# time docker wait 123
0

real    0m2.701s
user    0m0.016s
sys     0m0.025s
[root@nebuchadnezzar vrothberg]# time docker wait 123
0

real    0m12.480s
user    0m0.023s
sys     0m0.021s
```

**Comment by vrothberg** [comment]
So to me the behavior is (somehow) defined in that `podman wait` waits for an exit but not the final one.

I will take a look at the bug though.

**Comment by Luap99** [comment]
Right now podman wait doesn't seem to wait correctly, it always runs into the 20 seconds timeout. Before it start looking up the exit code db and then exits correctly. I think wait should exit at the first container exit. Maybe we should read back the podman events in these cases.

**Comment by vrothberg** [comment]
I opened https://github.com/containers/podman/pull/18581.  PTAL and let's see what CI has to say

**Comment by Luap99** [comment]
I assume we are good to close this one (#18581 is merged), @vrothberg?

**Comment by vrothberg** [comment]
Nice catch. I agree, let's close.
