### ISSUE TITLE
Error in podman: loading seccomp profile (/usr/share/containers/seccomp.json) failed: seccomp not enabled in this build".

### ISSUE THREAD

**Issue by rashPatil1** [containers/podman#18609]
### Issue Description

I setup podman 4.5 using below https://www.computingpost.com/how-to-install-podman-4-x-on-centos-7-rhel-7/. But now container is not running

Some error for this podman version
"Error: loading seccomp profile (/usr/share/containers/seccomp.json) failed: seccomp not enabled in this build".

Can someone help here?

### Steps to reproduce the issue

Steps to reproduce the issue
1.
2.
3.

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rhatdan** [comment]
Looks like you did not build podman with seccomp support?

**Comment by rashPatil1** [comment]
> Looks like you did not build podman with seccomp support?

@rhatdan How is that done? I am not aware on it yet

**Comment by giuseppe** [comment]
have you used `make BUILDTAGS="selinux seccomp"`?

**Comment by rashPatil1** [comment]
> have you used `make BUILDTAGS="selinux seccomp"`?
I had tried but then found that there was some error. Is this compulsory?

**Comment by giuseppe** [comment]
you need to make sure seccomp is not referenced anywhere, e.g. the seccomp profile path must be empty.

**Comment by rhatdan** [comment]
This is not really an upstream issue, so closing.
