### ISSUE TITLE
Docker Composer in Docker in Rootless Podman: volume mounting fails

### ISSUE THREAD

**Issue by ST-Apps** [containers/podman#18600]
### Issue Description

``I am in the process of replacing my old Docker Executor for GitLab Pipelines with Podman, and I already have a configured Rootless Podman setup.

Most of the jobs works fine out of the box, however I'm having issues with jobs using Docker Compose (which cannot be migrated to Podman yet). For those unfamiliar with GitLab Runner Docker Executor, this works by spawning a container in which the job is executed.

Given that in the current scenario the job is launching a Docker Compose script, this ends up generating a series of nested containers that can be summarized like this:
- `docker:20` and `docker:23.0.1-dind` running on the Rootless Podman VM
- Docker Compose running inside `docker:20`
- Docker Compose generated containers running inside `docker:20` as well

When executing `docker compose up`, what happens is that I get the following error:

> Error response from daemon: make cli opts(): making volume mountpoint for volume /builds/mygroup/myproject: mkdir /builds: permission denied

Judging by the error, seems like that Compose is trying to create a `/builds` folder inside my generated container but it fails because of a lack of permissions.

This is the relevant snippet of the Compose spec:
```yaml
services:
  instance:
    build:
      context: ..
      dockerfile: file
    volumes:
    - ../:/opt/app
    - dev.config:/root/config
    - ~/.gitignore:/root/.gitignore
    - /var/run/docker.sock:/var/run/docker.sock
```

The file is located at `/builds/mygroup/myproject/.compose`, meaning that its context will be `/builds/mygroup/myproject`.

For starters what I don't understand is why is it attempting to create the `/builds` folder if this one is not a mount (e.g. never appears on the right side of volumes definitions). I'm also starting to think that probably this scenario is not feasible but I cannot find enough information on this.

I also tried adding `:z` to every volume definition, as well as completely disabling SELinux, but I don't know what to do more.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create a Rootless Podman GitLab Runner
2. Create a Docker Compose file like the one shown above
3. Execute `docker compose up` in a GitLab pipeline targeting the Runner at step 1

### Describe the results you received

Describe the results you received

### Describe the results you expected

Error response from daemon: make cli opts(): making volume mountpoint for volume /builds/mygroup/myproject: mkdir /builds: permission denied

### podman info output

```yaml
Podman v4.5.0-1
Fedora Cloud 38 x86_64
```

### Podman in a container

Yes

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
Docker creates the volume source on the host when it does not exists. The podman docker compat API mirrors that behaviour.
What permissions does the `/builds` directory have, sounds like you do not give the rootless podman user access to that directory so it tries to create it.

**Comment by ST-Apps** [comment]
Let me see if I got it right.

Does this mean that the `docker:20` container, since it has a mounted `/var/run/docker.sock`, is trying to send the host's `/build` folder as a Docker Compose context rather than its own?

If this is the case, can we change this behavior somehow?

I would expect the client (in this case the `docker:20` container) to be the one to send its local files to the Docker Daemon, needing to have the files on the host as well seems counterintuitive and it even defeats the purpose of build isolation somehow (assuming I got your reply correctly).

**Comment by Luap99** [comment]
I have no idea how your setup looks like but if you mount /run/docker.sock then yes you aren't running nested containers you only run a client in the container but talk to the host daemon. The containers are launched by the server if this runs on the host then it will use the volumes on the host. There is no way to change that.
