### ISSUE TITLE
Wrong user id on Debian

### ISSUE THREAD

**Issue by Mte90** [containers/podman#18633]
### Issue Description

I have an old workstation that I am still using with debian sid since 10 years.

So I had some issue on running podman for missing setuid/setgid that was missing and I added them. I changed the id from 1000 to 10000 because there was some issues.
I am able only to run on root, if I run from the user I get this:

![immagine](https://github.com/containers/podman/assets/403283/ad40c18a-03fc-44cd-a004-212b2bbfbd24)

If you need more commands to run let me know.

### Steps to reproduce the issue

The screen above

### Describe the results you received

An error

### Describe the results you expected

Don't get any error...

### podman info output

```yaml
Debian sid, podman 4.3.1+ds1-8
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
Switching the UID is not supported by podman as we store full paths in our db. https://github.com/containers/podman/issues/11377

Something like `rm -rf ~/.local/share/containers/storage/` should remove all podman data and get it back working after that.

**Comment by Mte90** [comment]
Doesn't fix that command the issue I have.
I replied on that ticket 3 weeks ago for the same issue.

**Comment by Luap99** [comment]
Do you have a containers.conf or storage.conf that defines this incorrect path?

**Comment by Luap99** [comment]
Is XDG_RUNTIME_DIR set properly?

**Comment by Mte90** [comment]
$XDG_RUNTIME_DIR = /tmp/runtime-mte90

About containers.conf I don't find that file, there isn't anything on `/etc/containers/storage.conf`.

**Comment by Mte90** [comment]
Any hint where is getting this value?
I am checking the code but I don't find anything.

**Comment by Luap99** [comment]
try running podman --log-level debug ...

**Comment by Mte90** [comment]
Bingo!

I mapped the folder for podman stuff in a different folder so in my case the database it was on `/media/mte90/Doh-cker/junk/rootless-storage/libpod/bolt_state.db`. Removed that file and now is working as non root.

Just for someone looking for the same command ```podman --log-level debug info```
