### ISSUE TITLE
New buildah/timeout/external container flakes

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#18631]
New weird flakes seen in buildah treadmill. I'm filing all under one issue, but they might be unrelated:
```
not ok 119 podman ps --external
...
# podman build -t thiswillneverexist -
STEP 1/3: FROM quay.io/libpod/testimage:20221018
STEP 2/3: RUN touch /intermediate.image.to.be.pruned
--> 0c116d0cdcf9
STEP 3/3: RUN sleep 30
timeout: sending signal TERM to command '/var/tmp/go/src/github.com/containers/podman/bin/podman'
[ rc=124 (expected) ]
#/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#|     FAIL: podman build did not get killed within 10 seconds
#| expected: -le 10
#|   actual:     32
```
(ISTR something changing in buildah signal handling recently)

And:
```
not ok 248 podman diff with buildah container 
...
$ podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
quay.io/libpod/testimage:20221018 f5a99120db64
buildahctr
$ podman diff --format json buildahctr
Error: buildahctr not found: layer not known
```
And:
```
not ok 137 podman rm container from storage
...
$ podman container exists --external testimage-working-container
[ rc=1 (** EXPECTED 0 **) ]
```
All of these are buildah-related. I haven't seen them in any other PRs, but this has been the lightest PR week in memory. If we don't see these in regular podman CI, it might be something in the new buildah vendoring.

* debian-12 : sys podman debian-12 root host boltdb
    * [05-19 09:06](https://api.cirrus-ci.com/v1/artifact/task/6575945180512256/html/sys-podman-debian-12-root-host-boltdb.log.html#t--00119) in [sys] podman ps --external
* debian-12 : sys podman debian-12 rootless host boltdb
    * [05-19 09:05](https://api.cirrus-ci.com/v1/artifact/task/4851910948159488/html/sys-podman-debian-12-rootless-host-boltdb.log.html#t--00137) in [sys] podman rm container from storage
    * [05-19 09:05](https://api.cirrus-ci.com/v1/artifact/task/4851910948159488/html/sys-podman-debian-12-rootless-host-boltdb.log.html#t--00248) in [sys] podman diff with buildah container
* rawhide : sys podman rawhide rootless host sqlite
    * [05-19 09:09](https://api.cirrus-ci.com/v1/artifact/task/6259285831712768/html/sys-podman-rawhide-rootless-host-sqlite.log.html#t--00119) in [sys] podman ps --external

**Comment by edsantiago** [comment]
Flakes being seen [in the wild](https://api.cirrus-ci.com/v1/artifact/task/5611877124800512/html/sys-podman-debian-12-rootless-host-sqlite.log.html), outside of the treadmill. Next guess: something to do with the `buildah` version in new VM images?

**Comment by edsantiago** [comment]
Everything points to something broken in containers/storage.

**Comment by edsantiago** [comment]
All the 13808 failures below are the buildah treadmill PR.

All the 17831 failures below are from my hammer-CI PR, during a period this weekend when I had cherry-picked #18634, a test PR that included a new containers/storage. That is why I believe the problem is in containers/storage. Today I have reverted that PR from my hammer-CI PR, and am no longer seeing those buildah failures.


* debian-12 : sys podman debian-12 root host boltdb
  * PR #13808
    * [05-22 14:16](https://api.cirrus-ci.com/v1/artifact/task/5543651669966848/html/sys-podman-debian-12-root-host-boltdb.log.html#t--00120) in [sys] podman ps --external
    * [05-19 19:46](https://api.cirrus-ci.com/v1/artifact/task/5167940815814656/html/sys-podman-debian-12-root-host-boltdb.log.html#t--00119) in [sys] podman ps --external
* debian-12 : sys podman debian-12 rootless host boltdb
  * PR #13808
    * [05-22 14:16](https://api.cirrus-ci.com/v1/artifact/task/6458445344276480/html/sys-podman-debian-12-rootless-host-boltdb.log.html#t--00138) in [sys] podman rm container from storage
    * [05-22 14:16](https://api.cirrus-ci.com/v1/artifact/task/6458445344276480/html/sys-podman-debian-12-rootless-host-boltdb.log.html#t--00249) in [sys] podman diff with buildah container
    * [05-19 19:45](https://api.cirrus-ci.com/v1/artifact/task/6716053187723264/html/sys-podman-debian-12-rootless-host-boltdb.log.html#t--00137) in [sys] podman rm container from storage
    * [05-19 19:45](https://api.cirrus-ci.com/v1/artifact/task/6716053187723264/html/sys-podman-debian-12-rootless-host-boltdb.log.html#t--00248) in [sys] podman diff with buildah container
* debian-12 : sys podman debian-12 rootless host sqlite
  * PR #17831
    * [05-22 11:58](https://api.cirrus-ci.com/v1/artifact/task/6378817355251712/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00137) in [sys] podman rm container from storage
    * [05-22 11:58](https://api.cirrus-ci.com/v1/artifact/task/6378817355251712/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00248) in [sys] podman diff with buildah container
    * [05-22 10:56](https://api.cirrus-ci.com/v1/artifact/task/6689920962527232/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00137) in [sys] podman rm container from storage
    * [05-22 10:56](https://api.cirrus-ci.com/v1/artifact/task/6689920962527232/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00248) in [sys] podman diff with buildah container
    * [05-22 09:39](https://api.cirrus-ci.com/v1/artifact/task/5090420682653696/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00137) in [sys] podman rm container from storage
    * [05-22 09:39](https://api.cirrus-ci.com/v1/artifact/task/5090420682653696/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00248) in [sys] podman diff with buildah container
    * [05-22 08:25](https://api.cirrus-ci.com/v1/artifact/task/6399702539698176/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00137) in [sys] podman rm container from storage
    * [05-22 08:25](https://api.cirrus-ci.com/v1/artifact/task/6399702539698176/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00248) in [sys] podman diff with buildah container
    * [05-21 22:10](https://api.cirrus-ci.com/v1/artifact/task/5511494712950784/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00137) in [sys] podman rm container from storage
    * [05-21 22:10](https://api.cirrus-ci.com/v1/artifact/task/5511494712950784/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00248) in [sys] podman diff with buildah container
    * [05-21 20:45](https://api.cirrus-ci.com/v1/artifact/task/5472837423595520/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00137) in [sys] podman rm container from storage
    * [05-21 20:45](https://api.cirrus-ci.com/v1/artifact/task/5472837423595520/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00248) in [sys] podman diff with buildah container
    * [05-21 08:34](https://api.cirrus-ci.com/v1/artifact/task/5262270545002496/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00137) in [sys] podman rm container from storage
    * [05-21 08:34](https://api.cirrus-ci.com/v1/artifact/task/5262270545002496/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00248) in [sys] podman diff with buildah container
    * [05-20 06:31](https://api.cirrus-ci.com/v1/artifact/task/4803070626889728/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00137) in [sys] podman rm container from storage
    * [05-20 06:31](https://api.cirrus-ci.com/v1/artifact/task/4803070626889728/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00248) in [sys] podman diff with buildah container
    * [05-19 23:14](https://api.cirrus-ci.com/v1/artifact/task/5601047834525696/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00137) in [sys] podman rm container from storage
    * [05-19 23:14](https://api.cirrus-ci.com/v1/artifact/task/5601047834525696/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00248) in [sys] podman diff with buildah container
    * [05-19 22:06](https://api.cirrus-ci.com/v1/artifact/task/4860767808258048/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00137) in [sys] podman rm container from storage
    * [05-19 22:06](https://api.cirrus-ci.com/v1/artifact/task/4860767808258048/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00248) in [sys] podman diff with buildah container
    * [05-19 21:03](https://api.cirrus-ci.com/v1/artifact/task/6638921849765888/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00137) in [sys] podman rm container from storage
    * [05-19 21:03](https://api.cirrus-ci.com/v1/artifact/task/6638921849765888/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00248) in [sys] podman diff with buildah container
    * [05-19 19:56](https://api.cirrus-ci.com/v1/artifact/task/5928721257857024/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00137) in [sys] podman rm container from storage
    * [05-19 19:56](https://api.cirrus-ci.com/v1/artifact/task/5928721257857024/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00248) in [sys] podman diff with buildah container
    * [05-19 18:41](https://api.cirrus-ci.com/v1/artifact/task/4582960196747264/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00137) in [sys] podman rm container from storage
    * [05-19 18:41](https://api.cirrus-ci.com/v1/artifact/task/4582960196747264/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00248) in [sys] podman diff with buildah container
    * [05-19 17:42](https://api.cirrus-ci.com/v1/artifact/task/6526679724589056/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00137) in [sys] podman rm container from storage
    * [05-19 17:42](https://api.cirrus-ci.com/v1/artifact/task/6526679724589056/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00248) in [sys] podman diff with buildah container
    * [05-19 16:10](https://api.cirrus-ci.com/v1/artifact/task/5611877124800512/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00137) in [sys] podman rm container from storage
    * [05-19 16:10](https://api.cirrus-ci.com/v1/artifact/task/5611877124800512/html/sys-podman-debian-12-rootless-host-sqlite.log.html#t--00248) in [sys] podman diff with buildah container
* fedora-38 : sys podman fedora-38 root host boltdb
  * PR #13808
    * [05-22 14:23](https://api.cirrus-ci.com/v1/artifact/task/5262176693256192/html/sys-podman-fedora-38-root-host-boltdb.log.html#t--00120) in [sys] podman ps --external

**Comment by mtrmac** [comment]
> All the 17831 failures below are from my hammer-CI PR, during a period this weekend when I had cherry-picked #18634, a test PR that included a new containers/storage.

Assuming that was github.com/mtrmac/storage v0.0.0-20230519165505-36c85d0b2b46 , that means upstream c/storage between v1.46.1 and ceaf6ce2c54a0a2b184b831a732c722758979e81 .

a short-list of relevant PRs (skipping dependency updates, non-overlay changes, and entirely new unused features):
- https://github.com/containers/storage/pull/1603
- https://github.com/containers/storage/pull/1601
- https://github.com/containers/storage/pull/1589
- https://github.com/containers/storage/pull/1581
- https://github.com/containers/storage/pull/1577
- https://github.com/containers/storage/pull/1578
- https://github.com/containers/storage/pull/1549
- https://github.com/containers/storage/pull/1571
- https://github.com/containers/storage/pull/1563
- https://github.com/containers/storage/pull/1568
- https://github.com/containers/storage/pull/1564

To me, it seems https://github.com/containers/storage/pull/1549 as the highest-risk change in this area, but there are certainly other candidates.

**Comment by edsantiago** [comment]
Uh-oh. [this](https://api.cirrus-ci.com/v1/artifact/task/5379214719844352/html/int-podman-fedora-38-root-host-boltdb.log.html#t--podman-image-rm-concurrent-with-shared-layers--1) might be the same bug, *without( the new containers/storage. It's really hard to tell, because nobody is submitting PRs the last few weeks.

```
# podman [options] rmi -f rmtest:1
Error: committing container for step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:run Args:[touch rmtest:8] Flags:[] Attrs:map[] Message:RUN touch rmtest:8 Original:RUN touch rmtest:8}: copying layers and metadata for container "802e6990add8b793b1cb8bbef78ae6cff2d027aa57397fa913d3fdca49170be1": committing the finished image: creating image "cde9f59aba1cf8c2625eceef9009afd9225fa12b2cfacf7d8bc6a850d41eafad": layer not known
```

**Comment by mtrmac** [comment]
That (`podman image rm - concurrent with shared layers`) is, I think at a first glance, entirely unrelated.

It seems to me that the test is buggy — it claims to test concurrent removal, but it tests concurrent (build + removal); and if an image is removed while another is being built from the same layers, I can imagine that failing (a build doesn’t hold a race-free “reference” to a layer that would protect it against concurrent removals).

Actually, well, the lack of a race-free “reference” is arguably a bug, but it’s not _the_ bug reportedly being tested by the test; https://github.com/containers/podman/pull/9266 only intended to make removes not fail against concurrent removals.

**Comment by edsantiago** [comment]
Thank you @mtrmac. I just panicked without looking closely.

**Comment by mtrmac** [comment]
@edsantiago I do think that build&rm one one is worth tracking and fixing.

**Comment by mtrmac** [comment]
Filed https://github.com/containers/podman/issues/18659 for my concurrent `rm` theory.

**Comment by nalind** [comment]
Aside from https://github.com/containers/buildah/pull/4813, I think https://github.com/containers/storage/pull/1571 is causing podman (with a containers/storage that incorporates it) and the system default version of buildah (built with a containers/storage that didn't incorporate it) to default to different storage drivers, so they see different sets of layers and images.

There are multiple options for getting them to agree.  Set `STORAGE_DRIVER` in the environment to `$($PODMAN $_PODMAN_TEST_OPTS info -f '{{.Store.GraphDriverName}}')`.  Create ~/.config/containers/storage.conf.  Incorporate the default that podman selects into the configuration file for CI.

**Comment by flouthoc** [comment]
> To me, it seems https://github.com/containers/storage/pull/1549 is the highest-risk change in this area, but there are certainly other candidates.

@mtrmac I was testing it with `podman` with https://github.com/containers/podman/pull/18224 and I never saw any race or issues with CI until I rebased recently and saw some debian failures ( debian failures looked unrelated to the PR ).  ( But let me take a look again and see if I missed anything )

**Comment by flouthoc** [comment]
Regarding following tests
```
[sys] podman rm container from storage
[sys] podman diff with buildah container
```
I think `buildah` version in VM might be the very much issue.

>There are multiple options for getting them to agree. Set STORAGE_DRIVER in the environment to $($PODMAN $_PODMAN_TEST_OPTS info -f '{{.Store.GraphDriverName}}'). Create ~/.config/containers/storage.conf. Incorporate the default that podman selects into the configuration file for CI.

`podman diff with buildah container` fails for me when storage driver is not set in `storage.conf` but error is different from what i see in CI but both tests pass for me with latest buildah binary and when storage is configured correctly.

**Comment by edsantiago** [comment]
I'm having trouble following the thread, and I don't have a way to play with debian. But I just think it's important to point out that system tests do not (and must not) muck around with setting `STORAGE_DRIVER` or adding `--this --that` options. They are intended to test our tools as configured on a real system. If there is an incompatibility between podman and buildah, on a system that could conceivable look like a real-world one, my inclination would be to fix our tools so they handle this situation better.

**Comment by rhatdan** [comment]
@edsantiago update on this issue?

**Comment by flouthoc** [comment]
I think this is similar what we saw in treadmill and was recently fixed by doing a workaround for debian. But I think @edsantiago can confirm this.

**Comment by edsantiago** [comment]
I do not understand the status of this bug. As best I can tell, #18822 changed the CI setup something something overlay/vfs/debian. Since then I have only run the buildah treadmill 2-3 times, because there have been very few buildah PRs. I have not seen these errors.

To me that means the bug has been swept under the carpet, not fixed. Opinions differ on this: some may believe the issue is fixed; some may believe that it's a difficult situation with no real good fix. I will step out of this discussion for now. If someone truly believes this is fixed, feel free to close this issue. If at all possible, please include a comment defending your actions.

**Comment by mtrmac** [comment]
My very imprecise impression, just skimming the conversations and not checking the details myself, is that Nalin diagnosed this in https://github.com/containers/podman/issues/18631#issuecomment-1558184454 , and that @flouthoc fixed the c/storage behavior in https://github.com/containers/storage/pull/1618 / https://github.com/containers/storage/pull/1637 .

Those c/storage changes are included in Podman since https://github.com/containers/podman/commit/e5399aaf3c10b03124e4b6855bb3dd5b9a1135cc .

@flouthoc PTAL and correct me if I’m wrong.

**Comment by flouthoc** [comment]
@mtrmac Yes, regarding https://github.com/containers/podman/pull/18822 we had a discussion in a watercooler that it is hard to ensure this compat for older version between `(new) podman <-> (old) buildah` hence we decided to create a workaround for debian  https://github.com/containers/podman/pull/18822 . For newer version this should be fixed via https://github.com/containers/storage/pull/1618 / https://github.com/containers/storage/pull/1637 .

**Comment by edsantiago** [comment]
#13808 is passing again. Closing.
