### ISSUE TITLE
Podman4 removed from coprs/rhcontainerbot

### ISSUE THREAD

**Issue by emmanuel-apau** [containers/podman#18635]
### Issue Description

Podman4 is missing from the copr repository https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman4/

is there another repository to find podman4? i used to use this repo to install it on fedora 35

### Podman in a container

Yes

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

**Comment by Luap99** [comment]
Fedora 35 and 36 are EOL, the latest podman version is in all currently active fedora releases so this repo was removed.
If you are looking for something even more bleeding edge there is https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/
cc @lsm5
