### ISSUE TITLE
Error restarting podman machine too quickly

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman#18648]
### Bug description

If I stop and restart a Podman machine 'too quickly' I get the failure below. It doesn't happen often - most of the time I can click as fast as possible and there's no problem, but other times I was slower and see this. 

### Operating system

macOS 13.3 M1

### Version

next (development version)

### Steps to reproduce

Create a new Podman machine. Start it, then try to stop and restart as fast as possible from the Settings > Resources page.

### Relevant log output

```shell
index.ts:134 main ↪️ [podman] Error: Error: qemu exited unexpectedly with exit code 1, stderr: qemu-system-aarch64: cannot create PID file: Cannot lock pid file: Resource temporarily unavailable

    at ChildProcess.<anonymous> (/Users/deboer/git/podman-desktop/extensions/podman/dist/extension.js:140:24)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
(
```

**Comment by benoitf** [comment]
looks like a dup of https://github.com/containers/podman/issues/16054

**Comment by deboer-tim** [comment]
Yup, agreed.
