### ISSUE TITLE
PublishPort in podman-systemd.unit(5) doesn’t document setting of the protocol

### ISSUE THREAD

**Issue by mcepl** [containers/podman#18641]
### Issue Description

When looking at the documentation on https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html (which I suppose is current) it doesn’t contain for the option `PublishPort` the equivalent of the text from `--publish` documentation in `podman-run(1)` manpage:

> By default, Podman publishes TCP ports. To publish a UDP port instead, give udp as protocol. To publish both TCP and UDP ports, set --publish twice, with tcp, and udp as protocols respectively. Rootful containers can also publish ports using the sctp protocol.

And yet, when I set up in `.container` file this in the `Container` section:

```ini
PublishPort=127.0.0.1:51413:51413/udp
```

I get perfectly correct output in the generated `.service` file:

```sh
--publish 127.0.0.1:51413:51413/udp
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. Look at the documentation
2.
3.

### Describe the results you received

Documentation on setting of the transport protocol is missing.

### Describe the results you expected

Documentation would include the information I copied above

### podman info output

```yaml
not applicable
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

**Comment by vrothberg** [comment]
Great catch, @mcepl. Thanks for reporting!

Are you interested in opening a PR and extending the docs to cover `PublishPort`?

**Comment by mcepl** [comment]
Please, no, I have already too many projects cloned. Please, do so yourself.

**Comment by rhatdan** [comment]
It is there now.
```
   PublishPort=
       Exposes a port, or a range of ports (e.g. 50-59), from the container to the host. Equivalent to the Podman --publish option. The format is similar to the  Podman  options,  which  is  of  the  form  ip:hostPort:containerPort,
       ip::containerPort, hostPort:containerPort or containerPort, where the number of host and container ports must be the same (in the case of a range).

       If the IP is set to 0.0.0.0 or not set at all, the port is bound on all IPv4 addresses on the host; use [::] for IPv6.

       Note that not listing a host port means that Podman automatically selects one, and it may be different for each invocation of service. This makes that a less useful option. The allocated port can be found with the podman port
       command.

       This key can be listed multiple times.
```
