### ISSUE TITLE
"podman image rm - concurrent with shared layers" seems racy

### ISSUE THREAD

**Issue by mtrmac** [containers/podman#18659]
### Issue Description

https://github.com/containers/podman/issues/18631 links to [a test failure](https://api.cirrus-ci.com/v1/artifact/task/5379214719844352/html/int-podman-fedora-38-root-host-boltdb.log.html#t--podman-image-rm-concurrent-with-shared-layers--1). 

AFAICS the test was added in #9266, with code that was supposed to make `podman rm` more robust against concurrent removals.

But the test does not quite test _that_: it tests concurrent (build + remove).

AFAICS this means that during a build, a layer can be created, and concurrently an image removal can remove that layer as dangling. (During builds, we don’t have a “reference” pointing to a created layer until an image is created pointing at a layer stack; that’s racy vs. concurrent removals.)

Arguably this build-vs-`rm` race is an user-visible problem we should fix, but it’s not trivially obvious how.

Meanwhile, the test is failing on something it, AFAICS, it wasn’t intended to trigger.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Read https://api.cirrus-ci.com/v1/artifact/task/5379214719844352/html/int-podman-fedora-38-root-host-boltdb.log.html#t--podman-image-rm-concurrent-with-shared-layers--1
2. Read the test code
3. Ponder

### Describe the results you received

A test fails in the “build” phase, after at least one removal has happened.

### Describe the results you expected

The test not failing

### podman info output

```yaml
I guess https://api.cirrus-ci.com/v1/artifact/task/5379214719844352/html/int-podman-fedora-38-root-host-boltdb.log.html#t--podman-image-rm-concurrent-with-shared-layers--1 implicitly contains that data
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Originally discussed in https://github.com/containers/podman/issues/18631#issuecomment-1557915088 .

**Comment by flouthoc** [comment]
Shouldn't storage have write-locks on layers created by a build, till the build ends ? i.e other instances should be able to read but not delete layers till build process unlocks it.

**Comment by edsantiago** [comment]
So, I think this might be the same as #18449. Should I close that one, pointing here?

**Comment by mtrmac** [comment]
#18664 hopefully fixes this flake.

---

> So, I think this might be the same as https://github.com/containers/podman/issues/18449 

It is, AFAICS.

**Comment by edsantiago** [comment]
Here's a slightly new symptom from the same test, a different flake, seen in [f38 root](https://api.cirrus-ci.com/v1/artifact/task/6597180908109824/html/int-podman-fedora-38-root-host-sqlite.log.html#t--podman-image-rm-concurrent-with-shared-layers--1):
```
podman image rm - concurrent with shared layers
...
time="2023-05-18T16:06:46-05:00"
level=warning
msg="Failed to determine if an image is a parent: reading image \"8eda20fb4f68dc6acb3aabb16d4c11b38db82116782ea2866c79b2b602f9e910\":
     locating image with ID \"8eda20fb4f68dc6acb3aabb16d4c11b38db82116782ea2866c79b2b602f9e910\":
     image not known, ignoring the error"
```
I'm assuming it's the same root cause.

And here's the full list of flakes this month:

* fedora-38 : int podman fedora-38 root host boltdb
    * [05-22 15:54](https://api.cirrus-ci.com/v1/artifact/task/5379214719844352/html/int-podman-fedora-38-root-host-boltdb.log.html#t--podman-image-rm-concurrent-with-shared-layers--1) in podman image rm - concurrent with shared layers
* fedora-38 : int podman fedora-38 root host sqlite
    * [05-18 17:32](https://api.cirrus-ci.com/v1/artifact/task/6597180908109824/html/int-podman-fedora-38-root-host-sqlite.log.html#t--podman-image-rm-concurrent-with-shared-layers--1) in podman image rm - concurrent with shared layers
    * [05-06 17:07](https://api.cirrus-ci.com/v1/artifact/task/6324159668551680/html/int-podman-fedora-38-root-host-sqlite.log.html#t--podman-image-rm-concurrent-with-shared-layers--1) in podman image rm - concurrent with shared layers
* fedora-38 : int remote fedora-38 root host boltdb [remote]
    * [05-10 23:46](https://api.cirrus-ci.com/v1/artifact/task/5937734649380864/html/int-remote-fedora-38-root-host-boltdb.log.html#t--podman-image-rm-concurrent-with-shared-layers--1) in podman image rm - concurrent with shared layers
* rawhide : int remote rawhide root host sqlite [remote]
    * [05-03 16:16](https://api.cirrus-ci.com/v1/artifact/task/5624177676255232/html/int-remote-rawhide-root-host-sqlite.log.html#t--podman-image-rm-concurrent-with-shared-layers--1) in podman image rm - concurrent with shared layers

**Comment by mtrmac** [comment]
That’s a great solution.
