### ISSUE TITLE
`podman load` won't load a file with `:`

### ISSUE THREAD

**Issue by Hi-Angel** [containers/podman#18673]
### Issue Description

As the title says. I stumbled upon it, because many images have a colon in their name, so I tried to unpack an image to a file with a colon as well. But then executing a `podman load -i ./file_os:version` errors out.

Note: to simplify steps-to-reproduce I use an invalid OCI file, because that doesn't really matter in the context of the problem.

### Steps to reproduce the issue

Steps to reproduce the issue *(in terms of terminal commands)*

```haskell
touch ubuntu:22.04.tar && podman load -i ./ubuntu:22.04.tar
```

### Describe the results you received

Complaints about a colon:

```haskell
Error: payload does not match any of the supported image formats:
 * oci: Invalid OCI reference: path ./ubuntu:22.04.tar contains a colon
 * oci-archive: Invalid OCI reference: path ./ubuntu:22.04.tar contains a colon
 * docker-archive: opening file "./ubuntu": open ./ubuntu: no such file or directory
 * dir: open ubuntu:22.04.tar/manifest.json: not a directory
```

### Describe the results you expected

Only complaints about the file being an invalid OCI archive, such as:

```
Error: payload does not match any of the supported image formats:
 * oci: parsing "localhost/./ubuntu_22.04.tar": parsing named reference "localhost/./ubuntu_22.04.tar": invalid reference format
 * oci-archive: loading index: open /var/tmp/oci1896190274/index.json: no such file or directory
 * docker-archive: loading tar component manifest.json: file does not exist
 * dir: open ubuntu_22.04.tar/manifest.json: not a directory
```

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.7-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: f633919178f6c8ee4fb41b848a056ec33f8d707d'
  cpuUtilization:
    idlePercent: 67.83
    systemPercent: 8.41
    userPercent: 23.75
  cpus: 4
  databaseBackend: boltdb
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: constantine-N61Ja
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 6.3.1-zen2-1-zen
  linkmode: dynamic
  logDriver: journald
  memFree: 2754531328
  memTotal: 8223801344
  networkBackend: cni
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.8.3-2
    path: /usr/bin/crun
    version: |-
      crun version 1.8.3
      commit: 59f2beb7efb0d35611d5818fd0311883676f6f7e
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.2.0-1
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 2587676672
  swapTotal: 7918841856
  uptime: 59h 32m 40.00s (Approximately 2.46 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /home/constantine/.config/containers/storage.conf
  containerStore:
    number: 8
    paused: 0
    running: 1
    stopped: 7
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/constantine/.local/share/containers/storage
  graphRootAllocated: 991614205952
  graphRootUsed: 810232426496
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 71
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/constantine/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.0
  Built: 1681856273
  BuiltTime: Wed Apr 19 01:17:53 2023
  GitCommit: 75e3c12579d391b81d871fd1cded6cf0d043550a-dirty
  GoVersion: go1.20.3
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

**Comment by vrothberg** [comment]
Thanks for reaching out, @Hi-Angel !

Yes, colons in file paths are not supported as they are used for referencing images in multi-image archives (see https://github.com/containers/image/blob/main/docs/containers-transports.5.md#ocipathreference).  While it's mentioned in `man containers-transports`, I think it wouldn't hurt to highlight that in the `podman-save` and `-load` man pages. Would that work for you?

**Comment by vrothberg** [comment]
I like your proposal.  My post-lunch brain didn't consider this option :^)
@mtrmac WDYT?

**Comment by Hi-Angel** [comment]
Well, at least it may be possible to process the `-i` command line argument of `podman load` to bail out with an explicit error that `:` is a special symbol used elsewhere in the internals and so needs to be avoided.

**Comment by Hi-Angel** [comment]
@github-actions yea, I presume still relevant

**Comment by rhatdan** [comment]
Please show the exact error you would like to see?

**Comment by Hi-Angel** [comment]
> Please show the exact error you would like to see?

Well, I think a `A colon is not allowed in the filename. Aborting…` might work. In case a colon is not the only character prohibited, a message like this may work: `The following characters are not allowed in a file name "…list…". Aborting…`. Or if you don't want to mention any specific characters at all *(which would be slightly worse usability, but figuring out "prohibited characters" most likely is an easy task anyway)*, this may work `Filename contains characters that are not allowed. Aborting…`.

**Comment by rhatdan** [comment]
Well the first error returned told you that.
So you want to go from:
```
$ touch ubuntu:22.04.tar && podman load -i ./ubuntu:22.04.tar
Error: payload does not match any of the supported image formats:
 * oci: Invalid OCI reference: path ./ubuntu:22.04.tar contains a colon
 * oci-archive: Invalid OCI reference: path ./ubuntu:22.04.tar contains a colon
 * docker-archive: opening file "./ubuntu": open ./ubuntu: no such file or directory
 * dir: open ubuntu:22.04.tar/manifest.json: not a directory
```
to
```
$ touch ubuntu:22.04.tar && podman load -i ./ubuntu:22.04.tar
oci: Invalid OCI reference: path ./ubuntu:22.04.tar contains a colon

**Comment by Hi-Angel** [comment]
The "oci: Invalid OCI reference" is just some internal detail that says nothing at all to a user. I think it's better to just `Error: path ./ubuntu:22.04.tar contains a colon`

**Comment by rhatdan** [comment]
The thing is we are trying not to put to much image name parsing in the client tool, since ib the past podman broke things allowed by the containers/image library. We also had situations where buildah/podamn and other tools disagreed on allowable image names.

**Comment by Hi-Angel** [comment]
Well… I don't the expertise to give any useful comment here… If you think improving the error message here will put a maintenance burden, then indeed it may be better to just close the issue. The message `podman` currently prints does have a small hint at the problem: it prints 4 different error messages, and 50% of them are actually valid ones. Not the best usability experience, granted… but sometimes "good enough" is better than "best".

**Comment by aadilayub** [comment]
I think I'm running into this issue right now, trying to load an image (tagged `localhost/react-app:latest` by default)

```
[aadil@fedora 4-react-app]$ podman image load -i react-app.tar 
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Error: payload does not match any of the supported image formats:
 * oci: initializing source oci:react-app.tar:: open react-app.tar/index.json: not a directory
 * oci-archive: loading index: open /var/tmp/oci2062792976/index.json: no such file or directory
 * docker-archive: Source image rejected: Running image docker-archive:react-app.tar:localhost/react-app:latest is rejected by policy.
 * dir: open react-app.tar/manifest.json: not a directory
 ```
 
 Is this caused only by colons in filenames, or does it happen with tags too?
