### ISSUE TITLE
podman machine stop does not stop the machine

### ISSUE THREAD

**Issue by chevdor** [containers/podman#18683]
### Issue Description

Stopping the podman machine is confirmed although the machine is not stopped.

### Steps to reproduce the issue

```
$ podman machine stop
Machine "podman-machine-default" stopped successfully
```

So I would then expect `podman-machine-default` to be stopped... but:

```
$ podman machine list
NAME                     VM TYPE     CREATED         LAST UP             CPUS        MEMORY      DISK SIZE
podman-machine-default*  qemu        21 minutes ago  Currently starting  4           33.55GB     107.4GB
```

### Describe the results you received

See above

### Describe the results you expected

Either the stop command fails with hint or it goes through and does what it tells

### podman info output

```yaml
Error: failed to connect: dial tcp [::1]:51773: connect: connection refused
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by chevdor** [comment]
As a side effect, attempting to start the machine hangs forever.

I also tried killing my qemu processes, the result remains the same.

**Comment by chevdor** [comment]
workaround:
```
killall qemu
podman machine rm
podman machine init...
podman machine start
```

**Comment by ashley-cui** [comment]
Do you know the QEMU version you're using?

**Comment by chevdor** [comment]
```
$ /usr/local/bin/qemu-system-x86_64 --version
QEMU emulator version 8.0.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
```

**Comment by rhatdan** [comment]
@vrothberg Is this something  your changes might cleanup?

**Comment by vrothberg** [comment]
Yes, the latest changes should address it.
