### ISSUE TITLE
[systest] subnet is already used on the host or by another config

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#18693]
Occasional flake in system tests, very likely because of a non-16-24 subnet:
```
# podman network create --subnet 172.31.30.0/24 testnet-8KINMhneHJ
Error: subnet 172.31.30.0/24 is already used on the host or by another config
```
Seems like a solved problem, and it is, but not without adding more dependencies. One simple possibility might involve:
```
  python -mipaddress -c '...ipaddress.ip_address("172.16.x.0") in ipaddress.ip_network("EACH-LINE-FROM-IP-ROUTE")
```
...in `helpers.network.bash:random_rfc1918_subnet()`. Filing so I don't forget.

* fedora-38-aarch64 : sys podman fedora-38-aarch64 root host boltdb
  * PR #18681
    * [05-25 10:13](https://api.cirrus-ci.com/v1/artifact/task/4823815151157248/html/sys-podman-fedora-38-aarch64-root-host-boltdb.log.html#t--00434) in [sys] podman run CONTAINERS_CONF_OVERRIDE dns options
* fedora-38-aarch64 : sys remote fedora-38-aarch64 root host sqlite [remote]
  * PR #17831
    * [05-18 22:08](https://api.cirrus-ci.com/v1/artifact/task/4752281095110656/html/sys-remote-fedora-38-aarch64-root-host-sqlite.log.html#t--00426) in [sys] podman network create

**Comment by Luap99** [comment]
That would make sense especially considering gating or local envs were we have no idea about other used network ranges.

> Seems like a solved problem, and it is, but not without adding more dependencies. One simple possibility might involve:

>  python -mipaddress -c '...ipaddress.ip_address("172.16.x.0") in ipaddress.ip_network("EACH-LINE-FROM-IP-ROUTE")

Well technically podman already does this internally as well if you do not specify a subnet on the cli. So you could just run `podman network create <name>`  and then get the subnet with
`podman network inspect --format "{{(index .Subnets 0).Subnet}}" <name>`
