### ISSUE TITLE
Podman rootless on different volume (and config weird behavior)

### ISSUE THREAD

**Issue by auwsom** [containers/podman#18692]
### Issue Description

Your "top of Podman's README.md" link above is broken. PM info is below.

I'm trying to use Podman in rootless mode and getting "Error: chmod /media/user: operation not permitted". I've set the graphroot and rootless_storage_path in /home/user/.config/containers/storage.conf (see below). Here's the weird thing.. when I change the runRoot in this file and check `podman info` nothing happens. But when I then change the graphRoot and check, the runRoot is changed. Even weirder, when I change the graphRoot back, it changes the runRoot back by itself. 

Anyone can explain this? Thx

This might be a bug, but my main issue is overcoming the chmod error (presumably from having the container on a different volume, because running with root works). I'm trying to run in rootless mode, so likely this is a permissions error. The ownership and permissions of the directories match my user though. If I use a directory with root ownership, I get an error, which makes sense. I don't know why PM would need to chmod /media/user which needs to be root ownership.

EDIT: Okay, so switching the graphRoot and rootless path to my home dir, resolves the error. And oddly enough, allowed me to change the runRoot to my user (this still could be consistent with a bug, unless PM checks the volume ownerships and guesses the best runRoot). I'll try with a symlink from my home dir.

EDIT2: symlinking failed with the same error. I tried chmoding the dir with recursive 777, with no success. Here is the stat /media/user/temp/containers output: 
`Access: (2777/drwxrwsrwx)  Uid: ( 1000/    user)   Gid: ( 1000/    user)`

--

    [storage]
    
    # Default Storage Driver, Must be set for proper operation.
    #driver = "overlay"
    driver = "vfs"
    
    # Temporary storage location
    #runroot = "/media/user/temp/containers/run"
    runroot = "/run/user/1000"
    
    # Primary Read/Write location of container storage
    graphroot = "/media/user/temp/containers/storage"
    
    # Storage path for rootless users
    rootless_storage_path = "/media/user/temp/containers/storage"

### podman info output

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 32
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: ub-h
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.0-71-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 5790887936
  memTotal: 75909517312
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 0
  swapTotal: 0
  uptime: 277h 49m 14.33s (Approximately 11.54 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 0
    stopped: 7
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /media/user/temp/containers/storage
  graphStatus: {}
  imageStore:
    number: 1
  runRoot: /media/user/temp/containers/run
  volumePath: /media/user/temp/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Wed Dec 31 16:00:00 1969
  GitCommit: ""
  GoVersion: go1.17.3
  OsArch: linux/amd64
  Version: 3.4.4


```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
podman caches the paths in its db, you need to run `podman system reset` before changing the paths.

**Comment by Luap99** [comment]
The db is stored in the graphroot so when you change that it will not see the old paths anymore and start from scratch basically.

**Comment by auwsom** [comment]
> podman caches the paths in its db, you need to run `podman system reset` before changing the paths.

Thanks for the info on the db being tied to graphroot. 

If I use `podman system reset` it will delete my downloaded containers.

**Comment by auwsom** [comment]
I thought having to destroy everything to reset a conf file seemed ridiculous, and it was. Just rename the file and run `podman info` again.
