### ISSUE TITLE
Debian Testing: Unmet dependency crun=100:0.19.1-1

### ISSUE THREAD

**Issue by skurhse** [containers/podman#18704]
### Issue Description

`sudo apt-get install podman` from the kubic libcontainers stable repository is not working for me on Debian Testing.  I am stuck on 'crun':

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 podman : Depends: crun (>= 100:0.19.1-1) but 1.8.1-1+b1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

`sudo apt-get install crun=100:0.19.1-1` does not resolve (version not found)

### Steps to reproduce the issue

1. Download, dearmor, verify and import repo signing key
2. Add source entry
3. Run sudo apt-get install podman

### Describe the results you received
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 podman : Depends: crun (>= 100:0.19.1-1) but 1.8.1-1+b1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

### Additional environment details
Debian GNU/Linux 12 (bookworm)

**Comment by Luap99** [comment]
@lsm5 PTAL

**Comment by lsm5** [comment]
> ### Issue Description
> `sudo apt-get install podman` from the kubic libcontainers stable repository is not working for me on Debian Testing. I am stuck on 'crun':

Just checking if you meant `unstable`? The `stable` repo is no longer being updated.

**Comment by skurhse** [comment]
> > ### Issue Description
> > `sudo apt-get install podman` from the kubic libcontainers stable repository is not working for me on Debian Testing. I am stuck on 'crun':
> 
> Just checking if you meant `unstable`? The `stable` repo is no longer being updated.

I was using 'stable'; I updated to `unstable` and the install is working now. thank you very much!
