### ISSUE TITLE
Terminal keyboard "^p" input not passed directly to interactive processes

### ISSUE THREAD

**Issue by philregier** [containers/podman#18708]
### Issue Description

(The title may not be perfectly precise; I've had some trouble determining exactly where the keystrokes get held)

On several versions, including 3.4.4 and 3.5.0, on several hosts (tested by myself on SUSE Leap, Enterprise, and Tumbleweed and by hearsay on Fedora) and several guests (I've tried multiple SUSE releases, as well as Fedora from its own registry and Ubuntu from docker.io) I've found that multiple shells that use the Emacs-style c-p key for previous history line only respond to this key in pairs.

### Steps to reproduce the issue

1. Start an interactive terminal session in a base container image:
```
podman run -it registry.opensuse.org/opensuse/leap:latest
```

2. Enter any two or more distinct inputs:
```
8f84e4b56b90:/ # a
bash: a: command not found
8f84e4b56b90:/ # b
bash: b: command not found
8f84e4b56b90:/ # c
bash: c: command not found
```

3. Enter `^p` for previous line (no effect)
4. Enter `^p` again to get the second-to-last history line, or any other character to see the last history line with the second character appended

### Describe the results you received

`^p` seems to be unique in only being passed to the container in pairs.  `^n` and other ASCII characters seem to be passed as they are received.

### Describe the results you expected

`^p` should be passed to the container immediately, where processes would process it as they do outside a container.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-1.2.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: unknown'
  cpuUtilization:
    idlePercent: 99.46
    systemPercent: 0.15
    userPercent: 0.38
  cpus: 16
  databaseBackend: boltdb
  distribution:
    distribution: '"opensuse-tumbleweed"'
    version: "20230401"
  eventLogger: journald
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

**Comment by Luap99** [comment]
This is the expected behavior, the default detach key combination is ^p^q so we need to buffer the ^p until we see a different char, see https://docs.podman.io/en/latest/markdown/podman-run.1.html#detach-keys-sequence. You can also change the default globally in containers.conf.

**Comment by philregier** [comment]
I'll note that my documentation doesn't indicate how to disable `detach_keys` altogether, and Podman's behavior differs in an unfortunate way from applications that use well-defined "escape prefix" keys; for example, in SSH it's relatively well known that to get a literal `~` you type `~~`.  That remedy is not available here, and whatever prefix is specified in `detach_keys` still gets passed only as one of a pair of characters.
I'll probably just set my detach to something like `"~,ctrl-q"` in the hopes of reminding myself to expect Podman's behavior to be surprising, but I would hope that some day future iterations of this functionality might include "traditional" behavior as an option.

**Comment by Luap99** [comment]
Note that this follows the same behavior as docker. 
I think supporting something like `--detach-keys none` sounds reasonable and not complicated to implement. Feel free to file a feature request for that.

**Comment by philregier** [comment]
Sorry, in `man podman-run` there is an additional piece of information not included in `man containers.conf`, at least on my system:

```
Specifying "" will disable this feature.
```

Without the information you've provided here, though, I would not have realized this was what I was looking for.  Thanks for bearing with me!
