### ISSUE TITLE
[Quadlet] Escape @ in container names by default

### ISSUE THREAD

**Issue by matt-allan** [containers/podman#18705]
## Context

I am using the Quadlet `.container` files to generate [template units](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Service%20Templates).

The filename is `memsol-index@.container` and the relevant part of the file looks like this:

```
[Unit]
Description=Memsol index container wrk.%I
After=network.target

[Container]
Image=example-internal-registry.com/orca/memsol:latest
ContainerName=systemd-memsol-index-%I
Exec=bin/memsol --index --consumer %i
```

I start the units like this:

```
systemctl --user start memsol-index@1.service
systemctl --user start memsol-index@2.service
```

I'm using the template units because I need to run N services where the only difference is the `--consumer` option's value.

## The Problem

It took me a while to figure this out. If I don't specify `ContainerName` manually I get an error because the `@` symbol is not allowed in a `ContainerName`, it is required to use a template unit, and the Quadlet generator does not escape or remove the `@` when generating the `ContainerName`. Specifying the `ContainerName` manually to omit the `@` and include the `%I` placeholder instead avoids the issue and gives me the container names `systemd-memsol-index-1`, `systemd-memsol-index-2`, etc.

### Suggest potential solution

Ideally Quadlet would generate a valid and unique name for instantiated template units.

If the unit file is a template unit, instead of [using `systemd-%N`](https://github.com/containers/podman/blob/1210efc44d2e5ec4e6444dd2137d1342f6fdbcd9/pkg/systemd/quadlet/quadlet.go#LL312C1-L312C31) as the default `ContainerName` it would use `systemd-%p-%I`.

For example, with the file `http-server@.container`, running `systemctl --user daemon-reload && systemctl --user start http-server@8080.service` would start a container named `http-server-8080`.

I don't believe this would count as a breaking change since the generated default `ContainerName` is not usable as-is?

### Have you considered any alternatives?

- The manual workaround I am using now works but it's a bit repetitive and the error message is confusing
- If container names could contain `@` this wouldn't be an issue but that may have other ramifications
- The `@` could be replaced with a different symbol than a `-`
- The Quadlet docs could include an example of using template units to document this workaround

**Comment by rhatdan** [comment]
Interested in opening a PR to add this functionality?

@alexlarsson @vrothberg @ygalblum PTAL

**Comment by ygalblum** [comment]
Currently, Quadlet does not support templating. There is an open discussion on this issue #17744.
@alexlarsson did you get any response from the Systemd team?

**Comment by rhatdan** [comment]
Still waiting for @alexlarsson response.

**Comment by alexlarsson** [comment]
@ygalblum No response, but this is the upstream issue:
https://github.com/systemd/systemd/issues/28006

I think changing the default to systemd-%p-%I if there is an `@`in the name makes a lot of sense. However, I agree with @ygalblum that there are more issues here related to the automatic enabling of such files.

Maybe we can decouple these for now by just saying we don't support the Install section on templates for now? That way we get part of this going, and can address easy auto-starting of templates later.

**Comment by rhatdan** [comment]
No update on this.

**Comment by Luap99** [comment]
I assume this can be closed after https://github.com/containers/podman/pull/21068
