### ISSUE TITLE
Go Image build failing with segmentation fault

### ISSUE THREAD

**Issue by anishasthana** [containers/podman#18719]
### Bug description

I've run into an image build failure using podman desktop on an M1 mac with the go build step getting segmentation faults. The same image build is succeeding when I run in a fedora environment. (Logs pasted below). The only difference in the command being called is that in Mac I'm calling `podman build -t  <tag> . --arch=amd64`, whereas in fedora I'm just calling `podman build -t <tag> .`

Mac details
```
➜  go version
go version go1.17 darwin/arm64
➜  uname
Darwin
➜  uname -r
22.4.0

➜ podman version
Client:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.20.3
Git Commit:   75e3c12579d391b81d871fd1cded6cf0d043550a
Built:        Fri Apr 14 13:28:20 2023
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.20.2
Built:        Fri Apr 14 15:41:12 2023
OS/Arch:      linux/arm64
```

Fedora details
```
$go version
go version go1.17 linux/amd64
$ uname -r
5.18.13.200.fc36.x86_64
$ podman version
podmanClient:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.18.7
Built:        Fri Nov 11 10:24:13 2022
OS/Arch:      linux/amd64
```

### Operating system

Apple Sillicon

### Version

1.0.x

### Steps to reproduce

I am building this dockerfile: https://github.com/anishasthana/kuberay/blob/update_makefile/ray-operator/Dockerfile

The command is generally run through a makefile, but the makefile is just calling podman under the hood. The only difference in the command being called is that in Mac I'm calling `podman build -t  <tag> . --arch=amd64`, whereas in fedora I'm just calling `podman build -t <tag> .`

### Relevant log output

```shell
[1/2] STEP 9/9: RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o manager main.go
go build k8s.io/api/rbac/v1: /usr/local/go/pkg/tool/linux_amd64/compile: signal: segmentation fault (core dumped)
go build k8s.io/client-go/tools/record: /usr/local/go/pkg/tool/linux_amd64/compile: signal: segmentation fault (core dumped)
Error: building at STEP "RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -a -o manager main.go": while running runtime: exit status 1

make: *** [docker-image] Error 1
```
```


### Additional context

_No response_

**Comment by benoitf** [comment]
Transferring the issue to podman repository as Podman Desktop is not involved here.

I think it might link to a qemu issue ( cross compilation and go have segmentation issues)

**Comment by vrothberg** [comment]
@flouthoc PTAL

**Comment by flouthoc** [comment]
Hi @anishasthana , 

You machine VM is runnin on `arm64` afaics, and you want to build an image for `amd64` this will need emulation so you have to make sure if `podman machine` VM contains `qemu-user-static` if not then you must install it manually on the VM.

or you can do 

```
podman machine ssh
sudo -i
rpm-ostree install qemu-user-static
systemctl reboot
```

Irrespective of this I think there is a plan to add this by default in the machine.

Also I think it should work if you don't add `--arch=amd64` but now it will build image for `arm64`.

I am closing this issue since this is a `qemu-user-static` missing case, but please feel free to re-open if you think something is unresolved.
