### ISSUE TITLE
Podman machine is running but error while pulling the images

### ISSUE THREAD

**Issue by tppalani** [containers/podman#18718]
### Issue Description

Describe your issue

my podman machine is active and running. But when I'm doing pull the images using podman command i'm getting like

```
$ podman pull alpine
Error: failed to connect: dial tcp 127.0.0.1:60219: connectex: No connection could be made because the target machine actively refused it.
```

wsl -l -v

```
$ wsl -l -v
  NAME                      STATE           VERSION
* wsl-vpnkit                Running         2
 podman-machine-default    Running         2

```

### Steps to reproduce the issue

Steps to reproduce the issue

using command prompt and podman desktop, i have tried to pull image but its not working.

### Describe the results you received

$ podman pull alpine
Error: failed to connect: dial tcp 127.0.0.1:60219: connectex: No connection could be made because the target machine actively refused it.

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
Did you try to stop the machine then start it again?

**Comment by si458** [comment]
im having a similar issue but just trying to list containers?
```
PS C:\Users\sas_2> podman ps
Error: failed to connect: dial tcp 127.0.0.1:61902: connectex: No connection could be made because the target machine actively refused it.
PS C:\Users\sas_2>
```

**Comment by Luap99** [comment]
Closing as I never heard back.
