### ISSUE TITLE
[Quadlet]: Add support for --sysctl

### ISSUE THREAD

**Issue by LauKr** [containers/podman#18727]
### Feature request description

As far as I saw there is no support for the [--sysctl flag](https://docs.podman.io/en/latest/markdown/podman-run.1.html#sysctl-name-value) up to now for Quadlet.
When using --sysctl for a container, this, at least to my understanding, makes it impossible to simultaneously use Quadlet.

### Suggest potential solution

I think this can easily be done similar to other options, like e.g. AddCapability in [quadlet.go](https://github.com/containers/podman/blob/main/pkg/systemd/quadlet/quadlet.go), something like:

```go	
	addSysctl := container.LookupAllStrv(ContainerGroup, KeyAddSysctl)
	for _, sysctl := range addSysctl {
		podman.addf("--sysctl=%s", strings.ToLower(sysctl))
	}
```

As this is neither tested yet nor I'm fluent in Go, please take with a grain of salt. Also, I'm not sure if the input should be filtered for allowed entries based on namespaces, or if Podman throwing the corresponding error is enough.

### Have you considered any alternatives?

One could always use the `podman generate` command to generate a separate unit file based on the used container, but mixing different types of container administration is not ideal.

**Comment by Luap99** [comment]
You can use `PodmanArgs=` to set arbitrary podman args that are not directly exposed in quadlet.
In any case this sounds like a reasonable request to support it directly in quadlet.

**Comment by rhatdan** [comment]
I agree.

**Comment by LauKr** [comment]
I gave the implementation a try.
For me it works, I can use the AddSysctl flag with one or several entries and they will be passed to the container as expected.
