### ISSUE TITLE
Missing Mac Installers for v4.5.1

### ISSUE THREAD

**Issue by kcak11** [containers/podman#18726]
### Issue Description

Missing PODMAN Installer (.pkg files) for MacOS for v4.5.1
https://github.com/containers/podman/releases/tag/v4.5.1

### Steps to reproduce the issue

Missing PODMAN Installer (.pkg files) for MacOS for v4.5.1
https://github.com/containers/podman/releases/tag/v4.5.1

### Describe the results you received

N/aA

### Describe the results you expected

N/A

### podman info output

```yaml
N/A
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Missing PODMAN Installer (.pkg files) for MacOS for v4.5.1
https://github.com/containers/podman/releases/tag/v4.5.1

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
@lsm5 PTAL

**Comment by lsm5** [comment]
@kcak11 thank you for reporting the issue. The engineers with access to creating the mac installers are away on vacation so this will take a few days to resolve. We'll update the release artifacts asap. I'll update this issue once those are available.

**Comment by kcak11** [comment]
> @kcak11 thank you for reporting the issue. The engineers with access to creating the mac installers are away on vacation so this will take a few days to resolve. We'll update the release artifacts asap. I'll update this issue once those are available.

Thanks @lsm5

**Comment by benoitf** [comment]
artifacts are there
