### ISSUE TITLE
can podman save / load image including digest / diffid, in order to restore cache.

### ISSUE THREAD

**Issue by umialpha** [containers/podman#18749]
### Feature request description

scenario:
we build business image based on base image. the base image is large, so we want to copy the base image to the edge device with portable storage device. we use "save / load" command. However, because missing of cache info, when pulling business, the base image is pulled again.

when using docker, we mannually copy the '/var/lib/docker/image/overlay2/distribution/diffid-by-digest' and '/var/lib/docker/image/overlay2/distribution/v2metadata-by-diffid' dirs to restore cache info.

What can i do to restore cache info when using podman?

**Comment by rhatdan** [comment]
@flouthoc @nalind PTAL

**Comment by flouthoc** [comment]
@umialpha I think loading a base image should prevent from build pulling it again, the problem which could be happening is that loaded image is not tagged with the correct name. It should work even if `blob-info-cache` is not present, please try the steps below.

Does it work if you
* Load the image and then tag the sha with exact name of base image ?

For example it works for me if i do 
```console
[fl@fedora bin]$ ./podman load -q < alpine.tar 
Loaded image: sha256:5e2b554c1c45d22c9d1aa836828828e320a26011b76c08631ac896cbc3625e3e
[fl@fedora bin]$ ./podman tag 5e2b554c1c45d22c9d1aa836828828e320a26011b76c08631ac896cbc3625e3e docker.io/library/alpine:latest
[fl@fedora bin]$ ./podman images -a
REPOSITORY                TAG         IMAGE ID      CREATED      SIZE
docker.io/library/alpine  latest      5e2b554c1c45  3 weeks ago  7.62 MB
[fl@fedora bin]$ 
```

**Comment by flouthoc** [comment]
@umialpha Although I think a feature request could be that `save` and `load` automatically carries and tags the image as well, but first I'd like you to try this and verify if it works for you.

**Comment by umialpha** [comment]
@flouthoc when i use "podman load -i baseimage.tar", it is automatically tag to the "baseimage:0.1". however, when i do "poman pull baseimage:0.1", all the layers are pulled again.

**Comment by umialpha** [comment]
@flouthoc , i tried the following steps:
1. save alpine **on one machine**, ```podman save -o alpine.3.16 docker.io/library/alpine:3.16 ```
2. copied it to **another machine.**
3. load alpine, ```podman load -i alpine.tar```. the "alpine.3.16 docker.io/library/alpine:3.16" tag is automatically tagged.
4. pull the "alpine.3.16 docker.io/library/alpine:3.16". **the image is pulled again.**

I guess i have to copy cache info. Docker, i.e. mody,  uses `digestid - diffid - chainid` to check if the layed is cached. I am not familar with podman. Can you tell me how to copy podman cache mannually, in order to restore cache info on the other machine.

**Comment by vrothberg** [comment]
Please have a look at the following comment on the issue trying to preserve digests when loading/saving: https://github.com/containers/podman/issues/18809#issuecomment-1581558053

**Comment by vrothberg** [comment]
> Can you tell me how to copy podman cache mannually, in order to restore cache info on the other machine.

This is not something we can support since there is no stability guarantee on _internal_ caches.  I think that same issue applies to copying `/var/lib/docker/` since Docker may change this _internal_ layout in the future.

Using `skopeo` as mentioned in https://github.com/containers/podman/issues/18809#issuecomment-1581558053 is the right approach.
