### ISSUE TITLE
Error: writing blob: uploading layer chunked: StatusCode: 403, <!DOCTYPE html>

### ISSUE THREAD

**Issue by erickellerek1** [containers/podman#18757]
### Issue Description

With this container file:

```
cat << EOF > Containerfile
FROM docker.io/bash
RUN ls /var/log
EOF
```

after building, 

```
podman build --format oci -t registry.code.test.com/eric/registry/ui:error2 .
STEP 1/2: FROM docker.io/bash
STEP 2/2: RUN ls /var/log
--> Using cache 062bf1c37cd4caf78a6be72dce25d3fa51e8d8dceed877cd030d363c28f3bd79
COMMIT registry.code.test.com/eric/registry/ui:error2
--> 062bf1c37cd
Successfully tagged registry.code.test.com/eric/registry/ui:error2
Successfully tagged registry.code.test.com/eric/registry/ui:error
062bf1c37cd4caf78a6be72dce25d3fa51e8d8dceed877cd030d363c28f3bd79
```

Pushing fails with:
```
podman push --format oci registry.code.test.com/eric/registry/ui:error2
Getting image source signatures
Copying blob bb01bd7e32b5 skipped: already exists  
Copying blob 2ae559c5a66b skipped: already exists  
Copying blob 3d5f212eb605 skipped: already exists  
Copying blob 74d9b3a7dbd0 [--------------------------------------] 0.0b / 0.0b
Copying config 062bf1c37c done  
Error: writing blob: uploading layer chunked: StatusCode: 403, <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-...
```

Changing the initial Containerfile, surrounding /var/log with quotes,
```
cat << EOF > Containerfile
FROM docker.io/bash
RUN ls "/var/log"
EOF
```

rebuild and the push Just works! 

### Steps to reproduce the issue

Steps to reproduce the issue
1. create above mentioned Containerfile
2. build
3. push

### Describe the results you received

The cryptic error:
```
Error: writing blob: uploading layer chunked: StatusCode: 403, <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-...
```

### Describe the results you expected

push successfully

### podman info output

```yaml
OS: ubuntu 22.04 LTS latest patch level
Podman version: 3.4.4
target registry on gitlab.com
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

I also tried out the --format command enforcing the oci format did not work.
using docker instead of podman with the same initial containerfile does not cause any issue when pushing to the registry.
Anything pointing in the right direction to debug this would be helpful.

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
I don't see why changing the Containerfile like that should help here? Did you try to rebuild the original Containerfile with --no-cache? Maybe the image is corrupted somehow.

Also please test with the latest podman 4.5.1, v3.4.4 is super old and not something we can support upstream.

**Comment by erickellerek1** [comment]
So did use the same files on a Fedora 37 with podman version: 4.5.0 And get exactly the same issue.
```
Error: writing blob: uploading layer chunked: StatusCode: 403, <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-...
```

**Comment by vrothberg** [comment]
Do you have access to the registry logs?  This may help determine what's going on.  I am under the impression of this being a registry issue rather than a Podman issue.

Cc: @mtrmac

**Comment by mtrmac** [comment]
@erickellerek1 already says that this was tracked down to a Cloudflare “Web Application Firewall”, i.e. a middlebox running heuristics.

My current guess is that the “firewall” might be filtering on `User-Agent` or something like that, to let Docker through.

---

I can’t see anything unusual from a quick code inspection: `json.Marshal` can, of course, represent string values that contain a `"`, and both Buildah and Docker seem to use the same standard-library implementation.

---

Just to be sure, can you try pushing the failing to a different registry not behind that firewall, please? (Maybe a `registry:2` container running locally.) And if that succeeds, capture `skopeo inspect --raw --config docker://…` , to double-check that the config itself is not invalid.

I see
```json
"created_by": "/bin/sh -c ls \"/var/log\""
```
which is, I think, fine.

I could see how a heuristic firewall looking for nested quoting could find that suspicious, but it must be the responsibility of the firewall operator to then tune that heuristic down to let legitimate content through.

**Comment by mtrmac** [comment]
Closing; @erickellerek1 please reopen when more information becomes available.
