### ISSUE TITLE
restart: failed to allocate for range 0: 10.88.109.255 has been allocated to XXX, duplicate allocation is not allowed

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#18753]
```
  [It] podman start container sets HOME to home of execUser
...
           # podman-remote [options] create --userns keep-id --user bin:bin quay.io/libpod/alpine:latest ls
           b56f8c668fc53da24557b1af33319fe027ca59860d30fe1b9ecc7fe2fc562674
           # podman-remote [options] start b56f8c668fc53da24557b1af33319fe027ca59860d30fe1b9ecc7fe2fc562674
           b56f8c668fc53da24557b1af33319fe027ca59860d30fe1b9ecc7fe2fc562674
           # podman-remote [options] inspect b56f8c668fc53da24557b1af33319fe027ca59860d30fe1b9ecc7fe2fc562674 --format {{.Config.Env}}
           [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin TERM=xterm container=podman HOME=/bin HOSTNAME=b56f8c668fc5]
           # podman-remote [options] restart b56f8c668fc53da24557b1af33319fe027ca59860d30fe1b9ecc7fe2fc562674
           time="2023-05-26T21:38:19-05:00" level=warning msg="Failed to load cached network config: network podman not found in CNI cache, falling back to loading network podman from disk"
           Error: plugin type="bridge" failed (add): cni plugin bridge failed: failed to allocate for range 0: 10.88.109.255 has been allocated to b56f8c668fc53da24557b1af33319fe027ca59860d30fe1b9ecc7fe2fc562674, duplicate allocation is not allowed
```
Seen in [f37 root remote](https://api.cirrus-ci.com/v1/artifact/task/6612816770105344/html/int-remote-fedora-37-root-host-sqlite.log.html#t--podman-start-container-sets-HOME-to-home-of-execUser--1)

**Comment by Luap99** [comment]
The warning can be ignored, the correct error is `failed to allocate for range 0: 10.88.109.255 has been allocated to XXX, duplicate allocation is not allowed`. The issue sounds like the network teardown was not done for the stop and thus start failed.

**Comment by edsantiago** [comment]
Removed `remote` from tags and title. This is no longer a remote-only bug.

* fedora-37 : int podman fedora-37 root container sqlite
    * [06-06 19:13](https://api.cirrus-ci.com/v1/artifact/task/4535622308724736/html/int-podman-fedora-37-root-container-sqlite.log.html#t--podman-start-container-does-not-set-HOME-to-home-of-caller--1) in podman start container does not set HOME to home of caller
* fedora-37 : int remote fedora-37 root host sqlite [remote]
    * [05-26 23:00](https://api.cirrus-ci.com/v1/artifact/task/6612816770105344/html/int-remote-fedora-37-root-host-sqlite.log.html#t--podman-start-container-sets-HOME-to-home-of-execUser--1) in podman start container sets HOME to home of execUser
    * [05-18 19:35](https://api.cirrus-ci.com/v1/artifact/task/5279301499617280/html/int-remote-fedora-37-root-host-sqlite.log.html#t--podman-start-container-does-not-set-HOME-to-home-of-caller--1) in podman start container does not set HOME to home of caller

**Comment by Luap99** [comment]
@edsantiago still happening?

**Comment by edsantiago** [comment]
Apparently, yes. Here's one from [October 4](https://api.cirrus-ci.com/v1/task/6193465789251584/logs/main.log) (not a colorized log, because the CI run timed out) and one from [August 29](https://api.cirrus-ci.com/v1/artifact/task/5188386856632320/html/int-remote-fedora-37-root-host-boltdb.log.html#t--Podman-create-with-ip-flag-Podman-create-two-containers-with-the-same-IP--1).

The error is infrequent, and it does not trigger a CI failure because in both places (podman run/create two containers with the same IP) the ginkgo code just does `Expect(ExitWithError)` and a substring check for message but no check for other messages. Since it does not trigger a CI failure, I'm only seeing it in logs where there's another flake.

**Comment by edsantiago** [comment]
However, I do not see the message in any "set HOME" tests as originally reported.

**Comment by Luap99** [comment]
Ok given and is that infrequent and CNI + remote only?? I rather not debug it given we will remove CNI with 5.0.

**Comment by edsantiago** [comment]
I'm OK with that.
