### ISSUE TITLE
Unable to pull container images 

### ISSUE THREAD

**Issue by SureshGota** [containers/podman#18777]
### Issue Description

I recently installed Podman 4.5.1 to try out Podman but I am stuck right at start. I am unable to pull any images,
I get a error as following,

> Trying to pull docker.io/library/ngnix:latest...
> Error: initializing source docker://ngnix:latest: pinging container registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution

I am running podman on windows 10. The same machine has docker which is working fine.

### Steps to reproduce the issue

Steps to reproduce the issue
1.podman machine init
2.podman machine start
3.podman pull ngnix

### Describe the results you received

> Trying to pull docker.io/library/ngnix:latest...
> Error: initializing source docker://ngnix:latest: pinging container registry registry-1.docker.io: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution

The steps given here https://github.com/containers/podman/discussions/16693 don't work.Even after updating nameserver it fails to pull but this time its a **lookup registry-1.docker.io: i/o timeout** instead of **temporary failure in name resolution**

### Describe the results you expected

Expected the container image be pulled successfully.

### podman info output

```yaml
podman:4.3.1
Host MS Windows 10
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

**Comment by rhatdan** [comment]
@n1hility PTAL

**Comment by n1hility** [comment]
@SureshGota This suggests a WSL networking issue. Are you running a VPN or firewall connection client?

**Comment by SureshGota** [comment]
I am not running a VPN and I tried running after disabling firewall, still the same issue. I think the issue is with the Fedora WSL that podman creates and uses.
I isolated this by installing a new Oracle linux distro and installed podman inside this linux env and was able to pull and run images. 
Also a side question is there a way I can use this oracle linux distro to work with podman that I have installed on windows?

**Comment by n1hility** [comment]
@SureshGota All WSL distros share the same Linux kernel (Microsoft provides), networking, and DNS, so if one distro is working the other should be as well. Can you try the following `wsl -d podman-machine-default curl google.com` and then repeat the command changing podman-machine-default for the Oracle linux distro you mention. Let me know if you get results on those.

**Comment by SureshGota** [comment]
@n1hility I think I figured out the issue. The WSL distros have the nameserver wrong so we would need to edit it. After editing the distro has external network access established, I validated by doing a curl from within the linux distro. 
Next I did `wsl -d podman-machine-default curl google.com` on another CLI even when the earlier CLI was open the changes of the nameserver was automatically overwritten automatically.

I could resolve it by installing chattr using the command `dnf install e2fsprogs` for fedora and making the `/etc/resolv.conf` immutable after editing the nameserver by using the command `sudo chattr +i /etc/resolv.conf`.

**Comment by n1hility** [comment]
@SureshGota so normally the way DNS is supposed to operate is that WSL sets up local name serving pointing to the host on the WSL network. If its not that indicates either 1) You have a VPN and the VPN needs special configuration - if supported 2) WSL is not operating correctly - in which case I would recommend upgrading WSL to the latest (or close to latest). You can check the version with `wsl --version` . If that command just give syou help text then you need to run Windows update first to pull down the new WSL, and from there you can do a wsl --update. 3) You have some special firewall software that is blocking dns traffic 

The workaround you meniton will work. Although another way is you can edit /etc/wsl.conf, and set generateResolvConf=false under '[network]'

**Comment by SureshGota** [comment]
@n1hility Yes, the initial step I followed was to set  `generateResolvConf=false` but for some reason this config is never considered and the name server was always over written.

WSL was setting up local name serving pointing to the host IP so that seems to work as expected. Btw the 'wsl --version' gives me help text so I guess I am not running the updated version.

**Comment by n1hility** [comment]
Going to close this one since it looks to be a WSL issue (potentially env-specific), likely related to an older version, and not something specifically in podman. Feel free to reopen if still seen occuring on a recent release.
