### ISSUE TITLE
Quadlet for adhoc units

### ISSUE THREAD

**Issue by antdking** [containers/podman#18778]
### Feature request description

2 main usecases I'm looking to solve:

- basic validation of unit files before they're deployed to a server
- generate unit files ahead of time for manual modification

### Suggest potential solution

a super quick implementation would be to document `QUADLET_UNIT_DIRS`.

A more ideal solution is to expose something like `podman generate quadlet ./path/to/dir`, as `quadlet` doesn't have a fixed location or is available on PATH.

### Have you considered any alternatives?

Currently using this as a workaround:

```sh
QUADLET_UNIT_DIRS=path/to/files /usr/lib/podman/quadlet -dryrun -user
```

---

why not `podman systemd generate`:
the `.container` files provide subjectively nicer interface in the context of provisioning a server, and the generated output requires less manual modification

**Comment by antdking** [comment]
It looks like the exit code doesn't get set if there's a conversion failure, too (ie, using an unsupported key).

```sh
$ /usr/libexec/podman/quadlet -v -user -dryrun
...
quadlet-generator[27250]: Error converting 'ns-server.container', ignoring: unsupported key 'XYZ' in group 'Container' in /home/nstack/.config/containers/systemd/ns-server.container
...

$ echo $?
0
```

Could this result in the previous version of the service being deleted (behaviour I'm seeing at the moment, and why being able to run adhoc dryruns is important to me)?

**Comment by vrothberg** [comment]
> It's not a need anymore [...]

That is good news, thanks!

**Comment by computator** [comment]
I'm not sure this should be closed as it only addresses a few of the concerns in this ticket. It doesn't address having a good way to manually run quadlet etc.

**Comment by vrothberg** [comment]
> It doesn't address having a good way to manually run quadlet etc.

Manually running Quadlet is documented: https://github.com/containers/podman/blob/main/docs/source/markdown/podman-systemd.unit.5.md#debugging-unit-files

Note that it's not supported to manually edit the generated files.
