### ISSUE TITLE
`rootless_storage_path` migration issue

### ISSUE THREAD

**Issue by Timost** [containers/podman#18780]
### Issue Description

Hi,

Thank you for podman ❤️.

I'm trying to migrate some rootless containers' storage to a new location using the `rootless_storage_path` field in `storage.conf`.

I have changed `/etc/containers/storage.conf` to set `rootless_storage_path` to the new location but I can't find a repeatable way for podman (rootless) to take the change into account (at least be visible in `podman info`)
As long as `podman info` isn't showing the new storage path, all operations are done within the "old" path.

After several (variable for each test I did) `podman system reset/host reboot` the change ends up being reflected in `podman info`.
It seems the storage path is cached somewhere, but I'm not sure how to reset it properly.

My `storage.conf` looks like that:
```ini
# This file is the configuration file for all tools
# that use the containers/storage library. The storage.conf file
# overrides all other storage.conf files. Container engines using the
# container/storage library do not inherit fields from other storage.conf
# files.
#
#  Note: The storage.conf file overrides other storage.conf files based on this precedence:
#      /usr/containers/storage.conf
#      /etc/containers/storage.conf
#      $HOME/.config/containers/storage.conf
#      $XDG_CONFIG_HOME/containers/storage.conf (If XDG_CONFIG_HOME is set)
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver, Must be set for proper operation.
driver = "overlay"

# Temporary storage location
runroot = "/run/containers/storage"

# Primary Read/Write location of container storage
# When changing the graphroot location on an SELINUX system, you must
# ensure  the labeling matches the default locations labels with the
# following commands:
# semanage fcontext -a -e /var/lib/containers/storage /NEWSTORAGEPATH
# restorecon -R -v /NEWSTORAGEPATH
graphroot = "/var/lib/containers/storage"

# Storage path for rootless users
rootless_storage_path = "/data/podman_storage/$USER/storage"
```

Moreover, since `podman system reset` is destructive it feels like playing russian roulette with "precious data".

### Steps to reproduce the issue

Steps to reproduce the issue
1. In podman rootless, create a container with a volume
2. Check that the volume is indeed created in `$HOME/.local/share/storage/volumes`
3. Check with `podman info` that the storage path is in the home of the user
4. Edit/create `storage.conf` in `/etc/containers/storage.conf`
5.  `podman info` still displays the old path for the storage location `store.graphRoot` and `store.volumePath`
6.  try log out/log in of the user, `podman system reset` etc. at some point `podman info` will display the right values after which all new container will use the new storage location.

### Describe the results you received

podman rootless doesn't take into account the `rootless_storage_path`  change immediately.

### Describe the results you expected

podman rootless takes the setting change into account:
- `podman info` displays the correct path
- All new podman operations use the new path

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon_2:2.1.7-0ubuntu22.04+obs15.38_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 98.33
    systemPercent: 0.67
    userPercent: 0.99
  cpus: 3
  databaseBackend: boltdb
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: sec-dev-vm-test-boot-1
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1301
      size: 1
    - container_id: 1
      host_id: 296608
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1301
      size: 1
    - container_id: 1
      host_id: 296608
      size: 65536
  kernel: 5.15.0-73-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 605126656
  memTotal: 3632984064
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun_101:1.8.4-0ubuntu22.04+obs55.14_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.4
      commit: 5a8fa99a5e41facba2eda4af12fa26313918805b
      rundir: /run/user/1301/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1301/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.2.0-0ubuntu22.04+obs10.76_amd64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 2h 3m 49.00s (Approximately 0.08 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/user1/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /data/disk1/podman_storage/user1/storage
  graphRootAllocated: 9967763456
  graphRootUsed: 103596032
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1301/containers
  transientStore: false
  volumePath: /data/disk1/podman_storage/user1/storage/volumes
version:
  APIVersion: 4.5.1
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.18.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Ubuntu 22.04
podman from unstable kubic repositories

### Additional information

My final goal is to find a clean migration path for podman's storage, e.g: being able to move an existing podman storage to a new location.

**Comment by Luap99** [comment]
It is expected that you have to run podman system reset before changing these fields. All storage paths are stored in the db to prevent any modification after the first run. Changing them without resetting would lead to al lot of weird and cryptic errors later on so we make sure they cannot be changed without a reset.

**Comment by Timost** [comment]
Thank you for your answer ! 🙏

If I understand correctly, I would need to:
1. Stop all running containers
2. `podman system reset`
3. Change `storage.conf`
4. Restart all containers ?

Since `podman system reset` needs to be run **before** changing the setting *and* `podman system reset` wipes the existing storage, is there any way I could migrate existing storage ? I really care about existing volumes

**Comment by Timost** [comment]
Just checked [the podman reset doc again](https://docs.podman.io/en/latest/markdown/podman-system-reset.1.html#description),
Sorry I missed the: `If the administrator modified the configuration files first, podman system reset might not be able to clean up the previous storage.` 🙏

**Comment by Luap99** [comment]
Well you could just copy the volume directory somewhere else and then restore it to the new location, however you would still need to run `podman volume create` afterwards to make the volumes appear in the podman db.

Maybe the easier way is to `podman volume export` and then `podman volume import` afterwards.

**Comment by Timost** [comment]
Alright, thank you for the pointers.

I'll try a few things and I'll you know how it went.

Thank you again for your help !🙏🙏

**Comment by Timost** [comment]
Thank you again for your answers, I think this issue can be closed.
