### ISSUE TITLE
Struggling to get "initialise and start" to work in Podman Desktop

### ISSUE THREAD

**Issue by richardissimo** [containers/podman#18781]
I'm just installing Podman for the first time today, and struggling to get it going. I'm hitting an issue that won't resolve itself by retrying, and I've been unable to find a solution by searching, and it's not mentioned in the list of running issues.

I'm using a Windows 10 Enterprise 64-bit (Build 19042) machine.

To install Podman desktop, I did `winget install -e --id RedHat.Podman-Desktop`

I needed to enable VirtualMachinePlatform from an Admin PowerShell, and then restarted.

Then install Windows Subsystem for Linux from Admin Powershell with `wsl --install` and then restarted.

Ubuntu comes up after reboot, and requires entering your admin-level user and password, so did that.
Then go to Podman Desktop, and press the button to install Podman.
I unticked "install WSL if not found" (given that I've just installed it).
It said before the install that it would need a restart, so afterwards I restarted.

In Podman Desktop, pressed "initialise and start". Within the application, a window appeared, just saying:
`Error: Error: could not create ssh keys: exit status 0xffffffff`

When I tried again, it gave a different error
`Error: Error: the WSL import of guest OS failed: exit status 0xffffffff`

Some googling indicated that I should try restarting a particular service, it was already stopped, but I started it with an Admin command `net start LxssManager`.

I also found something saying to try `podman machine init`, which showed this:
```
Extracting compressed file
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
Import in progress, this may take a few minutes.
A distribution with the supplied name already exists.
Error code: Wsl/Service/0x800700b7
Error: the WSL import of guest OS failed: exit status 0xffffffff
```

Something else indicated that I should do `wsl -l -v`, and which reveals:
```
  NAME                      STATE           VERSION
* Ubuntu                    Stopped         2
  podman-machine-default    Stopped         2
```
So I'm guessing the second one there is the one it's trying to put in place... and I'm not sure why it's trying, given that it looks like it's already there. Perhaps because it's stopped; but I have no idea why it's stopped, or how to start it.

Any help on how to resolve this would be most welcome. Thankyou.

**Comment by anudeepreddy** [comment]
Try init with the machine name like `podman machine init <machine-name>`. where machine-name will the the name of wsl vm.

**Comment by richardissimo** [comment]
Thanks. I'm assuming you meant to try `podman machine init podman-machine-default` (because I really don't know what I'm doing - I just need podman to work). If I try that, it does similar to what's reported above:
```
Downloading VM image: fedora-podman-amd64-v37.0.32.tar.xz: done
Extracting compressed file
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
Import in progress, this may take a few minutes.
A distribution with the supplied name already exists.
Error code: Wsl/Service/0x800700b7
Error: the WSL import of guest OS failed: exit status 0xffffffff
```
and it still was not working.

Just in case, I tried `podman machine init ubuntu` and it's done something which looks successful. I won't quote it here because it mentions key-related information, I have no idea whether it's sensitive.

The dashboard isn't showing the "initialise and start" option any more, and it says the "Podman Machine" is "ubuntu". Which I think was the default machine created by the WSL install, so I'm not sure whether I've just accidentally wiped that out for podman to use...?

I'll now go back and try the thing which required Podman, which required WSL, and see whether it works.

**Comment by SureshGota** [comment]
This seems to be same issue that I have reported [18777]( https://github.com/containers/podman/issues/18777)

**Comment by richardissimo** [comment]
It looks like @SureshGota has figured out their issue; however, I think our scenarios are slightly different, because @n1hility asked about a VPN, which wasn't the case for them on #18777; but it is the case for me. My computer in on a company VPN.

Another suggestion on there was to try `wsl -d podman-machine-default curl google.com`, which just gives me
```
Logon failure: the user has not been granted the requested logon type at this computer.
Error code: Wsl/Service/CreateInstance/CreateVm/0x80070569
```
but I noticed that it gave exactly the same response if I did `wsl hello`, so I thought "maybe there's something fundamentally wrong with wsl now". Interestingly `wsl -l -v` was still working, and returned 3 lines instead of the 2 given earlier (the third is called 'podman-ubuntu'). If I do `podman machine start ubuntu` (which worked successfully a few days ago) it is now saying
```
Logon failure: the user has not been granted the requested logon type at this computer.
Error code: Wsl/Service/CreateInstance/CreateVm/0x80070569
Logon failure: the user has not been granted the requested logon type at this computer.
Error code: Wsl/Service/CreateInstance/CreateVm/0x80070569
Error: the WSL bootstrap script failed: exit status 0xffffffff
```
Ah but then, based on [WSL issue 5401](https://github.com/microsoft/WSL/issues/5401), I tried one several of the suggestions, and restarting a service whose name was "Hyper-V Host Compute Service" (the only Hyper-V service which was running) has sorted that, and that command now works, and podman desktop has noticed that the 'ubuntu' podman machine is running.

OK, so going back to trying `wsl -d podman-machine-default curl google.com`, now responds with:
```
curl: (6) Could not resolve host: google.com
```
So I'm guessing that means it can't see the internet. And just as @n1hility predicted, this has the same outcome when I try it with the 'ubuntu' machine which podman is using.

I'm sorry, I have no WSL skills, so I have no idea how to resolve this. I've only installed it so I can try Podman... please can anyone advise? (mine is a company computer, running under various group policies, so I may be limited to what I can do).

**Comment by anudeepreddy** [comment]
@richardissimo , I had a similar situation where when I am connected to a VPN my wsl couldn't access the internet anymore. I am currently using this setup to enable access to the internet. https://github.com/sakai135/wsl-vpnkit

**Comment by n1hility** [comment]
@richardissimo ah, that makes sense. So depending on which VPN software your work is using they may have the ability to allow this to work. For example Cisco AnyConnect has an option that can be set to allow networks from VMs to communicate on the VPN. Although they may intentionally disallow it.

We have a user-mode-networking option that is in the main branch, and will show up in the next podman feature release, and this acts similarly to wsl-vpnkit but is built in. In the meantime the you can run wsl-vpnkit as @anudeepreddy mentions.

**Comment by tonyc76** [comment]
hi @n1hility, thanks for the info above 'We have a user-mode-networking option that is in the main branch, and will show up in the next podman feature release' - any ideas when we can see this go live ? thank you

**Comment by n1hility** [comment]
Marking this as resolved by the user-mode-networking option which is now in 4.6. To use it run the following commands:

```
podman machine stop
# Delete the existing machine, backing up first if desired
podman machine rm
podman machine init --user-mode-networking
```
