### ISSUE TITLE
Fedora COPR repo doesnt exist

### ISSUE THREAD

**Issue by daltschu22** [containers/podman#18808]
### Issue Description

The documentation mentions manually adding the COPR repository for podman 4, yet this doesnt exist.

The link in the documentation is for:
https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman4/

Which leads to a 404

### Steps to reproduce the issue

Steps to reproduce the issue
1. Visit https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman4/

### Describe the results you received

404 error for that repository

### Describe the results you expected

For the repository to exist

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
What docs are you talking about? Please provide a link.
If you talk about the installation instructions then this was removed yesterday: https://github.com/containers/podman.io/pull/154

**Comment by Ricky-Tigg** [comment]
Good observation, containerbot/**podman4** does not exist; probably to be exact, **no longer**, as it certainly used to exist. I had too reported here in this regard, thus in an inappropriate repository. You reported about one hour before the mentionned correction was merged. Then that last operation makes the present report outdated.

**Comment by daltschu22** [comment]
The installation instructions at this link:
https://podman.io/docs/installation

At the time I posted this issue, the instructions mentioned the COPR link, so it seems you are correct that the release #154
has removed this. 

Thanks
