### ISSUE TITLE
Missing schema for type returned by /libpod/info endpoint

### ISSUE THREAD

**Issue by vv9k** [containers/podman#18844]
### Issue Description

In the v4.5.1 swagger schema there is a missing type for `/libpod/info` endpoint or rather it points to a wrong type and the correct one is missing.

Here are relevant fragments of the schema:
```
definitions:
...
    Info:
        description: |-
            Info contains information about the Volume as a whole as provided by
            the CSI storage plugin.
        properties:
            AccessibleTopology:
                description: |-
                    AccessibleTopolgoy is the topology this volume is actually accessible
                    from.
                items:
                    $ref: '#/definitions/Topology'
                type: array
            CapacityBytes:
                description: |-
                    CapacityBytes is the capacity of the volume in bytes. A value of 0
                    indicates that the capacity is unknown.
                format: int64
                type: integer
            VolumeContext:
                additionalProperties:
                    type: string
                description: |-
                    VolumeContext is the context originating from the CSI storage plugin
                    when the Volume is created.
                type: object
            VolumeID:
                description: |-
                    VolumeID is the ID of the Volume as seen by the CSI storage plugin. This
                    is distinct from the Volume's Swarm ID, which is the ID used by all of
                    the Docker Engine to refer to the Volume. If this field is blank, then
                    the Volume has not been successfully created yet.
                type: string
        type: object
        x-go-package: github.com/docker/docker/api/types/volume
...
paths:
...
    /libpod/info:
        get:
            description: Returns information on the system and libpod configuration
            operationId: SystemInfoLibpod
            produces:
                - application/json
            responses:
                "200":
                    $ref: '#/responses/infoResponse'
                "500":
                    $ref: '#/responses/internalError'
            summary: Get info
            tags:
                - system
...
responses:
...
    infoResponse:
        description: Info
        schema:
            $ref: '#/definitions/Info'
...
```

As you can see, the `/libpod/info` endpoint shoud return `#responses/infoResponse` which is a reference to `#/definitions/Info` and the `Info` definition contains `information about the Volume as a whole as provided by the CSI storage plugin.` rather than system info.

### Steps to reproduce the issue

Doesn't apply

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
Podman v4.5.1
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by vrothberg** [comment]
Thanks for reaching out, @vv9k !

**Comment by Luap99** [comment]
I am almost sure this was already fixed in https://github.com/containers/podman/pull/18376

**Comment by vv9k** [comment]
Looks like the same issue. Sorry for duplicate, I didn't find anything when searching on GitHub issues. Will close this as its most likely already solved.
