### ISSUE TITLE
pod create + run --pod: Waiting for container, getting exit code from DB, no such exit code

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#18860]
Weird new flake:
```
[It] podman pod create --sysctl test
...
# podman [options] pod create --share pid --sysctl kernel.msgmax=65535
<PODID>
# podman [options] run --pod <PODID> --rm quay.io/libpod/alpine:latest sysctl kernel.msgmax
time="2023-06-12T12:59:50Z" level=error msg="Waiting for container <CID>: getting exit code of container <CID> from DB: no such exit code (container in state running)"
time="2023-06-12T12:59:50Z" level=error msg="Removing container <CID>: cannot remove container <CID> as it is running - running or paused containers cannot be removed without force: container state improper"
```
Seen in [debian root](https://api.cirrus-ci.com/v1/artifact/task/5341261570244608/html/int-podman-debian-12-root-host-sqlite.log.html#t--Podman-pod-create-podman-pod-create-sysctl-test--1). Even though this looks a lot like many other "container state improper" flakes we've seen in the past, I think this one is different enough to merit a new issue.

**Comment by vrothberg** [comment]
Thanks for filing, I'll take a look.

**Comment by vrothberg** [comment]
I do not see where start-attach would transition the container state.  Have we always been relying on the cleanup process to fire fast enough?

@giuseppe @Luap99 can you take a look to double check?

If so, I am surprised the error doesn't occur more often. And we'd need to add a wait instead of querying the exit code.

https://github.com/containers/podman/blob/38b8c172444dd7e63eec045c73c7780c460763aa/pkg/domain/infra/abi/containers.go#L1169-L1171

**Comment by Luap99** [comment]
`ic.GetContainerExitCode()` already waits for the container to exit?!

I don't see how the state can still be running after that point, maybe something wrong with `c.syncContainer()` where the state is not updated correctly?

**Comment by vrothberg** [comment]
> `ic.GetContainerExitCode()` already waits for the container to exit?!

Ha, I felt to be missing something obvious.

> I don't see how the state can still be running after that point, maybe something wrong with `c.syncContainer()` where the state is not updated correctly?

It may just be a bug in the wait logic; we shouldn't attempt to look up the exit code if the container is still running.

**Comment by vrothberg** [comment]
Hm...looking at the timestamps. The tests starts at 12:59:26 and fails at 12:59:50.

It smells a bit like the 20 seconds "conmon is dead and wait for state transition" timeout.  Since I can only guess, I'll open a PR to help debug.

**Comment by Luap99** [comment]
But how can the container be still running? Attached should not return before the container exits, right?
And our wait logic waits 20 seconds after conmon exists so how can the container not be in exited state by that point. The only way I see this ever failing if our cleanup process just died and did nothing.

**Comment by Luap99** [comment]
20 seconds is more than enough, there is no way that we should assume anything will happen after that in CI.

Reading the code more `syncContainer()` check the conmon exit file and transition the sate to stopped if it sees that file.
Therefore even without cleanup process podman should be able to notice that. It could be conmon never wrote the exit file.

**Comment by vrothberg** [comment]
> 20 seconds is more than enough, there is no way that we should assume anything will happen after that in CI.

I agree, 20 seconds should be largely enough for things to be cleaned up.

> Reading the code more `syncContainer()` check the conmon exit file and transition the sate to stopped if it sees that file. Therefore even without cleanup process podman should be able to notice that. It could be conmon never wrote the exit file.

I opened https://github.com/containers/podman/pull/18869 to indicate in the error whether the time out kicked in or not.  This should give slightly more insight in what's going on.

**Comment by edsantiago** [comment]
There is only one instance of this in my flake logs, the June 12 one. I can't justify keeping this open.
