### ISSUE TITLE
rm -fa + dependencies is still issuing warnings 

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#18865]
I assume it's a flake, since otherwise Matt's PR would never have merged.
```
[It] podman rm -fa with dependencies
...
# podman [options] rm -fa
kill container: No such process
a56742cb3f318e7bebcf568d2fb67c72e2753528be9df535211c451b3a4a4230
5210226ca965cd1b101ea5c4d417957e84463b53f47d4f228545a5d999ffcb39

[FAILED] rm -fa error logged
```
In [rawhide root](https://api.cirrus-ci.com/v1/artifact/task/5234205953622016/html/int-podman-rawhide-root-host-sqlite.log.html#t--Podman-rm-podman-rm--fa-with-dependencies--1)

**Comment by Luap99** [comment]
I cannot find `kill container` in the podman codebase (only looking at error messages)

However I see that in the crun code right below the open pidfd one. So basically we manage to hit the tiny window between pidfd_open() and then the container exited right after that but before it reads the status from /proc/$pid/stat.
https://github.com/containers/crun/blob/7da99fb998a89e5f258dea67b7387f741808e58d/src/libcrun/linux.c#L5333-L5338

So I would argue we need to match this string as well, @mheon WDYT?

**Comment by mheon** [comment]
Now that we've built ourselves a mechanism for catching superfluous errors, we might as well use it. Let's get this error included.
