### ISSUE TITLE
Restore API: missing importPrevious option

### ISSUE THREAD

**Issue by antoniocalagna98** [containers/podman#18886]
### Feature request description

Hi everyone,

Thank you very much for the great work you have been doing.

I noticed that, according to the lastest API documentation, the "import" option is a boolean and (1) there seems to be no way to provide a path, (2) there is no comment about a default location where to put the tar archive.

Moreover, the option to restore from exported pre-checkpoint archive, i.e., "importPrevious", is missing.

(see [Restore API](https://docs.podman.io/en/latest/_static/api.html?#tag/containers/operation/ContainerRestoreLibpod))

Would it be too difficult to investigate and enhance these features? Thanks a lot for your time.

**Comment by rhatdan** [comment]
@mheon PTAL

**Comment by mheon** [comment]
You don't provide a path to a tar file, but rather transfer the contents of the tar file in the request body after setting Import to true.
