### ISSUE TITLE
Support DaemonSet with `podman kube play`

### ISSUE THREAD

**Issue by fwiesel** [containers/podman#18899]
### Feature request description

The current command supports Pods and Deployments in the yaml file, it would be great, if it also supports a `DaemonSet`.

### Suggest potential solution

If I provide a yaml containing a `DaemonSet`, instead of a `Deployment` it should generate the corresponding pod for it.

### Have you considered any alternatives?

Currently, I simply replace the `DaemonSet` in the yaml with `Deployment` and that works.
Only it would improve the interoperability of the podman itself, if it would be done "properly".

### Additional context

The field `.spec.template` of  a `DaemonSet` is a `PodTemplateSpec`. The same as a `Deployment`.

Presumably, there is a large overlap in the functionality, so I hope it would be a rather low hanging fruit.

**Comment by danishprakash** [comment]
>If I provide a yaml containing a DaemonSet, instead of a Deployment it should generate the corresponding pod for it.

Are you suggesting it to be functionally equivalent to Deployments?

**Comment by rhatdan** [comment]
@ygalblum @umohnani8 WDYT?
@fwiesel @danishprakash is this something you are interested in working on?

**Comment by ygalblum** [comment]
@rhatdan Makes sense and from the looks of it, sounds simple to implement (Same path as for `Deployment`)

**Comment by danishprakash** [comment]
Sure, I can take this up. The idea is to simply allow using `DaemonSet`  in the Pod template but then follow through as if the user has created a `Deployment`, is that right?

**Comment by ygalblum** [comment]
Seems so, yes

**Comment by danishprakash** [comment]
Just so that we're on the same page, when you say use the same path as for Deployment, do you really mean
```
case "Deployment", "DaemonSet":
```
which seems a tad bit misleading because we're missing out on handling certain non-overlapping attributes such as numReplicas and potentially others in the future.

I'm going in this direction for now - https://github.com/containers/podman/compare/main...danishprakash:podman:daemonset-support?expand=1
