### ISSUE TITLE
not possible to create macvlan network without default gateway

### ISSUE THREAD

**Issue by pakagi** [containers/podman#18914]
### Issue Description

Using podman 4.3.1, from the new Debian 12.

Trying to create macvlan network using "podman network ..." , without default gateway. Even when --gateway option is not used, the network gets created with some just guessed default gateway addr, which is clearly wrong.

### Steps to reproduce the issue

podman network create -d macvlan -o parent=enp7s0  --subnet 172.22.99.0/24 int

### Describe the results you received

[
     {
          "name": "int",
          "id": "60b8bc923f2e2d43768ecb8497fa04f617eb44ea845b8710fe763ddbd5e53e06",
          "driver": "macvlan",
          "network_interface": "enp7s0",
          "created": "2023-06-16T12:17:52.65670352+02:00",
          "subnets": [
               {
                    "subnet": "172.22.99.0/24",
                    "gateway": "172.22.99.1"
               }
          ],
          "ipv6_enabled": false,
          "internal": false,
          "dns_enabled": true,
          "ipam_options": {
               "driver": "host-local"
          }
     }
]

Note the 172.22.99.1 used as gateway, which is IP addr I didn't provide at all.

### Describe the results you expected

The network  should be created without default gateway, when --gateway option is not used. Adding some guessed addr as gateway is wrong (and e.g. causes troubles inside the containers, where more default routes are added when more interfaces are used, when default gateway is needed on just one of those).

Note: tried also adding --opt no_default_route=1, but fails with "unsupported macvlan network option no_default_route".

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.28.2
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2.1.6+ds1-1_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.6, commit: unknown'
  cpuUtilization:
    idlePercent: 98.79
    systemPercent: 0.57
    userPercent: 0.64
  cpus: 1
  distribution:
    codename: bookworm
    distribution: debian
    version: "12"
  eventLogger: journald
  hostname: pavpod1
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.1.0-9-amd64
  linkmode: dynamic
  logDriver: journald
  memFree: 1057837056
  memTotal: 1496862720
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun_1.8.1-1+b1_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.1
      commit: f8a096be060b22ccd3d5f3ebe44108517fbf6c30
      rundir: /run/user/0/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.2.0-1_amd64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 0
  swapTotal: 0
  uptime: 0h 32m 30.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 5195333632
  graphRootUsed: 4022796288
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.19.8
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

**Comment by Luap99** [comment]
If you do not want a gateway you should set `--internal`.

I agree that picking the first ip is not optimal. Maybe we should check the routes one the host for a default gateway in this subnet and if none is set do not add a gateway.

> Note: tried also adding --opt no_default_route=1, but fails with "unsupported macvlan network option no_default_route".

You need to use the latest podman and netavark from the main branch to use it, it is not in a released version.

**Comment by pakagi** [comment]
But is --internal really intended for that purpose ? The help says "restrict external access from this network"...

**Comment by Luap99** [comment]
yes it is: https://github.com/containers/podman/issues/13319

But you make a valid point the docs should be updated to clarify the status of --internal and macvlan networks.
