### ISSUE TITLE
.local resolving in nested namespace

### ISSUE THREAD

**Issue by EdwinKM** [containers/podman#18911]
### Bug description

We have issues with .local resolving in combination with podman (desktop). This works fine if we just exit.

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.1.0

### Steps to reproduce

Our setup:
  ESX -> VDI -> Windows 10 Enterprise -> Podman Desktop
  Our company is doing SSL MiTM

 

Basically we did
  * Create %UserProfile%\.wslconfig with "localhostforwarding=true"
  * Installation of Podman Desktop en Windows Terminal
  * Added the MiTM and the company root CA trust in the podman-machine-default
  * Installation of "podman-compose"

 

  

If we select "podman-machine-default" in Windows Terminal we see the "nested namespace" MOTD.
We cd to the folder with the compose and Dockerfile.
Some content is redacted.

 

`
You will be automatically entered into a nested process namespace where
systemd is running. If you need to access the parent namespace, hit ctrl-d
or type exit. This also means to log out you need to exit twice.

 
[user@HOSTNAME ~]$ cd /mnt/c/gitrepo/this-is-our-application/
[user@HOSTNAME this-is-our-application]$ podman-compose up -d

podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.5.0
** excluding:  set()
['podman', 'inspect', '-t', 'image', '-f', '{{.Id}}', 'this-is-our-application_applicationservice']
Error: inspecting object: this-is-our-application_applicationservice: image not known
podman build -f ./Dockerfile -t this-is-our-application_applicationservice --build-arg artifactory_token=ARTIFACTORY_TOKEN --build-arg artifactory_username=ARTIFACTORY_USERNAME .
[1/6] STEP 1/5: FROM docker.repos.local/ubi8/ubi:latest AS jboss_base_image
Trying to pull docker.repos.local/ubi8/ubi:latest...
Error: creating build container: initializing source docker://docker.repos.local/ubi8/ubi:latest: pinging container registry docker.repos.local: Get https://docker.repos.local/v2/: dial tcp: lookup docker.repos.local: Temporary failure in name resolution
exit code: 125
['podman', 'ps', '--filter', 'label=io.podman.compose.project=this-is-our-application', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
['podman', 'network', 'exists', 'this-is-our-application_default']
podman run --name=this-is-our-application_mssqlserverservice_1 -d --label io.podman.compose.config-hash=bbcaa8e0d6ebf3dfa643fe9c08e9a0353ac3a1815f7fe5a02948f879fb2a7dd4 --label io.podman.compose.project=this-is-our-application --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@this-is-our-application.service --label com.docker.compose.project=this-is-our-application --label com.docker.compose.project.working_dir=/mnt/c/gitrepo/this-is-our-application --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=mssqlserverservice -e ACCEPT_EULA=Y -e MSSQL_SA_PASSWORD=myStrong(!)Password -e TZ=Europe/Amsterdam -v /mnt/c/Docker/sql_data:/var/opt/mssql/data -v /mnt/c/Docker/sql_log:/var/opt/mssql/log -v /mnt/c/Docker/sql_secrets:/var/opt/mssql/secrets -v /mnt/c/Docker/bakfiles_share:/mnt/bakfiles_share --net this-is-our-application_default --network-alias mssqlserverservice -p 1433:1433 mcr.microsoft.com/mssql/server:2019-latest
Trying to pull mcr.microsoft.com/mssql/server:2019-latest...
Getting image source signatures
Copying blob bda324a2f0a3 [================>---------------------] 33.1MiB / 73.7MiB
Copying blob 6e66059d3f09 [=================>--------------------] 13.4MiB / 28.5MiB
Copying blob 0350df93555e [====>---------------------------------] 49.6MiB / 393.9MiB
`

 
Notice the problem with pulling from "docker.repos.local"
We can resolve this .local address

`
[user@HOSTNAME this-is-our-application]$ nslookup docker.repos.local
Server:         SERVER_IP
Address:        SERVER_ADDRESS#53

 
Non-authoritative answer:
docker.repos.local canonical name = CNAME.aws.local.
Name:   CNAME.aws.local
Address: ADDRESS1
Name:   CNAME.aws.local
Address: ADDRESS2
Name:   CNAME.aws.local
Address: ADDRESS3
`

Or can we?
`
[user@HOSTNAME this-is-our-application]$ curl https://docker.repos.local/v2/
curl: (6) Could not resolve host: docker.repos.local
`

 

If we break out of the nested namespace with ''exit''.
Now the curl does work fine:

 

`
[user@HOSTNAME this-is-our-application]$ curl https://docker.repos.local/v2/
{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}
`

And we can start the full stack.
This however renders Podman Desktop useless. And our users should be informed to always exit the nested namespace.

 
* What is happening here?
* Is there a workaround?
* Will this be fixed with the WSL change (phase out of the nested namespace?) - https://github.com/containers/podman/discussions/17835

**Comment by benoitf** [comment]
transferring the issue to podman repository as machine/wsl2/dns/etc is managed by this repository

**Comment by Luap99** [comment]
How does /etc/resolv.conf look like in the nested namespace? 

@n1hility Ideas? I assume the new `--user-mode-networking` option might fix that?

**Comment by EdwinKM** [comment]
The resolve.conf seems the same

` cat /etc/resolv.conf

# This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:

# [network]

# generateResolvConf = false

nameserver 172.24.48.1`


slirp4netns and podman-plugins are installed.
Also tried rootful mode. None seems to change anything.

fwiw, found this in a post.


[user@VDT238657 ~]$ cat /proc/self/cgroup

15:name=systemd:/user.slice/user-1000.slice/session-c3.scope

14:misc:/

13:rdma:/

12:pids:/user.slice/user-1000.slice/session-c3.scope

11:hugetlb:/

10:net_prio:/

9:perf_event:/

8:net_cls:/

7:freezer:/

6:devices:/user.slice

5:memory:/user.slice/user-1000.slice/session-c3.scope

4:blkio:/user.slice

3:cpuacct:/

2:cpu:/user.slice

1:cpuset:/

0::/user.slice/user-1000.slice/session-c3.scope

[user@VDT238657 ~]$

logout

[user@VDT238657 ~]$ cat /proc/self/cgroup

15:name=systemd:/

14:misc:/

13:rdma:/

12:pids:/

11:hugetlb:/

10:net_prio:/

9:perf_event:/

8:net_cls:/

7:freezer:/

6:devices:/

5:memory:/

4:blkio:/

3:cpuacct:/

2:cpu:/

1:cpuset:/

0::/
`

**Comment by EdwinKM** [comment]
@Luap99 Do you need more information?

**Comment by rhatdan** [comment]
@Luap99 Any update?

**Comment by Luap99** [comment]
@n1hility would know.
I have no idea how wsl networking works.

**Comment by n1hility** [comment]
@EdwinKM  looks like we had a bug introduced on Windows as part of F37+, where systemd-resolved is still running (it should be disabled). This is caused by the systemd target name with the want changing.  Normally this would be harmless, but since .local is (by default) not relayed to dns per default nssswitch policy, those names will never resolve. To workaround the issue you can run ```systemctl disable systemd-resolved.service``` on the WSL prompt, and then back on a windows prompt restart it ```podman machine stop; podman machine start```

**Comment by EdwinKM** [comment]
This seems to be solved with the workaround. However, when will it be upstream?
