### ISSUE TITLE
Support for updating additionalimagestores by non-root users

### ISSUE THREAD

**Issue by yeswalrus** [containers/podman#18918]
### Feature request description

I'd like to be able to have a non-root user pull images to a directory being used as an additionalimagestore.

The workflow I imagine is this:
User A updates branch and compiles new image, then updates a repo to point at the new image
User B pulls the repo, then tries to run a command relying on the new image. A script running notices the image isn't in the shared cache(additionalimagestore), and adds it.
User C pulls the repo, tries to run the same command. The same script sees that the image *is* in the cache and runs

This scenario is for a multi-user compute cluster, where the shared image store is on a XFS mountpoint.

### Suggest potential solution

I'd like any user to be able to run a command to cleanly add to the image store given correct permissions on the directory.
ex: /share/podman_cache might be owned by group `cacheworker` with g+rwx , and any user in that group would be able to add to the cache, while other users would only have +rx.
Updating would ideally happen with `podman --root /share/podman_cache --sharedroot image pull <image>` or some other flag which would indicate we were pulling to a shared cache directory, and cause podman to not write anything not meant to be shared & automatically set permissions so we didn't have to run `chmod -R <store>` manually after.

### Have you considered any alternatives?

At the moment, the only way I can see this working is by writing a small C executable that runs `podman --root <store> image pull <image> && chmod -R ag+rx <store>` and have it be owned by root with the +s bit set, which makes me concerned about introducing security holes.

**Comment by vrothberg** [comment]
Thanks for reaching out, @yeswalrus!

@giuseppe @rhatdan PTAL

**Comment by giuseppe** [comment]
I don't think we can handle that use case just with groups ownership.  For that to work, we would also need to chown each file in the storage to be writeable by the group and that has an effect on the containers since we affect files in the layers.

**Comment by giuseppe** [comment]
I am closing this issue because it is not possible to achieve it, you'd need a privileged helper tool to run "podman pull" as root user.
