### ISSUE TITLE
Error: Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Unknown Error

### ISSUE THREAD

**Issue by mdddj** [containers/podman#18922]
### Bug description

<img width="1050" alt="image" src="https://github.com/containers/podman-desktop/assets/29020213/8b64a183-7dfc-4076-9fe6-0fb83ba31861">

### Operating system

Mac14.0 M1 Pro

### Installation Method

Installer from website/GitHub releases

### Version

1.1.0

**Comment by benoitf** [comment]
Transferring to podman repository as the podman machine is managed by this repository

**Comment by Luap99** [comment]
On an M1/2 you have to install the arm version. This looks like you installed the x86_64 version.
