### ISSUE TITLE
Podman 4.4.1 doesn't support "ENCRYPTED SIGSTORE PRIVATE KEY"

### ISSUE THREAD

**Issue by LiZhang19817** [containers/podman#18937]
### Issue Description

podman -v
podman version 4.4.1

### Steps to reproduce the issue

Steps to reproduce the issue
1. Generate sigstore key pair with command "cosign generate-key-pair", and Cosign enforce to provide password
2. Push image to Redhat Quay by specifying the Cosign private key, and input correct pasword.

### Describe the results you received

Describe the results you received

### Describe the results you expected

When using https://docs.sigstore.dev/cosign/installation/ to generate key pair,  and use to sign image when push image with podman, hit error "Error: initializing private key: unsupported pem type: ENCRYPTED SIGSTORE PRIVATE KEY"

Is it known issue or any other suggestions here?

### podman info output

```yaml
podman push quay-quay-quay390.apps.quaytest-977.qe.devcluster.openshift.com/quay/demo --tls-verify=false --sign-by-sigstore-private-key=./cosign.key
Key Passphrase: 
Error: initializing private key: unsupported pem type: ENCRYPTED SIGSTORE PRIVATE KEY
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by vrothberg** [comment]
Thanks for reaching out, @LiZhang19817.

I think this should work.  @mtrmac, did we support it after 4.4.1?

**Comment by LiZhang19817** [comment]
The error message is clear that the Cosign Private key is encrypted with password, and when you using command "cosign generate-key-pair" to generate a key pair, you must input the password, how to W/A this issue, or maybe need to wait for new podman version.

**Comment by mtrmac** [comment]
The support for this was added to Podman in https://github.com/containers/podman/commit/260bc3ec4c9020fa4555506a9aa5196b89f20a39 , i.e. released in 4.5.0 .

Alternatively, you could manually edit the (copy of the) key to replace SIGSTORE with COSIGN; the two formats are identical, it’s just the identifier that differs.

**Comment by rhatdan** [comment]
Since this is in the next release, closing.  Continue conversation here.

**Comment by LiZhang19817** [comment]
Get it, thx @rhatdan @mtrmac
