### ISSUE TITLE
Expose buildah --compression-level on push command

### ISSUE THREAD

**Issue by ralbertazzi** [containers/podman#18939]
### Feature request description

`buildah push` provides a [--compression-level](https://www.mankier.com/1/buildah-push#--compression-level) argument which is however not exposed on `podman`. It would be great to let this parameter bubble out in podman's CLI, similarly to `--compression-format`

### Have you considered any alternatives?

The alternative would be to use buildah directly.

**Comment by giuseppe** [comment]
opened a PR to expose the option: https://github.com/containers/podman/pull/18940
