### ISSUE TITLE
host dns resolution broken with rootless podman

### ISSUE THREAD

**Issue by mohan43u** [containers/podman#18934]
### Issue Description

`aardvark-dns` cannot communicate with host dns server (systemd-resolved). seems `slirp4netns` built-in dns resolution is broken with `--enable-sandbox`, see [this issue](https://github.com/rootless-containers/slirp4netns/issues/315).

Since podman sets `10.0.2.3` as first `nameserver` in /etc/resolv.conf for `aardvark-dns`, `aardvark-dns` cannot communicate to host dns server (systemd-resolved), `aardvark-dns` communicate to next `nameserver` only after it gets `None()` (empty response) from 10.0.2.3, by the time it gets response from the second nameserver, the dns query requester (`ping`) in the container already timed out and failed.

The current workaround is to disable passing `--enable-sandbox` to `slirp4netns`. I dont know the relationship between `no_pivot_root` and `--enable-sandbox`, but setting `no_pivot_root = true` disables passing `--enable-sandbox` to `slirp4netns`.

```console
mkdir -p ~/.config/containers/containers.conf.d
echo -e "[engine]\nno_pivot_root = true\n" >~/.config/containers/containers.conf.d/disable-sandbox.conf
```
Until `slirp4netns` fix, `podman` should not pass `--enable-sandbox` by default to `slirp4netns` for rootless containers.

### Steps to reproduce the issue

Steps to reproduce the issue
```console
podman network create testnet
podman container run --rm --rmi --network testnet docker.io/library/alpine ping -c 2 google.com
```

### Describe the results you received

given steps will fail to resolve `google.com` with `bad address`

### Describe the results you expected

ping command inside alpine should resolve `google.com` to an IP address

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.7-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: f633919178f6c8ee4fb41b848a056ec33f8d707d'
  cpuUtilization:
    idlePercent: 99.4
    systemPercent: 0.27
    userPercent: 0.33
  cpus: 2
  databaseBackend: boltdb
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: netcup0-host0
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.3.8-arch1-1
  linkmode: dynamic
  logDriver: journald
  memFree: 447934464
  memTotal: 2067918848
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.8.5-1
    path: /usr/bin/crun
    version: |-
      crun version 1.8.5
      commit: b6f80f766c9a89eb7b1440c0a70ab287434b17ed
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.2.0-1
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 0
  swapTotal: 0
  uptime: 4h 8m 9.00s (Approximately 0.17 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/mohan/.config/containers/storage.conf
  containerStore:
    number: 8
    paused: 0
    running: 8
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/mohan/.local/share/containers/storage
  graphRootAllocated: 40895807488
  graphRootUsed: 13158592512
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 7
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/mohan/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.1
  Built: 1685139594
  BuiltTime: Sat May 27 00:19:54 2023
  GitCommit: 9eef30051c83f62816a1772a743e5f1271b196d7-dirty
  GoVersion: go1.20.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

```console
$ uname -a
Linux host0 6.3.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 14 Jun 2023 20:10:31 +0000 x86_64 GNU/Linux
$
```

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
From the slirp4netns [man page](https://github.com/rootless-containers/slirp4netns/blob/master/slirp4netns.1.md):
> --enable-sandbox (since v0.4.0) enter the user namespace and create a new mount namespace where only /etc and /run are mounted from the host.
> Requires /etc/resolv.conf not to be a symlink to a file outside /etc and /run.
> When running as the root, the process does not enter the user namespace but all the capabilities except CAP_NET_BIND_SERVICE are dropped.

So does your /etc/resolv.conf point outside of /etc or /run? 

I rather not change important security options like that.

**Comment by mohan43u** [comment]
> So does your /etc/resolv.conf point outside of /etc or /run?

Thanks, this is the root cause, my `/etc/resolve.conf` was pointing to `/var/run/systemd/resolve/stub-resolv.conf` instead of `/run/systemd/resolv/stub-resolv.conf`. I fixed it now. everything works as expected
