### ISSUE TITLE
huge amount of sessions when lingering enables for rootless container started via systemd

### ISSUE THREAD

**Issue by dada216** [containers/podman#18957]
we have a podman host (it's kept updated with the rhel9.1 release) which runs production services in rootless containers.
we might have misunderstood how this is supposed to interact with the OS (rhel) because we observe a huge amount of open user session for the user we created to handle containers.

we have created a container user, the user is not member of the wheel group, via root we enabled lingering for the container user, we have a certain amount of rootless containers started under this user systemd services, we also log in interactively with the same user to run other containers and develop/test scripts and services inside those containers.

we noticed that upon reboot we have hundreds of open sessions, it occured to us that lingering keeps every single session open, both the one needed for the user systemd rootless containers and the interactive sessions we created when we ssh into the server and do our development/test.

are there guidelines about how to handle this? is our assumption correct and lingering keeps open every single interactive login session we made to the server?

**Comment by vrothberg** [comment]
Thanks for reaching out, @dada216.

With `lingering` enabled, the sessions will be kept open if there are still running processes attached to this session (see https://www.freedesktop.org/software/systemd/man/logind.conf.html#KillUserProcesses=).  When ssh-ing into the machine, are the containers still running on logout?

**Comment by dada216** [comment]
thanks for the reply @vrothberg,
Yes, when we log back into the server the containers are still running.

**Comment by giuseppe** [comment]
sessions created through ssh should not be kept alive forever if they are terminated.

You can see all the current sessions with `loginctl list-sessions` and get more information about each of those with `loginctl session-status $ID`.

Closing since it is not a Podman issue.  Feel free to continue the discussion though

**Comment by vrothberg** [comment]
An alternative may be using the REST API to create these containers on the remote machine.
