### ISSUE TITLE
Native NBD support

### ISSUE THREAD

**Issue by jpalus** [containers/podman#18990]
### Feature request description

Not sure if it's in scope of `podman` but anyway but it would really nice if `podman` had native support for `NBD` (Network Block Device). Some host exposes block device over network `podman` connects to it and makes it available as a block device inside container. Could be quite useful for rootless containers.

**Comment by rhatdan** [comment]
Interested in opening a PR?

**Comment by Luap99** [comment]
Before opening PRs we should agree on designs.
First, I don't know how NBD works but if it creates devices then it will not be possible to use it rootless. Rootless users are not allowed to create devices.

If the block device is available on the host you could just mount it into the container with `--device` or `--volume`.

**Comment by rhatdan** [comment]
Since we have heard nothing back on this, closing.  Reopen if you still would like us to pursue this?
