### ISSUE TITLE
Introductory tutorial test of first container rum

### ISSUE THREAD

**Issue by evelynmitchell** [containers/podman#18992]
### Feature request description

The introductory tutorial has the example of using podman to run a webserver from the fedora project on port 8080.

To be able to verify that this worked the user needs to know how to test this.

The introductory tutorial skipped the testing step

### Suggest potential solution

I would like someone to be able to verify that the first test of podman worked, by doing the steps needed to verify,

To do that, those instructions need to be explicit.

### Have you considered any alternatives?

I could assume someone running the podman introductory tutorial knows how to test if a webserver container ran correctly. 

For experienced users, this step is likely redundant. Introductory tutorials often are used by more inexperienced people.

### Additional context

I've made a patch.

**Comment by Luap99** [comment]
Sounds good, if you have a patch to improve the docs PRs are always welcome.

**Comment by rhatdan** [comment]
Since this never went forward I am closing.  Reopen if you want to update the docs.
