### ISSUE TITLE
1Password & Podman Kube Play Secrets

### ISSUE THREAD

**Issue by MadSpindel** [containers/podman#19014]
I'm trying to understand how I can use secrets in Podman Kube Play in a secure way. Committing secrets in cleartext into my GitHub repo is not an option. I would like to use my password manager 1Password instead. Is this possible somehow? I know it exists a 1Password Secrets Injector for Kubernetes, but that is not possible to use with Podman Kube Play, right?

https://github.com/1password/kubernetes-secrets-injector
https://github.com/1Password/onepassword-operator

**Comment by fsdrw08** [comment]
consider encrypt your secret by sops

**Comment by MadSpindel** [comment]
@fsdrw08 That could absolutely be the solution. I realized I could do something similar with 1Password with op inject:
https://developer.1password.com/docs/cli/reference/commands/inject/

I'll close this issue.
