### ISSUE TITLE
Possible to set user-mode networking from `podman machine start` on WSL2?

### ISSUE THREAD

**Issue by gbraad** [containers/podman#19022]
### Feature request description

Currently, there is no option to start

```
PS> podman machine init --user-mode-networking
```

from Podman Desktop.

### Suggest potential solution

Expose this somehow as an option from the configuration interface.

### Have you considered any alternatives?

Ideally, this should be a `podman machine start`-option. So, let's start the discussion...

### Additional context

This will otherwise need a destructive `machine rm` to allow the use.

**Comment by gbraad** [comment]
Currently, the user has to run:

````
PS> podman machine rm
PS> podman machine init --user-mode-networking
```

**Comment by Luap99** [comment]
Did you mean to file this against podman-desktop?

As far as config goes should this be configurable with `podman machine set` instead of start?

**Comment by gbraad** [comment]
Ideally. This should also be filed against podman desktop, but rather have this resorted before. If this happens during the creation stage, this needs a modification to the Podman extension to ask the user on installation, or possibly when changed in the configuration to delete the existing instance, etc. It seems a lot of hassle for something that is an additional start of the `vmproxy` binary. If technically difficult, a user flow for Podman Desktop needs to be discussed.

**Comment by Luap99** [comment]
Well if you want to set it on start it means it must be set on each start. With `machine set` you only need to call this once then we store the wanted value and know what to do on start.

cpu, memory, etc... They all could be set on start but we went with the machine set design. I think we should be consistent here and not start adding options to start.  

And actually this is already supported by `podman machine set` as it looks:
```
$ bin/podman machine set --help | grep network
      --user-mode-networking   Whether this machine should use user-mode networking, routing traffic through a host user-space process
```

**Comment by Luap99** [comment]
cc @n1hility @baude @ashley-cui

**Comment by gbraad** [comment]
> actually this is already supported by podman machine set as it looks:

haven't tested or verified the code, but does hit enable this also for an already existing installation, or is a recreation necessary? The instructions that were given to the customer included `machine rm -f`.

**Comment by gbraad** [comment]
BTW, I have `podman.exe version 4.5.1`

```
PS> podman --version
podman.exe version 4.5.1
PS> podman machine set --help
Sets a virtual machine setting

Description:
  Sets an updatable virtual machine setting

Usage:
  podman.exe machine set [options] [NAME]

Examples:
  podman machine set --rootful=false

Options:
      --cpus uint        Number of CPUs
      --disk-size uint   Disk size in GB
  -m, --memory uint      Memory in MB
      --rootful          Whether this machine should prefer rootful container execution
```

so, no `--user-mode-networking` option exposed

**Comment by Luap99** [comment]
230ddbe0caf6f2ad7d88346b0f862bb17f011a30 was merged after 4.5 so it will only be added in 4.6.

**Comment by gbraad** [comment]
when is 4.6 expected?

**Comment by Luap99** [comment]
rc1 should be next week, if there are no big issues reported then the final release soon after that.

**Comment by rhatdan** [comment]
I believe this is fixed in the current released version, closing.  Reopen if I am mistaken.
