### ISSUE TITLE
hostnames are not propagated to other containers in the same network

### ISSUE THREAD

**Issue by benoitf** [containers/podman#19025]
### Issue Description

Here is a difference with hosts handling between docker and podman

in docker if you start a container with a given hostname on a custom network, this hostname is reachable from other containers on the same network

in podman it's not the case

### Steps to reproduce the issue

Steps to reproduce the issue

## steps on docker:

1. Create network
```
$ docker network create my-network
```

2. Start the first container (here for example a database) using a host
```
$ docker run -d --name redis-container --hostname redis --network my-network redis
```

3. start a fedora container for example
```
$ docker run -d --name fedora-container --hostname fedora --network my-network fedora tail -f /dev/null
```

4. Now connect to the fedora container and try to ping 'redis' host
```
$ docker exec -ti fedora-container bash
[root@fedora /]# yum install -y iputils
[root@fedora /]# ping redis
PING redis (172.20.0.2) 56(84) bytes of data.
64 bytes from redis-container.my-network (172.20.0.2): icmp_seq=1 ttl=64 time=0.187 ms
64 bytes from redis-container.my-network (172.20.0.2): icmp_seq=2 ttl=64 time=0.096 ms
```
it works and it's replying from `redis-container.my-network`

Now, using podman:
## steps on podman:

1. Create network
```
$ podman network create my-network
```

2. Start the first container (here for example a database) using a host
```
$ podman run -d --name redis-container --hostname redis --network my-network redis
```

3. start a fedora container for example
```
$ podman run -d --name fedora-container --hostname fedora --network my-network fedora tail -f /dev/null
```

4. Now connect to the fedora container and try to ping 'redis' host
```
$ podman exec -ti fedora-container bash
[root@fedora /]# yum install -y iputils
root@fedora /]# ping redis
ping: redis: Name or service not known

```

it doesn't work, name is not found

of course it works using the container name but it's not what was expected 
```
[root@fedora /]# ping redis-container
PING redis-container.dns.podman (10.89.2.2) 56(84) bytes of data.
64 bytes from 10.89.2.2 (10.89.2.2): icmp_seq=1 ttl=64 time=0.074 ms
64 bytes from 10.89.2.2 (10.89.2.2): icmp_seq=2 ttl=64 time=0.084 ms
64 bytes from 10.89.2.2 (10.89.2.2): icmp_seq=3 ttl=64 time=0.082 ms
64 bytes from 10.89.2.2 (10.89.2.2): icmp_seq=4 ttl=64 time=0.112 ms
```

### Describe the results you received

From the fedora container
```
[root@fedora /]# ping redis
ping: redis: Name or service not known
```

### Describe the results you expected

expect to have the ping to the hostname of the other container working

### podman info output

```yaml
4.5.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rhatdan** [comment]
@Luap99 PTAL

**Comment by Luap99** [comment]
Duplicate of #17370 I assume

**Comment by benoitf** [comment]
looks like 👍

**Comment by benoitf** [comment]
closing as dup of https://github.com/containers/podman/issues/17370

**Comment by Luap99** [comment]
I put it on my TODO list, the fix should be easy enough.
