### ISSUE TITLE
slight difference in error message with inspect between docker and podman

### ISSUE THREAD

**Issue by benoitf** [containers/podman#19027]
### Feature request description

I'm trying to run some Docker Desktop extensions on top of podman

One of this extension is using the inspect command to figure out if a container is already started or not and search for a string in returned error message. In this case they were expecting `No such object`

like `docker inspect foo` command

in docker we have error message
```
docker inspect foo                                                                                                                                                                                                   []
Error: No such object: foo
```

and in podman we have:
```
podman inspect foo                                                                                                                                                                                                 []
Error: inspecting object: no such object: "foo"
```

so `No` vs `no` then it was failing the logic

### Suggest potential solution

Of course I've proposed to the extension to search on a lowercase version of the error message

but other extensions could rely on the same kind of logic so I was wondering if Uppercase letter could be added

### 1. diff in `container inspect` as well
```
docker container inspect foo                                                                                                                                                                                       []
Error response from daemon: No such container: foo
```
```
podman container inspect foo                                                                                                                                                                                         
[]
Error: inspecting object: no such container "foo"
```

### 2. diff in order sequence for network `network {name} not found` vs `network {name}: network not found`
```
docker network inspect foo                                                                                                                                                                                         []
Error response from daemon: network foo not found
```

```
 podman network inspect foo                                                                                                                                                                                         []
Error: inspecting object: network foo: network not found
```

### 3. for volumes it's OK

```
docker volume inspect foo                                                                                                                                                                                            
[]
Error response from daemon: get foo: no such volume
```

```
podman volume inspect foo                                                                                                                                                                                            []
Error: inspecting object: no such volume "foo"
```

### 4. diff in default inspect
```
docker inspect foo                                                                                                                                                                                                   []
Error: No such object: foo
```

and in podman we have:
```
podman inspect foo                                                                                                                                                                                                 []
Error: inspecting object: no such object: "foo"
```

**Comment by rhatdan** [comment]
In Podman we enforce no capitalization on error codes, so this would be a huge change. Although I think the `inspecting object` part of this error is just noise and should be removed.

**Comment by Luap99** [comment]
string parsing error messages is always kinda broken. External tools should just check exit codes IMO.
For podman we added `podman container/image/volume/network exists` commands to make this trivial for users but well that doesn't help with docker compat obviously.

**Comment by benoitf** [comment]
yes I know it can be broken, just seeing tools relying on the error message.
I have no opinion. Could be a 'won't fix' I'm just reporting that tools were not working at first when doing the switch from docker engine to podman engine.

**Comment by rhatdan** [comment]
Could you open an issue with this plugin, to at least do the string compare after doing a ToLower()

**Comment by benoitf** [comment]
I've already submitted patches (that were merged) to handle the difference

**Comment by rhatdan** [comment]
Awesome.  I don't see us changing, although I did open a quick PR to remove the extra noise on the error message.

**Comment by vrothberg** [comment]
I reopen as I want to explore the issue a bit further.  @benoitf, is this plugin using the CLI or the REST API?  Because we must be compatible on the REST API.

**Comment by benoitf** [comment]
@vrothberg CLI

In fact Docker Desktop extensions have an API to execute commands
https://github.com/microcks/microcks-docker-desktop-extension/blob/main/client/src/api/containers.ts#L35-L36

that is then executed on the host through CLI

And extension can grab error and analyze it
https://github.com/microcks/microcks-docker-desktop-extension/blob/main/client/src/api/containers.ts#L55

(now you can see it's checking using the lowercase)

**Comment by vrothberg** [comment]
Thanks for elaborating, @benoitf!

I agree that this will be hard to tackle on the CLI.  We probably need to tackle issues as they come in.
