### ISSUE TITLE
Support for kube collections

### ISSUE THREAD

**Issue by StanEgo** [containers/podman#19052]
### Feature request description

It would be nice to have a support for https://kubernetes.io/docs/reference/using-api/api-concepts/#collections. Nothing sophisticated, just looks like a resource with "kind: List", but this greatly simplifies to play kube manifest in JSON with multiple resources. Right now code below results in "Error: playing YAML file: YAML document does not contain any supported kube kind" message:

```
{
  "apiVersion": "v1",
  "kind": "List",
  "items": [
    {
      "apiVersion": "v1",
      "kind": "ConfigMap",
      ...
    },
    {
      "apiVersion": "apps/v1",
      "kind": "Deployment",
      ...
```

**Comment by rhatdan** [comment]
@umohnani8 WDYT?

**Comment by rhatdan** [comment]
@ygalblum WDYT?

**Comment by ygalblum** [comment]
I don't see a reason why not to support this. Especially since the code already handles a list of documents. It will just need to be adjusted to a document that is a list.
I'll see if I can find a time slot for this
