### ISSUE TITLE
Podman complaining about missing global policy.json while a local one is present

### ISSUE THREAD

**Issue by Erwyn** [containers/podman#19073]
### Issue Description

I installed Podman through Nix. I have a `policy.json` defined as this in `/home/MYUSER/.config/containers/policy.json`:

```json
{
    "default": [
        {
            "type": "insecureAcceptAnything"
        }
    ]
}
```

 I don't have an `/etc/containers/policy.json`. 

If i issue a `podman image trust show` I get an `Error: open /etc/containers/policy.json: no such file or directory` . I checked running strace and I do see that `newfstatat(AT_FDCWD, "/home/MYUSER/.config/containers/policy.json", {st_mode=S_IFREG|0644, st_size=93, ...}, 0) = 0` but still get the error of the missing /etc/containers/policy.json file.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Have a local (/home/MYUSER/.config/containers/policy.json) policy file
2. Run `podman image trust show`
3. See it fail with error message regarding missing /etc/containers/policy.json

### Describe the results you received

I get an `Error: open /etc/containers/policy.json: no such file or directory`.

```bash
$ podman image trust set -t reject default
Error: open /etc/containers/policy.json: permission denied
```

If we enforce with `sudo` then /etc/containers/policy.json gets created.

### Describe the results you expected

I expect the local `policy.json` to be sufficient and be the only file read.

### podman info output

```yaml
❯❯❯ podman version
Client:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.20.5
Built:        Tue Jan  1 01:00:00 1980
OS/Arch:      linux/amd64

❯❯❯ podman info
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /nix/store/bbxml9qrpvlq8hijvamqwd2mk0wcknsw-conmon-2.1.7/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 88.9
    systemPercent: 3.33
    userPercent: 7.77
  cpus: 8
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: kde
    version: "35"
  eventLogger: journald
  hostname: MyMachine
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.0.12-100.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1067839488
  memTotal: 16423763968
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: Unknown
    path: /nix/store/pbmmg9k43qdj7ji7kj1dc2wz67dd86ns-crun-1.8.5/bin/crun
    version: |-
      crun version 1.8.5
      commit: 1.8.5
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /nix/store/kwdv5jw8awxw31i25i4l93qgy43srr20-slirp4netns-1.2.0/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 8513908736
  swapTotal: 8589930496
  uptime: 7h 33m 40.00s (Approximately 0.29 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/MYUSER/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/MYUSER/.local/share/containers/storage
  graphRootAllocated: 510389125120
  graphRootUsed: 218087268352
  graphStatus: {}
  imageCopyTmpDir: /tmp/nix-shell.EeYf91
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/MYUSER/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.1
  Built: 315532800
  BuiltTime: Tue Jan  1 01:00:00 1980
  GitCommit: ""
  GoVersion: go1.20.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Installed Fedora through Nix package manager 

### Additional information

nothing

**Comment by Luap99** [comment]
@mtrmac @vrothberg PTAL

**Comment by Erwyn** [comment]
Just in case, I discussed this issue with @lsm5 and @vrothberg on the Podman Matrix room where @vrothberg confirmed that it seemed unexpected.

**Comment by ariasmn** [comment]
Hi

Just had a look at this and seems like the problem lies here:
https://github.com/containers/podman/blob/9d9f4aaafea01b6604c3a54b9a934c21090ef64a/pkg/trust/policy.go#L56-L67

I tried using an implementation similar to the one used in the `image` package and seems like this would solve the problem:
https://github.com/containers/podman/blob/9d9f4aaafea01b6604c3a54b9a934c21090ef64a/vendor/github.com/containers/image/v5/signature/policy_config.go#L63-L75

I wouldn't mind contributing a PR for this, however, I still want to hear your thoughts (since maybe this is not the correct way of tackling this, or perhaps you have some plans regarding this task, etc.)

**Comment by mtrmac** [comment]
@ariasmn Yes, I think updating `podman/pkg/trust.DefaultPolicyPath` seems reasonable. Conceptually I’m not much of a fan of exposing `signature.defaultPolicyPathWithHomeDir` as a stable API (that commits us to the policy being in a single file, for example) — but then `podman trust` really needs that value, so we ended up with a copy in `podman/pkg/trust`.

**Comment by ariasmn** [comment]
@rhatdan Sure, I will work on it in the coming days!

@mtrmac Yeah, makes perfect sense. I still have some doubts, for example, about where I should declare the `userPolicyFile` variable. I guess that it makes a lot of sense to just declare it in the config files, example:

https://github.com/containers/podman/blob/cd58306a811b34c920479a933123b4ac9df0f614/vendor/github.com/containers/common/pkg/config/config_linux.go#L10-L20

However, I don't know if it's the best thing, nor I have a lot of experience with vendoring, so I would appreciate some pointers for this!

**Comment by mtrmac** [comment]
Nothing about `userPolicyFile` is configurable, and I don’t think it makes any sense to make that an option. Similarly to the exiting code in `policy_config.go`, I would recommend just hard-coding a value in `trust/policy.go`.

**Comment by ariasmn** [comment]
Just created a PR.

Please let me know if any further work is needed on my part!

**Comment by Erwyn** [comment]
Nice, thank you very much, will try this as soon as possible.
