### ISSUE TITLE
invalid version displayed in the pkg installer of v4.6.0-RC1

### ISSUE THREAD

**Issue by benoitf** [containers/podman#19103]
### Issue Description

I've downloaded https://github.com/containers/podman/releases/download/v4.6.0-rc1/podman-installer-macos-arm64.pkg

When I run it, it displays 4.5.0
![image](https://github.com/containers/podman/assets/436777/961e588c-b945-4576-aa5d-6cb00e6567d7)

### Steps to reproduce the issue

1. Download the pkg and execute it

you can also check by unpacking the files

```
pkgutil --expand  ~/Downloads/podman-installer-macos-arm64.pkg /tmp/pkg
more /tmp/pkg/Distribution                                                                                                      ✔  8s 
<?xml version="1.0" encoding="utf-8"?>
<installer-script minSpecVersion="1">
    <title>Podman 4.5.0</title>
    <background mime-type="image/png" file="banner.png" scaling="proportional"/>
    <welcome file="welcome.html" mime-type="text/html"/>
    <conclusion file="conclusion.html" mime-type="text/html"/>
    <license file="LICENSE.txt"/>
    <options customize="never" hostArchitectures="x86_64,arm64"/>
    <domains enable_localSystem="true"/>
    <choices-outline>
        <line choice="podman"/>
    </choices-outline>
    <choice id="podman" title="podman">
        <pkg-ref id="podman.pkg"/>
    </choice>
    <pkg-ref id="podman.pkg" packageIdentifier="com.redhat.podman" version="4.5.0" installKBytes="396521">#podman.pkg</pkg-ref>
    <pkg-ref id="podman.pkg">
        <bundle-version/>
    </pkg-ref>
</installer-script>
```

### Describe the results you received

4.5

### Describe the results you expected

4.6.0-RC1

### podman info output

```yaml
no
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by vrothberg** [comment]
Thanks for reaching out, @benoitf!

@lsm5 can you take a look?

**Comment by ashley-cui** [comment]
Huh, don't know how that happened. I think maybe I forgot to run `make clean` before building. Anyway, updated and fixed, thanks!
