### ISSUE TITLE
`podman container prune --filter until=` | All stopped containers removed regardless the time value they lastly were created within

### ISSUE THREAD

**Issue by Ricky-Tigg** [containers/podman#19119]
### For reference
Manual _podman-container-prune(1)_
```
 Remove all stopped containers from local storage created within last 10 minutes.
  $ podman container prune --filter until="10m"
```
### Description
Hello. The `until` filter removes all stopped containers from local storage regardless the time value they lastly were created within.
```
$ podman ps -a
CONTAINER ID  IMAGE                           COMMAND           CREATED         STATUS                    PORTS                 NAMES
0efb80fe2e82  docker.io/library/httpd:latest  httpd-foreground  22 seconds ago  Exited (0) 5 seconds ago  0.0.0.0:8080->80/tcp  elastic_swanson
$ podman run -dt -p 8080:80/tcp docker.io/library/httpd:latest
0efb80fe2e829bce07cbb19bd61da807f6fce2da3ac43d59901c394667d9acfc
```

### Steps to reproduce the issue

Shortest time value chosen, _one second_, so that no container is expected to be eligible for selection for removal as **no container was lastly created within that value**:
```
$ podman container prune --filter until="1s"
WARNING! This will remove all non running containers.
Are you sure you want to continue? [y/N] y
0efb80fe2e829bce07cbb19bd61da807f6fce2da3ac43d59901c394667d9acfc
```

### Describe the results you received

All non running containers that were non eligible for removal were removed from local storage.

### Describe the results you expected

Output's presented in this order

1. **Exhaustive description** of the future operation; model:

`[Warming] This will remove all non running containers created within the last 1 second(s) from local storage.`

2. Previous statement followed by the selection of the eligible containers.

3. The presentation of choice:

"`Are you sure you want to continue? [No/yes]`".

Since no non running container was created within the **last second**, there should have been no container eligible for removal.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.31.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc38.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 68.94
    systemPercent: 5.7
    userPercent: 25.36
  cpus: 4
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: workstation
    version: "38"
  eventLogger: journald
  freeLocks: 2048
  hostname: fedora
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 6.3.11-200.fc38.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 3325014016
  memTotal: 8190038016
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.7.0-1.fc38.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.7.0
    package: netavark-1.7.0-1.fc38.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.7.0
  ociRuntime:
    name: crun
    package: crun-1.8.5-1.fc38.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.5
      commit: b6f80f766c9a89eb7b1440c0a70ab287434b17ed
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20230625.g32660ce-1.fc38.x86_64
    version: |
      pasta 0^20230625.g32660ce-1.fc38.x86_64
      Copyright Red Hat
      GNU Affero GPL version 3 or later <https://www.gnu.org/licenses/agpl-3.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-12.fc38.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 8189374464
  swapTotal: 8189374464
  uptime: 0h 21m 19.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/yk/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/yk/.local/share/containers/storage
  graphRootAllocated: 160498188288
  graphRootUsed: 22981140480
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 5
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/yk/.local/share/containers/storage/volumes
version:
  APIVersion: 4.6.0-rc1
  Built: 1688395307
  BuiltTime: Mon Jul  3 17:41:47 2023
  GitCommit: ""
  GoVersion: go1.20.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.0-rc1
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

**Comment by vrothberg** [comment]
Thanks for reaching out, @Ricky-Tigg!

@jakecorrenti, interested in taking a look at it?

**Comment by jakecorrenti** [comment]
Sure thing, I'll take a look

**Comment by Ricky-Tigg** [comment]
An investigation to determine the time/duration formats led me to https://pkg.go.dev/time#Duration.

"_A duration string is a possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as "300ms", "-1.5h" or "2h45m". Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h"._"

Hence, supposing that source as being correct, Podman behaves as intended by failing to parse units matching _day_, _month_ and _year_, respectively possibly, _d_ or _D_, _M_ and _y_ or _Y_ that are as time value in `podman` commands.

The format of timestamp as expressed by '`podman container logs -tl`' appears to be identical to the one that is expressed by '`date --iso-8601=ns`'.
```
$ date --iso-8601=ns
2023-07-06T19:07:13,673348006+03:00
```
Application in Podman:
```
$ podman container prune --filter until=`date --iso-8601=ns`
WARNING! This will remove all non running containers.
Are you sure you want to continue? [y/N] y
9d846f91b8efc1b6d9496510f56b5312e25c653af10c17b20d7890712718a0d7
```
Then a time value expressed in that format triggers this same faulty behavior.

**Comment by Ricky-Tigg** [comment]
An investigation to determine the time/duration formats led me to https://pkg.go.dev/time#Duration.

"_A duration string is a possibly signed sequence of decimal numbers, each with optional fraction and a unit suffix, such as "300ms", "-1.5h" or "2h45m". Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h"._"

Hence, supposing that source as being correct, Podman behaves as intended by failing to parse units matching _day_, _month_ and _year_, respectively possibly, _d_ or _D_, _M_ and _y_ or _Y_ that are as time value in `podman` commands.

**Comment by jakecorrenti** [comment]
Hi @Ricky-Tigg, thank you for filing this issue. The behavior that you are experiencing with the `--filter until` flag is correct and will remove all containers **except** those created within the time specified. 

If you are trying to remove all containers that were created within the last 10 minutes, you are looking for a `since` filter, which I filed an issue for in #19228

The documentation's example you noted was incorrect and will be changed in #19227.

**Comment by Ricky-Tigg** [comment]
I had a doubt that manual's description may apply to _since_ and therefore might be incorrect. Thanks to that future `since` filter it won't be necessary to compile their equivalent time expressions for the `until` filter, for instance `$(expr $(date +%s) - 600)`.
