### ISSUE TITLE
rootlessport exited unexpectedly while container still running

### ISSUE THREAD

**Issue by cloud-yu** [containers/podman#19123]
### Issue Description

I run a container in rootless mode, expose port 18066 with `-p`.
It works as expected for about 3 or 4 days before I can't connect to port 18066.
`podman ps` shows container is still running, 
`ss -anop | grep 18066`  --- no result, no process is listening 18066
`ps axuf | grep rootlessport` can't find `rootlessport` process. 

**Seems `rootlessport` exited while container still running**
 I can't found any logs about rootlessport, and have no idea about this weird result.

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman run -d -p 18066:18066 --network podman_dual  -- cb2e104b1f18
2. let container keep running for a few days

### Describe the results you received

`rootlessport` exited while container still running.

### Describe the results you expected

`rootlessport` should keep running while container is running with a `-p` parameter

### podman info output

```yaml
❯ podman version
Client:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.20.4
Git Commit:   9eef30051c83f62816a1772a743e5f1271b196d7-dirty
Built:        Sat May 27 06:19:54 2023
OS/Arch:      linux/amd64
❯ podman info
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.7-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: f633919178f6c8ee4fb41b848a056ec33f8d707d'
  cpuUtilization:
    idlePercent: 99.73
    systemPercent: 0.08
    userPercent: 0.19
  cpus: 1
  databaseBackend: boltdb
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: hd.LA
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.4.1-arch2-1
  linkmode: dynamic
  logDriver: journald
  memFree: 72695808
  memTotal: 1012715520
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.8.5-1
    path: /usr/bin/crun
    version: |-
      crun version 1.8.5
      commit: b6f80f766c9a89eb7b1440c0a70ab287434b17ed
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.2.0-1
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 443019264
  swapTotal: 505933824
  uptime: 12h 2m 23.00s (Approximately 0.50 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: ${HOME}/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: ${HOME}/.local/share/containers/storage
  graphRootAllocated: 26627538944
  graphRootUsed: 17332678656
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: ${HOME}/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.1
  Built: 1685139594
  BuiltTime: Sat May 27 06:19:54 2023
  GitCommit: 9eef30051c83f62816a1772a743e5f1271b196d7-dirty
  GoVersion: go1.20.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
Something is killing the process or the process itself is crashing or something. Do you only run the command from the cli? Systemd will kill processes on logout but that should include the contianer (https://github.com/containers/podman/blob/main/troubleshooting.md#17-rootless-containers-exit-once-the-user-session-exits)
Is the slirp4netns process for the container still running?

Can you strace the process until it fails the next time?

**Comment by cloud-yu** [comment]
> Something is killing the process or the process itself is crashing or something. Do you only run the command from the cli? Systemd will kill processes on logout but that should include the contianer (https://github.com/containers/podman/blob/main/troubleshooting.md#17-rootless-containers-exit-once-the-user-session-exits) Is the slirp4netns process for the container still running?
> 
> Can you strace the process until it fails the next time?
- Yes, slirp4netns is stilling running. and enable-linger is done.

- I run `strace -t -i -f -p xxx -o podman.log` in tmux , till now, it has been five days, `rootlessport` is still running, maybe I should run strace in backgroud ?

**Comment by cloud-yu** [comment]
I can't reproduce this after update my OS, container keep running for about two weeks, and rootlessport still running.
close this issue
