### ISSUE TITLE
podman image policy docker-daemon transport

### ISSUE THREAD

**Issue by tomasdedic** [containers/podman#19128]
### Issue Description

using **policy.json** like 
`
{
  "default": [
    {
      "type": "reject"
    }
  ],
  "transports": {
    "docker": {
      "registry.aquasec.com": [
        {
          "type": "insecureAcceptAnything"
        }
      ],
      "quay.io": [
        {
          "type": "insecureAcceptAnything"
        }
      ],
      "mcr.microsoft.com": [
        {
          "type": "insecureAcceptAnything"
        }
      ]
    },
    "docker-daemon": {
      "": [
        {
          "type": "insecureAcceptAnything"
        }
      ]
    }
  }
}
`
when I build a container and use aquascan with provisioned podman socket for API

`
docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp registry.aquasec.com/scanner:2302.13.13 scan --local testimage:0.1.212 --no-verify 
`
(/var/run/docker.sock is symlink to /run/user/1001/podman/podman.sock) 

_unable to get uncompressed layer sha256:f5bb4f853c84f6579d86f72de5f1d43fc8866443d9a027e2106e3755acefd61c: failed to get the layer (sha256:f5bb4f853c84f6579d86f72de5f1d43fc8866443d9a027e2106e3755acefd61c): unable to populate: unable to open: unable to export the image: 
Error response from daemon: Source image rejected: Running image containers-storage:[overlay@/home/AzDevOps/.local/share/containers/storage+/tmp/containers-user-1001/containers]@f26ca2ef7f93332030eed7122c79c1d59bc60dcb1b237da84a11e489987ebe04 is rejected by policy._
  
**With policy.json set to default** like:
`
   {
          "default": [ { "type": "insecureAcceptAnything" } ]
    }
`
**everything is working fine.**

### Steps to reproduce the issue

Steps to reproduce the issue
1. enable policy
2. run container with provisioned podman socket and run an already present container over API

### Describe the results you received

Layer usage is blocked by policy:

unable to get uncompressed layer sha256:f5bb4f853c84f6579d86f72de5f1d43fc8866443d9a027e2106e3755acefd61c: failed to get the layer (sha256:f5bb4f853c84f6579d86f72de5f1d43fc8866443d9a027e2106e3755acefd61c): unable to populate: unable to open: unable to export the image: Error response from daemon: Source image rejected: Running image containers-storage:[overlay@/home/AzDevOps/.local/share/containers/storage+/tmp/containers-user-1001/containers]@f26ca2ef7f93332030eed7122c79c1d59bc60dcb1b237da84a11e489987ebe04 is rejected by policy.

### Describe the results you expected

run as normal

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2:2.1.7-0ubuntu22.04+obs15.50_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 98.16
    systemPercent: 0.61
    userPercent: 1.23
  cpus: 4
  databaseBackend: boltdb
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: C1-PLT-DEV-OPS-rst-vmss00000P
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.15.0-1041-azure
  linkmode: dynamic
  logDriver: journald
  memFree: 13892984832
  memTotal: 16767574016
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun_101:1.8.4-0ubuntu22.04+obs55.14_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.4
      commit: 5a8fa99a5e41facba2eda4af12fa26313918805b
      rundir: /run/user/1001/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.2.0-0ubuntu22.04+obs10.87_amd64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 0h 13m 6.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: $HOME/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/AzDevOps/.local/share/containers/storage
  graphRootAllocated: 103865303040
  graphRootUsed: 25445507072
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 9
  runRoot: /tmp/containers-user-1001/containers
  transientStore: false
  volumePath: /home/AzDevOps/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.1
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.18.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

**Comment by vrothberg** [comment]
Thanks for reaching out, @tomasdedic.  Where (which path) did you configure the policy?  Can you pull from other registries than the aquasec one?

Cc: @mtrmac

**Comment by tomasdedic** [comment]
@vrothberg policy file is in /etc/containers/policy.json

I think this is not about pulling from registries
1. build image locally, in this example image tagged as testimage:0.1.212 
2. run aquscan image with podman socket mounted and run image testimage:0.1.212 over API
`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp registry.aquasec.com/scanner:2302.13.13 scan --local testimage:0.1.212 --no-verify`
4. getting error: _Source image rejected: Running image containers-storage:[overlay@/home/AzDevOps/.local/share/containers/storage+/tmp/containers-user-1001/containers]@f26ca2ef7f93332030eed7122c79c1d59bc60dcb1b237da84a11e489987ebe04 is rejected by policy._

When I disable policy` { "default": [ { "type": "insecureAcceptAnything" } ] }` everythink is working fine.
But to response to you question yes I can pull from: registry.aquasec.com, quay.io, mcr.microsoft.com

**Comment by vrothberg** [comment]
Thanks, @tomasdedic.

Does it work when running `podman` instead of `docker`?

**Comment by tomasdedic** [comment]
@vrothberg docker is alias to podman.

**Comment by vrothberg** [comment]
@tomasdedic you mentioned that the socket is aliased

> (/var/run/docker.sock is symlink to /run/user/1001/podman/podman.sock)

I interpreted it that the docker client is talking to the Podman socket.  That will  use different code paths than using `podman` directly.  If that is the case, please try with `podman` as well.

**Comment by tomasdedic** [comment]
@vrothberg there is no docker running only podman

**Comment by tomasdedic** [comment]
@vrothberg I have move forward, forget about aquascan it is only accompanying phenomenon. Problem is much simplier, with policy.json defined above and simple Dockerfile

`
podman build -f Dockerfile -t 'agr1/tst:1' --log-level debug
`
_Successfully tagged localhost/agr1/tst:1
DEBU[0017] printing final image id "00fa582fae7aeca1f4c85fda4c22e7f608314ad827b83941fda57dc7033c6c46"
00fa582fae7aeca1f4c85fda4c22e7f608314ad827b83941fda57dc7033c6c46_

`
podman build -f Dockerfile-multistage -t 'agr2/tst:1' --log-level debug
`

_DEBU[0000] Using blob info cache at /var/home/core/.local/share/containers/cache/blob-info-cache-v1.boltdb
DEBU[0000] IsRunningImageAllowed for image containers-storage:[overlay@/var/home/core/.local/share/containers/storage]@00fa582fae7aeca1f4c85fda4c22e7f608314ad827b83941fda57dc7033c6c46
DEBU[0000]  Using default policy section
DEBU[0000] Requirement 0: denied, done
Error: copying image "00fa582fae7aeca1f4c85fda4c22e7f608314ad827b83941fda57dc7033c6c46": Source image rejected: Running image containers-storage:[overlay@/var/home/core/.local/share/containers/storage+/run/user/501/containers]@00fa582fae7aeca1f4c85fda4c22e7f608314ad827b83941fda57dc7033c6c46 is rejected by policy.
DEBU[0000] Shutting down engines_

**It seems that with policy above we cannot use local cache, as the policy is very poorly described in the documentation it is possible that I have missed something**

**Comment by tomasdedic** [comment]
ok it seems that adding containers-storage transport works:
`
    "transports": {
        "containers-storage": {
            "": [
                {
                    "type": "insecureAcceptAnything"
                }
            ]
        },
`

`
podman build -f Dockerfile-multistage -t 'agr2/tst:1' --log-level debug
`

_DEBU[0000] Found image "agr2/tst:1" as "localhost/agr2/tst:1" in local containers storage
DEBU[0000] Found image "agr2/tst:1" as "localhost/agr2/tst:1" in local containers storage ([overlay@/var/home/core/.local/share/containers/storage+/run/user/501/containers]@00fa582fae7aeca1f4c85fda4c22e7f608314ad827b83941fda57dc7033c6c46)
DEBU[0000] exporting opaque data as blob "sha256:00fa582fae7aeca1f4c85fda4c22e7f608314ad827b83941fda57dc7033c6c46"
DEBU[0000] parsed reference into "[overlay@/var/home/core/.local/share/containers/storage+/run/user/501/containers]localhost/agr2/tst:1"
Successfully tagged localhost/agr2/tst:1
Successfully tagged localhost/agr1/tst:1
DEBU[0000] printing final image id "00fa582fae7aeca1f4c85fda4c22e7f608314ad827b83941fda57dc7033c6c46"
00fa582fae7aeca1f4c85fda4c22e7f608314ad827b83941fda57dc7033c6c46_
`
podman images
REPOSITORY                    TAG         IMAGE ID      CREATED         SIZE
localhost/agr2/tst            1           00fa582fae7a  13 minutes ago  75.2 MB
localhost/agr1/tst            1           00fa582fae7a  13 minutes ago  75.2 MB
`

**Comment by tomasdedic** [comment]
it seems that adding containers-storage transport works:
```json
    "transports": {
        "containers-storage": {
            "": [
                {
                    "type": "insecureAcceptAnything"
                }
            ]
        },
```

**Comment by vrothberg** [comment]
Nice catch, @tomasdedic.  I am glad you got it working!

**Comment by mtrmac** [comment]
Returning to this late, I’m afraid:

IIRC (and looking at libimage’s `PolicyAllowStorage` and copies of `storageAllowedPolicyScopes` in Buildah seems to confirm) that Buildah intends, at least for `commit` and `push`, to automatically override `policy.json`.

I’m not sure that we should _extend_ that too far (I recognize the pragmatic value of that override, but to a point…) but if a plain `podman build` fails, is that a bug in the code as currently intended? Or is it one of the operations that we did not intend to override?

---

In particular, if the “unable to export the image” refers to something like `podman save`, I’m not surprised that it fails with a restrictive policy.

I am a bit more surprised that `podman build` fails — AFAICS it’s a fairly thin wrapper against Buildah. (But it could still very well be the case that this is currently intended behavior.)

---

As far as a recommendation to users … yes, setting the policy for `containers-storage` to `insecureAcceptAnything` is a good idea on a local development box, to allow creating/exporting/… unsigned images. On other systems, e.g. on cluster nodes that are intended to only run images and do nothing else, the `reject` behavior could well be more appropriate.
