### ISSUE TITLE
Connect from podman container to host service

### ISSUE THREAD

**Issue by naymore** [containers/podman#19130]
### Feature request description

I need to connect to a service (e.g. REST API) on my windows workstation.
This is where podman desktop is running.

podman-engine is running inside WSL2 (Ubuntu).
I tried a lot of combinations of service hosting on ANY ip address instead of only 127.0.0.1 on the host combined with calls to `host.containers.internal` from inside the container. Connection refused. I also tried --net="host" but to no avail (on a side note: networking-tools:extra failed to stat because nginx tried to bind to port 80 - operation not permitted).

If Windows firewall is part of this problem I can instantly shoot myself as it is company managed. Security first, developer experience second. Is there something I need to do which Docker for windows maybe did in the background? Network? Routing?

```
bash-5.1# ip route
default via 10.0.2.2 dev tap0
10.0.2.0/24 dev tap0 proto kernel scope link src 10.0.2.100
```

I have no idea where this 10.0.2.0/24 network is coming from. It's not part of my WSL.

### Suggest potential solution

Documentation or FAQ entry how to make this work.

**Comment by vrothberg** [comment]
Thanks for reaching out, @naymore!

@n1hility PTAL

**Comment by baude** [comment]
is the host service listening on 10.0.2.1?

**Comment by rhatdan** [comment]
Since we never heard back, closing.
