### ISSUE TITLE
[Maybe, maybe not]: reduce exposure to registry flakes

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#19148]
`registry.k8s.io` was mostly down for parts of yesterday, leading to flakes in manifest-related tests:
```
Podman manifest
           [It] add w/ inspect
...
           Error: setting up to read manifest [...] in registry.k8s.io/pause: received unexpected HTTP status: 500 Internal Server Error
```
Reason: https://github.com/containers/podman/blob/b721f96f5b2f45bf21595cbb7eccdbc1b73f2120/test/e2e/manifest_test.go#L20-L28

Discussion: can we change those to a quay-based image? Not that quay is rock solid, of course, but when quay goes down all other tests will fail anyway. It's a one-basket vs many-baskets thing, which is impossible to get right. I'm looking for thoughts on whether/how we can reduce our exposure to flakes in so many different registries.

One further and interesting complication: all registries are pinged on setup, when caching images. I was surprised that out of all the failing jobs below, only one was in `setup`. I can't explain this.

One further factor to consider: do we have any guarantees that `pause:3.1` will never be removed/changed? `quay.io/libpod/*` is under our control, `k8s.io` is not.

* debian-12 : int podman debian-12 rootless host sqlite
  * PR #17831
    * [07-05 20:57](https://api.cirrus-ci.com/v1/artifact/task/6212869751046144/html/int-podman-debian-12-rootless-host-sqlite.log.html#t--Podman-manifest-add-w--inspect--1) in Podman manifest add w/ inspect
    * [07-05 19:49](https://api.cirrus-ci.com/v1/artifact/task/5069321085386752/html/int-podman-debian-12-rootless-host-sqlite.log.html#t--Podman-manifest-push-all--1) in Podman manifest push --all
    * [07-05 18:26](https://api.cirrus-ci.com/v1/artifact/task/5614167550328832/html/int-podman-debian-12-rootless-host-sqlite.log.html#t--Podman-manifest-push--1) in Podman manifest push
    * [07-05 18:26](https://api.cirrus-ci.com/v1/artifact/task/5614167550328832/html/int-podman-debian-12-rootless-host-sqlite.log.html#t--Podman-manifest-push-progress--1) in Podman manifest push progress
* debian-12 : int remote debian-12 root host sqlite [remote]
  * PR #17831
    * [07-05 18:53](https://api.cirrus-ci.com/v1/artifact/task/6599329968816128/html/int-remote-debian-12-root-host-sqlite.log.html#t--Podman-manifest-remove-not-found--1) in Podman manifest remove not-found
* fedora-36 : int remote fedora-36 root host boltdb [remote]
  * PR #19136
    * [07-05 15:20](https://api.cirrus-ci.com/v1/artifact/task/5034717272080384/html/int-remote-fedora-36-root-host-boltdb.log.html) in int remote fedora-36 root host boltdb: unknown failure
    * [07-05 14:30](https://api.cirrus-ci.com/v1/artifact/task/6742919902658560/html/int-remote-fedora-36-root-host-boltdb.log.html) in int remote fedora-36 root host boltdb: unknown failure
* fedora-37 : int podman fedora-37 rootless host boltdb
  * PR #19136
    * [07-05 14:29](https://api.cirrus-ci.com/v1/artifact/task/6206358228303872/html/int-podman-fedora-37-rootless-host-boltdb.log.html) in int podman fedora-37 rootless host boltdb: unknown failure
* fedora-37 : int podman fedora-37 rootless host sqlite
  * PR #17831
    * [07-05 20:59](https://api.cirrus-ci.com/v1/artifact/task/5868857013829632/html/int-podman-fedora-37-rootless-host-sqlite.log.html#t--Podman-manifest-push--1) in Podman manifest push
    * [07-05 19:53](https://api.cirrus-ci.com/v1/artifact/task/5302285144686592/html/int-podman-fedora-37-rootless-host-sqlite.log.html#t--Podman-manifest-push--1) in Podman manifest push
    * [07-05 18:31](https://api.cirrus-ci.com/v1/artifact/task/5051217596907520/html/int-podman-fedora-37-rootless-host-sqlite.log.html#t--Podman-manifest-add-with-new-version--1) in Podman manifest add with new version
* fedora-37 : int remote fedora-37 root host sqlite [remote]
  * PR #17831
    * [07-05 20:03](https://api.cirrus-ci.com/v1/artifact/task/4873905106583552/html/int-remote-fedora-37-root-host-sqlite.log.html#t--Podman-manifest-remove-not-found--1) in Podman manifest remove not-found
    * [07-05 18:39](https://api.cirrus-ci.com/v1/artifact/task/6036380015394816/html/int-remote-fedora-37-root-host-sqlite.log.html#t--Podman-manifest-add-all--1) in Podman manifest add --all
    * [07-05 18:39](https://api.cirrus-ci.com/v1/artifact/task/6036380015394816/html/int-remote-fedora-37-root-host-sqlite.log.html#t--Podman-manifest-add-os--1) in Podman manifest add --os
* fedora-38 : int podman fedora-38 root container sqlite
  * PR #17831
    * [07-05 20:58](https://api.cirrus-ci.com/v1/artifact/task/6325887520473088/html/int-podman-fedora-38-root-container-sqlite.log.html#t--Podman-manifest-add-w--inspect--1) in Podman manifest add w/ inspect
    * [07-05 19:51](https://api.cirrus-ci.com/v1/artifact/task/5408957838131200/html/int-podman-fedora-38-root-container-sqlite.log.html#t--Podman-manifest-push-rm-to-local-directory--1) in Podman manifest push --rm to local directory
    * [07-05 18:29](https://api.cirrus-ci.com/v1/artifact/task/4769742620196864/html/int-podman-fedora-38-root-container-sqlite.log.html#t--Podman-manifest-remove-digest--1) in Podman manifest remove digest
* fedora-38 : int podman fedora-38 root host sqlite
  * PR #17831
    * [07-05 18:30](https://api.cirrus-ci.com/v1/artifact/task/6669698712993792/html/int-podman-fedora-38-root-host-sqlite.log.html#t--Podman-manifest-add-w--inspect--1) in Podman manifest add w/ inspect
    * [07-05 18:30](https://api.cirrus-ci.com/v1/artifact/task/6669698712993792/html/int-podman-fedora-38-root-host-sqlite.log.html#t--Podman-manifest-push-rm-to-local-directory--1) in Podman manifest push --rm to local directory
* fedora-38 : int podman fedora-38 rootless host sqlite
  * PR #17831
    * [07-05 19:54](https://api.cirrus-ci.com/v1/artifact/task/5914309125996544/html/int-podman-fedora-38-rootless-host-sqlite.log.html#t--Podman-manifest-push-rm-to-local-directory--1) in Podman manifest push --rm to local directory
* fedora-38 : int remote fedora-38 root host sqlite [remote]
  * PR #17831
    * [07-05 18:37](https://api.cirrus-ci.com/v1/artifact/task/4910480108552192/html/int-remote-fedora-38-root-host-sqlite.log.html#t--Podman-manifest-add-with-new-version--1) in Podman manifest add with new version
    * [07-05 18:37](https://api.cirrus-ci.com/v1/artifact/task/4910480108552192/html/int-remote-fedora-38-root-host-sqlite.log.html#t--Podman-manifest-remove-not-found--1) in Podman manifest remove not-found

**Comment by Luap99** [comment]
I agree, sounds like a good idea to only depend our our own namespace for these images.

**Comment by rhatdan** [comment]
SGTM

**Comment by rhatdan** [comment]
@edsantiago did you ever go through with this change, or do you want someone else to do it?

**Comment by edsantiago** [comment]
I have a working fix, but it relies on `quay.io/libpod/testimage:00000004` which has every arch except ARM. (Plain ARM, that is. The image already has ARM64). I can:
1. submit this work as a PR, or
2. try to regenerate the `testimage` so it includes plain-ARM.

My gut feel is that the manifest test is good enough by testing two or three platforms; current tests do five, option (1) reduces that to four. Is anyone not OK with that?

**Comment by rhatdan** [comment]
SGTM
