### ISSUE TITLE
New podman pod remove API error message is less detailed

### ISSUE THREAD

**Issue by jelly** [containers/podman#19159]
### Issue Description

In 4.6.0-rc1 the `libpods/pod` DELETE endpoint's error message changed to:

![image](https://github.com/containers/podman/assets/67428/09887439-128b-42be-92bb-7b9da3b92dcf)

From:

![image](https://github.com/containers/podman/assets/67428/8dd91399-3241-451e-8ef2-c7ee13b38979)

The new error message does not include anything about it being unable delete running/paused containers.

### Steps to reproduce the issue

Steps to reproduce the issue
```
[root@fedora-testing-127-0-0-2-2201 ~]# podman pod ps
POD ID        NAME           STATUS      CREATED         INFRA ID      # OF CONTAINERS
64ec75433156  brave_solomon  Running     24 minutes ago  c168e97d7e68  2
[root@fedora-testing-127-0-0-2-2201 ~]# curl -X DELETE -s -g --no-buffer --unix-socket /run/podman/podman.sock 'http://localhost/v1.12/libpod/pods/64ec75433156'
{"cause":"removing pod containers","message":"not all containers could be removed from pod 64ec754331564082b0ccbf078268d701ad009a415ad1dfdaca64425cbe8d8821: removing pod containers","response":500}
```

### Describe the results you received

See above :)

### Describe the results you expected

I'm wondering if the error should inform that the container is running/paused so requires force to be removed.

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by vrothberg** [comment]
Thanks for reaching out, @jelly !  @mheon PTAL

**Comment by mheon** [comment]
The individual errors from the containers in the pod are now propagated via the API through the `RemovedCtrs` field in the returned JSON (https://github.com/containers/podman/blob/main/pkg/domain/entities/pods.go#L108), instead of being returned squished into a single error. The individual errors in `RemovedCtrs` will still say that "container X was running" or similar.

**Comment by jelly** [comment]
@mheon interesting, I don't see this yet with the 4.6.0-rc1, all I get from a pod delete call is:

 ```
 {"cause":"removing pod containers","message":"not all containers could be removed from pod 64ec754331564082b0ccbf078268d701ad009a415ad1dfdaca64425cbe8d8821: removing pod containers","response":500}
 ```

Or from our JavaScript:
```
{
  "status": 500,
  "reason": "Internal Server Error",
  "message": "not all containers could be removed from pod d7424b8f211e48c8da5a18e2bd5e386c6c0b5d3b65f6fae9792fd65b40c57e60: removing pod containers",
  "problem": null,
  "cause": "removing pod containers",
  "response": 500
}
```

**Comment by mheon** [comment]
Sounds like a bug, I’ll take a look and we can get this fixed for 4.6 final

**Comment by mheon** [comment]
Confirming I can reproduce, self-assigning.

**Comment by mheon** [comment]
#19188 to fix

**Comment by jelly** [comment]
@mheon Thanks, just tested on `podman` main and it seems to work as expected!
