### ISSUE TITLE
podman logs and podman exec not working when using systemd LogNamespace

### ISSUE THREAD

**Issue by kriansa** [containers/podman#19177]
### Issue Description

Creating a container and having it orchestrated by systemd won't work as expected if you edit the `.service` file to [include a `LogNamespace`](https://www.freedesktop.org/software/systemd/man/systemd-journald.service.html#Journal%20Namespaces). A LogNamespace allows us to separate logs from services and quickly viewing them by using `journalctl --namespace=` and is very useful if you have noisy containers that would quickly fill up journald storage.

In a scenario where you appended a `LogNamespace` to a service file, you will no longer be able to:

1. Execute `podman logs` on that container -- the output will be empty
2. Execute `podman exec` on that container if it also has `--user` set -- The command will fail with the message `Error: unable to find user XXX: no matching entries in passwd file`, unless you specify a UID instead, e.g.: `podman exec -tiu 0 mycontainer bash`
3. Have your container's healthcheck enabled if it has a `--user` set, as that will also fail under the same issue above (no matching entries in passwd file)

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman create --name mycontainer --rm -e MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1 --user=mysql --health-interval 10s --health-cmd "healthcheck.sh --innodb_initialized" docker.io/library/mariadb:10.11.4`
2. `cd /etc/systemd/system && podman generate systemd --new --files --name --container-prefix=ct mycontainer`
3. Edit the file `mycontainer.service` and append the line `LogNamespace=ct` right after the `[Service]` line
4. `podman rm mycontainer`  (just for cleanup)
5. `systemctl daemon-reload`
6. `systemctl start ct-mycontainer`

Now, for testing:
1. `podman logs mycontainer`  -- will be empty, although you can see logs with `journalctl --namespace=ct -efu ct-mycontainer`
2. `podman exec -ti mycontainer bash` -- will fail
3. `podman exec -ti -u root mycontainer bash` -- will also fail, unless you pass a `0` instead of `root`
4. `journalctl -f` will show failures when doing healthchecks, usually `unable to find user root: no matching entries in passwd file`

### Describe the results you received

Effective usage of `podman logs`, `podman exec` and health checks severely impacted, although there are workarounds.

### Describe the results you expected

Have them all working.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: 3c1e4548e778d692b2b7c2848d83708223a148b9'
  cpuUtilization:
    idlePercent: 98.97
    systemPercent: 0.32
    userPercent: 0.71
  cpus: 8
  databaseBackend: boltdb
  distribution:
    distribution: '"centos"'
    version: "9"
  eventLogger: journald
  hostname: na-hercules
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.0-333.el9.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 22251552768
  memTotal: 33341145088
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.5-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.5
      commit: b6f80f766c9a89eb7b1440c0a70ab287434b17ed
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.2.0-3.el9.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 0
  swapTotal: 0
  uptime: 29h 6m 2.00s (Approximately 1.21 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 107307073536
  graphRootUsed: 9251192832
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 5
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.5.1
  Built: 1686840794
  BuiltTime: Thu Jun 15 10:53:14 2023
  GitCommit: ""
  GoVersion: go1.20.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.1
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
I have not looked in the systemd code but the docs say:

> Internally, journal namespaces are implemented through Linux mount namespacing and over-mounting the directory that contains the relevant AF_UNIX sockets used for logging in the unit's mount namespace. Since mount namespaces are used this setting disconnects propagation of mounts from the unit's processes to the host, similarly to how ReadOnlyPaths= and similar settings describe above work. Journal namespaces may hence not be used for services that need to establish mount points on the host.

Podman has to manage mount points so this cannot work.
