### ISSUE TITLE
podman --remote top -eo pid,comm doesn't parse the columns parameter correctly

### ISSUE THREAD

**Issue by EvaristeGalois11** [containers/podman#19176]
### Issue Description

Hi, I'm trying to execute `podman --remote top -eo pid,comm` and for some reason it broke down with a weird message about `mm` not being a valid column.

> Error: executing ps(1) in the container: runtime failed with exit status: 1 and output: error: unknown user-defined format specifier "mm"  Usage:  ps [options]   Try 'ps --help <simple|list|output|threads|misc|all>'   or 'ps --help <s|l|o|t|m|a>'  for additional help text.  For more details see ps(1).

I'm using podman compiled from source because so I can make use of the fix #18983 and the error message is more clear, otherwise with podman 4.5.1 it's just a generic `Error: unexpected end of JSON input`.

Just to be clear this isn't the same problem of #19001 because I know for sure that `ps` is present inside the container, with just `-eo pid` or `-eo comm` everything works fine indeed. It's the comma that messes the parser it seems, but only in remote mode. Standard podman works fine.

I also tried compiling the patch from #19066 and it returns the same error but with a slightly different message. I don't know how stable it is as a pull request, but I thought it was worth a try.

> Error: executing ps(1): ps(1) failed with exit code 1: error: unknown user-defined format specifier "mm"
> 
> Usage:
>  ps [options]
> 
>  Try 'ps --help <simple|list|output|threads|misc|all>'
>   or 'ps --help <s|l|o|t|m|a>'
>  for additional help text.
> 
> For more details see ps(1).

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman run -d --name remote-top jenkins/jenkins` (I'm using this image just because I know that `ps` is already installed, you can also use a normal debian image but you need to install the `procps` package)
2. `systemctl --user start podman.socket` (if you don't have already the socket enable)
3. `podman --remote top remote-top -eo pid,comm`
4. `podman top remote-top -eo pid,comm`
5. `podman --remote top remote-top -eo pid`
6. `podman --remote top remote-top -eo comm`

### Describe the results you received

The 4, 5 and 6 steps all work fine, it's just the combination of the remote flag and the comma in the list of columns that is a problem in the 3 command.

### Describe the results you expected

That `podman --remote top remote-top -eo pid,comm` works without error just like the not remote counterpart.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.31.0
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon è contenuto in conmon 1:2.1.7-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: f633919178f6c8ee4fb41b848a056ec33f8d707d'
  cpuUtilization:
    idlePercent: 55.54
    systemPercent: 5.71
    userPercent: 38.75
  cpus: 8
  databaseBackend: boltdb
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  freeLocks: 2044
  hostname: thinkpad
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.4.2-arch1-1
  linkmode: dynamic
  logDriver: journald
  memFree: 1302781952
  memTotal: 16438267904
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: /usr/lib/podman/aardvark-dns è contenuto in aardvark-dns 1.7.0-1
      path: /usr/lib/podman/aardvark-dns
      version: aardvark-dns 1.7.0
    package: /usr/lib/podman/netavark è contenuto in netavark 1.7.0-1
    path: /usr/lib/podman/netavark
    version: netavark 1.7.0
  ociRuntime:
    name: crun
    package: /usr/bin/crun è contenuto in crun 1.8.5-1
    path: /usr/bin/crun
    version: |-
      crun version 1.8.5
      commit: b6f80f766c9a89eb7b1440c0a70ab287434b17ed
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns è contenuto in slirp4netns 1.2.0-1
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 4294746112
  swapTotal: 4294963200
  uptime: 23h 33m 43.00s (Approximately 0.96 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/claudio/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 1
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/claudio/.local/share/containers/storage
  graphRootAllocated: 201731903488
  graphRootUsed: 56462966784
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 20
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/claudio/.local/share/containers/storage/volumes
version:
  APIVersion: 4.7.0-dev
  Built: 1688933861
  BuiltTime: Sun Jul  9 22:17:41 2023
  GitCommit: 5d706eb0277fc5fd14710f9e4e0444c65da18fde-dirty
  GoVersion: go1.20.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.7.0-dev
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

**Comment by Luap99** [comment]
> I also tried compiling the patch from https://github.com/containers/podman/pull/19066 and it returns the same error but with a slightly different message. I don't know how stable it is as a pull request, but I thought it was worth a try.

Yeah that just exec ps from the host with teh same arguments so it should not change anything if you have the same ps in the container already.

This looks more like either podman-remote or the API server changes the arguments somwhow.
