### ISSUE TITLE
WARN[0000] SHELL is not supported for OCI image format, [/bin/bash -o pipefail -c] will be ignored. Must use `docker` format 

### ISSUE THREAD

**Issue by webmutation** [containers/podman#19235]
### Issue Description

Podman build throws this warning but my Dockerfile has no SHELL commands

### Steps to reproduce the issue

Steps to reproduce the issue
1. Use the followind Dockerfile
FROM docker.io/bitnami/apache:2.4
ENV PORT 8080
EXPOSE 8080
 
# Labeling based on https://github.com/opencontainers/image-spec/blob/master/annotations.md
LABEL org.opencontainers.image.title="someimage"

COPY /dist /opt/bitnami/apache/htdocs
# Configuration for httpd, can be oberwritten by ConfigMap
COPY /httpd.conf /opt/bitnami/apache/conf/httpd.conf
2. run podman build -p myimage:1.0.0 .
3. After COPY commands it throws the error

### Describe the results you received

Describe the results you received

WARN[0000] SHELL is not supported for OCI image format, [/bin/bash -o pipefail -c] will be ignored. Must use `docker` format 

### Describe the results you expected

Describe the results you expected

To build OCI compliant image.

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.

host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 16
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
`docker.io/bitnami/apache:2.4` contains a SHELL instruction so it will be ignored if you build your image with oci format.
use `podman build --format docker ...`
