### ISSUE TITLE
Podman push results in "Requesting bearer token: invalid status code from registry 400 (Bad Request)"

### ISSUE THREAD

**Issue by dan-chop-ris** [containers/podman#19247]
### Issue Description

When I try to use `podman` to push to an internal quay registry, I get an error 
`Requesting bearer token: invalid status code from registry 400 (Bad Request)`

### Steps to reproduce the issue

Steps to reproduce the issue
1.  On internal quay registry, create organization, and then create repository  (quay.MYSUBDOMAIN.MYDOMAIN.com/organization_name/repository_name)
2. In repository, create a robot with write permission to repository
3. Clone GitHub repository that contains a Dockerfile
4. Enter the following commands:
```
podman build . --file deploy/Dockerfile --tag id_f431c8b --build-arg RELEASE=f431c8b
podman login -u="quay_robot_username" -p="quay_robot_password" quay.MYSUBDOMAIN.MYDOMAIN.com/organization_name/repository_name
podman push id_f431c8b  quay.MYSUBDOMAIN.MYDOMAIN.com/organization_name/repository_name/id_f431c8b
```

### Describe the results you received

Getting image source signatures
Error: trying to reuse blob sha256:0c23ed2428e1ef41fdb571789f6968dd47c95135311b1c8bf56462c98581694b at destination: Requesting bearer token: invalid status code from registry 400 (Bad Request)

### Describe the results you expected

Getting image source signatures
Copying blob sha256: ...
 71.41 MB / 71.41 MB [======================================================] 9s
Copying blob sha256:...
 1.21 KB / 1.21 KB [========================================================] 0s
Copying config sha256:...
 3.01 KB / 3.01 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.27.3
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.4-1.module+el8.7.0+17824+66a0202b.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: 3af09f8ff9780bd806d2e2db2a8518250622d362'
  cpuUtilization:
    idlePercent: 97.77
    systemPercent: 0.64
    userPercent: 1.59
  cpus: 6
  distribution:
    distribution: '"rhel"'
    version: "8.7"
  eventLogger: file
  hostname: MYSERVERNAME
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 85000002
      size: 1
    - container_id: 1
      host_id: 65535
      size: 65537
    uidmap:
    - container_id: 0
      host_id: MYUID
      size: 1
    - container_id: 1
      host_id: 65535
      size: 65537
  kernel: 4.18.0-425.19.2.el8_7.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 4057305088
  memTotal: 16567517184
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.4-1.module+el8.7.0+17824+66a0202b.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.4
      spec: 1.0.2-dev
      go: go1.18.4
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/MYUID/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.module+el8.7.0+17824+66a0202b.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 4290506752
  swapTotal: 4294963200
  uptime: 189h 31m 16.00s (Approximately 7.88 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  quay.MYSUBDOMAIN.MYDOMAIN.com/repository/ris_application_services/etraining:
    Blocked: false
    Insecure: true
    Location: quay.MYSUBDOMAIN.MYDOMAIN.com/ris_application_services/etraining
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: quay.MYSUBDOMAIN.MYDOMAIN.com/repository/ris_application_services/etraining
    PullFromMirror: ""
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
  - quay.MYSUBDOMAIN.MYDOMAIN.com
store:
  configFile: /home/MYUSERNAME/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/MYUSERNAME/.local/share/containers/storage
  graphRootAllocated: 10726932480
  graphRootUsed: 7718678528
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 84
  runRoot: /run/user/MYUID/containers
  volumePath: /home/MYUSERNAME/.local/share/containers/storage/volumes
version:
  APIVersion: 4.2.0
  Built: 1673617532
  BuiltTime: Fri Jan 13 08:45:32 2023
  GitCommit: ""
  GoVersion: go1.18.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

RHEL8

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
Please test with the latest version. Does it only happens on push or also when you try to pull a private image?

cc @mtrmac @vrothberg


Also if you use RHEL it is recommended to go through the Red Hat support channels instead.

**Comment by vrothberg** [comment]
> Requesting bearer token: invalid status code from registry 400 (Bad Request)

Could be related to authentication.  Can you also try `podman push --creds` and specify the credentials directly on push?

**Comment by mtrmac** [comment]
Also `podman --log-level=debug push …` might be interesting.

Sadly none of that contains the full contents of the HTTP “bad request” response, so if that contains a more specific error message, we wouldn’t see it that way.

If you are the administrator of the registry, does the server-side log contain more details about the failure?

**Comment by dan-chop-ris** [comment]
@mtrmac @vrothberg @Luap99 

Here's the results of adding --log-level=debug and --creds after upgrading my podman version:

$ podman push  --creds "robot_username":"robot_password"   id_c2e0243  quay.subdomain.domain.edu/repository_name/repository_name/id_c2e0243  --log-level=debug
INFO[0000] podman filtering at log level debug
DEBU[0000] Called push.PersistentPreRunE(podman push --creds robot_username:robot_password id_c2e0243 quay.subdomain.domain.edu/repository_name/repository_name/id_c2e0243 --log-level=debug)
DEBU[0000] Using conmon: "/usr/bin/conmon"
DEBU[0000] Initializing boltdb state at /home/myusername/.local/share/containers/storage/libpod/bolt_state.db
DEBU[0000] Using graph driver overlay
DEBU[0000] Using graph root /home/myusername/.local/share/containers/storage
DEBU[0000] Using run root /run/user/myuid/containers
DEBU[0000] Using static dir /home/myusername/.local/share/containers/storage/libpod
DEBU[0000] Using tmp dir /run/user/myuid/libpod/tmp
DEBU[0000] Using volume path /home/myusername/.local/share/containers/storage/volumes
DEBU[0000] Using transient store: false
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] Cached value indicated that overlay is supported
DEBU[0000] Cached value indicated that overlay is supported
DEBU[0000] Cached value indicated that metacopy is not being used
DEBU[0000] Cached value indicated that native-diff is usable
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false
DEBU[0000] Initializing event backend file
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument
DEBU[0000] Configured OCI runtime ocijail initialization failed: no valid executable found for OCI runtime ocijail: invalid argument
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument
DEBU[0000] Configured OCI runtime youki initialization failed: no valid executable found for OCI runtime youki: invalid argument
DEBU[0000] Using OCI runtime "/usr/bin/runc"
INFO[0000] Setting parallel job count to 19
DEBU[0000] Looking up image "id_c2e0243" in local containers storage
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] }
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf"
DEBU[0000] Failed to decode keys ["registry.short-name-mode"] from "/etc/containers/registries.conf"
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/000-shortnames.conf"
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/001-rhel-shortnames.conf"
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/002-rhel-shortnames-overrides.conf"
DEBU[0000] Trying "localhost/id_c2e0243:latest" ...
DEBU[0000] parsed reference into "[overlay@/home/myusername/.local/share/containers/storage+/run/user/myuid/containers]@1d5ffc115d3d2b436d2c3cbbcf61462627a131e5752c676ad029ad7a67d8f7a0"
DEBU[0000] Found image "id_c2e0243" as "localhost/id_c2e0243:latest" in local containers storage
DEBU[0000] Found image "id_c2e0243" as "localhost/id_c2e0243:latest" in local containers storage ([overlay@/home/myusername/.local/share/containers/storage+/run/user/myuid/containers]@1d5ffc115d3d2b436d2c3cbbcf61462627a131e5752c676ad029ad7a67d8f7a0)
DEBU[0000] exporting opaque data as blob "sha256:1d5ffc115d3d2b436d2c3cbbcf61462627a131e5752c676ad029ad7a67d8f7a0"
DEBU[0000] Pushing image id_c2e0243 to quay.subdomain.domain.edu/repository_name/repository_name/id_c2e0243
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] }
DEBU[0000] Copying source image [overlay@/home/myusername/.local/share/containers/storage+/run/user/myuid/containers]@1d5ffc115d3d2b436d2c3cbbcf61462627a131e5752c676ad029ad7a67d8f7a0 to destination image //quay.subdomain.domain.edu/repository_name/repository_name/id_c2e0243:latest
DEBU[0000] Using registries.d directory /etc/containers/registries.d
DEBU[0000] Returning credentials for quay.subdomain.domain.edu/repository_name/repository_name/id_c2e0243 from DockerAuthConfig
DEBU[0000]  No signature storage configuration found for quay.subdomain.domain.edu/repository_name/repository_name/id_c2e0243:latest, using built-in default file:///home/myusername/.local/share/containers/sigstore
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/quay.subdomain.domain.edu
DEBU[0000] Using blob info cache at /home/myusername/.local/share/containers/cache/blob-info-cache-v1.boltdb
DEBU[0000] IsRunningImageAllowed for image containers-storage:[overlay@/home/myusername/.local/share/containers/storage]@1d5ffc115d3d2b436d2c3cbbcf61462627a131e5752c676ad029ad7a67d8f7a0
DEBU[0000]  Using transport "containers-storage" policy section ""
DEBU[0000]  Requirement 0: allowed
DEBU[0000] Overall: allowed
Getting image source signatures
DEBU[0000] Manifest has MIME type application/vnd.oci.image.manifest.v1+json, ordered candidate list [application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.oci.image.index.v1+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.docker.distribution.manifest.v1+json]
DEBU[0000] ... will first try using the original manifest unmodified
DEBU[0000] Checking if we can reuse blob sha256:a143064a5702ec0fe6a10ce5ac4cfa4da7eb541a2624b1e3d7e1aa55712eb097: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:a143064a5702ec0fe6a10ce5ac4cfa4da7eb541a2624b1e3d7e1aa55712eb097
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/
DEBU[0000] Checking if we can reuse blob sha256:0c104482fada097dbe88c3bece1202c7e6a6b1fcd2e72c454a1af12639082dc3: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:0c104482fada097dbe88c3bece1202c7e6a6b1fcd2e72c454a1af12639082dc3
DEBU[0000] Checking if we can reuse blob sha256:0c23ed2428e1ef41fdb571789f6968dd47c95135311b1c8bf56462c98581694b: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:0c23ed2428e1ef41fdb571789f6968dd47c95135311b1c8bf56462c98581694b
DEBU[0000] Checking if we can reuse blob sha256:32a54fe876873797d93264dc9c5e2b86ccf258eaf1cea39bfc2e47a3ccda3e4f: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:32a54fe876873797d93264dc9c5e2b86ccf258eaf1cea39bfc2e47a3ccda3e4f
DEBU[0000] Checking if we can reuse blob sha256:9bb4b2221f4d79e8947780d84e3b40909d8286e53ae768e7f2101c052936f0a1: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:9bb4b2221f4d79e8947780d84e3b40909d8286e53ae768e7f2101c052936f0a1
DEBU[0000] Checking if we can reuse blob sha256:4882d3bc0594e9683ff05cfb3a5f6ffd42fa9080ee9c3d7df8be2eb457191f69: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:4882d3bc0594e9683ff05cfb3a5f6ffd42fa9080ee9c3d7df8be2eb457191f69
DEBU[0000] Ping https://quay.subdomain.domain.edu/v2/ status 401
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] Checking if we can reuse blob sha256:9ef2b9d0ee597d9b1c096874ba9482d116e796c3e9c8014c4868964eb072461a: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:9ef2b9d0ee597d9b1c096874ba9482d116e796c3e9c8014c4868964eb072461a
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] Checking if we can reuse blob sha256:c065e499b738b5026271069e2f8382d9e20b643b792c1b99a65be09fa83169d4: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:c065e499b738b5026271069e2f8382d9e20b643b792c1b99a65be09fa83169d4
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] Checking if we can reuse blob sha256:af18f987866b81b23acad76673f082ebaa8152ae50556a7252fcc2f4b0159277: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:af18f987866b81b23acad76673f082ebaa8152ae50556a7252fcc2f4b0159277
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] Checking if we can reuse blob sha256:a583582a1c2d8a7a9c592089f38c0b8134e9ba35ec0b70bb834e0132e37b9eb9: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:a583582a1c2d8a7a9c592089f38c0b8134e9ba35ec0b70bb834e0132e37b9eb9
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] Checking if we can reuse blob sha256:6d66dd6f4750b31de69fda6a09f8803ffd6dcb88b272dcb6071558649589032d: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:6d66dd6f4750b31de69fda6a09f8803ffd6dcb88b272dcb6071558649589032d
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] Checking if we can reuse blob sha256:20d21df1a5be80a70d4773113540c31ad30b6787d8c717567b1f9f5e1ab6792d: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:20d21df1a5be80a70d4773113540c31ad30b6787d8c717567b1f9f5e1ab6792d
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] Checking if we can reuse blob sha256:e6dcb91b7d79cf704815bff946af35a142f2a249ec04a07087b54ea3517d1ff0: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:e6dcb91b7d79cf704815bff946af35a142f2a249ec04a07087b54ea3517d1ff0
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] Checking if we can reuse blob sha256:b002d04998893a0ab09d47445e49c18535af7db1d9a7a96a0f0ada8f2e2837da: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:b002d04998893a0ab09d47445e49c18535af7db1d9a7a96a0f0ada8f2e2837da
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] Checking if we can reuse blob sha256:8155559c6e9716898a4d9674e963d6cd1ca57386975f0e261cafc1b60bd3c956: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:8155559c6e9716898a4d9674e963d6cd1ca57386975f0e261cafc1b60bd3c956
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] Checking if we can reuse blob sha256:587e4d387966311a485364c2938ec762c046597e1c0f06ff5babd79731bdb211: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:587e4d387966311a485364c2938ec762c046597e1c0f06ff5babd79731bdb211
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] Checking if we can reuse blob sha256:1bf3a204909037b6e7eb00190f718a93086866c5291df99c66a729dcd0d2121e: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:1bf3a204909037b6e7eb00190f718a93086866c5291df99c66a729dcd0d2121e
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] Checking if we can reuse blob sha256:236af75f45b8918fb53eef7542a23726863b3faa3e4eae2d9e01c417eaf4447b: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:236af75f45b8918fb53eef7542a23726863b3faa3e4eae2d9e01c417eaf4447b
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] Checking if we can reuse blob sha256:2643d8972be2a1887c82a2303311a645c22894be14a9b8d1aade5225600165b6: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:2643d8972be2a1887c82a2303311a645c22894be14a9b8d1aade5225600165b6
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] Checking if we can reuse blob sha256:592408822eb6bcec4e0eaa2889023b412049fd221320f277f7deede105ae61d2: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:592408822eb6bcec4e0eaa2889023b412049fd221320f277f7deede105ae61d2
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] Checking if we can reuse blob sha256:5f29640952c88dd30478cc04334689a90a4f8a3426a626961e5c1301a1ef7ea7: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:5f29640952c88dd30478cc04334689a90a4f8a3426a626961e5c1301a1ef7ea7
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] Checking if we can reuse blob sha256:58bee8057838d1a562000e5b3bde8b8e66fce137651d800ee07284a8d11d2e47: general substitution = true, compression for MIME type "application/vnd.oci.image.layer.v1.tar" = true
DEBU[0000] Checking /v2/repository_name/repository_name/id_c2e0243/blobs/sha256:58bee8057838d1a562000e5b3bde8b8e66fce137651d800ee07284a8d11d2e47
DEBU[0000] GET https://quay.subdomain.domain.edu/v2/auth?account=repository_name%2Bgithub&scope=repository%3Arepository_name%2Frepository_name%2Fid_c2e0243%3Apull%2Cpush&service=quay.subdomain.domain.edu
DEBU[0000] Looking up image "id_c2e0243" in local containers storage
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] }
DEBU[0000] Trying "localhost/id_c2e0243:latest" ...
DEBU[0000] parsed reference into "[overlay@/home/myusername/.local/share/containers/storage+/run/user/myuid/containers]@1d5ffc115d3d2b436d2c3cbbcf61462627a131e5752c676ad029ad7a67d8f7a0"
DEBU[0000] Found image "id_c2e0243" as "localhost/id_c2e0243:latest" in local containers storage
Error: trying to reuse blob sha256:0c23ed2428e1ef41fdb571789f6968dd47c95135311b1c8bf56462c98581694b at destination: Requesting bearer token: invalid status code from registry 400 (Bad Request)
DEBU[0000] Shutting down engines
