### ISSUE TITLE
Volume option does fails with missing host directories

### ISSUE THREAD

**Issue by domdomegg** [containers/podman#19266]
### Issue Description

When running commands designed for docker using the `-v` option to attach volumes, Podman can fail where the directory does not yet exist on the host. Users will get the error:

```
Error: statfs /Users/username/path/to/volume/: no such file or directory
```

However, Docker will create the folder ([source](https://docs.docker.com/engine/reference/commandline/run/#volume)):

> ```
> docker run -v /doesnt/exist:/foo -w /foo -i -t ubuntu bash
>```
> When the host directory of a bind-mounted volume doesn’t exist, Docker automatically creates this directory on the host for you. In the example above, Docker creates the /doesnt/exist folder before starting your container.

Given that one of Podman's aims is to provide "Support for a Docker-compatible CLI interface", it'd feels like a bug that we don't match Docker's (reasonable) behaviour here of creating the volume folder if one does not exist and the user has permissions to create that folder. Supporting this would make the CLIs more compatible and therefore make it easier for people to use Podman in place of Docker.

### Steps to reproduce the issue

Run `podman run -v /doesnt/exist:/foo -w /foo -i -t ubuntu bash`

### Describe the results you received

Receive the error: `Error: statfs /doesnt/exist: no such file or directory`

### Describe the results you expected

As a Docker-compatible CLI, the directory `/doesnt/exist` is created and the container runs with the container folder `/foo` attached to the (new) host folder `/doesnt/exist`.

### podman info output

```yaml
host:
  arch: arm64
  buildahVersion: 1.30.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc38.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 96.84
    systemPercent: 1.84
    userPercent: 1.31
  cpus: 1
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: coreos
    version: "38"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.3.11-200.fc38.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 610271232
  memTotal: 2048483328
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.5-1.fc38.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.5
      commit: b6f80f766c9a89eb7b1440c0a70ab287434b17ed
      rundir: /run/user/501/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/501/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-12.fc38.aarch64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 12m 21.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 2941276160
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/501/containers
  transientStore: false
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.1
  Built: 1685123899
  BuiltTime: Fri May 26 18:58:19 2023
  GitCommit: ""
  GoVersion: go1.20.4
  Os: linux
  OsArch: linux/arm64
  Version: 4.5.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

**Comment by Luap99** [comment]
From the podman [docs](https://docs.podman.io/en/latest/markdown/podman-run.1.html#volume-v-source-volume-host-dir-container-dir-options):
> If the source does not exist, Podman returns an error. Users must pre-create the source files or directories.

We discussed this before and we really think this is bad behavior, https://github.com/containers/podman/issues/8513#issuecomment-735806403

also just from a quick search:
https://github.com/containers/podman/issues/9510
https://github.com/containers/podman/issues/6234
https://github.com/containers/podman/issues/10471
https://github.com/containers/podman/issues/14781

**Comment by domdomegg** [comment]
Thanks! I thought I had searched for existing issues, but maybe I did it on the wrong repository or with the wrong filters. My bad.

I think given the history of people running into this we can do better here - will leave comments in #6234 given that appears to be the earliest this was reported and better to have in one place.
