### ISSUE TITLE
Container log file is not exist

### ISSUE THREAD

**Issue by Gnyblast** [containers/podman#19292]
### Issue Description

I'm running a podman container in detached and rootless mode as follows:
```
  podman run -d \
    -v /podman/models-files:/root/models-files \
    -v /podman/api-tmp:/tmp \
    -v /podman/api-libs:/usr/local/lib \
    --name "${CONTAINER_NAME}" \
    -p 8000:8000 \
    localhost/api:latest
```

when I do `podman logs -f ${CONTAINER_NAME}` it's perfectly fine and I can see my container logs but I need these logs so I'll start monitoring and collecting errors from these logs. 

I checked following locations:
- `/home/<user>/.local/share/containers/storage/overlay-containers/<containerID>/userdata/` -> there is no `ctr.log`
- `/var/lib/containers/storage` -> not even exist since I didn't run any container in privileged mode

I also search whole server for `ctr.log`:
`find /* -name "ctr.log" -type f`

There is not results. It's not only for this container, all other containers don't seem to have log files anywhere in the server. They are running with  `-d` which is `detached` so I'm sure it's not the problem.

I also tried:
1. `podman logs -f <containerID>`
2. Then `ps aux | grep podman`
3. `pgrep -P <podman logs command pid>`
4. So I'd see if it uses some OS binaries to tail logs then I'd discover the logs path but no, it does not use any OS binary to do that and it does not reveal the path anyway. 

I'm wondering if this version of the podman is keeping logs with a different name, or keeping them in memory, or it's just a bug? 

We had other machines that was running in same version but log files was getting created.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create a container in detached and rootless mode
2. Check if `ctr.log` is created

### Describe the results you received

`ctr.log` is not created in the  `/home/<user>/.local/share/containers/storage/overlay-containers/<containerID>/userdata/`

### Describe the results you expected

`ctr.log` to be created in the  `/home/<user>/.local/share/containers/storage/overlay-containers/<containerID>/userdata/`

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.1.2, commit: '
  cpus: 48
  distribution:
    codename: focal
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: db-fra-2
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 4043
      size: 1
    - container_id: 1
      host_id: 755360
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 10003
      size: 1
    - container_id: 1
      host_id: 755360
      size: 65536
  kernel: 5.4.0-120-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 26850185216
  memTotal: 270362013696
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: ea1fe3938eefa14eb707f1d22adff4db670645d6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /tmp/podman-run-10003/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 31711637504
  swapTotal: 31999995904
  uptime: 9206h 15m 10.01s (Approximately 383.58 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/guney/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.9.0
        fuse-overlayfs: version 1.5
        FUSE library version 3.9.0
        using FUSE kernel interface version 7.31
  graphRoot: /home/guney/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 6
  runRoot: /tmp/podman-run-10003/containers
  volumePath: /home/guney/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 3.4.2
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by vrothberg** [comment]
Thanks for reaching out, @Gnyblast.

The `podman info` output shows `logDriver: journald` which means that `journald` is used a backend for the container logs.  Please refer to the [documentation](https://docs.podman.io/en/latest/markdown/podman-create.1.html#log-driver-driver) for other log drivers.

The description above suggests that you're attempting to read the logs from disk and podman-internal paths (e.g., `/home/<user>/.local/share/containers/storage/overlay-containers/<containerID>/userdata/ `).  Those _internal_ structures may not change in the foreseeable future but they are not supported and may change in the future.  It's better to rely on the output of `podman logs` or even using `journalctl` when using the `journald` driver.

**Comment by Gnyblast** [comment]
After I made the ticket and went over the `podman info` I saw that it uses `journald` as `logDriver`. My local uses `k8s-file` as `logDriver` and it creates `ctr.log` I think I need to switch the server to use `k8s-file` as `logDriver` as well.

**Comment by Gnyblast** [comment]
> Thanks for reaching out, @Gnyblast.
> 
> The `podman info` output shows `logDriver: journald` which means that `journald` is used a backend for the container logs. Please refer to the [documentation](https://docs.podman.io/en/latest/markdown/podman-create.1.html#log-driver-driver) for other log drivers.
> 
> The description above suggests that you're attempting to read the logs from disk and podman-internal paths (e.g., `/home/<user>/.local/share/containers/storage/overlay-containers/<containerID>/userdata/ `). Those _internal_ structures may not change in the foreseeable future but they are not supported and may change in the future. It's better to rely on the output of `podman logs` or even using `journalctl` when using the `journald` driver.

Yeah exactly the `journald` is the problem for me. Thanks.

**Comment by vrothberg** [comment]
You can use containers.conf to set these settings globally on the host.  The `man containers.conf` man page explains how to do that but feel free to reach out here if you any question.

**Comment by Gnyblast** [comment]
Thanks, I'm on it atm. I imagine I can also create `.config/containers.conf` for local users right?

**Comment by vrothberg** [comment]
> Thanks, I'm on it atm. I imagine I can also create `~/.config/containers.conf` for local users right?

`~/.config/containers/containers.conf` will work :+1:
