### ISSUE TITLE
Podman cannot read the default auth file when using the `sudo`

### ISSUE THREAD

**Issue by jianzhangbjz** [containers/podman#19307]
### Issue Description

When using `sudo`, podman failed to read the default auths.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Check the default auth, the image can be pulled successfully **without** the `sudo`
```console
[cloud-user@preserve-olm-env2 jian]$ sudo cat ${XDG_RUNTIME_DIR}/containers/auth.json |jq
{
  "quay.io": {
    "auth": "xxx"
  }
}

[cloud-user@preserve-olm-env2 jian]$ podman pull quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:cf9db3bcde9778f347a83564cfbc85a07e6592690184e33afbb077cd01e5103e
Trying to pull quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:cf9db3bcde9778f347a83564cfbc85a07e6592690184e33afbb077cd01e5103e...
...
fb9b68e7cfcac23a591fe0a5a3c9bfec267f1f2082fb3524af33587d295d645e
```
2. Pull it **with** the `sudo`

### Describe the results you received

Describe the results you received

### Describe the results you expected

Auth fails with `sudo`.
```console
[cloud-user@preserve-olm-env2 jian]$ sudo podman pull quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:cf9db3bcde9778f347a83564cfbc85a07e6592690184e33afbb077cd01e5103e
Trying to pull quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:cf9db3bcde9778f347a83564cfbc85a07e6592690184e33afbb077cd01e5103e...
Error: initializing source docker://quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:cf9db3bcde9778f347a83564cfbc85a07e6592690184e33afbb077cd01e5103e: reading manifest sha256:cf9db3bcde9778f347a83564cfbc85a07e6592690184e33afbb077cd01e5103e in quay.io/openshift-release-dev/ocp-v4.0-art-dev: unauthorized: access to the requested resource is not authorized
```

### podman info output

```yaml
[cloud-user@preserve-olm-env2 jian]$ podman version
Client:       Podman Engine
Version:      4.1.1
API Version:  4.1.1
Go Version:   go1.17.7
Built:        Mon Jul 11 22:56:53 2022
OS/Arch:      linux/amd64
[cloud-user@preserve-olm-env2 jian]$ podman info 
host:
  arch: amd64
  buildahVersion: 1.26.2
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.32-1.module+el8.5.0+13852+150547f7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.32, commit: 4b12bce835c3f8acc006a43620dd955a6a73bae0'
  cpuUtilization:
    idlePercent: 99.82
    systemPercent: 0.05
    userPercent: 0.14
  cpus: 8
  distribution:
    distribution: '"rhel"'
    version: "8.4"
  eventLogger: file
  hostname: preserve-olm-env2
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-287.el8.dt4.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 5056225280
  memTotal: 16600383488
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.0.3-1.module+el8.5.0+13556+7f055e70.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.3
      spec: 1.0.2-dev
      go: go1.16.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.5.0+12582+56d94c81.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 0
  swapTotal: 0
  uptime: 912h 9m 19.13s (Approximately 38.00 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/cloud-user/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/cloud-user/.local/share/containers/storage
  graphRootAllocated: 128731557888
  graphRootUsed: 58494676992
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 4
  runRoot: /run/user/1000/containers
  volumePath: /home/cloud-user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.1.1
  Built: 1657551413
  BuiltTime: Mon Jul 11 22:56:53 2022
  GitCommit: ""
  GoVersion: go1.17.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.1.1
[cloud-user@preserve-olm-env2 jian]$ rpm -q podman
podman-4.1.1-2.module+el8.6.0+15917+093ca6f8.x86_64
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
If you run it like this `sudo cat ${XDG_RUNTIME_DIR}/containers/auth.json |jq` then the user shell will expend the var before running sudo.
Try `sudo sh -c 'cat ${XDG_RUNTIME_DIR}/containers/auth.json |jq'` then you will see that this file does not exists for root.

Or just run `sudo podman pull --authfile ${XDG_RUNTIME_DIR}/containers/auth.json ...` to make it use the existing file.

```
$ sudo echo $XDG_RUNTIME_DIR 
/run/user/1000
$ sudo sh -c 'echo $XDG_RUNTIME_DIR' 
                       <<<---empty
```

**Comment by jianzhangbjz** [comment]
> Try sudo sh -c 'cat ${XDG_RUNTIME_DIR}/containers/auth.json |jq' then you will see that this file does not exists for root.

Yes, thanks! But, as I remember the Podman will read the `Docker` auth config if the `${XDG_RUNTIME_DIR}/containers/auth.json` doesn't exist, but it did not with the `sudo`, as follows, Docker auth did exist.
```console
[cloud-user@preserve-olm-env2 mirror-tmp]$ sudo sh -c 'cat ~/.docker/config.json |jq'
{
  "auths": {
...
```

> Or just run sudo podman pull --authfile ${XDG_RUNTIME_DIR}/containers/auth.json ... to make it use the existing file.

Yes, but it's really inconvenient. I have to specify the auth file via ``--authfile` every time. :(

**Comment by Luap99** [comment]
You can use `REGISTRY_AUTH_FILE` env instead of the option.

As for using `.docker/config.json` I don't know, I leave that for @mtrmac or @vrothberg to answer.

**Comment by mtrmac** [comment]
`sudo` changes `HOME` to root’s one, so I think does not point to the original users’ home directory either.

(The entire problem space of `su`/`sudo` and using (or overwriting!) configuration with the invoking users’ home directory is just problematic.)

---

I would suggest thinking about why you are mixing `sudo podman pull` with a non-`sudo` `login`, in the first place.

Each user account has its own set of credentials, and tools are designed to make _that_ easy to use (and, if anything, to make it _hard_ to accidentally share credentials across users).

In particular, if this is some kind of automated script, the right solution might be to use _neither_ users’ credentials; create a single-purpose file just for that script, and use `--authfile` with all Podman commands.

**Comment by jianzhangbjz** [comment]
Hi @mtrmac , thanks for your suggestions! I have to use the `sudo` for the normal user since issue #19438 . And, I'm curious why the `podman` cannot read the `~/.docker/config.json` when using `sudo`. As the above shows, it did in there.
```console
[cloud-user@preserve-olm-env2 mirror-tmp]$ sudo sh -c 'cat ~/.docker/config.json |jq'
{
  "auths": {
...
```

**Comment by mtrmac** [comment]
> And, I'm curious why the `podman` cannot read the `~/.docker/config.json` when using `sudo`.

`podman --log-level=debug pull …` should contain details about where the code was looking for credentials, and where they were found.

**Comment by rhatdan** [comment]
Since we never heard back, closing.
