### ISSUE TITLE
podman --remote version takes 5 seconds on ubuntu

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman#19317]
### Issue Description

Doing a simple `podman-remote version`, as often done to ping the daemon, is slow on Ubuntu but fast on Fedora.

It has gotten worse with later versions, so if it was a few seconds with Podman 3.4 it is now up to 5 seconds in 4.6...

### Steps to reproduce the issue

Steps to reproduce the issue
1. `systemctl --user start podman.socket`
2. `podman --remote version`
3.

### Describe the results you received

Describe the results you received

5 seconds delay

### Describe the results you expected

Describe the results you expected

0.1 seconds delay

### podman info output

```yaml
Built v4.6.0 from source, Ubuntu 20.04
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Ubuntu 20.04, no virtualization

### Additional information

Happens on Debian platforms, using dpkg.

**Comment by afbjorklund** [comment]
This is a "bug" (shortcoming) in containers/common, when using a debian platform:

* https://github.com/containers/common/pull/1578

Since version calls info, and it checks a _lot_ of different commands now, it adds up (0.5s overhead per dpkg call)

Installing the `dlocate` program brings the whole overhead down from 5 seconds to 0.5 seconds, which is "OK"

**Comment by afbjorklund** [comment]
Note: the `podman version` command doesn't check package versions, so it is still fast.

Calling `podman version` on Fedora and other redhat platforms is fast, because of rpm.

**Comment by rhatdan** [comment]
Interested in opening a PR to use dlocate?

**Comment by afbjorklund** [comment]
The dlocate updatedb is just a perl script (run from cron) that creates a text file, that can be used to grep...

It's not really a database, like the one that rpm uses, but it is "good enough". The dpkg-query is OK, as well.

If this is called a _lot_, it would be possible to cache them in podman.

But if it is 0.5s (or 0.1s), that should be good enough for casual usage.

**Comment by afbjorklund** [comment]
Merged in (totally unrelated) e596b17fbef0097f78f78f1f04122ee1b52449f3
