### ISSUE TITLE
Issue with ulimits memlock -1:-1

### ISSUE THREAD

**Issue by leolivier** [containers/podman#19319]
### Issue Description

As requested by @rhatdan in #6389, I open this issue about the following problem I encountered:

I used a docker compose file from gravitee.io to create a set of brand new containers (never created before)
When starting elasticsearch in rootless mode on RHEL 9.2, I got 
```
Error: crun: setrlimit `RLIMIT_MEMLOCK`: Operation not permitted: OCI permission denied
``` 
although I have a quite big limit on memlock
```
$ podman unshare ulimit -l
8192
```
Looking at the docker-compose file, it contains
```
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 65536
```
In that context (rootless), shouldn't it take the highest possible value (8192 in my case) for -1 ie unlimited (maybe with a warning) ? 

### Steps to reproduce the issue

Steps to reproduce the issue
1. Not being root, start a container with option '--ulimit memlock=-1:-1'
e.g. in my case
```
$ podman run --name=gio_apim_elasticsearch -d --label io.podman.compose.config-hash=123 --label io.podman.compose.project=gravitee --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=gravitee --label com.docker.compose.project.working_dir=/ad_users/olivier_levillain/gravitee --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=elasticsearch -e http.host=0.0.0.0 -e transport.host=0.0.0.0 -e xpack.security.enabled=false -e xpack.monitoring.enabled=false -e cluster.name=elasticsearch -e bootstrap.memory_lock=true -e discovery.type=single-node -e ES_JAVA_OPTS=-Xms512m -Xmx512m -v gravitee_data-elasticsearch:/usr/share/elasticsearch/data --net storage --network-alias elasticsearch --restart always --ulimit memlock=-1:-1 --ulimit nofile=65536 docker.elastic.co/elasticsearch/elasticsearch:8.8.1
```

### Describe the results you received

```
Error: crun: setrlimit `RLIMIT_MEMLOCK`: Operation not permitted: OCI permission denied
```

### Describe the results you expected

No error, maybe a warning saying unlimited is actually limited to $(podman unshare ulimit -l)

### podman info output

```yaml
Running latest podman on RHEL 9.2
No access to the server now to provide the podman version.
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Installed with `yum install` on RHEL 9

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rhatdan** [comment]
@mheon PTAL

**Comment by mheon** [comment]
So, for context, does setting a limit of 8192 manually (instead of -1) work?

**Comment by rhatdan** [comment]
I would think it sets the lolimit to hard limit, in rootless containers this might be prevented, so we might want to check the default. or do nothing.
