### ISSUE TITLE
/etc/hostname contains name of pod even for hostNetwork: true

### ISSUE THREAD

**Issue by christian-2** [containers/podman#19321]
### Issue Description

I have `podman kube play` starting a pod with `hostNetwork: true`. 

Inside the resulting container, I observe that `/etc/hosts` contains the name of the pod, not the `$(hostname)` of the host (as in `hostNetwork`). With Kubernetes, it would be the name of the node, where the pod is running' and with `podman run --network host ...` it would likewise be the name of the host, not the pod (since `hostNetwork: true`).

Is this a feature or a bug? It currently prevents me from porting a workload from Docker Compose v2.19.1 to Podman 4.3.1 (on Debian 12.1). In particular `hostname -f` fails with "hostname: Name or service not known" inside the container. 

### Steps to reproduce the issue

(see above)

### Describe the results you received

(see above)

### Describe the results you expected

(see above)

### podman info output

```yaml
(see above)
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional information

I have not tried this with the latest upstream release, because I am installing Podman from a Debian package. Debian 12.1 currently comes with Podman 4.3.1. I have checked Podman [release notes](https://github.com/containers/podman/blob/main/RELEASE_NOTES.md), though, and these do not suggest that the latest upstream release would behave differently.

#14015 appears similar, but it was fixed in Podman 4.1.0.

**Comment by christian-2** [comment]
I would appear to come down to whether [`infraOptions.Hostname = podSpec.PodSpecGen.PodBasicConfig.Hostname`](https://github.com/containers/podman/blob/67f03406877c1a0a2e81973329bed32837452bea/pkg/domain/infra/abi/play.go#L619) assigns a [non-default value](https://github.com/containers/podman/blob/67f03406877c1a0a2e81973329bed32837452bea/pkg/specgen/podspecgen.go#L17-L22) in that particular case.

**Comment by dubmarm** [comment]
Confirmed the issue for me today. I was expecting Podman to set the name according to hostname and not pod name.

**Comment by rhatdan** [comment]
Care to open a PR to fix?
