### ISSUE TITLE
Podman configured with `netavark` failing with "validating network configs invalid cni_plugin_dirs"

### ISSUE THREAD

**Issue by danishprakash** [containers/podman#19327]
### Issue Description

Podman on a fresh install with Netavark and Aardvark-dns on SUSE ALP exits with the following error
```
ERRO[0000] validating network configs invalid cni_plugin_dirs: /usr/libexec/cni
```
Despite netavark as the network backend.

I came across https://github.com/containers/podman/issues/15845, in particular, @Luap99's response on there which makes sense but I still have some questions.

> ...To do so we will check for cni configs and possible detect errors and warn about that.

Could we just warn in this case and not break the installation? That'd be more in line with this reasoning.

> Assuming you did not create the cni config and it was shipped by your distro I would say this is packing bug. At least since podman v3.2 there shouldn't be a default config shipped since podman will create it automatically.

We still ship `containers.conf` primarily due to certain configurations that pertain to the distribution so it wouldn't be ideal for us to _not_ ship or _stop_ shipping the containers.conf right away.

> On the first run we have to check if podman was used previously in which case we default to cni.

From what I can tell, I tried this on a fresh install with only Podman and Netavark/Aardvark-dns installed, not CNI but I seem to get an error in this case. Am I missing something here?

Lastly, might I suggest not erroring out while validating CNI related configuration attributes while Netavark has been set as the network backend?

### Steps to reproduce the issue

Steps to reproduce the issue
1. Run `podman` on SUSE ALP

### Describe the results you received

```
ERRO[0000] validating network configs invalid cni_plugin_dirs: /usr/libexec/cni
```

### Describe the results you expected

For Podman to have behaved normally

### podman info output

```yaml
Client:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.20.4
Built:        Fri Jul 29 05:30:00 2023
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

**Comment by Luap99** [comment]
This is not related to #15845, the reason this is failing is because you specify a cni_plugin_directory in your config which does not exists. That is why config validation fails and we error out in such case.

I don't know why this check exists but it is there for a very long time. In general the containers.conf parsing/validation is very inconsistent. Only some parts are checked early others will fail only if they are actually used. Thus I have no problem simply removing this check.

**Comment by danishprakash** [comment]
> the reason this is failing is because you specify a cni_plugin_directory in your config which does not exists. That is why config validation fails and we error out in such case.

Understood. But should it also take into account which backend is in use actively? Or is this because we check whether we want to fallback to cni or not.

> I don't know why this check exists but it is there for a very long time. In general the containers.conf parsing/validation is very inconsistent. Only some parts are checked early others will fail only if they are actually used. Thus I have no problem simply removing this check.

I can take a look at this once. Additionally, if not removing, can we turn this into a warning or if my above understanding is correct, ensure we don't do such checks for when netavark is in use?

**Comment by Luap99** [comment]
I would just drop it, the CNI code will blow up later anyway if it does not find its plugins.
There is really no need to validate this for every single podman command.

**Comment by rhatdan** [comment]
I agree remove the check.
