### ISSUE TITLE
Add 'pre-defined/reserved' internal hostnames

### ISSUE THREAD

**Issue by benoitf** [containers/podman#19361]
### Feature request description

Some containers are using some predefined docker hosts like `host.docker.internal` or `gateway.docker.internal`

Then, these containers are failing during their execution as these hosts don't exists

It seems that there is `host.containers.internal` and `gateway.containers.internal` https://github.com/containers/gvisor-tap-vsock/blob/049be485f9a50ecbc8fb1aed9a040ceeead4e864/cmd/gvproxy/main.go#L187-L194

but for compatibility with Docker I think it would be nice if  `host.docker.internal` and `gateway.docker.internal` were aliased to `host.containers.internal.` and `gateway.containers.internal`

### Suggest potential solution

Add alias from `host.docker.internal` to `host.containers.internal.` and `gateway.docker.internal` to `gateway.containers.internal`

### Have you considered any alternatives?

N/A

### Additional context

I found that while testing digma-ai app with Podman

https://github.com/search?q=org%3Adigma-ai+host.docker.internal&type=code

related docker documentation: https://docs.docker.com/desktop/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host

**Comment by rhatdan** [comment]
@Luap99 PTAL

**Comment by Luap99** [comment]
I don't know the history of why we choose this name over the docker one but I will try to dig it up.
In general I have no issues in adding the docker entry as well, however that would need to happen both in gvproxy for podman machines and the normal /etc/hosts handling in c/common for the local podman.

**Comment by rhatdan** [comment]
We wanted to have a name without the letters "docker" but it turns out some customers built this functionality into the container images.

**Comment by Luap99** [comment]
I mean adding the entry is simple and because it helps converting existing workloads depending on it I think we should just add them.

**Comment by Luap99** [comment]
will be added with https://github.com/containers/gvisor-tap-vsock/pull/251 and https://github.com/containers/common/pull/1592

**Comment by vrothberg** [comment]
@Luap99 I assume this is done, is it?

**Comment by Luap99** [comment]
Ah yes, code changes are merged.
I assume it will be part of podman 4.7 for the c/common side and it needs a new gvproxy release.
