### ISSUE TITLE
Container kill does not return 409 error code for stopped containers

### ISSUE THREAD

**Issue by lukasmrtvy** [containers/podman#19368]
### Issue Description

podman kill ( compat  / libpod )  does not return 409 error code  ( https://docs.docker.com/engine/api/v1.43/#tag/Container/operation/ContainerKill ) for stopped containers

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman -r run -d --name nginx nginx 
2. podman -r stop nginx
3. podman -r kill nginx

### Describe the results you received
```
{"cause":"container state improper","message":"can only kill running containers. 6830d229c01064f76b9de62b76b80492fe4d08136c7b459bc0de926b1581093f is in state exited: container state improper","response":500}
```

### Describe the results you expected

409 is returned 

### podman info output

```yaml
4.6.0
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

**Comment by vrothberg** [comment]
Thanks for reaching out, @lukasmrtvy !
