### ISSUE TITLE
Logic error and exception "Failed to parse the authentication scope from the given challenge" on multi scope responses

### ISSUE THREAD

**Issue by xrow** [containers/podman#19363]
### Issue Description

I am using podman with gitlab.com. My project is configured to push a copy of an oci container into a second repository via the feature https://docs.gitlab.com/ee/ci/jobs/ci_job_token.html#allow-access-to-your-project-with-a-job-token that will grant a token access to many projects. When doing a push to the second repo I get this error:

```
time="2023-07-25T21:43:35+02:00" level=error msg="Failed to parse the authentication scope from the given challenge" challenge="{bearer map[error:insufficient_scope realm:https://gitlab.com/jwt/auth scope:repository:xrow-public/repository/php:pull,push repository:xrow-shared/s2i-php/php:pull service:container_registry]}" error="error parsing auth scope: 'repository:xrow-public/repository/php:pull,push repository:xrow-shared/s2i-php/php:pull'" scope="repository:xrow-public/repository/php:pull,push repository:xrow-shared/s2i-php/php:pull"
Error: writing blob: initiating layer upload to /v2/xrow-public/repository/php/blobs/uploads/ in registry.gitlab.com: requested access to the resource is denied
```

At first glance I though shit a permission error at my end. But it looks to me that podman can handle permission responses having multiple scopes. Here is why:

In [code](https://github.com/containers/podman/blob/main/vendor/github.com/containers/image/v5/docker/docker_client.go#L498C27-L498C41) there is a test for the format of a scope via function [parseAuthScope](https://github.com/containers/image/blob/main/docker/wwwauthenticate.go#L75) which will work if you scope is "repository:xrow-public/repository/php:pull,push", but not if your scope is like "repository:xrow-public/repository/php:pull,push repository:xrow-shared/s2i-php/php:pull". It is missing the functionality to split the scope via " " if multiple scopes are present. 

Please tell me if I am correct or not.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create 2 projects in gitlab
2. Grant the 1 project access in the second project via https://docs.gitlab.com/ee/ci/jobs/ci_job_token.html#allow-access-to-your-project-with-a-job-token
3. run CICD in the first project to create a container, push it to repo of project 1 and then into repo of project 2
4. You shall now get the error.

### Describe the results you received

```
time="2023-07-25T21:43:35+02:00" level=error msg="Failed to parse the authentication scope from the given challenge" challenge="{bearer map[error:insufficient_scope realm:https://gitlab.com/jwt/auth scope:repository:xrow-public/repository/php:pull,push repository:xrow-shared/s2i-php/php:pull service:container_registry]}" error="error parsing auth scope: 'repository:xrow-public/repository/php:pull,push repository:xrow-shared/s2i-php/php:pull'" scope="repository:xrow-public/repository/php:pull,push repository:xrow-shared/s2i-php/php:pull"
Error: writing blob: initiating layer upload to /v2/xrow-public/repository/php/blobs/uploads/ in registry.gitlab.com: requested access to the resource is denied
```

### Describe the results you expected

No such error as Failed to parse the authentication scope from the given challenge

### podman info output

```yaml
The version doesn`t matter.
```

### Podman in a container

Yes

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

**Comment by xrow** [comment]
I just noticed. Please be aware of the scope "service:container_registry" in my response. This will also trigger an error since you will not find 3 times a ":".

**Comment by Luap99** [comment]
@mtrmac PTAL

**Comment by mtrmac** [comment]
Please compare https://github.com/containers/image/issues/1972 / https://gitlab.com/gitlab-org/gitlab/-/issues/414402 ; the token GitLab token semantics might not be exactly what you expect.

---

If that doesn’t help, please capture a full log with `--log-level=debug`. You’re right that “Failed to parse the authentication scope” reports that the scope can’t be parsed, and that the code really can’t do that, but that happens on a _fallback path_; just from that one line it’s not obvious that the implementation of that fallback path is relevant (e.g. if the credentials just don’t have permissions, that fallback path parsing the data correctly could fail all the same).

**Comment by rhatdan** [comment]
Since we never heard back on this issue, closing.
