### ISSUE TITLE
podman system connection clobbers /etc/containers/containers.conf

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#19379]
```console
# cat containers/containers.conf
[engine]
# events_logger = "file"     <---- this is a comment, not a root prompt

# podman system connection add foo tcp://localhost:12345
# cat containers/containers.conf
[containers]

[engine]
  active_service = "foo"
  [engine.service_destinations]
    [engine.service_destinations.foo]
      uri = "tcp://localhost:12345"

[machine]
....more added stuff...
```
`containers.conf(5)` reads:
>Container  engines like Podman & Buildah **read** containers.conf file

**read** (emphasis mine). Nowhere does it say 'write'. As a system administrator, I object to tools modifying my files in `/etc`.

**Comment by vrothberg** [comment]
@rhatdan, something to brainstorm.  Also see https://github.com/containers/common/pull/1566.

**Comment by Luap99** [comment]
Lets close this in favor of https://github.com/containers/common/issues/1515
