### ISSUE TITLE
SIGTERM is not handled by "podman run --rm"

### ISSUE THREAD

**Issue by 125priyank** [containers/podman#19395]
### Issue Description

I started a podman container with '--rm' flag so that its get deleted after stopping it. I am sending SIGTERM to the podman process so that the container get stopped and deleted afterwards.
```
[user@mock1201 ~]$ sudo podman run --rm -it nicolaka/netshoot bash
d334493ced90:~#
(container is not deleted)
```
```
[user@mock1201 ~]$ ps -aux | grep d334493ced90
root     2833277  0.0  0.0   8644  2144 ?        Ss   00:29   0:00 /usr/bin/conmon --api-version 1 -c d334493ced90f37a7c93c4cd366aa51f9c6ff1d259bbb8e928ca4ff4dafd7bbc -u d334493ced90f37a7c93c4cd366aa51f9c6ff1d259bbb8e928ca4ff4dafd7bbc -r /usr/bin/crun -b /var/lib/containers/storage/overlay-containers/d334493ced90f37a7c93c4cd366aa51f9c6ff1d259bbb8e928ca4ff4dafd7bbc/userdata -p /run/containers/storage/overlay-containers/d334493ced90f37a7c93c4cd366aa51f9c6ff1d259bbb8e928ca4ff4dafd7bbc/userdata/pidfile -n frosty_agnesi --exit-dir /run/libpod/exits --full-attach -s -l journald --log-level warning --runtime-arg --log-format=json --runtime-arg --log --runtime-arg=/run/containers/storage/overlay-containers/d334493ced90f37a7c93c4cd366aa51f9c6ff1d259bbb8e928ca4ff4dafd7bbc/userdata/oci-log -t --conmon-pidfile /run/containers/storage/overlay-containers/d334493ced90f37a7c93c4cd366aa51f9c6ff1d259bbb8e928ca4ff4dafd7bbc/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /var/lib/containers/storage --exit-command-arg --runroot --exit-command-arg /run/containers/storage --exit-command-arg --log-level --exit-command-arg warning --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /run/libpod --exit-command-arg --network-config-dir --exit-command-arg  --exit-command-arg --network-backend --exit-command-arg netavark --exit-command-arg --volumepath --exit-command-arg /var/lib/containers/storage/volumes --exit-command-arg --transient-store=false --exit-command-arg --runtime --exit-command-arg crun --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --storage-opt --exit-command-arg overlay.mountopt=nodev,metacopy=on --exit-command-arg --events-backend --exit-command-arg journald --exit-command-arg container --exit-command-arg cleanup --exit-command-arg --rm --exit-command-arg d334493ced90f37a7c93c4cd366aa51f9c6ff1d259bbb8e928ca4ff4dafd7bbc
[user@mock1201 ~]$ sudo kill -15 2833277

```

For a docker running host, docker handles SIGTERM and deletes the container
```
~ @mock336.sjc> docker run --rm -it nicolaka/netshoot bash
25bfbace6635:~# ~ @mock336.sjc>
(container is deleted)

~ @mock336.sjc> ps -aux | grep 25bfbace6635
root      4991  0.0  0.0 720176  8684 ?        Sl   03:02   0:00 /usr/bin/containerd-shim-runc-v2 -namespace moby -id 25bfbace6635f78a564d0ac76c0bab96b116c5dc06c2f8374e751165138e99b3 -address /run/containerd/containerd.sock
~ @mock336.sjc> sudo kill -15 4991
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. create a container using `sudo podman run --rm -it nicolaka/netshoot bash`
2. send SIGTERM to the running podman container process `sudo kill -15 <PID>`

### Describe the results you received

The container is not deleted.

### Describe the results you expected

The container should get deleted after receiving SIGTERM.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-1.el9_2.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: fab2fef7227d2dc16478d29f1185953f81451702'
  cpuUtilization:
    idlePercent: 99.89
    systemPercent: 0.04
    userPercent: 0.08
  cpus: 96
  distribution:
    distribution: '"almalinux"'
    version: "9.2"
  eventLogger: journald
  hostname: mock1201.sjc.aristanetworks.com
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.62-32538884.priyankkernelCompat0.el7.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 520196853760
  memTotal: 540646731776
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.4-1.el9_2.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.4
      commit: 5a8fa99a5e41facba2eda4af12fa26313918805b
      rundir: /run/user/10000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.2.0-3.el9.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 0
  swapTotal: 0
  uptime: 315h 29m 17.00s (Approximately 13.12 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 5714156118016
  graphRootUsed: 28770897920
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 24
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.4.1
  Built: 1683706293
  BuiltTime: Wed May 10 01:11:33 2023
  GitCommit: ""
  GoVersion: go1.19.6
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.1
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

**Comment by rhatdan** [comment]
@mheon PTAL

This should be handled via the conmon command.  Is conmon still running when you see the container with podman ps?

**Comment by mheon** [comment]
We're proxying the signal through to the container via sig-proxy, so the Bash in the container is getting SIGTERM. In my testing, Bash is ignoring SIGTERM entirely and not exiting, so the container (and Podman) keep running. If I actually stop the container (sent SIGKILL directly to the container process - Podman can't catch it so we can't proxy it) the container stops and is then removed, as normal. Docker must be stopping the container directly instead of proxying the SIGTERM. Need further testing to identify exactly what they're doing.

**Comment by mheon** [comment]
I don't see any special handling in Docker's sig-proxy implementation. It's basically identical to ours - forward all signals to the container, save a few reserved ones (SIGPIPE, SIGCHLD, SIGURG)

**Comment by mheon** [comment]
Wait a second. You're sending a SIGKILL to *conmon*, not Podman.

Conmon is ignoring SIGTERM entirely, which seems correct. We cannot monitor the container without Conmon, so it will resist being stopped, and if forced down by anything less than SIGKILL it should immediately SIGKILL the container before exiting to ensure we don't lose track of a container process. Sending signals to Conmon is STRONGLY not recommended; it is an internal implementation detail of Podman. To interact with a container, please use either Podman's own CLI (`podman kill`), or send signals to the container process (or the `podman run` or `podman attach` process associated with the container). Sending signals to the container monitor process to attempt to shut a container down should not and will not work. While we do promise Docker compatibility, this does not extend to sending signals to our internal worker processes - Podman is daemonless, so we cannot handle the death of a container monitor in the same way containerd or Docker can. I don't think there's an argument to be made that this is an API, either - this is very much an internal implementation detail of Podman vs Docker.

Going to close given this.

**Comment by 125priyank** [comment]
The actual issue which we faced is
- we run a long-running service on a server inside a podman container and this container is started by systemd
- when reboot of the server happens the systemd sends SIGTERM to podman container to stop and delete the container 
- This SIGTERM is not handled by podman and the container remains on the server even after the reboot

**Comment by mheon** [comment]
@vrothberg PTAL - How are we handling this with Quadlet/`generate systemd`? Just pre-start `podman rm` on the name of the container?

**Comment by vrothberg** [comment]
@125priyank how are you running Podman in systemd?  `podman generate systemd` or Quadlet?  Are you editing the services in any form?

* when reboot of the server happens the systemd sends SIGTERM to podman container to stop and delete the container
* This SIGTERM is not handled by podman and the container remains on the server even after the reboot

This does not look like the systemd unit Podman runs in was generated via `podman generate systemd` or Quadlet.  Both let _podman_ terminate the container and remove it.

**Comment by 125priyank** [comment]
No, I did not know of this `podman generate systemd`. I was using a template similar to this (/usr/bin/docker is wrapper for sudo podman).
```
[Service]
User=user
ExecStart=/usr/bin/docker run --rm --name container service
ExecStop=/usr/bin/docker stop container
IOSchedulingClass=idle
KillMode=process
Restart=on-failure
```

Thanks for the info, I will try to use `podman generate systemd` and see if this issue is seen again.

**Comment by vrothberg** [comment]
Glad to be of help!

I suggest to use Quadlet directly, see https://www.redhat.com/sysadmin/quadlet-podman.  That's the "new" way of running Podman inside of systemd and _much_ easier to use.

**Comment by rhatdan** [comment]
I think we should start to hide or warn users against using podman generate systemd, and encourage them to use quadlet all of the time.

**Comment by vrothberg** [comment]
> I think we should start to hide or warn users against using podman generate systemd, and encourage them to use quadlet all of the time.

Good idea, now that Quadlet is GA.  I _think_ that a warning on STDERR is acceptable :+1:
