### ISSUE TITLE
Podman fails to pull images from docker.io if they aren't cached at mirror.gcr.io

### ISSUE THREAD

**Issue by shaunmayo** [containers/podman#19409]
### Issue Description

Podman gives an error when pulling an image from docker.io that doesn't exist on the mirror.gcr.io mirror.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman pull docker.io/fallenbagel/jellyseerr`

### Describe the results you received

`Error: initializing source docker://fallenbagel/jellyseerr:latest: reading manifest latest in mirror.gcr.io/fallenbagel/jellyseerr: manifest unknown: Failed to fetch "latest" from request "/v2/fallenbagel/jellyseerr/manifests/latest".`

### Describe the results you expected

I expect the image to start pulling either from the mirror or fallback to docker.io instead of receiving an error that isn't obvious for an idiot like to me resolve.

### podman info output

```yaml
host:
  arch: arm64
  buildahVersion: 1.30.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: app-containers/conmon-2.1.7
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.1.7, commit: v2.1.7'
  cpuUtilization:
    idlePercent: 72.11
    systemPercent: 8.49
    userPercent: 19.39
  cpus: 4
  databaseBackend: boltdb
  distribution:
    distribution: gentoo
    version: "2.13"
  eventLogger: file
  hostname: gentoo-pi
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.1.39-v8+
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 253890560
  memTotal: 8006238208
  networkBackend: cni
  ociRuntime:
    name: crun
    package: app-containers/crun-1.8.4
    path: /usr/bin/crun
    version: |-
      crun version 1.8.4
      commit: 5a8fa99a5e41facba2eda4af12fa26313918805b
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: app-containers/slirp4netns-1.2.0
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 2h 40m 10.00s (Approximately 0.08 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  docker.io:
    Blocked: false
    Insecure: false
    Location: mirror.gcr.io
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: docker.io
    PullFromMirror: ""
  docker.io/library:
    Blocked: false
    Insecure: false
    Location: quay.io/libpod
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: docker.io/library
    PullFromMirror: ""
  localhost:5000:
    Blocked: false
    Insecure: true
    Location: localhost:5000
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: localhost:5000
    PullFromMirror: ""
  search:
  - docker.io
  - quay.io
  - registry.fedoraproject.org
store:
  configFile: /home/shaun/.config/containers/storage.conf
  containerStore:
    number: 12
    paused: 0
    running: 7
    stopped: 5
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/shaun/.local/share/containers/storage
  graphRootAllocated: 124896559104
  graphRootUsed: 50494599168
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 9
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/shaun/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.0
  Built: 1688946570
  BuiltTime: Mon Jul 10 11:49:30 2023
  GitCommit: 75e3c12579d391b81d871fd1cded6cf0d043550a
  GoVersion: go1.20.5
  Os: linux
  OsArch: linux/arm64
  Version: 4.5.0
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

The issue is easily resolved by changing `/etc/containers/registries.conf` lines from

```
prefix="docker.io"
location="mirror.gcr.io"
```
to

```
prefix="docker.io"
location="docker.io"
```

I assume it's because the image isn't popular enough to be cached or isn't cached for another reason at the mirror.  But I would expect podman to fallback to docker.io in that case.  Unless it's a problem with the mirror not grabbing and caching the image?  Which does seem to be the expected behaviour if I am reading the link in the `/etc/containers/registries.conf` file right (https://cloud.google.com/container-registry/docs/pulling-cached-images).

**Comment by vrothberg** [comment]
@shaunmayo, thank you for reaching out.

I assume that you want to use `mirror.gcr.io` as a _mirror_.  You configured it as follows
```TOML
prefix="docker.io"
location="mirror.gcr.io"
```
This is not setting it as a mirror but entirely replacing `docker.io` with `mirror.gcr.io`.    Instead, configure it as follow:
```TOML
location="docker.io"
[[registry.mirror]]
location = "mirror.gcr.io"
```

Please refer to the [registries.conf man page ](https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md)for details.

**Comment by shaunmayo** [comment]
Thanks for the reply. 

I didn't make any changes to registries.conf.  Rather the default configuration didn't work and wanted to report this.

My bad for calling it a mirror in this context, I get it now haha.

**Comment by vrothberg** [comment]
> I didn't make any changes to registries.conf. Rather the default configuration didn't work and wanted to report this.

@shaunmayo, can you elaborate on that?  The default registries.conf on Fedora does not set any `[registry]`.  Somebody must have added the below lines to the file.

```TOML
prefix="docker.io"
location="mirror.gcr.io"
```

**Comment by shaunmayo** [comment]
I am using Gentoo but i assumed it was the same defaults as https://github.com/containers/podman/blob/main/test/registries.conf

**Comment by vrothberg** [comment]
Ah, OK. Thanks!

**Comment by vrothberg** [comment]
> https://github.com/containers/podman/blob/main/test/registries.conf

This registries.conf is only used in the upstream CI.   All requests to docker.io go to `mirror.gcr.io` instead.  We do this to avoid hitting rate limits on Docker Hub.

**Comment by shaunmayo** [comment]
That makes sense.  It was just a little frustrating working out why it wasn't able to pull the image on Gentoo without making any changes.  

Thank you.

**Comment by vrothberg** [comment]
I understand the frustration.  Please report the issue to the Gentoo maintainer for them to take a look.  There is nothing we can do upstream, unfortunately.

**Comment by shaunmayo** [comment]
FYI for anyone coming across this issue on Gentoo.  I have given additional information to the already existing issue here https://bugs.gentoo.org/849863

It seems the upstream examples are unsuitable for distribution as they are used for testing only in order to prevent hitting the docker hub rate limits.
