### ISSUE TITLE
Problem creating new podman machine configuration using windows 10 

### ISSUE THREAD

**Issue by kavya-karri** [containers/podman#19443]
### Bug description

We successfully created a new podman machine by selecting CPU = 2, Memory size = 5 GB, and Disk space = 250 GB. However, when we checked the configuration, we noticed that the values were different from the ones we had chosen.

Attached the screenshot for your reference. 
![podman creation](https://github.com/containers/podman/assets/81950811/0de94684-7168-4258-8274-4f79139b8145)

![Podman config](https://github.com/containers/podman-desktop/assets/81950811/c80ab4fc-f82e-4794-a405-4b0c7cf176ec)

Podman Version: 4.5.1 

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.1.0

### Steps to reproduce

We are in the process of creating a new configuration setup for a new podman machine.

**Comment by benoitf** [comment]
transferring the issue in podman repository where the podman machine is handled 

I think management of VMs is different on Windows when using WSL.

it will be different using Hyper-V

**Comment by Luap99** [comment]
yeah all these options are a NOP for WSL AFAIK, these limits can only be configured globally for all WSL distros, see https://learn.microsoft.com/en-us/windows/wsl/wsl-config#configuration-setting-for-wslconfig

We should definitely highlight that in the docs. For 1podman machine set` I see that we throw an explicit error when a user tries to change them.

**Comment by n1hility** [comment]
That's correct.The way WSL works is that esources are all shared globally across all WSL distributions (podman machine instances + any other WSL instance [e.g. stock Ubuntu instance]). This is mentioned in the man pages for podman machine set for example, that the settings are only relevant for Qemu backed machines, where they are per machine.

If you wish to restrict resources, the way to do that is a user specific `.wslconfig` file:[
](https://learn.microsoft.com/en-us/windows/wsl/wsl-config)

**Comment by rhatdan** [comment]
Seems that there is nothing Podman can do, so closing.
