### ISSUE TITLE
publish FCOS image of podman to easily try development versions of Podman in macOS podman machines

### ISSUE THREAD

**Issue by benoitf** [containers/podman#19448]
### Feature request description

There are Fedora images published at https://quay.io/repository/podman/upstream?tab=tags

but then it's not possible to use these images with `podman os apply` command on macOS

```
$ podman machine os apply quay.io/podman/upstream test

Pulling manifest: ostree-unverified-image:oci:/tmp/quayiopodmanupstream159226734
error: Preparing import: Fetching manifest: Parsing manifest layout: Target image does not have ostree.bootable label
Error: exit status 1

```

as it's not using os-tree layout.

### Suggest potential solution

Build images from https://github.com/coreos/layering-examples/tree/main/podman-next where it seems it's build from FCOS here

### Have you considered any alternatives?

any quay.io/ location would be fine

### Additional context

It would be great to have the rolling tag `latest` but also a git tag like `b6a52f1f` so you can apply from different commits (and not always the last one that can be totally broken)

git tags history could be deleted after like > 10-20 days

**Comment by ashley-cui** [comment]
Sounds like a good idea.

**Comment by baude** [comment]
it is something we could do ... I could do it as well.  The one problem that I have not figured out is how we do this using copr.  Using the built package would be superior to dropping a built binary into an image (I think).  But I would support and will volunteer if needed.

**Comment by baude** [comment]
I should also mention this can be done with existing podman commands on the fly ... like podman machine os apply (for issues not related to first boot)

**Comment by lsm5** [comment]
Packit people tell me this might be doable with a github action https://github.com/packit/wait-for-copr
