### ISSUE TITLE
`man podman-machine-list` table contains duplicate entries of `.LastUp`

### ISSUE THREAD

**Issue by eriksjolund** [containers/podman#19462]
### Issue Description

There are duplicate entries of `.LastUp` in the table

https://github.com/containers/podman/blob/dcb7f5e13002bff8ab3152e5fc389982db588dc0/docs/source/markdown/podman-machine-list.1.md.in#L42-L43

### Steps to reproduce the issue

Steps to reproduce the issue
1.
2.
3.

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by vrothberg** [comment]
Nice catch, @eriksjolund!  Time to open a PR?

**Comment by eriksjolund** [comment]
Yes, I'll fix it later this week.
