### ISSUE TITLE
Error validating CNI config file

### ISSUE THREAD

**Issue by mluhmann** [containers/podman#19463]
I am relating to the following issue:
https://github.com/containers/podman/issues/13396

I am not able to install any CNI related packages on my system, but all the comments are miss-leading and do not solving the real issue. It looks like Podman is still searching for these config files even if netavark is used. In my opinion that shouldn't be the case and the warnings are quite annoying.

`WARN[0000] Error validating CNI config file /etc/cni/net.d/deps_default.conflist: [failed to find plugin "bridge" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "portmap" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "firewall" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin] failed to find plugin "tuning" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin]]`

**Comment by Luap99** [comment]
Please provide the information as requested in the bug template.

In general this means your system is not configured correctly. You used podman before which means we keep using CNI to avoid breaking configs. If you then remove the cni plugins then of course it will not work.
`podman info --format {{.Host.NetworkBackend}}` will tell you what backend is used and it will likely show you CNI in that case.

If you want to migrate to netavark you should run `podman system reset` to start from a clean state.
