### ISSUE TITLE
podman machine start fails with "cp: cannot stat '/mnt/wsl/resolv.conf': No such file or directory" when user-mode-networking is enabled

### ISSUE THREAD

**Issue by eidottermihi** [containers/podman#19499]
### Issue Description

I was trying to use podman with the newly introduced `user-mode-networking`, but after successful initialization of the podman machine, `podman machine start` fails with

```
Starting machine "podman-machine-default"
Starting user-mode networking...
cp: cannot stat '/mnt/wsl/resolv.conf': No such file or directory
Error: error setting up user-mode networking: exit status 1
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman machine init --user-mode-networking`
2. `podman machine start`

### Describe the results you received

```
Starting machine "podman-machine-default"
Starting user-mode networking...
cp: cannot stat '/mnt/wsl/resolv.conf': No such file or directory
Error: error setting up user-mode networking: exit status 1
```

### Describe the results you expected

podman machine should start, with user-mode-networking enabled.

### podman info output

```yaml
fails because machine is not running

podman version: 4.6.0
OS: Windows 10 22H2 (Build 19045.3208)
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

-

### Additional information

-

**Comment by n1hility** [comment]
@eidottermihi We have a known issue were we aren't detecting older versions of WSL that user-mode is not compatible with and so you end up with this obscure error.

To fix it you need to update to the current WSL generation. Here are the steps:

1. Double check that you are running at least 21H1 although preferrably 22H2, then apply any outstanding windows updates.
2. Reboot, then run wsl --update (may also make you reboot) 
3. Restart podman machine

**Comment by eidottermihi** [comment]
Seems like my organization managed Windows (although `winver` is reporting "22H2") is missing some updates concering WSL, `wsl --update` is failing and `wsl --version` does not work ( https://github.com/MicrosoftDocs/WSL/issues/1649 ) - but I managed to update WSL by installing the direct distribution from https://github.com/microsoft/WSL/releases .

`wsl --version` then reports

```
WSL-Version: 1.3.15.0
Kernelversion: 5.15.90.4-1
WSLg-Version: 1.0.55
MSRDC-Version: 1.2.4419
Direct3D-Version: 1.608.2-61064218
DXCore-Version: 10.0.25880.1000-230602-1350.main
Windows-Version: 10.0.19045.3208
```

and then 

    podman machine init --user-mode-networking
    podman machine start

are working :) Thank you @n1hility for your help!
