### ISSUE TITLE
Only the last image described in a multistage containerfile is being built

### ISSUE THREAD

**Issue by vanmegenNiels** [containers/podman#19513]
### Issue Description

When building a multistage container file only the last image from the file is actually being built. 

### Steps to reproduce the issue

1. Create simple multistage [ContainerFile](https://github.com/containers/podman/files/12262306/ContainerFile.txt)
2. Build the images from this file with the following command: `podman build --file=$(pwd)/ContainerFile .`

### Describe the results you received

Only the last image described in the containerfile is being built this can be observed in the output of the [podman build command](https://github.com/containers/podman/files/12262118/podman_build_output.txt)

Only a single untagged image is being present after the build finishes as can be observed in the [podman images output](https://github.com/containers/podman/files/12262119/podman_images_output.txt)

### Describe the results you expected

I expected to see two FROM statements in the podman build uitput.
I expected to see two untagged images in my local container registry 

### podman info output

```yaml
host:
  arch: arm64
  buildahVersion: 1.30.0
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc38.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 93
    systemPercent: 6.19
    userPercent: 0.81
  cpus: 1
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: coreos
    version: "38"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 501
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.3.12-200.fc38.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 1660375040
  memTotal: 2048544768
  networkBackend: netavark
  networkBackendInfo:
    backend: ""
    dns: {}
  ociRuntime:
    name: crun
    package: crun-1.8.5-1.fc38.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.5
      commit: b6f80f766c9a89eb7b1440c0a70ab287434b17ed
      rundir: /run/user/501/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: true
    path: /run/user/501/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-12.fc38.aarch64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 3m 0.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 3834966016
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/user/501/containers
  transientStore: false
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.1
  Built: 1685123899
  BuiltTime: Fri May 26 19:58:19 2023
  GitCommit: ""
  GoVersion: go1.20.4
  Os: linux
  OsArch: linux/arm64
  Version: 4.5.1


podman --version
podman version 4.6.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Podman 4.6.0 installed with brew on macOS 13.4.1

### Additional information

I noticed this first with podman 4.2.0  and then replicated it with podman 4.6.0 on my personal macOS machine.

I did not have this issue in the previous podman version I used (2.1.1)

**Comment by rhatdan** [comment]
@flouthoc PTAL

**Comment by vanmegenNiels** [comment]
I also tried the above with podman 3.4.4 in ubuntu (22.04.5 LTS) and with that version the build functioned as expected.
After updating to podman 4.6.0 the problem with the multistage container build occurs.

**Comment by flouthoc** [comment]
Hi @vanmegenNiels , Only last stage is being build because, first stage is not used in target stage, it is useless for the build.
In order to still build the first stage, either use `podman build --skip-unused-stages=false ...` or modify containerfile to actually use first stage.

Solution is 

* Either build with 

```console
podman build  --skip-unused-stages=false --file=$(pwd)/ContainerFile .
```

or  Modify container file to use first stage as well in target stage

```Dockerfile
FROM alpine:latest as Stage1
RUN echo hey > world
ENV STAGE=1

FROM alpine:latest as Stage2
COPY --from=Stage1 world .
ENV STAGE=2
```

Feel free to re-open issue if something is unresolved.
