### ISSUE TITLE
DNS options taken from host may break host resolution in containers

### ISSUE THREAD

**Issue by jdelker** [containers/podman#19515]
### Issue Description

I've deployed a set of multiple pods with `podman kube play ...`, which use some inter-pod communications. As an example, consider the classic wordpress-database-setup, **but with both containers in a distinct pod**.
To be able to connect from pod A to pod B, the provided DNS service is used to resolve the particular host.
That's basically running fine, so I'm not going in more detail here.

However, I discovered that this resolution was highly unreliable, only return the host's IP with every other request. Meanwhile it has become clear why that is.

When creating the containers, podman obviously takes the `/etc/resolv.conf` from the local host, which is this
```
nameserver 10.10.0.2
nameserver 10.10.0.11
options rotate timeout:1
```
and just inserts it's own nameserver on top:
```
nameserver 10.89.0.1
nameserver 10.10.0.2
nameserver 10.10.0.11
options rotate timeout:1
```

Due to the option "rotate", the container is unable to properly resolve the other's pod name reliably, because it also uses external DNS hosts to resolve internal pod names.
Unfortunately, I can neither remove that option from the local host, nor did I find a way to tell podman (via `/etc/containers/containers.conf`) to drop the options altogether, when creating the container.

So, unless I've overseen the possibility to do so, I would consider this a bug ;)

### Steps to reproduce the issue

Steps to reproduce the issue
1. Define "options rotate" in your local `/etc/resolv.conf`
2. Create a new pod/container with `podman kube play ...` 
3. Enter the container and validate the content of `/etc/resolv.conf`

### Describe the results you received

podman blindly copies the problematic "rotate" DNS option, and no workaround seems possible to explicitly prevent the copy of the options

### Describe the results you expected

podman should either filter any "harmful" DNS options, or at least provide a way to override the options within `/etc/containers/containers.conf`.
As far as I understood, it currently only allows to **add** options.

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.6-1.module_el8.8.0+3470+252b1910.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.6, commit: 21c43a36b2ccb9799dfab0e8428837fca920fb45'
  cpuUtilization:
    idlePercent: 98.99
    systemPercent: 0.29
    userPercent: 0.72
  cpus: 2
  distribution:
    distribution: '"almalinux"'
    version: "8.8"
  eventLogger: file
  hostname: dr-idm-test.tf.twinsec.de
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-477.15.1.el8_8.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 2886909952
  memTotal: 3843649536
  networkBackend: netavark
  ociRuntime:
    name: runc
    package: runc-1.1.4-1.module_el8.7.0+3407+95aa0ca9.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.4
      spec: 1.0.2-dev
      go: go1.18.9
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_SYS_CHROOT,CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.module_el8.7.0+3407+95aa0ca9.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 2684350464
  swapTotal: 2684350464
  uptime: 0h 41m 31.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 0
    stopped: 4
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 23069986816
  graphRootUsed: 5588623360
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 3
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.4.1
  Built: 1688126783
  BuiltTime: Fri Jun 30 14:06:23 2023
  GitCommit: ""
  GoVersion: go1.19.10
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.1
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rhatdan** [comment]
@Luap99 PTAL

**Comment by Luap99** [comment]
Please retry with the latest version, I think this is the bug were we added the host resolvers by accident.
If dns is used it should only include the aardvark-dns ip and aardvark-dns will forward external requests.
