### ISSUE TITLE
Podman 4.6.0 OpenAPI Spec is missing properties

### ISSUE THREAD

**Issue by LucaDev** [containers/podman#19527]
### Issue Description

The OpenAPI specification for podman 4.6.0 is missing a lot of properties for definitions.

For example with SpecGenerator:
<img width="824" alt="SpecGenerator in 4.5 api spec" src="https://github.com/containers/podman/assets/5812715/a7059f76-99c4-4e49-8cf3-20b451fcbe6b">
4.5.1 (about 900 Lines of properties)
vs
<img width="748" alt="SpecGenerator in 4.6 api spec" src="https://github.com/containers/podman/assets/5812715/1d6bda34-b5ae-42e8-8d97-ba54a3e1e7fd">
4.6.0 (no properties at all)

### Steps to reproduce the issue

Have a look at:
https://storage.googleapis.com/libpod-master-releases/swagger-v4.6.0.yaml
vs
https://storage.googleapis.com/libpod-master-releases/swagger-v4.5.1.yaml

### Describe the results you received

The 4.6.0 spec is way smaller indicating a LOT of missing properties
<img width="440" alt="image" src="https://github.com/containers/podman/assets/5812715/92f41800-5b60-4bce-ab06-2d281263a80f">

### Describe the results you expected

Similar document sizes containing all definitions

### podman info output

```yaml
not applicable
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

**Comment by vrothberg** [comment]
Thanks for reaching out, @LucaDev !

@baude can you take a look?

**Comment by baude** [comment]
I looked for a bit, and it is not obvious to me.  Swagger is one of those things I never fully groaked.  I wonder if @jwhonce might know what the deal is?

**Comment by rhatdan** [comment]
@LucaDev Do you have any ideas on how to fix this?

**Comment by LucaDev** [comment]
I just stumbled upon it while trying to use the API. I'll have a look at it.

**Comment by Luap99** [comment]
Pretty sure the lastest swagger should look good again.
