### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by bwgjoseph** [containers/podman#19554]
### Bug description

note: realize this could be the same issue as https://github.com/containers/podman-desktop/issues/1173, but I have tried to provide more information and am not sure if it's really the same. Ok to close as duplicate if deem so.

---

I have saved an image from the internet machine and bring into an air-gapped machine to load it in.

I encounter the following error

```
Error: failed to connect: dial tcp [::1]:49675: connectex: No connection could be made because the target machine actively refused it.
```

### Operating system

Windows 10

### Version

0.12.0

### Steps to reproduce

```
// save image on internet machine
docker save busybox:latest > busybox.tar
```

```
// load image on air-gapped machine
podman load < busybox.tar
```

> Docker was installed but not running. I did start Docker afterwards, but the same error occur

Initially, I was thinking if this has something to do with `DOCKER_HOST`, so I followed the [guide](https://podman-desktop.io/docs/migrating-from-docker/using-the-docker_host-environment-variable) but when I ran the command

```bash
podman machine inspect
``` 

The output

```
[
     {
          "ConfigPath": {
               "Path": "C:\\Users\\bwgjoseph\\.config\\containers\\podman\\machine\\wsl\\podman-machine-default.json"
          },
          "ConnectionInfo": {
               "PodmanSocket": null
          },
          "Created": "2023-02-18T11:25:40.0285425-08:00",
          "Image": {
               "IgnitionFilePath": {
                    "Path": ""
               },
               "ImageStream": "custom",
               "ImagePath": {
                    "Path": "C:\\Users\\bwgjoseph\\.local\\share\\containers\\podman\\machine\\wsl\\podman-image-x64.tar.xz"
               }
          },
          "LastUp": "2023-02-18T13:43:18.4028289-08:00",
          "Name": "podman-machine-default",
          "Resources": {
               "CPUs": 2,
               "DiskSize": 550502400,
               "Memory": 325951488
          },
          "SSHConfig": {
               "IdentityPath": "C:\\Users\\bwgjoseph\\.ssh\\podman-machine-default",
               "Port": 49675,
               "RemoteUsername": "user"
          },
          "State": "running"
     }
]
```

### Relevant log output

```shell
> podman system connection list


Name                         URI                                                          Identity                                        Default
podman-machine-default       ssh://user@localhost:49675/run/user/1000/podman/podman.sock  C:\Users\bwgjoseph\.ssh\podman-machine-default  true
podman-machine-default-root  ssh://root@localhost:49675/run/podman/podman.sock            C:\Users\bwgjoseph\.ssh\podman-machine-default  false
```

> podman machine info

```
Host:
  Arch: amd64
  CurrentMachine: podman-machine-default
  DefaultMachine: podman-machine-default
  EventsDir: C:\Users\bwgjoseph\.local\share\containers\podman\podman
  MachineConfigDir: C:\Users\bwgjoseph\.config\containers\podman\machine\wsl
  MachineImageDir: C:\Users\bwgjoseph\.local\share\containers\podman\machine\wsl
  MachineState: Running
  NumberOfMachines: 1
  OS: windows
  VMType: wsl
Version:
  APIVersion: 4.4.1
  Built: 1675890486
  BuiltTime: Wed Feb  8 13:08:06 2023
  GitCommit: 34e8f3933242f2e566bbbbf343cf69b7d506c1cf
  GoVersion: go1.19.5
  Os: windows
  OsArch: windows/amd64
  Version: 4.4.1
```

### Additional context

- It looks a little related to
  - https://github.com/containers/podman/issues/17373
  - https://github.com/containers/podman/issues/15975
  - https://github.com/containers/podman-desktop/issues/1297
  - https://github.com/containers/podman-desktop/issues/1173

- I also tried rebooted my machine. This is running on a Virtual Machine if this helps

![image](https://user-images.githubusercontent.com/37484538/219843536-c8fc9cab-c925-40f7-9297-bfc8fdfca896.png)

**Comment by recodingLife** [comment]
For me the root cause was a DNS configuration issue in WSL, which sometimes arises after a Windows reboot.

To address this:

1. Open WSL terminal.
2. Edit the DNS configuration: sudo vim /etc/resolv.conf.
3. Set the nameserver to Google's DNS: nameserver 8.8.8.8.
4. Save and exit the file.

This change redirects DNS requests to Google's nameserver and allowed podman to connect again.

Hope it can help others...

**Comment by n1hility** [comment]
FYI to those impacted by the issue described by the OP: #19557 (just merged) should address this problem.

The new behavior will detect port conflicts on startup and automatically switch to a new available port, which will then be bindable by the wsl relay. You won't need to take any action other than updating to the new release when it's available.

**Comment by kid1412621** [comment]
after enabled `User mode networking`, this issue had been resolved.
![image](https://github.com/containers/podman/assets/26278054/d329a808-13c2-4af5-aa22-527cb24272a7)
