### ISSUE TITLE
podman stop <container> --time 0 resulted in "Error: given PIDs did not die within timeout"

### ISSUE THREAD

**Issue by nranudeep** [containers/podman#19572]
### Issue Description

We have a podman container running inside a Qemu instance (docker instance). 
podman stop <container> -time 0 on the Qemu resulted in 
Error: given PIDs did not die within timeout
making the container in accessible.

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman run -t --rm <image> /sbin/init <params>
2. podman stop <container> -time 0

Very rare to reproduce and when occurred makes container in accessible.

### Describe the results you received

Error: given PIDs did not die within timeout

### Describe the results you expected

<container name>

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - pids
  - debug
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.30+git0+e67bb4d9bb-r0.1.0.core2_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.31-dev, commit: e67bb4d9bb74424569b3b38943d13fe9e5dfcb20'
  cpus: 4
  distribution:
    distribution: enea
    version: "8.2"
  eventLogger: journald
  hostname: host
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.237-yocto-standard
  linkmode: dynamic
  logDriver: journald
  memFree: 1839624192
  memTotal: 4129574912
  ociRuntime:
    name: runc
    package: runc-opencontainers-1.0.3+git0+e0124d569c-r0.1.0.core2_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.3+dev
      commit: v1.0.3-2-ge0124d5-dirty
      spec: 1.0.2-dev
      go: go1.14.12
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-0.4.1-r0.0.core2_64
    version: |-
      slirp4netns version 0.4.1
      commit: unknown
  swapFree: 0
  swapTotal: 0
  uptime: 23m 59.68s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/shared/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  volumePath: /var/shared/containers/storage/volumes
version:
  APIVersion: 3.4.3-dev
  Built: 1687287347
  BuiltTime: Tue Jun 20 18:55:47 2023
  GitCommit: 72031783c5152cc715a8f1b6dc39bb5de8bfc3ca
  GoVersion: go1.14.12
  OsArch: linux/amd64
  Version: 3.4.3-dev
```

### Podman in a container

Yes

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Issue happens very rare and is very hard to reproduce. 
We do see it on 3.4.3 version we have inhouse.

**Comment by nranudeep1990** [comment]
Hi @rhatdan ,
Here is the full podman run command.. 
IMG_NAME points to an oci container built by yocto 

/usr/bin/podman run -t --network=host --rm --name $1 \
--hostname=$hostname \
--systemd=always \
-v /dev:/dev \
-v /var/run/dbus:/var/run/host-dbus \
-v /mnt:/mnt/host:rshared \
-v /run/podman/podman.sock:/run/podman/podman.sock \
--device=/dev/packet_injector:/dev/packet_injector \
--device=/dev/ppp:/dev/ppp:rw \
--shm-size=1g --privileged --cgroup-manager=cgroupfs \
--security-opt seccomp=unconfined \
$IMG_NAME /sbin/init root=/dev/vda rw highres=off \
mem=1024M ip=dhcp vga=0 uvesafb.mode_option=640x480-32 oprofile.timer=1 \
uvesafb.task_timeout=-1 FSS_CARD_ID=$FSS_CARD_ID \
$options \
systemdParams="" > /dev/null

Yes the image is properly setup to run with /sbin/init which starts systemd as PID 1 inside container.

The current version of linux we have can only support upto podman 3.4.3.

**Comment by vrothberg** [comment]
Please try with a more recent version of Podman.  Upstream we cannot support such an old version.

**Comment by nranudeep** [comment]
@vrothberg sure we will update the podman
Can you help us identify what scenarios we might run into these errors?

**Comment by vrothberg** [comment]
> Can you help us identify what scenarios we might run into these errors?

It's probably just a bug in `podman stop` when using -t0.  In that case you may just use `podman kill`.

**Comment by vrothberg** [comment]
I am going to close but we can continue the conversation.
