### ISSUE TITLE
cni plugin bridge failed: failed to allocate for range 0: requested IP address 10.88.0.101 is not available in range set 10.88.0.1-10.88.255.254

### ISSUE THREAD

**Issue by grisu48** [containers/podman#19583]
### Issue Description

Occasionally after an automatic reboot, a container with a static ip address fails to start with the error message

    cni plugin bridge failed: failed to allocate for range 0: requested IP address 10.88.0.101 is not available in range set 10.88.0.1-10.88.255.254

The container uses the default `podman` network and the `--network podman --ip 10.88.0.101` parameter. The issue occurs only sometimes, but we observed it now three times over the course of two weeks. There is no ip address conflict on the system AFAICS.

When the container fails to start, the ip address is not present in `/var/lib/cni/networks/podman`, nor can I see the IP address via `podman ps -a -q | xargs podman container inspect -f '{{.NetworkSettings.IPAddress}}'`.

We are running 3 containers on that system, and only the grafana container seems to be affected. I didn't observe the issue on the other two (`influxdb` and a custom application).

Running podman 4.6.0 on openSUSE MicroOS.

### Steps to reproduce the issue

No concrete reproducer identified. This happens sporadically after a system reboot (automatic transactional system update)

### Describe the results you received

* Container fails to start

### Describe the results you expected

* Container starts without issues

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.31.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.1.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: unknown'
  cpuUtilization:
    idlePercent: 98.99
    systemPercent: 0.33
    userPercent: 0.68
  cpus: 4
  databaseBackend: boltdb
  distribution:
    distribution: '"opensuse-microos"'
    version: "20230808"
  eventLogger: journald
  freeLocks: 2034
  hostname: publiccloud-ng.qa.suse.de
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.4.8-1-default
  linkmode: dynamic
  logDriver: journald
  memFree: 12515262464
  memTotal: 20659531776
  networkBackend: cni
  networkBackendInfo:
    backend: cni
    dns: {}
    package: |-
      cni-1.1.2-2.4.x86_64
      cni-plugins-1.1.1-2.4.x86_64
    path: /usr/libexec/cni
  ociRuntime:
    name: runc
    package: runc-1.1.8-1.1.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.8
      commit: v1.1.8-0-g82f18fe0e44a
      spec: 1.0.2-dev
      go: go1.20.5
      libseccomp: 2.5.4
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-1.3.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: unknown
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 5
      libseccomp: 2.5.4
  swapFree: 0
  swapTotal: 0
  uptime: 17h 37m 19.00s (Approximately 0.71 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.opensuse.org
  - registry.suse.com
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 3
    stopped: 0
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 42940215296
  graphRootUsed: 11731886080
  graphStatus:
    Build Version: Btrfs v6.3
    Library Version: "102"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 4
  runRoot: /var/run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.6.0
  Built: 1691020800
  BuiltTime: Thu Aug  3 00:00:00 2023
  GitCommit: ""
  GoVersion: go1.20.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.0
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

openSUSE MicroOS VM.

### Additional information

Sporadic issue after reboot. Happened three times over the course of the last two weeks and only with the grafana container.

Here is the systemd unit we use to start the grafana container:

```ini
[Unit]
Description=grafana podman container
Wants=network-online.target
After=network-online.target
RequiresMountsFor=%t/containers

[Service]
Environment=PODMAN_SYSTEMD_UNIT=%n
Restart=on-failure
TimeoutStopSec=70
ExecStartPre=/bin/rm -f %t/%n.ctr-id
ExecStart=/usr/bin/podman run --cidfile=%t/%n.ctr-id \
        --name grafana \
        --cgroups=no-conmon \
        --rm --sdnotify=conmon \
        --replace -d \
        -v /srv/grafana/grafana.ini:/etc/grafana/grafana.ini:Z \
        -v /srv/grafana/data:/var/lib/grafana:Z \
        -v /var/log/grafana:/var/log/grafana:Z \
        --read-only --tmpfs=/run --tmpfs=/tmp \
        --memory=1G \
        --network podman \
        --ip 10.88.0.101 \
        -p 3000:3000 \
        --label io.containers.autoupdate=image \
        docker.io/grafana/grafana-oss
ExecStop=/usr/bin/podman stop --ignore --cidfile=%t/%n.ctr-id
ExecStopPost=/usr/bin/podman rm -f --ignore --cidfile=%t/%n.ctr-id
Type=notify
NotifyAccess=all

[Install]
WantedBy=default.target
```

**Comment by Luap99** [comment]
Do your other containers also use `--ip` to set a static ip? It is possible that containers without static ip get this ip assigned, the static ip is only reserved while the container is running

**Comment by grisu48** [comment]
> Do your other containers also use `--ip` to set a static ip? It is possible that containers without static ip get this ip assigned, the static ip is only reserved while the container is running

All containers on this host have their own static `--ip` assigned and once they are running, they are ok.

**Comment by Luap99** [comment]
Normally a conflict should say request ip is already assigned to container but this error can also come from a conflict.

The only case where this error can happen is here https://github.com/containernetworking/plugins/blob/9d9ec6e3e18ea245b9cef0f8396e570247338d1f/plugins/ipam/host-local/backend/disk/backend.go#L65
which the triggers the error here: https://github.com/containernetworking/plugins/blob/9d9ec6e3e18ea245b9cef0f8396e570247338d1f/plugins/ipam/host-local/backend/allocator/allocator.go#L70

So at least following the code the only reason this can happen is when the ip file already exists under `/var/lib/cni/networks/podman`


So the first thing are you sure `/var/lib/cni/networks/podman` is empty when you boot,we have tmpfile config upstream to delete it automatically https://github.com/containers/podman/blob/c01ec25e6c98b9c8e56a18fb37751ccaea286d49/contrib/tmpfile/podman.conf#L8
Is this file installed on opensuse?

Then are you sure the container did not failed to start previously, i.e. if you check system unit logs are you sure this is the first start after the boot which fails and there was no other error messages logged?

**Comment by Luap99** [comment]
And my obligatory question: Can you try switching the system to netavark? I don't think such error should happen there and if it does I should be able to debug and fix it.

**Comment by grisu48** [comment]
> And my obligatory question: Can you try switching the system to netavark? I don't think such error should happen there and if it does I should be able to debug and fix it.

Nope, that's on that system not possible and I haven't found a reproducer to check it in a different VM.

If https://github.com/containernetworking/plugins/blob/9d9ec6e3e18ea245b9cef0f8396e570247338d1f/plugins/ipam/host-local/backend/allocator/allocator.go#L70 is the only place where that error message is produced, then I will look for potential conflicts. https://github.com/containers/podman/issues/19583#issuecomment-1672910512 gave me a good starting point.

I will report back once we find something, thnx for pointing us in the (hopefully) right direction. :slightly_smiling_face:

**Comment by grisu48** [comment]
We found a dangling auxiliary service, which spins up containers with no assigned IP address periodically. I'm confident that this was the culprit.

Thanks @Luap99 for insisting on checking for possible ip conflicts, that indeed helped. I'm closing the issue for now and will re-open if the issue reappears.

**Comment by grisu48** [comment]
Anyone who comes here later: This issue is likely caused by an IP address conflict. Check if you are having another container running with the same IP address.
