### ISSUE TITLE
Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64

### ISSUE THREAD

**Issue by xRomZak** [containers/podman#19610]
### Issue Description

Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Unknown Error

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman machine init --cpus 3 --memory 2000 --rootful
2. podman machine start

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
macos ventura 13.4.1
podman 4.6.1
qemu 8.0.4 (seems podman is broken after update to the latest qemu)
/podman/machine/qemu/cache/fedora-coreos-38.20230722.2.1-qemu.x86_64.qcow2.xz
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by RainbowHerbicides** [comment]
Same issue. Tried to init machine with different parameters and same result: `Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Unknown Error`
```
macos ventura 13.5
podman 4.6.1
qemu 8.0.4 
```

Removed manually emu with `brew uninstall  --ignore-dependencies qemu` and installed it back via `brew install qemu` seems to fix this problem

**Comment by xRomZak** [comment]
Seems qemu already published some fix, tested, works now
```
brew install qemu
Running `brew update --auto-update`...
==> Fetching qemu
==> Downloading https://ghcr.io/v2/homebrew/core/qemu/manifests/8.0.4-1
```

**Comment by johnnykang** [comment]
> Seems qemu already published some fix, tested, works now
> 
> ```
> brew install qemu
> Running `brew update --auto-update`...
> ==> Fetching qemu
> ==> Downloading https://ghcr.io/v2/homebrew/core/qemu/manifests/8.0.4-1
> ```

verified solution.

**Comment by Luap99** [comment]
Closing given this does not look like a podman problem and the qemu update fixes it

**Comment by corleoneZeng** [comment]
I also met the same problem yesterday and I have solved it in this way.

**Comment by xRomZak** [comment]
NOTE: facing a similar issue again after brew installed a latest qemu update
```
==> Upgrading qemu
  8.0.4 -> 8.1.0

> podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Error: HV_DENIED
```
