### ISSUE TITLE
CI: pasta: ICMP echo test: 100% packet loss

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#19612]
Seeing this often in CI and gating:
```
[+1568s] not ok 554 podman networking with pasta(1) - ICMP echo request
...
<+072ms> # $ podman run --net=pasta quay.io/libpod/testimage:20221018 sh -c ping -c3 -W1 $(sed -nr "s/^nameserver[ ]{1,}([^.]*).(.*)/\1.\2/p" /etc/resolv.conf | head -1)
<+3.37s> # PING 169.254.169.254 (169.254.169.254): 56 data bytes
         #
         # --- 169.254.169.254 ping statistics ---
         # 3 packets transmitted, 0 packets received, 100% packet loss
<+005ms> # [ rc=1 (** EXPECTED 0 **) ]
```

### [sys] podman networking with pasta(1) - ICMP echo request
* fedora-38 : sys podman fedora-38 rootless host boltdb
    * [08-09 22:09](https://api.cirrus-ci.com/v1/artifact/task/5497811299467264/html/sys-podman-fedora-38-rootless-host-boltdb.log.html#t--00554)
* fedora-38 : sys podman fedora-38 rootless host sqlite
    * [08-11 09:27](https://api.cirrus-ci.com/v1/artifact/task/5723234134392832/html/sys-podman-fedora-38-rootless-host-sqlite.log.html#t--00557)
    * [08-03 20:32](https://api.cirrus-ci.com/v1/artifact/task/4969047473782784/html/sys-podman-fedora-38-rootless-host-sqlite.log.html#t--00552)
* fedora-38 : sys remote fedora-38 rootless host sqlite [remote]
    * [08-11 16:05](https://api.cirrus-ci.com/v1/artifact/task/4870920423079936/html/sys-remote-fedora-38-rootless-host-sqlite.log.html#t--00557)
* rawhide : sys podman rawhide rootless host sqlite
    * [08-10 20:40](https://api.cirrus-ci.com/v1/artifact/task/6108747446091776/html/sys-podman-rawhide-rootless-host-sqlite.log.html#t--00557)

It's a flake in CI, but [not in gating](https://artifacts.dev.testing-farm.io/9e7d4f68-3a08-4400-90b4-de81cbeed237/work-tests.ymlxrl21qwf/tests-juh1y1y0/test.podman-rootless-cgroupsv2.bats.log), that one seems 100% reproducible.

**Comment by Luap99** [comment]
We are pinging infrastructure were we have close to zero control about it. The answer is we should not rely on ICMP being allowed for the first nameserver.

The question is why should podman CI even test pasta's ICMP? This feels like something pasta itself should test in an environment where ICMP is allowed. I don't see point of doing this for each podman PRs and the same for most other pasta features, i.e transfer tests and so on. pasta has to be gated on most of these tests not every podman PR.
Instead we catch regressions in podman CI image updates and gating which is already to late as this means a new (broken) passt package was pushed.

For podman we only really care about option parsing (`--network pasta:...`) and port forwarding.
