### ISSUE TITLE
Containers created with `--restart=always` do not restart when started through a pod

### ISSUE THREAD

**Issue by nivekuil** [containers/podman#19671]
### Issue Description

containers created with `--restart=always` do not restart when they exit, when started through the parent pod

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman pod create --name test-pod
2. podman create --restart=always --pod test-pod docker.io/bash exit 0
3. podman pod start test-pod
4. `podman ps -a`

### Describe the results you received

See that the container `Exited (127) N seconds ago` and is not restarting

### Describe the results you expected

I think `--restart=always` should always restart the container if it exits regardless of how it's started

### podman info output

```yaml
4.6.0
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by nivekuil** [comment]
@rhatdan thanks for putting up the patch. Are you able to put out a rush release? I see that there was discussion about this in https://github.com/containers/podman/pull/17627 where reviewers didn't want to break this exact situation, but unfortunately the line in question would actually have prevented the current situation where all workloads on 4.6 are at very high risk of unexpected downtime.

**Comment by rhatdan** [comment]
@mheon WDYT?

**Comment by mheon** [comment]
We are planning a 4.6.2 soon, aiming to finalize plans for when on Monday.
