### ISSUE TITLE
qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Error: HV_DENIED

### ISSUE THREAD

**Issue by xRomZak** [containers/podman#19708]
### Issue Description

Describe your issue:

Update brew and start podman/qemu
```
==> Upgrading qemu 8.0.4 -> 8.1.0
...
qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Error: HV_DENIED
```
Found this
https://patchwork.ozlabs.org/project/qemu-devel/patch/20230607085555.51643-1-quic_acaggian@quicinc.com/
https://github.com/search?q=repo%3Aqemu%2Fqemu%20HV_DENIED&type=code

### Steps to reproduce the issue

Steps to reproduce the issue
- podman machine init --cpus 3 --memory 2000 --rootful
- podman machine start

### Describe the results you received

> podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...

Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Error: HV_DENIED
> cat ~/.config/containers/podman/machine/qemu/podman-machine-default.json | grep accel
"q35,accel=hvf:tcg",

### Describe the results you expected

Podman/Qemu machine is up and running (as on qemu 8.04)

### podman info output

```yaml
macos ventura 13.4.1
podman 4.6.1
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
sounds like a problem with the qemu build from brew and not podman.

**Comment by xRomZak** [comment]
seems you are right, found similar issue in brew repo
https://github.com/Homebrew/homebrew-core/issues/140244

**Comment by xRomZak** [comment]
brew build issue. see a workaround

**Comment by chevdor** [comment]
Indeed, same issue and the following resolves it:
`brew update; brew upgrade qemu`
