### ISSUE TITLE
kube play: unexpectedly slow

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#19716]
```console
$ cat >/tmp/foo.yaml <<EOF
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: test
  name: test_pod
spec:
  restartPolicy: Never
  containers:
    - name: ctr1
      image: quay.io/libpod/testimage:20221018
      command:
      - true
    - name: ctr2
      image: quay.io/libpod/testimage:20221018
      command:
      - true
    - name: ctr3
      image: quay.io/libpod/testimage:20221018
      command:
      - true
    - name: ctr4
      image: quay.io/libpod/testimage:20221018
      command:
      - true
EOF
$ time bin/podman kube play /tmp/foo.yaml
...
bin/podman kube play /tmp/foo.yaml  0.34s user 0.16s system 7% cpu 6.897 total
```
It looks like a linear 1.5s per container (on my f38 laptop). Removing `ctrX` stanzas in the yaml speeds it up by 1.5s per container; adding more, slows it down more. Maybe this is intentional or unavoidable, but it surprises me.

**Comment by edsantiago** [comment]
It's just as slow in podman v4.0, so I guess this is nothing new.

**Comment by vrothberg** [comment]
You're spot on: _Everything_ in `kube play` is created in sequence without any use of parallelism.  Technically it's absolutely possible to parallelize most operations such as volume and (init) container creation.  The big _BUT_ from end is that we should first consider a refactoring of the `kube play` code.  It's spaghetti code that I fear would get even more complex when adding concurrency to it.

**Comment by edsantiago** [comment]
Should this be closed WONTFIX then?

**Comment by vrothberg** [comment]
I think it's worth pursuing to speed up kube play, so I would like to keep it open.

**Comment by edsantiago** [comment]
This is unlikely ever to get fixed.
