### ISSUE TITLE
podman pods with pasta network fail to start

### ISSUE THREAD

**Issue by waffshappen** [containers/podman#19722]
### Issue Description

When running a pod with --network pasta: it simply fails

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman pod create --replace --infra=true --hostname pod_main --network pasta:--mtu,1500,-a,x.y.z.0,-n,24,-g,x.y.z.2,--dns-forward,x.y.z.3,--no-ndp,--no-dhcpv6,--no-dhcp --share "net,ipc" --uts private main_pod` (Replace x.y.z with network of choice not already used)
2. podman pod start main_pod

### Describe the results you received

```
Error: starting container 0dbf397ea097b7b98e1214eff53ede7f925eafa9dea1217fc3a679a337f4b695: pasta failed with exit code 1:
Couldn't get any nameserver address
Template interface: enp35s0 (IPv4), enp35s0 (IPv6)
Namespace interface: enp35s0
MAC:
    host: a8:a1:[...]
DNS search list:
    example.com[replaced]
DNS search list:
    example.com[replaced]
Couldn't set IPv4 route(s) in guest: Network is unreachable
```

### Describe the results you expected

It working like it did with the previous pasta version in Fedora 38

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.31.2
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc38.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 94.84
    systemPercent: 1.86
    userPercent: 3.3
  cpus: 12
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    version: "38"
  eventLogger: journald
  freeLocks: 1993
  hostname: tobimain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 500000
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 500000
  kernel: 6.4.11-200.fc38.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 46391746560
  memTotal: 67324641280
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.7.0-1.fc38.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.7.0
    package: netavark-1.7.0-1.fc38.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.7.0
  ociRuntime:
    name: crun
    package: crun-1.8.6-1.fc38.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.6
      commit: 73f759f4a39769f60990e7d225f561b4f4f06bcf
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20230818.g0af928e-1.fc38.x86_64
    version: |
      pasta 0^20230818.g0af928e-1.fc38.x86_64
      Copyright Red Hat
      GNU Affero GPL version 3 or later <https://www.gnu.org/licenses/agpl-3.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-12.fc38.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 34m 33.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/tobias/.config/containers/storage.conf
  containerStore:
    number: 21
    paused: 0
    running: 21
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/tobias/.local/share/containers/storage
  graphRootAllocated: 510481399808
  graphRootUsed: 108740812800
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 22
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/tobias/.local/share/containers/storage/volumes
version:
  APIVersion: 4.6.1
  Built: 1691705273
  BuiltTime: Fri Aug 11 00:07:53 2023
  GitCommit: ""
  GoVersion: go1.20.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Fedora 38

**Comment by waffshappen** [comment]
Saving Maintainers the work: 
CC @sbrivio-rh @dgibson

**Comment by sbrivio-rh** [comment]
See also: https://github.com/containers/podman/pull/19699#issuecomment-1689366443 https://passt.top/passt/commit/?id=5e4f7b92b0b0bf4724c505fa95fcae1526a8f88b

...give me a moment. :)

**Comment by sbrivio-rh** [comment]
Fedora 38 [update](https://bodhi.fedoraproject.org/updates/FEDORA-2023-3a7b730bc9) with fix should reach "testing" in a bit.

**Comment by Luap99** [comment]
Given the fix is merged upstream I close this.

@sbrivio-rh @dgibson I invited you to this repo to give you triage permissions, with that you should be able to close/reopen issues and apply labels and assign people for example.

**Comment by sbrivio-rh** [comment]
> Given the fix is merged upstream I close this.
> 
> @sbrivio-rh @dgibson I invited you to this repo to give you triage permissions, with that you should be able to close/reopen issues and apply labels and assign people for example.

Thanks @Luap99!

@waffshappen this is now fixed in (passt-0^20230823.ga7e4bfb-1.fc38)[https://bodhi.fedoraproject.org/updates/FEDORA-2023-3a7b730bc9].

**Comment by waffshappen** [comment]
> @waffshappen this is now fixed in [passt-0^20230823.ga7e4bfb-1.fc38](https://bodhi.fedoraproject.org/updates/FEDORA-2023-3a7b730bc9).

Can confirm it is fixed 😃

**Comment by mailinglists35** [comment]
@sbrivio-rh if RH plans to ship a newer version of passt in an EL9 update, will this fix be included? If yes, will there be cherrypicks only, or a released based on more recent commit?

**Comment by dezza** [comment]
> @sbrivio-rh if RH plans to ship a newer version of passt in an EL9 update, will this fix be included? If yes, will there be cherrypicks only, or a release based on more recent commit?

Also very interested to know this. I have crun 1.8.7 pinned (https://github.com/containers/crun/issues/1302) and built the f38 passt version for cos-9 due to https://passt.top/passt/commit/?id=5e4f7b92b0b0bf4724c505fa95fcae1526a8f88b

**Comment by dgibson** [comment]
I believe we've been typically updating the release rather than cherry picking.  @sbrivio-rh would know better, but he's otherwise occupied most of this week.

**Comment by Luap99** [comment]
You can see the sources for centos stream: https://gitlab.com/redhat/centos-stream/rpms/passt/-/tree/c9s?ref_type=heads
Looks like it set to 0^20230818.g0af928e currently which I assume will ship in RHEL 9.3 so it will likely not contain this bug fix.

In general if you need fixes in RHEL or Centos Stream you have to file bug reports against the distro version. Upstream cannot really help with that.

**Comment by dezza** [comment]
We can hope only hope these issues if present somewhere are not locked by redhat, because otherwise its not easy to write a meaningful bug report - thats why it seems easier to ask redhat insider directly, sadly..

**Comment by mailinglists35** [comment]
> Looks like it set to 0^20230818.g0af928e currently which I assume will ship in RHEL 9.3 so it will likely not contain this bug fix.

that's exactly why I dared to ask Silvio here

**Comment by mailinglists35** [comment]
> Looks like it set to 0^20230818.g0af928e currently which I assume will ship in RHEL 9.3 so it will likely not contain this bug fix.

that's exactly why I dared to ask Stefano here
