### ISSUE TITLE
can`t start chronyd.service in container

### ISSUE THREAD

**Issue by sema200** [containers/podman#19771]
### Issue Description

I use roootles mode, and try to run container in rootless mode:
[podman@worker ~]$ podman version
Client:       Podman Engine
Version:      4.4.1
API Version:  4.4.1
Go Version:   go1.19.4
Built:        Wed May 17 00:22:45 2023
OS/Arch:      linux/amd64

[podman@worker ~]$ podman info
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.6-1.module+el8.8.0+1265+fa25dd7a.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.6, commit: a88a21e8953a6243d5f369f61a342bcaf0630aa1'
  cpuUtilization:
    idlePercent: 99.39
    systemPercent: 0.55
    userPercent: 0.05
  cpus: 1
  distribution:
    distribution: '"rocky"'
    version: "8.7"
  eventLogger: file
  hostname: worker
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1011
      size: 1
    - container_id: 1
      host_id: 820896
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1011
      size: 1
    - container_id: 1
      host_id: 820896
      size: 65536
  kernel: 4.18.0-425.19.2.el8_7.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 198086656
  memTotal: 1900793856
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.4-1.module+el8.8.0+1265+fa25dd7a.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.4
      spec: 1.0.2-dev
      go: go1.19.4
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /run/user/1011/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_SYS_CHROOT,CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.2.0-2.module+el8.8.0+1265+fa25dd7a.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 2126635008
  swapTotal: 2147479552
  uptime: 3h 27m 32.00s (Approximately 0.12 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  docker.io:
    Blocked: false
    Insecure: true
    Location: docker.io
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: docker.io
    PullFromMirror: ""
  search:
  - docker.io
store:
  configFile: /home/podman/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/podman/.local/share/containers/storage
  graphRootAllocated: 18238930944
  graphRootUsed: 6805135360
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /tmp/containers-user-1011/containers
  transientStore: false
  volumePath: /home/podman/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.1
  Built: 1684272165
  BuiltTime: Wed May 17 00:22:45 2023
  GitCommit: ""
  GoVersion: go1.19.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.1
  
[podman@worker ~]$ rpm -q podman
podman-4.4.1-12.module+el8.8.0+1265+fa25dd7a.x86_64

Hello dear colleagues!
I have some problems, with chronyd.service in my containers.
I run containers with all capabilities (and try run with only SYS-TIME capabilities), and chronyd.service service does\`t start.
Service failed, and report "chronyd[20]: adjtimex(0x8001) failed : Operation not permitted",
i search with problem on [https://bugzilla.redhat.com/show_bug.cgi?id=1772053](url), but it didn't help me.
I use to try run different command:

`podman run -d --cap-add=ALL --name rocky mymirror.localhost/rocky8`
`podman run -d --cap-add=CAP_SYS_TIME --name rocky mymirror.localhost/rocky8` 
`podman run -d --cap-add=ALL --privileged --name rocky mymirror.localhost/rocky8`

In all cases, service chronyd.service doesn`t work:

`[podman@worker ~]$ podman exec -it rocky bash`
`[root@6350b2e720e9 /]# systemctl status chronyd.service`
● chronyd.service - NTP client/server
   Loaded: loaded (/usr/lib/systemd/system/chronyd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2023-08-28 13:57:25 MSK; 13s ago
     Docs: man:chronyd(8)
           man:chrony.conf(5)
  Process: 29 ExecStopPost=/usr/libexec/chrony-helper remove-daemon-state (code=exited, status=0/SUCCESS)
  Process: 20 ExecStart=/usr/sbin/chronyd $OPTIONS (code=exited, status=1/FAILURE)

Aug 28 13:57:25 6350b2e720e9 systemd[1]: Starting NTP client/server...
Aug 28 13:57:25 6350b2e720e9 chronyd[20]: adjtimex(0x8001) failed : Operation not permitted
Aug 28 13:57:25 6350b2e720e9 systemd[1]: chronyd.service: Control process exited, code=exited status=1
Aug 28 13:57:25 6350b2e720e9 systemd[1]: chronyd.service: Failed with result 'exit-code'.
Aug 28 13:57:25 6350b2e720e9 systemd[1]: Failed to start NTP client/server.

### Steps to reproduce the issue

Steps to reproduce the issue
I use roootles mode, and try to run container in rootless mode:
`podman run -d --cap-add=ALL --name rocky mymirror.localhost/rocky8`
`podman run -d --cap-add=CAP_SYS_TIME --name rocky mymirror.localhost/rocky8` 
`podman run -d --cap-add=ALL --privileged --name rocky mymirror.localhost/rocky8`
In all cases, service chronyd.service doesn`t work:

`[podman@worker ~]$ podman exec -it rocky bash`
`[root@6350b2e720e9 /]# systemctl status chronyd.service`
● chronyd.service - NTP client/server
   Loaded: loaded (/usr/lib/systemd/system/chronyd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2023-08-28 13:57:25 MSK; 13s ago
     Docs: man:chronyd(8)
           man:chrony.conf(5)
  Process: 29 ExecStopPost=/usr/libexec/chrony-helper remove-daemon-state (code=exited, status=0/SUCCESS)
  Process: 20 ExecStart=/usr/sbin/chronyd $OPTIONS (code=exited, status=1/FAILURE)

Aug 28 13:57:25 6350b2e720e9 systemd[1]: Starting NTP client/server...
Aug 28 13:57:25 6350b2e720e9 chronyd[20]: adjtimex(0x8001) failed : Operation not permitted
Aug 28 13:57:25 6350b2e720e9 systemd[1]: chronyd.service: Control process exited, code=exited status=1
Aug 28 13:57:25 6350b2e720e9 systemd[1]: chronyd.service: Failed with result 'exit-code'.
Aug 28 13:57:25 6350b2e720e9 systemd[1]: Failed to start NTP client/server.`

### Describe the results you received

In all cases, service chronyd.service doesn`t work:

Service can`t get access to adjtimex(0x8001):
Aug 28 13:57:25 6350b2e720e9 chronyd[20]: adjtimex(0x8001) failed : Operation not permitted

### Describe the results you expected

In rootless mode, service chronyd.service can start in container.

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by vrothberg** [comment]
Thanks for reaching out, @sema200.

>  Aug 28 13:57:25 6350b2e720e9 chronyd[20]: adjtimex(0x8001) failed : Operation not permitted

I am pretty sure this requires root privileges as it alters kernel data.  Can you try running the container as the root user?

**Comment by sema200** [comment]
Hello @vrothberg, thank you for you answer!
In root mode, service start and work:
`[root@worker ~] podman run -d --cap-add=ALL --name rocky mymirror.localhost/rocky8`
`[root@worker ~]# podman exec -it rocky bash`
`[root@cc8a85b156b6 /]# systemctl status chronyd.service`
● chronyd.service - NTP client/server
   Loaded: loaded (/usr/lib/systemd/system/chronyd.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2023-08-28 14:28:28 MSK; 34s ago
     Docs: man:chronyd(8)

**Comment by vrothberg** [comment]
Thanks for checking, @sema200.

In this case, there is nothing Podman can do as the workload requires true root that cannot be mapped by a user namespace.

**Comment by sema200** [comment]
I use jenkins + podman, and i test my roles in molecule.
When i user docker (docker`s daemon start on root), i don`t have this problems, after migration to Rocky8, and to podman,
i catch this problems.
@vrothberg thank you for you time!

**Comment by vrothberg** [comment]
@sema200, docker already runs as root. Podman runs rootless by default (for security reasons, among many others). It's rare that workloads require running as true root. In your case, add a `sudo podman` and it should work without issues.

**Comment by sema200** [comment]
@vrothberg Thank you for you help!
i will try use `sudo podman`.

**Comment by sema200** [comment]
@vrothberg some problems i solved, if i start this options "-x" (i insert this key to /etc/sysconfig/chronyd).
chronyd[152]: Disabled control of system clock
and service is start.
