### ISSUE TITLE
Clamav antivirus: fanotify_init failed: Operation not permitted

### ISSUE THREAD

**Issue by sema200** [containers/podman#19778]
### Issue Description

I use roootles mode, and try to run container in rootless mode:
[podman@worker ~]$ podman version
Client: Podman Engine
Version: 4.4.1
API Version: 4.4.1
Go Version: go1.19.4
Built: Wed May 17 00:22:45 2023
OS/Arch: linux/amd64

[podman@worker ~]$ podman info
host:
arch: amd64
buildahVersion: 1.29.0
cgroupControllers: []
cgroupManager: cgroupfs
cgroupVersion: v1
conmon:
package: conmon-2.1.6-1.module+el8.8.0+1265+fa25dd7a.x86_64
path: /usr/bin/conmon
version: 'conmon version 2.1.6, commit: a88a21e8953a6243d5f369f61a342bcaf0630aa1'
cpuUtilization:
idlePercent: 99.39
systemPercent: 0.55
userPercent: 0.05
cpus: 1
distribution:
distribution: '"rocky"'
version: "8.7"
eventLogger: file
hostname: worker
idMappings:
gidmap:
- container_id: 0
host_id: 1011
size: 1
- container_id: 1
host_id: 820896
size: 65536
uidmap:
- container_id: 0
host_id: 1011
size: 1
- container_id: 1
host_id: 820896
size: 65536
kernel: 4.18.0-425.19.2.el8_7.x86_64
linkmode: dynamic
logDriver: k8s-file
memFree: 198086656
memTotal: 1900793856
networkBackend: cni
ociRuntime:
name: runc
package: runc-1.1.4-1.module+el8.8.0+1265+fa25dd7a.x86_64
path: /usr/bin/runc
version: |-
runc version 1.1.4
spec: 1.0.2-dev
go: go1.19.4
libseccomp: 2.5.2
os: linux
remoteSocket:
path: /run/user/1011/podman/podman.sock
security:
apparmorEnabled: false
capabilities: CAP_SYS_CHROOT,CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
rootless: true
seccompEnabled: true
seccompProfilePath: /usr/share/containers/seccomp.json
selinuxEnabled: false
serviceIsRemote: false
slirp4netns:
executable: /bin/slirp4netns
package: slirp4netns-1.2.0-2.module+el8.8.0+1265+fa25dd7a.x86_64
version: |-
slirp4netns version 1.2.0
commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
libslirp: 4.4.0
SLIRP_CONFIG_VERSION_MAX: 3
libseccomp: 2.5.2
swapFree: 2126635008
swapTotal: 2147479552
uptime: 3h 27m 32.00s (Approximately 0.12 days)
plugins:
authorization: null
log:

k8s-file
none
passthrough
journald
network:
bridge
macvlan
ipvlan
volume:
local
registries:
docker.io:
Blocked: false
Insecure: true
Location: docker.io
MirrorByDigestOnly: false
Mirrors: []
Prefix: docker.io
PullFromMirror: ""
search:
docker.io
store:
configFile: /home/podman/.config/containers/storage.conf
containerStore:
number: 1
paused: 0
running: 1
stopped: 0
graphDriverName: overlay
graphOptions: {}
graphRoot: /home/podman/.local/share/containers/storage
graphRootAllocated: 18238930944
graphRootUsed: 6805135360
graphStatus:
Backing Filesystem: xfs
Native Overlay Diff: "true"
Supports d_type: "true"
Using metacopy: "false"
imageCopyTmpDir: /var/tmp
imageStore:
number: 1
runRoot: /tmp/containers-user-1011/containers
transientStore: false
volumePath: /home/podman/.local/share/containers/storage/volumes
version:
APIVersion: 4.4.1
Built: 1684272165
BuiltTime: Wed May 17 00:22:45 2023
GitCommit: ""
GoVersion: go1.19.4
Os: linux
OsArch: linux/amd64
Version: 4.4.1
[podman@worker ~]$ rpm -q podman
podman-4.4.1-12.module+el8.8.0+1265+fa25dd7a.x86_64

I try to run clamav antivirus in container, in run comand i pass all capabilities:
`podman run -d --cap-add=ALL --name rocky mymirror.localhost/rocky8`

after i login in to container, and install calmav antivirus.
When is start it, i get error:
Aug 28 15:58:52 abb6eb38006f clamonacc[16788]: ERROR: Clamonacc: fanotify_init failed: Operation not permitted
Aug 28 15:58:52 abb6eb38006f clamonacc[16788]: ERROR: Clamonacc: clamonacc must have elevated permissions ... exiting

I use recommendations from:
https://bugzilla.redhat.com/show_bug.cgi?id=2028060,
but it`s not work.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman run -d --cap-add=ALL --name rocky mymirror.localhost/rocky8`
2. `podman exec -it rocky bash`
3. `[root@abb6eb38006f /]# dnf install clamd clamav`
4. `[root@abb6eb38006f /]# systemctl restart clamav-clamonacc.service`
`[root@abb6eb38006f /]# systemctl status clamav-clamonacc.service`
● clamav-clamonacc.service - ClamAV On-Access Scanner
   Loaded: loaded (/usr/lib/systemd/system/clamav-clamonacc.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2023-08-28 18:16:35 MSK; 2s ago
     Docs: man:clamonacc(8)
           man:clamd.conf(5)
           https://docs.clamav.net/
  Process: 17206 ExecStart=/usr/sbin/clamonacc -F --config-file=/etc/clamd.d/scan.conf (code=exited, status=2)
 Main PID: 17206 (code=exited, status=2)

Aug 28 18:16:35 abb6eb38006f systemd[1]: Started ClamAV On-Access Scanner.
Aug 28 18:16:35 abb6eb38006f clamonacc[17206]: ERROR: Clamonacc: fanotify_init failed: Operation not permitted
Aug 28 18:16:35 abb6eb38006f clamonacc[17206]: ERROR: Clamonacc: clamonacc must have elevated permissions ... exiting ...

if i start clamav-clamonacc.service in root mode (after admit settings from https://bugzilla.redhat.com/show_bug.cgi?id=2028060), service start and workin (on root mode).

### Describe the results you received

service clamav-clamonacc.service can`t start

### Describe the results you expected

clamav-clamonacc.service cat start and working

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by mheon** [comment]
Given that `--cap-add=all` is passed, this is most likely a kernel restriction; I can't find any mention of user namespaces in the `fanotify_init` manpage, but given that it requires `CAP_SYS_ADMIN` and that capability is very restricted for rootless containers.

**Comment by rhatdan** [comment]
Try in --privileged mode to make sure SELinux or Seccomp is not blocking.  But it is likely that real SYS_ADMIN acces is required versus Namespaced SYS_ADMIN.

**Comment by baude** [comment]
given this is not likely a podman issue but more of a "how do i run my container" question, should this be closed or moved to a discussion?

**Comment by sema200** [comment]
@baude Hello, i think that it`s a podman`s problem. I use --privileged mode, and pass SYS_ADMIN capabilities.
I root mode, this problem doesn`t shown.
If i use docker, this problem doesn`t shown too.

**Comment by vrothberg** [comment]
Docker runs as root by default.  Since it works with root Docker and root Podman, I assume that the workload just requires true root privileges which is confirmed in the blog (https://blog.clamav.net/2019/09/understanding-and-transitioning-to.html). In that case, there is nothing Podman can do.

**Comment by rhatdan** [comment]
If you run docker in rootless mode you will have the same problem.
