### ISSUE TITLE
Pull from public.ecr.aws is extremely slow and uses excessive disk space

### ISSUE THREAD

**Issue by onitake** [containers/podman#19811]
### Issue Description

When pulling the image `public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:5.0` from the public AWS container registry, a huge amount of disk space is used to download and unpack the layers (>100GB).

Pulling the same image with Docker (tested: 20.10.25) is at least one order of magnitude faster and uses disk space in the same order of magnitude than the reported size of the container image (~7GB used, image is 2.6GB).

### Steps to reproduce the issue

```shell
podman pull public.ecr.aws/codebuild/amazonlinux2-x86_64-standard:5.0
```

### Describe the results you received

After displaying a number of "Copying blob xxxxxx done" messages, local disk fills up, and pull aborts at some point due to lack of disk space.

Trying to clean up the incomplete download fails via `podman rmi` (no images shown) and via `podman system prune` (no effect). Only deleting all layers from `~/.local/share/containers/storage/vfs` manually helps to reclaim space, but this will lead to problems when trying another pull later (presumably due to state caching).

### Describe the results you expected

Container image is downloaded and unpacked quickly and does not use unnecessary disk space.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2.1.6+ds1-1_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.6, commit: unknown'
  cpuUtilization:
    idlePercent: 85.69
    systemPercent: 5.71
    userPercent: 8.6
  cpus: 2
  distribution:
    codename: trixie
    distribution: debian
    version: unknown
  eventLogger: journald
  hostname: debian
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.4.0-3-amd64
  linkmode: dynamic
  logDriver: journald
  memFree: 1246035968
  memTotal: 2062450688
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun_1.8.7-1_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.7
      commit: 53a9996ce82d1ee818349bdcc64797a1fa0433c4
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.2.0-1_amd64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 1022357504
  swapTotal: 1022357504
  uptime: 0h 2m 11.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 19947929600
  graphRootUsed: 1540501504
  graphStatus: {}
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.0
  Built: 0
  BuiltTime: Wed Dec 31 19:00:00 1969
  GitCommit: ""
  GoVersion: go1.19.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Tests were run on a local machine and on an EC2 instance.

### Additional information

I can't test with an upstream or privileged version at the moment, but will try to do so later.

**Comment by flouthoc** [comment]
Could you try with using `overlay` as storage driver instead of `vfs` ? Although there could somthing related to `pull` mechanism itself, tagging @mtrmac for info.

**Comment by vrothberg** [comment]
Also please provide the full output of `podman info` as requested in the issue template.

**Comment by mtrmac** [comment]
This is a 45-layer image, and with `vfs` each layer makes a full copy. So if the image is on the order of 1 GB within the first 5 layers, that means 40 more copies of at least 1 GB.

At a first glance it seems likely to me that most of that time and space can be attributed to the unavoidable cost of using `vfs`; some other graph driver, probably some of the overlay variants, would be a much better fit.

**Comment by onitake** [comment]
The issue does not occur with the `overlay` driver. In fact, performance is comparable with docker in that case.
I suppose I could have seen this coming had I read the man page: https://docs.podman.io/en/latest/markdown/podman-run.1.html#rootless-containers

Added `podman info` output, as requested.

**Comment by onitake** [comment]
Is there a specific reason why the `vfs` driver isn't the default?
It seems a bit risky to allow container storage explosion so easily.

**Comment by afbjorklund** [comment]
* https://github.com/containers/podman/issues/8560

**Comment by vrothberg** [comment]
> Is there a specific reason why the vfs driver is the default?

Podman defaults to using overlayfs, so I assume that the Debian package may configure it otherwise.  Please open a bugzilla issue over at Debian for that.

Cc: @siretart

**Comment by afbjorklund** [comment]
> Is there a specific reason why the `vfs` driver is the default? It seems a bit risky to allow container storage explosion so easily.

The fix appeared in 4.5.0 (444f19cb2a3d056a5ffca96f4b0a8af69ecde5ab), but you are running 4.4.0

**Comment by onitake** [comment]
Thanks a lot for that information!
I've reported this issue on the Debian bug tracker: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1050993
There were some related bug reports, but none of them about enabling the `overlay` driver by default.

**Comment by vrothberg** [comment]
Thank you!  I think the best is to no configure a driver by default at all.  Podman is smart enough to use overlayfs is possible and would otherwise resort to less performant drivers.

**Comment by onitake** [comment]
Hmm... is that the case in 4.4?
Debian doesn't even ship a storage.conf file, so I assume the default must be in the source code somewhere?

**Comment by vrothberg** [comment]
Interesting.  Maybe that was 4.5 change then.

**Comment by siretart** [comment]
It seems to me that this issue is very similar to what has been reported before as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1002997 -- in that bug report, the reporter requested a tweaked `storage.conf` to enable a specific option (`metacopy=on`).  I've suggested to have this option enabled in the upstream configuraiton file, but it doesn't seem this got executed on.

After 18 months without updates, Cian noted that this option is not necessary by making podman prefer overlayfs over vfs, which is tracked as https://github.com/containers/storage/issues/1570 and https://github.com/containers/storage/pull/1571 -- None of these changes are currently in Debian, since I'm still working on integrating new package dependencies podman 4.5 requires. But I'll make a mental note to close both http://bugs.debian.org/1002997 and https://bugs.debian.org/1050993 as soon as I'm able to upload podman 4.5

thanks for looping me in!

**Comment by vrothberg** [comment]
Thanks for sharing the details, @siretart !

**Comment by onitake** [comment]
I just upgraded to the Debian version 4.5, and it looks like it still defaults to vfs:

```
$ podman info
  graphDriverName: vfs
  Version: 4.5.1
$ ls /etc/containers/storage.conf
ls: cannot access '/etc/containers/storage.conf': No such file or directory
$ ls $HOME/.config/containers/storage.conf
ls: cannot access '$HOME/.config/containers/storage.conf': No such file or directory
```

Is there anything that needs to be set during build to encourage usage of the overlay driver?

**Comment by afbjorklund** [comment]
> Is there anything that needs to be set during build to encourage usage of the overlay driver?

Any existing driver will be kept during upgrades, unless you decide to reset all the storage.

**Comment by afbjorklund** [comment]
Oops, apparently the patch was in v4.6.0 and **not** in v4.5.0 as I accidentally wrote...

But since you all read the changelogs carefully, you probably already noticed this? 😄

https://github.com/containers/podman/releases/tag/v4.6.0

> Updated the containers/storage library to v1.48.0

https://github.com/containers/podman/releases/tag/v4.5.0

> Updated the containers/storage library to v1.46.1

**Comment by onitake** [comment]
> Any existing driver will be kept during upgrades, unless you decide to reset all the storage.

That is not exactly what happened here...

Sure, the storage driver was kept, but it resulted in errors like this after I removed the previous explicit override to the `overlay` driver in `storage.conf`, expecting podman 4.5 to use `overlay` by default:

```
ERRO[0000] User-selected graph driver "vfs" overwritten by graph driver "overlay" from database - delete libpod local files
```

Thanks for the explanation - I hope the Debian package can be updated to 4.6 soon!
Ping @siretart (Thanks!)

**Comment by siretart** [comment]
4.6.2 is now available and ready to use from debian/experimental. Please give it a try and let me know how it works for you. I plan to push to unstable/testing soon.

**Comment by onitake** [comment]
It's working very well for me so far.

I've found [this guide](https://www.redhat.com/sysadmin/share-container-image-podman-save) to help with image export and import, but it's not quite enough for a full storage migration.
Is there any official documentation, blog post, etc. about migrating from vfs to overlay?

This might cover the most important things:
```shell
# save the filesystem of a container
podman export -o important-container.tar important_container
# save a volume
podman volume export -o important-volume.tar important_volume
# save all container images
podman save -o images.tar
# delete ~/.local/share/containers
# check that podman is using the overlay driver
podman info | grep graphDriverName
# re-import all container images
podman load -i images.tar
# re-import a saved container filesystem as a container image
podman import important-container.tar
# re-import a volume
podman volume import important_volume important-volume.tar
```
