### ISSUE TITLE
On some systems, running `sleep 1` can take up to 8s when running several processes in parallel

### ISSUE THREAD

**Issue by bduffany** [containers/podman#19824]
### Issue Description

Hi, we are seeing an issue in podman that running several concurrent instances of `podman run busybox sleep 1` exhibits the following behavior:

- At first, each sleep command takes ~1.2-1.3s, which is expected (since podman has some small overhead).
- Over time though, the performance degrades. The average slowly goes up to about 2s per sleep command, with many commands taking 3-4s and a few commands taking as much as 8s.

(Our real problem is that we have a service that runs podman containers on-the-fly, and occasionally we see the tail latency spike up very high when running several containers concurrently. But this `sleep` example is probably easier to look at since it mostly takes the container workload type out of the equation.)

I am running Ubuntu 22.04 with podman 4.6.2 (from the [alvistack](https://software.opensuse.org/download/package?package=podman&project=home%3Aalvistack) repo) but am also able to reproduce this with earlier versions of podman, including 4.5. The number of concurrent instances is limited to the number of available threads on my machine (32) by using `make -j32`.

Oddly, I *cannot* reproduce this behavior when running podman 4.6.2 nested inside an alpine linux container. All of the runs seem to be consistently taking ~1.2-1.3s without getting sluggish. I'm running the alpine container on my ubuntu machine like `podman run --privileged mgoltzsche/podman:4.6.2`.

I was also able to reproduce this on a Debian 11 VM with `gcloud compute instances create` with settings `--machine-type=c2-standard-30 -boot-disk-size=100GB --boot-disk-type=pd-ssd`

I am happy to help gather any profiling data needed to find the bottleneck here, I just don't have a good sense for what to look for yet. I don't see any obvious differences in `top` or `iotop` when running the repro script in both setups. And it is hard to make sense of the `strace` output because I am running so many tasks in parallel; it outputs data too quickly.

### Steps to reproduce the issue

Install `make` and `bc` if not installed (`sudo apt-get update && sudo apt-get install make bc`), then copy and paste the following into a terminal (if needed, replace `32` in `make -j32` with the number of CPU cores on your system)

```shell
# Write a script "sleep1.sh" that runs `sleep 1` in a busybox container with podman
echo > ./sleep1.sh '#!/bin/sh
set -eu
start=$(cat /proc/uptime | awk "{print \$1}")
podman run --net=none --rm mirror.gcr.io/library/busybox sleep 1
end=$(cat /proc/uptime | awk "{print \$1}")
echo $(echo $end - $start | bc) seconds
'
chmod +x ./sleep1.sh

# Write a Makefile that when running make <anything> it just runs sleep1.sh
# e.g. "make 1 2 3" will just run sleep1.sh 3 times
printf '%%:\n\t./sleep1.sh\n' > Makefile

# Pull busybox
podman pull mirror.gcr.io/library/busybox

# Run `sleep1.sh` 1000 times, with 32 concurrent jobs
# Replace 32 with the number of cores on your system
seq 1 1000 | xargs sudo make -j32
```

### Describe the results you received

- At first, each sleep command takes 1.3s, which is fine - I expect around 300ms of podman overhead.
- Over time though, the performance degrades. It looks to be about 2s on average, with frequent spikes as high as 8s.

### Describe the results you expected

Each command should take 1.3-1.4s consistently, like it does in Alpine.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.31.2
  cgroupControllers:
  - memory
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon_100:2.1.8-1_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.8, commit: 00e08f4a9ca5420de733bf542b930ad58e1a7e7d'
  cpuUtilization:
    idlePercent: 98.56
    systemPercent: 0.37
    userPercent: 1.07
  cpus: 32
  databaseBackend: boltdb
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: file
  freeLocks: 2027
  hostname: d
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.2.0-26-generic
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 5490999296
  memTotal: 66505388032
  networkBackend: cni
  networkBackendInfo:
    backend: cni
    dns: {}
    package: 'containernetworking-plugins, containernetworking: /usr/libexec/cni'
    path: /usr/libexec/cni
  ociRuntime:
    name: runc
    package: runc_1.1.4-0ubuntu1~22.04.3_amd64
    path: /usr/sbin/runc
    version: |-
      runc version 1.1.4-0ubuntu1~22.04.3
      spec: 1.0.2-dev
      go: go1.18.1
      libseccomp: 2.5.3
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_100:1.2.1-1_amd64
    version: |-
      slirp4netns version 1.2.1
      commit: unknown
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 1916530688
  swapTotal: 2046816256
  uptime: 58h 3m 28.00s (Approximately 2.42 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/b/.config/containers/storage.conf
  containerStore:
    number: 21
    paused: 0
    running: 0
    stopped: 21
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/b/.local/share/containers/storage
  graphRootAllocated: 1963519844352
  graphRootUsed: 175010361344
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 11
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/b/.local/share/containers/storage/volumes
version:
  APIVersion: 4.6.2
  Built: 0
  BuiltTime: Wed Dec 31 18:00:00 1969
  GitCommit: ""
  GoVersion: go1.21.0
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.2
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

**Comment by vrothberg** [comment]
Thanks for reaching out and providing the nice reproducer, @bduffany.

I thin you are reaching the architectural limitations of Podman.  Podman does not run as a daemon but employs a traditional fork-exec model for running containers.  That implies that state must be written to and synchronized on disk.  If we have 32 processes running concurrently and all wanting to remove the container, they will queue in on the lock for the central container storage.  This storage is on disk, and for each write/removal Podman needs to perform a fairly expensive fsync call.

That means that the `podman run --rm` processes queue at the file locks, waiting for the previous ones to finish certain operations.  Podman is not designed for such highly concurrent use cases.  _BUT_ there a tricks :-)  Can you try running `podman --transient-store` (see "Transient Store" in https://www.redhat.com/sysadmin/speed-containers-podman-raspberry-pi) and observe the behavior?  That should _greatly_ improve the situation as many operations are significantly faster; especially the fsyncs have near 0 cost.

**Comment by bduffany** [comment]
@vrothberg thanks for replying so quickly! Seems `--transient-store` fixes the issue. For the repro I was using, it turns out that setting both `--transient-store` and `--net=none` is needed to get good performance (as they mention in that article). If I remove either of those, I see the throughput issues.

**Comment by vrothberg** [comment]
@bduffany, thanks for reporting back.  I am glad it's performing in your use case.  Please reach out again if you encounter any other issue.
