### ISSUE TITLE
Command `manifest inspect` wants to mount stuff

### ISSUE THREAD

**Issue by gabyx** [containers/podman#19828]
### Issue Description

I have installed `podman` inside a container. I am aware that I can only run containers with special privileges set etc.
However `docker manifest inspect alpine:latest` works without having to mount anything.
Podman tries to do some startup probably which is too much for the command `manifest inspect`.

Run `podman manifest inspect alpine:latest` returns
``` 

### Steps to reproduce the issue

Steps to reproduce the issue
1.
2.
3.


### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by mheon** [comment]
Do you have any details on errors encountered, or better yet, a reproducer?
