### ISSUE TITLE
Unable to connect to RabbitMQ server run using podman from remote client machine on the same network

### ISSUE THREAD

**Issue by pavanrudraswamy** [containers/podman#19832]
### Issue Description

Hi 
I have RabbitMq which is run in machine 1(192.168.0.106) and machine 2(192.168.0.66) accesses it as a client in the same network(same subnet and default gateway). The issue is, when I run using podman using below mentioned command. I am unable to access it from machine 2(192.168.0.66) with http://192.168.0.106:15672 to get login page of RabbitMQ management portal.
 **podman run --rm -it -e RABBITMQ_DEFAULT_USER=testuser -e RABBITMQ_DEFAULT_PASS=testuser123 -p 15672:15672 -p 5672:5672 rabbitmq:3-management** 
 
 But, if I run it using docker with same Rabbit Mq version as mentioned above, I can access with http://192.168.0.106:15672 without any problem.
 **docker run --rm -it -e RABBITMQ_DEFAULT_USER=testuser -e RABBITMQ_DEFAULT_PASS=testuser123 -p 15672:15672 -p 5672:5672 rabbitmq:3-management**
 
 **Rabbit Mq Version: 3.12.4** for both podman and docker
 Is it an underlying issue with podman, am I missing something while running it?
 Note: Host machine in Windows OS

Podman details:
C:\Users\rpavan>podman version
Client:       Podman Engine
Version:      4.5.1
API Version:  4.5.1
Go Version:   go1.20.4
Git Commit:   9eef30051c83f62816a1772a743e5f1271b196d7
Built:        Fri May 26 22:36:38 2023
OS/Arch:      windows/amd64

Server:       Podman Engine
Version:      4.5.0
API Version:  4.5.0
Go Version:   go1.19.7
Built:        Fri Apr 14 21:12:56 2023
OS/Arch:      linux/amd64

C:\Users\rpavan>podman info
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.7-2.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 99.88
    systemPercent: 0.06
    userPercent: 0.06
  cpus: 16
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: container
    version: "37"
  eventLogger: journald
  hostname: 3457-J93BHW3
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 5.15.90.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 5778661376
  memTotal: 7927525376
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.5-1.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.5
      commit: b6f80f766c9a89eb7b1440c0a70ab287434b17ed
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 2147483648
  swapTotal: 2147483648
  uptime: 7h 5m 54.00s (Approximately 0.29 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 1517080576
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.0
  Built: 1681486976
  BuiltTime: Fri Apr 14 21:12:56 2023
  GitCommit: ""
  GoVersion: go1.19.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.0

C:\Users\rpavan>rpm -q podman
'rpm' is not recognized as an internal or external command,
operable program or batch file.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Laptop/machine 1 has to be connected to a wifi/lan network and Podman has to be intialized and running
2. Now go to command prompt and run the following command:
podman run --rm -it -e RABBITMQ_DEFAULT_USER=testuser -e RABBITMQ_DEFAULT_PASS=testuser123 -p 15672:15672 -p 5672:5672 rabbitmq:3-management

RabbitMQ image is pulled and it successfully starts accepting connections like this snipper
2023-09-01 17:41:02.060627+00:00 [info] <0.617.0> Server startup complete; 4 plugins started.
2023-09-01 17:41:02.060627+00:00 [info] <0.617.0>  * rabbitmq_prometheus
2023-09-01 17:41:02.060627+00:00 [info] <0.617.0>  * rabbitmq_management
2023-09-01 17:41:02.060627+00:00 [info] <0.617.0>  * rabbitmq_management_agent
2023-09-01 17:41:02.060627+00:00 [info] <0.617.0>  * rabbitmq_web_dispatch
2023-09-01 17:41:03.095626+00:00 [info] <0.766.0> accepting AMQP connection <0.766.0> ([::1]:56482 -> [::1]:5672)
2023-09-01 17:41:03.108683+00:00 [info] <0.766.0> connection <0.766.0> ([::1]:56482 -> [::1]:5672): user 'tb-user' authenticated and granted access to vhost '/'

3. Now take another laptop/machine 2 and connect it to the same network as machine 2
4. Just for proof use ping command with the IP address of machine 1 and check if machine 2 is getting reply from machine 1.
5. Now that they are communicating, go to any browser(chrome/edge) and type http://<IP Address of Machine 1>:15672 and click enter

### Describe the results you received

Receive an error that "This site can't be reached"

### Describe the results you expected

I should be able to get login page of RabbitMq management portal to access it.

All firewalls settings are off and docker is able to successfully provide a RabbitMq managent portal with same version of RabbitMQ server(3.12.4). So there must be something missing, so I request someone to please help me with this

### podman info output

```yaml
C:\Users\rpavan>podman info
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.7-2.fc37.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 99.88
    systemPercent: 0.06
    userPercent: 0.06
  cpus: 16
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: container
    version: "37"
  eventLogger: journald
  hostname: 3457-J93BHW3
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 5.15.90.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 5778661376
  memTotal: 7927525376
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.8.5-1.fc37.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.5
      commit: b6f80f766c9a89eb7b1440c0a70ab287434b17ed
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-8.fc37.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 2147483648
  swapTotal: 2147483648
  uptime: 7h 5m 54.00s (Approximately 0.29 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 1517080576
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.5.0
  Built: 1681486976
  BuiltTime: Fri Apr 14 21:12:56 2023
  GitCommit: ""
  GoVersion: go1.19.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.0
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by mheon** [comment]
Can the machine running Podman access the management port?

Also, I assume you're using a `podman machine` VM?

**Comment by baude** [comment]
@n1hility does the wsl networking allow for these types of connections?

**Comment by baude** [comment]
@n1hility does the wsl networking allow for these types of connections?

**Comment by n1hility** [comment]
WSL port port forwarding, by default, is limited to localhost. However, you can forward traffic from an external network by creating a port proxy. See this doc for details: https://learn.microsoft.com/en-us/windows/wsl/networking#accessing-a-wsl-2-distribution-from-your-local-area-network-lan

**Comment by pavanrudraswamy** [comment]
@n1hility I tried making the changes and it worked without any issue, thank you so much for your help. I also thank @baude and @mheon for your comments.
**I have attached steps to be performed for other members, if they face similar issue in the future** 
[StepstorunRabbitMQ.txt](https://github.com/containers/podman/files/12504581/StepstorunRabbitMQ.txt)
