### ISSUE TITLE
Create container with docker image doesn't work

### ISSUE THREAD

**Issue by nicolasduminil** [containers/podman#19845]
### Issue Description

Running the following command to create a container from a Docker image:

    $ docker images
    REPOSITORY                            TAG                                IMAGE ID       CREATED         SIZE
    ...
    swaggerapi/swagger-ui                 latest                             f6ccd9f45778   2 weeks ago     106MB
    ...
    $ podman create -p 80:8080 --name  swaggerapi/swagger-ui:latest
    Error: short-name "swaggerapi/swagger-ui:latest" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"

What am I doing wrong here ?

### Steps to reproduce the issue

Steps to reproduce the issue

    $ docker pull swaggerapi/swagger-ui
    $ podman create -p 80:8080 --name  swaggerapi/swagger-ui:latest

### Describe the results you received

    Error: short-name "swaggerapi/swagger-ui:latest" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"

### Describe the results you expected

Create a new podman container running the given docker image

### podman info output

```yaml
$ podman version
    Version:      3.4.4
    API Version:  3.4.4
    Go Version:   go1.18.1
    Built:        Thu Jan  1 01:00:00 1970
    OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by vrothberg** [comment]
Thanks for reaching out, @nicolasduminil.

Can you share the output of `podman info`?

As the error message points out, there is no search registry configured on your host.  This sounds like a custom installation?  For more information about what this error message means, please refer to https://www.redhat.com/sysadmin/container-image-short-names.

If you want a quick-fix for it, configure `/etc/containers/registries.conf` as follows:
```TOML
unqualified-search-registries = ["registry.fedoraproject.org", "registry.access.redhat.com", "docker.io", "quay.io"]
```

I am closing the issue but we can continue the conversation here.

**Comment by vrothberg** [comment]
> No, I don't need to configure any registry since the image is local.

Did you read https://www.redhat.com/sysadmin/container-image-short-names?  It also impacts how images resolved locally.  If you use a short name, you need to configure unqualified-search-registries (or configure aliases).

**Comment by vrothberg** [comment]
Please read the linked article to adjust your assumptions.

See the error message: `Error: short-name "swaggerapi/swagger-ui:latest"`.  `swaggerapi/swagger-ui:latest` does not include a registry and is hence considered as a short name.  In order to resolve that, Podman either needs a short-name alias or search registries configured.

Docker always defaults to `docker.io`.  Podman gives users more flexibility and can resolve to any (configured) alias or registry.  Your environment seems to miss this configuration.

**Comment by nicolasduminil** [comment]
I just have read the link you attached but it isn't relevant as it's about pulling. And I don't pull anything since my image is already pulled.

**Comment by nicolasduminil** [comment]
@vrothberg Could you please forget the pulling since I'm telling you that I don't pull  anything ? And forget also docker.io since I'm telling you that the image is local ?

**Comment by nicolasduminil** [comment]
I tried to create a tag for the mentioned `swaggerapi/swagger-ui:latest` image but I got:

    Error: swaggerapi/swagger-ui:latest: image not known

So podman doesn't "see" the image and, as a matter of fact:

    $ podman images
    REPOSITORY        TAG         IMAGE ID      CREATED      SIZE
    k8s.gcr.io/pause  3.5         ed210e3e4a5b  2 years ago  690 kB

But:

    $ docker images
    REPOSITORY                            TAG                                IMAGE ID       CREATED         SIZE
    nctsdep-sec                           latest                             1dc161052bcf   5 hours ago     497MB
    nctstra-sec                           latest                             5380baea5d1c   5 hours ago     497MB
    ncts-gateway                          latest                             f04a49f4715a   5 hours ago     516MB
    minfin/fram                           latest                             cfbe584a89b5   13 days ago     430MB
    swaggerapi/swagger-ui                 latest                             f6ccd9f45778   2 weeks ago     106MB
    tomcat                                8-jre8                             e08afcbe3f36   2 weeks ago     242MB
    tomcat                                latest                             6adff26d17ba   2 weeks ago     426MB
    tomcat                                10.1.11-jdk17-temurin-jammy        74c40fb60535   2 weeks ago     429MB
    openidentityplatform/openam           latest                             233ea142e977   6 weeks ago     771MB
    testcontainers/ryuk                   0.3.4                              7ac27de2f0c4   13 months ago   12MB
    openjdk                               17-oracle                          5e28ba2b4cdb   16 months ago   471MB
    tomcat                                jdk17-openjdk-slim                 89dbd4aee4c1   16 months ago   428MB
    tomcat                                9.0.58-jdk17-openjdk-slim          dfad3c1ccda1   19 months ago   428MB
    jboss/keycloak                        latest                             011a708d97bf   19 months ago   759MB
    openjdk                               17-jdk-alpine                      264c9bdce361   2 years ago     326MB
    nicolasduminil/openjdk11-with-tools   latest                             51d95b93878f   3 years ago     457MB
    adoptopenjdk                          8u212-b04-jre-hotspot-bionic       47d41d0c85ce   4 years ago     200MB
    tomcat                                9.0.21-jdk8-adoptopenjdk-hotspot   f14542de9331   4 years ago     326MB
    oracleinanutshell/oracle-xe-11g       latest                             ad13c30ec346   4 years ago     2.13GB
    tutum/tomcat                          latest                             2edd730bbedd   8 years ago     540MB

My conclusion is that podman isn't able to recognize any of the docker images above. So the reason that prevented the `podman create ...` command to work wasn't that it needed another tag but that podman was unable to "see" the mentioned image locally and wanted to pull it from the registry. Should podman have been able to "see" these docker images, it wouldn't have needed neither to configure the registry, nor to create another tag.

So I don't know why the result of the two commands, `docker images` and `podman images` is so different but, in my opinion, this isn't normal and, by itself, it's a very good reason to  avoid using podman and to continue with docker.

**Comment by vrothberg** [comment]
@nicolasduminil, Podman and Docker do not share the local storage.  It seems like you pulled `swaggerapi/swagger-ui` via Docker.  If you want to use it with Podman, you need to pull it with Podman.
