### ISSUE TITLE
Old containers/podman quay tags are not available 

### ISSUE THREAD

**Issue by itsLucario** [containers/podman#19842]
### Issue Description

I see only some of the tags are recreated after issue #19799 
I still don't see some of the old tags recreated. Example 4.5.0.

Can I know what's the ETA for this?
<img width="789" alt="image" src="https://github.com/containers/podman/assets/20811782/a755a926-0620-4d72-82ba-afb8fc2f8956">

### Steps to reproduce the issue

https://quay.io/repository/containers/podman?tab=history

### Describe the results you received

NA

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
NA
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by vrothberg** [comment]
Thanks for reaching out, @cevich PTAL

**Comment by baude** [comment]
@cevich can we put a priority on this for our users?

**Comment by cevich** [comment]
Please follow [the current status on the discussion](https://github.com/containers/podman/discussions/19796).  Specifically, there are so many old tags, I need a script to do the (fairly complex) validation process.  That's in progress now and is my top priority (in addition to watching for related issues :wink:).
