### ISSUE TITLE
[MacOS] inotify instance limit reached

### ISSUE THREAD

**Issue by valeriano-manassero** [containers/podman#19848]
### Discussed in https://github.com/containers/podman/discussions/19847

<div type='discussions-op-text'>

<sup>Originally posted by **valeriano-manassero** September  4, 2023</sup>
This happens a lot on my dev instances especially using `kind` clusters.

It's pretty easy to solve it doing `podman machine ssh` and then `echo fs.inotify.max_user_instances=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p`

There's a way to force this setup in vm by podman itself during `init`?</div>

**Comment by giuseppe** [comment]
opened a PR: https://github.com/containers/podman/pull/19849

**Comment by afbjorklund** [comment]
Known issue with kind: https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files
