### ISSUE TITLE
support `--dns` in Quadlet

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#19884]
### Feature request description

At the time of writing, Quadlet does not support the `--dns` flag in form of a field.

Noticed while reviewing a blog post that is resorting to `PodmanArgs=--dns=...`.

### Suggest potential solution

Add a `DNS` field to `.container` filees.

### Have you considered any alternatives?

`PodmanArgs` is a work around but not idiomatic.

### Additional context

Cc: @ygalblum @rhatdan

**Comment by ryanhockstad** [comment]
I can work on this issue. Could someone set the 'in progress' label?

**Comment by rhatdan** [comment]
You got it.

**Comment by rhatdan** [comment]
If you do this, you should add --dns-option, --dns-search as well as --dns

**Comment by ryanhockstad** [comment]
Thanks. Just opened a PR [here](https://github.com/containers/podman/pull/19958)
