### ISSUE TITLE
Podman rm (--force) does not work anymore ("container state improper"/"invalid argument" when unmounting) and start neither

### ISSUE THREAD

**Issue by rugk** [containers/podman#19913]
### Issue Description

**Describe the bug**
Somehow I get the error:
> Error: container "nextcloud_[…]" is mounted and cannot be removed without using force: container state improper

…when trying to remove containers.

### Steps to reproduce the issue

```
$ podman-compose -p nextcloud down
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.6.1
** excluding:  set()
podman stop -t 10 nextcloud_caddy_1
Error: no container with name or ID "nextcloud_caddy_1" found: no such container
exit code: 125
podman stop -t 10 nextcloud_cron_1
Error: no container with name or ID "nextcloud_cron_1" found: no such container
exit code: 125
podman stop -t 10 nextcloud_nc_1
Error: no container with name or ID "nextcloud_nc_1" found: no such container
exit code: 125
podman stop -t 10 nextcloud_db_1
Error: no container with name or ID "nextcloud_db_1" found: no such container
exit code: 125
podman stop -t 10 nextcloud_redis_1
Error: no container with name or ID "nextcloud_redis_1" found: no such container
exit code: 125
podman rm nextcloud_caddy_1
Error: no container with ID or name "nextcloud_caddy_1" found: no such container
exit code: 1
podman rm nextcloud_cron_1
Error: no container with ID or name "nextcloud_cron_1" found: no such container
exit code: 1
podman rm nextcloud_nc_1
Error: container "nextcloud_nc_1" is mounted and cannot be removed without using force: container state improper
exit code: 2
podman rm nextcloud_db_1
Error: container "nextcloud_db_1" is mounted and cannot be removed without using force: container state improper
exit code: 2
podman rm nextcloud_redis_1
Error: container "nextcloud_redis_1" is mounted and cannot be removed without using force: container state improper
exit code: 2
$ podman rm nextcloud_db_1
Error: container "nextcloud_db_1" is mounted and cannot be removed without using force: container state improper
```

When trying to start the container I get this error then:
```
$ podman-compose --in-pod=0 -p nextcloud up -d
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.6.1
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=nextcloud', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
podman pod create --name=pod_nextcloud --infra=false --share=
Error: adding pod to state: name "pod_nextcloud" is in use: pod already exists
exit code: 125
[…]
Error: creating container storage: the container name "nextcloud_redis_1" is already in use by 4dbd88724af1ee89d859c6b2dfebb89f95cf6358503e09a8763009877a4830cb. You have to remove that container to be able to reuse that name: that name is already in use
exit code: 125
podman start nextcloud_redis_1
Error: no container with name or ID "nextcloud_redis_1" found: no such container
exit code: 125
[…]
Error: creating container storage: the container name "nextcloud_db_1" is already in use by 2760fa4a652ba952ef5270d256c658dd3f4455d96fe7554abdb13bbfbdbd6c19. You have to remove that container to be able to reuse that name: that name is already in use
exit code: 125
podman start nextcloud_db_1
Error: no container with name or ID "nextcloud_db_1" found: no such container
exit code: 125
[…]
```

Then there are dependency errors depending on the mentioned containers to start.

The thing is I see nothing of that running?
```
$ podman ps -a
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
$ podman pod ls
POD ID        NAME           STATUS      CREATED      INFRA ID    # OF CONTAINERS
562b052bdab9  pod_nextcloud  Created     4 hours ago              0
```

Also the container that is said to use the name, is not there?
```
$ podman inspect 4dbd88724af1ee89d859c6b2dfebb89f95cf6358503e09a8763009877a4830cb
[]
Error: no such object: "4dbd88724af1ee89d859c6b2dfebb89f95cf6358503e09a8763009877a4830cb"
```

I can remove the pod, but it does not help:
```
$ podman pod rm pod_nextcloud 
562b052bdab9c31692403405579935979a7026f1945bbc0eb0f1594a2b80b546
$ podman inspect nextcloud_db_1
[]
Error: no such object: "nextcloud_db_1"
```

### Describe the results you received

I cannot stop or start the containers.

### Describe the results you expected

I should somehow be able to force/fix that. I have no idea what is "improper" nor how to fix it. 

### podman info output

```yaml
$ podman-compose version
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.6.1
podman-compose version 1.0.6
podman --version 
podman version 4.6.1
exit code: 0
$ podman version
Client:       Podman Engine
Version:      4.6.1
API Version:  4.6.1
Go Version:   go1.20.7
Built:        Fri Aug 11 00:07:53 2023
OS/Arch:      linux/amd64
$ podman info
host:
  arch: amd64
  buildahVersion: 1.31.2
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc38.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 98.31
    systemPercent: 0.82
    userPercent: 0.86
  cpus: 4
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: coreos
    version: "38"
  eventLogger: journald
  freeLocks: 615
  hostname: minipure
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
  kernel: 6.4.7-200.fc38.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 60165713920
  memTotal: 67283185664
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.7.0-1.fc38.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.7.0
    package: netavark-1.7.0-1.fc38.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.7.0
  ociRuntime:
    name: crun
    package: crun-1.8.6-1.fc38.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.6
      commit: 73f759f4a39769f60990e7d225f561b4f4f06bcf
      rundir: /run/user/1002/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20230625.g32660ce-1.fc38.x86_64
    version: |
      pasta 0^20230625.g32660ce-1.fc38.x86_64
      Copyright Red Hat
      GNU Affero GPL version 3 or later <https://www.gnu.org/licenses/agpl-3.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    path: /run/user/1002/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-12.fc38.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 4h 27m 21.00s (Approximately 0.17 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /var/home/****/.config/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 4
    stopped: 2
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/****/.local/share/containers/storage
  graphRootAllocated: 999650168832
  graphRootUsed: 46548176896
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 12
  runRoot: /run/user/1002/containers
  transientStore: false
  volumePath: /var/home/****/.local/share/containers/storage/volumes
version:
  APIVersion: 4.6.1
  Built: 1691705273
  BuiltTime: Fri Aug 11 00:07:53 2023
  GitCommit: ""
  GoVersion: go1.20.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.1
$ rpm -q podman
podman-4.6.1-1.fc38.x86_64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes kinda

### Additional environment details

 - OS: Linux Fedora CoreOS v38.20230819.3.0
 -  podman version: 4.6.1
 - podman compose version: (git hex) 1.0.6

### Additional information

Docker-compose v'3.7' – exact same YAML started before without any problems.

I tested [the echo example here](https://github.com/containers/podman-compose/tree/devel/examples/echo) and it did work, I have no idea what's wrong.

Cross-posted as https://github.com/containers/podman-compose/issues/767 and https://github.com/coreos/fedora-coreos-tracker/issues/1572

**Comment by Luap99** [comment]
Did you try to remove them with `podman rm --force`?

**Comment by baude** [comment]
the nuclear option might be `system reset` if you don't have anything you want to retain.

**Comment by rhatdan** [comment]
This issue is not similar ,please open a different issue. or discussion

**Comment by rugk** [comment]
> Did you try to remove them with podman rm --force?

```
$ podman rm --force nextcloud_db_1
WARN[0000] Unmounting container "nextcloud_db_1" while attempting to delete storage: unmounting "/var/home/****/.local/share/containers/storage/overlay/e655542583cc8bbc943e354a5b441bfb3df598e1cc88a0fa5b6ade002d533263/merged": invalid argument 
Error: removing storage for container "nextcloud_db_1": unmounting "/var/home/****/.local/share/containers/storage/overlay/e655542583cc8bbc943e354a5b441bfb3df598e1cc88a0fa5b6ade002d533263/merged": invalid argument
$ podman rm --force nextcloud_redis_1
WARN[0000] Unmounting container "nextcloud_redis_1" while attempting to delete storage: unmounting "/var/home/****/.local/share/containers/storage/overlay/7ae38929f1fb15eeef60eef63118a0d71ac386260bff82e17beb24c12127bd87/merged": invalid argument 
Error: removing storage for container "nextcloud_redis_1": unmounting "/var/home/****/.local/share/containers/storage/overlay/7ae38929f1fb15eeef60eef63118a0d71ac386260bff82e17beb24c12127bd87/merged": invalid argument
$ podman rm --force nextcloud_nc_1
WARN[0000] Unmounting container "nextcloud_nc_1" while attempting to delete storage: unmounting "/var/home/****/.local/share/containers/storage/overlay/3989bcb8ce368e6b0a2bb98fa3fa6033edb16e0d5541ed37077b603101cc113e/merged": invalid argument 
Error: removing storage for container "nextcloud_nc_1": unmounting "/var/home/****/.local/share/containers/storage/overlay/3989bcb8ce368e6b0a2bb98fa3fa6033edb16e0d5541ed37077b603101cc113e/merged": invalid argument
```

> nuclear option might be system reset if you don't have anything you want to retain.

Uhm I _do_ like to retain container volumes :eyes:

**Comment by Luap99** [comment]
run `podman unshare mount -t tmps none <path from the error message>`  then try podman rm --force again, this should work to delete the storage container.

**Comment by rugk** [comment]
```
$ $ podman rm --force nextcloud_nc_1
WARN[0000] Unmounting container "nextcloud_nc_1" while attempting to delete storage: unmounting "/var/home/****/.local/share/containers/storage/overlay/3989bcb8ce368e6b0a2bb98fa3fa6033edb16e0d5541ed37077b603101cc113e/merged": invalid argument 
Error: removing storage for container "nextcloud_nc_1": unmounting "/var/home/****/.local/share/containers/storage/overlay/3989bcb8ce368e6b0a2bb98fa3fa6033edb16e0d5541ed37077b603101cc113e/merged": invalid argument
$ podman unshare mount -t tmps none /var/home/****/.local/share/containers/storage/overlay/3989bcb8ce368e6b0a2bb98fa3fa6033edb16e0d5541ed37077b603101cc113e/merged
mount: /var/home/****/.local/share/containers/storage/overlay/3989bcb8ce368e6b0a2bb98fa3fa6033edb16e0d5541ed37077b603101cc113e/merged: unknown filesystem type 'tmps'.
       dmesg(1) may have more information after failed mount system call.
```

I ran `dmesg`, but did not see something related. Note I run everything without sudo/root rights as this is rootless podman.
Also note the error has survived a reboot before, so I have no idea what's wrong.

**Comment by rugk** [comment]
Ahhh you probably meant `podman unshare mount -t tmpfs none` i.e. `tmpfs` instead of `tmps`. Typos…

This worked and `podman rm --force nextcloud_nc_1` also worked afterwards. Woow…

Thaat works, thanks a lot!

Anyway, I assume this should have never happened, also that like three commands that usually help did not help is bad IMHO: Not a good experience, whatever went wrong here…

**Comment by rugk** [comment]
As you saw I executed the commands, though the container state was still “improper” afterwards. Anyway, after rebooting I executed `podman ps` and it takes ages to finish, but this is usual for me and has happened a lot of times…

I'll see whether it works later maybe.

**Comment by rugk** [comment]
Okay so after a reboot (which also starts/tries to start all containers I have to say) it first seemed to work (workaround worked for removing redis worked, but failed for the DB (MariaDB) container again due to the directory not being empty.

In the end I could "solve" the issue by deleting the directory it mentions respectively just renaming it (to have a backup, just in case), then the container could be removed.

Anyway, this workaround just got even harder and I have no clue what the root case is.

**Comment by rugk** [comment]
Aaand had it again. Could it be related to increased disk I/P (have stuff running in my Nextcloud now) or maybe DB connections? (I frequently have [DB timeout issues like these](https://serverfault.com/questions/908563/mariadb-10-2-14-got-timeout-reading-communication-packets)). But this thing is new here…

Could fix it again, but this is annoying.

---

Frustrated I [asked ChatGPT to automate this](https://chat.openai.com/share/84a60de8-3492-4572-8e8f-5a85d2d96607) and it also gave me more hints to check stuff:

It seems like you're facing issues with removing containers in Podman due to "container state improper" errors. This can be a frustrating problem, but let's try to address it.

First, it's important to note that these issues might be specific to your environment or the specific containers you're running. However, there are some general troubleshooting steps you can take:

1. **Check for Zombie Containers:**
   Sometimes, containers might not have completely exited and could be in a "zombie" state. You can check for such containers using:
   
   ```
   podman ps -a --filter "status=exited"
   ```

   If you see any containers in this state, you can try to remove them using `podman rm` with the `--force` flag.

2. **Manually Unmount Overlay Filesystem:**
   It appears that the issue is related to unmounting overlay filesystems. You can try manually unmounting these filesystems using the `podman unshare` command. For example:

   ```
   podman unshare mount -t tmpfs none /var/home/****/.local/share/containers/storage/overlay/3989bcb8ce368e6b0a2bb98fa3fa6033edb16e0d5541ed37077b603101cc113e/merged
   ```

   After doing this for the problematic containers, try running `podman rm --force` again.

3. **Check for Disk Space:**
   Ensure that you have enough disk space available on your system. If your storage is running low, it can lead to issues with container management.

4. **Podman and Kernel Version Compatibility:**
   Sometimes, issues like these can be related to compatibility between Podman and the Linux kernel. Ensure that you are using a compatible version of Podman with your kernel.

5. **Podman and Systemd Service:**
   It seems you have systemd service files for your containers. Check the status of these services to see if they are running or stopped:

   ```
   sudo service podman status
   ```

   If there are any issues with the Podman service itself, it might affect container management.

6. **Logs and Debugging:**
   Check the logs for Podman and your containers for any error messages or clues about what might be causing the issue. You can use `journalctl` to view Podman's logs:

   ```
   journalctl -u podman.service
   ```

   Additionally, inspect the container logs:

   ```
   podman logs <container_name_or_id>
   ```

Remember that forcefully removing containers can lead to data loss, so make sure you understand the consequences before proceeding.

----

When asked again it [also gave me a workaround shell script to automate the manual unshare etc. steps](https://gist.github.com/rugk/aab9539f689962ed8ff78ec5b5c94918). While cumbersome, I may try this the next time this happens and report back whether it works.

**Comment by Luap99** [comment]
Please update to 4.7 and see if you can reproduce there.

**Comment by rhatdan** [comment]
We believe this is fixed in current version.
