### ISSUE TITLE
Windows: Podman without admin rights cannot create \\.\pipe\docker_engine for Docker API

### ISSUE THREAD

**Issue by MastermindPanda** [containers/podman#19919]
### Issue Description

I want to use Podman under Windows, without admin rights.

As stated in a previous [Issue #17232](https://github.com/containers/podman/issues/17232#issuecomment-1405571778), this should be possible. (WSL is installed beforehand).

However, when executing as a normal user, an error message appears that API forwarding failed to start:
````
API forwarding for Docker API clients is not available due to the following startup failures.
        CreateFile \\.\pipe\docker_engine: Das System kann die angegebene Datei nicht finden.
````

### Steps to reproduce the issue

Steps to reproduce the issue
1. Install podman (4.6.2 podman-remote-release-windows_amd64.zip)
2. Initialise podman machine ``podman machine init``
3. Start podman machine ``podman machine start``

### Describe the results you received

When executing in elevated PowerShell:

```
PS > podman machine start
Starting machine "podman-machine-default"

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

        podman machine set --rootful

API forwarding listening on: npipe:////./pipe/docker_engine

Docker API clients default to this address. You do not need to set DOCKER_HOST.
Machine "podman-machine-default" started successfully
```

When executing as a normal user

````
PS > podman machine start
Starting machine "podman-machine-default"

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

        podman machine set --rootful

API forwarding for Docker API clients is not available due to the following startup failures.
        CreateFile \\.\pipe\docker_engine: Das System kann die angegebene Datei nicht finden.

Podman clients are still able to connect.
Machine "podman-machine-default" started successfully
````

### Describe the results you expected

Docker API can also be used when using podman without admin rights.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.31.2
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.7-2.fc38.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 99.95
    systemPercent: 0.03
    userPercent: 0.02
  cpus: 8
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: container
    version: "38"
  eventLogger: journald
  freeLocks: 2048
  hostname: ET0451
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 5.15.90.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 15666745344
  memTotal: 16609374208
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.7.0-1.fc38.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.7.0
    package: netavark-1.7.0-1.fc38.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.7.0
  ociRuntime:
    name: crun
    package: crun-1.9-1.fc38.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.9
      commit: a538ac4ea1ff319bcfe2bf81cb5c6f687e2dc9d3
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20230908.g05627dc-1.fc38.x86_64
    version: |
      pasta 0^20230908.g05627dc-1.fc38.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP
_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.1-1.fc38.x86_64
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 4294967296
  swapTotal: 4294967296
  uptime: 3h 11m 3.00s (Approximately 0.12 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 923586560
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 4.6.2
  Built: 1693251588
  BuiltTime: Mon Aug 28 21:39:48 2023
  GitCommit: ""
  GoVersion: go1.20.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.2
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Windows 10

### Additional information

None

**Comment by MastermindPanda** [comment]
I did some digging myself, but beware, I am not really firm with Windows programming.

It seems that podman machine uses ``win-sshproxy.exe`` for the named pipe: [function launchWinProxy](https://github.com/containers/podman/blob/18561f26adf94a97ffeec9fb7f6de9ec4ccaea57/pkg/machine/wsl/machine.go#L1260C14-L1260C14)

The ssh proxy seems to be the [gvisor-tap-vsock](https://github.com/containers/gvisor-tap-vsock/tree/f93fe269e82f603d130df62ab862ee59b4ecce9a) repo.

There, some Windows magic is happening with [access rights](https://github.com/containers/gvisor-tap-vsock/blob/f93fe269e82f603d130df62ab862ee59b4ecce9a/pkg/sshclient/npipe_windows.go#L17C33-L17C60)
```
const SddlDevObjSysAllAdmAll = "D:P(A;;GA;;;SY)(A;;GA;;;BA)"
```

From what I gathered, [finally ](https://github.com/microsoft/go-winio/blob/e6aebd619a7278545b11188a0e21babea6b94182/pipe.go#L376C8-L376C29 )the Windows API function ``ntCreateNamedPipeFile`` is called.

The [documentation](https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/sddl-for-device-objects) states:
```
SDDL_DEVOBJ_SYS_ALL_ADM_ALL

"D:P(A;;GA;;;SY)(A;;GA;;;BA)"

SDDL_DEVOBJ_SYS_ALL_ADM_ALL allows the kernel, system, and administrator complete control over the device. No other users may access the device.
```

So it would makes sense, that as a normal user a pipe with these access rights cannot be created?

However, I don't now why those parameters where chosen and if other parameters would work as well.

**Comment by n1hility** [comment]
@MastermindPanda you shouldn't need admin perms to create a named pipe. After starting and you receive that error do you still see the pipe with the following powershell command?:

`dir \\.\pipe\ | Where-Object Name -Match docker_engine`

When the pipe is created it grants full access to the system as well as your user, so your user should be able to access and connect to it (unless some sort of group policy or other restriction is somehow preventing them). The element that is generating the failure is on the connection side though, however there is a short lived polling action, so I am just curious if it exists and is spurious.

**Comment by MastermindPanda** [comment]
@n1hility thanks for taking a look. It seems you're right, the named pipe seems to be made eventually. I had to run the command a few times until it popped up.

`PS C:\Windows\system32> podman machine start
Starting machine "podman-machine-default"

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

        podman machine set --rootful

API forwarding for Docker API clients is not available due to the following startup failures.
        CreateFile \\.\pipe\docker_engine: Das System kann die angegebene Datei nicht finden.

Podman clients are still able to connect.
Machine "podman-machine-default" started successfully
PS C:\Windows\system32> dir \\.\pipe\ | Where-Object Name -Match docker_engine
PS C:\Windows\system32> dir \\.\pipe\ | Where-Object Name -Match docker_engine
PS C:\Windows\system32> dir \\.\pipe\ | Where-Object Name -Match docker_engine
PS C:\Windows\system32> dir \\.\pipe\ | Where-Object Name -Match docker_engine


    Verzeichnis: \\.\pipe


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
------        01.01.1601     01:00              2 docker_engine

PS C:\Windows\system32> $Env:DOCKER_HOST = "npipe:////./pipe/docker_engine"
PS C:\Windows\system32> docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
PS C:\Windows\system32> podman machine stop
Machine "podman-machine-default" stopped successfully
PS C:\Windows\system32> docker ps
error during connect: this error may indicate that the docker daemon is not running: Get "http://
%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: Das System ka
nn die angegebene Datei nicht finden.`

**Comment by n1hility** [comment]
@MastermindPanda thanks for checking!

Could you also try running the following as a powershell script (for admin and not admin) after making sure podman is shutdown (podman machine stop)? I am curious how long of a delay you are seeing, and if there is a variations between admin and not admin. Thanks!

```powershell
podman machine start
Write-Host "Waiting for docker_engine..."
Measure-Command {
$sock = "\\.\pipe\docker_engine"
$exists = test-path  $sock
while (!$exists) {
   $exists = test-path $sock
   Start-Sleep -Milliseconds 100
}
Write-Host "Found docker_engine!"
}
podman machine stop
```

**Comment by MastermindPanda** [comment]
@n1hility unfortunately I cannot reproduce any more. Not sure what changed, but my machine is also remotely managed, so I don't know what (e.g. Windows) updates were pushed.

Even without admin rights, the script runs in approx. 45 ms.

```
Starting machine "podman-machine-default"

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

        podman machine set --rootful

API forwarding listening on: npipe:////./pipe/docker_engine

Docker API clients default to this address. You do not need to set DOCKER_HOST.
Machine "podman-machine-default" started successfully
Waiting for docker_engine...
Found docker_engine!


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 46
Ticks             : 460324
TotalDays         : 5.32782407407407E-07
TotalHours        : 1.27867777777778E-05
TotalMinutes      : 0.000767206666666667
TotalSeconds      : 0.0460324
TotalMilliseconds : 46.0324

Machine "podman-machine-default" stopped successfully
```
Not sure if this could be a result of a check the anti virus software does and delays the creation of the named pipe? (If anti virus software even checks pipes...)

How to proceed? Close this ticket?
I will keep an eye out and will reopen this ticket (or create a new one) if it happens again, starting with providing the timing you requested?

**Comment by MastermindPanda** [comment]
@n1hility I think this is a problem specific to my machine. Today the problem does appear again, so I can provide you with a measurement.

I want to point out, that after the printing of ``podman machine set --rootful`` it already takes some time to continue. This was not the case two days ago. So I guess there is already some kind of blocking method waiting for the pipe to be created.

```
Starting machine "podman-machine-default"

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

        podman machine set --rootful

API forwarding for Docker API clients is not available due to the following startup failures.
        CreateFile \\.\pipe\docker_engine: Das System kann die angegebene Datei nicht finden.

Podman clients are still able to connect.
Machine "podman-machine-default" started successfully
Waiting for docker_engine...
Found docker_engine!


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 21
Milliseconds      : 680
Ticks             : 216802527
TotalDays         : 0.000250928850694444
TotalHours        : 0.00602229241666667
TotalMinutes      : 0.361337545
TotalSeconds      : 21.6802527
TotalMilliseconds : 21680.2527

Machine "podman-machine-default" stopped successfully
```

**Comment by n1hility** [comment]
Thanks @MastermindPanda this is helpful. That does seem like a significant delay. I agree that this is likely system specific. My best guess would be your system is actively being scanned by some virus/malware agent, is undergoing updates, or is being monopolized by some other system activity. However, I will look into whether the handling could be a little more robust or at least better informing of the problem. I will close this particular issue out for now since we ruled out a permission bug, but thank you for opening it and sharing all these details.
