### ISSUE TITLE
Podman is extremely slow while pulling image on windows 10

### ISSUE THREAD

**Issue by ravindrakmr** [containers/podman#19928]
### Issue Description

When try to pull an image from a registry (e.g. JFrog), podman takes lot of time in copying blob steps.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Run init command - podman machine init --cpus 2 --memory 2048 --disk-size 20 --user-mode-networking
2. podman machine set --rootful
3. podman machine start

### Describe the results you received

time="2023-09-11T22:02:32+05:30" level=info msg="podman filtering at log level debug"
time="2023-09-11T22:02:32+05:30" level=debug msg="Called pull.PersistentPreRunE(podman pull myjfrog.com/docker/java/openjdk:jre17.0.4_8 --log-level debug)"
time="2023-09-11T22:02:32+05:30" level=debug msg="SSH Ident Key \"C:\\\\Users\\\\rrkumar\\\\.ssh\\\\podman-machine-default\" SHA256:epPWo9+sA7PwtPdRtEKVdyywgIAp5E3BerAxxQ+Mqrw ssh-ed25519"
time="2023-09-11T22:02:32+05:30" level=debug msg="DoRequest Method: GET URI: http://d/v4.6.2/libpod/_ping"
time="2023-09-11T22:02:32+05:30" level=debug msg="Loading registries configuration \"/etc/containers/registries.conf\""
time="2023-09-11T22:02:32+05:30" level=debug msg="DoRequest Method: POST URI: http://d/v4.6.2/libpod/images/pull"
Trying to pull myjfrog.com/docker/java/openjdk:jre17.0.4_8...
Getting image source signatures
Copying blob sha256:7a2074752f177d6532619a7ba0ecb328c1c6546336042d0a38cddd2d49202d22
Copying blob sha256:449310293efe8a083c71ff76b4d299795d6e34f15a6ec9e552d3e4e291d9ab98
Copying blob sha256:f5194575274b78319a1324f1e1fe48ed1ba558e2aca06971a4e64734e195048a
Copying blob sha256:aef53af80d18d2b0e131b0dea9f3010b7db77d3cfbc6f2ec0392142e8d87855f
Copying blob sha256:06d39c85623a79eb68b6cac39f4c4aba8834873ee5fc27be9d9d7655e6313c26
Copying blob sha256:4825b8c9226b54499e8b33b1ce2dd9fd09a8ca2cd19edc6413dd7f668df980c4
Copying blob sha256:a67b7185fb8d97c666db8f9b2defac7a86e1768dab298ca8a2f92cb8c7db5892
Copying blob sha256:80f7a13a9172f38bb0dd40b05cae17453096d68e38b323d3a2340372eed2c900
Copying blob sha256:71623a8373ecb5bea1c6b9ca926f1708a9ef323366de8b8fcb982427dfc92029
Copying blob sha256:cee1c860570e62f9a529655291dc76650b1e30c56fe82c4bb41d31a227a39479
Copying blob sha256:cbbff8901fcdff2b782fd6dc72dacf5009ffe28456dabea6243e71628eb350fc
Copying blob sha256:180003349f3572c48c338c13d9580a3a1ee261046073ebd05f34b35a91d06184
(stuck here..........)

### Describe the results you expected

It should not stuck on copying blob steps for long time. 

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.31.2
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.7-2.fc38.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 99.62
    systemPercent: 0.25
    userPercent: 0.13
  cpus: 8
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: container
    version: "38"
  eventLogger: journald
  freeLocks: 2048
  hostname: PUNLT0101812
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.90.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 7525101568
  memTotal: 8151564288
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.7.0-1.fc38.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.7.0
    package: netavark-1.7.0-1.fc38.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.7.0
  ociRuntime:
    name: crun
    package: crun-1.9-1.fc38.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.9
      commit: a538ac4ea1ff319bcfe2bf81cb5c6f687e2dc9d3
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20230908.g05627dc-1.fc38.x86_64
    version: |
      pasta 0^20230908.g05627dc-1.fc38.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.1-1.fc38.x86_64
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 2147483648
  swapTotal: 2147483648
  uptime: 0h 22m 47.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 935837696
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.6.2
  Built: 1693251588
  BuiltTime: Tue Aug 29 01:09:48 2023
  GitCommit: ""
  GoVersion: go1.20.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.2
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Windows 10 Pro 22H2
4 Core, 16GB RAM
wsl --version
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3208

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rhatdan** [comment]
@mtrmac @vrothberg PTAL
Could this be a network setup issue?

**Comment by mtrmac** [comment]
There’s literally nothing to go on here. What is the image, or at least its characteristics? Which aspect of the VM (CPU, memory, swap, disk I/O, network) is under load?

This requires generic Linux performance tuning expertise / documentation, first.

**Comment by vrothberg** [comment]
Thanks, @ravindrakmr.  I think we can close the issue since it's not related to Podman but the VPN.
