### ISSUE TITLE
Add Intel RDT support

### ISSUE THREAD

**Issue by wpross** [containers/podman#19922]
### Feature request description

When running a container, I would love be able to use the Cache Allocation Technology (CAT) feature that is part of the Intel Resource Director Technology (RDT) feature set. It is already integrated into the [OCI runtime spec](https://github.com/opencontainers/runtime-spec/blob/main/config-linux.md#intelrdt) and [runc](https://github.com/opencontainers/runc/pull/2920) and is based on the [resctrl](https://docs.kernel.org/arch/x86/resctrl.html) kernel driver. 

`Resctrl` enables a user to interact with registers that specify the RDT behaviour based on a pseudo-file system mounted at `/sys/fs/resctrl`. By e.g. writing the PID of a container to a subfolders' `tasks` file, `runc` enables the container to use the cache-ways defined within the `bitmask` within the `schemata` file in this subfolder. the subfolder's name is the name of the `Class of service (CLOS)`. `runc` gets the CLOS name (or `closID`) from the `intelRDT` section within the Linux Container specification, for example

```yaml
"linux": {
    "intelRdt": {
        "closID": "myClos",
    }
}
```

`myClos` would be the name of the CLOS, so a subfolder within `/sys/fs/resctrl`.
 

### Suggest potential solution

Add a flag, similar to the one in [nerdctrl](https://github.com/containerd/nerdctl/blob/main/docs/command-reference.md?plain=1#L212) or [ctr](https://github.com/containerd/containerd/blob/main/cmd/ctr/commands/run/run_unix.go#L399), e.g. `--rdt-class=myClos` that is then added to the OCI spec's `linux` section to look like in the above example.

### Additional context

Intel RDT is only supported in `runc` so far. So the default runtime `crun` does not support it so far. However, I will also open an issue to support RDT in `crun`.

**Comment by baude** [comment]
care to submit a PR?

**Comment by giuseppe** [comment]
I can take a look from the crun side, but I lack the hardware to test it (and that is the main reason why crun doesn't implement it yet).

Is it possible to enable the feature under qemu?

**Comment by rhatdan** [comment]
@wpross Care to open a PR to add support?

**Comment by wpross** [comment]
@rhatdan I will add a PR for Podman soon.

**Comment by wpross** [comment]
> I can take a look from the crun side, but I lack the hardware to test it (and that is the main reason why crun doesn't implement it yet).

I could test it on my side if I get access to the changes

**Comment by wpross** [comment]
unfortunately I can't set the "In Progress" label myself. Can someone help with it?
