### ISSUE TITLE
commit: no progress messages when remote

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#19947]
`podman commit` does not emit user-visible progress messages:
```console
$ podman run --name c quay.io/libpod/testimage:20221018 true 
$ bin/podman-remote commit c i-remote
66564a71395dbe909d6945363ab0a8b6f1f25141f83239a396fdcc988692b51b
```
Expected (on stderr):
```
Getting image source signatures
Copying blob 7b378ec3d3ca skipped: already exists  
Copying blob 5f70bf18a086 skipped: already exists  
Copying blob 0e7e062a6ade done   | 
Copying config 66564a7139 done   | 
Writing manifest to image destination
```
These messages are displayed on the server end, which is not seen by humans.

`podman pull` manages to emit its "Trying to pull... Getting image source signatures ... Writing manifest" messages to the client's stderr, so this is not technically impossible. Maybe it's technically hard, and I'm okay with closing EWONTFIX, but I want it to be a deliberate, documented decision.

**Comment by rhatdan** [comment]
Yes I agree these messages should be sent over the the client side if at all possible.

**Comment by edsantiago** [comment]
Same with `podman import`. See https://github.com/containers/podman/pull/19959/files#diff-c4858c0a8003da090874c5e9929508e55c6a650085baa6879b46f4b26f1ec1d1
