### ISSUE TITLE
issue for "apt-get install podman"

### ISSUE THREAD

**Issue by Test45o** [containers/podman#19942]
### Issue Description

Good morning

I created an artificialory repo that points to this url: https://download.opensuse.org/

It works really well, when I do a curl on the repo to retrieve the Release.key through the repo it works well too

However, when I try to do an "apt-get update" I get an error on the repo in question:

http://link_repo/dists/focal/main/binary-amd64/Packages 404 not found
E: Failed to download some index files. They were ignored or old ones were used instead.

Here is my source.list file

deb [trusted=yes] https://login:password@link_repo/artifactory/name_repo/ focal main

do you have an idea ?

Thanks in advance

### Steps to reproduce the issue

Steps to reproduce the issue
1.
2.
3.

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by giuseppe** [comment]
If I understand correctly, you are having an issue with the rpm repo you've created on opensuse.org. In this case I suggest asking on a SUSE related forum.  This is not an issue affecting upstream podman development.

**Comment by Test45o** [comment]
Hello @giuseppe 

Thank for your answer it's not issue for rpm i'm in ubuntu 22.04 i do this action in ubuntu 22.04
