### ISSUE TITLE
podman fails ungracefully if log destinations have no free space for writes

### ISSUE THREAD

**Issue by srcshelton** [containers/podman#19943]
### Issue Description

My filesystem setup is as follows, with a separate partition for `/var`, with '/var/run/libpod' (`tmp_dir`) and `/var/run/podman` (`runroot`) being `tmpfs` mounts overlaid:

```
/dev/md3 on /var type ext4
runtmpfs on /var/run type tmpfs
podman.runRoot on /var/run/podman type tmpfs
podman.libpod.runRoot on /var/run/libpod type tmpfs
```

… which means, so far as I can tell, that the only cases where `podman` accesses the actual `/var` partition filesystem is for event- and general- logging (with containerised services also logging to `/var/log/<service>/podman-<service>.log` - but even this is only by running `podman` via `start-stop-daemon` and using SSD's `--stdout` and `--stderr` options to redirect container output to the specified files).

However, if the `/var` partition ever runs out of space then `podman` does not respond gracefully: many running containers will change to status `Stopping`, but will not actually stop - the only way to clean them up is to use `rm -f`, and sometimes having resolved the space issues, removing the initial round of zombie containers then leads to a second set also suddenly changing to `Stopping` but being stuck.

(This could be some combinatorial behaviour with `start-stop-daemon`, in cases where the `stdout` and `stderr` buffers aren't being drained?)

### Steps to reproduce the issue

1. Have `podman` run containers with `events_logfile_path`/`--log-opt path` set to a location on a given filesystem and `stdout`/`stderr` streams connected via another process to the same filesystem;
2. Have said filesystem run out of free space (without impacting `podman`'s internal data in `run/podman`);
3. Notice that containers fail and set stuck with status `Stopping`.

### Describe the results you received

Random containers will be killed-off but `podman` will still show them as having `Stopping` status - but in an invalid state where neither `podman container stop` nor `podman container rm` succeeds, and so a manual `podman container rm -f` is required to reset the state in order to start a new container with the same name - there is no `podman`-initiated auto-recovery.

### Describe the results you expected

Out-of-space issues are clearly a system-management failure, it would be ideal if `podman` could either:

1) Continue running (… and buffer log messages in memory if practical?), but ultimately continue running containers whilst dropping log messages until it can again write them to the filesystem; or

2) If being unable to write logs is intentionally classified as a fatal error, then gracefully stop (or, ideally, pause!) containers so that they can be restored once the error condition is resolved.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.31.2
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: app-containers/conmon-2.1.8
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.1.8, commit: 00e08f4a9ca5420de733bf542b930ad58e1a7e7d'
  cpuUtilization:
    idlePercent: 95.69
    systemPercent: 1.88
    userPercent: 2.42
  cpus: 8
  databaseBackend: sqlite
  distribution:
    distribution: gentoo
    version: "2.14"
  eventLogger: file
  freeLocks: 2020
  hostname: dellr330
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.5.2-gentoo
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 32416481280
  memTotal: 67331043328
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: app-containers/aardvark-dns-1.7.0
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.7.0
    package: app-containers/netavark-1.7.0
    path: /usr/libexec/podman/netavark
    version: netavark 1.7.0
  ociRuntime:
    name: crun
    package: app-containers/crun-1.9
    path: /usr/bin/crun
    version: |-
      crun version 1.9
      commit: a538ac4ea1ff319bcfe2bf81cb5c6f687e2dc9d3
      rundir: /var/run/crun
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    path: unix://var/run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 42949652480
  swapTotal: 42949652480
  uptime: 9h 23m 10.00s (Approximately 0.38 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  localhost:5000:
    Blocked: false
    Insecure: true
    Location: localhost:5000
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: localhost:5000
    PullFromMirror: ""
  search:
  - docker.io
  - docker.pkg.github.com
  - quay.io
  - public.ecr.aws
  - registry.fedoraproject.org
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 26
    paused: 0
    running: 24
    stopped: 2
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /mnt/podman-storage
  graphRootAllocated: 2000397795328
  graphRootUsed: 73762693120
  graphStatus:
    Build Version: Btrfs v6.3.3
    Library Version: "102"
  imageCopyTmpDir: /var/tmp/.private/root
  imageStore:
    number: 120
  runRoot: /var/run/podman
  transientStore: false
  volumePath: /space/podman/volumes
version:
  APIVersion: 4.6.2
  Built: 1693253621
  BuiltTime: Mon Aug 28 21:13:41 2023
  GitCommit: 5db42e86862ef42c59304c38aa583732fd80f178
  GoVersion: go1.20.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.2

```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

**Comment by flouthoc** [comment]
Thanks for reporting I think this is a bug and podman should

*) Continue running (… and buffer log messages in memory if practical?), but ultimately continue running containers whilst dropping log messages until it can again write them to the filesystem.

But lets wait for other maintainers to see what they think.

**Comment by rhatdan** [comment]
conmon is doing the logging not Podman.

**Comment by srcshelton** [comment]
So sorry, should I re-raise this bug against conmon instead?

Please note that the content of the logging isn't the main problem here - it's the inconsistent state in which containers are left after this issue occurs, which I assume _is_ a podman issue?

**Comment by rhatdan** [comment]
@mheon Thoughts?

**Comment by mheon** [comment]
My educated guess is that Conmon is blowing up, but the containers it is monitoring are just fine - so Conmon dies because it can't log anymore, but the container process continues. Which, in a way, is worse than Conmon taking the container down with it, because we lose the ability to track container PID1, and are unable to clean up after the container.

The fixes will definitely need to be in Conmon if this is correct; Podman is broken, but Conmon misbehaving is the underlying cause. The question would be what to do in a logging-failed case; do we keep going without logs, or take the container down? Unfortunately Conmon doesn't have enough to do a safe shutdown of the container now (though this could be added).

**Comment by mheon** [comment]
Personally I lean towards shutting the container down - without logging the container is effectively untracked and unable to be audited, so refusing to continue until this is addressed is important.

Finally - I thought we had log rotation implemented in Conmon for a long while now, so I do wonder how we're actually filling up a partition with only Podman logs.

**Comment by rhatdan** [comment]
Conmon should exit, and execute the cleanup phase, would be my thoughts.

**Comment by srcshelton** [comment]
> The question would be what to do in a logging-failed case

Keeping the container running without logs is IMHO the least harmful (and arguably least surprising?) option - especially if `conmon` gained an option (via a feature-request 😅) for a secondary log location or to buffer logs and retry in a filesystem-full scenario… but perhaps this behaviour vs. killing the container without cleanup could be a `podman` option to set the desired behaviour per container on run?

**Comment by srcshelton** [comment]
> Finally - I thought we had log rotation implemented in Conmon for a long while now, so I do wonder how we're actually filling up a partition with only Podman logs.

Ah, the full partition wasn't _just_ podman logs, so this could well be working but not rotating fast enough to save the system when there's a log-storm for other reasons.

**Comment by rhatdan** [comment]
I think I can close this, reopen if I am mistaken.
