### ISSUE TITLE
podman [X] --filter pod : documented in man pages, not in command completion

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#19967]
The following commands list `pod` as a valid option to `--filter`, in man pages, and AFAICT it works,  but `podman X --filter <TAB>` does not list "pod":

- [ ] podman container list
- [ ] podman container pause
- [ ] podman container ps
- [ ] podman container restart
- [ ] podman container rm
- [ ] podman container start
- [ ] podman container stop
- [ ] podman container unpause
- [ ] podman pause
- [ ] podman ps
- [ ] podman restart
- [ ] podman rm
- [ ] podman start
- [ ] podman stop
- [ ] podman unpause

**Comment by Luap99** [comment]
Yeah unfortunately many of the shell completions are hard coded and need to be adjusted manually if new values are added so it is likely that since I implement this a larger part of the completions are now missing valid options.
