### ISSUE TITLE
Update podman load example

### ISSUE THREAD

**Issue by DaveJarvis** [containers/podman#19989]
### Feature request description

The example for the [podman-load](https://github.com/containers/podman/blob/main/docs/source/markdown/podman-load.1.md) document shows:

    $ podman load --quiet -i fedora.tar

Consider showing an example for `.tar.gz` (or `.tgz`) instead of `.tar`. It isn't immediately apparent from reading the documentation that compressed files are supported.

### Suggest potential solution

Change `.tar` to `.tgz`.

### Have you considered any alternatives?

n/a

### Additional context

n/a

**Comment by rhatdan** [comment]
Please open a PR with your suggested change, kills two birds with one stone.

**Comment by afbjorklund** [comment]
Some of the containers/image compression is really slow.

So you might want to just run `gunzip`, before `podman`...
