### ISSUE TITLE
@Luap99 - understood. Yes standard podman would be great! Didn't realise it _cannot_ run as root.

### ISSUE THREAD

**Issue by DevilDogLinux** [containers/podman#20010]
@Luap99 - understood. Yes standard podman would be great! Didn't realise it _cannot_ run as root.

Podman isn't in the Fatdog repo so I pulled various versions until I found one that executed.

I'm not looking for anything fancy ... just want "podman machine init" to run!

 So - having created a podman user ...
 
```
 # su podman
 podman$ podman info
ERRO[0000] stat /root/.config/containers/storage.conf: permission denied 
podman$ 

```

I must have missed a configuration step?

_Originally posted by @DevilDogLinux in https://github.com/containers/podman/issues/20008#issuecomment-1723052027_

**Comment by Luap99** [comment]
Please don't create new issues, we can continue talking on the other issue.
