### ISSUE TITLE
Support better isulation when building images as part of `kube play`

### ISSUE THREAD

**Issue by ifireball** [containers/podman#20024]
### Feature request description

`podman kube play` has a useful option to build an image when the image specified in the K8s YAML maps to a directory with a Dockerfile or a Container file in it. 

Currently when images are built this way, the isolation use is hard-coded to "cheroot" as evident by [this code][1].

This can cause more complex container builds to fail due to e.g. collisions with resources running on  the host.

[1]: https://github.com/containers/podman/blob/main/pkg/domain/infra/abi/play.go#L984-L990

### Suggest potential solution

I would like to have at least one of the following:

- If nothing else, document the current behaviour - it took us quite a while to figure out why images that build properly with `podman build` fail to build with `podman kube play`
- A command-line option to set the desired isolation level
- Support for the `BUILDAH_ISOLATION` environment variable
- A way the specify the isolation via the k8s YAML file (E.g. via a POD annotation)
- Default to higher isolation level (OCI or rootless)

### Have you considered any alternatives?

We are currently telling people to build the images on their own via `podman build` before spinning up their environment via `podman kube play`. We may also end up providing our own wrapper script, but this is cumbersome. We'd really like to have a single command to spin up a work environment.

**Comment by rhatdan** [comment]
Interested in doing any of this yourself?

@flouthoc WDYT?

**Comment by flouthoc** [comment]
Yes I think `podman play kube` must honor `BUILDAH_ISOLATION` or must have a higher level CLI flag.

**Comment by flouthoc** [comment]
I'll check this.

**Comment by rhatdan** [comment]
@flouthoc any update?
