### ISSUE TITLE
cannot start podman on MAC M1

### ISSUE THREAD

**Issue by azazadev** [containers/podman#20033]
### Issue Description

cannot start podman on MAC M1

(base) ➜  ~ podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
**Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Unknown Error**

MAC description : 

(base) ➜  ~ /usr/sbin/system_profiler SPHardwareDataType
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,3
      Chip: Apple M1 Pro
      Total Number of Cores: 10 (8 performance and 2 efficiency)
      Memory: 16 GB
      
      

### Steps to reproduce the issue

Steps to reproduce the issue

**1. Install podman-desktop**
```
(base) ➜  ~ arch -x86_64 brew install podman-desktop
==> Downloading https://github.com/containers/podman-desktop/releases/download/v1.4.0/podman-desktop-1.4.0-x64.dmg
==> Installing podman
==> Pouring podman--4.6.2.ventura.bottle.tar.gz
🍺  /usr/local/Cellar/podman/4.6.2: 190 files, 55.5MB
==> Installing Cask podman-desktop
==> Moving App 'Podman Desktop.app' to '/Applications/Podman Desktop.app'
🍺  podman-desktop was successfully installed!
```

**2. init machine**

```
(base) ➜  ~ podman machine init --cpus 4 --memory=6144
Extracting compressed file
Image resized.
Machine init complete
To start your machine run:

	podman machine start
```

**3. check machine**

```
(base) ➜  ~ podman machine ls
NAME                     VM TYPE     CREATED         LAST UP         CPUS        MEMORY      DISK SIZE
podman-machine-default*  qemu        26 seconds ago  26 seconds ago  4           6GiB        100GiB
```

**4. start machine**

```
(base) ➜  ~ podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Unknown Error
```

### Describe the results you received

cannot start machine, error 

**`Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Unknown Error`**

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
You need to install the arm version of podman not the x86_64 on your M1.
see https://github.com/containers/podman/issues/16262

**Comment by azazadev** [comment]
Thanks @Luap99 for your quick answer, agree with you we need to install arm version, but solution in https://github.com/containers/podman/issues/16262 not working for me, now I'm able to achieve this by installing the podman-desktop arm version with this command

`
arch -arm64 /opt/homebrew/bin/brew install podman-desktop`
