### ISSUE TITLE
podman machine start command failing

### ISSUE THREAD

**Issue by paraggit** [containers/podman#20066]
### Discussed in https://github.com/containers/podman/discussions/19841

<div type='discussions-op-text'>

<sup>Originally posted by **paraggit** September  4, 2023</sup>
Hi,

I have installed Podman on macOS Ventura 13.5.1,  M2 max configuration. I am encountering an issue with the `podman machine start` command; the command is failing with the following error.

```
> podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Error: EOF
```

Here are the packages version info.
```
> podman -v
podman version 4.6.2

> qemu-system-x86_64 --version
QEMU emulator version 8.1.0
Copyright (c) 2003-2023 Fabrice Bellard and the QEMU Project developers

```

I have attempted to use `podman machine init` with increased CPU and memory values, but I am still encountering the same error. Please let me know if i missed anything in configuration.

Thanks in Advance.

</div>

**Comment by mheon** [comment]
@ashley-cui PTAL

**Comment by ashley-cui** [comment]
Hi! Looks like you have the x86 version of qemu installed instead of the arm version. Did you install Podman using Homebrew? If so, please check that your homebrew installation is not under Rosetta.

**Comment by paraggit** [comment]
Hi @ashley-cui , I removed Rosetta and reinstalled Podman. This time, I can confirm that arm64 packages are installed. However, I am still encountering an error with the 'podman machine start' command.

Following packages are installed on system
```
==> Pouring qemu--8.1.0_3.arm64_ventura.bottle.tar.gz
🍺  /opt/homebrew/Cellar/qemu/8.1.0_3: 162 files, 533.9MB
==> Installing podman
==> Pouring podman--4.6.2.arm64_ventura.bottle.tar.gz
```

Error in `podman machine start` command

```
> podman machine init
Extracting compressed file
Image resized.
Machine init complete
To start your machine run:

	podman machine start

> podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code -1, stderr: Assertion failed: (isv), function hvf_vcpu_exec, file hvf.c, line 1914.
```

**Comment by baude** [comment]
did you remove the machine and re-run init?

**Comment by ashley-cui** [comment]
Closing for now, as there is no response. Please re-open if you continue to run into this.
