### ISSUE TITLE
podman farm update --help error

### ISSUE THREAD

**Issue by yuhuijiang** [containers/podman#20079]
### Issue Description

https://github.com/containers/podman/blob/dce3ef3c42805b56adadad6c452791d52928e7cb/cmd/podman/farm/update.go#L24
https://github.com/containers/podman/blob/dce3ef3c42805b56adadad6c452791d52928e7cb/cmd/podman/farm/update.go#L25
in line 24 and line 25, it shoule be "	podman farm update --remove con2 farm2", we miss out "farm" indeed

### Steps to reproduce the issue

Steps to reproduce the issue
1.
2.
3.

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rhatdan** [comment]
Care to open a PR?

**Comment by boaz0** [comment]
Seems like an easy fix. @rhatdan mind if I work on it?
