### ISSUE TITLE
podman 4.6 on Ubuntu 22.04 - missing podmansh and overlayfs error

### ISSUE THREAD

**Issue by nigwil** [containers/podman#20078]
### Issue Description

Installing podman 4.6 on Ubuntu 22.04 via the Alvistack project (https://software.opensuse.org/download/package?package=podman&project=home%3Aalvistack)

podmansh is not setup, this can be fixed via the ln -s command
when using an example quadlet, setting podmansh as a login shell results in this error and an immediate exit from /bin/sh

# cat > /etc/containers/systemd/users/${USER_ID}/podmansh.container << _EOF
[Unit]
Description=The Podmansh container
After=local-fs.target

[Container]
Image=registry.fedoraproject.org/fedora
ContainerName=podmansh
RemapUsers=keep-id
RunInit=yes
DropCapability=all
NoNewPrivileges=true

Exec=sleep infinity

[Install]
RequiredBy=default.target
_EOF

overlayfs: fs on '/home/podtest/.local/share/containers/storage/overlay/compat638544074/lower1' does not support file handles, falling back to xino=off.

### Steps to reproduce the issue

Steps to reproduce the issue
1. install Ubuntu server 22.04
2. upgrade to Podman 4.6 via https://software.opensuse.org/download/package?package=podman&project=home%3Aalvistack
3. ln -s podman podmansh
4. use example quadlet with a new user, set the shell to podmansh

logon as that user, immediate exit after MOTD appears.

### Describe the results you received

User unable to logon to container.

### Describe the results you expected

Expected container to be fetched and user logged on.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.31.2
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon_100:2.1.8-1_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.8, commit: 00e08f4a9ca5420de733bf542b930ad58e1a7e7d'
  cpuUtilization:
    idlePercent: 99.93
    systemPercent: 0.03
    userPercent: 0.03
  cpus: 48
  databaseBackend: boltdb
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: file
  freeLocks: 2038
  hostname: 
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.0-84-generic
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 536465977344
  memTotal: 540422598656
  networkBackend: cni
  networkBackendInfo:
    backend: cni
    dns:
      package: podman-plugins_100:1.2.0-1_amd64
      path: /usr/libexec/cni/dnsname
      version: CNI dnsname plugin version unknown
    package: 'podman-machine-cni, containernetworking, containernetworking-plugins,
      podman-plugins: /usr/libexec/cni'
    path: /usr/libexec/cni
  ociRuntime:
    name: crun
    package: crun_100:1.9-1_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.9
      commit: a538ac4ea1ff319bcfe2bf81cb5c6f687e2dc9d3
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_100:1.2.2-1_amd64
    version: |-
      slirp4netns version 1.2.2
      commit: unknown
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 1h 1m 1.00s (Approximately 0.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 96748417024
  graphRootUsed: 18123206656
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.6.2
  Built: 0
  BuiltTime: Thu Jan  1 11:00:00 1970
  GitCommit: ""
  GoVersion: go1.21.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.2
```

### Podman in a container

Yes

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rhatdan** [comment]
@lsm5 PTAL

**Comment by lsm5** [comment]
@nigwil thanks for the report and for your interest in podmansh. The podman team doesn't maintain the alvistack repo you mentioned, so there's nothing we can do here. Your best option would be to contact them directly.

Closing..
