### ISSUE TITLE
podman selinux test failure for downstream podman on RHEL 8.9 and RHEL 9.3

### ISSUE THREAD

**Issue by chuanchang** [containers/podman#20087]
### Issue Description

It's failed to run test/system/410-selinux.bats for downstream podman both on RHEL 8.9 and RHEL 9.3, for details, please see the following test steps.

### Steps to reproduce the issue

Steps to reproduce the issue
1. dnf install podman podman-tests
2. install bats
3. cd /usr/share/podman
4. export PODMAN=/usr/bin/podman
5. bats test/system/410-selinux.bats

### Describe the results you received

[root@kvm-02-guest10 podman]# bats test/system/410-selinux.bats
410-selinux.bats
 ✓ podman selinux: confined container
 ✗ podman selinux: container with label=disable
   (from function `is' in file test/system/helpers.bash, line 866,
    from function `check_label' in file test/system/410-selinux.bats, line 23,
    in test file test/system/410-selinux.bats, line 44)
     `check_label "--security-opt label=disable" "spc_t"' failed
   [07:30:08.218197478] # podman rm -t 0 --all --force --ignore
   [07:30:08.263169540] # podman ps --all --external --format {{.ID}} {{.Names}}
   [07:30:08.308358956] # podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
   [07:30:08.369337766] quay.io/libpod/testimage:20221018 f5a99120db64
   [07:30:08.384923721] # podman run --rm --security-opt label=disable quay.io/libpod/testimage:20221018 cat -v /proc/self/attr/current
   [07:30:08.790903629] unconfined_u:unconfined_r:spc_t:s0^@
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #|     FAIL: SELinux role should always be system_r
   #| expected: '.*_u:system_r:.*' (using expr)
   #|   actual: 'unconfined_u:unconfined_r:spc_t:s0^@'
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   \# [teardown]
   [07:30:08.813507569] # podman pod rm -t 0 --all --force --ignore
   [07:30:08.851230232] # podman rm -t 0 --all --force --ignore
   [07:30:08.888425184] # podman network prune --force
   [07:30:08.925716285] # podman volume rm -a -f
 ✗ podman selinux: privileged container
   (from function `is' in file test/system/helpers.bash, line 866,
    from function `check_label' in file test/system/410-selinux.bats, line 23,
    in test file test/system/410-selinux.bats, line 49)
     `check_label "--privileged --userns=host" "spc_t"' failed
   [07:30:09.006790689] # podman rm -t 0 --all --force --ignore
   [07:30:09.052849978] # podman ps --all --external --format {{.ID}} {{.Names}}
   [07:30:09.099957334] # podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
   [07:30:09.144952275] quay.io/libpod/testimage:20221018 f5a99120db64
   [07:30:09.161027355] # podman run --rm --privileged --userns=host quay.io/libpod/testimage:20221018 cat -v /proc/self/attr/current
   [07:30:09.577332235] unconfined_u:unconfined_r:spc_t:s0^@
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #|     FAIL: SELinux role should always be system_r
   #| expected: '.*_u:system_r:.*' (using expr)
   #|   actual: 'unconfined_u:unconfined_r:spc_t:s0^@'
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   \# [teardown]
   [07:30:09.597826044] # podman pod rm -t 0 --all --force --ignore
   [07:30:09.638833311] # podman rm -t 0 --all --force --ignore
   [07:30:09.677205159] # podman network prune --force
   [07:30:09.716751043] # podman volume rm -a -f
 ✓ podman selinux: init container
 ✓ podman selinux: init container with --security-opt type
 ✓ podman selinux: init container with --security-opt level&type
 ✓ podman selinux: init container with --security-opt level
 ✗ podman selinux: pid=host
   (from function `is' in file test/system/helpers.bash, line 866,
    from function `check_label' in file test/system/410-selinux.bats, line 23,
    in test file test/system/410-selinux.bats, line 81)
     `check_label "--pid=host" "spc_t"' failed
   [07:30:12.967485273] # podman rm -t 0 --all --force --ignore
   [07:30:13.011452598] # podman ps --all --external --format {{.ID}} {{.Names}}
   [07:30:13.056846889] # podman images --all --format {{.Repository}}:{{.Tag}} {{.ID}}
   [07:30:13.100169856] quay.io/libpod/testimage:20221018 f5a99120db64
   [07:30:13.117306938] # podman run --rm --pid=host quay.io/libpod/testimage:20221018 cat -v /proc/self/attr/current
   [07:30:13.533054092] unconfined_u:unconfined_r:spc_t:s0^@
   #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
   #|     FAIL: SELinux role should always be system_r
   #| expected: '.*_u:system_r:.*' (using expr)
   #|   actual: 'unconfined_u:unconfined_r:spc_t:s0^@'
   #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   \# [teardown]
   [07:30:13.554592415] # podman pod rm -t 0 --all --force --ignore
   [07:30:13.597741210] # podman rm -t 0 --all --force --ignore
   [07:30:13.634962794] # podman network prune --force
   [07:30:13.672686163] # podman volume rm -a -f
 ✓ podman selinux: container with overridden range
 ✓ podman selinux: inspect kvm labels
 ✓ podman selinux: inspect multiple labels
 ✓ podman selinux: shared context in (some) namespaces
 ✓ podman selinux: containers in pods share full context
 ✓ podman selinux: containers in --no-infra pods do not share context
 ✓ podman with nonexistent labels
 ✓ podman selinux: check relabel
 ✓ podman selinux nested

17 tests, 3 failures

### Describe the results you expected

fix them.

### podman info output

```yaml
[root@kvm-02-guest10 ~]# cat /etc/redhat-release 
Red Hat Enterprise Linux release 9.3 Beta (Plow)

[root@kvm-02-guest10 ~]# podman version
Client:       Podman Engine
Version:      4.6.1
API Version:  4.6.1
Go Version:   go1.20.6
Built:        Fri Aug 25 07:08:17 2023
OS/Arch:      linux/amd64
[root@kvm-02-guest10 ~]# podman info
host:
  arch: amd64
  buildahVersion: 1.31.3
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.8-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.8, commit: aadb7c890ac6283eb4666d92690238e5fbdec5c7'
  cpuUtilization:
    idlePercent: 86.27
    systemPercent: 5.14
    userPercent: 8.59
  cpus: 1
  databaseBackend: boltdb
  distribution:
    distribution: '"rhel"'
    version: "9.3"
  eventLogger: journald
  freeLocks: 2042
  hostname: XXX.XXX.XXX.com
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.14.0-362.3.1.el9_3.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 2916114432
  memTotal: 3695702016
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.7.0-1.el9.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.7.0
    package: netavark-1.7.0-1.el9.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.7.0
  ociRuntime:
    name: crun
    package: crun-1.8.7-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.7
      commit: 53a9996ce82d1ee818349bdcc64797a1fa0433c4
      rundir: /run/user/0/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.1-1.el9.x86_64
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 4034617344
  swapTotal: 4034916352
  uptime: 2h 27m 21.00s (Approximately 0.08 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 35458646016
  graphRootUsed: 5828931584
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.6.1
  Built: 1692961697
  BuiltTime: Fri Aug 25 07:08:17 2023
  GitCommit: ""
  GoVersion: go1.20.6
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.1

[root@kvm-02-guest10 ~]# rpm -q podman
podman-4.6.1-5.el9.x86_64
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by vrothberg** [comment]
@edsantiago @rhatdan can you peek at it?  I asked @chuanchang to open an issue for that.  Note that the tests pass on a fresh machine and when being run entirely.

**Comment by edsantiago** [comment]
What version of `container-selinux`?

**Comment by edsantiago** [comment]
Okay, I'm seeing it on 9.3. It looks like that SELinux test got a major rewrite in #18612, but that is not in the 4.6 branch. @rhatdan can you shed light on this please?

**Comment by edsantiago** [comment]
Anyhow, I guess the solution is to waive these test failures until v4.7

**Comment by rhatdan** [comment]
Yes the tests changed on newer versions of selinux-policy which will never be updated in RHEL9 or earlier.

**Comment by vrothberg** [comment]
Would backporting https://github.com/containers/podman/pull/18612/ to the v4.6.1-rhel branch work and make it partially conditional on the RHEL host?

Or is it nothing to worry about?

**Comment by edsantiago** [comment]
I'm OK with backporting, assuming all the approvals/etc can be overcome

**Comment by vrothberg** [comment]
@rhatdan can we just backport or is there any host dependency we need to consider?

**Comment by rhatdan** [comment]
I am fine with backporting the section that hanldes the SELinux label test.
