### ISSUE TITLE
podman farm update enhancement

### ISSUE THREAD

**Issue by yuhuijiang** [containers/podman#20080]
### Issue Description

"podman farm update --add testcon1 testfarm1" will perform successfully, even though the connection name "testcon1" not exist or the farm name "testfarm1" not exist.
this issue both exists in "podman farm update --add/--remove/--default"

### Steps to reproduce the issue

Steps to reproduce the issue
1.[root@sweetpig-6 ~]# podman farm list
Name        Connections  Default
demo        []           true
2.[root@sweetpig-6 ~]# podman system connection list
Name          URI                                                                                        Identity    Default
rhel86_aarch  ssh://root@ampere-mtsnow-altra-01-vm-14.lab.eng.rdu2.redhat.com:22/run/podman/podman.sock              false
rhel88_aarch  ssh://root@arm-virt-02.lab.eng.pek2.redhat.com:22/run/podman/podman.sock                               false
rhel88_ppc64  ssh://root@ibm-p9z-06-lp10.khw3.lab.eng.bos.redhat.com:22/run/podman/podman.sock                       true
rhel88_s390   ssh://root@s390x-kvm-073.lab.eng.rdu2.redhat.com:22/run/podman/podman.sock                             false
3.[root@sweetpig-6 ~]# podman farm update --add testcon1 testfarm1
Farm "testfarm1" updated

### Describe the results you received

Farm "testfarm1" updated

### Describe the results you expected

podman should exit with error and prompt 
WARN[0000] farm "testfarm1" doesn't exist; nothing to update 
Error: failed to update farms ["testfarm1"]

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rhatdan** [comment]
@umohnani8 PTAL
