### ISSUE TITLE
Privileged container DNS resolution issues (with network)

### ISSUE THREAD

**Issue by kingsleyzissou** [containers/podman#20102]
### Issue Description

When running priviliged podman with a custom network DNS resolution fails. 
However, everything is okay when:
- I don't create a network and just use the default
- running rootless podman 

### Steps to reproduce the issue

Steps to reproduce the issue
1. sudo podman network create basic-net
2. sudo podman run -d --net basic-net --name fedora fedora:latest sleep infinity
3. sudo podman exec -it fedora curl google.com

This is also happening  with podman-compose between containers, the above is just a simple reproducer.

### Describe the results you received

curl: (6) Could not resolve host: google.com

### Describe the results you expected

DNS resolution to work

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.31.2
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.8-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.8, commit: 00e08f4a9ca5420de733bf542b930ad58e1a7e7d'
  cpuUtilization:
    idlePercent: 97.25
    systemPercent: 0.67
    userPercent: 2.08
  cpus: 8
  databaseBackend: boltdb
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  freeLocks: 2037
  hostname: zissou
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.4.12-arch1-1
  linkmode: dynamic
  logDriver: journald
  memFree: 24640790528
  memTotal: 33350717440
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: /usr/lib/podman/aardvark-dns is owned by aardvark-dns 1.7.0-1
      path: /usr/lib/podman/aardvark-dns
      version: aardvark-dns 1.7.0
    package: /usr/lib/podman/netavark is owned by netavark 1.7.0-1
    path: /usr/lib/podman/netavark
    version: netavark 1.7.0
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.8.7-1
    path: /usr/bin/crun
    version: |-
      crun version 1.8.7
      commit: 53a9996ce82d1ee818349bdcc64797a1fa0433c4
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.2.1-1
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 17179865088
  swapTotal: 17179865088
  uptime: 0h 35m 9.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 2
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 485597708288
  graphRootUsed: 279174926336
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 86
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.6.2
  Built: 1693343961
  BuiltTime: Tue Aug 29 22:19:21 2023
  GitCommit: 5db42e86862ef42c59304c38aa583732fd80f178-dirty
  GoVersion: go1.21.0
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.2
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

 sudo podman info --format {{.Host.NetworkBackend}}: netavark

### Additional information

<details>
<summary><b>--log-level debug</b> output</summary>
<br>
time="2023-09-22T15:14:10+01:00" level=info msg="podman filtering at log level debug"
time="2023-09-22T15:14:10+01:00" level=debug msg="Called run.PersistentPreRunE(podman run -d --name fedora --net osbuild-net --log-level debug fedora:latest sleep infinity)"
time="2023-09-22T15:14:10+01:00" level=debug msg="Using conmon: \"/usr/bin/conmon\""
time="2023-09-22T15:14:10+01:00" level=debug msg="Initializing boltdb state at /var/lib/containers/storage/libpod/bolt_state.db"
time="2023-09-22T15:14:10+01:00" level=debug msg="Using graph driver overlay"
time="2023-09-22T15:14:10+01:00" level=debug msg="Using graph root /var/lib/containers/storage"
time="2023-09-22T15:14:10+01:00" level=debug msg="Using run root /run/containers/storage"
time="2023-09-22T15:14:10+01:00" level=debug msg="Using static dir /var/lib/containers/storage/libpod"
time="2023-09-22T15:14:10+01:00" level=debug msg="Using tmp dir /run/libpod"
time="2023-09-22T15:14:10+01:00" level=debug msg="Using volume path /var/lib/containers/storage/volumes"
time="2023-09-22T15:14:10+01:00" level=debug msg="Using transient store: false"
time="2023-09-22T15:14:10+01:00" level=debug msg="[graphdriver] trying provided driver \"overlay\""
time="2023-09-22T15:14:10+01:00" level=debug msg="Cached value indicated that overlay is supported"
time="2023-09-22T15:14:10+01:00" level=debug msg="Cached value indicated that overlay is supported"
time="2023-09-22T15:14:10+01:00" level=debug msg="Cached value indicated that metacopy is being used"
time="2023-09-22T15:14:10+01:00" level=debug msg="Cached value indicated that native-diff is not being used"
time="2023-09-22T15:14:10+01:00" level=info msg="Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled"
time="2023-09-22T15:14:10+01:00" level=debug msg="backingFs=extfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=true"
time="2023-09-22T15:14:10+01:00" level=debug msg="Initializing event backend journald"
time="2023-09-22T15:14:10+01:00" level=debug msg="Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument"
time="2023-09-22T15:14:10+01:00" level=debug msg="Configured OCI runtime youki initialization failed: no valid executable found for OCI runtime youki: invalid argument"
time="2023-09-22T15:14:10+01:00" level=debug msg="Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument"
time="2023-09-22T15:14:10+01:00" level=debug msg="Configured OCI runtime ocijail initialization failed: no valid executable found for OCI runtime ocijail: invalid argument"
time="2023-09-22T15:14:10+01:00" level=debug msg="Configured OCI runtime crun-wasm initialization failed: no valid executable found for OCI runtime crun-wasm: invalid argument"
time="2023-09-22T15:14:10+01:00" level=debug msg="Configured OCI runtime runc initialization failed: no valid executable found for OCI runtime runc: invalid argument"
time="2023-09-22T15:14:10+01:00" level=debug msg="Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument"
time="2023-09-22T15:14:10+01:00" level=debug msg="Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument"
time="2023-09-22T15:14:10+01:00" level=debug msg="Using OCI runtime \"/usr/bin/crun\""
time="2023-09-22T15:14:10+01:00" level=info msg="Setting parallel job count to 25"
time="2023-09-22T15:14:10+01:00" level=debug msg="Successfully loaded network osbuild-net: &{osbuild-net dce7994838aa8152ec963b0e287454829cb4c1f750a883b1219602d725f754f0 bridge podman1 2023-09-22 15:01:15.418190016 +0100 IST [{{{10.89.0.0 ffffff00}} 10.89.0.1 <nil>}] [] false false true [] map[] map[] map[driver:host-local]}"
time="2023-09-22T15:14:10+01:00" level=debug msg="Successfully loaded 2 networks"
time="2023-09-22T15:14:10+01:00" level=debug msg="Pulling image fedora:latest (policy: missing)"
time="2023-09-22T15:14:10+01:00" level=debug msg="Looking up image \"fedora:latest\" in local containers storage"
time="2023-09-22T15:14:10+01:00" level=debug msg="Normalized platform linux/amd64 to {amd64 linux  [] }"
time="2023-09-22T15:14:10+01:00" level=debug msg="Loading registries configuration \"/etc/containers/registries.conf\""
time="2023-09-22T15:14:10+01:00" level=debug msg="Loading registries configuration \"/etc/containers/registries.conf.d/00-shortnames.conf\""
time="2023-09-22T15:14:10+01:00" level=debug msg="Trying \"registry.fedoraproject.org/fedora:latest\" ..."
time="2023-09-22T15:14:10+01:00" level=debug msg="parsed reference into \"[overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev]@72c9e456423548988a55fa920bb35c194d568ca1959ffcc7316c02e2f60ea0ff\""
time="2023-09-22T15:14:10+01:00" level=debug msg="Found image \"fedora:latest\" as \"registry.fedoraproject.org/fedora:latest\" in local containers storage"
time="2023-09-22T15:14:10+01:00" level=debug msg="Found image \"fedora:latest\" as \"registry.fedoraproject.org/fedora:latest\" in local containers storage ([overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev]@72c9e456423548988a55fa920bb35c194d568ca1959ffcc7316c02e2f60ea0ff)"
time="2023-09-22T15:14:10+01:00" level=debug msg="exporting opaque data as blob \"sha256:72c9e456423548988a55fa920bb35c194d568ca1959ffcc7316c02e2f60ea0ff\""
time="2023-09-22T15:14:10+01:00" level=debug msg="Looking up image \"registry.fedoraproject.org/fedora:latest\" in local containers storage"
time="2023-09-22T15:14:10+01:00" level=debug msg="Normalized platform linux/amd64 to {amd64 linux  [] }"
time="2023-09-22T15:14:10+01:00" level=debug msg="Trying \"registry.fedoraproject.org/fedora:latest\" ..."
time="2023-09-22T15:14:10+01:00" level=debug msg="parsed reference into \"[overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev]@72c9e456423548988a55fa920bb35c194d568ca1959ffcc7316c02e2f60ea0ff\""
time="2023-09-22T15:14:10+01:00" level=debug msg="Found image \"registry.fedoraproject.org/fedora:latest\" as \"registry.fedoraproject.org/fedora:latest\" in local containers storage"
time="2023-09-22T15:14:10+01:00" level=debug msg="Found image \"registry.fedoraproject.org/fedora:latest\" as \"registry.fedoraproject.org/fedora:latest\" in local containers storage ([overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev]@72c9e456423548988a55fa920bb35c194d568ca1959ffcc7316c02e2f60ea0ff)"
time="2023-09-22T15:14:10+01:00" level=debug msg="exporting opaque data as blob \"sha256:72c9e456423548988a55fa920bb35c194d568ca1959ffcc7316c02e2f60ea0ff\""
time="2023-09-22T15:14:10+01:00" level=debug msg="Looking up image \"fedora:latest\" in local containers storage"
time="2023-09-22T15:14:10+01:00" level=debug msg="Normalized platform linux/amd64 to {amd64 linux  [] }"
time="2023-09-22T15:14:10+01:00" level=debug msg="Trying \"registry.fedoraproject.org/fedora:latest\" ..."
time="2023-09-22T15:14:10+01:00" level=debug msg="parsed reference into \"[overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev]@72c9e456423548988a55fa920bb35c194d568ca1959ffcc7316c02e2f60ea0ff\""
time="2023-09-22T15:14:10+01:00" level=debug msg="Found image \"fedora:latest\" as \"registry.fedoraproject.org/fedora:latest\" in local containers storage"
time="2023-09-22T15:14:10+01:00" level=debug msg="Found image \"fedora:latest\" as \"registry.fedoraproject.org/fedora:latest\" in local containers storage ([overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev]@72c9e456423548988a55fa920bb35c194d568ca1959ffcc7316c02e2f60ea0ff)"
time="2023-09-22T15:14:10+01:00" level=debug msg="exporting opaque data as blob \"sha256:72c9e456423548988a55fa920bb35c194d568ca1959ffcc7316c02e2f60ea0ff\""
time="2023-09-22T15:14:10+01:00" level=debug msg="Inspecting image 72c9e456423548988a55fa920bb35c194d568ca1959ffcc7316c02e2f60ea0ff"
time="2023-09-22T15:14:10+01:00" level=debug msg="exporting opaque data as blob \"sha256:72c9e456423548988a55fa920bb35c194d568ca1959ffcc7316c02e2f60ea0ff\""
time="2023-09-22T15:14:10+01:00" level=debug msg="exporting opaque data as blob \"sha256:72c9e456423548988a55fa920bb35c194d568ca1959ffcc7316c02e2f60ea0ff\""
time="2023-09-22T15:14:10+01:00" level=debug msg="Inspecting image 72c9e456423548988a55fa920bb35c194d568ca1959ffcc7316c02e2f60ea0ff"
time="2023-09-22T15:14:10+01:00" level=debug msg="Inspecting image 72c9e456423548988a55fa920bb35c194d568ca1959ffcc7316c02e2f60ea0ff"
time="2023-09-22T15:14:10+01:00" level=debug msg="Inspecting image 72c9e456423548988a55fa920bb35c194d568ca1959ffcc7316c02e2f60ea0ff"
time="2023-09-22T15:14:10+01:00" level=debug msg="Inspecting image 72c9e456423548988a55fa920bb35c194d568ca1959ffcc7316c02e2f60ea0ff"
time="2023-09-22T15:14:10+01:00" level=debug msg="using systemd mode: false"
time="2023-09-22T15:14:10+01:00" level=debug msg="setting container name fedora"
time="2023-09-22T15:14:10+01:00" level=debug msg="No hostname set; container's hostname will default to runtime default"
time="2023-09-22T15:14:10+01:00" level=debug msg="Loading seccomp profile from \"/etc/containers/seccomp.json\""
time="2023-09-22T15:14:10+01:00" level=debug msg="Allocated lock 7 for container f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb"
time="2023-09-22T15:14:10+01:00" level=debug msg="parsed reference into \"[overlay@/var/lib/containers/storage+/run/containers/storage:overlay.mountopt=nodev]@72c9e456423548988a55fa920bb35c194d568ca1959ffcc7316c02e2f60ea0ff\""
time="2023-09-22T15:14:10+01:00" level=debug msg="exporting opaque data as blob \"sha256:72c9e456423548988a55fa920bb35c194d568ca1959ffcc7316c02e2f60ea0ff\""
time="2023-09-22T15:14:10+01:00" level=debug msg="Cached value indicated that idmapped mounts for overlay are supported"
time="2023-09-22T15:14:11+01:00" level=debug msg="Created container \"f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb\""
time="2023-09-22T15:14:11+01:00" level=debug msg="Container \"f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb\" has work directory \"/var/lib/containers/storage/overlay-containers/f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb/userdata\""
time="2023-09-22T15:14:11+01:00" level=debug msg="Container \"f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb\" has run directory \"/run/containers/storage/overlay-containers/f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb/userdata\""
time="2023-09-22T15:14:11+01:00" level=debug msg="overlay: mount_data=lowerdir=/var/lib/containers/storage/overlay/l/BI2PL4ILTZGGJ7F7WI7A3DVB72,upperdir=/var/lib/containers/storage/overlay/a0d049279d1409e288930ce6f071102177216db1412eca2548ede0f47b464d1f/diff,workdir=/var/lib/containers/storage/overlay/a0d049279d1409e288930ce6f071102177216db1412eca2548ede0f47b464d1f/work,nodev"
time="2023-09-22T15:14:11+01:00" level=debug msg="Mounted container \"f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb\" at \"/var/lib/containers/storage/overlay/a0d049279d1409e288930ce6f071102177216db1412eca2548ede0f47b464d1f/merged\""
time="2023-09-22T15:14:11+01:00" level=debug msg="Made network namespace at /run/netns/netns-14fdd5bc-3d62-30d8-2fac-b9f2a0289f23 for container f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb"
time="2023-09-22T15:14:11+01:00" level=debug msg="Created root filesystem for container f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb at /var/lib/containers/storage/overlay/a0d049279d1409e288930ce6f071102177216db1412eca2548ede0f47b464d1f/merged"
[DEBUG netavark::network::validation] "Validating network namespace..."
[DEBUG netavark::commands::setup] "Setting up..."
[INFO  netavark::firewall] Using iptables firewall driver
[DEBUG netavark::network::bridge] Setup network osbuild-net
[DEBUG netavark::network::bridge] Container interface name: eth0 with IP addresses [10.89.0.4/24]
[DEBUG netavark::network::bridge] Bridge name: podman1 with IP addresses [10.89.0.1/24]
[DEBUG netavark::network::core_utils] Setting sysctl value for net.ipv4.ip_forward to 1
[DEBUG netavark::network::core_utils] Setting sysctl value for /proc/sys/net/ipv6/conf/eth0/autoconf to 0
[INFO  netavark::network::netlink] Adding route (dest: 0.0.0.0/0 ,gw: 10.89.0.1, metric 100)
[DEBUG netavark::firewall::varktables::helpers] chain NETAVARK-2862F47756C1C exists on table nat
[DEBUG netavark::firewall::varktables::helpers] chain NETAVARK-2862F47756C1C exists on table nat
[DEBUG netavark::firewall::varktables::helpers] chain NETAVARK_ISOLATION_2 exists on table filter
[DEBUG netavark::firewall::varktables::helpers] chain NETAVARK_ISOLATION_2 exists on table filter
[DEBUG netavark::firewall::varktables::helpers] chain NETAVARK_ISOLATION_3 exists on table filter
[DEBUG netavark::firewall::varktables::helpers] chain NETAVARK_ISOLATION_3 exists on table filter
[DEBUG netavark::firewall::varktables::helpers] chain NETAVARK_FORWARD exists on table filter
[DEBUG netavark::firewall::varktables::helpers] chain NETAVARK_FORWARD exists on table filter
[DEBUG netavark::firewall::varktables::helpers] rule -d 10.89.0.0/24 -j ACCEPT exists on table nat and chain NETAVARK-2862F47756C1C
[DEBUG netavark::firewall::varktables::helpers] rule ! -d 224.0.0.0/4 -j MASQUERADE exists on table nat and chain NETAVARK-2862F47756C1C
[DEBUG netavark::firewall::varktables::helpers] rule -s 10.89.0.0/24 -j NETAVARK-2862F47756C1C exists on table nat and chain POSTROUTING
[DEBUG netavark::firewall::varktables::helpers] rule -d 10.89.0.0/24 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT exists on table filter and chain NETAVARK_FORWARD
[DEBUG netavark::firewall::varktables::helpers] rule -s 10.89.0.0/24 -j ACCEPT exists on table filter and chain NETAVARK_FORWARD
[DEBUG netavark::firewall::varktables::helpers] chain NETAVARK-HOSTPORT-SETMARK exists on table nat
[DEBUG netavark::firewall::varktables::helpers] chain NETAVARK-HOSTPORT-SETMARK exists on table nat
[DEBUG netavark::firewall::varktables::helpers] chain NETAVARK-HOSTPORT-MASQ exists on table nat
[DEBUG netavark::firewall::varktables::helpers] chain NETAVARK-HOSTPORT-MASQ exists on table nat
[DEBUG netavark::firewall::varktables::helpers] chain NETAVARK-HOSTPORT-DNAT exists on table nat
[DEBUG netavark::firewall::varktables::helpers] chain NETAVARK-HOSTPORT-DNAT exists on table nat
[DEBUG netavark::firewall::varktables::helpers] rule -j MARK  --set-xmark 0x2000/0x2000 exists on table nat and chain NETAVARK-HOSTPORT-SETMARK
[DEBUG netavark::firewall::varktables::helpers] rule -j MASQUERADE -m comment --comment 'netavark portfw masq mark' -m mark --mark 0x2000/0x2000 exists on table nat and chain NETAVARK-HOSTPORT-MASQ
[DEBUG netavark::firewall::varktables::helpers] rule -j NETAVARK-HOSTPORT-DNAT -m addrtype --dst-type LOCAL exists on table nat and chain PREROUTING
[DEBUG netavark::firewall::varktables::helpers] rule -j NETAVARK-HOSTPORT-DNAT -m addrtype --dst-type LOCAL exists on table nat and chain OUTPUT
[DEBUG netavark::commands::setup] {
        "osbuild-net": StatusBlock {
            dns_search_domains: Some(
                [
                    "dns.podman",
                ],
            ),
            dns_server_ips: Some(
                [
                    10.89.0.1,
                ],
            ),
            interfaces: Some(
                {
                    "eth0": NetInterface {
                        mac_address: "86:dd:5b:e1:66:64",
                        subnets: Some(
                            [
                                NetAddress {
                                    gateway: Some(
                                        10.89.0.1,
                                    ),
                                    ipnet: 10.89.0.4/24,
                                },
                            ],
                        ),
                    },
                },
            ),
        },
    }
[DEBUG netavark::commands::setup] "Setup complete"
time="2023-09-22T15:14:11+01:00" level=debug msg="Skipping unrecognized mount in /etc/containers/mounts.conf: \"# Configuration file for default mounts in containers (see man 5\""
time="2023-09-22T15:14:11+01:00" level=debug msg="Skipping unrecognized mount in /etc/containers/mounts.conf: \"# containers-mounts.conf for further information)\""
time="2023-09-22T15:14:11+01:00" level=debug msg="Skipping unrecognized mount in /etc/containers/mounts.conf: \"\""
time="2023-09-22T15:14:11+01:00" level=debug msg="/etc/system-fips does not exist on host, not mounting FIPS mode subscription"
time="2023-09-22T15:14:11+01:00" level=debug msg="Setting Cgroups for container f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb to machine.slice:libpod:f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb"
time="2023-09-22T15:14:11+01:00" level=debug msg="reading hooks from /usr/share/containers/oci/hooks.d"
time="2023-09-22T15:14:11+01:00" level=debug msg="Workdir \"/\" resolved to host path \"/var/lib/containers/storage/overlay/a0d049279d1409e288930ce6f071102177216db1412eca2548ede0f47b464d1f/merged\""
time="2023-09-22T15:14:11+01:00" level=debug msg="Created OCI spec for container f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb at /var/lib/containers/storage/overlay-containers/f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb/userdata/config.json"
time="2023-09-22T15:14:11+01:00" level=debug msg="/usr/bin/conmon messages will be logged to syslog"
time="2023-09-22T15:14:11+01:00" level=debug msg="running conmon: /usr/bin/conmon" args="[--api-version 1 -c f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb -u f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb -r /usr/bin/crun -b /var/lib/containers/storage/overlay-containers/f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb/userdata -p /run/containers/storage/overlay-containers/f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb/userdata/pidfile -n fedora --exit-dir /run/libpod/exits --full-attach -s -l journald --log-level debug --syslog --conmon-pidfile /run/containers/storage/overlay-containers/f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /var/lib/containers/storage --exit-command-arg --runroot --exit-command-arg /run/containers/storage --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /run/libpod --exit-command-arg --network-config-dir --exit-command-arg  --exit-command-arg --network-backend --exit-command-arg netavark --exit-command-arg --volumepath --exit-command-arg /var/lib/containers/storage/volumes --exit-command-arg --db-backend --exit-command-arg boltdb --exit-command-arg --transient-store=false --exit-command-arg --runtime --exit-command-arg crun --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --storage-opt --exit-command-arg overlay.mountopt=nodev --exit-command-arg --events-backend --exit-command-arg journald --exit-command-arg --syslog --exit-command-arg container --exit-command-arg cleanup --exit-command-arg f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb]"
time="2023-09-22T15:14:11+01:00" level=info msg="Running conmon under slice machine.slice and unitName libpod-conmon-f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb.scope"
time="2023-09-22T15:14:11+01:00" level=debug msg="Received: 17408"
time="2023-09-22T15:14:11+01:00" level=info msg="Got Conmon PID as 17406"
time="2023-09-22T15:14:11+01:00" level=debug msg="Created container f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb in OCI runtime"
time="2023-09-22T15:14:11+01:00" level=debug msg="Adding nameserver(s) from network status of '[\"10.89.0.1\"]'"
time="2023-09-22T15:14:11+01:00" level=debug msg="Adding search domain(s) from network status of '[\"dns.podman\"]'"
time="2023-09-22T15:14:11+01:00" level=debug msg="Starting container f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb with command [sleep infinity]"
time="2023-09-22T15:14:11+01:00" level=debug msg="Started container f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb"
time="2023-09-22T15:14:11+01:00" level=debug msg="Notify sent successfully"
f70961ae5c9d686f5bae6b4e68767166df2bf73726744796e0df81cb50a626cb
time="2023-09-22T15:14:11+01:00" level=debug msg="Called run.PersistentPostRunE(podman run -d --name fedora --net osbuild-net --log-level debug fedora:latest sleep infinity)"
time="2023-09-22T15:14:11+01:00" level=debug msg="Shutting down engines"
</details>

**Comment by rhatdan** [comment]
@Luap99 PTAL

**Comment by baude** [comment]
when you run the first container on the network, do you see an aardvark process running on your system?

**Comment by kingsleyzissou** [comment]
Yeah, indeed:

```
root       13737  0.0  0.0 1155648 3252 ?        Ssl  Sep22   0:00 /usr/lib/podman/aardvark-dns --config /run/containers/networks/aardvark-dns -p 53 run
```
This is the output from `lsof`:
```
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
aardvark- 13737 root    9u  IPv4 462474      0t0  UDP zissou:domain 
```

**Comment by Luap99** [comment]
Do you see any error logged in journald? Is something else already listening on port 53? You can check with `ss -ulpn`

**Comment by Luap99** [comment]
`No configuration found stopping the sever` this is normal assuming all you containers are stopped, the dns sever is only running when it is needed.
Can you show me your firewall setup, how does `iptables -nvL` look like? Do you have a deny all INPUT rule by default?

**Comment by kingsleyzissou** [comment]
Ah flip, yeah that's exactly what it was.
```
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), deny (routed)
New profiles: skip  
```
I quickly disabled the firewall to check and it was all good. I'll setup some rules to handle that. Thanks for your help debugging this, I appreciate it.

**Comment by Luap99** [comment]
This should work automatically with the next netavark update: https://github.com/containers/netavark/issues/742
