### ISSUE TITLE
URGENT: CI is broken: new f39 image fubar

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#20119]
Fallout from #20082: "useradd not found". [Sample failure](https://api.cirrus-ci.com/v1/artifact/task/4756712645722112/html/int-podman-fedora-37-root-container-boltdb.log.html#t--Podman-exec-podman-exec-with-user-only-in-container--1). All CI jobs are failing.

 **WE TESTED THIS**. It was working. I can only conclude that someone upstream modified the f39 image in the registry.

Suggestion: my usual one. Stop relying on registries that we do not control.

Sorry, it's my bedtime, I can't deal with this now. Good luck.

**Comment by vrothberg** [comment]
I'll take a look

**Comment by giuseppe** [comment]
should we just revert 682ca6b2eaf908efb25d8b703bbfc000235e4324 ?

**Comment by vrothberg** [comment]
> should we just revert [682ca6b](https://github.com/containers/podman/commit/682ca6b2eaf908efb25d8b703bbfc000235e4324) ?

That would be a quick fix but I don't think it's a permanent solution.  I am currently working on a PR moving these tests to our CITEST_IMAGE to make sure it's only us to break CI and no update to public registry.

**Comment by vrothberg** [comment]
> should we just revert [682ca6b](https://github.com/containers/podman/commit/682ca6b2eaf908efb25d8b703bbfc000235e4324) ?

Turned out we needed a mix of both, see https://github.com/containers/podman/pull/20127.
