### ISSUE TITLE
Certs not propagated on hyperV

### ISSUE THREAD

**Issue by ashley-cui** [containers/podman#20129]
### Issue Description

HTTP_PROXY and Cert files are not propagated into the machine on start

### Steps to reproduce the issue

Steps to reproduce the issue
1. set  HTTP_PROXY, SSL_CERT_FILE, SSL_CERT_DIR 
2. podman machine ssh printenv

### Describe the results you received

Certs propagated into the machine

### Describe the results you expected

See that the vars are not set

### Additional environment details

HyperV

**Comment by Luap99** [comment]
was fixed in https://github.com/containers/podman/commit/f218f8430aa092ec45c4b7868f6d51b0bba4052b
