### ISSUE TITLE
Podman does not understand "here document" syntax

### ISSUE THREAD

**Issue by larsks** [containers/podman#20143]
### Issue Description

Docker implements support for "here documents" in Dockerfiles, like [this](https://docs.docker.com/build/building/multi-stage/):

```
COPY <<EOF ./main.go
package main

import "fmt"

func main() {
  fmt.Println("hello, world")
}
EOF
```

Podman is unable to translate this Dockerfile into an image, failing with:

```
Error: building at STEP "COPY <<EOF ./main.go": checking on sources under "/home/lars/tmp/container": copier: stat: "/<<EOF": no such file or directory
```

This syntax is new in [version 1.4 of the specification](https://docs.docker.com/engine/reference/builder/#here-documents).

---

I am using podman version:

```
Client:       Podman Engine
Version:      4.6.2
API Version:  4.6.2
Go Version:   go1.20.7
Built:        Tue Sep 12 16:07:22 2023
OS/Arch:      linux/amd64
```

### Steps to reproduce the issue

(see the description)

### Describe the results you received

(see the description)

### Describe the results you expected

I expected Podman to support the most recent Dockerfile specification.

### podman info output

```yaml
n/a
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

n/a

### Additional information

n/a

**Comment by flouthoc** [comment]
@larsks I already have somewhat working thing for this, but i was unable to work on it due to other priority issues. I'll pick it up and finish it in coming weeks.

Please track progress here: https://github.com/containers/buildah/issues/3474

I am closing this issue since its duplicate.
