### ISSUE TITLE
WSL machine init and set --options are not configurable

### ISSUE THREAD

**Issue by baude** [containers/podman#20175]
### Issue Description

Per #20158 , the machine set and init options for disk size, mounts, memory, and cpu counts is not configurable.

we need to determine if these should be disabled for WSL or error out when changed, etc.

all other providers do honor those settings.

### Steps to reproduce the issue

Steps to reproduce the issue
1.
2.
3.

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
podman main branch
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by vrothberg** [comment]
@n1hility WDYT?  Are these settings configurable in WSL2?  I wonder if there are any limitations imposed by WSL.

**Comment by n1hility** [comment]
@vrothberg right these dont map well to WSL. At the moment we just say they are only supported on QEMU based backends 
https://docs.podman.io/en/latest/markdown/podman-machine-set.1.html . 

Foor cpu and memory, there is a shared VM that is global across all WSL dists, so they can't be set for just podman. A user would need to edit their global .wslconfig to change these.

For disk, WSL uses a sparse volume that has a very large limit (250 GB iirc), so this setting isn't needed.

For the volume option to machine, all volumes are already mapped in /mnt (and our volume code for container operations, e.g. run -v etc, remaps the paths), so this one has no meaning either.

All of these values are just treated as a no-op and ignored, so we could validate and fail but it would be a change in behavior from today.

**Comment by vrothberg** [comment]
Thanks for clarifying, @n1hility !
