### ISSUE TITLE
Support symlinks for quadlet container files

### ISSUE THREAD

**Issue by raffomania** [containers/podman#20174]
### Feature request description

I'd like to manage my quadlet files in ~/.config/containers/systemd as symlinks to another folder.

Currently, using symlinks results in output similar to this:
```
/usr/lib/systemd/system-generators/podman-system-generator --user --dryrun
quadlet-generator[3515]: Loading source unit file /home/rafael/.config/containers/systemd/hedgedoc-db.volume
quadlet-generator[3515]: Loading source unit file /home/rafael/.config/containers/systemd/hedgedoc-uploads.volume
quadlet-generator[3515]: Loading source unit file /home/rafael/.config/containers/systemd/hedgedoc.container
quadlet-generator[3515]: No files parsed from [/home/rafael/.config/containers/systemd /etc/containers/systemd/users/1000 /etc/containers/systemd/users]
```

### Suggest potential solution

I'd like quadlet to successfully follow and read contents of symlinks.

### Have you considered any alternatives?

Using hardlinks instead of symlinks does not work for me.

**Comment by lsm5** [comment]
@ygalblum @alexlarsson @rhatdan PTAL

**Comment by ygalblum** [comment]
The following worked for me:
```
echo "[Volume]" > /tmp/real.volume
ln -s /tmp/real.volume ~/.config/containers/systemd/
/usr/lib/systemd/system-generators/podman-system-generator --user --dryrun
```

Are you symlinking each file separately or at the directory level? Could this be a permissions (or SELinux) issue?

**Comment by raffomania** [comment]
Apologies. It turns out I forgot to use the `-r` flag, resulting in broken relative symlinks. With correct symlinks, everything actually works fine!

Thanks for the help and sorry to take up your time!
