### ISSUE TITLE
e2e CNI tests: race? conflist could not be converted to a libpod config

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#20173]
Seen at least twice:
```
[It] podman network ID test
...
# podman [options] network create networkIDTest
time="2023-09-22T12:54:56-05:00" level=error msg="CNI config list /etc/cni/net.d/netef629377e134d87dce82347fb8e2407e39fd33ce6d98593eaf3d8605a43032da.conflist could not be converted to a libpod config, skipping: stat /etc/cni/net.d/netef629377e134d87dce82347fb8e2407e39fd33ce6d98593eaf3d8605a43032da.conflist: no such file or directory"
```
and
```
[It] podman network list --filter two names
...
$ podman [options] network ls --filter name=netbc24e644b027f2a8c428f6aa0878bb4732aef7261b4bab36ad449fd55265bad0 --filter name=nete042494580ff5fc12cd7af9da1dc4f30349d29f2aa3675593e3cb56f9fa50410
time="2023-09-27T07:50:27-05:00" level=error msg="CNI config list /home/some2718dude/.config/cni/net.d/net57ae2fdd90c3bb3e7a6cb259b56d5c668e035d7bbccc3f4c7da36965c0690005.conflist could not be converted to a libpod config, skipping: stat /home/some2718dude/.config/cni/net.d/net57ae2fdd90c3bb3e7a6cb259b56d5c668e035d7bbccc3f4c7da36965c0690005.conflist: no such file or directory"
```
In both cases the test actually passes (commands exit with status 0) but `ExitCleanly()` fails because of unwanted stderr.

In both cases the offending SHA (`ef62`, `e042`) appears in a different test within a few lines of the failing one, suggesting a TOCTOU between `readdir()` and (some sort of processing of the readdir).

* fedora-37 : int podman fedora-37 root host sqlite
  * PR #17831
    * [09-22 14:22](https://api.cirrus-ci.com/v1/artifact/task/6334394592395264/html/int-podman-fedora-37-root-host-sqlite.log.html#t--Podman-network-podman-network-ID-test--1) in Podman network podman network ID test
* fedora-38 : int podman fedora-38 rootless host sqlite
  * PR #17831
    * [09-27 08:55](https://api.cirrus-ci.com/v1/artifact/task/4569440528891904/html/int-podman-fedora-38-rootless-host-sqlite.log.html#t--Podman-network-podman-network-list-filter-two-names--1) in Podman network podman network list --filter two names

Seen root & rootless, only in CNI tests

**Comment by Luap99** [comment]
easy enough to fix: https://github.com/containers/common/pull/1668
