### ISSUE TITLE
podman fails to install on Ubuntu 22.04.3

### ISSUE THREAD

**Issue by jacobwdv** [containers/podman#20214]
### Issue Description

following directions on this site: https://podman.io/docs/installation

installing podman on Ubuntu 22.04 should be as easy as 

```
# Ubuntu 20.10 and newer
sudo apt-get update
sudo apt-get -y install podman
```

But on my system, which is a newly deployed Ubuntu VM, I get the following error:

```
root@scarred1:~# sudo apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1,014 kB]
Fetched 1,352 kB in 1s (961 kB/s)
Reading package lists... Done
root@scarred1:~# sudo apt-get -y install podman
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package podman is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'podman' has no installation candidate
```

OS Info:
```
root@scarred1:~# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

```

### Steps to reproduce the issue

Steps to reproduce the issue
1. sudo apt-get update
2. sudo apt-get -y install podman
3.

### Describe the results you received

podman is not installable.

### Describe the results you expected

podman to be installed

### podman info output

```yaml
root@scarred1:~# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by afbjorklund** [comment]
It is available in the "universe" (not in "main"), but _should_ be enabled by default ?

https://packages.ubuntu.com/podman

It means that it is unsupported by Ubuntu, and will not receive security updates...

https://help.ubuntu.com/community/Repositories/Ubuntu

**Comment by rhatdan** [comment]
This is not an upstream issue.

**Comment by jacobwdv** [comment]
Could we update the steps in the installation guide for Ubuntu with ones that work? The site shows the steps I followed and says the package _is_ available in official repositories for Ubuntu 20.10. Maybe it is available but it can't be installed by the steps printed.. Has anyone successfully installed on 22.04? if so, how?

**Comment by jacobwdv** [comment]
The additional step would be to enable 'universe'. This command does it: `sudo add-apt-repository universe`

**Comment by afbjorklund** [comment]
You can make a PR for the documentation, to suggest adding that line. It should not hurt, if already enabled.

```console
$ sudo add-apt-repository universe
'universe' distribution component is already enabled for all sources.
```

https://github.com/containers/podman.io/blob/main/docs/installation.md
