### ISSUE TITLE
WARN[0000] Error validating CNI config file(s)

### ISSUE THREAD

**Issue by thefonso** [containers/podman#20213]
### Issue Description

Describe your issue

When I run... podman-compose -p penpot -f docker-compose.yaml up -d 
...I am greeted with the following output...

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman-compose -p penpot -f docker-compose.yaml up -d
2.
3.

### Describe the results you received

Describe the results you received

podman-compose version: 1.0.6
[‘podman’, ‘–version’, ‘’]
using podman version: 3.4.4
** excluding: set()
[‘podman’, ‘ps’, ‘–filter’, ‘label=io.podman.compose.project=penpot’, ‘-a’, ‘–format’, ‘{{ index .Labels “io.podman.compose.config-hash”}}’]
WARN[0000] Error validating CNI config file /home/unclefonso/.config/cni/net.d/penpot.conflist: [plugin bridge does not support config version “1.0.0” plugin portmap does not support config version “1.0.0” plugin firewall does not support config version “1.0.0” plugin tuning does not support config version “1.0.0”]
[‘podman’, ‘network’, ‘exists’, ‘penpot_penpot’]
WARN[0000] Error validating CNI config file /home/unclefonso/.config/cni/net.d/penpot.conflist: [plugin bridge does not support config version “1.0.0” plugin portmap does not support config version “1.0.0” plugin firewall does not support config version “1.0.0” plugin tuning does not support config version “1.0.0”]
podman run --name=penpot_penpot-exporter_1 -d --label io.podman.compose.config-hash=87c50c428bb9ce353f1b26ad58e829ec3317dc50d90cb734d8cdab1b621e0010 --label io.podman.compose.project=penpot --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@penpot.service --label com.docker.compose.project=penpot --label com.docker.compose.project.working_dir=/home/unclefonso/myapps/penpot/docker/images --label com.docker.compose.project.config_files=docker-compose.yaml --label com.docker.compose.container-number=1 --label com.docker.compose.service=penpot-exporter -e PENPOT_PUBLIC_URI=http://penpot-frontend -e PENPOT_REDIS_URI=redis://penpot-redis/0 --net penpot_penpot --network-alias penpot-exporter --restart always penpotapp/exporter:latest
WARN[0000] Error validating CNI config file /home/unclefonso/.config/cni/net.d/penpot.conflist: [plugin bridge does not support config version “1.0.0” plugin portmap does not support config version “1.0.0” plugin firewall does not support config version “1.0.0” plugin tuning does not support config version “1.0.0”]
Error: short-name “penpotapp/exporter:latest” did not resolve to an alias and no unqualified-search registries are defined in “/etc/containers/registries.conf”
exit code: 125
podman start penpot_penpot-exporter_1
WARN[0000] Error validating CNI config file /home/unclefonso/.config/cni/net.d/penpot.conflist: [plugin bridge does not support config version “1.0.0” plugin portmap does not support config version “1.0.0” plugin firewall does not support config version “1.0.0” plugin tuning does not support config version “1.0.0”]
Error: no container with name or ID “penpot_penpot-exporter_1” found: no such container
exit code: 125
podman volume inspect penpot_penpot_postgres_v15 || podman volume create penpot_penpot_postgres_v15
[‘podman’, ‘volume’, ‘inspect’, ‘penpot_penpot_postgres_v15’]

### Describe the results you expected

Describe the results you expected

No errors

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

podman version 4.6.2

Pop!-OS 22.04 (Ubuntu 22.04)

$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.31.2
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2:2.1.8-0ubuntu22.04+obs16.13_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.8, commit: '
  cpuUtilization:
    idlePercent: 88.87
    systemPercent: 4.91
    userPercent: 6.22
  cpus: 16
  databaseBackend: boltdb
  distribution:
    codename: jammy
    distribution: pop
    version: "22.04"
  eventLogger: journald
  freeLocks: 2046
  hostname: pop-os
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
  kernel: 6.4.6-76060406-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 3251249152
  memTotal: 67256393728
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns_1.6.0-0ubuntu22.04+obs34.25_amd64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.6.0
    package: netavark_1.3.0-0ubuntu22.04+obs22.9_amd64
    path: /usr/libexec/podman/netavark
    version: netavark 1.3.0
  ociRuntime:
    name: crun
    package: crun_101:1.9-0ubuntu22.04+obs59.11_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.9
      commit: a538ac4ea1ff319bcfe2bf81cb5c6f687e2dc9d3
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.2.2-0ubuntu22.04+obs12.3_amd64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 21474029568
  swapTotal: 21474304000
  uptime: 24h 0m 0.00s (Approximately 1.00 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/unclefonso/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/unclefonso/.local/share/containers/storage
  graphRootAllocated: 482105122816
  graphRootUsed: 339368574976
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/unclefonso/.local/share/containers/storage/volumes
version:
  APIVersion: 4.6.2
  Built: 0
  BuiltTime: Wed Dec 31 19:00:00 1969
  GitCommit: ""
  GoVersion: go1.18.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.2

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
Upstream did never create cni config files with version 1.0.0 set. This looks like a problem with your old 3.4.4 podman build in ubuntu: https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/2024394

I suggest you delete the config and if you stick to 4.6.2 version then it should work.

**Comment by thefonso** [comment]
@Luap99 Hmm "delete the config" I'm sorry, I'm a bit of beginner with podman, how do I delete the config?

**Comment by thefonso** [comment]
@Luap99 ah so you are saying just delete the files inside  ~/.config/cni/ ??

**Comment by Luap99** [comment]
yes

**Comment by aheilmaier** [comment]
delete of ~/.config/cni/ also worked for me with podman 5.0.0-dev
