### ISSUE TITLE
Quadlets in folders inside containers/systemd

### ISSUE THREAD

**Issue by herzenschein** [containers/podman#20236]
### Feature request description

It seems systemd services are not generated for Quadlets inside directories in the unit search paths. This means that all container, network, volume and kube files need to be bundled together in e.g. ~/.config/containers/systemd to generate systemd services, which can become messy when you have more than a few Quadlets.

### Suggest potential solution

It would be nice if the unit search paths for Quadlets also applied recursively, looking into inner directories.

This would allow to group container files together, which is useful for example if a service has multiple dependent services, like databases. This would also be handy for logically bundling network, volume and kube files together with their respective container files.

**Comment by flouthoc** [comment]
@vrothberg PTAL

**Comment by vrothberg** [comment]
Thanks for reaching out.  This is being addressed by the just released Podman v4.7.

Please fill out the entire issue template next time (including `podman info` output), so we know which version you're running on.
