### ISSUE TITLE
`podman search --list-tags` doesn't return all tags

### ISSUE THREAD

**Issue by lnicola** [containers/podman#20231]
### Issue Description

`podman search docker.io/debian --list-tags` only returns tags for version `10`

### Steps to reproduce the issue

1. `podman search docker.io/debian --list-tags`

### Describe the results you received

```
NAME                      TAG
docker.io/library/debian  10
docker.io/library/debian  10-slim
docker.io/library/debian  10.0
docker.io/library/debian  10.0-slim
docker.io/library/debian  10.1
docker.io/library/debian  10.1-slim
docker.io/library/debian  10.10
docker.io/library/debian  10.10-slim
docker.io/library/debian  10.11
docker.io/library/debian  10.11-slim
docker.io/library/debian  10.12
docker.io/library/debian  10.12-slim
docker.io/library/debian  10.13
docker.io/library/debian  10.13-slim
docker.io/library/debian  10.2
docker.io/library/debian  10.2-slim
docker.io/library/debian  10.3
docker.io/library/debian  10.3-slim
docker.io/library/debian  10.4
docker.io/library/debian  10.4-slim
docker.io/library/debian  10.5
docker.io/library/debian  10.5-slim
docker.io/library/debian  10.6
docker.io/library/debian  10.6-slim
docker.io/library/debian  10.7
```

### Describe the results you expected

Debian 11, 12 etc.

### podman info output

`podman 4.7.0` on Fedora 38 and `quay.io/containers/podman:v4.6.1` (`v4.7.0` is missing)

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional information

Found by @strk.

**Comment by Luap99** [comment]
The default display limit is 25, you have to add `--limit 100` or much more to get all results
