### ISSUE TITLE
Please support `--module` feature in quadlet

### ISSUE THREAD

**Issue by mhjacks** [containers/podman#20246]
### Feature request description

Podman now supports a `module` option to enable setting multiple containers.conf level options. Quadlet should support using this feature as well.

### Suggest potential solution

Add the necessary code in the quadlet config file and in constructing podman commands to enable its usage

### Have you considered any alternatives?

The PodmanArgs catch-all may work for some cases, but according to the community discussion on 10/3/2023 the order of command line args is very important; --module options need to be set early in the command line

**Comment by vrothberg** [comment]
Thanks for opening the issue, @mhjacks.

As so often, I wonder about the right name of the option.  We opted for `--module` instead of `--containers-conf-module` to keep the name short.  But in Quadlet, I feel like `ContainersConfModule` is probably the right choice.
@rhatdan @ygalblum WDYT?

**Comment by sanmai-NL** [comment]
`--module` is too short in my mind, even for the original option. It confused me upon reading the release notes.

**Comment by vrothberg** [comment]
> `--module` is too short in my mind, even for the original option. It confused me upon reading the release notes.

Thanks for the feedback, @sanmai-NL.  Are the --help message and the docs sufficiently clear?  I'm happy to improve but probably need an outside perspective.

**Comment by rhatdan** [comment]
I think we are bike shedding. 
Either 
```
ConfModule
Module
```
ContainersConfModule seems like a stutter, since you are in the [containers] section. (Although will this work in a .kube, .volume, .network file?

**Comment by vrothberg** [comment]
@rhatdan please look at the PR https://github.com/containers/podman/pull/20253. We're already on `ContainersConfModule`.  IMO it doesn't hurt in a write-once file to be explicit.
