### ISSUE TITLE
PODMAN 4.7.1 - Missing MacOS Installers (.pkg files)

### ISSUE THREAD

**Issue by kcak11** [containers/podman#20287]
PODMAN 4.7.1 - Missing MacOS Installers (.pkg files)

In the latest 4.7.1 release page, the MacOS .pkg installers are missing.

https://github.com/containers/podman/releases/tag/v4.7.1

Will these not be shipped anymore?

**Comment by vrothberg** [comment]
@lsm5 PTAL

**Comment by Luap99** [comment]
The automatic CI job failed so they did not get build: https://github.com/containers/podman/actions/runs/6422307581
cc @ashley-cui

**Comment by ashley-cui** [comment]
Should be there now! Apparently if you change your appleid password it removes all the CI keys from your account 😢

**Comment by lsm5** [comment]
> Should be there now! Apparently if you change your appleid password it removes all the CI keys from your account 😢

@ashley-cui is this your personal id and password? Can we get something for the org / team by any chance?

**Comment by ashley-cui** [comment]
It's the my ID but it's under the RH Apple cert org. AFAIK, it looks like signing requires a dev id and I don't think there are team dev-id's.
