### ISSUE TITLE
Podman build multi-stage with squash should not remove intermediate base image from local cache

### ISSUE THREAD

**Issue by gabs79** [containers/podman#20291]
### Issue Description

Building a multi-stage image with squash removes intermediate base image from local cache.

### Steps to reproduce the issue

Steps to reproduce the issue

`podman build -t parent-one - <<EOF
FROM alpine
RUN echo "parent-one" > parent-one
EOF

podman build -t parent-two - <<EOF
FROM alpine
RUN echo "parent-two" > parent-two
EOF

podman build -t multi-stage - <<EOF
FROM localhost/parent-one as p1
FROM localhost/parent-two
COPY --from=p1 parent-one .
EOF

podman build -t multi-stage-squash --squash - <<EOF
FROM localhost/parent-one as p1
FROM localhost/parent-two
COPY --from=p1 parent-one .
EOF

podman image ls
`

### Describe the results you received

local/parent-one built image vanished from my local cache.
Note, if we remove the '--squash' option, it persists.

![image](https://github.com/containers/podman/assets/5895852/0f38d3f6-441e-4a21-b86f-4ca731450e16)

### Describe the results you expected

The image "parent-one" should have not been removed from the local cache.

Which is the case when I remove the --squash option.
Note, I was not able to reproduce with buildah.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.7-150400.3.11.1.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: unknown'
  cpuUtilization:
    idlePercent: 82.64
    systemPercent: 13.14
    userPercent: 4.21
  cpus: 1
  distribution:
    distribution: '"opensuse-leap"'
    version: "15.4"
  eventLogger: file
  hostname: localhost
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.21-150400.24.28-default
  linkmode: dynamic
  logDriver: journald
  memFree: 3288801280
  memTotal: 4107755520
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.8-150000.49.1.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.8
      commit: v1.1.8-0-g82f18fe0e44a
      spec: 1.0.2-dev
      go: go1.21.0
      libseccomp: 2.5.3
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-150300.8.5.2.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: unknown
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 5
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 29m 19.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.opensuse.org
  - registry.suse.com
  - docker.io
store:
  configFile: /home/vagrant/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/vagrant/.local/share/containers/storage
  graphRootAllocated: 44069601280
  graphRootUsed: 1332903936
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 4
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/vagrant/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.4
  Built: 1680004800
  BuiltTime: Tue Mar 28 12:00:00 2023
  GitCommit: ""
  GoVersion: go1.18.10
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.4
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

I'm in VirtualBox, buy tried this also out of VM in redhat 8.8

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by flouthoc** [comment]
Using `--layers` with `--squash` should prevent this but there is also a bug in buildah and PR https://github.com/containers/buildah/pull/5081 should fix it.

**Comment by gabs79** [comment]
@flouthoc thank you for looking into this.

Note, at the podman-cli level when building an image, we cannot specify both options (--layers  and --squash), otherwise the error below is shown:

`Error: cannot specify --squash, --squash-all and --layers options together`

**Comment by flouthoc** [comment]
@gabs79 You are using very old version of podman newer version allows `--squash-all` and `--layers` together.

**Comment by gabs79** [comment]
> Using `--layers` with `--squash` should prevent this but there is also a bug in buildah and PR [containers/buildah#5081](https://github.com/containers/buildah/pull/5081) should fix it.

You are right, I was able to prevent this behavior with a newer version of Podman 4.7.1., by using `--squash-all` and `--layers` together.
Although, I'm assuming with the proper fix above, it would only need --squash, correct?

**Comment by flouthoc** [comment]
Yes the fix is in the above PR
