### ISSUE TITLE
wait command on podman play kube

### ISSUE THREAD

**Issue by dargentieri** [containers/podman#20307]
### Issue Description

Hello,
I read on the [documentation](https://docs.podman.io/en/latest/markdown/podman-kube-play.1.html#wait-w) that I can use the command **--wait** to execute the pod and containers in the foreground. 
When I launch the command wait, I have an error (*Error: unknown flag: --wait*).

My podman version is 4.4.1

### Steps to reproduce the issue

podman play kube --wait app-config.yaml

### Describe the results you received

Error: unknown flag: --wait

### Describe the results you expected

the pod and containers in the foreground

### podman info output

```yaml
Error: unknown flag: --wait
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by vrothberg** [comment]
Thanks for reaching out!

The `--wait` has been added after the 4.4 release.  The docs point by default to the "latest" development branch.  The [docs for 4.4](https://docs.podman.io/en/v4.4/markdown/podman-kube-play.1.html) do not include the `--wait` flag.
