### ISSUE TITLE
Podman checkpoint takes a long time

### ISSUE THREAD

**Issue by wanghang7410** [containers/podman#20325]
### Issue Description

I used the "podman checkpoint" command to take a memory snapshot of a container running a Python program that consumes 1GB of memory. However, I noticed significant variations in the time required for multiple executions of the "podman checkpoint" command, with some taking as little as 1.4 seconds and others as long as 31.5 seconds.

### Steps to reproduce the issue

Steps to reproduce the issue
1.podman pull python:latest
2.podman run -e PYTHONUNBUFFERED=1 python:latest python -c "import os
import time
import gc
import random
import string

total_memory_size = 1 * 1024 * 1024 * 1024  # 10GB

def generate_random_data(size):
    return bytearray(''.join(random.choices(string.ascii_letters + string.digits, k=size)), 'utf-8')

memory_usage = bytearray()
current_memory_size = 0

while current_memory_size < total_memory_size:
    random_data = generate_random_data(1024 * 1024)
    memory_usage.extend(random_data)
    current_memory_size += len(random_data)

for i in range(1, 6000):
    print(i)
    time.sleep(1)

memory_usage = None
gc.collect()
"
3. Wait for digital print
podman container checkpoint <containerId>

### Describe the results you received

Sometimes it takes only 1.4 seconds to checkpoint, others it takes 31.5 seconds.

### Describe the results you expected

Expect the checkpoint to end soon

### podman info output

```yaml
打podman镜像花费时间 1.430109339s"Id":"d108d0c4564e4f1be2a534930d4fb13c68dceb43de398a48c0b71dde0b7f608f" "runtime checkpoint duration:579920,"criu statistics":f"freezing time":1028,"frozen time":514373,"memdump time":407886,"memwrite time":346097,"pages scanned":5233468,"pages written": 2677471]开始恢复podman镜像恢复podman镜像花费时间 769.38059ms

开始打podman镜像
2023-10-10720:22:21+8:09 3927打podman镜像花费时间 31.546884985s"id":"d108d0c4564e4f1be2a534930d4fb13c68dceb43de398a48c0b71ddeb7f608f","runtime checkpoint duration':663466,"criu statistics": "freezing time":101410,"frozen time":512639,"mendump time":407629,"memwritetime":345821,pages scanned":5233468, "pages written":2677471]开始恢复podman镜像
恢复podman镜像花费时间 730.360804ms
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

host:
  arch: amd64
  buildahVersion: 1.32.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc38.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 99.88
    systemPercent: 0.08
    userPercent: 0.04
  cpus: 8
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: server
    version: "38"
  eventLogger: journald
  freeLocks: 2019
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.5.6-200.fc38.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 31266705408
  memTotal: 33603272704
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.8.0-1.fc38.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.8.0
    package: netavark-1.8.0-2.fc38.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.8.0
  ociRuntime:
    name: runc
    package: runc-1.1.8-1.fc38.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.8
      spec: 1.0.2-dev
      go: go1.20.7
      libseccomp: 2.5.3
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20230908.g05627dc-1.fc38.x86_64
    version: |
      pasta 0^20230908.g05627dc-1.fc38.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.1-1.fc38.x86_64
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 15h 24m 12.00s (Approximately 0.62 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 29
    paused: 0
    running: 0
    stopped: 29
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 535531360256
  graphRootUsed: 20825763840
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.7.0
  Built: 1695839078
  BuiltTime: Thu Sep 28 02:24:38 2023
  GitCommit: ""
  GoVersion: go1.20.8
  Os: linux
  OsArch: linux/amd64
  Version: 4.7.0

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by giuseppe** [comment]
@adrianreber PTAL

**Comment by wanghang7410** [comment]
@adrianreber 
@cost time 1.430109339s
{"Id":"d108d0c4564e4f1be2a534930d4fb13c68dceb43de398a48c0b71dde0b7f608f" "runtime checkpoint duration:579920,"criu statistics":f"freezing time":1028,"frozen time":514373,"memdump time":407886,"memwrite time":346097,"pages scanned":5233468,"pages written": 2677471}

cost time 31.546884985s
{"id":"d108d0c4564e4f1be2a534930d4fb13c68dceb43de398a48c0b71ddeb7f608f","runtime checkpoint duration':663466,"criu statistics": "freezing time":101410,"frozen time":512639,"mendump time":407629,"memwritetime":345821,pages scanned":5233468, "pages written":2677471}

**Comment by adrianreber** [comment]
Are you sure that is the original output of podman? It mixes single and double quotes and doesn't seem to be valid JSON.

Try to add the output of `podman container checkpoint` as pre-formatted code block.

**Comment by rhatdan** [comment]
Since we never heard back a response, closing.
