### ISSUE TITLE
podman 4.6.2 specify container IP in `compose.yml` not work

### ISSUE THREAD

**Issue by WittonBell** [containers/podman#20330]
### Issue Description

podman version 4.6.2  specify container IP in `compose.yml` not work.
use `docker-compose.exe` on windows to compose to remote ubuntu.

my `compose.yml` like this:
`
version: "3.9"

...

services:
  ms:
    <<: *build
    command: [ ]
    networks:
      network:
        ipv4_address: 18.1.1.2

...

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet:  18.1.1.0/24
`

when start the `ms` service, the IP is a random allocate IP such as `18.1.1.25` instead of  `18.1.1.2`.

windows Docker Compose version v2.2.1

```
$ podman version
Client:       Podman Engine
Version:      4.6.2
API Version:  4.6.2
Go Version:   go1.18.1
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. create `compose.yml` and `Dockerfile` and specify service IP in `compose.yml`
2. remote ubuntu run `sudo podman system service --time=0 tcp:0.0.0.0:2345`
3. use windows Docker Compose to compose: `docker-compose --host "tcp://192.168.1.8:2345" -f compose.yml -p demo up --remove-orphans -d`, replace IP to yours.
4. detect the service that specfy IP is correctly.

### Describe the results you received

The IP of service is not my specfiy IP  in `compose.yml`

### Describe the results you expected

The IP of service is  my specfiy IP  in `compose.yml`

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.31.2
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2:2.1.8-0ubuntu22.04+obs16.15_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.8, commit: '
  cpuUtilization:
    idlePercent: 97.05
    systemPercent: 1.44
    userPercent: 1.51
  cpus: 4
  databaseBackend: boltdb
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  freeLocks: 2033
  hostname: witton
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.0-83-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 85356544
  memTotal: 2021994496
  networkBackend: cni
  networkBackendInfo:
    backend: cni
    dns:
      package: golang-github-containernetworking-plugin-dnsname_1.3.1+ds1-2_amd64
      path: /usr/lib/cni/dnsname
      version: |-
        CNI dnsname plugin
        version: 1.3.1
        commit: unknown
    package: 'containernetworking-plugins, golang-github-containernetworking-plugin-dnsname:
      /usr/lib/cni'
    path: /usr/lib/cni
  ociRuntime:
    name: crun
    package: crun_101:1.9.2-0ubuntu22.04+obs60.3_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.9.2
      commit: 35274d346d2e9ffeacb22cc11590b0266a23d634
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.0.1-2_amd64
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 3897061376
  swapTotal: 4082102272
  uptime: 1h 46m 22.00s (Approximately 0.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/witton/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/witton/.local/share/containers/storage
  graphRootAllocated: 72329912320
  graphRootUsed: 6494203904
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 4
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/witton/.local/share/containers/storage/volumes
version:
  APIVersion: 4.6.2
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.18.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.2
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

windows Docker Compose version v2.2.1

**Comment by rhatdan** [comment]
@Luap99 PTAL

**Comment by Luap99** [comment]
We have this exact case a test in our CI running so I expect this to work. https://github.com/containers/podman/blob/main/test/compose/ipam_set_ip/docker-compose.yml

Can you share your full compose file?

**Comment by WittonBell** [comment]
`Dockerfile`:
```
FROM nginx:latest

ENTRYPOINT ["nginx", "-g", "daemon off;"]
```

`compose.yml`:
```
version: "3.9"

x-base:
  &build
  image: ngx
  build:
    context: .
    dockerfile: Dockerfile
  stop_grace_period: 5m
  stop_signal: SIGTERM

services:
  ms:
    <<: *build
    networks:
      network:
        ipv4_address: 18.1.1.2

networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  18.1.1.0/24
```

up cmd:`docker-compose --host "tcp://192.168.1.8:2345" -f compose.yml -p demo up --remove-orphans -d`
down cmd:`docker-compose --host "tcp://192.168.1.8:2345" -f compose.yml -p demo down --rmi all --remove-orphans --volumes`

Multiple `up` and `down` to reproduce.

**Comment by Luap99** [comment]
I cannot reproduce, I suggest you update your compose version to something up to date and try again.

**Comment by WittonBell** [comment]
My `docker-compose.exe` version is v2.2.1`. I have tried to upgrade to the latest version, but encountered many problems and did not upgrade.

I use podman 3.4.4 no this issue, but has issue [#20213](https://github.com/containers/podman/issues/20213):

```
WARN[0063] Error validating CNI config file /home/xxx/.config/cni/net.d/dxs_network.conflist: [plugin bridge does not support config version "1.0.0" plugin portmap does not support config version "1.0.0" plugin firewall does not support config version "1.0.0" plugin tuning does not support config version "1.0.0"] 
ERRO[0063] error loading cached network config: network "dxs_network" not found in CNI cache 
WARN[0063] falling back to loading from existing plugins on disk 
WARN[0063] Error validating CNI config file /home/xxx/.config/cni/net.d/dxs_network.conflist: [plugin bridge does not support config version "1.0.0" plugin portmap does not support config version "1.0.0" plugin firewall does not support config version "1.0.0" plugin tuning does not support config version "1.0.0"] 
ERRO[0063] Error tearing down partially created network namespace for container b84152202a30908f7961beac738b7216b88c2ced9e885c2de2cd460d133284e9: CNI network "dxs_network" not found 
```

How to resove it if I keep use ubuntu default podman version 3.4.4? Now I change the `cniVersion` from `1.0.0` to `0.4.0` manually everytime.Very troublesome.

btw, I use docker instead of podman work correctly.

**Comment by Luap99** [comment]
The simple answer is do not use CNI, use netavark. But especially do not use old outdated podman versions such as 3.4.4, I don't know what ubuntu did but the ubuntu 2204 podman package is just completely broken due the CNI version change (https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/2024394). There is nothing upstream can do about that.

If you want an update to date podman you can use `podman machine` to create a fedora based WSL distro on windows which should work much better than the outdated ubuntu versions.
