### ISSUE TITLE
network connect/disconnect with port forwarding: curl: empty results

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#20335]
This looks identical to #11248, except this one is *root*, not rootless. And, sigh, is only happening under VFS (which makes no sense to me).
```
[+1694s] not ok 482 podman network connect/disconnect with port forwarding
...
<+020ms> # # podman run -d -p 5074:80 --hostname host-V1gILFpgNx --network testnet-ursuRNcqbm -v /var/tmp/podman_bats.h95bel/hello.txt:/var/www/index.txt:Z -w /var/www quay.io/libpod/testimage:20221018 /bin/busybox-extras httpd -f -p 80
<+505ms> # e748507a00fcf0651f6a8cbe66c04d4cfb8e154720ff8af6fcb90aad29c57e51
         # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
         # #|     FAIL: curl 127.0.0.1:/index.txt
         # #| expected: '8nrO6jGUa1Rp16iHkFilXAz2GKbQm8'
         # #|   actual: ''
         # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
The failing command is `curl --max-time 3 -s $SERVER/index.txt`. Do note that this is not a curl-error-7 (connection failure). Curl connects, but gets empty results. This is disturbingly similar to other VFS flakes I'm seeing involving empty files that should not be empty, but I'm going to ignore that for now.

### [sys] podman network connect/disconnect with port forwarding
* fedora-38 : sys podman fedora-38 root host boltdb
    * [10-10 08:01](https://api.cirrus-ci.com/v1/artifact/task/6116867048210432/html/sys-podman-fedora-38-root-host-boltdb.log.html#t--00482)
* fedora-38 : sys remote fedora-38 root host boltdb [remote]
    * [10-10 07:48](https://api.cirrus-ci.com/v1/artifact/task/6327973280743424/html/sys-remote-fedora-38-root-host-boltdb.log.html#t--00482)
    * [10-09 19:18](https://api.cirrus-ci.com/v1/artifact/task/5530963996835840/html/sys-remote-fedora-38-root-host-boltdb.log.html#t--00482)
    * [10-03 13:37](https://api.cirrus-ci.com/v1/artifact/task/6031089584570368/html/sys-remote-fedora-38-root-host-boltdb.log.html#t--00481)
    * [10-03 12:23](https://api.cirrus-ci.com/v1/artifact/task/6702977679884288/html/sys-remote-fedora-38-root-host-boltdb.log.html#t--00481)

Seen in: sys podman+remote fedora-38 root host boltdb

**Comment by Luap99** [comment]
Yeah doesn't look like a network problem if curl doesn't print an error.
Given your other VFS bugs I would agree that this file appears to be empty for some reason. Given the file is only bind mounted the easiest explanation is that the file was unmounted.
