### ISSUE TITLE
Error while running podman machine start

### ISSUE THREAD

**Issue by rajeshnawale** [containers/podman#20344]
### Issue Description

While running podman machine start getting below error.

podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code 1, stderr: qemu-system-x86_64: -virtfs local,path=/scratch/obaas,mount_tag=vol0,security_model=none: 'virtio-9p-pci' is not a valid device model name

podman version
Client:       Podman Engine
Version:      4.4.1
API Version:  4.4.1
Go Version:   go1.19.10
Built:        Fri Sep 22 09:47:59 2023
OS/Arch:      linux/amd64

podman info
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.6-1.module+el8.8.0+21045+adcb6a64.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.6, commit: 31a72124adb6095b6be85b27e3e481313a1cea96'
  cpuUtilization:
    idlePercent: 97.93
    systemPercent: 0.71
    userPercent: 1.36
  cpus: 4
  distribution:
    distribution: '"ol"'
    variant: server
    version: "8.7"
  eventLogger: file
  hostname: xx.xx.xx.xx
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.0-105.125.6.2.2.el8uek.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 24734564352
  memTotal: 31223042048
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.4-1.0.1.module+el8.8.0+21119+51f68ed8.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.4
      spec: 1.0.2-dev
      go: go1.19.10
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_SYS_CHROOT,CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.module+el8.8.0+21045+adcb6a64.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 16724779008
  swapTotal: 16724779008
  uptime: 1h 31m 40.00s (Approximately 0.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - container-registry.oracle.com
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 95435374592
  graphRootUsed: 25995190272
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.4.1
  Built: 1695376079
  BuiltTime: Fri Sep 22 09:47:59 2023
  GitCommit: ""
  GoVersion: go1.19.10
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.1

 rpm -q podman
podman-4.4.1-15.module+el8.8.0+21167+8358bf95.x86_64

### Steps to reproduce the issue

Steps to reproduce the issue
# podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code 1, stderr: qemu-system-x86_64: -virtfs local,path=/scratch/obaas,mount_tag=vol0,security_model=none: 'virtio-9p-pci' is not a valid device model name

### Describe the results you received

Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code 1, stderr: qemu-system-x86_64: -virtfs local,path=/scratch/obaas,mount_tag=vol0,security_model=none: 'virtio-9p-pci' is not a valid device model name

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
Is there a reason you are trying to run `podman machine` on linux? You can just use podman natively without VM on linux.

Regardless this looks like your qemu install does not support 9p mounts so it does not look like a podman problem.

**Comment by rajeshnawale** [comment]
I am trying to run minikube on podman 
Following the doc https://minikube.sigs.k8s.io/docs/drivers/podman/

**Comment by rajeshnawale** [comment]
Where I can get the help for qemu ?
I have installed qemu-kvm 
dnf info qemu-kvm
Last metadata expiration check: 1 day, 2:16:52 ago on Wed 11 Oct 2023 09:17:32 AM GMT.
Installed Packages
Name         : qemu-kvm
Epoch        : 15
Version      : 6.2.0
Release      : 33.module+el8.8.0+21164+ed375313
Architecture : x86_64
Size         : 0.0  
Source       : qemu-kvm-6.2.0-33.module+el8.8.0+21164+ed375313.src.rpm
Repository   : @System
From repo    : ol8_appstream
Summary      : QEMU is a machine emulator and virtualizer
URL          : http://www.qemu.org/
License      : GPLv2 and GPLv2+ and CC-BY
Description  : qemu-kvm is an open source virtualizer that provides hardware
             : emulation for the KVM hypervisor. qemu-kvm acts as a virtual
             : machine monitor together with the KVM kernel modules, and emulates the
             : hardware for a full system such as a PC and its associated peripherals.

**Comment by Luap99** [comment]
> I am trying to run minikube on podman
Following the doc https://minikube.sigs.k8s.io/docs/drivers/podman/

there it says:
> On all other operating systems, make sure to create and start the virtual machine that is needed for Podman.

This instruction does not apply to linux, you can use podman natively without the machine.

If you use distros shipping old versions is it always recommend to go through the distro support/bug channels for help not upstream.
