### ISSUE TITLE
Saving key "podman-machine-default" failed: Permission denied

### ISSUE THREAD

**Issue by fervand1** [containers/podman#20355]
### Issue Description

When I run the podman machine init command , it fails with following error

PS C:\> podman machine init
Extracting compressed file: podman-machine-default_fedora-podman-amd64-v38.0.24.tar: done
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
Configuring system...
Generating public/private ed25519 key pair.
Saving key "podman-machine-default" failed: Permission denied
Error: could not create ssh keys: exit status 1

### Steps to reproduce the issue

Steps to reproduce the issue
1. Install latest version of podman for windows
2. Execute podman machine init on windows terminal

### Describe the results you received

Saving key "podman-machine-default" failed: Permission denied
Error: could not create ssh keys: exit status 1

I tried reinstalling ubuntu in WSL
Also,
wsl --unregister podman-machine-default
and retired the command

### Describe the results you expected

Installation steps mentioned here to run successfully
https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md

### podman info output

```yaml
PS C:\> podman info
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.7.1/libpod/_ping": dial unix ///run/podman/podman.sock: connect: An invalid argument was supplied.
PS C:\> podman version
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.7.1/libpod/_ping": dial unix ///run/podman/podman.sock: connect: An invalid argument was supplied.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Windows 10 OS running windows terminal

**Comment by baude** [comment]
hello @fervand1 thanks for the report.  your ubuntu image should have nothing to do with what podman is doing ... so i think you can leave that alone.

by default, podman will attempt to save keys to ~/.ssh ... does that directory exist? are the permissions more exclusive than it needs to be?  does the key possibly already exist from a failed session?

**Comment by baude** [comment]
gentle ping

**Comment by fervand1** [comment]
@baude I am on the windows 10, and yes the directory exists and am able to create ssh keys using ssh-keygen. There are existing keys in it . But should it not create a new one if it already exists?
![image](https://github.com/containers/podman/assets/44014460/0fc36dc1-962e-4dc9-ab59-f255b280d132)

**Comment by fervand1** [comment]
@baude We can close this, It was directory permissions issue.
Steps I perfomed:
- Deleted existing .ssh directory
- Created a new directory with mkdir in windows terminal
- Run `wsl --unregister podman-machine-default` to remove failed machine entry
- Run `podman machine init` and it created machine successfully this time
