### ISSUE TITLE
Podman compose on Windows

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman#20373]
Following a customer call, I was trying to setup a compose sample.

I ended up with: Error: socket of machine is not set

Seems on Windows PodmanSocket is not returned by PodmanPipe

I used the sample from https://github.com/docker/awesome-compose/tree/master/nginx-golang-postgres

See
https://github.com/containers/podman/blob/dabf6c83a7793a2e5c76a54d5a41e6f4d2e62660/cmd/podman/compose.go#L187

**Comment by rhatdan** [comment]
@n1hility PTAL

**Comment by lstocchi** [comment]
@n1hility do you mind if i take this? I work in the Podman Desktop team and this could be a good opportunity to start looking at the podman codebase

**Comment by Luap99** [comment]
@lstocchi Feel free to work on it, as long as nobody is assigned it is open for everyone.

**Comment by n1hility** [comment]
+1
