### ISSUE TITLE
Registry not failing over to next mirror when error occurs

### ISSUE THREAD

**Issue by Mrls94** [containers/podman#20374]
### Issue Description

Recently we noticed a failure pulling a container image from quay.io but the mirror we setup (docker.io) was not tried. Upon further inspect looks like it was a fault in one of the CDN servers of quay.io but we would have expected after the quay.io pull failed to failover to docker.io mirror but it did not. 

While debugging the issue we noticed that when blocking all traffic from quay.io it does failover to docker.io but when ONLY restricting the CDN servers failover doesn't work.

In our tests we setup bogus ips in hosts file to simulate quay failure.

This hosts file works and fails over to docker.io mirror
```
10.11.12.13 quay.io
10.11.12.13 cdn.quay.io
10.11.12.13 cdn01.quay.io
10.11.12.13 cdn02.quay.io
10.11.12.13 cdn03.quay.io
```

this does not:

```
# 10.11.12.13 quay.io
10.11.12.13 cdn.quay.io
10.11.12.13 cdn01.quay.io
10.11.12.13 cdn02.quay.io
10.11.12.13 cdn03.quay.io
```

We would expect that failover should happen when mirror pull fails at all steps.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Set up a registries conf file
```
[[registry]]
prefix = "registry.bogus.com/prometheus"
location = "this-domain-is-unused.com"

[[registry.mirror]]
location = "quay.io/prometheus"

[[registry.mirror]]
location = "docker.io/prom"

[aliases]
"node-exporter" = "registry.bogus.com/prometheus/node-exporter"
```
2. Add bogus ips to /etc/hosts file for quay cdn servers
```
10.11.12.13 cdn.quay.io
10.11.12.13 cdn01.quay.io
10.11.12.13 cdn02.quay.io
10.11.12.13 cdn03.quay.io
```
3. podman pull node-exporter

### Describe the results you received

Pull errors out with a timeout getting the image
`Error: copying system image from manifest list: parsing image configuration: Get "https://cdn03.quay.io/ .....  dial tcp 10.11.12.13:443: i/o timeout`

### Describe the results you expected

Pull works or at least tries to pull from other mirror docker.io

### podman info output

```yaml
podman version

Client:       Podman Engine
Version:      4.7.0
API Version:  4.7.0
Go Version:   go1.21.1
Built:        Wed Sep 27 18:18:00 2023
OS/Arch:      linux/amd64
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
@vrothberg @mtrmac PTAL

**Comment by mtrmac** [comment]
Yes, that’s how it works now, per the man page:
> The mirrors are attempted in the specified order; the first one that can be contacted and contains the image will be used

Once a mirror is chosen, only that one is used. There is no per-request mirror choice, nor any mirror failover if a mirror starts to provide data but fails in the middle.

It’s a reasonable RFE to ask for the mirror code to deal with weird broken mirrors, and transient failures, more reliably. Typically I’d expect the local mirror to be notably more reliable than any more remote registry, so as a _very unqualified_ guess, to me it seems not to be a very high priority item.

**Comment by rhatdan** [comment]
If you want to continue to pursue mirror failover open an issue in containers/image, this is not really a Podman problem.

**Comment by edsantiago** [comment]
Quick drive-by comment: `cdn03.quay.io` has been broken for many years. The workaround is to disable `systemd-resolve`:
```diff
--- a/authselect/nsswitch.conf  Sun Dec 03 05:23:47 2023 -0700
+++ b/authselect/nsswitch.conf  Sun Dec 03 05:44:38 2023 -0700
@@ -9,3 +9,3 @@
 group:      files sss systemd
-hosts:      files myhostname mdns4_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns
+hosts:      files dns myhostname mdns4_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns
 services:   files sss
```
(disabling `systemd-resolve` is a good idea in general, it does not play well with openvpn and is a frequent source of frustration)
