### ISSUE TITLE
Can not run MongoDB container in a pod on M1 Mac

### ISSUE THREAD

**Issue by holen-zhang** [containers/podman#20370]
### Issue Description

Podman failed to run the MongoDB container from docker.io/library/mongo:latest in a pod. And I don't get enough information to debug the error.

It is working when I run _podman run -d --name=project1-web docker.io/library/mongo:latest_ without the _--pod_ option.
However, it is giving me _Error: starting some containers: internal libpod error_ when I run _podman run -d --pod=backendPod --name=project1-web docker.io/library/mongo:latest_

BTW, I tried this on Ubuntu and it is working. Seems only happens on M1 Mac

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create a pod with: _podman pod create --name backendPod -p 27017:27017 -p 5000:5000_
2. Run: _podman run -d --pod=backendPod --name=project1-web docker.io/library/mongo:latest_
3. Error message _Error: starting some containers: internal libpod error_ is given.

### Describe the results you received

The only result I got is the error message: Error: starting some containers: internal libpod error

### Describe the results you expected

It should run the container in the pod successfully.

### podman info output

```yaml
host:
  arch: arm64
  buildahVersion: 1.32.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.7-2.fc38.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.7, commit: '
  cpuUtilization:
    idlePercent: 99.76
    systemPercent: 0.16
    userPercent: 0.08
  cpus: 4
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: coreos
    version: "38"
  eventLogger: journald
  freeLocks: 2043
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.5.5-200.fc38.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 7239319552
  memTotal: 7722053632
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.7.0-1.fc38.aarch64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.7.0
    package: netavark-1.7.0-1.fc38.aarch64
    path: /usr/libexec/podman/netavark
    version: netavark 1.7.0
  ociRuntime:
    name: crun
    package: crun-1.9.2-1.fc38.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.9.2
      commit: 35274d346d2e9ffeacb22cc11590b0266a23d634
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20230908.g05627dc-1.fc38.aarch64
    version: |
      pasta 0^20230908.g05627dc-1.fc38.aarch64-pasta
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.1-1.fc38.aarch64
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 32m 49.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 99252940800
  graphRootUsed: 3300171776
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.7.0
  Built: 1695839065
  BuiltTime: Wed Sep 27 14:24:25 2023
  GitCommit: ""
  GoVersion: go1.20.8
  Os: linux
  OsArch: linux/arm64
  Version: 4.7.0
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

M1 Mac

**Comment by holen-zhang** [comment]
Anyone reviewing this issue? Or at least let me know whether this is reproducible.

**Comment by eriksjolund** [comment]
I could not reproduce on a Fedora CoreOS 39.20231006.1.0 (aarch64) VM.


rootless:
```
[test@localhost ~]$  podman pod create --name backendPod -p 27017:27017 -p 5000:5000
33f56e3e877981b0e2283903331283b892dbb0d8a4f13d453d4800a402cc953e
[test@localhost ~]$  podman run -d --pod=backendPod --name=project1-web docker.io/library/mongo:latest
Trying to pull docker.io/library/mongo:latest...
Getting image source signatures
Copying blob 208482253dd3 done   | 
Copying blob 895d322e8e59 done   | 
Copying blob 53942a81bbed done   | 
Copying blob 6c77c1ea6f8e done   | 
Copying blob 9269ffa19aee done   | 
Copying blob 1ae10bad0105 done   | 
Copying blob 0beb4a4f2118 done   | 
Copying blob 26ec439e9d10 done   | 
Copying blob 6ec0210a426e done   | 
Copying config 8b10e7ef02 done   | 
Writing manifest to image destination
0e8fb629ad19c1e062e541ddc5d201ac2e215d3c99b47950beb12e82fe72baa1
[test@localhost ~]$
```

rootful:

```
[root@localhost ~]# podman pod create --name backendPod -p 27017:27017 -p 5000:5000
f5a26a79b5c6dac4a262cb0c94f961f17f3faf600d2fd2867fc0bb47d8ec90a1
[root@localhost ~]# podman run -d --pod=backendPod --name=project1-web docker.io/library/mongo:latest
Trying to pull docker.io/library/mongo:latest...
Getting image source signatures
Copying blob 208482253dd3 done   | 
Copying blob 895d322e8e59 done   | 
Copying blob 53942a81bbed done   | 
Copying blob 6c77c1ea6f8e done   | 
Copying blob 9269ffa19aee done   | 
Copying blob 1ae10bad0105 done   | 
Copying blob 0beb4a4f2118 done   | 
Copying blob 26ec439e9d10 done   | 
Copying blob 6ec0210a426e done   | 
Copying config 8b10e7ef02 done   | 
Writing manifest to image destination
9b2e038ef0c2034aaa63011bdae7a57e6bb0c923c024b59232efe4939b3444e8
[root@localhost ~]# 
```


```
$ rpm -q podman
podman-4.7.0-1.fc39.aarch64
```

**Comment by holen-zhang** [comment]
> I could not reproduce on a Fedora CoreOS 39.20231006.1.0 (aarch64) VM.
> 
> rootless:
> 
> ```
> [test@localhost ~]$  podman pod create --name backendPod -p 27017:27017 -p 5000:5000
> 33f56e3e877981b0e2283903331283b892dbb0d8a4f13d453d4800a402cc953e
> [test@localhost ~]$  podman run -d --pod=backendPod --name=project1-web docker.io/library/mongo:latest
> Trying to pull docker.io/library/mongo:latest...
> Getting image source signatures
> Copying blob 208482253dd3 done   | 
> Copying blob 895d322e8e59 done   | 
> Copying blob 53942a81bbed done   | 
> Copying blob 6c77c1ea6f8e done   | 
> Copying blob 9269ffa19aee done   | 
> Copying blob 1ae10bad0105 done   | 
> Copying blob 0beb4a4f2118 done   | 
> Copying blob 26ec439e9d10 done   | 
> Copying blob 6ec0210a426e done   | 
> Copying config 8b10e7ef02 done   | 
> Writing manifest to image destination
> 0e8fb629ad19c1e062e541ddc5d201ac2e215d3c99b47950beb12e82fe72baa1
> [test@localhost ~]$
> ```
> 
> rootful:
> 
> ```
> [root@localhost ~]# podman pod create --name backendPod -p 27017:27017 -p 5000:5000
> f5a26a79b5c6dac4a262cb0c94f961f17f3faf600d2fd2867fc0bb47d8ec90a1
> [root@localhost ~]# podman run -d --pod=backendPod --name=project1-web docker.io/library/mongo:latest
> Trying to pull docker.io/library/mongo:latest...
> Getting image source signatures
> Copying blob 208482253dd3 done   | 
> Copying blob 895d322e8e59 done   | 
> Copying blob 53942a81bbed done   | 
> Copying blob 6c77c1ea6f8e done   | 
> Copying blob 9269ffa19aee done   | 
> Copying blob 1ae10bad0105 done   | 
> Copying blob 0beb4a4f2118 done   | 
> Copying blob 26ec439e9d10 done   | 
> Copying blob 6ec0210a426e done   | 
> Copying config 8b10e7ef02 done   | 
> Writing manifest to image destination
> 9b2e038ef0c2034aaa63011bdae7a57e6bb0c923c024b59232efe4939b3444e8
> [root@localhost ~]# 
> ```
> 
> ```
> $ rpm -q podman
> podman-4.7.0-1.fc39.aarch64
> ```

Thank you! I could not reproduce it on Ubuntu 22.04 AMD64 either. Seems to only happen on M1 Mac? (My OS is sonoma by the way). I also tried to reinstall podman with brew but no luck. Will try on other Apple Silicon Macbooks.

**Comment by Luap99** [comment]
I suggest you run `podman machine ssh` and the run the same commands locally this should output relevant errors. Looks like we are loosing import error context via the remote client.

**Comment by holen-zhang** [comment]
> I suggest you run `podman machine ssh` and the run the same commands locally this should output relevant errors. Looks like we are loosing import error context via the remote client.

Hi, Paul, thank you very much! So I tried to execute the command inside the machine and got more information about the error.  It was because somehow port 27017 was in use on my machine... I should have checked that sorry, I am a newbie to podman...  it would be nice if such information could be printed not only inside the machine but also in the terminal though.

Anyhow, thank you very much for the help, and have a good one. I am closing this issue now.
