### ISSUE TITLE
Implement podman update --restart

### ISSUE THREAD

**Issue by pinko-fowle** [containers/podman#20419]
### Feature request description

I'd like to be able to do [similar to Docker](https://docs.docker.com/engine/reference/commandline/update/#restart), and update the RestartPolicy for a container.

### Suggest potential solution

On the Docker CLI, I can do `docker update --restart=never wonderous_wozniak`.

Trying to do similar in podman results in:
```sh-session
$ podman update --restart never st-postgres-13-bookworm
Error: unknown flag: --restart
```

### Have you considered any alternatives?

Unknown.

### Additional context

This is extra troublesome because `unless-stopped` restart policy doesnt work (#20418), and doing a naive solution like `always` does results in multiple containers each trying to start & grab the same ports on our machine. We would like to at least be able to tell some containers to stop restarting, but found that `update` lacks a `--restart` like Docker does.

**Comment by rhatdan** [comment]
Can you just use --replace and remove and recreate the container?

podman update can only update the cgroup settings for the running container.  The current design of Podman does not allow the modification of the core container database.

**Comment by pinko-fowle** [comment]
These are postgres, mysql, & other dev-focused data-storage containers, and have the data inside the container (volume mounts on Mac are notoriously slow). AFAIK, we'd lose the data inside the containers (unless we develop tools to copy the datas out/export the dbs). So I don't think we have a very good path to `--replace`'ing the containers.

One constraint we'd be fine living with, if this changes anything, is that we only want to change the RestartPolicy of stopped containers.

**Comment by rhatdan** [comment]
@mheon thoughts?

**Comment by mheon** [comment]
Same situation as #14678 - we can do this with SQLite, but not BoltDB. Good candidate for a Podman 5.1 once we deprecate Bolt?

**Comment by rhatdan** [comment]
Now that we are moving to sqlite, we can recosider this, correct @mheon ?

**Comment by mheon** [comment]
This will be in 5.1
