### ISSUE TITLE
Surprising code in storageService.CreateContainerStorage

### ISSUE THREAD

**Issue by mtrmac** [containers/podman#20411]
### Issue Description

I found some locally-surprising code, looking at the https://github.com/containers/podman/blob/0b0f128bfb682e871f40c80dcc63275b1599ae4f/libpod/storage.go#L70 condition:
- If `imageName` is set… it isn’t used for anything
- Actually, just the opposite, https://github.com/containers/podman/blob/0b0f128bfb682e871f40c80dcc63275b1599ae4f/libpod/storage.go#L98-L100 is dead on that path, and https://github.com/containers/podman/blob/0b0f128bfb682e871f40c80dcc63275b1599ae4f/libpod/storage.go#L101 seems to do nothing (if `imageID` really carries an image ID)
- `imageConfig` is _only_ set if `imageName` is non-empty, I wouldn’t expect the two to be related.

I didn’t check the callers / origins of the data. It’s quite possible that this does not matter in practice because `imageName`/`imageID` are always set in some particular way.

### Steps to reproduce the issue

N/A

### Describe the results you received

N/A

### Describe the results you expected

N/A

### podman info output

```yaml
N/A
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

**Comment by Luap99** [comment]
7bdfb4f9b361aca4f4f3337907feb3ca414d36e4
I guess we could drop the name argument and just rely on `imageID != ""`, in practice either both name and id are set or none in case of --rootfs.

**Comment by mtrmac** [comment]
`RuntimeContainerMetadata` is, AFAICS (??), write-only for both `ImageName` and `ImageID`. So one option could really be to just drop that value entirely.

Alternatively, document that `imageID` must be set iff `imageName` is set, make the condition `imageID != ""`, and drop the assignments at the end of that conditional path.

---

Looking at the callers a bit, yes, `imageID` is a full valid ID (not a name, not a prefix), so this seems safe to do.
