### ISSUE TITLE
Error: unable to connect to Podman socket

### ISSUE THREAD

**Issue by ImperrattoR** [containers/podman#20424]
Hello,

when I try to podman login I got:
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: dial tcp [::1]:64503: connectex: No connection could be made because the target machine actively refused it.

![image](https://github.com/containers/podman/assets/26445096/9d54de5e-77e8-420b-b600-2dc141bc0d9c)

Does anyone else have the same error and know how to fix it?

Podman version: 4.6.2.
I also have Podman Desktop installed 1.4.0

Br

**Comment by Luap99** [comment]
Did you try to do a `podman machine stop` first then start it again?

**Comment by ImperrattoR** [comment]
![image](https://github.com/containers/podman/assets/26445096/22a517b2-390d-4d9c-8c2e-ff5dba00275f)

**Comment by ImperrattoR** [comment]
I did 
```
podman machine list
podman machine stop
podman machine rm podman-machine-default
podman machine init
podman machine start
```
and it solved the issue. Thank you very much for help!!

Best regards
