### ISSUE TITLE
File based event logging does not include uid in event.

### ISSUE THREAD

**Issue by larry-cable** [containers/podman#20430]
### Issue Description

podman (events) currently supports two event logging backends:
- journald
- file based

with journald event logging configured, the journal contains the originating uid of the user that orginated each event logged.

however should a system administrator configure 'file' event logging to a single common file, and individual users do not override this within their own configuration, then the 'global' log file will contain "anonymous" events that cannot be
associated with a particular user.

### Steps to reproduce the issue

Steps to reproduce the issue
1. configure 'event_logger' in global config to 'file'
2. configure 'events_logfile_path' to reference a single events logfile
3. run some podman cmds as any arbitrary user
4. run some podman cmds as any other distinct user
5. inspect the event logfile

### Describe the results you received

n.a

### Describe the results you expected

while I did not 'expect' any particular results, it would be of value if when file logging was configured if podman events included the uid of the user to support the use case where a single event log file is used.

I suggest perhaps as an "attribute" ?

### podman info output

```yaml
n.a
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

n.a

### Additional information

only relevant if the administrator configures file event logging to a common (not per-user) log file.

**Comment by Luap99** [comment]
The uid is not part of the events, systemd will log it for all journal writes that is why you see it in journald.

If you use a log file all users must use their own individual log file so storing the uid is pointless. You should never share the events log between users as this is not secure and you will mess up podman events as it will show events from all users resulting in incorrect events that make no sense at all.
