### ISSUE TITLE
Configure Memory Limit on Containers via Quadlet

### ISSUE THREAD

**Issue by Doomsdayrs** [containers/podman#20499]
### Feature request description

Currently, Quadlet creates containers with an uncapped memory limit.

Normally when I work with Containers, I limit memory per container as a safeguard against memory leaks (Even if it is improbable).

### Suggest potential solution

A `Memory` argument that can be added under `[Container]` in a Quadlet `.container` file.

### Have you considered any alternatives?

Respecting `MemoryMax` as declared for `[Service]`

**Comment by rhatdan** [comment]
With quadlet, you can manage things like cgroups in the Systemd [service] section rather then manage it via podman.
I believe we should allow systemd to manage the cgroup, it also controls the podman service and any other tools executed.

For example in Quadlet we do.
```
[Service]
AllowedCPUs=1
CPUWeight=50
Delegate=true
IOWeight=50
ManagedOOMSwap=kill
MemorySwapMax=0
# Containers within the qm y default set OOMScoreAdj to 750
OOMScoreAdjust=500
Restart=always
Slice=QM.slice
Environment=ROOTFS=/usr/lib/qm/rootfs

[Container]
AddCapability=all
AddDevice=-/dev/kvm
AddDevice=-/dev/fuse
ContainerName=qm
Exec=/sbin/init
Network=host
PodmanArgs=--security-opt label=nested --security-opt unmask=all
ReadOnly=true
Rootfs=${ROOTFS}
SecurityLabelFileType=qm_file_t
SecurityLabelLevel=s0
SecurityLabelType=qm_t
Timezone=local
Volume=${ROOTFS}/etc:/etc
Volume=${ROOTFS}/var:/var
```

**Comment by Doomsdayrs** [comment]
> With quadlet, you can manage things like cgroups in the Systemd [service] section rather then manage it via podman. I believe we should allow systemd to manage the cgroup, it also controls the podman service and any other tools executed.

Perhaps my issue then is with the Cockpit UI. Since I have a unit with a `MemoryMax` of `2G` but it reads as the following (2.08/16.7GB)

![image](https://github.com/containers/podman/assets/38189170/d8e0d14c-ad99-4a64-80b1-18292bcd9ffa)

**Comment by dnmvisser** [comment]
If you must, you could pass those options manually using PodmanArgs:

```ini
[Container]
PodmanArgs=--memory 128m --cpus 0.25
...
```

**Comment by rhatdan** [comment]
I think we should rely on Systemd for setting this up or just use podmanargs to pass it down.  Having both will just confuse things.

**Comment by rhatdan** [comment]
Perhaps we should enhance the Quadlet man page to make it easier to discover settings for it.
