### ISSUE TITLE
`cgroup-parent` absolute paths are always relative to `/sys/fs/cgroup`

### ISSUE THREAD

**Issue by gr0l0rg** [containers/podman#20495]
### Issue Description

The docs of `podman-run` says that the `cgroup-parent` flag can be either an absolute path or a relative path. However, in reality, cgroup2 absolute paths are appended to the typical root cgroup in `/sys/fs/cgroup`, at least that's the behaviour when `--cgroup-manager` is set to `cgroupfs`. Simply if you set the cgroup path to `/tmp/a01` then it automatically becomes `/sys/fs/cgroup/tmp/a01` not `/tmp/a01`. You can see the root of the problem in this file [here](https://github.com/containers/common/blob/v0.56.0/pkg/cgroups/cgroups_linux.go) which is imported and used by this file [here](https://github.com/containers/podman/blob/642c0c798a4f204d9d7b66b3b8e80401cec27827/libpod/oci_conmon_linux.go).

Simply `cgroup-parent` only works when the path is relative to `/sys/fs/cgroup`. For example `mkdir -p /sys/fs/cgroup/a01` and using `--cgroup-parent` as `a01` works perfectly. But if you set it to `/sys/fs/cgroup/a01` then cgroup used becomes actually `/sys/fs/cgroup/sys/fs/cgroup/a01` 

### Steps to reproduce the issue

Steps to reproduce the issue
1. Set the `--cgroup-parent` flag to some cgroup2 absolute path
2. See in the logs that the absolute path is appended to `/sys/fs/cgroup`

### Describe the results you received

Absolute cgroup path used for `--cgroup-parent` are not actually used as is. They are appended to `/sys/fs/cgroup`

### Describe the results you expected

Absolute cgroup path should be used as is.

### podman info output

```yaml
You can see it simply by using `--log-level=debug` in `podman run` or even easier when checking out the cgroup fs manually.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by giuseppe** [comment]
this is not an issue.  The cgroup-parent path, like all cgroup paths, is absolute within the cgroup hierarchy.  It is not absolute in the sense of a system path.

Podman/crun doesn't support any non-standard mount for cgroups and expect the cgroup file system to be mounted at `/sys/fs/cgroup`.
