### ISSUE TITLE
podman save --format oci-dir should be able to create a tagged image

### ISSUE THREAD

**Issue by amluto** [containers/podman#20515]
### Feature request description

Tools that use OCI image directories seem to generally expect that the images intended for direct use are tagged.  For example, umoci seems to be entirely incapable of working with untagged images (https://github.com/opencontainers/umoci/issues/511).

But podman save does not appear to be able to tag its output.  For example:

`$ podman save --format=oci-dir <hash> -o <directory name>`

does not result in an `org.opencontainers.image.ref.name` annotation.

skopeo can do this:

`$ skopeo copy containers-storage:<hash> oci:<dir>:<tag>`

### Suggest potential solution

A couple of options come to mind:

podman could support colon-delimited syntax, like this:

`$ podman save --format=oci-dir <hash> -o <directory name>:<tag>`

Or podman-save.1 could suggest using skopeo for this purpose.

### Have you considered any alternatives?

Yes -- as above, skopeo can solve this particular problem.

**Comment by rhatdan** [comment]
@vrothberg @mtrmac PTAL

**Comment by vrothberg** [comment]
`podman save` inherited the UI from Docker which I personally find limited in flexibility.  Instead of `podman save`, I suggest using `podman push` which works with a specified source and destination:

`podman push <hash> oci:/tmp/foo:12345` will create an OCI image with the specified tag.

**Comment by amluto** [comment]
Nifty. Might I suggest that the podman-save manpage be updated to suggest using push instead and perhaps even to note that save fails to emit tags?

**Comment by rhatdan** [comment]
Please open a PR to make the change, I would also suggest that you meantion the change in both podman save and podman push man pages.

**Comment by vrothberg** [comment]
> Nifty. Might I suggest that the podman-save manpage be updated to suggest using push instead and perhaps even to note that save fails to emit tags?

`podman save` does not emit tags.  If you do a `podman save [...] registry.com/repo/image:tag` the tag will be preserved.  But if the image is being referenced via its digest, there is just no specified tag to preserve.

Are you interested in opening a PR for that?  If not, we can follow up.

**Comment by amluto** [comment]
> Please open a PR to make the change, I would also suggest that you meantion the change in both podman save and podman push man pages.

Will do (probably tomorrow).  I wrote a first draft of the podman save part:

https://github.com/amluto/podman/tree/save-docs

> `podman save` does not emit tags. If you do a `podman save [...] registry.com/repo/image:tag` the tag will be preserved. But if the image is being referenced via its digest, there is just no specified tag to preserve.
> 
> Are you interested in opening a PR for that? If not, we can follow up.

Maybe?  The current semantics are far from clear to me, and I have no idea whether the current semantics are intentional (or are intentional in the sense of bug-for-bug compatibility with Docker).  Are you saying that, if the image being saved is already tagged, then podman save will copy the literal tag name to the destination?

Perhaps someone familiar with the current and intended semantics of podman save should be the one to document it :)

**Comment by vrothberg** [comment]
>  Are you saying that, if the image being saved is already tagged, then podman save will copy the literal tag name to the destination?

Yes, if you replace the input image `<hash>` with `<something-tagged>` the latter will be preserved.  In your specific case, there is no tag, so `save` doesn't preserve it.
