### ISSUE TITLE
Applehv podman machine e2e "Basic ops" test timeout

### ISSUE THREAD

**Issue by cevich** [containers/podman#20535]
### Issue Description

When executing the basic podman machine e2e, every test hits 90s timeout.
[Example](https://cirrus-ci.com/task/5551147658772480?logs=e2e#L238) (log).

### Steps to reproduce the issue

Steps to reproduce the issue
1. `brew tap cfergeau/crc`
2. `brew install go go-md2man coreutils vfkit cirruslabs/cli/cirrus`
3. `sudo sysadminctl -addUser test-user`
4. `sudo rm -rf /Users/test-user/*`
5. `sudo rm -rf /Users/test-user/.??*`
6. `sudo su - test-user`
7. clone podman repo & cd into its directory
8. `make .install.ginkgo podman-remote podman-mac-helper`
9. `export MACHINE_IMAGE="https://fedorapeople.org/groups/podman/testing/applehv/arm64/fedora-coreos-38.20230925.dev.0-applehv.aarch64.raw.gz"`
10. `export CONTAINERS_MACHINE_PROVIDER="applehv"`
11. `export GINKGO_TAGS="remote exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper containers_image_openpgp remote"`
12. `./test/tools/build/ginkgo -vv --tags "$GINKGO_TAGS" -timeout=90m --trace --no-color --focus-file "basic_test.go" pkg/machine/e2e/.`

### Describe the results you received

```
run basic podman commands
/Users/test-user/podman/pkg/machine/e2e/basic_test.go:15
  Basic ops
  /Users/test-user/podman/pkg/machine/e2e/basic_test.go:28
  > Enter [BeforeEach] run basic podman commands - /Users/test-user/podman/pkg/machine/e2e/basic_test.go:21 @ 10/30/23 18:01:12.77
  < Exit [BeforeEach] run basic podman commands - /Users/test-user/podman/pkg/machine/e2e/basic_test.go:21 @ 10/30/23 18:02:34.581 (1m21.812s)
  > Enter [It] Basic ops - /Users/test-user/podman/pkg/machine/e2e/basic_test.go:28 @ 10/30/23 18:02:34.581
  /Users/test-user/podman/bin/darwin/podman machine init --image-path /private/tmp/fedora-coreos-38.20230925.dev.0-applehv.aarch64.raw.gz --now b829d29d93b8
  [FAILED] Timed out after 90.000s.
  Expected process to exit.  It did not.
  In [It] at: /Users/test-user/podman/pkg/machine/e2e/config_test.go:54 @ 10/30/23 18:04:04.635
```

### Describe the results you expected

Basic tests should all pass

### podman info output

```yaml
OS: darwin/arm64
provider: qemu
version: 4.8.0-dev
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Same results on MacOS 13 and 14

### Additional information

Manually running `./bin/darwin/podman --log-level=debug machine init --image-path $MACHINE_IMAGE --now` works perfectly fine.

I tried using [the `SpecTimeout` decorator](https://onsi.github.io/ginkgo/#the-spectimeout-and-nodetimeout-decorators) but couldn't get it to work - likely I wrote the golang bad/wrong.

**Comment by cevich** [comment]
Thanks, I'll try right away.

**Comment by cevich** [comment]
Unfortunately no love from that patch, [tests fail in the same way](https://cirrus-ci.com/task/6518703194374144?logs=e2e#L226) :cry: 

Note: [The "smoke" test takes a full (nearly) 9-minutes to run.](https://cirrus-ci.com/task/6518703194374144).  So if the basic test is doing a machine init, 90-seconds is nowhere near long enough.

Is there any way to get more info. out of the test?  Maybe it's not failing in a way you/I assume? i.e. an actual hang somewhere vs something disk related.

**Comment by ashley-cui** [comment]
Closed via https://github.com/containers/podman/pull/20696
