### ISSUE TITLE
Unreachable code

### ISSUE THREAD

**Issue by VoroninArtemii** [containers/podman#20542]
### Issue Description
The condition will always be false, so the block will never be executed.
Constant value:
https://github.com/containers/podman/blob/1146f2ca7803da4acb0539a8179ca5d540113e86/vendor/github.com/golang/protobuf/proto/text_decode.go#L22
Blocks __IF__:
https://github.com/containers/podman/blob/1146f2ca7803da4acb0539a8179ca5d540113e86/vendor/github.com/golang/protobuf/proto/text_decode.go#L33-L35
https://github.com/containers/podman/blob/1146f2ca7803da4acb0539a8179ca5d540113e86/vendor/github.com/golang/protobuf/proto/text_decode.go#L51-L59
And this case is in other file:
https://github.com/containers/podman/blob/377644640a62bec2921e64ea931facee9e3f2181/vendor/github.com/golang/protobuf/proto/text_encode.go#L23
https://github.com/containers/podman/blob/377644640a62bec2921e64ea931facee9e3f2181/vendor/github.com/golang/protobuf/proto/text_encode.go#L54-L70
Similar case is in other files:
https://github.com/containers/podman/blob/735e24331900574e30dd439cfe485a24b7ce5f3b/vendor/github.com/golang/protobuf/jsonpb/decode.go#L25
https://github.com/containers/podman/blob/735e24331900574e30dd439cfe485a24b7ce5f3b/vendor/github.com/golang/protobuf/jsonpb/decode.go#L97-L126
https://github.com/containers/podman/blob/735e24331900574e30dd439cfe485a24b7ce5f3b/vendor/github.com/golang/protobuf/jsonpb/encode.go#L26
https://github.com/containers/podman/blob/735e24331900574e30dd439cfe485a24b7ce5f3b/vendor/github.com/golang/protobuf/jsonpb/encode.go#L97-L108

**Comment by giuseppe** [comment]
this code is coming from vendored dependencies.  Please report it to the correct project.
