### ISSUE TITLE
Default override ‘run.oci.keep_original_groups’ annotation, according to a new option abort groups.

### ISSUE THREAD

**Issue by ty359** [containers/podman#20553]
### Feature request description

I think "run.oci.keep_original_groups" is an abnormal behavior of crun. When I have a "–userns=host" config, I always expect having the same groups of host. So it' better to have a new option abort this to notice the podman users.

**Comment by rhatdan** [comment]
You can just use the --group-add=keep-groups option which sets that annotation.

**Comment by ty359** [comment]
> You can just use the --group-add=keep-groups option which sets that annotation.

I see. Maybe use this as default.

**Comment by rhatdan** [comment]
You can modify containers.conf, I believe to set this as default.
