### ISSUE TITLE
--db-backend considered harmful

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#20563]
Yikes. I realize `--db-backend` is undocumented, but in the post-#20318 world it is actively dangerous to use it:
```console
# podman system reset -f
# podman info --format '{{.Host.DatabaseBackend}}'
sqlite

! OK so far. Run a container.
# bin/podman run -d -q quay.io/libpod/testimage:20221018 top
aaf4adf79792650449cd5ef21309db7c506cf347a448da53665426f7b12639cd
# bin/podman ps
CONTAINER ID  IMAGE                              COMMAND     CREATED         STATUS         PORTS       NAMES
aaf4adf79792  quay.io/libpod/testimage:20221018  top         23 seconds ago  Up 24 seconds              competent_galois

! OK so far. Now run just one command with boltdb:
# podman --db-backend=boltdb info --format '{{.Host.DatabaseBackend}}'
boltdb

! Boom. We are now in a completely unusable state forevermore.
# bin/podman ps
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES

# podman info --format '{{.Host.DatabaseBackend}}'
boltdb      <-------- it got stuck!

! You can check out any time you like but you can never leave
# bin/podman system reset -f
ERRO[0000] no container with name or ID "..." found: no such container 
ERRO[0000] image used by ....: image is in use by a container: consider listing external containers and force-removing image 

! (works with --db-backend=sqlite but that may not be obvious)
```
Reason: https://github.com/containers/podman/blob/0cd20090b2243160bc42dfe0928d4383d8777b20/libpod/runtime.go#L320

Discussion: oof. I don't know. This is a real tough one. How should podman distinguish between:
1. boltdb file exists and is real
2. boltdb file exists but is bogus

I tentatively suggest that if *both* boltdb and sqlite files exist, *and* there is no explicit command-line (or c.conf?) setting, podman should bail with a fatal error. Bonus points for providing instructions with a command-line way to fix:
```
podman: You have both boltdb and sqlite databases. This can lead to disaster!
podman: please pick one (sqlite or boltdb), then run podman --db-backend=YOUR-CHOICE magic-command-that-wipes-the-other
```

Another option (possibly in addition to the above): `podman --db-backend=boltdb` will check if an sqlite file already exists, and if so (waves hands):
* warn?
* create a state file, `.boltdb-is-bogus`, that gets checked in `runtime.go`?
* use a different filename for the boltdb file, such that `--db-backend` is explicitly different from the created-by-default file?

There are more snags I'm thinking of right now, but I haven't thought them through yet. This is enough for now.

**Comment by vrothberg** [comment]
I could imagine an error message asking to `podman system reset` before changing the DB.  I personally do not feel strongly either way.

@Luap99 WDYT?

**Comment by Luap99** [comment]
I think the docs are very clear that this would be expected, from containers.conf:
> The database backend of Podman. Supported values are "" (default), "boltdb" and "sqlite". An empty value means it will check whenever a boltdb already exists and use it when it does, otherwise it will use sqlite as default (e.g. new installs). This allows for backwards compatibility with older versions. Please run podman-system-reset prior to changing the database backend of an existing deployment, to make sure Podman can operate correctly.

 `--db-backend` is undocumented and you should not use it unless you know what you are doing.

Adding an error when both exists is something I suggested when sqlite was originally added but now I am not sure I see the value of that. This behaves juts like --network-backend which is not really safe either but immensely useful to local testing for me. Having the option to test db bugs quickly without having to system reset each time (assuming you know exactly what you do) seem very useful to me.

**Comment by edsantiago** [comment]
>Having the option to test db bugs quickly

Yes, precisely, that has been tremendously useful... but the new behavior is: if you DO NOT have an explicit `sqlite` in `containers.conf`; and you EVER run `--db-backend=boltdb`, you are hosed forever. I think this may bite even podman experts.

**Comment by Luap99** [comment]
@edsantiago Can we close this one given we can no longer create new boltdb databases?

**Comment by edsantiago** [comment]
The option remains dangerous, but I suppose anyone using it in 2024 deserves what they get.
