### ISSUE TITLE
quadlet with nftables

### ISSUE THREAD

**Issue by fansari** [containers/podman#20587]
### Feature request description

In my scenario only the first container is able to start bcause I cannot disable firewall rules created by netavark as I have described here:

[https://github.com/containers/podman/issues/13760](url)

The issue is that after the first container is started netavark injects firewall rules. When the second container tries to start it gives this  "chain already exists" error message and it does not come up.

```
netavark: code: 1, msg: iptables: Chain already exists
```

As a workaround I have suggested here:

[https://github.com/containers/podman/issues/13760](url)

```
[Service]
ExecStartPre=/usr/bin/systemctl reload nftables
ExecStartPost=/usr/bin/systemctl reload nftables
```
This works with "podman generate systemd" generated files - but with quadlet this does not work for some reason.

I have tested with two root containers and also tried to add sleep commands - but it always fails with thees "chain alread exist" errors.

So far the only working scenario with two containers was to create a chain with "After" so that the second container is to start after the first one and in addtion to that the mentioned service config.

```
[Unit]
Description=postfix
After=local-fs.target bind.service

[Service]
ExecStartPre=/usr/bin/systemctl reload nftables
ExecStartPost=/usr/bin/systemctl reload nftables
```
In this example the container called "postfix" has to wait for a container called "bind" before it could be started.

This cannot be the solution. Containers should be able to start independently.

### Suggest potential solution

I need some suggestion or feature to make sure that this netavark firewall enforcing featrue which cannot be disabled is not in the way starting up containers. As described above with the "systemctl reload nftables" command I was unable to achieve that and I still do not understand why.

### Have you considered any alternatives?

Alterernatives for me are to stay with "podman generate systemd" generated files in scenarios bigger than just two containers or to switch back to docker until it is possible with podman to disable this firewall feature.

### Additional context

Fedora 39 Sliverblue
podman-4.7.0-1.fc39.x86_64
netavark-1.7.0-2.fc39.x86_64

**Comment by baude** [comment]
@vrothberg mind offering an opinion?

**Comment by mheon** [comment]
This seems like a bug in the iptables Netavark backend - an EEXIST on a chain we are trying to create should not be fatal?

The nftables/firewalld drivers under development will likely be unaffected but that does not mean we shouldn't fix the iptables driver.

**Comment by mheon** [comment]
I can't see any relation to #13760 - that seems like a misunderstanding of how iptables works in an nftables system?

**Comment by Luap99** [comment]
The latest netavark version support nft natively so I would suggest you try that.
