### ISSUE TITLE
Starting from 4.7.0 there is no msi installer in GitHib releases page

### ISSUE THREAD

**Issue by fedinskiy** [containers/podman#20618]
### Issue Description

Previous versions of podman (eg [1]) contained file podman-vX.Y.Z.msi, which could be used to install podman on Windows from command line. Starting from 4.7.0 all releases(eg [2]) contain only podman-X.Y.Z-setup.exe, which requires GUI for installation and can not be used in scripts (including CI)

[1] https://github.com/containers/podman/releases/tag/v4.6.2
[2] https://github.com/containers/podman/releases/tag/v4.7.2

### Steps to reproduce the issue

1. Open https://github.com/containers/podman/releases/tag/v4.7.2

### Describe the results you received

There is no msi file

### Describe the results you expected

There should be msi file

### podman info output

```yaml
Podman: 4.7.2
OS: Windows
Architecture: x86_64
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

**Comment by rhatdan** [comment]
@n1hility PTAL

**Comment by n1hility** [comment]
@fedinskiy You can run the installer executable offline (its Wix Burn based, and follows those conventions). Here is an example we use in our: CI https://github.com/containers/podman/blob/main/contrib/cirrus/win-installer-main.ps1 

The old MSIs were unmaintained and not recommended, so we removed them to avoid confusion.

**Comment by fedinskiy** [comment]
@n1hility is it possible to add this notice (and workaround) into release notes (eg for 4.7.0)?
