### ISSUE TITLE
IPv4 address spill - leaving NIC unmasqed

### ISSUE THREAD

**Issue by imp1sh** [containers/podman#20623]
### Issue Description

Packets originating from containers leave my hosts network interface that have a source IP set from the containers namespace, in my case 10.89.0.0/24. Those packets arrive at the firewall but when they return to the firewall, they can never be routed back to the container host, since the route does not exist at the firewall.
The result is malfunctioning services.
I just switched to Debian because under Ubuntu 22.04 the problem was really bad. Eversince I switched to Debian the amount of problematic packets shrunk but never went to 0.

### Steps to reproduce the issue

I don't know the exact circumstances when this happens but I will try to give as much details about my setup as possible.

# Host
Container Host is virtualized Debian in Proxmox 8, using kvm64 CPU type and 16 GB of RAM with 1 GB of SWAP.

# Software version
- Debian 12.2 6.1.0-13-amd64
- aardvark / netavark 1.4.0-3
- podman 4.3.1
- iptables 1.8.9-2
- nftables / libnftables 1.0.6-2

# Container env
- running around 45 containers
- no firewalld no ufw
- RAM usage about 25%
- Load between 1 and 2#
- 14 cores assigned 
- using netavark / aardvark
- All containers using the podmannet network
```root@cntr-ofden1:~# podman network inspect podmannet
[
     {
          "name": "podmannet",
          "id": "cbea01b7398ff5fdf95faf1a5275d62d0691f0821a7906f4dd36bfe054956b53",
          "driver": "bridge",
          "network_interface": "podman1",
          "created": "2023-11-01T23:35:21.231236772+01:00",
          "subnets": [
               {
                    "subnet": "10.89.0.0/24",
                    "gateway": "10.89.0.1"
               },
               {
                    "subnet": "fda9:92d6:18ac:e10e::/64",
                    "gateway": "fda9:92d6:18ac:e10e::1"
               }
          ],
          "ipv6_enabled": true,
          "internal": false,
          "dns_enabled": true,
          "ipam_options": {
               "driver": "host-local"
          }
     }
]
```

### Describe the results you received

Describe the results you received

### Describe the results you expected

Packets with a source IP address from the container network leave the network interface, instead of the masked IP from the host.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.28.2
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2.1.6+ds1-1_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.6, commit: unknown'
  cpuUtilization:
    idlePercent: 98.75
    systemPercent: 0.34
    userPercent: 0.91
  cpus: 14
  distribution:
    codename: bookworm
    distribution: debian
    version: "12"
  eventLogger: journald
  hostname: cntr-ofden1.libcom.de
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.1.0-13-amd64
  linkmode: dynamic
  logDriver: journald
  memFree: 272003072
  memTotal: 16766947328
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun_1.8.1-1+b1_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.1
      commit: f8a096be060b22ccd3d5f3ebe44108517fbf6c30
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.2.0-1_amd64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 147648512
  swapTotal: 1023406080
  uptime: 72h 35m 34.00s (Approximately 3.00 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 43
    paused: 0
    running: 42
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 41459032064
  graphRootUsed: 28039704576
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 62
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.3.1
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.19.8
  Os: linux
  OsArch: linux/amd64
  Version: 4.3.1
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

**Comment by Luap99** [comment]
I assume only some packages are incorrect an in general the NAT works for most of the traffic?
If this is the case I suggest you update to the latest version as I think https://github.com/containers/netavark/pull/774 would fix it.
Or you just add the rule manually `iptables -A FORWARD -m conntrack --ctstate INVALID -j DROP`

**Comment by imp1sh** [comment]
> I assume only some packages are incorrect an in general the NAT works for most of the traffic? If this is the case I suggest you update to the latest version as I think [containers/netavark#774](https://github.com/containers/netavark/pull/774) would fix it. Or you just add the rule manually `iptables -A FORWARD -m conntrack --ctstate INVALID -j DROP`

Yeah only very few packages are incorrect.
I will see what I can do to update. I will report back.

**Comment by Luap99** [comment]
I am confident that this rule will fix the issue so I am going to close this but feel free to comment if it did not help and I will reopen.
