### ISSUE TITLE
Ubuntu 22.04 LTS Which podman installation to use? Installation instructions not adequate. 

### ISSUE THREAD

**Issue by irudkin** [containers/podman#20648]
### Issue Description

I am trying to get the latest version of Podman installed on Ubuntu 22.04 LTS. It has to work with NVIIDA's container Toolkit. It requires podman greater than v4.4.1 otherwise podman reports CDI 0.5.0 is not recognised. I have tried various installation following these instructions:
https://podman.io/docs/installation
https://github.com/liebig/podman/releases
https://github.com/containers/podman/blob/main/DOWNLOADS.md
https://github.com/containers/podman/releases/tag/v4.7.2
Which tar or download link do I need for Ubuntu? I have tried various from the above 
 Either I cannot uncompress the zips or tars, get the wrong binary format (expected in some cases) or podman reports: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by ./podman).
Out of the box Ubuntu 22.04 installs not the latest podman but v3.4.4. Yes not necessary an issue this group can fix, but please provide the necessary steps, the installation instructions to install the latest podman.
v4.4.1 at least provided a directory structure to copy across manually.
The releases for v4.7.2. either I cannot uncompress, wrong binary format or does not work. Various other supporting files appear to be missing to which are present in v4.4.1.

### Steps to reproduce the issue

Steps to reproduce the issue
1.
2.
3.

### Describe the results you received

Unable to install and execute the latest Podman version using the instruction provided by Podman installation guide.

I did the following:
sudo podman run --log-level debug --rm --device=nvidia.com/gpu=all --security-opt=label=disable ubuntu nvidia-smi -L

The following errors were triggered when creating the CDI registry: map[/etc/cdi/nvidia.yaml:[failed to load CDI Spec: invalid CDI Spec: invalid version "0.5.0"] /var/run/cdi/nvidia.yaml:[failed to load CDI Spec: invalid CDI Spec: invalid version "0.5.0"]]

This means version 4.4.1 is not new enough to consume 0.5.0 CDI.

### Describe the results you expected

Having followed the appropriate step by step explicit instructions, the latest version of podman is able to execute and report its version to the user from the command line.

### podman info output

```yaml
Podman v4.7.2 installation package for Ubuntu 22.04 LTS
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

nvidia-ctk
NAME:
   NVIDIA Container Toolkit CLI - Tools to configure the NVIDIA Container Toolkit

USAGE:
   nvidia-ctk [global options] command [command options] [arguments...]

VERSION:
   1.14.3
commit: 53b24618a542025b108239fe602e66e912b7d6e2

**Comment by Luap99** [comment]
https://podman.io/docs/installation lists the kubic repo as alternative to get newer versions.

**Comment by irudkin** [comment]
Hi,Thanks. However, kubic is not recommended for production use.   Is this not the case?Sent from my iPhone12+On 10 Nov 2023, at 12:26, Paul Holzinger ***@***.***> wrote:﻿
https://podman.io/docs/installation lists the kubic repo as alternative to get newer versions.

**Comment by irudkin** [comment]
@Luap99 Ok, followed the instructions at 
The installation failed.
sudo mkdir -p /etc/apt/keyrings
a@PC:~$ curl -fsSL "https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/Release.key" | gpg --dearmor | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
a@PC:~$ sudo apt-get update -qq
W: GPG error: http://ru.archive.ubuntu.com/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 3B4FE6ACC0B21F32
E: The repository 'http://ru.archive.ubuntu.com/ubuntu bionic InRelease' is not signed.
a@PC:~$ sudo apt-get --qq -y install podman
E: Command line option --qq is not understood in combination with the other options

**Comment by irudkin** [comment]
Confirmed v4.6.2 of Podman worked with the NVIDIA Container Toolkit CDI specification outputting the type of NVIDA  GPU installed.

IMO the installation instructions are not specifically clear (and incorrect) to enable someone to make a clean quick installation of Podman on Ubuntu. This took many days to resolve the issue for someone not familiar with Podman.

**Comment by rhatdan** [comment]
Interested in opening a PR to fix the documentation?
