### ISSUE TITLE
e2e: push to local registry: dial tcp [::1]:5000: connect: connection refused

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#20655]
Always port 5000. This is what the code looks like:
```go
lock := GetPortLock("5000")
defer lock.Unlock()
session := podmanTest.Podman([]string{"run", "-d", [registry on port 5000]})
....
```
There are three of those in `e2e/push_test.go`, seven more in other tests.

My hunch is that this is a race: `Unlock()` runs when `It()` falls out of scope, but the registry container isn't cleaned up until `AfterEach()`. Supporting evidence: look at [this log](https://api.cirrus-ci.com/v1/artifact/task/5055742575640576/html/int-podman-fedora-39%CE%B2-root-container-sqlite.log.html#t--Podman-push-podman-push-to-local-registry--1):
```
→ Enter [It] podman push to local registry [...]  @ 10/31/23 15:26:23.803
...
podman run registry...
time="2023-10-31T15:26:26.28714805Z" level=info msg="listening on [::]:5000" go.version=go1.19.9 instance.id=7d37ba0d-27b3-4a12-b449-8a2bc3ce8e79 service=registry version=2.8.2 
```
...then scroll up, skip the previous test , go up one more to `push test --force-compression` (because it uses port 5000) and look at its timestamps:
```
← Exit  [It] push test --force-compression [...] @ 10/31/23 15:26:25.629 (2.524s)
→ Enter [AfterEach] TOP-LEVEL [...]              @ 10/31/23 15:26:25.63
[podman stop and rm]
← Exit  [AfterEach] TOP-LEVEL [...]              @ 10/31/23 15:26:26.704 (1.074s)
```
Those are tight timings.

Possible solution:
1. use ports other than 5000; and/or
2. stop/rm the registry within each test; and/or
3. globalize the lock, and unlock in teardown *after* all containers have been cleaned up.

Not hard, just not something I'm gonna do today.

* fedora-39β : int podman fedora-39β root container sqlite
    * [10-31 11:29](https://api.cirrus-ci.com/v1/artifact/task/5055742575640576/html/int-podman-fedora-39β-root-container-sqlite.log.html#t--Podman-push-podman-push-to-local-registry--1) in Podman push podman push to local registry
    * [10-19 17:53](https://api.cirrus-ci.com/v1/artifact/task/6714693289508864/html/int-podman-fedora-39β-root-container-sqlite.log.html#t--Podman-push-podman-push-to-local-registry--1) in Podman push podman push to local registry
* fedora-39β : int podman fedora-39β root host boltdb
    * [11-02 07:55](https://api.cirrus-ci.com/v1/artifact/task/4952281880199168/html/int-podman-fedora-39β-root-host-boltdb.log.html#t--Podman-push-podman-push-to-local-registry-with-authorization--1) in Podman push podman push to local registry with authorization
    * [10-19 17:51](https://api.cirrus-ci.com/v1/artifact/task/6011005847732224/html/int-podman-fedora-39β-root-host-boltdb.log.html#t--Podman-push-podman-push-to-local-registry--1) in Podman push podman push to local registry
* fedora-39β : int remote fedora-39β root host boltdb [remote]
    * [10-05-2023 22:08](https://api.cirrus-ci.com/v1/artifact/task/6405999829975040/html/int-remote-fedora-39β-root-host-boltdb.log.html#t--Podman-push-podman-push-to-local-registry--1) in Podman push podman push to local registry

Seen in: int podman+remote fedora-39β root container+host boltdb+sqlite

Only seen in #17831, because on normal PRs the ginkgo retry succeeds.

**Comment by rhatdan** [comment]
I think the easiest would be to randomize the port.

**Comment by Luap99** [comment]
Using different ports seems the best way in general, locking specific ports just makes parallel tests wait for no reason which slows down overall test time.

That said if there truly is a port conflict `podman run` for the registry container should have errored out right away and you would not be able to start to containers on the same port at the same time.
Note the `[::1]` in the error message, `localhost` is ambiguous as it can resolve to either `127.0.0.1` or `::1`and I don't know how go resolves that internally (I think it should try both). Importantly `::1` port forwarding is not supported with rootful podman as DNAT is not supported by the kernel for it. It works for rootless however as we use a user space proxy there. Given all your errors are rooful I think this could also be at play here.
