### ISSUE TITLE
Podman Desktop (Windows) - "Podman needs to be set up"

### ISSUE THREAD

**Issue by harleydk** [containers/podman#20654]
### Issue Description

After an initial installation of Podman Desktop (WIndows, version 1.5.3) , I'm faced with this notification on the dashboard:

![image](https://github.com/containers/podman/assets/1468788/c32804c4-ec5e-4a19-9c5f-3d898c1b46ce)

However if I press the 'Set up' button, I'm guided to the settings menu with no indication of anything needing further setting up:

![image](https://github.com/containers/podman/assets/1468788/5d319003-633a-4a0a-9c6a-5928732d82d5)

As the notification message alludes to the Podman Extension, I opt to visit the settings for that, but all seems fine here:

![image](https://github.com/containers/podman/assets/1468788/c95c7e56-a64f-4257-a2b2-272e9367a43c)

So I'm wondering what I should do here. Thank in advance for any assistance.

**Comment by NeoEffle** [comment]
same issue on MAC

**Comment by FLWFTW** [comment]
And on Fedora via Flathub

**Comment by Luap99** [comment]
Podman Desktop issues should be reported against: https://github.com/containers/podman-desktop
