### ISSUE TITLE
export: Allow filesystem export from image as well as container

### ISSUE THREAD

**Issue by adambkaplan** [containers/podman#20680]
### Feature request description

Enhance `podman export` so that it can accept an image reference directly, instead of a container name/ID. Ideally, the container image referenced does not have to be runnable by providing a `CMD` or `ENTRYPOINT`. 

### Suggest potential solution

1. For runnable container images, this _could_ be a shortcut to the following:

   ```sh
   $ CONT_ID=$(podman create <image>)
   $ podman export CONT_ID <target>
   $ podman rm CONT_ID
   ```

2. Ideally this can be done for _non-runnable_ OCI artifacts. 

### Have you considered any alternatives?

[crane](https://github.com/google/go-containerregistry/blob/main/cmd/crane/README.md) has this capability via `crane export`.

### Additional context

Use cases:

1. Extract content from Operator-SDK/OLM [bundle images](https://sdk.operatorframework.io/docs/olm-integration/tutorial-bundle/)
2. Extract SBOMs and signatures associated with container images (the latter is typically done using tools like `cosign verify`).

**Comment by mtrmac** [comment]
https://docs.podman.io/en/latest/markdown/podman-image-mount.1.html ?

**Comment by mtrmac** [comment]
(For running Podman with c/storage with no privileges at all, just to be able to do a format conversion, compare the problem space of https://github.com/containers/storage/pull/1735 .)

**Comment by rhatdan** [comment]
You can do this now with podman container mount and podman image mount.

**Comment by adambkaplan** [comment]
I can confirm that this is feasible with `podman image mount`, however the user experience leaves much to be desired, especially for rootless podman.

For folks who find this feature request, here's what it takes to get similar/equivalent functionality as `crane export` with rootless podman:

```sh
$ mkdir image-export
$ cd image-export
$ podman unshare
# IMAGE_FS=$(podman image mount <image name>)
# cp -r "$IMAGE_FS"/merged .
# exit
$ sudo chown -r $(whoami):$(whoami) .
```
