### ISSUE TITLE
Quadlet documentation - syntax `yes`/`no` vs `true`/`false`

### ISSUE THREAD

**Issue by moneytoo** [containers/podman#20686]
### Issue Description

Looking at the quadlet documentation at [podman-systemd.unit.5.md](https://github.com/containers/podman/blob/9c954739e9555c0940238f71ba3cc205deaa0e5e/docs/source/markdown/podman-systemd.unit.5.md), I see a table at the top with "valid options" like: `ReadOnlyTmpfs=true` or `RunInit=true`. However lower it states  `ReadOnlyTmpfs= (defaults to yes)` and `RunInit= (default to no)`. This makes me wonder what syntax should I use. Is it `yes`/`no` or `true`/`false`?

### Steps to reproduce the issue

See above.

### Describe the results you received

N/A

### Describe the results you expected

N/A

### podman info output

```yaml
N/A
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

**Comment by Luap99** [comment]
I think both work fine, the yes/no is more systemd like as it documents booleans as yes/no while podman in general uses true/false so I guess we decided to allow both. Properly worth documenting it in the man page, are you interested in doing that?
