### ISSUE TITLE
Support lookup of intermediate ID for uidmapping and gidmapping in `--userns=auto`

### ISSUE THREAD

**Issue by kaivol** [containers/podman#20699]
### Feature request description

As a rootless user, the host ID in **uidmapping** and **gidmapping** in `--userns=auto` is mapped from the intermediate namespace, just like when using the **--uidmap** and **--gidmap** options.

But these options also support preceding the _host id_ in the mapping with the @ symbol, which means that podman will look up the _intermediate id_ corresponding to the given _host id_ and it will map the found _intermediate id_ to the given _container id_. 

I think this functionality would be useful for the **uidmapping** and **gidmapping** options in `--userns=auto`, too. 

### Suggest potential solution

The behavior should be the same as with the **--uidmapping** and **--gidmapping** options (see [**podman-run** -> **--uidmap** -> **Referencing a host ID from the parent namespace**](https://docs.podman.io/en/latest/markdown/podman-run.1.html#uidmap-flags-container-uid-from-uid-amount)). 

### Have you considered any alternatives?

Looking up the intermediate id manually is also possible, just a little cumbersome.

**Comment by giuseppe** [comment]
would you like to open a PR to introduce this feature?

**Comment by kaivol** [comment]
Yes, I would like to look into it.

**Comment by rhatdan** [comment]
@kaivol you got it.
