### ISSUE TITLE
Auto recover from "invalid internal status .. could not find any running process: no such process"

### ISSUE THREAD

**Issue by grooverdan** [containers/podman#20697]
### Feature request description

[ci connections fail](https://buildbot.mariadb.org/#/builders/311/builds/19647/steps/3/logs/stdio) and podman can get thrown into an invalid state.

What shouldn't happen is every [consequent job](https://buildbot.mariadb.org/#/builders/311/builds/19648) ends up with the error:
```
time="2023-11-15T12:11:14+01:00" level=error msg="invalid internal status, try resetting the pause process with \"/usr/bin/podman system migrate\": could not find any running process: no such process"
```

With no such process I assume there's a fairly clear resolution that needs to occur, and it shouldn't require manual intervention to happen.

### Suggest potential solution

Podman recognises the "no such process", does it own cleanup and continues.

### Have you considered any alternatives?

"/usr/bin/podman system migrate" at the beginning of every CI job.

### Additional context

version at time of failure:

podman-3:4.4.1-16.module+el8.8.0+19993+47c8ef84.x86_64

**Comment by Luap99** [comment]
Maybe the better question is how you get into this situation, this sounds to me your podman environment is not correctly configured? Did you make sure your runnroot is on tmpfs?

**Comment by grooverdan** [comment]
Ok, its not on tmpfs.
```
store:
  configFile: /home/buildbot/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 0
    stopped: 3
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /data/buildbot/containers/storage
  graphRootAllocated: 157934215168
  graphRootUsed: 122460618752
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 704
  runRoot: /tmp/containers-user-1003/containers
  transientStore: false
  volumePath: /data/buildbot/containers/storage/volumes
```

The worker was killed by TTY removal by virtue of a disconnect of the buildbot master, the VM machine on which podman is running didn't reboot. So podman is relying on of a runroot purge in the case of its demise?

**Comment by Luap99** [comment]
yes podman puts a file there that needs to be removed to trigger a state refresh and it will also write the pause.pid file there.

You would need to remove `/tmp/containers-user-1003/libpod/tmp` on your setup I think, by default it should be `$XDG_RUNTIME_DIR/libpod/tmp`. Basicaly there is a `alive` file in there that tell us to refresh the state (new boot but also if you logged out and killed all user processes it would be needed as well). The refresh is needed to set all containers to not running, etc...
The best way to fix this is to remove `/tmp/containers-user-1003` before you launch podman again after you forcefully killed all processes.

Ignoring the pause.pid issue and self fixing is sort of possible but will likely hide underlying issues, if we create a new pause pid it means we have a new userns so that means likely a lot of non obvious issues later on if you already had running container at this point.

**Comment by giuseppe** [comment]
I agree with @Luap99 the run root is not meant to survive a reboot.

Could you mount a tmpfs on `/tmp`?

**Comment by grooverdan** [comment]
> I agree with @Luap99 the run root is not meant to survive a reboot.

Yes, but its not a reboot.

> Could you mount a tmpfs on `/tmp`?

Yes. I was surprised it wasn't. Anyway, my fault.

>  if we create a new pause pid it means we have a new userns ...

To make `TryJoinPauseProcess` return the same values as `os.ErrNotExist` on the `pausePidPath`, and to clear out the pidfile so later looks at the pidfile don't see it and just recreate the pause process.

Something like the following? (excluse crappy go programming, its been awhile)
```
diff --git a/pkg/rootless/rootless_linux.go b/pkg/rootless/rootless_linux.go
index d303c8bd0..77702fb80 100644
--- a/pkg/rootless/rootless_linux.go
+++ b/pkg/rootless/rootless_linux.go
@@ -501,12 +501,23 @@ func TryJoinFromFilePaths(pausePidPath string, needNewNamespace bool, paths []st
                        }
                }
 
-               if pausePid > 0 && unix.Kill(pausePid, 0) == nil {
-                       joined, pid, err := joinUserAndMountNS(uint(pausePid), pausePidPath)
-                       if err == nil {
-                               return joined, pid, nil
+               if pausePid > 0 {
+                       if kerr := unix.Kill(pausePid, 0); kerr == nil {
+                               joined, pid, err := joinUserAndMountNS(uint(pausePid), pausePidPath)
+                               if err == nil {
+                                       return joined, pid, nil
+                               }
+                               lastErr = err
+                       } else if kerr == unix.ESRCH {
+                               // pidfile lies, delete if exists (could be "", but hope(!!!) remove handles that with PathError
+                               rerr := os.Remove(pausePidPath)
+                               if _, ok := rerr.(*os.PathError); rerr != nil && !ok {
+                                       lastErr = fmt.Errorf("cannot delete pause pid file %s: %w", pausePidPath, rerr)
+                               } else {
+                                       // treat like there is no process
+                                       return false, -1, lastErr
+                               }
                        }
-                       lastErr = err
                }
        }
        if lastErr != nil {


```

`alive.lck` appears to be getting unix advisory locks so will survive and reinitialize I think as you've described.

**Comment by giuseppe** [comment]
> Something like the following? (excluse crappy go programming, its been awhile)
> 
> ```
> diff --git a/pkg/rootless/rootless_linux.go b/pkg/rootless/rootless_linux.go
> index d303c8bd0..77702fb80 100644
> --- a/pkg/rootless/rootless_linux.go
> +++ b/pkg/rootless/rootless_linux.go
> @@ -501,12 +501,23 @@ func TryJoinFromFilePaths(pausePidPath string, needNewNamespace bool, paths []st
>                         }
>                 }
>  
> -               if pausePid > 0 && unix.Kill(pausePid, 0) == nil {
> -                       joined, pid, err := joinUserAndMountNS(uint(pausePid), pausePidPath)
> -                       if err == nil {
> -                               return joined, pid, nil
> +               if pausePid > 0 {
> +                       if kerr := unix.Kill(pausePid, 0); kerr == nil {
> +                               joined, pid, err := joinUserAndMountNS(uint(pausePid), pausePidPath)
> +                               if err == nil {
> +                                       return joined, pid, nil
> +                               }
> +                               lastErr = err
> +                       } else if kerr == unix.ESRCH {
> +                               // pidfile lies, delete if exists (could be "", but hope(!!!) remove handles that with PathError
> +                               rerr := os.Remove(pausePidPath)
> +                               if _, ok := rerr.(*os.PathError); rerr != nil && !ok {
> +                                       lastErr = fmt.Errorf("cannot delete pause pid file %s: %w", pausePidPath, rerr)
> +                               } else {
> +                                       // treat like there is no process
> +                                       return false, -1, lastErr
> +                               }
>                         }
> -                       lastErr = err
>                 }
>         }
>         if lastErr != nil {
> ```
> 
> `alive.lck` appears to be ge

the issue with this approach is what happens if two podman instances end up in this same check and we end up creating two separate  pause processes

**Comment by grooverdan** [comment]
> the issue with this approach is what happens if two podman instances end up in this same check and we end up creating two separate pause processes

That would be the same as `TryJoinPauseProcess` both hitting the case of no-pidfile.

Like `TryJoinPauseProcess` above code could `lockfile.GetLockFile(pausePidPath)` on before kill (or read?, or remove?).

**Comment by Luap99** [comment]
I am going to close this as I do not think it is worth fixing, you must ensure the runroot/tmpdir is on tmpfs and/or deleted if you just kill all the podman processes/containers for it to detect the "reboot".

We do however have plans to make this more discoverable when things go wrong.
