### ISSUE TITLE
Support a module for enabling exception for namespace creation when using kernel-hardened

### ISSUE THREAD

**Issue by firefoxlover** [containers/podman#20720]
### Feature request description

When using the kernel-hardened, which restricts namespace creation, both flatpak and podman are broken.

Arch has a package `bubblewrap-setuid` which solves this problem for flatpak apps.

### Suggest potential solution

Could a similar package be available for Podman, to only allow this feature for these two programs and not the entire system?

### Have you considered any alternatives?

Disabling the parameter entirely, as it may even have negative consequences. I want to discuss if this is a good or bad idea and if it should be generally avoided

### Additional context

linux-hardened is a project available for Arch and [Fedora](https://copr.fedorainfracloud.org/coprs/samsepi0l/HardHatOS/packages/) at least, now even with [custom ublue images for Fedora](https://github.com/qoijjj/hardened-images).

Especially the ublue images rely entirely on Podman and Flatpak, so this is necessary to fix.

I am not sure if the same applies for Wine and Waydroid too?

**Comment by rhatdan** [comment]
We do not want to add any setuid apps to Podman, kind of ruins the security story.

**Comment by rhatdan** [comment]
So you want to restrict creation of usernamespace and then add a setuid app that allows you to create a user namespace?

**Comment by rhatdan** [comment]
You hardened the kernel to prevent user namespaces and then open a hole to allow user namespaces, I would just turn off the hardening if you want to use rootless podman.

**Comment by firefoxlover** [comment]
Okay I suppose this is the best idea. 

What would be the problem with user namespaces? And would it makes sense to only allow specific apps, via these exceptions?

**Comment by rhatdan** [comment]
In the (distant) past there were some issues with User Namespace that allowed people to gain more access then was expected and allowed.  These bugs have been fixed, but User Namespace still makes people nervous, because if gives accounts access to more then one UID and the ability to mount certain file systems without being root.  

Turning off user namespace eliminates the risk.  I would argue there is limited risk, and this blocking of user namespace is mistaken and leads people to either use less safe rules like running all containers as root, or adding setuid applications that could cause bad security outcomes.

**Comment by Luap99** [comment]
I don't think it is even possible to write podman like this. If the user namespace is created as root then only root is the owner and can manage it, thus it would mean we cannot drop the privs right away and need them to setup everything, we could only drop them for the container. And this functionality already exists in the form of `sudo podman run --userns=auto` or `sudo podman run --subuidname <user>` if you want the mapping from a specific user.

But as @rhatdan said we do not think it is insecure. All major distros and upstream kernel have it enabled by default as far as I know so unless you have some special requirements I say you should not worry about it.

**Comment by firefoxlover** [comment]
https://madaidans-insecurities.github.io/guides/linux-hardening.html#application-sandboxing

I dont really understand much of that, but I guess it is basically referring to the same things as you @rhatdan .

**Comment by trytomakeyouprivate** [comment]
Hey, could you explain if this would be possible to accomplish anyways?

> and this blocking of user namespace is mistaken and leads people to either use less safe rules like running all containers as root, or adding setuid applications that could cause bad security outcomes.

Could you elaborate on that? When using the hardened Kernel, this is required.

**Comment by Luap99** [comment]
We have no plan to work on this and I don't think it is even possible with our current architecture.
