### ISSUE TITLE
Cannot list HyperV podman machines

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman#20736]
### Issue Description

Using the HyperV provider, `podman machine ls` reports:

`Error: listing vms: could not find virtual machine "podman-machine-default": no results found`

### Steps to reproduce the issue

Steps to reproduce the issue
1. set CONTAINERS_MACHINE_PROVIDER=hyperv
2. podman machine ls

### Describe the results you received

Describe the results you received

### Describe the results you expected

Error: listing vms: could not find virtual machine "podman-machine-default": no results found

### podman info output

```yaml
OS: windows/amd64
provider: hyperv
version: 4.8.0-rc1
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rhatdan** [comment]
Looks like you did not `init` or `start` the machine?

**Comment by jeffmaury** [comment]
I created a machine with podman machine init and got a previous one already

**Comment by rhatdan** [comment]
@baude @n1hility @ashley-cui Thoughts?  

I thought the command would follow the environment variable.

**Comment by mheon** [comment]
Does not reproduce over here. I suspect the VM has been removed from HyperV but our config file remains as it was not removed by `podman machine rm`. You can verify in the HyperV console - if we don't have a VM with the podman-machine-default name, that's what it is. If it is missing from HyperV - does `podman machine rm` still work?

We can definitely handle this case more gracefully, though the VM itself will be unrecoverable - maybe automatically delete it?

**Comment by n1hility** [comment]
I think @mheon's theory is correct, the error message is from libhvee, and the "no results found" sub error would indicate that the WQL query that selected the machine by name had no entries.

**Comment by jeffmaury** [comment]
Closing at it seems to be caused by previous HyperV machines that were not on the HyperV side. Once I cleared my Podman HyperV env, I can create and list the machine right
