### ISSUE TITLE
Error starting a container in a rootless static installation

### ISSUE THREAD

**Issue by JKSTAFF** [containers/podman#20743]
### Issue Description

I try to deploy [this container](https://v2raya.org/en/docs/prologue/installation/podman/#rootless-mode) with the same parameters.    
It usually works fine on my SteamOS 3.0, but at the very nearest deploy I only got error `unable to start container : exit status 1` after I type the podman start command.   
I'm new to podman so I'm having trouble finding the crash logs inside the container. But my podman-desktop GUI tells me additional error message `http code 409 preparing container XXX for attach write child : broken pipe`  

### Steps to reproduce the issue

Steps to reproduce the issue  
1. Deploy a podman static install on SteamOS 3.5.5  
2. `podman create -it --name v2raya --restart=unless-stopped --label io.containers.autoupdate=registry --cgroup-parent=v2raya.slice --security-opt no-new-privileges --cap-drop all --network host  --volume ~/.config/v2raya:/etc/v2raya:z docker.io/mzz2017/v2raya:latest`  
3. `podman start v2raya`  

### Describe the results you received

shell output after start command:   
`unable to start container : exit status 1`
podman-desktop GUI output after start command:  
`http code 409 preparing container XXX for attach write child : broken pipe`   

### Describe the results you expected

If everything is right ,container should running

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.30.0
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /home/deck/.local/share/podman/lib/podman/conmon
    version: 'conmon version 2.1.7, commit: f633919178f6c8ee4fb41b848a056ec33f8d707d'
  cpuUtilization:
    idlePercent: 94.08
    systemPercent: 1.78
    userPercent: 4.14
  cpus: 8
  databaseBackend: boltdb
  distribution:
    codename: holo
    distribution: steamos
    variant: steamdeck
    version: 3.5.5
  eventLogger: file
  hostname: NEpGear
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.1.52-valve7-1-neptune-61
  linkmode: dynamic
  logDriver: journald
  memFree: 4778610688
  memTotal: 15534063616
  networkBackend: cni
  ociRuntime:
    name: crun
    package: Unknown
    path: /home/deck/.local/share/podman/bin/crun
    version: |-
      crun version 1.8.7
      commit: 53a9996ce82d1ee818349bdcc64797a1fa0433c4
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns 由 slirp4netns 1.2.0-1 所拥有    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 1073737728
  swapTotal: 1073737728
  uptime: 0h 53m 38.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  configFile: /home/deck/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/deck/.local/share/podman/lib/containers/storage
  graphRootAllocated: 1007619178496
  graphRootUsed: 653515927552
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /home/deck/.local/share/podman/run/containers/storage
  transientStore: false
  volumePath: /home/deck/.local/share/podman/share/podman/volume
version:
  APIVersion: 4.5.1
  Built: 1694025576
  BuiltTime: Thu Sep  7 02:39:36 2023
  GitCommit: 9eef30051c83f62816a1772a743e5f1271b196d7-dirty
  GoVersion: go1.20.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.5.1

```
```


### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

_No response_

### Additional information

_No response_

**Comment by giuseppe** [comment]
do you get the error only with this specific image or does it happen with other images too?

Could you try without using podman remote?

It looks like conmon crashed, have you compiled it by yourself?  Could you check if there is any useful information in the journal?

**Comment by JKSTAFF** [comment]
> It looks like conmon crashed, have you compiled it by yourself? Could you check if there is any useful information in the journal?
Thank you for your working and reply. After checking for the past few hours, I found that SteamOS has built-in podman in version 3.5, which conflicts with my [static installation](https://github.com/mgoltzsche/podman-static). The problem has been solved and I'm very sorry for occupying public resources.
