### ISSUE TITLE
prefer podman's installer binary (gvproxy, qemu) over system wide binaries

### ISSUE THREAD

**Issue by benoitf** [containers/podman#20808]
### Feature request description

if I install podman on my computer using installer and have for example an old brew install or any other installation

1. podman will start gvproxy from `/usr/local/bin` folder

```
benoitf          86983   0.0  0.0 409869360  32800 s013  S    11:44AM   0:00.14 /usr/local/bin/gvproxy -listen-qemu unix:///var/folders/_s/rlbw3qg15vx0j6vr4l7kd1hm0000gn/T/podman/qmp_podman-machine-default.sock
```

I would expect that it launches gvproxy from `/opt/podman` folder

my `podman` binary comes from `/opt/podman/bin/podman` and in `/opt/podman/bin` there is a gvproxy binary

I would expect that it launches it from this `/opt/podman/bin` folder to avoid to mix with other binaries that might not be compliant with the one podman binary expects.

2. podman will start qemu from brew folder and not from /opt/podman

for example I have one process which is:
```
/opt/homebrew/bin/qemu-system-aarch64
```

```bash
/opt/podman/qemu/bin/qemu-system-aarch64 --version
QEMU emulator version 8.0.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers
```

```bash
/opt/podman/qemu/bin/qemu-system-aarch64 --version                                                                                                                                    QEMU emulator version 8.1.1
Copyright (c) 2003-2023 Fabrice Bellard and the QEMU Project developers
```

### Additional context

I would have assumed that it would use https://github.com/containers/podman/blob/main/contrib/pkginstaller/package.sh#L10

but it seems it still take my system binaries and not the one provided by the installer

**Comment by cfergeau** [comment]
Relevant code is in `containers/common`: https://github.com/containers/common/blob/3cec82a3710580e7e545b23c47534f5cb2682917/pkg/config/default.go#L340-L343
and https://github.com/containers/common/blob/3cec82a3710580e7e545b23c47534f5cb2682917/pkg/config/config_darwin.go#L33-L47

If `additionalHelperBinariesDir` comes first in `HelperBinariesDir`, then `"$BINDIR/../libexec/podman"`, and then all the default 'well-known' locations, this should avoid the false positives you described.
