### ISSUE TITLE
HyperV regression tests fail due to privileges

### ISSUE THREAD

**Issue by baude** [containers/podman#20843]
### Issue Description

HyperV CI tests are failing to run properly because they apparently do not have correct permissions.  These errors can be seen in https://cirrus-ci.com/task/5759477765373952?logs=main#L289  ... I didn't include this in #20842 because while this is likely why the tests fail, it is not the reason the CI still passes.

### Steps to reproduce the issue

Steps to reproduce the issue
1.
2.
3.

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
I assume this can be closed now as tests seem to be working
