### ISSUE TITLE
Error: database libpod root directory (staticdir)  does not match our libpod root directory (staticdir)

### ISSUE THREAD

**Issue by kisame217** [containers/podman#20872]
### Issue Description

Starting with version 4.8.0, I get the error below.
```
Error: database libpod root directory (staticdir) "/home/<user>/.local/share/containers/storage/libpod" does not match our libpod root directory (staticdir) "/var/home/<user>/.local/share/containers/storage/libpod": database configuration mismatch
```
I'm on Fedora Kinoite 39. No problems with version 4.7.2.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Upgraded to 4.8.0 from 4.7.2.
2. Try to start a container
```
podman --log-level debug start postgres
```

### Describe the results you received

```
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called start.PersistentPreRunE(podman --log-level debug start postgres) 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
INFO[0000] Using boltdb as database backend             
DEBU[0000] Initializing boltdb state at /var/home/<user>/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Overriding graph root "/var/home/<user>/.local/share/containers/storage" with "/home/<user>/.local/share/containers/storage" from database 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/<user>/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000/containers     
DEBU[0000] Using static dir /var/home/<user>/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /var/home/<user>/.local/share/containers/storage/volumes 
DEBU[0000] Using transient store: false                 
Error: database libpod root directory (staticdir) "/home/<user>/.local/share/containers/storage/libpod" does not match our libpod root directory (staticdir) "/var/home/<user>/.local/share/containers/storage/libpod": database configuration mismatch
DEBU[0000] Shutting down engines 
```

### Describe the results you expected

Container should start normally.

### podman info output

```yaml
Error: database libpod root directory (staticdir) "/home/<user>/.local/share/containers/storage/libpod" does not match our libpod root directory (staticdir) "/var/home/<user>/.local/share/containers/storage/libpod": database configuration mismatch

OS: Fedora Kinoite 39
Arch: x86_64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Running of bare metal.

### Additional information

None.

**Comment by yann-soubeyrand** [comment]
Same on Fedora 39 Silverblue (I guess it’s expected since it affects Kinoite 39).

**Comment by Luap99** [comment]
What is the value of $HOME?

**Comment by yann-soubeyrand** [comment]
> What is the value of $HOME?

`/home/yann` for me. It’s the correct path to my home directory. However, `/home` is a symlink to `/var/home` on Silverblue (and I guess on Kinoite too).

**Comment by Luap99** [comment]
Does it work if you set `HOME=/var/home/yann`?

**Comment by mheon** [comment]
We can probably fix this in the logic for checking the current config against the DB - eval symlinks on both paths (the one in the DB and the one we're trying to use) and compare the final paths. We'd need fixes for both Bolt and SQLite that way though

**Comment by Luap99** [comment]
reproducer on a not rpm-ostree system:
```
# create symlink for home
$ ln -s /home /tmp/home
# run system reset to start fresh
$ podman system reset

# run old podman 4.7.2, you need to change HOME var to your username of course
$ HOME=/tmp/home/pholzing podman ps
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES
# run podman 4.8 or main
$ HOME=/tmp/home/pholzing bin/podman ps
Error: database libpod root directory (staticdir) "/tmp/home/pholzing/.local/share/containers/storage/libpod" does not match our libpod root directory (staticdir) "/home/pholzing/.local/share/containers/storage/libpod": database configuration mismatch
```

**Comment by kisame217** [comment]
> #20874 is still open. Is there a work-around? I tried to change HOME, but with no success.

How did you change home? I set my home in /etc/passwd file. Also had to delete the containers folder in .local/share to reset the db config after I took backups of my container.

**Comment by mheon** [comment]
Setting `static_dir` in containers.conf is more likely to work. If your error message is:

```
Error: database libpod root directory (staticdir) "/home/<user>/.local/share/containers/storage/libpod" does not match our libpod root directory (staticdir) "/var/home/<user>/.local/share/containers/storage/libpod": database configuration mismatch
```

Then set `static_dir` to the "database libpod root directory" (in this case `/home/<user>/.local/share/containers/storage/libpod`)

**Comment by elken** [comment]
Looks like I timed it well to run into this.



> Setting `static_dir` in containers.conf is more likely to work. If your error message is:
> 
> ```
> Error: database libpod root directory (staticdir) "/home/<user>/.local/share/containers/storage/libpod" does not match our libpod root directory (staticdir) "/var/home/<user>/.local/share/containers/storage/libpod": database configuration mismatch
> ```
> 
> Then set `static_dir` to the "database libpod root directory" (in this case `/home/<user>/.local/share/containers/storage/libpod`)

Have just tried with the following file to no luck
![image](https://github.com/containers/podman/assets/2872862/a69e326a-76ad-40c0-8281-6e6ac4a92072)

Have tried both combinations of home paths.

**Comment by mheon** [comment]
Looks pile it is now complaining about volume path, also in containers.conf
(I think named volume_path but not sure?). Same procedure for the new error
but different key in containers.conf basically.

**Comment by elken** [comment]
> Looks pile it is now complaining about volume path, also in containers.conf (I think named volume_path but not sure?). Same procedure for the new error but different key in containers.conf basically.

Perfect! That works for podman at least

For future finders my file looks like

```
[engine]
static_dir = "/home/lkn/.local/share/containers/storage/libpod"
volume_path = "/home/lkn/.local/share/containers/storage/libpod"
```

Now trying to access existing containers with distrobox I get an error like

```
ERRO[0000] Unmounting /home/lkn/.local/share/containers/storage/overlay/f79b472b5b98d8e7a728c7d52415ea60b1043ae60cb1d08ee766f8dc71c08963/merged: invalid argument 
Error: unable to start container "ff34fb71718140a638f7c834ed6d116f413d8a50f8bfbc88307a38d717f7ff52": mounting storage for container ff34fb71718140a638f7c834ed6d116f413d8a50f8bfbc88307a38d717f7ff52: creating overlay mount to /home/lkn/.local/share/containers/storage/overlay/f79b472b5b98d8e7a728c7d52415ea60b1043ae60cb1d08ee766f8dc71c08963/merged, mount_data="lowerdir=/home/lkn/.local/share/containers/storage/overlay/l/6I7L4CUQJIQPFUYHFX5OZBL4JK:/home/lkn/.local/share/containers/storage/overlay/l/6I7L4CUQJIQPFUYHFX5OZBL4JK/../diff1:/home/lkn/.local/share/containers/storage/overlay/l/7JTTU5TJDPKSG76SE4CVJCD5OT:/home/lkn/.local/share/containers/storage/overlay/l/BFAWGXFYIDBJFEOEEW66NT5TUI,upperdir=/home/lkn/.local/share/containers/storage/overlay/f79b472b5b98d8e7a728c7d52415ea60b1043ae60cb1d08ee766f8dc71c08963/diff,workdir=/home/lkn/.local/share/containers/storage/overlay/f79b472b5b98d8e7a728c7d52415ea60b1043ae60cb1d08ee766f8dc71c08963/work,userxattr,context=\"system_u:object_r:container_file_t:s0:c1022,c1023\"": invalid argument
```

But I'm happy to take this elsewhere if it's not directly related to podman :smile:

**Comment by nariba** [comment]
Thank you very much!
I was having the same problem and this issue helped me solve it.

In my environment, there was no directory, not even containers.conf, but if I create the directory and file, it should be OK.
The containers.conf mentioned in [this comment](https://github.com/containers/podman/issues/20872#issuecomment-1837199097) is in the following path,
`/home/lkn/.config/containers/containers.conf`

**Comment by debarshiray** [comment]
I couldn't reproduce this on my Fedora Silverblue 39:
```ShellSession
rishi@fedora:~$ podman version
Client:       Podman Engine
Version:      4.8.0
API Version:  4.8.0
Go Version:   go1.21.4
Built:        Tue Nov 28 10:58:32 2023
OS/Arch:      linux/amd64
rishi@fedora:~$ 
rishi@fedora:~$ echo $HOME
/var/home/rishi
rishi@fedora:~$ 
```

... but clearly a lot of people can.  Based on these [two](https://github.com/containers/podman/issues/20872#issuecomment-1836451878) [comments](https://github.com/containers/podman/issues/20872#issuecomment-1836458913), I think this affects those who have been upgrading their installations in-place for a while.

I usually reinstall once every year, and I remember that we changed the default value of `HOME` from `/home/foo` to `/var/home/foo` at some point to avoid relying on the symbolic link.

**Comment by walking-octopus** [comment]
```
stas@thinkpad-t14 /h/stas [1]> rpm-ostree status -b
State: idle
AutomaticUpdates: stage; rpm-ostreed-automatic.timer: no runs since boot
BootedDeployment:
● fedora:fedora/39/x86_64/kinoite
                  Version: 39.20231205.0 (2023-12-05T01:04:12Z)
               BaseCommit: 694f995d4b7ca42e87b393ff3058949dad660e5f2d692338dacaaceab06cd754
             GPGSignature: Valid signature by E8F23996F23218640CB44CBE75CF5AC418B8E74C
          LayeredPackages: 'gcc-c++' adb alsa-lib-devel automake cmake duperemove ffmpeg-free fish gcc htop
                           jetbrains-mono-fonts-all make mozilla-openh264 podman-compose podman-docker
                           powertop systemd-devel tmux xeyes

AvailableUpdate:
           Diff: 7 upgraded
stas@thinkpad-t14 ~> echo $HOME
/home/stas
stas@thinkpad-t14 ~> export HOME=/var/home/stas
stas@thinkpad-t14 /h/stas> echo $HOME
/var/home/stas
stas@thinkpad-t14 /h/stas> podman --version
podman version 4.8.0
stas@thinkpad-t14 /h/stas> podman version
Error: database libpod root directory (staticdir) "/home/stas/.local/share/containers/storage/libpod" does not match our libpod root directory (staticdir) "/var/home/stas/.local/share/containers/storage/libpod": database configuration mismatch
```

Just changing the $HOME seems to not be enough. Perhaps there's a config file somewhere that I can edit?

It's also strange it didn't happen after the rebase but just another version update...

**Comment by elken** [comment]
> Perhaps there's a config file somewhere that I can edit?

https://github.com/containers/podman/issues/20872#issuecomment-1837199097

**Comment by quazar-omega** [comment]
Oh good, thanks for explaining!

**Comment by Justinzobel** [comment]
I rebased from Fedora 39 Kinoite to Rawhide Kinoite to do some testing and this affects my ability to run a toolbox:
```
toolbox
Error: failed to get the Podman version
...
podman --version
podman version 4.8.1
```
