### ISSUE TITLE
Podman for restricted environment still asks me for admin - Win10

### ISSUE THREAD

**Issue by grgghrn** [containers/podman#20904]
### Issue Description

Win 10 19044.3693  - No admin access.   WSL2 was installed by admin with no distro successfully:

Trying to install the restricted environment version so that I can do it without admin.  But when time comes to actually install podman from podman desktop, it still prompts for admin and I cannot continue.

### Steps to reproduce the issue

Steps to reproduce the issue
1.  Have admin user Install WSL2 with --no-distribution. Reboot.
2.  Verify wsl setup right:
`wsl --status`
> Default Version: 2

`wsl --list`
> Windows Subsystem for Linux has no installed distributions.

3. Install windows podman desktop for restricted environment with normal non-admin user.  Works fine.
4. Start podman desktop as normal user and check it's status:
-In main panel, it says "Podman Desktop was not able to find an installation of Podman" and has an 'install' button.
-In lower 'Featured Extensions:" panel it shows 'Podman" and says "installed".

5. Ignore that apparent inconsistency and hit the 'install' button.
I get the exact same popup that I would have with the full install - asking me for admin login and having an option checked box to install WSL if unavailable.
I uncheck the WSL button, since it's installed already, but I still get the admin popup when install starts.
Cancel on the admin popup and it aborts the install.

Am I missing the point of the restricted environment - and I still need admin to install this, or should I really be able to install without admin (assuming WSL2 is installed by admin previously)

### Describe the results you received

Describe the results you received

### Describe the results you expected

Expect to be able to install and use the podman desktop for restricted environments, and subsequent podman engine without having to provide administrator credentials.

### podman info output

```yaml
When choosing 'install' for podman from the podman-desktop UI, I am still prompted for admin elevated rights, just like if I installed the normal version.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

### Additional environment details

Restricted corporate environment where we don't have admin.
I haven't gotten far enough to choose root/less for the podman env.

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
Note podman-desktop is not maintained by the podman maintainers, if you have problems with the desktop installer you should ask there: https://github.com/containers/podman-desktop/
