### ISSUE TITLE
Release 4.8.1 is missing the .pkg installers for MacOS

### ISSUE THREAD

**Issue by kcak11** [containers/podman#20909]
Release 4.8.1 is missing the .pkg installers for MacOS

The latest release of Podman 4.8.1 doesn't ship the .pkg installers for MacOS.
This has happened multiple times previously also.

Can we automate this process so that it is taken care whenever a new build is released.

Thanks in advance.

See Previous Issues:
https://github.com/containers/podman/issues/18726
https://github.com/containers/podman/issues/20287

**Comment by Luap99** [comment]
The process is automated, it just doesn't help if the automation is failing: https://github.com/containers/podman/actions/runs/7100276693/job/19326018871

@lsm5 @ashley-cui @baude Who has access to the credentials and can fix this?

**Comment by kcak11** [comment]
The .pkg files are now available as part of the release assets. 
Closing this issue.

Thanks all.
