### ISSUE TITLE
Podman Desktop Mac M2 qemu error on machine start

### ISSUE THREAD

**Issue by savagematt** [containers/podman#20915]
### Bug description

When I start podman-machine-default from a clean install of Podman Desktop 1.4.0 I get an error related to qemu

### Operating system

macOS Ventura 13.5.1, Apple M2 

### Installation Method

Installer from website/GitHub releases

### Version

1.4.0

### Steps to reproduce

Steps to reproduce the issue
1. Install Podman Desktop 1.4.0 on M2 MBP
2. Start Podman machine
3. View logs

### Relevant log output

```shell
Logs show:


Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code 1, stderr: qemu-system-aarch64: -accel hvf: invalid accelerator hvf
qemu-system-aarch64: falling back to tcg
qemu-system-aarch64: unable to find CPU model 'host'
```
```


### Additional context

I tried creating a new machine, with the same result

**Comment by xakraz** [comment]
Looks similar to this issue: https://github.com/containers/podman/issues/20776

Is it a duplicate?

**Comment by Luap99** [comment]
Podman 5.0 no longer support qemu on macos, we now use the apple hypervisor
