### ISSUE TITLE
allow rootless podman to volume mount devices without noexec 

### ISSUE THREAD

**Issue by mythi** [containers/podman#20974]
### Issue Description

Originally commented [here](https://github.com/opencontainers/runtime-tools/issues/759#issuecomment-1846913248). The original issue was `runtime-tools` specific but podman seems to use it's own [way for mounting devices](https://github.com/containers/podman/blob/611ba2ff316f09ff49dee4bc354f00b9052dc237/pkg/specgen/generate/config_linux.go#L134-L149)

I'm using the latest `podman` from the Kubic repo:
```
$ podman version
Client:       Podman Engine
Version:      4.6.2
API Version:  4.6.2
Go Version:   go1.18.1
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. `$ podman run -it --rm --device /dev/sgx_enclave  --group-add keep-groups --workdir /opt/intel/sgx-sample-app   --entrypoint /bin/bash localhost/intel/sgx-sdk-demo:devel`
2. `# mount|grep sgx_enclave`
`devtmpfs on /dev/sgx_enclave type devtmpfs (rw,nosuid,noexec,relatime,size=1997876k,nr_inodes=499469,mode=755)`

### Describe the results you received

Cannot create SGX enclaves.

### Describe the results you expected

to run SGX enclaves, devfs cannot be `noexec`. Can this be made configurable similar to volumes `OPTIONS`?

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.31.2
  cgroupControllers:
  - cpuset
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2:2.1.8-0ubuntu22.04+obs16.38_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.8, commit: '
  cpuUtilization:
    idlePercent: 93.98
    systemPercent: 3.19
    userPercent: 2.83
  cpus: 4
  databaseBackend: boltdb
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  freeLocks: 2048
  hostname: ubuntu
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 6.6.0+
  linkmode: dynamic
  logDriver: journald
  memFree: 169840640
  memTotal: 4097372160
  networkBackend: cni
host:
  arch: amd64
  buildahVersion: 1.31.2
  cgroupControllers:
  - cpuset
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2:2.1.8-0ubuntu22.04+obs16.38_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.8, commit: '
  cpuUtilization:
    idlePercent: 93.98
    systemPercent: 3.19
    userPercent: 2.83
  cpus: 4
  databaseBackend: boltdb
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  freeLocks: 2048
  hostname: ubuntu
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 6.6.0+
  linkmode: dynamic
  logDriver: journald
  memFree: 169840640
  memTotal: 4097372160
  networkBackend: cni
  networkBackendInfo:
    backend: cni
    dns:
      package: golang-github-containernetworking-plugin-dnsname_1.3.1+ds1-2_amd64
      path: /usr/lib/cni/dnsname
      version: |-
        CNI dnsname plugin
        version: 1.3.1
        commit: unknown
    package: 'golang-github-containernetworking-plugin-dnsname, containernetworking-plugins:
      /usr/lib/cni'
    path: /usr/lib/cni
  ociRuntime:
    name: crun
    package: crun_101:1.12-0ubuntu22.04+obs65.10_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.12
      commit: ce429cb2e277d001c2179df1ac66a470f00802ae
      rundir: /run/user/1001/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: true
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.0.1-2_amd64
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 0
  swapTotal: 0
  uptime: 74h 42m 8.00s (Approximately 3.08 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/mythi/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/mythi/.local/share/containers/storage
  graphRootAllocated: 19092647936
  graphRootUsed: 12492144640
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 20
  runRoot: /run/user/1001/containers
  transientStore: false
  volumePath: /home/mythi/.local/share/containers/storage/volumes
version:
  APIVersion: 4.6.2
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.18.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.2
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by mythi** [comment]
This patch fixes my error:
```
diff --git a/pkg/specgen/generate/config_linux.go b/pkg/specgen/generate/config_linux.go
index 965072a0a..48ea149e8 100644
--- a/pkg/specgen/generate/config_linux.go
+++ b/pkg/specgen/generate/config_linux.go
@@ -158,7 +158,7 @@ func addDevice(g *generate.Generator, device string) error {
                        Destination: dst,
                        Type:        define.TypeBind,
                        Source:      src,
-                       Options:     []string{"slave", "nosuid", "noexec", perm, "rbind"},
+                       Options:     []string{"slave", "nosuid", perm, "rbind"},
                }
                g.Config.Mounts = append(g.Config.Mounts, devMnt)
                return nil
```

**Comment by giuseppe** [comment]
since you are running as rootless, you could just bind mount the device, as anyway that is what is done internally since an unprivileged user cannot use `mknod`:

```
$ podman run -it --rm -v /dev/sgx_enclave:/dev/sgx_enclave  --group-add keep-groups fedora mount|grep sgx_enclave
devtmpfs on /dev/sgx_enclave type devtmpfs (rw,nosuid,seclabel,size=4096k,nr_inodes=4053248,mode=755,inode64)
```

would that work for you?

**Comment by mythi** [comment]
I think it does but I guess I'm curious to understand what is happening. What's the difference between `--device` and `-v` then? How are the device cgroups handled with rootless?

**Comment by giuseppe** [comment]
device cgroups are not handled with rootless since an unprivileged user cannot install an ebpf filter.

with `--device` you've the equivalent of `-v /dev/sgx_enclave:/dev/sgx_enclave:noexec`

**Comment by mythi** [comment]
> device cgroups are not handled with rootless since an unprivileged user cannot install an ebpf filter.

does it need some precondition from, e.g., systemd (`DeviceAllow`?) to get the access granted? I'm not able to see anything in my default Ubuntu 22.04 setup for `char-misc rw`.
 
> with `--device` you've the equivalent of `-v /dev/sgx_enclave:/dev/sgx_enclave:noexec`

:+1

**Comment by giuseppe** [comment]
> does it need some precondition from, e.g., systemd (`DeviceAllow`?) to get the access granted? I'm not able to see anything in my default Ubuntu 22.04 setup for `char-misc rw`.

it will simply use the same configuration as its parent cgroup.  The limitation is not in user space so systemd cannot help here.  The kernel refuses to install the filter unless you are root in the initial user namespace.

**Comment by mythi** [comment]
> > does it need some precondition from, e.g., systemd (`DeviceAllow`?) to get the access granted? I'm not able to see anything in my default Ubuntu 22.04 setup for `char-misc rw`.
> 
> it will simply use the same configuration as its parent cgroup. The limitation is not in user space so systemd cannot help here. The kernel refuses to install the filter unless you are root in the initial user namespace.

The default for a user session (`user.slice`) on Ubuntu 22.04 seems to be `DevicePolicy=auto` which allows all devices to be bind mounted. I wanted to test how to control/configure this per device access and that seems easy with a user ID specific config snippet, e.g,

```
[Slice]
DevicePolicy=strict
DeviceAllow=<foobar>
...
# uncommenting the line adds /dev/sgx_enclave access
# DeviceAllow=/dev/char/10:124 rw
```

(a bit offtopic but helped me to learn how this works)

I think I can close this, thanks @giuseppe!
