### ISSUE TITLE
URGENT: fix the red-broken-tests thing in CI

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#20980]
CI is constantly red these days, because of windows mac whatever.

This makes it very hard for a human to see **ACTUAL** failed tests, like `sys`, like in #20827. So broken tests get merged.

Someone please figure out a way to stop showing red results in the CI log. Make it so red means red.

**Comment by baude** [comment]
hey @edsantiago , you can follow #20953 for starters.  and in spirit, we have so many other tests that can fail and still allow merge, it is bound to continue to happen.  this is why i do not like testing for other teams on our CI.

**Comment by Luap99** [comment]
This sounds like a symptom not a cause.
The real problem is that the merge bot is broken, it does not wait for the tests to pass and happy merges stuff were CI is not yet green. The second problem is people add `/lgtm` without `/hold` while CI is still running so we allow the merge bot to behave like this.

**Comment by edsantiago** [comment]
Followup notes:
* the merge tool is called either "prow" or "tide".  Here is a link to its [config documentation](https://docs.prow.k8s.io/docs/components/core/tide/config/)
* I believe the magic term we're looking for is `branch-protection`
* Neither "prow" nor "tide" appear anywhere (relevant) in the podman repo @ main. It is not clear where this config file lives.

Giving up.

**Comment by Luap99** [comment]
> Neither "prow" nor "tide" appear anywhere (relevant) in the podman repo @ main. It is not clear where this config file lives.

There I would assume: https://github.com/openshift/release/tree/master/core-services/prow/02_config/containers/podman

**Comment by edsantiago** [comment]
Wow. I have no idea how you found that, but thank you!

(I wonder if it might be a good idea to include that link in some sort of in-repo readme...)

**Comment by edsantiago** [comment]
Is this fixed? Are Macintosh tests green now?

**Comment by Luap99** [comment]
machine tests are enforcing on main AFAIK
