### ISSUE TITLE
podman images from one server to another not working

### ISSUE THREAD

**Issue by hmntsharma** [containers/podman#21037]
### Issue Description

Describe your issue

I have 2 RHEL 8.8 servers, running podman 4.4.1, one has internet (development) and the other (production) does not.

The development server works fine as podman is able to pull the images directly using internet, but then I create and move the image with "podman save" and "podman load" command (I have also tried "podman import") to the production environment and it does not work.

I have tried this a few times but always found the same outcome.

### Steps to reproduce the issue

Steps to reproduce the issue
1. On the development server, create a tarball as below

$ podman save -o cp-zookeeper.7.1.1.tar docker.io/confluentinc/cp-zookeeper:7.1.1
Copying blob f2c4302f03b8 done
Copying blob 60609ec85f86 done
Copying blob 5693d08c15ed done
Copying blob 37cafaf80b7e done
Copying blob 936ea683b512 done
Copying blob d117415e61f8 done
Copying blob f67583d3da0a done
Copying blob c8c571a6a27d done
Copying blob a93c87792774 done
Copying blob 3bfddb9a813d done
Copying blob c898263a4c9c done
Copying config 534c2e2cfd done
Writing manifest to image destination
Storing signatures

3. On the production, tried to impor as well as load but no joy

$ podman load -i cp-zookeeper.7.1.1.tar
Getting image source signatures
Copying blob d117415e61f8 done
Copying blob 60609ec85f86 done
Copying blob f2c4302f03b8 done
Copying blob 5693d08c15ed done
Copying blob 936ea683b512 done
Copying blob 37cafaf80b7e done
Copying blob f67583d3da0a done
Copying blob c8c571a6a27d done
Copying blob a93c87792774 done
Copying blob c898263a4c9c done
Copying blob 3bfddb9a813d done
Error: payload does not match any of the supported image formats:
 * oci: initializing source oci:cp-zookeeper.7.1.1.tar:: open cp-zookeeper.7.1.1.tar/index.json: not a directory
 * oci-archive: loading index: open /var/tmp/oci1034655130/index.json: no such file or directory
 * docker-archive: writing blob: adding layer with blob "sha256:f2c4302f03b8582b388fb66058da2ae3a3b70cff3ab8ce3ebfc0cc24349814b9": processing tar file(potentially insufficient UIDs or GIDs available in user namespace (requested 0:12 for /var/spool/mail): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /var/spool/mail: invalid argument): exit status 1
 * dir: open cp-zookeeper.7.1.1.tar/manifest.json: not a directory
$
$
$
$ podman import cp-zookeeper.7.1.1.tar cp/zookeeper:7.1.1
Getting image source signatures
Copying blob 16c4955e07b2 skipped: already exists
Copying config 98f7a9e904 done
Writing manifest to image destination
Storing signatures
sha256:98f7a9e90417aaddc5c1b61d0d12e075bbf9e2b092c00cc900c8c789d419eed6
$
$ podman run -d -it cp/zookeeper:7.1.1
Error: no command or entrypoint provided, and no CMD or ENTRYPOINT from image
$

5.

### Describe the results you received

Describe the results you received

On the production server, I get the following

$ podman load -i cp-zookeeper.7.1.1.tar
Getting image source signatures
Copying blob d117415e61f8 done
Copying blob 60609ec85f86 done
Copying blob f2c4302f03b8 done
Copying blob 5693d08c15ed done
Copying blob 936ea683b512 done
Copying blob 37cafaf80b7e done
Copying blob f67583d3da0a done
Copying blob c8c571a6a27d done
Copying blob a93c87792774 done
Copying blob c898263a4c9c done
Copying blob 3bfddb9a813d done
Error: payload does not match any of the supported image formats:
 * oci: initializing source oci:cp-zookeeper.7.1.1.tar:: open cp-zookeeper.7.1.1.tar/index.json: not a directory
 * oci-archive: loading index: open /var/tmp/oci1034655130/index.json: no such file or directory
 * docker-archive: writing blob: adding layer with blob "sha256:f2c4302f03b8582b388fb66058da2ae3a3b70cff3ab8ce3ebfc0cc24349814b9": processing tar file(potentially insufficient UIDs or GIDs available in user namespace (requested 0:12 for /var/spool/mail): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown /var/spool/mail: invalid argument): exit status 1
 * dir: open cp-zookeeper.7.1.1.tar/manifest.json: not a directory
$
$
$
$ podman import cp-zookeeper.7.1.1.tar cp/zookeeper:7.1.1
Getting image source signatures
Copying blob 16c4955e07b2 skipped: already exists
Copying config 98f7a9e904 done
Writing manifest to image destination
Storing signatures
sha256:98f7a9e90417aaddc5c1b61d0d12e075bbf9e2b092c00cc900c8c789d419eed6
$
$ podman run -d -it cp/zookeeper:7.1.1
Error: no command or entrypoint provided, and no CMD or ENTRYPOINT from image
$

### Describe the results you expected

Describe the results you expected

I expect it to work as it does in development

$ podman load -i cp-zookeeper.7.1.1.tar
Getting image source signatures
Copying blob d117415e61f8 skipped: already exists
Copying blob 5693d08c15ed skipped: already exists
Copying blob 37cafaf80b7e skipped: already exists
Copying blob 936ea683b512 skipped: already exists
Copying blob 60609ec85f86 skipped: already exists
Copying blob f67583d3da0a skipped: already exists
Copying blob f2c4302f03b8 skipped: already exists
Copying blob a93c87792774 skipped: already exists
Copying blob c8c571a6a27d skipped: already exists
Copying blob 3bfddb9a813d skipped: already exists
Copying blob c898263a4c9c skipped: already exists
Copying config 534c2e2cfd done
Writing manifest to image destination
Storing signatures
Loaded image: docker.io/confluentinc/cp-zookeeper:7.1.1
$
$ podman images | grep zoo
docker.io/confluentinc/cp-zookeeper  7.1.1       534c2e2cfdbc  20 months ago  797 MB

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.

development:

$ podman info
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.8-1.module+el8.9.0+20326+387084d0.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.8, commit: 21e9be52d14128789284e1bbf54d8c25b4820215'
  cpuUtilization:
    idlePercent: 98.8
    systemPercent: 0.44
    userPercent: 0.76
  cpus: 16
  distribution:
    distribution: '"rhel"'
    version: "8.9"
  eventLogger: file
  hostname: redhat.lab
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 10
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-513.9.1.el8_9.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 5426561024
  memTotal: 16510853120
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.9-1.module+el8.9.0+20326+387084d0.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.9
      spec: 1.0.2-dev
      go: go1.20.6
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.1-1.module+el8.9.0+20326+387084d0.x86_64
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 0
  swapTotal: 0
  uptime: 4h 20m 45.00s (Approximately 0.17 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/lab/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/lab/.local/share/containers/storage
  graphRootAllocated: 53569630208
  graphRootUsed: 15052869632
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 8
  runRoot: /run/user/1001/containers
  transientStore: false
  volumePath: /home/lab/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.1
  Built: 1695119471
  BuiltTime: Tue Sep 19 11:31:11 2023
  GitCommit: ""
  GoVersion: go1.19.12
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.1

production:

$ podman info
host:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.6-1.module+el8.8.0+19993+47c8ef84.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.6, commit: 0dcf8a206aff64a95e52d205642f8a7c7ed45049'
  cpuUtilization:
    idlePercent: 99.96
    systemPercent: 0.03
    userPercent: 0.02
  cpus: 24
  distribution:
    distribution: '"rhel"'
    version: "8.8"
  eventLogger: file
  hostname: lab.prod
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 13762
      size: 1
    - container_id: 1
      host_id: 2147473647
      size: 1
    uidmap:
    - container_id: 0
      host_id: 58015
      size: 1
    - container_id: 1
      host_id: 2147473647
      size: 1
  kernel: 4.18.0-477.21.1.el8_8.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 121644580864
  memTotal: 134633074688
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.4-1.module+el8.8.0+19993+47c8ef84.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.4
      spec: 1.0.2-dev
      go: go1.19.12
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    path: /run/user/58015/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_SYS_CHROOT,CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.module+el8.8.0+19993+47c8ef84.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 1614h 56m 21.00s (Approximately 67.25 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /var/SP/myuser/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/SP/myuser/.local/share/containers/storage
  graphRootAllocated: 536608768000
  graphRootUsed: 10951081984
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/user/58015/containers
  transientStore: false
  volumePath: /var/SP/myuser/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.1
  Built: 1695119471
  BuiltTime: Tue Sep 19 12:31:11 2023
  GitCommit: ""
  GoVersion: go1.19.12
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Additional environment details
both RHELs are virtual machines

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by giuseppe** [comment]
you do not have enough IDs available in the rootless user namespace.

You need to allocate more IDs to your user.

Please take a look at the subuid(5) man page for more information on how to do it.

**Comment by hmntsharma** [comment]
> you do not have enough IDs available in the rootless user namespace.
> 
> You need to allocate more IDs to your user.
> 
> Please take a look at the subuid(5) man page for more information on how to do it.

Thanks, I thought that is required when you actually run the container and here I  struggling to even load the image.

How is this not a problem when pulled from a public repository but doesn't work when the same image is archived and loaded on another machine?
