### ISSUE TITLE
Not able to build podman with Golang version (1.18) specified in go.mod 

### ISSUE THREAD

**Issue by lstolcman** [containers/podman#21048]
### Issue Description

Building podman from source failed - one package reported error that golang version is too old.

### Steps to reproduce the issue

Steps to reproduce the issue
1. make sure you have go 1.18 or 1.19.
1. clone latest podman (e.g. https://github.com/containers/podman/commit/07834ab39e92b7f292be808ae5ed69d67c1f9bee)
2. build from source
3. build failed due to `go-dockerclient`

### Describe the results you received

Error appears:
```sh
➜  podman git:(main) make BUILDTAGS="seccomp systemd" PREFIX=/usr
CGO_ENABLED=1 GOOS=linux GOARCH=arm go build \
         \
        -ldflags '-X github.com/containers/podman/v4/libpod/define.gitCommit=2258329769c03561b07722ec3ab412bb9f977728 -X github.com/containers/podman/v4/libpod/define.buildInfo=1702658926 -X github.com/containers/podman/v4/libpod/config._installPrefix=/usr -X github.com/containers/podman/v4/libpod/config._etcDir=/etc -X github.com/containers/podman/v4/pkg/systemd/quadlet._binDir=/usr/bin -X github.com/containers/common/pkg/config.additionalHelperBinariesDir= ' \
        -tags "seccomp systemd" \
        -o bin/podman ./cmd/podman
# github.com/fsouza/go-dockerclient
vendor/github.com/fsouza/go-dockerclient/client.go:514:18: undefined: context.Cause
note: module requires Go 1.20
make: *** [Makefile:350: bin/podman] Error 2
➜  podman git:(main)
```

### Describe the results you expected

build passed, binaries created

### podman info output

```yaml
podman lastest commit https://github.com/containers/podman/commit/07834ab39e92b7f292be808ae5ed69d67c1f9bee
raspberry pi (arm v6)
debian bookworm (11)
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

raspberry pi
debian bookworm (11)
golang installed from apt (go 1.19)

### Additional information

I've succeeded to build podman: removed golang from apt, installed newest go 1.21 from golang website -> podman build passed

package `go-dockerclient` changed its minimal go version from 1.18 to 1.19 in v1.9.4, in this merge request: https://github.com/fsouza/go-dockerclient/pull/957

newest 1.10.0 version of the package (version specified in podman requirements) bumps golang version even further, and requires go 1.20

**Comment by rhatdan** [comment]
What would you suggest we change to indicate you need golang 1.20 or newer?  And open a PR to make such change.

**Comment by vrothberg** [comment]
I'd rather update the module to `go 1.20`.  1.18 and 1.19 are EOL upstream.

**Comment by giuseppe** [comment]
opened a PR: https://github.com/containers/podman/pull/21054

**Comment by giuseppe** [comment]
the PR got merged, so closing the issue
