### ISSUE TITLE
Unable to install on Linux PopOs -> Ubuntu 20.04

### ISSUE THREAD

**Issue by zainen** [containers/podman#21041]
### Issue Description

Unable to install Podman via CLI 

### Steps to reproduce the issue

sudo apt update && sudo apt upgrade -y

Fails -> 
sudo apt-get -y install podman

```
sudo mkdir -p /etc/apt/keyrings

# Debian Testing/Bookworm
curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Testing/Release.key \
  | gpg --dearmor \
  | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg]\
    https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Testing/ /" \
  | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null

# Debian Unstable/Sid
curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Unstable/Release.key \
  | gpg --dearmor \
  | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg]\
    https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/Debian_Unstable/ /" \
  | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list > /dev/null

# Install Podman
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install podman
```

### Describe the results you received

```
**sudo apt-get -y install podman**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package podman
exit 100
```

```
** curl -fsSL "https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_$(lsb_release -rs)/Release.key" \
  | gpg --dearmor \
  | sudo tee /etc/apt/keyrings/devel_kubic_libcontainers_unstable.gpg > /dev/null ** 
curl: (22) The requested URL returned error: 404 
gpg: no valid OpenPGP data found.
```

### Describe the results you expected

to be able to use the package :sweat_smile: 

### podman info output

```yaml
cannot use podman
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional information

I cannot find https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_20.04/Release.key

Is Podman not supported for 20.04 anymore?

**Comment by rhatdan** [comment]
@lsm5 PTAL

**Comment by afbjorklund** [comment]
> Is Podman not supported for 20.04 anymore?

You have to use "stable" for Kubic, not "unstable".

I don't think _either_ of them is supported anymore...

https://podman.io/docs/installation#ubuntu docs mentions that:

_"CAUTION: The Kubic repo is NOT recommended for production use"_

It will get you 3.4.2, not 3.4.4 which is [in Ubuntu 22.04](https://packages.ubuntu.com/jammy/podman)

Most likely, they should both be updated to version 3.4.7

**Comment by adriens** [comment]
I used `brew` and am pretty happy with the resulting runtime, if it can help :thought_balloon:

**Comment by adriens** [comment]
Validated on `Pop!_OS 22.04 LTS`
