### ISSUE TITLE
Unable to init podman machine on mac with provider applehv due to truncate missing

### ISSUE THREAD

**Issue by adrianriobo** [containers/podman#21065]
### Issue Description

Trying to start a podman machine on macos with applehv it ends up on error due to missing truncate tool

### Steps to reproduce the issue

Steps to reproduce the issue
1. export CONTAINERS_MACHINE_PROVIDER= applehv
2. podman machine init

### Describe the results you received

podman machine init ends up failing with:

```bash
Extracting compressed file: podman-machine-default_fedora-coreos-39.20231204.2.1-applehv.x86_64.raw: done  
Error: exec: "truncate": executable file not found in $PATH
```

### Describe the results you expected

podman machine is properly initialized

### podman info output

```yaml
podman v4.8.2 installed from pkg
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by cfergeau** [comment]
Probably a good reason to revert the `pkg/machine/applehv` changes in https://github.com/containers/podman/commit/33a92aa006d39abfff24cf3112b0568b7f4906da
If I remember correctly, the external `truncate` command had the same performance issues in some corner cases.

**Comment by rhatdan** [comment]
Should we use truncate if it is found and then fall back to slower mechanism?

**Comment by gbraad** [comment]
Agree. While we can assume these are mostly on development machines, not everyone will have xcode installed.

**Comment by cfergeau** [comment]
I think the external command had the same issues, not sure a fallback is worth it.

**Comment by rhatdan** [comment]
I thought the porblem was if the external command does not exist, the fall back is not executed?
