### ISSUE TITLE
podman from brew takes precedence over podman from the podman.io installer

### ISSUE THREAD

**Issue by cfergeau** [containers/podman#21073]
### Issue Description

I recently uninstalled podman/qemu from brew, then installed podman using podman.io installer, and finally installed mongodb atlas through brew.
I did not notice this dragged again podman from brew, and did my testing with podman from brew instead of from the installer.

I'm not sure there's a great solution to this though :-/

### Steps to reproduce the issue

on macOS
- `brew uninstall podman qemu`
- install podman from the installer from podman.io
- install some tool to interact with your containers using brew (eg `mongodb-atlas-cli` following https://www.mongodb.com/docs/atlas/cli/stable/install-atlas-cli/ )
- do not pay attention to the fact that it's pulling podman/qemu from brew as dependencies
- run `podman machine ...`

, while 

### Describe the results you received

This results in podman/qemu being run from brew

### Describe the results you expected

Using the binaries from /opt/podman (the installer) is probably what the user expected.

This is due to brew coming before `/opt/podman/bin` in `$PATH`. brew is added to the path with something like `echo "export PATH=/usr/local/bin:$PATH" >> ~/.bash_profile && source ~/.bash_profile` which puts it first in `$PATH`.
on the contrary, podman installer adds podman to the path by dropping a file in `/etc/paths.d` which is added to the end of `$PATH`.

### podman info output

```yaml
host:
  arch: arm64
  buildahVersion: 1.32.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.8-2.fc39.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.8, commit: '
  cpuUtilization:
    idlePercent: 98.25
    systemPercent: 0.57
    userPercent: 1.18
  cpus: 5
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: coreos
    version: "39"
  eventLogger: journald
  freeLocks: 2038
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.6.3-200.fc39.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 1093345280
  memTotal: 1979293696
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.8.0-1.fc39.aarch64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.8.0
    package: netavark-1.8.0-2.fc39.aarch64
    path: /usr/libexec/podman/netavark
    version: netavark 1.8.0
  ociRuntime:
    name: crun
    package: crun-1.12-1.fc39.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.12
      commit: ce429cb2e277d001c2179df1ac66a470f00802ae
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20231119.g4f1709d-1.fc39.aarch64
    version: |
      pasta 0^20231119.g4f1709d-1.fc39.aarch64-pasta
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.2-1.fc39.aarch64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 1h 14m 55.00s (Approximately 0.04 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 0
    stopped: 3
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 5864538112
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.7.2
  Built: 1698762633
  BuiltTime: Tue Oct 31 15:30:33 2023
  GitCommit: ""
  GoVersion: go1.21.1
  Os: linux
  OsArch: linux/arm64
  Version: 4.7.2
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rhatdan** [comment]
Is there a way to conflict with packages installed from brew?

**Comment by rhwood** [comment]
> Is there a way to conflict with packages installed from brew?

No. I think you would have to modify libpod to only use the first podman binary in $PATH after walking through a predefined set of locations to check first for a podman binary.

**Comment by rhatdan** [comment]
There is no libpod?  The user executes podman is going to get the first podman in their path. Podman Desktop could prioritize finding it in the expected path.

**Comment by rhwood** [comment]
It seems to me that mongodb-atlas-cli uses imports from libpod within this repo, but now that look more closely, only for static definitions, but actually calls podman as a separate executable.

I think the easiest (and most immediate fix) may be `brew uninstall --ignore-dependencies podman qemu`, but don't know if  brew would reinstall those when or if updating something that relies on podman like mongodb-atlas-cli.

**Comment by Luap99** [comment]
Duplicate of #20808
Fixed in https://github.com/containers/common/pull/1754 which is in 4.8.2 AFAIK

**Comment by cfergeau** [comment]
yeah, not sure at all there's a great solution to this, but filed the issue anyway as the fix for #20808 is only a partial solution when brew can install a podman binary as a dependency of another tool, which will have priority over the already installed podman binary.
podman-machine config could record the full path to the podman binary which was used to create it, and require that this same binary is always used, but this would most likely cause other annoying issues.

**Comment by Luap99** [comment]
Should this be closed? I do not see how this can be fixed realistically. Managing $PATH will always be user responsibility.

**Comment by rhatdan** [comment]
I agree, bottom line is don't use brew for Podman.
