### ISSUE TITLE
Support for fixed ip with more than one network

### ISSUE THREAD

**Issue by soubinan** [containers/podman#21082]
### Feature request description

I have a use case where I need my container to have a specific IP address (the application configuration use it for many purposes, I am not the creator of this application so not able to change it - the application is cloudstack management)

The conatiner is on two networks (frontend network for external access and backend for db acces)
Each network is defined on a fixe subnet (frontend: 10.100.1.0/24 and backend: 10.200.1.0/24)
I need the frontend ip address to be fixed, but there is a limitation with with the option `--ip`
It can be used with only when we have only one network (normal since with `--ip`  we cannot say what network we are targeting, it assumes only one network in the picture)

So if we want to use a specific ip on a container, we are forced to use only one network (escading effect)
Since the database cannot stay on the backend network, and all other containers using it are impacted as well.
This impact the network speration feature 

How to reproduce ?

```bash
$ podman run --rm -d --network=frontend --ip 10.100.1.100 --network=backend docker.io/library/httpd
Error: --ip can only be set for a single network: invalid argument
```

### Suggest potential solution

Be able to use a specific option able to differenciate the networks when many are used
Porpositions:
A. a dedicated network aware ip option:

```bash
# if no network-configs mentionned, so we use "dhcp like" ip
$ podman run --rm -d --network=frontend --network-configs=net=frontend,ip=10.100.1.100 --network=backend docker.io/library/httpd
```

B. an extended network option:

```bash
# if no ip mentionned, so we use "dhcp like" ip
$ podman run --rm -d --network=net=frontend,ip=10.100.1.100 --network=backend docker.io/library/httpd
```
or

```bash
# if no ip mentionned, so we use "dhcp like" ip
$ podman run --rm -d --network=frontend:10.100.1.100 --network=backend docker.io/library/httpd
```

### Have you considered any alternatives?

The only alternative I have for now is to use only one network
Did not found another way as easyand  that just work

### Additional context

I am using quadlet a lot (actually I am using only that since I know it)
So would be very good to have it added to quandlet as well (even if the PodmanArgs would do the job)

**Comment by sbrivio-rh** [comment]
This will be supported, at least for user-mode networking with pasta(1), once we find some time for: https://bugs.passt.top/show_bug.cgi?id=47

**Comment by soubinan** [comment]
Great, I will retry with this one
Thanks @Luap99

**Comment by kingcdavid** [comment]
Do you know it's possible to make this work with podman-compose as well?
https://github.com/containers/podman-compose/blob/bce40c2db30fb0ffb9264b5f51535c26f48fe983/podman_compose.py#L884
Would the above need to be changed to the `--network netname:ip=x.x.x.x` format?
