### ISSUE TITLE
Podman machine start stuck at `Waiting for VM ...`

### ISSUE THREAD

**Issue by tekawade** [containers/podman#21088]
### Issue Description

This is Podman running in MacOS ARM64

```
$podman version
```
```
$podman info
```
```
$ podman version
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: ssh: handshake failed: read tcp 127.0.0.1:49555->127.0.0.1:50507: read: connection reset by peer
```

```
$ podman info
OS: darwin/arm64
provider: qemu
version: 4.8.2

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: ssh: handshake failed: read tcp 127.0.0.1:49556->127.0.0.1:50507: read: connection reset by peer
```
I followed through [Podman Troubleshooting Guide](https://github.com/containers/podman/blob/main/troubleshooting.md). Tried removing, re-installing, Podman desktop, unsetting `SSH_AUTH_SOCK`, checking `ssh-add -L` etc. Even firewall is disabled for the Mac as per suggestion.

I am suspecting it's something related to SSH but can't figure out what is the issue here.

Any suggested are welcome. Looking for location where I can check logs or run Podman in verbose mode will be helpful.

```
$ podman --log-level=debug ps
```
```
INFO[0000] podman filtering at log level debug
DEBU[0000] Called ps.PersistentPreRunE(podman --log-level=debug ps)
DEBU[0000] SSH Ident Key "<$HOME>/.ssh/podman-machine-default" SHA256:<key> ssh-ed25519
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: ssh: handshake failed: read tcp 127.0.0.1:49561->127.0.0.1:50507: read: connection reset by peer
DEBU[0003] Shutting down engines
```

On Podman desktop I see:
```
 [compose] Error getting compose version: Error: Failed to execute command: spawn <$HOME>/.local/share/containers/podman-desktop/extensions-storage/podman-desktop.compose/bin/docker-compose ENOENT
```

Podman installed with `brew install podman`. Podman desktop tried with direct as well with brew `brew install --cask podman-desktop`. I am able to run docker fine and also able to start docker image in Podman.

```
```
$ uname -a
Darwin <machine-name>.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020 arm64
```


### Steps to reproduce the issue

Steps to reproduce the issue
1. brew install podman
2. podman machine init
3. podman machine start


### Describe the results you received

System stuck at `Starting VM...`

### Describe the results you expected

VM started and running as expected.

### podman info output

```yaml
$ podman info
OS: darwin/arm64
provider: qemu
version: 4.8.2

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: ssh: handshake failed: read tcp 127.0.0.1:49556->127.0.0.1:50507: read: connection reset by peer
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

$ uname -a
Darwin <machinename>.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020 arm64

### Additional information

```
$ echo $SSH_AUTH_SOCK
/private/tmp/com.apple.launchd.Yw5BA959Qf/Listeners
```

**Comment by lednerb1** [comment]
I thought that was my bad. Have the same issue

**Comment by yangboroy** [comment]
Have the same issue too.

I have two podman machines in my macOS (arm M1). The first one:`podman-machine-default`, the second one: `usbTest`. They use the `fedora-coreos-39.20231119.2.0-qemu.aarch64.qcow2` image, and they start / ssh / stop work well always.

Later, seems I `brew upgrade` my qemu two or three times recent months.

Now, i have tired below steps.
1. `podman machine rm` remove the first machine and its related files.
2. `podman machine init` downloads the latest fedora coreos image, it works. 
3. `podman start --log-level debug` fails as this new machine hangs with below screenshot:
<img width="1503" alt="Screenshot 2023-12-26 at 08 17 24" src="https://github.com/containers/podman/assets/11975317/06b2b194-1c3a-4b9f-9df3-ffb58bcafaf5">
4. As my second machine `usbTest` works, so i copy its image and rename `testSecond.qcow2`
5. `podman machine init --image-path=testSecond.qcow2 --log-level debug`, it works.
6. `podman start --log-level debug` fails as the same issue.

In my eye step 6 should work well with early image. But it is not.
Not clear qemu or image issue.

**Comment by krvpal** [comment]
I encountered the issue on Mac after the recent package updates via homebrew. The issue appears to be with `qemu`. I downgraded it to version `8.1.3`, and now podman machine starts successfully.

To get verbose output I used `podman --log-level=trace machine start`, and could see the VM freeze at some point during startup sequence.

**Comment by tekawade** [comment]
@krvpal  Thanks. Looks like issue is with `qemu` as you said. I have other machine and it works fine. I checked version and it's with `8.1.3`. I will try manually installing `8.1.3` and then try again. I close after confirming and create issue with `qemu` instead.

**Comment by buca92** [comment]
Having the same issue after brew upgrade

podman: 4.8.2
qemu: 8.2.0
MacOS: Sonoma 14.2.1 (23C71) - the latest one

**Comment by zlogic** [comment]
I was able to fix this by copying the `/opt/homebrew/share/qemu/edk2-aarch64-code.fd` file from QEMU 8.1.3 into QEMU 8.2.0.
It looks like an issue with the UEFI firmware: https://gitlab.com/qemu-project/qemu/-/issues/1990

**Comment by tekawade** [comment]
Thanks @zlogic. This worked for me. I just downloaded it directly from [gitlab](https://gitlab.com/qemu-project/qemu/-/blob/86305e864191123dcf87c3af639fddfc59352ac6/pc-bios/edk2-aarch64-code.fd.bz2).

There is also workaround posted in issue by [Vincent Murphy](https://gitlab.com/vdm1) :https://gitlab.com/qemu-project/qemu/-/issues/1990#note_1707002525 (I haven't tried it though). Copying here for reference:
```
$ brew --version
Homebrew 4.2.0-68-g7817518
Homebrew/homebrew-core (git revision bad6b2c8726; last commit 2023-12-25)
Homebrew/homebrew-cask (git revision 5a0d345709; last commit 2023-12-25)
$ /opt/homebrew/bin/qemu-system-aarch64 -version
QEMU emulator version 8.2.0
$ curl -LO https://kojipkgs.fedoraproject.org//packages/edk2/20231122/14.fc39/noarch/edk2-aarch64-20231122-14.fc39.noarch.rpm
$ brew install rpm2cpio
$ rpm2cpio <edk2-aarch64-20231122-14.fc39.noarch.rpm | cpio -idmv
$ jq -r '.. | .filename? | select(.)' usr/share/qemu/firmware/52-edk2-aarch64-verbose-qcow2.json
/usr/share/edk2/aarch64/QEMU_EFI-pflash.qcow2
/usr/share/edk2/aarch64/vars-template-pflash.qcow2
$ /opt/homebrew/bin/qemu-system-aarch64 -M virt,accel=hvf -cpu host -m $((1 * 1024)) -nographic -snapshot \
-pflash $PWD/usr/share/edk2/aarch64/QEMU_EFI-pflash.qcow2 \
Fedora-Cloud-Base-39-1.5.aarch64.qcow2
```

Closing issue as it's resolved for me now!

**Comment by craigjperry2** [comment]
Hit this myself, wanted to add an alternative homebrew-specific workaround for this until the qemu fix lands:

1. `brew uninstall podman qemu`
2. Grab a copy of the previous homebrew formula for qemu working version v8.1.3: `wget https://raw.githubusercontent.com/Homebrew/homebrew-core/676c6922d79d24cc0794dd22250e3ea1167f2cd9/Formula/q/qemu.rb` - NB: i saved this to my ~/Downloads/ not to my /opt/homebrew install, there's no messing with homebrew's local formula git repo
3. Run `brew install qemu.rb` - there are some warnings but you'll see they're nothing to bother about in this case
4. Prevent homebrew upgrading this for now: `brew pin qemu` NB: you'll need to remember to unpin in january!
5. Then you can `brew install --ignore-dependencies podman ; podman machine init ; podman machine start`

**Comment by AntonioSun** [comment]
> Hit this myself, wanted to add an alternative homebrew-specific workaround for this until the qemu fix lands:

Thanks! I tried every single fix I can find on SO sites, but nothing works. I almost already want to give up, then decided to take a quick search here.

I can confirm that this non-homebrew-specific fix works for me. thx!!!

**Comment by lakkeger** [comment]
If you force remove the desktop app's podman and qemu dependency manually with:
```
brew uninstall --ignore-dependencies qemu podman
```
then the desktop app takes care of qemu and podman and everything works as expected.

**Comment by AntonioSun** [comment]
> then the desktop app takes care of qemu and podman and everything works as expected

Hmm... I'm still getting

![image](https://github.com/containers/podman/assets/2840074/6e49992e-e8bd-4aa9-828b-962ff0d63811)

Here is my work log:

```sh
$ podman
-bash: podman: command not found

$ brew uninstall --ignore-dependencies qemu podman
Error: No such keg: /opt/homebrew/Cellar/qemu

$ brew uninstall --ignore-dependencies podman
Error: No such keg: /opt/homebrew/Cellar/podman

$ brew install podman-desktop
. . .
==> Pouring qemu--8.2.0.arm64_sonoma.bottle.tar.gz
==> Pouring podman--4.8.3.arm64_sonoma.bottle.tar.gz
🍺  podman-desktop was successfully installed!

$ podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
^C

$ podman machine start --log-level=debug
Waiting for VM ...
# and then get the above screenshot

$ brew info podman-desktop
==> podman-desktop: 1.6.4

$ brew info qemu
==> qemu: stable 8.2.0 (bottled), HEAD

$ uname -rms
Darwin 23.2.0 arm64

$ sw_vers
ProductName:		macOS
ProductVersion:		14.2.1
BuildVersion:		23C71
```

If I do `brew uninstall --ignore-dependencies qemu podman` now, then, the desktop app immediately reports that the podman package is missing. If I close it, then I won't even be able to start again.

**Comment by lakkeger** [comment]
@AntonioSun You seem to missunderstand a bit what I meant. Install the cask:
```
brew install podman-desktop
```
Then remove the dependencies:
```
brew uninstall --ignore-dependencies --zap qemu podman
```
Then on the UI if you start up the desktop app it will report that podman is not installed. Click setup/install and that will start the podman installer. Click through the installer's steps and voila you are setup to run the `podman machine init` command.

**Comment by lclc** [comment]
Thanks @lakkeger, that worked for me on a M3.

**Comment by lilac** [comment]
I work around this issue by installing the head version of `qemu` on Jan 23, 2024. Following is the list of commands I ran.

```shell
# Install the head version of qemu from git repository.
brew unlink qemu
brew install --head qemu

# Recreate the machine.
podman machine rm
podman machine init

# Start the new machine.
podman machine start
```

After that, everything works as expected.

**Comment by RobYed** [comment]
Thanks @lilac! `brew install --head qemu` did the trick for me. However I needed to first install qemu and then podman without the qemu dependency, just like @craigjperry2 suggested [here](https://github.com/containers/podman/issues/21088#issuecomment-1871502921). 

This worked for me (don't forget to unpin later):

```
brew install --head qemu
brew pin qemu
brew install --ignore-dependencies podman
brew install minikube
podman machine init --cpus 8 --memory 32768 --rootful
podman machine start
```

**Comment by adrian-moisa** [comment]
I had the same issue on Mac M1 Pro. "Waiting for VM".  Got it working by reverting to qemu 8.1.3. It started using latest podman 4.9.0.
- `podman machine init -m 3072` - tried it as suggested, did not help.
- I tried several earlier podman versions up to 4.8.0. No luck.
- `podman machine start --log-level=debug` - Retrieve more info about the failure. Thanks to this command I got out this error message from qemu: `Synchronous Exception at 0x00000000BC562000 ASSERT [ArmCpuDxe] /home/kraxel/projects/qemu/roms/edk2/ArmPkg/Library/DefaultExceptionHandlerLib/Arch64/DefaultExceptionHandler.c(343): ((BOOLEAN)(0==1))`
- Following hints from here: Some people suggest reverting to an older qemu - [qemu ASSERT [ArmCpuDxe] DefaultExceptionHandler.c:333 on Mac M3](https://gitlab.com/qemu-project/qemu/-/issues/1990), [Synchronous Exception at 0x00000000BC562000](https://github.com/containers/podman/discussions/21122), [[podman machine start stuck "Waiting for VM" indefinitely with qemu synchronous exception MacOS M3](https://github.com/containers/podman/issues/20776#top)
#20776](https://github.com/containers/podman/issues/20776)
- I managed to get it running by reverting qemu to 8.1.3 [qemu.rb](https://github.com/Homebrew/homebrew-core/blob/676c6922d79d24cc0794dd22250e3ea1167f2cd9/Formula/q/qemu.rb). Reverting brew version instructions here: [How To Install Older Versions of Homebrew Packages](https://nelson.cloud/how-to-install-older-versions-of-homebrew-packages/) 


**Edit:**
Looks like the answer is buried in many answers. A plea to the original author @tekawade. Please append the description to let people know that there's are 2 ways to fix: via the rollback of qemu or via applehv provider. I wasted 3 hours looking for the answer. Had it been in the first post it would have been only 30 mins lost. Cheers!

**Comment by josepheiba** [comment]
I have the same problem with qemu @8.2.1
