### ISSUE TITLE
published ports not available

### ISSUE THREAD

**Issue by butleger** [containers/podman#21119]
### Issue Description

When i run container in podman and publish ports this ports not available on other machine. I can reach this ports on machine where podman is running. I run python3 http.server and reach this port, when container is down, so looks like it is not firewall issue.

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman run -dt -p 8080:80 nginx

### Describe the results you received

When curl http://127.0.0.1:8080 from podman machine all works fine. When curl from another machine i can see tcp SYN but no SYN, ACK in reverse. 

### Describe the results you expected

I expect see nginx page in another machine

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 2
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: control
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.0-91-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 388395008
  memTotal: 2059182080
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 0
  swapTotal: 0
  uptime: 204h 50m 24.13s (Approximately 8.50 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 2
    stopped: 2
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 8
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Thu Jan  1 03:00:00 1970
  GitCommit: ""
  GoVersion: go1.18.1
  OsArch: linux/amd64
  Version: 3.4.4
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by rhatdan** [comment]
Podman does not poke holes in firewalls.  If  you want ports available to remote machines, you have to adjust the firewall rules.

**Comment by butleger** [comment]
i open this port in ufw and can start python script to listen on this port

**Comment by butleger** [comment]
> Podman does not poke holes in firewalls. If you want ports available to remote machines, you have to adjust the firewall rules.

looks like it needs some special rules for cni firewall

**Comment by butleger** [comment]
i add rules in CNI-ADMIN and things start working, but is it should work like this?

**Comment by butleger** [comment]
Like i should open port and in addition add rules to specific chain?

**Comment by rhatdan** [comment]
If you want a process on a separate machine to reach a port on your host machine, then the port needs to be opened. Not really sure what your question means.
