### ISSUE TITLE
ERRO[0008] Error while applying layer: 

### ISSUE THREAD

**Issue by circuitikzuser** [containers/podman#21130]
### Issue Description

Distrobox relies on podman as container system on my system.
podman croaks unfortunately and exits with 

```
ERRO[0009] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 0:12 for /var/spool/mail): Check /etc/subuid and /etc/subgid: lchown /var/spool/mail: invalid argument 
  ApplyLayer exit status 1 stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 0:12 for /var/spool/mail): Check /etc/subuid and /etc/subgid: lchown /var/spool/mail: invalid argument
Error: Error committing the finished image: error adding layer with blob "sha256:80b613d8f1ff97f71b4b01e404b0d17d29ee58162c15135f6b9a5478cb1f7bff": ApplyLayer exit status 1 stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 0:12 for /var/spool/mail): Check /etc/subuid and /etc/subgid: lchown /var/spool/mail: invalid argument
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. Install distrobox and podman
2. Do  `distrobox create --name Resolve-Fedora-37 --image fedora:37`
3. The error message as above appears due to podman having an issue with uid/gid it seems

### Describe the results you received

ERRO[0009] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 0:12 for /var/spool/mail): Check /etc/subuid and /etc/subgid: lchown /var/spool/mail: invalid argument 
  ApplyLayer exit status 1 stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 0:12 for /var/spool/mail): Check /etc/subuid and /etc/subgid: lchown /var/spool/mail: invalid argument
Error: Error committing the finished image: error adding layer with blob "sha256:80b613d8f1ff97f71b4b01e404b0d17d29ee58162c15135f6b9a5478cb1f7bff": ApplyLayer exit status 1 stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 0:12 for /var/spool/mail): Check /etc/subuid and /etc/subgid: lchown /var/spool/mail: invalid argument

### Describe the results you expected

podman completing without throwing errors

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.19.6
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 32
  distribution:
    distribution: debian
    version: "11"
  eventLogger: journald
  hostname: Tango
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
  kernel: 5.15.0-12.2-liquorix-amd64
  linkmode: dynamic
  memFree: 112682340352
  memTotal: 135184121856
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 34355539968
  swapTotal: 34355539968
  uptime: 38h 52m 30.51s (Approximately 1.58 days)
registries: {}
store:
  configFile: /home/noneofyourbusiness/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/noneofyourbusiness/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/noneofyourbusiness/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 0
  BuiltTime: Wed Dec 31 19:00:00 1969
  GitCommit: ""
  GoVersion: go1.15.15
  OsArch: linux/amd64
  Version: 3.0.1
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Used with distrobox.
Podman fails.

### Additional information

happens always

There has been a post regarding a similar issue, but you closed it before it was resolved.
So the issue clearly still exists.

**Comment by vrothberg** [comment]
Thanks for reaching out, @circuitikzuser !

> potentially insufficient UIDs or GIDs available in user namespace (requested 0:12 for /var/spool/mail): Check /etc/subuid and /etc/subgid:

Can you share the contents of `/etc/subuid` and `/etc/subgid`?

**Comment by circuitikzuser** [comment]
$ cat /etc/subuid
demo:100000:65536
demo1:165536:65536
demo2:231072:65536

$ cat /etc/subgid
demo:100000:65536
demo1:165536:65536
demo2:231072:65536

**Comment by vrothberg** [comment]
@circuitikzuser that must be the source of the error.  Without the ID mappings, rootless won´t work. Can you add your user and report back?

**Comment by circuitikzuser** [comment]
What values must I add for the missing user?
I am not sure what the numbers mean.
The last number is 16bits in binary and seemingly always the same, dont know what the first represents.

Why the heck was there never entries added for the main user during a vanilla MX debian install ?
I sure did not edit it out !

**Comment by vrothberg** [comment]
> What values must I add for the missing user?

The archlinux wiki has [a great explanation](https://wiki.archlinux.org/title/Podman) of the format and what values to add.

If I did the math right, you may add an entry as follows: `$user:296608:65536`

> Why the heck was there never entries added for the main user during a vanilla MX debian install ?

That's up to the distribution/admin but outside of Podman's control.

**Comment by rhatdan** [comment]
useradd does this automatically, if the passwd entry was added manually or via some other tool, the /etc/subuid and /etc/subgid files might not be updated.

**Comment by vrothberg** [comment]
Closing the issue as it's unrelated to Podman but we can continue the conversation.

**Comment by circuitikzuser** [comment]
Thanks 
I will try and let you know.

**Comment by circuitikzuser** [comment]
After updating the files I still get the same error.
Is there maybe a daemon I have to restart to activate the changes to the files?

`Storing signatures
ERRO[0008] Error while applying layer: ApplyLayer exit status 1 stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 0:12 for /var/spool/mail): Check /etc/subuid and /etc/subgid: lchown /var/spool/mail: invalid argument 
  ApplyLayer exit status 1 stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 0:12 for /var/spool/mail): Check /etc/subuid and /etc/subgid: lchown /var/spool/mail: invalid argument
Error: Error committing the finished image: error adding layer with blob "sha256:80b613d8f1ff97f71b4b01e404b0d17d29ee58162c15135f6b9a5478cb1f7bff": ApplyLayer exit status 1 stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 0:12 for /var/spool/mail): Check /etc/subuid and /etc/subgid: lchown /var/spool/mail: invalid argument`

**Comment by rhatdan** [comment]
try `podman system migrate`  You might need to logout and log back in.

**Comment by circuitikzuser** [comment]
Did podman system migrate
At least the error now changed, but now it cant find something.
`ERRO[0000] invalid internal status, try resetting the pause process with "podman system migrate": cannot find newuidmap: exec: "newuidmap": executable file not found in $PATH `

**Comment by rhatdan** [comment]
Looks like you need to install newuidmap onto your system,  usually comes as part of shadow-utils.  But perhaps not on your distribution.

**Comment by circuitikzuser** [comment]
Neither newuidmap or shadow-utils are in MX/Debian repositories.
I did find that uidmap was not even installed !!! . How can they release a distro with that missing ?
Anyway.
I installed uidmap and now the errro changed again.

  ERRO[0005] unable to write volume event: "write unixgram @00150->/run/systemd/journal/socket: sendmsg: no such file or directory" 
ERRO[0005] unable to write volume event: "write unixgram @00150->/run/systemd/journal/socket: sendmsg: no such file or directory" 
ERRO[0005] unable to write pod event: "write unixgram @00150->/run/systemd/journal/socket: sendmsg: no such file or directory" 
ERRO[0000] unable to write pod event: "write unixgram @00155->/run/systemd/journal/socket: sendmsg: no such file or directory" 
ERRO[0000] unable to write pod event: "write unixgram @00155->/run/systemd/journal/socket: sendmsg: no such file or directory" 
ERRO[0000] unable to write pod event: "write unixgram @00155->/run/systemd/journal/socket: sendmsg: no such file or directory" 
ERRO[0000] unable to write pod event: "write unixgram @00155->/run/systemd/journal/socket: sendmsg: no such file or directory" 

This seems to be the usual old buggy bogus systemD nonsense. Linux is worse off with systemD for sure.
Usually at the source of most of my problems.

**Comment by circuitikzuser** [comment]
It works so the issue is resolved. 
But all these bogus and useless systemD and Dbus errors still pops-up like a clueless drunken sailor.  
systemD sure is the biggest scourge that ever happened to Linux. 
Just plain nonsense.

**Comment by circuitikzuser** [comment]
Thanks all for the help.
