### ISSUE TITLE
Podman --gpus all support instead of --devices nvidia.com/gpu=all for compability

### ISSUE THREAD

**Issue by Gnyblast** [containers/podman#21156]
### Feature request description

We have as a company been trying to adapt podman for many usages recently especially for Machine Learning side. Datalore and Prefect is just two of them and in both cases we hitting the wall on attaching GPUs to the container. Both of these application are dedicated to get used with Docker but we managed to get them run with podman for their base server, but they also access to the `docker.sock` which is `podman.sock` we mount and they spawn their own containers on demand to run some tasks. That's where we hit the wall, these applications are hardcoded to send API commands in a way that docker understands on how to bind GPUs to the container but podman has no idea because it uses a different run arguments for that purpose. This is really a thing that prevents us using it and I imagine it should be an easy fix to make podman understand `--gpus all` is exactly same thing as `--devices nvidia.com/gpu=all `.

### Suggest potential solution

If podman can consider `--gpus all` same as `--devices nvidia.com/gpu=all ` it will be solving toto many problems.

### Have you considered any alternatives?

Yes I tried everything, in datalore local agents, gives you option to append run arguments so local agents can get used, but weirdly external agents doesn't give you that option and sends `--gpus all` hardcoded and I don't want to wait for this development on their side.

**Comment by rhatdan** [comment]
Seams resablable But is '--gpus all' tied to nvidia? Or does it retrieve this from somewhere else?

**Comment by rhatdan** [comment]
`--devices nvidia.com/gpu=all ` does not exist in either Podman or Docker?

**Comment by Gnyblast** [comment]
Looks like Docker uses `--gpu all` command to attach Nvidia GPUs to the machine. In case of Podman this command is `--devices nvidia.com/gpu=all`. This difference between the run comman options makes Podman incompatible with some applications like Datalore and Prefect.

**Comment by Gnyblast** [comment]
> `--devices nvidia.com/gpu=all ` does not exist in either Podman or Docker?

It exists in Podman not sure about Docker but my understanding Docker uses `--gpus all`.

**Comment by Gnyblast** [comment]
> Does --gpus=foobar equate to --device nvidia.com/foobar?

Yes I think they are equivalent of each other if there is not anything else behind the scene that I don't know.
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/cdi-support.html
https://stackoverflow.com/questions/25185405/using-gpu-from-a-docker-container

**Comment by rhatdan** [comment]
$ podman run --devices
Error: unknown flag: --devices
See 'podman run --help'

**Comment by rhatdan** [comment]
Ok it is --device
