### ISSUE TITLE
Podman Redirects Successful Outputs to STDERR, Causing Azure DevOps Failures

### ISSUE THREAD

**Issue by beginner1010** [containers/podman#21181]
### Issue Description

I am facing an issue with Podman where it outputs to standard error (STDERR) even when the operation is successful. This behavior is causing problems in our Azure DevOps pipeline.

**Impact on Azure DevOps:**
In our Azure DevOps environment, the pipeline stages consider any output to STDERR as an error, causing the stage to fail. To mitigate this, we tried redirecting all STDERR to STDOUT. However, this approach has a drawback: actual errors are no longer recognized as such, and the stage incorrectly shows as successful (marked green) because we streamed the errors to STDOUT, which suppresses the real error recognition.

----
- Is there a known workaround or a fix for this issue where Podman outputs to STDERR even for successful operations?
- How can we differentiate between actual errors and normal output in such scenarios, especially in a CI/CD pipeline like Azure DevOps?

Thank you in advance for your assistance and insights.

### Steps to reproduce the issue

When running the podman pull command, Podman directs its output to STDERR instead of standard output (STDOUT). This can be reproduced by running a command like `podman pull [image] 2>stderr.txt`, where the output, even if successful, is saved to `stderr.txt`.

### Describe the results you received
```
[container]# podman pull hello-world 2>stderr.txt
d2c94e258dcb3c5ac2798d32e1249e42ef01cba4841c2234249495f87264ac5a
[container]# cat stderr.txt
Trying to pull docker.io/library/hello-world:latest...
Getting image source signatures
Copying blob sha256:c1ec31eb59444d78df06a974d155e597c894ab4cda84f08294145e845394988e
Copying config sha256:d2c94e258dcb3c5ac2798d32e1249e42ef01cba4841c2234249495f87264ac5a
Writing manifest to image destination
```
### Describe the results you expected

--

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.32.0
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon_100:2.1.10-1_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: 2dcd736e46ded79a53339462bc251694b150f870'
  cpuUtilization:
    idlePercent: 89.64
    systemPercent: 5.54
    userPercent: 4.82
  cpus: 8
  databaseBackend: boltdb
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: file
  freeLocks: 2048
  hostname: deploy-agent-68df654766-pzcv6
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.192-183.736.amzn2.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 4445495296
  memTotal: 16277569536
  networkBackend: cni
  networkBackendInfo:
    backend: cni
    dns: {}
    package: 'containernetworking, containernetworking-plugins: /opt/cni/bin'
    path: /opt/cni/bin
  ociRuntime:
    name: runc
    package: cri-o-runc_100:1.1.11-1_amd64
    path: /usr/lib/cri-o-runc/sbin/runc
    version: |-
      runc version unknown
      spec: 1.0.2-dev
      go: go1.21.5
      libseccomp: 2.5.3
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: false
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 1743h 43m 49.00s (Approximately 72.62 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 536858308608
  graphRootUsed: 31000961024
  graphStatus:
    Backing Filesystem: overlayfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.7.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.21.5
  Os: linux
  OsArch: linux/amd64
  Version: 4.7.0

```

### Podman in a container

Yes

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
you can use `--quiet` to silence the progress bars.

**Comment by beginner1010** [comment]
`podman tag` and `podman rmi` `podman login` do not accept --quiet. 
I used podman pull as an example.

**Comment by hochrai** [comment]
I face the same issue and dug into the discussions which explain/justify the existing behaviour. Would you consider to allow the end user to select the output channel of these messages via a command line flag? Then default behaviour can remain as is without breaking any backward-compatibility and CI users who want to see success messages on STDOUT instead of STDERR have the ability to do so.

**Comment by rhatdan** [comment]
We have decided that Docker behaviour is broken, and using --quiet will fix your issue.  Azure should not be looking for output on stderr to indicate errors, but actual exit codes.

**Comment by beginner1010** [comment]
I agree that ADO should look for exit codes not the output stream. Thanks for the update.
