### ISSUE TITLE
podman struck at starting machine in macos

### ISSUE THREAD

**Issue by ashokks80** [containers/podman#21205]
### Issue Description

Just installed podman in macos, after entering command podman machine start podman-machine-default it struck at starting machine "podman-machine-default". I don't see any logs or failures some thing like that.

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman machine init
2.podman machine start podman-machine-dafault
<img width="890" alt="Screenshot 2024-01-09 at 2 14 21 PM" src="https://github.com/containers/podman/assets/58323161/6a8db04c-caeb-4d3a-97f3-603355ffa1c1">

### Describe the results you received

struck at podman starting

### Describe the results you expected

it has to start a vm

### podman info output

```yaml
OS: darwin/arm64
provider: qemu
version: 4.8.3

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: ssh: handshake failed: read tcp 127.0.0.1:56467->127.0.0.1:55615: read: connection reset by peer
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by arixmkii** [comment]
If it is Apple Silicon and brew installation, then it is probably a duplicate of https://github.com/containers/podman/issues/21096 Linked issue has some workarounds listed.

**Comment by bentito** [comment]
Yeah I have exactly this problem. Can't use podman 😢

**Comment by cartesius68** [comment]
Podman still unusable on MacOS after all those weeks. Even the new 4.9.0 on Macos 14.3.

**Comment by bentito** [comment]
I agree Podman is not starting properly on MacOS. If you follow the detailed workaround instructions in https://github.com/containers/podman/issues/21096 you should be able to get it working. At least that worked for me.

**Comment by Luap99** [comment]
Podman 5.0 uses applehv now and qemu is no longer supported.
