### ISSUE TITLE
Unable to install the latest podman on Ubuntu 22.04 by following the instruction on the website

### ISSUE THREAD

**Issue by klesh** [containers/podman#21249]
### Issue Description

I followed this guide https://podman.io/docs/installation#ubuntu and try to install the latest podman on my WSL2 (ubuntu 22.04).
And it failed, looks like some of the package is broken, specifically the **conmon**  seems broken.
I tried downloading the package from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04/amd64/conmon_2:2.1.10-0ubuntu22.04+obs18.4_amd64.deb and installed it manually and this is what i got:
```
[klesh@klesh-laptop] ~/Downloads> sudo dpkg -i 'conmon_2 2.1.10-0ubuntu22.04+obs18.4_amd64.deb'
[sudo] password for klesh:
dpkg-deb: error: 'conmon_2 2.1.10-0ubuntu22.04+obs18.4_amd64.deb' is not a Debian format archive
dpkg: error processing archive conmon_2 2.1.10-0ubuntu22.04+obs18.4_amd64.deb (--install):
 dpkg-deb --control subprocess returned error exit status 2
Errors were encountered while processing:
 conmon_2 2.1.10-0ubuntu22.04+obs18.4_amd64.deb
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. follow https://podman.io/docs/installation#ubuntu to install the latest podman for ubuntu22.04
2. see error

### Describe the results you received

Get:1 https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_22.04  conmon 2:2.1.10-0ubuntu22.04+obs18.4 [122 kB]
Err:1 https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_22.04  conmon 2:2.1.10-0ubuntu22.04+obs18.4
  Hash Sum mismatch
  Hashes of expected file:
   - SHA256:862cf4a0fd50d140f0cdb6d6feeb002347bd67adc43faea14e500e4cf7ecc678
   - SHA1:a95ae224fac0cfdf476c47c209ab8cbfde470767 [weak]
   - MD5Sum:4fc653ed168cfa4516c0c8fa8f6ee052 [weak]
   - Filesize:121726 [weak]
  Hashes of received file:
   - SHA256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
   - SHA1:da39a3ee5e6b4b0d3255bfef95601890afd80709 [weak]
   - MD5Sum:d41d8cd98f00b204e9800998ecf8427e [weak]
   - Filesize:0 [weak]
E: Failed to fetch https://mirror.aardsoft.fi/opensuse/repositories/devel%3A/kubic%3A/libcontainers%3A/unstable/xUbuntu_22.04/amd64/conmon_2%3A2.1.10-0ubuntu22.04%2Bobs18.4_amd64.deb  Hash Sum mismatch
   Hashes of expected file:
    - SHA256:862cf4a0fd50d140f0cdb6d6feeb002347bd67adc43faea14e500e4cf7ecc678
    - SHA1:a95ae224fac0cfdf476c47c209ab8cbfde470767 [weak]
    - MD5Sum:4fc653ed168cfa4516c0c8fa8f6ee052 [weak]
    - Filesize:121726 [weak]
   Hashes of received file:
    - SHA256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    - SHA1:da39a3ee5e6b4b0d3255bfef95601890afd80709 [weak]
    - MD5Sum:d41d8cd98f00b204e9800998ecf8427e [weak]
    - Filesize:0 [weak]

### Describe the results you expected

Install successfully

### podman info output

```yaml
4:4.6.2-0ubuntu22.04+obs81.12
ubuntu 22.04 (wsl2 on windows 11)
x86_64
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by lstolcman** [comment]
Hi, what do you mean by "it failed, looks like some of the package is broken"?

The instruction docs "how to install on ubuntu" is apparently broken (at least on my side it did not work). However, I used kubic page to get the correct commands to add the apt repository and install podman (to get it, go [here]() and click "Download package" and select your system version. kubic repo contains podman version which is not the latest, although the build [should be fixed soon](https://build.opensuse.org/package/show/devel:kubic:libcontainers:unstable/podman#comment-1871338))

Please type the following:

```sh
echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list
curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/devel_kubic_libcontainers_unstable.gpg > /dev/null
sudo apt update
sudo apt install podman
```

I tested on clean ubuntu 22.04 on wsl2, I was able to isntall podman and run example container.


Alternatively, you can remove `conmon` from apt, and download and copy binary to `/usr/local/bin` from https://github.com/containers/conmon/releases/

**Comment by klesh** [comment]
@lstolcman The `conmon` package was broken, I downloaded it from the repo manually and it can not be recognized as a valid `deb` package by `dpkg`.

Anyway, I tried it again yesterday, and it worked again. Closing the issue now.
