### ISSUE TITLE
Equivalent `--root`, `--runroot`, `--registries-conf`, and `--registries-conf-dir` flags for podman's CLI

### ISSUE THREAD

**Issue by offbynull** [containers/podman#21250]
### Feature request description

My understanding is that the flags in the title are for buildah's CLI, and they allow the user to completely change up where buildah looks for its state/configuration for that specific launch of the CLI. Would it be possible for these flags (or similar flags) to be included in podman's CLI? This would help avoid polluting the user's list of podman containers / podman's state when automated scripts are involved. For example, imagine I have a custom script that runs podman's CLI to create a few containers. Maybe I don't want those containers to show up in the user's list of normal containers.

### Suggest potential solution

Add the flags.

### Have you considered any alternatives?

I've been using buildah directly in my scripts (as a hack) rather than using podman.

**Comment by rhatdan** [comment]
Similar flags are available for podman (Real podman, not Podman on the MAC, which is podman-remote.

**Comment by offbynull** [comment]
Apologies if this is the case. Could you kindly point me to the relevant
documentation? Google didn't give me any hits.

**Comment by offbynull** [comment]
So, it looks like `--root` and `--runroot` are there but `--registries-conf`, and `--registries-conf-dir` aren't.

**Comment by rhatdan** [comment]
Environment CONTAINERS_REGISTRIES_CONF should work, but no --registries-conf-dir equivalent.

**Comment by rhatdan** [comment]
We also have a hidden option.
./cmd/podman/root.go:		pFlags.StringVar(&podmanConfig.RegistriesConf, "registries-conf", "", "Path to a registries.conf to use for image processing")

**Comment by rhatdan** [comment]
This patch to Podman would enable --registires-conf-dir for podman build and podman kube play, but only for local non --remote builds.
[registries-conf-dir.patch](https://github.com/containers/podman/files/13931480/registries-conf-dir.patch.txt)

**Comment by offbynull** [comment]
Okay. I think this covers it. Thank you.
