### ISSUE TITLE
Error: database storage temporary directory (runroot) "" does not match our storage temporary directory (runroot) "/var/tmp/podman_test2131378507/runroot": database configuration mismatch

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#21270]
Seen just now in [f38 root](https://api.cirrus-ci.com/v1/artifact/task/5813390585626624/html/int-podman-fedora-38-root-host-boltdb.log.html#t--Podman-run-with-sig-proxy-signals-are-not-forwarded-to-container-with-sig-proxy-false--1), in #17831 which has no flake retries:
```
Podman run with --sig-proxy
  [It] signals are not forwarded to container with sig-proxy false
 .....
  # podman [options] run --name test2 --sig-proxy=false quay.io/libpod/systemd-image:20230531 bash -c trap "echo Received" SIGFPE; while :; do sleep 0.25; done
  # podman [options] ps -q
  Error: database storage temporary directory (runroot) "" does not match our storage temporary directory (runroot) "/var/tmp/podman_test2131378507/runroot": database configuration mismatch
```
My `cirrus-flake-grep` shows no other instances of this. Even though this is a one-off, I'm filing anyway because I just really don't like it.

**Comment by mheon** [comment]
F38 root *boltdb*? We have a lot of special handling around putting the empty string in DB paths in Bolt, and none in SQLite, so that's kind of surprising.

**Comment by Luap99** [comment]
@edsantiago Still seeing this?

**Comment by edsantiago** [comment]
Nope, only that one time. Let's sweep it under the rug.
