### ISSUE TITLE
podman machine start fails with "gvproxy exited unexpectedly with exit code 0"

### ISSUE THREAD

**Issue by jhaiduce** [containers/podman#21337]
### Issue Description

When starting a container with provider=applehv, `podman machine start` fails with `gvproxy unixgram socket "/var/folders/82/c0s0s7md2m1c5nzd6s08j1tn09h343/T/podman/gvproxy.sock" not found: stat /var/folders/82/c0s0s7md2m1c5nzd6s08j1tn09h343/T/podman/gvproxy.sock: no such file or directory`. This appears not to be a duplicate of #21288 because `${TMPDIR%%/}/podman/gvproxy.sock"` exists, but for some reason podman claims it doesn't. Also, the problem occurs without rebooting the host first.

### Steps to reproduce the issue

Steps to reproduce the issue
1. export CONTAINERS_MACHINE_PROVIDER=applehv
2. podman machine init
3. podman --log-level=debug machine start

### Describe the results you received

Error message is similar to #21288:
```
$ podman --log-level=debug machine start
INFO[0000] podman filtering at log level debug          
DEBU[0000] Using Podman machine with `applehv` virtualization provider 
DEBU[0000] connection refused: http://localhost:8081/vm/state 
Starting machine "podman-machine-default"
DEBU[0000] connection refused: http://localhost:8081/vm/state 
DEBU[0000] gvproxy binary being used: /opt/homebrew/Cellar/podman/4.9.0/libexec/podman/gvproxy 
DEBU[0000] [-debug -mtu 1500 -ssh-port 56066 -listen-vfkit unixgram:///var/folders/82/c0s0s7md2m1c5nzd6s08j1tn09h343/T/podman/gvproxy.sock -forward-sock /Users/haiducek/.local/share/containers/podman/machine/applehv/podman.sock -forward-dest /run/user/1083706499/podman/podman.sock -forward-user core -forward-identity /Users/haiducek/.ssh/podman-machine-default -pid-file /var/folders/82/c0s0s7md2m1c5nzd6s08j1tn09h343/T/podman/gvproxy.pid] 
DEBU[0000] gvproxy unixgram socket "/var/folders/82/c0s0s7md2m1c5nzd6s08j1tn09h343/T/podman/gvproxy.sock" not found: stat /var/folders/82/c0s0s7md2m1c5nzd6s08j1tn09h343/T/podman/gvproxy.sock: no such file or directory 
Error: gvproxy exited unexpectedly with exit code 0
DEBU[0000] Shutting down engines                        
```

But unlike #21288, /var/folders/82/c0s0s7md2m1c5nzd6s08j1tn09h343/T/podman exists:
```
$ ls /var/folders/82/c0s0s7md2m1c5nzd6s08j1tn09h343/T/podman
podman-machine-default_ready.sock
```

### Describe the results you expected

podman machine start runs successfully

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.

OS: darwin/arm64
provider: applehv
version: 4.9.0

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: dial tcp 127.0.0.1:56066: connect: connection refused
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Host is MacOS Monterey (12.6.1)

**Comment by Luap99** [comment]
The error is `gvproxy exited unexpectedly with exit code 0`

**Comment by jfrantzius** [comment]
See also discussion https://github.com/containers/podman-desktop/discussions/5669

**Comment by jfrantzius** [comment]
This can be reproduced with Podman Desktop pre-release 1.7.0 (podman 4.9.0) when following the installation instructions for installing from .dmg here (without any brew): https://gist.github.com/jfrantzius/0996e224cbe81d885553ece6f8abf99a

**Comment by Schweeeeeeeeeeeeeeee** [comment]
same problem on arch

**Comment by herrernst** [comment]
me too with podman 5.0 release

**Comment by Luap99** [comment]
Do you still see this?

**Comment by ashley-cui** [comment]
Closing as there is no response and there have been fixes in 5.X since.
