### ISSUE TITLE
there's a mislead about filter on podman docs

### ISSUE THREAD

**Issue by Cl1p** [containers/podman#21346]
### Feature request description

docs/source/markdown/podman-search.1.md.in ([web path](https://docs.podman.io/en/stable/markdown/podman-search.1.html))
![podman_search_wrong_explain](https://github.com/containers/podman/assets/27112718/864819da-4560-490e-a19a-fcedfd4c17b5)

The image above is not the correct explain, I found the right one like below ([web path](https://docs.podman.io/en/latest/_static/api.html?version=v4.0#tag/images/operation/ImageSearchLibpod))

![podman_search_right_explain](https://github.com/containers/podman/assets/27112718/5004688d-9e3f-45b4-9767-9db260f1dac2)

### Suggest potential solution

should be at least number of stars , I confirmed the right output like this 

![image](https://github.com/containers/podman/assets/27112718/0abfb483-957e-45b3-98f8-cf5043ba7e1d)

**Comment by rhatdan** [comment]
Interested in opening a PR to fix?

**Comment by kanielrkirby** [comment]
@rhatdan I opened a PR to correct that section of the documentation.

**Comment by marinmo** [comment]
@rhatdan As the PR by @kanielrkirby was merged, should be able to close this one?
