### ISSUE TITLE
Network Settings.IPAddress never populates and have no connectivity to a podman container (through podman network or pod)

### ISSUE THREAD

**Issue by mattFernandezNGC** [containers/podman#21340]
### Issue Description

When I run a podman container from inside of a podman pod or run a podman container when attaching to a podman network the "Network Settings" section never gets populated.  This could be the reason why I am never able to successfully connect to a kafka broker running inside of a container-inside of the pod.  My containerized java application has no issues connecting to the container while running inside of the pod.  There is absolutely 0 connectivity to the kafka broker running outside of the podman pod.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman pod create -n test --network <localNetwork> -p 1337:1337`
2. or `podman pod create -n test --network slirp4netns:port_handler=slirp4netns -p 1337:1337`
3.  `podman run --rm -d --pod test <localImage>`
4. `podman inspect localImage>

### Describe the results you received

          "NetworkSettings": {
               "EndpointID": "",
               "Gateway": "",
               "IPAddress": "",
               "IPPrefixLen": 0,
               "IPv6Gateway": "",
               "GlobalIPv6Address": "",
               "GlobalIPv6PrefixLen": 0,
               "MacAddress": "",
               "Bridge": "",
               "SandboxID": "",
               "HairpinMode": false,
               "LinkLocalIPv6Address": "",
               "LinkLocalIPv6PrefixLen": 0,
               "Ports": {
}}

### Describe the results you expected

          "NetworkSettings": {
               "EndpointID": "",
               "Gateway": "",
               "IPAddress": "",
               "IPPrefixLen": 0,
               "IPv6Gateway": "",
               "GlobalIPv6Address": "",
               "GlobalIPv6PrefixLen": 0,
               "MacAddress": "",
               "Bridge": "",
               "SandboxID": "",
               "HairpinMode": false,
               "LinkLocalIPv6Address": "",
               "LinkLocalIPv6PrefixLen": 0,
               "Ports": {

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.27.3
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.4-1.module+el8.7.0+17498+a7f63b89.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.4, commit: 419a7c7817d7da098aa7648abddea5014f593ac6'
  cpuUtilization:
    idlePercent: 96.2
    systemPercent: 3.1
    userPercent: 0.7
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "8.7"
  eventLogger: file
  hostname: mau-swtest-01d.local.bench
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1599200003
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1599200023
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-372.9.1.el8.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 1967775744
  memTotal: 33591554048
  networkBackend: cni
  ociRuntime:
    name: crun
    package: crun-1.5-1.module+el8.7.0+17498+a7f63b89.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.5
      commit: 54ebb8ca8bf7e6ddae2eb919f5b82d1d96863dea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1599200023/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.0-2.module+el8.7.0+17498+a7f63b89.x86_64
    version: |-
      slirp4netns version 1.2.0
      commit: 656041d45cfca7a4176f6b7eed9e4fe6c11e8383
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 8580694016
  swapTotal: 8589930496
  uptime: 183h 14m 58.00s (Approximately 7.62 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /pfss/home/mfernandez/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 2
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.9-1.module+el8.7.0+17498+a7f63b89.x86_64
      Version: |-
        fusermount3 version: 3.3.0
        fuse-overlayfs: version 1.9
        FUSE library version 3.3.0
        using FUSE kernel interface version 7.26
  graphRoot: /var/tmp/mfernandez
  graphRootAllocated: 28951183360
  graphRootUsed: 4271693824
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 16
  runRoot: /run/user/1599200023/containers
  volumePath: /var/tmp/mfernandez/volumes
version:
  APIVersion: 4.2.0
  Built: 1670845316
  BuiltTime: Mon Dec 12 11:41:56 2022
  GitCommit: ""
  GoVersion: go1.18.4
  Os: linux
  OsArch: linux/amd64
  Version: 4.2.0
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Podman version 4.2.0

### Additional information

Again, I can connect to the containerized kafka broker while running inside of the pod but have 0 connectivity from outside of that pod.

**Comment by Luap99** [comment]
Slirp4netns does not allow inter container communication, the ip in the container is not reachable from the outside other than forwarded ports. So you either have to communicate over forwarded ports or you must use named networks (`podman network ls`)
