### ISSUE TITLE
Podman 4.9 PKG provides qemu 8.0.0 

### ISSUE THREAD

**Issue by slemeur** [containers/podman#21353]
### Issue Description

Installing Podman 4.9 on a new laptop today, I initially used Podman Desktop, which installed podman and Qemu. I ended up with the version 8.0.0 of QEMU. Removing my QEMU installation, I've downloaded the proper PKG from the 4.9 release artifacts: https://github.com/containers/podman/releases/tag/v4.9.0 . 

It appears that the QEMU version installed is 8.0.0:
https://github.com/containers/podman/blob/01b2243e73076a0e71a667153af1b98ecbf3b2f5/contrib/pkginstaller/Makefile#L10

We should be providing a newer version of QEMU. Ideally, the one that is validated to be solving the [qemu ASSERT [ArmCpuDxe] DefaultExceptionHandler.c:333 on Mac M3 (#1990) · Issues · QEMU / QEMU · GitLab](https://gitlab.com/qemu-project/qemu/-/issues/1990)

### Steps to reproduce the issue

Steps to reproduce the issue
1. Install podman on mac from the PKG
2. Check the version of QEMU in `opt/podman/qemu/bin`

### Describe the results you received

Qemu version is 8.0.0

### Describe the results you expected

--

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
Looks like it was updated here: https://github.com/containers/podman/pull/21445
