### ISSUE TITLE
podman farm support for registries.conf settings

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman#21352]
### Feature request description

When building with `podman farm`, the registries.conf is not used (for instance for insecure registries)

### Suggest potential solution

The build and push works OK with `podman build`, but it fails with `podman farm build` (due to https)

### Have you considered any alternatives?

The workaround (for insecure) is to use `--tls-verify=false`, but other settings might be harder to replicate.

### Additional context

Broken out from issue:
* #21338

**Comment by vrothberg** [comment]
registries.conf is a server-side configuration.  I guess that's what's happening here.

**Comment by umohnani8** [comment]
Oh okay, I thought it was on the client side similar to how the auth file is on the client side and we send that info over to the server. I hadn't looked into what we did for podman push yet when remote and wrt to registries.conf, but if it is a server side configuration then nothing needs to be done here for farm apart from probably updating the docs.

**Comment by afbjorklund** [comment]
I had changed both client and server configuration, though.
