### ISSUE TITLE
Support creating tmpfs mounts inside containers with memory-backend emptyDir configuration

### ISSUE THREAD

**Issue by andremarianiello** [containers/podman#21367]
### Feature request description

From the [k8s docs](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir):

> The emptyDir.medium field controls where emptyDir volumes are stored. By default emptyDir volumes are stored on whatever medium that backs the node such as disk, SSD, or network storage, depending on your environment. If you set the emptyDir.medium field to "Memory", Kubernetes mounts a tmpfs (RAM-backed filesystem) for you instead.

This medium field is ignored by `podman play kube`. It would be useful if podman made a tmpfs when `medium: Memory` is specified.

### Suggest potential solution

`Medium` is already part of the empty dir spec. That information is being thrown away by `VolumeFromEmptyDir`, but if it is retained it should be able to be propagated as necessary. And podman already supports `tmpfs` mounts in general, just not from kube config.

### Have you considered any alternatives?

Using a default emptyDir produces an ephemeral volume, but it has the performance characteristics of host storage, which is not suitable for use cases where `tmpfs` performance is needed. Making a `tmpfs` on the host and mounting it into the pod with a hostPath volume is possible, but introduces potentially security issues.

### Additional context

From the k8s docs on sizing memory-backed emptyDirs:

> Note: If the SizeMemoryBackedVolumes [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) is enabled, you can specify a size for memory backed volumes. If no size is specified, memory backed volumes are sized to node allocatable memory.

For compatibility, podman might want to take a similar approach for sizing

**Comment by giuseppe** [comment]
that seems useful.

Would you like to open a PR to add this feature?

**Comment by andremarianiello** [comment]
I can certainly try! However, I have some higher priority stuff to do before I get back around to this. I am happy to work on in when I get time, but if someone sees this issue and wants to pick it up before then, feel free.

**Comment by Luap99** [comment]
@andremarianiello For the future please add `Fixes #XXXX` or `Closes #XXXX` in your commit and PR so the issue will be auto closed once the PR is merged. Regardless thanks for the contribution. Fixed in https://github.com/containers/podman/pull/21524.
