### ISSUE TITLE
Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Unknown Error

### ISSUE THREAD

**Issue by moose-byte** [containers/podman#21375]
### Issue Description

Podman fails to start on a new Apple M1 laptop. I'm suspicious about the default image because I have an AArch64 architecture, and the image is x86_64, but from what I understand, it shouldn't matter. This is a fresh install, and Podman used to work fine on my old machine. Any advice would me much appreciated.

```shell
$ brew info podman
==> podman: stable 4.9.0 (bottled), HEAD
Tool for managing OCI containers and pods
https://podman.io/
/usr/local/Cellar/podman/4.9.0 (198 files, 73.9MB) *
  Poured from bottle using the formulae.brew.sh API on 2024-01-25 at 16:20:33
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/p/podman.rb
License: Apache-2.0 and GPL-3.0-or-later
==> Dependencies
Build: go ✔, go-md2man ✔, make ✔
Required: qemu ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
        In order to run containers locally, podman depends on a Linux kernel.
        One can be started manually using `podman machine` from this package.
        To start a podman VM automatically at login, also install the cask
        "podman-desktop".

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Analytics
install: 23,992 (30 days), 62,574 (90 days), 162,730 (365 days)
install-on-request: 20,375 (30 days), 53,065 (90 days), 144,199 (365 days)
build-error: 110 (30 days)
```

```shell
$ podman machine init
Extracting compressed file: podman-machine-default_fedora-coreos-39.20240112.2.0-qemu.x86_64.qcow2: done
Image resized.
Machine init complete
To start your machine run:

	podman machine start
```

```shell
$ podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Unknown Error
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. brew install podman
2. podman init
3. podman start

### Describe the results you expected

Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Unknown Error

### podman info output

```yaml
podman info
OS: darwin/amd64
provider: qemu
version: 4.9.0

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: dial tcp 127.0.0.1:59724: connect: connection refused
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by arixmkii** [comment]
Please describe how did you install Podman. There was similar issue and solution posted in https://github.com/containers/podman/issues/21096#issuecomment-1898425312 but if you have some specific you might need some extra steps.

**Comment by arixmkii** [comment]
@moose-byte  Please describe how did you install Podman. There was similar issue and solution posted in https://github.com/containers/podman/issues/21096#issuecomment-1898425312 but if you have some specific you might need some extra steps.

**Comment by moose-byte** [comment]
I installed it with homebrew

```shell
brew install podman podman-desktop
```

**Comment by arixmkii** [comment]
Please provide output of the commands from
https://github.com/containers/podman/issues/21096#issuecomment-1898155422
Also, could you mention if you restored your homebrew setup from a backup
of Intel Mac?

**Comment by moose-byte** [comment]
I installed the official arm64 version, and that fixed my issue! I didn't restore my homebrew setup from an Intel Mac, a started fresh on my new machine

**Comment by moose-byte** [comment]
Funny enough, I think hombrew thinks I have an x86_64 machine

```shell
brew config
HOMEBREW_VERSION: 4.2.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9c8374d3b78c4f531c5c2c0d272d1fb1f1b60d70
Last commit: 5 days ago
Core tap JSON: 26 Jan 18:38 UTC
Core cask tap JSON: 26 Jan 18:38 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_EDITOR: st
HOMEBREW_MAKE_JOBS: 10
Homebrew Ruby: 3.1.4 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/3.1.4/bin/ruby
CPU: 10-core 64-bit westmere
Clang: 15.0.0 build 1500
Git: 2.39.3 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 8.4.0 => /usr/bin/curl
macOS: 14.3-x86_64     <---------------------
CLT: 15.1.0.0.1.1700200546
Xcode: N/A
Rosetta 2: true
```

I can't control my homebrew installation; my company's IT department installs it.
