### ISSUE TITLE
podman farm list should not require an "engine" (connection)

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman#21383]
### Feature request description

Currently when you try to distribute builds with `podman-remote`, it _still_ requires a local socket with v4.9.0

You can't even do farm list:

`Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM`

Only edit containers.conf.

### Suggest potential solution

I think that at least `podman-remote farm list` shouldn't require a connection, probably only "build" needs one ?

### Have you considered any alternatives?

`cat ~/.config/containers/containers.conf`

### Additional context

Looking at "system connection list", it seems that you can no-op the engine creation.

```diff
diff --git a/cmd/podman/farm/list.go b/cmd/podman/farm/list.go
index eb13b6d48..26742f276 100644
--- a/cmd/podman/farm/list.go
+++ b/cmd/podman/farm/list.go
@@ -25,7 +25,9 @@ and the output format can be changed to JSON or a user specified Go template.`
                Args:               validate.NoArgs,
                Short:              "List all existing farms",
                Long:               farmLsDescription,
+               PersistentPreRunE:  validate.NoOp,
                RunE:               list,
+               PersistentPostRunE: validate.NoOp,
                ValidArgsFunction:  completion.AutocompleteNone,
        }
 
```

cc @umohnani8

**Comment by Luap99** [comment]
I would assume this applies to farm add,rm,update, etc... as well. I think even build does not need it depending on what connections are selected.

**Comment by afbjorklund** [comment]
Some of the other commands do a "test call", just to see that the connection name that you provide is still working (or something like that?)

**Comment by afbjorklund** [comment]
But maybe it should be handled the same way (as s"ystem connection", disabled in the top "farm" command and then enabled again where it is needed?

**Comment by afbjorklund** [comment]
@umohnani8
