### ISSUE TITLE
Support mmap on bind mounts to APFS

### ISSUE THREAD

**Issue by sanmai-NL** [containers/podman#21407]
### Feature request description

See https://github.com/containers/podman/issues/19639#issuecomment-1681444069. This was closed for a specific case, but the problem is more general. The linked comment describes the remaining problem and suggests a solution.

`mmap failed: Invalid argument`

### Suggest potential solution

See https://github.com/containers/podman/issues/19639#issuecomment-1681444069.

### Have you considered any alternatives?

Not using software that depends on mmap. Even some linkers, like `mold`, depend on it though.

**Comment by rhatdan** [comment]
Have you tried with applehv?

**Comment by Luap99** [comment]
I assume this works with virtiofs now since 5.0 on macos
