### ISSUE TITLE
Pulling images from docker into podman via daemon protocol not working due to API incompatibility

### ISSUE THREAD

**Issue by koen-serneels** [containers/podman#21419]
### Issue Description

I´m trying to pull images into podman from a docker daemon. First attempt was with docker and podman both installed on my host machine:

```
podman pull docker-daemon:hello-world:latest
Error: initializing source docker-daemon:hello-world:latest: loading image from docker engine: Error response from  daemon: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer  version
```

Host docker version:

> Client: Docker Engine - Community
>
>  Version:           25.0.1
>  API version:       1.44
>  Go version:        go1.21.6
>  Git commit:        29cf629
>  Built:             Tue Jan 23 23:09:23 2024
>  OS/Arch:           linux/amd64
>  Context:           default
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          25.0.1
>   API version:      1.44 (minimum version 1.24)
>   Go version:       go1.21.6
>   Git commit:       71fa3ab
>   Built:            Tue Jan 23 23:09:23 2024
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.6.27
>   GitCommit:        a1496014c916f9e62104b33d1bb5bd03b0858e59
>  runc:
>   Version:          1.1.11
>   GitCommit:        v1.1.11-0-g4bccb38
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0`
> 

Host podman version:

> Version:      3.4.4
> API Version:  3.4.4
> Go Version:   go1.18.1
> Built:        Thu Jan  1 01:00:00 1970
> OS/Arch:      linux/amd64

This is an older version, but that is all I can get on debian at this time (Mint 21.2) So, my next attempt was to run podman inside a container (docker:latest) hoping to get a new version. This played out well:

> Client:       Podman Engine
> Version:      4.8.3
> API Version:  4.8.3
> Go Version:   go1.21.5
> Built:        Wed Jan  3 22:19:43 2024
> OS/Arch:      linux/amd64

Unfortunately, pulling inside the container resulted in :

```
/ # podman pull docker-daemon:hello-world:latest
Error: initializing source docker-daemon:hello-world:latest: loading image from docker engine: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

A few tests pointed out that podman pull is not adhering the DOCKER_HOST variable and it always using the socket which isn´t linked. So, socat to the rescue:

`socat UNIX-LISTEN:/var/run/docker.sock,fork TCP-CONNECT:192.168.0.27:2375`

This time it worked, however, I got the exact same error as on my host:

```
/ # podman pull docker-daemon:hello-world:latest
Error: initializing source docker-daemon:hello-world:latest: loading image from docker engine: Error response from daemon: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
```

http traffic is showing that the call is made to /v1.22:

> > 2024/01/29 22:12:43.000185379  length=119 from=0 to=118
> GET /v1.22/images/get?names=hello-world%3Alatest HTTP/1.1\r
> Host: api.moby.localhost\r
> User-Agent: Go-http-client/1.1\r
> \r
> < 2024/01/29 22:12:43.000185654  length=342 from=0 to=341
> HTTP/1.1 400 Bad Request\r
> Api-Version: 1.44\r
> Content-Type: text/plain; charset=utf-8\r
> Ostype: linux\r
> Server: Docker/25.0.1 (linux)\r
> X-Content-Type-Options: nosniff\r
> Date: Mon, 29 Jan 2024 22:12:43 GMT\r
> Content-Length: 117\r
> \r
> client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
> 

Any idea what is going on? Why isn´t podman pull adhering to the DOCKER_HOST variable and why does the latest podman seem incompatible with the latest docker version?

### Steps to reproduce the issue

See description

### Describe the results you received

See description

### Describe the results you expected

See description

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

Yes

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by koen-serneels** [comment]
When testing podman 4.8.3 with an older docker engine (docker:23.0.0-dind) I can confirm that the pull via the docker-daemon works. So it seems that docker has lifted the minimum API version in their more recent releases and that   podman needs to upgrade

**Comment by mtrmac** [comment]
Yes, this is ~ https://github.com/containers/skopeo/issues/2202 , fixed in https://github.com/containers/skopeo/issues/2202 on `main`, and on a branch in https://github.com/containers/image/pull/2270 = c/image 5.29.2

**Comment by mtrmac** [comment]
Also note the workaround documented in https://github.com/containers/skopeo/issues/2202 .

**Comment by rhatdan** [comment]
So if we vendor in latest containers/image we can close this?

**Comment by mheon** [comment]
I'm going to close, we pulled the updated c/image into 4.9.1

**Comment by mtrmac** [comment]
> So if we vendor in latest containers/image we can close this?

Yes. Doing that on `main` ~depends (well, not quite, but, eventually…) on https://github.com/containers/buildah/pull/5286 .
