### ISSUE TITLE
publish event when there are errors as well

### ISSUE THREAD

**Issue by benoitf** [containers/podman#21458]
### Feature request description

In Podman Desktop we're interested to track failures of people trying to pull images for example.

One issue is that while if it's a user that do that inside Podman Desktop we can track the call to the REST API, etc.

But quite often, user is starting containers/pulling images from shell scripts, by using some `compose up` commands on the CLI, by the IDE, etc so we don't see any errors. In case of success, we receive events with the name of the image, the id of the image, etc.

### Suggest potential solution

I would like to receive pull error events.

For example if I pull 'hello', it would send an event like 'pull-error' with image being `quay.io/podman/hello` (FQDN) and the error of why we were not able to pull the image

I would expect an error code as well to not really to have to parse error messages.

Then, we could for example prompt the user to authenticate to some registries if not done, etc.

### Have you considered any alternatives?

N/A

### Additional context

We could for example prompt the user to authenticate to some registries depending on the error

**Comment by Luap99** [comment]
@rhatdan This still needs work in podman: https://github.com/containers/podman/pull/21563#discussion_r1508817409
