### ISSUE TITLE
shell completion container name from root user 

### ISSUE THREAD

**Issue by burgesQ** [containers/podman#21515]
### Feature request description

Currently, attempting to resolve the container names from a `sudo podman [smth]` command fails.

```
% sudo podman ps -a 
CONTAINER ID  IMAGE           COMMAND     CREATED   STATUS   PORTS  NAMES
(...) some containers

% sudo podman exec -it [tab] // fail to auto-complete containers name
```

Both my current and root users have the zsh completion script installed and loaded in the `fpath`

### Suggest potential solution

Not really sure - should the issue be opened on cobra side ?

### Have you considered any alternatives?

The only solution I've currently found is to start a session as root. By doing so, the containers names are resolved by the zsh auto-completion script. 

### Additional context

```console
16:13:30 ❯ zsh --version
zsh 5.8.1 (x86_64-ubuntu-linux-gnu)

16:13:31 ❯ podman --version             
podman version 4.8.3
```

**Comment by edsantiago** [comment]
This is unsolvable. It is pretty much equivalent to
```console
$ sudo ls -l /root/<TAB>
```
There is nothing podman or cobra or anything or anyone can possibly do to resolve this. I'm sorry.

**Comment by Luap99** [comment]
I think sudo already has a special shell completion scripts to call into the completion scripts of the following command so I think it would make the most to ask the maintainers of the sudo completion script if there is something that can be done.

**Comment by burgesQ** [comment]
> There is nothing podman or cobra or anything or anyone can possibly do to resolve this. I'm sorry.

So sad to hear that ... I think I've just found my first only inconvenient while switching from docker compose to podman pods, I think I'll manage it :) 

But container completion's pretty much useless for me 😿
