### ISSUE TITLE
`quay.io/containers/podman-remote-artifacts` requires authorization

### ISSUE THREAD

**Issue by xduugu** [containers/podman#21574]
### Issue Description

According to [contrib/podmanremoteimage/README.md](https://github.com/containers/podman/blob/5311233f86eb40005c0ebe7e13d1f5c0576211c5/contrib/podmanremoteimage/README.md), there are images available at [`quay.io/containers/podman-remote-artifacts`](https://quay.io/containers/podman-remote-artifacts) that contain the static `podman-remote` binaries. However, these images are not publicly accessible (anymore?).

Running one of the commands provided in the README fails with an authorization error:

```bash
$ podman cp $(podman create --name remote-temp quay.io/containers/podman-remote-artifacts:latest):/podman-remote-static-linux_amd64 . && podman rm remote-temp
Trying to pull quay.io/containers/podman-remote-artifacts:latest...
Error: initializing source docker://quay.io/containers/podman-remote-artifacts:latest: reading manifest latest in quay.io/containers/podman-remote-artifacts: unauthorized: access to the requested resource is not authorized
Error: accepts 2 arg(s), received 1
```

### Steps to reproduce the issue

Steps to reproduce the issue
1.
2.
3.

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by cevich** [comment]
Sorry I have no idea what that repo is.  I get a 404 from quay trying to access it.  Maybe you're thinking of `quay.io/podman/stable` or `quay.io/containers/podman` (same contents)?  Those images all have a `podman` binary available you could use to connect to a remote socket.  

Unf. they don't have `podman-remote` available, I just checked.  But you can do all the same things with the `podman` binary, so there's not much point.

Does that help, or were you asking about something else?

**Comment by cevich** [comment]
I see the README you're referring to.  Looks like it was last touched at the end of 2022.  Honestly I didn't even know it was there.  I'll open a PR to update the docs or just remove it.

**Comment by Luap99** [comment]
This is described here: https://github.com/containers/podman/blob/main/contrib/podmanremoteimage/README.md
And the real images do not contain static remote binaries for windows and macos.

**Comment by xduugu** [comment]
@cevich Unfortunately, `quay.io/containers/podman` is not suitable for me. By the way, there are no images for the releases since v4.9.0.

I was looking for an official image that contains `podman-remote` to copy the binary from instead of downloading and extracting the tarball from the github releases when building a devcontainer image. If I would use the regular `podman` binary, I had to create a wrapper script that passes the `--remote` option and, since the binary is not statically linked, some additional libraries had to be installed.

My use case would look like this:

```Dockerfile
FROM docker.io/library/debian:12

COPY --from=quay.io/containers/podman:v4.9.0 \
    /usr/bin/podman \
    /usr/local/bin/podman

RUN /usr/local/bin/podman info
```

But this fails with the regular podman binary, because of a missing library:

```
/usr/local/bin/podman: error while loading shared libraries: libsubid.so.4: cannot open shared object file: No such file or directory
```

**Comment by cevich** [comment]
Sorry, I'm confused why extracting a binary from a container image is more useful than an official installer or package for your OS of choice.  The example you provide illustrates exactly why: You need a binary suitable for the environment.  That cannot be guaranteed outside of a container.  Heck even the official release tarball will only work in certain environments. 
Unless I'm misunderstanding something, please let me know.  Is there a reason you can't simply install the podman debian package?

**Comment by xduugu** [comment]
I don't want to extract the binary to use it on my host system, but add it to an image that I use as a devcontainer. Because I need the development tools and docker-compose at the same time in several scripts, I expose the host podman socket to the container and run `podman compose` inside the container. It is similar to the setups described in https://www.redhat.com/sysadmin/podman-inside-container.

My setup looks like this:
- Rootless podman on Fedora 39 (host)
- Development container with docker-compose and podman-remote (dockers official language-specific images are usually debian-based)

I don't use the distro's podman package, because the packages on distributions, which are not Fedora, are usually quite outdated and, at least as far as I remember, there are some issues if the connecting podman is too old for the remote podman (maybe only an issue when using different major versions of podman). In my specific case, I also depend on `podman compose` which is only available in podman >= 4.6.

**Comment by Luap99** [comment]
static podman-remote linux binaries are attached to every release on github

**Comment by cevich** [comment]
> static podman-remote linux binaries are attached to every release on github

Are they? I thought we stopped doing that.  I'll trust what @Luap99 says over my memory though :rofl: 

> some issues if the connecting podman is too old

If you're debian based, you could grab the SID package, no?  They keep that really current with development, I know because we use it in our CI.

**Comment by cevich** [comment]
Oh yeah, [will you look at that](https://github.com/containers/podman/releases/latest)! `podman-remote-static-linux_amd64.tar.gz` and `podman-remote-static-linux_arm64.tar.gz`.  Neat!  @xduugu do those meet your needs?

**Comment by xduugu** [comment]
@Luap99 @cevich Thanks! These are exactly the tarballs I was talking about [before](https://github.com/containers/podman/issues/21574#issuecomment-1936462612). By the way, for the v4.9.3 release, these tarballs are missing for some reason.

To sum up this issue:

I have a Dockerfile that contains these `RUN` commands:

```Dockerfile
# install podman-remote
RUN set -xe \
	&& tarfile="/tmp/podman-remote.tar.gz" \
	&& file="podman-remote-static-linux_amd64" \
	&& dest="/usr/local/bin" \
	&& release="v4.9.2" \
	&& sha256sum="873a019d6d2e9baafeb760a85cf252bcac441fe538064e0b39594b5ce820c6ad" \
	&& curl -L -o "$tarfile" "https://github.com/containers/podman/releases/download/${release}/${file}.tar.gz" \
	&& echo "$sha256sum  $tarfile" | sha256sum -c - \
	&& tar xaf "$tarfile" -C "$dest" --no-same-owner --strip-components=1 "bin/$file" \
	&& rm "$tarfile" \
	&& mv "$dest/$file" "$dest/docker"

# install docker-compose
COPY --from=docker.io/docker/compose-bin:v2.24.6 \
	/docker-compose \
	/usr/libexec/docker/cli-plugins/docker-compose
```

and I hoped that I could use `quay.io/containers/podman-remote-artifacts` to get to something like:

```Dockerfile
# install podman-remote
COPY --from=quay.io/containers/podman-remote:v4.9.2 \
	/podman-remote \
	/usr/local/bin/docker

# install docker-compose
COPY --from=docker.io/docker/compose-bin:v2.24.6 \
	/docker-compose \
	/usr/libexec/docker/cli-plugins/docker-compose
```

The advantages would be that it is obviously much easier to read, but also that different architectures are handled transparently and it is not necessary to install wget or curl in the build step if it is not already included in the base image. So I was looking for an equivalent image for `podman-remote` as it exists for `docker-compose` with `docker.io/docker/compose-bin`.

I thought that it was just an configuration issue that `quay.io/containers/podman-remote-artifacts` is not accessible, but apparently I was wrong. However, since it does not look like the image in its current (or past) form would help me as it only contained an x86_64 `podman-remote` binary, removing the documentation would be a valid solution for me to close this issue.

**Comment by Luap99** [comment]
@mheon 4.9.3 is missing release artefacts, please add them.

**Comment by mheon** [comment]
Done
