### ISSUE TITLE
Minimal resource usage for containerized GUI app

### ISSUE THREAD

**Issue by aarif1233456y-gmail** [containers/podman#21599]
### Discussed in https://github.com/containers/podman/discussions/21598

<div type='discussions-op-text'>

<sup>Originally posted by **aarif1233456y-gmail** February 10, 2024</sup>
#lots of people use containerization other than virtulization also because of resource usage reduction (like me). Esp who have low end pc

My problem description : 
i recently bought a refurburished very low end laptop that i could only afford (specs: 2gb ram, intel i3 (forgot the gen but it is not 10,11 or later)), i run windows 11 which takes up almost all the ram cpu and disk space

i basically wanted a virtual machine which i could spoof to identify as host machine as much as possible 
why ? because i have many highly/super advanced/expert ai protoctored exams/interviews etc

so i dont want my examiner/interviewer/protctor to detect o know anyhow i am using virtual machine either via network/user agent or any other way

then i wanted to use a simulated webcam and mic (obs studio) so that the virtual machine will detect that simulated cam and mic where either a pre-recorded video of me or my friend would be there , as the original internal cam and mic source 

then i can open their custom app or exam link in a lockdown browser (like in JEE Advanced) that they mailed me in the virtual machine in full screen and on my real host machine i can open browsers , apps etc without it detecting because it would be opened in myvirtual machine and i would be doing tasks in my real host machine

Multiple people i know use virtual machine for the same and i tried to but as my pc dont have enough resources i am unable to do so
I want to know the minimalistic way to achieve the above conditions using podman. Its not about using it for ill intent or cheating or promoting such practices but esp when others are doing it and if you dont then thats a major setback

Kindly help ASAP (already tried various other platforms and ai but still no help and it is starting from tomorrow :( 

this is all my attemps that were closest

but i couldnt get a gui for browser , neither perform anything

i would like to use the following browsers (priority-wise) : Microsoft edge , Mullvad/librrewolf , Brave 
for the exams

.

<img width="420" alt="Screenshot 2023-07-10 092555" src="https://github.com/containers/podman/assets/159604588/c99bda85-fdf7-4016-a1ba-f8afa59524da">

.

<img width="602" alt="Screenshot 2023-07-12 033901" src="https://github.com/containers/podman/assets/159604588/d4ee141d-0a81-4167-971c-d3d454ff1b2c">

.

<img width="939" alt="Screenshot 2023-07-12 032523" src="https://github.com/containers/podman/assets/159604588/c7c95eb9-3b28-4ee0-9cb8-8cd46f081bd9">

also refered to these :- 

[https://matrix.to/#/!SEjxdEhDPWoPxzjWCX:matrix.org/$9YPhECRE7uYssVS3Ki74D18ywpjRwzyPOs6-VXMBCS4?via=fedora.im&via=matrix.org&via=polarbear.army](url)

[https://matrix.to/#/!SEjxdEhDPWoPxzjWCX:matrix.org/$VZkd6FyCtp5NaCm0OFKc9IOlXeUznYN_M3rYEti7I2M?via=fedora.im&via=matrix.org&via=polarbear.army](url)

[https://matrix.to/#/!SEjxdEhDPWoPxzjWCX:matrix.org/$0WBnmX0MreVoqKMqb2Q6zTUm0YThz1tmFqe7s5oNvDk?via=fedora.im&via=matrix.org&via=polarbear.army](url)</div>

**Comment by giuseppe** [comment]
I am closing this one since it doesn't seem to be a Podman issue.

If anyone is interested in helping you, the discussion you've opened seems like the best place.
