### ISSUE TITLE
Error when pull image after set storage to ntfs folder

### ISSUE THREAD

**Issue by jianlins** [containers/podman#21610]
### Issue Description

The same pull image command works by default settings (podman pull nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04). However, if I configure the storage location to a mounted ntfs drive, it generate error: 
Error: writing blob: adding layer with blob "sha256:aece8493d3972efa43bfd4ee3cdba659c0f787f8f59c82fb3e48c87cbb22a12e": Error processing tar file(exit status 1): open /var/lib/dpkg/info/gcc-12-base:amd64.list: invalid argument

### Steps to reproduce the issue

Steps to reproduce the issue
1. mount an ntfs drive to ubuntu
2. set ~/.config/containers/storage.conf based on https://docs.oracle.com/en/operating-systems/oracle-linux/podman/podman-ConfiguringStorageforPodman.html#configuring-podman-storage. Change runroot and graphroot to folders on the ntfs drive.
3.podman pull nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

### Describe the results you received

stopped pulling at one of the blobs.

### Describe the results you expected

Pull all blobs successfully

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 16
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: smile-ThinkStation-P350-Tiny
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.5.0-17-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 54014734336
  memTotal: 67066167296
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 16776163328
  swapTotal: 16776163328
  uptime: 1h 5m 40.28s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/smile/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/smile/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /home/smile/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Wed Dec 31 17:00:00 1969
  GitCommit: ""
  GoVersion: go1.18.1
  OsArch: linux/amd64
  Version: 3.4.4

```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by giuseppe** [comment]
please run the following command and attach here the generated `strace.log` file:

`podman unshare strace -f -v -s 1000 -o strace.log podman pull nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04`

**Comment by bridgesense** [comment]
This is an issue with the rollout of 6.5.0-17-generic. The kernel breaks rootless containers. I had to drop back to 6.5.0-15 to get everything working again.

**Comment by giuseppe** [comment]
closing the issue, got no feedback after my last comment
