### ISSUE TITLE
`no valid disk artifact found` in main branch

### ISSUE THREAD

**Issue by tnk4on** [containers/podman#21648]
### Issue Description

I built the main branch under macOS.
I then ran `podman machine init` and got `no valid disk artifact found`.

### Steps to reproduce the issue

```
% git clone https://github.com/containers/podman.git
% cd podman
% git rev-parse HEAD
3d1f98e2f6c0f442bd13eeec4437cd3806695a9c
% make podman-remote
% ./bin/darwin/podman machine init
Error: no valid disk artifact found
```

Error occur in the following.
https://github.com/containers/podman/blob/3d1f98e2f6c0f442bd13eeec4437cd3806695a9c/pkg/machine/ocipull/source.go#L122-L124

debug results:
```
opts.os:  darwin
bar.ReadOnly.Platform.OS:  linux
```

### Describe the results you received

```
Error: no valid disk artifact found
```

### Describe the results you expected

```
Machine init complete
To start your machine run:

        podman machine start
```

### podman info output

```yaml
OS: darwin/arm64
provider: applehv
version: 5.0.0-dev
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

```
% sw_vers
ProductName:            macOS
ProductVersion:         14.3
BuildVersion:           23D56
```

**Comment by Luap99** [comment]
Machine is heavily under development at the moment so expect problems if you want to play around with it on main.
@baude PTAL

**Comment by tnk4on** [comment]
Fixed by https://github.com/containers/podman/pull/21657, close this.
