### ISSUE TITLE
Create network forcibly

### ISSUE THREAD

**Issue by xtexChooser** [containers/podman#21700]
### Feature request description

Currently, `podman run --replace` is able to replace exist containers.
I think it will be useful for `podman network create` (or even `pod create`) to have a `--replace` option, which overrides old network configurations.

### Suggest potential solution

Add a new network, add containers to the new network, then remove the old.

### Have you considered any alternatives?

```sh
podman network exists A && podman network rm -f A
podman network create A
# Connect containers back
```

**Comment by xtexChooser** [comment]
ops

**Comment by Luap99** [comment]
I rather not do it given that would imply to automatically delete attached containers which could be very unexpected for some users.

You also do not have to check for existing before calling network rm
`podman network rm -f NAME` will not return an error if NAME does not exists.
