### ISSUE TITLE
Changing podman runtime from 'runc' to 'crun'

### ISSUE THREAD

**Issue by krahimza** [containers/podman#21736]
Dear Community, 

I am running Podman version 4.6.1 and there is a HTML5 container running. The thing is, when I change the runtime in 'containers.conf' under '/usr/share/containers/' path, podman commands no longer work and I get the error below:

'Error: default OCI runtime "crun" not found: invalid argument'

![image](https://github.com/containers/podman/assets/160232069/ad1074cf-272b-4209-9e3b-05d225629244)

What could be the possible issue and how am I able to resolve this?

Best regards

**Comment by rhatdan** [comment]
Firrst you should change containers.conf in /etc/containers/containers.conf or in the users homedir for rootless mode.

The most logical reason this fails is that crun is not installed or the podman command can not find it.

Podman looks for crun in the following directories:

#  "/usr/bin/crun",
#  "/usr/sbin/crun",
#  "/usr/local/bin/crun",
#  "/usr/local/sbin/crun",
#  "/sbin/crun",
#  "/bin/crun",
#  "/run/current-system/sw/bin/crun",


If you are running on a Mac or Windows, then the crun must be present in one of those paths within the podman machine or the VM that you are ru nning the podman service in.

**Comment by rhatdan** [comment]
I have no idea.  @giuseppe WDYT?
