### ISSUE TITLE
Docker build or Podman build fails from Yocto and seen no issue when run manually

### ISSUE THREAD

**Issue by mohanigs** [containers/podman#21745]
### Bug description

Docker build or Podman build fails from Yocto and seen no issue when run manually. Below are the error logs.
Log data follows:
| DEBUG: Executing shell function do_compile
| Deleting any existing *tar.gz files
| Building img_ui from
| time="2024-02-13T08:51:23Z" level=error msg="invalid internal status, try resetting the pause process with \"/usr/bin/podman system migrate\": command required for rootless mode with multiple IDs: exec: \"newuidmap\": executable file not found in $PATH"
| WARNING: /home/build/tmp/work/corei7-64-poky-linux/ui-docker/1.0-r0/temp/run.do_compile.48173:156 exit 1 from 'docker build -t img_ui -f /home/build/tmp/work/corei7-64-poky-linux/ui-docker/1.0-r0/Dockerfile /home/build/tmp/work/corei7-64-poky-linux/ui-docker/1.0-r0'
| WARNING: Backtrace (BB generated script):
| 	containers/podman-desktop#1: do_compile, /home/build/tmp/work/corei7-64-poky-linux/ui-docker/1.0-r0/temp/run.do_compile.48173, line 156
| 	containers/podman-desktop#2: main, /home/build/tmp/work/corei7-64-poky-linux/ui-docker/1.0-r0/temp/run.do_compile.48173, line 172

So, I thought the issue is related to PATH and added below line in local.conf. Now I am observing below error.
PATH:append = ":/usr/bin"
Log data follows:
| DEBUG: Executing shell function do_compile
| Deleting any existing *tar.gz files
| Building img_ui from
| time="2024-02-13T08:54:43Z" level=error msg="running `/usr/bin/newuidmap 48505 0 1000 1 1 10000 65536`: newuidmap: write to uid_map failed: Operation not permitted\n"
| time="2024-02-13T08:54:43Z" level=error msg="invalid internal status, try resetting the pause process with \"/usr/bin/podman system migrate\": cannot set up namespace using \"/usr/bin/newuidmap\": exit status 1"
| WARNING: /home/build/tmp/work/corei7-64-poky-linux/ui-docker/1.0-r0/temp/run.do_compile.48488:156 exit 1 from 'docker build -t img_ui -f /home/build/tmp/work/corei7-64-poky-linux/ui-docker/1.0-r0/Dockerfile /home/build/tmp/work/corei7-64-poky-linux/ui-docker/1.0-r0'

uid_map file data when run manually:
![Screenshot from 2024-02-13 14-30-03](https://github.com/containers/podman-desktop/assets/6063876/35b6d9e4-8f0c-4c53-8552-c88eb8fdab30)
uid and gid data:
![uid_gid](https://github.com/containers/podman-desktop/assets/6063876/9b2b8a0d-f816-4b71-87ec-758cb3dafcf3)

uid_map file data from yocto:
       1000       1000          1

I have gone through below thread and tried ignore_chown_errors = "true" in your storage.conf file. Observed below error.
https://github.com/containers/podman/issues/15238

Log data follows:
| DEBUG: Executing shell function do_compile
| Deleting any existing *tar.gz files
| Building img_ui from
|       1000       1000          1
| time="2024-02-13T09:08:35Z" level=warning msg="Failed to decode the keys [\"storage.options.thinpool.ignore_chown_errors\"] from \"/etc/containers/storage.conf\""
| time="2024-02-13T09:08:35Z" level=error msg="running `/usr/bin/newuidmap 49612 0 1000 1 1 10000 65536`: newuidmap: write to uid_map failed: Operation not permitted\n"
| time="2024-02-13T09:08:35Z" level=error msg="invalid internal status, try resetting the pause process with \"/usr/bin/podman system migrate\": cannot set up namespace using \"/usr/bin/newuidmap\": exit status 1"
| WARNING: /home/build/tmp/work/corei7-64-poky-linux/ui-docker/1.0-r0/temp/run.do_compile.49595:157 exit 1 from 'docker build -t img_ui -f /home/build/tmp/work/corei7-64-poky-linux/ui-docker/1.0-r0/Dockerfile /home/build/tmp/work/corei7-64-poky-linux/ui-docker/1.0-r0'

### Operating system

NAME="Red Hat Enterprise Linux" VERSION="8.9 (Ootpa)"

### Installation Method

Other

### Version

1.7.0

### Steps to reproduce

Run podman build or docker build command from bitbake recipe on RHEL 8.9.
podman version 4.6.1

### Relevant log output

```shell
Log data follows:
| DEBUG: Executing shell function do_compile
| Deleting any existing *tar.gz files
| Building img_ui from
| time="2024-02-13T08:51:23Z" level=error msg="invalid internal status, try resetting the pause process with \"/usr/bin/podman system migrate\": command required for rootless mode with multiple IDs: exec: \"newuidmap\": executable file not found in $PATH"
| WARNING: /home/build/tmp/work/corei7-64-poky-linux/ui-docker/1.0-r0/temp/run.do_compile.48173:156 exit 1 from 'docker build -t img_ui -f /home/build/tmp/work/corei7-64-poky-linux/ui-docker/1.0-r0/Dockerfile /home/build/tmp/work/corei7-64-poky-linux/ui-docker/1.0-r0'
| WARNING: Backtrace (BB generated script):
| 	containers/podman-desktop#1: do_compile, /home/build/tmp/work/corei7-64-poky-linux/ui-docker/1.0-r0/temp/run.do_compile.48173, line 156
| 	containers/podman-desktop#2: main, /home/build/tmp/work/corei7-64-poky-linux/ui-docker/1.0-r0/temp/run.do_compile.48173, line 172

So, I thought the issue is related to PATH and added below line in local.conf. Now I am observing below error.
Log data follows:
| DEBUG: Executing shell function do_compile
| Deleting any existing *tar.gz files
| Building img_ui from
| time="2024-02-13T08:54:43Z" level=error msg="running `/usr/bin/newuidmap 48505 0 1000 1 1 10000 65536`: newuidmap: write to uid_map failed: Operation not permitted\n"
| time="2024-02-13T08:54:43Z" level=error msg="invalid internal status, try resetting the pause process with \"/usr/bin/podman system migrate\": cannot set up namespace using \"/usr/bin/newuidmap\": exit status 1"
| WARNING: /home/build/tmp/work/corei7-64-poky-linux/ui-docker/1.0-r0/temp/run.do_compile.48488:156 exit 1 from 'docker build -t img_ui -f /home/build/tmp/work/corei7-64-poky-linux/ui-docker/1.0-r0/Dockerfile /home/build/tmp/work/corei7-64-poky-linux/ui-docker/1.0-r0'
```

**Comment by giuseppe** [comment]
> I see /usr/bin/newuidmap is owned by user nobody instead of root while running yocto bitbake recipe. is this causing issue ? Anyway to change user from nobody to root in yocto environment.?

yes that can be an issue, it means yocto itself is running inside a user namespace.

To confirm it, please share the output of `cat /proc/self/uid_map` from Yocto

**Comment by mohanigs** [comment]
> > I see /usr/bin/newuidmap is owned by user nobody instead of root while running yocto bitbake recipe. is this causing issue ? Anyway to change user from nobody to root in yocto environment.?
> 
> yes that can be an issue, it means yocto itself is running inside a user namespace.
> 
> To confirm it, please share the output of `cat /proc/self/uid_map` from Yocto
![image](https://github.com/containers/podman/assets/6063876/58e02646-5d95-4f72-80cd-493b8c338f8f)

**Comment by giuseppe** [comment]
there is a single UID mapped inside Yocto (e.g. the same environment you can get with `unshare -r`), so Podman cannot create its user namespace in that restricted environment

**Comment by mohanigs** [comment]
> there is a single UID mapped inside Yocto (e.g. the same environment you can get with `unshare -r`), so Podman cannot create its user namespace in that restricted environment

Is there a way to fix the issue inside yocto?

**Comment by giuseppe** [comment]
how do you get into that environment?  Do you run a specific command?

If so, can you try running the same command from a `podman unshare` session (or alternatively run as root)?
