### ISSUE TITLE
Why is podman compose not available on non x86_64 & non arm?

### ISSUE THREAD

**Issue by dcermak** [containers/podman#21757]
`podman compose` is excluded via build tags from building on anything but arm64 & x86_64. Is there a particular reason for that? 

https://github.com/containers/podman/blob/c9b61b08c666482113ca787368b08943f69ff108/cmd/podman/compose.go#L1

**Comment by vrothberg** [comment]
Thanks for reaching out!  I think that's probably a copy-paste error that happened when creating the file.

**Comment by vrothberg** [comment]
Opened https://github.com/containers/podman/pull/21758
