### ISSUE TITLE
v5.0.0-rc2 MacOS pkg has wrong arch

### ISSUE THREAD

**Issue by camporter** [containers/podman#21769]
### Issue Description

Downloaded the amd64 version of v5.0.0-rc2 from github releases (`https://github.com/containers/podman/releases/download/v5.0.0-rc2/podman-installer-macos-amd64.pkg`). The installed binary is not for amd64, but for arm64.

```
~ podman
zsh: bad CPU type in executable: podman
~ which podman
/opt/podman/bin/podman
~ file /opt/podman/bin/podman
/opt/podman/bin/podman: Mach-O 64-bit executable arm64
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. `wget https://github.com/containers/podman/releases/download/v5.0.0-rc2/podman-installer-macos-amd64.pkg`
2. `sudo installer -pkg podman-installer-macos-amd64.pkg -target /`
3. `podman`

### Describe the results you received

Incorrect arch for the binary package in the prerelease version.

### Describe the results you expected

An amd64 binary instead.

### podman info output

```yaml
Cannot run.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

MacOS Monterey

**Comment by rhatdan** [comment]
@mheon @lsm5 PTAL

**Comment by Luap99** [comment]
@ashley-cui @baude PTAL It is also broken in rc3 (https://github.com/containers/podman/issues/21902)

**Comment by ashley-cui** [comment]
Looking..

**Comment by ashley-cui** [comment]
Closed via https://github.com/containers/podman/pull/21978
