### ISSUE TITLE
CI RFE: logformatter for macos/windows machine tests

### ISSUE THREAD

**Issue by Luap99** [containers/podman#21760]
The logformatter is really helpful to quickly see the relevant errors in the test logs. Every time I look at the windows/macos machine CI failures I need much longer to find the problem.
I know logformatter is written in perl so it should be possible to run that on macos and windows (although it might need to be installed first). I am not sure if there are more requirements for it to get it to work but I think it would be really helpful to have it on these tests (also in regards to flake tracking)

cc @edsantiago

**Comment by edsantiago** [comment]
Mac is now running logformatter, although incompletely: #21871

Windows: this is what I tried:
```diff
--- a/contrib/cirrus/win-podman-machine-test.ps1
+++ b/contrib/cirrus/win-podman-machine-test.ps1
@@ -34,4 +34,4 @@ New-Item -ItemType "directory" -Path "$env:AppData\containers"
 Copy-Item -Path pkg\machine\ocipull\policy.json -Destination "$env:AppData\containers"
 
 Write-Host "`nRunning podman-machine e2e tests"
-Run-Command ".\winmake localmachine"
+Run-Command ".\winmake localmachine" | Run-Command ".\contrib\cirrus\logformatter $Env:TEST_FLAVOR-podman-windows-rootless-host-sqlite"
```
This is the [result](https://cirrus-ci.com/task/6414310885294080?logs=main#L76):
```
Building Ginkgo
go build -o build/ginkgo.exe ./vendor/github.com/onsi/ginkgo/v2/ginkgo
./test/tools/build/ginkgo.exe -vv  --tags "remote exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper containers_image_openpgp" -timeout=90m --trace --no-color  pkg/machine/e2e/. 
.\contrib\cirrus\logformatter machine-wsl-podman-windows-rootless-host-sqlite
```
That is: nothing. No output. Not even any error messages. No clues to go on. (`logformatter` acts as a filter. It should pass stdin directly to stdout, untouched. The formatted output goes to a file, not stdout).

Sorry, this is not something I can fix.

**Comment by Luap99** [comment]
I have no idea what `Run-Command` is or does, I cannot find any docs online about it. It has been a long time since I used powershell but what I remeber is that you can just exec commands directly just like on a normal posix shell so I have no diea what this is used for. So yeah I have no idea about this stuff either.

**Comment by edsantiago** [comment]
`Run-Command` is internal https://github.com/containers/podman/blob/690b671ecdb26e1451175f9fc887dfea8181e289/contrib/cirrus/win-lib.ps1#L62-L76

I tried this too:
```
Run-Command ".\winmake localmachine" | Run-Command "perl .\contrib\cirrus\logformatter $Env:TEST_FLAVOR-podman-windows-rootless-host-sqlite"
```
(adding "perl"). Result:
```
powershell.exe : Invoke-Expression : The term 'perl' is 
not recognized as 
At line:1 char:5
```
Next thing to try:
```
Run-Command ".\winmake localmachine | .\contrib\cirrus\logformatter $Env:TEST_FLAVOR-podman-windows-rootless-host-sqlite"
```

**Comment by Luap99** [comment]
Well I think perl is not installed on windows by default so unless we include it somehow already I think that would be the first blocker. Windows likely also has no idea about the perl shebang so I would assume perl .\contrib\cirrus\logformatter would be the correct way to go.

**Comment by edsantiago** [comment]
Pipe in the middle of the string [fails](https://cirrus-ci.com/task/5195198796398592?logs=main#L77):
```
powershell.exe : Invoke-Expression : Cannot run a document 
in the middle of 
```
That was my last attempt. This will need to be solved by a Windows expert.

**Comment by Luap99** [comment]
yeah understandable, I didn't expect windows to be easy.
I am already happy to have at least macos :)

**Comment by edsantiago** [comment]
@l0rd in case you didn't get my response on Slack, this is the issue I brought up in standup today

**Comment by l0rd** [comment]
@n1hility yes. Thank you for those info, that's useful. @edsantiago what's the best way to test a cirrus task locally? There are a lot of env variables that should be setup. I can try and fail and set them all but is there another way to do that?

**Comment by n1hility** [comment]
@l0rd my recommendation would be to run winmake with the formatting script locally first (assuming you have a windows box handy)  and get the basics functioning (it produces output etc). After you get that working you can create a draft PR  to iterate on rapidly where you hack up cirrus.yml to just run the tasks you need, basically the cross build and the win task. You can hack it up even more by replacing the repo URL with a static link to a past job run and skip everything but the sole windows task  and the env vars

**Comment by l0rd** [comment]
@n1hility ah ah using a static link is very clever. Will try that thanks.

@edsantiago interesting. At least that is useful for me as it provides some information on the images and how they are setup. I was not looking for something that worked on windows specifically but something that I could run locally (linux or mac are fine) and to use an example for windows and avoid abusing the CI for testing. But @n1hility recommendation is a great idea.

**Comment by l0rd** [comment]
https://github.com/containers/podman/pull/21991 is ready for review.

The example formatted log of the [machine hyperv podman windows task](https://api.cirrus-ci.com/v1/artifact/task/4606291419594752/html/repo/machine-hyperv-podman-windows-rootless-host-sqlite.log.html).

**Comment by l0rd** [comment]
I am closing this issue as `logformatter` is invoked on windows machine tests as well.
