### ISSUE TITLE
Data corruption on "down" with podman kube play

### ISSUE THREAD

**Issue by joelpurra** [containers/podman#21767]
### Issue Description

When shutting down a "kube" using `podman kube down something.yaml` the containers in the pod does not receive `SIGTERM` and a grace period -- only `SIGKILL`. Containerized processes are instantly killed and have no chance to perform a graceful, clean shutdown.

This issue has been reported earlier by @alecello (#19135). As was mentioned then, this issue affects `podman kube down` and therefore also `[Kube]` (`*.kube`) quadlets. The issue was closed, but only partially resolved with a fix for kube container exit code propagation (#18671).

My use-case includes databases and database indexing, migrated to quadlets after running for years on Kubernetes. Graceful shutdowns with `SIGTERM` are important. Data _corruption_ has been detected more than once, but has fortunately been recoverable so far. No data _loss_ detected yet.

One workaround is to run `podman pod stop something` *before* `podman kube down something.yaml`. This also works for quadlet services, by adding `[Service]` `ExecStop=podman pod stop something` to the unit. Verified to work on the system where the issue was found.

See below for sample files, manual step-by-step test cases, plus workarounds. Test cases have turned off kube and quadlet service restarts, as they may otherwise interfere with results.

### Steps to reproduce the issue

1. Create a Kubernetes YAML file for software which expects a `SIGTERM` signal for a graceful shutdown.
1. Play the YAML file: `podman kube play software.yaml`
1. Down the YAML file: `podman kube down software.yaml`

Additionally, create/start/stop a `[Kube]` quadlet for the same YAML file and investigate the systemd service status. The result should be the same.

### Describe the results you received

1. The containerized process is unexpectedly killed by `SIGKILL`.
1. The process is not given the chance to perform a graceful shutdown.
1. Traces of an abrupt, unclean shutdown are found:
   - Logs found to be incomplete, cut off in the middle of data processing.
   - Process lock files found on disk (persistent volume).
   - Data on disk (persistent volume) found to be corrupted.
   - External service orchestrators were not notified of the service shutdown.

### Describe the results you expected

1. The containerized process receives `SIGTERM`.
1. The process is given time to perform a graceful shutdown.
1. The process stops after performing any cleanup steps.
1. Evidence of a graceful shutdown:
   - Shutdown logs are complete.
   - Lock files cleaned up.
   - Data on disk not corrupted.
   - External service orchestrators schedule jobs elsewhere.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.33.5
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2:2.1.10-0ubuntu23.10+obs18.1_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: '
  cpuUtilization:
    idlePercent: 44.56
    systemPercent: 0.63
    userPercent: 54.82
  cpus: 32
  databaseBackend: sqlite
  distribution:
    codename: mantic
    distribution: ubuntu
    version: "23.10"
  eventLogger: journald
  freeLocks: 2047
  hostname: compendious
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.5.0-17-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 42109521920
  memTotal: 67248631808
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns_1.10.0-0ubuntu23.10+obs38.1_amd64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.10.0
    package: netavark_1.10.3-0ubuntu23.10+obs36.1_amd64
    path: /usr/libexec/podman/netavark
    version: netavark 1.10.3
  ociRuntime:
    name: crun
    package: crun_101:1.14.3-0ubuntu23.10+obs69.1_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.14.3
      commit: 1961d211ba98f532ea52d2e80f4c20359f241a98
      rundir: /run/user/1234/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: true
    path: /run/user/1234/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.2.3-0ubuntu23.10+obs13.1_amd64
    version: |-
      slirp4netns version 1.2.3
      commit: c22fde291bb35b354e6ca44d13be181c76a0a432
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.4
  swapFree: 0
  swapTotal: 0
  uptime: 10h 27m 8.00s (Approximately 0.42 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/username/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /mnt/some-bigger-disk/containers/storage
  graphRootAllocated: 104840822784
  graphRootUsed: 59208216576
  graphStatus:
    Build Version: Btrfs v6.3.2
    Library Version: "102"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 12
  runRoot: /run/user/1234/containers
  transientStore: false
  volumePath: /mnt/some-bigger-disk/containers/storage/volumes
version:
  APIVersion: 4.9.2
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.21.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.9.2
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Using [OBS builds](https://build.opensuse.org/project/show/devel:kubic:libcontainers:unstable).

## Tests cases

Tests are used to show step-by-step which execution abstraction layers perform a clean shutdown, and which do not. Tests use the faked long-running service `strace sleep 1h` (simplified), which does nothing but output logs for each signal received and caught. Note that `SIGKILL` cannot be caught, and thus requires paying attention to the _lack_ of log output.

Layers covered are:

- `strace sleep` directly on the host.
- Container in the foreground.
- (Detached) container in a pod.
- Kube.
- Kube Quadlet.

The last two do not shut down cleanly and need a workaround, which is also tested.

### Test files

For quadlet tests, put files in `~/.config/containers/systemd/strace-sleep/`.

```text
.
├── strace-sleep
│   └── Containerfile
├── strace-sleep.kube
└── strace-sleep.yaml
```

**Containerfile**

<details>

- Uses [`tini`](https://github.com/krallin/tini) as `ENTRYPOINT` (PID 1) to ensure signals are handled and zombie processes reaped.
- Uses [`strace`](https://github.com/strace/strace) (in a subprocess) to log signals, primarily `SIGTERM`.
- Uses `sleep 1h` to simulate a long-running service. A fuller test would also write data to disk, sleep after `SIGTERM`, etcetera.

</details>

```dockerfile
FROM docker.io/library/alpine:3

RUN apk add --no-cache tini
ENTRYPOINT ["/sbin/tini", "--"]

RUN apk add --no-cache strace
CMD ["strace", "--daemonize", "--trace", "!all", "sleep", "1h"]
```

**strace-sleep.yaml**

<details>

- Prevents container restarts for testing purposes, and also so quadlet/systemd can manage restarts externally.
- Running `podman kube play` automatically builds and tags `./strace-sleep/Containerfile`.

</details>

```yaml
---
apiVersion: apps/v1
kind: Pod
metadata:
  name: strace-sleep
spec:
  restartPolicy: Never
  containers:
    - image: strace-sleep
      name: strace-sleep
```

**strace-sleep.kube**

<details>

- Prevents systemd service restarts for testing purposes.
- Quadlet sets the unit working directory to allow container auto-building.
- Uncomment `ExecStop=` for a `[Kube]` quadlet `SIGTERM` workaround.

</details>

```ini
[Service]
Restart=no
#ExecStop=podman pod stop strace-sleep

[Kube]
SetWorkingDirectory=yaml
Yaml=./strace-sleep.yaml
```

### Test status

```shell
# Verify that the container/pod is up and running.
podman container ps --pod --watch 1

# Inspect the container process PIDs. PID 1=tini, PID 2=sleep, strace on a higher PID.
podman container exec strace-sleep ps -Af

# Filter container/pod logs by identifier(s).
journalctl --user --follow --identifier 'strace-sleep' --identifier 'strace-sleep-strace-sleep'

# View quadlet status.
systemctl --user status strace-sleep.service
```

### Test signals

To emulate Podman's termination signal, send `SIGTERM` to PID 1 (`tini`) in the container and inspect the logs. Other useful test signals are `SIGINT` (emulate <kbd>Ctrl</kbd>+<kbd>C</kbd>), `SIGCONT`/`SIGURG` (no effect, only for logging), and `SIGKILL` (instagib). 

It is also possible to send messages directly to `sleep`, bypassing `tini`. The signals should still get logged by `strace`, and work as intended.

```shell
# Send a signal to tini in the container.
podman container exec strace-sleep kill -s SIGTERM 1

# Send a signal directly to all "sleep 1h" processes. Should work in all test cases.
pkill --signal SIGTERM --exact --full 'sleep 1h'

# Repeat the "urgent" signal to all "sleep 1h" processes every 10 seconds. Works across all test cases, but may clutter the logs.
( while : ; do pkill --signal SIGURG --exact --full 'sleep 1h' ; sleep 10 ; done ; )
```

### Manual test case steps

First create the test files (above).

1. Execute lines one-by-one in a terminal.
1. Inspect the terminal and `journalctl` log for `strace` output.
1. Make sure the test service has stopped before moving to the next test case.

(Optional.) Start the `SIGURG` signal loop (above) to see some additional signal logs.

```shell
# 1. Test directly on the host.
# ✅ Ctrl+C does send SIGINT to sleep.
strace --daemonize --trace '!all' sleep 1h ; echo "$?"

# Build the image used in containerized tests.
podman image build --tag strace-sleep ./strace-sleep

# 2. Standalone container in the foreground. (Try resizing the terminal window.)
# ✅ Ctrl+C does send SIGINT to tini.
podman container run --rm --name strace-sleep strace-sleep ; echo "$?"

# 3. Standalone detached container.
podman container run --rm --name strace-sleep --detach strace-sleep
# ✅ Stopping the container does send SIGTERM.
podman container stop strace-sleep

# 4. Pod with detached container.
podman pod create --name strace-sleep
podman container run --detach --pod strace-sleep --name strace-sleep strace-sleep
# ✅ Stopping the pod does send SIGTERM.
podman pod stop strace-sleep
podman pod rm strace-sleep

# 5. Kube-managed pod.
podman kube play strace-sleep.yaml
# ❌ Downing the kube *not* send SIGTERM. Process unexpectedly dies. There is no strace log.
podman kube down strace-sleep.yaml

# 6. Kube-managed pod, with workaround.
podman kube play strace-sleep.yaml
# ✅ Stopping the kube's pod send SIGTERM.
podman pod stop strace-sleep
# Use down to remove the stale kube.
podman kube down strace-sleep.yaml

# Regenerate quadlet systemd services; optionally view the generated unit file.
systemctl --user daemon-reload
cat ${XDG_RUNTIME_DIR}/systemd/generator/strace-sleep.service

# 7. Quadlet kube service.
systemctl --user start strace-sleep.service
# ❌ By default, stopping the service does *not* send SIGTERM. Process unexpectedly dies. There is no strace log.
systemctl --user stop strace-sleep.service

# 8. Quadlet kube service, with workaround.
# Now uncomment ExecStop= in strace-sleep.kube and reload units.
systemctl --user daemon-reload
systemctl --user start strace-sleep.service
# ✅ Custom ExecStop command does send SIGTERM. Kube is automatically removed.
systemctl --user stop strace-sleep.service
```

### Test cleanup

If `strace-sleep.kube` is left in `~/.config/containers/systemd/strace-sleep/` quadlet will keep regenerating the systemd service. It will show up among other user units, but does not have an `[Install]` section and should not autostart. Consider deleting the test file directory.

**Comment by sbancal** [comment]
Issue well detailed, well done!

We've run into exactly the same problem with services that are deployed using Ansible's _fedora.linux_system_roles.podman_.
In our case, this resulted in nightly data loss (scheduled pipeline) as the service never received a `SIGTERM`.

Our workaround was the same as described above: adding `ExecStop=/usr/bin/podman stop CONTAINER_NAME` to the `*.kube` files.

We look forward to seeing how this subject is addressed here.

**Comment by Luap99** [comment]
That was fixed in https://github.com/containers/podman/pull/22398
