### ISSUE TITLE
[tracker][low pri] e2e: kube play expose char device: Error descending into path /dev/foodevXXXX: ENOENT

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#21782]
LOW PRIORITY. This is almost certainly a bug in the test itself. Does not merit any attention during the crunch. I just need to track this for myself.

Two in the past month:
```
Podman kube play
  [It] expose character device inside container
  ...
  # podman [options] inspect --format {{.HostConfig.Devices}} testPod-testCtr
  time="2024-01-17T14:49:07-06:00" level=warning msg="Error descending into path /dev/foodevdb450935b579: open /dev/foodevdb450935b579: no such file or directory"
  [{/dev/foodevda7ade5db579/chardevice /dev/foodevda7ade5db579/chardevice }]

  [FAILED] Unexpected warnings seen on stderr: "....."
```

* fedora-39 : int podman fedora-39 root host sqlite
    * [02-21 16:02](https://api.cirrus-ci.com/v1/artifact/task/5920365436731392/html/int-podman-fedora-39-root-host-sqlite.log.html#t--Podman-kube-play-expose-character-device-inside-container--1)
* rawhide : int podman rawhide root host sqlite
    * [01-17-2024 16:12](https://api.cirrus-ci.com/v1/artifact/task/4612826094895104/html/int-podman-rawhide-root-host-sqlite.log.html#t--Podman-kube-play-expose-character-device-inside-container--1)

| x | x | x | x | x | x |
| ---: | ---: | ---: | ---: | ---: | ---: |
| int(2) | podman(2) | rawhide(1) | root(2) | host(2) | sqlite(2) |
|  |  | fedora-39(1) |  |  |  |

**Comment by Luap99** [comment]
I think the bug is in the code: https://github.com/containers/podman/pull/22252
