### ISSUE TITLE
API documentation error

### ISSUE THREAD

**Issue by rodolfocerezo** [containers/podman#21800]
I'm trying to view the latest documentation of the API (https://docs.podman.io/en/latest/_static/api.html) but I'm getting this error:

```

Something went wrong...

Load failed
Stack trace
u@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:8:75662
@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:8:76788
s@https://cdn.jsdelivr.net/npm/redoc@next/bundles/redoc.standalone.js:8:74783

ReDoc Version: 2.0.0-rc.75
Commit: d7440fb
```

Sorry if this is the wrong place to report this issue

**Comment by Luap99** [comment]
The site load fine for me, does it still not load for you? Maybe it was some temporary outage.
