### ISSUE TITLE
Add support for pod requirements

### ISSUE THREAD

**Issue by Doomsdayrs** [containers/podman#21815]
### Feature request description

`podman` supports creating containers with [requirements](https://docs.podman.io/en/latest/markdown/podman-create.1.html#requires-container)

### Suggest potential solution

Add a `Requires=` configuration to `.container` to create dependency trees.

This would also manipulate systemd `requires` with connections to other podman files.

This would also mean that before shutdown, the other containers must be stopped too.

### Have you considered any alternatives?

No.

**Comment by Luap99** [comment]
If quadlet is used I suggest you only use the dependency options, such as `Requires=`, that already part of the systemd unit section.

If we would also add --requires to the podman command that just adds double the dependency logic for no gain AFAICT.

**Comment by Doomsdayrs** [comment]
> If quadlet is used I suggest you only use the dependency options, such as `Requires=`, that already part of the systemd unit section.
> 
> If we would also add --requires to the podman command that just adds double the dependency logic for no gain AFAICT.

The problem is that it kills my system when I do that.

I tried doing a `Requires` via systemd on another container, and I had a server not booting.

**Comment by Luap99** [comment]
Then you investigate why because systemd dependency management is pretty common and shouldn't result in a non booting server
