### ISSUE TITLE
universal pkg installer

### ISSUE THREAD

**Issue by benoitf** [containers/podman#21829]
### Feature request description

some people are downloading the wrong .pkg installer due to podman.io redirecting to amd64 installer as it's hard to know which arch is operated from a browser.

Then, they're unable to start a podman machine as it's trying to run the wrong qemu binary as the arch is not the same

So if the recommended pkg from the website would be the universal .pkg it would solve many problems

### Suggest potential solution

there is a [podman-installer-macos-amd64.pkg](https://github.com/containers/podman/releases/download/v4.9.3/podman-installer-macos-amd64.pkg) and a [podman-installer-macos-arm64.pkg](https://github.com/containers/podman/releases/download/v4.9.3/podman-installer-macos-arm64.pkg)

probably there should be a -universal.pkg

That would also help Podman Desktop that will embed the universal pkg in its universal distribution

**Comment by rhatdan** [comment]
@mheon PTAL

**Comment by benoitf** [comment]
for reference, the https://podman.io issue : https://github.com/containers/podman.io/issues/275

**Comment by ashley-cui** [comment]
I'd agree this is a good idea and looks possible but prob needs some time to read the mac packaging docs.

**Comment by cfergeau** [comment]
Fwiw, universal binaries can be generated cross-platform using https://github.com/randall77/makefat (we are using it in `crc`).

**Comment by ashley-cui** [comment]
Closed via https://github.com/containers/podman/pull/21978
