### ISSUE TITLE
machine-linux: unable to load machine config file: "unexpected end of JSON input"

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#21849]
Pretty sure I heard this one mentioned in scrum today, but there's no issue filed, so here's your tracker.
```
podman machine list
  list machine: check if running while starting
  ...
           podman-remote machine start 601893886e6c
           podman-remote machine list --format {{.LastUp}}
           Starting machine "601893886e6c"
           Error: unable to load machine config file: "unexpected end of JSON input"
```
* fedora-39 : machine-linux podman fedora-39 rootless host sqlite
  * PR #21838
    * [02-27 07:05](https://api.cirrus-ci.com/v1/artifact/task/4595165407477760/html/machine-linux-podman-fedora-39-rootless-host-sqlite.log.html) in machine-linux podman fedora-39 rootless host sqlite: unknown failure
  * PR #21763
    * [02-20 11:40](https://api.cirrus-ci.com/v1/artifact/task/4646925283098624/html/machine-linux-podman-fedora-39-rootless-host-sqlite.log.html) in machine-linux podman fedora-39 rootless host sqlite: unknown failure
  * PR #21684
    * [02-18 11:22](https://api.cirrus-ci.com/v1/artifact/task/5120513140326400/html/machine-linux-podman-fedora-39-rootless-host-sqlite.log.html) in machine-linux podman fedora-39 rootless host sqlite: unknown failure

**Comment by vrothberg** [comment]
Looking at the code I _suspect_ that `loadMachineFromFQPath()` loads the file while being written to.  `func (mc *MachineConfig) write()` is not atomic.

The writing could be made atomic or loading needs to hold the lock.  Maybe both to be extra sure?
