### ISSUE TITLE
machine-mac: unable to clean up gvproxy: checking if process running: input/output error

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#21845]
I don't think this is the same one being discussed in Slack right now, but please close if it is.
```
/Users/MacM1-1-worker/ci/task-4908461394231296/bin/darwin/podman machine reset --force
Error: 1 error occurred:
	* unable to clean up gvproxy: checking if process running: input/output error
```
Four instances, all of them in the last 24 hours.

* darwin : machine-mac podman darwin rootless host sqlite
  * PR #21834
    * [02-27 07:23](https://api.cirrus-ci.com/v1/task/4908461394231296/logs/test.log) in machine-mac podman darwin rootless host sqlite: unknown failure in test
  * PR #21825
    * [02-27 08:39](https://api.cirrus-ci.com/v1/task/4636973776764928/logs/test.log) in machine-mac podman darwin rootless host sqlite: unknown failure in test
  * PR #21753
    * [02-26 11:56](https://api.cirrus-ci.com/v1/task/6442520901582848/logs/test.log) in machine-mac podman darwin rootless host sqlite: unknown failure in test
  * PR #21594
    * [02-26 13:57](https://api.cirrus-ci.com/v1/task/5805301182496768/logs/test.log) in machine-mac podman darwin rootless host sqlite: unknown failure in test

**Comment by baude** [comment]
is this a flake that fails a test ?

**Comment by baude** [comment]
it looks like remove does it too; and yes, it is a flake; i will try to look next time im on my mac

**Comment by edsantiago** [comment]
I would assume that it causes a CI failure, since by definition that's what my flake-logger logs. [Confirmation](https://cirrus-ci.com/task/5660819405406208). (Wow, it is so hard to work with non-logformatted logs....)

**Comment by baude** [comment]
@edsantiago are you still seeing this error?

**Comment by edsantiago** [comment]
The last one in my logs was on 02-27, shortly after I filed this issue.

**Comment by baude** [comment]
ok, i was asking because #21778 had a potential fix for this.

**Comment by edsantiago** [comment]
CI load has been super low the last few days, but I've seen no `darwin` flakes. If you're confident that #21778 fixed the gvproxy issue, feel free to close this: one less dangling sword to track. Ah what the heck, I'll close it myself.
