### ISSUE TITLE
podman system reset speedup: Imply --time 0 or provide option for it

### ISSUE THREAD

**Issue by martinpitt** [containers/podman#21874]
### Feature request description

I'm currently [trying to clean up cockpit-podman's test setup/cleanup](https://github.com/cockpit-project/cockpit-podman/issues/1591), after a quick [inquiry](https://github.com/containers/podman/pull/21592#issuecomment-1968282971). In some ideal world, calling `podman system reset --force` would clean up *everything*. It doesn't yet, but I'd like to gradually get rid of our extra hacks.

An easy one is to make it faster:

```
podman run -d docker.io/busybox sleep infinity
time podman system reset --force
```

shows:
```
WARN[0010] StopSignal SIGTERM failed to stop container lucid_jones in 10 seconds, resorting to SIGKILL 

real	0m10.324s
user	0m0.134s
sys	0m0.152s
```

This is annoying for many tests, as it quickly piles up, is often slower than the actual test, and completely unnecessary.

### Suggest potential solution

Given the hammer size and intent of `system reset`, it'd would make sense to me if it didn't bother with the 10s timeout, and just immediately kill everything.

Alternatively, it could grow a `--time 0` option like `podman rm` has.

### Have you considered any alternatives?

We currently do an extra `podman rm --force --time 0 --all; podman pod rm --force --time 0 --all` (conditionalized, as e.g. Ubuntu 22.04's podman doesn't yet understand the `--time` option). This works, but it's one more step to keep track of.

### Additional context

This is on current Fedora 40: podman-5.0.0~rc1-3.fc40.x86_64

**Comment by Luap99** [comment]
For system reset it should just default to 0 IMO, the data is gone anyway after that so no reason to wait for a graceful container shut-down.

Anyhow you can run `podman stop --all -t0` even on older ubuntu versions to work around that for now.

**Comment by baude** [comment]
@martinpitt thanks for the nicely dont report.

**Comment by martinpitt** [comment]
Wow, thanks @baude for the fast fix!
