### ISSUE TITLE
podman use `ubuntu:jammy` image run `test -x` command

### ISSUE THREAD

**Issue by Liripo** [containers/podman#21898]
### Issue Description

podman use `ubuntu:jammy` image run `test -x` command, it don't work. 

### Steps to reproduce the issue

when I use docker use `ubuntu:jammy` image run `test -x` command, it can work well.
![image](https://github.com/containers/podman/assets/54770415/77f53925-5150-474e-ab09-47e474e21d3a)
but use podman,it don't work.

My podman version `2.2.1`.

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
Podman v2.2.1 is extremely outdated and not supported by us, I suggest you try this on something much newer (i.e. v4.9).
And please provide all the requested details if you file a bug.
