### ISSUE TITLE
Pull images automatically in podman-volume-create when missing

### ISSUE THREAD

**Issue by xtexChooser** [containers/podman#21919]
### Feature request description

When using `--mount=type=image` or `podman volume create --driver image` and the given image is missing, it will not be pulled and will cause "image not known" error.

**Comment by rhatdan** [comment]
Seems like a lot of complexity for something that could easily be worked around.

podman pull --pull=ifmissing IMAGE

The issue with pulling would require us to add all of the options specified in the podman pull command into whatever command pulls the image.  I am not sure this is a good idea from a support point of view.  Currently we only do this for situations where we are running containers.
