### ISSUE TITLE
Podman macine init fails on MacOS 14.2.1

### ISSUE THREAD

**Issue by ahrynkie** [containers/podman#21922]
### Issue Description

I downloaded podman (4.9.2) CLI for OSX (Sonoma 14.2.1) and followed the commands to initialise a new machine (podman machine init and start). The second command resulted in an Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Unknown Error' error. I am running podman on an Apple MacBook Pro M2 Max processor.

### Steps to reproduce the issue

Steps to reproduce the issue
1.podman machine init
2.podman machine start
3.

### Describe the results you received

I received the following error:
Error: qemu exited unexpectedly with exit code -1, stderr: qemu-system-x86_64: Unknown Error

### Describe the results you expected

No idea.

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
podman v4.9.2
macOS 14.2.1
Apple MacBook Pro M2 Max
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by baude** [comment]
usually when this happens it is because brew was installed for x86 at one point and its pulling the wrong qemu arch.  you didnt say how you got the helper binaries, like gvproxy and qemu, so i am guessing here.

**Comment by ahrynkie** [comment]
I don't think this has anything to do with homebrew.
It's a fairly my MacBook pro with very little third party software installed.

**Comment by baude** [comment]
your issue description specifically calls out that podman cannot find the an x86_64 version of qemu but you also cite you have apple silicon.  one way or another you have a wrong binary somewhere; and that depends on how you installed podman and its dependencies.  is it possible you downloaded the wrong podman binary?

**Comment by ahrynkie** [comment]
I downloaded the link (podman CLI for macOS - CLI only installer for intel Macs).
Yes, that is the problem. I have an Apple processor and not an Intel one.
Thank you for helping me diagnose the issue.

**Comment by arixmkii** [comment]
There is a feature request to provide universal packages https://github.com/containers/podman/issues/21829
