### ISSUE TITLE
build_osx.md is out of date

### ISSUE THREAD

**Issue by cgwalters** [containers/podman#21926]
### Issue Description

It seems like for podman5 we take a dependency on fetching a disk image from a registry, and this requires us to have at least `containers.conf` installed.

https://github.com/containers/podman/pull/21862 is relevant but earlier PRs are too.

Can someone who knows this please update the `build_osx.md` with what steps need to be done here?

### Steps to reproduce the issue

Try to use `build_osx.md`

### Describe the results you received

```
> podman machine init --now --rootful -m 8192
Error: failed to pull quay.io/baude/stage-podman-machine-image@sha256:a1214cf6fccc9f8de03af65c6b65439d022e3a4c1ff8d161ed606921449dd871: no DefaultPolicyJSONPath defined and no local overwrites found: ["stat /Users/walters/.config/containers/policy.json: no such file or directory" "stat /etc/containers/policy.json: no such file or directory"]
```

### Describe the results you expected

Functioning podman-machine

### podman info output

```yaml
$ podman --version
podman version 5.0.0-dev
$ git rev-parse HEAD
413819de0747b74219ec68f5a61e241886d10387
$
```
```


### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

_No response_

**Comment by Luap99** [comment]
see also https://github.com/containers/podman/issues/21855

**Comment by cgwalters** [comment]
Thanks; teah this is basically a duplicate..
