### ISSUE TITLE
minikube flakes

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#21931]
No useful diagnostics:
```
# X Exiting due to RUNTIME_ENABLE: Failed to enable container runtime: sudo systemctl restart cri-docker.socket: Process exited with status 1
```
Smells like the quay flakiness, but there's nothing to go on. Tests should probably be instrumented to run `journalctl`, `minikube logs`, and anything else that could give a user some hints.

* fedora-39 : minikube podman fedora-39 rootless host sqlite
  * PR #21908
    * [03-01 13:52](https://api.cirrus-ci.com/v1/artifact/task/6174705799921664/html/minikube-podman-fedora-39-rootless-host-sqlite.log.html#t--00001) in [minikube] minikube - check cluster is up
  * PR #21862
    * [02-29 14:12](https://api.cirrus-ci.com/v1/artifact/task/6425760194363392/html/minikube-podman-fedora-39-rootless-host-sqlite.log.html#t--00002) in [minikube] [001] minikube - deploy generated container yaml to minikube
  * PR #21601
    * [02-28 14:12](https://api.cirrus-ci.com/v1/artifact/task/5118444224380928/html/minikube-podman-fedora-39-rootless-host-sqlite.log.html#t--00001) in [minikube] minikube - check cluster is up

| x | x | x | x | x | x |
| ---: | ---: | ---: | ---: | ---: | ---: |
| minikube(3) | podman(3) | fedora-39(3) | rootless(3) | host(3) | sqlite(3) |

**Comment by afbjorklund** [comment]
Weird that already the cri-docker.socket fails, you would think it would wait until cri-docker.service

**Comment by edsantiago** [comment]
[Caught one](https://api.cirrus-ci.com/v1/artifact/task/6685304503926784/html/minikube-podman-fedora-39-rootless-host-sqlite.log.html#t--00002):
```
<+010ms> # $ minikube kubectl -- apply -f /tmp/minikube_deploy_SEeITt.yaml
<+593ms> # pod/test-ctr-pod created
         #
<+023ms> # $ minikube kubectl get pods
<+266ms> # NAME           READY   STATUS              RESTARTS   AGE
         # test-ctr-pod   0/1     ContainerCreating   0          0s
....
<+1.03s> # $ minikube kubectl get pods
<+232ms> # NAME           READY   STATUS         RESTARTS   AGE
         # test-ctr-pod   0/1     ErrImagePull   0          18s        <<<<<<<<<<<<<--------------------------------
....
<+1.03s> # $ minikube kubectl get pods
<+265ms> # NAME           READY   STATUS             RESTARTS   AGE
         # test-ctr-pod   0/1     ImagePullBackOff   0          30s       <<<<<<<<<<<<------------------
....
         # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
         # #| FAIL: Timed out waiting for pod to move to 'Running' state
         # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
"ErrImagePull" smells to me like quay flake. Anyone know for sure?

**Comment by cevich** [comment]
I believe I hit this using a "new" F40 image (still under test) or possibly a new flake?

https://api.cirrus-ci.com/v1/artifact/task/5131719219609600/html/minikube-podman-fedora-40-rootless-host-sqlite.log.html

The output seems [similar to a previous (above)](https://api.cirrus-ci.com/v1/artifact/task/5118444224380928/html/minikube-podman-fedora-39-rootless-host-sqlite.log.html#t--00001) hit on:

`You are using the QEMU driver without a dedicated network, which doesn't support `minikube service` & `minikube tunnel` commands.`

I don't think that test should be trying to use QEMU, but maybe that's a red herring?  In any case, I re-ran the task and it passed.

**Comment by cevich** [comment]
Maybe worth asking Urvashi to take a look?  IIRC she wrote these tests, and might have a quick/easy answer.

**Comment by cevich** [comment]
FWIW, I attempted to reproduce this in a `hack/get_ci_vm.sh` environment.  Painstakingly copy-pasting commands in the code-path one-by-one.  This worked perfectly fine for `minikube - check cluster is up` and `minikube - deploy generated container yaml to minikube`.  I was hoping to get lucky and it would reproduce for me given how seemingly often it breaks :cry: So I'm giving up.

Ref: https://github.com/containers/podman/pull/23237
