### ISSUE TITLE
private repo used `quay.io/baude/podman-machine-images-art`

### ISSUE THREAD

**Issue by lsm5** [containers/podman#21943]
https://github.com/containers/podman/blob/3e1d2ab874f637dba2daf0a933bda621ed4d9eaf/pkg/machine/ocipull/ociartifact.go#L29-L31

@baude PTAL

**Comment by lsm5** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2267825

**Comment by Luap99** [comment]
yes the image was changed between rc3 and rc4, the old URL however was removed for some reason.
I recommend to just update to rc4.

**Comment by lsm5** [comment]
cool, published rc4 just now https://github.com/containers/podman/releases
