### ISSUE TITLE
Random "authentication required" on podman 4.6.1

### ISSUE THREAD

**Issue by mpalourdio** [containers/podman#21976]
### Issue Description

Hi,

After an upgrade on our redhat 8, our podman version has been upgraded from podman `4.4.1` to `4.6.1`. Things have worked flawlessly for 2 years so far.

Since this sanity patching, we have observed random "authorization required", without any root cause. It "seems" that it happens at the very end of the push process (internal registry, based on https://hub.docker.com/_/registry), but setting podman to debug log level does not give more information, except that it seems to fail when trying to write the manifest at the very end.

Our credentials are in `~/.docker/config.json`, but moving them to to`${XDG_RUNTIME_DIR}/containers/auth.json` does not fix this randomness.

After this fail, relaunching a simple `podman push XXX` works 2 times on 3.

We have inspected LDAP logs for auth. failures, but no bind is processed. Looks like it's at client side that things go wrong.

We have `yum downgraded` this morning to `4.4.1`, things are back to normal. After reading the changelog, we can't see any deprecation that could give us a clue.

Please let me know if you need more information.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Redhat 8, install latest patches
2. podman --version should be 4.6.1
3. build and push some images, you may observe some authentication required failures

### Describe the results you received

```
+ podman push docker-registry.XXXXXX.com/whatever/whatever:24.2.X
Getting image source signatures
Copying blob sha256:d66e821df3f97b437d52fd6557fb1ef3ce68709a542d279ca8227fd333ca051e
Copying blob sha256:968151aebc01a5e290fe9a62f33ac9ed3bc1d7e5d3ad50218df605b2189a1f20
Copying blob sha256:d9ff549177a94a413c425ffe14ae1cc0aa254bc9c7df781add08e7d2fba25d27
Copying blob sha256:96b8c4e38de56d91a792604e14069e9e7f98a3649fd82caf8a34db63f2cd8aeb
Copying blob sha256:79a803ab33e2500155e0192a5ee33f99b5bc43ebe368b67a179a7344387509d4
Copying blob sha256:c5637af9c584264e892755c3ed8983092d0868fac79bdf900f57ca3d0ef0b99e
Copying blob sha256:f9633dda4d3f05e30d228fadd92af0b94a4abf9040cfeae997827541b53914a9
Copying blob sha256:cea0d813679af597ebda4da839e5de58c35e5496c9e1b6fadfd6b8928cf61959
Copying blob sha256:2bd11f6e753285481287ea0a570084640d6fed6bc841f56412fee2d3e9701ba7
Copying blob sha256:cee3743a313ec4040f67ae1b0613a6ae73952acb2903fd19ba5e0020bf1c4d16
Error: writing blob: uploading layer chunked: authentication required
```

### Describe the results you expected

pushed withour any error

### podman info output

```yaml
ost:
  arch: amd64
  buildahVersion: 1.29.0
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.8-1.module+el8.9.0+20326+387084d0.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.8, commit: 21e9be52d14128789284e1bbf54d8c25b4820215'
  cpuUtilization:
    idlePercent: 91.56
    systemPercent: 1.64
    userPercent: 6.79
  cpus: 6
  distribution:
    distribution: '"rhel"'
    version: "8.9"
  eventLogger: file
  hostname: slvXXXXXd
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 10818
      size: 1
    - container_id: 1
      host_id: 427680
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 10818
      size: 1
    - container_id: 1
      host_id: 427680
      size: 65536
  kernel: 4.18.0-513.11.1.el8_9.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 361766912
  memTotal: 16749625344
  networkBackend: cni
  ociRuntime:
    name: runc
    package: runc-1.1.9-1.module+el8.9.0+20326+387084d0.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.9
      spec: 1.0.2-dev
      go: go1.20.6
      libseccomp: 2.5.2
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/10818/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.1-1.module+el8.9.0+20326+387084d0.x86_64
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 3070025728
  swapTotal: 3221221376
  uptime: 49h 51m 6.00s (Approximately 2.04 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /ccv/XXXXXX/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /ccv/XXXXXXX/.local/share/containers/storage
  graphRootAllocated: 1073731338240
  graphRootUsed: 373058322432
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 2
  runRoot: /run/user/10818/containers
  transientStore: false
  volumePath: /ccv/XXXXXXXX/.local/share/containers/storage/volumes
version:
  APIVersion: 4.4.1
  Built: 1695119471
  BuiltTime: Tue Sep 19 12:31:11 2023
  GitCommit: ""
  GoVersion: go1.19.12
  Os: linux
  OsArch: linux/amd64
  Version: 4.4.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
If you have an issue with a RHEL version you should contact RHEL support unless you know the bug still exists in the latest version.
As upstream devs we will always ask you to first test with the latest upstream version, especially if the reproducer is "random" and cannot quickly be verified by us.

**Comment by mpalourdio** [comment]
I can fully understand that an issue on an 'outdated' version is not something you may look at. But was wondering if any clue on your side could lead us to any workaround. We are unfortunately stuck on RH8 for the moment, and as "non root" users as those VM, we are dependent of what is in the RH repositories.

Feel free to close this issue if you think this is something at RedHat side, and we'll open a ticket et RH support.

**Comment by Luap99** [comment]
It is not so much that I think the issue is with RHEL, RHEL has its own bug process that should be followed for best experience. In the end it is likely that the issue is still in our code however as far as upstream is concerned we fix the bug then release a new version eventually and until RHEL picks that up you may wait another 6+ months depending on the timing.
So it is in your best interest to go through the Red Hat channels because you then can request to backport the fixes to the version you are actually using right now.

**Comment by vrothberg** [comment]
I'd also echo what @Luap99 said.  There is also the valuable enterprise support to help resolve such issues - even if they are not caused by Podman.

While reaching out to RH support, you may already start taking a look at the registry you are using if possible.  I have no recollection of this symptom/issue.  In case you are using a proxy, try running without it if possible.  Proxies are a common source of transient failures.

**Comment by mpalourdio** [comment]
Thanks, we'll go this way. Closing now.
