### ISSUE TITLE
'podman system service' missing in >v4.x

### ISSUE THREAD

**Issue by tbshrst** [containers/podman#22008]
### Issue Description

I'm running rootless podman v3.4.4 (installed via APT) on the host and want to pass it's socket into containers, such that I can build inside the container, but write images to the host's podman. In the container rootless podman v3.4.4 is also installed via APT. This works fine.

However, for newer versions (currently v4.9.3, but apparently for all versions >v4.0) I'm unable to perform socket activation of the API service since 'podman system service' was apparently removed. I also found no replacement among the available commands. This is pretty confusing because the most recent mention of this command was in the changelog for v4.6.0. In fact this command doesn't show up from >v4.0. In addition, all the documentation still mention this command. 

I also found no related Issue, which makes it more confusing.
What am I missing here? 

Thanks in advance

### Steps to reproduce the issue

Steps to reproduce the issue
1. 'podman system service'
2. 'ls -la $XDG_RUNTIME_DIR/podman/podman.sock'
3. 'podman image ls'

### Describe the results you received

1. Error: unrecognized command `podman system service`
2. ls: cannot access '/podman/podman.sock': No such file or directory
3. Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.9.3/libpod/_ping": dial unix /var/run/user/0/podman/podman.sock: connect: connection refused

### Describe the results you expected

socket exists, successful communication with API through the socket

### podman info output

```yaml
Error: unable to connect to Podman socket: Get "http://d/v4.9.3/libpod/_ping": dial unix /var/run/user/0/podman/podman.sock: connect: connection refused
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

-

### Additional information

-

**Comment by Luap99** [comment]
The command still exists, I do not know you installed a newer podman but you are most likely using podman-remote and not podman.
