### ISSUE TITLE
FQDN needed in containers

### ISSUE THREAD

**Issue by Vic-M** [containers/podman#22013]
### Issue Description

When a container tries to connect to a server somehostname, the connection fails unless the FQDN is used (somehostname.fully.qualified.name). However connecting to somehostname works on the host.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create a container with podman-compose
2. In the container, try to connect to another server in the same network as the host using only the server's hostname

### Describe the results you received

host:
[vmatassa@lxkvmap178 medphys-server]$ curl WNETDCAD32
curl: (7) Failed to connect to WNETDCAD32 port 80: Connection refused
[vmatassa@lxkvmap178 medphys-server]$ curl WNETDCAD32.fully.qualified.name
curl: (7) Failed to connect to WNETDCAD32.fully.qualified.name port 80: Connection refused

container:
root@fb2be2e37aa7:/var/www/html# curl WNETDCAD32
curl: (6) Could not resolve host: WNETDCAD32
root@fb2be2e37aa7:/var/www/html# curl WNETDCAD32.fully.qualified.name
curl: (7) Failed to connect to WNETDCAD32.fully.qualified.name port 80: Connection refused

### Describe the results you expected

host:
[vmatassa@lxkvmap178 medphys-server]$ curl WNETDCAD32
curl: (7) Failed to connect to WNETDCAD32 port 80: Connection refused
[vmatassa@lxkvmap178 medphys-server]$ curl WNETDCAD32.fully.qualified.name
curl: (7) Failed to connect to WNETDCAD32.fully.qualified.name port 80: Connection refused

container:
root@fb2be2e37aa7:/var/www/html# curl WNETDCAD32
curl: (7) Failed to connect to WNETDCAD32 port 80: Connection refused
root@fb2be2e37aa7:/var/www/html# curl WNETDCAD32.fully.qualified.name
curl: (7) Failed to connect to WNETDCAD32.fully.qualified.name port 80: Connection refused

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.33.5
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.8-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.8, commit: 65953271fc1e506ac4eb890c645f3f75976973b4'
  cpuUtilization:
    idlePercent: 99.43
    systemPercent: 0.16
    userPercent: 0.41
  cpus: 4
  databaseBackend: sqlite
  distribution:
    distribution: centos
    version: "9"
  eventLogger: journald
  freeLocks: 1949
  hostname: lxkvmap178.fully.qualified.name
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 10102
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 10102
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.14.0-352.el9.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 3994652672
  memTotal: 16489390080
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.9.0-1.el9.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.9.0
    package: netavark-1.10.3-1.el9.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.10.3
  ociRuntime:
    name: crun
    package: crun-1.9.2-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.9.2
      commit: 35274d346d2e9ffeacb22cc11590b0266a23d634
      rundir: /run/user/10102/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: true
    path: /run/user/10102/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.3-1.el9.x86_64
    version: |-
      slirp4netns version 1.2.3
      commit: c22fde291bb35b354e6ca44d13be181c76a0a432
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 4292055040
  swapTotal: 4294963200
  uptime: 593h 17m 25.00s (Approximately 24.71 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/vmatassa/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /data/podman/lib/containers/storage
  graphRootAllocated: 105089261568
  graphRootUsed: 15273082880
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 15
  runRoot: /data/podman/run/containers/storage
  transientStore: false
  volumePath: /data/podman/lib/containers/storage/volumes
version:
  APIVersion: 4.9.3-dev
  Built: 1707216158
  BuiltTime: Tue Feb  6 05:42:38 2024
  GitCommit: ""
  GoVersion: go1.21.3
  Os: linux
  OsArch: linux/amd64
  Version: 4.9.3-dev
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

OS is CentOS 9 stream running in a VM
podman-compose version: 1.0.7

### Additional information

/etc/hosts on host:

127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
172.26.190.103 axap43
172.26.123.234 lxkvmap178.fully.qualified.name
172.26.125.177 lxkvmbe35.otherfully.qualified.name lxkvmbe35

/etc/hosts on container

127.0.0.1       localhost localhost.localdomain localhost4 localhost4.localdomain4
::1     localhost localhost.localdomain localhost6 localhost6.localdomain6
172.26.190.103  axap43
172.26.123.234 lxkvmap178.fully.qualified.name
172.26.125.177 lxkvmbe35.otherfully.qualified.name lxkvmbe35
172.26.123.234  host.containers.internal host.docker.internal
10.89.0.149     47d6f7fddd0c medphys-server_api_1

**Comment by Luap99** [comment]
And what exactly resolves `WNETDCAD32` on the host, /etc/hosts, dns, mdns, ...?

**Comment by Vic-M** [comment]
Networking isn't my specialty, so I'm not exactly sure how to answer your question but I think I figured out the issue. On the host's /etc/resolv.conf, we have:

```
domain fully.qualified.name
search fully.qualified.name
nameserver      172.25.192.16
nameserver      172.25.192.20
nameserver      172.25.32.8
nameserver      172.25.32.136
```

while on the container:
```
search dns.podman
nameserver 10.89.0.1
```

Adding `search fully.qualified.name` to the container's /etc/resolv.conf fixed the issue for that container. Is there a way to permanently add the search domain to all network containers created by podman?

**Comment by Luap99** [comment]
> Adding search fully.qualified.name to the container's /etc/resolv.conf fixed the issue for that container. Is there a way to permanently add the search domain to all network containers created by podman?

Yes in containers.conf there is a `dns_searches` option
