### ISSUE TITLE
Request for backport of sqlite respecting transient mode option to 4.9

### ISSUE THREAD

**Issue by alexlarsson** [containers/podman#22023]
In the automotive project we want to use transient storage mode, and we're currently using the 4.9 podman (in centos stream 9.4), however that version uses sqlite for the store which incorrectly doesn't store the sqlite database in /run for transient mode.

The fix for this is 6142c16a9c17fe7f2c2770b45b55d4d853f291eb. Is there any chance we could get this backported to 4.9?

**Comment by rhatdan** [comment]
@TomSweeneyRedHat ^^ Not sure if we plan on any more back ports to 4.9.

**Comment by Luap99** [comment]
6142c16a9c17fe7f2c2770b45b55d4d853f291eb is in 4v.5 and newer (including v4.9) thus it is is already included

So either you are testing the wrong thing, the fix commmit didn't fix the problem, or we regressed later again.

**Comment by alexlarsson** [comment]
Ah, I was testing this with the wrong config. Sorry.
