### ISSUE TITLE
add make validate deps

### ISSUE THREAD

**Issue by baude** [containers/podman#22025]
### Issue Description

When I run `make validate` without a `make docs`, the validate fails.  Validate does build ginkgo as a dep, it should also do make docs and make podman.

Thoughts?

### Steps to reproduce the issue

clone main, run make validate on Linux

### Describe the results you received

lets make this easier for developers

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
main
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
@edsantiago PTAL

**Comment by edsantiago** [comment]
Thanks for the ping, I lost track of this one.
