### ISSUE TITLE
ssh required when starting HyperV machine

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman#22075]
### Issue Description

I created a Podman 5.0.0 HyperV machine but when running `podman machine start` an error message about ssh is printed:

```
Starting machine "h1"

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

        podman machine set --rootful h1

time="2024-03-18T16:04:45+01:00" level=warning msg="could not copy output from command ssh to stderr"
time="2024-03-18T16:04:45+01:00" level=warning msg="could not copy output from command ssh to stdout"
Error: exec: "ssh": executable file not found in %PATH%
```
The error code is 127.`
podman machine ls` report machine is running.
But then `podman machine ssh` reports the same error.
And running podman machine ssh from a shell where ssh is available fails:
```
Connecting to vm h1. To close connection, use `~.` or `exit`
ssh: connect to host localhost port 61437: Connection refused
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. set CONTAINERS_MACHINE_PROVIDER=hyperv
2. podman machine init 
3. podman machine start

### Describe the results you received

Error while the machine is starting

### Describe the results you expected

Machine should start

### podman info output

```yaml
OS: windows/amd64
provider: hyperv
version: 5.0.0-rc7

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: dial tcp 127.0.0.1:61437: connectex: Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée.
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Win11Pro

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
I am pretty sure that ssh is hard requirement for hyperV.
cc @baude @mheon @n1hility

**Comment by jeffmaury** [comment]
That's my point: why is it a hard requirement for HyperV and not WSL ? Is it going to be handled by the installer ?

**Comment by n1hility** [comment]
5.x is requiring it for all systems atm  (including WSL). The readiness check and the proxy installation code are currently  using it. podman machine ssh has always required it, but to your point previously it was not required to start.

**Comment by n1hility** [comment]
>  Is it going to be handled by the installer ?

The installer could auto-install the SSH feature, or we could drop the need for ssh for start. I'll look into the former. Although this won't make 5.0, it will have to be 5.0.x release.

**Comment by jeffmaury** [comment]
> > Is it going to be handled by the installer ?
> 
> The installer could auto-install the SSH feature, or we could drop the need for ssh for start. I'll look into the former. Although this won't make 5.0, it will have to be 5.0.x release.

I'm not focused on start but on the general onboarding and to get if we need to implement or not in Podman Desktop
