### ISSUE TITLE
Nested containers has wrong permissions when using `--userns:keep-id`

### ISSUE THREAD

**Issue by gabyx** [containers/podman#22088]
### Issue Description

Discovering the possibility to nest containers in https://github.com/gabyx/container-nesting (which was specifically made for this bug report to properly test this). 
This repo uses the podman image to nest containers, so doing podman-in-podman-in-podman-.....

*Note: This container nesting is not some academic example (although for nesting levels >2 it migth be), this usecase appears in CI when we want the ability to not have everything in one top-level image only but leave room to run other containers inside the top-level one.*

Container nesting works with user `root`.

It seems that when running the container nesting recursion as user `podman` together with `--userns=keep-id:uid=1000,gid=1000` something is at odd when looking at the permission how the files are mounted at nesting level >1 (here only `/home/podman` is relevant but other directories have similar issues).

I dont think its a podman issue (hopefully) but maybe a image issue or a configuration issue. It would however be nice if the podman image would support such kind of nesting (1-2 levels).

### Steps to reproduce the issue

Steps to reproduce the issue
1. `git clone --branch bugfix/report-bug-podman https://github.com/gabyx/container-nesting`
2. `cd container-nesting`
3. Check that the root recursion works:
    ```shell
    just podman custom root
    ``` 
    or 
    ```shell
    cd src/podman && start-run.sh custom root false
    ```
    The output should be  

    <details>
    <pre>
     ===========================================================
     ===========================================================
     ==================== Start Recursion ======================
     ===========================================================
     ===========================================================
    | -> 1. Container: inside [version: 36ff37d9a63c55f5974889fcc8b778c4]
    | -> 1. Container: Launching a new container ...
    | -> 1. Container: create volume:
    | podman-root-1
    | -> 1. Container: Simple container run test:
    | NAME="Alpine Linux"
    | -> 1. Container: Start new container:
    |
    | | -> 2. Container: inside [version: 36ff37d9a63c55f5974889fcc8b778c4]
    | | -> 2. Container: Launching a new container ...
    | | -> 2. Container: create volume:
    | | podman-root-2
    | | -> 2. Container: Simple container run test:
    | | NAME="Alpine Linux"
    | | -> 2. Container: Start new container:
    | |
    | | | -> 3. Container: inside [version: 36ff37d9a63c55f5974889fcc8b778c4]
    | | | -> 3. Container: Launching a new container ...
    | | | -> 3. Container: create volume:
    | | | podman-root-3
    | | | -> 3. Container: Simple container run test:
    | | | NAME="Alpine Linux"
    | | | -> 3. Container: Start new container:
    | | |
    | | | | -> 4. Container: inside [version: 36ff37d9a63c55f5974889fcc8b778c4]
    | | | | -> 4. Container: Launching a new container ...
    | | | | -> 4. Container: create volume:
    | | | | podman-root-4
    | | | | -> 4. Container: Simple container run test:
    | | | | NAME="Alpine Linux"
    | | | | -> 4. Container: Start new container:
    | | | |
    | | | | | -> 5. Container: inside [version: 36ff37d9a63c55f5974889fcc8b778c4]
    | | | | | -> 5. Container: Finally reached container level: 5
    | | | | | -> 5. Container: leaving
    | | | |
    | | | | -> 4. Container: leaving
    | | |
    | | | -> 3. Container: leaving
    | |
    | | -> 2. Container: leaving
    |
    | -> 1. Container: leaving
    </pre>
    </details>
1. Run the recursion with user `podman`.
    This will use `--userns=keepid:uid=1000,gid=1000` to make all mounts use `podman` user.
    ```shell
    cd src/podman && start-run.sh custom podman false
    ```
    This will crash. To inspect whats going on use `start-run.sh custom podman true` which will put you in a `bash` shell right after entering every container and  right after leaving. Exit the shell to continue the recursion.

2. Inspect inside the `-> 1. Container: entering` that
    `ls -alnd /home/podman` has permission `1000`.
    
2. Inspect inside the `-> 2. Container: entering` that
    `ls -aln /home/podman` has **not permission `1000`** but on my machine its `999` which is weird.
    
**Note:** The image which is used is an `alpine` image with podman installed. You can also use `original` instead of `custom` above to build and use the original `quay.io/podman/stable` image. The findings are the same.

### Describe the results you received

The permissions on `ls -aln /home/podman` result in 1000 in the  1. container and **not** 1000 in the 2. container.
when  `podman run --userns=keepid:uid=1000,gid=1000 ...` is launched from within the 1. container. 

### Describe the results you expected

The `/home/podman` directory should be mounted with permissions `1000` also in the 2. container and on further deeper levels.

**Note**: I am using `--privileged` all the time, not sure if thats wrong...

### podman info output
<details>
<pre>
host:
  arch: amd64
  buildahVersion: 1.33.5
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /nix/store/wp1wic4bsd28qb7hs04dr7dsgls5j8pf-conmon-2.1.10/bin/conmon
    version: 'conmon version 2.1.10, commit: '
  cpuUtilization:
    idlePercent: 98.82
    systemPercent: 0.58
    userPercent: 0.6
  cpus: 32
  databaseBackend: sqlite
  distribution:
    codename: uakari
    distribution: nixos
    version: "24.05"
  eventLogger: journald
  freeLocks: 2019
  hostname: linux-nixos
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 100
      size: 1
    - container_id: 1
      host_id: 100000
      size: 10000000
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 10000000
  kernel: 6.6.19
  linkmode: dynamic
  logDriver: journald
  memFree: 39401140224
  memTotal: 67342225408
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: Unknown
      path: /nix/store/vwrqp3pfj17p0zd5gdnrkrvr702z838r-podman-4.9.3/libexec/podman/aardvark-dns
      version: aardvark-dns 1.10.0
    package: Unknown
    path: /nix/store/vwrqp3pfj17p0zd5gdnrkrvr702z838r-podman-4.9.3/libexec/podman/netavark
    version: netavark 1.7.0
  ociRuntime:
    name: crun
    package: Unknown
    path: /nix/store/h9wpwj1zjz6qjw3q331k757cq27kmj9k-crun-1.14.4/bin/crun
    version: |-
      crun version 1.14.4
      commit: 1.14.4
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /nix/store/vwrqp3pfj17p0zd5gdnrkrvr702z838r-podman-4.9.3/libexec/podman/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.2.3
      commit: c22fde291bb35b354e6ca44d13be181c76a0a432
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.5
  swapFree: 77309407232
  swapTotal: 77309407232
  uptime: 5h 53m 35.00s (Approximately 0.21 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/nixos/.config/containers/storage.conf
  containerStore:
    number: 25
    paused: 0
    running: 0
    stopped: 25
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/nixos/.local/share/containers/storage
  graphRootAllocated: 1049659179008
  graphRootUsed: 181234888704
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 622
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/nixos/.local/share/containers/storage/volumes
version:
  APIVersion: 4.9.3
  Built: 315532800
  BuiltTime: Tue Jan  1 01:00:00 1980
  GitCommit: ""
  GoVersion: go1.21.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.9.3
</pre>
</details>

### Podman in a container

Yes

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by cevich** [comment]
> The /home/podman directory should be mounted with permissions 1000 also in the 2. container and on further deeper levels.

User-namespaces can also be nested, and it get's really super confusing.  But for the 2. continaer, check the podman entry in 1. container's /etc/sub{u,g}id files.  There is an expected second translation based on the entries.

I think perhaps what you're after in the 2. container, is to run the nested podman with additional `--userns=keep-id:...` options to setup the maps how you expect.  I expect this will become confusing very quickly (it already hurts my brain).

**Comment by giuseppe** [comment]
how is this different than https://github.com/containers/podman/discussions/22049 ?

Is there anything to fix in Podman?  Otherwise, if it is not clear there is a Podman issue, let's close this issue and keep the discussion in one place.

**Comment by gabyx** [comment]
@giuseppe : Whats a shared store? Podman on my NixOS has `graphdrivername: overlay` and in the image its also `overlay` but also there is `overlay.mount_program` which points to `fuse-overlayfs` so its not OverlayFS (overlay2 (?).
How can I test this?

We can continue in the discussion, I can copy over the stuff there, for better reference...

**Comment by gabyx** [comment]
@giuseppe : When I remove 
- https://github.com/gabyx/container-nesting/blob/main/src/podman/container/run.sh#L81
- https://github.com/gabyx/container-nesting/blob/main/src/podman/start-run.sh#L40
I get the same uid map run from 1 container for `tail` in the second container :

```shell
cat /proc/468/uid_map
         0          1        999
       999       1001          1
      1000       1000          1
      1001       1002      64534
```

But the permissions on `/home/podman` are now correct to `1000`.
> There is no guarantee that a shared store will have the correct ownership for its files
I cannot access your solution to this link, would you share the gist of it?

**Comment by giuseppe** [comment]
> @giuseppe : Whats a shared store? Podman on my NixOS has `graphdrivername: overlay` and in the image its also `overlay` but also there is `overlay.mount_program` which points to `fuse-overlayfs` so its not OverlayFS (overlay2 (?).
> How can I test this?

the store you share with the nested containers must have been created with `fuse-overlays` as mount_program and it must have the following configuration:

```
[storage.options.overlay]
force_mask = "shared"
```

after you pull the images, also make sure all the files in the store are world readable, so you need:

```
chmod -R 755 /path/to/the/store
```

In the nested containers then you need to use fuse-overlayfs.

Since it is not a podman issue we need to address.  I am closing this issue now
