### ISSUE TITLE
WSL2 Mirrored Mode doesn't Share Ports Nicely

### ISSUE THREAD

**Issue by avlec** [containers/podman#22084]
### Issue Description

Running containers on a different IP address from my workstations NIC IP address on a podman ipvlan network I am unable to bind them to the same port as a application running on my workstation. I have verified I can have several applications binding to the same port in Windows 11 and they can share without issue.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Setup WSL2 mirrored networking
2. Create an ipvlan podman network on an interface
3. Run a windows app that binds to that port.
4. Create a container that uses the ipvlan network and tries to bind to the same port.

### Describe the results you received

> Error: cannot listen on the UDP port: listen udp4 :XXXXX: bind: address already in use

### Describe the results you expected

Success and both applications can use the same UDP port on different IP addresses.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.33.5
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - blkio
  - memory
  - devices
  - freezer
  - net_cls
  - perf_event
  - net_prio
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.10-1.fc39.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: '
  cpuUtilization:
    idlePercent: 99.79
    systemPercent: 0.05
    userPercent: 0.16
  cpus: 20
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: container
    version: "39"
  eventLogger: journald
  freeLocks: 2037
  hostname: RDFW-W-022
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.146.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 11144491008
  memTotal: 16771399680
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.10.0-1.fc39.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.10.0
    package: netavark-1.10.3-1.fc39.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.10.3
  ociRuntime:
    name: crun
    package: crun-1.14.3-1.fc39.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.14.3
      commit: 1961d211ba98f532ea52d2e80f4c20359f241a98
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20240220.g1e6f92b-1.fc39.x86_64
    version: |
      pasta 0^20240220.g1e6f92b-1.fc39.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.2-1.fc39.x86_64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 4294967296
  swapTotal: 4294967296
  uptime: 72h 32m 30.00s (Approximately 3.00 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 1
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /usr/lib/containers/storage
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 2231398400
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 14
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.9.3
  Built: 1708357294
  BuiltTime: Mon Feb 19 07:41:34 2024
  GitCommit: ""
  GoVersion: go1.21.7
  Os: linux
  OsArch: linux/amd64
  Version: 4.9.3
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

Windows 11 mirrored networking WSL2

### Additional information

UDP sockets. TCP sockets haven't been tried

**Comment by Tonyangl** [comment]
##I also faced this problem.
###wsl2
<img width="803" alt="1712108548806" src="https://github.com/containers/podman/assets/11551959/0539dc28-8c53-449b-b53d-3f5b87844d73">
###win11 ps
<img width="528" alt="1712108769814" src="https://github.com/containers/podman/assets/11551959/6b3c78b5-ab12-4dc5-ba56-7890373e0a79">

**Comment by avlec** [comment]
Thank you @Luap99 for looking into this.
I am using an ipvlan network and am looking to publish them to the same port but with the unique IP address from the ipvlan (I would be using macvlans if they worked with Windows 11 mirrored networking).

I am using SO_REUSEPORT in both the application running natively on windows as well as the application running within the container. The application in the container has a unique IP address to the host so I should be able to publish the ports of the container to be accessible on the LAN.

```
podman run -d --ip 192.168.1.123 -p 4000:4000/udp container-name
```

I'll take another look in case there's something else I'm missing about how the port binding is working on both sides. I assume with wanting broadcast reception to work that's going to be a different story.

**Comment by Luap99** [comment]
`-p 4000:4000/udp` that tell podman to bind port 4000 on every ip (on the WSL instance), podman doesn't use SO_REUSEPORT so it fails.

In general as root and witj ipvlan no port binding can work as root only uses

**Comment by Luap99** [comment]
So to fix your problem just remove the -p from your podman command

**Comment by avlec** [comment]
I guess the problem then is that I have a container that can communicate out but it seemingly can't receive any messages externally and for my application I need to receive unicast and broadcast packets.
