### ISSUE TITLE
Podman 5.0.0 fails to build image on macOS(Arm64): setup network: pasta failed with exit code 1

### ISSUE THREAD

**Issue by bc-lee** [containers/podman#22109]
### Issue Description

I updated podman 5.0.0 today and tried to build an image on macOS(Arm64) Host, but it failed with an error message related to the pasta.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create a simple Dockerfile like below:
```Dockerfile
FROM fedora:39

RUN mkdir -p /usr/local/share/ca-certificates
```

2. Run `podman build -t test .`

### Describe the results you received

The build fails with the following error:
```
$ podman build -t test .
STEP 1/2: FROM fedora:39
STEP 2/2: RUN mkdir -p /usr/local/share/ca-certificates
error running container: did not get container start message from parent: EOF
Error: building at STEP "RUN mkdir -p /usr/local/share/ca-certificates": setup network: pasta failed with exit code 1:
Don't run as root. Changing to nobody...
No routable interface for IPv6: IPv6 is disabled
Couldn't open network namespace /proc/2381/ns/net: Permission denied
```

### Describe the results you expected

The build should succeed.

### podman info output

```yaml
$ podman --version
podman version 5.0.0
$ podman info
host:
  arch: arm64
  buildahVersion: 1.35.0
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.10-1.fc39.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: '
  cpuUtilization:
    idlePercent: 99.65
    systemPercent: 0.15
    userPercent: 0.21
  cpus: 8
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: coreos
    version: "39"
  eventLogger: journald
  freeLocks: 2048
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.7.7-200.fc39.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 3161096192
  memTotal: 4088262656
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.10.0-1.20240312103946045036.main.18.g8377c0a.fc39.aarch64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.11.0-dev
    package: netavark-1.10.1-1.20240319111419242122.main.46.gcc3f35d.fc39.aarch64
    path: /usr/libexec/podman/netavark
    version: netavark 1.11.0-dev
  ociRuntime:
    name: crun
    package: crun-1.14.4-1.20240302220834691516.main.10.g64ee22c.fc39.aarch64
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: feb70bc2ab11944a6443e4f5d2eb96a22f186b80
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20240220.g1e6f92b-1.fc39.aarch64
    version: |
      pasta 0^20240220.g1e6f92b-1.fc39.aarch64-pasta
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.2-1.fc39.aarch64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 0h 11m 1.00s
  variant: v8
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /usr/share/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 16574820352
  graphRootUsed: 2911940608
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 3
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 5.0.0-dev-8a643c243
  Built: 1710720000
  BuiltTime: Mon Mar 18 09:00:00 2024
  GitCommit: ""
  GoVersion: go1.21.8
  Os: linux
  OsArch: linux/arm64
  Version: 5.0.0-dev-8a643c243
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Host Information
```
$ sw_vers -productVersion
14.4
$ uname -m
arm64
```
Above command worked on macOS(x86_64) Host.

Fedora Core information
```
# cat /etc/*-release | grep PRETTY_NAME
PRETTY_NAME="Fedora CoreOS 39.20240309.2.0"
# pasta --version | head -1
pasta 0^20240220.g1e6f92b-1.fc39.aarch64-pasta
```

**Comment by sbrivio-rh** [comment]
@bc-lee, thanks for reporting this! Could you please have a look at SELinux denials (`/var/log/audit/audit.log` or using a tool of your choice)?

**Comment by Luap99** [comment]
Is `container-selinux` installed in the image? If it is not installed try adding it with `rpm-ostree install container-selinux` then reboot.
If it is installed please check the selinux label with `ls -Z /usr/bin/podman` it should be `system_u:object_r:container_runtime_exec_t:s0`

**Comment by bc-lee** [comment]
> Could you please have a look at SELinux denials (/var/log/audit/audit.log or using a tool of your choice)?

Well, it seems that no SELinux denials are present in the audit log. I ran `# grep -i "denied" /var/log/audit/audit.log` and got no output.

**Comment by sbrivio-rh** [comment]
> Maybe this is related to #22052 ?

I don't think it has anything to do with that, actually. One thing that strikes me here is that pasta(1) is started as root in this case, and we don't quite expect that. I'm not sure if this is the intended behaviour for podman machine. If pasta is started as root, we might end up dropping additional capabilities compared to a regular user.

**Comment by Luap99** [comment]
Wait a minute? You are running podman as root, that should never use pasta there. Pasta will not run as root:
> Don't run as root. Changing to nobody...

Therefore it can never open the netns which is expected

**Comment by Luap99** [comment]
Does `podman run` work?

**Comment by sbrivio-rh** [comment]
> Wait a minute? You are running podman as root

But the `$` in `$ podman build -t test .` doesn't look like root...? I'm confused.

**Comment by bc-lee** [comment]
> But the `$` in `$ podman build -t test .` doesn't look like root...? I'm confused.

Yes, `$ podman run` works and can perform network operations.

I'm running on a non-root macOS account, where the podman machine is created with the `--rootful` option.

**Comment by Luap99** [comment]
Yeah I think this is once again a common podman-remote bug where we check privs on the remote side rather than on the server.

**Comment by Luap99** [comment]
Ok so yeah that is trivial to reproduce even on linux by running the service as root then connecting as rootless.
And I knew this was familiar to me, as I fixed the inverse problem (root->rootless) a while ago https://github.com/containers/podman/commit/dbfe79757b33231b3e5dc8537deb85fba8402eef.

I guess nobody noticed the problem so far because slirp4netns can be run as root so it never failed until we switched the default to pasta. so I guess a workaround is to use `podman build --network slirp4netns ...` or if do not not need any networking then `--network none`

**Comment by rhatdan** [comment]
I think they might be seeing something like this with podman desktop now.

**Comment by bc-lee** [comment]
Can I reopen this issue? Unfortunately, [the proposed fix](https://github.com/containers/podman/pull/22122) does not work for me.

I only checked the `podman-remote` side. If the isolation is set to `IsolationOCIRootless`, the `podman-remote` command fails, just as I initially reported.

<img width="1295" alt="Screenshot 2024-03-23 at 10 24 12" src="https://github.com/containers/podman/assets/7533290/f4cae432-7dd0-4e38-a893-0da3f5bb302f">

However, if I modify the code or set a command-line flag like `--isolation=default` or `--isolation=oci` to use `IsolationDefault` or `IsolationOCI`, then `podman build` works as expected.

<img width="1711" alt="Screenshot 2024-03-23 at 10 22 53" src="https://github.com/containers/podman/assets/7533290/9e051ced-91a8-447c-b8fb-e21ce212d502">


Note that, `unshare.IsRootless()` always returns `true` on macOS. [Link](https://github.com/containers/storage/blob/6c835719e98e403dae4a437e3809e247c9561b29/pkg/unshare/unshare_darwin.go)

**Comment by Luap99** [comment]
the fix only worked on the server so you need to update the server not the client, the client was fixed in https://github.com/containers/podman/pull/22133

**Comment by bc-lee** [comment]
As of e852b970f609b62202e212fad8de63cadd1d3d29, my issue is fixed. Thanks for the quick response!

**Comment by brianmcarey** [comment]
I am seeing a similar issue with `podman run` after upgrading our podman in container setup to podman v5. It uses a rootful remote podman socket. 

```
podman run hello-world
Resolved "hello-world" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull quay.io/podman/hello:latest...
Getting image source signatures
Copying blob 81df7ff16254 done   |
Copying config 5dd467fce5 done   |
Writing manifest to image destination
Error: setting up Pasta: pasta failed with exit code 1:
Don't run as root. Changing to nobody...
```

podman system info
<details>
host:
  arch: amd64
  buildahVersion: 1.35.4
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.10-1.fc40.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: '
  cpuUtilization:
    idlePercent: 94.9
    systemPercent: 0.8
    userPercent: 4.3
  cpus: 12
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: container
    version: "40"
  eventLogger: file
  freeLocks: 2047
  hostname: f599e6f31774
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.8.10-300.fc40.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 5265596416
  memTotal: 67164237824
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.10.0-1.fc40.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.10.0
    package: netavark-1.10.3-3.fc40.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.10.3
  ociRuntime:
    name: crun
    package: crun-1.15-1.fc40.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.15
      commit: e6eacaf4034e84185fd8780ac9262bbf57082278
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /bin/pasta
    package: passt-0^20240510.g7288448-1.fc40.x86_64
    version: |
      pasta 0^20240510.g7288448-1.fc40.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.2.2-2.fc40.x86_64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.3
  swapFree: 8587309056
  swapTotal: 8589930496
  uptime: 53h 46m 11.00s (Approximately 2.21 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /var/lib/shared-images
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 510389125120
  graphRootUsed: 282680532992
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 5.0.3
  Built: 1715299200
  BuiltTime: Fri May 10 00:00:00 2024
  GitCommit: ""
  GoVersion: go1.22.2
  Os: linux
  OsArch: linux/amd64
  Version: 5.0.3
</details>

**Comment by brianmcarey** [comment]
> > I am seeing a similar issue with `podman run` after upgrading our podman in container setup to podman v5. It uses a rootful remote podman socket.
> 
> What Podman version are you using, exactly? This is fixed only starting from 5.0.1.

podman v5.0.3

**Comment by Luap99** [comment]
@brianmcarey please file a new issue and provide a full reproducer there.
This here was a very specific issue about podman build so it cannot be related to yours.

**Comment by brianmcarey** [comment]
> @brianmcarey please file a new issue and provide a full reproducer there. This here was a very specific issue about podman build so it cannot be related to yours.

I've opened an issue here - https://github.com/containers/podman/issues/22907 - thanks @Luap99
