### ISSUE TITLE
No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by Ech0bv** [containers/podman#22145]
### Issue Description

Hello! im trying to download Vencord, its an app that unlocks new discord features, and i didnt have any problem installing it.
  But when i tried to install vencord files on discord lots of messages pop up saying "No connection could be made because the target machine actively refused it.".
also. I need to use a vpn to enter github because for some reason it doesnt let me enter github without one and it will just tell me
"github.com refused to connect." i tried to change browsers and everything but doesnt work, only using a vpn fixes it
P.S it also says that it was a success but when i try to open discord it doesnt work
![image](https://github.com/containers/podman/assets/164627929/b8150eeb-ed15-4d93-8a6f-46965866337a)

### Steps to reproduce the issue

Steps to reproduce the issue
1.Download and install vencord
2.open vencord.exe or vencordclient
3.press install
4. error message pops up saying "No connection could be made because the target machine actively refused it."
5. discord doesnt open because of a java error

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
Did you mean to report this somehwere else? This is the podman issue tracker so I will close this.
