### ISSUE TITLE
Podman 5.0.0-1 from linuxbrew does not build containerfile on Ubuntu 22.04 Github Actions runner

### ISSUE THREAD

**Issue by jiridanek** [containers/podman#22152]
### Issue Description

https://github.com/skupperproject/skupper-router/actions/runs/8392267222/job/23044730533

```
==> Downloading https://ghcr.io/v2/homebrew/core/podman/manifests/5.0.0-1
...
==> Pouring podman--5.0.0.x86_64_linux.bottle.1.tar.gz

...


Run podman build --build-arg PLATFORM=amd64 -t local/skupper-router:local -f ./Containerfile .
[1/2] STEP 1/19: FROM registry.access.redhat.com/ubi9/ubi-minimal:latest AS builder
Trying to pull registry.access.redhat.com/ubi9/ubi-minimal:latest...
Getting image source signatures
Copying blob sha256:2895d6faeea81934722a9a23efd8814ca51c1af558a3a70983ad2f7a412cdbe8
Copying config sha256:94c0198373526084dd06c13f07db53783c7318be9bcb6d691332d591d768f596
Writing manifest to image destination
[1/2] STEP 2/19: RUN microdnf -y upgrade --refresh --best --nodocs --noplugins --setopt=install_weak_deps=0 --setopt=keepcache=0  && microdnf clean all -y
error running container: from /usr/bin/crun creating container for [/bin/sh -c microdnf -y upgrade --refresh --best --nodocs --noplugins --setopt=install_weak_deps=0 --setopt=keepcache=0  && microdnf clean all -y]: unknown version specified
: exit status 1
time="2024-03-25T08:20:28Z" level=error msg="did not get container create message from subprocess: EOF"
Error: building at STEP "RUN microdnf -y upgrade --refresh --best --nodocs --noplugins --setopt=install_weak_deps=0 --setopt=keepcache=0  && microdnf clean all -y": while running runtime: exit status 1
Error: Process completed with exit code 1.
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. git clone https://github.com/skupperproject/skupper-router.git
2. brew install podman 
3. podman build --build-arg PLATFORM=amd64 -t local/skupper-router:local -f ./Containerfile .

### Describe the results you received

```
error running container: from /usr/bin/crun creating container for [/bin/sh -c microdnf -y upgrade --refresh --best --nodocs --noplugins --setopt=install_weak_deps=0 --setopt=keepcache=0  && microdnf clean all -y]: unknown version specified
```

### Describe the results you expected

no error

### podman info output

```yaml
podman 5.0.0, ubuntu 22.04, running as GitHub Actions hosted runner
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by ganeshmurthy** [comment]
```
2024-03-25T14:17:48.8805162Z 🍺  /home/linuxbrew/.linuxbrew/Cellar/crun/1.14.4: 9 files, 2.0MB
```
It looks like we are indeed using the latest version of crun (1.14.4)

**Comment by bougyman** [comment]
I see this issue as closed but what was the solution? I'm having the same problem currently on latest ubuntu with linuxbrew's podman and crun 1.14.4. I noticed that crun and podman were installed in the OS as well, I've since removed those and now have a new fun issue:

```
 % podman build -f ./oci/Containerfile .
[1/2] STEP 1/11: FROM docker.io/ruby:3.3.0-alpine3.19 AS build-env
[1/2] STEP 2/11: ARG APP_ROOT=/app
--> Using cache 9b34e448058ff1f871b7337d1408ff47875aaf6ca4fee07462fe0f98aa4fbdc4
--> 9b34e448058f
[1/2] STEP 3/11: ENV LANG C.UTF-8
--> Using cache b259586a8f067b7626d3fdaece2809c4d340dc25fc262f93133928a6bd10d581
--> b259586a8f06
[1/2] STEP 4/11: ENV BUNDLE_SILENCE_ROOT_WARNING=1
--> Using cache b26e818d9f2e5e2ec950ff876fe524cd228bcb9517281969fbe6aeba2c691767
--> b26e818d9f2e
[1/2] STEP 5/11: ENV RACK_ENV=production
--> Using cache fd5b9e36ce910047bf8e53ba25dfe2fd771b5eeaa15231120c7a42dcea9cd66d
--> fd5b9e36ce91
[1/2] STEP 6/11: RUN apk --update add curl ruby-dev build-base git postgresql-dev libsodium-dev
error running container: did not get container start message from parent: EOF
Error: building at STEP "RUN apk --update add curl ruby-dev build-base git postgresql-dev libsodium-dev": setup network: could not find pasta, the network namespace can't be configured: exec: "pasta": executable file not found in $PATH
```

**Comment by jiridanek** [comment]
The solution was to install podman not from Brew, but the Ubuntu build from opensuse kubic

* https://github.com/skupperproject/skupper-router/commit/a99fbee2fe8b7efd707d13c95e156be4a807d4f5
* 

[The internets say that](https://askubuntu.com/questions/1414446/whats-the-recommended-way-of-installing-podman-4-in-ubuntu-22-04) the Kubic package "has been discontinued", and there is indeed only an [older version of podman present](https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04/amd64/), but in actual usage it seems to work, whereas the brew one does not.

**Comment by bougyman** [comment]
Huh, I'm using the brew version, after removing ubuntu's 'podman' and 'crun' (which was the Unknown version), I had to install paast to get by the pasta networking thing (I guess podman defaults to pasta now?).
Pasta install here: https://passt.top/passt/about/#try-it. This is working with linuxbrew's latest podman.

**Comment by jiridanek** [comment]
@bougyman you can try going back to `slirp4netns` and avoid that step. Maybe something like https://github.com/containers/podman/issues/22044#issuecomment-2009255504 or add `--network=slirp4netns` to all your `podman build ` and `podman run` commands.

**Comment by bougyman** [comment]
@jiridanek no worries. I'm glad I found pasta in this effort. It's a welcome addition to my toolbox.

**Comment by w-hc** [comment]
May I ask what is the recommended way to install Podman v5 on ubuntu-22.04? 
The apt-get version is still 3.4.4.

**Comment by rhatdan** [comment]
The upstream team has nothing to do with this, but I have heard that packages are being made available via brew.

Upstream Podman team does not provide distro specific packages for any distro. 
Although upstream people can get paid to update distros like Fedora and RHEL. but even those distros require the packages to come from the distro not from upstream.

**Comment by w-hc** [comment]
Understood. Just looking for a recommendation.

**Comment by Cyclenerd** [comment]
For all those who find this issue current because Kubic package (`download.opensuse.org/repositories/devel:kubic:libcontainers`) no longer works on GitHub Actions hosted runner...

The solution is as described above:

* Install `podman` and `crun` via Linuxbrew.
* Additionally pass `--network slirp4netns` during the build.

You can find a working configuration at:
https://github.com/Cyclenerd/cloud-tools-container/blob/9333550a820b160efb28c03f5db8708906582e81/.github/workflows/docker-latest.yml
