### ISSUE TITLE
[AzureTools] Fail to F5 a Aspire starter project with an error on Podman CLI 5.0.0

### ISSUE THREAD

**Issue by v-mengwe** [containers/podman#22169]
**Clean machine:** Win11 x64 23h2 ENU
**VS Version**: 17.10.0 Preview 3.0 [34725.203.main]
**Aspire Version:** 8.0.0-preview.5.24175.9
Apply NuGet Feeds
**Regression:** Not a regression
**Podman Desktop:** 1.8.0
**Podman:** 5.0.0

**REPRO STEPS:**

1. Create a Aspire starter project with command > `dotnet new aspire-starter --use-redis-cache`.
2. Change dir to AppHost folder > `cd AspireStarterApp01\AspireStarterApp01.AppHost`
3. Run the app > `dotnet run`

**Expect:**
No error occurs.
![image](https://github.com/dotnet/aspire/assets/62053665/90c5f37e-0427-450a-8589-0c2cc8cfd5fb)

**Actual:**
An error pops up.
![image](https://github.com/dotnet/aspire/assets/62053665/13fedbb7-f500-4797-bb00-e91ae3d15a1b)

**More Info:**
1. This issue **doesn't reproduce** for the VS 17.10.0 Preview 3.0 [34725.203.main] with podman CLI 4.9.3.
2. This issue also **reproduces** for VS 17.10 Preview 2 with podman CLI 5.0.0.
3. This issue **doesn't reproduce** for VS 17.10 Preview 2 with podman CLI 4.9.3.

**Comment by v-mengwe** [comment]
Please help to move to the right path if this path is wrong, thanks!

**Comment by mheon** [comment]
This looks like the Entrypoint change in `podman inspect` (changed from string to array to match Docker's output, breaking change in Podman 5.0). The app may need to change to account for this.

**Comment by mheon** [comment]
Ref: https://github.com/containers/podman/releases/tag/v5.0.0 - in breaking changes:
`The output of podman inspect for containers has seen a number of breaking changes to improve Docker compatibility, including changing Entrypoint from a string to an array of strings and StopSignal from an int to a string.`

**Comment by Luap99** [comment]
Looks like this was answered
