### ISSUE TITLE
debian: runc create failed: error mounting cgroup to rootfs: something slice: ENOENT

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#22165]
Two instances, both seen only in [last week's new VM build](https://github.com/containers/automation_images/pull/337#issuecomment-2010128930):
```
# podman [options] run --pod testpod quay.io/libpod/alpine:latest cat /etc/hosts
time="2024-03-25T17:20:16Z" level=error msg="Starting some container dependencies"
time="2024-03-25T17:20:16Z" level=error msg="\"runc: runc create failed: unable to start container process: error during container init: error mounting \\\"cgroup\\\" to rootfs at \\\"/sys/fs/cgroup\\\": stat /sys/fs/cgroup/devices/machine.slice/machine-libpod_pod_0b2bfa75b9e139af1542a302869e7de36c11ec40691616fd980cfc2a04813699.slice/libpod-1ae333654906d875ed36bea81bf0be74da47dc7e867c7ecc22c44b407240db64.scope: no such file or directory: OCI runtime attempted to invoke a command that was not found\""
Error: starting some containers: internal libpod error
```
Seems to be related to pods. Root only (so far).

Relevant VM diffs: 
* kernel 6.6.15 -> 6.7.9
* runc 1.1.12+ds1-1 -> **-2**
* systemd 255.3 -> **.4**

Probably a don't-care, given our intention to abandon runc.

* debian-13 : int podman debian-13 root host sqlite
    * [03-25 13:22](https://api.cirrus-ci.com/v1/artifact/task/5172171547344896/html/int-podman-debian-13-root-host-sqlite.log.html#t--Podman-run-networking-podman-run-with-pod-does-not-add-extra-127-entry-to--etc-hosts--1) in Podman run networking podman run with pod does not add extra 127 entry to /etc/hosts
    * [03-19 16:14](https://api.cirrus-ci.com/v1/artifact/task/6683361299660800/html/int-podman-debian-13-root-host-sqlite.log.html#t--Podman-kube-play-with-multiple-networks--1) in Podman kube play with multiple networks

EDIT: forgot to mention, there's another current flake having to do with cgroup-slice, #20044, but I don't think it's related. Still, maybe.

**Comment by Luap99** [comment]
We no longer test runc AFAICT
