### ISSUE TITLE
Can rmi support a regular expression?

### ISSUE THREAD

**Issue by wraschke** [containers/podman#22179]
### Feature request description

Based on forum posts like this:

https://forums.docker.com/t/how-do-i-delete-multiple-docker-images-in-a-single-command/115499/5

and

https://stackoverflow.com/questions/40084044/how-to-remove-docker-images-based-on-name

I believe there is a common need to remove images with a regular expression/wildcard that matches a number of images; i.e., so that a specific ID does not need to be supplied with a separate command.

I understand there are ways to do this with bash scripting. However, to allow users to do this with Podman alone would be a great convenience--for example, with a flag that takes a regular expression provided by the user.

### Have you considered any alternatives?

Within the bash command line, issue the following:

podman images | grep <pattern_for_matching> | awk '{print $3}' | xargs podman rmi -f

**Comment by Luap99** [comment]
I would not be in favour of that, the added complexity in our code is not worth it IMO. My main concern is that if we add it to podman rmi then the next persons wnats it for podman rm, pod rm, volume rm and so on... This quickly explodes in a lot of complexity so I rather avoid it.

**Comment by rhatdan** [comment]
I agree, leave this to the shell.
