### ISSUE TITLE
include arch/os in image libpod list

### ISSUE THREAD

**Issue by benoitf** [containers/podman#22185]
### Feature request description

Today, 

```
 "Architecture": "arm64",
"Os": "linux",
```

are only available when we inspect an image

But usually this information is useful when we want to list images. For example to know if an image is using `amd64` or Apple Silicon computer, etc.

so it requires one additional query for each image.

### Suggest potential solution

Include

```json
 "Architecture": "arm64",
"Os": "linux",
```

as part of `libpod/images/json` return this information

could be with an additional query parameter to the endpoint `?arch=true&os=true`, `?displayArchAndOs`, whatever so opt-in query.

**Comment by rhatdan** [comment]
@vrothberg PTAL, I think the problem here is that libimage does not return these by default but only in inspectinfo.  Valentin would their be a penalty to return these automatically in list?

**Comment by baude** [comment]
i have the ball on this one.
