### ISSUE TITLE
podman 5.0.0 running as root inside systemd-nspawn containers with user namespacing overmounts the system-wide `/run` directory

### ISSUE THREAD

**Issue by PeterCxy** [containers/podman#22218]
### Issue Description

I am not sure whether this is technically a supported use-case, however it used to work fine for me: I run a bunch of systemd-nspawn containers with `PrivateUsers=pick` (so that the root user inside is not the real root), and then run Podman as root inside of those containers. This is useful, for example, when I want to run a CI daemon that requires access to a docker-compatible socket without giving it access to any Podman socket on the host system.

However after upgrading to Podman 5.0.0, this seems to no longer work. Running any Podman container gives the error

```
Error: rootless netns: write ref counter: open /run/containers/storage/networks/rootless-netns/ref-count: no such file or directory
```

It looks like the `/run` directory inside the systemd-nspawn container is overmounted by Podman at some point before this error message is printed (did Podman fail / forget to enter the mountns somehow but without printing an error?). This also causes everything else that requires access to `/run` to break as well.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Start a `systemd-nspawn` container with `PrivateUsers=pick`
2. Install Podman inside that `systemd-nspawn` container
3. Attempt to run any Podman container inside the `systemd-nspawn` container (e.g. `sudo podman run --rm -it hello-world`)

### Describe the results you received

Podman fails to execute the container with

```
Error: rootless netns: write ref counter: open /run/containers/storage/networks/rootless-netns/ref-count: no such file or directory
```

And the environment inside the `systemd-nspawn` container is broken due to `/run` being overmounted by Podman.

### Describe the results you expected

Podman used to work just fine running as root inside a non-root user namespace.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.35.1
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.1.10-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: 2dcd736e46ded79a53339462bc251694b150f870'
  cpuUtilization:
    idlePercent: 88.48
    systemPercent: 6.75
    userPercent: 4.77
  cpus: 16
  databaseBackend: sqlite
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  freeLocks: 2037
  hostname: forgejo-runner
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 6.6.23-1-lts
  linkmode: dynamic
  logDriver: journald
  memFree: 57755320320
  memTotal: 66798481408
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: /usr/lib/podman/aardvark-dns is owned by aardvark-dns 1.10.0-1
      path: /usr/lib/podman/aardvark-dns
      version: aardvark-dns 1.10.0
    package: /usr/lib/podman/netavark is owned by netavark 1.10.3-1
    path: /usr/lib/podman/netavark
    version: netavark 1.10.3
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 1.14.4-1
    path: /usr/bin/crun
    version: |-
      crun version 1.14.4
      commit: a220ca661ce078f2c37b38c92e66cf66c012d9c1
      rundir: /run/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: /usr/bin/pasta is owned by passt 2024_03_26.4988e2b-1
    version: |
      pasta 2024_03_26.4988e2b
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.2.3-1
    version: |-
      slirp4netns version 1.2.3
      commit: c22fde291bb35b354e6ca44d13be181c76a0a432
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.5
  swapFree: 66797432832
  swapTotal: 66797432832
  uptime: 3h 9m 21.00s (Approximately 0.12 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 0
    stopped: 3
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphRootAllocated: 871697575936
  graphRootUsed: 432323764224
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 8
  runRoot: /run/containers/storage
  transientStore: false
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 5.0.0
  Built: 1711060217
  BuiltTime: Thu Mar 21 18:30:17 2024
  GitCommit: e71ec6f1d94d2d97fb3afe08aae0d8adaf8bddf0-dirty
  GoVersion: go1.22.1
  Os: linux
  OsArch: linux/amd64
  Version: 5.0.0
```
```


### Podman in a container

Yes

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Both host and the `systemd-nspawn` container are on the latest Arch Linux packages as of 2024-03-29

### Additional information

_No response_

**Comment by PeterCxy** [comment]
Downgrading to 4.9.3 seems to resolve the issue. Personally I suspect the new `rootlessnetns` module in `common` might have introduced this issue.

**Comment by PeterCxy** [comment]
It looks like the mount [here](https://github.com/containers/common/blob/main/libnetwork/internal/rootlessnetns/netns_linux.go#L437) is where that `/run` mount came from. But I'm pretty sure this mount should happen in its own mount namespace...?

**Comment by PeterCxy** [comment]
Ok, it seems that this `setupMounts()` function simply do not work correctly if `podman` is running with a "fake" root account. We can fix the over-mounting by making the entire mount tree private, but then podman network still cannot get set up properly because `/run` is still not valid inside the mount namespace (it is set up for CNI plugins, but podman itself still tries to look for `ref-count` which is present in the *original* `/run` directory, but not in the version set up for the namespace).

On the other hand, do we actually need to call `setupMounts()` here if podman is run with a fake root inside a usernamespace'd container? To me it looks like it is only needed if CNI plugins cannot write directly to the system-wide `/run` directory. Simply deleting `setupMounts()` seems to make everything work for me.

**Comment by PeterCxy** [comment]
Not sure about correctness / security, but I am currently using the following workaround:

```go
diff --git a/vendor/github.com/containers/common/libnetwork/internal/rootlessnetns/netns_linux.go b/vendor/github.com/containers/common/libnetwork/internal/rootlessnetns/netns_linux.go
index 1531ee52e..61797a8c3 100644
--- a/vendor/github.com/containers/common/libnetwork/internal/rootlessnetns/netns_linux.go
+++ b/vendor/github.com/containers/common/libnetwork/internal/rootlessnetns/netns_linux.go
@@ -275,6 +275,11 @@ func mountAndMkdirDest(source string, target string, fstype string, flags uintpt
 func (n *Netns) setupMounts() error {
 	// Before we can run the given function,
 	// we have to set up all mounts correctly.
+	// Unless /run is writable already: this is possible if podman is running as
+	// root inside some other container with user namespaces
+	if unix.Access("/run", unix.W_OK) == nil && unix.Access("/var/lib/cni", unix.W_OK) == nil {
+		return nil
+	}
 
 	// The order of the mounts is IMPORTANT.
 	// The idea of the extra mount ns is to make /run and /var/lib/cni writeable
```

**Comment by rhatdan** [comment]
Could this also be a pasta versus slirp4netns issue, you could change containers.conf to user slirp4netns to see if the issue goes away.  slirp4netns was default in 4.9.*, pasta is default in 5.0

**Comment by PeterCxy** [comment]
@rhatdan I don't believe it's related to pasta vs slirp4netns. Changing it back to slirp4netns ends up in the same error. It looks like the path to the netns (`/run/containers/storage/networks/rootless-netns/`) is passed in to rootlessnetns from the rest of podman.

There seems to be two issues here:

1. When podman is running as root inside another container, the netns path defaults to somewhere in `/run`, or at least the `ref-count` file is expected to be located in there. So once `/run` is overmounted during `setupMounts()`, all the files no longer exist;
2. When `rootlessnetns` creates its own mount namespace, it does not set the root of that namespace to be `MS_PRIVATE|MS_REC`. This results in mounts inside there to propagate outside (as `systemd-nspawn` mounts the container root as `MS_SHARED`), and causing `/run` outside of podman to be overmounted as well, breaking the system.

**Comment by PeterCxy** [comment]
To me it feels like `setupMounts()` is not really needed if `/run` and `/var/lib/cni` are already accessible to the user running podman, hence the patch above.

**Comment by Luap99** [comment]
The patch is not a bad idea but really the whole rootless-netns code must be skipped when running as root with CAP_SYS_ADMIN and CAP_NET_ADMIN. Do you have these caps in your nspawn container?

Basically the code today checsk IsRootless() which is not correct as it also counts a userns as rootless, we should check whenever we re-execed into the podman userns or not.

**Comment by Luap99** [comment]
Making sure we make our mounts private is of course also a good idea to avoid this issue of breaking the "host" system accidentally

**Comment by PeterCxy** [comment]
@Luap99 Yes, and after checking older Podman (which worked inside `systemd-nspawn`) and Docker I think none of them used rootless netns at all, at least `slirp4netns` or `pasta` are not launched. Bridges can be directly created inside `systemd-nspawn`.

**Comment by Luap99** [comment]
@PeterCxy In case you able to compile from source please test if https://github.com/containers/podman/pull/22243 works for you.

**Comment by PeterCxy** [comment]
@Luap99 Seems to work fine for me.

**Comment by Luap99** [comment]
@PeterCxy Thanks for checking.
