### ISSUE TITLE
Manpage for podman-systemd.unit includes incomplete advice which can lead to unexpected behavior

### ISSUE THREAD

**Issue by drawks** [containers/podman#22233]
The advice to use the `RemainAfterExit` option neglects to provide a full explanation as to the motivation which leads to the advice sometimes (often?) being incorrect. 

https://github.com/containers/podman/blob/45b809c0631fa1e3d92608345cd96b988537d7ce/docs/source/markdown/podman-systemd.unit.5.md?plain=1#L90-L91

If the generated container unit is meant to be a recurring oneshot job activated by a timer unit then setting ` RemainAfterExit` will result in the container/service being run only once and then left in the "started" state which will prevent subsequent timer events from triggering the unit again. It would perhaps be more useful to the user to refer to the systemd manpage for `systemd.service(5)` which provides a much more full explanation which.

Similarly the note about `TimeoutStartSec`:

https://github.com/containers/podman/blob/45b809c0631fa1e3d92608345cd96b988537d7ce/docs/source/markdown/podman-systemd.unit.5.md?plain=1#L68-L72

neglects to mention that the behavior of systemd is different when `type=oneshot`, again it would probably be useful to reference the systemd.service manpage, which details more completely the expected behavior and includes the critical notes about exceptional behaviors.

**Comment by baude** [comment]
would love a PR!
