### ISSUE TITLE
Unable to Create First Machine with New Download on Windows

### ISSUE THREAD

**Issue by AllanHall** [containers/podman#22244]
### Issue Description

This is my first time working with Podman. I downloaded a fresh exe of the most recent version 5.0.1. Downloaded the newest version of WSL. As well as windows terminal per the documentation. After restarting everything I am unable to run podman machine init to create a machine with the following error:

`Error: unable to load machine config file: "json: cannot unmarshal string into Go struct field MachineConfig.ImagePath of type define.VMFile"`

I found a similar issue that was closed here https://github.com/containers/podman/issues/22144 but it focused more on trying to upgrade from a previous version of Podman so I created a new issue. As I am a brand new user, I am just trying to make my first machine. Any guidance on trying to find a fix for a new user or downloading a previous version to get started is appreciated.
![Screenshot 2024-04-02 140921](https://github.com/containers/podman/assets/47412396/26d81d67-068e-4a09-ad7e-218a89069919)
![Screenshot 2024-04-02 141144](https://github.com/containers/podman/assets/47412396/387863c0-46af-4c05-b629-968f2d76723d)

### Steps to reproduce the issue

Steps to reproduce the issue
1. Download and Install Podman 5.0.1 exe for windows
2. Install newest WSL version 2.1.5.0
3. Install Windows Terminal
4. Reboot
5. Run podman machine init

### Describe the results you received

`Error: unable to load machine config file: "json: cannot unmarshal string into Go struct field MachineConfig.ImagePath of type define.VMFile"`

### Describe the results you expected

The init command will install a minimal installation of Fedora, customizing it to run podman. Able to create first machine.

### podman info output

```yaml
OS: windows/amd64
provider: wsl
version: 5.0.1
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

**Comment by baude** [comment]
can you ls on `C:\Users\Ahall\.config/containers/podman/machine/wsl` ? if there is only one JSON file in there, can you paste its contents (preferably do not paste as a picture)

**Comment by FritzsHero** [comment]
{
 "ConfigPath": "C:\\Users\\Username\\.config\\containers\\podman\\machine\\wsl\\podman-machine-default.json",
 "Created": "2023-12-12T08:29:41.9944601+01:00",
 "ImageStream": "testing",
 "ImagePath": "C:\\Users\\Username\\.local\\share\\containers\\podman\\machine\\wsl\\podman-machine-default_fedora-podman-amd64-v39.0.2.tar",
 "LastUp": "2024-03-28T23:43:50.3886254+01:00",
 "Name": "podman-machine-default",
 "Rootful": true,
 "IdentityPath": "C:\\Users\\Username\\.ssh\\podman-machine-default",
 "Port": 49961,
 "RemoteUsername": "user",
 "Version": 3,
 "UserModeNetworking": false
}

![image](https://github.com/containers/podman/assets/10697943/ef409182-2f3d-4ca2-be72-dd5191d259c1)

Getting the same error on Win10, Podman 5.0.1 and Podman Desktop 1.8.0

**Comment by lazka** [comment]
Same problem here, using a self built podman though:

```console
$ podman --version
podman.exe version 5.0.1
$ podman machine reset
Error: unable to load machine config file: "json: cannot unmarshal string into Go struct field MachineConfig.ImagePath of type define.VMFile"
```

```json
{
 "ConfigPath": "C:\\Users\\user\\.config\\containers\\podman\\machine\\wsl\\podman-machine-default.json",
 "Created": "2023-02-13T22:05:19.4946104+01:00",
 "ImageStream": "35",
 "ImagePath": "C:\\Users\\user\\.local\\share\\containers\\podman\\machine\\wsl\\podman-machine-default_fedora-podman-amd64-v36.0.124.tar",
 "LastUp": "2024-04-01T12:01:39.3473492+02:00",
 "Name": "podman-machine-default",
 "Rootful": false,
 "IdentityPath": "C:\\Users\\user\\.ssh\\podman-machine-default",
 "Port": 62950,
 "RemoteUsername": "user",
 "Version": 3,
 "UserModeNetworking": false
}
```

**Comment by AllanHall** [comment]
I had installed Podman Desktop the day before and completely deleted it - thinking I removed everything related to start fresh on 5. However, it looks like the VM still remained and it was picking those remnants when trying to init a new machine. I needed to run podman machine rm to finish cleaning up. I believe this can be closed as its the same issue alisonatwork described above.
