### ISSUE TITLE
Docs: No documentation on manifest creation return

### ISSUE THREAD

**Issue by cdrage** [containers/podman#22256]
### Issue Description

When you use the API to create a manifest:

```
▶ curl --unix-socket /var/folders/cn/pm5mgrcs5h339nphypxtvd080000gn/T/podman/podman-machine-default-api.sock -X POST \
     "http://d/v4.2.0/libpod/manifests/test?images=quay.io/bootc-extension/httpd"

{"Id":"6a105d8fe5a76e15c4687f44deb923acf62608d56ede79b74f5a9251de5e2155"}
```

You get ID in return.

However in the API documentation it says it returns null, when it should be ID?

![Screenshot 2024-04-03 at 3 49 25 PM](https://github.com/containers/podman/assets/6422176/bfcd9bb9-2623-446d-a804-1dad73b0528e)

### Steps to reproduce the issue

Do the CURL request in the issue description and see it returns ID.

### Describe the results you received

ID, but in docs it shows null

### Describe the results you expected

Null (docs should be corrected to null)

### podman info output

```yaml
N/A
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

Was when implementing https://github.com/containers/podman-desktop/issues/6624

**Comment by Luap99** [comment]
something seems to be wrong with the entire swagger file, this does not effect just this one endpoint. All endpoints seems to have no payloads so something in the generation is broken.

**Comment by Luap99** [comment]
should work again https://docs.podman.io/en/latest/_static/api.html#tag/manifests/operation/ManifestAddLibpod
