### ISSUE TITLE
API: libpod system prune endpoint lacks complete documentation

### ISSUE THREAD

**Issue by jponge** [containers/podman#22333]
### Feature request description

The current API docs lack important details.

Consider the `system prune` API endpoint:
<img width="1296" alt="image" src="https://github.com/containers/podman/assets/25961/b869c54b-f5a9-428e-9bf9-b18e288f2f37">

What is the `POST` payload? Are there URL or query parameters? What are they?

### Suggest potential solution

I can eventually figure this out by reading the Go source code, but this should really be in the docs.

### Have you considered any alternatives?

Reading at the Go source code 😄

**Comment by baude** [comment]
well there are a couple of things at play: knowing there is an endpoint that is wrong; and then fixing it.  I'm not sure we knew about this one.  Care to submit a PR?

**Comment by baude** [comment]
I'm going to change the title to reflect this one if you are ok with that.

**Comment by Luap99** [comment]
@baude All endpoints are broken, this is a general issue. At some point the swagger we generate lost just all payload information for whatever reasons.

**Comment by Luap99** [comment]
With the latest swagger fixes we now see the payloads correctly again: https://docs.podman.io/en/latest/_static/api.html#tag/system/operation/SystemPing
This however only shows the 200 return value and not the parameter that the endpoint accepts so this still has to be added manually.

**Comment by jponge** [comment]
LGTM thanks!
