### ISSUE TITLE
Rootless networking backend info w/ podman info

### ISSUE THREAD

**Issue by danishprakash** [containers/podman#22356]
### Feature request description

We currently show networking backend information for rootful containers but not for rootless containers, though we show information about both pasta and slirp4netns. But since we're in a middle of a transition w/ the rootless networking backends, it'd be helpful to show rootless networking backend as part of `podman info`. 

I'll raise a PR if the idea sounds good.

### Suggest potential solution

`NetworkBackendInfo` could show information for both rootless and rootfull containers.

**Comment by Luap99** [comment]
Duplicate of #22172
