### ISSUE TITLE
Allow disabling default mounts via `podman machine init` command

### ISSUE THREAD

**Issue by arixmkii** [containers/podman#22364]
### Feature request description

There are predefined mounts for machine init. It is possible to override them with `-v "/mnt:/mnt"` series of arguments, but it is not currently possible to disable them, when running `podman machine init` command. Later on it is possible to disable them by editing machine config json file.

This covers edge cases, when one wants to run podman machine as isolated from host as possible or cases, where due to some specifics it is not possible to use mounts from host.

### Suggest potential solution

Add special treatment to the `-v ""` option (empty string value), which will override the defaults, but not actually add anything to the list.

Could be implemented with a patch as little as this (not including documentation).

```diff
diff --git a/pkg/machine/shim/volume.go b/pkg/machine/shim/volume.go
index a145f5847..e67e577db 100644
--- a/pkg/machine/shim/volume.go
+++ b/pkg/machine/shim/volume.go
@@ -8,6 +8,9 @@ import (
 func CmdLineVolumesToMounts(volumes []string, volumeType vmconfigs.VolumeMountType) []*vmconfigs.Mount {
        mounts := []*vmconfigs.Mount{}
        for i, volume := range volumes {
+               if volume == "" {
+                       continue
+               }
                var mount vmconfigs.Mount
                tag, source, target, readOnly, _ := vmconfigs.SplitVolume(i, volume)
                switch volumeType {
```

### Have you considered any alternatives?

Manually editing machine config json after machine init.

**Comment by Luap99** [comment]
I thought that was already the case? Or maybe I am just mixing that up with another option for a different command.
But yeah using -v "" to unset all default volumes sounds good.

**Comment by afbjorklund** [comment]
Originally there were no default volumes, for this reason. But it didn't match the Docker experience, so mounting $HOME as added in 4.1... The configuration is hiding in containers.conf (containers(common).

```toml
# Host directories to be mounted as volumes into the VM by default.
# Environment variables like $HOME as well as complete paths are supported for
# the source and destination. An optional third field `:ro` can be used to
# tell the container engines to mount the volume readonly.
#
#volumes = [
#  "$HOME:$HOME",
#]

```

**Comment by arixmkii** [comment]
> The configuration is hiding in containers.conf (containers/common).

Yes, this works as expected, but this is a default for all the machines and the new handling of CLI arguments would be to configure per instance in a more ergonomic way.

> I thought that was already the case?

I checked and it didn't. It created a faulty configuration instead.

```
% podman machine init -v "" test-machine
Looking up Podman Machine image at quay.io/podman/machine-os:5.0 to create VM
Extracting compressed file: test-machine-arm64.raw: done  
Machine init complete
To start your machine run:

	podman machine start test-machine

% cat /Users/user/.config/containers/podman/machine/applehv/test-machine.json 
```

```
{
    "Created": "2024-04-15T12:26:57.753607+03:00",
    "GvProxy": {
        "Debug": false,
        "MTU": 0,
        "LogFile": "",
        "PidFile": "",
        "SSHPort": 0
    },
    "HostUser": {
        "Rootful": false,
        "UID": 501,
        "HostUserModified": false
    },
    "LastUp": "0001-01-01T00:00:00Z",
    "Mounts": [
        {
            "OriginalInput": "",
            "ReadOnly": false,
            "Source": "",
            "Tag": "",
            "Target": "",
            "Type": "virtiofs",
            "VSockNumber": null
        }
    ],
    "Name": "test-machine",
    "Resources": {
        "CPUs": 5,
        "DiskSize": 100,
        "Memory": 2048,
        "USBs": []
    },
    "SSH": {
        "IdentityPath": "/Users/user/.local/share/containers/podman/machine/machine",
        "Port": 54609,
        "RemoteUsername": "core"
    },
    "Version": 1,
    "ImagePath": {
        "Path": "/Users/user/.local/share/containers/podman/machine/applehv/test-machine-arm64.raw"
    },
    "AppleHypervisor": {
        "Vfkit": {
            "LogLevel": "panic",
            "Endpoint": "http://localhost:55555",
            "VfkitBinaryPath": null,
            "VirtualMachine": {
                "vcpus": 5,
                "memoryBytes": 2048,
                "bootloader": {
                    "kind": "efiBootloader",
                    "EFIVariableStorePath": "/Users/user/.local/share/containers/podman/machine/applehv/efi-bl-test-machine",
                    "CreateVariableStore": true
                }
            }
        }
    },
    "Starting": false
}
```

Where mounts are set to 
```
    "Mounts": [
        {
            "OriginalInput": "",
            "ReadOnly": false,
            "Source": "",
            "Tag": "",
            "Target": "",
            "Type": "virtiofs",
            "VSockNumber": null
        }
    ]
```

While it should be `"Mounts": []` for disabled mounts.

**Comment by baude** [comment]
that kind of makes sense to me ... you are logically passing a mount.  we just need to add parsing of the mount to skip it for consideration.

**Comment by baude** [comment]
we are also going to want to verify the ignition file has no mount info in it too

**Comment by arixmkii** [comment]
I will revisit this in the end of May and make a PR.

**Comment by arixmkii** [comment]
Additional action points related to this.
* pass this setting to all e2e tests as right now default machine configuration will initiate default mounts for every tests except specific tests for volume mounts, this doesn't look like a desired behavior, but rather a bug
* do not error machine startup on missing virtiofsd binary if there no volume mounts in the config as there will be no calls to it

Goals: 
* all e2e tests except volume mount related tests should successfully pass for QEMU, when virtiofsd binary is missing in the system
* one should be able to use create and use machine w/o volume mounts for QEMU, when virtiofsd binary is missing
