### ISSUE TITLE
Failed to open file “/home/hamzy/.config/containers/podman/machine/qemu/podman-machine-default.ign”: No such file or directory

### ISSUE THREAD

**Issue by hamzy** [containers/podman#22375]
### Issue Description

podman machine init fails to succeed.

### Steps to reproduce the issue

hamzy:~$ podman machine init
Downloading VM image: fedora-coreos-39.20240407.2.0-qemu.x86_64.qcow2.xz: done
Extracting compressed file
Image resized.
Error: exit status 1

hamzy:~$ podman machine list
NAME                     VM TYPE     CREATED        LAST UP        CPUS        MEMORY      DISK SIZE
podman-machine-default*  qemu        2 minutes ago  2 minutes ago  1           2GiB        100GiB

hamzy:~$ podman machine start podman-machine-default
Starting machine "podman-machine-default"
Waiting for VM ...
Error: qemu exited unexpectedly with exit code 1, stderr: qemu-system-x86_64: -fw_cfg name=opt/com.coreos/config,file=/home/hamzy/.config/containers/podman/machine/qemu/podman-machine-default.ign: can't load /home/hamzy/.config/containers/podman/machine/qemu/podman-machine-default.ign: Failed to open file “/home/hamzy/.config/containers/podman/machine/qemu/podman-machine-default.ign”: No such file or directory

### Describe the results you received

The ignition file
/home/hamzy/.config/containers/podman/machine/qemu/podman-machine-default.ign
is not created

### Describe the results you expected

The ignition file
/home/hamzy/.config/containers/podman/machine/qemu/podman-machine-default.ign
is created

### podman info output

```yaml
hamzy:~$ podman version
Client:       Podman Engine
Version:      4.6.1
API Version:  4.6.1
Go Version:   go1.20.12
Built:        Tue Feb  6 07:04:01 2024
OS/Arch:      linux/amd64

hamzy:~$ podman info
host:
  arch: amd64
  buildahVersion: 1.31.3
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.8-1.module+el8.9.0+21243+a586538b.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.8, commit: 64375b77dc0eda8f5a71b9208e041bc1e36eac81'
  cpuUtilization:
    idlePercent: 92.23
    systemPercent: 2.27
    userPercent: 5.5
  cpus: 16
  databaseBackend: boltdb
  distribution:
    distribution: '"rhel"'
    version: "8.9"
  eventLogger: file
  freeLocks: 2047
  hostname: li-3d08e84c-2e1c-11b2-a85c-e2db7bb078fc.ibm.com
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-513.9.1.el8_9.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 4381495296
  memTotal: 33379540992
  networkBackend: cni
  networkBackendInfo:
    backend: cni
    dns:
      package: podman-plugins-4.6.1-8.module+el8.9.0+21243+a586538b.x86_64
      path: /usr/libexec/cni/dnsname
      version: |-
        CNI dnsname plugin
        version: 1.3.1
        commit: unknown
    package: containernetworking-plugins-1.3.0-8.module+el8.9.0+21243+a586538b.x86_64
    path: /usr/libexec/cni
  ociRuntime:
    name: runc
    package: runc-1.1.12-1.module+el8.9.0+21243+a586538b.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.12
      spec: 1.0.2-dev
      go: go1.20.12
      libseccomp: 2.5.2
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.1-1.module+el8.9.0+21243+a586538b.x86_64
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 30160637952
  swapTotal: 33395044352
  uptime: 2494h 30m 55.00s (Approximately 103.92 days)
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/hamzy/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/hamzy/.local/share/containers/storage
  graphRootAllocated: 476911042560
  graphRootUsed: 155237134336
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 8
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/hamzy/.local/share/containers/storage/volumes
version:
  APIVersion: 4.6.1
  Built: 1707224641
  BuiltTime: Tue Feb  6 07:04:01 2024
  GitCommit: ""
  GoVersion: go1.20.12
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.1
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

### Additional environment details

hamzy:~$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	RedHatEnterprise
Description:	Red Hat Enterprise Linux release 8.9 (Ootpa)
Release:	8.9
Codename:	Ootpa

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
Is there a particular reason you are using podman machine on linux? You can juts use podman natively without the extra VM on linux.

Podman 5.0 was completely rewritten for podman 5.0 so I don't think this bug still exists and we only support the latest version upstream.

Also if you have issues with RHEL it is best to reach out to the Red Hat support channels.
