### ISSUE TITLE
Support system-wide configuration file on Windows too

### ISSUE THREAD

**Issue by l0rd** [containers/podman#22411]
### Feature request description

On Windows, system-wide configuration files, are in `%ProgramData%` whereas user specific configuration files are in `%APPDATA%` or `%LOCALAPPDATA%` ([reference](https://learn.microsoft.com/en-us/windows/win32/shell/knownfolderid)). Currently `podman` ignores configuration files under `%ProgramData%` and only support user specific configuration.

The problem is that, at installation time, the user will be asked to select the machine provider (WSL or Hyper-V). Then a corresponding config file is generated and added in the user config folder. This is problematic if there are other users on the windows machine and [the windows installer complains about that](https://learn.microsoft.com/en-us/windows/win32/msi/ice91).

It would be much better if podman supported configs in Windows system-wide configuration folder.

### Suggest potential solution

In [`config_windows.go`](https://github.com/containers/common/blob/main/pkg/config/config_windows.go): 
- `OverrideContainersConfig` is set to `/etc/containers/containers.conf`
- `DefaultContainersConfig` is set to `/usr/share/containers/containers.conf`

Those paths don't make much sense on Windows. 

We can use a functions to set the paths relative to `%ProgramData%`:

 ```go
func overrideContainersConfigPath() (string, error) {
	return os.Getenv("ProgramData") + "\\containers\\containers.conf", nil
}
```

### Have you considered any alternatives?

Keep the constants but hardcode them to `C:\\ProgramData\\containers\\containers.conf`

**Comment by Luap99** [comment]
@n1hility Any suggestions for a default path?
ProgramData sounds reasonable to me.

**Comment by l0rd** [comment]
> @n1hility Any suggestions for a default path? ProgramData sounds reasonable to me.

@Luap99 apart from the choice of the system wide folder (%ProgramData% seams the easy choice) I would appreciate your's and @n1hility's point of view on those questions:

1) Should we prefer system-wide configuration to user-specific configuration for Podman on Windows? I am thinking in particular about machine related configuration. Note that every user can write in `%ProgramData%`.
2) Should we refactor the constants `OverrideContainersConfig` and `DefaultContainersConfig` as values returned from a function so that we can use `%ProgramData%` to build them on Windows?

**Comment by Luap99** [comment]
> Should we prefer system-wide configuration to user-specific configuration for Podman on Windows? I am thinking in particular about machine related configuration. Note that every user can write in %ProgramData%.

The order should be defined like on windows, first read the global config then the user local config. The later config always can overwrite options from the previous configs so that should work. Not sure how I feel about the fact that every user can write the global path.

> Should we refactor the constants OverrideContainersConfig and DefaultContainersConfig as values returned from a function so that we can use %ProgramData% to build them on Windows?

Sure that is fine if we have to resolve env vars.

**Comment by l0rd** [comment]
Thank you for the feedback @Luap99

**Comment by n1hility** [comment]
+1 to introducing a systemwide location
