### ISSUE TITLE
Use --platform / --arch etc.,  podman will not lookup image shortname

### ISSUE THREAD

**Issue by soiamsoNG** [containers/podman#22420]
### Issue Description

if run/build use --platform / --arch etc,  podman will not lookup shortname already in local with same platform (use podman inspect  output info Architecture/OS),  and prompt user to select registry

if use localhost/shortname  exact as the RepoTags it will work

https://github.com/microsoft/vscode-remote-release/issues/9748

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman build --platform xxxx -f Dockerfile

### Describe the results you received

Prompt select image registry

### Describe the results you expected

same behaviour as without  --platform or --arch
just prompt user select registry when **no**  already build image's platform or arch or os match its **shortname**.

### podman info output

```yaml
podman version 4.9.4
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

**Comment by baude** [comment]
@vrothberg what say you?

**Comment by vrothberg** [comment]
Please share a full reproducer.  Based on the description I am unable to reproduce.

**Comment by soiamsoNG** [comment]
create Dockerfile
```
FROM alpine:latest
CMD ["echo","hello world"]
```

follow below step
1. podman pull docker.io/alpine:latest
2. podman inspect alpine
3. podman --arch amd64 --file Dockerfile  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(the prompt of registry select show up)
4. podman --file Dockerfile                                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (the prompt of registry will not show up)

step 3 and 4 same Dockerfile different behavior

**Comment by rhatdan** [comment]
podman build --arch amd64 --file Dockerfile      (the prompt of registry select show up)
podman build --file Dockerfile       (the prompt of registry will not show up)

I think  you meant, this looks like it might be the same issue as:


https://github.com/containers/buildah/pull/5478

**Comment by soiamsoNG** [comment]
`--platform linux/amd64`  not fix the issue ,the prompt of registry select show up

**Comment by vrothberg** [comment]
It works exactly as designed.  Once you have selected an image and it's pulled down, the selection is being recorded.

See https://www.redhat.com/sysadmin/container-image-short-names for details on the behavior.

**Comment by soiamsoNG** [comment]
maybe you miss understand, step 3 and step 4 can be exchange the order, and same difference behavior. 
step 1 , step 2 , step 4 never give us any select prompt.

**Comment by vrothberg** [comment]
Which system are you running on? If there's a recorded alias, there will be no prompt.

**Comment by soiamsoNG** [comment]
fedora 39, podman version 4.9.4, 

the post you provide said below but I never find this file
`Podman will automatically record a new short-name alias in the users $HOME/.config/containers/short-name-aliases.conf file`

and please take a detail look at below workaround for this issue, it still will search local/localbuildimage but not at the first, it prompt first if there is more than one registry even with local match.
https://github.com/microsoft/vscode-remote-release/issues/9748#issuecomment-2049238258

May be this issue title not match the exact issue. may be **re-title to will not lookup local image first**.

**Comment by vrothberg** [comment]
Fedora 39 ships with `/etc/containers/registries.conf.d/000-shortnames.conf` which has an alias for `alpine`, so pulling this image will never show a prompt.

> and please take a detail look at below workaround for this issue, it still will search local/localbuildimage but not at the first, it prompt first if there is more than one registry even with local match.
https://github.com/microsoft/vscode-remote-release/issues/9748#issuecomment-2049238258

I need an exact reproducer.  Sorry, I am a bit lost in what the problem is.

I am sure we'll get to the bottom of the issue.

**Comment by soiamsoNG** [comment]
Just update to fedora 40, podman version 5.0.1

find alpine in /etc/containers/registries.conf.d/000-shortnames.conf

Sorry can't let you you get to reproducer I refind the step description to below

make sure more than one registry by below command
```
podman info -f json | jq '.registries["search"]'
```

Dockerfile
```
FROM alpine:latest
CMD ["echo","hello world"]
```

Dockerfile2
```
FROM localalpine:latest
CMD ["echo","hello world2"]
```



prompt will not come out with below step (I think it can find image **localalpine** )
```
podman pull alpine:latest
podman build --file Dockerfile -t localalpine
podman build --file Dockerfile2 -t locallocalalpine
```
prompt will show at the third step of below (don't know why image **localalpine** alreay in local and prompt show  behavior not as above three step, but you can force it to fallback to use local image by limit remote registry to only one)
```
podman pull alpine:latest
podman build --file Dockerfile -t localalpine
podman build --arch amd64 --file Dockerfile2 -t locallocalalpine
```
