### ISSUE TITLE
mkcomposefs: Invalid Integer

### ISSUE THREAD

**Issue by engelmi** [containers/podman#22422]
### Issue Description

The `composefs` backend in podman causes build failures after the images built:
```
mkcomposefs: Invalid integer 628
Error: creating build container: committing the finished image: failed to put layer using a partial pull: failed to convert json to erofs: exit status 1
```

### Steps to reproduce the issue

On Fedora Rawhide install:
```bash
dnf install \
        podman \
        python3-dasbus \
        python3-paramiko \
        python3-podman \
        python3-pytest \
        python3-pyyaml \
        -y
```
__Note:__ `podman-5:5.0.1-1.fc41` and `composefs-1.0.3-1.fc40` should be installed.

And build the BlueChi test container:
```bash
git clone https://github.com/eclipse-bluechi/bluechi.git
cd bluechi
podman build --build-arg copr_repo=@centos-automotive-sig/bluechi-snapshot -f ./tests/containers/integration-test-snapshot -t bluechi-image .
```

### Describe the results you received

The `podman build` command fails due to mkcomposefs. For example (output from a CI run):

err: + podman build --build-arg copr_repo=packit/eclipse-bluechi-bluechi-885 -f ./containers/integration-test-snapshot -t bluechi-image .
out: STEP 1/7: FROM quay.io/bluechi/integration-test-base:latest
err: Trying to pull quay.io/bluechi/integration-test-base:latest...
err: Getting image source signatures
err: Copying blob sha256:97a053fecd3c8cdab88960e03c87ffe33b8a531ee55410760f35604e74b0c0ee
err: Copying blob sha256:c62973d79fbf6833d2fff68328f197d33941113b1007b4b5e001546b081b7ed6
err: Copying config sha256:0547cac6361658f4ab58fdb7eaedcdff38e4bb0f9e5e0f03c6ffd1639f799f5b
err: Writing manifest to image destination
err: mkcomposefs: Invalid integer 628
err: 
err: Error: creating build container: committing the finished image: failed to put layer using a partial pull: failed to convert json to erofs: exit status 1

### Describe the results you expected

The successfully built image. 

### podman info output

```yaml
Podman Version: 5:5.0.1-1.fc41
OS: Fedora Rawhide x86_64
```

### Podman in a container

Yes

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

Running on testing farm. Example run:
https://artifacts.dev.testing-farm.io/d9b2d2b0-ff99-480f-8cfe-cc749b233c52/
https://artifacts.dev.testing-farm.io/d9b2d2b0-ff99-480f-8cfe-cc749b233c52/work-containerlzi7uhh4/log.txt
(seems to run in a container)

### Additional information

---

**Comment by giuseppe** [comment]
fixed by https://github.com/containers/storage/pull/1895
