### ISSUE TITLE
quadlet does not generate service from .container files in `/etc/containers/systemd/` on boot

### ISSUE THREAD

**Issue by Coachonko** [containers/podman#22430]
### Issue Description

On 4.6.1 (el9.3) my quadlet .container definition is not being read on reboot.

The following definition is parsed correctly with `/usr/libexec/podman/quadlet -dryrun`, a service is correctly generated with `systemctl daemon-reload`. This service can be started correctly too. However, it is not read automatically after a system restart, and therefore it is not run automatically.

```config
[Unit]
Description=Redis container

[Container]
Image=docker.io/redis
PublishPort=6379:6379
User=999

[Service]
Restart=always

[Install]
WantedBy=local.target
```

I have seen #20660 but in my case, there is a single partition and it can't be a file system race mounting condition situation.

### Steps to reproduce the issue

Steps to reproduce the issue
1. symlink the container file to /etc/containers/systemd
2. `systemctl daemon-reload` and start the generated service
3. reboot system

### Describe the results you received

`systemctl daemon-reload` generates the service and it can be started no problem.
On reboot: 
```
systemctl status my-app
Unit my-app.service could not be found.
```

### Describe the results you expected

Service is created and started on reboot.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.31.3
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.8-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.8, commit: 8aa778a2fdb2df7c8cf9516fceda0ae1789b40b3'
  cpuUtilization:
    idlePercent: 95.1
    systemPercent: 1.56
    userPercent: 3.34
  cpus: 8
  databaseBackend: boltdb
  distribution:
    distribution: '"rhel"'
    version: "9.3"
  eventLogger: journald
  freeLocks: 2048
  hostname: 4790K
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.0-362.24.1.el9_3.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 26644992000
  memTotal: 33242198016
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.7.0-1.el9.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.7.0
    package: netavark-1.7.0-2.el9_3.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.7.0
  ociRuntime:
    name: crun
    package: crun-1.8.7-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.8.7
      commit: 53a9996ce82d1ee818349bdcc64797a1fa0433c4
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20230818.g0af928e-4.el9.x86_64
    version: |
      pasta 0^20230818.g0af928e-4.el9.x86_64
      Copyright Red Hat
      GNU Affero GPL version 3 or later <https://www.gnu.org/licenses/agpl-3.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.1-1.el9.x86_64
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 34359734272
  swapTotal: 34359734272
  uptime: 0h 25m 18.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/coachonko/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/coachonko/.local/share/containers/storage
  graphRootAllocated: 549487378432
  graphRootUsed: 39412776960
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 15
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/coachonko/.local/share/containers/storage/volumes
version:
  APIVersion: 4.6.1
  Built: 1709815759
  BuiltTime: Thu Mar  7 13:49:19 2024
  GitCommit: ""
  GoVersion: go1.20.10
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.1
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Coachonko** [comment]
I gave up.

**Comment by rhatdan** [comment]
We have seen issues with apps failing because the start before the network stack is up.  If you added requirements to make sure the network stack is up, your redis server might work better.

**Comment by ygalblum** [comment]
I was able to reproduce this issue with both `4.6.1` and `4.9.4` and it does seem related to the symlink. 

I'm looking into this issue, but fixes will only be part of future versions. So, for `4.6.x` the solution is not to use symlinks.

**Comment by ygalblum** [comment]
@Coachonko Are you sure that manually running `systemctl daemon-reload` generates the service? For me it does not work when the symlink is in `/etc/containers/systemd`

**Comment by ygalblum** [comment]
After further testing, I found that the success or failure of the procedure does depend on the location of the actual file and only for system services.
When the actual file was under `/tmp` and linked from `/etc/containers/systemd`, Quadlet failed to open the file resulting in `open /etc/containers/systemd/test-redis.container: no such file or directory` (I had to make some changes to the code to see the print). However, storing the file under `~/tmp/` with a similar symlink worked.
Can you please elaborate on where the actual file is stored?

**Comment by Coachonko** [comment]
Thank you for trying to reproduce the issue, I had already given up, I do not have the project set up any longer so I cannot attempt to repro it any more.
The file used to be in my user's home dir, in this exact path: `/home/coachonko/Documents/projects/containers/deploy/nginx.container`
I did do a symbolic link of the `nginx.container` file to the `/etc/containers/systemd/` directory.
`systemctl daemon-reload` did generate the service.

If I will need to use containers again on this version of podman I will use hard file copies and stay away from symbolic links.
