### ISSUE TITLE
Add a pull policy of AlwaysIfPossible to better cope with transient network issues

### ISSUE THREAD

**Issue by ericzolf** [containers/podman#22454]
### Feature request description

Looking more and more at edge use cases, network availability isn't a given. On the other hand, you might want to make sure that you've always got the latest version of a container image, without endangering the availability of the service it provides.

### Suggest potential solution

Provide an "AlwaysIfPossible" pull policy, which would always try to pull a new version of the image, but instead of failing if something goes wrong while downloading, would simply ignore it and continue the current action using the previously available version of the image.

### Have you considered any alternatives?

Add some more logic around the podman command, but as the pull policies provided by podman are used in upper level tools like ansible-navigator or AWX (or even K8S), implementing it directly in podman would make more sense so that all tools can profit from it.

### Additional context

A timeout parameter could make sense to ensure that the service provided by the container isn't unavailable for too long, for example in cases where the network isn't completely broken but just too slow.

**Comment by vrothberg** [comment]
Thanks for reaching out, @ericzolf.

The "Newer" pull policy does what you need, I believe.  It will pull down the image if there's a more recent one available.  If there's an error pulling the image, it will be ignored and the local image will be used.

**Comment by vrothberg** [comment]
See the docs of "newer": https://docs.podman.io/en/latest/markdown/podman-create.1.html#pull-policy

**Comment by ericzolf** [comment]
Ups, I'm ashamed of having overseen this. I see that ansible-navigator doesn't support it, I was under the (wrong?!) impression that it was just passing on the parameter. Something for the Ansible colleagues to fix :smirk:. Thanks, closing!
