### ISSUE TITLE
Podman 5.x stable image unavailable on quay.io

### ISSUE THREAD

**Issue by libfitz** [containers/podman#22475]
### Feature request description

The Podman organization on quay.io is missing Podman 5.x images in the podman/stable repository. At the moment only quay.io/podman/upstream:latest seems to be built for 5.x

### Suggest potential solution

Podman 5.x images should be available at quay.io/podman/{stable,testing,...}

### Have you considered any alternatives?

n/a

### Additional context

n/a

**Comment by Luap99** [comment]
The stable image is based on fedora so it only gets updated to 5.0 when the update lands in the stable fedora version, as fedora 40 was just released today this should happen very soon.

**Comment by baude** [comment]
i checked and stable now has 5.0.1 in it.  closing as such.
