### ISSUE TITLE
podman + latest c-storage: thinpool throws a warning

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#22473]
With latest c-storage:
```console
$ bin/podman pull -q quay.io/libpod/testimage:20240123
WARN[0000] Failed to decode the keys ["storage.options.thinpool"] from "/usr/share/containers/storage.conf" 
1f6acd4c4a1d4d39395870e1c12dbb68da27dd432afecf86e7cb6e23cf4b75d0
```

**Comment by edsantiago** [comment]
I would humbly suggest that a better solution would be to fix storage.conf **first**, then wait for it to distribute everywhere that podman can possibly run, and then settle, and **then** remove thinpool from podman.

**Comment by Luap99** [comment]
FYI: thinpool was never part of podman (well not for years)

**Comment by edsantiago** [comment]
Sorry, I misspoke due to haste.

As a podman user, I am not likely to know or care what thinpool is. If I upgrade podman, maybe on some distro that is not 100% careful about bumping c-common, I will see the above warning and I will waste time worrying about it. Multiply by hundreds or thousands of users.

I would like to encourage our team to take steps such that no user ever sees this warning. (Possible exception for someone with a custom `/etc` file, but even then it should say "that block of settings has not worked for a long time, please remove everything from `[storage.options.thinpool]` to the next bracketed section".)

**Comment by rhatdan** [comment]
Rawhide should have it removed now.  We could tone down containers/storage verifying its storage.conf file, but that could lead to people adding bad settings and not knowing they have typos in storage.conf files.
