### ISSUE TITLE
Quadlet --privileged option is missing

### ISSUE THREAD

**Issue by lehmanju** [containers/podman#22487]
### Feature request description

Right now quadlets do not support running a container in `privileged` mode. With `podman run` there is a flag `--privileged` that can be used to run a container with elevated right and allow it to access `/sys/*` paths.

My use case is running `tuned` in a container but since it requires setting all kinds of kernel configuration options it only runs reliably in `privileged` mode.

### Suggest potential solution

Add an option to the quadlet specification that allows running a container in `privileged` mode. Should suffice to make it a simple boolean option that enables the `--privileged` flag on `podman run`.

### Have you considered any alternatives?

I have tried to achieve the same with plain `security-opt label=disable` but with no success.

### Additional context

Running Fedora CoreOS and trying to save power by using `tuned`. Since layering is discouraged I tried running it in a container, which works great with the following command: `sudo podman run -it --privileged --rm ghcr.io/lehmanju/containers/tuned:latest -p powersave --no-dbus`. Now putting it in a quadlet and adding it to my server configuration would be great.

**Comment by rhatdan** [comment]
Unmask=all
SecurityLabelDisable=true 
AddCapability=all
SeccompProfile=unconfined

Or you can do

PodmanArgs=--privileged

**Comment by lehmanju** [comment]
Aw man, thanks for the hint to `PodmanArgs`. That helps a lot.
