### ISSUE TITLE
podman v4 is fetching podman v5 and it's not compliant on macOS

### ISSUE THREAD

**Issue by benoitf** [containers/podman#22517]
### Issue Description

if you have podman v4 installed on macOS for example the latest `4.9.4`

if you create a podman machine, it'll fetch a machine that is not compliant with your current podman CLI version

### Steps to reproduce the issue

Steps to reproduce the issue
1. install podman 4.9.4
2. do `podman machine init`
3. run a container like `podman run httpd`

### Describe the results you received

 podman run httpd                                                                                                                                                                                       ✔  54s 
Resolving "httpd" using unqualified-search registries (/etc/containers/registries.conf.d/999-podman-machine.conf)
Trying to pull docker.io/library/httpd:latest...
Getting image source signatures
Copying blob sha256:bae159c85a0b3662b8e9d58344f7da1b84836a7338c8ddf6b88360cea400929f
Copying blob sha256:855b568ab02c3fee1362d51176f966517b1e03ca0c8efde55eddace90835f300
Copying blob sha256:22d97f6a5d13532e867231d23d92620a81874d51a456196be50154eeb32edc08
Copying blob sha256:98c8bced82bd1d3557a49d39ea03bb8090bf3abc8154ab65388d9f9728f3ce02
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Copying blob sha256:c521cc2c4e8a439951003122cdab841fe1b1350db864e2cf9dea69298513f711
Copying config sha256:73acb239a8eb7a9ef5b6848a5b01bb26cc03d2262056705876bf7ac6ad781f02
Writing manifest to image destination
Error: unmarshalling into &define.InspectContainerData{ID:"48f4a3afb8d290ff3068a18e248d1628a18a9321a3ca4cdbc391fd46eba1ffaa", Created:time.Date(2024, time.April, 26, 15, 8, 56, 97196689, time.Local), Path:"httpd-foreground", Args:[]string{"httpd-foreground"}, State:(*define.InspectContainerState)(0x14000686640), Image:"73acb239a8eb7a9ef5b6848a5b01bb26cc03d2262056705876bf7ac6ad781f02", ImageDigest:"sha256:36c8c79f900108f0f09fd4148ad35ade57cba0dc19d13f3d15be24ce94e6a639", ImageName:"docker.io/library/httpd:latest", Rootfs:"", Pod:"", ResolvConfPath:"", HostnamePath:"", HostsPath:"", StaticDir:"/var/home/core/.local/share/containers/storage/overlay-containers/48f4a3afb8d290ff3068a18e248d1628a18a9321a3ca4cdbc391fd46eba1ffaa/userdata", OCIConfigPath:"", OCIRuntime:"crun", ConmonPidFile:"/run/user/501/containers/overlay-containers/48f4a3afb8d290ff3068a18e248d1628a18a9321a3ca4cdbc391fd46eba1ffaa/userdata/conmon.pid", PidFile:"/run/user/501/containers/overlay-containers/48f4a3afb8d290ff3068a18e248d1628a18a9321a3ca4cdbc391fd46eba1ffaa/userdata/pidfile", Name:"optimistic_ganguly", RestartCount:0, Driver:"overlay", MountLabel:"system_u:object_r:container_file_t:s0:c53,c832", ProcessLabel:"system_u:system_r:container_t:s0:c53,c832", AppArmorProfile:"", EffectiveCaps:[]string{"CAP_CHOWN", "CAP_DAC_OVERRIDE", "CAP_FOWNER", "CAP_FSETID", "CAP_KILL", "CAP_NET_BIND_SERVICE", "CAP_SETFCAP", "CAP_SETGID", "CAP_SETPCAP", "CAP_SETUID", "CAP_SYS_CHROOT"}, BoundingCaps:[]string{"CAP_CHOWN", "CAP_DAC_OVERRIDE", "CAP_FOWNER", "CAP_FSETID", "CAP_KILL", "CAP_NET_BIND_SERVICE", "CAP_SETFCAP", "CAP_SETGID", "CAP_SETPCAP", "CAP_SETUID", "CAP_SYS_CHROOT"}, ExecIDs:[]string{}, GraphDriver:(*define.DriverData)(0x14000116d20), SizeRw:(*int64)(nil), SizeRootFs:0, Mounts:[]define.InspectMount{}, Dependencies:[]string{}, NetworkSettings:(*define.InspectNetworkSettings)(0x140005fbb00), Namespace:"", IsInfra:false, IsService:false, KubeExitCodePropagation:"invalid", LockNumber:0x0, Config:(*define.InspectContainerConfig)(0x1400021a780), HostConfig:(*define.InspectContainerHostConfig)(0x14000108c08)}, data "{\"Id\":\"48f4a3afb8d290ff3068a18e248d1628a18a9321a3ca4cdbc391fd46eba1ffaa\",\"Created\":\"2024-04-26T15:08:56.097196689+02:00\",\"Path\":\"httpd-foreground\",\"Args\":[\"httpd-foreground\"],\"State\":{\"OciVersion\":\"1.2.0\",\"Status\":\"created\",\"Running\":false,\"Paused\":false,\"Restarting\":false,\"OOMKilled\":false,\"Dead\":false,\"Pid\":0,\"ExitCode\":0,\"Error\":\"\",\"StartedAt\":\"0001-01-01T00:00:00Z\",\"FinishedAt\":\"0001-01-01T00:00:00Z\",\"CheckpointedAt\":\"0001-01-01T00:00:00Z\",\"RestoredAt\":\"0001-01-01T00:00:00Z\"},\"Image\":\"73acb239a8eb7a9ef5b6848a5b01bb26cc03d2262056705876bf7ac6ad781f02\",\"ImageDigest\":\"sha256:36c8c79f900108f0f09fd4148ad35ade57cba0dc19d13f3d15be24ce94e6a639\",\"ImageName\":\"docker.io/library/httpd:latest\",\"Rootfs\":\"\",\"Pod\":\"\",\"ResolvConfPath\":\"\",\"HostnamePath\":\"\",\"HostsPath\":\"\",\"StaticDir\":\"/var/home/core/.local/share/containers/storage/overlay-containers/48f4a3afb8d290ff3068a18e248d1628a18a9321a3ca4cdbc391fd46eba1ffaa/userdata\",\"OCIRuntime\":\"crun\",\"ConmonPidFile\":\"/run/user/501/containers/overlay-containers/48f4a3afb8d290ff3068a18e248d1628a18a9321a3ca4cdbc391fd46eba1ffaa/userdata/conmon.pid\",\"PidFile\":\"/run/user/501/containers/overlay-containers/48f4a3afb8d290ff3068a18e248d1628a18a9321a3ca4cdbc391fd46eba1ffaa/userdata/pidfile\",\"Name\":\"optimistic_ganguly\",\"RestartCount\":0,\"Driver\":\"overlay\",\"MountLabel\":\"system_u:object_r:container_file_t:s0:c53,c832\",\"ProcessLabel\":\"system_u:system_r:container_t:s0:c53,c832\",\"AppArmorProfile\":\"\",\"EffectiveCaps\":[\"CAP_CHOWN\",\"CAP_DAC_OVERRIDE\",\"CAP_FOWNER\",\"CAP_FSETID\",\"CAP_KILL\",\"CAP_NET_BIND_SERVICE\",\"CAP_SETFCAP\",\"CAP_SETGID\",\"CAP_SETPCAP\",\"CAP_SETUID\",\"CAP_SYS_CHROOT\"],\"BoundingCaps\":[\"CAP_CHOWN\",\"CAP_DAC_OVERRIDE\",\"CAP_FOWNER\",\"CAP_FSETID\",\"CAP_KILL\",\"CAP_NET_BIND_SERVICE\",\"CAP_SETFCAP\",\"CAP_SETGID\",\"CAP_SETPCAP\",\"CAP_SETUID\",\"CAP_SYS_CHROOT\"],\"ExecIDs\":[],\"GraphDriver\":{\"Name\":\"overlay\",\"Data\":{\"LowerDir\":\"/var/home/core/.local/share/containers/storage/overlay/e652c896c118b3283988502a6b98ab28e4afeacd29161465d37a7f03e04a5cb2/diff:/var/home/core/.local/share/containers/storage/overlay/aff6eda49bd7b7f1dfa45552fc21b42902605a6c3ae11159010155d2b0a00a76/diff:/var/home/core/.local/share/containers/storage/overlay/c4e4361abad41c669082fdfb93710eb07cb7e5363b8676015f97a9dcafb79d76/diff:/var/home/core/.local/share/containers/storage/overlay/9612a6c52f07c9ff3ff2ee0a1ff5317d09bfdc65c5c8b0e67a1ca2a00b7a0a7e/diff:/var/home/core/.local/share/containers/storage/overlay/212354c052eefe0cfa4c3951d75e076b8910026d78fbee00b548b3803ff48c41/diff:/var/home/core/.local/share/containers/storage/overlay/8560597d922ca8edaeea533c482a61b9cd840e55ae55cedd31b0087547e2933d/diff\",\"UpperDir\":\"/var/home/core/.local/share/containers/storage/overlay/bbe2532c44ebd7e2092186fd23bf4239c9312c17516b3f5dfdd77664f7f49cc8/diff\",\"WorkDir\":\"/var/home/core/.local/share/containers/storage/overlay/bbe2532c44ebd7e2092186fd23bf4239c9312c17516b3f5dfdd77664f7f49cc8/work\"}},\"Mounts\":[],\"Dependencies\":[],\"NetworkSettings\":{\"EndpointID\":\"\",\"Gateway\":\"\",\"IPAddress\":\"\",\"IPPrefixLen\":0,\"IPv6Gateway\":\"\",\"GlobalIPv6Address\":\"\",\"GlobalIPv6PrefixLen\":0,\"MacAddress\":\"\",\"Bridge\":\"\",\"SandboxID\":\"\",\"HairpinMode\":false,\"LinkLocalIPv6Address\":\"\",\"LinkLocalIPv6PrefixLen\":0,\"Ports\":{\"80/tcp\":null},\"SandboxKey\":\"\",\"Networks\":{\"podman\":{\"EndpointID\":\"\",\"Gateway\":\"\",\"IPAddress\":\"\",\"IPPrefixLen\":0,\"IPv6Gateway\":\"\",\"GlobalIPv6Address\":\"\",\"GlobalIPv6PrefixLen\":0,\"MacAddress\":\"\",\"NetworkID\":\"podman\",\"DriverOpts\":null,\"IPAMConfig\":null,\"Links\":null,\"Aliases\":[\"48f4a3afb8d2\"]}}},\"Namespace\":\"\",\"IsInfra\":false,\"IsService\":false,\"KubeExitCodePropagation\":\"invalid\",\"lockNumber\":0,\"Config\":{\"Hostname\":\"48f4a3afb8d2\",\"Domainname\":\"\",\"User\":\"\",\"AttachStdin\":false,\"AttachStdout\":false,\"AttachStderr\":false,\"Tty\":false,\"OpenStdin\":false,\"StdinOnce\":false,\"Env\":[\"PATH=/usr/local/apache2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin\",\"container=podman\",\"HTTPD_VERSION=2.4.59\",\"HTTPD_SHA256=ec51501ec480284ff52f637258135d333230a7d229c3afa6f6c2f9040e321323\",\"HTTPD_PATCHES=\",\"HTTPD_PREFIX=/usr/local/apache2\"],\"Cmd\":[\"httpd-foreground\"],\"Image\":\"docker.io/library/httpd:latest\",\"Volumes\":null,\"WorkingDir\":\"/usr/local/apache2\",\"Entrypoint\":null,\"OnBuild\":null,\"Labels\":null,\"Annotations\":null,\"StopSignal\":\"SIGWINCH\",\"HealthcheckOnFailureAction\":\"none\",\"CreateCommand\":[\"podman\",\"run\",\"httpd\"],\"Umask\":\"0022\",\"Timeout\":0,\"StopTimeout\":10,\"Passwd\":true,\"sdNotifyMode\":\"container\"},\"HostConfig\":{\"Binds\":[],\"CgroupManager\":\"systemd\",\"CgroupMode\":\"private\",\"ContainerIDFile\":\"\",\"LogConfig\":{\"Type\":\"journald\",\"Config\":null,\"Path\":\"\",\"Tag\":\"\",\"Size\":\"0B\"},\"NetworkMode\":\"bridge\",\"PortBindings\":{},\"RestartPolicy\":{\"Name\":\"\",\"MaximumRetryCount\":0},\"AutoRemove\":false,\"VolumeDriver\":\"\",\"VolumesFrom\":null,\"CapAdd\":[],\"CapDrop\":[],\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":[],\"GroupAdd\":[],\"IpcMode\":\"shareable\",\"Cgroup\":\"\",\"Cgroups\":\"default\",\"Links\":null,\"OomScoreAdj\":0,\"PidMode\":\"private\",\"Privileged\":false,\"PublishAllPorts\":false,\"ReadonlyRootfs\":false,\"SecurityOpt\":[],\"Tmpfs\":{},\"UTSMode\":\"private\",\"UsernsMode\":\"\",\"ShmSize\":65536000,\"Runtime\":\"oci\",\"ConsoleSize\":[0,0],\"Isolation\":\"\",\"CpuShares\":0,\"Memory\":0,\"NanoCpus\":0,\"CgroupParent\":\"user.slice\",\"BlkioWeight\":0,\"BlkioWeightDevice\":null,\"BlkioDeviceReadBps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteIOps\":null,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuRealtimePeriod\":0,\"CpuRealtimeRuntime\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"Devices\":[],\"DiskQuota\":0,\"KernelMemory\":0,\"MemoryReservation\":0,\"MemorySwap\":0,\"MemorySwappiness\":0,\"OomKillDisable\":false,\"PidsLimit\":0,\"Ulimits\":[],\"CpuCount\":0,\"CpuPercent\":0,\"IOMaximumIOps\":0,\"IOMaximumBandwidth\":0,\"CgroupConf\":null}}\n": json: cannot unmarshal string into Go struct field InspectContainerConfig.Config.StopSignal of type uint

### Describe the results you expected

podman machine being a v4 machine

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by benoitf** [comment]
a current workaround is to do `podman machine init --image-path stable podman-machine-default` as it fetches FCOS 39 rather than FCOS 40 (or upgrade to podman v5)

**Comment by Luap99** [comment]
v4 is no longer supported by us, we just pull FCOS so there is no way for us to fix this in a meaningful way.

That is why v5 uses the new approach to match client and server by default so this should not be a issue for future bumps.

cc @baude

**Comment by odockal** [comment]
I believe that we at least should notify users about this problem and outline a way out if they want to stay on v4 until moving out to v5. Atm, it stops working without any action from their side.

**Comment by baude** [comment]
We have no control of the FCOS images in v4.  There is nothing that can be done to prevent this.  This is why it is different for v5.  v4 is no longer supported as was said.
