### ISSUE TITLE
Mac - Podman Machine - and Quadlets

### ISSUE THREAD

**Issue by Nitrousoxide** [containers/podman#22524]
### Is your enhancement related to a problem? Please describe

Podman quadlet ([systemd unit](https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html)) has a few search paths:
```
Rootful:
    /etc/containers/systemd/
    /usr/share/containers/systemd/
Rootless:
    $XDG_CONFIG_HOME/containers/systemd/ or ~/.config/containers/systemd/
    /etc/containers/systemd/users/$(UID)
    /etc/containers/systemd/users/
```
However none of these paths are normally mounted into the podman machine when it created from somewhere on the host.  This forces the user to `podman machine ssh` into the podman machine and manually create and add any quadlets they want and then refresh the systemd daemon.

### Describe the solution you'd like

Mounting the host's `~/.config/containers/systemd/` into the podman machine along the same path would allow persistent systemd quadlets to be created on the host and persist into the podman machine with it seeing them as soon as it starts up and spinning up those services.  It would also survive the machine being recreated.

This path may not exist at the time podman is installed on the host's machine so it will need to be created.  This path would also exist in `/Users/$USERNAME/.config/containers/systemd/` on the podman machine, but I don't think it existing in two places would be terribly troublesome.

Edit:
Something to note.  The current coreos podman machine has some example service files for enabling lingering in `~/.config/systemd/user/` and below.  These may need to be blown out if they are not necessary to avoid potential conflicts with the host's version of that `~/.config/systemd/`

### Describe alternatives you've considered

Alternatively perhaps the quadlet component of podman could be updated itself with new search paths that could be compatible for the existing mounts.  I don't think this is ideal however.

**Comment by benoitf** [comment]
transferring the issue to podman repository

**Comment by Luap99** [comment]
systemd generators run very early at boot even before some filesystems are mounted so I am not sur eif this would even work reliably. For apple with viriofs mounts it might work but for all the other mounts the answer is most likely it will not work as they depend on the networking to be fully setup which is far later.

So I don't think this is a good idea and they should be added in the machine fs directly.

**Comment by Nitrousoxide** [comment]
> systemd generators run very early at boot even before some filesystems are mounted so I am not sur eif this would even work reliably. For apple with viriofs mounts it might work but for all the other mounts the answer is most likely it will not work as they depend on the networking to be fully setup which is far later.
> 
> So I don't think this is a good idea and they should be added in the machine fs directly.

If that's an issue it shouldn't be difficult to just define a systemd service in the coreos vm's ignition to do a quick `systemctl --user daemon-reload` after mounts are complete.

**Comment by Luap99** [comment]
> > systemd generators run very early at boot even before some filesystems are mounted so I am not sur eif this would even work reliably. For apple with viriofs mounts it might work but for all the other mounts the answer is most likely it will not work as they depend on the networking to be fully setup which is far later.
> > So I don't think this is a good idea and they should be added in the machine fs directly.
> 
> If that's an issue it shouldn't be difficult to just define a systemd service in the coreos vm's ignition to do a quick `systemctl --user daemon-reload` after mounts are complete.

It is not that easy, yes it will generate the new units but if they are setup to be started on boot then they won't trigger if they are added later AFAIK so this would make them quite useless.

**Comment by Luap99** [comment]
I don't think we can provide a mount by default to make it work properly in all scenarios. You can always add you own mounts to on podman machine init if you want that.
