### ISSUE TITLE
Outdated documentation: slirp4netns vs pasta

### ISSUE THREAD

**Issue by lahwaacz** [containers/podman#22543]
### Issue Description

[podman-network.1.md](https://github.com/containers/podman/blob/108d2bc430eb77fb77a94f623925c34960d286f9/docs/source/markdown/podman-network.1.md#slirp4netns) says that slirp4netns is the default network program for rootless containers.

However, [containers.conf.5.md](https://github.com/containers/common/blob/ead8bddbad08b53b21e4e04a1fdc53da4935a63e/docs/containers.conf.5.md#network-table) has `default_rootless_network_cmd="pasta"` by default.

### Steps to reproduce the issue

Read the latest man pages :smile: 

### Describe the results you received

Outdated documentation

### Describe the results you expected

Documentation should be up to date

### podman info output

```yaml
(irrelevant)
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
Contributions welcome

**Comment by radar07** [comment]
@Luap99 Can I work on this?

**Comment by Luap99** [comment]
@radar07 sure

**Comment by radar07** [comment]
@Luap99 I wonder if we have to write a brief description about `pasta` as the default rootless network in place of `slirp4netns` in the man page. Do you have any suggestions?

**Comment by Luap99** [comment]
Yes that would be good, pasta works a bit differently so adding it there would be good. Maybe the pasta section here could serve as a string point: https://blog.podman.io/2024/03/podman-5-0-breaking-changes-in-detail/

The default is also wrong in https://github.com/containers/podman/blob/main/docs/source/markdown/options/network.md

**Comment by radar07** [comment]
@Luap99, Thanks for letting me know. I created a PR with few changes that might get this done. Also, please let me know if you have any other suggestions.
