### ISSUE TITLE
Let netfilter handle NAT

### ISSUE THREAD

**Issue by uenokatsura** [containers/podman#22542]
### Feature request description

Just as the title, I wish NAT can be done by nftables(netfilter).

I want this feature for the current NAT, NAT66 to be more specific, having some problem when special routing policy is set.

Here's a quick reproduce:

0.  A bridge podman network with IPv6 enabled. A interface **Tunnel0** with **Addr0**. A dummy interface with **Addr1**
1.  **$ ip -6 route add 2620:fe::11 dev Tunnel0 src Addr1** on host.
2.  Ping 2620:fe::11 in container with the bridge network.
3.  Wireshark will show the ICMPv6 packet with **source address Addr0 instead of Addr1** which is asked by the routing rule.

If switching to netfiltet NAT, the problem can be resolved as netfilter correctly SNAT to Addr1.

**Comment by Luap99** [comment]
Can be more specific, what rules are you talking about. Podman doesn't manage any firewall rules that is done by netavark. And netavark create normal NAT rules, assuming you use iptables-nft it should already be translated ruleset otherwise we recently added a direct nftables driver. Try using `export NETAVARK_FW=nftables` and then run podman and have a look if the rules look good to you

**Comment by uenokatsura** [comment]
> Can be more specific, what rules are you talking about. 

I mean route with SRC set. Cause on my machine(Debian Testing), netavark seems to just ignore the SRC value and SNAT to address on the outbound interface.
```nft ruleset
table ip6 nat { # handle 16
        chain NETAVARK-0D76D767645F0 { # handle 1
                ip6 daddr fdc0:a8::/32 counter packets 0 bytes 0 accept # handle 2
                ip6 daddr != ff00::/8 counter packets 229 bytes 23168 # Warning: XT target MASQUERADE not found
xt target "MASQUERADE" # handle 3
        }

        chain POSTROUTING { # handle 4
                type nat hook postrouting priority srcnat; policy accept;
                counter packets 95951 bytes 20871486 jump NETAVARK-HOSTPORT-MASQ # handle 11
                ip6 saddr fdc0:a8::/32 counter packets 288 bytes 29007 jump NETAVARK-0D76D767645F0 # handle 5
        }

        chain NETAVARK-HOSTPORT-SETMARK { # handle 6
                counter packets 0 bytes 0 meta mark set mark or 0x2000 # handle 9
        }

        chain NETAVARK-HOSTPORT-MASQ { # handle 7
                 meta mark & 0x00002000 == 0x00002000 counter packets 0 bytes 0 # Warning: XT target MASQUERADE not found
xt target "MASQUERADE" # handle 10
        }

        chain NETAVARK-HOSTPORT-DNAT { # handle 8
        }
…
}
```
The old iptables-nft rule. which doesn’t seems to really handle the SNAT.

> export NETAVARK_FW=nftables

Thanks. Can confirm it’s working properly with nf masquerade on latest 5.0.2 .
Though my current distro is on 4.9.3 .
