### ISSUE TITLE
machine: Volume ops test: statfs /private/tmp/ci/ginkgoNNN: no such file or directory

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#22569]
Not quite as frequent or annoying as #22551, but still causing wasted runs:
```
run basic podman commands
  Volume ops
....
  Trying to pull quay.io/libpod/alpine_nginx:latest...
  ...
  Writing manifest to image destination
  WARNING: image platform (linux/amd64) does not match the expected platform (linux/arm64)
  Error: statfs /private/tmp/ci/ginkgo630638030: no such file or directory
```

* darwin : machine-mac podman darwin rootless host sqlite
  * PR #22552
    * [05-01 12:16](https://api.cirrus-ci.com/v1/artifact/task/5917831663976448/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-ops--1) in run basic podman commands Volume ops
  * PR #22489
    * [04-24 17:00](https://api.cirrus-ci.com/v1/artifact/task/6358617849331712/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-ops--1) in run basic podman commands Volume ops
    * [04-24 12:06](https://api.cirrus-ci.com/v1/artifact/task/5392202929537024/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-ops--1) in run basic podman commands Volume ops
  * PR #22486
    * [04-24 10:09](https://api.cirrus-ci.com/v1/artifact/task/5837157749751808/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-ops--1) in run basic podman commands Volume ops
  * PR #22461
    * [04-22 18:43](https://api.cirrus-ci.com/v1/artifact/task/6489167138390016/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-ops--1) in run basic podman commands Volume ops

| x | x | x | x | x | x |
| ---: | ---: | ---: | ---: | ---: | ---: |
| machine-mac(5) | podman(5) | darwin(5) | rootless(5) | host(5) | sqlite(5) |

**Comment by edsantiago** [comment]
@cevich is there any chance whatsoever that https://github.com/containers/podman/blob/c9644ebccf14309a77769cba00833cd139509e4a/contrib/cirrus/mac_cleanup.sh is getting invoked in the middle of a running CI job? I just can't understand this bug and am grasping at straws.

**Comment by Luap99** [comment]
Unlikely, there is a extra level of indirectness here given the dir is mounted in the machine VM. As such maybe the machine mount failed silently?

**Comment by Luap99** [comment]
@edsantiago Not sure if you are testing machine in your non flake retry testing PR but if you do could you give this a go:
```diff
diff --git a/pkg/machine/apple/apple.go b/pkg/machine/apple/apple.go
index 93201407e..04db7638b 100644
--- a/pkg/machine/apple/apple.go
+++ b/pkg/machine/apple/apple.go
@@ -124,7 +124,7 @@ func GenerateSystemDFilesForVirtiofsMounts(mounts []machine.VirtIoFs) ([]ignitio
        mountPrep.Add("Service", "Type", "oneshot")
        mountPrep.Add("Service", "ExecStartPre", "chattr -i /")
        mountPrep.Add("Service", "ExecStart", "mkdir -p '%f'")
-       mountPrep.Add("Service", "ExecStopPost", "chattr +i /")
+       // mountPrep.Add("Service", "ExecStopPost", "chattr +i /")
 
        mountPrep.Add("Install", "WantedBy", "remote-fs.target")
        mountPrepFile, err := mountPrep.ToString()
```

**Comment by edsantiago** [comment]
Oops, no, I long ago disabled machine tests in #17831. I will look into reenabling this one.

FWIW here's the current flake list. I don't think there's any useful info in this list, i.e., I haven't seen any logs that look different or provide interesting new data, but am posting anyway.

* darwin : machine-mac podman darwin rootless host sqlite
  * PR #22658
    * [05-13 16:18](https://api.cirrus-ci.com/v1/artifact/task/5468362984128512/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-ops--1) in run basic podman commands Volume ops
  * PR #22582
    * [05-02 20:13](https://api.cirrus-ci.com/v1/artifact/task/6445473010024448/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-ops--1) in run basic podman commands Volume ops
  * PR #22552
    * [05-01 12:16](https://api.cirrus-ci.com/v1/artifact/task/5917831663976448/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-ops--1) in run basic podman commands Volume ops
  * PR #22489
    * [04-24 17:00](https://api.cirrus-ci.com/v1/artifact/task/6358617849331712/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-ops--1) in run basic podman commands Volume ops
    * [04-24 12:06](https://api.cirrus-ci.com/v1/artifact/task/5392202929537024/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-ops--1) in run basic podman commands Volume ops
  * PR #22486
    * [04-24 10:09](https://api.cirrus-ci.com/v1/artifact/task/5837157749751808/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-ops--1) in run basic podman commands Volume ops
  * PR #22461
    * [04-22 18:43](https://api.cirrus-ci.com/v1/artifact/task/6489167138390016/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-ops--1) in run basic podman commands Volume ops

| x | x | x | x | x | x |
| ---: | ---: | ---: | ---: | ---: | ---: |
| machine-mac(7) | podman(7) | darwin(7) | rootless(7) | host(7) | sqlite(7) |

**Comment by Luap99** [comment]
The alternative is I instrument the tests to do some checks. Basically I it would have to ssh into the machine VM and run systemctl status on all the mount units. I think the race here is the most likely cause.

One interesting point would be the new `machine init with volume` test, if this never fails then I am sure this is a race due the parallel running `chattr -i` and `chattr +i` in different units. Reason this tests mounts only one path so there cannot be a race, however the default volumes are several paths thus the chance for the race.

**Comment by Luap99** [comment]
@edsantiago Any conclusions?

**Comment by edsantiago** [comment]
No. This isn't something I can look into, and our PR merge rate is too low these days; not many flakes to report.

**Comment by edsantiago** [comment]
However, I just ran my afternoon flake catchup, and [here's a new one](https://api.cirrus-ci.com/v1/artifact/task/5330767054635008/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-ops--1)

**Comment by Luap99** [comment]
I was mostly interested if you ever saw it in the no flake retry PR (https://github.com/edsantiago/libpod/commit/28882ca65ce4f9e15ab9db6e11b577cacfb6f0db)

However as I have a mac now I can try to reproduce locally and see where I go from there.

**Comment by edsantiago** [comment]
Still active

* darwin : machine-mac podman darwin rootless host sqlite
  * PR #23068
    * [06-21 15:03](https://api.cirrus-ci.com/v1/artifact/task/6682369908801536/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-ops--1) in run basic podman commands Volume ops
  * PR #23030
    * [06-19 09:12](https://api.cirrus-ci.com/v1/artifact/task/5600364802605056/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-ops--1) in run basic podman commands Volume ops
  * PR #23021
    * [06-17 17:01](https://api.cirrus-ci.com/v1/artifact/task/5330767054635008/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-ops--1) in run basic podman commands Volume ops
  * PR #22913
    * [06-06 08:52](https://api.cirrus-ci.com/v1/artifact/task/4602843850604544/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-ops--1) in run basic podman commands Volume ops

**Comment by edsantiago** [comment]
I still suspect this is related to the weird Macintosh CI setup, and as such will only trigger in CI. But I have no evidence to back that up.

**Comment by Luap99** [comment]
Well my PR did triggered it first try so I can tell you now that the bug is in the VM
https://api.cirrus-ci.com/v1/artifact/task/4925116956540928/html/machine-mac-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-ops--1

**Comment by Luap99** [comment]
https://github.com/containers/podman/pull/23118 should contain a proper fix now
