### ISSUE TITLE
Not able Install podman windows 10

### ISSUE THREAD

**Issue by tppalani** [containers/podman#22579]
### Issue Description

We are trying to install podman version 4.9.4 in windows system when run the wsl -l -v command i can see podman and wsl vpn kit both are in installing state past one week, can you somebody help me what is going wrong here, and how to stop this installation process.

### Steps to reproduce the issue

Steps to reproduce the issue
1.
2.
3.
![podman-installing](https://github.com/containers/podman/assets/6921037/cdb8f8d0-0942-4d15-92c5-17018096e100)

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by ashley-cui** [comment]
How did you install podman? What commands have you run?

**Comment by tppalani** [comment]
Hi @ashley-cui we have installed podman using exe file only in our window machine

**Comment by Luap99** [comment]
wsl-vpnkit is not somthing from podman AFAICS. sounds like something with your WSL is broken so you should check if your WSL works in general and llok into the windows docs on how to remove them and try again
