### ISSUE TITLE
Cannot run podman info getting cannot clone: Operation not permitted

### ISSUE THREAD

**Issue by illunix** [containers/podman#22606]
### Issue Description

Hey, I'm trying to run podman info inside my container but it does not work because I get cannot clone: Operation not permitted, thats my dockerfile

```
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

RUN apt-get update \
&& apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        jq \
        git \
        iputils-ping \
        libcurl4 \
        libicu-dev \
        libunwind8 \
        netcat \
        libssl3 \
        wget \
        apt-transport-https \
        software-properties-common \    
        podman \
		zip \
		unzip \
&& rm -rf /var/lib/apt/lists/*

RUN podman info \
  && alias docker=podman 

# Install Node.js
RUN curl -sL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh \
    && bash nodesource_setup.sh \
    && apt-get install -y nodejs \
    && rm nodesource_setup.sh \
    && rm -rf /var/lib/apt/lists/*

# Install .Net 
RUN wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
  && dpkg -i packages-microsoft-prod.deb \
  && apt-get update \
  && apt-get install -y dotnet-sdk-8.0 \
  && rm packages-microsoft-prod.deb \
  && rm -rf /var/lib/apt/lists/*

# Install Kiota
RUN wget -q https://github.com/microsoft/kiota/releases/download/v1.13.0/linux-x64.zip -O kiota.zip \
  && unzip -q kiota.zip -d /usr/local/bin/ \
  && chmod +x /usr/local/bin/kiota \
  && rm kiota.zip

RUN curl -LsS https://aka.ms/InstallAzureCLIDeb | bash \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /azp

COPY ./start.sh .
RUN chmod +x start.sh

CMD ["./start.sh"]
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. Use my dockerfile

### Describe the results you received

cannot clone: Operation not permitted

### Describe the results you expected

Version of the installed podman

### Podman in a container

Yes

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

**Comment by giuseppe** [comment]
how was the outer container created?  Is it a podman container or any other kind?

**Comment by illunix** [comment]
It is docker container created with docker build, and there I get this error @giuseppe

**Comment by illunix** [comment]
What exactly is seccomp? I will use podman in this container only for building and pushing images, not for running so do I need that? Also how do I disable
It? @giuseppe

**Comment by giuseppe** [comment]
yes, "building" an image still requires running a container.

You can disable it with `--security-opt seccomp=unconfined`

**Comment by giuseppe** [comment]
does the error happen if you use podman for the outer container?

**Comment by illunix** [comment]
I've not tested with podman, only with docker, you think that should change something? @giuseppe

**Comment by illunix** [comment]
Using podman it seems it built the image

**Comment by illunix** [comment]
Later when my azure agent have a deploy job where he builds a couple of images it gives again this error
Cannot clone: Operation not permitted
```
podman build -t registry.gitlab.com/varico/docker-registry/s30-api-gateway:20240506.11 -f apps/api/gateway/varico-s30-gateway-api/Dockerfile . 
```
@giuseppe

**Comment by giuseppe** [comment]
if it works with Podman, and it doesn't with Docker, then it is clearly a problem with Docker.

You must be able to run something like `unshare -r true` inside the Docker container.

Are you able to run that command in the Docker container?  It looks like `--security-opt seccomp=unconfined ` had no effect

**Comment by illunix** [comment]
The first problem I had was when I tried to use podman info inside dockerfile in RUN, and you've told me to try to build container with podman instead of docker, and that worked, but right now I get error when I try build container image using podman inside container

**Comment by illunix** [comment]
If you will take a look at the last line of output here you can see that I try build container using podman inside container 

https://github.com/containers/podman/issues/22606#issuecomment-2096591794

**Comment by illunix** [comment]
I've tried using buildah and I get error like this
```
time="2024-05-06T23:14:03Z" level=error msg="error parsing PID \"\": strconv.Atoi: parsing \"\": invalid syntax"
```

**Comment by giuseppe** [comment]
I've tried locally your Dockerfile and it works well with Podman 5 on Linux 6.8.  I'd first suggest to use a newer Podman.  The version present in Ubuntu 22.04 is 3.4.4, that is very old.


Can you run a command like `unshare -U echo hello` on your host?

**Comment by illunix** [comment]
I use ubuntu 22.04, I can't find available repository with podman with version 5.x @giuseppe

**Comment by illunix** [comment]
Also as I mentioned, Dockerfile works for me too, but later when my container gets request to build a container inside it it fails like this
https://github.com/containers/podman/issues/22606#issuecomment-2096591794

**Comment by giuseppe** [comment]
Please run `unshare -U echo hello` both on the host and inside `docker build` and tell me what you get

**Comment by illunix** [comment]
I get hello in response on host and container, also i use podman build if that changes something @giuseppe

**Comment by giuseppe** [comment]
I am not familiar with that environment but it seems to be blocking the creating of a new user namespace.  In this restricted environment you can't use Podman
