### ISSUE TITLE
podman machine start continually fails with vfkit error

### ISSUE THREAD

**Issue by jvdnguyen** [containers/podman#22624]
### Issue Description

Had podman working via Podman Desktop a few weeks ago, but after returning to it now, getting errors just trying to start up. Completely uninstalled Podman Desktop, did `brew uninstall podman-compose` and `brew uninstall podman`, and tried starting over with just a brew install. Am able to `init`, but when trying to `start`, keep running into `Error: vfkit exited unexpectedly with exit code 1`. 

### Steps to reproduce the issue

Steps to reproduce the issue
1. Run `podman machine start`

### Describe the results you received

```
podman machine start dbhs
Starting machine "dbhs"
Error: vfkit exited unexpectedly with exit code 1
```

### Describe the results you expected

VM starts with no issue

### podman info output

```yaml
OS: darwin/amd64
provider: applehv
version: 5.0.2
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
https://blog.podman.io/2024/03/the-dreaded-vfkit-exit-1/

**Comment by Luap99** [comment]
Is this a M1/2/3 mac? Your podman info says amd64 (intel) so you have the wrong bianry installed as mentioned in the blog, you need to install the arm version.

**Comment by jvdnguyen** [comment]
Ah yes thanks, it was an Apple Silicon mac and installing brew native and then podman did fix it!
