### ISSUE TITLE
Not able to perform podman init

### ISSUE THREAD

**Issue by tppalani** [containers/podman#22659]
![podman-hyper-v-failed](https://github.com/containers/podman/assets/6921037/f4e94630-eaa7-44b6-b183-91059c615a18)

### Issue Description

I'm using widows 11 VM, after installing podman when I'm trying to perform the podman init i can see the below error message. I want to check with you is that all the hyper-v option should enabled in my system please refer the attached screen shot for more information.

### Steps to reproduce the issue

```
Steps to reproduce the issue
dism.exe /online /enable-feature /featurename:Microsoft-Windows-Subsystem-Linux /all /norestart
dism.exe /online /enable-feature /featurename:VirtualMachinePlatform /all /norestart
DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V
bcdedit /set hypervisorlaunchtype auto

```
### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.

podman machine init
Extracting compressed file
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
Import in progress, this may take a few minutes.
WSL2 is not supported with your current machine configuration.
Please enable the "Virtual Machine Platform" optional component and ensure virtualization is enabled in the BIOS.
Enable "Virtual Machine Platform" by running: wsl.exe --install --no-distribution
For information please visit https://aka.ms/enablevirtualization
Error code: Wsl/Service/RegisterDistro/CreateVm/HCS/HCS_E_HYPERV_NOT_INSTALLED
Error: the WSL import of guest OS failed: exit status 0xffffffff
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by tnk4on** [comment]
You should check `ExposeVirtualizationExtensions`.
```
Get-VMProcessor -VMName * |ft VMName,ExposeVirtualizationExtensions
```

If `False` is returned, stop the virtual machine and enable the feature.
```
Set-VMProcessor -VMName <VMName> -ExposeVirtualizationExtensions $true
```
Please see references.
https://learn.microsoft.com/en-us/windows/wsl/faq#can-i-run-wsl-2-in-a-virtual-machine-
https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/enable-nested-virtualization

**Comment by ashley-cui** [comment]
I believe you are using the WSL provider. You can set it to hyperV in containers.conf or the env var: `$env:CONTAINERS_MACHINE_PROVIDER="hyperv"`

**Comment by tppalani** [comment]
Hi @ashley-cui  @tnk4on Thanks for the quick response.

Our VMS are running VDDS , after enabling hyper-v hypervisor above issue got resolved.
