### ISSUE TITLE
Podman-compose mount volume incorrectly under Windows with podman machine on WSL

### ISSUE THREAD

**Issue by ohhappy1986** [containers/podman#22684]
### Issue Description

When using podman-compose to bring up below container. The volume mapping is incorrectly mapped, it automatically adds "/mnt/d" before each of the volume entry in compose file.

podman-compose v1.1.0

Compose file below:

services:
  ibml:
    image: /nvidia/cuda
    container_name: ibml_engine
    build:
      context: .\IBML
      args:
         APP_VERSION: latest
    volumes:
      - /mnt/e/Data:/mnt/e/Data
      - /mnt/d/Logs:/mnt/d/Logs
    networks:
      candela-net:
        ipv4_address: 172.168.0.11
    dns:
      - "8.8.8.8" 
    devices:
      - nvidia.com/gpu=all
    security_opt:
     - "label=disable"

If you inspect the container which it brought up. You can see volumes are mount as below
`/mnt/d/mnt/e/Data:/mnt/e/Data
/mnt/d/mnt/d/Logs:/mnt/d/Logs`

### Steps to reproduce the issue

Steps to reproduce the issue
1. Save the posted compose file into compose.yaml file
2. Run podman-compose -f compose.yaml up -d
3. Inspect the container using Podman desktop or command line

### Describe the results you received

The volume mounted as
`/mnt/d/mnt/e/Data:/mnt/e/Data
/mnt/d/mnt/d/Logs:/mnt/d/Logs`

### Describe the results you expected

Then volume should be mounted as
`/mnt/e/Data:/mnt/e/Data
/mnt/d/Logs:/mnt/d/Logs`

### podman info output

```yaml
OS: windows/amd64
provider: wsl
version: 5.0.2
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by mheon** [comment]
Can you try without Podman Compose, just with a `podman run` command with the same volume? I suspect the result will be the same but confirmation would be nice.

**Comment by ohhappy1986** [comment]
podman run works, issues only exists in podman-compose

**Comment by mheon** [comment]
You may want to reopen against the podman-compose repo then, we only support Podman itself here
