### ISSUE TITLE
Hostname written to /etc/hostname does not include new-line at end

### ISSUE THREAD

**Issue by dagraff-cisco** [containers/podman#22729]
As noted in [docker](https://github.com/docker-library/docker/issues/496), the hostname written to `/etc/hostname` does not include a new-line at the end.

As per debian's [hostname (5)](https://manpages.debian.org/bookworm/systemd/hostname.5.en.html) man page:

> The file should contain a single newline-terminated hostname string. Comments (lines starting with a "#") are ignored. The hostname should be composed of up to 64 7-bit ASCII lower-case alphanumeric characters or hyphens forming a valid DNS domain name. It is recommended that this name contains only a single label, i.e. without any dots. Invalid characters will be filtered out in an attempt to make the name valid, but obviously it is recommended to use a valid name and not rely on this filtering.

The code in question: is here

https://github.com/containers/podman/blob/f7a30461e06f6786b02fc44b5c48525d2ebbc482/libpod/container_internal_linux.go#L667

This should be amended to read

```go
hostnamePath, err := c.writeStringToRundir("hostname", fmt.Sprintf("%s\n", c.Hostname()))
```

**Comment by raghavgh** [comment]
@Luap99 Can i pick this up?

**Comment by rhatdan** [comment]
You got it.

**Comment by ut-wangbo** [comment]
@rhatdan 
I noticed that this issue has not been closed for two weeks.  And I wanna try to make my first contribution for  containers/podman . ^_^

**Comment by raghavgh** [comment]
@rhatdan
Apologies I didn't found time from few weeks to complete this task, please
help re assign.

Thank you

**Comment by rhatdan** [comment]
@ut-wangbo you got it.

**Comment by dagraff-cisco** [comment]
I have created a branch to address this in a forked repository - if you would like me to proceed with a PR for this please let me know.

**Comment by rhatdan** [comment]
If you have a fix, please open a PR.

**Comment by dagraff-cisco** [comment]
This issue was closed in June - however was not included into 5.1 - what is the process to request inclusion?

**Comment by Luap99** [comment]
It will be part of 5.2 which will be released in the next few weeks.

**Comment by dagraff-cisco** [comment]
@Luap99 thank you very much for the super fast response. Truly appreciate the work y'all do!
