### ISSUE TITLE
Empty `NetworkSettings` when doing `podman inspect` on container using pasta

### ISSUE THREAD

**Issue by der-eismann** [containers/podman#22768]
### Issue Description

After updating Podman from 5.0.0 to 5.0.2 on CentOS 9 Stream, we were suddenly hit with the issue of default rootless containers not being able to connect to ports on the host IP. IIUC this shouldn't have worked in 5.0.0 already because of the switch to pasta as the default network provider for rootless containers, but somehow it did :man_shrugging: 

Now apart from the fact that this breaking change was poorly communicated and documented in the release notes, this issue was very hard to debug as `podman inspect <container>` doesn't give any network information at all. Yes, there is `"NetworkMode": "pasta",`, but that's it. The network settings however are completely empty, which left me puzzled about the IP of the container.

Would it be possible to populate this with any information for containers using pasta? Even if it was just the same settings as used on the host, it would have helped me. It was also very confusing, because older posts like [this](https://www.redhat.com/sysadmin/container-ip-address-podman) don't even mention pasta.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Run rootless container with pasta networking, e.g. `podman run --rm -p 5432:5432 -e POSTGRES_PASSWORD=test postgres:14.12-alpine`
2. Inspect it, e.g. `podman inspect sharp_mendeleev | jq '.[0].NetworkSettings'`

### Describe the results you received

Empty details:
```json
          "NetworkSettings": {
               "EndpointID": "",
               "Gateway": "",
               "IPAddress": "",
               "IPPrefixLen": 0,
               "IPv6Gateway": "",
               "GlobalIPv6Address": "",
               "GlobalIPv6PrefixLen": 0,
               "MacAddress": "",
               "Bridge": "",
               "SandboxID": "",
               "HairpinMode": false,
               "LinkLocalIPv6Address": "",
               "LinkLocalIPv6PrefixLen": 0,
               "Ports": {},
               "SandboxKey": "/run/user/1001/netns/netns-896fcf14-d119-7aa4-7703-fc9df3646f14"
          },
```

### Describe the results you expected

More information, maybe put networking mode here instead of in the HostConfig? Or at least put the host IP that's being used here.

### podman info output

```yaml
podman info
host:
  arch: amd64
  buildahVersion: 1.35.4
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.10-1.fc40.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: '
  cpuUtilization:
    idlePercent: 95.91
    systemPercent: 1.09
    userPercent: 3
  cpus: 16
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: workstation
    version: "40"
  eventLogger: journald
  freeLocks: 2032
  hostname: eduard-laser
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.8.9-300.fc40.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 5720895488
  memTotal: 32401354752
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.10.0-1.fc40.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.10.0
    package: netavark-1.10.3-3.fc40.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.10.3
  ociRuntime:
    name: crun
    package: crun-1.14.4-1.fc40.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.14.4
      commit: a220ca661ce078f2c37b38c92e66cf66c012d9c1
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20240510.g7288448-1.fc40.x86_64
    version: |
      pasta 0^20240510.g7288448-1.fc40.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 47223136256
  swapTotal: 47229952000
  uptime: 69h 53m 51.00s (Approximately 2.88 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/sysop/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/sysop/.local/share/containers/storage
  graphRootAllocated: 805289590784
  graphRootUsed: 763075788800
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 37
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/sysop/.local/share/containers/storage/volumes
version:
  APIVersion: 5.0.3
  Built: 1715299200
  BuiltTime: Fri May 10 02:00:00 2024
  GitCommit: ""
  GoVersion: go1.22.2
  Os: linux
  OsArch: linux/amd64
  Version: 5.0.3
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

**Comment by Luap99** [comment]
What purpose would the ip serve? You cannot connect to the ip from the host or other containers as they are in separate namespaces and there is no directly routable connection between them. Showing the ip would just confuse people even more IMO. 

The inspect output is inherited from docker and almost all of these fields do not make sense for slirp4netns/pasta so we just leave them empty. We do set SandboxKey and Ports so they are also not all empty. The SandboxKey is useful to join the netns. I guess we could also fill in the MacAddress.

**Comment by Luap99** [comment]
> Now apart from the fact that this breaking change was poorly communicated and documented in the release notes

How and where should we communicate such changes, there is https://blog.podman.io/2024/03/podman-5-0-breaking-changes-in-detail/ that goes into more detail.

> It was also very confusing, because older posts like [this](https://www.redhat.com/sysadmin/container-ip-address-podman) don't even mention pasta.

Well the blog post is over two years old, back then pasta integration didn't even exists nor is this a official podman documentation. (I know our docs are also far from perfect)

**Comment by der-eismann** [comment]
> How and where should we communicate such changes, there is [blog.podman.io/2024/03/podman-5-0-breaking-changes-in-detail](https://blog.podman.io/2024/03/podman-5-0-breaking-changes-in-detail/) that goes into more detail.

In the release notes for 5.0.0 it only states this:
> The default tool for rootless networking has been swapped from slirp4netns to pasta for improved performance. As a result, networks named pasta are no longer supported.

A link to the blog post can nowhere be found in the release, this or at least some hints about the implications of this change would have been nice. The mention of networks named pasta would suggest that this is the _only_ important result. In general I'd say you can't expect people to google for blog posts every time there is a new release, just put it at the top of the release notes (even though that makes automatic release processes more complicated).

> What purpose would the ip serve? You cannot connect to the ip from the host or other containers as they are in separate namespaces and there is no directly routable connection between them. Showing the ip would just confuse people even more IMO.
> 
> The inspect output is inherited from docker and almost all of these fields do not make sense for slirp4netns/pasta so we just leave them empty. We do set SandboxKey and Ports so they are also not all empty. The SandboxKey is useful to join the netns. I guess we could also fill in the MacAddress.

I see. I guess the Docker compatibility is the issue (but it's needed, I know), as it prevents podman from showing "only useful" information here. If you think this doesn't make sense, feel free to close this issue, at least others can find it then if someone has the same thought as I am. 

I am probably just frustrated because I wasted 2 hours debugging and fixing this (+30 mins because the `[network]` line was missing in the second pasta config example in the blog post and I forgot to add it) while our whole CI blew up because of this change. I wanted to get the IP of the container to get an idea why this suddenly stopped working and I just couldn't. Maybe it's just me, but debugging networking issues in podman can be a real pain because most images are missing tools like `ip`.
(While debugging I tried to run our containers with `--network=bridge`, only to notice that DNS resolution doesn't work. I understand that many of these limitations have their reasons, but sometimes you just sit there thinking _why on earth doesn't this just work_?)

**Comment by Luap99** [comment]
> > How and where should we communicate such changes, there is [blog.podman.io/2024/03/podman-5-0-breaking-changes-in-detail](https://blog.podman.io/2024/03/podman-5-0-breaking-changes-in-detail/) that goes into more detail.
> 
> In the release notes for 5.0.0 it only states this:
> 
> > The default tool for rootless networking has been swapped from slirp4netns to pasta for improved performance. As a result, networks named pasta are no longer supported.
> 
> A link to the blog post can nowhere be found in the release, this or at least some hints about the implications of this change would have been nice. The mention of networks named pasta would suggest that this is the _only_ important result. In general I'd say you can't expect people to google for blog posts every time there is a new release, just put it at the top of the release notes (even though that makes automatic release processes more complicated).

Thanks, to be clear my comment was not meant in any way negative. I just like to know so I can improve this going forward. Linking the blogs in the releases notes is definitely something we can and should do. Writing releases notes is hard and complicated, some want a short log, some want more details, etc... We didn't anticipate the amount of "breaking" scenarios with pasta so we did not consider this such a big deal. In hindsight this should have been made much more clear to users I agree.


> Maybe it's just me, but debugging networking issues in podman can be a real pain because most images are missing tools like ip.

You don't need networking tools inside the container
```
podman unshare nsenter -n$(podman inspect --format '{{.NetworkSettings.SandboxKey}}' c1) ip a
```
or when running as root remove the `podman unshare`, you can execute any host command in the container netns like this.

> I am probably just frustrated because I wasted 2 hours debugging and fixing this (+30 mins because the [network] line was missing in the second pasta config example in the blog post and I forgot to add it)

I edited the post and added the `[network]` line, hopefully it helps others




---

> > The inspect output is inherited from docker and almost all of these fields do not make sense for slirp4netns/pasta so we just leave them empty. We do set SandboxKey and Ports so they are also not all empty. The SandboxKey is useful to join the netns. I guess we could also fill in the MacAddress.
> 
> I see. I guess the Docker compatibility is the issue (but it's needed, I know), as it prevents podman from showing "only useful" information here. If you think this doesn't make sense, feel free to close this issue, at least others can find it then if someone has the same thought as I am.

It depends, there is no formal of course. I think adding the ip there could confuse others as they try to use it for connections. And it is hard to tell the impact of such change, thus I rather leave the behavior as is unless there are strong arguments for doing it.

**Comment by der-eismann** [comment]
I'd agree with your arguing. Thanks for the elaborate answers and your time!
