### ISSUE TITLE
podman healthcheck + sdnotify: Error: container is stopped

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#22760]
```
<+015ms> # # podman run --name IK28z8EJtw --health-cmd=touch /terminate --sdnotify=healthy quay.io/libpod/testimage:20240123 sh -c while test \! -e /terminate; do sleep 0.1; done; echo finished
<+572ms> # finished
         # Error: container is stopped
<+004ms> # [ rc=126 (** EXPECTED 0 **) ]
```
Reproducer fails within seconds on 1mt:
```console
# while :;do bin/podman run --health-cmd="touch /terminate" --sdnotify=healthy quay.io/libpod/testimage:20240123 sh -c "while test \! -e /terminate; do sleep 0.1; done; echo finished" || break; done
finished
finished
finished
finished
finished
finished
finished
finished
finished
finished
Error: container is stopped
```
While I'm at it, this is probably a bug too: (above command, with `run --rm`, fails instantly):
```console
# bin/podman run --rm --health-cmd="touch /terminate" --sdnotify=healthy quay.io/libpod/testimage:20240123 sh -c "while test \! -e /terminate; do sleep 0.1; done; echo finished"
finished
# echo $?
127
```

Almost certainly related to #22658. @giuseppe PTAL. Only seen on aarch64, but that's consistent with the previous flake that you fixed in your PR.

* fedora-40-aarch64 : sys podman fedora-40-aarch64 root host sqlite
  * PR #22731
    * [05-16 18:10](https://api.cirrus-ci.com/v1/artifact/task/4666751898615808/html/sys-podman-fedora-40-aarch64-root-host-sqlite.log.html#t--00442) in [sys] [260] sdnotify : healthy
    * [05-16 16:49](https://api.cirrus-ci.com/v1/artifact/task/6395645383147520/html/sys-podman-fedora-40-aarch64-root-host-sqlite.log.html#t--00442) in [sys] [260] sdnotify : healthy

| x | x | x | x | x | x |
| ---: | ---: | ---: | ---: | ---: | ---: |
| sys(2) | podman(2) | fedora-40-aarch64(2) | root(2) | host(2) | sqlite(2) |

**Comment by edsantiago** [comment]
OBTW `vim /usr/share/containers/storage.conf` and comment out the `thinpool` line, otherwise lots of nasty warnings

**Comment by giuseppe** [comment]
opened a tentative PR: https://github.com/containers/podman/pull/22764

Marked as a Draft as I want to test it better.  It doesn't solve the root issue as it would still fail if the healthcheck change takes much longer than a waiting interval
