### ISSUE TITLE
podman pull writes to read only additional image store

### ISSUE THREAD

**Issue by ankurmalhotra07** [containers/podman#22784]
### Issue Description

Describe your issue
I have created a read-only directory that will be used as an additional image store ('/var/lib/mycontainers')
However, when I try to pull an image, it throws the following error:
Error: creating lock file directory: mkdir /var/lib/mycontainers/overlay-images: read-only file system
script returned exit code 125

### Steps to reproduce the issue

Steps to reproduce the issue
1.mkdir /var/lib/mycontainers
2. podman pull --storage-opt additionalimagestore=/var/lib/mycontainers alpine

### Describe the results you received

Error: creating lock file directory: mkdir /var/lib/mycontainers/overlay-images: read-only file system

### Describe the results you expected

podman pulls image to primary storage, reusing layers from additional image store. The lock file should only be created in primary storage, not additional image stores which are meant to be read-only

### podman info output

```yaml
Version v4.9
```

### Podman in a container

Yes

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by ankurmalhotra07** [comment]
@giuseppe do you know if the above is a bug? Its a blocker for our use case

**Comment by rhatdan** [comment]
You need to precreate the lock files in the additional store.

**Comment by ankurmalhotra07** [comment]
We have a cron job that would populate the additional storage but it might not be ready before client calls podman pull. Can you explain what's the purpose of that lock file?

**Comment by giuseppe** [comment]
> We have a cron job that would populate the additional storage on the node but it might not be ready before client calls podman pull. Can you explain what's the purpose of that lock file?

It is not only a matter of ignoring the lock file.  An empty directory is not a valid store and there are more things that could wrong.  Make sure the store is valid before using it with Podman.

It is enough you run something like `podman --root /var/lib/images images` to create the store and the required files
