### ISSUE TITLE
podman exec [mandatory command?]

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#22849]
### Issue Description

At https://docs.podman.io/en/latest/markdown/podman-exec.1.html the synopsis is:

> podman exec [options] container [command [arg …]]
> podman container exec [options] container [command [arg …]]

For me this means that the `command` argument is optional.  The webpage does not say what is the default command, if `command` does not follow `exec`.  So I thought it will be the Containerfile’s `ENTRYPOINT`.   But it is not:

```
$ podman exec -ti uuu
Error: must provide a non-empty command to start an exec session: invalid argument
```

The problem report is that the synopsys at the aforementioned web page, and the synopsis printed by `podman exec --help` wrongly suggest, that COMMAND is optional, by putting it between square brackets.

### Steps to reproduce the issue

Not applicable.

### Describe the results you received

Describe the results you received

### Describe the results you expected

Not applicable.

### podman info output

```yaml
podman 5.0.3 on darwin/amd64.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by giuseppe** [comment]
thanks for opening the issue.  The documentation is wrong, the argument to exec is mandatory

**Comment by alkesander** [comment]
@giuseppe can you please add me as assignee? I can update the documentation accordingly.

**Comment by giuseppe** [comment]
@alkesander, it was assigned to you

**Comment by edsantiago** [comment]
@alkesander, ping, are you still interested in working on this?

**Comment by aksaswadkar** [comment]
Hi @rhatdan are you working on this? If not, I'd like to give it a try.

**Comment by rhatdan** [comment]
Thanks I guess I worked on this and forgot to submit it.  PTAL
