### ISSUE TITLE
Quay.io images are lagging behind

### ISSUE THREAD

**Issue by duck-rh** [containers/podman#22861]
### Issue Description

I'm using quay.io images and I was waiting for a fix in later version but all I get is 5.0.2. I checked the documentation and quay.io is still the recommended registry. On the quay.io page the last tag is indeed 5.0.2. 5.1.0 is very recent and the build might not have been triggered but 5.0.3 should already be there, therefore I think there's a problem somewhere. Could you have a look please?

### Steps to reproduce the issue

pull quay.io/podman/stable

### Describe the results you received

version 5.1.0, or at least 5.0.3

### Describe the results you expected

got 5.0.2

### podman info output

```yaml
\_o<
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
builds are based on fedora packages  not upstream tags so it will always lag behind until the podman update lands in fedora

**Comment by duck-rh** [comment]
@Luap99 thanks for the explanation.

I hope you'll consider another workflow because that leaves only building from source to get the latest version (since this repo only publishes a podman-remote binary and not a full build on Linux) and that's not very practical.

**Comment by Luap99** [comment]
> and btw all the other podman/testing, podman/upstream, podman/staging are dead, so really no other option

Huh? This is definitely unexpected to me. At least I don't recall any conversation about removing them.

@cevich PTAL

**Comment by cevich** [comment]
> Huh? This is definitely unexpected to me. At least I don't recall any conversation about removing them.

The `Containerfile` and build automation for this was moved to https://github.com/containers/image_build

> I hope you'll consider another workflow because that leaves only building from source to get the latest version

The "upstream" flavored container image is built from the latest upstream source.  It happens daily, so should be w/in 10-or-so commits of `main`.  Are you looking for something that tracks `main` even closer or something different entirely?

**Comment by cevich** [comment]
Oh hang on, there is something wrong.  I just checked the "upstream" flavored podman|buildah|skopeo repos on quay and indeed they're all empty.  They should all have a "latest" tag.  I'll investigate and fix this.

**Comment by duck-rh** [comment]
@cevich thanks for the fix
