### ISSUE TITLE
unable to do cross-compilation (arm64 build within amd64 machine)

### ISSUE THREAD

**Issue by benoitf** [containers/podman#22883]
hello, it looks like this podman machine is not allowing to do arm64 builds using amd64 machine

See https://github.com/containers/podman/issues/19961

it might require an extra configuration in addition to the installation of `qemu-user-static` package done there https://github.com/containers/podman-machine-wsl-os/blob/main/.cirrus.yml#L9

**Comment by Luap99** [comment]
I close this as dup of #19961
