### ISSUE TITLE
Allow disabling "Executing external compose provider"

### ISSUE THREAD

**Issue by ctron** [containers/podman#22904]
### Feature request description

Each time I start `podman compose` I get the following message:

```
>>>> Executing external compose provider "/usr/local/bin/docker-compose". Please refer to the documentation for details. <<<<
```

I am aware of that fact, but would like to disable that message. Also, it is not quite clear which "documentation" to look in to.

### Suggest potential solution

There should be a message pointing me to the specific documentation. That documentation should contain instructions on how to remove this message.

### Have you considered any alternatives?

None

### Additional context

None

**Comment by Luap99** [comment]
`podman-compose(1)` (https://docs.podman.io/en/latest/markdown/podman-compose.1.html)
which should lead you to man `containers.conf(5)` https://github.com/containers/common/blob/main/docs/containers.conf.5.md and if you search for compose there you find
`compose_warning_logs`

But yeah I agree this should just be part of the podman-compose page directly and then this page could be part of the message

**Comment by ctron** [comment]
Ping.

**Comment by rhatdan** [comment]
Care to open a PR to fix?

**Comment by Luap99** [comment]
A PR is already open https://github.com/containers/podman/pull/23074
