### ISSUE TITLE
podman machine start requires Rosetta even when CONTAINERS_MACHINE_ROSETTA is set to false

### ISSUE THREAD

**Issue by agsimeonov** [containers/podman#22918]
### Issue Description

With version 5.1.0 the following was introduced:
```
VMs created by podman machine on macOS with Apple silicon can now use Rosetta 2 (a.k.a Rosetta) for high-speed emulation of x86 code. This is enabled by default. If you wish to change this option, you can use the CONTAINERS_MACHINE_ROSETTA environment variable or containers.conf.
```

Running the following
```
export CONTAINERS_MACHINE_ROSETTA=false
podman machine init --cpus=4 --disk-size=60 --memory=8192 --rootful
podman machine start
```

I get a popup asking me to install Rosetta.

I can't seem to get things running without Rosetta in the mix.

### Steps to reproduce the issue

Steps to reproduce the issue
1.  on a fresh install run: `export CONTAINERS_MACHINE_ROSETTA=false`
2. `podman machine init --cpus=4 --disk-size=60 --memory=8192 --rootful`
3. `podman machine start`

You will get a prompt to install Rosetta

### Describe the results you received

Rosetta is required even though `CONTAINERS_MACHINE_ROSETTA` is set to `false`

### Describe the results you expected

I can use podman without installing Rosetta when `CONTAINERS_MACHINE_ROSETTA` is set to `false`

### podman info output

```yaml
OS: darwin/arm64
provider: applehv
version: 5.1.1
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

`CONTAINERS_MACHINE_ROSETTA` is set to `false`

### Additional information

- Rosetta is not installed on my machine.
- This is on a fresh install of Podman without any other machines/etc. present.

**Comment by tnk4on** [comment]
@agsimeonov This is not a bug, it is a documentation bug in the [v.5.1.0 release page](https://github.com/containers/podman/releases/tag/v5.1.0).
This environment variable was removed during development and has not been implemented. https://github.com/containers/podman/pull/21670
Also, the release notes file has been corrected in this PR https://github.com/containers/podman/pull/22842.
However, the fixes do not seem to be reflected in the release page.

@containers/podman-maintainers PTAL

**Comment by agsimeonov** [comment]
If anyone else happens on this the way I got things to run without rosetta is the following:
```
vim $HOME/.config/containers/containers.conf
```
then add the following to it:
```
[machine]
rosetta=false
```

now you can init a new machine and start things up from there.

Anyways @tnk4on I am also curious as to why Rosetta is the default behavior now? Requiring stopgap software from Apple when things were running fine for years without it previously seems rather odd even if there is a performance gain. Judging from what Apple did with Rosetta 1 when they transitioned from PowerPC to x86 it is reasonable to believe that they will stop supporting Rosetta 2 in the near future after they deem that support for `darwin/arm64` is at a satisfactory level. Shouldn't using Rosetta be an option rather than the default?

**Comment by tnk4on** [comment]
@agsimeonov You can check the reasons why it has been enabled by default in the comments of the PR https://github.com/containers/podman/pull/21670.

Previously, qemu-user-static was used as User Mode Emulation within Podman machine. Rosetta is superior to QEMU in terms of both performance and emulation compatibility for x86_64.

Docker Desktop has Rosetta enabled by default. Podman should also be the same.
For more information on Rosetta Support, please check my presentation.
https://speakerdeck.com/tnk4on/rosetta-support-podman-v5-dot-1
