### ISSUE TITLE
Typo in podman-build.1.md.in

### ISSUE THREAD

**Issue by dilyanpalauzov** [containers/podman#22946]
### Issue Description

https://docs.podman.io/en/stable/markdown/podman-build.1.html#building-an-image-using-a-git-repository :

> Podman fetches the archive file, decompress it, and use its contents as the build context.

→ *decompressES*, *useS*

In the same file:

> Podman clones the specified GitHub repository to a temporary location and use it as the context.

→ *useS*

### Steps to reproduce the issue

Not applicable.

### Describe the results you received

Not applicable.

### Describe the results you expected

Not applicable.

### podman info output

```yaml
Not applicable.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

**Comment by rhatdan** [comment]
Please open a PR

**Comment by dilyanpalauzov** [comment]
https://github.com/containers/podman/pull/17156#issuecomment-1425746409

**Comment by baude** [comment]
@dilyanpalauzov thank you for the issue filing.
