### ISSUE TITLE
support download vm image manually before  machine init

### ISSUE THREAD

**Issue by LeiYangGH** [containers/podman#23012]
### Feature request description

i'm new user and following [podman-for-windows](https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md)
but stuck on `podman machine init`

```powershell
PS C:\Users\user> podman machine init
Downloading VM image: v20240616181311-5.1-rootfs-amd64.tar.zst [>------------------------------------------------] 3.2MiB / 162.2MiB
Error: stream error: stream ID 5; PROTOCOL_ERROR; received from peer
PS C:\Users\user>
```

for some reason the network may be extremely slow, and i can download things before `machine init`.

### Suggest potential solution

so want some options to specify local downloaded files in init command, of course, need documents on what files should be downloaded. thanks!

### Have you considered any alternatives?
setting proxy may solve but it's more difficult for me.

### Additional context

in china we are blocked from many websites.

**Comment by Luap99** [comment]
This is already supported, you can use --image option to specify a local disk image
https://docs.podman.io/en/latest/markdown/podman-machine-init.1.html#image

For WSL you can download the images from here: https://github.com/containers/podman-machine-wsl-os/releases

**Comment by LeiYangGH** [comment]
> This is already supported, you can use --image option to specify a local disk image https://docs.podman.io/en/latest/markdown/podman-machine-init.1.html#image
> 
> For WSL you can download the images from here: https://github.com/containers/podman-machine-wsl-os/releases

thanks, will try soon.

**Comment by LeiYangGH** [comment]
works!
```powershell
PS C:\Users\user> podman machine init --image "C:\Users\user\Downloads\5.1-rootfs-amd64.tar.zst"
Extracting compressed file: podman-machine-default-amd64: done
Importing operating system into WSL (this may take a few minutes on a new WSL install)...
Configuring system...
Machine init complete
To start your machine run:

        podman machine start

PS C:\Users\user> podman machine start
Starting machine "podman-machine-default"

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

        podman machine set --rootful

API forwarding listening on: npipe:////./pipe/docker_engine

Docker API clients default to this address. You do not need to set DOCKER_HOST.
Machine "podman-machine-default" started successfully
PS C:\Users\user>
```
