### ISSUE TITLE
Swagger docs mismatch for /images/{name}/push and libpod endpoint

### ISSUE THREAD

**Issue by AlexanderNull** [containers/podman#23040]
### Issue Description

The current main branch swagger/openapi docs for both the /images/{name}/push and /libpod/images/{name}/push endpoints are both incomplete with regard to the parameters the corresponding handlers will accept. The "format" parameter that's missing from both in particular is one that caused me a bit of a headache on my current project.

### Steps to reproduce the issue

Steps to reproduce the issue
1. read the API docs
    1. [compat](https://docs.podman.io/en/latest/_static/api.html#tag/images-(compat)/operation/ImagePush)
    2. [libpod](https://docs.podman.io/en/latest/_static/api.html#tag/images/operation/ImagePushLibpod)
2. compare to the implemented handler functions
    1. [compat](https://github.com/containers/podman/blob/main/pkg/api/handlers/compat/images_push.go#L23)
    2. [libpod](https://github.com/containers/podman/blob/main/pkg/api/handlers/libpod/images_push.go#L23)

### Describe the results you received

Actual parameter list for [/images/{name}/push](https://github.com/containers/podman/blob/main/pkg/api/server/register_images.go#L247):
- all
- compress
- destination
- name
- tag

Actual parameter list for [/libpod/images/{name}/push](https://github.com/containers/podman/blob/main/pkg/api/server/register_images.go#L712):
- destination
- forceCompressionFormat
- name
- quiet
- tlsVerify

### Describe the results you expected

Expected parameter list for [/images/{name}/push](https://github.com/containers/podman/blob/main/pkg/api/handlers/compat/images_push.go#L23):
- all
- compress
- destination
- format
- name
- tlsVerify
- tag

Expected parameter list for [/libpod/images/{name}/push](https://github.com/containers/podman/blob/main/pkg/api/handlers/libpod/images_push.go#L23):
- all
- compressionFormat
- compressionLevel
- forceCompressionFormat
- destination
- format
- name
- quiet
- removeSignatures
- retry
- retryDelay
- tlsVerify

### podman info output

```yaml
Just reading the online docs/source control
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
Interested in opening a PR to fix the swagger doc?

**Comment by AlexanderNull** [comment]
@Luap99 : PR submitted
