### ISSUE TITLE
`podman-catatonit` cannot be installed in a UBI9 based container image

### ISSUE THREAD

**Issue by cgruver** [containers/podman#23057]
### Issue Description

When attempting to install `podman` and `podman-catatonit` in a UBI9 based container image, catatonit appears to be looking for a specific, older version of `podman`

```bash
nothing provides podman = 2:4.2.0-11.el9_1 needed by podman-catatonit-2:4.2.0-11.el9_1.x86_64 from ubi-9-appstream-rpms
```

podman 4.9.4 is the current version in RHEL 9.4

### Steps to reproduce the issue

In a RHEL 9.4 based UBI9 container:

1. `microdnf install -y podman podman-catatonit`

Observe failure: `nothing provides podman = 2:4.2.0-11.el9_1 needed by podman-catatonit-2:4.2.0-11.el9_1.x86_64 from ubi-9-appstream-rpms`

__Note:__  `catatonit` appears to be an rpm alias for `podman-catatonit`. I tried both with the same error resulting.

### Describe the results you received

```bash
error: Could not depsolve transaction; 1 problem detected:
 Problem: conflicting requests
  - nothing provides podman = 2:4.2.0-11.el9_1 needed by podman-catatonit-2:4.2.0-11.el9_1.x86_64 from ubi-9-appstream-rpms
```

### Describe the results you expected

Successful install of podman and catatonit

### podman info output

```yaml
podman version 4.9.4
```

### Podman in a container

Yes

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
Packaging issues should be reported against the distro bug trackers not upstream
