### ISSUE TITLE
Podman push successful image does not appear in repository, i using Ubuntu

### ISSUE THREAD

**Issue by PunkFleet** [containers/podman#23129]
### Discussed in https://github.com/containers/podman/discussions/23117

<div type='discussions-op-text'>

<sup>Originally posted by **PunkFleet** June 27, 2024</sup>
I using Podman setup a private registry. and i can push image `registry.xxxxx.com:5000/xxxx/hello` from localhsot to registry.
If i
```
curl -u user:pass https://registry.xxxxx.com:5000/v2/_catalog
{"repositories":["hello","xxxx/hello"]}
```
Great, i see It's success. 
But....
```
podman images
REPOSITORY                           TAG         IMAGE ID      CREATED        SIZE
docker.io/library/registry           latest      6a3edb1d5eb6  8 months ago   26 MB
registry.xxxx.com:5000/hello  latest      d2c94e258dcb  14 months ago  28.5 kB
docker.io/library/hello-world        latest      d2c94e258dcb  14 months ago  28.5 kB
```
There don't display the new image that from localhost pushed.
It should display
```
registry.xxxxx.com:5000/xxxx/hello
```

May i missed something? or this is a bug?</div>

**Comment by Luap99** [comment]
Let's keep the discus in one palce
