### ISSUE TITLE
Support top-level type drop-ins (pod.d, container.d, etc) and truncated unit drop-ins (name-.container.d) for quadlet

### ISSUE THREAD

**Issue by benniekiss** [containers/podman#23158]
### Feature request description

Regular systemd unit files allow for top-level type drop-ins, such as `service.d/` and `socket.d/`. Quadlet generated files should support this as well. For example, drop-in files in `pod.d/` should be applied to all generated `.pod` files.

**Comment by Luap99** [comment]
What kind of options would you like to set "globally"?

We already have a config file for setting defaults, containers.conf.

cc @ygalblum @alexlarsson

**Comment by benniekiss** [comment]
I was thinking more along the lines of `[Unit]`, `[Service]`, and `[Install]` sections to set these globally for Quadlet files.

**Comment by benniekiss** [comment]
It would also be helpful to support drop-ins for truncated units, where drop-ins in directories like `{CONTAINER_NAME}-.container.d/` were applied to all `.container` quadlet files beginning with `{CONTAINER_NAME}-`

**Comment by Luap99** [comment]
> It would also be helpful to support drop-ins for truncated units, where drop-ins in directories like `{CONTAINER_NAME}-.container.d/` were applied to all `.container` quadlet files beginning with `{CONTAINER_NAME}-`

Is this something systemd can do? I think it is best to keep the logic is similar to the systemd parsing as possible.

**Comment by benniekiss** [comment]
Yes, it is. The drop-in functionality is described in the 12th paragraph block in the description section [here](https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html#Description)
