### ISSUE TITLE
Podman Machine init: dial tcp 140.82.121.4:443: connectex: No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by odockal** [containers/podman#23196]
### Issue Description

Reported on podman desktop: https://github.com/containers/podman-desktop/issues/7827.
User is facing problems getting image from `quay.io` when initializing the podman machine.

> Hi,
I did a fresh install of Podman Desktop v1.11.1 on Windows11. Also ran the wsl upgrade command. On clicking the setup button, I am getting this error:

> Error: Command execution failed with exit code 125 Command execution failed with exit code 125 Error: head request failed: https://github.com/containers/podman-machine-wsl-os/releases/latest/download: Head "https://github.com/containers/podman-machine-wsl-os/releases/latest/download/5.1-rootfs-amd64.tar.zst": dial tcp 140.82.121.4:443: connectex: No connection could be made because the target machine actively refused it.

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman machine init --now

### Describe the results you received

Error: Command execution failed with exit code 125 Command execution failed with exit code 125 Error: head request failed: https://github.com/containers/podman-machine-wsl-os/releases/latest/download: Head "https://github.com/containers/podman-machine-wsl-os/releases/latest/download/5.1-rootfs-amd64.tar.zst": dial tcp 140.82.121.4:443: connectex: No connection could be made because the target machine actively refused it.

### Describe the results you expected

Podman Machine is created and started.

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Windows 11, guessing Podman 5.1.1.

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by odockal** [comment]
@rahulbtchrya Feel free to fill in any other information about system and podman.

**Comment by Luap99** [comment]
Can you run `curl --head "https://github.com/containers/podman-machine-wsl-os/releases/latest/download/5.1-rootfs-amd64.tar.zst"`? This sounds like the system is not allowed to access github.

**Comment by rahulbtchrya** [comment]
> @rahulbtchrya Can you please test the above command?

Hi, below is the output I am getting from the curl command:

curl: (7) Failed to connect to github.com port 443 after 2056 ms: Couldn't connect to server

The Podman Desktop version is 5.1.1

The system is a Windows11 virtual machine.

**Comment by Luap99** [comment]
If you cannot connect to github you have allow such connections in your environment so podman can download the machine image.

Alternatively you could try using the "Installer for restricted environments" on https://podman-desktop.io/downloads/windows which embeds the machine image AFAIK.

In any case this does not sound like a podman bug.

**Comment by rahulbtchrya** [comment]
Hi, I uninstalled the original Podman and installed the "Installer for restricted environments" version of Podman desktop. I am still getting the same error. Is it necessary to configure a proxy for this version of Podman Desktop as well?
