### ISSUE TITLE
There is no max file option like Docker

### ISSUE THREAD

**Issue by limoou** [containers/podman#23191]
### Feature request description

Since there is a max size that can limit the size, why not add a max file to limit the quantity?

**Comment by giuseppe** [comment]
What is max file option?  Do you mean `--ulimit nofile=SOFT:HARD` ?

```
$ podman run --rm --ulimit nofile=100:100 fedora ulimit -n
100
```

**Comment by limoou** [comment]
> What is max file option? Do you mean `--ulimit nofile=SOFT:HARD` ?
> 
> ```
> $ podman run --rm --ulimit nofile=100:100 fedora ulimit -n
> 100
> ```

Docker can use the specified max file=3 to rotate the number of files for log rotation
![image](https://github.com/containers/podman/assets/34920129/c4f7384e-20fa-412b-9c6e-3bdc4f6497a0)
![image](https://github.com/containers/podman/assets/34920129/6899a13b-6d2a-409a-8877-67f0bcffd93b)

Podman does not have this option and can only use -- log opt path={path} in conjunction with logrotate to complete this function, which is obviously troublesome

**Comment by giuseppe** [comment]
thanks, that is already tracked here: https://github.com/containers/conmon/issues/211
