### ISSUE TITLE
libkrun machine start stucks if cpus greater than available on the machine

### ISSUE THREAD

**Issue by jeffmaury** [containers/podman#23194]
### Issue Description

On my Mac M2Pro I tried to run `podman machine init --cpus 12 --memory 16384` --now and the process is stuck

I noticed that the limit on my machine is 8 and system info reports I have 8 cpus for performance and 4 for efficiency

### Steps to reproduce the issue

Steps to reproduce the issue
1. Enable libkrun
2. `podman machine init --cpus 12 --memory 16384`

### Describe the results you received

Process never returns

### Describe the results you expected

Podman machine should start

### podman info output

```yaml
N/A
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

### Additional environment details

Using podman from main branch

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by slemeur** [comment]
I faced the same issue. It also affect resizing an existing machine
I was expecting a timeout at the creation of the podman machine.

In order to get things sorted out, I did:
`killall qemu-system-aarch64 gvproxy podman krunkit`

**Comment by jakecorrenti** [comment]
I can take a look at this

**Comment by slemeur** [comment]
Do we have any update on that one? I think it's an important bug for 5.2, as we would like to start speaking about libkrun.

**Comment by jakecorrenti** [comment]
No update due to hardware issues. 

@Luap99  or @ashley-cui any chance you have the cycles to take this over?

**Comment by Luap99** [comment]
I can reproduce but I know nothing about krunkit/libkrun.
The question is who should validate the cpus? Podman or krun? The command line passed to krun is `krunkit --cpus 10 --memory 2048` and the krunkit hangs.

Doing the same with vfkit it accepts 10 cpus and even shows 10 cpus in the VM despite my laptop only having 8. So I guess it is best for libkrun to match that behaviour?
If krun does not do that then it should error out IMO.

cc @slp

**Comment by jeffmaury** [comment]
My understanding is that libkrun has a limitation to 8 CPUs so the check should be there.

**Comment by Luap99** [comment]
> My understanding is that libkrun has a limitation to 8 CPUs so the check should be there.

I don't think this applies here. We boot the fedora coreos image with the standard kernel. The krun limit AFAIK is for the embedded kernel used by the krun container runtime for example.

**Comment by slp** [comment]
The limit is also in libkrun on macOS until we switch from GICv2 to GICv3, something we plan to do on Q4. Until then, krunkit should check for this (cc/ @tylerfanelli).

**Comment by tylerfanelli** [comment]
Hi, I've just been made aware of this. We can check within krunkit. We can set a max value of 8 vCPUs on krunkit and fail if input is larger than this for the time being?

**Comment by Luap99** [comment]
Failing works for me until you can support more cores.

**Comment by jakecorrenti** [comment]
@jeffmaury see https://github.com/containers/krunkit/pull/14

**Comment by slp** [comment]
#23342 prevents `podman machine start` from gettin stuck, failing instead. That said, the actual error can only be seen when run with `--log-level=debug`. It may be worth checking the number of CPUs somewhere in the provider code.
