### ISSUE TITLE
podman network disconnect for bridged network rootless containers

### ISSUE THREAD

**Issue by iamtimtok** [containers/podman#23216]
### Feature request description

I have a rootless container that is using the default bridged network.  At some point I would like to disconnect the network to this container while it is running.  I have tried:
podman network disconnect podman vigorous_shaw 
but I am getting the following error:
Error: "slirp4netns" is not supported: invalid network mode

### Suggest potential solution

I am not aware of any alternative solution at the moment, but it would be great if someone can suggest one.

**Comment by Luap99** [comment]
> I have a rootless container that is using the default bridged network

Per you error message you don't, is using slirp4netns or since 5.0 pasta as default. If you want to use the default bridge network then you must create the container with `--network bridge` or `--network podman` then `podman network connect/disconnect` will work as expected.
