### ISSUE TITLE
Podman 3.4 only binds to IPv6

### ISSUE THREAD

**Issue by t3r6** [containers/podman#23231]
### Issue Description

Docker binds to both ipv4 and ipv6 by default but looks like Podman only binds to ipv6.

It can cause issues with some very old protocols that do not support ipv6 and get confused where to send requests, like protocol [NATNEG](https://wiki.tockdom.com/wiki/Network_Protocol/Server/mariokartwii.natneg.gs.nintendowifi.net) which is commonly used in games.

```
~$ podman -v
podman version 3.4.4
```

Not sure about the latest `podman` release since I can't run it because of the missing `pasta` library.

### Steps to reproduce the issue

Steps to reproduce the issue
**Docker example**
1. Run my application with 
```
docker run --rm --name ffa -itd   -p 3455:3455/udp  docker.io/painkillergameclassic/pkserver:main
```
2. Check with `netstat` and `ss`
```
~$ netstat -ano | grep 3455
udp        0      0 0.0.0.0:3455            0.0.0.0:*                           off (0.00/0/0)
udp6       0      0 :::3455                 :::*                                off (0.00/0/0)

~$ ss -ntulp | grep 3455
udp   UNCONN 0      0            0.0.0.0:3455       0.0.0.0:*          
udp   UNCONN 0      0               [::]:3455          [::]:*   
```

**Podman example**
1. Run my application with 
```
podman run --rm --name ffa -itd   -p 3455:3455/udp  docker.io/painkillergameclassic/pkserver:main
```
2. Check with `netstat` and `ss`
```
~$ netstat -ano | grep 3455
udp6       0      0 :::3455                 :::*                                off (0.00/0/0)

~$ ss -ntulp | grep 3455
udp   UNCONN 0      0                  *:3455             *:*    users:(("exe",pid=3278,fd=12)) 
```

### Describe the results you received

Describe the results you received

With Docker, I can see ping on my game server as a client and can join it. NATNEG is successful.

With Podman, I can't see ping on my game server as a client and I can't join it. I receive this error in the game:

```
NAT Negotiation error: Partnet did not register with the NAT Negotiation Server
```

### Describe the results you expected

Podman should bind to both ipv4 and ipv6.

### podman info output

If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.

I running a Virtual Box VM Version 7.0.18 r162988 (Qt5.15.2).
OS - Ubuntu 22.04 amd64
```
$ cat /etc/os-release 

PRETTY_NAME="Ubuntu 22.04.4 LTS"

```
Podman version that comes with Ubuntu 22.04
```
~$ podman -v
podman version 3.4.4
```
```


### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
We do not support older version upstream.

Your output (`*:3455`) clearly shows that the port is bound to both ipv4 and the ipv6 address on the host so that is not the problem. Note that netstat is lying to you in this case and it is deprecated, ss uses `*` to tell you it is bind all ipv4 and ipv6 addresses.

I am not familiar with NATNEG but testing with a new podman and pasta might be worth a try.
Otherwise if you want a more docker like behaviour run podman as root.

**Comment by YevheniiPokhvalii** [comment]
> We do not support older version upstream.
> 
> Your output (`*:3455`) clearly shows that the port is bound to both ipv4 and the ipv6 address on the host so that is not the problem. Note that netstat is lying to you in this case and it is deprecated, ss uses `*` to tell you it is bind all ipv4 and ipv6 addresses.
> 
> I am not familiar with NATNEG but testing with a new podman and pasta might be worth a try. Otherwise if you want a more docker like behaviour run podman as root.

I see your point. I'll try a new version when they fix pasta in brew.
However, it's worth mentioning that my issue is actually connected with the Podman bridge network and not root perimission.
Netstat is not lying - it gives different outputs for Docker and Podman and those results actually make a difference on a connection to the server.

**Comment by t3r6** [comment]
> We do not support older version upstream.
> 
> Your output (`*:3455`) clearly shows that the port is bound to both ipv4 and the ipv6 address on the host so that is not the problem. Note that netstat is lying to you in this case and it is deprecated, ss uses `*` to tell you it is bind all ipv4 and ipv6 addresses.
> 
> I am not familiar with NATNEG but testing with a new podman and pasta might be worth a try. Otherwise if you want a more docker like behaviour run podman as root.

I see your point. I'll try a new version when they fix pasta in brew.
However, it's worth mentioning that my issue is actually connected with the Podman bridge network and not root perimission.
Netstat gives different outputs for Docker and Podman and those results actually make a difference on a connection to the server.
