### ISSUE TITLE
On MacOS with krunkit installed, the `run basic podman commands [It] Volume ops` test fails

### ISSUE THREAD

**Issue by cevich** [containers/podman#23296]
### Issue Description

On MacOS with krunkit installed, the `run basic podman commands [It] Volume ops` test fails

### Steps to reproduce the issue

Steps to reproduce the issue
1. On MacOS, `brew tap slp/krunkit`, `brew install krunkit`.
1. Remove conflicting symlink `rm -vf /opt/homebrew/bin/vfkit` ([ref. PR](https://github.com/slp/homebrew-krunkit/pull/1))
1. `brew tap cfergeau/crc` then `brew install vfkit`
1. Clone the podman repo
1. `export CONTAINERS_MACHINE_PROVIDER="libkrun"`
1. `make localmachine`

### Describe the results you received

[Example annotated log](https://api.cirrus-ci.com/v1/artifact/task/4648064202309632/html/mac-libkrun-podman-darwin-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-ops--1)

### Describe the results you expected

Test should pass

### podman info output

```yaml
Ref. related build CI task: https://cirrus-ci.com/task/5136030032986112
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

[Mac setup PR](https://github.com/containers/automation/pull/208): Not in production use at the time this issue was open.

### Additional information

Happens every run.

**Comment by rhatdan** [comment]
@slp FYI

**Comment by Luap99** [comment]
Testing locally I see that mounts are supported and the default mounts should be the same with applehv so I don't see a reason why this should fail with krun

**Comment by slp** [comment]
```
/Users/cevichTesting-0-worker/ci/task-4648064202309632/bin/darwin/podman -r run -v /private/tmp/ci/ginkgo1303331317:/test:Z quay.io/libpod/alpine_nginx ls /test/attr-test-file
  Trying to pull quay.io/libpod/alpine_nginx:latest...
  Getting image source signatures
  Copying blob sha256:d2c7362ca710ad35a846a34571a7c3450ea3cce04efcbcb4d3af276eda154ade
  Copying blob sha256:df9b9388f04ad6279a7410b85cedfdcb2208c0a003da7ab5613af71079148139
  Copying blob sha256:71895e83ea49901b7b752bbf3ca19a54148a5f4ab5fdff3dca9bcd59d44c59e3
  Copying config sha256:ecea49d99daa5bd62ebaef1338f6bc4c948bf2651b139160404f9c1c48fcd85c
  Writing manifest to image destination
  WARNING: image platform (linux/amd64) does not match the expected platform (linux/arm64)
  Error: statfs /private/tmp/ci/ginkgo1303331317: no such file or directory
```

How is the `/private/tmp/ci/ginkgo1303331317` created? Is the test code publicly available somewhere?

**Comment by Luap99** [comment]
@slp on podman main, this is what I am using.
```
$ export CONTAINERS_MACHINE_PROVIDER=libkrun
$ TMPDIR=/private/tmp make localmachine FOCUS="Volume ops"
```

But this works for me so there is something special with the CI setup and likely not related to krun.

Possible the flake was not fixed or somehow special for libkrun: https://github.com/containers/podman/issues/22569

**Comment by cevich** [comment]
> Possible the flake was not fixed or somehow special for libkrun

Correct, I've never seen this during my recent libkrun testing, when `CONTAINERS_MACHINE_PROVIDER=`.  With libkrun, it's not a flake, it fails 100% of the time.

**Comment by cevich** [comment]
In case it matters, in this CI environment:

* We're running as a regular user w/ any admin permissions.
* `$TMPDIR=/private/tmp/ci` and `$HOME=/home/$USER/ci`.
* A local SSD volume (root) is mounted on both `$TMPDIR` and `/home/$USER`.

**Comment by cevich** [comment]
> How is /private/tmp/ci/ginkgo1303331317 created? Is the test code publicly available somewhere?

I believe it's created in the test here:

https://github.com/containers/podman/blob/36bab759b25621ed459ed3c662aa70e27e2e90a6/pkg/machine/e2e/basic_test.go#L65

**Comment by slp** [comment]
@cevich I think we're going to need some debugging to dig deeper into this issue. Is it possible to connect to the CI machine to run some tests? It'd be interesting doing a manual `podman machine init && podman machine start`, and then connecting to the VM with `podman machine ssh` and checking if the volumes `/private` and `/Users` are exposed to the guest.

**Comment by cevich** [comment]
> Is it possible to connect to the CI machine

Yes, and in fact I'm using a Mac that's already isolated from the rest of our system.

**Comment by slp** [comment]
Thanks to @cevich help, we were able to debug this issue. https://github.com/containers/libkrun/pull/209 fixes this.

**Comment by cevich** [comment]
Thanks @slp for "getting your hands dirty" and figuring it out.

FYI- I'll be off on PTO next week, so won't be enabling libkrun testing in Podman until I return.  There are changes needed on the Mac's used for CI and I don't want to risk breaking something while I'm away :wink:

**Comment by Luap99** [comment]
@slp Is there a new krunkit version with the fix we can use?

**Comment by slp** [comment]
> @slp Is there a new krunkit version with the fix we can use?

Yes, it also includes the ability to increase the SHM window of virtio-gpu for running larger AI models. We're testing it now and we'll send a PR to podman by the end of the week.
