### ISSUE TITLE
Another race: completion: no such container/pod

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#23327]
Seeing this on 100% of my laptop runs, parallelized, in the completion test:
```
# [08:17:33.191977368] $ bin/podman __completeNoDesc  container clone
# [08:17:35.303772119] [Debug] [Error] could not find container 434f172ce4e01a95e0a982202771b1f44d59ee77011cf30b4a68ca42695ca789 pod (id 9cf7f239db729a452efd4aa3504cb2affada2dd0744506d0d2e2f5aee0f9eef0) in state: no such pod
```
or
```
# [08:29:09.423573500] $ bin/podman pod stats --no-stream --format {{"\n"}}
# [08:29:10.813740865] Error: no pod with ID cfae61793335459d1500f57b642f1303aaf09e749056cf215daa06879e510243 found in database: no such pod
```
or
```
# [08:37:46.860673870] $ bin/podman __completeNoDesc  container start arg arg
# [08:37:48.074021817] [Debug] [Error] could not find container d8fe9ff54a9252cc6dc3edd3b860fff2dd454e04b850c441abf72e172605fe15 pod (id d4cd52d0e48caf07e968178f5dd21f01c3acaf6c180c06b11e76927d0124ea88) in state: no such pod
```
I have not yet found a reproducer (other than running parallel bats tests)

**Comment by edsantiago** [comment]
Forgot to mention: this is with #23325 cherry-picked

**Comment by Luap99** [comment]
yeah that is most likely still the same issue as shows the same no such pod issue so my PR doesn't fix it.

**Comment by Luap99** [comment]
The `no pod with ID ...` is a new one and looks specific for podman stats not podman ps.

**Comment by edsantiago** [comment]
Seems to check out. Over lots of runs, I see the `container` one everywhere but the `no pod` one only in `podman pod stats`. That gives me something to try as a reproducer. And, am trying your new #23325 now.

**Comment by Luap99** [comment]
As I don't want to create even more PRs/branches I pushed the commit for the pod stats issue also to https://github.com/containers/podman/pull/23325
