### ISSUE TITLE
VirusTotal Alerts for podman on macOS

### ISSUE THREAD

**Issue by paul-cossey** [containers/podman#23377]
### Issue Description

Hi, Folks

I know some other have raised the windows MSI installer previously, but I've not seen one for macOS so raising for awareness.

https://www.virustotal.com/ is flagging Thonny as potential Malware. I'm sure these are false positives, the most recent scan just now has two vendors flagging on both architecture versions.

amd64: https://www.virustotal.com/gui/file/33af62588ba4c68c9e24aab9040f13e1a6de132600e3dc20aed19051153535e5?nocache=1
arm64: https://www.virustotal.com/gui/file/737e58a4631b1670220472f8b1d0ffd5c05386d823ecf8ac468f6ca928fb193b?nocache=1
![Screenshot 2024-07-23 at 16 15 18](https://github.com/user-attachments/assets/701749ba-e321-471c-846b-bbd5d7e5db7e)

FWIW Podman Desktop gets a clean bill of health: https://www.virustotal.com/gui/file/8f43eff3b4c54db8bad9c0c1c00f49e83580988660a2f7ce5ee548e3643d9a3c?nocache=1 

Many folks use Virus Total in an automated way to gauge the safety of software before rolling out to their fleet of computers, you may wish to work with the vendors flagging your software to get it safe listed/flags removed. It's _very_ common for the automation to halt the rollout of title if 2 or vendors flag the software requiring manual intervention.

Thanks!

### Steps to reproduce the issue

Steps to reproduce the issue
1. Download the latest version of podman for macOS
2. upload to https://www.virustotal.com/

### Describe the results you received

Two security vendors have flagged the software as being malicious 

### Describe the results you expected

All vendors pass the software as ok

### podman info output

```yaml
N/A
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

N/A

### Additional information

N/A

**Comment by Luap99** [comment]
Golang binaries are often flagged as false positive. https://go.dev/doc/faq#virus

> you may wish to work with the vendors flagging your software to get it safe listed/flags removed

We do have time to deal with such vendors, especially not when it is not even clear where one should report this.
