### ISSUE TITLE
CI tests: userns auto tests are skipped as root due missing subuid setup

### ISSUE THREAD

**Issue by Luap99** [containers/podman#23383]
May CI tests are skipped because there is no containers entry in /etc/sub{u,g}id setup. This means we are not testing it properly

i.e.
```
[+0692s] ok 338 [170] podman userns=auto in config file in 192ms # skip no IDs allocated for user 'containers'
```
https://api.cirrus-ci.com/v1/artifact/task/6480607260180480/html/sys-podman-fedora-40-root-host-sqlite.log.html

Same in the e2e tests
```
→ Enter [It] podman build with --userns=auto - /var/tmp/go/src/github.com/containers/podman/test/e2e/run_userns_test.go:45 @ 07/11/24 15:35:12.569
       [SKIPPED] cannot find mappings for the current user
```
https://api.cirrus-ci.com/v1/artifact/task/5904463167225856/html/int-podman-fedora-40-root-host-sqlite.log.html

**Comment by edsantiago** [comment]
Would something like this be a fix? I don't like the hardcoded uid but don't really see a way to autoallocate one.
```diff
diff --git a/contrib/cirrus/setup_environment.sh b/contrib/cirrus/setup_environment.sh
index 420819ffdd..3c5ebf0f5f 100755
--- a/contrib/cirrus/setup_environment.sh
+++ b/contrib/cirrus/setup_environment.sh
@@ -285,6 +285,13 @@ case "$PRIV_NAME" in
     *) die_unknown PRIV_NAME
 esac
 
+# Root user namespace
+for which in uid gid;do
+    if ! grep -qE '^containers:' /etc/sub$which; then
+        echo 'containers:200000:65536' >>/etc/sub$which
+    fi
+done
+
 # FIXME! experimental workaround for #16973, the "lookup cdn03.quay.io" flake.
 #
 # If you are reading this on or after April 2023:
```

**Comment by Luap99** [comment]
yes, although given it is used for userns=auto we may need to allocate a bigger range than `65536`, i.e. `1048576` (there plenty of free ids). Reason userns=auto tries to pick a unique free range according from that for each container. And as we think about running sys tests in parallel we have to make sure there are enough ids for podman to use in that case.

**Comment by edsantiago** [comment]
`int` tests were easy. [sys](https://api.cirrus-ci.com/v1/artifact/task/5898057223503872/html/sys-podman-debian-13-root-host-sqlite.log.html#t--00109) are beyond my ken:
```
[+0288s] not ok 109 [030] podman run - rootfs with idmapped mounts in 1764ms
...
<+012ms> # # podman run --uidmap=0:1000:10000 --rm --rootfs /tmp/CI_Wxqp/podman_bats.1rNMIZ/rootfs:idmap=uids=0-1001-10000;gids=0-1002-10000 stat -c %u:%g /bin
<+066ms> # Error: failed to create idmapped mount: operation not permitted
```
First problem: failure does not reproduce on my f40 laptop. 

Second problem: test is actually broken, needs a fix:
```diff
-    run_podman run --rm --uidmap=0:1000:10000 -v volume:/volume:idmap --rootfs $romount stat -c %u:%g /volume
+    run_podman run --rm --uidmap=0:1000:10000 -v $myvolume:/volume:idmap --rootfs $romount stat -c %u:%g /volume
```
When I fix it, test fails on my laptop with:
```
[08:49:52.744732625] # /home/esm/src/atomic/2018-02.podman/libpod/bin/podman run --rm --uidmap=0:1000:10000 -v my-volume-t1-w7nuobt1:/volume:idmap --rootfs /tmp/podman_bats.kC6FCy/rootfs stat -c %u:%g /volume/myfile
   [08:49:52.858913405] Error: mapping user 0:0: host ID 0 cannot be mapped to a container ID
   [08:49:52.861820205] [ rc=126 (** EXPECTED 0 **) ]
```
Any userns experts care to weigh in?
