### ISSUE TITLE
pasta doesn't map IPv6 ports

### ISSUE THREAD

**Issue by akostadinov** [containers/podman#23403]
### Issue Description

In the past (I believe podman 3 with slirpvnetns) it mapped ports on IPv4 as well IPv6. Like:
```json
"CreateCommand": [
                    "/usr/bin/podman",
                    "run",
                    "-d",
                    "-p",
                    "5432:5432",
                    "-e",
                    "POSTGRES_USER=postgres",
                    "-e",
                    "POSTGRES_DB=zync",
                    "--name",
                    "postgres14-test",
                    "cimg/postgres:14.12"
]
```

Now with podman5 and pasta it seems only IPv4 is bound. If I add the command line option `--network=slirp4netns` then previous behavior is observed.

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman run "-d" "-p"  "5432:5432" "-e" "POSTGRES_USER=postgres" "-e"  "POSTGRES_DB=zync" "--name" "postgres14-test" "cimg/postgres:14.12"

### Describe the results you received

```
🐚 telnet ::1 5432
Trying ::1...
telnet: connect to address ::1: Connection refused
```

### Describe the results you expected

```
🐚 telnet ::1 5432
Trying ::1...
Connected to ::1.
```

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

Fedora 40

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
You need a rotatable ipv6 setup for pasta to activate ipv6 mode, see https://github.com/containers/podman/issues/22959

**Comment by akostadinov** [comment]
I assume you mean "routable", ust for anybody else looking at this. I guess auto-correction is to blame.

**Comment by Luap99** [comment]
yes fixed
