### ISSUE TITLE
Podman build fails buildah 124 bud-preserve-subvolumes and 136 bud-volume-perms

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman#23420]
### Issue Description

After vendoring Buildah v1.37 into the Podman v5.2 release branch, these tests failed:

Failed tests (2):

    124 bud-preserve-subvolumes
    136 bud-volume-perms

and they were included a couple weeks ago in Buildah via this PR: https://github.com/containers/buildah/pull/5604. In particular, this commit in the PR tweaked the two tests that are failing: https://github.com/containers/buildah/commit/a7098c776a7fda585358c91496d35ce690ea9fb7

Both tests had the new `--compat-volumes` option added to them.

### Steps to reproduce the issue

See description

### Describe the results you received

Test failures

### Describe the results you expected

happy tests

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by TomSweeneyRedHat** [comment]
@edsantiago FYI

**Comment by Luap99** [comment]
Because you do not wire in the new option https://github.com/containers/podman/pull/23417#pullrequestreview-2204212121
