### ISSUE TITLE
machine rm: unable to clean up gvproxy: remove xxxx.pid: The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#23472]
In [hyperv windows rootless](https://api.cirrus-ci.com/v1/artifact/task/4723761537089536/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-init-machine-init-rootless-docker-sock-check--1):
```
podman machine init
  machine init rootless docker.sock check
...
  C> podman.exe machine rm --force 97cd37622ad8
  Error: unable to clean up gvproxy: remove C:\Users\ADMINI~1\AppData\Local\Temp\podman\gvproxy.pid: The process cannot access the file because it is being used by another process.
```
I don't know if this is the first instance. I rarely look at podman-machine flakes because there are more every day than any human can possibly handle. Every once in a while I peek at one or two, and if I see a new-to-me flake I'll file it.

**Comment by edsantiago** [comment]
A few more

* windows : machine-hyperv podman windows rootless host sqlite
  * PR #23462
    * [07-31 15:53](https://api.cirrus-ci.com/v1/artifact/task/4723761537089536/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-init-simple-init-with-start--1) in podman machine init simple init with start
    * [07-31 15:53](https://api.cirrus-ci.com/v1/artifact/task/4723761537089536/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-init-machine-init-with-cpus--disk-size--memory--timezone--1) in podman machine init machine init with cpus, disk size, memory, timezone
    * [07-31 15:53](https://api.cirrus-ci.com/v1/artifact/task/4723761537089536/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-init-machine-init-rootless-docker-sock-check--1) in podman machine init machine init rootless docker.sock check
    * [07-31 15:53](https://api.cirrus-ci.com/v1/artifact/task/4723761537089536/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-init-machine-init-rootful-with-docker-sock-check--1) in podman machine init machine init rootful with docker.sock check
    * [07-31 15:53](https://api.cirrus-ci.com/v1/artifact/task/4723761537089536/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-start-start-simple-machine--1) in podman machine start start simple machine
    * [07-31 15:53](https://api.cirrus-ci.com/v1/artifact/task/4723761537089536/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-start-start-machine-already-started--1) in podman machine start start machine already started
    * [07-31 15:53](https://api.cirrus-ci.com/v1/artifact/task/4723761537089536/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-start-start-machine-with-conflict-on-SSH-port--1) in podman machine start start machine with conflict on SSH port
    * [07-31 15:53](https://api.cirrus-ci.com/v1/artifact/task/4723761537089536/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-start-start-only-starts-specified-machine--1) in podman machine start start only starts specified machine
    * [07-31 15:53](https://api.cirrus-ci.com/v1/artifact/task/4723761537089536/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-start-start-two-machines-in-parallel--1) in podman machine start start two machines in parallel
    * [07-31 15:53](https://api.cirrus-ci.com/v1/artifact/task/4723761537089536/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-ssh-ssh-to-running-machine-and-check-os-type--1) in podman machine ssh ssh to running machine and check os-type
    * [07-31 15:53](https://api.cirrus-ci.com/v1/artifact/task/4723761537089536/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Basic-ops--1) in run basic podman commands Basic ops
    * [07-31 15:53](https://api.cirrus-ci.com/v1/artifact/task/4723761537089536/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-should-be-disabled-by-command-line--1) in run basic podman commands Volume should be disabled by command line
    * [07-31 15:53](https://api.cirrus-ci.com/v1/artifact/task/4723761537089536/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Podman-ops-with-port-forwarding-and-gvproxy--1) in run basic podman commands Podman ops with port forwarding and gvproxy
    * [07-31 15:53](https://api.cirrus-ci.com/v1/artifact/task/4723761537089536/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--run-basic-podman-commands-podman-volume-on-non-standard-path--1) in run basic podman commands podman volume on non-standard path
  * PR #23455
    * [07-31 14:39](https://api.cirrus-ci.com/v1/artifact/task/6666573753090048/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html) in 22551
    * [07-31 14:39](https://api.cirrus-ci.com/v1/artifact/task/6666573753090048/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html) in 22551
    * [07-31 14:39](https://api.cirrus-ci.com/v1/artifact/task/6666573753090048/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--run-basic-podman-commands-podman-volume-on-non-standard-path--1) in run basic podman commands podman volume on non-standard path
    * [07-31 14:39](https://api.cirrus-ci.com/v1/artifact/task/6666573753090048/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-reset-reset-with-running-machine-and-other-machines-idle--1) in podman machine reset reset with running machine and other machines idle
    * [07-31 14:39](https://api.cirrus-ci.com/v1/artifact/task/6666573753090048/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-rm-Remove-running-machine--1) in podman machine rm Remove running machine
    * [07-31 14:39](https://api.cirrus-ci.com/v1/artifact/task/6666573753090048/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-rm-Remove-machine-sharing-ssh-key-with-another-machine--1) in podman machine rm Remove machine sharing ssh key with another machine
    * [07-31 14:39](https://api.cirrus-ci.com/v1/artifact/task/6666573753090048/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-init-simple-init-with-start--1) in podman machine init simple init with start
    * [07-31 14:39](https://api.cirrus-ci.com/v1/artifact/task/6666573753090048/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-init-machine-init-with-cpus--disk-size--memory--timezone--1) in podman machine init machine init with cpus, disk size, memory, timezone
    * [07-31 14:39](https://api.cirrus-ci.com/v1/artifact/task/6666573753090048/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-init-machine-init-rootless-docker-sock-check--1) in podman machine init machine init rootless docker.sock check
    * [07-31 14:39](https://api.cirrus-ci.com/v1/artifact/task/6666573753090048/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-init-machine-init-rootful-with-docker-sock-check--1) in podman machine init machine init rootful with docker.sock check
    * [07-31 14:39](https://api.cirrus-ci.com/v1/artifact/task/6666573753090048/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-list-list-machine--check-if-running-while-starting--1) in podman machine list list machine: check if running while starting
    * [07-31 14:39](https://api.cirrus-ci.com/v1/artifact/task/6666573753090048/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-set-set-machine-cpus--disk--memory--1) in podman machine set set machine cpus, disk, memory
    * [07-31 14:39](https://api.cirrus-ci.com/v1/artifact/task/6666573753090048/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-set-no-settings-should-change-if-no-flags--1) in podman machine set no settings should change if no flags
    * [07-31 14:39](https://api.cirrus-ci.com/v1/artifact/task/6666573753090048/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-set-set-rootful-with-docker-sock-change--1) in podman machine set set rootful with docker sock change
    * [07-31 14:39](https://api.cirrus-ci.com/v1/artifact/task/6666573753090048/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-set-set-while-machine-already-running--1) in podman machine set set while machine already running
  * PR #23425
    * [07-29 08:18](https://api.cirrus-ci.com/v1/artifact/task/6747039428509696/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html) in 22551
    * [07-29 08:18](https://api.cirrus-ci.com/v1/artifact/task/6747039428509696/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html) in 22551
    * [07-29 08:18](https://api.cirrus-ci.com/v1/artifact/task/6747039428509696/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-stop-Stop-running-machine--1) in podman machine stop Stop running machine
    * [07-29 08:18](https://api.cirrus-ci.com/v1/artifact/task/6747039428509696/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Basic-ops--1) in run basic podman commands Basic ops
    * [07-29 08:18](https://api.cirrus-ci.com/v1/artifact/task/6747039428509696/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Volume-should-be-disabled-by-command-line--1) in run basic podman commands Volume should be disabled by command line
    * [07-29 08:18](https://api.cirrus-ci.com/v1/artifact/task/6747039428509696/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--run-basic-podman-commands-Podman-ops-with-port-forwarding-and-gvproxy--1) in run basic podman commands Podman ops with port forwarding and gvproxy
    * [07-29 08:18](https://api.cirrus-ci.com/v1/artifact/task/6747039428509696/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--run-basic-podman-commands-podman-volume-on-non-standard-path--1) in run basic podman commands podman volume on non-standard path
    * [07-29 08:18](https://api.cirrus-ci.com/v1/artifact/task/6747039428509696/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-init-simple-init-with-start--1) in podman machine init simple init with start
    * [07-29 08:18](https://api.cirrus-ci.com/v1/artifact/task/6747039428509696/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-init-machine-init-with-cpus--disk-size--memory--timezone--1) in podman machine init machine init with cpus, disk size, memory, timezone
    * [07-29 08:18](https://api.cirrus-ci.com/v1/artifact/task/6747039428509696/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-init-machine-init-rootless-docker-sock-check--1) in podman machine init machine init rootless docker.sock check
    * [07-29 08:18](https://api.cirrus-ci.com/v1/artifact/task/6747039428509696/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-init-machine-init-rootful-with-docker-sock-check--1) in podman machine init machine init rootful with docker.sock check
    * [07-29 08:18](https://api.cirrus-ci.com/v1/artifact/task/6747039428509696/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-ssh-ssh-to-running-machine-and-check-os-type--1) in podman machine ssh ssh to running machine and check os-type
    * [07-29 08:18](https://api.cirrus-ci.com/v1/artifact/task/6747039428509696/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-rm-Remove-running-machine--1) in podman machine rm Remove running machine
    * [07-29 08:18](https://api.cirrus-ci.com/v1/artifact/task/6747039428509696/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-rm-Remove-machine-sharing-ssh-key-with-another-machine--1) in podman machine rm Remove machine sharing ssh key with another machine
    * [07-29 08:18](https://api.cirrus-ci.com/v1/artifact/task/6747039428509696/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-reset-reset-with-running-machine-and-other-machines-idle--1) in podman machine reset reset with running machine and other machines idle
  * PR #23373
    * [07-23 15:25](https://api.cirrus-ci.com/v1/artifact/task/5690016490323968/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html) in 22551
    * [07-23 15:25](https://api.cirrus-ci.com/v1/artifact/task/5690016490323968/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html) in 22551
    * [07-23 15:25](https://api.cirrus-ci.com/v1/artifact/task/5690016490323968/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-set-set-while-machine-already-running--1) in podman machine set set while machine already running
  * PR #23290
    * [08-01 18:57](https://api.cirrus-ci.com/v1/artifact/task/4609469760405504/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html) in 22551
    * [08-01 18:57](https://api.cirrus-ci.com/v1/artifact/task/4609469760405504/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html) in 22551
    * [08-01 18:57](https://api.cirrus-ci.com/v1/artifact/task/4609469760405504/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-init-simple-init-with-start--1) in podman machine init simple init with start
    * [08-01 18:57](https://api.cirrus-ci.com/v1/artifact/task/4609469760405504/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-init-machine-init-with-cpus--disk-size--memory--timezone--1) in podman machine init machine init with cpus, disk size, memory, timezone
    * [08-01 18:57](https://api.cirrus-ci.com/v1/artifact/task/4609469760405504/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-init-machine-init-rootless-docker-sock-check--1) in podman machine init machine init rootless docker.sock check
    * [08-01 18:57](https://api.cirrus-ci.com/v1/artifact/task/4609469760405504/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-init-machine-init-rootful-with-docker-sock-check--1) in podman machine init machine init rootful with docker.sock check
    * [08-01 18:57](https://api.cirrus-ci.com/v1/artifact/task/4609469760405504/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-set-set-machine-cpus--disk--memory--1) in podman machine set set machine cpus, disk, memory
    * [08-01 18:57](https://api.cirrus-ci.com/v1/artifact/task/4609469760405504/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-set-no-settings-should-change-if-no-flags--1) in podman machine set no settings should change if no flags
    * [08-01 18:57](https://api.cirrus-ci.com/v1/artifact/task/4609469760405504/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-set-set-rootful-with-docker-sock-change--1) in podman machine set set rootful with docker sock change
    * [08-01 18:57](https://api.cirrus-ci.com/v1/artifact/task/4609469760405504/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-set-set-while-machine-already-running--1) in podman machine set set while machine already running
    * [08-01 18:57](https://api.cirrus-ci.com/v1/artifact/task/4609469760405504/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-start-start-simple-machine--1) in podman machine start start simple machine
    * [08-01 18:57](https://api.cirrus-ci.com/v1/artifact/task/4609469760405504/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-start-start-machine-already-started--1) in podman machine start start machine already started
    * [08-01 18:57](https://api.cirrus-ci.com/v1/artifact/task/4609469760405504/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-start-start-machine-with-conflict-on-SSH-port--1) in podman machine start start machine with conflict on SSH port
    * [08-01 18:57](https://api.cirrus-ci.com/v1/artifact/task/4609469760405504/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-start-start-only-starts-specified-machine--1) in podman machine start start only starts specified machine
    * [08-01 18:57](https://api.cirrus-ci.com/v1/artifact/task/4609469760405504/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-start-start-two-machines-in-parallel--1) in podman machine start start two machines in parallel
    * [08-01 18:57](https://api.cirrus-ci.com/v1/artifact/task/4609469760405504/html/machine-hyperv-podman-windows-rootless-host-sqlite.log.html#t--podman-machine-stop-Stop-running-machine--1) in podman machine stop Stop running machine

| x | x | x | x | x | x |
| ---: | ---: | ---: | ---: | ---: | ---: |
| machine-hyperv(63) | podman(63) | windows(63) | rootless(63) | host(63) | sqlite(63) |

**Comment by baude** [comment]
this error has been switched from a hard error to soft.  we should no longer see it.
