### ISSUE TITLE
remote: run --restart=always, then wait: timeout

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#23473]
```
[+0113s] not ok 110 [030] podman run --restart=always -- wait
...
<+     > # # podman-remote run -d --restart=always --name=c_t110-iolrdtkp quay.io/libpod/testimage:20240123 false
<+131ms> # eaa555d6a4f6dba6cdac3b177a514e853731c2bdc39ed41feb6f252be111ce66
         #
<+009ms> # # podman-remote wait c_t110-iolrdtkp
<+0020s> # timeout: sending signal TERM to command ‘/var/tmp/go/src/github.com/containers/podman/bin/podman-remote’
<+005ms> # [ rc=124 (** EXPECTED 0 **) ]
         # *** TIMED OUT ***
```

* debian-13 : sys remote debian-13 root host sqlite [remote]
    * [07-31 17:52](https://api.cirrus-ci.com/v1/artifact/task/5445561392824320/html/sys-remote-debian-13-root-host-sqlite.log.html#t--00110) in [sys] [030] podman run --restart=always -- wait
* fedora-40 : sys remote fedora-40 rootless host sqlite [remote]
  * PR #23275
    * [07-31 08:24](https://api.cirrus-ci.com/v1/artifact/task/6446991591342080/html/sys-remote-fedora-40-rootless-host-sqlite.log.html#t--00089) in [sys] [030] podman run --restart=always -- wait
* fedora-40-aarch64 : sys remote fedora-40-aarch64 root host sqlite [remote]
  * PR #23444
    * [07-30 06:44](https://api.cirrus-ci.com/v1/artifact/task/4711954927845376/html/sys-remote-fedora-40-aarch64-root-host-sqlite.log.html#t--00110) in [sys] [030] podman run --restart=always -- wait
    * [07-22 07:48](https://api.cirrus-ci.com/v1/artifact/task/6721323668340736/html/sys-remote-fedora-40-aarch64-root-host-sqlite.log.html#t--00110) in [sys] [030] podman run --restart=always -- wait

| x | x | x | x | x | x |
| ---: | ---: | ---: | ---: | ---: | ---: |
| sys(4) | remote(4) | fedora-40-aarch64(2) | root(3) | host(4) | sqlite(4) |
|  |  | fedora-40(1) | rootless(1) |  |  |
|  |  | debian-13(1) |  |  |  |

**Comment by Luap99** [comment]
I looked into that as it happened a lot in my parallel PR as well but I didn't find any obvious. Overall the wait code is rather ugly as it is polling the status so in theory it could be possible that it misses an exit on a fast restarting container but I don't think this is the case for 20s.

And I tried reproducing for a while without out luck.

**Comment by Luap99** [comment]
Yes you are right kube play --wait uses the same wait API internally possible that they have the same cause.
Although the output there clearly shows that kube got the TERM and then cleans up but somehow hangs and gets killed instead of exiting.

**Comment by cevich** [comment]
Hit this just now: https://api.cirrus-ci.com/v1/artifact/task/4618842666696704/html/sys-remote-fedora-40-aarch64-root-host-sqlite.log.html

**Comment by Luap99** [comment]
I will try to reproduce this, last time I tried to run this for hours in a loop without any errors. Not sure if there is some magic requirement I was missing to trigger it.

**Comment by Luap99** [comment]
```
$ bin/podman run --name c1 -d --restart on-failure  quay.io/libpod/testimage:20240123 false
930bb7f5bab705b0838c0a73a8ea8acd18a4d31c361ce566ab7c5969e45f1fd0
$ time bin/podman wait c1
1

real    0m20.492s
user    0m0.077s
sys     0m0.164s
```

--restart=always has some extra special logic to "make it work" better but using on-failure shows that the current logic is clearly not working properly

**Comment by Luap99** [comment]
Let me know if you see any hangs after https://github.com/containers/podman/pull/23601

**Comment by Luap99** [comment]
Last logged instance on the flake tracker was 8-14 so I am going to close this.
