### ISSUE TITLE
URGENT: CI is broken, Win Installer

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#23495]
Looks like all CI jobs are failing. Restart does not help:
```
Verifying that the machine provider configuration is correct...
Expected "hyperv" as default machine provider but got "wsl"
At C:\Users\Administrator\AppData\Local\cirrus-ci-build\repo\contrib\win-installer\test-installer.ps1:91 char:9
+         throw "Expected `"$expected`" as default machine provider but ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Expected "hyper...r but got "wsl":String) [], RuntimeException
    + FullyQualifiedErrorId : Expected "hyperv" as default machine provider but got "wsl"
```
(and vice-versa, expected wsl got hyperv).  Logs:
* https://cirrus-ci.com/task/5226923922554880?logs=main#L199 (wsl)
* https://cirrus-ci.com/task/4520263289667584?logs=main#L199 (hyperv)

The relevant code claims to have a parameter, `$provider`, but all calls to this function are parameterless. https://github.com/containers/podman/blob/0bc073941a37ec0b9ab2aa9a5493b6be52f56fb2/contrib/win-installer/test-installer.ps1#L83-L91

Needs a Windows expert.

**Comment by edsantiago** [comment]
Also Macintosh is down too.

**Comment by l0rd** [comment]
I have opened [a PR](https://github.com/containers/podman/pull/23501) to temporarily disable the test that's failing and opened a [dedicated issue](https://github.com/containers/podman/issues/23502) to continue investigating the problem.

**Comment by Luap99** [comment]
We can close this then
