### ISSUE TITLE
machine ssh: remote host identification has changed

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#23505]
Noticed by accident in [machine-linux](https://api.cirrus-ci.com/v1/artifact/task/5066225183621120/html/machine-linux-podman-fedora-40-rootless-host-sqlite.log.html#t--podman-machine-ssh-ssh-to-running-machine-and-check-os-type--1)
```
[+0762s] podman machine ssh
           ssh to running machine and check os-type
....
[+0765s]   Image resized.
           Machine init complete
           Starting machine "0326c9aaeb61"
[+0783s] 
           This machine is currently configured in rootless mode. If your containers
           require root permissions (e.g. ports < 1024), or if you run into compatibility
           issues with non-podman clients, you can switch using the following command:
         
           	podman machine set --rootful 0326c9aaeb61
         
[+0785s]   Mounting volume... /tmp/podman_test1724224437:/tmp/podman_test1724224437
[+0786s]   API forwarding listening on: /tmp/podman_test1724224437/podman/0326c9aaeb61-api.sock
           You can connect Docker API clients by setting DOCKER_HOST using the
           following command in your terminal session:
         
                   export DOCKER_HOST='unix:///tmp/podman_test1724224437/podman/0326c9aaeb61-api.sock'
         
           Machine "0326c9aaeb61" started successfully
           /var/tmp/go/src/github.com/containers/podman/bin/podman-remote machine ssh 0326c9aaeb61 cat /etc/os-release
           @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
           @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
           @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
           IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
```

**Comment by Luap99** [comment]
My best guess is that we use the shared known_hosts and it is possible that a previous test used the same ssh port and thus the second test uses a new identification causing this to fail.
I have not looked the the code but I guess we wouldn't care about known_hosts for podman machine so we should pass the right options to make it ignore the file.

**Comment by cevich** [comment]
I remember discussing this or something very similar last year (maybe a Cabal topic?).  The conclusion was the same: PM should ignore the known_hosts file.  I ocastionally find myself in a very similar situation when I want to ssh into a CI VM.  I don't know about other host OS's but on Linux these are the options I use: `-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o CheckHostIP=no`.  That will instead _always_ give you a warning message, but maybe there's a way to stop or mask that.

**Comment by cevich** [comment]
Confirmed, it will always print: `Warning: Permanently added '<FOO>' (ED25519) to the list of known hosts.`  You can suppress that with `-o LogLevel=ERROR` but I can see that as possibly being not so good for PM usage.

**Comment by cevich** [comment]
Nice job @inknos
