### ISSUE TITLE
Error: database volume path does not match our volume path: database configuration mismatch

### ISSUE THREAD

**Issue by shi2wei3** [containers/podman#23515]
### Issue Description

Starting with podman-5.2.0-1.el10, I get the following error in centos-bootc(rpm-ostree) rootless mode
home -> var/home
$HOME=/home/admin
```
Error: database volume path "/home/admin/.local/share/containers/storage/volumes" does not match our volume path "/var/home/admin/.local/share/containers/storage/volumes": database configurat
ion mismatch

```
This bug starts with CentOS-Stream-10-20240805.0 with podman-5.2.0-1.el10
No exists on CentOS-Stream-10-20240802.0 with podman-5.1.2-2.el10

### Steps to reproduce the issue

Steps to reproduce the issue
1. boot centos-bootc:stream10 with podman-5.2.0-1.el10
2. run podman system info in rootless
3.

### Describe the results you received

```
Error: database volume path "/home/admin/.local/share/containers/storage/volumes" does not match our volume path "/var/home/admin/.local/share/containers/storage/volumes": database configurat
ion mismatch

```

### Describe the results you expected

podman system info

### podman info output

```yaml
Error: database volume path "/home/admin/.local/share/containers/storage/volumes" does not match our volume path "/var/home/admin/.local/share/containers/storage/volumes": database configurat
ion mismatch

```
```


### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

centos-bootc:stream10 with podman-5.2.0-1.el10 deployed on a KVM guest

### Additional information

_No response_

**Comment by Luap99** [comment]
@mheon PTAL

**Comment by mheon** [comment]
Ah, I see now. Volume path doesn't exist, so evalSymlinksIfExists doesn't have a symlink to evaluate and so just cleans the path, leading to a `/var/home` vs `/home` mismatch on OSTree.

Best solution probably just to create the path as part of Podman init.

As a workaround, you can `mkdir /home/admin/.local/share/containers/storage/volumes` and, now that the directory exists, the symlink we be evaluated correctly and things should go back to working.

**Comment by j-dominguez9** [comment]
Also having this issue on fedora silverblue after rpm-ostree update

**Comment by mheon** [comment]
Uh-oh, we didn’t cherry pick this into 5.2.1. Will probably require a
second patch release. We want this in the next stable RHEL release

**Comment by rmb938** [comment]
Having same problem as @j-dominguez9  on Fedora Kionite
