### ISSUE TITLE
Has no one solved the problem with macOS installation ?

### ISSUE THREAD

**Issue by dojeee** [containers/podman#23535]
### Issue Description

<img width="1952" alt="image" src="https://github.com/user-attachments/assets/4fb0641e-c42f-443d-9f9f-b84c1005c817">

### Steps to reproduce the issue

Steps to reproduce the issue
1. I installed it according to the official documentation, and there were problems throughout the process.
2.when I click the init and start button. an error message appeared.
<img width="1086" alt="image" src="https://github.com/user-attachments/assets/e4c3661c-6705-41ff-84fa-9f2b24337afa">

3. I don't understand this message what are mean.
4.

### Describe the results you received

Describe the results you received

### Describe the results you expected

I just hope it installs successfully and works fine.

### podman info output

```yaml
podman machine start
Starting machine "podman-machine-default"
Error: vfkit exited unexpectedly with exit code 1
podman info
OS: darwin/amd64
provider: applehv
version: 5.2.0

Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: dial tcp 127.0.0.1:59179: connect: connection refused
podman version
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: dial tcp 127.0.0.1:59179: connect: connection refused
```

### Podman in a container

Yes

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
Looks like you installed the amd64 version instead of the arm version? If you are on an arm system you need to install the arm version as you cannot run podman machine emulated, i.e. https://github.com/containers/podman/releases/download/v5.2.0/podman-installer-macos-arm64.pkg
