### ISSUE TITLE
race: podman run --privileged: ENOENT if /dev/transientdirectory vanishes

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#23582]
In window 1:
```console
# while :;do mkdir /dev/tmpdir;rmdir /dev/tmpdir;done
```
Window 2:
```console
# while :;do podman run --privileged --rm quay.io/libpod/testimage:20240123 true || break;done
```
It takes a while, but eventually the podman window will fail:
```
Error: open /dev/tmpdir: no such file or directory
```
Seen [in CI](https://api.cirrus-ci.com/v1/artifact/task/5220711197835264/html/int-podman-fedora-40-root-container-sqlite.log.html#t--Podman-run-device-podman-run-device-host-device-with-privileged--1)

**Comment by rhatdan** [comment]
Is /dev/tmpdir specified in a config file somewhere?

**Comment by edsantiago** [comment]
Make it `/dev/abcdefghijklmnop` if you like. I believe this is a race between `readdir(/dev)` and recreating `/dev` entries in the container, using `--privileged`. (Disclaimer: I have no idea what I'm talking about)

**Comment by rhatdan** [comment]
Ok, now I have a clue what is causing this.  So we are walking through /dev, when creating --privileged containers in rootful containers and there is a race condition on directory existing.
