### ISSUE TITLE
Change quadlet-generator to ignore missing `/run/containers/systemd` directory

### ISSUE THREAD

**Issue by lovette** [containers/podman#23620]
### Feature request description

As I'm working with Quadlets, I've been seeing this "lstat error":

    [root ~]# /usr/libexec/podman/quadlet -dryrun
    quadlet-generator[18301]: Error occurred resolving path "/run/containers/systemd": lstat /run/containers/systemd: no such file or directory
    quadlet-generator[18301]: No files parsed from [/run/containers/systemd /etc/containers/systemd /usr/share/containers/systemd]

This leads me to questions like "well, why doesn't it exist?" and "who is responsible for creating it?"

Being a busy guy, I've just been silencing it with a quick `mkdir` which of course only works until a reboot and `/run` gets reset.

    [root ~]# mkdir /run/containers/systemd

### Suggest potential solution

I just took a minute to look into it further and it appears to me that the directory missing is not really an *error* condition, and based on #23363 I'm guessing that the user is responsible for creating it if they want it to be used.

If these both are true statements, can quadlet-generator be changed to silently ignore when this particular directory is missing? Or log it as a "notice"?

### Have you considered any alternatives?

I can use `mkdir` when I'm testing manually but the error will still show up in the boot log.

### Additional context

I suspect to a lot of people "error" means "something is broken, you may want to fix it" so ultimately I'm looking for the proper fix 😁

**Comment by Luap99** [comment]
Marking this as bug as this should definitely not log such an error.

**Comment by lovette** [comment]
Good to know, thanks!

FWIW, I'm running podman version 5.2.0-dev-a3e9a2af4.

**Comment by lovette** [comment]
I just upgraded to podman version 5.3.0-dev-734c4b98d and now get an "error" for `/etc/containers/systemd/users` too.

**Comment by rhatdan** [comment]
Care to open a PR?

**Comment by rhatdan** [comment]
These messages are only showing at  "debug" level correct?

grep -r "Error occurred resolving path" .
./cmd/quadlet/main.go:		Debugf("Error occurred resolving path %q: %s", unitDirAdminUser, err)
./cmd/quadlet/main.go:		Debugf("Error occurred resolving path %q: %s", path, err)
./.coverage/coverage.html:                Debugf("Error occurred resolving path %q: %s", path, err)

**Comment by rhatdan** [comment]
Which is only enabled with --dryrun or -v

**Comment by rhatdan** [comment]
So by default these messages are not logged.

**Comment by lovette** [comment]
Ah, I see, that looks to be the case. 

When a directory exists but is empty, the message is clear:

> "No files parsed from [/run/containers/systemd /etc/containers/systemd /usr/share/containers/systemd]"

Perhaps then, since these directories are not mandatory, the message could follow that pattern:

> "No files parsed from /etc/containers/systemd/users; no such directory"

**Comment by Luap99** [comment]
> Ah, I see, that looks to be the case.
> 
> When a directory exists but is empty, the message is clear:
> 
> > "No files parsed from [/run/containers/systemd /etc/containers/systemd /usr/share/containers/systemd]"
> 
> Perhaps then, since these directories are not mandatory, the message could follow that pattern:
> 
> > "No files parsed from /etc/containers/systemd/users; no such directory"

There is no need because the "No files parsed from" message already includes the path so logging ENOENT logs the same path twice for no user benefit. As such quadlet should not log them there, logging permission errors does make sense so I would really only hide it on ENEOENT

**Comment by lovette** [comment]
To clarify, when you say "hide", are you proposing to not log anything when a search directory doesn't exist? That's fine with me. Ultimately, I just take issue with reporting "Error occurred resolving path" for directories that are not required to exist. As an aside, I just noticed the "No files parsed from" message only appears when no quadlets are found in any search directories.

**Comment by rhatdan** [comment]
This use case is just for debugging the system setup not for use in normal use patterns.  It does not log any messages when systemctl daemon-reload is executed, which is the normal pattern.

**Comment by lovette** [comment]
As you said earlier, and I understand that. I opened this issue because the "error" reported while debugging Quadlets started me down the path of resolving a problem that, it turns out, isn't a problem 🙄. My ultimate suggestion is only that tweaking the message to be more of a "notice" than an "error" would be less confusing and hopefully benefit other developers debugging Quadlets. The mere existence of this thread may be solution enough, so I'll leave it at that and can consider the issue closed.
