### ISSUE TITLE
e2e: events network connection: off-by-one in "expect network connect string"

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#23634]
Seeing this one just often enough to annoy me. Almost definitely a bug in the test itself. Or maybe something weird in debian that we're not accounting for.
```
Podman events
           [It] podman events network connection
           # podman-remote [options] events --stream=false --since 30s
           2024-07-16 11:28:14.969562329 +0000 UTC system refresh
           2024-07-16 11:28:15.096974122 +0000 UTC container create c05b19f96654e621ce6977b6b5a51153b5d44bfe73e24a2af346b29e002c73ad (image=quay.io/libpod/alpine:latest, name=gracious_ganguly)
           2024-07-16 11:28:15.167205637 +0000 UTC network connect c05b19f96654e621ce6977b6b5a51153b5d44bfe73e24a2af346b29e002c73ad (container=c05b19f96654e621ce6977b6b5a51153b5d44bfe73e24a2af346b29e002c73ad, name=61da780ddfa3f307ea66dc59f1640d37c70efd83e90b6c38b0721ad2753bae0c)
           2024-07-16 11:28:15.075319494 +0000 UTC image pull 961769676411f082461f9ef46626dd7a2d1e2b2a38e6a44364bcbecf51e66dd4 quay.io/libpod/alpine:latest
           2024-07-16 11:28:15.203980038 +0000 UTC network disconnect c05b19f96654e621ce6977b6b5a51153b5d44bfe73e24a2af346b29e002c73ad (container=c05b19f96654e621ce6977b6b5a51153b5d44bfe73e24a2af346b29e002c73ad, name=61da780ddfa3f307ea66dc59f1640d37c70efd83e90b6c38b0721ad2753bae0c)

           [FAILED] Expected
               <string>: 2024-07-16 11:28:15.075319494 +0000 UTC image pull 961769676411f082461f9ef46626dd7a2d1e2b2a38e6a44364bcbecf51e66dd4 quay.io/libpod/alpine:latest
           to contain substring
               <string>: network connect
```

* debian-13 : int remote debian-13 root host sqlite [remote]
  * PR #23275
    * [07-23 20:34](https://api.cirrus-ci.com/v1/artifact/task/5222962364678144/html/int-remote-debian-13-root-host-sqlite.log.html#t--Podman-events-podman-events-network-connection--1) in Podman events podman events network connection
    * [08-15 10:22](https://api.cirrus-ci.com/v1/artifact/task/4811656197308416/html/int-remote-debian-13-root-host-sqlite.log.html#t--Podman-events-podman-events-network-connection--1) in Podman events podman events network connection
    * [07-17-2024 17:11](https://api.cirrus-ci.com/v1/artifact/task/6152137690841088/html/int-remote-debian-13-root-host-sqlite.log.html#t--Podman-events-podman-events-network-connection--1) in Podman events podman events network connection
    * [07-16-2024 07:29](https://api.cirrus-ci.com/v1/artifact/task/6457889936637952/html/int-remote-debian-13-root-host-sqlite.log.html#t--Podman-events-podman-events-network-connection--1) in Podman events podman events network connection

| x | x | x | x | x | x |
| ---: | ---: | ---: | ---: | ---: | ---: |
| int(4) | remote(4) | debian-13(4) | root(4) | host(4) | sqlite(4) |

**Comment by Luap99** [comment]
The reason this is happening because all image events are generated separately in c/common/libimage and than passed via channel to podman where it writes it to the log. Local podman commands before always make sure to drain all event and log them before they exit thus in local runs we have a sane order. AS the pull even event was generated by the podman create command.

If you use the remote server however the timings no longer match as it depends on the scheduling of the event reader routine.

I think long term we should likely fix this by moving the event code in c/common and directly write the events there. Which should make sure we have a sane order and much less overhead in general. However for now fixing the test is the easiest.

**Comment by Luap99** [comment]
@edsantiago This is assigned to you. Are you working on fixing the test or should I open a PR to make the test work?

**Comment by edsantiago** [comment]
Sorry... I focused on the "long term [...] c/common" part of your comment and didn't see the "for now" part. I will work on a fix.
