### ISSUE TITLE
Podman calls `newuidmap` when `--userns host`

### ISSUE THREAD

**Issue by gdonval** [containers/podman#23658]
### Issue Description

I wanted to use podman for its OCI capabilities only, using `podman run --userns host ...` to avoid calling `newuidmap`, specifically. 

I have setup an environment without a valid `newuidmap` and it turns out Podman still calls it in `host` mode, which I think is a bug.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Set up a system where `newuidmap` is not valid: either it does not have SUID, or it's not available, etc.
2. Run `podman run --rm --cgroups=split --sdnotify=conmon -d --userns host -v ... <image>`
3. Get errors related to `newuidmap` in log and crashed container.
   
   ```
   Aug 18 14:31:29: Error: cannot set up namespace using "/usr/bin/newuidmap": exit status 1
   ```

### Describe the results you received

Podman tried to use `newuidmap` when it should not be necessary.

### Describe the results you expected

When using `--userns host`, `podman` should run unimpeded without having called `newuidmap`. 

### podman info output

```yaml
podman version 5.2.1
Tried on flatcar (arm64), archlinux (x86-64) and fedora 40 (x86-64).
```

### Podman in a container

Yes

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

In my particular test system, I ran `podman` in a Systemd container with `NoNewPrivilege` active, which disables SUID, which shows the problem. The same happens in a VM where I replaced `/usr/bin/newuidap` with `/usr/bin/false`: the specific error was naturally different but it still proves that `newuidmap` was called.

**Comment by gdonval** [comment]
The same thing happens when I use `--uidmap` and `--gidmap` to map my user to `root` in the container.

**Comment by Luap99** [comment]
Do you have /etc/subuid setup with your user? Rootless podman always has to create a user namespace in order to function (i.e. without it we cannot mount configure networking,etc...). When creating the namespace we map the uid to root in the namespace and them map all extra uid ranges from /etc/subuid after that via newuidmap as it requires privileges to do so.

In theory it might be possible to run without newuidmap with only a single id mapped but this will break almost all images as they use more than one uid so we would not be able to store the images and your container would not be able to switch users.

**Comment by Luap99** [comment]
In any case this is not relevant to `--userns host` at all. This option basically means do not create a new userns for the container which is the default. However rootless podman always will have to create its own userns first

**Comment by gdonval** [comment]
Ah fair enough, but does it make sense then that it calls `newuidmap` when I specify `--uidmap`? What mapping is there to discover?

I think I see where you are coming from with all the complaints the "my container starts but does not actually work", but Podman would do wonder in single-UID mode, even gated behind a flag.

**Comment by Luap99** [comment]
I close this as this is the expected behavior
