### ISSUE TITLE
Add a `systemd-` prefix to the name of pod's infra container created by Quadlet as well

### ISSUE THREAD

**Issue by ruihe774** [containers/podman#23665]
### Feature request description

Containers and pods created by Quadlet have a `systemd-` prefix in their names to avoid conflicts with user-managed containers. However, the pod's infra container does not follow this naming convention. I propose that we can use a `systemd-` prefixed name by default for pod's infra container created by Quadlet.

### Suggest potential solution

For example, a pod `systemd-mypod` can set `systemd-mypod-infra` as the name of its infra container.

### Have you considered any alternatives?

No

### Additional context

None

**Comment by rhatdan** [comment]
Care to open a PR?

**Comment by ruihe774** [comment]
> Care to open a PR?

OK. I'm going to work on it.
