### ISSUE TITLE
Podman 5.2.x `podman cp` command failed

### ISSUE THREAD

**Issue by harbby** [containers/podman#23661]
### Issue Description

Podman 5.2.x does not support copying container files to the local file system via the `podman cp` command

### Steps to reproduce the issue

Steps to reproduce the issue
1.podman run -dit --name bug1 ubuntu:22.04
2.podman cp bug1:/etc/hosts .

### Describe the results you received

Error: 2 errors occurred:
	* copying to host: error in copier subprocess: SIGSEGV: segmentation violation
PC=0x750cce3adad5 m=0 sigcode=1 addr=0x20
signal arrived during cgo execution

goroutine 1 gp=0xc0000061c0 m=0 mp=0x2e65540 [syscall]:
runtime.cgocall(0x175e700, 0xc00063f528)
	/usr/lib/go-1.22/src/runtime/cgocall.go:157 +0x4b fp=0xc00063f500 sp=0xc00063f4c8 pc=0x40accb
os/user._Cfunc_mygetpwnam_r(0xc000314dd0, 0xc0000df400, 0x400, 0xc000314dd8, 0xc000314ddc)
	_cgo_gotypes.go:146 +0x65 fp=0xc00063f528 sp=0xc00063f500 pc=0x7e7b05
os/user._C_getpwnam_r(0xc000314dd0, 0xc0000df400, 0x400)
	/usr/lib/go-1.22/src/os/user/cgo_lookup_cgo.go:85 +0xaa fp=0xc00063f5d0 sp=0xc00063f528 pc=0x7e7e8a
os/user.lookupUser.func1({0xc0000df400?, 0x8?, 0x0?})
	/usr/lib/go-1.22/src/os/user/cgo_lookup_unix.go:30 +0x65 fp=0xc00063f678 sp=0xc00063f5d0 pc=0x7e6a45
os/user.retryWithBuffer(0x0?, 0xc00063f770)
	/usr/lib/go-1.22/src/os/user/cgo_lookup_unix.go:171 +0x68 fp=0xc00063f6d8 sp=0xc00063f678 pc=0x7e74c8
os/user.lookupUser({0x1d4e13a, 0x7})
	/usr/lib/go-1.22/src/os/user/cgo_lookup_unix.go:28 +0xd3 fp=0xc00063f7b0 sp=0xc00063f6d8 pc=0x7e68b3
os/user.Lookup({0x1d4e13a, 0x7})
	/usr/lib/go-1.22/src/os/user/lookup.go:43 +0x91 fp=0xc00063f7f0 sp=0xc00063f7b0 pc=0x7e76d1
github.com/containers/buildah/copier.copierMain()
	/tmp/build/podman-5.2.1/vendor/github.com/containers/buildah/copier/copier.go:722 +0xc7 fp=0xc00063fea8 sp=0xc00063f7f0 pc=0x11d4a67
github.com/containers/storage/pkg/reexec.Init(...)
	/tmp/build/podman-5.2.1/vendor/github.com/containers/storage/pkg/reexec/reexec.go:30
main.main()
	/tmp/build/podman-5.2.1/cmd/podman/main.go:37 +0x4c7 fp=0xc00063ff50 sp=0xc00063fea8 pc=0x1757c07
runtime.main()
	/usr/lib/go-1.22/src/runtime/proc.go:271 +0x29d fp=0xc00063ffe0 sp=0xc00063ff50 pc=0x4435fd
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00063ffe8 sp=0xc00063ffe0 pc=0x47c101

goroutine 2 gp=0xc000006c40 m=nil [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc00008efa8 sp=0xc00008ef88 pc=0x443a4e
runtime.goparkunlock(...)
	/usr/lib/go-1.22/src/runtime/proc.go:408
runtime.forcegchelper()
	/usr/lib/go-1.22/src/runtime/proc.go:326 +0xb3 fp=0xc00008efe0 sp=0xc00008efa8 pc=0x4438b3
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00008efe8 sp=0xc00008efe0 pc=0x47c101
created by runtime.init.6 in goroutine 1
	/usr/lib/go-1.22/src/runtime/proc.go:314 +0x1a

goroutine 3 gp=0xc000007180 m=nil [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc00008f780 sp=0xc00008f760 pc=0x443a4e
runtime.goparkunlock(...)
	/usr/lib/go-1.22/src/runtime/proc.go:408
runtime.bgsweep(0xc0000b8000)
	/usr/lib/go-1.22/src/runtime/mgcsweep.go:318 +0xdf fp=0xc00008f7c8 sp=0xc00008f780 pc=0x42d5df
runtime.gcenable.gowrap1()
	/usr/lib/go-1.22/src/runtime/mgc.go:203 +0x25 fp=0xc00008f7e0 sp=0xc00008f7c8 pc=0x421ee5
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00008f7e8 sp=0xc00008f7e0 pc=0x47c101
created by runtime.gcenable in goroutine 1
	/usr/lib/go-1.22/src/runtime/mgc.go:203 +0x66

goroutine 4 gp=0xc000007340 m=nil [GC scavenge wait]:
runtime.gopark(0x10000?, 0x2080800?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc00008ff78 sp=0xc00008ff58 pc=0x443a4e
runtime.goparkunlock(...)
	/usr/lib/go-1.22/src/runtime/proc.go:408
runtime.(*scavengerState).park(0x2e5fda0)
	/usr/lib/go-1.22/src/runtime/mgcscavenge.go:425 +0x49 fp=0xc00008ffa8 sp=0xc00008ff78 pc=0x42af89
runtime.bgscavenge(0xc0000b8000)
	/usr/lib/go-1.22/src/runtime/mgcscavenge.go:658 +0x59 fp=0xc00008ffc8 sp=0xc00008ffa8 pc=0x42b539
runtime.gcenable.gowrap2()
	/usr/lib/go-1.22/src/runtime/mgc.go:204 +0x25 fp=0xc00008ffe0 sp=0xc00008ffc8 pc=0x421e85
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00008ffe8 sp=0xc00008ffe0 pc=0x47c101
created by runtime.gcenable in goroutine 1
	/usr/lib/go-1.22/src/runtime/mgc.go:204 +0xa5

goroutine 5 gp=0xc000007c00 m=nil [finalizer wait]:
runtime.gopark(0xc00008e648?, 0x414ca5?, 0xa8?, 0x1?, 0xc0000061c0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc00008e620 sp=0xc00008e600 pc=0x443a4e
runtime.runfinq()
	/usr/lib/go-1.22/src/runtime/mfinal.go:194 +0x107 fp=0xc00008e7e0 sp=0xc00008e620 pc=0x420f27
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00008e7e8 sp=0xc00008e7e0 pc=0x47c101
created by runtime.createfing in goroutine 1
	/usr/lib/go-1.22/src/runtime/mfinal.go:164 +0x3d

goroutine 6 gp=0xc00038afc0 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc000090750 sp=0xc000090730 pc=0x443a4e
runtime.gcBgMarkWorker()
	/usr/lib/go-1.22/src/runtime/mgc.go:1310 +0xe5 fp=0xc0000907e0 sp=0xc000090750 pc=0x423fc5
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0000907e8 sp=0xc0000907e0 pc=0x47c101
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/go-1.22/src/runtime/mgc.go:1234 +0x1c

goroutine 7 gp=0xc00038b180 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc000090f50 sp=0xc000090f30 pc=0x443a4e
runtime.gcBgMarkWorker()
	/usr/lib/go-1.22/src/runtime/mgc.go:1310 +0xe5 fp=0xc000090fe0 sp=0xc000090f50 pc=0x423fc5
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000090fe8 sp=0xc000090fe0 pc=0x47c101
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/go-1.22/src/runtime/mgc.go:1234 +0x1c

goroutine 8 gp=0xc00038b340 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc000091750 sp=0xc000091730 pc=0x443a4e
runtime.gcBgMarkWorker()
	/usr/lib/go-1.22/src/runtime/mgc.go:1310 +0xe5 fp=0xc0000917e0 sp=0xc000091750 pc=0x423fc5
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0000917e8 sp=0xc0000917e0 pc=0x47c101
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/go-1.22/src/runtime/mgc.go:1234 +0x1c

goroutine 18 gp=0xc000102380 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc00008a750 sp=0xc00008a730 pc=0x443a4e
runtime.gcBgMarkWorker()
	/usr/lib/go-1.22/src/runtime/mgc.go:1310 +0xe5 fp=0xc00008a7e0 sp=0xc00008a750 pc=0x423fc5
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00008a7e8 sp=0xc00008a7e0 pc=0x47c101
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/go-1.22/src/runtime/mgc.go:1234 +0x1c

goroutine 9 gp=0xc00038b880 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc000091f50 sp=0xc000091f30 pc=0x443a4e
runtime.gcBgMarkWorker()
	/usr/lib/go-1.22/src/runtime/mgc.go:1310 +0xe5 fp=0xc000091fe0 sp=0xc000091f50 pc=0x423fc5
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000091fe8 sp=0xc000091fe0 pc=0x47c101
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/go-1.22/src/runtime/mgc.go:1234 +0x1c

goroutine 34 gp=0xc000500000 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc000506750 sp=0xc000506730 pc=0x443a4e
runtime.gcBgMarkWorker()
	/usr/lib/go-1.22/src/runtime/mgc.go:1310 +0xe5 fp=0xc0005067e0 sp=0xc000506750 pc=0x423fc5
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0005067e8 sp=0xc0005067e0 pc=0x47c101
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/go-1.22/src/runtime/mgc.go:1234 +0x1c

goroutine 10 gp=0xc00038ba40 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc000502750 sp=0xc000502730 pc=0x443a4e
runtime.gcBgMarkWorker()
	/usr/lib/go-1.22/src/runtime/mgc.go:1310 +0xe5 fp=0xc0005027e0 sp=0xc000502750 pc=0x423fc5
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0005027e8 sp=0xc0005027e0 pc=0x47c101
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/go-1.22/src/runtime/mgc.go:1234 +0x1c

goroutine 35 gp=0xc0005001c0 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc000506f50 sp=0xc000506f30 pc=0x443a4e
runtime.gcBgMarkWorker()
	/usr/lib/go-1.22/src/runtime/mgc.go:1310 +0xe5 fp=0xc000506fe0 sp=0xc000506f50 pc=0x423fc5
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000506fe8 sp=0xc000506fe0 pc=0x47c101
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/go-1.22/src/runtime/mgc.go:1234 +0x1c

goroutine 36 gp=0xc000500380 m=nil [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc000507750 sp=0xc000507730 pc=0x443a4e
runtime.gcBgMarkWorker()
	/usr/lib/go-1.22/src/runtime/mgc.go:1310 +0xe5 fp=0xc0005077e0 sp=0xc000507750 pc=0x423fc5
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0005077e8 sp=0xc0005077e0 pc=0x47c101
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/go-1.22/src/runtime/mgc.go:1234 +0x1c

goroutine 37 gp=0xc000500540 m=nil [GC worker (idle)]:
runtime.gopark(0x82aa49aacf?, 0x3?, 0xa2?, 0x7?, 0x0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc000507f50 sp=0xc000507f30 pc=0x443a4e
runtime.gcBgMarkWorker()
	/usr/lib/go-1.22/src/runtime/mgc.go:1310 +0xe5 fp=0xc000507fe0 sp=0xc000507f50 pc=0x423fc5
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000507fe8 sp=0xc000507fe0 pc=0x47c101
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/go-1.22/src/runtime/mgc.go:1234 +0x1c

goroutine 38 gp=0xc000500700 m=nil [GC worker (idle)]:
runtime.gopark(0x2ed3b60?, 0x3?, 0x5d?, 0x7?, 0x0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc000508750 sp=0xc000508730 pc=0x443a4e
runtime.gcBgMarkWorker()
	/usr/lib/go-1.22/src/runtime/mgc.go:1310 +0xe5 fp=0xc0005087e0 sp=0xc000508750 pc=0x423fc5
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0005087e8 sp=0xc0005087e0 pc=0x47c101
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/go-1.22/src/runtime/mgc.go:1234 +0x1c

goroutine 19 gp=0xc000102540 m=nil [GC worker (idle)]:
runtime.gopark(0x2ed3b60?, 0x1?, 0xd0?, 0x9c?, 0x0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc00008af50 sp=0xc00008af30 pc=0x443a4e
runtime.gcBgMarkWorker()
	/usr/lib/go-1.22/src/runtime/mgc.go:1310 +0xe5 fp=0xc00008afe0 sp=0xc00008af50 pc=0x423fc5
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00008afe8 sp=0xc00008afe0 pc=0x47c101
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/go-1.22/src/runtime/mgc.go:1234 +0x1c

goroutine 11 gp=0xc00038bc00 m=nil [GC worker (idle)]:
runtime.gopark(0x82aa4793bd?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc000502f50 sp=0xc000502f30 pc=0x443a4e
runtime.gcBgMarkWorker()
	/usr/lib/go-1.22/src/runtime/mgc.go:1310 +0xe5 fp=0xc000502fe0 sp=0xc000502f50 pc=0x423fc5
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000502fe8 sp=0xc000502fe0 pc=0x47c101
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/go-1.22/src/runtime/mgc.go:1234 +0x1c

goroutine 20 gp=0xc000102700 m=nil [GC worker (idle)]:
runtime.gopark(0x82aa49a372?, 0x1?, 0x74?, 0x80?, 0x0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc00008b750 sp=0xc00008b730 pc=0x443a4e
runtime.gcBgMarkWorker()
	/usr/lib/go-1.22/src/runtime/mgc.go:1310 +0xe5 fp=0xc00008b7e0 sp=0xc00008b750 pc=0x423fc5
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00008b7e8 sp=0xc00008b7e0 pc=0x47c101
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/go-1.22/src/runtime/mgc.go:1234 +0x1c

goroutine 39 gp=0xc0005008c0 m=nil [GC worker (idle)]:
runtime.gopark(0x82aa49b043?, 0x1?, 0xb8?, 0xfe?, 0x0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc000508f50 sp=0xc000508f30 pc=0x443a4e
runtime.gcBgMarkWorker()
	/usr/lib/go-1.22/src/runtime/mgc.go:1310 +0xe5 fp=0xc000508fe0 sp=0xc000508f50 pc=0x423fc5
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc000508fe8 sp=0xc000508fe0 pc=0x47c101
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/go-1.22/src/runtime/mgc.go:1234 +0x1c

goroutine 12 gp=0xc00038bdc0 m=nil [GC worker (idle)]:
runtime.gopark(0x82aa49b7a0?, 0x3?, 0x29?, 0x6f?, 0x0?)
	/usr/lib/go-1.22/src/runtime/proc.go:402 +0xce fp=0xc000503750 sp=0xc000503730 pc=0x443a4e
runtime.gcBgMarkWorker()
	/usr/lib/go-1.22/src/runtime/mgc.go:1310 +0xe5 fp=0xc0005037e0 sp=0xc000503750 pc=0x423fc5
runtime.goexit({})
	/usr/lib/go-1.22/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0005037e8 sp=0xc0005037e0 pc=0x47c101
created by runtime.gcBgMarkStartWorkers in goroutine 1
	/usr/lib/go-1.22/src/runtime/mgc.go:1234 +0x1c

rax    0x0
rbx    0xc000314dd0
rcx    0x6e
rdx    0x2ecabf0
rdi    0x750cce3fef98
rsi    0x750cce3ef27d
rbp    0x7ffd7970e310
rsp    0x7ffd7970e1e8
r8     0xffffffff
r9     0x0
r10    0x750ccc3b1fc0
r11    0x750ccc3b28c0
r12    0x7ffd7970e250
r13    0x47932d0
r14    0x0
r15    0x0
rip    0x750cce3adad5
rflags 0x10246
cs     0x33
fs     0x0
gs     0x0

	* copying from container: copier: get: "/root/1.txt": writing header for /root/1.txt (1.txt): io: read/write on closed pipe

### Describe the results you expected

podman cp container file to local filesystem succeed

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.37.1
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /data/lib/podman/lib/podman/conmon
    version: 'conmon version 2.1.12, commit: e8896631295ccb0bfdda4284f1751be19b483264'
  cpuUtilization:
    idlePercent: 99.03
    systemPercent: 0.44
    userPercent: 0.53
  cpus: 16
  databaseBackend: sqlite
  distribution:
    codename: noble
    distribution: ubuntu
    version: "24.04"
  eventLogger: file
  freeLocks: 2045
  hostname: ideal-pc
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.8.0-40-generic
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 25390231552
  memTotal: 29269254144
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: Unknown
      path: /data/lib/podman/lib/podman/aardvark-dns
      version: aardvark-dns 1.12.1
    package: Unknown
    path: /data/lib/podman/lib/podman/netavark
    version: netavark 1.12.1
  ociRuntime:
    name: crun
    package: Unknown
    path: /data/lib/podman/sbin/crun
    version: |-
      crun version 1.15
      commit: e6eacaf4034e84185fd8780ac9262bbf57082278
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: /data/lib/podman/lib/passt-bin/bin/pasta
    package: Unknown
    version: |
      pasta unknown version
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: false
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: slirp4netns
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: ""
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /data/lib/podman/lib/slirp4netns/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.3.1
      commit: e5e368c4f5db6ae75c2fce786e31eef9da6bf236
      libslirp: 4.8.0
      SLIRP_CONFIG_VERSION_MAX: 5
      libseccomp: 2.5.3
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 0h 17m 4.00s
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/$USER/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 1
    stopped: 2
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /data/cached/podman
  graphRootAllocated: 195722883072
  graphRootUsed: 87883489280
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 4
  runRoot: /data/cached/podman/storage
  transientStore: false
  volumePath: /data/cached/podman/volumes
version:
  APIVersion: 5.2.1
  Built: 0
  BuiltTime: Thu Jan  1 08:00:00 1970
  GitCommit: ""
  GoVersion: go1.22.2
  Os: linux
  OsArch: linux/amd64
  Version: 5.2.1
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

OS: Ubuntu 24.04
Linux {hostname} 6.8.0-40-generic #40-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 10:34:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Additional information

In podman 5.1.2, copying files from the container to the local machine using the cp command is completely correct, but it is incorrect in podman 5.2.0 and 5.2.1

**Comment by Luap99** [comment]
Does it happen every time?

> signal arrived during cgo execution

This sounds like a go bug and not something podman did change.

**Comment by baude** [comment]
go-1.22 ?

**Comment by Luap99** [comment]
As we haven't seen this elsewhere I suggest you report this to your distro maintainers as the failure seems to be in mygetpwnam_r C function called by the golang stdlib and not anywahere in the podman code I would say
