### ISSUE TITLE
CI: podman stop: timeout

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#23685]
One-off. I think I've seen this one before, but have no way to find it because I didn't file it.
```
[+0242s] • [FAILED] [92.098 seconds]
         TOP-LEVEL [AfterEach]
           Podman UserNS support
             podman --userns=container:CTR
         
....
           $ podman [options] run --rm --userns=container:userns-ctr --net=container:userns-ctr alpine cat /proc/self/uid_map
                    0          0          1
                    1          2       4998
           ← Exit  [It] podman --userns=container:CTR - /var/tmp/go/src/github.com[/containers/podman/test/e2e/run_userns_test.go:324](https://github.com/containers/podman/blob/fc30620cdb11b011ee396222795af415feda8b03/test/e2e/run_userns_test.go#L324) @ 08/19/24 15:33:35.557 (1.09s)
           → Enter [AfterEach] TOP-LEVEL - /var/tmp/go/src/github.com[/containers/podman/test/e2e/common_test.go:122](https://github.com/containers/podman/blob/fc30620cdb11b011ee396222795af415feda8b03/test/e2e/common_test.go#L122) @ 08/19/24 15:33:35.558
           $ podman [options] stop --all -t 0
           SIGABRT: abort
           PC=0x4820e1 m=0 sigcode=0
         
           goroutine 0 gp=0x2d7c440 m=0 mp=0x2d7f5e0 [idle]:
           runtime.futex(0x2d7f720, 0x80, 0x0, 0x0, 0x0, 0x0)
           	/usr/lib/go-1.22/src/runtime/sys_linux_amd64.s:557 +0x21 fp=0x7ffd4f5dc8a0 sp=0x7ffd4f5dc898 pc=0x4820e1
           runtime.futexsleep(0x7ffd4f5dc918?, 0x417030?, 0x455607?)
           	/usr/lib/go-1.22/src/runtime/os_linux.go:69 +0x30 fp=0x7ffd4f5dc8f0 sp=0x7ffd4f5dc8a0 pc=0x441610
           runtime.notesleep(0x2d7f720)
           	/usr/lib/go-1.22/src/runtime/lock_futex.go:170 +0x87 fp=0x7ffd4f5dc928 sp=0x7ffd4f5dc8f0 pc=0x4171c7
           runtime.mPark(...)
           	/usr/lib/go-1.22/src/runtime/proc.go:1761
           runtime.stopm()
```
In [debian rootless](https://api.cirrus-ci.com/v1/artifact/task/6333888472023040/html/int-podman-debian-13-rootless-host-sqlite.log.html#t--Podman-UserNS-support-podman-userns-container-CTR--1), and not in any of my test PRs

**Comment by Luap99** [comment]
[seen again](https://api.cirrus-ci.com/v1/artifact/task/5106343298727936/html/int-podman-fedora-40-rootless-host-sqlite.log.html#t--Podman-UserNS-support-podman-userns-container-CTR--1)

There is no panic, see https://github.com/containers/podman/pull/23551

This is an intentionally send SIGABRT on timeout, see the red error message. If it doesn't say panic or SIGSEGV it is not a panic but rather us sending the signal (see `SIGABRT: abort` as first line)

**Comment by edsantiago** [comment]
Fine with me. I opened the issue because some flakes are easy to keep track of (when they all fail in the same test) and some are not (non-unique failure message across multiple tests).

**Comment by liangdy678** [comment]
Hi sir,

I have also encountered a similar situation. 

**When the tasks in the container are completed, the container cannot exit.**

![image](https://github.com/user-attachments/assets/c7c5f7ba-2684-4d05-85df-be0da0989d87)

**If no parameters (--rm) are used, it can exit normally.**

![image](https://github.com/user-attachments/assets/b606e1a1-563e-4004-9c7e-dc8d161564c1)

thanks

**Comment by Luap99** [comment]
@edsantiago Another case in https://api.cirrus-ci.com/v1/artifact/task/6443976285224960/html/int-podman-rawhide-rootless-host-sqlite.log.html but more importantly as the process was killed the netns file was leaked so the new netns leak seems to work as expected I would say.

**Comment by Luap99** [comment]
Ok maybe we are getting somewhere here, QE hit this in RHEL 9.5 testing and I have access to that VM.

```
[test@kvm-08-guest26 ~]$ podman unshare cat /proc/self/mountinfo | grep netns
490 707 0:4 net:[4026532338] /run/user/1000/netns/netns-7eb79636-16b9-8180-5836-e672a21ebc1e rw - nsfs nsfs rw
487 707 0:45 /netns /run/user/1000/netns rw,nosuid,nodev,relatime shared:252 master:240 - tmpfs tmpfs rw,seclabel,size=374644k,nr_inodes=93661,mode=700,uid=1000,gid=1000,inode64
[test@kvm-08-guest26 ~]$ podman unshare umount /run/user/1000/netns/netns-7eb79636-16b9-8180-5836-e672a21ebc1e
umount: /run/user/1000/netns/netns-7eb79636-16b9-8180-5836-e672a21ebc1e: not mounted.
[test@kvm-08-guest26 ~]$ podman unshare rm /run/user/1000/netns/netns-7eb79636-16b9-8180-5836-e672a21ebc1e
rm: cannot remove '/run/user/1000/netns/netns-7eb79636-16b9-8180-5836-e672a21ebc1e': Device or resource busy
```

This doesn't make any sense to me, mount says it is mounted, umount says it is not mounted and rm is failing with EBUSY (which is why podman keeps looping until we remove successfully or a different error is hit, I am starting to regret that I didn't add a max timeout before we give up trying to remove the file)

**Comment by edsantiago** [comment]
Weird. In case it helps, here's the list so far. All rootless, and all in the same test:

* debian-13 : int podman debian-13 rootless host sqlite
  * PR #23857
    * [09-06 08:13](https://api.cirrus-ci.com/v1/artifact/task/5772116363051008/html/int-podman-debian-13-rootless-host-sqlite.log.html#t--Podman-UserNS-support-podman-userns-container-CTR--1) in TOP-LEVEL [AfterEach] Podman UserNS support podman --userns=container:CTR
  * PR #23666
    * [08-19-2024 11:44](https://api.cirrus-ci.com/v1/artifact/task/6333888472023040/html/int-podman-debian-13-rootless-host-sqlite.log.html#t--Podman-UserNS-support-podman-userns-container-CTR--1) in TOP-LEVEL [AfterEach] Podman UserNS support podman --userns=container:CTR
* fedora-40 : int podman fedora-40 rootless host sqlite
  * PR #23948
    * [09-13 12:12](https://api.cirrus-ci.com/v1/artifact/task/5842428735782912/html/int-podman-fedora-40-rootless-host-sqlite.log.html#t--Podman-UserNS-support-podman-userns-container-CTR--1) in TOP-LEVEL [AfterEach] Podman UserNS support podman --userns=container:CTR
* rawhide : int podman rawhide rootless host sqlite
  * PR #24006
    * [09-18 13:57](https://api.cirrus-ci.com/v1/artifact/task/6443976285224960/html/int-podman-rawhide-rootless-host-sqlite.log.html#t--Podman-UserNS-support-podman-userns-container-CTR--1) in TOP-LEVEL [AfterEach] Podman UserNS support podman --userns=container:CTR

| x | x | x | x | x | x |
| ---: | ---: | ---: | ---: | ---: | ---: |
| int(4) | podman(4) | debian-13(2) | rootless(4) | host(4) | sqlite(4) |
|  |  | rawhide(1) |  |  |  |
|  |  | fedora-40(1) |  |  |  |

**Comment by Luap99** [comment]
strace umount says EINVAL
```
umount2("/run/user/1000/netns/netns-7eb79636-16b9-8180-5836-e672a21ebc1e", MNT_DETACH) = -1 EINVAL (Invalid argument)
```

**Comment by Luap99** [comment]
No that is most likely something else. It is the remote hang so we do not see the server stack trace which would be the interesting thing here. I really should get https://github.com/containers/podman/pull/23631 in a good state so we can capture this info on all tests as this has been needed several times by now.
