### ISSUE TITLE
Quadlet add support for --add-host

### ISSUE THREAD

**Issue by jerome59** [containers/podman#23692]
### Feature request description

In a quadlet file, I don't see any options equivalent to the --add-host of the podman run command. 
Today if we want to add some hosts, we need to do : 
`PodmanArgs=--add-host my-host-name:192.168.10.10 --add-host my-second-host-name:192.168.10.10 --add-host my-third-host-name:192.168.10.11`

### Suggest potential solution

For Pod and Container units, I'd like to have a key AddHost which allows me to define the same behavior as the  --add-host argument. 

Example : 

```
AddHost=my-host-name:192.168.10.10
AddHost=my-second-host-name:192.168.10.10
AddHost=my-third-host-name:192.168.10.11
```

If possible, it would even be better if we can define multiple hostnames for a single IP at once. The previous example would look like : 

```
AddHost=my-host-name;my-second-host-name:192.168.10.10
AddHost=my-third-host-name:192.168.10.11
```

**Comment by rhatdan** [comment]
Please open a PR to add it.
