### ISSUE TITLE
CI: tests should perform netns leak check

### ISSUE THREAD

**Issue by Luap99** [containers/podman#23715]
Podman will create a bind mounted netns file under /run/netns ($XDG_RUNTIME_DIR/netns) in the following format `netns-839e5791-ef98-7fe1-ff60-d9e9a39fc06d`

System tests (potentially e2e tests as well) should make sure that we do no leak any of these files are running the tests. This will ensure our cleanup is working properly.
We already have a leak check in on single test but we need to make sure we do not leak anywhere, https://github.com/containers/podman/blob/ae4eaaf1ae6921eab9d5ba5f3c9252cb267e77b1/test/system/500-networking.bats#L1002-L1004

It is possible that there are outstanding bugs where we currently leak so if we find them these need to be fixed first.

cc @edsantiago

**Comment by rhatdan** [comment]
We should also look for leaked builds in /var/tmp

**Comment by edsantiago** [comment]
Here is my `/run/netns`:
```
-r--r--r--. 1 root root 0 Aug 20 11:34 netns5KQttnHVx0
-r--r--r--. 1 root root 0 Aug 20 11:35 netnsCjgJDYip24
-r--r--r--. 1 root root 0 Aug 21 05:07 netnst21-fje7qm7v
-r--r--r--. 1 root root 0 Aug 21 05:15 netnst21-nlfgmr11
-r--r--r--. 1 root root 0 Aug 20 11:35 netnszH9JpPAdM2
```
The `t21` ones are probably leftovers from me ^Cing a test or maybe a test failing. The others, I don't know. I do not see any `netns-UUID` files.

> We should also look for leaked builds in /var/tmp

#22642

**Comment by Luap99** [comment]
> The t21 ones are probably leftovers from me ^Cing a test or maybe a test failing. The others, I don't know. I do not see any netns-UUID files.

Ack then this is a test issue not podman itself. Either way we like to catch both of course. I think for the ones created by tests we should name them more specific so that we know that they are safe to nuke
