### ISSUE TITLE
'podman info' cannot be filter like 'podman inspect'

### ISSUE THREAD

**Issue by mahmut-Abi** [containers/podman#23746]
### Issue Description

![image](https://github.com/user-attachments/assets/d244e75f-24f0-4524-886f-73d62033eb0c)

podman info cannot filter correctly. but podman inspect can.

### Steps to reproduce the issue

podman info -f '{{ .Host }}'

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
It is not clear what you are asking, `podman info -f '{{ .Host }}'` seems to work fine based on your output.

Please provide the information reuested in the template. podman info, what did you expect to happen, etc...
And please do not use screen shots for terminal text, copy and paste the text please in formatted code blocks.

**Comment by mahmut-Abi** [comment]
`podman info` print lowercase `host`,  but i need to use uppercase `Host` to filer the output.

**Comment by mahmut-Abi** [comment]
`podman inspect` output can be filter with it's `key`, but `podman info` cannot.
