### ISSUE TITLE
podman-docker compose fails to read that port 53 is free

### ISSUE THREAD

**Issue by jbwyatt4** [containers/podman#23740]
### Issue Description

Describe your issue

With the docker compose file here: https://github.com/pi-hole/docker-pi-hole/?tab=readme-ov-file#quick-start

I run into an issue where the system claims that port 53 is being used.

Following the instructions here

https://unix.stackexchange.com/a/637521

I am run docker compose up -d (proper from the docker repo). I am able to get to the main page at an amended port (changed port 80 to 8300)

On podman-docker it keeps complaining that port 53 is still being used despite `sudo lsof -i :53` not showing it being used

This is behavior breaking with docker cli.

### Steps to reproduce the issue

Steps to reproduce the issue (make sure podman-docker is installed)
1. sudo mkdir -p /etc/systemd/resolved.conf.d && touch /etc/systemd/resolved.conf.d/10-make-dns-work.conf
2. Copy and paste the text from 10-make-dns-work.conf into a docker-compose.yml
[Resolve]
DNSStubListener=no
3. Restart the system
4. sudo docker compose up -d

You can test this in a virtual machine running on virt-manager.

### Describe the results you received

Describe the results you received

pihole complains about port 53.

### Describe the results you expected

Describe the results you expected

For the container to start. Works with actual docker.

### podman info output

```yaml
Starting pihole ... error

ERROR: for pihole  Cannot start service pihole: netavark (exit code 1): IO error: Error while applying dns entries: IO error: aardvark-dns failed to start: Error from child process
Error starting server failed to bind udp listener on 10.89.1.1:53: IO error: Address already in use (os error 98)

ERROR: for pihole  Cannot start service pihole: netavark (exit code 1): IO error: Error while applying dns entries: IO error: aardvark-dns failed to start: Error from child process
Error starting server failed to bind udp listener on 10.89.1.1:53: IO error: Address already in use (os error 98)
ERROR: Encountered errors while bringing up the project.
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

Additional environment details:
Fedora 40 Gnome running in a virt-manager vm. Docker is able to bring up the main screen
podman-5.2.1-1.fc40

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
see https://github.com/containers/podman/issues/23226 and https://github.com/containers/podman/issues/23128

You cannot bind to 0.0.0.0 because aardvark-dns has to bind to the bridge ip there. So you either change the dns_bind_port in containers.conf or you make sure to only bind your external host ip `-p <hostip>:53:53/udp ...` to not cause bind conflicts.

**Comment by jbwyatt4** [comment]
Thank you for your information @Luap99.

I am still getting a conflict with port 67. I had to bind my local ip to the 53/tcp port as well, which worked, and 67, which did not.

`
ERROR: for pihole  preparing container 0bc32662c4d6ac161552e56e9b4752e44264bbbb9e5b81b7db7ff99398bfeeec for attach: cannot listen on the UDP port: listen udp4 10.0.0.10:67`

**Comment by Luap99** [comment]
Port 67 is not something podman uses itself, only 53 is used by our dns server. So if 67 fails to bind then something else is listening there on the host already.
