### ISSUE TITLE
rootFsSize changing on a created (not running) container?

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#23756]
```
not ok 162 |090| events - container inspect data - journald in 6871ms
....
   SizeRootFs: 11762614    ->   11761590
```
In parallel tests. Only one instance, [f39 root](https://api.cirrus-ci.com/v1/artifact/task/5793292044992512/html/sys-podman-fedora-39-root-host-boltdb.log.html#t--00162p). Feel free to verify for yourself that `SizeRootFs` is the only diff.

I'm having trouble understanding how this can happen. `rootFsSize()`[1] is image size + container size. A created container should not change size. Can the image? `podman tag existingimage newname` does not change the size of `existingimage`. Is there some other action that could? Note that load/save tests are not parallelizable.

 [1] https://github.com/containers/podman/blob/d04f0d2802832dfbe47a29f592fc023e7df70607/libpod/container_internal.go#L70

Almost certainly this needs to be addressed in the test, not in podman, but I'd like to understand it first.

**Comment by Luap99** [comment]
```
// ImageSize computes the size of the image's layers and ancillary data.
ImageSize(id string) (int64, error)

...and the in ImageSize()
	// Count big data items.
	names, err := imageStore.BigDataNames(id)
	if err != nil {
		return -1, fmt.Errorf("reading list of big data items for image %q: %w", id, err)
	}
	for _, name := range names {
		n, err := imageStore.BigDataSize(id, name)
		if err != nil {
			return -1, fmt.Errorf("reading size of big data item %q for image %q: %w", name, id, err)
		}
		size += n
	}

```

The word ancillary seems to suggest it counts more than just the layers, at least "BigData" is counted as well but I am not sure what exactly it stores and if other processes modify it after the image/container is created.

**Comment by edsantiago** [comment]
Still [flaking](https://api.cirrus-ci.com/v1/artifact/task/4617516838813696/html/sys-podman-rawhide-rootless-host-sqlite.log.html#t--00150p)
