### ISSUE TITLE
More accurate documentation around podman machine volume mounts in WSL 2

### ISSUE THREAD

**Issue by wbrefvem** [containers/podman#23763]
### Feature request description

The documented behavior of `podman machine init` is misleading when it comes to volumes and Windows users using WSL 2.  The CLI's help text says you get a simple `C:\Users\<my username>:/Users/<my username>` mount for free (the full docs say something equivalent but more generic), which is not strictly true: it's more like `C:\Users\<my username>:/mnt/c/Users/<my username>`. That's what you get in every WSL 2 container, including the default podman machine.

Additionally, if you, say, try to mount your Windows `$HOME` at something Linux-y like `/home/<my username`, podman just ignores it and proceeds as if all is well.

### Suggest potential solution

The behavior of podman makes sense here: you get your entire Windows tree in every WSL instance under `/mnt/c`, so no need to mount stuff. But the docs and CLI help text should reflect that so users aren't banging their heads against the wall like I was the past half hour.

**Comment by rhatdan** [comment]
Interested in opening a PR?

**Comment by wbrefvem** [comment]
Sure!
