### ISSUE TITLE
Podman CLI --add-host with multiple host for a single IP

### ISSUE THREAD

**Issue by jerome59** [containers/podman#23770]
### Feature request description

Hello, 

podman CLI has a parameter --add-host which allows us to add a mapping between a hostname and an IP  (add line in the /etc/hosts file).  This parameter can be set multiple times to add multiple mappings. 
In case we have to set a lot of hostname which are mapped to the same IP, we could improve clarity by allowing to specify multiple hostname without duplicating the parameter --add-host. 

 This behavior is actually supported by default in the host files where we can map multiple hostnames to a single IP on a single line :
 `192.168.10.10 hostname1 hostname2`

It is also supported by kube play (and kubernetes) : 
```
  hostAliases:
  - hostnames:
    - hostname1
    - hostname2
    ip: 192.168.10.10
  
```

### Suggest potential solution

From a user point of view, instead of writing the following when running a container or creating a pod : 

`--add-host=hostname1:192.168.10.10 --add-host=hostname2:192.168.10.10 --add-host=hostname3:192.168.10.10 --add-host=hostname4:192.168.10.11`

I'd like to write : 
`--add-host=hostname1;hostname2;hostname3:192.168.10.10 --add-host=hostname4:192.168.10.11`

### Additional context

This issue is opened following the comments on the following PR https://github.com/containers/podman/pull/23713#pullrequestreview-2257816012

**Comment by Luap99** [comment]
Using a semicolon sounds fine with me, if this is implemented the new syntax would need to be add to ValidateExtraHost() in cmd/podman/parse/net.go and then in c/common/libnetwork where we generate the hosts file:
https://github.com/containers/common/blob/b001f1ae2b4ebd52b9bbd55ba6cb01d4422b62ef/libnetwork/etchosts/hosts.go#L235
