### ISSUE TITLE
race? Failed to retrieve cgroup stats: open .../user.slice/sha.scope/memory.stats and pids.current: ENOENT

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#23789]
New one-off (so far) in [rawhide rootless parallel](https://api.cirrus-ci.com/v1/artifact/task/5252627401801728/html/sys-podman-rawhide-rootless-host-sqlite.log.html#t--00371p):
```
<+026ms> # $ podman container stats --no-stream --format {{"\n"}}
<+163ms> # time="2024-08-27T22:13:08-05:00" level=warning msg="Failed to retrieve cgroup stats: open /sys/fs/cgroup/user.slice/user-4839.slice/user@4839.service/user.slice/libpod-7328f381a1cde439c6e20df0aa54dfe87e731daf1716f97279072fe7786b7480.scope/memory.stat: no such file or directory"
         # time="2024-08-27T22:13:08-05:00" level=warning msg="Failed to retrieve cgroup stats: open /sys/fs/cgroup/user.slice/user-4839.slice/user@4839.service/user.slice/libpod-7328f381a1cde439c6e20df0aa54dfe87e731daf1716f97279072fe7786b7480.scope/pids.current: no such file or directory"
         # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
         # #| FAIL: Command succeeded, but issued unexpected warnings
         # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by Luap99** [comment]
On quick look, we are locked during the stats call so this should prevent another podman process from stopping/removing the container in parallel. We also only query the cgroup of the ctr state is running or paused. I am not to familiar with how the cgroups setup works, but the container process itself can exit at any time during or calls but AFAIK the cgroup isn't deleted when the process exits but rather needs an explicit removal via podman/oci runtime which also needs to hold a lock so it is not clear to me where the race would be.

**Comment by edsantiago** [comment]
Seen last week in [rawhide rootless](https://api.cirrus-ci.com/v1/artifact/task/4676745176023040/html/sys-podman-rawhide-rootless-host-sqlite.log.html#t--00390p), slightly different symptom:
```
<+026ms> # $ podman stats --no-stream --format {{"\n"}}
<+219ms> # Error: unable to obtain cgroup stats: read /sys/fs/cgroup/user.slice/user-3860.slice/user@3860.service/user.slice/libpod-c472c9ad2475d01451cced72412f6221b819b050026324f5c7768c7ed66f6840.scope/memory.max: no such device
```
(`read` instead of `open`, and `memory.max`)

**Comment by Luap99** [comment]
@giuseppe PTAL
Is it expected that reading the cgroup files is racy? We do seem to hold the container locks correctly so there should be not removal happening at the same time I think, https://github.com/containers/podman/issues/23789#issuecomment-2315320296

**Comment by giuseppe** [comment]
one reason for seeing `ENODEV` is that the cgroup is deleted after the open, but before the read syscall: https://github.com/containers/crun/issues/537

Trying to reproduce locally

**Comment by giuseppe** [comment]
I was able to reproduce quite easily with:

```diff
diff --git a/vendor/github.com/containers/common/pkg/cgroups/cgroups_linux.go b/vendor/github.com/containers/common/pkg/cgroups/cgroups_linux.go
index d2c610fb1..7e49c7ed3 100644
--- a/vendor/github.com/containers/common/pkg/cgroups/cgroups_linux.go
+++ b/vendor/github.com/containers/common/pkg/cgroups/cgroups_linux.go
@@ -8,6 +8,7 @@ import (
        "context"
        "errors"
        "fmt"
+       "io"
        "math"
        "os"
        "path/filepath"
@@ -258,10 +259,19 @@ func (c *CgroupControl) initialize() (err error) {
 }

 func readFileAsUint64(path string) (uint64, error) {
-       data, err := os.ReadFile(path)
+       file, err := os.Open(path)
        if err != nil {
                return 0, err
        }
+       defer file.Close()
+
+       time.Sleep(time.Second / 5)
+
+       data, err := io.ReadAll(file)
+       if err != nil {
+               return 0, err
+       }
+
```

running `while true; do podman stats --no-trunc --no-stream --no-reset --format '\n'; done` in a loop while in another terminal I create containers with `podman run -d ...`.

Not sure about the fix here, should we ignore any kind of error if the cgroup is gone?

Or should the test just stat a known container that it has control over instead of being affected by other runs?

**Comment by Luap99** [comment]
> Or should the test just stat a known container that it has control over instead of being affected by other runs?

That is not really possible and the point of these tests is to catch bugs like this.


> Not sure about the fix here, should we ignore any kind of error if the cgroup is gone?

But what deletes the cgroup? AFAIK we hold the container lock so we should not call crun kill/delete or any other runtime command at the same time.
I mean making the listing robust against such races make sense to me but only if that race is to be expected.

**Comment by giuseppe** [comment]
> But what deletes the cgroup? AFAIK we hold the container lock so we should not call crun kill/delete or any other runtime command at the same time.

systemd deletes the cgroup when it detects there are no more processes running there

**Comment by giuseppe** [comment]
> > Or should the test just stat a known container that it has control over instead of being affected by other runs?
> 
> That is not really possible and the point of these tests is to catch bugs like this.

if we want to support this case, we need to define when these errors can be ignored.  One way could be for `podman stats -a` to validate if the container/cgroup is still running/existing on each error.  If the container exited, then it should be ignored

**Comment by Luap99** [comment]
yes I think we should catch ENOENT and ENODEV then we could simply check if the container pid is still alive with kill(pid,0) and if not we ignore this error and continue with the next container.

**Comment by giuseppe** [comment]
opened a PR: https://github.com/containers/podman/pull/24400
