### ISSUE TITLE
pull EXTEND_TIMEOUT_USEC: dial unixgram $NOTIFY_SOCKET: connect: ENOENT

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#23798]
Failure in the USEC test:
```
[+0401s] not ok 200 [260] podman pull - EXTEND_TIMEOUT_USEC in 1058ms
         ...
         #
<+     > # # podman --storage-driver vfs --root /tmp/CI_Wbi1/bats-run-9BZCtY/suite/podman-bats-registry/root --runroot /tmp/CI_Wbi1/bats-run-9BZCtY/suite/podman-bats-registry/runroot --tmpdir /tmp/CI_Wbi1/bats-run-9BZCtY/suite/podman-bats-registry/tmpdir network reload --all
<+213ms> # 326a26406461fb291f701bac8691416115b1c2983cfc4c056ef06d7697a914f3
         #
<+019ms> # # podman push --tls-verify=false --creds userqhud:pw3uManIPnWDSnDBy quay.io/libpod/testimage:20240123 localhost:42915/name:tag
<+122ms> # Getting image source signatures
         # Copying blob sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef
         # Copying blob sha256:25a964f60e84b2d24f8098376c985a5c057bea74d699ee50c93e417c26516cc3
         # Copying config sha256:1f6acd4c4a1d4d39395870e1c12dbb68da27dd432afecf86e7cb6e23cf4b75d0
         # Writing manifest to image destination
         #
<+011ms> # # podman pull --tls-verify=false --creds userqhud:pw3uManIPnWDSnDBy localhost:42915/name:tag
<+050ms> # Trying to pull localhost:42915/name:tag...
         # Error: dial unixgram /tmp/CI_Wbi1/podman_bats.dM0zjZ/notify.sock: connect: no such file or directory
<+005ms> # [ rc=125 (** EXPECTED 0 **) ]
```
Happening only in #23275, but this is NOT A PARALLEL TEST. The failure is happening in pass 1, the serial tests, which run before parallel tests.

This is almost certainly my problem to deal with. I'm just filing because all these flakes are getting hard to track.

* debian-13 : sys podman debian-13 root host sqlite
  * PR #23275
    * [08-28 09:23](https://api.cirrus-ci.com/v1/artifact/task/6013042503188480/html/sys-podman-debian-13-root-host-sqlite.log.html#t--00200) in [sys] [260] podman pull - EXTEND_TIMEOUT_USEC
    * [08-26 09:26](https://api.cirrus-ci.com/v1/artifact/task/6181125477892096/html/sys-podman-debian-13-root-host-sqlite.log.html#t--00200) in [sys] [260] podman pull - EXTEND_TIMEOUT_USEC
    * [08-22 08:08](https://api.cirrus-ci.com/v1/artifact/task/5271340641419264/html/sys-podman-debian-13-root-host-sqlite.log.html#t--00240) in [sys] [260] podman pull - EXTEND_TIMEOUT_USEC
    * [08-20 21:58](https://api.cirrus-ci.com/v1/artifact/task/5509423630647296/html/sys-podman-debian-13-root-host-sqlite.log.html#t--00240) in [sys] [260] podman pull - EXTEND_TIMEOUT_USEC
    * [08-14 15:45](https://api.cirrus-ci.com/v1/artifact/task/4678865774182400/html/sys-podman-debian-13-root-host-sqlite.log.html#t--00281) in [sys] [260] podman pull - EXTEND_TIMEOUT_USEC
* fedora-39 : sys podman fedora-39 root host boltdb
  * PR #23275
    * [08-27 10:10](https://api.cirrus-ci.com/v1/artifact/task/4990078399807488/html/sys-podman-fedora-39-root-host-boltdb.log.html#t--00200) in [sys] [260] podman pull - EXTEND_TIMEOUT_USEC

| x | x | x | x | x | x |
| ---: | ---: | ---: | ---: | ---: | ---: |
| sys(6) | podman(6) | debian-13(5) | root(6) | host(6) | sqlite(5) |
|  |  | fedora-39(1) |  |  | boltdb(1) |

**Comment by Luap99** [comment]
ENOENT possibly means the socat process was never started, exited before we tried to connect (also exits and deletes the socket on something like SIGTERM but if it got SIGKILL we should get ECONNREFUSED instead). We do have no error checking on the socat process so this is a possibility but if I read the setup correctly we should still see stderr from it!?    And lastly something might be deleting the socket file but if there are no parallel things going on it seems really strange.

I would recommend to add a simple file check before the pull command to see if the socket is there
