### ISSUE TITLE
overlayfs: fs does not support file handles, falling back to xino=off on ubuntu22

### ISSUE THREAD

**Issue by kalyanbhonagiri16** [containers/podman#23808]
### Issue Description

After installing podman 3.4.4 on ubuntu22 we continuously see these messages in dmesg or /var/log/messages . I have tried several configurations but the errors dont go away

[Thu Aug 29 08:15:02 2024] overlayfs: fs on '/home/<username>/.local/share/containers/storage/overlay/opaque-bug-check115720875/l2' does not support file handles, falling back to xino=off.
[Thu Aug 29 08:37:34 2024] overlayfs: fs on '/home/<username>/.local/share/containers/storage/overlay/compat3416904402/lower1' does not support file handles, falling back to xino=off.
[Thu Aug 29 08:37:35 2024] overlayfs: fs on '/home/<username>/.local/share/containers/storage/overlay/metacopy-check3075981219/l1' does not support file handles, falling back to xino=off.
[Thu Aug 29 08:37:35 2024] overlayfs: fs on '/home/<username>/.local/share/containers/storage/overlay/opaque-bug-check974546424/l2' does not support file handles, falling back to xino=off.

~# mount | grep /home
/dev/mapper/vg00-home on /home type ext4 (rw,nosuid,nodev,relatime)

# cat /etc/containers/storage.conf
[storage]
driver = "overlay2"
[storage.options.overlay]
mountopt = "xino=off"
mount_program = "/usr/bin/fuse-overlayfs"

~# podman --version
podman version 3.4.4

### Steps to reproduce the issue

Steps to reproduce the issue
1. Have an ubuntu22 machine
2. install podman

### Describe the results you received

After installing podman 3.4.4 on ubuntu22 we continuously see these messages in dmesg or /var/log/messages . I have tried several configurations but the errors dont go away

### Describe the results you expected

No errors related to xino=off

### podman info output

```yaml
# podman info
WARN[0000] Storage configuration is unset - using hardcoded default graph root "/var/lib/containers/storage"
WARN[0000] Storage configuration is unset - using hardcoded default graph root "/var/lib/containers/storage"
WARN[0000] Storage configuration is unset - using hardcoded default graph root "/var/lib/containers/storage"
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - hugetlb
  - pids
  - rdma
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 8
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: <masked>
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.0-118-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 1457971200
  memTotal: 17035550720
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: true
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 4293115904
  swapTotal: 4294963200
  uptime: 474h 54m 13.46s (Approximately 19.75 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay2.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.10.5
        fuse-overlayfs: version 1.7.1
        FUSE library version 3.10.5
        using FUSE kernel interface version 7.31
    overlay2.mountopt: xino=off
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Wed Dec 31 16:00:00 1969
  GitCommit: ""
  GoVersion: go1.18.1
  OsArch: linux/amd64
  Version: 3.4.4
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
3.4.4 is ancient and we only support the latest version upstream

**Comment by kalyanbhonagiri16** [comment]
> 3.4.4 is ancient and we only support the latest version upstream

That is default version on ubuntu22

**Comment by dinkonin** [comment]
The same issue happens with podman 5.2.2

**dmesg log**
```
[  +0.000007] overlayfs: fs on '/home/user/.local/share/containers/storage/overlay/compat1849726343/lower1' does not support file handles, falling back to xino=off.
[  +0.000003] overlayfs: fs on '/home/user/.local/share/containers/storage/overlay/metacopy-check318920475/l1' does not support file handles, falling back to xino=off.
[  +0.000002] overlayfs: fs on '/home/user/.local/share/containers/storage/overlay/opaque-bug-check1730570080/l2' does not support file handles, falling back to xino=off.
[  +0.000004] overlayfs: fs on '/home/user/.local/share/containers/storage/overlay/volatile-check1621200136/lower' does not support file handles, falling back to xino=off.
[  +0.000002] overlayfs: fs on '/home/user/.local/share/containers/storage/overlay/l/I5S7L5V3COSOJSO7CF3MYFBDXB' does not support file handles, falling back to xino=off.
```
**/etc/containers/storage.conf**
```
[storage]
driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
pull_options = {enable_partial_images = "true", use_hard_links = "false", ostree_repos=""}
[storage.options.overlay]
mountopt = "nodev"

```

**Podman info**
```
host:
  arch: amd64
  buildahVersion: 1.37.2
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-1:2.1.12-1
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: e8896631295ccb0bfdda4284f1751be19b483264'
  cpuUtilization:
    idlePercent: 87.1
    systemPercent: 2.77
    userPercent: 10.13
  cpus: 4
  databaseBackend: sqlite
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  freeLocks: 2047
  hostname: server
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.10.7-arch1-1
  linkmode: dynamic
  logDriver: journald
  memFree: 4441190400
  memTotal: 16675553280
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.12.1-1
      path: /usr/lib/podman/aardvark-dns
      version: aardvark-dns 1.12.1
    package: netavark-1.12.2-1
    path: /usr/lib/podman/netavark
    version: netavark 1.12.2
  ociRuntime:
    name: runc
    package: runc-1.1.13-1
    path: /usr/bin/runc
    version: |-
      runc version 1.1.13
      spec: 1.0.2-dev
      go: go1.22.4
      libseccomp: 2.5.5
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-2024_08_21.1d6142f-1
    version: |
      pasta 2024_08_21.1d6142f
      Copyright Red Hat
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /etc/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 3h 54m 8.00s (Approximately 0.12 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 502528200704
  graphRootUsed: 77259960320
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 9
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 5.2.2
  Built: 1724352649
  BuiltTime: Thu Aug 22 21:50:49 2024
  GitCommit: fcee48106a12dd531702d729d17f40f6e152027f
  GoVersion: go1.23.0
  Os: linux
  OsArch: linux/amd64
  Version: 5.2.2
```

**Comment by Luap99** [comment]
xino doesn't seem to be a mount option set anywhere in our code base which means it likely just uses the kernel default and as your lower file systems doesn't seem to support file handles you always get this warning.

Reading the kernel docs https://docs.kernel.org/filesystems/overlayfs.html#xino seems to indicate that is can be set with CONFIG_OVERLAY_FS_XINO_AUTO kernel option so I assume this is turned on on your kernel so this doesn't sounds like a podman problem to me.

Can you try this config
```
[storage]
driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
pull_options = {enable_partial_images = "true", use_hard_links = "false", ostree_repos=""}
[storage.options.overlay]
mountopt = "nodev,xino=off"
```

and strace the mount syscalls (`strace -f -e mount ...`) to see what options are being passed

**Comment by dinkonin** [comment]
Hello 
> Reading the kernel docs https://docs.kernel.org/filesystems/overlayfs.html#xino seems to indicate that is can be set with CONFIG_OVERLAY_FS_XINO_AUTO kernel option so I assume this is turned on on your kernel so this 
doesn't sounds like a podman problem to me.
This  kernel option is definitely on in default archlunux kernel.
```
zgrep CONFIG_OVERLAY_FS_XINO_AUTO /proc/config.gz                                                                                                                                                    
CONFIG_OVERLAY_FS_XINO_AUTO=y
```



                                        

> Can you try this config
> 
> ```
> [storage]
> driver = "overlay"
> runroot = "/run/containers/storage"
> graphroot = "/var/lib/containers/storage"
> [storage.options]
> additionalimagestores = [
> ]
> pull_options = {enable_partial_images = "true", use_hard_links = "false", ostree_repos=""}
> [storage.options.overlay]
> mountopt = "nodev,xino=off"
> ```
> 
> and strace the mount syscalls (`strace -f -e mount ...`) to see what options are being passed

I've tried running podman with `mountopt = "nodev,xino=off"` the error still occurs in the logs. 

As I'm new to this can you point me to the right direction of what exactly should I `strace -f -e mount` 

I'm evaluating podman using quadlet files on Archlinux with ext4 as the underlying fs if it helps, I also
tried that the same quadlet on Rocky 9.4 (podman 4.9.4-rhel,ext4) and it does not produce errors on startup except this one:
`overlayfs: idmapped layers are currently not supported`

**Comment by Luap99** [comment]
> As I'm new to this can you point me to the right direction of what exactly should I strace -f -e mount

Whatever podman command triggering the warnings, i.e. 
strace -f -e mount podman run ...

**Comment by dinkonin** [comment]
I've attached the [podman.strace.log](https://github.com/user-attachments/files/16846387/podman.strace.log) , the command produced the same error 

```

Sep 03 12:23:20 server kernel: overlayfs: upper fs does not support file handles, falling back to index=off.
Sep 03 12:23:20 server kernel: overlayfs: fs on '/home/user/.local/share/containers/storage/overlay/l/5KBVGOMUKOLZQS6D6NWM23URLO' does not support file handles, falling back to xino=off.```

**Comment by Luap99** [comment]
ah strace truncated the options as they are to long you need to add `-s 4096`

Anyhow I see the problem with the config file, the root storage.conf file is not used for the rootless users except the rootless_storage_path option. The config file must be created in `~/.config/containers/storage.conf` as rootless in order for the mount options to take effect. Something like this seems to apply the storage.conf options:
```
[storage]
driver = "overlay"
[storage.options]
[storage.options.overlay]
mountopt = "nodev,metacopy=on,xino=off"
```


But regardless this seems to be something wrong with your kernel mount options I think, we do not set xino=on or xino=auto so the fact that it defaults to that and it fails on your fs is odd and this has nothing to so with podman.

If you run something like this (on the same fs as the podman storage) I assume it generates the same warning
```
$ mkdir lower work upper merged
$ unshare -rm mount -t overlay overlay -o lowerdir=lower,upperdir=upper,workdir=work merged
```

**Comment by kalyanbhonagiri16** [comment]
The config i tried on user level and it didnt help and yes it generates same warning when i run the commands you shared

[Tue Sep  3 09:09:22 2024] overlayfs: fs on 'lower' does not support file handles, falling back to xino=off.

**Comment by Luap99** [comment]
Ack sounds like some problem with the kernel config and/or filesystem then. I cannot help you with that.

**Comment by jklaiho** [comment]
> Anyhow I see the problem with the config file, the root storage.conf file is not used for the rootless users except the rootless_storage_path option. The config file must be created in ~/.config/containers/storage.conf as rootless in order for the mount options to take effect.

@Luap99 since when has this been the case? Looking at the [rootless tutorial](https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md#storageconf) storage.conf section, it says there that Podman reads `/etc/containers/storage.conf` in any case, but for rootless setups just ignores the `graphroot` and `runroot` settings there.

I've never had any rootless-specific config files (`containers.conf`, `storage.conf` or `registries.conf`) under `${XDG_CONFIG_HOME}/containers` on any of my servers. I know that I manually set `driver` to `overlay` back in the 4.x days in `/etc/containers/storage.conf` for my rootless containers, and it had the desired effect.
