### ISSUE TITLE
Image list sorted by repository is not always deterministic

### ISSUE THREAD

**Issue by oszi** [containers/podman#23803]
### Issue Description

In certain conditions, `podman image list --sort=repository` produces different results. See the steps to reproduce.
I think, it's based on the time the images were last touched on the disk.
It would be nice if sort could be tuned by a second field - also fixing this issue. [sort=repository,tag]

### Steps to reproduce the issue

```bash
alias podman-images="podman image list --filter=dangling=false --sort=repository --format='{{.Repository}}:{{.Tag}}'"
podman pull quay.io/oszi/toolbox:latest quay.io/oszi/toolbox:latest-amd64

podman-images
podman-images | xargs podman pull
podman-images
```

### Describe the results you received

The two tags of the same image are flipped after every pull.

### Describe the results you expected

Sorting should always be deterministic.

### podman info output

REDACTED / `podman-5.2.2-1.fc40.x86_64`

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

**Comment by Luap99** [comment]
>Sorting should always be deterministic.

Well sounds like it is if it depends on the pull order. 

Anyhow I do agree if we sort by repository it would make sense to imply to also sort the tags as well without having to specify an extra cli arg.

**Comment by oszi** [comment]
Sounds good. I wasn't sure secondary sorting can be changed internally this easily.
Thank you for the quick fix.
