### ISSUE TITLE
Podman over SSH in native mode does not use custom config `~/.ssh/config`

### ISSUE THREAD

**Issue by evolutics** [containers/podman#23831]
### Issue Description

Connecting to a remote Podman socket over native SSH (e.g., `podman --host ssh://my-host --ssh native ps`) fails, despite the local `~/.ssh/config` file containing an entry for `Host my-host` (i.e., `ssh my-host` succeeds).

### Steps to reproduce the issue

Set up:

1. Run a test VM locally using Vagrant:

   ```bash
   vagrant init bento/fedora-40
   vagrant up
   ```

1. Set up SSH access to the VM:

   ```bash
   vagrant ssh-config --host my-host >>~/.ssh/config
   ssh my-host echo 'SSH setup is OK'
   ```

1. Set up Podman on the VM (with Docker API), running an example container:

   ```bash
   ssh my-host <<EOF
   sudo dnf --assumeyes install podman
   podman info

   systemctl --user enable --now podman
   sudo loginctl enable-linger
   sudo ln --force --symbolic /usr/bin/podman /usr/local/bin/docker

   podman run --detach docker.io/hashicorp/http-echo:1.0
   EOF
   ```

Test:

- Local Docker can connect to the remote Podman service, showing 1 container:

  ```
  docker --host ssh://my-host ps
  ```

- But local Podman cannot connect to remote Podman – see error below:

  ```
  podman --host ssh://my-host --ssh native ps
  ```

Tear down:

1. Remove Vagrant resources:

   ```
   vagrant destroy
   rm --force --recursive .vagrant Vagrantfile
   ```

1. Undo changes to `~/.ssh/config`.

### Describe the results you received

```console
$  podman --host ssh://my-host --ssh native ps
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: failed to connect: dial tcp: lookup my-host: device or resource busy: ssh://my-host
```

### Describe the results you expected

```console
$  docker --host ssh://my-host ps
CONTAINER ID   IMAGE                     COMMAND   CREATED              STATUS              PORTS     NAMES
abcdef123456   hashicorp/http-echo:1.0   ""        About a minute ago   Up About a minute             foo_bar
```

### podman info output

```yaml
$ podman version
Client:       Podman Engine
Version:      5.2.2
API Version:  5.2.2
Go Version:   go1.22.5
Built:        Tue Jan  1 01:00:00 1980
OS/Arch:      linux/amd64

$ uname --all
Linux foo-desktop 5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 GNU/Linux


$ vagrant ssh -- podman version
Client:       Podman Engine
Version:      5.2.2
API Version:  5.2.2
Go Version:   go1.22.6
Built:        Wed Aug 21 00:00:00 2024
OS/Arch:      linux/amd64

$ vagrant ssh -- uname --all
Linux fedora 6.8.7-300.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Apr 17 19:21:08 UTC 2024 x86_64 GNU/Linux
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

–

### Additional information

Possibly related:

- https://github.com/containers/podman/issues/21113
- https://github.com/containers/podman/pull/16601

**Comment by afbjorklund** [comment]
This is a known shortcoming, you have to add the basic ssh config to the podman "system connection"

**Comment by evolutics** [comment]
Thanks for your fast explanation!

> This is a known shortcoming, you have to add the basic ssh config to a podman "system connection"

Does this mean that I'd have to unpack my (possibly generated) `~/.ssh/config` file to translate the supported subset of options to `podman system connection add`? The [manual](https://docs.podman.io/en/latest/markdown/podman-system-connection-add.1.html) seems to suggest so.

A workaround would be to extend the `$PATH` with a folder containing a custom `ssh` executable that essentially forwards to `/usr/bin/ssh -F /my/ssh/config`. This works with Docker, however not with Podman – I guess I am misunderstanding what `--ssh native` does exactly.

**Comment by afbjorklund** [comment]
I think it should be possible for podman to parse the basics, but you would lose out on any other ssh features...

* https://github.com/containers/podman/issues/21113#issuecomment-1873910478

The same issue exists in Lima, and is worse now when Podman Desktop can parse connections but not forwards...

* https://github.com/containers/podman-desktop/issues/8281#issuecomment-2260233308

**Comment by afbjorklund** [comment]
> I guess I am misunderstanding what `--ssh native` does exactly.

It seems to be used a little inconsistently around the podman code base.

Some parts are using the "SSHMode", but some are still calling `ssh.Dial`.

**Comment by afbjorklund** [comment]
I think it has been this way since Podman v2, that is before the connections...

e.g. https://boot2podman.github.io/2020/07/22/machine-replacement.html

**Comment by Luap99** [comment]
ssh=native was never properly finished AFAIK, it doesn't seem to be tested either.

I do agree this should work with native mode as we call the ssh binary which should read you ssh config so yes this seems like a bug to me.

**Comment by afbjorklund** [comment]
Most of the current system seem to not be supporting `ssh:` at all (even though it was introduced in Docker 18.09), but instead rely on some _other_ system creating a tunnel for them (in case the server does not support the old `tcp:` that is).

**Comment by afbjorklund** [comment]
If wanting to support the Docker syntax, then there also needs to be something added for the default path. With the docker client, the $DOCKER_HOST is coming from the environment on the remote side but with podman it is local...

So `--host ssh://my-host` is not going to fly with podman, because it doesn't have a path to `podman.sock` - in pretty much the same way that `--host ssh://my-host/run/podman/podman.sock` fails with a docker client because it **does** have a path.

**Comment by afbjorklund** [comment]
The patched version looks like this:

`Error: unable to connect to Podman socket: Get "http://d/v4.9.3/libpod/_ping": ssh: rejected: connect failed (open failed)`

Instead of the default podman version:

`Error: unable to connect to Podman socket: failed to connect: dial tcp: lookup lima-podman: no such host`

----

So the parsing of the ssh config goes OK:

```
DEBU[0000] Alias: lima-podman                           
DEBU[0000] User: anders                                 
DEBU[0000] Hostname: 127.0.0.1                          
DEBU[0000] Port: 39901                                  
DEBU[0000] Identity: "/home/anders/.lima/_config/user"  
```

But the connection still fails, due to path.

And it is hard to "guess" (need to read env)

---

Something similar to this, connect to the remote server and try to find the socket path.

https://docs.docker.com/engine/security/rootless/#expose-docker-api-socket-through-ssh

I think with Podman, you would call `podman info` on the remote side and parse the output?

```
    path: /run/user/1000/podman/podman.sock
```

**Comment by afbjorklund** [comment]
Parsing the basic 4 values and querying for the 5th seems to be working - even with "golang":

```console
$ podman-remote --host ssh://lima-podman version
Client:       Podman Engine
Version:      4.9.3
API Version:  4.9.3
Go Version:   go1.22.3
Git Commit:   59c8f28173a8c65d181c08622947135101fc9ef1-dirty
Built:        Sun Sep  1 22:29:36 2024
OS/Arch:      linux/amd64

Server:       Podman Engine
Version:      5.2.2
API Version:  5.2.2
Go Version:   go1.22.6
Built:        Wed Aug 21 02:00:00 2024
OS/Arch:      linux/amd64
```

It doesn't use any of the other features of the ssh_config, so that does need the "native" ssh...

The most important one is the `ControlMaster auto`*

----

\* https://docs.docker.com/engine/security/protect-access/#ssh-tips

Others include using AES hardware crypto (where available), etc etc

**Comment by evolutics** [comment]
Thank you very much for your hard work on this.

For anyone stumbling across this issue, above mentioned workaround with the SSH tunnel looks like so:

Keep

```bash
ssh -F ssh_config -L "${PWD}/my.sock:/run/user/1000/podman/podman.sock" my-host
```

running, where `-F ssh_config` can be omitted if `~/.ssh/config` should apply. Also, `/run/user/1000/podman/podman.sock` is just an example; it may be different on your remote host (see `podman info`).

Now `podman --host "unix://${PWD}/my.sock" ps` works.

**Comment by afbjorklund** [comment]
> For anyone stumbling across this issue, above mentioned workaround with the SSH tunnel...

It's not only a workaround, but also an optimization that is used by Podman Desktop and Lima

**Comment by afbjorklund** [comment]
Another (actual) workaround would be to use `ssh -G`, with the `ssh -F` if needed.

And let `ssh` handle the parsing of the `ssh_config`, and just look for the results:

```
ssh -G lima-podman | grep -E "^(user|hostname|port|identityfile) "
```

And then feed that as input to `podman system connection add`, to look up the path.
