### ISSUE TITLE
Dashboard message seems misleading?

### ISSUE THREAD

**Issue by pwright** [containers/podman#23859]
### Issue Description

The Podman Desktop dashboard suggests 'to start working with containers, OpenShift Local needs to be installed'.. 
Might be misleading to some users.

![image](https://github.com/user-attachments/assets/c061161b-5828-4d6e-8a32-c2cac0b55ed7)

### Steps to reproduce the issue

Start Podman Desktop... that's it!

### Describe the results you received

 'to start working with containers, OpenShift Local needs to be installed'.

### Describe the results you expected

 'to start working with OpenShift, OpenShift Local needs to be installed'.

### podman info output

```yaml
5.2.2 x86
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
You need to report podman-desktop issues on the podman-desktop repository
https://github.com/containers/podman-desktop/issues

**Comment by pwright** [comment]
created https://github.com/containers/podman-desktop/issues/8742
I saw the readme here mentioned 'Podman Desktop', and linked to https://podman-desktop.io
I missed the later sentence that linked to the correct repo.
