### ISSUE TITLE
[Podman Desktop V1.12.0] Not exposing the UDP ports using docker-compose

### ISSUE THREAD

**Issue by joaopalma5** [containers/podman#23901]
### Issue Description

Open ports using docker-compose like
"12201:12201/udp"
"8888:8888/udp"
With these configs on docker-compose the ports not are shown when I do "Get-NetUDPEndpoint | Select-Object LocalPort, OwningProcess | Sort-Object LocalPort"

### Steps to reproduce the issue

Clone this git:
https://github.com/s0p4L1n3/Graylog-Ready-to-go-Compose/blob/main/docker-compose.yml
Run docker-compose up -d
Run docker-compose ps
The output will be like:
NAME IMAGE COMMAND SERVICE CREATED STATUS PORTS
graylog-graylog-1 docker.io/graylog/graylog:6.0 "" graylog 52 minutes ago Up 52 minutes 5044/tcp, 5140/udp, 5140/tcp, 9000/tcp, 8888/udp, 12201/tcp, 13301/tcp, 12201/udp

That seems all ok the TCP and UDP ports are open but...
If you do
Get-NetUDPEndpoint | Select-Object LocalPort, OwningProcess | Sort-Object LocalPort

The UDP ports not are listen/not are open...

### Describe the results you received

Only TCP ports are open

### Describe the results you expected

The excepted will be both TCP and UDP ports are open

### podman info output
None

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details
```yaml
Operating system
Windows 11

Installation Method
Installer from website/GitHub releases

Version
1.12.0
```
### Additional information

I don't know how but the ports are open inside of WSL, the bug it's just on the host machine

**Comment by Luap99** [comment]
> I don't know how but the ports are open inside of WSL, the bug it's just on the host machine

If the ports are open in the machine then there is not much we can do, we simply depend on the WSL proxy to forward ports from the host accordingly https://learn.microsoft.com/en-us/windows/wsl/networking#default-networking-mode-nat

I am not aware of anything udp specific? If th eports are bound inside WSL by podman then it is working as far as podman is concerned.
