### ISSUE TITLE
`--expose=8000/sctp` causes Error: protocol SCTP is not allowed

### ISSUE THREAD

**Issue by sreevatsank1999** [containers/podman#23911]
### Issue Description

Unable to run container image built with `EXPOSE 8000/sctp` in the `Dockerfile` or equivalently run with `--expose=8000/sctp` fail to run as `root` or a non-root user with the following error:
> Error: validating protocols for exposed port 8000: protocol SCTP is not allowed for exposed ports

### Steps to reproduce the issue

Steps to reproduce the issue
1. `podman run -it --expose 8000/sctp ubuntu:22.04 bash`

or
 
2. `podman run -it oaisoftwarealliance/oai-amf:v2.1.0 bash` (This image is built with `EXPOSE 38412/sctp` )

### Describe the results you received

> Error: validating protocols for exposed port 8000: protocol SCTP is not allowed for exposed ports

### Describe the results you expected

I expect it to run regardless, as privileged or rootless, as `--expose` or `EXPOSE` should not have any effect on the runtime. 

https://github.com/containers/podman/blob/c12c86e303f502684a84f817ad0004582ab67a1f/docs/source/markdown/options/expose.md?plain=1#L7-L12

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.37.2
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.1.12, commit: f363b49bbd4daee434d5cf0099f567502a94fbbb'
  cpuUtilization:
    idlePercent: 98.65
    systemPercent: 0.79
    userPercent: 0.55
  cpus: 64
  databaseBackend: boltdb
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  freeLocks: 2000
  hostname: wcsng-36
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 3938
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 3938
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 6.5.0-44-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 97522569216
  memTotal: 540450496512
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: Unknown
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.12.2
    package: Unknown
    path: /usr/libexec/podman/netavark
    version: netavark 1.12.2
  ociRuntime:
    name: crun
    package: Unknown
    path: /usr/local/bin/crun
    version: |-
      crun version 1.16.1
      commit: afa829ca0122bd5e1d67f1f38e6cc348027e3c32
      rundir: /run/user/3938/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  pasta:
    executable: /usr/local/bin/pasta
    package: Unknown
    version: |
      pasta 2024_09_06.6b38f07
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/3938/podman/podman.sock
  rootlessNetworkCmd: slirp4netns
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/local/bin/slirp4netns
    package: Unknown
    version: slirp4netns-like wrapper for pasta
  swapFree: 0
  swapTotal: 0
  uptime: 797h 51m 49.00s (Approximately 33.21 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/skadaveru/.config/containers/storage.conf
  containerStore:
    number: 43
    paused: 0
    running: 4
    stopped: 39
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /mnt/intA-hddr0-4tb/skadaveru/.local/share/containers/storage
  graphRootAllocated: 3999688294400
  graphRootUsed: 1382029111296
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 306
  runRoot: /run/user/3938/containers
  transientStore: false
  volumePath: /mnt/intA-hddr0-4tb/skadaveru/.local/share/containers/storage/volumes
version:
  APIVersion: 5.2.2
  Built: 1725933101
  BuiltTime: Mon Sep  9 18:51:41 2024
  GitCommit: fcee48106a12dd531702d729d17f40f6e152027f-dirty
  GoVersion: go1.23.1
  Os: linux
  OsArch: linux/amd64
  Version: 5.2.2
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Bare-metal Ubuntu 22.04 Server

### Additional information

`podman run -it --publish 8000:8000/sctp ubuntu:22.04 bash `  behaves as described in 

https://github.com/containers/podman/blob/c12c86e303f502684a84f817ad0004582ab67a1f/docs/source/markdown/options/publish.md?plain=1#L15-L18

It runs successfully when run as `root` and when run as a non-root user I get the following error:
> Error: rootlessport spec was not validated?

## Solution (possibly)

The following fix worked for me.

```diff
--- a/pkg/specgen/generate/ports.go
+++ b/pkg/specgen/generate/ports.go
@@ -356,7 +356,7 @@ func createPortMappings(s *specgen.SpecGenerator, imageData *libimage.ImageData)
                        if port == 0 {
                                return nil, nil, fmt.Errorf("cannot expose 0 as it is not a valid port number")
                        }
-                       protocols, err := checkProtocol(proto, false)
+                       protocols, err := checkProtocol(proto, true)
                        if err != nil {
                                return nil, nil, fmt.Errorf("validating protocols for exposed port %d: %w", port, err)
                        }

```

**Comment by sbrivio-rh** [comment]
This is an issue in the documentation, because available rootless network back-ends don't support SCTP.

For pasta, this is the related [tracker](https://bugs.passt.top/show_bug.cgi?id=3), but it's such a low priority that we never got to it.

Same for slirp4netns: there's a [TODO](https://github.com/rootless-containers/slirp4netns/blob/ee1542e1532e6a7f266b8b6118973ab3b10a8bb5/api.c#L112) in the port forwarding implementation.

**Comment by Luap99** [comment]
@sbrivio-rh No not really, --expose != --publish as mentioned in the linked docs in thus nothing but adding the port to the metadata which will be used on podman commit to add a sctp port to the image config.
But given expose is never used by default and users have to explicitly publish the port it doesn't really make sense to error here as it just prevent users from being able to run the image which a sctp port in them defined.

**Comment by Luap99** [comment]
@sreevatsank1999 I think your diff make sense, although if all callers pass true then we should just remove the arg allowSCTP arg from that function.

Looking at the git log to try to figure out why expose is special and not allowed for expose I cannot find any reason, it was added in https://github.com/containers/podman/commit/7ac3d906b5c080803f7898d3307af87bb57ad436 but without any reason given. @mheon Can we remove that sctp check? I cannot see why this would cause any harm.

**Comment by mheon** [comment]
I have no memory of why I did that. My two questions would be: Can we commit SCTP exposed ports to an image, and if we make a container from an image with an SCTP exposed port and use `-P`, does it properly publish the port?

If both of those are true I'm fine with removing the check.
