### ISSUE TITLE
Add --cgroup-manager to the podman run command

### ISSUE THREAD

**Issue by brunzefb** [containers/podman#23917]
### Feature request description

podman build has a --cgroup-manager.  Add the same flag to podman run.

### Suggest potential solution

Change the code to add the flag to podman run.

### Have you considered any alternatives?

My current workaround is to modify the containers.conf with
`sed -i 's/\[engine\]/\[engine\]\ncgroup_manager = "cgroupfs"/' /usr/share/containers/containers.conf`
While this works, its harder than just passing the option, which is also more explicit.

### Additional context

Context is a Jenkins build agent which is itself a pod (running container)  It does a docker-in-docker build, followed by a podman run. `
```
podman run -it ACCOUNT.dkr.ecr.us-east-2.amazonaws.com/POD:qa_1_0-1c1b272-89 
time="2024-09-06T21:32:39-04:00" 
level=warning msg="Failed to add conmon to systemd sandbox cgroup: 
      dial unix /run/systemd/private: connect: no such file or directory"
```

**Comment by giuseppe** [comment]
you need to pass it to the podman command itself:

```
podman --cgroup-manager $MANAGER run ...`

**Comment by rhatdan** [comment]
$ podman --help | grep cgroup-manager
      --cgroup-manager string       Cgroup manager to use ("cgroupfs"|"systemd") (default "systemd")
