### ISSUE TITLE
podman-systemd.unit.5.md: example `--add-host foobar` in podman-systemd.unit.5.md has incorrect syntax

### ISSUE THREAD

**Issue by eriksjolund** [containers/podman#23954]
### Issue Description

```
--add-host foobar
```
in
https://github.com/containers/podman/blob/fdb8b1c6d3a6820acfd5af812075ff0a0721748c/docs/source/markdown/podman-systemd.unit.5.md?plain=1#L306

does not follow the syntax of the __podman run__ option __--add-host__

__--add-host__=host:ip

See man page of `podman run` https://docs.podman.io/en/latest/markdown/podman-run.1.html#add-host-host-ip

### Steps to reproduce the issue

Steps to reproduce the issue
1.
2.
3.

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by baude** [comment]
care to provide a PR?

**Comment by eriksjolund** [comment]
Sure, I'll do that.
