### ISSUE TITLE
Volumes as OCI artefacts

### ISSUE THREAD

**Issue by ericcurtin** [containers/podman#23956]
### Feature request description

This is a feature I wish podman has had for a while:

https://kubernetes.io/blog/2024/08/16/kubernetes-1-31-image-volume-source/

build a directory structure as an OCI artefact, push to to an OCI registry so someone can download and bind mount somewhere.

Basically downloadable volumes from OCI registries.

**Comment by Luap99** [comment]
Duplicate of #23775
