### ISSUE TITLE
Invalid rpm/podman.spec file when building from source

### ISSUE THREAD

**Issue by joshmcorreia** [containers/podman#23969]
### Issue Description

The `rpm/podman.spec` file is not a valid spec file according to `dnf builddep`. I'm following the instructions at https://podman.io/docs/installation#building-from-source.

### Steps to reproduce the issue

Steps to reproduce the issue:
```
# git clone https://github.com/containers/podman.git
# cd podman
# dnf -y builddep rpm/podman.spec --enablerepo=codeready-builder-for-rhel-$(rpm --eval %{?rhel})-$(uname -m)-rpms
Updating Subscription Management repositories.
Last metadata expiration check: 1:43:08 ago on Mon Sep 16 11:52:10 2024.
RPM: error: %changelog entries must start with *
Failed to open: 'rpm/podman.spec', not a valid spec file: can't parse specfile

Error: Some packages could not be found.
```

### Describe the results you received

Unable to build from source on RHEL8.

### Describe the results you expected

I expect to be able to build from source on RHEL8.

### podman info output

```yaml
N/A - happens before even running podman
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

```
# cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.8 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.8 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
```

### Additional information

N/A

**Comment by rhatdan** [comment]
@lsm5 PTAL

**Comment by lsm5** [comment]
@joshmcorreia Current main branch will have trouble building on rhel8 because of lack of `rpmautospec` support on rhel8 (there may be other issues, but that's the issue as seen in your error log). You can get around that by changing the `%changelog` section to look like:

```
%changelog
* Mon May 01 2023 Foo Bar <foobar@example.com>
- Placeholder changelog for envs that are not autochangelog-ready
```

The doc you mentioned needs to be updated to get rid of rhel8 as rhel8 is no longer under active development. I'd recommend switching to rhel9 / centos stream 9 or higher or Fedora.

Closing...

**Comment by joshmcorreia** [comment]
> The doc you mentioned needs to be updated to get rid of rhel8 as rhel8 is no longer under active development.

RHEL8 still has maintenance support until 5/31/2029 which is still used in production by a ton of organizations. Does podman only support active development OSs?

**Comment by rhatdan** [comment]
RHEL8 is supported only for CVE Back ports at this point.
