### ISSUE TITLE
Processes top api service incompatibility

### ISSUE THREAD

**Issue by iongion** [containers/podman#23981]
### Issue Description

Describe your issue

The compat endpoints do not behave the same

- Api docs of docker <https://docs.docker.com/reference/api/engine/version/v1.39/#tag/Container/operation/ContainerTop>
- Api docs of podman <https://docs.podman.io/en/latest/_static/api.html#tag/containers-(compat)/operation/ContainerTop>

### Steps to reproduce the issue

Steps to reproduce the issue

1. Get processes list using libpod compat endpoint
2. Get processes list using docker api engine endpoint
3. Compare

### Describe the results you received

Describe the results you received

Received a list of strings

### Describe the results you expected

Describe the results you expected

Receive a list of lists of strings

### podman info output

```yaml
Podman is working fine on 5.2.2
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

It happens on any environment

**Comment by mheon** [comment]
Can you be more specific about the incompatibilities you're seeing?

**Comment by iongion** [comment]
Sure Matt, look, this is response shape from docker api

> notice how columns are separated in the array of `Processes` - each column, its own element

![image](https://github.com/user-attachments/assets/b6f5e4aa-359a-45b0-810f-5ada6c766600)

- Now the libpod response

> notice how there is only one element in the Processes list

![image](https://github.com/user-attachments/assets/2b03903f-cd75-47a9-a086-fc1a17cb6231)
