### ISSUE TITLE
Typo in "Error: getting store info: unable to collect graph root usasge " 

### ISSUE THREAD

**Issue by neils-ibm** [containers/podman#24001]
### Issue Description

There is a minor typo for the word usage (usasge):

`"Error: getting store info: unable to collect graph root usasge ..."`

### Steps to reproduce the issue

Steps to reproduce the issue
1.  No need to repro, simple typo in the message
2.
3.

### Describe the results you received

N/A

### Describe the results you expected

Correct spelling for the word usage.

### podman info output

```yaml
N/A
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

N/A

### Additional information

Error is in libpod/info.go line 232.

**Comment by rhatdan** [comment]
Interested in opening a PR?

I wonder why codespell is not catching this one.

**Comment by neils-ibm** [comment]
Someone from our team will open a PR later today.  Thanks.

Neil Shah
  CIO Data Center Services – IBM Z Specialist
  Certified IT Specialist
  Member of the IBM Academy of Technology
  Finance and Operations
  Office: 845-433-1778
  Email: ***@***.******@***.***>

From: Daniel J Walsh ***@***.***>
Sent: Wednesday, September 18, 2024 11:52 AM
To: containers/podman ***@***.***>
Cc: Neil Shah ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [containers/podman] Typo in "Error: getting store info: unable to collect graph root usasge " (Issue #24001)

Interested in opening a PR? I wonder why codespell is not catching this one. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message ID: <containers/podman/issues/24001/2358841962@ github. com>


Interested in opening a PR?

I wonder why codespell is not catching this one.
