### ISSUE TITLE
Unable to install the latest podman on Ubuntu 22.04 by following the instructions on the website

### ISSUE THREAD

**Issue by giuliohome** [containers/podman#24013]
### Issue Description

I have seen https://github.com/containers/podman/issues/21249 and resolved the problem with this https://github.com/containers/podman/issues/21249#issuecomment-1890753225 but I think it should be opened a new issue.
Indeed [the instructions say to install podman from ap](https://podman.io/docs/installation#ubuntu)t which in turn is installing an old 3 release, not 4.

### Steps to reproduce the issue

Steps to reproduce the issue
1. choose an Ubuntu 22.04.3 LTS OS
2. follow the doc instruction and apt install 
3. check the installled podman version

### Describe the results you received

As I said, the version installed by apt on Ubuntu is outdated and not currently usable.

### Describe the results you expected

Please update the docs or answer here below to show the correct, current way to install podman on ubuntu.

### podman info output

from apt install following the docs

$ podman info
```yaml
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: unknown'
  cpus: 12
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  hostname: WPWS19069419
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.153.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 6329237504
  memTotal: 7691501568
  ociRuntime:
    name: runc
    package: 'runc: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.1.12-0ubuntu2~22.04.1
      spec: 1.0.2-dev
      go: go1.21.1
      libseccomp: 2.5.3
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 2147483648
  swapTotal: 2147483648
  uptime: 13m 49.11s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/giulio/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/giulio/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 5
  runRoot: /run/user/1000/containers
  volumePath: /home/giulio/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.4
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.18.1
  OsArch: linux/amd64
  Version: 3.4.4
```

Instead searching the closed issues and applying the suggestion from a comment in a closed issue:
$ podman info
```yaml
host:
  arch: amd64
  buildahVersion: 1.31.2
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon_2:2.1.12-0ubuntu22.04+obs20.30_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: '
  cpuUtilization:
    idlePercent: 99.32
    systemPercent: 0.31
    userPercent: 0.36
  cpus: 12
  databaseBackend: boltdb
  distribution:
    codename: jammy
    distribution: ubuntu
    version: "22.04"
  eventLogger: journald
  freeLocks: 2048
  hostname: WPWS19069419
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.153.1-microsoft-standard-WSL2
  linkmode: dynamic
  logDriver: journald
  memFree: 6177370112
  memTotal: 7691501568
  networkBackend: cni
  networkBackendInfo:
    backend: cni
    dns:
      package: golang-github-containernetworking-plugin-dnsname_1.3.1+ds1-2_amd64
      path: /usr/lib/cni/dnsname
      version: |-
        CNI dnsname plugin
        version: 1.3.1
        commit: unknown
    package: 'golang-github-containernetworking-plugin-dnsname, containernetworking-plugins:
      /usr/lib/cni'
    path: /usr/lib/cni
  ociRuntime:
    name: crun
    package: crun_101:1.14.4-0ubuntu22.04+obs70.24_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.14.4
      commit: a220ca661ce078f2c37b38c92e66cf66c012d9c1
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.0.1-2_amd64
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.6.1
  swapFree: 2147483648
  swapTotal: 2147483648
  uptime: 0h 18m 49.00s
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
  - quay.io
store:
  configFile: /home/giulio/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/giulio/.local/share/containers/storage
  graphRootAllocated: 1081101176832
  graphRootUsed: 10735333376
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 5
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/giulio/.local/share/containers/storage/volumes
version:
  APIVersion: 4.6.2
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.18.1
  Os: linux
  OsArch: linux/amd64
  Version: 4.6.2
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by giuliohome** [comment]
Sorry but I understand that you have no control over distros but it is not usable, e.g. I would get error from mount cache type etc.... The question here for the documentation is to explain how to install podman without compiling from source - if possible.

At least, reference the discussion in the docs? And what about summarizing the viable answers from the discussion etc...?

**Comment by Luap99** [comment]
We as a project no longer provide a repo for ubuntu/debian so there is no official way, the discussion https://github.com/containers/podman/discussions/17362 links third party repos that you can use if you like that, But as project I do not see us recommending external repos so compiling from source it is as far as I am concerned.

**Comment by giuliohome** [comment]
Maybe just writing that in the docs instead of referencing apt?

**Comment by Luap99** [comment]
Well I would assume most users seems to be fine with the old versions, after all that is why that have chosen debian/ubuntu?

**Comment by giuliohome** [comment]
> Well I would assume most users seems to be fine with the old versions

I don't know about the stats, but it's not fine for me, [I can't deploy rust](https://rocket.rs/guide/v0.5/deploying/#deploying) to a container for example

> after all that is why that have chosen debian/ubuntu?

I have Fedora as well of course, but sometime I need debian for compatibility and I need to build image there too.> Well I would assume most users seems to be fine with the old versions

I can't speak to the stats, but it's not fine for me. For instance, [I can't deploy rust](https://rocket.rs/guide/v0.5/deploying/#deploying) to a container due to outdated versions.

> after all that is why that have chosen debian/ubuntu?

I use Fedora as well, but sometimes I need Debian for compatibility reasons, and I need to build images there too.

**Comment by giuseppe** [comment]
this is a packaging issue, nothing that the upstream project can help with.

> The main question for the documentation is: Can you explain how to install Podman without having to compile it from source (if that's possible)?
> 
> At the very least, could the documentation reference the discussion? Also, could it include a summary of the viable solutions mentioned in that discussion?

that requires that we maintain that piece of information updated.

Have you considered running a nested podman so you could run an updated podman inside a container?  We maintain a container image for that: https://quay.io/repository/containers/podman

**Comment by giuseppe** [comment]
we use issues to track what needs to be addressed in the upstream project, but in this case we have no control on the way distros package podman.

But since you are facing the problem, and we already have an ongoing discussion, we can use it to find something that works for you.

Now, if you want to use Docker because you've chosen a distro that doesn't keep up with updated packages, that’s your choice

**Comment by giuliohome** [comment]
We are talking past each other: I have unsubscribed this discussion.
