### ISSUE TITLE
Centos7.9 Build 5.1.2

### ISSUE THREAD

**Issue by BeyondTheBlade** [containers/podman#24051]
### Issue Description

podman run failed

### Steps to reproduce the issue

[root@7ohx4720 ~]# podman run -itd --name=hello --log-level=debug quay.io/podman/hello
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called run.PersistentPreRunE(podman run -itd --name=hello --log-level=debug quay.io/podman/hello) 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
INFO[0000] Using sqlite as database backend             
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /vdb/podman/graph           
DEBU[0000] Using run root /vdb/podman/run               
DEBU[0000] Using static dir /vdb/podman/graph/libpod    
DEBU[0000] Using tmp dir /run/libpod                    
DEBU[0000] Using volume path /vdb/podman/graph/volumes  
DEBU[0000] Using transient store: false                 
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is not being used 
DEBU[0000] Cached value indicated that native-diff is usable 
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Initializing event backend journald          
DEBU[0000] Configured OCI runtime crun initialization failed: no valid executable found for OCI runtime crun: invalid argument 
DEBU[0000] Configured OCI runtime crun-vm initialization failed: no valid executable found for OCI runtime crun-vm: invalid argument 
DEBU[0000] Configured OCI runtime youki initialization failed: no valid executable found for OCI runtime youki: invalid argument 
DEBU[0000] Configured OCI runtime ocijail initialization failed: no valid executable found for OCI runtime ocijail: invalid argument 
DEBU[0000] Configured OCI runtime crun-wasm initialization failed: no valid executable found for OCI runtime crun-wasm: invalid argument 
DEBU[0000] Configured OCI runtime runj initialization failed: no valid executable found for OCI runtime runj: invalid argument 
DEBU[0000] Configured OCI runtime kata initialization failed: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] Configured OCI runtime runsc initialization failed: no valid executable found for OCI runtime runsc: invalid argument 
DEBU[0000] Configured OCI runtime krun initialization failed: no valid executable found for OCI runtime krun: invalid argument 
DEBU[0000] Using OCI runtime "/usr/bin/runc"            
INFO[0000] Setting parallel job count to 25             
DEBU[0000] Pulling image quay.io/podman/hello (policy: missing) 
DEBU[0000] Looking up image "quay.io/podman/hello" in local containers storage 
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] } 
DEBU[0000] Trying "quay.io/podman/hello:latest" ...     
DEBU[0000] parsed reference into "[overlay@/vdb/podman/graph+/vdb/podman/run:overlay.mountopt=nodev]@5dd467fce50b56951185da365b5feee75409968cbab5767b9b59e325fb2ecbc0" 
DEBU[0000] Found image "quay.io/podman/hello" as "quay.io/podman/hello:latest" in local containers storage 
DEBU[0000] Found image "quay.io/podman/hello" as "quay.io/podman/hello:latest" in local containers storage ([overlay@/vdb/podman/graph+/vdb/podman/run:overlay.mountopt=nodev]@5dd467fce50b56951185da365b5feee75409968cbab5767b9b59e325fb2ecbc0) 
DEBU[0000] exporting opaque data as blob "sha256:5dd467fce50b56951185da365b5feee75409968cbab5767b9b59e325fb2ecbc0" 
DEBU[0000] Looking up image "quay.io/podman/hello:latest" in local containers storage 
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] } 
DEBU[0000] Trying "quay.io/podman/hello:latest" ...     
DEBU[0000] parsed reference into "[overlay@/vdb/podman/graph+/vdb/podman/run:overlay.mountopt=nodev]@5dd467fce50b56951185da365b5feee75409968cbab5767b9b59e325fb2ecbc0" 
DEBU[0000] Found image "quay.io/podman/hello:latest" as "quay.io/podman/hello:latest" in local containers storage 
DEBU[0000] Found image "quay.io/podman/hello:latest" as "quay.io/podman/hello:latest" in local containers storage ([overlay@/vdb/podman/graph+/vdb/podman/run:overlay.mountopt=nodev]@5dd467fce50b56951185da365b5feee75409968cbab5767b9b59e325fb2ecbc0) 
DEBU[0000] exporting opaque data as blob "sha256:5dd467fce50b56951185da365b5feee75409968cbab5767b9b59e325fb2ecbc0" 
DEBU[0000] Looking up image "quay.io/podman/hello" in local containers storage 
DEBU[0000] Normalized platform linux/amd64 to {amd64 linux  [] } 
DEBU[0000] Trying "quay.io/podman/hello:latest" ...     
DEBU[0000] parsed reference into "[overlay@/vdb/podman/graph+/vdb/podman/run:overlay.mountopt=nodev]@5dd467fce50b56951185da365b5feee75409968cbab5767b9b59e325fb2ecbc0" 
DEBU[0000] Found image "quay.io/podman/hello" as "quay.io/podman/hello:latest" in local containers storage 
DEBU[0000] Found image "quay.io/podman/hello" as "quay.io/podman/hello:latest" in local containers storage ([overlay@/vdb/podman/graph+/vdb/podman/run:overlay.mountopt=nodev]@5dd467fce50b56951185da365b5feee75409968cbab5767b9b59e325fb2ecbc0) 
DEBU[0000] exporting opaque data as blob "sha256:5dd467fce50b56951185da365b5feee75409968cbab5767b9b59e325fb2ecbc0" 
DEBU[0000] Inspecting image 5dd467fce50b56951185da365b5feee75409968cbab5767b9b59e325fb2ecbc0 
DEBU[0000] exporting opaque data as blob "sha256:5dd467fce50b56951185da365b5feee75409968cbab5767b9b59e325fb2ecbc0" 
DEBU[0000] exporting opaque data as blob "sha256:5dd467fce50b56951185da365b5feee75409968cbab5767b9b59e325fb2ecbc0" 
DEBU[0000] Inspecting image 5dd467fce50b56951185da365b5feee75409968cbab5767b9b59e325fb2ecbc0 
DEBU[0000] Inspecting image 5dd467fce50b56951185da365b5feee75409968cbab5767b9b59e325fb2ecbc0 
DEBU[0000] Inspecting image 5dd467fce50b56951185da365b5feee75409968cbab5767b9b59e325fb2ecbc0 
DEBU[0000] using systemd mode: false                    
DEBU[0000] setting container name hello                 
DEBU[0000] Loading seccomp profile from "/usr/share/containers/seccomp.json" 
INFO[0000] Sysctl net.ipv4.ping_group_range=0 0 ignored in containers.conf, since Network Namespace set to host 
DEBU[0000] Allocated lock 0 for container 1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9 
DEBU[0000] exporting opaque data as blob "sha256:5dd467fce50b56951185da365b5feee75409968cbab5767b9b59e325fb2ecbc0" 
DEBU[0000] Cached value indicated that idmapped mounts for overlay are not supported 
DEBU[0000] Check for idmapped mounts support            
DEBU[0000] Created container "1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9" 
DEBU[0000] Container "1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9" has work directory "/vdb/podman/graph/overlay-containers/1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9/userdata" 
DEBU[0000] Container "1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9" has run directory "/vdb/podman/run/overlay-containers/1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9/userdata" 
DEBU[0000] overlay: mount_data=lowerdir=/vdb/podman/graph/overlay/l/4IKG3FWFJQX7SDZVTC7AGHHWCA,upperdir=/vdb/podman/graph/overlay/e6d6e5ddb19989d6928a7d4166576064896ffc549d492f86d3c90e54d4a40a4e/diff,workdir=/vdb/podman/graph/overlay/e6d6e5ddb19989d6928a7d4166576064896ffc549d492f86d3c90e54d4a40a4e/work,nodev 
DEBU[0000] Mounted container "1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9" at "/vdb/podman/graph/overlay/e6d6e5ddb19989d6928a7d4166576064896ffc549d492f86d3c90e54d4a40a4e/merged" 
DEBU[0000] Created root filesystem for container 1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9 at /vdb/podman/graph/overlay/e6d6e5ddb19989d6928a7d4166576064896ffc549d492f86d3c90e54d4a40a4e/merged 
DEBU[0000] /etc/system-fips does not exist on host, not mounting FIPS mode subscription 
DEBU[0000] Setting Cgroups for container 1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9 to machine.slice:libpod:1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9 
DEBU[0000] reading hooks from /usr/share/containers/oci/hooks.d 
DEBU[0000] Workdir "/" resolved to host path "/vdb/podman/graph/overlay/e6d6e5ddb19989d6928a7d4166576064896ffc549d492f86d3c90e54d4a40a4e/merged" 
DEBU[0000] Created OCI spec for container 1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9 at /vdb/podman/graph/overlay-containers/1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9/userdata/config.json 
DEBU[0000] /usr/bin/conmon messages will be logged to syslog 
DEBU[0000] running conmon: /usr/bin/conmon               args="[--api-version 1 -c 1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9 -u 1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9 -r /usr/bin/runc -b /vdb/podman/graph/overlay-containers/1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9/userdata -p /vdb/podman/run/overlay-containers/1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9/userdata/pidfile -n hello --exit-dir /run/libpod/exits --persist-dir /run/libpod/persist/1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9 --full-attach -s -l journald --log-level debug --syslog -t --conmon-pidfile /vdb/podman/run/overlay-containers/1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /vdb/podman/graph --exit-command-arg --runroot --exit-command-arg /vdb/podman/run --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /run/libpod --exit-command-arg --network-config-dir --exit-command-arg  --exit-command-arg --network-backend --exit-command-arg netavark --exit-command-arg --volumepath --exit-command-arg /vdb/podman/graph/volumes --exit-command-arg --db-backend --exit-command-arg sqlite --exit-command-arg --transient-store=false --exit-command-arg --runtime --exit-command-arg runc --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --storage-opt --exit-command-arg overlay.mountopt=nodev --exit-command-arg --events-backend --exit-command-arg journald --exit-command-arg --syslog --exit-command-arg container --exit-command-arg cleanup --exit-command-arg 1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9]"
INFO[0000] Running conmon under slice machine.slice and unitName libpod-conmon-1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9.scope 
DEBU[0000] Received: -1                                 
DEBU[0000] Cleaning up container 1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9 
DEBU[0000] Network is already cleaned up, skipping...   
DEBU[0000] Unmounted container "1a241c38eaf8ca7820cccc8ae8e0f1cdfd8ff7e28bfca786f5c1a1f480db7ae9" 
DEBU[0000] ExitCode msg: "runc: time=\"2024-09-24t15:12:16+08:00\" level=error msg=\"container_linux.go:360: starting container process caused \\\"error adding seccomp filter rule for syscall bdflush: requested action matches default action of filter\\\"\"\ncontainer_linux.go:360: starting container process caused \"error adding seccomp filter rule for syscall bdflush: requested action matches default action of filter\": oci runtime error" 
Error: OCI runtime error: runc: time="2024-09-24T15:12:16+08:00" level=error msg="container_linux.go:360: starting container process caused \"error adding seccomp filter rule for syscall bdflush: requested action matches default action of filter\""
container_linux.go:360: starting container process caused "error adding seccomp filter rule for syscall bdflush: requested action matches default action of filter"
DEBU[0000] Shutting down engines     

### Describe the results you received

how to do

### Describe the results you expected

how to do

### podman info output

```yaml
[root@7ohx4720 ~]# podman info
host:
  arch: amd64
  buildahVersion: 1.36.0
  cgroupControllers:
  - cpuset
  - cpu
  - cpuacct
  - memory
  - devices
  - freezer
  - net_cls
  - blkio
  - perf_event
  - hugetlb
  - pids
  - net_prio
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.12-3.15.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: e21e7c85b7637e622f21c57675bf1154fc8b1866'
  cpuUtilization:
    idlePercent: 99.97
    systemPercent: 0.02
    userPercent: 0.01
  cpus: 8
  databaseBackend: sqlite
  distribution:
    distribution: centos
    version: "7"
  eventLogger: journald
  freeLocks: 2029
  hostname: 7ohx4720.vm
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 3.10.0-1160.el7.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 30343340032
  memTotal: 33566199808
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: Unknown
    package: podman-netavark-1.12.2-1.9.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.12.2
  ociRuntime:
    name: runc
    package: runc-1.0.0-70.rc10.el7_9.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: false
    path: /run/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.3.1-1.23.x86_64
    version: |-
      slirp4netns version 1.3.1
      commit: unknown
      libslirp: 4.8.0
      SLIRP_CONFIG_VERSION_MAX: 5
      libseccomp: 2.3.1
  swapFree: 0
  swapTotal: 0
  uptime: 361h 39m 35.00s (Approximately 15.04 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  docker.1ms.run:
    Blocked: false
    Insecure: false
    Location: docker.1ms.run
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: docker.1ms.run
    PullFromMirror: ""
  docker.ctxjj.com:9081:
    Blocked: false
    Insecure: false
    Location: docker.ctxjj.com:9081
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: docker.ctxjj.com:9081
    PullFromMirror: ""
  docker.m.daocloud.io:
    Blocked: false
    Insecure: false
    Location: docker.m.daocloud.io
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: docker.m.daocloud.io
    PullFromMirror: ""
  search:
  - docker.m.daocloud.io
  - docker.1ms.run
  - docker.ctxjj.com:9081
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /vdb/podman/graph
  graphRootAllocated: 53659832320
  graphRootUsed: 2651299840
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "false"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 1
  runRoot: /vdb/podman/run
  transientStore: false
  volumePath: /vdb/podman/graph/volumes
version:
  APIVersion: 5.1.2
  Built: 0
  BuiltTime: Thu Jan  1 08:00:00 1970
  GitCommit: ""
  GoVersion: go1.23.1
  Os: linux
  OsArch: linux/amd64
  Version: 5.1.2
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

No

### Additional environment details

5.1.2

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
We do not support such old distros upstream. In your case you likely need to modify the seccomp profile or most likely need to update the runc version (or use crun) as it looks super outdated.
