### ISSUE TITLE
CIFS and NFS are not installed in WSL image

### ISSUE THREAD

**Issue by ThePMO** [containers/podman#24079]
### Bug description

Since I haven't found anything regarding this in any documentation I assume this is a bug:
The WSL image for the podman machine does not contain mount.cifs and mount.nfs, they need to be installed manually (cifs-utils and nfs-utils).

### Operating system

Windows 10

### Installation Method

Installer from website/GitHub releases

### Version

1.12.0

**Comment by benoitf** [comment]
moving the issue to the podman repository where the podman machine issues are tracked

**Comment by Luap99** [comment]
Lets keep the discussion in one place. https://github.com/containers/podman-machine-wsl-os/issues/7
