### ISSUE TITLE
Podman container created in cgroupv2 is unable to start when host rebooted in cgroupv1

### ISSUE THREAD

**Issue by sourav-sharma796** [containers/podman#24107]
### Issue Description

We have found out an issue in podman application. When we create a podman container in a host with cgroupv2 hierarchy then it works normally without any issue but when we reboot our host with cgroupv1 hierarchy and tries to start that container then it does not get started and raise below given error :-

"Error: unable to start container "32358ee8c18a076c944f73294888df38d2cfbcf1f20e1bf4154b1ceb4fc17cdd": cgroup namespace is not supported with cgroup v1 and systemd mode"

Therefore, this error should not come whether the container is created in cgroupv1 or cgroupv2 container should start normally.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Check if host in cgroupv2, for cgroupv2 type will be cgroup2fs and for cgroupv1 type will be tmpfs
 stat -f /sys/fs/cgroup/

2.  Create the container
sudo podman create --name testnode-v2 --hostname testnode-v2 --entrypoint="/usr/sbin/init" --memory 8g --systemd true oraclelinux:8

3. Start the container
sudo podman start testnode-v2

4. Reboot the host in cgroupv1 hierarchy
sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0 systemd.legacy_systemd_cgroup_controller"

5. Start the container  testnode-v2 which was created in cgroupv2 hierarchy
[my_vm ~]$ sudo podman start testnode-v2
WARN[0000] Using cgroups-v1 which is deprecated in favor of cgroups-v2 with Podman v5 and will be removed in a future version. Set environment variable `PODMAN_IGNORE_CGROUPSV1_WARNING` to hide this warning.
Error: unable to start container "32358ee8c18a076c944f73294888df38d2cfbcf1f20e1bf4154b1ceb4fc17cdd": cgroup namespace is not supported with cgroup v1 and systemd mode

### Describe the results you received

Describe the results you received

### Describe the results you expected

Describe the results you expected

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.37.2
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.10-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: ""'
  cpuUtilization:
    idlePercent: 99.55
    systemPercent: 0.17
    userPercent: 0.28
  cpus: 2
  databaseBackend: sqlite
  distribution:
    distribution: ol
    variant: server
    version: "9.4"
  eventLogger: journald
  freeLocks: 2048
  hostname: my_vm
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.15.0-210.163.7.el9uek.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 12540911616
  memTotal: 16287358976
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.10.0-3.el9_4.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.10.0
    package: netavark-1.10.3-1.el9.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.10.3
  ociRuntime:
    name: crun
    package: crun-1.14.3-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.14.3
      commit: ""
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20231204.gb86afe3-1.el9.x86_64
    version: |
      pasta 0^20231204.gb86afe3-1.el9.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: false
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.3-1.el9.x86_64
    version: |-
      slirp4netns version 1.2.3
      commit: "'
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 24h 38m 1.00s (Approximately 1.00 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - container-registry.oracle.com
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphRootAllocated: 31608274944
  graphRootUsed: 14223237120
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 5.2.2
  Built: 1726464184
  BuiltTime: Mon Sep 16 05:23:04 2024
  GitCommit: ""
  GoVersion: go1.21.11 (Red Hat 1.21.11-1.module+el8.10.0+90357+32bea22c)
  Os: linux
  OsArch: linux/amd64
  Version: 5.2.2
```

### Podman in a container

Yes

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by giuseppe** [comment]
Podman uses the cgroup namespace by default when cgroup v2 is detected and that is part of the container configuration.

The cgroup namespace breaks systemd in a container on cgroup v1, so the alternative would be to ignore the setting by loosening the container configuration (dropping the namespace could leak information into the container that was not available before).  I am not sure this should be done automatically.

**Comment by rhatdan** [comment]
I agree, if you change the underlying cgroups, you need to recreate the containers, this is not something we will fix.  People should just move to cgroupV2 and be done with it.

**Comment by sushmbha** [comment]
Hi @rhatdan @giuseppe , is there a way to migrate containers which were created in cgroupv2, to a cgroupv1 system? Also, I think containers should work even if the underlying OS settings are changed. Is there a problem if the cgroup settings of the system is detected at container start, and the container is able to come up accordingly?  Why do the cgroup settings have to be persisted as part of the container state ?

**Comment by giuseppe** [comment]
> Hi @rhatdan @giuseppe , is there a way to migrate containers which were created in cgroupv2, to a cgroupv1 system? Also, I think containers should work even if the underlying OS settings are changed.

no, unfortunately you cannot update the namespaces used by a container.

> Is there a problem if the cgroup settings of the system is detected at container start, and the container is able to come up accordingly? Why do the cgroup settings have to be persisted as part of the container state ?

yes, I think it is a problem if we loosen the configuration.  It would work on cgroupv1 if the container was created with `--cgroupns=host` so to override the different default on cgroup v2

**Comment by sushmbha** [comment]
Do you consider portability as a requirement in the forward direction at least ? i.e Should containers created on a cgroupv1 system, work when the system is later booted in cgroupv2?  I would think that should be supported at least, if not the backward direction (v2->v1), do you agree ?

**Comment by rhatdan** [comment]
I don't think the upstream Podman team makes any support promise for this, but I agree it would be nice.
