### ISSUE TITLE
pull or pod create: Error creating cache file for layer "x": locating layer with ID "x": layer not known

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#24146]
Yet another "layer not known" flake seen in parallel CI testing:
```
# podman --noout pod create --name p-t181-wdhsgkec --infra-name infra_container_t181-wdhsgkec --infra-image quay.io/libpod/k8s-pause:3.5
time="2024-09-25T14:16:22-05:00" level=warning msg="Error creating cache file for layer \"e8e4716d9f3cacdbc440b0e7a9fd9ccd0103cc0e8e6910c6637339cf75067a37\": locating layer with ID \"e8e4716d9f3cacdbc440b0e7a9fd9ccd0103cc0e8e6910c6637339cf75067a37\": layer not known"
```
or on pull:
```
# podman pull quay.io/libpod/alpine:latest
Trying to pull quay.io/libpod/alpine:latest...
Getting image source signatures
Copying blob sha256:9d16cba9fb961d1aafec9542f2bf7cb64acfc55245f9e4eb5abecd4cdc38d749
time="2024-09-27T09:08:02-05:00" level=warning msg="Error creating cache file for layer \"36c060c90a06b65bef01ce7534f40e663a03528dbc504920784ddbd97c7e6588\": locating layer with ID \"36c060c90a06b65bef01ce7534f40e663a03528dbc504920784ddbd97c7e6588\": layer not known"
Copying config sha256:961769676411f082461f9ef46626dd7a2d1e2b2a38e6a44364bcbecf51e66dd4
Writing manifest to image destination
961769676411f082461f9ef46626dd7a2d1e2b2a38e6a44364bcbecf51e66dd4
```
Both are warnings, not errors. The command succeeds, but test fails because of undesired warnings.

* rawhide : sys podman rawhide root host sqlite
  * PR #24073
    * [09-25 15:20](https://api.cirrus-ci.com/v1/artifact/task/5534559138217984/html/sys-podman-rawhide-root-host-sqlite.log.html#t--00181p) in [sys] |200| podman pod create should fail when infra-name is already in use
  * PR #24069
    * [09-25 10:23](https://api.cirrus-ci.com/v1/artifact/task/6431848337768448/html/sys-podman-rawhide-root-host-sqlite.log.html#t--00181p) in [sys] |200| podman pod create should fail when infra-name is already in use
  * PR #23275
    * [10-02 18:28](https://api.cirrus-ci.com/v1/artifact/task/6178046237999104/html/sys-podman-rawhide-root-host-sqlite.log.html#t--00181p) in [sys] |200| podman pod create should fail when infra-name is already in use
    * [09-27 10:09](https://api.cirrus-ci.com/v1/artifact/task/5606996982890496/html/sys-podman-rawhide-root-host-sqlite.log.html#t--00414p) in [sys] |700| podman play with image volume pull policies
    * [09-19 18:39](https://api.cirrus-ci.com/v1/artifact/task/6313176948539392/html/sys-podman-rawhide-root-host-sqlite.log.html#t--00407p) in [sys] |700| podman play with image volume pull policies

| x | x | x | x | x | x |
| ---: | ---: | ---: | ---: | ---: | ---: |
| sys(5) | podman(5) | rawhide(5) | root(5) | host(5) | sqlite(5) |

**Comment by Luap99** [comment]
I assume this is fixed on main now, reopen if you still see it.
