### ISSUE TITLE
Cannot access podman in WSL with Arch

### ISSUE THREAD

**Issue by EnderWolf50** [containers/podman#24174]
### Bug description

I tried to follow the steps in the [documentation](https://podman-desktop.io/docs/podman/accessing-podman-from-another-wsl-instance), but whenever I try to use podman command (with podman machine in rootful mode), it shows me that I don't have enough permissions:
![image](https://github.com/containers/podman/assets/14370053/2b54bb78-3504-4aab-83b7-ba8bf86a3a84)

It seems like Arch cannot recognize "group 10":
![image](https://github.com/containers/podman/assets/14370053/3ce0c854-4661-4e4f-8e41-a6f9639329ee)

### Operating system

Windows 11, WSL with Arch

### Installation Method

None

### Version

1.10.2

**Comment by Luap99** [comment]
I don't know where the group 10 is supposed to come from? The service as root requires root to access normally. You can check the permission on the actual real socket /run/podman/podman.sock. Can you try to connect with sudo?
