### ISSUE TITLE
[Quadlet] Implicit network online dependencies cannot be removed

### ISSUE THREAD

**Issue by lambinoo** [containers/podman#24193]
### Issue Description

As explained in the quadlet man page, we should be able to remove the `network-online.target` implicit dependency by just overriding it with `After=`. But this doesn't really seem to work at all. The network-online dependencies seem to stick even by adding a `After=` in a `[Unit]` section.

In the `systemd.unit` man page itself, it even seems to say that you cannot reset "dependencies" (After=, Wants=) into an empty list.
> Dependencies (After=, etc.) cannot be reset to an empty list, so dependencies can only be added in
> drop-ins. If you want to remove dependencies, you have to override the entire unit.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create a sleep.container file
    ```
   [Unit]
   After=
   Wants=

   [Container]
   Image=docker://docker.io/ubuntu:jammy
   Exec=sleep infinity
    ```

### Describe the results you received

`systemctl cat sleep.service` will show the following:
```
# /run/systemd/generator/sleep.service
# Automatically generated by /usr/lib/systemd/system-generators/podman-system-generator
[Unit]
Wants=network-online.target
After=network-online.target
After=
Wants=
[...]
```

But looking at the effective dependencies of the unit, we can see the following:
```
# systemctl show sleep.service -p After -p Wants
Wants=network-online.target
After=network-online.target sysinit.target basic.target systemd-journald.socket -.mount system.slice
```

### Describe the results you expected

That we do not see the network-online.target default dependencies added by quadlet.

### podman info output

Running podman version 5.2.2 on Centos 9 stream on an amd64 machine.

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by lambinoo** [comment]
I was under the same impression, but this was buried quite deep in the man pages..

Something like `QuadletDefaultDependencies=` would make sense, to stay close to how systemd does things with `DefaultDependencies=`

**Comment by ygalblum** [comment]
I agree. @lambinoo would like to contribute this?

**Comment by lambinoo** [comment]
@ygalblum Sure, got the PR ready!
