### ISSUE TITLE
Volumes auto-backup

### ISSUE THREAD

**Issue by CyberFox001** [containers/podman#24201]
### Feature request description

Automate the backup of volumes data in a similar way of how auto-update work. Each backup is done regularly and the container(s) that use the volumes is (are) stopped before the backup and started after.

### Suggestion A: At volume level

- When a user create a volume to be automatically backup, he/she mark it with a label `io.containers.autobackup=periodicity`
-  `periodicity` can be: `hourly`, `daily`, `weekly`, etc
- When the command `podman auto-backup` is run, each container using a marked volume is stopped, the backup of the volume data is done to a destination directory then the stopped containers a restarted
- The destination directory have a default value, but can be defined with the label `io.containers.backupdir=path`, where path is a host path
- The structure of the destination directory is `volume_name/date_volume_name.tar`, where `date` are in formate `year-month-day-hour-minute`
- A systemd `podman-auto-backup.service` and `podman-auto-backup.timer` are available

### Suggestion B: At container level

Work the same way as suggestion A, except
- The user mark the container with volumes to backup, not the volumes themselves
- When the command `podman auto-backup` is run, each marked containers are stopped, all their volumes data are saved to a destination directory then the stopped containers a restarted
- The structure of the destination directory is `container_name/volume_name/date_volume_name.tar`, where `date` are in formate `year-month-day-hour-minute`

### Backup restoration

- A backup can be restored with the actual command `podman volume import`
- It would be nice to introduce a command that can restore all volumes data of one container on a given date and manage it stop before and restart after
- It would be also nice to introduce an option to `podman run` or `podman volume create` to restore data after the volume creation or before the container run

### Notes

- To complete suggestion B, maybe a user could mark a pod instead of a container: In this case, it the volumes used by the pod's containers that are backup
- Before a backup, when a container is stopped, each containers that require this container (with option `--requires`) are stopped before
- After a backup, restart every stopped container following the `--requires` option

### Have you considered any alternatives?

- I didn't found a software that already does that
- I have considered write a simple python script that implement the base
- But if it is included in podman, my python script would be not useful

**Comment by Luap99** [comment]
This sounds way out of scope for podman, backups in general can be done is so many ways that there is not one size fits it all solution.
Trying to implement something like this in podman will just lead to endless churn and maintenance headaches because every users wants something else.

In particular doing full backups every time is just a huge waste of space and then you need to worry about running our of disk and some kind of retention policy when we delete old backups, etc...

**Comment by CyberFox001** [comment]
The goal is not to provide every possible ways of doing backup. Only a simple one.

Like updating a container could be done in so many ways, but `podman auto-update` provide a simple one.

We can already use the commands `podman volume export` to manually get the data of a volume. But we still need to stop the container who use this volume first. This feature request suggest to provide a way of doing it automatically, similarly to auto-update.

**Comment by rhatdan** [comment]
Seems like this could be written in a script to pause or stop a container; export the volume and restart the container.  Not something needed to be done in core Podman.

**Comment by Luap99** [comment]
>  Only a simple one.

Well this is not how it works in practise, people will always ask for more and more. And this isn't super simple either.

Overall backups are super specialized depending on your work loads/environments, I do not think it is reasonable to try to abstract one specific way into podman.
