### ISSUE TITLE
podman auto-update in conflict with pods

### ISSUE THREAD

**Issue by michelmetran** [containers/podman#24256]
### Issue Description

I'm using `podman auto-update` and I'm getting the error
> auto-updating container "febf6...": no PODMAN_SYSTEMD_UNIT label found.

This only happens if I create the service with the option for the container to be inside a pod.

When I remove the pod option, auto-update works without any major problems.

Could someone help me understand the problem?

<br>

I'm using `podman version 4.9.4-rhel`

<br>

------

### Steps to reproduce the issue

To reproduce the error, I followed these steps:
````shell
# Create Pod
podman pod create \
-p 3050:3051 \
-p 5000:5001 \
--name pod-nginx

# -------------------------------
# CHOOSE ONE TO RUN
# Create container with Pod = ERROR
podman run \
-d \
--restart=always \
--pod pod-nginx \
-v uptime-kuma:/app/data \
--name my-kuma \
--label "io.containers.autoupdate=local" \
docker.io/louislam/uptime-kuma:1

# Create container without Pod = NO ERROR
podman run \
-d \
--restart=always \
-v uptime-kuma:/app/data \
--name my-kuma \
--label "io.containers.autoupdate=local" \
docker.io/louislam/uptime-kuma:1
# -------------------------------

# Create Service
podman generate systemd --new my-kuma  > ~/.config/systemd/user/my-kuma.service
systemctl --user daemon-reload

# Drop Docker Instance
podman rm -f my-kuma

# Start Service
systemctl --user enable my-kuma.service
systemctl --user restart my-kuma.service
systemctl --user status my-kuma.service

# Update
podman auto-update
````

<br>

To clean the tests above...

````shell
systemctl --user stop my-kuma.service
systemctl --user daemon-reload

rm ~/.config/systemd/user/my-kuma.service
podman pod rm pod-nginx -f
````

<br>

------

### Describe the results you received

When I try the keep my podman updated inside a pod, I recive the error:
`````shell
podman auto-update
            UNIT                  CONTAINER                    IMAGE                          POLICY      UPDATED
            my-kuma.service  f6bcc5b898d6 (my-kuma)  docker.io/louislam/uptime-kuma:1   local       false
Error: auto-updating container "febf6585f37d48871efb94803c3e49baa0d1a0fb1bcfaa3c0e93d972ae629913": no PODMAN_SYSTEMD_UNIT label found
`````

When I create a service (to update) without a pod (outside a pod) a receive no erros...
````shell
podman auto-update
            UNIT                  CONTAINER                    IMAGE                             POLICY      UPDATED
            my-kuma.service       6a9d04ada52d (my-kuma)       docker.io/louislam/uptime-kuma:1  local       false
````

<br>

------

### Describe the results you expected

I would like to know if there are any restrictions on using both services together: `podman auto-update` plus pods.

### podman info output

host:
  arch: amd64
  buildahVersion: 1.33.8
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.10-1.el9.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: fb8c4bf50dbc044a338137871b096eea8041a1fa'
  cpuUtilization:
    idlePercent: 99.7
    systemPercent: 0.05
    userPercent: 0.25
  cpus: 4
  databaseBackend: boltdb
  distribution:
    distribution: rhel
    version: "9.4"
  eventLogger: journald
  freeLocks: 1971
  hostname: (i hide this)
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.14.0-427.33.1.el9_4.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 1417818112
  memTotal: 3798859776
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.10.0-3.el9_4.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.10.0
    package: netavark-1.10.3-1.el9.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.10.3
  ociRuntime:
    name: crun
    package: crun-1.14.3-1.el9.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.14.3
      commit: 1961d211ba98f532ea52d2e80f4c20359f241a98
      rundir: /run/user/1001/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20231204.gb86afe3-1.el9.x86_64
    version: |
      pasta 0^20231204.gb86afe3-1.el9.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: false
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.3-1.el9.x86_64
    version: |-
      slirp4netns version 1.2.3
      commit: c22fde291bb35b354e6ca44d13be181c76a0a432
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 4099637248
  swapTotal: 4198494208
  uptime: 238h 17m 18.00s (Approximately 9.92 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/michelsilva/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 3
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/michelsilva/.local/share/containers/storage
  graphRootAllocated: 33273937920
  graphRootUsed: 9625772032
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 13
  runRoot: /run/user/1001/containers
  transientStore: false
  volumePath: /home/michelsilva/.local/share/containers/storage/volumes
version:
  APIVersion: 4.9.4-rhel
  Built: 1719829634
  BuiltTime: Mon Jul  1 07:27:14 2024
  GitCommit: ""
  GoVersion: go1.21.11 (Red Hat 1.21.11-1.el9_4)
  Os: linux
  OsArch: linux/amd64
  Version: 4.9.4-rhel

<br>

------

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

<br>

------

### Additional information

I'm trying to maintain services running in podmans, such as flask applications (python), FastAPI applications (python), static sites and uptime kuma, for example, in isolated podmans. Finally, I want an NGINX podman to expose all the services to the internet.

I want the pod to "group" all these isolated podmans, however, I would like to be able to keep them updated using podman auto-update.

**Comment by Luap99** [comment]
You have to run the entire pod under systemd not just a single container, i.e. run `podman generate systemd` wiyth the pod name and the `--files` option to generate the files for the pod and container.
