### ISSUE TITLE
podman compose should support `links:` without deprecated `--link`?

### ISSUE THREAD

**Issue by stacyharper** [containers/podman#24254]
### Issue Description

At the moment, any compose file that use a `links` service node fails with `Error response from daemon: bad parameter: link is not supported`.

While the `link` feature is deprecated by Docker, the `links` features from the compose file spec is not.

`podman compose` should support the compose `links` feature using something else (`podman connect`?) 

### Steps to reproduce the issue

Steps to reproduce the issue
1. use a docker compose file with a `links:`
2. podman compose up -d

### Describe the results you received

It fails with `Error response from daemon: bad parameter: link is not supported`

### Describe the results you expected

It works, and connect the nodes using the provided name/alias.

### podman info output

$ podman --version
podman version 5.2.4
$ podman compose --version
Docker Compose version v2.29.7

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

I run Podman 5.2.4, with the package podman-docker, on Alpine Linux Edge.

**Comment by Luap99** [comment]
We will not support --link, it has been deprecated for years in docker and we have no plans of adding support for it. It doesn't matter what compose says about that. `podman compose` is just a wrapper for calling docker-compose or podman-compose we have no compose logic ourselves and you seems to be using docker-compose which just used the detracted --link option from docker
