### ISSUE TITLE
Potential for buggy slice behavior

### ISSUE THREAD

**Issue by zackattackz** [containers/podman#24267]
I noticed that this code could potentially cause a bug that would probably be annoying to figure out. I don't believe that this bug could be triggered any way currently, but it has the potential to happen in the future. So I wanted to share this and suggest a fix before it became an issue.

The issue could happen in the `transferRootless` function in `pkg/domain/infra/abi/images.go`
https://github.com/containers/podman/blob/3fbae8e28e38ab4d06ef4250a8dfc43eaac8bd14/pkg/domain/infra/abi/images.go#L804-L808

Specifically, because `saveCommand` and `loadCommand` are pointing to the same slice `parentFlags`. If this slice was passed in with a capacity > it's length it could lead to unexpected behavior in the subsequent appends

Currently, it works fine because if length == capacity (which it seems to always be the case currently) then the appends will end up creating new backing arrays anyways.

See this playground example of a similar situation, and how the second example does not produce the same result as the first example:
https://go.dev/play/p/iItEPu4hQ0p

The suggested fix would be to call `make` to create new slices for `saveCommand` and `loadCommand`. This way they won't share the same backing array, and would avoid the problem. Pretty much like what `transferRootful` does:
https://github.com/containers/podman/blob/3fbae8e28e38ab4d06ef4250a8dfc43eaac8bd14/pkg/domain/infra/abi/images.go#L845-L856

I can submit a PR for this if you think it would be valuable.

**Comment by giuseppe** [comment]
> I noticed that this code could potentially cause a bug that would probably be annoying to figure out. I don't believe that this bug could be triggered any way currently, but it has the potential to happen in the future. So I wanted to share this and suggest a fix before it became an issue.
> 
> The issue could happen in the `transferRootless` function in `pkg/domain/infra/abi/images.go`
> 
> [podman/pkg/domain/infra/abi/images.go](https://github.com/containers/podman/blob/3fbae8e28e38ab4d06ef4250a8dfc43eaac8bd14/pkg/domain/infra/abi/images.go#L804-L808)
> 
> Lines 804 to 808 in [3fbae8e](/containers/podman/commit/3fbae8e28e38ab4d06ef4250a8dfc43eaac8bd14)
> 
>  func transferRootless(source entities.ImageScpOptions, dest entities.ImageScpOptions, podman string, parentFlags []string) error { 
>  	var cmdSave *exec.Cmd 
>  	saveCommand, loadCommand := parentFlags, parentFlags 
>  	saveCommand = append(saveCommand, []string{"save"}...) 
>  	loadCommand = append(loadCommand, []string{"load"}...) 
> Specifically, because `saveCommand` and `loadCommand` are pointing to the same slice `parentFlags`. If this slice was passed in with a capacity > it's length it could lead to unexpected behavior in the subsequent appends
> 
> Currently, it works fine because if length == capacity (which it seems to always be the case currently) then the appends will end up creating new backing arrays anyways.
> 
> See this playground example of a similar situation, and how the second example does not produce the same result as the first example: https://go.dev/play/p/iItEPu4hQ0p
> 
> The suggested fix would be to call `make` to create new slices for `saveCommand` and `loadCommand`. This way they won't share the same backing array, and would avoid the problem. Pretty much like what `transferRootful` does:
> 
> [podman/pkg/domain/infra/abi/images.go](https://github.com/containers/podman/blob/3fbae8e28e38ab4d06ef4250a8dfc43eaac8bd14/pkg/domain/infra/abi/images.go#L845-L856)
> 
> Lines 845 to 856 in [3fbae8e](/containers/podman/commit/3fbae8e28e38ab4d06ef4250a8dfc43eaac8bd14)
> 
>  func transferRootful(source entities.ImageScpOptions, dest entities.ImageScpOptions, podman string, parentFlags []string) error { 
>  	basicCommand := make([]string, 0, len(parentFlags)+1) 
>  	basicCommand = append(basicCommand, podman) 
>  	basicCommand = append(basicCommand, parentFlags...) 
>   
>  	saveCommand := make([]string, 0, len(basicCommand)+4) 
>  	saveCommand = append(saveCommand, basicCommand...) 
>  	saveCommand = append(saveCommand, "save") 
>   
>  	loadCommand := make([]string, 0, len(basicCommand)+3) 
>  	loadCommand = append(loadCommand, basicCommand...) 
>  	loadCommand = append(loadCommand, "load") 
> I can submit a PR for this if you think it would be valuable.

yes, please open a PR to address the issue you've found

**Comment by Luap99** [comment]
FYI, the make new slice append hack to clones should really no longer be used for new code, instead one should use `slices.Clone()` which is much easier to use.
