### ISSUE TITLE
Document incorrect about mouting /Users into the VM as /mnt/Users

### ISSUE THREAD

**Issue by bbbush** [containers/podman#24281]
### Issue Description

The document mentioned

> Initialize the default Podman machine with the host directory /Users mounted into the VM at /mnt/Users.
> ```
> $ podman machine init -v /Users:/mnt/Users
> ```

https://docs.podman.io/en/latest/markdown/podman-machine-init.1.html

But it didn't seem to work. I had used Podman on MBP for a long time but only occasionally. I don't know when the issue started.

Podman version: 5.2.4 from brew

### Steps to reproduce the issue

Steps to reproduce the issue
1. stop and rm default machine, then init a new machine and start
2. login to the machine with "podman machine ssh"
3. check service status

### Describe the results you received

```
$ podman machine init -v /Users:/mnt/Users
Looking up Podman Machine image at quay.io/podman/machine-os:5.2 to create VM

$ podman machine start

$ podman machine ssh
Connecting to vm podman-machine-default. To close connection, use `~.` or `exit`
Fedora CoreOS 40.20240920.2.0
Tracker: https://github.com/coreos/fedora-coreos-tracker
Discuss: https://discussion.fedoraproject.org/tag/coreos

[systemd]
Failed Units: 1
  mnt-Users.mount


core@localhost:~$ systemctl status mnt-Users.mount
× mnt-Users.mount - /mnt/Users
     Loaded: loaded (/etc/systemd/system/mnt-Users.mount; enabled; preset: enabled)
     Active: failed (Result: resources)
      Where: /mnt/Users
       What: 3b2f82ca701c87f79e1a0ba8981dfa3ded24

Oct 15 11:59:16 localhost systemd[1]: mnt-Users.mount: Mount path /mnt/Users is not canonical (contains a symlink).
Oct 15 11:59:16 localhost systemd[1]: mnt-Users.mount: Failed with result 'resources'.
Oct 15 11:59:16 localhost systemd[1]: Failed to mount mnt-Users.mount - /mnt/Users.
```

### Describe the results you expected

No error.

### podman info output

host:
  arch: arm64
  buildahVersion: 1.37.4
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.12-2.fc40.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: '
  cpuUtilization:
    idlePercent: 99.67
    systemPercent: 0.2
    userPercent: 0.13
  cpus: 5
  databaseBackend: sqlite
  distribution:
    distribution: fedora
    variant: coreos
    version: "40"
  eventLogger: journald
  freeLocks: 2048
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 503
      size: 1
    - container_id: 1
      host_id: 100000
      size: 1000000
  kernel: 6.10.10-200.fc40.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 1530310656
  memTotal: 2044022784
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.12.1-1.20241007140227477357.main.38.g08fbf82.fc40.aarch64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.13.0-dev
    package: netavark-1.12.1-1.20241007131025236895.main.62.g47632d8.fc40.aarch64
    path: /usr/libexec/podman/netavark
    version: netavark 1.13.0-dev
  ociRuntime:
    name: crun
    package: crun-1.17-1.20241007140634150540.main.7.g7c194cb.fc40.aarch64
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: 4f2c23486977b381fd9461150d2c0038b7d918b3
      rundir: /run/user/503/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20240906.g6b38f07-1.fc40.aarch64
    version: |
      pasta 0^20240906.g6b38f07-1.fc40.aarch64-pasta
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/503/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.2-2.fc40.aarch64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.5
  swapFree: 0
  swapTotal: 0
  uptime: 0h 7m 58.00s
  variant: v8
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /var/home/core/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/home/core/.local/share/containers/storage
  graphRootAllocated: 106769133568
  graphRootUsed: 4573306880
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 0
  runRoot: /run/user/503/containers
  transientStore: false
  volumePath: /var/home/core/.local/share/containers/storage/volumes
version:
  APIVersion: 5.2.4
  Built: 1728259200
  BuiltTime: Sun Oct  6 19:00:00 2024
  GitCommit: ""
  GoVersion: go1.22.7
  Os: linux
  OsArch: linux/arm64
  Version: 5.2.4

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

The document might need updating? Because $HOME is mounted by default (the document says so).

> Default volume mounts are defined in containers.conf. Unless changed, the default values is $HOME:$HOME

I assume `/mnt/Users` might be a workaround when CoreOS didn't allow creating folders under `/` but it seems `/Users` is created now.

**Comment by Luap99** [comment]
Yeah it looks like /mnt is now a symlink to /var/mnt and systemd doesn't seem to be happy about using the symlink as target.

**Comment by bbbush** [comment]
Because "$HOME is mounted by default" I think the document should avoid
that example.
