### ISSUE TITLE
zstd: podman save: error writing blob: archive/tar: write too long

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#24283]
`podman save` barfs when dealing with an image that has been saved with `zstd:chunked`:

```console
$ bin/podman pull quay.io/libpod/testimage:20241010
Trying to pull quay.io/libpod/testimage:20241010...
Getting image source signatures
Copying blob a3ed95caeb02 skipped: already exists  
Copying blob d005489f1e59 done  5.2MiB / 5.2MiB (skipped: 659.0b = 0.01%)
Copying config 263622a183 done   | 
Writing manifest to image destination
263622a183c94c2433a43be5464a954b9c4e5b0a77cb177f6fe60dacfff66f80

$ bin/podman save -o /tmp/foo.tar quay.io/libpod/testimage:20241010
Copying blob fcaea6d86226 done   | 
Copying blob 5f70bf18a086 done   | 
Error: writing blob: archive/tar: write too long
```
See also #24280

It is possible that this is fixed by https://github.com/containers/storage/pull/2130. I have not yet tested.

**Comment by edsantiago** [comment]
I just tested on my laptop, and it looks like your PR fixes it. I'll repush my test-zstd PR and see.

**Comment by mtrmac** [comment]
Confirming that in manual testing, https://github.com/containers/storage/pull/2130 fixes this.

**Comment by edsantiago** [comment]
Vendored into podman in #24326, and this particular bug no longer manifests.
