### ISSUE TITLE
health-startup-cmd leaks a failed systemd unit

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#24351]
Setup: first make sure you have an empty failed list:
```console
$ systemctl --user list-units --failed
  UNIT LOAD ACTIVE SUB DESCRIPTION

0 loaded units listed.
```
If you've ever run bats tests on your laptop, you may see a long list. Kill it with `systemctl --user reset-failed`. To the best of my knowledge there's no harm in nuking these. I really don't know why these linger.

Now:
```console
$ run -d --name foo --health-cmd /home/podman/healthcheck --health-startup-cmd /home/podman/healthcheck quay.io/libpod/testimage:20241011 /home/podman/pause
e506e3994ba7bd5df664c8f0b71da085609be70d122df002646aa58193aabb2c

$ systemctl --user list-units --failed
  UNIT                                                                                             LOAD   ACTIVE SUB    DESCRIPTION        >
● e506e3994ba7bd5df664c8f0b71da085609be70d122df002646aa58193aabb2c-startup-61bf67e6fec5d89.service loaded failed failed /home/esm/src/.....>

Legend: LOAD   → Reflects whether the unit definition was properly loaded.
        ACTIVE → The high-level unit activation state, i.e. generalization of SUB.
        SUB    → The low-level unit activation state, values depend on unit type.

1 loaded units listed.
```
This failed unit will now linger until reboot or until `reset-failed`.

**Comment by Luap99** [comment]
Yes when we stop/remove the units we should definitely call `reset-failed` on them to clear the state, there is no need that should persist

**Comment by Luap99** [comment]
Actually it seems we are already be doing this https://github.com/containers/podman/pull/12697 so there is likely more to it.

**Comment by Luap99** [comment]
Ok interesting, it works with 5.2. I broke this recently https://github.com/containers/podman/commit/0bbef4b830aedcd8a5c8d463e7fd0dc84d95c05d
