### ISSUE TITLE
Add pdf to .readthedocs.yml?

### ISSUE THREAD

**Issue by ylluminate** [containers/podman#24354]
### Feature request description

It would be nice to add `- pdf` format to `.readthedocs.yml` for available document types for offline viewing of Podman documentation.

See:
- https://docs.readthedocs.io/en/stable/downloadable-documentation.html
- https://github.com/jax-ml/jax/pull/9869/files

 

### Suggest potential solution

Facilitates offline reading and other uses of documentation.

**Comment by Luap99** [comment]
Sure open a PR. AFAIK this used to just work and you could select other version on the docs site by default but I guess that got lost when it was migrated to the new config file?

**Comment by Luap99** [comment]
Interestingly I just looked at the epub and this seems to have all the man pages in there
