### ISSUE TITLE
errors while running container mount/unmount

### ISSUE THREAD

**Issue by paridee** [containers/podman#24367]
### Issue Description

Cannot run any container using podman run on my RHEL servers after a system update getting errors about mount/unmount and aardvark entries 

### Steps to reproduce the issue

Container not starting with error output

`[jupyter@c2eatrej2 bin]$ podman run -d --net tulip-net --ip=10.89.0.5 --log-driver=journald -p 8080:8080 --name=minio-log-collector localhost/orep/orep-minio-logger
ERRO[0000] Unmounting /opt/data/podman/containers/storage/overlay/57c6860c94e6d1cba576554539c8185b8033b9dc140669147119c6b85153cca9/merged: invalid argument
ERRO[0000] failed to move the rootless netns slirp4netns process to the systemd user.slice: dbus: couldn't determine address of session bus
Failed to create bus connection: No such file or directory
ERRO[0000] Unable to clean up network for container fe47270a269ec49347f005b6eb9f5c76d265b9a248febe2fb3ae03eca50645b8: "tearing down network namespace configuration for container fe47270a269ec49347f005b6eb9f5c76d265b9a248febe2fb3ae03eca50645b8: netavark: remove aardvark entries: failed to get aardvark pid: IO error: No such file or directory (os error 2)"
Error: mounting storage for container fe47270a269ec49347f005b6eb9f5c76d265b9a248febe2fb3ae03eca50645b8: creating overlay mount to /opt/data/podman/containers/storage/overlay/57c6860c94e6d1cba576554539c8185b8033b9dc140669147119c6b85153cca9/merged, mount_data="lowerdir=/opt/data/podman/containers/storage/overlay/l/EFQN4FI3DF2HS42QIWMZ7DUDXG:/opt/data/podman/containers/storage/overlay/l/HSEPTJSBWLHUB2HUPW63FLLAHT:/opt/data/podman/containers/storage/overlay/l/7C5IP425C6YW25Q3AMKGDNXR4G:/opt/data/podman/containers/storage/overlay/l/KZA33VWEP2EWO6ICNHHSS2GLTV:/opt/data/podman/containers/storage/overlay/l/YAH4JHI4X4M4GQXD6XX2R3HYYT:/opt/data/podman/containers/storage/overlay/l/4AWLHCDGFJYG4FRHXCPO7P6D5C:/opt/data/podman/containers/storage/overlay/l/VJZ245SLIFFVIDJO4KLI2SMUBQ:/opt/data/podman/containers/storage/overlay/l/RNOS7SRQLYO6KQLNTZRA2JH6WW:/opt/data/podman/containers/storage/overlay/l/CICIYOXDI6LZR7OJUA6KZ6EWV6:/opt/data/podman/containers/storage/overlay/l/XKKHHWBEJZNSWQMEK7V66UUWTU:/opt/data/podman/containers/storage/overlay/l/Y2LAAXOMHK54NSHOJHC6QCO4DO,upperdir=/opt/data/podman/containers/storage/overlay/57c6860c94e6d1cba576554539c8185b8033b9dc140669147119c6b85153cca9/diff,workdir=/opt/data/podman/containers/storage/overlay/57c6860c94e6d1cba576554539c8185b8033b9dc140669147119c6b85153cca9/work,nodev, metacopy=on,userxattr,context=\"system_u:object_r:container_file_t:s0:c388,c826\"": invalid argument`

### Describe the results you received

Container not starting with error output

`[jupyter@c2eatrej2 bin]$ podman run -d --net tulip-net --ip=10.89.0.5 --log-driver=journald -p 8080:8080 --name=minio-log-collector localhost/orep/orep-minio-logger
ERRO[0000] Unmounting /opt/data/podman/containers/storage/overlay/57c6860c94e6d1cba576554539c8185b8033b9dc140669147119c6b85153cca9/merged: invalid argument
ERRO[0000] failed to move the rootless netns slirp4netns process to the systemd user.slice: dbus: couldn't determine address of session bus
Failed to create bus connection: No such file or directory
ERRO[0000] Unable to clean up network for container fe47270a269ec49347f005b6eb9f5c76d265b9a248febe2fb3ae03eca50645b8: "tearing down network namespace configuration for container fe47270a269ec49347f005b6eb9f5c76d265b9a248febe2fb3ae03eca50645b8: netavark: remove aardvark entries: failed to get aardvark pid: IO error: No such file or directory (os error 2)"
Error: mounting storage for container fe47270a269ec49347f005b6eb9f5c76d265b9a248febe2fb3ae03eca50645b8: creating overlay mount to /opt/data/podman/containers/storage/overlay/57c6860c94e6d1cba576554539c8185b8033b9dc140669147119c6b85153cca9/merged, mount_data="lowerdir=/opt/data/podman/containers/storage/overlay/l/EFQN4FI3DF2HS42QIWMZ7DUDXG:/opt/data/podman/containers/storage/overlay/l/HSEPTJSBWLHUB2HUPW63FLLAHT:/opt/data/podman/containers/storage/overlay/l/7C5IP425C6YW25Q3AMKGDNXR4G:/opt/data/podman/containers/storage/overlay/l/KZA33VWEP2EWO6ICNHHSS2GLTV:/opt/data/podman/containers/storage/overlay/l/YAH4JHI4X4M4GQXD6XX2R3HYYT:/opt/data/podman/containers/storage/overlay/l/4AWLHCDGFJYG4FRHXCPO7P6D5C:/opt/data/podman/containers/storage/overlay/l/VJZ245SLIFFVIDJO4KLI2SMUBQ:/opt/data/podman/containers/storage/overlay/l/RNOS7SRQLYO6KQLNTZRA2JH6WW:/opt/data/podman/containers/storage/overlay/l/CICIYOXDI6LZR7OJUA6KZ6EWV6:/opt/data/podman/containers/storage/overlay/l/XKKHHWBEJZNSWQMEK7V66UUWTU:/opt/data/podman/containers/storage/overlay/l/Y2LAAXOMHK54NSHOJHC6QCO4DO,upperdir=/opt/data/podman/containers/storage/overlay/57c6860c94e6d1cba576554539c8185b8033b9dc140669147119c6b85153cca9/diff,workdir=/opt/data/podman/containers/storage/overlay/57c6860c94e6d1cba576554539c8185b8033b9dc140669147119c6b85153cca9/work,nodev, metacopy=on,userxattr,context=\"system_u:object_r:container_file_t:s0:c388,c826\"": invalid argument`

### Describe the results you expected

Contained started

### podman info output

`
host:
  arch: amd64
  buildahVersion: 1.33.8
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.10-1.module+el8.10.0+22346+28c02849.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: b01a5d9cd2305ae83e60f5fa8ba584856d913bc6'
  cpuUtilization:
    idlePercent: 94.27
    systemPercent: 2.72
    userPercent: 3.01
  cpus: 2
  databaseBackend: sqlite
  distribution:
    distribution: rhel
    version: "8.10"
  eventLogger: file
  freeLocks: 2044
  hostname: XXXXXXXXXXXXXXX
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 100843
      size: 1
    - container_id: 1
      host_id: 10000
      size: 69999
    uidmap:
    - container_id: 0
      host_id: 100841
      size: 1
    - container_id: 1
      host_id: 10000
      size: 69999
  kernel: 4.18.0-553.16.1.el8_10.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 2512322560
  memTotal: 8071614464
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.10.1-2.module+el8.10.0+22346+28c02849.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.10.1-rhel
    package: netavark-1.10.3-1.module+el8.10.0+22346+28c02849.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.10.3
  ociRuntime:
    name: runc
    package: runc-1.1.12-5.module+el8.10.0+22346+28c02849.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.12
      spec: 1.0.2-dev
      go: go1.21.13 (Red Hat 1.21.13-3.module+el8.10.0+22345+acdd8d0e)
      libseccomp: 2.5.2
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: false
    path: /run/user/100841/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_SYS_CHROOT,CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.2.3-1.module+el8.10.0+22346+28c02849.x86_64
    version: |-
      slirp4netns version 1.2.3
      commit: c22fde291bb35b354e6ca44d13be181c76a0a432
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 2144595968
  swapTotal: 2147479552
  uptime: 1h 26m 15.00s (Approximately 0.04 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/jupyter/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 0
    stopped: 4
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev, metacopy=on
  graphRoot: /opt/data/podman/containers/storage
  graphRootAllocated: 96589578240
  graphRootUsed: 40128303104
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 8
  runRoot: /opt/data/podman/containers/storage
  transientStore: false
  volumePath: /opt/data/podman/containers/storage/volumes
version:
  APIVersion: 4.9.4-rhel
  Built: 1727863292
  BuiltTime: Wed Oct  2 12:01:32 2024
  GitCommit: ""
  GoVersion: go1.21.13 (Red Hat 1.21.13-3.module+el8.10.0+22345+acdd8d0e)
  Os: linux
  OsArch: linux/amd64
  Version: 4.9.4-rhel
`

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

On prem deployment over VMWare, can't install latest upstream due to OS and repo policies

### Additional information

Tried different workarounds:

- System restart
- `podman system reset`
- `podman system prune`
- setting `mountopt = "nodev, metacopy=off"` in storage.conf file
- rm containers folder

**Comment by Luap99** [comment]
>  runRoot: /opt/data/podman/containers/storage

This must be on a tmpfs or you must ensure that all the files are delete on boot before podman is run

Also how did you log into this user, we require a proper systemd login session, https://github.com/containers/podman/blob/main/troubleshooting.md#solution-28

Also if you have an issue with RHEL you should contact the Red Hat support and not upstream as the version is old and we only support the latest version upstream
