### ISSUE TITLE
podman exec --interactive consumes stdin even when the contained process does not

### ISSUE THREAD

**Issue by ntrrgc** [containers/podman#24370]
### Issue Description

`podman exec --interactive` is hungry for stdin. As soon as podman exec is launched it spawns a goroutine that reads data from stdin and sends it through a socket.

`pkg/bindings/containers/attach.go`:
```go
if options.GetAttachInput() {
	go func() {
		logrus.Debugf("Copying STDIN to socket")
		_, err := detach.Copy(socket, options.InputStream, []byte{})
		// ...
	}()
}
```

This is a problem in scripts containing multiple `podman exec --interactive` commands, as the first podman command will consume more input than its contained process, the extra input will be discarded and then the contained process of second command will hang waiting for the input that was accidentally discarded.

In my particular case, I was trying to debug why a seemingly simple clangd wrapper was seemingly not receiving any commands from VS Code. The script contained two commands, a first one for setup, and a second one for invoking clangd. Making the first non-interactive (either by removing `--interactive` or by giving it /dev/null as stdin) fixed the issue. However, this should not be necessary: when you batch commands in a shell script you don't expect them to consume stdin if they don't need it, and it shouldn't be different for commands ran inside podman.

### Steps to reproduce the issue

This minimal repro runs the `true` command inside the `wkdev` container. `podman exec` is ran under strace to reveal what podman is doing with stdin (file descriptor 0).

```
$ strace --silence=attach,exit --signal='!all' --decode-fds=all -e trace=read --trace-fds=0 --follow-forks podman exec -i wkdev true
[pid 278007] read(0<pipe:[651320]>, "Hi\n", 32768) = 3
[pid 278007] read(0<pipe:[651320]>, "", 32768) = 0
```

### Describe the results you received

podman exec --interactive eats all the stdin it can even if the contained process never does so.

### Describe the results you expected

podman exec should not be hungry, it should only read from stdin when the process being executed reads from stdin, and only for the same size the contained process asks for.

For reference, here is strace showing the `true` command does not consume stdin as you would expect.

```
$ echo Hi | strace --silence=attach,exit --signal='!all' --decode-fds=all -e trace=read --trace-fds=0 --follow-forks true
(empty output)
```

### podman info output

podman info from my system, but I also confirmed the issue also happens with `bin/podman` from the main branch.

host:
  arch: amd64
  buildahVersion: 1.37.3
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.12-2.fc40.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: '
  cpuUtilization:
    idlePercent: 98.68
    systemPercent: 0.38
    userPercent: 0.93
  cpus: 32
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: workstation
    version: "40"
  eventLogger: journald
  freeLocks: 2036
  hostname: chuches
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 6.11.4-201.fc40.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 96476483584
  memTotal: 134116134912
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.12.2-2.fc40.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.12.2
    package: netavark-1.12.2-1.fc40.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.12.2
  ociRuntime:
    name: crun
    package: crun-1.17-1.fc40.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.17
      commit: 000fa0d4eeed8938301f3bcf8206405315bc1017
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20240906.g6b38f07-1.fc40.x86_64
    version: |
      pasta 0^20240906.g6b38f07-1.fc40.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.2-2.fc40.x86_64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.5
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 4h 5m 38.00s (Approximately 0.17 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /home/ntrrgc/.config/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 1
    stopped: 5
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/ntrrgc/.local/share/containers/storage
  graphRootAllocated: 1099494850560
  graphRootUsed: 1058592116736
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 11
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/ntrrgc/.local/share/containers/storage/volumes
version:
  APIVersion: 5.2.3
  Built: 1727136000
  BuiltTime: Tue Sep 24 02:00:00 2024
  GitCommit: ""
  GoVersion: go1.22.7
  Os: linux
  OsArch: linux/amd64
  Version: 5.2.3

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

podman running on Fedora Workstation 40, which is running baremetal.

### Additional information

The issue happens every time, although at first I thought it didn't because I wasn't using `strace --follow-forks` and sometimes it's not the top `podman exec` process that does the read(), but one of its forked children.

**Comment by Luap99** [comment]
> podman exec should not be hungry, it should only read from stdin when the process being executed reads from stdin, and only for the same size the contained process asks for.

And how do you imagine this should work? Is is impossible to do this, we cannot know if and how much the container process will read as such this cannot be done.

We do not pass through the real fd into the container it always gets proxied for security reasons and to allow things like the remote API so the proxy must be used and it cannot know how much will be read.
For podman run we have a `--log-driver passthrough` option that would actually pass though the real fd so in this case there it would work. We could consider adding the same option to podman exec.

**Comment by Luap99** [comment]
Please open a PR to document this there.

**Comment by ntrrgc** [comment]
Can you explain what the current documentation line means with "keep stdin open even if not attached"? From what I've seen so far I'd rather replace it for "pipe stdin to the contained process", but I've also noticed that the same option is present for `podman create`, `podman exec`, `podman run` and `podman start`, so I may be missing some context from one of them or something of the like.

**Comment by Luap99** [comment]
The thing with a container is you can do `podman run -i -d` to run the container in the background, the container then would still see stdin as open and the reads would simply block if there is no data. You can then attach to this container via `podman attach` at any time and then send data from stdin there into the container.

The easiest to see this is via something like `podman run -i -d quay.io/libpod/testimage:20240123 cat` if you remove the -i it will exit as cat sees stdin as closed.

**Comment by Luap99** [comment]
And it is similar for podman exec: `podman exec -i -d test cat` keeps cat running even though it is in the background while without -i it again exits right away as stdin is closed. Of course for exec there is no attach command later so you would not be able to get it back in the foreground later but that is not important for keep stdin open part.

**Comment by ntrrgc** [comment]
Thanks a lot for the explanation, with that context it now makes sense. What do you think of this as a proposal for the documentation?

Old text:

> When set to **true**, keep stdin open even if not attached. The default is **false**.

New text:

> When set to **true**, make stdin available to the contained process. If **false**, the contained process' stdin is empty and immediately closed.
> 
> If attached, stdin is piped to the contained process. If detached, reading stdin will block until later attached.
>
> **Caveat:** podman will consume input from stdin as soon as it becomes available, even if the contained process doesn't request it. This is a design limitation derived from piping stdio over sockets and not exclusive to podman.

**Comment by Luap99** [comment]
sounds good to me
