### ISSUE TITLE
Error: vm "podman-machine-default" already exists on hypervisor

### ISSUE THREAD

**Issue by Heagan** [containers/podman#24378]
### Issue Description

Installed Podman last night and it was working perfectly, this morning after turning my computer on it stopped working, and nothing I do fixes it.
I run Windows 10, I do **not** have docker installed, WSL 2 is installed and I can still use it fine so thats not broken

I keep getting the error: 
`Error: vm "podman-machine-default" already exists on hypervisor`

But I don't know what that means or how to fix it

Terminal logs showing a few commands, theres no machines listed, system is failing to connect but nothing can initialize 
![Image](https://github.com/user-attachments/assets/ea90f32e-e0d5-4906-9bb7-0ce502be2cf1)

Podman Desktop also having the error
![Image](https://github.com/user-attachments/assets/6a7985c4-73c8-4896-9565-8af1d597d9de)

Things I've tried:
- Restarting PC / Podman
- Uninstalling and Reinstalling Podman and Podman Desktop
- Manually Deleting User/.local/ folder
- The commands you see in the Terminal screenshot (not sure if theres other commands I can try)

Even podman version fails but I used the `podman-5.2.4-setup.exe` to install it so it should be that
![Image](https://github.com/user-attachments/assets/a50aff82-42e9-4ca3-a2cf-eff3b2e2dc21)

podman info kinda works 
![Image](https://github.com/user-attachments/assets/326711b7-50d7-4ad4-bafb-8c929d7aee75)

### Steps to reproduce the issue

Steps to reproduce the issue
1. Not sure, best guess is when I turned my PC off the night before podman did not shut down correctly and something got corrupted

### Describe the results you received

Describe the results you received
Podman is not working at all, and I can not reset it to a working state even with a reinstall

### Describe the results you expected

Describe the results you expected
n/a

### podman info output

If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
OS: windows/amd64
provider: wsl
version: 5.2.5

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Serena01** [comment]
> took me too long to "figure" this out,
> 
> "fixed" by running:
> 
> ```
> wsl --unregister podman-machine-default
> ```
> 
> and deleting .local/ folder

Unfortunately, it didn't work for me on windows arm64
