### ISSUE TITLE
[Quadlet] Pod units are always started regardless of the content of [Install]

### ISSUE THREAD

**Issue by lambinoo** [containers/podman#24401]
### Issue Description

I'm not really sure this is a bug or not, as I doubt you can really do what I wanted to do with k8s pods.
When adding a unit to a pod, Quadlet generates `Wants=` dependencies in the pod service unit on top of the ordering (`Before=`) statements.

This starts the container unit with the pod unit regardless of how the container is configured in the `[Install]` section.

I was looking at having a setup where multiple containers, that should have a shared IPC namespace (hence the pod), start depending on if some systemd target are pulled in at boot.

Here's an example that sort of matches what I've been trying to do:
- `multi-user.target`: `app.pod`
- `production.target`: `app.container`
- `dev.target`: `logging.container`

But in this example, the `logging` container is always started with the pod, regardless of the state of the dev target.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create a `my.pod` with `WantedBy=default.target`
2. Create an empty `other.target` that isn't started
3. Create a container unit with `Pod=my.pod` and either `WantedBy=other.target`, or no `[Install]` section at all

### Describe the results you received

Container starts regardless of its `[Install]` section.

### Describe the results you expected

The container should follow its `[Install]` section, and not get started unless `other.target` is started.
Ordering requirements should still work in case the pod and container starts.

### podman info output

Running podman version 5.2.2 on Centos 9 stream on an amd64 machine.

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

**Comment by Luap99** [comment]
This is expected currently, the idea is that you generally only "enable" (install section) the pod and it will trigger all the containers automatically for you without also needed to declare them all as starting. I think this is what most users want and make sense as default.

We just added the `DefaultDependencies` key very recently to avoid adding the network-online dependency. https://github.com/containers/podman/commit/bac655a6b121a79492bced91ff79f421ffdc7b71
It doesn't cover the Wants/Before of the pod unit but I guess we can still change this as it is only in 5.3.0-rc1 yet if we think that would make sense. Alternatively we could add another key to disable the implicit unit dependencies on the container units.

cc @ygalblum

**Comment by lambinoo** [comment]
I'd be up to open a PR also once you reach a decision. Should be quite trivial, did the last one for the DefaultDependencies. But the ordering requirements must be kept, otherwise the container units would just be straight up invalid.

**Comment by Luap99** [comment]
Ah good I didn't look at the author, right keeping Before= makes sense and is needed so it would only be the Wants= that should be dropped from the pod unit in such case.

**Comment by lambinoo** [comment]
Would a `[Container]`  key like `StartwithPod` work in that case?

**Comment by ygalblum** [comment]
I think that both suggestions are misleading. Regardless to what the service file will have, starting the pod will make Podman start the container. 
So, the first question is what is the expected behaviour. Is the user still allowed to start the pod service? If yes, then not setting these values may cause systemd to be out of sync with Podman. So, maybe the right way is to set a key at the [Pod] section that will make the `ExecStart` into a `noop`? WDYT?

**Comment by Luap99** [comment]
How would we get out of sync? When the container unit is not started (running) the container does not exists and is thus nor part of the pod. As such it cannot get started by the pod unit I would think (unless like we do now we declare the wants).

**Comment by ygalblum** [comment]
Yeah, you're right, my bad. I was thinking of `podman container create` but, Quadlet just does `run` and `kill` so when the container service is down the pod is not aware of it.
So, I think it makes sense for this to be container specific configuration rather than a pod level one. This way the user can choose per container whether to start it with the pod or not. So, `StartWithPod` with a default `true` makes sense to me.

**Comment by lambinoo** [comment]
I'll go ahead and open a PR tomorrow!
