### ISSUE TITLE
podman machine start never ends

### ISSUE THREAD

**Issue by vtolstov** [containers/podman#24429]
### Issue Description

Waiting for VM ... never ends with latest podman on macos sequoia

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman machine init
2. podman machine start

### Describe the results you received

podman machine start  --log-level debug 
INFO[0000] podman filtering at log level debug          
DEBU[0000] Using Podman machine with `qemu` virtualization provider 
Starting machine "podman-machine-default"
DEBU[0000] {true 1500 map[forward-dest:[/run/user/501/podman/podman.sock] forward-identity:[/Users/vtolstov/.ssh/podman-machine-default] forward-sock:[/Users/vtolstov/.local/share/containers/podman/machine/qemu/podman.sock] forward-user:[core]] [] map[listen-qemu:unix:///var/folders/ym/j5bjj8cn1kn5gmyh6vrdqs580000gn/T/podman/qmp_podman-machine-default.sock] /var/folders/ym/j5bjj8cn1kn5gmyh6vrdqs580000gn/T/podman/podman-machine-default_proxy.pid 51483} 
DEBU[0000] qemu cmd: [/opt/podman/qemu/bin/qemu-system-aarch64 -accel hvf -accel tcg -cpu host -M virt,highmem=on -drive file=/opt/podman/qemu/share/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on -drive file=/Users/vtolstov/.local/share/containers/podman/machine/qemu/podman-machine-default_ovmf_vars.fd,if=pflash,format=raw -m 2048 -smp 4 -fw_cfg name=opt/com.coreos/config,file=/Users/vtolstov/.config/containers/podman/machine/qemu/podman-machine-default.ign -qmp unix:/var/folders/ym/j5bjj8cn1kn5gmyh6vrdqs580000gn/T/podman/qmp_podman-machine-default.sock,server=on,wait=off -netdev socket,id=vlan,fd=3 -device virtio-net-pci,netdev=vlan,mac=5a:94:ef:e4:0c:ee -device virtio-serial -chardev socket,path=/var/folders/ym/j5bjj8cn1kn5gmyh6vrdqs580000gn/T/podman/podman-machine-default_ready.sock,server=on,wait=off,id=apodman-machine-default_ready -device virtserialport,chardev=apodman-machine-default_ready,name=org.fedoraproject.port.0 -pidfile /var/folders/ym/j5bjj8cn1kn5gmyh6vrdqs580000gn/T/podman/podman-machine-default_vm.pid -virtfs local,path=/Users,mount_tag=vol0,security_model=none -virtfs local,path=/private,mount_tag=vol1,security_model=none -virtfs local,path=/var/folders,mount_tag=vol2,security_model=none -drive if=virtio,file=/Users/vtolstov/.local/share/containers/podman/machine/qemu/podman-machine-default_fedora-coreos-41.20241027.2.0-qemu.aarch64.qcow2] 
Waiting for VM ...

### Describe the results you expected

machine runs

### podman info output

podman info
OS: darwin/arm64
provider: qemu
version: 4.8.3

macos sequoia 15.1 (mac m1)

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by vtolstov** [comment]
![Image](https://github.com/user-attachments/assets/91fbe4db-828a-4112-88d7-1e944e69f04d)

**Comment by vtolstov** [comment]
after 8 attempts i can run podman machine
```
INFO[0000] podman filtering at log level debug          
DEBU[0000] Using Podman machine with `qemu` virtualization provider 
Starting machine "podman-machine-default"
DEBU[0000] {true 1500 map[forward-dest:[/run/user/501/podman/podman.sock] forward-identity:[/Users/vtolstov/.ssh/podman-machine-default] forward-sock:[/Users/vtolstov/.local/share/containers/podman/machine/qemu/podman.sock] forward-user:[core]] [] map[listen-qemu:unix:///var/folders/ym/j5bjj8cn1kn5gmyh6vrdqs580000gn/T/podman/qmp_podman-machine-default.sock] /var/folders/ym/j5bjj8cn1kn5gmyh6vrdqs580000gn/T/podman/podman-machine-default_proxy.pid 51483} 
DEBU[0000] qemu cmd: [/opt/podman/qemu/bin/qemu-system-aarch64 -accel hvf -accel tcg -cpu host -M virt,highmem=on -drive file=/opt/podman/qemu/share/qemu/edk2-aarch64-code.fd,if=pflash,format=raw,readonly=on -drive file=/Users/vtolstov/.local/share/containers/podman/machine/qemu/podman-machine-default_ovmf_vars.fd,if=pflash,format=raw -m 2048 -smp 4 -fw_cfg name=opt/com.coreos/config,file=/Users/vtolstov/.config/containers/podman/machine/qemu/podman-machine-default.ign -qmp unix:/var/folders/ym/j5bjj8cn1kn5gmyh6vrdqs580000gn/T/podman/qmp_podman-machine-default.sock,server=on,wait=off -netdev socket,id=vlan,fd=3 -device virtio-net-pci,netdev=vlan,mac=5a:94:ef:e4:0c:ee -device virtio-serial -chardev socket,path=/var/folders/ym/j5bjj8cn1kn5gmyh6vrdqs580000gn/T/podman/podman-machine-default_ready.sock,server=on,wait=off,id=apodman-machine-default_ready -device virtserialport,chardev=apodman-machine-default_ready,name=org.fedoraproject.port.0 -pidfile /var/folders/ym/j5bjj8cn1kn5gmyh6vrdqs580000gn/T/podman/podman-machine-default_vm.pid -virtfs local,path=/Users,mount_tag=vol0,security_model=none -virtfs local,path=/private,mount_tag=vol1,security_model=none -virtfs local,path=/var/folders,mount_tag=vol2,security_model=none -drive if=virtio,file=/Users/vtolstov/.local/share/containers/podman/machine/qemu/podman-machine-default_fedora-coreos-41.20241027.2.0-qemu.aarch64.qcow2] 
Waiting for VM ...
DEBU[0016] Executing: ssh [-i /Users/vtolstov/.ssh/podman-machine-default -p 51483 core@localhost -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o LogLevel=ERROR -o SetEnv=LC_ALL= true] 
Mounting volume... /Users:/Users
DEBU[0017] Executing: ssh [-i /Users/vtolstov/.ssh/podman-machine-default -p 51483 core@localhost -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o LogLevel=ERROR -o SetEnv=LC_ALL= -q -- sudo chattr -i / ; sudo mkdir -p /Users ; sudo chattr +i / ;] 
chattr: Operation not supported while reading flags on /
mkdir: cannot create directory ‘/Users’: Read-only file system
chattr: Operation not supported while reading flags on /
Error: exit status 1
DEBU[0017] Shutting down engines               
```

**Comment by vtolstov** [comment]
podman machine info
```
Host:
  Arch: arm64
  CurrentMachine: podman-machine-default
  DefaultMachine: podman-machine-default
  EventsDir: /var/folders/ym/j5bjj8cn1kn5gmyh6vrdqs580000gn/T/podman-run--1/podman
  MachineConfigDir: /Users/vtolstov/.config/containers/podman/machine/qemu
  MachineImageDir: /Users/vtolstov/.local/share/containers/podman/machine/qemu
  MachineState: Stopped
  NumberOfMachines: 1
  OS: darwin
  VMType: qemu
Version:
  APIVersion: 4.8.3
  Built: 1704295706
  BuiltTime: Wed Jan  3 18:28:26 2024
  GitCommit: 85dc30df56566a654700722a4dd190e1b9680ee7
  GoVersion: go1.21.5
  Os: darwin
  OsArch: darwin/arm64
  Version: 4.8.3

```

**Comment by baude** [comment]
when the vm is in this state, can you verify what podman and gvproxy processes are running ?  also, can you run with `podman --log-level debug machine start` and report what youi see in the console ?

**Comment by baude** [comment]
i see you posted some of it already ... do youi always see the login prompt in the terminal window with debug ? if so, it can only be two things:

1. the initial boot failed and the ignition file did not get injected or run properly
2. you are using an unsupported disk image.

I'm going to assume it is not the second one.  Was there anything wrong with the first boot? Did it get interupted? It worked fine?

**Comment by vtolstov** [comment]
as i'm try several times - first boot completed like in screenshot - vm waiting on login promt

**Comment by Luap99** [comment]
We only support the latest version upstream, 4.8 is long unsupported. Also as of 5.0 we no longer support/use qemu on macos.
