### ISSUE TITLE
`podman run -it fedora /bin/bash` fails on Fedora 41

### ISSUE THREAD

**Issue by scottmarlow** [containers/podman#24422]
### Issue Description

I tried  `podman run -it fedora /bin/bash` on Fedora 41 (upgraded Monday night and updated again this morning) and see no output.

I then tried  `podman --log-level=DEBUG run -it fedora /bin/bash` and see the following output [podman.log](https://github.com/user-attachments/files/17576746/podman.log)

### Steps to reproduce the issue

Steps to reproduce the issue
1. podman run -it fedora /bin/bash
2.
3.

### Describe the results you received

Container is not launched as per:

podman ps
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES

### Describe the results you expected

I expected to see a container started.

### podman info output

host:
  arch: amd64
  buildahVersion: 1.37.5
  cgroupControllers:
  - cpu
  - io
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.12-3.fc41.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.12, commit: '
  cpuUtilization:
    idlePercent: 95.14
    systemPercent: 0.62
    userPercent: 4.24
  cpus: 20
  databaseBackend: boltdb
  distribution:
    distribution: fedora
    variant: workstation
    version: "41"
  eventLogger: journald
  freeLocks: 2018
  hostname: scottmarlow
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 524288
      size: 65536
  kernel: 6.11.5-300.fc41.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 13658316800
  memTotal: 67107979264
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns-1.12.2-2.fc41.x86_64
      path: /usr/libexec/podman/aardvark-dns
      version: aardvark-dns 1.12.2
    package: netavark-1.12.2-1.fc41.x86_64
    path: /usr/libexec/podman/netavark
    version: netavark 1.12.2
  ociRuntime:
    name: crun
    package: crun-1.18-1.fc41.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.18
      commit: 8656b2548509fcc69ea7e8823a870564360a57a1
      rundir: /run/user/1000/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt-0^20240906.g6b38f07-1.fc41.x86_64
    version: |
      pasta 0^20240906.g6b38f07-1.fc41.x86_64
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: false
    path: /run/user/1000/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.2-3.fc41.x86_64
    version: |-
      slirp4netns version 1.2.2
      commit: 0ee2d87523e906518d34a6b423271e4826f71faf
      libslirp: 4.8.0
      SLIRP_CONFIG_VERSION_MAX: 5
      libseccomp: 2.5.5
  swapFree: 8549822464
  swapTotal: 8589930496
  uptime: 28h 30m 27.00s (Approximately 1.17 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - docker.io
store:
  configFile: /home/smarlow/.config/containers/storage.conf
  containerStore:
    number: 24
    paused: 0
    running: 0
    stopped: 24
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/smarlow/.local/share/containers/storage
  graphRootAllocated: 1022488477696
  graphRootUsed: 411859501056
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 75
  runRoot: /run/user/1000/containers
  transientStore: false
  volumePath: /home/smarlow/.local/share/containers/storage/volumes
version:
  APIVersion: 5.2.5
  Built: 1729209600
  BuiltTime: Thu Oct 17 20:00:00 2024
  GitCommit: ""
  GoVersion: go1.23.2
  Os: linux
  OsArch: linux/amd64
  Version: 5.2.5

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Using GNOME.

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
Does `podman ps -a` shows it, your log output clearly shows that the container was started correctly so I assume the bash process exits right away. Can you try using `sleep 10` or another command to check?

**Comment by scottmarlow** [comment]
podman ps -a shows:

> CONTAINER ID  IMAGE                                         COMMAND               CREATED         STATUS                       PORTS                             NAMES
> 2ed05c67106f  registry.fedoraproject.org/fedora:latest      /bin/bash             38 minutes ago  Exited (139) 38 minutes ago                                    thirsty_gates
> 2766f72eb600  registry.fedoraproject.org/fedora:latest      /bin/bash             38 minutes ago  Exited (139) 38 minutes ago                                    festive_moore
> 279ea7b90f2a  registry.fedoraproject.org/fedora:latest      /bin/bash             20 minutes ago  Exited (139) 20 minutes ago                                    sad_moser
> 6
> 

I tried `podman run -d --name sleeptest fedora sleep 10000000` and checked again:

> podman ps -a
> 50ffba0d2f4f  registry.fedoraproject.org/fedora:latest      sleep 10000000        About a minute ago  Exited (139) About a minute ago                                    sleeptest

**Comment by rhatdan** [comment]
Looks like an SELinux issue.

Could you make sure your system is up2date


sudo dnf -y update container-selinux

**Comment by rhatdan** [comment]
Something might have gone wrong on container-selinux install, so you might want to try

sudo dnf -y reinstall container-selinux

**Comment by scottmarlow** [comment]
No change from `dnf -y reinstall container-selinux`

> Repositories loaded.
> Package                                                                              Arch             Version                                                                              Repository                                            > Size
> Reinstalling:
>  container-selinux                                                                    noarch            2:2.233.0-1.fc41                                                                      fedora                                             > 68.1 KiB
>   replacing container-selinux                                                        noarch            2:2.233.0-1.fc41                                                                      fedora                                             68.1 KiB

**Comment by rhatdan** [comment]
Now run your AVC's though audit2allow 

audit2allow -la

**Comment by scottmarlow** [comment]
audit2allow -la

> 
> #============= container_t ==============
> 
> #!!!! This avc can be allowed using one of the these booleans:
> #     domain_can_mmap_files, virt_sandbox_use_fusefs
> allow container_t fusefs_t:file map;
> 
> #============= init_t ==============
> allow init_t unlabeled_t:file execute;
> 
> #============= setfiles_t ==============
> allow setfiles_t self:capability2 mac_admin;

**Comment by jesperpedersen** [comment]
Isn't there a test suite for things like this in the Fedora release model ?

**Comment by scottmarlow** [comment]
Output from `setsebool -P -V virt_sandbox_use_fusefs=1`:

> libsepol.context_from_record: type ktlshd_exec_t is not defined
> libsepol.context_from_record: could not create context structure
> libsepol.context_from_string: could not create context structure
> libsepol.sepol_context_to_sid: could not convert system_u:object_r:ktlshd_exec_t:s0 to sid
> invalid context system_u:object_r:ktlshd_exec_t:s0
> libsemanage.semanage_validate_and_compile_fcontexts: setfiles returned error code 255.
> Failed to commit changes to booleans: Success

Output from `getsebool -a | grep virt_sandbox_use_fusefs`
> virt_sandbox_use_fusefs --> on

**Comment by rhatdan** [comment]
This looks like issues in selinux-policy or at least whoever is providing ktlshd_t?

**Comment by rhatdan** [comment]
> Isn't there a test suite for things like this in the Fedora release model ?

No there are infinite combinations of applications and policies.  This boolean is usually shut off and I have not seen this in years of people using containers. 

Are you using fuse-overlay instead of overlayfs?

**Comment by jesperpedersen** [comment]
Isn't `podman run -it fedora /bin/bash` a simple test case ?

**Comment by jesperpedersen** [comment]
Maybe it could be run with the various configurations...

**Comment by scottmarlow** [comment]
> Are you using fuse-overlay instead of overlayfs?

Good question, I started with Fedora 9 so anything is possible.  I'm reading a bit more via https://www.redhat.com/en/blog/podman-rootless-overlay but still looking for the how to tell if I am using one or the other and how to switch.

**Comment by rhatdan** [comment]
What does podman info show?  You might want to do a `podman system reset`  which will blow away all of your images and containers but will get you to a known good state.

**Comment by scottmarlow** [comment]
`podman info --debug` output is here [podmaninfo.txt](https://github.com/user-attachments/files/17587959/podmaninfo.txt)

I tried `podman system reset -f` as root and no complaints from that but running `podman system reset -f` as non-root gives some complaints:

> WARN[0000] Found incomplete layer "ff2dc218b0847214c5bfbd5a86a6d607a28ab9b8367d753770fb34c46518e1ef", deleting it 
> WARN[0000] Found incomplete layer "d4d88b668759f3638ddf1346b6581428eab20a968b680ac5fb4cba3d0b6825a7", deleting it 
> WARN[0000] Found incomplete layer "514e74d7ef5a3012addf9d6b27c354c196568d3f8643e6fb00b4918701dd0d88", deleting it 
> WARN[0000] Found incomplete layer "7b4b2d899f3431a63dd3c19ca311bd76b3bfdd8d784d5d8c4039f720d632c833", deleting it 
> WARN[0000] Found incomplete layer "d015d003fb76bd58d2faac79df43c5c29732a1df56ec571f429aabd8014bdfc4", deleting it 
> WARN[0000] Found incomplete layer "ff2dc218b0847214c5bfbd5a86a6d607a28ab9b8367d753770fb34c46518e1ef", deleting it 
> WARN[0000] Found incomplete layer "d4d88b668759f3638ddf1346b6581428eab20a968b680ac5fb4cba3d0b6825a7", deleting it 
> WARN[0000] Found incomplete layer "514e74d7ef5a3012addf9d6b27c354c196568d3f8643e6fb00b4918701dd0d88", deleting it 
> WARN[0000] Found incomplete layer "7b4b2d899f3431a63dd3c19ca311bd76b3bfdd8d784d5d8c4039f720d632c833", deleting it 
> WARN[0000] Found incomplete layer "d015d003fb76bd58d2faac79df43c5c29732a1df56ec571f429aabd8014bdfc4", deleting it 
> WARN[0000] Found incomplete layer "ff2dc218b0847214c5bfbd5a86a6d607a28ab9b8367d753770fb34c46518e1ef", deleting it 
> WARN[0000] Found incomplete layer "d4d88b668759f3638ddf1346b6581428eab20a968b680ac5fb4cba3d0b6825a7", deleting it 
> WARN[0000] Found incomplete layer "514e74d7ef5a3012addf9d6b27c354c196568d3f8643e6fb00b4918701dd0d88", deleting it 
> WARN[0000] Found incomplete layer "7b4b2d899f3431a63dd3c19ca311bd76b3bfdd8d784d5d8c4039f720d632c833", deleting it 
> WARN[0000] Found incomplete layer "d015d003fb76bd58d2faac79df43c5c29732a1df56ec571f429aabd8014bdfc4", deleting it 
> ERRO[0000] 15 errors occurred:
>         * deleting layer "ff2dc218b0847214c5bfbd5a86a6d607a28ab9b8367d753770fb34c46518e1ef": openfdat /home/smarlow/.local/share/containers/storage/overlay/ff2dc218b0847214c5bfbd5a86a6d607a28ab9b8367d753770fb34c46518e1ef/diff/home/tck: permission denied
>         * deleting layer "d4d88b668759f3638ddf1346b6581428eab20a968b680ac5fb4cba3d0b6825a7": unlinkat /home/smarlow/.local/share/containers/storage/overlay/d4d88b668759f3638ddf1346b6581428eab20a968b680ac5fb4cba3d0b6825a7/diff/run/systemd/netif/leases/.wh..wh..opq: permission denied
>         * deleting layer "514e74d7ef5a3012addf9d6b27c354c196568d3f8643e6fb00b4918701dd0d88": unlinkat /home/smarlow/.local/share/containers/storage/overlay/514e74d7ef5a3012addf9d6b27c354c196568d3f8643e6fb00b4918701dd0d88/diff/opt/server/standalone/configuration/standalone_xml_history/.wh..opq: permission denied
>         * deleting layer "7b4b2d899f3431a63dd3c19ca311bd76b3bfdd8d784d5d8c4039f720d632c833": unlinkat /home/smarlow/.local/share/containers/storage/overlay/7b4b2d899f3431a63dd3c19ca311bd76b3bfdd8d784d5d8c4039f720d632c833/diff/usr/share/jenkins/ref/plugins/ace-editor.jpi: permission denied
>         * deleting layer "d015d003fb76bd58d2faac79df43c5c29732a1df56ec571f429aabd8014bdfc4": unlinkat /home/smarlow/.local/share/containers/storage/overlay/d015d003fb76bd58d2faac79df43c5c29732a1df56ec571f429aabd8014bdfc4/diff/usr/share/jenkins/ref/update-center-rootCAs: permission denied
>         * deleting layer "ff2dc218b0847214c5bfbd5a86a6d607a28ab9b8367d753770fb34c46518e1ef": openfdat /home/smarlow/.local/share/containers/storage/overlay/ff2dc218b0847214c5bfbd5a86a6d607a28ab9b8367d753770fb34c46518e1ef/diff/home/tck: permission denied
>         * deleting layer "d4d88b668759f3638ddf1346b6581428eab20a968b680ac5fb4cba3d0b6825a7": unlinkat /home/smarlow/.local/share/containers/storage/overlay/d4d88b668759f3638ddf1346b6581428eab20a968b680ac5fb4cba3d0b6825a7/diff/run/systemd/netif/leases/.wh..wh..opq: permission denied
>         * deleting layer "514e74d7ef5a3012addf9d6b27c354c196568d3f8643e6fb00b4918701dd0d88": unlinkat /home/smarlow/.local/share/containers/storage/overlay/514e74d7ef5a3012addf9d6b27c354c196568d3f8643e6fb00b4918701dd0d88/diff/opt/server/standalone/configuration/standalone_xml_history/.wh..opq: permission denied
>         * deleting layer "7b4b2d899f3431a63dd3c19ca311bd76b3bfdd8d784d5d8c4039f720d632c833": unlinkat /home/smarlow/.local/share/containers/storage/overlay/7b4b2d899f3431a63dd3c19ca311bd76b3bfdd8d784d5d8c4039f720d632c833/diff/usr/share/jenkins/ref/plugins/ace-editor.jpi: permission denied
>         * deleting layer "d015d003fb76bd58d2faac79df43c5c29732a1df56ec571f429aabd8014bdfc4": unlinkat /home/smarlow/.local/share/containers/storage/overlay/d015d003fb76bd58d2faac79df43c5c29732a1df56ec571f429aabd8014bdfc4/diff/usr/share/jenkins/ref/update-center-rootCAs: permission denied
>         * deleting layer "ff2dc218b0847214c5bfbd5a86a6d607a28ab9b8367d753770fb34c46518e1ef": openfdat /home/smarlow/.local/share/containers/storage/overlay/ff2dc218b0847214c5bfbd5a86a6d607a28ab9b8367d753770fb34c46518e1ef/diff/home/tck: permission denied
>         * deleting layer "d4d88b668759f3638ddf1346b6581428eab20a968b680ac5fb4cba3d0b6825a7": unlinkat /home/smarlow/.local/share/containers/storage/overlay/d4d88b668759f3638ddf1346b6581428eab20a968b680ac5fb4cba3d0b6825a7/diff/run/systemd/netif/leases/.wh..wh..opq: permission denied
>         * deleting layer "514e74d7ef5a3012addf9d6b27c354c196568d3f8643e6fb00b4918701dd0d88": unlinkat /home/smarlow/.local/share/containers/storage/overlay/514e74d7ef5a3012addf9d6b27c354c196568d3f8643e6fb00b4918701dd0d88/diff/opt/server/standalone/configuration/standalone_xml_history/.wh..opq: permission denied
>         * deleting layer "7b4b2d899f3431a63dd3c19ca311bd76b3bfdd8d784d5d8c4039f720d632c833": unlinkat /home/smarlow/.local/share/containers/storage/overlay/7b4b2d899f3431a63dd3c19ca311bd76b3bfdd8d784d5d8c4039f720d632c833/diff/usr/share/jenkins/ref/plugins/ace-editor.jpi: permission denied
>         * deleting layer "d015d003fb76bd58d2faac79df43c5c29732a1df56ec571f429aabd8014bdfc4": unlinkat /home/smarlow/.local/share/containers/storage/overlay/d015d003fb76bd58d2faac79df43c5c29732a1df56ec571f429aabd8014bdfc4/diff/usr/share/jenkins/ref/update-center-rootCAs: permission denied 
>

**Comment by scottmarlow** [comment]
Should I manually delete the ^ folders that had permission denied problems?

**Comment by jesperpedersen** [comment]
I have to do that, and then it will work

**Comment by jesperpedersen** [comment]
I mean the `dnf system reset` thing

**Comment by scottmarlow** [comment]
`dnf system reset` works for me now but I'm still looking to understand how to answer `Are you using fuse-overlay instead of overlayfs?` as the launched VM still exits immediately (`podman run -it fedora /bin/bash`).

Some possible answers:

> podman info | grep -i over
>     capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
>   graphDriverName: overlay
>     Native Overlay Diff: "true"
>   GoVersion: go1.23.2

**Comment by scottmarlow** [comment]
In case it helps others to see my sestatus:

> sestatus
> SELinux status:                 enabled
> SELinuxfs mount:                /sys/fs/selinux
> SELinux root directory:         /etc/selinux
> Loaded policy name:             targeted
> Current mode:                   enforcing
> Mode from config file:          enforcing
> Policy MLS status:              enabled
> Policy deny_unknown status:     allowed
> Memory protection checking:     actual (secure)
> Max kernel policy version:      33
>

**Comment by scottmarlow** [comment]
Don't use this workaround but I now have Podman working again temporarily:

Starting Podman container:
> podman run -it fedora /bin/bash
> [root@99f1d9c5f55d /]#

Listing Podman containers:
> podman ps
> CONTAINER ID  IMAGE                                     COMMAND     CREATED         STATUS         PORTS       NAMES
> 99f1d9c5f55d  registry.fedoraproject.org/fedora:latest  /bin/bash   17 seconds ago  Up 18 seconds              mystifying_jones

Temporary workaround of disabling SELinux:
> setenforce Permissive

Enabling SELinux after container is stopped (e.g. you are done with it):
> setenforce Enforcing

Note that enabling SELinux while contain is still running will cause container to exit:
> podman ps -a
> 99f1d9c5f55d  registry.fedoraproject.org/fedora:latest  /bin/bash   5 minutes ago   Exited (0) 2 minutes ago                 mystifying_jones

**Comment by scottmarlow** [comment]
More info but similar to previous post:

> ausearch -m  ALL -ts recent
> ----
> time->Fri Nov  1 09:45:19 2024
> type=AVC msg=audit(1730468719.431:433): avc:  denied  { read write } for  pid=12371 comm="bash" path="/dev/pts/0" dev="devpts" ino=3 scontext=system_u:system_r:container_t:s0:c42,c159 tcontext=system_u:object_r:container_file_t:s0:c42,c159 tclass=chr_file permissive=0
> ----
> time->Fri Nov  1 09:45:19 2024
> type=AVC msg=audit(1730468719.431:434): avc:  denied  { read write } for  pid=12371 comm="bash" path="/dev/pts/0" dev="devpts" ino=3 scontext=system_u:system_r:container_t:s0:c42,c159 tcontext=system_u:object_r:container_file_t:s0:c42,c159 tclass=chr_file permissive=0
> ----
> time->Fri Nov  1 09:45:19 2024
> type=AVC msg=audit(1730468719.431:435): avc:  denied  { read write } for  pid=12371 comm="bash" path="/dev/pts/0" dev="devpts" ino=3 scontext=system_u:system_r:container_t:s0:c42,c159 tcontext=system_u:object_r:container_file_t:s0:c42,c159 tclass=chr_file permissive=0
> ----
> time->Fri Nov  1 09:45:19 2024
> type=AVC msg=audit(1730468719.431:436): avc:  denied  { read write } for  pid=12371 comm="bash" path="/dev/pts/0" dev="devpts" ino=3 scontext=system_u:system_r:container_t:s0:c42,c159 tcontext=system_u:object_r:container_file_t:s0:c42,c159 tclass=chr_file permissive=0
> ----
> time->Fri Nov  1 09:45:19 2024
> type=AVC msg=audit(1730468719.432:437): avc:  denied  { read } for  pid=12371 comm="bash" path="/usr/lib64/libc.so.6" dev="dm-0" ino=114881106 scontext=system_u:system_r:container_t:s0:c42,c159 tcontext=unconfined_u:object_r:data_home_t:s0 tclass=file permissive=0

I think ran `journalctl -t setroubleshoot` and went to the end of the output which mentioned:
> Nov 01 09:49:15 scottmarlow setroubleshoot[13075]: SELinux is preventing bash from read access on the file /usr/lib64/libc.so.6. For complete SELinux messages run: sealert -l db17fa16-897f-46cb-bd6e-dc92cda4af6f

So, here I am doing that:

> sealert -l db17fa16-897f-46cb-bd6e-dc92cda4af6f
> SELinux is preventing bash from read access on the file /usr/lib64/libc.so.6.
> 
> *****  Plugin restorecon (99.5 confidence) suggests   ************************
> 
> If you want to fix the label. 
> /usr/lib64/libc.so.6 default label should be lib_t.
> Then you can run restorecon. The access attempt may have been stopped due to insufficient permissions to access a parent directory in which case try to change the following command accordingly.
> Do
> # /sbin/restorecon -v /usr/lib64/libc.so.6
> 
> *****  Plugin catchall (1.49 confidence) suggests   **************************
> 
> If you believe that bash should be allowed read access on the libc.so.6 file by default.
> Then you should report this as a bug.
> You can generate a local policy module to allow this access.
> Do
> allow this access for now by executing:
> # ausearch -c 'bash' --raw | audit2allow -M my-bash
> # semodule -X 300 -i my-bash.pp
> 
> 
> Additional Information:
> Source Context                system_u:system_r:container_t:s0:c401,c832
> Target Context                unconfined_u:object_r:data_home_t:s0
> Target Objects                /usr/lib64/libc.so.6 [ file ]
> Source                        bash
> Source Path                   bash
> Port                          <Unknown>
> Host                          scottmarlow
> Source RPM Packages           
> Target RPM Packages           glibc-2.40-3.fc41.x86_64
> SELinux Policy RPM            selinux-policy-targeted-41.24-1.fc41.noarch
> Local Policy RPM              selinux-policy-targeted-41.24-1.fc41.noarch
> Selinux Enabled               True
> Policy Type                   targeted
> Enforcing Mode                Enforcing
> Host Name                     scottmarlow
> Platform                      Linux scottmarlow 6.11.5-300.fc41.x86_64 #1 SMP
>                               PREEMPT_DYNAMIC Tue Oct 22 20:11:15 UTC 2024
>                               x86_64
> Alert Count                   1
> First Seen                    2024-11-01 09:49:12 EDT
> Last Seen                     2024-11-01 09:49:12 EDT
> Local ID                      db17fa16-897f-46cb-bd6e-dc92cda4af6f
> 
> Raw Audit Messages
> type=AVC msg=audit(1730468952.937:508): avc:  denied  { read } for  pid=13055 comm="bash" path="/usr/lib64/libc.so.6" dev="dm-0" ino=114881106 scontext=system_u:system_r:container_t:s0:c401,c832 tcontext=unconfined_u:object_r:data_home_t:s0 tclass=file permissive=0
> 
> 
> Hash: bash,container_t,data_home_t,file,read
>

**Comment by scottmarlow** [comment]
The first option didn't help `/sbin/restorecon -v /usr/lib64/libc.so.6`

So will try the other option and report it as a bug if it helps:
> ausearch -c 'bash' --raw | audit2allow -M my-bash
> semodule -X 300 -i my-bash.pp

^ seemed to fail:

> semodule -X 300 -i my-bash.pp
> Failed to resolve typeattributeset statement at /var/lib/selinux/targeted/tmp/modules/200/snappy/cil:223
> Failed to resolve AST
> semodule:  Failed!
>
> semodule -i my-bash.pp
> Failed to resolve typeattributeset statement at /var/lib/selinux/targeted/tmp/modules/200/snappy/cil:223
> Failed to resolve AST
> semodule:  Failed!

**Comment by scottmarlow** [comment]
Also tried `fixfiles -B onboot` and rebooted but still see same failure (bash exits with 127).

**Comment by bachradsusi** [comment]
> The first option didn't help `/sbin/restorecon -v /usr/lib64/libc.so.6`
> 
> So will try the other option and report it as a bug if it helps:
> 
> > ausearch -c 'bash' --raw | audit2allow -M my-bash
> > semodule -X 300 -i my-bash.pp
> 
> ^ seemed to fail:
> 
> > semodule -X 300 -i my-bash.pp
> > Failed to resolve typeattributeset statement at /var/lib/selinux/targeted/tmp/modules/200/snappy/cil:223
> > Failed to resolve AST
> > semodule:  Failed!
> > semodule -i my-bash.pp
> > Failed to resolve typeattributeset statement at /var/lib/selinux/targeted/tmp/modules/200/snappy/cil:223
> > Failed to resolve AST
> > semodule:  Failed!

Most likely related to snapd-selinux and it should be already fixed in snapd-2.65.1-2.fc41 - https://src.fedoraproject.org/rpms/snapd/c/5d25d758dbb194041e637562e8e3b3739614a46e?branch=rawhide

Update snapd-selinux and reinstall container-selinux and it should work.

**Comment by scottmarlow** [comment]
> 
> Most likely related to snapd-selinux and it should be already fixed in snapd-2.65.1-2.fc41 - https://src.fedoraproject.org/rpms/snapd/c/5d25d758dbb194041e637562e8e3b3739614a46e?branch=rawhide
> 
> Update snapd-selinux and reinstall container-selinux and it should work.

+100 thank you so much SELinux team + @bachradsusi + @rhatdan + @Luap99!  After doing a `dnf update` this morning, Podman just works again!
