### ISSUE TITLE
Rootless Podman containers fail to start due to IP exhaustion in CNI network after multiple deployments

### ISSUE THREAD

**Issue by ksemtinimahmoud** [containers/podman#24444]
### Issue Description

We have been encountering a recurring IP exhaustion issue with rootless Podman containers, running as systemd units, over the past two weeks on one of our servers. Most containers are attached to a specific CNI (Container Network Interface), and after several container deployments, any new container attached to this CNI fails to start.

The error displayed is:

`Error: plugin type="bridge" failed (add): cni plugin bridge failed: failed to allocate for range 0: no IP addresses available in range set: 10.89.0.1-10.89.0.254`

The issue seems related to IP address exhaustion within the CNI range specified.
We initially expanded the IP range, which temporarily resolved the issue. However, it recurred after additional deployments, suggesting that IP addresses are either not being released or are being continuously consumed over time.

### Steps to reproduce the issue

Steps to reproduce the issue
1. Create CNI Network: Create a CNI network with a limited IP range to simulate IP exhaustion:
`podman network create --interface-name cni-podman1 --ipam-driver=host-local --subnet=10.89.0.0/24 --ip-range=10.89.0.0/24  --gateway 10.89.0.1 --route=0.0.0.0/0,10.89.0.1 my_network`
2. Run Multiple Containers: Deploy multiple containers on this network to consume IP addresses in the specified range:
`for i in {1..300}; do
  podman run --rm --name my_container --network my_network alpine sleep 1
done`
3. Observe Behavior: After a certain number of deployments (typically reaching the IP limit in the specified subnet), you should encounter the following error for new container startups:
`Error: plugin type="bridge" failed (add): cni plugin bridge failed: failed to allocate for range 0: no IP addresses available in range set: 10.89.0.1-10.89.0.254`

### Describe the results you received

After several deployments, we reach a point where new containers attached to the affected CNI fail to start. Specifically, we receive the error indicating IP address exhaustion:

`Error: plugin type="bridge" failed (add): cni plugin bridge failed: failed to allocate for range 0: no IP addresses available in range set: 10.89.0.1-10.89.0.254`

When this error occurs, restarting the affected containers does not free up IP addresses, and we are unable to start new containers until the CNI range is manually expanded or recreated. This suggests that IP addresses are being continuously allocated without release, even after containers stop. This behavior persists even after expanding the IP range temporarily, as the issue reoccurs after additional deployments.

### Describe the results you expected

We expect IP addresses within the CNI range to be reused after container shutdowns, rather than continuously consumed until the range is exhausted.

### podman info output

```
host:
  arch: amd64
  buildahVersion: 1.33.8
  cgroupControllers: []
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.1.10-1.module+el8.10.0+22202+761b9a65.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: 148bf229a807d6e44637491c5f02ea75d07                            00397'
  cpuUtilization:
    idlePercent: 81.86
    systemPercent: 5.64
    userPercent: 12.5
  cpus: 16
  databaseBackend: boltdb
  distribution:
    distribution: rhel
    version: "8.10"
  eventLogger: file
  freeLocks: 2014
  hostname: xxxx
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 56116
      size: 1
    - container_id: 1
      host_id: 1017504
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 56116
      size: 1
    - container_id: 1
      host_id: 1017504
      size: 65536
  kernel: 4.18.0-553.16.1.el8_10.x86_64
  linkmode: dynamic
  logDriver: k8s-file
  memFree: 1506492416
  memTotal: 134634512384
  networkBackend: cni
  networkBackendInfo:
    backend: cni
    dns:
      package: podman-plugins-4.9.4-12.module+el8.10.0+22202+761b9a65.x86_64
      path: /usr/libexec/cni/dnsname
      version: |-
        CNI dnsname plugin
        version: 1.4.0-dev
        commit: unknown
        CNI protocol versions supported: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.4.0, 1.0.                            0
    package: containernetworking-plugins-1.4.0-5.module+el8.10.0+22202+761b9a65.                            x86_64
    path: /usr/libexec/cni
  ociRuntime:
    name: runc
    package: runc-1.1.12-4.module+el8.10.0+22202+761b9a65.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.1.12
      spec: 1.0.2-dev
      go: go1.21.7 (Red Hat 1.21.7-2.module+el8.10.0+21638+b01be198)
      libseccomp: 2.5.2
  os: linux
  pasta:
    executable: ""
    package: ""
    version: ""
  remoteSocket:
    exists: false
    path: /run/user/56116/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,C                            AP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_S                            YS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.2.3-1.module+el8.10.0+22202+761b9a65.x86_64
    version: |-
      slirp4netns version 1.2.3
      commit: c22fde291bb35b354e6ca44d13be181c76a0a432
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.2
  swapFree: 15501967360
  swapTotal: 34359734272
  uptime: 635h 6m 31.00s (Approximately 26.46 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/USER/.config/containers/storage.conf
  containerStore:
    number: 29
    paused: 0
    running: 24
    stopped: 5
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /home/USER/.local/share/containers/storage
  graphRootAllocated: 525877641216
  graphRootUsed: 447688060928
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 353
  runRoot: /run/user/56116/containers
  transientStore: false
  volumePath: /home2/podman/containers/storage/volumes
version:
  APIVersion: 4.9.4-rhel
  Built: 1723116282
  BuiltTime: Thu Aug  8 11:24:42 2024
  GitCommit: ""
  GoVersion: go1.21.7 (Red Hat 1.21.7-2.module+el8.10.0+21638+b01be198)
  Os: linux
  OsArch: linux/amd64
  Version: 4.9.4-rhel
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

physical severs

### Additional information

We are running the same Podman setup on multiple servers across different environments. Currently, this IP exhaustion issue is only occurring on one specific server, which has a higher frequency of container deployments compared to others. This could suggest that the issue may be tied to deployment volume or frequency on this particular server, rather than a configuration inconsistency across environments.

**Comment by Luap99** [comment]
Upstream only supports the latest version and as of podman 5.0 CNI is no longer supported.

If you have issues in RHEL you need to contact Red Hat support.
