### ISSUE TITLE
Migrate 'projectatomic/libpod' to 'Webhook To Fedora Messaging'

### ISSUE THREAD

**Issue by gridhead** [containers/podman#24475]
This project was listed in the [**GitHub2FedMsg**](https://github.com/fedora-infra/github2fedmsg) database and we want to you to inform you about the upcoming deprecation of the service. As the [**Fedora Infrastructure**](https://docs.fedoraproject.org/en-US/infra/) is finishing up with migrating its applications away from [**FedMsg**](https://github.com/fedora-infra/fedmsg) to [**Fedora Messaging**](https://github.com/fedora-infra/fedora-messaging), we encourage you to migrate your repository to the successor of the [**GitHub2FedMsg**](https://fedora-arc.readthedocs.io/en/latest/github2fedmsg/index.html) project, [**Webhook To Fedora Messaging**](https://webhook2fedmsg.apps.ocp.fedoraproject.org/docs).

Please follow [this link](https://communityblog.fedoraproject.org/announcing-webhook-to-fedora-messaging/) to the official announcement of the project’s release and use the instructions there to [migrate](https://pagure.io/fedora-infra/w2fm-migration/issues) to the new service. If this notification was a mistake, please close this notification ticket. We will not act on the repositories whose migrations have not been requested and any related GitHub2FedMsg operations will stop working once the service is decommissioned.

**Comment by Luap99** [comment]
projectatomic/libpod no longer exists
