### ISSUE TITLE
Migrate 'containers/podman' to 'Webhook To Fedora Messaging'

### ISSUE THREAD

**Issue by gridhead** [containers/podman#24477]
This project was listed in the [**GitHub2FedMsg**](https://github.com/fedora-infra/github2fedmsg) database and we want to you to inform you about the upcoming deprecation of the service. As the [**Fedora Infrastructure**](https://docs.fedoraproject.org/en-US/infra/) is finishing up with migrating its applications away from [**FedMsg**](https://github.com/fedora-infra/fedmsg) to [**Fedora Messaging**](https://github.com/fedora-infra/fedora-messaging), we encourage you to migrate your repository to the successor of the [**GitHub2FedMsg**](https://fedora-arc.readthedocs.io/en/latest/github2fedmsg/index.html) project, [**Webhook To Fedora Messaging**](https://webhook2fedmsg.apps.ocp.fedoraproject.org/docs).

Please follow [this link](https://communityblog.fedoraproject.org/announcing-webhook-to-fedora-messaging/) to the official announcement of the project’s release and use the instructions there to [migrate](https://pagure.io/fedora-infra/w2fm-migration/issues) to the new service. If this notification was a mistake, please close this notification ticket. We will not act on the repositories whose migrations have not been requested and any related GitHub2FedMsg operations will stop working once the service is decommissioned.

**Comment by lsm5** [comment]
@gridhead does github2fedmsg get used in release-monitoring.org ? I don't see any other reason it got added there.

**Comment by lsm5** [comment]
ah I see it's this webhook https://github.com/containers/podman/settings/hooks/58625171 . I'm gonna disable it and see if anything blows up. I don't think we need it anymore after packit integration.

**Comment by Luap99** [comment]
yes we do have these webhooks set up, however they seems to have zero metadata attached as of when or why they were added to the repo so it is impossible to know who created them unless that person remembers hence my question internally first

**Comment by lsm5** [comment]
closing this one. Don't think anything has blown up in the last 3 weeks.

**Comment by lsm5** [comment]
i hear we need it for sync2jira. reopening

**Comment by lsm5** [comment]
> i hear we need it for sync2jira. reopening

nvm, looks like it's all working. Re-closing.
