### ISSUE TITLE
nvidia gpu device acess in containers

### ISSUE THREAD

**Issue by viprob-ai** [containers/podman#24474]
Hi I am facing an issue in setting up the gpu inside container.

**OS: ubuntu 22.04
podman versions : 3.4.4
nvidia-ctk version : 1.17**

Followed all the instruction as per the below link but still no success :
`https://github.com/NVIDIA/nvidia-container-runtime/issues/85#issuecomment-1772741424`

    nvidia-ctk cdi generate --output=/etc/cdi/nvidia.yaml

    podman run --rm --device nvidia.com/gpu=all --security-opt=label=disable ubuntu nvidia-smi -L

**```Error: stat nvidia.com/gpu=all: no such file or directory```**

**Comment by Luap99** [comment]
You need a newer podman, we only support the latest version upstream

**Comment by viprob-ai** [comment]
How to fetch the latest Podman on Ubuntu 22.04 

I ran below command
sudo apt install Padmanabhan
Still the version is 3.4.4

Any help on this.
