### ISSUE TITLE
podman not able pull image

### ISSUE THREAD

**Issue by tppalani** [containers/podman#24492]
### Issue Description

I'm trying to install podman (4.3.1) in my VDAAS machine windows i have created podman machine and i can able to start also but when I'm trying to podman pull image i'm getting error like connection refused.

```
Name                         URI                                                          Identity                                      Default
podman-machine-default       ssh://user@localhost:60710/run/user/1000/podman/podman.sock  C:\Users\.ssh\podman-machine-default  false
podman-machine-default-root  ssh://root@localhost:60710/run/podman/podman.sock            C:\Users\.ssh\podman-machine-default  true
``` 

```
podman machine ssh
Connecting to vm podman-machine-default. To close connection, use `~.` or `exit`
ssh: connect to host localhost port 60710: Connection refused
```

```
wsl -l -v
  NAME                      STATE           VERSION
* podman-machine-default    Running         2
```

```
Get-NetTCPConnection -LocalPort 60710-State Listen

Get-NetTCPConnection : No matching MSFT_NetTCPConnection objects found by CIM query for instances of the
ROOT/StandardCimv2/MSFT_NetTCPConnection class on the  CIM server: SELECT * FROM MSFT_NetTCPConnection  WHERE ((LocalPort = 60710)) AND ((State
= 2)). Verify query parameters and retry.
At line:1 char:1
+ Get-NetTCPConnection -LocalPort 60710-State Listen
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MSFT_NetTCPConnection:String) [Get-NetTCPConnection], CimJobException
    + FullyQualifiedErrorId : CmdletizationQuery_NotFound,Get-NetTCPConnection
```

### Steps to reproduce the issue

Steps to reproduce the issue
1.
2.
3.

### Describe the results you received

odman machine start
Starting machine "podman-machine-default"
wsl: Error: 0xe000020b
Error code: CreateInstance/CreateVm/ConfigureNetworking/HNS/0xe000020b
wsl: Failed to configure network (networkingMode Nat), falling back to no networking.
API forwarding for Docker API clients is not available due to the following startup failures.
        CreateFile \\.\pipe\docker_engine: All pipe instances are busy.
 
Podman clients are still able to connect.
Machine "podman-machine-default" started successfully

### Describe the results you expected

Describe the results you expected

### podman info output

If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
```
wsl: Error: 0xe000020b
Error code: CreateInstance/CreateVm/ConfigureNetworking/HNS/0xe000020b
wsl: Failed to configure network (networkingMode Nat), falling back to no networking.
```

This sounds like some WSL errors and not something podman is doing, in any case upstream only supported the latest version and podman 4.3 is way to old.
