### ISSUE TITLE
Add a Hash Mechanism for Podman Secrets to Improve Security

### ISSUE THREAD

**Issue by Zakeeyullah** [containers/podman#24519]
### Feature request description

According to [Red Hat Guide](https://www.redhat.com/en/blog/new-podman-secrets-command), It is said that **the secret stored on disk in unencrypted files controlled by the container host**. This can be a security concern if someone gains access to the container.

### Suggest potential solution

I suggest to set up a **Hashing Mechanism** for the secrets stored, in a manner it cannot be read from within the container but can be used for relevant authentication.

I am not sure is this a good idea. I don't have such technical expertise. Anyway, I wanted to suggest this Idea I've got.

Hope this will help to patch up that loophole.

**Comment by Luap99** [comment]
Hashing != Encryption, Hashing is a one way function and would not help.

Fundamentally the goal of a secret is to make it available as plain text file to the container. If you don't want a secret in the container do not leak it into it via --secret. And given we need to expose this unencrypted secret it must exists as plain file on the host as well in order for us to bind mount it.

There are actually different secret drivers that allow you to store the content encrypted such as pass: https://docs.podman.io/en/latest/markdown/podman-secret-create.1.html#secret-drivers
But in the end we will always have a unencrypted copy when the container is created copied into the container storage dir.
