### ISSUE TITLE
Empty volume exports

### ISSUE THREAD

**Issue by oSourceSE** [containers/podman#24562]
### Issue Description

Volume exports are empty and no error message during exports.

### Steps to reproduce the issue

Steps to reproduce the issue:

Not sure if there is any steps to reproduce this, since the export has been working for these specific container for a long time but suddenly one day the export is only 1Kb in size, other containers on the same host still produce correct volume exports.

The containers themself works and i can use the data within the containers without issue.

Running the following command which gives zero output to console:
podman volume export --output backup_c4.tar volume-c4-data

### Describe the results you received

Describe the results you received:

Empty 1Kb files when they should at least hold a couple of Mb and more.

1.0K Nov 14 13:56 backup_c1.tar
4.8M Nov 14 13:56 backup_c2.tar
213M Nov 14 13:57 backup_c3.tar
1.0K Nov 14 13:57 backup_c4.tar

container export for c1 should be around 64Mb and c4 should be around 63Mb

### Describe the results you expected

Describe the results you expected:

Full volume exports usable for restoring when needed.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.33.7
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon_2.1.10+ds1-1build2_amd64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.10, commit: unknown'
  cpuUtilization:
    idlePercent: 99.27
    systemPercent: 0.34
    userPercent: 0.39
  cpus: 4
  databaseBackend: sqlite
  distribution:
    codename: noble
    distribution: ubuntu
    version: "24.04"
  eventLogger: journald
  freeLocks: 2038
  hostname: ***
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 10000000
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 10000000
  kernel: 6.8.0-47-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 4230172672
  memTotal: 8226430976
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns_1.4.0-5_amd64
      path: /usr/lib/podman/aardvark-dns
      version: aardvark-dns 1.4.0
    package: netavark_1.4.0-4_amd64
    path: /usr/lib/podman/netavark
    version: netavark 1.4.0
  ociRuntime:
    name: crun
    package: crun_1.14.1-1_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.14.1
      commit: de537a7965bfbe9992e2cfae0baeb56a08128171
      rundir: /run/user/1001/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +WASM:wasmedge +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt_0.0~git20240220.1e6f92b-1_amd64
    version: |
      pasta unknown version
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: false
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_1.2.1-1build2_amd64
    version: |-
      slirp4netns version 1.2.1
      commit: 09e31e92fa3d2a1d3ca261adaeb012c8d75a8194
      libslirp: 4.7.0
      SLIRP_CONFIG_VERSION_MAX: 4
      libseccomp: 2.5.5
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 460h 18m 22.00s (Approximately 19.17 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /***/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 3
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,index=off
  graphRoot: /***/storage
  graphRootAllocated: 100861726720
  graphRootUsed: 18820022272
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Supports shifting: "false"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 5
  runRoot: /run/user/1001/containers
  transientStore: false
  volumePath: /***/storage/volumes
version:
  APIVersion: 4.9.3
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.22.2
  Os: linux
  OsArch: linux/amd64
  Version: 4.9.3
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

No

### Additional environment details

I'm running on Ubuntu 24.04 LTS and 4.9.3 is the latest version available there.

Not sure what the issue can be but are open to testing some things if needed.

**Comment by mheon** [comment]
Any chance you can try with a newer Podman? 4.9.3 may be the latest available but it's closing in on a year old.

And can you add `--log-level=debug` to your `podman volume export` (specifically on the volume that fails) and provide the output?
A `podman inspect` of the volume would also help.

**Comment by mheon** [comment]
OK. There's nothing at all unusual about the volume, and it seems like our archiver did choose the right directory (the filepath is correct for our named volume schema; I'm assuming that `/***/storage/volumes/volume-c1-data/_data` does contain the volume data?). There doesn't appear to be anything obvious that would prevent us from archiving it. Can you check the permissions on the directory's contents versus other volumes? I'd expect us to get actual error messages off such an error, but nothing else jumps out as a potential cause.

**Comment by oSourceSE** [comment]
Been investigating this a bit further and my conclusion is user error on my side.

One of the backup file that is 1Kb has actually no static data, it is session information for that system and somehow it has cleaned itself up to not use that folder anymore due to version changes from the container owner.

The other one is an error on my side, between 2 versions of my own built container i data location within the container making the already mounted volume pointing in the wrong place, this explains the 1Kb size on that one.

Sorry for taking up your time, closing this one as solved.
