### ISSUE TITLE
Command line option for netavark

### ISSUE THREAD

**Issue by anpic** [containers/podman#24574]
### Feature request description

```
$ ls -1 ./bin
conmon
fuse-overlayfs
netavark
podman
runc
```
```
$ export PATH=$PATH:abs_path_to_bin
```
```
$ ./bin/podman system info
Error: could not find "netavark" in one of [/usr/local/libexec/podman /usr/local/lib/podman /usr/libexec/podman /usr/lib/podman].  To resolve this error, set the helper_binaries_dir key in the `[engine]` section of containers.conf to the directory containing your helper binaries.
```

### Suggest potential solution

Additional command line options are needed that will repeat all the options available through the configuration file.

**Comment by PiotrBzdrega** [comment]
@anpic do you have containers.conf  file??
Looks like you are searching for this tag:
 [#example
[engine]
helper_binaries_dir = ["/usr/libexec/podman"]](https://github.com/containers/common/blob/main/docs/containers.conf.5.md#:~:text=helper_binaries_dir%3D%5B%22/usr/libexec/podman%22%2C%20...%5D)

**Comment by anpic** [comment]
> do you have containers.conf file??

But why is it not possible to set these options directly on the command line?
It can be more convenient to specify on the command line than to create configuration files and set environment variables.

**Comment by Luap99** [comment]
Because if we have to add a cli options for every single config option we end up with 100+ options which is a lot of extra complexity that is really not needed in the majority of use cases.

What is your reason for having to set them on the cli over using a config file?

**Comment by anpic** [comment]
> Because if we have to add a cli options for every single config option we end up with 100+ options which is a lot of extra complexity that is really not needed in the majority of use cases.

Yes, let's cancel the command line options everywhere in linux and leave only the configuration files :)



> What is your reason for having to set them on the cli over using a config file?

And why are command line options generally considered best practice in linux? Because it is more convenient to automate them. And it's certainly more convenient to use configuration files in the form of JSON format.
The only justification for your approach can only be a reason if project was built from several different old projects. But it's still not a reason to leave things as they are.

**Comment by anpic** [comment]
And why is it possible to configure paths separately for some binaries and for some only a general parameter `helper_binaries_dir` is made?
Moreover, all this is also scattered across various docs.

**Comment by rhatdan** [comment]
Sometimes adding config options for every possible option, just makes the tool become too complicated and hard to use.  Look at the complexity of lxc tools versus Podman and Docker.  Exposing every possible option on the CLI can lead to worse outcomes for the user by causing complexity.

**Comment by anpic** [comment]
> Exposing every possible option on the CLI can lead to worse outcomes for the user by causing complexity.

You have created a wonderful tool and you know better how to develop it.
At least, it seems to me that it is more convenient to use configuration files in JSON format.

**Comment by anpic** [comment]
> Things grow historically

I can't say that I agree with everything, but at the same time I recognize the persuasiveness of your arguments. Thanks for the explanation.


> JSON is not nice to type manually which is often done for config files. It also doesn't allow comments which is important for many users.

It may be worth adding it as an additional format. Then it's still easier to manage the subsections of options.
