### ISSUE TITLE
Command line and config option for fuse-overlayfs

### ISSUE THREAD

**Issue by anpic** [containers/podman#24573]
### Feature request description

```
$ ls -1 ./bin
conmon
fuse-overlayfs
netavark
podman
runc
```
```
$ cat ./etc/containers.conf 
[engine]

conmon_path = [
	"./bin/conmon",
]

helper_binaries_dir = [
	"./bin"
]

[engine.runtimes]

runc = [
	"./bin/runc"
]
```
```
$ export CONTAINERS_CONF=./etc/containers.conf
```
```
$ ./bin/podman system info
Error: configure storage: 'overlay' is not supported over overlayfs, a mount_program is required: backing file system is unsupported for this graph driver
```
```
$ export PATH=$PATH:abs_path_to_bin
```
```
$ ./bin/podman system info
host:
    ...
```

### Suggest potential solution

An additional option is needed to configure the path to `fuse-overlayfs` from the command line and config file.

**Comment by PiotrBzdrega** [comment]
@anpic do you have [storage.conf](https://github.com/containers/storage/blob/main/storage.conf)  file??
 [You probably need mount_program = "/usr/bin/fuse-overlayfs" under [storage.options.overlay]](https://docs.podman.io/en/stable/markdown/podman.1.html#:~:text=If%20storage.conf%20exists%20in%20the%20homedir%2C%20add%20mount_program%20%3D%20%22/usr/bin/fuse%2Doverlayfs%22%20under%20%5Bstorage.options.overlay%5D%20to%20enable%20this%20feature.)
