### ISSUE TITLE
toast messages are not visible in windows 11 (podman.exe version 5.2.5)

### ISSUE THREAD

**Issue by cetindogu** [containers/podman#24589]
### Issue Description

in default light theme, toast message body is not visible.  content text and background are both white color.
PS C:\Users\cetin.dogu> podman --version
podman.exe version 5.2.5

bug in light mode:
![Image](https://github.com/user-attachments/assets/1afbe938-8e91-43f4-920f-ab1d3438df75)

in dark mode:
![Image](https://github.com/user-attachments/assets/367ec04e-8dc6-45d1-865f-e2caa0b4b7cc)

### Steps to reproduce the issue

Steps to reproduce the issue
1. install latest versino in windows 11
2. check toast message on right bottom side.
3.

### Describe the results you received

toast messages are not visible.

### Describe the results you expected

toast messages must be visible.

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
podman desktop issues must be reported in the desktop repo: https://github.com/podman-desktop/podman-desktop/issues
