### ISSUE TITLE
Podman 5.3.0 on Windows 11

### ISSUE THREAD

**Issue by er-eg** [containers/podman#24606]
### Issue Description

API forwarding for Docker API clients is not available on Windows 11 after the latest update.
User is not admin and podman is installed via scoop.

### Steps to reproduce the issue

Update Podman to 5.3.0 from the previous version.

### Describe the results you received

Message when starting default podman machine:

```
API forwarding for Docker API clients is not available due to the following startup failures. 
The system cannot find the path specified.
```

### Describe the results you expected

No warning.

### podman info output

```yaml
Starting machine "podman-machine-default"
API forwarding for Docker API clients is not available due to the following startup failures.
        The system cannot find the path specified.

Podman clients are still able to connect.
```

### Podman in a container

No

### Privileged Or Rootless

None

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by baude** [comment]
I think this is a dup of #24557

**Comment by er-eg** [comment]
This is the output when teh machine is stopped:

`Could not stop API forwarding service (win-sshproxy.exe): open C:\Users\???\.local\share\containers\podman\machine\wsl\podman-machine-default\win-sshproxy.tid: The system cannot find the file specified.`
