### ISSUE TITLE
`sudo podman system reset` deleted my $HOME without warning

### ISSUE THREAD

**Issue by imax9000** [containers/podman#24638]
### Issue Description

I installed podman to try running [coreos-assembler](https://github.com/coreos/coreos-assembler/blob/main/docs/building-fcos.md). It was complaining that `Error: 'overlay' is not supported over zfs, a mount_program is required: backing file system is unsupported for this graph driver`

So I went ahead and tried to change the storage driver to zfs.

![Image](https://github.com/user-attachments/assets/f9092a8b-e217-4574-9dfc-a8cb4b80f9ea)

Note that the confirmation prompt does not mention that everything under the current working directory is going to be deleted.

### Steps to reproduce the issue

Sorry, I'm too pissed off to try to reproduce it again.

### Describe the results you received

Most of my data gone.

### Describe the results you expected

Only the podman-managed data gone, which at that point was none.

### podman info output

```yaml
% podman info
Error: 'overlay' is not supported over zfs, a mount_program is required: backing file system is unsupported for this graph driver
```

### Podman in a container

No

### Privileged Or Rootless

Privileged

### Upstream Latest Release

No

### Additional environment details

Laptop with root on ZFS

**Comment by Luap99** [comment]
Please provide the storage.conf you used and the proper podman info output or well at least the version.

**Comment by imax9000** [comment]
```
% cat /etc/containers/storage.conf 
[storage]
driver="zfs"
```

As for `podman info` - that's the actual output I got. At this point I've uninstalled podman and blacklisted it in /etc/apt/preferences.d/. Here's the version mentioned in /var/log/dpkg.log:

```
2024-11-21 11:24:52 remove podman:amd64 3.4.4+ds1-1ubuntu1.22.04.3 <none>
```

**Comment by Luap99** [comment]
3.4.4 is not a supported release and very old. If I remember correctly there were issues like this reported in the past that should be all be fixed. https://github.com/containers/podman/issues/18349
