### ISSUE TITLE
"userns=auto" not overwriting default "userns=host"

### ISSUE THREAD

**Issue by dmennecke1** [containers/podman#24661]
I am running rootless podman and ive tried to put each container in a different user namespace using `--userns auto`. Based on [this issue](https://github.com/containers/podman/discussions/13728?sort=old) it seemed that its more secure to run rootless containers with individual user namespaces for each container (using `--userns auto`). I am working to ensure that if an attacker manages to escape a container, they will not be able to compromise or affect other containers running under non-root users.

I have created a pod with `--userns auto` consisting of two containers (each consisting of an apache2 web server). When inspecting the pod it still says `"userns": "host"`. 

Also, both containers still use the same namespace:

```sh
$podman top containerA user huser
USER        HUSER
root        231072
root        231072
root        231072
www-data    231105
www-data    231105

$ podman top containerB user huser
USER        HUSER
root        231072
root        231072
root        231072
www-data    231105
www-data    231105
```

### Steps to reproduce the issue

Create a pod with `userns=auto` and see if `podman pod inspect <POD>` returns `userns=auto` instead of the default `userns=host`

### Describe the results you received

See Issue Description

### Describe the results you expected

I expected every container to run inside an isolated user namespace.

### podman info output

```yaml
host:
  arch: amd64
  buildahVersion: 1.38.0
  cgroupControllers:
  - cpu
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.1.12, commit: e8896631295ccb0bfdda4284f1751be19b483264'
  cpuUtilization:
    idlePercent: 98.32
    systemPercent: 0.59
    userPercent: 1.09
  cpus: 4
  databaseBackend: boltdb
  distribution:
    codename: noble
    distribution: ubuntu
    version: "24.04"
  eventLogger: journald
  freeLocks: 2026
  hostname: appserver-ek03
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
  kernel: 6.8.0-49-generic
  linkmode: dynamic
  logDriver: journald
  memFree: 5411762176
  memTotal: 12492906496
  networkBackend: netavark
  networkBackendInfo:
    backend: netavark
    dns:
      package: aardvark-dns_1.4.0-5_amd64
      path: /usr/lib/podman/aardvark-dns
      version: aardvark-dns 1.4.0
    package: netavark_1.4.0-4_amd64
    path: /usr/lib/podman/netavark
    version: netavark 1.13.0
  ociRuntime:
    name: crun
    package: crun_1.14.1-1_amd64
    path: /usr/bin/crun
    version: |-
      crun version 1.17
      commit: 000fa0d4eeed8938301f3bcf8206405315bc1017
      rundir: /run/user/1001/crun
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  pasta:
    executable: /usr/bin/pasta
    package: passt_0.0~git20240220.1e6f92b-1_amd64
    version: |
      pasta unknown version
      Copyright Red Hat
      GNU General Public License, version 2 or later
        <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
      This is free software: you are free to change and redistribute it.
      There is NO WARRANTY, to the extent permitted by law.
  remoteSocket:
    exists: true
    path: /run/user/1001/podman/podman.sock
  rootlessNetworkCmd: pasta
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns_100:1.1.8-4_amd64
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 1977085952
  swapTotal: 1977085952
  uptime: 59h 21m 51.00s (Approximately 2.46 days)
  variant: ""
plugins:
  authorization: null
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  - ipvlan
  volume:
  - local
registries: {}
store:
  configFile: /home/containeruser/.config/containers/storage.conf
  containerStore:
    number: 18
    paused: 0
    running: 8
    stopped: 10
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs_1.13-1_amd64
      Version: |-
        fusermount3 version: 3.14.0
        fuse-overlayfs: version 1.13-dev
        FUSE library version 3.14.0
        using FUSE kernel interface version 7.31
  graphRoot: /var/home/containeruser/podman_storage
  graphRootAllocated: 84398252032
  graphRootUsed: 40484597760
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Supports shifting: "true"
    Supports volatile: "true"
    Using metacopy: "false"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 32
  runRoot: /tmp/containers-user-1001/containers
  transientStore: false
  volumePath: /var/home/containeruser/podman_storage/volumes
version:
  APIVersion: 5.3.0
  Built: 1732110805
  BuiltTime: Wed Nov 20 14:53:25 2024
  GitCommit: 874bf2c301ecf0ba645f1bb45f81966cc755b7da-dirty
  GoVersion: go1.23.2
  Os: linux
  OsArch: linux/amd64
  Version: 5.3.0
```

### Podman in a container

No

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

I've build Podman and all of it's components from source (crun, passt, netvark, conmon etc.)

**Comment by giuseppe** [comment]
can you run something like `podman exec $CTR grep . /proc/self/?id_map` and show the result?

Containers running inside the same pod will share the same user namespace, there won't be a nested user namespace created for them.

**Comment by dmennecke1** [comment]
@giuseppe both containers return:

```sh
/proc/self/gid_map:         0          1       1024
/proc/self/uid_map:         0          1       1024
```

If containers running in the same pod share the same user namespace, wouldn't that mean that if an attacker breaks out of one container, they would have access to the other containers as well?

**Comment by giuseppe** [comment]
you are running in a nested user namespace, so the flag is in place.



> If containers running in the same pod share the same user namespace, wouldn't that mean that if an attacker breaks out of one container, they would have access to the other containers as well?

containers in a pod are meant to share some resources, in this case the user namespace.  If you want to protect container A from container B, then you need to not use a pod, or two different ones.

It would be also difficult to manage the nested user namespaces, because some resources need to be accessed from the parent user namespace, and some others from the nested ones.

I am closing the issue because it works as expected, but feel free to comment further

**Comment by dmennecke1** [comment]
I’m not sure what the best approach is for running containers that should be grouped. Should all the containers run in the same pod, with the downside of sharing the same user namespace? Or is it better to run them without a pod and in separate user namespaces?

What would you recommend? And if you’d go with the pod approach, how can the security risks of the shared user namespace be reduced?
