### ISSUE TITLE
Fail to run privileged nested container, on fedora 41

### ISSUE THREAD

**Issue by Yarboa** [containers/podman#24692]
### Issue Description

Describe your issue

Fail to run privileged nested container, on fedora 41

### Steps to reproduce the issue

Steps to reproduce the issue
1. Fedora41
2.  `dnf copr enable -y @centos-automotive-sig/bluechi-snapshot "Fedora-41-$(arch)"`
3. `dnf copr enable -y rhcontainerbot/qm "fedora-41-$(arch)"`
4. `dnf install -y qm`
5. Now, need to run emulated setup script to install qm systemd and podman in QM rootfs.
`     bash -x /usr/share/qm/setup `
6. Verify qm service is up
```
    systemctl is-acive qm 
    podman ps shows qm enviroment is running.

```
7. Run nested container, rootfull
```
    podman exec qm podman run ubi9-minimal pwd
```

### Describe the results you received

Describe the results you received

```
    Resolved "ubi9-minimal" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
    Trying to pull registry.access.redhat.com/ubi9-minimal:latest...
    Getting image source signatures
    Writing manifest to image destination
    Storing signatures
Error: crun: setrlimit `RLIMIT_NOFILE`: Operation not permitted: OCI permission denied

```

### Describe the results you expected

Describe the results you expected
Nested container should run without failures.[host-podman-info.txt](https://github.com/user-attachments/files/17935955/host-podman-info.txt)
[qm-podman-info.txt](https://github.com/user-attachments/files/17935954/qm-podman-info.txt)

Nested podman container is run successfully for c9s
https://artifacts.dev.testing-farm.io/0d73bf4f-14b2-43c9-8bcf-27b07f3406fb/work-kvm-tier-05glnpgbx/plans/e2e/kvm-tier-0/execute/data/guest/default-0/tests/qm-sanity-test/check_qm_podman_quadlet_is_ok-4/output.txt 

### podman info output

```yaml
If you are unable to run podman info for any reason, please provide the podman version, operating system and its version and the architecture you are running.

*podman info*

Please see attached files
host-podman-info.txt
attached file for qm
qm-podman-info.txt

*podman version*

rpm -q podman
podman-5.3.1-1.fc41.x86_64

podman exec qm rpm -q podman
podman-5.3.1-1.fc41.x86_64


*operating system* 
Fedora
*version*
41, uname -r
6.11.8-300.fc41.x86_64

architecture
x86_64
```

### Podman in a container

Yes

### Privileged Or Rootless

Privileged

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

To understand tested enviroment please refer this README
https://github.com/containers/qm?tab=readme-ov-file#qm-is-a-containerized-environment-for-running-functional-safety-qm-quality-management-software

### Additional information

more details exist here
[qm#660](https://github.com/containers/qm/issues/666) 

This one https://github.com/containers/qm/issues/666#issuecomment-2500103556
Did not help to solve the issue

**Comment by Luap99** [comment]
Can you provide the actual podman commands used please.

**Comment by Luap99** [comment]
> LimitNOFILE=65536

Ok I see, your outer container sets a low file limit and you do not give the container CAP_SYS_RESOURCE so it cannot increase it. Since commit
https://github.com/containers/podman/commit/5ebba75dbd4462da47283b3f018804b7361d52bf we try to set a static default limit. So you either need to use a higher limit for the outer container or use a different limit for the inner container, either via --ulimit or there should be a containers.conf default I think.

The alternative is for podman to not assume we can increase the limits as root (check for CAP_SYS_RESOURCE) and if not just clamp it like with the rootless case: https://github.com/containers/podman/issues/24508#issuecomment-2470105817

cc @giuseppe

**Comment by Yarboa** [comment]
OK, i think i got it from here 
man getrlimit | grep RLIMIT_NPROC

**Comment by Luap99** [comment]
> [conmon:d]: failed to write to /proc/self/oom_score_adj: Permission denied

That can be ignored conmon tries to bump this so it is not killed before container process as we want conmon to work and correctly spawn the container cleanup command. But as rootless this is not possible so it safe to ignore.

> podman exec qm podman run --ulimit nofile=256:1024  ubi9-minimal pwd
Error: crun: setrlimit `RLIMIT_NPROC`: Operation not permitted: OCI permission denied

That is now failing on NPROC, you fixed the NOFILE issue


With https://github.com/containers/podman/pull/24696 merged it should just work without any changes for you again if you test podman from main. Podman checks for sys_resource and not try to bump the limits higher when it does have the cap.
