### ISSUE TITLE
Debian rootless integration tests fail remote tests that are supposed to raise an error

### ISSUE THREAD

**Issue by siretart** [containers/podman#24803]
### Issue Description

Debian rootless integration tests fail remote tests that are supposed to raise an error.

For instance, this one: https://github.com/containers/podman/blob/v5.3/test/e2e/system_dial_stdio_test.go

The reason appears to be that the testsuite installs the `podman` Distro package, which comes with the systemd unit `/usr/lib/systemd/user/podman.socket` to make rootless podman as a system service work out of the box.

That's awesome, but it appears this test particular asserts that this fails.

Maybe this test could be written in a  way that skips the test in this situation?

As a sidenote, the Debian autopkgtest run "as-installed" package tests. I've written a small test invocation script that runs  the upstream integration tests to revalidate fresh rebuilds of podman with potentially updated dependencies.

### Privileged Or Rootless

Rootless

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by Luap99** [comment]
You are right the tests should pass regardless if a podman service is running on the default location or not.

The test doesn't particular useful either. Just checking that we get a connection error does not mean the command actually works properly when there is a functioning connection.
