### ISSUE TITLE
rootless: allow binding privileged ports with CAP_NET_BIND_SERVICE file cap

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/podman#3212]
https://github.com/containers/libpod/blob/master/rootless.md says `Podman can not create containers that bind to ports < 1024.`, but could be enabled with `sudo setcap cap_net_bind_service=+ep $(which slirp4netns)` if Podman could run slirp4netns in the initial userns.

**Comment by vrothberg** [comment]
Thanks for opening the issue, @AkihiroSuda! PRs are always welcome :) Would you open one to change the document?

**Comment by rhatdan** [comment]
That seems like a decent documentation fix, definitely not something we could do by default.

**Comment by giuseppe** [comment]
this is quite risky though.  I am fine if we document it, but we also need to point out what are the risks associated with it

**Comment by rhatdan** [comment]
Depends how much you consider the risk of a rogue process listening at a port < 1024.

**Comment by baude** [comment]
whats the story here

**Comment by rhatdan** [comment]
@AkihiroSuda If you want this, could you open a PR for it?

**Comment by AkihiroSuda** [comment]
I noticed it doesn't work actually, because Podman executes slirp4netns in a user namespace and hence the cap is dropped :(

**Comment by AkihiroSuda** [comment]
RootlessKit + Docker is not affected by this problem (nor https://github.com/rootless-containers/slirp4netns/issues/135)  because RootlessKit executes its own port forwarder in the initial namespaces.  

It would be great if Podman can use this pkg as well. https://github.com/rootless-containers/rootlesskit/tree/v0.6.0/pkg/port/builtin

**Comment by AkihiroSuda** [comment]
A workaround is `sudo sh -c "echo 0 > /proc/sys/net/ipv4/ip_unprivileged_port_start"`

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
now rootless Podman creates and joins the user namespace immediately so it would be very complicated to run the slirp4netns process in the initial user namespace.  I think for Podman the `sudo sh -c "echo 0 > /proc/sys/net/ipv4/ip_unprivileged_port_start"` workaround would be safer

**Comment by QGB** [comment]
why `# setcap 'cap_net_bind_service=+ep' /usr/bin/podman`  not work, useless ?

**Comment by AkihiroSuda** [comment]
> why `# setcap 'cap_net_bind_service=+ep' /usr/bin/podman` not work, useless ?

https://github.com/containers/podman/issues/3212#issuecomment-523303048

**Comment by rhatdan** [comment]
@QGB Why not just do the sysctl?
