### ISSUE TITLE
podman should support native secrets

### ISSUE THREAD

**Issue by kallisti5** [containers/podman#3264]
docker has the 'secret' command to manage local secrets, podman should offer the same.

  * Selectively exposing secrets to the container in question
    * "username=ewrwer32"

Ideally, given kubernetes popularity, podman should offer some/all of the same "in-container" expose options k8s can.

* Environment Variable
* Mount point

**Reference:**
* https://kubernetes.io/docs/concepts/configuration/secret/

**Extras:**
  * ```podman generate kube``` could generate k8s secret files as well :fire: 

The current mount.conf method exposes the same secrets to all containers which is insecure. (lacks isolation)

**Comment by mheon** [comment]
From what I've seen, Docker secrets are mostly intended for use with Swarm, but I don't see much reason we can't use them with `podman run`. We'd need four commands for parity (`secret create`, `secret ls`, `secret inspect`, `secret rm`) plus a flag for `podman create` and `podman run` to add them.

**Comment by kallisti5** [comment]
It makes sense for "small single-node deployments"  I mean, once you're up to things like k8s, you can graduate to their secret storage.  This is nice because it (hopefully) avoids the "having clear text passwords on disk"

**Comment by rhatdan** [comment]
@kallisti5 Would you be interested in opening PRs to do this work?  We would welcome it.

**Comment by kallisti5** [comment]
sure.  I've been searching for secret storage solutions, and tbh the options outside of k8s kind of suck. Vault looks interesting, but Hasicorp is pretty hard to deal with if you don't have a contract with them.

I'll play around with some things and see if anything interesting comes of it.  Would PR's 'going the right direction' that don't break the build be accepted, or is this a 'we need a working end-to-end solution' before accepting the PR?

**Comment by rhatdan** [comment]
Right direction would be fine.

**Comment by kallisti5** [comment]
ok. *early*  work in progress here:
  * https://github.com/kallisti5/libpod/commits/podman_secrets

Thinking of modeling secrets like volumes initially.
  * Secrets using the 'local' driver get stored at:
    * secret_path="~/.local/share/containers/storage/secrets"
  * A randomly generated encryption key stored in "~/.config/containers/libpod.conf" which encrypts all of the secrets on disk.
  * Secrets presented to attached containers at /secrets/local/(name)

Having an encryption key in libpod.conf isn't great long-term, but I feel like it is a better solution than what people do today, and a good first iteration.

**Comment by rhatdan** [comment]
We already have a direcory /run/secrets in every container, better to place them there.
If this is a rootless case, should the secrets be encrypted with the a key key under ~/.ssh?

**Comment by rhatdan** [comment]
@mtrmac @vrothberg @mrunalp  WDYT?

**Comment by mtrmac** [comment]
- It would be very nice (if not an outright requirement) if this could seamlessly graduate to k8s secrets (i.e. using the same concepts / formats, and ideally `pod man generate kube` knowing how to export them in the right format). (OTOH personally I am very uninterested in Swarm compatibility, but others may have different opinions on that.)
- I am extremely skeptical about encrypting secrets and storing the key in a location with exactly the same permissions necessary to access the encrypted secrets. AFAICT all that can do is confuse casual users into thinking the data is somehow protected. Either be honest about the nonexistent confidentiality (i.e. just write the data to disk in plain text), or record the secrets and/or the secret-encrypting key in an actually more secure way (e.g. use a login-unlocked keyring, don’t record the key at all and force the user to enter a passphrase each time).

**Comment by rhatdan** [comment]
I agree on both points.  We need this to be as integrated with the k8s work flow as possible.  And at least for the rootless version, have the secrets encrypted with the user login session.  At least then they would be secret when the user is not logged in.

No really good way to solve this for secrets used by root though, unless systemd has some magic thing.

**Comment by kallisti5** [comment]
Things like hashicorp vault require 3 of 5 unlock keys to decrypt the secret storage on startup.. unfortunately that doesn't make much sense in the non-daemon world. (And from a security standpoint still isn't super great since 'the app in the container still has to auth to vault'

So.. key things to solve:
 * How to encrypt / decrypt secrets in a way that offers some real protection.
 * How to export secrets to native k8s long-term as an upgrade path.
 * Keeping compatibility. If podman run requires a password to unlock secrets, that isn't docker workflow compatible.

**Comment by rhatdan** [comment]
Would storing the unlock key in gnome-keyring or in kernel keyring be more in line with what the Docker Daemon does.
IE I specify the key one time and then it uses the one in the kernel keyring from then on.

**Comment by rhatdan** [comment]
@kallisti5 Any progress on this?

**Comment by kallisti5** [comment]
not at the moment.  Too many projects, not enough man hours :-)
If anyone else wants to play with my changes / finish them / refactor them, feel free. (just post here so I know)

**Comment by mheon** [comment]
I've seen additional interest in this from #podman on Freenode, but no solid answers as to security model yet.

**Comment by vrothberg** [comment]
That's something we can discuss next week. Would love to here @mtrmac's thoughts on it.

**Comment by rhatdan** [comment]
Added.

**Comment by Michael-Angel-Sec** [comment]
Thank you for your work on this feature.  We are doing single node podman deployments and are looking forward to this feature.

**Comment by vrothberg** [comment]
@rhatdan, shall we reevaluate the priority of this request?

**Comment by rhatdan** [comment]
Yes I think this is something we should start work on.

**Comment by rhatdan** [comment]
@vrothberg do you have time to work on this?  Otherwise I can add it to @QiWang19 List.

**Comment by mheon** [comment]
I think we still need a design conversation on how these should work.

**Comment by vrothberg** [comment]
I will be on PTO, but I will find time for that in March (along with the systemd work and auto updates). But anyone can pick it up :) There's also some performance improvements for c/image that I want to tackle in the near future.

I agree with Matt that we need a conversation on the design first; ideally a dedicated meeting where we can carve out what we want.

**Comment by rhatdan** [comment]
@ashley-cui PTAL

**Comment by mheon** [comment]
I still think we need to discuss how this should be implemented.

If anyone is following this, I think having use cases would very much help.

**Comment by dtitov** [comment]
So, AFAIU, this was not implemented? What are the official suggested alternatives? How do people inject secrets to `podman` now? Just as plain files?

**Comment by mheon** [comment]
No, this is not presently implemented, but it is something we'd like to look into. Can you describe your use case? I think a big part of the problem with this one is not really understanding how a secrets implementation should function in a single-node scenario.

**Comment by dtitov** [comment]
Sure, so the scenario is pretty simple. I'm migrating my single-node Docker Compose deployment to podman. In my `docker-compose.yml` file I have the secrets section, and then those secrets are injected to some services, here's the file: https://github.com/neicnordic/LocalEGA-deploy-swarm/blob/master/docker-compose.yml

Now, I converted my Docker Compose setup to podman setup following [this article](https://www.redhat.com/sysadmin/compose-podman-pods) (using `podman generate kube` and `podman play kube`). In general, it works, but I realized that there's no support for secrets...

Meanwhile, just to keep going with testing out podman, I replaced secrets with mounting files, which is, obviously, not the best approach for sensitive files. 

P.S. Also, a bit of off-topic, but maybe you could quickly point me to some resource: it seems that `podman play kube` also doesn't pick up environment variables from the host OS. Neither I could find any information on using `.env` files to do such kind of propagation. And again, AFAIK, Kubernetes ConfigMaps are not supported currently by `podman play kube`. So what would be the recommended way of propagating external env-vars to pods (without having them manually put to the `.yaml` file)?

**Comment by rhatdan** [comment]
@dtitov Please open a second issue on the ConfigMaps, I think this is something we could easily get someone to work on.  Should not be that hard.

On the Secrets, I believe we should handle them the same way that kubernetes does.  (Not that I know how that is done.)  We are always looking for Community help, and often their are people looking to add Kubernetes features/ideas to Podman,

**Comment by rhatdan** [comment]
I would say the smartest thing would be to tie the support to Kubernetes.

Following what is provided here.

https://kubernetes.io/docs/concepts/configuration/secret/

Add the ability for `podman secret` to manage this content and share it with Kubernetes.  The problem we will have is how to store these secrets.  Docker seems to store them in some encrypted service, we have no service for Podman, so it would have to be done as a flat file or an extension onto the libpod database.

**Comment by dtitov** [comment]
Got it, thanks 👍

**Comment by xordspar0** [comment]
My usecase is similar to @dtitov 's. I have a single-node that I'm converting from docker-compose to podman. I already know Kubernetes, so I think having the same API as k8s would be awesome. The only gap for me is keeping the secrets out of my config, which is checked into git.

Ansible has support for local [secrets](https://docs.ansible.com/ansible/latest/user_guide/vault.html). I use this for my (non-containerized) deployments today. The vault file is not checked into git, but I have a Makefile that prompts for secrets and creates the vault file if it's missing. So if I want to deploy from a new host, I can check out the git repo, run `make deploy`, copy-paste from my password manager, and deployments can be automated from then on. Maybe the design for how Podman stores secrets could learn something from that.

Come to think of it, maybe I can use Ansible to drive my Podman deployments. In that case I wouldn't need native secret support in Podman. However, if it would be really powerful if I could migrate to Kubernetes with no changes to my deployment spec.

**Comment by mheon** [comment]
The ansible secrets link is very interesting - I can see a model like that as being a viable way forward.

**Comment by mheon** [comment]
Ideally, we'd find a library to handle the cryptography/secret storage for us - I'd prefer not to have to write and maintain that ourselves.

**Comment by kallisti5** [comment]
> Would storing the unlock key in gnome-keyring or in kernel keyring be more in line with what the Docker Daemon does.
> IE I specify the key one time and then it uses the one in the kernel keyring from then on.

I think this is likely the best plan of action.  Protecting secret storage with a local system keyring makes sense.

> I would say the smartest thing would be to tie the support to Kubernetes.

I agree.   Back in 2019 I was still using swarm, but k8s is easy enough to deploy now and widespread enough it's a better target.

> Now, I converted my Docker Compose setup to podman setup following this article (using podman generate kube and podman play kube). In general, it works, but I realized that there's no support for secrets...

```podman generate kube``` potentially spitting out kubernetes secrets from podman is pretty :fire: 

Y'all would corner the market and make docker a thing of the past for desktop container development :-)

**Comment by rhatdan** [comment]
@ashley-cui Have you thought about this at all?

**Comment by ashley-cui** [comment]
@rhatdan I have not, but would be happy to pick it up with some help

**Comment by rhatdan** [comment]
Sounds good, lets talk about this at watercooler.

**Comment by xordspar0** [comment]
> Ideally, we'd find a library to handle the cryptography/secret storage for us - I'd prefer not to have to write and maintain that ourselves.

Ansible (written in Python) implements its [Vaults](https://github.com/ansible/ansible/blob/devel/lib/ansible/parsing/vault/__init__.py) with the symmetric encryption library `cryptography`: https://cryptography.io/en/latest/

I wonder if there's a similar symmetric encryption library for Go. That would be something to look into.

**Comment by xordspar0** [comment]
[golang.org/x/crypto/nacl/secretbox][1] is an option. Packages in the golang.org/x/ space are semi-official. Canonical JuJu apparently imports it. As a bonus, it is compatible with the [NaCl secretbox library][2], which is written in C and has multiple bindings for other languages. The interface is only two functions: `Open()` and `Seal()`, which operate on `[]byte`. I'm not sure how much we would need to implement from scratch to get the features we want, but this seems like a good start, or at least a candidate.

[1]: https://godoc.org/golang.org/x/crypto/nacl/secretbox
[2]: https://nacl.cr.yp.to/secretbox.html

**Comment by mtrmac** [comment]
Careful with NaCl or any other format inventions (including things that compose FIPS-acceptable primitives), if we want this to be FIPS-certifiable. (Even deciding what crypto package to use requires having, and keeping up with, cryptography, sadly.)

IIRC the vague consensus from recent discussions has been:
- Use system-provided keyrings / facilities to store secrets.
- Or maybe just use an _unencrypted_ plain-text file, explicitly not obfuscating anything, only providing a k8s-like feature to allow interoperating with k8s-targeted containers.
- Failing that, perhaps prompt interactively.

If I got it wrong, please correct me.

**Comment by mheon** [comment]
Initial prototype should be unencrypted. After that, we can look into encryption - best suggestion I heard was gnupg

**Comment by Radtoo** [comment]
pass/gopass and comparable tools could be great, just hand the password and other data from "pass show podman/container_id".

With a solution like it, you probably would have to mainly specify how you expect container secrets to be named, and whether you also support parsing additional YAML or TOML or whatever format data into additonal runtime relevant variables if present. The rest is probably just documentation.

**Comment by slewsys** [comment]
I am not familiar with k8s secrets, nor have I reviewed all the suggestions submitted above, so forgive me if this has been covered: [Mozilla sops](https://github.com/mozilla/sops).  The idea to store secrets in a JSON or YAML file whose keys remain unencrypted.  For instance, a secrets file uploaded to a repository might look like:

**Comment by ashley-cui** [comment]
Working on it, bot!!! slowly but surely

**Comment by vrothberg** [comment]
Note that it's not a hard requirement for 3.0.  If we get it into a following minor release (e.g., 3.1) that's cool :)

**Comment by rhatdan** [comment]
This does not look like it made it, moving back to 3.1 it is under heavy development.

**Comment by ashley-cui** [comment]
closed via https://github.com/containers/podman/pull/9125
