### ISSUE TITLE
Checkpoint/Restore failure with internal IPv6 connections

### ISSUE THREAD

**Issue by adrianreber** [containers/podman#3722]
There was a bug report in the CRIU bug tracker (https://github.com/checkpoint-restore/criu/issues/735) that checkpoint/restore did not work with docker because it lacks support for checkpointing restoring containers with established TCP connections. The failure happened during checkpointing.

I recommend to try out Podman and checkpointing works but restoring fails.

The reason for the failure is that the container, in this special case, uses internal IPv6 TCP connections. This TCP connections are bound to the link-local IPv6 address.

On restore Podman (CNI) currently creates a network namespace with the same IPv4 address the container had during checkpointing. IPv6 is ignored. This means a new IPv6 link-local IP address is used in the restored container and the restore of the established TCP connection fails.

The upcoming IPv6 support in Podman is probably a good starting point to add IPv6 addresses to the checkpoint so that they are restored correctly. As far as I understand it right now this will probably be not enough for the special case where the link-local IPv6 address is used by an application in the container. I still need to figure out the details.

I am assigning this to me. This is mainly as a reminder for me and that it is known and documented.

**Comment by rhatdan** [comment]
SGTM

**Comment by vrothberg** [comment]
Added the do-not-close label.

**Comment by rhatdan** [comment]
@adrianreber Any progress on this one?

**Comment by adrianreber** [comment]
Unfortunately no. Nothing from my side so far. Still planing to fix it.

**Comment by rhatdan** [comment]
@adrianreber ping

**Comment by rhatdan** [comment]
@adrianreber ping again

**Comment by rhatdan** [comment]
@adrianreber This issue is 1.5 years old, do you want to keep it open?

**Comment by adrianreber** [comment]
I will just close it. Nobody has been complaining about this in the last 1.5 years so it does not seem to be really important.
