### ISSUE TITLE
A way to regenerate firewall rules

### ISSUE THREAD

**Issue by matpen** [containers/podman#3842]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Under some circumstances the the sysadmin might want to clear the firewall rules entirely, thereby deleting the CNI-generated rules, too. With daemon-based runtimes (e.g. docker), these rules can be regenerated by restarting the daemon, but with podman I see no other way than manually restarting all containers. It would be handy to have a command to regenerate them, possibly without restarting the running containers.

**Steps to reproduce the issue:**

1. Clear firewall rules: e.g. 
```
iptables -t filter -F
iptables -t filter -X
iptables -t nat -F
iptables -t nat -X
```

2. Restart all containers to force regeneration of firewall rules

**Describe the results you received:**

There is no way to restore podman-generated rules.

**Describe the results you expected:**

A command to regenerate the rules without restarting the containers would be nice.

**Additional information you deem important (e.g. issue happens only occasionally):**

None.

**Output of `podman version`:**

```
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.0.0-rc2, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "18.04"
  MemFree: 123392000
  MemTotal: 1033375744
  OCIRuntime:
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 2066706432
  SwapTotal: 2066706432
  arch: amd64
  cpus: 1
  hostname: develop
  kernel: 4.15.0-58-generic
  os: linux
  rootless: true
  uptime: 29m 3.29s
registries:
  blocked: null
  insecure: null
  search: null
store:
  ConfigFile: /home/matteo/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/matteo/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /run/user/1000
  VolumePath: /home/matteo/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

None.

**Comment by mheon** [comment]
Likely will need CNI support. We could theoretically destroy and recreate
all networks in CNI, but I have no idea if that will actually do what we
want.

**Comment by baude** [comment]
Id want to talk this through before committing ... it is an interesting idea nevertheless.

**Comment by rhatdan** [comment]
Lets talk to the CNI guys.

**Comment by rhatdan** [comment]
@dcbw PTAL

**Comment by vrothberg** [comment]
Friendly ping. This issue is getting a bit dusty.

**Comment by mheon** [comment]
This is still important, but I think we need help from the CNI team to make it happen.

**Comment by rhatdan** [comment]
@dcbw @mccv1r0 Any comment?

**Comment by mccv1r0** [comment]
CNI doesn't store any info re firewall rules.  Everything is derived when plugin is invoked by a runtime (e.g. podman)

For cniADD, each plugin in a chain adds (or not) rules based on the type of plugin itself (bridge vs p2p) and how a given plugin is configured (masqurade or not).  At cniDEL time, same config is used to remove (or ignore already removed) rules.  

An entire new command, firewall specific, would probably need to be invented to "recreate just the iptables rules that were previously added".  I doubt upstream would have much use for this.

**Comment by mheon** [comment]
If we're willing to accept a temporary loss in connectivity, could we tear down and reconfigure (CNI delete then add) the network namespace for the container?

**Comment by mccv1r0** [comment]
> Likely will need CNI support. We could theoretically destroy and recreate all networks in CNI, but I have no idea if that will actually do what we want.

You would have to destroy and recreate all containers on a network.

**Comment by mccv1r0** [comment]
> If we're willing to accept a temporary loss in connectivity, could we tear down and reconfigure (CNI delete then add) the network namespace for the container?

Yes

**Comment by rhatdan** [comment]
@mheon This issue seems to be in many places?

**Comment by mheon** [comment]
I'll take this one. Just need to figure out a good name... `podman system reload-firewall`? `podman network reload`?

**Comment by rhatdan** [comment]
podman network reload, works for me.

**Comment by rhatdan** [comment]
@mheon Did you ever make any progress on this?

**Comment by mheon** [comment]
I actually have a (very neglected) PR open for this: https://github.com/containers/podman/pull/6545

I will try and get it completed.

**Comment by rhatdan** [comment]
@mheon any progress?

**Comment by mheon** [comment]
I got the command rebased and working in 2.1, but the issue blocking it remains - I can successfully tear down the old network, but CNI does not actually configure the network namespace again after that. I tracked the problem into CNI itself but haven't gotten further than that

**Comment by Luap99** [comment]
This was fixed in https://github.com/containers/podman/pull/8571. Podman now has the `podman network reload` command. The first release with this feature will be 3.0.
