### ISSUE TITLE
Podman volume parent directory created are owned by root when using --user and --uidmap

### ISSUE THREAD

**Issue by TristanCacqueray** [containers/podman#3977]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When mounting a configuration volume, the parent directory is owned by root, which prevent the container user from creating lateral configuration.

**Steps to reproduce the issue:**

1. Create user in image
`cid=$(buildah from registry.fedoraproject.org/fedora); buildah run $cid useradd -m user && buildah commit --rm $cid fedora-user`

2. Start the container
```
host$ podman run -it --rm --volume ~/.config/pavucontrol.ini:/home/user/.config/pavucontrol.ini --user 1000 --uidmap 1000:0:1 --uidmap 0:1:999 --uidmap 1001:1001:64535 fedora-user
[user@7246ce1da224 /]$ ls -la ~/.config
total 8
drwxr-xr-x. 2 root root 4096 Sep  9 20:14 .
drwx------. 3 user user 4096 Sep  9 20:14 ..
-rw-rw-r--. 1 user user    0 Sep  9 20:04 pavucontrol.ini
[user@7246ce1da224 /]$ mkdir ~/.config/pulseaudio
mkdir: cannot create directory ‘/home/user/.config/pulseaudio’: Permission denied
```

**Describe the results you received:**

Volume parent directory created by podman are not writable by the container user.

**Describe the results you expected:**

Volume parent directory should respect their parent owner uid or the volume target owner.

**Additional information you deem important (e.g. issue happens only occasionally):**

A solution is to pre-create the directory structure:

```
host$ mkdir -p /tmp/pavucontrol-container/.config
host$ chcon -R system_u:object_r:container_file_t:s0 /tmp/pavucontrol-container/
host$ podman run -it --rm --volume /tmp/pavucontrol-container:/home/user --volume ~/.config/pavucontrol.ini:/home/user/.config/pavucontrol.ini --user 1000 --uidmap 1000:0:1 --uidmap 0:1:999 --uidmap 1001:1001:64535 fedora-user
bash-5.0$ mkdir ~/.config/pulseaudio
bash-5.0$ ls -la ~/.config
total 12
drwxrwxr-x. 3 user user 4096 Sep  9 20:23 .
drwxrwxr-x. 3 user user 4096 Sep  9 20:21 ..
-rw-rw-r--. 1 user user    0 Sep  9 20:04 pavucontrol.ini
drwxr-xr-x. 2 user user 4096 Sep  9 20:23 pulseaudio
```

**Output of `podman version`:**

```
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.7
  podman version: 1.5.1
host:
  BuildahVersion: 1.10.1
  Conmon:
    package: podman-1.5.1-3.fc30.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.0, commit: d728afa06cd2df86a27f32a4692c7099a56acc97-dirty'
  Distribution:
    distribution: fedora
    version: "30"
  MemFree: 464338944
  MemTotal: 16815693824
  OCIRuntime:
    package: containerd.io-1.2.6-3.3.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc8
      commit: 425e105d5a03fabd737a126ad93d62a9eeede87f
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  eventlogger: file
  hostname: ocp.rdocloud
  kernel: 5.2.9-200.fc30.x86_64
  os: linux
  rootless: true
  uptime: 121h 59m 13.33s (Approximately 5.04 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /home/fedora/.config/containers/storage.conf
  ContainerStore:
    number: 9
  GraphDriverName: vfs
  GraphOptions: null
  GraphRoot: /home/fedora/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 37
  RunRoot: /tmp/1000
  VolumePath: /home/fedora/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.5.1-3.fc30.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The host is running in OpenStack

**Comment by mheon** [comment]
I'll take this one

**Comment by 12factor-mx** [comment]
Hello

Any progress?

**Comment by rhatdan** [comment]
@12factor-mx Interested in opening a PR?  @mheon has been off working on other issues/features...

**Comment by vrothberg** [comment]
Friendly ping. @mheon, do you have cycles to tackle this?

**Comment by mheon** [comment]
Will take a look today

**Comment by mheon** [comment]
We don't actually make these directories - they're created by the OCI runtime when it goes to finalize the container's rootfs and make bind mounts.

@giuseppe Poke - do you think this is something crun/runc should do?

**Comment by giuseppe** [comment]
could it be a security issue if two containers running with different `--user` use the same volume?

This is something that could be easily fixed by creating the directory before running the container with the correct permissions.

**Comment by rhatdan** [comment]
The source directory should always be created by the user, if using a volume.  We could add a flag to the volume when we start running in random User Namespace, for the container engine to "Chown" the directory.

**Comment by rhatdan** [comment]
@giuseppe Interested in opening a PR?

**Comment by rhatdan** [comment]
@ashley-cui Could you fix this bug.  Basically any directory created by podman within the container should match the parent directory.

In this case the podman is creating ~/.config/ as owned by root when it should have created it with the ownership of `~` "$HOME"

**Comment by rhatdan** [comment]
I don't think this is a bug.  I did the same thing on Docker and got the same results.

```
docker run -ti -v $PWD/Dockerfile:/test/Dockerfile --user bin fedora sh
sh-5.0$ id
uid=1(bin) gid=1(bin) groups=1(bin)
sh-5.0$ cd /test/
sh-5.0$ ls
Dockerfile
sh-5.0$ touch dan
touch: cannot touch 'dan': Permission denied
sh-5.0$ id
uid=1(bin) gid=1(bin) groups=1(bin)
```
