### ISSUE TITLE
Move container to pod

### ISSUE THREAD

**Issue by abitrolly** [containers/podman#3979]
/kind feature

Is it possible to move container into a pod? I want to expose container ports without killing it (#3949) and I thought that maybe moving it to a pod can accomplish this.

**Output of `podman version`:**
```
➜  ~ podman version
Version:            1.5.1
RemoteAPI Version:  1
Go Version:         go1.12.7
OS/Arch:            linux/amd64
```

**Comment by baude** [comment]
you cannot currently do this with podman. we have discussed being able to "add" a container with new ports to a pod but that feature is not implemented yet either.

**Comment by rhatdan** [comment]
You can add a container to an existing container my combining the namespaces.

**Comment by abitrolly** [comment]
@rhatdan you mean to existing pod? What is the command to combine namespaces?

**Comment by rhatdan** [comment]
Well all a pod is, is a bunch of containers sharing namespaces (and cgroups)

If I have an existing container and do

podman run --pid container:containerA --net container:containerA --ipc container:containerA ...

Then the two containers will basically work as a pod.

**Comment by mheon** [comment]
Actually explicitly restricted - you can only share namespaces with a container in a pod if you are part of the pod. Removal ordering issues - need to be able to remove a pod without leaving straggler containers that want to use its resources.

**Comment by abitrolly** [comment]
How does it work in the following user story.
1. I created container with PostgreSQL named **postcon**
```
$ podman run -d --name postcon postgres
```
2. I forgot to expose port 5432 to access the db, and instead of restarting container I decide to create a pod name **postpod** with exposed port, and more container there
```
$ podman pod create --name postpod -p 5432
```
3. Now I need to move the `postcon` container to `postpod` pod. Now it gets complicated.

`pod` is just a namespace and cgroup (that's on kernel level). `container` is in the `pod`, when its namespace is "combined" with `pod` namespace. `podman` doesn't expose interface for combining namespaces.

Is that right?

**Comment by rhatdan** [comment]
Yes, you can not add an existing container to a pod, because of the conflicts in namespaces, and cgroups.

**Comment by abitrolly** [comment]
Is it possible to detect those conflicts and resolve them one by one manually?

**Comment by mheon** [comment]
We've discussed a 'podman clone' command - copy an existing container and
make changes (like moving to a pod). That would be the easiest way forward
for this that I can see.

**Comment by abitrolly** [comment]
@mheon is it possible to make changes to container checkpoints that are used for live migrations https://criu.org/Podman ?

**Comment by mheon** [comment]
Not at present - but we'd probably use a similar mechanism for `podman clone`

**Comment by vrothberg** [comment]
Added the "do-not-close" label as I'm sure this is something worth adding.

**Comment by abitrolly** [comment]
If I make a checkpoint.
```
podman container checkpoint -l -e /tmp/chkpt.tar.gz
```
Why it is not possible to restore it inside a pod?

**Comment by adrianreber** [comment]
> If I make a checkpoint.
> 
> ```
> podman container checkpoint -l -e /tmp/chkpt.tar.gz
> ```
> 
> Why it is not possible to restore it inside a pod?

CRIU cannot handle this currently. If CRIU restores a process running in namespaces, CRIU currently also restores all namespaces. For Podman we introduced the possibility in CRIU to restore a container into an existing network namespace, because Podman uses CNI to create network namespaces and CRIU can now restore a container into an existing network namespace. To restore a process into an existing network namespace is the big difference between Podman's checkpoint/restore support and other container engines.

With this as background it should be possible to extend CRIU to restore a process (container) into an existing set of namespaces (a pod). But this requires work on the CRIU level, runc and Podman level. It is doable, but not something which is being worked on (at least from what I know from the CRIU point of view).

**Comment by rhatdan** [comment]
Is anyone working on this?  Planning to work on this?

**Comment by mheon** [comment]
It should be part of `podman container clone`, which nobody is actively working on. However, the work @baude is doing with create for APIv2 is making `clone` a lot closer than it once was.

**Comment by rhatdan** [comment]
@mheon Reminder.

**Comment by mheon** [comment]
I have cards for `podman container clone`, so hopefully this gets done this summer

**Comment by adrianreber** [comment]
Not sure what `clone` is exactly about, but I started to work on enabling restoring a container into an existing PID namespace: https://github.com/checkpoint-restore/criu/pull/1056

**Comment by rhatdan** [comment]
@mheon Should we merge a bunch of these issues together that requires `podman container clone`

**Comment by mheon** [comment]
@rhatdan Agree, that sounds like a good idea

**Comment by jmpolom** [comment]
The idea of a `podman clone` subcommand to re-instantiate a container in a pod, etc. is super interesting. Is there any hope that this might soon become a reality?

**Comment by giuseppe** [comment]
opened a PR: https://github.com/containers/podman/pull/13587
