### ISSUE TITLE
Preserve shared namespaces settings when creating pod from YAML.

### ISSUE THREAD

**Issue by mooncube** [containers/podman#4059]
/kind feature

**Description**

Is it possible to preserve --share option for pod when generating/playing pod's yaml file?

**Steps to reproduce the issue:**

```
$ podman pod create --share=pid -n test
$ podman run --pod=test -d alpine /usr/bin/top
$ podman run --pod=test -d alpine /usr/bin/tail -f
```

So, we have running pod with 3 containers and shared pid namespace.

```
$ podman generate kube test > test.yml
$ podman pod rm -f test
$ podman play kube test.yml
```

After that we have the same pod, but without pid namespace sharing.  

**Describe the results you received:**

pod, restored from definition file, does not preserve --share option. Pod's definition file does not contain any instructions to share namespace (ShareProcessNamespace: true may be?).

**Describe the results you expected:**

Containers from pod, created with --share=pid preserves shared pid namespace.

**Comment by mheon** [comment]
We'd need to figure out how to encode that in Kube YAML, which I'm 99% sure does not support this by default.

**Comment by haircommander** [comment]
it is possible!
/assign

**Comment by mheon** [comment]
Still a feature we want

**Comment by rhatdan** [comment]
@haircommander Have you thought about this or worked on it at all?

**Comment by rhatdan** [comment]
@ryanchpowell PTAL

**Comment by rhatdan** [comment]
@haircommander If you don't have time to work on this, could you at least document what needs to be done?

**Comment by haircommander** [comment]
wow, a whole year has gone by. Yeah I'll either tackle this or document what needs to be done
