### ISSUE TITLE
Support "podman-remote cp"

### ISSUE THREAD

**Issue by sshnaidm** [containers/podman#4207]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Add support for `podman-remote` to copy files from/to containers.

**Describe the results you expected:**
```
podman-remote cp /local_path/file container:/path/file
podman-remote cp container:/path/file /local_path/file
```

**Additional information you deem important (e.g. issue happens only occasionally):**

It will unblock remote containers execution in ansible podman plugin: https://github.com/ansible/ansible/pull/63166

**Comment by rhatdan** [comment]
This is still being worked and definitely something we want.

**Comment by vrothberg** [comment]
> This is still being worked and definitely something we want.

@rhatdan, still valid with the new v2 API coming?

**Comment by rhatdan** [comment]
Well we want it in V2 API.

**Comment by vrothberg** [comment]
> Well we want it in V2 API.

Note that the request mentions varlink explicitly.

**Comment by sshnaidm** [comment]
> > Well we want it in V2 API.
> 
> Note that the request mentions varlink explicitly.

I think you can easily remove "varlink" from the description. The main goal is to have it remotely, no matter with which API

**Comment by vrothberg** [comment]
> I think you can easily remove "varlink" from the description. The main goal is to have it remotely, no matter with which API

Perfect! I did that and assigned @baude who is the driving force behind the new v2 API.

**Comment by rhatdan** [comment]
Yes this will be done in V2.

**Comment by afbjorklund** [comment]
I used the following workaround, for missing remote functionality:

`podman cp /foo container:/bar `--> `podman-remote exec -i container tee /bar < /foo`

Even if it is fixed in Podman 2.0, clients will be older 1.x for a while.

We will still use the regular "cp" command, when running locally.

**Comment by rhatdan** [comment]
This is still being worked.

**Comment by rhatdan** [comment]
@sshnaidm @afbjorklund @vrothberg @baude Where are we on this one?  We now have API V2 and podman cp should be using it.

**Comment by afbjorklund** [comment]
Here is what I get, with podman-remote 2.0.6/podman 2.0.5:

```
 podman-remote cp /tmp/foo focused_knuth:foo
Error: unrecognized command `podman-remote cp`
Try 'podman-remote --help' for more information.
 podman --remote cp /tmp/foo focused_knuth:foo
Error: unrecognized command `podman cp`
Try 'podman --help' for more information.
```

Installing latest/greatest podman 2.0.6 (from koji) didn't help...

**Comment by afbjorklund** [comment]
There are some weird `ABIMode` and `TunnelMode` constants.

And the "cp" command only has the ABIMode, assume that is local ?

**Comment by mheon** [comment]
@rhatdan I was in the early stages of implementing this one before we went bugs-only

**Comment by rhatdan** [comment]
Ok sorry I thought we were further along.

**Comment by rhatdan** [comment]
@jwhonce I think we need you to handle this one.

**Comment by holser** [comment]
Hi,

It would be nice to get this feature done, allowing operators to build images using Dockerfiles from their workstations rather than jumping in to servers to build image. This feature will make podman more development friendly, IMHO

**Comment by vrothberg** [comment]
Thanks for reaching out, @holser.  I am currently working on it.  It's only a matter of polishing a couple of things.

**Comment by vrothberg** [comment]
The PR is merged, closing

**Comment by afbjorklund** [comment]
Having limited success, but whatever.

```
 ./bin/podman-remote run -d busybox sleep 3600
ERRO[0000] The storage 'driver' option must be set in /etc/containers/storage.conf, guarantee proper operation. 
1e0db3943cd8d75fcfa1656afc847a232b687a02f3ae05f2b24a723bc0b07cf3
 ./bin/podman-remote cp /tmp/foo infallible_cannon:foo
ERRO[0000] The storage 'driver' option must be set in /etc/containers/storage.conf, guarantee proper operation. 
Error: "foo" could not be found on container infallible_cannon: 405 Method Not Allowed
```

Not sure where this 405 is coming from

**Comment by vrothberg** [comment]
Glad it works for you, @afbjorklund :+1:
