### ISSUE TITLE
Provide arm64 multiarch images on quay.io

### ISSUE THREAD

**Issue by everflux** [containers/podman#4773]
/kind feature

**Description**

Currently only amd64 images are available for podman and buildah on 
quay.io/podman/stable
This prevents usage on ARM64 architectures.
Please provide multi-arch images and according manifests.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat PTAL

**Comment by rhatdan** [comment]
@everflux Any help you could provide, IE Opening a PR, would help move this along.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Any chance to look at this?  @nalind could you help with this?

**Comment by MaxPeal** [comment]
+1

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Could you take a look?

**Comment by TomSweeneyRedHat** [comment]
I'm happy to look, but I've not a clue on where to start.  I'll have to dig deeply into Google.  Pointers gratefully accepted.

**Comment by rhatdan** [comment]
I was hoping @cevich could jump in an offer up a way to do this on CIRRUS.  Basically we need an arm64 vm with buildah/go ... installed, and have it build the images.  Once we have images built for different arches, we need something to reassemble them into a manifest, I believe.

**Comment by rhatdan** [comment]
Perhaps @nalind has some ideas.

**Comment by cevich** [comment]
I'm happy to advise, but there are no ready-to-go options here.  Non-commodity hardware is a big ask for every cloud-provider.  I'm told even the IBM cloud tightly controls ppc64 :confounded: We're really beholden to the cloud-providers here if we want something automated and public.

I did open up:

https://github.com/containers/automation_images/pull/21

That image has nested-virt. enabled.  My main concern is performance; however,  It's worth investigating further as this may actually be the most-viable option.  Test/play with qemu-kvm using `hack/get_ci_vm fedora-c4566280017543168`  should work as per usual, though you will need to install qemu-kvm.  Ref: https://wiki.qemu.org/Documentation/Platforms/ARM

The only other idea I have is to work with cirrus-support to get a job running in AWS, which offers ARM VMs (when special-magic incantations are uttered).  This is a long/hard road, as I have almost zero knowledge of AWS nor do we have any VM-image build setup.

**Comment by rhatdan** [comment]
@nalind is this something you could attempt with your presentation from Devconf.cz?

**Comment by nalind** [comment]
I believe so.  There are some things ahead of it in my to-do list, though.

**Comment by rhatdan** [comment]
I have been told that the SUSE build servers might be a possibility for this?

**Comment by nalind** [comment]
If I'm reading https://en.opensuse.org/openSUSE:Build_Service_supported_build_targets#Supported_processor_platforms right, it'd be broader than what we have now.

**Comment by ppouliot** [comment]
Hey Everyone,

If you are looking for ARM64 vm resources for the project.  Feel free to send a request here.   OpenStack API access can be provided.

https://osuosl.org/services/aarch64/request_hosting/

**Comment by woodrad** [comment]
I don't know enough to meaningfully contribute to this issue, but lacking a rootless CNI image on quay.io makes it difficult to use rootless podman on popular aarch64 devices like the Raspberry Pi. I am willing to write howto documentation, for what it's worth.

**Comment by rhatdan** [comment]
I have opened a PR on Buildah to make building these images via emulation a lot easier.

https://github.com/containers/buildah/pull/2869

**Comment by rhatdan** [comment]
Buildah can now build multi-arch images.  Now we just need to setup something to push them.
@vrothberg @lsm5 Is this something to do on OBS?  Can we setup a cron job to build and push images from there?

**Comment by rhatdan** [comment]
@cevich Now that we have support for this with Buildah, can we do similar for Podman

**Comment by cevich** [comment]
Ya, I can more/less copy-paste the github action (I don't 100% understand how build-x works).  What are the FQIN's you'd like built and pushed when *master* changes?

**Comment by cevich** [comment]
Created Jira card RUN-1188

**Comment by TomSweeneyRedHat** [comment]
@cevich I can't get into Jira at the moment for some reason.  I don't know if you as the conversation with @barthy1 in the Buildah repo, but we need to create the `podman/stable:{version}` and `containers/podman:{version]` tags one  and only one time.  If that means we need to do that "by hand" as we have been doing, I'm fine with that.  https://github.com/containers/buildah/pull/3059

**Comment by cevich** [comment]
okay.  My plan was to use the buildah workflow as a starting place, so I'll keep that in mind.

**Comment by cevich** [comment]
Thanks for the friendly reminder.

**Comment by rhatdan** [comment]
Don't we have something for this on Buildah now?  @TomSweeneyRedHat ?

**Comment by cevich** [comment]
Yes, I have a jira card to employ the buildah method on the podman repo.

**Comment by cevich** [comment]
working on this now

**Comment by georgettica** [comment]
To make sure I am not butchering something..
Does quay allow arm64 deployment?
https://www.reddit.com/r/kubernetes/comments/uzvozb/_/

**Comment by rhatdan** [comment]
Yes I am almost certain we store arm64 images on quay.

**Comment by georgettica** [comment]
@rhatdan can you comment on the thread then with the details?

**Comment by rhatdan** [comment]
@cevich ANy reason we can't support that arch?

**Comment by cevich** [comment]
Confirmed, we're build `arm64`, I just checked using `skopeo inspect --raw ...`. Though builds are broken since F36 dropped with [a fix coming very soon](https://github.com/containers/podman/pull/14437).
