### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by mheon** [containers/podman#4854]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Podman's debug-level logs are starting to get out of hand. We've been abusing the DEBUG level for everything that is below WARN, ignoring the INFO and TRACE levels entirely, and it's seriously affecting readability of our logs. Further, we should investigate improvements to log tagging if a debug-level log is printed; including the part of the project the log originated from (libpod, containers/storage, etc) would aid clarity significantly, as would including filename and line number in the printed logs.

**Steps to reproduce the issue:**

1. `podman run --log-level=debug -t -i --rm fedora bash`

**Describe the results you received:**

A massive block of mostly-undifferentiated text which makes it very difficult to tell what's going on

**Describe the results you expected:**

Differentiated logging levels that allow me to easily tell when critical operations happen via INFO logs, and omit minute debugging information that would should only be in TRACE logs.

**Comment by baude** [comment]
@mheon make a card and lets remove from here. wdyt ?

**Comment by rhatdan** [comment]
@mheon did you make a card?

**Comment by mheon** [comment]
I'll make a card, but I'd prefer not to close this. This could easily be taken by a community contributor.

**Comment by rhatdan** [comment]
@sujil02 Could you investigate this?  At least look at cleaning up a some of the Warning messages.

**Comment by sujil02** [comment]
Hi, @mheon @rhatdan I looked into this. Understanding through the regular stack trace I retagged a bunch load of debug messages that referred to using or creating resources to Info level.

Referring to the log tagging with the file name and line number,  Logrus does support this however enabling it kind of clutters the logs messages with a lot of text. I suggest adding a flag for the --log-level to explicitly enable it is that a wise option?  wdyt Need opinions?

**Comment by rhatdan** [comment]
@sujil02 Please hand this over to @ParkerVR 
I want to get to the point of running by default at level Warning.

**Comment by sujil02** [comment]
> Hi, @mheon @rhatdan I looked into this. Understanding through the regular stack trace I retagged a bunch load of debug messages that referred to using or creating resources to Info level.
> 
> Referring to the log tagging with the file name and line number, Logrus does support this however enabling it kind of clutters the logs messages with a lot of text. I suggest adding a flag for the --log-level to explicitly enable it is that a wise option? wdyt Need opinions?

@ParkerVR  Most of my findings are discussed here probably this branch might help to understand it better [https://github.com/sujil02/libpod/tree/improve-logging](url). Let's connect to get going with this further.

**Comment by rhatdan** [comment]
@ParkerVR Any movement on this?

**Comment by ParkerVR** [comment]
@rhatdan I will get to this soon after we are out of bug phase

**Comment by rhatdan** [comment]
This is still something we want, but know one has stepped up to work on it.

**Comment by rhatdan** [comment]
Still something we would like to get done, if someone from community wants to help it would be nice.

**Comment by weirdwiz** [comment]
If someone isn't working on this, I would like to take this issue.

**Comment by vrothberg** [comment]
> If someone isn't working on this, I would like to take this issue.

Great, thanks!  It's all yours :)

Please make sure to split the changes into small commits.  That'll help reviewing, reverting, back porting etc.

**Comment by rhatdan** [comment]
@weirdwiz Any progress?

**Comment by weirdwiz** [comment]
I've made some changes, couldn't focus on it for a few weeks. I'll update the pull request soon.

**Comment by weirdwiz** [comment]
I had a couple questions while moving ahead with this issue.

- Should a trace level be added for the more granular logs?
- What would a be a good criteria to identify which log should go in the trace level or the debug level?
- Should the identifying information i.e. filename, line number, the repository of origin be added in the trace level instead of the debug level?

**Comment by rhatdan** [comment]
The only time we have talked about trace level was when it came to containers/image and its communications with the remote registries. Basically to trace the http connections.  The connections can contain Passwords, so we don't want them written to the logs by mistake.

**Comment by vrothberg** [comment]
I think that the main goal is to reduce the noise in the logs.  There are a lot of logs on INFO or DEBUG that provide little to no value other to the person debugging a specific issue.  Such things should IMHO be moved to TRACE.

There is a number of candidates when running even a simple command such as `podman --log-level=debug info`:
* `DEBU[0000] Called info.PersistentPreRunE(podman --log-level=debug info)` 
  * This one is printed _every time_ and doesn't provide value IMHO.  We might even remove it.
* `DEBU[0000] Merged system config [...]`
 * Way too much noise, absolutely not human-readable. Should be tackled in `containers/common`.

```
DEBU[0000] using runtime "/usr/bin/runc"
INFO[0000] Error initializing configured OCI runtime kata: no valid executable found for OCI runtime kata: invalid argument
DEBU[0000] using runtime "/usr/bin/crun"
```
That's printed multiple times and is very misleading.  We're actually _looking for_ the runtime, not using it.  Then, there's a mix of DEBUG and INFO.  What IMHO should be on INFO is the runtime that is actually being used, the remainder of the logs should go into TRACE.

There will be more cases but I hope that will help develop a gut feeling for what things we can improve.

**Comment by rhatdan** [comment]
I got a couple of fixes in for this, are there other priorities you see?

**Comment by vrothberg** [comment]
Reopening for the community as @weirdwiz ran short of time (https://github.com/containers/podman/pull/9017#issuecomment-841164033).

**Comment by vrothberg** [comment]
We've made quite some improvements since then, especially @rhatdan was very active.

I am going to close this as it's hard to quantify and something we should always care about.
