### ISSUE TITLE
CI flakes with podman-login

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#5212]
I hit podman-login flakes quite frequently in the passed which suggests to have a look at it and track down potential sources for the flakes.

[+1077s] [Fail] Podman login and logout [BeforeEach] podman login and logout with flag --authfile 
[+1077s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/login_logout_test.go:58
[+1077s] 
[+1077s] [Fail] Podman login and logout [It] podman login and logout 
[+1077s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/login_logout_test.go:101
[+1077s] 
[+1077s] [Fail] Podman login and logout [It] podman login and logout with --tls-verify 
[+1077s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/login_logout_test.go:157
[+1077s] 
[+1077s] [Fail] Podman login and logout [It] podman login and logout with flag --authfile 
[+1077s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/login_logout_test.go:135
[+1077s] 
[+1077s] [Fail] Podman login and logout [It] podman login and logout 
[+1077s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/login_logout_test.go:105
[+1077s] 
[+1077s] [Fail] Podman login and logout [It] podman login and logout with flag --authfile 
[+1077s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/login_logout_test.go:135
[+1077s] 
[+1077s] [Fail] Podman login and logout [It] podman login and logout 
[+1077s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/login_logout_test.go:105
[+1077s] 
[+1077s] [Fail] Podman login and logout [It] podman login and logout with --cert-dir 
[+1077s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/login_logout_test.go:177
[+1077s] 
[+1077s] [Fail] Podman login and logout [It] podman login and logout with --cert-dir 
[+1077s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/login_logout_test.go:177
[+1077s] 
[+1077s] [Fail] Podman login and logout [It] podman login and logout with --cert-dir 
[+1077s] /var/tmp/go/src/github.com/containers/libpod/test/e2e/login_logout_test.go:177

**Comment by rhatdan** [comment]
@vrothberg Any movement on this issue?

**Comment by vrothberg** [comment]
Not to my knowledge, no.

**Comment by rhatdan** [comment]
@vrothberg Is this still an issue or can we close?

**Comment by vrothberg** [comment]
Haven't seen them in a while. Much of the code has changed.

**Comment by edsantiago** [comment]
Reopening. cirrus-flake-xref is reporting a *ton* of these, most recently on July 6:

Podman login and logout [It] podman login and logout with --tls-verify
* fedora-30 : test fedora-30
  * PR #6424
    * [05-28 19:41](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5278045802070016/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--1)
    * [05-28 19:41](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5278045802070016/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--2)
    * [05-28 19:41](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5278045802070016/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--3)
* fedora-31 : in-podman fedora-31
  * PR #6838
    * [07-02 10:38](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5944867819880448/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--1)
    * [07-02 10:38](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5944867819880448/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--2)
    * [07-02 10:38](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5944867819880448/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--3)
  * PR #6516
    * [06-09 12:42](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6408321802436608/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--1)
    * [06-09 12:42](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6408321802436608/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--2)
    * [06-09 12:42](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6408321802436608/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--3)
* fedora-31 : test fedora-31
  * PR #6727
    * [06-23 10:49](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5897685926412288/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--1)
    * [06-23 10:49](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5897685926412288/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--2)
    * [06-23 10:49](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5897685926412288/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--3)
  * PR #6356
    * [05-26 15:20](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6086469980782592/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--1)
    * [05-26 15:20](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6086469980782592/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--2)
    * [05-26 15:20](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6086469980782592/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--3)
* fedora-32 : in-podman fedora-32
  * PR #6826
    * [06-30 12:21](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4893293060292608/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--1)
* [06-30 12:21](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4893293060292608/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--2)
    * [06-30 12:21](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4893293060292608/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--3)
  * PR #6736
    * [07-02 03:17](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5996766996725760/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--1)
    * [07-02 03:17](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5996766996725760/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--2)
    * [07-02 03:17](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5996766996725760/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--3)
* fedora-32 : test fedora-32
  * PR #6790
    * [07-03 16:16](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5771283226951680/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--1)
    * [07-03 16:16](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5771283226951680/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--2)
    * [07-03 16:16](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5771283226951680/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--3)
  * PR #6552
    * [06-10 10:27](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5803140240900096/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--1)
    * [06-10 10:27](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5803140240900096/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--2)
    * [06-10 10:27](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5803140240900096/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--3)
  * PR #6476
    * [06-03 09:46](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5348582687506432/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--1)
    * [06-03 09:46](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5348582687506432/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--2)
    * [06-03 09:46](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5348582687506432/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--3)
* ubuntu-19 : test ubuntu-19
  * PR #6859
    * [07-06 07:00](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6701373762830336/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--1)
    * [07-06 07:00](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6701373762830336/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--2)
    * [07-06 07:00](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6701373762830336/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--3)
  * PR #6794
    * [06-29 10:59](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6259846829834240/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--1)
    * [06-29 10:59](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6259846829834240/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--2)
    * [06-29 10:59](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6259846829834240/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--3)
  * PR #6520
    * [06-08 14:28](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5468676373610496/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--1)
    * [06-08 14:28](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5468676373610496/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--2)
    * [06-08 14:28](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5468676373610496/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--3)
* ubuntu-20 : test ubuntu-20
  * PR #6727
    * [06-23 10:49](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6460635879833600/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--1)
    * [06-23 10:49](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6460635879833600/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--2)
    * [06-23 10:49](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6460635879833600/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--3)
  * PR #6648
    * [06-17 12:49](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5826397891461120/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--1)
    * [06-17 12:49](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5826397891461120/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--2)
    * [06-17 12:49](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5826397891461120/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--3)
  * PR #6546
    * [06-10 06:30](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6635798604808192/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--1)
    * [06-10 06:30](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6635798604808192/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--2)
    * [06-10 06:30](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6635798604808192/html/integration_test.log.html#t--podman-login-and-logout-with---tls-verify--3)

As best I can tell, the common factor is:
```
Error: error authenticating creds for "localhost:5002": error creating new docker client: error loading registries: error loading registries configuration "test/registries.conf": open test/registries.conf: no such file or directory
```
The string `error creating new docker client` appears only in [vendor/github.com/containers/image/v5/docker/docker_client.go](https://github.com/containers/podman/blob/master/vendor/github.com/containers/image/v5/docker/docker_client.go), in two places: [CheckAuth](https://github.com/containers/podman/blob/master/vendor/github.com/containers/image/v5/docker/docker_client.go#L291) and [SearchRegistry](https://github.com/containers/podman/blob/master/vendor/github.com/containers/image/v5/docker/docker_client.go#L354).

Near I can tell, the string `test/registries.conf` is (possibly?) being set in [test/e2e/libpod_suite_test.go](https://github.com/containers/podman/blob/master/test/e2e/libpod_suite_test.go), possibly as the environment variable `REGISTRIES_CONFIG_PATH`. What I can't tell is if `INTEGRATION_ROOT` is empty or if `p.TempDir` is set to `test`, so I can't follow the code flow. 

I've spent too long on this without getting anywhere; will trust that the above links will help someone track it down quickly.

**Comment by rhatdan** [comment]
@mtrmac Thoughts?

**Comment by mtrmac** [comment]
Starting with “no such file or directory” being true as written, `INTEGRATION_ROOT` being empty is a good hypothesis.

I have very little experience with Ginkgo; reading https://onsi.github.io/ginkgo/#parallel-specs , ginkgo parallel tests apparently run in separate _processes_, not threads/goroutines, so https://github.com/containers/podman/blob/b1cc781c68964dff3ee4a00ef7ce71f56ae69e7c/test/e2e/common_test.go#L103 runs in only one of the processes and does not affect the others; so, the test fails if it is run in one of the other processes.

If this absolutely untested guess were correct, a quick could be copying the above line to the https://github.com/containers/podman/blob/b1cc781c68964dff3ee4a00ef7ce71f56ae69e7c/test/e2e/common_test.go#L154 function as well. A good fix would probably be different.

**Comment by edsantiago** [comment]
Still flaking. PR #6903 and #7024 this time.

#### in-podman fedora-31 fedora-31

  2020-07-15T08:03:14  [integration_test](https://api.cirrus-ci.com/v1/task/5680780816941056/logs/integration_test.log)
*   Podman login and logout [It] podman login and logout with flag --authfile
  *   [same]
*   Podman login and logout [It] podman login and logout with --tls-verify
*   Podman login and logout [It] podman login and logout with flag --authfile
*   Podman login and logout [It] podman login and logout with --tls-verify
  *   [same]
*   Podman run networking [It] podman run network expose duplicate host port results in error

Could someone ginkgo-savvy please look into this? If noone else responds, I'll try @mtrmac's suggestion later this week.
