### ISSUE TITLE
APIv2: containers/create does not call Init 

### ISSUE THREAD

**Issue by schubter** [containers/podman#5260]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

creating a container via the API does create the container, but isn't created  in the OCI runtime
thus attaching to the container does not work.

**Steps to reproduce the issue:**

1. create a container via the api

2. try to attach to the created container

**Describe the results you received:**

attach works

**Describe the results you expected:**

`Request Failed(Internal Server Error): can only attach to created or running containers: container state improper `

**Output of `podman version`:**

```
Version:            1.8.1-dev
RemoteAPI Version:  1
Go Version:         go1.12.17
Git Commit:         1bed53b02c2f65ba26dc320a797c6fe473fce9a1-dirty
Built:              Wed Feb 19 11:14:11 2020
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: 1bed53b02c2f65ba26dc320a797c6fe473fce9a1-dirty
  go version: go1.12.17
  podman version: 1.8.1-dev
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.10, commit: unknown'
  Distribution:
    distribution: debian
    version: "10"
  MemFree: 735125504
  MemTotal: 4138446848
  OCIRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0~rc6+dfsg1
      commit: 1.0.0~rc6+dfsg1-3
      spec: 1.0.1
  SwapFree: 2897207296
  SwapTotal: 4138442752
  arch: amd64
  cpus: 2
  eventlogger: journald
  hostname: hst-m04.dc.burg-1.de
  kernel: 4.19.0-6-amd64
  os: linux
  rootless: false
  uptime: 1981h 3m 39.01s (Approximately 82.54 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 3
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 25
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

i have implemented ctr.Init before returning the container response in CreateContainer, that seems to do the trick. I am not sure tho if that's the desired way to do it.
If it is, please let me know. and I will open a PR.

**Comment by vrothberg** [comment]
This looks like an typo in the error message `can only attach to created or running containers: container state improper`; we can only attach to running containers. @mheon WDYT?

**Comment by schubter** [comment]
the error is fine, attaching to created containers too.
I've fixed it with

```
if err := ctr.Init(r.Context()); err != nil {
		utils.Error(w, "Something went wrong.", http.StatusInternalServerError, errors.Wrap(err, "ContainerInit()"))
		return
	}
```

above https://github.com/containers/libpod/blob/master/pkg/api/handlers/containers_create.go#L75

and attaching via the api, works like I expected it to.
i am however not sure if that's the intended design

**Comment by mheon** [comment]
Init should happen automatically in start - see `prepareToStart()` (https://github.com/containers/libpod/blob/master/libpod/container_internal.go#L767-L777). What we're probably seeing here is an incorrect state check somewhere in the handler code, which an Init is working around by changing the state of the container.

**Comment by schubter** [comment]
As I have understood It this is somewhat replicating the docker api and from what I gathered from things like gitlab-runner it expects the container to be fully created as it attachtes right after to inject some things and then starts the container with a custom command. 

With the lines above gitlab-runner does get pretty far now, not all the way there yet but it can create, pull, attach, kill and stop. 

Maybe @baude can give more insight.

**Comment by rhatdan** [comment]
@schubter @mheon Is this still an issue, or should it be closed?

**Comment by schubter** [comment]
yes, created containers via the api cannot be interacted with, ie attached to as they are not initialized in the runtime.

**Comment by jgallucci32** [comment]
I am unable to get this behavior to work with Docker. Both Podman and Docker behave the same way (cannot attach to container when using the API).

I ran this command using Docker 1.13 and the container cannot be attached
```
curl --unix-socket /var/run/docker.sock -H "Content-Type: application/json" \
  -d '{"Image": "docker.io/library/busybox:latest"}' \
  -X POST http:/v1.24/containers/create?name=busybox

curl --unix-socket /var/run/docker.sock -X POST http:/v1.24/containers/busybox/start
```

**Comment by psakar** [comment]
I have different example where APIv2 behaves differently compared to docker / CLI

Docker
CLI
```
docker create --interactive --tty -p 61616:61616 --name activemq docker.io/rmohr/activemq:5.15.9-alpine
docker start activemq
sleep 10
docker logs activemq
docker inspect activemq > /tmp/test-activemq-docker.txt
docker stop activemq
docker rm activemq 
```

REST

```
curl --unix-socket /var/run/docker.sock -X POST -H "Content-Type: application/json" 'http://127.0.0.1:8880/containers/create?name=activemq' --data '{"name":"activemq", "Image":"docker.io/rmohr/activemq:5.15.9-alpine", "ExposedPorts": { "61616/tcp": {} }, "HostConfig": { "PortBindings": { "61616/tcp": [{ "HostPort": "" }] } } }'
curl --unix-socket /var/run/docker.sock -X POST -H "Content-Type: application/json" 'http://127.0.0.1:8880/containers/activemq/start'
sleep 10
curl --unix-socket /var/run/docker.sock --output - -H "Content-Type: application/json" "http://127.0.0.1:8880/containers/activemq/logs?stdout=true&stderr=true"
docker logs activemq
docker inspect activemq > /tmp/test-activemq-docker-api.txt
curl --unix-socket /var/run/docker.sock -X POST -H "Content-Type: application/json" 'http://127.0.0.1:8880/containers/activemq/stop'
curl --unix-socket /var/run/docker.sock -X DELETE -H "Content-Type: application/json" 'http://127.0.0.1:8880/containers/activemq'
```

Podman
CLI

```
podman create --interactive --tty -p 61616:61616 --name activemq docker.io/rmohr/activemq:5.15.9-alpine
podman start activemq
sleep 10
podman logs activemq
podman inspect activemq > /tmp/test-activemq-docker.txt
podman stop activemq
podman rm activemq 
```

REST

```
podman --log-level=debug system service -t 0 tcp:localhost:8880 2>&1>/tmp/podman-rest.log &

curl -X POST -H "Content-Type: application/json" 'http://127.0.0.1:8880/containers/create?name=activemq' --data '{"name":"activemq", "Image":"docker.io/rmohr/activemq:5.15.9-alpine", "ExposedPorts": { "61616/tcp": {} }, "HostConfig": { "PortBindings": { "61616/tcp": [{ "HostPort": "" }] } } }'
curl -X POST -H "Content-Type: application/json" 'http://127.0.0.1:8880/containers/activemq/start'
sleep 10
curl --output - -H "Content-Type: application/json" "http://127.0.0.1:8880/containers/activemq/logs?stdout=true&stderr=true"
podman logs activemq
podman inspect activemq > /tmp/test-activemq-docker-api.txt
curl -X POST -H "Content-Type: application/json" 'http://127.0.0.1:8880/containers/activemq/stop'
curl -X DELETE -H "Content-Type: application/json" 'http://127.0.0.1:8880/containers/activemq'
```


Please notice that REST log contains only "/bin/sh: bin/activemq: not found" instead of "INFO | ..." in other cases.

**Comment by psakar** [comment]
@mheon Please would you check the case in the above comment ? It blocks use of testcontainers with podman

**Comment by mheon** [comment]
How does it behave differently? Can you provide details?

**Comment by psakar** [comment]
It is described in the comment https://github.com/containers/podman/issues/5260#issuecomment-668127624 - it contains full reproducer.
Basically the container does not start properly because working directory is not set (and possibly other few things)

**Comment by mheon** [comment]
I'm 99% sure that the original issue here (Init not being called) has been resolved. These sound like separate issues?

Can you file separate issues for each thing you're seeing?

**Comment by psakar** [comment]
Sure, I'll do, thanx for looking into it

**Comment by mheon** [comment]
I'm going to close this one - Init is definitely called as part of start now.
