### ISSUE TITLE
Can't start a container while a push operation is in progress

### ISSUE THREAD

**Issue by jlebon** [containers/podman#5356]
Was trying to push a container image to quay.io and in a separate terminal I tried to start a container based on it. The start operation blocked without any apparent feedback in the terminal or the journal. Cancelling the push allowed me to create it.

Some kind of locking I suppose? If so, seems like they should be using shared lock?

**Comment by mheon** [comment]
I wonder if this is the c/storage locking that @saschagrunert has been trying to work around with https://github.com/containers/storage/pull/473

**Comment by saschagrunert** [comment]
If starting containers does not need write access to layers then we could solve it with https://github.com/containers/storage/pull/473. If not, then we can still solve this issues with layer-wise storage locking.

**Comment by rhatdan** [comment]
This is still being worked on.

**Comment by rhatdan** [comment]
@saschagrunert Still working on this?

**Comment by saschagrunert** [comment]
Yep this still depends on https://github.com/containers/storage/pull/473

**Comment by rhatdan** [comment]
Still waiting.  @nalind WDYT, Can we finally get the containers/storage update?

**Comment by rhatdan** [comment]
We are getting closer on this.

**Comment by rhatdan** [comment]
Sadly still in a holding pattern on this.

**Comment by vrothberg** [comment]
https://github.com/containers/image/pull/1167 has addressed the issue.
