### ISSUE TITLE
`podman update` is missing

### ISSUE THREAD

**Issue by kolyshkin** [containers/podman#5763]
/kind feature

**Description**

`podman update` is missing

**Steps to reproduce the issue:**

```console
$ podman update
$ podman container update
```

**Describe the results you received:**

```console
$ podman update
Error: unrecognized command `podman update`
Try 'podman --help' for more information.
$ podman container update
Error: unrecognized command `podman container update`
Try 'podman container --help' for more information.
```

**Describe the results you expected:**
```console
kir@ubuntu1910:~$ docker update   
"docker update" requires at least 1 argument.
See 'docker update --help'.

Usage:  docker update [OPTIONS] CONTAINER [CONTAINER...]

Update configuration of one or more containers
kir@ubuntu1910:~$ docker update --help

Usage:	docker update [OPTIONS] CONTAINER [CONTAINER...]

Update configuration of one or more containers

Options:
      --blkio-weight uint16        Block IO (relative weight), between 10 and 1000, or 0
                                   to disable (default 0)
      --cpu-period int             Limit CPU CFS (Completely Fair Scheduler) period
      --cpu-quota int              Limit CPU CFS (Completely Fair Scheduler) quota
      --cpu-rt-period int          Limit the CPU real-time period in microseconds
      --cpu-rt-runtime int         Limit the CPU real-time runtime in microseconds
  -c, --cpu-shares int             CPU shares (relative weight)
      --cpus decimal               Number of CPUs
      --cpuset-cpus string         CPUs in which to allow execution (0-3, 0,1)
      --cpuset-mems string         MEMs in which to allow execution (0-3, 0,1)
      --kernel-memory bytes        Kernel memory limit
  -m, --memory bytes               Memory limit
      --memory-reservation bytes   Memory soft limit
      --memory-swap bytes          Swap limit equal to memory plus swap: '-1' to enable
                                   unlimited swap
      --pids-limit int             Tune container pids limit (set -1 for unlimited)
      --restart string             Restart policy to apply when a container exits
kir@ubuntu1910:~$ 
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```console
$ podman --version
podman version 1.8.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```console
$ rpm -q podman
podman-1.8.2-2.fc31.x86_64
```

**Additional details:**

* https://docs.docker.com/engine/reference/commandline/update/

**Comment by mheon** [comment]
This is deliberate. Podman containers are, by design, immutable once created.

There has been extensive discussion of a way to clone containers (`podman container clone`) to produce an identical copy with changes, which would act somewhat similar to `update`. No one's found the time to implement it yet, though.

**Comment by kolyshkin** [comment]
> This is deliberate

Would be nice to have it documented/stated somewhere (say output of `podman update`).

> Podman containers are, by design, immutable once created

The resource limits can still be changed using `runc update`, `systemctl set property`, or directly writing into cgroup files. Not implying it was a bad decision, just thinking out loud.

**Comment by mheon** [comment]
> > This is deliberate
> 
> Would be nice to have it documented/stated somewhere (say output of `podman update`).
>

Sure - I'd want to hide the command so it doesn't seem like `update` is a real command that is ready to use, but we can make it output an error to this effect.
 
> > Podman containers are, by design, immutable once created
> 
> The resource limits can still be changed using `runc update`, `systemctl set property`, or directly writing into cgroup files. Not implying it was a bad decision, just thinking out loud.

Sure - the big blocker here is actually Podman's internal storage of container configuration. Our configs (which contain an initial version of the container's OCI spec among other things) are immutable as a design decision, to make state that needs to be distributed across different Podman processes as minimal as we can. This means that, while we can certainly adjust the resources of a running container, those changes will not be saved, so our report of the container configuration in `podman inspect` would be wrong, and the next time the container is restarted it would not have the changes made with `podman update`.

**Comment by rhatdan** [comment]
@mheon What do you want to do with this one?

**Comment by mheon** [comment]
Consolidate everything related to this in one `podman container clone` issue

**Comment by baude** [comment]
@mheon please do the consolidation and close this

**Comment by rhatdan** [comment]
Duplicate of https://github.com/containers/podman/issues/1925
