### ISSUE TITLE
Static Binary for Github Release?

### ISSUE THREAD

**Issue by hswong3i** [containers/podman#5774]
Refer to #5773, now we could only install podman from source build, in order to provide a synchronized user experience for installation under follow OS combination:
- Ubuntu 16.04/18.04/19.10
- CentOS/RHEL 7/8
- openSUSE 15.1

Could we reference how runc/conmon/cri-o/kubectl/kubeadm/kubelet Github release works (e.g. https://github.com/cri-o/cri-o/releases/tag/v1.17.3), therefore also provide an static binary archive for download with each release?

**Comment by rhatdan** [comment]
We are now shipping a static podman-remote for each release along with podman in a container.

**Comment by hswong3i** [comment]
@rhatdan what about also include #6402 nix-based statically linked `podman` binary into release?
