### ISSUE TITLE
Play kube support for volumes created with `podman volume create`

### ISSUE THREAD

**Issue by frezbo** [containers/podman#5788]
Play kube support for volumes created with `podman volume create`

/kind feature

**Description**
Play kube support for volumes created with `podman volume create`

**Comment by rhatdan** [comment]
This currently does not work?  What happens?
@kunalkushwaha @sujil02 PTAL

**Comment by mheon** [comment]
We have support for bind-mount (and I think tmpfs) volumes, but not named volumes. Those generate additional bits of Kubernetes YAML, which we have to deal with in both `generate kube` and `play kube` (and there was some debate as to exactly what YAML was required). Probably not particularly difficult, but someone more familiar with Kube would be a good fit for this.

**Comment by kunalkushwaha** [comment]
I can look into this.

**Comment by rhatdan** [comment]
@kunalkushwaha Any progress on this?

**Comment by rhatdan** [comment]
@mheon @haircommander Any ideas on this?

**Comment by mheon** [comment]
On our end, the real difficulty is figuring out the format for Kube volume YAML. Once we have that, I think it's a pretty simple mapping.

**Comment by haircommander** [comment]
named volumes sound like [emptyDir](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir). am I correct in saying so?

**Comment by mheon** [comment]
Hmm. That does sound pretty close. I'll take a look.

**Comment by frezbo** [comment]
@haircommander That seems fine to me too, since podman runs on the host.

**Comment by rhatdan** [comment]
@ryanchpowell Could you work with @haircommander on this?

**Comment by rhatdan** [comment]
@mheon @ashley-cui Could you take a look?

**Comment by xordspar0** [comment]
The problem with emptyDir is that its lifetime is the same as the pod. When the pod is created, a new empty volume is created. When the pod is destroyed, the volume is deleted forever. emptyDir is a scratch space for running applications. It's similar to `/tmp`, and it can optionally be memory-backed, similar to `/tmp`.

podman volumes are independent of pods; they can be created and destroyed on their own. This is more similar to Kubernetes [PersistentVolumeClaims](https://kubernetes.io/docs/concepts/storage/volumes/#persistentvolumeclaim), which is an API designed for abstracting over vendor-specific storage like S3 or Google Cloud Storage.

**Comment by aidan-plenert-macdonald** [comment]
I opened a PR to support this. I am trying to figure out how to write unit tests for this. Any guidance would be appreciated. I'm a bit stuck trying to figure out how to mock the Runtime.

**Comment by AlbanBedel** [comment]
Using named volume in kube files is already possible, just use a `hostPath` volume with `path`set to the volume name. This is working just fine for me:
```
  volumes:
    - name: app-data
      hostPath:
        path: my-named-volume
        type: Directory
```

**Comment by mheon** [comment]
If that works, I'd consider it more of a bug than a feature... I'm not saying we'll fix it, but if it breaks, fixing it will not be a priority.

**Comment by mheon** [comment]
#8497 merged and added support for persistent volume claims (backed by named volumes) to `play kube`. We do not, however, have support for this in `generate kube` yet, so I'll leave this open until that can be added.

**Comment by frezbo** [comment]
@mheon I can we can close this issue now. Kudos for implementing the fixes 👍 ❤️  Sorry for not being around.

**Comment by rhatdan** [comment]
@frezbo We still don't have generate kube according to @mheon .

**Comment by rhatdan** [comment]
@mheon this is probably something you need to do.

**Comment by mheon** [comment]
Unassigning myself, I don't think I'm going to have time for this any time soon. Hopefully the New First Issue label will attract contributors?

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by jwillikers** [comment]
I just a came across a situation where having the generate behavior would be helpful.
I should be able to add this functionality later this week.

**Comment by xordspar0** [comment]
This has been on my to do list for a long time, and it just worked its way up to the top. @jwillikers, please go ahead and work on this, it would save me some work! But I'll probably get to it next week if no one is working on it at that time.
