### ISSUE TITLE
RFE: cli plugin support?

### ISSUE THREAD

**Issue by christian-korneck** [containers/podman#5802]
I'm new to podman and have a quick question: Does podman support CLI plugins, [similar to the Docker CLI](https://docs.docker.com/engine/extend/cli_plugins/)? If so it would be great if someone could point me to a starting point like docs or an example. (If not I would still appreciate a quick confirmation - it'll save me some time from digging into the sources).

(Background: I have some homebrew Docker CLI plugins and would like to find out if/how I could use them with podman).

Thanks a lot in advance!

**Comment by mheon** [comment]
We do not at present support CLI plugins, sorry.

**Comment by christian-korneck** [comment]
@mheon thanks for clarifying!

**Comment by rhatdan** [comment]
What exactly do you do with a CLI Plugin?

**Comment by christian-korneck** [comment]
Small convenience things that I was missing from the Docker CLI. For example I have a plugin `pushrm` which pushes the _README.md_ from the current dir to the registry (with support for Dockerhub, quay, harbor). So I can run something like this to push the image and update the repo description in one go:

```
docker push docker.io/foo/foo:bar && docker pushrm docker.io/foo/foo:bar
```

I use it both interactively and in CI jobs. It uses registry creds from the Docker credentials store, so it made sense at the time to make it a Docker CLI plugin (instead of a standalone tool).

**Comment by TomSweeneyRedHat** [comment]
hmm, sounds like a good RFE to me if someone wanted to run with it.  Maybe we should add RFE to the title of this and open it up for someone to dive into?

**Comment by christian-korneck** [comment]
> Maybe we should add RFE to the title of this and open it up for someone to dive into?

Done. Thanks for supporting this!

**Comment by rhatdan** [comment]
Sure this is an open project. If we can get a contributor to work on this, we would welcome the addition.

**Comment by rhatdan** [comment]
@christian-korneck Any movement on this?

**Comment by christian-korneck** [comment]
no, not from my side so far

**Comment by rhatdan** [comment]
@QiWang19 Could you take a look at this?

**Comment by rhatdan** [comment]
@QiWang19 Did you ever get a chance to look at this?

**Comment by rhatdan** [comment]
We have found little interest in this from the community and it is not likely to be a priority for the development team.

**Comment by christian-korneck** [comment]
thanks, close

**Comment by christian-korneck** [comment]
just to add some infos to this (already closed) issue: CLI Plugin support in Docker is now [deprecated](https://github.com/docker/cli/blob/master/docs/deprecated.md#cli-plugins-support) and the spec (linked above) has been removed from the docs (last version is [here](https://github.com/docker/cli/blob/13ee065e954da5bf867a70520bf4d4f998848146/docs/extend/cli_plugins.md)). It looks like Docker has moved to a different model: In recent versions of Docker Desktop the "docker" executable is now a closed source wrapper around the original (now renamed) docker CLI that provides additional features (cloud integrations)). 

I still find CLI plugins useful (many CLIs support them, kubectl has [nice docs](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/) about the usecase). Generally speaking when a tool has a hard dependency on interfaces provided by the host tool (i.e. its API, credentials store, etc) and won't really work standalone imho it makes sense to make it a CLI plugin. (If I find time for a PR (unlikely soon) I'll reopen this issue).

**Comment by kriansa** [comment]
Well, that's weird. Although the support for CLI plugins is deprecated, the new Compose V2 is relying on it to work -- and it just got released: https://github.com/docker/compose/releases/tag/v2.0.0

`docker-compose` is simply broken now and a quick fix is to do a simple shell alias:

```bash
alias docker-compose="/usr/lib/docker/cli-plugins/docker-compose compose"
```

But that's not guaranteed to work with `podman` as I just tested and `build` command doesn't work :cry:

**Comment by christian-korneck** [comment]
yep, also Docker Desktop still ships with several CLI plugins. So I have some hope the interface for it won’t go away in the nearest future. (But I could be wrong).

Unrelated, I still don’t think CLI plug-ins for Podman would be a bad idea. Other CLIs like git or kubectl have such interfaces, too (and I personally use them quite a bit).

**Comment by kriansa** [comment]
@christian-korneck I agree that regardless of `docker` current state, `podman` could indeed support that kind of interface extensibility -- I'm also a user of `kubectl` and `git` plugins myself and I found it super useful to simply write a quick bash script and easily turn it into a subcommand.

I know this issue didn't get community traction when you first opened it, but I believe that it might get prioritized if `Compose V2` integration is still desired.

**Comment by christian-korneck** [comment]
> with podman [...] Compose V2 [...] `docker-compose compose build` command doesn't work

did you activate the Podman Docker socket?
https://www.redhat.com/sysadmin/podman-docker-compose

**Comment by kriansa** [comment]
Yes I did. Is it working on your end?

**Comment by jerdna-regeiz** [comment]
> > with podman [...] Compose V2 [...] `docker-compose compose build` command doesn't work
> 
> did you activate the Podman Docker socket? https://www.redhat.com/sysadmin/podman-docker-compose

I got it to run with docker-compose v2, but it requires the docker cli to be installed
```bash
docker -H unix:///run/user/1000/podman/podman.sock compose build 
```
To note: the -H is now a parameter for the docker cli itself and the compose cmd does not know anything about -H

**Comment by rhatdan** [comment]
We need to look at how we can get podman to directly run compose.

**Comment by kriansa** [comment]
@rhatdan [this](https://github.com/docker/docker.github.io/issues/10852#issuecomment-996023453) discussion might be of interest, since the future of compose as a standalone tool might be compromised depending on their internal decision. We all know compose is a ubiquitous tool in the ecosystem and it would not be great if its codebase eventually gets merged onto docker-cli (forks are not ideal IMHO).

**Comment by rhatdan** [comment]
Yes I am not sure we would ever add a CLI plugin interface. But supporting docker-compose as it evolves is something we hope to be able to maintain.
