### ISSUE TITLE
Communication between containers on separate networks

### ISSUE THREAD

**Issue by aparhatus** [containers/podman#5805]
Is communication between rootful containers on separate networks allowed by design? In Docker, containers on separate networks cannot access each other out of the box, whereas here they appear to:

```
[root@sandbox ~]# podman run --network network1 --name container1 -d docker.io/library/nginx
cb9d8e5ac20f25bf52866d1e468d139aff2b33de53b9c143d20fe1fed200fe97
[root@sandbox ~]# podman inspect -f "{{ .NetworkSettings.Networks.network1.IPAddress }}" container1
10.89.0.4
[root@sandbox ~]# podman run --network network2 --rm -it curlimages/curl 10.89.0.4
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
...
```

The networks were created with `podman network create <name>`.

Is there any way to get the same behaviour as with Docker, where containers cannot reach each other directly in this fashion and instead have to go through published ports on the host?

**Output of `podman version`:**

```
Version:            1.8.2
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
```

**Comment by mheon** [comment]
No way at present, though I imagine you could add firewall rules manually to restrict networks from reaching each other.

I imagine that CNI does have some way of doing this, given its origins in Kube, so that is something else worth researching.

**Comment by rhatdan** [comment]
@baude @mheon @mccv1r0 Any further info on this?

**Comment by mheon** [comment]
Nope. We should investigate further, though, this sounds like something we should support.

**Comment by mccv1r0** [comment]
> Is communication between rootful containers on separate networks allowed by design? 

This is (should be) a function of what you set the `iptables` FORWARD chain to allow.

**Comment by rhatdan** [comment]
@mccv1r0 @mheon Anyone ever work on this?

**Comment by mccv1r0** [comment]
No.  CNI has no way of knowing what you want the network you create to do/not do with respect to other "networks" (e.g. bridges) on the host system.

**Comment by mheon** [comment]
@rhatdan I think we'll need another CNI plugin, similar to the dnsname plugin, to do this.

**Comment by rhatdan** [comment]
@baude PTAL Seems like something for you.

**Comment by baude** [comment]
@rhatdan i dont think this is something podman should tread into. i think users should have to add fw rules, unless there is something in cni we can flip a bit on.

**Comment by rhatdan** [comment]
It would be nice if they were isolated by default.  But yes having CNI implement this would be best.

**Comment by AkihiroSuda** [comment]
This sounds like a security issue. Can we document this in the man page?

**Comment by AkihiroSuda** [comment]
A workaround is to assign distinct VLAN IDs with  `podman network create -o vlan=<VLANID>`. Would it be possible to enable VLAN by default?

**Comment by AkihiroSuda** [comment]
The following iptables commands seem to successfully isolate `cni-podman1` and `cni-podman2`:

```bash
iptables -A INPUT -i cni-podman1 -j MARK --set-mark 1
iptables -A INPUT -i cni-podman2 -j MARK --set-mark 2
iptables -A FORWARD -o cni-podman1 -m mark --mark 0 -j ACCEPT
iptables -A FORWARD -o cni-podman1 -m mark ! --mark 1 -j REJECT
iptables -A FORWARD -o cni-podman2 -m mark --mark 0 -j ACCEPT
iptables -A FORWARD -o cni-podman2 -m mark ! --mark 2 -j REJECT
```

The number of commands is O(N) where N is the number of the networks (not the number of the containers).

I'm planning to implement this as a CNI plugin, but I'd like to get some design review before doing that. RFC.

**Comment by mheon** [comment]
Can we make a separate chain in FORWARD for each network? We could have the separate chains default to REJECT which would only require a single ACCEPT rule for each new chain. Keeps the overall FORWARD chain smaller.

**Comment by mheon** [comment]
Sorry, a separate chain which FORWARD would transfer to for each network

**Comment by mccv1r0** [comment]
It looks like, to enforce isolation between docker networks, docker added two chans:

Chain DOCKER-ISOLATION-STAGE-1 
Chain DOCKER-ISOLATION-STAGE-2 

Stage 1 has a rule for each bridge sending to somewhere off bridge:

```
 pkts   bytes   target    prot opt  in            out          source               destination     
 1498 77256 DOCKER-ISOLATION-STAGE-2  all    --    docker0 !docker0  0.0.0.0/0            0.0.0.0/0   
```

Stage 2 also has rules for all their bridges where the output is another docker created network:

```
 pkts   bytes target     prot opt in     out         source               destination     
    0     0       DROP     all    --  *      docker0  0.0.0.0/0            0.0.0.0/0           
```

Thus anything from a docker network to another docker network is isolated. 

As each network is created/removed, these chains are updated.

If there is a way for docker (or podman) to explicitly allow network x to talk to network y via run command option, I suspect that they explicitly add ACCEPT rules, probably to stage-2.

**Comment by AkihiroSuda** [comment]
```

iptables -N CNI-ISOLATION-STAGE-1
iptables -N CNI-ISOLATION-STAGE-2
# NOTE: "-j CNI-ISOLATION-STAGE-1" needs to be before "CNI-FORWARD" created by CNI firewall plugin. So we use -I here.
iptables -I FORWARD -j CNI-ISOLATION-STAGE-1
iptables -A CNI-ISOLATION-STAGE-1 -i cni-podman1 ! -o cni-podman1 -j CNI-ISOLATION-STAGE-2
iptables -A CNI-ISOLATION-STAGE-1 -i cni-podman2 ! -o cni-podman2 -j CNI-ISOLATION-STAGE-2
iptables -A CNI-ISOLATION-STAGE-1 -j RETURN
iptables -A CNI-ISOLATION-STAGE-2 -o cni-podman1 -j DROP
iptables -A CNI-ISOLATION-STAGE-2 -o cni-podman2 -j DROP
iptables -A CNI-ISOLATION-STAGE-2 -j RETURN
```

This seems to work as well.

**Comment by AkihiroSuda** [comment]
Implemented as a CNI plugin (`/opt/cni/bin/isolation`): https://github.com/AkihiroSuda/cni-isolation

I'm planning to propose this to CNI upstream (https://github.com/containernetworking/plugins).

**Comment by AkihiroSuda** [comment]
Submitted a proposal to CNI upstream: https://github.com/containernetworking/plugins/issues/573

**Comment by AkihiroSuda** [comment]
Still can’t get review for PR https://github.com/containernetworking/plugins/pull/584

Can we just use https://github.com/AkihiroSuda/cni-isolation ?

**Comment by rhatdan** [comment]
@AkihiroSuda Since this is no movement in the upstream project, I am not sure what we can do about this?

**Comment by AkihiroSuda** [comment]
> @AkihiroSuda Since this is no movement in the upstream project, I am not sure what we can do about this?

If we can't get review comments for containernetworking/plugins#584 in the next couple of weeks, I think we should just use  https://github.com/AkihiroSuda/cni-isolation .

**Comment by rhatdan** [comment]
@AkihiroSuda Any progress?

**Comment by cdoern** [comment]
@flouthoc I am looking to dive into some rust/netavark work. @rhatdan @Luap99 you think this would be a good thing to try as a first issue I got here from containers/netavark#154

**Comment by flouthoc** [comment]
@cdoern Sure, please feel free to take this one. I think this falls more into category of iptables/firewall stuff.

**Comment by rhatdan** [comment]
Sure, if you think you can handle it, and @Luap99 and @flouthoc and @mheon don't have time to work on it.

**Comment by rhatdan** [comment]
@cdoern Are you working on this?

**Comment by cdoern** [comment]
yes @rhatdan containers/netavark#275 is the first step I am about to open a c/common PR for the option handling as well

**Comment by rhatdan** [comment]
Great

**Comment by cdoern** [comment]
@Luap99 do we need to modify podman to expose this option?

**Comment by Luap99** [comment]
No but we have to add the option to the network create man page

**Comment by umohnani8** [comment]
This has been fixed upstream.

@cdoern can you please verify this?

**Comment by cdoern** [comment]
yes, a new network option `--isolate` was added in netavark.

**Comment by Luap99** [comment]
We still have to document that in the man page.

**Comment by cdoern** [comment]
> We still have to document that in the man page.

I will do that today, nice catch
