### ISSUE TITLE
Give more control to `auto-update`

### ISSUE THREAD

**Issue by sebastienhasa** [containers/podman#5898]
/kind feature

**Description**

`auto-update` is really useful to update the image of a container. But
it would be even better to give more control on update process.

- Add the ability to launch manually the image update of only one
  container without the need to have the container managed by systemd
- When user launch an update of the image of one container, give the
  possibility to choose another tag for the image or even another
  image
- When update the container image, just stop the old container without
  delete it and create a new container with same settings and volumes
  from the old container
- If the new container fail to start, simply restart the old one
- If the new container start correctly, ask user if she/he want to
  keep the old one for future rollback
- Add a sub command to "prune" old containers
- Add a sub command to rollback manually an updated container
  (if the old one are still there)

**Comment by mheon** [comment]
@vrothberg I'm going to assign this one to you

**Comment by vrothberg** [comment]
Thanks for reaching out @sebastienhasa!

As you mentioned, auto-updates are currently heavily tied to systemd. While we are planning to implement simple rollbacks in the near future, there are no plans to move away from systemd. But nothing is carved into stone yet which is also why we marked the auto-update command as experimental.

@mheon @baude, as many things have changed in the backend, I want to give the idea another shot. With the new code, how far are we from being able to recreate a container from an existing one?

**Comment by mheon** [comment]
Once SpecGen is finalized, a lot closer than we were; I'd need to look more in depth to determine exactly how close.

**Comment by vrothberg** [comment]
Sounds good, thanks @mheon!

**Comment by rhatdan** [comment]
@mheon @vrothberg This is still being worked on correct?

**Comment by vrothberg** [comment]
I did not touch auto-updates as it has a lower priority than other work items. Once we can clone containers, we'll have quite some new playground.

**Comment by rhatdan** [comment]
@vrothberg Still same state?

**Comment by vrothberg** [comment]
Yes, unless we can clone containers, there's not much we can w.r.t. all requested items. 

I am still undecided whether Podman should really take care of auto updates on such fine granularity. The beauty of the current mechanism is it's simplicity and that Podman only needs to update the image and restart the systemd service.

**Comment by rhatdan** [comment]
I like the rollback and failure ideas, the others should be done with a different tool (Tooling).

**Comment by vrothberg** [comment]
> I like the rollback and failure ideas, the others should be done with a different tool (Tooling).

In a simple form, we can achieve this with the systemd-unit approach. We could wait until the service reports back a running/failed status and then retag the previous image and restart again.

**Comment by rhatdan** [comment]
@vrothberg I take it this is still in the distant future.

**Comment by vrothberg** [comment]
> @vrothberg I take it this is still in the distant future.

Rollbacks are definitely possible and fairly easy to implement. But time is scarce at the moment.

**Comment by rhatdan** [comment]
This is still something we would like to get.

**Comment by rhatdan** [comment]
Almost a year later, @vrothberg What do you want to do with this?

**Comment by vrothberg** [comment]
> Almost a year later, @vrothberg What do you want to do with this?

I don't decide priorities but still want to work on it.  Up to the Jedi council to carve out time for me to work on it.

**Comment by rhatdan** [comment]
I think we need to start organizing these together to figure out a list of priorities.

**Comment by vrothberg** [comment]
Work on auto-update has resumed. The output has changed significantly and --dry-run (see https://github.com/containers/podman/pull/10937) gives more flexibility. https://github.com/containers/podman/issues/10875 is tracking the idea of allowing updates without the requirement of running inside a systemd service. Rollbacks are currently being discussed.

I am going to close this issue here.  If there are more things on the wish list, let's create one issue per item.
