### ISSUE TITLE
Couldn't change binded file inside container by command in entrypoint

### ISSUE THREAD

**Issue by NTMan** [containers/podman#5922]
/kind bug

I see that podman allow bind single file https://github.com/containers/libpod/issues/5134
But inside the container, this file couldn't be changed by sed command in entrypoint.

```
podman run -v "./stend/test/inside.ini":"/root/services/inside/online/sbis-rpc-service.ini":Z -v "./stend/test/inside-ps.ini":"/root/services/inside/online-ps/sbis-rpc-service.ini":Z --rm --entrypoint sleep --name="inside" --hostname "10-176-134-209.dev-vpn.corp.tensor.ru" --net host --shm-size=1g  --memory="16g" --memory-swap="32g" dev-registry.sbis.ru/local_stand/inside:20.3100-night 5 && sed -i "s/#your_hostname/`hostname`/g" /root/services/inside/online/sbis-rpc-service.ini /root/services/inside/online-ps/sbis-rpc-service.ini
sed: can't read /root/services/inside/online/sbis-rpc-service.ini: Permission denied
sed: can't read /root/services/inside/online-ps/sbis-rpc-service.ini: Permission denied
```

**Output of `podman version`:**
```
# podman version
Version:            2.0.0-dev
RemoteAPI Version:  1
Go Version:         go1.14
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**
```
# podman info --debug
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.14
  podmanVersion: 2.0.0-dev
host:
  arch: amd64
  buildahVersion: 1.14.8
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.16-0.1.dev.gite34c6d6.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.16-dev, commit: 1978f44ff6e2dcac0b37e52448ce37789c99add3'
  cpus: 32
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.7.0-0.rc1.20200416git9786cab67457.1.2.fc33.x86_64
  memFree: 2247114752
  memTotal: 33552924672
  ociRuntime:
    name: crun
    package: crun-0.13-2.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 55072518144
  swapTotal: 68719472640
  uptime: 67h 26m 51.72s (Approximately 2.79 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 0
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  Built: 0
  GitCommit: ""
  GoVersion: go1.14
  OsArch: linux/amd64
  RemoteAPIVersion: 1
  Version: 2.0.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# rpm -q podman
podman-2.0.0-0.10.dev.git8857ba2.fc33.x86_64
```

**Comment by mheon** [comment]
Sorry that this issue's been neglected for so long. I see that you were running a v2.0.0-dev build; there's been a massive amount of change to master over the last month, so would it be possible to try again with the latest master?

Also, are you running Podman rootless, or as root?

**Comment by NTMan** [comment]
> Sorry that this issue's been neglected for so long. I see that you were running a v2.0.0-dev build; there's been a massive amount of change to master over the last month, so would it be possible to try again with the latest master?

I see that since build `2.0.0-0.13.dev.git5b4e91d.fc33` broken `WORKDIR`. Any command in entrypoint that should be executed relatively WORKDIR now not working. Because start directory now `/` instead of `WORKDIR`.

> Also, are you running Podman rootless, or as root?

I am running Podman rootless.

**Comment by rhatdan** [comment]
Can you give us a simple reproducer?

**Comment by rhatdan** [comment]
@NTMan Could you describe a simple reproducer?

**Comment by mheon** [comment]
I don't think anyone has managed to reproduce this. I'm going to close this for a lack of information on how to proceed; if someone has a reproducer, please comment and we can reopen.

**Comment by NTMan** [comment]
> I don't think anyone has managed to reproduce this. I'm going to close this for a lack of information on how to proceed; if someone has a reproducer, please comment and we can reopen.

I have prepared a demo here: https://github.com/NTMan/podman-example

**Comment by rhatdan** [comment]
I just downloaded and tried podman-example


$ podman run  -v "$PWD/inside.ini":"/root/inside.ini":Z localhost/bugreport:1.0
sed: cannot rename /root/sedcxVmUe: Device or resource busy

This looks like sed is attempting to mv the /root/inside.ini file which since it is a mount point, is not allowed
So I changed the test a little and did
$ mkdir root
$ cp inside.ini root/
$ podman run  -v "$PWD/root":"/root":Z localhost/bugreport:1.0

And it succeeds.
