### ISSUE TITLE
Rootless podman: support passing arbitrary paths to configuration files

### ISSUE THREAD

**Issue by grahamc** [containers/podman#6053]
/kind feature

**Description**

I'd like to be able to specify all configuration files to podman (rootless or not) via configuration flags or podman-specific environment variables.

On Podman 1.9.1 and 1.8.2, when I run `podman import result/tarball/nixos-system-x86_64-linux.tar.xz my-image`, I get:

> Error: open /etc/containers/policy.json: no such file or directory

I found #1336 (rootless: allow to override policy.json by the user) but creating a file at `~/.config/containers/policy.json` doesn't seem to change the error. Additionally, since this is part of some automation, I do not want the runners to need to add configuration to their `~` either, and overriding `HOME` during the test phase is a bit ugly.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

both:

```
Version:            1.8.2
RemoteAPI Version:  1
Go Version:         go1.14.1
Built:              Wed Dec 31 19:00:01 1969
OS/Arch:            linux/amd64
```

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.14.1
  podman version: 1.8.2
host:
  BuildahVersion: 1.14.3
  CgroupVersion: v1
  Conmon:
    package: Unknown
    path: /nix/store/3dndp024ipa71x2iq9nphq0r4xic7irk-conmon-2.0.15/bin/conmon
    version: 'conmon version 2.0.15, commit: unknown'
  Distribution:
    distribution: nixos
    version: 20.03.1422.1e90c46c2d9
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 100
      size: 1
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
  MemFree: 2304905216
  MemTotal: 16424857600
  OCIRuntime:
    name: runc
    package: Unknown
    path: /nix/store/a0ghvlp1416x90k3a65f9p78zbkqpc5x-runc-1.0.0-rc10-bin/bin/runc
    version: |-
      runc version 1.0.0-rc10
      spec: 1.0.1-dev
  SwapFree: 17149521920
  SwapTotal: 17177767936
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: Petunia
  kernel: 5.5.17
  os: linux
  rootless: true
  slirp4netns:
    Executable: /nix/store/qch3lh6r65qwd3jziczbkl2ma13673kh-slirp4netns-1.0.1/bin/slirp4netns
    Package: Unknown
    Version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.3.0
  uptime: 19h 52m 35.67s (Approximately 0.79 days)
registries: {}
store:
  ConfigFile: /home/grahamc/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: vfs
  GraphOptions: {}
  GraphRoot: /home/grahamc/.local/share/containers/storage
  GraphStatus: {}
  ImageStore:
    number: 0
  RunRoot: /run/user/1000/containers
  VolumePath: /home/grahamc/.local/share/containers/storage/volumes
```

and

```
Version:            1.9.1
RemoteAPI Version:  1
Go Version:         go1.14.1
Built:              Wed Dec 31 19:00:01 1969
OS/Arch:            linux/amd64
```

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.14.1
  podmanVersion: 1.9.1
host:
  arch: amd64
  buildahVersion: 1.14.8
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /nix/store/3dndp024ipa71x2iq9nphq0r4xic7irk-conmon-2.0.15/bin/conmon
    version: 'conmon version 2.0.15, commit: unknown'
  cpus: 8
  distribution:
    distribution: nixos
    version: 20.03.1422.1e90c46c2d9
  eventLogger: file
  hostname: Petunia
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 100
      size: 1
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
  kernel: 5.5.17
  memFree: 2319196160
  memTotal: 16424857600
  ociRuntime:
    name: runc
    package: Unknown
    path: /nix/store/a0ghvlp1416x90k3a65f9p78zbkqpc5x-runc-1.0.0-rc10-bin/bin/runc
    version: |-
      runc version 1.0.0-rc10
      spec: 1.0.1-dev
  os: linux
  rootless: true
  slirp4netns:
    executable: /nix/store/qch3lh6r65qwd3jziczbkl2ma13673kh-slirp4netns-1.0.1/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.3.0
  swapFree: 17149521920
  swapTotal: 17177767936
  uptime: 19h 51m 42.91s (Approximately 0.79 days)
registries: {}
store:
  configFile: /home/grahamc/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/grahamc/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/grahamc/.local/share/containers/storage/volumes
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I'd like to be able to do this universally.

**Comment by mheon** [comment]
We verified this isn't affected by containers.conf (1.8.2 still has the bug). Based on #1336 my first suspicion is some form of runtime config validation catching it, though it's possible that it could be somewhere in c/image as well.

**Comment by rhatdan** [comment]
This is definitely something in containers/image.  I don't believe Podman can currently override this.

**Comment by mtrmac** [comment]
Things like https://github.com/containers/libpod/blob/6803e72bf87e737663db054d971135bc06d0747f/cmd/podman/images/pull.go#L84 exist, and c/image also allows specifying the policy path.

If `podman import` does not have the CLI option, and does not use the same rootless code to set the rootless overrides (which are _not_ c/image defaults), at least currently, that’s all entirely within the Podman repo.

**Comment by ayilmaz81** [comment]
I am getting the same error while i do `podman build .`
`STEP 1: FROM busybox
STEP 2: COPY sleep10.sh /home/
Error: error committing container for step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:copy Args:[sleep10.sh /home/] Flags:[] Attrs:map[] Message:COPY sleep10.sh /home/ Original:COPY sleep10.sh /home/}: error obtaining default signature policy: open /etc/containers/policy.json: no such file or directory`
As I don't have root access, can't create the file.
Note : `docker pull` successfully runs.

**Comment by rhatdan** [comment]
If you create policy.json in ~/.config/containers/policy.json
Something like:
```{
    "default": [
        {
            "type": "insecureAcceptAnything"
        }
    ],
    "transports":
        {
            "docker-daemon":
                {
                    "": [{"type":"insecureAcceptAnything"}]
                }
        }
}
```

Does it work?

**Comment by ayilmaz81** [comment]
I have that file indeed. I am running rootless podman.
`podman run`, `podman pull` works fine.

**Comment by grahamc** [comment]
I'm not sure this is stale.

**Comment by rhatdan** [comment]
Well we gave you two options, one is placing the policy.json file in your homedir.  Or using the command line option --signature-policy PATHTOPOLICY
What else do you need?

**Comment by rhatdan** [comment]
Basically if you install podman yourself, not using a distro package, then you need to create the appropriate config files.  If this is a distro package of Podman, then the disto package was not created correctly.

**Comment by adisbladis** [comment]
> If this is a distro package of Podman, then the disto package was not created correctly.

This is assuming the package manager is even able to create files in `/etc/` or `$HOME`.
Not all package managers allow this.

**Comment by adisbladis** [comment]
The flag `--signature-policy` seems very inconsistently exposed and is not documented in the `podman pull --help` output.

It's not available in `podman run`, which will attempt to pull an image if it's not locally accessible.

**Comment by mtrmac** [comment]
Primarily Podman needs to update c/image to include https://github.com/containers/image/pull/922 , for a global default; there hasn’t been a c/image release since. And then Podman would hopefully prune some of the Podman-specific-defaults code that sets the same defaults as that PR.

And then we _probably_ should add the explicit `--signature-policy` option for `podman import` and `podman build`, or wherever else it would make sense but it is currently missing.

**Comment by vrothberg** [comment]
@rhatdan, I removed the assigned from me. 

I think the request should be discussed in a bigger round. There are many configuration files that "could" be passed around and I am not sure we want to expose all of them in the Podman flags.

If we do that, I'd vote for making them root-level flags (e..g, podman --conf) instead of adding them to each and every command that may need them.

@baude @mheon PTAL

**Comment by ayilmaz81** [comment]
Sorry for hijacking this one.
There are still issues with signature policy not being read from $HOME dir.
Is there another ticket to synchronize the behaviour for all podman commands?
Thanks

**Comment by mtrmac** [comment]
There’s also the https://github.com/containers/skopeo/issues/849 quagmire.

**Comment by vrothberg** [comment]
@QiWang19 PTAL. Let's focus on the policy parts.
