### ISSUE TITLE
Trouble with rootless podman over ansible or distcc

### ISSUE THREAD

**Issue by avikivity** [containers/podman#6068]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I use rootless podman underneath distcc to serve various compiler images. If I let distcc or ansible execute "podman pull", under the distcc user, then I get the dreaded "there might not be enough IDs" message. If I execute the command from a login shell, then it works. I suspect that podman is misdetecting its own configuration if not running under a login shell.

**Steps to reproduce the issue:**

1.  ansible --become-user=distcc -some_host -m podman_image -a name=

(same problem happens with "ansible -a" or if distcc itself executes it as part of "podman run")

**Describe the results you received:**

There might not be enough IDs available.

**Describe the results you expected:**

Pull complete.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

podman version 1.8.0

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.15
  podman version: 1.8.0
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.13-1.fc30.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.13, commit: 0d76d92618b091af3623e9d4a60889b32fe4bff6'
  Distribution:
    distribution: fedora
    version: "30"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1015
      size: 1
    - container_id: 1
      host_id: 1000000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1015
      size: 1
    - container_id: 1
      host_id: 1000000
      size: 65536
  MemFree: 9592545280
  MemTotal: 16477880320
  OCIRuntime:
    name: runc
    package: runc-1.0.0-102.dev.gitdc9208a.fc30.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: ffa084d279c26351e6e63bd2c3f28d43fa1f6e57
      spec: 1.0.1-dev
  SwapFree: 20662956032
  SwapTotal: 20736630784
  arch: amd64
  cpus: 4
  eventlogger: file
  hostname: thor.cloudius-systems.com
  kernel: 4.18.19-100.fc27.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-4.git19d199a.fc30.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.2
      commit: 19d199a6ca424fcf9516320a327cedad85cf4dfb
  uptime: 1615h 1m 44.89s (Approximately 67.29 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /var/distcc/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.5-2.fc30.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /var/distcc/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 1
  RunRoot: /var/tmp/run-1015/containers
  VolumePath: /var/distcc/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical, Fedora 30

**Comment by mheon** [comment]
It's already known and documented that Podman does not play nicely with `sudo` and `su` (they don't play nicely with some PAM things that we expect, for example mounting `/run/user/$UID`), so I suspect that this may be similar; however, I've never seen an ID-related error involved in that. I don't know exactly how `become_user` works, but it's possible that it's doing things in a strange manner that is causing us to not properly detect what user we're running as.

**Comment by avikivity** [comment]
That's unfortunate. What do people do? 

Is there a list of such requirements that I can try to satisfy myself?

**Comment by avikivity** [comment]
The failure could be much more graceful. If /run/blah doesn't exist, tell me that's the problem, don't tell me that there might not be enough IDs available.

**Comment by avikivity** [comment]
I worked around this by giving this command to ansible: `sudo sudo -i -u distcc podman pull ...`. Of course ansible cursed me for using sudo.

Please make it easier to work with rootless podman in non-interactive scenarios. And also try to improve error reporting, the "not enough IDs" message is thrown whenever there is some misconfiguration, but there is no clue as to what the misconfiguration is.

**Comment by mheon** [comment]
If sudo actually works, it sounds like something about Ansible's become is
confusing the rootless code majorly. I wouldn't consider this a
misconfiguration, but rather Podman likely not being entirely sure what
user it was run as and not locating the proper subuid entry.

**Comment by avikivity** [comment]
It works after I added the service that kept /run/user/$(id foo) up (I did not do exhaustive checks to see if the exact incantation that ended up working does not work without it).

Is it possible to make podman's notion of the user more consistent with other system tools? And perhaps report the user it thinks it is when consulting subuid?

**Comment by avikivity** [comment]
and/or document what podman expects?

**Comment by rhatdan** [comment]
@giuseppe @mheon Could you guys add something to troubleshooting on this.

Basically document
````
ssh root@HOSTNAME
# su user
$ podman ...
Failure
```

**Comment by rhatdan** [comment]
The basic problem is the lack of XDG_RUNTIME_DIR being set or other fields set incorrectly so that podman tries to do stuff that the root process can only do.  IE Write the /root homedir or /run/user/0/...

We have to document that the user needs to setup a true user login session by either coming in through a login process or by executine `su -- USER`.

**Comment by rhatdan** [comment]
This is now documented, closing. Reopen if I am mistaken.
