### ISSUE TITLE
passthrough fuse mounts to host?

### ISSUE THREAD

**Issue by bam80** [containers/podman#6075]
Is it possible? So I could see the same mounts on host I mounted inside the container.
Also filed for Toolbox: https://github.com/containers/toolbox/issues/429

**Comment by rhatdan** [comment]
We need a lot more information about what you are asking?

**Comment by mheon** [comment]
Assuming that this is for Rootless - unfortunately, I don't think this is possible, as it's a kernel limitation. The user namespace that rootless Podman runs inside creates what is effectively a separate mount table, which the kernel does not allow to mix with the table on the host.

**Comment by bam80** [comment]
Hm, what should be the solution then?
I have an app ultimate goal of which is to create that mount - it's a distributed FS: https://book.keybase.io/docs/files
And it doesn't need root to operate. It works perfectly fine within Toolbox.
Of course, it's highly advisable to have that mount point accessible on the host also.

It's undesirable to install it on host because I run immutable OS - Fedora Silverblue.

**Comment by rhatdan** [comment]
Can you run a rootful podman and do your commands, I think this is supported on Silverblue.

**Comment by AkihiroSuda** [comment]
/proc/PID/root might be what you want

**Comment by bam80** [comment]
@AkihiroSuda could you explain what do you mean please?

**Comment by rhatdan** [comment]
@bam80 Are you still interested in this?

**Comment by bam80** [comment]
@rhatdan yes, probably, just don't have time on it now. I'm not sure Toolbox provides rootfull containers variant..

**Comment by HarryMichal** [comment]
> I'm not sure Toolbox provides rootfull containers variant..

You are right about this one. It's coming in the future.

**Comment by rhatdan** [comment]
Since this is currently impossible with the kernel, I am going to close.  If new kernel features come about, we could reopen and consider.
