### ISSUE TITLE
How to find who owns unreadable files in .local?

### ISSUE THREAD

**Issue by abitrolly** [containers/podman#6111]
/kind feature

`podman` creates unreadable files in my home, which fill find output with many errors. I don't know how they appeared. Perhaps I ran `podman` with `sudo`. How to find out to which container do these belong? It would be convenient to get is a script for that.
```
ERR: Error opening directory ./.local/share/containers/storage/overlay-containers/43c0bd3a68f89535febd769723932dc41e973cd01cc602acc6ce5d4f4eb3c43e/userdata: Permission denied
ERR: Error opening directory ./.local/share/containers/storage/overlay/dd86cecf6972861368c4db864e361a7b7852c12bf3904231064b4dab83e1f08f/diff/var/tmp/dnf-anatoli-3l5obs7x: Permission denied
ERR: Error opening directory ./.local/share/containers/storage/overlay/2dc9f76fb25b31e0ae9d36adce713364c682ba0d2fa70756486e5cedfaf40012/diff/var/cache/apt/archives/partial: Permission denied
ERR: Error opening directory ./.local/share/containers/storage/overlay/7094ec09299a1a79690ceea9d9dc3386126dd4aeb0fd6b44c7cff89253bea961/diff/var/cache/apt/archives/partial: Permission denied
ERR: Error opening directory ./.local/share/containers/storage/overlay/b592b5433bbffb04389a0e6349cdba6af8d006779bbb93beb69aa77d59133be4/diff/var/lib/apt/lists/partial: Permission denied
```

**Comment by mheon** [comment]
If you open a shell with 'podman unshare' you should be able to remove
them. They are likely made by the extra users we map into the container
from subuid and subgid, which the unshare command gives you access to.

**Comment by abitrolly** [comment]
@mheon not sure I want to remove them. Maybe they are from legit containers.

**Comment by rhatdan** [comment]
They are most likely legit files.  Almost every container in the world that is based on a distro, will have more then one UID in them.  These UIDs can only be created and removed while in the user namespace,

podman unshare 

Puts you in the user namespace and allows you to manipulate these files.

Read https://github.com/shadow-maint/shadow/issues/154 to get the whole gory details or what I would like to see.
It would be awesome if ls, find and other coreutils could figure out that you own these files in your usernamespace.

**Comment by abitrolly** [comment]
@rhatdan I skimmed over the thread, but still could not understand what a user namespace is, and what `podman unshare` really does.

**Comment by rhatdan** [comment]
These might help you understand.

https://lwn.net/Articles/532593/

man podman-unshare

https://opensource.com/article/19/2/how-does-rootless-podman-work
https://www.redhat.com/sysadmin/behind-scenes-podman

**Comment by abitrolly** [comment]
@rhatdan with recursive definitions like that I need to find better info elsewhere.

> User namespaces allow per-namespace mappings of user and group IDs.

**Comment by mheon** [comment]
A user namespace is basically a way of "mapping" some (or all) users on the host into a new process (usually a container) and its descendants. It lets us expose only some users to the container (IE, for a rootless container, only your own UID and a block of users/groups specified in `/etc/subuid` and `/etc/subgid` are exposed inside the container) and also reorder those users (inside a rootless container, your user appears to be UID/GID 0; but on the host, you'll still see the container as your UID).

In a rootless container, this lets us get around one of the largest obstacles to running containers as a normal user: access to more than one user. Inside a container, you expect to be able to have a number of users and groups available, so you can launch processes as non-root users, use file permissions to ensure that config files are read-only for that user, etc. Obviously, the standard Linux permissions model is that you have access only to the user you're logged in as (except root, which has the capability to ignore file ownership and switch to any user trivially). User namespaces let us gain access to a block of extra UIDs and GIDs within the container (using `newuidmap` and `newgidmap`, system utilities that read `/etc/subuid` and `/etc/subgid` and give us access to the specified users/groups), and then map those users and groups into the container such that it appears to be a standard Linux system running as root from within the container, but an unprivileged user process from the host system.

**Comment by abitrolly** [comment]
No filesystem touched so far. What `unshare` then does without filesystem?

**Comment by mheon** [comment]
`podman unshare` enters the user namespace that Podman uses, but does not mount any containers (well, it can, but only if you tell it to). Basically, it gives you the same "view" of the system's users that the container has - you will appear to be root, but actually be your own UID, and you will have access to the users/groups you were allocated in `/etc/subuid` and `/etc/subgid` (visible as UID/GID 1 and up in the shell launched by `unshare`). This makes no direct changes to your containers, but it does let you act as any of the users your containers have access to. If a container created a file in a volume mounted from your home directory as, say, UID 25, that UID is mapped through the user namespace to a different UID on the host, and you probably that it's actually owned by 10024 (or similar) on the host, and your user cannot access or remove it when not inside a container because it's not owned by you. `podman unshare` gives you a shell where you'll see it as it is in the container (owned by UID 25) and can open/remove it.

**Comment by rhatdan** [comment]
Well we now have a library to be able to discover who owns these files. https://github.com/shadow-maint/shadow/commit/0a7888b1fad613a052b988b01a71933b67296e68

**Comment by abitrolly** [comment]
Any command line tool for that?

**Comment by rhatdan** [comment]
Not yet, but it is moving forward slowly.

**Comment by abitrolly** [comment]
@rhatdan had any CLI tooling appeared to check the ownership of the unreadable storage dirs?

**Comment by rhatdan** [comment]
This should find them:

podman unshare find ~/.local/share/containers ! -uid 0

**Comment by abitrolly** [comment]
This still gives no direct connection to which containers these files belong, or if they are orphaned.
```
➜  ~ podman ps   
CONTAINER ID  IMAGE                               COMMAND  CREATED       STATUS           PORTS                     NAMES
d79c46e7f840  localhost/cheat.sh:latest                    24 hours ago  Up 24 hours ago                            zealous_ardinghelli
78031c11267b  docker.io/openzipkin/zipkin:latest           28 hours ago  Up 28 hours ago  127.0.0.1:9411->9411/tcp  fervent_mclean
➜  ~ podman unshare find ~/.local/share/containers ! -uid 0
/home/anatoli/.local/share/containers/storage/overlay/0e33060be17cca7fe5322e2db78d003f244fb7a24dc8ab2fe7e3ce844b97eb65/diff/var/cache/apt/archives/partial
/home/anatoli/.local/share/containers/storage/overlay/ff02e3f2ca6b2f8c422e1c52bc2b608bd5fe4a87b90390d07c31f44a7801e1e2/diff/var/cache/apt/archives/partial
/home/anatoli/.local/share/containers/storage/overlay/b1fd9cd5ec935c722e197f91d2f18f6f354f86f386691ddba01c2f95e4723e0d/diff/var/cache/apt/archives/partial
/home/anatoli/.local/share/containers/storage/overlay/7c5793d6295641dc1beeb2abee0b56c4a4c31109330c368210642f7265f25c94/diff/zipkin
/home/anatoli/.local/share/containers/storage/overlay/7c5793d6295641dc1beeb2abee0b56c4a4c31109330c368210642f7265f25c94/diff/zipkin/BOOT-INF
```

**Comment by rhatdan** [comment]
Well the directory that they are stored in would indicate the image they are associated with.  Note these files could be associated with a regular image as well as a container runtime image.  Meaning they might not be associated with an image at all.

What kind of command would you want?

**Comment by vrothberg** [comment]
Container mounts are in `storage/overlay-containers`.  Images are in `storage/overlay`.  We can use `podman inspect` to know which container/image uses which mount.

But I would not want to add a command to list these explicitly as it's not something, I want users to worry about as it's an implementation detail.  Changing the data can lead to data corruption.

`podman *prune` commands allow for removing unused data if necessary.

**Comment by rhatdan** [comment]
I think this is explained fairly well what is going on.  I am going to close this issue.
