### ISSUE TITLE
docs doesn't state if auth.json is created by default and if it's secure

### ISSUE THREAD

**Issue by peterducai** [containers/podman#6170]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Manual at docs/source/markdown/podman-login.1.md doesn't clearly state that if you do podman login, it will actually create /run/user/1000/containers/auth.json with base64 encoded password which is not secure.

**Steps to reproduce the issue:**

1. podman --log-level debug login registry.redhat.io

2. sudo cat /run/user/1000/containers/auth.json

**Describe the results you received:**

```
{
	"auths": {
		"registry.redhat.io": {
			"auth": ".......some hash"
		}
```

**Describe the results you expected:**

no auth file or other options..

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version
Version:            1.9.1
RemoteAPI Version:  1
Go Version:         go1.14.2
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
Woudl you care to open a PR without your suggested text?

**Comment by vrothberg** [comment]
I'll ask our auth specialist, @QiWang19, to document it :)
