### ISSUE TITLE
Would be nice to have a different 'podman pull' exit code for network failures

### ISSUE THREAD

**Issue by debarshiray** [containers/podman#6190]
/kind feature

**Description**

Every once in a while, I come across people who failed to create a [toolbox](https://github.com/containers/toolbox) container because `podman pull` errored out for some reason. For example:
```
$ toolbox create
toolbox: failed to pull base image fedora-toolbox:32
```

And if you use the `--verbose` flag you get to see the spew from `podman pull`.
```
$ toolbox --verbose create
toolbox: Fedora generational core is f32
toolbox: base image is fedora-toolbox:32
toolbox: customized user-specific image is fedora-toolbox-jsgrant:32
toolbox: container is fedora-toolbox-jsgrant:32
toolbox: checking if image fedora-toolbox-jsgrant:32 already exists
ERRO[0000] exit status 1                                
toolbox: looking for image localhost/fedora-toolbox:32
Pulling docker://localhost/fedora-toolbox:32
ERRO[0000] exit status 1                                
toolbox: looking for image registry.fedoraproject.org/f32/fedora-toolbox:32
Pulling docker://registry.fedoraproject.org/f32/fedora-toolbox:32
ERRO[0000] exit status 1                                
toolbox: failed to pull base image fedora-toolbox:32
```

More often than not (almost always?) these are passing network errors. I have seen them myself once or twice, and trying it again gets you past the failure. It would be nice if `toolbox` could throw a more indicative error message that makes it clear that it was due to a network failure or such, instead of a generic string that makes people want to file a bug. :)

**Output of `podman version`:**

```
Version:            1.9.1
RemoteAPI Version:  1
Go Version:         go1.13.10
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.13.10
  podmanVersion: 1.9.1
host:
  arch: amd64
  buildahVersion: 1.14.8
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.15-1.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.15, commit: 4152e6044da92e0c5f246e5adf14c85f41443759'
  cpus: 4
  distribution:
    distribution: fedora
    version: "31"
  eventLogger: file
  hostname: kolache
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.4.14-200.notify.fc31.x86_64
  memFree: 1635704832
  memTotal: 8107806720
  ociRuntime:
    name: crun
    package: crun-0.13-2.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  swapFree: 4133482496
  swapTotal: 4133482496
  uptime: 24m 32.81s
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  configFile: /home/rishi/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.0.0-1.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 1.0.0
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  graphRoot: /home/rishi/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  volumePath: /home/rishi/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.9.1-1.fc31.x86_64
```

**Comment by debarshiray** [comment]
There's a similar feature request for `buildah pull` too: https://github.com/containers/buildah/issues/1499

**Comment by mheon** [comment]
The big issue on our end is identifying what is a network failure from c/image - I don't think the errors we get out of it are formatted in a way to make that easy.

**Comment by rhatdan** [comment]
@mtrmac WDYT?

**Comment by mtrmac** [comment]
(As a side note, matching on error texts is completely unsustainable.)

On network errors, I would expect the returned error (or maybe `errors.Cause(err)`) to be a somewhat-well-typed Go error in that case. But it’s hard to consider that an API contract, _especially_ when the Go library itself does not commit to using any particular types (e.g. there is a `DNSError` type but not a commitment to return it from particular functions AFAICS).

So, I suppose, if you want to check for a _specific single_ error cause, it could be possible; several situations have specific error types defined. The Go error non-hierarchy does not allow checking _all_ “network failures” AFAICS.

— and anyway I’m not sure it’s actually what you want. E.g. a registry returning HTTP status 408/504, or many of the other 5* codes, is not a “network” error but retrying a few times might still be the appropriate response. So… it seems hard to reserve an exclusive exit code for a category with unclear boundaries, where there may well be different overlapping! sets of errors the caller may want to check for.

So, ideally, the retry logic, if any, should be in Go and use Go types, not the executable and a <8-bit exit code value. But then that’s just not available currently.

**Comment by mtrmac** [comment]
BTW looking at the examples above(or were they truncated?), `toolbox` could definitely help users by actually printing the error; it does not contain a Podman-printed message even on `--verbose`. (But then the Podman or c/image errors could also benefit from someone working to make them look nicer.)

**Comment by debarshiray** [comment]
> BTW looking at the examples above(or were they truncated?), `toolbox` could
> definitely help users by actually printing the error; it does not contain a Podman-printed
> message even on `--verbose`. (But then the Podman or c/image errors could also
> benefit from someone working to make them look nicer.)

At the moment `--verbose` or `-v` shows the `stderr` of all the inner commands and some extra debug spew from Toolbox itself. You can escalate that with `-vv`, which will invoke Podman with `--log-level debug`.

**Comment by debarshiray** [comment]
> (As a side note, matching on error texts is completely unsustainable.)

Having an explicit code for the Podman binary would remove the urge to parse the actual error text (as in https://github.com/containers/libpod/issues/5288). :)

**Comment by mtrmac** [comment]
That’s sort of exactly my point: If we reserve an exit status for exactly HTTP status 503, as #5288 asks, and an exit status for exactly “network failures” (whatever that means – and does that include HTTP status 503?), as this issue asks, how can we design such an API without breaking users as new feature requests come along? It just doesn’t work for more than 2–3 cases.

**Comment by mtrmac** [comment]
See also https://github.com/containers/buildah/blob/912ca5acd9c7d74f41dce2620caef0a043ecdc9f/common.go#L121 .
- This shows things that _can_ be built
- The logic is different than what you are asking for (probably, this issue does not have a strict spec): DNS failures are “network failures”, but not retryable.

**Comment by debarshiray** [comment]
I don't care that much about the distinction between retryable and non-retryable failures. If such a distinction can be made, then great, but it's not critical.

I mostly care about the difference between a faulty `podman pull` invocation (eg., with an invalid image URL), and a valid invocation that failed due to problems with the network or the registry. In the first case, it's clearly the user's fault (or in this case Toolbox's), and in the latter it's caused by something else.

**Comment by mheon** [comment]
The biggest issue there is that individual registries cannot agree what a bad URL vs a registry issue will actually do. HTTP status codes aren't really standardized for registry implementations, so a missing image could be a 404, a 500, or any number of other things - and we really can't know exactly what they mean without knowing the exact server software in question is and how it uses those codes. There are some efforts to standardize this, but I'm not really confident that all the existing implementations will rewrite to conform to the new standard when it's finalized.

**Comment by mtrmac** [comment]
In principle, it _would_ be valuable to collect all that knowledge and provide a best-effort API for that in c/image. (IIRC we were reasonably close with the plain “image not found” case a few years ago, but not quite there so it was abandoned at that time.)

Still, I don’t see that we can squeeze this through the single exit code (with a fixed set of exclusive values) in a long-term sustainable way. Maybe `podman --exit-status-on-syntax-error=42 --exit-status-on-retryable=43 --exit-status-on-network-failure=44` (and refusing options that conflict _in that particular version_) … ugh.

**Comment by rhatdan** [comment]
We currently exit 125 on syntax failures.  If we could differentiate between Image does not exist and network failure. that would be enough.

On podman rm and rmi,  we have exit codes like:

```
  **0**   All specified images removed

  **1**   One of the specified images did not exist, and no other failures

  **2**   One of the specified images has child images or is being used by a container

  **125** The command fails for a reason other than an image did not exist or is in use
```
If we could specify 0 for success, 1 for image does not exist, 2 for network failure 125 for all other failures.

**Comment by rhatdan** [comment]
There is ongoing work to add retry to podman.

**Comment by baude** [comment]
I'm going to close this.  Retry is implemented I believe and really this issue would need to filed against another component if there was any way to do this...which I think @mtrmac is saying there isnt.
