### ISSUE TITLE
podman-system-service: support sighup reload

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#6255]
Long-running processes are commonly reloading their configs after receiving sighub. Since `podman-system-service` may be such a long-running process, it could be worth supporting such reloads. Configs to consider:
* containers.conf
* storage.conf
* registries.conf (+ registries.conf.d)
* ...?

Basically a similar behaviour as cri-o.

@baude @jwhonce @mheon @rhatdan @TomSweeneyRedHat WDYT?

**Comment by mheon** [comment]
This could be as simple as stopping + recreating our `libpod.Runtime`, though I'm not sure if that will be enough - some of our config logic is wired as `sync.Once` IIRC.

**Comment by mheon** [comment]
Initial look suggests that a lot of rootless paths are `sync.Once`'d. And not much else. This might end up being not that bad.

**Comment by rhatdan** [comment]
containers.conf is sync.Onced.  But that does not mean the global data could not be substituted for by calling another function.  The `podman system service` is not supposed to be a long running service in general, but I guess could end up that way if under heavy load.
In a perfect world, we could watch for the config file changes with INotify and reload automatically.  But this could become difficult with lots of config files.

**Comment by rhatdan** [comment]
SGTM
@QiWang19 PTAL.
I think you would need to add signal handling to podman and then add interfaces to the containers.conf, storage.conf, registries.conf to reload their config.

**Comment by rhatdan** [comment]
@QiWang19 Could you add an interface to containers/common to reload configuration.
