### ISSUE TITLE
[apiv2] command can't be executed correctly by attached running container

### ISSUE THREAD

**Issue by chuanchang** [containers/podman#6263]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1.  ./bin/podman system service --timeout 0 tcp:127.0.0.1:8080

2.  to run a container

3. to attach the above running container and execute command

**Describe the results you received:**
```
[fedora@fedora32 libpod]$ curl -v -X POST http://localhost:8080/v1.40/libpod/containers/myalpine/attach?stdin=1&stdout=1
[1] 104589
[fedora@fedora32 libpod]$ *   Trying ::1:8080...
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /v1.40/libpod/containers/myalpine/attach?stdin=1 HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.69.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 101 UPGRADED
< Content-Type: application/vnd.docker.raw-stream
< Connection: Upgrade
< Upgrade: tcp
<
pwd
/home/fedora/go/src/github.com/containers/libpod
[fedora@fedora32 libpod]$ pwd
/home/fedora/go/src/github.com/containers/libpod

NOTE: command is executed in host namespace not inside the container

[fedora@fedora32 libpod]$ ./bin/podman exec myalpine pwd
/
```

**Describe the results you expected:**
```
command is executed inside the container and output correct result
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            2.0.0-dev
RemoteAPI Version:  1
Go Version:         go1.14.2
Git Commit:         4611ff5ce4ff67a142363ab66e10944bfc40f860
Built:              Fri May 15 03:26:27 2020
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0-dev
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.15-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.15, commit: 33da5ef83bf2abc7965fc37980a49d02fdb71826'
  cpus: 4
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: fedora32
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.6.10-300.fc32.x86_64
  linkmode: dynamic
  memFree: 715292672
  memTotal: 4118323200
  ociRuntime:
    name: crun
    package: crun-0.13-2.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.0.0-1.fc32.x86_64
    version: |-
      slirp4netns version 1.0.0
      commit: a3be729152a33e692cd28b52f664defbf2e7810a
      libslirp: 4.2.0
  swapFree: 0
  swapTotal: 0
  uptime: 171h 35m 36.9s (Approximately 7.12 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/fedora/.config/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 3
    stopped: 3
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.0.0-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.0.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/fedora/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 5
  runRoot: /run/user/1000/containers
  volumePath: /home/fedora/.local/share/containers/storage/volumes
version:
  Built: 1589513187
  GitCommit: 4611ff5ce4ff67a142363ab66e10944bfc40f860
  GoVersion: go1.14.2
  OsArch: linux/amd64
  RemoteAPIVersion: 1
  Version: 2.0.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
[fedora@fedora32 libpod]$ git rev-parse HEAD
4611ff5ce4ff67a142363ab66e10944bfc40f860
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Openstack VM

**Comment by mheon** [comment]
I don't think we can test attach with curl, and I'm 99% certain that your command is actually running in the host's shell, not being forwarded to the container. The URL itself seems to have some escaping issues.

I can see streaming output from a container started as `podman run -t -i --rm --name testctr alpine top` with `sudo curl --unix-socket /var/run/podman/podman.sock -v -X POST 'http://localhost:8080/v1.40/libpod/containers/testctr/attach'` but nothing I type is forwarded to the container - it seems like a curl issue, potentially? This is also the best-case scenario - a container without `-t` will produce unreadable binary gibberish that cannot be interpreted by curl.

**Comment by Edward5hen** [comment]
> I don't think we can test attach with curl, and I'm 99% certain that your command is actually running in the host's shell, not being forwarded to the container. The URL itself seems to have some escaping issues.
> 
> I can see streaming output from a container started as `podman run -t -i --rm --name testctr alpine top` with `sudo curl --unix-socket /var/run/podman/podman.sock -v -X POST 'http://localhost:8080/v1.40/libpod/containers/testctr/attach'` but nothing I type is forwarded to the container - it seems like a curl issue, potentially? This is also the best-case scenario - a container without `-t` will produce unreadable binary gibberish that cannot be interpreted by curl.

@mheon what is the best way to test this scenario? I agree curl is not a good option.

**Comment by edsantiago** [comment]
I'm going to recommend closing this issue. As reported, it is a problem with the reporter's setup, not podman: the reporter is failing to use quotes in the curl command, which of course makes the shell interpret `&` as 'background me'.

curl works perfectly fine with attach and stdout, it just (unsurprisingly) does not handle stdin:
```console
$ podman run -d --name foo alpine_labels top
$ curl -X POST -o - 'http://localhost:9999/v1.40/libpod/containers/foo/attach?stdin=1&stdout=1'
[pause for a second, then clears screen and displays the running 'top' output]
```
It works fine with `nc` but devising an actually useful test of this is left as an exercise for the reader:
```console
$ podman run -d -it --name foo alpine_labels sh                                                                                                 -
b3b5b52f753abea712a8be565c78078c61405a1217f17aa6b652111aaaf13197
$ nc localhost 9999
POST /v1.40/libpod/containers/foo/attach?stdin=1&stdout=1 HTTP/1.1
Host: localhost

HTTP/1.1 101 UPGRADED
Content-Type: application/vnd.docker.raw-stream
Connection: Upgrade
Upgrade: tcp

date
date
Wed Jul  8 16:52:41 UTC 2020
/ # ^[[60;5Rs
```

**Comment by Edward5hen** [comment]
> I'm going to recommend closing this issue. As reported, it is a problem with the reporter's setup, not podman: the reporter is failing to use quotes in the curl command, which of course makes the shell interpret `&` as 'background me'.
> 
> curl works perfectly fine with attach and stdout, it just (unsurprisingly) does not handle stdin:
> 
> ```
> $ podman run -d --name foo alpine_labels top
> $ curl -X POST -o - 'http://localhost:9999/v1.40/libpod/containers/foo/attach?stdin=1&stdout=1'
> [pause for a second, then clears screen and displays the running 'top' output]
> ```
> 
> It works fine with `nc` but devising an actually useful test of this is left as an exercise for the reader:
> 
> ```
> $ podman run -d -it --name foo alpine_labels sh                                                                                                 -
> b3b5b52f753abea712a8be565c78078c61405a1217f17aa6b652111aaaf13197
> $ nc localhost 9999
> POST /v1.40/libpod/containers/foo/attach?stdin=1&stdout=1 HTTP/1.1
> Host: localhost
> 
> HTTP/1.1 101 UPGRADED
> Content-Type: application/vnd.docker.raw-stream
> Connection: Upgrade
> Upgrade: tcp
> 
> date
> date
> Wed Jul  8 16:52:41 UTC 2020
> / # ^[[60;5Rs
> ```

Understood, thanks for the answer!
