### ISSUE TITLE
Shell completion

### ISSUE THREAD

**Issue by Luap99** [containers/podman#6440]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

The current bash autocompletion is hard to maintain and buggy. Cobra can create completion shell scripts. This was already tried in PR #4768 but dropped because the lack of autocompletion support for containers/pods/volumes/etc...

With the current cobra version 1.0.0 you can now add a custom function to do this for flags and args
**cobra documentation:**
[main completion](https://github.com/spf13/cobra/blob/master/bash_completions.md#1-custom-completions-of-nouns-written-in-go)
[flag completion](https://github.com/spf13/cobra/blob/master/bash_completions.md#1-custom-completions-of-flags-written-in-go)

With this it would be possible to create autocompletion scripts for bash, zsh, fish, and powershell!

I would take the time to implement this if this is wanted?

**Comment by TomSweeneyRedHat** [comment]
@Luap99 we're always open to contributions!  I'd say start with a small subset and we can build from there.  We also use some Cobra flags that are defined in Buildah.  I know that's so for the build command and I think the commit command to.

**Comment by rhatdan** [comment]
Skopeo also.  My only concern would be around more advanced features like completions of container names or image names.  Plus option values.  But having the tool automatically generate most of this would be great.

**Comment by Luap99** [comment]
OK, so i started testing this a bit and it looks like that completion for the build command will also be added automatically. I agree that completion for containers/images... is a must have but this also is doable. I will open a PR soon so you can take a look :)

**Comment by rhatdan** [comment]
Great thanks.

**Comment by vrothberg** [comment]
Note that we tried using Cobra for completions various times in our projects and failed. We cannot really automate code generation without context. Completions for volumes, images, containers and so on all need context knowledge that Cobra does not have.

> The current bash autocompletion is hard to maintain and buggy

That quite ignores the benefits of the manually-maintained script: just do a `podman run [TAB]`.

**Comment by rhatdan** [comment]
Getting closer on this.

**Comment by rhatdan** [comment]
@Luap99 How close are we on this?
