### ISSUE TITLE
A bug in Dockerfile

### ISSUE THREAD

**Issue by wangluochao902** [containers/podman#6475]
https://github.com/containers/libpod/blob/95ea39edf34e4de4450c1674721ab02a7cf6a327/contrib/podmanimage/upstream/Dockerfile#L58
Hi, we are developing a tool to detect typos/bugs in dockerfiles automatically. Our tool finds a potential bug above. Is it a bug? we believe there is a redundant blackslash "\\" at the beginning of the line. Our tool is currently available here https://wangluochao902.github.io/clcheck/

**Comment by vrothberg** [comment]
Thanks for opening the issue and for sharing the tool!

The backslash won't do any harm but it certainly is confusing. Would you be interested in opening a PR to fix it?

**Comment by rhatdan** [comment]
This syntax is legal, and basically eliminates anyone having done a `alias cp=cp ...` in shell.
This could be a problem if for some reason a .bashrc or .bash_profile had setup an alias.
Most likely removing it would not be a problem.  But it is definelty not invalid syntax.

**Comment by edsantiago** [comment]
@TomSweeneyRedHat git blames you for introducing the backslash, in #3287 almost exactly one year ago. The commit message nor PR comments do not explain why you added the backslash. Do you remember?

**Comment by TomSweeneyRedHat** [comment]
@edsantiago the use of the backslash was discussed in the review comments in #3287.  From what I recall the build hung without it.

**Comment by edsantiago** [comment]
I'm so sorry - it's very prominently discussed, in fact. I don't know how I missed it and apologize for bothering you.

**Comment by wangluochao902** [comment]
Since it is not a bug, then there is a bug in our tool. Thank you for the helpful discussion.

**Comment by rhatdan** [comment]
Yes @wangluochao902 \COMMAND should be ignored, as bash allows this syntax to remove alias commands.

**Comment by zhangguanzhang** [comment]
could use `/usr/bin/cp`

**Comment by rhatdan** [comment]
Yes that would work also.
