### ISSUE TITLE
Issue with `podman play kube` on Ubuntu

### ISSUE THREAD

**Issue by mheon** [containers/podman#6506]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

On Ubuntu, the E2e test `podman generate with user and reimport kube on pod` ([link](https://github.com/containers/libpod/blob/master/test/e2e/generate_kube_test.go#L256)) fails. We have temporarily disabled the test.

The error message is:
```
Error: container_linux.go:349: starting container process caused "error adding seccomp rule for syscall socket: requested action matches default action of filter": OCI runtime error
```

I believe this is related to the recent vendor of https://github.com/seccomp/containers-golang/pull/27 into Podman. The error message in question is generated by runc when trying to add a seccomp rule whose action matches the default action of the policy; my current theory is that the specific errno number in that PR is being dropped, causing the rule to just have ActErrno - which is exactly identical to the default action.

It is presently unclear why this only occurs on one test for `podman play kube`.

**Steps to reproduce the issue:**

1. Create an Ubuntu 20.04 VM

2. Clone Podman repository and install all dependencies

3. Run E2E tests

**Describe the results you received:**

Test fails

**Describe the results you expected:**

Test succeeds

**Additional information you deem important (e.g. issue happens only occasionally):**

Core difference here appears to be crun (Fedora) vs runc (Ubuntu)

**Output of `podman version`:**

Latest master

**Comment by mheon** [comment]
@rhatdan @giuseppe PTAL

**Comment by giuseppe** [comment]
I think we need an updated runc that has: https://github.com/opencontainers/runc/pull/2424

**Comment by rhatdan** [comment]
@lsm5 PTAL

**Comment by lsm5** [comment]
`/usr/bin/runc` on Ubuntu is owned by the distro default runc. I have set dependencies to use distro runc by default since that seemed good enough for most cases. Would it be ok to let this be until Ubuntu updates its runc?

**Comment by rhatdan** [comment]
@giuseppe @lsm5 Is this still an issue, has the runc been  updated?  Should we switch to crun?

**Comment by lsm5** [comment]
@mheon how's this looking now?

**Comment by mheon** [comment]
Still being skipped on Ubuntu. I'll make a PR to try reenabling and see if it still explodes.

**Comment by mheon** [comment]
https://github.com/containers/podman/pull/7024
