### ISSUE TITLE
CI flake: podman run --conmon-pidfile: /proc/PID/exe is empty

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#6519]
cirrus-flake-xref is reporting three instances of this flake since May 27:
```
not ok 19 podman run --conmon-pidfile --cidfile
#   `is "$(readlink /proc/$conmon_pid/exe)" ".*/conmon"  \' failed
# $ ./bin/podman run --name sPARAiXiRX --conmon-pidfile=/tmp/podman_bats.hie4Cf/pidfile --cidfile=/tmp/podman_bats.hie4Cf/cidfile --detach quay.io/libpod/alpine_labels:latest sleep infinity
# 3db731b05f57bcc68afa6e48ea7df236786935648136065c9e4463ff118345ca
# #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# #|     FAIL: conmon pidfile (= PID 89369) points to conmon process
# #| expected: '.*/conmon'
# #|   actual: ''
# #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
That is: `podman run --conmon-pidfile` is writing a pidfile with a number in it. My code is doing `readlink /proc/PID/exe`, expecting it to be `/path/to/conmon`, but it's empty.

So far only rootless, and only in `fedora-32 : special_testing_rootless`. Logs: [PR 6402](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4808455686979584/html/system_test.log.html), [PR 6467](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6212888014618624/html/system_test.log.html), and [PR 6500](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4830747674542080/html/system_test.log.html).

This is probably my bug to fix, in my test code, but I will need help: can anyone understand how this can happen? Can podman write the wrong PID? Can conmon exit or fork/exit?

The test code itself is absurdly simple:
```bash
conmon_pid=$(< $pidfile)
is "$(readlink /proc/$conmon_pid/exe)" ".*/conmon"  \
   "conmon pidfile (= PID $conmon_pid) points to conmon process"
```

**Comment by mheon** [comment]
If the container in question exited, its Conmon would also go away. I wonder if something is killing it (or causing the container to exit immediately after it starts)

**Comment by mheon** [comment]
Also, is Conmon still running, just with an empty `/proc/$PID/exe`? Or is it completely dead?

**Comment by edsantiago** [comment]
The container command is `sleep infinity`; I should've included that.

Without instrumenting the script, I have no way of knowing if the pid is running or in fact anything else about the system.

**Comment by rhatdan** [comment]
@edsantiago has this issue disappeared?

**Comment by edsantiago** [comment]
Not seen again since initial report[*]. Closing.

 [*] Not seen by cirrus-flake-summarize, at least. That is not a guarantee that the problem hasn't occurred, because cirrus-flake-summarize does not look at errors in closed-without-merging PRs nor in CI runs that were followed by a new force-push. But it's the best I can do.
