### ISSUE TITLE
[APIv2] volume ls output no "UsageData","Status"

### ISSUE THREAD

**Issue by yuhuijiang** [containers/podman#6526]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

volume ls output no "UsageData","Status" parameters

**Steps to reproduce the issue:**

1. podman system service --timeout 0 tcp:127.0.0.1:8080

2. curl -s http://localhost:8080/v1.40/libpod/volumes/json | jq

3. Check the output

**Describe the results you received:**
[
  {
    "Name": "demo",
    "Driver": "local",
    "Mountpoint": "/var/lib/containers/storage/volumes/demo/_data",
    "CreatedAt": "2020-06-08T15:48:59.257413586-04:00",
    "Labels": {},
    "Scope": "local",
    "Options": {}
  },
  {
    "Name": "test0142",
    "Driver": "local",
    "Mountpoint": "/var/lib/containers/storage/volumes/test0142/_data",
    "CreatedAt": "2020-06-08T15:28:43.173893297-04:00",
    "Labels": {
      "helloname": "yujiang",
      "time": "2020"
    },
    "Scope": "local",
    "Options": {}
  }
]

**Describe the results you expected:**
According to http://docs.podman.io/en/latest/_static/api.html#operation/listVolumes, the output should contain "UsageData","Status"

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.9.3
RemoteAPI Version:  1
Go Version:         go1.14.3
Git Commit:         8891b82332de4afa23f935b58263d08a3a5c6d95
Built:              Mon Jun  8 15:21:36 2020
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: 8891b82332de4afa23f935b58263d08a3a5c6d95
  goVersion: go1.14.3
  podmanVersion: 1.9.3
host:
  arch: amd64
  buildahVersion: 1.14.9
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.17-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.17, commit: bb8e273f5925c1a51737644637ef65d094a67ab1'
  cpus: 4
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: hp-dl360g5-01.mpc.lab.eng.bos.redhat.com
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.6.16-300.fc32.x86_64
  memFree: 573079552
  memTotal: 2072551424
  ociRuntime:
    name: crun
    package: crun-0.13-2.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 2193879040
  swapTotal: 2210394112
  uptime: 11h 21m 2.96s (Approximately 0.46 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 0
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
fadora32

**Comment by rhatdan** [comment]
@QiWang19 PTAL
@lsm5 Are you working on this?

**Comment by lsm5** [comment]
Haven't touched this in the last couple weeks, it's cool with me if @QiWang19 takes it.

**Comment by QiWang19** [comment]
Do the docs need a fix or the UsageData should be added? https://docs.docker.com/engine/api/v1.40/#operation/VolumeList has no `UsageData` field. @jwhonce @rhatdan?
