### ISSUE TITLE
[APIv2] volume rm force parameter not implement

### ISSUE THREAD

**Issue by yuhuijiang** [containers/podman#6527]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

While removing a using volume by force=true, but it doesn't work as expected

**Steps to reproduce the issue:**

1. podman system service --timeout 0 tcp:127.0.0.1:8080

2. curl -X DELETE  http://localhost:8080/v1.40/libpod/volumes/test?force=true -v

3. Check the output

**Describe the results you received:**
*   Trying ::1:8080...
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> DELETE /v1.40/libpod/volumes/test?force=true HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.69.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Type: application/json
< Date: Mon, 08 Jun 2020 20:07:22 GMT
< Content-Length: 378
< 
{"cause":"container state improper","message":"error removing container 5f1d5c6c6610e317c48e1ca47489dc8a20926e81d871e1c5c4fe3b2848d1fbb2 that depends on volume test: cannot remove container 5f1d5c6c6610e317c48e1ca47489dc8a20926e81d871e1c5c4fe3b2848d1fbb2 as it is running - running or paused containers cannot be removed without force: container state improper","response":500}

**Describe the results you expected:**
should remove the using volume 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.9.3
RemoteAPI Version:  1
Go Version:         go1.14.3
Git Commit:         8891b82332de4afa23f935b58263d08a3a5c6d95
Built:              Mon Jun  8 15:21:36 2020
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: 8891b82332de4afa23f935b58263d08a3a5c6d95
  goVersion: go1.14.3
  podmanVersion: 1.9.3
host:
  arch: amd64
  buildahVersion: 1.14.9
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.17-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.17, commit: bb8e273f5925c1a51737644637ef65d094a67ab1'
  cpus: 4
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: hp-dl360g5-01.mpc.lab.eng.bos.redhat.com
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.6.16-300.fc32.x86_64
  memFree: 573079552
  memTotal: 2072551424
  ociRuntime:
    name: crun
    package: crun-0.13-2.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 2193879040
  swapTotal: 2210394112
  uptime: 11h 21m 2.96s (Approximately 0.46 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 0
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
fadora32

**Comment by mheon** [comment]
@ParkerVR PTAL. Feel free to reach out to me or @jwhonce for help getting started!

**Comment by ParkerVR** [comment]
Not a Bug - This behavior is intended in order to maintain consistency with `docker volume rm --force` and `podman volume remove -f`, both of which do not remove volumes in use

**Comment by rhatdan** [comment]
@ParkerVR That is exactly the purpose of the --force
podman volume rm --help
...
  -f, --force   Remove a volume by force, even if it is being used by a container

man podman-volume-rm
...
       Remove a volume by force.  If it is being used by containers, the containers will be removed first.

**Comment by mheon** [comment]
@rhatdan I investigated this one with @ParkerVR and @baude last night, and ended up breaking out Docker to see what they do with `--force` so we can match them in the API. The answer is that Docker's `--force` acts absolutely nothing like our `--force`. We assume `--force` means "remove containers, but only if they're not running". Docker takes `force` to mean the same as GNU coreutils `rm` does - "do not error when asked to remove something that does not exist". So `docker volume rm DOESNOTEXIST` will fail, but `docker volume rm --force DOESNOTEXIST` will succeed.

This is very different from how removing images and containers with --force works, and is honestly very confusing. But I think we need to adopt the Docker behaviour, at least on the API side.

**Comment by mheon** [comment]
We should discuss more in detail at scrum, though.

**Comment by rhatdan** [comment]
What happens when a container is using a volume and the user attempts to remove the volume with a force?  It should remove the container and then the volume, is what I would assume.

**Comment by mheon** [comment]
With Docker, and the Docker API? No, it will not do that. It will error that the volume is in use.

**Comment by rhatdan** [comment]
@mheon Can we close this issue, Did we remove the ability to pass the force flag?

**Comment by mheon** [comment]
This one should be done
