### ISSUE TITLE
Feature request: Allow container to override /proc/sys/kernel/core_pattern

### ISSUE THREAD

**Issue by kgibm** [containers/podman#6528]
/kind feature

**Description**

After some customers upgraded from OCP 3.11 to 4, they can no longer **easily** acquire core dumps of a container process which are a common diagnostic used by [OpenJ9 Java](https://www.eclipse.org/openj9/) for [memory analysis (e.g. OutOfMemoryErrors, sizing, etc.)](https://www.eclipse.org/openj9/docs/dump_systemdump/) using the [Eclipse Memory Analyzer Tool](https://www.eclipse.org/mat/) and [advanced debugging](https://www.ibm.com/developerworks/library/j-memoryanalyzer/index.html) using [-Xdump](https://www.eclipse.org/openj9/docs/xdump/) and [-Xtrace](https://www.eclipse.org/openj9/docs/xtrace/).

This is because `/proc/sys/kernel/core_pattern` in 3.11 was the default of `core` allowing the core to be produced within the container, but in 4, it's `|/usr/lib/systemd/systemd-coredump [...]` which means it goes to `/var/lib/systemd/coredump/` **in the host** and it requires root access to read (e.g. `sudo coredumpctl -o core.dmp dump ${PID}`). This creates significant friction for customers to use this diagnostic feature because there is often a lot of bureaucracy to get access to a container **host**, especially with root access.

This feature request is to allow containers to have their own `/proc/sys/kernel/core_pattern` independent of the host. This could be accomplished with a podman runtime flag when starting the container (similar to `--ulimit core=-1`). Perhaps this requires an accompanying Linux feature.

Note that the way J9 accomplishes non-destructively gathering core dumps on Linux is by [forking and killing the forked process](https://www.eclipse.org/openj9/docs/xdump/#system-dumps-on-linux):

> Linux does not provide an operating system API for generating a system dump from a running process. The VM produces system dumps on Linux by using the fork() API to start an identical process to the parent VM process. The VM then generates a SIGSEGV signal in the child process. The SIGSEGV signal causes Linux to create a system dump for the child process. The parent VM processes and renames the system dump, as required, by the -Xdump options, and might add additional data into the dump file.

Symptoms of this issue for others searching are:

* `JVMPORT030W /proc/sys/kernel/core_pattern setting "|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h %e" specifies that the core dump is to be piped to an external program.  Attempting to rename either core or core.190.`
* `JVMDUMP012E Error in System dump: The core file created by child process with pid = 190 was not found. Expected to find core file with name "/opt/ibm/wlp/output/defaultServer/core.190"`

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by navidsh** [comment]
**Output of `podman version`:**

```
$ podman version
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.15-1.rhaos4.3.el8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.15, commit: 4be4250b123dba66a8d43ea094eb168da2ebed0f'
  Distribution:
    distribution: '"rhcos"'
    version: "4.3"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 811122688
  MemTotal: 16814645248
  OCIRuntime:
    name: runc
    package: runc-1.0.0-67.rc10.rhaos4.3.el8.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: worker1.shames.os.fyre.ibm.com
  kernel: 4.18.0-147.8.1.el8_1.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /bin/slirp4netns
    Package: slirp4netns-0.4.2-4.git21fdece.el8.x86_64
    Version: |-
      slirp4netns version 0.4.2+dev
      commit: 21fdece2737dc24ffa3f01a341b8a6854f8b13b4
  uptime: 520h 55m 2.81s (Approximately 21.67 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - docker.io
store:
  ConfigFile: /var/home/core/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-5.module+el8.1.1+6114+953c5a57.x86_64
      Version: |-
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  GraphRoot: /var/home/core/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /run/user/1000/containers
  VolumePath: /var/home/core/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ rpm -q podman
podman-1.6.4-10.rhaos4.3.el8.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OpenShift `4.3.19`

**Comment by giuseppe** [comment]
`/proc/sys/kernel/core_pattern` seems to not be namespaced in the kernel; so it is not possible to set a different value for the container.  You can do a quick test by running a privileged container and trying to change the value of `/proc/sys/kernel/core_pattern`.  You'll see the change is propagated to the host.

It seems like an interesting feature, but we must first make sure it is supported by the kernel and then it can be used by Podman.

For the time being, I'd suggest to override the `/proc/sys/kernel/core_pattern` setting to use a file.

@ebiederm is there any chance to have `/proc/sys/kernel/core_pattern` namespaced?

**Comment by kgibm** [comment]
@giuseppe Thanks, that's what I guessed also. We don't want to use privileged to update the host core_pattern as that affects other containers who may not want in-container core files.

If anything is needed for me to open a feature request for the Linux kernel, let me know. Thanks.

**Comment by ebiederm** [comment]
Is there any need to support a core dump helper program?

There have been a couple attempts in the past to implement this and they have all gotten
hung up in the question of how to implement the core dump helper program.    In the long term
if systemd wants to capture core dumps we will probably have to work through the core dump helper program logic, but we don't have to do that for a first implementation.

You would also need to be root in a container.

Are either of those a problem?

@kgibm the best way is to describe the problem and ask on the container mailling list.

**Comment by kgibm** [comment]
@ebiederm Thanks, here are my thoughts:

> Is there any need to support a core dump helper program?

For the J9 use case, no. We just want to set it to `core` and produce the core in the current working directory. But I guess others might want a helper program and I guess the kernel folks might not like core_pattern behaving differently within a container.

> You would also need to be root in a container.

Could it be specified on the podman run command instead (like with `--ulimit core=-1`)?

> the best way is to describe the problem and ask on the container mailling list.

Which mailing list is this and any tips on how to ask the question?

**Comment by rhatdan** [comment]
@ebiederm Could you answer @kgibm   question?

**Comment by rhatdan** [comment]
Since this is a kernel issue, I am going to close, please open this issue against the kernel.
