### ISSUE TITLE
[APIv2]: some DOC issues

### ISSUE THREAD

**Issue by Edward5hen** [containers/podman#6547]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
When our team - Atomic QE is verifying the APIv2 JIRA cards, we find below issues that relate to the [API v2 DOC](http://docs.podman.io/en/latest/_static/api.html)

- container checkpoint. There is no response samples for normal status(return 200)
- container restore. This doc looks like a copy from the container checkpoint, so there are some places not updated for restore command.
    - ignoreRootFS: should be "do not include root file-system changes when importing" but not "exporting"
    - "200 tarball returned in body if exported" need to be updated as this is a description for checkpoint
    - also miss response samples for normal status
- pod stats. The output of the API does not include "Process" and "Titles". Those are output from pod top. The output is similar to podman pod stats just a list of dict including the statistics.
- pod top. ps_args arguments are separated with "," which is not usual in urls. So it is better to include this in the doc, otherwise it is very hard for users to find out this.
- The 'header parameters' and request samples are lost in http://docs.podman.io/en/latest/_static/api.html#operation/buildImage
-  'Libpod Build Image' has the same issue as the above one and no request samples - http://docs.podman.io/en/latest/_static/api.html#operation/libpodBuildImage
- Need document for query parameters 'comment', which is only used w/ docker format, and successful return code should be 200 not 201 - http://docs.podman.io/en/latest/_static/api.html#operation/libpodCommitContainer
- Overall the section "header Parameters" is needed for some command.

Besides, I'm not able to find the corresponding DOC for below commands/JIRA cards which have been all moved to DONE.
- logout
- diff
- port
- abi run
- container prune
- tunnel attach
- mount (ABI only)
- cp(ABI)

**Comment by rhatdan** [comment]
@Edward5hen Do we still have this issue?  @jwhonce @baude Is this fixed?

**Comment by Edward5hen** [comment]
> @Edward5hen Do we still have this issue? @jwhonce @baude Is this fixed?

@rhatdan yes, we still have this issue.

**Comment by baude** [comment]
@jwhonce can you own this and feel free to break cards out for it and assign to folks.

**Comment by rhatdan** [comment]
@ashley-cui Any chance you could look at this?

**Comment by ashley-cui** [comment]
@rhatdan yep, ill give it a go soon

**Comment by rhatdan** [comment]
@ashley-cui @TomSweeneyRedHat @baude @jwhonce This issue is still active and really needs to be cleaned up.

**Comment by rhatdan** [comment]
@Edward5hen Has this improved at all?

**Comment by Edward5hen** [comment]
@rhatdan no. Dan, what does "ABI" mean for some of the APIs? What's the difference for testing the ABI only ones?

**Comment by rhatdan** [comment]
API is for podman-remote (And for other APIv2 protocols) and ABI is for local podman.  Some commands are not available for remote, so I think we want to test the local ones.

**Comment by Edward5hen** [comment]
Thank you!

**Comment by rhatdan** [comment]
I am going to assume this is all fixed now, reopen if I mistaken, or better yet open new issues with specific problems.
