### ISSUE TITLE
containers killed when restarting a systemd service

### ISSUE THREAD

**Issue by parmentelat** [containers/podman#6549]
I am transitioning a system from docker to podman; my current setup runs on 

* fedora32
* vanilla podman-1.9.3-1.fc32.x86_64 
* cgroupv2 aka unified hierarchy

I am using this in pre-production and am rather pleased with 

In essence we have

* an main uwsgi application powering a django app, started by systemd
* the main app forks a bash script that in turn spawns containers with  
  `podman run --detach --rm ...`

I am surprised to see that restarting the main app with `systemctl restart`, which in turn
will trigger `kill -INT` on the uwsgi instance, is causing the containers to be killed in
turn (which in operations is of course a catastrophic event)

I realize I have the wrong mental model here; in terms of process hierarchy, I can see 
each container materialized as a `conmon` process whose parent process is, as expected, 
systemd with pid 1; so based on that i thought I'd be safe to kill the `uwsgi` process
without interfering with container execution

```
# pstree
systemd─┬─NetworkManager───2*[{NetworkManager}]
        ├─3*[abrt-dump-journ]
        ├─abrtd───2*[{abrtd}]
        ├─agetty
        ├─atd
        ├─auditd───{auditd}
        ├─chronyd
        ├─12*[conmon─┬─tini───runuser───jupyter-noteboo─┬─python───39*[{python}]]
        │            │                                  └─2*[{jupyter-noteboo}]]
        │            └─{conmon}]
```

But that's not what I see; so digging further I noticed that these `conmon` processes 
appeared in the output of 

```
# systemctl status the-main-uwsgi.service
● nbh-django.service - the nbhosting django app as a uwsgi instance
     Loaded: loaded (/etc/systemd/system/nbh-django.service; enabled; vendor preset: disabled)
     Active: active (running) since Tue 2020-06-09 15:22:49 CEST; 18h ago
   Main PID: 1344921 (uwsgi)
     Status: "uWSGI is ready"
      Tasks: 153 (limit: 309370)
     Memory: 366.0M
        CPU: 3min 35.897s
     CGroup: /system.slice/nbh-django.service
             ├─1344921 /usr/sbin/uwsgi --ini /etc/uwsgi.d/nbhosting.ini
             ├─1344921 /usr/sbin/uwsgi --ini /etc/uwsgi.d/nbhosting.ini
<snip>
             ├─1774675 /usr/bin/conmon --api-version 1 -s <snip>
             ├─1774675 /usr/bin/conmon --api-version 1 -s <snip>
<snip>
```

I must say the main reason why I am surprised is that the same architecture based on
docker was not exhibiting this behaviour; with the same app based on docker i could
restart any part of the system including the web app, or the docker daemon for that
matter, without affecting the running containers

So, my questions :

* why is that so ? am I right to conjecture that it is because the conmon processes
  are being stored in the same cgroup as the main uwsgi app, that the containers are
  affected by a kill on uwsgi ?

* so as a wild guess I have tried to add a `--cgroup-parent=MYAPP` to the `podman run` 
  command, but why am I getting the following error message ?

```
Jun 09 15:24:13 thermals uwsgi[1345101]: Error: did not receive systemd slice as cgroup parent when using systemd to manage cgroups: invalid argument
```

So, I can tell I'm a bit over my head here, could someone please shed some light on what I
am doing wrong, and the best angle to take so that the main web app can be restarted on
its own, without messing with the running containers; I've read about cgroup drivers, and
have the intuition it could be part of the solution, but I don't know how to use them...

Many thanks in advance for any tip

**Comment by parmentelat** [comment]
PS. just out of curiosity I have just confirmed that the same behaviour happens when running the kernel with cgroupv1, i.e. with `systemd.unified_cgroup_hierarchy=0`

**Comment by goochjj** [comment]
If you want to use systemd cgroup-manager, it requires a slice, not a service.  It defaults to /machine.slice/libpod-guid.scope and puts everything there.

If you want it to show under the service, you have to use the cgroupfs manager.

i.e. in my service file:
--cgroup-parent=/system.slice/%n --cgroup-manager cgroupfs

**Comment by goochjj** [comment]
You'll see them in `systemd-cgls`

**Comment by mheon** [comment]
Now that I'm thinking about this more - I think we're deliberately disabling putting Conmon in a separate cgroup in `podman generate systemd` unit files using `--cgroups=no-conmon`, but I forget exactly why (@vrothberg would know).

**Comment by vrothberg** [comment]
@giuseppe added that logic in https://github.com/containers/libpod/pull/4861 for backward compat. Newer Podman versions auto-detect when running in a systemd service and won't create a cgroup as systemd does not like monitoring processes in other cgroups.

**Comment by vrothberg** [comment]
@ parmentelat, can you share the unit file you are using? There are many potential pitfalls running podman in systemd.

**Comment by parmentelat** [comment]
@vrothberg my service unit file is here
https://github.com/parmentelat/nbhosting/blob/podman/systemd/nbh-django.service

In my use case, the service in question is just a web service that will spawn containers; whether this web service is up or not, should have no incidence on the peaceful continuation of already spawned containers; ; but I digress...

right now I'm using `KillMode=process`, with which IIUC `systemd` kills the main process subtree and ignores cgroups; with this setting my deployment is going rather nicely, and I can restart the django app with no incidence on running containers, so I'm kind of fine (like in: this issue is less serious to me than it was when I created this issue)

It'd be nice to have some control on the cgroups where the containers end up though; typically the application is about hosting notebooks for various courses, and one cgroup per course would make perfect sense from a resource management point of view

 thanks !

**Comment by goochjj** [comment]
@parmentelat isn't the default that every container gets its own cgroup?  Currently in /machine.slice/libpod-containerid.scope... So you already have container cgroup separation.  If you wanted to adjust the allocation you could, using cgroup-parent.  i.e. with systemd, perhaps --cgroup-parent machine-%{course}.slice or similar.

**Comment by parmentelat** [comment]
> On 15 Jun 2020, at 22:30, Joe Gooch <notifications@github.com> wrote:
> 
> 
> @parmentelat isn't the default that every container gets its own cgroup? Currently in /machine.slice/libpod-containerid.scope... So you already have container cgroup separation. If you wanted to adjust the allocation you could, using cgroup-parent. i.e. with systemd, perhaps --cgroup-parent machine-%{course}.slice or similar.

well right now I see this

# ps -o cgroup $(pgrep conmon)
CGROUP
0::/system.slice/nbh-django.service
0::/system.slice/nbh-django.service
<snip…>

so unless I have this very wrong, that means that all my containers end up in the same cgroup, and it’s also the same as the processes involved in the nbh-django service, no ?

I remember I have given this —cgroup-parent a try at the beginning of my investigation, but that did not pan out, I can’t remember exactly how right now,
I can try again and report back on this channel if that’s worth it

at the time it felt like it had to do with the cgroup manager; 
I still have to find an explanation about what the cgroup manager does exactly, and what are the available options; 
right now it looks like I use the systemd cgroup manager, from the commented contents of /usr/share/containers/containers.conf that reads
# cgroup_manager = "systemd"


thanks !

**Comment by goochjj** [comment]
But that's just conmon - the actual cgroup separation of the container processes is happening I'm guessing.

I'm curious how you're spawning the containers from your main app... You may want --cgroups enabled instead of --cgroups no-conmon - though, if what @vrothberg is saying is true and it'll just magically switch enabled back to "no-conmon" because it detects systemd, that would actually be contrary to what you want in this case... without looking at that code I'm not sure off the top of my head.

**Comment by goochjj** [comment]
Looks like it's detecting INVOCATION_ID in your environment.

What happens if you unset that env variable before calling podman run from your web application? i.e. `env -u INVOCATION_ID podman run ....`

**Comment by parmentelat** [comment]
yes this is better

before your suggestion I was getting this

```
root@thermals ~ (master *) # ps -o cgroup $(psfamily $CONMON)
CGROUP
0::/system.slice/nbh-django.service
0::/machine.slice/libpod-6f2945afaf06226270498ab7ebfe44b3d73e343af5b8376fb56fe84e06695273.scope
0::/machine.slice/libpod-6f2945afaf06226270498ab7ebfe44b3d73e343af5b8376fb56fe84e06695273.scope
0::/machine.slice/libpod-6f2945afaf06226270498ab7ebfe44b3d73e343af5b8376fb56fe84e06695273.scope
0::/machine.slice/libpod-6f2945afaf06226270498ab7ebfe44b3d73e343af5b8376fb56fe84e06695273.scope
```

and after I unset `INVOCATION_ID` I get this

```
root@thermals ~/nbhosting (podman *$=) # ps -o cgroup $(psfamily $CONMON)
CGROUP
0::/machine.slice/libpod-conmon-53966c45b575ad73dccd078fa581d55da1f788c4fcb52773c1a8ae27f7829621.scope
0::/machine.slice/libpod-53966c45b575ad73dccd078fa581d55da1f788c4fcb52773c1a8ae27f7829621.scope
0::/machine.slice/libpod-53966c45b575ad73dccd078fa581d55da1f788c4fcb52773c1a8ae27f7829621.scope
0::/machine.slice/libpod-53966c45b575ad73dccd078fa581d55da1f788c4fcb52773c1a8ae27f7829621.scope
0::/machine.slice/libpod-53966c45b575ad73dccd078fa581d55da1f788c4fcb52773c1a8ae27f7829621.scope
```

and for the record here's how I gather the process tree

```
function psfamily() {
    local thispid="$1"; shift
    echo $thispid
    local childlist=$(ps --ppid $thispid -o pid h)
    for pid in $childlist; do psfamily $pid; done
}
```

so bottom line, I guess I'm good on this one; thanks !

**Comment by goochjj** [comment]
HTH

**Comment by rhatdan** [comment]
@goochjj @vrothberg @mheon @parmentelat What is the scoop on this one?  Is it still an issue?

**Comment by goochjj** [comment]
I believe @parmentelat is all set... went with the best combination of options available.

**Comment by parmentelat** [comment]
yes I am fine indeed, thinks work fine for me at this point, thanks for checking
