### ISSUE TITLE
Is podman-remote-windows broken?

### ISSUE THREAD

**Issue by towe75** [containers/podman#6558]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'd like to use podman-remote-windows to interact with podman on my linux boxes. Ultimately i'd like to be able to use/debug/improve vscode integration.

For sure there are not many users on this platform (yet) but the experience for first time users is relatively bad because of terse documentation. I am willing to help testing and to submitting PR's, if appropriate, in order to improve the situation on windows. 

**Steps to reproduce the issue:**

1. Download zip file for podman-remote-windows from the release page

2. Unpack zip and try to run the executable

3. For podman release 1.9.2 i get simply this:

```
podman-remote-windows.exe version

time="2020-06-10T18:59:50+02:00" level=error msg="error validating engine configs: static directory must be an absolute path - instead got \"\\\\var\\\\lib\\\\containers\\\\storage\\\\libpod\""
```

4. Going back to 1.8.1 yields:

```
podman-remote-windows.exe version

time="2020-06-10T18:59:41+02:00" level=error msg="failed to setup podman build flags: failed to get container config: error validating engine configs: static directory must be an absolute path - instead got \"\\\\var\\\\lib\\\\containers\\\\storage\\\\libpod\""
Error: could not get runtime: dial unix /run/podman/io.podman: connect: A socket operation encountered a dead network.
```

**Describe the results you received:**

I can not use the remote command at all. 

**Additional information you deem important (e.g. issue happens only occasionally):**

Results when running podman-remote-windows.exe from the zip files and from msi setups are similar.

**Output of `podman info --debug`:**

Same like above, it does not print the info just the same errors.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows 10.0.18363, running podman-remote-windows.exe in a plain cmd.exe shell.

**Comment by towe75** [comment]
I ran a build from master and i get indeed a very different result now:

```
podman-remote-windows.exe --log-level debug --identity \Users\xxxxxx\.ssh\id_rsa  --url ssh://xxxxxx@10.x.x.x/run/podman/podman.sock?secure=True ps

time="2020-06-11T15:37:23+02:00" level=info msg="podman-remote-windows.exe filtering at log level debug"
time="2020-06-11T15:37:23+02:00" level=debug msg="Called podman-remote-windows.exe.PersistentPreRunE(podman-remote-windows.exe --log-level debug --identity \\Users\\xxxxx\\.ssh\\id_rsa --url ssh://xxxxx@10.x.x.x/run/podman/podman.sock?secure=True -r ps)"
Error: Failed to create sshClient: Connection to bastion host (ssh://xxxxx@x.x.x.x/run/podman/podman.sock?secure=True) failed.: ssh: handshake failed: ssh: host key mismatch
```

Clearly an improvement. But it's still unclear which ssh config directory is used. Connecting to the machine with ssh.exe and the given key works. There is a known_hosts entry for this host in my (windows) .ssh folder. 

Moreover i do not understand if i should use -r/--remote and --url or if i could use a profile definition in a toml configuration file like it was documented for older versions.  Can you clearify?

**Comment by mheon** [comment]
@jwhonce PTAL

**Comment by rhatdan** [comment]
@ashley-cui PTAL

**Comment by baude** [comment]
https://www.redhat.com/sysadmin/podman-clients-macos-windows

**Comment by baude** [comment]
this should now be fixed, ive also provided a brief how to
