### ISSUE TITLE
podman-remote: exec, then stop -a: given PIDs did not die within timeout

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#6573]
Failure seen in #6570 . [log](https://api.cirrus-ci.com/v1/task/6487475096911872/logs/integration_test.log). Reproducer:
```console
$ MYSOCK=unix:/tmp/mypodmansock
$ bin/podman --log-level=debug system service --timeout=0 $MYSOCK
```
Separate window:
```console
$ MYSOCK=unix:/tmp/mypodmansock
$ ./bin/podman-remote --url $MYSOCK run -d --name foo alpine top
47cb6de99d0885e802d101426c813b638f6fb5d8b0288db1b4c0926525365db1
$ ./bin/podman-remote --url $MYSOCK exec --workdir /missing foo pwd
[conmon:d]: exec with attach is waiting for start message from parent
[conmon:d]: exec with attach got start message from parent
chdir: No such file or directory: OCI runtime command not found error
$ ./bin/podman-remote --url $MYSOCK stop -a
Error: failed to stop 47cb6de99d0885e802d101426c813b638f6fb5d8b0288db1b4c0926525365db1: given PIDs did not die within timeout
```
back to server with debug log:
```
DEBU[1117] Stopping ctr 47cb6de99d0885e802d101426c813b638f6fb5d8b0288db1b4c0926525365db1 (timeout 10)
DEBU[1117] Stopping container 47cb6de99d0885e802d101426c813b638f6fb5d8b0288db1b4c0926525365db1 (PID 1174462)
DEBU[1117] Sending signal 15 to container 47cb6de99d0885e802d101426c813b638f6fb5d8b0288db1b4c0926525365db1
WARN[1127] Timed out stopping container 47cb6de99d0885e802d101426c813b638f6fb5d8b0288db1b4c0926525365db1, resorting to SIGKILL
DEBU[1127] Sending signal 9 to container 47cb6de99d0885e802d101426c813b638f6fb5d8b0288db1b4c0926525365db1
INFO[1132] Request Failed(Internal Server Error): failed to stop 47cb6de99d0885e802d101426c813b638f6fb5d8b0288db1b4c0926525365db1: given PIDs did not die within timeout
```

**Comment by rhatdan** [comment]
@mheon This might be something to do with your parallel PRs?

**Comment by mheon** [comment]
That second-to-last `podman exec` also exits 0 despite clearly showing a large number of error messages, which is not good

**Comment by mheon** [comment]
We somehow have two Conmons spawned for the abortive exec session, as well

**Comment by mheon** [comment]
Ah, I think one is a child of the other, so that ought to be fine...

**Comment by mheon** [comment]
It's related to having Conmon alive - `--exit-delay` keeps Conmon up for 300 seconds, idle and waiting to launch the cleanup command. Once it does, it stops/removes cleanly.

Does not seem to be related to `podman-remote`.

**Comment by mheon** [comment]
Ah - it is related to `remote` but only so far as the exit delay only occurs on `podman-remote exec`.

**Comment by mheon** [comment]
I see an extra process appearing inside the container. I think it's the fork()'d Conmon, which exec'd the OCI runtime but failed due to the error we saw here. The parent Conmon in the host namespace is sticking around for 300 seconds, and for some reason the child Conmon must be as well? Maybe we're not reaping it properly?

**Comment by mheon** [comment]
The process leftover in the container is definitely a zombie. This looks like an issue on the Conmon side.

**Comment by mheon** [comment]
Only happens when `-t` is not set.

I think there's probably a code path in Conmon that's not waiting for the PID of the OCI runtime if we get an error back during startup, causing a zombie to appear that we don't reap until Conmon itself dies. Unfortunately, that can be 300 seconds later, in the case of `podman-remote exec`.

**Comment by mheon** [comment]
@giuseppe @haircommander PTAL. I'm going to dig around to try and find it, but I'm not very used to the Conmon codebase.

**Comment by mheon** [comment]
https://github.com/containers/conmon/pull/181 fixed.

**Comment by mheon** [comment]
Closing, we should have a new-enough conmon landed.
