### ISSUE TITLE
Podman run with an image on an Additional Image Stores over NFS throws exception

### ISSUE THREAD

**Issue by gcs278** [containers/podman#6612]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman fails to run a container when the image exists on an Additional Image Store that is hosted over NFS. Here's the exception that get's thrown:

```
podman run -it localhost/test-image bash
Error: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/var/run/containers/storage/overlay-containers/e52f47d8f0f95be67901e50b1dc6c70486b90dfacb1aed4dfc16961d9b1fd671/userdata/run/secrets\\\" to rootfs \\\"/var/lib/containers/storage/overlay/a307af9c4112a7281dc1b886d20e7254800f0137e67e259ab991a460deb1e65f/merged\\\" at \\\"/var/lib/containers/storage/overlay/a307af9c4112a7281dc1b886d20e7254800f0137e67e259ab991a460deb1e65f/merged/run/secrets\\\" caused \\\"mkdir /var/lib/containers/storage/overlay/a307af9c4112a7281dc1b886d20e7254800f0137e67e259ab991a460deb1e65f/merged/run/secrets: operation not supported\\\"\"": OCI runtime error
```

Here's another server with a very similar exception:
```
podman run -it localhost/test-image bash
Error: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/root/containers/runroot/storage/overlay-containers/f92f06d4f1b54007132ff731ce633276fc41bdc0785b7f30157f0fa81ae7a15c/userdata/hostname\\\" to rootfs \\\"/root/containers/storage/overlay/e0a1b413d450d164f6ba469f615641d39322127283d1c6c6b062504643c7837c/merged\\\" at \\\"/root/containers/storage/overlay/e0a1b413d450d164f6ba469f615641d39322127283d1c6c6b062504643c7837c/merged/etc/hostname\\\" caused \\\"open /root/containers/storage/overlay/e0a1b413d450d164f6ba469f615641d39322127283d1c6c6b062504643c7837c/merged/etc/hostname: operation not supported\\\"\"": OCI runtime error
```

Running `podman images` lists these images on the NFS additional image store successfully. It is my impression that the overlay storage driver should work fine with a lower based NFS share (which is what Additional Image Stores should provide). I'm specifically working with RHEL8. Once I move the additional image store to a local file system, this exception disappears, and I can successfully run an container from this local additional image store. 

CRIO also fails to run images from an NFS Additional Image Store.
 
**Steps to reproduce the issue:**

1. Use `podman load` or `podman pull` to load an image into the runroot directory

2. Copy the contents of the directory runroot as specified in /etc/containers/storage.conf to the NFS mount point

3. `rm -rf <runroot>/*` to clear the default runroot location

4. Modify `additionalimagestores = [ ]` in /etc/containers/storage.conf to include the NFS mount point with the contents you copied off from runroot in step 2

4. Run `podman images` to show the R/O images
```
REPOSITORY                                  TAG     IMAGE ID         CREATED      SIZE      R/O
localhost/test-image                     latest   52aceac82312   2 weeks ago     316 MB    true
```

5. Attempt to run a container that is one of the R/O images

**Describe the results you received:**

```
podman run -it localhost/test-image bash
Error: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/var/run/containers/storage/overlay-containers/e52f47d8f0f95be67901e50b1dc6c70486b90dfacb1aed4dfc16961d9b1fd671/userdata/run/secrets\\\" to rootfs \\\"/var/lib/containers/storage/overlay/a307af9c4112a7281dc1b886d20e7254800f0137e67e259ab991a460deb1e65f/merged\\\" at \\\"/var/lib/containers/storage/overlay/a307af9c4112a7281dc1b886d20e7254800f0137e67e259ab991a460deb1e65f/merged/run/secrets\\\" caused \\\"mkdir /var/lib/containers/storage/overlay/a307af9c4112a7281dc1b886d20e7254800f0137e67e259ab991a460deb1e65f/merged/run/secrets: operation not supported\\\"\"": OCI runtime error
```

**Describe the results you expected:**
```
podman run -it localhost/test-image bash
# container successfully started
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 1.9.3
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.12.12
  podmanVersion: 1.9.3
host:
  arch: amd64
  buildahVersion: 1.14.9
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.17-1.el8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.17, commit: 184cd9a79d9f6eb857f79edfe14fba9711e29834'
  cpus: 10
  distribution:
    distribution: '"rhel"'
    version: "8.0"
  eventLogger: file
  hostname: rhel8-vm1
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-80.el8.x86_64
  memFree: 9024368640
  memTotal: 10055262208
  ociRuntime:
    name: runc
    package: containerd.io-1.2.4-3.1.el7.x86_64
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0-rc6+dev
      commit: 6635b4f0c6af3810594d2770f662f34ddc15b40d
      spec: 1.0.1-dev
  os: linux
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 5179961344
  swapTotal: 5179961344
  uptime: 916h 5m 36.72s (Approximately 38.17 days)
registries:
  search:
  - registry.redhat.io
  - quay.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 9
    paused: 0
    running: 0
    stopped: 9
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /root/nfs/shared
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 5
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.9.3-2.1.el8.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
1. NFS version 4.2.
2. Selinux is off
3. RHEL 8.0
4. Running podman as root

**Comment by giuseppe** [comment]
I've tried the same reproducer on Fedora and it works fine here (same podman version and with both the crun/runc OCI runtimes).

Could you provide the output for  `strace -f -vvv -s 4096 podman run localhost/test-image true`?

It seems so from the `podman info` output but just to make sure, are you running podman as root on the host?

**Comment by gcs278** [comment]
Correct. Using podman as root with RHEL 8.

Here's the logs: [podman-strace.txt](https://github.com/containers/libpod/files/4786941/podman-strace.txt)

**Comment by rhatdan** [comment]
Are the NFS shares mounted with no-root-squash?  This could be that the root user is being treated badly?

**Comment by gcs278** [comment]
Correct - the NFS options I was using in /etc/exportfs were *(rw, sync, no_root_squash)

**Comment by rhatdan** [comment]
Sadly no one has looked at this for a while.  Were you able to debug this any further?

**Comment by rhatdan** [comment]
@gcs278 Any movement onthis?

**Comment by gcs278** [comment]
@rhatdan Sorry, other priorities at the moment, but we are still very much interested in making this work. Still having the same issue with running over additionalImageStore over NFS, but haven't tried anything new yet.

**Comment by rhatdan** [comment]
Podman 2.1 is arriving on rhel8.3 very soon, could you try this out?

**Comment by rhatdan** [comment]
I believe this is fixed, reopen if I am mistaken.

**Comment by gcs278** [comment]
Sorry for the delay. It looks like we enabled `mount_program = "/usr/bin/fuse-overlayfs"` in our storage.conf configuration and that solved the issue. As far as I know, additionalImageStores wouldn't work over NFS for us without that mount_program set.
