### ISSUE TITLE
clean up GitHub labels

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#6617]
The list of labels got pretty long. While some can be removed, others seem redundant (e..g, "help wanted" and "contributor wanted").

Cc: @baude @mheon

**Comment by mheon** [comment]
There are a lot of duplicates for the kind/ set of labels - we have both `bug` and `kind/bug`. In those cases we should prefer `kind/bug` given the bot generates them.

A lot of the old `Release Notes x.y.z` labels can be simply removed.

**Comment by rhatdan** [comment]
@vrothberg @mheon Can you clean this up?

**Comment by vrothberg** [comment]
> @vrothberg @mheon Can you clean this up?

Sure!

**Comment by vrothberg** [comment]
Done.
