### ISSUE TITLE
inspect command: Populate Bridge field in network settings

### ISSUE THREAD

**Issue by drewbailey** [containers/podman#6618]
/kind feature

**Populate bridge field in network settings when applicable**

**Steps to reproduce the issue:**

1. `sudo podman run -m=40m -p 8080:89 --network=bridge redis`

2. `sudo podman inspect <container>`

**Describe the results you received:**

```json
    "NetworkSettings": {
      "EndpointID": "",
      "Gateway": "10.88.0.1",
      "IPAddress": "10.88.0.239",
      "IPPrefixLen": 16,
      "IPv6Gateway": "",
      "GlobalIPv6Address": "",
      "GlobalIPv6PrefixLen": 0,
      "MacAddress": "62:86:4f:c2:28:01",
      "Bridge": "",
      "SandboxID": "",
      "HairpinMode": false,
      "LinkLocalIPv6Address": "",
      "LinkLocalIPv6PrefixLen": 0,
      "Ports": [
        {
          "hostPort": 8080,
          "containerPort": 89,
          "protocol": "tcp",
          "hostIP": ""
        }
      ],
      "SandboxKey": "/var/run/netns/cni-5ada0c78-0a5f-ea18-a950-7141c110f46b"
    },
```
**Describe the results you expected:**

Bridge to be populated with the cni id of the bridge in use

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
→ podman version
Version:            1.9.3
RemoteAPI Version:  1
Go Version:         go1.13.8
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by QiWang19** [comment]
Do you mean there should  be `Network` field Under "NetworkSettings"?

```
"Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "0df86146427ffaaf905bee17342ed31d012d761fc34a8788584427f53e1ac99b",
                    "EndpointID": "bd120b2e6fd090dbb180342956f9daa440ea5a3db78466dc1ed19bf3ba197dfd",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }

```

**Comment by mheon** [comment]
No - that looks like the output of a network from `podman network create` - this is about populating the name of the CNI network that is being used by default, I believe

**Comment by rhatdan** [comment]
@QiWang19 @mheon What is the scoop on this issue?

**Comment by mheon** [comment]
Should be possible, but a little annoying to retrieve. Maybe a good job for
an intern?

**Comment by rhatdan** [comment]
Know one has worked on this, and it is still an issue.  (At least I verified the bug using the repeater above).

@containers/podman-maintainers Anyone want to take a look?

**Comment by rhatdan** [comment]
@baude do you have time for this?

**Comment by rhatdan** [comment]
Still an issue.

**Comment by rhatdan** [comment]
@mheon Any chance you can work on this?

**Comment by baude** [comment]
I can peek at it ...
