### ISSUE TITLE
"streaming output" test: constant flakes on ubuntu

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#6626]
The [Podman logs [It] streaming output test](https://github.com/containers/libpod/blob/d6965da26d194c7edfef65985d4a2c7b564a3fca/test/e2e/logs_test.go#L275) is broken on Ubuntu, or maybe it's reporting a real problem. It is flaking frequently in CI. Only in Ubuntu, AFAICT. 

Symptom: the `log -f` terminates successfully, then the next `podman run` (with same name) fails:
```
       Running: podman [options] run --rm --name logs-f-rm -dt docker.io/library/alpine:latest true
         Error: error creating container storage: the container name "logs-f-rm" is already in use by "6daa668028d4270d9d4bcfc66c415ce6a2a56b70e0b5753f9064dc46f7047da0". You have to remove that container to be able to reuse that name.: that name is already in use
```
Full history from cirrus-flake-xref:

* ubuntu-19 : test ubuntu-19
  * PR #6615
    * [06-16 06:04](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6499551370543104/html/integration_test.log.html#t--streaming-output--1)
    * [06-16 06:04](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6499551370543104/html/integration_test.log.html#t--streaming-output--2)
    * [06-16 06:04](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6499551370543104/html/integration_test.log.html#t--streaming-output--3)
  * PR #6610
    * [06-15 16:01](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5075873026015232/html/integration_test.log.html#t--streaming-output--1)
    * [06-15 16:01](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5075873026015232/html/integration_test.log.html#t--streaming-output--2)
    * [06-15 16:01](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5075873026015232/html/integration_test.log.html#t--streaming-output--3)
  * PR #6591
    * [06-15 11:30](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5251236305829888/html/integration_test.log.html#t--streaming-output--1)
    * [06-15 11:30](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5251236305829888/html/integration_test.log.html#t--streaming-output--2)
    * [06-15 11:30](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5251236305829888/html/integration_test.log.html#t--streaming-output--3)
  * PR #6559
    * [06-11 18:44](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4923262570332160/html/integration_test.log.html#t--streaming-output--1)
    * [06-11 18:44](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4923262570332160/html/integration_test.log.html#t--streaming-output--2)
    * [06-11 18:44](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4923262570332160/html/integration_test.log.html#t--streaming-output--3)
* ubuntu-20 : test ubuntu-20
  * PR #6615
    * [06-16 09:06](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6752502932570112/html/integration_test.log.html#t--streaming-output--1)
    * [06-16 09:06](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6752502932570112/html/integration_test.log.html#t--streaming-output--2)
    * [06-16 09:06](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6752502932570112/html/integration_test.log.html#t--streaming-output--3)
    * [06-16 08:21](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6128764528623616/html/integration_test.log.html#t--streaming-output--1)
    * [06-16 08:21](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6128764528623616/html/integration_test.log.html#t--streaming-output--2)
    * [06-16 08:21](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6128764528623616/html/integration_test.log.html#t--streaming-output--3)
    * [06-16 08:20](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5588794965491712/html/integration_test.log.html#t--streaming-output--1)
    * [06-16 08:20](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5588794965491712/html/integration_test.log.html#t--streaming-output--2)
    * [06-16 08:20](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5588794965491712/html/integration_test.log.html#t--streaming-output--3)
    * [06-16 06:04](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5936601417121792/html/integration_test.log.html#t--streaming-output--1)
    * [06-16 06:04](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5936601417121792/html/integration_test.log.html#t--streaming-output--2)
    * [06-16 06:04](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5936601417121792/html/integration_test.log.html#t--streaming-output--3)
  * PR #6610
    * [06-16 06:08](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5563686754451456/html/integration_test.log.html#t--streaming-output--1)
    * [06-16 06:08](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5563686754451456/html/integration_test.log.html#t--streaming-output--2)
    * [06-16 06:08](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5563686754451456/html/integration_test.log.html#t--streaming-output--3)
    * [06-15 19:17](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5973305033228288/html/integration_test.log.html#t--streaming-output--1)
    * [06-15 19:17](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5973305033228288/html/integration_test.log.html#t--streaming-output--2)
    * [06-15 19:17](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5973305033228288/html/integration_test.log.html#t--streaming-output--3)
    * [06-15 18:39](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4539744774258688/html/integration_test.log.html#t--streaming-output--1)
    * [06-15 18:39](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4539744774258688/html/integration_test.log.html#t--streaming-output--2)
    * [06-15 18:39](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4539744774258688/html/integration_test.log.html#t--streaming-output--3)
    * [06-15 18:01](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4830541272842240/html/integration_test.log.html#t--streaming-output--1)
    * [06-15 18:01](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4830541272842240/html/integration_test.log.html#t--streaming-output--2)
    * [06-15 18:01](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4830541272842240/html/integration_test.log.html#t--streaming-output--3)
    * [06-15 16:10](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6465247701630976/html/integration_test.log.html#t--streaming-output--1)
    * [06-15 16:10](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6465247701630976/html/integration_test.log.html#t--streaming-output--2)
    * [06-15 16:10](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/6465247701630976/html/integration_test.log.html#t--streaming-output--3)
    * [06-15 15:31](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5847846052167680/html/integration_test.log.html#t--streaming-output--1)
    * [06-15 15:31](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5847846052167680/html/integration_test.log.html#t--streaming-output--2)
    * [06-15 15:31](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5847846052167680/html/integration_test.log.html#t--streaming-output--3)

Best guess is that `log -f` does not actually wait for container cleanup. But why would this be only on Ubuntu?

**Comment by vrothberg** [comment]
Are we using the same version of conmon?

**Comment by mheon** [comment]
There's a newer Conmon on Fedora. Looking to remedy this in Ubuntu with https://github.com/containers/libpod/pull/6560

**Comment by rhatdan** [comment]
@mheon @vrothberg Should we close this, referenced PRs have been merged?

**Comment by vrothberg** [comment]
I agree. Please reopen if I am mistaken.
