### ISSUE TITLE
[APIv2] hangs indefinitely when following logs of a stopped container

### ISSUE THREAD

**Issue by jgallucci32** [containers/podman#6627]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
When following the logs of a stopped container using APIv2 it hangs indefinitely.

**Steps to reproduce the issue:**

1. Run a container which stops immediately
```
podman run -d --name hello-world hello-world
```
2. Use cURL retreiving logs with the `follow=1` parameter on the stopped container
```
curl --unix-socket /run/podman/podman.sock 'http://docker/v1.24/containers/hello-world/logs?follow=1&stderr=1'
```

**Describe the results you received:**
Command hangs indefinitely

**Describe the results you expected:**
Command should exit

**Additional information you deem important (e.g. issue happens only occasionally):**
This is a similar issue to https://github.com/containers/libpod/issues/6531 which had the same problem with the Podman CLI which was fixed in PR https://github.com/containers/libpod/pull/6591

**Output of `podman version`:**

```
Version:      2.0.0-dev
API Version:  1
Go Version:   go1.14.3
Git Commit:   d857275901e8c1ea7515360631e5894018e17f30
Built:        Fri Jun  5 17:00:00 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0-dev
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.18-0.6.dev.git50aeae4.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.18-dev, commit: 51e91bbc42aaf0676bb4023fb86f00460bf7a0a2'
  cpus: 4
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: file
  hostname: gallucci-fedora.devlnk.net
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.7.0-1.fc33.x86_64
  linkmode: dynamic
  memFree: 15180460032
  memTotal: 16783962112
  ociRuntime:
    name: crun
    package: crun-0.13-2.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.13
      commit: e79e4de4ac16da0ce48777afb72c6241de870525
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 210h 52m 47.56s (Approximately 8.75 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 10
    paused: 0
    running: 4
    stopped: 6
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 5
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1591401600
  BuiltTime: Fri Jun  5 17:00:00 2020
  GitCommit: d857275901e8c1ea7515360631e5894018e17f30
  GoVersion: go1.14.3
  OsArch: linux/amd64
  Version: 2.0.0-dev
```
**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**
```
podman-2.0.0-0.121.dev.git1fcb678.fc33.x86_64```
```
**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 33 (Rawhide Prerelease)

**Comment by jgallucci32** [comment]
@QiWang19 Recommend waiting until #6620 is merged before working on this.

**Comment by rhatdan** [comment]
@QiWang19 The PR @mheon Said to wait for is merged, could you check if this is still an issue?
@jgallucci32 Could you also check.

**Comment by vrothberg** [comment]
The logs backend now has a `context.Context` that can be cancelled which seems like a good approach to stop logs once a container has stopped.

**Comment by rhatdan** [comment]
@vrothberg if you want to run with this one, go for it.

**Comment by vrothberg** [comment]
> @vrothberg if you want to run with this one, go for it.

On it now

**Comment by vrothberg** [comment]
This has been fixed in the meantime.
