### ISSUE TITLE
podman-remote: logs -f hangs client, makes server go 100% CPU

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#6643]
Window 1:
```console
$ bin/podman system service --timeout=0 unix:/tmp/mypodmansock
```
Window 2:
```console
$ ./bin/podman-remote --url $MYSOCK run -d --name foo alpine sh -c "echo hi;sleep 5;echo bye"
ceb3c5e1eea86779bf33fe0e9dfc66788aa2a07317de5e4e1b3086eb4a83dd93
$ ./bin/podman-remote --url $MYSOCK logs -f foo
hi
bye     <<<< this does not always appear; race condition being discussed elsewhere
```
At this point, the `podman logs` hangs and my system gets one CPU pegged at 100%. The CPU hog is the server, not the client: ^C'ing the client keeps CPU pegged, ^C'ing the server stops the CPU load.

Running `strace` on the pegged process is unenlightening:
```
futex(0x2a63048, FUTEX_WAIT_PRIVATE, 0, NULL
```
master @ 38391ed25fdb1cc53b70a75ee4fbe7ea0fa782c3

**Comment by jgallucci32** [comment]
@edsantiago Is podman-remote using APIv2 to make the call for 'logs -f' or is this the equivalent of running `podman logs -f <container>` using the CLI?

If it is using APIv2 I may have an idea of what is going on. I experienced 100% CPU when doing some testing on following logs with APIv2.

**Comment by edsantiago** [comment]
It looks like @jwhonce has taken this on; I believe he mentioned last week that he knows where the problem is. Please coordinate with him if you'd like to work on it.

**Comment by rhatdan** [comment]
@jwhonce Did you get a chance to look at this?  @edsantiago Is this still an issue.  I thought there was some work done on log handling.

**Comment by edsantiago** [comment]
Tried four times on current master @ 1aac197f79e91b06ec7e948bd73bb2464e8a508f. Cannot reproduce. I will assume it's fixed.
