### ISSUE TITLE
Windows installer removed all items from PATH

### ISSUE THREAD

**Issue by Noah-Huppert** [containers/podman#6692]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I used the `podman-v1.9.3.msi` Windows installer and it cleared all items from my user `PATH` environment variable.

**Steps to reproduce the issue:**

1. Be on Windows

2. Use the Postman 1.9.3 installer with default options

**Describe the results you received:**

All my entires for my user `PATH` environment variables are now gone. Only Podman remains. 

**Describe the results you expected:**

For the Podman installer not to nuke all the `PATH` entries I've been accumulating over the long life of computer.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

An error about not being able to find the conf file.

**Output of `podman info --debug`:**

An error about not being able to find the conf.

**Comment by Noah-Huppert** [comment]
Also it Podman creates a new directory in AppData named podman. It would probably be best to place this directory in Local, LocalLow, or Roaming to follow the standard which all other windows apps use.

**Comment by mheon** [comment]
@jwhonce PTAL

**Comment by rhatdan** [comment]
@ashley-cui PTAL

**Comment by rhatdan** [comment]
@ashley-cui Did you get a chance to look at this?

**Comment by baude** [comment]
this should be fixed

**Comment by Noah-Huppert** [comment]
Thank you very much!!!
