### ISSUE TITLE
Rename libpod repo to podman?

### ISSUE THREAD

**Issue by Conan-Kudo** [containers/podman#6701]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

This repository is primarily known for being the home of Podman. The fact that this repository is named `libpod` is confusing, especially since none of the release tarballs are named as such. It also makes discovering this repo harder, since people search for podman and _don't_ find a repo named as such. Can we just have the libpod Git repo renamed to `podman` and be done with it? The fact that `libpod` exists in here is somewhat incidental. A repository rename shouldn't break links, since GitHub maintains a redirect for renames.

**Comment by mheon** [comment]
There have been talks about splitting Podman and Libpod into separate repos (or, potentially, even moving Libpod into the existing `containers/common` repo) and renaming this repo to `containers/podman` as part of said move. That's probably still a good way off (we'd need to greatly improve testing of Libpod itself) but I see no reason we can't rename to containers/podman before it happens.

**Comment by TomSweeneyRedHat** [comment]
I'm building a script today to build all of our container images on quay.io.  Skopeo and Buildah both have their image and github repos with the same name,   Because Podman lives in Libpod, I'd to do some special handling in the script just for Libpod and had this very thought @Conan-Kudo

**Comment by Conan-Kudo** [comment]
It was a pain for me when I was working on packaging Podman and friends for Mageia, as well. And it's just confusing to people. It's weird and annoying. So let's fix it? 😄

**Comment by TomSweeneyRedHat** [comment]
I did just spot one small trouble spot, any old blogs with pointers to libpod.  I wonder if we can alias that somehow?

**Comment by Conan-Kudo** [comment]
GitHub will redirect `containers/libpod` to `containers/podman` automatically.

**Comment by rhatdan** [comment]
Now that we have declared podman 2.0 it is time to do it.  Let's rename it and begin the process of moving libpod under containers/common.

**Comment by mheon** [comment]
It's done.

**Comment by Conan-Kudo** [comment]
THANK YOU! 💯 🥇
