### ISSUE TITLE
RFE: create `podman login --verbose` to show file location

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman#6717]
As I'm forgetful as all get out, and love cut/pasting, I'd love for the `podman login` command to return the file location of the auth.json file that it created.

For example, do this by default would be great for me, but for compatibility reasons maybe not good for all?
```
# podman login quay.io
Username: tomsweeneyredhat
Password: 
Login Succeeded!
Created: /run/user/0/containers/auth.json
```

But if we only print the location if the `--verbose` or `-v` option is supplied, we should be OK.

If we do this for `podman login`, then buildah and skopeo login should follow suit.

**Comment by vrothberg** [comment]
I like the idea!

The `Created:` example is a bit tied to auth files. Maybe we can generalize the output to also cover keyrings, authhelpers and whatever the future might bring. I guess it should display which authentication mechanism was used and add some specific data to the output, in case of auth files the path.

@QiWang19 @mtrmac WDYT?

**Comment by rhatdan** [comment]
I am fine with this, but make it easily scriptable.

**Comment by rhatdan** [comment]
I think -v --verbose is proper option

**Comment by mtrmac** [comment]
I’m very reluctant to make this an API, whether an official one or unofficial text output that would be parsed. (E.g. consider the planned change to default to credential helpers, not printing a path would break that API.)

For `GetCredentials`, at one point there was a global effort to add debug logs that indicate the source of the data (although it seems we haven’t been quite consistent about adding debug logs as new features are added).

Adding similar debug logs to the write paths would make good sense to me.

Having `SetAuthentication` call return a well-typed long-term-stable data type that describes the location in a machine-parseable way that makes sense as an API, _and_ can be used by callers as we add more ways / change the way credentials are recorded, seems quite a lot of work compared to the benefit. Having `SetAuthentication` (or rather a new `SetCredentials`) return a single human-readable string would formally avoid the API commitment, but it would probably become a de-facto API, and we would have an API to return an English text that can’t be localized (which, sure, would not be anything exceptional in these projects).

**Comment by rhatdan** [comment]
@mtrmac @QiWang19 Any movement on this?

**Comment by rhatdan** [comment]
@QiWang19 Please take a look at this?
I think revealing this information in podman info is worth while also.

**Comment by rhatdan** [comment]
@mtrmac @vrothberg @QiWang19 If we just make 

https://github.com/containers/image/blob/master/pkg/docker/config/config.go#L129
func getAuthFilePaths(sys *types.SystemContext) []authPath {

Public then we could retrieve this data.  Would this be acceptable?  Or has this already been discussed?

**Comment by QiWang19** [comment]
`getAuthFilePaths` can give a list of paths that used for searching for valid credentials of some registry, but not cover the case if no credentials exists. The data required may need an API to tell the credentials were found, or the new file is created since no valid credential found, or credentials were saved to keyring, if this is supported in the future.  The above comment has reservations about exposing this kind of text from an API.

**Comment by vrothberg** [comment]
I echo what @QiWang19 said.

I think we need to generalize a bit more to account for non-authfile credentials sources. Returning an additional context string to the credential API that indicates where credentials were stored (or located) may help.

**Comment by rhatdan** [comment]
SGTM, is this doable?

**Comment by vrothberg** [comment]
> SGTM, is this doable?

I wouldn't suggest otherwise :^) We had to start in `github.com/containers/image/v5/pkg/docker/config` and allow to return some context of the auth origin there. For instance, a new `GetCredentials(...) (types.DockerAuthConfig, string, error)` (note the new 2nd return value). We may do the same for auth removal. Once wired in, we can extend `container/common/auth`.

**Comment by rhatdan** [comment]
@QiWang19 Any progress on this?

**Comment by rhatdan** [comment]
@QiWang19 did you ever work on this?

**Comment by rhatdan** [comment]
@QiWang19 @vrothberg Any progress?

**Comment by vrothberg** [comment]
I didn't work on it.

**Comment by QiWang19** [comment]
I didn't work on it.

**Comment by rhatdan** [comment]
@lsm5 PTAL. I think this requires changes in containers/image to retrieve the auth.json file path.

**Comment by mtrmac** [comment]
Not a _path_, at best an English text (or a complex doubtfully-future-proof API), see above.

**Comment by rhatdan** [comment]
@lsm5 any progress on this?

**Comment by lsm5** [comment]
@lsm5 just noticing this now. I think I'll need to give priority to the remainder of subdomain matching and switching skopeo CI to cirrus. So, feel free to re-assign this to someone else if it needs to get done in the next 3 weeks.

**Comment by rhatdan** [comment]
@lsm5 Any progress?

**Comment by flouthoc** [comment]
@rhatdan @vrothberg @lsm5 Can we use `SystemContext` to propogate `verbosity` and instrument future codebase by checking `Verbosity` flag, Should be much more easier than modifying API schema.

**Comment by flouthoc** [comment]
@mtrmac raised few important and fair points here https://github.com/containers/image/pull/1204#pullrequestreview-638240935 although I had few doubts so just putting it here I might be wrong but please correct.
* From issue it seems the `-v`,`--verbose` is more of a UX feature for end user afaik so having it on `stdout` should be fine right ?
* What would be an ideal use-case where we would want to have callback/promise associated with `verbose/debug`.

**Comment by mtrmac** [comment]
I don’t think a vague “verbosity” boolean/callback is the right approach at all. We want to obtain specific data, let’s just return a value that contains that data. (Either way we are going to face difficulties with defining what exactly the data _means_, but) at least that way the caller gets exactly the data expected, no more, no less, and there’s no concern about extracting the right data item out of an undefined ever-expanding “verbose” stream.

And `stdout` is not helpful for remote Podman uses.

**Comment by rhatdan** [comment]
The question then would be what is the command the user would execute to see this information, or are you saying we just dump the information on the screen.  Somthing like:

```
podman login
Using /run/1000/containers/auth.json
Username:
```

**Comment by mtrmac** [comment]
I have no opinion on the Podman UI. My concern is that c/image should be providing an API like `SetCredentials(…) (humanDescriptionWhereTheyWereStored string, err error)`, not `SetCredentials(…, beVerbose) error`.

**Comment by mtrmac** [comment]
A separate `HumanDescriptionWhereCredentialsWillBeStoredInTheFuture(repository) (string, error)` might also make sense if you want the UI like the above, I’m not sure whether we can reliably built it with the current / contemplated helper fallback logic; I haven’t looked now.

**Comment by flouthoc** [comment]
@mtrmac Makes sense i'll try to incorporate these changes in existing PRs if i can. But not sure if it is going to easy change, will have to check where all this change is going to make impact. If not i'll just close the PR. Whatever the case i'll report on this issue.

**Comment by rhatdan** [comment]
@flouthoc What is the latest on this issue?

**Comment by rhatdan** [comment]
@lsm5 Do you have any time to work on this?

**Comment by flouthoc** [comment]
@rhatdan I want to try a new patch for this, will probably force push over old PR this weekend. If @lsm5 is not already working on this.

**Comment by flouthoc** [comment]
@rhatdan @lsm5 I want to give another shot, could we please re-open https://github.com/containers/image/pull/1204 so i can push my  changes.

**Comment by flouthoc** [comment]
@mtrmac  @rhatdan @lsm5 @TomSweeneyRedHat This got implemented in https://github.com/containers/image/pull/1204 and https://github.com/containers/common/pull/607 and propagated to podman via https://github.com/containers/podman/pull/10690.

There is a add example to  docs PR: https://github.com/containers/podman/pull/10068 (not necessary though)

But I think this issue can be safely closed now.

**Comment by flouthoc** [comment]
@rhatdan @TomSweeneyRedHat This is resolved. Could we close this as well.

**Comment by vrothberg** [comment]
Thanks @flouthoc !
