### ISSUE TITLE
Any plans to implement docker compat endpoints for volumes in APIv2?

### ISSUE THREAD

**Issue by maybe-sybr** [containers/podman#6720]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Are there any current plans to implement docker compatible endpoints in APIv2 for managing volumes. I'm currently using the Python `docker` module for portability reasons and would prefer not to have to mix in usage of the alpha looking containers/podman-py package.

**Comment by rhatdan** [comment]
Yes we should have these interfaces.  Interested in opening a PR?  :^)

**Comment by maybe-sybr** [comment]
#6736 is reviewable now I think. I've thrown up some questions which probably any of the maintainers here could answer (mostly relating to where some code should live).

**Comment by maybe-sybr** [comment]
With #6736 merged, this should be all done now. There are a few ongoing pieces of work (notably #6765 ) but those don't require this to remain open.
