### ISSUE TITLE
`podman pod inspect POD` is inconsistent with `podman inspect IMAGE|CONTAINER`

### ISSUE THREAD

**Issue by markstos** [containers/podman#6757]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Looking to inspect something? Try `podman inspect`:

    podman inspect IMAGE
    podman inspect CONTAINER

Oh, you want to inspect a pod? You might guess that's not supported yet. It's supported, but the command name is inconsistent:

 > podman pod inspect POD

**Steps to reproduce the issue:**

1. Look at `podman inspect --help`

2.  Try to figure out how to inspect a pod. 

**Describe the results you received:**

No support for inspecting pods was found

**Describe the results you expected:**

Either `podman inspect` should support inspecting pods,  or if there's a good reason for having the `pod` inspection feature under `podman pod`, then at least `podman inspect --help` should mention the existence of the feature to redirect users who reasonably look for it under `podman inspect`.

**Output of `podman version`:**

```
podman 2.0
```
For example, see #6734 where I use was told to give pod inspection output but failed to find it under `podman inspect`, causing more back-and-forth just to locate the command.

**Comment by mheon** [comment]
It looks like we also need to make `podman inspect` inspect volumes and networks for Docker compatibility.

**Comment by rhatdan** [comment]
podman container inspect
podman image inspect
podman volume inspect
podman network inspect

Docker was moving away from not using three level of commands, I guess they have moved back

**Comment by rhatdan** [comment]
The problem with using just podman inspect, is you have a naming conflicts.

**Comment by markstos** [comment]
podman inspect --help could be updated to mention it is deprecated, and
mention these alternatives instead.

Right now `podman inspect --help` is a dead-end for discovery.

**Comment by rhatdan** [comment]
Interested in opening a PR to add this information?

**Comment by markstos** [comment]
@rhatdan https://github.com/containers/libpod/pull/6773

**Comment by rhatdan** [comment]
Thanks @markstos

**Comment by rhatdan** [comment]
@marcosps Since we merged the documentation change should I close this PR?  Or should we actually make podman inspect also handle network and volumes to match Docker?

**Comment by marcosps** [comment]
@rhatdan I believe you wanted to ping @markstos :)

**Comment by markstos** [comment]
@rhatdan Because of the tagline `alias docker=podman`, if that's still the current vision, you should pursue the compatibility. 

Personally, I never loved Docker and my company is not invested in it. I'm investigating `podman` as "post-Docker" tool, so close compatibility is not a personal concern.  I do like consistent interfaces and clear docs, though.

**Comment by mheon** [comment]
@ashley-cui PTAL

**Comment by rhatdan** [comment]
The information is there now.

```
$ podman inspect --help
Display the configuration of object denoted by ID

Description:
  Displays the low-level information on an object identified by name or ID.
  For more inspection options, see:

      podman container inspect
      podman image inspect
      podman network inspect
      podman pod inspect
      podman volume inspect
```

**Comment by rhatdan** [comment]
@ashley-cui Are you still working on this?
