### ISSUE TITLE
What permissions need to be set for additionalimagestore ?

### ISSUE THREAD

**Issue by gatoniel** [containers/podman#6788]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I have two users on my system. With one of them I create an world accessible (read only) new image store via the `--root` flag. Then I add this image store to the other user as an additionalimagestore with the config as in [#6777](https://github.com/containers/libpod/issues/6777#issuecomment-650116931). When I run `podman images` with the second user I get an permission denied error, that does not make a lot of sense...

**Steps to reproduce the issue:**

1. Create a new folder with user one, that is accessible for all other users.

2. Make the new folder a storage and pull an image into that storage: `podman --root /full/path/to/folder pull registry.fedoraproject.org/f29/httpd`.

3. Create a config file for second user as mentioned above.

4. run `podman images` with second user. This gives the error
   > Error: error opening "/full/path/to/folder/overlay-images/images.lock": permission denied

5. Fix the error: run `chmod go+rwx /full/path/to/folder/overlay-images/images.lock` and `chmod go+rwx /full/path/to/folder/overlay-layers/layers.lock`

6. Check result with 2nd user: `podman images` gives the same error.

7. Make the whole folder read/write: `sudo chmod go+rw -R /full/path/to/folder`. Sudo is needed since some of the files in the storage container belong to different users, etc. due to the creation throuhg podman. Maybe using podman unshare would be a better approach? 

8. Check result with 2nd user: `podman images` gives still the same error.

9. Make the whole folder read/write/execute: `sudo chmod go+xrw -R /full/path/to/folder`.

10. `podman images` gives the expected result:

   > REPOSITORY                            TAG     IMAGE ID      CREATED        SIZE    ReadOnly
   > registry.fedoraproject.org/f29/httpd  latest  25c76f9dcdb5  14 months ago  482 MB  true

**Describe the results you received:**
In all cases the error message is regarding to the file /full/path/to/folder/overlay-images/images.lock. This file is read/write/execute for all users from step 5 on. The error statement is unprecise, since the error comes from other files. These other files are made read/write/executable in step 9. Than it works. Making them just read/write for every user does not solve the problem for the 2nd user.

**Describe the results you expected:**
Step 6 should work or give a different error message.

It would be very good to know, which of the additional storage files need read/write/execute permissions and which just need read permission.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.0.0
API Version:  1
Go Version:   go1.13.4
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.18-1.el8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.18, commit: 3f215ac67ed650ab6a44f8c036bcbd692afdc21e'
  cpus: 32
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: ****
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1039
      size: 1
    - container_id: 1
      host_id: 951968
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1037
      size: 1
    - container_id: 1
      host_id: 951968
      size: 65536
  kernel: 4.18.0-147.8.1.el8_1.x86_64
  linkmode: dynamic
  memFree: 13772951552
  memTotal: 270112145408
  ociRuntime:
    name: runc
    package: runc-1.0.0-15.5.el8.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: ffb456f24bd637cec53c611f309d89abb027b1d3
      spec: 1.0.1-dev
  os: linux
  remoteSocket:
    path: /run/user/1037/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.1-1.el8.x86_64
    version: |-
      slirp4netns version 1.1.1
      commit: bbf27c5acd4356edb97fa639b4e15e0cd56a39d5
      libslirp: 4.2.0
      SLIRP_CONFIG_VERSION_MAX: 2
  swapFree: 2997936128
  swapTotal: 4294963200
  uptime: 430h 16m 56.39s (Approximately 17.92 days)
registries: {}
store:
  configFile: /home/myuser/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 0
    stopped: 3
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /full/path/to/folder
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.1-1.el8.x86_64
      Version: |-
        fusermount3 version: 3.2.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/myuser/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/user/1037/containers
  volumePath: /home/myuser/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.13.4
  OsArch: linux/amd64
  Version: 2.0.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Installierte Pakete
podman.x86_64        2.0.0-2.el8        @devel_kubic_libcontainers_stable
Verfügbare Pakete
podman.aarch64        2.0.0-2.el8        devel_kubic_libcontainers_stable
podman.src        2.0.0-2.el8        devel_kubic_libcontainers_stable

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS 8 on physical workstation.

**Comment by mheon** [comment]
@rhatdan PTAL

**Comment by rhatdan** [comment]
The problem is the lock file is being rewritten each time you update the local share, I believe, so everytime you pull you need to 
chown a+rx -R rootfs

I recently got a PR into container/storage to fix this problem,https://github.com/containers/storage/pull/652
But this fix has not bubbled its way up into buildah/podman yet.

**Comment by rhatdan** [comment]
This is now fixed in master.
