### ISSUE TITLE
Podman connection reset by peer 

### ISSUE THREAD

**Issue by Aruscha** [containers/podman#6795]
Hello,

I have changed from Docker to Podman and unfortunately it is very difficult at the moment...

As you can see most of the PULL commands don't work for me I always get an error.
I tested it on six podman pull files.  None worked except for the two below.
![IMG_20200627_024620_136](https://user-images.githubusercontent.com/49562390/85911137-74226a00-b823-11ea-80f9-6a4c13257d3b.jpg)

podman pull hello-world and podman pull nginx are working.

Can anyone help me? 

What could be the reason ?

**Comment by rhatdan** [comment]
Worked for me on rootless, and rootfull.
What does `podman info` show?
Any chance you are running out of space?

**Comment by goochjj** [comment]
I just tripped over this, and then it resolved itself.

Is it possible there was a network issue and the error just isn't that great?

**Comment by vrothberg** [comment]
I am under the same impression. This usually happens when the network is unstable.

We have received reports that Docker is slightly more tolerant toward network issues; I assume it has some retries or exponential backoff. But in the end there's no good medicine for that other than using a stable network.

**Comment by vrothberg** [comment]
@Aruscha, any chance you can try another network?

**Comment by Aruscha** [comment]
So first of all sorry I was a little bit on the road, I even changed the operating system to Centos8 today, same problem, podman on my laptop, works without problems, I don't understand the problem anymore...

**Comment by Aruscha** [comment]
> Worked for me on rootless, and rootfull.
> What does `podman info` show?
> Any chance you are running out of space?

[arusha@Florina ~]$ podman info                                                                host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module_el8.2.0+305+5e198a41.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: a2b11288060ebd7abd20e0b4eb1a834bbf0aec3e'
  Distribution:
    distribution: '"centos"'
    version: "8"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 13240213504
  MemTotal: 14450925568
  OCIRuntime:
    name: runc
    package: runc-1.0.0-65.rc10.module_el8.2.0+305+5e198a41.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 7377776640
  SwapTotal: 7377776640
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: Florina
  kernel: 4.18.0-193.6.3.el8_2.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.2-3.git21fdece.module_el8.2.0+305+5e198a41.x86_64
    Version: |-
      slirp4netns version 0.4.2+dev
      commit: 21fdece2737dc24ffa3f01a341b8a6854f8b13b4
  uptime: 26m 56.16s
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  ConfigFile: /home/arusha/.config/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-5.module_el8.2.0+305+5e198a41.x86_64
      Version: |-
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  GraphRoot: /home/arusha/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 1
  RunRoot: /run/user/1000
  VolumePath: /home/arusha/.local/share/containers/storage/volumes

**Comment by rhatdan** [comment]
@Aruscha Were you ever able to get this to work?  We have seen some issues with Artifactory registries?

**Comment by Aruscha** [comment]
@rhatdan No, I had to go back to docker Wi-Fi is probably fine, but I can't do it on Ian.

**Comment by rhatdan** [comment]
Well we have added retry to podman now, so it should be better able to handle unstable networks.

**Comment by Aruscha** [comment]
So up to now it does not go unfortunately still with me in lan enterprise.

Is it perhaps because of cloudflare?
Because in the wifi it goes...


![IMG_20200807_132636_272.jpg](https://user-images.githubusercontent.com/49562390/89641356-c9857880-d8b1-11ea-88cc-db7311dabaed.jpg)

**Comment by rhatdan** [comment]
Did you try this with podman in the upstream repo?
