### ISSUE TITLE
Podman system reset fails, if storage driver has been changed

### ISSUE THREAD

**Issue by skorhone** [containers/podman#6807]
/kind bug

**Description**
As a user I expect that podman system reset can be used to recover from most error conditions. Currently if storage driver configuration has been changed and user wants to reset system to use the new configuration, `podman system reset` throws an error.

**Steps to reproduce the issue:**

1. Reset system to clean state: `podman system reset`

2. Set default storage driver to vfs

3. podman podman run --rm ubuntu env

4. Set default storage driver to overlay

5. podman system reset

**Describe the results you received:**
Podman outputs following errors:

```
ERRO[0000] User-selected graph driver "overlay" overwritten by graph driver "vfs" from database - delete libpod local files to resolve 
ERRO[0000] User-selected graph driver "overlay" overwritten by graph driver "vfs" from database - delete libpod local files to resolve 
```

Command executes without any warnings, if executed with storage driver option `podman --storage-driver vfs system reset`

**Describe the results you expected:**
A warning about inconsistency with storage driver is written before confirmation. Warning does not prevent reset.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.0.0
API Version:  1
Go Version:   go1.13.8
Built:        Thu Jan  1 02:00:00 1970
OS/Arch:      linux/amd64
```

**Comment by rhatdan** [comment]
@QiWang19 PTAL

**Comment by QiWang19** [comment]
The error doesn't prevent resetting. It caused by the mismatch between storage driver configuration and database but the storage directory still removed.

**Comment by rhatdan** [comment]
@skorhone Is that a satisfactory explanation?  Can we close the issue?
