### ISSUE TITLE
Rootless pods crash after start via systemd

### ISSUE THREAD

**Issue by 0xb35c** [containers/podman#6839]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I want to be able to start and stop rootless pods via systemd units. Currently we only have version 1.6.4 available so I can't use the better systemd support of v2 right now. (Not sure which version is currently available in the upstream RH repos, as v2 of podman is still somewhat young). Anyways, that's not the issue as far as I can tell, as I get the same behaviour on my fedora workstation with podman v2.0.0.

So I wrote a quite simple systemd unit to simply `podman play kube <podfile>` and `podman pod start <podname>`, as I want to make sure the pods are also started after the system is rebooted. If I run those commands directly on bash everything works fine.
If the pods are started via the unit, they seem to crash immediately in a way even podman doesn't notice. `podman ps -a` says everything is up and running, while it actually is not. After `podman ps -a --sync` podman will correctly notice that the containers are dead.

Is there something I'm missing? I've seen from other issues, that "User=" in the systemd unit might cause issues, but as far as I understand it is more regarding the PIDFile, which I don't use here. (Been there, failed with that :/)

**Steps to reproduce the issue:**
Podfile (originally created via podman):
```yml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2020-06-22T14:38:24Z"
  labels:
    app: pac
  name: pac-app
spec:
  containers:
    - env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - name: TERM
          value: xterm
        - name: HOSTNAME
          value: pac-app
        - name: container
          value: oci
      ports:
        - containerPort: 9000
          hostPort: 9000
          protocol: TCP
      image: our.internal.artifactory.host/path/to/pac-app:test
      name: pac-app-container
      resources: {}
      securityContext:
        allowPrivilegeEscalation: true
        capabilities: {}
        privileged: false
        readOnlyRootFilesystem: false
        runAsUser: 0
      workingDir: /home/docker-user
status: {}
```
Systemd unit:
```
[Unit]
Description=Podman pac-app.service
Documentation=man:podman-generate-systemd(1)

[Service]
# ignore result of play kube - that's just to initially create the pod if not existent
ExecStartPre=-/bin/podman play kube /path/to/pac-app.pod.yml
ExecStart=/bin/podman pod start pac-app
ExecStop=-/bin/podman pod stop -t 10 pac-app
Type=oneshot
User=docker-deploy
TimeoutStartSec=60
RemainAfterExit=yes
KillMode=none

[Install]
WantedBy=multi-user.target
```

1. Place the podfile and systemd unit file
2. `systemctl enable pac-app.service`
3. `systemctl start pac-app.service`

**Describe the results you received:**
```
> sudo systemctl start pac-app
> podman ps -a
CONTAINER ID  IMAGE                                                                                       COMMAND               CREATED        STATUS            PORTS                   NAMES
bfb47fdf53f6  our.internal.artifactory.host/path/to/pac-app:test  /bin/sh -c php-fp...  5 seconds ago  Up 5 seconds ago  0.0.0.0:9000->9000/tcp  pac-app-container
4010aeb6655d  our.internal.artifactory.host/path/to/pause:3.2                                                    5 seconds ago  Up 5 seconds ago  0.0.0.0:9000->9000/tcp  037268f26eae-infra
> podman ps -a --sync
ERRO[0005] No exit file for container 4010aeb6655d820c4b888e06884be2d0a29e86cf0c2c270f3e2c4e1ce635792e found: timed out waiting for file /run/user/12502/libpod/tmp/exits/4010aeb6655d820c4b888e06884be2d0a29e86cf0c2c270f3e2c4e1ce635792e: internal libpod error 
ERRO[0005] No exit file for container bfb47fdf53f61b574eaca85a66c9e0f3f7664971ca9dd7dd1611382083bb64fd found: timed out waiting for file /run/user/12502/libpod/tmp/exits/bfb47fdf53f61b574eaca85a66c9e0f3f7664971ca9dd7dd1611382083bb64fd: internal libpod error 
CONTAINER ID  IMAGE                                                                                       COMMAND               CREATED         STATUS                              PORTS                   NAMES
bfb47fdf53f6  our.internal.artifactory.host/path/to/pac-app:test  /bin/sh -c php-fp...  14 seconds ago  Exited (-1) Less than a second ago  0.0.0.0:9000->9000/tcp  pac-app-container
4010aeb6655d  our.internal.artifactory.host/path/to/pause:3.2                                                    14 seconds ago  Exited (-1) Less than a second ago  0.0.0.0:9000->9000/tcp  037268f26eae-infra
```

**Describe the results you expected:**
This is what i get, when i run podman on the shell:
```
> podman play kube /path/to/pac-app.pod.yml
Pod:
e3e7d431cb653a4c01b842b8d001461ba93f96e237e5774613e346e0ff6009fb
Container:
033a8eead8c73cdefd2898ab8b80952afe67e9d5d5c28e139087226e57ac5a1f
> podman ps -a --sync
CONTAINER ID  IMAGE                                                                                       COMMAND               CREATED         STATUS            PORTS                   NAMES
033a8eead8c7  our.internal.artifactory.host/path/to/pac-app:test  /bin/sh -c php-fp...  8 seconds ago   Up 8 seconds ago  0.0.0.0:9000->9000/tcp  pac-app-container
ed57f2fb03c5  our.internal.artifactory.host/path/to/pause:3.2                                                    22 seconds ago  Up 8 seconds ago  0.0.0.0:9000->9000/tcp  e3e7d431cb65-infra

```

**Additional information you deem important (e.g. issue happens only occasionally):**
I also tried `Type=simple` in the unit file. That results in only having the infra container setup and running. The "real" container isn't even created.

**Output of `podman version`:**

```
podman version 1.6.4
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.15-1.el7_8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.15, commit: 372b4a12f1c2df4f70c280d41173b60acd3f1260'
  Distribution:
    distribution: '"rhel"'
    version: "7.8"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 12502
      size: 1
    - container_id: 1
      host_id: 1214112
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 12502
      size: 1
    - container_id: 1
      host_id: 1214112
      size: 65536
  MemFree: 515940352
  MemTotal: 16637501440
  OCIRuntime:
    name: runc
    package: runc-1.0.0-67.rc10.el7_8.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 3853512704
  SwapTotal: 4294963200
  arch: amd64
  cpus: 6
  eventlogger: file
  hostname: lxneocidservices.schmid.local
  kernel: 3.10.0-1127.13.1.el7.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /bin/slirp4netns
    Package: slirp4netns-0.4.3-4.el7_8.x86_64
    Version: |-
      slirp4netns version 0.4.3
      commit: 2244b9b6461afeccad1678fac3d6e478c28b4ad6
  uptime: 162h 49m 36.61s (Approximately 6.75 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.lxecartifactory.schmid.local
store:
  ConfigFile: /home/docker-deploy/.config/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-6.el7_8.x86_64
      Version: |-
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.6.1
        using FUSE kernel interface version 7.29
  GraphRoot: /home/docker-deploy/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 3
  RunRoot: /run/user/12502/containers
  VolumePath: /home/docker-deploy/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.4-18.el7_8.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Where running on virtualized (via VMWare) Red Hat Enterprise Linux Server release 7.8 (Maipo) boxes in our own data center

**Comment by 0xb35c** [comment]
I found a workaround for the issue:
If I place the required commands in a shell script file and call that from the unit file, everything works as inspected.
Still this doesn't fix the issue itself.

**Comment by vrothberg** [comment]
Thanks for reaching out, @0xb35c!

Can you share the output of `systemctl status`? I suspect that `oneshot` is a problem. Could try setting it to `type=Forking`?

**Comment by 0xb35c** [comment]
Hi,

yeah sure. `systemctl status` with `Type=oneshot`:
```
systemctl status pac-app
● pac-app.service - Podman pac-app.service
   Loaded: loaded (/usr/lib/systemd/system/pac-app.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2020-07-02 13:16:28 CEST; 45s ago
     Docs: man:podman-generate-systemd(1)
  Process: 127551 ExecStart=/bin/pod start pac-app (code=exited, status=203/EXEC)
  Process: 127187 ExecStartPre=/bin/podman play kube /path/to/pac-app.pod.yml (code=exited, status=0/SUCCESS)
 Main PID: 127551 (code=exited, status=203/EXEC)

Jul 02 13:16:17 podmanmachine.local podman[127187]: Writing manifest to image destination
Jul 02 13:16:17 podmanmachine.local podman[127187]: Storing signatures
Jul 02 13:16:28 podmanmachine.local podman[127187]: Pod:
Jul 02 13:16:28 podmanmachine.local podman[127187]: 22ccda935d2d32fd23b51d5166591270786ed195f7d2e8b447aef9e3447b5d32
Jul 02 13:16:28 podmanmachine.local podman[127187]: Container:
Jul 02 13:16:28 podmanmachine.local podman[127187]: 7287a3dfef85fabb83d2be49445e63b8985c4a27da6c0ab30d9c2d15cdbe45ed
Jul 02 13:16:28 podmanmachine.local systemd[1]: pac-app.service: main process exited, code=exited, status=203/EXEC
Jul 02 13:16:29 podmanmachine.local systemd[1]: Failed to start Podman pac-app.service.
Jul 02 13:16:29 podmanmachine.local systemd[1]: Unit pac-app.service entered failed state.
Jul 02 13:16:29 podmanmachine.local systemd[1]: pac-app.service failed.
```
It's strange right now, as I didn't get errors before and I'm not sure what I changed that produces the error now. Still podman needs to sync first before it knows, that the containers are dead.


And here `systemctl status` with `Type=forking`:
```
systemctl status pac-app
● pac-app.service - Podman pac-app.service
   Loaded: loaded (/usr/lib/systemd/system/pac-app.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2020-07-02 13:26:15 CEST; 30s ago
     Docs: man:podman-generate-systemd(1)
  Process: 1708 ExecStart=/bin/pod start pac-app (code=exited, status=203/EXEC)
  Process: 1267 ExecStartPre=/bin/podman play kube /path/to/pac-app.pod.yml (code=exited, status=0/SUCCESS)
 Main PID: 130234 (code=exited, status=203/EXEC)

Jul 02 13:26:03 podmanmachine.local podman[1267]: Writing manifest to image destination
Jul 02 13:26:03 podmanmachine.local podman[1267]: Storing signatures
Jul 02 13:26:15 podmanmachine.local podman[1267]: Pod:
Jul 02 13:26:15 podmanmachine.local podman[1267]: 033e37ebf07284e4003aedcb16db7129ad32e87dfe312fab89e2e078cfe80a05
Jul 02 13:26:15 podmanmachine.local podman[1267]: Container:
Jul 02 13:26:15 podmanmachine.local podman[1267]: 11e045fe26926a156c50371eff2ca4cb794daba8f64fb85423ff0d425c4cd6cc
Jul 02 13:26:15 podmanmachine.local systemd[1]: pac-app.service: control process exited, code=exited status=203
Jul 02 13:26:15 podmanmachine.local systemd[1]: Failed to start Podman pac-app.service.
Jul 02 13:26:15 podmanmachine.local systemd[1]: Unit pac-app.service entered failed state.
Jul 02 13:26:15 podmanmachine.local systemd[1]: pac-app.service failed.
```
podman shows the same behaviour regarding its dead containers.

Does `Type=forking` make sense here? If I understand correctly this tells systemd to watch any forking process starting from the given ExecStart-command? (And fail/restart if this process exits?) Also I assumed that `Type=oneshot` means that systemd should just run that command and don't care about what happens then.

If you like, I can post the debug output for the systemd startup. Though it didn't seem to have any critical issues, as the containers seem to start at some point.

**Comment by 0xb35c** [comment]
Hi @vrothberg,

do you have any updates on this issue? :)

Thanks

**Comment by vrothberg** [comment]
Thanks for the ping! Apologies, I got pulled into other issues. I will have a look tomorrow.

**Comment by vrothberg** [comment]
@0xb35c ... one last try: can you check with `type=simple`?

We didn't imagine `play kube` to be used in a systemd unit. With v2.0, `podman generate systemd` supports the `--new` flag also for pods, which may be something more reliable for your use case. However, v1.6.4 is too old to properly support these new features.

It looks like `oneshot` is shooting down the containers.

**Comment by limburgher** [comment]
I think this is related: I'm on Fedora 32, podman 2.0.2.  I used generate to create a unit file for a pod. Systemd (245.6) won's start it: Service has more than one ExecStart= setting, which is only allowed for Type=oneshot services. Refusing.

oneshot fails as well: Unit container-7634fa278c8aa456da4354b6d7e0f39b11146db3f83ca019c21046c958b681e7.service not found.

**Comment by vrothberg** [comment]
> I think this is related: I'm on Fedora 32, podman 2.0.2. I used generate to create a unit file for a pod. Systemd (245.6) won's start it: Service has more than one ExecStart= setting, which is only allowed for Type=oneshot services. Refusing.

That sounds like a red herring. Systemd happily eats multiple `ExecStarts`s for non-oneshot types of services. The generated unit files are of type=forking and they don't error. I just verified on workstation, also with F32, Podman v2.0.2 and systemd 245.6.

**Comment by limburgher** [comment]
The generated unit file was type=forking and do error, that's why I tried oneshot at all.

Failed to start podman-esrapps.service: Unit podman-esrapps.service has a bad unit file setting.
See system logs and 'systemctl status podman-esrapps.service' for details.

journalctl:

podman-esrapps.service: Service has more than one ExecStart= setting, which is only allowed for Type=oneshot services. Refusing.
[podman-esrapps.service.txt](https://github.com/containers/podman/files/4972065/podman-esrapps.service.txt)

**Comment by vrothberg** [comment]
Can you share a reproducer?

**Comment by limburgher** [comment]
Yes. Previous comment. pod generated with:
#!/bin/bash
podman pod create --name esrapps -p 7070:8080
podman create --name irc_bot --pod esrapps esrum.org:5000/esrum /root/irc_bot.py
podman create --name storged --user storge --pod esrapps esrum.org:5000/esrum /usr/sbin/storged -p 8080

**Comment by vrothberg** [comment]
Thanks! Unfortunately esrum.org:5000/esrum requires authentication, so I can't reproduce.

**Comment by limburgher** [comment]
Yes, it's a private repo. The image is built from Fedora 32 and includes some python modules and internal software. Do you have a working pod whose generated systemd file works that I could try?

**Comment by vrothberg** [comment]
Sure. Here's an example:
``` 
user $ podman pod create --name=test-pod
48be223f565a3f09c90a262114ea1c8401d35a59d9a972e06a0612354465d2da
user $ podman create --name=test-ctr --pod=test-pod fedora sleep 42m
324385804c2357969fba15ac5c21dd57a3fe32a256f3c1e4b41d95fb4ea9ab2c
user $ podman generate systemd --files test-pod
/home/valentin/.config/systemd/user/pod-48be223f565a3f09c90a262114ea1c8401d35a59d9a972e06a0612354465d2da.service
/home/valentin/.config/systemd/user/container-324385804c2357969fba15ac5c21dd57a3fe32a256f3c1e4b41d95fb4ea9ab2c.service
user $ systemctl --user daemon-reload
user $ systemctl --user start pod-48be223f565a3f09c90a262114ea1c8401d35a59d9a972e06a0612354465d2da.service 
user $ podman ps
CONTAINER ID  IMAGE                            COMMAND    CREATED         STATUS            PORTS   NAMES
2a2d3fd3a28d  k8s.gcr.io/pause:3.2                        39 seconds ago  Up 6 seconds ago          48be223f565a-infra
324385804c23  docker.io/library/fedora:latest  sleep 42m  29 seconds ago  Up 5 seconds ago          test-ctr
user $ systemctl --user status pod-48be223f565a3f09c90a262114ea1c8401d35a59d9a972e06a0612354465d2da.service 
● pod-48be223f565a3f09c90a262114ea1c8401d35a59d9a972e06a0612354465d2da.service - Podman pod-48be223f565a3f09c90a262114ea1c8401d35a59d9a972e06>
     Loaded: loaded (/home/valentin/.config/systemd/user/pod-48be223f565a3f09c90a262114ea1c8401d35a59d9a972e06a0612354465d2da.service; disabl>
     Active: active (running) since Fri 2020-07-24 15:30:50 CEST; 20s ago
       Docs: man:podman-generate-systemd(1)
    Process: 1599614 ExecStart=/usr/bin/podman start 2a2d3fd3a28d126675173522365521d7cfd8830eb82939269da3fbd617329210 (code=exited, status=0/>
   Main PID: 1599709 (conmon)
      Tasks: 4 (limit: 19009)
     Memory: 3.9M
        CPU: 389ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/pod-48be223f565a3f09c90a262114ea1c8401d35a59d9a972e06a0612354465d2da.service
             ├─1599666 /usr/bin/fuse-overlayfs -o lowerdir=/home/valentin/.local/share/containers/storage/overlay/l/GGCV23ATQC5Y5N3UCACXAS7BK>
             ├─1599670 /usr/bin/slirp4netns --disable-host-loopback --mtu 65520 --enable-sandbox --enable-seccomp -c -e 3 -r 4 --netns-type=p>
             └─1599709 /usr/bin/conmon --api-version 1 -c 2a2d3fd3a28d126675173522365521d7cfd8830eb82939269da3fbd617329210 -u 2a2d3fd3a28d126>

Jul 24 15:30:50 nebuchadnezzar systemd[1123]: Starting Podman pod-48be223f565a3f09c90a262114ea1c8401d35a59d9a972e06a0612354465d2da.service...
Jul 24 15:30:50 nebuchadnezzar podman[1599614]: 2a2d3fd3a28d126675173522365521d7cfd8830eb82939269da3fbd617329210
Jul 24 15:30:50 nebuchadnezzar systemd[1123]: Started Podman pod-48be223f565a3f09c90a262114ea1c8401d35a59d9a972e06a0612354465d2da.service.
```

**Comment by vrothberg** [comment]
Note, I am in `$HOME/.config/systemd/user/`.

**Comment by limburgher** [comment]
I had installed my unit file to /etc/systemd/system/, run daemon-reload, and attempted systemctl start podman esrapps, as root. I had used podman generate systemd > podman-esrapps.service, as I had for individual containers. I see yours generates multiple unit files. I wasn't aware of the --files flag...I take it a single unit file is therefore not intended to work?

**Comment by vrothberg** [comment]
Entirely my fault of not reading carefully enough, apologies! The error message now makes much more sense to me. What the unit files have is one ExecStart but mulitple ExecStartPre.

> I had installed my unit file to /etc/systemd/system/, run daemon-reload, and attempted systemctl start podman esrapps, as root. I had used podman generate systemd > podman-esrapps.service, as I had for individual containers. I see yours generates multiple unit files. I wasn't aware of the --files flag...I take it a single unit file is therefore not intended to work?

Using the printed output for a pod will not work, no. That includes multiple unit files. We ran with it for backward compat reasons as it works for a container.

**Comment by limburgher** [comment]
Ahhh, ok. The multiple unit files work perfectly. Thank you!

**Comment by 0xb35c** [comment]
Hey there,

sorry for not getting back to this for so long. I was able to get back to this issue today and tried to reproduce the issue for myself and it seems systemd is working as expected for now.
I'm not sure if it relates to the fact, that I enabled lingering (`loginctl --enable-linger <user>`), though I tried turning it off and it still works.

Anyways: I'll close this issue.

Thanks for your support so far :)

**Comment by Elrondo46** [comment]
Same problem and it's a random problem, runs in Raspberry pi for aarch64 ARM

**Comment by Elrondo46** [comment]
Please reopen the bug

**Comment by mheon** [comment]
This issue is over two years old. Please file a new issue, as it's quite likely that the cause has changed.
