### ISSUE TITLE
podman run with pod and uidmap: mount mqueue not permitted

### ISSUE THREAD

**Issue by matpen** [containers/podman#6843]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

This is a follow-up issue to containers/crun#396, which was closed and marked as solved.

I came to the above mentioned issue after facing the very same problem it describes, in my case on an Ubuntu 18.04 host with runc runtime:
```
# The host is Ubuntu 18.04 on a physical laptop
matteo@matteo-laptop:~$ cat /etc/issue
Ubuntu 18.04.4 LTS

# Kernel is the latest available through HWE
matteo@matteo-laptop:~$ uname -r
5.3.0-61-generic

# I am trying to map container user 1000 to host user 3001 (this fails)
matteo@matteo-laptop:~$ sudo podman run \
    --rm \
    --uidmap 1000:3001:1 \
    "docker.io/library/ubuntu:18.04" whoami
Error: error creating libpod runtime: Container ID 0 cannot be mapped to a host ID

# Once the system users are mapped, too, it works
matteo@matteo-laptop:~$ sudo podman run \
    --rm \
    --uidmap 0:1000:1000 \
    --uidmap 1000:3001:1 \
    "docker.io/library/ubuntu:18.04" whoami
root

# However, trying to join a pod seems not to work (as per #396)
matteo@matteo-laptop:~$ sudo podman pod create \
    --name test_pod
matteo@matteo-laptop:~$ sudo podman run \
    --rm \
    --pod test_pod \
    --uidmap 0:1000:1000 \
    --uidmap 1000:3001:1 \
    "docker.io/library/ubuntu:18.04" whoami
Error: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"sysfs\\\" to rootfs \\\"...\\\" at \\\"/sys\\\" caused \\\"operation not permitted\\\"\"": OCI runtime permission denied error
```

Having found the solution in containers/crun#396, I installed [crun](https://github.com/containers/crun) from [master (65e35c5)](https://github.com/containers/crun/commit/65e35c5759e024f9abc2b672d4857aabf37eb1bf).
Switching to the newly installed crun runtime and retrying the last command gives a different error:
```
# Repeating the previous command with crun
matteo@matteo-laptop:~$ sudo podman pod create \
    --runtime crun \
    --name test_pod2
matteo@matteo-laptop:~$ sudo podman run \
    --rm \
    --runtime crun \
    --pod test_pod2 \
    --uidmap 0:1000:1000 \
    --uidmap 1000:3001:1 \
    "docker.io/library/ubuntu:18.04" whoami
Error: mount `mqueue` to '/dev/mqueue': Operation not permitted: OCI runtime permission denied error

# Making the container privileged does not help
matteo@matteo-laptop:~$ sudo podman run \
    --rm \
    --privileged \
    --runtime crun \
    --pod test_pod2 \
    --uidmap 0:1000:1000 \
    --uidmap 1000:3001:1 \
    "docker.io/library/ubuntu:18.04" whoami
Error: mount `mqueue` to '/dev/mqueue': Operation not permitted: OCI runtime permission denied error
```

These sources might be related (although they deal with docker and runc):
* moby/moby#20798
* moby/moby#36674
* [redhat bugzilla 1401537](https://bugzilla.redhat.com/show_bug.cgi?id=1401537)

**Steps to reproduce the issue:**

See description.

**Describe the results you received:**

Various permission errors.

**Describe the results you expected:**

The commands should succeed without errors.

**Additional information you deem important (e.g. issue happens only occasionally):**

None.

**Output of `podman version`:**

```
Version:            1.6.2
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.10.4
  podman version: 1.6.2
host:
  BuildahVersion: 1.11.3
  CgroupVersion: v1
  Conmon:
    package: 'conmon: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.3, commit: unknown'
  Distribution:
    distribution: ubuntu
    version: "18.04"
  MemFree: 4763987968
  MemTotal: 16647471104
  OCIRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 17036734464
  SwapTotal: 17036734464
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: matteo-laptop
  kernel: 5.3.0-61-generic
  os: linux
  rootless: false
  uptime: 3h 16m 11.02s (Approximately 0.12 days)
registries:
  blocked: null
  insecure: null
  search: null
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 14
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /home/matteo/MyData/data/podman/root
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 161
  RunRoot: /var/run/containers/storage
  VolumePath: /home/matteo/MyData/data/podman/root/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/bionic,now 1.6.2-1~ubuntu18.04~ppa1 amd64 [installed]
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical laptop.

**Comment by mheon** [comment]
We do not presently support using `--uidmap` with pods. We're looking into enabling it at the pod level, but when we do, it's likely going to be a flag to give a configuration for the whole pod - I don't think it is possible to sanely support containers with varying mappings inside the same pod.

Besides that, though, is the fact that we just allowed this to happen without error, and happily handed off a container configuration that would never work to the OCI runtime, which handed back a not particularly relevant error. We should catch this earlier and error at the container creation stage with an error that actually makes sense.

**Comment by mheon** [comment]
@rhatdan Good issue for an intern, I think

**Comment by matpen** [comment]
Thank you for the prompt response, @mheon. Indeed I was led to think that solving containers/crun#396 was meant to enable this feature. Seems like I will have to wait for further development, and come up with a different solution for my use case.

**Comment by rhatdan** [comment]
Let's let @QiWang19 Look at this one.

**Comment by mheon** [comment]
This is a kernel-level restriction - you can't join namespaces not owned by your user namespace, so we can't join the uidmapped containers to the pod-level network namespace (which existed before the new container and its user namespace). I believe that the work @giuseppe did in crun is to enable the entire pod to share a single user namespace (which Podman still does not have support for, but could add at this point).

**Comment by giuseppe** [comment]
crun 0.14 will permit doing it but it requires Linux 5.3+: https://github.com/containers/crun/pull/400

**Comment by matpen** [comment]
@mheon IIUC one would set the mapping on the pod, and the various containers would not be allowed to specify a different mapping. That would probably be enough in my case. 

@giuseppe containers/crun#400 is the PR that solved the containers/crun#396 (mentioned in the OP). My kernel is `5.3.0-61` so the test seems to cover that: IIUC only the proper option in `podman pod create` is missing (as @mheon says).

**Comment by mheon** [comment]
@giuseppe Wow - the kernel is allowing that now?

Also, I only see proc/IPC listed - what about net? We're still broken if pods can't share network.

**Comment by giuseppe** [comment]
> @giuseppe Wow - the kernel is allowing that now?

I am using a dirty trick of creating the mount before creating the user namespace and then I mount it once I am in the user+mount namespace :-)

**Comment by giuseppe** [comment]
latest crun version has this feature, so closing the issue.
