### ISSUE TITLE
podman-remote exec return codes incorrect

### ISSUE THREAD

**Issue by baude** [containers/podman#6893]
Several integration tests that are current disabled review that podman-remote sets exit codes of 0 when commands have failed.

exec foobar /etc should return a 126 (returns 0 today)
exec foobar notarealcommand should return a 127 (returns 0 today)

These can be verified with exec_test.go: 229 and :240

**Comment by mheon** [comment]
Working on this now. Think it might be a race between Podman reading the exit code from Conmon and the client doing an inspect to get exit status.

**Comment by mheon** [comment]
It is definitely a race, but not what I originally thought. Seems specific to exec sessions that exit instantly.

**Comment by edsantiago** [comment]
@mheon, `exit 1` triggers the error but only because there is no `exit` command. `exec sh -c "exit 5"` exits 5 as expected.

Just for the sake of dotting every 't', I want to provide precise full context here. The problem as reported is only with two specially-defined cases of podman and docker execution: running a directory, and running a nonexistent command. Exact setup follows:

In window 1:
```console
$ ./bin/podman system service --timeout=0
```
In window 2:
```console
$ ./bin/podman-remote run -d --name foo alpine sleep 60
776787db6f7824763cdcb6db6b8953a716e995a356003151c799bf48ea8cefb1
$ for i in true false /etc no-such-command;do ./bin/podman-remote exec foo $i;echo $?;echo;done
0

1

open executable: Operation not permitted: OCI runtime permission denied error
0    <--- bad: should be 126

executable file not found in $PATH: No such file or directory: OCI runtime command not found error
0    <--- bad: should be 127
```
Meanwhile, back in window 1, the following two error messages are seen (for the last two cases respectively):
```
ERRO[0392] Error attaching to container 776787db6f7824763cdcb6db6b8953a716e995a356003151c799bf48ea8cefb1 exec session 4f91602528aa287febb160648a05eec3a6b8642b94065163963390533bd5e1ee: open executable: Operation not permitted: OCI runtime permission denied error
ERRO[0392] Error attaching to container 776787db6f7824763cdcb6db6b8953a716e995a356003151c799bf48ea8cefb1 exec session 23251cc3fe750ca944a735f0c90c82a5f0a19d8d758bcdcd4ed5e1861f9aef11: executable file not found in $PATH: No such file or directory: OCI runtime command not found error
```

**Comment by vrothberg** [comment]
> Working on this now. Think it might be a race between Podman reading the exit code from Conmon and the client doing an inspect to get exit status.

Thanks, @mheon! I did not find/take the time to tackle it.

**Comment by mheon** [comment]
@edsantiago Thanks, that helped a lot.

I think I have a fix now, doing some tests before I make a PR.
