### ISSUE TITLE
rootless: support launching slirp4netns without --disable-host-loopback

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/podman#6912]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Support launching slirp4netns without `--disable-host-loopback`, so that the localhost ports on the host can be accessed as 10.0.2.2 from containers.

For security, the default MUST remain to use --disable-host-loopback.

Originally requested by @tmds https://github.com/containers/podman/issues/1733#issuecomment-655969836

Corresponding code: https://github.com/containers/podman/blob/9eac75a967e3459b32b1acd220afb49b60f5e5aa/libpod/networking_linux.go#L218-L220

**Comment by rhatdan** [comment]
Sure, what would you suggest the CLI for this should be?

**Comment by tmds** [comment]
suggestions: `--enable-host-loopback`/`--add-host-loopback`.

**Comment by mheon** [comment]
I'm still of the opinion we need a generic network options CLI - `--network-opt slirp4netns:enable-host-loopback,disable-seccomp` or similar

**Comment by tmds** [comment]
It would be nice to be able to pass options to `slirp4netns` from the command line.

First class features should also be exposed through direct arguments, without referencing `slirp4netns`.

**Comment by giuseppe** [comment]
let's add new flags for slirp4netns using: https://github.com/containers/podman/pull/6965

**Comment by giuseppe** [comment]
I've added a patch to #6963 

@AkihiroSuda will this help with rootless kind?

**Comment by AkihiroSuda** [comment]
I guess you meant #6965?

> rootless kind

I'm not sure. At least kind with rootless Docker doesn't seem to require this.

**Comment by giuseppe** [comment]
Yes I think the main issue is that with podman containers cannot communicate with each other when running rootless

**Comment by tmds** [comment]
@AkihiroSuda @giuseppe I'm not sure how to use this.

I have a webserver running on localhost:
```
$ curl http://localhost:5000
Hello World!
```

I create a container that is on a network. I'd like the container to be able to the localhost webserver.
```
$ podman network create mynet
$ podman run -ti --network mynet busybox /bin/sh
/ # wget http://10.0.2.2:5000
Connecting to 10.0.2.2:5000 (10.0.2.2:5000)
wget: can't connect to remote host (10.0.2.2): Network is unreachable
```

What argument should I add, and to which command?

**Comment by AkihiroSuda** [comment]
`podman run --network slirp4netns:allow_host_loopback=true`. Requires Podman 2.1.0 or later.

**Comment by tmds** [comment]
I'd like the container to be connected to a network, and still be able to access localhost. I'm not able to ping the other containers on the network when I add the `allow_host_loopback=true`.

```
$  podman run -ti --network mynet busybox /bin/sh
/ # ping other_container
PING other_container (10.88.23.8): 56 data bytes
64 bytes from 10.88.23.8: seq=0 ttl=64 time=0.098 ms
64 bytes from 10.88.23.8: seq=1 ttl=64 time=0.107 ms
^C
--- other_container ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 0.098/0.102/0.107 ms
/ # exit
$  podman run -ti --network mynet --network slirp4netns:allow_host_loopback=true busybox /bin/sh
/ # ping other_container
ping: bad address 'other_container'

```

**Comment by AkihiroSuda** [comment]
Unimplemented yet

**Comment by tmds** [comment]
Thanks! I've created a feature request for it: https://github.com/containers/podman/issues/7888.
