### ISSUE TITLE
[Question] - Access NFS Home Dir w/ keep-id

### ISSUE THREAD

**Issue by choman** [containers/podman#6919]
Sorry for not filling out all the info, but this is really more of a question

**podman version:**
Version:      2.0.2
API Version:  1
Go Version:   go1.13.11
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64

**System Info:**
selinux is enforcing
home directories are NFS mounted

Out of the following two commands
1) podman container run -it --rm -v $HOME:$HOME --entrypoint bash --security-opt label=disable  _image_
2) podman container run -it --rm -v $HOME:$HOME --entrypoint bash --security-opt label=disable  --userns keep-id  _image_

Result:
1) Work great, but I do not have access to user's group info
2) Error's out:
~~~
Error: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: moun
ting \\\"/home/user1\\\" to rootfs \\\"/var/lib/users/user1/containers/storage/overlay/8cf9b03f94fbfcfafe4150092b5aff74b58dbb6
62fda50cebe4fe72721766798/merged\\\" at \\\"/home/user1\\\" caused \\\"stat /home/user1: permission denied\\\"\"": OCI runtime
 permission denied error
~~~

I'm gonna take a stab this has something to do with the /etc/sub?id files and that the remote NFS server has no concept of the sub?id(s).

My question is can an OCI hook get me around this, or am I dead in the water?
If I'm dead  in the water, suggestion on the best way to get group into into the container?

**Comment by rhatdan** [comment]
If you are using crun, you can leak the groups into the container.

```
man podman run
...
       Note:  if  the  user  only has access rights via a group, accessing the device from inside a rootless container will fail. The crun(1) runtime offers a workaround for this by adding the option --annotation run.oci.keep_origi‐
       nal_groups=1.

```

Did you tell container/storage to ignore-chown-errors?

**Comment by choman** [comment]
I did not on the ignore chown errors, and the system I'm on has the runc environment as opposed to the crun environment

**Comment by rhatdan** [comment]
The CHOWN Errors should not matter whether it is in runc or crun mode.  
On and NFS Homedir, the NFS Server will not allow a process in the user namespace to chown a file to a different UID/GID, since it has no concept of User Namespace.

**Comment by vrothberg** [comment]
@choman did leaking the group via crun solve the issue for you?

**Comment by rhatdan** [comment]
If it did not, reopen this issue.
