### ISSUE TITLE
Feature request: systemd start rootless containers at boot without user login.

### ISSUE THREAD

**Issue by andrew-kennedy** [containers/podman#6940]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Podman currently does not seem to allow running rootless containers at boot using systemd without user login. I am trying to use the User= directive in the service files generated by podman generate systemd --files to make sure podman runs as my user at boot, but it isn't working. I get error messages like `podman[2400]: Error: error creating tmpdir /run/user/1000/libpod/tmp: mkdir /run/user/1000: permission denied`.

I know there is the loginctl enable linger way of running pods, but as I understand it that requires a user login and just stops pods from exiting when the user logs out. Is there a better way to accomplish what I want? rootless containers all started at system boot without a login?

**Comment by Luap99** [comment]
From my understanding `loginctl enable-linger` should start at boot without the user login.

**Comment by vrothberg** [comment]
Hi @andrew-kennedy, thanks for reaching out!

With Podman 2.0, we support running system services (root) with the User/Group primitives to run rootless containers. Starting them at boot can be achieved via `systemctl enable ...`. If you have an ordinary user and want to run rootless containers in user services, you can use `loginctl enable-linger` (as suggest by @Luap99). Once lingering is enabled, the units will start at boot when they have been enabled before.

The [generate systemd docs](https://github.com/containers/podman/blob/master/docs/source/markdown/podman-generate-systemd.1.md) mentioned the process briefly. I tested the setup on a F32 server VM with Podman v2.0.2:
```
$ id -u
1000
$ cd $HOME/.config/systemd/user
$ podman create -d --name foo fedora sleep 365d
$ podman generate systemd --new --name --files foo
$ systemctl --user daemon-reload
$ systemctl --user enable container-foo.service
```
Now reboot and login as root:
```
[root@localhost ~]# ps aux|grep 365d
valentin    1023  0.3  0.0   2352   576 ?        Ss   12:59   0:00 sleep 365d
root        1123  0.0  0.0 216084   644 pts/0    S+   13:00   0:00 grep --color=auto 365d
```

Does that work in your environment?

**Comment by andrew-kennedy** [comment]
I'll have to try what you suggested. Away from my computer at the moment but I ended up not being able to get the services to run rootless via systemd, using either the loginctl way or the User/Group root systemd way. I can launch them just fine normally as rootless containers using podman run, but they fail when attempting to enable and launch via systems. I'll attach logs in a few days so there's hopefully more to go off of as far as why the generated systemd units don't work for me on podman 2.0.2

**Comment by andrew-kennedy** [comment]
Update: I tried to create a pod and a container using the following commands:

```
podman pod create \
--name=web-services \
-p 8080 \
-p 8443
```

```
podman create \
--name=caddy \
--pull=always \
--pod=web-services \
--detach \
--memory 256m \
-v ~/services/caddy/data:/data:Z \
-v ~/services/caddy/config:/config:Z \
-v ~/services/caddy/caddyfile:/etc/caddy:Z \
caddy
```

```
podman create \
--name=plex \
--pull=always \
--pod=web-services \
--detach \
--memory 1g \
-e PUID=$(id -u `whoami`) \
-e PGID=$(id -g `whoami`) \
-e TZ=America/Los_Angeles \
-e NVIDIA_VISIBLE_DEVICES=all \
-e NVIDIA_DRIVER_CAPABILITIES=all \
-v /media/plex/config:/config:z \
-v /media/plex/transcode:/transcode:Z \
-v /media/movies:/media/movies:z \
-v /media/tvseries:/media/tv:z \
linuxserver/plex
```
With no luck. I can start all these containers or the pod rootless, but not via rootless systemd once I generate the systemd service files using `podman generate systemd --new --name --files web-services`. When I check journalctl, I see quite a few errors, and when I do `sudo setenforce 0` I notice lots of selinux related errors that I don't get when launching these rootless normally, such as 

```
type=AVC msg=audit(1594281360.061:7231): avc:  denied  { read } for  pid=2757300 comm="systemd-user-ru" name="secrets" dev="tmpfs" ino=1403342 scontext=system_u:system_r:systemd_logind_t:s0 tcontext=system_u:object_r:container_file_t:s0:c352,c807 tclass=dir permissive=0

type=AVC msg=audit(1595244639.584:6349): avc:  denied  { read } for  pid=163053 comm=506C6578204D656469612053657276 name="params" dev="tmpfs" ino=108904 scontext=system_u:system_r:container_t:s0:c255,c493 tcontext=unconfined_u:object_r:container_runtime_tmpfs_t:s0 tclass=file permissive=0
```

**Comment by rhatdan** [comment]
Do they start via systemd if you setenforce 0?

**Comment by rhatdan** [comment]
Do you know what the  `params` file is?
It looks like the container engines (Podman) is creating it and leaking it into the container.

**Comment by andrew-kennedy** [comment]
> Do they start via systemd if you setenforce 0?

Unfortunately no.

> Do you know what the  `params` file is?
> 
> It looks like the container engines (Podman) is creating it and leaking it into the container.

Also no. There are lots of audit2allow messages that show up for files I didn't realize were being access before as they work fine without any errors or audit messages with SELinux enforcing as long as I use rootless podman directly and not through `systemd --user.`

**Comment by vrothberg** [comment]
To localize the source of your issue a bit further: Did you try running the services as root?

**Comment by andrew-kennedy** [comment]
> To localize the source of your issue a bit further: Did you try running the services as root?

Sorry for the delay, I briefly tried running them as root but still ran into issues, however I did get them locally working with one caveat: I can get them to launch as rootless with systemctl --user, but not using the --new flag. So if the containers already exist, we're fine. The behavior I really want is for systemd as non root to create and lauch the containers from scratch every time.

**Comment by rhatdan** [comment]
@andrew-kennedy @vro is this still an issue?

**Comment by andrew-kennedy** [comment]
No! Somehow the --new flag seems to work now. But they don't work with auto update so I opened a ticket for that.

**Comment by andrew-kennedy** [comment]
They're now starting at login and creating new containers every time as `--new` would imply, so some bug has clearly been fixed. But now `podman auto-update` isn't working so I opened a new [issue](https://github.com/containers/podman/issues/7407)
