### ISSUE TITLE
Renaming the project invalidated checksums of archives

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman#6941]
This is more of a heads-up, than an actual bug. But all of the source downloads now have different checksums...

> It seems like renaming the project from libpod to podman has invalidated all the tarballs on github
> Since they are not created using something predictable like "make dist", but are just git archives
>
> So the (stupid) filename is still `v1.9.3.tar.gz`
> But the contents are now `podman-1.9.3/`

<details>

```
>>> podman v1.9.3 Downloading
--2020-07-11 21:38:34--  https://github.com/containers/libpod/archive/v1.9.3.tar.gz
Resolving github.com (github.com)... 140.82.118.4
Connecting to github.com (github.com)|140.82.118.4|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://github.com/containers/podman/archive/v1.9.3.tar.gz [following]
--2020-07-11 21:38:34--  https://github.com/containers/podman/archive/v1.9.3.tar.gz
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/containers/podman/tar.gz/v1.9.3 [following]
--2020-07-11 21:38:34--  https://codeload.github.com/containers/podman/tar.gz/v1.9.3
Resolving codeload.github.com (codeload.github.com)... 140.82.112.9
Connecting to codeload.github.com (codeload.github.com)|140.82.112.9|:443... connected.
HTTP request sent, awaiting response... 200 OK
```
</details>

```
ERROR: v1.9.3.tar.gz has wrong sha256 hash:
ERROR: expected: 2c44c6e5f61578e223dce2a2f48776adb553752a782e309e96f2d608e0ace81b
ERROR: got     : a16846fe076aaf2c9ea2e854c3baba9fb838d916be7fb4b5be332e6c92d907d4
ERROR: Incomplete download, or man-in-the-middle (MITM) attack
```

There are several things that are wrong with the world* here, so I guess podman is just a victim of circumstance.

* The tarball could have been called libpod-1.9.3.tar.gz and podman-1.9.3.tar.gz
* The checksum could have been on the contents, instead with the directory name
* We could have provided a "distfiles" archive, instead of trusting the github URL
* It could have stayed with the old name forever, since renaming things always break :-)

**Comment by afbjorklund** [comment]
I think the next generation of build system will have to build _everything_ from git instead. Maybe create one with `pristine-tar`

Clearly _nobody_ is using this antiquated "name-version" system anymore. Already have to provide $GIT_COMMIT and friends.

**Comment by cgwalters** [comment]
See also http://github.com/cgwalters/git-evtag which is not subject to this issue.

**Comment by afbjorklund** [comment]
People have started checksumming and signing now ? That would be nice too, but I'm still stuck at the MD5 and ASC level.

While we are at the soapbox, I still think base-32 was a neat idea. Then again, I always preferred the "hex" version myself.

**Comment by afbjorklund** [comment]
We just updated the checksum to match (but did **not** update podman version)
