### ISSUE TITLE
podman installation error ！

### ISSUE THREAD

**Issue by mkyman** [containers/podman#6942]
OS : CentOS 7.8.2003 x64
Description : today , while I followed  the steps of podman installation instructions on official website, it threw me some errors below : 

**[MIRROR] podman-plugins-2.0.2-1.el7.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 77ec61cc55fb3273e123d65ac535c6cc6b7423f0(sha1)  Expected: 58a4429d610ecc3940a4239f3ea867ad0c1115bf(sha1) 

[FAILED] podman-plugins-2.0.2-1.el7.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success                  
(6-7/15): podman-2.0.2-1.el7.x86_64.rpm           19% [=========-                                       ] 1.1 MB/s |  13 MB     00:48 ETA
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Cannot download x86_64/podman-plugins-2.0.2-1.el7.x86_64.rpm: All mirrors were tried**

================================
I tried several times to reinstall the packages, but the same error info appeared.
thank you !

**Comment by zhangguanzhang** [comment]
Find the mirror source closest to your network

**Comment by rhatdan** [comment]
This is not an upstream issue.  Looks like you centos repos are not configured correctly.
