### ISSUE TITLE
rootless+privileged `/dev` mount fails when host changes (e.g. reboot)

### ISSUE THREAD

**Issue by cgwalters** [containers/podman#6943]
This is a bit of a conflict between podman's design for "create immutable container configuration" versus dynamic host submounts, and also whether containers should be "elephants" or "ants" (pets vs _).

I use [coretoolbox](https://github.com/cgwalters/coretoolbox) and often have the problem after rebooting that my pet development container fails to start with:
```
walters@quicksilver ~> coretoolbox run
Error: unable to start container "d149540e65abbff3d2c54ddde2e19bd37a5cc9b049ead2089df70ef6e2d170c5": error stat'ing file `/dev/bus/usb/001/011`: No such file or directory: OCI runtime command not found error
error: Child ["podman" "start" "coreos-toolbox"] exited: exit code: 125
```

As far as I can tell what's going on is that we request `--volume=/dev:/host/dev:rslave` at start.  Podman then traverses that and finds child mounts, and where things go wrong is those get *persisted to disk*.  The set of mounts is dynamic, so on reboot the hierarchy is different.

**Comment by mheon** [comment]
This seems really strange, because we have no code that would go through and generate these child mounts.

Is this a privileged rootless container? For those, we do create bind mounts for everything in `/dev` into the container (no permissions to recreate device nodes), which has the problematic side-effect of tying us to a single version of `/dev/` and breaking containers on simple things, like USB device removal. We had several options for fixing this last I checked, but the most promising one didn't pan out and discussion fizzled shortly thereafter.

**Comment by cgwalters** [comment]
> This seems really strange, because we have no code that would go through and generate these child mounts.

I should clarify that I was taking a guess as to what was going wrong, I didn't trace through it.

> Is this a privileged rootless container? 

Yep!

> For those, we do create bind mounts for everything in /dev into the container (no permissions to recreate device nodes), which has the problematic side-effect of tying us to a single version of /dev/ and breaking containers on simple things, like USB device removal.

OK yep, that sounds like the bug.  So it's not specific to coretoolbox.  Hmm.  Currently for the toolbox use case we really want everything from the host including things like `/run` and `/var` - I am going to try to switch to just `--volume=/:/host` like `oc debug node` and the MCO do.  If we do that, then we can just `rmdir /dev && ln -sr /host/dev /dev` in the container, but we'd need to suppress podman's builtin mount for `/dev`.

Is there an existing issue for this?  We could close this as a duplicate (although there is the "toolbox" aspect here that might drive us to do something different).

**Comment by cgwalters** [comment]
Sorry right I remembered now why we need a separate `/dev`, it's because of `/dev/pts`.  Argh.

**Comment by mheon** [comment]
Yes. That was our proposed way around individual mounts, but we haven't figured out a good way around it (bind mounting and shadowing paths were both considered, but couldn't resolve the issue).

At this point, it sounds like our best option is to move the logic for generating these links inside `libpod` so we can regenerate them every time the container starts.

**Comment by cgwalters** [comment]
> At this point, it sounds like our best option is to move the logic for generating these links inside libpod so we can regenerate them every time the container starts.

Right; in coretoolbox today we have this notion of "static" vs "runtime" container initialization, see: https://github.com/cgwalters/coretoolbox/blob/e317fbd89dbc90234d49bacdeba1aebaad024889/src/coretoolbox.rs#L649
The "static" configuration is on the persistent parts of the container filesystem - e.g. we inject our user into `/etc/sudoers` and use a "stamp file" in `/etc` to signal that that process is complete.

But exactly some of this state propagation must be *runtime*, e.g. we re-create bind mounts because the host configuration may have changed.  We store our "stamp file" in `/run` and also use it as a lock file to ensure we have "at most once" semantics if e.g. two processes try to start the container at the same time.

I assume there's a place in podman/runc that has these hooks today.

**Comment by wngfra** [comment]
Having the same issue when USB devices changed. Running with `-it --privileged -p 10240:10240 --net=host` and nothing else.
Any workaround or solution?

**Comment by rhatdan** [comment]
@giuseppe PTAL
Can we do a better job of handling this for rootless containers?  Why do we need to walk the /dev directory rather then just bind mounting it?

**Comment by giuseppe** [comment]
I think it is a dup of https://github.com/containers/podman/issues/4900

**Comment by debarshiray** [comment]
I am not sure what the deal is here.

[Toolbox](https://github.com/containers/toolbox) has been doing `--volume /dev/:/dev:rslave` for more than a year now. Haven't run into any problems so far.

From what I understood after discussing with @giuseppe a few weeks back, it's not a problem unless you do `podman create --interactive --tty ...`, which Toolbox doesn't. Instead, doing `podman exec --interactive --tty ...` is fine.

**Comment by rhatdan** [comment]
Closing carry on discussion in #4900
