### ISSUE TITLE
terminal broken inside of podman with usernamespace in some images

### ISSUE THREAD

**Issue by FlorianLudwig** [containers/podman#6944]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The terminal is pretty broken on some images when running with `--userns=keep-id`.

**Steps to reproduce the issue:**

1. `podman run -ti --userns=keep-id docker.io/greyrook/cde-dev-py37:cbfa6f05455445fbdc86acc3c7d7945c42c61829 bash`

2. press `aa[backspace]`

**Describe the results you received:**

`[I have no name!@7c735c260625 /]$ a`
`[I have no name!@7c735c260625 /]$ aa`
`[I have no name!@7c735c260625 /]$ aa  ` <- space entered after `aa`

**Describe the results you expected:**

`[I have no name!@7c735c260625 /]$ a`
backspace working to delete stuff

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.0.2
API Version:  1
Go Version:   go1.14.3
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.18-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.18, commit: 6e8799f576f11f902cd8a8d8b45b2b2caf636a85'
  cpus: 8
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: knight1
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.7.7-200.fc32.x86_64
  linkmode: dynamic
  memFree: 1008619520
  memTotal: 16415260672
  ociRuntime:
    name: runc
    package: containerd.io-1.2.13-3.2.fc31.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
      spec: 1.0.1-dev
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.1-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.1
      commit: bbf27c5acd4356edb97fa639b4e15e0cd56a39d5
      libslirp: 4.2.0
      SLIRP_CONFIG_VERSION_MAX: 2
  swapFree: 7771770880
  swapTotal: 9656332288
  uptime: 59h 21m 54.71s (Approximately 2.46 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/f.ludwig/.config/containers/storage.conf
  containerStore:
    number: 40
    paused: 0
    running: 2
    stopped: 38
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.1-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/f.ludwig/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 56
  runRoot: /run/user/1000
  volumePath: /home/f.ludwig/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.14.3
  OsArch: linux/amd64
  Version: 2.0.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.2-1.fc32.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This issue was not present in some earlier version of podman.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
I am not able to reproduce using both crun and runc from upstream.

Do you see the same issue if you install crun and try?

```
podman --runtime /usr/bin/crun run -ti --userns=keep-id docker.io/greyrook/cde-dev-py37:cbfa6f05455445fbdc86acc3c7d7945c42c61829 bash
```
Could you also try to disable temporarily selinux?  It could also be causing issues with the terminal

**Comment by FlorianLudwig** [comment]
Hi @giuseppe ,

> Do you see the same issue if you install crun and try?
> 
> ```
> podman --runtime /usr/bin/crun run -ti --userns=keep-id docker.io/greyrook/cde-dev-py37:cbfa6f05455445fbdc86acc3c7d7945c42c61829 bash
> ```

Produces the exact same result.

![term](https://user-images.githubusercontent.com/432263/87413004-010e4700-c5ca-11ea-9e7f-3d805afd00f7.gif)


> Could you also try to disable temporarily selinux? It could also be causing issues with the terminal
Interesting, didn't know that :)  But didn't make a difference.


---
I tried using a different user on the same machine - and didn't have an issue. Maybe it's one of podmans configs - but I always forget where to find those :sweat:

**Comment by edsantiago** [comment]
```console
 [I have no name!@7c735c260625 /]$ aa <- space entered after aa
```
When I see "backspace sends space", my first thought is termcap. What is `$TERM` set to in your invoking shell? Does your container have a corresponding termcap entry for that term? Can you try running the container with `TERM=xterm` (or something plain and simple)?

**Comment by FlorianLudwig** [comment]
@edsantiago 
```
TERM=vt100 podman --runtime /usr/bin/crun run -ti --userns=keep-id docker.io/greyrook/cde-dev-py37:cbfa6f05455445fbdc86acc3c7d7945c42c61829 bash
```
produces the same result.

Setting it inside the container, does also not change it. Interestingly `reset` still errors out:
```
$ reset
reset: unknown terminal type vt100
```

**Comment by edsantiago** [comment]
My point is, you need to use a termcap entry that is supported by your container. Or, if the container is under your control, install (or don't delete) termcap entries.

**Comment by rhatdan** [comment]
I believe this is not a bug in Podman, reopen if you disagree.
