### ISSUE TITLE
Rootless podman causes slow behaviour for nginx subdomain reverse proxy. Running as root restores performance.

### ISSUE THREAD

**Issue by osirase** [containers/podman#6945]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Nginx has poor performance when running as rootless for certain a application under subdomain redirect. Loading time is around 20-30 seconds. When ran as root, loading time is cut down to 5-6 seconds. I initially filed a bug report at jellyfin due to faulty reasoning, to save myself typing out all my findings here, please visit the initial issue I opened: https://github.com/jellyfin/jellyfin-web/issues/1515

**Steps to reproduce the issue:**

1. Setup nginx and jellyfin using podman, you can see my config here to get started quickly: https://github.com/jellyfin/jellyfin-web/issues/1515

2. Observe the difference in performance when running with and without sudo using your web browser performance inspector.

I went into quite a lot of detail here: https://github.com/jellyfin/jellyfin-web/issues/1515

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
podman info --debug
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.18-1.fc32.x86_64
    path: /usr/libexec/crio/conmon
    version: 'conmon version 2.0.18, commit: 6e8799f576f11f902cd8a8d8b45b2b2caf636a85'
  cpus: 4
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: t440p
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.7.8-200.fc32.x86_64
  linkmode: dynamic
  memFree: 5429493760
  memTotal: 16656658432
  ociRuntime:
    name: crun
    package: crun-0.14.1-1.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.14.1
      commit: 598ea5e192ca12d4f6378217d3ab1415efeddefa
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.1-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.1
      commit: bbf27c5acd4356edb97fa639b4e15e0cd56a39d5
      libslirp: 4.2.0
      SLIRP_CONFIG_VERSION_MAX: 2
  swapFree: 8413769728
  swapTotal: 8413769728
  uptime: 1h 34m 22.35s (Approximately 0.04 days)
registries:
  search:
  - docker.io
store:
  configFile: /home/dfenn/.config/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 3
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.1-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/dfenn/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 16
  runRoot: /tmp/1000
  volumePath: /home/dfenn/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Thu Jan  1 12:00:00 1970
  GitCommit: ""
  GoVersion: go1.14.3
  OsArch: linux/amd64
  Version: 2.0.2

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.2-1.fc32.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora 32
podman 2.0.2
nginx:stable
jellyfin:stable
nextcloud:stable

**Comment by mheon** [comment]
I suspect that this is slirp4netns. Rootless networking uses slirp4netns instead of creating an interface in a network bridge, which is a sort of manual bridge, tunnelling traffic from the host into the container. We can't really do this differently, as rootless Podman doesn't have the necessary permissions to set up a network bridge like root Podman does. If you require further performance, you could consider disabling network isolation with `--net=host` which should remove slirp4netns from the equation.

**Comment by osirase** [comment]
Any advice on how to troubleshoot slirp4netns? I want to see exactly why it's not handling the GET requests properly and taking 5000ms to respond on certain GET requests. I'd like to understand why there is no performance impact for nextcloud, but a massive one for jellyfin.

**Comment by AkihiroSuda** [comment]
Is this related?
https://github.com/rootless-containers/slirp4netns/blob/v1.1.4/slirp4netns.1.md#bugs

**Comment by osirase** [comment]
> Is this related?
> https://github.com/rootless-containers/slirp4netns/blob/v1.1.4/slirp4netns.1.md#bugs

I'd like to test this but I'm really not familiar at all with namespaces, I don't understand how to run this first command:

```
nsenter -t $(cat /tmp/pid) -U -n -m
```
What's up with the target being some temp file? Shouldn't the flags following also have some sort of input?

**Comment by rhatdan** [comment]
@AkihiroSuda @osirase @giuseppe Is this still an issue?

**Comment by vrothberg** [comment]
Friendly ping

**Comment by AkihiroSuda** [comment]
>  I don't understand how to run this first command:

Podman doesn't write slirp4netns PID to any file, so please substitute `cat /tmp/pid` with `pgrep slirp4netns`

**Comment by rhatdan** [comment]
Since we got no response, I am going to close this issue, Reopen if more information is available.

**Comment by randchoice** [comment]
[I ran into this issue myself ](https://www.reddit.com/r/linuxadmin/comments/o6e1x6/performance_issues_when_running_nginx_reverse/). This issue only appears when running both containers on the same host. Running the same containers on two separate machines works fine.

I tried to change tcp_rmem but running:

`nsenter -t $(cat /tmp/pid) -U -n -m`

as @AkihiroSuda suggested gives me the following error:

`nsenter: reassociate to namespace 'ns/net' failed: Operation not permitted`

Distro: Arch
Podman: 3.2.1-1
slirp4netns: 1.1.11-1

**Comment by AkihiroSuda** [comment]
@randchoice `nsenter -t $(cat /tmp/pid) -U --preserve-credentials -n -m`

**Comment by randchoice** [comment]
Adding --network slirp4netns:mtu=1500 to the podman run command for the nginx container appears to fix the issue.

@AkihiroSuda I messed up the c&p. I ran it with your pgrep slirp4netns substitution.

Running 
`nsenter -t $(pgrep slirp4netns) -U --preserve-credentials -n -m`
Gives me the same error message as before.

**Comment by AkihiroSuda** [comment]
You have to specify a PID that is associated with the child network namespace. i.e., a PID of container. (`podman inspect <CONTAINER>`)
