### ISSUE TITLE
podman exec: Error: unable to find user $USER: no matching entries in passwd file

### ISSUE THREAD

**Issue by owtaylor** [containers/podman#6953]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Trying to exec into a container with '-u $USER' fails to look up the user that is automatically added by `--userns=keep-id --user root:root`

**Steps to reproduce the issue:**

in one terminal:

```
$ podman run  --userns=keep-id --user root:root -it --rm --name foof registry.fedoraproject.org/fedora:32 /bin/bash
```

in another terminal:

```
$ podman exec -it -u $USER foof /bin/bash
Error: unable to find user otaylor: no matching entries in passwd file
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This is a distillation of a problem toolbox triggers; I see this on Fedora Silverblue rawhide, @mheon was able to reproduce on his system

**Output of `podman version`:**

Version:      2.1.0-dev
API Version:  1
Go Version:   go1.14.3
Built:        Wed Dec 31 19:00:00 1969
OS/Arch:      linux/amd64

**Comment by mheon** [comment]
This is almost certainly our code for creating + bind-mounting `/etc/passwd` into the container.

**Comment by rhatdan** [comment]
I think the problem is the image is mounted but not the bind mounts, so the /etc/passwd is not mounted at the time of the lookup.

**Comment by rhatdan** [comment]
If I just exec into the container , it sees the entry.

**Comment by rhatdan** [comment]
```
$ podman exec -l -ti grep dwalsh /etc/passwd
dwalsh:x:3267:3267:dwalsh:/:/bin/sh
$ podman exec --user dwalsh -l -ti grep dwalsh /etc/passwd
Error: unable to find user dwalsh: no matching entries in passwd file
```

**Comment by mheon** [comment]
Yes. I think we probably want to avoid the lookup if we made our own `/etc/passwd` and populate with the info we know we put in there.

**Comment by owtaylor** [comment]
What actually toolbox needs is a way to entirely disable the overmount and use it's own existing useradd logic. (Or perhaps, for compatibility, adding the user entry needs to be optional, and not done default.)

For toolbox, it's important to be able yum/dnf install packages - which might need to add users and groups. This means there needs to be a writable /etc/passwd that is persistent with the container. (You can't even useradd with the overmount at all, since that tries to rename the newly written file over /etc/passwd. But even if it worked, changes would be gone the next time the container was started.)

**Comment by mheon** [comment]
I believe the current logic presents a writable, persistent `/etc/passwd` (I'll need to verify the persistent part) - it's just a bind mount, as opposed to being part of the image.

**Comment by mheon** [comment]
Though, I just tried running `--userns=keep-id` on a FreeIPA-managed system and our passwd-generation logic completely blew up - so it's clearly not that durable.

**Comment by rhatdan** [comment]
The file is writeable but not useradd fails, because it is trying to rename over the file.

**Comment by rhatdan** [comment]
@owtaylor We probably should not do this in the case of /etc being a mount point, which would fix the issue with toolbox.  Does not fix the issue with --keep-id though.

**Comment by mheon** [comment]
@rhatdan I'm starting to think the entire passwd as a bind mount approach is broken - we're re-creating it every container restart, so we're dropping all user-added changes, which definitely does not seem correct.

**Comment by mheon** [comment]
We're also explicitly mounting over any user-added `/etc/passwd` mount, which also seems bunk.

**Comment by rhatdan** [comment]
Yes it should be static, IE Survive container start/stop.  I thought it was, but maybe I have a bug.
I am wondering if we should take advantage of the COW layer and write the file into it, then it would be more natural.

**Comment by mheon** [comment]
I'm going to reopen because we only partially solved this.

We can definitely edit /etc/passwd in the image. That does not work in the read-only case, but that would also make it impossible to add users, so we could still use the old approach.

**Comment by bbros-dev** [comment]
We are triggering this error in `3.0.1` via:

```bash
$ podman generate kube c1d2e96b6fc0 -s -f podman-pod.yaml 
Error: unable to find user yelgeb: no matching entries in passwd file
```

**Comment by mheon** [comment]
Can you give further details - is this 100% consistent? Can you give any details on the container/pod you're generating from, so we can repro ourselves?

**Comment by rhatdan** [comment]
Is the container running as user yelgeb?

**Comment by rhatdan** [comment]
Is this container created with --userns=keep-id?

**Comment by bbros-dev** [comment]
Not running as user `yelgeb`, not created or running with `--userns=keep-id`.

Here is the Dockerfile:

```dockerfile
FROM docker.io/library/rust:1.52.1-slim-buster as debian-build

## Principle of least privilege
#
# Create a user unlikely to exist.
#
RUN useradd yelgeb

RUN mkdir -p /usr/src/yelgeb

WORKDIR /usr/src/yelgeb

COPY Cargo.toml Cargo.toml

## Rust OpenSSL
#
RUN echo "deb http://ftp.debian.org/debian buster-backports main" | tee /etc/apt/sources.list.d/backports.list \
    && apt update \
    && apt --yes install -t buster-backports cmake \
    && apt --yes install --no-install-recommends pkg-config libssl-dev

## Workaround Cargo #2644
#
# Reference:
# - https://github.com/rust-lang/cargo/issues/2644
#
RUN echo "fn main() {println!(\"if you see this, the build broke\")}" > /usr/src/yelgeb/gti.rs

## Cache Build Dependencies
#
# Docker caches each RUN in a layer. Cache the build dependencies.
#
RUN cargo build --release

## Build
#
# With all dependencies built and cached we can build the application without
# having to wait for all dependencies to be rebuilt on each change.
#
RUN rm -f target/release/deps/gti*
COPY gti.rs /usr/src/yelgeb/gti.rs
RUN cargo build --release

RUN chown yelgeb:yelgeb /usr/src/yelgeb/target/release/gti
RUN chmod a+x /usr/src/yelgeb/target/release/gti

FROM scratch

COPY --from=debian-build /usr/src/yelgeb/target/release/gti /usr/local/bin/gti
# Chore: Bring along linked libraries.
COPY --from=debian-build /usr/lib/x86_64-linux-gnu/libssl.so.1.1 /usr/lib/x86_64-linux-gnu/libssl.so.1.1
COPY --from=debian-build /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
COPY --from=debian-build /lib/x86_64-linux-gnu/libgcc_s.so.1 /lib/x86_64-linux-gnu/libgcc_s.so.1
COPY --from=debian-build /lib/x86_64-linux-gnu/librt.so.1 /lib/x86_64-linux-gnu/librt.so.1
COPY --from=debian-build /lib/x86_64-linux-gnu/libpthread.so.0 /lib/x86_64-linux-gnu/libpthread.so.0
COPY --from=debian-build /lib/x86_64-linux-gnu/libm.so.6 /lib/x86_64-linux-gnu/libm.so.6
COPY --from=debian-build /lib/x86_64-linux-gnu/libdl.so.2 /lib/x86_64-linux-gnu/libdl.so.2
COPY --from=debian-build /lib/x86_64-linux-gnu/libc.so.6 /lib/x86_64-linux-gnu/libc.so.6
COPY --from=debian-build /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2

## Setup Container User
#
COPY --from=debian-build /etc/passwd /etc/passwd
USER yelgeb

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin

ENTRYPOINT ["/usr/local/bin/gti"]

CMD ["--list"]
```

The docker-compose (podman-compose) and Podman Pod setup we're working on is [here](https://github.com/bbros-dev/goose/tree/issue-289/examples/the-internet)
