### ISSUE TITLE
Change in semantics for 'podman run --pull'?

### ISSUE THREAD

**Issue by srcshelton** [containers/podman#6983]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Prior to podman-2.0.x (possibly as recently as release 2.0.1?) the '`--pull`' argument to `podman run` did not need a parameter.

Now, however, the parameter appears mandatory, with the `--pull` option consuming the following argument (e.g. `podman run --pull --rm ...` results in:

```
Error: invalid pull policy "--rm"
```

Whilst the `--help` text states:

```
Pull image before creating ("always"|"missing"|"never") (default "missing")
```

The fact that a default is mentioned suggests that the `--pull` option is intended to be allowed to be used without a policy, in which case it inherits the default setting?

This appears to have recently been changed - was this the intention?

**Output of `podman version`:**

```
Version:      2.0.2
API Version:  1
Go Version:   go1.14.2
Git Commit:   201c9505b88f451ca877d29a73ed0f1836bb96c7
Built:        Wed Jul  8 17:39:51 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.17, commit: 41877362fc4685d55e0473d2e4a1cbe5e1debee0'
  cpus: 8
  distribution:
    distribution: gentoo
    version: unknown
  eventLogger: file
  hostname: dellr330
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.38-gentoo
  linkmode: dynamic
  memFree: 733523968
  memTotal: 8132182016
  ociRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
      spec: 1.0.1-dev
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 25209147392
  swapTotal: 25769787392
  uptime: 960h 14m 44.42s (Approximately 40.00 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 10
    paused: 0
    running: 9
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.ignore_chown_errors: "false"
  graphRoot: /space/podman/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2465
  runRoot: /space/podman/run
  volumePath: /space/podman/volumes
version:
  APIVersion: 1
  Built: 1594229991
  BuiltTime: Wed Jul  8 17:39:51 2020
  GitCommit: 201c9505b88f451ca877d29a73ed0f1836bb96c7
  GoVersion: go1.14.2
  OsArch: linux/amd64
  Version: 2.0.2
```

**Comment by rhatdan** [comment]
This might have changed from podman 1.9 to podman 2.0, but this is a CLI issue, I believe, and I am not sure I can fix it,  The idea of defaults, is that if you don't specify the option then it will take the default. If you specify --pull then it expects a flag.
@baude @TomSweeneyRedHat Any thoughts on this?  Is there a way we could ignore the fact that there is no value on --pull?

**Comment by TomSweeneyRedHat** [comment]
@srcshelton thanks for the issue.  I'm not sure if this is an unintentional change, I know there were some discussions about `--pull` at some point.  However, we either need to allow pull to take no values and/or update the man page because that's clearly wrong now.  @baude, do you remember if this was intentionally changed?

**Comment by mheon** [comment]
The manpages were updated with it (`--pull=always|missing|never` is in the `podman run` manpage) so it looks intentional?
