### ISSUE TITLE
Misleading warnings about use of 'libpod.conf'?

### ISSUE THREAD

**Issue by srcshelton** [containers/podman#6985]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

If running podman with '`--log-level debug`' then amongst the output appears:

```
time="2020-07-13T14:16:37Z" level=debug msg="Found deprecated file /etc/containers/libpod.conf, please remove. Use /etc/containers/containers.conf to override defaults.\n"
```

... but if this advice is followed then none of the settings in `containers.conf` are applied - it very much looks as if podman is only examining `libpod.conf`, despite this notice.

Alternatively, is `containers.conf` of a different format to `libpod.conf` and, if so, could a link to further information or a migration guide be added to the debug message?

**Output of `podman version`:**

```
Version:      2.0.2
API Version:  1
Go Version:   go1.14.2
Git Commit:   201c9505b88f451ca877d29a73ed0f1836bb96c7
Built:        Wed Jul  8 17:39:51 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.17, commit: 41877362fc4685d55e0473d2e4a1cbe5e1debee0'
  cpus: 8
  distribution:
    distribution: gentoo
    version: unknown
  eventLogger: file
  hostname: dellr330
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.38-gentoo
  linkmode: dynamic
  memFree: 733523968
  memTotal: 8132182016
  ociRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
      spec: 1.0.1-dev
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 25209147392
  swapTotal: 25769787392
  uptime: 960h 14m 44.42s (Approximately 40.00 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 10
    paused: 0
    running: 9
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.ignore_chown_errors: "false"
  graphRoot: /space/podman/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2465
  runRoot: /space/podman/run
  volumePath: /space/podman/volumes
version:
  APIVersion: 1
  Built: 1594229991
  BuiltTime: Wed Jul  8 17:39:51 2020
  GitCommit: 201c9505b88f451ca877d29a73ed0f1836bb96c7
  GoVersion: go1.14.2
  OsArch: linux/amd64
  Version: 2.0.2 
```

**Comment by srcshelton** [comment]
**Update:**

If I make `/etc/containers/libpod.conf` a symlink to `/etc/containers/containers.conf` then the settings from this file _are_ applied - suggesting that the debug line requesting the use of `containers.conf` has been added before `containers.conf` is being used in place of `libpod.conf`?

**Comment by rhatdan** [comment]
Containers.conf should override libpod.conf, if they do not then this is a bug.
The order should be 

DefaultConfig (Hard coded into Podman)
libpod.conf
/usr/share/containers/containers.conf
/etc/containers/containers.conf
$HOME/.config/containers/containers.conf
If you put a field in containers.conf, do you see the value from libpod.conf?

**Comment by mheon** [comment]
I thought we agreed the opposite, at least for the initial few releases that included containers.conf. We're at the point where I'd be comfortable switching to the opposite, though.

**Comment by rhatdan** [comment]
Well you should not have a containers.conf with any content, if you create one, and we accidently created a libpod.conf as a side effect, then the containers.conf should override the conflicting fields.

containers.conf that gets installed in /usr/share/containers/containers.conf is commented out.  I guess a distribution could screw this up, but for the most part I think this is the proper sequence.

**Comment by srcshelton** [comment]
> Well you should not have a containers.conf with any content, if you create one, and we accidently created a libpod.conf as a side effect, then the containers.conf should override the conflicting fields.
> 
> containers.conf that gets installed in /usr/share/containers/containers.conf is commented out. I guess a distribution could screw this up, but for the most part I think this is the proper sequence.

The message says to put settings/overrides in `/etc/containers/containers.conf` and that `/etc/containers/libpod.conf` should be migrated/removed... is this correct?

**Comment by mheon** [comment]
Yes.

Right now, `libpod.conf` takes precedence over `containers.conf`. `libpod.conf` is considered deprecated and this behavior will be switched (potentially soon) to the opposite, with libpod.conf settings being overridden by containers.conf if both are present. I don't think we're going to remove it entirely any time soon, but that too will probably happen eventually.

**Comment by rhatdan** [comment]
Yes remove libpod.conf and move any special settings to containers.conf, if they were something you set, if not, then removing libpod.conf should be enough.

**Comment by srcshelton** [comment]
If I remove `libpod.conf` and leave `containers.conf`, then at least some of the settings aren't applied:

```
dellr330 ~ # cd /etc/containers/
dellr330 containers # ls -l *.conf
-rw-r--r-- 1 root root 5637 Jul 15 11:31 containers.conf
lrwxrwxrwx 1 root root   15 Jul  9 12:22 libpod.conf -> containers.conf
-rw-r--r-- 1 root root  225 Jun  7 00:47 registries.conf
-rw-r--r-- 1 root root  788 May 25 21:25 storage.conf
dellr330 containers # podman ps
CONTAINER ID  IMAGE                                                 COMMAND               CREATED       STATUS           PORTS                   NAMES
38a0acc8fbb9  localhost/dell-ism:351                                                      7 days ago    Up 7 days ago                            dell-ism-351
483e72e903b6  localhost/service.net-im.bitlbee:3.6-r1               -D -P /var/run/bi...  18 hours ago  Up 18 hours ago  0.0.0.0:6667->6667/tcp  openrc-bitlbee-3.6-r1
74e70f86157c  localhost/service.net-mail.imapproxy:1.2.8_p14843-r1  -f /etc/imapproxy...  31 hours ago  Up 31 hours ago                          openrc-imapproxy-1.2.8_p14843-r1
a76ba07c002f  localhost/service.net-misc.openntpd:6.2_p3-r1         -d -f /etc/opennt...  18 hours ago  Up 18 hours ago  0.0.0.0:123->123/udp    openrc-openntpd-6.2_p3-r1
cbad730605e7  localhost/service.net-misc.dhcp:4.4.2-r2              -cf /etc/dhcp/dhc...  29 hours ago  Up 29 hours ago                          openrc-dhcp-4.4.2-r2
e8af63ed9fd2  localhost/service.net-dns.bind:9.14.12                -u named -f           18 hours ago  Up 18 hours ago                          openrc-bind-9.14.12
eccca3b4dffa  localhost/service.sys-apps.irqbalance:1.6.0           -d -f -s /var/run...  18 hours ago  Up 18 hours ago                          openrc-irqbalance-1.6.0
f10c04ad9233  localhost/service.dev-lang.php:7.4.6                  --fpm-config /etc...  31 hours ago  Up 31 hours ago                          openrc-php-7.4.6
dellr330 containers # mv libpod.conf libpod.conf.disabled
dellr330 containers # podman ps
CONTAINER ID  IMAGE   COMMAND  CREATED  STATUS  PORTS   NAMES
dellr330 containers # 
```

**Comment by rhatdan** [comment]
Are you saying  you have a setting in containers.conf that is being ignored by podman?  If so, what setting?

**Comment by srcshelton** [comment]
> Are you saying you have a setting in containers.conf that is being ignored by podman? If so, what setting?

Given that `podman` loses state when `libpod.conf` is removed with `containers.conf` in place, that seems to be a fair conclusion, no?

(Noting that `libpod.conf` is simply a symlink to `containers.conf`)

My `libpod.conf`/`containers.conf` reads:
```
image_default_transport = "docker://"
conmon_path = ["/usr/bin"]
conmon_env_vars = ["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"]
cgroup_manager = "cgroupfs"
lock_type = "shm"
hooks_dir=["/etc/containers/hooks"]
static_dir = "/space/podman/static"
tmp_dir = "/var/run/libpod"
max_log_size = -1
no_pivot_root = false
cni_config_dir = "/etc/cni/net.d/"
cni_plugin_dir = ["/opt/cni/bin"]
infra_image = "gcr.io/google_containers/pause-amd64:3.2"
infra_command = "/usr/bin/pause"
namespace = "podman"
num_locks = 2048
volume_path = "/space/podman/volumes"
network_cmd_path = "/usr/bin/slirp4netns"
events_logger = "file"
cni_default_network = "podman"
enable_port_reservation = true
runtime = "runc"
runtime_supports_json = ["runc", "crun"]
runtime_supports_nocgroups = ["crun"]
[runtimes]
runc = ["/usr/bin"]
crun = ["/usr/bin"]
kata-runtime = []
kata-qemu = []
kata-fc = []
```

... so `static_dir` or `volume_path`?  Is the former path used when tracking active containers?

**Comment by mheon** [comment]
The formatting of the two files is somewhat different, so it's likely that some/all of the configuration directives of libpod.conf are being discarded after the rename.

**Comment by srcshelton** [comment]
> The formatting of the two files is somewhat different, so it's likely that some/all of the configuration directives of libpod.conf are being discarded after the rename.

Ahh - in that case some clarification of the debug might be helpful to confirm that manual migration is required, as I read it to be a simple rename.

**Comment by srcshelton** [comment]
(Also, if https://github.com/containers/common/blob/master/pkg/config/containers.conf is the correct resource, then the only actual difference seems to be that `containers.conf`subdivides settings into tables, whereas with `libpod.conf` all settings are at the top-level.  So they do seem similar enough to be easily mistaken, at a glance...)

**Comment by rhatdan** [comment]
Yes containers.conf coveres more then libpod.conf, so need to be careful, we want to make libpod.conf disappear.  Fixing up man pages should be next step.

**Comment by rhatdan** [comment]
This is fixed in upstream.
