### ISSUE TITLE
How to specify OCI runtime flags to 'podman run'?

### ISSUE THREAD

**Issue by srcshelton** [containers/podman#6986]
`podman build` has the `--runtime-flags` option to pass options to the active OCI runtime.
These aren't documented or accepted for `podman run`.

I can't see any documented means to add runtime-specific options via libpod.conf/containers.conf either.

(Both `build` and `run` do support `--annotation`, I note in passing)

I'm trying to migrate from `runc` to `crun`, and being able to globally add `--runtime-flag debug --runtime-flag log=file:/var/log/crun.log` would be very helpful!

**Comment by afbjorklund** [comment]
My workaround is use a local wrapper.

```
runc-debug = [
	    "/usr/local/bin/runc-debug",
]
```

```console
$ more /usr/local/bin/runc-debug 
#!/bin/sh
exec /usr/bin/runc --debug "$@"

```

**Comment by mheon** [comment]
We don't have this flag yet, but we could certainly add it.

**Comment by srcshelton** [comment]
I get that there's a work-around... but in all fairness, it's a bit of a hack ;)

I feel that adding this flag would be a worthwhile improvement! 👍

**Comment by rhatdan** [comment]
Interested in opening a PR?

**Comment by rhatdan** [comment]
@QiWang19 Could you add this option to podman run/create.

**Comment by rhatdan** [comment]
@QiWang19 Can we get these PRs merged?

**Comment by rhatdan** [comment]
This looks like it is ready to merge, lets get it over the finish line.
