### ISSUE TITLE
CI flake: run --preserve-fds: attach / unixpacket / bad file descriptor

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#6987]
Flake seen three times on CI for #6958. Passed on re-run:
```
Running: podman [options] run --preserve-fds 1 docker.io/library/alpine:latest ls
time="2020-07-14T16:51:22-04:00" level=error msg="unable to close socket: \"close unixpacket @->/tmp/podman_test328676400/socket/7d5388edb2bed82a1bfbd8d549e58fa977154dfd03c5f6dc4ceadac06597f15c/attach: bad file descriptor\""
Error: error attaching to container 7d5388edb2bed82a1bfbd8d549e58fa977154dfd03c5f6dc4ceadac06597f15c: read unixpacket @->/tmp/podman_test328676400/socket/7d5388edb2bed82a1bfbd8d549e58fa977154dfd03c5f6dc4ceadac06597f15c/attach: read: bad file descriptor
```
Log: https://api.cirrus-ci.com/v1/task/6481256420474880/logs/integration_test.log#t--podman-run---preserve-fds

This was in "test fedora-31". cirrus-flake-xref finds no other instances of this in the last three weeks.

The error looks suspiciously close to #5769 (fixed last month), but that was `exec`; this is `run`. Possibly because of #6625

**Comment by edsantiago** [comment]
@QiWang19 PTAL

**Comment by edsantiago** [comment]
Seeing it on f32 now. Three failures, so it caused a CI flake. @QiWang19 PTAL.

* fedora-32-podman-6439450735542272 : test fedora-32
  * PR #7085
    * [07-27 17:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5376945888165888/html/integration_test.log.html#t--podman-run---preserve-fds--1)
    * [07-27 17:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5376945888165888/html/integration_test.log.html#t--podman-run---preserve-fds--2)
    * [07-27 17:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5376945888165888/html/integration_test.log.html#t--podman-run---preserve-fds--3)

**Comment by QiWang19** [comment]
This flake should be fixed by https://github.com/containers/podman/pull/7120
