### ISSUE TITLE
(podman image sign) fails with “Use a supported scheme” if the directory is explicitly specified or the default

### ISSUE THREAD

**Issue by mtrmac** [containers/podman#6993]
/kind bug

**Description**

For now, filing just to have a place to track this.

```console
$ podman --version
podman version 1.6.4
$ podman image sign --directory /var/lib/atomic/sigstore --sign-by … docker://…
…
ERRO[0000] invalid signature storage /var/lib/atomic/sigstore: writing to /var/lib/atomic/sigstore is not supported. Use a supported scheme
```

From a quick skim of the code, this seems became worse since, in that this message is triggered on many more code paths (and `--directory` is entirely ignored?!).

- `isValidSigStoreDir` is misnamed: it’s actually `localPathFromURI`
- … and it is called on strings that are paths, not URIs.

**Comment by rhatdan** [comment]
@QiWang19 PTAL
