### ISSUE TITLE
(podman image sign) uses an unpredictable image name for the destination file

### ISSUE THREAD

**Issue by mtrmac** [containers/podman#6994]
/kind bug

**Description**

For now, filling primarily to have a place to track this.

If a specific image is available locally, using several different repo@digest values, `podman image sign` will use that value instead of the name the user specified for storing the resulting signature.
 https://github.com/containers/podman/blob/54d16f3b5fc4210c7c46e4cca240f988fa5f39f5/pkg/domain/infra/abi/images.go#L637 (or the equivalent in earlier versions) should instead use the repository from `srcRef` and the digest of `getManifest`, like `c/image/docker.{configuredSignatureStorageBase,signatureStorageURL}` .

**Comment by rhatdan** [comment]
@QiWang19 PTAL
