### ISSUE TITLE
Communication to host is not working in podman 1.6.4, but working in podman 1.9.3 

### ISSUE THREAD

**Issue by bhanukumar22** [containers/podman#7007]
Communication to host is not working in podman 1.6.4, but working in podman 1.9.3

Im using RHEL 8 server, which has default podman 1.6.4

Command:
Version - 1.6.4
-------------------
podman run --name=test -d -p 10.x.x.x:8200:8200 -v /data:/data --ip=10.88.1.30 rhel:8   

This creates the container, but when I try to do telnet to host inside container, it doesn't work

telnet  10.x.x.x.  8200    ---> This doesn't work
--------------------------------------------------------------------------------------------------------------
Version - 1.9.3
--------------------
podman run --name=test -d -p 10.x.x.x:8200:8200 -v /data:/data --ip=10.88.1.30 rhel:8 

This created the container and telnet worked fine. I was able to communicate with host
---------------------------------------------------------------------------------------------------------------

But problem here is, RHEL 8,2 base OS has podman 1.6.4.
I manually upgraded to 1.9.3 and I was able to do fix the issue. 

Would be helpful if someone can let me know what was the fix done in 1.9.3? Any official RHEL link to install podman in RHEL baseOS

Thanks in advance

**Comment by mheon** [comment]
Podman 1.9.3 will be landing in RHEL 8.2.1 - so the fix should be arriving soon.

Unfortunately, I remember that the fix involved code changes (a new version of the `ocicni` library).

**Comment by bhanukumar22** [comment]
Will I be able to make container communicate with host IP on port 8200? Im trying all the ways, nothing is working. Is it going to work or I will have to wait till RHEL 8.2.1 is released. 
Please help!

**Comment by bhanukumar22** [comment]
Able to resolve this by using network=host. By default bridge was getting selected and connectivity issue was there with podman 1.6.4. As a work around, have used host network.
