### ISSUE TITLE
Toolbox: failed to write to /proc/self/oom_score_adj: Permission denied - The error returns!

### ISSUE THREAD

**Issue by RaghavRao** [containers/podman#7030]
I've seen this bug pop and be "resolved" but on Fedora 32 with  podman-2.0.2-1.fc32 and fuse-overlay 1.1.2 I still get this pesky `Error: failed to start container fedora-toolbox-32`

I rm'd .local/share/containers and .config/containers and killed podman but to no avail

**Comment by vrothberg** [comment]
Transferred the issue over to podman

**Comment by RaghavRao** [comment]
[Here](https://pastebin.com/znww74PD) is the log output for `podman start --log-level=debug fedora-toolbox-32`:

**Comment by vrothberg** [comment]
@giuseppe, do you have a suspicion what could go wrong here?

**Comment by giuseppe** [comment]
I think you've mounted cgroup v1 controllers on a cgroup v2 host.  Could you share the output for `grep cgroup /proc/mounts ` ?

If so, it is an issue in crun, fixed with: https://github.com/containers/crun/pull/436 (looks similar to https://github.com/mullvad/mullvadvpn-app/issues/1893)

are you using mullvad?

**Comment by RaghavRao** [comment]
Not Mullvad, But I have the PIA vpn client installed. Possibly same issue?
```
$ grep cgroup /proc/mounts
cgroup2 /sys/fs/cgroup cgroup2 rw,seclabel,nosuid,nodev,noexec,relatime,nsdelegate 0 0
none /sys/fs/cgroup/net_cls cgroup rw,seclabel,relatime,net_cls 0 0
```

**Comment by giuseppe** [comment]
yes definitely same issue, I am going to close this issue as it is not related podman and we already have a patch to address it.

**Comment by RaghavRao** [comment]
Thank you so much, Uninstalling PIA and rebooting fixed it. 

I find it really interesting that a conmon warning message generated by a `toolbox` command that seemed like a podman issue was actually a crun issue caused by my VPN client.

**Comment by vrothberg** [comment]
Luckily there's @giuseppe, thanks a lot!
