### ISSUE TITLE
When two or more containers are started at the same time, the latter always fails

### ISSUE THREAD

**Issue by sunyitao** [containers/podman#7058]
When two or more containers are started at the same time, the latter always fails, because dangling file in /var/lib/cni/networks/podman prevents container starting.

====================podman info
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module_el8.2.0+305+5e198a41.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: a2b11288060ebd7abd20e0b4eb1a834bbf0aec3e'
  Distribution:
    distribution: '"centos"'
    version: "8"
  MemFree: 9451700224
  MemTotal: 16513523712
  OCIRuntime:
    name: runc
    package: runc-1.0.0-65.rc10.module_el8.2.0+305+5e198a41.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 8409575424
  SwapTotal: 8409575424
  arch: amd64
  cpus: 2
  eventlogger: journald
  hostname: server1
  kernel: 4.18.0-193.6.3.el8_2.x86_64
  os: linux
  rootless: false
  uptime: 1h 15m 18.15s (Approximately 0.04 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 6
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
======end

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

/kind feature

**Description**

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Can you provide the output of `podman version` and a reproducer?

**Comment by lsm5** [comment]
I spawned 5 containers simultaneously using goroutines, seemed to work just fine for me on v2.0.4.

@sunyitao I see that you're using the podman from container-tools module on centos which is often very old. Can you check if the podman from OBS has this issue as well? Instructions for fetching it can be found at https://podman.io/getting-started/installation .

@mheon @vrothberg hope it's fair to close this. Please reopen if not :)

**Comment by sunyitao** [comment]
This problem still exists in 2.0.5

**Comment by mheon** [comment]
Please open a separate issue and provide a reproducer and any relevant
details about how and when the issue occurs.
