### ISSUE TITLE
adding a user with /bin/false as shell, doesn't add to /etc/subuid, /etc/subgid

### ISSUE THREAD

**Issue by burhan** [containers/podman#7059]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Create a new user with no shell `useradd -r -s /bin/false appuser`
2. Attempt any command, for example `sudo -u appuser podman build -t myapp -f ./Dockerfile ./`
3. `ERRO[0000] cannot find mappings for user appuser: No subuid ranges found for user "appuser" in /etc/subuid`

This should work?

**Output of `podman version`:**

```
Version: 1.6.4
RemoteAPI Version: 1
Go Version: go1.12.12
OS/Arch: linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.15-1.el7_8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.15, commit: 372b4a12f1c2df4f70c280d41173b60acd3f1260'
  Distribution:
    distribution: '"rhel"'
    version: "7.8"
  MemFree: 22437888
  MemTotal: 510885888
  OCIRuntime:
    name: runc
    package: runc-1.0.0-67.rc10.el7_8.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 1068756992
  SwapTotal: 1073737728
  arch: amd64
  cpus: 1
  eventlogger: journald
  hostname: REDACTED
  kernel: 3.10.0-1127.13.1.el7.x86_64
  os: linux
  rootless: false
  uptime: 25m 47.97s
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 0
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.4-18.el7_8.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on Fusion, but don't think that's relevant.

**Comment by rhatdan** [comment]
Seems like you believe this is a bug for shadow-utils. not much podman can do about this.

**Comment by burhan** [comment]
The initial user that I created (that has a shell) is added successfully.

So where should I raise this bug?

**Comment by rhatdan** [comment]
In bugzilla.redhat.com on shadow-utils.

The upstream repo is https://github.com/shadow-maint/shadow

**Comment by giuseppe** [comment]
agree with Dan.  There is not much Podman can do about it, that is shadow-utils responsibility.
