### ISSUE TITLE
Disappearing images after successful podman build

### ISSUE THREAD

**Issue by groovyman** [containers/podman#7060]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

This looks quite weired to me. I upgraded my system from Fedora F31 to F32 and i got a strange behaviour.
Whenever i build a new podman images, i see the newly created image on a different console. When the
podman build has been successfully finished, the images stays visible `podman images`  for a short 
period of time an then disappear.

I have no clue what is going on. In order to access a nexus repo, i am using `FROM image on repo` followed by a `copy ..`. I thought that podman is trying to send the newly created image to nexus, but i do not see any activity,

The system has been updater from F31 to F32. Maybe the FS of podman is broken.

**Steps to reproduce the issue:**

1.  create a new image via podman

2. check immediately if image is there `podman images` 

3. wait a while and see that the image disappared 

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```^[[3~host:

  arch: amd64

  buildahVersion: 1.15.0

  cgroupVersion: v2

  conmon:

    package: conmon-2.0.18-1.fc32.x86_64

    path: /usr/bin/conmon

    version: 'conmon version 2.0.18, commit: 6e8799f576f11f902cd8a8d8b45b2b2caf636a85'

  cpus: 4

  distribution:

    distribution: fedora

    version: "32"

  eventLogger: file

  hostname: l-msgn10192

  idMappings:

    gidmap:

    - container_id: 0

      host_id: 1000

      size: 1

    - container_id: 1

      host_id: 100000

      size: 65536

    uidmap:

    - container_id: 0

      host_id: 1000

      size: 1

    - container_id: 1

      host_id: 100000

      size: 65536

  kernel: 5.7.9-200.fc32.x86_64

  linkmode: dynamic

  memFree: 4084035584

  memTotal: 9076903936

  ociRuntime:

    name: crun

    package: crun-0.14.1-1.fc32.x86_64

    path: /usr/bin/crun

    version: |-

      crun version 0.14.1

      commit: 598ea5e192ca12d4f6378217d3ab1415efeddefa

      spec: 1.0.0

      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL

  os: linux

  remoteSocket:

    path: /run/user/1000/podman/podman.sock

  rootless: true

  slirp4netns:

    executable: /usr/bin/slirp4netns

    package: slirp4netns-1.1.4-1.fc32.x86_64

    version: |-

      slirp4netns version 1.1.4

      commit: b66ffa8e262507e37fca689822d23430f3357fe8

      libslirp: 4.3.1

      SLIRP_CONFIG_VERSION_MAX: 2

  swapFree: 5305790464

  swapTotal: 5305790464

  uptime: 13h 37m 36.59s (Approximately 0.54 days)

registries:

  search:

  - registry.fedoraproject.org

  - registry.access.redhat.com

  - registry.centos.org

  - docker.io

store:

  configFile: /home/groovc/.config/containers/storage.conf

  containerStore:

    number: 0

    paused: 0

    running: 0

    stopped: 0

  graphDriverName: overlay

  graphOptions:

    overlay.mount_program:

      Executable: /usr/bin/fuse-overlayfs

      Package: fuse-overlayfs-1.1.2-1.fc32.x86_64

      Version: |-

        fusermount3 version: 3.9.1

        fuse-overlayfs: version 1.1.0

        FUSE library version 3.9.1

        using FUSE kernel interface version 7.31

  graphRoot: /home/groovc/.local/share/containers/storage

  graphStatus:

    Backing Filesystem: extfs

    Native Overlay Diff: "false"

    Supports d_type: "true"

    Using metacopy: "false"

  imageStore:

    number: 0

  runRoot: /run/user/1000/containers

  volumePath: /home/groovc/.local/share/containers/storage/volumes

version:

  APIVersion: 1

  Built: 0

  BuiltTime: Thu Jan  1 01:00:00 1970

  GitCommit: ""

  GoVersion: go1.14.3

  OsArch: linux/amd64

  Version: 2.0.2
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
We have not heard about this from anyone else, so I feel like something strange might be going on on your system.

**Comment by groovyman** [comment]
Salut Daniel  
thank you for your opinion. You must be right, the dev-Environement was an ole F31, that has been upgraded. Later i change the OCI runtime environement to podman, that was accidentally set to an alternate implementation. It would be a waste to figure out, what went wrong.
I installed a new F32 server and the problem disappeared - maybe a bad ole package, i dunno.

Thank you and good luck to you!
Christian

**Comment by rhatdan** [comment]
I like problems that disappear.
