### ISSUE TITLE
events Rest API changes in v1.12

### ISSUE THREAD

**Issue by KKoukiou** [containers/podman#7078]
Previously this used to work, now it returns this error:

```
# curl -s --unix-socket /run/podman/podman.sock http://d/v1.12/events
{"cause":"unexpected end of JSON input","message":"Failed to parse parameters for /v1.12/events: unexpected end of JSON input","response":400}
```

Tested with podman-2.0.3-1.module+el8.3.0+7450+9ea086fe.x86_64

(breaks RHEL-8-3 gating)

**Comment by rhatdan** [comment]
Ok that is bad.

**Comment by mheon** [comment]
I am wondering if this was the parameter type change from @vrothberg from `map[string][]stiring` to `map[string]map[string]bool` for Docker compat.

I'm also curious as to why the Docker endpoint is being used here - thought Cockpit was using our endpoints?

**Comment by vrothberg** [comment]
I've tested it with Docker but will take a look right now.

**Comment by marusak** [comment]
> I'm also curious as to why the Docker endpoint is being used here - thought Cockpit was using our endpoints?

This was the last one where we used compat one, now we switched to libpod one - https://github.com/cockpit-project/cockpit-podman/pull/456

However it is broken in both:
```
$ sudo curl -s --unix-socket /run/podman/podman.sock http://d/v1.12/events
{"cause":"unexpected end of JSON input","message":"Failed to parse parameters for /v1.12/events: unexpected end of JSON input","response":400}
$ sudo curl -s --unix-socket /run/podman/podman.sock http://d/v1.12/libpod/events
{"cause":"unexpected end of JSON input","message":"Failed to parse parameters for /v1.12/libpod/events: unexpected end of JSON input","response":400}
```

I updated podman yesterday from fedora repos and now cannot use c-podman at all.
```
$ rpm -q podman
podman-2.0.3-1.fc32.x86_64
```

**Comment by vrothberg** [comment]
Thanks, @marusak!

**Comment by martinpitt** [comment]
Can you please make a new release with this? 2.0.3 now made it into Fedora 32 as well, and it's completely breaking cockpit-podman. Thanks!

**Comment by marusak** [comment]
FWIV we already got report about that in https://github.com/cockpit-project/cockpit-podman/issues/469, our test image refresh is blocked due to that in https://github.com/cockpit-project/bots/pull/1109 and every team member who touched c-podman in last week had problem with this. I suspect that more people will hit this problem as they update podman in their fedoras (and we even now start to support debian, where is also broken version 2.0.3)

**Comment by vrothberg** [comment]
We're on it. Just wrapped up other backports in https://github.com/containers/podman/pull/7166.
