### ISSUE TITLE
API v2 and docker-compose compatibility (Question)

### ISSUE THREAD

**Issue by ziXet** [containers/podman#7080]
Can we assume that podman v2.x.x (with new API) will eventually could work with docker-compose?

PS. I know there is a podman-compose project. But, it's not prod ready yet.

Thanks

**Comment by rhatdan** [comment]
Yes, we will work with people having compose issues, as long as those compose scripts do not use features that Podman does not support like Docker swarm.

One area of concern is around Docker networking, which is quite a bit different then Podman networking.

One last caveat is that the Podman Core developers have little experience with Compose, so we will probably be asking for easy reproducers of issues with the way we are supporting the Docker API.

**Comment by rhatdan** [comment]
We also feel(hope) that community will be very helpful in this area.

**Comment by ziXet** [comment]
Thanks Dan! I think the networking issue is the main challenge for running a simple docker-compose config.
docker has a command for creating network but Podman does networking via pods. 

Perhaps podman wants to be compatible with docker-compose and be a drop-in replacement for Docker, it needs to somehow mimic the concept of docker networking via its API.

**Comment by mheon** [comment]
We can provide networking very similar as root, but our network commands and API are not a perfect match right now due to our use of CNI. I am going to tackle improving this at some point in the next few months.

As rootless, we do not have the necessary privileges, so it is not possible to create networks at present.
