### ISSUE TITLE
Podman api v2 stable sdk

### ISSUE THREAD

**Issue by mrinaldhillon** [containers/podman#7093]
Is docker python sdk + podman-py sdk fully compatible for podman build , podman unshare, mount API for unprivileged containers ?

**Comment by mheon** [comment]
It should be compatible with Docker features, but it will not include support for unique Podman features - so no pods, no `podman mount`, no `podman generate kube` or `podman generate systemd`.

However, it should work fine with privileged containers.

**Comment by rhatdan** [comment]
These types of questions should go to the mailing list.

**Comment by TomSweeneyRedHat** [comment]
And you can subscribe to the list [here](https://lists.podman.io/admin/lists/podman.lists.podman.io/).
