### ISSUE TITLE
CI flake: Podman run/create two containers with the same IP

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#7096]
Although it's not a frequent flake, it's still a flake, and should be fixed:

Podman run with --ip flag [It] Podman run two containers with the same IP
* fedora-31 : in-podman fedora-31
  * PR #6783
    * [06-25 18:11](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5092539076182016/html/integration_test.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
    * [06-25 18:11](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5092539076182016/html/integration_test.log.html#t--Podman-run-two-containers-with-the-same-IP--2)
* fedora-31 : test fedora-31
  * PR #6372
    * [05-27 03:27](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4749736102068224/html/integration_test.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
* fedora-31-podman-5869602141896704 : in-podman fedora-31
  * PR #7079
    * [07-25 06:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6578429166354432/html/integration_test.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
    * [07-25 06:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6578429166354432/html/integration_test.log.html#t--Podman-run-two-containers-with-the-same-IP--2)
    * [07-25 06:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6578429166354432/html/integration_test.log.html#t--Podman-run-two-containers-with-the-same-IP--3)
* ubuntu-19 : test ubuntu-19
  * PR #6794
    * [06-29 11:27](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4686879750619136/html/integration_test.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
    * [06-29 11:27](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4686879750619136/html/integration_test.log.html#t--Podman-run-two-containers-with-the-same-IP--2)
    * [06-29 11:27](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4686879750619136/html/integration_test.log.html#t--Podman-run-two-containers-with-the-same-IP--3)
* ubuntu-20 : test ubuntu-20
  * PR #6609
    * [06-15 10:43](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4692372711800832/html/integration_test.log.html#t--Podman-run-two-containers-with-the-same-IP--1)

Podman create with --ip flag [It] Podman create two containers with the same IP
* fedora-31 : in-podman fedora-31
  * PR #6783
    * [06-25 18:11](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5092539076182016/html/integration_test.log.html#t--Podman-create-two-containers-with-the-same-IP--1)
* fedora-31-podman-5869602141896704 : in-podman fedora-31
  * PR #7079
    * [07-25 06:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6578429166354432/html/integration_test.log.html#t--Podman-create-two-containers-with-the-same-IP--1)
    * [07-25 06:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6578429166354432/html/integration_test.log.html#t--Podman-create-two-containers-with-the-same-IP--2)
* ubuntu-19 : test ubuntu-19
  * PR #6794
    * [06-29 11:27](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4686879750619136/html/integration_test.log.html#t--Podman-create-two-containers-with-the-same-IP--1)
    * [06-29 11:27](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/4686879750619136/html/integration_test.log.html#t--Podman-create-two-containers-with-the-same-IP--2)

I tried to fix this some months ago in #5286 but obviously there's still something I missed.

**Comment by rhatdan** [comment]
Sadly this is still active.

**Comment by edsantiago** [comment]
Correct. Instances since initial filing:

* fedora-31 : test fedora-31
  * PR #6851
    * [07-28 11:12](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5396844572311552/html/integration_test.log.html#t--Podman-create-two-containers-with-the-same-IP--1)
    * [07-28 11:12](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5396844572311552/html/integration_test.log.html#t--Podman-create-two-containers-with-the-same-IP--2)
* fedora-32 : in-podman fedora-32
  * PR #7282
    * [08-10 16:27](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4927871053463552/html/integration_test.log.html#t--Podman-create-two-containers-with-the-same-IP--1)

None of these flaked three times, so they shouldn't've triggered an actual CI run failure, but some day it will again.

**Comment by edsantiago** [comment]
* prior-fedora : test prior-fedora
  * PR #7729
    * [09-22 13:56](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6368645309792256/html/integration_test.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
    * [09-22 13:56](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6368645309792256/html/integration_test.log.html#t--Podman-run-two-containers-with-the-same-IP--2)

* prior-fedora : test prior-fedora
  * PR #7729
    * [09-22 13:56](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6368645309792256/html/integration_test.log.html#t--Podman-create-two-containers-with-the-same-IP--1)

**Comment by edsantiago** [comment]
cirrus-flake-summarize reports no incidents since 09-28, which is right around the time that @Luap99 merged #7835 so maybe this is fixed?

**Comment by rhatdan** [comment]
Maybe is good enough for me.  We will reopen if it happens again.

**Comment by edsantiago** [comment]
It's back. Reopening.

## Podman run with --ip flag [It] Podman run two containers with the same IP
* gce_instance:fedora : int remote fedora-33 root host
  * PR #9789
    * [03-23 13:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4770045071982592/html/int-remote-fedora-33-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
    * [03-23 13:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4770045071982592/html/int-remote-fedora-33-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--2)
    * [03-23 13:36](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4770045071982592/html/int-remote-fedora-33-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--3)
    * [03-23 11:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4925789176070144/html/int-remote-fedora-33-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
    * [03-23 11:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4925789176070144/html/int-remote-fedora-33-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--2)
    * [03-23 11:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4925789176070144/html/int-remote-fedora-33-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--3)
  * PR #9598
    * [03-03 17:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6135622575325184/html/int-remote-fedora-33-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
  * PR #9483
    * [02-23 06:20](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6286544166191104/html/int-remote-fedora-33-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
  * PR #9295
    * [02-09 17:58](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5005638490128384/html/int-remote-fedora-33-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
  * PR #9284
    * [02-09 14:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5693393412030464/html/int-remote-fedora-33-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
  * PR #9275
    * [02-16 07:52](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6634276798070784/html/int-remote-fedora-33-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
* gce_instance:prior-fedora : int remote fedora-32 root host
  * PR #9464
    * [02-22 11:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6006523643035648/html/int-remote-fedora-32-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
  * PR #9428
    * [02-18 13:27](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6497419346051072/html/int-remote-fedora-32-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
  * PR #9319
    * [02-11 06:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5873097595158528/html/int-remote-fedora-32-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
  * PR #9301
    * [02-10 08:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6750954016997376/html/int-remote-fedora-32-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
  * PR #9275
    * [02-16 07:53](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4593583216918528/html/int-remote-fedora-32-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
  * PR #9231
    * [02-05 05:02](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5274169908658176/html/int-remote-fedora-32-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
  * PR #9154
    * [02-03 07:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5462657635450880/html/int-remote-fedora-32-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
  * PR #9117
    * [02-22 04:31](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5323167569805312/html/int-remote-fedora-32-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
* gce_instance:prior-ubuntu : int remote ubuntu-2004 root host
  * PR #9699
    * [03-11 17:50](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5550722788884480/html/int-remote-ubuntu-2004-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
  * PR #9208
    * [02-02 22:32](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6448591940091904/html/int-remote-ubuntu-2004-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)

**Comment by edsantiago** [comment]
[another one](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4621363773177856/html/int-remote-ubuntu-2004-root-host.log.html)

**Comment by edsantiago** [comment]
Another one. [podman (non-remote) fedora-33 root](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5307986504581120/html/int-podman-fedora-33-root-host.log.html)

**Comment by edsantiago** [comment]
Sigh. Last seen on April 6; I guess that means I close it and reopen it when it happens again.

**Comment by edsantiago** [comment]
Another one. This still is not fixed:

* fedora-33 : int podman fedora-33 root host
  * PR #10970
    * [07-20 12:27](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5111577587220480/html/int-podman-fedora-33-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
    * [07-20 12:27](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5111577587220480/html/int-podman-fedora-33-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--2)
    * [07-20 12:27](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5111577587220480/html/int-podman-fedora-33-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--3)

Leaving the issue closed because I know nobody is going to look into it, so I'm saving future-me the time it takes, 30 days hence, to context-switch back into this and sigh and close it.

**Comment by edsantiago** [comment]
And again, a triple failure causing a CI failure, but it's in [f33](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5470368979746816/html/int-podman-fedora-33-root-container.log.html) on an old branch so I'm not bothering to reopen.

**Comment by edsantiago** [comment]
This just popped up again after many months of absence; but it's in test runs also affected by #14331 (the horrible sctp one)

### Podman create with --ip flag [It] Podman create two containers with the same IP 
* fedora-35 : int podman fedora-35 root host
  * PR #14354
    * [05-25 07:30](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6514268865560576/html/int-podman-fedora-35-root-host.log.html#t--Podman-create-two-containers-with-the-same-IP--1)
    * [05-25 07:30](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6514268865560576/html/int-podman-fedora-35-root-host.log.html#t--Podman-create-two-containers-with-the-same-IP--2)
  * PR #14232
    * [05-16 04:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4768504061624320/html/int-podman-fedora-35-root-host.log.html#t--Podman-create-two-containers-with-the-same-IP--1)
    * [05-16 04:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4768504061624320/html/int-podman-fedora-35-root-host.log.html#t--Podman-create-two-containers-with-the-same-IP--2)
    * [05-16 04:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4768504061624320/html/int-podman-fedora-35-root-host.log.html#t--Podman-create-two-containers-with-the-same-IP--3)
 
 
### Podman run with --ip flag [It] Podman run two containers with the same IP 
* fedora-35 : int podman fedora-35 root host
  * PR #14354
    * [05-25 07:30](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6514268865560576/html/int-podman-fedora-35-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
    * [05-25 07:30](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6514268865560576/html/int-podman-fedora-35-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--2)
    * [05-25 07:30](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6514268865560576/html/int-podman-fedora-35-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--3)
  * PR #14232
    * [05-16 04:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4768504061624320/html/int-podman-fedora-35-root-host.log.html#t--Podman-run-two-containers-with-the-same-IP--1)
