### ISSUE TITLE
podman run --env-host: inconsistency between man page, actual behavior

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#7099]
podman-run(1) documents the ENVIRONMENT precedence order as follows:
- **--env-host**: Host environment of the process executing Podman is added.
- **--http-proxy**: ....
- Container image: Any environment variables specified in the container image.

However, in practice:
```console
$ printf "FROM alpine\nENV E=defined-in-image\n" >ddd/Containerfile
$ ./bin/podman build -t foo ddd
...
$ ./bin/podman run foo printenv E
defined-in-image
$ ./bin/podman run --env-host foo printenv E
defined-in-image
$ E=from-host ./bin/podman run --env-host foo printenv E
from-host
```
I don't know if the bug is in the man page or the code. This is master @ 2b7bc9b10

If someone fixes this, no need to add tests: that's what I'm working on and how I caught it. I'll be submitting a PR tomorrow, with this particular test commented out.

**Comment by rhatdan** [comment]
Bug in the code.
@ashley-cui PTAL
Anything the user specifies overrides the defaults.

**Comment by rhatdan** [comment]
BTW This would be a good test.

**Comment by rhatdan** [comment]
Oops this is a bug in man page.
--env-host and --http-proxy should override the image.

**Comment by rhatdan** [comment]
I tested this by hand and the code seems to work correctly.

**Comment by edsantiago** [comment]
OK, I'll fix the man page in my PR.
