### ISSUE TITLE
APIv2: 'resize' resizes always to 80 characters

### ISSUE THREAD

**Issue by marusak** [containers/podman#7102]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Using [containers/resize](https://podman.readthedocs.io/en/latest/_static/api.html#operation/libpodResizeContainer) or [exec/resize](https://podman.readthedocs.io/en/latest/_static/api.html#operation/libpodResizeExec) to resize TTY session ignores `w` parameter and resizes always to 80 characters.

**Steps to reproduce the issue:**

1. 
```
sudo podman run -dt fedora bash
7d481626f41cec219a377c7fb20be9e25d37f9965e9e7e868b9361952ddef597
```
2. `sudo podman attach 7d481626f41cec219a377c7fb20be9e25d37f9965e9e7e868b9361952ddef597` and just type more than 80 characters. You should be able to type as many, as you want.

3. run in different terminal `sudo curl -X POST --unix-socket /run/podman/podman.sock "http://d/v1.24/libpod/containers/7d481626f41cec219a377c7fb20be9e25d37f9965e9e7e868b9361952ddef597/resize?w=200&h=20"` and then in the one where you are still attached you can type only 80 characters and then the line will start to overwrite itself. Feels like the `w` is ignored and 80 is used as default value?

**Output of `podman version`:**

```
Version:      2.0.2
API Version:  1
Go Version:   go1.14.3
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.2-1.fc32.x86_64
```

**Comment by rhatdan** [comment]
@jwhonce PTAL

**Comment by rhatdan** [comment]
@ashley-cui PTAL

**Comment by rhatdan** [comment]
@jwhonce What is going on with this?

**Comment by rhatdan** [comment]
@containers/podman-maintainers PTAL
It does not seem like this should be a big issue?  Is this fairly easy to fix?
