### ISSUE TITLE
CLI inconsistency with docker build

### ISSUE THREAD

**Issue by georgmu** [containers/podman#7107]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Use podman as a docker replacement
```
ln -s /usr/local/bin/docker /usr/bin/podman
```

2. Build a new docker container from stdin
```
echo -e "FROM debian:testing\nRUN /bin/echo 'Test'" | docker build -t debian-test -
```

**Describe the results you received:**

With podman as docker replacement, I get the following error:
```
Error: error reading info about "/var/tmp/buildah510720429/var/tmp/buildah510720429/Dockerfile": stat /var/tmp/buildah510720429/var/tmp/buildah510720429/Dockerfile: no such file or directory
```

**Describe the results you expected:**

With docker, the container is built and tagged:
```
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM debian:testing
testing: Pulling from library/debian
73b408cb748b: Pull complete 
Digest: sha256:3a901d53cb199478770f3fafd8cdce130b602e3f9c7695516702a39f4ab926ca
Status: Downloaded newer image for debian:testing
 ---> 03c237d6b0a4
Step 2/2 : RUN /bin/echo 'Test'
 ---> Running in 1bf2c746e69d
Test
Removing intermediate container 1bf2c746e69d
 ---> e78872fbeaef
Successfully built e78872fbeaef
Successfully tagged debian-test:latest
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.0.3
API Version:  1
Go Version:   go1.14.3
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

Podman works by using `podman build ... -f -`, but this does not work with docker. Since there are scripts which are primarily targeted at docker (e.g. the travis-ci script in systemd) and use the docker-compatible syntax, I think podman is the right place to align its CLI with docker.

**Comment by vrothberg** [comment]
Thanks for opening the issue, @georgmu!

@TomSweeneyRedHat @nalind PTAL

**Comment by rhatdan** [comment]
This works:

echo -e "FROM debian:testing\nRUN /bin/echo 'Test'" | buildah bud -t debian-test -

So this looks like a podman bug.

**Comment by TomSweeneyRedHat** [comment]
yeah, and it doesn't work if you replace `docker` with `podman` in the example above, so more finger pointing at the podman/buildah interaction and not a symlink handling issue.

**Comment by rhatdan** [comment]
Fixed merged into master branch.

**Comment by TomSweeneyRedHat** [comment]
Should this be added to the v2.0 branch too?

**Comment by vrothberg** [comment]
https://github.com/containers/podman/pull/7121 is already marked for backporting
