### ISSUE TITLE
How to install latest podman on s390x - docker-archive doesn't support digest references issue

### ISSUE THREAD

**Issue by apasrini** [containers/podman#7108]
Wanted to know how to install podman latest version in s390x.

Right now getting error Error: error getting Docker archive ImageReference for "bundle_staging_394747874/bundle.tar:.............": docker-archive doesn't support digest references

**Comment by vrothberg** [comment]
Please follow the requested issue template and provide the data along with a reproducer. It seems that you installed Podman successfully on an s390x machine.

The error message refers to (https://github.com/containers/image/blob/master/docs/containers-transports.5.md#docker-archivepathdocker-reference): docker-archive references must not contain digests.

Can you share which kind of archive you are attempting to load and the command line?

**Comment by rhatdan** [comment]
@apasrini Is this still an issue?  We have had no feed back in over a month?

**Comment by rhatdan** [comment]
Since no information, closing, reopen if further info becomes available.
