### ISSUE TITLE
Support Socket HostPath type with 'play kube' command

### ISSUE THREAD

**Issue by inflatador** [containers/podman#7112]
/kind feature

**Description**

Support Socket HostPath type with 'play kube' command
 
**Steps to reproduce the issue:**

1. podman play kube kube.yml

**Describe the results you received:**
2. message: Error: Directories are the only supported HostPath type (note that this error message is incorrect, HostPath type 'File' is also supported)

**Describe the results you expected:**

Support Socket HostPath type with 'play kube' command

**Additional information you deem important (e.g. issue happens only occasionally):**
Example kube.yml
```
spec:
  volumes:
    - name: awx_redis_conf
      hostPath:
        path: /opt/podman/etc/redis.conf
        type: File
        
    - name: aws_redis_socket
      hostPath:
        path: /opt/podman/run/redis/redis.sock
        type: Socket
        
    - name: awx_redis 
      image: redis
      command:
        - redis-server
        - "/redis/redis.conf"
      volumeMounts: 
          - name: awx_redis_conf
            mountPath: /redis/redis.conf
            readOnly: true
          - name: aws_redis_socket
            mountPath: /redis/redis.sock
            readOnly: false
```

**Output of `podman version`:**

```
podman --version
podman version 2.0.3

```

**Output of `podman info --debug`:**

```
INFO[0000] podman filtering at log level info
WARN[0000] Error initializing configured OCI runtime crun: no valid executable found for OCI runtime crun: invalid argument
WARN[0000] Error initializing configured OCI runtime kata: no valid executable found for OCI runtime kata: invalid argument
INFO[0000] Found CNI network podman (type=bridge) at /etc/cni/net.d/87-podman-bridge.conflist
WARN[0000] Default CNI network name podman is unchangeable
INFO[0000] Setting parallel job count to 25
Error: Directories are the only supported HostPath type
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
rpm -q podman
podman-2.0.3-1.el8.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CentOS 8 VM using podman installed from copr repo

**Comment by rhatdan** [comment]
@ashley-cui @haircommander PTAL
