### ISSUE TITLE
podman-remote: run --entrypoint: extra /bin/sh somewhere

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#7115]
In window 1:
```console
$ ./bin/podman system service --timeout=0
```
Window 2:
```console
$ ./bin/podman-remote run --entrypoint='["/bin/echo"]' alpine
/bin/sh     <---- expected: empty line
```
This is a problem because it's getting passed to all entrypoint commands:
```console
$ ./bin/podman-remote run --entrypoint='["/bin/date"]' alpine
date: invalid date '/bin/sh'
```
master @ 288ebec6e, root & rootless

**Comment by mheon** [comment]
The Alpine image does not specify ENTRYPOINT - instead it specified a CMD (`/bin/sh`). We were appending the image's CMD to the manually-specified ENTRYPOINT, but it looks like this is incorrect - we should only add image CMD if the user *did not* specify an entrypoint.
