### ISSUE TITLE
podman-remote: run docker-archive: ... must be a docker reference

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#7116]
In window 1:
```console
$ ./bin/podman system service --timeout=0
```
In window 2:
```console
$ ./bin/podman save -o /tmp/alpine.tar alpine
$ ./bin/podman-remote run docker-archive:/tmp/alpine.tar date
Error: image destination "docker-archive:/tmp/alpine.tar" is not a docker-transport reference: reference "docker-archive:/tmp/alpine.tar" must be a docker reference
```
Expected:
```console
$  ./bin/podman run docker-archive:/tmp/alpine.tar date
Getting image source signatures
Copying blob 50644c29ef5a [--------------------------------------] 0.0b / 0.0b
Copying config a24bb40132 done
Writing manifest to image destination
Storing signatures
Tue Jul 28 17:04:58 UTC 2020
```
master @ 288ebec6e , root & rootless

**Comment by baude** [comment]
@edsantiago this error is actually correct.  it may not be clear enough, but it is correct.  I'm worried that trying to catch this in the remote client (as opposed to the API), will bloat the remote client by bring in containers/image stuff.

wdyt?

**Comment by rhatdan** [comment]
So `podman-remote run` only supports docker transports while `podman run` supports all of the transports.
We need to document this.

**Comment by edsantiago** [comment]
@baude I'm totally fine with podman-remote not accepting this usage; I just think the error message may not be helpful to users. Loath as I am to suggest this, could the remote client be hacked to intercept the message and make it palatable? Maybe add a suggestion like "You need to `podman load %s` first"?

**Comment by rhatdan** [comment]
@edsantiago if we remove the stutter, does the message become more clear?

./bin/podman-remote run docker-archive:/tmp/alpine.tar date
Error: reference "docker-archive:/tmp/alpine.tar" must be a docker reference

**Comment by edsantiago** [comment]
TBH no, not really. It doesn't help me, the end user, figure out what's wrong. Would it be possible to intercept this error and offer a suggestion?
* "podman-remote cannot run (or create) a tarball; you need to 'podman-remote load' it first"
* "podman-remote cannot run/create an OCI archive; please 'podman-remote pull' it first"

...or something along those lines, assuming that one of those would work
