### ISSUE TITLE
podman-remote: container killed by 'rm -f', exit code is 0

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#7117]
In window 1:
```console
$ ./bin/podman system service --timeout=0
```
In window 2:
```console
$ ./bin/podman-remote run --name foo alpine sleep 30
```
In window 3:
```console
$ ./bin/podman-remote rm -f foo    [pauses 10 seconds]
<sha>
```
Go back to window 2. Container has exited, but rc=0 (expected: 137). `podman stop foo` works as expected - kills the container, and the `run` process (window 2) exits 137.

Related: #3795

master @ 288ebec6e, root & rootless

**Comment by mheon** [comment]
We need to adapt the fix for #3795 (reading events) for remote - right now it's local Podman only

**Comment by zhangguanzhang** [comment]
I test this on 2.0.5, It still exists

**Comment by zhangguanzhang** [comment]
https://github.com/containers/podman/blob/master/pkg/domain/infra/tunnel/containers.go#L481
containers has be removed by `podman-remote rm -f foo`, so this will response a 404
https://github.com/containers/podman/blob/master/pkg/bindings/containers/containers.go#L263
so line 481's `exitCode` will be 0

**Comment by vrothberg** [comment]
I opened https://github.com/containers/podman/pull/7574 to fix it. This required quite some massaging but it's passing on my end.
