### ISSUE TITLE
Rootless Podman between different users

### ISSUE THREAD

**Issue by stanislaw55** [containers/podman#7129]
This is general question about approach.

Let's assume that I would like to run applications for some user. I want this applications to be containerised and running as non-root. However, I do not trust the other user to no break things accidentally or on purpose.

So, it could be good to have some user A which has Podman installed and configured, secret to registry access and everything else that is needed to run my applications. I want to somehow allow my user B to *use* but not *modify* any of applications. Also, I would not want to share secret for accessing container registry. User B can just use application or not. Nothing more.

From what I've read in docs I did not see anything that would describe such approach. From technical point of view only thing I could think of was some mangling with user groups on Linux machine but I am not sure if this allow me to keep user A's secret, well, secret. I hope that I formulated question good enough to describe what I'm trying to achieve. 

Thanks for answers in advance

**Comment by giuseppe** [comment]
so would you like to share the images owned by user A with user B?

That is currently not supported, you'd have to copy the images from one store to the other.  You could try using additionalstores, but you need to make sure all the files are world readable.

**Comment by stanislaw55** [comment]
Hi @giuseppe, thanks for response.

I was thinking more about end result than technical solution. The bottom line is I want my user B *use* application but nothing more. Like when you install RPM, it's installed under `/usr` and is owned by root. Ordinary user cannot change it. But if there's some executable under `/usr/bin`, ordinary user can use it. I wanted to achieve something similar with Podman and containers but without having to run anything root.

**Comment by rhatdan** [comment]
I think i handled this in an article I wrote.
https://www.redhat.com/sysadmin/image-stores-podman

**Comment by skorhone** [comment]
Having image available locally is more or less same as having RPM package available locally. Creating a container from the image would be equivalent of installing RPM.

When you grant user access to create containers, you grant them access to install and run applications from any _available_ source.

If I understood your question correctly, you want to control what user is able to run. So what you really want is to control available images for a given user. I don't think there is any easy/documented way to accomplish this, **if user is able to access the host system** used for running containers. Considering that you are worried about sharing secret on host filesystem, I assume this applies to you.

**Comment by rhatdan** [comment]
I believe @stanislaw55 we answered your question? Satisfied this issue?  If not reopen the issue.
