### ISSUE TITLE
podman-remote: kill -s: hangs

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#7135]
In window 1:
```console
$ ./bin/podman system service --timeout=0
```
In window 2:
```console
$ ./bin/podman pull fedora-minimal

$ ./bin/podman-remote run -d --name foo fedora-minimal env --default-signal sh -c "trap 'echo GOT HERE' 2;while :;do sleep 1;done"
ddd0303f467f170f46ca92e9b8c8b7ce61ca5574ad50de42ea82c4ee2a831cfa

$ time ./bin/podman-remote kill -s 2 foo
^C     <--- I got impatient before waiting 10 minutes
./bin/podman-remote kill -s 2 foo  0.12s user 0.09s system 0% cpu 8:34.25 total

$ ./bin/podman-remote logs foo
GOT HERE           <--- ok, so the signal DID make it to container
```
Using `fedora-minimal` and `env` because of #5004. 

It also hangs with `-s 3`, which indicates that `trap` is not the problem. It also hangs with just plain `sleep 999`, I just did the trap thing so I could see if the container was getting the signal.

**Comment by edsantiago** [comment]
Still happening, master @ 575b3a3d8ab4f1f72d58b71aa4d534eca3a5d8f9

**Comment by vrothberg** [comment]
I'll take a stab at this one. Thanks for providing a reproducer, @edsantiago !

**Comment by vrothberg** [comment]
#7572 to the rescue
