### ISSUE TITLE
podman-remote: build: does not emit 'STEP'

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#7136]
Also, other output is out of order, and includes unexpected cruft.

In window 1:
```console
$ ./bin/podman system service --timeout=0
```
In window 2:
```console
$ printf "FROM alpine\nRUN echo hi\n" >Containerfile
$ ./bin/podman-remote build -t foo -f Containerfile .
hi               <----- what is this doing here? I expected it much farther down below
Getting image source signatures
Copying blob sha256:50644c29ef5a27c9a40c393a73ece2479de78325cae7d762ef3cdc19bf42dd0a
Copying blob sha256:1846819bbfecae935016434cedca6048bea8129532da628c1b5a88c29a77ea66
Copying config sha256:44c079bfdef6a5d51438995fa9dce6e70add2204c2d2dacfc0165e0379d9e650
Writing manifest to image destination
Storing signatures
--> 44c079bfdef
44c079bfdef6a5d51438995fa9dce6e70add2204c2d2dacfc0165e0379d9e650

FROM alpine          <--- expected: STEP 1
RUN echo hi          <--- expected: STEP 2
COMMIT foo           <--- expected: STEP 3
Successfully built 44c079bfdef6a5d51438995fa9dce6e70add2204c2d2dacfc0165e0379d9e650
```
Comparison against non-remote:
```console
$ ./bin/podman build -t foo -f Containerfile .
STEP 1: FROM alpine
STEP 2: RUN echo hi
hi
STEP 3: COMMIT foo
--> fa3f90c1de0
fa3f90c1de0be86d636cc70d4ca5d817c9d2292f7cb52a681a0c27afdaf30c52
```

**Comment by lsm5** [comment]
@vrothberg is non-remote podman ideal, or should it also emit the `Getting image source signatures` and `Copying blob..` lines?

**Comment by lsm5** [comment]
hmm, fwiw, non-remote won't say hi to me :( 

```$ ./bin/podman build -t foo -f Containerfile .
STEP 1: FROM alpine
STEP 2: RUN echo hi
--> Using cache cb4e7c12b13e5ea2b1ac71dc8405fbb197a3c447e114605dd580b16a981a121d
STEP 3: COMMIT foo
--> cb4e7c12b13
cb4e7c12b13e5ea2b1ac71dc8405fbb197a3c447e114605dd580b16a981a121d
```

**Comment by vrothberg** [comment]
@lsm5 currently `remote` does not display the information from pulling/pushing or building images.

@baude @jwhonce is that something you want to see? I guess @rhatdan has a growing desire to support that, especially for Win and Mac, but I'm not sure how much work that would be.

**Comment by zhangguanzhang** [comment]
> hmm, fwiw, non-remote won't say hi to me :(
> 
> ```
> $ ./bin/podman build -t foo -f Containerfile .
> STEP 1: FROM alpine
> STEP 2: RUN echo hi
> --> Using cache cb4e7c12b13e5ea2b1ac71dc8405fbb197a3c447e114605dd580b16a981a121d
> STEP 3: COMMIT foo
> --> cb4e7c12b13
> cb4e7c12b13e5ea2b1ac71dc8405fbb197a3c447e114605dd580b16a981a121d
> ```

I see the `Using cache`
```
[root@sz-test temp]# vi Containerfile 
[root@sz-test temp]# ../podman/bin/podman build -t foo -f Containerfile .
STEP 1: FROM docker.io/zhangguanzhang/alpine:latest
STEP 2: RUN echo hi
hi
STEP 3: COMMIT foo
--> faea0e66e6e
faea0e66e6ed18c284f79fb7eae75b446b3c9fddb880bc01501ce8dea7029332
[root@sz-test temp]# ../podman/bin/podman build -t foo -f Containerfile .
STEP 1: FROM docker.io/zhangguanzhang/alpine:latest
STEP 2: RUN echo hi
--> Using cache faea0e66e6ed18c284f79fb7eae75b446b3c9fddb880bc01501ce8dea7029332
STEP 3: COMMIT foo
--> faea0e66e6e
faea0e66e6ed18c284f79fb7eae75b446b3c9fddb880bc01501ce8dea7029332

```

**Comment by lsm5** [comment]
@zhangguanzhang thanks!

@vrothberg So, podman-remote doesn't seem to be using cache either as I can see the message echoed everytime. That should also be made similar to non-remote, yes?

**Comment by vrothberg** [comment]
> @zhangguanzhang thanks!
> 
> @vrothberg So, podman-remote doesn't seem to be using cache either as I can see the message echoed everytime. That should also be made similar to non-remote, yes?

Yes, a server-side cache could be quite helpful.

**Comment by rhatdan** [comment]
@jwhonce Has this fix been merged yet?
