### ISSUE TITLE
Recovering Podman Usability After Full Disk

### ISSUE THREAD

**Issue by rhdojun** [containers/podman#7145]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

At first there was a problem using podman after the root disk was filled by a running container (`/var/lib` not a separate mount).

```
[root@Centos7 ~]# podman ps -a
Error: error creating libpod runtime: mkdir /var/lib/containers/storage/overlay/compat258837963: no space left on device
```

So I decided to clean up with the following commands assuming that every tool should recover from its contents in `/var` being not there:

```
[root@Centos7 ~]# sudo rm -rf /var/lib/containers/storage/overlay/*
[root@Centos7 ~]# sudo rm -rf /var/lib/containers/storage/overlay-containers/*
```

However, it didn't fully recover. When I try to create a pod now, e.g. by building my [simpleserver](https://github.com/rhdojun/simpleserver) project, I get the following result:

```
Error: error creating build container: error creating container: error creating read-write layer with ID "d244d8fbcdd773c28ac7dc29a08c09358ea3c50db92acb1a6ef44d00eb0a0386": no such file or directory
```

**Steps to reproduce the issue:**

1. `[root@Centos7 code]# git clone https://github.com/rhdojun/simpleserver.git`

2. `[root@Centos7 code]# cd simpleserver/`

3. make:
```
[root@Centos7 simpleserver]# make
podman build -t simpleserver .
STEP 1: FROM centos:latest
Getting image source signatures
Copying blob 294dced27509 done  
Copying config c460095972 done  
Writing manifest to image destination
Storing signatures
Error: error creating build container: error creating container: error creating read-write layer with ID "d244d8fbcdd773c28ac7dc29a08c09358ea3c50db92acb1a6ef44d00eb0a0386": no such file or directory
make: *** [all] Error 125
```

**Describe the results you received:**

Podman errors out with: `Error: error creating build container: error creating container: error creating read-write layer with ID "d244d8fbcdd773c28ac7dc29a08c09358ea3c50db92acb1a6ef44d00eb0a0386": no such file or directory`

**Describe the results you expected:**

Podman creates the container and starts building the simpleserver project.
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
# podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.8-1.el7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.8, commit: f85c8b1ce77b73bcd48b2d802396321217008762'
  Distribution:
    distribution: '"centos"'
    version: "7"
  MemFree: 32092590080
  MemTotal: 33524305920
  OCIRuntime:
    name: runc
    package: runc-1.0.0-67.rc10.el7_8.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 1073737728
  SwapTotal: 1073737728
  arch: amd64
  cpus: 8
  eventlogger: journald
  hostname: <deleted>
  kernel: 3.10.0-1127.10.1.el7.x86_64
  os: linux
  rootless: false
  uptime: 6h 56m 14.53s (Approximately 0.25 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.fedoraproject.org
  - registry.centos.org
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions: {}
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 15
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.6.4-18.el7_8.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

bare metal. Centos provided by server maintainer.

**Comment by mheon** [comment]
I think that removing all of `/var/lib/containers/storage/` is probably necessary - otherwise, there are databases left behind that expect that the files you just removed still exist, and Podman will be very confused because of this.

**Comment by rhdojun** [comment]
That's it.

So the problem was not as I feared that I deleted too much. The problem was I didn't delete enough. All my pods are coming up again now. Thanks @mheon!
