### ISSUE TITLE
Shell within podman sometimes does not receive standard input

### ISSUE THREAD

**Issue by wwilson** [containers/podman#7183]
For at least a year, maybe longer, I've noticed a rare but annoying issue where an interactive podman container never seems to get stdin connected to it. The container is totally unresponsive, and the only way out of the situation is to run `podman kill $CONTAINER_NAME` in another terminal session.

The reason I think this is related to stdin being disconnected rather than some deadlock or infinite loop is that after the container is killed, all the things I tried to type in the original interactive session suddenly appear in the terminal from which the container was launched.

Another clue maybe: once a terminal has had this happen once, all future invocations of `podman run -it` will encounter this failure mode. However changing users in that terminal with `su` and then changing back seems to rescue it, and podman works properly again.

I've seen this on Ubuntu 16.04, 18.04, and 20.04, with a wide variety of podman versions. Unfortunately I don't have any additional guesses as to the cause. It's a weird one!

**Comment by zhangguanzhang** [comment]
How to reproduce the issue?

**Comment by wwilson** [comment]
As I said, it reproduces rarely, and seemingly at random, except that once a given terminal session is in this state, it stays there. I wish I had a better reproduction to offer.

**Comment by mheon** [comment]
Can you verify if the `reset` fixes the terminal?

Any further details about the terminal? What shell do you use, what is $TERM set to...?

**Comment by wwilson** [comment]
I am an incredibly boring Linux user. Shell is bash, $TERM is `xterm-256color`.

I will try the `reset` thing the next time this randomly happens to me.

**Comment by rhatdan** [comment]
Yes this seems like something in the terminal is getting mucked up.

**Comment by rhatdan** [comment]
@wwilson Did you figure out any additional information on this?

**Comment by wwilson** [comment]
Only one relatively weak piece of information: it appears to happen much less often on Ubuntu 20.04.

**Comment by wwilson** [comment]
Actually, now that I'm thinking about it, I haven't seen this happen in a few weeks. Maybe some combination of OS and podman upgrades has solved the issue, or at least made it asymptomatic.

**Comment by rhatdan** [comment]
Ok I am going to close, reopen if this happens again.
