### ISSUE TITLE
cannot assemble cgroup path with base "/libpod_parent" - must end in .slice: invalid argument 

### ISSUE THREAD

**Issue by djnotes** [containers/podman#7186]
When I installed Fedora 32, I couldn't use Docker. Later, I followed some instructions to allow docker to run. Later, I moved to podman and disabled Docker again (presumably by changing systemd.unified_cgroup_hierarchy=0). Now, whenever I start podman for the first time, I see this error, although it does the job (e.g. building the image):  

> ERRO[0000] Error creating CGroup for pod 29aabe91bd2d1eaf3805b00df904f40177357f75e0c499508a5086e873e4f8ea: cannot assemble cgroup path with base "/libpod_parent" - must end in .slice: invalid argument 

Just curious what this means and if I need to do anything.

**Comment by rhatdan** [comment]
@mheon PTAL

**Comment by mheon** [comment]
Looks like a container created with cgroupfs, and now Podman is using the
Systemd driver and can't make sense of the cgroup parent the container was
made with. Best solution is probably to force cgroupfs in containers.conf
for now.

We should probably not hardcode cgroup parent at creation time (unless the
user sets it), too - can lead to things like this.

**Comment by rhatdan** [comment]
@djnotes If you don't have much content could you reset your storage and see if this clears this up.

podman system reset

Note this will delete everything in your containers/storage.

**Comment by djnotes** [comment]
@rhatdan I tried `podman system reset` and executed build. It showed `sd-bus call: Permission denied`.  I rebooted the system and built and run the image without any problem. The error is gone. Why?

**Comment by rhatdan** [comment]
The sd-bus usually means that the containers can not communicate with the systemd dbus server.  I think this means your login account was not setup correctly or not initialized correctly.

We see this when people login as root and `su user`.  But if you login normaly via ssh or graphical login, systemd should setup the user session correctly.

**Comment by rhatdan** [comment]
Since we have had no futher comments, I guess we have explained it.  Reopen if more discussion is necessary.

**Comment by djnotes** [comment]
@rhatdan  

>We see this when people login as root and su user. But if you login normaly via ssh or graphical login, systemd should setup the user session correctly. 

Actually I login via a normal user. Nevertheless, after following your `podman system reset` recommendation and restarting the computer, the issue was solved completely.

**Comment by fdcds** [comment]
I confirm: The error message was gone for me as well after `podman system reset`.
