### ISSUE TITLE
IPV6 support in Podman container

### ISSUE THREAD

**Issue by sumit0900** [containers/podman#7189]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Need to configure ipv6 network over the podman containers. I have created one network and changed the</etc/cni/net.d/"network_name".conflist> file to add ipv6 support. Still I am not able to connect to public ipv6 inside container.

When I tried to remove the container then it will throws below error - 
ERRO[0000] Error deleting network: running [/sbin/ip6tables -t nat -D POSTROUTING -s fd00::1:8:2/112 -j CNI-04437f9ba3e1c4266f92bc82 -m comment --comment name: "ipv6test" id: "0c7cdf600901b541fcfe9b3efa5d89d548fdafe040769820e454fd0f923e56a6" --wait]: exit status 1: iptables: Bad rule (does a matching rule exist in that chain?). 

Is there any workaround to both the issue

**Steps to reproduce the issue:**

1.podman network create ipv6test
/etc/cni/net.d/ipv6test.conflist - 
{
   "cniVersion": "0.4.0",
   "name": "ipv6test",
   "plugins": [
      {
         "type": "bridge",
         "bridge": "cni-podman1",
         "isGateway": true,
         "ipMasq": true,
         "hairpinMode": true,
         "ipam": {
            "type": "host-local",
            "routes": [
               {
                  "dst": "0.0.0.0/0"
               },
               {
                  "dst": "::/0"
               }
            ],
            "ranges": [
               [
                  {
                     "subnet": "10.89.0.0/24",
                     "gateway": "10.89.0.1"
                  }
               ],
               [
                  {
                     "subnet": "fd00::1:8:0/112",
                     "gateway": "fd00::1:8:1"
                  }
               ]
            ]
         }
      },
      {
         "type": "portmap",
         "capabilities": {
            "portMappings": true
         }
      },
      {
         "type": "firewall",
         "backend": ""
      },
      {
         "type": "dnsname",
         "domainName": "dns.podman"
      }
   ]
}

2.podman run -dt --name ubuntu --network ipv6test ubuntu
71485ae7c8eea154d0be5a5253d27d0f9fe4c76e0e0b29ba2ba7af5341f020db

3. podman exec -it ubuntu bash
ping6 2001:4860:4860::8844
ping6: connect: Network is unreachable

4. podman rm -f ubuntu

ERRO[0000] Error deleting network: running [/sbin/ip6tables -t nat -D POSTROUTING -s fd00::1:8:2/112 -j CNI-04437f9ba3e1c4266f92bc82 -m comment --comment name: "ipv6test" id: "0c7cdf600901b541fcfe9b3efa5d89d548fdafe040769820e454fd0f923e56a6" --wait]: exit status 1: iptables: Bad rule (does a matching rule exist in that chain?). 

Am i doing something wrong in configuration? Please suggest
**Describe the results you received:**

**Describe the results you expected:**
Ipv6 communication should work after changes in network cni file.
Error should not be there while remove container from host

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
podman --version
podman version 1.9.3

**Output of `podman info --debug`:**

debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.13.4
  podmanVersion: 1.9.3
host:
  arch: amd64
  buildahVersion: 1.14.9
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.17-1.module+el8.2.1+6771+3533eb4c.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.17, commit: 3c703d9f178a3a53966e1d5c03d0275ea6cb36a0'
  cpus: 2
  distribution:
    distribution: '"rhel"'
    version: "8.2"
  eventLogger: file
  hostname: ip-172-31-99-83.us-west-2.compute.internal
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-193.el8.x86_64
  memFree: 227770368
  memTotal: 8186880000
  ociRuntime:
    name: runc
    package: runc-1.0.0-66.rc10.module+el8.2.1+6465+1a51e8b6.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 50h 53m 47.67s (Approximately 2.08 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 3
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by sumit0900** [comment]
Looks like ping issue resolved as I had some custom nft tables and after delete ping6 using ipv6 inside container is working.
Is there any workaround to "exit status 1: iptables: Bad rule (does a matching rule exist in that chain?)" issue.
It appeared every time when i tried to remove container.
Steps - podman rm -f <container name>

ERRO[0000] Error deleting network: running [/sbin/ip6tables -t nat -D POSTROUTING -s fd00::1:8:4/112 -j CNI-685ba65fbd6b7fcfbf06c5ce -m comment --comment name: "demo" id: "85f12ce7ce04c4b0d1d33113c5e691f9a4d0167075f37fe914cef50a10b67b62" --wait]: exit status 1: iptables: Bad rule (does a matching rule exist in that chain?). 
ERRO[0000] Error while removing pod from CNI network "demo": running [/sbin/ip6tables -t nat -D POSTROUTING -s fd00::1:8:4/112 -j CNI-685ba65fbd6b7fcfbf06c5ce -m comment --comment name: "demo" id: "85f12ce7ce04c4b0d1d33113c5e691f9a4d0167075f37fe914cef50a10b67b62" --wait]: exit status 1: iptables: Bad rule (does a matching rule exist in that chain?). 
ERRO[0000] unable to cleanup network for container 85f12ce7ce04c4b0d1d33113c5e691f9a4d0167075f37fe914cef50a10b67b62: "error tearing down CNI namespace configuration for container 85f12ce7ce04c4b0d1d33113c5e691f9a4d0167075f37fe914cef50a10b67b62: running [/sbin/ip6tables -t nat -D POSTROUTING -s fd00::1:8:4/112 -j CNI-685ba65fbd6b7fcfbf06c5ce -m comment --comment name: \"demo\" id: \"85f12ce7ce04c4b0d1d33113c5e691f9a4d0167075f37fe914cef50a10b67b62\" --wait]: exit status 1: iptables: Bad rule (does a matching rule exist in that chain?).\n" 
85f12ce7ce04c4b0d1d33113c5e691f9a4d0167075f37fe914cef50a10b67b62

Any ip6table rule that i have to add manually? Or I am doing something wrong.

**Comment by mheon** [comment]
@sumit0900 Can you provide `ip6tables -nvL` and `ip6tables -t nat -nvL` both with and without a container running?

**Comment by sumit0900** [comment]
@mheon Commands before container running - 
**ip6tables -nvL**
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination  


**ip6tables -t nat -nvL**
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination  

Commands after container running -

**ip6tables -nvL**
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 CNI-FORWARD  all      *      *       ::/0                 ::/0                 /* CNI firewall plugin rules */

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain CNI-FORWARD (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 CNI-ADMIN  all      *      *       ::/0                 ::/0                 /* CNI firewall plugin rules */
    0     0 ACCEPT     all      *      *       ::/0                 fd00::1:8:36         ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all      *      *       fd00::1:8:36         ::/0                

Chain CNI-ADMIN (1 references)
 pkts bytes target     prot opt in     out     source               destination  

**ip6tables -t nat -nvL**
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 CNI-f484be9537c2b4c00ca3b6e9  all      *      *       fd00::1:8:36         ::/0                 /* name: "demo" id: "b02bd89cd470cccd438525c1c06c8b843eac7e90d80ef544f9fa121271cb25ec" */

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain CNI-f484be9537c2b4c00ca3b6e9 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all      *      *       ::/0                 fd00::1:8:0/112      /* name: "demo" id: "b02bd89cd470cccd438525c1c06c8b843eac7e90d80ef544f9fa121271cb25ec" */
    0     0 MASQUERADE  all      *      *       ::/0                !ff00::/8             /* name: "demo" id: "b02bd89cd470cccd438525c1c06c8b843eac7e90d80ef544f9fa121271cb25ec" */

Let me know if anything else is required

**Comment by mheon** [comment]
It looks like there are basically no rules present for IPv6 - most notably I am not seeing any masquerade rules to NAT the container?

@mccv1r0 Mind taking a look here?

**Comment by mccv1r0** [comment]
A quick test on fedora 32 / podman 1.8.0 shows this works.   Note:  I don't have dnsname plugin so it was removed.   Also, ping6 doesn't exist in ubuntu image so I just used an image I have handy.

```
[root@snark net.d]# podman run -dt --name v6test0 --network ipv6test socksink-sudo 
0fe8633110ac22c9c8f5dfd5697f06ee88454ea4631b871c460e88d619fcc5f4
[root@snark net.d]# podman exec -it v6test0 /bin/bash 
root@0fe8633110ac:/# ping6 2001:4860:4860::8844
PING 2001:4860:4860::8844(2001:4860:4860::8844) 56 data bytes
64 bytes from 2001:4860:4860::8844: icmp_seq=1 ttl=119 time=1.69 ms
64 bytes from 2001:4860:4860::8844: icmp_seq=2 ttl=119 time=1.46 ms
^C
--- 2001:4860:4860::8844 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 1.460/1.577/1.694/0.117 ms
root@0fe8633110ac:/# exit
exit
Error: non zero exit code: 127: OCI runtime error
[root@snark net.d]# podman version 
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.12.15
OS/Arch:            linux/amd64
[root@snark net.d]# 

```

Removing works too.

```
[root@snark net.d]# podman rm -f ubuntu
b2412c69e1bef6cece8a1a571404a0227d5b102eef24c8e9f1d5bf88a3294ae1
[root@snark net.d]# podman rm -f v6test0
0fe8633110ac22c9c8f5dfd5697f06ee88454ea4631b871c460e88d619fcc5f4
[root@snark net.d]# 
```

What version of cni is podman using?

**Comment by mheon** [comment]
Podman v1.9.3 vendors code from Plugins v0.8.5. It looks like RHEL 8.2.1 shipped v0.8.6, though.

**Comment by sumit0900** [comment]
How to check the version of CNI and plugins?

**Comment by mheon** [comment]
`rpm -q containernetworking-plugins`

**Comment by mheon** [comment]
Oops, wrong button

**Comment by sumit0900** [comment]
rpm -q containernetworking-plugins
containernetworking-plugins-0.8.6-1.module+el8.2.1+6626+598993b4.x86_64

podman --version
podman version 1.9.3

cat /etc/redhat-release 
Red Hat Enterprise Linux release 8.2 (Ootpa)

**Comment by Balthyr** [comment]
Hello,

I'm facing the same issue like @sumit0900 on CentOS:
```bash
[root@poddy ~]# podman run -it --rm alpine /bin/ash
/ # ping -6 google.com
PING google.com (2a00:1450:400f:80a::200e): 56 data bytes
ping: sendto: Network unreachable
/ # ip ad
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if5: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP 
    link/ether 16:cb:e7:f5:63:01 brd ff:ff:ff:ff:ff:ff
    inet 10.88.0.37/16 brd 10.88.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fd00:dead:cafe::2/64 scope global 
       valid_lft forever preferred_lft forever
    inet6 fe80::14cb:e7ff:fef5:6301/64 scope link 
       valid_lft forever preferred_lft forever
/ # ERRO[0046] Error deleting network: running [/usr/sbin/ip6tables -t nat -D POSTROUTING -s fd00:dead:cafe::2/64 -j CNI-b5cf3e62c17e41fe475ca220 -m comment --comment name: "podman" id: "250f1bcf26b584baf28a67daab1ced96dfab8e29dc47ab5399beafac790dfbde" --wait]: exit status 1: iptables: Bad rule (does a matching rule exist in that chain?). 
ERRO[0046] Error while removing pod from CNI network "podman": running [/usr/sbin/ip6tables -t nat -D POSTROUTING -s fd00:dead:cafe::2/64 -j CNI-b5cf3e62c17e41fe475ca220 -m comment --comment name: "podman" id: "250f1bcf26b584baf28a67daab1ced96dfab8e29dc47ab5399beafac790dfbde" --wait]: exit status 1: iptables: Bad rule (does a matching rule exist in that chain?). 
ERRO[0046] unable to cleanup network for container 250f1bcf26b584baf28a67daab1ced96dfab8e29dc47ab5399beafac790dfbde: "error tearing down CNI namespace configuration for container 250f1bcf26b584baf28a67daab1ced96dfab8e29dc47ab5399beafac790dfbde: running [/usr/sbin/ip6tables -t nat -D POSTROUTING -s fd00:dead:cafe::2/64 -j CNI-b5cf3e62c17e41fe475ca220 -m comment --comment name: \"podman\" id: \"250f1bcf26b584baf28a67daab1ced96dfab8e29dc47ab5399beafac790dfbde\" --wait]: exit status 1: iptables: Bad rule (does a matching rule exist in that chain?).\n" 
```

The versions of Podman and CNI are the latest ones:
```bash
[root@poddy ~]# podman version
Version:      2.0.4
API Version:  1
Go Version:   go1.13.4
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
[root@poddy ~]# rpm -q containernetworking-plugins
containernetworking-plugins-0.8.6-1.el8.x86_64
```

**Comment by mheon** [comment]
Can you also provide the CNI config you're using, and `ip6tables -nvL` / `ip6tables -t nat -nvL` output?

**Comment by Balthyr** [comment]
Sure. Here is my CNI config:

```json
{
  "cniVersion": "0.4.0",
  "name": "podman",
  "plugins": [
    {
      "type": "bridge",
      "bridge": "cni-podman0",
      "isGateway": true,
      "ipMasq": true,
      "hairpinMode": true,
      "ipam": {
        "type": "host-local",
        "routes": [{"dst": "0.0.0.0/0"}, {"dst": "::/0"}],
        "ranges": [
          [
            {
              "subnet": "10.88.0.0/16",
              "gateway": "10.88.0.1"
            }
          ],
          [
            {
              "subnet": "fd00:dead:cafe::/64",
              "gateway": "fd00:dead:cafe:0:ffff:ffff:ffff:fffe"
            }
          ]
        ]
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      }
    },
    {
      "type": "firewall"
    },
    {
      "type": "tuning"
    }
  ]
}
```

- **`ip6tables -nvL`**:
```bash
Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  138 17880 CNI-FORWARD  all      *      *       ::/0                 ::/0                 /* CNI firewall plugin rules */

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain CNI-FORWARD (1 references)
 pkts bytes target     prot opt in     out     source               destination         
  138 17880 CNI-ADMIN  all      *      *       ::/0                 ::/0                 /* CNI firewall plugin rules */
    0     0 ACCEPT     all      *      *       ::/0                 fd00:dead:cafe::7    ctstate RELATED,ESTABLISHED
    0     0 ACCEPT     all      *      *       fd00:dead:cafe::7    ::/0                

Chain CNI-ADMIN (1 references)
 pkts bytes target     prot opt in     out     source               destination  
```
- **`ip6tables -t -nvL`**:
```bash
Chain PREROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain INPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain POSTROUTING (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
   16  1320 SNAT       all      *      veth0   fd00:dead:cafe::/64  ::/0                 to:2a01:4f9:c010:1192::cd
    0     0 CNI-5ddc3285f3de547f1cb52d8b  all      *      *       fd00:dead:cafe::7    ::/0                 /* name: "podman" id: "56d661853d95d847516b5e345c2ba57eb643cd0eae72e476ca0f90f35a7941ac" */

Chain OUTPUT (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain CNI-d6a7b1b9d9130b681def95b5 (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all      *      *       ::/0                 fd00:dead:cafe::/64  /* name: "podman" id: "a7408ba29f078c9dfac92ce30bd919cdacc0e08a7d3811f740df1b1dd1ccecb0" */
    0     0 MASQUERADE  all      *      *       ::/0                !ff00::/8             /* name: "podman" id: "a7408ba29f078c9dfac92ce30bd919cdacc0e08a7d3811f740df1b1dd1ccecb0" */

Chain CNI-b5cf3e62c17e41fe475ca220 (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all      *      *       ::/0                 fd00:dead:cafe::/64  /* name: "podman" id: "250f1bcf26b584baf28a67daab1ced96dfab8e29dc47ab5399beafac790dfbde" */
    0     0 MASQUERADE  all      *      *       ::/0                !ff00::/8             /* name: "podman" id: "250f1bcf26b584baf28a67daab1ced96dfab8e29dc47ab5399beafac790dfbde" */

Chain CNI-bd51c819d4c1a9ab433768b5 (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all      *      *       ::/0                 fd00:dead:cafe::/64  /* name: "podman" id: "2c85b0b0ed0c5ec1768249ae5fc50f0df7a09a0c7bccd36b630373fec4cf0a93" */
    0     0 MASQUERADE  all      *      *       ::/0                !ff00::/8             /* name: "podman" id: "2c85b0b0ed0c5ec1768249ae5fc50f0df7a09a0c7bccd36b630373fec4cf0a93" */

Chain CNI-76cd743e9cf74b9a2d506605 (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all      *      *       ::/0                 fd00:dead:cafe::/64  /* name: "podman" id: "8e94e54991eaf3e8adc0b2a97c54fa153f5bd3d180f304ac8fb616f2b1b51b07" */
    0     0 MASQUERADE  all      *      *       ::/0                !ff00::/8             /* name: "podman" id: "8e94e54991eaf3e8adc0b2a97c54fa153f5bd3d180f304ac8fb616f2b1b51b07" */

Chain CNI-d77d861d8652ab7661b27e7e (0 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all      *      *       ::/0                 fd00:dead:cafe::/64  /* name: "podman" id: "197315364d771e9971ada70b8248a08448319ea85fda14fb5b1693129f5efe26" */
    0     0 MASQUERADE  all      *      *       ::/0                !ff00::/8             /* name: "podman" id: "197315364d771e9971ada70b8248a08448319ea85fda14fb5b1693129f5efe26" */

Chain CNI-5ddc3285f3de547f1cb52d8b (1 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     all      *      *       ::/0                 fd00:dead:cafe::/64  /* name: "podman" id: "56d661853d95d847516b5e345c2ba57eb643cd0eae72e476ca0f90f35a7941ac" */
    0     0 MASQUERADE  all      *      *       ::/0                !ff00::/8             /* name: "podman" id: "56d661853d95d847516b5e345c2ba57eb643cd0eae72e476ca0f90f35a7941ac" */
```

- **An interesting thing is that the connection to web sites like `google.com` works without any issues:**
```bash
/ # curl -IL6 google.com
HTTP/1.1 301 Moved Permanently
Location: http://www.google.com/
Content-Type: text/html; charset=UTF-8
Date: Wed, 05 Aug 2020 22:18:03 GMT
Expires: Fri, 04 Sep 2020 22:18:03 GMT
Cache-Control: public, max-age=2592000
Server: gws
Content-Length: 219
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN

HTTP/1.1 200 OK
Content-Type: text/html; charset=ISO-8859-1
P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
Date: Wed, 05 Aug 2020 22:18:03 GMT
Server: gws
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
Transfer-Encoding: chunked
Expires: Wed, 05 Aug 2020 22:18:03 GMT
Cache-Control: private
Set-Cookie: 1P_JAR=2020-08-05-22; expires=Fri, 04-Sep-2020 22:18:03 GMT; path=/; domain=.google.com; Secure
Set-Cookie: NID=204=pHfdVK1v-O_gPwVUBzG4gLr0AdtIgpW7EfYJSOdEWXzYnGyw6_K41XLkv-lzgfiCFE9MjSoav4DJV1SUQLVaYMn_Xc-tpJ04yx2npUcsvj6i6rPCKlDruWnSbRT7N1hPrmk2YMm5BXkqZ238aq3RGP-oYXBVC2gAyK-_NlIxp5w; expires=Thu, 04-Feb-2021 22:18:03 GMT; path=/; domain=.google.com; HttpOnly
/ # ip -6 route
fd00:dead:cafe::/64 dev eth0  metric 256 
fe80::/64 dev eth0  metric 256 
default via fd00:dead:cafe:0:ffff:ffff:ffff:fffe dev eth0  metric 1024 
ff00::/8 dev eth0  metric 256 
```

**Comment by rhatdan** [comment]
@mheon have you gotten a chance to look at this?

**Comment by mheon** [comment]
No - and honestly, it's rapidly exceeding my expertise with networking (I know enough about IPv4 and iptables to be dangerous, but my knowledge of v6 is a lot more limited). I think we need to get a solid reproducer and hand this over to the CNI folks.

**Comment by mccv1r0** [comment]
I think this https://bugzilla.redhat.com/show_bug.cgi?id=1860518 is what is being seen.

**Comment by mheon** [comment]
That sounds about right. If I follow that correctly, it looks like we need an update to go-iptables or ip6tables itself to resolve.

**Comment by rhatdan** [comment]
@mheon Any progress on this?

**Comment by mheon** [comment]
@rhatdan It's out of our hands. We need an update to either `ip6tables` or the CNI bridge plugin, or possibly both. @haircommander wanted to take a look to be sure but doesn't seem to have had a chance yet.

**Comment by haircommander** [comment]
yeah I haven't had time, but I really think the best place to fix is in the cni bridge plugin

**Comment by rhatdan** [comment]
@mccv1r0 WDYT?

**Comment by unixfox** [comment]
Bump

**Comment by cehoffman** [comment]
It is likely that the ip6tables command is using nftables under the hood through a compatibility interface. Debian buster is such a system, to use the original iptables you need to switch to the `-legacy` executables. Example on debian buster that fixed the issue for me.

~~~sh
update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
update-alternatives --set iptables /usr/sbin/iptables-legacy
~~~

**Comment by mheon** [comment]
CNI should be able to work with the `nftables` frontend commands - we did a lot of work a year or so ago to get a good experience with `iptables` with the `nftables` backend working as expected. Unfortunately we did not work with `ip6tables` at the same time. Most of what needed to be changes was exit codes (CNI checks those to determine what a command actually did, and they seem to have changed during the transition).

**Comment by rhatdan** [comment]
@mheon So what do you propose we do?

**Comment by mheon** [comment]
The linked BZ indicates the issue has been fixed upstream. I think part of it is the go-iptables revendor Tom is doing? We can get CNI 0.9.1 out in Podman 3.1 and have folks retest?

**Comment by rhatdan** [comment]
I believe this is fixed in the main branch now closing, Reopen if I am mistaken.
