### ISSUE TITLE
Drop [Install] section from podman.service

### ISSUE THREAD

**Issue by martinpitt** [containers/podman#7190]
/kind bug

/kind feature

**Description**

`podman.service` is socket activated through `podman.socket`. It should not have its own `[Install]` section, it does not make sense to `systemctl enable podman.service`. This is defined [here](https://github.com/containers/podman/blob/master/contrib/systemd/system/podman.service#L12).

This leads to podman.service always running on a Debian system, as Debian's policy is to enable/start running services by default.

Can you please drop this?

**Output of `podman version`:**

    podman version 2.0.4

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unstable,now 2.0.4+dfsg1-1 amd64 [installed]
```

**Comment by vrothberg** [comment]
Thanks for the report. I'll open a PR in a minute.
