### ISSUE TITLE
podman-remote: pull: stderr goes to server, not client

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#7198]
This one is so old, and so obvious, that I had simply assumed there was already an open issue. There isn't (at least as far as I can find), neither open nor closed.

In window 1:
```console
$ ./bin/podman system service --timeout=0
```
In window 2:
```console
$ ./bin/podman-remote pull busybox
018c9d7b792b4be80095d957533667279843acf9a46c973067c8d1dff31ea8b4
```
Back to window 1 (the server):
```
Trying to pull registry.fedoraproject.org/busybox...
  manifest unknown: manifest unknown
Trying to pull registry.access.redhat.com/busybox...
  name unknown: Repo not found
Trying to pull registry.centos.org/busybox...
  manifest unknown: manifest unknown
Trying to pull docker.io/library/busybox...
Getting image source signatures
Copying blob 61c5ed1cbdf8 done
Copying config 018c9d7b79 done
Writing manifest to image destination
Storing signatures
```
The above output is usually sent to stderr in regular non-remote podman. With podman-remote, it is displayed only on the server, whose output is almost certainly invisible to the remote user.

**Comment by edsantiago** [comment]
Still a problem.

**Comment by vrothberg** [comment]
@jwhonce is your PR (https://github.com/containers/podman/pull/7452) fixing that?

**Comment by jwhonce** [comment]
Fixed by https://github.com/containers/podman/pull/7647 

Please reopen if there are additional issues
