### ISSUE TITLE
Verify that /etc/hosts and /etc/resolv.conf are handled appropriately in bind

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman#7206]
This PR in Buildah: https://github.com/containers/buildah/pull/2488 fixes an issue with `buildah run` where /etc/hosts and /etc/resolv.conf are bound when there's no network in the container.  This keeps the user from making and retaining any values to the two files.

This issue is a place holder to check that the issue doesn't live in `podman run` too, and to  fix it there is a problem.

**Comment by mheon** [comment]
This is already handled correctly for `--net=none`.
