### ISSUE TITLE
Podman --remote argument ordering can instead run local Podman

### ISSUE THREAD

**Issue by mheon** [containers/podman#7211]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Argument ordering with `podman --remote` can cause Podman to not run remote, and instad execute locally.

**Steps to reproduce the issue:**

1. `podman run -t -i --rm --name testctr fedora bash`

2. `podman system service --log-level=debug`

3. `podman exec --log-level=debug --remote exec -t -i testctr bash`

**Describe the results you received:**

Note that `podman exec` debug logs indicate that it started Conmon, and there are no debug logs out of `podman system service`

**Describe the results you expected:**

Debug logs for `podman system service` indicate that `podman exec` executed remotely.

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Output of `podman version`:**

Master

**Comment by jwhonce** [comment]
@mheon From previous discussions `--remote` must be given before subcommand. Otherwise, it gets eaten before the subcommand can see it. https://github.com/containers/podman/pull/7212 does allow `--remote` to be given anywhere between `podman` and subcommand.

**Comment by mheon** [comment]
@jwhonce Oops, I mistyped the example - omit the first `exec`

It should be `podman --log-level=debug --remote ...`
