### ISSUE TITLE
[APIv2] Adding a container to a just 'Created' pod will start it but not 'start' event will be sent for the pod

### ISSUE THREAD

**Issue by KKoukiou** [containers/podman#7213]
/kind bug

**Description**

There is not 'start' event for pods, which got started after bring created by adding a running container to these. 

**Steps to reproduce the issue:**

1. $ podman pod create --name=user_one

2. $ sudo podman pod ps 
POD ID        NAME                  STATUS   CREATED        # OF CONTAINERS  INFRA ID
4d1b9950b7c8  user_one              Created  4 minutes ago  1                58f0cc683006

2. $ podman run -dit --pod user_one fedora bash

**Describe the results you received:**
 The user_one pod will now be Running but there is not event received.

**Describe the results you expected:**
Expected to receive `start` event for the pod.

**Output of `podman version`:**

```
podman version 2.0.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.4-1.fc32.x86_64
```

**Comment by mheon** [comment]
We aren't technically starting the *pod* - we're starting the infra container for the pod. If there are other containers in the pod, we do not start them, only the infra container. As such, I tend to think that we should not be generating a "pod start" event.

**Comment by KKoukiou** [comment]
> We aren't technically starting the _pod_ - we're starting the infra container for the pod. If there are other containers in the pod, we do not start them, only the infra container. As such, I tend to think that we should not be generating a "pod start" event.

I see what you are saying, but could you still emit a "pod start" event (or some event) when the PODS status changes from "Created" to "Running", which is what happens in this case?

**Comment by mheon** [comment]
Maybe we need a better state for the pod here, to indicate it's only partially running - because you could run a `podman pod start` on a pod in that state, and it would still start containers within the pod.

**Comment by mheon** [comment]
I'm going to bring this up at scrum tomorrow and ask for opinions from the team. I think we may end up with a new state for pods that are only partially running.

**Comment by rhatdan** [comment]
I believe having another state makes sense.  Although I do not have a good name for that state.

**Comment by mheon** [comment]
Kube makes me lean towards `Degraded` as a good name.

**Comment by rhatdan** [comment]
Works for me.

**Comment by rhatdan** [comment]
@mheon Did you ever have a chance to work on this?

**Comment by mheon** [comment]
No - will get to it this week.

**Comment by rhatdan** [comment]
@KKoukiou @mheon Is this still an issue or did the linked merge fix it?

**Comment by rhatdan** [comment]
Since I never heard back, I am going to assume that this is fixed. Reopen if I am mistaken.
