### ISSUE TITLE
"PodName" property in Containers object never filled by the Rest API 

### ISSUE THREAD

**Issue by KKoukiou** [containers/podman#7214]
/kind bug

**Description**

When listing containers through the Rest API there is PodName property which should be there according to the documentation but it's always empty string. "Pod" property contains the Pod ID and can be used to identify the pods instead.

**Steps to reproduce the issue:**

1.  sudo curl --unix-socket /run/podman/podman.sock http://d/v1.24/libpod/containers/json | jq
``` json  
{
    "Command": [
      "bash"
    ],
...
    "Pod": "8cc10866fa4c22029afc01846525ed96fa726384ad95884b7d99e9a09ed4c642",
    "PodName": "",
...
  }
]
```

**Output of `podman version`:**

```
podman version 2.0.4
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.19-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.19, commit: 5dce9767526ed27f177a8fa3f281889ad509fea7'
  cpus: 4
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: sequioa
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.7.8-200.fc32.x86_64
  linkmode: dynamic
  memFree: 241860608
  memTotal: 11945615360
  ociRuntime:
    name: runc
    package: runc-1.0.0-144.dev.gite6555cc.fc32.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10+dev
      commit: fbdbaf85ecbc0e077f336c03062710435607dbf1
      spec: 1.0.1-dev
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4742705152
  swapTotal: 6039793664
  uptime: 26h 3m 13.98s (Approximately 1.08 days)
registries:
  localhost:5000:
    Blocked: false
    Insecure: true
    Location: localhost:5000
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: localhost:5000
  search:
  - localhost:5000
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 8
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.14.6
  OsArch: linux/amd64
  Version: 2.0.4

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.4-1.fc32.x86_64
```

**Comment by rhatdan** [comment]
Does the pod actually have a name?

**Comment by KKoukiou** [comment]
> Does the pod actually have a name?

Sure, with sudo podman pod inspect I can see the Name property, I double verified now.

**Comment by rhatdan** [comment]
The code is looking for a opts.Pod option to be set to get this information.
```
	if opts.Pod && len(conConfig.Pod) > 0 {
		pod, err := rt.GetPod(conConfig.Pod)
		if err != nil {
			return entities.ListContainer{}, err
		}
		ps.PodName = pod.Name()
	}
```

**Comment by KKoukiou** [comment]
@rhatdan Oh right - my fault.

The documentation clearly says it, https://podman.readthedocs.io/en/latest/_static/api.html#operation/libpodListContainers

That  opts.Pod should be set to get information about the pod (Id, Name) when listing containers.

It was confusing because I did not set that parameter,  but the PodId was present in the container details (which should be missing according to the docs) - in my case only the PodName was missing.

**Comment by rhatdan** [comment]
I am wondering why we don't return it always.  I think this might be a performance issue.

@mheon @baude Ideas?

**Comment by mheon** [comment]
Yes, this is mainly performance - Pod ID is free, pod name requires a
lookup in the DB for each container.

**Comment by baude** [comment]
ill take this one and look into it.

**Comment by baude** [comment]
talked to @mheon , we have a good way to do this and not make it too much a perf hit.

**Comment by baude** [comment]
as such, @mheon is taking this over as it in involves a db call.
