### ISSUE TITLE
podman (1) is not on docs.podman.io

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman#7219]
The main man page for podman (1) is not on the docs.podman.io site and should be as there are a number of global options listed on that man page that are used by a variety of commands and it should be available there along with the other man pages.

**Comment by rhatdan** [comment]
@baude @TomSweeneyRedHat Have either of  you gotten a chance to look at this.

After quickly reviewing the docs, not sure where the man page should be referenced, perhaps in the main commands page.

It would also be nice to get the man page links to work.  IE If I am looking at podman-attach and it refereces podman-exec, I should be able to click on the see-also link at the bottom of the page.

**Comment by TomSweeneyRedHat** [comment]
I've not looked at it since dropping this issue so we wouldn't forget it.  I'm not sure where it should live either on the page, but my thought was at least under the commands section along with the other man pages.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Any movement on this?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan not that I'm aware of.  I think we'll need some of @baude 's time to figure out the readthedocs bit.  There's some funkiness there with the main man page and getting it published.

**Comment by rhatdan** [comment]
This is fixed.
