### ISSUE TITLE
RFE: default to "OCIFile" in addition to "Dockerfile"

### ISSUE THREAD

**Issue by langdon** [containers/podman#7225]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I would like to have a default filename for builds in addition to "Dockerfile." I have been using "OCIFile" as it seems accurate but, presently, I have to pass "-f" to pick it up. I would prefer it just find it.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 2.0.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.4-1.fc32.x86_64
```

**Comment by mheon** [comment]
After some debate, I believe we settled on (and presently support) `Containerfile`

**Comment by langdon** [comment]
Oh, ha, I tried searching the issues and didn't find anything seemingly related. That's a great answer! Sorry for the noise.

**Comment by TomSweeneyRedHat** [comment]
Yes, we indeed search for Containerfile, then if not found, Dockerfile when doing a build.  OCIFile is a good suggestion too, we had considered that at one point before settling on Containerfile.

**Comment by vrothberg** [comment]
Note that building is not standardized in the OCI. I believe that's why Containerfile won the race.
