### ISSUE TITLE
Silence healthcheck warnings on hosts without systemd when '--no-healthcheck' is specified

### ISSUE THREAD

**Issue by srcshelton** [containers/podman#7234]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Calling `podman run` on a Dockerfile containing a `HEALTHCHECK` statements fails (and throws errors on container removal) if attempted on a host system not running systemd.

**Describe the results you received:**

Attempting to start the container defined by https://github.com/netdata/netdata/blob/master/packaging/docker/Dockerfile:

```
# ./netdata.docker 
Trying to pull docker.io/netdata/netdata...
Getting image source signatures
Copying blob 6da931af51a4 skipped: already exists  
Copying blob a460fefbc2da skipped: already exists  
Copying blob 1c21fe61f2e0 skipped: already exists  
Copying blob 5008bc6f0a3a skipped: already exists  
Copying blob 83ca82b89f48 skipped: already exists  
Copying blob 7ea78e5885cd skipped: already exists  
Copying blob 0f328e810e2f skipped: already exists  
Copying blob d93edfd5aada [--------------------------------------] 0.0b / 0.0b
Copying blob 4875e21803c1 [--------------------------------------] 0.0b / 0.0b
Copying config 2584673e50 done  
Writing manifest to image destination
Storing signatures
ERRO[0004] unable to get systemd connection to add healthchecks: dial unix /run/systemd/private: connect: no such file or directory 
ERRO[0004] unable to get systemd connection to start healthchecks: dial unix /run/systemd/private: connect: no such file or directory 
a42252888d45228b19f9f2da630f92428644b9ffac929fb9145ecae02cfc4a27
 -> 0
# podman ps -a | grep netdata-hc
a42252888d45  docker.io/netdata/netdata:latest                                           About a minute ago  Exited (1) About a minute ago  0.0.0.0:19999->19999/tcp  netdata-hc
# podman rm -v a42252888d45228b19f9f2da630f92428644b9ffac929fb9145ecae02cfc4a27
ERRO[0000] Error removing timer for container a42252888d45228b19f9f2da630f92428644b9ffac929fb9145ecae02cfc4a27 healthcheck: unable to get systemd connection to remove healthchecks: dial unix /run/systemd/private: connect: no such file or directory 
a42252888d45228b19f9f2da630f92428644b9ffac929fb9145ecae02cfc4a27
```

The ideal would be to have an alternate health check back-end which doesn't assume the presence of systemd, or perhaps a warning suggesting the use of `--no-healthcheck`.

It feels, though, as if a healthcheck not even being able to be started should be a warning rather than a fatal error?

**Output of `podman version`:**

```
Version:      2.0.3
API Version:  1
Go Version:   go1.14.5
Git Commit:   2349723f89bdb3033d064f6278ca04da8b8ae42d
Built:        Wed Jul 29 21:34:26 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: 13244db638cf987c415298a3c23393ae5abeb885'
  cpus: 8
  distribution:
    distribution: gentoo
    version: unknown
  eventLogger: file
  hostname: dellr330
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.38-gentoo
  linkmode: dynamic
  memFree: 994226176
  memTotal: 8132190208
  ociRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc91
      commit: 24a3cf88a7ae5f4995f6750654c0e2ca61ef4bb2
      spec: 1.0.2-dev
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 25697181696
  swapTotal: 25769787392
  uptime: 192h 6m 37.05s (Approximately 8.00 days)
registries:
  search:
  - docker.io
  - docker.pkg.github.com
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 5
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.ignore_chown_errors: "false"
  graphRoot: /space/podman/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 883
  runRoot: /space/podman/run
  volumePath: /space/podman/volumes
version:
  APIVersion: 1
  Built: 1596058466
  BuiltTime: Wed Jul 29 21:34:26 2020
  GitCommit: 2349723f89bdb3033d064f6278ca04da8b8ae42d
  GoVersion: go1.14.5
  OsArch: linux/amd64
  Version: 2.0.3

```

**Comment by mheon** [comment]
@baude PTAL

**Comment by baude** [comment]
as mentioned, systemd is required for healthchecks. no other backend has been developed.  making the failure non-fatal seems reasonable.

**Comment by vrothberg** [comment]
> as mentioned, systemd is required for healthchecks. no other backend has been developed. making the failure non-fatal seems reasonable.

SGTM :+1:

**Comment by rhatdan** [comment]
@vrothberg @srcshelton @baude Was anything done to make this happen?

**Comment by vrothberg** [comment]
Not to my knowledge.

**Comment by mheon** [comment]
Concur, this still needs to be worked on.

**Comment by baude** [comment]
I have looked at the code and had @mheon double check.  We can conclude that the failure to setup, execute, and remove a healthcheck is not fatal.  It is logged as a logrus (i.e. log only).  I think something else might be failing and those messages are a red herring?

anyways, closing for now. re-open if you dont buy my explanation or open a new issue if there is something else.  thanks for the excellent report.

**Comment by srcshelton** [comment]
You're right and further investigation shows that the warnings (logged as ERROrs ;) are indeed non-fatal.

However, the appear even for containers started with the `--no-healthcheck` parameter... please could these logs be entirely silenced if the container has been started with an explicit instruction to disable healthchecks?

**Comment by srcshelton** [comment]
(@baude would you be able to re-open this issue, or should I raise the above as a new issue?)

**Comment by rhatdan** [comment]
@baude did you ever fix this issue?

**Comment by cbluth** [comment]
im getting a similar error with podman running inside a docker container:
```
exit status 125 Error:
unable to create pod cgroup for pod cf4b9b5d5e2870fffc5025e1043c610d340956732eca9a6e590e2293ef4b3b31: error creating cgroup machine.slice/machine-libpod_pod_cf4b9b5d5e2870fffc5025e1043c610d340956732eca9a6e590e2293ef4b3b31.slice:
dial unix /run/systemd/private: connect: no such file or directory
```

**Comment by mheon** [comment]
That is a very different error, please file a separate bug report for it.

**Comment by rhatdan** [comment]
@mheon is the original issue fixed?  Can we close this?

**Comment by baude** [comment]
I should be working on this bug today at some point; specifically the secondary issue reported when no attempts to connect to systemd should occur when systemd is not present.

**Comment by rhatdan** [comment]
@baude any update on this?

**Comment by srcshelton** [comment]
I did a quick test with `podman-3.2.0_rc1` and the output is now:

```
ERRO[0034] Error removing timer for container 9132be32131e7364b18a647c4e584ff0a1feb00e5560835eb2ad1fbeb5c47b31 healthcheck: unable to get systemd connection to remove healthchecks: dial unix /var/run/systemd/private: connect: no such file or directory 
```

… **but** if `--no-healthcheck` is used it no longer complains!

**Comment by Yajo** [comment]
Is there a way to make `/run/systemd/private` actually available inside docker/podman containers?

**Comment by Yajo** [comment]
Oh and by the way, [the man page](https://www.man7.org/linux/man-pages/man1/init.1.html#SOCKETS_AND_FIFOS) says:

>     /run/systemd/private           
> Used internally as communication channel between systemctl(1)
           and the systemd process. This is an AF_UNIX stream socket.
           This interface is private to systemd and **should not be used
           in external projects**.

Does that bold phrase apply to podman? 🤔

**Comment by rhatdan** [comment]
Yes, but if you are using SELinux, you must disable the SELinux separation on the container.  It also seems like you have to be in the same pid namespace as the host.

```
# cat /tmp/Containerfile 
from fedora 
run yum -y install /usr/bin/systemctl
# podman build -t systemctl /tmp/
STEP 1: FROM fedora
STEP 2: run yum -y install /usr/bin/systemctl
Fedora 34 openh264 (From Cisco) - x86_64        2.8 kB/s | 2.5 kB     00:00    
Fedora Modular 34 - x86_64                      2.0 MB/s | 4.9 MB     00:02    
Fedora Modular 34 - x86_64 - Updates            2.1 MB/s | 4.2 MB     00:01    
Fedora 34 - x86_64 - Updates                    3.6 MB/s |  11 MB     00:03    
Fedora 34 - x86_64                              3.5 MB/s |  74 MB     00:20    
Dependencies resolved.
...
# podman run --pid=host -v /run:/run --security-opt label=disable systemctl systemctl status
● 689749c49865
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Wed 2021-05-19 15:02:56 UTC; 4 days ago
   CGroup: /
           └─342304 systemctl status
sh-5.1# podman run --pid=host -v /run:/run --security-opt label=disable systemctl systemctl status podman.socket
● podman.socket - Podman API Socket
     Loaded: loaded (/usr/lib/systemd/system/podman.socket; enabled; vendor preset: disabled)
     Active: active (listening) since Wed 2021-05-19 15:03:00 UTC; 4 days ago
   Triggers: ● podman.service
       Docs: man:podman-system-service(1)
     Listen: /run/podman/podman.sock (Stream)
      Tasks: 0 (limit: 18689)
     Memory: 0B
        CPU: 0
     CGroup: /system.slice/podman.socket
```

**Comment by Yajo** [comment]
> Is there a way to make `/run/systemd/private` actually available inside docker/podman containers?

I made it by making sure systemd is pid 1 inside the container.

**Comment by rhatdan** [comment]
Ok I misunderstood the question, but I wrote a blog on the answer anyways.
