### ISSUE TITLE
`podman system service` and `podman system connection` is not on docs.podman.io

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman#7252]
The man page for `podman system service` seems to be missing from docs.podman.io.  This [page](http://docs.podman.io/en/latest/system.html) has a number of commands for `podman system`, but service is not one of them.

`podman system connection` is also not on this page and should be.

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by edeediong** [comment]
Seems this issue has been fixed. Should it still be opened?
