### ISSUE TITLE
podman creating improperly configured containers

### ISSUE THREAD

**Issue by ideepika** [containers/podman#7260]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

```
 podman run -d --name jaeger \
  -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
  -p 5775:5775/udp \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 14268:14268 \
  -p 14250:14250 \
  -p 9411:9411 \
  jaegertracing/all-in-one:1.18
Error: stat /home/deepika/.local/share/containers/storage/overlay/ffd9ff7408b75314c2fea3331aea9b7ee4be6b54e4f7de30771b869aee82f167: no such file or directory
```

**Additional information you deem important (e.g. issue happens only occasionally):**

reproduced everytime
**Output of `podman version`:**

```
podman version 2.0.4

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.19-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.19, commit: 5dce9767526ed27f177a8fa3f281889ad509fea7'
  cpus: 8
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: x1carbon
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
  kernel: 5.7.10-201.fc32.x86_64
  linkmode: dynamic
  memFree: 239558656
  memTotal: 16651743232
  ociRuntime:
    name: crun
    package: crun-0.14.1-1.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.14.1
      commit: 598ea5e192ca12d4f6378217d3ab1415efeddefa
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 2
  swapFree: 5967097856
  swapTotal: 8392798208
  uptime: 178h 45m 35.28s (Approximately 7.42 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/ideepika/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/deepika/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 3
  runRoot: /run/user/1000/containers
  volumePath: /home/deepika/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Thu Jan  1 05:30:00 1970
  GitCommit: ""
  GoVersion: go1.14.6
  OsArch: linux/amd64
  Version: 2.0.4


(paste your output here)
```

**Comment by TomSweeneyRedHat** [comment]
@ideepika thanks for the issue report.  Couple of quick hits.  I'm assuming that you're running this as a rootless user?  Are you able to pull the image `jaegertracing/all-in-one:1.18`?  Does this by chance run as root?

**Comment by ideepika** [comment]
@TomSweeneyRedHat yes, no issues there, the container is not able to configure properly.

**Comment by rhatdan** [comment]
@giuseppe fuse-overlayfs?

**Comment by giuseppe** [comment]
I've used the same command and it works fine here.  Can you please share the output when you run with `--log-level debug`?

**Comment by rhatdan** [comment]
```
$  podman run -d --name jaeger \
>   -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
>   -p 5775:5775/udp \
>   -p 6831:6831/udp \
>   -p 6832:6832/udp \
>   -p 5778:5778 \
>   -p 16686:16686 \
>   -p 14268:14268 \
>   -p 14250:14250 \
>   -p 9411:9411 \
>   jaegertracing/all-in-one:1.18
Trying to pull registry.fedoraproject.org/jaegertracing/all-in-one:1.18...
  manifest unknown: manifest unknown
Trying to pull registry.access.redhat.com/jaegertracing/all-in-one:1.18...
  name unknown: Repo not found
Trying to pull registry.centos.org/jaegertracing/all-in-one:1.18...
  manifest unknown: manifest unknown
Trying to pull docker.io/jaegertracing/all-in-one:1.18...
Getting image source signatures
Copying blob 8c0dcf21dc1c done  
Copying blob 38530a749fd6 done  
Copying blob 6fb6138a05a8 done  
Copying config 0e2e4c273c done  
Writing manifest to image destination
Storing signatures
7571949a146160b4d714c966f55bea50dbb3f166ac79ad3f4dcd854df52a3995
```

Also works for me

**Comment by ideepika** [comment]
@giuseppe 
```
INFO[0000] podman filtering at log level debug          
DEBU[0000] Called run.PersistentPreRunE(podman run -d --name jaeger -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 -p 5775:5775/udp -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778 -p 16686:16686 -p 14268:14268 -p 14250:14250 -p 9411:9411 --log-level debug jaegertracing/all-in-one:1.18) 
DEBU[0000] Ignoring libpod.conf EventsLogger setting "/home/ideepika/.config/containers/containers.conf". Use "journald" if you want to change this setting and remove libpod.conf files. 
DEBU[0000] Reading configuration file "/usr/share/containers/containers.conf" 
DEBU[0000] Merged system config "/usr/share/containers/containers.conf": &{{[] [] containers-default-0.14.6 [] private enabled [CAP_AUDIT_WRITE CAP_CHOWN CAP_DAC_OVERRIDE CAP_FOWNER CAP_FSETID CAP_KILL CAP_MKNOD CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETFCAP CAP_SETGID CAP_SETPCAP CAP_SETUID CAP_SYS_CHROOT] [] []  [] [] [] false [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] false false false  private k8s-file -1 slirp4netns false 2048 private /usr/share/containers/seccomp.json 65536k private host 65536} {true systemd [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] [/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon] ctrl-p,ctrl-q true /run/user/1000/libpod/tmp/events/events.log file [/usr/share/containers/oci/hooks.d] docker:// /pause k8s.gcr.io/pause:3.2 /usr/libexec/podman/catatonit shm   false 2048 /usr/bin/crun map[crun:[/usr/bin/crun /usr/sbin/crun /usr/local/bin/crun /usr/local/sbin/crun /sbin/crun /bin/crun /run/current-system/sw/bin/crun] kata:[/usr/bin/kata-runtime /usr/sbin/kata-runtime /usr/local/bin/kata-runtime /usr/local/sbin/kata-runtime /sbin/kata-runtime /bin/kata-runtime /usr/bin/kata-qemu /usr/bin/kata-fc] runc:[/usr/bin/runc /usr/sbin/runc /usr/local/bin/runc /usr/local/sbin/runc /sbin/runc /bin/runc /usr/lib/cri-o-runc/sbin/runc /run/current-system/sw/bin/runc]] missing false   [] [crun runc] [crun] [kata kata-runtime kata-qemu kata-fc] {false false false false false false} /etc/containers/policy.json false 3 /home/ideepika/.local/share/containers/storage/libpod 10 /run/user/1000/libpod/tmp /home/ideepika/.local/share/containers/storage/volumes} {[/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin] podman /etc/cni/net.d/}} 
DEBU[0000] Using conmon: "/usr/bin/conmon"              
DEBU[0000] Initializing boltdb state at /home/ideepika/.local/share/containers/storage/libpod/bolt_state.db 
DEBU[0000] Overriding graph root "/home/ideepika/.local/share/containers/storage" with "/home/deepika/.local/share/containers/storage" from database 
DEBU[0000] Overriding static dir "/home/ideepika/.local/share/containers/storage/libpod" with "/home/deepika/.local/share/containers/storage/libpod" from database 
DEBU[0000] Overriding volume path "/home/ideepika/.local/share/containers/storage/volumes" with "/home/deepika/.local/share/containers/storage/volumes" from database 
DEBU[0000] Using graph driver overlay                   
DEBU[0000] Using graph root /home/deepika/.local/share/containers/storage 
DEBU[0000] Using run root /run/user/1000/containers     
DEBU[0000] Using static dir /home/deepika/.local/share/containers/storage/libpod 
DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
DEBU[0000] Using volume path /home/deepika/.local/share/containers/storage/volumes 
DEBU[0000] Set libpod namespace to ""                   
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] overlay: mount_program=/usr/bin/fuse-overlayfs 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=false 
DEBU[0000] Initializing event backend file              
DEBU[0000] using runtime "/usr/bin/runc"                
DEBU[0000] using runtime "/usr/bin/crun"                
WARN[0000] Error initializing configured OCI runtime kata: no valid executable found for OCI runtime kata: invalid argument 
DEBU[0000] using runtime "/usr/bin/crun"                
INFO[0000] Setting parallel job count to 25             
DEBU[0000] Adding port mapping from 5775 to 5775 length 1 protocol "udp" 
DEBU[0000] Adding port mapping from 6831 to 6831 length 1 protocol "udp" 
DEBU[0000] Adding port mapping from 6832 to 6832 length 1 protocol "udp" 
DEBU[0000] Adding port mapping from 5778 to 5778 length 1 protocol "" 
DEBU[0000] Adding port mapping from 16686 to 16686 length 1 protocol "" 
DEBU[0000] Adding port mapping from 14268 to 14268 length 1 protocol "" 
DEBU[0000] Adding port mapping from 14250 to 14250 length 1 protocol "" 
DEBU[0000] Adding port mapping from 9411 to 9411 length 1 protocol "" 
DEBU[0000] parsed reference into "[overlay@/home/deepika/.local/share/containers/storage+/run/user/1000/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]docker.io/jaegertracing/all-in-one:1.18" 
DEBU[0000] parsed reference into "[overlay@/home/deepika/.local/share/containers/storage+/run/user/1000/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]docker.io/jaegertracing/all-in-one:1.18" 
DEBU[0000] parsed reference into "[overlay@/home/deepika/.local/share/containers/storage+/run/user/1000/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]@0e2e4c273c1d9e999ccfdfa242f4753198bc65a06f2a895f6c7d5dccd6682d77" 
DEBU[0000] exporting opaque data as blob "sha256:0e2e4c273c1d9e999ccfdfa242f4753198bc65a06f2a895f6c7d5dccd6682d77" 
Error: stat /home/deepika/.local/share/containers/storage/overlay/ffd9ff7408b75314c2fea3331aea9b7ee4be6b54e4f7de30771b869aee82f167: no such file or directory

```

**Comment by giuseppe** [comment]
do you have `/home` on a different partition?  What does `lsblk -af` show?

**Comment by ideepika** [comment]
@giuseppe 
```
NAME FSTYPE FSVER LABEL UUID                                   FSAVAIL FSUSE% MOUNTPOINT
loop0
     squash 4.0                                                      0   100% /var/lib/s
loop1
     squash 4.0                                                      0   100% /var/lib/s
sda                                                                           
nvme0n1
│                                                                             
├─nvme0n1p1
│    vfat   FAT32       1602-C334                               578.4M     3% /boot/efi
├─nvme0n1p2
│    ext4   1.0         148ad8b6-872a-4030-a613-e8e7b5ca89ce    659.5M    26% /boot
└─nvme0n1p3
     LVM2_m LVM2        Qyyvl9-N7Sk-M5ve-F1wG-ttwS-SngH-c39zh2                
  ├─fedora_localhost--live-root00
  │  ext4   1.0         c8f3561b-5fbc-4cb9-bf84-d46bfb3ab9ca     51.5G    20% /
  ├─fedora_localhost--live-swap00
  │  swap   1           4ca3c07d-581b-480f-9f3d-09fbb34f0b37                  [SWAP]
  └─fedora_localhost--live-home00
     ext4   1.0         569fa954-d4d0-443c-a1cf-aa4939f506c1     43.8G    67% /home
```
sorry missed notification, but still the issue persists

**Comment by ideepika** [comment]
@giuseppe @rhatdan @TomSweeneyRedHat this is blocking in some sense.
I can see the cause being I moved the previous username to a new user and deleted old one, but turns out podman is somehow picking up the old one in creating overlay path: 
`Error: stat /home/deepika/.local/share/containers/storage/overlay/ffd9ff7408b75314c2fea3331aea9b7ee4be6b54e4f7de30771b869aee82f167: no such file or directory`

while should be `/home/new_username/*`

**Comment by ideepika** [comment]
> @giuseppe
> 
> ```
> INFO[0000] podman filtering at log level debug          
> DEBU[0000] Called run.PersistentPreRunE(podman run -d --name jaeger -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 -p 5775:5775/udp -p 6831:6831/udp -p 6832:6832/udp -p 5778:5778 -p 16686:16686 -p 14268:14268 -p 14250:14250 -p 9411:9411 --log-level debug jaegertracing/all-in-one:1.18) 
> DEBU[0000] Ignoring libpod.conf EventsLogger setting "/home/ideepika/.config/containers/containers.conf". Use "journald" if you want to change this setting and remove libpod.conf files. 
> DEBU[0000] Reading configuration file "/usr/share/containers/containers.conf" 
> DEBU[0000] Merged system config "/usr/share/containers/containers.conf": &{{[] [] containers-default-0.14.6 [] private enabled [CAP_AUDIT_WRITE CAP_CHOWN CAP_DAC_OVERRIDE CAP_FOWNER CAP_FSETID CAP_KILL CAP_MKNOD CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETFCAP CAP_SETGID CAP_SETPCAP CAP_SETUID CAP_SYS_CHROOT] [] []  [] [] [] false [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] false false false  private k8s-file -1 slirp4netns false 2048 private /usr/share/containers/seccomp.json 65536k private host 65536} {true systemd [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] [/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon] ctrl-p,ctrl-q true /run/user/1000/libpod/tmp/events/events.log file [/usr/share/containers/oci/hooks.d] docker:// /pause k8s.gcr.io/pause:3.2 /usr/libexec/podman/catatonit shm   false 2048 /usr/bin/crun map[crun:[/usr/bin/crun /usr/sbin/crun /usr/local/bin/crun /usr/local/sbin/crun /sbin/crun /bin/crun /run/current-system/sw/bin/crun] kata:[/usr/bin/kata-runtime /usr/sbin/kata-runtime /usr/local/bin/kata-runtime /usr/local/sbin/kata-runtime /sbin/kata-runtime /bin/kata-runtime /usr/bin/kata-qemu /usr/bin/kata-fc] runc:[/usr/bin/runc /usr/sbin/runc /usr/local/bin/runc /usr/local/sbin/runc /sbin/runc /bin/runc /usr/lib/cri-o-runc/sbin/runc /run/current-system/sw/bin/runc]] missing false   [] [crun runc] [crun] [kata kata-runtime kata-qemu kata-fc] {false false false false false false} /etc/containers/policy.json false 3 /home/ideepika/.local/share/containers/storage/libpod 10 /run/user/1000/libpod/tmp /home/ideepika/.local/share/containers/storage/volumes} {[/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin] podman /etc/cni/net.d/}} 
> DEBU[0000] Using conmon: "/usr/bin/conmon"              
> DEBU[0000] Initializing boltdb state at /home/ideepika/.local/share/containers/storage/libpod/bolt_state.db 
> DEBU[0000] Overriding graph root "/home/ideepika/.local/share/containers/storage" with "/home/deepika/.local/share/containers/storage" from database 
> DEBU[0000] Overriding static dir "/home/ideepika/.local/share/containers/storage/libpod" with "/home/deepika/.local/share/containers/storage/libpod" from database 
> DEBU[0000] Overriding volume path "/home/ideepika/.local/share/containers/storage/volumes" with "/home/deepika/.local/share/containers/storage/volumes" from database 
> DEBU[0000] Using graph driver overlay                   
> DEBU[0000] Using graph root /home/deepika/.local/share/containers/storage 
> DEBU[0000] Using run root /run/user/1000/containers     
> DEBU[0000] Using static dir /home/deepika/.local/share/containers/storage/libpod 
> DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp      
> DEBU[0000] Using volume path /home/deepika/.local/share/containers/storage/volumes 
> DEBU[0000] Set libpod namespace to ""                   
> DEBU[0000] [graphdriver] trying provided driver "overlay" 
> DEBU[0000] overlay: mount_program=/usr/bin/fuse-overlayfs 
> DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=false 
> DEBU[0000] Initializing event backend file              
> DEBU[0000] using runtime "/usr/bin/runc"                
> DEBU[0000] using runtime "/usr/bin/crun"                
> WARN[0000] Error initializing configured OCI runtime kata: no valid executable found for OCI runtime kata: invalid argument 
> DEBU[0000] using runtime "/usr/bin/crun"                
> INFO[0000] Setting parallel job count to 25             
> DEBU[0000] Adding port mapping from 5775 to 5775 length 1 protocol "udp" 
> DEBU[0000] Adding port mapping from 6831 to 6831 length 1 protocol "udp" 
> DEBU[0000] Adding port mapping from 6832 to 6832 length 1 protocol "udp" 
> DEBU[0000] Adding port mapping from 5778 to 5778 length 1 protocol "" 
> DEBU[0000] Adding port mapping from 16686 to 16686 length 1 protocol "" 
> DEBU[0000] Adding port mapping from 14268 to 14268 length 1 protocol "" 
> DEBU[0000] Adding port mapping from 14250 to 14250 length 1 protocol "" 
> DEBU[0000] Adding port mapping from 9411 to 9411 length 1 protocol "" 
> DEBU[0000] parsed reference into "[overlay@/home/deepika/.local/share/containers/storage+/run/user/1000/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]docker.io/jaegertracing/all-in-one:1.18" 
> DEBU[0000] parsed reference into "[overlay@/home/deepika/.local/share/containers/storage+/run/user/1000/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]docker.io/jaegertracing/all-in-one:1.18" 
> DEBU[0000] parsed reference into "[overlay@/home/deepika/.local/share/containers/storage+/run/user/1000/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]@0e2e4c273c1d9e999ccfdfa242f4753198bc65a06f2a895f6c7d5dccd6682d77" 
> DEBU[0000] exporting opaque data as blob "sha256:0e2e4c273c1d9e999ccfdfa242f4753198bc65a06f2a895f6c7d5dccd6682d77" 
> Error: stat /home/deepika/.local/share/containers/storage/overlay/ffd9ff7408b75314c2fea3331aea9b7ee4be6b54e4f7de30771b869aee82f167: no such file or directory
> ```
> 
> also, an observation that might help, this works fine with sudo(root privileges)

you see here as well, instead of using ideepika, podman is making use of /home/deepika ( whick does no exists)

**Comment by ideepika** [comment]
when with sudo I get:
```
DEBU[0000] failed to create container jaeger(e50e8dd9d65d3e0e155642d8ec06bd80b69746df133d11b1ee30e7bba92f15e9): the container name "jaeger" is already in use by "0cab192af4338714f7a89a51842dbc979db8b38821f06490b507cff397173d31". You have to remove that container to be able to reuse that name.: that name is already in use 
Error: error creating container storage: the container name "jaeger" is already in use by "0cab192af4338714f7a89a51842dbc979db8b38821f06490b507cff397173d31". You have to remove that container to be able to reuse that name.: that name is already in use
```
although I have tried to remove the container using it's ID as well:

```
sudo docker rm 0cab192af4338714f7a89a51842dbc979db8b38821f06490b507cff397173d31
Error: No such container: 0cab192af4338714f7a89a51842dbc979db8b38821f06490b507cff397173d31
```

**Comment by mheon** [comment]
You will need to `podman rm --storage` the ID if it does not appear in `podman ps` but Podman complains about it existing

**Comment by rhatdan** [comment]
podman ps -a --storage
now exists.  Working on adding the ability to remove specific container images.
