### ISSUE TITLE
Add --connection flag

### ISSUE THREAD

**Issue by jwhonce** [containers/podman#7276]
Add `--connection <name>` flag allowing the user to pick the connection to use from `containers.conf`.  Giving a non-existing connection will cause a failure.

This will override the default connection in the user's and system's `containers.conf`. It will not override the CONTAINER_* environment variables for building a connection. 

New resolution precedence:

- env `CONTAINER_HOST` / `CONTAINER_SSHKEY`
- env `CONTAINER_CONNECTION`
- `--url` / `--identity` 
- `--connection`
- results from `podman system connection default <name>` (`containers.conf`)
- defaults `unix://run/podman/podman.sock` or `ssh://root@<host>:22/run/podman/podman.sock`

**Comment by jwhonce** [comment]
@rhatdan and @baude PTAL re: Any additional requirements?

**Comment by rhatdan** [comment]
This is the requirement we want.
