### ISSUE TITLE
Cannot run any podman commands

### ISSUE THREAD

**Issue by j00bar** [containers/podman#7278]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Cannot run any podman commands.

**Steps to reproduce the issue:**

1. Run `podman` with or without subcommands, with or without arguments.

**Describe the results you received:**

```
[jag@bad-chicken ~]$ podman
ERRO[0000] error validating engine configs: static directory must be an absolute path - instead got "test/libpod" 
[jag@bad-chicken ~]$ podman ps
ERRO[0000] error validating engine configs: static directory must be an absolute path - instead got "test/libpod" 
[jag@bad-chicken ~]$ podman --help
ERRO[0000] error validating engine configs: static directory must be an absolute path - instead got "test/libpod" 
[jag@bad-chicken ~]$ podman -v
ERRO[0000] error validating engine configs: static directory must be an absolute path - instead got "test/libpod" 
```

**Describe the results you expected:**
Anything at all.

**Output of `podman version`:**

```
ERRO[0000] error validating engine configs: static directory must be an absolute path - instead got "test/libpod" 
```

**Output of `podman info --debug`:**

```
ERRO[0000] error validating engine configs: static directory must be an absolute path - instead got "test/libpod" 
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.4-1.fc32.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical.

**Comment by mheon** [comment]
Appears that you're running rootless. Can you check if you have a `~/.config/containers/libpod.conf` or `~/.config.containers/containers.conf` and provide the contents of each if you do?

**Comment by rhatdan** [comment]
Since we have had no response @j00bar I figure this issue no longer exists, closing.  Reopen if I am mistaken
