### ISSUE TITLE
RFE: rootless containers running on remote storage

### ISSUE THREAD

**Issue by langdon** [containers/podman#7279]
/kind feature

**Description**

I mount my "work" directory from another computer on my network via sshfs or NFS and often want to run a container mounting the content of those directories inside the container. Unfortunately, if I use the ":z" flag on the volume mount, selinux is unable to relabel the content correctly.

In case it helps with coming up with ideas for a solution, this is the actual error I get (with paths changed to protect the innocent):
```Error: relabel failed "/mnt/remote-computer/dir1/blender-render": failed to set file label on /mnt/remote-computer/dir1/blender-render: operation not supported```

Command I run is:
```podman run --rm -it -v $PWD:/files:z blender-render```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.0.4
API Version:  1
Go Version:   go1.14.6
Built:        Wed Dec 31 19:00:00 1969
OS/Arch:      linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.4-1.fc32.x86_64
```

**Comment by rhatdan** [comment]
What happens without the :z, does it work or does SELinux block it?  If SELinux blocks access what AVC's are generated?

**Comment by langdon** [comment]
Ummm. It just works. Is this a change at some point? I never used to be able to access local files inside the container with ":z".

**Comment by langdon** [comment]
Awesomely, it just works. 

However, i had no idea that the label on the file would effect this. Or, put a different way, i didn't know some labels were exempt from the enforcing policy on the container. In short, if you have files labeled: `fusefs_t` or `nfs_t` -- don't use ":z" and you can access the files on the host. However, if you have other labels (e.g. `user_home_t`) you do need the ":z" so that the file can be relabeled as `container_file_t`. I am sure this list is not exhaustive.
