### ISSUE TITLE
RFE: anchors in docs.podman.io's man pages would be nice to have

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman#7300]
I'm not sure it is possible, or easily doable, but it would be nice to have anchors on the man pages that are shown in docs.podman.io.  For instance, I was reviewing @ashley-cui 's blog on timezones and I wanted to link to the tz option there, with something like: `http://docs.podman.io/en/latest/markdown/podman-run.1.html#--tz` but I could not.  I had to use a link to the top of the page, and it's a long scroll down.

**Comment by ashley-cui** [comment]
It looks like you can link headers but not content inside the headers, which is seems to be a markdown standard? Otherwise, you can definitely do them, I know regular HTML anchors work on markdown, but you would need to create an anchor for each flag which may be super annoying. Might be a better way, but this is as much as I know now :)

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @ashley-cui Any movement on this?

**Comment by TomSweeneyRedHat** [comment]
I believe it's been smoldering in the background, but still a nice to have.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @ashley-cui Is this something you think we will ever have?  Or should I close the issue?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan I'd love to have it, just a matter of time.  I'd leave it in hopes someone will grab it and run with it.

**Comment by rhatdan** [comment]
I have just read up on this.  So you want to take each option and make them into a link
Something like?
```
[**--tz**=*timezone*](#--tz)
```
Sadly gomd2man makes the man page look like
```
man podman-create
...
       --tz=timezone ⟨#--tz⟩
```

**Comment by TomSweeneyRedHat** [comment]
Honestly, I've not dived into the syntax that's needed to make it happen, but the end result would be something like what we have on podman.io that @Luap99 (I think) did for us.  I'm not sure if he's a thought or three on this.  So the end result is you'd see a little link symbol next to the titles in the online man page, and whecn clicked on you'd get something like:  https://podman.io/#podman-has-gone-210

**Comment by Luap99** [comment]
I will take a look.
