### ISSUE TITLE
Unable to install podman in Ubuntu 18.04

### ISSUE THREAD

**Issue by mouri11** [containers/podman#7307]
**BUG REPORT**

/kind bug

**Description**

Unable to install podman by following instructions on the podman.io site.

**Steps to reproduce the issue:**

Steps mentioned [here](https://podman.io/getting-started/installation.html).

**Describe the results you received:**

```
$ sudo apt-get install podman
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package podman

```

**Describe the results you expected:**

Podman installed in my system.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown 2.0.4~1 amd64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS Ubuntu 18.04 arm64

**Comment by lsm5** [comment]
See: https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman

For ubuntu 18.04, podman is available only for x86_64. I'd recommend upgrading your ubuntu to 20.04 which has aarch64 package available.

Closing...

**Comment by junaruga** [comment]
Note podman ubuntu package is available on Ubuntu 20.04 groovy.
https://packages.ubuntu.com/groovy/podman

**Comment by vrothberg** [comment]
A small yet important correction and to avoid potential confusion: Groovy is Ubuntu 20.10 (not 20.04).

**Comment by junaruga** [comment]
Thanks for finding my mistake!
