### ISSUE TITLE
Is there any way to override the storage.conf options?

### ISSUE THREAD

**Issue by ziXet** [containers/podman#7309]
I would like to run some podman commands with different options in the storage.conf.

Without this option I need to use "sed" to comment and uncomment specific lines in the storage.conf before and after running my special podman command which is not ideal with multiprocessing.

I'd prefer to run something like this:
`podman image pull --storage storage.options.additionalimagestores=["/storage"]`

Is it possible?

**Comment by giuseppe** [comment]
podman --storage-opt...?  Is that what you would like to use?

**Comment by ziXet** [comment]
> podman --storage-opt...? Is that what you would like to use?

Thanks for the response.
I would like to override the value of additionalimagestores in the storage.conf. I think --storage-opt is for overriding "storage driver options". 

Please correct me if I'm wrong

**Comment by giuseppe** [comment]
I think you are right.  I don't see a way to change the additionalimagestores using `--storage-opt`.

Anyway, I think that allowing a different additionalimagestores per container could cause some issues.  For example how would we find the image referred by the container if the stores can change?  We would need to store the configuration per each container

**Comment by ziXet** [comment]
My use case is a bit special. I would like to pull the images to the additional storage using: 
`podman image pull myimage:v1 --root /storage`
If I run this command while I have `additionalstorage=['/storage']` in my storage.conf, I get this error:
`Error: lock "/storage/overlay-images/images.lock" is not a read-only lock`
To solve this issue, I need to set the `additionalstorage=[]` or comment it out. after pulling a readonly image, I can put the '/storage' back to the additionalstorage.

**Comment by rhatdan** [comment]
I am working on a better fix for this, but this will work.

podman image pull myimage:v1 --storage-opt=overlay2.mountopt=nodev --root /storage

**Comment by ziXet** [comment]
> I am working on a better fix for this, but this will work.
> 
> podman image pull myimage:v1 --storage-opt=overlay.mountopt=nodev --root /storage

Thanks Dan! it actually worked!

**Comment by rhatdan** [comment]
I have a PR for this, just need to get it merged.

**Comment by rhatdan** [comment]
This is now fixed in master branch.
