### ISSUE TITLE
podman run -d: hangs when $NOTIFY_SOCKET is set

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#7316]
```console
# export NOTIFY_SOCKET=/tmp/mypodmansocket
# socat unix-recvfrom:"$NOTIFY_SOCKET",fork system:"(cat;echo)" &
[1] 104770
# podman run -d --sdnotify=container alpine sh -c 'sleep 10'
2020/08/13 16:50:03 socat[104857] E sendto(8, 0x55de50ff26b0, 14, 0, AF=1 "<anon>", 0): Transport endpoint is not connected
95fb97931bbf3c3b773dddff07f9fea80b341293fb39e6d63e3becbd3937099f
2020/08/13 16:50:13 socat[104864] E sendto(8, 0x55de50ff26b0, 14, 0, AF=1 "<anon>", 0): Transport endpoint is not connected
```
Note the ten-second difference in the `socat` timestamps; that is because the container is `sleep 10`. Change it to `sleep 30`, you get a 30-second delay.

What I expected: since this is `run -d` (detached), I expected podman to detach immediately and let the container deal with sdnotify.

(How I found this: trying to run `systemd-notify` in a `fedora:latest` container. Ha ha, silly me, they removed systemd-notify from that image). Ergo, I think this is counterintuitive behavior if a user has a container that never makes it to `sdnotify`. I really don't expect `podman run -d` to hang forever.

**Comment by edsantiago** [comment]
Oooh! Try running `podman ps` or even `podman info` while there's a hung `podman run -d`. It too will hang. (`podman images` is fine).

**Comment by mheon** [comment]
Is this the same issue as https://github.com/containers/podman/issues/6688

**Comment by edsantiago** [comment]
Yes, it looks like a different manifestation of the same problem. I'd say "feel free to close", but given how badly #6688 has been neglected, I'm going to leave it open as a reminder that this really is an unpleasant and unacceptable bug,

**Comment by giuseppe** [comment]
I don't think it is a bug.  `podman run` waits for the container to notify when it is ready.  If the container is never ready what should we do?  It is not even Podman fault at this point, the OCI runtime is handling the NOTIFY_SOCKET

**Comment by edsantiago** [comment]
I'm fine with the container hanging. I'm not fine with `podman ps` or `podman info` or other podman commands hanging.

**Comment by rhatdan** [comment]
Yes, I think we need a way to work around the lock.

**Comment by mheon** [comment]
We have a way forward via https://github.com/containers/conmon/pull/182 if we can get it landed

**Comment by giuseppe** [comment]
> We have a way forward via [containers/conmon#182](https://github.com/containers/conmon/pull/182) if we can get it landed

I am fine with the solution proposed there, but we would still have the locking issue when `--sdnotify=podman` is used though.

**Comment by rhatdan** [comment]
Looks like https://github.com/containers/conmon/pull/182 is ready to go in, but was not looked at for 20 days.

**Comment by rhatdan** [comment]
I am continuing to try to get this to pass CI in https://github.com/containers/podman/pull/8508

**Comment by edsantiago** [comment]
Issue still present, fc02d16e728dfdd5a5f2e3bc622bbceb7f8c0d24

**Comment by edsantiago** [comment]
Still present in 3bdbe3ce969ac510b8d4ee44da4578da9fed659c

**Comment by vrothberg** [comment]
IMHO, the only way to prevent hanging is to change the default of `--sdnotify` from "container" to "ignore";  `runc` is blocking until it receives the READY message from the container.

**Comment by vrothberg** [comment]
Or well, once https://github.com/containers/podman/pull/11246 is merged.

**Comment by edsantiago** [comment]
Confirmed: I no longer see this bug when I apply #11246.
