### ISSUE TITLE
--rootfs should be a string option, not a switch

### ISSUE THREAD

**Issue by stephen-dexda** [containers/podman#7324]
Currently --rootfs is a boolean option that determines the meaning of the first (non-option) argument: "If specified, the first argument refers to an exploded container on the file system."

This is needlessly confusing behaviour. It should just be a string option (i.e. value immediately following the option).

Example syntaxes:

a) `podman run ... --rootfs <root-fs-dir> <cmd>`
b) `podman run ... --rootfs <other-opt> <root-fs-dir> <cmd>`
c) `podman run ... --rootfs <root-fs-dir> <other-opt> <cmd>`
d) `podman run ... --rootfs=<root-fs-dir> ... <cmd>`

Currently:

* a) works, but `--rootfs` looks like a string option when it isn't.
* b) works, but is confusing (have to look back through the options to see that the first non-option arg. means the root FS dir. instead of the command).
* c) doesn't work, but looks like it should.
* d) doesn't work, but looks like it should.

With `--rootfs` changed to be a string option:

* a) would work, and now `--rootfs` is the string option it looks like.
* b) wouldn't work. But probably an unlikely construction.
* c) would work.
* d) would work.

**Output of `podman version`:**

```
podman version 2.0.4
```

**Comment by mheon** [comment]
I'm very reluctant to do this as it would be a breaking change to our CLI -
commands using your second example are presently perfectly valid and almost
certainly in use, and we'd break anyone using them.

**Comment by stephen-dexda** [comment]
Understood. It could either be introduced under a different option name, changed as part of the next major version, or some combination of both.

**Comment by giuseppe** [comment]
I think we should not change how it works.  It is implemented as a boolean option because when `--rootfs` is used, the image argument makes no sense.  With "c)" it is not clear whether the next argument is the rootfs or another argument.
