### ISSUE TITLE
podman stats - not showing anything

### ISSUE THREAD

**Issue by pocelka** [containers/podman#7325]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I have two containers running, but when executing (sudo) podman stats it is not showing any statistics at all.

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/20441822/90267610-1a6b1300-de56-11ea-8396-c54d70454ee9.png)

![image](https://user-images.githubusercontent.com/20441822/90267692-37074b00-de56-11ea-8d56-7ff8cb604e73.png)

**Describe the results you expected:**

I would expect to see statistics about CPU and memory usage.

**Additional information you deem important (e.g. issue happens only occasionally):**

n/a 

**Output of `podman version`:**

```
Version:      2.0.2
API Version:  1
Go Version:   go1.14.4
Git Commit:   201c9505b88f451ca877d29a73ed0f1836bb96c7
Built:        Sun Jul 12 22:46:58 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.18, commit: 7b3e303be8f1aea7e0d4a784c8e64a75c14756a4'
  cpus: 8
  distribution:
    distribution: manjaro
    version: unknown
  eventLogger: file
  hostname: manjaro
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65536
  kernel: 5.4.52-1-MANJARO
  linkmode: dynamic
  memFree: 25098330112
  memTotal: 33640067072
  ociRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc91
      commit: 24a3cf88a7ae5f4995f6750654c0e2ca61ef4bb2
      spec: 1.0.2-dev
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 9448923136
  swapTotal: 9448923136
  uptime: 1h 59m 17.99s (Approximately 0.04 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /home/pocelka/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: Unknown
      Version: |-
        fusermount3 version: 3.9.2
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.2
        using FUSE kernel interface version 7.31
  graphRoot: /home/pocelka/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/user/1000/containers
  volumePath: /home/pocelka/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1594586818
  BuiltTime: Sun Jul 12 22:46:58 2020
  GitCommit: 201c9505b88f451ca877d29a73ed0f1836bb96c7
  GoVersion: go1.14.4
  OsArch: linux/amd64
  Version: 2.0.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

n/a

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical environment.

**Comment by danopia** [comment]
It looks like your containers are running rootless (no sudo). Have you tried running `podman stats` without sudo as well?

`sudo podman stats` would show containers that were run with `sudo podman`

**Comment by mheon** [comment]
I believe that we expect 'podman stats' to not work as rootless on cgroups
v1 sirens (it requires cgroups to identify what processes are in the
container and their resource usage, AFAIK - but it's been a while since I
was in that part of the code). Suspicion: the part of the code that should
have detected an unsupported configuration for stats and errored was
accidentally dropped in the migration to v2.0.

**Comment by Luap99** [comment]
@mheon I still get the error `Error: stats is not supported in rootless mode without cgroups v2` in podman v2 with cgroup v1.

**Comment by pocelka** [comment]
@mheon: It's exactly as @Luap99 wrote: `Error: stats is not supported in rootless mode without cgroups v2`. However I would expect that with sudo (since it has bigger privileges) it would display those stats even if containers are running without sudo.

**Comment by Luap99** [comment]
`sudo podman` only knows about containers created by root, so it cannot show you the stats for rootless containers. If you want to see stats on rootless with cgroups v1 you can use regular `top` or `htop` to see the resources of all processes including the ones in your containers.

Or you migrate to cgroups v2 but this requires to recreate all containers AFAIK.

**Comment by pocelka** [comment]
I have tried to use cgroups v2 but since I'm kind of Linux newbie and I got many strange errors I just recreated all containers with sudo.

Thanks for help guys!
