### ISSUE TITLE
man page for podman-generate-systemd

### ISSUE THREAD

**Issue by barnscott** [containers/podman#7331]
Man page for podman-generate-systemd references putting unit file in /usr/lib/systemd for a rootful container, however, this isnt available in silverblue/rpm-ostree system.

i used the /etc directory instead, so i have two takeaways:

1) is using etc the best alternative solution
2) if so, should man page be updated?

**Comment by Luap99** [comment]
Yes `/etc/systemd/system` is the best option. The man page is already updated on master #7181.
