### ISSUE TITLE
Podman 2.0 fails to create container with hostname complaining about host UTS namespace

### ISSUE THREAD

**Issue by ericzolf** [containers/podman#7332]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Since the upgrade to 2.0.0.rc7 on CentOS 8 Stream, containers can't be created anymore which used to be created.

**Steps to reproduce the issue:**

1. "podman", "container", "run", "--name", "nginx-cnt", "--hostname", "nginx-host", "--pod", "ncpod", "--volume", "nextcloud-vol:/var/www/html:z,ro", "--volume", "/var/lib/containers/sources/nginx.conf:/etc/nginx/nginx.conf:Z,ro", "--env", "VIRTUAL_HOST=fantasio.lavarde.eu", "--env", "LETSENCRYPT_HOST=fantasio.lavarde.eu", "--env", "LETSENCRYPT_EMAIL=le@mymail.com", "--network", "proxy-nw,podman", "--detach", "nginx:stable-alpine"

**Describe the results you received:**

return code 125 and error message: "Error: invalid config provided: cannot set hostname when running in the host UTS namespace: invalid configuration"

**Describe the results you expected:**

With 1.6.4 the container would be created.

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue always happen, already for 2 containers (I don't dare destroy more).

**Output of `podman version`:**

```
podman version 2.0.0-rc7
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.18-1.module_el8.3.0+432+2e9cbcd8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.18, commit: 4d7da6016270217928f56161842ad4367c88dbb6'
  cpus: 4
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: pe140centos.home
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-211.el8.x86_64
  linkmode: dynamic
  memFree: 13651775488
  memTotal: 16442118144
  ociRuntime:
    name: runc
    package: runc-1.0.0-66.rc10.module_el8.3.0+401+88d810c7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 25186791424
  swapTotal: 25186791424
  uptime: 6h 8m 50.73s (Approximately 0.25 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 3
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 7
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.13.4
  OsArch: linux/amd64
  Version: 2.0.0-rc7
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.0-0.9.rc7.module_el8.3.0+432+2e9cbcd8.x86_64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical server, entirely setup with kickstart and ansible, available from https://gitlab.com/EricPublic/miscericlaneous/-/blob/master/automate/redfish_ipmi/misc/ks_centos8stream.cfg and https://gitlab.com/EricPublic/miscericlaneous/-/blob/ericzolf-own-nginx-proxy/nextcloud_container/setup_nextcloud_container.yml

**Comment by mheon** [comment]
The error message here is clearly not correct, but the fact that it is giving an error is correct. Using `--hostname` with a pod that shares the UTS namespace (as it does by default) is not supported, and the fact that it worked before is a bug. You can set the hostname for the entire pod, but individual containers inside a pod must use the pod's hostname.

**Comment by mheon** [comment]
I think this should be left open to fix the error message, though, that's rather egregious.

**Comment by Luap99** [comment]
@ericzolf If you still want to use different hostnames for your containers inside the pod you can create the pod like this: `podman pod create --name test --share net,cgroup,ipc`. With that option the UTS namespace will not get shared in the pod and thus you can set a hostname for the container.

**Comment by mheon** [comment]
You should be able to force a private UTS namespace for just one container with `--uts=private` that would allow you to set a hostname for a container within a pod (at the cost of losing a shared `/dev/shm` and other shared IPC constructs).

**Comment by ericzolf** [comment]
Thanks to everybody, now I have many options and can't decide which one to use.

Just joking but it's truly difficult to understand what the actual impact is of the choices. @mheon isn't IPC another namespace than UTS, if I refer to https://lwn.net/Articles/531114/ ? Does the hostname only impact what hostname, uname & Co returns, or also the inter-container dynamic DNS managed by podman (that was at least the case with docker IIRC)?

And, yes, I agree that the error message could be improved. From what I understood so far, I would suggest something like: `the hostname of a container can't be set when sharing the UTS namespace with a pod. Check options --uts for the container or --share for the pod creation.`

Looking through the man pages, I also see that the description for `--uts` isn't correct:

1. `private` is obviously _not_ the default when the container is created within a pod (is it then `host`, the "host" being the pod? Is it also insecure somehow?)
2. for `ns` it's not clear what an "own" namespace makes a difference to a private one.
3. a note that the uts mode `host` (and/or whichever mode is used within a pod) keeps one from using the --hostname option could be helpful.

**Comment by Luap99** [comment]
1. you will join the pods UTS namespace so it will be a private namespace which is shared between all containers inside the pod.
2. ns expects a path to an existing UTS namespace which the container than joins

I opened #7352 to update the docs and error message.
