### ISSUE TITLE
CI: gpg2: not found in $PATH

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#7347]
One of those "Action recommended" IRC messages. Starting point link is https://cirrus-ci.com/build/5933219147153408

Two of those failures are the horrible nasty Monday 2020-08-17 timeout, but one looks like a different problem: [test ubuntu-20](https://cirrus-ci.com/task/5322509090291712) ([highlighted log](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5322509090291712/html/integration_test.log.html#t--podman-image-trust-show--1)):
```
  podman image trust show
 ...
Running: podman [options] image trust show --registrypath /var/tmp/go/src/github.com/containers/podman/test --policypath /var/tmp/go/src/github.com/containers/podman/test/policy.json
         time="2020-08-17T19:43:46Z" level=error msg="error getting key identity: exec: \"gpg2\": executable file not found in $PATH"
```
I imagine this should be very easy for @cevich to figure out. Probably some sort of difference between the VMs used in testing master vs those used in testing PRs.

**Comment by cevich** [comment]
Good catch @edsantiago among all the other chaos.  That's a really odd error, IIRC we install gnupg everywhere.  Thanks for opening this, I'll investigate...
