### ISSUE TITLE
`podman version` shows 1970-01-01 as the built date

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/podman#7359]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`podman version` shows 1970-01-01 as the built date

**Steps to reproduce the issue:**

```console
$ git rev-parse HEAD
748e8829da76394ec956ea6590599fab01b467b7
$ make
$ ./bin/podman version
Version:      2.1.0-dev
API Version:  1
Go Version:   go1.15
Built:        Thu Jan  1 09:00:00 1970
OS/Arch:      linux/amd64
```

**Describe the results you received:**

`Built:        Thu Jan  1 09:00:00 1970`

**Describe the results you expected:**

Should be the actual date

**Output of `podman version`:**

```
Version:      2.1.0-dev
API Version:  1
Go Version:   go1.15
Built:        Thu Jan  1 09:00:00 1970
OS/Arch:      linux/amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Comment by mheon** [comment]
This is also present on the v2.0.4 build we're shipping in the official Fedora RPMs, which is concerning

**Comment by Luap99** [comment]
#7361 to fix this
