### ISSUE TITLE
support container-to-container copy

### ISSUE THREAD

**Issue by daiaji** [containers/podman#7370]
```
podman cp v2ray:/etc/ssl/certs/ca-certificates.crt caddy:/etc/ssl/certs/ca-certificates.crt
Error: invalid arguments v2ray:/etc/ssl/certs/ca-certificates.crt, caddy:/etc/ssl/certs/ca-certificates.crt you must use just one container
```
There seems to be no harm in implementing this function.

**Comment by zhangguanzhang** [comment]
which version did you used to? or , did you tried with the latest version?

**Comment by mheon** [comment]
Should be technically possible. I'll label this as a feature request.

**Comment by rhatdan** [comment]
@vrothberg Is working on podman-remote cp now, so maybe he can look at this?

**Comment by vrothberg** [comment]
> @vrothberg Is working on podman-remote cp now, so maybe he can look at this?

Good timing. I am currently rewiring the entire copy code. I will keep this in mind so that we can easily add support for container-to-container copy.

**Comment by rhatdan** [comment]
@vrothberg Did you make this work?

**Comment by vrothberg** [comment]
> @vrothberg Did you make this work?

No.  I focused on host/ctr copying only.  The backend code, however, would allow that now, so that (nearly) all code changes would happen `cmd/podman`.

**Comment by rhatdan** [comment]
Since this is a feature, we can put it off for a while until we stabilize 3.0

**Comment by rhatdan** [comment]
This  would still be a good feature.  I was recently asked about this in buildah copy as well, but in that case they wanted to copy from an image to a container.

**Comment by vrothberg** [comment]
Agreed, it would be really nice to get this done.  I have too many things on my plate at the moment but I'd be more than happy to help others get it done.  A word of caution: I do not think it's a good first issue. It will require _very_ extensive testing.

**Comment by infiniteregrets** [comment]
hey @vrothberg, are you working on this? If not then, can I try working on it

**Comment by vrothberg** [comment]
> hey @vrothberg, are you working on this? If not then, can I try working on it

Thanks, it's yours :)

As mentioned above.  This feature will need extensive testing in https://github.com/containers/podman/blob/master/test/system/065-cp.bats but we can assist.  Code wise, the plumbing would happen `cmd/podman/containers/cp.go`.

**Comment by infiniteregrets** [comment]
I will try to work on it as soon as possible. I will ping you if I am stuck! Thank you

**Comment by rhatdan** [comment]
@infiniteregrets @vrothberg Did this ever move forward?

**Comment by infiniteregrets** [comment]
I did move it forward, but I couldnt figure out how to rename a file which does not exist in the destination when copied, so @vrothberg will take over. sorry ):

**Comment by vrothberg** [comment]
I plan to tackle it this week :+1:
