### ISSUE TITLE
podman save --format oci-archive: loses image ID

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#7371]
This may not be a bug, but I think it is, because `podman save` without `--format oci-archive` preserves image ID.
```console
$ cat >oci-check.sh <<EOF
#!/bin/bash

image=${1?Usage: $0 FQIN}

OCI_FORMAT="--format oci-archive"

./bin/podman rm  -a >/dev/null
./bin/podman rmi -a >/dev/null
./bin/podman pull -q "$image" >/dev/null
./bin/podman images --noheading
rm -f /tmp/foo.tar
./bin/podman save $OCI_FORMAT -o /tmp/foo.tar "$image"
./bin/podman rmi -a >/dev/null
./bin/podman load -q -i /tmp/foo.tar   >/dev/null
./bin/podman images --noheading
EOF
$ chmod 755 ./oci-check.sh

!! basically just "podman pull", "podman save", and "podman load". Note differing image IDs.
$ for i in docker.io/library/busybox docker.io/library/alpine:latest quay.io/libpod/alpine_labels:latest;do ./oci-check.sh $i;echo;done
docker.io/library/busybox  latest  018c9d7b792b  3 weeks ago  1.45 MB
docker.io/library/busybox  latest  c71b90eb5b17  3 weeks ago  1.44 MB

docker.io/library/alpine  latest  a24bb4013296  2 months ago  5.85 MB
docker.io/library/alpine  latest  0f5f445df8cc  2 months ago  5.85 MB

quay.io/libpod/alpine_labels  latest  4fab981df737  21 months ago  4.69 MB
quay.io/libpod/alpine_labels  latest  dd8b0a90b986  21 months ago  4.68 MB

```
Commenting out `OCI_FORMAT=` makes all the IIDs agree.

master @ 7e2a1b34c

**Comment by vrothberg** [comment]
@mtrmac, do you think it's a bug or feature request/enhancement?

**Comment by mtrmac** [comment]
In general, neither. The change ultimately happens in https://github.com/containers/image/blob/1c313b2d23e039a81a64bbced1b2b427d60429e1/image/docker_schema2.go#L78 , and as the comment says, the conversion from v2s2 to OCI is lossy (IIRC OCI does not have health checks).

So, workflows that convert from v2s2 to OCI should be prepared for the config digest == image ID changing. (If the missing fields are the only difference between the formats, we _could_ check that nothing of substance has changed when doing the conversion, and in that case use the original raw bytes to preserve the ID. I don’t think that’s desirable: it’s extra code to preserve an illusion of a property that does not hold in general.)

**Comment by rhatdan** [comment]
@edsantiago Does this answer your question?

**Comment by edsantiago** [comment]
Yes, it does. Thanks @mtrmac.

**Comment by vrothberg** [comment]
I entirely oversaw the conversion, thanks for clarifying @mtrmac!
