### ISSUE TITLE
Error message needed when creating container in pod with -p option

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman#7373]
Pulling this from a discussion by @Luap99 in #7364

IMO, we have to error on the podman create command. I've seen some people run into it and not realize the error.

This should not work:
```
$ podman pod create --name t1
$ podman create --pod t1 -p 8080:80 nginx
```
The create command should note the -p option when being used in a pod and at the very least issue a warning if not an error and disallow it totally.

**Comment by Luap99** [comment]
Closing since this got already fixed by #7390
