### ISSUE TITLE
Podman create command unable to distinguish between pods and containers using the same name

### ISSUE THREAD

**Issue by Pit95** [containers/podman#7377]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Creating a pod or a container with `--name` directive and a name already used, podman doesn't distinguish between pods and containers with the same name.

**Steps to reproduce the issue:**
Case A

1. Create a pod with `podman pod create --name test`

2. Create a container with `podman container run --name test some_image`

OR

Case B

1. Create a container with `podman container run --name test some_image`

2. Create a pod with `podman pod create --name test`

**Describe the results you received:**
Case A: `Error: name test is in use: container already exists`
Case B: `Error: error adding pod to state: name test is in use: pod already exists`

**Describe the results you expected:**
Case A: `Error: name test is in use: pod already exists with the same name`
Case B: `Error: error adding pod to state: name test is in use: container already exists with the same name`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
2.0.4
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 2
  distribution:
    distribution: ubuntu
    version: "18.04"
  eventLogger: file
  hostname: server
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 4.15.0-112-generic
  linkmode: dynamic
  memFree: 325439488
  memTotal: 4045078528
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 0.4.3
      commit: unknown
  swapFree: 4043554816
  swapTotal: 4044353536
  uptime: 273h 13m 3.85s (Approximately 11.38 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/giulio/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/giulio/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 4
  runRoot: /run/user/1000/containers
  volumePath: /home/giulio/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.14.4
  OsArch: linux/amd64
  Version: 2.0.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Result of apt list podman
podman/unknown,now 2.0.4~1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 18.04.5 LTS

**Comment by mheon** [comment]
This was a deliberate design decision when we originally wrote Podman - container and pod names were required to be globally unique, so a `podman inspect $NAME` (for example) could be guaranteed to return a unique result.

This hasn't necessarily turned out to be the best idea (`podman play kube` for example, runs into issues because Kubernetes allows identically-named pods and containers). However, at this point, the assumption is baked very deep into the code, and it would be extremely difficult to remove.

**Comment by mheon** [comment]
I'm going to remove the bug label and retag this as an enhancement request as such. This is not a bug, it was intended behaviour, just behaviour we no longer particularly want.

**Comment by Pit95** [comment]
> I'm going to remove the bug label and retag this as an enhancement request as such. This is not a bug, it was intended behaviour, just behaviour we no longer particularly want.

Thanks

**Comment by rhatdan** [comment]
@mheon Is there any issue with removing the constraing other then podman inspect?  Which I believe should not work for pods, we should require podman pod inspect.

I know Docker merges them altogether, but I am not a big fan of unexpected results.

**Comment by rhatdan** [comment]
Podman 3.0 seems correct.

**Comment by rhatdan** [comment]
@baude @mheon Are we going to be able to get this in podman 3.0 or have we missed the boat?

**Comment by mheon** [comment]
Completely missed the boat - this is going to be a giant change when we decide to make it.

**Comment by rhatdan** [comment]
Ok, I would guess if it is a big change it is not worth it.

**Comment by rhatdan** [comment]
Since this is such a huge change, and I feel hardly worth it, I am going to close as won't fix.
