### ISSUE TITLE
CI flake: healthcheck command exceeded timeout of 3s

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#7378]
Seeing this one a lot lately, not just in PR testing but also in [post-merge testing](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6006585321324544/html/integration_test.log.html#t--podman-healthcheck-that-should-fail--1)

Podman healthcheck run [It] podman healthcheck that should fail
* ubuntu-19 : test ubuntu-19
  * PR #7238
    * [08-10 09:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5251489859895296/html/integration_test.log.html#t--podman-healthcheck-that-should-fail--1)
    * [08-10 09:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5251489859895296/html/integration_test.log.html#t--podman-healthcheck-that-should-fail--2)
    * [08-10 09:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5251489859895296/html/integration_test.log.html#t--podman-healthcheck-that-should-fail--3)
  * PR #6684
    * [06-19 07:50](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5798059428806656/html/integration_test.log.html#t--podman-healthcheck-that-should-fail--1)
    * [06-19 07:50](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5798059428806656/html/integration_test.log.html#t--podman-healthcheck-that-should-fail--2)
    * [06-19 07:50](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5798059428806656/html/integration_test.log.html#t--podman-healthcheck-that-should-fail--3)
  * PR #6415
    * [06-11 05:43](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5203506971803648/html/integration_test.log.html#t--podman-healthcheck-that-should-fail--1)
    * [06-11 05:43](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5203506971803648/html/integration_test.log.html#t--podman-healthcheck-that-should-fail--2)
    * [06-11 05:43](https://storage.googleapis.com/cirrus-ci-5385732420009984-fcae48/artifacts/containers/libpod/5203506971803648/html/integration_test.log.html#t--podman-healthcheck-that-should-fail--3)

**Comment by edsantiago** [comment]
@baude, this is the issue I mentioned in IRC just now. No rush, I'm just filing this as a placeholder.

**Comment by edsantiago** [comment]
@baude I thought you had fixed this in the image? Did you forget to tag or push or something? Seeing the same failure [in pr 7437](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5975699540410368/html/integration_test.log.html#t--podman-healthcheck-that-should-fail--1)

**Comment by baude** [comment]
i lengthened the timeout.  that might not have been enough.  ill look and see.

**Comment by edsantiago** [comment]
ISTR you changing it from 3 to 10, but the error log is showing 3:
```
Running: podman [options] healthcheck run hc
Error: healthcheck command exceeded timeout of 3s
```

**Comment by baude** [comment]
@edsantiago it is updated now, lemme know if you see this flake any more

**Comment by vrothberg** [comment]
I am optimistically closing the issue. I haven't seen it flake while browsing through recent PRs.

Please reopen if I am mistaken.
