### ISSUE TITLE
using podman with kubeadm

### ISSUE THREAD

**Issue by jmccormick2001** [containers/podman#7380]
/kind feature

**Description**

is there any documentation on how to run kubeadm using podman?

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

would love to be able to run podman instead of docker when installing kubeadm

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by TomSweeneyRedHat** [comment]
@jmccormick2001 The closest that I found quickly was this post from @baude https://developers.redhat.com/blog/2019/01/29/podman-kubernetes-yaml/

**Comment by rhatdan** [comment]
Podman is not intended to be used as a CRI, CRI-O is the package you are looking for.

**Comment by jmccormick2001** [comment]
ah, thanks Dan!
