### ISSUE TITLE
`podman load ... [name:tag]` inconsistencies

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#7387]
The optional `name:tag` for `podman load` is treated differently among the formats. `docker-archive` will apply it as tag to the loaded image while `oci-archive` seems to try to extract it from the image. Let's try to find a way to untangle the hairy ball and get it consistent (or clearly document the different behaviours).

The man pages need to be more explicit:
> You can also specify a name for the image if the archive does not contain a named reference, of if you want an additional name for the local image.

Background discussion: https://github.com/containers/podman/pull/6811/files#r472198035

**Comment by zhangguanzhang** [comment]
```
podman save --format oci-archive alpine:latest > /tmp/FOO.tar
podman load -i /tmp/FOO.tar domain.com/NewName:tag   
```
after this, the image's name should be `domain.com/NewName:tag`? or just search `domain.com/NewName:tag` in the `/tmp/FOO.tar` and load it

**Comment by vrothberg** [comment]
That really depends what we want to do.

I am also open to change `podman load` to not accept such an optional `name:tag`. If users want to load a specific image, they can use `podman pull` instead. That way, `podman load` would be ~identical to `docker load`.

**Comment by rhatdan** [comment]
I think podman load should be identical to docker load.

**Comment by vrothberg** [comment]
Proposal: let's wait first for Podman v2.1 and then remove the optional arguments and get that into Podman v3.0.

Users can always load+tag or use pull to extract a specific image.

**Comment by vrothberg** [comment]
@mtrmac WDYT?

**Comment by mtrmac** [comment]
Note that this is not just the CLI: changes might affect the two `/images/load` APIs (OTOH at least in Swagger the “reference” parameter seems completely undocumented).

> Users can always load+tag or use pull to extract a specific image.

Right now, the CLI load command prints the IDs(?) of loaded images only in a non-trivially-parseable text format.

---

_Conceptually_, I think it does make sense to offer _both_
- Extract only image $name from archive (as opposed to the `docker load` “overwrite an unpredictable set of images in local storage” behavior, making “load” insecure to use with not-100%-trusted archives)
- Tag the result with $dest-tag

OTOH, considering how broken it’s been (we provide sometimes one, sometimes the other, sometimes a broken version of one or the other, and we don’t document which one it is supposed to be) and how there haven’t been many reports complaining about this, removing the feature and waiting for an actual user motivated to contribute one of those features makes sense.

**Comment by rhatdan** [comment]
@vrothberg What is going on with this issue?

**Comment by vrothberg** [comment]
> @vrothberg What is going on with this issue?

> Proposal: let's wait first for Podman v2.1 and then remove the optional arguments and get that into Podman v3.0.

^ no breaking changes at this point :)

**Comment by baude** [comment]
shall we merge?

**Comment by rhatdan** [comment]
We need a PR to merge.  But yes we should fix this problem.

**Comment by Aryanrt** [comment]
Currently I am trying to build an image using buildkit and use podman load to save the built image.
However, currently the name of the built image is "localhost/latest:latest".
How can I specify the name of the loaded image?
Thank you in advance

**Comment by rhatdan** [comment]
podman tag localhost/latest NAME.

**Comment by vrothberg** [comment]
@Aryanrt, which version of Podman do you use?  I think it's best to open a new issue but note that recent versions of Podman _should_ support it.

**Comment by Aryanrt** [comment]
> podman tag localhost/latest NAME.
This works. Thanks!

**Comment by vl-shopback** [comment]
podman 3.4.4 also same issue

**Comment by vrothberg** [comment]
Please open a new issue with a reproducer. Otherwise, it's impossible to track.
