### ISSUE TITLE
Starting a stopped pod does not bind published ports

### ISSUE THREAD

**Issue by TrevorBenson** [containers/podman#7397]
**Steps to reproduce the issue:**

1. Build a pod with a published port: `podman pod create --name test-ports-pod --publish 12345:12345`

2. Start the pod: `podman pod start test-ports-pod`

3. Check the port is bound: `netstat -plven | grep 12345`

4. Stop the pod: `podman pod stop test-ports-pod`

5. Check the port is missing: `netstat -plven | grep 12345`

6. Start the pod: `podman pod start test-ports-pod`

7. Check the port is still missing: `netstat -plven | grep 12345`

8. Fix the port by restarting the running pod: `podman pod restart test-ports-pod`

9. Check the port is bound again: `netstat -plven | grep 12345`

**Describe the results you received:**

When stopping a pod with published ports and starting it again, the published port is never bound on the host. Restarting a running pod does not remove a published port from the host and will restore the published port if it is unbound. 

**Describe the results you expected:**

Stopping and starting a pod removes and consistently recreates the published port binding.

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue occurs every time a stopped pod is started. Every time the pod is running and the port is not bound a restart restores the published port. 

**Output of `podman version`:**

```
Version:      2.0.4
API Version:  1
Go Version:   go1.14.6
Built:        Wed Dec 31 16:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.19-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.19, commit: 5dce9767526ed27f177a8fa3f281889ad509fea7'
  cpus: 16
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: mymachine
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.7.15-200.fc32.x86_64
  linkmode: dynamic
  memFree: 9473900544
  memTotal: 16750624768
  ociRuntime:
    name: crun
    package: crun-0.14.1-1.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.14.1
      commit: 598ea5e192ca12d4f6378217d3ab1415efeddefa
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 2
  swapFree: 8443129856
  swapTotal: 8443129856
  uptime: 1h 30m 27.07s (Approximately 0.04 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 1
    stopped: 3
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/user/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 23
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Wed Dec 31 16:00:00 1969
  GitCommit: ""
  GoVersion: go1.14.6
  OsArch: linux/amd64
  Version: 2.0.4
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.4-1.fc32.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical host running Fedora32

**Comment by vrothberg** [comment]
Closing as it's now fixed.

**Comment by duckie** [comment]
This is weird, #7103 made its way to 2.1.1, yet I still observe this exact bug, consistently.
