### ISSUE TITLE
podman build -q does not quiet image pull log

### ISSUE THREAD

**Issue by ashley-cui** [containers/podman#7401]
/kind bug

podman build -q still shows parts of the build log

**Steps to reproduce the issue:**

1. podman build -q ~/tst

2. look at output 

**Describe the results you received:**

$ ./bin/podman build --quiet ~/tst 
Getting image source signatures
Copying blob df20fa9351a1 done  
Copying config a24bb40132 done  
Writing manifest to image destination
Storing signatures
6b857695d6b6c962e94c88b01b4f8e36bcf147b3fab091add219cb7e935c39c6

**Describe the results you expected:**
$ ./bin/podman build --quiet ~/tst 
6b857695d6b6c962e94c88b01b4f8e36bcf147b3fab091add219cb7e935c39c6

**Additional information you deem important (e.g. issue happens only occasionally):**
Output comes from containers/image
This works properly in buildah

**Output of `podman version`:**

```
podman version 2.1.0-dev
```

**Comment by TomSweeneyRedHat** [comment]
@ashley-cui can you include the BZ that this is fixing either in the description or as a reply please?

**Comment by ashley-cui** [comment]
@TomSweeneyRedHat uhh I dont think this is a Bugzilla, this is a podman bug that I found while working on the --log-basic BZ

**Comment by TomSweeneyRedHat** [comment]
OK, I thought this was part of the log-basic fix, nvm.
