### ISSUE TITLE
RFE: Sort the API endpoints alphabetically in the documentation.

### ISSUE THREAD

**Issue by Luap99** [containers/podman#7404]
/kind feature

**Description**

The endpoints inside the RestAPI Documentation at https://docs.podman.io/en/latest/_static/api.html are grouped in categories which is good. But within each category the endpoints seem to be in a random order (see below). It would be nice if they were sorted alphabetically.

![image](https://user-images.githubusercontent.com/45212748/90923667-5c63fe00-e3ee-11ea-9573-95a5f18316b8.png)

**Comment by rhatdan** [comment]
SGTM. Could one of you open a PR to fix this.

**Comment by Luap99** [comment]
I have looked at the swagger documentation but didn't found a way to achieve the desired result. Maybe someone else finds/knows a way to do this.

**Comment by rhatdan** [comment]
@baude @jwhonce Any ideas?

**Comment by vrothberg** [comment]
https://stackoverflow.com/questions/24951268/sort-api-methods-in-swagger-ui looks promising.

**Comment by vrothberg** [comment]
But I don't know how our docs are wired. @baude, in case you tackle it, I'd like to watch over your shoulders so I know what to tweak where.

**Comment by jwhonce** [comment]
@TomSweeneyRedHat @baude 

From a quick read:
 - it appears we need to set properties on the redoc script. Manipulation of the yaml does not change the presentation order
 - we currently retrieve the redoc script on-demand from html

To fix:
 - We need to either set properties when running redoc script
 - Or, build json application combining redoc with properties and our swagger. Application provides most control on future changes and locks us into a version of redoc.
 - Either way, we need to update operationId's in the swagger:operation comments to maintain desired sort order, examples that would work:
   - createNetworkCompat
   - createNetworkLibpod
   - <verb><object><differentiator>

**Comment by TomSweeneyRedHat** [comment]
@jwhonce it doesn't get published to podman.io, it gets published to readthedocs via some make magic that @baude put together.  We then do a redirect of docs.podman.io to readthedocs.  Also readthedocs has some settngs you can select to make that look seamless.

eithe suggestion sounds at least slightly painful, I'll let @baude flip the coin.

**Comment by rhatdan** [comment]
@Luap99 @TomSweeneyRedHat @baude @jwhonce Anyone have a chance to look at this?

**Comment by TomSweeneyRedHat** [comment]
Think we need a decision first from @baude and/or @umohnani8 about which direction to go as requested in @jwhonce 's comment a few back.

**Comment by baude** [comment]
we need @jwhonce on this one ... i have no clue here.

**Comment by rhatdan** [comment]
@Luap99 @jwhonce Any progress on figuring out what is going on here?

**Comment by rhatdan** [comment]
From my naive reading of this issue, it seems like an easy fix, is there a reason that this has not been solved other then people busy on other projects?

@Luap99 @baude @jwhonce ???

**Comment by vrothberg** [comment]
friendly ping

**Comment by rhatdan** [comment]
This seems to be a never ending Issue, with noone coming up with good ideas.
@TomSweeneyRedHat Any chance you could look at this?
@flouthoc Any ideas?

**Comment by flouthoc** [comment]
`Redoc` maintains the order which is specified in spec `swagger.yaml` and `go-swagger` maintains the order in which our code is commented.

Solution 1. 
We could reorder our code but this is non-scalable approach and hard to maintain.

Solution 2.
Patch `go-swagger` to sort swagger according to `summary`. Again this would be wrong since not all documenting solution use `summary` as title.

Solution 3.
Fix at `redoc` level since only redoc is responsible how `operations` are rendered.  `Redoc` documents this new feature but it was never implemented `sortOperationsAlphabetically`: https://redoc.ly/docs/api-reference-docs/guides/migration-guide-2-0/#automated-sorting

I think solution 3 is the best.
Here is the PR for upstream: https://github.com/Redocly/redoc/pull/1843
PR for downstream:

**Comment by flouthoc** [comment]
Screenshot of fix:

![swagger-fix](https://user-images.githubusercontent.com/9384699/147447989-ffb2f905-00c3-4d83-a004-512a8935b336.png)

**Comment by rhatdan** [comment]
Great job @flouthoc
