### ISSUE TITLE
podman v2*.* images on quay.io are failing

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman#7413]
I'm running this command using podman v2.0.2:

```
# podman run quay.io/podman/stable:latest podman version
Error: mount /var/lib/containers/storage/overlay:/var/lib/containers/storage/overlay, flags: 0x1000: operation not permitted
```
If I do the same command with images prior to v2.*, I see success.

```
# podman run quay.io/containers/podman:v1.9.1 podman version
Version:            1.9.1
RemoteAPI Version:  1
Go Version:         go1.14.2
OS/Arch:            linux/amd64
```

Did something change with overlayfs as of v2.0 that we need to adjust within the Containerfiles that build the images on quay.io?  FWIW, the images for Skopeo and Buildah are both fine.

**Comment by vrothberg** [comment]
@rhatdan @giuseppe any ideas? It seems we're either missing or requiring a capability (it works with `--cap-add=all`).

**Comment by rhatdan** [comment]
The issue is the podman image is not defaulting to run as the podman user.  Plus you need to use --device /dev/fuse
```
# podman run --user podman --device /dev/fuse quay.io/podman/stable:latest podman version
Version:      2.0.5
API Version:  1
Go Version:   go1.14.6
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```
I am not sure how much of this actually works.  We have never gotten the time to fully test it.

**Comment by rhatdan** [comment]
It would be nice if we had a way to report an error to the user, like this image requires /dev/fuse to work correctly.
perhaps have an OCI hook that checks if the device exists and then prints out an error that the user could use.

**Comment by vrothberg** [comment]
Great idea!

**Comment by rhatdan** [comment]
This reminds me of something atomic command used to have.  The help command. That would read and display a help message from the container image, on how to use it.

podman image help quay.io/podman/stable:latest

Would display help on use cases for this image.

**Comment by vrothberg** [comment]
Maybe we should add a runlabel to the image as well, so users can just `podman runlabel quay.io/podman/stable`?

**Comment by rhatdan** [comment]
Sure, except I am not sure of the default way that users want to use this image.  
Do they want to run it rootless mode?  
Do they want to just play with the latest version of Podman?

**Comment by TomSweeneyRedHat** [comment]
Did you all make any changes to Podman for this?  I just reset my sandbox to upstream, compiled and install Podman and now it's able to run the podman images.....  But I don't see any changes to the Dockerfiles that run it...  Maybe something else or maybe my system had a bad bit in Podman?
