### ISSUE TITLE
Support podman build --pod in order to image building join pod's network

### ISSUE THREAD

**Issue by awerlang** [containers/podman#7420]
/kind feature

**Description**

I wish rootless `podman build` could join another pod's network. My use case is for speeding up builds with a transparent http proxy.

**Steps to reproduce the issue:**

1. podman run --rm -d --pod new:builder --name local_proxy http-proxy

2. docker build --pod builder ...

**Describe the results you received:**

Rootless podman cannot use a `--network` flag to specify an existing network, and it cannot join a CNI network.

**Describe the results you expected:**

Be able to use the --pod flag.

**Additional information you deem important (e.g. issue happens only occasionally):**

For rootfull podman, a better way to accomplish this is with an overlay mount. If overlay mounts cannot be achieved when going rootless, then this is a reasonable alternative.

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.4-2.1.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical.

**Comment by rhatdan** [comment]
Overlay mounts should be used in rootful and rootless mode.

**Comment by rhatdan** [comment]
@mheon PTAL

**Comment by mheon** [comment]
If `buildah bud` supports `--net ns:` we can mock this under the hood by passing the path to the infra container's network namespace.

**Comment by awerlang** [comment]
> Overlay mounts should be used in rootful and rootless mode.

It's supported in rootless buildah.

**Comment by rhatdan** [comment]
@mheon Buildah bud 1.6 supports --net ns:

**Comment by rhatdan** [comment]
@awerlang Is this still something you are interested in?

@mheon  Do you think this is something we should do?

**Comment by awerlang** [comment]
> @awerlang Is this still something you are interested in?

I was able to use overlay mounts with rootless buildah to accomplish the same thing. So atm I don't have a use case for this.

**Comment by mheon** [comment]
This could be a bit annoying to add (is not hard but could be a fair bit of
extra code) so I vote no unless someone has a solid use case.
