### ISSUE TITLE
Podman push fails : Error copying image to the remote destination: Error writing blob

### ISSUE THREAD

**Issue by pratham-m** [containers/podman#7424]
**Description**
Podman push fails for an image pulled from local registry and then re-tagged and pushed to image registry of OCP cluster.

**Steps to reproduce the issue:**
1. Setup local registry
2. Update /etc/containers/registries.conf to include insecure image registry
3. Build any image and push it to local registry
4. Pull the image from local registry
5. Tag the image with some different name (optional)
6. Login to OCP cluster as kubeadmin and get default-route for cluster host
7. Login to podman as kubeadm 
8. Tag the image with default-route or OCP cluster
9. Push the image to image registry of OCP cluster
REFER attached file for detailed steps.
[steps-to-reproduce.txt](https://github.com/containers/podman/files/5117607/steps-to-reproduce.txt)
[podman-push-log.txt](https://github.com/containers/podman/files/5117610/podman-push-log.txt)

**Describe the results you received:**
Push to image-registry of cluster failed with error below.
`Error: Error copying image to the remote destination: Error writing blob: Error initiating layer upload to /v2/local-images/kn-operator/blobs/uploads/ in default-route-openshift-image-registry.apps.shivani1-95de.ibm.com: received unexpected HTTP status: 500 Internal Server Error`

**Describe the results you expected:**
Podman push should be successful.

**Additional information you deem important (e.g. issue happens only occasionally):**
Tried above steps with `docker.io/library/hello-world` image. Push failed with same error.

**Output of `podman version`:**
```
$ podman version
Version:            1.9.3
RemoteAPI Version:  1
Go Version:         go1.13.4
OS/Arch:            linux/ppc64le
```

**Output of `podman info --debug`:**
[podman-info.txt](https://github.com/containers/podman/files/5117618/podman-info.txt)

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**
```
podman-1.9.3-2.module+el8.2.1+6867+366c07d6.ppc64le
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**
No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
$ uname -a
Linux shivani1-95de-bastion.ibm.com 4.18.0-193.el8.ppc64le #1 SMP Fri Mar 27 14:40:12 UTC 2020 ppc64le ppc64le ppc64le GNU/Linux
$ oc version
Client Version: 4.5.4
Server Version: 4.5.4
Kubernetes Version: v1.18.3+012b3ec
```

**Comment by pratham-m** [comment]
Debugged the issue and found that the issue was with user permission issue within the OCP cluster, and not related to podman.
Closing the issue.

**Comment by vkesharwal** [comment]
> Debugged the issue and found that the issue was with user permission issue within the OCP cluster, and not related to podman.
> Closing the issue.

Haow did you find that out?

**Comment by pratham-m** [comment]
> Haow did you find that out?

My OCP cluster's image-registry was configured to NFS storage and the mount path didn't have correct permissions. And that was causing podman push to cluster's image-registry fail. Had to use correct permissions while setting up NFS.
