### ISSUE TITLE
[Question] Is there a way to limit the size of the logs?

### ISSUE THREAD

**Issue by yamrzou** [containers/podman#7434]
/kind feature

Is there a way to make sure container logs do not grow indefinitely?
Would it be safe to remove ~/.local/share/containers/storage/overlay-containers/*/userdata/ctr.log while the container is running?

**Comment by mheon** [comment]
There is a maximum log size for containers, in bytes, defined in `containers.conf` - it is defaulted to -1, unlimited. I believe setting that should accomplish what you're looking for?

**Comment by TomSweeneyRedHat** [comment]
If so, this might be a good entry for the troubleshooting guide....

**Comment by yamrzou** [comment]
Thank you, yes that's should accomplish what I'm looking for.

**Comment by rhatdan** [comment]
Labeling this as containers.conf, since I should write this up in the forthcoming blog on containers.conf.

**Comment by Luap99** [comment]
I just want to add that docker uses `--log-opt` for this. https://docs.docker.com/config/containers/logging/json-file/#options
`docker run -it --log-opt max-size=10m --log-opt max-file=3 alpine ash`
This might be worth mentioning.

**Comment by vrothberg** [comment]
@rhatdan, did you add that to the blog? Can we close the issue?

**Comment by rhatdan** [comment]
I have not written any blogs yet.  Too much vacationing.

**Comment by rhatdan** [comment]
I opened this related PR. https://github.com/containers/conmon/issues/211

**Comment by pmoogi-redhat** [comment]
Hello @rhatdan .  For my simulations on log-loss i needed to change limit on log size - so created changes in my repo as https://github.com/containers/podman/compare/master...pmoogi-redhat:supportforlogsizemax. It is found working fine as expected. i did some validation on log files written onto disk. This is my first change to podman repo. Kindly let me know if PR can be submitted here reflecting this change in case you find it useful and if it doesn't hurt other modules which are dependent on this repo.

**Comment by mheon** [comment]
That change looks fine on the whole, feel free to make a PR and we can see about getting it landed.

**Comment by rhatdan** [comment]
Yes @pmoogi-redhat Open a PR.
