### ISSUE TITLE
podman uses wrong pid(?)

### ISSUE THREAD

**Issue by burhan** [containers/podman#7461]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I don't think this is a bug, but maybe it should be? Or am I doing something wrong here? Using `su` to switch user, and podman uses the original user's pid resulting in errors (rootless).

**Steps to reproduce the issue:**

1. Create RHEL 8 vm or machine

2. A normal user is created (pid 1000)

3. ssh into the machine with this normal user

4. Create another user `sudo useradd ...`

5. Set the password `sudo passwd ...`

6. Switch to the user `su another`

7. Execute any podman command

**Describe the results you received:**

Errors, as podman is trying to create directories with wrong pid:

```none
ERRO[0000] cannot mkdir /run/user/1000/libpod: mkdir /run/user/1000/libpod: permission denied 
ERRO[0000] cannot mkdir /run/user/1000/libpod: mkdir /run/user/1000/libpod: permission denied 
ERRO[0000] failed to setup From and Bud flags: failed to get container config: cannot mkdir /run/user/1000/libpod: mkdir /run/user/1000/libpod: permission denied 
ERRO[0000] cannot mkdir /run/user/1000/libpod: mkdir /run/user/1000/libpod: permission denied 
ERRO[0000] cannot mkdir /run/user/1000/libpod: mkdir /run/user/1000/libpod: permission denied 
ERRO[0000] cannot mkdir /run/user/1000/libpod: mkdir /run/user/1000/libpod: permission denied 
ERRO[0000] cannot mkdir /run/user/1000/libpod: mkdir /run/user/1000/libpod: permission denied 
ERRO[0000] cannot mkdir /run/user/1000/libpod: mkdir /run/user/1000/libpod: permission denied 
ERRO[0000] cannot mkdir /run/user/1000/libpod: mkdir /run/user/1000/libpod: permission denied 
ERRO[0000] cannot mkdir /run/user/1000/libpod: mkdir /run/user/1000/libpod: permission denied 
```
**Describe the results you expected:**

I expected it to work normally?

```
[retool@localhost onpremise]$ id
uid=1001(retool) gid=1001(retool) groups=1001(retool) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
[retool@localhost onpremise]$ whoami
retool
```

**Additional information you deem important (e.g. issue happens only occasionally):**

If I exit the session, and then ssh as that user; and then type `/bin/bash`, it works.

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
[burhan@localhost ~]$ podman info --debug
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.13.4   
  podmanVersion: 1.9.3  
host:
  arch: amd64
  buildahVersion: 1.14.9
  cgroupVersion: v1     
  conmon:
    package: conmon-2.0.17-1.module+el8.2.1+6771+3533eb4c.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.17, commit: 3c703d9f178a3a53966e1d5c03d0275ea6cb36a0'
  cpus: 1
  distribution:
    distribution: '"rhel"'
    version: "8.2"
  eventLogger: file
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-193.el8.x86_64
  memFree: 5599051776
  memTotal: 8189816832
  ociRuntime:
    name: runc
    package: runc-1.0.0-66.rc10.module+el8.2.1+6465+1a51e8b6.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.0.1-1.module+el8.2.1+6595+03641d72.x86_64
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.3.0
  swapFree: 8493461504
  swapTotal: 8493461504
  uptime: 4h 58m 50.46s (Approximately 0.17 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/burhan/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.0.0-2.module+el8.2.1+6465+1a51e8b6.x86_64
      Version: |-
        fuse-overlayfs: version 1.0.0
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/burhan/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/burhan/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.9.3-2.module+el8.2.1+6867+366c07d6.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
I'm assuming the UID of the user you `su`'d to is not 1000?

There are well-known problems with rootless Podman and `sudo`/`su` (they don't count as a full "session" in the eyes of PAM and systemd, so certain things that Podman expects will be created and configured are not), but it looks like we have a different problem here. I suspect that some environment variables (`XDG_RUNTIME_DIR` perhaps?) are being leaked from one user into the other, potentially?

**Comment by burhan** [comment]
The system has two users; my user (burhan, uid 1000) and the retool user, (uid 1001).

As `retool` is a system user, I login with my user, and then `su` to `retool`. However, to test things out, I enabled ssh and when I ssh directly using `retool`, it works.

I did re-run the shell (executed `/bin/bash` after logging in as retool), because I read somewhere else (forgot where) that this loads the environment correctly while troubleshooting this issue.

However, in the initial scenario - where I ssh as `burhan`, then `su retool`, I also did `/bin/bash` as retool, but that didn't work.

Not sure what's going on to be honest.

**Comment by asottile** [comment]
if you're using `su` you'll probably want to use `su --login`:

(from `man su`)

```
       -, -l, --login
              Start  the shell as a login shell with an environment similar to
              a real login:

                 o      clears all the environment variables except  TERM  and
                        variables specified by --whitelist-environment

                 o      initializes  the  environment  variables  HOME, SHELL,
                        USER, LOGNAME, and PATH

                 o      changes to the target user's home directory

                 o      sets argv[0] of the shell to '-' in order to make  the
                        shell a login shell
```

otherwise you'll leak XDG environment variables which can affect processes in the other user:

```console
$ env | grep XDG | sort
XDG_RUNTIME_DIR=/run/user/1000
```

**Comment by burhan** [comment]
Ah okay. I didn't realize there was an environment variable being used.

Is it going to be an issue if the target user (retool in this case) has no shell? As its just a system user in production they won't have a shell assigned and won't have a home directory either. Its just for permission management.

**Comment by asottile** [comment]
idk, you'd have to try it -- worst case you can probably utilize `env` (either with `-i` or `-u`)

or use `sudo -u ...` which seems to do a better job than `su`

**Comment by vrothberg** [comment]
> Ah okay. I didn't realize there was an environment variable being used.
> 
> Is it going to be an issue if the target user (retool in this case) has no shell? As its just a system user in production they won't have a shell assigned and won't have a home directory either. Its just for permission management.

Not having a home will very likely be an issue as that's where the rootless container storage for each user resides.

**Comment by vrothberg** [comment]
@burhan are you ready to go? Can we close?

**Comment by burhan** [comment]
Yes thank you. This resolves the issue. I need to create a "real" user with a valid home and environment.
