### ISSUE TITLE
Change documentation site to use monospaced fonts

### ISSUE THREAD

**Issue by burhan** [containers/podman#7474]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Please use a mono-spaced font on the documentation site, because the current font makes it difficult to distinguish between a `-` and `--` in the command line arguments.

**Comment by Luap99** [comment]
Are you talking about https://docs.podman.io?

**Comment by burhan** [comment]
Yes.

**Comment by eriksjolund** [comment]
If I do copy paste of some text in

http://docs.podman.io/en/latest/markdown/podman-run.1.html

with Google Chrome and Fedora 32 it looks like this

```
–interactive, -i=true|false
```
I think it should have been

```
--interactive, -i=true|false
```

**Comment by TomSweeneyRedHat** [comment]
@eriksjolund and @burhan I'd not noticed that, thanks for the heads up.  Now to figure out how to change the font there....

**Comment by burhan** [comment]
A few options:

* change the markdown  so that instead of bold `**--build-arg**=*arg=value*` for the arguments, it is marked up as a code block, the default Sphinx theme being used (`alabaster`) will use `'Consolas', 'Menlo', 'DejaVu Sans Mono', 'Bitstream Vera Sans Mono', monospace`, which should render better.

* override the default body font, by adding `font_family` to the `conf.py` setting for the theme options.

**Comment by TomSweeneyRedHat** [comment]
@burhan TYVM for the pointers, I'll go dig around for those.

**Comment by vrothberg** [comment]
@TomSweeneyRedHat, did you find a way to alter the fonts?

**Comment by TomSweeneyRedHat** [comment]
@vrothberg no I've not, I was sidetracked by other things.  Will try to boost this up the queue again.

**Comment by TomSweeneyRedHat** [comment]
@burhan do you have some MD tips you might offer?  The issue I'm having is if I convert this line:
```
**--interactive**, **-i**=**true**|**false**
```
which now shows as:
**--interactive**, **-i**=**true**|**false**

To a code block for each of the bold fields in that line:

```
**`--interactive`**, **`-i`**=**`true`**|**`false`**
```

I see:
**`--interactive`**, **`-i`**=**`true`**|**`false`**

That makes the bold text too small.  The only thing I could come up with is this:
```
<pre><b>--interactive</b>, <b>-i</b>=<b>true</b>|<b>false</b></pre>
```
which shows:
<pre><b>--interactive</b>, <b>-i</b>=<b>true</b>|<b>false</b></pre>

Which is also too small.

I tried specifying the size of the `<pre>` font, but that was not very successful.  If it was straight html I could do something with css or `<div>` tags, but I'm not seeing how to make that work in md.  Thoughts?

**Comment by rhatdan** [comment]
I am going to close this issue, since we never got any additional feedback.

**Comment by TomSweeneyRedHat** [comment]
Just noting https://github.com/containers/podman/pull/9856from @Luap99 which fixed this issue.
