### ISSUE TITLE
Closing stdin of container from containers.Attach

### ISSUE THREAD

**Issue by repomaa** [containers/podman#7479]
/kind feature

**Description**

Using the go bindings I stumbled across the issue that attaching to a container and passing a `Reader` as the `stdin` parameter (in my case an `io.PipeReader`) will keep the `stdin` of that container open, after the `Reader` returns `EOF`.

I think Docker does this by returning a special kind of struct called `HijackedResponse` which has a `CloseWrite` method. Calling this method actually closes the `stdin` of the container.

This feature is crucial for running shells or other repls and passing e.g. user input to them and (most importantly) getting the exit code of the shell.

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Comment by vrothberg** [comment]
Hi @repomaa, thanks for reaching out and apologies for the longer silence.

@baude @jwhonce @mheon what do you think? This might be something to consider when refactoring the bindings (not sure if that's still on the roadmap).

**Comment by mheon** [comment]
I think we need to figure out how the Docker API handles this and try and duplicate that behavior. I'm actually not sure how they handle closing one side of the HTTP connection, but they clearly have some way to do it.

**Comment by jwhonce** [comment]
@mheon This may impact a number of endpoints as we've been adding code to stop the endpoint when the client closes the connection. I'm not sure we've added any of that code to hijacked connections which is why I used "may".

**Comment by mheon** [comment]
@jwhonce We are not supporting the client *closing* the connection (which already works fine) - we just want to close one stream (STDIN). The remaining standard streams will continue streaming - we just stopped accepting input.

**Comment by rhatdan** [comment]
@jwhonce @mheon What is the scoop on this Issue now?

**Comment by mheon** [comment]
Have not had time to look into this further.

**Comment by rhatdan** [comment]
@jwhonce Do you have time to work on this?

**Comment by rhatdan** [comment]
This is still an open issue, would love to get someone from the community to work on it.

**Comment by rhatdan** [comment]
@jwhonce Do you think you could have some time this sprint to look at this?

**Comment by mheon** [comment]
I now know how this works on the server side. Accomplishing it on the client side could be tricky, mostly from perspective of exposing the right method to get it to happen. Could be a good 4.0 candidate since I think it could be a breaking change.

**Comment by rhatdan** [comment]
@jwhonce @mheon any movement on this one?

**Comment by mheon** [comment]
Negative. This is probably more of a @jwhonce and @baude thing than me since it will be entirely a bindings change.

**Comment by rhatdan** [comment]
@jwhonce @baude any progress on this?

**Comment by vrothberg** [comment]
Friendly ping.

**Comment by Luap99** [comment]
I pretty sure I fixed some bugs like this, can you test again? I think if the reader returns EOF we close the stdin on the server side now.

**Comment by rhatdan** [comment]
I will close this, reopen if it is still broken...

**Comment by mheon** [comment]
I think the server works, but I don't know if the client does - original request was that the bindings we able to initiate a close of STDIN themselves.
