### ISSUE TITLE
Swagger API documentation for specific podman version

### ISSUE THREAD

**Issue by fstephany** [containers/podman#7495]
/kind documentation

**Description**

Is there any way to retrieve the API documentation for a given version of Podman? 
From what I understand, the [API swagger description](https://docs.podman.io/en/latest/_static/api.html) is based on the master branch of the repo? Are the generated docs versioned somewhere (say, I'd like to retrieve them for Podman 2.0.4 specifically)?

**Comment by rhatdan** [comment]
@jwhonce @baude Any update on this?

**Comment by rhatdan** [comment]
@jwhonce @baude  Please comment.

**Comment by rhatdan** [comment]
As of right now, we don't have a way to get specific version of the API.

**Comment by rhatdan** [comment]
@jwhonce @baude Please comment.

**Comment by baude** [comment]
i can work with @cevich on this first thing next year.  the request is absolutely right.

**Comment by cevich** [comment]
I opened a Jira card to track this.

**Comment by baude** [comment]
#9112 should fix this for 3.0! working through a few hiccups

**Comment by rhatdan** [comment]
Looks like that merged, closing,

**Comment by fstephany** [comment]
Cool, thanks! :+1:

**Comment by baude** [comment]
for the sake of completeness, http://docs.podman.io/en/v3.0/Reference.html

**Comment by cevich** [comment]
@baude FWIW swagger upload script on master will [properly handle uploading a versioned yaml to cloud storage.](https://github.com/containers/podman/blob/master/contrib/cirrus/runner.sh#L159).  With the new upload code ported to other branches, the only thing needing changing from one branch to the next[ is the file reference on the static page.](https://github.com/containers/podman/blob/master/docs/source/_static/api.html#L21).  I did a bit of research, and it is possible to do that automatically with jinja templating...I'm just not sure how to test it on RTD.  How did you originally test the RTD setup w/o needing to tinker with files on podman master?

**Comment by baude** [comment]
i think i made a bogus branch?

**Comment by cevich** [comment]
Ahh okay, well shucks, I don't think that trick would work again now that RTD is already in place.  Maybe I can do something with the *containers/automation_sandbox* repo.
