### ISSUE TITLE
broken dependencies on debian 10

### ISSUE THREAD

**Issue by x70b1** [containers/podman#7508]
/kind bug

**Description**

At the moment the dependencies for podman 2.0.5 on debian are broken.

**Steps to reproduce the issue:**

1. use sources from the [docs](https://podman.io/getting-started/installation.html)

2. `sudo apt-get -qq -y install podman`

3. Error: `E: Unable to correct problems, you have held broken packages.`

**Describe the results you received:**

The core problem seems to be `libseccomp2`.

`podman` depends on `cri-o-runc` package which wants `libseccomp2`.

```
The following packages have unmet dependencies:
 cri-o-runc : Depends: libseccomp2 (>= 2.4.1) but 2.3.3-4 is to be installed
```

**Describe the results you expected:**

I am should be able to install podman.

**Comment by stephankoelle** [comment]
Same issue here, with update to date debian 10.
I have tried to exclude cri-o-runc, I think it is not needed, podman uses crun by default?

**Comment by mheon** [comment]
@lsm5 Poke, PTAL

**Comment by lsm5** [comment]
so @mheon mentioned that we're defaulting to runc (provided by cri-o-runc) so I'll check whatsup with the seccomp dependency.

**Comment by stephankoelle** [comment]
Work arround:
get an old cri-o-runc packge from some were an older poman 2 is installed:

/var/cache/apt/archives/cri-o-runc_1.0.0-3~dev2_amd64.deb

install that with dpk -i 
continue to install pomman with apt-get ... (should install without complain)

**Comment by lsm5** [comment]
@mheon @baude @cevich I sent a `2.0.5~3` to OBS just now which should unblock debian 10 users. It goes back to preferring runc over cri-o-runc in the dependencies. However, if there's a cri-o-runc installed already, it will prefer using that instead as `/usr/lib/cri-o-runc/sbin/runc` is listed before `/usr/sbin/runc`. So, as long as we have the CI image builder explicitly install cri-o-runc, we should be good to go.

**Comment by lsm5** [comment]
2.0.5~3 is available in the OBS stable repo now. Closing this. Please reopen if you still see this issue.

**Comment by ssbarnea** [comment]
Apparently installing podman from debian repos got broken one or two days ago for a similar kind of conflict: https://github.com/ansible-community/toolset/pull/40/checks?check_run_id=1528906129

**Comment by mheon** [comment]
Libseccomp - this is https://github.com/containers/podman/issues/8665 again

**Comment by stephankoelle** [comment]
I think the issue is back - debian 10

```
16-Dec-2020 13:43:46 | podman : Depends: libseccomp2 (>= 2.4.3-1) but 2.3.3-4 is to be installed
-- | --
16-Dec-2020 13:43:46 | Recommends: crun but it is not going to be installed
16-Dec-2020 13:43:46 | Recommends: varlink but it is not going to be installed
```

**Comment by stephankoelle** [comment]
Workarround from #8665 did work
apt-get -t buster-backports install libseccomp-dev

**Comment by zhangguanzhang** [comment]
@lsm5 PTAL

**Comment by dmlond** [comment]
I tried to install podman on a Raspberry Pi 4 using the Raspberry Pi OS. The cpu is ARMv7 Processor rev 3 (v7l).  I am not able to follow the instructions to install buster-backports because I am not able to install the gpg key for it. apt-get -t buster-backports install libseccomp-dev gives the following error:
E: The value 'buster-backports' is invalid for APT::Default-Release as such a release is not available in the sources.

I also get the above error when I try to apt-get install podman
apt-get -qq -y install podman
E: Unable to correct problems, you have held broken packages.

**Comment by Andreyooo** [comment]
I also tried installing Podman following the instructions on a Raspberry Pi 3 (Raspbian GNU/Linux 10 (buster) & ARMv7 Processor rev 4 (v7l)) and get:

```
apt-get -qq -y install podman
E: Unable to correct problems, you have held broken packages.
```

**Comment by justinschuldt** [comment]
@dmlond @Andreyooo if you remove the `-qq` from the `apt-get` call it will tell you what is going on. The tl;dr is that there is not a compatible version of `libseccomp2` for Debian10/Raspberry Pi OS 10, so you have to manually install it from the `buster-backports` source before installing podman.

- First make sure you have the keys for the debian archive: `sudo apt-get install debian-archive-keyring`
- Source the repo with the unstable version that will satisfy podman's dependencies: `echo 'deb http://deb.debian.org/debian buster-backports main' >> /etc/apt/sources.list`
- Then update `sudo apt-get update`
- Manually install the `libseccomp2: v2.4.4-1` package to make podman happy `sudo apt-get -y -t buster-backports install libseccomp2`

Good luck!

**Comment by Andreyooo** [comment]
Thx a lot @justinschuldt. Podman is now successfully installed on my Raspberry Pi :)

**Comment by rhatdan** [comment]
Should this issue be closed then?

**Comment by x70b1** [comment]
@rhatdan Yes, can be closed again.
Using `libseccomp2` from debian-backports solves the latest issue.

**Comment by dmlond** [comment]
I was not able to install the gpg keys for debian-backport because most of the older public key servers are not available.

**Comment by yacineMTB** [comment]
@dmlond Might be your location, I was just able to do so
