### ISSUE TITLE
Automatic creation of storage.conf/libpod.conf is an anti-feature

### ISSUE THREAD

**Issue by jjzmajic** [containers/podman#7509]
This effectively introduces the requirement that all users running podman either have a writable home directory or are provisioned in advance. This is not always the case, especially at scale with lots of "worker" users.

The cost is clear but I see no benefit to this approach. Is there something I'm missing?

**Comment by jjzmajic** [comment]
I presume this specific use case was why the `--storage-opt` setting was added. (Though I sorely miss an equivalent `--libpod-opt`.)

**Comment by mheon** [comment]
I believe we've already disabled this - @rhatdan can you confirm?

**Comment by jjzmajic** [comment]
Ok, this is my mistake. I didn't rehash my shell after `sudo make install`. You did remove this feature.

Should I open a separate issue for `--libpod-opt`? My issue is that I cannot guarantee the appropriate `XDG_SESSION_ID`, the right `XDG_RUNTIME_DIR`, nor a writable home directory. I would like to configure all of this from the command line and I assume this is only possible with something like `--libpod-opt`. Am I wrong in this?

**Comment by jjzmajic** [comment]
There still seem to be some directories that podman is trying to create, but the upside is that at least it can still run under 2.0.5.

I'm running the following command:
`podman --root /podman/storage --runroot /podman/run run -it alpine sh`

As expected, I get dropped into `ash`, but I still get:
`ERRO[0000] unable to make temp dir /home/<dummy>/.config`

**Comment by jjzmajic** [comment]
I believe this line is the culprit: https://github.com/containers/podman/blob/master/pkg/util/utils_supported.go#L87

It should have also been removed as part of the changes discussed above no? (For the same reasons at least.)

**Comment by rhatdan** [comment]
Yes that should have been removed before.

@jjzmajic Nice catch.
