### ISSUE TITLE
Static IPv6 address and --ip6

### ISSUE THREAD

**Issue by hakonhall** [containers/podman#7511]
/kind feature

**Description**

We need to start containers with a static IPv6 address: the `--ip6` option to `podman run`. These containers may or may not also have a static IPv4 address (`--ip`).

This has been mentioned in tickets and comments before, but extracted to this ticket for visibility:
https://github.com/containers/podman/issues/7265#issuecomment-671054850
https://github.com/containers/podman/issues/6114#issuecomment-632410709

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes, checked HEAD on master.

**Comment by hakonhall** [comment]
From https://github.com/containers/podman/issues/6114#issuecomment-632410709 this may already be in progress @mheon ?

**Comment by apoos-maximus** [comment]
I want to work on this issue !

**Comment by mheon** [comment]
Sure, let me assign it to you.

This should mostly involve adding the flag to the command line and passing it through into Libpod, similar to how the existing `--ip` flag works. Unfortunately, it looks like CNI presently limits us to a static IP or IPv6 address, both cannot be used at the same time.

**Comment by rhatdan** [comment]
Welcome @apoos-maximus. Looking forward to what you come up with.

**Comment by apoos-maximus** [comment]
@rhatdan sure !

**Comment by andrin55** [comment]
Hi

Is there any progress on this issue?
With Podman version 2.1.1 it's still not implemented:
```
[root@container01 ~]# podman run -it --rm --network container_dmz --ip6 2a01:x:x:x::199 alpine ping6 2620:fe::fe -c 4
Error: unknown flag: --ip6
```


When I start the container on my dualstack macvlan network with IPv4 set statically, it allocates a both address types (just the IPv6 address is dynamic):
```
[root@container01 ~]# podman run -it --rm --network container_dmz --ip 192.168.115.199 alpine sh
/ # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0@if3: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue state UP
    link/ether f6:cc:d5:a7:0c:a5 brd ff:ff:ff:ff:ff:ff
    inet 192.168.115.199/24 brd 192.168.115.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2a01:x:x:x::9/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::f4cc:d5ff:fea7:ca5/64 scope link
       valid_lft forever preferred_lft forever
/ # ping6 google.com
PING google.com (2a00:1450:4001:800::200e): 56 data bytes
64 bytes from 2a00:1450:4001:800::200e: seq=0 ttl=118 time=15.479 ms
64 bytes from 2a00:1450:4001:800::200e: seq=1 ttl=118 time=15.575 ms
^C
--- google.com ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max = 15.479/15.527/15.575 ms
```

**Comment by mheon** [comment]
Not yet. We want to look into Podman and IPv6 compatibility, but we haven't found the time to do so properly yet.

**Comment by remyluslosius** [comment]
ok. Thanks for the quick response.

**Comment by rhatdan** [comment]
@mheon Some IPv6 code just got merged, did that fix this issue or move us closer?

**Comment by mheon** [comment]
No - there are still some pretty fundamental issues with IPv6 and CNI.

**Comment by rhatdan** [comment]
I believe there is a duplicate issue to this one in existence, one of them should be closed.

**Comment by unixfox** [comment]
Bump

**Comment by rhatdan** [comment]
@apoos-maximus Did you ever work on this?

**Comment by rhatdan** [comment]
@mheon PTAL

**Comment by apoos-maximus** [comment]
Hello i am sorry I am not getting enough time to work on the isuue apologies.
Please reassign it to someone else

**Comment by mzhirnov1** [comment]
Hello! I realy need that in our project. Docker have static IPv6 but I like cri-o in production

**Comment by mzhirnov1** [comment]
![image](https://user-images.githubusercontent.com/47160263/133315632-d98b9a1b-ceae-4e39-9d11-ea6bafc4a4ee.png)

**Comment by mheon** [comment]
Podman and CRI-O are different projects - if you need support in CRI-O, please open an issue over there.

This is something we are targeting for the network rework in Podman 4.0.

**Comment by mzhirnov1** [comment]
we use podman to run containers. When are you going to release Podman 4.0 ?

**Comment by mheon** [comment]
Current target is early next year.

**Comment by anthr76** [comment]
Any ways the community can chip in and help? I'm not super familiar with podman CNIs yet but I'm going to read up a bit tonight

**Comment by mheon** [comment]
Testing netavark, our new network stack, once it becomes available (we're starting to get close to done, functionality-wise) will be extremely helpful - we'll put out a post once it's ready for testing.

The new network code lives at https://github.com/containers/netavark - we're accepting contributions there, but it's still changing rapidly as things come together.

**Comment by Luap99** [comment]
Should I add the flag or do we only want to support the `--network netname:ip6=fd10::2` syntax, @mheon WDYT?

**Comment by mheon** [comment]
We should add the flag for Docker compat's sake

**Comment by Luap99** [comment]
ack, should be simple to add now
