### ISSUE TITLE
OAuth2 support

### ISSUE THREAD

**Issue by hobbytp** [containers/podman#7518]
does podman support OAuth2 (bearer token) authorization like docker engine does in the picture in https://docs.docker.com/registry/spec/auth/token/?  There are 6 steps in OAuth2 flow.
That means, when podman pull image, it will try to access container registry but failed (return 401 unauthorized), and then it send request to "Authorization Service" to get access token, after getting access token, it will send send request to container registry again.

**Comment by rhatdan** [comment]
@mtrmac @QiWang19 PTAL

**Comment by mtrmac** [comment]
Please start with describing what you are actually trying to do.

That protocol you link is not really OAuth, and it is ~supported in the default flow starting with `podman login` (but not _exactly_ as described because that isn’t how Docker behaves, and that would not allow working with some real-world registries). There is a separate way to sort of integrate with (something closer to?) real OAuth2 via https://docs.docker.com/registry/spec/auth/oauth/ , which IIRC requires setting up the `auth.json` file manually with an appropriate `identitytoken` value.

**Comment by hobbytp** [comment]
thanks @mtrmac, sorry for unclear description. let me try to clarify my questions as below:

I tried docker engine/docker client + docker registry (configured with authorization server realm and root cert) +keycloak (use docker-v2 protocol mapper), the OAuth2 flow in https://docs.docker.com/registry/spec/auth/token/ can work, I tcpdump the pkt to verify it.  So I would like to know if podman command can support the similar flow to execute authorization for a container registry.

e.g. can **podman pull** do authorization with OAuth2 (like the flow in https://docs.docker.com/registry/spec/auth/token/ which docker supported.)? 

For **podman login**, I check the podman login code (https://github.com/containers/podman/blob/master/cmd/podman/login.go#69), it will call https://github.com/containers/common/blob/master/pkg/auth/auth.go#60, it does not support identifytoken, but it will call docker.CheckAuth function in https://github.com/containers/common/blob/ee01e148b90710472f47474597672ed6df622049/vendor/github.com/containers/image/v5/docker/docker_client.go#L288, it makes me confused, does that mean **podman login** only support docker engine for authorization? or docker_client here does not mean the container engine must be docker?

**Comment by mtrmac** [comment]
> That protocol you link is not really OAuth

containers/image/v5/docker/docker_client.go has nothing to do with the Docker Engine.

**Comment by hobbytp** [comment]
Thanks @mtrmac for clarification. it is not real OAuth, so can I call it auth challenges?

Can I understand code containers/image/v5/docker/docker_client.go only follow OCI distribution spec to do some auth job? or it just follow Docker distribution API? Is this auth flow is the similar with https://docs.docker.com/registry/spec/auth/token/?

And I guess both podman and  skopeo can use containers/image/v5/docker/docker_client.go to do auth (when challenges are needed), right?

And I found the cri-o pull does use the same challenges logic in containers/image, cri-o calls containers/image/copy/copy.go to pullimage job, so can I understand cri-o container engine does not support this auth challenge flow?

Sorry for raising many questions at a time, and thanks for your clarification.

**Comment by mtrmac** [comment]
Are you encountering any _actual issue_? Did you try using Podman, and did it work? Is there something that does not work, or something specific that you can’t configure?

If you want to understand the how the code works, it’s all Open Source; but I’m not going to explain it line by line if there is no bug/feature to investigate.

**Comment by rhatdan** [comment]
Since we got no info back from reporter, closing.  Reopen if more info is provided.
