### ISSUE TITLE
Server/service fails to detect client disconnect in stats REST API

### ISSUE THREAD

**Issue by hakonhall** [containers/podman#7521]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The server does not detect client disconnect with the stats REST API, taking up resources linear in the the number of historical requests.

**Steps to reproduce the issue:**

1.

```
sudo podman run -d --name c1 --entrypoint /bin/sleep docker.io/library/alpine 12345
```

2.

Start the service in terminal A:

```
sudo podman --root /var/vespa/podman system service -t 0
```

3.

In Terminal B:

```
sudo curl --unix-socket /run/podman/podman.sock http://h/containers/c1/stats
```

and then `control-c` after, say, 10s.

**Describe the results you received:**

Every 4 seconds, the server responds with stats and prints a warning:

```
http: superfluous response.WriteHeader call from github.com/containers/libpod/pkg/api/handlers/utils.WriteJSON (handler.go:64)
```

This is annoying but looks harmless. After `control-c` (in terminal B), the message is printed a few more times, the following is printed instead every 4 seconds:

```
http: superfluous response.WriteHeader call from github.com/containers/libpod/pkg/api/handlers/utils.WriteJSON (handler.go:64)
ERRO[0276] unable to write json: "write unix /run/podman/podman.sock->@: write: broken pipe" 
```

**Describe the results you expected:**

I expect the server to detect that the client has disconnected, and stop trying to send a response.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Version:            1.9.3
RemoteAPI Version:  1
Go Version:         go1.13.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
(if needed)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.9.3-2.module+el8.2.1+6867+366c07d6.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No and yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

(if needed)

**Comment by mheon** [comment]
The API in 1.9.3 is *very* early - any chance you can retest with Podman v2.0.5?

**Comment by hakonhall** [comment]
On RHEL 8 that's the latest I have available.  The description in https://podman.io/getting-started/installation would install an even older version, so it requires building from scratch.

**Comment by rhatdan** [comment]
@baude Has a PR for this.
