### ISSUE TITLE
no_proxy environment variable causes to access the proxy when it shouldn't

### ISSUE THREAD

**Issue by masayag** [containers/podman#7531]
/kind bug

**Description**

Podman uses the proxy for accessing the domain although no_proxy environment variable is set as '.domain-name'.
Podman doesn't use the proxy for accessing the sub-domain when only the domain is set.
There is no option to exclude only subdomains from using the proxy.

Specifically, when setting the following values for no_proxy, this is the actual behavior:

- no_proxy=".quay.io" - podman uses the proxy for accessing quay.io:443
- no_proxy="quay.io" - podman doesn't use the proxy for any access to quay.io and for its subdomains (e.g. cdn02.quay.io:443)
- no_proxy=".quay.io,quay.io" - podman doesn't use the proxy for quay.io and its subdomains

Based on https://www.gnu.org/software/wget/manual/html_node/Proxies.html (which is referenced from https://github.com/containers/podman/blob/master/vendor/github.com/docker/docker/api/swagger.yaml#L3939)
> no_proxy
This variable should contain a comma-separated list of domain extensions proxy should not be used for. For instance, if the value of no_proxy is ‘.mit.edu’, proxy will not be used to retrieve documents from MIT.

**Steps to reproduce the issue:**
```
export https_proxy=http://10.46.41.7:3128
export no_proxy='.quay.io'
podman run --rm=true --rmi=true quay.io/masayag/hello
```

**Describe the results you received:**
The proxy's access.log contains:
```
1599035610.636    622 192.168.126.10 TCP_TUNNEL/200 5724 CONNECT quay.io:443 - HIER_DIRECT/52.201.153.168 -
1599035610.666    652 192.168.126.10 TCP_TUNNEL/200 5695 CONNECT quay.io:443 - HIER_DIRECT/52.201.153.168 -
```

**Describe the results you expected:**
I'd expect the following:
- no_proxy=".quay.io" not to use proxy for both quay.io and its subdomains
- no_proxy="quay.io" not to use proxy for quay.io domain, but use it for its subdomains

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.9.3
RemoteAPI Version:  1
Go Version:         go1.13.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  gitCommit: ""
  goVersion: go1.13.4
  podmanVersion: 1.9.3
host:
  arch: amd64
  buildahVersion: 1.14.9
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.17-1.rhaos4.5.el8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.17, commit: c7b458c6595c8d4f0a5dd6e72012d00dd81e646b'
  cpus: 4
  distribution:
    distribution: '"rhcos"'
    version: "4.6"
  eventLogger: file
  hostname: test-infra-cluster-master-0
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-211.el8.x86_64
  memFree: 15316758528
  memTotal: 17423351808
  ociRuntime:
    name: runc
    package: runc-1.0.0-70.rhaos4.5.gite677e8b.el8.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2'
  os: linux
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 15h 3m 18.93s (Approximately 0.62 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.9.3-1.rhaos4.6.el8.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Tested on kvm-based VM

**Comment by rhatdan** [comment]
Podman is just using the golang libraries to handle this.  If no_proxy is not working correctly then it is a bug in go/golang, I believe.  There is not much that Podman can do about this.

**Comment by masayag** [comment]
Thanks for highlighting it, so I'm closing this issue since the behavior is as defined on https://godoc.org/golang.org/x/net/http/httpproxy for the NoProxy field which seems to be the desired one by golang lib.
