### ISSUE TITLE
ipv6 support for portmap

### ISSUE THREAD

**Issue by ruben-herold** [containers/podman#7606]
hi,

I try to use podman on a centos 8 host. The host has only Ipv6. So I want portmap a container with ipv6. 
I could not find any option on podman create to make it listen on ipv6

**Comment by mheon** [comment]
Are you running as root, or rootless?

**Comment by ruben-herold** [comment]
podman container create  -p 9115:9115 blackbox_exporter
podman container start $container_id

After this it  is only listen on ipv4

**Comment by mheon** [comment]
Again - are you running Podman as root, or as a normal user?

**Comment by ruben-herold** [comment]
I was testing as root sorry

**Comment by rhatdan** [comment]
@ruben-herold @mheon What is going on with this one?

**Comment by mheon** [comment]
Sorry, this slipped through my radar. To listen on a port via IPv6, `podman run -p [::]:8080:80 ...` should forward port 80 in the container to port 8080 on all IPv6 addresses on the host

**Comment by unixfox** [comment]
Listening on an IPv6 port works but the container doesn't receive any request:
```
root@podman:~# podman run -d -p [::]:8080:80 nginx
b97753fa31d88938352f90d6818ca1c79a798ec915e984eeda981c998b5ed9dd
root@podman:~# lsof -i:8080
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
conmon  9817 root    5u  IPv6  53231      0t0  TCP *:http-alt (LISTEN)
root@podman:~# curl -m 10 [::1]:8080
curl: (28) Operation timed out after 10000 milliseconds with 0 bytes received
```

Here is the result in IPv4:
```
root@podman:~# podman run -d -p 8080:80 nginx
9f6f754fe0003760c9d8b537e908cf4be1c1d1a618c6d4c7471054b610c2c416
root@podman:~# lsof -i:8080
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
conmon  9513 root    5u  IPv4  52042      0t0  TCP *:http-alt (LISTEN)
root@podman:~# curl -I 127.0.0.1:8080
HTTP/1.1 200 OK
Server: nginx/1.19.3
```

podman version 2.1.1 and it is running as root

**Comment by remyluslosius** [comment]
Any idea what podman version first implements this ipv6 solution "podman run -p [::]:8080:80 ..."? This obviously doesn't work in RHEL 8.2.  **Podman version 1.9.3**

``
 podman run -p [::]:80:80 -p 80:80 --name web -d docker.io/library/nginx:latest 
``

**output:** Error: cannot resolve the TCP address: address :::80: too many colons in address

**Comment by mheon** [comment]
Podman 2.0 and up

**Comment by remyluslosius** [comment]
@mheon Thanks

**Comment by remyluslosius** [comment]
I think I'm having the same issue @unixfox mentioned [above](https://github.com/containers/podman/issues/7606#issuecomment-708435854). 

Below is the response I got when using curl.

**IP address is modified in the sample data below.**
```

[rootuser ~]# curl -6 -v -k -g http://[::12]
* Rebuilt URL to: http://[::12]/
*   Trying ::12...
* TCP_NODELAY set
* Connected to ::12 (::12) port 80 (#0)
> GET / HTTP/1.1
> Host: [::12]
> User-Agent: curl/7.61.1
> Accept: */*
>

```
IPv6 connection above hangs -- response is timeout.

```
[rootuser ~]# curl -4 -k -v http://1.1.1.1
* Rebuilt URL to: http://1.1.1.1
*   Trying 1.1.1.1...
* TCP_NODELAY set
* Connected to 1.1.1.1 (1.1.1.1) port 80 (#0)
> GET / HTTP/1.1
> Host: 1.1.1.1
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Server: nginx
< Content-Type: text/html; charset=utf-8
< Content-Length: 340
< Connection: close
<
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>404 - Not Found</title>
 </head>
 <body>
  <h1>404 - Not Found</h1>
 </body>
</html>
* Closing connection 0
```
IPv4 works fine

**Comment by ericzolf** [comment]
Sounds to me like a duplicate of #7415

**Comment by remyluslosius** [comment]
@ericzolf Yeah I think it's the same issue.

**Comment by rhatdan** [comment]
Closing since this is a duplicate of #7415
