### ISSUE TITLE
sles15.2/sp2 (podman-1.8,crun,groupsv2) can't run containers when sshing with non-root account

### ISSUE THREAD

**Issue by bobhenkel** [containers/podman#7615]
Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)

/kind bug

**Description**
I'm running sles15.2/sp2 and can't ssh into the vm with a non-root account and run a container without an error, simple run like this podman run --rm -it alpine sh will fail.  I have enabled cgroupsv2 and installed crun details below.  If I instead never ssh in as the non-root account and instead su over to the non-root account  after ssh in with the root account I can run podman run --rm -it alpine sh with success.

If I don't use crun and don't enable cgroupsv2 this issue doesn't happen.  My goal is to get true rootless containers and the isolation that comes with them so from what I read I need cgroupsv2 and crun as part of the requirements to make that happen.

**Steps to reproduce the issue:**

1.ssh with root into sles15sp2 instance.

2. zypper refresh
3. zypper update
4. zypper in --no-confirm buildah fuse-overlayfs podman slirp4netns
5. sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT="/&systemd.unified_cgroup_hierarchy=1 /' /etc/default/grub
6. grub2-mkconfig -o /boot/grub2/grub.cfg
7. wget https://github.com/containers/crun/releases/download/0.14.1/crun-0.14.1-static-x86_64 -O /usr/bin/crun
8. chmod +x /usr/bin/crun
9. reboot
10. ssh with root into vm
11.  
useradd bob -m
groupadd bob
usermod -a -G bob bob
mkdir /home/bob/.ssh
cp /root/.ssh/authorized_keys /home/bob/.ssh/authorized_keys
chown -R bob:bob /home/bob
12. exit
13. ssh into vm with bob account
14. podman info (note that crun, fuse overlay, and cgroups v2 show up in output)
15. podman run --rm -it alpine sh

**Describe the results you received:**
```
bob@test-cgroupsv1-sles15sp2-podman:~> podman run --rm -it alpine sh
Error: error creating systemd unit `libpod-e3946c951706db8260184d6165508b88b7662fa995566a23c02175dbb779216c.scope`: got `failed`: OCI runtime error
```

**Describe the results you expected:**
Should have received a shell in the container.

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens only if I ssh into the vm and issue podman commands with the non-root account. The root account doesn't not seem to suffer from this. Once in this state I can't get the non-root account to not receive this error unless I do the following after receiving this error.

ssh into vm as root
```
ps -aux | grep bob | grep podman
```
kill and pids that show up for that command
```
kill XYZ ABC
```
exit as root and ssh in as bob or su -l bob and do
```
rm -fr .local/share/containers/
rm -fr .config/containers/
```
Now podman will work for bob account
```
podman run --rm -it alpine sh
/ #
```
However if you exit out and ssh in as bob the error shows up again.

**Output of `podman version`:**

```
bob@test-cgroupsv1-sles15sp2-podman:~> podman version
Version:            1.8.0
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

```
bob@test-cgroupsv1-sles15sp2-podman:~> podman info --debug
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.12
  podman version: 1.8.0
host:
  BuildahVersion: 1.13.1
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.10-3.3.1.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.10, commit: unknown'
  Distribution:
    distribution: '"sles"'
    version: "15.2"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 100
      size: 1
    - container_id: 1
      host_id: 296608
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1003
      size: 1
    - container_id: 1
      host_id: 296608
      size: 65536
  MemFree: 12136247296
  MemTotal: 12552650752
  OCIRuntime:
    name: crun
    package: Unknown
    path: /usr/bin/crun
    version: |-
      crun version 0.14.1
      commit: 598ea5e192ca12d4f6378217d3ab1415efeddefa
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 8
  eventlogger: file
  hostname: test-cgroupsv1-sles15sp2-podman
  kernel: 5.3.18-22-default
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.7-3.12.1.x86_64
    Version: |-
      slirp4netns version 0.4.7
      commit: unknown
      libslirp: 4.3.1-git
  uptime: 20m 41.54s
registries:
  search:
  - docker.io
store:
  ConfigFile: /home/bob/.config/containers/storage.conf
  ContainerStore:
    number: 0
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.6-3.6.1.x86_64
      Version: |-
        fuse-overlayfs: version 0.7.6
        FUSE library version 3.6.1
        using FUSE kernel interface version 7.29
  GraphRoot: /home/bob/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 1
  RunRoot: /var/tmp/run-1003/containers
  VolumePath: /home/bob/.local/share/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
bob@test-cgroupsv1-sles15sp2-podman:~> zypper search --installed-only podman
Loading repository data...
Reading installed packages...

S  | Name              | Summary                                                               | Type
---+-------------------+-----------------------------------------------------------------------+--------
i+ | podman            | Daemon-less container engine for managing containers, pods and images | package
i  | podman-cni-config | Basic CNI configuration for podman                                    | package
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No(suse 15.2/sp2 repo has 1.8 in it so that's what I was using)/Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OpenStack VM

**Comment by vrothberg** [comment]
Hi @bobhenkel, thanks for opening the issue!

I suggest opening a ticket on the SUSE Bugzilla. I don't know if crun is supported on SLES. Upstream, we're focusing on the latest version and issues against RHEL or SLES should go through the corresponding support channels.

Note that you can run rootless containers with runc and CGroups v1 as well. CGroups v2 has some more sophisticated features but v1 works and is well tested.
