### ISSUE TITLE
Move ghcr.io/akihirosuda/podman-rootless-cni-infra to official quay

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/podman#7617]
https://github.com/containers/podman/blob/25fb0c2b966c193e8c4045e440316850f6f1b889/libpod/rootless_cni_linux.go#L25-L29

The image should be moved to the official quay repo

Follow-up to #7460

**Comment by vrothberg** [comment]
Thanks for catching up on this, @AkihiroSuda. I'll move the image and open a PR to change the reference.
