### ISSUE TITLE
podman centos8 repo  unavailable

### ISSUE THREAD

**Issue by lostz** [containers/podman#7631]
Status code: 404 for http://ftp.lysator.liu.se/pub/opensuse/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/repodata/91e2f0d1b4f5e4dbaaffe33fccfefad47782c4b6537eb36d3487a8456f6f00ae-filelists.xml.gz 

ftp.lysator.liu.se seems not rsync any more.

**Comment by vrothberg** [comment]
It looks like the mirror isn't working. Can you try another one?

**Comment by lsm5** [comment]
@lostz I'm able to install podman just fine using the steps mentioned in the install doc. Maybe it's just a case of a bad mirror. Check if a `dnf clean all` followed by the installation steps works for you. If that doesn't work either, I guess it's best to open a bug with the opensuse people.

Closing...
