### ISSUE TITLE
Is there a Podman Version Requirement to enable  (systemctl --user enable podman.socket ?)

### ISSUE THREAD

**Issue by bobhenkel** [containers/podman#7632]
Is there a required version for podman to be at on the podman host for this to work? If so is there a manual way to get this to work on say podman version 1.8.6?

I was following this post https://www.redhat.com/sysadmin/podman-clients-macos-windows.

Thanks!

**Comment by mheon** [comment]
Our support for the REST API (and the accompanying `podman.socket` systemd service for the API socket) was added in Podman v1.9, but only became stable in Podman v2.0. We recommend using Podman v2.0 and up if you want to use the REST API.
