### ISSUE TITLE
CLI defaults should come from server not client

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#7657]
We need to make sure that all CLI defaults that we may inherit from containers.conf are set by the server, not the remote client. See https://github.com/containers/podman/pull/7621#discussion_r489450218 for a discussion on the issue.

**Comment by rhatdan** [comment]
How do we verify this?

**Comment by vrothberg** [comment]
> How do we verify this?

Adding new tests where the server is started with containers.conf.A and the client with containers.conf.B, which has consistently different values than A. Then we can run a series of commands that exercise the specifics parts.

It's sounds like a lot of work but I think it's a good exercise to explore new areas in the code as the config knobs in containers.conf impact so many different parts of Podman. Maybe not a "good first issue" but an issue "to explore the code and stay for a long while" :-)

Once done, we should make sure that it's made explicit in the man pages.

I believe there are some knobs in containers.conf which need to be used by the remote client (e.g., service_destinations), so there may be a grey area we need to document.
