### ISSUE TITLE
/version API endpoint reports wrong ApiVersion and MinAPIVersion

### ISSUE THREAD

**Issue by riyad** [containers/podman#7682]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The REST API is supposed to be compatible with Docker's API version 1.40, but it reports version 1.0.0.
This trips up certain client libraries (most notably https://github.com/docker/docker-py and by extension Ansible) which currently require a minimum API version of [1.21](https://github.com/docker/docker-py/blob/master/docker/constants.py#L5).

**Steps to reproduce the issue:**

From the command line: `curl -sv --unix-socket /run/podman/podman.sock http://localhost/version`

With Python: `pip3 install -U docker; python3`
```
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
[GCC 9.3.0] on linux
>>> import docker
>>> client = docker.APIClient(base_url='unix:///run/podman/podman.sock')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/docker/api/client.py", line 198, in __init__
    raise InvalidVersion(
docker.errors.InvalidVersion: API versions below 1.21 are no longer supported by this library.
>>> 
```

**Describe the results you received:**

The version endpoint returns the following data:
```json
{
  "Platform": {
    "Name": "linux/amd64/fedora-32"
  },
  "Components": [
    {
      "Name": "Podman Engine",
      "Version": "2.0.6",
      "Details": {
        "APIVersion": "1.0.0",
        "Arch": "amd64",
        "BuildTime": "2020-09-01T19:26:51Z",
        "Experimental": "true",
        "GitCommit": "",
        "GoVersion": "go1.14.6",
        "KernelVersion": "5.4.0-47-generic",
        "MinAPIVersion": "1.0.0",
        "Os": "linux"
      }
    }
  ],
  "Version": "2.0.6",
  "ApiVersion": "1.0.0",
  "MinAPIVersion": "1.0.0",
  "GitCommit": "",
  "GoVersion": "go1.14.6",
  "Os": "linux",
  "Arch": "amd64",
  "KernelVersion": "5.4.0-47-generic",
  "Experimental": true,
  "BuildTime": "2020-09-01T19:26:51Z"
}
```

**Describe the results you expected:**

According to https://github.com/containers/podman/blob/90636fe8c2d1eb5ae75afa73405c8b12a0417fca/pkg/api/types/types.go#L5 `ApiVersion` should be "1.40" and `MinAPIVersion` should be "1.24"

**Output of `podman version`:**

```
Version:      2.0.6
API Version:  1
Go Version:   go1.14.4
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

Installed on Ubuntu 20.04 LTS from [OBS](https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman):
```
Listing... Done
podman/unknown,now 2.0.6~2 amd64 [installed]
podman/unknown 2.0.6~2 arm64
podman/unknown 2.0.6~2 armhf
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

2.0.6 is the latest sable release

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Tested with
- Ubuntu 20.04 LTS, Podman 2.0.6
- Ubuntu 20.04 LTS, Podman 2.0.6 in LXD container
- Fedora 32, Podman 2.0.6 in LXD container

**Comment by jwhonce** [comment]
This was fixed in https://github.com/containers/podman/pull/7642

**Comment by riyad** [comment]
Hah! ... awesome. :smile:
