### ISSUE TITLE
Dotnet webapi doesn't compile on fedora 32 podman

### ISSUE THREAD

**Issue by wkrea** [containers/podman#7683]
> Note: All works fine outside of podman, as you can see here:
```bash
[dell@localhost webApi]$ cd Podman/test/
[dell@localhost test]$ dotnet build
Microsoft (R) Build Engine versión 16.4.0+e901037fe para .NET Core
Copyright (C) Microsoft Corporation. Todos los derechos reservados.

  Restore completed in 60,87 ms for /home/dell/Escritorio/webApi/Podman/test/test.csproj.
  test -> /home/dell/Escritorio/webApi/Podman/test/bin/Debug/netcoreapp3.1/test.dll

Compilación correcta.
    0 Advertencia(s)
    0 Errores

Tiempo transcurrido 00:00:01.68
```

# Dotnet webapi doesn't compile on fedora 32 podman

When I just try to compile a webapi project created from CLI, i'm getting this message:
> /usr/lib64/dotnet/sdk/3.1.108/NuGet.targets(123,5): error : '32 (Container Image)' is not a valid version string. (Parameter 'value') [/home/dell/Escritorio/webApi/Podman/test/test.csproj]

Be as descriptive as you can with your title.

# General

I'm using podman online for testing purpose. I won't break my personal stable configuration on my OS; it just a simple test!!!, however not works like as [documentation says here!!!](https://docs.microsoft.com/en-us/dotnet/core/install/linux-fedora#supported-distributions)

## My personal enviroment
```bash
[dell@localhost webApi]$ cat /etc/os-release 
NAME=Fedora
VERSION="32 (KDE Plasma)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (KDE Plasma)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="KDE Plasma"
VARIANT_ID=kde
```
## Steps for reproduce the trouble

0. sudo dnf toolbox
1. toolbox create --release f32  --container netcore3.1
2. toolbox list 
3. toolbox -v enter netcore3.1
4. sudo dnf install -y dotnet-sdk-3.1 aspnetcore-runtime-3.1 dotnet-runtime-3.1
5. dotnet --info
6. dotnet new webapi -o hello-world
7. cd hello-world
8. dotnet restore && dotnet run

## Issue (Problem)
```bash
⬢[dell@toolbox test]$ dotnet build
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/lib64/dotnet/sdk/3.1.108/NuGet.targets(123,5): error : '32 (Container Image)' is not a valid version string. (Parameter 'value') [/home/dell/Escritorio/webApi/Podman/test/test.csproj]

Build FAILED.

/usr/lib64/dotnet/sdk/3.1.108/NuGet.targets(123,5): error : '32 (Container Image)' is not a valid version string. (Parameter 'value') [/home/dell/Escritorio/webApi/Podman/test/test.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.40
```

# References
* [Crossref to netcore issue report](https://github.com/dotnet/core/issues/5224#issue-703934385)

**Comment by omajid** [comment]
With my Fedora .NET Core package maintainer hat on, the bug is not in `podman`. It probably can be worked around in `toolbox`. But the real culprit is .NET Core/msbuild, as I say in the linked .NET Core issue.

**Comment by vrothberg** [comment]
Thanks for opening and the issue! Based on the last comment, I will close the issue as it appears to be unrelated to Podman.
