### ISSUE TITLE
APIv2 pull: response body is different from the DOC

### ISSUE THREAD

**Issue by Edward5hen** [containers/podman#7686]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
/kind bug

**Description**
I just pull the latest code and build podman. When I use pull feature by APIv2, I got a different response body than the DOC says - http://docs.podman.io/en/latest/_static/api.html#operation/libpodImagesPull. I tried it this months ago, the result was following the DOC.

**Steps to reproduce the issue:**

1. start APIv2 service

2. curl -X POST http://localhost:$PORT/v1.40/libpod/images/pull\?reference\=quay.io/libpod/alpine_labels:latest

**Describe the results you received:**
```
# curl -X POST http://localhost:8082/v1.40/libpod/images/pull\?reference\=quay.io/libpod/alpine_labels:latest
{"stream":"Trying to pull quay.io/libpod/alpine_labels:latest...\n"}
{"stream":"Getting image source signatures\n"}
{"stream":"Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\n"}
{"stream":"Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\n"}
{"stream":"Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\n"}
{"stream":"Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\n"}
{"stream":"Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\n"}
{"stream":"Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\n"}
{"stream":"Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\n"}
{"stream":"Copying blob sha256:4fe2ade4980c2dda4fc95858ebb981489baec8c1e4bd282ab1c3560be8ff9bde\n"}
{"stream":"Copying blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4\n"}
{"stream":"Writing manifest to image destination\n"}
{"stream":"Storing signatures\n"}
{"images":["4fab981df737963d83b548a3a6f4e7b43f718eb88567ba5ec7921f636a93d7bc"]}
```

**Describe the results you expected:**
Months ago the result was:
{"id": "4fab981df737963d83b548a3a6f4e7b43f718eb88567ba5ec7921f636a93d7bc"}

**Comment by vrothberg** [comment]
@jwhonce PTAL

**Comment by jwhonce** [comment]
@Edward5hen My bad.  I'll have a PR soon to restore expected behavior and include the new Images field as well.
