### ISSUE TITLE
Can't upgrade podman from version 1.6.4 to newer version.

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/podman#7703]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
@greenpau

/kind bug

**Description**

I use the old podman version containing various bugs but  can't upgrade podman using dnf on CentOS8 in any way
**Steps to reproduce the issue:**

I have podman ver 1.6.4 installed on Centos 8.1 
1. My installed podman version check: 
dnf info podman.x86_64 shows 
Version      : 1.6.4
Release      : 10.module_el8.2.0+305+5e198a41
Architecture : x86_64
Source       : podman-1.6.4-10.module_el8.2.0+305+5e198a41.src.rpm
Repository   : @System

2. as is podman version - 1.6.4
3. dnf search podman.x86_64
No matches found.

**Describe the results you received:**

Can't upgrade to the newer version containing many issues correction, especially related to container networking and firewall backend. 
**Describe the results you expected:**
podman upgraded to the latest release for CentOS8.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.4
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module_el8.2.0+305+5e198a41.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: a2b11288060ebd7abd20e0b4eb1a834bbf0aec3e'
  Distribution:
    distribution: '"centos"'
    version: "8"

```
``

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**
No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Podman on CentOS8  WSL distro upgraded to:
  centos-gpg-keys-8.2-2.2004.0.2.el8.noarch            centos-release-8.2-2.2004.0.2.el8.x86_64            centos-repos-8.2-2.2004.0.2.el8.x86_64
My enabled distros are 

dnf repolist enabled:
repo id                                                                  repo name
AppStream                                                                CentOS-8 - AppStream
BaseOS                                                                   CentOS-8 - Base
extras                                                                   CentOS-8 - Extras


Github podman repository contains later versions for CentOS

**Comment by zhangguanzhang** [comment]
please try this
```
dnf -y module disable container-tools
dnf -y install 'dnf-command(copr)'
dnf -y copr enable rhcontainerbot/container-selinux
curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_8/devel:kubic:libcontainers:stable.repo
dnf -y install podman
```

**Comment by PavelSosin-320** [comment]
Thanks a lot! Upgraded to 2.0.6
