### ISSUE TITLE
Podman run error in non-root mode: "user namespaces are not enabled in /proc/sys/user/max_user_namespaces"

### ISSUE THREAD

**Issue by Poor12** [containers/podman#7704]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman run well in root-mode, however run error in non-root mode except --help.
Error is below: 
cannot clone: Invalid argument
user namespaces are not enabled in /proc/sys/user/max_user_namespaces
Error: could not get runtime: cannot re-exec process

**Steps to reproduce the issue:**

1.switch a normal user

2.run podman

**Describe the results you received:**
podman run error

**Describe the results you expected:**
podman run well

**Output of `podman info --debug`:**
cannot clone: Invalid argument
user namespaces are not enabled in /proc/sys/user/max_user_namespaces
Error: could not get runtime: cannot re-exec process

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**
Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Centos7 in Parallels Desktop. I am a newcomer to podman. Thanks for any help.

**Comment by AkihiroSuda** [comment]
CentOS 7 requires running `echo “user.max_user_namespaces=10000” > /etc/sysctl.d/42-rootless.conf` and `sysctl --system` as root

**Comment by TiloGit** [comment]
here my steps on RHEL. 

```console
[joedoe@myserver ]$ cat /proc/sys/user/max_user_namespaces
0
[joedoe@myserver ]$ sudo sysctl user.max_user_namespaces=15000
user.max_user_namespaces = 15000
[joedoe@myserver ]$ cat /proc/sys/user/max_user_namespaces
15000
[joedoe@myserver ]$ sudo usermod --add-subuids 200000-201000 --add-subgids 200000-201000 joedoe
[joedoe@myserver ]$ grep joedoe /etc/subuid /etc/subgid
/etc/subuid:joedoe:200000:1001
/etc/subgid:joedoe:200000:1001
```

**Comment by hjoukl** [comment]
Just for anyone stumbling upon this issue as a top search result like me: Here's some context and explanation on the previous fine answers: https://github.com/containers/podman/blob/master/docs/tutorials/rootless_tutorial.md

**Comment by Jeffy1992** [comment]
> CentOS 7 requires running `echo “user.max_user_namespaces=10000” > /etc/sysctl.d/42-rootless.conf` and `sysctl --system` as root

$ cat /proc/sys/user/max_user_namespaces
63907
