### ISSUE TITLE
unknown seccomp syscall `fchmodat2` ignored

### ISSUE THREAD

**Issue by cevich** [containers/podman#7713]
/kind bug

**Description**

In CI tests using freshly updated VM images, I'm seeing many `podman logs` test failures.  All of them seem to execute `podman run ...` fine, but the subsequent `podman logs` shows the error:

```unknown seccomp syscall `fchmodat2` ignored```

**Steps to reproduce the issue:**

1.  Execute CI tests using images with suffix c6106205175152640

**Describe the results you received:**

         Running: podman [options] run -dt docker.io/library/alpine:latest sh -c echo podman; echo podman; echo podman
         61f6b0726eae32b74769c573a1cdd336df9341e14f1788df587dedfe9271d170
         Running: podman [options] logs 61f6b0726eae32b74769c573a1cdd336df9341e14f1788df587dedfe9271d170
         unknown seccomp syscall `fchmodat2` ignored
         podman
         podman
         podman
         [AfterEach] Podman logs
           /var/tmp/go/src/github.com/containers/podman/test/e2e/logs_test.go:32
         Running: podman [options] stop -a --time 0
         61f6b0726eae32b74769c573a1cdd336df9341e14f1788df587dedfe9271d170
         Running: podman [options] pod stop -a -t 0
         Running: podman [options] pod rm -fa
         Running: podman [options] rm -fa
         61f6b0726eae32b74769c573a1cdd336df9341e14f1788df587dedfe9271d170

**Describe the results you expected:**

All tests should pass

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman system info`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-2.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 81d18b6c3ffc266abdef7ca94c1450e669a6a388'
  cpus: 2
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: journald
  hostname: cirrus-task-6527098196066304.c.libpod-218412.internal
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.8.10-200.fc32.x86_64
  linkmode: dynamic
  memFree: 2214621184
  memTotal: 4119330816
  ociRuntime:
    name: crun
    package: crun-0.14.1-5.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.14.1
      commit: 598ea5e192ca12d4f6378217d3ab1415efeddefa
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 31m 20.91s
registries:
  search:
  - docker.io
  - quay.io
  - registry.fedoraproject.org
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 0
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1600713190
  BuiltTime: Mon Sep 21 13:33:10 2020
  GitCommit: 9e10ace678b71da1713bf341e7f6838e2fc0e14d
  GoVersion: go1.14.9
  OsArch: linux/amd64
  Version: 2.1.0-dev
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Typical annotated results, this one is from Fedora 32 local (not remote): 

https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6527098196066304/html/integration_test.log.html#t--all-lines--2

**Comment by cevich** [comment]
This issue is most certainly the same as https://github.com/containers/crun/issues/496

**Comment by rhatdan** [comment]
I am removing fchmodat2 from seccomp.json in containers-common.

**Comment by cevich** [comment]
@rhatdan thanks, yep I'm watching.  Soon as that's ready and packaged, I can rebuild the images to incorporate it.

**Comment by rhatdan** [comment]
This is up2date now.  Closing.
