### ISSUE TITLE
podman/docker compatibility during volume creation

### ISSUE THREAD

**Issue by rsommer** [containers/podman#7740]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
When a named volume is created via docker and the volume does already exist, no error ist returned. podman on the other hand returns `Error: volume with name test already exists: volume already exists`

**Steps to reproduce the issue:**

docker:
```
$ docker volume create test
test
$ docker volume create test
test
```

podman:
```
$ podman volume create test
test
$ podman volume create test
Error: volume with name test already exists: volume already exists
```

**Describe the results you received:**
podman throws an error when the volume does already exist.

**Describe the results you expected:**
podman just "returns" the existing volume, being compatible to docker. The behaviour was discovered while trying to replace the docker daemon in gitlab ci. The cache volumes used by the gitlab runner are (re-)created using the same volume name, leading to the shown error.

**Output of `podman version`:**

```
Version:      2.1.0
API Version:  2.0.0
Go Version:   go1.14
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 2
  distribution:
    distribution: debian
    version: "10"
  eventLogger: journald
  hostname: cirunnertest01
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1221
      size: 1
    - container_id: 1
      host_id: 2459296
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1221
      size: 1
    - container_id: 1
      host_id: 2459296
      size: 65536
  kernel: 4.19.0-10-amd64
  linkmode: dynamic
  memFree: 209768448
  memTotal: 2066657280
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0~rc6+dfsg1
      commit: 1.0.0~rc6+dfsg1-3
      spec: 1.0.1
  os: linux
  remoteSocket:
    path: /run/user/1221/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.4
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 190300160
  swapTotal: 213905408
  uptime: 1h 4m 43.96s (Approximately 0.04 days)
version:
  APIVersion: 2.0.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.14
  OsArch: linux/amd64
  Version: 2.1.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/additional,now 2.1.0~1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Comment by rhatdan** [comment]
Do you think this is a bug in Docker? Does not see proper to not return an error when something already exists. I checked their man page and it does not mention this behaviour?

**Comment by rsommer** [comment]
The man page of `docker-volume-create` states: _Multiple containers can use the same volume in the same time period_ - so I would assume, that two or more containers could require that a specific volume exists and that it could be ok to call `create` again with the same name. I just came accross the difference in behaviour that renders the gitlab-runner useless when using the podman service  instead of the docker daemon.

**Comment by rhatdan** [comment]
Sure, but you could make the arguments about creating a directory.

mkdir /tmp
mkdir: cannot create directory ‘/tmp’: File exists

What happens in Docker if I change the options?

```
       -d, --driver="local"
           Specify volume driver name

       --label=
           Set metadata for a volume

       -o, --opt=map[]
           Set driver specific options
```

**Comment by rhatdan** [comment]
Does `docker network create`, `docker container create`, `docker config create`, `docker service create`
All work the same way?

**Comment by rsommer** [comment]
The behaviour is inconsistent. `docker network create` for example _does_ throw an error if the network already exists.

**Comment by rhatdan** [comment]
By any chance could you open an issue with Docker on this to get their opinion.

**Comment by rsommer** [comment]
[Docker issue/question](https://github.com/moby/moby/issues/41491)

**Comment by rsommer** [comment]
[There was already an older issue](https://github.com/moby/moby/issues/16068)

**Comment by mheon** [comment]
So Docker seem to be of the opinion that this behavior is not good and should be changed... Given that, I think we should document the difference and leave it, in the expectation that Docker will eventually change it.

**Comment by rhatdan** [comment]
@rsommer Interested in opening a PR to transfer.md?
