### ISSUE TITLE
Hot pausing containerized process to cut startup/init time

### ISSUE THREAD

**Issue by abitrolly** [containers/podman#7744]
/kind feature

**Description**

One shot container images are slow, because they don't cut initialization and warmup times. Especially for things like Python. It would be much more beneficial if the image could include the process that is already loaded into memory and did some initialization work on its own. The process that waits for the next external io operation to proceed. External io operation is anything that reaches out of container - accessing a volume or the network.

**Comment by rhatdan** [comment]
Why not have the container loaded and running python in sleep mode, then exec into the container and run your python commands, would this satisfy your needs?

First build an image with python installed and call it python.
```
# cat /tmp/Containerfile 
from fedora
run dnf -y install python
# podman build -t python /tmp
...

Now create a daemonized container called quickpython using this python, and have the container just go to sleep.

```
# podman run -d --rm --name quickpython python  python -c "import signal; signal.pause()"
```

Now exec into the container and run python, this should be fast since the python is already loaded into memory.
```
# time podman exec quickpython python -c "print('this should be faster')"
this should be faster

real	0m0.210s
user	0m0.109s
sys	0m0.076s
```
To compare it to running just the python image directly.
```
# time podman run python python -c "print('this should be slower')"
this should be slower

real	0m0.353s
user	0m0.177s
sys	0m0.156s
```
It looks lt is twice as fast, for this simple example.  Your mileage may vary.

**Comment by mheon** [comment]
I think this is also possible right now with checkpoint/restore - you'd checkpoint-export a container with a Python VM set up and idle, and then restore as many copies as you want from that snapshot, having them come back up in a good state to begin working.

**Comment by abitrolly** [comment]
Need to see how it can speed up https://github.com/heroku/heroku-buildpack-python

**Comment by rhatdan** [comment]
@abitrolly Have you tried any of these ideas?

**Comment by rhatdan** [comment]
I believe the suggested ideas are enough and have not heard a response.  Reopen if you have other ideas.

**Comment by abitrolly** [comment]
@rhatdan the idea with python in sleep mode is basically a proposal to run everything in a single container, which is a significant drawback.

@mheon how to do checkpoint/restore with `podman`?
```
✗ podman -h | grep check
  healthcheck Manage health checks on containers
```

**Comment by rhatdan** [comment]
Checkpoint and restore require rootful Podman.
```
# podman container checkpoint

# podman container restore
```

**Comment by rhatdan** [comment]
The sleep idea could be expanded to lot's of containers, no need to run a single version of it. Just run  multiple sleeping containers as a pool.

**Comment by abitrolly** [comment]
The sleep idea works, because Python libs are already loaded in memory when container is sleeping. My idea is to pause and make snapshot of the initial process while it is waiting for I/O. The missing part is how to checkpoint at the right moment.
