### ISSUE TITLE
events.log grows indefinitely and starves /run

### ISSUE THREAD

**Issue by yangm97** [containers/podman#7748]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

If your host has too much podman events before rebooting (i.e. a faulty container keeps restarting) eventually `/run/libpod/events/events.log` is going to fill up the whole `/run` mount and cause system instability.

**Steps to reproduce the issue:**

1. Have container managed by systemd with a restart policy of `always` to crash constantly with a short backoff. Simply generating a systemd unit which starts an existing container along with the following `override.conf` should be enough:

```
[Service]
Restart=always
RestartSec=3

[Unit]
StartLimitIntervalSec=0
```

2. Around `Scheduled restart job, restart counter is at 132701.` `events.log` should have filled up `/run` (`du` says mine used `43M`)

3.

**Describe the results you received:**

**Describe the results you expected:**
`events.log` should probably trim itself when it reaches a certain number of lines or when `/run` becomes too crowded.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 2.0.3
```

**Output of `podman info --debug`:**

```
host:
  arch: arm
  buildahVersion: 1.16.1
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 4
  distribution:
    distribution: debian
    version: "10"
  eventLogger: journald
  hostname: hubot
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.45-sunxi
  linkmode: dynamic
  memFree: 78196736
  memTotal: 516595712
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0~rc6+dfsg1
      commit: 1.0.0~rc6+dfsg1-3
      spec: 1.0.1
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 258293760
  uptime: 196h 18m 38.27s (Approximately 8.17 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 7
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 44
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/arm
  Version: 2.1.0

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing...
podman/unknown 2.1.0~1 amd64
podman/unknown 2.1.0~1 arm64
podman/unknown,now 2.1.0~1 armhf [installed]
podman/unknown 2.1.0~1 ppc64el

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Not tested latest but checked the guide.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Unfortunately the host got updated while I was writing this report, so I couldn't provide the the output for the two commands above with the version which reproduced the issue.
Host is an Orange Pi Zero running Armbian Buster.

**Comment by baude** [comment]
if your podman is built with systemd, you may find that using the `journald` event logger would handle this better? it can be set permanently in the containers.conf file.

**Comment by rhatdan** [comment]
@baude Should we limit the size of this file since it is temperal, say 10000 lines or something.

**Comment by baude** [comment]
imho, we should make systemd journal the default when it is built with that.  i dont think podman should manage the file. we are just appending and events are frequent.  this would be a huge perf hit i think.

**Comment by rhatdan** [comment]
Well we have the chance to change the default in fedora 33.

**Comment by baude** [comment]
final recommendation is to switch to journal for your event logger.  this can be done in containers.conf.

**Comment by baude** [comment]
the # in the events_logger line needs to be removed to activate it.  also, your podman binary needs to be built with system (iirc)
