### ISSUE TITLE
Detaching from container doesn't print newline

### ISSUE THREAD

**Issue by mohd-akram** [containers/podman#7751]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Run `podman run -it fedora /bin/bash`

2. Press `ctrl-p` `ctrl-q` to detach

**Describe the results you received:**

```
[root@6aef033eef57 /]# [user@host ~]$
```

**Describe the results you expected:**

```
[root@6aef033eef57 /]# read escape sequence
[user@host ~]$
```

**Additional information you deem important (e.g. issue happens only occasionally):**

On Docker, the additional message is printed to stderr.

**Output of `podman version`:**

```
2.0.6
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.1
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.19-1.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.19, commit: 5dce9767526ed27f177a8fa3f281889ad509fea7'
  cpus: 8
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: file
  hostname: razrlab-am
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.8.7-200.fc32.x86_64
  linkmode: dynamic
  memFree: 679784448
  memTotal: 15745339392
  ociRuntime:
    name: crun
    package: crun-0.14.1-5.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.14.1
      commit: 598ea5e192ca12d4f6378217d3ab1415efeddefa
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 2
  swapFree: 4345999360
  swapTotal: 7944007680
  uptime: 218h 43m 4.09s (Approximately 9.08 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/mohamed/.config/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 3
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/mohamed/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 4
  runRoot: /run/user/1000/containers
  volumePath: /home/mohamed/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1598988411
  BuiltTime: Tue Sep  1 23:26:51 2020
  GitCommit: ""
  GoVersion: go1.14.6
  OsArch: linux/amd64
  Version: 2.0.6
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.6-1.fc32.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical laptop.

**Comment by rhatdan** [comment]
Interested in opening a PR to fix this?

**Comment by mohd-akram** [comment]
How do I build without `make package-install` (I don't want to run sudo)?. I get this with `make`:

```
# Only generate the varlink code on Linux (see issue #4814).
GO111MODULE=off go generate ./pkg/varlink/...
../../vendor/github.com/varlink/go/cmd/varlink-go-interface-generator/main.go:12:2: cannot find package "github.com/varlink/go/varlink/idl" in any of:
        /usr/lib/golang/src/github.com/varlink/go/varlink/idl (from $GOROOT)
        /home/mohamed/Downloads/podman/_output/src/github.com/varlink/go/varlink/idl (from $GOPATH)
pkg/varlink/generate.go:3: running "go": exit status 1
make: *** [Makefile:646: pkg/varlink/iopodman.go] Error 1
```

**Comment by ParkerVR** [comment]
@mohd-akram I'll take a look at this.
It's not recommended to install podman without sudo privileges but you can consider using nix as in the guide 
https://podman.io/getting-started/installation and installing any failing dependencies manually.

**Comment by ParkerVR** [comment]
@mohd-akram I'm getting identical results in both Docker and Podman on both 2.0.6 and upstream. can you clarify what exactly you're seeing differently?

**Comment by mohd-akram** [comment]
It's described in the issue. What is the result you're getting?

**Comment by ParkerVR** [comment]
➜  ~ podman run -it fedora /bin/bash     
[root@1509726a4eeb /]# %                                                                  
➜  ~ sudo docker run -it fedora /bin/bash
[root@a6e4cffd2cea /]# %                                                                  
➜  ~

**Comment by mohd-akram** [comment]
Try this:

```
docker create -it --name fedora fedora
docker start fedora
docker attach fedora
<ctrl-p> <ctrl-q>
```

**Comment by rhatdan** [comment]
@ParkerVR Any progress on this?

**Comment by ParkerVR** [comment]
@rhatdan I made two PRs for this - one that is strictly the Docker compatible style and another that is internally consistent and prints a newline on detaches, let me know what you think

**Comment by rhatdan** [comment]
It is probably better we follow Docker.

**Comment by ParkerVR** [comment]
@rhatdan the non-docker edition got merged in. If you want the Docker style I can update that PR to undo the other change, otherwise I will continue with the current detach method and test on the other cases brought up
