### ISSUE TITLE
How to pass --cgroup-parent to podman container

### ISSUE THREAD

**Issue by psaini79** [containers/podman#7757]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I am testing my application with podman and trying to change the parent group mount point to /docker. By default, PODMAN provides /machine.slice/libpod-* but I want some other cgroup mount. I tried using the following but it is not working:

```
podman create \
  --hostname test1 \
  --cgroup-parent="/ol7" \
  --name test1 \
oraclelinux:7
```
The above command kept on failing. How can I change the cgroup parent mountpoint inside the container?

**Describe the results you received:**
It fails with the following error:
```
Error: did not receive systemd slice as cgroup parent when using systemd to manage cgroups: invalid argument
```

**Describe the results you expected:**
It should work with the different cgroup mount point. It works in docker and we can pass different parent cgroup to docker daemon but here podman doesn't have any daemon and not sure how can I pass --cgroup-parent?

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.12.9
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.9
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-4.0.1.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: '"ol"'
    version: "7.8"
  MemFree: 1425793024
  MemTotal: 16535801856
  OCIRuntime:
    package: runc-1.0.0-65.rc8.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 8589131776
  SwapTotal: 8589930496
  arch: amd64
  cpus: 2
  hostname: raconpodman
  kernel: 4.14.35-1902.305.4.el7uek.x86_64
  os: linux
  rootless: false
  uptime: 47h 32m 6.39s (Approximately 1.96 days)
registries:
  blocked: null
  insecure: null
  search:
  - container-registry.oracle.com
  - quay.io
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 1
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.4.4-4.0.1.el7.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

It is a virtual machine.

**Comment by psaini79** [comment]
Further update on this, I tried following and able to create the container but it is failing on start:

```
# podman create   --hostname test1  --cgroup-parent=/ol7  --cgroup-manager=cgroupfs --name test1   oraclelinux:7
a5819c3f7c22798473e8c334f59bad3f2b5d4b52b3cd94d7a4c4855cbb6d2db8
# podman start test1
Error: unable to start container "test1": container_linux.go:345: starting container process caused "process_linux.go:281: applying cgroup configuration for process caused \"Invalid slice name ol7\""
: OCI runtime error
```

**Comment by rhatdan** [comment]
@giuseppe @vrothberg PTAL

**Comment by giuseppe** [comment]
looks like we need `--cgroup-manager=cgroupfs` for both commands.  Can you try:

```
# podman --cgroup-manager=cgroupfs create ...
# podman --cgroup-manager=cgroupfs start -l
```

**Comment by psaini79** [comment]
I tried but it doesn't work. I am wondering do we need to create ol7 cgroup ? Isn't be created by podman?

```
#  podman --cgroup-manager=cgroupfs create   --hostname test1  --cgroup-parent=/ol7   --name test1   oraclelinux:7
1f459709dfbbf2ab27915b62c8270686691fe47e2e023f9cdaf03e75a41456d5
# podman start test1 --latest
unable to start container "test1": container_linux.go:345: starting container process caused "process_linux.go:281: applying cgroup configuration for process caused \"Invalid slice name ol7\""
: OCI runtime error
Error: unable to start container "1f459709dfbbf2ab27915b62c8270686691fe47e2e023f9cdaf03e75a41456d5": container_linux.go:345: starting container process caused "process_linux.go:281: applying cgroup configuration for process caused \"Invalid slice name ol7\""
: OCI runtime error
```

**Comment by psaini79** [comment]
@giuseppe 

It worked as per your suggestion:
```
podman --cgroup-manager=cgroupfs start -l test1
```

**Comment by psaini79** [comment]
@giuseppe 

Though I am able to start the container,  I still have some question. How do I set the cpu.rt_runtime_us to 950000 during the group creation because if  I pass --cpu-rt-runtime=95000 for test1,  the parent group doesn't have this value. With docker I was able to do it bt passing the --cpu-rt-runtime to docker-daemon and child cgroup can inherit the values from the parent cgroups.

For details, please check following:
```
# pwd
/sys/fs/cgroup/cpu,cpuacct/ol7
# cat cpu.rt_runtime_us 
0
```

Trying with another cgroup:
```
[root@raconpodman ol7]# podman --cgroup-manager=cgroupfs start -l test11
unable to start container "test11": container_linux.go:345: starting container process caused "process_linux.go:281: applying cgroup configuration for process caused \"failed to write 95000 to cpu.rt_runtime_us: write /sys/fs/cgroup/cpu,cpuacct/ol71/libpod-8dbbcbdacdcb6327b1e35dcdbf2d1b098cc893e1a5f3b78dc8f5ce4c3aa8b522/cpu.rt_runtime_us: invalid argument\""
: OCI runtime error
Error: unable to start container "8dbbcbdacdcb6327b1e35dcdbf2d1b098cc893e1a5f3b78dc8f5ce4c3aa8b522": container_linux.go:345: starting container process caused "process_linux.go:281: applying cgroup configuration for process caused \"failed to write 95000 to cpu.rt_runtime_us: write /sys/fs/cgroup/cpu,cpuacct/ol71/libpod-8dbbcbdacdcb6327b1e35dcdbf2d1b098cc893e1a5f3b78dc8f5ce4c3aa8b522/cpu.rt_runtime_us: invalid argument\""
: OCI runtime error
```

**Comment by rhatdan** [comment]
@giuseppe Could you answer the question so we can close this issue?

**Comment by giuseppe** [comment]
I don't think you can do it directly from Podman.  If you want to configure the parent cgroup, you'd have to do it manually.

**Comment by devon6686** [comment]
how to work in centos8 podman run with cgroup-parent option?

# podman run --replace --name cg-redis -itd --cgroup-parent=/cgtest --rm -p 16379:6379 docker.io/library/redis --appendonly yes
Error: did not receive systemd slice as cgroup parent when using systemd to manage cgroups: invalid argument

➜  cgtest podman info
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-1.el8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: b20060e9d24f226e29d57d8be99bbba7a94fa0e9-dirty'
  cpus: 32
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: journald
  hostname: k8s
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.9.11-1.el8.elrepo.x86_64
  linkmode: dynamic
  memFree: 57501433856
  memTotal: 67444662272
  ociRuntime:
    name: runc
    package: runc-1.0.0-145.rc91.git24a3cf8.el8.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 21474832384
  swapTotal: 21474832384
  uptime: 144h 20m 43.32s (Approximately 6.00 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 15
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1606223637
  BuiltTime: Tue Nov 24 21:13:57 2020
  GitCommit: ""
  GoVersion: go1.13.15
  OsArch: linux/amd64
  Version: 2.2.0-rc2

**Comment by mheon** [comment]
If you are not using systemd-managed slices as the cgroup parent you need to use the `cgroupfs` cgroup manager (`--cgroup-manager=cgroupfs`).

**Comment by rhatdan** [comment]
Since the question was answered I am closing.  If this is still a problem please reopen.
