### ISSUE TITLE
Unable to assign a network to a running container

### ISSUE THREAD

**Issue by psaini79** [containers/podman#7771]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I  am testing our APP on podman and I am not finding a way to attach and detach a network to a container.

I am able to specify the network during the container creation but unable to attach a network to the running container. It used to work with docker using the command docker network attach but didn't find a way for containers running with a PODMAN.

If I try the command `podman help network', it throws the following message:
```
# podman help network
Unknown help topic [`network`]
Usage:
  podman [flags]
  podman [command]
```

**Describe the results you received:**
Unable to attach the network to the running container.

**Describe the results you expected:**
We should be able to attach the network to a running container or already created container.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:            1.4.4
RemoteAPI Version:  1
Go Version:         go1.12.9
OS/Arch:            linux/amd64

```

**Output of `podman info --debug`:**

```
debug:
  compiler: gc
  git commit: ""
  go version: go1.12.9
  podman version: 1.4.4
host:
  BuildahVersion: 1.9.0
  Conmon:
    package: podman-1.4.4-4.0.1.el7.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 0.3.0, commit: unknown'
  Distribution:
    distribution: '"ol"'
    version: "7.8"
  MemFree: 13915369472
  MemTotal: 16535801856
  OCIRuntime:
    package: runc-1.0.0-65.rc8.el7.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 8589131776
  SwapTotal: 8589930496
  arch: amd64
  cpus: 2
  hostname: raconpodman
  kernel: 4.14.35-1902.305.4.el7uek.x86_64
  os: linux
  rootless: false
  uptime: 73h 54m 19.03s (Approximately 3.04 days)
registries:
  blocked: null
  insecure: null
  search:
  - container-registry.oracle.com
  - quay.io
  - docker.io
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 2
  GraphDriverName: overlay
  GraphOptions: null
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 2
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes


```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-1.4.4-4.0.1.el7.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It is a virtual machine.

**Comment by mheon** [comment]
This feature is not presently supported. I'd like to do a rewrite of our `podman network` commands at some point to enable this and other things, but that will likely not happen for some time. Re-tagging as feature request given this.

**Comment by rhatdan** [comment]
Still hoping for this in the future.

**Comment by mheon** [comment]
The work we are doing now on network aliases lays the groundwork for `network connect` and `network disconnect`

**Comment by rhatdan** [comment]
@mheon Any progress on this?

**Comment by mheon** [comment]
`network connect` and `network disconnect` have merged.
