### ISSUE TITLE
Allow manual rootless operation when running as UID 0

### ISSUE THREAD

**Issue by maybe-sybr** [containers/podman#7774]
/kind feature

**Description**
At the moment, if EUID is 0, podman will decide it should run in rootful mode. When running user namespaces not related to podman, this is the wrong choice and it would be nice if I could tell podman about this explicitly. At the moment we can do:

```sh
$ _CONTAINERS_ROOTLESS_UID=1337 _CONTAINERS_USERNS_CONFIGURED=true podman <commands>
```

but this isn't very friendly and almost certainly undocumented since I found it by grepping the source.

**Steps to reproduce the issue:**

1. Check some stuff as yourself
```sh
[maybe@zen tmp]$ podman info | grep configFile
  configFile: /home/maybe/.config/containers/storage.conf
[maybe@zen tmp]$ podman run --rm -ti docker.io/alpine echo hello
hello
```

2. Do the same after unsharing the user namespace
```sh
[maybe@zen tmp]$ unshare -U
[nobody@zen tmp]$ podman info | grep configFile
cannot clone: Operation not permitted
cannot clone: Operation not permitted
ERRO[0000] cannot re-exec process
[nobody@zen tmp]$ podman run --rm -ti docker.io/alpine echo hello
cannot clone: Operation not permitted
cannot clone: Operation not permitted
ERRO[0000] cannot re-exec process
[nobody@zen tmp]$ logout
```

3. Try again after mapping the root user to yourself too. This fails because we can't do mount things even after we trick podman into running rootless.

```sh
[maybe@zen tmp]$ unshare -U --map-root-user
[root@zen tmp]# podman info | grep configFile
Error: error creating runtime static files directory /var/lib/containers/storage/libpod: mkdir /var/lib/containers/storage/libpod: permission denied
[root@zen tmp]# podman run --rm -ti docker.io/alpine echo hello
Error: error creating runtime static files directory /var/lib/containers/storage/libpod: mkdir /var/lib/containers/storage/libpod: permission denied
[root@zen tmp]# _CONTAINERS_ROOTLESS_UID=1337 _CONTAINERS_USERNS_CONFIGURED=true podman info | grep configFile
Error: mount /home/maybe/.local/share/containers/storage/overlay:/home/maybe/.local/share/containers/storage/overlay, flags: 0x1000: operation not permitted
[root@zen tmp]# _CONTAINERS_ROOTLESS_UID=1337 _CONTAINERS_USERNS_CONFIGURED=true podman run --rm -ti docker.io/alpine echo hello
Error: mount /home/maybe/.local/share/containers/storage/overlay:/home/maybe/.local/share/containers/storage/overlay, flags: 0x1000: operation not permitted
[root@zen tmp]# logout
```
4. But if we also unshare the mount namespace, we can run after telling podman we're rootless. We can't get info of other running containers and it spits out an error about FS magic, so maybe that could be silenced too?

```sh
[maybe@zen tmp]$ unshare -U --map-root-user -m
[root@zen tmp]# _CONTAINERS_ROOTLESS_UID=1337 _CONTAINERS_USERNS_CONFIGURED=true podman info | grep configFile
ERRO[0000] error joining network namespace for container 30a063d3e3b12d1d3b06637d94caabcc05749832d6ec622aff869466d62e2b12: error retrieving network namespace at /run/user/1337/netns/cni-1cda6035-7a66-2dd7-6ec7-31f93eb92127: unknown FS magic on "/run/user/1337/netns/cni-1cda6035-7a66-2dd7-6ec7-31f93eb92127": 1021994
  configFile: /home/maybe/.config/containers/storage.conf
[root@zen tmp]# _CONTAINERS_ROOTLESS_UID=1337 _CONTAINERS_USERNS_CONFIGURED=true podman run --rm -ti docker.io/alpine echo hello
hello
```

**Describe the results you received:**
Has to use internal env vars

**Describe the results you expected:**
Would like a single external env var

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by maybe-sybr** [comment]
My specific situation is that I'm doing some namespace hopping with rootlesskit to run stuff in sub-namespaces.

**Comment by rhatdan** [comment]
Can you manually do this using --uidmap and --gidmap?

**Comment by giuseppe** [comment]
Would help if we teach `podman unshare` how to handle this case?  Something like `podman unshare --current`?

**Comment by maybe-sybr** [comment]
@rhatdan - I don't think that does anything to help unfortunately. Regardless of what UID/GID mapping we use, podman has still decided that it's rootful by the point and attempts to use the default (non-`XDG_CONFIG_PATH`) config files. Here's some output of things I just tried:
```sh
$ podman run --rm -ti --uidmap host --gidmap host docker.io/alpine echo hello
Error: error creating runtime static files directory /var/lib/containers/storage/libpod: mkdir /var/lib/containers/storage/libpod: permission denied
$ podman run --rm -ti --uidmap 0:0:65535 --gidmap 0:0:65535 docker.io/alpine echo hello
Error: error creating runtime static files directory /var/lib/containers/storage/libpod: mkdir /var/lib/containers/storage/libpod: permission denied
```

@giuseppe - I didn't know about `podman unshare`, that's really cool. In my case I don't think I could use it as it is currently provided since I need to unshare the network namespace as well, and I can't use it once I'm in my sub-namespace because podman again decides that it's rootful before actually doing any of its business. The problem isn't so much that podman uses an incorrect namespace or UID/GID map once it gets going - in fact I wouldn't want containers to use the current namespace IIUC what you are be suggesting, I'd want them to run in a sub-sub-namespace - it's just that it fails to understand that even though UID==0, it's not rootful in this case.

**Comment by rhatdan** [comment]
Your examples above are launching a rootless container?  I thought the complaint was trying to run a rootfull container?

**Comment by maybe-sybr** [comment]
No, sorry if I wasn't clear on that @rhatdan. The issue is with starting a rootless container when I am in a user namespace where UID 0 in that namespace is mapped to my UID in the main namespace. The exact problem is around podman's logic around making the inference about whether it is running rootless or rootful. Specifically this snippet doesn't meet my (admittedly weird) use case:

https://github.com/containers/podman/blob/f48b1639348da2e398c4e30e10f542dec02c69d5/pkg/rootless/rootless_linux.go#L53-L72

By setting `_CONTAINERS_USERNS_CONFIGURED` to some non-empty string I'm convincing that function that it is running in rootless mode even though EUID is 0 in my root-mapped user namespace.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
from a user point of view, would be fine to require using `podman unshare` to create the "rootless" environment?  It would make it clearer the user asked for it and we don't do any sort of detection based on the capabilities we have.

**Comment by maybe-sybr** [comment]
For me, it wouldn't be acceptable because I need to do stuff with network namespaces which AFAICT `podman unshare` doesn't let me do. I'd be happy to mimic some non-hidden variables and wear the cost of  ensuring that I set up the NS such that podman can actually function though.

**Comment by giuseppe** [comment]
> For me, it wouldn't be acceptable because I need to do stuff with network namespaces which AFAICT `podman unshare` doesn't let me do. I'd be happy to mimic some non-hidden variables and wear the cost of ensuring that I set up the NS such that podman can actually function though.

Is your process already running with all the needed capabilities?  Don't you already need to create a new user namespace for gaining them?

**Comment by maybe-sybr** [comment]
Yep, my namespace is basically `unshare -Urnm`. If there's a trapdoor to make `podman` behave nicely in that environment, I'd be happy. This currently works but is clunky and I wouldn't want to rely on it working in future since the env var names are underscored:
```sh
$ unshare -Urnm env _CONTAINERS_ROOTLESS_UID=${UID} _CONTAINERS_USERNS_CONFIGURED=true podman run --rm hello-world
...
```

**Comment by maybe-sybr** [comment]
I've also noticed that if I don't have a `~/.config/container/policy.json`, `podman` will explode like so if I need to pull the image:
```
INFO[0000] podman filtering at log level debug
DEBU[0000] Called run.PersistentPreRunE(podman --log-level debug run -d --rm registry.lan:5000/some/repository)
DEBU[0000] Ignoring libpod.conf EventsLogger setting "/home/maybe/.config/containers/containers.conf". Use "journald" if you want to change this setting and remove libpod.conf files.
DEBU[0000] Reading configuration file "/usr/share/containers/containers.conf"
DEBU[0000] Merged system config "/usr/share/containers/containers.conf": &{{[] [] containers-default-0.14.10 [] private enabled [CAP_AUDIT_WRITE CAP_CHOWN CAP_DAC_OVERRIDE CAP_FOWNER CAP_FSETID CAP_KILL CAP_MKNOD CAP_NET_BIND_SERVICE CAP_NET_RAW CAP_SETFCAP CAP_SETGID CAP_SETPCAP CAP_SETUID CAP_SYS_CHROOT] [] []  [] [] [] false [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin TERM=xterm] false false false  private k8s-file -1 slirp4netns false 2048 private /usr/share/containers/seccomp.json 65536k private host 65536} {true systemd [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] [/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon] ctrl-p,ctrl-q true /run/user/1337/libpod/tmp/events/events.log file [/usr/share/containers/oci/hooks.d] docker:// /pause k8s.gcr.io/pause:3.2 /usr/libexec/podman/catatonit shm   false 2048 /usr/bin/crun map[crun:[/usr/bin/crun /usr/sbin/crun /usr/local/bin/crun /usr/local/sbin/crun /sbin/crun /bin/crun /run/current-system/sw/bin/crun] kata:[/usr/bin/kata-runtime /usr/sbin/kata-runtime /usr/local/bin/kata-runtime /usr/local/sbin/kata-runtime /sbin/kata-runtime /bin/kata-runtime /usr/bin/kata-qemu /usr/bin/kata-fc] runc:[/usr/bin/runc /usr/sbin/runc /usr/local/bin/runc /usr/local/sbin/runc /sbin/runc /bin/runc /usr/lib/cri-o-runc/sbin/runc /run/current-system/sw/bin/runc]] missing false    map[] [] [crun runc] [crun] [kata kata-runtime kata-qemu kata-fc] {false false false false false false} /home/maybe/.config/containers/policy.json false 3 /home/maybe/.local/share/containers/storage/libpod 10 /run/user/1337/libpod/tmp /home/maybe/.local/share/containers/storage/volumes} {[/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin] podman /etc/cni/net.d/}}
DEBU[0000] Using conmon: "/usr/bin/conmon"
DEBU[0000] Initializing boltdb state at /home/maybe/.local/share/containers/storage/libpod/bolt_state.db
DEBU[0000] Using graph driver overlay
DEBU[0000] Using graph root /home/maybe/.local/share/containers/storage
DEBU[0000] Using run root /run/user/1337/containers
DEBU[0000] Using static dir /home/maybe/.local/share/containers/storage/libpod
DEBU[0000] Using tmp dir /run/user/1337/libpod/tmp
DEBU[0000] Using volume path /home/maybe/.local/share/containers/storage/volumes
DEBU[0000] Set libpod namespace to ""
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] overlay: mount_program=/usr/bin/fuse-overlayfs
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=false, usingMetacopy=false
DEBU[0000] Initializing event backend file
DEBU[0000] using runtime "/usr/bin/runc"
DEBU[0000] using runtime "/usr/bin/crun"
WARN[0000] Error initializing configured OCI runtime kata: no valid executable found for OCI runtime kata: invalid argument
DEBU[0000] using runtime "/usr/bin/crun"
INFO[0000] Setting parallel job count to 25
DEBU[0000] parsed reference into "[overlay@/home/maybe/.local/share/containers/storage+/run/user/1337/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]registry.lan:5000/some/repository:latest"
DEBU[0000] reference "[overlay@/home/maybe/.local/share/containers/storage+/run/user/1337/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]registry.lan:5000/some/repository:latest" does not resolve to an image ID
DEBU[0000] parsed reference into "[overlay@/home/maybe/.local/share/containers/storage+/run/user/1337/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]registry.lan:5000/some/repository:latest"
Error: unable to pull registry.lan:5000/some/repository: open /home/maybe/.config/containers/policy.json: no such file or directory
```

I was able to sidestep it by copying the system-wide `policy.json` into the appropriate place but it would be nice if that wasn't necessary.

**Comment by giuseppe** [comment]
my suggestion is to make `podman unshare` do the equivalent of `unshare -Urm` (differently than your command, there is no new network namespace created) and set the environment variables.

**Comment by maybe-sybr** [comment]
> my suggestion is to make `podman unshare` do the equivalent of `unshare -Urm` (differently than your command, there is no new network namespace created) and set the environment variables.

As in you're suggesting that I do that, or suggesting that's the change you'd look to make to `podman unshare`? It already does that AFAICT and I'd most likely rather just use the hidden environment variables in my own codebase than alter my `unshare` command in scripts which I'd like to eventually upstream to Akihiro in rootlesskit where it wouldn't be sensible to use.

I could make my scripts accept a custom `unshare` command to run, but then I'd need to do a second `unshare -n` anyway, so it'd be kind of pointless to do so unless `podman unshare` learns to create new network namespaces. I can explain my use case more exactly if that would help you?

**Comment by giuseppe** [comment]
> I could make my scripts accept a custom `unshare` command to run, but then I'd need to do a second `unshare -n` anyway, so it'd be kind of pointless to do so unless `podman unshare` learns to create new network namespaces. I can explain my use case more exactly if that would help you?

`podman unshare` should also ensure you will re-join the same user+mount namespace once one was created.  The issue with `unshare -c` is that it creates a different user namespace each time, so you might not be able to access/manage containers created in a different user namespace by a different `unshare -r` command.

**Comment by rhatdan** [comment]
@maybe-sybr @giuseppe Any movement on this?

**Comment by maybe-sybr** [comment]
Not AFAIK. I've been continuing to use the workaround from above.

**Comment by rhatdan** [comment]
@giuseppe Any chance you could work on this?

**Comment by giuseppe** [comment]
I am still unsure how to support it in a more generic way.  If we implement the idea I've described above, then it works only if all the podman commands are executed as part of that `podman unshare` session.  It won't be possible to use podman from another environment.

**Comment by rhatdan** [comment]
Would it make more sense to just `su 1337 - podman ...`?

**Comment by rhatdan** [comment]
Since I have not heard response, I am going to close this issue.  If more discussion is necessary please reopen.
