### ISSUE TITLE
podman pod stats failing to run on Ubuntu 20.04.1 on WSL2

### ISSUE THREAD

**Issue by Persistent13** [containers/podman#7775]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Running `podman pod stats POD_ID_HERE` returns the error `Error: pod stats is not supported in rootless mode without cgroups v2` but to my understanding cgroups v2 is already enabled for my installation of Ubuntu.

**Steps to reproduce the issue:**

1. Install podman

2. Play a K8s Pod or Deployment YAML file

3. Run `podman pod stats POD_ID_HERE`

**Describe the results you received:**

`Error: pod stats is not supported in rootless mode without cgroups v2`

**Describe the results you expected:**

Pod stats

**Additional information you deem important (e.g. issue happens only occasionally):**

I am running Ubuntu 20.04.1 on WSL2 and to my understanding cgroups v2 is enabled.

```
$ grep cgroup /proc/filesystems
nodev   cgroup
nodev   cgroup2
```

The command `sudo mount -t cgroup2 none /data` runs just fine.

**Output of `podman version`:**

```
Version:      2.1.0
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Wed Dec 31 17:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 8
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: file
  hostname: DESKTOP-6LCTTUI
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.19.104-microsoft-standard
  linkmode: dynamic
  memFree: 15924731904
  memTotal: 26868047872
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: 3e46dd849fdf6bfa68127786e073318184641f05
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /tmp/run-1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.4
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 7516192768
  swapTotal: 7516192768
  uptime: 106h 4m 54.27s (Approximately 4.42 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/dakota/.config/containers/storage.conf
  containerStore:
    number: 8
    paused: 0
    running: 1
    stopped: 7
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/dakota/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 4
  runRoot: /tmp/run-1000/containers
  volumePath: /home/dakota/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 0
  BuiltTime: Wed Dec 31 17:00:00 1969
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.1.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ apt list podman
Listing... Done
podman/unknown,now 2.1.0~1 amd64 [installed]
podman/unknown 2.1.0~1 arm64
podman/unknown 2.1.0~1 armhf
podman/unknown 2.1.0~1 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes, I am on the latest version as of writing this issue and I don't think I saw anything applicable to this error in the troubleshooting guide.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows 10 2004 OS Build 19041.508

```
PS > wsl --list --all --verbose
  NAME                   STATE             VERSION
* Ubuntu                 Running         2
```

**Comment by vrothberg** [comment]
Thanks for reaching out!

`podman info` claims that you're running cgroups v1 so I fear there's not much we can do.

**Comment by mheon** [comment]
You may be running "hybrid mode" in which cgroups v1 and v2 are both available. Podman only supports native cgroups v2, however.

**Comment by benyaminl** [comment]
WSL2 Require cgroup v1 to be enabled, so we can't disable it. sad. 
https://github.com/microsoft/WSL/issues/6662

**Comment by AdsonCicilioti** [comment]
Same problem with Podman on WSL

**Comment by rorshik** [comment]
Same problem with Podman on WSL. 
I turned off the hybrid mode, tried various methods and tips that are available on the Internet for this request, nothing helps. The surprising thing is that the problem has been around since 2020
[wsl2]
kernelCommandLine=systemd.unified_cgroup_hierarchy=1 cgroup_no_v1=all
The problem is urgent, there is no solution for me

**Comment by rorshik** [comment]
https://github.com/containers/podman/blob/main/troubleshooting.md 
Item 16. I understand that in this this solution will only work fedora does not support cgroup v2
And then how to change the distribution to another one in WSL? fedora by default
