### ISSUE TITLE
F33 podman stats with cgroupfs broken

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#7779]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Steps to reproduce the issue:**

1. podman run --rm -d --cgroup-manager=cgroupfs docker.io/alpine sleep 666

2. podman stats -l

**Describe the results you received:**

podman (master) $ podman stats -l
Error: unable to obtain cgroup stats: open /sys/fs/cgroup/user-1000.slice/user@1000.service/user.slice/libpod_parent/libpod-d9b0700a382b6ed6b95ea0c2031dfd82c9430d696e98ab2a6d9c725323754e23.scope/memory.current: open /sys/fs/cgroup/user-1000.slice/user@1000.service/user.slice/libpod_parent/libpod-d9b0700a382b6ed6b95ea0c2031dfd82c9430d696e98ab2a6d9c725323754e23.scope/memory.current: no such file or directory

**Comment by vrothberg** [comment]
The path is different:
* `/sys/fs/cgroup/user.slice/user-1000.slice/` exists on F33
* `/sys/fs/cgroup/user-1000.slice/` what Podman looks at

**Comment by vrothberg** [comment]
Got it. For some reason podman beliefs the container is running under systemd.

**Comment by vrothberg** [comment]
Took me a while to wrap my head around the issue.

To clarify: the upper example is failing as we're not storing the cgroup manager per container but in the engine's config. Hence, we need to use `--cgroup-manager=cgroupfs` for `podman stats` as well.

When doing that, we get the following error (which aligns with the failures from the e2e stats tests):
unable to obtain cgroup stats: open /sys/fs/cgroup/libpod_parent/libpod-c91f034f7c8cb248713db8afcb35ffab59870e2f0a0b98d0434c8d29c232cbc4/memory.current

**Comment by vrothberg** [comment]
Does not happen on cgroupsv2 (root). @giuseppe I think that's something for you

**Comment by vrothberg** [comment]
Rootless we're just not creating the paths and I don't yet know why.

**Comment by giuseppe** [comment]
> Rootless we're just not creating the paths and I don't yet know why.

rootless cannot create paths with cgroupfs.  It has not enough privileges for doing it

**Comment by vrothberg** [comment]
I have no idea how `test/e2e/stats_test.go` is then passing rootless because it's always on cgroupfs.
