### ISSUE TITLE
In Fedora we have dropped CAP_AUDIT_WRITE, which is causing issues in seccomp.json

### ISSUE THREAD

**Issue by rhatdan** [containers/podman#7781]
podman run ping ping 4.2.2.2
Error: container_linux.go:346: starting container process caused "error adding seccomp rule for syscall socket: permission denied": OCI runtime permission denied error

The default seccomp.json file is broken, if you remove the CAP_AUDIT_WRITE capability.

**Comment by rhatdan** [comment]
@giuseppe Seems something in your seccomp.json files is broken.

**Comment by giuseppe** [comment]
the error is coming from runc, what version are you using?

**Comment by rhatdan** [comment]
rpm -qf /bin/runc
containerd.io-1.2.10-3.2.fc31.x86_64

runc --version
runc version 1.0.0-rc8+dev
commit: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
spec: 1.0.1-dev

**Comment by rhatdan** [comment]
Ok I updated runc and now it works.  How do we get moby to update its version of runc or to use the system default?  Would docker work with the current version?

**Comment by lsm5** [comment]
@olivierlemasle ping, I see you're the current moby-engine maintainer. PTAL ^

**Comment by rhatdan** [comment]
I opened a bugzilla against Moby in Fedora to either use the packaged version of runc like every other package or to embed the specific version of runc required by moby in a moby private directory. /usr/libexec/moby/runc or something like that.

**Comment by olivierlemasle** [comment]
As I wrote on the bugzilla ticket, runc is not packaged by Fedora package moby-engine (actually since I took over moby-engine).

You mention [here](https://github.com/containers/podman/issues/7781#issuecomment-699051416) a package containerd.io-1.2.10-3.2.fc31.x86_64; there's no package named `containerd.io` in Fedora and it seems it did not exist in Fedora 31 either, so I guess it was installed from another source? :man_shrugging:

**Comment by rhatdan** [comment]
Ok, then I got it from upstream.  Sorry about that.

**Comment by rahbal** [comment]
Experiencing same issue. Any working solution on Fedora 33 ?
```
Error: unable to start container 83e4d20fdd5e43fb9ee85f32c6efe4b2ff7c01f02e7b092199d0081ef6fba894: container_linux.go:349: starting container process caused "error adding seccomp rule for syscall socket: permission denied": OCI permission denied

```

**Comment by mheon** [comment]
Switch to the crun OCI runtime. The runc package on Fedora is not very well
maintained because most Fedora users are on cgroups v2 and crun.

**Comment by natiiix** [comment]
@mheon How does one set that permanently? Is there a config file to set the default runtime somewhere? When I run podman with `--runtime /usr/bin/crun`, it works fine, but when I try to build my image without it, I get the same error as OP. Is there something incorrectly configured in my system that doesn't use cgroups V2 and therefore podman doesn't default to crun?

**Comment by mheon** [comment]
Copy /use/share/containers/containers.conf to /etc/containers and then set
the ‘runtime’ field in the copied file to crun.
