### ISSUE TITLE
Groups do not seem to be getting assigned by default in rootless mode versus rootful mode.

### ISSUE THREAD

**Issue by rhatdan** [containers/podman#7782]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

$ podman (pullpolicy) $ sudo podman run --rm alpine id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
$ podman (pullpolicy) $ podman run --rm alpine id
uid=0(root) gid=0(root)

**Comment by rhatdan** [comment]
@giuseppe @mheon @vrothberg Ideas?

**Comment by giuseppe** [comment]
we are not setting additional gids for rootless: https://github.com/containers/podman/blob/master/libpod/container_internal_linux.go#L417-L422

I think the reason is that it won't work when there are no multiple gids available, or not enough to cover all the additional gids

**Comment by rhatdan** [comment]
You are saying that if the range of GIDs  is not mapped into the user namespace?  If so should we make this smarter and allow it to check the range of UIDs and make sure they will work and not blow up the container, then warn about missing gids.
