### ISSUE TITLE
[APIv2] the url of list volume is not correct

### ISSUE THREAD

**Issue by yuhuijiang** [containers/podman#7794]
/kind bug

**Description**

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Comment by yuhuijiang** [comment]
The url of list volume is not correct. It should be be "volumes/json", but in the doc(http://docs.podman.io/en/latest/_static/api.html#operation/listVolumes), it's "volumes"

**Comment by Luap99** [comment]
The Podman API provides two endpoints:
1. The docker compatible endpoint `/volumes` (https://docs.docker.com/engine/api/v1.40/#operation/VolumeList) (http://docs.podman.io/en/latest/_static/api.html#operation/listVolumes)
2. The libpod endpoint `/libpod/volumes/json` (http://docs.podman.io/en/latest/_static/api.html#operation/libpodListVolumes)

I think it is correctly documented.

**Comment by vrothberg** [comment]
Thanks for reaching out, @yuhuijiang, and for providing all the information, @Luap99!

I am closing the issue as `/volumes` refers to the Docker compat endpoint.
