### ISSUE TITLE
[APIv2] the parameter of create volume is not correct

### ISSUE THREAD

**Issue by yuhuijiang** [containers/podman#7795]
-->

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
the parameter of create a volume with spcific label is not correct, the parameter should be "Label", but in the doc(http://docs.podman.io/en/latest/_static/api.html#operation/createVolume), the parameter is "Labels"

**Steps to reproduce the issue:**

1. podman system service --timeout 0 tcp:127.0.0.1:8080

2. curl -X POST -H 'Content-type: application/json' -d '{"Name":"test01","Label":{"testlabel":"testvalue"}}' http://localhost:8080/v1.40/libpod/volumes/create

3. curl -X POST -H 'Content-type: application/json' -d '{"Name":"test02","Labels":{"testlabel":"testvalue"}}' http://localhost:8080/v1.40/libpod/volumes/create

**Describe the results you received:**
Step 2 could create a volume with specific label, but step 3, the label of volume is null.

**Comment by Luap99** [comment]
This is the documentation for the libpod endpoint: http://docs.podman.io/en/latest/_static/api.html#operation/libpodCreateVolume
You are looking at the docs for the docker compatible endpoint.
