### ISSUE TITLE
race: remote,rootless: podman network create followed by run

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#7808]
I've seen this one twice so far:
```console
$ podman-remote network create --subnet 172.16.206.0/24 testnet-TrgvHhKQAK
/etc/cni/net.d/testnet-TrgvHhKQAK.conflist
$ podman-remote run --rm --network testnet-TrgvHhKQAK quay.io/libpod/testimage:20200917 ip a
Error: error preparing container 8efdbe7260f5e082c2a256ee0781a23fecbcd0776d5ac1b43d924d39cfae5086 for attach: error configuring network namespace for container 8efdbe7260f5e082c2a256ee0781a23fecbcd0776d5ac1b43d924d39cfae5086: CNI network "testnet-TrgvHhKQAK" not found
[ rc=127 (** EXPECTED 0 **) ]
```

Log: [from PR 7803, ubuntu remote](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4668854372663296/html/system_test.log.html)

Again, I'm not going to spend any time right now trying to reproduce (acting on the assumption that this will be an easy one to track down). I will try to keep track of flake occurrences and log them here.

**Comment by edsantiago** [comment]
I wonder if the race is in CNI? And I wonder if this is related? It's a very frequent flake in `podman network rm`, the classic symptom being:
```
Running: podman [options] network ls --quiet
podman-integrationtest
Running: podman [options] network rm podman-integrationtest
podman-integrationtest
Running: podman [options] network ls --quiet
podman-integrationtest
remove /home/some18764dude/.config/cni/net.d/eaac2f093ac23f24b699d68d1118f986b8620b03e3d5974e14c12147e06dfdab.conflist: no such file or directory
```
Recent instances (all one-offs, no triplets which cause a complete CI abort):

Podman network [It] podman network rm
* fedora : in-podman fedora
  * PR #7676
    * [09-17 13:05](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6365935319646208/html/integration_test.log.html#t--podman-network-rm--1)
* fedora : special_testing_rootless
  * PR #7777
    * [09-25 04:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4733700711645184/html/integration_test.log.html#t--podman-network-rm--1)
* fedora : test fedora
  * PR #7621
    * [09-16 08:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4768884966293504/html/integration_test.log.html#t--podman-network-rm--1)
* prior-fedora : test prior-fedora
  * PR #7729
    * [09-22 13:56](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6368645309792256/html/integration_test.log.html#t--podman-network-rm--1)
* ubuntu : test ubuntu
  * PR #7761
    * [09-23 17:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4826825551511552/html/integration_test.log.html#t--podman-network-rm--1)
* ubuntu-19 : test ubuntu-19
  * PR #7335
    * [08-25 08:56](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4504263864877056/html/integration_test.log.html#t--podman-network-rm--1)

Apologies in advance if this is unrelated.

**Comment by Luap99** [comment]
@edsantiago The tests are run in parallel, right?

**Comment by edsantiago** [comment]
@Luap99 I cannot answer that with confidence, but yes, I believe so.

**Comment by baude** [comment]
correct. in parallel depending on the run itself. i think remote tests are not in parallel.

**Comment by rhatdan** [comment]
@edsantiago @Luap99 Is this still an issue?

**Comment by edsantiago** [comment]
The last two incidents reported by cirrus-flake-summarize are on 09-29:

* prior-ubuntu : test prior-ubuntu
  * PR #7833
    * [09-29 15:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5579232669597696/html/integration_test.log.html#t--podman-network-rm--1)
* ubuntu : test ubuntu
  * PR #7825
    * [09-29 16:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5528995376660480/html/integration_test.log.html#t--podman-network-rm--1)

**Comment by rhatdan** [comment]
Ok I will close this issue, with a hope and a prayer that it has been fixed, reopen if it happens again.
