### ISSUE TITLE
ERRO[0002] could not find slirp4netns

### ISSUE THREAD

**Issue by ocafebabe** [containers/podman#7810]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

ERRO[0002] could not find slirp4netns, the network namespace won't be configured: exec: "slirp4netns": executable file not found in $PATH

**Steps to reproduce the issue:**

1. Add Podman Ubuntu repository

2. Install Podman using offical method

3. Start a container

**Describe the results you received:**

No network...

**Describe the results you expected:**

Functional network...

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Wed Dec 31 19:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 12
  distribution:
    distribution: linuxmint
    version: "20"
  eventLogger: journald
  hostname: mobichris
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.4.0-48-generic
  linkmode: dynamic
  memFree: 2041085952
  memTotal: 33548574720
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 1019998208
  swapTotal: 1023406080
  uptime: 3h 26m 45.82s (Approximately 0.12 days)
registries:
  search:
  - docker.io
  - quay.io
  - docker-dev.repo.expretio.com
store:
  configFile: /home/cbourque/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/cbourque/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 3
  runRoot: /run/user/1000/containers
  volumePath: /home/cbourque/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 0
  BuiltTime: Wed Dec 31 19:00:00 1969
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 2.1.1~1 amd64 [installed]
podman/unknown 2.1.1~1 arm64
podman/unknown 2.1.1~1 armhf
podman/unknown 2.1.1~1 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical / Linux Mint 20 (Ubuntu 20.04)

The workaround is to manually install the missing package but IMHO it should be a mandatory dependency of the podman installation:
```
sudo apt install slirp4netns
```

**Comment by mheon** [comment]
We've gone back and forth on this one before; there are reasons to not want to install it by default (there were issues filed when it was a hard dependency requesting that we return it to a Recommends, but I can't seem to locate them). I believe it's set as a Recommended dependency now - @lsm5 can you confirm?

**Comment by ocafebabe** [comment]
@mheon ok but what are the other options?

**Comment by rhatdan** [comment]
This is an Ubuntu packaging issue.  It is a Recommends in Fedora and should be similar in Ubuntu.

**Comment by ocafebabe** [comment]
@rhatdan But how can this be a "recommended" dependency when this network mode is the default in Podman?

```
--network string                           Connect a container to a network (default "slirp4netns")
```

**Comment by mheon** [comment]
It is only required for rootless Podman. Running as root does not require `slirp4netns` (but does require the CNI plugins)

**Comment by ocafebabe** [comment]
Well, this is my case...

**Comment by afbjorklund** [comment]
It shows up as a "recommends" here, so should be installed by default (unless using --no-install-recommends)

```
Depends: libseccomp2, libdevmapper1.02.1, libgpgme11, catatonit, conmon (>= 2.0.18~1), containers-common (>= 1.1.1~2), containernetworking-plugins (>= 0.8.6~1), runc | cri-o-runc, iptables, podman-plugins
Recommends: crun, slirp4netns, uidmap, varlink
Conflicts: podman-rootless
```

```console
$ sudo apt install podman
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  catatonit conmon containernetworking-plugins containers-common containers-golang containers-image crun podman-plugins
  slirp4netns uidmap varlink
The following NEW packages will be installed:
  catatonit conmon containernetworking-plugins containers-common containers-golang containers-image crun podman
  podman-plugins slirp4netns uidmap varlink
0 upgraded, 12 newly installed, 0 to remove and 2 not upgraded.
Need to get 11,3 MB/27,9 MB of archives.
After this operation, 131 MB of additional disk space will be used.
Do you want to continue? [Y/n]
```

It is not required, since `sudo podman` should work without it. But it also should have been installed by default ?

**Comment by rhatdan** [comment]
@ocafebabe I believe everything is correct on Ubuntu, and this was a local install problem.  Reopen if you disagree.

**Comment by ocafebabe** [comment]
@rhatdan I guess Linux Mint behaves differently than Ubuntu when installing podman, even if it's a derivative of the later. It's also odd that this dependency is recommended on Ubuntu but required on these distributions: Gentoo, Arch Linux, openSUSE Tumbleweed...

**Comment by rhatdan** [comment]
It is recommended in RHEL, Centos and Fedora as well.
The key issue is fuse-overlay, slirp4netns are only required for rootless.  Each distro has the ability to define their own specification.  Personally I prefer Recommended, just so I can get rid of packages that I don't need, especially when embedding tools within containers.
