### ISSUE TITLE
STOPSIGNAL ignored

### ISSUE THREAD

**Issue by g574** [containers/podman#7821]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**I execute podman command as a non-root user.**
The STOPSIGNAL step in the Dockerfile is ignored when the container is being stopped.

**Steps to reproduce the issue:**

1. Write a simple Dockerfile:
```
FROM centos:centos8
STOPSIGNAL 2
```

2. Build an image:
```
podman build -t signaltest .
```

3. Start a container with that image, wait a few seconds then hit Ctrl+C:
```
 podman run -ti -u root --name signal_test localhost/signaltest /bin/bash -c 'trap "echo SIGINT" SIGINT ; sleep 1000000'
^CSIGINT
```
So far so good.

4. Start a container with that image:
```
podman run -ti -u root --name signal_test localhost/signaltest /bin/bash -c 'trap "echo SIGINT" SIGINT ; sleep 1000000'
```
Wait a few seconds, open another window to the machine, double-check the stop signal:
```
podman inspect signal_test --format '{{json .Config.StopSignal}}'
2
```
Then stop the container:
```
 time podman stop signal_test
9f98d5b10e887c8dcbe52d0799793f5e4009400bcea83e8144df8c18b3d6f761

real    0m10.495s
user    0m0.140s
sys     0m0.275s
```

5. Go back to the first screen and I see no output. The container is stopped.

**Describe the results you received:**
What I see is that it took a little more than 10 seconds to stop the container. I understand that podman sent a SIGTERM first, after 10 second a SIGKILL.
The process in the container never received the required SIGINT (STOPSIGNAL 2)

**Describe the results you expected:**
Stopping the container with `podman stop` should have the same output as hitting Ctrl+C.

**Additional information you deem important (e.g. issue happens only occasionally):**

This scenario is a reproduction of a more complex setup where the process in the container has to be stopped gracefully, i.e. by receiving a SIGINT.

**Output of `podman version`:**

```
Version:      2.0.6
API Version:  1
Go Version:   go1.13.4
Built:        Tue Sep  8 21:37:13 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.1
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.21-1.el8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 3460cd1ad859a79bd27df1714f39c76926ac1b39-dirty'
  cpus: 2
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: *****************
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 796
      size: 1
    - container_id: 1
      host_id: 100000
      size: 10001
    uidmap:
    - container_id: 0
      host_id: 992
      size: 1
    - container_id: 1
      host_id: 100000
      size: 10001
  kernel: 4.18.0-193.14.2.el8_2.x86_64
  linkmode: dynamic
  memFree: 604229632
  memTotal: 4130025472
  ociRuntime:
    name: runc
    package: runc-1.0.0-145.rc91.git24a3cf8.el8.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /tmp/run-992/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-2.el8.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 2067263488
  swapTotal: 2147479552
  uptime: 42h 50m 32.13s (Approximately 1.75 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/podman/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/podman/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 28
  runRoot: /tmp/run-992/containers
  volumePath: /home/podman/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1599593833
  BuiltTime: Tue Sep  8 21:37:13 2020
  GitCommit: ""
  GoVersion: go1.13.4
  OsArch: linux/amd64
  Version: 2.0.6
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.6-1.el8.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Comment by rhatdan** [comment]
Ok it looks like the StopSignal is making its way into the `podman inspect`  of the container.

**Comment by mheon** [comment]
Can you provide the output of `podman stop --log-level=debug` on the container?

**Comment by mheon** [comment]
Also, more environment details would be appreciated. Are you running as root or rootless, are you running the Podman remote client, etc...

Can you also check and make sure that SIGTERM is being sent, using a similar command but trapping SIGTERM instead?

**Comment by rhatdan** [comment]
Podman is definitely doing the right thing.

It is calling crun with this command.

/usr/bin/crun kill 6f1d5073e6130bbc85824592e4fad98e14ecfe8b398cc32dafc07bbada5f8dc4 2

**Comment by rhatdan** [comment]
@giuseppe Any ideas.

**Comment by rhatdan** [comment]
./bin/podman run --rm -ti -u root --name signal_test localhost/signaltest /bin/bash -c 'trap "echo SIGQUIT" SIGQUIT ; sleep 1000000'

podman stop -l

I do not see any signal hitting the bash script.

**Comment by rhatdan** [comment]
It seems like the sleep is causing bash to ignore signals, Try Setting the StopSignal to 10, (SIGUSR1) Then use read.  Signal 2 (SIGQUIT) is not able to be trapped.

```
./bin/podman run --rm -ti -u root --name signal_test localhost/signaltest /bin/bash -c 'trap "echo SIGUSR1" SIGUSR1 ; read'
```
Second Terminal
```
./bin/podman stop -l
```
First terminal now shows:
```
./bin/podman run --rm -ti -u root --name signal_test localhost/signaltest /bin/bash -c 'trap "echo SIGUSR1" SIGUSR1; read'
SIGUSR1
```

**Comment by g574** [comment]
@rhatdan, @mheon Thanks a lot for the inputs.
As I mentioned I tried to reproduce a more complex issue here and I failed apparently.
In the real-life situation I have a Dockerfile (built with Docker), with a CMD like this:
```
CMD ["/bin/bash", "script.sh"]
```
`script.sh` something looks like this:
```
#!/bin/bash
if ...
  exec command
else
  exec command
fi
```
When I run this in docker I can shut down the container gracefully (the application has to write the memory to the disk before shutting down).
If I run the same image with Podman the app is closed abruptly although `podman exec <container_name> ps aux` shows that the app is running as PID 1.
I only added `STOPSIGNAL 2` later as a way to troubleshoot the problem. Unfortunately using SIGUSR1 does not solve my problem.

Is there a difference between `CMD ["x", "y"]` and `CMD xy` like in Docker (https://docs.docker.com/engine/reference/builder/#cmd)? How could I make sure the SIGINT is forwarded to the process inside the container?

**Comment by g574** [comment]
I did some more testing.
Basically having `STOPSIGNAL 2` in the Dockerfile and then `podman stop container` does not stop the application with SIGINT, `podman kill --signal SIGINT container` does.
