### ISSUE TITLE
run files under /tmp can be clobbered by systemd.tmpfiles

### ISSUE THREAD

**Issue by industrial-sloth** [containers/podman#7852]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I have several long-running, little-used podman containers running under Centos 7.8. These are running rootless, and are launched by systemd with `User=` flags. The systemd unit files were created by podman, with `User=`, `Group=` and `WorkingDirectory=` flags manually added.

After some period of time (which I now believe to be approximately 10 days), some of these containers would go into a "zombie" state, where they no longer appeared under `podman ps`, but did appear in a "created" state under `podman ps --all`. Under some circumstances the containers would continue running, seemingly fine other than not showing up in `podman ps`; in other cases the container networking would die.

The important factor appears to be that the `runRoot` is under `/tmp`. Stock Centos runs `systemd-tmpfiles` daily, and by default, files under `/tmp` that have not been created, accessed, or modified in the past 10 days get blown away. 

**Steps to reproduce the issue:**
1. launch a container with runfiles under `/tmp`. The container should be idle, without doing anything that would lead to access or modification times being updated for its runfiles. Verify that it shows up under `podman ps`.

2. modify `/usr/lib/tmpfiles.d/tmp.conf` so that the `/tmp` cleanup line reads (for instance) `v /tmp 1777 root root 1m` rather than the default of `v /tmp 1777 root root 10d`. Wait a minute, then run `sudo /usr/bin/systemd-tmpfiles --clean`. Alternatively, do nothing besides waiting 11 days, and this will happen automatically. :)

3. rerun `podman ps`. 

**Describe the results you received**
Container will no longer show up under `podman ps`; the underlying processes appear to still be running, but networking, etc will be hosed. The particular behavior seen here seems to depend on whether anything has happened to cause access or modification times to be updated for files under `/tmp`, as recent file accesses/modifications keep `systemd-tmpfiles` from blowing those files away.

**Describe the results you expected**
Container stays happy.

**Output of `podman version`:**
```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15
Built:        Mon Sep 28 02:07:17 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**
```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.21-1.el7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: efe288263ebb1bab4673d2cfbe1a352f3c7d27c1-dirty'
  cpus: 2
  distribution:
    distribution: '"centos"'
    version: "7"
  eventLogger: journald
  hostname: <ip>.us-west-2.compute.internal
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 925
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 925
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 3.10.0-1127.19.1.el7.x86_64
  linkmode: dynamic
  memFree: 2220236800
  memTotal: 3923103744
  ociRuntime:
    name: runc
    package: runc-1.0.0-103.dev.el7.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: 70f396b2cfa8fb0c6c12bd46020af4744b9eff5b
      spec: 1.0.1-dev
  os: linux
  remoteSocket:
    path: /tmp/run-925/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.1.4-2.el7.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 0
  swapTotal: 0
  uptime: 24m 53.82s
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/my_user/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/my_user/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 1
  runRoot: /tmp/run-925/containers
  volumePath: /home/my_user/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1601258837
  BuiltTime: Mon Sep 28 02:07:17 2020
  GitCommit: ""
  GoVersion: go1.15
  OsArch: linux/amd64
  Version: 2.1.1
```
**Package Info**
`podman-2.1.1-4.el7.x86_64`

**Workaround**
For anyone else who might be bit by this, I have a workaround that so far seems to be effective:
* copy `/usr/lib/tmpfiles.d/tmp.conf` into `/etc/tmpfiles.d/tmp.conf`
* add the following exclusions to `/etc/tmpfiles.d/tmp.conf`:
```
x /tmp/[0-9]*
x /tmp/containers-user-[0-9]*
x /tmp/run-[0-9]*
```

**Fix?**
I'm not sure whether this can/should be fixed in podman itself - perhaps just documenting the workaround above (or something similar?) would be appropriate. 

In man pages for other versions of `tmpfiles.d` there's a suggestion that an application take out a "BSD file lock" on files under `/tmp` that it doesn't want to be cleaned up - see for instance <https://www.freedesktop.org/software/systemd/man/tmpfiles.d.html>, search for "BSD file lock". However this text doesn't appear in `man tmpfiles.d` on my centos machine, and, not having investigated further, I'm not sure whether that would be applicable here.

**Comment by mheon** [comment]
Hm. We shouldn't be using those directories unless you didn't have a `/run/user/$UID` when you first ran Podman - normally all our rootless containers use a temp directory in there, and I don't believe systemd will ever clean up that directory except on user logout. Perhaps we should investigate moving the backup directories we create when `/run/user/$UID` is not available to use `/var/run` (which does not appear to be cleaned up by default)?

**Comment by rhatdan** [comment]
@industrial-sloth did you figure a way to fix this problem. I don't really see a way for the default podman to fix this issue, and since we store our tmp files in /run by default, we don't face this issue.

I think the best would be to figure out a way to tell systemd to not remove /tmp/podman-* files.

**Comment by industrial-sloth** [comment]
@rhatdan so yeah, I do have a workaround (see **workaround** section in original issue post). And I hear what you're saying about storing under `/run` by default. I guess the concern is that I did not explicitly configure `runRoot`, etc, to be under `/tmp`, this instead fell out of some fallback logic in the default configuration that I'd need to go back and reconstruct. As I recall, it came out of some permutation of the podman-generated unit files, running under systemd at all, and/or running rootless - something somewhere didn't have permission to write under `/run`, and so it ends up writing to `/tmp` instead.

I guess the upshot is that there is *some* fallback condition in podman that *does* lead to files being written in `/tmp`, and subsequently blown away. I can go back and dig and reconstruct those conditions if it'd be helpful.

**Comment by rhatdan** [comment]
I think systemd launched user containers can do this if the linger flag is not set.

Do you know if/how we can block systemd from cleaning up this content?

**Comment by industrial-sloth** [comment]
Hi Dan - Yes, from the issue posting above, cleanup can be blocked by a `tmpfiles.d` config setting - see `man tmpfiles.d`, e.g. <https://www.unix.com/man-page/centos/5/tmpfiles.d/>. Here's my workaround:

* copy /usr/lib/tmpfiles.d/tmp.conf into /etc/tmpfiles.d/tmp.conf
* add the following exclusions to /etc/tmpfiles.d/tmp.conf:
```
x /tmp/[0-9]*
x /tmp/containers-user-[0-9]*
x /tmp/run-[0-9]*
```

That is perhaps less than ideal as a long-term fix, however, since (for instance) it would block cleanup of *any* files in `/tmp` that have a numeric filename. Maybe consider prepending a "podman" / "libpod" / something to the filenames?

But per @mheon 's comment above, just not using `/tmp` seems like a potentially better fix, provided that there's an alternative location that would be available to a systemd-launched user container.
