### ISSUE TITLE
podman.service unit file should include a known EnvironmentFile directive

### ISSUE THREAD

**Issue by jwhonce** [containers/podman#7859]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

If podman.service included a directive like `EnvironmentFile=-/etc/sysconfig/podman` then changing an environment variable's value would require only restarting podman vs reloading the `systemd` daemon

**Describe the results you received:**
Edit `podman.service` file, add an Environment or EnvironmentFile directive, then `systemctl daemon-reload`

**Describe the results you expected:**
Edit `/etc/sysconfig/podman`,  add/change environment variable's value, then `systemctl restart podman`

**Additional information you deem important (e.g. issue happens only occasionally):**
 - This change would isolate the impact of the change to just podman not all of systemd

**Output of `podman version`:**

```
Version:      2.0.6
API Version:  1
Go Version:   go1.14.6
Built:        Tue Sep  1 12:26:51 2020
OS/Arch:      linux/amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
 - Impacts packaging

**Comment by bbros-dev** [comment]
My understanding is that `EnvironmentFile` use is frowned on:

See:
https://lists.freedesktop.org/archives/systemd-devel/2015-December/035236.html

 and [this comment](https://github.com/systemd/systemd/issues/618#issuecomment-123808429)

**Comment by rhatdan** [comment]
I guess the preferred method then would be to create an /etc/system/systemd/podman.service file with the environment added?  I believe the issue that @jwhonce is attempting to fix here is handling of HTTP_PROXY environment variables.

If an admin was to set this environment variable in /etc/profile.d, would the service pick up on it?

**Comment by jwhonce** [comment]
@rhatdan No, the service will not pick anything from /etc/profile.d

@bbros-dev Thanks for the pointers. 

I'll close this and leave individuals choose how to manage systemd.
