### ISSUE TITLE
Docker Compatibility API Timestamp Format

### ISSUE THREAD

**Issue by hhergeth** [containers/podman#7860]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Docker compatibility endpoint /containers/id/json does not comply with the Docker API specification. The specs [here](https://docs.docker.com/engine/api/v1.40/#operation/ContainerInspect) show that the __Created__ property is in ISO 8601 format. Podman on the other hand returns a string formatted differently (see below)

[Line 318](https://github.com/containers/podman/blob/master/pkg/api/handlers/compat/containers.go#L318) in `podman/pkg/api/handlers/compat/containers.go` is the source of this behaviour:
`		Created:         l.CreatedTime().String(),`
This would have to be changed to something like:
`		Created:        l.CreatedTime().Format(time.RFC3339),`

**Steps to reproduce the issue:**

1. Start the api as described: podman system service -t 5000 &

2. Call the api endpoint: curl -s --unix-socket $XDG_RUNTIME_DIR/podman/podman.sock http://dummy/containers/id/json (format with jq for readability)

**Describe the results you received:**
A string formatted with [Time.String()](https://golang.org/pkg/time/#Time.String) :
`"Created": "2020-09-27 17:01:55.178157437 +0000 UTC",`

**Describe the results you expected:**
A string in ISO-8601:
`"Created": "2020-09-27T17:01:55.178157437",`

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 4
  distribution:
    distribution: ubuntu
    version: "19.10"
  eventLogger: journald
  hostname: <>
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.3.0-64-generic
  linkmode: dynamic
  memFree: 332857344
  memTotal: 16462323712
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.4
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 4162895872
  swapTotal: 8589930496
  uptime: 424h 54m 20.43s (Approximately 17.67 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/<>/.config/containers/storage.conf
  containerStore:
    number: 68
    paused: 0
    running: 65
    stopped: 3
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.4.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.4.1
        using FUSE kernel interface version 7.27
  graphRoot: /home/<>/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 162
  runRoot: /run/user/1000/containers
  volumePath: /home/<>/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 2.1.1~1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
Thanks for opening the issue, @hhergeth!

@baude @jwhonce PTAL. I recall some timestamp issues but am not sure if this endpoint was affected.

**Comment by rhatdan** [comment]
Yes this endpoint should be fixed.  The issues we had were with json output, that were difficult to fix.
