### ISSUE TITLE
support container network aliases

### ISSUE THREAD

**Issue by tmds** [containers/podman#7870]
Allow to set network aliases for containers.

Either providing the alias on docker run:

```
docker run --name container1 --network network1 --network-alias alias1 --network-alias alias2 <image>
```

Or providing the alias post docker run:
```
network connect --alias alias1 --alias alias2 network1 container1
```

**Comment by rhatdan** [comment]
@baude This looks like something that the dns-CNI PLugin would need to handle?

**Comment by baude** [comment]
nope, i dont think so.  in fact, i dont think we can do this with our current container architecture.  @mheon do I remember that correctly?

**Comment by mheon** [comment]
I think we can but it would be a fair amount of effort to get it working - maybe a week or two of time for me or someone else who knows the network code well.

**Comment by mheon** [comment]
Also, there's going to be an unavoidable connection drop when we do add the new network, I think (we basically need to have CNI tear down and then recreate the network)

**Comment by tmds** [comment]
My use for `podman network connect` is to be able to pass an `--alias`.
`podman` also supports it via a `--network-alias` argument on the `run` command.
@mheon probably this is simpler to implement? Should I change this issue for adding that argument?

**Comment by mheon** [comment]
I would say that aliases are more difficult to implement than `network connect` right now (still possible, but probably a good sprint worth of work to implement)

**Comment by rhatdan** [comment]
Of course if the community wanted to work on a PR, we would love to see it.

**Comment by tmds** [comment]
Without `podman network connect --alias`, or `podman run --network-alias` all container dns names share the same namespace. It is not possible to use the same network name for containers that live on different networks, because they clash as container names.

@rhatdan I hope someone takes this on, unfortunately I can volunteer because I don't speak any `go`.

**Comment by mheon** [comment]
Are you sure about that? I'm fairly certain that we run per-network DNS instances, so we effectively namespace container names by the network they're attached to? @baude can confirm.

**Comment by tmds** [comment]
The clash is at the container name level:
```
$ podman network create net1
$ podman network create net2
$ podman run --rm -d --name name1 --network net1 busybox sleep 10
$ podman run --rm --name name1 --network net2 busybox sleep 10
Error: error creating container storage: the container name "name1" is already in use by "650f7d2d299dfe23d05e5f1a2cadc4230841fd33eec5bae3d9be9da05d2b1ee3". You have to remove that container to be able to reuse that name.: that name is already in use
```

**Comment by rhatdan** [comment]
Would --hostname fix this?

**Comment by tmds** [comment]
> Would --hostname fix this?

I tried that. This sets the hostname for the host itself. It isn't added as a name to the DNS.

**Comment by tmds** [comment]
For my use-case either of these will work:

Providing the alias on `docker run`:
```
docker run --name container1 --network network1 --network-alias alias1 --network-alias alias2 <image>
```

Providing the alias post `docker run`:
```
network connect --alias alias1 --alias alias2 network1 container1
```

**Comment by mheon** [comment]
This is being worked on now by myself and @baude

**Comment by baude** [comment]
merged upstream today ... closing

**Comment by tmds** [comment]
@mheon I'm trying this out. Is it supposed to work rootless? That's how I want to use it.
If it doesn't: should I create a new issue for that?

I have:
```
podman.x86_64                                          2:2.2.1-1.fc32                         @updates-testing                                  
```
And this doesn't work for me:
```
podman network create mynetwork
podman run --rm -d --network mynetwork --network-alias alias1 alpine sleep 10
podman run --rm --network mynetwork alpine ping alias1
```

**Comment by mheon** [comment]
Rootless needs an upgrade to the CNI infra image - we're discussing changes to said image right now (moving towards using content from the host, so you wouldn't need to upgrade the infra container when you upgraded CNI and dnsname). So this is root-only for now while we build a better way to handle it as rootless.

**Comment by tmds** [comment]
Is there an issue that I can follow to know when this may work?

**Comment by mheon** [comment]
https://github.com/containers/podman/pull/8585
