### ISSUE TITLE
integration test issues with fedora 33 on btrfs

### ISSUE THREAD

**Issue by lsm5** [containers/podman#7875]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Listing the integration test failures using the latest sources on fedora 33 using btrfs

**Steps to reproduce the issue:**

1. setup fedora 33 with btrfs

2. make localintegration

**Describe the results you received:**

[Fail] Podman cp [It] podman cp file to dir 
/home/foobar/repositories/podman/test/e2e/cp_test.go:88

[Fail] Podman cp [It] podman cp file to dir 
/home/foobar/repositories/podman/test/e2e/cp_test.go:88

[Fail] Podman cp [It] podman cp dir to dir 
/home/foobar/repositories/podman/test/e2e/cp_test.go:128

[Fail] Podman cp [It] podman cp file to dir 
/home/foobar/repositories/podman/test/e2e/cp_test.go:88

[Fail] Podman cp [It] podman cp tar 
/home/foobar/repositories/podman/test/e2e/cp_test.go:197

[Fail] Podman cp [It] podman cp symlink 
/home/foobar/repositories/podman/test/e2e/cp_test.go:227

[Fail] Podman cp [It] podman cp dir to dir 
/home/foobar/repositories/podman/test/e2e/cp_test.go:128

[Fail] Podman cp [It] podman cp tar 
/home/foobar/repositories/podman/test/e2e/cp_test.go:197

[Fail] Podman cp [It] podman cp symlink 
/home/foobar/repositories/podman/test/e2e/cp_test.go:227

[Fail] Podman cp [It] podman cp tar 
/home/foobar/repositories/podman/test/e2e/cp_test.go:197

[Fail] Podman cp [It] podman cp dir to dir 
/home/foobar/repositories/podman/test/e2e/cp_test.go:128

[Fail] Podman cp [It] podman cp symlink 
/home/foobar/repositories/podman/test/e2e/cp_test.go:227

[Fail] Podman run with volumes [It] podman run with volumes and suid/dev/exec options 
/home/foobar/repositories/podman/test/e2e/run_volume_test.go:210

[Fail] Podman run with volumes [It] podman run with volumes and suid/dev/exec options 
/home/foobar/repositories/podman/test/e2e/run_volume_test.go:210

[Fail] Podman run with volumes [It] podman run with volumes and suid/dev/exec options 
/home/foobar/repositories/podman/test/e2e/run_volume_test.go:210

[Fail] Podman pod create [It] podman run --add-host in pod 
/home/foobar/repositories/podman/test/e2e/pod_infra_container_test.go:392

[Fail] Podman pod create [It] podman run --add-host in pod 
/home/foobar/repositories/podman/test/e2e/pod_infra_container_test.go:392

[Fail] Podman pod create [It] podman run --add-host in pod 
/home/foobar/repositories/podman/test/e2e/pod_infra_container_test.go:392

[Fail] Podman pod pause [It] podman pod pause a running pod by id 
/home/foobar/repositories/podman/test/e2e/pod_pause_test.go:70

[Fail] Podman pod pause [It] podman pod pause a running pod by id 
/home/foobar/repositories/podman/test/e2e/pod_pause_test.go:70

[Fail] Podman pod pause [It] podman pod pause a running pod by name 
/home/foobar/repositories/podman/test/e2e/pod_pause_test.go:106

[Fail] Podman pod pause [It] podman pod pause a running pod by id 
/home/foobar/repositories/podman/test/e2e/pod_pause_test.go:70

[Fail] Podman pod pause [It] podman pod pause a running pod by name 
/home/foobar/repositories/podman/test/e2e/pod_pause_test.go:106

[Fail] Podman pod pause [It] podman pod pause a running pod by name 
/home/foobar/repositories/podman/test/e2e/pod_pause_test.go:106

[Fail] Podman network create [It] podman network create with name and subnet 
/home/foobar/repositories/podman/test/e2e/network_create_test.go:175

[Fail] Podman run memory [It] podman run memory test 
/home/foobar/repositories/podman/test/e2e/run_memory_test.go:46

[Fail] Podman run memory [It] podman run memory test 
/home/foobar/repositories/podman/test/e2e/run_memory_test.go:46

[Fail] Podman run memory [It] podman run memory test 
/home/foobar/repositories/podman/test/e2e/run_memory_test.go:46

[Fail] Podman run memory [It] podman run memory-reservation test 
/home/foobar/repositories/podman/test/e2e/run_memory_test.go:64

[Fail] Podman run memory [It] podman run memory-reservation test 
/home/foobar/repositories/podman/test/e2e/run_memory_test.go:64

[Fail] Podman run memory [It] podman run memory-reservation test 
/home/foobar/repositories/podman/test/e2e/run_memory_test.go:64

[Fail] Podman run memory [It] podman run kernel-memory test 
/home/foobar/repositories/podman/test/e2e/run_memory_test.go:90

[Fail] Podman run memory [It] podman run kernel-memory test 
/home/foobar/repositories/podman/test/e2e/run_memory_test.go:90

[Fail] Podman run memory [It] podman run kernel-memory test 
/home/foobar/repositories/podman/test/e2e/run_memory_test.go:90

[Fail] Podman network create [It] podman network create with name and subnet 
/home/foobar/repositories/podman/test/e2e/network_create_test.go:175

[Fail] Podman network create [It] podman network create with name and subnet 
/home/foobar/repositories/podman/test/e2e/network_create_test.go:175

[Fail] Podman network [It] podman inspect container two CNI networks 
/home/foobar/repositories/podman/test/e2e/network_test.go:218

[Fail] Podman network [It] podman inspect container two CNI networks 
/home/foobar/repositories/podman/test/e2e/network_test.go:218

[Fail] Podman network [It] podman inspect container two CNI networks 
/home/foobar/repositories/podman/test/e2e/network_test.go:218

[Fail] Podman generate kube [It] podman security labels from image 
/home/foobar/repositories/podman/test/e2e/run_security_labels.go:111

[Fail] Podman generate kube [It] podman security labels from image 
/home/foobar/repositories/podman/test/e2e/run_security_labels.go:111

[Fail] Podman generate kube [It] podman security labels from image 
/home/foobar/repositories/podman/test/e2e/run_security_labels.go:111

[Fail] Podman network [It] podman inspect container single CNI network 
/home/foobar/repositories/podman/test/e2e/network_test.go:194

[Fail] Podman run [It] podman run with cgroups=enabled makes cgroups 
/home/foobar/repositories/podman/test/e2e/run_test.go:1123

[Fail] Podman run [It] podman run with cgroups=enabled makes cgroups 
/home/foobar/repositories/podman/test/e2e/run_test.go:1123

[Fail] Podman run [It] podman run with cgroups=enabled makes cgroups 
/home/foobar/repositories/podman/test/e2e/run_test.go:1123

[Fail] Podman run [It] podman run verify pids-limit 
/home/foobar/repositories/podman/test/e2e/run_test.go:1221

[Fail] Podman run [It] podman run verify pids-limit 
/home/foobar/repositories/podman/test/e2e/run_test.go:1221

[Fail] Podman run [It] podman run verify pids-limit 
/home/foobar/repositories/podman/test/e2e/run_test.go:1221

[Fail] Podman pause [It] podman pause a running container by id 
/home/foobar/repositories/podman/test/e2e/pause_test.go:91

[Fail] Podman pause [It] podman container pause a running container by id 
/home/foobar/repositories/podman/test/e2e/pause_test.go:108

[Fail] Podman pause [It] podman pause a running container by id 
/home/foobar/repositories/podman/test/e2e/pause_test.go:91

[Fail] Podman pause [It] podman container pause a running container by id 
/home/foobar/repositories/podman/test/e2e/pause_test.go:108

[Fail] Podman pause [It] podman pause a running container by id 
/home/foobar/repositories/podman/test/e2e/pause_test.go:91

[Fail] Podman pause [It] podman container pause a running container by id 
/home/foobar/repositories/podman/test/e2e/pause_test.go:108

[Fail] Podman pause [It] podman remove a paused container by id without force 
/home/foobar/repositories/podman/test/e2e/pause_test.go:139

[Fail] Podman pause [It] podman remove a paused container by id with force 
/home/foobar/repositories/podman/test/e2e/pause_test.go:161

[Fail] Podman pause [It] podman remove a paused container by id without force 
/home/foobar/repositories/podman/test/e2e/pause_test.go:139

[Fail] Podman pause [It] podman remove a paused container by id with force 
/home/foobar/repositories/podman/test/e2e/pause_test.go:161

[Fail] Podman pause [It] podman remove a paused container by id without force 
/home/foobar/repositories/podman/test/e2e/pause_test.go:139

[Fail] Podman pause [It] podman remove a paused container by id with force 
/home/foobar/repositories/podman/test/e2e/pause_test.go:161

[Fail] Podman pause [It] podman stop a paused container by id 
/home/foobar/repositories/podman/test/e2e/pause_test.go:181

[Fail] Podman pause [It] podman pause a running container by name 
/home/foobar/repositories/podman/test/e2e/pause_test.go:217

[Fail] Podman pause [It] podman stop a paused container by id 
/home/foobar/repositories/podman/test/e2e/pause_test.go:181

[Fail] Podman pause [It] podman pause a running container by name 
/home/foobar/repositories/podman/test/e2e/pause_test.go:217

[Fail] Podman network [It] podman inspect container single CNI network 
/home/foobar/repositories/podman/test/e2e/network_test.go:194

[Fail] Podman pause [It] podman stop a paused container by id 
/home/foobar/repositories/podman/test/e2e/pause_test.go:181

[Fail] Podman pause [It] podman pause a running container by name 
/home/foobar/repositories/podman/test/e2e/pause_test.go:217

[Fail] Podman pause [It] podman pause a running container by id and another by name 
/home/foobar/repositories/podman/test/e2e/pause_test.go:238

[Fail] Podman pause [It] podman pause a running container by id and another by name 
/home/foobar/repositories/podman/test/e2e/pause_test.go:238

[Fail] Podman pause [It] Pause a bunch of running containers 
/home/foobar/repositories/podman/test/e2e/pause_test.go:283

[Fail] Podman pause [It] podman pause a running container by id and another by name 
/home/foobar/repositories/podman/test/e2e/pause_test.go:238

[Fail] Podman pause [It] Pause a bunch of running containers 
/home/foobar/repositories/podman/test/e2e/pause_test.go:283

[Fail] Podman pause [It] Unpause a bunch of running containers 
/home/foobar/repositories/podman/test/e2e/pause_test.go:305

[Fail] Podman pause [It] Pause a bunch of running containers 
/home/foobar/repositories/podman/test/e2e/pause_test.go:283

[Fail] Podman pause [It] Unpause a bunch of running containers 
/home/foobar/repositories/podman/test/e2e/pause_test.go:305

[Fail] Podman pause [It] Unpause a bunch of running containers 
/home/foobar/repositories/podman/test/e2e/pause_test.go:305

[Fail] Podman network [It] podman inspect container single CNI network 
/home/foobar/repositories/podman/test/e2e/network_test.go:194

[Fail] Podman systemd [It] podman run container with systemd PID1 
/home/foobar/repositories/podman/test/e2e/systemd_test.go:109

[Fail] Podman systemd [It] podman run container with systemd PID1 
/home/foobar/repositories/podman/test/e2e/systemd_test.go:109

[Fail] Podman systemd [It] podman run container with systemd PID1 
/home/foobar/repositories/podman/test/e2e/systemd_test.go:109

Ran 994 of 1112 Specs in 700.652 seconds
FAIL! -- 967 Passed | 27 Failed | 0 Flaked | 0 Pending | 118 Skipped

**Comment by lsm5** [comment]
This was tested with storage driver "overlay"

**Comment by baude** [comment]
Im not sure what make localintegration really is ... if you cd test/e2e and then do a ginkgo -v . do things pass?

**Comment by vrothberg** [comment]
> Im not sure what make localintegration really is ... if you cd test/e2e and then do a ginkgo -v . do things pass?

It calls ginkgo in test/e2e and is also used in CI for the integration tests.

**Comment by rhatdan** [comment]
@lsm5 what is the skoop with this issue?

**Comment by rhatdan** [comment]
@lsm5 Any update?

**Comment by rhatdan** [comment]
@lsm5 I am asking again, what is the scoop on this one?

**Comment by vrothberg** [comment]
I think we're good with F33 :)
