### ISSUE TITLE
Podman 2.0.6 pull and run fails on ubuntu image

### ISSUE THREAD

**Issue by bobhenkel** [containers/podman#7914]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When doing a podman pull or a podman run on docker.io/library/ubuntu:latest it fails.

**Steps to reproduce the issue:**

1. ```podman pull docker.io/library/ubuntu:latest``` or ```podman run --rm -it docker.io/library/ubuntu:latest bash```

**Describe the results you received:**
For pull
```
bob@server1:~> podman pull docker.io/library/ubuntu:latest
Trying to pull docker.io/library/ubuntu:latest...
Getting image source signatures
Copying blob d72e567cc804 done  
Copying blob 0f3630e5ff08 done  
Copying blob b6a83d81d1f4 done  
Copying config 9140108b62 done  
Writing manifest to image destination
Storing signatures
  Error processing tar file(exit status 1): there might not be enough IDs available in the namespace (requested 100:0 for /var/cache/apt/archives/partial): lchown /var/cache/apt/archives/partial: invalid argument
Error: unable to pull docker.io/library/ubuntu:latest: Error committing the finished image: error adding layer with blob "sha256:d72e567cc804d0b637182ba23f8b9ffe101e753a39bf52cd4db6b89eb089f13b": Error processing tar file(exit status 1): there might not be enough IDs available in the namespace (requested 100:0 for /var/cache/apt/archives/partial): lchown /var/cache/apt/archives/partial: invalid argument
bob@server1:~>
```
For run
```
bob@server1:~> podman run --rm -it ubuntu bash
Trying to pull registry.opensuse.org/ubuntu...
  name unknown
Trying to pull docker.io/library/ubuntu...
Getting image source signatures
Copying blob 0f3630e5ff08 done  
Copying blob d72e567cc804 done  
Copying blob b6a83d81d1f4 done  
Copying config 9140108b62 done  
Writing manifest to image destination
Storing signatures
  Error processing tar file(exit status 1): there might not be enough IDs available in the namespace (requested 100:0 for /var/cache/apt/archives/partial): lchown /var/cache/apt/archives/partial: invalid argument
Error: unable to pull ubuntu: 2 errors occurred:
	* Error initializing source docker://registry.opensuse.org/ubuntu:latest: Error reading manifest latest in registry.opensuse.org/ubuntu: name unknown
	* Error committing the finished image: error adding layer with blob "sha256:d72e567cc804d0b637182ba23f8b9ffe101e753a39bf52cd4db6b89eb089f13b": Error processing tar file(exit status 1): there might not be enough IDs available in the namespace (requested 100:0 for /var/cache/apt/archives/partial): lchown /var/cache/apt/archives/partial: invalid argument


bob@server1:~>
```

**Describe the results you expected:**
pull and run should of completed with success.

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens 100% of the time.
 
I'm not an admin on the system this is happening on so I'm working with the system admins to figure things out. One observation I had after reading this https://github.com/containers/podman/blob/master/troubleshooting.md#solution-8 is my account is not in /etc/passwd. I believe we have ldap setup so I'm not sure if that doesn't leverage /etc/passwd at all, I will need to ask our system admins.  Would this cause issues?  It's odd that my commands complain about not enough IDs in the namespace yet in subgid and subuid it looks fine to me.  Seems like it's not actually using those values. 

Here is output of subgid and subuid
```
bob@server1:~> cat /etc/{subgid,subuid}
adm:100000:65536
bob:214009:65536
adm:100000:65536
bob:214009:65536
```

**Output of `podman version`:**

```
Version:      2.0.6
API Version:  1
Go Version:   go1.13.15
Built:        Tue Sep  8 08:00:00 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
bob@server1:~> podman version
Version:      2.0.6
API Version:  1
Go Version:   go1.13.15
Built:        Tue Sep  8 08:00:00 2020
OS/Arch:      linux/amd64
bob@server1:~> podman info --debug
host:
  arch: amd64
  buildahVersion: 1.15.1
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.10-3.3.1.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.10, commit: unknown'
  cpus: 256
  distribution:
    distribution: '"sles"'
    version: "15.2"
  eventLogger: file
  hostname: server1
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 21176
      size: 1
    - container_id: 1
      host_id: 214009
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 214009
      size: 1
  kernel: 5.3.18-22-default
  linkmode: dynamic
  memFree: 245732708352
  memTotal: 270266920960
  ociRuntime:
    name: runc
    package: runc-1.0.0~rc10-1.9.1.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      spec: 1.0.1-dev
  os: linux
  remoteSocket:
    path: /run/user/214009/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-0.4.5-3.9.1.x86_64
    version: |-
      slirp4netns version 0.4.5
      commit: unknown
      libslirp: 4.3.0-git
  swapFree: 214748360704
  swapTotal: 214748360704
  uptime: 70h 11m 54.38s (Approximately 2.92 days)
registries:
  search:
  - registry.opensuse.org
  - docker.io
store:
  configFile: /home/users/bob/.config/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 0
    stopped: 7
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.6-3.6.1.x86_64
      Version: |-
        fusermount3 version: 3.6.1
        fuse-overlayfs: version 0.7.6
        FUSE library version 3.6.1
        using FUSE kernel interface version 7.29
  graphRoot: /home/users/bob/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 4
  runRoot: /run/user/214009/containers
  volumePath: /home/users/bob/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1599566400
  BuiltTime: Tue Sep  8 08:00:00 2020
  GitCommit: ""
  GoVersion: go1.13.15
  OsArch: linux/amd64
  Version: 2.0.6
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
bob@server1:~> rpm -q podman
podman-2.0.6-4.25.1.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical server
```
bob@server1:~> cat /etc/os-release
NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"
ID="sles"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:15:sp2"
```

**Comment by mheon** [comment]
Your account most likely does not have entries in `/etc/subuid` and `/etc/subgid` to allocate additional UIDs and GIDs for your user to use - see https://www.redhat.com/sysadmin/rootless-podman

You can either create the entries and then run `podman system migrate` to cause Podman to re-read the file and use the entries, or set the `ignore_chown_errors` storage option to use only a single UID and GID (and the restrictions that come with that).

**Comment by bobhenkel** [comment]
I do have those entries

```
bob@server1:~> cat /etc/{subgid,subuid}
adm:100000:65536
bob:214009:65536
adm:100000:65536
bob:214009:65536
```

**Comment by mheon** [comment]
Podman sees the `/etc/subgid` entry but not the `/etc/subuid` one (the `idMappings` section of `podman info`). The entry in `subuid` seems correct. I would recommend trying a `podman system migrate` and then re-pulling the image to see if that resolves matters; otherwise, the `newuidmap` binary could be missing a file capability, perhaps?

**Comment by bobhenkel** [comment]
Migrate didn't seem to help. Still same error message.

```
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 21176
      size: 1
    - container_id: 1
      host_id: 214009
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 214009
      size: 1
```

**Comment by bobhenkel** [comment]
I ran podman system migrate as my non-root user account.  Does this need to be executed as root?

**Comment by mheon** [comment]
No, it's meant to be run as the user running rootless Podman. It causes the rootless user namespace to be re-created, which re-reads the subuid and subgid files.

**Comment by mheon** [comment]
Actually, I do notice a problem in your `/etc/subuid` - there's an overlap between the range assigned to you and UIDs and GIDs in use in the system (your UID, specifically). The ranges assigned in subuid and subgid should never overlap UIDs and GIDs in use by actual users in the system. I think that you'll need to adjust these to ranges that are not in use, and then run `podman system migrate` to force a re-read of the files.

**Comment by bobhenkel** [comment]
Thanks for the help! I've got a message out to our system admin to fix that up. I'll reply back with the results once they make the needed change.

**Comment by rhatdan** [comment]
I do not believe this is an issue with Podman. Reopen if I am mistaken.

**Comment by gokamal** [comment]
@bobhenkel Can you please post what's the fix for the issue ?

**Comment by bobhenkel** [comment]
The suggestion by mheon solved this.  There were overlapping id values. Thanks!
> Actually, I do notice a problem in your `/etc/subuid` - there's an overlap between the range assigned to you and UIDs and GIDs in use in the system (your UID, specifically). The ranges assigned in subuid and subgid should never overlap UIDs and GIDs in use by actual users in the system. I think that you'll need to adjust these to ranges that are not in use, and then run `podman system migrate` to force a re-read of the files.

**Comment by gokamal** [comment]
Ok thanks, got it fixed along with `podman system migrate`
