### ISSUE TITLE
[APIv2] Environment variables are not initialized in container

### ISSUE THREAD

**Issue by psakar** [containers/podman#7923]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug
REST API v2

**Description**
Related to https://github.com/containers/podman/issues/7235

Container created with REST API v2 does not have environment variables set

**Steps to reproduce the issue:**

1. Run following script
```
# create Dockerfile
echo -e "from alpine\nenv foo=\"bar\"" > /tmp/Dockerfile
podman build -t test /tmp/

# start podman REST API
killall podman
podman --log-level=debug --runtime=/usr/bin/crun system service -t 0 tcp:localhost:8880 2>&1>/tmp/podman-rest.log &

#REST API v2 - create container, show log, inspect container and remove it
curl -X POST -H "Content-Type: application/json" 'http://127.0.0.1:8880/containers/create?name=test' --data '{"name":"test","Image":"localhost/test:latest", "Cmd":["printenv"]}'
curl -X POST -H "Content-Type: application/json" 'http://127.0.0.1:8880/containers/test/start'
curl --output - -H "Content-Type: application/json" "http://127.0.0.1:8880/containers/test/logs?stdout=true&stderr=true"
podman logs test
podman inspect test > /tmp/test-test-podman-api.txt
curl -X DELETE -H "Content-Type: application/json" 'http://127.0.0.1:8880/containers/test'
```

**Describe the results you received:**
```
$ podman logs test
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
TERM=xterm
HOSTNAME=2c2ca1c98053
HOME=/root
container=libpod
```

**Describe the results you expected:**
I expect the log would show the environment variables as when running the same commands using CLI below
Relevant part is line foo=bar which is missing when using REST API v2

```
# CLI
podman create --name test localhost/test:latest printenv
podman start test
podman logs test
podman inspect test > /tmp/test-test-podman.txt
podman rm test
```

```
$ podman logs test
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
TERM=xterm
container=podman
containers=podman
foo=bar
HOSTNAME=b224b3dc9ab7
HOME=/root
```
```
**Additional information you deem important (e.g. issue happens only occasionally):**

I've tested it on FC31 and FC32. I have not tested with podman-remote

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.13.15
Built:        Wed Sep 30 21:51:15 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: d9f047cb413248e30a1ec560547d9b203396c31b'
  cpus: 8
  distribution:
    distribution: fedora
    version: "31"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 21528
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 21528
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.8.11-100.fc31.x86_64
  linkmode: dynamic
  memFree: 1175146496
  memTotal: 16381120512
  ociRuntime:
    name: crun
    package: crun-0.15-5.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.15
      commit: 56ca95e61639510c7dbd39ff512f80f626404969
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/21528/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-1.1.4-1.fc31.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.1.0
      SLIRP_CONFIG_VERSION_MAX: 1
  swapFree: 8155656192
  swapTotal: 8252289024
  uptime: 116h 24m 10.29s (Approximately 4.83 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/psakar/.config/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 0
    stopped: 5
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/psakar/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 67
  runRoot: /run/user/21528/run
  volumePath: /home/psakar/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1601495475
  BuiltTime: Wed Sep 30 21:51:15 2020
  GitCommit: ""
  GoVersion: go1.13.15
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.1.1-3.fc31.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Laptop

**Comment by psakar** [comment]
Related to https://github.com/testcontainers/testcontainers-java/issues/2088

**Comment by rhatdan** [comment]
@baude @ashley-cui @jwhonce PTAL

**Comment by jwhonce** [comment]
I was unable to recreate on master, I believe it was taken care of in cde367c1c0b348366fcaf4d8fac3b753de8456d5

**Comment by jwhonce** [comment]
@rhatdan @mheon Does this commit need to be back ported to other branches?

**Comment by rhatdan** [comment]
No I don't think so.  We should just get ready for another release.
