### ISSUE TITLE
podman ps --format does not interpret control characters

### ISSUE THREAD

**Issue by Token00** [containers/podman#7928]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

The podman ps --format command does not interpret control characters.

Example: podman ps --format "table {{.Names}}\t{{.Image}}\t{{.ID}}

In docker it does, which allows for much better formatting.

**Steps to reproduce the issue:**

1. Run the command stated above

2. Enjoy ugly formatting

3. Try the same with docker

**Describe the results you received:**
<img width="523" alt="podman" src="https://user-images.githubusercontent.com/60583202/95120903-8aa75e00-074e-11eb-9a3a-995b9c9e5fa8.png">

**Describe the results you expected:**
<img width="530" alt="docker" src="https://user-images.githubusercontent.com/60583202/95120912-8ed37b80-074e-11eb-9139-a1be3a266692.png">

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.13.15
Built:        Fri Oct  2 16:30:39 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.21-1.el8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: fa5f92225c4c95759d10846106c1ebd325966f91-dirty'
  cpus: 8
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: journald
  hostname: ech0.ru
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-193.19.1.el8_2.x86_64
  linkmode: dynamic
  memFree: 221593600
  memTotal: 16797290496
  ociRuntime:
    name: runc
    package: runc-1.0.0-145.rc91.git24a3cf8.el8.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 8437444608
  swapTotal: 8464101376
  uptime: 62h 41m 56.49s (Approximately 2.58 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 6
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 7
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1601649039
  BuiltTime: Fri Oct  2 16:30:39 2020
  GitCommit: ""
  GoVersion: go1.13.15
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.1.1-4.el8.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

CentOS 8.2 minimal on dedicated server

**Comment by rhatdan** [comment]
@jwhonce More table issues....

**Comment by eiffel-fl** [comment]
I have the same problem.
Maybe I can try to do it?!

**Comment by Token00** [comment]
Here's a reference how docker does it https://github.com/docker/docker-ce/blob/e31504a75c8dfe9d47d5419f77bd314987c691af/components/cli/cli/command/formatter/formatter.go

Seems to be this part:
```
c.finalFormat = strings.Trim(c.finalFormat, " ")
r := strings.NewReplacer(`\t`, "\t", `\n`, "\n")
c.finalFormat = r.Replace(c.finalFormat)
```

**Comment by jwhonce** [comment]
@Token00 This fix is rolling out across the podman commands now.

**Comment by jwhonce** [comment]
Fixed by https://github.com/containers/podman/pull/7973
