### ISSUE TITLE
When specifying one only container published port, the host port is not random but equal to containers one

### ISSUE THREAD

**Issue by sshnaidm** [containers/podman#7947]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
When specifying one only container published port - `--publish 9000`, the host port is not random but equal to containers one. In docs it's mentioned that host port will be a random port.

**Steps to reproduce the issue:**

1. `podman run -dit --name zzz -p 9000 alpine sleep 2m`

2. `podman inspect zzz`
**Describe the results you received:**
```json
"PortBindings": {
                "9000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "9000"
                    }
                ]
            },
```

**Describe the results you expected:**
I'd expect host port to be random as it's mentioned in documentation, like:
```json
"PortBindings": {
                "9000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "43276"
                    }
                ]
            },
```

**Additional information you deem important (e.g. issue happens only occasionally):**
It happens in podman version 2, in podman versions 1 it's a real random port.
**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 4
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: ubuntu20-vmtest
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.4.0-48-generic
  linkmode: dynamic
  memFree: 1591517184
  memTotal: 2083717120
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.4
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 0
  swapTotal: 0
  uptime: 1m 29.64s
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/ubuntu/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/ubuntu/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 22
  runRoot: /run/user/1000/containers
  volumePath: /home/ubuntu/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.1.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 2.1.1~2 amd64 [installed]
podman/unknown 2.1.1~2 arm64
podman/unknown 2.1.1~2 armhf
podman/unknown 2.1.1~2 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS: Ubuntu 20.04

Related to issue of idempotency in ansible podman modules: https://github.com/containers/ansible-podman-collections/issues/116

**Comment by mheon** [comment]
I'll take this one.

**Comment by sshnaidm** [comment]
@mheon is there a reason behind a "randomness" of host port? What is it useful for? Wouldn't be more logical to set the same port if only one port was configured (as it's behavior now in 2.x)?
Probably this is not a bug, but feature. (Just need to update docs about it)

**Comment by mheon** [comment]
The logic, from what I can tell, is that this makes it trivial to launch a large batch of containers that all want to use the same port, and safely expose all of them to the internet. I could run a dozen HTTP servers with `podman run -p 80 -d alpine` and all of them would safely assign a host port.
