### ISSUE TITLE
REST API Method Not Allowed with Podman 2.0.5 and Grype

### ISSUE THREAD

**Issue by fatherlinux** [containers/podman#7950]
/kind bug

**Description**

Using Grype (https://toolbox.anchore.io/) with CentOS Stream 8 and Podman 2.0.5, the Docker Compatible REST endpoint returns a Method not Found error.

**Steps to reproduce the issue:**

1.grype registry.access.redhat.com/ubi8/ubi

Or

1. grype centos

**Describe the results you received:**

From terminal: 
```
[root@centos-stream ~]# grype centos
 ✔ Vulnerability DB     [no update available]
 ✔ Pulled image         
 ⠋ Loading image        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ [requesting image from docker]
[0018] ERROR failed to catalog: could not fetch image 'centos': unable to save image tar: Error response from daemon: Method Not Allowed
```

From debug log:

```
INFO[0071] Failed Request: (405:Method Not Allowed) for GET:'/v1.40/images/get?names=centos'
```

**Describe the results you expected:**

Results similar to video here: https://toolbox.anchore.io/

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.0.5
API Version:  1
Go Version:   go1.14.7
Built:        Thu Sep 24 13:58:13 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.1
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.20-2.module_el8.3.0+475+c50ce30b.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.20, commit: 1019ecdeda3936be22162bb1cca308192145de53'
  cpus: 1
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: centos-stream.dc2.crunchtools.com
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-236.el8.x86_64
  linkmode: dynamic
  memFree: 347070464
  memTotal: 1905127424
  ociRuntime:
    name: runc
    package: runc-1.0.0-68.rc92.module_el8.3.0+475+c50ce30b.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 2147479552
  swapTotal: 2147479552
  uptime: 17m 22.1s
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 2
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1600970293
  BuiltTime: Thu Sep 24 13:58:13 2020
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.0.5
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.5-5.module_el8.3.0+512+b3b58dca.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtual machine with CentOS 8 Stream. I suspect that this could be as simple as accepting 1.40 as the version number?

**Comment by rhatdan** [comment]
Any chance you could try this against the main branch.  I believe we have load support now?
@jwhonce @baude PTAL

**Comment by baude** [comment]
Ok, dug into this a little.  The problem is that they are hitting an endpoint that doesnt exist because we were not able to save/load multiple images in a single tarball. I think @vrothberg worked on this recently.  @vrothberg lets talk about this one, coach me up if we can do this.

**Comment by vrothberg** [comment]
The loading part is working transparently (https://github.com/containers/podman/blob/master/libpod/runtime_img.go#L279) as we are trying a couple of formats in a specific order.

The saving part, however, needs to know whether we are creating a multi-image archive or a single-image archive with additional tags. On the CLI, we added the `--multi-image-archive, -m` flag to `podman save`. To create such a multi-image archive, we need to call libpod's `func (ir *Runtime) SaveImages(ctx context.Context, namesOrIDs []string, format string, outputFile string, quiet bool) (finalErr error)`. I guess that's what the compat endpoint may need to do.

**Comment by baude** [comment]
added test
