### ISSUE TITLE
podman-remote run and podman-remote start --attach does not handle detaching with detach keys correctly

### ISSUE THREAD

**Issue by Luap99** [containers/podman#7979]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`podman-remote run` and `podman-remote start --attach` does not handle detaching with the detach keys `<ctrl-p><ctrl-q>` correctly.

**Steps to reproduce the issue:**

For `podman-remote run`:

1. Start the podman service

2. `podman-remote run -it alpine sh`

3. detach with `<ctrl-p><ctrl-q>`

For `podman-remote start --attach`:

1. Start the podman service

2. `podman-remote create -it --name test alpine sh`

3. `podman-remote start --attach test`

4. detach with `<ctrl-p><ctrl-q>`

**Describe the results you received:**

The process does not exit.

**Describe the results you expected:**

The process should exit with exitcode 0.

**Additional information you deem important (e.g. issue happens only occasionally):**

With `podman-remote start --attach` the error happens only if the container is not already started.
It also works fine with `podman-remote attach`

If I hit enter after detaching I get this error: `ERRO[0003] failed to write input to service: write unix @->/run/user/1000/podman/podman.sock: write: broken pipe`
So it looks like it does detach and closes the pipe but the process does not exit. It instead waits for the container to exit.

**Output of `podman version`:**

```
$ podman-remote version
Client:
Version:      2.2.0-dev
API Version:  2.0.0
Go Version:   go1.14.9
Git Commit:   71d675a164ee64111db1a9214673a3498b3aa123
Built:        Fri Oct  9 13:10:16 2020
OS/Arch:      linux/amd64

Server:
Version:      2.2.0-dev
API Version:  2.0.0
Go Version:   go1.14.9
Git Commit:   71d675a164ee64111db1a9214673a3498b3aa123
Built:        Fri Oct  9 13:10:05 2020
OS/Arch:      linux/amd64
```

**Comment by andylibrian** [comment]
Let me look into this

/assign
