### ISSUE TITLE
create network --label and run --restart unless-stopped are not compatible with Docker.

### ISSUE THREAD

**Issue by HarriL** [containers/podman#7989]
**Description**
/kind bug
You can not just install podman-docker and expect podman to be compatible.

 I installed podman-docker and got four compatibility issues from a Docker compatible installation kit.
	1. Build Bridge
	Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
	Error: unknown flag: --label
	2. Start container1
	Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
	Error: the unless-stopped restart policy is not supported: invalid argument
	3. Start container2
	Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
	Error: the unless-stopped restart policy is not supported: invalid argument
	4. Start container3
	Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
	Error: the unless-stopped restart policy is not supported: invalid argument 

**Steps to reproduce the issue:**
1. Install CentOS 8.2.2004
2. Install podman-docker
3. Run `docker network create --label "abc" --label "xyz" target-name
4. Run docker run ... --restart unless-stopped ...

**Describe the results you received:**
3. Error: unknown flag: --label
4. Error: the unless-stopped restart policy is not supported: invalid argument
**Describe the results you expected:**
3. Accept metadata "abc" and "zyz" in the network container as Docker defines and as other type of containers does.
4. The error message is wrong, this is not a restart. Actually this is **not restart** ! And Podman already works as this argument asks it to do! This argument means that after the "podman stop" command do not start this container in a reboot. And that is how podman works already. Remove the error and just do nothing. This way the behavior of podman is correct and the argument is handled "correctly".

**Additional information you deem important (e.g. issue happens only occasionally):**

#### Raises error:
> Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
> 	Error: unknown flag: --label

#### Expected to handle metadata argument(s): 
--label argument1 --label argument2
#### Docker definition: [Link to Docker CLI reference](https://docs.docker.com/engine/reference/commandline/network_create/)

The second one seems to be a  misunderstanding of what does Docker's argument unless-stopped really means/does.
#### Raises error:
	Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
	Error: the unless-stopped restart policy is not supported: invalid argument
NOTE: the community has misunderstood what this argument does and means! it is related to _docker stop_ and nothing to with Docker Engine! **It means that if you have stopped a container it does not restart the container automatically after reboot!**
**Expected** to not raise an error, but instead, **just ignore this argument in Podman** without raising an error!
**Root cause:** Podman does not start containers automatically after reboot as Docker does and that is the same that Docker unless-stopped does in Docker!
**Reasoning**: It is annoying to get correct "unless-stopped" behavior natively by Podman and at the same time it does raise an error on the argument that askes literally to do that!

## Environment 

```
podman version 1.6.4
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
Linux ... 4.18.0-193.19.1.el8_2.x86_64
```

```
Docker version 19.03.12, build 48a66213fe
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
Linux ... 3.10.0-1127.19.1.el7.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Comment by zhangguanzhang** [comment]
I think you should try with the latest version, maybe you need update your repo, and install the latest podman by your package command

**Comment by mheon** [comment]
We still don't support labels on networks (going to need the network
rewrite for that) but unless-stopped was added (I want to say in 2.x?).

**Comment by rhatdan** [comment]
@mheon What is stopping us from adding --label to the network now?

**Comment by mheon** [comment]
No place to store them. We only store networks as CNI conflist files, and there is no provision for storing a label in those files (and no provision for comments, so we can't hack them in easily either)

**Comment by rhatdan** [comment]
@mheon should we add this data to database then?

**Comment by mheon** [comment]
That's what we have to do - the "network rewrite" I keep talking about it basically moving network logic inside Libpod so we can use the DB to store information on a network and lessen our dependence on CNI for what we do and do not support.

Doing it right is probably a sprint worth of work, minimum, for a team member, though. I'd be happy to take it on early next year once volume plugins are done if the priorities work out right.

**Comment by rhatdan** [comment]
@HarriL @afbjorklund @mheon Have we gotten any closer on this one?

**Comment by mheon** [comment]
Network label support has been added to master, we can close

**Comment by afbjorklund** [comment]
For now we have removed `--label` and mtu for podman (only used for docker) in the minikube "kic" driver, once 8494bcb866f1c0978cbe35c62c1e3312a91040b4 and b1b35707aae57d299933f029eb0adc0a9000f97f lands in a release (3.0?) and that release is started to used we can revisit... Also needs the ls fix for the `--filter`.
