### ISSUE TITLE
podman equavalent for `docker trust inspect ...`

### ISSUE THREAD

**Issue by marcofranssen** [containers/podman#8006]
/kind feature

**Description**

I'm searching for the equivalent of `docker trust inspect alpine`. For compatibility with docker I think that should be added. furthermore I can't find any documentation with regards to enabling content trust.

In Docker this can be done using `DOCKER_CONTENT_TRUST=1`.

I have checked this using the `quay.io/podman/stable:latest` with image id `4c0f1fd71288`.

**Comment by rhatdan** [comment]
Podman does not support Notary.  This would require community to get support.  It does support Simple Signing.

podman image trust 
podman image sign
