### ISSUE TITLE
Weird Userspace Bug Related to Kube YAML Format

### ISSUE THREAD

**Issue by bcstinch** [containers/podman#8017]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

With specifically the postgres container, postgres within the container cannot be run as root. When running this container via podman cli, it works fine. When you then export that container in a kube yaml file, then try and do a podman play kube, it will throw an error related to postgres not being able to run as root.

**Steps to reproduce the issue:**

https://pastebin.pl/view/3d0f60f1

**Additional information you deem important (e.g. issue happens only occasionally):**

I am not sure if this bug is specifically related to high uid/gid mappings.

**Output of `podman version`:**

```
podman-2.1.0
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on fedora server 32

**Comment by Luap99** [comment]
Can you share the kube yaml file and also the error you are receiving?

**Comment by rhatdan** [comment]
I am closing this for a lack of followup.  Reopen if you can provide the information requested.
