### ISSUE TITLE
error when runlabel is missing

### ISSUE THREAD

**Issue by langdon** [containers/podman#8038]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. `podman container runlabel run registry.access.redhat.com/ubi8/php-73`
1. `panic: runtime error: index out of range [0] with length 0`
</snip>

OR
1. `podman container runlabel --display run registry.access.redhat.com/ubi8/php-73`
1. `panic: runtime error: index out of range [0] with length 0`
</snip>

**Describe the results you received:**
index out of range

**Describe the results you expected:**
"Image does not have a run label" or some such.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.1.1-12.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
I'll grab this one.

**Comment by zhangguanzhang** [comment]
@mheon  It’s daytime in our place, if you don’t submit the pr in time, can I take it?
