### ISSUE TITLE
Not able to access over web-ui

### ISSUE THREAD

**Issue by sonuyos** [containers/podman#8049]
I have a server with podman installed,

And this is the command i run.

`podman run -dt --name=deluge --net=host -p 0.0.0.0:5362:5363 docker.io/linuxserver/deluge`

But whenever i try to access the Web-Ui it just says the connection is reset.

Neither Port works, i even tried to curl to the port from within the server, but it just says connection reset.

I cannot access the webui at all, same for sabnzbd as well. Am i missing something?

I am sure i am doing something wrong, but i am unable to understand what i am doing wrong.

**Comment by Luap99** [comment]
This is not a podman problem. Did you follow the instructions here: https://docs.linuxserver.io/images/docker-deluge?
It says you shouldn't use the `-p` option and the url is `http://SERVER-IP:8112`
