### ISSUE TITLE
how to login my repository

### ISSUE THREAD

**Issue by lovebaby979** [containers/podman#8051]
/kind feature

**Description**
podman login my repository report error,how to setting?

error:
podman login registry.my.com:31231
Authenticating with existing credentials...
Existing credentials are invalid, please enter valid username and password
Username (admin): admin
Password:
Error: error authenticating creds for "registry.my.com:31231": pinging docker registry returned: Get https://registry.my.com:31231/v2/: http: server gave HTTP response to HTTPS client

**Comment by Luap99** [comment]
Try `podman login --tls-verify=false registry.my.com:31231`, by default podman will try to connect with https.

**Comment by lovebaby979** [comment]
@Luap99 Thank you!
