### ISSUE TITLE
Unable to run podman via user (without sudo or root access).

### ISSUE THREAD

**Issue by sonuyos** [containers/podman#8052]
I just restarted the server and logged in as user.

Tried to execute this command

`podman run -dt -v ~/.config/rutorrent:/config --net=host docker.io/linuxserver/rutorrent`

And it wouldn't lemme start, throws error 

`ERRO[0000] cannot mkdir /run/user/0/libpod: mkdir /run/user/0/libpod: permission denied
`

I can however run it as admin and it works fine. Am i doing anything wrong?

**Comment by Luap99** [comment]
Did you change to this user with `su`?

**Comment by sonuyos** [comment]
@Luap99 i have not changed anything.

I did put 777 on /run/user/ and both worked, but at a time only 1 works, for some reason when 1 works other says

`ERRO[0000] could not set sticky bit on /run/user/0/libpod: chmod /run/user/0/libpod: operation not permitted`

even tho both users userid is

1000 & 1001

**Comment by Luap99** [comment]
How do you login? Are you using `su `or `sudo`?

What is the output from `printenv XDG_RUNTIME_DIR`?

**Comment by sonuyos** [comment]
yes i did `su user`.

output is for both users.

`/run/user/0`

**Comment by Luap99** [comment]
You cannot use `su` as this does not create a proper user session. It also leaks the `XDG_RUNTIME_DIR` env var from the root user (/run/user/0).
Try to change the user with `su --login` or `sudo -i -u user`.

**Comment by sonuyos** [comment]
Alright, thanks i will try 👍

**Comment by sonuyos** [comment]
@Luap99 i have another query, say i am running deluge or rutorrent docker with /config set to .config/rutorrent

The files are set with permission denied (presumably root permission), anyway to have access to the files?

**Comment by Luap99** [comment]
If you running on a system with selinux enabled you have to mount the volume with the `Z` option, e.g. `-v ~/.config/rutorrent:/config:Z`
This blog post https://www.redhat.com/sysadmin/rootless-podman-makes-sense describes how permission works as rootless. Another option is to use the `--userns keep-id`.

**Comment by sonuyos** [comment]
@Luap99 I cannot find `--userns keep-id`. in podman --help

**Comment by Luap99** [comment]
Its for the `podman create/run` command

**Comment by sonuyos** [comment]
Yes, i tried it,

podman --userns keep-id run -dt -v ~/.config/deluge:/config
docker.io/linuxserver/deluge

It doesn't detect.

**Comment by Luap99** [comment]
`podman run --userns keep-id  -dt -v ~/.config/deluge:/config`

**Comment by sonuyos** [comment]
Doesnt work :(

snthostings@seedbox04:~/.config/deluge$ rm -rf core.conf
rm: cannot remove 'core.conf': Permission denied

**Comment by mheon** [comment]
You'll likely need '--security-opt label=disable' for this container.

**Comment by sonuyos** [comment]
That didnt work either :(

I ran this - podman run --security-opt label=disable -dt --net=host -v
~/.config/deluge:/config docker.io/linuxserver/deluge

And then

podman stop -a
cd .config/deluge/
rm -rf web.conf

Gives - rm: cannot remove 'web.conf': Permission denied

**Comment by sonuyos** [comment]
The file is being created under uknown permission.

-rw------- 1 100999 100999  598 Oct 17 20:20 web.conf

`podman run --net=host --security-opt label=disable -e PUID=1000 -e PGID=1000 -v ~/.config/deluge:/config docker.io/linuxserver/deluge
`

**Comment by mheon** [comment]
What UID are you running as in the container? What UID are you using on the host?

**Comment by sonuyos** [comment]
I am trying to run as 1000 as that's the uid of my user.

I tried to use udocker now, and without setting uid, it automatically sets
the .config file under my user and I can delete or edit the files. I don't
understand why it wouldn't work with podman.

I cannot run udocker detached.

**Comment by mheon** [comment]
It would work with *root* Podman. As rootless, Podman uses a user namespace - which alters the users inside the container. By default, in a rootless Podman container, UID 0 is mapped to the UID of the user that launched Podman, and UIDs 1 to 65536 are mapped to a range of 65535 UIDs assigned to that user in `/etc/subuid`. With the `--userns=keep-id` flag, Podman will ensure that the user that launched Podman has the same UID in the container - so UID 1000 inside and outside the container would match - while the remaining 65535 UIDs around it are, again, drawn from the range allocated in `/etc/subuid`.

If your intention is to run as UID 1000 inside the container, you will need `--userns=keep-id`. I suspect you'll also need `--label=disable` to ensure that SELinux won't object to mounting volumes into the container.

**Comment by sonuyos** [comment]
Yes, that works :D Thanks a ton @mheon  <3

**Comment by rhatdan** [comment]
The preferable SELinux fix would be to use `-v ~/.config/deluge:/config:z` option, if the deluge directory is going to be shared between multiple containers rather then --label disabled.  You can us the `:Z` option if the ~/.config/deluge directory is only going to be used within one container.

**Comment by rhatdan** [comment]
BTW To remove a file created by a different user within the user namespace, you need to enter the user namespace

podman unshare rm web.conf
