### ISSUE TITLE
Cannot read container mount files

### ISSUE THREAD

**Issue by Zeranoe** [containers/podman#8057]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm trying to use postgres in a podman container with a custom mounted data directory. I'm able to create the container and the database works, but I lose the ability to read any files in the database data folder from the launching user account.

**Steps to reproduce the issue:**

1. `mkdir data`

2. `podman run --publish 5432 -e POSTGRES_PASSWORD=password -v ./data:/var/lib/postgresql/data:Z -it --rm postgres:13`

**Describe the results you received:**

Running `ls data` gives a permissions denied, but running `sudo ls -l data` shows that all the files inside were created with 100998:100998, and have `drwx` permissions.

**Describe the results you expected:**

With postgres running the processes as non-root, this is the result I expect.

**Additional information you deem important (e.g. issue happens only occasionally):**

So far I've tried setting `--user root` and other combinations to attempt to get the container to run the postgres process as my user ID, but nothing seems to work and I'm at a loss as to how this is supposed to operate.

The following seem to be related to this:
* https://www.redhat.com/sysadmin/rootless-podman-makes-sense
* https://github.com/docker-library/postgres/pull/253

The article seems very close, but in reverse (unable to write inside the image).

**Output of `podman version`:**

`podman version 2.1.1`

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-2.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 81d18b6c3ffc266abdef7ca94c1450e669a6a388'
  cpus: 8
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: journald
  hostname: f32
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.8.15-201.fc32.x86_64
  linkmode: dynamic
  memFree: 6770266112
  memTotal: 16662794240
  ociRuntime:
    name: crun
    package: crun-0.15-5.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.15
      commit: 56ca95e61639510c7dbd39ff512f80f626404969
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 2
  swapFree: 8401186816
  swapTotal: 8401186816
  uptime: 30h 40m 58.71s (Approximately 1.25 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: ~/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 1
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: ~/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 8
  runRoot: /run/user/1000/containers
  volumePath: ~/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1601494271
  BuiltTime: Wed Sep 30 15:31:11 2020
  GitCommit: ""
  GoVersion: go1.14.9
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

`podman-2.1.1-7.fc32.x86_64`

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
What user is the application in the container running as? It doesn't seem to be running as root, if you're seeing files created as a UID not equal to the run that ran Podman.

One option would be to use `--userns=keep-id` and run the app in the container as the same ID as your user. The `--userns=keep-id` flag ensures that your UID inside the container is mapped to the same UID outside the container so there should be no permissions issues there. This could be a matter of using the `--user` flag, or possibly that image drops privileges and runs as a non-root user (you'll need to consult documentation for the image in that case)

**Comment by Zeranoe** [comment]
I believe the server in the container is running as the `postgres` user.

Attempting what you suggested:
```
$ podman run --rm -it -v ./data:/var/lib/postgresql/data:Z --user $USER --userns=keep-id postgres:13
Error: unable to find user zeranoe: no matching entries in passwd file
```

**Comment by mheon** [comment]
You'll need to either add your user to the container, or use your UID instead of username as an argument to `--user`

**Comment by Zeranoe** [comment]
Thank you so much! The following worked:
`podman run --rm -it -v ./data:/var/lib/postgresql/data:Z --user $(id -u) -e POSTGRES_PASSWORD=pw --userns=keep-id postgres:13`
