### ISSUE TITLE
REST APIv2 - log does not contain EOL

### ISSUE THREAD

**Issue by psakar** [containers/podman#8058]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Container logs provided by REST API does not contain EOL (\n)

**Steps to reproduce the issue:**

1. To be determined (I've found out by debugging test containers Log output Wait Strategy

**Describe the results you received:**
Log lines are provided without EOL

**Describe the results you expected:**
Log lines are provided with EOL

**Additional information you deem important (e.g. issue happens only occasionally):**

```
diff --git a/pkg/api/handlers/compat/containers_logs.go b/pkg/api/handlers/compat/containers_logs.go
index d24b7d959..c01456454 100644
--- a/pkg/api/handlers/compat/containers_logs.go
+++ b/pkg/api/handlers/compat/containers_logs.go
@@ -148,7 +148,7 @@ func LogsFromContainer(w http.ResponseWriter, r *http.Request) {
 			frame.WriteString(line.Time.Format(time.RFC3339))
 			frame.WriteString(" ")
 		}
-		frame.WriteString(line.Msg)
+		frame.WriteString(line.Msg + "\n")
 
 		if writeHeader {
 			binary.BigEndian.PutUint32(header[4:], uint32(frame.Len()))
```

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.13.15
Built:        Wed Sep 30 21:51:15 2020
OS/Arch:      linux/amd64
```

**Comment by psakar** [comment]
Related to https://github.com/containers/podman/issues/7927

**Comment by rhatdan** [comment]
Can you open this as a PR rather then an issue?

@jwhonce @baude PTAL

**Comment by crunchtime-ali** [comment]
@rhatdan @psakar I created the suggested change as a PR here https://github.com/containers/podman/pull/8083
If there is anything else I can help you with just tell me.

**Comment by rhatdan** [comment]
Awesome job @crunchtime-ali. Thanks.
