### ISSUE TITLE
Podman pull --creds does not work as expected for registry mirrors

### ISSUE THREAD

**Issue by saschagrunert** [containers/podman#8072]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Configured registry mirrors seem to break authentication. For example if we define:

```
[[registry]]
prefix = "our-registry.com"
location = "registry.local"
```

Then authenticate against `our-registry.com` and then pull an image like this:

```
> podman pull --creds some-credentials  our-registry.com/image:version
```

It will not work because the mirroring changes the location internally. We somehow have to tage the original location into account, too, or we pre-check the registry configuration on `podman login`.

**Output of `podman version`:**

```
2.1.1
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Comment by vrothberg** [comment]
What is the expected behaviour?

Are the specified credentials (e.g., `--creds XXX`) ignored?

**Comment by saschagrunert** [comment]
I think I messed up the issue description. Closing for now, sorry for the noise.
