### ISSUE TITLE
APIv2: /info is getting slower

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#8076]
The "ten /info requests" timing test is getting slower:
https://github.com/containers/podman/blob/36682115b0f3f5f7cfcc6bc4580e5a7435b9a4d8/test/apiv2/01-basic.at#L62-L78
It was bumped up from 5 to 7 seconds last week, and is about to get bumped up to 10 (#8065) because it is causing CI flakes:
  * PR #8061
    * [10-19 11:24](https://api.cirrus-ci.com/v1/task/5094534637944832/logs/main.log)
    * [10-19 11:07](https://api.cirrus-ci.com/v1/task/4907117565968384/logs/main.log)
    * [10-19 11:01](https://api.cirrus-ci.com/v1/task/6711281124114432/logs/main.log)
  * PR #8044
    * [10-17 09:41](https://api.cirrus-ci.com/v1/task/6652761322291200/logs/main.log)
  * PR #8021
    * [10-14 14:10](https://api.cirrus-ci.com/v1/task/5011470339538944/logs/main.log)
  * PR #7126
    * [10-20 10:07](https://api.cirrus-ci.com/v1/task/6139620037492736/logs/main.log)
    * [10-20 09:38](https://api.cirrus-ci.com/v1/task/6675604374290432/logs/main.log)

This issue is a placeholder so the slowdown can be investigated and, perhaps, addressed.

**Comment by zhangguanzhang** [comment]
maybe could close this ?

**Comment by TomSweeneyRedHat** [comment]
@edsantiago PTAL

**Comment by rhatdan** [comment]
Closing do to lack of activity.
