### ISSUE TITLE
Headings missing when using podman...--format table...

### ISSUE THREAD

**Issue by jwhonce** [containers/podman#8079]
/kind bug

**Description**

During podman 1.9->2.0 formatting with table directive was compromised. The last piece missing is printing headers on table columns.

**Steps to reproduce the issue:**

1. bin/podman image ls --format 'table {{.ID}}' 

**Describe the results you received:**
```
f81b045129db                                                                                                                        
c8f0cfab5214                                                                                                                        
af748fb2ce8f
```

**Describe the results you expected:**
```
ID
f81b045129db                                                                                                                        
c8f0cfab5214                                                                                                                        
af748fb2ce8f
```

**Comment by rhatdan** [comment]
I thought this was fixed by your --table pr.  Are you still working on it?

**Comment by rhatdan** [comment]
Closing, reopen if I am mistaken.
