### ISSUE TITLE
Does OS Security Policy profiles affect Podman

### ISSUE THREAD

**Issue by remyluslosius** [containers/podman#8087]
**Is this a BUG REPORT? **

/kind bug

**Description**

Unable to use podman to create container. 

```
rootuser ~#] podman run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" --name elasticsearch docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.2-amd64
```
**Output error:**

```
Error: /usr/bin/runc: error while loading shared libraries: libpthread.so.0: cannot open shared object file: Operation not permitted: OCI runtime permission denied error
```
**Steps to reproduce the issue:**

1. Install RHEL 8.3 minimal and Container Management environment with Security Policy enabled and DISA STIG profile/content.

2. 
```
rootuser ~#] fips-mode-setup --check
FIPS mode is enabled.

rootuser ~#] update-crypto-policies --show
FIPS:OSPP
```
**Describe the results you expected:**
I was expected podman to create the container successfully. 

``podman run`` had no issues creating a container with the same security policy profile in RHEL 8.2 . However, the latest podman version in RHEL 8.2 is 1.9.x which doesn't provide support for IPv6.

**Additional information you deem important (e.g. issue happens only occasionally):**

1. The error is consistent if the system was provisioning with security profile is enabled. Log file attached

2. Podman works fine with if the system was built without a security profile.

**Output of `podman version`:**

```

Version:      2.0.0-rc7
API Version:  1
Go Version:   go1.14.2
Built:        Wed Dec 31 19:00:00 1969
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.0
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.18-1.module+el8.3.0+7084+c16098dd.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.18, commit: 7fd3f71a218f8d3a7202e464252aeb1e942d17eb'
  cpus: 1
  distribution:
    distribution: '"rhel"'
    version: "8.3"
  eventLogger: file
  hostname: rhelpod.vnet1.net
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-221.el8.x86_64
  linkmode: dynamic
  memFree: 995037184
  memTotal: 1905205248
  ociRuntime:
    name: runc
    package: runc-1.0.0-66.rc10.module+el8.3.0+7084+c16098dd.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 2210394112
  swapTotal: 2210394112
  uptime: 4h 49m 4.84s (Approximately 0.17 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 1
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Wed Dec 31 19:00:00 1969
  GitCommit: ""
  GoVersion: go1.14.2
  OsArch: linux/amd64
  Version: 2.0.0-rc7

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.0-0.9.rc7.module+el8.3.0+7084+c16098dd.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No, podman-2.0.0-0.9.rc7 is the latest version in RHEL 8.3

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Both Virtualbox 6.1 and VMWare vSphere 6.5
[debug.log](https://github.com/containers/podman/files/5412215/debug.log)

**Comment by mheon** [comment]
I recommend you file a Bugzilla about this one - Podman should definitely be working with FIPS mode enabled.

**Comment by rhatdan** [comment]
Would be interesting to see if this works with crun.  But runc was tested with fips mode.

Could you see if this works with a --privileged container?
If yes, then check to see if SELinux is causing issues.

**Comment by remyluslosius** [comment]
@rhatdan, adding --privileged=true results with the same error message. I'll check Bugzilla. Thanks

**Comment by rhatdan** [comment]
@remyluslosius Any update to this?

**Comment by remyluslosius** [comment]
@rhatdan, I'm waiting for the RHEL 8.3.1 release. You commented on my [bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1890707) request that the latest RHEL release will have crun.  And since I enable CGroups v2, the default OCI runtime for podman changes to ``crun``.  

```
rootuser ~#] podman version
Error: default OCI runtime "crun" not found: invalid argument
```

The error with CGroups v1 was:
```
Error: /usr/bin/runc: error while loading shared libraries: libpthread.so.0: cannot open shared object file: Operation not permitted: OCI runtime permission denied error
```

**Comment by rhatdan** [comment]
Ok let's handle this in the bugzilla, this is not an upstream issue.
