### ISSUE TITLE
Podman wait man page is obsolete for version 2.x

### ISSUE THREAD

**Issue by alitvak69** [containers/podman#8088]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman wait command man page displayed on [Read The Docs](https://podman.readthedocs.io/en/latest/markdown/podman-wait.1.html) and distributed with podman package 2.x is obsolete as it doesn't reflect changes to the interval option format.

**Steps to reproduce the issue:**

1. Execute following command:
`root@foo:~# podman wait -i 200000  --latest`

**Describe the results you received:**
`Error: invalid argument "200000" for "-i, --interval" flag: time: missing unit in duration "200000"`

**Describe the results you expected:**
Wait starts, no error.

**Additional information you deem important (e.g. issue happens only occasionally):**
The actual command in version 2.x should be 

`root@foo:~# podman wait -i 200ms  --latest` 

Where numeric value follows a time unit (s,ms,us, ... etc)

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Wed Dec 31 16:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 48
  distribution:
    distribution: ubuntu
    version: "18.04"
  eventLogger: journald
  hostname: container2-chi.xcastlabs.net
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.15.0-47-generic
  linkmode: dynamic
  memFree: 49324331008
  memTotal: 101043154944
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 6446641152
  swapTotal: 6446641152
  uptime: 599h 59m 0.38s (Approximately 24.96 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 1
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 22
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 0
  BuiltTime: Wed Dec 31 16:00:00 1969
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 2.1.1~2 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 18.04 amd64

**Comment by zhangguanzhang** [comment]
interval ，must endwith time unit, like ms s h

**Comment by alitvak69** [comment]
> interval ，must endwith time unit, like ms s h

The ticket is about a documentation changes.  After our jobs started failing to start we figured out what was wrong.  However current man pages don't reflect the change.  Podman 1.x wait works without time unit with number in micro seconds.

**Comment by rhatdan** [comment]
This is not a documentation failure but a failure in code.  We should allow for the specification of micro seconds.

**Comment by mheon** [comment]
This sounds like a bug if it worked in 1.x but broke in 2.x - I don't mind
keeping the new units but if none are present we should default to whatever
1.x did.

**Comment by rhatdan** [comment]
#8093 fixed this.
