### ISSUE TITLE
Missing resolv.conf in WSL2

### ISSUE THREAD

**Issue by c-goes** [containers/podman#8089]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When installing [Ubuntu 20.04 rootfs](https://wiki.ubuntu.com/WSL#Installing_Ubuntu_on_WSL_via_rootfs) for WSL
and Podman 2.1.1 no container starts because of missing `/run/systemd/resolve/resolv.conf`.

**Steps to reproduce the issue:**

1. [Install Ubuntu 20.04 via tar in WSL2](https://wiki.ubuntu.com/WSL#Installing_Ubuntu_on_WSL_via_rootfs)

2. [Install Podman](https://www.redhat.com/sysadmin/podman-windows-wsl2)

3. Run a container as root: `podman run hello-world`

**Describe the results you received:**

```
# podman run hello-world
Error: error creating resolv.conf for container 59dc1c8f45abe1b1d7c880a21e315948ee36a5951be6be31945334b4a87ec716: unable to read /run/systemd/resolve/resolv.conf: open /run/systemd/resolve/resolv.conf: no such file or directory
```

**Describe the results you expected:**

Container starts without errors.

**Additional information you deem important (e.g. issue happens only occasionally):**

It works if I run `cp /etc/resolv.conf /run/systemd/resolve/resolv.conf` beforehand. But I need to repeat this every time I restart WSL.

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 8
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: file
  hostname: wslhost
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.19.128-microsoft-standard
  linkmode: dynamic
  memFree: 6718386176
  memTotal: 8345993216
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 25m 40.16s
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 0
    stopped: 6
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 14
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 2.1.1~2 amd64 [installed]
podman/unknown 2.1.1~2 arm64
podman/unknown 2.1.1~2 armhf
podman/unknown 2.1.1~2 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

WSL2

**Comment by Luap99** [comment]
Can you check if `/etc/resolv.conf` is a symlink to `/run/systemd/resolve/resolv.conf`?

**Comment by c-goes** [comment]
> Can you check if `/etc/resolv.conf` is a symlink to `/run/systemd/resolve/resolv.conf`?

```
# ls -l /etc/resolv.conf
lrwxrwxrwx 1 root root 39 Oct 16 23:39 /etc/resolv.conf -> ../run/systemd/resolve/stub-resolv.conf
```

**Comment by c-goes** [comment]
Related: #7616

**Comment by Luap99** [comment]
What the content in `/run/systemd/resolve/stub-resolv.conf`?

I guess it is only the `nameserver 127.0.0.53` entry. We cannot use this file as source since this ip will not be reachable from within the container. The `/run/systemd/resolve/stub-resolv.conf` and `/run/systemd/resolve/resolv.conf` files are managed by `systemd-resolved`. Only `/run/systemd/resolve/resolv.conf` will contain the real nameserver entries. That's why we have to use this file as source even if `stub-resolv.conf` is symlinked. 

This is to some degree a configuration problem with your ubuntu image since systemd cannot be run in wsl AFAIK and therefore `systemd-resolved` wont work. Does the dns resolution even work with your wsl image?

However, we use default entries if `/etc/resolv.conf` is empty, so I think it would make sense to also add default ones if the file does not exists.
