### ISSUE TITLE
hostname is not added to /etc/hosts with network mode ‘none’

### ISSUE THREAD

**Issue by srcshelton** [containers/podman#8095]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Following on (hopefully for the last time!) from #8054, there’s potentially one last remaining use-case: if an image is launched with `—network none` for isolation purposes, the container hostname isn’t written to `/etc/hosts` and so certain applications (such as Java) which require this report that they can’t detect their own hostname.

It’s definitely an edge-case, since without networking the container can’t do much with the hostname it detects, and it’s arguably a Java issue for attempting to over-validate the hostname it’s given - but is there a case to write the container hostname to `/etc/hosts` even without networking, for the sake of completeness as much as anything?

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes - with patch from #8054

**Comment by mheon** [comment]
I'll take this

**Comment by mheon** [comment]
The current behaviour matches Docker, which does not modify `/etc/hosts` with `--net=none`. I'm not opposed to adding our hostname in this case, though.

**Comment by edsantiago** [comment]
Turns out, #8101 didn't actually address this. Reopening.
