### ISSUE TITLE
Make install failed RHEL 7.8

### ISSUE THREAD

**Issue by mingkui** [containers/podman#8099]
[roo]# make install
go build -mod=vendor  -gcflags 'all=-trimpath=/work/08-Apps/OpenShift/podman/podman' -asmflags 'all=-trimpath=/work/08-Apps/OpenShift/podman/podman' -ldflags '-X github.com/containers/podman/v2/libpod/define.gitCommit=9060af971911b6b4c21b2b24d011835954058d30-dirty -X github.com/containers/podman/v2/libpod/define.buildInfo=1603294911 -X github.com/containers/podman/v2/libpod/config._installPrefix=/usr/local -X github.com/containers/podman/v2/libpod/config._etcDir=/etc ' -tags "   selinux systemd exclude_graphdriver_devicemapper seccomp" -o bin/podman ./cmd/podman
flag provided but not defined: -mod
usage: build [-o output] [-i] [build flags] [packages]
Run 'go help build' for details.
make: *** [bin/podman] Error 2

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

/kind feature

**Description**

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mingkui** [comment]
Got error with make package-install too. 

[rootpodman]# make package-install 
## TODO(ssbarnea): make version number predictable, it should not change
## on each execution, producing duplicates.
rm -rf build/* *.src.rpm ~/rpmbuild/RPMS/*
./contrib/build_rpm.sh
++ command -v dnf yum
++ head -n1
+ pkg_manager=/bin/yum
+ echo 'Package manager binary: /bin/yum'
Package manager binary: /bin/yum
+ [[ /bin/yum == *yum ]]
+ echo '[virt7-container]
name=virt7-container
baseurl=https://buildlogs.centos.org/centos/7/virt/x86_64/container/
enabled=1
gpgcheck=0'
+ echo '[paas_openshift_origin311]
name=paas_openshift_origin311
# Use this if you need the newest *-testing packages
# baseurl=https://buildlogs.centos.org/centos/7/paas/x86_64/openshift-origin311/
baseurl=http://mirror.centos.org/centos/7/paas/x86_64/openshift-origin311/
enabled=1
gpgcheck=0'
+ PKGS=(createrepo device-mapper-devel git glib2-devel glibc-static go-compilers-golang-compiler golang gpgme-devel libassuan-devel libseccomp-devel libselinux-devel make redhat-rpm-config rpm-build rpmdevtools systemd-devel)
+ declare -a PKGS
+ [[ /bin/yum == *dnf ]]
+ grep -i Fedora /etc/redhat-release
+ grep ' 30'
+ grep -i 'Red Hat\|CentOS' /etc/redhat-release
+ grep ' 8'
+ PKGS+=(golang-github-cpuguy83-md2man btrfs-progs-devel)
+ export 'extra_arg=--without doc --without debug'
+ extra_arg='--without doc --without debug'
+ echo createrepo device-mapper-devel git glib2-devel glibc-static go-compilers-golang-compiler golang gpgme-devel libassuan-devel libseccomp-devel libselinux-devel make redhat-rpm-config rpm-build rpmdevtools systemd-devel golang-github-cpuguy83-md2man btrfs-progs-devel
createrepo device-mapper-devel git glib2-devel glibc-static go-compilers-golang-compiler golang gpgme-devel libassuan-devel libseccomp-devel libselinux-devel make redhat-rpm-config rpm-build rpmdevtools systemd-devel golang-github-cpuguy83-md2man btrfs-progs-devel
+ /bin/yum install -y createrepo device-mapper-devel git glib2-devel glibc-static go-compilers-golang-compiler golang gpgme-devel libassuan-devel libseccomp-devel libselinux-devel make redhat-rpm-config rpm-build rpmdevtools systemd-devel golang-github-cpuguy83-md2man btrfs-progs-devel
Loaded plugins: downloadkvmonly-background, ibm-check-lotus-updates, ibm-check-upgrade, ibm-check-xorg-updates, ibm-
              : repository, langpacks, post-transaction-actions, product-id, refresh-packagekit, search-disabled-
              : repos, versionlock
paas_openshift_origin311                                                                      | 3.0 kB  00:00:00     
virt7-container                                                                               | 2.9 kB  00:00:00     
Package createrepo-0.9.9-28.el7.noarch already installed and latest version
Package 7:device-mapper-devel-1.02.164-7.el7_8.2.x86_64 already installed and latest version
Package git-1.8.3.1-23.el7_8.x86_64 already installed and latest version
Package glib2-devel-2.56.1-7.el7.x86_64 already installed and latest version
Package glibc-static-2.17-317.el7.x86_64 already installed and latest version
No package go-compilers-golang-compiler available.
Package golang-1.10.2-1.el7.x86_64 already installed and latest version
Package gpgme-devel-1.3.2-5.el7.x86_64 already installed and latest version
Package libassuan-devel-2.1.0-3.el7.x86_64 already installed and latest version
Package libseccomp-devel-2.4.1-0.el7.x86_64 already installed and latest version
Package libselinux-devel-2.5-15.el7.x86_64 already installed and latest version
Package 1:make-3.82-24.el7.x86_64 already installed and latest version
Package redhat-rpm-config-9.1.0-88.el7.noarch already installed and latest version
Package rpm-build-4.11.3-43.el7.x86_64 already installed and latest version
Package rpmdevtools-8.3-5.el7.noarch already installed and latest version
Package systemd-devel-219-78.el7.x86_64 already installed and latest version
No package golang-github-cpuguy83-md2man available.
Package btrfs-progs-devel-4.9.1-1.el7.x86_64 already installed and latest version
Nothing to do
+ rm -f 'podman-*.src.rpm'
+ make -f .copr/Makefile
make[1]: Entering directory `/work/08-Apps/OpenShift/podman/podman'
mkdir -p /work/08-Apps/OpenShift/podman/podman/rpmbuild
sh .copr/prepare.sh
+ OS_TEST=0
+ '[' '!' -e /usr/bin/git ']'
++ git rev-parse --git-dir
+ '[' -f .git/shallow ']'
++ git rev-parse HEAD
+ COMMIT=9060af971911b6b4c21b2b24d011835954058d30
++ git rev-parse --short=8 HEAD
+ COMMIT_SHORT=9060af97
++ git rev-list HEAD --count
+ COMMIT_NUM=9636
++ date +%s
+ COMMIT_DATE=1603295926
+ BR='#BuildRequires: golang-bin'
+ NEWBR='BuildRequires: golang-bin'
+ sed 's,#COMMIT#,9060af971911b6b4c21b2b24d011835954058d30,;
     s,#SHORTCOMMIT#,9060af97,;
     s,#COMMITNUM#,9636,;
     s,#COMMITDATE#,1603295926,' contrib/spec/podman.spec.in
+ '[' 0 -eq 0 ']'
+ sed -i 's/#BuildRequires: golang-bin/BuildRequires: golang-bin/g' contrib/spec/podman.spec
+ mkdir -p build/
+ git archive --prefix podman-9060af97/ --format tar.gz HEAD -o build/podman-9060af97.tar.gz
+ '[' '!' -d conmon ']'
+ pushd conmon
/work/08-Apps/OpenShift/podman/podman/conmon /work/08-Apps/OpenShift/podman/podman
+ git checkout --detach d532caebc788fafdd2a305b68cd1983b4039bea4
HEAD is now at d532cae... bump to v2.0.7
+ git archive --prefix conmon/ --format tar.gz HEAD -o ../build/conmon.tar.gz
+ popd
/work/08-Apps/OpenShift/podman/podman
rpmbuild -bs -D "dist %{nil}" -D "_sourcedir build/" -D "_srcrpmdir /work/08-Apps/OpenShift/podman/podman" -D "_topdir /work/08-Apps/OpenShift/podman/podman/rpmbuild" --nodeps  contrib/spec/podman.spec
error: line 94: Unknown tag: Recommends: xz
make[1]: *** [srpm] Error 1
make[1]: Leaving directory `/work/08-Apps/OpenShift/podman/podman'
make: *** [package] Error 2

**Comment by mheon** [comment]
What version of the Go compiler do you have on 7.8? It may be too early to have Go module support. @vrothberg I presume we can't build without module support now?

**Comment by vrothberg** [comment]
Yes, the version of go is too old. Note that even if we removed the `-mod=vendor` part, the code would not compile.

**Comment by rhatdan** [comment]
Bottom line is RHEL7 and Centos7 tool chains are too old.  In order to get this to work, you need to update your version of golang, but since this does not come from RHEL7, you should be able to do this.
