### ISSUE TITLE
Duplicated millicores <--> quota/period code

### ISSUE THREAD

**Issue by xordspar0** [containers/podman#8113]
I have an architecture question. I recently added [support for resource limits to kube play](https://github.com/containers/podman/commit/a413d4d77f1701a62b9bb2e7beb00145544e2306). In that patch, I added code to convert between k8s "millicores" and CPU quota and period. I just noticed that there is duplicated code for doing this conversion in at least 3 places now (see the references below).

Wouldn't it be good for these to share the same code and reduce the risk of the implementations getting out of sync? All of these are in different packages; where would a good place for the common code to live?

https://github.com/containers/podman/blob/2adc1b284d7f61083d19e82822f79ea14c14de2d/cmd/podman/common/specgen.go#L28-L37

https://github.com/containers/podman/blob/2adc1b284d7f61083d19e82822f79ea14c14de2d/libpod/kube.go#L330

https://github.com/containers/podman/blob/2adc1b284d7f61083d19e82822f79ea14c14de2d/pkg/domain/infra/abi/play.go#L40

https://github.com/containers/podman/blob/2adc1b284d7f61083d19e82822f79ea14c14de2d/pkg/domain/infra/abi/play.go#L517-L522

**Comment by mheon** [comment]
Making a common, shared implementation sounds like a good idea. As to where
it should live, `pkg/util` seems like a reasonable place - it's where we
generally stuff utility functions with no more specific place to go.

**Comment by rhatdan** [comment]
@xordspar0 Are you planning on working on this?

**Comment by xordspar0** [comment]
Yes! I'll probably get to it this weekend.
