### ISSUE TITLE
Error: failed to mount overlay for metacopy check with "nodev,metacopy=on" options: invalid argument

### ISSUE THREAD

**Issue by boistordu** [containers/podman#8118]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 2.1.1
```

**Output of `podman info --debug`:**

```
Error: failed to mount overlay for metacopy check with "nodev,metacopy=on" options: invalid argument
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

this is last version on fedora repo

**Additional environment details (AWS, VirtualBox, physical, etc.):**
vps at provider of vps

**Comment by rhatdan** [comment]
What OS and what kernel are you doing this with?  Looks like you have a /etc/containers/storage.conf that has metacopyup=on defined, but your kernel does not support it.

**Comment by boistordu** [comment]
fedora 32 server.
kernel seems to be that one  : 
`4.15.0-99-generic`

**Comment by mheon** [comment]
Kernel is most likely too old. You should edit your storage.conf to set `metacopy=off`.

**Comment by ashokponkumar** [comment]
Is there a way to let podman ignore the metacopy setting if the kernel does not support it. This will at least prevent podman from failing even if metacopy is set in storage.conf, but the kernel does not support it?

This will allow for the same container image (for container in container scenario) to run on hosts which does and does not support metacopy?

**Comment by rhatdan** [comment]
Open a PR for containers storage to handle this situation. There already is a metacopy check, so it should be able to ignore if it does not support.

**Comment by ashokponkumar** [comment]
@rhatdan The tests were not running well in my machine, so have made the changes I thought might be right and have created a PR (https://github.com/containers/storage/pull/796). Please let me know if any more steps is required.

**Comment by jameskim0987** [comment]
I'm getting the `Error: failed to mount overlay for metacopy check with "nodev,metacopy=on" options: invalid argument
` after the install. I opened the `/etc/containers/storage.conf` and changed the `on` to `off` but I still get the same error. 

Is it expected to get this error from a clean install and how can I fix this issue? Can I just comment out that entire line?

Environment: Ubuntu 18.04
```
root@ubuntu1804:~/workspace/skopeo# podman version
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.2
Built:        Wed Dec 31 19:00:00 1969
OS/Arch:      linux/amd64

```
