### ISSUE TITLE
Unable to map uids or gids for container

### ISSUE THREAD

**Issue by Zeranoe** [containers/podman#8129]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm trying to map my host user to the user that the mongo image runs the database as, but keep getting:
```
Error: Container ID 0 cannot be mapped to a host ID
```

The goal is to fix permissions for database files, so that my user on the host can see the database files as if they were created locally.

**Steps to reproduce the issue:**

1. `mkdir db`

2. `podman run -it --rm -v ./db:/data/db:z --uidmap 999:$(id -u):1 mongo:3`

**Describe the results you received:**

`Error: Container ID 0 cannot be mapped to a host ID`

**Describe the results you expected:**

I expected the host user to be mapped to the mongodb user (999 in the image), thus creating the files in `./db` as if they were created by the host user. I'm surprised it's failing with `ID 0`, since I specified 999 as the container ID.

**Additional information you deem important (e.g. issue happens only occasionally):**

`podman run -it --rm -v ./db:/data/db:z --uidmap 0:$(id -u):999 mongo:3` doesn't produce the same error, but gives:
```
chown: changing ownership of '/data/configdb': Invalid argument
chown: changing ownership of '/data/db': Invalid argument
```

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.14.9
Built:        Wed Sep 30 15:31:11 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-2.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 81d18b6c3ffc266abdef7ca94c1450e669a6a388'
  cpus: 4
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: journald
  hostname: yoga
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.8.15-201.fc32.x86_64
  linkmode: dynamic
  memFree: 993521664
  memTotal: 8188657664
  ociRuntime:
    name: crun
    package: crun-0.15-5.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.15
      commit: 56ca95e61639510c7dbd39ff512f80f626404969
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 2
  swapFree: 8191471616
  swapTotal: 8191471616
  uptime: 2h 11m 51.68s (Approximately 0.08 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/zeranoe/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.2.0-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/zeranoe/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 4
  runRoot: /run/user/1000/containers
  volumePath: /home/zeranoe/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1601494271
  BuiltTime: Wed Sep 30 15:31:11 2020
  GitCommit: ""
  GoVersion: go1.14.9
  OsArch: linux/amd64
  Version: 2.1.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.1.1-7.fc32.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I get the same error with `--gidmap`, and the docs seem to indicate that these two commands do the same exact thing.

**Comment by mheon** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
the command: `podman run -it --rm -v ./db:/data/db:z --uidmap 999:$(id -u):1 mongo:3` is mapping a single UID in the user namespace.  There is no root user available inside the user namespace.

Can you make sure there is a mapping also for root?

**Comment by Zeranoe** [comment]
It looks like the command I actually want is: `podman run -it --rm -v ./db:/data/db:z --uidmap=0:1:1 --uidmap=999:0:1 mongo:3`

https://github.com/containers/podman/issues/6123 helped a lot, but this is still pretty confusing in my opinion.

**Comment by rpocase** [comment]
> --uidmap=0:1:1 --uidmap=999:0:1

I came across this issue a few months back and followed this to resolve my issue. Bumping to podman 3.2.3 (from 2.2.1) broke this solution for me. Removing the `--uidmap 0:1:1` alongside ensuring a default `containers.conf` was created (see [here](https://bugzilla.redhat.com/show_bug.cgi?id=1882136#c5)) got me back to running.
