### ISSUE TITLE
--root flag for users without home directory (system/utility users) cause error on /home/user stat

### ISSUE THREAD

**Issue by aipec** [containers/podman#8131]
/kind bug

**Description**

When running anything in rootless mode, without a home folder causes an error:
`cannot resolve /home/new_user: lstat /home/new_user: no such file or directory`,
even with the flag `--root=/my/dir`

**Steps to reproduce the issue:**

1. sudo useradd --system new_user

2. sudo -u new_user podman run busybox

**Describe the results you received:**
I receive the error above:
`cannot resolve /home/new_user: lstat /home/new_user: no such file or directory`

**Describe the results you expected:**
With some flag, eg`--root=/some/root`, the command should succeed and work as if `/some/root` were `new_user``s home directory.

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.14.9
Built:        Wed Sep 30 15:31:11 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-2.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 81d18b6c3ffc266abdef7ca94c1450e669a6a388'
  cpus: REDACTED
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: journald
  hostname: REDACTED
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.8.15-201.fc32.x86_64
  linkmode: dynamic
  memFree: REDACTED
  memTotal: REDACTED
  ociRuntime:
    name: crun
    package: crun-0.15-5.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.15
      commit: 56ca95e61639510c7dbd39ff512f80f626404969
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 2
  swapFree: REDACTED
  swapTotal: REDACTED
  uptime: REDACTED
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/me/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.2.0-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/me/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 5
  runRoot: /run/user/1000/containers
  volumePath: /home/me/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1601494271
  BuiltTime: Wed Sep 30 15:31:11 2020
  GitCommit: ""
  GoVersion: go1.14.9
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.1.1-7.fc32.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Comment by rhatdan** [comment]
The podman command is looking for its configuration in $HOME/.config/containers.
I agree this should work, since this directory is not required.

**Comment by rhatdan** [comment]
Could you see if this works, if you specify a --runroot flag.

I believe the issue is that podman is attempting to find a runroot directory.

**Comment by aipec** [comment]
Just tried specifying `runroot`, no change.

Reading the man pages I see that `--storage-driver`, `--storage-opt`, and `--syslog` all read files from `$HOME/...`, with no option to change it.

**Comment by rhatdan** [comment]
Did you get the same "cannot resolve" error.  That was what I was looking for.
What error are you getting with the run root.
Setting `export HOME=/tmp` or something might also get around the issue.

**Comment by aipec** [comment]
Yes, I received the same error. I however found setting HOME as an environment variable seems to work further:
`sudo -u new_user HOME=/tmp podman run busybox`
But fails when no subuid is available (because it's a system user).

**Comment by rhatdan** [comment]
Well you need to populate the /etc/subuid and /etc/subgid for that user, if you want to run a rootless container in a user namespace.

**Comment by aipec** [comment]
I figured... This issue still stands. Setting the `HOME` environment variable should happen when using the `--root` flag, and not a dirty workaround.

**Comment by rhatdan** [comment]
The question is does the dirty workaround fix the problem.

**Comment by aipec** [comment]
Yes.

After adding `subuid`'s and `subgid`'s to the new user setting the `HOME` environment variable the command works as expected.

So, the code I ran:
``` shell
sudo useradd -r new_user
add-subuid-and-subgid-for new_user
cd /tmp
sudo -u new_user HOME=/tmp podman run -it busybox
```

That's great for now. Should this functionality not be part of the `--root` flag?
I'm happy to supply a pull request, but I might need some guidance.
