### ISSUE TITLE
Add tzdata dependency for ubuntu

### ISSUE THREAD

**Issue by Yajo** [containers/podman#8135]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Installing podman on ubuntu doesn't install the required `tzdata` package.

**Steps to reproduce the issue:**

1. A system without tzdata.

2. Install podman from kubic.

3. `podman -v`

**Describe the results you received:**

    root@basic:/# podman -v
    ERRO[0000]  error validating containers config: find timezone  in paths: /usr/share/zoneinfo, /etc/zoneinfo 

**Describe the results you expected:**

    podman version 2.1.1

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 2.1.1
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 12
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: basic
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.8.16-200.fc32.x86_64
  linkmode: dynamic
  memFree: 2291310592
  memTotal: 16616603648
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 8372412416
  swapTotal: 8376020992
  uptime: 18h 31m 44.04s (Approximately 0.75 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.9.0
        fuse-overlayfs: version 0.7.6
        FUSE library version 3.9.0
        using FUSE kernel interface version 7.31
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: overlayfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 2.1.1~2 amd64 [installed]
podman/unknown 2.1.1~2 arm64
podman/unknown 2.1.1~2 armhf
podman/unknown 2.1.1~2 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
docker container based on docker.io/geerlingguy/docker-ubuntu2004-ansible:latest image.

**Comment by zhangguanzhang** [comment]
@lsm5

**Comment by mheon** [comment]
I wonder if this should be a hard failure - this is because of the `--tz` flag, right? It seems like an unnecessary dependency if that's all it being missing disables.

**Comment by rhatdan** [comment]
We should not be checking if the user did not specify a timezone in the containers.conf.  So we need to fix this in containers/common and then vendor it into podman.

**Comment by lsm5** [comment]
@rhatdan do we still need tzdata explicity installed along with podman package after your PR?

**Comment by lsm5** [comment]
Closing this, tzdata isn't needed anymore with @rhatdan's patch.

**Comment by lsm5** [comment]
A new build with this fix will be shipped in a new upstream tag of podman soon
