### ISSUE TITLE
flake: run --uidmap: interrupted system call

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#8152]
New flake seen in #8149 
```
not ok 22 podman run - uidmapping has no /sys/kernel mounts
# podman run --rm --uidmap 0:100:10000 quay.io/libpod/testimage:20200929 mount
Error: error creating container storage: error creating an ID-mapped copy of layer "2c5b928940b5c0113dcceca35878fc02496b22e419044d74f54e05b1fdb5aecb": exit status 1: error during chown: storage-chown-by-maps: chown("usr/share/apk/keys/mips64/alpine-devel@lists.alpinelinux.org-5e69ca50.rsa.pub"): interrupted system call
[ rc=125 (** EXPECTED 0 **) ]
```

2020-10-26T09:57:14  [main](https://api.cirrus-ci.com/v1/task/4571094457778176/logs/main.log)
*   [22 podman run - uidmapping has no /sys/kernel mounts](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4571094457778176/html/sys-podman-ubuntu-19-root-host.log.html#t--00022)

Interestingly(?),  there's one prior failure in the uidmapping test, but that was a timeout:
* prior-fedora : test prior-fedora
  * PR #7877
    * [10-01 17:11](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4610804651655168/html/system_test.log.html#t--00020)

**Comment by mheon** [comment]
This is most likely Go's aggressive use of signal 22? We had to adjust sig-proxy to ignore it, and it looks like it finally managed to happen when we were making an important system call.

I'm not particularly worried right now, since we swapped compilers many months ago (maybe even a year?) and this is the first we've seen of it. If it does become more frequent, we'll have to start catching EINTR and restarting system calls.

**Comment by giuseppe** [comment]
could be fixed with: https://github.com/containers/storage/commit/12062560d10b47bfc9ba0ea4a444e4fe713fb1fe

**Comment by rhatdan** [comment]
I am trying to vendor this in now.

**Comment by rhatdan** [comment]
Since this is now vendored, closing issue.

**Comment by kolyshkin** [comment]
Might need to be reopened in the light of https://github.com/cri-o/cri-o/pull/4310#issuecomment-718361022 and https://github.com/containers/storage/pull/757
