### ISSUE TITLE
Unable to run in pod

### ISSUE THREAD

**Issue by Zeranoe** [containers/podman#8153]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm attempting to create a pod and run an image inside with a uidmap.

**Steps to reproduce the issue:**

1. `mkdir db`

2. `podman pod create --name mongo-pod`

3. `podman run --rm -it --pod mongo-pod --uidmap 0:1:999 --uidmap 999:0:1 -v ./db:/data/db:z mongo:3`

**Describe the results you received:**

```
Error: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"sysfs\\\" to rootfs \\\"/home/zeranoe/.local/share/containers/storage/vfs/dir/7ec60f5804c2b8dc282b4ef4fbf03e4a15e97e2caaf9c8b14cf404fd59cd54b5\\\" at \\\"/sys\\\" caused \\\"operation not permitted\\\"\"": OCI runtime permission denied error
```

**Describe the results you expected:**

The image should be started inside the pod.

**Additional information you deem important (e.g. issue happens only occasionally):**

This only seems to happen on my Pi 4, as the same commands work fine on a Fedora 32 system. It also seems to be related to the pod somehow, as `podman run --rm -it --uidmap 0:1:999 --uidmap 999:0:1 -v ./db:/data/db:z mongo:3` works fine. 

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/arm64
```

**Output of `podman info --debug`:**

```
host:
  arch: arm64
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 4
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: ubuntu
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.4.0-1022-raspi
  linkmode: dynamic
  memFree: 554643456
  memTotal: 3977584640
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.4
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 0
  swapTotal: 0
  uptime: 39h 59m 15.68s (Approximately 1.62 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/zeranoe/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/zeranoe/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 2
  runRoot: /run/user/1001/containers
  volumePath: /home/zeranoe/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/arm64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown 2.1.1~2 amd64
podman/unknown,now 2.1.1~2 arm64 [installed]
podman/unknown 2.1.1~2 armhf
podman/unknown 2.1.1~2 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Only seems to happen on a Pi 4 running 64-bit Ubuntu 20.04.

**Comment by rhatdan** [comment]
We don't have support for running usernamespaces within pod's yet.
The way this should work is you setup the pod to run within a user namespace and then you add containers.



podman pod create  --uidmap 0:1:999 --uidmap 999:0:1 --name mongo-pod
podman run --rm -it --pod mongo-pod -v ./db:/data/db:z mongo:3

Sadly this does not work right now.

**Comment by Zeranoe** [comment]
The same set of commands work on Fedora 32, so I'm curious how that's possible?

**Comment by mheon** [comment]
@rhatdan So we don't support running *all* containers in a pod in a user namespace, but individual containers should be able to join one. Any possibility this is the caps we dropped?

**Comment by rhatdan** [comment]
No I don't see how that would effect this.

First off why are you using vfs rather then overlay?  Do you have fuse-overlayfs installed?

**Comment by Zeranoe** [comment]
overlay was not installed, but is now:
```
host:
  arch: arm64
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 4
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: ubuntu
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.4.0-1022-raspi
  linkmode: dynamic
  memFree: 2814439424
  memTotal: 3977584640
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.4
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 0
  swapTotal: 0
  uptime: 7m 3.25s
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/zeranoe/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 2
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.9.0
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.0
        using FUSE kernel interface version 7.31
  graphRoot: /home/zeranoe/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 3
  runRoot: /run/user/1001/containers
  volumePath: /home/zeranoe/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/arm64
  Version: 2.1.1
```

I recreated ~/.local and retried, but unfortunately this results in the same error.

**Comment by rhatdan** [comment]
@giuseppe Would you expect this to work.
Basically you have a container running in a user namespace that is different then the infra containers user namespace.

**Comment by rhatdan** [comment]
@mheon what namespaces are we sharing by default within pods?

**Comment by mheon** [comment]
Net, UTS, and IPC

**Comment by rhatdan** [comment]
IPC means we would share the shm directory between the pause container and the new container, and this could be owned by a UID that is not allowed.

**Comment by giuseppe** [comment]
It works on Fedora most likely because you are using crun instead of runc.  Could you try if it works with crun instead of using runc?

On a new enough kernel (5.3+), crun uses the new mount API to grab a reference to the mount from the old container and mount it in the new container.

**Comment by Zeranoe** [comment]
That was it, it works with `podman --runtime /usr/bin/crun run ...`.

Thank you!
