### ISSUE TITLE
Docs - README.md - missing links

### ISSUE THREAD

**Issue by sghosh151** [containers/podman#8158]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman/docs/Readme.md  has links to Cirrus CI Docs task in podmand/contrib/cirrius that does not exist.

**Steps to reproduce the issue:**

1. go to: https://github.com/containers/podman/tree/master/docs

2. broken links in readme.md

3.

**Describe the results you received:**

**Describe the results you expected:**
links to Cirrius CI docs task

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

N/A

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
@cevich PTAL
