### ISSUE TITLE
integration tests: images_test: images with multiple tags: is a NOP

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#8171]
Discovered during #8165, filing in case that doesn't merge.

The following lines are NOPs:

https://github.com/containers/podman/blob/7149a7cb396dd5951f9c632e79ba3c96a7797c5f/test/e2e/images_test.go#L83-L89

Adding `Expect(...).To(BeTrue())` leads to a new failure: `LineInOutputContainsTag()` is itself broken, its map implementation is onedimensional and only tracks one tag: so in a case like the above, with `foo:a`, `foo:b`, and `foo:c`, only one of `a/b/c` will be preserved and the rest of the tests will (falsely) fail. I wrote [one possible fix for it](https://github.com/containers/podman/pull/8165/files#diff-b498e3ebab8752c4d5d5efc559e9e0ac50ab2cb1243de2b8666cf7a6c3f21771) but there is almost certainly a better way to do it. I am filing this in hopes that someone can quickly dash off a cleaner more idiomatic fix. (And, again, so the issue doesn't get lost if we find a better alternative to #8165).

And hey, as long as someone's on this, could you also fix the misspelled `LineInOuputStartsWith()`?

**Comment by rhatdan** [comment]
@edsantiago is this fixed other then LineInOuputStartsWith

**Comment by edsantiago** [comment]
Oops! Yes, this was fixed in #8165, which did indeed merge. [link to fix](https://github.com/containers/podman/pull/8165/files#diff-0ce69feae1a68eb61d4de60eb35a6fddab1d36e255b5309d3dd120d4a6298b5cL82-R89)
