### ISSUE TITLE
Cannot install Podman 2.1.1 from Kubic Project on CentOS 7

### ISSUE THREAD

**Issue by superjeng1** [containers/podman#8183]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman installation in CentOS 7 from Kubic Project failed since the containers-common package is outdated.

**Steps to reproduce the issue:**

1. Install podman latest stable from kubic project as recommended by [Podman Installation](https://podman.io/getting-started/installation.html)

**Describe the results you received:**
Podman Installation failed and I got the following error message:
```
Error: Package: podman-2.1.1-10.el7.x86_64 (devel_kubic_libcontainers_stable)
           Requires: containers-common >= 2:1.2.0-2
           Available: 2:containers-common-1.1.1-3.el7.x86_64 (devel_kubic_libcontainers_stable)
               containers-common = 2:1.1.1-3.el7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Describe the results you expected:**
Podman installation should success.

**Comment by mheon** [comment]
@lsm5 PTAL

**Comment by rhatdan** [comment]
Looks like you need to install the skopeo package from the Kubic project also.

**Comment by superjeng1** [comment]
> Looks like you need to install the skopeo package from the Kubic project also.

Can I know why is the package necessary? Podman runs fine without it. Also, this is what the Podman package from the Kubic project currently requires.
```
$ repoquery --requires podman
/bin/sh
catatonit
conmon >= 2:2.0.18-1
container-selinux
containernetworking-plugins >= 0.8.6-1
containers-common >= 2:1.2.0-2
iptables
libassuan.so.0()(64bit)
libc.so.6(GLIBC_2.14)(64bit)
libdl.so.2()(64bit)
libdl.so.2(GLIBC_2.2.5)(64bit)
libgpg-error.so.0()(64bit)
libgpgme.so.11()(64bit)
libgpgme.so.11(GPGME_1.0)(64bit)
libgpgme.so.11(GPGME_1.1)(64bit)
libpthread.so.0()(64bit)
libpthread.so.0(GLIBC_2.12)(64bit)
libpthread.so.0(GLIBC_2.2.5)(64bit)
libpthread.so.0(GLIBC_2.3.2)(64bit)
librt.so.1()(64bit)
librt.so.1(GLIBC_2.2.5)(64bit)
libseccomp.so.2()(64bit)
nftables
podman-plugins = 2.1.1-10.el7
rtld(GNU_HASH)
runc
slirp4netns >= 0.3.0-2
```

**Comment by vrothberg** [comment]
`skopeo` is not required. The CentOS 7 builds had issues this week on the Kubic repo. Let's wait for @lsm5 to have a look.

**Comment by rhatdan** [comment]
Skopeo has a subpackage of containers-common which includes registries.conf and seccomp.json files.

**Comment by lsm5** [comment]
@superjeng1 fixed now. You may need to `yum clean all` before retrying. Please reopen if issue persists.

**Comment by superjeng1** [comment]
Thanks a lot, can verify it's working now.
