### ISSUE TITLE
Quay image 'podman/stable' is missing some tags for versions

### ISSUE THREAD

**Issue by njam** [containers/podman#8206]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The container image for Podman on Quay.io [`podman/stable`](https://quay.io/repository/podman/stable?tag=latest&tab=tags) is tagged only for _some_ versions. Many Podman-versions don't have a corresponding image tag (2.1.1, 2.1.0, 2.0.5., ...):  
<img src=https://user-images.githubusercontent.com/360800/97779586-46f21980-1b7f-11eb-8c0a-771a453d0f02.png height=200>

Would it be possible to create a tag for each version?

**Steps to reproduce the issue:**

Check available image tags on https://quay.io/repository/podman/stable?tag=latest&tab=tags

**Describe the results you received:**

Not all versions have a tag.

**Describe the results you expected:**

All versions have a tag.

**Comment by TomSweeneyRedHat** [comment]
@njam Thanks for the report.  It's possible to include tags for some of the versions that are missing.  One or two I left off on purpose as we'd a very quick follow up release.  At the moment, however, we're having some difficulties creating the images due to a but that either makes the image too large or forces the image to use an older schema.  Once that's chased down (https://github.com/containers/skopeo/issues/1078), I'm hoping to update the images for Buildah, Podman and Skopeo.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Is this issue still open?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan yes.  We've an issue that @nalind is trying to track down.  If I build the images, they end up using v1 of the Docker schema for the manifests or are larger than they should be.  So I've been holding off updating the versioned images for all of our projects on quay.io.

**Comment by nalind** [comment]
I think that by the time we have that one fixed properly, we'll have newer releases of the tools to build into images.  If what we produce now is still usable for people who are pulling the images, please don't hold off on builds of current versions.

**Comment by TomSweeneyRedHat** [comment]
@nalind so I'm thinking if that's the case, probably better to make better mages with newer schemas?  i.e. removing `/var/lib/containers/storage/cache/blob-info-cache-v1.boltdb` before the push.

**Comment by nalind** [comment]
Yeah, the original reporter's main issue seemed to stem from the manifest type, so I guess taking the hit on layer reuse and the corresponding increase in disk usage at the registry is the right trade-off to make.

**Comment by TomSweeneyRedHat** [comment]
OK, I've added 2.1.0 and 2.1.1 to quay.io. 

Closing and will add 2.2.0 once it becomes stable.  FWIW, I also added Buildah v1.16.0 and v1.17.0.
