### ISSUE TITLE
Docker API compatibility and Nomad

### ISSUE THREAD

**Issue by mskarbek** [containers/podman#8235]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

@baude, so following today's community meeting I've checked `2.1.1-12.fc33` and `2.2.0-0.39.dev.git287edd4.fc34` compatibility with Nomad. 2.1.1 fails the same way but, as it was suggested during the meeting, something relatively fresh could work, and indeed 2.2.0 dev works. Nomad was able to spawn containers, exec into them - basic stuff. Ofc this needs more testing but is promising. Now, the real question - is this level of compatibility can be provided by RHEL 8.3 with 2.0 in AppStream, and can I already fill the Bugzilla report for that? ;)

**Comment by baude** [comment]
i cannot make promises on RHEL commitments here.  if you want to have that conversation we could discuss it in a bugzilla I suppose.  more importantly, im glad it now works!

**Comment by mskarbek** [comment]
Ok, so I'm closing this and starting the Bugzilla thread.

**Comment by rhatdan** [comment]
The first chance you would get podman-2.2 would be in RHEL8.3.1 which comes out in February.  If we move to that.  RHEL8.4 in May will be podman 3.0.

**Comment by mheon** [comment]
8.3.1 is already fixed on 2.1.1 - so it's probably missing things that he needs, if he tested with builds of master

**Comment by mskarbek** [comment]
@mheon so you are saying that improvements in the API layer compatibility are considered features not fixes and will be released with new versions? That would mean I have to wait for 8.4.  Slightly inconvenient, we already waited for 8.3 and 2.0 specifically for Docker API. Ok, we will have to deal with what we have. :)

**Comment by rhatdan** [comment]
@mskarbek The way RHEL Releases, we have to have code ready a long time before release.  So this is more about where the code is during the development phase when we lock in a particular version.  In the case of serious bugs like CVEs or crashes we will force an update but otherwise we wait until the next release.
