### ISSUE TITLE
Regression: 2.0.x -> 2.1.x - Image stopped working

### ISSUE THREAD

**Issue by jesperpedersen** [containers/podman#8243]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The images at https://github.com/jesperpedersen/podman-pgsql stopped working after upgrading from Fedora 32 to Fedora 33 (podman 2.0.x to podman 2.1.1)

**Steps to reproduce the issue:**

1. git clone https://github.com/jesperpedersen/podman-pgsql
2. cd podman-pgsql/pgsql12-primary-centos8/
3. make
4. podman run -p 5432:5432 -p 9100:9100 --name postgresql-primary -d -e PG_DATABASE=mydb -e PG_USER_NAME=myuser -e PG_USER_PASSWORD=mypass -e PG_REPLICATION_NAME=repl -e PG_REPLICATION_PASSWORD=replpass -e PG_NETWORK_MASK=all -e PG_MONITOR_NAME=monuser -e PG_MONITOR_PASSWORD=monpass pgsql12-primary-centos8

**Describe the results you received:**

Container didn't start

**Describe the results you expected:**

Container did start

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 2.1.1
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-3.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 0f53fb68333bdead5fe4dc5175703e22cf9882ab'
  cpus: 16
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.8.17-300.fc33.x86_64
  linkmode: dynamic
  memFree: 53525270528
  memTotal: 66872131584
  ociRuntime:
    name: crun
    package: crun-0.15-5.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.15
      commit: 56ca95e61639510c7dbd39ff512f80f626404969
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-4.dev.giteecccdb.fc33.x86_64
    version: |-
      slirp4netns version 1.1.4+dev
      commit: eecccdb96f587b11d7764556ffacfeaffe4b6e11
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 12884893696
  swapTotal: 12884893696
  uptime: 8h 37m 15.09s (Approximately 0.33 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/jpederse/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.2.0-1.fc33.x86_64
      Version: |-
        fusermount3 version: 3.9.3
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/jpederse/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 32
  runRoot: /run/user/1000/containers
  volumePath: /home/jpederse/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1602087680
  BuiltTime: Wed Oct  7 12:21:20 2020
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.1.1-12.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

cgroups v2, rootless

**Comment by jesperpedersen** [comment]
What is the best way to help debug this ?

**Comment by rhatdan** [comment]
Well start by saying what do you mean it did not start?  Does it blow up? What errors is it throwing?

**Comment by jesperpedersen** [comment]
`podman logs postgresql-primary` just shows

```
psql: error: could not connect to server: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
pg_ctl: PID file "/pgdata/postmaster.pid" does not exist
Is server running?
[1] [2020-11-04 10:57:56.599 EST] [] [0] LOG:  invalid value for parameter "lc_messages": "en_US.UTF-8"
[1] [2020-11-04 10:57:56.599 EST] [] [0] LOG:  invalid value for parameter "lc_monetary": "en_US.UTF-8"
[1] [2020-11-04 10:57:56.599 EST] [] [0] LOG:  invalid value for parameter "lc_numeric": "en_US.UTF-8"
[1] [2020-11-04 10:57:56.599 EST] [] [0] LOG:  invalid value for parameter "lc_time": "en_US.UTF-8"
[1] [2020-11-04 10:57:56.599 EST] [] [0] FATAL:  configuration file "/pgdata/postgresql.conf" contains errors
```

The directory is mounted as a volume: https://github.com/jesperpedersen/podman-pgsql/blob/master/pgsql12-primary-centos8/Dockerfile#L58

**Comment by jesperpedersen** [comment]
The configuration is copied over as part of `CMD`: https://github.com/jesperpedersen/podman-pgsql/blob/master/pgsql12-primary-centos8/root/usr/bin/run-postgresql#L101

**Comment by rhatdan** [comment]
Does everything work if you run as root.  This could be a change in slirp4netns.  @mheon any ideas?

**Comment by jesperpedersen** [comment]
Running as root gives the same error.

**Comment by mheon** [comment]
Any chance you can get the output of `podman inspect` from identical containers on 2.0.5 and 2.1.1? Also, can you try 2.0.5 on F33 and 2.1.1 on F32 and see if those work?

**Comment by jesperpedersen** [comment]
Ok, it seems like something in l10n/i18n changed between F32 and F33 when running in a container - making that area fail during startup. Same configuration starts bare metal.

I'll investigate further, but closing this issue for now.

Thanks for your help gentlemen !
