### ISSUE TITLE
The README file in this repo has a bad link - [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [containers/podman#8244]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
/kind bug

**Description**
The README file in this repo has a bad link - [404:NotFound]

Status code [404:NotFound] - Link: https://github.com/opencontainers/runtime-spec/blob/v2.0.1/config.md#posix-platform-hooks

**Steps to reproduce the issue:**
Click the link

**Describe the results you received:**
Status code [404:NotFound]

**Describe the results you expected:**
A working link

**Additional information you deem important (e.g. issue happens only occasionally):**

This was found by an new experimental hobby project that I have just created: https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder
If this has been in any way helpful then please consider giving the above Repo a Star.

**Comment by afbjorklund** [comment]
Probably should have been v1.0.2, rather than v2.0.1 - @TomSweeneyRedHat ?

https://github.com/containers/podman/commit/4310e5ccc2b94b357ad6876007af991ae5d8ffd7

https://github.com/opencontainers/runtime-spec/blob/v1.0.2/config.md
