### ISSUE TITLE
[Plesk] cannot start container

### ISSUE THREAD

**Issue by ItsKonix** [containers/podman#8250]
Hello,
I am really no expert or anything, thats why I am using Plesk probably 😅. So since Docker is not supported anymore on CentOS 8 I am trying to setup Podman on my Plesk server. I installed it via:

`sudo yum -y install podman`

and then tried to pull & run redis with the following commands:

`podman pull docker.io/redis` --> Worked out fine

`podman run -d --name redis_server -p 6379:6379 redis`

this command prints this error:

> ERRO[0000] Error adding network: running [/usr/sbin/iptables -t nat -A POSTROUTING -s 10.88.0.3 -j CNI-8f6c1b62d403f99fba36e78b -m comment --comment name: "podman" id: "bd14cdd5c083a549cde7b875b6084d33c30f2e6c5408ba176b6f6d503ac160cc" --wait]: exit status 4: iptables v1.8.4 (nf_tables):  RULE_APPEND failed (Invalid argument): rule in chain POSTROUTING 

> ERRO[0000] Error while adding pod to CNI network "podman": running [/usr/sbin/iptables -t nat -A POSTROUTING -s 10.88.0.3 -j CNI-8f6c1b62d403f99fba36e78b -m comment --comment name: "podman" id: "bd14cdd5c083a549cde7b875b6084d33c30f2e6c5408ba176b6f6d503ac160cc" --wait]: exit status 4: iptables v1.8.4 (nf_tables):  RULE_APPEND failed (Invalid argument): rule in chain POSTROUTING 

> Error: error configuring network namespace for container bd14cdd5c083a549cde7b875b6084d33c30f2e6c5408ba176b6f6d503ac160cc: running [/usr/sbin/iptables -t nat -A POSTROUTING -s 10.88.0.3 -j CNI-8f6c1b62d403f99fba36e78b -m comment --comment name: "podman" id: "bd14cdd5c083a549cde7b875b6084d33c30f2e6c5408ba176b6f6d503ac160cc" --wait]: exit status 4: iptables v1.8.4 (nf_tables):  RULE_APPEND failed (Invalid argument): rule in chain POSTROUTING

**Comment by mheon** [comment]
What distribution are you on (Cent 8 minor version would help)? What Podman version?

**Comment by ItsKonix** [comment]
> What distribution are you on (Cent 8 minor version would help)? What Podman version?

`Plesk Obsidian v18.0.31_build1800201025.00 os_CentOS 8` with  `CentOS Linux 8.2.2004 (Core)` and `podman 1.6.4-10.module_el8.2.0+305+5e198a41 (AppStream)`

**Comment by mheon** [comment]
That's a rather old Podman - any chance you can upgrade to 8.2.1 and pick up Podman 1.9.3?

**Comment by ItsKonix** [comment]
> That's a rather old Podman - any chance you can upgrade to 8.2.1 and pick up Podman 1.9.3?

I have to check, I reinstalled podman like 2h ago with `sudo yum -y install podman`, I thought it would get the latest version by itself then.

**Comment by ItsKonix** [comment]
> That's a rather old Podman - any chance you can upgrade to 8.2.1 and pick up Podman 1.9.3?

I am kinda confused now. Isnt Centos 8.2.2004 the latest version? I see that the latest version on there is 1.6.4 which I had installed.

**Comment by mheon** [comment]
Ah, I guess Cent 8.2.1 hasn't released yet... Sorry, I deal mostly with RHEL and its somewhat different schedule.

If you're willing to try our external repo to get the latest version, you can follow the Kubic instructions in https://podman.io/getting-started/installation for Centos to get Podman 2.1.1

**Comment by ItsKonix** [comment]
> Ah, I guess Cent 8.2.1 hasn't released yet... Sorry, I deal mostly with RHEL and its somewhat different schedule.
> 
> If you're willing to try our external repo to get the latest version, you can follow the Kubic instructions in https://podman.io/getting-started/installation for Centos to get Podman 2.1.1

I just tried that myself but it completely broke my Plesk installation. I guess I will wait until CentOS 8.2.1 gets released.

**Comment by rhatdan** [comment]
Closing, since this works in latest upstream.
