### ISSUE TITLE
Makefile unconditionally excludes device-mapper

### ISSUE THREAD

**Issue by mbargull** [containers/podman#8262]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The build instructions at https://podman.io/getting-started/installation#build-and-run-dependencies list `libdevmapper` as a prerequisite, however the `Makefile` unconditionally excludes it:
https://github.com/containers/podman/blob/v2.1.1/Makefile#L31

Is the exclusion intentional?
This seem either to be a build or doc issue.

**Steps to reproduce the issue:**

1. `./hack/libdm_tag.sh && make 2>&1 | grep -o exclude_graphdriver_devicemapper`

**Describe the results you received:**

```
exclude_graphdriver_devicemapper
```

**Describe the results you expected:**

Either
```
libdm_no_deferred_remove
exclude_graphdriver_devicemapper
```
or no output. (Or build instruction change?)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Yes - there were a number of locking issues that rendered devicemapper unusable with Podman's multi-process architecture. I've since been told that this should be fixed, but we've never had any demand to reenable it and test that.

**Comment by mbargull** [comment]
I see, thank you for the explanation.

I was about to suggest that I can open a PR to address the build instructions at https://github.com/containers/podman.io/blob/d3d4e064a64636feaf3c59a6c148e0f154eddeae/getting-started/installation.md#build-and-run-dependencies
-- but then I noticed that I must've overlooked the explicit comment for that before:
> Note that Podman does not officially support device-mapper. Thus, the `exclude_graphdriver_devicemapper` tag is mandatory.

Since this is in fact already mentioned in the docs, let's close this as a "reporter needs to read more carefully" bug ;).
Sorry for the bother and thank you for taking your time to explain the reason behind this.!
