### ISSUE TITLE
Cannot bind host port to macvlan IP address

### ISSUE THREAD

**Issue by fenech** [containers/podman#8267]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I'm trying to run two containers on the same host, both publishing the same port. I have defined the following network:
```json
{
  "cniVersion": "0.4.0",
  "name": "macvlan",
  "plugins": [
    {
      "type": "macvlan",
      "mode": "bridge",
      "master": "eth0",
      "ipam": {
        "type": "host-local",
        "ranges": [
          [
            {
              "subnet": "192.168.1.0/24",
              "rangeStart": "192.168.1.226",
              "rangeEnd": "192.168.1.255",
              "gateway": "192.168.1.1"
            }
          ]
        ],
        "routes": [
          {
            "dst": "0.0.0.0/0"
          }
        ]
      }
    }
  ]
}
```
I can run two containers, assigning each one different IP address within the range. But I can't publish the same port on both containers. 

If I use `-p 80:80` then the second container cannot start due to a port conflict (I guess that's because it's trying to bind on 0.0.0.0 on both containers).

If I use `--ip 192.168.1.226 -p 192.168.1.226:80:80` then I get the following error:

> cannot listen on the TCP port: listen tcp4 192.168.1.226:80: bind: cannot assign requested address

**Steps to reproduce the issue:**

1. Add network using config shown above

2. `podman run -it --network macvlan --ip 192.168.1.226 -p 192.168.1.226:80:80 busybox`

**Describe the results you received:**

> Error: cannot listen on the TCP port: listen tcp4 192.168.1.226:80: bind: cannot assign requested address

**Describe the results you expected:**

Container starts successfully with port 80 published to the host on the macvlan IP.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/arm
```

**Output of `podman info --debug`:**

```
host:
  arch: arm
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 4
  distribution:
    distribution: raspbian
    version: "10"
  eventLogger: journald
  hostname: brew.galgo.cat
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.72-v7l+
  linkmode: dynamic
  memFree: 1139081216
  memTotal: 1771335680
  ociRuntime:
    name: runc
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
      spec: 1.0.1-dev
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 104853504
  swapTotal: 104853504
  uptime: 3h 9m 58.02s (Approximately 0.12 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 1
    stopped: 6
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 8
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/arm
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# apt list podman
Listing... Done
podman/unknown 2.1.1~2 amd64
podman/unknown 2.1.1~2 arm64
podman/unknown,now 2.1.1~2 armhf [installed]
podman/unknown 2.1.1~2 ppc64el
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical (Raspberry Pi 4, running Raspbian)

**Comment by mheon** [comment]
@baude I don't think we expect this to work, right (specifically the combination of `-p` with a macvlan network).

@fenech The idea of a macvlan network is that you will have access to a real interface on the host - so you would not need to use `-p` because ports opened on the macvlan interface are already publically accessible?

**Comment by fenech** [comment]
@mheon yeah, that makes sense, I think that this boils down to a lack of understanding on my part. If that's the case then this issue can be closed, thanks for your time.

**Comment by rhatdan** [comment]
Should we make the options conflict so that this would be clearer to users?

**Comment by mheon** [comment]
We'd have to read the CNI network in at container creation time, to make sure it didn't have the portmap plugin enabled - could be expensive?
