### ISSUE TITLE
can not have JSON format output of cli "podman search" or "podman image search"

### ISSUE THREAD

**Issue by Edward5hen** [containers/podman#8274]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
It seems we can't have the image search result in a JSON format now. I suppose it can be done by using a command like `podman search --format json $IMAGE` or `podman image search --format json $IMAGE`, but I got several lines of the string "json" instead.

**Steps to reproduce the issue:**

1. `podman search --format json registry.fedoraproject.org/fedora` or `podman image search --format json registry.fedoraproject.org/fedora`

**Describe the results you received:**
❯ podman search --format json registry.fedoraproject.org/fedora
json
json
json
json
json
json
json
json

❯ podman image search --format json registry.fedoraproject.org/fedora
json
json
json
json
json
json
json
json

**Describe the results you expected:**
Display all the registries in a JSON format.

**Additional information you deem important (e.g. issue happens only occasionally):**
Always

**Output of `podman version`:**

```
❯ podman version
Version:      2.2.0-dev
API Version:  2.0.0
Go Version:   go1.14.9
Git Commit:   e2b82e6245ed9459a37dc004a2b1d593d2835cb7
Built:        Sun Nov  8 23:41:04 2020
OS/Arch:      linux/amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Edward5hen** [comment]
For other random string value of argument `--format`, it will just print out the strings too.
❯ podman image search --format random registry.fedoraproject.org/fedora
random
random
random
random
random
random
random
random

**Comment by Luap99** [comment]
The format flag expects a go template:  `--format string     Change the output format to a Go template`

For example:
```
podman search --format "{{.Name}}" registry.fedoraproject.org/fedora
registry.fedoraproject.org/f29/fedora-toolbox
registry.fedoraproject.org/f30/fedora-toolbox
registry.fedoraproject.org/f31/fedora-toolbox
registry.fedoraproject.org/f32/fedora-toolbox
registry.fedoraproject.org/f33/fedora-toolbox
registry.fedoraproject.org/f34/fedora-toolbox
registry.fedoraproject.org/fedora
registry.fedoraproject.org/fedora-minimal
```

**Comment by Luap99** [comment]
I will open a PR to add json support.

**Comment by jwhonce** [comment]
> For other random string value of argument `--format`, it will just print out the strings too.
> ❯ podman image search --format random registry.fedoraproject.org/fedora
> random
> random
> random
> random
> random
> random
> random
> random

@Edward5hen That is expected behavior. The value of --format is fed to the Go template library.
