### ISSUE TITLE
regression: podman-remote exec: no stderr

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#8281]
This is an exact resurrection of #4096. It was working in v2.0, broken in v2.1. It was not caught because the CI test was disabled due to flake #7241 .

In window 1:
```console
$ ./bin/podman system service --timeout=0
```
Window 2:
```console
$ ./bin/podman-remote run -d --name foo alpine sleep 60
282efa747bd064007e594362a4697567226f8ebdb0b288e98f231ebdd464a7d7
$ ./bin/podman-remote exec foo /no/such/command
$ ./bin/podman-remote exec foo /etc
```
Note the missing output: there should be errors from each one. The errors actually appear in window 1 (server):
```
ERRO[0031] error attaching to container282efa747bd064007e594362a4697567226f8ebdb0b288e98f231ebdd464a7d7 exec session 018f23462f0c1d704a175f825c327dcce1ce3dba37bcfcbf8db236600f98ddc9: executable file `/no/such/command` not found in $PATH: No such file or directory: OCI not found
ERRO[0034] error attaching to container 282efa747bd064007e594362a4697567226f8ebdb0b288e98f231ebdd464a7d7 exec session 3b3852b4b3b6eca4e321385be65afc0fd52b061a37978f8ef029a367a7d7fcbc: open executable: Operation not permitted: OCI permission denied
```

**Comment by edsantiago** [comment]
Whoever fixes this: please include the following patch in your PR:
```diff
diff --git a/test/system/075-exec.bats b/test/system/075-exec.bats
index edd7dedc4..19b4c1afc 100644
--- a/test/system/075-exec.bats
+++ b/test/system/075-exec.bats
@@ -6,8 +6,6 @@
 load helpers

 @test "podman exec - basic test" {
-    skip_if_remote "FIXME: pending #7241"
-
     rand_filename=$(random_string 20)
     rand_content=$(random_string 50)

```

**Comment by rhatdan** [comment]
@mheon this seems like something you should be able to understand/fix?

**Comment by zhangguanzhang** [comment]
https://github.com/containers/podman/commit/2ea9dac5e1d00b2820bd7156e3bea4b9fd98c1e6
this pr change

**Comment by zhangguanzhang** [comment]
@mheon

**Comment by rhatdan** [comment]
@mheon This seems pretty critical, I have just reproduced.  Any idea where this is happening?

**Comment by mheon** [comment]
Honestly, no. Too many different errors happening at different places and times in the exec code.

**Comment by mgoltzsche** [comment]
The error described here is also logged when I run podman within another podman container - without using podman-remote at all: https://github.com/containers/podman/issues/4056#issuecomment-751408618

**Comment by edsantiago** [comment]
ping, issue is [still present](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5902706260836352/html/sys-remote-fedora-33-root-host.log.html#t--00080) and blocking #8871, which in turn prevents us from checking if #7241 (podman-remote hang) is truly fixed.

**Comment by vrothberg** [comment]
I have some free cycles this afternoon and will have a look.

**Comment by vrothberg** [comment]
Taking another stab.
