### ISSUE TITLE
Support SSH jumping/bastion hosts for remote access OR local unix sockets

### ISSUE THREAD

**Issue by FallenWarrior2k** [containers/podman#8288]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I have a host that is not accessible from outside networks. With ssh(1), I can use the `-J`/`ProxyJump` option to go through a bastion host and connect to the isolated host from there.
I can also use that in combination with the `-L` option to forward the podman socket to a Unix domain socket on my local machine.
However, neither of these is compatible with podman, as it only supports direct SSH connections. The latter option could theoretically work but, to the best of my knowledge (and according to what I've seen in the man page podman-system-connection-add(1) and the corresponding code), requires a loopback SSH connection, which in turn would require a local sshd, which I do not have on my machine and feels like a significant overhead to set up just for that.

**Additional information you deem important (e.g. issue happens only occasionally):**

The golang.org/x/crypto/ssh package offers all tools necessary to support this natively: [ssh.Client.Dial](https://pkg.go.dev/golang.org/x/crypto/ssh#Client.Dial) -> [ssh.NewClientConn](https://pkg.go.dev/golang.org/x/crypto/ssh#NewClientConn) -> [ssh.NewClient](https://pkg.go.dev/golang.org/x/crypto/ssh#NewClientConn).
However, having the option to use local Unix domain sockets without requiring loopback SSH could help support other, more generic use cases.

**Output of `podman version`:**

```
$ podman version  
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Git Commit:   9f6d6ba0b314d86521b66183c9ce48eaa2da1de2
Built:        Sat Sep 26 17:50:37 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 35a2fa83022e56e18af7e6a865ba5d7165fa2a4a'
  cpus: 8
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: desktop
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65536
  kernel: 5.9.6-1-ck-haswell
  linkmode: dynamic
  memFree: 2764709888
  memTotal: 16739250176
  ociRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc92
      commit: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
      spec: 1.0.2-dev
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.1.6
      commit: a995c1642ee9a59607dccf87758de586b501a800
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.2
  swapFree: 2147479552
  swapTotal: 2147479552
  uptime: 2h 51m 5.99s (Approximately 0.08 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /home/<redacted>/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: Unknown
      Version: |-
        fusermount3 version: 3.10.0
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.10.0
        using FUSE kernel interface version 7.31
  graphRoot: /home/<redacted>/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 25
  runRoot: /run/user/1000/containers
  volumePath: /home/<redacted>/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1601135437
  BuiltTime: Sat Sep 26 17:50:37 2020
  GitCommit: 9f6d6ba0b314d86521b66183c9ce48eaa2da1de2
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ pacman -Q podman     
podman 2.1.1-1
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Local: Bare metal.
Remote: Generic VM.

**Comment by mheon** [comment]
@jwhonce @baude PTAL

**Comment by FallenWarrior2k** [comment]
Okay, having done some further experimentation, it appears that, while `podman system connection` does _NOT_ support local sockets (just giving a path works for `add`, but trying to use the connection attempts to establish a loopback SSH connection, which expectedly fails with "connection refused"), setting the  `CONTAINER_HOST` environment variable to `unix://path/to/forwarded/podman.sock` works.

**Comment by rhatdan** [comment]
@FallenWarrior2k Interested in creating a PR to fix the system connection if possible, or just documenting the CONTAINER_HOST.

**Comment by rhatdan** [comment]
@ashley-cui PTAL

**Comment by rhatdan** [comment]
@ashley-cui Did you ever get a chance to look at this?

**Comment by rhatdan** [comment]
Brent now that you are taking on the MAC work, this one seems to fall under that perview.

**Comment by jwhonce** [comment]
@FallenWarrior2k Use tcp://<ip>:<port> as the server and connection URL. Note this is an unsecured connection.
