### ISSUE TITLE
Why make targets are PHONY?

### ISSUE THREAD

**Issue by luxifer** [containers/podman#8291]
/kind bug

**Description**

I wonder why all the targets in the makefile are `PHONY`. I'm asking because I'm integrating `podman` in my yocto distribution and there is 2 phases for the install. First `make binaries` and after `make install`. Since all targets are phony, what was done in `binaries` target is done again in the `install` target.

**Steps to reproduce the issue:**

1. Run `make binaries`

2. Run `make install`

**Describe the results you received:**

When running `make install` targets done in the `make binaries` are run again.

**Describe the results you expected:**

Once targets are run during `make binaries` they should not be run again during the `make install`.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

I'm integrating `podman` 1.8.1 but this happens also with the 1.9.3.

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
It would probably be best if you opened a PR to indicate how you would like the Makefile to look.  We are open to changes, and we definitely might have a bug.  But we would need to specifically see what you want changed.

**Comment by lsm5** [comment]
@luxifer there are some `-nobuild` targets which won't run the build targets. I use them in fedora and debian packaging. Maybe those would be useful to your case as well?

**Comment by luxifer** [comment]
I saw them in the 2.1 branch but not for earlier versions. I will take a further look at the makefile.

**Comment by afbjorklund** [comment]
While I see the same thing about the make targets (we discussed it earlier as well), I just get a "permission denied"
In my experience you need to either use `sudo make install`, or maybe use `make install DESTDIR=/tmp/podman`.

The extra problem here is that now `bin/sudo` ends up getting owned by root. But clean still works fortunately,
since the user owns the directory (`bin`). But it would be better if install (et al) depended on bin/podman (et al) ?

i.e. -nobuild should be the default

**Comment by afbjorklund** [comment]
Our workaround for Buildroot is to _replace_ the build steps. But it's a bit risky, you could end up missing things.

```Makefile
define PODMAN_BUILD_CMDS
	mkdir -p $(@D)/bin
	$(PODMAN_BIN_ENV) CIRRUS_TAG=$(PODMAN_VERSION) $(MAKE) $(TARGET_CONFIGURE_OPTS) -C $(@D) GIT_COMMIT=$(PODMAN_COMMIT) PREFIX=/usr podman
endef

define PODMAN_INSTALL_TARGET_CMDS
	$(INSTALL) -Dm755 $(@D)/bin/podman $(TARGET_DIR)/usr/bin/podman
	$(INSTALL) -d -m 755 $(TARGET_DIR)/etc/cni/net.d/
	$(INSTALL) -m 644 $(@D)/cni/87-podman-bridge.conflist $(TARGET_DIR)/etc/cni/net.d/87-podman-bridge.conflist
endef
```

**Comment by rhatdan** [comment]
Since there has been no PRs and no conclusion on the best way to handle this, I am going to close.  Open a PR to show how you would like to see the Makefile changed.
