### ISSUE TITLE
CI: need to reenable docs checks

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#8296]
CI v2.0 removed the man page vs --help check:
```
-        - '/usr/local/bin/entrypoint.sh clean podman xref_helpmsgs_manpages BUILDTAGS="exclude_graphdriver_devicemapper selinux seccomp" |& ${TIMESTAMP}'
```
This needs to be reenabled ASAP. Unfortunately, the situation is now completely broken, the `hack/xref-helpmsgs-manpages` script is failing, I will need to spin up an emergency PR to fix it.

**Comment by cevich** [comment]
@edsantiago re-assigned to you since my urgently requested fix, is effectively completely nullified by #8299
