### ISSUE TITLE
Error: statfs /tmp/secret: no such file or directory

### ISSUE THREAD

**Issue by winkeesail** [containers/podman#8302]
when I mount a local file on host machine to the container, this error pops out.
my commands are:

```
podman pull mysql:5.7
podman run --name ms5.7 -v $HOME/my_password:/tmp/my_password -e MYSQL_ROOT_PASSWORD_FILE=/tmp/my_password -d mysql:5.7
```
errors:
```
Error: statfs /Users/winkee/my_password: no such file or directory
```

Environment versions:
- Mac OS X, Mojave, 10.14.6
- podman version 

Client:
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Sat Sep 26 09:07:39 2020
OS/Arch:      darwin/amd64

Server:
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Thu Jan  1 08:00:00 1970
OS/Arch:      linux/amd64

Environment setups

```
brew cask install multipass
multipass launch -c 2 -d 10G -m 2G -n podman
<
...
setup podman service in Ubuntu VM
...
>
brew install podman
podman system connection add ubuntu ...
podman info
...
```

Explanation:
I launched a ubuntu instance in my virtual machine, and use podman client (on Mac OS) to connect to the podman service in ubuntu.

After that, I can use podman just like I use docker on Mac OS.

But when I test pulling a mysql image and try to mount a file to be used while creating the container instance, this error pops out and stop me from proceeding.

I tested the exact same command for docker, and it works perfectly, so I guess there is a potential issue with podman?

**Comment by Luap99** [comment]
Volumes over remote are not supported. The podman remote client will try to bind mount the file on the server side. 

see issue #8016

**Comment by winkeesail** [comment]
Thanks for the info. But are there workarounds or solutions if I need to mount files on my host machine?

**Comment by Luap99** [comment]
Well, you can copy it to your server and then mount it.

**Comment by jsirianni** [comment]
> Well, you can copy it to your server and then mount it.

This is not a great solution for development workflows. When coming from Docker, this is a large refression.

**Comment by Luap99** [comment]
docker does not mount via an actual remote connection either.

Docker desktop does provide support to mount directories in the VM. If you are looking for this we have the same with `podman machine -v ...`, see the linked issue. Also the home directory should be mounted as default wirh v4.1, https://github.com/containers/podman/pull/13849
