### ISSUE TITLE
First time run `podman run hello-world` in a vm got stuck

### ISSUE THREAD

**Issue by chenliu1993** [containers/podman#8303]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Hi exprts, I am currently working on a project which package podman binary in a container and then running this container in a vm. The goal of this project is to make users can go inside the container to play with podman.
The issue is not really a bug I think, just a little bit confused. 
Detail is:
    When I shell into the container (host shell => VM => container's sh on host) and pull && run hello-world, the `podman run hello-world` won't return back to shell, it got stuck. And through top cmd I can see that hello-world process is a zombie while conmon process still existed. 
    To break this stuck situation, ctrl-c is enough. And run hello-world again(podman run hello-world) won't got stuck. So this stuck issue only exists when first time running `podman run hello-world`
     I did a little debug, find this [https://github.com/containers/podman/blob/90c2cc6c8342e96ca0a21e59c3cdb7761b2229ea/libpod/oci_attach_linux.go#L222 ](url)
 Because the conn.Read() will never read EOF thus hello-world will got stuck. But why only first time? 

**Steps to reproduce the issue:**

1. podman pull hello-world 

2. podman run hello-world (stuck)

3. ctrl-c

4. podman run hello-world (won't stuck)

**Describe the results you received:**
First time hello-world outputs to the container sh while didn't return back.

**Describe the results you expected:**
container shell is returned 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.1.0
API Version:  2.0.0
Go Version:   go1.13.8
Git Commit:   d8868746fd3f45b9bfd79e37bf2aa0c7103245fd
Built:        Thu Sep 24 06:01:48 2020
OS/Arch:      linux/amd64```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.18, commit: 7b3e303be8f1aea7e0d4a784c8e64a75c14756a4'
  cpus: 2
  distribution:
    distribution: alpine
    version: 3.11.3
  eventLogger: file
  hostname: podman
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.19.138-7.ph3-esx
  linkmode: dynamic
  memFree: 767537152
  memTotal: 1038905344
  ociRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
      spec: 1.0.1-dev
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 37.07s
registries:
  search:
  - docker.io
  - quay.io
  - registry.fedoraproject.org
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: <unknown>
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1600927308
  BuiltTime: Thu Sep 24 06:01:48 2020
  GitCommit: d8868746fd3f45b9bfd79e37bf2aa0c7103245fd
  GoVersion: go1.13.8
  OsArch: linux/amd64
  Version: 2.1.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

In a Virtual Machine, The IO operation from container to VM and then from VM to host is like how kata does.

**Comment by rhatdan** [comment]
Can you reproduce this error?  IE Is this just the first time you run a rootless container in the VM, and now all future containers work?  If you create a different user inside of the container and run these commands, does it get stuck?

**Comment by chenliu1993** [comment]
Yes, I can reproduce this error every first time running podman run hello-world through the privileged container's shell. But I haven't try another user, let my try it. Thanks.

**Comment by rhatdan** [comment]
I take it that that worked for you with a different user. CLosing,
