### ISSUE TITLE
Static "nix" build fails to compile podman

### ISSUE THREAD

**Issue by cevich** [containers/podman#8313]
/kind bug

**Description**

After fixing a Cirrus-CI caching problem (related to available VM disk space on boot), podman fails to compile.  I've temporarily made the static build task "optional", so the failure is currently ignored.

**Steps to reproduce the issue:**

1.  Execute a Cirrus-CI build on a branch or in a PR

**Describe the results you received:**

```
  go build -mod=vendor  -gcflags 'all=-trimpath=/tmp/nix-build-podman.drv-0/podman' -asmflags 'all=-trimpath=/tmp/nix-build-podman.drv-0/podman' -ldflags '-X github.com/containers/podman/v2/libpod/define.gitCommit=12dbc1ff7dd7468f0be22e597ed9e552ad545e20-dirty -X github.com/containers/podman/v2/libpod/define.buildInfo=315532800 -X github.com/containers/podman/v2/libpod/config._installPrefix=/usr/local -X github.com/containers/podman/v2/libpod/config._etcDir=/etc -s -w -linkmode external -extldflags "-static -lm"' -tags "static netgo osusergo exclude_graphdriver_btrfs exclude_graphdriver_devicemapper seccomp apparmor selinux" -o bin/podman ./cmd/podman
  # runtime/cgo
  In file included from /nix/store/ypih4394q488ljr421x8jak55vmr0ckn-glibc-2.32-dev/include/errno.h:28,
                   from cgo-gcc-prolog:30:
  /nix/store/ypih4394q488ljr421x8jak55vmr0ckn-glibc-2.32-dev/include/bits/errno.h:26:11: fatal error: linux/errno.h: No such file or directory
     26 | # include <linux/errno.h>
        |           ^~~~~~~~~~~~~~~
  compilation terminated.
  make: *** [Makefile:195: bin/podman] Error 2
error: build of '/nix/store/q0256ixhmc5myyxpgqimw3gp1rqji8pq-podman.drv' failed
```

[Ref. Cirrus task output from master](https://cirrus-ci.com/task/6579811101442048?command=main#L89)

**Describe the results you expected:**

Exit 0

**Additional information you deem important (e.g. issue happens only occasionally):**

[As part of the fix, please comment out the line which causes failures to be ignored](https://github.com/containers/podman/blob/master/.cirrus.yml#L336)

Otherwise, please feel free to mention me if you need any help with the automation-side of things

**Comment by hswong3i** [comment]
Ummm... I have no idea why that fail coming... My local build with `nix build -f nix/` working correctly :-S

**Comment by rhatdan** [comment]
Looks like the package that provides  # include <linux/errno.h> on Nix did not get installed?

**Comment by cevich** [comment]
I think that's glibc, no?  Sorry my C isn't what I use to be...perhaps is there some search path or something that could be wrong?

In case it helps, I'm pretty sure the commit that broke this was https://github.com/containers/podman/commit/46498331a3 which unfortunately, AFAICT didn't change anything related to this job :cry:   

I know this because the job passed successfully a few commits earlier: https://github.com/containers/podman/runs/1353113376

**Comment by cevich** [comment]
One idea that just occurred to me: Maybe the cache (in Cirrus-CI) is "bad" for the key being used.  I can prefix the cache key with the output of `$(date +%VY)` (week + year number).  That will force a somewhat regular cache refresh.

**Comment by hswong3i** [comment]
Maybe just simply add '-v1' or '-v2' suffix to the cache key, which should be more simple for control?

**Comment by cevich** [comment]
Confirmed: It was simply bad cache.  [Running w/ fresh cached passes.](https://github.com/containers/podman/pull/8337/checks?check_run_id=1396634808)

> Maybe just simply add '-v1' or '-v2' suffix

That would work and I considered it...but then somebody needs to remember to bump it periodically :confused: 

Hmmm...Another idea (instead of using the date) is use the contents of `version/version.go`.  That would tie a cache-update to a bump of the release, which is only ever done by one person.  The context for that PR would also be more relevant to refreshing the cache (i.e. getting ready for a new podman release).

**Comment by cevich** [comment]
@mheon  What do you think about the `version/version.go` idea?   If the static build task fails in a release PR, there is a line in `.cirrus.yml` to uncomment to ignore the failure.  Otherwise the only difference would be the task runtime (<10min vs >30min for a release PR + nix cache refresh).

**Comment by mheon** [comment]
I will note that we've been going increasingly long without changing the contents of version.go on master given our move to release branches - 3 months between changes might become the norm. How often do we need this cache to flush?

**Comment by cevich** [comment]
@mheon I've got a better idea that using a date.  It's similar to what @hswong3 suggested above (using a manually updated 'v1' or 'v2' string)

It would be less surprising (on failure) for any PR's where we also change the tag identifying new VM and Container images.  This value exists in `.cirrus.yml` and is accessible at runtime for use as a cache-key.  It also happens somewhat regularly, since this is the mechanism by which we realize package and dependency updates (in general).
