### ISSUE TITLE
Signed Mac Binary

### ISSUE THREAD

**Issue by ashley-cui** [containers/podman#8314]
/kind feature

**Description**
On every release, we build podman-remote for Mac (attached [here](https://github.com/containers/podman/releases)). When these binaries are run, macos will pop up a window, warning the user that this binary is not signed, and recommends them to move it to their trash. We need to sign it somehow using an [apple developer ID](https://developer.apple.com/developer-id/). (Preferably without having to open a mac and manually sign it using xcode?) 

This is less of a problem than it used to be because of our brew packaging, but still something we should have. 

If anyone has any experience with signing mac apps, please feel free to share the wisdom you have

**Comment by rhatdan** [comment]
@ashley-cui any progress on this?

**Comment by ashley-cui** [comment]
@rhatdan I've been mostly wrapped up in the secrets work but I did do a little reading on this. There's guides online that show people signing Mac apps from Travis CI, but I haven't seen anything for cirrus, but I'd imagine there would be a similar process that could allow us to do it. We could also sign the mac binaries using the command line on a mac machine or the XCode GUI. 
I also know that there are other teams that do have a Mac Developer ID certificate that can sign things for us, but that would require us creating a ticket every time we need to sign a binary. Otherwise, we can get our own id and try integrating it into out CI. To test anything out (in our CI or even locally) I would need to get a Developer ID, since there's no test ID's (that I've read about at least)

**Comment by rhatdan** [comment]
Ok let's talk about this as Watercooler

**Comment by rhatdan** [comment]
@ashley-cui Lets bring this up again to get latest status.

**Comment by ashley-cui** [comment]
@rhatdan Was looking into getting an Apple Developer ID, but it looks like we fall under the category of an organization and need to have a D-U-N-S number, as well as be a legal organization, so we can't just sign up as like, "Podman Maintainers." This means that we probably need to sign it under Red Hat. I know Red Hat definitely has one, but I'm not sure who to contact to see if we can get access to that account, or if we could create a new one.

Here are the requirements for getting said Developer ID: https://developer.apple.com/programs/enroll/

**Comment by rhatdan** [comment]
@fatherlinux Could you look into this?

**Comment by rhatdan** [comment]
This one keeps rolling along, but will become more important when we get nearer to RHEL8.5.

**Comment by infiniteregrets** [comment]
I just downloaded this file: https://github.com/containers/podman/releases/download/v3.2.1/podman-remote-release-darwin.zip and did not get any such thing as unsigned binary. Can you please provide the exact steps to reproduce this? 
Currently on:
```
❯ uname -a
Darwin 192.168.1.4 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
```

**Comment by infiniteregrets** [comment]
hi @ashley-cui can you provide more info on this? Or has this issue been resolved

**Comment by ashley-cui** [comment]
Sure, after downloading podman, if you try to run it, on macs, a pop up will show and warn that the program is not safe because it is 1. not signed, and 2. downloaded from the internet. I think @baude is working on this though. Please let me know if you are able to see the pop up warning, @infiniteregrets

**Comment by infiniteregrets** [comment]
@ashley-cui Nope, didn't see any such pop up

**Comment by ashley-cui** [comment]
It's the right one. I'll give it another look today and update you :)

**Comment by infiniteregrets** [comment]
@ashley-cui sounds great! If there are any other mac related issues that I could possibly help then lmk!

**Comment by rhatdan** [comment]
@ashley-cui Any update?

**Comment by ashley-cui** [comment]
@rhatdan We know how to sign binaries as of now (though we still don't sign the binary artifacts on our release page), but in order to get it through Apple's gatekeeper fully, we need to send in every binary to Apple to notarize, which I think @baude looked at?

**Comment by infiniteregrets** [comment]
I wasnt able to reproduce the issue anyhow

**Comment by ashley-cui** [comment]
We should have a signed binary for the next release!

**Comment by infiniteregrets** [comment]
Awesome!
