### ISSUE TITLE
Commands Table format messed up in docs.podman.io

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman#8317]
I've not idea off the top of my head how to fix this, but did want to note that the table under the Commands heading is one long continuous line.  http://docs.podman.io/en/latest/markdown/podman.1.html#commands  

Something has obviously gone wrong translating the md to html, but I know not where and haven't divd in.

**Comment by rhatdan** [comment]
Perhaps one of our community people have an idea?
@Luap99 @zhangguanzhang Any ideas?

**Comment by Luap99** [comment]
@TomSweeneyRedHat I also noticed this.

I found this Issue: https://github.com/readthedocs/recommonmark/issues/3

This could be a possible solution: https://pypi.org/project/sphinx-markdown-tables/

**Comment by Luap99** [comment]
Fixed by #8335
