### ISSUE TITLE
RFE: `podman login {registry}` authenticates with Docker creds 

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman#8319]
On my test machine, I happened to first login to quay.io using `docker login`.  Later after installing Podman, I ran into this:

```
# podman login quay.io
Authenticating with existing credentials...
Existing credentials are valid. Already logged in to quay.io
```

I expected I would have to supply my credentials again, or at the very least, be told that I was logged in with Docker and I was using those credentials.  When I looked, there was no auth.json in the system for Podman and that might cause confusion.

Personally I think we should log in in this instance and not use the docker creds.  I didn't test buildah or skopeo's login commands, but suspect they do the same thing.

**Comment by rhatdan** [comment]
Yes we fall back to the Docker credentials, some of this was prior to tools have credential support.

**Comment by TomSweeneyRedHat** [comment]
I think falling back to the Docker creds when our tools are doing some action like run, build, copy, etc, is entirely reasonable.  However, I don't think we should claim to have "credentials" when we're doing 'podman login' and we've only logged in using `docker login`.  I hate to add a prompt asking if you want to continuing logging in at this case, but I think at the very least we should print out a message saying "Using Docker Credentials" or some such.  Now it just tells you that you're authenticated already.

But I'd prefer we'd just move on to asking for the un/pwd in this situation.

At least that's my nickel's worth.

**Comment by vrothberg** [comment]
I think that's very related to the other request to print out information about the origin of credentials (https://github.com/containers/podman/issues/6717).

Changing the behaviour and not fallback to using Docker creds might break some workflows. I am more in favour of giving users more context as discussed in https://github.com/containers/podman/issues/6717.

**Comment by rhatdan** [comment]
I agree we can not break the Docker Credentials.  It will become less common in the future, as people stop using it and go primarily to Podman.

**Comment by rhatdan** [comment]
Ok I am going to close this and continue the error in #6717
