### ISSUE TITLE
podman remote fails with connection error

### ISSUE THREAD

**Issue by bexelbie** [containers/podman#8340]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Cannot add a podman remote

**Steps to reproduce the issue:**

1. On a Mac brew install podman; receive latest version, 2.1.1

2. On a CentOS Stream box, set up the podman socket, and sshd per instructions.  Note: version 2.0.5 seems to be the latest.  SSH is working as expected

3.  On the Mac run `podman system connection add srv 192.168.0.227`

**Describe the results you received:**

Error: failed to connect to  "ssh://bexelbie@192.168.0.227:22": failed to parse 'podman info' results: json: cannot unmarshal number into Go struct field Version.version.APIVersion of type string

**Describe the results you expected:**

A connection created

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens consistently.  Downgrading to the 2.0.5 client on the Mac results in a connection entry, but all commands fail.

**Output of `podman version`:**

Mac
```
podman version 2.1.1
```

CentOS Stream
```
podman version 2.0.5
```

**Output of `podman info --debug`:**

Mac
```
Error: Get "http://d/v2.0.0/libpod../../../_ping": dial unix ///var/folders/br/6gbf6hbn5pv7bswz5n86zkm40000gn/T/run--1/podman/podman.sock: connect: no such file or directory
```

CentOS Stream 
```
host:
  arch: amd64
  buildahVersion: 1.15.1
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.20-2.module_el8.3.0+475+c50ce30b.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.20, commit: 1019ecdeda3936be22162bb1cca308192145de53'
  cpus: 4
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: localhost.localdomain
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-240.el8.x86_64
  linkmode: dynamic
  memFree: 18721136640
  memTotal: 20677484544
  ociRuntime:
    name: runc
    package: runc-1.0.0-68.rc92.module_el8.3.0+475+c50ce30b.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-2.module_el8.3.0+475+c50ce30b.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 10510921728
  swapTotal: 10510921728
  uptime: 407h 44m 26.59s (Approximately 16.96 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/bexelbie/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-3.module_el8.3.0+507+aa0970ae.x86_64
      Version: |-
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/bexelbie/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /home/bexelbie/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1600970293
  BuiltTime: Thu Sep 24 19:58:13 2020
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.0.5
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

Mac
```
% brew info podman
podman: stable 2.1.1 (bottled)
Tool for managing OCI containers and pods
https://podman.io/
/usr/local/Cellar/podman/2.1.1 (143 files, 37.1MB) *
  Poured from bottle on 2020-11-14 at 13:58:26
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0
==> Dependencies
Build: go ✘, go-md2man ✘
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Analytics
install: 1,742 (30 days), 7,316 (90 days), 7,318 (365 days)
install-on-request: 1,701 (30 days), 6,932 (90 days), 6,934 (365 days)
build-error: 0 (30 days)
```

CentOS Stream 
```
$ rpm -q podman
podman-2.0.5-5.module_el8.3.0+512+b3b58dca.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes - checked troubleshooting guide

No - have not tested a later version that is packaged for CentOS Stream 

**Additional environment details (AWS, VirtualBox, physical, etc.):**

2 separate physical boxes on a local wired network.  SSH works.

**Comment by zhangguanzhang** [comment]
centos8 could update to 2.1.1, and try again

**Comment by bexelbie** [comment]
@zhangguanzhang I don't believe that a newer version is packaged.  I find it odd that if there was a break in minor releases that wouldn't be in release notes somewhere.  I am hesitant to build my own package until we know that this wasn't intentional.

I've updated the title, as it was wrong.

**Comment by bexelbie** [comment]
This was the other error message I've received

```
% podman system connection add srv 192.168.0.227
Error: failed to connect to  "ssh://bexelbie@192.168.0.227:22": failed to parse 'podman info' results: json: cannot unmarshal number into Go struct field Version.version.APIVersion of type string
```

**Comment by rhatdan** [comment]
@jwhonce @baude PTAL
I have a feeling this was unexpected but intentional.   I am not sure we are being backwords compatible with the client, yet.

**Comment by bexelbie** [comment]
To add to my confusion, there are three module streams available in CentOS Stream 8:

1.0 which contains the 1.0 binary
2.0 which contains the 1.6.4 binary
rhel8 which contains the 2.0.5 binary

It'd be great to see a stream that was running to provide "latest", which is what I naively assumed 2.0 would be.  Perhaps we should update the docs to suggest when to use the other streams (rhel8 is default) or to state that they are being deprecated.

@rhatdan Thank you

**Comment by rhatdan** [comment]
Only podman 2.* support APIV2, so we at least need that version on the client and server.

**Comment by rhatdan** [comment]
You need to talk to @fatherlinux about the streams names.

**Comment by mheon** [comment]
The rhel8 stream is the latest - the others are long-term support streams that will stay on an older Podman version for stability, with critical bugfixes and security updates. They are not deprecated, though I believe the 1.0 stream is approaching that point (I believe the update guarantee is for 2 years, so 1.0 will be deprecated in 8.4 and a new 3.0 stream will be created; but I'm less clear on these points).

**Comment by bexelbie** [comment]
@mheon OK - makes sense.

**Comment by rhatdan** [comment]
I don't think this is an issue any longer after @mheon explanation, closing.
