### ISSUE TITLE
Volume filtering works differently and misses existing label

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman#8341]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Volume filtering works differently in podman, when compared to docker.

**Steps to reproduce the issue:**

1. minikube start --driver podman

2. sudo -n podman volume ls --filter label=name.minikube.sigs.k8s.io=minikube

3.

**Describe the results you received:**

```
```

**Describe the results you expected:**

```
DRIVER      VOLUME NAME
local       minikube
```

**Additional information you deem important (e.g. issue happens only occasionally):**

The --filter doesn't work with label:

`minikube start --driver podman`

```console
$ sudo -n podman volume ls --filter label=name.minikube.sigs.k8s.io=minikube
$ sudo -n podman volume ls 
DRIVER      VOLUME NAME
local       minikube
$ sudo -n podman volume inspect minikube
[
     {
          "Name": "minikube",
          "Driver": "local",
          "Mountpoint": "/var/lib/containers/storage/volumes/minikube/_data",
          "CreatedAt": "2020-11-14T15:13:11.855745076+01:00",
          "Labels": {
               "created_by.minikube.sigs.k8s.io": "true",
               "name.minikube.sigs.k8s.io": "minikube"
          },
          "Scope": "local",
          "Options": {
               
          },
          "UID": 0,
          "GID": 0,
          "Anonymous": false
     }
]
```

It works OK with the docker driver.

`minikube start --driver docker`

```console
$ docker volume ls --filter label=name.minikube.sigs.k8s.io=minikube
DRIVER              VOLUME NAME
local               minikube
$ docker volume inspect minikube
[
    {
        "CreatedAt": "2020-11-14T15:22:40+01:00",
        "Driver": "local",
        "Labels": {
            "created_by.minikube.sigs.k8s.io": "true",
            "name.minikube.sigs.k8s.io": "minikube"
        },
        "Mountpoint": "/var/lib/docker/volumes/minikube/_data",
        "Name": "minikube",
        "Options": {},
        "Scope": "local"
    }
]


```
**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 20.04

**Comment by afbjorklund** [comment]
There is some bug in the filter construction, that butchers the options.

```go
        for _, f := range cliOpts.Filter {
                filterSplit := strings.Split(f, "=")
                if len(filterSplit) < 2 {
                        return errors.Errorf("filter input must be in the form of filter=value: %s is invalid", f)
                }
                lsOpts.Filter[filterSplit[0]] = append(lsOpts.Filter[filterSplit[0]], filterSplit[1:]...)
        }

```
cliOpts.Filter [label=name.minikube.sigs.k8s.io=minikube]
lsOpts.Filter map[label:[name.minikube.sigs.k8s.io minikube]]

The bug is in GenerateVolumeFilters, in the loop construct.

So instead of checking key=value, it checks the key twice instead:

label name.minikube.sigs.k8s.io
label minikube

The filter switch needs to come _before_ the value loop.
```go
        for filter, v := range filters {
                for _, val := range v {
                        switch filter {
```

Otherwise it won't work for these label=key=value filters ?

`map[label:[name.minikube.sigs.k8s.io minikube]]`

It looks for a `'='` character, but it has already been lost.

```go
                        case "label":
                                filterArray := strings.SplitN(val, "=", 2)
```

**Comment by afbjorklund** [comment]
I think it was GenerateVolumeFilters that was right, when having multiple filters.

So it was the command line flag parser that was too greedy, splitting every '='

**Comment by afbjorklund** [comment]
It also seems that the login in Volumes() filtering is broken.

Currently it does an OR of the criteria, instead of an AND...

```go
        if len(filters) == 0 {
                return vols, nil
        }

        volsFiltered := make([]*Volume, 0, len(vols))
        for _, vol := range vols {
                include := false
                for _, filter := range filters {
                        include = include || filter(vol)
                }

                if include {
                        volsFiltered = append(volsFiltered, vol)
                }
        }

        return volsFiltered, nil
```
So as long as the label matches, it will include _every_ name:

`podman volume ls --filter name=foo,label=blue`

But that's a different bug than this one, just found while testing...

**Comment by Luap99** [comment]
>So as long as the label matches, it will include every name:

I think this is not a bug and expected. see: https://github.com/containers/podman/pull/8232

**Comment by afbjorklund** [comment]
Okay, then it was just the example in the docs that was silly (not updated)...
