### ISSUE TITLE
remote + build + RUN: emits spurious CR (^M)

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#8342]
Another variant of #7942 : RUN commands within a `podman build` are emitting an unwanted `^M`.

In window 1:
```console
$ bin/podman system service --timeout=0
```
In window 2:
```
$ printf "FROM alpine\nRUN echo hi\n" | bin/podman-remote build -t foo - | cat -vET
```
Output is below, contrasting podman (left) to podman-remote (right):
```
STEP 1: FROM alpine$                | STEP 1: FROM alpine$
STEP 2: RUN echo hi$                | STEP 2: RUN echo hi$
hi$                                 | hi^M$   <---- unwanted ^M
STEP 3: COMMIT foo$                 | STEP 3: COMMIT foo$
```
master @ 4eb9c28433f8aa1827f844881efb1ae1d15b0860; also present in podman-2.1.1-7.fc32

If/when this is fixed, please update test: https://github.com/containers/podman/blob/9fa09a83b30c5d9300eb40b3d50b405153b37f7a/test/system/070-build.bats#L358-L367

**Comment by rhatdan** [comment]
@nalind Any ideas what is causing this?

**Comment by nalind** [comment]
Is there a pseudo-terminal involved?  If so, does it have the "ONLCR" flag set on its output?  Running "stty -a" in that context would tell us, either with "onlcr" (set) or "-onlcr" (not set).

**Comment by edsantiago** [comment]
The terminal from which I'm running has `onlcr`; if I try `stty -onlcr` life is too horrible to contemplate. 

The `^M` happens even if I `s/|/|&/`, which presumably removes ptys completely out of the equation:
```console
$ printf "FROM alpine\nRUN echo hi\n" | bin/podman-remote build -t foo - |&  cat -vET
...
hi^M$
```

**Comment by nalind** [comment]
Is the command indicated in the RUN instruction being executed with a pseudo-terminal, and if so, is "onlcr" set in it?

Experimentally, it looks like `docker build` always disables use of pseudo-terminals for RUN, and I'm thinking we should switch to doing the same.  That would also make https://github.com/containers/buildah/pull/2577 viable.

**Comment by edsantiago** [comment]
Duh, sorry, I misunderstood.
```console
$ printf "FROM alpine\nRUN stty -a\n" | bin/podman-remote build -t foo - |& cat -vET
STEP 1: FROM alpine$
STEP 2: RUN stty -a$
speed 38400 baud;stty: standard input^M$
 line = 0;^M$
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>;^M$
eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R;^M$
werase = ^W; lnext = ^V; flush = ^O; min = 1; time = 0;^M$
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts^M$
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl ixon -ixoff^M$
-iuclc -ixany -imaxbel -iutf8^M$
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0^M$
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt^M$
echoctl echoke -flusho -extproc^M$
STEP 3: COMMIT foo$
...
$ printf "FROM alpine\nRUN stty -onlcr && echo hi\n" | bin/podman-remote build -t foo - |& cat -vET 
STEP 1: FROM alpine$
STEP 2: RUN stty -onlcr && echo hi$
hi$     <--- yippee!
STEP 3: COMMIT foo$
...
```
podman-non-remote for comparison:
```console
$ printf "FROM alpine\nRUN stty -a\n" | bin/podman build -t foo - |& cat -vET
STEP 1: FROM alpine$
STEP 2: RUN stty -a$
stty: standard input: Not a tty$
Error: error building at STEP "RUN stty -a": error while running runtime: exit status 1$
```

**Comment by rhatdan** [comment]
This is fixed in the main branch.
