### ISSUE TITLE
build: remote is verbosier than local

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#8343]
An unexpected (to me) difference in output between `podman` and `podman-remote`:
```console
$ printf "FROM alpine\nRUN true\n" | bin/podman-remote build -t foo -
```
Output below is podman(left), podman-remote (right)
```
STEP 1: FROM alpine         = STEP 1: FROM alpine
STEP 2: RUN true            = STEP 2: RUN true
STEP 3: COMMIT foo          = STEP 3: COMMIT foo
                            > Getting image source signatures
                            > Copying blob sha256:<sha1...>
                            > Copying blob sha256:<sha2...>
                            > Copying config sha256:<sha3...>
                            > Writing manifest to image destination
                            > Storing signatures
--> <sha11>                 = --> <different sha of course>
<sha64>                     = <another sha64>
```
It's probably not a big deal, and I'm OK with closing this as NOTABUG. I'm just curious if I should adapt my tests to work around this.

master @ 4eb9c28433f8aa1827f844881efb1ae1d15b0860

If this is fixed, please update test: https://github.com/containers/podman/blob/9fa09a83b30c5d9300eb40b3d50b405153b37f7a/test/system/070-build.bats#L358-L367

**Comment by rhatdan** [comment]
`buildah bud` works like podman remote.
They should be consistent,  
```
./bin/buildah bud /tmp
STEP 1: FROM alpine
STEP 2: RUN true
STEP 3: COMMIT
Getting image source signatures
Copying blob ace0eda3e3be skipped: already exists  
Copying blob bf839c0000a1 done  
Copying config 37b38535e9 done  
Writing manifest to image destination
Storing signatures
--> 37b38535e90
37b38535e90b1c51cdf0188bd46c744b358c546925906906dfc6e8a440dc7b54
```
@nalind WDYT?

**Comment by rhatdan** [comment]
@edsantiago I don't have easy access to Docker, could you see if Docker puts out this information about blobs?

**Comment by edsantiago** [comment]
Unfortunately it seems I no longer have a way to run docker either. Something has changed in the year or so since I last tried to set up RHEL subscriptions; it doesn't work any more. I've wasted an hour of my Sunday morning on it, giving up now. Will try again on Monday.

**Comment by nalind** [comment]
I think that output is written to the `ReportWriter` that's passed in `BuildOptions`.  If that option is set differently for remote and local builds, that would explain what you're seeing, and I think that'd be considered a bug.

**Comment by rhatdan** [comment]
You get the output when --layers=false

**Comment by rhatdan** [comment]
```
$ buildah bud --layers=true /tmp/
STEP 1: FROM alpine
STEP 2: RUN echo hello
--> Using cache 4de98db25baab655473e99941cb0980c2dbc89c8949906f09acdaf5ca23fb7b8
--> 4de98db25ba
STEP 3: RUN echo goodbye
--> Using cache 168452bf51ea00e7f56b6ab7dd667309fa6e6b599914e579c29ccb1535d7999a
--> 168452bf51e
STEP 4: RUN echo test2
test2
STEP 5: COMMIT
--> 74812aff1e2
74812aff1e268021cdd606dd9139f42bb4fc1dd02ac924e9c7a23f65ad98f72d
```
```
$ buildah bud --layers=false /tmp/
STEP 1: FROM alpine
STEP 2: RUN echo hello
hello
STEP 3: RUN echo goodbye
goodbye
STEP 4: RUN echo test2
test2
STEP 5: COMMIT
Getting image source signatures
Copying blob ace0eda3e3be skipped: already exists  
Copying blob 068908bfdfbf done  
Copying config d112db3949 done  
Writing manifest to image destination
Storing signatures
--> d112db39494
d112db39494d83c00a064a783e9496d25b492439dba0bfc29c06c5413ace10b6
```

**Comment by rhatdan** [comment]
I don't think this is a bug, it is just caused by cached images. Closing.
