### ISSUE TITLE
status filters for podman ps and podman pod ps should be inclusive

### ISSUE THREAD

**Issue by Luap99** [containers/podman#8344]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I want to filter the output for `podman ps`  to only contain created and exited containers for example.

Since filters are exclusive I cannot do this.

**Steps to reproduce the issue:**

1. `podman create alpine`

2. `podman ps --filter status=created,status=exited`

**Describe the results you received:**
empty output

**Describe the results you expected:**
show all created and exited containers

**Output of `podman version`:**

```
$ bin/podman version
Version:      2.2.0-dev
API Version:  2.0.0
Go Version:   go1.14.10
Git Commit:   4eb9c28433f8aa1827f844881efb1ae1d15b0860
Built:        Sat Nov 14 16:50:57 2020
OS/Arch:      linux/amd64
```

**Comment by zhangguanzhang** [comment]
libpod/runtime_ctr.go:804-808
```golang
	for _, ctr := range ctrs {
		include := true
		for _, filter := range filters {
			include = include && filter(ctr)
		}

		if include {
			ctrsFiltered = append(ctrsFiltered, ctr)
		}
	}
```
This code determines that if one of the filter conditions is not met, it will not match.

**Comment by rhatdan** [comment]
Do you know how Docker handles this?

**Comment by Luap99** [comment]
It does work with docker
```
# docker ps --filter status=created --filter status=exited 
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS                       PORTS               NAMES
42aec3a7874a        alpine              "sleep 1000"        58 seconds ago       Exited (137) 5 seconds ago                       affectionate_shaw
be48cb2a08aa        alpine              "/bin/sh"           About a minute ago   Created                                          vibrant_black
20bcf202d6d9        alpine              "/bin/sh"           About a minute ago   Created                                          pensive_clarke
```

**Comment by rhatdan** [comment]
Since the issue reported is fixed.  I am closing this issue.  We will follow along with #8376
