### ISSUE TITLE
podman images --format "{{json .}}" fails

### ISSUE THREAD

**Issue by maxamillion** [containers/podman#8354]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

/kind feature

**Description**

When using `podman images` with the `--format "{{json . }}"` option, podman produces the error message:
```
Error: template: list:1: function "json" not defined
``` 

**Steps to reproduce the issue:**

1. podman images quay.io/ansible/default-test-container:1.11 --format "{{json .}}"

2.

3.

**Describe the results you received:**
```
Error: template: list:1: function "json" not defined
```

**Describe the results you expected:**
json format output of the image information

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Wed Oct  7 11:21:20 2020
OS/Arch:      linux/amd64```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-3.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 0f53fb68333bdead5fe4dc5175703e22cf9882ab'
  cpus: 8
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: optiplex5055
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.8.18-300.fc33.x86_64
  linkmode: dynamic
  memFree: 18629120000
  memTotal: 32571674624
  ociRuntime:
    name: crun
    package: crun-0.15.1-1.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.15.1
      commit: eb0145e5ad4d8207e84a327248af76663d4e50dd
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-4.dev.giteecccdb.fc33.x86_64
    version: |-
      slirp4netns version 1.1.4+dev
      commit: eecccdb96f587b11d7764556ffacfeaffe4b6e11
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 20648550400
  swapTotal: 20648550400
  uptime: 23h 33m 53.39s (Approximately 0.96 days)
registries:
  search:
  - registry.redhat.io
  - registry.fedoraproject.org
  - registry.centos.org
  - docker.io
  - quay.io
store:
  configFile: /home/admiller/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.2.0-1.fc33.x86_64
      Version: |-
        fusermount3 version: 3.9.3
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/admiller/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 75
  runRoot: /run/user/1000/containers
  volumePath: /home/admiller/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1602087680
  BuiltTime: Wed Oct  7 11:21:20 2020
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.1.1```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Name        : podman
Epoch       : 2
Version     : 2.1.1
Release     : 12.fc33
Architecture: x86_64
Install Date: Wed 11 Nov 2020 08:34:06 AM CST
Group       : Unspecified
Size        : 46394700
License     : ASL 2.0
Signature   : RSA/SHA256, Wed 07 Oct 2020 11:30:16 AM CDT, Key ID 49fd77499570ff31
Source RPM  : podman-2.1.1-12.fc33.src.rpm
Build Date  : Wed 07 Oct 2020 11:21:18 AM CDT
Build Host  : buildvm-x86-12.iad2.fedoraproject.org
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : https://podman.io/
Bug URL     : https://bugz.fedoraproject.org/podman
Summary     : Manage Pods, Containers and Container Images
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical desktop running Fedora 33

**Comment by jwhonce** [comment]
@maxamillion 
From master, will be in podman 2.2

$ bin/podman images registry.fedoraproject.org/fedora --format '{{json .}}'
[
    {
        "Id": "79fd58dc76113dac76a120f22cadecc3b2d1794b414f90ea368cf66096700053",
        "Size": 181097798,
        "Labels": {
            "license": "MIT",
            "name": "fedora",
            "vendor": "Fedora Project",
            "version": "33"
        },
        "Names": [
            "registry.fedoraproject.org/fedora:latest"
        ],
        "Digest": "sha256:edd0366dd4164485d31bd05d06d3f4f549c4ef278e08141c2da65277dd10325c",
        "Digests": [
            "sha256:edd0366dd4164485d31bd05d06d3f4f549c4ef278e08141c2da65277dd10325c",
            "sha256:d0a84038959b1be3021cb7ffb6dae386d13a27c39519a2185eab5c4069e71295"
        ],
        "Created": 1603784951,
        "CreatedAt": "2020-10-27T07:49:11Z"
    }
]

/cc @mheon
