### ISSUE TITLE
PIDFile= references a path below legacy directory

### ISSUE THREAD

**Issue by mavit** [containers/podman#8369]
**Is this a BUG REPORT or FEATURE REQUEST?**

/kind bug

**Description**

On starting a systemd service generated by `podman generate systemd`, log messages like the following are generated:

```
/etc/systemd/system/container-squeeze.service:17: PIDFile= references a path below legacy directory /var/run/, updating /var/run/containers/storage/overlay-containers/5e31ca2b09faaaa7719790b24796021874bf2790e6441c50f4f4e4dc3318046d/userdata/conmon.pid → /run/containers/storage/overlay-containers/5e31ca2b09faaaa7719790b24796021874bf2790e6441c50f4f4e4dc3318046d/userdata/conmon.pid; please update the unit file accordingly.
```

**Steps to reproduce the issue:**

1. `cd /etc/systemd/system && podman generate systemd --name --files foo`
2. `systemctl enable --now container-foo.service`
3. `systemctl status container-foo.service`

**Describe the results you received:**
The generated file contained a line `PIDFile=/var/run/...`

**Describe the results you expected:**
The generated file contained a line `PIDFile=/run/...`

**Additional information you deem important:**
The issue appears to be cosmetic only for now.

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.14.9
Built:        Wed Sep 30 20:31:11 2020
OS/Arch:      linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.1.1-7.fc32.x86_64
systemd-245.8-2.fc32.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Comment by vrothberg** [comment]
Thanks, @mavit!

@containers/podman-maintainers PTAL. Could we start doing  a `s/\/var\/run/\/run\/`?

**Comment by rhatdan** [comment]
Yes, I think we should stop using /var/run and just use /run

**Comment by vrothberg** [comment]
@rhatdan took care of it.
