### ISSUE TITLE
Podman play kube does not recreate pod (requires removal first?)

### ISSUE THREAD

**Issue by nc-ruth** [containers/podman#8372]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I can't recreate pods using "podman play kube <pod>.yaml", it says: 
Error: error adding pod to state: name "<pod_name>" is in use: pod already exists

In the documentation, it states:
podman play kube will read in a structured file of Kubernetes YAML. It will then **recreate** the pod and containers described in the YAML. The containers within the pod are then started and the ID of the new Pod is output.

**Steps to reproduce the issue:**

1. Create a pod.yaml with a yaml pod specification.

2. Run podman play kube pod.yaml

3. Modify the pod.yaml (change a port or something).

4. Run podman play kube pod.yaml

**Describe the results you received:**
Error: error adding pod to state: name "<pod_name>" is in use: pod already exists

**Describe the results you expected:**
"pod have changed"

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Tried on: 2.1.1 and 1.6.4
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

CentOS 8.2

**Comment by mheon** [comment]
Dupe of https://github.com/containers/podman/issues/4478

**Comment by nc-ruth** [comment]
my bad mheon :) 
I will close the issue.
