### ISSUE TITLE
podman-remote cannot send tar content with correct dockerfile

### ISSUE THREAD

**Issue by kazimsarikaya** [containers/podman#8374]
Hello,
There is a two bug while sending tar to remote with podman-remote. 

First one is at: https://github.com/containers/podman/blob/master/pkg/bindings/images/build.go#L143 
~~~
params.Set("dockerfile", filepath.Base(containerFiles[0]))
~~~
docker file can be at anywhere so I don't think we set dockerfile parameter as only the file name. 

The second one is at: https://github.com/containers/podman/blob/master/pkg/bindings/images/build.go#L219
~~~
if !info.Mode().IsRegular() || path == s {
~~~
sources[0] is dockerfile and **path==s** always will be true. hence dockerfile will not be added to tar.

I use my own fork with tar compression with gzip and dockerignore parsing at https://github.com/kazimsarikaya/podman/tree/fix-send-tar 

I didn't create any push request however because I use additional gzip and dockerignore enhancements.

**Comment by zhangguanzhang** [comment]
could you show the steps to reproduce it?

**Comment by kazimsarikaya** [comment]
I started a podman system on a linux machine with:
~~~
/usr/local/bin/podman system service --time=0 tcp:192.168.99.114:1928
~~~

on osx machine I send a build request with:

~~~
declare -x CONTAINER_HOST="tcp://192.168.99.114:1928"
podman-remote  build -f docker/test.Dockerfile --platform linux/amd64  . 
~~~

And after sending context, the returned result is about not finding **test.Dockerfile**. Dockerfile path is changed. It should be **docker/test.Dockerfile**. The line 

~~~
params.Set("dockerfile", filepath.Base(containerFiles[0]))
~~~

removes directroy name. Probably the aim is always sending dockerfile if it is also removed by .dockerignore.

And also I reading/testing the code, nTar functions parameter sources contains docker file at index 0. for loop's first try with filepath.Walk, the line 

~~~
if !info.Mode().IsRegular() || path == s {
~~~

always returns true. because path and s is both the dockerfile. I found it when I implement .dockerignore when sending context as tar file.

The problem occurs when dockerfiles are inside subdirectories.

**Comment by zhangguanzhang** [comment]
https://github.com/kazimsarikaya/podman/commit/656526463d447f67933d600d14383ed5bb8b21c6
@rhatdan PTAL

**Comment by rhatdan** [comment]
@zhangguanzhang Are you opening a PR?

**Comment by kazimsarikaya** [comment]
I open an pr.

**Comment by kazimsarikaya** [comment]
I am still working on the pr #8456

**Comment by kazimsarikaya** [comment]
#8456 merged.
