### ISSUE TITLE
[RFE] podman system service: set default log level to info

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#8390]
/kind feature

I would love `podman system service` to be more verbose by default. At the moment it does not really print anything but I want to _see_ that it's alive, especially when throwing requests at it.

Setting the default log level to info could be a good first. Once done, I would love each request to be printed on info as well.

It may come in handy for future maintenance and debugging. The logs would now indicate that something's happening and also the order of requests etc.

@containers/podman-maintainers @WDYT?

**Comment by rhatdan** [comment]
Info level makes sense.  as long as we don't flood the logs with useless information.

**Comment by jwhonce** [comment]
@rhatdan Currently only debug floods the logs with  requests, headers etc
