### ISSUE TITLE
Cannot Create New Container With -cpu-shares= Using cgroups v1 and cgroups v2 on Raspbian Lite

### ISSUE THREAD

**Issue by Saroufim** [containers/podman#8396]
/kind bug

**Steps to reproduce the issue:**

1. Create a new container with run or create and pass --cpu-shares argument with cgroups v1. The following error will be obtained: 
`Error: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:390: setting cgroup config for procHooks process caused \\\"cannot set cpu limit: container could not join or create cgroup\\\"\"": OCI runtime error`

2. Load cgroups v2 and retry the run command and the following error will be obtained: 
"Error: error creating systemd unit `libpod-6b1b19071aa0f8c1592fc8a6f77e3d429f46a91fc97bc6bc086b7aeb6919bba3.scope`: got `failed`: OCI runtime error" 

3. Create the container without --cpu-shares and the container will be successfully created. 

**Additional information you deem important (e.g. issue happens only occasionally):**
Running Raspbian Lite on RPi3B+

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Thu Jan  1 02:00:00 1970
OS/Arch:      linux/arm

```

**Output of `podman info --debug`:**

```
host:
  arch: arm
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 4
  distribution:
    distribution: raspbian
    version: "10"
  eventLogger: journald
  hostname: VagrantCloud
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65536
    - container_id: 65537
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 10000
      size: 65536
    - container_id: 65537
      host_id: 100000
      size: 65536
  kernel: 5.4.72-v7+
  linkmode: dynamic
  memFree: 39612416
  memTotal: 969756672
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0~rc6+dfsg1
      commit: 1.0.0~rc6+dfsg1-3
      spec: 1.0.1
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.4
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 4374126592
  swapTotal: 4399816704
  uptime: 2m 40.38s
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 19
    paused: 0
    running: 17
    stopped: 2
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/user/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 22
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 0
  BuiltTime: Thu Jan  1 02:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/arm
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 2.1.1~2 armhf [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
None

**Comment by rhatdan** [comment]
Have you tried as root?

**Comment by Saroufim** [comment]
Yes it works swimmingly well with sudo. Now how do I make it work with rootless? I've already added 
```
[Service]
Delegate=memory pids cpu io
```
to `/etc/systemd/system/user@1000.service.d/delegate.conf`
and 
```
[Service]
Delegate=yes
```
with `systemctl edit user@1000.service`
Why isn't that enough?

**Comment by rhatdan** [comment]
@giuseppe @vrothberg PTAL

**Comment by giuseppe** [comment]
what is the error you get on cgroup v2?

On cgroup v1 it won't work.  Even if the cgroup is chowned, we don't support it in Podman, delegation to unprivileged users is not safe

**Comment by Saroufim** [comment]
Hello. Sorry for the delay, I ran into a few snafus that I had to address before being able to interact with podman again. In any case, the error yielded would be:
`Error: unable to start container "370879258ccd4e823ccec806fc3257c9339882fc24dbac99fdd047c3824b080e": sd-bus call: Permission denied: OCI runtime permission denied error`

Not only that but when mounting cgroups v2 (whether on boot or afterwards), running any container would yield an error such as running an already established container in this example:
`Error: unable to start container "a437f0c790a981af5524921297dcb95df08fe30931fb5a05df166eef3c65fb5b": systemd cgroup flag passed, but systemd support for managing cgroups is not available: OCI runtime error
`
This and other issues have gotten me thinking that Debian (Or Raspbian) are not ideal for working with podman. I'm preparing Fedora IoT for installation instead. Hopefully this will fix various issues and not just this one.

**Comment by giuseppe** [comment]
it looks like systemd is not available or it is too old.

Can you run something like `unshare -r systemd-run --scope --user echo hi`?

**Comment by Saroufim** [comment]
Output:

`Failed to create bus connection: No such file or directory`

systemd version:
```
apt list systemd
Listing... Done
systemd/buster-backports,now 245.6-1~bpo10+1 armhf [installed]
```

**Comment by Saroufim** [comment]
I'm closing this issue as I've switched to Fedora IoT and everything works fine on it. It is probably an issue with how debian handles cgroups v2.
