### ISSUE TITLE
New flake: unable to obtain cgroup stats: open /sys/fs/cgroup/pids/pids.current: ENOENT

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#8397]
This one started just yesterday, and it's hitting us all over the place. The basic gist is:
```console
$ podman-remote [options] pod stats --no-stream ...
Error: unable to obtain cgroup stats: open /sys/fs/cgroup/pids/pids.current: no such file or directory
```
Only on ubuntu-19 and -20; only root, not rootless. Seems to happen both local and remote. What changed yesterday?

------------------------

Podman pod stats [It] podman stats on running pods
* gce_instance:prior-ubuntu : int podman ubuntu-19 root host
  * PR #8363
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-on-running-pods--1)
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-on-running-pods--2)
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-on-running-pods--3)
* gce_instance:prior-ubuntu : int remote ubuntu-19 root host
  * PR #8170
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-on-running-pods--1)
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-on-running-pods--2)
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-on-running-pods--3)
* gce_instance:ubuntu : int podman ubuntu-20 root host
  * PR #8371
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-on-running-pods--1)
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-on-running-pods--2)
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-on-running-pods--3)

Podman pod stats [It] podman stats on a specific running pod
* gce_instance:prior-ubuntu : int podman ubuntu-19 root host
  * PR #8363
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-on-a-specific-running-pod--1)
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-on-a-specific-running-pod--2)
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-on-a-specific-running-pod--3)
* gce_instance:prior-ubuntu : int remote ubuntu-19 root host
  * PR #8170
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-on-a-specific-running-pod--1)
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-on-a-specific-running-pod--2)
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-on-a-specific-running-pod--3)
* gce_instance:ubuntu : int podman ubuntu-20 root host
  * PR #8371
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-on-a-specific-running-pod--1)
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-on-a-specific-running-pod--2)
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-on-a-specific-running-pod--3)

Podman pod stats [It] podman stats on a specific running pod with name
* gce_instance:prior-ubuntu : int podman ubuntu-19 root host
  * PR #8363
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-on-a-specific-running-pod-with-name--1)
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-on-a-specific-running-pod-with-name--2)
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-on-a-specific-running-pod-with-name--3)
* gce_instance:prior-ubuntu : int remote ubuntu-19 root host
  * PR #8170
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-on-a-specific-running-pod-with-name--1)
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-on-a-specific-running-pod-with-name--2)
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-on-a-specific-running-pod-with-name--3)
* gce_instance:ubuntu : int podman ubuntu-20 root host
  * PR #8371
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-on-a-specific-running-pod-with-name--1)
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-on-a-specific-running-pod-with-name--2)
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-on-a-specific-running-pod-with-name--3)

Podman pod stats [It] podman stats on a specific running pod with shortID
* gce_instance:prior-ubuntu : int podman ubuntu-19 root host
  * PR #8363
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-on-a-specific-running-pod-with-shortID--1)
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-on-a-specific-running-pod-with-shortID--2)
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-on-a-specific-running-pod-with-shortID--3)
* gce_instance:prior-ubuntu : int remote ubuntu-19 root host
  * PR #8170
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-on-a-specific-running-pod-with-shortID--1)
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-on-a-specific-running-pod-with-shortID--2)
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-on-a-specific-running-pod-with-shortID--3)
* gce_instance:ubuntu : int podman ubuntu-20 root host
  * PR #8371
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-on-a-specific-running-pod-with-shortID--1)
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-on-a-specific-running-pod-with-shortID--2)
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-on-a-specific-running-pod-with-shortID--3)
Podman pod stats [It] podman stats on all pods
* gce_instance:prior-ubuntu : int podman ubuntu-19 root host
  * PR #8363
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-on-all-pods--1)
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-on-all-pods--2)
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-on-all-pods--3)
* gce_instance:prior-ubuntu : int remote ubuntu-19 root host
  * PR #8170
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-on-all-pods--1)
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-on-all-pods--2)
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-on-all-pods--3)
* gce_instance:ubuntu : int podman ubuntu-20 root host
  * PR #8371
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-on-all-pods--1)
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-on-all-pods--2)
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-on-all-pods--3)

Podman pod stats [It] podman stats on net=host post
* gce_instance:prior-ubuntu : int podman ubuntu-19 root host
  * PR #8363
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-on-net-host-post--1)
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-on-net-host-post--2)
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-on-net-host-post--3)
* gce_instance:prior-ubuntu : int remote ubuntu-19 root host
  * PR #8170
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-on-net-host-post--1)
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-on-net-host-post--2)
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-on-net-host-post--3)
* gce_instance:ubuntu : int podman ubuntu-20 root host
  * PR #8371
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-on-net-host-post--1)
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-on-net-host-post--2)
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-on-net-host-post--3)

Podman pod stats [It] podman stats with GO template
* gce_instance:prior-ubuntu : int podman ubuntu-19 root host
  * PR #8363
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-with-GO-template--1)
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-with-GO-template--2)
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-with-GO-template--3)
* gce_instance:prior-ubuntu : int remote ubuntu-19 root host
  * PR #8170
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-with-GO-template--1)
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-with-GO-template--2)
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-with-GO-template--3)
* gce_instance:ubuntu : int podman ubuntu-20 root host
  * PR #8371
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-with-GO-template--1)
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-with-GO-template--2)
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-with-GO-template--3)

Podman pod stats [It] podman stats with json output
* gce_instance:prior-ubuntu : int podman ubuntu-19 root host
  * PR #8363
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-with-json-output--1)
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-with-json-output--2)
    * [11-17 14:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5552157690691584/html/int-podman-ubuntu-19-root-host.log.html#t--podman-stats-with-json-output--3)
* gce_instance:prior-ubuntu : int remote ubuntu-19 root host
  * PR #8170
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-with-json-output--1)
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-with-json-output--2)
    * [11-18 11:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5933768118632448/html/int-remote-ubuntu-19-root-host.log.html#t--podman-stats-with-json-output--3)
* gce_instance:ubuntu : int podman ubuntu-20 root host
  * PR #8371
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-with-json-output--1)
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-with-json-output--2)
    * [11-17 10:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4858815784943616/html/int-podman-ubuntu-20-root-host.log.html#t--podman-stats-with-json-output--3)

**Comment by rhatdan** [comment]
@giuseppe @cevich WDYT?
Seems like something is screwed up in cgroups V1 on these boxes?  Could their be new versions of Ubuntu out there?

**Comment by edsantiago** [comment]
So, #8290 merged yesterday, and it deals with stats and cgroups. My quick look at it doesn't find anything that could be related to this failure, but it's the only cgroup or stats PR in the last few weeks. @vrothberg would you mind looking at the failures above and seeing if your PR could have possibly caused this?

**Comment by vrothberg** [comment]
#8290 may be related but it doesn't add up yet.

@giuseppe WDYT?

**Comment by giuseppe** [comment]
> #8290 may be related but it doesn't add up yet.
> 
> @giuseppe WDYT?

it could be.  If the host is on cgroup v1, there are multiple controllers present in `/proc/PID/cgroup` and we may be using the wrong one?

**Comment by cevich** [comment]
Yes...both Ubuntu 19/20 are cgv1 w/ runc coming from OBS.

**Comment by edsantiago** [comment]
I don't think it's a runc issue; I did a quick check yesterday, comparing `package_versions` from today vs 2 weeks ago, and runc/crun are the same. I'm feeling more and more certain that it's #8290

**Comment by zhangguanzhang** [comment]
https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5207530957701120/html/int-remote-ubuntu-20-root-host.log.html
```
         Running: podman-remote [options] pod stats --no-stream
[+2840s] Error: unable to obtain cgroup stats: open /sys/fs/cgroup/pids/pids.current: no such file or directory
```
on my host , 
```
[root@Centos8 ~]# ls -l /sys/fs/cgroup/pids/ | grep pids
# no output
```

**Comment by edsantiago** [comment]
Ooooh! If you still have access to this system, can you post the results of `cat /proc/$$/cgroup` please?

**Comment by zhangguanzhang** [comment]
```
[root@Centos8 ~]# ls -l /sys/fs/cgroup/pids/ | grep pids
[root@Centos8 ~]# cat /proc/$$/cgroup
12:freezer:/
11:perf_event:/
10:hugetlb:/
9:cpu,cpuacct:/user.slice
8:net_cls,net_prio:/
7:memory:/user.slice/user-0.slice/session-78.scope
6:pids:/user.slice/user-0.slice/session-78.scope
5:rdma:/
4:devices:/user.slice
3:blkio:/user.slice
2:cpuset:/
1:name=systemd:/user.slice/user-0.slice/session-78.scope
```

**Comment by edsantiago** [comment]
Thank you! @giuseppe @vrothberg I hope that helps?

**Comment by vrothberg** [comment]
Opened https://github.com/containers/podman/pull/8422 after talking with @giuseppe

**Comment by vrothberg** [comment]
Thanks for providing all the data, @edsantiago
