### ISSUE TITLE
requested IP address 172.18.24.103 is not available in range set 172.18.24.1-172.18.24.254

### ISSUE THREAD

**Issue by laf0rge** [containers/podman#8403]
* A fresh, plain, new installation of podman on Debian 10 using devel:/kubic:/libcontainers:/stable
* a fresh, never used new docker network was created with the 172.17.24.0/24 range: `podman network create --internal --subnet 172.18.24.0/24 ttcn3-gbproxy-test`
* no containers running on on the system (verified with `podman ps`)
* trying to execute the container with a static IP well within that range of the network: `podman run --rm --network ttcn3-gbproxy-test --ip 172.18.24.10 --ulimit core=-1 -v /tmp/tmp.sfWj6EpGoL/sgsn:/data --name nonjenkins-sgsn -d root/osmo-sgsn-master /bin/sh -c osmo-gbproxy -c /data/osmo-gbproxy.cfg >/data/osmo-gbproxy.log 2>&1`

Result: `Error: error configuring network namespace for container b2070138703930fdc35ea1367b0470c572dc3bd81758bf6e8fced27584fd7b36: failed to allocate for range 0: requested IP address 172.18.24.10 is not available in range set 172.18.24.1-172.18.24.254`

<pre>
# podman network inspect ttcn3-gbproxy-test
[
  {
    "cniVersion": "0.4.0",
    "name": "ttcn3-gbproxy-test",
    "plugins": [
      {
        "bridge": "cni-podman1",
        "hairpinMode": true,
        "ipam": {
          "ranges": [
            [
              {
                "gateway": "172.18.24.1",
                "subnet": "172.18.24.0/24"
              }
            ]
          ],
          "routes": [
            {
              "dst": "0.0.0.0/0"
            }
          ],
          "type": "host-local"
        },
        "isGateway": false,
        "type": "bridge"
      },
      {
        "capabilities": {
          "portMappings": true
        },
        "type": "portmap"
      },
      {
        "backend": "",
        "type": "firewall"
      },
      {
        "domainName": "dns.podman",
        "type": "dnsname"
      }
    ]
  }
]
</pre>

**Comment by mheon** [comment]
Any chance you deleted/recreated a container using that static IP previously? We could have a leftover lease file for the IP.

**Comment by mheon** [comment]
Given the lack of any further info from the reporter, I'm going to assume this will be fixed in our next release via https://github.com/containers/podman/pull/8692 and close
