### ISSUE TITLE
Cannot start a container imported from a newer version of podman.ssh 

### ISSUE THREAD

**Issue by TrevorBenson** [containers/podman#8407]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

An image created and saved on podman 2.1.1 (from Fedora 33) that is imported into podman 1.6.4 (to CentOS 8.2.2004) is failing to run. The error is:
`Error: container_linux.go:349: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": OCI runtime command not found error`

- I am running the containers _rootless_ on both the source and targets 
- Using `podman run -it repository/imagename:tag` works on the source.
- Using `podman start` and then `podman attach` for the built container also works on the source.

**Steps to reproduce the issue:**

1. Build container on podman 2.1.1 `podman build ./path/to/dockerfile_directory/ -t repository/imagename:tag`

2. Save container to tarball `podman save > image-name.tar repository/imagename:tag` 

3. Copy to remote system with podman 1.6.4 (CentOS 8)

4. Import the tarball to the local repository `cat image-name.tar | podman import -`

5. Attempt to run the image either via CMD or setting a new ENTRYPOINT `podman run -it repository/imagename:tag /bin/sh` **or** `podman run -it -entrypoint "/bin/sh" repository/imagename:tag`

**Describe the results you received:**
The target site produces the following error:
`Error: container_linux.go:349: starting container process caused "exec: \"/bin/sh\": stat /bin/sh: no such file or directory": OCI runtime command not found error`

**Describe the results you expected:**
Expected the target site to start the container process normally via both entrypoint and command.

**Additional information you deem important (e.g. issue happens only occasionally):**
I've exported and imported from podman 1.6.4 to podman 1.6.4, this appears to work as expected.

**Output of `podman version`:**

- **Podman Source (Build/Save):**
```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Wed Oct  7 09:21:20 2020
OS/Arch:      linux/amd64
```

- **Podman Target (Import/Run):**
```
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.13.4
OS/Arch:            linux/amd64
```

**Output of `podman info --debug`:**

- **Podman Source (Build/Save):**
```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-3.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 0f53fb68333bdead5fe4dc5175703e22cf9882ab'
  cpus: 16
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: physical-test
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
  kernel: 5.8.18-300.fc33.x86_64
  linkmode: dynamic
  memFree: 651821056
  memTotal: 84319129600
  ociRuntime:
    name: crun
    package: crun-0.15.1-1.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.15.1
      commit: eb0145e5ad4d8207e84a327248af76663d4e50dd
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1002/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-4.dev.giteecccdb.fc33.x86_64
    version: |-
      slirp4netns version 1.1.4+dev
      commit: eecccdb96f587b11d7764556ffacfeaffe4b6e11
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 12314206208
  swapTotal: 12738093056
  uptime: 232h 56m 34.04s (Approximately 9.67 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/someusername/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.2.0-1.fc33.x86_64
      Version: |-
        fusermount3 version: 3.9.3
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/someusername/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 556
  runRoot: /run/user/1002/containers
  volumePath: /home/someusername/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1602087680
  BuiltTime: Wed Oct  7 09:21:20 2020
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.1.1
```

- **Podman Target (Import/Run):**
```
debug:
  compiler: gc
  git commit: ""
  go version: go1.13.4
  podman version: 1.6.4
host:
  BuildahVersion: 1.12.0-dev
  CgroupVersion: v1
  Conmon:
    package: conmon-2.0.6-1.module_el8.2.0+305+5e198a41.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.6, commit: a2b11288060ebd7abd20e0b4eb1a834bbf0aec3e'
  Distribution:
    distribution: '"centos"'
    version: "8"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  MemFree: 107266048
  MemTotal: 2936188928
  OCIRuntime:
    name: runc
    package: runc-1.0.0-65.rc10.module_el8.2.0+305+5e198a41.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  SwapFree: 1301016576
  SwapTotal: 2151673856
  arch: amd64
  cpus: 2
  eventlogger: journald
  hostname: virtual-test
  kernel: 4.18.0-193.28.1.el8_2.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.2-3.git21fdece.module_el8.2.0+305+5e198a41.x86_64
    Version: |-
      slirp4netns version 0.4.2+dev
      commit: 21fdece2737dc24ffa3f01a341b8a6854f8b13b4
  uptime: 232h 46m 27.32s (Approximately 9.67 days)
registries:
  blocked: null
  insecure: null
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  ConfigFile: /home/myuser/.config/containers/storage.conf
  ContainerStore:
    number: 9
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-5.module_el8.2.0+305+5e198a41.x86_64
      Version: |-
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  GraphRoot: /home/myuser/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 12
  RunRoot: /run/user/1001
  VolumePath: /home/myuser/.local/share/containers/storage/volumes
```
**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

- **Podman Source (Build/Save):**
```
podman-2.1.1-12.fc33.x86_64
```

- **Podman Target #1(Import/Run):**
```
podman-1.6.4-10.module_el8.2.0+305+5e198a41.x86_64
```

- **Podman Target #2(Import/Run):**
```
podman-1.6.4-10.module_el8.2.0+305+5e198a41.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

- Latest Version: NO
- Troubleshooting Guide: YES

Issue 26 was the closest to the error, however architecture on both all systems involved in tests is x86_64.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- Fedora 33: Physical host
- CentOS 8: Virtual Machine (Podman Target #1) & Physical (Podman Target #2)

Both physical/virtual targets are same OS and kept in sync. Most of the requested details I did not provide a unique output for both, so all results are Target #1.  I did include both results for the package version to provide confirmation the same RPM was in use in physical and virtual CentOS targets.

Thanks

**Comment by rhatdan** [comment]
@QiWang19 @vrothberg @mtrmac Any ideas?

**Comment by vrothberg** [comment]
I think some commands were mixed up>

`podman save/load` are for images while `podman export/import` are for containers.

**Comment by TrevorBenson** [comment]
> I think some commands were mixed up.
> 
> `podman save/load` are for images while `podman export/import` are for containers.

The issue definitely is on my side with running the wrong command. The above statement makes it clear and we can close the ticket.

**Food for thought**

Since one is about images and the other about containers I find it interesting that the word container is found in podman save documentation for **container archive** and podman load has it multiple times referencing **container image archive** or the latter **container archive**. Yet the podman import documentation never once uses the word container or references creating a **container image archive**. Import doc however does clearly list podman-export under the **see-also** section. 

I'm not requesting any specific doc changes, just providing some thoughts. 

Thanks

**Comment by vrothberg** [comment]
Thanks for the feedback, @TrevorBenson! I totally agree. It's a reoccurring issue and I stepped into the trap many times. Podman inherited these commands from Docker and I believe it was a mistake to put the commands on the same level. A `podman {container,image} {save,load}` may be much easier to wrap the head around as the "container" and "image" sub-command give the context.

I like your idea to have a look at the man pages and `--help` texts. The latter may even highlight that difference to the container/image counterpart.

@TrevorBenson, are you interested in opening a PR?

**Comment by vrothberg** [comment]
Looks like @QiWang19 already opened a PR (https://github.com/containers/podman/pull/8459), thanks!

**Comment by TrevorBenson** [comment]
Great. If someone else has taken up the torch I'll leave it to them.
Otherwise I'm definitely willing to think of revisions and submit PR's for
documentation.

Thanks!
