### ISSUE TITLE
seeing different manifest versions for an image built on centos 8 and fedora 33

### ISSUE THREAD

**Issue by jmccormick2001** [containers/podman#8412]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

/kind bug

**Description**

I'm seeing podman use different manifest types when I build on Fedora 33 versus Centos 8:

On Fedora I get the folllowing when I run 'podman inspect':
"ManifestType": "application/vnd.docker.distribution.manifest.v2+json",
"io.buildah.version": "1.16.1"

On Centos 8 I get the following when I run 'podman inspect':
 "ManifestType": "application/vnd.oci.image.manifest.v1+json",
 "io.buildah.version": "1.16.1",

**Steps to reproduce the issue:**

1. run podman inspect on a built container on Fedora 32/32

2. run podman inspect on a built container image on Centos 8

**Describe the results you received:**

the manifest versions are different

**Describe the results you expected:**
the manifest versions would be the same

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
on fedora 33:
```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Wed Oct  7 11:21:20 2020
OS/Arch:      linux/amd64
```

on Centos 8:

```
[jeffmc@snoot ~]$ podman version
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.13.15
Built:        Fri Oct 30 18:23:30 2020
OS/Arch:      linux/amd64```

**Output of `podman info --debug`:**
on fedora 33:
```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-3.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 0f53fb68333bdead5fe4dc5175703e22cf9882ab'
  cpus: 8
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: mojo
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.8.17-300.fc33.x86_64
  linkmode: dynamic
  memFree: 15988940800
  memTotal: 17182998528
  ociRuntime:
    name: crun
    package: crun-0.15-5.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.15
      commit: 56ca95e61639510c7dbd39ff512f80f626404969
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-4.dev.giteecccdb.fc33.x86_64
    version: |-
      slirp4netns version 1.1.4+dev
      commit: eecccdb96f587b11d7764556ffacfeaffe4b6e11
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 7516184576
  swapTotal: 7516184576
  uptime: 1m 46.08s
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/jeffmc/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.2.0-1.fc33.x86_64
      Version: |-
        fusermount3 version: 3.9.3
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/jeffmc/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 47
  runRoot: /run/user/1000/containers
  volumePath: /home/jeffmc/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1602087680
  BuiltTime: Wed Oct  7 11:21:20 2020
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.1.1
```

on centos 8:
```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.13.15
Built:        Fri Oct 30 18:23:30 2020
OS/Arch:      linux/amd64
[jeffmc@snoot ~]$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.21-1.el8.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 3701b9d2b0bd16229427f6f372cb3b96243fe19b-dirty'
  cpus: 8
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: journald
  hostname: snoot
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-193.el8.x86_64
  linkmode: dynamic
  memFree: 16547168256
  memTotal: 17057132544
  ociRuntime:
    name: runc
    package: runc-1.0.0-65.rc10.module_el8.2.0+305+5e198a41.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-0.4.2-3.git21fdece.module_el8.2.0+305+5e198a41.x86_64
    version: |-
      slirp4netns version 0.4.2+dev
      commit: 21fdece2737dc24ffa3f01a341b8a6854f8b13b4
  swapFree: 2147479552
  swapTotal: 2147479552
  uptime: 6m 14.07s
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/jeffmc/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-5.module_el8.2.0+305+5e198a41.x86_64
      Version: |-
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/jeffmc/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 27
  runRoot: /run/user/1000
  volumePath: /home/jeffmc/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1604100210
  BuiltTime: Fri Oct 30 18:23:30 2020
  GitCommit: ""
  GoVersion: go1.13.15
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

on centos 8
```
podman-2.1.1-10.el8.x86_64
```
on fedora 33
```
podman-2.1.1-12.fc33.x86_64
```
**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM running under KVM on a Fedora physical host.

**Comment by mheon** [comment]
@TomSweeneyRedHat @nalind PTAL

**Comment by rhatdan** [comment]
@mtrmac PTAL

**Comment by mtrmac** [comment]
@jmccormick2001 Thanks for your report. If this is really exactly the same Podman version, that’s certainly unexpected.

Can you upload and collect debug logs from both builds, please (`podman --log-level=debug bud …` or the like) ?

Another thing to test would be whether it is the platform that matters, or whether the manifest changes on repeated uploads; e.g. try using the same host and build+push the same image twice in a row and see whether that impacts the manifest (this is not a _known_ impact of https://github.com/containers/image/issues/733 but it looks a bit similar).

**Comment by jmccormick2001** [comment]
I did some more testing of this today, I can't reproduce it sadly.  What I do notice is that I have to specify --format=docker to get either of these to build a v2 manifest which I guess is expected?   I still see issues when I push these to quay.io, in that if I pull down the images from quay.io, I get back a v1 manifest image.  But I think that is being tracked in another issue.

**Comment by rhatdan** [comment]
Ok I am going to close, reopen if it happens again.
