### ISSUE TITLE
podman container image does not work properly when running in OpenShift container

### ISSUE THREAD

**Issue by seansund** [containers/podman#8417]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

We have a Tekton pipeline that uses the quay.io/podman/stable:latest (v2.0.11) image as the container base to build container images for an operator project. The flow uses podman to build and push a "bundle" image to the container registry then in a later step uses opm (and podman internally) to build a catalog image from that bundle.

The opm command pulls the bundle image and attempts to copy the contents out of the image into the filesystem so they can be repackaged into another container image. The process fails while copying the contents with this error:

```
Error: error resolving storage path for container 61862a5aa3c1fa8fd8767d3b8b58d6399cd68a49e7027db9b7848c5ecaa39e8c: lstat /var/lib/containers/storage/overlay/60386b5f690b6e884c9217dc1b7cdb609ecbdc2b5ee9b1fd1137a7fba587b6a6/merged: invalid argument\n" bundles="[us.icr.io/garage-dev-tools/memcached-operator-ansible-bundle:0.0.2]"
time="2020-11-11T19:12:36Z" level=error msg="permissive mode disabled" bundles="[us.icr.io/garage-dev-tools/memcached-operator-ansible-bundle:0.0.2]" error="error copying container directory Error: error resolving storage path for container 61862a5aa3c1fa8fd8767d3b8b58d6399cd68a49e7027db9b7848c5ecaa39e8c: lstat /var/lib/containers/storage/overlay/60386b5f690b6e884c9217dc1b7cdb609ecbdc2b5ee9b1fd1137a7fba587b6a6/merged: invalid argument\n: exit status 125"
```

It appears that the underlying problem is that the opm tool expects the contents to be mounted into a `/merged` directory but it doesn't exist. As we understand it, the `/merged` directory is created when the `overlay2` storage driver is used. 

The container image used for the opm build is quay.io/ibmgaragecloud/operator-sdk:v0.6.0 (which is based off of quay.io/podman/stable:latest, v0.2.11).

**Steps to reproduce the issue:**

It works correctly if these commands are run from my Mac:

1. Start the docker image: `docker run --privileged -it quay.io/ibmgaragecloud/operator-sdk:v0.6.0`

2. Run the opm command: `opm index add --bundles quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2 --tag quay.io/ibmgaragecloud/operator-catalog:0.0.1 --pull-tool podman`

**HOWEVER:** when it runs in a pod in the cluster it fails

1. Create a file named `opm-job.yaml` and paste the following into the file:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: opm-job
spec:
  template:
    metadata:
      labels:
        run: opm-job
    spec:
      serviceAccountName: opm-job
      volumes:
      - name: varlibcontainers
        emptyDir: {}
      containers:
      - image: quay.io/ibmgaragecloud/operator-sdk:v0.6.0
        name: opm
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/containers
          name: varlibcontainers
        command:
        - /bin/bash
        - -c
        - |
          echo "podman version"
          podman version
          echo "---"
          echo "podman info --debug"
          podman info --debug
          echo "---"
          echo "podman package info"
          rpm -q podman
          echo "---"

          echo "opm index add --bundles quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2 --tag quay.io/ibmgaragecloud/operator-catalog:0.0.1 --pull-tool podman"
          opm index add --bundles quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2 --tag quay.io/ibmgaragecloud/operator-catalog:0.0.1 --pull-tool podman
      restartPolicy: Never
```

2. Create a file named `opm-job.sh` in the same directory as the yaml file and paste the following into the file:

```
#!/usr/bin/env bash
SCRIPT_DIR=$(cd $(dirname $0); pwd -P)
oc create sa opm-job
oc adm policy add-scc-to-user privileged -z opm-job
oc create -f "${SCRIPT_DIR}/opm-job.yaml"
sleep 20
oc logs job/opm-job -f
```

3. Make `opm-job.sh` executable - `chmod +x opm-job.sh`
4. Log into an OpenShift cluster
5. Create a project where the job will run, e.g. `opm-test` - `oc new-project opm-test`
6. Run the shell script to deploy the job - `./opm-job.sh`

It should start the job and print the log from the job

**Describe the results you received:**

The command fails with an error resolving the storage path. The logs look like 
```
time="2020-11-19T21:52:21Z" level=info msg="building the index" bundles="[quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2]"
time="2020-11-19T21:52:21Z" level=info msg="running /usr/bin/podman pull quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2" bundles="[quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2]"
time="2020-11-19T21:52:22Z" level=info msg="running podman create" bundles="[quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2]"
time="2020-11-19T21:52:22Z" level=info msg="running podman cp" bundles="[quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2]"
time="2020-11-19T21:52:22Z" level=error msg="Error: error resolving storage path for container 29baf9b96f58710979ce75a6b9c8225d11880066ff53bb7a8a238bafec38d80f: lstat /var/lib/containers/storage/overlay/5e396bd63d5e10704148e6963b9035753385a6b4323cdc014733ab1c16828393/merged: invalid argument\n" bundles="[quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2]"
time="2020-11-19T21:52:22Z" level=error msg="permissive mode disabled" bundles="[quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2]" error="error copying container directory Error: error resolving storage path for container 29baf9b96f58710979ce75a6b9c8225d11880066ff53bb7a8a238bafec38d80f: lstat /var/lib/containers/storage/overlay/5e396bd63d5e10704148e6963b9035753385a6b4323cdc014733ab1c16828393/merged: invalid argument\n: exit status 125"
Error: error copying container directory Error: error resolving storage path for container 29baf9b96f58710979ce75a6b9c8225d11880066ff53bb7a8a238bafec38d80f: lstat /var/lib/containers/storage/overlay/5e396bd63d5e10704148e6963b9035753385a6b4323cdc014733ab1c16828393/merged: invalid argument
: exit status 125
```

**Describe the results you expected:**

The log output should look something like this:

```
INFO[0000] building the index                            bundles="[quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2]"
INFO[0000] running /usr/bin/podman pull quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2  bundles="[quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2]"
INFO[0002] running podman create                         bundles="[quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2]"
INFO[0003] running podman cp                             bundles="[quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2]"
INFO[0004] running podman rm                             bundles="[quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2]"
INFO[0004] Could not find optional dependencies file     dir=bundle_tmp190385226 file=bundle_tmp190385226/metadata load=annotations
INFO[0004] found csv, loading bundle                     dir=bundle_tmp190385226 file=bundle_tmp190385226/manifests load=bundle
INFO[0004] loading bundle file                           dir=bundle_tmp190385226/manifests file=cache.example.com_memcacheds.yaml load=bundle
INFO[0004] loading bundle file                           dir=bundle_tmp190385226/manifests file=memcached-operator-ansible-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml load=bundle
INFO[0004] loading bundle file                           dir=bundle_tmp190385226/manifests file=memcached-operator-ansible.clusterserviceversion.yaml load=bundle
INFO[0004] Generating dockerfile                         bundles="[quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2]"
INFO[0004] writing dockerfile: index.Dockerfile413833048  bundles="[quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2]"
INFO[0004] running podman build                          bundles="[quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2]"
INFO[0004] [podman build --format docker -f index.Dockerfile413833048 -t quay.io/ibmgaragecloud/operator-catalog:0.0.1 .]  bundles="[quay.io/ibmgaragecloud/memcached-operator-bundle:0.0.2]"
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Wed Oct  7 16:21:20 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.21-3.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 0f53fb68333bdead5fe4dc5175703e22cf9882ab'
  cpus: 4
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: file
  hostname: opm-job-fxcw2
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 3.10.0-1160.2.2.el7.x86_64
  linkmode: dynamic
  memFree: 738107392
  memTotal: 31245389824
  ociRuntime:
    name: crun
    package: crun-0.15.1-1.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.15.1
      commit: eb0145e5ad4d8207e84a327248af76663d4e50dd
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 243h 5m 37.52s (Approximately 10.12 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /var/lib/shared
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.2.0-1.fc33.x86_64
      Version: |-
        fusermount3 version: 3.9.3
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.3
        using FUSE kernel interface version 7.31
    overlay.mountopt: nodev,fsync=0
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1602087680
  BuiltTime: Wed Oct  7 16:21:20 2020
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.1.1-12.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

OpenShift 4.5 cluster running in IBMCloud

**Comment by csantanapr** [comment]
Thanks @seansund for written down the blocker that prevents on making progress on implementing a generic tekton pipeline to build and deploy operators on OpenShift

**Comment by mheon** [comment]
The problem is that CRI-O, which is running the container with Podman in it, is also using Overlay; and Overlay atop Overlay is not supported by the kernel. There are three ways forward, listed in descending order of preference.
- Mount a volume onto `/var/lib/containers/storage` in the container - this is what is usually done.
- Add `/dev/fuse` into the container, and modify `storage.conf` to use fuse-overlayfs.
- Modify `storage.conf` to use the VFS storage driver. This storage driver does not support layer deduplication and thus has large storage needs, but will run atop almost anything.

**Comment by mheon** [comment]
Though, we're not seeing the errors I'd expect out of c/storage - I'd expect an error trying to mount the filesystem, and instead we've gotten past that point without an error and instead are producing errors after the fact where the mount has seemingly failed without an error? Very unusual.

**Comment by mheon** [comment]
Also, it seems like you do have a volume at `/var/lib/containers`, but I'm unclear as to what is backing that volume - is it a bind mount from the host, or is it handled differently?

**Comment by csantanapr** [comment]
Hi @mheon take a look at the Pod Spec we are using an emptyDir
```
volumes:
      - name: varlibcontainers
        emptyDir: {}
```
This is usually what we do when running `buildah` inside OpenShift with Tekton, is the same way the tekton task for buildah uses in the ClusterTask that ships with Add-on OpenShift Pipelines.

**Comment by csantanapr** [comment]
We want to use empty dir as this is for tekton task, not persistent

**Comment by rhatdan** [comment]
It is much easier to use buildah inside of a container image then it is to use podman. Have you looked at doing this with Buildah?

**Comment by csantanapr** [comment]
Hi @rhatdan So glad to hear this from you ❤️ 
> It is much easier to use buildah inside of a container image then it is to use podman. Have you looked at doing this with Buildah?

That was my answer when @seansund show me the blocker today we are building enterprise pipelines using openshift pipelines and when it comes to deal with images in tekton we use buildah to build and skope to release a tag version to external registry. 

The problem is opm only supports docker and podman and all the docs and CI testing they have they don’t use opm inside a container to be use in a cicd flow (ie tekton, github-actions), they assume it’s used in a VM or desktop that has docker desktop or podman 

We are block and we want to discuss it with both teams opm and podman to talk what’s the best architecture and practice to get opm working in cicd tekton specially on OpenShift pipelines

I’m not an expert on overlay file systems so on that part I’m looking for guidance from RedHat from both teams. 

Our work is not just one task, but a full pipeline that makes customer writing operators just git push and the series of pipelines take over the orchestration including the final publish of a custom catalog 

Thank you in advance

**Comment by rhatdan** [comment]
We should setup a design meeting to understand exactly what you want to do and then we could work on a solution.  Next week is bad because of Thanksgiving, but the week after would work.

**Comment by seansund** [comment]
Unfortunately, I'm not sure we have an option to use buildah here... We are using the `opm` cli to create an Operator catalog image. The `opm` cli uses podman (or docker) internally to interact with the container images and doesn't give an option for buildah.

Here's the repo for the opm tool - https://github.com/operator-framework/operator-registry
...and here's the documentation for the operator-sdk - https://sdk.operatorframework.io/docs/olm-integration/quickstart-bundle/

The ultimate goal is to be able to run through the entire operator build process in a Tekton pipeline in-cluster.

**Comment by csantanapr** [comment]
> We should setup a design meeting to understand exactly what you want to do and then we could work on a solution. Next week is bad because of Thanksgiving, but the week after would work.

Hi @rhatdan how do we go about setting up that design meeting?

**Comment by chris-short** [comment]
@rhatdan @fatherlinux Can you invite @christianh814 and I as optional to this meeting, please?

**Comment by csantanapr** [comment]
I opened an issue in opm repo to see who from that team would need to get involved to get opm working inside  a container https://github.com/operator-framework/operator-registry/issues/529

**Comment by csantanapr** [comment]
The Dockerile for the image that includes both `podman` and `opm` is here https://github.com/ibm-garage-cloud/image-operator-sdk/blob/main/Dockerfile

**Comment by usrbinkat** [comment]
> Unfortunately, I'm not sure we have an option to use buildah here... We are using the `opm` cli to create an Operator catalog image. The `opm` cli uses podman (or docker) internally to interact with the container images and doesn't give an option for buildah.
> 

Tacking onto this line of thinking, when `opm index prune` cli calls podman to locally start up the `registry.redhat.io/redhat/redhat-operator-index:v4.6` image for example, it starts the api so opm can grpcurl the packages.

being able to point OPM at a specific image and it do all that is needed with local podman commands is a valuable work flow but predominantly useful only for development and niche fringe cases.

Alternate path:
`opm` should query publicly available api endpoints by default instead of starting up the image locally where possible and unless passed a flag stating to perform actions locally.

In the scenario where opm can reach a public endpoint for package lists such as `https://quay.io/cnr/api/v1/packages` then opm in a container pipeline could handle the rest of it's actions with buildah and eliminate the need to call podman or docker directly and meeting the needs of most use cases.

Am I off base in this train of thought?

@christianh814

**Comment by rhatdan** [comment]
We have a lot of bugs/issues asking about Podman in a container.  We are working on a blog/paper to describe the best practices on running podman in different kinds of containers, and consolidating all issues looking at podman in a container into a single issue.
https://github.com/containers/podman/issues/9015
