### ISSUE TITLE
Rest API - missing created attribute in images list for reproducible containers

### ISSUE THREAD

**Issue by psakar** [containers/podman#8418]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Json generated for image created as reproducible ( thus has created attribute equal to 0 Unix time (January 1, 1970 UTC)) by endpoint /images/json does not contain created attribute with value 0.

**Steps to reproduce the issue:**

1. pull any image with created date time January 1, 1970 UTC (eg. generated by JIB)

2. retrive image list - eg. http://localhost:8880/images/json given podman rest service is running on localhost port 8880

3. find record for the image

**Describe the results you received:**
image json is missing created attribute

**Describe the results you expected:**
immage json contains created attribute with value 0

**Additional information you deem important (e.g. issue happens only occasionally):**

Caused by using the int64 type of field Created in pkg/domain/entities/images.go combined with omitempty - thus if field is 0 it is omitted in the generated json.
```
Created     int64             `json:",omitempty"`
```
One way to solve this is to use an int64 pointer

**Output of `podman version`:**

```
podman version 2.2.0-rc1
```

**Comment by psakar** [comment]
Relates to https://github.com/containers/podman/issues/7927

**Comment by zhangguanzhang** [comment]
could you provide an image which created date time January 1, 1970 UTC?

**Comment by psakar** [comment]
I can not provide image as the project I'm working on is not public. 
I can provide how to create one and import it to your local repo
```
git clone https://github.com/GoogleContainerTools/jib.git
cd jib/examples/helloworld/
mvn jib:buildTar -Djib.to.image=jib-test
podman load --input target/jib-image.tar
```
To see json returned by podman rest api
```
podman --log-level=debug system service -t 0 tcp:localhost:8880 2>&1>/tmp/podman-rest.log &
curl http://localhost:8880/images/json | jq '.[] | select (.RepoTags==["localhost/jib-test:latest"])'
```

**Comment by psakar** [comment]
BTW it seems to me that the easiest solution is to remove omitempty from https://github.com/containers/podman/blob/b898f91/pkg/domain/entities/images.go#L57
given that Created seems to be mandatory attribute
