### ISSUE TITLE
podman-2.2.0-rc1: "Error: could not get either XDG_CONFIG_HOME or HOME"

### ISSUE THREAD

**Issue by srcshelton** [containers/podman#8434]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I've just updated from a (heavily patched) `podman-2.1.1` to `podman-2.2.0-rc1`, and now on attempting to run a container I've getting the message:

```
Error: could not get either XDG_CONFIG_HOME or HOME
```

In this case, the container is being invoked from from an OpenRC init script, so may be subject to a restricted set of environment variables.

Should a variant of HOME not being accessible be an error, though, or simply a warning?  I recall that overrides to the system configuration for certain elements could be placed in per-user dot-files, but should their absence prevent podman from launching the container at all?

(If it makes a difference, this is a system not running `systemd`)

**Output of `podman version`:**

```
Version:      2.2.0-rc1
API Version:  2.1.0
Go Version:   go1.15.5
Git Commit:   02843f881f9271440e7eaad8db231ddf20e33e51
Built:        Thu Nov 19 22:59:08 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 35a2fa83022e56e18af7e6a865ba5d7165fa2a4a'
  cpus: 8
  distribution:
    distribution: gentoo
    version: unknown
  eventLogger: file
  hostname: dellr330
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.9.6-gentoo
  linkmode: dynamic
  memFree: 1757749248
  memTotal: 33392836608
  ociRuntime:
    name: crun
    package: Unknown
    path: /usr/bin/crun
    version: |-
      crun version 0.15.1
      commit: eb0145e5ad4d8207e84a327248af76663d4e50dd
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 25669844992
  swapTotal: 25769787392
  uptime: 222h 16m 40.57s (Approximately 9.25 days)
registries:
  search:
  - docker.io
  - docker.pkg.github.com
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 30
    paused: 0
    running: 25
    stopped: 5
  graphDriverName: overlay
  graphOptions:
    overlay.ignore_chown_errors: "false"
  graphRoot: /space/podman/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 386
  runRoot: /space/podman/run
  volumePath: /space/podman/volumes
version:
  APIVersion: 2.1.0
  Built: 1605826748
  BuiltTime: Thu Nov 19 22:59:08 2020
  GitCommit: 02843f881f9271440e7eaad8db231ddf20e33e51
  GoVersion: go1.15.5
  OsArch: linux/amd64
  Version: 2.2.0-rc1

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Comment by mheon** [comment]
We believe this is fixed now - hoping to get an RC2 out by end of day with the fix included.

**Comment by srcshelton** [comment]
... any luck with the RC2?  This one's a little inconvenient, and if there's another RC soon I'd prefer not to have to make a temporary fix to numerous scripts...

Alternatively, do you know the commit which fixed this issue?  Patching RC1 would also be fine.  I had a quick scan through, but couldn't see the change which should fix this.

**Comment by srcshelton** [comment]
Found it!

**Comment by motiejus** [comment]
Looks like rc1 is still in kubic repositories:
```
$ apt-cache policy podman
podman:
  Installed: 2.2.0~0.1+nmu1
  Candidate: 2.2.0~0.1+nmu1
  Version table:
 *** 2.2.0~0.1+nmu1 500
        500 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/Debian_10  Packages
        100 /var/lib/dpkg/status
```

Looking forward to the rc2 there.

**Comment by rhatdan** [comment]
RC2 should be released this week, but the Holiday might cause issues.

**Comment by motiejus** [comment]
> RC2 should be released this week, but the Holiday might cause issues.

Thanks. In the meanwhile, is there a way to get podman 2.1 deb, equivalent to what's https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/Debian_10/, but for 2.1?

Podman 2.0.6 (what's now available in official debian repos) is a bit too big of a jump for me by now.

**Comment by mheon** [comment]
There is a non testing version of that repo that tracks the latest stable
release. It's linked in our install page.

**Comment by mheon** [comment]
Install page is located at https://podman.io/getting-started/installation

Locate your distro and there should be instructions to install the stable
OBS repo.

**Comment by lsm5** [comment]
> > RC2 should be released this week, but the Holiday might cause issues.
> 
> Thanks. In the meanwhile, is there a way to get podman 2.1 deb, equivalent to what's https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/Debian_10/, but for 2.1?
> 
> Podman 2.0.6 (what's now available in official debian repos) is a bit too big of a jump for me by now.

@motiejus you can get the debianized tarball podman_2.1.1~2.tar.gz from https://build.opensuse.org/package/show/devel:kubic:libcontainers:testing/podman?rev=243 and run `dpkg-buildpackage -us -uc` in it to generate the 2.1.1 packages.

**Comment by motiejus** [comment]
> @motiejus you can get the debianized tarball podman_2.1.1~2.tar.gz from https://build.opensuse.org/package/show/devel:kubic:libcontainers:testing/podman?rev=243 and run dpkg-buildpackage -us -uc in it to generate the 2.1.1 packages.

Thanks a lot, that worked.

**Comment by rhatdan** [comment]
Since this is fixed in master, I am closing.  Hope to have fix out this week.
