### ISSUE TITLE
Feature: Static IP with "podman play kube --network=<network> --ip=<IP>"

### ISSUE THREAD

**Issue by hoonetorg** [containers/podman#8442]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

It would be useful if ```podman play kube``` would support using static IP for the generated pod.
The usecase for me is a dhcphelper pod which uses the host network wants to talk to a app pod, which has dnsmasq running in it. Forwarding DHCP requests from dhcphelper pod to app pod with dnsmasq container is easy by using a static IP.

**Steps to reproduce the issue:**

1. ```podman play kube app.yaml --network=app --ip=192.168.2.253```

**Describe the results you received:**

```Error: unknown flag: --ip```

**Describe the results you expected:**

```
Pod:
553d4b...
Containers:
xda643...
381d9f...
y1c49f...
43459c...
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.14
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 2
  distribution:
    distribution: debian
    version: "10"
  eventLogger: journald
  hostname: youdontneedtoknow
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.19.0-12-amd64
  linkmode: dynamic
  memFree: 877731840
  memTotal: 4138450944
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0~rc6+dfsg1
      commit: 1.0.0~rc6+dfsg1-3
      spec: 1.0.1
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 188h 3m 58.18s (Approximately 7.83 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 7
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 258
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.14
  OsArch: linux/amd64
  Version: 2.1.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 2.1.1~2 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

virtual

**Comment by rhatdan** [comment]
Interested in opening a PR to add this functionality?

**Comment by hoonetorg** [comment]
@rhatdan: Oh i think my knowledge about go and the code is not good enough for it :)

**Comment by rhatdan** [comment]
Ok no problem, I just thought I would ask.

**Comment by mier85** [comment]
@rhatdan i would like to take this as my "first issue"

**Comment by rhatdan** [comment]
Thanks @mier85, you got it.

**Comment by mier85** [comment]
@hoonetorg as you requested this feature, there is some question about it here: https://github.com/containers/podman/pull/8617#issuecomment-756040201

**Comment by rhatdan** [comment]
@mier85 What is the scoop on this one?

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by rhatdan** [comment]
@Luap99 any chance you could look at this?

**Comment by Luap99** [comment]
Sure

**Comment by Luap99** [comment]
PR #10043
