### ISSUE TITLE
[RFE] podman kill --cidfile

### ISSUE THREAD

**Issue by TerraTech** [containers/podman#8443]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

podman version: 2.1.1
Ubuntu: 20.04 LTS server

I would like to request `podman kill` be outfitted with reading container id via `--cidfile`

This is useful in Systemd services for `ExecReload`, e.g.
`ExecReload=/usr/bin/podman kill --signal HUP --cidfile %t/%n.ctr-id`

Actually, I was sort of surprised this didn't already exist, like it is for `run` and `stop`.

Thank you for your consideration.

**Comment by rhatdan** [comment]
Interested in opening a PR to add this functionality?

**Comment by TerraTech** [comment]
Sure, doesn't seem like it would be difficult to implement along with being an itch that really needs to be scratched.  ;)

**Comment by rhatdan** [comment]
Thanks, Looking forward to seeing it.

**Comment by baude** [comment]
@TerraTech i hope you dont mind that i made a pr for this ...
