### ISSUE TITLE
System prune does not support filter option ("Error: unknown flag"). 

### ISSUE THREAD

**Issue by svdHero** [containers/podman#8453]
In Docker I can do this:
```
docker system prune -a --force --filter "until=48h"
```
which I use as part of a systemd timer on our CI server in order to clean up disk space.

However, when I try this
```
podman system prune -a --force --filter "until=48h"
```
I get an error saying `Error: unknown flag: --filter`.

The filter option was added to `image prune`  and `container prune` in #4512 and #4596, respectively.
It should be added to `system prune`, too.

**Comment by rhatdan** [comment]
@svdHero Interested in opening a PR to fix this?

**Comment by svdHero** [comment]
@rhatdan I'd love to if it wasn't in go. ;-) Unfortunately I have no experience and go, and right now not the time to learn it.
However, if nobody else gives it a shot, I might be tempted to pick it up. Is there any contribution how-to for dummies and noobs?

**Comment by rhatdan** [comment]
The best we have is https://github.com/containers/podman/blob/master/CONTRIBUTING.md

**Comment by endasexton** [comment]
I've been meaning to get into Go and would love to give this a "go".

**Comment by bblenard** [comment]
I started poking at this. If someone else more capable wants to pick it up feel free but I'll continue to mess with it and maybe try to submit a PR

```
[ 10:23PM ]  [ b@void:~/Documents/podman(master✗) ]
 $ podman volume create --label test=baron myvol            
myvol
[ 10:23PM ]  [ b@void:~/Documents/podman(master✗) ]
 $ bin/podman volume list                                       
DRIVER      VOLUME NAME
local       316371a165f0ead9f206b0ee32910657dff74dbf733d89bcb43a799718716bc8
local       myvol
local       myvol3
[ 10:24PM ]  [ b@void:~/Documents/podman(master✗) ]
 $ bin/podman volume inspect myvol
[
    {
        "Name": "myvol",
        "Driver": "local",
        "Mountpoint": "/home/b/.local/share/containers/storage/volumes/myvol/_data",
        "CreatedAt": "2020-12-08T22:23:55.861451993-06:00",
        "Labels": {
            "test": "baron"
        },
        "Scope": "local",
        "Options": {},
        "UID": 0,
        "GID": 0,
        "Anonymous": false
    }
]
[ 10:24PM ]  [ b@void:~/Documents/podman(master✗) ]
 $ bin/podman system prune --volumes --filter "label=test=baron"

WARNING! This will remove:
        - all stopped containers
        - all volumes not used by at least one container
        - all stopped pods
        - all dangling images
        - all build cache
Are you sure you want to continue? [y/N] y
Deleted Pods
Deleted Containers
Deleted Volumes
myvol
Deleted Images
```

**Comment by rhatdan** [comment]
PR Merged.
