### ISSUE TITLE
Strange effect of the podman run --pod new:podname on the Container status and port publishing. No Documentation

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/podman#8462]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

kind bug BUG

**Description**

When podman run is used with --pod new:podname and port publishing -p 8080:80 
but timing is wrong! It takes several seconds for heavy Nginx to start. But flyweight infra container starts instantly! When I test Nginx home page using the browser I get several times only constant string and after a few seconds, everything is settled.
**Steps to reproduce the issue:**

1. podman run -dt --pod new:nginx2 -p 8080:80 nginx
both nginx and infra containers get port mapping 0.0.0.0:8080->80/tcp

**Describe the results you received:**

Constant string response after the command is executed and after several seconds Nginx responses as expected
**Describe the results you expected:**
It should work like podman pod create xxx, podman run --pod xxx, podman pod start, ... 
nginx
**Additional information you deem important (e.g. issue happens only occasionally):**
At the end Nginx is settled and ports are exposed
podman port -a
44756998367d    80/tcp -> 0.0.0.0:8080 < nginx
9f45763221d8    80/tcp -> 0.0.0.0:8080 < infra
**Output of `podman version`:**

```
podman version
Version:      2.1.1
API Version:  2.0.0
```

**Output of `podman info --debug`:**

```
podman info --debug
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 4
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: MSI
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.19.128-microsoft-standard
.
.
.
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
apt list podman
Listing... Done
podman/now 2.1.1~2 amd64 [installed,local]
```
Still old?
**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**
Yes, it is not documented

**Ubuntu-20.04 WSL distro:**

It can be an adventure to know how such heavyweight containers with slow async start and no own health check started
Documentation on healthcheck is empty. Is it the same as for [Docker --healthcheck option?] or [Kubernetes Pod lifecycle?](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/) 
 (https://docs.docker.com/engine/reference/run/#healthcheck). Is it on the Pod or Container level? What is the default? How it affects status?

**Comment by Luap99** [comment]
`podman run -dt --pod new:nginx2 -p 8080:80 nginx` shoudle be the same as:
```
$ podman pod create --name nginx2 -p 8080:80
$ podman run -dt --pod nginx2 nginx
```

**Comment by Luap99** [comment]
If you are in a pod you share the same network interface so the port mapping is applied to all container in the pod.

**Comment by rhatdan** [comment]
I don't believe this is a Podman bug. Podman is just setting up the namespaces and launching the container.  I believe this is most likely something strange going on with WSL2.

I am not sure what Documentation you would like to had added?

**Comment by PavelSosin-320** [comment]
How to use health check command what it does, how to configure health check, how it affects Container and Pod status. Something more than a blank page.
For such things like Nginx it can be not so complex:
**podman exec 9f45763221d8 curl http://localhost:80**
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   612  100   612    0     0   597k      0 --:--:-- --:--:-- --:--:--  597k
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
and I know that Nginx is alive and the corresponding container 9f45763221d8 is not only up and running but also healthy.

**Comment by PavelSosin-320** [comment]
@Luap99 it's true, all containers can share the same locahost but it doesn't solve the problem: on the same Pod it can take 0.5 sec to start flyweight containers and 5 sec to start heavyweight containers like Nginx, Tomcat. Nginx starts to respond minutes later after Pod is shown as running and Nginx container appears in Podman PS.
Some containers can fail to start due to allowed startup time expiration. Only healthy containers are accounted. 
Docker and Kubernetes solve this problem differently: Docker counts healthy containers in state reconciliation. Kubernetes counts healthy Pods. In both cases, the health check definition, healthcheck mechanism, healthcheck implementation in Containers, and outcomes of healthcheck failure are documented and discussed in the smallest details. 
I can't expect the correct response from Nginx before its Pod/Container hasn't pass healthcheck, i.e "healthy". I can't find documentation about Podman healthcheck command and Podman rejects this command in any form although I do everything as a root user.

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by PavelSosin-320** [comment]
I tested the following use-case using analogy with docker:
podman pod create --name nginx3 --publish 8080:80
podman run -dt --pod nginx3 --health-cmd='curl localhost:80' --health-interval=5s --health-start-period=10s nginx;latest
podman ps
CONTAINER ID  IMAGE                           COMMAND               CREATED        STATUS            PORTS                 NAMES
17cfa82ffcfd  docker.io/library/nginx:latest  nginx -g daemon o...  2 minutes ago  Up 2 minutes ago  0.0.0.0:8080->80/tcp  admiring_booth
podman healthcheck run 17cfa82ffcfd
**healthy**
So, it possibly works OK but it is not documented in any way. I know, the waiting period for Documentation developers is long. Maybe, it is possible to accelerate anyway?

**Comment by baude** [comment]
@rhatdan what am i even looking at? i see multiple problems being reported ... one of which is that containers in wsl may or may not be slow to start.  are you wanting me to check that?

**Comment by PavelSosin-320** [comment]
@baude I mean that good intention to create and start single container pod using single command **Podman run --pod new:** resulted in chaos due to incomplete design. In Docker the command **docker run** means create and start the container. after the command has been finished the container is created and started (container id is printed!) and is ready to serve the user's requests. In Podman it is impossible to interpret the result. When I tried to use "Nginx Pod" The HTTP request failed because Nginx is slow to start and there is no indication of its actual status. I expect that the single container pod is created and started and I can use it.
I also defined the **health check** for my Nginx container but it was ignored completely. Testing using the browser returned random results. It leaves me completely confused. 
Then, I used Podman healthcheck run command to check Nginx readiness, it printed healthy, Browser and Curl tests returned positive result but **Podman pod ls** and **Podman ps** command shows the container in undocumented state UP instead of running or healthy. The pod had CREATED status.

**Comment by rhatdan** [comment]
@PavelSosin-320 Lets start by seeing if podman run ... and docker run can do the same thing.  We can look at pods after we make sure regular containers work.

**Comment by PavelSosin-320** [comment]
Related: Podman events outputs all container events together: regular and infra. The is no filter. I can hardly imagine how a client can use infra container events. Say, promise-based asynchronous client which creates new promise for every Podman operation - which promise is resolved by infra container event and then what????? Regardless of infra image.

**Comment by PavelSosin-320** [comment]
The documentation in [Debian manpages ](https://manpages.debian.org/unstable/podman/podman-events.1.en.html) containes much more and much more consistent information than the "official" Podman documentation Man pages

**Comment by rhatdan** [comment]
@PavelSosin-320 interested in opening a PR to make the main project match the debian man pages?

**Comment by PavelSosin-320** [comment]
Yes, I think that is convenient when only one "Official documentation"
exists to reference it and create tests following this documentation.
Like in my former company SAP: documentation snippets <--> test fragments.

**Comment by Luap99** [comment]
@PavelSosin-320 I can't see any differences between the page you linked and our man page: https://github.com/containers/podman/blob/master/docs/source/markdown/podman-events.1.md

**Comment by mheon** [comment]
Concur - I would be very surprised if Debian is patching our manpages downstream (and if they are, I'd be quite happy to merge their changes if they upstream them).

**Comment by PavelSosin-320** [comment]
Oh, Sorry, the difference is mainly in formatting. On my screen, MD version
is cut to  2/3 of the original size with long scrolling, when the Debian
HTML version is stretched to the full-17"  laptop screen size. From the 1st
example, I concluded by mistake that only Container events are emitted by
the default.

**Comment by PavelSosin-320** [comment]
Sorry again! This is not only a formatting issue. This is the real bug:
Podman Pod start, stop, ls by the default, without the --no-trunc use only
short Pod ID. The Podman events command with type=pod show the long Pod ID
with meaningless (image=, name=devcontainerShare)
It looks fine visually. The event observer at the client-side has no chance
to match the created Pod with its lifecycle events only because the
defaults of Podman pod commands and Podman events are different. Podman
events command uses --no-trunc by the default?
