### ISSUE TITLE
How to use a directory, which is shared read only with other users on the host using group permissions inside a rootless container by a non-root user, who can read and write the directory, without modifying the permissions of directory on the host?

### ISSUE THREAD

**Issue by topas-rec** [containers/podman#8471]
/kind unknown

(Tell me what this is? Cannot say bug - cannot say feature, yet. I suggest "help wanted")

**Description**
A lot of explanation follows. Questions are marked bold.
A short summary is the title.

Assuming there is a directory which looks like this on the host:
```
tobias@tobias-pc:~$ ls -l /mnt/
total 20
drwxrwxr-x 1 root tobiasdata 20480 Nov 23 20:40 DATA
tobias@tobias-pc:~$ ls -ln /mnt/
total 20
drwxrwxr-x 1 0 1003 20480 Nov 23 20:40 DATA
```

(This one is an NTFS drive mounted using `ntfs-3g`.
`root` is the owner since no other user was mentioned as owner in `fstab` (works - don't care). `tobiasdata` is the group that owns this directory. This was set in fstab.
The NTFS mount is not really relevant here, but I didn't want to leave it out completely)

Group `tobiasdata` is set to grant user `tobias` write access to the `DATA` directory. I want world to have read access to that directory, because there is another user on the host that reads from this directory.
_I currently don't know how to achieve that in a better way. Maybe here is the cause for my misunderstandings. In that case I'm open to discuss it._

I want to directly write from nextcloud inside the container into that `DATA` directory - using podman.
*Why? I love the rootless idea of podman, the `-l` option :-), the auto-update function and the backup (to archive) option.*

How can I get that done in podman together with for example nextcloud which uses www-data user instead of root I asked myself. (And my favourite search engine and github issues)

I found

- this article: [Running rootless Podman as a non-root user | Enable Sysadmin](https://www.redhat.com/sysadmin/rootless-podman-makes-sense)
  
  - This should make the directory writable inside the container - yes, but the initial permissions of the folder outside of the container will be changed, too. This seems not ideal for me. I can try to just make the folder owned by user `www-data` (not owned by the group `www-data`) inside the container. Then the user `www-data`can write the directory inside the container and outside the container the group permission manages it on the host. (Seems easy and should work - tested - `operation not permitted`. What did I do wrong?)
    
  - I don't like the fact that a change in ownership inside the container changes the ownership outside the container. **Is there a better way?**
    
- podman mapping options like `--gidmap` and the namespace mapping files `subgid`
  
  - I played with both. This really never worked. I was unable to get this option working the way I expected it (Map a group from host to a group inside the container so that users in the mapped group inside the container can write to the `DATA`directory)

**Can someone tell me**

- **if my scenario (see title and explanation) is possible?** (And optional: Is it valid at all? Directory sharing between users on the host?)
  
- **how that can be done the `podman` way if it is a valid setup?**  

I currently have this setup working using `docker` and `root` containers. The `DATA` directory is added to the container as a host volume. A group `tobiasdata` is added inside the container with the same id that the group with the same name has on the host (1003). The user `www-data` inside the container is then added to that group and can write to that directory (docker feature).

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.14
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 4
  distribution:
    distribution: debian
    version: "10"
  eventLogger: journald
  hostname: tobias-pc
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.19.0-6-amd64
  linkmode: dynamic
  memFree: 563970048
  memTotal: 8315002880
  ociRuntime:
    name: runc
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
      spec: 1.0.1-dev
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.4
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 8387555328
  swapTotal: 8387555328
  uptime: 13m 24.62s
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/tobias/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.4.1
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.4.1
        using FUSE kernel interface version 7.27
  graphRoot: /home/tobias/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /home/tobias/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.14
  OsArch: linux/amd64
  Version: 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 2.1.1~2 amd64 [installed]
podman/unknown 2.1.1~2 arm64
podman/unknown 2.1.1~2 armhf
podman/unknown 2.1.1~2 ppc64el
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by topas-rec** [comment]
>Running rootless Podman as a non-root user | Enable Sysadmin [...] (Seems easy and should work - tested - operation not permitted. What did I do wrong?)

This might be an NTFS mount permission problem. I'll check that.

**Comment by rhatdan** [comment]
If you can access a directory via non root account then can't reach it via a podman container with it volume mounted in, then I would guess it is one of two problems.
1. SELinux blocking access.  You can test this theory by disabling SELinux for the container --security-opt label=disabled.
2.  If your access to the files is based on group access, this group access will not be leaked into the container.  If you are using crun as your container runtime, then you can set a special annnotation
--annotation  run.oci.keep_original_groups=1.

```
man podman run
...
       Note:  if  the  user only has access rights via a group, accessing the
       device from inside a rootless container will fail. The crun(1) runtime
       offers  a  workaround  for  this  by  adding  the  option --annotation
       run.oci.keep_original_groups=1.

```

**Comment by topas-rec** [comment]
> > Running rootless Podman as a non-root user | Enable Sysadmin [...] (Seems easy and should work - tested - operation not permitted. What did I do wrong?)
> 
> This might be an NTFS mount permission problem. I'll check that.

Seems to be an "NTFS fstab root" permission problem - I don't want to follow it because there is a general problem with it before that one comes in:

So back to article [Running rootless Podman as a non-root user | Enable Sysadmin](https://www.redhat.com/sysadmin/rootless-podman-makes-sense): After owning the volume by a container user (postgres in that case) and getting the directory to be owned by an unknown user and group on the host:
```
ls -ld $PWD/html
drwxrwxr-x. 2 100025 100025 4096 Sep 13 07:14 /home/dwalsh/html
```
that folder on the host is not accessible by the host user anymore (`Permission denied
`). Did I miss something here (My Debian uses AppArmour instead of SELinux - I tested the `:Z` option with that volume, too without success)
Was this article meant only to place data on the host from inside the container without sharing the data with the host user? That would be my intention of linking a volume to a location from container to host.

**Comment by topas-rec** [comment]
> If you can access a directory via non root account then can't reach it via a podman container with it volume mounted in, then I would guess it is one of two problems.
> 
>     1. SELinux blocking access.  You can test this theory by disabling SELinux for the container --security-opt label=disabled.
> 
>     2. If your access to the files is based on group access, this group access will not be leaked into the container.  If you are using crun as your container runtime, then you can set a special annnotation
>        --annotation  run.oci.keep_original_groups=1.
> 
> 
> ```
> man podman run
> ...
>        Note:  if  the  user only has access rights via a group, accessing the
>        device from inside a rootless container will fail. The crun(1) runtime
>        offers  a  workaround  for  this  by  adding  the  option --annotation
>        run.oci.keep_original_groups=1.
> ```

Thanks for that.
1. I don't use SELinux but AppAramour.
2. I look into this to understand a bit more about it and come back to that if there is no simpler solution

**Comment by topas-rec** [comment]
As mentioned in the last comment I'm able to use the mounted volume in a rootless container by the non-root user `www-data` inside the container. (BTW why? That volume has `root:root` permission inside the container)
I created a file in that volume. Also here the files created by a non-root user inside the rootless container remain without write permission to the host user. (Tough deletion and renaming are allowed)
Is this intended?
Can this be changed?
I would like to share the data between container and host.

**Comment by Luap99** [comment]
I think you are looking for the `--userns keep-id` option for podman run/create

**Comment by topas-rec** [comment]
> As mentioned in the last comment I'm able to use the mounted volume in a rootless container by the non-root user `www-data` inside the container. (**edit:** ~BTW why? That volume has `root:root` permission inside the container~ world writable most likely **end edit**)
> I created a file in that volume. Also here the files created by a non-root user inside the rootless container remain without write permission to the host user. (Tough deletion and renaming are allowed)
> Is this intended?
> Can this be changed?
> I would like to share the data between container and host.

This issue is mentioned [here](https://www.jujens.eu/posts/en/2017/Jul/02/docker-userns-remap/), with the only difference that docker is used.

Can be solved by mapping the non-root user inside container to the user who wants to use the files on host by using `--uidmap`.
(Knowing issue https://github.com/containers/podman/issues/6123 saves hours)

```
tobias@tobias-pc:~$ podman run --uidmap=0:1:33 --uidmap=33:0:1 --uidmap=34:34:65502 -dt --volume=/home/tobias/podmanMount/:/container/volume --restart=always -e NEXTCLOUD_ADMIN_USER="XXX" -e NEXTCLOUD_ADMIN_password="XXX" -p 8084:80/tcp nextcloud
08c754ad3673f4e170dd20038e7e65b87d81f603c6f6b9c5148b7fa59400e86c
tobias@tobias-pc:~$ podman exec -l -i -u www-data touch /container/volume/test.md
tobias@tobias-pc:~$ ls -l ~/podmanMount/
total 0
-rw-r--r-- 1 tobias tobias 0 Nov 26 19:44 test.md

```

**Comment by topas-rec** [comment]
The NTFS drive can be written by non-root user in rootless container when mounted inside my home folder instead of `/mnt`.
I'll move to mounting that drive in my home folder - then giving access to the other users on the system using `bindfs`.

**Comment by topas-rec** [comment]
> I think you are looking for the `--userns keep-id` option for podman run/create

Thanks @Luap99 
That would give me

**Comment by crcox** [comment]
Sorry to revive an old thread, but I have a related question. Am trying to set up a server environment where a number of users, identified by group membership, might run containers without root permission on data that they have access to based on their group membership.

I have the images installed in a way that they are shared among non-root users following [this blog post](https://www.redhat.com/sysadmin/image-stores-podman). This is confirmed working, unless a user tries to map a volume containing data that they do not directly own.

I do not understand how to use the `--userns keep-id` option. Adding that to the command the user runs does not fix the issue, and that doesn't surprise me---it does not seem like a non-root user should be able to control how namespaces are mapped into the container. This is the command the non-root user it trying and failing to run.

    podman run --rm -it -v /path/to/shared/data:/base:Z shared/image /base

Do I, as root, need to create the container from the image in advance and define the namespace mapping rules? And once doing that, will that change how the non-root user engages with the container?

**Comment by rhatdan** [comment]
The shared directory should be chowned manually one time.

chcon -t container_file_t -r /path/to/shared/data

Now the containers can share the content. Now you also need to make the content owned by a shared group between all of the users.  Say the data group and them chown root:data -r /pat/to/share/data.  Now each user has to be added to the `data` group in /etc/groups.  Finally the containers need to be run with crun and use the 
`--annotation run.oci.keep_original_groups=1` flag. ( I hope to make this simpler in the near future.) 

https://github.com/containers/podman/pull/9495
