### ISSUE TITLE
podman 2.0.5 cannot create cgroup in /sys/fs/cgroup/systemd/

### ISSUE THREAD

**Issue by coldbloodx** [containers/podman#8480]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
podman 2.0.5 cannot create cgroup in /sys/fs/cgroup/systemd/

**Steps to reproduce the issue:**

1. install podman 2.0.5 
bash-4.4$ podman info
host:
  arch: amd64
  buildahVersion: 1.15.1
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.17-1.module+el8.2.1+6771+3533eb4c.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.17, commit: 3c703d9f178a3a53966e1d5c03d0275ea6cb36a0'
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "8.2"
  eventLogger: file
  hostname: lsf1x125
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 10007
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 34004
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-193.28.1.el8_2.x86_64
  linkmode: dynamic
  memFree: 7135715328
  memTotal: 8189206528
  ociRuntime:
    name: runc
    package: runc-1.0.0-66.rc10.module+el8.2.1+6465+1a51e8b6.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/user/34004/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.0.1-1.module+el8.2.1+6595+03641d72.x86_64
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.3.0
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 5h 52m 44.52s (Approximately 0.21 days)
registries:
  search:
  - docker.io
store:
  configFile: /home/jxgao/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.0.0-2.module+el8.2.1+6465+1a51e8b6.x86_64
      Version: |-
        fuse-overlayfs: version 1.0.0
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /podmanfs/jxgao/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/user/34004
  volumePath: /podmanfs/jxgao/volumes
version:
  APIVersion: 1
  Built: 1600877882
  BuiltTime: Wed Sep 23 12:18:02 2020
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.0.5

2. enable user linger
bash-4.4$ loginctl user-status jxgao
jxgao (34004)
           Since: Wed 2020-11-25 04:29:36 EST; 5h 47min ago
           State: lingering
          Linger: yes
            Unit: user-34004.slice
                  `-user@34004.service
                    |-dbus.service
                    | `-1516 /usr/bin/dbus-daemon --session --address=systemd: --nofork --nopidfile --systemd-act>
                    |-init.scope
                    | |-1145 /usr/lib/systemd/systemd --user
                    | `-1173 (sd-pam)
                    `-user.slice
                      `-podman-pause.scope
                        `-1506 /usr/bin/podman
3. run a podman container
bash-4.4$ podman run -d centos sleep 1000
574a9178099abc45e4cb9227601edd62da99745356e03682cc80afdea6dce752

bash-4.4$ podman ps
CONTAINER ID  IMAGE                            COMMAND     CREATED        STATUS            PORTS   NAMES
574a9178099a  docker.io/library/centos:latest  sleep 1000  7 minutes ago  Up 7 minutes ago          tender_roentgen

bash-4.4$ find /sys/fs/cgroup/systemd/ -iname '574a9178099a*'
bash-4.4$
bash-4.4$ find /sys/fs/cgroup/ -iname '574a9178099abc45e4cb9227601edd62da99745356e03682cc80afdea6dce752'
bash-4.4$
bash-4.4$ podman version
Version:      2.0.5
API Version:  1
Go Version:   go1.14.7
Built:        Wed Sep 23 12:18:02 2020
OS/Arch:      linux/amd64

**Describe the results you received:**
podman does not create cgroup in /sys/fs/cgroup for container.

**Describe the results you expected:**
in podman 1.9.3 and 1.6.4 podman will create cgroup for container 
[xianwu@rcn01 ~]$ podman run -d  centos  sleep 12222
19cd03157d7f44ee524f64ac146fac33b16989adc6069ada0626cf695366daa7
[xianwu@rcn01 ~]$ find /sys/fs/cgroup/ -iname 19cd03157d7f44ee524f64ac146fac33b16989adc6069ada0626cf695366daa7
/sys/fs/cgroup/systemd/user.slice/user-33857.slice/user@33857.service/user.slice/podman-3187369.scope/19cd03157d7f44ee524f64ac146fac33b16989adc6069ada0626cf695366daa7
[xianwu@rcn01 ~]$ podman version
Version:            1.9.3
RemoteAPI Version:  1
Go Version:         go1.13.4
OS/Arch:            linux/amd64

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
bash-4.4$ podman version
Version:      2.0.5
API Version:  1
Go Version:   go1.14.7
Built:        Wed Sep 23 12:18:02 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
bash-4.4$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.15.1
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.17-1.module+el8.2.1+6771+3533eb4c.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.17, commit: 3c703d9f178a3a53966e1d5c03d0275ea6cb36a0'
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "8.2"
  eventLogger: file
  hostname: lsf1x125
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 10007
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 34004
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-193.28.1.el8_2.x86_64
  linkmode: dynamic
  memFree: 7131004928
  memTotal: 8189206528
  ociRuntime:
    name: runc
    package: runc-1.0.0-66.rc10.module+el8.2.1+6465+1a51e8b6.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/user/34004/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.0.1-1.module+el8.2.1+6595+03641d72.x86_64
    version: |-
      slirp4netns version 1.0.1
      commit: 6a7b16babc95b6a3056b33fb45b74a6f62262dd4
      libslirp: 4.3.0
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 5h 59m 38.91s (Approximately 0.21 days)
registries:
  search:
  - docker.io
store:
  configFile: /home/jxgao/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.0.0-2.module+el8.2.1+6465+1a51e8b6.x86_64
      Version: |-
        fuse-overlayfs: version 1.0.0
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /podmanfs/jxgao/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/user/34004
  volumePath: /podmanfs/jxgao/volumes
version:
  APIVersion: 1
  Built: 1600877882
  BuiltTime: Wed Sep 23 12:18:02 2020
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.0.5
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
bash-4.4$ rpm -q podman
podman-2.0.5-5.module+el8.3.0+8221+97165c3f.x86_64```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
vmware virtual host

**Comment by mheon** [comment]
I wonder if it's switched to using systemd cgroups. Can you do a `podman inspect` of the container and pastebin the result?

**Comment by coldbloodx** [comment]
Here is the result, please check it.

bash-4.4$ podman run -d centos sleep 20000
3bc14872777de686061f88f78fe8329d6ac09f998ba5765c2df9fea5c4a13314
bash-4.4$ podman inspect 3bc
[
    {
        "Id": "3bc14872777de686061f88f78fe8329d6ac09f998ba5765c2df9fea5c4a13314",
        "Created": "2020-11-25T23:10:25.170685706-05:00",
        "Path": "sleep",
        "Args": [
            "20000"
        ],
        "State": {
            "OciVersion": "1.0.2-dev",
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 39734,
            "ConmonPid": 39722,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-11-25T23:10:25.559178293-05:00",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Healthcheck": {
                "Status": "",
                "FailingStreak": 0,
                "Log": null
            }
        },
        "Image": "0d120b6ccaa8c5e149176798b3501d4dd1885f961922497cd0abef155c869566",
        "ImageName": "docker.io/library/centos:latest",
        "Rootfs": "",
        "Pod": "",
        "ResolvConfPath": "/run/user/34004/overlay-containers/3bc14872777de686061f88f78fe8329d6ac09f998ba5765c2df9fea5c4a13314/userdata/resolv.conf",
        "HostnamePath": "/run/user/34004/overlay-containers/3bc14872777de686061f88f78fe8329d6ac09f998ba5765c2df9fea5c4a13314/userdata/hostname",
        "HostsPath": "/run/user/34004/overlay-containers/3bc14872777de686061f88f78fe8329d6ac09f998ba5765c2df9fea5c4a13314/userdata/hosts",
        "StaticDir": "/podmanfs/jxgao/storage/overlay-containers/3bc14872777de686061f88f78fe8329d6ac09f998ba5765c2df9fea5c4a13314/userdata",
        "OCIConfigPath": "/podmanfs/jxgao/storage/overlay-containers/3bc14872777de686061f88f78fe8329d6ac09f998ba5765c2df9fea5c4a13314/userdata/config.json",
        "OCIRuntime": "runc",
        "LogPath": "/podmanfs/jxgao/storage/overlay-containers/3bc14872777de686061f88f78fe8329d6ac09f998ba5765c2df9fea5c4a13314/userdata/ctr.log",
        "LogTag": "",
        "ConmonPidFile": "/run/user/34004/overlay-containers/3bc14872777de686061f88f78fe8329d6ac09f998ba5765c2df9fea5c4a13314/userdata/conmon.pid",
        "Name": "optimistic_chatelet",
        "RestartCount": 0,
        "Driver": "overlay",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "EffectiveCaps": [
            "CAP_AUDIT_WRITE",
            "CAP_CHOWN",
            "CAP_DAC_OVERRIDE",
            "CAP_FOWNER",
            "CAP_FSETID",
            "CAP_KILL",
            "CAP_MKNOD",
            "CAP_NET_BIND_SERVICE",
            "CAP_NET_RAW",
            "CAP_SETFCAP",
            "CAP_SETGID",
            "CAP_SETPCAP",
            "CAP_SETUID",
            "CAP_SYS_CHROOT"
        ],
        "BoundingCaps": [
            "CAP_AUDIT_WRITE",
            "CAP_CHOWN",
            "CAP_DAC_OVERRIDE",
            "CAP_FOWNER",
            "CAP_FSETID",
            "CAP_KILL",
            "CAP_MKNOD",
            "CAP_NET_BIND_SERVICE",
            "CAP_NET_RAW",
            "CAP_SETFCAP",
            "CAP_SETGID",
            "CAP_SETPCAP",
            "CAP_SETUID",
            "CAP_SYS_CHROOT"
        ],
        "ExecIDs": [],
        "GraphDriver": {
            "Name": "overlay",
            "Data": {
                "LowerDir": "/podmanfs/jxgao/storage/overlay/291f6e44771a7b4399b0c6fb40ab4fe0331ddf76eda11080f052b003d96c7726/diff",
                "MergedDir": "/podmanfs/jxgao/storage/overlay/d3a38a9343208175272c8df2bae74326cfa4ba52d525ecaa6af8b7eeeb4bb273/merged",
                "UpperDir": "/podmanfs/jxgao/storage/overlay/d3a38a9343208175272c8df2bae74326cfa4ba52d525ecaa6af8b7eeeb4bb273/diff",
                "WorkDir": "/podmanfs/jxgao/storage/overlay/d3a38a9343208175272c8df2bae74326cfa4ba52d525ecaa6af8b7eeeb4bb273/work"
            }
        },
        "Mounts": [],
        "Dependencies": [],
        "NetworkSettings": {
            "EndpointID": "",
            "Gateway": "",
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "MacAddress": "",
            "Bridge": "",
            "SandboxID": "",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/run/user/34004/netns/cni-0c18f926-14c6-d9cc-869e-878d93817511"
        },
        "ExitCommand": [
            "/usr/bin/podman",
            "--root",
            "/podmanfs/jxgao/storage",
            "--runroot",
            "/run/user/34004",
            "--log-level",
            "error",
            "--cgroup-manager",
            "cgroupfs",
            "--tmpdir",
            "/tmp/run-34004",
            "--runtime",
            "runc",
            "--storage-driver",
            "overlay",
            "--storage-opt",
            "overlay.mount_program=/usr/bin/fuse-overlayfs",
            "--storage-opt",
            "overlay.mount_program=/usr/bin/fuse-overlayfs",
            "--storage-opt",
            "overlay.mountopt=nodev,metacopy=on",
            "--events-backend",
            "file",
            "container",
            "cleanup",
            "3bc14872777de686061f88f78fe8329d6ac09f998ba5765c2df9fea5c4a13314"
        ],
        "Namespace": "",
        "IsInfra": false,
        "Config": {
            "Hostname": "3bc14872777d",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "TERM=xterm",
                "container=podman",
                "HOSTNAME=3bc14872777d",
                "HOME=/root"
            ],
            "Cmd": [
                "sleep",
                "20000"
            ],
            "Image": "docker.io/library/centos:latest",
            "Volumes": null,
            "WorkingDir": "/",
            "Entrypoint": "",
            "OnBuild": null,
            "Labels": {
                "org.label-schema.build-date": "20200809",
                "org.label-schema.license": "GPLv2",
                "org.label-schema.name": "CentOS Base Image",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vendor": "CentOS"
            },
            "Annotations": {
                "io.container.manager": "libpod",
                "io.kubernetes.cri-o.Created": "2020-11-25T23:10:25.170685706-05:00",
                "io.kubernetes.cri-o.TTY": "false",
                "io.podman.annotations.autoremove": "FALSE",
                "io.podman.annotations.init": "FALSE",
                "io.podman.annotations.privileged": "FALSE",
                "io.podman.annotations.publish-all": "FALSE",
                "org.opencontainers.image.stopSignal": "15"
            },
            "StopSignal": 15,
            "CreateCommand": [
                "podman",
                "run",
                "-d",
                "centos",
                "sleep",
                "20000"
            ]
        },
        "HostConfig": {
            "Binds": [],
            "CgroupMode": "host",
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "k8s-file",
                "Config": null
            },
            "NetworkMode": "slirp4netns",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [],
            "CapDrop": [],
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": [],
            "GroupAdd": [],
            "IpcMode": "private",
            "Cgroup": "",
            "Cgroups": "default",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "private",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": [],
            "Tmpfs": {},
            "UTSMode": "private",
            "UsernsMode": "",
            "ShmSize": 65536000,
            "Runtime": "oci",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": 0,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": [],
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        }
    }
]

bash-4.4$ podman inspect 3bc |grep cgroup -i
            "--cgroup-manager",
            "cgroupfs",
            "CgroupMode": "host",
            "Cgroup": "",
            "Cgroups": "default",
            "CgroupParent": "",

**Comment by rhatdan** [comment]
First off this should be a bugzilla not an issue.  Really not an upstream issue.

But I do not believe this would have worked in older podman, since cgroups are not supported in rootless mode with cgroupV1.  Cgroups can not be delegated and not root users are not allowed to write to them,  So this is expected behaviour until you move to cgroupV2 and using an OCI runtime like crun, or an upstream version of runc.
