### ISSUE TITLE
Missing `runc` dependency on Ubuntu

### ISSUE THREAD

**Issue by ctron** [containers/podman#8492]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Following the installation instructions for Ubuntu fail to create a working installation.

**Steps to reproduce the issue:**

1. Follow installation instructions (`apt install podman`)

2. Run `podman ps`

3.

**Describe the results you received:**

~~~
ubuntu@ubuntu:~$ podman ps
Error: default OCI runtime "runc" not found: invalid argument
~~~

**Describe the results you expected:**

~~~
ubuntu@ubuntu:~$ podman ps
CONTAINER ID  IMAGE   COMMAND  CREATED  STATUS  PORTS   NAMES
~~~

**Additional information you deem important (e.g. issue happens only occasionally):**

Can be fixed with:

~~~
sudo apt install runc
~~~

**Output of `podman version`:**

```
Version:      2.0.6
API Version:  1
Go Version:   go1.14.7
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/arm64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/groovy,now 2.0.6+dfsg1-1ubuntu1 arm64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

~~~
Linux ubuntu 5.8.0-1007-raspi #10-Ubuntu SMP PREEMPT Thu Nov 5 17:52:40 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
~~~

**Comment by Luap99** [comment]
If you installed from the ubuntu repos you should report this there.

**Comment by lsm5** [comment]
Hi @ctron, like @Luap99 mentioned, bugs on packages from the official distro repos are best reported at their own bug reporting sites. OBS bugs can be reported here though. Copying @siretart, the official debian/ubuntu maintainer for reference.

Closing..

**Comment by siretart** [comment]
Sounds an awful lot like https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=971253 -- please send followup, suggestions and patches to 971253 (at) bugs.debian.org, subscribe by email 971253-subscribe@bugs.debian.org
