### ISSUE TITLE
Unable to compile podman using Ubuntu 20.04

### ISSUE THREAD

**Issue by dc25** [containers/podman#8496]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**
Going by instructions found here:  https://podman.io/getting-started/installation.html

1.  Install prerequisites.  Using btrfs-progs instead of btrfs-tools (which was not available) and libprotobuf-c-dev instead of libprotobuf-c0-dev (also not available)
```
sudo apt install -y   make curl
sudo apt install -y   libapparmor-dev
sudo apt install -y libprotobuf-c-dev btrfs-progs 
sudo apt install -y git   golang-go   go-md2man   iptables   libassuan-dev   libbtrfs-dev   libc6-dev   libdevmapper-dev   libglib2.0-dev   libgpgme-dev   libgpg-error-dev   libprotobuf-dev    libseccomp-dev   libselinux1-dev   libsystemd-dev   pkg-config   runc   uidmap
```
2.  Set golang related variables.
```
export GOPATH=~/go
export GOCACHE="$(mktemp -d)"
mkdir -p $GOPATH
```
3.  Verify recent enough version of go

```
$ go version
warning: GOPATH set to GOROOT (/home/dave/go) has no effect
go version go1.13.8 linux/amd64
```

4.  Attempt to compile.

```
mkdir -p $GOPATH/src/github.com/containers/podman
git clone https://github.com/containers/podman/ $GOPATH/src/github.com/containers/podman
cd $GOPATH/src/github.com/containers/podman
make BUILDTAGS="selinux seccomp"
```
**Describe the results you received:**
```
$ cd $GOPATH/src/github.com/containers/podman
$ make BUILDTAGS="selinux seccomp"
warning: GOPATH set to GOROOT (/home/dave/go) has no effect
# Only generate the varlink code on Linux (see issue #4814).
go generate ./pkg/varlink/...
warning: GOPATH set to GOROOT (/home/dave/go) has no effect
go: inconsistent vendoring in /home/dave/go/src/github.com/containers/podman:
	go.mod requires github.com/containers/podman/v2  but vendor/modules.txt does not include it.
	run 'go mod tidy; go mod vendor' to sync
make: *** [Makefile:667: pkg/varlink/iopodman.go] Error 1
```

**Additional information you deem important (e.g. issue happens only occasionally):**

This happens on a "bare metal" lenovo thinkpad and a virtual box both running ubuntu 20.04 machine.   It does not(!) happen in a docker based environment based on Ubuntu 20.04.   

I played with the "go mod tidy; go mod vendor" suggestion but it didn't lead to anything useful.

I was able to build and install conmon per the instructions.

**Comment by rhatdan** [comment]
Looks like something in your GOPATH is not setup correctly.

echo $GOPATH 
/home/dwalsh/go

@giuseppe @vrothberg any idea what is wrong in his setup?

**Comment by vrothberg** [comment]
`warning: GOPATH set to GOROOT (/home/dave/go) has no effect`

That looks odd. Can you make sure that GOPATH and GOROOT are different.  MY GOROOT is empty.

**Comment by dc25** [comment]
Thank you.   Yes, that was it.   Unsetting GOROOT took care of the problem.
