### ISSUE TITLE
Installing podman to use mounted docker.sock in ubi8-minimal

### ISSUE THREAD

**Issue by ashokponkumar** [containers/podman#8509]
I want to access the mounted docker.sock and run containers from inside a ubi8 container.

To achieve it, I have the following questions:
1. How to install podman using microdnf or any other method inside a ubi8-minimal image
2. How to make podman use the mounted docker socket and run docker commands

**Comment by mheon** [comment]
Can you clarify your setup here? Are you trying to use Podman in a container to communicate with a Docker daemon on the host system? This does not work - Podman is a separate container runtime and does not use or interact with the Docker daemon. We can pull images from Docker, but that is really the extent of our interaction.

**Comment by baude** [comment]
this isnt really an upstream question.

**Comment by ashokponkumar** [comment]
> Can you clarify your setup here? Are you trying to use Podman in a container to communicate with a Docker daemon on the host system? This does not work - Podman is a separate container runtime and does not use or interact with the Docker daemon. We can pull images from Docker, but that is really the extent of our interaction.

Oh okay. I thought podman can emulate docker client. Thanks for the quick response.

For our [Move2Kube](https://github.com/konveyor/move2kube), to be capable of running container inside container for cnb, we needed a way to leverage the docker socket, so that it can use the underlying docker system when using [docker compose](https://github.com/konveyor/move2kube-ui/blob/master/docker-compose.yml). We weren't able to get podman running within the container. If docker sock is not supported, it would be great if we can find the right [pod spec](https://github.com/konveyor/move2kube-operator/blob/master/helm-charts/move2kube/templates/move2kubeapi-statefulset.yaml), which will make the podman work with a rootless container (for running it as a container in Kubernetes/Openshift).

We are using ubi8-minimal image for it, so we needed a way to install podman in it.

**Comment by rhatdan** [comment]
Can you run the container with privileges?  To run podman inside of a container, it needs at least CAP_SETUID and CAP_SETGID.
Or you could do the same type of hack that Docker is doing and leak a podman.sock into the container and allow podman-remote to connect to the socket to launch containers.

**Comment by ashokponkumar** [comment]
> Can you run the container with privileges? To run podman inside of a container, it needs at least CAP_SETUID and CAP_SETGID.
> Or you could do the same type of hack that Docker is doing and leak a podman.sock into the container and allow podman-remote to connect to the socket to launch containers.

Thanks @rhatdan . I want to REQUIRE as minimum permissions as possible, though would fall back to what is technically NEEDED. I will try with CAP_SETUID and CAP_SETGID permissions and see how it works.

What would be the best way to install podman/podman-remote in ubi8-minimal? I don't see it in microdnf repos.

Also, is there a way to use say podman-remote to interface with crio in a Openshift/Kubernetes cluster so that I can use the same hack to get container there too?

**Comment by rhatdan** [comment]
@fatherlinux could you anwer the questions on ubi-minimal?  @ashokponkumar You could also just use ub8 regular along with dnf.  If Podman is currently available as a UBI package.

podman only works with CRI-O on the image level, not at the container level.  This has always been a goal, but over time it has become less of a goal.  You can use crictl to interact with the CRI-O socket,

**Comment by ashokponkumar** [comment]
Thanks @rhatdan . This helps. Have fallen back to ubi8 for now. 

I did try with cricrl, but the interface seemed to be intentionally designed to support ONLY k8s deployment and not for easy spawning of containers like podman/docker.Though was able to bring up containers, it wasn't smooth and could not get all features up, so was thinking of using podman if it supported it.

**Comment by rhatdan** [comment]
Well You can use podman to create containers and you can use CRI-O/crictl.  But using them together on the same host is problematic.  Currently Kubernetes likes to control all containers running on the system, and will do stuff like remove images and containers that it does not know about or does not feel it needs.

Running Podman within a container or on the host should be possible,

**Comment by ashokponkumar** [comment]
> Well You can use podman to create containers and you can use CRI-O/crictl.  But using them together on the same host is problematic.  Currently Kubernetes likes to control all containers running on the system, and will do stuff like remove images and containers that it does not know about or does not feel it needs.
> 
> Running Podman within a container or on the host should be possible,

Sure. Will try to use podman to create container within container using the CAP_ permissions.
