### ISSUE TITLE
Unknown options --subuid and --subgid

### ISSUE THREAD

**Issue by mavit** [containers/podman#8510]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The `podman-create` and `podman-run` manpages both mention options ` --subuid` and `--subgid`, but neither exist.  Are these typos for ` --subuidname` and `--subgidname`?

**Output of `podman version`:**

```
podman version 2.1.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.1.1-7.fc32.x86_64
```

**Have you tested with the latest version of Podman?**

Yes

**Comment by rhatdan** [comment]
Opened a PR to fix.
