### ISSUE TITLE
Docker CLI incompatibility missing volume creation

### ISSUE THREAD

**Issue by Jakuje** [containers/podman#8513]
/kind bug

**Description**

I am not sure if this is intentional design decision (and it should be documented in [transfer.md](https://github.com/containers/podman/blob/master/transfer.md)) or something that should be fixed.

**Steps to reproduce the issue:**

If one runs docker with non-existent local mount:

    docker run -v /tmp/nononono:/yes -it fedora:latest /bin/bash

it is automatically created and mounted into the container.

In podman, it not very surprisignly complains there is no such source directory:

    Error: error checking path "/tmp/nononono": stat /tmp/nononono: no such file or directory

**Output of `podman version`:**

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.14.9
Built:        Wed Sep 30 21:31:11 2020
OS/Arch:      linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.1.1-7.fc32.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora 32, physical

** Background **

oss-fuzz is using docker from a [helper script](https://github.com/google/oss-fuzz/blob/master/infra/helper.py) to run containers for fuzzing open source project. I use podman locally to reproduce issues, build fuzzing drivers and so on. It works for me for some years already, sometimes better, sometimes worse and now with a couple of patches on top of their helpers to work with podman. As I would like to get the upstream and make sure it works also in future, I need to clarify couple of things as the above, whether this should be fixed in the helper script or in `podman`.

**Comment by mheon** [comment]
This is a known, deliberate difference. We feel that this behavior from
Docker is more of a bug than a feature - if I want to mount, say, /tmp/test
but instead I mistype and write /tmp/tset, Docker will happily create a new
directory which was decidedly not my intention. We realize that differences
from Docker behavior like this are inconvenient, so we try to keep them as
free as possible, but we also do not want to force ourselves to follow
their mistakes as well as their successes.

**Comment by Jakuje** [comment]
Thanks for clarification. I had the same feeling that it more sane way doing things but I was not able to find this difference documented so there fore I wanted to check if there is a place where this should be mentioned (either above document, manual page of docker run or completely elsewhere).

**Comment by rhatdan** [comment]
Where did you look for the documentation?  Would you want this specified in the podman run/create man page?

**Comment by Jakuje** [comment]
I used https://github.com/containers/podman/blob/master/transfer.md and manual page for `podman run`. I think either of these is fine for me. If the same "issue" is also in the `podman create`, its manual should mention it too.

I don't know if one of these is more suitable for documenting these differences, but manual pages are always at hand and up to date so they would be my preference. Unless they are already too long so having it in the above page might make more sense.
