### ISSUE TITLE
Image layer storage/deletion slow on Oracle Linux

### ISSUE THREAD

**Issue by iinuwa** [containers/podman#8516]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When pulling images, after downloading the image layers, there is a long delay.

**Steps to reproduce the issue:**

Pull any image, or build any image.

**Describe the results you received:**
```
> time podman pull docker.io/fedora
Trying to pull docker.io/fedora...
Getting image source signatures
Copying blob ae7b613df528 done
Copying config b3048463dc done
Writing manifest to image destination
Storing signatures
b3048463dcefbe4920ef2ae1af43171c9695e2077f315b2bc12ed0f6f67c86c7

real    1m13.358s
user    0m14.674s
sys     0m6.100s
```

Truncated `strace` output. Note that after the "Storing signatures" step, the wait for pid 94832 takes 69 seconds. (I think; I'm not familiar with Linux syscalls at all.)

```
> strace -T podman pull docker.io/fedora
# ...
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fb5bc41fa10) = 94832 <0.001674>
close(7)                                = 0 <0.000030>
close(8)                                = 0 <0.000023>
wait4(94832, Trying to pull docker.io/fedora...
Getting image source signatures
Copying blob sha256:ae7b613df528a37664448affa6e52ff405701cda015a2a67301423bc20226b61
Copying config sha256:b3048463dcefbe4920ef2ae1af43171c9695e2077f315b2bc12ed0f6f67c86c7
Writing manifest to image destination
Storing signatures
b3048463dcefbe4920ef2ae1af43171c9695e2077f315b2bc12ed0f6f67c86c7
[{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 94832 <69.195757>
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=94832, si_uid=993, si_status=0, si_utime=1450, si_stime=205} ---
rt_sigreturn({mask=[]})                 = 94832 <0.000035>
futex(0x5615ed0c8e98, FUTEX_WAKE_PRIVATE, 1) = 1 <0.000044>
exit_group(0)                           = ?
+++ exited with 0 +++
```

While executing this in real time outside of `strace`, the pause takes place between the `Storing signatures` and `b30484...` lines.

**Describe the results you expected:**

I expected the image to save within ~10 seconds after the layers are downloaded.

**Additional information you deem important (e.g. issue happens only occasionally):**

This issue happened on version 1.9.x as well.

Someone mentioned that this may be due to image decompression

**Output of `podman version`:**

```
Version:      2.0.5
API Version:  1
Go Version:   go1.14.7
Built:        Sat Nov  7 04:18:34 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.1
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.20-2.module+el8.3.0+7866+f387f528.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.20, commit: 68196d58ce37bc799ff4cf59f50a0fe7e1382b74'
  cpus: 2
  distribution:
    distribution: '"ol"'
    version: "8.3"
  eventLogger: file
  hostname: eabuilddv1-ol8.moody.edu
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 989
      size: 1
    - container_id: 1
      host_id: 296608
      size: 66536
    uidmap:
    - container_id: 0
      host_id: 993
      size: 1
    - container_id: 1
      host_id: 296608
      size: 65536
  kernel: 5.4.17-2036.100.6.1.el8uek.x86_64
  linkmode: dynamic
  memFree: 452665344
  memTotal: 3795267584
  ociRuntime:
    name: crun
    package: crun-0.14.1-2.module+el8.3.0+7866+f387f528.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.14.1
      commit: 598ea5e192ca12d4f6378217d3ab1415efeddefa
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/993/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-2.module+el8.3.0+7866+f387f528.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 6404698112
  swapTotal: 6434058240
  uptime: 114h 22m 39.11s (Approximately 4.75 days)
registries:
  search:
  - container-registry.oracle.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  configFile: /var/lib/jenkins/.config/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 0
    stopped: 7
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-3.module+el8.3.0+7866+f387f528.x86_64
      Version: |-
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /var/lib/jenkins/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 14
  runRoot: /tmp/run-993
  volumePath: /var/lib/jenkins/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1604744314
  BuiltTime: Sat Nov  7 04:18:34 2020
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.0.5
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
> rpm -q podman
podman-2.0.5-5.0.1.module+el8.3.0+7866+f387f528.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No, and Yes

I have checked the Podman Troubleshooting Guide, and this is the latest available version on this repository. I haven't tried building 2.1.0 yet.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Oracle Linux 8 OS in VMware VM

**Comment by mheon** [comment]
@mtrmac Am I correct in remembering that the next step after downloading is extracting? That seems like it could be our culprit.

**Comment by mtrmac** [comment]
Yes, in the current implementation of pull, “copying blob” just decompresses the layer and writes it as a simple linear temporary file, ideally a nice efficient streaming operation. Only in the “commit” step (after “Storing signatures”, without a separate marker) are all the new layers actually extracted to the filesystem as individual files, incurring all the seeks and journalling filesystem commits and the associated disk queue/cache flushes.

We do want to eventually make more of the filesystem extraction parallel with downloading (at least for multi-layer images), and visible in the progress output; a significant part of that already exists as part of Valentin’s work on concurrent copy detection (which also took on 3-4 other issues, some of them much more difficult).

So this is not currently very surprising (although the report does not contain much precise data; 69 seconds of commit vs. 73 seconds total would probably count as surprising).

(And if I’m reading that strace / output correctly, 69 seconds is the time for the whole subprocess, probably including the pull. Anyway, a useful strace would need to include that child process, maybe using `-f` or `-ff`.)

**Comment by iinuwa** [comment]
@mtrmac, thanks for your input!

> 69 seconds of commit vs. 73 seconds total would probably count as surprising

This is what I'm observing; the layer only takes 5-10 seconds to download, and then a minute to commit.

> the report does not contain much precise data ... a useful strace would need to include that child process, maybe using `-f` or `-ff`

I ran `strace -T -f podman pull docker.io/fedora`, but the output file is 70M. Is there somewhere you want me to post this, or any filters you want me to use? (Sorry, I'm generally unfamiliar with `strace`)

**Comment by iinuwa** [comment]
[strace-with-forks-podman-pull.txt.gz](https://github.com/containers/podman/files/5630905/strace-with-forks-podman-pull.txt.gz)

I didn't realize GitHub supported file attachments.

**Comment by iinuwa** [comment]
Does anyone have any pointers that I could use to start troubleshooting this myself? This is probably a system configuration issue or something on my end, so this may not be reproducible by others. It adds a lot of time for our container-based CI platform, so I'd like to look into it further.

Is `strace` the right tool to look into this? Should I be looking at something else?

**Comment by rhatdan** [comment]
@giuseppe Thoughts?

**Comment by giuseppe** [comment]
Does the issue happen only with Oracle Linux?  Have you tried a different distro and keeping the same configuration for the VM?

Few things you can investigate:

run `top` during the decompression and see how much cpu is the podman process taking.

It may also be related to slow storage.  Could you try setting the equivalent of `cache-mode=unsafe` for the VM?

**Comment by iinuwa** [comment]
> run top during the decompression and see how much cpu is the podman process taking.

D'oh! I should have thought of that a long time ago. It looks like an antivirus agent is stalling the stall. I'll work with our sysadmins to see if we can work around this. Sorry to bother you.

Thanks for your help!

**Comment by rhatdan** [comment]
Ok I am going to close this issue.  Reopen if this turns out to be related to podman.
