### ISSUE TITLE
podman-2.2.0_rc2 & later: '--rm' option isn't removing exited containers?

### ISSUE THREAD

**Issue by srcshelton** [containers/podman#8524]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I have a container I've launched as follows:

```
podman run --rm --quiet --detach --init --network host --pids-limit 2048 --name <process>-daily   <process>:latest
```

... with the expectation that, once the container terminates for any reason, it will be removed.  This allowed for a primitive form of locking when run from a cron-job: if the process completed it's container would be removed and the next invocation could run - but if the previous run was still in-progress, then duplicate name would prevent the second instance from launching.

With `podman-2.2.0_rc2`, however, the container remains even after exiting:

```
# podman ps -a | grep <process>
58e3adc12b3a    localhost/<process>:latest    6 hours ago    Exited (0) 2 hours ago    <process>-daily
```

... anything I can check to see when removal isn't triggering?

**Steps to reproduce the issue:**

1. Start a container with `--rm`;

2. Allow the process within the container to exit.

**Describe the results you received:**

Container still exists after termination, blocking the container-name from re-use.

**Describe the results you expected:**

Container would be erased on exit.

**Output of `podman version`:**

```
Version:      2.2.0-rc2
API Version:  2.1.0
Go Version:   go1.15.5
Git Commit:   cbdb4d54bd3dddb8b4452adbfc29ca7702b8e387
Built:        Sun Nov 29 02:20:47 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 35a2fa83022e56e18af7e6a865ba5d7165fa2a4a'
  cpus: 8
  distribution:
    distribution: gentoo
    version: unknown
  eventLogger: file
  hostname: dellr330
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.9.6-gentoo
  linkmode: dynamic
  memFree: 787894272
  memTotal: 33392836608
  ociRuntime:
    name: crun
    package: Unknown
    path: /usr/bin/crun
    version: |-
      crun version 0.16
      commit: eb0145e5ad4d8207e84a327248af76663d4e50dd
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 20386598912
  swapTotal: 25769787392
  uptime: 165h 48m 17.24s (Approximately 6.88 days)
registries:
  search:
  - docker.io
  - docker.pkg.github.com
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 24
    paused: 0
    running: 22
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.ignore_chown_errors: "false"
  graphRoot: /space/podman/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 844
  runRoot: /space/podman/run
  volumePath: /space/podman/volumes
version:
  APIVersion: 2.1.0
  Built: 1606616447
  BuiltTime: Sun Nov 29 02:20:47 2020
  GitCommit: cbdb4d54bd3dddb8b4452adbfc29ca7702b8e387
  GoVersion: go1.15.5
  OsArch: linux/amd64
  Version: 2.2.0-rc2

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Comment by baude** [comment]
is this still an issue?

**Comment by srcshelton** [comment]
I've now updated to `podman-2.2.1` - I'll update to confirm the issue or close it off once the scheduled task showing the above behaviour runs overnight...

... but I *think* it's still an issue...

**Comment by mheon** [comment]
I recently fixed a bug that might be related, but it only affected containers started with `--log-level=debug`

**Comment by srcshelton** [comment]
Ah - that might be it!  Some of these containers are started with debug logging which is then redirected to a file.

...

Hmm - but not these ones.  Even with `2.2.1` I'm starting containers with the above command-line (including `--rm`) and their status is showing as `Exited (0) 15 hours ago` but they've not been removed.

**Comment by rhatdan** [comment]
Any thing reported in the journal?  When containers run in daemon mode they launch conmon, which will launch a podman container cleanup process when the container exits.  For some reason this cleanup process must be failing.

**Comment by srcshelton** [comment]
I'm on a host without systemd - is this logged elsewhere (by default)?  Do the cleanup processes still trigger under other init systems?

I've not added any specific logging for these containers - but I can run with debug logging and capture `stdout`/`stderr` if that'd help?

**Comment by rhatdan** [comment]
You can see the cleanup call in the conmon process.

ps -auxww | grep conmon

If you can execute that command on a stopped container see if it throws an error.

```--exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /home/dwalsh/.local/share/containers/storage --exit-command-arg --runroot --exit-command-arg /run/user/3267/containers --exit-command-arg --log-level --exit-command-arg error --exit-command-arg --cgroup-manager --exit-command-arg systemd --exit-command-arg --tmpdir --exit-command-arg /run/user/3267/libpod/tmp --exit-command-arg --runtime --exit-command-arg crun --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --storage-opt --exit-command-arg overlay.mount_program=/home/dwalsh/bin/fuse-overlayfs --exit-command-arg --events-backend --exit-command-arg journald --exit-command-arg container --exit-command-arg cleanup --exit-command-arg 9a952811af1e90c72b0570d3c32b07687ea31ff34eb4391aa0bc5f015db9caa5```

Remove the --exec-command and --exec-command-arg and you get the command to be executes in cleanup.

**Comment by srcshelton** [comment]
Interestingly, I've got `conmon` processes for all of the running containers, but none for the unremoved container (with status `Exited`) - suggesting that the process has already executed the exit commands (or not) and has itself then quit?

I chose another disposable container and confirmed that there was a `conmon` process running, and then ran `podman stop` on this container.  This container now also has status `Exited` and the conmon process is gone.

**Comment by srcshelton** [comment]
Noting that `podman ps -a` still shows:

```
CONTAINER ID  IMAGE                                                   COMMAND               CREATED        STATUS                       PORTS   NAMES
fa752ee7b204  localhost/dell-ism:351                                                        33 hours ago   Exited (143) 19 seconds ago          dell-ism-351
```

**Comment by rhatdan** [comment]
Did you record the podman container cleanup call from the `ps -auxww | grep common` command, you should be able to run this a second time and see if it throws an error.

**Comment by srcshelton** [comment]
... so this is interesting - the container in question is launched from `crontab` with different parameters at either 18, 19, or 20 minutes past the hour depending on the day of the week/month, and so I added an additional task to run at 21 minutes past the hour and run, as you suggested, `ps -auxww | grep conmon`.

And the output shows a whole stack of running `conmon` processes for each of the containers I have running, searchable by name.

**But** there is no entry for the container which isn't being removed on exit... so it appears that conmon is exiting early (without causing the container to abort), but is then long-gone hours later when the container *does* exit.

Is there a good way to get `conmon` to log diagnostics (or, at least, that it is exiting early?)

**Comment by rhatdan** [comment]
conmon should be writing log information to journal.

**Comment by srcshelton** [comment]
> conmon should be writing log information to journal.

... and on systems without systemd?

I'm getting nothing via syslog or on stderr...

**Comment by mheon** [comment]
Should be going to syslog, as long as `--log-level=debug` was specified when the container was created.

**Comment by srcshelton** [comment]
Okay - I've added `--log-level=debug`, I'll post the results after the next run.

Is `conmon` disappearing at/soon-after launch a known issue under any circumstance?

**Comment by mheon** [comment]
No? Conmon disappearing would be a very large problem, though, we lose the ability to track the container.

**Comment by srcshelton** [comment]
So that's what seems to be happening... but I've only seen this when the container is started by cron (`cronie`, specifically) - I've not seen this interactively or when starting containers as services on boot.

Tasks run from cron are run with a minimal environment - but so are services run by `openrc-run`.

Any good way to get additional logging from `conmon` (or automatically starting it with a debugger attached, or similar)?

If there's no better more integrated option available I could always temporarily replace `conmon` with a script that runs `strace` against the actual `conmon` binary?

**Comment by rhatdan** [comment]
If you put a shell script in the same place as conmon or modified containers.conf to point to `Your conmon` it should work.

**Comment by rhatdan** [comment]
```
# conmon_path = [
#        "/usr/libexec/podman/conmon",
#        "/usr/local/libexec/podman/conmon",
#        "/usr/local/lib/podman/conmon",
#        "/usr/bin/conmon",
#        "/usr/sbin/conmon",
#        "/usr/local/bin/conmon",
#        "/usr/local/sbin/conmon"
# ]
```

**Comment by rhatdan** [comment]
Usually there is a process that is killing the conmon process.  We have seen this kind of issue with systemd.  Other potential would be something that kills all processes inside of the current cgroup,

You could play with the --cgroups option.  But I have no idea what is killing conmon.

**Comment by srcshelton** [comment]
From the debug log:

```
time="2021-01-07T18:18:03Z" level=debug msg="running conmon: /usr/bin/conmon" args="[--api-version 1 -c c531cf0db39bc2f9ae7a60c116e803220447a65fac85a98333eceb2e6e6bb7d9 -u c531cf0db39bc2f9ae7a60c116e803220447a65fac85a98333eceb2e6e6bb7d9 -r /usr/bin/crun -b /space/podman/storage/overlay-containers/c531cf0db39bc2f9ae7a60c116e803220447a65fac85a98333eceb2e6e6bb7d9/userdata -p /space/podman/run/overlay-containers/c531cf0db39bc2f9ae7a60c116e803220447a65fac85a98333eceb2e6e6bb7d9/userdata/pidfile -n process-funds --exit-dir /var/run/libpod/exits --socket-dir-path /var/run/libpod/socket -l k8s-file:/space/podman/storage/overlay-containers/c531cf0db39bc2f9ae7a60c116e803220447a65fac85a98333eceb2e6e6bb7d9/userdata/ctr.log --log-level debug --syslog --conmon-pidfile /space/podman/run/overlay-containers/c531cf0db39bc2f9ae7a60c116e803220447a65fac85a98333eceb2e6e6bb7d9/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /space/podman/storage --exit-command
-arg --runroot --exit-command-arg /space/podman/run --exit-command-arg --log-level --exit-command-arg debug --exit-command-arg --cgroup-manager --exit-command-arg cgroupfs --exit-command-arg --tmpdir --exit-command-arg /var/run/libpod --exit-command-arg --runtime --exit-command-arg crun --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --storage-opt --exit-command-arg overlay.ignore_chown_errors=false --exit-command-arg --events-backend --exit-command-arg file --exit-command-arg --syslog --exit-command-arg container --exit-command-arg cleanup --exit-command-arg --rm --exit-command-arg c531cf0db39bc2f9ae7a60c116e803220447a65fac85a98333eceb2e6e6bb7d9]"
time="2021-01-07T18:18:04Z" level=debug msg="Received: 5274"
time="2021-01-07T18:18:04Z" level=info msg="Got Conmon PID as 5271"
```

... when I checked 14 minutes later (with the container still running) there was no process 5271.

This system isn't running systemd, so other than OOM there shouldn't be anything killing off processes.

Worth noting that this is now with `conmon-2.0.22`, but the problem has been around for at least the previous release also.

**Comment by rhatdan** [comment]
@giuseppe @haircommander Ideas?

**Comment by srcshelton** [comment]
I've put a script which invokes `strace` in place of `conmon` - I should be able to report the results by Tuesday morning.

**Comment by mheon** [comment]
@srcshelton We recently found and fixed a bug in Conmon where it would dump core in some cases when launching the cleanup process. Can you test again with the latest Conmon tag, v2.0.26?

**Comment by srcshelton** [comment]
> @srcshelton We recently found and fixed a bug in Conmon where it would dump core in some cases when launching the cleanup process. Can you test again with the latest Conmon tag, v2.0.26?

Sure thing - let me get this built now!

**Comment by srcshelton** [comment]
... so I'm now on:

```
Version:      3.0.0-rc2
API Version:  3.0.0
Go Version:   go1.15.7
Git Commit:   510a983a752a136a5df0bdbff9d14db0490956b2
Built:        Fri Feb  5 22:53:35 2021
OS/Arch:      linux/amd64
```

```
host:
  arch: amd64
  buildahVersion: 1.19.2
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: app-emulation/conmon-2.0.26
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 0e155c83aa739ef0a0540ec9f9d265f57f68038b'
  cpus: 8
  distribution:
    distribution: gentoo
    version: unknown
  eventLogger: file
  hostname: dellr330
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.12-gentoo
  linkmode: dynamic
  memFree: 346030080
  memTotal: 33390886912
  ociRuntime:
    name: crun
    package: app-emulation/crun-0.17
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 24351277056
  swapTotal: 25769787392
  uptime: 58h 35m 28.7s (Approximately 2.42 days)
registries:
  localhost:5000:
    Blocked: false
    Insecure: true
    Location: localhost:5000
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: localhost:5000
  search:
  - docker.io
  - docker.pkg.github.com
  - quay.io
  - public.ecr.aws
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 23
    paused: 0
    running: 23
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.ignore_chown_errors: "false"
  graphRoot: /space/podman/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 161
  runRoot: /space/podman/run
  volumePath: /space/podman/volumes
version:
  APIVersion: 3.0.0
  Built: 1612565615
  BuiltTime: Fri Feb  5 22:53:35 2021
  GitCommit: 510a983a752a136a5df0bdbff9d14db0490956b2
  GoVersion: go1.15.7
  OsArch: linux/amd64
  Version: 3.0.0-rc2

```

... and unfortunately I'm seeing the same behaviour: even when started with `--rm`, these particular (but not all!) containers are persisting after they exit.

**Comment by baude** [comment]
it looks like you are on gentoo, can you paste the bit of the build where the gocode is being compiled? i wonder if we are dealing with a missing option or use flag?

**Comment by srcshelton** [comment]
> it looks like you are on gentoo, can you paste the bit of the build where the gocode is being compiled? i wonder if we are dealing with a missing option or use flag?

I am... were you looking for the build-log from `conmon` (presumably?), `podman`, or one of the other tools?  Any/all of the above? 😅

**Comment by vrothberg** [comment]
@baude, which info are you looking for?

**Comment by rhatdan** [comment]
I believe this is fixed in our current release, reopen if I am mistaken.
