### ISSUE TITLE
vendoring non-upstream cobra

### ISSUE THREAD

**Issue by vrothberg** [containers/podman#8528]
We are currently vendoring a non-upstream version of cobra (see https://github.com/containers/podman/blob/master/go.mod#L79):
```
[...]
replace github.com/spf13/cobra => github.com/Luap99/cobra v1.0.1-0.20201110155035-83a59186c706
```

That's not sustainable and is breaking Debian packaging. I'd loved to get that fixed quickly.

@Luap99, could you take care of it?  I think you're the cobra expert and will know what to do :)

@mheon @baude FYI ... may be worth a 2.2.1 :^)

**Comment by Luap99** [comment]
@vrothberg Why is it exactly failing? 

The problem is that upstream cobra is missing a feature and bug fixes that I rely on. Commit df4bf5c584f264bdefef5cb30d85c036260eff8f mentions the necessary PRs. Unfortunately there is no indication when these are merged upstream.

**Comment by vrothberg** [comment]
@Luap99, many distributions are not using the `./vendor` directory.  Each dependency is put in a dedicated source package, similar to how traditional C programs are built and distributed.

We currently vendor a fork of a non-released version of project we do not control.  That can cause all kinds of problems (e.g., we miss potential security fixes) with the immediate consequence of breaking downstream packaging.  Downstream packagers won't create a source package for your github fork, so they're blocked.

I missed this part when reviewing https://github.com/containers/podman/pull/6442 unfortunately.

Lets check what we can do to resolve the issue. Do you see a workaround that would avoid the dependency? How much work would it be?

**Comment by Luap99** [comment]
Well that only leaves the option to revert to the latest cobra release. It's doable but will hurt completion experience.

**Comment by vrothberg** [comment]
> Well that only leaves the option to revert to the latest cobra release. It's doable but will hurt completion experience.

Can you elaborate on which functionality would be missing?

**Comment by Luap99** [comment]
It's not easy to explain for zsh and fish we are fine just small bug fixes that are missing. Bash however would have bigger problems, it would recommend every flag with and without the equal sign. Also persistent flags will be shown on subcommands which is not wrong but it will add even more flag suggestions. And it

I guess the best trade off is to add the old bash script back and keep the things for zsh and fish.

**Comment by Luap99** [comment]
I will open a PR

**Comment by vrothberg** [comment]
@Luap99, would the reduced bash functionality be superior to the old script? How long would it take to get your patches upstream?

I would _love_ to keep the great completions you added. Just checking which options we have.

**Comment by mheon** [comment]
Can we convince Cobra to cut a new version? We know at least some of the
maintainers.

Agree this would be a good candidate for a 2.2.1.

**Comment by vrothberg** [comment]
@mheon, we need some PRs to get merged in Cobra before. We pinged Eric Paris who might help us speed things up.

**Comment by mheon** [comment]
I am hoping to avoid a super-quick turnaround on a 2.2.1 so we definitely have some time here. Ideally we'd be able to get this landed and ready somewhere in the next few weeks.

**Comment by vrothberg** [comment]
Debian found a workaround by patching out the offending cobra calls.  Let's see if others hit the same issue.

**Comment by rhatdan** [comment]
@Luap99 @vrothberg Still a valid issue?

**Comment by Luap99** [comment]
Well it is fixed on the podman side. I am still waiting for several PRs to be merged upstream but we cannot control that.
