### ISSUE TITLE
APIv2 DOC: can't find docs for command "diff"

### ISSUE THREAD

**Issue by Edward5hen** [containers/podman#8529]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
There's a [JIRA card](https://issues.redhat.com/browse/RUN-683) about this which has been moved to `Done`, but I can't find its DOC in this [specification](http://docs.podman.io/en/latest/_static/api.html).

**Comment by jwhonce** [comment]
The card is poorly written.  There exists a `podman diff` which is an alias for `podman container diff` or `podman image diff` depending on the input.  The API does not provide this style of switching, you must call a method on a given resource.

As a developer, I cannot delete cards only mark done or obsolete.
