### ISSUE TITLE
APIv2 DOC: can't find docs for command "port"

### ISSUE THREAD

**Issue by Edward5hen** [containers/podman#8530]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
There is a [JIRA card](https://issues.redhat.com/browse/RUN-700) about this which has been marked as `Done`, but I can't find its DOC in [this specification](http://docs.podman.io/en/latest/_static/api.html
).

**Comment by jwhonce** [comment]
The card is poorly written.  There exists a `podman port` which is an alias for `podman container port`.  The API does not provide this style of changing container attributes, you must set this attribute when creating the container.

As a developer, I cannot delete cards only mark done or obsolete.
