### ISSUE TITLE
APIv2 DOC: can't find docs for command "logout" 

### ISSUE THREAD

**Issue by Edward5hen** [containers/podman#8532]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
There is a [JIRA card](https://issues.redhat.com/browse/RUN-696) about this which has been marked as `Done`, but I can't find its DOC in [this specification](http://docs.podman.io/en/latest/_static/api.html
).

**Comment by jwhonce** [comment]
The card is poorly written.  There exists a `podman logout`. The API requires you to set headers depending on which method you are calling  on a given resource.

As a developer, I cannot delete cards only mark done or obsolete.
