### ISSUE TITLE
Cirrus-CI Build validation fails on tag-push

### ISSUE THREAD

**Issue by cevich** [containers/podman#8538]
/kind bug

When pushing a new tag, Cirrus-CI executes a special job.  A github "check suite" is created by Cirrus-CI, and associated with the tag in github.  However, this "check run" (a.k.a. "build" in Cirrus) is very hard to find in the github WebUI.  It's much easier to observe directly in the Cirrus-CI WebUI using a url of the form `https://cirrus-ci.com/github/containers/podman/<new tag>`.

[Specifically, for the v2.2.0 tag, this Cirrus-CI build failed in the validation step.](https://cirrus-ci.com/task/5693152994525184?command=main#L29)

**Steps to reproduce the issue:**

1. Create a new tag
2. Push tag

**Describe the results you received:**

The validation step fails due to a bad value being passed to the vbatts/git-validation tool.

**Describe the results you expected:**

The `validate` makefile target should pass for new tags

**Comment by cevich** [comment]
The bug is coming from `contrib/cirrus/lib.sh`:

```sh
# N/B: CIRRUS_BASE_SHA is empty on branch and tag push.
CIRRUS_BASE_SHA=${CIRRUS_BASE_SHA:-${CIRRUS_LAST_GREEN_CHANGE:-YOU_FOUND_A_BUG}}
CIRRUS_BUILD_ID=${CIRRUS_BUILD_ID:-$RANDOM$(date +%s)}  # must be short and unique

# The starting place for linting and code validation
EPOCH_TEST_COMMIT="$CIRRUS_BASE_SHA"
```

**Comment by cevich** [comment]
***Uggg...this is incredibly, deceptively, complex WRT [the podman release process doc](https://docs.google.com/document/d/1Nfq8R04XtpFEweExs31Qv6iZVnz-A5BQkOyEzXP9eb8/edit?ts=5fb82bc6)***
The obvious fixes here seems to be something similar to:

```diff
diff --git a/contrib/cirrus/lib.sh b/contrib/cirrus/lib.sh
index 01e75d9a6..87b6bd25c 100644
--- a/contrib/cirrus/lib.sh
+++ b/contrib/cirrus/lib.sh
@@ -81,7 +81,8 @@ DEST_BRANCH="${DEST_BRANCH:-master}"
 CONTINUOUS_INTEGRATION="${CONTINUOUS_INTEGRATION:-false}"
 CIRRUS_REPO_NAME=${CIRRUS_REPO_NAME:-podman}
 # N/B: CIRRUS_BASE_SHA is empty on branch and tag push.
-CIRRUS_BASE_SHA=${CIRRUS_BASE_SHA:-${CIRRUS_LAST_GREEN_CHANGE:-YOU_FOUND_A_BUG}}
+#      CIRRUS_LAST_GREEN_CHANGE is empty on tag push
+CIRRUS_BASE_SHA=${CIRRUS_BASE_SHA:-${CIRRUS_LAST_GREEN_CHANGE:-$DEST_BRANCH}}
 CIRRUS_BUILD_ID=${CIRRUS_BUILD_ID:-$RANDOM$(date +%s)}  # must be short and unique

 # The starting place for linting and code validation
```

In order for the above fix to work (allow git-validation tool to receive a valid `$EPOCH_TEST_COMMIT`) a CI run ("build") must verify `$DEST_BRANCH` != `master` on the branch-push, during the "smoke" task.  However, @mheon document specifies the new branch is pushed w/o any additional commits.  Example failure: https://cirrus-ci.com/task/6296522633510912?command=main#L13 (smoke test).

Worse, both recently and historically, the result of CI builds is completely ignored during release. Ref [new branch build](https://cirrus-ci.com/build/6366196163411968) and [new tag build]( https://cirrus-ci.com/build/6483810923577344):

* This is bad in that if it's ignored, no script-fix or `$DEST_BRANCH` change commit, would be relevant.
* This is good in that it allows a human to survive the complex release workflow w/o needing to add any CI "fixes" or updates that themselves may lead to further CI failures.
* Release-related script fixes will be infrequently utilized and tested, it's easily possible CI/script breakage could be unintentionally introduced between releases.

@edsantiago I could use your input here, since you understand git branching/taging and generally understand the scripted CI flow.

The only env. var. I can find to possibly key checks off of seems to be [some kind of regex match involving the word "bump" vs `$CIRRUS_CHANGE_MESSAGE`](https://cirrus-ci.com/task/6296522633510912?command=setup#L26).  This gives me the willies.

Maybe this problem isn't worth fixing.

Even if @mheon is open to altering the release process doc to include a `$DEST_BRANCH` change ***and*** monitoring CI jobs for success, ***and still*** including possible additional commits after tag or branch-push needed to fix CI problems :confounded:

**Comment by mheon** [comment]
Altering DEST_BRANCH seems perfectly fine for the release process. I am somewhat less open to monitoring jobs for success given the timeframe we push these releases out in - it already takes most of a day to successfully push a release out, and a full CI run could add an hour to that process.

**Comment by cevich** [comment]
> it already takes most of a day to successfully push a release out, and a full CI run could add an hour to that process.

And potentially ***much*** longer if CI fails (on tag-push), then more again if additional commits are needed to fix the failures (requiring more tags).  I completely understand not wanting to burden a release with also having to wrestle automation :confused: 

I'd like to believe that updating `DEST_BRANCH` in the process would be be enough.  If we also discount all CI testing results during release, they cannot confer confidence through successful results, to the automatically built + tagged binaries.  The sticking point seems to be that the CI run for the tag-push is a one-shot deal.  If it fails, and smashing re-run can't fix it, the _only_ option is to commit a fix and tag again.

It really seems like it's a binary situation WRT CI and the release workflow.  We either rely 100% on automation to do the release (always deal with any failures), or we completely ignore CI and do it 100% manually (perhaps assisted with some manual helper scripts).  I can't see any/much room for a middle-ground here :face_with_head_bandage:   @edsantiago you understand git and cirrus-ci well enough...do you see any other possibilities/options we're not thinking of?

**Comment by cevich** [comment]
(woops, didn't mean to mention that PR here)

**Comment by rhatdan** [comment]
@cevich is this Issue still valid?

**Comment by cevich** [comment]
Yes, pushing a new tag will result in a job failure...but since the result is ignored anyway (see above and release doc. link), maybe we don't need to run the tests at all.  If acceptable, the "fix" could be to skip all tasks when `CIRRUS_TAG != ""`.  Unfortunately, doing this requires some really tricky and ugly changes to `.cirrus.yml`
