### ISSUE TITLE
RFE: Remove libpod.conf from Podman v3.0

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman#8546]
As of v2.0 of Podman, the libpod.conf file is only read if there is not a containers.conf file in the environment.  Having this file in the environment may cause confusion and it should be removed.

During the December 2020 Podman Community Meeting, it was suggested that it could be removed in Podman v3.0.  The removal is probably relatively easy, the harder part will be the documentation and notification of the removal to the user base.  Also, would there be a problem if someone upgraded from an older version of Podman?  We would need to come up with a procedure, possibly written instructions, on how to transition from libpod.conf to containers.conf.

**Comment by rhatdan** [comment]
This has been done in main branch.
