### ISSUE TITLE
v2.0.5-rhel branch near-constant CI-Failures

### ISSUE THREAD

**Issue by cevich** [containers/podman#8555]
/kind bug

**Description**

Every day Cirrus-CI triggers a build on the v2.0.5-rhel branch and one/more Fedora tasks frequently fail:

* [11/30 example](https://cirrus-ci.com/build/5095160889475072)
* [11/29 example (passed on re-run)](https://cirrus-ci.com/build/4850328627576832)
* [11/28 example](https://cirrus-ci.com/build/5487638826188800)
* [11/27 example](https://cirrus-ci.com/build/4966383140208640)
* ...+ 8 more daily examples :face_with_head_bandage: 

**Steps to reproduce the issue:**

1. Wait a day

**Describe the results you received:**

One or more Fedora integration tests fail.

**Describe the results you expected:**

Should not be daily failures.

**Additional information you deem important (e.g. issue happens only occasionally):**

Maybe testing tasks on this branch can be pruned so there is less chance for flake?

Another idea could be to add a ginkgo filter statement to exclude frequently flaking test(s)?

**Comment by cevich** [comment]
note to me: Decision was: tune the tests down to only running gating ("does it build" check).

**Comment by rhatdan** [comment]
Since PR merged, closing.
