### ISSUE TITLE
2.2.0 regression: can't create service when /root/ is write protected

### ISSUE THREAD

**Issue by tinywrkb** [containers/podman#8559]
Arch Linux, Podman 2.2.0-1.  

Podman fails to create service when `/root` is immutable or read-only due to failing to create `/root/.config`.  
This is a regression of 2.2.0, I have no issue with 2.1.1.  
I run Podman as root, as a system daemon, for services limited to my private network.  
root is not a regular user, I find it pretty much unacceptable to give write access to `/root', nothing should be saved there.  
I'm not sure what's going on, don't we already have `/etc/containers/storage.conf`.

I'm using podman-compose but auto-generated commands that I can run to reproduce are:

```
podman pod create --name=flatpaksrv --share net -p 3061:80
podman create \
  --name=flatpaksrv_con
  --pod=flatpaksrv
  --label io.podman.compose.config-hash=123
  --label io.podman.compose.project=flatpaksrv
  --label io.podman.compose.version=0.0.1
  --label com.docker.compose.container-number=1
  --label com.docker.compose.service=flatpaksrv
  -e NGINX_HOST=flatpak.net.private
  -e NGINX_PORT=80
  -v /etc/podman/compose/flatpaksrv/./nginx.conf:/etc/nginx/nginx.conf:ro
  -v /srv/flatpak:/srv/flatpak
  --add-host flatpaksrv:127.0.0.1
  --add-host flatpaksrv_con:127.0.0.1
  --restart always nginx nginx
  -g daemon off;
```

Error message
```
Error: mkdir /root/.config: operation not permitted
```

Downgrading to 2.1.1 fixes the issue.

**Comment by mheon** [comment]
@vrothberg Any chance this is something shortnames related, trying to make a local file for that?

**Comment by mheon** [comment]
This is also why I dislike some of the error un-stuttering done by @rhatdan - I have no idea where this error is coming from, now... Can you add `--log-level=debug` to the failing command and pastebin the results, so I have a better idea of where the failure is happening?

**Comment by tinywrkb** [comment]
@mheon here the log: https://gist.github.com/tinywrkb/f0fc4060fae3a33139cdf06efb4948fc

**Comment by vrothberg** [comment]
> @vrothberg Any chance this is something shortnames related, trying to make a local file for that?

Short names shouldn't lead to such an error (i.e., there's no ".confg" file).

**Comment by rhatdan** [comment]
I believe this is in containers/storage.

**Comment by rhatdan** [comment]
I removed the /root/.config directory and then do
mount --bind -o ro /root /root
Then run the podman command you specified above and it worked for me.
 podman pod create --name=flatpaksrv --share net -p 3061:80
43487fea46eb8b8416cada0dbe8fa970755880100e0c56cf0923799c3052f04a

**Comment by rhatdan** [comment]
vrothberg if it asked me to select an expansion it would attempt to write there.  Not sure if it would attempt to create .config.

**Comment by rhatdan** [comment]
This is caused by shortnames.

Mount /root readonly

./bin/podman run fedora echo hello
Error: mkdir /root/.config: read-only file system

Remount readwrite, successfully run a container
Remount read/only 
And I see:

./bin/podman --root /tmp/root/ --storage-driver vfs run fedora echo hello
Error: error opening "/root/.config/containers/short-name-aliases.conf.lock": read-only file system

**Comment by rhatdan** [comment]
```
# HOME=/tmp ./bin/podman run fedora echo hello
Resolved short name "fedora" to a recorded short-name alias (origin: /etc/containers/registries.conf.d/shortnames.conf)
Trying to pull registry.fedoraproject.org/fedora:latest...
Getting image source signatures
Copying blob 8fde7942e775 [=======================>--------------] 42.5MiB / 66.4MiB
```

**Comment by mheon** [comment]
Can we swap the path for root to use something in Libpod's permanent files directory, instead of `~/.config`?

**Comment by mheon** [comment]
I'd like to have this one fixed for 2.2.1

**Comment by vrothberg** [comment]
Apologies for not getting the `/root/.config` issue earlier.

> Can we swap the path for root to use something in Libpod's permanent files directory, instead of `~/.config`?

It must be shared by Buildah, Podman and other consumers of c/image. @mtrmac, do you have a preferred new destination for the root `short-name-aliases.conf`?

**Comment by mtrmac** [comment]
Hum, what’s the actual _issue_ here?
- To a first approximation, every user should have a writable home directory; why is `root` an exception?
- If `root` is not a “real user” in this case, but a service account for something SELinux-restricted or the like,
  - Why is `/root` a directory we would expect to be restricted to the service, but not any other system-wide state like `/var/lib/containers/short-name-aliases.conf`? Both would allow the service to “escape” and affect other services using the same `root` UID; so short names should either just be turned off for the service (which I’d argue is the only right thing to do long-term), or each service needs to use _its own_ alias path. Can that be automated at all?
- Assuming the default `ShortNamePermissive` mode (is that the case here?), should this be a hard failure? Arguably the code should at least be fine with finding the configuration, or parents, read-only and not try to fail creating directories just to create a lock file. (OTOH that would probably not help here if `/root` is not even readable, I think we do want to fail in that case.)

Sure, there’s fair bit of precedent of `root`-owned processes just using shared state in `/var` or the like, but conceptually I can’t see that it’s much of an improvement.

**Comment by vrothberg** [comment]
@rhatdan is a RO `/root` common? I tend to agree with @mtrmac but I have no feeling if should assume writeable `/root`.  At least on my Fedora system, there's much more going on in `/root`.

**Comment by mtrmac** [comment]
OTOH, it would be quite unsurprising to store the state in `/var/lib/containers` and treat it (in particular, share it) in the same way as `/var/lib/containers/storage`.

Still, to me `short-name-aliases.conf` is an interactive, per-user choice, and _definitely not_ a file `root` manages to be consumed by all other users (that’s for `registries.conf.d` is for). I don’t have a good idea of what that means for `root`-owned non-interactive separate isolated services in the short term. Silently ignoring a failure to read configuration and falling back to search is not great either.

**Comment by rhatdan** [comment]
I think we should just not fail and not record the alias,  Just print a warning.
I have not heard of someone doing /root read/only before this.  I know of preventing root writing without DAC_OVERRIDE, but this seems a little more stringent.
Since storing the shortname in a directory is not required, it should just be a warning, if the process gets EPERM, EACCES, ENOSUP.

**Comment by mtrmac** [comment]
That would be fine, but this fails already when _reading_ the alias (and while it would probably be fine to read the alias file without locking and write access, silently ignoring the alias file on read failure doesn’t look OK).

**Comment by rhatdan** [comment]
Yes I would still want to read the file.  I don't think there is a race condition, to wait for on read access.

**Comment by mtrmac** [comment]
There could be a race condition with another process that _does_ have write access and is currently updating the file (the code currently does not do edit-in-temporary+rename, probably worth considering as a part of the fix). In that situation the parsing might fail, or it might not.

**Comment by rhatdan** [comment]
Yes I would like to remove lock and just do create temporary and rename.

**Comment by mtrmac** [comment]
The lock is still useful for concurrent writers so that we don’t lose data. Sure, allowing lock-free readers would be nice.

Still, that probably only gets us from “`mkdir` fails“ to “`read` fails”.

**Comment by rhatdan** [comment]
Sure, if you are expecting that kind of load. Hundreds of podmans running at the same time each one selecting a new image name?
CRI-O would never use this code, for writing.

**Comment by tinywrkb** [comment]
I want to make clear that the reason `/root` is immutable on my system is to catch bad behaved apps and scripts.  
Podman is shipped with a systemd service running with the root user, and I consider a systemd service that saves its state in `/root` is a badly behaved one.  
If you still keeping `short-name-aliases.conf.lock` in `HOME` and just making Podman fault-tolerant, then please change the systemd service to use a dedicated `podman` user with root permissions (for setting networks, and etc) and with `HOME` in `/var/lib/podman`.  
For my own needs, I just force `HOME=/var/lib/podman` in the systemd service.

**Comment by mtrmac** [comment]
This is a `podman generate`-created service? In that case, @vrothberg , future versions should _definitely_ generate a command that does not use short names at all. That wouldn’t solve the general problem class, but it’s the right thing to do anyway.

**Comment by vrothberg** [comment]
> This is a `podman generate`-created service? In that case, @vrothberg , future versions should _definitely_ generate a command that does not use short names at all. That wouldn’t solve the general problem class, but it’s the right thing to do anyway.

Can you elaborate on "does not use short names at all"?  It's entirely up to users to configure the short-names mode.

**Comment by vrothberg** [comment]
> Yes I would still want to read the file. I don't think there is a race condition, to wait for on read access.

There is a race condition as the file isn't written atomically.  Reading during a write would yield JSON errors.  We could turn it into a read-write lock but that should really be a separate issue.

Back to RO issue: In case we can't create the directory, do we agree to just log the error on stderr - assuming EPERM, EACCES, ENOSUP?

**Comment by vrothberg** [comment]
> We could turn it into a read-write lock but that should really be a separate issue.

Actually, we already account for that. Readers will always acquire the lock as a reader.

**Comment by rhatdan** [comment]
It should be at the Warn level, not an error. 
The question I have is why are we doing this if we don't intend to write content in /root in the first place.  Perhaps move the lock file out of the homedir, so we don't attempt to create content in the directory?

**Comment by mtrmac** [comment]
> > This is a `podman generate`-created service? In that case, @vrothberg , future versions should _definitely_ generate a command that does not use short names at all. That wouldn’t solve the general problem class, but it’s the right thing to do anyway.
> 
> Can you elaborate on "does not use short names at all"? It's entirely up to users to configure the short-names mode.

At generate time (when the command may be interactive), convert the short name into a long name, and write _that_ into the generated service so that any future changes in the configuration, environment or network will not affect the service.

**Comment by vrothberg** [comment]
> The question I have is why are we doing this if we don't intend to write content in /root in the first place. Perhaps move the lock file out of the homedir, so we don't attempt to create content in the directory?

I am not emotionally attached to `/root`. Using `/etc` for computer-generated files may not be the best place. Where else could we put it?

**Comment by mtrmac** [comment]
> > Yes I would still want to read the file. I don't think there is a race condition, to wait for on read access.
> 
> There is a race condition as the file isn't written atomically. Reading during a write would yield JSON errors. We could turn it into a read-write lock but that should really be a separate issue.

- Keep the lock for writes
- Actually do a temporary file + rename for updating the JSON file
- No lock needed, and no write access at all, is necessary for reading.

Note that all of this only ever makes a difference if the service is restricted from writing to `/root` but allowed to read from it. I don’t really think that is very likely — if SELinux or whatever is designed to protect `/root` from the service, why wouldn’t reading be allowed as well?

**Comment by mtrmac** [comment]
> Where else could we put it?

https://github.com/containers/podman/issues/8559#issuecomment-737865604 - there pretty much by definition isn’t any single place in this situation.

**Comment by vrothberg** [comment]
Note that we can also just continue using `/root` :laughing:  Just to not exclude this option.

**Comment by rhatdan** [comment]
Logical Choices would be /etc/containers/registries.conf.d/ or /root.  Anything else will add confusion.
I have no problem sticking with /root, but not failing hard, just warn the the file will not be saved.  This file is not critical to by use case.

**Comment by mtrmac** [comment]
@rhatdan We are not even _trying to save anything_ at this point. Changing the implementation of _saving_ is irrelevant, other than maybe (I am doubtful) allowing us to change the implementation of reading.

**Comment by yangm97** [comment]
Not sure if this helps but I've noticed this issue reproduces (consistently) on this:

```
/usr/bin/podman run \
--sdnotify=conmon \
--conmon-pidfile %t/yggdrasil.pid \
--cidfile %t/yggdrasil.ctr-id \
--cgroups=no-conmon \
-d \
--rm \
--log-driver=journald \
--device=/dev/net/tun \
--net=host \
--cap-add=NET_ADMIN \
--replace \
--name=yggdrasil \
--interactive \
-v /etc:/etc \
-v /var/run:/var/run \
yangm97/yggdrasil-go:latest -useconffile /etc/yggdrasil.conf
```

But not on this:

```
/usr/bin/podman run \
--conmon-pidfile %t/container-bla.pid \
--cidfile %t/container-bla.ctr-id \
--cgroups=no-conmon \
--detach \
--net=host \
--read-only \
--replace \
--sdnotify=conmon \
--log-driver=journald \
--label io.containers.autoupdate=image \
--privileged \
--name=bla \
--device=/dev/spidev1.0 \
--env-file=/home/bla/.env \
registry.bla.com/bla:dev
```

**Comment by rhatdan** [comment]
@vrothberg Since this involves Shortnames can you take a look?
