### ISSUE TITLE
Network fails on rootfull containers on Debian 10 (Buster)

### ISSUE THREAD

**Issue by pmakholm** [containers/podman#8568]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

With Debian 10 creating a rootfull container with a bridged network do not have access to the internet. Connections from host to the container works, but packets does not get forwarded and masqueraded to the hosts upstream interface.

Publishing ports fails explicitly with an error returned by iptables, but the setup of the bridged network seems to fail silently.

The default iptables implementation on Debian 10 is a wrapper around nftables. Changing to the iptables implementation to iptables-legacy (using the command 'update-alternatives --set iptables /usr/sbin/iptables-legacy') fixes the problem. I have not tried if using firewalld works as well.

Another untested alternative might be the nftables compatible CNI plugins at https://github.com/greenpau/cni-plugins

**Output of `podman version`:**

```
Version:      2.2.0
API Version:  2.1.0
Go Version:   go1.14
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 8
  distribution:
    distribution: debian
    version: "10"
  eventLogger: journald
  hostname: pmakholm
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 1214112
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 1214112
      size: 65536
  kernel: 4.9.0-11-amd64
  linkmode: dynamic
  memFree: 575799296
  memTotal: 33681797120
  ociRuntime:
    name: runc
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc10
      commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
      spec: 1.0.1-dev
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /home/pmakholm/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.1.7+dev
      commit: 0bac9946c0d556dfb38a8db09ea89d2b18feb559
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.3.3
  swapFree: 34093490176
  swapTotal: 34297868288
  uptime: 2067h 46m 18.33s (Approximately 86.12 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/pmakholm/.config/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 0
    stopped: 6
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/pmakholm/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 22
  runRoot: /run/user/1000/containers
  volumePath: /home/pmakholm/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.14
  OsArch: linux/amd64
  Version: 2.2.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 2.2.0~0.1+nmu3 amd64 [installed]
podman/unknown 2.2.0~0.1+nmu3 arm64
podman/unknown 2.2.0~0.1+nmu3 armhf
podman/unknown 2.2.0~0.1+nmu3 ppc64el
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
"Publishing ports fails explicitly with an error returned by iptables, but the setup of the bridged network seems to fail silently." - Any chance you can provide that error?

Also, for further details: do you have any firewall management software (e.g. firewalld, ufw) installed? Can you provide the output of `iptables -nvL` and `iptables -t nat -nvL` both with and without a Podman container running?

**Comment by mheon** [comment]
We should be 100% compatible with nftables-backed iptables out of the box - RHEL 8 ships this configuration by default, and Podman is fully supported there - so I am leaning towards an environment issue.

**Comment by rhatdan** [comment]
Since we believe this is not a podman issue, I am closing.
