### ISSUE TITLE
podman docker swagger mismatches

### ISSUE THREAD

**Issue by tmds** [containers/podman#8577]
I'm running podman 2.1.1 and tried using it with a client generated from vendor/github.com/docker/docker/api/swagger.yaml.

These differences came up:

Command is not a string, but an array of strings.
```
        "Command": [
            "/bin/bash"
        ],
```

ports don't contain required PrivatePort and Type:
```
        "Ports": [
            {
                "hostPort": 3000,
                "containerPort": 3000,
                "protocol": "tcp",
                "hostIP": ""
            }
```

mounts is not an array of type Mount, but of strings.
```
        "Mounts": [
            "/root"
        ],
```

**Comment by tmds** [comment]
I'm using `/containers/json` on `systemctl` `--user` `podman.socket`.

I'm using the docker swagger file. I tried using the https://storage.googleapis.com/libpod-master-releases/swagger-latest-master.yaml but the tool I'm using has an issue with it.

**Comment by mheon** [comment]
@baude @jwhonce PTAL

**Comment by jwhonce** [comment]
@tmds Which tool are you using? We've put a lot of work in the swagger  support and I am sorry to hear you are having issues.

**Comment by tmds** [comment]
@jwhonce I'm using NSwag to generate a C# client. It may be a limitation of the tool, rather than an issue with the podman swagger file. I'll cc you on the issue in the NSwag repo.

**Comment by tmds** [comment]
@jwhonce this is what I need to change to the swagger file to make NSwag happy:
```diff
diff --git a/swagger-latest-master.yaml b/swagger-latest-master.yaml
index d9b199f..1891a02 100644
--- a/swagger-latest-master.yaml
+++ b/swagger-latest-master.yaml
@@ -10300,7 +10300,8 @@ paths:
       - application/json
       responses:
         "200":
-          $ref: '#/definitions/IDResponse'
+          schema:
+            $ref: '#/definitions/IDResponse'
         "400":
           $ref: '#/responses/BadParamError'
         "404":
@@ -10329,7 +10330,8 @@ paths:
       - application/json
       responses:
         "200":
-          $ref: '#/definitions/IDResponse'
+          schema:
+            $ref: '#/definitions/IDResponse'
         "404":
           $ref: '#/responses/NoSuchManifest'
         "409":
@@ -10383,7 +10385,8 @@ paths:
       - application/json
       responses:
         "200":
-          $ref: '#/definitions/IDResponse'
+          schema:
+            $ref: '#/definitions/IDResponse'
         "400":
           $ref: '#/responses/BadParamError'
         "404":
@@ -10415,7 +10418,8 @@ paths:
       - application/json
       responses:
         "200":
-          $ref: '#/definitions/IDResponse'
+          schema:
+            $ref: '#/definitions/IDResponse'
         "400":
           $ref: '#/responses/BadParamError'
         "404":
@@ -10811,7 +10815,8 @@ paths:
       - application/json
       responses:
         "200":
-          $ref: '#/definitions/IdResponse'
+          schema:
+            $ref: '#/definitions/IdResponse'
         "400":
           $ref: '#/responses/BadParamError'
         "500":

```

**Comment by tmds** [comment]
`IdResponse` is also used with the `schema` in the docker swagger file.

Note: the podman swagger has both a `IdResponse` and `IDResponse`definition.

**Comment by jwhonce** [comment]
@tmds Thanks for the details!

**Comment by tmds** [comment]
@jwhonce another issue the tool has with podman swagger:
```
  /images/{name:.*}:
    delete:
      description: Delete an image from local storage
      operationId: removeImage
      parameters:
      - description: name or ID of image to delete
        in: path
        name: name:.*
        required: true
        type: string
```
What is this `:.*` for?

**Comment by tmds** [comment]
I'm trying to use the API to do the same things as the Docker API _Run a container_ example: https://docs.docker.com/engine/api/sdk/examples/#run-a-container

I'm running into these issues with the podman swagger:
- ContainerCreate is missing the body parameter
- ContainerWait seems to accept different values for condition
- ContainerLogs doesn't have a response 200 return type

And, for the tool to pick up the type names I need to move the `title` properties under the schema (like it is in the docker swagger file). For example:
```diff
@@ -11392,8 +11392,8 @@ responses:
       type: object
   ContainerCreateResponse:
     description: Create container
-    title: "ContainerCreateResponse"
     schema:
+      title: "ContainerCreateResponse"
       properties:
         Id:
           description: ID of the container created
```

**Comment by tmds** [comment]
The `operationId` gets used by code generators (as mentioned in the swagger spec). It would be nice if these would match between docker swagger and podman swagger. Currently these ids are different.

**Comment by rhatdan** [comment]
@tmds Could you open a PR with podman to make the changes you want.  That would make this go through a lot faster then relying on other engineers to work the PR.
Thanks.

**Comment by tmds** [comment]
@rhatdan how does the swagger get generated? Is it from the comments in the code, like this one?

https://github.com/containers/podman/blob/3fcf346890c0437611fc18c30d58cc2d9f61fe6c/pkg/api/server/register_containers.go#L12-L34

**Comment by baude** [comment]
yup

**Comment by tmds** [comment]
@baude does this comment 

https://github.com/containers/podman/blob/c3b39842ce76e3e3bfc843abfebeeb603f04591d/pkg/api/handlers/compat/swagger.go#L9-L16

cause generation of:

```yaml
  ContainerCreateResponse:
    description: Create container
    schema:
      properties:
        Id:
          description: ID of the container created
          type: string
          x-go-name: ID
        Warnings:
          description: Warnings during container creation
          items:
            type: string
          type: array
      type: object
```
What would be a way to add a `title: ContainerCreateResponse` for such types under the `schema` property?

**Comment by tmds** [comment]
@baude see my previous question: What generates the swagger for these types? And can we make it include a `title` property?

**Comment by baude** [comment]
@jwhonce ptal

**Comment by tmds** [comment]
> What generates the swagger for these types? And can we make it include a title property?

ping @jwhonce

**Comment by tmds** [comment]
@jwhonce @mheon @baude my requests here and https://github.com/containers/podman/pull/9126, https://github.com/containers/podman/pull/9123, https://github.com/containers/podman/pull/9121 have been idle for a few weeks. Can you take a look? I think these are real issues when using the podman swagger file.

**Comment by tmds** [comment]
The REST API may be usable, but the swagger needs love.

I'm going to try use the docker swagger file instead.

**Comment by tmds** [comment]
@jwhonce thanks for working on this issue past week! The only thing stopping me now from using the podman swagger is https://github.com/containers/podman/pull/9126.
In particular:
- the missing parameter for the build context on the build image command, and
- the missing parameter for configuration on the create container command.

**Comment by vrothberg** [comment]
@jwhonce are we good?

**Comment by jwhonce** [comment]
> swagger:response

@tmds The go-swagger tool currently does not allow us to set the title key on responses.

**Comment by jwhonce** [comment]
> `IdResponse` is also used with the `schema` in the docker swagger file.
> 
> Note: the podman swagger has both a `IdResponse` and `IDResponse`definition.

go-swagger picks up IdResponse from vendor'ed code. I changed all our definitions to use IDResponse.
