### ISSUE TITLE
[APIv2] /images/load implementation is wrong

### ISSUE THREAD

**Issue by jwhonce** [containers/podman#8586]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Endpoint should honor https://docs.docker.com/engine/api/v1.40/#operation/ImageLoad API

**Output of `podman version`:**

```
podman 2.2.0
```

**Comment by rhatdan** [comment]
@jwhonce Is this fixed in the main branch now?  Can we close this PR?

**Comment by rhatdan** [comment]
I am going to say yes, reopen if I am mistaken.
