### ISSUE TITLE
`podman commit` fails when --userns, --uidmap, or --gidmap specified 

### ISSUE THREAD

**Issue by codementation** [containers/podman#8602]
**Kind**
bug

**Description**

When committing changes to a running container started with a a specified namespace using --uidmap, --gidmap, or --userns the command fails with the error:
```
Error: error copying layers and metadata for container <CONTAINER_ID>":
Error initializing source containers-storage:<CONTAINER-NAME>: 
unable to look up size of layer "<STORAGE_ID>"
```

**Steps to reproduce the issue:**
1. Run a container specifying a namespace using --uidmap, --gidmap, or --userns
2. Attempt to commit said image

**Rootless:**
```
podman run -it --rm --userns=keep-id --name test alpine
```

```
podman commit test test

Error: error copying layers and metadata for container
"46ec4dd4a4c0213ff8baf2e589199ddc2263a1efdd71ec85f2102f8fbe5eee9b": 
Error initializing source containers-storage:test: 
unable to look up size of layer
"1c1809d86870c4b3c20557351fe3fb43d6fd803b7d643066ebf62adb0c8f0290"
```
**Describe the results you received:**

**Rootfull:**
```
sudo podman run -it --rm --uidmap 0:0:999999 --name test alpine
```

```
sudo podman commit test test

Error: error copying layers and metadata for container
"3133e52bdc717a2327e8c921686174fc4997006e86fc9652bb83ae3e44e8b068": 
Error initializing source containers-storage:test: unable to look up size of layer
"f45690e905efebc8d849b3f844e412941870be561101a0b3f1d9cfb7a075bb04"
```

**Without specifying a namespace works fine:**
```
podman run -it --rm --name test alpine
```

```
podman commit test test
Getting image source signatures
Copying blob ace0eda3e3be skipped: already exists
Copying blob a7686bbd68ad done
Copying config e8c4f168b5 done
Writing manifest to image destination
Storing signatures
e8c4f168b5562ee2a7418251dee06df3028b74d7c03fe4ab5d95c6fb31852303
```

**Describe the results you expected:**

The container to successfullly commit when running in a namespace

**Additional information you deem important**

I need to specify a namespace to be able to write to mounted volumes, and sometimes it's necessary to commit changes made to running containers without rebuilding from scratch.

I searched the issue history and documentation but did not turn up anything.  If this is expected behavior it would be great to know the underlying reason and posible workaround. 

The storage driver is **btrfs**
I've tried turning off the index for the overlayfs driver 
```
[storage.options.overlay] 
index=off
```
 

**Output of `podman version`:**

```
podman version
Version:      2.2.0
API Version:  2.1.0
Go Version:   go1.15.5
Git Commit:   db1d2ff111ee9b012779ff3a5279a982520ccda4
Built:        Tue Dec  1 16:59:35 2020
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 35a2fa83022e56e18af7e6a865ba5d7165fa2a4a'
  cpus: 4
  distribution:
    distribution: artix
    version: unknown
  eventLogger: file
  hostname: myhost
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.9.2-artix1-1
  linkmode: dynamic
  memFree: 4004855808
  memTotal: 33612644352
  ociRuntime:
    name: crun
    package: Unknown
    path: /usr/bin/crun
    version: |-
      crun version 0.15.1
      commit: eb0145e5ad4d8207e84a327248af76663d4e50dd
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 4265123840
  swapTotal: 4294963200
  uptime: 298h 16m 17.39s (Approximately 12.42 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 6
    stopped: 0
  graphDriverName: btrfs
  graphOptions: {}
  graphRoot: /mnt/cryptotank/containers/storage/user/graphroot
  graphStatus:
    Build Version: 'Btrfs v5.9 '
    Library Version: "102"
  imageStore:
    number: 314
  runRoot: /mnt/cryptotank/containers/storage/user/runroot
  volumePath: /mnt/cryptotank/containers/storage/user/graphroot/volumes
version:
  APIVersion: 2.1.0
  Built: 1606863575
  BuiltTime: Tue Dec  1 16:59:35 2020
  GitCommit: db1d2ff111ee9b012779ff3a5279a982520ccda4
  GoVersion: go1.15.5
  OsArch: linux/amd64
  Version: 2.2.0
```

**Package info**

```
pacman -Qi podman
Name            : podman
Version         : 2.2.0-1
Description     : Tool and library for running OCI-based containers in pods
Architecture    : x86_64
URL             : https://github.com/containers/libpod
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : cni-plugins  conmon  containers-common  device-mapper  iptables  libseccomp
                  runc  slirp4netns  libsystemd  fuse-overlayfs  libgpgme.so=11-64
Optional Deps   : podman-docker: for Docker-compatible CLI
                  btrfs-progs: support btrfs backend devices [installed]
                  catatonit: --init flag support
                  crun: support for unified cgroupsv2 [installed]
Required By     : ansible-bender
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 79.02 MiB
Packager        : Morten Linderud <foxboron@archlinux.org>
Build Date      : Tue 01 Dec 2020 04:59:35 PM CST
Install Date    : Thu 03 Dec 2020 07:12:33 PM CST
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical

**Thank you!**

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
could you confirm it works with overlay?

The btrfs storage driver is not as stable and widely used as overlay.

**Comment by rhatdan** [comment]
Since we have had no response, I am going to close this issue.  Reopen if more information is to be provided.

**Comment by yuckster** [comment]
I can confirm this does not work with overlay:

Error: error copying layers and metadata for container "047c2f8b4702bc5bf5dee497db0172131ff6a1a8bf3ce70309e3e24d89e07747": Error initializing source containers-storage:company-wordpress: unable to look up size of layer "d35e2fdeb713e8779a404b23600553dc68553657d292ed0597991be59face74e"


**podman info --debug**
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.20-2.module_el8.3.0+475+c50ce30b.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.20, commit: 1019ecdeda3936be22162bb1cca308192145de53'
  cpus: 1
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: journald
  hostname: www2.autarch.co
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-193.6.3.el8_2.x86_64
  linkmode: dynamic
  memFree: 172204032
  memTotal: 2972803072
  ociRuntime:
    name: runc
    package: runc-1.0.0-68.rc92.module_el8.3.0+475+c50ce30b.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 4372h 7m 50.04s (Approximately 182.17 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 3
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 6
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1610243993
  BuiltTime: Sun Jan 10 01:59:53 2021
  GitCommit: ""
  GoVersion: go1.14.12
  OsArch: linux/amd64
  Version: 2.2.1
