### ISSUE TITLE
[Question] Best practice for triggering auto-update command?

### ISSUE THREAD

**Issue by seanybaggins** [containers/podman#8605]
I followed the blog post [here](https://www.redhat.com/sysadmin/improved-systemd-podman) to create the services needed for auto-update command.

The blog says "Updates are triggered via a `systemd timer` or external triggers running `podman auto-update`. For more details, please refer to the [upstream documentation](https://github.com/containers/podman/blob/v2.0/docs/source/markdown/podman-auto-update.1.md)" but the upstream documentation does not have much detail on `systemd timers`or external triggers running `podman auto-update`.

Is there a suggested systemd timer configuration that I can pull off the shelf? Is it worth seeing if podman can generate the timer to call `podman auto-update` as well as the services?

**Comment by mheon** [comment]
@vrothberg PTAL

**Comment by vrothberg** [comment]
Thanks for reaching out, @seanybaggins!

We maintain a Systemd service-timer pair upstream: https://github.com/containers/podman/tree/master/contrib/systemd/auto-update. They're both shipped in Fedora and RHEL, and possibly more Linux distributions.

The service-timer pair covers time-based triggers (i.e, the timer) but also event and dependency-based triggers via the service such that other Systemd services can trigger or depend on it.  Other (custom) use cases can be covered by calling `podman auto-update` directly.

Does that address your use case?

**Comment by seanybaggins** [comment]
Yes. The link you provided is great. It would be nice if documentation mentioned these in some way.

**Comment by vrothberg** [comment]
> Yes. The link you provided is great. It would be nice if documentation mentioned these in some way.

:+1: thanks for the feedback.  I added that to my todo list.

**Comment by vrothberg** [comment]
Opened #8655

**Comment by elgorro** [comment]
On Ubuntu 20.10 with Podman 2.0.6 I installed Auto-Update Containers (the systemend unit creation is fine), but triggering the auto-update doesn't work.
The `podman-auto-update.service` and `podman-auto-update.timer` Systemd-Units are not present (http://docs.podman.io/en/latest/markdown/podman-auto-update.1.html#systemd-unit-and-timer).
So got a error when I run `podman auto-update`: error auto-updating container "<guid>": no PODMAN_SYSTEMD_UNIT label found !
Am I missing something or is this an issue?

**Comment by vrothberg** [comment]
Thanks for reaching out @elgorro!

This looks like something that should be filed against Ubuntu. @siretart PTAL

**Comment by siretart** [comment]
Thanks for pointing this out. Sorry, I missed this item for too long, it might have helped to file it to the debian bugtracker.

I've just uploaded a change that includes these systemd units to unstable as `libpod_2.1.1+dfsg1-5`

**Comment by elgorro** [comment]
@siretart May due hard work on version 3, possible you forget to launch on Ubuntu/Stable? Is CentOS better supported?

**Comment by siretart** [comment]
I'm not sure what your expectations are, but may I suggest to try out ubuntu groovy and see if that works for you?

As for earlier releases, there are rather strict guidelines on what kind of changes are acceptable, and all of them start with having a bug in the ubuntu big tracker. I'd suggest we continue this conversation there.

**Comment by elgorro** [comment]
@siretart I'm on Groovy, but still the same since January!
>On Ubuntu 20.10 with Podman 2.0.6 I installed Auto-Update Containers (the systemend unit creation is fine), but triggering the auto-update doesn't work.

Double checked: https://launchpad.net/ubuntu/+source/libpod.
Also in your PPA (ppa:siretart/podman) for Podman is no libpod at all.
All I see is that the project is more up-to-date here https://github.com/containers/podman/releases
I'm not getting your point of multiple discussions over divers bug-trackers.

**Comment by siretart** [comment]
Apologies, i meant to write hirsute, not groovy. One those packages are confirmed working, I can look into updating my ppa.
