### ISSUE TITLE
Documentation on how to nuke podman from space

### ISSUE THREAD

**Issue by daveman1010221** [containers/podman#8612]
/kind feature

**Description**
Podman is incredibly fragile but I've come to rely on it. Fixing it is impossible, as 'podman system reset' never works, even if I delete everything I can possibly find to delete first and uninstall and reinstall it. (always says "Error registering shutdown handler for libpod: handler with name libpod already exists") I've spent entirely too many hours trying to get podman working again. It would be helpful to just have the documented procedure for how to nuke podman from space, get rid of all errors, and start over. Thanks.

**Comment by mheon** [comment]
When you run any Podman command (except `podman version`) with `--log-level=debug` set, it will print information on the paths it is using. Specifically:
```
DEBU[0000] Using graph root ...
DEBU[0000] Using run root ...
DEBU[0000] Using static dir ...
DEBU[0000] Using tmp dir ... 
```

All that `system reset` is doing doing, fundamentally, is removing those four directories (it will try to stop and unmount any running containers/pods first, which is necessary for removal as some resources in said directories will be in use and unable to be removed).

I would definitely appreciate more information on the fragile parts of Podman you're seeing, though (I'm 99% sure I already know what the `system reset` issue is, and it should be fixed for 2.2.1).

**Comment by mheon** [comment]
For now, I would recommend going back to v2.1.1 until v2.2.1 is released. There were a number of serious issues with 2.2.0 that were not caught by testing, and we'll be getting 2.2.1 out (likely sometime on Monday) to address them.

**Comment by rhatdan** [comment]
V2.2.1 has been released.  Reopen if this does not fix your issue.
