### ISSUE TITLE
Breaking Change in Container Config will cause JSON Decode Failures with Older Containers

### ISSUE THREAD

**Issue by mheon** [containers/podman#8613]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

In the very old, pre-1.0 days before Libpod had proper named volume support, we emulated image volumes using bind mounts or tmpfs mounts. Part of this support involved a field in container configuration, `ImageVolumes` (type string), that determined whether we were using a tmpfs or bind mount. Libpod eventually grew support for named volumes, and the field was deprecated and became unused. I removed it in Podman 1.8 with https://github.com/containers/podman/commit/e3a549b7b1191a1667373cf60f8d08b96bbce7ba.

@vrothberg recently added a new, completely separate feature, where images can be mounted into containers as volumes (e.g. for security inspection). This again adds an `ImageVolumes` field (https://github.com/containers/podman/blob/master/libpod/container_config.go#L138) but now with a different struct type. These are completely incompatible in JSON terms and means that any containers created with Podman < 1.8.0 will be completely unusable with Podman 2.2.0.

**Steps to reproduce the issue:**

1. Check out and build Podman 1.6.4 (any pre-1.8 will work, but we still support 1.6.4 in RHEL).

2. Create a container (`podman create`, `podman run`, doesn't really matter.

3. Upgrade to Podman 2.2.0 and run `podman ps`

**Describe the results you received:**

Podman will not be able to read the container from the database due to a JSON decode error

**Describe the results you expected:**

Podman works as expected

**Additional information you deem important (e.g. issue happens only occasionally):**

The old `ImageVolumes` was not `omitempty`, so every container pre-removal is guaranteed to have it.

**Comment by mheon** [comment]
@rhatdan @vrothberg @baude PTAL, this is a bad one. Going to be interesting trying to resolve this without breaking 2.2.0 containers - we may have to rename the JSON field for the new image volumes and accept that any container made on 2.2.0 with image volumes will not have them after upgrade to 2.2.1.

**Comment by vrothberg** [comment]
Ewwww that's an ugly one. To summarize:

* There was an `imageVolumes` field earlier of type FOO which was eventually removed.
* Podman 2.2 added an `imageVolumes` field of type BAR (not knowing/forgetting that FOO ever existed).

Containers created with FOO will know break with 2.2 was Podman expects it to be BAR.

As we cannot change the past, I suggest to rename the field and drop a HUGE comment at the top-level struct to never ever use that name again.

**Comment by mheon** [comment]
Concur.

**Comment by rhatdan** [comment]
SGTM

**Comment by TomSweeneyRedHat** [comment]
@mheon, in the release notes, please include something like @vrothberg 's summary.
