### ISSUE TITLE
Unmarshalling error, can not remove container

### ISSUE THREAD

**Issue by WittyNameHere** [containers/podman#8618]
kind/bug

Briefly describe the problem you are having:

$ sudo podman rm nextcloud
Error: error unmarshalling container 1718cbba8ae35c6e838f3d84f61e5d22d85c95b562727308424b4bc811fee73d config: libpod.ContainerConfig.ContainerRootFSConfig: ImageVolumes: []*libpod.ContainerImageVolume: decode slice: expect [ or n, but found t, error found in #10 byte of ...|Volumes":true,"ShmDi|..., bigger context ...|.io/linuxserver/nextcloud:latest","imageVolumes":true,"ShmDir":"/var/lib/containers/storage/overlay-|...

That's what I get trying to perform many operations in podman (including ps, auto-update, etc). I'm using CentOS 8 up to date and the latest release of Podman from the project's repo, but I think this container and two others that produce similar errors were all made using the older version of Podman that is included with CentOS. I haven't tried going backwards to the older version because I am novice to intermediate in Linux sysadmin tasks and don't know how to reverse versions safely.

**Comment by mheon** [comment]
You are seeing #8613 - please revert to Podman 2.1.1 until Podman
2.2.1 can be released with a fix.

**Comment by WittyNameHere** [comment]
Understood. Kubic's repo doesn't have 2.1.1, so if acceptable I'll just deal with seeing error messages during certain tasks. They don't refer to any containers I currently use.

**Comment by mheon** [comment]
`podman rm --force` should also be able to forcibly remove the containers even if they cannot be decoded properly

**Comment by rhatdan** [comment]
I agree, But I think there might be issues down in containers/storage.

**Comment by vrothberg** [comment]
Closing as it's fixed now.
