### ISSUE TITLE
podman wait -i has confusing documentation about its behaviour

### ISSUE THREAD

**Issue by zem** [containers/podman#8619]
With a recent podman 2.1.1 I got confusing information about podman wait -i

The podman-wait manpage shows: 

```       --interval, -i=microseconds
         Microseconds to wait before polling for completion
```

while podman wait --help shows: 

```
  -i, --interval duration   Milliseconds to wait before polling for completion (default 250ns)
```

together with an example: 

```
Examples:
  podman wait --interval 5000 ctrID
```

lets try this example: 

```
# podman wait --interval 5000 gitlab_gitlab
Error: invalid argument "5000" for "-i, --interval" flag: time: missing unit in duration 5000
```

So the first documentation says it wants microseconds the second says it wants milliseconds and then it does not work without units at all, except that the only provided example says it should. After this the user can't be sure if the 250ns are correct. 

It looks like `podman wait --interval 5s gitlab_gitlab` is giving some result so please document the right behaviour.

**Comment by rhatdan** [comment]
In podman 2.2 this is fixed.
```
man podman wait ...
...
   --interval, -i=duration
       Time interval to wait before polling for completion. A duration string is a sequence of decimal numbers, each with optional fraction and a  unit  suffix,  such  as  "300ms",  "-1.5h"  or
       "2h45m". Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h". Time unit defaults to "ms".
```
https://github.com/containers/podman/pull/8093
