### ISSUE TITLE
Add a way to disable progress-meters

### ISSUE THREAD

**Issue by Jakuje** [containers/podman#8626]
/kind feature

**Description**

I run podman from time to time in automated environment, which logs output and does not allow to update progressmeter as podman would like to, resulting in hundreds or thousands of lines of `…` or `Copying blob 9c4cf6c2176d  7.4KiB / 87.1MiB` messages, depending on the size of image, speed of connection and version of `podman`.

**Steps to reproduce the issue:**

1. Run `podman pull` in script with output passed to a file

**Describe the results you received:**

Many repeated lines with
```
Copying blob 9c4cf6c2176d  7.4KiB / 87.1MiB
Copying blob 4ca77ff8a54a  1.5KiB / 1.5KiB


Copying blob 9c4cf6c2176d  31.4KiB / 87.1MiB
Copying blob 4ca77ff8a54a done
```
(older podman)

or just with
```
…  
…  
```
(newer podman)

**Describe the results you expected:**

I would like to have either an option to disable progress bar (through a commandline, environment variable, whatever) or for podman to detect if it can actually use the progress meter to something useful and if not, do not attempt to do that.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

all

**Output of `podman info --debug`:**

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

All

**Comment by vrothberg** [comment]
Thanks for reaching out!

You can use the `--quiet` flag on the CLI to disable the pull/push logs.

**Comment by Jakuje** [comment]
Thank you very much for the fast reply. I am not sure how I missed this. Works fine!
