### ISSUE TITLE
Publishing more than one port range with automatically assigned ports leads to port mapping conflict

### ISSUE THREAD

**Issue by znerol** [containers/podman#8651]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Using the `--publish` flag it is possible to either specify the host port range explicitly or omit it. In the latter case the container runtime will allocate a random port range. If multiple `--publish` flags are used with multiple port ranges with host port range omitted, the container fails to start.

**Steps to reproduce the issue:**

1. Run a container and specify more than one port range without explicit host port range mapping.
    ```
    podman run --rm --publish 3000-3001 --publish 4000-4001 k8s.gcr.io/pause
    ```

**Describe the results you received:**

```
Error: conflicting port mappings for host port 1 (protocol tcp)
```

**Describe the results you expected:**

Container starting with two random host port ranges allocated to the container port ranges.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Reproducible with both 2.2.1 and master branch

```
podman version
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.14
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

```
./bin/podman version
Version:      3.0.0-dev
API Version:  3.0.0
Go Version:   go1.14.10
Git Commit:   47d2a4be2af5143c9619a65ec641daa1025130a3
Built:        Tue Dec  8 21:47:44 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

Very likely not relevant.

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

compiled from source and installed from [kubic](https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman)

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
I think #8652 will also fix this one, let me add a test
