### ISSUE TITLE
`podman system prune` should report the reclaimed space

### ISSUE THREAD

**Issue by bugaevc** [containers/podman#8658]
/kind feature

**Description**

`docker system prune` reports the reclaimed space at the end:

```
$ docker system prune
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all dangling images
  - all dangling build cache

Are you sure you want to continue? [y/N] y
Deleted Containers:
8fcb38ea15ef170c327369012e1d4c4d112f5b046f72903a334351a42b869317

Deleted Images:

deleted: sha256:418ac6a457a2544bfb1bbe9046f002fed3ee4bc1adfd1f3c4c8d45ec373fa8ac
deleted: sha256:ea8ef451b04d7a1e0019635b35bddcfe9be370eb92d952ac92a960d53ef746db
deleted: sha256:ef1dfae27b2770b314dea312dd9ed0fcf2e8bd660218c04c20f0461263c51662
deleted: sha256:740ccc93eab3e4cdd9de3eca878800a9e1f0690f2159adb40c68b7dbba5edd2e
deleted: sha256:aba0e78044385bf12a7eea4d5398bc52c1a783cb792807f4fb9dbb56e2617c1d
deleted: sha256:1e9e09fdf99a8eaba56092093bf8966b8cddcbaf8829fae9a219e9a2ff581b24
deleted: sha256:f6149cf35f6e7b18e122595f0d5392d128f92e7a8cfc17bded48126671f1e2c7
deleted: sha256:d7df63b29760f856fa577d5ca79558cce6f073d415524bd3365aedbcb41eb52f
deleted: sha256:4244afa8d27d5c13d14a4db204de8b57c67a865455d231317db67d9945ddf36b
<...snip...>
deleted: sha256:bd9f4f01725d96a1e37beb4cbf21d24c8dc9e0dafb44aac23b8b9895418c6d9a
deleted: sha256:a0ec0d50c85f08dabb61d7e5f0a9e1b0e90418e0483cb2cd90223f44d7430dfb

Total reclaimed space: 1.216GB
```

But `podman system prune` doesn't seem output the same info.

**Comment by bblenard** [comment]
I poked at this for a little bit and got something maybe working (at least for reclaimed space for images) but I'm not sure on all of the specific requirements for this feature / if the maintainers want this.

![reclaimed_size_output](https://user-images.githubusercontent.com/15173997/102030370-30db9980-3d78-11eb-8957-c77935357ccb.png)

I can open a PR after I clean up the code more but I would want to know more of the specific requirements such as:

- What should the `relaimed space` metric include exactly? Images, Volumes, etc?
- How should the data be presented. Currently prune reports seem to have a `Size: ` output but it seems to be unformatted and just a byte count
- Is it okay for the Podman project to pull in dependencies such as [go-units](https://github.com/docker/go-units) from docker if the maintainers want human readable output.

**Comment by rhatdan** [comment]
Reclaimed space should be from containers/images and volumes.
It should be displayed in Human sizes.  go-units is already imported, so that is not a problem.

Thanks for working on this.

**Comment by bblenard** [comment]
@bugaevc I haven't forgotten about this issue. I'm currently trying to wrap up a different PR so I haven't been focusing on this, but I plan to.

**Comment by bblenard** [comment]
Made some decent progress on this. Not exactly sure the best way to test these changes and I might want to cleanup some of the prune helper functions that are no longer very useful.

![progress](https://user-images.githubusercontent.com/15173997/103107284-97906b00-4634-11eb-98d6-1d8b94c89fbc.png)

**Comment by rhatdan** [comment]
Looks great.

**Comment by bblenard** [comment]
@bugaevc PR opened and ready for review from Podman people: https://github.com/containers/podman/pull/8831
