### ISSUE TITLE
How to install podman by itself binares ?

### ISSUE THREAD

**Issue by oldthreefeng** [containers/podman#8660]
Is there any official binaries registry for podman?

**Comment by Luap99** [comment]
Install instructions can be found here: https://podman.io/getting-started/installation

**Comment by zhangguanzhang** [comment]
> Install instructions can be found here: https://podman.io/getting-started/installation

What he means is to directly copy the relevant binary files for installation without the system's own package management

**Comment by mheon** [comment]
It's very difficult to install Podman proper without packages due to the number of binaries involved - Podman, Conmon, the CNI plugins (for root), slirp4netns and fuse-overlayfs (rootless) would be the minimum install.

**Comment by oldthreefeng** [comment]
nothing is difficult if you have a  great makefile !

**Comment by rhatdan** [comment]
Don't forget runc/crun for an oci runtime.

**Comment by rhatdan** [comment]
Sure if you want to suck out about 7 different git repositories and build all of these different tools, then create config for the tool, which usually comes from containers-common.

**Comment by zhangguanzhang** [comment]
maybe useful from https://github.com/containers/podman/issues/8788

**Comment by afbjorklund** [comment]
> Sure if you want to suck out about 7 different git repositories and build all of these different tools, then create config for the tool, which usually comes from containers-common.

This is what cri-o is doing at the moment.

**Comment by oldthreefeng** [comment]
@afbjorklund  great job!!

**Comment by afbjorklund** [comment]
> great job!!

I'm not super-convinced myself that fully static binaries is the way to go, just pointing out that there _are_ already the Nix binaries...

It also lacks documentation, on how to install and use these static binaries ? I don't think CRI-O is doing a great job of that, either.

Personally, I prefer "sudo yum install podman".

But static binaries comes in handy too, sometimes.

**Comment by willzhang** [comment]
i'd like to offline install podman, but it's impossible if i have no apt or yum repo

**Comment by rhatdan** [comment]
You can build it locally.

**Comment by willzhang** [comment]
> You can build it locally.

ok , i'd like choose apt or yum , i'm so lazy, lol
