### ISSUE TITLE
How to backup volumes? 

### ISSUE THREAD

**Issue by topas-rec** [containers/podman#8662]
/kind feature

**Description**
I want to update the image of a rootless container running as non root which has a volume with persistent data attached to it. 
For the update I can remove the container and start another one with the same options as the removed one and using the newer image with it. 

This process (update process inside the container) can fail and might have already altered the data in the attached volume.
I could then revert to the previous image by creating a container with the previous image and the mentioned volume. When using the previous image again the volume then might not work with the previous image because it was already altered during the update process.

How can I keep a copy of a volume that I can restore when the volume got broken (somehow,  perhaps through updating the image)? 

Possible solutions:

1. There is the `checkpoint` command, that doesn't already work with rootless containers.
2. I can copy the contents of that volume to the host using the `cp` command (how does restoring work? Create an empty volume, mount it to a hello world container, copy the data back in that volume and attache it to the real container?)
3. I can copy the volume in podman storage to another place (How does restoring work? Replace that volume on disk? Can podman handle that?)
4. ???

Which solution should I use?
Is there an intended way to do this?

**Comment by mheon** [comment]
We'd like to eventually support a `podman volume mount` / `podman volume unmount` command pair that would allow you to do what you're looking at. For now, for volumes that do not require mounting (not backed by NFS or similar), you can `podman inspect` the volume to find its Mountpoint - that is the location of all data in the volume, which will allow you to back it up. Restoring is trickier; best bet is to re-create the volume using `podman volume create`, inspect to find Mountpoint, and copy contents to that directory.

**Comment by topas-rec** [comment]
> We'd like to eventually support a `podman volume mount` / `podman volume unmount` command pair that would allow you to do what you're looking at. For now, for volumes that do not require mounting (not backed by NFS or similar), you can `podman inspect` the volume to find its Mountpoint - that is the location of all data in the volume, which will allow you to back it up. Restoring is trickier; best bet is to re-create the volume using `podman volume create`, inspect to find Mountpoint, and copy contents to that directory.

I tried this and it worked. Thanks @mheon.

Note to myself and others: This should be noted in the docs.

So for me this is close. I like the solution. When there are diferent suggestions for backing up volumes please leave a comment.

**Comment by rhatdan** [comment]
Any chance you want to document the procedure in the podman volume man page?

**Comment by topas-rec** [comment]
Yes, this one is on the list together with one or two other things I found during my podman discovery. (Like issue 6123 (don't want to link it here))
