### ISSUE TITLE
All podman (root and rootless) commands result in "podman: symbol lookup error: podman: undefined symbol: seccomp_api_get"

### ISSUE THREAD

**Issue by usury** [containers/podman#8665]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

_Evey_ podman command (even "podman --version" and "podman info --log-level=debug") results in
```
root@containerhost:~ # podman --version
podman: symbol lookup error: podman: undefined symbol: seccomp_api_get
```

**The error occurs as both root and as regular user**

Just updated yesterday to podman v2.2.1~2
Also, "libseccomp" is the latest available version in standard Debian and OpenSuse repos (see below)

```
root@containerhost:~ # dpkg -l |grep podman
ii  podman                                2.2.1~2 

root@containerhost:~ # dpkg -l |grep libseccomp
ii  libseccomp2:amd64                     2.3.3-4
```

Containerhost is a Debian VM
Podman package comes from "opensuse" repo (as is the case for https://github.com/containers/podman/issues/8647)
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/

**Describe the results you received:**
Failure to do anything with podman

**Describe the results you expected:**
Ability to do all pre-upgrade things with podman

**Additional information you deem important (e.g. issue happens only occasionally):**
100% repeatable

**Output of `podman version`:**
_not possible_

**Output of `podman info --debug`:**
_not possible_

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
root@containerhost:~ # apt list podman
Listing... Done
podman/unknown,now 2.2.1~2 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Container host is a virtual machine running Debian 10 (Buster) on a Fedora 32 host

**Comment by mheon** [comment]
The symbol in question is only available in `libseccomp` v2.4.0 and higher, so this is unsurprising... I am curious as to what's going on in OBS such that we're building against a Libseccomp not in Debian stable.

@lsm5 We don't package libseccomp ourselves in OBS right?

**Comment by usury** [comment]
I should mention my Debian 10 (Buster) install uses the customary standard Debian repos _**as well as**_ one additional repo from OpenSuse for podman packages (since podman doesn't seem to be available in the standard ones). I've been under the impression that using the OpenSuse repo is the accepted way of making podman available on Debian (and Ubuntu) installs.

```
root@containerhost:~ # cat /etc/apt/sources.list.d/devel\:kubic\:libcontainers\:stable.list
## "Kubric" repo for "podman" packages since they aren't in Debian 10 (buster) repos
deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/ /
```

I suppose it's possible a more recent version of "libseccomp" exists in standard _OpenSuse_ repos (which I haven't tried to use)

**Comment by markonen** [comment]
Also seeing this on a fresh Debian 10 install with podman installed from `https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/`

**Comment by rhatdan** [comment]
Can you get a new libseccomp from the same location?

**Comment by usury** [comment]
> Can you get a new libseccomp from the same location?

If you mean _is the new libseccomp available in the same opensuse repository branch that podman came from_, then the answer is **no**. It's not there.

If you mean _is the new libseccomp available elsewhere in opensuse repos_, then the answer is **I don't know**. I'm not familiar enough with the opensuse repos to know where to start looking.

Regardless, if a specific version of "libseccomp" is required for podman, shouldn't the podman package be built with that specific version as a dependency? At least "apt-get" on Debian can refuse to install the offending "podman" unless it can also install the "libseccomp" required by podman.

**Comment by rhatdan** [comment]
Well I don't really know apt, I do know that these kind of dependencies get built into RPM at build time, I believe.  @lsm5 Might now better about Debian.

**Comment by twagtwig** [comment]
openSUSE's libseccomp is [at version 2.5.0](https://software.opensuse.org/package/libseccomp) and Debian buster's libseccomp-dev is [at version 2.3.3-4](https://packages.debian.org/search?keywords=libseccompl). 

You can install a newer version from backports using [these instructions](https://backports.debian.org/Instructions/) to temporarily resolve the issue.

E.g. after updating your sources.list:
`$ apt-get -t buster-backports install libseccomp-dev `

**Comment by usury** [comment]
> You can install a newer version from backports using [these instructions](https://backports.debian.org/Instructions/) to temporarily resolve the issue.

Thank you! Indeed, this works on Debian 10. Podman launches normally again. :-)
```
dpkg -l | grep libseccomp2
ii  libseccomp2:amd64                     2.4.4-1~bpo10+1  
```

**Comment by rhatdan** [comment]
@lsm5 Is this still an issue?  Seems like we have a few of these around, can we close some?

**Comment by rhatdan** [comment]
I am going to assume this is fixed and close, reopen if I am mistaken.
