### ISSUE TITLE
podman network prune is missing

### ISSUE THREAD

**Issue by rhatdan** [containers/podman#8673]
Docker has a network prune, so podman should as well.

Once network prune is added, it should also be wired into podman system prune.

**Comment by Luap99** [comment]
Podman does not store any network information inside the db. `podman network create` creates a cni config file in `/etc/cni/net.d/` so the idea would be to remove all config files which are currently not used by any container. 

Users can add their own cni configs directly to this directory and don't have to use `podman network create`. What should a network prune do in this case? Should it remove files not created by podman and how would we know if the file was created by podman?

**Comment by rhatdan** [comment]
Good point.  Theoretically it would look through all of it's containers and see if any use the network, and then if not remove the networks that were created.  We could also do something with labels to indicate that podman created the file.  And only remove files created with podman.  Didn't you do something similar?

Bottom line is it is probably to dangerous, and maybe we should just document in podman network  why there is no prune command and explain to users how to remove unused networks.

**Comment by Luap99** [comment]
For future networks we could definitely add some key/label to the the config file to indicate that we are allowed to remove this file.
I agree that it is dangerous to blindly remove files. There could be other applications who rely on files in there.

I added a TODO comment for a dangling filter for `network ls`. Maybe its better to implement this and document that that the user should use `ls --filter dangling=true`. With that they can make sure that nothing important is in there.

**Comment by rhatdan** [comment]
@Luap99 @baude Interested in working on this, or at least adding documentation on not supported to man page.  Before 3.0?

**Comment by baude** [comment]
network prune is merged.
