### ISSUE TITLE
Podman install for Ubuntu 18.04: slirp4netns not found

### ISSUE THREAD

**Issue by SigursteinnBjarni** [containers/podman#8684]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Hi all.

I'm trying to install podman on ubuntu 18.04.

I'm following the guide here: https://podman.io/getting-started/installation
```
. /etc/os-release
echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install podman
```
When I try to start a container I am met with this error message from systemd
```
level=error msg="could not find slirp4netns, the network namespace won't be configured
```
Manually running the container 
```
ERRO[0009] could not find slirp4netns, the network namespace won't be configured: exec: "slirp4netns": executable file not found in $PATH 
```

Despite this error message the containers are still ran by the user and seem to be working.
But this error worries me if this to be used in a production environment,

When I look into the opensuse repo is **no** reference to slirp4netns

**Steps to reproduce the issue:**

1. install podman on ubuntu 18.04 from https://podman.io/getting-started/installation

2. run a container as a non root user

3. See error messages in console

**Describe the results you received:**
```
ERRO[0009] could not find slirp4netns, the network namespace won't be configured: exec: "slirp4netns": executable file not found in $PATH 
9460790aa6707e5feea64cfefce5526538e1cdf191afb5022fb1cffabbd869c1

```

**Describe the results you expected:**
```
9460790aa6707e5feea64cfefce5526538e1cdf191afb5022fb1cffabbd869c1
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.2.0
API Version:  2.1.0
Go Version:   go1.15.2
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 2
  distribution:
    distribution: ubuntu
    version: "18.04"
  eventLogger: journald
  hostname: ver-xr-test-01
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 4.15.0-112-generic
  linkmode: dynamic
  memFree: 262389760
  memTotal: 4112379904
  ociRuntime:
    name: runc
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4101750784
  swapTotal: 4111462400
  uptime: 583h 1m 12.69s (Approximately 24.29 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/verxr/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/verxr/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/verxr/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.2.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 2.2.1~4 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@lsm5 PTAL

**Comment by afbjorklund** [comment]
It is only a recommendation, not a dependency:

```
The following additional packages will be installed:
  catatonit conmon containernetworking-plugins containers-common containers-golang containers-image cri-o-runc crun dmsetup
  iptables libdevmapper1.02.1 libglib2.0-0 libglib2.0-data libgpgme11 libicu60 libip4tc0 libip6tc0 libiptc0 libmnl0
  libnetfilter-conntrack3 libnfnetlink0 libxml2 libxtables12 libyajl2 multiarch-support podman-plugins shared-mime-info uidmap
  varlink xdg-user-dirs
Suggested packages:
  kmod
Recommended packages:
  slirp4netns
The following NEW packages will be installed:
  catatonit conmon containernetworking-plugins containers-common containers-golang containers-image cri-o-runc crun dmsetup
  iptables libdevmapper1.02.1 libglib2.0-0 libglib2.0-data libgpgme11 libicu60 libip4tc0 libip6tc0 libiptc0 libmnl0
  libnetfilter-conntrack3 libnfnetlink0 libxml2 libxtables12 libyajl2 multiarch-support podman podman-plugins shared-mime-info
  uidmap varlink xdg-user-dirs
0 upgraded, 31 newly installed, 0 to remove and 0 not upgraded.
```

I suppose `podman --network=none` works :-P

**Comment by afbjorklund** [comment]
It is also missing `fuse-overlayfs`, see #8560. So basically, you should use `sudo podman` with this package.

**Comment by SigursteinnBjarni** [comment]
@afbjorklund thank you for the answers :)

If slirp4netns is recommenced and Podman throws an error when I run a container, why is it not included in the opensuse repo :) ?

But, since slirp4netns not a dependency, can I then ignore this error? Is it safe / stable for me to run Podman like this in prodcution on Ubuntu 18.04?

I won't be using sudo to run the containers so it must work without sudo permissions.

**Comment by afbjorklund** [comment]
If you run rootless podman, you _want_ to install both the `fuse-overlayfs` and `slirp4netns` packages.

It will "work" without them, but you get will get limited functionality (slow storage and limited networking)

However, it seems they are **not** available in the old distribution:

https://packages.ubuntu.com/search?keywords=fuse-overlayfs

https://packages.ubuntu.com/search?keywords=slirp4netns

So probably they will need to be backported, to Ubuntu 18.04 LTS

**Comment by rhatdan** [comment]
I don't see this as an upstream issue, can we close this issue?

**Comment by SigursteinnBjarni** [comment]
@afbjorklund Thanks again for your answers.

I will close this ticket then and create an issue with the maintainer of the repository.

**Comment by afbjorklund** [comment]
>  Is it safe / stable for me to run Podman like this in prodcution on Ubuntu 18.04?

It seems like you will need Ubuntu 20.04 then, only supported on e.g. RHEL 8

> I will close this ticket then and create an issue with the maintainer of the repository.

I thought this was the repository (for podman, and the needed dependencies)

But you are right, it's an issue with the packaging and not with podman itself.
I suppose you can install fuse-overlayfs and slirp4netns from source instead.

**Comment by arunah** [comment]
minikube start
😄  minikube v1.17.1 on Ubuntu 20.04
👎  Unable to pick a default driver. Here is what was considered, in preference order:
    ▪ vmware: Not installed: exec: "docker-machine-driver-vmware": executable file not found in $PATH
    ▪ docker: Not healthy: "docker version --format {{.Server.Os}}-{{.Server.Version}}" exit status 1: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version: dial unix /var/run/docker.sock: connect: permission denied
    ▪ kvm2: Not installed: exec: "virsh": executable file not found in $PATH
    ▪ podman: Not installed: exec: "podman": executable file not found in $PATH
    ▪ virtualbox: Not installed: unable to find VBoxManage in $PATH

❌  Exiting due to DRV_NOT_DETECTED: No possible driver was detected. Try specifying --driver, or see https://minikube.sigs.k8s.io/docs/start/

Can any one help to troubleshoot this on a VMware workstation . How to install pod man?

sudo apt install podman
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package podman

sudo apt-get -y install podman
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package podman

**Comment by afbjorklund** [comment]
> Can any one help to troubleshoot this on a VMware workstation . How to install pod man?

Please see https://podman.io/getting-started/installation#ubuntu
