### ISSUE TITLE
Podman v3.0 requires crun which might not be present

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman#8687]
This is probably aimed at @lsm5 and hopefully already taken care of.  I just built Podman v3.0 for the first time from GitHub on one of my older VM's (F30).  When I went to run it, I got:

```
# podman version
Error: default OCI runtime "crun" not found: invalid argument
```

So I changed my runtime entry from runc to crun in containers.conf, and still the same error.  The issue was crun was not installed on the system, a simple `dnf -y install crun` solved the problem.  

Two questions:  

1. Is crun a required install with Podman v3.0 as far as the Podman rpm is concerned?
2. I think we need to add "crun" to the [Build and Run Dependencies](https://podman.io/getting-started/installation#build-and-run-dependencies) on the install.md file on podman.io.

**Comment by mheon** [comment]
We need to fix this. `crun` should be default only if present.

**Comment by rhatdan** [comment]
We had the same problem with runc.  We could add something to containers/common to set the default based on whether it can find crun or runc. Or leave it blank otherwise.

**Comment by afbjorklund** [comment]
The ubuntu package uses `cri-o-runc | runc` (the default is CRI-O). With an optional _recommendation_ of `crun`

The only difference is that the cri-o-runc's runc might be newer, like rc92 instead of rc10 (for Ubuntu 20.04 LTS).

**Comment by yufeifly** [comment]
Hi, I want to ask what configurations should I do to use runc instead of crun?

**Comment by rhatdan** [comment]
create a /etc/containers/containers.conf or $HOME/.config/containers/containers.conf that looks like

[engine]
runtime="runc"

**Comment by rhatdan** [comment]
The latest podman 3.0 in main now has the change to look for the ociruntime rather then hard coding it to crun.  So if crun is not installed it should fail over to runc, if it can find it.

**Comment by mheon** [comment]
@yufeifly At this point, I'm just going to recommend `crun` for everything - it's very mature and generally speaking more capable than `runc`.

**Comment by afbjorklund** [comment]
Seems like "crun" will have the same missing-on-Ubuntu-18.04-LTS issue as "fuse-overlayfs" (#8560) and "slirp4netns" (#8684)

* https://packages.ubuntu.com/search?keywords=crun

**Comment by imperialguy** [comment]
> podman 3.0

Are there plans to release podman runtime on Windows/Mac anytime soon?

**Comment by rhatdan** [comment]
No Podman launches Linux containers, Linux containers require a Linux Kernel.  Neither Windows or Mac use Linux kernels, so you need to run a VM or work with a remote linux machine. Windows supports WSL2 which is really just a VM running Linux, so podman will work within WSL2.

**Comment by mheon** [comment]
Worth noting that we do support a remote client for OS X and Windows right now that is capable of managing containers on a Linux machine (usually a VM on the system).
