### ISSUE TITLE
Output formatting syntax with --format is not fully supported

### ISSUE THREAD

**Issue by mprasil** [containers/podman#8702]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman does not support formatting of output the same way as docker does. As an example this is used by `docker` Emacs plugin and thus podman is not viable replacement in that case:

**Steps to reproduce the issue:**

1. `podman image ls --format="[{{json .Repository}},{{json .Tag}},{{json .ID}},{{json .CreatedAt}},{{json .Size}}]"`

**Describe the results you received:**

```
Error: template: list:1: function "json" not defined
```

**Describe the results you expected:**

docker will display image list with appropriate formatting:

```
["redis","5.0.6-alpine","6f63d037b592","2019-10-21 22:59:50 +0100 IST","29.3MB"]
["alpine","3.3","a6fc1dbfa81a","2019-01-30 22:20:20 +0000 GMT","4.82MB"]
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 2.2.1~4 amd64 [installed]
podman/unknown 2.2.1~4 arm64
podman/unknown 2.2.1~4 armhf
podman/unknown 2.2.1~4 s390x

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

I'm using the latest released version.

**Comment by zhangguanzhang** [comment]
@jwhonce

**Comment by buvoli** [comment]
@zhangguanzhang @jwhonce Is there any update on this bug? I also ran into it today using podman 2.2.1 and noticed that it is currently affecting other commands such as `podman ps` and `podman inspect` (See Below)

```bash
$ podman --version
podman version 2.2.1
$ podman ps -a --format='{{json .Id}}'
Error: template: listContainers:1: function "json" not defined
$ podman inspect 5f10 --format='{{json .Id}}'
ERRO[0000] Error printing inspect output: template: all inspect:1: function "json" not defined 
```

**Comment by rhatdan** [comment]
This seems to be still broken.
@jwhonce Should this work?

**Comment by rhatdan** [comment]
If you remove the "json" indicator podman prints out the output you want.

podman image ls --format="[{{.Repository}},{{.Tag}},{{.ID}},{{.CreatedAt}},{{.Size}}]" | head -3
[localhost/pinp,latest,7042e92aac12,2021-04-12 12:36:21 +0000 UTC,501 MB]
[quay.io/rhatdan/podman,latest,7042e92aac12,2021-04-12 12:36:21 +0000 UTC,501 MB]
[<none>,<none>,b6ecae6e561f,2021-04-12 12:32:37 +0000 UTC,501 MB]


What is the significance of the "json" param?

**Comment by jwhonce** [comment]
In podman 3.2 this works as expected. Notice `ID` vs `Id`.

```
$ bin/podman ps -a --format='{{json .ID}}'
"326d362d9f6d"
```

The `json`  operation causes ID to be wrapped in quotes.
