### ISSUE TITLE
outbound_addr not supported on 2.2.1

### ISSUE THREAD

**Issue by avin3sh** [containers/podman#8703]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**outbound_addr** with **slirp4netns** should have been available for the podman version 2.2.1 per b6176d8987a0049a253fd7a70b2cd8e17bd50b53 but I am still not able to use the option on version 2.2.1

**Steps to reproduce the issue:**

1. Create a pod with `outbound_addr` option,
`podman pod create --network=slirp4netns:outbound_addr=ens3  --publish 51820:51820/udp --name vpn`

2. Add a container to this newly created pod,
`podman run -d  --name=wireguard --pod vpn   --cap-add net_admin   --cap-add sys_module   -e PUID=1000   -e PGID=1000   -e TZ=Europe/London   -e SERVERURL=192.168.1.34   -e SERVERPORT=51820   -e PEERS=1   -e PEERDNS=1.1.1.1   -e INTERNAL_SUBNET=10.13.13.0   -e ALLOWEDIPS=0.0.0.0/0   -v ./wireguard/config:/config   -v /lib/modules:/lib/modules   --sysctl="net.ipv4.conf.all.src_valid_mark=1" --restart unless-stopped   ghcr.io/linuxserver/wireguard`

**Describe the results you received:**
I get the following error,
```
ERRO[0000] error starting some container dependencies   
ERRO[0000] "outbound_addr not supported"                
Error: error starting some containers: internal libpod error

```

**Describe the results you expected:**

I should have been able to add the container in the pod configured with `outbound_addr`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.2
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: '
  cpus: 1
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: olivegreen
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.4.0-58-generic
  linkmode: dynamic
  memFree: 164524032
  memTotal: 2033971200
  ociRuntime:
    name: runc
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 0.4.3
      commit: 2244b9b6461afeccad1678fac3d6e478c28b4ad6
  swapFree: 0
  swapTotal: 0
  uptime: 23h 13m 12.15s (Approximately 0.96 days)
registries:
  search:
  - docker.io
store:
  configFile: /home/vv019/.config/containers/storage.conf
  containerStore:
    number: 8
    paused: 0
    running: 6
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.9.0
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.0
        using FUSE kernel interface version 7.31
  graphRoot: /home/vv019/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 6
  runRoot: /run/user/1000/containers
  volumePath: /home/vv019/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 2.2.1~4 amd64 [installed]
podman/unknown 2.2.1~4 arm64
podman/unknown 2.2.1~4 armhf
podman/unknown 2.2.1~4 s390x

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
What version of slirp4netns do you have installed?

**Comment by avin3sh** [comment]
> What version of slirp4netns do you have installed?
@mheon My slirp4netns version is `0.4.3-1` on Ubuntu `20.04`

**Comment by mheon** [comment]
It looks like v1.1.0 is minimum for outbound address support.

**Comment by avin3sh** [comment]
Thanks. This was no longer an issue when using  >= `v1.1.0` for `slirp4netns`
