### ISSUE TITLE
Centos 8 dnf install error

### ISSUE THREAD

**Issue by Ds894** [containers/podman#8704]
/kind bug

**Description**

Attempting to install the latest podman on Centos 8, two packages report download errors: catatonit and conmon

**Steps to reproduce the issue:**

1. dnf clean all

2.dnf -y install podman

**Describe the results you received:**
[root@a0ed51e264a8 build]# dnf clean all
57 files removed
[root@a0ed51e264a8 build]# dnf -y install podman
CentOS Linux 8 - AppStream                                                       662 kB/s | 6.2 MB     00:09    
CentOS Linux 8 - BaseOS                                                          1.1 MB/s | 2.3 MB     00:02    
CentOS Linux 8 - Extras                                                          7.4 kB/s | 8.1 kB     00:01    
Copr repo for container-selinux owned by rhcontainerbot                          3.2 kB/s | 1.4 kB     00:00    
Stable Releases of Upstream github.com/containers packages (CentOS_8)             28 kB/s |  69 kB     00:02    
Dependencies resolved.
=================================================================================================================
 Package                     Arch   Version                         Repository                              Size
=================================================================================================================
Installing:
 podman                      x86_64 2.2.1-1.el8                     devel_kubic_libcontainers_stable        23 M
Installing dependencies:
 conmon                      x86_64 2:2.0.21-1.el8                  devel_kubic_libcontainers_stable        42 k
 containernetworking-plugins x86_64 0.8.7-1.el8                     devel_kubic_libcontainers_stable        38 M
 containers-common           x86_64 2:1.2.0-12.el8                  devel_kubic_libcontainers_stable        91 k
 iptables                    x86_64 1.8.4-15.el8                    baseos                                 583 k
 jansson                     x86_64 2.11-3.el8                      baseos                                  46 k
 libnetfilter_conntrack      x86_64 1.0.6-5.el8                     baseos                                  65 k
 libnfnetlink                x86_64 1.0.1-13.el8                    baseos                                  33 k
 libnftnl                    x86_64 1.1.5-4.el8                     baseos                                  83 k
 libselinux-utils            x86_64 2.9-4.el8_3                     baseos                                 242 k
 nftables                    x86_64 1:0.9.3-16.el8                  baseos                                 312 k
 policycoreutils             x86_64 2.9-9.el8                       baseos                                 377 k
 rpm-plugin-selinux          x86_64 4.14.3-4.el8                    baseos                                  75 k
 selinux-policy              noarch 3.14.3-54.el8                   baseos                                 622 k
 selinux-policy-targeted     noarch 3.14.3-54.el8                   baseos                                  15 M
Installing weak dependencies:
 catatonit                   x86_64 0.1.5-1.el8                     devel_kubic_libcontainers_stable       288 k
 container-selinux           noarch 2:2.145.0-1.el8                 copr:copr.fedorainfracloud.org:rhcontainerbot:container-selinux
                                                                                                            59 k
 libvarlink-util             x86_64 19-3.el8                        devel_kubic_libcontainers_stable        51 k
 podman-plugins              x86_64 2.2.1-1.el8                     devel_kubic_libcontainers_stable       2.4 M
 runc                        x86_64 2:1.0.0-145.rc91.git24a3cf8.el8 devel_kubic_libcontainers_stable       5.8 M
 slirp4netns                 x86_64 1.1.8-1.el8                     devel_kubic_libcontainers_stable        53 k

Transaction Summary
=================================================================================================================
Install  21 Packages

Total download size: 88 M
Installed size: 234 M
Downloading Packages:
(1/21): libnetfilter_conntrack-1.0.6-5.el8.x86_64.rpm                            356 kB/s |  65 kB     00:00    
(2/21): jansson-2.11-3.el8.x86_64.rpm                                            247 kB/s |  46 kB     00:00    
(3/21): libnftnl-1.1.5-4.el8.x86_64.rpm                                          343 kB/s |  83 kB     00:00    
(4/21): libnfnetlink-1.0.1-13.el8.x86_64.rpm                                      76 kB/s |  33 kB     00:00    
(5/21): iptables-1.8.4-15.el8.x86_64.rpm                                         708 kB/s | 583 kB     00:00    
(6/21): libselinux-utils-2.9-4.el8_3.x86_64.rpm                                  375 kB/s | 242 kB     00:00    
(7/21): nftables-0.9.3-16.el8.x86_64.rpm                                         497 kB/s | 312 kB     00:00    
(8/21): rpm-plugin-selinux-4.14.3-4.el8.x86_64.rpm                               439 kB/s |  75 kB     00:00    
(9/21): policycoreutils-2.9-9.el8.x86_64.rpm                                     387 kB/s | 377 kB     00:00    
(10/21): container-selinux-2.145.0-1.el8.noarch.rpm                              295 kB/s |  59 kB     00:00    
(11/21): selinux-policy-3.14.3-54.el8.noarch.rpm                                 586 kB/s | 622 kB     00:01    
[MIRROR] catatonit-0.1.5-1.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 295160 but expected size is: 295204
[MIRROR] conmon-2.0.21-1.el8.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: a995a31a2dbf2ea71ca21aa787f317e93f0c97c09f4bf6b3c53edab78b5ecbb3(sha256)  Expected: de911f508c9f42f1b6783353351d0f74e238c35000a7fca9563802ed4e2015e1(sha256) 
[MIRROR] catatonit-0.1.5-1.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 295160 but expected size is: 295204
[MIRROR] conmon-2.0.21-1.el8.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: a995a31a2dbf2ea71ca21aa787f317e93f0c97c09f4bf6b3c53edab78b5ecbb3(sha256)  Expected: de911f508c9f42f1b6783353351d0f74e238c35000a7fca9563802ed4e2015e1(sha256) 
[FAILED] conmon-2.0.21-1.el8.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
(13-14/21): catatonit-0.1.5-1.el8.x86  4% [=-                                  ] 1.0 MB/s | 4.1 MB     01:20 ETA
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Cannot download x86_64/conmon-2.0.21-1.el8.x86_64.rpm: All mirrors were tried
[root@a0ed51e264a8 build]# dnf clean packages
11 files removed

**Describe the results you expected:**
I did not expect signature or size errors on download

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
<not applicable, since I could not install podman>
```

**Output of `podman info --debug`:**

```
<not applicable, since I could not install podman>
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
<not applicable, since I could not install podman>
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Centos 8 is in a podman container.

**Comment by mheon** [comment]
@lsm5 PTAL, looks like something about the Cent OBS builds is off?

**Comment by leftl** [comment]
Confirming same issue on 8_Stream
`[root@centos ~]# dnf install podman
[...]
[MIRROR] podman-plugins-2.2.1-1.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 2536056 but expected size is: 2536064
[MIRROR] podman-2.2.1-1.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 22514300 but expected size is: 22514304
[MIRROR] containers-common-1.2.0-12.el8.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 82570c09fe63a78354ef89f108cf760dbe17a7d23475e1d6bc473de9396efdb4(sha256)  Expected: 82a4c85afd8b09a3952492e72517039a4c0072421951603f790c1e2ea7a67e5f(sha256)
[MIRROR] podman-plugins-2.2.1-1.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 2536056 but expected size is: 2536064
[FAILED] podman-plugins-2.2.1-1.el8.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
(8-9/11): containers-common-1.2.0-12.el8.x86_64.rpm         10% [======                                                     ] 844 kB/s | 3.2 MB     00:32 ETA
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Cannot download x86_64/podman-plugins-2.2.1-1.el8.x86_64.rpm: All mirrors were tried`

**Comment by rhatdan** [comment]
@Ds894 @leftl Is this still an issue?  We should have podman-3.0.0-rc1 available I believe.
@jnovy @lsm5 PTAL

**Comment by leftl** [comment]
@rhatdan still unable to update via kubic repo
```
Downloading Packages:
[MIRROR] containers-common-1.2.0-15.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 93740 but expected size is: 93748
[MIRROR] libslirp-4.3.1-2.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 67892 but expected size is: 67888
(1/5): conmon-2.0.25-1.el8.x86_64.rpm                                25 kB/s |  46 kB     00:01
[MIRROR] libslirp-4.3.1-2.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 67892 but expected size is: 67888
[MIRROR] containers-common-1.2.0-15.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 93740 but expected size is: 93748
[FAILED] containers-common-1.2.0-15.el8.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
(3-4/5): libvarlink-19-3.el8.x  2% [-                             ] 117 kB/s | 138 kB     00:52 ETA
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Cannot download x86_64/containers-common-1.2.0-15.el8.x86_64.rpm: All mirrors were tried
```

**Comment by lsm5** [comment]
@Ds894 @leftl could you try a `dnf clean all` and then retry installing?

**Comment by lsm5** [comment]
> @Ds894 @leftl Is this still an issue? We should have podman-3.0.0-rc1 available I believe.
> @jnovy @lsm5 PTAL

The stable repo ain't getting any 3.0 until I get green light from matt for v3.0.0

**Comment by leftl** [comment]
@lsm5 apologies for the late response! Looks like the issue still exists on my VM, even after running `clean all`. I'll try spinning up a fresh install of 8_Stream and give it another go.
```
[tyler@centos ~]$ sudo dnf -y --refresh install podman
CentOS Stream 8 - AppStream                                                                        9.6 kB/s | 4.4 kB     00:00
CentOS Stream 8 - BaseOS                                                                           7.0 kB/s | 3.9 kB     00:00
CentOS Stream 8 - Extras                                                                           4.4 kB/s | 1.5 kB     00:00
Copr repo for container-selinux owned by rhcontainerbot                                             12 kB/s | 3.3 kB     00:00
Testing Releases of Upstream github.com/containers packages (CentOS_8_Stream)                      3.0 kB/s | 1.7 kB     00:00
Dependencies resolved.
===================================================================================================================================
 Package               Arch       Version                Repository                                                           Size
===================================================================================================================================
Installing:
 podman                x86_64     3.0.0-0.2.rc1.el8      devel_kubic_libcontainers_testing                                    21 M
Installing dependencies:
 conmon                x86_64     2:2.0.26-1.el8         devel_kubic_libcontainers_testing                                    46 k
 container-selinux     noarch     2:2.145.0-1.el8        copr:copr.fedorainfracloud.org:rhcontainerbot:container-selinux      59 k
 containers-common     x86_64     2:1.2.0-15.el8         devel_kubic_libcontainers_testing                                    92 k
 crun                  x86_64     0.16-1.el8             devel_kubic_libcontainers_testing                                   183 k
 libslirp              x86_64     4.3.1-2.el8            devel_kubic_libcontainers_testing                                    66 k
Installing weak dependencies:
 catatonit             x86_64     0.1.5-1.el8            devel_kubic_libcontainers_testing                                   290 k
 podman-plugins        x86_64     3.0.0-0.2.rc1.el8      devel_kubic_libcontainers_testing                                   2.5 M
 slirp4netns           x86_64     1.1.8-1.el8            devel_kubic_libcontainers_testing                                    53 k

Transaction Summary
===================================================================================================================================
Install  9 Packages

Total download size: 24 M
Installed size: 68 M
Downloading Packages:
(1/9): container-selinux-2.145.0-1.el8.noarch.rpm                                                  401 kB/s |  59 kB     00:00
[MIRROR] conmon-2.0.26-1.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 47512 but expected size is: 47496
[MIRROR] catatonit-0.1.5-1.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 296972 but expected size is: 296964
(2/9): containers-common-1.2.0-15.el8.x86_64.rpm                                                    70 kB/s |  92 kB     00:01
[MIRROR] conmon-2.0.26-1.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 47512 but expected size is: 47496
[MIRROR] catatonit-0.1.5-1.el8.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 296972 but expected size is: 296964
[FAILED] catatonit-0.1.5-1.el8.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
(4-5/9): crun-0.16-1.el8.x86_64.rpm             1% [-                                            ] 459 kB/s | 441 kB     00:53 ETA
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Cannot download x86_64/catatonit-0.1.5-1.el8.x86_64.rpm: All mirrors were tried
```

**Comment by WittyNameHere** [comment]
Is this the same issue? RHEL 8.3 running CentOS repo.

```
========================================================================================================================
 Package                            Architecture  Version                 Repository                               Size
========================================================================================================================
Upgrading:
 conmon                             x86_64        2:2.0.26-2.el8          devel_kubic_libcontainers_stable         49 k
 containernetworking-plugins        x86_64        0.9.1-2.el8             devel_kubic_libcontainers_stable         41 M
 containers-common                  noarch        4:1-4.el8               devel_kubic_libcontainers_stable         58 k
 podman                             x86_64        3.0.0-1.el8             devel_kubic_libcontainers_stable         23 M
 podman-plugins                     x86_64        3.0.0-1.el8             devel_kubic_libcontainers_stable        2.5 M
 slirp4netns                        x86_64        1.1.8-3.el8             devel_kubic_libcontainers_stable         55 k
Installing dependencies:
 crun                               x86_64        0.16-1.el8              devel_kubic_libcontainers_stable        182 k

Transaction Summary
========================================================================================================================
Install  1 Package
Upgrade  6 Packages

Total download size: 67 M
Is this ok [y/N]: y
Downloading Packages:
[MIRROR] crun-0.16-1.el8.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 7ede10fe22764e3c77d544c6be24939e4224ff83129092fc03c50dc73da8423e(sha256)  Expected: 704d4604f43464cf5848c3bf432926ec1e5add72e794b81d1d3e2f059300ffec(sha256)
[MIRROR] crun-0.16-1.el8.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 7ede10fe22764e3c77d544c6be24939e4224ff83129092fc03c50dc73da8423e(sha256)  Expected: 704d4604f43464cf5848c3bf432926ec1e5add72e794b81d1d3e2f059300ffec(sha256)
(1/7): conmon-2.0.26-2.el8.x86_64.rpm                                                    29 kB/s |  49 kB     00:01
[MIRROR] crun-0.16-1.el8.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 7ede10fe22764e3c77d544c6be24939e4224ff83129092fc03c50dc73da8423e(sha256)  Expected: 704d4604f43464cf5848c3bf432926ec1e5add72e794b81d1d3e2f059300ffec(sha256)
[MIRROR] crun-0.16-1.el8.x86_64.rpm: Downloading successful, but checksum doesn't match. Calculated: 7ede10fe22764e3c77d544c6be24939e4224ff83129092fc03c50dc73da8423e(sha256)  Expected: 704d4604f43464cf5848c3bf432926ec1e5add72e794b81d1d3e2f059300ffec(sha256)
[FAILED] crun-0.16-1.el8.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
(3-4/7): containernetworking-plugins-0.9  0% [                                        ] 411 kB/s | 647 kB     02:46 ETA
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  Cannot download x86_64/crun-0.16-1.el8.x86_64.rpm: All mirrors were tried
```

**Comment by lsm5** [comment]
I'm updating dependencies on OBS atm. Just sent crun and catatonit updates. I'll check on the rest and try locally as well. Sorry about the lag.

**Comment by lsm5** [comment]
should be fixed with podman 2:3.0.0-3, available on Kubic Stable now: https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman

Closing, please reopen if issue persists.

**Comment by lmgray** [comment]
Still seeing this problem:

**Comment by lmgray** [comment]
I can't re-open this issue per @lsm5 request -- perhaps OP (@Ds894) can reopen?

**Comment by lmgray** [comment]
opened #9503
