### ISSUE TITLE
Error: Get "http://d/v2.0.0/libpod/_ping": on Mac

### ISSUE THREAD

**Issue by tolerious** [containers/podman#8708]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. brew install podman

2. podman search busybox

**Describe the results you received:**
Got this error:
```
Error: Get "http://d/v2.0.0/libpod/_ping": dial unix ///var/folders/5c/f7b4ff4n4995dpfncl6bmv240000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```

**Describe the results you expected:**
Also got this error:
```
Error: Get "http://d/v2.0.0/libpod/_ping": dial unix ///var/folders/5c/f7b4ff4n4995dpfncl6bmv240000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Got this error:

Error: Get "http://d/v2.0.0/libpod/_ping": dial unix ///var/folders/5c/f7b4ff4n4995dpfncl6bmv240000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory

```

**Output of `podman info --debug`:**

```
Error: Get "http://d/v2.0.0/libpod/_ping": dial unix ///var/folders/5c/f7b4ff4n4995dpfncl6bmv240000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
MacBook

**Comment by vrothberg** [comment]
Thanks for reaching out!

Podman on Mac OS and Windows requires a Linux machine running Podman (e.g., in a VM).  There's a great blog on Enable SysAdmin (https://www.redhat.com/sysadmin/podman-clients-macos-windows) that explains the architecture.
