### ISSUE TITLE
Error: unable to load cgroup at /machine.slice/.../: cgroup deleted

### ISSUE THREAD

**Issue by cevich** [containers/podman#8732]
/kind bug

**Description**

Discovered while developing #8312, executing integration tests on F32 inside a container, on a host using CGroupsV1 + runc, nearly/all the 'podman pod stats' tests fail with this error message.

**Steps to reproduce the issue:**

1. Using podman on host w/ CGv1 + runc-1.0.0-146.rc92
2. Start super-privileged container
    ```
    podman run --rm --privileged --net=host --cgroupns=host \
        -v /dev/fuse:/dev/fuse \
        -v "$GOPATH:$GOPATH:Z" \
        --workdir "$GOSRC" \
        quay.io/libpod/fedora_podman:c6233039174893568
    ```
3. `make localintegration`

**Describe the results you received:**

(from `podman stats on all pods` test/e2e/pod_stats_test.go:119)

[+1284s] Running: podman --storage-opt vfs.imagestore=/tmp/podman/imagecachedir --root /tmp/.../crio --runroot /tmp/.../crio-run --runtime runc --conmon /usr/bin/conmon --cni-config-dir /etc/cni/net.d --cgroup-manager cgroupfs --tmpdir /tmp/... --events-backend file --storage-driver vfs run --pod 2...5 -d quay.io/libpod/alpine:latest top
[+1284s] output: 4...5
[+1284s] Running: podman --storage-opt vfs.imagestore=/tmp/podman/imagecachedir --root /tmp/.../crio --runroot /tmp/.../crio-run --runtime runc --conmon /usr/bin/conmon --cni-config-dir /etc/cni/net.d --cgroup-manager cgroupfs --tmpdir /tmp/... --events-backend file --storage-driver vfs pod stats --no-stream -a
[+1284s] Error: unable to load cgroup at /machine.slice/libpod-3...1.scope/libpod_parent/2...5/libpod-4...5: cgroup deleted

Note: big numbers replaced with `...`

**Describe the results you expected:**

Test should pass (along with nearly/all other podman pod stats tests)

**Additional information you deem important (e.g. issue happens only occasionally):**

[Representative failure in CI](https://cirrus-ci.com/task/5185187027877888?command=main#L3660)

**Comment by rhatdan** [comment]
This is no longer and issue, I believe and there is a duplicate issue already.  Closing.
