### ISSUE TITLE
Error: pod stats is not supported in rootless mode without cgroups v2

### ISSUE THREAD

**Issue by cevich** [containers/podman#8734]
/kind bug

**Description**

Nearly/all `podman pod stats` tests fail when running as a user, on a host using CGroupsV1 & `runc-1.0.0-146.rc92`.  The tests were globally skipped in the case of rootless + CGroupsV2.  However, apparently they also cannot function with CGv1 either.

As of #8312 this has been addressed by a blanket `SkipIfRootless()`. I am not certain if this is otherwise fixable or worth the effort, since `--cgroup-manager=cgroupfs` is required for rootless operation.

**Steps to reproduce the issue:**

1. Execute integration tests as a regular user

**Describe the results you received:**

[(typical failure example)](https://cirrus-ci.com/task/6062647370055680)

```
[+0284s] Podman pod stats 
[+0284s]   podman stats should run with no pods
[+0284s]   /var/tmp/go/src/github.com/containers/podman/test/e2e/pod_stats_test.go:42
[+0284s] 
[+0284s] [BeforeEach] Podman pod stats
[+0284s]   /var/tmp/go/src/github.com/containers/podman/test/e2e/pod_stats_test.go:19
[+0284s] [It] podman stats should run with no pods
[+0284s]   /var/tmp/go/src/github.com/containers/podman/test/e2e/pod_stats_test.go:42
[+0284s] Running: podman --storage-opt vfs.imagestore=/tmp/podman/imagecachedir --root /tmp/.../crio --runroot /tmp/.../crio-run --runtime runc --conmon /usr/bin/conmon --cni-config-dir /home/some20681dude/.config/cni/net.d --cgroup-manager cgroupfs --tmpdir /tmp/... --events-backend file --storage-driver vfs pod stats --no-stream
[+0284s] Error: pod stats is not supported in rootless mode without cgroups v2
```

**Describe the results you expected:**

Someone who knows more than me should examine `BeforeEach()` in `test/e2e/pod_stats_test.go` to ensure the skip-selection is correct.  Esp. after #8312 is merged.

**Comment by mheon** [comment]
The logic here sounds inverted. The tests should run on Cgroups v2 + rootless. They are not expected to work on cgroups v1 + rootless.

**Comment by cevich** [comment]
Sorry, I don't follow how that's any different from the issue title?

**Comment by cevich** [comment]
Also...aren't you suppose to be on PTO? 😛
