### ISSUE TITLE
published ports syntax not working as expected

### ISSUE THREAD

**Issue by bfallik** [containers/podman#8741]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The syntax `podman run -p <PORT> ...` suddenly stopped working 

**Steps to reproduce the issue:**

1.  `# podman run -it --rm -p 8080 busybox sh -c "while true ; do echo 'Hello World' | nc -lp 8080; done"`

2. `#  socat TCP4:localhost:8080 - `

**Describe the results you received:**

`2020/12/15 22:48:09 socat[17906] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused`

**Describe the results you expected:**

`Hello World`

**Additional information you deem important (e.g. issue happens only occasionally):**

`# podman run -p 8080:8080 ...` seems to work

**Output of `podman version`:**

```
# podman version
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.5
Built:        Tue Dec  8 09:37:50 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
# podman info --debug
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-3.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 0f53fb68333bdead5fe4dc5175703e22cf9882ab'
  cpus: 4
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: groot.lan.bfallik.net
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.9.13-200.fc33.x86_64
  linkmode: dynamic
  memFree: 2041810944
  memTotal: 7903309824
  ociRuntime:
    name: crun
    package: crun-0.16-1.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.16
      commit: eb0145e5ad4d8207e84a327248af76663d4e50dd
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 12016672768
  swapTotal: 12016672768
  uptime: 8h 5m 53.24s (Approximately 0.33 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 7
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 13
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1607438270
  BuiltTime: Tue Dec  8 09:37:50 2020
  GitCommit: ""
  GoVersion: go1.15.5
  OsArch: linux/amd64
  Version: 2.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# rpm -q podman
podman-2.2.1-1.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical hardware

**Comment by bfallik** [comment]
possibly related to #8742

**Comment by mheon** [comment]
The syntax you're mentioning binds the the requested port in the container to a random port in the host. We had a bug in a few previous versions where this was not random and instead always bound to the same port, but this was not the intended behavior and has been fixed. If you require a consistent assignment, `-p 8080:8080` is the correct syntax. Alternatively, you can retrieve the host port we bound to via `podman port` or `podman inspect` on the container.

**Comment by bfallik** [comment]
@mheon wow, I had no idea I'd been using buggy syntax for months now. Thanks for clarifying.

I now see that detail clearly explained here: http://docs.podman.io/en/latest/markdown/podman-create.1.html?highlight=publish#publish-p-port.
