### ISSUE TITLE
unable to publish UDP port on a specific iface

### ISSUE THREAD

**Issue by bfallik** [containers/podman#8742]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Publishing UDP ports doesn't seem to work at all.

**Steps to reproduce the issue:**

1.  `# podman run -it --rm -p 10.100.10.5:8080:8080/udp busybox sh -c "while true ; do echo 'Hello World' | nc -u -lp 8080; done"`

2. `socat UDP4:localhost:8080 -`

**Describe the results you received:**

`2020/12/15 22:54:32 socat[18638] E read(5, 0x55bca6f4d390, 8192): Connection refused`

**Describe the results you expected:**

`Hello World`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
# podman version
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.5
Built:        Tue Dec  8 09:37:50 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
# podman info --debug
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-3.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 0f53fb68333bdead5fe4dc5175703e22cf9882ab'
  cpus: 4
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: groot.lan.bfallik.net
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.9.13-200.fc33.x86_64
  linkmode: dynamic
  memFree: 2041810944
  memTotal: 7903309824
  ociRuntime:
    name: crun
    package: crun-0.16-1.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.16
      commit: eb0145e5ad4d8207e84a327248af76663d4e50dd
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 12016672768
  swapTotal: 12016672768
  uptime: 8h 5m 53.24s (Approximately 0.33 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 7
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 13
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1607438270
  BuiltTime: Tue Dec  8 09:37:50 2020
  GitCommit: ""
  GoVersion: go1.15.5
  OsArch: linux/amd64
  Version: 2.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
# rpm -q podman
podman-2.2.1-1.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical hardware

**Comment by bfallik** [comment]
possibly related to issue #8741

**Comment by mheon** [comment]
Your reproducer looks a little questionable... You bind to a 10.0.0.0/8 address, but then try to `socat` against localhost?

**Comment by mheon** [comment]
Did this work in previous Podman versions?

**Comment by bfallik** [comment]
@mheon yeah, sorry for the confusion on the reproducer. Similar to #8741 I'm trying to understand why my podman-managed containers suddenly stopped working. In this case I had been running CoreDNS via podman by publishing the UDP port to a specific interface, `-p 10.100.10.5:53:53/udp` but that has stopped working.

The reproducer I captured above doesn't capture the problem I'm seeing. I can launch one container with `-p 10.100.10.5:53:53/udp` and use socat to see "Hello World" on 10.100.10.5:53.

But my container that runs CoreDNS (via systemd) still doesn't seem to receive any traffic on this port. I'm not sure how to debug this further since (1) it used to work, and (2) there's nothing obviously wrong with UDP traffic since nc/socat work OK when I run them manually.

**Comment by bfallik** [comment]
I think I have an actual reproducer now. There seems to be an unexplained interaction between publishing TCP port and the UDP port. This works:

```
# podman run -it --rm -p 10.100.10.5:54:54/udp -p 9154:9154 busybox sh -c "while true ; do echo 'Hello World' | nc -u -lp 54; done"
```

```
# socat UDP4:10.100.10.5:54 -

Hello World
^C
```

but this does not

```
# podman run -it --rm -p 10.100.10.5:54:54/udp -p 9154 busybox sh -c "while true ; do echo 'Hello World' | nc -u -lp 54; done"
```

```
#  socat UDP4:10.100.10.5:54 -

2020/12/16 00:10:25 socat[36258] E read(5, 0x560ec1624890, 8192): Connection refused
```

It's very strange to me that the second `-p 9154` for TCP port 9154 has any impact on publishing UDP port 54.

**Comment by mheon** [comment]
Assuming you're running as root - are you using `firewalld` on your system to manage the firewall?

**Comment by bfallik** [comment]
@mheon yes

```
$ sudo firewall-cmd --state
running
```

**Comment by mheon** [comment]
Can you provide `iptables -t nat -nvL` and `iptables -nvL` with a working container (missing the second `-p`) and a broken container?

**Comment by bfallik** [comment]
[broken-log.txt](https://github.com/containers/podman/files/5712352/broken-log.txt)

**Comment by bfallik** [comment]
[working-log.txt](https://github.com/containers/podman/files/5712356/working-log.txt)

**Comment by bfallik** [comment]
@mheon attached two sessions in the broken and working states. Hopefully this is helpful.

Also, the broken state doesn't have a second -p argument. The difference is the argument to -p, "9154" causes an unrelated UDP port (53) to stop working while "9154:9154" does not interfere with UDP port 53.

**Comment by mheon** [comment]
The working log has:

```
27831 1947K CNI-DN-ca1c0c324ed72eeae4e8d  udp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* dnat name: "podman" id: "8ff8bf0831b83801198eb3d6dfe35c695f666e6ff9d10035094bd1c2c3d5880f" */ multiport dports 53
```

The broken log does not. This is definitely a port forward rule for port 53, so it not being there gives us a pretty clear cause. It seems like it's never being added by CNI or Podman. Can you verify that the broken container has an entry for port 53 in its `podman inspect` output? That will tell us whether CNI, or Podman itself, is responsible.

**Comment by bfallik** [comment]
hi @mheon 

It doesn't look like it does:

```
$ sudo podman ps -a | grep coredns
0de14042d8b9  docker.io/coredns/coredns:latest          -conf /root/Coref...  2 hours ago   Up 2 hours ago   0.0.0.0:36313-
$ sudo podman inspect 0de14042d8b9 | grep '\b53\b'
               "10.100.10.5:53:53/udp",
```

where ""10.100.10.5:53:53/udp" is just a repeat of the podman args in the CreateCommand key and container 0de14042d8b9 is in the broken state.

Thanks,
brian

**Comment by mheon** [comment]
OK, so it's Podman, not CNI, then. Must be an issue with how we're parsing the ports.

**Comment by bfallik** [comment]
Cool, glad we're narrowing it down. Let me know if I can provide any more details. Thx!

**Comment by rhatdan** [comment]
@mheon Any progress on this?

**Comment by mheon** [comment]
No - I'll try and take care of it this week, now that we're in bugfixing mode.

**Comment by mheon** [comment]
Cannot reproduce on the 3.0 RC - I'm seeing all ports added correctly. @bfallik Mind trying again with 3.0.0-RC1?

**Comment by bfallik** [comment]
@mheon Happy to try again. What's the easiest way to install RC1 on Fedora 33?

**Comment by mheon** [comment]
RPMs available at https://koji.fedoraproject.org/koji/buildinfo?buildID=1670934

**Comment by bfallik** [comment]
@mheon looks to me like it's fixed. First I reproduced the problem with my existing installation then upgraded the podman packages and tried again. I wasn't able to reproduce it anymore.

```
$ podman version
Version:      3.0.0-rc1
API Version:  3.0.0
Go Version:   go1.15.6
Built:        Mon Jan 18 11:07:50 2021
OS/Arch:      linux/amd64
```

**Comment by mheon** [comment]
Thanks! I'll close then.
