### ISSUE TITLE
podman run home directory

### ISSUE THREAD

**Issue by marcpawl** [containers/podman#8757]
/kind feature

**Description**
Automatic assignment of home directory may be incorrect, we need the ability to set the home directory for when a user is specified.

1.
```
podman run --userns=keep-id --rm -i -t --name centos  centos /bin/bash
bash-4.4$ id
uid=1000(mpawlowsky) gid=1000(mpawlowsky) groups=1000(mpawlowsky)
bash-4.4$ echo $HOME
/
bash-4.4$ touch ${HOME}/hello
touch: cannot touch '//hello': Permission denied
bash-4.4$ touch ${HOME}hello
touch: cannot touch '/hello': Permission denied
bash-4.4$ grep mpawlowsky /etc/passwd
mpawlowsky:*:1000:1000::/:/bin/sh
bash-4.4$ 
```

**Describe the results you received:**
Cannot write to the home directory.  Programs such as gradle fail, since they want to create a temporary files in the home directory and ignore the environment variable HOME.  I do not want the root directory to be writable though.

**Describe the results you expected:**
Need ability to specify the home directory on the podman run command that will be used when the entry in /etc/passwd is created.

**Additional information you deem important (e.g. issue happens only occasionally):**
```
[mpawlowsky@sigbeehler ~]$ podman exec -u 0:0 -it crazy_driscoll usermod --home /home/mpawlowsky mpawlowsky
usermod: user mpawlowsky is currently used by process 1
[mpawlowsky@sigbeehler ~]$ 
```

Would be nice to have most of the options that exist for useradd, e.g. shell, groups, ...

Using docker exec to change the home directory in /etc/passwd with vi, and creating the home directory, allows gradle to work.

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.14.10
Built:        Tue Dec  8 09:37:43 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
[mpawlowsky@sigbeehler ~]$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-2.fc32.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 81d18b6c3ffc266abdef7ca94c1450e669a6a388'
  cpus: 4
  distribution:
    distribution: fedora
    version: "32"
  eventLogger: journald
  hostname: sigbeehler.genband.com
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.7.7-200.fc32.x86_64
  linkmode: dynamic
  memFree: 2887172096
  memTotal: 16770170880
  ociRuntime:
    name: crun
    package: crun-0.16-1.fc32.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.16
      commit: eb0145e5ad4d8207e84a327248af76663d4e50dd
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.fc32.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 8453603328
  swapTotal: 8455712768
  uptime: 1256h 2m 46.58s (Approximately 52.33 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/mpawlowsky/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.3.0-1.fc32.x86_64
      Version: |-
        fusermount3 version: 3.9.1
        fuse-overlayfs: version 1.3
        FUSE library version 3.9.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/mpawlowsky/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 25
  runRoot: /run/user/1000/containers
  volumePath: /home/mpawlowsky/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1607438263
  BuiltTime: Tue Dec  8 09:37:43 2020
  GitCommit: ""
  GoVersion: go1.14.10
  OsArch: linux/amd64
  Version: 2.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.2.1-1.fc32.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical PC

**Comment by rhatdan** [comment]
$ podman run --userns=keep-id --rm -i -t --name centos  centos grep dwalsh /etc/passwd
dwalsh:*:3267:3267:Daniel J Walsh:/:/bin/sh

**Comment by rhatdan** [comment]
The issue is the /home/dwalsh does not exists inside of the container, to it fails.  If I create a homedir with the correct name in the container then it works.

$ podman run --privileged -v /home:/home --userns=keep-id --rm -i -t --name centos  centos grep dwalsh /etc/passwd
dwalsh:*:3267:3267:Daniel J Walsh:/home/dwalsh:/bin/sh

**Comment by rhatdan** [comment]
$ podman run --privileged -v pwd:/home/dwalsh --userns=keep-id --rm -i -t --name centos  centos echo $HOME
/home/dwalsh
$ podman run -v ./home:/home/dwalsh:Z --userns=keep-id --rm -i -t --name centos  centos echo $HOME
/home/dwalsh

This looks like it it working perfectly,  I am going to close.

**Comment by marcpawl** [comment]
But now we are mapping a directory into the home container.  Which is a nice workaround but still not quite right, since the container is leaking into the outside.

**Comment by rhatdan** [comment]
$ podman run --tmpfs /home/dwash --userns=keep-id --rm -i -t --name centos centos echo $HOME
/home/dwalsh
Or
$ podman run home:/home/dwash --userns=keep-id --rm -i -t --name centos centos echo $HOME
/home/dwalsh

Would also work, which would either create a tmpfs on /home/dwalsh or a volume specific for the container at that site.

Bottom line if an application is going to use $HOME, it is going to expect it to exists.  This is why podman is checking if the homedir exists and then setting it.

Of course you could also run

podman run --env HOME=/tmp ...

But this would not match up with the contents in /etc/passwd.

**Comment by marcpawl** [comment]
That worked like a charm.  Thanks you. 
May I recommend that this be mentioned explicitly in the documentation for "podman run".

keep-id: creates a user namespace where the current rootless user’s UID:GID are mapped to the same values in the container. This option is ignored for containers created by the root user.

**Entries will be created in containers /etc/passwd and /etc/group, using the current users home directory .  If the container does not have the home directory then the root (/) will be used.  You may create a temporary home directory using --tmpfs.  Example:  podman run --tmpfs ${HOME} --userns=keep-id --rm  centos echo $HOME**

**Comment by rhatdan** [comment]
Please open a PR with this exact change and we can get it merged.
