### ISSUE TITLE
"Permission denied" error when running parallel containers that mount and run a single script

### ISSUE THREAD

**Issue by dmach** [containers/podman#8763]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I build a container image and use it as an environment for running tests.
The tests are run in parallel according to the number of CPU cores.
The tests are executed via a script that exists in a working directory and is mounted into the containers.
Running the containers in parallel fails on permission errors. This is related to the shared script that is mounted to all containers.
There is probably some race condition, because adding a sleep fixes the problem (the running containers still run, the sleep doesn't make them run in sequence).

**Steps to reproduce the issue:**

1. echo "#!/bin/sh
date
sleep 5" > script.sh

2. chmod a+x script.sh

3. write the following script and run it:
```
#!/bin/sh

for i in $(seq 3); do
    # the following sleep usually makes the parallel runs work
    # a longer sleep (0.5s) works better
    # sleep 0.1
    podman run \
    --volume .:/root/workdir:rw,Z \
    --workdir /root/workdir \
    -it fedora:33 \
    ./script.sh &
done
```

**Describe the results you received:**
/bin/sh: /root/workdir/./script.sh: Permission denied

**Describe the results you expected:**
dates printed

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.0.0-dev
API Version:  3.0.0
Go Version:   go1.15.6
Built:        Wed Dec 16 00:37:59 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.0-dev
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.22-0.9.dev.git2fbeb9f.fc34.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.22-dev, commit: 87878e20b6fe74f377214092876c0a3745fe221b'
  cpus: 12
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: ws
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.0-0.rc6.20201204git34816d20f173.92.fc34.x86_64
  linkmode: dynamic
  memFree: 19914649600
  memTotal: 33508569088
  ociRuntime:
    name: crun
    package: crun-0.16-1.fc34.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.16
      commit: eb0145e5ad4d8207e84a327248af76663d4e50dd
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-2.dev.git6dc0186.fc34.x86_64
    version: |-
      slirp4netns version 1.1.8+dev
      commit: 6dc0186e020232ae1a6fcc1f7afbc3ea02fd3876
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 12884893696
  swapTotal: 12884893696
  uptime: 5h 17m 31.22s (Approximately 0.21 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/dmach/.config/containers/storage.conf
  containerStore:
    number: 170
    paused: 0
    running: 0
    stopped: 170
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.3+dev-2.dev.git3a1301e.fc34.x86_64
      Version: |-
        fusermount3 version: 3.10.1
        fuse-overlayfs: version 1.3
        FUSE library version 3.10.1
        using FUSE kernel interface version 7.31
  graphRoot: /home/dmach/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 11
  runRoot: /run/user/1000/containers
  volumePath: /home/dmach/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1608075479
  BuiltTime: Wed Dec 16 00:37:59 2020
  GitCommit: ""
  GoVersion: go1.15.6
  OsArch: linux/amd64
  Version: 3.0.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.0.0-0.62.dev.git66e979a.fc34.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora 34 (Rawhide)

**Comment by Luap99** [comment]
I guess this is blocked by selinux. You have to use a lowercase `z` for the volume mount options. see:https://github.com/containers/podman/blob/master/docs/source/markdown/podman-run.1.md#--volume--vsource-volumehost-dircontainer-diroptions

**Comment by dmach** [comment]
Thanks for pointing to the `z` option. It seems to be working fine.
I'm not sure why the `Z` option behaves differently depending on if I use sleep or not.
My expectation is that that podman/overlayfs should always pass or report an error, but maybe I simply don't understand how it works internally and this is expected.

**Comment by rhatdan** [comment]
You :z rather then :Z if you want the content to be shared between containers.  But a better case would be to change your script to do

chcon -t container_file_t -l s0 -R .

And then don't do the :Z or :z

**Comment by Luap99** [comment]
> My expectation is that that podman/overlayfs should always pass or report an error, but maybe I simply don't understand how it works internally and this is expected.

Well that's a classic race condition. Before the container is executed the volume is relabelled. With `Z` only the current container is allowed to access the files. If you run this in parallel the second `podman run` call might have relabelled the directory before the first container executes the script.

**Comment by vrothberg** [comment]
@rhatdan wrote a great blog on this topic that I consult frequently when facing selinux mount issues:

https://www.redhat.com/sysadmin/user-namespaces-selinux-rootless-containers
