### ISSUE TITLE
unix.SIGSTKFLT   was not found when compiled 

### ISSUE THREAD

**Issue by xuan200922702** [containers/podman#8768]
unix.SIGSTKFLT   was not found when compiled 
![image](https://user-images.githubusercontent.com/32674956/102569318-38a49080-4120-11eb-8246-d7724d63cfe5.png)

我通过添加这个信号量，在我的golang.org/unix里

并且成功编译通过

使用podman 的命令 pull  push   都很正常

但是当我运行podman  run  -it   容器    
![image](https://user-images.githubusercontent.com/32674956/102569196-f7ac7c00-411f-11eb-8731-14066d6df840.png)

没有任何反应
我通过sudo tail -f  /var/log/messages  查看日志

![image](https://user-images.githubusercontent.com/32674956/102569252-114dc380-4120-11eb-8907-fbb94ce57bf8.png)

Please help me. Thank you very much

**Comment by zhangguanzhang** [comment]
could you show your os and go version？

**Comment by xuan200922702** [comment]
> could you show your os and go version？

![Uploading image.png…]()

**Comment by xuan200922702** [comment]
> could you show your os and go version？

![Uploading image.png…]()

**Comment by zhangguanzhang** [comment]
which your arch,could you show the  result of command `arch`?

**Comment by xuan200922702** [comment]
> which your arch,could you show the result of command `arch`?

uos@uos-sw:~/go/src/github.com/containers/podman$ arch
sw_64

**Comment by zhangguanzhang** [comment]
what about `go env` print

**Comment by xuan200922702** [comment]
uos@uos-sw:~/go/src/github.com/containers/podman$ go env
GO111MODULE=""
GOARCH="sw64"
GOBIN=""
GOCACHE="/home/uos/.cache/go-build"
GOENV="/home/uos/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="sw64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY="https://gitlabwh.uniontech.com/wuhan/container/gowarehouses"
GONOSUMDB="https://gitlabwh.uniontech.com/wuhan/container/gowarehouses"
GOOS="linux"
GOPATH="/home/uos/go"
GOPRIVATE="https://gitlabwh.uniontech.com/wuhan/container/gowarehouses"
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.14"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.14/pkg/tool/linux_sw64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/uos/go/src/github.com/containers/podman/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build965382663=/tmp/go-build -gno-record-gcc-switches"

**Comment by zhangguanzhang** [comment]
I think the reason lies in the imperfect support of golang for sw64, you can try the latest golang version

**Comment by xuan200922702** [comment]
> I think the reason lies in the imperfect support of golang for sw64, you can try the latest golang version
我在mips64架构也遇到这个问题，使用go1.14.1都是可以的
这个原因和golang本身有关系嘛

**Comment by zhangguanzhang** [comment]
主要是目标架构，golang对sw64的支持不行，目前arm的应该没问题的

**Comment by xuan200922702** [comment]
> 主要是目标架构，golang对sw64的支持不行，目前arm的应该没问题的

我想知道podman 运行过程，哪里影响到了这里。

**Comment by vrothberg** [comment]
As @zhangguanzhang mentioned, Golang does not support sw64, so I am closing the issue.

**Comment by rhatdan** [comment]
I had never heard of sw_64... Had to do some internet searching.

**Comment by xuan200922702** [comment]
> 我从未听说过sw_64 ...必须进行一些Internet搜索。

我想知道podman运行过程，涉及到架构方面，哪里影响到了这里。非常感谢你

**Comment by fishbar** [comment]
@hellocloudnative  the offical Golang does not support sw_64 arch,  you should read this blog https://blog.frytea.com/archives/598/?hmsr=joyk.com&utm_source=joyk.com&utm_medium=referral
