### ISSUE TITLE
Regression: Output formatting no longer supports join (Go template)

### ISSUE THREAD

**Issue by matusmarhefka** [containers/podman#8773]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman (v2.2.1) no longer supports `join` Go template when formatting output using `--format`. This is a regression compared to older podman (e.g. in F31). I haven't tested all Go templates from https://docs.docker.com/config/formatting/ so `join` might not be the only one which is not working.

**Steps to reproduce the issue:**

1. `podman pull fedora`

2. `podman inspect fedora --format '{{join .Config.Env "\n"}}'`

**Describe the results you received:**
`ERRO[0000] Error printing inspect output: template: all inspect:1: function "join" not defined`

**Describe the results you expected:**
```
DISTTAG=f33container
FGC=f33
container=oci
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.5
Built:        Tue Dec  8 09:37:50 2020
OS/Arch:      linux/amd64
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.2.1-1.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes, latest released in Fedora 33.

**Additional information:**

On Fedora 31 this works as expected:
```
# podman inspect fedora --format '{{join .Config.Env "\n"}}'
DISTTAG=f33container
FGC=f33
container=oci
# rpm -q podman 
podman-2.1.1-3.fc31.x86_64
```

**Comment by mheon** [comment]
@jwhonce PTAL

**Comment by vrothberg** [comment]
@jwhonce @ashley-cui do you know what's going on?

**Comment by ashley-cui** [comment]
I don't know exactly where the problem is but I tested on podman 2.1 and it's definitely a regression. I haven't looked into the old code enough to know where join is handled, but its different than table - table is `table {{.Name}}` whereas join is `{{join .Config.Env "\n"}}`, inside the template itself

**Comment by jwhonce** [comment]
@ashley-cui I know what the issue is and will fix it.

**Comment by jwhonce** [comment]
c/common updated with https://github.com/containers/common/pull/426
podman will need to vendor in this update.

**Comment by jwhonce** [comment]
https://github.com/containers/podman/pull/9196 should have included fix in podman
