### ISSUE TITLE
build fails on MIPS systems

### ISSUE THREAD

**Issue by dangowrt** [containers/podman#8782]
/kind bug

podman 2.2.1 fails to build on MIPS (both little and big endian, 32-bit as well as 64-bit) due to some type incompatibility.

```
# github.com/containers/podman/v2/pkg/signal
../../pkg/signal/signal_linux.go:46:14: undefined: unix.SIGSTKFLT
```
as well as

```
# github.com/containers/psgo/internal/dev
../../../../../dl/go-mod-cache/github.com/containers/psgo@v1.5.1/internal/dev/tty.go:116:22: cannot use s.Rdev (type uint32) as type uint64 in argument to minDevNum
../../../../../dl/go-mod-cache/github.com/containers/psgo@v1.5.1/internal/dev/tty.go:117:22: cannot use s.Rdev (type uint32) as type uint64 in argument to majDevNum
```

Please see the links below for full build logs:

https://downloads.openwrt.org/snapshots/faillogs/mips64_octeonplus/packages/podman/compile.txt

https://downloads.openwrt.org/snapshots/faillogs/mips_24kc/packages/podman/compile.txt

https://downloads.openwrt.org/snapshots/faillogs/mipsel_24kc/packages/podman/compile.txt

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Comment by zhangguanzhang** [comment]
`unix.SIGSTKFLT` is that golang does not support mips

**Comment by dangowrt** [comment]
> `unix.SIGSTKFLT` is that golang does not support mips

well, at least officially Go does support MIPS and we do build other golang package in OpenWrt and they do work.
From what I understood Go supports aarch66, arm, i386, i686, mips, mips64, mips64el, mipsel, powerpc64 and x86_64.
Ie. ppc32 and armbe being the most popular exotic ones missing in the list, but all MIPS variants are among the supported architectures.

**Comment by Luap99** [comment]
@dangowrt I opened #8797. Can you try this please I do not have a mips system.

The other error comes from https://github.com/containers/psgo you should open an issue there.
