### ISSUE TITLE
podman :z :Z attack vector on home dir

### ISSUE THREAD

**Issue by abitrolly** [containers/podman#8786]
/kind bug

I've recently submitted a very simple PR to avoid remembering lines when running some app from container, and there people [expressed concerns on using :Z with volume mounts](https://github.com/kaitai-io/kaitai_struct_visualizer/pull/44/files#r543594607) following Docker docs. Namely, that users tend to run a lot of stuff in their home dir, and :Z causes SELinux relabeling of the home, which would "mess their dir". I am not sure what could go wrong. Maybe their `.ssh` will become readable by malicious container process. Would be nice to see this clarified and protected from accidents.

`podman` volumes without :Z do not work on SELinux enabled systems, such as Fedora.

**Comment by rhatdan** [comment]
There is no way to determine this safely. 
I could for example create a directory labeled container_file_t:s0 to share between multiple containers.  In this case we would not want to use the :z or :Z.

**Comment by abitrolly** [comment]
To determine what?

**Comment by rhatdan** [comment]
To determine if :Z/:z will  cause problems or if the relabelling is even needed.

**Comment by abitrolly** [comment]
There can be only one SELinux label per object, right? I can not explicitly set labels just for `podman`?

**Comment by abitrolly** [comment]
I mean set labels for `podman` without overwriting other labels.

**Comment by rhatdan** [comment]
Correct, one label per inode.  SELinux security can not be "proven" if we allowed multi labels on inodes.

**Comment by abitrolly** [comment]
And `podman unshare` doesn't touch labels, right?

**Comment by abitrolly** [comment]
And labels are not restored after `podman -v ...:Z`, right?

**Comment by rhatdan** [comment]
Podman unshare does not touch labels.
podman -v ....:Z will always set labels, it will never restore them.

**Comment by abitrolly** [comment]
What are the consequences of setting podman :Z label on home dir? Like remote SSH login will stop work? Apps won't be able to read their `.config`?

**Comment by rhatdan** [comment]
Bottom line do not do it.  It will screw up other confined domains that need to read that content.

The only time you should use the :Z or :z is if the data directory is just for containers.  If it is shared content you need to either disable SELinux container separation --security-opt label=disable or run with a different type using something like udica to define a different type

--security-opt label=type:UDICATYPE

**Comment by abitrolly** [comment]
Data for containers sounds strange. I use containers to minimize the impact on my data, and the issue is serious enough to read about specific cases before getting to the bottom line. What are those confined domains, what content do they need to read?

**Comment by rhatdan** [comment]
sshd reads ~/.ssh for example.
httpd reads ~/.public 
Lots of others. 

But also on the other hand you want to keep containers away from this content, so you don't want an escaped container process from reading ~/.credit.card.data from home directory.  Labeling your homedir as container content is a bad idea.

**Comment by rhatdan** [comment]
But if you insist on doing this just do 

chcon -t container_file_t ~/

And see what happens.

restorecon -R --force -v ~

Will clean it up for you, if lots of stuff starts to break.

**Comment by baude** [comment]
@rhatdan can we put this to bed?

**Comment by rhatdan** [comment]
I think we have answered this issue.

**Comment by abitrolly** [comment]
> Labeling your homedir as container content is a bad idea.

Without labeling I can not access it from container on Fedora. Even if it is my app that needs this access.

**Comment by abitrolly** [comment]
Unfortunately, there is no filesystem isolation at volume level. There are no drivers for volume mappings that can implement more reliable access rules that other than a single SELinux label for everything.

Therefore to make my system usable without the risk of locking up my system, I need not just to detect if my automation scripts are given the home path to map as a volume, but also if there are any unusual labels that will be destroyed by the `podman` remapping dirs for itself. How can I detect if anything will be remapped as a result of `podman` command?

**Comment by rhatdan** [comment]
No, if you are looking to share your home directory with containers or between containers, then disable SELinux separation.
--security-opt label=disable

Or use udica.

**Comment by abitrolly** [comment]
Am I reading it correctly that there is no way to figure out if running `podman -v ...:Z` would cause remapping (loss of previous values) of SELinux label for some files under the current tree?

**Comment by rhatdan** [comment]
:Z or :z tells podman to force the label to be container specific.  There is no attempt at knowing the ramifications of this from the Podman point of view.  Except for some rudimentary attempt to block certain directories, that we know are a mistake.

Looking at the existing labels, is not something Podman could do, or will do, since the labeling is arbitrary.  And not static across all distributions.
