### ISSUE TITLE
Support DOCKER_CONFIG environment variable

### ISSUE THREAD

**Issue by ArjenKorevaar** [containers/podman#8796]
/kind feature

podman doesn't support the use of DOCKER_CONFIG environment variable, breaking compatibility with docker CLI.

We use Azure DevOps build agents to build and deploy containers to OpenShift. One step in our pipeline is pushing docker images to a Quay repository using an authentication token (Quay calls this a Robot Token).

This token is configured in Azure DevOps using a Docker Registry service connection, much like how it is described [here](https://www.redhat.com/en/blog/using-red-hat-universal-base-image-azure-pipelines-and-red-hat-quayio). The build proces takes this token, saves it to a temporary config.json file and sets the DOCKER_CONFIG environment variable before calling docker push. Using docker CLI, this would do the trick. Podman ignores this DOCKER_CONFIG environment variable, resulting in unauthorized calls to the Quay image repository.

Podman does support the use of REGISTRY_AUTH_FILE environment variable and an --authfile option. This is also discussed in #1340. However, Azure DevOps doesn't have any Podman build or deploy steps, just the Docker steps.

One could argue that the Azure DevOps Docker steps need to be changed, or that Podman compatible steps need to be developed next to Docker steps.. but given that Podman aims to provide "support for a Docker-compatible CLI interface", I would like to request  support for DOCKER_CONFIG file (as well as the --config CLI argument).

**Comment by mheon** [comment]
We intend to provide command line and API compatibility with Docker. We
have not extended that promise to configuration file compatibility. I am
somewhat hesitant to develop an entirely parallel way of configuring Podman
and then exposing this as a first class citizen via CLI, confusing users at
to what the right configuration files to use; it would be a very large
amount of complexity and potential confusion to enable this.

**Comment by ArjenKorevaar** [comment]
Hi @mheon , thank you for your reply.

I understand your point of view, however this would mean that next to the current support of Docker, we would have to develop custom Azure DevOps build and release components to support Podman. And this would probably be the case for other CI/CD tools as well (such as Jenkins as mentioned in #1340).

I am not saying that that is an issue per se, but the whole "compatible with Docker" becomes more or less useless to us if we need to develop custom support for Podman. Podman is either compatible with Docker, or it's not. And currently it is not.

**Comment by rhatdan** [comment]
I think we could add support for DOCKER_CONFIG to point the REGISTRY_AUTH_FILE at, if the environment was not set.
IE Check REGISTRY_AUTH_FILE then DOCKER_CONFIG.  BUT this would only be for support of the credentials, since we currently support credentials from $HOME/.docker/config.json.

**Comment by ArjenKorevaar** [comment]
@rhatdan, thank you for your reply. I would appreciate that, since it would solve our current issue with the Azure DevOps pipelines.

> BUT this would only be for support of the credentials, since we currently support credentials from $HOME/.docker/config.json.

In general, if you aim to be compatible with Docker, and even claim things like "Simply put: alias docker=podman." (and that's also how the podman-docker rpm package installs itself), you should make sure you are 100% compatible so that programs that rely on Docker won't break after installing Podman.

We use standard components: an Azure DevOps pipeline, Quay image registry and OpenShift container hosting platform and out-of-the-box build steps to build and push a container. No custom code or configuration, nothing fancy.. but it breaks on Podman. Imho that is a really bad thing.

**Comment by rhatdan** [comment]
I would hesitate that we plan to be 100% compatible.  The original promise was to be as CLI compatible as possible, which I believe we have achieved.  Now we have moved to API Compatibility with APIV V2

But we make choices that are incompatible for certain features like:

- We do not plan to create like docker swarm.  
- Features we did not implement the same way like docker network versus podman network.
- Features we see as bugs in Docker.  For example Docker will create a src directory on the host where Podman does not.
- Certain outputs of commands like podman info and podman inspect are not identical to Docker. Some for bug reasons that can not be fixed without Podman breaking its own compatibility some because fields are just different. Line network above.
- Finally limited support for configuration files. Docker never made configuration files a priority, so we have gone our own way.
-

**Comment by ArjenKorevaar** [comment]
> The original promise was to be as CLI compatible as possible

I'm sorry, but that is not what "alias docker=podman" says.

I understand why you would not want to pin down to being 100% compatible.. for reasons you already mentioned and probably some more giving it some thinking. But that would make Podman 'similar' to Docker and not an alias. What happens now is that podman is treated as a substitute for docker, assuming everything will continue to work as expected after installing podman and that is simply (and understandably) not the case.

So, Podman is an (arguably better) alternative to Docker. Similar but not the same. And definately not an alias. Which means that support for Podman needs to be developed (and maintained) for things like Azure DevOps pipelines.

**Comment by rhatdan** [comment]
Sure, bottom line, if the change and simple and not necessary to conflict, then we will make the change.  But we reserve the rights to have differences.
The goal with `alias docker=podman` was to explain to users, that it would be easy for the general user to convert from docker to podman.  Now we are dealing with more of the corner cases, where we are only 90% compatible.  

Bottom line supporting things like docker-compose and docker-py are the harder problems at this point.  When looking at CI/CD systems that is where we are seeing breakage and are working hard to fix.

**Comment by rhatdan** [comment]
@QiWang19 @mtrmac Points out that podman should fail over to use DOCKER_CONFIG if it is set.

**Comment by mtrmac** [comment]
It already can do so as of https://github.com/containers/image/pull/1056 .

**Comment by rhatdan** [comment]
Which means this was fixed as of podman 2.2.

**Comment by ArjenKorevaar** [comment]
Right, I have not searched the containers/image github, just containers/podman for issues or PR's related to DOCKER_CONFIG.

This remains to be an issue for us though, as we run RHEL 8 and cannot simply upgrade Podman to version 2.2 because of its dependencies.

> Now we are dealing with more of the corner cases

No, we're dealing with enterprise environments in which claims like "alias docker=podman" can have large consequences.

**Comment by rhatdan** [comment]
Podman 2.2.1 will be available for RHEL 8 in February.
