### ISSUE TITLE
How do I set the tag to <none> but repository to be <none>

### ISSUE THREAD

**Issue by l30006821** [containers/podman#8811]
like this:
`REPOSITORY                           TAG                                                  IMAGE ID         CREATED      SIZE`
`quay.io/openshift/okd          <none>                                            9b89d802f81d  10 days ago  321 MB`

**Comment by rhatdan** [comment]
Please explain what you are trying to do?

**Comment by l30006821** [comment]
thank for your reply, I just started podman. I used the command 'podman save -o xxxxx.tar imageID' to save an image to my hard drive and load it onto another computer. Podman performs a pull operation when the image is already there.Is this because of tag inconsistency? I want to change their tags to match the source host to test
