### ISSUE TITLE
[Podman 2.2.1] rootless works, as root I get a system error

### ISSUE THREAD

**Issue by p7kdev** [containers/podman#8812]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Hi, I am currently struggling with a problem here and hope I am in the right place.

When I start a container as root, I get the following error:
```shell
$ id -u
0

$ podman run -ti ubuntu:16.04 su
su: System error
```
Adding CAP_AUDIT_WRITE will remedy the situation.

```shell
$ id -u
0

$ podman run --cap-add audit_write -ti ubuntu:16.04 su
root@e2649f92006a:/#

```
When I start the container rootless, everything works fine
```shell
$ id -u
1000

$  podman run -ti ubuntu:16.04 su
root@70cffdaaaea9:/#
```

Even if I drop the permissions

```shell
$ id -u
1000

$ podman run --cap-drop audit_write -ti ubuntu:16.04 su
root@5c6772348c85:/#
```

That's a little strange. Why doesn't this work as root user?

**Additional information you deem important (e.g. issue happens only occasionally):**

Downgrade to 2.1.1 has helped temporarily.  But probably only because the CAP_AUDIT_WRITE flag is still set there, but fails of course as soon as I drop the CAP.

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.5
Built:        Tue Dec  8 15:37:50 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-3.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 0f53fb68333bdead5fe4dc5175703e22cf9882ab'
  cpus: 12
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: localhost
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.9.14-200.fc33.x86_64
  linkmode: dynamic
  memFree: 670806016
  memTotal: 16772382720
  ociRuntime:
    name: crun
    package: crun-0.16-1.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.16
      commit: eb0145e5ad4d8207e84a327248af76663d4e50dd
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 8585732096
  swapTotal: 8585732096
  uptime: 1h 16m 2.96s (Approximately 0.04 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 0
    stopped: 6
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 1
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1607438270
  BuiltTime: Tue Dec  8 15:37:50 2020
  GitCommit: ""
  GoVersion: go1.15.5
  OsArch: linux/amd64
  Version: 2.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.2.1-1.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
I think the libraries that are trying to write the audit.log are smart enough to know if the process is running as real/root versus running as the user UID, and in the non root case, it ignores the fact that it can not write an audit message.  When running as real/root it is not ignored, causing the error to be pushed up to su, causing it to fail.
