### ISSUE TITLE
Rootfull port forwarding not working

### ISSUE THREAD

**Issue by RomainNakedCat** [containers/podman#8814]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
/kind bug
**Description**
If you run any container with Podman you cannot access the service from remote machines despite -p. Only way to do it is to use --network=host

**Steps to reproduce the issue:**

1. podman run -d  -p 80:80 nginx
2. curl my_address 80

**Describe the results you received:**
curl: (7) Failed to connect to my_address port 80: Connection timed out

**Describe the results you expected:**
```
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.22, commit: '
  cpus: 48
  distribution:
    distribution: ubuntu
    version: "18.04"
  eventLogger: journald
  hostname: controller-1
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.15.0-128-generic
  linkmode: dynamic
  memFree: 126855479296
  memTotal: 135093325824
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 137338286080
  swapTotal: 137338286080
  uptime: 20h 8m 0.15s (Approximately 0.83 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 1
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 18
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.2.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 2.2.1~4 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes => using last version and nothing about rootfull container

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical server ubuntu 18.04.5

**Comment by rhatdan** [comment]
Podman does NOT automatically open a Hole in your firewall rules.  So you need to open the firewall rules for port 80.

**Comment by RomainNakedCat** [comment]
I do not need to open anything because chain INPUT uses an accept policy

**Comment by mheon** [comment]
Please provide ‘iptables -t nat -nvL’ and ‘iptables -nvL’ both with and
without the container in question running. Also , do you use any external
software (e.g. firewalld) to manage the system firewall?

**Comment by RomainNakedCat** [comment]
Hello,

When I checked iptables rules i figured out the problem. I'm migrating from Docker to Podman but `apt purge docker.io` didnt remove any docker chains. Docker was taking over Podman that's why it didnt work. It's not a Podman issue.

Sorry for the inconvenience
