### ISSUE TITLE
`podman exec -t <container>/bin/sh` hangs

### ISSUE THREAD

**Issue by v42net** [containers/podman#8815]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

After starting a container (for instance Alpine), executing /bin/sh in that container hangs. This happens both rootfull and rootless.

**Steps to reproduce the issue:**

1. Via one bash session on the host: `podman run -t --rm --name=test alpine:latest`
2. Via another bash session on the host:  `podman exec -t test /bin/sh`

**Describe the results you received:**

1. The second session hangs and cannot be detached
2. The first session can be used to exit the container (which terminates the second session)

**Describe the results you expected:**

Both /bin/sh sessions can be used normally and allows them to be detached

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.0.5
API Version:  1
Go Version:   go1.14.7
Built:        Sat Nov  7 11:18:34 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.1
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.20-2.module+el8.3.0+7866+f387f528.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.20, commit: 68196d58ce37bc799ff4cf59f50a0fe7e1382b74'
  cpus: 2
  distribution:
    distribution: '"ol"'
    version: "8.3"
  eventLogger: file
  hostname: NLDTMGN05.cmf.atos-srv.net
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.4.17-2036.101.2.el8uek.x86_64
  linkmode: dynamic
  memFree: 1270898688
  memTotal: 3823841280
  ociRuntime:
    name: runc
    package: runc-1.0.0-68.rc92.module+el8.3.0+7866+f387f528.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-2.module+el8.3.0+7866+f387f528.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 3424632832
  swapTotal: 3439325184
  uptime: 43h 22m 58.75s (Approximately 1.79 days)
registries:
  search:
  - container-registry.oracle.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  configFile: /home/nagios/.config/containers/storage.conf
  containerStore:
    number: 15
    paused: 0
    running: 0
    stopped: 15
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-3.module+el8.3.0+7866+f387f528.x86_64
      Version: |-
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/nagios/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 45
  runRoot: /run/user/1001/containers
  volumePath: /home/nagios/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1604744314
  BuiltTime: Sat Nov  7 11:18:34 2020
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.0.5
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.5-5.0.1.module+el8.3.0+7866+f387f528.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

- No, I did not test a newer version: this is the latest version available from the Oracle Linux 8 repository
- Yes, I did check the Troubleshooting Guide but there was nothing in it that halped me.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Up to date VMware ESX VM with 2 CPU's and 4 GB memory. Docker on Oracle Linux 7 was running fine on the same VM.
I decided to upgrade this VM to Podman on Oracle Linux 8 to check if we can start migrating our existing environment (last time I checked was 6 months ago). It seems we have to stick with Docker on Oracle Linux 7 for some more time ...

**Comment by v42net** [comment]
**OS version:**

Oracle Linux Server release 8.3

**Rootfull output of `podman info --debug`:**
```
host:
  arch: amd64
  buildahVersion: 1.15.1
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.20-2.module+el8.3.0+7866+f387f528.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.20, commit: 68196d58ce37bc799ff4cf59f50a0fe7e1382b74'
  cpus: 2
  distribution:
    distribution: '"ol"'
    version: "8.3"
  eventLogger: file
  hostname: NLDTMGN05.cmf.atos-srv.net
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.17-2036.101.2.el8uek.x86_64
  linkmode: dynamic
  memFree: 1268482048
  memTotal: 3823841280
  ociRuntime:
    name: runc
    package: runc-1.0.0-68.rc92.module+el8.3.0+7866+f387f528.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 3424632832
  swapTotal: 3439325184
  uptime: 43h 35m 43.36s (Approximately 1.79 days)
registries:
  search:
  - container-registry.oracle.com
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.centos.org
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 1
    stopped: 3
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 2
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1604744314
  BuiltTime: Sat Nov  7 11:18:34 2020
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.0.5
```

**Comment by mheon** [comment]
We’ve made numerous fixes to Exec in subsequent releases. I’m betting this
is probably fixed in a future upstream release.

**Comment by Luap99** [comment]
You need `-i` for podman run/exec to have a interactive terminal

**Comment by rhatdan** [comment]
Should be fixed in podman 2.2.1 which is shipping in February if the addition of the -i flag does not fix it.
BTW This should be reported in bugzilla not in the upstream.

**Comment by v42net** [comment]
The missing `-i` for podman run/exec was a typo while raising this issue.

After some time the first `podman run` session also started hanging, so I suspected something else must be causing this.
So I started, again, with a fresh install of Oracle Linux 8, and found that everything now worked fine.

Going over my notes I found the difference between the two Oracle Linux 8 installations:

- On the first OL8 installation `podman run -it alpine` successfully pulled alpine, but failed to run. This was caused by SElinux, so I disabled SElinux and rebooted the system. Now alpine runs okay, but the problem described above occurred.
- On the second OL8 installation I disabled SElinux and rebooted right after installing OL8 and before updating or installing any packages. This time `podman run -it alpine` successfully pulls and runs alpine okay and all problems are gone.

I compared the output of `podman info --debug` but did not find any differences that might explain the issue.
My guess is that the first failure to run alpine caused *something* that resulted in this problem after disabling SElinux.
As I did not have a spare VM, I had to reuse it for the second OL8 installation. So I'm not able to investigate any further.

And thanks for the redirection: next time I'll use bugzilla or even start with raising the issue with Oracle as they are providing the Podman version I'm using.

Thanks for your time and best wishes for the holidays and a happy 2021 !!!

**Comment by rhatdan** [comment]
Sad to see you disabling SELinux, this should never be required.

**Comment by v42net** [comment]
I agree, but I'm using a default minimal install of Oracle Linux 8 (8.3) with Podman from the Oracle Linux repository.
Rootless `podman run -it alpine` successfully pulls alpine but fails to run. This happened to me before on OL 8.1.
I know, I should try to solve the root cause, but I'm also expected to deliver a new application in time ... 
As soon as SELinux does not cause issues anymore, I'll certainly not disable it anymore: I always prefer minimal changes to a default minimal install as the basis for all applications.

**Comment by rhatdan** [comment]
What issue did SELinux cause?  Perhaps I could help diagnose the issue.  Do you have the AVC messages?
