### ISSUE TITLE
Wrap container into single binary using podman

### ISSUE THREAD

**Issue by abitrolly** [containers/podman#8817]
/kind feature

Once in a while I need to do this.
```
podman run -v "$(pwd)":"/root/app":Z -w "/root/app" -it heroku/heroku:18-build
```
Basically regenerate a single `Gemfile.lock` file in current directory. And I want to delegate the task to somebody else. And I want to make it a single binary, for example, `regen`, so that the person could just download and run `regen` without additional `apt-get/choco/dnf install/update/etc` hassle.

Is that possible to build such binary with `podman`? That will run in userspace and won't create any additional files outside of the current project dir.

**Comment by rhatdan** [comment]
If you mean could you bundle up everything that is podman along with this command into a single binary, the answer is no.

Podman relies on other packages to run containers.  It requires a containers monitor (conmon) It uses an OCI Runtime (runc, crun, kata).  If you run rootless, it also needs slirp4netns, fuse-overlayfs.  It uses the containers-common package for most of its configuration also.

**Comment by baude** [comment]
to me this sounds like you shouild make your own image and push it to a registry.  then use podman container runlabel to build the gem.

https://github.com/containers/podman/blob/master/docs/source/markdown/podman-container-runlabel.1.md

**Comment by abitrolly** [comment]
>  It requires a containers monitor (conmon) It uses an OCI Runtime (runc, crun, kata). If you run rootless, it also needs slirp4netns, fuse-overlayfs. It uses the containers-common package for most of its configuration also.

Is it possible to decouple this to run completely in userspace? If not, what `kernel` interfaces should be supported out of the box to make the user OS "portable podman friendly"?

**Comment by rhatdan** [comment]
I really do not understand what you are after.  Any OCI Image is podman friendly and should run on any Linux OS that has podman.

**Comment by abitrolly** [comment]
@baude nice feature, thanks. Although **-v /:/host** makes me nervous about trusting Docker Hub. :D
```

**Comment by rhatdan** [comment]
@abitrolly you should not trust images period.  But doing -v/:/host gives them full reign on your host.

**Comment by abitrolly** [comment]
@rhatdan I want to ensure that any Linux DevOps can run that, like any other tool written in Go and compiled into single binary. Not every Linux OS has `podman`.

**Comment by rhatdan** [comment]
Well that is the rub.  You need a container engine to run a container image.  (Podman, Docker, CRI-O, Containerd, Buildah...)
Any one of these can run an image created by Podman, but one of them is required.

**Comment by abitrolly** [comment]
@rhatdan so no containers in userspace without some engine one leg in `kernel`? I had a hope that Linux containers got a leg in userspace finally. :D

**Comment by imperialguy** [comment]
@rhatdan A little out of topic, but are there any plans to release podman runtime for both Windows/Mac anytime soon?

**Comment by rhatdan** [comment]
Answered in other places. NO windows or MAC native support.  Not going to happen.

@abitrolly you need a tool to pull the image, store it and configure the linux kernel to run it.  So yes you need an engine.  You could build a tool to embed all of this into one executable, but no one has done that.

**Comment by abitrolly** [comment]
@imperialguy hey, that's hijacking the thread! :D

@rhatdan I guess the imperial question is not about native support, so shipping `podman` as a binary with QEMU and Linux under the hood may solve that problem.

The part with pulling and storing the image is possible in userspace. But is it possible to configuring Linux kernel to run the image from the userspace?

**Comment by rhatdan** [comment]
I am going to close this since it is not likely to happen.

**Comment by abitrolly** [comment]
Linux kernel is unlikely to run in userspace as a container without additional software?
