### ISSUE TITLE
what is the best way to implement pre-copy for container checkpointing?

### ISSUE THREAD

**Issue by yufeifly** [containers/podman#8825]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
criu implements precopy for checkpointing. I want to use precopy feature in podman. Is it feasible? What can I do to implement this feature?

**Describe the results you expected:**
podman supports precopy for container checkpointing.

**Comment by rhatdan** [comment]
@adrianreber PTAL

**Comment by rhatdan** [comment]
BTW, is https://github.com/containers/podman/pull/8819 something you need?

**Comment by yufeifly** [comment]
> BTW, is #8819 something you need?

yes, it is. I will look at it. Thank you!

**Comment by rhatdan** [comment]
I think this issue is fixed, reopen if I am mistaken.
