### ISSUE TITLE
podman unable to spin up containers in WSL (not WSL2) Ubuntu 20.04

### ISSUE THREAD

**Issue by imperialguy** [containers/podman#8826]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
podman unable to spin up containers in WSL (not WSL2) Ubuntu 20.04. 

**Steps to reproduce the issue:**

1. Install WSL ubuntu 20.04 on Windows 10. Install podman. Switch to root and update container.conf with cgroup_manager = "cgroupfs"  and events_logger = "file"

2.  Try spinning up a container using any image. For example, this is what I did:
     ```podman run -it registry.access.redhat.com/ubi8/ubi-minimal bash```

**Describe the results you received:**
```
Your kernel does not support pids limit capabilities or the cgroup is not mounted. PIDs limit discarded.
Error: error creating network namespace for container 1c450a359a05cf89b4b8580f314bb3d2a1aa4ca828c5f71f6be297307d7b9e20: failed to create namespace: permission denied
```

**Describe the results you expected:**
I expected the container to be up and running.

**Additional information you deem important (e.g. issue happens only occasionally):**

I ran these commands as root because non-root was not working at all, which appears to be a separate issue altogether. I posted that issue [here](https://github.com/containers/podman/issues/8827).

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.2
Built:        Wed Dec 31 19:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.22, commit: '
  cpus: 4
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: file
  hostname: DESKTOP-AQIHC5B
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.4.0-19041-Microsoft
  linkmode: dynamic
  memFree: 10876375040
  memTotal: 17179324416
  ociRuntime:
    name: runc
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 29992464384
  swapTotal: 29992464384
  uptime: 10h 25m 43.75s (Approximately 0.42 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 0
    stopped: 5
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: <unknown>
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 0
  BuiltTime: Wed Dec 31 19:00:00 1969
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 2.2.1~4 amd64 [installed]
podman/unknown 2.2.1~4 arm64
podman/unknown 2.2.1~4 armhf
podman/unknown 2.2.1~4 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is tested on a Ubuntu WSL running inside a Windows 10 VM.

**Comment by mheon** [comment]
I think this is expected. Among the main advertised features of WSL2 was
support for containers, which implies that WSL1 lacked such support. Is
there any reason you cannot use WSL2?

**Comment by rhatdan** [comment]
Not supported.
