### ISSUE TITLE
Fish completion not working as expected

### ISSUE THREAD

**Issue by pastalian** [containers/podman#8829]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Fish completion will not work if the command is prefixed with a space.

**Steps to reproduce the issue:**

1. In fish shell, type `<SPACE>podman<SPACE>`

2. Press TAB

**Describe the results you received:**

Fish shows file completion
```
❯  podman
bspwm_0_0-socket  fcitx-socket-:0  nvimgPYgkx/  tmux-1000/
```

**Describe the results you expected:**

Fish shows command completion
```
❯ podman
attach                                      (Attach to a running container)
auto-update  (Auto update containers according to their auto-update policy)
build               (Build an image using instructions from Containerfiles)
commit                    (Create new image based on the changed container)
…and 51 more rows
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.6
Git Commit:   a0d478edea7f775b7ce32f8eb1a01e75374486cb
Built:        Thu Dec 24 19:42:33 2020
OS/Arch:      linux/amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
❯ fish --version
fish, version 3.1.2
```

**Comment by rhatdan** [comment]
@Luap99 @edsantiago PTAL

**Comment by Luap99** [comment]
@pastalian Thanks for reaching out. Podman does not create the shell scripts they are auto generated by the [spf13/cobra](https://github.com/spf13/cobra) library. I will debug this and open a issue there.
