### ISSUE TITLE
Rootless network serious bandwidth reduction?

### ISSUE THREAD

**Issue by bitstrings** [containers/podman#8834]
In rootless, upload speed is seriously reduced, using a 1Gbps link I'm only getting ~100Mbps top.

The funny thing is, download speed seems to be full speed, ~940Mbps.

I am not sure if I should open an issue with slirp4netns. 

This is with all latest versions.

Is this something expected? Is there some configuration I could try? Hopefully this is not normal.

**Comment by ocafebabe** [comment]
I'm observing the same behaviour as @bitstrings.

On a local gigabit network, between 2 hosts on the same switch, iperf3 download is maxed out at **940 Mbps** but the upload average is **+/-100 Mbps**...

Server is Linux Mint 20 and client is Podman 2.2.1 (slirp4netns 1.1.7) running on Ubuntu 20.04 (WSL2).

**Comment by ocafebabe** [comment]
To exclude slirp4netns from the equation, I've tweaked their iPerf benchmark [script](https://github.com/rootless-containers/slirp4netns/blob/master/benchmarks/benchmark-iperf3.sh) to reproduce what I was doing in my tests: the container is uploading to a different host than the one hosting it (10.0.2.2). The results are consistent: the upload speed is maxed out on a gigabit network.

So the problem doesn't seem to be with slirp4netns but with podman.

**Comment by AkihiroSuda** [comment]
@ocafebabe Thanks for testing.  Podman launches slirp4netns with --mtu=65520 by default. Do you see the bandwidth issue if you run benchmark-iperf3.sh with MTU=65520, or  let Podman launch slirp4netns with --mtu=1500?

https://github.com/containers/podman/blob/479fc226044b745ecaafc2d5fa925afe6ca06de0/libpod/networking_linux.go#L362

**Comment by ocafebabe** [comment]
@AkihiroSuda it's confirmed: I ran the slirp4netns benchmark with a MTU value of 65520 and I got the same drop in bandwidth.
[slirp4netns_mtu_benchmark.txt](https://github.com/containers/podman/files/5875161/slirp4netns_mtu_benchmark.txt)

Do you have an example showing how to override the default MTU with podman? I don't see any options in the man pages...

**Comment by rhatdan** [comment]
You might need to compile it from hand.  @AkihiroSuda Should we add this to containers.conf so that users could set it?

**Comment by bitstrings** [comment]
@rhatdan I believe it would be the right thing to do. Also, why is `65520` the default?

**Comment by rhatdan** [comment]
I have no idea where that number comes from @mheon @giuseppe Any ideas?

**Comment by rhatdan** [comment]
@bitstrings Interested in opening a PR for containers/common to add it?

**Comment by ocafebabe** [comment]
> I have no idea where that number comes from @mheon @giuseppe Any ideas?

@rhatdan it seems that the default MTU was set to 65520 here: #1732

**Comment by rhatdan** [comment]
@ocafebabe Thanks.

**Comment by giuseppe** [comment]
I think it should be made configurable.  I'll be glad to assist anyone who is interested to work on this issue.

**Comment by bitstrings** [comment]
To test without recompiling and using whatever MTU:

file: slirp4netns (chmod +x)
```
#!/bin/bash
/bin/slirp4netns $(echo "$@" | sed 's/65520/1500/')
```
assuming script is under `./`
(example)
```
PATH=".:$PATH" podman run -it ubuntu:20.04
```

**Comment by ocafebabe** [comment]
I ran my benchmarks again using @bitstrings script to override the MTU and it's pretty conclusive:

1. Vanilla test  (MTU == 65520) -> [iperf3-old-mtu.txt](https://github.com/containers/podman/files/5890063/iperf3-old-mtu.txt)
2. Test with the overriding script (MTU == 1500) -> [iperf3-new-mtu.txt](https://github.com/containers/podman/files/5890051/iperf3-new-mtu.txt)

As you can see, the bandwidth difference is huge between both tests and the second one is what I would expect under normal circumstances...

**Comment by rhatdan** [comment]
@giuseppe and others what should we call the option in containers.conf?

rootless_mtu?

**Comment by mheon** [comment]
Slirp isn't just allowed as rootless. `slirp4netns_mtu` maybe?

**Comment by bitstrings** [comment]
Maybe, `slirp_mtu` ?

Makes it a bit lib agnostic?

**Comment by rhatdan** [comment]
Interested in opening a PR?

**Comment by bitstrings** [comment]
@rhatdan Well, I'll see if I have time this weekend.

**Comment by bitstrings** [comment]
Wait, I didn't notice but in `containers.conf` I see:
```
# Path to the slirp4netns binary
#
# network_cmd_path=""

# Default options to pass to the slirp4netns binary.
# For example "allow_host_loopback=true"
#
# network_cmd_options=[]
```

So I guess `mtu` as an option should work?

So the only real change would be not explicitly setting the `mtu` and let the user do:
```
network_cmd_options=["mtu=9000"]
```
?

**Comment by bitstrings** [comment]
Quick coding WIP: https://github.com/bitstrings/podman/commit/62f179672231a3ae6d2a52e5ce6fb15ca8273a6c

Feedback welcomed...

**Comment by rhatdan** [comment]
Not sure what the ask is?  Is this currently supported in containers.conf and podman, to be able to modify the MTU.  So should this issue be closed?
