### ISSUE TITLE
container podman showing after reboot what we can do

### ISSUE THREAD

**Issue by arjunw007** [containers/podman#8838]
ERRO[0000] error joining network namespace for container c314debfc0b299d09cf620247ed9c811afb6ef9cdf7a98978f4647403b821b0b: error retrieving network namespace at /tmp/run-1002/netns/cni-3fcbc990-2e9d-9d4f-9eae-6a9ddf45c1f1: unknown FS magic on "/tmp/run-1002/netns/cni-3fcbc990-2e9d-9d4f-9eae-6a9ddf45c1f1": 58465342

**Comment by rhatdan** [comment]
Basically this is saying the file system of the path  /tmp/run-1002/netns/cni-3fcbc990-2e9d-9d4f-9eae-6a9ddf45c1f
is not a PROC or NSFS file system.

```
func IsNSorErr(nspath string) error {
	stat := syscall.Statfs_t{}
	if err := syscall.Statfs(nspath, &stat); err != nil {
		if os.IsNotExist(err) {
			err = NSPathNotExistErr{msg: fmt.Sprintf("failed to Statfs %q: %v", nspath, err)}
		} else {
			err = fmt.Errorf("failed to Statfs %q: %v", nspath, err)
		}
		return err
	}

	switch stat.Type {
	case PROCFS_MAGIC, NSFS_MAGIC:
		return nil
	default:
		return NSPathNotNSErr{msg: fmt.Sprintf("unknown FS magic on %q: %x", nspath, stat.Type)}
	}
}
```

**Comment by rhatdan** [comment]
Probably means the network namespace does not exists.

**Comment by arjunw007** [comment]
I got these solution I did mistake that was I didn't created systemd service for container that where I created
