### ISSUE TITLE
Rootless Bug Report - pihole image-series

### ISSUE THREAD

**Issue by NickJLange** [containers/podman#8839]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Root-less podman fails to complete a pull of pihole (although other images have exhibited this in the past). Pulling the same image as root works just fine.

**Steps to reproduce the issue:**

1. podman --version
```
podman version 2.1.1
```

2. podman pull pihole/pihole:v5.3.4-armhf-busterpodman

**Describe the results you received:**

```
Writing manifest to image destination
Storing signatures
  invalid argument
Trying to pull registry.fedoraproject.org/pihole/pihole:v5.3.4-armhf-buster...
  manifest unknown: manifest unknown
Trying to pull registry.access.redhat.com/pihole/pihole:v5.3.4-armhf-buster...
  name unknown: Repo not found
Error: unable to pull pihole/pihole:v5.3.4-armhf-buster: 3 errors occurred:
	* Error committing the finished image: error adding layer with blob "sha256:57d855fc4bf16475719b18bc379d5a973f566877a1920de2e8f92dff2fa017fb": error creating layer with ID "0ec38d325952e916259e2f38536af0f94c46280489928d92d3d49b97a8404182": invalid argument
```

**Describe the results you expected:**

<image id>
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman --version
podman version 2.1.1
```

**Output of `podman info --debug`:**

```
 podman info --debug
host:
  arch: arm
  buildahVersion: 1.16.1
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/local/libexec/podman/conmon
    version: 'conmon version 2.0.21, commit: 35a2fa83022e56e18af7e6a865ba5d7165fa2a4a'
  cpus: 4
  distribution:
    distribution: raspbian
    version: unknown
  eventLogger: journald
  hostname: terraPhi
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.4.51-v7l+
  linkmode: dynamic
  memFree: 341753856
  memTotal: 896733184
  ociRuntime:
    name: runc
    package: 'runc: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0~rc92+dfsg1
      commit: 1.0.0~rc92+dfsg1-5
      spec: 1.0.2-dev
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 0.2.3
      commit: be6d34ba4c7ac62b9f31b0ea931ec91a5f16dc3b
  swapFree: 0
  swapTotal: 0
  uptime: 146h 5m 0.23s (Approximately 6.08 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  configFile: /home/njl/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/njl/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 2
  runRoot: /run/user/1001/containers
  volumePath: /home/njl/.local/share/containers/storage/volumes
version:
  APIVersion: 2.0.0
  Built: 1609011822
  BuiltTime: Sat Dec 26 19:43:42 2020
  GitCommit: 9f6d6ba0b314d86521b66183c9ce48eaa2da1de2
  GoVersion: go1.14.7
  OsArch: linux/arm
  Version: 2.1.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes - I find the lack of debug jump off points frustrating. Open to new ideas here.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
armhf arch on rpi4.

**Comment by rhatdan** [comment]
This indicates that a UID/GID inside of the image is not within the range of UIDs/GIDs specified for the user.

For example the default rootless user only has 65536 UIDs.  If an image has a UID > 65536 then the Pull will fail.

**Comment by rhatdan** [comment]
BTW I am not finding this image anywhere?

**Comment by NickJLange** [comment]
> This indicates that a UID/GID inside of the image is not within the range of UIDs/GIDs specified for the user.
> 
> For example the default rootless user only has 65536 UIDs. If an image has a UID > 65536 then the Pull will fail.
Thank you. How could one read the tea-leaves to figure out this error without raising an issue on GitHub?  :-) This error is non-obvious but I had seen references to this kind-of-issue.. that said, I'm not sure the Docker image is actually generating any multi-user ids although again, open to ideas on how to track that down. 

> BTW I am not finding this image anywhere?

https://hub.docker.com/r/pihole/pihole /
https://github.com/pi-hole/docker-pi-hole

thank you for responding.

**Comment by rhatdan** [comment]
Strange this worked fine for me.

```
$ podman pull pihole/pihole
Completed short name "pihole/pihole" with unqualified-search registries (origin: /etc/containers/registries.conf)
Trying to pull registry.fedoraproject.org/pihole/pihole:latest...
  manifest unknown: manifest unknown
Trying to pull registry.access.redhat.com/pihole/pihole:latest...
  name unknown: Repo not found
Trying to pull registry.centos.org/pihole/pihole:latest...
  manifest unknown: manifest unknown
Trying to pull docker.io/pihole/pihole:latest...
Getting image source signatures
Copying blob d96b1be31a58 done  
Copying blob 23408a6cc8f8 done  
Copying blob dfb6a7ca3fea done  
Copying blob 313b77f8dddb done  
Copying blob fa614ec02b0b done  
Copying blob 6ec7b7d162b2 done  
Copying blob d109af080552 done  
Copying blob c321ec849636 done  
Copying blob c337f5920d89 done  
Copying blob 7446300e026d done  
Copying blob be54c32d9c40 done  
Copying blob a3707270fb79 done  
Copying blob 76398051b4cd done  
Copying config 4e52755957 done  
Writing manifest to image destination
Storing signatures
4e527559577f094619f5b76fc502cddd84bfeb4bf6b0a59d92cfd90767612fb8
$ podman unshare cat /proc/self/uid_map 
         0       3267          1
         1     100000      65536
```

**Comment by rhatdan** [comment]
$ rpm -q podman fuse-overlayfs
podman-2.2.1-1.fc33.x86_64
fuse-overlayfs-1.3.0-1.fc33.x86_64

**Comment by NickJLange** [comment]
> $ rpm -q podman fuse-overlayfs
> podman-2.2.1-1.fc33.x86_64
> fuse-overlayfs-1.3.0-1.fc33.x86_64

Thanks for the hint  - indeed, installing fuse-overlayfs seems to address the issue. I'll update my installer scripts to put this in place. I apologize if I missed a documentation update that puts this as a requirement...
