### ISSUE TITLE
Upgrade from 2.0.6 to 2.2.1 on Ubuntu Groovy

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/podman#8840]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

On my Ubuntu 20.04 WSL distro I had the working  Podman version 2.2.1
Ubuntu and Microsoft are stopping to support this aging Ubuntu version and moving development to the 20.10 Groovy code baseline.
There is no official Ubuntu 20.10 distro with genie and Podman. Anyway, I succeeded to Upgrade Ubuntu to 20.10, Genie to 1.29, Install Podman. But the Installed Podman version is 2.0.6, ie. much older than those I had ion 20.04. - 2.2.1
How to upgrade my Podman from the 2.0.6 to the recent release or RC version?
**Steps to reproduce the issue:**

1. Install Ubuntu 20.04 WSL distro
Upgrade WSL Kernel
2.
.
.

3. Install Podman 
It installs 2.0.6:

podman info
host:
  arch: amd64
  buildahVersion: 1.15.2
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: unknown'
  cpus: 4
  distribution:
    distribution: ubuntu
    version: "20.10"
  eventLogger: file
  hostname: MSI
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.72-microsoft-standard-WSL2
  linkmode: dynamic
  memFree: 11466813440
  memTotal: 12561657856
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 3221225472
  swapTotal: 3221225472
  uptime: 13h 31m 33.24s (Approximately 0.54 days)
registries:
  search:
  - quay.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Thu Jan  1 02:00:00 1970
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.0.6

**Describe the results you received:**
podman version
Version:      2.0.6
API Version:  1
Go Version:   go1.14.7

**Describe the results you expected:**

podman version
Version:      2.2.1
API Version:  1
Go Version:   go1.14.7

After manual Podman upgrade to 2.2.1

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
apt list podman
Listing... Done
podman/groovy,now 2.0.6+dfsg1-1ubuntu1 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 20.10 Groovy Gorilla on WSL 2

**Comment by PavelSosin-320** [comment]
One step further - cgroup-light is currently installed. But then ... I got the error that I already reported for CentOS8: 
Warning: iptables-legacy tables present, use iptables-legacy to see them\niptables v1.8.5 (nf_tables):  CHAIN_ADD failed (No such file or directory): chain PREROUTING\n" 
I think no contemporary Linux distro uses iptables. It is replaced with nftables with the set of conversion utilities. 
Why CNI plugins still use iptables?

**Comment by rhatdan** [comment]
I believe it supports both.  @mccv1r0 @mheon PTAL

**Comment by mheon** [comment]
CNI on nftables systems uses the iptables front end in Nftables mode.
Unaware of any plans to migrate to calling nftables directly on that side.

**Comment by PavelSosin-320** [comment]
1. iptables in nftables mode returns ret code 4 that is processed incorrectly as an error. This issue exists in CentOS and Ubutu in CNI firewall plugin. greenp has started to develop correction for nftables as I can see in the Github. In the Ubuntu Groovy it will not help because nft is missed.
2. nftables's nft  is already substituted with ufw utility in the Ubuntu Groovy, it has started from 16.04. In 20.10 only iptables-legacy exists and yet works. [Uncomplicated firewall](https://wiki.ubuntu.com/UncomplicatedFirewall)
ufw --version
ufw 0.36 (up to 0.37)
Copyright 2008-2015 Canonical Ltd.

**Comment by PavelSosin-320** [comment]
It is surprize but not everything is lost yet [UFW for RHEL/CentOS 8](https://shouts.dev/install-and-setup-ufw-firewall-on-centos-8-rhel-8)

**Comment by PavelSosin-320** [comment]
@mheon I expect that CNI development team has plans to support UFW s soon as possible . Aother part part of RedHat is already adopting UFW in the OS and infrastructure management tools[Ansimble UFW playbook](https://docs.ansible.com/ansible/latest/collections/community/general/ufw_module.html) and drugs other big companies dependant on these tools.

**Comment by PavelSosin-320** [comment]
Indeed there is no "IPConfig"  problem with rootless containers.
But I can't find the Podman version  above 2.06 already installed on my Ubuntu Groovy

**Comment by PavelSosin-320** [comment]
Not relevant after Podman 3.0 rc release.
