### ISSUE TITLE
Feature: --replace or else for "podman network create" and "podman volume create"

### ISSUE THREAD

**Issue by daniel-wtd** [containers/podman#8842]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Creating new volumes or networks can be done via `podman volume create <name>` or `podman network create <name>`. This will fail, if `<name>` already exists. For volumes, one can workaround this issue, since `podman volume run -v <name>:/foo` will only create the volume, if it is not existing. For networks, this does not work.

It would be awesome to see some cli additions, so `podman network create --replace <name>` or `podman network create --if-not.-exists <name>` can be used.

**Output of `podman version`:**

```
podman version 2.2.1
```

**Comment by rhatdan** [comment]
Not sure what your goal here is?  Are you looking to have a script that runs multiple times but does not know if the network was already created?

Would `podman network create foobar` failing with an already EEXIST (17) satisfy your needs?

$ errno  -l | grep -i exis
EEXIST 17 File exists

**Comment by daniel-wtd** [comment]
The goal is quite easy. podman containers will be started with systemd. For me it is only natural to do the network and volume creation the same way, alongside the containers. This is currently not achievable, since `ExecStart=` will fail, if the network is already existing.

**Comment by rhatdan** [comment]
Couldn't you do something like 

ExecStartPre=podman network inspect FOOBAR > /dev/null || podman network create FOOBAR

**Comment by daniel-wtd** [comment]
Sure, I can do this or provide a script or else.

It just feels like a missing feature/a workaround, since:

```
# This works and replaces existing pods with the same name
podman pod create --replace web

# This works and replaces existing containers with the same name
podman container run --name web01 --replace httpd:2

# This will fail, if net01 already exists
podman network create net01

# This will fail, if vol01 already exists
podman volume create vol01

# This will fail, if net01 does not exist
podman container run --name web01 --replace --network net01 httpd:2

# This works and creates vol01 on demand/if not existing
podman container create --volume vol01:/var/www/html httpd:2
```

**Comment by Luap99** [comment]
Note that `replace` is not the same as `if not exists`. Replace will always remove before creating the container/pod. If not exists will do nothing if it already exists. Deleting a network is not safe if other containers are using it so I think you want the if not exists behaviour.

**Comment by daniel-wtd** [comment]
@Luap99 completely correct. This is how `--volume` currently works and I would appreciate to see the same for `--network`.

Having a proper switch for `podman volume create` or `podman network create` just seemed reasonable.

**Comment by Luap99** [comment]
I opened #8987 to add `--if-not-exists` to podman network create.

**Comment by Luap99** [comment]
We now support `podman network exists` and `podman volume exists` commands. This allows for more flexible use cases.
