### ISSUE TITLE
setting http_proxy env on [engine] table results in containers always having http_proxy

### ISSUE THREAD

**Issue by ahmadalli** [containers/podman#8843]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
/kind bug

**Description**

**Steps to reproduce the issue:**

1. set `http_proxy` env on `[engine]` table on `/etc/containers/containers.conf
   ```toml
   env = [
        "http_proxy=http://1.2.3.4:5678",
        "https_proxy=http://1.2.3.4:5678",
        "no_proxy=localhost,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16",
      ]
   ```
1. set `http_proxy` to false on `[containers]` table
   ```toml
   http_proxy = false
   ```
1. check the results
   ```bash
   podman run --rm docker.io/library/alpine printenv http_proxy
   ```

**Describe the results you received:**

the output of the last step would be `http://1.2.3.4:5678`

but if we add `--http-proxy=false` to the command, it works fine

```bash
podman run --rm --http-proxy=false docker.io/library/alpine printenv http_proxy
```

**Describe the results you expected:**

the last step shouldn't have any output

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.2
Built:        Thu Jan  1 03:30:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.22, commit: '
  cpus: 24
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: nebula6
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.0-58-generic
  linkmode: dynamic
  memFree: 29907927040
  memTotal: 67501182976
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.16.3-fd58-dirty
      commit: fd582c529489c0738e7039cbc036781d1d039014
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 335h 14m 34.85s (Approximately 13.96 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 0
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 3
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 0
  BuiltTime: Thu Jan  1 03:30:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 2.2.1~4 amd64 [installed]
podman/unknown 2.2.1~4 arm64
podman/unknown 2.2.1~4 armhf
podman/unknown 2.2.1~4 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):** baremetal

**Comment by rhatdan** [comment]
This is simple to fix on the podman local side, but difficult to fix on the remote side.

**Comment by ahmadalli** [comment]
Shouldn't remote obey it's own containser.json configuration? since what are we considering `engine` when we use remote mode? the client or the podman socket running in the target host?

**Comment by rhatdan** [comment]
No the goal is to be able to set server side defaults, and then allow users to override them.  This works fine for everything except booleans, Since the default unset state of a boolean is false, there is no way to know if a user set it to false versus just sending the default.

**Comment by ahmadalli** [comment]
why `http_proxy` should be enabled by default?

**Comment by rhatdan** [comment]
Let's ignore podman-remote and just look at the APIV2.  If I am sing podman-py and create a container and the user does not specify http_proxy, then the server should default to true, based on containers.conf.  If the user specifies http_proxy=false, then we should fall back to not doing http_proxy.  The issue is the server currently can not tell the difference between the user specifying nothing and the user specying false.  So if server default is true, what should server do?

The better solution is to use an optionalbool in the parameter rather then a regular bool.  That allows the user to know if the user specified true/false or did not specify.
