### ISSUE TITLE
Cannt publish container port with literal IPv6 address

### ISSUE THREAD

**Issue by grigorig** [containers/podman#8855]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Cannot expose container ports on literal IPv6 addresses.

**Steps to reproduce the issue:**

Run a container and try to expose on IPv6 locahost address:

    podman run -p '[::1]:1234:1234' hello-world

**Describe the results you received:**

```
Error: rootlessport listen tcp: address ::1:1234: too many colons in address
```

**Describe the results you expected:**

Port is published, or at least the publish request is parsed correctly.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.5
Built:        Tue Dec  8 15:37:50 2020
OS/Arch:      linux/amd64

```

**Comment by mheon** [comment]
Can you verify if this works as root? If so, I believe this is probably a slirp4netns bug.

**Comment by umohnani8** [comment]
No response from the reporter, closing.
