### ISSUE TITLE
unable to pass options to slirp4netns

### ISSUE THREAD

**Issue by zem** [containers/podman#8857]
```
podman pod create --network slirp4netns:enable_ipv6=true ...
```

results in the following error: 

```
error configuring network namespace for container 8141426fb804b275465f49cb30009790ee07febb65336ce9c5ea4bf4006608e4: CNI network "slirp4netns:enable_ipv6=true" not found
```

The Manpage says: `slirp4netns[:OPTIONS,...]: use slirp4netns to create a user network stack.` so it should be a valid option. 

podman version 2.1.1

**Comment by Luap99** [comment]
This is only supported since v2.2

**Comment by zem** [comment]
Ah thats interesting, I now have to understand why Coreos fc33 and Fedora fc33 are shipping different Versions. Thanks ;-)
