### ISSUE TITLE
Errors are not reported when starting a pod from the REST API

### ISSUE THREAD

**Issue by fstephany** [containers/podman#8865]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Errors are not reported when starting a pod from the REST API. 

**Steps to reproduce the issue:**

1. Start a Pod using a port mapping (e.g., 8080:80).
2. Start another pod using the same port mapping as the previous one with the CLI. This result in an expected bind error:

```
$ podman pod start second-pod 
error starting container 47ab04855d52b81fc4245e4abb8a6f04933518e865d0aca695b65effc3193aee: rootlessport listen tcp 0.0.0.0:8080: bind: address already in use
Error: error starting container d6efdf7a7d2366e8af67deea417a98c3235fdcccbb8ecf99ca4babb23782e91c: a dependency of container d6efdf7a7d2366e8af67deea417a98c3235fdcccbb8ecf99ca4babb23782e91c failed to start: container state improper
```

3. Start a podman daemon:  ` $ podman system service -t 0 tcp:127.0.0.1:1234`
4. Try to start the same pod with the REST API:

```
$ curl -X POST -s 'http://localhost:1234/v2.0.0/libpod/pods/second-pod/start'
{"Errs":[{},{}],"Id":"3568556cd9b293a53f2ce3ff98d9bea58929a7f2ac41cebf575f958079dcf061"}
```

**Describe the results you received:**

The `Errs` property contains empty objects instead of the expected string (as described in [the reference](https://docs.podman.io/en/latest/_static/api.html#operation/startPod)).

**Output of `podman version`:**

Podman running on Fedora 33. 

```
$ podman version
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.5
Built:        Tue Dec  8 15:37:50 2020
OS/Arch:      linux/amd64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Comment by rhatdan** [comment]
@jwhonce PTAL

**Comment by baude** [comment]
we are getting a partial fail error back in this case.  but then we still return an OK.  That is easy to fix, but it also looks like the encoder is eating/throwing away the slice of errs.  i need @jwhonce to advise here and then fix should be easy.
