### ISSUE TITLE
Question: does podman allow socket connection between containers in same pod

### ISSUE THREAD

**Issue by millerthegorilla** [containers/podman#8866]
I want to use podman to create a pod with two containers, one python with django installed, and one postgres for the django database.

I have successfully created this in the past using the localhost address and standard port, and the django running in the python container has been able to connect to the postgres database running in the other container.

I want to ask if it is possible to connect via a socket. Postgres publishes its socket in /var/run/postgresql/.s.PGSQL.5432 inside the postgres container. Is there anyway to expose the postgres socket inside the postgres container to a python container in the same pod that is running django?

I have considered bind mounts, and it may be possible, but this would expose the socket on the host machine.

Does podman provide a facility to connect to sockets internal to containers?

mtia

**Comment by mheon** [comment]
The usual method would be to expose the socket to localhost in the
container, as all containers in a pod share a network stack. Alternatively,
you could use a named volume - a Podman managed mount. This would still
exist on the host, but as it’s managed by Podman it would be in our
internal data folders, and we keep permissions on those tight for security.

**Comment by millerthegorilla** [comment]
thanks.
