### ISSUE TITLE
Firefox doesn't load any URL with --cap-drop all

### ISSUE THREAD

**Issue by kruppemage** [containers/podman#8867]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Custom Firefox container fails to load any URL when started with **--cap-drop all**. I've had this working previously, but I'm not sure if it's Podman related at all, since it's been a while I have last tried this. IIRC I had this working before the capabilities issues that 2.2.0 solved. Probably with 1.9.2.

The below were the commands I used in order to create a firefox-test container which exhibits this behaviour:

$ buildah from --name tmp docker.io/library/debian:latest
$ buildah run tmp sh -c "apt update && apt install --no-install-recommends -y firefox-esr ttf-dejavu && rm -fr /var/lib/apt/lists/*"
$ buildah run tmp useradd -m -s /bin/bash firefox-esr
$ buildah config -u firefox-esr tmp
$ buildah config --entrypoint firefox-esr tmp
$ buildah commit tmp firefox-test
$ buildah rm tmp

**Steps to reproduce the issue:**

1. sudo podman run --cap-drop all --rm -v /tmp:/tmp -e DISPLAY=:0 firefox-test

**Describe the results you received:**

Firefox fails to render the typed URL. As soon as enter is pressed, the window looks like it enters a loop and nothing is displayed. The main Firefox windows is still responsive, though.

**Describe the results you expected:**

Successful render of the typed URL.

**Output of `podman version`:**

Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.6
Git Commit:   a0d478edea7f775b7ce32f8eb1a01e75374486cb
Built:        Tue Dec  8 21:48:23 2020
OS/Arch:      linux/amd64

**Output of `podman info --debug`:**

host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.22, commit: 9c34a8663b85e479e0c083801e89a2b2835228ed'
  cpus: 4
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: archpc
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.3-arch1-1
  linkmode: dynamic
  memFree: 12831252480
  memTotal: 16495616000
  ociRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc92
      commit: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
      spec: 1.0.2-dev
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 16922988544
  swapTotal: 16922988544
  uptime: 8h 34m 12.82s (Approximately 0.33 days)
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 3
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 11
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1607464103
  BuiltTime: Tue Dec  8 21:48:23 2020
  GitCommit: a0d478edea7f775b7ce32f8eb1a01e75374486cb
  GoVersion: go1.15.6
  OsArch: linux/amd64
  Version: 2.2.1

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

$ pacman -Qs|grep podman
local/podman 2.2.1-1

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Regular laptop.

**Comment by rhatdan** [comment]
Looks like some other security mechanism is causing the issue.  If you don't drop all calls, does it work?

**Comment by rhatdan** [comment]
I would also think you need to share the network with the host for this to work.

**Comment by kruppemage** [comment]
@rhatdan, thanks for helping! That is correct, without --cap-drop is works flawlessly. By sharing the network, do you mean --net host? Why would that have any influence over this?

**Comment by kruppemage** [comment]
Just tried with **--cap-drop all** and **--net host** and it has the same effect, sadly.

**Comment by rhatdan** [comment]
I guess the interesting thing, is what cap does it need.  I would figure DAC_OVERRIDE?

--cap-drop=all --cap-add override

And see if this works.

**Comment by kruppemage** [comment]
Same thing, @rhatdan. I'll try to see what capability makes it work.
I'm not seeing anything particularly interesting with dmesg:

[  117.042451] audit: type=1101 audit(1609793093.126:279): pid=2702 uid=1000 auid=1000 ses=1 msg='op=PAM:accounting grantors=pam_unixam_permitam_time acct="test" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/2 res=success'
[  117.042716] audit: type=1110 audit(1609793093.126:280): pid=2702 uid=1000 auid=1000 ses=1 msg='op=PAM:setcred grantors=pam_faillockam_permitam_envam_faillock acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/2 res=success'
[  117.042871] audit: type=1105 audit(1609793093.126:281): pid=2702 uid=1000 auid=1000 ses=1 msg='op=PAM:session_open grantors=pam_limitsam_unixam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=/dev/pts/2 res=success'
[  117.216264] IPv6: ADDRCONF(NETDEV_CHANGE): veth29bcd861: link becomes ready
[  117.216323] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[  117.216632] cni-podman0: port 1(veth29bcd861) entered blocking state
[  117.216644] cni-podman0: port 1(veth29bcd861) entered disabled state
[  117.216820] device veth29bcd861 entered promiscuous mode
[  117.216836] audit: type=1700 audit(1609793093.303:282): dev=veth29bcd861 prom=256 old_prom=0 auid=1000 uid=0 gid=0 ses=1
[  117.217027] cni-podman0: port 1(veth29bcd861) entered blocking state
[  117.217030] cni-podman0: port 1(veth29bcd861) entered forwarding state
[  117.256893] audit: type=1325 audit(1609793093.323:283): table=nat family=2 entries=10 op=xt_replace pid=2806 comm="iptables"
[  117.286888] audit: type=1325 audit(1609793093.343:284): table=nat family=2 entries=12 op=xt_replace pid=2808 comm="iptables"
[  117.340227] audit: type=1325 audit(1609793093.376:285): table=nat family=2 entries=13 op=xt_replace pid=2810 comm="iptables"
[  117.380288] audit: type=1325 audit(1609793093.430:286): table=nat family=2 entries=14 op=xt_replace pid=2812 comm="iptables"
[  117.419946] audit: type=1325 audit(1609793093.486:287): table=filter family=2 entries=24 op=xt_replace pid=2833 comm="iptables"
[  117.446850] audit: type=1325 audit(1609793093.510:288): table=filter family=2 entries=25 op=xt_replace pid=2835 comm="iptables"
[  131.891117] kauditd_printk_skb: 16 callbacks suppressed
[  131.891119] audit: type=1101 audit(1609793107.976:303): pid=3004 uid=1000 auid=1000 ses=1 msg='op=PAM:accounting grantors=pam_unixam_permitam_time acct="test" exe="/usr/bin/sudo" hostname=? addr=? terminal=? res=success'
[  131.891297] audit: type=1110 audit(1609793107.976:304): pid=3004 uid=1000 auid=1000 ses=1 msg='op=PAM:setcred grantors=pam_faillockam_permitam_envam_faillock acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=? res=success'
[  131.891440] audit: type=1105 audit(1609793107.976:305): pid=3004 uid=1000 auid=1000 ses=1 msg='op=PAM:session_open grantors=pam_limitsam_unixam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=? res=success'
[  131.897088] audit: type=1106 audit(1609793107.983:306): pid=3004 uid=1000 auid=1000 ses=1 msg='op=PAM:session_close grantors=pam_limitsam_unixam_permit acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=? res=success'
[  131.897686] audit: type=1104 audit(1609793107.983:307): pid=3004 uid=1000 auid=1000 ses=1 msg='op=PAM:setcred grantors=pam_faillockam_permitam_envam_faillock acct="root" exe="/usr/bin/sudo" hostname=? addr=? terminal=? res=success'

Cheers!

**Comment by rhatdan** [comment]
On Fedora 33, this works fine for me.
$ cat /tmp/Containerfile 
FROM fedora
RUN yum -y install firefox
$ podman build -t firefox /tmp
...
$ podman run -ti --security-opt label=disable --rm -v /tmp:/tmp -e DISPLAY=:0 firefox /usr/bin/firefox

Firefox window shows up.

I had to disable SELinux separation.  But everything else worked. 

I can also drop all caps except DAC_OVERRIDE, and it works.

$ podman run -ti --cap-drop=all --cap-add dac_override --security-opt label=disable --rm -v /tmp:/tmp -e DISPLAY=:0 firefox /usr/bin/firefox 

I have not tried this as root, but I am pretty sure it would work.
