### ISSUE TITLE
Create Documentation for Networking Guide

### ISSUE THREAD

**Issue by fatherlinux** [containers/podman#8874]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Need a set of docs focused on creating and managing networks. Should cover 3-5 most common use cases when coming from Docker.

**Steps to reproduce the issue:**

1. Go to podman.io, click on Documentation, then click on search, and type "network" in the search box. 

**Describe the results you received:**

The only things which come up are  man pages. The man pages don't have all of the extra detail of a tutorial nor good examples. The man pages would augment this proposed documentation.

**Describe the results you expected:**
User should find a nice tutorial which covers common use cases when coming from Docker.

**Additional information you deem important (e.g. issue happens only occasionally):**
Like the manifest documentation RFE, I contemplated making this a RHEL documentation request, but I think it would be better upstream. Upstream first is the right approach for this.

**Comment by baude** [comment]
@fatherlinux it would help us to cover the use cases.  i can only think of two. bridge and macvlan.

**Comment by vrothberg** [comment]
I just saw on Twitter that CNI has fresh documentation which may be helpful: https://www.cni.dev/plugins/main/

**Comment by rhatdan** [comment]
Baude this seems like something in your area.

**Comment by baude** [comment]
that is a scary thought
