### ISSUE TITLE
flake: podman logs: sometimes emits wrong output

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#8879]
`podman logs` is sometimes returning the wrong result. It actually seems to be a problem with the stored output, not `podman logs` itself; i.e. once a container gets in this bad state, all future `podman logs` commands will fail.

Simpleminded overview (not a reproducer):
```console
$ ./bin/podman run -t --name test IMG sh -c 'echo 1;echo 2'
1
2
$ ./bin/podman logs test
<something other than '1 2'>
```
Sample failed results:
* '1', 2nd line is empty
* empty line, '2' on second line
* empty line, '12' on second line

Context: seeing this kind of regularly in integration tests:

Podman logs [It] Make sure logs match expected length
* gce_instance:fedora : int podman fedora-33 root host
  * PR #8487
    * [11-25 15:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6248697619021824/html/int-podman-fedora-33-root-host.log.html#t--Make-sure-logs-match-expected-length--1)
* gce_instance:prior-fedora : int podman fedora-32 root container
  * PR #8852
    * [12-29 12:50](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5095812399104000/html/int-podman-fedora-32-root-container.log.html#t--Make-sure-logs-match-expected-length--1)
  * PR #8747
    * [12-18 09:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5056399564603392/html/int-podman-fedora-32-root-container.log.html#t--Make-sure-logs-match-expected-length--1)
    * [12-18 09:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5056399564603392/html/int-podman-fedora-32-root-container.log.html#t--Make-sure-logs-match-expected-length--2)
    * [12-18 09:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5056399564603392/html/int-podman-fedora-32-root-container.log.html#t--Make-sure-logs-match-expected-length--3)
* gce_instance:prior-fedora : int podman fedora-32 root host
  * PR #8871
    * [01-04 09:59](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5269387563237376/html/int-podman-fedora-32-root-host.log.html#t--Make-sure-logs-match-expected-length--1)
    * [01-04 09:59](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5269387563237376/html/int-podman-fedora-32-root-host.log.html#t--Make-sure-logs-match-expected-length--2)
    * [01-04 09:59](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5269387563237376/html/int-podman-fedora-32-root-host.log.html#t--Make-sure-logs-match-expected-length--3)
* gce_instance:prior-fedora : int podman fedora-32 rootless host
  * PR #8793
    * [12-22 20:58](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5864957893935104/html/int-podman-fedora-32-rootless-host.log.html#t--Make-sure-logs-match-expected-length--1)
    * [12-22 20:58](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5864957893935104/html/int-podman-fedora-32-rootless-host.log.html#t--Make-sure-logs-match-expected-length--2)
    * [12-22 20:58](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5864957893935104/html/int-podman-fedora-32-rootless-host.log.html#t--Make-sure-logs-match-expected-length--3)
  * PR #8792
    * [12-23 14:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6063085943259136/html/int-podman-fedora-32-rootless-host.log.html#t--Make-sure-logs-match-expected-length--1)
    * [12-23 14:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6063085943259136/html/int-podman-fedora-32-rootless-host.log.html#t--Make-sure-logs-match-expected-length--2)
    * [12-23 14:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6063085943259136/html/int-podman-fedora-32-rootless-host.log.html#t--Make-sure-logs-match-expected-length--3)
* gce_instance:prior-ubuntu : int podman ubuntu-19 root host
  * PR #8410
    * [11-20 11:53](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4568878044938240/html/int-podman-ubuntu-19-root-host.log.html#t--Make-sure-logs-match-expected-length--1)

Reproducer [[podman-logs-flake.sh.txt](https://github.com/containers/podman/files/5766804/podman-logs-flake.sh.txt)]:
```bash
#!/bin/sh

img=quay.io/libpod/testimage:20200929
expect=

while :;do
    ./bin/podman run -t --name test $img sh -c 'echo 1;echo 2'
# The integration test has a 'wait'; this is not actually necessary, test will fail even without it
#    ./bin/podman wait test
    x=$(./bin/podman logs test)
    printf "%q\n" $x

    # First time through
    if [[ -z "$expect" ]]; then
        expect=$x
    fi

    if [[ "$x" != "$expect" ]]; then
        echo -ne '\a'
        echo "*********************"
        echo
        exit
    fi
    ./bin/podman rm test
done
```
It takes several hours to fail on my laptop. Once it fails, the container is left in place, and all subsequent `podman log test` commands will remain consistent with the first failure.

master @ 23f25b8261cf2c0d83f8ce5b8251951a11a7e2c4. Seems to happen both root and rootless, f32 and f33; even once on ubuntu 19.

**Comment by edsantiago** [comment]
Update: it's looking likely that the `-t` is the culprit. I've had the reproducer running for the last 3+ hours, without `-t`, and no failure yet. I'll let it run overnight.

**Comment by edsantiago** [comment]
Forgot to update here: the job without `-t` ran all night, over twelve hours. I stopped it, added back `-t`, job failed within two hours.

**Comment by Luap99** [comment]
Can you paste the content of the log file please? It could be that podman logs works correct and the file is wrong.

**Comment by edsantiago** [comment]
Good idea.
```console
$ ./bin/podman logs test | cat -vET
1^M$
^M$
$ cat -vET ~/.local/share/containers/storage/overlay-containers/<sha>/userdata/ctr.log
2021-01-05T09:30:48.745347870-07:00 stdout F 1^M$
2021-01-05T09:30:48.745347870-07:00 stdout P 2$
2021-01-05T09:30:48.745582542-07:00 stdout F ^M$
```
On a good container:
```console
$ cat -vET ~/.local/share/containers/storage/overlay-containers/<sha>/userdata/ctr.log
2021-01-06T13:53:05.349022525-07:00 stdout F 1^M$
2021-01-06T13:53:05.349022525-07:00 stdout F 2^M$
```

**Comment by Luap99** [comment]
OK `podman logs` is wrong. I will open a PR.

**Comment by Luap99** [comment]
#8904
