### ISSUE TITLE
Cannot install podman on Amazon Linux 2

### ISSUE THREAD

**Issue by thomashoefkens-vw** [containers/podman#8888]
/kind bug

**Description**
Whilst following the podman documentation on installing podman on Amazon Linux 2, I cannot get the installation to work. The yum install podman command always results in "package podman not avaible".

**Steps to reproduce the issue:**

On a blank A1 EC2 instance, run the commands as specified here for Amazon Linux 2:
https://podman.io/getting-started/installation

```
sudo curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/devel:kubic:libcontainers:stable.repo
sudo yum -y install yum-plugin-copr
sudo yum -y copr enable lsm5/container-selinux
sudo yum -y install podman
```

**Describe the results you received:**
The final command fails with the message "package podman not available".

**Describe the results you expected:**
A successful podman installation.

**Additional information you deem important (e.g. issue happens only occasionally):**
![image](https://user-images.githubusercontent.com/71012278/103660628-1ad38a00-4f6e-11eb-9c6a-f7fc7511d1e7.png)

**Comment by rhatdan** [comment]
@thomashoefkens-vw Have you reached out to Amazon Linux people asking why Podman is not available natively?  If they don't have it I would recommend using a different OS Say RHEL8.   :^)

**Comment by thomashoefkens-vw** [comment]
> @thomashoefkens-vw Have you reached out to Amazon Linux people asking why Podman is not available natively? If they don't have it I would recommend using a different OS Say RHEL8. :^)

I did not as the documentation of podman clearly states how to install it on Amazon Linux. If the documentation is wrong and it should be available natively, then the documentation should be updated to reflect this, right?

**Comment by rhatdan** [comment]
Yes, if the documentation is wrong, but the goal of the documentation is really to allow users to build and install packages that are not available from a distribution.  What I am really interested in is, whether Amazon Linux has a version of Podman available.

These instructions are contributed from community, since the coreteam only works on a subset of the distributions that Podman is being used on.  If people find issues with the documentation, we usually ask them to update the docs, and make sure it works for them.

**Comment by thomashoefkens-vw** [comment]
@rhatdan No, Amazon Linux does not have a versio of podman available. That is why I wanted to find out whether I could still get the installation running by putting up the question here - perhaps someone knows what broke the installation by following the docs...

**Comment by rhatdan** [comment]
Ok hopefully @lsm5 can look at the docs, or figure out why the Amazon package is not available.  But if you could open an issue with Amazon to ship Podman, that would be useful to us.

**Comment by lsm5** [comment]
@rhatdan amazon linux is a recompile of rhel7 so the centos7 steps work as-is for amazon linux. I don't think amazon will entertain requests for their own build of podman.

@thomashoefkens-vw I tried the steps on a `docker.io/library/amazonlinux` container just now and it worked fine. Could you please give it another try?

**Comment by rhatdan** [comment]
There should be a podman 1.6.6 version of podman on RHEL7, Centos7 and Amazone Linux 7 then correct?

**Comment by thimslugga** [comment]
For rootless podman these steps should work. let me know if you run into any issues.

```
sudo amazon-linux-extras disable docker
sudo amazon-linux-extras install -y kernel-ng

sudo yum check-update
sudo yum install -y yum-utils yum-plugin-copr

sudo cat <<EOF > /etc/yum.repos.d/devel\:kubic\:libcontainers\:stable.repo
[devel_kubic_libcontainers_stable]
name=Stable Releases of Upstream github.com/containers packages (CentOS_7)
type=rpm-md
baseurl=https://provo-mirror.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/
gpgcheck=0
gpgkey=https://provo-mirror.opensuse.org/devel:/kubic:/libcontainers:/stable/CentOS_7/repodata/repomd.xml.key
enabled=1
EOF

sudo yum copr enable -y lsm5/container-selinux

sudo yum check-update
sudo yum install -y podman slirp4netns

test ! -f /etc/containers/seccomp.json && \
  sudo wget https://raw.githubusercontent.com/docker/labs/master/security/seccomp/seccomp-profiles/default.json -O /etc/containers/seccomp.json

sudo grubby --update-kernel=ALL \
   --args="systemd.unified_cgroup_hierarchy=1 namespace.unpriv_enable=1 user_namespace.enable=1"

echo "user.max_user_namespaces=10000" | sudo tee /etc/sysctl.d/98-userns.conf

echo "$(id -un):100000:65536" | sudo tee -a /etc/subuid
echo "$(id -un):100000:65536" | sudo tee -a /etc/subgid

sudo yum install -y git-core autoconf gettext-devel automake libtool libxslt byacc libsemanage-devel

mkdir -pv ~/src && cd ~/src
git clone https://github.com/shadow-maint/shadow shadow-utils
cd shadow-utils
./autogen.sh --prefix=/usr/local
make -j $(nproc)

sudo cp src/newgidmap src/newuidmap /usr/local/bin/

sudo setcap cap_setuid+ep /usr/local/bin/newuidmap
sudo setcap cap_setgid+ep /usr/local/bin/newgidmap

sudo systemctl reboot
podman system migrate
podman version
podman run --rm -it hello-world:latest
```

**Comment by lsm5** [comment]
> There should be a podman 1.6.6 version of podman on RHEL7, Centos7 and Amazone Linux 7 then correct?

Default CentOS 7 Extras will have everything from RHEL 7 Extras. But Amazon Linux Extras is not the same. AFAIK, there's no default podman build available on Amazon Linux. So, you either gotta build your own or use the one from the Kubic repos (Known to work) or CentOS Extras repo (not sure if this one works).

Amazon Extras: https://aws.amazon.com/premiumsupport/knowledge-center/ec2-install-extras-library-software/

**Comment by lsm5** [comment]
I'll close this. Please reopen if it still occurs.

**Comment by koalawangyang** [comment]
I still have this issue, can not install podman in Amazon Linux 2. 

"no podman package found" when enabled epel source. Already followed above solutions, no one works for me.

**Comment by rhatdan** [comment]
Have you contacted Amazon and asked them to package it up.

**Comment by koalawangyang** [comment]
> Have you contacted Amazon and asked them to package it up.

not yet, I will contact Amazon's support today.

**Comment by mihaigalos** [comment]
> not yet, I will contact Amazon's support today.

@koalawangyang, any news?

**Comment by koalawangyang** [comment]
> > not yet, I will contact Amazon's support today.
> 
> @koalawangyang, any news?

I have sent feedback to Amazon, but they haven't replied yet.

**Comment by mihaigalos** [comment]
In the meantime, I've simplified the process of developing an install script for the installer by directly using a docker image. The environment is not a VM but is the same you would get in an EC2 instance:

```bash
$ docker run --rm -it amazonlinux
```

This produced the following install script which installs podman in the `amazonlinux` docker. 

The next step will be to try it out on an EC2.

```bash
#!/bin/bash

cat <<EOF >/tmp/base
[base]
name=CentOS 7 Base Packages
baseurl=http://mirror.centos.org/centos/7/os/x86_64/
enabled=1
gpgcheck=0
EOF

sudo mv /tmp/base /etc/yum.repos.d/centos-base.repo

cat <<EOF >/tmp/extras
[extras]
name=CentOS 7 Extras Packages
baseurl=http://mirror.centos.org/centos/7/extras/x86_64/
mirrorlist=http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=extras
enabled=1
gpgcheck=0
EOF

sudo mv /tmp/extras /etc/yum.repos.d/centos-extras.repo

sudo mv /etc/yum.repos.d/amzn2-core.repo  /tmp
sudo yum update
sudo yum install \
        buildah \
        podman

sudo mv /tmp/amzn2-core.repo /etc/yum.repos.d/amzn2-core.repo
```

**Comment by rhatdan** [comment]
Why wouldn't you use a more recent version of centos?  Podman on Centos 7 is ancient.

**Comment by lsm5** [comment]
> Why wouldn't you use a more recent version of centos? Podman on Centos 7 is ancient.

amazon linux 2 is a recompile of rhel 7 AFAIK. Unlikely they'll be able to use from a newer centos.

**Comment by mihaigalos** [comment]
We're open to a better mechanism than manually setting the mirrors, including a vanilla AMI/docker which has them in by default. Or alternatively, have `podman` installed by default.

**Comment by lsm5** [comment]
> We're open to a better mechanism than manually setting the mirrors, including a vanilla AMI/docker which has them in by default. Or alternatively, have `podman` installed by default.

Don't want this turning into another distro war, but just wondering why not switch entirely to RHEL / CentOS Stream 8/9 if you need a rhel-based environment? You get the latest podman there by default.

If you need a custom amazon linux AMI with the latest podman, I'm afraid that's gonna have to be a volunteer effort. Upstream does not have the bandwidth to provide/support that.

**Comment by mihaigalos** [comment]
We use hardened AMIs which have the upstream as base. 

We can't change that since they're coming from a different part of our organisation.

**Comment by koalawangyang** [comment]
We use Amazon EKS as our K8s platform and the nodePool is selfManaged with Amazon Linux 2 AMIs. Other AMIs couldn't be used in this selfManaged nodePool.

So we have to use Amazon Linux 2 image.

**Comment by Nwexpert** [comment]
@koalawangyang use the EKS supported ubuntu 
https://cloud-images.ubuntu.com/aws-eks/
