### ISSUE TITLE
REST API pull does not work behind a corporate proxy

### ISSUE THREAD

**Issue by karljaxon** [containers/podman#8908]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

When trying to use the REST API to pull an image behind a corporate proxy, the pull will fail. Note that the command works fine if run without a proxy in the way (curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v1.0.0/images/create?fromImage=alpine').

The podman command line works fine both with and without the proxy, and respects the https_proxy environment variable. It was clear how to configure this for docker, as this was running as a service and could be configured with a service file (see https://docs.docker.com/config/daemon/systemd/#httphttps-proxy). I tried making a similar systemd drop-in file for the socket but that doesn't work... I don't see any obvious way I can make the socket aware of the proxy location.

**Steps to reproduce the issue:**

1. Activate the podman socket

2. curl -XPOST --unix-socket /run/podman/podman.sock -v 'http://d/v1.0.0/images/create?fromImage=alpine'

**Describe the results you received:**
Fails to pull with:

* Uses proxy env variable http_proxy == 'http://iss-emea-pitc-londonz.proxy.corporate.ge.com:80'
*   Trying /run/podman/podman.sock:0...
* Connected to d (/run/podman/podman.sock) port 80 (#0)
> POST /v1.0.0/images/create?fromImage=alpine HTTP/1.1
> Host: d
> User-Agent: curl/7.71.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Api-Version: 1.40
< Content-Type: application/json
< Libpod-Api-Version: 2.0.0
< Server: Libpod/2.0.0 (linux)
< Date: Thu, 07 Jan 2021 15:39:58 GMT
< Content-Length: 329
< 
{"cause":"Get \"https://registry-1.docker.io/v2/\": dial tcp: lookup registry-1.docker.io: no such host","message":"Error initializing source docker://alpine:latest: error pinging docker registry registry-1.docker.io: Get \"https://registry-1.docker.io/v2/\": dial tcp: lookup registry-1.docker.io: no such host","response":500}
* Connection #0 to host d left intact

**Describe the results you expected:**
Should pull the image 'alpine'

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.5
Built:        Tue Dec  8 14:37:50 2020
OS/Arch:      linux/amd64

**Output of `podman info --debug`:**

host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.21-3.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 0f53fb68333bdead5fe4dc5175703e22cf9882ab'
  cpus: 6
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: file
  hostname: e5b4e295c3dd
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.19.121-linuxkit
  linkmode: dynamic
  memFree: 114343936
  memTotal: 2084966400
  ociRuntime:
    name: crun
    package: crun-0.16-1.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.16
      commit: eb0145e5ad4d8207e84a327248af76663d4e50dd
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 870313984
  swapTotal: 1073737728
  uptime: 5h 54m 49.09s (Approximately 0.21 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions:
    vfs.imagestore: /var/lib/shared
  graphRoot: /var/lib/containers/storage
  graphStatus: {}
  imageStore:
    number: 0
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1607438270
  BuiltTime: Tue Dec  8 14:37:50 2020
  GitCommit: ""
  GoVersion: go1.15.5
  OsArch: linux/amd64
  Version: 2.2.1

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

podman-2.2.1-1.fc33.x86_64

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running in container on MacOS (systemd-initialised docker container)

**Comment by mheon** [comment]
My first thought would be that the server does not have the environment variable set. Can you try running the service manually (`podman system service --timeout 0` will start the service with the socket at the default location) on a shell where you are sure the environment variable is exported?

**Comment by karljaxon** [comment]
@mheon - thanks for looking at this. This works - the proxy settings are respected.
The issue here is with how I activated the socket. If you search for 'podman socket' the first hit is:
http://crunchtools.com/a-first-look-at-the-podman-2-0-api/

It activates the socket with a straight call to:
systemctl enable --now podman.socket

The same method is used in a few redhat docs and issues here (eg. https://github.com/containers/podman/issues/7632). Anyway, a direct call to systemd does not respect proxies, but 'podman system service' does.

**Comment by rhatdan** [comment]
Should we document this better?  Should we put something in the systemd unit file about setting up proxies?

**Comment by karljaxon** [comment]
> Should we document this better? Should we put something in the systemd unit file about setting up proxies?

Hi @rhatdan - more documentation would be useful, particularly around how we should treat the socket in real-world situations. The use case I have is a commandline app (written in Python) that controls deployments. It can drive either docker or podman, and users would interact with it a lot. The available python libraries control podman through the API.

I'd initially thought this should be used with the podman socket running as a service, that would survive reboots and always be there. I'm getting the impression now that it would be better to actually activate the socket from within the commandline utility and close it at the end of execution... But I'm not sure what would be 'best practice'. I'm assuming that using the 'podman system service' ensures we have rootless containers whereas my direct call to systemd would not, but again I'm not finding it clear
