### ISSUE TITLE
Error running hook on CentOS 8

### ISSUE THREAD

**Issue by rbqbjyur** [containers/podman#8909]
**This a BUG REPORT**

/kind bug

**Description**

When trying to run a new container, I am getting the below error:
```
Error: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: : OCI runtime error
```

Have searched around the internet, checked the [Podman Troubleshooting Guide](https://github.com/containers/podman/blob/master/troubleshooting.md), tried removing all optional run flags, added --privileged, etc. Haven't been able to get any further.

The only situation it seems to work is if I run with sudo, which I'd like to avoid.

I don't want to waste anyone's time, so I do just want to call out initially. This is on podman 2.0.5, and not 2.2.1
I did look through the changelogs between and didn't specifically notice anything, that might address it.
I am running on CentOS 8, and using package from the AppStream repo. Generally I'd prefer not to start grabbing releases from GitHub etc.
So if this is outside the intended scope for issues on GitHub, my apologies, feel free to close the issue.

I'll also note that before everything was working on podman 1.6.4, the system was then upgraded (podman went to 2.0.5)
Most other related packages where minor updates.
And now this has started occurring.

podman 2 was obviously a major version change, but I can't seem to see or find anything that would cause this.

**Steps to reproduce the issue:**
I am just running an image with the below settings (image as example, not limited to bazarr);
```
podman run --name bazarr -d -v /mnt/DriveC1/usenet/config/bazarr:/config -v /mnt/DriveC1/usenet/data:/data:z -p 6767:6767 docker.io/hotio/bazarr
```
also occurs when limited to below;
```
podman run -d docker.io/hotio/bazarr
```

**Describe the results you received:**
Container is created, but doesn't start. Provides below error;
```
Error: container_linux.go:370: starting container process caused: process_linux.go:459: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: : OCI runtime error
```
Trying to start existing container, results in same error.

**Describe the results you expected:**
The container should start. 

**Additional information you deem important (e.g. issue happens only occasionally):**
Seems to only happen with some images, doesn't occur when running with sudo.
Podman was recently updated from 1.6.4 -> 2.0.5

**Output of `podman version`:**

```
Version:      2.0.5
API Version:  1
Go Version:   go1.14.7
Built:        Thu Sep 24 18:58:13 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
arch: amd64
  buildahVersion: 1.15.1
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.20-2.module_el8.3.0+475+c50ce30b.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.20, commit: 1019ecdeda3936be22162bb1cca308192145de53'
  cpus: 8
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: colossus
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-240.1.1.el8_3.x86_64
  linkmode: dynamic
  memFree: 169172992
  memTotal: 8007094272
  ociRuntime:
    name: runc
    package: runc-1.0.0-68.rc92.module_el8.3.0+475+c50ce30b.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-2.module_el8.3.0+475+c50ce30b.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 8041263104
  swapTotal: 8359243776
  uptime: 111h 43m 49.96s (Approximately 4.62 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/outis/.config/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 6
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-3.module_el8.3.0+507+aa0970ae.x86_64
      Version: |-
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/outis/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 10
  runRoot: /run/user/1000
  volumePath: /home/outis/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1600970293
  BuiltTime: Thu Sep 24 18:58:13 2020
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.0.5
```

**Package info (e.g. output of `rpm -q podman`):**

```
podman-2.0.5-5.module_el8.3.0+512+b3b58dca.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

It's the latest from the CentOS 8 Repo (2.0.5), but not latest (2.2.1 as of writing).
If possible, would like to refrain from using out of repo builds in this situation.
Willing to try if necessary, but wanted to see if there was an alternative, or config issue first.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical server, have direct access to.

**Comment by mheon** [comment]
Did you install any OCI hooks? It would help to know what the failing hook is.

**Comment by rbqbjyur** [comment]
I hadn't installed any additional packages, there were some additional dependencies brought in from the upgrade e.g. podman-catatonit

I certainly amn't intending or trying to use any OCI hooks, I'm not aware of what they are.

Looking into them now, looks like the directory "/usr/share/containers/oci/hooks.d" has only one file "oci-systemd-hook.json"
Contents are below.
```
{
     "cmd": [".*/init$" , ".*/systemd$" ],
     "hook": "/usr/libexec/oci/hooks.d/oci-systemd-hook",
     "stage": [ "prestart", "poststop" ]
 }
```

I also tried creating new container with --log-level=debug, the below seem like the relevant lines.

```
...
DEBU[0000] reading hooks from /usr/share/containers/oci/hooks.d
DEBU[0000] added hook /usr/share/containers/oci/hooks.d/oci-systemd-hook.json
DEBU[0000] hook oci-systemd-hook.json did not match
DEBU[0000] Created OCI spec for container 965fd0fac4078f8b45a63aec59cb98ac8e20acc09777eff30f5a00e76ed6d830 at /home/outis/.local/share/containers/storage/overlay-containers/965fd0fac4078f8b45a63aec59cb98ac8e20acc09777eff30f5a00e76ed6d830/userdata/config.json
...
DEBU[0001] reading hooks from /usr/share/containers/oci/hooks.d
DEBU[0001] added hook /usr/share/containers/oci/hooks.d/oci-systemd-hook.json
DEBU[0001] hook oci-systemd-hook.json matched; adding to stages [prestart poststop]
/usr/share/containers/oci/hooks.d/oci-systemd-hook.json
DEBU[0001] Created OCI spec for container 210dddeaa9ba2ad79ddb58dedd2e7d97a457eff6f4012185d752415ef4f902ce at /home/outis/.local/share/containers/storage/overlay-containers/210dddeaa9ba2ad79ddb58dedd2e7d97a457eff6f4012185d752415ef4f902ce/userdata/config.json
...
```

Apologies if I missed anything, am not familiar with OCI hooks.

**Comment by vrothberg** [comment]
Could you temporarily move the `oci-systemd-hook.json` out of the directory and try again?

**Comment by rhatdan** [comment]
Podman has no need of this hook, I would just remove it.

**Comment by rbqbjyur** [comment]
Moving `oci-systemd-hook.json` worked, based on that and Podman not needing it, went ahead and removed the `oci-systemd-hook` package.

Everything working perfectly, thank you very much everyone.
