### ISSUE TITLE
RFE: Let `podman volume prune` show the volumes that are going to be removed

### ISSUE THREAD

**Issue by Tronde** [containers/podman#8913]
/kind feature

**Description**

Running `podman volume prune` you have to confirm the operation but you don't see which volumes actually will be removed after you confirm the command:

```
$ podman volume prune
WARNING! This will remove all volumes not used by at least one container.
Are you sure you want to continue? [y/N]
```

I was trapped by the issue #7862. This could have been avoided by showing the volumes that are going to be removed before you confirm the removal. Because the user would have the chance that there is a volume going to be removed that's currently in use by a running container instance. Possible data loss could be prevented this way.

Or at least add an option to the command that will show the volumes that are going to be removed.

**Steps to reproduce the issue:**

1. `podman volume prune`

2. Hit 'y'

3.

**Describe the results you received:**

```
$ podman volume prune
WARNING! This will remove all volumes not used by at least one container.
Are you sure you want to continue? [y/N]
```

**Describe the results you expected:**

```
$ podman volume prune
WARNING! This will remove all volumes not used by at least one container. The following volumes will be removed:
volume1
volume2
...
Are you sure you want to continue? [y/N]
```

**Output of `podman version`:**

```
podman version 3.0.0-dev
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Comment by rhatdan** [comment]
Good idea.  Interested in opening a PR?  I think this would make sense for a few of the tools.  Note that this could be a bit racy.

**Comment by Tronde** [comment]
Thanks. Sad but true I'm not able to open a PR. Because I'm not a developer and most of the source code I don't understand. I don't know go.

So, I hope some Dev who is capable of implementing this would take over to get it done.

I would be able to help testing the implementation, though.

**Comment by rhatdan** [comment]
No problem, I set this as a good first issue, and we shall see if someone grabs it.

Thanks for your suggestion, and any help you give to the project is appreciated.

**Comment by iwita** [comment]
Hello, I am quite a beginner in open-source and completely new to the Podman project. 
Could I get this issue assigned?
I made the needed changes but I am not sure how could I test it.

**Comment by Luap99** [comment]
@iwita I assigned the issue to you. Volume prune tests can be found here https://github.com/containers/podman/blob/master/test/e2e/volume_prune_test.go

**Comment by iwita** [comment]
Hello,
I am having some trouble creating tests for this newly added functionality because of the user interaction (yes/no stdin). 
Any help would be greatly appreciated :)

**Comment by rhatdan** [comment]
How about

podman volume prune <<< n | grep VOLUMES

**Comment by rhatdan** [comment]
You can do that as a system tests.  test/system/*.bats

**Comment by iwita** [comment]
> You can do that as a system tests. test/system/*.bats

@rhatdan Thank you very much for your help!
