### ISSUE TITLE
Filesystem other than VFS when running Podman in a Docker container on Kubernetes

### ISSUE THREAD

**Issue by philnalwalker** [containers/podman#8918]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

We would like to use Podman for builds on our enterprise Jenkins installation which runs on top of Kubernetes v1.16 EKS and uses Docker as the underlying containerization platform. VFS performance however is suboptimal (as expected.)  Is it possible to get overlay working in this scenario? When we try to use overlay we encounter the following error:

```
Error: error mounting new container: error mounting build container "7c8ab2bfab6bd5b9670c7b6b2cb7c954b454ddb6490774bd9628d457a7fd5faa": error creating overlay mount to /var/lib/containers/storage/overlay/fe81a50663cd85853c9974e5a58fd537c198ff081779332548807bd70217e301/merged: using mount program /usr/local/bin/fuse-overlayfs: fuse: device not found, try 'modprobe fuse' first
fuse-overlayfs: cannot mount: No such file or directory
: exit status 1
```

We are running in an unprivileged container, but do give SYS_ADMIN and SYS_RESOURCE.

```
apiVersion: v1
kind: Pod
metadata:
  name: ***
spec:
  containers:
  - name: podman
    image: ***
    tty: true
    command: [ "cat" ]
    imagePullPolicy: Always
    volumeMounts:
      - name: shared-build-output
        mountPath: /var/run/outputs
    securityContext:
      capabilities:
        add: [ "SYS_ADMIN", "SYS_RESOURCE" ]
```  

```
+ podman info
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.22, commit: 9c34a8663b85e479e0c083801e89a2b2835228ed'
  cpus: 32
  distribution:
    distribution: alpine
    version: 3.12.3
  eventLogger: file
  hostname: ***
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.14.203-156.332.amzn2.x86_64
  linkmode: dynamic
  memFree: 89872969728
  memTotal: 267533062144
  ociRuntime:
    name: runc
    package: Unknown
    path: /usr/local/bin/runc
    version: |-
      runc version 1.0.0-rc92
      commit: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
      spec: 1.0.2-dev
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 487h 55m 41.45s (Approximately 20.29 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.ignore_chown_errors: "true"
    overlay.mount_program:
      Executable: /usr/local/bin/fuse-overlayfs
      Package: Unknown
      Version: |-
        fuse-overlayfs: version 1.3
        fusermount3 version: 3.10.1
        FUSE library version 3.10.1
        using FUSE kernel interface version 7.31
    overlay.mountopt: nodev,fsync=0
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: overlayfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.14.13
  OsArch: linux/amd64
  Version: 2.2.1
```

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
I believe this should be possible, but you'll need to pass `/dev/fuse` from the host into the container. @rhatdan would know more, though.

**Comment by rhatdan** [comment]
Yes you need /dev/fuse mounted into the container. If you are using cri-o you can just setup cri-o to always mount /dev/fuse into containers, and problem is solved.  In k8s you can volume mount them in.  Sadly currently there is no equivalent to podman --device /dev/fuse in k8s.

@giuseppe @mrunalp Thoughts.

**Comment by philnalwalker** [comment]
For those not on CRI-O i.e., EKS and trying to use Podman with overlay the fuse-device-plugin seems to be working well over here. Like CRI-O you can automount /dev/fuse by adding the appropriate configuration in your pod YAML.

Steps required follow:

1. EKS Kernel upgrade (required for fuse-overlay to work)
 
sudo amazon-linux-extras install kernel-ng
 
2. Load fuse device driver (should set this to load on boot)
 
modprobe fuse
 
3. Enable kubelet feature gate by modifying the DAEMON_ARGS in the environment file used /usr/lib/systemd/system/kubelet.service
 
--feature-gates=DevicePlugins=true
 
4. Deploy daemonset using kubectl
 
Daemonset: https://github.com/kuberenetes-learning-group/fuse-device-plugin/blob/master/fuse-device-plugin-k8s-1.16.yml
 
5. Modify your pod YAML to specify fuse device resource:
 
  containers:
    - name: podman
      image:  docker.mycompany.com/podman:latest
      tty: true
      command: [ "cat" ]
      imagePullPolicy: Always
      securityContext:
        capabilities:
          add: [ "SYS_ADMIN", "SYS_RESOURCE" ]
resources:
        limits:
          github.com/fuse: 1

**Comment by rhatdan** [comment]
We have just published

https://www.redhat.com/sysadmin/podman-inside-container
And
https://www.redhat.com/sysadmin/podman-inside-kubernetes

Please read these and see if they help solve your problem.  Reopen if you need more information.
