### ISSUE TITLE
Can podman pass the physical NIC to the container?

### ISSUE THREAD

**Issue by daiaji** [containers/podman#8919]
This link mentions that LXC/LXD seems to be easy to do.
https://stackoverflow.com/questions/60189587/how-to-pass-through-physical-nic-to-docker-container

This link mentions a method of using SR-IOV devices in the user space where the container is located.
https://medium.com/@tukai.anirban/sr-iov-in-docker-containers-f13fdb297da0

Can podman also let the container pass through the network card?

At least this can reduce the pain of configuring a firewall for openwrt on the host.

**Comment by Luap99** [comment]
Yes podman also supports creating a macvlan network. The syntax is different from docker please see: https://github.com/containers/podman/blob/master/docs/source/markdown/podman-network-create.1.md#--macvlan and the last example on that page.

**Comment by Luap99** [comment]
Podman uses cni for its networking. You can also create your own cni config file and use for example the `host-device` plugin https://www.cni.dev/plugins/main/host-device/

**Comment by daiaji** [comment]
@Luap99 Thank you, I will try it.

**Comment by rhatdan** [comment]
This would be a nice blog, if either of you are interested.

**Comment by baude** [comment]
https://www.redhat.com/sysadmin/leasing-ips-podman

**Comment by RobertWojtowicz** [comment]
> https://www.cni.dev/plugins/main/host-device/

I installed the containernetworking-plugins package.
I created a configuration file, according to the example:
https://www.cni.dev/plugins/current/main/host-device/
for the sr-iov interface, but now how to use it with a podman in container, what should be the syntax ?

BR,
Robert
