### ISSUE TITLE
Error: no such file or directory on RHEL 6.9 

### ISSUE THREAD

**Issue by syaoo** [containers/podman#8924]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I have use conda install podman on RHEL 6.9 successfully, however, when trying to get the image, the following error was encountered:
````
Error: no such file or directory
````
Here is my system infomations:
```
$ uname -a
Linux localhost.localdomain 2.6.32-696.6.3.el6.x86_64 #1 SMP Wed Jul 12 14:17:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.9 (Santiago)
Release:        6.9
Codename:       Santiago
````

**Steps to reproduce the issue:**

```bash
$ podman pull ubuntu
Error: no such file or directory
```
The same error occurs in its operation
```bash
$ podman ps -a
Error: no such file or directory

$ podman build .
Error: no such file or directory
```
Only help to work properly, can get help info.

**Describe the results you received:**
There is no information except for the error prompt mentioned earlier

**Describe the results you expected:**
work normally.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman -v
podman version 2.2.1
```

**Output of `podman info --debug`:**

```
$ podman info --debug
Error: no such file or directory
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ conda list | grep podman
podman                    2.2.1                h72ce3c1_0    conda-forge
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
This is not an upstream issue, and clearly podman is not being worked on for RHEL6.  I have no idea what is going wrong here.

**Comment by mheon** [comment]
Most likely, it’s the lack of newuidmap/newgidmap binaries in RHEL 6. I do
not expect that kernel support is available either. RHEL 7 is on the
borderline of being able to run rootless Podman; RHEL 6 is far too old.
