### ISSUE TITLE
Podman events command lacks of --no-trunc option. It complicates the interpretation of event stream.

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/podman#8930]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman events command lacks --no-trunc option and always or by default emits Pod lifecycle events with the long Pod ID. All other Podman Pod lifecycle management commands: Pod stop, Pod start, Pod ls either allow using of the short ID or truncate Pod ID to its short form if --no-trunc options is provided.
It complicates the interpretation of the event stream:
What happens with my Pod after I stopped it and started it again? Its ID doesn't appear in the event stream.
**Steps to reproduce the issue:**

1. Create and start named Pod using Podman run with the --pod new:devContainerShare
2. Check that the pod is running: Podman pod ls
POD ID        NAME               STATUS  CREATED       # OF CONTAINERS  INFRA ID
f5377880e451  devcontainerShare
3. Start listening to the event stream: Podman events --filter type=pod &
3. Stop the pod using its short Id
4. Start it again
**Describe the results you received:**
Event is appear in the form 2021-01-10 22:42:13.2484531 +0200 IST pod stop f5377880e451453c3452c3e48a43d767a785660437a1315b0a11ef1e244ae136 (image=, name=devcontainerShare), ie. with long ID. The short Pod ID never appears in the event stream although Pod's state is actually changed according to Podman pod ls output. Does Podman execute Lifecycle commands on Pods created using --pod new: option? Maybe the state transition is affected by the --pod new: option?

**Describe the results you expected:**
Podman events command displays long or short Object ID's when --no-trunc option is provided or not.
The default should be the same as Podman Pod ls command, i.e. truncate.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.0.6
API Version:  1
Go Version:   go1.14.7
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.2
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.22, commit: '
  cpus: 4
  distribution:
    distribution: ubuntu
    version: "20.10"
.......
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown 2.2.1~4 amd64 [upgradable from: 2.0.6+dfsg1-1ubuntu1]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No - 2.0.0.6 is what I have for Ubuntu Groovy yet

WSL 2 Ubuntu 20.10 distro: self-upgrade from 20.04 Focal

**Comment by rhatdan** [comment]
Interested in opening a PR to add this functionality?

**Comment by umohnani8** [comment]
This is a feature request, closing the bug.
