### ISSUE TITLE
"podman pull" ignores storage.conf

### ISSUE THREAD

**Issue by ensc** [containers/podman#8940]
/kind bug

**Description**

Due to `$HOME` being in NFS, I have a `storage.conf` which relocates the graphroot.  `podman pull` seems to ignore settings there and tries to access `$HOME/.local/share.containers`.

This worked before (I am not sure when it broke).

My `~/.config/storage/containers.conf` is

```
[storage]
  driver = "overlay"
  runroot = "/run/user/505"
  graphroot = "/.local/home/ensc/.local/share/containers/storage"
```

and I get (as non-root):

```
$ podman pull   fedora:33
  open /home/ensc/.local/share/containers/sigstore/fedora@sha256=d0a84038959b1be3021cb7ffb6dae386d13a27c39519a2185eab5c4069e71295/signature-1: permission denied
```

--> it accesses `$HOME` but not the configured graphroot.  

Adding `--loglevel=debug` shows the the configured graphroot is used at some places (but ignored later):

```
$ podman pull --loglevel=debug fedora:33
DEBU[0000] Initializing boltdb state at /.local/home/ensc/.local/share/containers/storage/libpod/bolt_state.db 
   --> OK
DEBU[0005] Reading /home/ensc/.local/share/containers/sigstore/fedora@sha256=d0a84038959b1be3021cb7ffb6dae386d13a27c39519a2185eab5c4069e71295/signature-1 
   --> BAD
```

**Steps to reproduce the issue:**

1. reconfigure `graphroot` in `$HOME/.config/container/storage.conf`

2. render default graphroot inaccessible; e.g.  `chmod 000 ~/.local/share/containers`

3. try to pull an image

**Describe the results you received:**

pull failed because signature can not be read/stored

**Describe the results you expected:**

pull succeeds

**Additional information you deem important (e.g. issue happens only occasionally):**

100%

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.5
Built:        Tue Dec  8 15:37:50 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-3.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 0f53fb68333bdead5fe4dc5175703e22cf9882ab'
  cpus: 8
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: ensc-virt.intern.sigma-chemnitz.de
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 505
      size: 1
    - container_id: 1
      host_id: 505000000
      size: 1000000
    uidmap:
    - container_id: 0
      host_id: 505
      size: 1
    - container_id: 1
      host_id: 505000000
      size: 1000000
  kernel: 5.9.16-200.fc33.x86_64
  linkmode: dynamic
  memFree: 2509008896
  memTotal: 32660541440
  ociRuntime:
    name: crun
    package: crun-0.16-3.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.16
      commit: eb0145e5ad4d8207e84a327248af76663d4e50dd
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/505/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.fc33.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 2946494464
  swapTotal: 4294963200
  uptime: 122h 59m 30.07s (Approximately 5.08 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/ensc/.config/containers/storage.conf
  containerStore:
    number: 7
    paused: 0
    running: 6
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.3.0-1.fc33.x86_64
      Version: |-
        fusermount3 version: 3.9.3
        fuse-overlayfs: version 1.3
        FUSE library version 3.9.3
        using FUSE kernel interface version 7.31
  graphRoot: /.local/home/ensc/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 263
  runRoot: /run/user/505
  volumePath: /.local/home/ensc/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1607438270
  BuiltTime: Tue Dec  8 15:37:50 2020
  GitCommit: ""
  GoVersion: go1.15.5
  OsArch: linux/amd64
  Version: 2.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.2.1-1.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@vrothberg PTAL

**Comment by rhatdan** [comment]
I believe this is fixed in the main branch, we had a similar bug.  Could you verify that main has the fix?

**Comment by rhatdan** [comment]
We should have podman 3.0 rc1 available this week, if you can not build from the branch.

**Comment by vrothberg** [comment]
> open /home/ensc/.local/share/containers/sigstore

@QiWang19 @mtrmac, I am under the impression the hard-coded default in c/image is responsible.  Should we tweak it a bit to default to using `$GRAPHROOT/sigstore`?

**Comment by rhatdan** [comment]
Yes this should be able to be set via the API, it should not be hard coded.

**Comment by mtrmac** [comment]
sigstore has nothing to do with the local c/storage – it stages (or perhaps stores) signatures that conceptually belong into `docker://` registries.

There’s no reason to expect that clients like `skopeo sync` that may want to use sigstores have any c/storage store or configuration at all, so tying the default sigstore location to the c/storage graph root does not make any sense to me.

---

Specifically
> `chmod 000 ~/.local/share/containers`

IMHO fails quite clearly into the “don’t do that, then” category. There’s only so much that is reasonable to accommodate for unusual setups like $HOME not being used to actually store per-user data, or multiple separate per-user stores in a single account.

Sure, this is a quick and obvious way to reach those code paths, and the actual setup is probably less unusual.

---

The per-user directory sigstore can currently be redirected by creating a `registries.d/$foo.yaml` default configuration that points to a different `default-docker` sigstore; `registries.d` can be configured by a `types.SystemContext` passed to c/image (so, probably, a CLI option).

---

It’s a perfectly fair comment that there are too many separate configuration mechanisms and too many different ways paths are configured and defaulted; see also https://github.com/containers/skopeo/issues/849 .

**Comment by rhatdan** [comment]
Issue was explained and a work around was suggested, closing.
