### ISSUE TITLE
podman and buildah downloaded from "xUbuntu_18.04" are not compatible with Ubuntu 18.04 due to GLIBC 2.28

### ISSUE THREAD

**Issue by AlexanderSamoilov** [containers/podman#8943]
Please see first the original issue https://github.com/openSUSE/open-build-service/issues/10610 that was closed as unrelevant with a suggestion to open an issue on Podman.

PROBLEM:

I've tried running podman and buildah from Kubic project from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ on Ubuntu 18.04.

I downloaded them from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/buildah_1.18.0~3.tar.gz and https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/podman_2.2.1~4.tar.gz respectively.

Both fail on Ubuntu 18.04 with the error message "/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found", because Ubuntu/xUbuntu 18.04 have just GLIBC 2.27 and no GLIBC 2.28.

So it was either wrongly built and the build should be fixed to be indeed compatible with Ubuntu 18.04, or the subfolder name "xUbuntu_18.04" should be corrected/removed, because it confuses the user who wants to install these products for Ubuntu/xUbuntu 18.04.

If these binaries were built for some non-standard configuration (that is Ubuntu 18.04 + GLIBC 2.28) then please mention it on the download page and explain where can one get this "special" Ubuntu.

--
Best Regards,
Alexander

**Comment by rhatdan** [comment]
@lsm5 PTAL

**Comment by afbjorklund** [comment]
The build log looks reasonable:
https://build.opensuse.org/package/live_build_log/devel:kubic:libcontainers:stable/podman/xUbuntu_18.04/x86_64

```
[   18s] [23/264] installing libc6-2.27-3ubuntu1
```

Something must have wrong in the packaging... Does the regular deb work, maybe only the .tar.gz is broken ?

```
[  245s] ln: failed to create hard link '///usr/src/packages/DEBS/podman_2.2.1~4.dsc': File exists
[  245s] ln: failed to create hard link '///usr/src/packages/DEBS/podman_2.2.1~4.tar.gz': File exists
```

**Comment by AlexanderSamoilov** [comment]
Well, it took a little time for me to get the .deb files from build.opensuse.org that forced me to create an account there (download.opensuse.org provides only .tar.gz and .dsc ones).
I confirm that your assumption is right, the binaries from .deb's really work. I checked the size and md5 for the binaries in .deb's and in .tar.gz and see the big difference (the smaller ones are from .deb):

63325656 Dec  9 17:50 ~/jenkins/tools/org.jenkinsci.plugins.docker.commons.tools.DockerTool/Podman/BUILD/bin/podman
47702736 Dec  9 18:54 podman/usr/bin/podman

36139344 Dec  7 21:39 ~/jenkins/tools/org.jenkinsci.plugins.docker.commons.tools.DockerTool/Buildah/BUILD/bin/buildah
27085488 Dec  8 21:26 buildah/usr/bin/buildah

So it looks as a build issue. The .tar.gz should provide the same binaries on my opinion.
I will try to use .deb files as a quick workaround now, but could you please also fix .tar.gz?
The reason I prefer that format is that I install these container tools in the automated mode from Jenkins "Global Tool Configuration" therefore Jenkins should be able to download it without being authenticated. But as I said above, the .deb files are not available for anonymous download under https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/.

**Comment by afbjorklund** [comment]
@AlexanderSamoilov : I don't think that .tar.gz is meant for public consumption, it has a .git directory and what not. So just some internal piece of the build machinery, which is also why it requires login I suppose.

Most people would just follow https://podman.io/getting-started/installation#ubuntu

```bash
. /etc/os-release

echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_${VERSION_ID}/Release.key | sudo apt-key add -
```

Otherwise it can be a bit hard to navigate the OBS site...

### build.opensuse.org

The download button is hidden on the far right, of the landing page:
https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman
![build-opensuse-podman](https://user-images.githubusercontent.com/10364051/104343637-7799ec00-54fc-11eb-89d7-7f3968d21b76.png)

### software.opensuse.org

Then you get to the friendly page, which will lead you to the apt config or directly to the deb file:
https://software.opensuse.org//download.html?project=devel%3Akubic%3Alibcontainers%3Astable&package=podman
![software-opensuse-podman](https://user-images.githubusercontent.com/10364051/104343723-95ffe780-54fc-11eb-87d2-fde89e68b43a.png)

### download.opensuse.org

And if you do _that_ setup, then you will finally find the download location.
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/

```console
# apt-cache madison podman
    podman |    2.2.1~4 | https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  Packages
```

**Comment by AlexanderSamoilov** [comment]
Dear @afbjorklund,

Thanks for your answer! You mixed it up it little bit saying that tar.gz requires login. I needed to be logged in to get the .deb file. 
But after your explanation I understood that I used the wrong link https://build.opensuse.org/package/binaries/devel:kubic:libcontainers:stable/podman/xUbuntu_18.04.
The correct link is https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/amd64/ and I did not find where the .deb files earlier, because I looked into the upper directory (not in the /amd64).

So I can use now the .deb files in automated mode, without being logged in and this fits my expectation.
This is up to you, whether to fix tar.gz files especially if they are intended for internal usage only as you said.
Thanks again and I am closing this ticket now.

**Comment by afbjorklund** [comment]
>  This is up to you, whether to fix tar.gz files especially if they are intended for internal usage only as you said.

Actually it is up to the project. I do believe that there are some static binaries available - but those tarballs are not it.
