### ISSUE TITLE
"Failed to connect to bus" error when running systemd enabled container rootless  (podman 2.0.5)

### ISSUE THREAD

**Issue by sshnaidm** [containers/podman#8965]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. `podman run -d --privileged --name test --systemd=true ubi8/ubi-init /sbin/init`

2. `podman exec -it test bash -c "systemctl status"`

**Describe the results you received:**
And I get the error:
```
Failed to connect to bus: No such file or directory
```

If I run as root, it works:
```
$ sudo podman run -d --privileged --name test --systemd=true ubi8/ubi-init /sbin/init
0a792fca966d80f56326a98ee98d9dd35de86e7155f19a43272765fed6d715b4
$ sudo podman exec -it test bash -c "systemctl status"
● 0a792fca966d
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Wed 2021-01-13 16:53:28 UTC; 11s ago
   CGroup: /machine.slice/libpod-0a792fca966d80f56326a98ee98d9dd35de86e7155f19a43272765fed6d715b4.scope
           ├─30 systemctl status
           ├─36 more
           ├─init.scope
           │ └─1 /sbin/init
           └─system.slice
             ├─systemd-journald.service
             │ └─21 /usr/lib/systemd/systemd-journald
             └─dbus.service
               └─27 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-only


```

**Describe the results you expected:**

Expect podman rootless to work with systemd containers.

**Output of `podman version`:**

```
Version:      2.0.5
API Version:  1
Go Version:   go1.14.7
Built:        Thu Sep 24 17:58:13 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.1
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.20-2.module_el8.3.0+475+c50ce30b.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.20, commit: 1019ecdeda3936be22162bb1cca308192145de53'
  cpus: 4
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: localhost
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-240.1.1.el8_3.x86_64
  linkmode: dynamic
  memFree: 5441921024
  memTotal: 8044417024
  ociRuntime:
    name: runc
    package: runc-1.0.0-68.rc92.module_el8.3.0+475+c50ce30b.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-2.module_el8.3.0+475+c50ce30b.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 0
  swapTotal: 0
  uptime: 23h 11m 59.95s (Approximately 0.96 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/centos/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-3.module_el8.3.0+507+aa0970ae.x86_64
      Version: |-
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/centos/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 4
  runRoot: /run/user/1000/containers
  volumePath: /home/centos/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1600970293
  BuiltTime: Thu Sep 24 17:58:13 2020
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.0.5

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.5-5.module_el8.3.0+512+b3b58dca.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Latest versions on Fedora 33 work, but I need it on CentOS 8.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Selinux is permissive.

**Comment by giuseppe** [comment]
I've just tried it on CentOS 8 and it works without `--privileged`.

Any reason for using `--privileged`?  I think that can confuse systemd as it runs with more capabilities than needed.

Does it make any difference if you drop it?

**Comment by rhatdan** [comment]
No need to run with --privileged.  Should avoid --privileged almost always.

**Comment by sshnaidm** [comment]
@giuseppe tried and it seems same:
```
$ podman run -d --name test --systemd=true  registry.access.redhat.com/ubi8/ubi-init /sbin/init
$ podman exec -it test bash -c "systemctl status"
Failed to connect to bus: No such file or directory
Error: exec session exited with non-zero exit code 1: OCI runtime error
```

**Comment by giuseppe** [comment]
I've tried with podman 2.1.1 and it works on CentOS 8 using the commands above as rootless.

Is there systemd running after the first command?

**Comment by sshnaidm** [comment]
> I've tried with podman 2.1.1 and it works on CentOS 8 using the commands above as rootless.
> 
> Is there systemd running after the first command?

Yes, I compiled podman 2.1.1 and it worked for me as well. Even 2.0.6 version works like a charm. But the problem is that we can use only podman version provided by CentOS 8 and it's 2.0.5. And this version does not work.
I'm not sure how to check if systemd is running, all systemd related commands fails with "bus" error.
```
$ ./podman-2.0.5 exec -it test bash
[root@98e8348ec425 /]# ps uax
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.5  0.0  93640  7748 ?        Ss   22:47   0:00 /sbin/init
root          11 20.0  0.0  19212  3672 pts/0    Ss   22:48   0:00 bash
root          22  0.0  0.0  51820  3732 pts/0    R+   22:48   0:00 ps uax

```

**Comment by sshnaidm** [comment]
OK, by "build and test" way I've found the commit that fixed this problem, it's https://github.com/containers/podman/commit/4da3677e3f243de1cedca11976f156f980e132dc
this line:
https://github.com/containers/podman/blob/2b7793b6121d336a285fb7b9a7612c221cbf63d2/pkg/domain/infra/abi/system.go#L80

Can you come with some workaround here before this fix?

**Comment by giuseppe** [comment]
you could wrap the command with `systemd-run --scope --user`:

`systemd-run --scope --user podman run -d --name test --systemd=true ubi8/ubi-init /sbin/init`

does it work better?

**Comment by sshnaidm** [comment]
@giuseppe yes, with this command it runs fine. The problem is, we use it in [molecule podman driver](https://github.com/ansible-community/molecule-podman) and there is no option to prefix such command, it can take only `podman` command options.
Seems like no choice but downgrade to 1.6.4.

**Comment by giuseppe** [comment]
can you run the entire wrapper program inside of `systemd-run --scope --user`?

**Comment by giuseppe** [comment]
In any case, I am going to close the issue as it is not affecting upstream.  Feel free to comment further though

**Comment by developedsoftware** [comment]
I am getting this same issue (identical in fact) using podman 3.0.2.

Has there been a regression ?
Should I open another issue or keep it contained within this issue ?

**Comment by developedsoftware** [comment]
Can we make rootless use systemd as the cgroupManager? That may solve this all in one go?
