### ISSUE TITLE
Keep older versions in PPA

### ISSUE THREAD

**Issue by matpen** [containers/podman#8971]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I am filing this issue to reopen the discussion on https://github.com/containers/podman/issues/3924.

At the moment, we still do not have a comfortable way to select a particular package version: 
* as discussed in #3924, the [project atomic PPA](https://launchpad.net/~projectatomic/+archive/ubuntu/ppa) does not support this;
* it seems like [OBS](https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/buildah) does not support this either ( `apt-cache madison buildah` shows only one version, the latest);
* the new [libpod PPA](https://launchpad.net/ubuntu/+source/libpod) does not support this either;
* as explained [here](https://github.com/containers/podman/issues/3924#issuecomment-668855523) and [here](https://github.com/containers/podman/issues/3924#issuecomment-669018703) using the default repos is not always an option, and generally only provides outdated versions.

**Comment by matpen** [comment]
@lsm5 I renew my intention to have a look at the OBS configuration, if you are still willing to support my progress and be patient while I try to find the time for this.

**Comment by vrothberg** [comment]
Please drop a comment in https://github.com/containers/podman/issues/3924.  I'm going to reopen and close this one here, so all eyes on https://github.com/containers/podman/issues/3924 will see the new discussion.
