### ISSUE TITLE
flake: remote: podman cp dir from host to container

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#8972]
podman-remote cp tests are flaking; so far only on ubuntu-2004. Symptom is:
```console
# podman-remote --url unix:/tmp/podman.RlDd0r exec cpcontainer cat /usr//hostfile0
#/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
#|     FAIL: copy contents of dir to usr/ (cp -> ctr:/usr/)
#| expected: 'random-0-C2gGRg2DgJ'
#|   actual: ''
#\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Instances to date:

## sys: podman cp dir from host to container
* gce_instance:prior-ubuntu : sys remote ubuntu-2004 root host
  * PR #8960
    * [01-13 12:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6496656617111552/html/sys-remote-ubuntu-2004-root-host.log.html)
  * PR #8923
    * [01-11 06:52](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5012806921617408/html/sys-remote-ubuntu-2004-root-host.log.html)
  * PR #8905
    * [01-11 19:21](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6746605023920128/html/sys-remote-ubuntu-2004-root-host.log.html)
  * PR #8904
    * [01-06 19:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6111985689427968/html/sys-remote-ubuntu-2004-root-host.log.html)
  * PR #8813
    * [12-23 06:04](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6477341243211776/html/sys-remote-ubuntu-2004-root-host.log.html)
  * PR #8804
    * [12-22 12:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5076482294808576/html/sys-remote-ubuntu-2004-root-host.log.html)

Also seen in [nightly cron](https://cirrus-ci.com/task/6345347066757120)

Test context: https://github.com/containers/podman/blob/bbff9c8710870bbadbaf2e69e827db30c109bbb9/test/system/065-cp.bats#L139

**Comment by vrothberg** [comment]
Thanks, @edsantiago!  Do you know how long it's happening already?

**Comment by edsantiago** [comment]
The first comment shows all instances known to my cirrus-flake-summarize script. It shows the first instance on 2020-12-22.

**Comment by vrothberg** [comment]
I will take a look at it once #8281 is fixed.

**Comment by vrothberg** [comment]
Looking at the failure, I am under the impression that `remote exec` is the flaky.

The file seems to be copied since we're not getting an ENOENT from the container.  So it seems like `remote exec` is missing the output.

**Comment by vrothberg** [comment]
The listed flakes have on thing in common: `sys remote ubuntu-2004 root host`

**Comment by edsantiago** [comment]
Well, now that you mention it, I searched my flake logs for anything that happens only on ubuntu 2004:

## sys: podman cp into a subdirectory matching GraphRoot
* gce_instance:prior-ubuntu : sys remote ubuntu-2004 root host
  * PR #8905
    * [01-12 06:50](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5482988869779456/html/sys-remote-ubuntu-2004-root-host.log.html)

## sys: podman cp into container: weird symlink expansion
* gce_instance:prior-ubuntu : sys remote ubuntu-2004 root host
  * PR #8871
    * [01-04 10:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5058281330704384/html/sys-remote-ubuntu-2004-root-host.log.html)

**Comment by edsantiago** [comment]
Here's one with a similar symptom, but it's f33 and *not* remote??

## sys: podman exec - with keep-id
* gce_instance:fedora : sys podman fedora-33 root host
  * PR #8992
    * [01-17 09:03](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4599307435245568/html/sys-podman-fedora-33-root-host.log.html)

**Comment by vrothberg** [comment]
It's smelling a like a race with conmon.  A tough cookie without an easy reproducer.

I'll skip this one for now in hope to get a better reproducer or for it to magically disappear.

**Comment by vrothberg** [comment]
My hopes are high the flake has been fixed with the latest conmon v2.0.26 (currently in testing for F3{2,3}).

**Comment by rhatdan** [comment]
@edsantiago Can you confirm/deny @vrothberg decision, IE Can we close this issue?

**Comment by edsantiago** [comment]
@vrothberg's comment was on Feb 8. I see one instance since then:

## sys: podman cp dir from host to container
* gce_instance:prior-ubuntu : sys remote ubuntu-2004 root host
  * PR #9598
    * [03-03 19:02](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6522650668302336/html/sys-remote-ubuntu-2004-root-host.log.html)

...but that was `conmon-2.0.22~1-amd64`. Unfortunately this is one of those flakes that appears in multiple tests, so I can't know if it's still present unless I go through all flake logs. But I will close for now, and reopen if I see it again.

**Comment by edsantiago** [comment]
It's not dead. ([remote ubuntu 2110 root](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6612265603432448/html/sys-remote-ubuntu-2110-root-host.log.html#t--00116)):
```
# # podman-remote --url unix:/tmp/podman_tmp_52Zm exec cpcontainer cat /srv/subdir/hostfile0
# #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
# #|     FAIL: copy to workdir/subdir (cp -> ctr:subdir)
# #| expected: 'random-0-BpQsfwQPb8'
# #|   actual: ''
# #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
It's the old ubuntu, which we no longer test, so I'm not going to reopen this issue.

**Comment by edsantiago** [comment]
Reopening, because we just saw this on 36-aarch64:

* fedora-36-aarch64 : sys remote fedora-36-aarch64 root host [remote]
  * PR #16207
    * [10-17 16:10](https://api.cirrus-ci.com/v1/artifact/task/5712566482632704/html/sys-remote-fedora-36-aarch64-root-host.log.html#t--00134)

**Comment by edsantiago** [comment]
Looks like this is another Ubuntu-only error.
