### ISSUE TITLE
Podman cannot find network with dnsname

### ISSUE THREAD

**Issue by chintan-mishra** [containers/podman#8984]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. Create a network using `sudo podman network create test`

2. Install the `dnsname` plugin using this [doc](https://github.com/containers/dnsname/blob/master/README_PODMAN.md)

3. Running the **Example: container name resolution** section throws the following error.

**Describe the results you received:**
```
ERRO[0000] CNI network "test" not found                 
Error: error configuring network namespace for container ***********************d87d64ca17cd8c: CNI network "test" not found
```

**Describe the results you expected:**
The container should run by default without throwing CNI errors.

**Additional information you deem important (e.g. issue happens only occasionally):**
I am in the middle of migrating dev infra to CentOS Stream. This apparently works fine in an old installation of Fedora 32 Server.

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.2
Built:        Thu Dec 17 16:10:45 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.21-3.module_el8.4.0+581+8bd31022.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 4cff974a37907e701aa2e31ad480ccc6f3f586f5'
  cpus: 1
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: ip-172-31-10-159.ap-south-1.compute.internal
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-259.el8.x86_64
  linkmode: dynamic
  memFree: 1230487552
  memTotal: 1902043136
  ociRuntime:
    name: runc
    package: runc-1.0.0-69.rc92.module_el8.4.0+581+8bd31022.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module_el8.4.0+581+8bd31022.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 0
  swapTotal: 0
  uptime: 40m 32.91s
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/centos/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.3.0-1.module_el8.4.0+581+8bd31022.x86_64
      Version: |-
        fusermount3 version: 3.2.1
        fuse-overlayfs: version 1.3
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/centos/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/centos/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1608221445
  BuiltTime: Thu Dec 17 16:10:45 2020
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.2.1-2.module_el8.4.0+581+8bd31022.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Comment by Luap99** [comment]
Please paste the content of the cni config file.

**Comment by baude** [comment]
the dns plugin must be installed prior to creating the network.

**Comment by chintan-mishra** [comment]
@Luap99  If you are referring to `/etc/cni/net.d/*.conflist` then here it is

<details>
<summary>
Here is the CNI config
</summary>

```
{
   "cniVersion": "0.4.0",
   "name": "lz",
   "plugins": [
      {
         "type": "bridge",
         "bridge": "cni-podman1",
         "isGateway": true,
         "ipMasq": true,
         "hairpinMode": true,
         "ipam": {
            "type": "host-local",
            "routes": [
               {
                  "dst": "0.0.0.0/0"
               }
            ],
            "ranges": [
               [
                  {
                     "subnet": "10.89.1.0/24"
                  }
               ]
            ]
         }
      },
      {
         "type": "portmap",
         "capabilities": {
            "portMappings": true
         }
      },
      {
         "type": "firewall",
         "backend": ""
      },
      {
         "type": "tuning"
      },
      {
         "type": "dnsname",
         "domainName": "dns.podman",
         "capabilities": {
            "aliases": true
         }
     }
   ]
}
```
</details>

@baude  I installed `dnsmasq` before creating the network.

**Comment by baude** [comment]
the network name in the example you provided is `lz`.  In your report earlier, you report that `test` was not found.  are you passing --network `lz` or `test`?

**Comment by chintan-mishra** [comment]
@baude the network's name is `test`.
 
I was sanitizing the data by replacing `lz` with `test`.

`lz` and `test` have the same config. Apologies for the confusion

**Comment by Luap99** [comment]
Can you run the podman run command with `--log-level debug` and paste the output. Also you explicitly mention the use of dnsname does it work without the plugin?

**Comment by baude** [comment]
I also pulled down your config file and ran it successfully with upstream fwiw

**Comment by chintan-mishra** [comment]
Thank you, @Luap99 and @baude for taking the time to help with this issue.

It slipped from my mind that on CentOS we need to compile the plugin manually as `dnsname` is not available by default.

Once installed, everything works as it is supposed to. Can we have `dnsname` plugin available by default on CentOS?

**Comment by andrimanna** [comment]
> It slipped from my mind that on CentOS we need to compile the plugin manually as `dnsname` is not available by default.
> 
> Once installed, everything works as it is supposed to. Can we have `dnsname` plugin available by default on CentOS?

I figured out that there is the package `podman-plugins` that contains `/usr/libexec/cni/dnsname`. Just install it.
