### ISSUE TITLE
COPR stops building

### ISSUE THREAD

**Issue by xcffl** [containers/podman#8991]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The [COPR repo](https://copr.fedorainfracloud.org/coprs/baude/Upstream_CRIO_Family/) listed in the[ installation page](https://podman.io/getting-started/installation) has stopped building for monthes. Although the latest builds fails, it only failed for Fedora 31, not the newer versions. So disabling builds for old releases should make it work.

Why should it be enabled after all? At least it's useful to test whether some issues persist in the git version.

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by baude** [comment]
fixed up! no more f32 or f32 and 33 and rawhide built
