### ISSUE TITLE
Improve swagger docs and mention which endpoints support auth headers

### ISSUE THREAD

**Issue by towe75** [containers/podman#8993]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Your HTTP API reference for libpod/images/pull at https://docs.podman.io/en/latest/_static/api.html#operation/libpodImagesPull includes a "credentials" query Parameter. But the handler at https://github.com/containers/podman/blob/v2.2/pkg/api/handlers/libpod/images_pull.go seems not to make use of it. 

Following the bread crumps i would guess that we can rather user docker'ish X-Registry-Auth / X-Registry-Config Headers.
Please clarify and improve/fix the documentation if i'm right. 

Further i am wondering how to use credential helpers correctly via HTTP API. I assume one has to configure global helpers via containers-auth.json and "it just works"? There is no way to influence/configure this via API, is it?

**Comment by vrothberg** [comment]
> Your HTTP API reference for libpod/images/pull at https://docs.podman.io/en/latest/_static/api.html#operation/libpodImagesPull includes a "credentials" query Parameter. But the handler at https://github.com/containers/podman/blob/v2.2/pkg/api/handlers/libpod/images_pull.go seems not to make use of it.
> 
> Following the bread crumps i would guess that we can rather user docker'ish X-Registry-Auth / X-Registry-Config Headers.
> Please clarify and improve/fix the documentation if i'm right.

That's correct. Credentials can be set via the header.

> Further i am wondering how to use credential helpers correctly via HTTP API. I assume one has to configure global helpers via containers-auth.json and "it just works"? There is no way to influence/configure this via API, is it?

Both are correct.

Thanks for reaching out.  We should definitely fix that in the docs.

**Comment by towe75** [comment]
@vrothberg thank you for info.

**Comment by rhatdan** [comment]
@towe75 Interested in opening a PR to help fix the docs?

**Comment by towe75** [comment]
@rhatdan i am actually tempted to cut some time in order to bring the podman project forward. But docs are certainly not my strength and i am not really familiar with the docker-way-of-auth, sorry. I can possibly help with setting up some ubuntu package tests via GH actions or having 2 ubuntu versions in the repo etc.  I will ping you on some another channel when i'm ready, ok?

**Comment by rhatdan** [comment]
@jwhonce PTAL at fixing these docs?

**Comment by rhatdan** [comment]
@cdoern PTAL

**Comment by cdoern** [comment]
@rhatdan will do, I have actually been looking at something similar on the libpod end with platform query parameters.

**Comment by rhatdan** [comment]
Looks like a bunch of fixes have merged, I am closing reopen if more need to be fixed.
