### ISSUE TITLE
"podman play kube" pipe input

### ISSUE THREAD

**Issue by ADIX7** [containers/podman#8996]
/kind feature

It would be great if `podman play kube` could use input from pipe. I try to use kustomize with podman and would like to do something like `kustomize build my-overlay | podman play kube`.

**Comment by rhatdan** [comment]
Seams reasonable, interested in opening a PR?

kustomize build my-overlay | podman play kube -

Would be potential syntax.

Then have podman play kube use the - to read from stdin, create a temporary file and go to down.

**Comment by ADIX7** [comment]
Unfortunately I'm a not a GO developer, I use mostly C# and JS. Nevertheless, I will try it.
