### ISSUE TITLE
Headless podman login fails in CI with "error creating tmpdir: mkdir /run/user/1000: permission denied"

### ISSUE THREAD

**Issue by svdHero** [containers/podman#9002]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

In my Jenkins CI we build container images and push them to our local container registry. This works most of the time. However, every now and then (a couple of times per day) the Jenkins build fails with the following error message just after executing `podman login`:
```
Error: error creating tmpdir: mkdir /run/user/1000: permission denied
script returned exit code 125
```

Why is that? I cannot see any pattern when and why this would happen. It just does on a (ir)regular basis.

**Steps to reproduce the issue:**

1. Create Containerfile with content:
```docker
FROM busybox

ENTRYPOINT echo "Hello World"
```

2. Execute
```
cat /home/my_ci_user/harbor_robot_tokens/CI_Robot.txt | podman login --username robot\$CI_Robot --password-stdin harbor.my.local.domain.com
podman build -t my-awesome-image:latest
podman tag my-awesome-image:latest harbor.my.local.domain.com/my-project/my-awesome-image:latest
podman push harbor.my.local.domain.com/my-project/my-awesome-image:latest
```

**Describe the results you received:**

Build job fails just after the `podman login` command with an output:
```
Error: error creating tmpdir: mkdir /run/user/1000: permission denied
script returned exit code 125
```

**Describe the results you expected:**

Build job succeeds with output
```
Login Succeeded!
```
after the login command.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens only a couple of times a day.

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.2
Built:        Thu Jan  1 00:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.22, commit: '
  cpus: 2
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: linux-jenkins
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.4.0-60-generic
  linkmode: dynamic
  memFree: 3339444224
  memTotal: 8348889088
  ociRuntime:
    name: runc
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc92
      commit: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
      spec: 1.0.2-dev
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 0.4.3
      commit: 2244b9b6461afeccad1678fac3d6e478c28b4ad6
  swapFree: 4294426624
  swapTotal: 4294963200
  uptime: 117h 37m 5.3s (Approximately 4.88 days)
registries:
  search:
  - docker.io
  - quay.io
  - harbor.my.local.domain.com
store:
  configFile: /home/my_ci_user/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.9.0
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.9.0
        using FUSE kernel interface version 7.31
  graphRoot: /home/my_ci_user/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 227
  runRoot: /run/user/1000/containers
  volumePath: /home/my_ci_user/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.2.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
apt list podman
Listing... Done
podman/unknown,now 2.2.1~4 amd64 [installed]
podman/unknown 2.2.1~4 arm64
podman/unknown 2.2.1~4 armhf
podman/unknown 2.2.1~4 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Jenkins Linux build slave on a virtual server on VMWare

**Comment by rhatdan** [comment]
Did you enable to account to linger?

**Comment by svdHero** [comment]
What exactly do you mean by that? Sorry, in case that is a stupid question. 🙈

**Comment by edsantiago** [comment]
As root: `loginctl enable-linger my_ci_user`. It's a systemd thing, and is pretty much necessary for running rootless podman.

**Comment by svdHero** [comment]
Thank you for clarifying. The concept of `user lingering` is new to me. So far I have only written simple systemd service files.

I will try and see if enabling helps with my problem.
Just to make sure I understood the context correctly: The fact that my build only fails occasionally, has something to do with timing then? If the build takes too long, the user session is closed already? Or how would that lingering argument work?

**Comment by edsantiago** [comment]
I... don't really know. I think it might have to do with, if you're ssh'ed in as that account while the cron job is running, it'll work, but the cron job by itself, with no actual session login, makes everything fail. For me it's just superstition: any time I set up a new account anywhere having to do with systemd, I automatically run the magic `loginctl` command, and things work better.

**Comment by svdHero** [comment]
😆👍
Superstition. I like it.

**Comment by rhatdan** [comment]
Bottom line is, systemd kills processes that relate to a user account when the user logs out.  Enabling linger mode allows the processes to stay running.  Similarly if you want systemd to setup a user session at boot time, then  you need to enable it.  Podman running as a rootless user needs a user session.

**Comment by svdHero** [comment]
Yeah, I understand that. However, in my case, while the build job is running and my build script is right in the middle of being executed, I can't see  how my Jenkins CI user would not be logged in. That just doesn't seem to make sense.

But I will give it a try over the next dew days. Let's see if that fixes my problems.

**Comment by edsantiago** [comment]
@svdHero my understanding is that systemd somehow distinguishes between "user processes that have come in via a console, or X11, or ssh" and "user processes run from cron or nohup'ed". For some reason, systemd thinks it is very important to kill user processes if there's no "session". For oldtime UNIX people this is incomprehensible and infuriating, but we have to live with it. The magic `loginctl` is the way to get a useful working system again. HTH.

**Comment by rhatdan** [comment]
Basically if the user session is not started using pam_systemd within the pam stack, then the session including /run/user/UID will not be setup properly.  Podman relies on this /run/user/UID directory existing to do it's thing.

**Comment by svdHero** [comment]
I did the magical `loginctl enable-linger my_ci_user` and haven't encountered any permission problems anymore.
Thanks for helping, everyone. :+1:

**Comment by Puiu** [comment]
I am running podman in WSL2 and I got this error after I've restarted the host. The solution for me was to run in powershell on the host the command: `podman machine start`

Maybe it will help someone that runs into this for the same reason as me.
