### ISSUE TITLE
cannot run nginx on Raspberry Pi OS (64 bit debian 10)

### ISSUE THREAD

**Issue by hetzbh** [containers/podman#9019]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I've installed Podman 2.2.1 arm64 on Raspberry Pi 4 with Raspberry pi 64 bit OS (arm64)
I then tried to simply launch nginx as non root: podman run -dt -p 8080:8080/tcp nginx

It fails. Details below.

**Steps to reproduce the issue:**

1. Install (using the official instructions) podman on Pi 4 with Raspberry Pi OS 64 bit beta

2. Try to launch nginx container: `podman run -dt -p 8080:8080/tcp nginx`

**Describe the results you received:**

Error: `Error: /usr/bin/slirp4netns failed: "/usr/bin/slirp4netns: unrecognized option '--netns-type=path'\nUsage: /usr/bin/slirp4netns [OPTION]... PID TAPNAME\nUser-mode networking for unprivileged network namespaces.\n\n-c, --configure      bring up the interface\n-e, --exit-fd=FD     specify the FD for terminating slirp4netns\n-r, --ready-fd=FD    specify the FD to write to when the network is configured\n-m, --mtu=MTU        specify MTU (default=1500, max=65521)\n-6, --enable-ipv6    enable IPv6 (experimental)\n-h, --help           show this help and exit\n-v, --version        show version and exit\n"`

**Describe the results you expected:**
nginx running :)

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.2
Built:        Thu Jan  1 02:00:00 1970
OS/Arch:      linux/arm64
```

**Output of `podman info --debug`:**

```
host:
  arch: arm64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.22, commit: '
  cpus: 4
  distribution:
    distribution: debian
    version: "10"
  eventLogger: journald
  hostname: hetz-pi.hetzlabs.io
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.10.5-v8+
  linkmode: dynamic
  memFree: 1854840832
  memTotal: 3979771904
  ociRuntime:
    name: runc
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 0.2.3
      commit: be6d34ba4c7ac62b9f31b0ea931ec91a5f16dc3b
  swapFree: 104853504
  swapTotal: 104853504
  uptime: 59h 46m 52.43s (Approximately 2.46 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/hetz/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 0
    stopped: 2
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/hetz/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 1
  runRoot: /run/user/1001/containers
  volumePath: /home/hetz/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 0
  BuiltTime: Thu Jan  1 02:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/arm64
  Version: 2.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
 $ apt list podman
Listing... Done
podman/unknown 2.2.1~4 amd64
podman/unknown,now 2.2.1~4 arm64 [installed]
podman/unknown 2.2.1~4 armhf
podman/unknown 2.2.1~4 ppc64el
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Raspberry Pi 4B, 4GB version.

**Comment by vrothberg** [comment]
Looks like `slirp4netns` is too old.  How did you install Podman?

**Comment by hetzbh** [comment]
I've installed it from buster-backports, the one that mentioned in the official instructions [here](https://podman.io/getting-started/installation).
Looks like the current version which can be obtained from [here](https://github.com/rootless-containers/rootlesskit/releases) will work for now. Any chance that someone would fix the package please?

**Comment by vrothberg** [comment]
Thanks, @hetzbh!

@lsm5 PTAL

**Comment by lsm5** [comment]
> I've installed it from buster-backports, the one that mentioned in the official instructions [here](https://podman.io/getting-started/installation).
> Looks like the current version which can be obtained from [here](https://github.com/rootless-containers/rootlesskit/releases) will work for now. Any chance that someone would fix the package please?

@hetzbh did it specifically pull in from buster-backports? The buster-backports repo was only meant for libseccomp dependency. There's a new slirp4netns available in the Kubic project repo itself, https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/slirp4netns . I will enforce that as the minimum dependency for podman, but that fix will show up on the Kubic Stable only once we have 3.0.0 released, until then I will push changes only to the Kubic Testing project.

**Comment by rhatdan** [comment]
I believe this issue is answered. Closing.  Reopen if I am mistaken.
