### ISSUE TITLE
Enable github discussions

### ISSUE THREAD

**Issue by ssbarnea** [containers/podman#9033]
Please enable github discussions, at least experimentally to enable us fully evaluate its benefits.

I am quite pleased about my personal experience with it of several projects (2-3k stars)

* helped decluttering the issue tracker
* makes much easier for new users to join the community: both irc and mailing list are old-school mediums which have a considerably higher entry barrier

Note: enabling/disabling the feature is just a checkbox on project settings.

**Comment by vrothberg** [comment]
I am supportive of the idea.  It would be great to have community members help us.

@containers/podman-maintainers @fatherlinux PTAL

**Comment by saschagrunert** [comment]
I'm also in favor of discussions, larger topics can be transferred to the discussion board and we're able to thread into single comments rather than quoting.

**Comment by mheon** [comment]
SGTM

**Comment by TomSweeneyRedHat** [comment]
Discussions are now live!  Thanks for the request!
