### ISSUE TITLE
podman generate systemd doesn't work as expected while using --new flag and container with log-opt tag set

### ISSUE THREAD

**Issue by sixeIa** [containers/podman#9034]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

While creating a container with `--log-driver=journald` and _--log-opt=tag={{.Name}}_ specified, we're unable to generate a systemd file while forcing _--new_.
Facing an error: "_Error: template: container_template:15:162: executing "container_template" at <.Name>: can't evaluate field Name in type *generate.containerInfo_"

**Steps to reproduce the issue:**

1. Create a random container (in this example, nginx): `sudo podman run -d --log-driver=journald --log-opt=tag={{.Name}} --name=nginx nginx`

2. Try to generate systemd file `sudo podman generate systemd --name nginx --new`

**Describe the results you received:**

`Error: template: container_template:15:162: executing "container_template" at <.Name>: can't evaluate field Name in type *generate.containerInfo`

**Describe the results you expected:**

Systemd file generated with log-opt option set correctly.

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.5
Built:        Tue Dec  8 15:37:50 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.21-3.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 0f53fb68333bdead5fe4dc5175703e22cf9882ab'
  cpus: 2
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: fedora
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.7-200.fc33.x86_64
  linkmode: dynamic
  memFree: 157720576
  memTotal: 2040107008
  ociRuntime:
    name: crun
    package: crun-0.16-3.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.16
      commit: eb0145e5ad4d8207e84a327248af76663d4e50dd
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 756019200
  swapTotal: 1019211776
  uptime: 3h 20m 2.33s (Approximately 0.12 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 1
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 4
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1607438270
  BuiltTime: Tue Dec  8 15:37:50 2020
  GitCommit: ""
  GoVersion: go1.15.5
  OsArch: linux/amd64
  Version: 2.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.2.1-1.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Tried on a Fedora 33 virtual machine

**Comment by vrothberg** [comment]
Thanks for reaching out, @sixeIa!  The tricky part is the `{{.Name}}` in the command line which is overlapping with the fields of the internal generator.

I will play with it a bit and check what we can do.

**Comment by Luap99** [comment]
The easiest thing might be changing the delimiter for the internal template https://golang.org/pkg/text/template/#Template.Delims

**Comment by vrothberg** [comment]
EDIT: the problem is that we're also using Go templating to generate the container, so `{{ .Name }}` cannot work.

What you can do as a workaround_ is to remove `--log-driver=journald` from the command, generate the .service files and add `--log-driver=journald ` to the file.

**Comment by sixeIa** [comment]
And it could not exist something to escape the {{ .Name }} ?

Yes that's what we're doing now.

**Comment by vrothberg** [comment]
> The easiest thing might be changing the delimiter for the internal template https://golang.org/pkg/text/template/#Template.Delims

@Luap99 got time to tackle it?

**Comment by Luap99** [comment]
@vrothberg Yes. I will tackle it.

**Comment by vrothberg** [comment]
Thanks, @Luap99 !

**Comment by Luap99** [comment]
PR #9035 to fix
