### ISSUE TITLE
flake: error reading /etc/cni/net.d/something

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#9041]
Starting to see a lot of this one:
```
Running: podman [options] network rm -f testNetThreeCNI2
Error: in /etc/cni/net.d/testNetSingleCNI.conflist: error reading /etc/cni/net.d/testNetSingleCNI.conflist: open /etc/cni/net.d/testNetSingleCNI.conflist: no such file or directory
```
...which then cascades into:
```
Running: podman [options] network create testNetThreeCNI2
Error: the network name testNetThreeCNI2 is already used
```
ISTR this being a race condition between `network create` and `network rm`, and thought there was an open issue about it already, but I can't find it now.

## Podman network [It] podman inspect container two CNI networks (container not running)
* fedora : int podman fedora-32 root host
  * PR #8030
    * [10-15 06:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5326005927673856/html/int-podman-fedora-32-root-host.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---1)
    * [10-15 06:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5326005927673856/html/int-podman-fedora-32-root-host.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---2)
    * [10-15 06:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5326005927673856/html/int-podman-fedora-32-root-host.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---3)
* gce_instance:fedora : int podman fedora-33 root container
  * PR #8956
    * [01-14 12:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5083534094237696/html/int-podman-fedora-33-root-container.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---1)
    * [01-14 12:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5083534094237696/html/int-podman-fedora-33-root-container.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---2)
    * [01-14 12:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5083534094237696/html/int-podman-fedora-33-root-container.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---3)
* gce_instance:fedora : int podman fedora-33 root host
  * PR #8486
    * [11-26 06:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6182710563569664/html/int-podman-fedora-33-root-host.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---1)
    * [11-26 06:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6182710563569664/html/int-podman-fedora-33-root-host.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---2)
    * [11-26 06:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6182710563569664/html/int-podman-fedora-33-root-host.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---3)
* gce_instance:prior-fedora : int podman fedora-32 root container
  * PR #9014
    * [01-20 11:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6745074539167744/html/int-podman-fedora-32-root-container.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---1)
    * [01-20 11:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6745074539167744/html/int-podman-fedora-32-root-container.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---2)
    * [01-20 11:29](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6745074539167744/html/int-podman-fedora-32-root-container.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---3)
* gce_instance:prior-fedora : int podman fedora-32 root host
  * PR #8306
    * [11-11 11:43](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5064390275760128/html/int-podman-fedora-32-root-host.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---1)
    * [11-11 11:43](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5064390275760128/html/int-podman-fedora-32-root-host.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---2)
    * [11-11 11:43](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5064390275760128/html/int-podman-fedora-32-root-host.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---3)
* gce_instance:ubuntu : int podman ubuntu-20 root host
  * PR #8493
    * [11-27 06:39](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5928499217170432/html/int-podman-ubuntu-20-root-host.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---1)
    * [11-27 06:39](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5928499217170432/html/int-podman-ubuntu-20-root-host.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---2)
    * [11-27 06:39](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5928499217170432/html/int-podman-ubuntu-20-root-host.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---3)
* gce_instance:ubuntu : int podman ubuntu-2010 root host
  * PR #8794
    * [12-21 08:03](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5747335080706048/html/int-podman-ubuntu-2010-root-host.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---1)
    * [12-21 08:03](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5747335080706048/html/int-podman-ubuntu-2010-root-host.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---2)
    * [12-21 08:03](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5747335080706048/html/int-podman-ubuntu-2010-root-host.log.html#t--podman-inspect-container-two-CNI-networks--container-not-running---3)
```

**Comment by Luap99** [comment]
I take a look. I think we should get rid of static network names and only use random ones.

**Comment by edsantiago** [comment]
@Luap99 I don't think that's the issue; I think it would happen even with `stringid.GenerateNonCryptoID()`. This seems to be a race  where something reads the `conf` directory, then acts on that list of files, but in the interim one of the files has disappeared.

**Comment by Luap99** [comment]
It's not the real issue but at least it would prevent a full failure in CI.
I agree with you that there is a race somewhere.

**Comment by Luap99** [comment]
OK @baude added a lockfile which should prevent these races but the lockfile is located in the tmpdir and not in the cni config dir. Therefore a second parallel test with a network create/remove call did not get the lock.

I think the best solution is to move the lockfile into the cni config directory.
