### ISSUE TITLE
Podman failed behind the proxy

### ISSUE THREAD

**Issue by Smahane** [containers/podman#9056]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. sudo yum install podman

2. podman run hello-world

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/5471356/105388954-8cbafd00-5c17-11eb-908e-87b880fe131a.png)

**Describe the results you expected:**
Hello world

**Additional information you deem important (e.g. issue happens only occasionally):**
Running on Centos7
**Output of `podman version`:**

```
podman version 2.2.1
```

**Output of `podman info --debug`:**

```
(base) bash-4.2$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.25-1.el7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: b1d355eec611e7d8db7fc65511cf5e2071856dd0'
  cpus: 80
  distribution:
    distribution: '"centos"'
    version: "7"
  eventLogger: journald
  hostname: ortce-skl9
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 100
      size: 1
    - container_id: 1
      host_id: 200000
      size: 1001
    uidmap:
    - container_id: 0
      host_id: 11416778
      size: 1
    - container_id: 1
      host_id: 200000
      size: 1001
  kernel: 3.10.0-1062.12.1.el7.x86_64
  linkmode: dynamic
  memFree: 27557105664
  memTotal: 201435746304
  ociRuntime:
    name: runc
    package: containerd.io-1.4.3-3.1.el7.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc92
      commit: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
      spec: 1.0.2-dev
  os: linux
  remoteSocket:
    path: /tmp/podman-run-11416778/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /bin/slirp4netns
    package: slirp4netns-0.4.3-4.el7_8.x86_64
    version: |-
      slirp4netns version 0.4.3
      commit: 2244b9b6461afeccad1678fac3d6e478c28b4ad6
  swapFree: 0
  swapTotal: 0
  uptime: 3218h 6m 3.41s (Approximately 134.08 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /nfs/pdx/home/sdouyeb/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.2-6.el7_8.x86_64
      Version: |-
        fuse-overlayfs: version 0.7.2
        FUSE library version 3.6.1
        using FUSE kernel interface version 7.29
  graphRoot: /nfs/pdx/home/sdouyeb/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: nfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /tmp/run-11416778/containers
  volumePath: /nfs/pdx/home/sdouyeb/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1607538826
  BuiltTime: Wed Dec  9 10:33:46 2020
  GitCommit: ""
  GoVersion: go1.15.5
  OsArch: linux/amd64
  Version: 2.2.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.2.1-1.el7.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Barematal system

**Comment by mheon** [comment]
Can you provide details on your proxy configuration - what environment variables are set, at a minimum.

**Comment by Smahane** [comment]
Hello @mheon . I exported http_proxy, https_proxy and all_proxy in the environment before running `podman run hello-world`

**Comment by mtrmac** [comment]
`proxyconnect tcp`: means that it is actually connecting to something. See what’s going on using something like Wireshark?

**Comment by Smahane** [comment]
@rhatdan @mtrmac  I have both Singularity and Docker working perfectly fine on this system. Singularity run with Go. Is there a way to setup the proxies for Podman if it doesn't take the system proxies?

**Comment by mtrmac** [comment]
But it did.

**Comment by Smahane** [comment]
As of now, this is still an issue that is preventing me from using Podman. The admin and many users don't have any issues working with other apps in the lab. So it's clearely a Podman issue.

**Comment by mheon** [comment]
Without further details on proxy configuration I don't know if we can help. Podman does not perform any proxy configuration, or take any action at all on proxies - it is all handled by the Go standard library. With further details, a bug could be filed against the Go standard library (we've had to do this before on proxy handling).

**Comment by rhatdan** [comment]
Any chance could you check if buildah/skopeo have the same problems?  If they work, and Podman does not then we could do further investigation.  If they don't then the issue is either in your setup, Golang or containers/image.

**Comment by edsantiago** [comment]
@Smahane ping, have you had a chance to try buildah or skopeo to see if they present the same issues?

**Comment by Smahane** [comment]
I'm not familiar with buildah/skopeo. So far I'm getting this error bellow. I will need to google a bit

(base) bash-4.2$ buildah pull docker-daemon:hello-world
Error during unshare(CLONE_NEWUSER): Invalid argument
User namespaces are not enabled in /proc/sys/user/max_user_namespaces.
ERRO error parsing PID "": strconv.Atoi: parsing "": invalid syntax
ERRO (unable to determine exit status)

**Comment by rhatdan** [comment]
You are on a RHEL7 box and have to enable the /proc/sys/user/max_user_namespaces in order to use user namespace for rootless podman or rootless buildah.

Could you try to do these commands as root, and see if they work with your proxy?

**Comment by vrothberg** [comment]
Friendly ping. @Smahane, are you still seeing the issue?

**Comment by rhatdan** [comment]
No response from reporter, closing.
