### ISSUE TITLE
rootless: `podman run --net=<CNI> -p <PORT>` is broken on master

### ISSUE THREAD

**Issue by AkihiroSuda** [containers/podman#9065]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

`podman run --net=<CNI> -p <PORT>` with rootless is broken on master, due to regression in #9052

**Steps to reproduce the issue:**

1. `podman network create foo`

2. `podman run -d --name nginx --network foo -p 8080:80 nginx:alpine`

3. `curl localhost:8080`

**Describe the results you received:**
`curl: (56) Recv failure: Connection reset by peer`

**Describe the results you expected:**
`...<title>Welcome to nginx!</title>...`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

f02aba659447ea9198851231d7f11a8bfdfe69ba is broken.
6fd83de31dab0c60932972c6b26f68fa0bd1871f works.
regression in #9052

**Comment by rhatdan** [comment]
@giuseppe @AkihiroSuda Could one of you open a PR to fix

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/podman/pull/9066
