### ISSUE TITLE
clarify wording of REST client for Windows/Mac

### ISSUE THREAD

**Issue by mattcen** [containers/podman#9104]
I was just reading the "What it Podman" page, and found a confusing paragraph.

https://github.com/containers/podman/blame/2c7b39ddb8961bf547a36420407adb461dd4c227/docs/source/index.rst#L9
This says:

> The Podman service runs only on Linux platforms, however a REST API and clients are currently under development which will allow Mac and Windows platforms to call the service. There is currently a RESTful based remote client which runs on Mac or Windows platforms that allows the remote client to talk to the Podman server on a Linux platform. In addition to those clients, there is also a Mac client.

So feel my understanding, it's saying:

1. A REST API is under development
2. There is a RESTful based remote client for Mac and Windows
3. There is a Mac client

So it sounds like 1 and 2 are contradictory (or at least confusing; "under development" suggests to me that it's not yet available, but 2 suggests it is?), And it appears to mention the existence of a Mac client *twice* in both 2 and 3.

Perhaps some rewording is in order?

I'd have sent a PR but I'm not sure what is most correct and therefore how to reword.

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

/kind feature

**Description**

**Steps to reproduce the issue:**

1.

2.

3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by baude** [comment]
@mattcen please consider the PR #9106 and if it is clearer, add a comment to the pr.
