### ISSUE TITLE
Podman 2.2.1 localhost image pulls fail with connection refused on Ubuntu

### ISSUE THREAD

**Issue by smijolovic** [containers/podman#9111]
Podman version: 2.2.1

Built a debian image (debootstrap) and added it to the local system repo:

$ podman images
REPOSITORY               TAG          IMAGE ID      CREATED         SIZE
localhost/chaasm/debian  buster-slim  9293f2fa2849  10 minutes ago  75.3 MB

When attempting to use that image as the baseimage for the following command:
docker build --pull -t $(BUILD_IMAGE) -f $(TEMP_DIR)/$(CONFIG)/Dockerfile.build $(TEMP_DIR)/$(CONFIG) --log-level=debug

DEBU[0000] base: "localhost/chaasm/debian:buster-slim"  
DEBU[0000] FROM "localhost/chaasm/debian:buster-slim"   
STEP 1: FROM localhost/chaasm/debian:buster-slim
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf" 
DEBU[0000] parsed reference into "[overlay@/home/chaasmadmin/.local/share/containers/storage+/run/user/5000/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]@9293f2fa2849ee4cc875d09e7e5fbf7c46ec308456c5a0c54d0d2ce63d8555ed" 
DEBU[0000] registry "localhost" is not listed in registries configuration "/etc/containers/registries.conf", assuming it's not blocked 
DEBU[0000] parsed reference into "[overlay@/home/chaasmadmin/.local/share/containers/storage+/run/user/5000/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]localhost/chaasm/debian:buster-slim" 
DEBU[0000] parsed reference into "[overlay@/home/chaasmadmin/.local/share/containers/storage+/run/user/5000/containers:overlay.mount_program=/usr/bin/fuse-overlayfs]localhost/chaasm/debian:buster-slim" 
DEBU[0000] copying "docker://localhost/chaasm/debian:buster-slim" to "localhost/chaasm/debian:buster-slim" 
DEBU[0000] Trying to access "localhost/chaasm/debian:buster-slim" 
DEBU[0000] Credentials not found                        
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]  No signature storage configuration found for localhost/chaasm/debian:buster-slim, using built-in default file:///home/chaasmadmin/.local/share/containers/sigstore 
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/localhost 
DEBU[0000] GET https://localhost/v2/                    
DEBU[0000] Ping https://localhost/v2/ err Get "https://localhost/v2/": dial tcp 127.0.0.1:443: connect: connection refused (&url.Error{Op:"Get", URL:"https://localhost/v2/", Err:(*net.OpError)(0xc00014a500)}) 
DEBU[0000] GET https://localhost/v1/_ping               
DEBU[0000] Ping https://localhost/v1/_ping err Get "https://localhost/v1/_ping": dial tcp 127.0.0.1:443: connect: connection refused (&url.Error{Op:"Get", URL:"https://localhost/v1/_ping", Err:(*net.OpError)(0xc00014a690)}) 
DEBU[0000] Accessing "localhost/chaasm/debian:buster-slim" failed: error pinging docker registry localhost: Get "https://localhost/v2/": dial tcp 127.0.0.1:443: connect: connection refused 
DEBU[0000] error copying src image ["docker://localhost/chaasm/debian:buster-slim"] to dest image ["localhost/chaasm/debian:buster-slim"] err: Error initializing source docker://localhost/chaasm/debian:buster-slim: error pinging docker registry localhost: Get "https://localhost/v2/": dial tcp 127.0.0.1:443: connect: connection refused 
DEBU[0000] error pulling image "docker://localhost/chaasm/debian:buster-slim": Error initializing source docker://localhost/chaasm/debian:buster-slim: error pinging docker registry localhost: Get "https://localhost/v2/": dial tcp 127.0.0.1:443: connect: connection refused 
DEBU[0000] unable to pull and read image "localhost/chaasm/debian:buster-slim": Error initializing source docker://localhost/chaasm/debian:buster-slim: error pinging docker registry localhost: Get "https://localhost/v2/": dial tcp 127.0.0.1:443: connect: connection refused 
Error: error creating build container: Error initializing source docker://localhost/chaasm/debian:buster-slim: error pinging docker registry localhost: Get "https://localhost/v2/": dial tcp 127.0.0.1:443: connect: connection refused
make: *** [Makefile:80: build] Error 125

This works on Centos 8 with podman 2.1.1...so I'm confused about why it's going to a remote registry to obtain a locally cached image.

$ podman info
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon-chaasm: /usr/bin/conmon'
    path: /usr/bin/conmon
    version: 'conmon version 2.0.22, commit: 9c34a8663b85e479e0c083801e89a2b2835228ed'
  cpus: 4
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: chaasm-build-test
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 5000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 5000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.4.0-62-generic
  linkmode: dynamic
  memFree: 544108544
  memTotal: 8335331328
  ociRuntime:
    name: runc
    package: 'runc-chaasm: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: |-
      runc version 1.0.0-rc92
      commit: ff819c7e9184c13b7c2607fe6c30ae19403a7aff-dirty
      spec: 1.0.2-dev
  os: linux
  remoteSocket:
    path: /run/user/5000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 0.4.3
      commit: 2244b9b6461afeccad1678fac3d6e478c28b4ad6
  swapFree: 4294426624
  swapTotal: 4294963200
  uptime: 17h 23m 47.28s (Approximately 0.71 days)
registries:
  search:
  - docker.io
  - quay.io
  - registry.fedoraproject.org
store:
  configFile: /home/chaasmadmin/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.9.0
        fuse-overlayfs: version 0.7.6
        FUSE library version 3.9.0
        using FUSE kernel interface version 7.31
  graphRoot: /home/chaasmadmin/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/user/5000/containers
  volumePath: /home/chaasmadmin/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1609357106
  BuiltTime: Wed Dec 30 19:38:26 2020
  GitCommit: a0d478edea7f775b7ce32f8eb1a01e75374486cb-dirty
  GoVersion: go1.15.6
  OsArch: linux/amd64
  Version: 2.2.1

**Comment by mheon** [comment]
@baude @vrothberg Is this potentially our `localhost/` prefix not being respected by Buildah?

**Comment by baude** [comment]
Im not sure, i think i saw this on irc and @vrothberg was going to peek at it.

**Comment by vrothberg** [comment]
@baude and I had a look. It seems like the behaviour of `--pull` was wrong. Opened https://github.com/containers/podman/pull/9127 to fix.
