### ISSUE TITLE
podman build --pull differs from docker build --pull

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman#9134]
The change made in th #9127 caused `podman build --pull` to not match `docker build --pull`.  With this change podman does a `PullIfNewer`.  This pulls the image if a newer variant is found on the registry or if there is not a local image.  An error is raised when there's no local image after the pull is completed; either due to the pull or because it was there prior.

Docker and the original functionality does a `PullAlways`.  This always attempts to pull the image from the registry.  If the image can not be pulled, then an error is raised even if there is a local image.

As @vrothberg pointed out in #9127, Buildah is doing a `PullIfNewer` and always has, but we've always said that Podman will line up with Docker for functionality.

If we decide to go to #9127, then the man page needs to change as currently it descibes the `PullAlways` functionality.

**Comment by TomSweeneyRedHat** [comment]
@vrothberg @rhatdan @mheon @umohnani8 @baude 
Let's talk through this tomorrow at end of demo please.

**Comment by TomSweeneyRedHat** [comment]
I forgot to include, here's the change from back in November: #8210

**Comment by vrothberg** [comment]
Thanks, Tom!  You are right.

If we revert to `PullAlways`, we need to find a solution to fix the `podman build --help` message which is explaining the `PullIfNewer` semantics.
