### ISSUE TITLE
Podman --expose doesn't expose the port

### ISSUE THREAD

**Issue by Andreyooo** [containers/podman#9145]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I installed podman on my Raspberry Pi 3 (Raspbian GNU/Linux 10 (buster) & ARMv7 Processor rev 4 (v7l)) following these instructions https://github.com/containers/podman/issues/7508#issuecomment-762536260.
Now I try to run the default mosquitto container image using: ```sudo podman run -d --expose=1883 c83ed7264442```

The container starts but Port 1883 is not exposed. Following [these ](https://access.redhat.com/discussions/4830451) debug instructions I checked .NetworkSettings.Ports & .HostConfig.PortBindings and both are empty.
I tried `echo br_netfilter > /etc/modules-load.d/podman.conf`, but it didn't fix it.

**Steps to reproduce the issue:**

1. Install podman on Raspberry Pi

2. Pull the official eclipse-mosquitto image

3. Run the image with port exposed to 1883

**Describe the results you received:**
Container runs with port 1883 not exposed.

**Describe the results you expected:**
Container runs with port 1883 exposed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/arm
```

**Output of `podman info --debug`:**

```
host:
  arch: arm
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.22, commit: '
  cpus: 4
  distribution:
    distribution: raspbian
    version: "10"
  eventLogger: journald
  hostname: raspberrypi
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.4.83-v7+
  linkmode: dynamic
  memFree: 497471488
  memTotal: 969768960
  ociRuntime:
    name: runc
    package: 'cri-o-runc: /usr/lib/cri-o-runc/sbin/runc'
    path: /usr/lib/cri-o-runc/sbin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.3.3
  swapFree: 104853504
  swapTotal: 104853504
  uptime: 1h 31m 42s (Approximately 0.04 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/pi/.config/containers/storage.conf
  containerStore:
    number: 25
    paused: 0
    running: 0
    stopped: 25
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/pi/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 9
  runRoot: /run/user/1000/containers
  volumePath: /home/pi/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/arm
  Version: 2.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 2.2.1~4 armhf  [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
I think you're confusing `--expose` and `--publish` (`-p`). Expose tells Podman that the container requests that port be open, *but does not forward it*. All exposed ports will be forwarded to random ports on the host if and only if `--publish-all` is also specified.
Meanwhile, the `--publish` flag tells Podman to publish the port to the host - no `--publish-all` required. Most people in my experience just use `-p` and ignore `--expose` unless they are building an image.

**Comment by Andreyooo** [comment]
Whoops, thank you for pointing that out 😄. `sudo podman run -d -p=1883 c83ed7264442` works.
