### ISSUE TITLE
rootless podman password exposed via systemctl status for podman user service creation

### ISSUE THREAD

**Issue by cjpit** [containers/podman#9153]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I've just set up a rootless podman instance, and created the systemd files.  The container itself users environment variables to set database passwords etc.  When doing a systemctl status from another user, the password can be seen. I'm not exactly sure this is a podman issue or not, but thought i would log it anyway

systemd unit files created using
```podman generate systemd --files```

Below is a screenshot from another user on the system running a systemctl status
![Screenshot from 2021-01-29 12-12-29](https://user-images.githubusercontent.com/3469512/106231084-d022f600-622b-11eb-93ab-d0d9aa07e876.png)

**Output of `podman version`:**

```
podman version 2.2.1
```

**Comment by mheon** [comment]
That doesn't look like an env variable - it's getting passed straight into the Python command being run in the container. I'm pretty sure it would be plainly visible in plain `ps` as well?

Regardless, this looks like more of an issue with the image than Podman.

**Comment by cjpit** [comment]
Yeah right, thanks for pointing me in the right direction!
