### ISSUE TITLE
Add ability to store all image logs in a single directory /var/log/containers.

### ISSUE THREAD

**Issue by rhatdan** [containers/podman#9158]
Currently container logs are being stored under /var/lib/container/storage in container specific directories.  These logs can grow quite large, and become difficult for admins to manage.  Moving them into /var/log/containers by default or at least allowing admin to specify the location to store the logs, would make it easier for container management.
From an SELinux point of view it would also allow us to label the content differently then the standard container label.

https://bugzilla.redhat.com/show_bug.cgi?id=1900997

Has requested this feature.  I think this should first be generated in containers.conf LogPath. Once specified newly created containers logs should point at /var/log/cotainers/$CID.log, or whatever path is specified. 

The question would be whether or not this should be the default.

**Comment by vrothberg** [comment]
Sounds like a great improvement to me.  Setting an upper limit to _all_ logs is a nice experience (containers.conf may come in handy).  We can symlink the old destination to the new, central, one.

**Comment by mheon** [comment]
The eternal problem: how do we handle rootless? Root Podman should be defaulting to journald already, I think - so it's much less of a problem.

**Comment by rhatdan** [comment]
I don;t see us defaulting to journald 

```
# podman create alpine ls
6d76cf5d98c700c52fe023455a8d8b2e5f048a07a5c2d23db7fd695f775474b7
# podman inspect -l  --format '{{ .HostConfig.LogConfig }}'
{k8s-file map[] /var/lib/containers/storage/overlay-containers/6d76cf5d98c700c52fe023455a8d8b2e5f048a07a5c2d23db7fd695f775474b7/userdata/ctr.log  0B}
```

**Comment by rhatdan** [comment]
journald will work fine for rootless also.  We should change the default.  For now we can easily do this in containers.conf, but perhaps we should change the default in conainers/common for 3.0, since we can do breaking changes, not sure if this is covered.

**Comment by mheon** [comment]
Journald is a lot less fine for rootless - as we discovered on RHEL, non
rot users may not have access depending on system configuration.

**Comment by rhatdan** [comment]
We can chnage the upstream to journald, and have RHEL ship a containers.conf setting its defaults to k8s_file.
