### ISSUE TITLE
podman on arm: `Error: failed to open 2048 locks in /libpod_lock: numerical result out of range`

### ISSUE THREAD

**Issue by srcshelton** [containers/podman#9164]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Another one for edge-cases-no-sane-person-is-ever-likely-to-encounter: `arm` userland but running on a 64bit kernel executing an `arm64` binary (with appropriate libraries available in `/lib64`/`/usr/lib64`):

Any podman command (`podman image ls`, `podman ps`, even `podman info`) results in:

```
Error: failed to open 2048 locks in /libpod_lock: numerical result out of range
```

This doesn't occur when running a 32bit binary - so I'm adding this more as a note of curious behaviour than anything else.  Note, however, that the 32bit binary is current unusable due to https://github.com/containers/crun/issues/575, and `runc` reporting `container exited on bad system call` :(

**Output of `podman version`:**

```
Error: failed to open 2048 locks in /libpod_lock: numerical result out of range
```

**Output of `podman info --debug`:**

```
Error: failed to open 2048 locks in /libpod_lock: numerical result out of range
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Comment by mheon** [comment]
Are you, by chance, swapping between 32 and 64 bit binaries on this system?
If so, you may want to try ‘podman system renumber’. I think all the locks
code uses fixed size integers, but maybe an int snuck in somewhere and it’s
confusing the matter.

**Comment by srcshelton** [comment]
You could be onto something there, but sadly with a 64bit binary:

```
$ sudo podman system renumber
Error: failed to open 2048 locks in /libpod_lock: numerical result out of range
```

... what can I delete on-disk to remove whatever locks need re-numbering?

Also, could `podman` not detect this particular error and automatically run a `system renumber` and try the operation again?

(... and, if it is the right response, could `system renumber` be made not to abort if a system renumber is required?! ;)

**Comment by mheon** [comment]
The locks file is in `/dev/shm` - if you have no Podman processes running (OK to have containers running, as long as you're not attached to them) then it's safe to remove anything in `/dev/shm` with a name starting with `libpod`.

`system renumber` is a somewhat involved operation under the hood (can potentially do bad things if other Podman processes are running at the same time) so we can't really automate it safely.

**Comment by srcshelton** [comment]
Perfect!  I'd cleared the entries under `(/var)/run` and even the storage directory, but didn't think to check `/dev/shm`... and with `/dev/shm/libpod_lock` removed, it looks as if things are working again!

**Comment by rhatdan** [comment]
So this is not an issue, for us to fix, I am closing.  If I am mistaken please reopen.

**Comment by srcshelton** [comment]
> So this is not an issue, for us to fix, I am closing. If I am mistaken please reopen.

Not worth re-opening this issue for, but perhaps a clearer error message which at least mentions `podman system renumber` might give any user hitting this a clearer indication of how to solve the problem?

**Comment by therevoman** [comment]
Just experienced this with Fedora 36 after getting the latest podman.  FWIW, podman system renumber doesn't remove the file in /dev/shm and so I couldn't fix the issue until I found this thread.
