### ISSUE TITLE
Podman 3.0 on Fedora33 WSL Image after 1st 24h of testing - repositories.conf content

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/podman#9166]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Installed .... /containers/registries.conf file contains redundant entry for unqualified-search-registries = [ "registry.access.redhat.com", "registry.centos.org", "docker.io"] ... "registry.fedora.org"

**Steps to reproduce the issue:**

1. Install or Upgrade Podman 3.0 on Fedora 33 or Fedora 33 VM image
2. Podman run .. nodejs
The list 

**Describe the results you received:**
List of proposed registries contains redundant entries
**Describe the results you expected:**
List of registries that really may contain the image.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
podman version
Version:      3.0.0-rc1
```

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.2
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.21-3.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 0f53fb68333bdead5fe4dc5175703e22cf9882ab'
  cpus: 4
  distribution:
    distribution: fedora
    version: "33"

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.0.0-0.1.rc1.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Works OK after manual removal of non-existing image registries from the registry.conf file.

**Comment by vrothberg** [comment]
Thanks for reaching out!  @PavelSosin-320, could you elaborate a bit more on the problem?

Are you referring to the prompt where you have to choose and image to pull?  Podman lists intentionally uses all unqualified-search registries in the registries.conf.  Figuring out if an image exists on one of the listed registries is not something we wanted to do. The reasons are manifold. A limited bandwidth would noticably slow it down but transient network errors or missing credentials may entirely hide the existence of an image.

**Comment by PavelSosin-320** [comment]
After installation of Podman 3.0 I got registries.conf installed and containing unqualified-search-registries with the broad list of DNS registry names. Some of them are not OCI image registries like CentOS and Fedora registries and have no suitable transport. Occasionally it interferes with the bug in Microsoft WSL's DNS resolution and My ISP's DNS malfunction. Instead of a clear choice between Docker's registry and RedHat Access registry I got a choice between 2 registries, Docker's registry, and RedHat Access registry I got 5 options and a bunch of Error messages. I expect the feature of OCI image search by parameters from Skopeo and single hit resolution without user interaction from Podman. This is also a security issue because some customers restrict the usage of public registries completely. ( Ask Eclipse/Che team about the request from SAP WebEDI team)

**Comment by vrothberg** [comment]
Thanks for elaborating!

What do you mean by "OCI image search"?

Skopeo and Docker always resolve to `docker.io` which Podman never did.  If a user wishes to not interact, they need to either specify a fully-qualified image reference (e.g., docker.io/library/alpine vs alpine) or configure the registries.conf. There's a blog post from last year going into the details: https://www.redhat.com/sysadmin/container-image-short-names

**Comment by PavelSosin-320** [comment]
The problems for me were 1. I expected the "best hit" from the security and reliability marked or selected by the default. 2. Why I see the entry "registry.centos.org" when I work in Fedora?  Then I see "can't resolve errors and 
ping registry.centos.org
PING registry.centos.org (35.180.173.132) 56(84) bytes of data.
From ec2-35-180-173-132.eu-west-3.compute.amazonaws.com (35.180.173.132) icmp_seq=1 Destination Host Prohibited. Is it an image registry at all?
Due to mentioned above bugs, registry.centos.org is resolved for me as Akamay CDN!
I think that the initial list must contain registry.access.redhat.com and docker.io only.

**Comment by vrothberg** [comment]
Did you read https://www.redhat.com/sysadmin/container-image-short-names?  Your security concerns should be addressed by it.

Changing the default list of unqualified-serach-registries is up the distributions to decide. Fedora, for instance, ships a different list than Debian or openSUSE.

**Comment by PavelSosin-320** [comment]
@vrothberg I thik the reason is
ls /usr/share/containers/
containers.conf  mounts.conf  seccomp.json  selinux
The blank repositories.conf is missed.

**Comment by vrothberg** [comment]
The registries.conf is in _/etc/containers/registries.conf_.

**Comment by PavelSosin-320** [comment]
/etc/containers/registries.conf contains 
unqualified-search-registries = [ "registry.access.redhat.com", "registry.centos.org", "docker.io"]
in the Fedora package and it is not commented.
I suppose it is used by the root. When I copy it to the $HOME it gives me centos again.
When I cleaned up the registries.conf from the junk entries and copied them to my $HOME it started to work.

**Comment by vrothberg** [comment]
I still don't understand the request, @PavelSosin-320.

**Comment by PavelSosin-320** [comment]
After installation on Fedora33 VM the file registries.conf contains the list of registries with a redundant entry for "CentOS7 image registry". Then this registry appears in the registries proposals dropdown if the user providers partially qualified image name. It's impossible to pull something from this "registry",  login to it, or even resolve its DNS name -  Podman pull prints several technical error messages. I had to solve these "errors" one-by-one. I suppose it's better to provide a minimal and reliable list of registries in the default configuration and commented example on how to expand it instead of such a list containing non-existing registry entries.

**Comment by vrothberg** [comment]
Thanks, @PavelSosin-320!

> After installation on Fedora33 VM the file registries.conf contains the list of registries with a redundant entry for "CentOS7 image registry". 

I don't think it's redundant since if you pull `centos`, the CentOS registry will be used and the image gets pulled from `registry.centos.org/centos:latest`.

> Then this registry appears in the registries proposals dropdown if the user providers partially qualified image name. It's impossible to pull something from this "registry", login to it, or even resolve its DNS name - Podman pull prints several technical error messages. 

Could it be network issue in your environment?  This registries.conf configuration is used on millions of machines but it's not involved in DNS.

> I had to solve these "errors" one-by-one. I suppose it's better to provide a minimal and reliable list of registries in the default configuration and commented example on how to expand it instead of such a list containing non-existing registry entries.

I think there is a network issue on your VM.  The `unqualified-search-registries` list is the default on Fedora and many other distributions and all listed registries exist and work.

**Comment by PavelSosin-320** [comment]
Yes, I know This is 1. The issue of my ISP's DNS that is obviously doesn't work as DynDNS must work. I need some tricks to bypass it and use Quad9. 2. This is a Windows WSL bug: MS blindly believes that Windows runs on the Desktop staying on the desk and connected to the wall via modem and every user uses the single infrastructure and served by a single ISP  providing single available DNS. The idea of the partially specified image name contradicts the idea of "Image transport". Docker provides one default Registry using one protocol. everything else is an extended list.  Everything that is non-default must be commented out in the default configuration. I run Podman on Fedora VM. I didn't pull CentOS image.  It is not my default.

**Comment by vrothberg** [comment]
I think there is nothing we can do in this case. Users are free to change the default list to whatever suits them.  Changing it to only default to docker.io would break millions of users who rely on the configured `unqualified-search-registries`.

The main intention is to provide flexibility and prevent vendor lock in.  Only using Docker Hub is understandable for Docker but it is not very friendly to users who want other defaults.

 That being said, I don't think Fedora can change that list.

**Comment by rhatdan** [comment]
Correct it is up to each distribution to choose the list.  Fedora will stick to it's list.

I don't see this as a Podman issue.  If Fedora or Ubuntu get full support on WSL, then the shipped Podman should work.  If users install there own Podman from scratch or third party sites, it is there responsibility to get it all installed correctly.

Closing as I don't see this as Podmans issue.  Reopen if I am mistaken.
