### ISSUE TITLE
podman play kube support for configMap volumeSource

### ISSUE THREAD

**Issue by gcs278** [containers/podman#9181]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Hello,

With podman v2.2.1, we are able to do  `podman play kube ... --configmap` and add configmaps. The current supported usage of config-maps in YAML is with `spec.containers[].envFrom.configMapRef`.

Is there a plan to support `spec.volumes.configMap` with `podman play kube`?

**Steps to reproduce the issue:**

1. Create pod.yaml with `spec.volumes.configMap` and a configmap.yaml wit a valid configmap

2. podman play kube pod.yaml --configmap configmap.yaml

**Describe the results you received:**
I believe you get something like: `HostPath is currently the only supported VolumeSource`

**Describe the results you expected:**
Support for `spec.volumes.configMap`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.2
Built:        Thu Dec 17 11:10:45 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.21-3.module_el8.4.0+581+8bd31022.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 4cff974a37907e701aa2e31ad480ccc6f3f586f5'
  cpus: 10
  distribution:
    distribution: '"rhel"'
    version: "8.2"
  eventLogger: file
  hostname: rhel82
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-193.el8.x86_64
  linkmode: dynamic
  memFree: 387756032
  memTotal: 3884625920
  ociRuntime:
    name: runc
    package: runc-1.0.0-65.rc10.module+el8.2.0+5762+aaee29fb.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4001624064
  swapTotal: 4190105600
  uptime: 1655h 43m 24.55s (Approximately 68.96 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 4
    paused: 0
    running: 2
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 16
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1608221445
  BuiltTime: Thu Dec 17 11:10:45 2020
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.2.1-2.module_el8.4.0+581+8bd31022.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
N/A

**Comment by rhatdan** [comment]
Interested in opening a PR to add this functionality?

**Comment by xordspar0** [comment]
I'm working on this.

**Comment by hoonetorg** [comment]
Any news on that? Especially asking @xordspar0.

**Comment by hoonetorg** [comment]
@xordspar0: I've seen you created the branch https://github.com/xordspar0/podman/tree/configMapVolumes, but you didn't push any commits yet, right?

**Comment by xordspar0** [comment]
Thanks for your interest. I am still working on it in my free time. I have a pile of unfinished changes on my laptop. I may as well commit and push them. I'm not sure if I'm going in the right direction yet. The main thing I haven't figured out yet is where to store the data that will be mounted as a volume.

There, it's rebased and pushed: https://github.com/xordspar0/podman/tree/configMapVolumes

**Comment by hoonetorg** [comment]
Thank you @xordspar0. In your comment you say it's not working yet. I looked at the commit and can imagine what you do, but I am far away from understanding and being able to help or finish that work. 
Will you have time to finish that work or maybe someone else can assist/finish that work?

One question:
In pkg/domain/infra/abi/play.go line 228-238 you implement registryCreds an dockerRegistryOptions. This has nothing to do with configMapVolumes, has it? :o)

**Comment by rhatdan** [comment]
@xordspar0 Any progress on this?

**Comment by xordspar0** [comment]
No; I had very limited Internet access in the last few weeks. Unfortunately the tests require an Internet connection to work. I'm re-connected now though. I'm planning to resume work tomorrow.

**Comment by rhatdan** [comment]
@xordspar0 Any progress?

**Comment by xordspar0** [comment]
Yes, I have been making slow progress in [my branch](https://github.com/xordspar0/podman/tree/configMapVolumes), but it's not done yet.

**Comment by MartinX3** [comment]
@rhatdan please remove the stale status. :)

**Comment by MartinX3** [comment]
@rhatdan please remove the stale status. :)

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by umohnani8** [comment]
@xordspar0 are you still working on this? If not, I can take over

**Comment by xordspar0** [comment]
I got stuck a while back. Feel free to take a look at my branch and do something different. :slightly_smiling_face: I'll keep checking in here as well, so I can take over eventually if it doesn't get done.

**Comment by xordspar0** [comment]
Woo, nice work @umohnani8! :tada: I look forward to seeing this in the next release!
