### ISSUE TITLE
FIPS mode secret always mounted on Fips enabled hosts - optional?

### ISSUE THREAD

**Issue by disposab1e** [containers/podman#9193]
/kind feature

**Description**

When running a container with a Fips aware OS (e.g. RHEL 7/8) on a Fips enabled host (e.g. RHEL 8.3) podman mounts a FIPS mode secret at `/etc/system-fips` and creates a symlink to `/run/secrets/system-fips`.

In many cases this is a prefect behavior!

But in some cases.. when the process (software) is not prepared to handle Fips this leads to trouble.

Concrete Example:

- RHEL 8.3 (Fips mode enabled)
- Podman: 2.0.5
- Container: RH Quay v3.3.4 with RHEL 7.9 

Quay crashes cause some python scripts use md5. 

I found no way to tell podman NOT to mount the FIPS mode secret into the container. 

**Describe the results you received:**

Podman always mounts FIPS mode secret on a fips enabled host.

**Describe the results you expected:**

Podman option to ignore Fips and not mounting FIPS mode secret on a fips enabled host.

**Additional information you deem important (e.g. issue happens only occasionally):**

Running Quay with podman via systemd. 

**Output of `podman version`:**

```
Version:      2.0.5
API Version:  1
Go Version:   go1.14.7
Built:        Wed Sep 23 18:18:02 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.1
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.20-2.module+el8.3.0+8221+97165c3f.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.20, commit: 77ce9fd1e61ea89bd6cdc621b07446dd9e80e5b6'
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "8.3"
  eventLogger: file
  hostname: repository.example.com
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-240.10.1.el8_3.x86_64
  linkmode: dynamic
  memFree: 5256990720
  memTotal: 14312976384
  ociRuntime:
    name: runc
    package: runc-1.0.0-68.rc92.module+el8.3.0+8221+97165c3f.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 7226781696
  swapTotal: 7226781696
  uptime: 14m 49.17s
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 8
    paused: 0
    running: 7
    stopped: 1
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 15
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1600877882
  BuiltTime: Wed Sep 23 18:18:02 2020
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.0.5
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.5-5.module+el8.3.0+8221+97165c3f.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No/Yes

**Comment by rhatdan** [comment]
You should not run non fips mode software on a fips mode enabled system. That is the basic idea of fips mode.  If you are breaking the rules then you are not fips mode.

**Comment by disposab1e** [comment]
@rhatdan  I didn't want to be taught. I had a specific question.

**Comment by disposab1e** [comment]
Podman only checks for /etc/system-fips on the Host file system to decide is a container running on a fips enabled host. If you rename /etc/system-fips before starting the container, no symlink /run/secrets/system-fips is created and from now the container believes it's not on a fips host. 

I wander cause.... 
```
bash-4.2$ cat /proc/sys/crypto/fips_enabled
1
bash-4.2$ sysctl crypto.fips_enabled
crypto.fips_enabled = 1
```
...is still showing fips is enabled.

@rhatdan It's so easy to break the rules... so in my opinion disabling Fips in podman can be a run option too :-) 

Now I ask myself... is checking only for /etc/system-fips a secure way?

**Comment by rhatdan** [comment]
Yup,  I guess we could add a --security-opt fips=disable or something like that if you are interested in opening a PR.  :^)

**Comment by rhatdan** [comment]
I have been told that openssl library will only work in fips mode if both the /proc/sys/crypto/fips_enabled is trueand the /etc/system-fips file exists.  When the /etc/system-fips file exists on the host then we create /run/secrets/system-fips so the containers settings match the hosts.  Then if the machine is in fips mode, the openssl will follow the rules.

**Comment by rhatdan** [comment]
Since we have had no futher response, I am closing this issue.
