### ISSUE TITLE
latest packages copr repo

### ISSUE THREAD

**Issue by tmds** [containers/podman#9199]
https://copr.fedorainfracloud.org/coprs/baude/Upstream_CRIO_Family/builds/ is mentioned as a source for latest packages on https://podman.io/getting-started/installation.

There aren't many recent builds, so maybe part of the CI/CD is broken?

cc @baude

**Comment by mheon** [comment]
@baude PTAL

**Comment by baude** [comment]
not sure whats going on there ... everything looks ok, i edited the settings and re-saved to see if the autobuilds start working again.

**Comment by rhatdan** [comment]
Did this work?

**Comment by baude** [comment]
working now, builds are flowing.

**Comment by tmds** [comment]
great, thanks!
