### ISSUE TITLE
podman build  error creating new mount namespace

### ISSUE THREAD

**Issue by tbongiovani** [containers/podman#9222]
**Is this a BUG REPORT**

/kind bug

operation not permitted from create directory 

**Description**

**Steps to reproduce the issue:**

1.
root@32e35d5a8172:/azp# podman build   .
STEP 1: FROM ubuntu:20.10
STEP 2: USER 0
--> Using cache 8659dca2a86dd325d3033f5d58860e7731b8c0a8781fb9d98c8bcb6660f67c81
STEP 3: RUN mkdir app
error running container: error creating new mount namespace for [/bin/sh -c mkdir app]: operation not permitted
Error: error building at STEP "RUN mkdir app": error while running runtime: exit status 1

root@32e35d5a8172:/azp# cat Dockerfile
FROM ubuntu:20.10
USER 0
RUN mkdir app

**Describe the results you received:**

error running container: error creating new mount namespace for [/bin/sh -c mkdir app]: operation not permitted
Error: error building at STEP "RUN mkdir app": error while running runtime: exit status 1

**Describe the results you expected:**

build image

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

podman version 2.0.6

**Output of `podman info --debug`:**

root@32e35d5a8172:/azp# podman info --debug
host:
  arch: amd64
  buildahVersion: 1.15.2
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.20, commit: unknown'
  cpus: 8
  distribution:
    distribution: ubuntu
    version: "20.10"
  eventLogger: file
  hostname: 32e35d5a8172
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.19.128-microsoft-standard
  linkmode: dynamic
  memFree: 369684480
  memTotal: 13072969728
  ociRuntime:
    name: runc
    package: 'runc: /usr/sbin/runc'
    path: /usr/sbin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4294430720
  swapTotal: 4294967296
  uptime: 25h 1m 55.34s (Approximately 1.04 days)
registries:
  search:
  - quay.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus: {}
  imageStore:
    number: 2
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 1
  Built: 0
  BuiltTime: Thu Jan  1 00:00:00 1970
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.0.6

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

root@32e35d5a8172:/azp# apt list podman
Listing... Done
podman/groovy,now 2.0.6+dfsg1-1ubuntu1 amd64 [installed]

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Run docker in docker

**Comment by mheon** [comment]
Can you provide additional details on "Run docker in docker" - is Podman being run inside a container? If so, please provide more details on the outer container.

**Comment by mheon** [comment]
@nalind @TomSweeneyRedHat PTAL

**Comment by rhatdan** [comment]
You can only run podman within a privileged docker container at this time.

**Comment by rhatdan** [comment]
We have multiple podman in container issues open, lets keep discussion in one place. #9015

**Comment by barfurth** [comment]
Has there been any progress on this? Our shared Gitlab CI runner does not allow us to set privileged mode and we're getting this exact error for a `build`.

```
error running container: error creating new mount namespace for [/bin/sh -c whoami]: operation not permitted
```

**Comment by nalind** [comment]
#10079 may have solved this; the owner of a user namespace should have the ability to create a new mount namespace.  If the `unshare` syscall is blocked, though, or the host system doesn't allow user namespaces to be created (i.e., if the `user.max_user_namespaces` sysctl setting is 0), we're kind of stuck.

**Comment by barfurth** [comment]
Not sure we can do anything about user namespaces in a CI environment to be honest. Seems like we’re stuck.

**Comment by barfurth** [comment]
@nalind it seems user namespaces configuration is not relevant. A clean Ubuntu Docker container won't run a `podman build` with `RUN` commands unless it gets privileged. Ubuntu usually has namespaces enabled by default.

In cases where the Docker context can't be modified (shared CI environments for example) it appears Podman cannot replace Docker yet.
