### ISSUE TITLE
We need to get logs testing to pass with journald driver.

### ISSUE THREAD

**Issue by rhatdan** [containers/podman#9249]
We attempted to switch default to journald, but tests were blowing up.

We need to fix these and to double the logging tests to run on both k8s_file and journald.

**Comment by rhatdan** [comment]
@ashley-cui Once you get your secrets merged, I would like you to work on this, so we can change the default to journald.

**Comment by ashley-cui** [comment]
closed via https://github.com/containers/podman/pull/9417
