### ISSUE TITLE
Expose `--dependency` for `podman run`

### ISSUE THREAD

**Issue by xcffl** [containers/podman#9250]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

There's already a field in the container metadata (`podman inspect xxx`) called `Dependencies`, which could perfectly solve the problem of container dependency (e.g. apps should be run after the database). But there's no such way to add dependency when create the container. The only place it's used now is for the pod `pause` container.

**Steps to reproduce the issue:**

1. `podman run --dep postgres alpine:latest`

**Describe the results you received:**

No such a parameter

**Describe the results you expected:**

There is such a parameter

**Comment by mheon** [comment]
I'll self-assign this one.

**Comment by vrothberg** [comment]
@mheon, can you add a check for the `PODMAN_SYSTEMD_UNIT` and throw a warning in case it's set?

A Podman-side dependency management can conflict with a systemd-side one (starting sequence, potential dead locks, etc). I think users should chose between the two but not mix.

**Comment by xcffl** [comment]
> I think users should chose between the two but not mix.

That's tricky. The `podman generate systemd` depends on the podman-side dependency.

**Comment by vrothberg** [comment]
I don't think it's tricky (I wrote most of generate systemd). The dependencies are taken into account and are especially important for pods but I don't think we should mix podman-side and systemd-side dependency management.

If users wish to do that, we should allow it but a warning may spare some from a longer debugging journey.

**Comment by xcffl** [comment]
> The dependencies are taken into account and are especially important for pods but I don't think we should mix podman-side and systemd-side dependency management.

Sure. Just want to make sure it doesn't break generate systemd

**Comment by mheon** [comment]
@vrothberg Sure
