### ISSUE TITLE
Podman 3.0.0-rc2 --iidfile Output is Incomptable with docker-compose

### ISSUE THREAD

**Issue by lachlan2k** [containers/podman#9260]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

From my understanding, one of the goals of Podman 3 is to [provide docker-compose compatibility.](https://www.redhat.com/sysadmin/podman-docker-compose) However, Podman's `--iidfile` output is not in the format docker-compose expects, and will cause `docker-compose build` to fail.

For context, Docker's `--iidfile` format is `<hashtype>:<hash>` and looks like this:
`sha256:0873da882a9bf444a7595643212dabebadf975fa312e2f0b94e889dff2bf0a0e` -- this is the format docker-compose expects.

On the other hand, Podman's output does not contain `<hashtype>:` and just contains the hash, e.g.: `0873da882a9bf444a7595643212dabebadf975fa312e2f0b94e889dff2bf0a0e`.

When docker-compose attempts to parse this [here](https://github.com/docker/compose/blob/bba8cd0322343750ae8f4aacdc46e9390a117089/compose/service.py#L1896), it crashes because the `:` separator is not present.

**Steps to reproduce the issue:**

With Podman@3.0.0-rc2, docker-compose, and podman-docker installed:
Use the following `docker-compose.yml`:
```
version: '3.8'
services:
  hello_world:
    build:
      context: .
      dockerfile: Dockerfile
```

And the following `Dockerfile`:
```
FROM alpine
CMD ["echo", "Hello, world!"]
```

Run `docker-compose build` to get the error.

**Describe the results you received:**

ID file format from Podman, and error when using Podman with docker-compose:
```
$ podman build . --iidfile=id.txt
...
$ cat id.txt
922945d6ac32ed9de4f328073c55d929e45a2354eb848c0d574acb1419018183

$ docker-compose build
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Building hello_world
STEP 1: FROM alpine
STEP 2: CMD ["echo", "Hello, world!"]
--> Using cache 922945d6ac32ed9de4f328073c55d929e45a2354eb848c0d574acb1419018183
STEP 3: COMMIT hello-world_hello_world
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 80, in main
  File "compose/cli/main.py", line 192, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 369, in build
  File "compose/project.py", line 521, in build
  File "compose/project.py", line 503, in build_service
  File "compose/service.py", line 1131, in build
  File "compose/progress_stream.py", line 22, in stream_output
  File "compose/utils.py", line 50, in split_buffer
  File "compose/utils.py", line 26, in stream_as_text
  File "compose/service.py", line 1896, in build
IndexError: list index out of range
[13975] Failed to execute script docker-compose
```

**Describe the results you expected:**

Desired behaviour and ID format, demonstrated with Docker:
```
$ docker build . --iidfile=id.txt
...
$ cat id.txt
sha256:0873da882a9bf444a7595643212dabebadf975fa312e2f0b94e889dff2bf0a0e

$ docker-compose build
Building hello_world
Step 1/2 : FROM alpine
 ---> 389fef711851
Step 2/2 : CMD ["echo", "Hello, world!"]
 ---> Using cache
 ---> 0873da882a9b

Successfully built 0873da882a9b
Successfully tagged hello-world_hello_world:latest
```
**Output of `podman version`:**

```
Version:      3.0.0-rc2
API Version:  3.0.0
Go Version:   go1.15.7
Built:        Mon Feb  8 05:17:21 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**
Probably not relevant.

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

N/A - manually compiled and installed.

**Additional environment details:**

Using podman-docker@2.2.1, however a simple `alias docker=podman` encounters the same issue.
Using docker-compose@1.28.2.

**Thoughts on possible fixes:**

* Podman could change the `--iidfile` output to match Docker -- this would be a breaking changing. But 3.0 will be part of a major release, so ¯\\_(ツ)_/¯.
* For a non-breaking idea, an extra flag, such as `--docker-style-iidfile` could be added to output the ID with Docker's format. The downside is that `podman-docker` would have to silently pass this flag for `docker-compose` to work.
* Encourage the docker-compose team to support parsing Podman's format. i.e. if file doesn't contain `:`, assume the whole file is the ID. This would require interest and co-operation from docker-compose though.

My apologies if this issue is more suited to `buildah`, however, I see references to `--iidfile` in both Podman's & Buildah's source. Plus I'm not sure how much the buildah team would care about this.

Thanks!

**Comment by vrothberg** [comment]
Thanks for opening the issue, @lachlan2k!

I think that changing the output to be compatible with Docker is the right thing to do.

**Comment by vrothberg** [comment]
Opened https://github.com/containers/buildah/pull/2984 to address the issue.

**Comment by lachlan2k** [comment]
Awesome! Thanks for the quick turnaround -- the format is as expected and docker-compose is now working perfectly for me.

**Comment by TomSweeneyRedHat** [comment]
@lachlan2k thanks for the follow up!  :+1:
