### ISSUE TITLE
Podman IN Docker works for Fedora, but not CentOS 8

### ISSUE THREAD

**Issue by gbraad** [containers/podman#9261]
Have been trying to get Podman IN Docker, which was no problem with the current Fedora 33; by changing the cgroup_manager, event_logger and the storage driver. However, when performing the same steps for CentOS 8 I kept having issues with iptables.

/kind bug

**Description**

**Steps to reproduce the issue:**

1. I create a Pind container image for CentOS: https://github.com/gbraad/pind-images/blob/main/Dockerfile.centos
2. `docker run -it --rm podman-centos bash`
3. `podman run -it --rm fedora bash`

**Describe the results you received:**

```
[root@72d3dae8c5b1 /]# podman run -it --rm fedora bash
ERRO[0000] Error adding network: running [/usr/sbin/iptables -t filter -C FORWARD -m comment --comment CNI firewall plugin rules -j CNI-FORWARD --wait]: exit status 2: iptables v1.8.4 (nf_tables): Couldn't load match `comment':No such file or directory

                Try `iptables -h' or 'iptables --help' for more information.
ERRO[0000] Error while adding pod to CNI network "podman": running [/usr/sbin/iptables -t filter -C FORWARD -m comment --comment CNI firewall plugin rules -j CNI-FORWARD --wait]: exit status 2: iptables v1.8.4 (nf_tables): Couldn't load match `comment':No such file or directory

                                          Try `iptables -h' or 'iptables --help' for more information.
Error: error configuring network namespace for container b7affb34f4a8a142e37f41ba76a1da532d707c7ee5a418311e7bb870c4e4e99f: running [/usr/sbin/iptables -t filter -C FORWARD -m comment --comment CNI firewall plugin rules -j CNI-FORWARD --wait]: exit status 2: iptables v1.8.4 (nf_tables): Couldn't load match `comment':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.

```

Complete output is hereL https://github.com/gbraad/pind-images/issues/2

**Describe the results you expected:**
I would expect the container to start.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
[root@79e135a49330 /]# podman version
Version:      2.0.5
API Version:  1
Go Version:   go1.14.7
Built:        Thu Sep 24 17:58:13 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
[root@79e135a49330 /]# podman info --debug
host:
  arch: amd64
  buildahVersion: 1.15.1
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.20-2.module_el8.3.0+475+c50ce30b.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.20, commit: 1019ecdeda3936be22162bb1cca308192145de53'
  cpus: 8
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: file
  hostname: 79e135a49330
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.72-microsoft-standard-WSL2
  linkmode: dynamic
  memFree: 15215374336
  memTotal: 26704027648
  ociRuntime:
    name: runc
    package: runc-1.0.0-68.rc92.module_el8.3.0+475+c50ce30b.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 7516192768
  swapTotal: 7516192768
  uptime: 233h 4m 0.48s (Approximately 9.71 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus: {}
  imageStore:
    number: 0
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1600970293
  BuiltTime: Thu Sep 24 17:58:13 2020
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.0.5
```

***Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes/~~No~~

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I have tried to use a more recent version of Podman on CentOS, but this resulted in the same problem. When I disable the firewall type from the network I can start the containers in that case, but they would not have any network/unable to resolve hostnames. What can be done to resolve this? WIll an update include a fix for the CNI plugins for example?

**Comment by mheon** [comment]
@rhatdan @umohnani8 Here's another in-container bug for you folks

**Comment by rhatdan** [comment]
We have just published

https://www.redhat.com/sysadmin/podman-inside-container
And
https://www.redhat.com/sysadmin/podman-inside-kubernetes

Please read these and see if they help solve your problem.  Reopen if you need more information.
