### ISSUE TITLE
Fail to generate swagger.yaml

### ISSUE THREAD

**Issue by photoszzt** [containers/podman#9276]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Fail to generate swagger.yaml

**Steps to reproduce the issue:**

1. get the go-swagger with version v0.26.1
2.  make swagger

2.

3.

**Describe the results you received:**
swagger generate spec -o swagger.yaml -i tags.yaml -w ./ -m
2021/02/08 15:25:23 WARNING: Missing embedded parser for a *types.Basic, skipping model
2021/02/08 15:25:23 WARNING: Missing embedded parser for a *types.Basic, skipping model
2021/02/08 15:25:23 WARNING: Missing embedded parser for a *types.Basic, skipping model
2021/02/08 15:25:23 WARNING: Missing embedded parser for a *types.Basic, skipping model
unsupported type "invalid type"
make[1]: *** [Makefile:12: swagger.yaml] Error 1
make[1]: Leaving directory '/mnt/data/src/ray_application/podman/pkg/api'
make: *** [Makefile:252: pkg/api/swagger.yaml] Error 2

**Describe the results you expected:**
The file is successfully generated. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.2
Built:        Wed Dec 31 18:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.24, commit: '
  cpus: 8
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: newage
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.8.0-41-generic
  linkmode: dynamic
  memFree: 6481321984
  memTotal: 33569755136
  ociRuntime:
    name: runc
    package: 'containerd.io: /usr/bin/runc'
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc92
      commit: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
      spec: 1.0.2-dev
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 34815864832
  swapTotal: 34815864832
  uptime: 3h 39m 33.35s (Approximately 0.12 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/zhitingz/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/zhitingz/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 19
  runRoot: /run/user/1000/containers
  volumePath: /home/zhitingz/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 0
  BuiltTime: Wed Dec 31 18:00:00 1969
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 2.2.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 2.2.1~4 amd64 [installed]
podman/unknown 2.2.1~4 arm64
podman/unknown 2.2.1~4 armhf
podman/unknown 2.2.1~4 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

I have tried using the master and version 2.2.1. They both fail. 

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm using ubuntu 20.04 LTS physical machine.

**Comment by baude** [comment]
@photoszzt i just tried this on my laptop (fedora) by rebuilding the latest go-swagger from their github repo.  It worked perfectly.  Could you tell me more about your environment.  Did you use their static build? How did you get go-swagger onto your system?

**Comment by photoszzt** [comment]
@baude I try both "go get" and download the static build. They both fail the same way.

**Comment by baude** [comment]
It worked perfectly for me using 20.04's default golang which is 1.13. I used both a compiled version of go-swagger and their static binary. Perhaps it is your golang binaries that have a problem?  That said, I am using golang-1.15 on Fedora with no problem.  I'm not sure we can call this a Podman issue at this point?

**Comment by photoszzt** [comment]
I'm using the binary I directly download from go's website(https://golang.org/dl/).

**Comment by photoszzt** [comment]
@baude I tried both 1.15.8 and 1.14.15, and fail the same way.

**Comment by baude** [comment]
@photoszzt I'll look again in the morning, but again, I don't think is a podman issue at all. if you can join #podman on freenode we might be able to live debug the issue collaboratively.

**Comment by photoszzt** [comment]
@baude Sure. I can join freenode tomorrow. I also try the ubuntu's go and also fail. I also try using a fresh ubuntu 20.04 container, install the dependencies and it also fails.

**Comment by baude** [comment]
@photoszzt try this:

```
FROM docker.io/library/ubuntu:20.04

# Install various packages we need from Ubuntu
RUN apt-get update && apt-get install -y make git wget && apt-get clean all

# Install latest golang binaries from upstream
RUN wget -qO- https://golang.org/dl/go1.15.8.linux-amd64.tar.gz | tar xvz -C /usr/local

# Set environment path to pick up new golang
ENV PATH="/usr/local/go/bin:${PATH}"

# Get and build go-swagger and pull upstream podman
RUN go get -u github.com/go-swagger/go-swagger/cmd/swagger && git clone http://github.com/containers/podman /root/go/src/github.com/containers/podman

# Set the workdir for convenience
WORKDIR /root/go/src/github.com/containers/podman
```

1. Make a Containerfile from the above.
2. podman build -t swagger .
3. podman run -it --rm swagger /bin/bash
# make swagger

**Comment by photoszzt** [comment]
@baude Thanks for the steps. It's working now.

**Comment by photoszzt** [comment]
@baude By the way, this is the container setup I try that fail:
```
From ubuntu:focal
ENV TZ=America/Chicago
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get -y update && apt-get -y install \
    git \
    golang-go \
    go-md2man \
    iptables \
    libassuan-dev \
    libbtrfs-dev \
    libc6-dev \
    libdevmapper-dev \
    libglib2.0-dev \
    libgpgme-dev \
    libgpg-error-dev \
    libprotobuf-dev \
    libseccomp-dev \
    libselinux1-dev \
    libsystemd-dev \
    pkg-config \
    runc \
    uidmap \
    make

RUN git clone https://github.com/go-swagger/go-swagger.git && \
    cd go-swagger && go install ./cmd/swagger && cd -

RUN git clone https://github.com/containers/podman.git && \
    cd podman && make swagger && cd -
```
I think the difference is I didn't know I need to put the source folder in GOPATH.
