### ISSUE TITLE
Registry selection dropdown contains both valid and invalid registries 

### ISSUE THREAD

**Issue by PavelSosin-320** [containers/podman#9279]
**Description**
In the case when not fully qualified image name is used in the run and pull commands the dropdown list contains both valid and invalid proposals:
Already login-in, not yet login-in, that allow anonymous access, those require authentication, accessible, not accessible, etc.   The selection of one of the registries from the list causes arbitrary error message and unpredictable results. In the test automation /kind bug
scenario, such behavior is unacceptable.
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**
/kind bug

**Steps to reproduce the issue:**

1. Run podman run or podman pull command with partially qualified image name

2. Select arbitrary registry from the proposed registry list dropdown, not logged, that user has no authorization, ...
3.

**Describe the results you received:**
An arbitrary list of error messages

**Describe the results you expected:**
A single error message indicating what the user must do as Elementary UX standard requires. All other error messages must be sent to log for further analysis by the user.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Podman 3.0 rc1
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Technically, I expect that the proposal list is filtered by podman login docker.io --get-login

**Comment by PavelSosin-320** [comment]
Further consideration: on the top of this correction, if filtered proposed registry list has only 1 entry the is no need in the visualization of UI, and the command can proceed with [INFO] message. It will be good for the test automation because simple bash script:
podman login
podman pull
podman run
do tests
podman logout 

can be used for unit testing.

**Comment by vrothberg** [comment]
We've been discussing this behavior in detail in another issue already. The decision of which registries are in the `unqualified-search-registries.conf` in `/etc/containers/registries.conf` is up to each distribution. Fedora has a different list than RHEL, same for OpenSUSE.

Please refer to the blog on short-name aliasing (https://www.redhat.com/sysadmin/container-image-short-names) or the documentation (https://github.com/containers/image/blob/master/docs/containers-registries.conf.5.md).

If you only want to use one registry for short-name resolution, you can change the configuration. Also, you can change the short-name-mode as described in the blog and documentation.

**Comment by PavelSosin-320** [comment]
@vrothberg No I want to use more than one. But I don't want to stuck with secured registries without authorization. When I develop a test I can't edit the configuration inside before_all and after_all methods.  I also want dev, test, and rel environment separation.

**Comment by vrothberg** [comment]
For testing, you could have multiple local config files and use the `REGISTRIES_CONFIG_PATH` environment variable. Would that work in your environment?

**Comment by PavelSosin-320** [comment]
@vrothberg If registry configuration will work as described in the old [Atomic Insecure times of users and support in the future](https://www.projectatomic.io/blog/2018/05/podman-tls/) it will definitely work. But id doesn't solve the issue that the dropdown should not show invalid options or should not allow their selection (inactive). Podman login --user-info does the probe and easily save the time of users and support. Without it, every forgotten password will be the Github issue.

**Comment by vrothberg** [comment]
@PavelSosin-320, do you consider a registry to be invalid when there are no local credentials for it?

**Comment by PavelSosin-320** [comment]
Yes, the is widspread scenario when a user knows the registry URL because it was published or used in the past, but his/her authorization has not been granted or revoked by the proprietary registry owner. Also, RedHat has such a registry. When authorization is revoked, it doesn't update registries.conf file. It only makes this registry "invisible" to the user without logon. Podman login --user-info solves this issue like the redundant OS specific registries in the configuration file. Podman login brings registry to UI, Podman logout will clean undesired registries from the UI.

**Comment by vrothberg** [comment]
The prompts only purpose is to let the user decide which `unqualified-search-registry` to pull from. Previously, Podman was just iterating over the list and the first successful pull won.

Only displaying registries that have local matching credentials is not part of the decision making.  A user may very well have forgotten to log in or may just want to pull a public image.  Querying each and every registry before the prompt sounds tempting and is something we considered but did not want to do. Transient network errors or registry downtimes may lead to false results.  Also it's a rather expensive process which would delay the prompt significantly, especially on slow networks.

Note that there is no Podman command that updates the registries.conf. Adding and removing these registries with `podman login/logout` would break backwards compatibility.

**Comment by PavelSosin-320** [comment]
No, I don't propose to edit registries.conf. I would like to avoid it. The cost of getting 
[pavel@MSI-wsl ~]$ podman pull nodejs
✔ docker.io/library/nodejs:latest
Trying to pull docker.io/library/nodejs:latest...
  denied: requested access to the resource is denied
Error: Error initializing source docker://nodejs:latest: Error reading manifest latest in docker.io/library/nodejs: errors:
denied: requested access to the resource is denied
unauthorized: authentication required. for those who have fast internet the time per **every image pull** is the same as the probe podman login --get-login docker.io or higher. The probe of the Enterprize repository or repository deployed to AWS, GCP can be as low as portions of a second.
