### ISSUE TITLE
Containers created with docker-compose are not able to connect to each other by using their name

### ISSUE THREAD

**Issue by d3xter** [containers/podman#9292]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Creating multiple containers with a single docker-compose.yml should allow the running containers to talk to each other using the container name. Connecting via IP address works fine.

docker-compose.yml:

```
version: '3.3'

services:
    db:
        container_name: podman_compose_db
        image: mysql:5.6
        volumes:
            - db-volume:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        container_name: podman_compose_phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
          ports:
          - "80:80"
        environment:
          - PMA_ARBITRARY=1

volumes:
  db-volume: 
```

**Steps to reproduce the issue:**

1. Run `sudo docker-compose -H unix:///run/podman/podman.sock up -d` 
2. Open `http://localhost/`
3. Try to connect to the database with host `podman_compose_db`, user `root` and password `root`

**Describe the results you received:**

PHPMyAdmin is not able to connect to the database

![grafik](https://user-images.githubusercontent.com/159784/107420876-afa34780-6b19-11eb-9269-b002f44f4501.png)

**Describe the results you expected:**

PHPMyAdmin is able to connect to the database

**Output of `podman version`:**

```
Version:      3.0.0-dev
API Version:  3.0.0
Go Version:   go1.15.6
Git Commit:   de5f52893ee05851244b042e348ea3413b0c464d
Built:        Sat Aug  4 02:00:00 2018
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: podman-3.0.0-1612892199.git763d5229.fc33.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.7, commit: 98d18ddf28f92704bf3ebf68cebfa0a01e546565'
  cpus: 16
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.12-200.fc33.x86_64
  linkmode: dynamic
  memFree: 4196048896
  memTotal: 33650802688
  ociRuntime:
    name: runc
    package: runc-1.0.0-279.dev.gitdedadbf.fc33.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc92+dev
      commit: c9a9ce0286785bef3f3c3c87cd1232e535a03e15
      spec: 1.0.2-dev
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 11h 48m 48.4s (Approximately 0.46 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 4
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1533340800
  BuiltTime: Sat Aug  4 02:00:00 2018
  GitCommit: 98d18ddf28f92704bf3ebf68cebfa0a01e546565
  GoVersion: go1.15.7
  OsArch: linux/amd64
  Version: 3.0.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ sudo dnf info podman
Last metadata expiration check: 1:16:09 ago on Tue Feb  9 19:07:25 2021.
Installed Packages
Name         : podman
Epoch        : 99
Version      : 3.0.0
Release      : 1612892199.git763d5229.fc33
Architecture : x86_64
Size         : 38 M
Source       : podman-3.0.0-1612892199.git763d5229.fc33.src.rpm
Repository   : @System
From repo    : copr:copr.fedorainfracloud.org:baude:Upstream_CRIO_Family
Summary      : Manage Pods, Containers and Container Images
URL          : %{git_podman}
License      : ASL 2.0
Description  : Manage Pods, Containers and Container Images
             : podman provides a library for applications looking to use
             : the Container Pod concept popularized by Kubernetes.
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
@baude PTAL

**Comment by baude** [comment]
this worked perfectly for me ... you likely do not have the dnsname plugin installed.

```
sudo dnf install podman-plugins
```

This is likely not being built or dep'd by the COPR repository.

**Comment by d3xter** [comment]
@baude Good catch, the dnsname plugin was not installed. Establishing a connection works after installing it and recreating the network

**Comment by iam-ehsan** [comment]
My containers are unable to communicate even with podman 3.2.3 and dns plugins installed on RHEL 8.4

**Comment by pantuza** [comment]
In my case, I had to first install `dnf` into `podman machine` then install `podman-plugins`:

```bash
$> podman machine ssh sudo rpm-ostree install dnf
$> podman machine ssh sudo systemctl reboot 
$> podman machine ssh sudo dnf install podman-plugins
```

**Comment by renegadevi** [comment]
> this worked perfectly for me ... you likely do not have the dnsname plugin installed.
> 
> ```
> sudo dnf install podman-plugins
> ```
> 
> This is likely not being built or dep'd by the COPR repository.

Spent almost a month on this issue with Podman on RHEL. There is no notice or indication that I was missing a package that that would lack communication. Just end up with nginx spitting out the error:

`nginx: [emerg] host not found in upstream`

**Now it works like it should again**.🎉

**Comment by micafego** [comment]
FWIW, as mentioned by @d3xter, I had to recreate the network after installing `podman-plugins`. In other words, the network's `dns_enabled` setting needs to be set to `true`. In my case, before installing `podman-plugins`, `dns_enable` was set to `false` and after installing it, it was still set to `false`, which is why removing and recreating the network was needed.
😀
