### ISSUE TITLE
[APIv2] /networks endpoint returns `null` instead of `[]` when there're no networks

### ISSUE THREAD

**Issue by riyad** [containers/podman#9293]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Trying to find regressions by exercising the APIv2 trough [docker-py](https://github.com/docker/docker-py)'s test suite (see #5386) I came across a flaky assertion in the [`TestNetworks::test_remove_network`](https://github.com/docker/docker-py/blob/master/tests/integration/api_network_test.py#L85) test.

It seems that Podman 3.0.0-dev wrongly returns `null` (instead of `[]`) from the `/networks` endpoint when no networks are defined.

**Steps to reproduce the issue:**

1. make sure we have no networks
```$ podman network ls
NAME    VERSION  PLUGINS
```

2. list the networks via API:
```$ curl -sS -v --unix-socket /var/run/user/1000/podman/podman.sock -XGET 'http://localhost/v1.40/networks'
*   Trying /var/run/user/1000/podman/podman.sock:0...
* Connected to localhost (/run/user/1000/podman/podman.sock) port 80 (#0)
> GET /v1.40/networks HTTP/1.1
> Host: localhost
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Api-Version: 1.40
< Content-Type: application/json
< Libpod-Api-Version: 2.0.0
< Server: Libpod/2.0.0 (linux)
< Date: Tue, 09 Feb 2021 20:30:40 GMT
< Content-Length: 5
< 
null
* Connection #0 to host localhost left intact
```

**Describe the results you received:**

Response was `200 null`

**Describe the results you expected:**

Response was `200 []`

**Additional information you deem important (e.g. issue happens only occasionally):**

FWIW: Podman 2.2.1 returns the correct result.

**Comment by rhatdan** [comment]
@jwhonce @baude @Luap99 PTAL

**Comment by Luap99** [comment]
I take this one.
