### ISSUE TITLE
[APIv2]  `/networks/prune` endpoint has wrong response format

### ISSUE THREAD

**Issue by riyad** [containers/podman#9310]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Trying to find regressions by exercising the APIv2 trough [docker-py](https://github.com/docker/docker-py)'s test suite (see #5386) I came across the failing [`TestNetworks::test_prune_networks`](https://github.com/docker/docker-py/blob/master/tests/integration/api_network_test.py#L467) test.

It seems that the Podman 3.0.0-dev `/networks/prune` endpoint wrongly returns the list of deleted networks directly `[...]` (instead of nesting them [according to the Docker API docs](https://docs.docker.com/engine/api/v1.40/#operation/NetworkPrune)).

**Steps to reproduce the issue:**

1.
```shell
$ curl -sS --unix-socket /var/run/user/1000/podman/podman.sock -XPOST 'http://localhost/v1.40/networks/create' -H "Content-Type: application/json" -d '{"Name": "dockerpytest_6a208c32613d1dde"}'
{"Id":"f5e714d4689079d34aa0b0f1d8a11f930da56bb66e1a450f31727776b9029a1c","Warning":null}
```

2.
```shell
$ curl -sS --unix-socket /var/run/user/1000/podman/podman.sock -XPOST 'http://localhost/v1.40/networks/prune'                                                                                   
["dockerpytest_6a208c32613d1dde"]
```

**Describe the results you received:**

The response looked like `200 ["<network name>", ...]`

**Describe the results you expected:**

The response should look like `200 {"NetworksDeleted": ["<network name>", ...]}`

**Additional information you deem important (e.g. issue happens only occasionally):**

Docker API docs: https://docs.docker.com/engine/api/v1.40/#operation/NetworkPrune

**Comment by baude** [comment]
thanks for the excellent write up!
