### ISSUE TITLE
[v3.0] APIv2 Test: FAIL: test_start_containers (test_rest_v2_0_0.TestApi)

### ISSUE THREAD

**Issue by cevich** [containers/podman#9328]
/kind bug

**Description**

[Daily cirrus-cron job failed at commit 2b89fe on branch v3.0.
](https://cirrus-ci.com/build/5137396943552512)

**Steps to reproduce the issue:**

1.  Wait for cirrus-cron job to execute on v3.0 branch

2. Open a PR against v3.0 branch (without any changes)

**Describe the results you received:**

https://cirrus-ci.com/task/4800100344004608

**Describe the results you expected:**

All tests on 3.0 branch should pass

**Additional information you deem important (e.g. issue happens only occasionally):**

All other relevant details (versions, logs, artifacts, output, etc.) are included in the above links

**Comment by rhatdan** [comment]
@cevich What is the scoop on this one?

**Comment by cevich** [comment]
This was (hopefully) fixed by https://github.com/containers/podman/pull/9699
