### ISSUE TITLE
Release key for 3.0.0 has expired

### ISSUE THREAD

**Issue by Foxboron** [containers/podman#9330]
Yo!

Seems like the key that belongs to @mheon has expired. It's the key that has signed the v3.0.0 tag and previous tags. No updates on the keyserver and the key fetched from their github profile is not updated either.

**Comment by mheon** [comment]
I definitely updated the expiration for the key locally and pushed it to a keyserver. Maybe Github also requires a new copy of the pubkey?

**Comment by Foxboron** [comment]
Which keyserver? I'm not sure if I'm failing at fetching it because of the keyservers being wonkey these days. Nothing on WKDs either :/

**Comment by mheon** [comment]
I just re-pushed to pool.sks-keyservers.net and pgp.mit.edu, in case it hadn't updated.

**Comment by Foxboron** [comment]
I was pulling from keyserver.ubuntu.com as the sks keypool has been broken for a while. Got it now :) Thanks!
