### ISSUE TITLE
Go bindings tutorial is out of date

### ISSUE THREAD

**Issue by mqus** [containers/podman#9334]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

The documentation in https://github.com/containers/podman/blob/master/docs/tutorials/podman-go-bindings.md is out of date and refers to the old repository libpod. Please update it, I personally can't make sense of the new structure, what I need and what I don't need.

It would also be nice if the go package documentation would contain an introduction into how the go bindings fit together. As of now, there is only a per-function description of a single (unstructured) package here: https://pkg.go.dev/github.com/containers/podman/v2/libpod

**Comment by vrothberg** [comment]
Thanks for reaching out.

@lsm5 would you update the tutorial with the latest 3.0 bindings? @baude FYI

**Comment by baude** [comment]
I think we have some wires crossed.  The reporter is correct that the tutorial is out of date.  There is an updated how-to on the bindings right here -> https://github.com/containers/podman/tree/master/pkg/bindings.

However, the second link provided by @mqus are API calls "in" libpod.  It should be clarified that when we talk about bindings, we are referring to go-bindings that wrap the RESTFul API calls not the internal libpod calls.

That said, there have been a series of asks lately for more concise internal APIs for libpod. We are still debating the upside to doing that.

**Comment by mqus** [comment]
Sorry, I'm still a newbie when it comes to podman and the container ecosystem as a whole. I got to the linked godoc by following the godoc badge at the top of the main readme, so this must have misled me. 

Can I also use libpod to do effectively the same thing as the go bindings, but more directly, without having to set up a socket and daemon? Or are these APIs too raw and intended to be used internally?

**Comment by mheon** [comment]
Libpod can definitely do that, but the APIs it offers are not presently considered stable (meaning we reserve the right to change the public interface without a major version bump; that won't happen with the REST API). Practically speaking, though, the bigger issue is a lack of documentation - we have docs around the REST API, but almost none exist for Libpod.

I also really want to go through and do a proper cleanup of the public interface in Libpod at some point - there's a lot of implementation details leaking out that should not be in the API.
