### ISSUE TITLE
Failing to access vainfo with --device /dev/dri/  for containers

### ISSUE THREAD

**Issue by Spindel** [containers/podman#9338]
/kind bug
**Description**

Attempting to access vaapi (vainfo) in a container fails due to some restriction.

I'm attempting to get hardware acceleration going in an openSUSE MicroOS machine, thus trying to run it in a container. Some restricting that is present without the --privileged flag is preventing this, but I cannot figure out which or how.

group 484 is "video"   on the host
group 486 is ""render" on the host

The following fails  ( removing privileged) :

** Failing case**  
`/usr/bin/podman run -ti --rm=true --group-add=484   --group-add=486 --device /dev/dri:/dev/dri:rwm debian:latest '/bin/bash' '-c' 'apt update;apt install -y vainfo;vainfo'`

** Working case **

`/usr/bin/podman run -ti --rm=true --group-add=484   --group-add=486 --privileged --device /dev/dri:/dev/dri:rwm debian:latest '/bin/bash' '-c' 'apt update;apt install -y vainfo;vainfo'`

The same behaviour is true for both rootless and rootful containers.

**Describe the results you received:**
```
error: XDG_RUNTIME_DIR not set in the environment.
error: can't connect to X server!
libva info: VA-API version 1.4.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so
libva info: Found init function __vaDriverInit_1_4
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
libva error: /usr/lib/x86_64-linux-gnu/dri/radeonsi_drv_video.so init failed
libva info: va_openDriver() returns 2
vaInitialize failed with error code 2 (resource allocation failed),exit

```

**Describe the results you expected:**

Working hardware accelleration

**Additional information you deem important (e.g. issue happens only occasionally):**

What I find mostly lacking is debugging information for a case like this. It is difficult for me as a somewhat advanced user to figure out the next steps.  My suspicion is that it is some kind of capability or limitation applied, but there isn't a good way for me to find out which settings, capabilities and more I can attempt to add rather than the big "--privileged" hammer.

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.13.15
Built:        Tue Jan  5 01:00:00 2021
OS/Arch:      linux/amd64

```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.22-1.1.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.22, commit: unknown'
  cpus: 4
  distribution:
    distribution: '"opensuse-tumbleweed"'
    version: "20210210"
  eventLogger: journald
  hostname: spring
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.12-1-default
  linkmode: dynamic
  memFree: 277774336
  memTotal: 14575706112
  ociRuntime:
    name: runc
    package: runc-1.0.0~rc93-1.1.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc93
      commit: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
      spec: 1.0.2-dev
      go: go1.13.15
      libseccomp: 2.5.0
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 13h 11m 26.97s (Approximately 0.54 days)
registries:
  search:
  - registry.opensuse.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 1
    stopped: 1
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 8
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1609804800
  BuiltTime: Tue Jan  5 01:00:00 2021
  GitCommit: ""
  GoVersion: go1.13.15
  OsArch: linux/amd64
  Version: 2.2.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
rpm -q podman
podman-2.2.1-1.1.x86_64

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Not the latest version of podman as it isn't available in opensuse  yet.

I have checked the troubleshooting guide.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by Spindel** [comment]
strace inside a container (with cap_sys_ptrace added) suggests that the system is attempting to look up character devices via /sys/dev/char, and I can't for the life of me figure out how to get that path mounted into a container without using --privileged


```

fstat(4, {st_mode=S_IFCHR|0666, st_rdev=makedev(0xe2, 0x80), ...}) = 0
stat("/sys/dev/char/226:128/device/drm", 0x7fff91d15c60) = -1 ENOENT (No such file or directory)

```

**Comment by rhatdan** [comment]
Tey podman --security-opt unmask=/sys/dev or /sys/dev/char ...

**Comment by Spindel** [comment]
is --security-opt unmask=...  a new feature? 

it's not available on either my Fedora 33 machine nor openSuse tumbleweed?

**Comment by rhatdan** [comment]
Yes new feature in podman 3.0.

**Comment by rhatdan** [comment]
I believe this functionality is available now, so I am closing this issue.
