### ISSUE TITLE
Package update failure on Ubuntu 20.04

### ISSUE THREAD

**Issue by zgoda** [containers/podman#9345]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

On Ubuntu 20.04 update fails with dpkg error

**Steps to reproduce the issue:**

1. sudo apt update

2. sudo apt upgrade

**Describe the results you received:**

```
$ LANG=C sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 buildah : Depends: containers-common (>= 100:1-7) but 1.2.1~2 is installed
 podman : Depends: containers-common (>= 100:1-7) but 1.2.1~2 is installed
 skopeo : Depends: containers-common (>= 100:1-7) but 1.2.1~2 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
$ LANG=C sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
  containers-golang containers-image varlink
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  containers-common
The following packages will be upgraded:
  containers-common
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
8 not fully installed or removed.
Need to get 0 B/44,8 kB of archives.
After this operation, 34,8 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 281752 files and directories currently installed.)
Preparing to unpack .../containers-common_100%3a1-7_all.deb ...
Unpacking containers-common (100:1-7) over (1.2.1~2) ...
dpkg: error processing archive /var/cache/apt/archives/containers-common_100%3a1-7_all.deb (--unpack):
 trying to overwrite '/usr/share/man/man5/containers-auth.json.5.gz', which is also in package containers-image 5.8.1~1
Errors were encountered while processing:
 /var/cache/apt/archives/containers-common_100%3a1-7_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Describe the results you expected:**

Packages gets updated.

**Output of `podman version`:**

```
$ podman version
Version:      3.0.0
API Version:  3.0.0
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.2
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.26, commit: '
  cpus: 8
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: bekon
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.4.0-65-generic
  linkmode: dynamic
  memFree: 13355417600
  memTotal: 31503855616
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.17.6-58ef-dirty
      commit: fd582c529489c0738e7039cbc036781d1d039014
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 2147479552
  swapTotal: 2147479552
  uptime: 8h 28m 12.77s (Approximately 0.33 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/jarek/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.9.0
        fuse-overlayfs: version 1.4
        FUSE library version 3.9.0
        using FUSE kernel interface version 7.31
  graphRoot: /home/jarek/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 21
  runRoot: /run/user/1000/containers
  volumePath: /home/jarek/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 3.0.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman/unknown,now 100:3.0.0-1 amd64 [installed]
podman/unknown 100:3.0.0-1 arm64
podman/unknown 2.2.1~4 armhf
podman/unknown 100:3.0.0-1 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine.

**Comment by vrothberg** [comment]
Thanks for reaching out! @lsm5 PTAL

**Comment by rokat** [comment]
Hello after removing the package containers-image 

By doing 
```shell
sudo apt remove containers-image podman
```
Because it tries to replace
```shell
 /usr/share/man/man5/containers-auth.json.5.gz
```
Which is already owned by containers-image , in my opinion package-conflict issue 

And re-installing it word as a charm

Good luck ! (eager to test podman3 and remove podman-compose from pip ^^)

**Comment by scotticles** [comment]
This happened to me on two machines, had to completely remove podman and then install podman, which is fine but i have production servers with podman...and not really wanted to remove and add to get podman v3. Hopefully a fix is on its way.

**Comment by asottile** [comment]
for me the workaround was:

```bash
sudo apt purge podman-rootless buildah
sudo apt autoremove --purge
sudo apt install podman-rootless buildah
```

**Comment by buck2202** [comment]
Probably goes without saying, but this affects 18.04 as well. `containers-image` was previously a dependency of `containers-common`, but `containers-common` is now listed without dependencies. 

Output from an un-updated system:
```
$ apt show -a containers-common
Package: containers-common
Version: 100:1-7
Priority: optional
Section: devel
Maintainer: Lokesh Mandvekar <lsm5@fedoraproject.org>
Installed-Size: 102 kB
Provides: skopeo-containers
Conflicts: skopeo-containers
Replaces: skopeo-containers
Homepage: https://github.com/projectatomic/skopeo
Download-Size: 44.8 kB
APT-Sources: http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04  Packages
Description: Configuration files for working with image signatures.

Package: containers-common
Version: 1.2.1~2
Status: install ok installed
Priority: optional
Section: devel
Source: skopeo
Maintainer: Lokesh Mandvekar <lsm5@fedoraproject.org>
Installed-Size: 68.6 kB
Provides: skopeo-containers
Depends: containers-golang, containers-image (>= 5.8.0~1)
Conflicts: skopeo-containers
Replaces: skopeo-containers
Homepage: https://github.com/projectatomic/skopeo
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: Configuration files for working with image signatures.
```

**Comment by asciiprod** [comment]
If `containers-image` is obsolete, it must be added to the control file of `containers-common` in the `Replaces` line.

**Comment by dimon222** [comment]
Same issue is affecting entire Debian tree (not just Ubuntu)

**Comment by lsm5** [comment]
sent containers-common_1-8 to OBS just now which should replace the older dependencies. I'll fix podman and the rest to use this minimum containers-common dependency as well, but hopefully manually upgrading containers-common should handle things for now.

**Comment by lsm5** [comment]
podman 3.0.0-2 should use containers-common 100:1-8, currently building at https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman .

**Comment by lsm5** [comment]
Closing as the builds have landed on the repo. Please reopen if the issue persists.

**Comment by lsm5** [comment]
There might be an issue with registries.conf. Looking ...

**Comment by lsm5** [comment]
Should be fixed with podman 100:3.0.0-3. Building on OBS atm: https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman . Will be available hopefully in an hour or less.

I'll keep the bug open for now. Please close it if this resolves your issue.

**Comment by asciiprod** [comment]
Upgrade now works without conflicts.
But configuration directories are now a bit redundant/confusing. There is a new `/etc/containers/registries.conf.d` as well as a `/etc/containers/registries.d` in `containers-common` with `shortnames.conf` moved to the new directory.  In 2.x this was all in  `registries.d`. Is there any distinction between the two directories?
Neither the manpage nor the `registries.conf`state how and that these directories are included.

**Comment by vrothberg** [comment]
Yes, the two directories are different. `registries.conf.d` is the one for drop-in config files for the registries.conf.

**Comment by lsm5** [comment]
@vrothberg do we need a manpage update perhaps? I'm gonna close this, we can open a new bug for manpage change if need be.

**Comment by vrothberg** [comment]
> @vrothberg do we need a manpage update perhaps? I'm gonna close this, we can open a new bug for manpage change if need be.

No changes needed.  Both directories have man pages that go into detail.

**Comment by ghherlin** [comment]
Problem persists with v3.4.2 in KUbuntu 21.10 (Impish Indri);
`apt-get -y install podman
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  buildah golang-github-containernetworking-plugin-dnsname golang-github-containers-common
  golang-github-containers-image libostree-1-1 libslirp0 runc
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  containers-common
The following NEW packages will be installed:
  containers-common podman
0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/20,8 MB of archives.
After this operation, 84,0 MB of additional disk space will be used.
(Reading database ... 332265 files and directories currently installed.)
Preparing to unpack .../containers-common_100%3a1-22_all.deb ...
Unpacking containers-common (100:1-22) ...
dpkg: error processing archive /var/cache/apt/archives/containers-common_100%3a1-22_all.deb (--unpack):
 trying to overwrite '/etc/containers/policy.json', which is also in package golang-github-containers-common 0.38.16+ds1-1ubuntu1
Selecting previously unselected package podman.
Preparing to unpack .../podman_100%3a3.4.2-4_amd64.deb ...
Unpacking podman (100:3.4.2-4) ...
Errors were encountered while processing:
 /var/cache/apt/archives/containers-common_100%3a1-22_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
`
It seems to me that (at least) the file `/etc/containers/policy.json` is being sourced twice...

Trying a `podman run ...` yields the following error:
`Error: open /etc/containers/policy.json: no such file or directory`
It seems also that the installation is incomplete / aborted.

I'm stuck...

**Comment by lsm5** [comment]
@ghherlin podman is available on the default repos itself on 21.10. Best to use that.

**Comment by ghherlin** [comment]
Thanks for the suggestion.
Sadly, this is what I got:
[image: image.png]
[image: image.png]
It doesn't seem to work any better... :-(

George Herlin
Tél:+33 658 301 928

**Comment by ghherlin** [comment]
Ok, thanks. I'll try them.
BTW the images just showed muon package manager showing the same error...
George Herlin
Tél:+33 658 301 928
