### ISSUE TITLE
[v3.1-dev] [rootless] cgroup v2 not detected

### ISSUE THREAD

**Issue by tobwen** [containers/podman#9357]
/kind bug

**Description**
Seems like _cgroup v2_ isn't detected by rootless podman.

**Steps to reproduce the issue:**

```
$ target="/home/tobwen/podman/usr/local/bin"
$ alias podman="PATH=$PATH:$target $target/podman \
--conmon $target/conmon \
--network-cmd-path $target/slirp4netns \
--root=$HOME/.local/share/containers/storage \
--runtime $target/crun \
--storage-driver overlay \
--storage-opt 'overlay.mount_program=$target/fuse-overlayfs'"

$ podman info --debug
```

**Describe the results you received:**
```
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: cgroupfs
  cgroupVersion: v1
```

**Describe the results you expected:**
_cgroupVersion v2_, since it's activated in my kernel:

```
grep cgroup /proc/filesystems
nodev   cgroup
nodev   cgroup2
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.1.0-dev
API Version:  3.0.0
Go Version:   go1.14
Git Commit:   3ba0afdd0f03195827f46b50757928ead44b1567
Built:        Sat Feb 13 19:38:35 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /home/tobwen/podman/usr/local/bin/conmon
    version: 'conmon version 2.0.27-dev, commit: c3f31c0671f6c84f5e02ec710385e1e8f2936066'
  cpus: 12
  distribution:
    distribution: debian
    version: "10"
  eventLogger: journald
  hostname: dev
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.5.0-0.bpo.2-amd64
  linkmode: dynamic
  memFree: 38050312192
  memTotal: 135098531840
  ociRuntime:
    name: /home/tobwen/podman/usr/local/bin/crun
    package: Unknown
    path: /home/tobwen/podman/usr/local/bin/crun
    version: |-
      crun version 0.17.31-bdc5
      commit: eb39fb52d693c84b1ed1c80c50f2a88cf36579cb
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /home/tobwen/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.1.4+dev
      commit: 676792204708ce10c7553000dcf293a79db6277a
libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.4
  swapFree: 22982606848
  swapTotal: 25767702528
  uptime: 2565h 25m 58.12s (Approximately 106.88 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/tobwen/.config/containers/storage.conf
  containerStore:
    number: 28
    paused: 0
    running: 0
    stopped: 28
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /home/tobwen/podman/usr/local/bin/fuse-overlayfs
      Package: Unknown
      Version: |-
        fusermount3 version: 3.9.0
        fuse-overlayfs: version 1.0.0
        FUSE library version 3.9.0
        using FUSE kernel interface version 7.31
  graphRoot: /home/tobwen/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/1001/containers
  volumePath: /home/tobwen/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1613245115
  BuiltTime: Sat Feb 13 19:38:35 2021
  GitCommit: 3ba0afdd0f03195827f46b50757928ead44b1567
  GoVersion: go1.14
  OsArch: linux/amd64
  Version: 3.1.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
n/a - manual build
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Debian 10, AMD64, physical.

**Comment by mheon** [comment]
Podman will only use V2 if it is the only cgroup system in use. We do not
support it in hybrid mode where both v1 and v2 are both active at the same
time. From your report, I suspect that is what you are doing.

**Comment by tobwen** [comment]
Actually, I've used podman with v2 in the past without changing my system's config. But let me try to disable v1.

**Comment by tobwen** [comment]
A reboot did it:

```
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: systemd
  cgroupVersion: v2
```

**Comment by PavelSosin-320** [comment]
@tobwen Sorry for incompetence. Do you mean to add           **cgroup_no_v1=all systemd.legacy_systemd_cgroup_controller**
I've added the parameter kernelCommandLine=cgroup_no_v1=all to to the .wslconfig file:

following the documentation:
       _These options cause the kernel to boot with the cgroups v1
       controllers disabled (meaning that the controllers are available
       in the v2 hierarchy), and tells systemd(1) not to mount and use
       the cgroup v2 hierarchy, so that the v2 hierarchy can be manually
       mounted with the desired options after boot-up.
to /proc/cmdline ?_


The WSL Kernel is  WSL Kernel is 5.4.91-microsoft-standard-WSL2 ... x86_64 GNU/Linux. The detected Fedora version is Fedora33.
The rootfull containers are OK with cgroup manager systemd. But in the documentation I found:
_Note: CGroup manager is not supported in rootless mode when using CGroups Version V1_ without saying how to configure the distro if it uses systemd and supports cgroups V2.
WSL distros are "initrd' distros, i.e starts from small compressed root filesystem containing Kernel modules and then mounts windows disks.
I will be glad to provide further details to make Podman 3.0 to work in WSL.

**Comment by tobwen** [comment]
> Do you mean to add **cgroup_no_v1=all systemd.legacy_systemd_cgroup_controller**

No, I've added `systemd.unified_cgroup_hierarchy=1` to `GRUB_CMDLINE_LINUX_DEFAULT` in  `/etc/default/grub` a long time ago, but seems like any script removed it. After rebooting, it worked again.

I've also read that mounting the cgroupv2 mounts should be enough to make it work. But as @mheon suggest, this might not be supported right now.

**Comment by PavelSosin-320** [comment]
Maybe, the root cause is the Fedora33 distro that I use. It is not something official but Microsoft official Fedora is not functional at all. It is also started using genie because Microsoft doesn't want to support systemd.
I checked my systemd version and configuration:
systemctl --version
systemd 246 (v246.10-1.fc33)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 **default-hierarchy=unified**
may it affect? I I think unified hierarchy contradicts cgroups v2. Could you advise how to upgrade and reconfigue systemd in Fedora33?

**Comment by PavelSosin-320** [comment]
I re-checked the recent available systemd version for Fedora33 and after reading [Managing cgroups with systemd](https://www.redhat.com/sysadmin/cgroups-part-four) I found that my systemd version is the latest available. After running Fedora OCI image as rootless user I got:
podman ps
CONTAINER ID  IMAGE                                     COMMAND    CREATED        STATUS            PORTS   NAMES
7f9e6a03c9f3  registry.fedoraproject.org/fedora:latest  /bin/bash  8 minutes ago  Up 8 minutes ago          cool_williams

and 
│ └─user-1000.slice
│   ├─user@1000.service
│   │ ├─dbus-broker.service
│   │ │ ├─408 /usr/bin/dbus-broker-launch --scope user
│   │ │ └─409 dbus-broker --log 4 --controller 9 --machine-id c53a30ca9b1942819377b54eb6553043 --max-bytes 100000000000000 --max-fds 25000000000
000 --max-matches 5000000000
│   │ ├─user.slice
│   │ │ └─podman-419.scope
│   │ │   ├─436 /usr/bin/slirp4netns --disable-host-loopback --mtu 65520 --enable-sandbox --enable-seccomp -c -e 3 -r 4 --netns-type=path /run/u
ser/1000/netns/cni-1e1c8d45-e8bc-db14-4d57-01e70be3c6c6 tap0
│   │ │   ├─438 /usr/bin/fuse-overlayfs -o lowerdir=/home/pavel/.local/share/containers/storage/overlay/l/WUVOX45CTPKUPY5FC4KTAOSKL6,upperdir=/h
ome/pavel/.local/share/containers/storage/overlay/8c0198d53f7aa22309e772974662fe4ec9384e076496e5623d5fe46eed083607/diff,workdir=/home/pavel/.local/share/con
tainers/storage/overlay/8c0198d53f7aa22309e772974662fe4ec9384e076496e5623d5fe46eed083607/work /home/pavel/.local/share/containers/storage/overlay/8c0198d53f
7aa22309e772974662fe4ec9384e076496e5623d5fe46eed083607/merged
│   │ │   ├─440 /usr/bin/conmon --api-version 1 -c 7f9e6a03c9f3cf98873263001daa6f788a4003cae986f7b39032a8814435deb8 -u 7f9e6a03c9f3cf98873263001
daa6f788a4003cae986f7b39032a8814435deb8 -r /usr/bin/crun -b /home/pavel/.local/share/containers/storage/overlay-containers/7f9e6a03c9f3cf98873263001daa6f788
a4003cae986f7b39032a8814435deb8/userdata -p /tmp/podman-run-1000/containers/overlay-containers/7f9e6a03c9f3cf98873263001daa6f788a4003cae986f7b39032a8814435d
eb8/userdata/pidfile -n cool_williams --exit-dir /tmp/run-1000/libpod/tmp/exits --socket-dir-path /tmp/run-1000/libpod/tmp/socket -l k8s-file:/home/pavel/.l
ocal/share/containers/storage/overlay-containers/7f9e6a03c9f3cf98873263001daa6f788a4003cae986f7b39032a8814435deb8/userdata/ctr.log --log-level warning --run
time-arg --log-format=json --runtime-arg --log --runtime-arg=/tmp/podman-run-1000/containers/overlay-containers/7f9e6a03c9f3cf98873263001daa6f788a4003cae986
f7b39032a8814435deb8/userdata/oci-log -t --conmon-pidfile /tmp/podman-run-1000/containers/overlay-containers/7f9e6a03c9f3cf98873263001daa6f788a4003cae986f7b
39032a8814435deb8/userdata/conmon.pid --exit-command /usr/bin/podman --exit-command-arg --root --exit-command-arg /home/pavel/.local/share/containers/storag
e --exit-command-arg --runroot --exit-command-arg /tmp/podman-run-1000/containers --exit-command-arg --log-level --exit-command-arg warning --exit-command-a
rg --cgroup-manager --exit-command-arg cgroupfs --exit-command-arg --tmpdir --exit-command-arg /tmp/run-1000/libpod/tmp --exit-command-arg --runtime --exit-
command-arg crun --exit-command-arg --storage-driver --exit-command-arg overlay --exit-command-arg --storage-opt --exit-command-arg overlay.mount_program=/u
sr/bin/fuse-overlayfs --exit-command-arg --events-backend --exit-command-arg journald --exit-command-arg container --exit-command-arg cleanup --exit-command
-arg 7f9e6a03c9f3cf98873263001daa6f788a4003cae986f7b39032a8814435deb8
│

It looks like from my side everything is OK. Everything works as described in the mentioned above article written by your colleague.

**Comment by PavelSosin-320** [comment]
@tobwen I'm running currently 2 different WSL distro via genie-systemd, i.e. systemd managed: Fedora33 and Ubuntu 20.10 In both I almost sure that cgroups V2 are supported because the groups FS checks show the same results:
![image](https://user-images.githubusercontent.com/54495912/108807450-29711180-75ad-11eb-84f5-0e0398014bb7.png)
![image](https://user-images.githubusercontent.com/54495912/108807470-3aba1e00-75ad-11eb-87be-fdaf0241b9d6.png)

But yet, Podman 2.1 and Podman 3.0 correspondingly don't detect cgroup V2 according to Podman info output.
Maybe not all controllers are meaningful in the scenario when Podman runs inside VM. On other hand, why Podman configuration and functionality can't be portable between Linux-on-bare-metall and Linux-inside-VM? The difference between these 2 scenaria is not systemd or cgroups version.
The previous Docker version had similar issue but the announced [Docker 20-10](https://www.docker.com/blog/introducing-docker-engine-20-10/) has solved this issue breaking the feature parity between Docker and Podman in the benefit of Docker.
