### ISSUE TITLE
podman requires dnsmasq for custom networks

### ISSUE THREAD

**Issue by aojea** [containers/podman#9359]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I hit this in the Github actions CI, it seems that podman packages doesn't have dnsmasq as a required dependency.
Without dnsmasq custom networks fail.

**Steps to reproduce the issue:**

try to create a container with podman with a custom network without dnsmasq in the system

**Describe the results you received:**

> ERROR: failed to create cluster: podman run error: command "podman run --hostname kind-control-plane --name kind-control-plane --label io.x-k8s.kind.role=control-plane --privileged --tmpfs /tmp --tmpfs /run --volume 8e70bb2070bb8a9529ce05d177cad46f0717906498affb089d2f2d6857c63048:/var:suid,exec,dev --volume /lib/modules:/lib/modules:ro --detach --tty --net kind --label io.x-k8s.kind.cluster=kind -e container=podman --publish=127.0.0.1:41797:6443/tcp kindest/node@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab" failed with error: exit status 126
> 
> Command Output: WARNING: The same type, major and minor should not be used for multiple devices.
> time="2021-02-14T10:42:57Z" level=error msg="Error adding network: unable to locate dnsmasq in path"
> time="2021-02-14T10:42:57Z" level=error msg="Error while adding pod to CNI network \"kind\": unable to locate dnsmasq in path"
> 

**Describe the results you expected:**

I expect that when I install podman from a package, it pulls all the required dependencies

**Additional information you deem important (e.g. issue happens only occasionally):**

xref issue in Github Actions https://github.com/actions/virtual-environments/issues/2708

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

The package is installed from the stable repo, 
https://github.com/actions/virtual-environments/blob/875891b86b39572d2c947197c4222d4d62d38d39/images/linux/scripts/installers/containers.sh

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

https://github.com/actions/virtual-environments/issues/2708

**Comment by Luap99** [comment]
The cni plugin dnsname requires the dnsmasq dependency. On fedora the dnsname plugin is install via the `podman-plugins` package which requires dnsmasq.
```
$ rpm -q podman-plugins --requires 
dnsmasq
...
```

**Comment by aojea** [comment]
> The cni plugin dnsname requires the dnsmasq dependency. On fedora the dnsname plugin is install via the `podman-plugins` package which requires dnsmasq.
> 
> ```
> $ rpm -q podman-plugins --requires 
> dnsmasq
> ...
> ```

so, what is the best solution for https://github.com/actions/virtual-environments/issues/2708?

**Comment by Luap99** [comment]
You mention ubuntu 2004 so I assume it is installed via the kubic repo.

@lsm5 PTAL It looks like the `podman-plugins` debian package doesn't depend on `dnsmasq`

**Comment by lsm5** [comment]
Should be fixed with podman 100:3.0.0-3. Building on OBS atm: https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman . Will be available hopefully in an hour or less.

I'll keep the bug open for now. Please close it if this resolves your issue.

**Comment by eiginn** [comment]
Is it possible to depend on the `dnsmasq-base` package instead? that will get you the binary but skip the service and default config, `libvirt-daemon` debian packaging does the same thing. Or do you need a host level dnsmasq running specifically?

**Comment by IceCodeNew** [comment]
> Is it possible to depend on the `dnsmasq-base` package instead? that will get you the binary but skip the service and default config, `libvirt-daemon` debian packaging does the same thing. Or do you need a host level dnsmasq running specifically?

Agreed. Ubuntu is shipped with `systemd-resolved` enabled by default.
Introducing `dnsmasq` dependency only makes conflict as `dnsmasq` is not able to start.

**Comment by lsm5** [comment]
> Is it possible to depend on the `dnsmasq-base` package instead? that will get you the binary but skip the service and default config, `libvirt-daemon` debian packaging does the same thing. Or do you need a host level dnsmasq running specifically?

I'll add the change, thanks

**Comment by lsm5** [comment]
New podman-plugins building at: https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman-plugins 

New podman with updated podman-plugins dep ^ building at https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman

Should be available on the repos soon.

**Comment by lsm5** [comment]
Closing, please reopen if you notice issues.

**Comment by aojea** [comment]
Thanks for the prompt answer :1st_place_medal:
