### ISSUE TITLE
labeling networks

### ISSUE THREAD

**Issue by replicajune** [containers/podman#9361]
/kind feature

**Description**

I would like to use label for network as we can for containers or volumes using `--label`

**Output of `podman version`:**

``` sh
Version:      3.0.0
API Version:  3.0.0
Go Version:   go1.15.2
Built:        Wed Dec 31 19:00:00 1969
OS/Arch:      linux/amd64
```

**Comment by mheon** [comment]
This is already supported as of 3.0.

**Comment by replicajune** [comment]
I forgot to double-check after running an upgrade. Sorry for that. It's indeed available !
