### ISSUE TITLE
[1.6.4-rhel] golangci-lint: SA1019: g.Spec is deprecated

### ISSUE THREAD

**Issue by cevich** [containers/podman#9376]
/kind bug

**Description**

Branch-testing jobs run daily via Cirrus-CI cron jobs on various branches, including https://github.com/containers/podman/tree/v1.6.4-rhel

[As of 2/14/2021 the 'gate' task on this branch has started failing with an error.](https://cirrus-ci.com/task/4604818851364864)

**Steps to reproduce the issue:**

1. Open a PR or wait for daily branch job to execute

2. No code changes required.

**Describe the results you received:**

```
[+0008s] GO111MODULE=off go generate ./cmd/podman/varlink/...
[+0009s] if [ ! -x "/go/bin/golangci-lint" ]; then \
[+0009s] 	curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b /go/bin/ v1.18.0; \
[+0009s] fi
[+0009s] /go/bin/golangci-lint run --tests=false
[+0034s] pkg/spec/spec.go:380:5: SA1019: g.Spec is deprecated: Replace with generator.Config.  (staticcheck)
[+0034s] 				g.Spec().Process.Capabilities.Effective = []string{}
[+0034s] 				^
[+0034s] pkg/spec/spec.go:381:5: SA1019: g.Spec is deprecated: Replace with generator.Config.  (staticcheck)
[+0034s] 				g.Spec().Process.Capabilities.Permitted = []string{}
[+0034s] 				^
[+0034s] pkg/spec/spec.go:382:5: SA1019: g.Spec is deprecated: Replace with generator.Config.  (staticcheck)
[+0034s] 				g.Spec().Process.Capabilities.Ambient = []string{}
[+0034s] 				^
[+0034s] make: *** [Makefile:151: golangci-lint] Error 1
```

**Describe the results you expected:**

The 'gate' task should pass.

**Additional information you deem important (e.g. issue happens only occasionally):**

@mheon mentioned on IRC:

    that was probably me force-merging the CVE fix last week

**Comment by mheon** [comment]
Fixed
