### ISSUE TITLE
build: cannot tar container entries: 0 errors occurred

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#9379]
Another unfortunate flake that happens in multiple tests, so I can't easily analyze it:
```
Running: podman-remote [options] build --layers=true -t test --file /tmp/podman_test768134587/Dockerfile /tmp/podman_test768134587
time="2021-02-14T09:34:12-06:00" level=error msg="cannot tar container entries [/tmp/podman_test768134587/Dockerfile /tmp/podman_test768134587] error: 0 errors occurred:\n\t\n\n"
Error: 0 errors occurred:
...
Exit code is 125, expected 0 (or maybe the other way around, I can never understand ginkgo diagnostics)
```
This is happening all over the place, and is now our number-one flake. It is not easily characterized other than "podman-remote build". It seems to have started on February 8. I recommend treating this as very high priority due to the number of flakes yesterday.

## Podman rmi [It] podman rmi with cached images
* gce_instance:fedora : int remote fedora-33 root host
  * PR #9348
    * [02-14 10:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6389174224814080/html/int-remote-fedora-33-root-host.log.html#t--podman-rmi-with-cached-images--1)
  * PR #9284
    * [02-09 14:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5693393412030464/html/int-remote-fedora-33-root-host.log.html#t--podman-rmi-with-cached-images--1)

## Podman rmi [It] podman image rm - concurrent with shared layers
* gce_instance:fedora : int remote fedora-33 root host
  * PR #9348
    * [02-14 10:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6389174224814080/html/int-remote-fedora-33-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--1)
    * [02-14 10:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6389174224814080/html/int-remote-fedora-33-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--2)
    * [02-14 10:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6389174224814080/html/int-remote-fedora-33-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--3)
  * PR #9272
    * [02-08 17:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5352871224934400/html/int-remote-fedora-33-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--1)
    * [02-08 17:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5352871224934400/html/int-remote-fedora-33-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--2)
    * [02-08 17:07](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5352871224934400/html/int-remote-fedora-33-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--3)
* gce_instance:prior-fedora : int remote fedora-32 root host
  * PR #9349
    * [02-12 17:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4895706050723840/html/int-remote-fedora-32-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--1)
    * [02-12 17:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4895706050723840/html/int-remote-fedora-32-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--2)
    * [02-12 17:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4895706050723840/html/int-remote-fedora-32-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--3)
  * PR #9332
    * [02-12 05:00](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4929950496063488/html/int-remote-fedora-32-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--1)
    * [02-12 05:00](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4929950496063488/html/int-remote-fedora-32-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--2)
    * [02-12 05:00](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4929950496063488/html/int-remote-fedora-32-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--3)
  * PR #9319
    * [02-11 06:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5873097595158528/html/int-remote-fedora-32-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--1)
    * [02-11 06:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5873097595158528/html/int-remote-fedora-32-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--2)
    * [02-11 06:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5873097595158528/html/int-remote-fedora-32-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--3)
  * PR #9269
    * [02-08 15:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4507996598304768/html/int-remote-fedora-32-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--1)
    * [02-08 15:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4507996598304768/html/int-remote-fedora-32-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--2)

## Podman rmi [It] podman rmi -a with parent|child images
* gce_instance:fedora : int remote fedora-33 root host
  * PR #9348
    * [02-14 10:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6389174224814080/html/int-remote-fedora-33-root-host.log.html#t--podman-rmi--a-with-parent-child-images--1)
  * PR #9295
    * [02-09 17:58](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5005638490128384/html/int-remote-fedora-33-root-host.log.html#t--podman-rmi--a-with-parent-child-images--1)

## Podman prune [It] podman image prune skip cache images
* gce_instance:fedora : int remote fedora-33 root host
  * PR #9348
    * [02-14 10:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6389174224814080/html/int-remote-fedora-33-root-host.log.html#t--podman-image-prune-skip-cache-images--1)

**Comment by vrothberg** [comment]
I thin we may need @nalind's force.

**Comment by edsantiago** [comment]
## Podman images [It] podman images --all flag
* gce_instance:fedora : int remote fedora-33 root host
  * PR #9483
    * [02-23 06:20](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6286544166191104/html/int-remote-fedora-33-root-host.log.html#t--podman-images---all-flag--1)

## Podman run entrypoint [It] podman run entrypoint
  * PR #9464
    * [02-22 11:16](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6006523643035648/html/int-remote-fedora-32-root-host.log.html#t--podman-run-entrypoint--1)
  * PR #9418
    * [02-18 06:18](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5976636911779840/html/int-remote-fedora-32-root-host.log.html#t--podman-run-entrypoint--1)
  * PR #9399
    * [02-16 10:30](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6154728935522304/html/int-remote-fedora-32-root-host.log.html#t--podman-run-entrypoint--1)

**Comment by edsantiago** [comment]
Can someone please make this a priority? It is now the number one flake.

## Podman rmi [It] podman image rm - concurrent with shared layers
* gce_instance:fedora : int remote fedora-33 root host
  * PR #9580
    * [03-02 15:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5659447872716800/html/int-remote-fedora-33-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--1)
    * [03-02 15:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5659447872716800/html/int-remote-fedora-33-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--2)
    * [03-02 15:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5659447872716800/html/int-remote-fedora-33-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--3)
* gce_instance:prior-fedora : int remote fedora-32 root host
  * PR #9549
    * [03-01 11:49](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5684445656121344/html/int-remote-fedora-32-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--1)
    * [03-01 11:49](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5684445656121344/html/int-remote-fedora-32-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--2)
    * [03-01 11:49](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5684445656121344/html/int-remote-fedora-32-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--3)
    * [03-01 10:39](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4818549043625984/html/int-remote-fedora-32-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--1)
    * [03-01 10:39](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4818549043625984/html/int-remote-fedora-32-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--2)
    * [03-01 10:39](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4818549043625984/html/int-remote-fedora-32-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--3)


FWIW it seems to be correlated with the following error:
```
Error: 1 error occurred:
         	* error reading image "2a4cefc9e51e81ad10c4e9b67f99ec00be58b8a29bb900940bb322b56dca00c1" as image: error locating item named "manifest" for image with ID "2a4cefc9e51e81ad10c4e9b67f99ec00be58b8a29bb900940bb322b56dca00c1": file does not exist
```

**Comment by edsantiago** [comment]
## sys: build with copy-from referencing the base image
* gce_instance:fedora : sys remote fedora-33 root host
  * PR #9592
    * [03-07 09:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4845264810803200/html/sys-remote-fedora-33-root-host.log.html)

## Podman rmi [It] podman image rm - concurrent with shared layers
* gce_instance:fedora : int remote fedora-33 root host
  * PR #9598
    * [03-03 17:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6135622575325184/html/int-remote-fedora-33-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--1)
    * [03-03 17:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6135622575325184/html/int-remote-fedora-33-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--2)
    * [03-03 17:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6135622575325184/html/int-remote-fedora-33-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--3)

## Podman run entrypoint [It] podman run no command, entrypoint, or cmd
* gce_instance:fedora : int remote fedora-33 root host
  * PR #9598
    * [03-03 17:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6135622575325184/html/int-remote-fedora-33-root-host.log.html#t--podman-run-no-command--entrypoint--or-cmd--1)

## Podman images [It] podman images filter since image
* gce_instance:fedora : int remote fedora-33 root host
  * PR #9598
    * [03-03 17:47](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6135622575325184/html/int-remote-fedora-33-root-host.log.html#t--podman-images-filter-since-image--1)

Of possible interest: a lot of failures in one specific test run. That suggests that maybe something happens on a particular system, such that once this triggers, more tests will also fail with the same problem?

**Comment by edsantiago** [comment]
## sys: podman build - does not gobble stdin that does not belong to it
* gce_instance:prior-ubuntu : sys remote ubuntu-2004 root host
  * PR #9627
    * [03-06 03:54](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6696900981161984/html/sys-remote-ubuntu-2004-root-host.log.html)

## sys: podman build --layers test
* gce_instance:fedora : sys remote fedora-33 root host
  * PR #9659
    * [03-08 10:30](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5981387749588992/html/sys-remote-fedora-33-root-host.log.html)
* gce_instance:prior-ubuntu : sys remote ubuntu-2004 root host
  * PR #9648
    * [03-07 08:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4619637364097024/html/sys-remote-ubuntu-2004-root-host.log.html)

**Comment by edsantiago** [comment]
Please. Please please please please, someone fix this.

## Podman rmi [It] podman rmi with cached images
* gce_instance:prior-ubuntu : int remote ubuntu-2004 root host
  * PR #9699
    * [03-11 17:50](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5550722788884480/html/int-remote-ubuntu-2004-root-host.log.html#t--podman-rmi-with-cached-images--1)

## Podman rmi [It] podman image rm - concurrent with shared layers
* gce_instance:prior-ubuntu : int remote ubuntu-2004 root host
  * PR #9699
    * [03-11 17:50](https://storage.googleapis.com/cirrus-ci-6707778565701632-fc
ae48/artifacts/containers/podman/5550722788884480/html/int-remote-ubuntu-2004-ro
ot-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--1)
    * [03-11 17:50](https://storage.googleapis.com/cirrus-ci-6707778565701632-fc
ae48/artifacts/containers/podman/5550722788884480/html/int-remote-ubuntu-2004-ro
ot-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--2)
    * [03-11 17:50](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5550722788884480/html/int-remote-ubuntu-2004-root-host.log.html#t--podman-image-rm---concurrent-with-shared-layers--3)

## sys: podman build --layers test
* gce_instance:prior-ubuntu : sys remote ubuntu-2004 root host
  * PR #9686
    * [03-10 09:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4627842328690688/html/sys-remote-ubuntu-2004-root-host.log.html)

## sys: build with copy-from referencing the base image
* gce_instance:fedora : sys remote fedora-33 root host
  * PR #9592
    * [03-07 09:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4845264810803200/html/sys-remote-fedora-33-root-host.log.html)

**Comment by vrothberg** [comment]
I bookmarked the issue and want to have a look at it this week.  If others are faster, I would not complain :)

**Comment by edsantiago** [comment]
I haven't seen this one since #9717 merged. Thanks, @nalind!
