### ISSUE TITLE
podman as root: Cannot connect to the Podman socket, make sure there is a Podman REST API service running

### ISSUE THREAD

**Issue by sebastian-philipp** [containers/podman#9382]
Hi folks, 

the Ceph CI got a new issue as of podman 3.0:

We're running this command as root:

```
$ /usr/bin/podman pull docker.io/ceph/ceph:v15
Error: Cannot connect to the Podman socket, make sure there is a Podman REST API service running.: failed to mount overlay for metacopy check with "nodev,metacopy=on" options: invalid argument
```

This this run:

http://qa-proxy.ceph.com/teuthology/yuriw-2021-02-12_16:01:06-rados:cephadm-wip-yuri2-testing-2021-02-08-1048-octopus-distro-basic-gibba/5877761/teuthology.log

Note that runnin `podman pull docker.io/ceph/ceph:v15` as root worked fine on the previous podman package

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Steps to reproduce the issue:**

1. install podman

2. run `podman pull docker.io/ceph/ceph:v15`

**Describe the results you received:**

```
$ /usr/bin/podman pull docker.io/ceph/ceph:v15
Error: Cannot connect to the Podman socket, make sure there is a Podman REST API service running.: failed to mount overlay for metacopy check with "nodev,metacopy=on" options: invalid argument
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman info --debug`:**

I wasn't able to get that information till now.

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

the log shows: `Setting up podman (100:3.0.0-1)`

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Comment by Luap99** [comment]
Dup of #9363
