### ISSUE TITLE
Files copied with 'podman cp' not available inside container when running systemd.

### ISSUE THREAD

**Issue by aressem** [containers/podman#9398]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. podman run --name copytest --detach --systemd always --entrypoint /sbin/init docker.io/centos:8
2. touch myfile
3. podman cp myfile copytest:/tmp
4. podman exec copytest /bin/ls /tmp
ks-script-esd4my7v  ks-script-eusq_sc5

**Describe the results you received:**
The file myfile is not available in /tmp inside the container

**Describe the results you expected:**
The file myfile should be available inside the container at /tmp or `podman cp ..` should give an error if this is not intended to work.

**Additional information you deem important (e.g. issue happens only occasionally):**
1. sudo podman cp myfile copytest:/root
2. sudo podman exec -ti copytest /bin/ls /root
anaconda-ks.cfg  anaconda-post.log  myfile  original-ks.cfg

Copy to /root folder works.

**Output of `podman version`:**

```
Version:      2.0.5
API Version:  1
Go Version:   go1.14.7
Built:        Wed Sep 23 16:18:02 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.1
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.20-2.module+el8.3.0+8221+97165c3f.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.20, commit: 77ce9fd1e61ea89bd6cdc621b07446dd9e80e5b6'
  cpus: 32
  distribution:
    distribution: '"rhel"'
    version: "8.3"
  eventLogger: file
  hostname: ##REDACTED##
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 100
      size: 1
    uidmap:
    - container_id: 0
      host_id: 93975
      size: 1
  kernel: 4.18.0-240.10.1.el8_3.x86_64
  linkmode: dynamic
  memFree: 54760775680
  memTotal: 67261603840
  ociRuntime:
    name: runc
    package: runc-1.0.0-68.rc92.module+el8.3.0+8221+97165c3f.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/user/93975/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-2.module+el8.3.0+8221+97165c3f.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 0
  swapTotal: 0
  uptime: 14h 25m 6.07s (Approximately 0.58 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/##REDACTED##/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-3.module+el8.3.0+8221+97165c3f.x86_64
      Version: |-
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/user/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/user/93975/containers
  volumePath: /home/##REDACTED##/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1600877882
  BuiltTime: Wed Sep 23 16:18:02 2020
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.0.5
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.5-5.module+el8.3.0+8221+97165c3f.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Troubleshooting yes, latest podman no. Using the latest available with Red Hat Enterprise Linux release 8.3 (Ootpa).

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical

**Comment by vrothberg** [comment]
Thanks for reaching out, @aressem!

I can reproduce on Podman v3.0.  The source of the issue is that `/tmp` is mounted as a tmpfs when running systemd in the container.  @rhatdan, do you concur?

I see that you're running on RHEL.  Please note that this is the upstream project.  If you want us to treat the issue with priority, please open a bug in the Red Hat channels.

**Comment by aressem** [comment]
Thanks @vrothberg. I have a workaround for the issue in my case (using another dir for copy), so this is not urgent. I just found this puzzling and wanted to bring it to your attention.

**Comment by vrothberg** [comment]
> Thanks @vrothberg. I have a workaround for the issue in my case (using another dir for copy), so this is not urgent. I just found this puzzling and wanted to bring it to your attention.

Thanks, I appreciate it!  Using another directory sounds like a good idea.

**Comment by mheon** [comment]
@vrothberg Suggest we add an error from copy code if we try to copy into a directory we can't handle - something mounted over by a filesystem like tmpfs or sysfs.

**Comment by vrothberg** [comment]
This has been fixed in the meantime. Thanks again for reaching out!
