### ISSUE TITLE
Arm64 Ubuntu 16.04 : Cannot set property PIDs, or unknown property.: OCI runtime error

### ISSUE THREAD

**Issue by lrodorigo** [containers/podman#9402]
/kind bug

**Description**
I am unable to start a single container on Ubuntu 16.04 Arm64 device (Nvidia TX2 board), .

**podman info**
```
root@host:~# podman info --debug
host:
  arch: arm64
  buildahVersion: 1.19.2
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: unknown'
  cpus: 6
  distribution:
    distribution: ubuntu
    version: "16.04"
  eventLogger: journald
  hostname: cube-2
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.4.197
  linkmode: dynamic
  memFree: 4078526464
  memTotal: 8236408832
  ociRuntime:
    name: runc
    package: Unknown
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc93
      spec: 1.0.2-dev
      go: go1.13.8
      libseccomp: 2.4.3
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 29h 25m 29.97s (Approximately 1.21 days)
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 11
    paused: 0
    running: 0
    stopped: 11
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1613474104
  BuiltTime: Tue Feb 16 11:15:04 2021
  GitCommit: ""
  GoVersion: go1.13.8
  OsArch: linux/arm64
  Version: 3.0.0

```
 
**Steps to reproduce the issue:**

1. Compile and install the above specified versions of podman, conmon, libseccomp and runc.

2. Try to run a simple container:
`podman run -it quay.io/prometheus/busybox-arm64v8-linux`

3.
```root@cube-2:~# podman run -it quay.io/prometheus/busybox-arm64v8-linux
Trying to pull quay.io/prometheus/busybox-arm64v8-linux:latest...
Getting image source signatures
Copying blob a3ed95caeb02 done  
....
Writing manifest to image destination
Storing signatures

WARN[0004] Failed to add conmon to systemd sandbox cgroup: Cannot set property PIDs, or unknown property. 

Error: OCI runtime error: container_linux.go:367: 
starting container process caused: process_linux.go:340: applying cgroup configuration for process caused: Cannot set property PIDs, or unknown property.
```

**Output of `podman version`:**

```
podman version 3.0.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

Built from source code on device

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Nvidia TX2 Ubuntu 16.04 Embedded Board

**Comment by mheon** [comment]
Can you try with the `crun` OCI runtime instead?

**Comment by baude** [comment]
I have to believe podman 3.0 wont work on ubuntu 16.10 ?

**Comment by lrodorigo** [comment]
@mheon I'm going to try it.
@baude Anyway I'm on Ubuntu 16.04... I hope it can run, in some way

**Comment by lrodorigo** [comment]
Latest version of crun does not compile on Ubuntu 16.04, picking up this specific commit https://github.com/containers/crun/commit/f67bd3e2d2b0d62a9ae2fc8f7e4bb686f3a7004f] (cited on this crun issue: https://github.com/containers/crun/issues/405 about Ubuntu 16.04), and building by using  `./configure --disable-systemd`  creates a working crun executable.

Using crun (with `--runtime` Podman option) instead of runc seems to solve the problem and **the container is correctly starting**.
I am going to do further steps to check if the solution is stable.

The following warning still remains:
```WARN[0000] Failed to add conmon to systemd sandbox cgroup: Cannot set property PIDs, or unknown property.```

**Comment by zhangguanzhang** [comment]
maybe your kernel doesn't enable pid namespace

**Comment by rhatdan** [comment]
The Warning is probably based on support not being available for that old systemd.  I am going to close this issue, since this is not an issue with Podman.  You can continue your conversation here if you would like.
