### ISSUE TITLE
Podman Tag Read Only Images

### ISSUE THREAD

**Issue by logan064** [containers/podman#9412]
/kind bug

**Description**

Podman can not tag images that are in an additional image store. This feels like a bug, but also possibly a feature request...
I am wondering if there is a way to tag an image in the additional image store and to have the image and new tag end up in the podman cache. Previously there was an issue with podman that would not allow pushing an image from the additional image store. This seems slightly related since a user may want to tag an image in the additional image store and push to a registry.

**Steps to reproduce the issue:**

1. Populate a directory with a image. For example, `mkdir /mnt/imgStore; podman load --root /mnt/imgStore busybox.tar`

2. List /mnt/imgStore in the additionalImageStore array found in /etc/containers/storage.conf.

3. `podman tag localhost/busybox:latest myregistry:5000/busybox:latest`

**Describe the results you received:**
Error: layer not known

**Describe the results you expected:**
No errors, podman images reflects the new tag, and `podman push myregistry:5000/busybox:latest` is successful

**Output of `podman version`:**

```
Version:          2.2.1
API Version:    2.1.0
Go Version:     go1.15.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.2.1-2.module_el8.4.0+581+8bd31022.x86_64.rpm
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical

**Comment by mheon** [comment]
Can you retry with Podman 3.0? I believe that @rhatdan may have resolved this.

**Comment by logan064** [comment]
I ran this snippet from, https://podman.io/getting-started/installation:
`git clone https://github.com/containers/podman/
cd podman
make BUILDTAGS="selinux seccomp"
sudo make install PREFIX=/usr`

This updated my version to:
`Version:      3.1.0-dev
API Version:  3.0.0
Go Version:   go1.14.13
Git Commit:   4aaaa6c1df3a1c90a930b97552bcc970d7d99dd4
Built:        Sat Feb 20 11:56:47 2021
OS/Arch:      linux/amd64`

Testing:
```
# podman images
REPOSITORY                     TAG     IMAGE ID      CREATED        SIZE     R/O
docker.io/library/registry     latest  678dfa38fcfa  2 months ago   26.8 MB  false
myregistry.io/registry         latest  678dfa38fcfa  2 months ago   26.8 MB  false
docker.io/library/centos       latest  300e315adb2f  2 months ago   217 MB   false
docker.io/cesanta/docker_auth  latest  9866a04a2227  11 months ago  17.5 MB  false
localhost:5000/busybox         latest  e7d168d7db45  6 years ago    2.65 MB  true
```

```
# podman tag localhost:5000/busybox:latest myregistry.io/busybox:latest
Error: layer not known
# podman run -it localhost:5000/busybox sh
/ #
```

Tagging read-only images with the latest version, podman 3, still results in Error: layer not known.
