### ISSUE TITLE
Podman not working with nfs users

### ISSUE THREAD

**Issue by joshbtay** [containers/podman#9416]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Our users' home directories are mounted on NFS shares. I created a local test user to try running an image and everything works fine, the container runs as expected. However, if I log in as a user whose home directory is on an NFS share, I get this error message:

```
$ podman run --rm -it rhel7.9
Error: error creating container storage: error creating read-write layer with ID 
"cb682b17769f21eaf8a9a240a886da15196a3b78771d8b36dd36689dc608c540":
potentially insufficient UIDs or GIDs available in user namespace (requested 65534:65534 for
/<NFS_SHARE>/<user>/.local/share/containers/storage/overlay/cb682b17769f21eaf8a9a240a886da15196a3b78771d8b36dd36689dc608c540):
Check /etc/subuid and /etc/subgid: chown
/<NFS_SHARE>/<user>/.local/share/containers/storage/overlay/cb682b17769f21eaf8a9a240a886da15196a3b78771d8b36dd36689dc608c540: invalid argument
```

I figured it had something to do with the NFS kernel not accepting the container's uid, so I tried to create a local directory for graphroot and runroot in /tmp/storage/<user> and /tmp/storage/<user>-tmp, respectively. 
However, with the edited storage configuration, I get the same error, but in a different place:

```
$ podman run --rm -it rhel7.9
Error: error creating container storage: error creating read-write layer with ID 
"7f58998004b05da99308ae2839c85994005a237019babd0d7fd5a401db80ea6f":
potentially insufficient UIDs or GIDs available in user namespace (requested 65534:65534 for 
/tmp/storage/<user>/overlay/7f58998004b05da99308ae2839c85994005a237019babd0d7fd5a401db80ea6f):
Check /etc/subuid and /etc/subgid: chown
/tmp/storage/<user>/overlay/7f58998004b05da99308ae2839c85994005a237019babd0d7fd5a401db80ea6f: invalid argument
```

**Additional Information**
Here are the contents of my user's storage.conf:
```
$ cat ~/.config/containers/storage.conf
[storage]
driver = "overlay"

runroot = "/tmp/storage/<user>-tmp"
graphroot = "/tmp/storage/<user>"

[storage.options]
additionalimagestores = [ "/var/lib/rootless/containers",]

[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
```
And here is the output of ls -la in /tmp/storage/
```
$ ls -la /tmp/storage/
total 24
drwxrwxrwt.  6 root   root   4096 Feb 16 15:16 .
drwxrwxrwt. 17 root   root   4096 Feb 17 12:33 ..
...
drwxrwxrwx. 10 <user> <user> 4096 Feb 17 10:54 <user>
drwxrwxrwx.  2 <user> <user> 4096 Feb 16 15:12 <user>-tmp
...
```

**Output of `podman version`:**

```
$ podman version
Version:      2.2.1
API Version:  2
Go Version:   go1.14.7
Built:        Mon Feb  8 14:19:06 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.22-3.module+el8.3.1+9857+68fb1526.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.22, commit: a40e3092dbe499ea1d85ab339caea023b74829b9'
  cpus: 6
  distribution:
    distribution: '"rhel"'
    version: "8.3"
  eventLogger: file
  hostname: ctb450-z1
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 4138
      size: 1
    - container_id: 1
      host_id: 10000
      size: 55537
    uidmap:
    - container_id: 0
      host_id: 1714
      size: 1
    - container_id: 1
      host_id: 10000
      size: 55537
  kernel: 4.18.0-240.15.1.el8_3.x86_64
  linkmode: dynamic
  memFree: 14786670592
  memTotal: 16570707968
  ociRuntime:
    name: runc
    package: runc-1.0.0-70.rc92.module+el8.3.1+9857+68fb1526.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /run/user/1714/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.3.1+9857+68fb1526.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 8359243776
  swapTotal: 8359243776
  uptime: 31m 8.3s
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /<NFS_SHARE>/<user>/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.imagestore: /var/lib/rootless/containers
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.3.0-2.module+el8.3.1+9857+68fb1526.x86_64
      Version: |-
        fusermount3 version: 3.2.1
        fuse-overlayfs: version 1.3
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /tmp/storage/<user>
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/user/1714/containers
  volumePath: /tmp/storage/<user>/volumes
version:
  APIVersion: "2"
  Built: 1612819146
  BuiltTime: Mon Feb  8 14:19:06 2021
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.2.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ rpm -q podman
podman-2.2.1-7.module+el8.3.1+9857+68fb1526.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

I haven't tried on the latest version of Podman because it doesn't seem to be available on the package manager and building from scratch did not work because the package manager was lacking many dependencies.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by rhatdan** [comment]
Not supported YET. https://github.com/containers/common/pull/457
We have a long term goal to support this, but it involves modifications to the NFS CLient and Server to support Xattrs. (Kernerl 5.11 has this support now, but it is not released).  Then we need fuse-overlay to support it, and then we can make sure it works.

For now this is documented as not supported so closing issue.

**Comment by joshbtay** [comment]
Ok, I can understand that nfs storage isn't supported yet, but that doesn't explain why even if I try to use local storage, it still throws the same error. /tmp/ is not on the nfs share

**Comment by rhatdan** [comment]
Could you try this with podman 3.0.  There was a bug in podman 2.2 which was not reading the storage.conf in the homedir correctly.

**Comment by joshbtay** [comment]
Ok, how can I get 3.0 on rhel 8? the repo only has 2.2 and there are a few missing dependencies that cause making from source to fail:
btrfs-progs-devel
device-mapper-devel
glibc-static
golang-github-cpuguy83-md2man
gpgme-devel
libassuan-devel
I tried installing the closest matches to these packages, but make still fails

**Comment by joshbtay** [comment]
OK I finally installed version 3.1 and I'm getting the same bug:
Error: error creating container storage: error creating read-write layer with ID "f8a556ecb022597b5895c8785780211e02000ff79921fa8ea1e8445ea71fac3d": there might not be enough IDs available in the namespace (requested 65534:65534 for /var/lib/rootless/storage/<user>/overlay/f8a556ecb022597b5895c8785780211e02000ff79921fa8ea1e8445ea71fac3d): chown /var/lib/rootless/storage/<user>/overlay/f8a556ecb022597b5895c8785780211e02000ff79921fa8ea1e8445ea71fac3d: invalid argument
