### ISSUE TITLE
Question: How to create rootless persitent volume outside of the home directory

### ISSUE THREAD

**Issue by polachz** [containers/podman#9424]
I'm trying to figure out how-to create podman rootless container persitent volume  outside of the user home directory. I'm going  to mount another disk to my  server and store all container persistent data here..

I can't find a way how to properly modify final destination for the 

`podman volume create <volume_name>`

for example 

`podman volume create -d local -o type=none -o o=bind -o device=/host/path volname`

doesn't work without root (as all mount tries)

I didn't find any useful piece of information how to reach what I want by this way.

Then I have tried another approach. I have created the volume

`podman volume create vol1`

it creates volume here:

_/home/user1/.local/share/containers/storage/volumes/vol1/_data_

Then i tried to move **vol1/_data** to my final location **/srv/vol1** and then create a link:

/home/user1/.local/share/containers/storage/volumes/vol1 --> /srv/vol1

But then I'm getting Permission Denied when I try to create any file inside volume mounted to the container.

But when I do not provide **"link magic"** and leave _data folder where is created by default then everything works smoothly and I'm able to create files inside the volume from the container without any problem

Can you please give me a hint how to correctly solve the problem? 

Thank yuou so much

**Comment by mheon** [comment]
May I ask why you're trying to do this? `podman volume create` is only intended to create Podman-managed volumes - Podman wants to manage the lifecycle and storage of these volumes. Is there a reason that a normal bind mount of the directory in question is not sufficient?

**Comment by polachz** [comment]
I'm trying to do that just because I guess that named volumes are right way how to make data persistent between container runs...  And I want to have persitent data separated from container images and instances due backup strategy. I can backup the mounted disk with persistent data by different way then disk with OS (all is virtualized)

Plus seeems that volumes created by

`podman volume create vol1`

doesn't need any special user rights handling. I just ceated volume, mount it to container and everything works!  All `podman unshare` magic is not necessary here. Seems that is provided automatically by right way...

All these advantages seems to  make my ansible deployment and maintenance tasks more easier I hope...

Anyway, if I'm wrong, what's a correct supported way how to make container data persistent by easy way? If my approach is wrong, I'll correct that. But I appreciate if I can use as easy as possible recipe to do that (avoid unshare if possible for example). But of course supported and recommended by podman team.

**Comment by rhatdan** [comment]
You should be able to set the volumes path for all containers in containers.conf
```
# List of volumes. Specified as
# If it is empty or commented out, no volumes will be added
# volumes = []
# Directory for libpod named volumes.
# volume_path = "/var/lib/containers/storage/volumes"
Change this in your containers.conf inside of homedir.
```

**Comment by polachz** [comment]
Hmm, I'm confused a little bit, because in man containers.conf and also in the  _/usr/share/containers/containers.conf_ I have found:

```
# List of volumes. Specified as
# "<directory-on-host>:<directory-in-container>:<options>", for example:
# "/db:/var/lib/db:ro".
# If it is empty or commented out, no volumes will be added
#
# volumes = []
```
but when i create file  _/home/user1/.config/containers/containers.conf_

```
volumes = []
"/srv/user1:/home/user1:rw".
```
I have got an error:

`ERRO[0000] error reading system config "/home/user1/.config/containers/containers.conf": unable to decode configuration /home/user1/.config/containers/containers.conf: Near line 2 (last key parsed '/srv/user1:/home/user1:rw'): expected key separator '=', but got '.' instead
`
You recommended completely different format of config file:
`volume_path = "/var/lib/containers/storage/volumes"`

But from the example is not clean volume name or container mount point.... 

Please, can you be more specific how to define a persistent volume inside the containers.conf file? 

Seems that official documentation is outdated :(

**Comment by polachz** [comment]
Additionally, I have found this issue: #7039

so I have created  /home/user1/.config/containers/containers.conf

with content:

```
volumes = []
# Directory for libpod named volumes.
volume_path="/srv/user1"
```

no change, volumes still creating at _/home/user1/.local/share/containers/storage/volumes/_

provide then `podman system reset`

It erased everything **INCLUDE!!!**  _/home/user1/.config/containers/containers.conf_ and folder  _/home/user1/.config/containers_

So I re-created the config file again and try to create new volume.

still created inside the;  _/home/user1/.local/share/containers/storage/volumes/_

I also tried run `podman system reset` as root

But no change. Unable to create a volume in my specified directory...

**Comment by rhatdan** [comment]
This is podman 3.0?

**Comment by polachz** [comment]
no, it's version 2.0.5 From Oracle Linux

**Comment by polachz** [comment]
Ok,after my "fight" with config files, I reach that my volumes are moved to ecpected folder and manual `podman unshare `is not necessary. So thank you a lot !

Just one question. Is possible to configure this volume_path variable universaly, from _/etc/containers/containers.conf_ ? 

Something like **/srv/volumes/$USER_NAME/** or simmilar ? 

Is possible to use any variables or placeholders here? 

Thank you.

**Comment by rhatdan** [comment]
Seems like a good requrest, we already do that for storage.conf. 
Sorry I went through and made the changes yesterday, and the issue I had was that the libpod database records the data once you have run a contianer and ignores the containers.conf settings from then on.  When I removed the libpod database, everything worked.

**Comment by polachz** [comment]
No problem with delay.  As I said, I have managed my containers working as I want :) 

But, about resetting the db: If you mean `podman system reset` then this command completely kill the **.config/containers** folder in my home directory.  All config files are gone and have to be re-created. (podman 2.0.5)

Maybe it's  a bug because I have found issue where you recommends this command and say that config files survive this. Then just FYI.

Anyway, I'm  able to store my volumes where I  want. Thank you for your help. 

Maybe the last question. Why write from container to volumes created by `podman volume create` is transparent without any issue  but when I provide explicit mapping by **-v /an/server/folder:/container/folder"**  (even with :Z) then I get permission denied inside the container. To solve this I have to use `podman unshare` over the **/an/server/folder**.  Seems that first run of the container do this automatically on `podman volume create` volumes but do not modify explicitly mapped folders....

**Comment by rhatdan** [comment]
If you are getting permission denied inside of your container on a volume mount of  -v /an/server/folder:/container/folder:Z then it most likely is not SELinux but could be user namespace.  Are you trying to access the content from a non root user.

**Comment by rhatdan** [comment]
This command is all you need to do to kill the database.  
rm -f ~/.local/share/containers/storage/libpod/bolt_state.db 

The issue with doing this, is all "containers" will be lost. So I would recommend you remove all pod's and containers before executing it.

Images should be fine.

Then the next podman info should hanlde the containers.conf properly.

**Comment by polachz** [comment]
> If you are getting permission denied inside of your container on a volume mount of -v /an/server/folder:/container/folder:Z then it most likely is not SELinux but could be user namespace. Are you trying to access the content from a non root user.

Tes, it''s really OID mapping issue. But what is interesting is, that it occurs only when I map folder explicitly. When i mapt he volume, it doesn't occur.

I can describe this better:

1. I try to run a container as non root user with oid 1000
2. i create volume by `podman volume create vol1`.
3. I create folder _/srv/storage_
4. when i check, then __data_ folder inside the vol1 has same rights and owner as _/srv/storage_ (1000:1000) and 644. **Rights and owner are identical.**

When i run a container with mapping vol1 to /home/step
```
podman run -it -v vol1:/home/step smallstep/step-ca sh
$ touch /home/step aaa

```
Then file aaa is correctly created. Plus _data folder inside the vol1 **has changed** owner Id to value  >65535.

But when I run a container with explicit mapping /srv/storage to /home/step
```
podman run -it -v /srv/storage:/home/step:Z smallstep/step-ca sh
$ touch /home/step aaa
```
Then file aaa is not created and **Permission Denied** error occurs. Owner of the _/srv/storage_ is **not changed**.

If i can allow to create the file i have to call  `podman unshare 1000:1000 /srv/storage` explicitly. Then I get here owner Id to value  >65535 ans then things work....

So, here is different behavior and depends on what kimd of volume is mapped.  One time is owner change provided under the hood, in second case it must be configured. 

So my question is why or what i do wrong in second case...

Hope now it' more clear...

**Comment by rhatdan** [comment]
This is working fine for me.
```
$ podman volume create foobar
$ podman run -v foobar:/tmp/dan ubi8 touch /tmp/dan/walsh
$ podman run -v foobar:/tmp/dan ubi8 ls -lZ /tmp/dan
-rw-r--r--. 1 root root system_u:object_r:container_file_t:s0 0 Feb 19 16:34 walsh
```
The command you executed
```
$ podman run -it -v /srv/storage:/home/step:Z smallstep/step-ca sh
$ touch /home/step aaa
```
Uses a volume mount and on the host do 
id; ls -ld /srv/storage 

What is your ID and what is the owner of the storage directory.  Are they different?

**Comment by polachz** [comment]
no, the user id is 1000: gid 1000, name user

owner of the /srv/storage

```
uid=1000(user) gid=1000(user) groups=1000(user) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
drwxr-xr-x. 2 user user 4096 Feb 18 16:16 /srv/storage

```
and after volume creation the _data
```
uid=1000(user) gid=1000(user) groups=1000(user) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
drwxr-xr-x. 2 user user 4096 Feb 19 18:05 /srv/volumes/vol1/_data

```
As i mentioned, it's completely same

**Comment by rhatdan** [comment]
And one of them gets permission denied?

**Comment by polachz** [comment]
Yes, when i use /srv/storage as /home/step mapping

This wrong sequence:
```
$podman run -it -v /srv/storage:/home/step:Z smallstep/step-ca sh
~ $ touch /home/step/aaa
touch: /home/step/aaa: Permission denied
```

**Comment by rhatdan** [comment]
$ podman run -it -v /srv/storage:/home/step:Z smallstep/step-ca sh
~ $ ls -l /home/step; id

**Comment by polachz** [comment]
```
ls -l /srv/; id
total 0
drwxr-xr-x. 2 labadmin labadmin 6 Feb 21 14:45 storage
uid=1000(labadmin) gid=1000(labadmin) groups=1000(labadmin),10(wheel) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
```

```
$ podman run -it -v /srv/storage:/home/step:Z smallstep/step-ca sh
~ $ ls -l /home/step; id
total 0
uid=1000(step) gid=1000(step) groups=1000(step)
```

```
$ podman unshare chown 1000:1000 /srv/storage
ls -l /srv; id
total 0
drwxr-xr-x. 2 100999 100999 6 Feb 21 14:48 storage
uid=1000(labadmin) gid=1000(labadmin) groups=1000(labadmin),10(wheel) context=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023
```

```
$ podman run -it -v /srv/storage:/home/step:Z smallstep/step-ca sh
~ $ touch /home/step/aaa
~ $ ls -l /home/step; id
total 0
-rw-r--r--    1 step     step             0 Feb 21 14:01 aaa
uid=1000(step) gid=1000(step) groups=1000(step)
```

**Comment by rhatdan** [comment]
So the problem seems to be the root inside of the container is UID=1000,  And you are attempting to run the container as UID=1000 INSIDE of the container.  But this UID is not the same as UID=1000 outside of the container.

If you want to fully map UID=1000-> Container UID=1000, then you have to use a special flag
podman run --userns=keep-id ...

```
man podman run
...
   --userns=auto|host|keep-id|container:id|ns:namespace
...
              • keep-id:  creates  a user namespace where the current rootless
                user's UID:GID are mapped to the same values in the container.
                This  option  is  ignored  for  containers created by the root
                user.
```
