### ISSUE TITLE
env-file has quoting problems

### ISSUE THREAD

**Issue by EvanCarroll** [containers/podman#9446]
I would like to configure my build script that creates the image, and the container with the same `.env` file. My build script uses shell which sources the env file like this,

```
set -o allexport
. ./.env
set +o allexport
```

A lot of image-building scripts I've created follow [that same method](https://stackoverflow.com/a/30969768/124486). Now I want to use that with `podman run` using the `--envfile` option. The problem there that the quotes aren't interpreted as they are with the shell,

    $ echo 'FOO="bar"' > .env

    $ source .env
    $ echo $FOO
    bar

    $ podman run --env-file ./.env alpine:3 sh -c "echo \$FOO"
    "bar"

I would expect both of those to be `bar` (no quotes).

**Comment by zhangguanzhang** [comment]
```
$ cat .env 
FOO="bar"
$ docker run --rm --env-file .env $IMG sh -c 'echo $FOO'
"bar"
```

**Comment by EvanCarroll** [comment]
@zhangguanzhang Are you confirming the problem? Isn't that I put in the question?

**Comment by zhangguanzhang** [comment]
docker has the same behavior

**Comment by vrothberg** [comment]
Thanks for reaching out, @EvanCarroll.  We aim at Docker compatibility where possible, so it's rather a feature than a bug :)  Please reopen in case Docker changes behavior.

**Comment by EvanCarroll** [comment]
@vrothberg confused, what are you being compatible with aside from shell, your breaking compatibility with all of these implementations of env file..

* [python](https://pypi.org/project/python-dotenv/)
* [rust](https://crates.io/crates/dotenv)
* [ruby](https://github.com/bkeepers/dotenv)
* [javascript](https://www.npmjs.com/package/dotenv)
* [r](https://cran.r-project.org/web/packages/dotenv/dotenv.pdf)
* [perl](https://metacpan.org/pod/Dotenv)

**Comment by mheon** [comment]
Podman is, first and foremost, compatible with Docker (except specific cases where we determine that Docker's behavior is a bug). Docker's parsing in this case is not compatible with the implementations you mentioned, and unfortunately this has been the case for at least five years - so we could easily be breaking existing Podman users relying on the current behavior. We could make an argument that this is a Docker bug, as I mentioned, but that's not something we do lightly - bug for bug compatibility is useful to many users.

**Comment by EvanCarroll** [comment]
oh shit, my bad I thought I was responding to the bug on docker. My bad all. Yes. this needs to be closed pending me getting Docker to change their insanity. Fully agree.

**Comment by EvanCarroll** [comment]
Linking issues: https://github.com/docker/for-linux/issues/1208
