### ISSUE TITLE
Podman docker-compose - enable service: "Failed to enable unit: Unit file start.service does not exist."

### ISSUE THREAD

**Issue by davidshumway** [containers/podman#9457]
Following this guide: https://www.redhat.com/sysadmin/podman-docker-compose. Installed podman, podman-docker, and docker-compose.

```bash
$ sudo systemctl enable --now start podman
Failed to enable unit: Unit file start.service does not exist.
```

```bash
uname -a
Linux localhost.localdomain 5.9.11-100.fc32.x86_64 #1 SMP Tue Nov 24 19:16:53 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
Is this because the author uses Fedora 33 and I'm using 32?

**Comment by afbjorklund** [comment]
I think it is some kind of confusion. Normally you do either/or, not both ?

```
sudo systemctl enable --now podman.socket
```

```
sudo systemctl enable podman.socket
sudo systemctl start podman.socket
```

I think the idea is that you "start" just the unix socket...
And then _it_ spawns the service, 5 seconds at a time ?

`/run/podman/podman.sock`

http://0pointer.de/blog/projects/socket-activation.html

**Comment by rhatdan** [comment]
Poman 3.0 is also not going to be released to F32, on f33 and later

**Comment by maxnatt** [comment]
@davidshumway this looks like a typo, the `--now` flag is already enough. Not sure where such errors are supposed to be reported though.

`systemctl enable --now podman.socket`

**Comment by skitoxe** [comment]
> @davidshumway this looks like a typo, the `--now` flag is already enough. Not sure where such errors are supposed to be reported though.
> 
> `# systemctl enable --now podman.socket`

Like Maxnatt states. That is indeed just an incorrect syntax.

**Comment by rhatdan** [comment]
I believe this is fixed in the current release.
