### ISSUE TITLE
podman-remote network create: race condition creating conflist file

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#9472]
The following sequence is starting to fail frequently in CI:
```console
# podman-remote network create a
# podman-remote network create b
# podman-remote run --network b something-something
Error: CNI network \"b\" not found"
         Error: error configuring network namespace for container X: CNI network "b" not found
```
I cannot reproduce it on my f33 laptop, possibly because it's faster than the CI VMs. What I can reproduce easily is:
```console
# ./bin/podman-remote network create b;./bin/podman-remote network rm b
```
and then, in the podman server window, I see:
```
ERRO[1299] Error loading CNI config list file /etc/cni/net.d/b.conflist: error reading /etc/cni/net.d/b.conflist: open /etc/cni/net.d/b.conflist: no such file or directory
```
(not 100% of the time, but about 25%)

master @ 6fbf73ed8bd34738f3f901df1e5d3b592a9c3354

## Podman network [It] podman network prune
* gce_instance:fedora : int remote fedora-33 root host
  * PR #9391
    * [02-16 05:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4742372631248896/html/int-remote-fedora-33-root-host.log.html#t--podman-network-prune--1)
    * [02-16 05:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4742372631248896/html/int-remote-fedora-33-root-host.log.html#t--podman-network-prune--2)
    * [02-16 05:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4742372631248896/html/int-remote-fedora-33-root-host.log.html#t--podman-network-prune--3)
  * PR #9348
    * [02-14 10:45](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6389174224814080/html/int-remote-fedora-33-root-host.log.html#t--podman-network-prune--1)
  * PR #9284
    * [02-09 15:24](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4531107414671360/html/int-remote-fedora-33-root-host.log.html#t--podman-network-prune--1)
    * [02-09 15:24](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4531107414671360/html/int-remote-fedora-33-root-host.log.html#t--podman-network-prune--2)
    * [02-09 15:24](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4531107414671360/html/int-remote-fedora-33-root-host.log.html#t--podman-network-prune--3)
    * [02-09 14:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5693393412030464/html/int-remote-fedora-33-root-host.log.html#t--podman-network-prune--1)
    * [02-09 14:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5693393412030464/html/int-remote-fedora-33-root-host.log.html#t--podman-network-prune--2)
    * [02-09 14:13](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5693393412030464/html/int-remote-fedora-33-root-host.log.html#t--podman-network-prune--3)
  * PR #9275
    * [02-21 06:02](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6004576143802368/html/int-remote-fedora-33-root-host.log.html#t--podman-network-prune--1)
    * [02-21 06:02](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6004576143802368/html/int-remote-fedora-33-root-host.log.html#t--podman-network-prune--2)
    * [02-21 06:02](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6004576143802368/html/int-remote-fedora-33-root-host.log.html#t--podman-network-prune--3)
    * [02-16 07:52](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6634276798070784/html/int-remote-fedora-33-root-host.log.html#t--podman-network-prune--1)
    * [02-16 07:52](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6634276798070784/html/int-remote-fedora-33-root-host.log.html#t--podman-network-prune--2)
* gce_instance:prior-fedora : int remote fedora-32 root host
  * PR #9428
    * [02-19 03:17](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6359148041338880/html/int-remote-fedora-32-root-host.log.html#t--podman-network-prune--1)
    * [02-19 03:17](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6359148041338880/html/int-remote-fedora-32-root-host.log.html#t--podman-network-prune--2)
    * [02-19 03:17](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6359148041338880/html/int-remote-fedora-32-root-host.log.html#t--podman-network-prune--3)
    * [02-18 13:27](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6497419346051072/html/int-remote-fedora-32-root-host.log.html#t--podman-network-prune--1)
    * [02-18 13:27](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6497419346051072/html/int-remote-fedora-32-root-host.log.html#t--podman-network-prune--2)
    * [02-18 13:27](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6497419346051072/html/int-remote-fedora-32-root-host.log.html#t--podman-network-prune--3)
  * PR #9406
    * [02-17 07:57](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5012611033989120/html/int-remote-fedora-32-root-host.log.html#t--podman-network-prune--1)
    * [02-17 07:57](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5012611033989120/html/int-remote-fedora-32-root-host.log.html#t--podman-network-prune--2)
    * [02-17 07:57](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5012611033989120/html/int-remote-fedora-32-root-host.log.html#t--podman-network-prune--3)
  * PR #9399
    * [02-16 09:37](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6111188036616192/html/int-remote-fedora-32-root-host.log.html#t--podman-network-prune--1)
    * [02-16 09:37](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6111188036616192/html/int-remote-fedora-32-root-host.log.html#t--podman-network-prune--2)
    * [02-16 09:37](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6111188036616192/html/int-remote-fedora-32-root-host.log.html#t--podman-network-prune--3)
  * PR #9301
    * [02-10 08:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6750954016997376/html/int-remote-fedora-32-root-host.log.html#t--podman-network-prune--1)
    * [02-10 08:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6750954016997376/html/int-remote-fedora-32-root-host.log.html#t--podman-network-prune--2)
    * [02-10 08:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6750954016997376/html/int-remote-fedora-32-root-host.log.html#t--podman-network-prune--3)
  * PR #9275
    * [02-16 07:53](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4593583216918528/html/int-remote-fedora-32-root-host.log.html#t--podman-network-prune--1)
  * PR #9269
    * [02-08 15:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4507996598304768/html/int-remote-fedora-32-root-host.log.html#t--podman-network-prune--1)
    * [02-08 15:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4507996598304768/html/int-remote-fedora-32-root-host.log.html#t--podman-network-prune--2)
    * [02-08 15:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4507996598304768/html/int-remote-fedora-32-root-host.log.html#t--podman-network-prune--3)

**Comment by Luap99** [comment]
@edsantiago I already chased that down see https://github.com/containers/podman/pull/9449 and https://github.com/cri-o/ocicni/pull/85

**Comment by edsantiago** [comment]
@Luap99 your fix LGTM, thank you!

**Comment by Luap99** [comment]
The bigger question is why it started to fail now and ubuntu works fine. The code did not changed.
