### ISSUE TITLE
Setting DOCKER_CONFIG leads to 20 line authfile log spam on INFO log level

### ISSUE THREAD

**Issue by Jaakkonen** [containers/podman#9473]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Having `DOCKER_CONFIG` environment variable set results to 20 lines of `INFO` log spam that's its being used for authfile path.
```INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker```

**Steps to reproduce the issue:**

1. `DOCKER_CONFIG=$HOME/.config/docker podman --version`

**Describe the results you received:**

```
INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker
INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker
INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker
INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker
INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker
INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker
INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker
INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker
INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker
INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker
INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker
INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker
INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker
INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker
INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker
INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker
INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker
INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker
INFO[0000] Using DOCKER_CONFIG environment variable for authfile path /home/user/.config/docker
podman version 3.0.1
```

**Describe the results you expected:**
```
podman version 3.0.1
```
Default log level to not include this log. And trace/debut log level to include the log only once.

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Environment variable `DOCKER_CONFIG=$HOME/.config/docker` set.

**Comment by Luap99** [comment]
I take a look

**Comment by Luap99** [comment]
@rhatdan PTAL
The problem is that we call `auth.GetDefaultAuthFile()` from c/common in the flag setup for many commands. Because init is run before we can parse the cli log level and configure logrus it will print everything. I don't see a easy solution other than removing the logrus call. WDYT?

**Comment by rhatdan** [comment]
Can we make it only log once?

**Comment by rhatdan** [comment]
Ok making it log once, makes it better, but still aggravating.  I say we remove the log message.
