### ISSUE TITLE
podman rm -fa with continers that have --rm should not throw errors

### ISSUE THREAD

**Issue by baude** [containers/podman#9479]
When you have containers that were created with --rm and you perform a rm -fa, there shouldn't be errors thrown that the container is missing (because it is stopped before deletion).

/kind bug

Reproducer:

````
$ sudo podman run -dt --rm alpine top
$ sudo podman rm -fa

```

**Comment by baude** [comment]
I'll grab this if nobody else does.

**Comment by vrothberg** [comment]
I'll take a look :^)

**Comment by vrothberg** [comment]
https://github.com/containers/podman/pull/9485
