### ISSUE TITLE
[RFE] bindings.NewConnection should implement a "retry"

### ISSUE THREAD

**Issue by cjeanneret** [containers/podman#9484]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
Hello there,
From time to time, when calling the ```bindings.NewConnection```, it fails because the socket is not temporary not available:
```
cannot connect to the Podman socket, please verify that Podman REST API service is running: Get "http://d/v2.0.0/libpod/_ping": dial unix /run/user/1000/podman/podman.sock: connect: no such fi
le or directory
```
When I re-run my app right after this failure, it's all green. If the NewConnection could implement a kind of retry with a configurable timeout (or number of retries), that would be really neat.
Of course, my own app could implement it - but maybe this could also interest other users.

Thank you!

Cheers,

C.

**Comment by vrothberg** [comment]
Thanks, @cjeanneret!

@jwhonce, would some kind of exponential back off make sense?

**Comment by cjeanneret** [comment]
In the meanwhile, I'm considering using some 3rd party retry lib, such as github.com/avast/retry-go
I'm already using it for another part in my code, so it's "ok". Still - apparently the podman socket seems to be flapping, so getting this as an embedded feature would be great :).

**Comment by rhatdan** [comment]
This issue is caused by mishandling of socket activation, I believe and I think we have a PR to fix this.
