### ISSUE TITLE
network connect should error if netmode is not bridge

### ISSUE THREAD

**Issue by Luap99** [containers/podman#9496]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Containers created with a network mode other than bridge should not work with network connect. (e.g. --network slirp4netns)

**Steps to reproduce the issue:**

1. `sudo bin/podman run --name test --network slirp4netns -d alpine top`

2. `sudo bin/podman network connect cni-podman3 test`
 This command actually works and connects to the cni network but does not keep it after a restart. Also inspect is broken with `asked to join 2 CNI network(s) [cni-podman3 podman], but have information on 1 network(s)`

In my opinion only bridge should be allowed and all other net modes must be rejected by network connect/disconnect.

**Comment by mheon** [comment]
Concur with disallowing for non-bridge network modes.

**Comment by baude** [comment]
also agree

**Comment by Luap99** [comment]
#9497 to fix
