### ISSUE TITLE
The Image remove compatibility endpoint's payload is incorrect.

### ISSUE THREAD

**Issue by jwhonce** [containers/podman#9499]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. `curl -v -X DELETE --unix-socket /run/user/1000/podman/podman.sock http://localhost/libpod/v1.35/images/fedora`

**Describe the results you received:**

```json
[
  {
    "deleted": "string",
    "untagged": []
  }
]
```
**Describe the results you expected:**

```json
[
  {
    "Untagged": "3e2f21a89f"
  },
  {
    "Deleted": "3e2f21a89f"
  },
  {
    "Deleted": "53b4f83ac9"
  }
]
```
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
greater than 2
```

**Comment by zhangguanzhang** [comment]
```
$ curl -X DELETE http://127.0.0.1:8081/v1.35/libpod/images/9617
{"Deleted":["961769676411f082461f9ef46626dd7a2d1e2b2a38e6a44364bcbecf51e66dd4"],"Untagged":["quay.io/libpod/alpine@sha256:fa93b01658e3a5a1686dc3ae55f170d8de487006fb53a28efcd12ab0710a2e5f"],"ExitCode":0,"Errors":[]}
```
seem has been fixed.
/close
