### ISSUE TITLE
No way to control /etc/hosts in podman play kube

### ISSUE THREAD

**Issue by gcs278** [containers/podman#9500]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman play kube does not have YAML or runtime options to set `--no-hosts` (like `podman pod create`). Therefore, it always the same /etc/hosts as the host, even if you have isolated (non-host) networking. Kubernetes does not shared the /etc/hosts file by default.

This is a problem for me since I need to isolate the /etc/hosts file and have no way to control it.

**Steps to reproduce the issue:**

1. podman play kube <YAML>

**Describe the results you received:**

POD Containers always has /etc/hosts from the host

**Describe the results you expected:**

Ability to control whether /etc/hosts is the same as the host's /etc/hosts

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      2.2.1
API Version:  2
Go Version:   go1.14.7
Built:        Mon Feb  8 16:19:06 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.21-3.module_el8.4.0+581+8bd31022.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.21, commit: 4cff974a37907e701aa2e31ad480ccc6f3f586f5'
  cpus: 10
  distribution:
    distribution: '"rhel"'
    version: "8.2"
  eventLogger: file
  hostname: rhel82
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-193.el8.x86_64
  linkmode: dynamic
  memFree: 1504854016
  memTotal: 3884625920
  ociRuntime:
    name: runc
    package: runc-1.0.0-65.rc10.module+el8.2.0+5762+aaee29fb.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.1-dev'
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  rootless: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 3776471040
  swapTotal: 4190105600
  uptime: 2195h 35m 53.54s (Approximately 91.46 days)
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 11
    paused: 0
    running: 5
    stopped: 6
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 12
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: "2"
  Built: 1612819146
  BuiltTime: Mon Feb  8 16:19:06 2021
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 2.2.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.2.1-7.module+el8.3.1+9857+68fb1526.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
So should the infra container default to --nohost

**Comment by rhatdan** [comment]
@haircommander WDYT?

**Comment by haircommander** [comment]
infra container should have `--nohost` if we're not using hostNetworking in the pod YAML

**Comment by gcs278** [comment]
I see a `no_hosts` parameter in the containers.conf, but I've tried it multiple times and podman play kube and podman run, and it doesn't seem to change anything. 

Can you guys think of a work around for the time being?

**Comment by gcs278** [comment]
Okay so that commit seems like it fixed the `no_hosts` in container.conf problem, but has the problem of not being able to control the /etc/hosts file from `podman play kube` been addressed?

Not sure if I agree this should be closed yet - seems like we fixed an accessory problem, but not the root cause.

**Comment by mheon** [comment]
Concur, reopening

**Comment by flouthoc** [comment]
@gcs278 Just curious how are you planning to populate this with relevant entries? Are you planning to bake `/etc/host` in image ? or plan to populate via `hostAliases` ?
