### ISSUE TITLE
`podman stats` shows the same values for every container in a pod

### ISSUE THREAD

**Issue by ahwayakchih** [containers/podman#9502]
/kind feature

**Description**

Sorry if i'm writing something stupid, but i'm new to cgroup stuff. I'm marking this as a `feature`, because i'm not sure if it's a bug or just my faulty configuration/setup.

On Alpine Linux (running inside QEmu-KVM) with OpenRC init system, running with cgroupfs as a manager, `podman stats` (and `podman pod stats`) show the same values for all the containers in a pod.

Is it possible that's because no cgroup subgroups are created per container there? They all seem to use the same cgroup path as pod. If so, could you point me to some information that will help me fix the issue? Should i create subgroups manually and move containers there?

**Steps to reproduce the issue:**

1. `podman pod create --name test`

2. `podman run -d --pod test --name test-loop alpine /bin/sh -c 'while true; do sleep 1; done'`

3. `podman pod stats test --no-stream`

**Describe the results you received:**

```txt
POD           CID           NAME                CPU %  MEM USAGE/ LIMIT  MEM %  NET IO   BLOCK IO  PIDS
124ccba95348  b551774961ac  124ccba95348-infra  8.12%  42.7MB / 4.134GB  1.03%  -- / --  -- / --   30
124ccba95348  fec58440c382  test-loop           8.12%  42.7MB / 4.134GB  1.03%  -- / --  -- / --   30
```

That's just a test. Same happens with pod that has 4 or more containers, including over 1GB PostgreSQL database, NodeBB and NGINX containers (so there's not much chance for every one of them to take exactly the same amount of RAM and CPU as the others).

**Describe the results you expected:**

```txt
POD           CID           NAME                CPU %  MEM USAGE/ LIMIT   MEM %  NET IO   BLOCK IO  PIDS
3c36e10a2561  fc252894342c  test-loop           1.70%  1.655MB / 10.32GB  0.02%  -- / --  -- / --   2
3c36e10a2561  063090a3d08c  3c36e10a2561-infra  2.58%  766kB / 10.32GB    0.01%  -- / --  -- / --   1
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I tried changing containers.conf, just in case, to make sure that cgroups are set to private, but that did not change anything.

I noticed that running pod on Arch with systemd, `podman stats` shows different values per container.
Alpine uses cgroupfs, Arch uses systemd.

When i checked `/sys/fs/cgroup/`, there was just a podname subdirectory there, with no subsubdirectories on Alpine. On Arch there is a bit scary subdirectory structure there with "endpoints" (deepest subdirectories) per container.

**Output of `podman version`:**

```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.16
Git Commit:   d048e65256dabad226b435c3f5811f6d34e335d4
Built:        Fri Feb 19 21:49:20 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: cgroupfs
  cgroupVersion: v2
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: a2be3362195c4f94c68cd2d250db5b27e37b3614'
  cpus: 2
  distribution:
    distribution: alpine
    version: 3.14.0_alpha20210212
  eventLogger: file
  hostname: localhost
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 10000
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 10000
  kernel: 5.10.17-0-virt
  linkmode: dynamic
  memFree: 3295375360
  memTotal: 4134473728
  ociRuntime:
    name: crun
    package: Unknown
    path: /usr/bin/crun
    version: |-
      crun version 0.18
      commit: 808420efe3dc2b44d6db9f1a3fac8361dde42a95
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /tmp/podman-run-1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: Unknown
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 2684350464
  swapTotal: 2684350464
  uptime: 8m 45.99s
registries:
  search:
  - docker.io
store:
  configFile: /home/me/.config/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 4
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: Unknown
      Version: |-
        fuse-overlayfs: version 1.4
        fusermount3 version: 3.10.2
        FUSE library version 3.10.2
        using FUSE kernel interface version 7.31
  graphRoot: /home/me/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 11
  runRoot: /tmp/podman-run-1000/containers
  volumePath: /home/me/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1613767760
  BuiltTime: Fri Feb 19 21:49:20 2021
  GitCommit: d048e65256dabad226b435c3f5811f6d34e335d4
  GoVersion: go1.16
  OsArch: linux/amd64
  Version: 3.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

`apk info podman`

```
podman-3.0.1-r0 description:
Simple management tool for pods, containers, and images

podman-3.0.1-r0 webpage:
https://podman.io/

podman-3.0.1-r0 installed size:
42 MiB
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

QEmu-KVM

**Comment by rhatdan** [comment]
I believe all containers within a pod share the same cgroups so this is expected.

@giuseppe @haircommander @mheon  Correct?

**Comment by mheon** [comment]
We have an outer cgroup for the pod, but each container in the pod has its own cgroup (that is a child of the pod cgroup).

**Comment by mheon** [comment]
I presume that means we should be getting per-container stats?

**Comment by ahwayakchih** [comment]
@mheon i do get per-container stats on Arch with systemd, which seems correct (the expected result i mentioned is from real test running there).

On Alpine with OpenRC i get only the same sum values (i presume), shown with each container on stats list.

On Alpine i have `/sys/fs/cgroup/test/`, on Arch path is a lot more complicated, but it looks like there is a separate directory per container, e.g., `/sys/fs/cgroup/.../user-libpod_pod_[pod SHA?].slice/libpod-[container-SHA?].scope/`

**Comment by ahwayakchih** [comment]
Looks like on Alpine i had test cgroup only because i added service that was starting the pod after system boot. Adding another pod did not create cgroup.

After removing pod that i just created, started and stopped (single container with crond -f) i got this:

```
WARN[0000] Error updating pod 3d080e7a0d70c93423aae052955efdafa3c3bb98d38cda811c6b254dd7a5aee7 conmon cgroup PID limit: open /sys/fs/cgroup/libpod_parent/3d080e7a0d70c93423aae052955efdafa3c3bb98d38cda811c6b254dd7a5aee7/conmon/pids.max: no such file or directory 
```

Indeed, there was no such thing as `/sys/fs/cgroup/libpod_parent`.

**Comment by ahwayakchih** [comment]
After trying `podman pod create --log-level debug --name test` debug log was quite big (let me know, if i should paste whole thing), but there this:

```txt
Got pod cgroup as /libpod_parent/196e78ccd0be830e46f9e96278305c674255f0a00cc277f5f933fe3cd031be24
```

but `su -c 'ls -la /sys/fs/cgroup'` shows no such thing:

```txt
dr-xr-xr-x    4 root     root             0 Feb 24 22:04 .
drwxr-xr-x    7 root     root             0 Feb 24 22:04 ..
-r--r--r--    1 root     root             0 Feb 24 22:04 cgroup.controllers
-rw-r--r--    1 root     root             0 Feb 24 22:04 cgroup.max.depth
-rw-r--r--    1 root     root             0 Feb 24 22:04 cgroup.max.descendants
-rw-r--r--    1 root     root             0 Feb 24 22:04 cgroup.procs
-r--r--r--    1 root     root             0 Feb 24 22:04 cgroup.stat
-rw-r--r--    1 root     root             0 Feb 24 22:04 cgroup.subtree_control
-rw-r--r--    1 root     root             0 Feb 24 22:04 cgroup.threads
-r--r--r--    1 root     root             0 Feb 24 22:04 cpu.stat
-r--r--r--    1 root     root             0 Feb 24 22:04 cpuset.cpus.effective
-r--r--r--    1 root     root             0 Feb 24 22:04 cpuset.mems.effective
-r--r--r--    1 root     root             0 Feb 24 22:04 io.stat
-r--r--r--    1 root     root             0 Feb 24 22:04 memory.stat
drwxr-xr-x    2 root     root             0 Feb 24 22:04 podman
drwxr-xr-x    2 root     root             0 Feb 24 22:04 sshd
```

**Comment by ahwayakchih** [comment]
I created, as root, /sys/fs/cgroup/test, chown it to user, and then created pod with `--cgroup-parent` set to test. A subpath for pod was created. So looks like this part is a matter of permissions maybe?

After adding containers there are subsubpaths created for each container, but `podman stats` and `podman pod stats` keep showing copies of values for each of the containers in the pod anyway :(.

**Comment by giuseppe** [comment]
we don't support cgroupfs for rootless users.  It might work if you configure the cgroup manually but it was never really tested

**Comment by ahwayakchih** [comment]
@giuseppe Thanks.
