### ISSUE TITLE
rawhide: podman diff of buildah container: error creating overlay mount

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#9507]
Podman fedora gating tests are [failing](http://artifacts.dev.testing-farm.io/e9ebe658-2987-4106-b21e-ec4a1408a2b8/work-tests.ymlo_U20O/tests-LmDMML/test.podman-root-cgroupsv2.bats.log) in one of the `diff` tests.

Simplest reproducer:
```console
# buildah from --name foo quay.io/libpod/alpine:latest
...
# buildah run foo sh -c 'touch /newfile'
# podman diff foo
ERRO[0000] error unmounting /var/lib/containers/storage/overlay/3027f967eb6b2ddf9ceebce0100d00d5109e47895d0fe837a97396287d5b314e/merged: invalid argument
Error: error creating overlay mount to /var/lib/containers/storage/overlay/3027f967eb6b2ddf9ceebce0100d00d5109e47895d0fe837a97396287d5b314e/merged: invalid argument
```

podman-3.1.0-0.48.dev.gitdec06b1.fc35 on kernel 5.12.0-0.rc0.20210222git31caf8b2a847.158.fc35 (don't bother trying on any 5.11 kernel, those are all completely b0rked). This is 100% reliable, fails every time. I cannot reproduce on f33.

The failing test was added 2020-10-19 by @rhatdan in PR #7908

**Comment by rhatdan** [comment]
@giuseppe I think this could be the new volatile flag?

**Comment by giuseppe** [comment]
my bad, I introduced the issue with the support for "volatile".

I've opened a PR to address it: https://github.com/containers/storage/pull/840

**Comment by edsantiago** [comment]
Still seeing this in [rawhide gating tests](http://artifacts.dev.testing-farm.io/0218fa2f-1ed1-4677-ab8d-ad48dc7ed606/work-tests.ymlKHBbwZ/tests-XzopDu/test.podman-root-cgroupsv2.bats.log). Can we get this vendored into podman?

**Comment by giuseppe** [comment]
we need to cut a new release of containers/storage

**Comment by rhatdan** [comment]
https://github.com/containers/storage/releases/tag/v1.28.0
