### ISSUE TITLE
RFC: CI rootless ubuntu tests

### ISSUE THREAD

**Issue by Luap99** [containers/podman#9508]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**
Is there a reason why rootless is only tested on fedora? I think it would help to also test rootless ubuntu when working on PRs like #9423 for example.

**Comment by rhatdan** [comment]
No reason not to, other them time of tests.  Ubuntu tests are slow, but hopefully upstream is fixing this.

**Comment by rhatdan** [comment]
@cevich PTAL

**Comment by cevich** [comment]
> No reason not to, other them time of tests. Ubuntu tests are slow, but hopefully upstream is fixing this.

In fact it would be tested in parallel so might not add much to the overall time.  Of course, we have ***SO*** many tasks now, we do run into queuing/throttling.  It's also "one more thing that could break", so we decided to not test it.  But @rhatdan is correct, there's no actual technical reason why we can't.  I'll put together a PR (it's a simple change) and let's see how it goes...

**Comment by cevich** [comment]
Blocked by #9997
