### ISSUE TITLE
[APIv3] /build endpoint wrongly assumes the labels parameter is a list

### ISSUE THREAD

**Issue by riyad** [containers/podman#9517]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Trying to find regressions by exercising the APIv2 trough [docker-py](https://github.com/docker/docker-py)'s test suite (see #5386) I came across a bug via the [`BuildTest::test_build_labels`](https://github.com/docker/docker-py/blob/master/tests/integration/api_build_test.py#L200) test.

The `/build` endpoint allows to specify a set of labels with corresponding values. Podman (and by extension Buildah) wrongly assume labels are a list of strings where it should be a mapping string -> string.

In the words of the [Docker API docs](https://docs.docker.com/engine/api/v1.40/#operation/ImageBuild) the `labels` parameter should be an "arbitrary key/value labels to set on the image, as a JSON map of string pairs".

**Steps to reproduce the issue:**

1.
```shell
cat > Dockerfile <<EOF
FROM scratch
CMD sh -c "echo \'something\'
EOF
```

2. `tar cf test.tar Dockerfile`

3. URL encode a (flat) JSON object (e.g. with https://www.urlencoder.org/) and use it for the `labels` parameter:
```json
{
  "test 1": "OK",
  "test 2": "also"
}
```
4. `curl -sS --unix-socket /var/run/user/1000/podman/podman.sock -XPOST 'http://localhost/v1.40/build?labels=%7B%0A%20%20%22test%201%22%3A%20%22OK%22%2C%0A%20%20%22test%202%22%3A%20%22also%22%0A%7D'  -H "Content-Type: application/tar" --data-binary '@test.tar'`

**Describe the results you received:**

Using a JSON object for `labels` fails with:
```
400 Bad Request
{"cause":"json: cannot unmarshal object into Go value of type []string","message":"failed to parse query parameter 'labels': \"{\\n  \\\"test 1\\\": \\\"OK\\\",\\n  \\\"test 2\\\": \\\"also\\\"\\n}\": json: cannot unmarshal object into Go value of type []string","response":400}
```

**Describe the results you expected:**

The image should build and the assigned labels should be visible via `podman image inspect aa74af768cd | jq '.[] | .Config.Labels'`

**Additional information you deem important (e.g. issue happens only occasionally):**

The error starts by failing to correctly parse the URL parameter as a JSON object:

https://github.com/containers/podman/blob/master/pkg/api/handlers/compat/images_build.go#L222

Changing the line to `var labels = map[string]string{}` fails to compile because Buildah expects this to be a list as well:

https://github.com/containers/buildah/blob/master/imagebuildah/build.go#L147

**Comment by mheon** [comment]
@rhatdan @baude @jwhonce This is another tricky case - I think we need to retain the `[]string` to not cause an API change, but we also need to accept maps for Docker-compat

**Comment by baude** [comment]
i dont, it's a bug ...

**Comment by rhatdan** [comment]
I agree it's a bug.
