### ISSUE TITLE
swagger type mismatch for the /version endpoint

### ISSUE THREAD

**Issue by TristanCacqueray** [containers/podman#9522]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The documentation http://docs.podman.io/en/latest/_static/api.html#operation/SystemVersion indicates the `/libpod/version` endpoint should returns a `{ Client, Server }` object, but the actual response is different.

**Steps to reproduce the issue:**

1. Query the `/libpod/version` endpoint

**Describe the results you received:**

The endpoint seems to return this object: https://github.com/containers/podman/blob/master/pkg/api/handlers/compat/version.go#L34, e.g.: 

```json
{
    "Platform": {
        "Name": "linux/amd64/fedora-32"
    },
    "Components": [{"Name": "Podman Engine", "..."}],
    "ApiVersion": "1.40",
    "..."
}
```

**Describe the results you expected:**

The endpoint should have return the documented `#/responses/Version` swagger ref, e.g.:

```json
{ "Server": { "APIVersion": "..." } }
```

**Comment by mheon** [comment]
@jwhonce PTAL

**Comment by rhatdan** [comment]
@TristanCacqueray Interested in opening a PR to fix?
