### ISSUE TITLE
Issue with Docker-Compose with Podman 3.0.1

### ISSUE THREAD

**Issue by BobyMCbobs** [containers/podman#9534]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Docker-Compose fails to bring up Podman containers with Podman socket running.

**Steps to reproduce the issue:**

1. `sudo systemctl enable --now start podman.socket`

2. `sudo docker-compose -f path/to/docker-compose.yml up`

**Describe the results you received:**

```
OCI runtime create failed: this version of runc doesn't work on cgroups v2: unknown
```

**Describe the results you expected:**

The container to come up and be live.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens everytime.

**Output of `podman version`:**

```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.8
Built:        Sat Feb 20 05:56:17 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.26-1.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 777074ecdb5e883b9bec233f3630c5e7fa37d521'
  cpus: 8
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: atlaslt
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.18-200.fc33.x86_64
  linkmode: dynamic
  memFree: 2294075392
  memTotal: 16489594880
  ociRuntime:
    name: crun
    package: crun-0.17-1.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.fc33.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 12612263936
  swapTotal: 12612263936
  uptime: 1h 7m 52s (Approximately 0.04 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /var/home/caleb/.config/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 1
    stopped: 4
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.4.0-1.fc33.x86_64
      Version: |-
        fusermount3 version: 3.9.3
        fuse-overlayfs: version 1.4
        FUSE library version 3.9.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/caleb/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 238
  runRoot: /run/user/1000
  volumePath: /home/caleb/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1613753777
  BuiltTime: Sat Feb 20 05:56:17 2021
  GitCommit: ""
  GoVersion: go1.15.8
  OsArch: linux/amd64
  Version: 3.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
🐚 rpm -q podman
podman-3.0.1-1.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Fedora Silverblue 33 on real hardware.
Docker-Compose version:
```
docker-compose version 1.28.5, build c4eb3a1f
docker-py version: 4.4.4
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Comment by Luap99** [comment]
Does your compose file contains a build step?

**Comment by BobyMCbobs** [comment]
> Does your compose file contains a build step?

There's no build stage.

Here's the compose file for context:

```yaml
version: "3.7"

services:
  flattrack_db:
    image: postgres:12.2-alpine
    restart: unless-stopped
    user: postgres
    ports:
      - '5432:5432'
    environment:
      - TZ=Pacific/Auckland
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATABASE=postgres
      - PGUSER=postgres
```

**Comment by baude** [comment]
I assume rootfull containers run without issue?  And also,  it looks like runc is being used in a cgroups v2 environment.  sometimes that is a red herring for an error but perhaps there is something unique about your environment of config files?

**Comment by BobyMCbobs** [comment]
> I assume rootfull containers run without issue? And also, it looks like runc is being used in a cgroups v2 environment. sometimes that is a red herring for an error but perhaps there is something unique about your environment of config files?

Rootful containers run fine in Podman - this error doesn't occur with `sudo podman run -it --rm -p 80:80 nginx:stable` for example.

Could it be `Docker-Compose` some how configuring the runtime?

**Comment by baude** [comment]
I don't think so.  Is this a brand new install or did you have older versions of podman on this system.  Like stuff back to 1.x.

**Comment by BobyMCbobs** [comment]
> I don't think so. Is this a brand new install or did you have older versions of podman on this system. Like stuff back to 1.x.

There were older versions. I've had this install since Fedora Silverblue 31.

**Comment by baude** [comment]
@BobyMCbobs any chance that your configuration file might be hard coding runc? i.e. /etc/containers/libpod.conf or containers.conf?  on fedora, the original sits in /usr/share/containers ... if you have one in /etc/containers/, maybe rename it and see if you get further?

**Comment by BobyMCbobs** [comment]
Both _libpod.conf_ and _containers.conf_ don't exist in _/etc/containers_. Copying _/usr/share/containers/containers.conf_ to _/etc/containers_ didn't seem to change anything

**Comment by baude** [comment]
ok, one more thing to try,rename runc to something else for now and try again?

**Comment by mheon** [comment]
Can you also do a `podman inspect` on a container made by `docker-compose` and provide the output?

**Comment by mheon** [comment]
`podman info` is showing the correct default runtime, which makes me very curious.

**Comment by BobyMCbobs** [comment]
> Can you also do a `podman inspect` on a container made by `docker-compose` and provide the output?

According to `sudo podman ps -a` after bringing the stack up, no containers appear.

**Comment by mheon** [comment]
Can you make containers with `podman run`? Do they work?

**Comment by BobyMCbobs** [comment]
`sudo podman run -it --rm -p 80:80 --name nginx nginx:stable` works fine.
The _OCIRuntime_ is set to _crun_ according to `sudo podman inspect nginx | jq -r '.[0].OCIRuntime'`

**Comment by baude** [comment]
@BobyMCbobs ok here's something to try. stop your sevice and socket . then in one terminal, do a  `sudo podman --log-level=debug system service -t0 unix://var/run/docker.sock`.  Then in another, run your compose...does this work ?

**Comment by BobyMCbobs** [comment]
> @BobyMCbobs ok here's something to try. stop your sevice and socket . then in one terminal, do a `sudo podman --log-level=debug system service -t0 unix://var/run/docker.sock`. Then in another, run your compose...does this work ?

@baude, this appears to do it. This is good. The container comes up as expected.

**Comment by baude** [comment]
Is there any chance you might have two different binaries of podman on your system?  or that the socket files are old?

**Comment by BobyMCbobs** [comment]
> Is there any chance you might have two different binaries of podman on your system? or that the socket files are old?

Both my user and root are using the same version.

The socket file looks like this
```ini
[Unit]
Description=Podman API Socket
Documentation=man:podman-system-service(1)

[Socket]
ListenStream=%t/podman/podman.sock
SocketMode=0660

[Install]
WantedBy=sockets.target
```
and seems pretty normal to me.

**Comment by c-goes** [comment]
I tried using docker-compose on Ubuntu 20.04 using kubic packages. Problem is the path `/var/run/docker.sock` does not exist. There is only `/var/run/podman/podman.sock`. Is this expected? What file do I need to change to make the socket on the correct path for docker-compose?

**Comment by c-goes** [comment]
I found how to make the socket (maybe) work.

podman.socket
```
[Unit]
Description=Podman API Socket
Documentation=man:podman-system-service(1)

[Socket]
ListenStream=%t/docker.sock
SocketMode=0660

[Install]
WantedBy=sockets.target
```

podman.service
```
[Unit]
Description=Podman API Service
Requires=podman.socket
After=podman.socket
Documentation=man:podman-system-service(1)
StartLimitIntervalSec=0

[Service]
Type=exec
KillMode=process
Environment=LOGGING="--log-level=info"
ExecStart=/usr/bin/podman $LOGGING system service -t0 unix://var/run/docker.sock
```

And have docker-compose working. But do these changes stay after an APT upgrade?

**Comment by mheon** [comment]
Can you show what the difference is between your current unit files and the originals? We could look into doing this upstream if it's a solution

**Comment by c-goes** [comment]
`ListenStream=%t/podman/podman.sock`
I changed to
`ListenStream=%t/docker.sock`


`ExecStart=/usr/bin/podman $LOGGING system service`
I changed to
`ExecStart=/usr/bin/podman $LOGGING system service unix://var/run/docker.sock`

**Comment by c-goes** [comment]
I found that in Fedora 33 there is a package `podman-docker` available that installs a symlink /run/docker.sock -> /run/podman/podman.sock
This is the reason it works there but not in Ubuntu. In Kubic/Ubuntu there is no package with this name.

**Comment by rhatdan** [comment]
@lsm5 ^^

**Comment by SvenMarquardt5772** [comment]
The missing socket is also a problem in opensuse. The unitfile is missing the docker.socket entry and creates a podman socket under /var/run. Is this something the packager should take care off? There is also no podman-docker package.

**Comment by rhatdan** [comment]
opensuse should ship a podman-docker package. Open up a bug with the distribution.
DOCKER_HOST environment variable is the other mechanism for this ot create a link between /run/docker.sock and /run/podman/podman.sock.

**Comment by baude** [comment]
I'm going to close this as it is the responsibility of the distributions to handle their packaging.  @lsm5 did you fix the kubic ubuntu packages?

**Comment by c-goes** [comment]
Still no podman-docker package in kubic/Ubuntu.

In official Debian experimental repo there is now podman-docker package but this won't install a symlink.

**Comment by Kiritow** [comment]
Try download the `podman-docker` deb package and install it manually.

```bash
curl -v http://mirrors.cloud.tencent.com/ubuntu/pool/universe/libp/libpod/podman-docker_3.2.1+ds1-2ubuntu2_amd64.deb -O
sudo dpkg -i podman-docker_3.2.1+ds1-2ubuntu2_amd64.deb
sudo systemctl restart podman && sudo systemctl restart podman.socket
```

*Tested on Ubuntu Server 20.04.2 LTS*
