### ISSUE TITLE
podman --connection not working on macOS (failed to resolve active destination: service destination not found)

### ISSUE THREAD

**Issue by christian-korneck** [containers/podman#9535]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

running `podman --remote --connection <connection-string> <some-command>` with the Podman MacOS client errors with `Error: failed to resolve active destination: "<connection-string>" service destination not found`

**Steps to reproduce the issue:**

Server(s): Podman 3.0.1 on Fedora 33 ([prepared](https://www.redhat.com/sysadmin/podman-clients-macos-windows) for remoting)
Client: Podman 3.0.1 on MacOS 11.2.2 x86_64 (installed via homebrew) 

On the Mac client:

1. create two connections:
```
$ podman system connection add conA --identity /Users/myuser/.ssh/podman_rsa ssh://root@servA/run/user/0/podman/podman.sock
$ podman system connection add conB --identity /Users/myuser/.ssh/podman_rsa ssh://root@servB/run/user/0/podman/podman.sock
$ podman system connection default conA
```

2. default connection works (without `--connection`):

```
$ podman --remote info
...
hostname: servA
...
```

3.  trying to use same connection with `--connection <connection-string>` fails:

```
$ podman --remote --connection conA info
Error: failed to resolve active destination: "conA" service destination not found
```

(same for the other connection, also same without `--remote`)

**Describe the results you received:**

```
$ podman --remote --connection conA info
Error: failed to resolve active destination: "conA" service destination not found
```

**Describe the results you expected:**

```
$ podman --remote --connection conA info
host:
  arch: amd64
...
```

**Additional information you deem important (e.g. issue happens only occasionally):**

- `--remote --connection <connection-string>` to the same servers seems to work when remoting from a Linux host.
- did not test on Windows

**Output of `podman version`:**

```
podman version
Client:
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.8
Built:        Sat Feb 20 05:46:59 2021
OS/Arch:      darwin/amd64

Server:
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.8
Built:        Fri Feb 19 17:56:17 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.26-1.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 777074ecdb5e883b9bec233f3630c5e7fa37d521'
  cpus: 8
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: servA.mydomain.local
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.17-200.fc33.x86_64
  linkmode: dynamic
  memFree: 15073468416
  memTotal: 16779329536
  ociRuntime:
    name: crun
    package: crun-0.18-1.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.18
      commit: 808420efe3dc2b44d6db9f1a3fac8361dde42a95
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 7734288384
  swapTotal: 7734288384
  uptime: 1h 17m 16.82s (Approximately 0.04 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 1
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 7
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1613753777
  BuiltTime: Fri Feb 19 17:56:17 2021
  GitCommit: ""
  GoVersion: go1.15.8
  OsArch: linux/amd64
  Version: 3.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ brew info podman
podman: stable 3.0.1 (bottled)
Tool for managing OCI containers and pods
https://podman.io/
/usr/local/Cellar/podman/3.0.1 (150 files, 37.9MB) *
  Poured from bottle on 2021-02-22 at 16:30:55
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/podman.rb
License: Apache-2.0
==> Dependencies
Build: go ✘, go-md2man ✘
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Analytics
install: 3,319 (30 days), 8,674 (90 days), 16,873 (365 days)
install-on-request: 3,314 (30 days), 8,628 (90 days), 16,434 (365 days)
build-error: 0 (30 days)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- server: qemu vm
- client: physical (Macbook Intel)

**Comment by Luap99** [comment]
The root socket listens on `/run/podman/podman.sock`

**Comment by christian-korneck** [comment]
> The root socket listens on /run/podman/podman.sock

@Luap99 thanks for the comment. On my server(s) both exist (`/run/podman/podman.sock` and `/run/user/0/podman/podman.sock`) and I have the same problem with both.

on a Mac:
```
$ podman system connection ls
Name    Identity                          URI
connC*     /Users/myuser/.ssh/podman_rsa  ssh://root@servC.tailscale.tk:22/run/podman/podman.sock
$ podman ps
CONTAINER ID  IMAGE                                 COMMAND         CREATED       STATUS           PORTS   NAMES
$ podman --remote -c connC ps
Error: failed to resolve active destination: "connC" service destination not found
```

**Comment by Luap99** [comment]
Can you paste the output of `podman --remote -c conC  --log-level debug ps`.

**Comment by christian-korneck** [comment]
> Can you paste the output of podman --remote -c conC --log-level debug ps.

@Luap99 

```
$ podman --remote -c conC --log-level debug ps
INFO[0000] podman filtering at log level debug
DEBU[0000] Called ps.PersistentPreRunE(podman --remote -c conC --log-level debug ps)
Error: failed to resolve active destination: "conC" service destination not found
```

**Comment by Luap99** [comment]
@jwhonce PTAL

**Comment by christian-korneck** [comment]
quick addition: also seeing this on Windows (Podman 3.0.1 via MSI installer) on Win10-2004 AMD64)

![image](https://user-images.githubusercontent.com/6320032/109419399-903b6400-79cd-11eb-9846-515bbbdba55a.png)

**Comment by rhatdan** [comment]
@christian-korneck Are you still seeing this issue.  @ashley-cui @baude Have been working hard on improving Podman on MAC.

**Comment by christian-korneck** [comment]
> Are you still seeing this issue. 

yes, still seeing this issue after having upgraded Podman client (Mac/Win) and server (fc 33) to **`3.1.0`**. Both with existing and recreated connection. Haven't tried from `main`. 

> @ashley-cui @baude Have been working hard on improving Podman on MAC.

thanks for bringing Podman to Mac/Win, it's already super useful!!

**Comment by ashley-cui** [comment]
I'll poke this a bit today

**Comment by christian-korneck** [comment]
> stale-issue

*poke

**Comment by rhatdan** [comment]
@ashley-cui Did you make any progress on this?

**Comment by ashley-cui** [comment]
Sorry, dropped off my list. Seems like still a problem, I will try to get to it this week.

**Comment by ashley-cui** [comment]
Closed via https://github.com/containers/common/pull/541
