### ISSUE TITLE
Two containers inside the same pod receive same ports

### ISSUE THREAD

**Issue by DaniBet** [containers/podman#9538]
Hello,

I have two containers in the same pod:

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: xxx
  name: xxx
spec:
  containers:
    - image: app1
      name: app1
      ports:
        - name: port1
          hostPort: 8081
          containerPort: 8081
          protocol: tcp
    - image: app2
      name: app2
      ports:
        - name: port2
          hostPort: 27017
          containerPort: 27017
          protocol: tcp
```

     The issue is that the both containers receive the same ports  (8081). How can I fix that?

**Comment by mheon** [comment]
This is how pods work by design in Podman - containers in a pod share a
network stack.

**Comment by DaniBet** [comment]
Hello @mheon ,

But how can I solve that?

**Comment by mheon** [comment]
What do you want to do such that this is a problem?

**Comment by DaniBet** [comment]
Mongo works on 27017 and my application works on 8081. It is a very big issue because my application or the database ports are wrong. My application needs to be pointed outsite to 8081 and mongo to 27017.

**Comment by mheon** [comment]
Every container in the pod has access to every pod assigned to the pod. There should be no barrier to having Mongo on 27017 and the app on 8081?

**Comment by mheon** [comment]
Sorry, to every *port* assigned to the pod.

**Comment by DaniBet** [comment]
Yes, I trust you but the both containers receive the first port declared, in our case 8081.

**Comment by mheon** [comment]
What do you mean "receive"?

Can you provide your Podman version?

**Comment by DaniBet** [comment]
podman version 1.6.4

CONTAINER ID  IMAGE                                                      COMMAND               CREATED        STATUS            PORTS                     NAMES
ab4701fc4bdb  mongo:3.6                                                  docker-entrypoint...  3 seconds ago  Up 2 seconds ago  0.0.0.0:27017->27017/tcp  mongodb
5758aebec01f xxx  /opt/axway/bin/ui...  3 seconds ago  Up 2 seconds ago  0.0.0.0:27017->27017/tcp  xxx

Here, for example, the both containers received 27017 even if my yaml looks like:

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: xxx
  name: xxx
spec:
  containers:
    - image: mongo
      name: mongo
      ports:
        - name: mongoport
          hostPort: 27017
          containerPort: 27017
          protocol: tcp
    - image: app
      name: app
      ports:
        - name: apport
          hostPort: 8081
          containerPort: 8081
          protocol: tcp

**Comment by mheon** [comment]
Please try a more recent Podman. `podman play kube` has advanced majorly since v1.6.4.

**Comment by DaniBet** [comment]
I am working with Centos 7, which is the latest stable version for Centos 7?

**Comment by mheon** [comment]
@lsm5 We were just talking about turning off OBS for Cent 7, right? Otherwise I'd suggest that.

**Comment by DaniBet** [comment]
Same issue also in 3.0 . The both containers receive the same port.

**Comment by mheon** [comment]
Can you provide the output of `podman inspect` on both containers?

**Comment by thephoenixofthevoid** [comment]
> podman version 1.6.4
> 
> CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
> ab4701fc4bdb mongo:3.6 docker-entrypoint... 3 seconds ago Up 2 seconds ago 0.0.0.0:27017->27017/tcp mongodb
> 5758aebec01f xxx /opt/axway/bin/ui... 3 seconds ago Up 2 seconds ago 0.0.0.0:27017->27017/tcp xxx
> 
> Here, for example, the both containers received 27017 even if my yaml looks like:
> 
> ```
> apiVersion: v1
> kind: Pod
> metadata:
>   labels:
>     app: xxx
>   name: xxx
> spec:
>   containers:
>     - image: mongo
>       name: mongo
>       ports:
>         - name: mongoport
>           hostPort: 27017
>           containerPort: 27017
>           protocol: tcp
>     - image: app
>       name: app
>       ports:
>         - name: apport
>           hostPort: 8081
>           containerPort: 8081
>           protocol: tcp
> ```

I have run your example (changing only app image to hello-world container):
```
CONTAINER ID  IMAGE                                 COMMAND   CREATED            STATUS                     PORTS                                           NAMES
e1ddadce8364  k8s.gcr.io/pause:3.2                            3 minutes ago      Up 58 seconds ago          0.0.0.0:8081->80/tcp, 0.0.0.0:27017->27017/tcp  6ae31e92450d-infra
93e01b0a7a45  docker.io/library/mongo:latest        mongod    3 minutes ago      Up 58 seconds ago          0.0.0.0:8081->80/tcp, 0.0.0.0:27017->27017/tcp  xxx-mongo
fa984d8d320c  docker.io/strm/nginx-balancer:latest            58 seconds ago     Up Less than a second ago  0.0.0.0:8081->80/tcp, 0.0.0.0:27017->27017/tcp  xxx-app
```
Running rootless `podman version 3.0.0`. Hope, it helps.

**Comment by DaniBet** [comment]
Hello,

I don't understand at all. So, this is my yaml file:

```

**Comment by thephoenixofthevoid** [comment]
> Hello,
> 
> I don't understand at all. So, this is my yaml file:
> 
> ```
> apiVersion: v1
> kind: Pod
> metadata:
>   labels:
>     app: app
>   name: app_pod
> spec:
>   containers:
>     - image: app_dev:2.0
>       name: app
>       command:
>       ports:
>         - name: port1
>           hostPort: 8081
>           containerPort: 8081
>           protocol: tcp
>       env:
>         - name: ACCEPT_EULA
>           value: "yes"
>       image: appdev:2.0.0
>       name: app
>       ports:
>       resources: {}
>       securityContext:
>         allowPrivilegeEscalation: true
>         capabilities: {}
>         privileged: false
>         readOnlyRootFilesystem: false
>       workingDir: /
> 
>     - image: mongo:3.6
>       name: mongodb
>       env:
>         - name: MONGO_INTERNAL_PORT
>           value: "27017"
>         - name: MONGO_INITDB_ROOT_USERNAME
>           value: "xxx"
>         - name: MONGO_INITDB_ROOT_PASSWORD
>           value: "xxx"
>         - name: MONGO_APP_DATABASE
>           value: "xxx"
>         - name: MONGO_APP_USER
>           value: "xxx"
>         - name: MONGO_APP_PASS
>           value: "xxx"
>       ports:
>         - name: port2
>           hostPort: 27017
>           containerPort: 27017
>           protocol: tcp
> status: {}
> ```
> 
> My output:
> 
> ```
> [root@podman apps.podman]# podman ps
> CONTAINER ID  IMAGE                                                      COMMAND  CREATED        STATUS            PORTS                     NAMES
> 04656859705e  k8s.gcr.io/pause:3.2                                                3 minutes ago  Up 3 minutes ago  0.0.0.0:27017->27017/tcp  0d5d76bda4bf-infra
> dc1acec438f6  app_dev:2.0                                                              3 minutes ago  Up 3 minutes ago  0.0.0.0:27017->27017/tcp  app_pod-app
> 3e2b8078d1e9  docker.io/library/mongo:3.6                                mongod   3 minutes ago  Up 3 minutes ago  0.0.0.0:27017->27017/tcp  flowmanager_pod-mongodb
> [root@podman a
> ```
> 
> ```
> [root@podman apps.podman]# podman -v
> podman version 3.0.1
> [root@podman apps.podman]# rpm -q centos-release
> centos-release-7-9.2009.1.el7.centos.x86_64
> ```
> 
> Any idea? Do you think that this issue can replicated only on CentOS 7? I also tried on a different VM, but also with CentOS 7, and the result is the same. I don't think that being root can be a problem.
> 
> @thephoenixofthevoid It seems to work a bit different to you, but I don't think that this is the correct behavior too. All the containers receive the same ports.

It seems what I see is actually a correct behavior. Since containers of a pod share network namespace, they are treated like a single entity. The problem is that configuration merges the wrong way in your case.

**Comment by DaniBet** [comment]
Hello @thephoenixofthevoid,

Could you, please, send me your yaml file used in your example? I want to see how it is treated on my VM. What operation system do you use?

**Comment by thephoenixofthevoid** [comment]
Sure
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: xxx
  name: xxx
spec:
  containers:
    - image: mongo
      name: mongo
      ports:
        - name: mongoport
          hostPort: 27017
          containerPort: 27017
          protocol: tcp
    - image: strm/nginx-balancer
      name: app
      ports:
        - name: apport
          hostPort: 8081
          containerPort: 80
          protocol: tcp
```

It's yours except for a single image

**Comment by rhatdan** [comment]
@mheon @thephoenixofthevoid Is this still an issue?

**Comment by mheon** [comment]
I'm still waiting for a `podman inspect` on a container in the post (or, ideally, all containers in the pod). I think this might just be a display issue in `podman ps` where it's cutting output after one port.

**Comment by mheon** [comment]
Sorry, on a container in the *pod*

**Comment by baude** [comment]
I'm going to close this issue.  Again, all containers in a pod share the same network namespace.  This means it is going to look in `podman ps` that each container has the port.  But because they are in the same network namespace, this is expected and the container that is actually running something on that port will "answer" for the pod.
