### ISSUE TITLE
Storage driver set in /etc/containers/storage.conf ignored for rootless configurations

### ISSUE THREAD

**Issue by jwillikers** [containers/podman#9547]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman does not use the storage driver configured in `/etc/containers/storage.conf` as the default storage driver for rootless containers.
When I set the driver as `btrfs` in `/etc/containers/storage.conf`, then reset rootless and delete any user configuration, it uses `vfs` instead.
This behavior is not mentioned in the documentation [here](https://github.com/containers/podman/blob/master/docs/tutorials/rootless_tutorial.md#storageconf), so I assume this is a bug.

**Steps to reproduce the issue:**

1. Install Podman from the Kubic repository on Ubuntu 18.04.

2. Set the driver as `btrfs` in `/etc/containers/storage.conf`.

3. Run `podman info` as a user and check the value for `graphDriverName` only to find it is `vfs`.

**Describe the results you received:**

The `graphDriverName` for the user's rootless configuration is `vfs`.

**Describe the results you expected:**

The `graphDriverName` for the user's rootless configuration should be `btrfs`.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.2
Built:        Wed Dec 31 18:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.26, commit: '
  cpus: 8
  distribution:
    distribution: elementary
    version: 5.1.7
  eventLogger: journald
  hostname: vaio
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.4.0-66-generic
  linkmode: dynamic
  memFree: 1426804736
  memTotal: 8326594560
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.18.1-7931a-dirty
      commit: 7931a1eab0590eff4041c1f74e2844b297c31cea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.3.1
  swapFree: 8352952320
  swapTotal: 8355049472
  uptime: 56m 26.89s
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/jordan/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/jordan/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 0
  runRoot: /run/user/1001/containers
  volumePath: /home/jordan/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 0
  BuiltTime: Wed Dec 31 18:00:00 1969
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/amd64
  Version: 3.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing... Done
podman/unknown,now 100:3.0.1-2 amd64 [installed]
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine using Btrfs on root.

**Comment by mheon** [comment]
@rhatdan Would you consider this deliberate?

**Comment by rhatdan** [comment]
I would like to know if this is working properly in rootfull mode?

I don't think we currently support btrfs in rootless mode, but If it works, I guess we should allow it.  The biggest issue is no one has used it in the past, so we have no idea how well it works.

**Comment by rhatdan** [comment]
I am also no quite sure if this is allowed in rootless mode.   @jwillikers interested in opening a PR to see if you could get this to work?

**Comment by jwillikers** [comment]
Yes, this works fine for the root configuration in my case.

```sh
$ sudo podman info | grep graphDriverName
  graphDriverName: btrfs
```

I've already verified that the `btrfs` driver works correctly in rootless mode, but I do have to configure the storage driver explicitly in `~/.config/containers/storage.conf`.
It creates Btrfs subvolumes under `/home/jordan/.local/share/containers/storage/btrfs/subvolumes/`.
I even verified from within a running container that the Btrfs mount options used for it were properly inherited from the parent subvolume.

I can certainly do a PR.
Since the driver appears to work fine from rootless, would the PR be for enabling rootless configurations to inherit the Btrfs driver from the `/etc/containers/storage.conf` file?
Or is some other work, needed?

**Comment by rhatdan** [comment]
Yes I would say that if BTRFS is set in /etc/containers/storage.conf then the rootless container storage should follow it.

Similarly if I put driver=btrfs in ~/.config/containers/storage.conf then rootless mode should use it.

**Comment by jwillikers** [comment]
Got it. 👍 I think I've found the related logic in [containers/storage/types/options.go](https://github.com/containers/storage/blob/364187782f1c761ad05b2b9db9e789ea2de292e8/types/options.go#L166).

**Comment by rhatdan** [comment]
Yes the changes would be in containers/storage.
