### ISSUE TITLE
Missing swagger type for SpecGenerator expose attribute

### ISSUE THREAD

**Issue by TristanCacqueray** [containers/podman#9559]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The Swagger type for SpecGenerator.expose does not have a type.

**Steps to reproduce the issue:**

1. Lookup definition at https://docs.podman.io/en/latest/_static/api.html#operation/libpodCreateContainer

**Describe the results you received:**

The expose attribute type is Any.

**Describe the results you expected:**

The correct attribute type, e.g. `map of uint16 (port number) to a string`.

**Comment by mheon** [comment]
@jwhonce PTAL

**Comment by rhatdan** [comment]
@TristanCacqueray could you open a PR to fix?

**Comment by TristanCacqueray** [comment]
It seems like the issue is related to the `uint16` basic type for the key, but i can't find where or how to fix that.
