### ISSUE TITLE
podman build: --build-arg: does not fall back to environment

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#9571]
Difference between `buildah bud` and `podman build`: buildah defaults a build-arg to an envariable if it's set; podman does not:
```console
$ export foo=bar
$ printf "FROM quay.io/libpod/alpine:latest\nARG foo\n" | ./bin/podman build --quiet --build-arg foo -
WARN[0000] missing "foo" build argument. Try adding "--build-arg foo=<VALUE>" to the command line
41187bb4760c7a6c46b3cf4c7ca2595c7432cf87c06c131fadb6fc9e509136c2
```
buildah, if it sees `--build-arg foo` without an explicit `=something`, will interpolate the environment variable `$foo`.

This may be a bug, or may be an intentional difference, or it may be a nothing-we-can-do-about-it difference. If it can't be fixed, perhaps it should be documented.

**Comment by rhatdan** [comment]
Give me a test for this one, as well, and I will give you a fix.

**Comment by rhatdan** [comment]
I will trade you one test for one fix. :^)

**Comment by edsantiago** [comment]
[build-arg.diff.txt](https://github.com/containers/podman/files/6072186/build-arg.diff.txt)

Reconciling all these diffs is left as an exercise for the reader
