### ISSUE TITLE
swagger type mismatch for the /libpod/images/{name:.*}/tree endpoint

### ISSUE THREAD

**Issue by TristanCacqueray** [containers/podman#9578]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The documentation https://docs.podman.io/en/latest/_static/api.html#operation/libpodImageTree indicates the /libpod/images/{name:.*}/tree endpoint should return a LibpodImageTreeResponse object, but the actual response is different.

**Steps to reproduce the issue:**

1. Query the `/libpod/images/fedora/tree` endpoint

**Describe the results you received:**

The endpoint returns:

```json
{
    "Tree": "Image ID: 9f2a56037643\nTags:     [registry.fedoraproject.org/fedora:latest]\nSize:     182.3MB\nImage Layers\n\u2514\u2500\u2500  ID: d9e1d1e08de2 Size: 182.3MB Top Layer of: [registry.fedoraproject.org/fedora:latest]\n"
}
```

**Describe the results you expected:**

The endpoint should have returned the documented LibpodImageTreeResponse object, e.g:

```json
{
  "id": "fedora",
  "layers": [{"..."}],
  "..."
}
```

**Comment by rhatdan** [comment]
@TristanCacqueray Could you open a PR to fix this?

**Comment by TristanCacqueray** [comment]
Should the documentation be changed to "string" or should the response be adapted to match the existing documentation?

**Comment by rhatdan** [comment]
Let's just fix the documentation
