### ISSUE TITLE
[podman 3.0.1] unqualified image name no longer resolves correctly

### ISSUE THREAD

**Issue by runlevel5** [containers/podman#9585]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

It's seems to me there is a regression in the way podman resolves unqualified image name.

In version 2.2.1, when I try to pull an image with unqualified name (NOTE: my image is hosted on docker.io), for example:

```
podman pull myorg/reponame
```

podman would go through the list of `unqualified-search-registries` (which is defined in `/etc/containers/registries.conf`), for my case, it is the stock Fedora 33 config:

```
unqualified-search-registries = ["registry.fedoraproject.org", "registry.access.redhat.com", "registry.centos.org", "docker.io"]
```

and it would eventually try each of them until it gets to `docker.io`

When I upgrade to 3.0.1 (part of the latest upgrade of Fedora 33), the same command now prompt me for selection:

```
podman pull myorg/reponame
 - registry.fedoraproject.org/myorg/reponame
 - registry.access.redhat.com/myorg/reponame
 - registry.centos.org/myorg/reponame
 - docker.io/myorg/reponame
```

This is to me considered a breaking changes in behaviour as it causes issues with my automated CI/CD pipeline

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.8
Built:        Sat Feb 20 03:56:17 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.26-1.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 777074ecdb5e883b9bec233f3630c5e7fa37d521'
  cpus: 8
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: compono
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.15-200.fc33.x86_64
  linkmode: dynamic
  memFree: 541843456
  memTotal: 16426217472
  ociRuntime:
    name: crun
    package: crun-0.18-1.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.18
      commit: 808420efe3dc2b44d6db9f1a3fac8361dde42a95
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.fc33.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 5683744768
  swapTotal: 12578709504
  uptime: 145h 55m 38.15s (Approximately 6.04 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/tle/.config/containers/storage.conf
  containerStore:
    number: 78
    paused: 0
    running: 0
    stopped: 78
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.4.0-1.fc33.x86_64
      Version: |-
        fusermount3 version: 3.9.3
        fuse-overlayfs: version 1.4
        FUSE library version 3.9.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/tle/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 32
  runRoot: /run/user/1000/containers
  volumePath: /home/tle/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1613753777
  BuiltTime: Sat Feb 20 03:56:17 2021
  GitCommit: ""
  GoVersion: go1.15.8
  OsArch: linux/amd64
  Version: 3.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.0.1-1.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Just physical Lenovo X1 Carbon Gen 7 laptop

**Comment by mheon** [comment]
Yes, this is a breaking change - hence the version bump from Podman 2.x to Podman 3.0.

This should only occur when Podman detects it's attached to a TTY, though, so scripts should be unaffected. What CI executor are you using that is showing this?

**Comment by runlevel5** [comment]
> This should only occur when Podman detects it's attached to a TTY, though, so scripts should be unaffected. What CI executor are you using that is showing this?

I am using [Buildkite CI/CD](https://buildkite.com) with https://github.com/KennaSecurity/podman-buildkite-plugin plugin

**Comment by runlevel5** [comment]
@mheon the question is how would I be able to replicate the old behaviour given that podman detects it is attached to a TTY?

**Comment by vrothberg** [comment]
https://www.redhat.com/sysadmin/container-image-short-names

You can set the `short-names-mode` to "disabled".
