### ISSUE TITLE
RFE: podman pull shortname=f.q.i.n

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#9586]
I'm finding it really hard to get used to the new shortnames universe. The guesser never gets it right for me, and the default path (under `~/.config/.cache`, a double-dot weirdness) is really hard for me to remember. Harder than FQINs, and hard to edit manually.

What if we added a nonstandard extension where we could specify a mapping on the command line that would be autosaved?
```console
$ podman pull myalpine=quay.io/edsantiago/alpine
[saving alias "myalpine" to ~/.config/.cache/containers/short-name-aliases.conf]
Trying to pull quay.io/edsantiago/alpine...
```
Behavior on conflict would be TBD:
```console
$ podman pull myalpine=quay.io/edsantiago/busybox
Error: alias "myalpine" is already defined in ~/.etc-etc, pointing to quay.io/edsantiago/alpine; use --force to override
```
(Or maybe just warn. Or even just be silent. I like the idea of being silent when overriding a system default, because system defaults may not be anything I care about).

Anyhow, just an idea. Feel free to WONTFIX if it's stupid.

**Comment by mheon** [comment]
I'd just as soon have a dedicated `podman alias` command for managing them - `podman alias add testimg quay.io/libpod/myimg` or similar. Would that be acceptable?

**Comment by edsantiago** [comment]
Entirely acceptable!

**Comment by rhatdan** [comment]
I would prefer it to be a separate command like podman alias.

**Comment by vrothberg** [comment]
The rootless path was recently fixed to be `~/.cache` but users should not edit that file; it's meant to be written by programs only when having (successfully) pulled a previously selected alias in the prompt.  Users can, however, edit their `registries.conf` files as they please.

I have rather strong feelings against exposing anything on the CLI but rather improve documentation.  Having a dedicated command like that is, at least from a technical perspective, a front end to edit `registries.conf` and I am rather afraid of opening to the door to configure more options (e.g., the search registries or mirrors).

My preference is to strongly push back on lifting short-name aliases any higher but improve documentation. In case there's consensus on ever implementing such a command: the backend code (c/image/pkg/sysregistriesv2) allows for manipulating aliases.

**Comment by rhatdan** [comment]
@edsantiago Let's discuss this at tomorrow's watercooler?

**Comment by vrothberg** [comment]
AFAIR we agreed to improve docs, and since #10249 merged, I am going to close.
