### ISSUE TITLE
podman save only seem to store multiple image for docker-archive format

### ISSUE THREAD

**Issue by martinetd** [containers/podman#9590]
/kind bug

**Description**

`podman save` allows saving multiple images at once, according to its help: `podman save [options] IMAGE [IMAGE...]`
In practice that is true for the default save format, but oci-archive for example only seems to store one when inspecting the generated tar.

**Steps to reproduce the issue:**

1. podman save --format oci-archive localhost/my_image:1.0 localhost/my_image:1.1  > t.tar

2. podman load < t.tar

**Describe the results you received:**

Only one image got loaded: `Loaded image(s): localhost/my_image:1.0`

**Describe the results you expected:**

Either both images should be stored or save should error out (e.g. "podman doesn't support saving multiple images in oci-archive format")

By the way, I've tried manually generating an oci-archive tar with multiple images (adjusting the index.json accordingly) and get the following errors on `podman load` ; it's interesting the error is different if it is a folder or archive (but load does not let me specify an image -- it does work with `podman pull oci-archive:t.tar:'localhost/my_image:1.1'` so my archive is probably alright.
```
$ podman load < t.tar 
  open /var/tmp/podman248900533/manifest.json: not a directory
  open /var/tmp/podman248900533/index.json: not a directory
Loaded image(s): 
$ podman load -i extracted-archive
  open extracted-archive/manifest.json: no such file or directory
  more than one image in oci, choose an image
Loaded image(s): 
```

Note: I'll just switch to docker-archive format, I'm not sure why I used oci-archive in the first place.

**Output of `podman version`:**

```
Version:      3.1.0-dev
API Version:  3.0.0
Go Version:   go1.15.8
Git Commit:   0a40c5a059455693de0cc9a3f4a2a16722fc61e9
Built:        Wed Mar  3 13:43:36 2021
OS/Arch:      linux/amd64
```

**Comment by mheon** [comment]
@vrothberg PTAL

**Comment by vrothberg** [comment]
Thanks for reaching out.  Work is already being tracked in https://github.com/containers/podman/issues/4646.  Note that the behavior is documented.

**Comment by martinetd** [comment]
Sorry I had missed that other issue, I was too focused on the saving part.

I don't see anything about this in podman save nor load's man page or help, where is it documented? (perhaps it could be more obvious? I suggested erroring out on save with multiple image arguments, that should be pretty simple to do)

Well if it's being worked on I'm fine either way, but it doesn't look like that'll be merged quickly so a stop-gap wouldn't hurt.
