### ISSUE TITLE
API: Unable to remove image throws 500 error

### ISSUE THREAD

**Issue by zyclonite** [containers/podman#9596]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. start podman service

2. try to remove an image via the api which does have more than one tag

**Describe the results you received:**
```
   {"cause":"unable to match user input to any specific repotag",
    "message":"unable to match user input to any specific repotag",
    "response":500} 
```

**Describe the results you expected:**
404 or other 4xx error

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.8
Built:        Fri Feb 19 16:56:17 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.26-1.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 777074ecdb5e883b9bec233f3630c5e7fa37d521'
  cpus: 2
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: ip-10-100-27-216
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.19-200.fc33.x86_64
  linkmode: dynamic
  memFree: 6321627136
  memTotal: 8073469952
  ociRuntime:
    name: crun
    package: crun-0.18-1.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.18
      commit: 808420efe3dc2b44d6db9f1a3fac8361dde42a95
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 1h 3m 30.54s (Approximately 0.04 days)
registries:
  docker.io:
    Blocked: false
    Insecure: false
    Location: nexus.noenv.com
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: docker.io
  search:
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 3
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 8
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1613753777
  BuiltTime: Fri Feb 19 16:56:17 2021
  GitCommit: ""
  GoVersion: go1.15.8
  OsArch: linux/amd64
  Version: 3.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
fedora coreos 33.20210301.2.0 (testing)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
aws

**Comment by zyclonite** [comment]
in addition, to a wrong input it returns a http 500 error containing a 404 and 500 json error in the body

e.g.
```
curl -v -X DELETE "http://127.0.0.1:2375/images/"
*   Trying 127.0.0.1:2375...
* Connected to 127.0.0.1 (127.0.0.1) port 2375 (#0)
> DELETE /images/ HTTP/1.1
> Host: 127.0.0.1:2375
> User-Agent: curl/7.71.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Api-Version: 1.40
< Content-Type: application/json
< Libpod-Api-Version: 3.0.0
< Server: Libpod/3.0.0 (linux)
< Date: Wed, 03 Mar 2021 15:00:16 GMT
< Content-Length: 204
< 
{"cause":"input name is blank","message":"failed to find image : input name is blank","response":500}
{"cause":"input name is blank","message":"failed to find image : input name is blank","response":404}
```

**Comment by mheon** [comment]
Likely a missing return statement somewhere...

**Comment by zyclonite** [comment]
in general there seems to be the `internal server error` as a fallback for all kind of non 500 errors...

on push a http 500
```
{"cause":"invalid argument","message":"failed to find image repo.custom.tld/group/app:1.0.0: destination image name must be specified: invalid argument","response":500}
{"cause":"invalid argument","message":"failed to find image repo.custom.tld/group/app:1.0.0: destination image name must be specified: invalid argument","response":404}
```

**Comment by mheon** [comment]
Looking at this, I'm fairly certain this isn't actually hitting the remove images handler - I think that, since the URL isn't really valid (missing a name), some other handling at a lower level is throwing the error.

@jwhonce PTAL

**Comment by jwhonce** [comment]
@mheon, @zyclonite: The code on the master branch now handles this error much cleaner. 

@zyclonite: @mheon is correct that there is no defined RESTful endpoint `DELETE:/images/`. Most examples of not providing a path parameter would result in a 404 status code, but you found a corner case where the gorilla routing mux code passed your call to the the defined endpoint `DELETE:/images/{name}` with an empty `name` parameter. See results below.

$ curl -v -X DELETE --unix-socket /run/user/1000/podman/podman.sock http://localhost/images/
* Uses proxy env variable no_proxy == 'localhost,127.0.0.0/8,.local,192.168.250.53/24'
*   Trying /run/user/1000/podman/podman.sock:0...
* Connected to localhost (/run/user/1000/podman/podman.sock) port 80 (#0)
> DELETE /images/ HTTP/1.1
> Host: localhost
> User-Agent: curl/7.71.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Api-Version: 1.40
< Content-Type: application/json
< Libpod-Api-Version: 3.2.0-dev
< Server: Libpod/3.2.0-dev (linux)
< Date: Mon, 12 Apr 2021 03:24:43 GMT
< Content-Length: 79
< 
{"cause":"input name is blank","message":"input name is blank","response":500}
