### ISSUE TITLE
podman-remote start --attach : can only attach to created or running containers - currently in state stopped

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#9597]
Looks like a race condition. Symptom is:
```console
$ podman-remote [options] start --attach test
Error: unable to start container b1ce2aadbf58178fe75cb41da71dd0bf8e4b53cea21029da2a5c4d08a7f32da7: can only attach to created or running containers - currently in state stopped: container state improper
```
## Podman run restart containers [It] Podman start after successful run
* gce_instance:fedora : int remote fedora-33 root host
  * PR #9580
    * [03-02 15:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5659447872716800/html/int-remote-fedora-33-root-host.log.html#t--Podman-start-after-successful-run--1)
  * PR #9231
    * [02-05 04:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5837119862079488/html/int-remote-fedora-33-root-host.log.html#t--Podman-start-after-successful-run--1)
    * [02-05 04:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5837119862079488/html/int-remote-fedora-33-root-host.log.html#t--Podman-start-after-successful-run--2)
    * [02-05 04:44](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5837119862079488/html/int-remote-fedora-33-root-host.log.html#t--Podman-start-after-successful-run--3)
* gce_instance:prior-fedora : int remote fedora-32 root host
  * PR #9319
    * [02-11 06:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5873097595158528/html/int-remote-fedora-32-root-host.log.html#t--Podman-start-after-successful-run--1)

**Comment by rhatdan** [comment]
@mheon this code looks like it will always race.  Since we need to attach to the container before starting it?

**Comment by mheon** [comment]
The attach code on the API side should be able to handle this - it will take containers in a bad state and initialize them so we can attach. I think this is a bug in the API code for Attach.

**Comment by rhatdan** [comment]
@mheon Do you have any time to tackle this?

**Comment by mheon** [comment]
Probably not, I'll be gone most of next week

**Comment by rhatdan** [comment]
@mheon Do you have time for this now?

**Comment by rhatdan** [comment]
@mheon PTAL

**Comment by edsantiago** [comment]
I haven't seen this since the initial issue. Feel free to close.

**Comment by edsantiago** [comment]
Reopening. Seen just now in [f35 root, remote](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4833363958693888/html/sys-remote-fedora-35-root-host.log.html), in the seemingly-jinxed PR #11795 
```
not ok 60 podman logs restarted - k8s-file
... 
# # podman-remote --url unix:/tmp/podman_tmp_L82A run --log-driver=k8s-file --name logtest quay.io/libpod/testimage:20210610 sh -c start=0; if test -s log; then start=`tail -n 1 log`; fi; seq `expr $start + 1` `expr $start + 10` | tee -a log
... (shows 1-10 correctly)
# # podman-remote --url unix:/tmp/podman_tmp_L82A start -a logtest
# Error: unable to start container 484b076605d18bb7f32187b2838a26b5fe5b8c604534803a20d00af701e73344: can only attach to created or running containers - currently in state stopped: container state improper
# [ rc=125 (** EXPECTED 0 **) ]
```

**Comment by edsantiago** [comment]
Bump. This is becoming a multiple-times-a-day flake.  [example](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5604276228587520/html/sys-remote-fedora-35-root-host.log.html)

**Comment by edsantiago** [comment]
### [sys] 60 podman logs restarted - k8s-file
* fedora-35 : sys remote fedora-35 root host [remote]
  * PR #12386
    * [11-22 14:35](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5890716187492352/html/sys-remote-fedora-35-root-host.log.html#t--00060)
  * PR #12364
    * [11-19 12:55](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5335377687871488/html/sys-remote-fedora-35-root-host.log.html#t--00060)
* ubuntu-2110 : sys remote ubuntu-2110 root host [remote]
  * PR #11795
    * [11-18 15:06](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4637903318941696/html/sys-remote-ubuntu-2110-root-host.log.html#t--00060)

**Comment by edsantiago** [comment]
This one is one of our biggest flakes right now. Who can take a look?

### [sys] 60 podman logs restarted - k8s-file
* fedora-35 : sys remote fedora-35 root host [remote]
  * PR #12511
    * [12-05 20:25](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5151600063807488/html/sys-remote-fedora-35-root-host.log.html#t--00060)
  * PR #12486
    * [12-02 16:51](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5627545656754176/html/sys-remote-fedora-35-root-host.log.html#t--00060)
  * PR #12471
    * [12-01 17:57](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5887239042367488/html/sys-remote-fedora-35-root-host.log.html#t--00060)
    * [12-01 17:38](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4663094979854336/html/sys-remote-fedora-35-root-host.log.html#t--00060)
    * [12-01 17:19](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5922438815940608/html/sys-remote-fedora-35-root-host.log.html#t--00060)
  * PR #12450
    * [12-01 04:49](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6504484193959936/html/sys-remote-fedora-35-root-host.log.html#t--00060)
  * PR #12407
    * [11-24 11:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5927380142260224/html/sys-remote-fedora-35-root-host.log.html#t--00060)
  * PR #12404
    * [11-24 06:22](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5954526751490048/html/sys-remote-fedora-35-root-host.log.html#t--00060)
* ubuntu-2110 : sys remote ubuntu-2110 root host [remote]
  * PR #12511
    * [12-05 20:26](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4870125087096832/html/sys-remote-ubuntu-2110-root-host.log.html#t--00060)

### [sys] 61 podman logs restarted journald
* fedora-35 : sys remote fedora-35 root host [remote]
  * PR #12511
    * [12-05 20:25](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5151600063807488/html/sys-remote-fedora-35-root-host.log.html#t--00061)
  * PR #12486
    * [12-02 15:41](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5473930514268160/html/sys-remote-fedora-35-root-host.log.html#t--00061)
  * PR #12480
    * [12-02 09:40](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5862164150878208/html/sys-remote-fedora-35-root-host.log.html#t--00061)
  * PR #12471
    * [12-01 18:14](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6303499488067584/html/sys-remote-fedora-35-root-host.log.html#t--00061)
    * [12-01 17:19](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5922438815940608/html/sys-remote-fedora-35-root-host.log.html#t--00061)
  * PR #12407
    * [11-24 10:54](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/4929815938596864/html/sys-remote-fedora-35-root-host.log.html#t--00061)
* ubuntu-2110 : sys remote ubuntu-2110 root host [remote]
  * PR #12466
    * [12-01 09:27](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6575711797379072/html/sys-remote-ubuntu-2110-root-host.log.html#t--00061)
  * PR #12405
    * [11-24 07:30](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5841569380040704/html/sys-remote-ubuntu-2110-root-host.log.html#t--00061)
  * PR #12404
    * [11-24 06:23](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6517476704911360/html/sys-remote-ubuntu-2110-root-host.log.html#t--00061)

**Comment by vrothberg** [comment]
I will take a look :heavy_check_mark:

**Comment by vrothberg** [comment]
Ouch, this one even flakes locally.

**Comment by vrothberg** [comment]
Easy reproducer on my workstation:
> ./bin/podman-remote run --replace --name test alpine sh -c 'start=0; if test -s log; then start=tail -n 1 log; fi; seq expr $start + 1 expr $start + 10 | tee -a log'; ./bin/podman-remote start -a test

**Comment by vrothberg** [comment]
There's something (race) going on in remote start/attach but I cannot put my finger on it.

@mheon could you take a look?  The flake has been dealt with but the bug is still there.

**Comment by edsantiago** [comment]
Last instance I see is from December 8, two days after @vrothberg's #12519, so the `wait` seems to have taken care of the flake (thank you Valentin!).

Since that was a sweep-under-the-rug, not a fix, I'm not willing to close this PR.

**Comment by rhatdan** [comment]
Since no one is working on this and Ed said we can close it...
