### ISSUE TITLE
[Volume Plugins] Specifying options resets Volume Driver to local.

### ISSUE THREAD

**Issue by thephoenixofthevoid** [containers/podman#9650]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

If using volume plugin with specified options, Driver (--driver) argument is completely ignored.

**Steps to reproduce the issue:**

1. Forked `docker-volume-sshfs` and changed paths to socket (it has been hardcoded).

2. Added a record in `containers.conf`

3. Started a plugin. Then tried to create a volume without options and specifying them. 

**Describe the results you received:**

For `podman volume create --driver testplugin` as well as using API endpoint `/libpod/volumes/create` with `{ Driver: "testplugin" }` got:
```
$ ./podman-volume-ssh 
INFO[0000] listening on /tmp/podman-plugins-test.sock   
2021/03/07 14:59:13 Entering go-plugins-helpers getPath
ERRO[0054] volume 784484bf997f98d0b04a07525eb12560da1740f6139cc0e7463132427496937a not found 
2021/03/07 14:59:13 Entering go-plugins-helpers createPath
ERRO[0054] 'sshcmd' option required         
```
API Endpoint response:
```
{
  cause: "'sshcmd' option required",
  message: `error creating volume "9874028d86d0e6404b0dcda74cd46da441dcc0b2a6650bb0f8fef56da8bc0eb4" in plugin testplugin: error on /VolumeDriver.Create on volume 9874028d86d0e6404b0dcda74cd46da441dcc0b2a6650bb0f8fef56da8bc0eb4 in volume plugin testplugin: 'sshcmd' option required`,
  response: 500
}
```
Which is correct actually. But.

For `podman volume create --driver testplugin --opt sshcmd=<whatever>` as well as using API endpoint `/libpod/volumes/create` with `{ Driver: "testplugin", Options: { sshcmd: <whatever> } }` got:
```
<NOTHING REACHES PLUGIN ENDPOINT>
```
and the response:
```
{
  cause: 'invalid argument',
  message: 'error running volume create option: unrecognized volume option "sshcmd" is not supported with local driver: invalid argument',
  response: 500
}
```

**Describe the results you expected:**

Expected to create a volume that corresponds to a remote sshfs.

**Additional information you deem important (e.g. issue happens only occasionally):**

This might be related: https://github.com/containers/podman/blob/d92b94677cc816a1e157802836195430b731d015/cmd/podman/volumes/create.go#L77

**Output of `podman version`:**

```
Version:      3.0.0
API Version:  3.0.0
Go Version:   go1.15.7
Built:        Fri Feb 12 02:12:57 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.2
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.26-1.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 777074ecdb5e883b9bec233f3630c5e7fa37d521'
  cpus: 8
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: thefallen
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.15-200.fc33.x86_64
  linkmode: dynamic
  memFree: 142139392
  memTotal: 8190509056
  ociRuntime:
    name: crun
    package: crun-0.17-1.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.fc33.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 9418559488
  swapTotal: 12445540352
  uptime: 10h 41m 15.58s (Approximately 0.42 days)
registries:
  localhost:5000:
    Blocked: false
    Insecure: true
    Location: localhost:5000
    MirrorByDigestOnly: false
    Mirrors: null
    Prefix: localhost:5000
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/feanor/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.4.0-1.fc33.x86_64
      Version: |-
        fusermount3 version: 3.9.3
        fuse-overlayfs: version 1.4
        FUSE library version 3.9.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/feanor/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 26
  runRoot: /run/user/1000
  volumePath: /home/feanor/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1613085177
  BuiltTime: Fri Feb 12 02:12:57 2021
  GitCommit: ""
  GoVersion: go1.15.7
  OsArch: linux/amd64
  Version: 3.0.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.0.0-1.fc33.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thephoenixofthevoid** [comment]
I checked the state of `createOpts` right before the 
```
response, err := registry.ContainerEngine().VolumeCreate(context.Background(), createOpts)
```
and it is correct:
```
./podman volume create --driver testplugin --opt sshcmd=1

Gives

{
	 "Name": "",
	 "Driver": "testplugin",
	 "Label": {},
	 "Options": {
	  "sshcmd": "1"
	 }
}
```
So need to investigate `registry.ContainerEngine().VolumeCreate` method.

**Comment by mheon** [comment]
Can you verify that `podman volume create` (the actual CLI command) has/does not have this issue? I'm strongly suspecting that it's an issue with the REST endpoint for volume creation, not the underlying logic.

**Comment by thephoenixofthevoid** [comment]
It does have an issue. Actually I first encountered it in cli, but tracking down is simpler using REST API. One of the important thing here is that option must have different option key than ones that local driver supports.

So, you won't have that exact bug with plugin that only supports "type", "device", "o", "UID" and/or "GID". But the following issue will arise instead: "cannot mount in rootless mode" . I think I figured out this one too: I will update this message with details ASAP.

**Comment by thephoenixofthevoid** [comment]
Here is latest code of my ongoing rework of famous docker plugin for podman:

https://gist.github.com/thephoenixofthevoid/2ced5a66e94777ad60d6a0b3b54d66c5

It depended on like 3-6 packages like docker-volume-sdk and so on. I examined all of them and inlined only relevant part of these (both relevant for such application and relevant for podman). The goal is to factor out common framework to build arbitrary plugins rapidly. The structure is already clearly visible.

Example: 
1. Host path volume plugin
2. Remountable volume plugin (like you can attach different USB hard drive and change drives as you want, the same idea applied to volumes)
3. "Routing Volume": each containers gets a single path in it to use as Unix Domain Endpoint, backed by a HTTP server. A single container  acts like a reverse proxy and routes requests based on directory structure of that volume and paths of endpoints. (Poor man's service mesh, it looks like) =)

**Comment by mheon** [comment]
If you're willing to submit it as a PR, I would accept the above patch if it was changed to still validate options if the driver was set to `local` or `""`.

**Comment by thephoenixofthevoid** [comment]
It happens here:
https://github.com/containers/podman/blob/d92b94677cc816a1e157802836195430b731d015/libpod/runtime_volume_linux.go#L66-L77
And there is the check you are talking about right now.

**Comment by mheon** [comment]
Alright, this looks fine, then.

**Comment by mheon** [comment]
I'm going to go ahead and close, since #9808 merged with the fix.
