### ISSUE TITLE
Document CONTAINERS_CONF and CONTAINERS_STORAGE_CONF

### ISSUE THREAD

**Issue by martinetd** [containers/podman#9656]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I was looking for a way to override the /etc/containers config files if required on a read-only system and stumbled upon CONTAINERS_CONF and CONTAINERS_STORAGE_CONF

Are these safe to use? (that is, can I rely on these working and not going away with minor version updates -- I see they're used in some tests so probably safe enough)
If so would it be worth documenting these?

Thanks!

**Comment by vrothberg** [comment]
Thanks for reaching out.  Yes, they are safe to use with Podman but I am not sure why they're not documented. @rhatdan may know.  It may have simply slipped through when adding the env vars.

**Comment by Luap99** [comment]
It is documented in `containers.conf(5)` https://github.com/containers/common/blob/master/docs/containers.conf.5.md#files

**Comment by martinetd** [comment]
uh, sorry :| Now I need to know why `man -K CONTAINERS_CONF` didn't find this, I can confirm the installed man page has it.. But that's another problem.

Thanks!

**Comment by vrothberg** [comment]
I don't consider it documented - if only half of the request since CONTAINERS_STORAGE_CONF is not mentioned.  I think that the Podman docs should mention it.

**Comment by martinetd** [comment]
There's one line about `CONTAINERS_STORAGE_CONF` there as well:
If the CONTAINERS_STORAGE_CONF path environment variable is set, this path is used for the storage.conf file rather than the default.  This is primarily used for testing.

**Comment by vrothberg** [comment]
I was a bit vague, apologies.  What I want is that it's mentioned in `man podman`.  It would be more approachable.

**Comment by martinetd** [comment]
Ah, sure :)

btw if anyone is curious, to answer myself: man -K searches for literals in the man page sources, so in this case I should have use `man -K 'CONTAINERS\_CONF'`... I had also grepped through the repo but go only has go sources from vendored dependencies and not a clone of the whole other repos -- either way I agree it can be made more easily discoverable, thanks for the follow up!

**Comment by martinetd** [comment]
@rhatdan (thanks for the PR)
While we're here, there is also REGISTRIES_CONFIG_PATH that I cannot find documented anywhere (this time not even in containers.conf(5) man page) -- it might already be too late to rename it to CONTAINERS_REGISTRIES_CONF to be homogeneous? but might as well be documented at the same time

**Comment by vrothberg** [comment]
@martinetd, I think your last comment should go into #9668.
