### ISSUE TITLE
ERROR (catatonit:2): failed to exec pid1: No such file or directory on 

### ISSUE THREAD

**Issue by sebastian-philipp** [containers/podman#9660]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

With the testing podman from `https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/testing/xUbuntu_20.04`, I'm getting:

```
2021-03-05T13:06:53.583 > sudo /home/ubuntu/cephtest/cephadm --image quay.ceph.io/ceph-ci/ceph:49c09faafe9891422be520f56474c0bc9f5ef70a shell -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring --fsid 4f62a35a-7db3-11eb-9069-001a4aab830c -- ceph orch host ls --format=json
2021-03-05T13:06:56.210 stderr:ERROR (catatonit:2): failed to exec pid1: No such file or directory
2021-03-05T13:07:06.597 stderr:level=error msg="Error removing container 84e3d2b2aa49ed159b93c71a35f634fccb0aeb60f511946ea51bb0cc80b63e60: error removing container 84e3d2b2aa49ed159b93c71a35f634fccb0aeb60f511946ea51bb0cc80b63e60 root filesystem: 1 error occurred:\n\t* unlinkat /var/lib/containers/storage/overlay/bb639d42bdd091a9c0ba250cba436637b6c0d582da0077c8fad8d2310875e216/merged: device or resource busy\n\n"
```

Full log is here: https://pulpito.ceph.com/swagner-2021-03-05_12:04:33-rados:cephadm-wip-swagner2-testing-2021-03-05-1040-pacific-distro-basic-smithi/5939138/

downstream bug is here: https://tracker.ceph.com/issues/49633

**Additional information you deem important (e.g. issue happens only occasionally):**

Looks like this was introduced on Friday last week or so as we haven't seen this issue before

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Comment by mheon** [comment]
Can you provide the full Podman command being executed by `cephadm`?

My initial impression is that `--init` is being used, and catatoinit is reporting that your requested command (`shell -c`) is not found in the container. Did you mean to type `sh -c`?

**Comment by sebastian-philipp** [comment]
Yeah, we're using `podman --init`, but interestingly, this fails only with about 10%-20% probability:

https://pulpito.ceph.com/swagner-2021-03-12_11:27:39-rados:cephadm:smoke-wip-swagner-testing-2021-03-11-1320-distro-basic-smithi/

**Comment by liewegas** [comment]
> Can you provide the full Podman command being executed by `cephadm`?
> 
> My initial impression is that `--init` is being used, and catatoinit is reporting that your requested command (`shell -c`) is not found in the container. Did you mean to type `sh -c`?

The full podman command looks something like
```
/bin/podman run --rm --ipc=host --net=host --privileged --group-add=disk --init -e CONTAINER_IMAGE=quay.ceph.io/ceph-ci/ceph:49c09faafe9891422be520f56474c0bc9f5ef70a -e NODE_NAME=dael -e CEPH_USE_RANDOM_NONCE=1 -v /var/run/ceph/63c0337e-c1b0-443b-9452-4c1c5a96a78b:/var/run/ceph:z -v /var/log/ceph/63c0337e-c1b0-443b-9452-4c1c5a96a78b:/var/log/ceph:z -v /var/lib/ceph/63c0337e-c1b0-443b-9452-4c1c5a96a78b/crash:/var/lib/ceph/crash:z -v /dev:/dev -v /run/udev:/run/udev -v /sys:/sys -v /var/lib/ceph/63c0337e-c1b0-443b-9452-4c1c5a96a78b/selinux:/sys/fs/selinux:ro -v /run/lvm:/run/lvm -v /run/lock/lvm:/run/lock/lvm -v /etc/ceph/ceph.conf:/etc/ceph/ceph.conf:z -v /etc/ceph/ceph.client.admin.keyring:/etc/ceph/ceph.keyring:z --entrypoint ceph quay.ceph.io/ceph-ci/ceph:49c09faafe9891422be520f56474c0bc9f5ef70a orch host ls --format=json
```

**Comment by umohnani8** [comment]
@liewegas are you still seeing this issue with the latest podman version?

**Comment by sebastian-philipp** [comment]
we're no longer seeing this in Ceph's CI.
