### ISSUE TITLE
Podman truncates last character of userdata symlink with a specific path length

### ISSUE THREAD

**Issue by zv0n** [containers/podman#9661]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
When running rootless podman with XDG_RUNTIME_DIR that has 25 characters the process fails due to truncating of socket dir symlink. Only the last character of the symlink path is truncated, I think there might be some problem with '\0' going on, but I couldn't find the userdata socket symlink in the source code.

For example this happens with $XDG_RUNTIME_DIR of length 25:

${XDG_RUNTIME_DIR}/libpod/tmp/socket/b3ee91f2f7e4e382f6395d3d5ead9ac24757b9bed6e86090069cab68c6477b2 -> ${PODMAN_ROOT}/overlay-containers/b3ee91f2f7e4e382f6395d3d5ead9ac24757b9bed6e86090069cab68c6477b28/userdata

as you can see the '8' that is supposed to be at the end of the symlink name is not there. Therefore podman fails with the following error:

Error: failed to connect to container's attach socket: ${XDG_RUNTIME_DIR}/libpod/tmp/socket/b3ee91f2f7e4e382f6395d3d5ead9ac24757b9bed6e86090069cab68c6477b28/attach: no such file or directory

**Steps to reproduce the issue:**

1. Create a directory whose path is 25 characters long

2. `export XDG_RUNTIME_DIR=$created_directory`

3. `podman run -it ubuntu /bin/bash`

**Describe the results you received:**

Error: failed to connect to container's attach socket: ${XDG_RUNTIME_DIR}/libpod/tmp/socket/b3ee91f2f7e4e382f6395d3d5ead9ac24757b9bed6e86090069cab68c6477b28/attach: no such file or directory

**Describe the results you expected:**

Running container

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Comment by mheon** [comment]
What Podman version? I'm fairly certain this was fixed as of 3.0.x.

**Comment by zv0n** [comment]
Version 3.0.1

**Comment by rhatdan** [comment]
Since the maximum length of a unix domain socket is 104 chars, that seems to be the issue.  I know there were fixes for this in both Podman and Conmon.  @haircommander @giuseppe PTAL

**Comment by haircommander** [comment]
https://github.com/containers/podman/pull/8979 should fix, which I've had trouble getting over the finish line. hopefully conmon 2.0.27 will solve the last CI problems with it

**Comment by zv0n** [comment]
@rhatdan I don't think it's the socket path issue as the path to the directory containing the socket (the one that's being symlinked to) is longer than the symlink path.

Also if I make the runtime directory path longer it works just fine. The 25 character long runtime path is the only one I've found so far that exhibits this behavior. If I had to guess I'd think that there might be a buffer problem somewhere that causes the last char to disappear. I don't know golang, but in C I'd think that somewhere `strlen` might say that the desired path can fit in buffer exactly, but then `strncpy` would replace the last character with `\0`. But as I said originally I couldn't find handling of this symlink in the source code, so I can't verify my hunch :/

**Comment by zv0n** [comment]
@haircommander nice, thanks for letting me know. I'll test the new version out when it's ready and hopefully the problem will be gone :)

**Comment by baude** [comment]
@zv0n 2.0.27 is out now ... if you are happy, please close this issue.

**Comment by rhatdan** [comment]
Let's reverse this and say reopen if it does not fix the issue.

**Comment by zv0n** [comment]
Hi, I've updated conmon to 2.0.27 and the issue persists.

`XDG_RUNTIME_DIR="/test/dir/podman/runtime" podman --root=/test/dir/podman run -it ubuntu /bin/bash`

results in: `Error: failed to connect to container's attach socket: /test/dir/podman/runtime/libpod/tmp/socket/460fb287adb6629610497aea213c97f0fe1d5fa6001f9374c7a89ad4773e7719/attach: no such file or directory`

but

`XDG_RUNTIME_DIR="/test/dir/podman/runtime2" /usr/bin/podman-real --root=/test/dir/podman run -it ubuntu /bin/bash`

results in a running container

**Comment by rhatdan** [comment]
@zv0n Does this issue still persist?

**Comment by rhatdan** [comment]
Since I got no response, I will assume it no longer exists.  Reopen if I am mistaken.
