### ISSUE TITLE
podman load with invalid input has 0 (success) exit code

### ISSUE THREAD

**Issue by martinetd** [containers/podman#9672]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature
(not quite sure there :D I swear I'm not just trying to use podman randomly like a fuzzer...!)

**Description**

if podman load failed to parse the input I believe it should error out not just in messages but also in its exit code
(mostly-unrelated: it's a shame saved images can't be signed somehow, or am I missing something?)

**Steps to reproduce the issue:**

```
$ echo garbled input | podman load
  open /var/tmp/podman877531368/manifest.json: not a directory
  open /var/tmp/podman877531368/index.json: not a directory
Loaded image(s): 

$ echo $?
0
```

I'm -very bad- at go, but pulling a debugger out it looks like a simple assignment problem in libpod/runtime_img.go (err goes out of scope after the if, so `saveErr = err` only ever saves "nil")?
With this diff:
```
diff --git a/libpod/runtime_img.go b/libpod/runtime_img.go
index 6e1105b9e3f5..76cd03dc0ebd 100644
--- a/libpod/runtime_img.go
+++ b/libpod/runtime_img.go
@@ -316,7 +316,8 @@ func() (types.ImageReference, error) {
        } {
                src, err := referenceFn()
                if err == nil && src != nil {
-                       if newImages, err := r.ImageRuntime().LoadFromArchiveReference(ctx, src, signaturePolicy, writer); err == nil {
+                       newImages, err := r.ImageRuntime().LoadFromArchiveReference(ctx, src, signaturePolicy, writer)
+                       if err == nil {
                                return getImageNames(newImages), nil
                        }
                        saveErr = err
```
I get:
```
$ ./bin/podman load -i foo
  open foo/manifest.json: not a directory
  open foo/index.json: not a directory
Error: error pulling image: unable to pull oci:foo:: 1 error occurred:
	* Error initializing source oci:foo:: open foo/index.json: not a directory

$ echo $?
125
```

The error only displaying the last handler's error isn't necessarily the most obvious for users but at least an error bubbles up as it looks like the code originally intended. Happy to submit that as a PR if that makes sense (I'm not sure if this project has a policy to always refer to an issue for each PR? Some people don't like PRs that hadn't been discussed first)

**Output of `podman version`:**

```
Version:      3.1.0-dev
API Version:  3.1.0-dev
Go Version:   go1.15.8
Git Commit:   b7c00f2cc03499d5d385a7aa7e8cd35d0ab994d7-dirty
Built:        Mon Mar  8 19:01:05 2021
OS/Arch:      linux/amd64
```

**Comment by vrothberg** [comment]
Thanks for reporting, @martinetd!
I will take a look now.

**Comment by vrothberg** [comment]
Opened https://github.com/containers/podman/pull/9677.
