### ISSUE TITLE
Containers archive endpoint does not include x-docker-container-path-stat header

### ISSUE THREAD

**Issue by jwhonce** [containers/podman#9680]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
pkg/api/handlers/compat/containers_archive.go should include the header x-docker-container-path-stat in the response.

**Steps to reproduce the issue:**

1. curl -v .../containers/{name}/archive?path=/etc/motd
2. Review output for x-docker-container-path-stat header

**Describe the results you received:**
Header not seen.

**Describe the results you expected:**
Header in output

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
as of 3.0.2
```

**Comment by jmguzik** [comment]
@jwhonce I wanted to look at this issue but output from newest podman that this header is present:

```
$ curl -v --unix-socket /run/user/1000/podman/podman.sock http://d/v3.0.0/containers/f2a52dc2a82c/archive?path=/etc/motd -o motd
*   Trying /run/user/1000/podman/podman.sock:0...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to d (/run/user/1000/podman/podman.sock) port 80 (#0)
> GET /v3.0.0/containers/f2a52dc2a82c/archive?path=/etc/motd HTTP/1.1
> Host: d
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Api-Version: 1.40
< Content-Type: application/x-tar
< Libpod-Api-Version: 3.1.0-dev
< Server: Libpod/3.1.0-dev (linux)
< X-Docker-Container-Path-Stat: eyJuYW1lIjoibW90ZCIsInNpemUiOjI4MywibW9kZSI6NDIwLCJtdGltZSI6IjIwMTktMDYtMTdUMTE6MDA6MTYrMDI6MDAiLCJpc0RpciI6ZmFsc2UsImxpbmtUYXJnZXQiOiIvZXRjL21vdGQifQ==
< Date: Sat, 13 Mar 2021 00:02:55 GMT
< Content-Length: 2048
< 
{ [2048 bytes data]
100  2048  100  2048    0     0  15058      0 --:--:-- --:--:-- --:--:-- 15058
* Connection #0 to host d left intact
```

`X-Docker-Container-Path-Stat: eyJuYW1lIjoibW90ZCIsInNp...` is the thing I think.

**Comment by vrothberg** [comment]
I'd also be surprised if we regressed on that since we're testing that in the `apiv2` tests. @jwhonce, did you myabe use an old version?
