### ISSUE TITLE
podman load fails in a cross environment using docker

### ISSUE THREAD

**Issue by kjeldflarup** [containers/podman#9701]
/kind feature

I want to run this command inside a docker container
```
podman --root $TMP/appfs/containers load --input $SRCOCI
```
The goal is to generate an unpacked container which I want to copy to an embedded controller.  
Thus I'm in a cross building environment and do not really want to be root.

I get this error
```
+ podman --root /tmp/tmp.ddqTLtnoM3/appfs/containers load --input build/tmp-glibc/deploy/images/pcm31/AMC300-PCM31_CODESYS3.5.15.20_v1.0.0.0local75-g3525e1a.oci
cannot clone: Operation not permitted
Error: cannot re-exec process
```
Trying with sudo
```
+ sudo podman --root /tmp/tmp.lfjsAIT1Kr/appfs/containers load --input build/tmp-glibc/deploy/images/pcm31/AMC300-PCM31_CODESYS3.5.15.20_v1.0.0.0local75-g3525e1a.oci
Error: 'overlay' is not supported over overlayfs, a mount_program is required: backing file system is unsupported for this graph driver

```

**Steps to reproduce the issue:**
It seems that the problem also exist just running `podman version`

Create this Dockerfile
```
FROM debian:10.4

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -q update \
    && apt-get install -y --no-install-recommends \
    	ca-certificates \
	gnupg \
        wget 

RUN echo 'deb http://deb.debian.org/debian buster-backports main' >> /etc/apt/sources.list \
    && echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list \
    && wget -O- https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/Release.key | apt-key add - \
    && apt-get -q update \
    && apt-get -y -t buster-backports install libseccomp2 podman

RUN podman version
```

```
docker build .
```

**Describe the results you received:**
 ```
---> Running in c6094608be98
Error: 'overlay' is not supported over overlayfs, a mount_program is required: backing file system is unsupported for this graph driver
The command '/bin/sh -c podman version' returned a non-zero code: 125
```

**Describe the results you expected:**
```
$ podman version
Version:      2.2.1
API Version:  2.1.0
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I assume that podman does some check on startup, that it is able to run the container.  
But I do not need that. 

I have success doing the load and copying it to my controller. The problem arrives when I try to add the commands to CI.

**Output of `podman version`:**

```
Error: 'overlay' is not supported over overlayfs, a mount_program is required: backing file system is unsupported for this graph driver
The command '/bin/sh -c podman info --debug' returned a non-zero code: 125
```

**Output of `podman info --debug`:**

```
Error: 'overlay' is not supported over overlayfs, a mount_program is required: backing file system is unsupported for this graph driver
The command '/bin/sh -c podman info --debug' returned a non-zero code: 125
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Listing...
podman/unknown,now 100:3.0.1-2 amd64 [installed]
podman/unknown 100:3.0.1-2 arm64
podman/unknown 100:3.0.1-2 armhf
podman/unknown 100:3.0.1-2 ppc64el
podman/unknown 100:3.0.1-2 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

I dont know how close the Docker recipe is to the latest.

The trouble shooting guide and all articlesfound via Google assumes that I want to do a `podman run`

**Comment by rhatdan** [comment]
@giuseppe Any idea what is going on here?

**Comment by giuseppe** [comment]
We need to use fuse-overlayfs inside of the container.  Is the container configured for it?

**Comment by rhatdan** [comment]
I just did this in my homedir, is this what you are attemping?

```
podman (buildah) $ podman save --format oci-archive alpine -o /tmp/foobar.oci
podman (buildah) $ file /tmp/foobar.oci 
/tmp/foobar.oci: POSIX tar archive
podman (buildah) $ podman --root /tmp/dan/containers load --input /tmp/foobar.oci 
Getting image source signatures
Copying blob a4fd5de14e9e done  
Copying config 781257a41f done  
Writing manifest to image destination
Storing signatures
Loaded image(s): localhost/alpine
podman (buildah) $ ls /tmp/dan/containers/
libpod  mounts  overlay  overlay-containers  overlay-images  overlay-layers  storage.lock  tmp  userns.lock
```

**Comment by kjeldflarup** [comment]
@giuseppe after seeing similar problems with buildah I found that running the fedora image from quay.io worked better.   
But that did not help me with podman

```
$ docker run -it --rm --security-opt seccomp=unconfined     --security-opt apparmor=unconfined      quay.io/podman/stable:latest podman version
Error: mount /var/lib/containers/storage/overlay:/var/lib/containers/storage/overlay, flags: 0x1000: operation not permitted
```

Do I need some modification of my docker runner?

Also, is some fixing needed inside the container? The rest of my Dockerfiles are based on debian tool chain, thus I would prefer to have a apt based Docker recipe.

**Comment by kjeldflarup** [comment]
@rhatdan Yes

**Comment by kjeldflarup** [comment]
I found a solution by changing the driver to vfs rather than overlay
```
sed -i -e 's|^driver = "overlay"|driver = "vfs"|g' /etc/containers/storage.conf
```

This works out of the box for docker, for both `podman` and `buildah`,   
but what are the drawbacks of this?

**Comment by rhatdan** [comment]
vfs is just a very slow and disk intensive driver.  Basically each layer is an entire copy of the underlying layer + changes.

**Comment by kjeldflarup** [comment]
As I only plan to put a single layer container on my controller, I can live with that.

However I may face this problem again in the future. So I'm quite curious about what the difference is in the Docker setups on Fedora and Ubuntu.

**Comment by rhatdan** [comment]
Not really sure of the question, but for what you are attempting to do, there is no difference between Fedora and Ubuntu.

**Comment by kjeldflarup** [comment]
@rhatdan  I'm wondering why the command in https://github.com/containers/podman/issues/9701#issuecomment-797532184 fails.

**Comment by rhatdan** [comment]
Try 

docker run --user=podman --device=/dev/fuse -it --rm --security-opt seccomp=unconfined     --security-opt apparmor=unconfined      quay.io/podman/stable:latest podman version

Or

docker run --cap-add SYS_ADMIN -it --rm --security-opt seccomp=unconfined     --security-opt apparmor=unconfined      quay.io/podman/stable:latest podman version

If you want to mount a file system as root, you need to have CAP_SYSADMIN, or run with a user namespace and mount namespace.

**Comment by rhatdan** [comment]
```
sh-5.1# docker run --user=podman --device=/dev/fuse -it --rm --security-opt seccomp=unconfined     --security-opt apparmor=unconfined      quay.io/podman/stable:latest podman version
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.8
Built:        Fri Feb 19 16:56:17 2021
OS/Arch:      linux/amd64
sh-5.1# docker run --cap-add cap-sysadmin -it --rm --security-opt seccomp=unconfined     --security-opt apparmor=unconfined      quay.io/podman/stable:latest podman version
docker: Error response from daemon: invalid CapAdd: unknown capability: "CAP_CAP-SYSADMIN".
See 'docker run --help'.
sh-5.1# docker run --cap-add SYS_ADMIN -it --rm --security-opt seccomp=unconfined     --security-opt apparmor=unconfined      quay.io/podman/stable:latest podman version
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.8
Built:        Fri Feb 19 16:56:17 2021
OS/Arch:      linux/amd64
```
