### ISSUE TITLE
podman container root able to write to file with no write permissions

### ISSUE THREAD

**Issue by millerthegorilla** [containers/podman#9704]
podman version 2.2.1

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. pull python latest image from dockerhub.  Run container with podman run -d -it --pod $POD_NAME --name $CONTAINER_NAME -v $WORKING_DIR:/opt/$DJANGO_PROJECT_NAME:Z  $IMAGE

2. run  podman exec -it $CONTAINER_NAME bash

3. create file, set permissions to 0400, run nano (installed with apt-get) on the file, write some stuff, save and exit.

**Describe the results you received:**
a file with some stuff in it.

**Describe the results you expected:**
an empty file, with nano faulting, stating 'no write permissions'

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 2.2.1
```

**Output of `podman info --debug`:**

```
$ podman info --debug
host:
  arch: arm64
  buildahVersion: 1.18.0
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.22-0.9.dev.git2fbeb9f.fc34.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.22-dev, commit: 7ee193aa813bd12547208482be359529ebcd3c9d'
  cpus: 4
  distribution:
    distribution: fedora
    version: "34"
  eventLogger: journald
  hostname: fedora
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.11.3-300.fc34.aarch64
  linkmode: dynamic
  memFree: 6515929088
  memTotal: 8217497600
  ociRuntime:
    name: crun
    package: crun-0.18-1.fc34.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 0.18
      commit: 808420efe3dc2b44d6db9f1a3fac8361dde42a95
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-3.dev.git6dc0186.fc34.aarch64
    version: |-
      slirp4netns version 1.1.8+dev
      commit: 6dc0186e020232ae1a6fcc1f7afbc3ea02fd3876
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 8216637440
  swapTotal: 8216637440
  uptime: 6h 45m 50.13s (Approximately 0.25 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /var/home/pod_server/.config/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.4+dev-2.dev.gitee8ce2e.fc34.aarch64
      Version: |-
        fusermount3 version: 3.10.2
        fuse-overlayfs: version 1.4
        FUSE library version 3.10.2
        using FUSE kernel interface version 7.31
  graphRoot: /var/home/pod_server/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 8
  runRoot: /run/user/1000/containers
  volumePath: /var/home/pod_server/.local/share/containers/storage/volumes
version:
  APIVersion: 2.1.0
  Built: 1607438288
  BuiltTime: Tue Dec  8 14:38:08 2020
  GitCommit: ""
  GoVersion: go1.15.5
  OsArch: linux/arm64
  Version: 2.2.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
using rpm-ostree, running on fedora-IOT-aarch64.  Have pinned podman version to 2.2.1 as the later 3.0.1 (current), does not allow me to connect successfully to a container in a pod -- issue #9532 
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No, cannot.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Are you running as root, or without?

**Comment by rhatdan** [comment]
I believe this would happen without containers at all.  Try this outside of a container and the same thing should happen.  The issue is you have the ability to write to the directory, and NANO is probably creating a temporary file and then renaming over you file, which does not take the permissions of the existing file into account.

**Comment by millerthegorilla** [comment]
Sorry, I should have mentioned, I am running rootless.

**Comment by millerthegorilla** [comment]
wowzers.  I just checked on my linux, and root can indeed write to files without permissions set.  I knew root would have the power to change the permissions and then write, but I didn't know that root could ignore permissions and just write regardless... doh.
many thanks for your help.
