### ISSUE TITLE
Ubuntu packages missing dependency package "uidmap"

### ISSUE THREAD

**Issue by prof7bit** [containers/podman#9707]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

After installation it is missing the binary "newuidmap"

**Steps to reproduce the issue:**

1. Install a fresh copy of Ubuntu 20.04 (from Armbian) on a Rock64 SoC

2. add the apt repository as instructed on https://podman.io/getting-started/installation which results in this deb line in the sources: 
```
deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /
```
and then 
```
apt update && apt install podman
```
it will install with no errors and also run as root but will refuse to run rootless as a normal user:
```
Error: cannot find newuidmap: exec: "newuidmap": executable file not found in $PATH
```

The problem can be easily fixed if the missing package is installed. On Ubuntu the missing package is ```uidmap``` and it is available in the official Ubuntu repositories. This package should be added to the dependencies of the .deb package so it will make sure it is pulled in during apt-get on such installations where it does not seem to be installed by default.

**Describe the results you expected:**
should have pulled all needed dependencies

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**
```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.2
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/arm64
```

**Output of `podman info --debug`:**

```
host:
  arch: arm64
  buildahVersion: 1.19.4
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.26, commit: '
  cpus: 4
  distribution:
    distribution: ubuntu
    version: "20.04"
  eventLogger: journald
  hostname: rock
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.10.21-rockchip64
  linkmode: dynamic
  memFree: 1303564288
  memTotal: 2011365376
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.18.1-7931a-dirty
      commit: 7931a1eab0590eff4041c1f74e2844b297c31cea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 1005678592
  swapTotal: 1005678592
  uptime: 59m 58.84s
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/bernd/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /home/bernd/.local/share/containers/storage
  graphStatus: {}
  imageStore:
    number: 0
  runRoot: /run/user/1000/containers
  volumePath: /home/bernd/.local/share/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.15.2
  OsArch: linux/arm64
  Version: 3.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
bernd@rock:~$ apt list podman
Auflistung... Fertig
podman/unbekannt 100:3.0.1-2 amd64
podman/unbekannt,now 100:3.0.1-2 arm64  [installiert]
podman/unbekannt 100:3.0.1-2 armhf
podman/unbekannt 100:3.0.1-2 s390x
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Comment by afbjorklund** [comment]
It is "recommended" but not required, since it is not needed when running `sudo podman`

Depends: libseccomp2 (>= 2.4.3-1), libdevmapper1.02.1, libgpgme11, catatonit, conmon (>= 100:2.0.25~2), containers-common (>= 100:1-12), dbus-user-session, iptables, podman-plugins (>= 100:1.1.1-5), crun (>= 100:0.17-4)
Recommends: slirp4netns (>= 100:1.1.8-3), containernetworking-plugins (>= 100:0.9.1-1), **uidmap**, fuse-overlayfs

**Comment by vrothberg** [comment]
@lsm5 PTAL

**Comment by rhatdan** [comment]
Yes this is fine,  it is a recommends since it is not required for running podman as root.
