### ISSUE TITLE
How to run Podman service in rootless mode with Debian 10

### ISSUE THREAD

**Issue by cmonty14** [containers/podman#9709]
Hello,

I have installed Podman version 3.0.1 on my Debian 10 system:
```
locadmin@pc4-pve:~$ podman -v
podman version 3.0.1
```

Based on the announcement regarding RESTful API here I want to have podman service in $XDG_RUNTIME_DIR/podman/podman.sock.

However, there's 1 problem:
Directory _/run/user/1000/podman_ and file _podman.sock_ does not exist.

```
locadmin@pc4-pve:~$ ll /run/user/1000/
total 0
srw-rw-rw- 1 locadmin locadmin   0 Mar 14 11:25 bus
drwx------ 2 locadmin locadmin  40 Mar 14 11:28 containers
drwx------ 3 locadmin locadmin  60 Mar 14 11:28 dbus-1
drwx------ 2 locadmin locadmin 140 Mar 14 11:25 gnupg
drwx-----T 2 locadmin locadmin  40 Mar 14 11:28 libpod
srw-rw-rw- 1 locadmin locadmin   0 Mar 14 11:25 pk-debconf-socket
drwxr-xr-x 3 locadmin locadmin 100 Mar 14 11:28 systemd
```

Please advise how to fix this error.

There's no problem with podman server running in rootfull mode; the file _/run/user/0/podman/podman.sock_ exists.

Regards
Thomas

**Comment by Krejza9** [comment]
I think it's the same bug as this #9280 
Unfortunately, it is still not fixed
