### ISSUE TITLE
Don't remove a secret if a running container is using it

### ISSUE THREAD

**Issue by chuanchang** [containers/podman#9712]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. printf "This is a secret" | ./bin/podman secret create my_secret_data -

2. ./bin/podman run -td --secret my_secret_data --name bar quay.io/libpod/alpine sleep 120
3. ./bin/podman secret rm my_secret_data

**Describe the results you received:**
```
[cloud-user@rhel-8 podman]$ ./bin/podman run -td --secret my_secret_data --name bar quay.io/libpod/alpine sleep 120
aeb5f2136e8e6ec1a0305057f40d0ff51010d782aee1175634a2aa2d40725f0f
[cloud-user@rhel-8 podman]$ ./bin/podman ps
CONTAINER ID  IMAGE                  COMMAND    CREATED        STATUS            PORTS   NAMES
aeb5f2136e8e  quay.io/libpod/alpine  sleep 120  7 seconds ago  Up 7 seconds ago          bar
[cloud-user@rhel-8 podman]$ ./bin/podman secret rm my_secret_data
28dc97ebf57228c144b8fa7c4
[cloud-user@rhel-8 podman]$ ./bin/podman secret ls
ID          NAME        DRIVER      CREATED     UPDATED
```

**Describe the results you expected:**
fix it

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ git rev-parse HEAD
789d579bc43cab0a179a17276478100b4b80e6fc

$ ./bin/podman --version
podman version 3.1.0-dev
```

**Output of `podman info --debug`:**

```
[cloud-user@rhel-8 podman]$ ./bin/podman info --debug
host:
  arch: amd64
  buildahVersion: 1.19.7
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.22-3.module+el8.4.0+9425+98db097b.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.22, commit: 3d0d8a951111b09390d39370fc42f109aa8030e5'
  cpus: 4
  distribution:
    distribution: '"rhel"'
    version: "8.4"
  eventLogger: file
  hostname: rhel-8.4.0-x86-64-nightly-latest-longterm-1
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-277.el8.x86_64
  linkmode: dynamic
  memFree: 785059840
  memTotal: 3917033472
  ociRuntime:
    name: crun
    package: crun-0.16-2.module+el8.4.0+9425+98db097b.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.16
      commit: eb0145e5ad4d8207e84a327248af76663d4e50dd
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.8-1.module+el8.4.0+9425+98db097b.x86_64
    version: |-
      slirp4netns version 1.1.8
      commit: d361001f495417b880f20329121e3aa431a8f90f
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 0
  swapTotal: 0
  uptime: 352h 35m 38.25s (Approximately 14.67 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/cloud-user/.config/containers/storage.conf
  containerStore:
    number: 3
    paused: 0
    running: 0
    stopped: 3
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.3.0-1.module+el8.4.0+9425+98db097b.x86_64
      Version: |-
        fusermount3 version: 3.2.1
        fuse-overlayfs: version 1.3
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/cloud-user/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /run/user/1000/containers
  volumePath: /home/cloud-user/.local/share/containers/storage/volumes
version:
  APIVersion: 3.1.0-dev
  Built: 1615256959
  BuiltTime: Mon Mar  8 21:29:19 2021
  GitCommit: 789d579bc43cab0a179a17276478100b4b80e6fc
  GoVersion: go1.15.5
  OsArch: linux/amd64
  Version: 3.1.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ ./bin/podman --version
podman version 3.1.0-dev
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Openstack VM

**Comment by vrothberg** [comment]
Thanks for reaching out, @chuanchang! Can you elaborate on why this behavior is problematic?

@ashley-cui and I were chatting about this scenario early on during development. We thought it's not a problem since the container can continue using the secret, even if it was removed while the container is still running. The important part is that the container can still access the data which is the case, since the secret is data is copied into the container.

**Comment by chuanchang** [comment]
> Thanks for reaching out, @chuanchang! Can you elaborate on why this behavior is problematic?
> 

IMO, we shouldn't allow to remove a secret if a service or running container is using it, but as you said, it's okay because the secret is copied into the container, although the secret still works well, we can't list/inspect this secret by podman secret command outside of container, docker doesn't allow to delete a secret if a service is using it - https://docs.docker.com/engine/swarm/secrets/,

**Comment by vrothberg** [comment]
Thanks for elaborating!

@rhatdan @ashley-cui what do you think?

**Comment by ashley-cui** [comment]
I think it's okay if we remove a secret if a container is still using it - a list/inspect doesn't give much info about the secret other than its name and time created - which doesn't have much to do with the secret data actually mounted into the container. Docker's behavior is mostly because secrets are used only in swarms. And also, the container will work anyway if the secret is deleted.

**Comment by rhatdan** [comment]
I agree, do we even record whether or not a secret is used by a container? I guess the only concern would be if a user created a secret then a container based off of it, then removed and re-added a different secret of the same name. would they expect the secret to change within the container?

**Comment by vrothberg** [comment]
> I agree, do we even record whether or not a secret is used by a container? 

I don't think so.  The implementation is very transparent which I find elegant.  Secrets are mounted at container creation as tmpfs mounts.

> I guess the only concern would be if a user created a secret then a container based off of it, then removed and re-added a different secret of the same name. would they expect the secret to change within the container?

That would require a bind mount which isn't secure, so I hope that's not a common expectation. @ashley-cui, do you think we should explain this specific behavior in the man pages?

**Comment by rhatdan** [comment]
Yes lets update the man pages to explain what is going on, and then we can close this issue.
