### ISSUE TITLE
Bash tab completion doesn't work if you specify arguments/options

### ISSUE THREAD

**Issue by gcs278** [containers/podman#9730]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Bash tab completion works for the most part in podman, but if you have an argument or option flags, it breaks the completion. Take `podman exec` for example. `podman exec <tab>` works, but `podman exec -it <tab>` does not.

Docker does successfully tab with arguments (like `docker exec -it <tab>`). This might seem harmless, but does make rapid development a little more difficult as I use `podman exec -it container bash` a lot to jump into my containers.

**Steps to reproduce the issue:**

1. `podman exec -it <tab>`

**Describe the results you received:**

It auto completes to the normal bash filesystem

**Describe the results you expected:**

 A listing of the available containers just like `podman exec <tab>`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.0.0-dev
API Version:  3.0.0
Go Version:   go1.15.7
Built:        Tue Feb  2 17:06:33 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.2
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.25-1.module_el8.4.0+673+eabfc99d.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: 897f4ebd69b9e9c725621fabf1d7c918ef635a68'
  cpus: 10
  distribution:
    distribution: '"rhel"'
    version: "8.0"
  eventLogger: file
  hostname: rhel8
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-80.el8.x86_64
  linkmode: dynamic
  memFree: 393658368
  memTotal: 10055262208
  ociRuntime:
    name: crun
    package: crun-0.17-1.module_el8.4.0+673+eabfc99d.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 5696h 37m 42.4s (Approximately 237.33 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 12
    paused: 0
    running: 1
    stopped: 11
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /root/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 6
  runRoot: /root/containers/runroot/storage
  volumePath: /root/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1612303593
  BuiltTime: Tue Feb  2 17:06:33 2021
  GitCommit: ""
  GoVersion: go1.15.7
  OsArch: linux/amd64
  Version: 3.0.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.0.0-0.33rc2.module_el8.4.0+673+eabfc99d.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by zhangguanzhang** [comment]
@Luap99 PTAL

**Comment by Luap99** [comment]
This is a know bug in the cobra library. I have opened a PR https://github.com/spf13/cobra/pull/1258 to fix this this but unfortunately it is not merged yet. I know this is annoying. As a workaround I recommend using `podman exec -i -t [TAB]`.

**Comment by mheon** [comment]
I'll assign @Luap99 so he remembers to close this whenever that Cobra issue closes.

Speaking of, we really need to get more attention on the Cobra PRs he has open.

**Comment by zhangguanzhang** [comment]
@Luap99 PTAL

**Comment by Luap99** [comment]
https://github.com/spf13/cobra/pull/1258 has been merged upstream. A new cobra release is following soon (https://github.com/spf13/cobra/issues/1388). Once this is done we can update podman.

**Comment by Luap99** [comment]
Still waiting for a new cobra release.

**Comment by rhatdan** [comment]
@Luap99 any idea when this is going to happen?  Is there someone we should nag?

**Comment by Luap99** [comment]
Hopefully soon, see https://github.com/spf13/cobra/issues/1388
