### ISSUE TITLE
Can't set mac address in podman play kube for cni DHCP plugin

### ISSUE THREAD

**Issue by gcs278** [containers/podman#9731]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

With `podman play kube`, there currently isn't a way to set the mac address so that the CNI DHCP plugin will be able to utilize it. `podman create pod` offers a `--mac-address`, but `podman play kube` does not. I did discover that I can use the [tuning plugin](https://www.cni.dev/plugins/meta/tuning/) to set the mac address, however, due to another issue with tuning (https://github.com/containernetworking/plugins/issues/450#issuecomment-582078010), you cannot use it to set the mac address that DHCP uses. So tuning is useless for setting the MAC address for the DHCP plugin.

Regardless, it seems like more arguments like `--mac-address` should be exposed to `podman play kube` just like they are exposed in `podman pod create`. This would allow for the ability to set the MAC address in pods started by `podman play kube`.

**Steps to reproduce the issue:**

1. `podman play kube --mac-address=<MAC_ADDRESS> <YAML>`

**Describe the results you received:**

Argument not supported

**Describe the results you expected:**

Ability to set the MAC address with `--mac-address`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.0.0-dev
API Version:  3.0.0
Go Version:   go1.15.7
Built:        Tue Feb  2 17:06:33 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.2
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.25-1.module_el8.4.0+673+eabfc99d.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.25, commit: 897f4ebd69b9e9c725621fabf1d7c918ef635a68'
  cpus: 10
  distribution:
    distribution: '"rhel"'
    version: "8.0"
  eventLogger: file
  hostname: rhel8
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-80.el8.x86_64
  linkmode: dynamic
  memFree: 393658368
  memTotal: 10055262208
  ociRuntime:
    name: crun
    package: crun-0.17-1.module_el8.4.0+673+eabfc99d.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.17
      commit: 0e9229ae34caaebcb86f1fde18de3acaf18c6d9a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_NET_RAW,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 5696h 37m 42.4s (Approximately 237.33 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 12
    paused: 0
    running: 1
    stopped: 11
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /root/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 6
  runRoot: /root/containers/runroot/storage
  volumePath: /root/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1612303593
  BuiltTime: Tue Feb  2 17:06:33 2021
  GitCommit: ""
  GoVersion: go1.15.7
  OsArch: linux/amd64
  Version: 3.0.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.0.0-0.33rc2.module_el8.4.0+673+eabfc99d.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
Re-tagging as feature request, given this is a request for a new flag or two on `play kube`.

**Comment by rhatdan** [comment]
@Luap99 since you were in podman play code recently, would you be interested in opening a PR for this?

**Comment by Luap99** [comment]
PR #10208
