### ISSUE TITLE
podman run or restore: requested cgroup controller `pids` is not available

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#9752]
Another one of those hard-to-track-down flakes that appears in different tests:
```
# podman-remote run [...]
Error: error preparing container <sha> for attach: the requested cgroup controller `pids` is not available: OCI runtime error
```
Only two instances, both in the last two days, both on Ubuntu 2010:

## sys: podman cp - will not recognize symlink pointing into host space
* gce_instance:ubuntu : sys remote ubuntu-2010 root host
  * PR #9732
    * [03-17 10:25](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5824604364079104/html/sys-remote-ubuntu-2010-root-host.log.html)

## sys: Verify /run/.containerenv exist
* gce_instance:ubuntu : sys remote ubuntu-2010 root host
  * PR #9717
    * [03-16 18:00](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6332135817609216/html/sys-remote-ubuntu-2010-root-host.log.html)

**Comment by edsantiago** [comment]
Two more instances, both on the same test run:

## sys: podman run : --userns=keep-id: passwd file is modifiable
* gce_instance:ubuntu : sys remote ubuntu-2010 root host
  * PR #9789
    * [03-23 14:37](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6192426571268096/html/sys-remote-ubuntu-2010-root-host.log.html)

## sys: podman run : add username to /etc/passwd if --userns=keep-id
* gce_instance:ubuntu : sys remote ubuntu-2010 root host
  * PR #9789
    * [03-23 14:37](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6192426571268096/html/sys-remote-ubuntu-2010-root-host.log.html)

**Comment by edsantiago** [comment]
And another: again in [remote ubuntu-2010 root](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5413539620847616/html/sys-remote-ubuntu-2010-root-host.log.html)

**Comment by zhangguanzhang** [comment]
I think some runner machine does not enable the `pids` cgroup

**Comment by edsantiago** [comment]
Another:
* instance:GCEInstance : sys remote ubuntu-2010 root host
  * PR #9939
    * [04-05 11:54](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5579517088497664/html/sys-remote-ubuntu-2010-root-host.log.html)

**Comment by edsantiago** [comment]
Two more:
## sys: podman run : user namespace preserved root ownership
* instance:GCEInstance : sys podman ubuntu-2010 root host
  * PR #9963
    * [04-07 12:08](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6696057238192128/html/sys-podman-ubuntu-2010-root-host.log.html)

## sys: podman run docker-archive
* instance:GCEInstance : sys podman ubuntu-2010 root host
  * PR #9963
    * [04-07 11:49](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6603680494387200/html/sys-podman-ubuntu-2010-root-host.log.html)

**Comment by edsantiago** [comment]
Now seeing it in [buildah CI](https://api.cirrus-ci.com/v1/task/4988969839493120/logs/setup.log), in setup (the registry thing) in https://github.com/containers/buildah/pull/3186/checks?check_run_id=2450159721

**Comment by edsantiago** [comment]
Okay... so I'm working on #11957, and in my local (laptop) testing, I'm seeing this flake about once in every 5-10 runs. This means that, if my PR gets merged, it will flake in half of CI runs. This flake needs to be fixed. Pretty please? Here's the best reproducer I can offer:
```console
$ while :;do sudo bin/podman run -d --name foo quay.io/libpod/testimage:20210610 sh -c 'while :;do cat /proc/uptime;done';sudo bin/podman container checkpoint foo;sudo bin/podman container logs foo >/dev/null;sudo bin/podman container inspect foo >/dev/null;sleep 0.5;sudo bin/podman container restore foo || break;sudo bin/podman container rm -f -t 0 foo;done
...
4476405605bf413c7f2305ec9e19abba6044175514dcb4947b024daf3c97cfa3
Error: OCI runtime error: the requested cgroup controller `pids` is not available
```
It's a poor reproducer: in one attempt, it failed within seconds. On another, it ran fine for 15 minutes. I will try to work on a better one, but right now I need to move on for the day.

**Comment by giuseppe** [comment]
it is an issue in crun (or better I think in the kernel), but in any case, we need to account for it in crun.  I am still validating my patch, opening a PR as soon as I've finished testing it

**Comment by giuseppe** [comment]
PR here: https://github.com/containers/crun/pull/758

**Comment by edsantiago** [comment]
The "requested cgroup controller 'pids' is not available" message also appeared (not recently) in the cgroups=split test:

### Podman run [It] podman run with cgroups=split
* fedora-34 : int podman fedora-34 root host
  * PR #11834
    * [10-01 16:37](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6739354816086016/html/int-podman-fedora-34-root-host.log.html#t--podman-run-with-cgroups-split--1)
* ubuntu-2104 : int podman ubuntu-2104 root host
  * PR #11605
    * [09-16 13:11](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6390454406086656/html/int-podman-ubuntu-2104-root-host.log.html#t--podman-run-with-cgroups-split--1)

**Comment by vrothberg** [comment]
containers/crun#758 has merged on Oct 19 and since CI is using newer cruns, I think we're good to close.  Please reopen if I am mistaken.

**Comment by emansom** [comment]
People are still running into this on RHEL 8 boxes see [#1897579](https://bugzilla.redhat.com/show_bug.cgi?id=1897579) on the bugzilla.

Doing a system-wide `systemctl daemon-reload` works as workaround.

However, it will still yield broken rootless containers on host restart. Is a systemd unit dependency for CGroup setup on the podman user units (I have them enabled, as well as linger for the user itself) missing?

**Comment by emansom** [comment]
Seems related to issue [#9578](https://github.com/systemd/systemd/issues/9578) in systemd. Can that fix be backported to RHEL 8?
