### ISSUE TITLE
Podman 3.0.1 :: As a non-root user inside a Fedora-33 docker-ce container, podman(1) fails with: "Error: cannot setup namespace using newuidmap: exit status 1". [Note: This was once working] ...

### ISSUE THREAD

**Issue by nmvega** [containers/podman#9753]
Hello Friends:

Environment:
- `Fresh install of Fedora-33 running inside a docker-ce container`
- `podman(1) version 3.0.1 is being used (installed via dnf(1) during "docker build [...]")`
- `Default podman configuration files (beneath /etc/) have not been modified.`
- `jdoe, the non-root user, has not implemented any podman(1) configuration overrides.`

Also:
```
jdoe@docker-ce-container$ grep jdoe /etc/subuid /etc/subgid
/etc/subuid:jdoe:100000:65536
/etc/subgid:jdoe:100000:65536
```
Under the above environment and configuration, `podman(1)` use to work, but now fails. All sub-commands fail with the following error:

```
jdoe@docker-ce-container$ podman version
Error: cannot setup namespace using newuidmap: exit status 1
```
As far as I can tell, the only command that works is:
```
jdoe@docker-ce-container$ podman -v
podman version 3.0.1
```
The only thing that I can think of as far as why this once worked but now fails, is that I freshly rebuilt the enclosing docker container (after many months -- just to freshen it), and perhaps it installed a newer major version of `podman(1) v3.x`; and this gave rise to this new issue.

Note that I didn't change anything in the `Dockerfile`; I simply rebuilt it.

Any ideas friends? Thank you in advance!

**Comment by mheon** [comment]
@rhatdan PTAL

**Comment by rhatdan** [comment]
Could you reinstall the shadow-utils (newuidmap) within the container.  And see if it works.  For some reason the file capabilities are not set by default.

**Comment by nmvega** [comment]
@rhatdan Absolutely. When I bring my cluster back up (likely tomorrow evening), I'll perform a `dnf -y reinstall shadow-utils` and let you know if that resolved the issue. If there is any other output that you would like to see (before or after), feel free to let me know. Hopefully it's something relatively simple either way. =:) Thank you.

**Comment by nmvega** [comment]
@rhatdan Hello Dan:

There is positive progress after running `dnf -y reinstall shadow-utils`.

I'm now able to `pull` and `ls` images; ... operations that I couldn't previously perform. However, there's now a pesky little `WARN`ing that appears after every sub-command:

```
jdoe@docker-ce-container$ podman pull docker.io/library/mariadb:latest
WARN[0000] Failed to detect the owner for the current cgroup: stat /sys/fs/cgroup/systemd/docker/e478aac5769b5a8d88c2b5c1c9c24ca79b3706ba075b535f67a5be969a4b04db: no such file or directory
[ ... snip ... ]

jdoe@docker-ce-container$ podman images
WARN[0000] Failed to detect the owner for the current cgroup: stat /sys/fs/cgroup/systemd/docker/e478aac5769b5a8d88c2b5c1c9c24ca79b3706ba075b535f67a5be969a4b04db: no such file or directory 
REPOSITORY                 TAG     IMAGE ID      CREATED       SIZE
docker.io/library/mariadb  latest  1138596852f3  33 hours ago  407 MB

jdoe@docker-ce-container$
```

Note that I'm running as `jdoe` (a normal user) and without `systemd` (and using `tini` instead):

```
jdoe@docker-ce-container$ ps -ef
UID        PID  PPID  C STIME TTY          TIME CMD
jdoe     1     0  0 20:53 ?        00:00:00 tini -g -- start-singleuser.sh --ip=0.0.0.
jdoe     6     1  0 20:53 ?        00:00:03 /opt/conda/bin/python /opt/conda/bin/jupyt
jdoe    57     6  0 20:53 pts/0    00:00:00 /bin/bash -l
jdoe   224     1  0 20:55 ?        00:00:00 podman
```

Given all of that, here are follow-on questions (and thank you in advance[!]):

1. When `building` the image, to avoid the original `namespace` error, what do you suggest I do? Do I run `dnf -y install podman && dnf -y reinstall shadow-utils` (during build)? Or implement some other configuration workaround? 

2. How do I fix the latter `WARN[0000]` issue, preferably without impacting performance? I noticed your comments in separate [issue thread](https://github.com/containers/podman/issues/5488), but didn't quite understand the resolution.

Thank you in advance!

**Comment by nmvega** [comment]
@rhatdan
UPDATE:

Regarding `Question 1` above, I rebuilt the `image` using the sequence I proposed, and that works. It's a little hacky in that it requires ordering of package installs, so if you have a better `workaround`, or if you know this will be addressed in an upcoming bug fix, feel free to let me know.

Regarding `Question 2` above, I still need help with that one. =:)

Thank you.

**Comment by rhatdan** [comment]
I think we should lower that warning to info, so that it will not show by default.
https://github.com/containers/podman/pull/9858
