### ISSUE TITLE
podman push oci-archive to oci-archive or docker registry without running a podman daemon [feature request]

### ISSUE THREAD

**Issue by sjackman** [containers/podman#9755]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I would like to push an `oci-archive` directory to a remote Docker Registry (GitHub Packages Container Registry ghcr.io) without running a podman daemon on both Linux in GitHub Actions and macOS for local development.

**Steps to reproduce the issue:**

```bash
podman push oci-archive:a oci-archive:b
```

**Describe the results you received:**

```
Error: cannot connect to the Podman socket, please verify that Podman REST API service is running: Get "http://d/v2.0.0/libpod/_ping": dial unix ///var/folders/_k/23rhw15x22d3f435jm716xkm0000gp/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```

**Describe the results you expected:**

The OCI archive `a/` is copied to `b/`.

**Additional information you deem important (e.g. issue happens only occasionally):**

The following commands are run on macOS using `brew install podman`, but my feature request also applies to Linux without running a Podman daemon.

**Output of `podman version`:**

```
Error: cannot connect to the Podman socket, please verify that Podman REST API service is running: Get "http://d/v2.0.0/libpod/_ping": dial unix ///var/folders/_k/23rhw15x22d3f435jm716xkm0000gp/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```

I'm using Podman version 3.0.1.

**Output of `podman info --debug`:**

```
Error: cannot connect to the Podman socket, please verify that Podman REST API service is running: Get "http://d/v2.0.0/libpod/_ping": dial unix ///var/folders/_k/23rhw15x22d3f435jm716xkm0000gp/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```console
$ brew list --versions podman
podman 3.0.1
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Currently running on macOS, but I have the same question for running on Linux without a Podman daemon running.

**Comment by mheon** [comment]
What you're describing is perfectly possible on Linux - the Podman service is not required for any Podman operations. My best guess is that you're using a remote-only Podman build in that case, that was not built with the Libpod backend and can only connect to a remote service; running a normal Podman binary would not have that restriction.

This is, unfortunately, not possible on OS X, nor is it likely to become possible. Podman runs on Linux only, which means that, in an OS X environment, we need a Linux VM to connect to, and we need to SSH into said VM and connect to a Podman service to run commands. We can't port Podman to native OS X as the kernel there lacks critical features we require (namespaces, an overlay filesystem, etc).

**Comment by sjackman** [comment]
Thank you for your amazingly quick response! I'll try it out Podman on Linux.

**Comment by sjackman** [comment]
For others that stumble onto this issue and need a native solution for macOS, Skopeo can push on OCI archive to a Docker Registry with `skopeo copy -a oci:… docker://ghcr.io/…`
See https://github.com/containers/skopeo

**Comment by vrothberg** [comment]
I echo what @sjackman mentions above: if you're looking for a tool to inspect, copy and manipulate container images, **Skopeo** is a good choice.

It can [run in a container](https://www.redhat.com/sysadmin/how-run-skopeo-container) and easily integrates into CI/CD pipelines and it supports [number of transport](https://www.redhat.com/sysadmin/7-transports-features) to copy images across all kinds of sources, formats and compressions.
