### ISSUE TITLE
Systemd can't start podman container after reboot due to deadlock on lockfile

### ISSUE THREAD

**Issue by sjpb** [containers/podman#9765]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
I have created a systemd unit file on CentOS 8 to run an `opendistro` container as the user `podman`. The unit file (see [here](https://gist.github.com/sjpb/912034910298bea779745adbd8eb75ee)) was generated using `podman generate systemd opendistro --restart-policy always --name` but then modified to use the `--sdnotify=conman` approach described [here](https://github.com/containers/podman/issues/5572#issuecomment-653574848) to avoid problems with the pidfile not being owned by root.

This initially works fine: systemd shows the `opendistro` service running ok and running `podman ps` as the podman user shows the container up. I did note that on running `systemctl stop opendistro` it claims to have failed due to the ExecStop (podman stop) command returning 143 but the container is stopped.

However if I reboot the host then service fails to startup, with systemd showing the ExecStart (`podman run`) command returning `126`. Trying `podman start opendistro` directly returns the same error code with the message:

```
Error: container 13fff305a82757d54303f4f627f9749c4e03edda29f91346b417ec90a5e191d7 and volume opendistro share lock ID 0: deadlock due to lock mismatch
```

To me this looks exactly like the error described in [this patch](https://github.com/mheon/libpod/commit/b8c9897dcd54d321614d1d0f7b0f973547126660).

Is there any way to work around this, e.g. by deleting lock files on unit stop or system shutdown?

**Steps to reproduce the issue:**

1. Create `podman` user and `opendistro` volume.

2. Copy the linked unit file to `/etc/systemd/system/opendistro.service`, replacing `{{ opendistro_podman_user }}` with `podman`

3. Run `sudo systemctl star opendistro` and check container starts

4. Reboot host

5. Check `systemctl status opendistro`

**Describe the results you received:**

```
● opendistro.service - Podman container-opendistro.service
   Loaded: loaded (/etc/systemd/system/opendistro.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2021-03-19 11:45:02 UTC; 2h 7min ago
     Docs: man:podman-generate-systemd(1)
  Process: 34205 ExecStopPost=/usr/bin/podman rm --ignore -f opendistro (code=exited, status=0/SUCCESS)
  Process: 34092 ExecStop=/usr/bin/podman stop --ignore opendistro -t 10 (code=exited, status=0/SUCCESS)
  Process: 33295 ExecStart=/usr/bin/podman run --sdnotify=conmon --cgroups=no-conmon -d --replace --name opendistro --restart=no --user elasticsearch --ulimit memlock=-1:-1 --ulimit nofile=65536:65536 --volume open>
 Main PID: 33295 (code=exited, status=143)
    Tasks: 1 (limit: 822732)
   Memory: 463.1M
   CGroup: /system.slice/opendistro.service
           └─1958 /usr/bin/podman

Mar 19 11:22:38 proto-control.novalocal systemd[1]: Starting Podman container-opendistro.service...
Mar 19 11:22:38 proto-control.novalocal systemd[1]: Started Podman container-opendistro.service.
Mar 19 11:22:38 proto-control.novalocal podman[33214]: 6f2b6b78b2f06bfcb20b49dd5311587e7a1a9e0422a74081aa2f653ad96e7c57
Mar 19 11:45:02 proto-control.novalocal systemd[1]: Stopping Podman container-opendistro.service...
Mar 19 11:45:02 proto-control.novalocal podman[34092]: 6f2b6b78b2f06bfcb20b49dd5311587e7a1a9e0422a74081aa2f653ad96e7c57
Mar 19 11:45:02 proto-control.novalocal systemd[1]: opendistro.service: Main process exited, code=exited, status=143/n/a
Mar 19 11:45:02 proto-control.novalocal podman[34205]: 6f2b6b78b2f06bfcb20b49dd5311587e7a1a9e0422a74081aa2f653ad96e7c57
Mar 19 11:45:02 proto-control.novalocal systemd[1]: opendistro.service: Failed with result 'exit-code'.
Mar 19 11:45:02 proto-control.novalocal systemd[1]: Stopped Podman container-opendistro.service.
```

**Describe the results you expected:**
See service running.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 2.2.1
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman.x86_64  2.2.1-7.module_el8.3.0+699+d61d9c41    @appstream
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No, Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical.

**Comment by sjpb** [comment]
Interestingly I just removed the `User=` and `Group=` parameters from the unit file and tried the "start, reboot, status" loop again and it comes up fine.

**Comment by mheon** [comment]
Please run `podman system renumber` to resolve the issue, and let us know if it happens again. Duplicate lock ID allocation should never happen, and is a sign of a serious issue.

**Comment by sjpb** [comment]
So it has happened again. I removed the `RuntimeDirectory` directive from the above unit file (which was left in from previous attempts getting a PID-based approach) and I thought that had fixed it as it came back up after two reboots. However after the 3rd reboot I got 

```
Error: container f6863ad60f8294b434dc2c3dc1e6b7602cd994627e4d8f9aa585c4e1d2639aae and volume opendistro share lock ID 2: deadlock due to lock mismatch
```

Did `podman system renumber` then `systemctl start opendistro` and it started ok.

The message on the patch I mentioned above suggests that allocation of existing locks is a known bug?

**Comment by mheon** [comment]
The usual cause for this that we find is Podman's temporary files directory not being on a tmpfs. The default should be under `/run/user/$UID` for the user running Podman, but that directory is not created by systemd when a service using said user runs, so Podman may have fallen back to a directory in `/tmp`. Is `/tmp` a tmpfs?

**Comment by sjpb** [comment]
`/tmp` isn't a tmpfs but `/run` is. Having said that only only `/run/user/1000` exists which matches the `centos` user not the `podman` user (uid/gid 1001).

**Comment by mheon** [comment]
Alright, that may well be the cause. Podman is probably using `/tmp/containers-user-$UID` (or a similar path). That directory is most likely not being cleaned up after reboot. If Podman does not detect a reboot, it will not properly refresh its state, which will lead to errors like this.

**Comment by mheon** [comment]
You should be able to determine the exact path with `podman info --log-level=debug` - this will print out a debug message including the path:
`DEBU[0000] Using tmp dir /run/user/1000/libpod/tmp`
