### ISSUE TITLE
Regression: Both REGISTRIES_CONFIG_PATH and CONTAINERS_REGISTRIES_CONF do not override /etc/containers/registries.conf

### ISSUE THREAD

**Issue by lsm5** [containers/podman#9766]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

I tried using a custom registries.conf and noticed podman still defaulted to `/etc/containers/registries.conf`

**Steps to reproduce the issue:**

1. $ echo "garbage" > \~/registries.conf; REGISTRIES_CONFIG_PATH=\~/registries.conf podman pull $ANY_IMAGE 

2. Try the same with CONTAINERS_REGISTRIES_CONF

**Describe the results you received:**

`/etc/containers/registries.conf` wasn't overriden.

**Describe the results you expected:**

`/etc/containers/registries.conf` should be overriden.

**Additional information you deem important (e.g. issue happens only occasionally):**

Checked with @vrothberg . He can consistently reproduce it as well.

**Output of `podman version`:**

```
3.1.0-rc1
```
as well as with upstream master 

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Desktop

**Comment by edsantiago** [comment]
Can confirm:
```console
# echo short-name-mode="disabled" >/tmp/registries.conf
# podman --registries-conf=/tmp/registries.conf pull sdf </dev/null
Error: error getting default registries to try: short-name resolution enforced but cannot prompt without a TTY
```

**Comment by vrothberg** [comment]
If others want to tackle the issue, please feel free. My queue is long at the moment.  What we'd need to do is to inspect _all_ places where we're using `c/image/v5/types.SystemContext` and make sure that we're setting the registries conf path.

**Comment by lsm5** [comment]
I don't mind taking this up, but only after April 9th I guess. Assigning to myself for now, if anyone else wants to take it before that, feel free.

**Comment by rhatdan** [comment]
```
$ CONTAINERS_REGISTRIES_CONF=/etc/passwd ./bin/podman pull alpine
Resolved "alpine" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/alpine:latest...
  Near line 0 (last key parsed ''): bare keys cannot contain ':'
Error: Error initializing source docker://alpine:latest: error loading registries configuration: error loading registries configuration "/etc/passwd": Near line 0 (last key parsed ''): bare keys cannot contain ':'

$ sudo CONTAINERS_REGISTRIES_CONF=/etc/passwd ./bin/podman pull alpine
Resolved "alpine" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/alpine:latest...
  Near line 0 (last key parsed ''): bare keys cannot contain ':'
Error: Error initializing source docker://alpine:latest: error loading registries configuration: error loading registries configuration "/etc/passwd": Near line 0 (last key parsed ''): bare keys cannot contain ':'
```

This seems to work for me?

**Comment by rhatdan** [comment]
Since I had no contradictory reports, I am closing.

**Comment by vrothberg** [comment]
Note that this will definitely be fixed with `libimage`.
