### ISSUE TITLE
podman will duplicate some of the parameters of a container executed with a systemd unit file by generating it again

### ISSUE THREAD

**Issue by unknowndev233** [containers/podman#9776]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

podman will duplicate some of the parameters of a container executed with a systemd unit file by generating it again

**Steps to reproduce the issue:**

1. Run the container
`# podman run --name t --rm busybox sleep 810`

2. generate systemd unit files
`# podman generate systemd --files --new --name t`

3. stop the container started in the first step
`# podman stop t`

4. Start the container with the unit file generated in step 2
`# cp *.service -t /etc/systemd/system && systemctl start container-t`

5. repeat step 2

**Describe the results you received:**

In the container: the --common-pidfile, --cidfile, --cgroups arguments repeat the arguments already in the previous systemd unit file on top of the podman generation
In pods: the --infra-conmon-pidfile parameter repeats the parameters of the last systemd unit file on top of those generated by podman

**Describe the results you expected:**

If in a container: only one podman-generated --conmon-pidfile, --cidfile, --cgroups parameter
If in a pod: only one podman-generated --infra-conmon-pidfile parameter

**Additional information you deem important (e.g. issue happens only occasionally):**
none
**Output of `podman version`:**

```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.16
Git Commit:   c640670e85c4aaaff92741691d6a854a90229d8d
Built:        Sun Feb 21 23:29:46 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.0.26-1
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 0e155c83aa739ef0a0540ec9f9d265f57f68038b'
  cpus: 3
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: arch
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.10.16-arch1-1
  linkmode: dynamic
  memFree: 1468776448
  memTotal: 6212612096
  ociRuntime:
    name: runc
    package: /usr/bin/runc is owned by runc 1.0.0rc93-1
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc93
      commit: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
      spec: 1.0.2-dev
      go: go1.15.7
      libseccomp: 2.5.1
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 6442442752
  swapTotal: 6442442752
  uptime: 21m 22.4s
registries: {}
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 5
    stopped: 0
  graphDriverName: overlay
  graphOptions: {}
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 31
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1613921386
  BuiltTime: Sun Feb 21 23:29:46 2021
  GitCommit: c640670e85c4aaaff92741691d6a854a90229d8d
  GoVersion: go1.16
  OsArch: linux/amd64
  Version: 3.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Repository      : community
Name            : podman
Version         : 3.0.1-2
Description     : Tool and library for running OCI-based containers in pods
Architecture    : x86_64
URL             : https://github.com/containers/libpod
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : cni-plugins  conmon  containers-common  device-mapper  iptables  libseccomp  runc  slirp4netns  libsystemd  fuse-overlayfs  libgpgme.so=11-64
Optional Deps   : podman-docker: for Docker-compatible CLI
                  btrfs-progs: support btrfs backend devices
                  catatonit: --init flag support
                  crun: support for unified cgroupsv2
Conflicts With  : None
Replaces        : None
Download Size   : 18.65 MiB
Installed Size  : 75.64 MiB
Packager        : Morten Linderud <foxboron@archlinux.org>
Build Date      : Sun Feb 21 23:29:46 2021
Validated By    : MD5 Sum  SHA-256 Sum  Signature
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
ArchLinux on VirtualBox

**Comment by Luap99** [comment]
Why do you want to regenerate the same file when you already have a running systemd unit?
Also the new generated unit file should still be working. Specifying the same cli argument several times is valid, only the last value will be used.

**Comment by unknowndev233** [comment]
> Why do you want to regenerate the same file when you already have a running systemd unit?
> Also the new generated unit file should still be working. Specifying the same cli argument several times is valid, only the last value will be used.

I only updated the scripts that podman 2.0.4 generated

**Comment by Luap99** [comment]
This makes sense. We already check for the --name flag so checking for other flags should be easy.

**Comment by unknowndev233** [comment]
> This makes sense. We already check for the --name flag so checking for other flags should be easy.

wdym

**Comment by Luap99** [comment]
I was wondering why you would want to do this. Updating the files after a podman upgrade sounds reasonable to me.
We have already a check in the generating code for the --name and --replace flag so adding the flags you mentioned should only need a small change to the code.
