### ISSUE TITLE
Failed to add conmon to systemd sandbox cgroup: mkdir /sys/fs/cgroup/cpuacct,cpu: read-only file system

### ISSUE THREAD

**Issue by mnsmithuk** [containers/podman#9799]
Hi,

I'm on a CentOS7 server running the latest podman available from the Kubic Project repo (v3.0.1) . I upgrade from the standard CentOS7 repo's v1.64 only because it did not have the podman network reload feature.

When I run an podman exec to any of my containers I get the following message prior to the command prompt of the container:

     WARN[0000] Failed to add conmon to systemd sandbox cgroup: mkdir /sys/fs/cgroup/cpuacct,cpu: read-only file system

As far as I can see the container is still behaving ok but I'd like to understand the warning and fix the issue.  I was not getting this message in v1.64.

Does anyone have any ideas what is going on, or is it a bug in v3.0.1 that you are aware of?

**Comment by rhatdan** [comment]
I think this is more about a bug in the new podman interacting with the old kernel/systemd.  Also in podman 3 we moved logrus level from Error to Warning. so this might have been warning for a while, but you never saw it.

**Comment by rhatdan** [comment]
@giuseppe Didn't you eliminate this message from appearing on rootless users of podman?

**Comment by mnsmithuk** [comment]
> I think this is more about a bug in the new podman interacting with the old kernel/systemd. Also in podman 3 we moved logrus level from Error to Warning. so this might have been warning for a while, but you never saw it.

Ok so nothing to worry about or config to change on my system ?

**Comment by rhatdan** [comment]
Yes I believe that is correct.

**Comment by mnsmithuk** [comment]
Ok thanks.  I would still like to remove it from the /var/log/messages file though.  Every minute podman does a health check the  WARN is added to the messages.  Everytime I access the container the  WARN is added to the messages.  Everytime a script access the container the  WARN is added to the messages.  It kinda makes my messages file clutttered with unecessary messages.

**Comment by rhatdan** [comment]
Change your command to 
podman --log-level=error ...
Should eliminate the message.

**Comment by mnsmithuk** [comment]
Perfect cheers.

Just need to work out how to get podman-compose to do the same now.
