### ISSUE TITLE
v3.1.0-rc2 fails to build for 32-bit because of coreos/go-systemd

### ISSUE THREAD

**Issue by lsm5** [containers/podman#9801]
so `vendor/github.com/coreos/go-systemd/v22/sdjournal/journal.go` uses C.ulong which isn't defined for 32-bit AFAICT, which makes v3.1.0-rc2 build fail on i686 and armv7hl.

I still built them for 32-bit using: 
```
%ifarch %{ix86} armv7hl
sed -i 's/id128StringMax := C.ulong/id128StringMax := C.uint/' vendor/github.com/coreos/go-systemd/v22/sdjournal/journal.go
%endif
```
in the rpm spec file. 

I'll look at making a PR to go-systemd unless someone is faster than me of course.

Anyway, main thing I'm curious about is how did that slip through our CI? I thought CI had a job to test build on all arches.

@mheon @vrothberg @cevich @baude @rhatdan PTAL.

**Comment by lsm5** [comment]
bodhi for v3.1.0-rc2:

f33: https://bodhi.fedoraproject.org/updates/FEDORA-2021-1da12eb9ce
f34: https://bodhi.fedoraproject.org/updates/FEDORA-2021-7c760a3379

**Comment by lsm5** [comment]
I don't have the original failure log anymore, but I can re-generate it if necessary.

**Comment by lsm5** [comment]
https://github.com/containers/podman/pull/9779/files#diff-e1fc58f0730e48d35a3643d46871bac00b70a13861d6babae1ce7e309735cdf5R1158 .. that's the problem line

**Comment by mheon** [comment]
Alright. Only option I can see is to fix this upstream, and revert that PR until a new release of go-systemd with the fix is available.

**Comment by lsm5** [comment]
> Alright. Only option I can see is to fix this upstream, and revert that PR until a new release of go-systemd with the fix is available.

@mheon our CI aside, if the specfile patch looks ok to you, maybe we can continue with it and not have to block on go-systemd update?

**Comment by cevich** [comment]
> I thought CI had a job to test build on all arches.

We do, it's called "Alt Arch. Cross", [for example on master](https://github.com/containers/podman/runs/2184144716).  Is it possible the problem crept in because we're doing a cross-compile (from Fedora) instead of a native build?

**Comment by Luap99** [comment]
The cross build test in CI is compiled without cgo support. AFAIK golang cannot cross compile with cgo. So there is no way to test c dependencies like go-systemd without a native build.

**Comment by cevich** [comment]
Ahh, okay, thanks for sharing.  Native building is a long way off, given the lack of meaningful support in the clouds.  There's a way we can hook on-prem. hardware into Cirrus-CI but this brings a whole new set of challenges.  Nested-virt is also possible, perhaps that might make sense for the 32-bit x86 case?

**Comment by lsm5** [comment]
https://github.com/coreos/go-systemd/pull/362 .. if anyone wants to review

**Comment by lsm5** [comment]
Closing this. The go-systemd PR has been merged. RE: the problem of ensuring 32-bit builds don't fail on koji, that should hopefully be addressed once we have packit integration in place which should be happening in the very near future.
