### ISSUE TITLE
Unable to identify which container the podman-compose logs in /var/log/messages came from

### ISSUE THREAD

**Issue by mnsmithuk** [containers/podman#9802]
Hi,

I have a server with multiple containers created with multiple podman-compose yml files.

Logs are replicated in /var/log/messages which is great, however there is no tags on the log message in /var/log/messages to identify which container sent the log.

How do I include a container name to the logs that go to /var/log/messages ?

I'm not sure if this is a podman issue or podman-compose issue.  I did report this in the podman-compose issues page https://github.com/containers/podman-compose/issues/282 a few weeks ago but received no reply so trying in here.

Apologies if this is the wrong place.

**Comment by rhatdan** [comment]
I am not sure how this is supposed to work, you are talking about stdout/stderr showing up in /var/log/messages? Podman has no control over this.

I believe this is the wrong place.
