### ISSUE TITLE
How can I log only unhealthy healthcheck messages?

### ISSUE THREAD

**Issue by mnsmithuk** [containers/podman#9804]
Hi,

Is there a way disregard healthy messages from the logs and only log unhealthy checks ?  ie Always log the unhealthy messages but ommit all podman healthcheck runs and healthy messages from unless its a change of state (recovery message from an unhealthy state) ?

**Comment by mheon** [comment]
@baude PTAL

**Comment by baude** [comment]
My first thought here is that I don't see a widespread use for this.  Aren't failed healthchecks also logged in journalctl.  Would like folks to say if this is a good idea first @rhatdan @Luap99 @mheon @ashley-cui @edsantiago

**Comment by mheon** [comment]
I think the first question is what "the logs" is referring to here - I really should have asked this when the issue first came in. Where are you seeing the failures being logged - the journal (maybe as events)?

**Comment by rhatdan** [comment]
Since we got no response to the question, I am closing.  Reopen if you can answer the question.
