### ISSUE TITLE
podman (docker-compose) incompatible with python v3.8.

### ISSUE THREAD

**Issue by quantum77** [containers/podman#9819]
/kind bug

Hate to be a bother, but...
Did a system upgrade today.  Then:

# zypper search docker-compose
Loading repository data...
Reading installed packages...

S  | Name                    | Summary                                                  | Type
---+-------------------------+----------------------------------------------------------+--------
   | python36-docker-compose | Tool to define and run complex applications using Docker | package
i+ | python38-docker-compose | Tool to define and run complex applications using Docker | package

# docker-compose up -d
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (docker-compose 1.28.5 (/usr/lib/python3.8/site-packages), Requirement.parse('docker-compose==1.26.2'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bill/bin/docker-compose", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'docker-compose==1.26.2' distribution was not found and is required by the application

**Comment by vrothberg** [comment]
Thanks for reaching out and apologies for the longer silence on this issue; we've been quite busy.

Please follow the requested issue template for reporting issues. Using zypper suggests you're on OpenSUSE but we really need more information about the host environment _and_ a clear reproducer.

**Comment by quantum77** [comment]
I no longer remember the context this was in as I've been through many podman Hells since, but I suspect I was trying to stand up mailu/postfix.

All I can say is here's what I see now:

`quantumn:~/mailu$ dir /run/docker.sock
lrwxrwxrwx  1 root   root     23 Mar 31 07:09 docker.sock -> /run/podman/podman.sock

quantumn:~/mailu$ dir /run/podman/
total 0
drwxrwxrwx  2 root root  60 Mar 31 07:09 .
drwxr-xr-x 28 root root 780 Mar 31 07:18 ..
srwxrwxrwx  1 root root   0 Mar 31 07:09 podman.sock

quantumn:~/mailu$ docker-compose up -d
Starting mailu_resolver_1 ... done
Starting mailu_front_1     ... done
Starting mailu_webdav_1   ... done
Starting mailu_redis_1    ... done
Starting mailu_admin_1     ... done
Starting mailu_antivirus_1 ... done
Starting mailu_fetchmail_1 ... done
Starting mailu_antispam_1  ... done
Starting mailu_imap_1      ... done
Starting mailu_smtp_1      ... done
quantumn:~/mailu$ podman ps
CONTAINER ID  IMAGE   COMMAND  CREATED  STATUS  PORTS   NAMES

quantumn:~/mailu$ podman pod ps
^C
quantumn:~/mailu$ podman log -l`
^C

Yes it just hangs on any podman command.  I've since moved on to trying to construct my wireguard and dns transactional server, but can't even get the simple docker.io/mvance/unbound:latest daemon working in a rootless pod.  --volume has billions of access denied for permissions.  It is able to create the unbound.pid with subuid, but everything else in the directory gives permissions errors.  Yes I'd had everything in that directory set to my user, and yes I'd tried setting everything to the subuid.  Nothing works.  MVance tried earnestly to help but he just doesn't know the ins and outs of pods, rootless, and podman.

Shelling inside the container the mounted volume is accessible and writeable, and when permissions set to the subuid, -properly- shows within the container to be owned by _unbound.  But the container's unbound daemon can not access?!  WTF?  In the podman run line I even tried  -e PUID=1003 -e PGID=1002 of my user, but no dice.

The only virtual machine I've been able to make run is my Deluge one, and that's with no pod and --net=host which is damned dangerous.  Clearly I'm a power user pushing this beyond a simple ngnix server to the functions it is ostensibly supposed to have, but I suspect that no one is actually testing real-world.  Can't be.

In desperation my last resort now is to create an empty pod and container and hand-build my own app inside each.  That will take quite a bit of study I suspect, and I have a state Supreme Court brief to finish, but if I can't make it work that way I've gotta ditch podman for a couple years until it's ready.

It's not worth my spending the time to document these anymore as my words don't make any sense to those who can do something about these issues.  Maybe English is not their native language, or maybe they're swamped in minutia, Idk.  I've tried and tried to explain and politely ask for guidance, but we just live in different universes apparently.

**Comment by vrothberg** [comment]
Did you do the `podman pod ps` etc. as rootless user? Something funky must be going on then, maybe unrelated, since `docker-compose` is talking to the rootful Podman.

**Comment by rhatdan** [comment]
Are you using docker-compose or podman-compose?

**Comment by quantum77** [comment]
Duh, docker-compose. There is no podman-compose.

Who do you think I am?

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by vrothberg** [comment]
Please remain polite if you want us to resolve the issue.

**Comment by quantum77** [comment]
Don't you think that was a misleading and unfair question V?

Anyway I've given up believing that this can/will be resolved within a reasonable time;  that is an amount of time where I will be able to use it.

**Comment by rhatdan** [comment]
Podman-compose is a thing, that works with docker compose files and translates them to a podman commands.

So duh, it was a valid question.

https://github.com/containers/podman-compose

**Comment by quantum77** [comment]
Please be advised that that project is shut down and obsolete.

**Comment by quantum77** [comment]
Go ahead and close my other bugs too, since you're not interested.
