### ISSUE TITLE
[Question] Documentation about supported compose versions / options?

### ISSUE THREAD

**Issue by pwFoo** [containers/podman#9830]
Hi,
read about compose support in podman which is a great feature! I use Docker Swarm at the moment. I know Swarm features (multi host networking?) is out of scope, but searching for some more documentation about supported compose versions / options.

Docker-compose works with a simple restart policy and swarm have some more details in deploy section. are volumes and network(s) supported same? Or which options still not supported? I would like to read some more detailed information about supported compose file features like restart policy, healthchecks, service / pod networking and how to share networks between different compose services?

**Comment by Luap99** [comment]
Short answer: Everything except swarm functionality should be working.

Long answer: Nobody knows what exactly works or what not. The only way to find out is to try if it works for you. With the v3.0.0 release we are confident enough to say that docker-compose works with podman (only as root, rootless support is being worked on see #9169). It is likely that there are still issues with the docker compat api and we rely on the community to find and report them so they can be fixed. The only exception is docker swarm support.

**Comment by pwFoo** [comment]
Thanks, I'll try.
