### ISSUE TITLE
Podman 2:3.1.0-0.2.rc2.fc34 fails to create overlays

### ISSUE THREAD

**Issue by waffshappen** [containers/podman#9834]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Fresh from the Fedora 34 updates-testing tree podman 2:3.1.0-0.2.rc2.fc34 fails to handle overlays correctly, atleast thats what the log is related to:

```
ERRO[0010] error unmounting /home/tobias/.local/share/containers/storage/overlay/bce02a1cef702ccbbd0cee9e8d1ba82c18063ef6792b26486b4bf90219769957/merged: invalid argument 
DEBU[0010] failed to mount container "831376d814f4129ea32b6af53608b7edd096ce4063d312fbffcd30eb2622a5d9": error creating overlay mount to /home/tobias/.local/share/containers/storage/overlay/bce02a1cef702ccbbd0cee9e8d1ba82c18063ef6792b26486b4bf90219769957/merged, mount_data=",lowerdir=/home/tobias/.local/share/containers/storage/overlay/l/XRR7QQFBMHO2P6EOVN2TD73LP3,upperdir=/home/tobias/.local/share/containers/storage/overlay/bce02a1cef702ccbbd0cee9e8d1ba82c18063ef6792b26486b4bf90219769957/diff,workdir=/home/tobias/.local/share/containers/storage/overlay/bce02a1cef702ccbbd0cee9e8d1ba82c18063ef6792b26486b4bf90219769957/work,userxattr,context=\"system_u:object_r:container_file_t:s0:c331,c884\"": permission denied 
```

Might be related to:
https://github.com/containers/podman/issues/9507

Downgrading to 
podman-2:3.0.1-1.fc34.x86_64
Immediately fixes the issue

**Steps to reproduce the issue:**

1. Run Fedora 34 beta with updates-testing enabled

2. `podman run -it --rm --security-opt label=disable -v local_dir:/destination fedora:35`

**Describe the results you received:**
podman fails to run due to overlay-related issues

**Describe the results you expected:**
podman to run

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes, the latest version is what breaks after all

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 34 beta on Kernel 5.11.9

**Comment by mheon** [comment]
I believe this is already fixed in c/storage upstream. We're trying to get a fresh version vendored to fix before we cut 3.1.0 final.

**Comment by jmontleon** [comment]
Is this the same issue as https://bugzilla.redhat.com/show_bug.cgi?id=1943321 ?

**Comment by vrothberg** [comment]
This has been mixed in the meantime.
