### ISSUE TITLE
[DOCS] Documentation translates double dash (--) to em dash (–)

### ISSUE THREAD

**Issue by EricIO** [containers/podman#9845]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The documentation seems to translate double dashes (--) to em dashes (–) making it highly confusing to tell apart from a single dash (-).

**Steps to reproduce the issue:**

1. Go to http://docs.podman.io/en/latest/markdown/podman-create.1.html#env-e-env

2. Look at the difference between –env and -e

3. Become confused

**Comment by eriksjolund** [comment]
That's a coincidence. I just opened an issue here:
https://github.com/containers/podman.io/issues/373
(2 days ago)
There is also an old issue that got closed during autumn:
https://github.com/containers/podman/issues/7474

**Comment by EricIO** [comment]
Erics do think alike. I guess my issue search was not good enough (I did only search for "dash" or "em dash" should of course have searched for long options).
