### ISSUE TITLE
It is not obvious how to map users' uid on the host to a specific container uid

### ISSUE THREAD

**Issue by sampie** [containers/podman#9847]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

I am trying to run public rstudio container with podman (without sudo) and work with external data (mapped with -v). The public rstudio container uses uid 1000 internally, which is different than my external user uid. 

I am looking a way to map host uid 1001 to container uid 1000, but could not find from the documentation how this is done.

**Steps to reproduce the issue:**

1.
Run following command with a user having uid 1001.

podman run --name rstudio -e ROOT=TRUE --user 0 --userns=keep-id -v /share:/share --rm -p 8787:8787 -e PASSWORD=foo rocker/rstudio

2.

Try to edit files (with the rstudio) on the /share, which are editable on the host for uid 1001.

3.

**Describe the results you received:**

I can not access the files on the /share (they are editable for user 1001 and rstudio container user is using uid 1000 which is mapped by podman to some other host uid than 1001)

(However, If my uid on the host is 1000 (the same than the "rstudio" user uid in the container), I can access the files on /share just fine.)

**Describe the results you expected:**

I am looking a way to do the mapping like --userns=keep-id, but map my host uid 1001 to container uid 1000 instead of mapping host uid 1001 to container uid 1001.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
$ podman version
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.14.7
Built:        Thu Jan  1 02:00:00 1970
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 12
  distribution:
    distribution: ubuntu
    version: "21.04"
  eventLogger: journald
  hostname: ariana
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1002
      size: 1
    - container_id: 1
      host_id: 200000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1001
      size: 1
    - container_id: 1
      host_id: 200000
      size: 65536
  kernel: 5.11.0-11-generic
  linkmode: dynamic
  memFree: 1473314816
  memTotal: 4115492864
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version 0.18.1-7931a-dirty
      commit: 7931a1eab0590eff4041c1f74e2844b297c31cea
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1001/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.4.3
  swapFree: 2039623680
  swapTotal: 2147479552
  uptime: 1h 25m 0.9s (Approximately 0.04 days)
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /home/akseli/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: vfs
  graphOptions: {}
  graphRoot: /tmp/user-1001
  graphStatus: {}
  imageStore:
    number: 1
  runRoot: /run/user/1001/containers
  volumePath: /tmp/user-1001/volumes
version:
  APIVersion: 3.0.0
  Built: 0
  BuiltTime: Thu Jan  1 02:00:00 1970
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd64
  Version: 3.0.1

```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
$ apt list podman
Listing... Done
podman/unknown,now 100:3.0.1-2 amd64 [installed]
podman/unknown 100:3.0.1-2 arm64
podman/unknown 100:3.0.1-2 armhf
podman/unknown 100:3.0.1-2 s390x

```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by mheon** [comment]
There was discussion late last year about a `--userns=image` option (similar to `--userns=host`, but mapping the user specified by the image to the user outside the container). This never happened, but this sounds like a good reason to finally implement it.

**Comment by mheon** [comment]
Though, it's not clear this would actually work in your case. The explicit `--user 0` means the container is running as root, which would prevent the flag from working as expected. You may need to manually specify userns mappings to do this - I don't have the material on-hand to tell you how to do this, but I will try and find it tomorrow.

**Comment by eriksjolund** [comment]
I did a test on a Ubuntu 20.04.2 computer.


1. Create the directory _~/share_ on the host
```
esjolund@laptop:~$ mkdir ~/share
esjolund@laptop:~$
```
2. Start `rstudio`

```
esjolund@laptop:~$ rstudioUID=1000; podman run  -e ROOT=TRUE --user 0  -v ./share:/home/rstudio/share --rm -p 8787:8787 --uidmap=0:1:$rstudioUID --uidmap=$(expr $rstudioUID + 1):$(expr $rstudioUID + 1):$(expr 65536 - $rstudioUID - 1) --uidmap=${rstudioUID}:0:1 -e PASSWORD=foo --rm -ti docker.io/rocker/rstudio
```
3. Start Google Chrome and go to http://localhost:8787 
4. Log in with username _rstudio_ and password _foo_
5. File -> New File -> RScript
6. Type some text
7. File -> Save As
8. Click the sub directory _share_
9. Choose `aa` as filename.
10. On the host terminal 

```
esjolund@laptop:~$ ls -l ~/share/
total 4
-rw-r--r-- 1 esjolund esjolund 3 mar 28 18:40 aa.R
esjolund@laptop:~$ 
```

It seems to work!

**Comment by sampie** [comment]
Thank you! This seems to work. I am trying to wrap my head around these mappings (`"–uidmap=container_uid:host_uid:amount"`). If I understood correctly, host_uids 1... means the range in /etc/subuid and host_uid 0 is the host uid that has executed the podman. So, this says that map all container uids to the /etc/subuid range, except map the container uid 1000 to the host uid who has executed podman.

**Comment by eriksjolund** [comment]
I tried to rewrite the `--uidmap` section in podman-run.1.md:
https://github.com/eriksjolund/podman/blob/rewrite_uidmap_documenation/docs/source/markdown/podman-run.1.md
(A work in progress...)

**Comment by sampie** [comment]
I am not absolutely sure, but I think that in most cases users would want podman to automatically map uids and gids to the range specified in /etc/subuid and subgid, except those that user wants to specially map outside of the subuid and subid range. For example, I was simply looking to say "map container uid 1000 to system uid 1001, and map all other uids automatically". I would also think that users would want to map gids (and gid ranges) in a similar manner. Naturally, user should be allowed to map to only own host uid and own host gids.

Btw. With current mapping scheme (only 0 is mapped outside of subuid and subgid ranges), if a user belongs to multiple host groups, say 1001, 1002 and 1003, how can the user map selected container gids to these host gids?

**Comment by mheon** [comment]
On your BTW: That's not really possible. We rely on the newuidmap/newgidmap executables to set up our user namespace mappings, and they only give us access to the current user (not their supplemental groups) and anything in subuid/subgid. With the keep-groups annotation we can tell the kernel not to drop these groups (so we can still access content owned by them) but they still aren't mapped into the user namespace, so we can't really interact with them properly.

**Comment by sampie** [comment]
Concerning the documentation, I found @eriksjolund's example very informative telling exactly how to map a certain container UID to user's UID (which can be for example 1001) while mapping the rest of the UIDs to the range specified in /etc/subuid. I think the example in a bit generalized form could make a good addition to the documentation.

Something like:
`user@mycomputer:~$ containerUID=1000` 
`user@mycomputer:~$ subuidSize=65536`
`user@mycomputer:~$ podman run \`
`   --user 1000 \`
`   --uidmap=0:1:$containerUID \`
`   --uidmap=$(expr $containerUID + 1):$(expr $containerUID + 1):$(expr $subuidSize - $containerUID - 1) \`
`   --uidmap=${containerUID}:0:1 \`
`   -ti ubuntu /bin/bash`

**Comment by eriksjolund** [comment]
In addition to adding an example, I think the `--uidmap` command-line option description could also be rewritten. Something like
https://github.com/eriksjolund/podman/commit/5490fb7da031aaa0ed2081c9ee3f2e0e2f9db58c#diff-709c13596091ef13fd9ca751f884bc013c271233f56d3d64a429a90c21b0326e
I could create a pull request (and name it "WIP ...") and also include the example. I guess it will be easier for others to provide feedback when it's in a form of a PR. (It might take a few days for me to create the PR)

**Comment by eriksjolund** [comment]
I opened up a PR https://github.com/containers/podman/pull/10072 for rewrite the description of **--uidmap**.
(Sorry, I didn't include the example above as I couldn't find the words of how to explain it well).

**Comment by rhatdan** [comment]
Since we have updated docs, I am closing.
