### ISSUE TITLE
[rootless] podman ps doesn't show anything, even though container is running

### ISSUE THREAD

**Issue by developedsoftware** [containers/podman#9849]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Podman ps has no output even though container is running. I am running rootless and starting the containers using a systemd service. I am also unable to run podman exec on any of the running containers because I get the following error 
**Error: can only create exec sessions on running containers: container state improper"**.

Running podman ps --all shows the containers. Running podman ps --all --sync does not resolve the problem. 

```
CONTAINER ID  IMAGE                           COMMAND               CREATED     STATUS   PORTS               NAMES
08d91c459257  localhost/gitlab-runner:latest  run --user=gitlab...  7 days ago  Created  0.0.0.0:80->80/tcp  gitlab-runner
15dbaf24744f  localhost/satis:latest          satis-server          7 days ago  Created  0.0.0.0:80->80/tcp  satis
3eb12fe80b76  localhost/proxy:latest          /usr/sbin/nginx       7 days ago  Created  0.0.0.0:80->80/tcp  proxy
81b11ec6843f  k8s.gcr.io/pause:3.2                                  7 days ago  Created  0.0.0.0:80->80/tcp  77502afe878b-infra
e1cabe9de0ec  localhost/gitlab:latest         /assets/wrapper       7 days ago  Created  0.0.0.0:80->80/tcp  gitlab
```

I assume the issue links somehow to the path **/tmp/run-1000/containers** being used as discussed in this ticket (was told to open another issue) #1680

/tmp being tidied after 7 days perhaps? 

Unit file is below

```
[Unit]
Description=Devops service
Wants=network.target
After=network-online.target

[Service]
User=repo.manager
Group=repo.manager
TimeoutStartSec=10m
Restart=on-failure
KillMode=none
Type=forking
Environment=PODMAN_SYSTEMD_UNIT=%n
ExecStart=/usr/local/bin/devops-start
ExecStop=/usr/local/bin/devops-stop

[Install]
WantedBy=multi-user.target
```

/usr/local/bin/devops-start contains a series of podman build and start commands

**Steps to reproduce the issue:**

1. Create a systemd service that runs some containers on boot as a rootless user

2. Log in as the rootless user - run podman ps. Initially everything will look fine. 

3. Run same command a week later and podman ps output will be empty. 

**Describe the results you received:**
podman ps is empty

**Describe the results you expected:**
```
CONTAINER ID  IMAGE                           COMMAND               CREATED     STATUS   PORTS               NAMES
08d91c459257  localhost/gitlab-runner:latest  run --user=gitlab...  7 days ago  Created  0.0.0.0:80->80/tcp  gitlab-runner
15dbaf24744f  localhost/satis:latest          satis-server          7 days ago  Created  0.0.0.0:80->80/tcp  satis
3eb12fe80b76  localhost/proxy:latest          /usr/sbin/nginx       7 days ago  Created  0.0.0.0:80->80/tcp  proxy
81b11ec6843f  k8s.gcr.io/pause:3.2                                  7 days ago  Created  0.0.0.0:80->80/tcp  77502afe878b-infra
e1cabe9de0ec  localhost/gitlab:latest         /assets/wrapper       7 days ago  Created  0.0.0.0:80->80/tcp  gitlab
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Only happens after a week or so. I can monitor daily to double check when exactly it occurs but the key thing is you have to leave the services running as rootless for X amount of time for the issue to occur. I assume its got something to do with the /tmp directory being cleaned up by RHEL8. 

**Output of `podman version`:**
```
Version:      2.0.5
API Version:  1
Go Version:   go1.14.7
Built:        Wed Sep 23 17:18:02 2020
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.15.1
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.20-2.module+el8.3.0+8221+97165c3f.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.20, commit: 77ce9fd1e61ea89bd6cdc621b07446dd9e80e5b6'
  cpus: 2
  distribution:
    distribution: '"rhel"'
    version: "8.3"
  eventLogger: file
  hostname: devops
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 4.18.0-240.10.1.el8_3.x86_64
  linkmode: dynamic
  memFree: 573374464
  memTotal: 16546279424
  ociRuntime:
    name: runc
    package: runc-1.0.0-68.rc92.module+el8.3.0+8221+97165c3f.x86_64
    path: /usr/bin/runc
    version: 'runc version spec: 1.0.2-dev'
  os: linux
  remoteSocket:
    path: /tmp/run-1000/podman/podman.sock
  rootless: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.4-2.module+el8.3.0+8221+97165c3f.x86_64
    version: |-
      slirp4netns version 1.1.4
      commit: b66ffa8e262507e37fca689822d23430f3357fe8
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
  swapFree: 8450981888
  swapTotal: 8451518464
  uptime: 179h 37m 40.82s (Approximately 7.46 days)
registries:
  search:
  - registry.access.redhat.com
  - registry.redhat.io
  - docker.io
store:
  configFile: /home/repo.manager/.config/containers/storage.conf
  containerStore:
    number: 5
    paused: 0
    running: 0
    stopped: 5
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.1.2-3.module+el8.3.0+8221+97165c3f.x86_64
      Version: |-
        fuse-overlayfs: version 1.1.0
        FUSE library version 3.2.1
        using FUSE kernel interface version 7.26
  graphRoot: /home/repo.manager/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 487
  runRoot: /tmp/run-1000/containers
  volumePath: /home/repo.manager/.local/share/containers/storage/volumes
version:
  APIVersion: 1
  Built: 1600877882
  BuiltTime: Wed Sep 23 17:18:02 2020
  GitCommit: ""
  GoVersion: go1.14.7
  OsArch: linux/amd6
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-2.0.5-5.module+el8.3.0+8221+97165c3f.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No - sticking with RHEL8 official binaries for now...

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.3 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.3:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.3"
Red Hat Enterprise Linux release 8.3 (Ootpa)
Red Hat Enterprise Linux release 8.3 (Ootpa)
```

**Comment by mheon** [comment]
If you're certain the container processes are actually running, then this is definitely `/tmp` being cleaned. The tmpfiles.d script at https://github.com/containers/podman/blob/master/contrib/tmpfile/podman.conf should prevent this from happening - we'll be shipping it in the package itself as of RHEL 8.4, but you can work around it for now by manually installing said config file to `/etc/tmpfiles.d/`

**Comment by developedsoftware** [comment]
Thanks, I will give that a try. 

However before I do I noticed that the file you reference has the following paths...

`

# /tmp/podman-run-* directory can contain content for Podman containers that have run
# for many days. This following line prevents systemd from removing this content.
x /tmp/podman-run-*
x /tmp/containers-user-*
D! /run/podman 0700 root root
D! /var/lib/cni/networks
`

But my runroot path is /tmp/run-1000/containers which doesn’t appear to match any of the rules in the file? Will that simply not work?

Would expect something like the below in the file? 

`
x /tmp/run-*/containers
`

**Comment by SahilChaudhary25** [comment]
How did you able to run as non root, i am getting this error 
**Error: cannot setup namespace using newuidmap: exit status 1**

**Comment by mheon** [comment]
@developedsoftware Yes, I would definitely add that. The paths we've used changed at some point in the past (the new ones are much more obvious as to who is using the directory in `/tmp`) and it looks like the old ones are not included in the file.

@SahilChaudhary25 Please open a new issue.

**Comment by developedsoftware** [comment]
For anybody having the same issue as this...I have added the following conf file to /etc/tmpfiles.d/podman.conf

`x /tmp/run-*`

Have restarted and will report back in 7 days if the fix was successful. 

@mheon can you confirm that looks OK? and that this will not be needed when RHEL 8.4 ships? Should I remove this file when RHEL 8.4 ships?

**Comment by mheon** [comment]
Yes, that looks fine. You may still need the file after 8.4, though, since we are not including the `/tmp/run-*` paths in it. We can get them in, but that will probably be later than 8.4, which is mostly finalized at this point.

**Comment by developedsoftware** [comment]
OK thanks for confirming. Will close once I have confirmed this is resolved. 

Is there a simple way of changing the runroot path? I could then just move this out of /tmp and into the users home directory and then the issue would not occur (and the above file would not be needed)...

**Comment by developedsoftware** [comment]
Can confirm this resolves the issue. Closing.
