### ISSUE TITLE
Inconsistent seccomp image label name

### ISSUE THREAD

**Issue by timholl** [containers/podman#9853]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Support for embedding seccomp filters via OCI Image Labels has been implemented in https://github.com/containers/podman/commit/f3f4c54f2abc341cee1e7b83e9538d91a3c627e3 .

However, there is some inconsistency in terms of the label name; while the label name is actually [`io.containers.seccomp.profile`](https://github.com/containers/podman/blob/54b82a175f16f27849e6791f65bf73eccae4701a/pkg/seccomp/seccomp.go#L11), the manual claims it was `io.podman.seccomp.profile` [here](https://github.com/containers/podman/blob/9439b699b8940e2caf84cc29026b0beb70a5a2bb/docs/source/markdown/podman-create.1.md#L824) and [here](https://github.com/containers/podman/blob/9439b699b8940e2caf84cc29026b0beb70a5a2bb/docs/source/markdown/podman-run.1.md#L876).

As this has already been confused in the original MR [here](https://github.com/containers/podman/commit/f3f4c54f2abc341cee1e7b83e9538d91a3c627e3#diff-c439bc8cc1b2797c8225af1faff01f0625207b80aa0a666e7382bc744afa2b11R36) vs [here](https://github.com/containers/podman/commit/f3f4c54f2abc341cee1e7b83e9538d91a3c627e3#diff-978f61b2d269cb102ccb6c661ad0d7c3b29edfd7d275f14750723105309197cbR668), I assume this was subject to change while implementation.

**Steps to reproduce the issue:**

- Compare the manual pages to the code base

**Describe the results you received:**
Inconsistent naming of the image label.

**Describe the results you expected:**
Consistent naming of the image label.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
-
```

**Output of `podman info --debug`:**

```
-
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
-
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by vrothberg** [comment]
Thanks for reaching out!  I'll fix that in the docs.  The code wins :)

**Comment by vrothberg** [comment]
https://github.com/containers/podman/pull/9854

**Comment by timholl** [comment]
:+1: Thanks for the quick response.
