### ISSUE TITLE
podman machine ssh argument missing validation

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman#9865]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. podman machine ssh

2.

3.

**Describe the results you received:**

```
[anders@localhost ~]$ podman machine ssh
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/containers/podman/v3/cmd/podman/machine.ssh(0x20eb100, 0x2141368, 0x0, 0x0, 0x0, 0x0)
	cmd/podman/machine/ssh.go:55 +0x320
github.com/spf13/cobra.(*Command).execute(0x20eb100, 0x4000184170, 0x0, 0x0, 0x20eb100, 0x4000184170)
	vendor/github.com/spf13/cobra/command.go:852 +0x320
github.com/spf13/cobra.(*Command).ExecuteC(0x20f6780, 0x400019c010, 0x11cd320, 0x2141368)
	vendor/github.com/spf13/cobra/command.go:960 +0x268
github.com/spf13/cobra.(*Command).Execute(...)
	vendor/github.com/spf13/cobra/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	vendor/github.com/spf13/cobra/command.go:890
main.Execute()
	cmd/podman/root.go:90 +0xf4
main.main()
	cmd/podman/main.go:38 +0xa4
```

**Describe the results you expected:**

Error message, or (preferrably) default vm used.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
podman version 3.1.0-dev
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by baude** [comment]
@afbjorklund I think this is fixed in main branch.  At least I cannot trigger that panic anymore.

**Comment by afbjorklund** [comment]
I get a slightly different panic, but it seems to still be there (on e6a5c0ffc1df78bf08aa25f4fe734b46a846a5d7)

```
$ ./bin/podman machine list
NAME        VM TYPE     CREATED      LAST UP
myvm        qemu        11 days ago  10 days ago
$ ./bin/podman machine ssh
panic: runtime error: index out of range [0] with length 0
```

It works fine when I remember the argument, but there was some muscle memory from the previous machine...
