### ISSUE TITLE
Remove images from a registry using Podman

### ISSUE THREAD

**Issue by SahilChaudhary25** [containers/podman#9866]
<!--
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
If we are pushing image with certain tag to container registry, then we should be able to delete images from remote by passing credentials using REST APIs

**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes/No

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by rhatdan** [comment]
We a better description then this?  You want podman to be able to do something like `skopeo --delete`

**Comment by mheon** [comment]
A more complete usecase is definitely required here.

**Comment by SahilChaudhary25** [comment]
@rhatdan Is there any Rest API Support such that once Image is pushed to remote container registry like GCR, ACR. I can delete images from these registries ?

**Comment by vrothberg** [comment]
[Skopeo](https://github.com/containers/skopeo) supports deleting images from a registry (`skopeo delete docker://$image`).  With Skopeo being able to run in a container and the officially supported image on `quay.io/containers/skopeo`, you could run it in a Podman container via the REST API; assuming the REST API is important to your use case.

**Comment by rhatdan** [comment]
But are you asking the right question?  Do you want to delete the image from the local store after successfully pushing it to a registry?  If that is really what you are after, then yes there are APIs for this.

**Comment by SahilChaudhary25** [comment]
Sorry for this short description, Actually we are trying to use pod man in kubernetes environments to programmatically build images and pushing it to remote container registry. This remote container registry can be anything like ACR, GCR, docker private registry etc. I am not concerned about images stored locally, it will go away as new pod will replace old one, i want to delete images anytime which is stored in remote container registry programmatically using rest API

**Comment by rhatdan** [comment]
Currently Skopeo can do this, with `skopeo delete` iff the server is configured to allow users to delete images.  Not all registries come configured that way.

**Comment by vrothberg** [comment]
@rhatdan, let's find consensus if we want to add that and how it would look like.

While I think the feature per se is out of scope for Podman, it does sound attractive for the REST use case.  Hence, I'd suggest to make this a REST-only feature and not expose it on the CLI; Skopeo should be used there.

@jwhonce @baude @mheon WDYT?

**Comment by mheon** [comment]
Feels awkward to not expose functionality we're adding, but I won't argue too loudly against it.

**Comment by rhatdan** [comment]
Why wouldn't I want the following?
`podman rmi --remote quay.io/rhatdan/badimage`
`podman image rm --remote quay.io/rhatdan/badimage`

I think they would be valuable.

**Comment by rhatdan** [comment]
Although --remote might cause confusion.  We would need to use a different flag.
podman image rm --registry quay.io/rhatdan/badimage?

**Comment by mheon** [comment]
I would mirror Git here - `podman push --delete`

**Comment by rhatdan** [comment]
I would be fine with that also.

**Comment by baude** [comment]
@lsm5 would you be interested in doing this?

**Comment by lsm5** [comment]
Just checked with the team and the consensus is that this feature should live inside skopeo along with a docs/manpage update in podman pointing users to skopeo. Correct me if I'm wrong. I can send a PR for it.

**Comment by rhatdan** [comment]
Yes lets just document that skopeo has this feature in the podman image rm man page.

**Comment by infiniteregrets** [comment]
Looks like the manpage hasnt been updated yet, should I do that? [This](https://github.com/containers/podman/blob/main/docs/source/markdown/podman-rmi.1.md) is the correct one right?

**Comment by rhatdan** [comment]
Yes please fix it.

**Comment by vrothberg** [comment]
Friendly ping.  Who wants to open a PR for it?

**Comment by rhatdan** [comment]
@umohnani8 PTAL
