### ISSUE TITLE
podman-remote build, with '*' in .dockerignore: overzealously ignores Dockerfile

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#9867]
Setup:
```console
$ mkdir aaa
$ echo "FROM scratch" >aaa/Dockerfile
$ echo '*' >aaa/.dockerignore
$ ./bin/podman system service --timeout=0
```
In window 2:
```console
$ ./bin/podman-remote build aaa
Error: stat /dev/shm/libpod_builder306103659/build/Dockerfile: no such file or directory
```
Regular (non-remote) podman works fine, presumably because it doesn't do the interim copy of the context dir to $TMPDIR:
```console
$ ./bin/podman build aaa
STEP 1: FROM scratch
STEP 2: COMMIT
--> 7c21f8178f5
7c21f8178f56c84713d534e8416eef383467c6bd6f42f0b00948fa0b0f1012a2
```

**Comment by rhatdan** [comment]
@vrothberg @nalind This I guess is an issue with the copier, where we should special case Containerfile and Dockerfile to not be ignored when * is specified.

@edsantiago did you try this out on Docker?

**Comment by edsantiago** [comment]
I didn't. I'm ~delighted~ I mean heartbroken to say I no longer have access to any hosts or VMs with docker.

**Comment by vrothberg** [comment]
> @vrothberg @nalind This I guess is an issue with the copier, where we should special case Containerfile and Dockerfile to not be ignored when * is specified.

I don't see the `copier` package being used in the build bindings: https://github.com/containers/podman/blob/master/pkg/bindings/images/build.go#L333.  As [mentioned in the other issue](https://github.com/containers/podman/issues/9871#issuecomment-810847427), I think the build bindings should use the copier package.

**Comment by rhatdan** [comment]
Volunteering?

**Comment by vrothberg** [comment]
I am usually volunteered :^)  Pipeline is long but we crossed the 200 issues threshold :)

**Comment by edsantiago** [comment]
Still present.

**Comment by edsantiago** [comment]
Still present: https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6152338764201984/html/bud-remote-fedora-34-root-host.log.html#t-00221

**Comment by rhatdan** [comment]
This works for me with the latest in the main branch.

**Comment by edsantiago** [comment]
It actually doesn't work. I suspect you shortcutted my reproducer above, running `podman system service` in the same directory as the Dockerfile and .dockerignore. Can you try my exact reproducer, no shortcuts? Reopening while we sort this out.
