### ISSUE TITLE
podman-remote build: -f gets confused

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#9871]
The `-f` flag is looking for ~love~ Dockerfiles in all the wrong places:
```console
$ bin/podman system service --timeout=0
```
In window 2:
```console
$ mkdir ccc
$ echo "FROM scratch" >ccc/Dockerfile2
$ ./bin/podman-remote build -t foo -f Dockerfile2 ccc
ERRO[0000] 1 error occurred:
        * lstat /path/to/my/current/directory/Dockerfile2: no such file or directory

Error: Post: "http:...long stuff probably related to the previous failure so I'm not going to bother filing an issue for it"
```
Non-remote `podman build` works fine.

**Comment by rhatdan** [comment]
@vrothberg @nalind is there an easy way to add a single file to the copier of the context directory?

**Comment by rhatdan** [comment]
@edsantiago is finding all of the little warts in podman-remote build. :^). 

I have been trying to kill them off as quickly as possible.

**Comment by vrothberg** [comment]
> @vrothberg @nalind is there an easy way to add a single file to the copier of the context directory?

Yes, that's possible (see https://github.com/containers/podman/blob/master/cmd/podman/containers/cp.go#L362).  Looking that the bindings for `build`, I think that [nTar(...)](https://github.com/containers/podman/blob/master/pkg/bindings/images/build.go#L332) should be replaced with using the copier package. It also supports `Excludes` among many other things.

**Comment by nalind** [comment]
The logic there is already checking for exclusions, and I think that slipping additional files into the tar stream (if we need to emulate something like the multiple-Dockerfiles feature) is going to be marginally easier with the current logic.

**Comment by edsantiago** [comment]
As an FYI: there are 52 tests in `bud.bats` that I'm currently skipping because they don't work with podman-remote due to this bug; all of them of the form `buildah bud -f path`. It seems like a common pattern.

**Comment by vrothberg** [comment]
I had a look at the code and it seems that the logic in `cmd/podman/images/build.go` needs some polishing.  IMHO the data passed to the bindings should be fully evaluated since we _must_ tar the files up.  Using @edsantiago's reproducer above, we `Dockerfile2` as the Dockerfile and  `/home/vrothberg/ccc` as the context directory.  I think the Dockerfile should have already been evaluated or at least be relative.

**Comment by vrothberg** [comment]
Ah, I have another idea.

**Comment by vrothberg** [comment]
Something for bug week.  The longer I read the code, the more questions I have.

**Comment by edsantiago** [comment]
Still present. This is the biggest problem facing buildah-bud tests under podman-remote: there are 53 buildah-bud tests that need to be skipped because of this bug.

**Comment by edsantiago** [comment]
Still present: https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6152338764201984/html/bud-remote-fedora-34-root-host.log.html#t-00205
