### ISSUE TITLE
podman-remote build: -v is a NOP

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#9874]
It does check for invalid path:
```console
$ ../bin/podman-remote build -v /foo:/bar .
Error: error checking path "/foo": stat /foo: no such file or directory
```
...but apart from that, it seems to be a NOP. Rather than fill out a detailed issue with a custom-crafted Containerfile and logs, I'm going to take a step back and ask: what does `-v` mean in the context of podman-remote, anyway? I'm tempted to think it should be intercepted with a fatal you-seem-to-be-unclear-on-the-concept error.

**Comment by rhatdan** [comment]
Well it should be hidden.

**Comment by Luap99** [comment]
Yes it should work but I only tested with podman create/run and never podman build.

**Comment by rhatdan** [comment]
This is now documented.
