### ISSUE TITLE
podman network connect should support setting a static ip and mac

### ISSUE THREAD

**Issue by Luap99** [containers/podman#9883]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

It is currently not possible to set a static ip or mac for a second network. You can only use `--ip` and `--mac` with podman run/create. podman network connect should also allow `--ip` and `--mac` to set the IP and MAC address for the new network.
This should be possible with CNI. The more challenging problem is how we store the ip and mac address currently. It is stored as single entry per container with such a change we would need to store it per container network.

**Comment by Luap99** [comment]
@mheon What do you think about the db structure, could you implement this? I am pretty sure I can make the cni part happen.

**Comment by mheon** [comment]
I think it's doable, but complicated. We'll need to deprecate the existing Static IP and Static MAC configuration in the DB (respect it if already configured and don't allow network connect to set static IPs on this containers, but stop generating it from now on) and move to a map of network name to static IP / static MAC and any other configuration information necessary. The DB functions for storing networks a container is joined to currently return a []string of just network names, but we should be able to patch them to return a map including this additional configuration information without much trouble.

**Comment by rhatdan** [comment]
@Luap99 Are you planning on looking at this?

**Comment by Luap99** [comment]
I think @mheon is currently working on the db structure.

**Comment by Luap99** [comment]
@mheon Have you started working on this?

**Comment by mheon** [comment]
Yep, but I put it down ~two weeks ago and have not found time to pick it back up. I'll try and pick it back up next week.

**Comment by rhatdan** [comment]
@Luap99 @mheon Any update on this one?

**Comment by Luap99** [comment]
This is planed for 4.0
