### ISSUE TITLE
podman-remote build: --stdin is ignored

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#9890]
```console
$ cat Containerfile
FROM alpine
RUN read -t 1 x
$ echo hi | ../bin/podman-remote build --stdin .
STEP 1: FROM alpine
STEP 2: RUN read -t 1 x
Error: error building at STEP "RUN read -t 1 x": error while running runtime: exit status 1
```
Works fine with non-remote.

This is probably tricky one due to remote input streams, but I'm leaning pretty heavily toward thinking we should make it work.

**Comment by edsantiago** [comment]
Still present: https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6152338764201984/html/bud-remote-fedora-34-root-host.log.html#t--00199

**Comment by edsantiago** [comment]
I no longer have access to any systems with docker. However, I think the history behing `--stdin` was [buildah issue 2863](https://github.com/containers/buildah/issues/2863), in which a Containerfile needed to read user input. This works with `podman build`, but I can see how it could be tricky or impossible to fix in podman-remote. 

My only reason for wanting it fixed is running the buildah-bud tests. I have no real-world use case for it.

**Comment by rhatdan** [comment]
Is there a way we can disable this test by default, and then we can document that --stdin is not enabled for remote.

**Comment by edsantiago** [comment]
Yes, disabling the test with an explanatory note is easy.

**Comment by rhatdan** [comment]
Since this is not supported by Docker, we should not support it in Podman remote build.
```
# docker build /tmp/test/
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM alpine
 ---> 28f6e2705743
Step 2/2 : RUN read -t 1 x
 ---> Running in 3c3625db2cf8
The command '/bin/sh -c read -t 1 x' returned a non-zero code: 1
```
