### ISSUE TITLE
Unprivileged net.ipv4.ping_group_range unavailable in older kernels

### ISSUE THREAD

**Issue by computator** [containers/podman#9897]
/kind bug

**Description**

containers/buildah#1618 seems to not have gotten ported to Podman

**Steps to reproduce the issue:**

As root:
```
podman run --rm -ti --uidmap 0:100000:1000 alpine cat /proc/self/uid_map
```
**Describe the results you received:**
(CentOS 7.5)
```
# podman run --rm -ti --uidmap 0:100000:1000 alpine cat /proc/self/uid_map
Error: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: write sysctl key net.ipv4.ping_group_range: open /proc/sys/net/ipv4/ping_group_range: no such file or directory: OCI not found
#
```

**Describe the results you expected:**
(Ubuntu 18.04)
```
# podman run --rm -ti --uidmap 0:100000:1000 alpine cat /proc/self/uid_map
         0     100000       1000
#
```

**Output of `podman version`:**

```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.5
Built:        Mon Mar  1 14:30:40 2021
OS/Arch:      linux/amd64
```
Kernel: `3.10.0-862.2.3.el7.x86_64`

**Comment by rhatdan** [comment]
I believe this is an issue with container.conf? crun should/would not do this on it's own.

There is a setting in /usr/share/containers/containers.conf asking to set this.

**Comment by rhatdan** [comment]
Bottom line, if you are using an older kernel, then you need to remove the sysctl settings from containers.conf.  If this is distro related then who ever is packagin the containers.conf that does not work on the distro, should fix it.  Not an upstream issue.

**Comment by vrothberg** [comment]
@rhatdan, most likely that's our packages from Kubic.  Podman v3.0.X is the last version for Ubuntu 18.04.  @lsm5 do you know if we could ship a dedicated `containers.con` for 18.04?

**Comment by computator** [comment]
@vrothberg 18.04 works fine. I used it as the example where things worked correctly. It was CentOS 7.5 that I was having issues with.

@rhatdan To make sure I understand correctly, this is something that's hardcoded for buildah but set in `containers.conf` for podman? If so, should buildah maybe be the one that needs to be updated to match?
