### ISSUE TITLE
Podman is not working in rootless k8s container when privilege flag set to false 

### ISSUE THREAD

**Issue by SahilChaudhary25** [containers/podman#9908]
/kind bug

**Description**

**Steps to reproduce the issue:**

1. Create kubernetes pod with podman image when privilege is not set true

2. Run Podman CLI commnads like podman info

**Describe the results you received:**

/app # podman info
ERRO[0006] 'overlay' is not supported over extfs at "/var/lib/containers/storage/overlay"
Error: kernel does not support overlay fs: 'overlay' is not supported over extfs at "/var/lib/containers/storage/overlay": backing file system is unsupported for this graph driver

**Describe the results you expected:**
Pod man should worked in k8s container with privilege set to false

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
   podman version 3.0.1
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: cgroupfs
  cgroupVersion: v1
  conmon:
    package: Unknown
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: 3f3bf835bb5bd523d4b4850825dbcbc8a52c0407'
  cpus: 8
  distribution:
    distribution: alpine
    version: 3.12.5
  eventLogger: file
  hostname: ai-deployer-deployment-57676f75cf-xb9cs
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.4.0-1036-azure
  linkmode: dynamic
  memFree: 1194172416
  memTotal: 33677254656
  ociRuntime:
    name: crun
    package: Unknown
    path: /usr/bin/crun
    version: |-
      crun version 0.18
      commit: 808420efe3dc2b44d6db9f1a3fac8361dde42a95
      spec: 1.0.0
      +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 0
  swapTotal: 0
  uptime: 1063h 0m 6.64s (Approximately 44.29 days)
registries:
  search:
  - aifdevregistry.azurecr.io
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 0
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1613767760
  BuiltTime: Fri Feb 19 20:49:20 2021
  GitCommit: d048e65256dabad226b435c3f5811f6d34e335d4
  GoVersion: go1.16
  OsArch: linux/amd64
  Version: 3.0.1
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**
Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AKS machine with alpine base image

uname -a
Linux ai-deployer-deployment-57676f75cf-xb9cs 5.4.0-1036-azure #38~18.04.1-Ubuntu SMP Wed Jan 6 18:26:30 UTC 2021 x86_64 Linux

/app # capsh --print
Current: = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap+eip
Bounding set =cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap
Ambient set =
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
 secure-no-ambient-raise: no (unlocked)
uid=0(root)
gid=0(root)
groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)

seccomp.json file
[ss.txt](https://github.com/containers/podman/files/6238380/ss.txt)

/app #  ls /dev/fuse -l
ls: /dev/fuse: No such file or directory

**Comment by mheon** [comment]
@rhatdan Podman-in-container issue

**Comment by SahilChaudhary25** [comment]
@rhatdan Any update on this, this security concern is blocking us to use podman for our production use case

**Comment by flouthoc** [comment]
@SahilChaudhary25 It seems like your setup is using native overlay on `privileged: false`. However podman within unprivileged scenario relies on `fuse-overlayfs` instead of `native overlay`.

You need to configure device plugin `/dev/fuse` and use that within your pod spec https://github.com/kuberenetes-learning-group/fuse-device-plugin/blob/main/fuse-device-plugin-k8s-1.16.yml.

Read more about using running k8s pods with `fuse-overlayfs` setup here : https://www.redhat.com/sysadmin/podman-inside-kubernetes

Closing this issue since `privileged` and `native overlay` together is not supported. cc @giuseppe Could you please confirm if we support `native overlay` under unprivileged scenarios since i am not 100% sure .
