### ISSUE TITLE
`podman run` bails out if you ^C a `git clone` running as non-root

### ISSUE THREAD

**Issue by Hi-Angel** [containers/podman#9913]
/kind bug

**Description**

I'm setting up a container for CI, and one thing CI needs to check is that build as non-root user isn't broken. What I stumbled upon is that if I log into a container as a non-root and run `git clone`, and then I <kbd>Ctrl</kbd>+<kbd>c</kbd> that command, podman quits.

This does not happen if interrupting e.g. `sleep n` command or an infinite bash cycle, so might be something to do with network… I assume there are other ways to trigger the problem that I didn't stumble upon yet.

**Steps to reproduce the issue *(in terms of terminal commands)*:**

```haskell
 λ cat Dockerfile
FROM docker.io/library/ubuntu:bionic
RUN useradd user -m
RUN apt-get update
RUN apt-get install -y git
 λ podman build . -t test
STEP 1: FROM docker.io/library/ubuntu:bionic
STEP 2: RUN useradd user -m
--> Using cache 84ccd08ce7a1c8becf387bd755a7ff38f1d2c49b0b78802d901e06f97d91c4bf
--> 84ccd08ce7a
STEP 3: RUN apt-get update
--> Using cache 8352484b6995152c2c77a20e16567bfc8953a2ceb57319f72915fd2b39b4b5f3
--> 8352484b699
STEP 4: RUN apt-get install -y git
--> Using cache 3cbb45349cbd4e5f3ad2b80af9174ffae18e5634a720d243fc3edd9189fbc19d
STEP 5: COMMIT test
--> 3cbb45349cb
3cbb45349cbd4e5f3ad2b80af9174ffae18e5634a720d243fc3edd9189fbc19d
 λ podman run -it test su - user
$ git clone https://github.com/torvalds/linux
Cloning into 'linux'...
^C
$ %
 λ
```

**Describe the results you received:**

Interrupting the last command resulted in podman bailing out of container.

**Describe the results you expected:**

podman would not exit.

**Additional information you deem important:**

When podman exits, the exit code is `130`.

Running podman under gdb results in gdb reporting `Inferior 1 (process 87385) exited with code 0202]`

**Output of `podman version`:**

```
 λ podman --version
podman version 3.1.0
```

**Output of `podman info --debug`:**

<details>

```
 λ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.20.0
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: /usr/bin/conmon is owned by conmon 1:2.0.27-1
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: 65fad4bfcb250df0435ea668017e643e7f462155'
  cpus: 4
  distribution:
    distribution: arch
    version: unknown
  eventLogger: journald
  hostname: constantine-N61Ja
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 165536
      size: 65536
  kernel: 5.11.11-arch1-1
  linkmode: dynamic
  memFree: 1355177984
  memTotal: 8235139072
  ociRuntime:
    name: crun
    package: /usr/bin/crun is owned by crun 0.18-1
    path: /usr/bin/crun
    version: |-
      crun version 0.18
      commit: 808420efe3dc2b44d6db9f1a3fac8361dde42a95
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: /usr/bin/slirp4netns is owned by slirp4netns 1.1.9-1
    version: |-
      slirp4netns version 1.1.9
      commit: 4e37ea557562e0d7a64dc636eff156f64927335e
      libslirp: 4.4.0
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 7961047040
  swapTotal: 8053059584
  uptime: 18h 25m 32.9s (Approximately 0.75 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  configFile: /home/constantine/.config/containers/storage.conf
  containerStore:
    number: 56
    paused: 0
    running: 1
    stopped: 55
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: /usr/bin/fuse-overlayfs is owned by fuse-overlayfs 1.5.0-1
      Version: |-
        fusermount3 version: 3.10.2
        fuse-overlayfs: version 1.5
        FUSE library version 3.10.2
        using FUSE kernel interface version 7.31
  graphRoot: /home/constantine/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 55
  runRoot: /run/user/1000/containers
  volumePath: /home/constantine/.local/share/containers/storage/volumes
version:
  APIVersion: 3.1.0
  Built: 1617202008
  BuiltTime: Wed Mar 31 17:46:48 2021
  GitCommit: 9f09fb62cba8f44c18eda84db3e72aab3ae76046-dirty
  GoVersion: go1.16.2
  OsArch: linux/amd64
  Version: 3.1.0
```

</details>

**Package info:**

<details>

```
 λ pacman -Qi podman
Name            : podman
Version         : 3.1.0-1
Description     : Tool and library for running OCI-based containers in pods
Architecture    : x86_64
URL             : https://github.com/containers/libpod
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : cni-plugins  conmon  containers-common  device-mapper  iptables  libseccomp  runc  slirp4netns  libsystemd  fuse-overlayfs  libgpgme.so=11-64
Optional Deps   : podman-docker: for Docker-compatible CLI
                  btrfs-progs: support btrfs backend devices [installed]
                  catatonit: --init flag support
                  crun: support for unified cgroupsv2 [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 72.86 MiB
Packager        : Morten Linderud <foxboron@archlinux.org>
Build Date      : Ср 31 мар 2021 17:46:48
Install Date    : Чт 01 апр 2021 15:06:14
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

<details>

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Comment by matejvasek** [comment]
@Hi-Angel I don't think this is a `podman` issue. The `docker`'s behaviour is the same as the `podman` ones. I think that problem here is that `su` is not a good entrypoint (it won't forward SIGINIT as `/bin/sh` entrypoint does).

So I think you should switch user in `Dockerfile`
```Dockerfile
FROM docker.io/library/ubuntu:bionic
RUN useradd user -m
RUN apt-get update
RUN apt-get install -y git
USER user
```
and then use standard entrypoint `/bin/sh`.

**Comment by Hi-Angel** [comment]
> So I think you should switch user in `Dockerfile`
> 
> ```dockerfile
> FROM docker.io/library/ubuntu:bionic
> RUN useradd user -m
> RUN apt-get update
> RUN apt-get install -y git
> USER user
> ```
> 
> and then use standard entrypoint `/bin/sh`.

Thank you for the workaround, will do!

> @Hi-Angel I don't think this is a `podman` issue. The `docker`'s behaviour is the same as the `podman` ones. I think that problem here is that `su` is not a good entrypoint (it won't forward SIGINIT as `/bin/sh` entrypoint does).

On the other hand, it's not what `su - user` does out of container. Since the purpose of container is to virtualize a system, and a real system would not bail out of `su` upon pressing ^C while running certain command, I think it's fair to say that both `docker` and `podman` has a bug.

**Comment by matejvasek** [comment]
I do not understand why `sleep n` exits as expected.
Only difference I see now is that `git` runs multiple processes:
```docker top naughty_pasteur
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
root                466635              466613              0                   18:22               pts/0               00:00:00            su - user
t1000               466673              466635              0                   18:22               pts/0               00:00:00            -su
t1000               466912              466673              2                   18:22               pts/0               00:00:00            git clone https://github.com/containers/podman
t1000               466913              466912              17                  18:22               pts/0               00:00:00            /usr/lib/git-core/git-remote-https origin https://github.com/containers/podman
t1000               466925              466913              7                   18:22               pts/0               00:00:00            /usr/lib/git-core/git fetch-pack --stateless-rpc --stdin --lock-pack --thin --check-self-contained-and-connected --cloning https://github.com/containers/podman/
t1000               466927              466925              0                   18:22               pts/0               00:00:00            /usr/lib/git-core/git index-pack --stdin -v --fix-thin --keep=fetch-pack 14 on 0a2d9ccb046d --check-self-contained-and-connected --pack_header=2,114524
```

**Comment by Hi-Angel** [comment]
> > @Hi-Angel I don't think this is a `podman` issue. The `docker`'s behaviour is the same as the `podman` ones. I think that problem here is that `su` is not a good entrypoint (it won't forward SIGINIT as `/bin/sh` entrypoint does).
> 
> On the other hand, it's not what `su - user` does out of container. Since the purpose of container is to virtualize a system, and a real system would not bail out of `su` upon pressing ^C while running certain command, I think it's fair to say that both `docker` and `podman` has a bug.

Forgot to say: even if it would be considered an intentional behavior, another point here is that podman prints no messages about why it exited.

**Comment by matejvasek** [comment]
>Forgot to say: even if it would be considered an intentional behavior, another point here is that podman prints no messages about why it exited.

At least it return errcode 130 -- SIGINT.

**Comment by matejvasek** [comment]
@Hi-Angel I tried this with Fedora CentOS and Alpine instead of Ubuntu and the bug is not present. Couldn't be something wrong with `su` on Ubuntu?

**Comment by Hi-Angel** [comment]
Hmm, this is interesting, yeah, it might be! Thank you very much, I'll try taking a closer look at it tomorrow then.

**Comment by Hi-Angel** [comment]
So… I did a lot of experimentation, and I do think you are right in that it is purely a `su` bug on the older Ubuntu, and is not specific to virtualization.

Specifically, it seems the bug is that under some circumstances `su` probably tries to do something with PID `1`, but then it does not expect that `su` *is* the process with PID 1. The workaround is simply making sure `su - user` does not have PID of `1`. For example, replacing the command with `sh -c "su - user"` fixes the problem.

Although I'm curious, but I didn't manage to figure out what exactly it tries to do with PID 1, because whatever I do with debugging tools inside the container results in either of α) PID of `su` getting changed to `2` *(e.g. attaching `strace`)*, or β) in container exiting without leaving me any chance to see stacktrace or anything. Oh, well…
