### ISSUE TITLE
Failing to build 3.1.0

### ISSUE THREAD

**Issue by alitvak69** [containers/podman#9922]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Trying to build podman 3.1.0 rpm from srpm on centos fails at

EOF
cd /root/rpmbuild/BUILD/podman-3.1.0/_build/src/github.com/containers/podman/vendor/k8s.io/api/apps/v1
/usr/lib/golang/pkg/tool/linux_amd64/compile -o $WORK/b717/_pkg_.a -trimpath "$WORK/b717=>" -shared -p github.com/containers/podman/vendor/k8s.io/api/apps/v1 -complete -installsuffix shared -buildid vkknGU7f2u6vvptX0xWv/vkknGU7f2u6vvptX0xWv -goversion go1.15.5 -D "" -importcfg $WORK/b717/importcfg -pack ./doc.go ./generated.pb.go ./register.go ./types.go ./types_swagger_doc_generated.go ./zz_generated.deepcopy.go
/usr/lib/golang/pkg/tool/linux_amd64/buildid -w $WORK/b717/_pkg_.a # internal
cp $WORK/b717/_pkg_.a /root/.cache/go-build/dd/dd07e76395c65aa8a7c059a2e35e9bed0934d52bd100f35f789fc57a8ad3156b-d # internal
error: Bad exit status from /var/tmp/rpm-tmp.jfHGsl (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.jfHGsl (%build)

Any hints is appreciated.

**Comment by baude** [comment]
could you cite the srpm?

**Comment by zhangguanzhang** [comment]
which OS did you use ?

**Comment by alitvak69** [comment]
I used centos 7 and tried to appropriate following SRPM with source changes to 3.1, i.e. getting appropriate source file(s) and changing spec file.
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/src/podman-3.0.1-2.el7.3.1.src.rpm

**Comment by zhangguanzhang** [comment]
I used CentOS8, there is my steps:
```
dnf install -y gcc make wget vim git libseccomp-devel systemd-libs systemd-devel jq patch tar

export CGO_ENABLED=1

make BUILDTAGS="containers_image_openpgp systemd exclude_graphdriver_btrfs btrfs_noversion exclude_graphdriver_devicemapper selinux seccomp " podman
```

**Comment by lsm5** [comment]
@alitvak69 the error would actually be somewhere way up in the build log. mind posting a link to the entire changelog please?

**Comment by lsm5** [comment]
@alitvak69 also, if it makes life a little easier for you, we can hold the centos7 specific changes in the spec file to make builds easier for you going forward.

**Comment by lsm5** [comment]
@alitvak69 I see this on CentOS 8 and Stream build logs: 

```
[  233s] /usr/lib/golang/pkg/tool/linux_amd64/compile -o $WORK/b577/_pkg_.a -trimpath "$WORK/b577=>" -shared -p github.com/containers/podman/pkg/trust -complete -installsuffix shared -buildid eTB0zXjrTG3w6KdRd1Tu/eTB0zXjrTG3w6KdRd1Tu -goversion go1.16.1 -D "" -importcfg $WORK/b577/importcfg -pack ./_build/src/github.com/containers/podman/pkg/trust/config.go ./_build/src/github.com/containers/podman/pkg/trust/trust.go
[  233s] # github.com/containers/podman/vendor/github.com/coreos/go-systemd/v22/sdjournal
[  233s] _build/src/github.com/containers/podman/vendor/github.com/coreos/go-systemd/v22/sdjournal/journal.go:1160:2: could not determine kind of name for C.my_sd_id128_to_string
[  233s] cgo: 
[  233s] gcc errors for preamble:
[  233s] _build/src/github.com/containers/podman/vendor/github.com/coreos/go-systemd/v22/sdjournal/journal.go:313:60: error: '_SD_ARRAY_STATIC' undeclared here (not in a function)
[  233s]  // my_sd_id128_to_string(void *f, sd_id128_t boot_id, char s[_SD_ARRAY_STATIC SD_ID128_STRING_MAX])
[  233s]                                                             ^~~~~~~~~~~~~~~~
[  233s] _build/src/github.com/containers/podman/vendor/github.com/coreos/go-systemd/v22/sdjournal/journal.go:313:76: error: expected ']' before numeric constant
[  233s]  // my_sd_id128_to_string(void *f, sd_id128_t boot_id, char s[_SD_ARRAY_STATIC SD_ID128_STRING_MAX])
[  233s]                                                                             ^
[  233s]                                                                             ]
[  233s] 
[  233s] github.com/containers/podman/vendor/github.com/containernetworking/plugins/pkg/ns
```

I wonder if it's an old golang to blame.

**Comment by lsm5** [comment]
@alitvak69 can this be closed?

**Comment by rhatdan** [comment]
Reopen if @lsm5 is mistaken.

**Comment by alitvak69** [comment]
@lsm5 Sorry for delay. Please keep those Centos 7 changes in spec.  After that issue can stay closed.
