### ISSUE TITLE
How to upgrade from podman version 2.2.1 to v.3.0

### ISSUE THREAD

**Issue by diegoturcios** [containers/podman#9923]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

How I can upgrade from podman 2.2.1 to 3.0 in "Red Hat Enterprise Linux 8" 
Not sure how to upgrade, as there's no information about how to do this [Version 3.0](https://github.com/containers/podman/releases/tag/v3.0.0) .

```
sudo dnf module list | grep container-tools
Failed to set locale, defaulting to C.UTF-8
container-tools      rhel8 [d][e] common [d] [i]                           Most recent (rolling) versions of podman, buildah, skopeo, runc, conmon, runc, conmon, CRIU, Udica, etc as well as dependencies such as container-selinux built and tested together, and updated as frequently as every 12 weeks.
container-tools      1.0          common [d]                               Stable versions of podman 1.0, buildah 1.5, skopeo 0.1, runc, conmon, CRIU, Udica, etc as well as dependencies such as container-selinux built and tested together, and supported for 24 months.                                 
container-tools      2.0          common [d]                               Stable versions of podman 1.6, buildah 1.11, skopeo 0.1, runc, conmon, etc as well as dependencies such as container-selinux built and tested together, and supported as documented on the Application Stream lifecycle page.
```

**Steps to reproduce the issue:**

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
(paste your output here)
```

**Output of `podman info --debug`:**

```
(paste your output here)
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
(paste your output here)
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No, not able to  update to latest version.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by baude** [comment]
Podman-v3.x has not been released in RHEL yet officially.  Please use https://bugzilla.redhat.com/ to report issues with RHEL.
