### ISSUE TITLE
Improvement on basic_setup() of helpers of test/system (Clean up phase)

### ISSUE THREAD

**Issue by aliaslanturk** [containers/podman#9930]
/kind feature

This issue proposes an improvement on basic_setup() function of helpers in its clean up phase.

### Current flow of the function
basic_setup() function includes following lines to clean up unnecessary images before running tests:
```
# Clean up all images except those desired
    found_needed_image=
    run_podman images --all --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    for line in "${lines[@]}"; do
        set $line
        if [ "$1" == "$PODMAN_TEST_IMAGE_FQN" ]; then
            found_needed_image=1
        else 
            echo "# setup(): removing stray images $1 $2" >&3
            run_podman rmi --force "$1" >/dev/null 2>&1 || true
            run_podman rmi --force "$2" >/dev/null 2>&1 || true
        fi  
    done
```
The for loop iterates to find the test image and remove any other image if present. Removing part uses `{{.Repository}}:{{.Tag}}` and `{{.ID}}` keywords to feed `podman rmi`. First key (Repository:Tag) works fine. However, ID key causes a problem if the test image has been tagged before. 

### What happens?
When a system test (XXX-*.bats) uses default `basic_setup()`, test passes if normal conditions are present. 
The problem occurs if the test image `($IMAGE/$PODMAN_TEST_IMAGE_FQN)` was tagged before as in:
`podman tag $IMAGE same_image_with:new-tag`
Following output can be observed as a result of the failure :
```
# setup(): removing stray images localhost/same_image_with:new-tag 4abe85964f5c
not ok 1 podman info - basic test
# (from function `is' in file helpers.bash, line 417,
#  in test file 005-info.bats, line 26)
#   `is "$output" ".*$expect" "output includes '$expect'"' failed
```

### Root cause
As far as I can trace it, the problem is caused by `run_podman rmi --force "$2" >/dev/null 2>&1 || true` which removes the test image since `run_podman rmi --force "$1" >/dev/null 2>&1 || true` already removed the **new_tag**. 

An improvement can be provided to avoid this case. I have not find a flow that reproduces the problem naturally, yet.

**Comment by aliaslanturk** [comment]
I would like to work on the issue. Due to some obligation, I cannot until early May. If the issue is to be solved, and assigned to me, I am more than happy to do so when I get back.

**Comment by rhatdan** [comment]
I have assigned it to you, I don't think anyone is going to grab it. Lots of other work to be done.
Thanks.

**Comment by rhatdan** [comment]
@edsantiago PTAL

**Comment by edsantiago** [comment]
@aliaslanturk does #10008 address your concerns?

**Comment by rhatdan** [comment]
Since we never heard back, I am going to assume yes, Please reopen if I am mistaken.
