### ISSUE TITLE
dnsmasq plugin is killed for rooted containers when user session is closed

### ISSUE THREAD

**Issue by adamoa** [containers/podman#9931]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

After starting a rooted container over a podman network using sudo, name resolution only works while the session of the user who called sudo is running. This happens because dnsmasq is run under the session of the user who called and not on a slice under machine.slice (like conmon does).

If a rooted container tries to resolve a name of another rooted container on the same network after the session of the user  is closed, it will fail since dnsmasq will be killed by systemd.

I don't believe that for rooted containers this should happen. There is a workaround of enabling lingering at loginctl of every user that could launch podman which is impracticable.

**Steps to reproduce the issue:**

1. Login to a machine.

2. Launch two rooted containers running bash over the same network using sudo (detached).

3. Logout

4. Wait for session cleanup by systemd.

5. Login again

6. Attach to any of the running containers.

7. Try to resolve the name of the other container.

**Describe the results you received:**

The container will not be able to resolve the IP of the other container.

**Describe the results you expected:**

The container should be able to continue resolving IP of other containers.

**Additional information you deem important (e.g. issue happens only occasionally):**

For some reason, dnsmasq is trapped on the user session despite the fact that both containers and network were created using sudo.

**Output of `podman version`:**

Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.8
Built:        Fri Feb 19 13:56:17 2021
OS/Arch:      linux/amd64

**Output of `podman info --debug`:**

host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.26-1.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 777074ecdb5e883b9bec233f3630c5e7fa37d521'
  cpus: 8
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: adampc
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.11.11-200.fc33.x86_64
  linkmode: dynamic
  memFree: 306077696
  memTotal: 16728383488
  ociRuntime:
    name: crun
    package: crun-0.18-4.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.18
      commit: 808420efe3dc2b44d6db9f1a3fac8361dde42a95
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 20601364480
  swapTotal: 21474828288
  uptime: 37m 18.02s
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 6
    paused: 0
    running: 4
    stopped: 2
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 31
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1613753777
  BuiltTime: Fri Feb 19 13:56:17 2021
  GitCommit: ""
  GoVersion: go1.15.8
  OsArch: linux/amd64
  Version: 3.0.1

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

podman-3.0.1-1.fc33.x86_64

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

No (only checked Troubleshooting, but have not found any issues like this nor notes of fix on release notes.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical

**Comment by baude** [comment]
@Luap99 @mheon @giuseppe wdyt? linger is sort of our answer here no?

**Comment by mheon** [comment]
@baude This is for Podman launched as root via sudo, so I don't know if linger is the answer - that's a reasonable response for rootless, but here you'd expect the dnsmasq to run in root's context.

I do think the rearchitecture of dnsmasq we were discussing will resolve this.

**Comment by rhatdan** [comment]
@adamoa Are you still seeing this?

@baude @Luap99 @mheon We sort have left this one hanging,  Any thoughts on fixing.

**Comment by umohnani8** [comment]
@adamoa hi, are you still seeing this issue?

@Luap99 @baude @mheon with the new network stack in the works, do we plan to tackle this? If not, let's close the issue.

**Comment by mheon** [comment]
This is definitely going to be addressed in the new stack.

**Comment by baude** [comment]
netavark and podman 4.x will fix this.

**Comment by baude** [comment]
with aardvark
