### ISSUE TITLE
[pedantic] swagger operation ID nits

### ISSUE THREAD

**Issue by edsantiago** [containers/podman#9951]
Thank you for #9944! It hugely improves consistency in swagger, which is something my `hack/swagger-check` script has sorely wanted to check. I've updated my script to recognize the new operation-name format, and added a bunch of special cases, but I think the following might be actual bugs:

--------------------

https://github.com/containers/podman/blob/f143de9db6861cd8b8d6fc4e03f2826041307982/pkg/api/server/register_containers.go#L777

Shouldn't that be `ContainerShowmountedLibpod`?

--------------
https://github.com/containers/podman/blob/f143de9db6861cd8b8d6fc4e03f2826041307982/pkg/api/server/register_containers.go#L1471-L1472

This one is weird: two consecutive swagger lines, the first one tagged `libpod` but not a `/libpod` endpoint, the second tagged `compat` but with a `/libpod` endpoint. This just looks completely off to me. If it's intentional, just say so, and I'll hardcode an exception.

------------------------

https://github.com/containers/podman/blob/f143de9db6861cd8b8d6fc4e03f2826041307982/pkg/api/server/register_play.go#L11

Going by the rules and conventions, that should be `PlayKube`

**Comment by edsantiago** [comment]
There are also these three which are annoying but I suppose I'll have to special-case:
```
       ContainersStatsAllLibpod
       ImageGetAll
       ImageDeleteAllLibpod
```
(I suppose the `All` is maybe helpful to humans, but it's spurious and arbitrary)

**Comment by jwhonce** [comment]
@edsantiago `All` came in from the compatibility requirements, the idea is those operations are "one or more". OperationIds need to be unique across the API which does lead to some naming weirdness.  #9953 includes all your recommendations.
