### ISSUE TITLE
Endpoint /libpod/manifests/{name:.*}/json response JSON inconsistent

### ISSUE THREAD

**Issue by jwhonce** [containers/podman#9957]
The swagger documentation reports the field name of "MIMEType" while the code returns "mediaType".  This should be corrected. 

Which field name is expected?

**Comment by jwhonce** [comment]
Should be covered in https://issues.redhat.com/browse/RUN-1217

**Comment by rhatdan** [comment]
@jwhonce now that we branched for 4.0 have you had a chance to work on this?

**Comment by vrothberg** [comment]
@jwhonce do you want to tackle it?  4.0 is coming closer

**Comment by vrothberg** [comment]
Ping @jwhonce @baude @rhatdan.  Shall we tackle that before 4.0?

**Comment by rhatdan** [comment]
Yes.

**Comment by rhatdan** [comment]
Well it should be fixed in 4.0
