### ISSUE TITLE
Inconsistencies in Container Wait API documentation

### ISSUE THREAD

**Issue by pablofsf** [containers/podman#9960]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

The HTTP API reference for libpod/containers/{name}/wait at https://docs.podman.io/en/latest/_static/api.html#operation/ContainerWaitLibpod says that the output for `200` is content type `application/json` and of the form:
```
{
    "Error": 
    {
        "Message": "string"
    },
    "StatusCode": 0
}
```
However, when I try on an instance of podman 3.0.1, the reply is a single integer, which seems to me consistent with the code here:
https://github.com/containers/podman/blob/382b5b81d24870abe400d14296e4f5ef47c99d29/pkg/api/handlers/utils/containers.go#L138

Is that possibly a bug in the documentation?

I also realized looking into the `WaitContainerLibpod` function, that there is  an undocumented parameter, `interval`. Should that possibly be documented?

**Comment by rhatdan** [comment]
I think other error codes could come back with strings.  IE If you attempt to wait on a non existent container.

Interval should be documented.

**Comment by pablofsf** [comment]
Thank you for your prompt reply!

> I think other error codes could come back with strings. IE If you attempt to wait on a non existent container.

That is definitely the case, but it seems to me that whenever that is the case, the response is either `404` or `500`:
https://github.com/containers/podman/blob/382b5b81d24870abe400d14296e4f5ef47c99d29/pkg/api/handlers/utils/containers.go#L129-L138

Is there actually a possibility that a `200` reply returns something else than a number? I understand that exitCode there is of type `entities.WairReport.ExitCode`, just formatted as a string. Or am I missing something?

> Interval should be documented.

Ok, thank you!

**Comment by rhatdan** [comment]
No, I don't think the 200 would ever come back with a string.
