### ISSUE TITLE
Podman exec is able to bypass the auditd

### ISSUE THREAD

**Issue by michalkuzma123** [containers/podman#9975]
/kind bug

**Description**
Podman exec is able to bypass the auditd

**Steps to reproduce the issue:**

1. Define rule in audit.rules like this:
`-w path/to/directory/file.env -p r -k something`
2. Run podman container:
```
podman run \
-dt \
-v /path/to/directory:/directory \
--name=something\
--net=host \
ubuntu
```
3. Run `podman exec ID cat directory/file.env`
4. Run `sudo ausearch -i -f /path/to/directory/file.env`

**Describe the results you received:**
Nothing

**Describe the results you expected:**
Entry in auditlog

**Output of `podman version`:**
```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.16.1
Built:        Thu Apr  8 02:24:06 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
  host:
  arch: amd64
  buildahVersion: 1.19.4
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: conmon-2.0.27-1.el8.1.7.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.27, commit: '
  cpus: 8
  distribution:
    distribution: '"centos"'
    version: "8"
  eventLogger: journald
  hostname: host02
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.18.0-240.15.1.el8_3.x86_64
  linkmode: dynamic
  memFree: 14954344448
  memTotal: 16205524992
  ociRuntime:
    name: crun
    package: crun-0.18-3.el8.6.6.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.18
      commit: 808420efe3dc2b44d6db9f1a3fac8361dde42a95
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 1073737728
  swapTotal: 1073737728
  uptime: 3h 44m 57.8s (Approximately 0.12 days)
registries:
    Blocked: false
    Insecure: true
    Location: xxx
    MirrorByDigestOnly: false
    Mirrors: []
    Prefix: xxx.xxx
  search:
  - xxx.xxx
  - xxx.xxx
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 2
    paused: 0
    running: 2
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageStore:
    number: 2
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.0.0
  Built: 1617841446
  BuiltTime: Thu Apr  8 02:24:06 2021
  GitCommit: ""
  GoVersion: go1.16.1
  OsArch: linux/amd64
  Version: 3.0.1
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.0.1-2.el8.3.9.x86_64
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
QEMU

**Comment by mheon** [comment]
This sounds more likely to be a Kernel audit subsystem bug - all we're doing is bind-mounting the path in question into the container. I suspect you could reproduce this without Podman (bind-mount inside a mount namespace).

**Comment by s4s0l** [comment]
But it works for `podman run`. When doing `exec` the `/proc/self/loginuid` seems to be not set.

**Comment by giuseppe** [comment]
are you running the `podman run` command and the `podman exec` from the same session?

**Comment by michalkuzma123** [comment]
> are you running the `podman run` command and the `podman exec` from the same session?

Yes

**Comment by giuseppe** [comment]
can you please show how the `/proc/self/loginuid` is different in the two cases?

Does it work if you change the OCI runtime to `runc`?

**Comment by michalkuzma123** [comment]
I misused ausearch. I should use it like this:
`sudo ausearch -i -f directory / file.env`

Sorry for wasting your time and thanks for your help :smile_cat:
