### ISSUE TITLE
#9615 isn't fixed in 3.1.0 (containers eternally stopping if they do too much stdio in specific circumstances)

### ISSUE THREAD

**Issue by penn5** [containers/podman#9976]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**
Containers stuck in "stopping" state on 3.1.0 (or crash on 3.0.1, #9615)

**Steps to reproduce the issue:**

Sorry the steps are convoluted, I tried to make a simple reproducer but I couldn't get it to work.

1. Clone https://gitlab.com/hackintosh5/riptester
2. pip install -r requirements.txt
3. In another window, `podman --log-level debug system service --time 0`
3. In the first window, `python -m backend`
4. In yet another window, `curl -X POST -H 'X-Api-Token=dff55903-db2c-4fd9-9348-e5fc9b0a599e' http://localhost:8080/v1/exec/python3 -d 'code=while 1:%0A print(0)&stdin='`
These steps always reproduce the issue on my machine (and might be useful for a test of #9615 if someone can work out exactly what is needed to reproduce it).

**Describe the results you received:**
Logs show:
```
INFO[0057] APIHandler(b94dba66-664a-4605-b26c-274ee1b6ffca) -- POST /v1.40/containers/e043f0c64304ba719b2d097ea1a22e215b9e02d7a0cbb13192839b4dc9be8ebf/stop BEGIN 
DEBU[0057] APIHandler(b94dba66-664a-4605-b26c-274ee1b6ffca) -- Header: Accept-Encoding=[gzip, deflate] 
DEBU[0057] APIHandler(b94dba66-664a-4605-b26c-274ee1b6ffca) -- Header: User-Agent=[Python/3.9 aiohttp/3.7.4.post0] 
DEBU[0057] APIHandler(b94dba66-664a-4605-b26c-274ee1b6ffca) -- Header: Content-Length=[0] 
DEBU[0057] APIHandler(b94dba66-664a-4605-b26c-274ee1b6ffca) -- Header: Content-Type=[application/octet-stream] 
DEBU[0057] APIHandler(b94dba66-664a-4605-b26c-274ee1b6ffca) -- Header: Accept=[*/*] 
DEBU[0057] Starting parallel job on container e043f0c64304ba719b2d097ea1a22e215b9e02d7a0cbb13192839b4dc9be8ebf 
DEBU[0057] Stopping ctr e043f0c64304ba719b2d097ea1a22e215b9e02d7a0cbb13192839b4dc9be8ebf (timeout 1) 
DEBU[0057] Stopping container e043f0c64304ba719b2d097ea1a22e215b9e02d7a0cbb13192839b4dc9be8ebf (PID 10736) 
DEBU[0057] Sending signal 15 to container e043f0c64304ba719b2d097ea1a22e215b9e02d7a0cbb13192839b4dc9be8ebf 
INFO[0058] Timed out stopping container e043f0c64304ba719b2d097ea1a22e215b9e02d7a0cbb13192839b4dc9be8ebf, resorting to SIGKILL: given PIDs did not die within timeout 
DEBU[0058] Sending signal 9 to container e043f0c64304ba719b2d097ea1a22e215b9e02d7a0cbb13192839b4dc9be8ebf 
INFO[0063] Request Failed(Internal Server Error): given PIDs did not die within timeout 
DEBU[0063] APIHandler(b94dba66-664a-4605-b26c-274ee1b6ffca) -- POST /v1.40/containers/e043f0c64304ba719b2d097ea1a22e215b9e02d7a0cbb13192839b4dc9be8ebf/stop END 
```
Podman inspect (truncated) shows:
```
        "State": {
            "OciVersion": "1.0.2-dev",
            "Status": "stopping",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 10736,
            "ConmonPid": 10733,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2021-04-08T16:11:37.478418293+01:00",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Healthcheck": {
                "Status": "",
                "FailingStreak": 0,
                "Log": null
            }
        },
```
(note the container is stuck in the stopping state)

**Describe the results you expected:**
Container is stopped cleanly by SIGTERM (Python should exit immediately when it gets a SIGTERM)

**Additional information you deem important (e.g. issue happens only occasionally):**
The issue can't be reproduced unless the application is doing a lot of output - perhaps some internal buffer gets full, deadlocking signals somehow? just speculation.

**Output of `podman version`:**

```
Version:      3.1.0
API Version:  3.1.0
Go Version:   go1.15.8
Built:        Mon Apr  5 15:21:04 2021
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.20.0
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.26-1.fc33.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.26, commit: 777074ecdb5e883b9bec233f3630c5e7fa37d521'
  cpus: 8
  distribution:
    distribution: fedora
    version: "33"
  eventLogger: journald
  hostname: Ferao
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.11.11-200.fc33.x86_64
  linkmode: dynamic
  memFree: 218726400
  memTotal: 7896944640
  ociRuntime:
    name: crun
    package: crun-0.18-5.fc33.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.18
      commit: 808420efe3dc2b44d6db9f1a3fac8361dde42a95
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    selinuxEnabled: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.9-1.fc33.x86_64
    version: |-
      slirp4netns version 1.1.9
      commit: 4e37ea557562e0d7a64dc636eff156f64927335e
      libslirp: 4.3.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.0
  swapFree: 11978137600
  swapTotal: 11984166912
  uptime: 3h 2m 7.75s (Approximately 0.12 days)
registries:
  search:
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - docker.io
store:
  configFile: /home/penn/.config/containers/storage.conf
  containerStore:
    number: 153
    paused: 2
    running: 4
    stopped: 147
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.4.0-1.fc33.x86_64
      Version: |-
        fusermount3 version: 3.9.3
        fuse-overlayfs: version 1.4
        FUSE library version 3.9.3
        using FUSE kernel interface version 7.31
  graphRoot: /home/penn/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 10
  runRoot: /run/user/1000/containers
  volumePath: /home/penn/.local/share/containers/storage/volumes
version:
  APIVersion: 3.1.0
  Built: 1617632464
  BuiltTime: Mon Apr  5 15:21:04 2021
  GitCommit: ""
  GoVersion: go1.15.8
  OsArch: linux/amd64
  Version: 3.1.0
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.1.0-2.fc33.x86_64
```
Installed from https://koji.fedoraproject.org/koji/buildinfo?buildID=1732440 because 3.0.1 (latest version available in Fedora stable) is subject to #9615

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes (troubleshooting is a [dead link](https://github.com/containers/podman/blob/master/cmd/podman/README.md))

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 33 cgroupsv2 rootless

**Comment by penn5** [comment]
Just noticed - the root process of the container becomes a zombie according to procfs. Killing conmon (the parent) with SIGCHLD makes no difference - it just stays asleep.
```
Name:	python
State:	Z (zombie)
Tgid:	12295
Ngid:	0
Pid:	12295
PPid:	12292
```

**Comment by mheon** [comment]
`INFO[0063] Request Failed(Internal Server Error): given PIDs did not die within timeout `

I'm fairly certain this means our zombie is such that even SIGKILL won't get rid of it. At this point, it's out of our hands - Podman can't do anything further about the process since even the kernel can't kill it. If you want to verify by hitting the zombie with a SIGKILL it would be appreciated, but I'm quite sure this is the case.

The Podman bug here is that we aren't moving the container to the `stopped` state. I don't know if we can move to exited (that involved unmounting the container, and we can't do that if the filesystem is in use, and there's a zombie using the filesystem that we can't kill... But we can move to the "stopped" state, which should allow the container to be used again.

**Comment by penn5** [comment]
> `INFO[0063] Request Failed(Internal Server Error): given PIDs did not die within timeout `
> 
> I'm fairly certain this means our zombie is such that even SIGKILL won't get rid of it. At this point, it's out of our hands - Podman can't do anything further about the process since even the kernel can't kill it. If you want to verify by hitting the zombie with a SIGKILL it would be appreciated, but I'm quite sure this is the case.
> 
> The Podman bug here is that we aren't moving the container to the `stopped` state. I don't know if we can move to exited (that involved unmounting the container, and we can't do that if the filesystem is in use, and there's a zombie using the filesystem that we can't kill... But we can move to the "stopped" state, which should allow the container to be used again.

The process is just Python. Moreover, I found a really simple reproducer that might help find the cause of the issue. In any case, the issue is 100% a bug in Podman (or something related) since sending SIGKILL to Python should Just Work :tm: . Will attach my reproducer in a moment.

**Comment by penn5** [comment]
```python
import aiodocker, asyncio

async def main():
    docker = aiodocker.Docker(url="unix:///run/user/1000/podman/podman.sock")
    c = await docker.containers.create({"Image": "python:3", "Cmd": ["python", "-c", "while 1:\n print(1)"], "HostConfig": {"LogConfig": {"Type": "none"}}})
    conn = c.attach(stdout=True)
    await c.start()
    await conn.read_out()
    await conn.close()
    await asyncio.sleep(1)
    await c.kill()
asyncio.run(main())
```
This code will cause process killing to hang forever, despite the process actually being a zombie. The python code is doing nothing more complex than printing "1". My guess is that conmon is waiting until the process has a clean stdout before it cleans up the process, leading to this hang when the reader process hangs up.

**Comment by mheon** [comment]
@haircommander @giuseppe PTAL - this doesn't map to my understanding of how Conmon handles waiting for the container process, but at the same time it does seem like it's not waiting for the process causing it to zombify.

I wonder if we can work around this to a degree in Podman with a pidfd on the container process - we can alter the container stop code to wait off a pidfd instead of polling the process with signal 0. That removes the polling aspect from the current stop code (attractive on its own) and should be more robust against cases like this, where Conmon isn't doing the right thing.

The point I made earlier about Podman not transitioning to Stopped also still holds. This is a case where the zombie seems to be the result of Conmon not acting properly, but there are cases where a process will get sufficiently stuck (uninterruptible I/O sleep for example) that it cannot be evicted at all, and we should try our best to recover from some cases.

**Comment by giuseppe** [comment]
are you able to reproduce it without remote podman?

I am trying something as:

```
$ podman run --rm -ti python:3 python -c "while 1: print(1)"
```

and from another terminal do the `kill -9 $PYTHON_PROCESS_IN_THE_CONTAINER`

the process is correctly reported as terminated and podman terminates.

Does the simpler version work for you?

**Comment by penn5** [comment]
> are you able to reproduce it without remote podman?
> 
> I am trying something as:
> 
> ```
> $ podman run --rm -ti python:3 python -c "while 1: print(1)"
> ```
> 
> and from another terminal do the `kill -9 $PYTHON_PROCESS_IN_THE_CONTAINER`
> 
> the process is correctly reported as terminated and podman terminates.
> 
> Does the simpler version work for you?

I wasn't able to reproduce with cli only, but I don't know why.

**Comment by rhatdan** [comment]
@mheon Any more thoughts on this, Did you make the changes?

**Comment by mheon** [comment]
Nope, not as of present.

**Comment by mheon** [comment]
Would still help to have a Conmon expert look more at this, too.

**Comment by rhatdan** [comment]
@giuseppe @haircommander @mrunalp PTAL

**Comment by penn5** [comment]
Still an issue

**Comment by rhatdan** [comment]
@mheon do you have time to look at this?

**Comment by mheon** [comment]
I can take a look.

**Comment by umohnani8** [comment]
@mheon @haircommander PTAL

**Comment by giuseppe** [comment]
I think this could be solved by https://github.com/containers/conmon/pull/291

Please reopen if it still exists with conmon v2.0.30
