### ISSUE TITLE
Kernel message on container shutdown.

### ISSUE THREAD

**Issue by alitvak69** [containers/podman#9987]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

**Steps to reproduce the issue:**

1. podman pull registry.fedoraproject.org/f29/httpd

2. podman run --rm --name fedora-httpd -dt  -p 8090:8080/tcp registry.fedoraproject.org/f29/httpd

3. podman stop fedora-httpd

**Describe the results you received:**
Message
```bash
kernel: overlayfs: unrecognized mount option "volatile" or missing value
```

**Describe the results you expected:**
No messages should be in kernel.  No volatile mount option set in storage.conf 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

```
Version:      3.2.0-dev
API Version:  3.2.0-dev
Go Version:   go1.15.10
Git Commit:   9ba2e78cdcc28c15d72a76f6200a74e7ad6562b1-dirty
Built:        Mon Dec 31 16:00:00 1979
OS/Arch:      linux/amd64
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.20.1-dev
  cgroupManager: systemd
  cgroupVersion: v1
  conmon:
    package: podman3-xcast-3.2.0-1.x86_64
    path: /opt/podman/bin/conmon
    version: 'conmon version 2.0.27, commit: 65fad4bfcb250df0435ea668017e643e7f462155-dirty'
  cpus: 8
  distribution:
    distribution: '"centos"'
    version: "7"
  eventLogger: journald
  hostname: web3n4-la.siptalk.com
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 4.19.12-1.el7.elrepo.x86_64
  linkmode: static
  memFree: 3996057600
  memTotal: 8363216896
  ociRuntime:
    name: crun
    package: podman3-xcast-3.2.0-1.x86_64
    path: /opt/podman/bin/crun
    version: |-
      crun version 0.19-dirty
      commit: e67a75672412975916dac6b87f8346f870e4b99a
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_AUDIT_WRITE,CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_MKNOD,CAP_NET_BIND_SERVICE,CAP_NET_RAW,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    selinuxEnabled: false
  slirp4netns:
    executable: ""
    package: ""
    version: ""
  swapFree: 4294963200
  swapTotal: 4294963200
  uptime: 12468h 42m 51.9s (Approximately 519.50 days)
registries:
  search:
  - docker.xcastlabs.net
  - docker.io
  - quay.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay2.mountopt: nodev
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "true"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 1
  runRoot: /var/run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 3.2.0-dev
  Built: 315532800
  BuiltTime: Mon Dec 31 16:00:00 1979
  GitCommit: 9ba2e78cdcc28c15d72a76f6200a74e7ad6562b1-dirty
  GoVersion: go1.15.10
  OsArch: linux/amd64
  Version: 3.2.0-dev
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
Selfbuilt rpm
```

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Centos 7.x, Qemu VM.  I tried released version 3.1 and it produces the same kernel message.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
How many times do you see that message in the log?

If it is just once then it is the test performed by containers/storage to verify whether volatile is supported.  Since it is not supported on the centos 7 kernel then it won't be used

**Comment by alitvak69** [comment]
After some cleaning it looks like messages appear after container stops.  Older versions of podman didn't trigger the same messages.

```console
Apr 27 00:13:51 web3n3-la.siptalk.com systemd[1]: Couldn't stat device /dev/char/10:200
Apr 27 00:13:51 web3n3-la.siptalk.com podman[5123]: 2021-04-27 00:13:51.5655328 -0700 PDT m=+0.348990503 container init b6a8743d39fa61a7a9c2f85950856ccaea9fdbcbf6e0263d3fe895f779c3a870 (image=docker.io/library/httpd:latest, name=httpd)
Apr 27 00:13:51 web3n3-la.siptalk.com podman[5123]: 2021-04-27 00:13:51.579013087 -0700 PDT m=+0.362470789 container start b6a8743d39fa61a7a9c2f85950856ccaea9fdbcbf6e0263d3fe895f779c3a870 (image=docker.io/library/httpd:latest, name=httpd)
Apr 27 00:13:51 web3n3-la.siptalk.com conmon[5234]: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 10.88.0.4. Set the 'ServerName' directive globally to suppress this message
Apr 27 00:13:51 web3n3-la.siptalk.com conmon[5234]: AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 10.88.0.4. Set the 'ServerName' directive globally to suppress this message
Apr 27 00:13:51 web3n3-la.siptalk.com conmon[5234]: [Tue Apr 27 07:13:51.623960 2021] [mpm_event:notice] [pid 1:tid 139803225207936] AH00489: Apache/2.4.46 (Unix) configured -- resuming normal operations
Apr 27 00:13:51 web3n3-la.siptalk.com conmon[5234]: [Tue Apr 27 07:13:51.624153 2021] [core:notice] [pid 1:tid 139803225207936] AH00094: Command line: 'httpd -D FOREGROUND'
Apr 27 00:14:09 web3n3-la.siptalk.com kernel: overlayfs: unrecognized mount option "volatile" or missing value
Apr 27 00:14:09 web3n3-la.siptalk.com conmon[5234]: [Tue Apr 27 07:14:09.349462 2021] [mpm_event:notice] [pid 1:tid 139803225207936] AH00492: caught SIGWINCH, shutting down gracefully
Apr 27 00:14:10 web3n3-la.siptalk.com kernel: overlayfs: unrecognized mount option "volatile" or missing value
Apr 27 00:14:10 web3n3-la.siptalk.com podman[5353]: 2021-04-27 00:14:10.454556691 -0700 PDT m=+1.197140372 container stop b6a8743d39fa61a7a9c2f85950856ccaea9fdbcbf6e0263d3fe895f779c3a870 (image=docker.io/library/httpd:latest, name=httpd)
Apr 27 00:14:10 web3n3-la.siptalk.com podman[5353]: 2021-04-27 00:14:10.486997307 -0700 PDT m=+1.229580953 container died b6a8743d39fa61a7a9c2f85950856ccaea9fdbcbf6e0263d3fe895f779c3a870 (image=docker.io/library/httpd:latest, name=httpd)
Apr 27 00:14:10 web3n3-la.siptalk.com kernel: cni-podman0: port 1(vethd2d04f68) entered disabled state
Apr 27 00:14:10 web3n3-la.siptalk.com kernel: device vethd2d04f68 left promiscuous mode
Apr 27 00:14:10 web3n3-la.siptalk.com kernel: cni-podman0: port 1(vethd2d04f68) entered disabled state
Apr 27 00:14:10 web3n3-la.siptalk.com podman[5397]: 2021-04-27 00:14:10.671749165 -0700 PDT m=+0.279814016 container remove b6a8743d39fa61a7a9c2f85950856ccaea9fdbcbf6e0263d3fe895f779c3a870 (image=docker.io/library/httpd:latest, name=httpd
```

**Comment by rhatdan** [comment]
When a podman container is stopped or exits, conmon gathers the exit code and then executes `podman container cleanup`.  This program cleans up the network stack and storage stack.  Since it is launching podman, podman loads container/storage.  When container/storage overlay driver is inited, it checks the for what options are available in the kernel for mounting.  It does this by actually setting up different mount points and mounting, and seeing what fails.  In this case it checks the volatile mount.  Since volatile mount is not supported on Centos 7, the kernel reports in it's logs that volatile is not supported.  This is nothing we can do to fix this.

**Comment by alitvak69** [comment]
@rhatdan and @giuseppe Thank you for a good explanation.

**Comment by mheon** [comment]
Per @giuseppe this is not a bug, but Podman searching for supported mount
options. The several second delay does not sound like it is expected.

**Comment by alitvak69** [comment]
[Tue May 11 03:04:25 2021] overlayfs: unrecognized mount option "volatile" or missing value
[Tue May 11 07:42:11 2021] overlayfs: unrecognized mount option "volatile" or missing value
[Tue May 11 07:42:14 2021] overlayfs: unrecognized mount option "volatile" or missing value
[Tue May 11 07:42:26 2021] overlayfs: unrecognized mount option "volatile" or missing value
[Tue May 11 07:42:38 2021] overlayfs: unrecognized mount option "volatile" or missing value
[Tue May 11 07:42:42 2021] overlayfs: unrecognized mount option "volatile" or missing value
[Tue May 11 07:42:49 2021] overlayfs: unrecognized mount option "volatile" or missing value
[Tue May 11 07:43:18 2021] overlayfs: unrecognized mount option "volatile" or missing value

**Comment by alitvak69** [comment]
```
root@container5-la:~# time podman ps
CONTAINER ID  IMAGE                                              COMMAND               CREATED       STATUS           PORTS   NAMES
e960fd2103aa  docker.xcastlabs.net/services/bind-host:1.17       /entrypoint           4 days ago    Up 4 days ago            dns-slave-internal
e2bfe971f02d  docker.xcastlabs.net/services/bind-host:1.17       /entrypoint           4 days ago    Up 4 days ago            dns-slave-public
f2c1f905744b  docker.xcastlabs.net/services/bind-ng:1.25         /entrypoint.sh        4 days ago    Up 4 days ago            dns-public-master
a5e1b87fce3e  docker.xcastlabs.net/utility/foreman-proxy:latest  /preinit              11 days ago   Up 11 days ago           foreman-proxy
88be856c13d9  docker.xcastlabs.net/dale/cdr-reputation:latest    -run -debug -no-t...  3 weeks ago   Up 3 weeks ago           cdr-reputation-57bdb587-74d5-416d-d5b0-dce1e89c2704
8c0d9bed6193  docker.io/jippi/hashi-ui:latest                    /hashi-ui             4 weeks ago   Up 4 weeks ago           hui-la2-la-edb6acd6-6fa7-315b-ce74-5f2fd837247f
03c0146f1f3e  docker.io/fabiolb/fabio:latest                     -cfg /etc/fabio/f...  4 weeks ago   Up 4 weeks ago           fabio
d648c9bb7afa  docker.xcastlabs.net/utility/squid-shaper:latest   /preinit              4 weeks ago   Up 4 weeks ago           squid-shaper
7a07e8c99727  docker.io/timberio/vector:latest-debian                                  4 weeks ago   Up 4 weeks ago           vector-journald
3e71324626ae  docker.xcastlabs.net/sbc/sbc2msteams:1.4           /entrypoint.sh        2 months ago  Up 2 months ago          sbc2teams2-la2
758d602f5369  docker.xcastlabs.net/sbc/pbx2msteams:1.2           /entrypoint.sh        2 months ago  Up 2 months ago          pbx2teams2-la2
639be1608cf3  docker.io/galexrt/healthchecks:latest              app:run               5 months ago  Up 5 months ago          healthchecks
7a3c317d4d8d  docker.xcastlabs.net/utility/superset:latest                             5 months ago  Up 5 months ago          superset
85418ac0b5ae  docker.xcastlabs.net/services/bind-host:latest     /entrypoint.sh        5 months ago  Up 5 months ago          dns

real    0m0.196s
user    0m0.192s
sys     0m0.102s
root@container5-la:~# podman -v
podman version 2.1.1
```
and

```
root@container2-la:/opt/podman/bin# time podman ps
CONTAINER ID  IMAGE   COMMAND  CREATED  STATUS  PORTS   NAMES

real    0m1.309s
user    0m1.305s
sys     0m0.091s
root@container2-la:/opt/podman/bin# podman -v
podman version 3.1.2
```

**Comment by ericzolf** [comment]
I've also been bitten by this error message, on CentOS 8 Stream; I understand that you've got other things to address but any spurious error makes the troubleshooting of real errors more difficult, for admins as for any support person. I would kindly ask to reconsider the decision, it did cost me time to come to this issue and find out that the message isn't after all an error.

**Comment by rhatdan** [comment]
What error message are you talking about?  Just the debug messages that talk about volatile?

**Comment by alitvak69** [comment]
```
overlayfs: unrecognized mount option "volatile" or missing value
```
This message shows because storage code check support for volatile regardless if this option exists in storage.conf.  But some other options are only checked if they exist in the file. For example, I have:
```
mountopt = "nodev,metacopy=on"
```
If I put metacopy instead of metacopy=on, I would see
```
overlayfs: unrecognized mount option "metacopy" or missing value
```
I am not sure if there is a reason to always check for volatile mount option if it doesn't exist among the mount options.

**Comment by giuseppe** [comment]
yes `volatile` doesn't have to specified in the mountopts but it is checked anyway and used for a certain class of containers that podman knows will be removed once they are terminated.

How are you running podman?  The result of the `volatile` check is cached and the mount attempted only once

**Comment by rhatdan** [comment]
I think the complaint is that every time they run podman it adds a line.

**Comment by ericzolf** [comment]
Correct, without any mean to know that it can be ignored. If the message can be cached, can't it be dropped as well?

**Comment by alitvak69** [comment]
I am still not getting any explanation but I wonder if seeing a lot of log entries is related to this.  I.e. even if I use 3.1.2 podman attempts to use volatile storage.
#### From 3.2.0 RC2 release notes.
Containers created with the --rm option now automatically use the volatile storage flag when available for their root filesystems, causing them not to write changes to disk as often as they will be removed at completion anyways. This should result in improved performance.

**Comment by alitvak69** [comment]
I upgraded to 3.2.0-RC2 and with new version of storage library the behavior is much more reasonable. It requests volatile on --rm and only one time on start.  BTW, the volatile overlay option was only added in kernel 5.10 so perhaps I get to enjoy some time next year after 22.04 released.  @giuseppe and @rhatdan Thank you for your work.
