### ISSUE TITLE
Please add arg “--pidfile” for supporting to get container process pid from file

### ISSUE THREAD

**Issue by chenk008** [containers/podman#9992]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Please add arg “--pidfile”.   Write the pid of the **container** process to a file. 

I start my worker porcess in container which created by `Podman run`, and want to get the container process pid. I will save the pid in `struct map`. I have tried the NOTIFY_SOCKET, but it always return conmon process pid.

How about add  arg “--pidfile” in Podman cli?

**Comment by rhatdan** [comment]
Interested in opening a PR to add this feature?

**Comment by chenk008** [comment]
> Interested in opening a PR to add this feature?

@mheon @rhatdan  I am glad to opening a PR  for it.

**Comment by rhatdan** [comment]
Go for it.
