### ISSUE TITLE
Ubuntu rootless podman cp / fails to stat cgroups file

### ISSUE THREAD

**Issue by cevich** [containers/podman#9997]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

PR #9905 enables rootless testing under cgroupsV2 enabled Ubuntu 2010 (with `crun`).  During one particular CI run, [this failure mode was observed](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/5313776456040448/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-cp-the-root-directory-from-the-ctr-to-an-existing-directory-on-the-host--1).  It seems to me, that the behavior or `cp` may be incorrect: Is it ***ever*** reasonable to copy a cgroups virtual file from inside a container to the host?   

**Steps to reproduce the issue:**

1. Execute rootless CI testing on Ubuntu 2010

2. Repeat (possibly a billion times) until this failure occurs :cry: 

**Describe the results you received:**

```
           podman cp the root directory from the ctr to an existing directory on the host 
           /var/tmp/go/src/github.com/containers/podman/test/e2e/cp_test.go:214
         
         [BeforeEach] Podman cp
           /var/tmp/go/src/github.com/containers/podman/test/e2e/cp_test.go:26
         [It] podman cp the root directory from the ctr to an existing directory on the host 
           /var/tmp/go/src/github.com/containers/podman/test/e2e/cp_test.go:214
         Running: podman [options] run --name copyroottohost -d quay.io/libpod/alpine:latest top
         b1f46c239b73b8e07fcfe08a03054eae512a841c5b0553e3e0cff67aa40a3292
         Running: podman [options] exec copyroottohost touch /dummy.txt
         Running: podman [options] cp copyroottohost:/ /tmp/212797057
         Error: 1 error occurred:
         	* error copying from container: copier: get: "/"("/"): copier: get: error reading "/sys/kernel/slab/dentry/cgroup/dentry(45891:podman-240179.scope)": lstat /sys/kernel/slab/dentry/cgroup/dentry(45891:podman-240179.scope): no such file or directory
         [AfterEach] Podman cp
           /var/tmp/go/src/github.com/containers/podman/test/e2e/cp_test.go:36
         Running: podman [options] stop -a --time 0
         b1f46c239b73b8e07fcfe08a03054eae512a841c5b0553e3e0cff67aa40a3292
         Running: podman [options] pod stop -a -t 0
         Running: podman [options] pod rm -fa
         Running: podman [options] rm -fa
         b1f46c239b73b8e07fcfe08a03054eae512a841c5b0553e3e0cff67aa40a3292
         
         

         • Failure [6.807 seconds]
         Podman cp
         /var/tmp/go/src/github.com/containers/podman/test/e2e/cp_test.go:19
           podman cp the root directory from the ctr to an existing directory on the host  [It]
           /var/tmp/go/src/github.com/containers/podman/test/e2e/cp_test.go:214
         
           Expected
               <int>: 125
           to equal
               <int>: 0
```

**Describe the results you expected:**

All tests should pass

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `podman version`:**

[Details available here](https://cirrus-ci.com/task/5313776456040448?logs=package_versions#L0)

**Output of `podman info --debug`:**

[Details available here](https://cirrus-ci.com/task/5313776456040448?logs=package_versions#L0)

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

[Details available here](https://cirrus-ci.com/task/5313776456040448?logs=package_versions#L0)

**Have you tested with the latest version of Podman and have you checked the Podman Troubleshooting Guide?**

Yes

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Possibly only happens on Ubuntu 2010 w/ Kubic "testing" packages installed.

**Comment by cevich** [comment]
@vrothberg you worked on the "cp crossing mountpoint boundry" thing.  I'm wondering if this issue is (somehow) a consequence of that?  Specifically - suggesting why this only happens in Ubuntu and never Fedora.

Also, I'm wondering if perhaps a "easy" solution could be to make "podman cp" always skip trying to read `/proc`, `/sys`, and `/dev` inside the container.  I can't think of any reason why directories down those trees would ***ever*** be useful to copy to any other context.

What's your take?

**Comment by vrothberg** [comment]
@cevich thanks for the ping. We exclude these directories already (see https://github.com/containers/podman/blob/master/libpod/container_copy_linux.go#L156) so I am not sure what's going on.

@nalind, do you have a suspicion why `/sys/kernel/slab/dentry/cgroup/dentry` may be read during copy?  May very well be a bug in how I used `buildah/copier` in https://github.com/containers/podman/blob/master/libpod/container_copy_linux.go#L156.

**Comment by cevich** [comment]
FWIW: I tried but wasn't able to reproduce this by-hand on the same Ubuntu VM image.  To confirm, I tried directly copying `/sys/kernel/slab/dentry/cgroup` to the host as root and as a user, both resulted in (expected) not copying anything.  Then I tried executing the specific test that failed, but it passed :disappointed: So there's certainly some kind of race here.

**Comment by nalind** [comment]
Re-running the command where the test fails with debugging enabled tells us more: we still descend into excluded directories, in case something below needs to be included anyway, as an exception.  It might make sense to either filter out `IsNotExist()` errors entirely, or make doing so something we control with a flag, or see if https://github.com/containers/buildah/pull/3143 would help.  If you have a preference, give a holler and we can incorporate it into the `copier` package.

**Comment by cevich** [comment]
>  containers/buildah#3143

I don't think that will help the podman integration test failure which prompted me to open this...unless we also update that test to use the option.  However I'm afraid doing that could hide bugs/problems we otherwise would want to know about :confused: 

I think the `IsNotExist()` filter is probably  the easiest way to go...but I'm not the expert.

**Comment by nalind** [comment]
To be clear, ignoring `IsNotExist()` errors would be something we do down `copier.Get()` when it encountered this error, otherwise you'd have to start the whole `Get()` call over.

**Comment by cevich** [comment]
FWIW: Here's [a new example](https://storage.googleapis.com/cirrus-ci-6707778565701632-fcae48/artifacts/containers/podman/6726212807557120/html/int-podman-ubuntu-2010-rootless-host.log.html#t--podman-cp-the-root-directory-from-the-ctr-to-an-existing-directory-on-the-host--1), same issue.  This is blocking https://github.com/containers/podman/pull/9905 in case I didn't mention that.

**Comment by rhatdan** [comment]
@cevich Any progress on this?

**Comment by cevich** [comment]
@rhatdan None that I'm aware of.  I'd fix it myself if I weren't so afraid of breaking something :fearful: I was hoping @nalind or @vrothberg knew the proper incantation to twiddle.

**Comment by cevich** [comment]
> To be clear, ignoring IsNotExist() errors would be something we do down copier.Get()

I ogled buildah's `copier.go` function `copierHandlerGet()` [where the error appears to come from](https://github.com/containers/buildah/blob/master/copier/copier.go#L1169).  Poking around here and in podman, I can say for certain this is definitely not something I would try to fix w/o (probably) days of free time.

I do wonder though, if maybe a `os.IsNotExist(err)` check to skip the file, might be the wrong approach.  Since copying a dangling symlink to another container or to the host seems ripe to cause all kinds of trouble (esp. if it's not dangling in the destination context).  So if the source item is a dangling symlink in the source, wouldn't it be safer to "copy" an empty file to the destination instead?

**Comment by nalind** [comment]
`os.Lstat()`, when pointed at a symlink, only looks at the symlink.  It's only when the symlink is itself something that we're told to read (compared to, say, being a symlink somewhere beneath a directory that we were pointed to) that we bother following it.

**Comment by cevich** [comment]
Ahh okay, thanks for the explanation.  That's why the podman test is be failing, since it's pointed at `/`, I get it now.  I Still have no clue how to fix it though :grinning:

**Comment by cevich** [comment]
@nalind looking at this code more, I got a simple idea:  Can't we just [throw a warning here instead of an error](https://github.com/containers/buildah/blob/master/copier/copier.go#L1170)?

Reason:  My understanding (could be wrong) is the purpose of this loop is to catch items not already in `queue`, but that should be included because they link to something inside the context for copying.  If the `lstat()` fails, presumably the copy (later) will also fail (and ***hopefully*** be ignored?).  Therefor simply informing the user there is possibly a problem following a link, should be good enough.

An alternative idea is we just ignore the failure.  Allow the future copy to fail (harmlessly?), and (possibly) don't even increment `followedLinks`.

WDYT?

**Comment by nalind** [comment]
Pretty sure the error is returned from [here](https://github.com/containers/buildah/blob/d78dfd1d7b2c7d1040cdadf44b60417a637f8887/copier/copier.go#L1190).  Unless `/sys/kernel/slab/dentry/cgroup/dentry`, or a symlink that points to it, or a glob that expands to name it, is being directly passed to us as the thing to copy, the loop that includes line 1170 isn't going to be called with it.

**Comment by cevich** [comment]
Actually I'm going to disagree (maybe sticking my foot in my mouth).  And I think there's potential here for a TOCTOU race (obtaining info, then copying stuff).  Anyway, the error message was this:

`error copying from container: copier: get: "/"("/"): copier: get: error reading "/sys.../dentry(45891:podman-240179.scope)": lstat /sys/.../dentry(45891:podman-240179.scope): no such file or directory`

That looks to me to resemble the format `copier: get: lstat %q(%q)`.  That was my (naive reasoning) :grinning: 

No?

Also, I see if we just ignore this on 1170 it will result in `info = nil` which doesn't seem to be handled.

**Comment by cevich** [comment]
How about: https://github.com/containers/buildah/pull/3210

**Comment by cevich** [comment]
Ya, I'm more convinced the race occurs because the file goes "poof" (or permissions change or whatever) in between the `path, err := os.Readlink(item)` and `if info, err = os.Lstat(item); err != nil` calls.  Which also explains why timing and i/o load is so critical to reproducing it (something our CI seems *too* good at sometimes :face_with_head_bandage: ).

**Comment by nalind** [comment]
There's no space for text between "get:" and "lstat" in [this error message](https://github.com/containers/buildah/blob/d78dfd1d7b2c7d1040cdadf44b60417a637f8887/copier/copier.go#L1170).  The parentheses in the error message are part of the path name, and not part of the error format specifier we provide; the text inside of them isn't quoted, which the "%q" format specifier would request.

Since Go 1.13 or so, `os.Lstat()` returns errors as `os.PathError` values, which is where the "lstat: $filename: $errnoText" part of the error message is coming from.

**Comment by cevich** [comment]
> There's no space for text between...Since Go 1.13 or so

Oh.  Well...err...that's why I (normally) avoid dabbling in these things (and maintain very, very, very clean and tasty feet) :smirk: 

I still think there's a TOCTOU here somewhere...crap in `/sys` and `/proc` can certainly change at any time w/o warning.

**Comment by cevich** [comment]
Right...okay ya, you're right.  I see it now.  1190 does fit...hmmm, so [does 1251 no?](https://github.com/containers/buildah/blob/master/copier/copier.go#L1251)

**Comment by nalind** [comment]
That would be part of the call stack, yes.  So in `copier`, does it make sense to either filter out `IsNotExist()` errors entirely, or make doing so something we control with a flag?

**Comment by cevich** [comment]
Ya, that's why I was thinking a warning + skip the file (or dir) might be good enough.  At least in this specific case, the file would not have been copied anyway (being cross-device).  I'm still a bit afraid of unintended consequences though.  Like printing a warning might still mess up the tests (we can make them filter for this known behavior).

**Comment by cevich** [comment]
There is precedent for printing a warning and ignoring the problem:  `tar` does this with something like: "Warning: File 'foo' disappeared while reading".

**Comment by cevich** [comment]
Maybe something like 

```diff
diff --git a/copier/copier.go b/copier/copier.go
index 8f6821c31..b16c07f8d 100644
--- a/copier/copier.go
+++ b/copier/copier.go
@@ -1186,6 +1186,9 @@ func copierHandlerGet(bulkWriter io.Writer, req request, pm *fileutils.PatternMa
                                                                return filepath.SkipDir
                                                        }
                                                        return nil
+                                               } else if os.IsNotExist(err) {
+                                                       logrus.Warningf("copier: file disappeared while reading: %q", path)
+                                                       return nil
                                                }
                                                return errors.Wrapf(err, "copier: get: error reading %q", path)
                                        }
```

**Comment by cevich** [comment]
Sigh...maybe we need this too just to be safe:

```diff
@@ -1241,6 +1244,9 @@ func copierHandlerGet(bulkWriter io.Writer, req request, pm *fileutils.PatternMa
                                        if err := copierHandlerGetOne(info, symlinkTarget, rel, path, options, tw, hardlinkChecker, idMappings); err != nil {
                                                if req.GetOptions.IgnoreUnreadable && errorIsPermission(err) {
                                                        return ok
+                                               } else if os.IsNotExist(err) {
+                                                       logrus.Warningf("copier: file disappeared while reading: %q", path)
+                                                       return nil
                                                }
                                                return err
                                        }
```

**Comment by rhatdan** [comment]
:+1: I think that is a good idea.

**Comment by cevich** [comment]
Great, thanks for the feedback.

**Comment by rhatdan** [comment]
@cevich Has this been fixed?

**Comment by cevich** [comment]
It was a race-condition so kind of hard to be certain, but yes it "should" be fixed.
